### ISSUE TITLE
Logging mechanism

### ISSUE THREAD

**Issue by huneau** [wekan/wekan#1001]
As refer here : #107 , I would like to log info over different services.

Usecase : I move a card A on board 'B' from list 'L1' to list 'L2'

Wekan -> log manager -> file/DB/...

I would like to use that https://github.com/winstonjs/winston, I will bind this logger with that https://docs.meteor.com/api/collections.html#Mongo-Cursor-observeChanges, which observe the data meteor collection in real time.

After that, you can imagine to send info into kafka or redis or mongo or what you want. And let dev make their own stats.

If your are agree with that I start tomorrow.

**Comment by xet7** [comment]
@huneau 

Yes I agree. Submit pull request to meteor-1.4 branch.
