### ISSUE TITLE
Uncaught Error: Cannot find module 'xss'

### ISSUE THREAD

**Issue by prawee** [wekan/wekan#1004]
<img width="493" alt="screen shot 2560-04-14 at 7 30 27 pm" src="https://cloud.githubusercontent.com/assets/3203937/25043273/e7a9a0c6-2148-11e7-9f19-e56d0e816910.png">

**Comment by stephenmoloney** [comment]
Please document the steps taken to build/run wekan including any versions, etc.

**Comment by timt** [comment]
Same problem after doing this:

    curl https://install.meteor.com/ | sh
    git clone https://github.com/wekan/wekan.git
    cd wekan
    meteor


All starts up find and get the message
    => App running at: http://localhost:3000/

But get the error above in the browser

**Comment by stephenmoloney** [comment]
have you tried the installing from source guide?

`https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source`

**Comment by timt** [comment]
And then I ran this:

    meteor npm install --save xss  

And now it all works

**Comment by Digital-Thor** [comment]
Thanks for posting your solution @timt!  I was having the same problem.

**Comment by xet7** [comment]
When you download binary tar.gz release of Wekan, you can start it with command meteor, there no need to build dependencies from source then.
