### ISSUE TITLE
Admin Panel Issues

### ISSUE THREAD

**Issue by valqk** [wekan/wekan#1011]
I hope I'm not duplicating this issue, but I didn;t find any.
There are some problems I've noticed for admin panel page:
- When I click Admin page link I'm redirected to /setting but not to /wekan/setting (link address is incorrect when ROOT_URL is not / )
- When I click Save I don't get any message it's been saved
- When I try to invite existing email, I get exception in console, but nothing happens in UI. Exception is: Exception in callback of async function: Error: Email must be unique [invitation-generated-fail] at models/settings.js:138:21

**Comment by NoodleBB** [comment]
Point 1: This is that one: #973

**Comment by valqk** [comment]
3. sorry. didn't formatted the exception code. (edited). It's not #923 

> Exception in callback of async function: Error: Email must be unique [invitation-generated-fail] at models/settings.js:138:21
It happens if I've already have such email as active user.

**Comment by NoodleBB** [comment]
Maybe you could post your first point in #973 , so that's clear that you're an "_participant_" of that bug.

**Comment by nztqa** [comment]
> When I click Admin page link I'm redirected to /setting but not to /wekan/setting (link address is incorrect when ROOT_URL is not / )

Fix https://github.com/wekan/wekan/pull/1084


> When I click Save I don't get any message it's been saved

The bug can't be reproduced.

> When I try to invite existing email, I get exception in console, but nothing happens in UI. Exception is: Exception in callback of async function: Error: Email must be unique [invitation-generated-fail] at models/settings.js:138:21

No problem. 
If you want a message on the screen please create a new issue.

@xet7 Please close this issue
