### ISSUE TITLE
Checklist Item empty : impossible to delete

### ISSUE THREAD

**Issue by phylophyl** [wekan/wekan#1013]
It is impossible to delete an item in a checklist when created empty. I am using Wekan on Sandstorm.

**Comment by nztqa** [comment]
TEST: Sandstorm app demo.
No problem.
![wekan_checklist_delete-iloveimg-compressed](https://user-images.githubusercontent.com/22808079/27570249-a7f8e7f6-5b37-11e7-824a-a9eb4e89f5c8.gif)
