### ISSUE TITLE
Pre-configuration wekan-autoinstall

### ISSUE THREAD

**Issue by phylophyl** [wekan/wekan#1014]
In the  README.md file of wekan-autoinstall, it is possible to edit particularly ROOT_URL
it is not explained if once ROOT_URL is edited, the following line has to be edited as well in the script:

181 /sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print $2 }'

Wekan auto-installation script link:
https://github.com/wekan/wekan-autoinstall

**Comment by xet7** [comment]
@phylophyl 

Please create issue to:
https://github.com/wekan/wekan-autoinstall/issues
