### ISSUE TITLE
Wrong links for card's images

### ISSUE THREAD

**Issue by jetnet** [wekan/wekan#1015]
hello Wekan developers!

since this is my first post here, I'd like to thank you guys for your work, effort and time you putting into the project!
ok, let's start with a trivial issue :)
If wekan is configured to run in a sub-folder, e.g. `export ROOT_URL='https://server.com/wk'`, then images, uploaded to cards, cannot be displayed correctly. The reason is a wrong URL path - the sub-folder is being added twice, .e.g. `https://server.com/wk/wk/<id>`.
As a workaround I currently use a simple rewrite in Nginx:
```
    location /wk {
        proxy_pass http://127.0.0.1:3000;
        rewrite ^(/wk/wk)/(.*)$ /wk/$2 last;
       ...
```
Would be great to get is fixed!
Thank you!

**Comment by NoodleBB** [comment]
Seems to be also this one: #973

**Comment by xet7** [comment]
@nztqa 

Is this already fixed?

**Comment by xet7** [comment]
Ok.
