### ISSUE TITLE
Unable to change language

### ISSUE THREAD

**Issue by mo-han** [wekan/wekan#1018]
_Newly installation with empty MongoDB._

version: 0.18
node version: 0.10.48

All other features seem good, but I just can't change language by clicking in the "Member Settings" menu. Browser console says `Uncaught Error: language does not exist`.

However it's alright to change the language of log-in UI.

Thought this issue was already fixed before. Anyone has the same issue or knows the reason?

**Comment by xet7** [comment]
It's fixed on:
- newest Docker version:
https://github.com/wekan/wekan-mongodb
- install from source:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source

There will be new release sometime.

I don't know is it useful to fix older releases.

**Comment by mo-han** [comment]
@xet7 

Have tried version 0.16 without discovering this issue, and versions ever since 0.11.0 until 0.18 do not have this issue if I remember correctly. Maybe the new codes cause it again?
