### ISSUE TITLE
Invitation code field is missing when registering form inv. mail

### ISSUE THREAD

**Issue by valqk** [wekan/wekan#1019]
I've sent an email with invitation code.
User opened the wekan signup form and didn't had any invitation code field, but when tried to register, he got message 'invitation code is required'.
I've inspected the page code and invite code field was there, but with display:none
Maybe the code had to be appended to the link that should be opened (and filled in in hidden field)?
Anyway, this is showstopper when trying to invite new users (and self registration is disabled).

**Comment by khagedorn** [comment]
Workaround:

* Open registration page using the link from the email
* On the registration-page, click on the login-link beneath the form fields
* When you're on the login-page, navigate back to the registration page using the register-link beneath the form fields
* Tadaa: the registration code form field is now visible

I don't understand Meteor code, but it could be related to the following fragment in `client/components/settings/invitationCode.js`
```
Template.invitationCode.onRendered(() => {
  const setting = Settings.findOne();
  if (!setting || !setting.disableRegistration) {
    $('#invitationcode').hide();
  }
});
```

**Comment by khagedorn** [comment]
And isn't this the same bug as in #993 ?

**Comment by valqk** [comment]
@khagedorn Indeed it's a duplicate, just the test case was a little bit different and didn't found it. Closing this one.
