### ISSUE TITLE
Custom Fields, moving card on mobile phone and filter cards by keyword, integration with RIOT (http://riot.im/) so user can be notified immediately on cell phone while Wekan cards have changed.

### ISSUE THREAD

**Issue by mfshiu** [wekan/wekan#1022]
How to allow login in multiple clients e.g. login mobile phone and desktop at the same time.

**Comment by xet7** [comment]
@mfshiu 

1) Does it not work? Do you get some error message?

2) Is Wekan installed on your own laptop/desktop, or remote server?

**Comment by xet7** [comment]
Works for me.

**Comment by mfshiu** [comment]
Can you post again? I miss the answer. Thanks.

**Comment by mfshiu** [comment]
Is Wekan installed on your own laptop/desktop, or remote server? 
In remote server for production
In my Windows for development

**Comment by xet7** [comment]
@mfshiu 

When Wekan is installed to some web address, like http://something , you can login to that URL from multiple devices at the same time: desktop, mobile, etc when using that same URL. If you make change on one device like desktop, you will then see change on other devices like mobile etc immediately after that change.

Is this what you did mean?

Or does something not work?

**Comment by xet7** [comment]
@mfshiu 

If you want to access Wekan in local LAN or in the Internet, you need to have your http port 80 or https port 443 open, so other computers can access that server.

It's also possible to use same database and have both LAN and VPN users access it https://github.com/wekan/wekan/issues/1210 .

Or do you have some problems when logging in with multiple devices? Please explain with more detail so I understand better :)

**Comment by mfshiu** [comment]
After trying current Wekan, I found the current Wekan 0.50 is work, it can support to login for multiple clients.
But my Wekan is started from 0.10 that has no such feature, client will be kick-off while the same account is login. 
It's hard to merge my Wekan to 0.50, can you let me know how to add multiple-login feature to old version Wekan?

**Comment by ocdtrekkie** [comment]
@mfshiu That version of Wekan is nearly two years old. You are going to have a LOT of problems if you aren't planning on updating to the current version of Wekan. There are not only a lot of bugs and security issues in older versions, but you're missing major features.

**Comment by xet7** [comment]
@mfshiu 

Backup your Wekan 0.10 MongoDB database with:

```
mongodump
```

Restore it to Wekan 0.50 MongoDB with:

```
mongorestore --drop
```

If you use Docker, see:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

For other Docker settings, see:
https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

If you have any errors, please add your error messages to this GitHub issue.

**Comment by xet7** [comment]
Wekan compatible Node.js, MongoDB etc versions are mentioned at Dockerfile:
https://github.com/wekan/wekan/blob/devel/Dockerfile

**Comment by mfshiu** [comment]
Thank you very much. I am trying to merge my old Wekan to version 0.50.

**Comment by mfshiu** [comment]
I have already developed some not bad features to my Wekan, like custom fields, moving card on mobile phone and filter by keyword. I will try to update to Wekan and make some contribution.

**Comment by xet7** [comment]
@mfshiu 

Currently also @papoola is developing Custom Fields feature.
https://github.com/wekan/wekan/wiki/Roadmap

I hope you have time to contribute your features, so others don't end up developing the same features.

Thanks! :)

**Comment by xet7** [comment]
@mfshiu 

I added your features to [Roadmap](https://github.com/wekan/wekan/wiki/Roadmap). Thanks!

**Comment by mfshiu** [comment]
I will take some time to do. It's my pleasure.

**Comment by xet7** [comment]
@mfshiu 

What are the features of your Custom Fields vs these https://github.com/wekan/wekan/issues/807#issuecomment-336591782 ?

**Comment by mfshiu** [comment]
I know why my Wekan cannot do multiple login.
I monkey-patch accounts loginWithPassword of accounts-apssword package to do LDAP login, that cause this problem, although I still don't know why.
Now I try to register login handler to complete the LDAP login feature, and my Wekan can multiple login again.

**Comment by xet7** [comment]
@mfshiu 

There is existing working LDAP  code at https://github.com/wekan/wekan/issues/119#issuecomment-287597821 but it's not integtated to Wekan yet. You could look does it or your code have more features. LDAP is very highly requested feature for standalone Wekan, it would be very to have.

**Comment by xet7** [comment]
LDAP configuration should be done with environment variables before starting Wekan.

**Comment by mfshiu** [comment]
Thanks for your suggestion. I will take time to make the LDAP package for Wekan.

**Comment by xet7** [comment]
@mfshiu 

Can you come to Vanila Chat and send me private message, so we can discuss about progress and sponsoring of these features?

https://chat.vanila.io/channel/wekan
