### ISSUE TITLE
export / backup

### ISSUE THREAD

**Issue by rawwerks** [wekan/wekan#1024]
we use the sandstorm implementation. it would be great to have a way to back up the wekan grain, in case someone accidentally deletes content from the wekan board, or we want to reset it for some reason.

**Comment by ocdtrekkie** [comment]
The owner of a Sandstorm grain can download a backup of the grain from the top bar. I definitely would like to see an automated version at some point of this feature though. You can also back up the entire Sandstorm server, and probably restore the grain contents in the file system, but that would likely be hacky and somewhat unsupported.

ping @kentonv

**Comment by ocdtrekkie** [comment]
I'd propose closure of this issue because it's a Sandstorm issue, not a Wekan issue. Related issues are:

https://github.com/sandstorm-io/sandstorm/issues/1324
https://github.com/sandstorm-io/sandstorm/issues/1647
