### ISSUE TITLE
Change URL in Project description

### ISSUE THREAD

**Issue by AmrEldib** [wekan/wekan#1027]
[https://wekan.io](https://wekan.io) leads to a "Your connection is not secure" error. Please change URL to [https://wekan.github.io/](https://wekan.github.io/) which is used on the [Twitter](https://twitter.com/WekanApp) page.

**Comment by xet7** [comment]
@AmrEldib 

Ok, I have now changed repo url to https://wekan.github.io

Twitter page has url http://wekan.io that redirects correctly to https://wekan.github.io

I have asked @mquandalle does can he update https://wekan.io SSL cert sometime.
