### ISSUE TITLE
Zulip logger: more descriptive log messages

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1028]
@huneau 

When Wekan starts, your zulip logger additions add text "here1 false". Could there be more descriptive text instead, so it's easier to know that they are related to zulip logger, and what those messages mean?

**Comment by huneau** [comment]
Hi,

I'm sorry this is a debug message from serveur/logger.js

(I'm at a wedding, I can't help right now)

**Comment by xet7** [comment]
@huneau 

Please enjoy wedding first, it's more important of course :)

**Comment by huneau** [comment]
https://github.com/wekan/wekan/blob/devel/server/logger.js#L11
https://github.com/wekan/wekan/blob/devel/server/logger.js#L12
https://github.com/wekan/wekan/blob/devel/server/logger.js#L14

This is lines to remove.

**Comment by xet7** [comment]
Fixed by https://github.com/wekan/wekan/pull/1033
