### ISSUE TITLE
Avatar doesn't load 

### ISSUE THREAD

**Issue by mathuin** [wekan/wekan#1030]
I have a small PNG file I use for an avatar.  It's 80x80, 8-bit RGB, and 13k in length.  I have attached the image to this issue.

When I upload it to Wekan using the change avatar setting, the app throws up a bar saying the application is currently offline, then a moment later that goes away and the change avatar page shows that an avatar was uploaded but the image is broken.  I had previously set my initials in the config, but I don't know if that matters.

![wheestoli](https://cloud.githubusercontent.com/assets/221823/25776496/6520d18c-3274-11e7-9d2e-55238d1acde4.png)

**Comment by Nefeth** [comment]
If you are on mongo 3.4 then you need to downgrade it to 3.2 as there is an issue between mongo 3.4 and meteor framework.
The description of your issue match that issue

**Comment by Nefeth** [comment]
There is even a note here on how to do the downgrade of mongo with keeping your data

**Comment by mathuin** [comment]
Downgrading to MongoDB 3.2 did address this issue, so I will close it.  Thank you!

**Comment by 1kidvidiot** [comment]
This will break other apps running on UCS so it appears wekan is not compatible now

**Comment by xet7** [comment]
You need to resize avatar to for example 300x300px and then upload avatar. Or if you have some existing other avarar size, resize to that size.

Wekan can not break any other apps in UCS, Wekan is at separate Docker container, and is not integrated to other UCS apps.

**Comment by xet7** [comment]
Anyway, I will test this.

**Comment by xet7** [comment]
@1kidvidiot 

How it would beak other UCS apps? Please give more details how to reproduce step by step, screenshots etc.

**Comment by xet7** [comment]
Bigger avatar images should work now.
