### ISSUE TITLE
Security flaws introduced by REST-API

### ISSUE THREAD

**Issue by mayjs** [wekan/wekan#1032]
It seems like the REST-API does currently not have any authorization features. This introduces severe security flaws. For example anyone can now get a list of all registered users using this request: `GET /api/users`. Using any users id given in the resulting list, we can now see the full user object using another GET-Request: `GET /api/users/:user_id`. The object returned here also contains the password hash, which is obviously not good.

The worst part about this seems to be the ability to delete any users account: `DELETE /api/users/:user_id`. The same problem also applies to lists, though I'm not sure if it is possible to receive the ids of every list.

Unless I'm getting something wrong, V0.22 is really not suited for production use because of these problems. I realize that the REST-API is far from finished, but I think a warning about these issues should be given in the release notes.

**Comment by xet7** [comment]
@huneau 

Please add authentication your REST API code to fix this security issue. Thanks!

**Comment by mayjs** [comment]
As a quick follow up: Maybe it would be better to use a more sophisticated library for handling the REST API. `restivus` seems to allow to easily create an authentication endpoint for password authentication. It also seems to allow for a pretty quick integration of a simple REST-API offering good functionality.

**Comment by huneau** [comment]
@xet7 done!

@mayjs I take the easiest way for me to create an API, I haven't the knowledge on `Meteor` to use `restivus`.

**Comment by mayjs** [comment]
Alright, #1033 fixes the vulnerabilities described here, so I will close this issue.
