### ISSUE TITLE
npm install bcrypt    bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz  does not exist

### ISSUE THREAD

**Issue by qq383762126** [wekan/wekan#1035]
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz    

This file does not exist

**Comment by xet7** [comment]
That is problem on kelektiv's repo, there is no binary download version of that dependency available. I do not have any write permissions to kelektiv's repo and downloads of kelektiv's releases.

In Wekan, bcrypt is built from source, and bcrypt/bson error fixed here:

## 1) Source install:
https://github.com/wekan/wekan/wiki/Install-and-Update#in-production
these lines:
```
sed -i "s|build\/Release\/bson|browser_build\/bson|g" .build/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/ext/index.js
cd .build/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt
rm -rf node_modules/bcrypt
npm install bcrypt
```

## 2) Docker container's Dockerfile, links:
https://github.com/wekan/wekan/blob/devel/Dockerfile#L109
https://github.com/wekan/wekan/blob/devel/Dockerfile#L110
https://github.com/wekan/wekan/blob/devel/Dockerfile#L111
https://github.com/wekan/wekan/blob/devel/Dockerfile#L112

Those links are to this source code:
```
gosu wekan sed -i "s|build\/Release\/bson|browser_build\/bson|g" /home/wekan/app_build/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/ext/index.js && \
cd /home/wekan/app_build/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt && \
gosu wekan rm -rf node_modules/bcrypt && \
gosu wekan npm install bcrypt && \
```
