### ISSUE TITLE
URL error for card

### ISSUE THREAD

**Issue by rickywu** [wekan/wekan#1036]
I created card under Kanban, but the link of card direct to http://mytodo/b/* and nginx shows 404 error

If I correct the link in new window then I can open it, where is the problem?

I install follow this link https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by rickywu** [comment]
my yml is like this
`wekandb:
  image: mongo
  volumes:
    - /home/wekan/data:/data/db

wekan:
  image: mquandalle/wekan
  links:
    - wekandb:db
  ports:
    - 8080:80
  environment:
    - MONGO_URL=mongodb://db
    - ROOT_URL=http://mytodo.com`

and my nginx.conf is like this
`    upstream websocket {
        server 127.0.0.1:8080;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen       80;
        server_name  mytodo.com;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        access_log  /var/log/nginx/access.80.log;
        error_log   /var/log/nginx/error.80.log;

        location / {
            proxy_read_timeout      300;
            proxy_connect_timeout   300;
            proxy_redirect          off;

            proxy_set_header    Host                $http_host;
            proxy_set_header    X-Real-IP           $remote_addr;
            proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto   $scheme;
      
            proxy_pass http://127.0.0.1:8080;
        }

        location ~ websocket$ {
           proxy_pass http://websocket;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection $connection_upgrade;
        }

    }
`

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Platforms

**Comment by xiaohelong** [comment]
in virtualbox images 0.49 version,I modified /home/wekan/repos/run-wekan.sh ROOT_URL to my ip,then restart ,it's ok then.
