### ISSUE TITLE
Card descriptions that cannot be edited

### ISSUE THREAD

**Issue by David-LeBlanc-git** [wekan/wekan#1038]
I am using version 0.22.
Today I discovered the following:

When I change an existing description or add a description to a card in the format of **[text]: text** - the description element will disappear and cannot be edited for the life of the card.

I originally tried putting **[Occurrence]: Weekly** and noticed that the description disappeared and could not be edited. Then I was able to reproduce the same behavior with any text in the similar format.

**Comment by xet7** [comment]
That's normal markdown in Wekan description. This is how you can make link in markdown, that below is list on links in markdown format:

```
[Wekan website][wekan]

[wekan]: https://wekan.github.io
```

But if you add this kind of "list of links" in markdown:

```
[Occurrence]: weekly
```

It then hides that list of links, and you did not provide the markdown required to display link text.

**Comment by David-LeBlanc-git** [comment]
Thank you for the explanation
