### ISSUE TITLE
Invalid mardown in Card description prevents future edits to Card description

### ISSUE THREAD

**Issue by David-LeBlanc-git** [wekan/wekan#1039]
As originally posted in issue #1038 - I discovered a scenario where a description can no longer be edited on a card.

If you have the following form of invalid markdown in a description on a card - there is no way of editing the card to correct it or to completely change it. The only solution for large cards is to restore the database for a time before it was entered or to modify it manually using a collection update in mongodb.

**[Text]: Text**

The above is clearly incorrect markdown - but there is no way to correct this within the UI.

**Comment by xet7** [comment]
Thanks  :+1: I can reproduce this now! I did not know it was possible to do this!

It needs to be fixed sometime so that when this happens, it's possible to click Description to edit the invisible description.

**Comment by xet7** [comment]
It seems that Details text should be made to work the same as Edit below it, at:
https://github.com/wekan/wekan/blob/devel/client/components/cards/cardDetails.jade#L49-L74

@rhelsing 

Do you know how to fix this? You changed that file during this year.

**Comment by xet7** [comment]
@GhassenRjab 

You can also look if you have time.
