### ISSUE TITLE
Implementing Wekan Design in my personal project

### ISSUE THREAD

**Issue by kubenstein** [wekan/wekan#1044]
Hi,
Im developing my own trello-like side project. As a developer i focus mostly on a technical aspect of it but maybe i will publish the project one day. I know there were storms going on around your project about copyrights and stuff. I would like to know if current Wekan design is free from any issues from Trello and if i can use part of the design to implement UI in my project?
I noticed that Wekan is MIT licensed but i want to double check and be sure.
Thank you so much.

**Comment by ocdtrekkie** [comment]
There are no known issues with Trello at the present time. (There was a long time ago, but it was resolved before this project was even called Wekan.)

**Comment by kubenstein** [comment]
thank you for quick answer, im really glad no issues were submitted by Trello. So the last question:
Is Wekan Design covered by Wekan MIT license?

**Comment by ocdtrekkie** [comment]
As far as I personally know, I don't think there's any claims beyond the MIT license covering the repository. "Wekan" as a brand/name might be trademarked, but I don't see a mark for that. Maybe @mquandalle could answer.

Out of curiosity, is there some reason Wekan itself doesn't meet your Trello-like needs?

**Comment by kubenstein** [comment]
thank you, I craft trello like board just to practice React, and because i cant design myself but enjoy elegant designs (and prefer not to mirror Trello one) i wanted to ask if using Wekans for my personal little pet project will be ok for everyone.

**Comment by xet7** [comment]
@kubenstein

Yes it is OK by MIT license.

There are some React related issues #299 #480 #953 we welcome pull requests for, if someone has time for them.

**Comment by xet7** [comment]
Designs related issue at #781
