### ISSUE TITLE
Activity user messed up when creating a card using the REST-API

### ISSUE THREAD

**Issue by mayjs** [wekan/wekan#1045]
I noticed that the REST-API endpoint for adding cards to a list seems to generate activities with invalid user ids.
To reproduce this issue, it is sufficient to create a card using the API-Endpoint `POST /api/boards/:boardId/lists/:listId/cards` with appropriate JSON in the requests body.
While the membership of the user is generated correctly, the user for the activity seems to be set to an invalid or empty ID. This results in a buggy display:
![wekan_add_card_bug](https://cloud.githubusercontent.com/assets/5578376/26328390/14f02754-3f43-11e7-8297-2502637db9df.png)
I suspect the `Cards.after.insert` hook used to create the activities is missing the userId for some reason.

**Comment by mayjs** [comment]
@huneau Are you still active on this project?
@xet7 any idea how we can set the current user in the REST-API in order to get this fixed? I am kind of stuck on this right now.

**Comment by huneau** [comment]
Hi, 
@mayjs I'm looking notifications and I respond when I can. 
Otherwise, I've got a coworker that work on this project (don't know his pseudo).

Anyway, I transfer this issues to my coworker, because he will probably impact.

**Comment by xet7** [comment]
@mayjs 

I have not yet looked at REST-API code with great detail yet so coworker of @huneau most likely is more up-to-speed on this.

**Comment by zarnifoulette** [comment]
Hi, 

I fix the issue. I did a pull request.
