### ISSUE TITLE
No log file (need to troubleshoot mail)

### ISSUE THREAD

**Issue by djswagerman** [wekan/wekan#1049]
I run wekan under apache using passenger. I understand the standardlocation of the log file is /var/log/wekan.log. The logfile is not there.

Ultimately i need the logfile to be able to troubleshoot mail. I can send mail from the box using the command line command 'mail -s'. I configure sending email from the wekan server using smtp-config.js in the server folder with the following content:

Meteor.startup(function () {
    smtp = {
        username: 'wekan',
        password: '',
        server:   'localhost',
        port: 25
    }

    process.env.MAIL_URL = 'smtp://' + encodeURIComponent(smtp.username) + ':' + encodeURIComponent(smtp.password) + '@' + encodeURIComponent(smtp.server) + ':' + smtp.port;
    Accounts.emailTemplates.from = 'Wekan <wekan@...>';
});

I see in my mail log file, that wekan sends the email,

Log from wekan looks likes this:
... sendmail[13423]: v51N62vV013421: to=<...>, delay=00:00:00, xdelay=00:00:00, mailer=esmtp, pri=120475, relay=.... [130.144.57.170], dsn=5.7.1, stat=Service unavailable

From the command line it look likes this:
...sendmail[15523]: v51NMAJb015523: to=<...>, ctladdr=<myuserid> (myuserid/myuserid), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=30234, relay=... . [], dsn=2.0.0, stat=Sent (Ok: queued as 54A6E3902B)

Any hints appreciated, both for the lack of logfile and the config of email

Best regards,
Dirk-Jan

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by djswagerman** [comment]
Hi Lauri,

I saw that, but then we are back to my 1st issue: which is: i do not have the log file.

Appologies for posting two issues in one questions, that was confusing.

Best regards,
Dirk-Jan

**Comment by xet7** [comment]
@whodafly

Do you have hints for this? You made that troubleshooting wiki page.

**Comment by whodafly** [comment]
I use the Docker image, so I don't actually know where the log file is located. According to the code, there's a "logs" directory somewhere, and that will contain one or more log files. I'm not a NodeJS or Meteor developer, so I can't say anything more than that.

As for your e-mail, it looks like WeKan is successfully talking to your mail server, but there's something that is incorrectly set up. Perhaps the To address is wrong? Or the From address? I'm no mail expert either, but that "Service unavailable" tells me WeKan is able to send the mail to your SMTP server but there might be an error either in the mail or how the mail server is set up.

**Comment by xet7** [comment]
Docker log commands:
https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-for-testing#show-mails-with-a-docker-image-without-mail-configuration

**Comment by djswagerman** [comment]
Thanks for pointers! I was able to finally resolve the issue by making a change to the SMARTHOST in my sendmail.mc.
