### ISSUE TITLE
[UX Bug] Sidebar expand/collapse state is not preserved

### ISSUE THREAD

**Issue by neandrake** [wekan/wekan#105]
I understand the UI/UX is being evaluated for redesign soon, but I found this mildly annoying. Perhaps this could be fixed instead of waiting for redesign.
### Test
1. Create or open a board
2. Ensure the sidebar is collapsed/hidden.
3. Create a new card or view an existing one. If a new card is created, you must then click it to open its full view in the overlay.
4. Close the card overlay.
### Result

The sidebar will expand.
### Notes
1. Clicking the star icon by the board name will also cause the sidebar to expand.
2. Refreshing the page also causes the sidebar to expand.
3. System: OS X 10.10 / Firefox 35

**Comment by neandrake** [comment]
Perhaps I should've re-organized the Test/Notes, as the sidebar expanding is more frequent when viewing and closing cards - refreshing the page and favorting boards are not as frequent actions on a board.

**Comment by mquandalle** [comment]
See also #58.

**Comment by xet7** [comment]
Fixed already.
