### ISSUE TITLE
Open card on mytodo.org...

### ISSUE THREAD

**Issue by Kahji** [wekan/wekan#1051]
Hi.

I just installed Wekan 3hours ago, and everything works fine... Expect one thing, when i click on a card, i'm redirect on mytodo.org...

![2017-06-02_13h31_43](https://cloud.githubusercontent.com/assets/25056916/26724237/9fd477b4-4798-11e7-8ed9-d1c1c51e8767.png)

I followed the guide to install Wekan on production with Docker on the website. I don't know how i can change the value.
I didn't find any topic on this issue.

Thank for your answer.

**Comment by xet7** [comment]
Can you add what Wekan wiki pages you used for install?

Newest links are on Wekan wiki Platforms page. I have not had time to cleanup and remove all old duplicate instructions that may not be up-to-date.

**Comment by Kahji** [comment]
I used this page : 

https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by xet7** [comment]
Try these. For me it works with wekan-mongodb compose script and Caddy webserver.

https://github.com/wekan/wekan-mongodb

https://github.com/wekan/wekan/issues/985

https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by KhaledMohamedP** [comment]
How did you install Waken. Try modifying the ROOT_URL before running the app

```
export ROOT_URL='https://example.com'
```

**Comment by xet7** [comment]
In wekan-mongodb above you need to change docker-compose.yml to have correct ROOT_URL like above, or like this, where ever you have setup wekan:

```
export ROOT_URL='https://example.com/wekan'
```

**Comment by Kahji** [comment]
Hello, thank you for your reply.

I tried to change the docker-compose.yml as you request and it works;)
Next time, I'll look for more ...

Thanks guys!
