### ISSUE TITLE
Board export not working

### ISSUE THREAD

**Issue by nebulade** [wekan/wekan#1055]
At least since version 0.22 the export menu item for a board does not seem to be doing anything. According to the webinspector there is no href nor any even attached to the dom element, but I might just not fully understand how it is patched up. Just tried v0.23 and it has still the same behavior. There is nothing in the webinspector logs nor on the server side from what I can tell.

Any ideas how to debug this further? Thanks.

**Comment by xet7** [comment]
@nebulade 

For individual changes to files, look at:

```
git diff oldrepo/file1 newrepo/file1
```

Going back in time into previous git tag in git history:

```
git checkout tags/v0.22
```

For seeing in newest version who has changed file and what lines:

```
git blame filename
```

When you know who has made those changes, look at git history viewer like gitk about changes between 0.22 and current version, of the person that is on git blame line.

You can also see with gitk all other changes that have happened between 0.22 and now.

Thanks!

**Comment by nebulade** [comment]
So in 0319bcf7bb090328e67766234723f5986c00bba2 it got commented and apparently never reenabled.

**Comment by xet7** [comment]
@nebulade 

Can you uncomment it and submit as pull request?

**Comment by xet7** [comment]
To devel branch

**Comment by xet7** [comment]
Actually, @huneau can you look at this? It looks like this got disabled when you added REST API changes at https://github.com/wekan/wekan/pull/1003

**Comment by huneau** [comment]
yes, I disable it, because of path. You can probably choose a tmp path ?

**Comment by xet7** [comment]
@huneau 

What path do you mean? Where in code?

**Comment by xet7** [comment]
@huneau 

Try to use some other path, tmp path or something elso so exporting board still works.
