### ISSUE TITLE
davos grains are now read only

### ISSUE THREAD

**Issue by deckspace** [wekan/wekan#1056]
Hi today a couple of us were collaborating on some work using the davos filesharing app.. but as the day went on more and more files became read only. One of the collaborators experienced problems after attempting to reconnect to the shared directory using the own-cloud client. Once reconnected, instead of a top up synchronization the system proceeded in reloading all the files. perhaps it was during this process that the files were effected? 

any ideas what may be going on.. ? log attached

**Comment by ocdtrekkie** [comment]
Are you referring to https://github.com/mnutt/davros ? Because this issue doesn't sound like it has anything to do with Wekan.

**Comment by deckspace** [comment]
oh hell sorry

**Comment by ocdtrekkie** [comment]
It sounds like this might be your issue: https://github.com/mnutt/davros/issues/87
