### ISSUE TITLE
Which version of Node.js?

### ISSUE THREAD

**Issue by fnordware** [wekan/wekan#1057]
On the [Install and Update](https://github.com/wekan/wekan/wiki/Install-and-Update) page in one section it says "currently Version 0.10.48 is required" of Node.js, and that we "need node version 0.10.48". But then later in the Install and Build Wekan section I see that it says "Install Node.js 4.8.1".

Which version should we use? Is 0.10.48 the earliest version, but later ones will work as well?

**Comment by xet7** [comment]
4.8.1 only, because 6.x have 100% CPU usage bug.

Thanks, I fixed to wiki.
