### ISSUE TITLE
Question: each iteration with an index

### ISSUE THREAD

**Issue by ittaiyam** [wekan/wekan#1058]
Hi,
I tried multiple variations, and I'm not sure anymore. But how do you include an index in a each loop?
I tried this:
```
each card,index in results.get
  if index >= offset.get && index < offset.get + 5
    a.minicard-wrapper.js-minicard
      +minicard(card)
```

But I get this error when meteor is updating:

> => Errors prevented startup:
> 
>    While processing files with mquandalle:jade (for target web.browser):
>    client/components/boards/boardHeader.jade: Jade syntax error: Expecte                                                                                                                                   d identifier, number, string, boolean, null, or a sub expression enclose                                                                                                                                   d in "(", ")"
>    {{#if index >= offset.get && ind...

Also `@index` doesnt work for me, what am I missing?

**Comment by GhassenRjab** [comment]
Relate to the first option of the accepted answer
https://stackoverflow.com/questions/19052539/get-both-the-key-and-the-index-using-jade-iteration
You should create your own index
