### ISSUE TITLE
Export board menu not visible on some boards

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1060]
@nebulade @huneau 

After merging https://github.com/wekan/wekan/pull/1059 I noticed on my Wekan differences between boards on the same Wekan+MongoDB instance:

On one of my boards Export is not visible:

![export-bug1](https://user-images.githubusercontent.com/15545/27026845-d60fd608-4f67-11e7-8d10-474db0fc4600.png)

And elsewhere on other boards it is visible:

![export-bug2](https://user-images.githubusercontent.com/15545/27026867-ec177d20-4f67-11e7-97b6-946d76508f6d.png)

Do yo have any idea how to fix this?

**Comment by huneau** [comment]
I'm looking in my pull request changes files, I see nothing about this menu : 
https://github.com/wekan/wekan/pull/1003/files
I continue to find in my changes.

**Comment by GhassenRjab** [comment]
"Change color", "Export board" and "Archive Board" menu entries appear only for the admin of the board

**Comment by xet7** [comment]
I am admin user in Wekan installed locally, and other boards have Export visible and one of the boards does not have those visible, as shown in those images above.

**Comment by nztqa** [comment]
Check database value.
```
# Find userId
db.users.find({username:"username"},{_id: 1})

# Find members
db.boards.find()
```
![image](https://user-images.githubusercontent.com/22808079/27462862-aded15b0-57fe-11e7-87e1-91ee67a2e672.png)

**Comment by xet7** [comment]
@nztqa 

Thanks!

I used [Robo 3T](https://robomongo.org)  to find my username's userId

```
db.getCollection('users').find({username: "xet7"})
```

Then I found board where I am not admin yet:

```
db.getCollection('boards').find({members: {$elemMatch: { userId: "MY-USER-ID-HERE", isAdmin: false} } })
```

And changed it to true.

**Comment by lime918** [comment]
hi @xet7, which command did you use to update the isAdmin value?

**Comment by xet7** [comment]
@lime918 

I used some MongoDB command, I don't remember anymore.

You can also use REST API to change member role on board:
https://github.com/wekan/wekan/wiki/REST-API-Role

**Comment by mklooss** [comment]
just for the searching folks:
This Value have also be true ;-) while your staring wekan

https://github.com/wekan/wekan/blob/master/start-wekan.sh#L28
