### ISSUE TITLE
Add Cloudron as possible installation target

### ISSUE THREAD

**Issue by nebulade** [wekan/wekan#1065]
Hi there,

would it be possible to add Cloudron as one of the installation options at https://github.com/wekan/wekan/wiki/Install-and-Update#installing-a-new-instance-of-wekan ?

Cloudron is a self-hosting platform with a focus on app installation and keeping them up-to-date. Our wekan package page is https://cloudron.io/store/io.wekan.cloudronapp.html and the package development happens at https://git.cloudron.io/cloudron/wekan-app

We try to follow upstream closely and also added basic selenium tests to ensure automatic app updates are working and data migration is good. If possible we also try to contribute back, for example https://github.com/wekan/wekan/pull/1059 

Our app packaging contains a few custom patches to fit the ldap integration. Hopefully we can get the ldap integration upstreamed at some point as well.

Please let me know how the process works to update the wiki, if you agree to have us listed.

Thanks.

**Comment by ocdtrekkie** [comment]
I am not a maintainer, but I don't see why you couldn't add sections on that page for Installing and Updating directly below the relevant Sandstorm versions. (Sandstorm should probably be listed above probably solely because it is currently the recommended distribution for certain needs like integration with corporate LDAP or ADFS schemes. I know Cloudron provides it's own LDAP, but I do not recall if it can connect to existing corporate authentication schemes.)

Direct support of LDAP in Wekan (see #119) is actually a really big longstanding request, by the way, if that was something you were able to upstream, you would probably have a lot of fans from the Wekan community. ;)

**Comment by ocdtrekkie** [comment]
It's a pretty community-oriented project over here, as long as your edit is nice and clean, you should just be able to edit the wiki.

**Comment by nebulade** [comment]
Thanks. I added it now. Please change it to your liking if you are not happy with it.

**Comment by xet7** [comment]
@nebulade 

Yes, anyone with GitHub account can freely edit Wiki to keep it up-to-date, add more platforms, etc.

I really have not used all platforms where Wekan could possibly run.

Selenium tests, data migration and LDAP support are welcome as pull requests. You could also have platform-specific environment variables for Cloudron similarly as there is currently for Sandstorm, I don't see any reason to keep those in separate fork.

**Comment by xet7** [comment]
@nebulade 

Wekan often breaks because there is no tests that check pull requests automatically.

**Comment by ocdtrekkie** [comment]
Looks great, @nebulade !

**Comment by nebulade** [comment]
> Selenium tests, data migration and LDAP support are welcome as pull requests. You could also have platform-specific environment variables for Cloudron similarly as there is currently for Sandstorm, I don't see any reason to keep those in separate fork.

So far I think we have managed to never require Cloudron specific flags inside any app code and I hope we can continue to do that. Those variations just add maintenance burden to the upstream project often hard to test by everyone. From what I can tell if I get some spare time to prepare the ldap part all our local patches (like remove signup/password change/...) can easily go away. I would like that, but can't promise some time line when I get around to do that :-)
