### ISSUE TITLE
Add feature : Have a personnal board wich is connected with all my others boards

### ISSUE THREAD

**Issue by ckiltolier** [wekan/wekan#1068]
Hi !

I don't know if the idea has already been mentionned, but it would be great if we had a personnal board connected to all of our projects board. And everytime you say you handle something in a project board, it appears in your personnal board.

The filters of your personnal board would be the name of the projects.

I don't know if it's possible to do it ?

What do you think about it ?

**Comment by xet7** [comment]
You can use REST API:
https://github.com/wekan/wekan/issues/1037

This issue is related to #878 #753 #211

**Comment by ckiltolier** [comment]
Don't know how to use an API for now, looks like i'm gonna learn it ;)

**Comment by sirup** [comment]
Sorry - how can the API help for doing that task? Can you give some quick instructions?
Thank you,

**Comment by xet7** [comment]
Install Wekan with Docker, for example:
https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

[Use Huginn of Flogo to call API](https://github.com/wekan/wekan/issues/1160)

[REST API Docs](https://github.com/wekan/wekan/wiki/REST-API)

There will be [some new REST API features](https://github.com/wekan/wekan/pull/1296) in next release of Wekan.

**Comment by sirup** [comment]
As I can see so far this is mainly for manipulating users? Is there a way to get for example all cards from a users with e.g. a specific label? Then I could get all cards from all users with label "SUPER board". Afterwards it would be cool to create a new board, create new columns and create new cards with the API? Could only find this: http://fusion.github.io/wekanapi/
For getting data, but not for commiting new data?

**Comment by sirup** [comment]
With Rest API #1037 I was able to connect to my Wekan DB.
However, it seems the Rest API is more designed to create/manage users. I could not figure out the following:
 - Is it possible to get the labels (or more information about the cards than only title, id, description)?
 - Is there and if so, what is the Rest API path for CREATING new cards?

Thank you...

(My aim is: I want people to work on their boards, but set a label (or something in the title if not possible) in cards for task which are very important. We than have a "meta" board, which includes all the important tasks of the team. So on one view we can have all important tasks of the whole team.

**Comment by xet7** [comment]
@sirup 

There is [REST API Docs](https://github.com/wekan/wekan/wiki/REST-API) and [Python client to REST API](https://github.com/wekan/wekan-python-api-client) but I did not look at all features yet.

@huneau @mayjs 

Do you know answer to this?

**Comment by xet7** [comment]
There is Linked Boards and Linked Cards feature in progress https://github.com/wekan/wekan/pull/1592
