### ISSUE TITLE
Enhanced logging information

### ISSUE THREAD

**Issue by neandrake** [wekan/wekan#107]
It looks like the log file consists of only some caught exceptions dumped to a file. The following would be a good start to enhancing the logging for better value. I would suggest utilizing an existing node/npm logging framework which can provide most all of these.
1. Add timestamps - there's currently no way of determining when a problem happens.
2. Add some level of logging - such as INFO, WARN, ERROR, DEBUG, etc.
3. Log file rolling - when the log files get too large they are renamed and a new one is created. Log files typically have some threshold for being deleted - usually a policy along the lines of, "1 MB log file, up to 10 log files".

**Comment by mquandalle** [comment]
Are you talking about server-side logs? Normally meteor handle timestamping for us, so we can just use JavaScript default `console.log`, `console.warn`, etc. Currently we don't have such call (apart for the migrations), so we need to figure out the kind of events we want to log (DDP connections, database operations, other indicators?).

**Comment by neandrake** [comment]
Sorry, yes I was referring to server-side logs, specifically the log file specified in the build script:
```
LOG="$APP/libreboard.log"
```

Looking in this log I found several exceptions, but could not determine when they happened or their severity. I'm not familiar with the meteor framework, so maybe something just needs configured in that case.

Some specific events that I would like to see logged, along with errors:
1. Service starting (include starting parameters, like port #).
2. Service stopping

**Comment by xet7** [comment]
See logging features at https://github.com/wekan/wekan/wiki/Features
