### ISSUE TITLE
Ubuntu 14.04 Install Guide

### ISSUE THREAD

**Issue by vClouds** [wekan/wekan#1083]
As long as starting from v0.19 wekan is built on Ubuntu 14.04 LTS
Please update step-by-step install guide or update the auto-install script.
The most annoying part is nodejs when it comes to install node-gyp fibers and forever on a matter of permissions whatever installing as root or others!
Thanks

**Comment by xet7** [comment]
[In-progress local install of npm modules etc](https://github.com/wekan/wekan/wiki/Install-source-without-sudo-on-Linux)
