### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by pnizet** [wekan/wekan#1088]
Hi EveryOne,
As I didn't have the opportunity to get a VPS and has the installation of wekan on my small and old Synology NAS failed, I installed wekan on my windows laptop.
The aim of this install is to use this tool for myself only and to continuously run the app.

And the fact is that I notice quite a huge RAM consumption, the app when it is on with not much activity, is around 400MB of RAM.
Is it normal ?
Is there anyway way to reduce it ?

Many thanks

PS : Is there somebody who manage to install it on a synology NAS (so old that it doesn't support docker) ? 
is there somebody who would like to share a piece of server with me ?

**Comment by xet7** [comment]
@pnizet 

How you did install Wekan to your Windows laptop?

How much RAM is in your laptop?

**Comment by xet7** [comment]
@pnizet 

Does you synology NAS have x64 processor?

**Comment by pnizet** [comment]
@xet7 
I followed the wiki tutorial for windows https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows and I get onyl 4GB of RAM

My NAS is not a x64...

**Comment by xet7** [comment]
@pnizet

On Windows, are you using these compatible versions with Wekan? Because for example Node.js 6.x causes 100% CPU usage.
- Node.js 4.8.1
- NPM 4.6.1
- fibers 1.0.15
- MongoDB 3.2.14

Wekan uses Meteor framework that currently works on x64.
It does not work yet on Raspberry Pi #1053 etc ARM processors, that would need some more research and work.

**Comment by pnizet** [comment]
I have to correct versions 

Do you think that those 400MB are "normal" ?

**Comment by xet7** [comment]
Yes, I don't know how to reduce memory usage.

**Comment by nztqa** [comment]
See also https://forums.meteor.com/t/how-to-increase-decrease-node-js-memory-limits-using-meteor/34355/5

**Comment by ripclaw** [comment]
Was wondering if Wekan would work OK on the [UDOO X86 Ultra](http://www.seco.com/misk/UDOO_X86_datasheet.pdf) SBC ?? It is a quad core Pentium N3710 2.56GHz with 8GB RAM.
(I am pretty sure it would work fine in the [UDOO Bolt](https://www.kickstarter.com/projects/udoo/udoo-bolt-raising-the-maker-world-to-the-next-leve), but it is a long wait)

**Comment by xet7** [comment]
@ripclaw 

8 GB RAM is plenty. UDOO x86 supports 64bit Linux distros. I would recommend using Ubuntu 18.04 64bit or Debian 9 64bit with Wekan Snap.

Wekan does run with 2 GB RAM, although more is of course better. Production systems usually have 4 GB or more.
