### ISSUE TITLE
Links in a checklist

### ISSUE THREAD

**Issue by ckiltolier** [wekan/wekan#1098]
Hi !

For now it's impossible to click a link in a check list, which is kind of frustrating.

Would it be possible to add in the platform : if a link is put in a checklist, if someone clicks on it, it opens a new tab with the url ?

Thank you !

**Comment by nztqa** [comment]
Related #877

**Comment by xet7** [comment]
Using markdown at checlists was already added to Wekan release [v0.55](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v055-2017-11-19-wekan-release)
