### ISSUE TITLE
Fails to load in Firefox Mobile Android

### ISSUE THREAD

**Issue by nileflowers** [wekan/wekan#110]
I wasn't able to load the [sample board](http://libreboard.com/boards/MeSsFJaSqeuo9M6bs/libreboard-roadmap) in Firefox 35.0 Android. It stays in the loading position. See Screenshot.
![screenshot_2015-01-23-08-41-05](https://cloud.githubusercontent.com/assets/51318/5876406/806658f6-a2dc-11e4-9c5c-1f933e88ff53.png)

**Comment by mquandalle** [comment]
(I'm using firefox I'm my main browser on android and) I cannot reproduce your issue.

**Comment by nileflowers** [comment]
I'll try to get Firefox remote debug going to see if there are any errors.

**Comment by krisak** [comment]
Also cant reproduce. On mobile (even big one) ui is unusable anyway.

**Comment by abredykhin** [comment]
I doesn't load for me in Chrome 40+ on MacOS either

**Comment by nileflowers** [comment]
this is no longer occurring.
