### ISSUE TITLE
Scheduling events

### ISSUE THREAD

**Issue by killua-eu** [wekan/wekan#1101]
Odoo has quite a killer feature that would suite wekan very well - event scheduling ![odoo-schedule](https://user-images.githubusercontent.com/410734/27736979-bd9beed4-5da6-11e7-99bf-8a4586d3b2ad.png) - would be great to have this in wekan as well along with sending notifications and listing this on daily/weekly calendar.

**Comment by rautamiekka** [comment]
A complete description of the feature as done in Odoo would be nice.

**Comment by killua-eu** [comment]
@rautamiekka , to do that properly I'd probably need access to the enterprise edition source code, nontheless, I'll try my best guesswork:

Terminology definition first: Each kanban card (in wekan, trello, odoo) consists of various dataobjects. I.e. trello's card will be defined completely by a 

- metadata object (card name, description, followers, asignees, duedates, tags, etc.)
- 0 to N messages objects (each containing a message)
- 0 to M checklists object (each containing all checklists)

Odoo on top of that seems to be able define 0 to P activity / event objects, consisting of:

- activity type
- deadline (date)
- summary (name)
- asignee(s)
- description

These activity objects show along with card deadlines on the asignee's calendar view (which wekan hopefully has soon too), both sending notifications (if set) upon incoming duedate.

Since Odoo stores its data in postgresql, I assume that it has a generic "event" data type (table), each data object (row) then referenced i.e. in the card, or in the asignees calendar and pulled via a join query. 

Would this description suffice?

**Comment by rautamiekka** [comment]
^ So far it does. And I didn't mean to read the source code.

(Damned Postgre ...)

**Comment by killua-eu** [comment]
Added a bounty on this issue. Please see https://www.bountysource.com/teams/wekan/issues ...
Let me know if I can provide details to further implementation of this.

**Comment by xet7** [comment]
Moved to here from #2305 

From @tKptCharly 

I'm looking for a possibility to add recurring cards into my boards, that have a predefined start-date (E.G. every day, every month on the 20th, etc..) to better optimize recurring workflows.

Is such a system already in place and I can't find it? Or if not, is it possible to add?

Thanks!
Charly

**Comment by liske** [comment]
I had the same requirement and hacked a small python script [wekan-scheduler](https://github.com/liske/wekan-scheduler) to create recurring cards via Wekan's REST API. It uses pycron for scheduling so it should be possible to handle most requirements (nth day of month, 2nd monday of a month, ...). It also has support for ICS files (iCal) to suppress card creations - this is useful for daily tasks (work days only) to be ignored on public holidays.

**Comment by xet7** [comment]
Fork of that liske's repo is also at https://github.com/wekan/wekan-scheduler , I now updated it, although sure sometime liske's repo can be ahead.

**Comment by xet7** [comment]
Moved to #2476

**Comment by Thorgrimson** [comment]
> Fork of that liske's repo is also at https://github.com/wekan/wekan-scheduler , I now updated it, although sure sometime liske's repo can be ahead.

How can I install the script in a non-docker environment like uberspace?

**Comment by xet7** [comment]
@Thorgrimson 

Maybe with these? I have not used uberspace.

https://manual.uberspace.de/lang-python

https://manual.uberspace.de/daemons-cron/
