### ISSUE TITLE
Document snap configuration

### ISSUE THREAD

**Issue by killua-eu** [wekan/wekan#1104]
I've installed the wekan snap in an lxd container and put a nginx reverse proxy infront of it to only notice that its not super obvious on howto configure wekan's root-url. I suggest adding the output of `wekan.help` or 
https://thinkonbytes.blogspot.cz/2017/05/how-config-wekan-snap.html to https://github.com/wekan/wekan/wiki/Install-and-Update.

**Comment by xet7** [comment]
Done.
