### ISSUE TITLE
Files accessible without authorization

### ISSUE THREAD

**Issue by killua-eu** [wekan/wekan#1105]
I noticed that accessing directly an uploaded image/attachment (i.e. https://wekan.example.com/cfs/files/attachments/WketAqrSi5oeZEiFA/picture.jpg) works even for unauthenticated/unauthorized clients - i guess that for someone this might be quite a serious security breach allowing to easily expose to the public (just share the links). Shouldn't wekan require users to be authenticated/authorized when accessing files?

Also a quick question: a brief search didn't reveal to me where wekan stores uploaded files/images. Are these stored directly in mongo? Thanks, P.

**Comment by rautamiekka** [comment]
Although it seems the uploads use an impossible-to-guess randomized address, such security vulnerability/breach is unacceptable regardless.

**Comment by killua-eu** [comment]
Well it could be a design decision (facebook works the same way, or at least used to work last time i cared to check), nonetheless I believe that for wekan this might not be the best solution and wekan is simple enough to keep assets authenticated. A quick fix would be to allow only authenticated users to see files (unless you shared a board is public), a more optimal fix would be to lookup the board a file belongs to and lookup what users can access the board and deal with authorization accordingly.

If wekan ever allows to share data between boards or cards, using a data deduplication mechanism such a CAS storage with userfriendly filenames as hardlinks is an option that can be easily implemented when need be.

**Comment by xet7** [comment]
Mitigation examples:
- Add Basic Auth in front of Wekan, if Wekan exposed to Internet
- Run Wekan on local network that does not have access to Internet
- use old version of Wekan in Sandstorm that makes usage safe

**Comment by rautamiekka** [comment]
@xet7 How/where is the mentioned data stored ?

**Comment by xet7** [comment]
@rautamiekka 

All data is stored to MongoDB.

Files are stored in CollectionFS format, so using them manually with direct database access with tools like [Robo 3T](https://robomongo.org) could be problematic, I don't know does CollectionFS storage format spread one file to multiple database records. There is [pull request to change it](https://github.com/wekan/wekan/pull/875).

For using files directly, see [cleanup scripts](https://github.com/wekan/wekan-cleanup).

**Comment by xet7** [comment]
I didn't notice yet does [REST API](https://github.com/wekan/wekan/issues/1037) have features for uploading and downloading files.

**Comment by rautamiekka** [comment]
Judging from https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/filesystem/filesystem.server.js, the files are physically stored on the computer's file system, but given Wekan doesn't run on a Web Server such as Apache, blocking access has to be done by modifying Wekan's Server JS (I think).

**Comment by killua-eu** [comment]
@xet7 , from what i can see the PR + usage of the meteor-file-collection changes the file storage model to a md5 addressed content-adressed storage. This i guess means that we have built-in data deduplication for free, making this a technically very sound solution from my perspective. How far along the way is the PR?

**Comment by xet7** [comment]
@killua-eu 

It looks like that there's just first one step implemented:
[X] Basic attachment upload/download/delete support

More details can be seen from pull request source code.

**Comment by killua-eu** [comment]
I checked back with vsivsi about the data-dedup, I was a bit overenthusiastic (built-in file-level dedup is not included in gridfs as I hoped it would) but luckily this is not on a major issue (and can be resolved by a write prior a read and some by wekan defined metadata). Please see the conversation in https://github.com/vsivsi/meteor-file-collection/issues/163 for details.

**Comment by xet7** [comment]
http://cryto.net/~joepie91/blog/2015/07/19/why-you-should-never-ever-ever-use-mongodb/

**Comment by killua-eu** [comment]
Well yep. But I guess wekan is tied to Mongo for as long as we find/write a DBAL for i.e. Mysql playing nicely with Meteor. Truth be said, Mongo improved since 2015, but I would feel way better about being able to manage files without it. Apart from FileCollection, there are projects like https://github.com/VeliovGroup/Meteor-Files ... Wish I knew js better, to offer something closer to a more technically sound solution myself. Since I cant, I'll try to summarize, hopefully unbiased:

- Current GridFS implementation has tons of problems. Switching over to FileCollection would benefit Wekan a lot. People are already working on this so hopefully this will get into master soon. 
- Adding basic deduplication + metadata ontop of FileColleection should be really easy (I can supply at least some basic pseudocode + a metadata schema)
- Alternative for non-mongo storage with Meteor exists. Since some code using FileCollection is already there, I'd stick to it. While Mongo may not be the best choice for storing blobs, FileCollection looks really nice.
- Ridding Wekan on hard Mongo dependency would be great, could be relatively easy, but is still is way more work then using FileCollection.

Using FileCollection with added metadata + file-level deduplication looks like the most reasonable step ATM. Writing a small abstraction layer between Wekan code and FileCollection making FileCollection replacable if we ever support more databases then just Mogno should be helpful to switch implementations quicky.

**Comment by GhassenRjab** [comment]
When exporting a Wekan board, the attachment's URL is used to point to the file and import that file in another Wekan installation.
Same thing happens with Trello.
We must take into consideration the import/export feature otherwise we risk losing exporting and importing attachments.

**Comment by xet7** [comment]
@GhassenRjab 

Could Wekan export/import also include attachments as base64 encoded (or similarly encoded) files directly to .json file? That would make it easier to import it to Sandstorm.

**Comment by GhassenRjab** [comment]
I'll start developing this feature and testing it right after #1117 gets merged

**Comment by xet7** [comment]
@GhassenRjab 

Ok it's merged now.

**Comment by GhassenRjab** [comment]
I created a PR #1134 to export and import Wekan attachments as base64 encoded files

**Comment by xet7** [comment]
@GhassenRjab 

Thanks! When that feature starts working in Wekan then authentication could be added for files on non-public boards and Import/Export of Wekan board would still work.
