### ISSUE TITLE
Ansible installation support

### ISSUE THREAD

**Issue by killua-eu** [wekan/wekan#1106]
To test wekan, i wrote two relevant ansible playbooks, one installing snap and its dependencies, one installing and configuring wekan using snaps. Currently only ubuntu is supported, I might add other distros upon request. Please feel free to ignore, fork, or rewrite these.

https://github.com/vaizard/mage-wekan
https://github.com/vaizard/mage-snapd

**Comment by xet7** [comment]
Thanks! I added those to wiki:
https://github.com/wekan/wekan-snap/wiki/Install-snap-with-Ansible
