### ISSUE TITLE
Create a "beginner"-Label

### ISSUE THREAD

**Issue by nammn** [wekan/wekan#1109]
Hi together, Wekan is a great piece of software! I really would like to contribute, but doesn't exactly know where though. This would make the start of contributions a lot easier for beginners like me.

It would be great if there was a custom label as "beginner-friendly" as in many other projects like: 

> https://github.com/Microsoft/vscode/labels/beginner

**Comment by xet7** [comment]
@nammn 

I have created [Beginner label](https://github.com/wekan/wekan/issues?q=is%3Aissue+is%3Aopen+label%3ABeginner) and also started adding that to issues with details about what to do.
