### ISSUE TITLE
Cross-domain link to meteor.com

### ISSUE THREAD

**Issue by singpolyma** [wekan/wekan#111]
Is this necessary?  Could libreboard.com maybe self-host whatever is being pulling in from there to not leak metadata to a third party on every page load?

**Comment by ocdtrekkie** [comment]
Where's it pulling data from meteor.com?

**Comment by singpolyma** [comment]
@ocdtrekkie not sure, looks like it's a websocket connection of some kind, actually.  When I block it with RequestPolicy, the pages just don't load.

**Comment by Slava** [comment]
Isn't the main board hosted on Meteor.com's free hosting? Not sure what you expected.

**Comment by singpolyma** [comment]
@Slava oh, is it?  That should be more clearly disclosed, maybe.

**Comment by Slava** [comment]
@singpolyma I am not a maintainer, I don't know for sure.

**Comment by singpolyma** [comment]
@Slava meteor.com won't even load properly for me, so it's hard to check what they offer, etc

**Comment by ocdtrekkie** [comment]
Ah, if you're just talking about libreboard.com, it's worth bearing in mind that the very nature of an open project clone you can self-host should carry some recommendation that the creators don't put a lot of stock in cloud security you don't host yourself. I'd recommend LibreBoard's own site for testing, but if you're looking for security, you should probably be self-hosting.

**Comment by ocdtrekkie** [comment]
@singpolyma Meteor is the platform this project is written in. They allow Meteor projects to be deployed and hosted on their servers for free for easy development, testing, and play. But you can also host Meteor projects elsewhere as well, of course.

**Comment by singpolyma** [comment]
@ocdtrekkie so is libreboard.com in fact hosted on meteor.com?  If so, that should probably be documented

**Comment by Slava** [comment]
@singpolyma I feel like it is a weird thing to document. They might change hosting in the future, so what?Meteor hosting is essentially AWS, should that also be documented?

The cross-domain connection might in fact be something the hosting needs to fix.

**Comment by singpolyma** [comment]
@Slava I just think that the reason for a cross-domain connection on every page load should be made clear.  If it's just because of the way the hosting provider works, then probably no additional metadata is leaking, so it should be fine, but that's not immediately obvious when seeing the connection.

**Comment by ocdtrekkie** [comment]
@singpolyma Documenting one's hosting provider is pretty abnormal. If you care enough for it to matter, you should be self-hosting.

**Comment by mquandalle** [comment]
If you use the instance we provide at http://libreboard.com, you are not only leaking the metadata, but also the data themselves (to me, Yasar, meteor, and amazon... at least). So don't put private stuff in it.

**Comment by andreioprisan** [comment]
This project is hosted on meteor.com. You can deploy on domain.meteor.com through the meteor command line tool, for free. The libreboard domain is simply CNAMEd to the libreboard.meteor.com site.

**Comment by singpolyma** [comment]
@ocdtrekkie it's not about the hosting provider, but the cross-domain request.  Documenting why it is a reasonable cross-domain request.  Which it is.

**Comment by mquandalle** [comment]
The instance deployed on https://wekan.io/sign-in is now self-hosted and isn’t calling the `meteor.com` servers anymore, which basically solve this issue.
