### ISSUE TITLE
Mail notifications not sent, no error logged.

### ISSUE THREAD

**Issue by killua-eu** [wekan/wekan#1111]
Hi,

I finally got to configuring email notifications, tested them by inviting someone to a board by email. Sending the mail results in an error, but no error has been logged (I use the snap packaged version of wekan, the only logs I were able to find were pulled with journalctl -u snap.wekan.wekan) 

```
export MAIL_URL='smtp://kanban%40example.com:kfe4JNAdsa1333356VAqfddsd0=@mail.example.com:587'
export MAIL_FROM='kanban@example.com'
```

Any hints on how to debug this? My mailserver expects a username (user@domain.com) a password and a letsencrypt cert on port 587 (tls).

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Does sending email work with some other program with those credentials?

Usually when there is no errors in Wekan logs, emails are sent successfully, and problem is in email server:
- email server missing SPF DNS records
- some spam filter preveinting email to be sent
- other email server error

**Comment by killua-eu** [comment]
This is really interesting. 

- The wiki entry didn't help
- Sending was tested with a different client
- SPF records ok
- No errors in mailserver log, just infos that wekan logged into the account, logged out.
- Didn't work 5 hours ago, now it works without any apparent reason.

In conclusion, I'm closing this bug and blaming it on random cosmic xrays hitting the server's hardware, my incompetency / blindness to the obvious, and threefingered dwarfs. The last ones mentioned are really the worst.
