### ISSUE TITLE
Missing port in cards' URL - wekan docker

### ISSUE THREAD

**Issue by sbuliga** [wekan/wekan#1112]
Hi, 

This issue is similar with #679. 

I've installed wekan via docker on Windows 10. I can access it on localhost:8080. 

I have launched it using `docker run -d --name=wekan --link=wekan-mongodb:db -e MONGO_URL=mongodb://db -e ROOT_URL=http://localhost -p 8080:80 mquandalle/wekan` - so using the `-e` parameter as recommended in the previous similar issue. 

However the issue #679 appears: the cards URL does not have the port 8080, and "localhost refused to connect" error is thrown. 

The URL for the welcome board is: `http://localhost:8080/b/HPjHSBRisppyK43Md/welcome-board`, but the card link is `http://localhost/b/HPjHSBRisppyK43Md/welcome-board/wtp4gtrbsAQXGRrBk`. 

As described in #679, when adding `:8080` to the card URL, the card is accessible. 

Is this a bug or I need to do something differently?

Thanks for your help!

**Comment by nztqa** [comment]
Please read again #679 

```
docker run -d --name=wekan --link=wekan-mongodb:db -e MONGO_URL=mongodb://db -e ROOT_URL=http://localhost:8080 -p 8080:80 mquandalle/wekan- -e
```

**Comment by sbuliga** [comment]
Adding the "- -e" parameter at the end of the CLI command was not my
understanding based on #679.

I'll try as suggested and report back the result.

**Comment by sbuliga** [comment]
I've re-read #679 and your comment. It worked with:

`docker run -d --name=wekan --link=wekan-mongodb:db -e MONGO_URL=mongodb://db -e ROOT_URL=http://localhost:8080 -p 8080:80 mquandalle/wekan`

Thanks for support!
