### ISSUE TITLE
Feature Request: Add complexity field to card

### ISSUE THREAD

**Issue by X-dark** [wekan/wekan#1115]
It would be useful to have a complexity field where it would be possible to set *points* for the card.

**Comment by ropeladder** [comment]
I am a Trello user who is looking around at alternatives with the hope that one of them might have this feature (or more broadly, the ability to set custom numeric or label tags that I could then filter and sort by).

**Comment by xet7** [comment]
@X-dark @ropeladder 

Is this same as Custom Fields #807 ?

Or is there some additional functionality needed ?

**Comment by ropeladder** [comment]
I hadn't seen #807--it looks basically like what I want (not sure if the current PR includes filtering and sorting though?)

**Comment by xet7** [comment]
Moved to #807
