### ISSUE TITLE
Add Feature: Anonymous user with write access on public board

### ISSUE THREAD

**Issue by guakamole** [wekan/wekan#1124]
Hello,

First of, thank you for Wekan!

I would like to know if it is possible to run Wekan publicly without forcing users to create an account ?

For example, you can use Etherpad without having to create an account : https://beta.etherpad.org/p/SISEmYYpYm (anyone can contribute to a pad).

In the case of Wekan, anonymous (understand: users without accounts) could create, move, edit,... cards. Would it possible ?

Thank you in advance for your answer :)

**Comment by xet7** [comment]
Yes. Set board as Public, then board publically visible in read-only mode, without login.

Does this answer your question?

**Comment by guakamole** [comment]
Hello xet7,

Thank you for your answer.

> Yes. Set board as Public, then board publically visible in read-only mode, without login.

If I understand correctly, that would allow anyone to read the board, that's great.
What about "write" rights ? So, not read-only but read-and-write. Would it be possible ?

**Comment by xet7** [comment]
There is not yet a way to edit without login. So you would create new user account "Anonymous" and add info that those wanting to edit need to login with that "Anonymous" username and password.

User permissions for boards are Admin / Normal / Comment only.
For example you could have that "Anonymous" user have Comment only permission, so only adding comments is allowed.

**Comment by guakamole** [comment]
Is there anything that can be done to help make this feature happen ?

**Comment by xet7** [comment]
Moved Anonymous Comment/Edit and Moderation #313 to here.

**Comment by xet7** [comment]
@guakamole 

Yes, someone should look at Wekan code about how to implement this.

**Comment by guakamole** [comment]
@xet7 that was the goal of my question :)

I want to try to help, I'm not familiar with Wekan source code yet, so where should I look ?

A way to implement it could be:

- to create an "anonymous" user at install time ;
- add an option in boards parameters to allow for public read/write access ;
- update the UI accordingly ;
- add a condition to the routine that checks rights : if the board is publicly writable in the config, enable write access publicly, assign to the user "anonymous" any action.

Does it make sense? Would it be the right way to do it?

**Comment by xet7** [comment]
@guakamole 

For development docs, look at:
https://github.com/wekan/wekan/wiki#Development

Wekan source code is here:
https://github.com/wekan/wekan

There is also general user management options missing from Admin Panel:
https://github.com/wekan/wekan/wiki/Features#wishes-for-admin-panel

According to Open Hub, Wekan code is only about 7000 lines of code, without adding additional node modules etc, so it's quite small when compared to other software. This is becauser Meteor.js framework provides so much functionality built-in.
https://www.openhub.net/p/wekan

You can see with graphical Git history viewer how various features have been made:
https://git-scm.com/book/uz/v2/Git-in-Other-Environments-Graphical-Interfaces
I currently use gitk on Linux.

I think there is no need to create anonymous user at install time.

Anonymous user settings could work like this below, also note that during development you could come up with better ideas, this is just a suggestion:

ADMIN PANEL SETTINGS for Wekan admin: Anonymous users

```
Anonymous username: ____________________
Anonymous user permissions: [Normal / Comment Only]   <== dropdown options
[Create Anonymous User] <=== button

List of Anonymous users:
[X]  Anonymous Username1
[X]  Anonymous Username2

List of all boards:
List [*] All [_] Anonymous user enabled
[X] Boardname1 [List of Anonymous users in this board]
[X] Boardname2 [List of Anonymous users in this board]

Options for selected Anonymous users on selected boards:
[_] Enable anonymous user on selected boards
[_] Disable anonymous user on selected boards
[_] Delete all comments by Anonymous user on selected boards 
[_] Delete anonymous user
[_] Move comments to this Anonymous user: [Dropdown of all Anonymous Users]
[Run actions for selected Anonymous users]    <=== button
```

BOARD SETTINGS for board admin: Anonymous user

```
[_] Anonymous write access  <=== Enable/Disable
Anonymous username: [Dropdown list of all anonymous users]
```

**Comment by xet7** [comment]
Moved to #3022
