### ISSUE TITLE
Improve usability in smartphones

### ISSUE THREAD

**Issue by geaplanet** [wekan/wekan#1129]
It is not an issue, they are some suggestions.
From smartphones it is common to attach photos, but integration with (for example, Android) is very poor. In addition, the option is quite hidden (Double touch in a card, touch in a menu icon, touch in a Edit attachments, touch in a computer, etc....)

I also noticed that to get into a card I need to give a lot of finger touches (it really is not a double tap, I need to give lots of taps), it is very annoying.

By last, when you want to edit something the edit box is often hidden and you have to make screen slides.

**Comment by xet7** [comment]
Moved to #953
