### ISSUE TITLE
Broken card links

### ISSUE THREAD

**Issue by dimidd** [wekan/wekan#1135]
Hi,

I've installed wekan on AWS server (with no domain) on a private VPC using docker. After importing a board from Trello as described [here](https://github.com/wekan/wekan/wiki/Migrating-from-Trello) all the links to the cards point to `localhost` rather than the actual server.

**Comment by xet7** [comment]
@dimidd 

You need to setup ROOT_URL to your real Wekan address, like https://example.com/wekan

What webpage did you use for install? I'll try to add this required info there.

Docker:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml

Source:
https://github.com/wekan/wekan/wiki/Install-and-Update#run-wekan-manually-if-youve-built-for-production

Wekan snap:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by dimidd** [comment]
Thanks @xet7 ! I just followed the instructions here:
https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

But, I've copied the yaml verbatim without modifying `ROOT_URL`.
