### ISSUE TITLE
Vanila chat usage

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1136]
@nztqa 

Can you come to [Vanila chat](https://chat.vanila.io/channel/wekan), add your chat username to [Wekan Team](https://github.com/wekan/wekan/wiki/Team) and start private chat with me about would you like to become [co-maintainer of Wekan](https://github.com/wekan/wekan-maintainer/wiki/FAQ) ?

**Comment by nztqa** [comment]
I’m afraid it is too much to ask of me.

**Comment by xet7** [comment]
@nztqa 

Ok :) No problem.
