### ISSUE TITLE
Update installation procedure for debian

### ISSUE THREAD

**Issue by hanneslehmann** [wekan/wekan#1137]
Hello,

I was following [Installation from Source on Linux](https://github.com/wekan/wekan/wiki/Install-source-without-sudo-on-Linux). That script shown there does not work - I tried executing the script (which creates dirs and expects them in another place) and then each step manually. It is always stuck somewhere. Could you please
- either remove it completely as it creates confusion, or
- update / validate it

Unfortunately I tried several hours installing wekan, but nodejs, npm, captnproto etc are messing up their versions, so that I am not able to use meteor reliable. Will come back to wekan once it has a stable installation.

At the moment it's failing with
```bash
836 verbose lifecycle meteor-dev-bundle@0.0.0~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/hannes/repos/wekan/.build/bundle/programs/server/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
837 verbose lifecycle meteor-dev-bundle@0.0.0~install: CWD: /home/hannes/repos/wekan/.build/bundle/programs/server
838 silly lifecycle meteor-dev-bundle@0.0.0~install: Args: [ '-c', 'node npm-rebuild.js' ]
839 silly lifecycle meteor-dev-bundle@0.0.0~install: Returned: code: 1  signal: null
840 info lifecycle meteor-dev-bundle@0.0.0~install: Failed to exec install script
841 verbose stack Error: meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
841 verbose stack Exit status 1
841 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
841 verbose stack     at emitTwo (events.js:125:13)
841 verbose stack     at EventEmitter.emit (events.js:213:7)
841 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
841 verbose stack     at emitTwo (events.js:125:13)
841 verbose stack     at ChildProcess.emit (events.js:213:7)
841 verbose stack     at maybeClose (internal/child_process.js:897:16)
841 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
842 verbose pkgid meteor-dev-bundle@0.0.0
843 verbose cwd /home/hannes/repos/wekan/.build/bundle/programs/server
844 verbose Linux 2.6.32-48-pve
845 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
846 verbose node v8.1.4
847 verbose npm  v5.0.3

```

**Comment by xet7** [comment]
Hi,
Wekan building from source is stable, but not all pages on wiki are up-to-date yet, although I update them nearly daily. As seen from GitHub repo changelog, I recently added menu to wiki.

That install from source without sudo page is in progress and not complete. Only running npm commands as local user should be used from that without sudo page. For most commands this should be used:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source

You have wrong versions of node and npm.

Correct versions can be seen for example at Dockerfile that uses Debian 8.8:
https://github.com/wekan/wekan/blob/devel/Dockerfile

and also VirtualBox wekan-rebuild.sh script:
https://github.com/wekan/wekan-maintainer/tree/master/virtualbox

Wekan uses Meteor.js framework that currently runs on x64 systems. Your logfile says that you use Linux 2.6.32-48-pve kernel, is that on x32 system?

Wekan does not yet run on ARM systems like Raspberry Pi and some ARM devices #1053

For easiest installation and newest features, I recommend any updated often platform like Docker or Ubuntu snap:
https://github.com/wekan/wekan/wiki/Platforms

Info about Wekan RAM usage is at https://github.com/wekan/wekan/issues/1088#issuecomment-311843230

When building Wekan, errors about capnp can be ignored. Some binary versions that build script tries to download are not available, so they are build from source.

What debian version and hardware are you trying to run Wekan on?

**Comment by rautamiekka** [comment]
^
> is that on x32 system?

https://en.wikipedia.org/wiki/Proxmox_Virtual_Environment says, if the `pve` kernel means that, it's exclusively x64, and their downloads at http://download.proxmox.com/debian/dists/wheezy/pve-no-subscription/ has only x64.

http://cephnotes.ksperis.com/blog/page/2 reinforces the possibility that OpenVZ prior to Proxmox VE dropping support for it, as mentioned on the Wikipedia article, shared kernels.

**Comment by hanneslehmann** [comment]
Hi,
thanks for pointing to the rebuild script, will give it a try tomorrow. I am on a hosted virtual server with Debian Sid x64, so I guess installing Docker on top might be shaky. That's why I wanted to run Wekan directly.
Will come back when tomorrow for results

**Comment by xet7** [comment]
@hanneslehmann 

Wekan Ubuntu snap is available on Debian sid:
https://snapcraft.io/docs/core/install-debian
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
I think, but it could also be that snap only works on Ubuntu 16.04 64bit, I'm not sure, needs testing.

**Comment by hanneslehmann** [comment]
Hi,

ok, that snap thing seems to be to experimental for a PROD debian :)

Nontheless I tried still manual approach, but npm/node is so confusing, the last step:
```bash
...
cd ~/repos/wekan/.build/bundle/programs/server
rm -rf node_modules
npm install
```

gives:
```bash

> bson@0.2.21 install /home/hannes/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hannes/.npm/_logs/2017-07-19T14_34_24_384Z-debug.log
```
But the mentioned log says something other?!
```bash
3116 info lifecycle meteor-dev-bundle@0.0.0~install: meteor-dev-bundle@0.0.0
3117 verbose lifecycle meteor-dev-bundle@0.0.0~install: unsafe-perm in lifecycle true
3118 verbose lifecycle meteor-dev-bundle@0.0.0~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/hannes/repos/wekan/.build/bundle/programs/server/node_modules/.bin:/home/hannes/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
3119 verbose lifecycle meteor-dev-bundle@0.0.0~install: CWD: /home/hannes/repos/wekan/.build/bundle/programs/server
3120 silly lifecycle meteor-dev-bundle@0.0.0~install: Args: [ '-c', 'node npm-rebuild.js' ]
3121 silly lifecycle meteor-dev-bundle@0.0.0~install: Returned: code: 1  signal: null
3122 info lifecycle meteor-dev-bundle@0.0.0~install: Failed to exec install script
3123 verbose stack Error: meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
3123 verbose stack Exit status 1
3123 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
3123 verbose stack     at emitTwo (events.js:125:13)
3123 verbose stack     at EventEmitter.emit (events.js:213:7)
3123 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
3123 verbose stack     at emitTwo (events.js:125:13)
3123 verbose stack     at ChildProcess.emit (events.js:213:7)
3123 verbose stack     at maybeClose (internal/child_process.js:897:16)
3123 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
3124 verbose pkgid meteor-dev-bundle@0.0.0
3125 verbose cwd /home/hannes/repos/wekan/.build/bundle/programs/server
3126 verbose Linux 2.6.32-48-pve
3127 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3128 verbose node v8.1.4
3129 verbose npm  v5.3.0
3130 error code ELIFECYCLE
3131 error errno 1
3132 error meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
3132 error Exit status 1
3133 error Failed at the meteor-dev-bundle@0.0.0 install script.
3133 error This is probably not a problem with npm. There is likely additional logging output above.
3134 verbose exit [ 1, true ]
```

I guess I have a mixup of versions, but to be honest I don't understand the concept behind meteor vs. node....
```bash
$ node -v
v8.1.4
$ meteor node -v
v4.8.1
$ npm -v
5.3.0
$ meteor npm -v
4.4.4
```

I guess I have to stick on trello :_(

**Comment by xet7** [comment]
WOW now you are using node 8.1.4, that really is not compatible :)

We currently use node 4.8.4.

**Comment by hanneslehmann** [comment]
Ok, switched node version an I am now thru till "echo Done." :) Now, how do I start that thing?

P.S.: at some stage I need to understand why node uses this versioning scheme, I have following on my machine: node/0.10.40, node/4.8.1, node/8.1.4...

**Comment by xet7** [comment]
@hanneslehmann 

You start it with run-wekan.sh script:
https://github.com/wekan/wekan/wiki/Install-and-Update#run-wekan-manually-if-youve-built-for-production

There ROOT_URL is for example:
- http://192.168.10.100
- http://192.168.10.100/wekan
- http://example.com
- http://example.com/wekan

**Comment by hanneslehmann** [comment]
Hi @xet7 , thanks - it's running AND reachable thru https/nginx B) . I was checking the mongoDB backup. It looks like it's dumping the complete database and not only the wekan relevant part, right? Have to check that soon...

**Comment by hanneslehmann** [comment]
Ah, and there was some critical patch for Node 4.8.1 - would need to update to 4.8.4 soon before using wekan seriously ;)
