### ISSUE TITLE
When I close browser and reopen it's lost

### ISSUE THREAD

**Issue by Yachikh** [wekan/wekan#1139]
Hello guys,

When I close the browser and reopen it shows only My tables and archives in the header and add a board in the body area. No user and no ability to reconnect even when I visit /sign-in
It is as if the cookie is gone!
Anyone having this issue? Anyone who can help?

Thanks in advance

**Comment by xet7** [comment]
@Yachikh 

Is your Wekan running?

How did you install Wekan ?

**Comment by Yachikh** [comment]
@xet7 
I did install it in windows, it's working just fine but once I close the browser and open it again it only shows My Boards, Archives and Add a new board
Here's a screenshot
![capture](https://user-images.githubusercontent.com/26182679/28384513-4ceb139e-6cc5-11e7-9201-4668b5ea87d9.PNG)

**Comment by Yachikh** [comment]
In the console I got this error:
`Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]`

**Comment by xet7** [comment]
@Yachikh

I have not yet tested installing on Windows.

Somebody did install Wekan for Windows at #1088

Currently in use versions of dependecies can be seen at Dockerfile, what versions do you use?
https://github.com/wekan/wekan/blob/devel/Dockerfile

**Comment by xet7** [comment]
It depends do you have saving history in browser enabled, do same browser tabs open. Also you need Internet connection to save data.
