### ISSUE TITLE
Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by ekarademir** [wekan/wekan#1141]
Might be related to database migration. This occurs when clicked on an old card. It doesn't show the contents and the whole board stops functioning properly.

Wekan ver 0.28, Docker
Mongo Version: 3.2.13

Console log:
[10.0.0.40-1500646586477.txt](https://github.com/wekan/wekan/files/1165776/10.0.0.40-1500646586477.txt)

**Comment by xet7** [comment]
@ekarademir 

Can you try again with newest wekanteam:latest Docker image? Because double slash bug related to opening cards was fixed recently.

**Comment by ekarademir** [comment]
Hi @xet7 ,

Thanks for the response. I've installed the latest image on 24th of July, and now I tested it agan and got the same error on the console. The log is attached.

Also the card closes, but the board becomes unfunctional because the transparent gray backdrop doesn't disappear. I'm also attaching a screenshot.
![ss](https://user-images.githubusercontent.com/329490/28662724-0665684a-72b3-11e7-9bf8-1f682dd0db11.png)
[10.0.0.40-1501145898653.txt](https://github.com/wekan/wekan/files/1179392/10.0.0.40-1501145898653.txt)

**Comment by tac0x2a** [comment]
Hi @xet7,

I faced same issue on [wekan/wekan-mongodb](https://github.com/wekan/wekan-mongodb).

When click the card does not include Comments and Details, it works.

But, when the card has Details, or Comments, only trans to modal.
(Does not display card detials like @ekarademir shown, too.)

It happen in the new card too.
I add a new card, it works. But when write details, it was broken too.

**Comment by xet7** [comment]
@ekarademir @tac0x2a 

a) [Check that you have admin rights to board](https://github.com/wekan/wekan/issues/1060)

b) Is it possible for you to export Wekan board where this issue happens, and attach JSON to this issue in .zip file? If there is private data, you can try to delete those first. It would help me reproduce this issue, and check exported JSON file first there is no private data left. 

Keep backups:
https://github.com/wekan/wekan/wiki/Export-Docker-Moängo-Data

**Comment by kolaente** [comment]
I have the same issue after upgrading to the latest version (`0.89`), using the official docker image.
I cannot view the details of cards, with the same error @ekarademir already reported, but the page turns blank instead, nor does it work when I create a new card. It doesn't seem to matter if the card has details or not.

However, if I create a new board, everything works as expected.

**Comment by kolaente** [comment]
I also tried to export and re-import the board, didn't work either.

**Comment by ekarademir** [comment]
@kolaente I did solve this issue by doing export-import. However, I cleaned up the cards before importing them. Like I got rid of all the history. And aligned the data fields by hand so that they all have the same fields.
