### ISSUE TITLE
Can't init service.

### ISSUE THREAD

**Issue by lucasdiedrich** [wekan/wekan#1143]
Hello guys, i'm installing the Wekan using the tar.gz file, i'm installed nodejs v0.10.40, uninstalled and installed fibers and exported the system variables, but for some reason i'm getting the error below:

```bash
[root@server wekan]# /root/.nvm/v0.10.40/bin/node main.js 

/opt/wekan/programs/server/mini-files.js:82
const unicodeNormalizePath = (path) => {
                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/wekan/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```
I'm running on Centos 7, any ideas?

**Comment by lucasdiedrich** [comment]
Extra info:

```bash
[root@server wekan]# which node
/root/.nvm/v0.10.40/bin/node
[root@server wekan]# node -v
v0.10.40
[root@server wekan]# npm -v
1.4.28
[root@server wekan]# which npm
/root/.nvm/v0.10.40/bin/npm
```

**Comment by xet7** [comment]
@lucasdiedrich 

Where did you get installation instructions to use old v0.10.40 version of Wekan?
You can see current version numbers of requirements at [Dockerfile](https://github.com/wekan/wekan/blob/devel/Dockerfile).

**Comment by xet7** [comment]
@lucasdiedrich

For easiest install on CentOS 7, I recommend [Install using Docker](https://github.com/wekan/wekan/wiki/Platforms#docker)

There is also  [Troubleshooting CentOS 7](https://github.com/wekan/wekan/issues/718).

**Comment by xet7** [comment]
@lucasdiedrich 

Change ROOT_URL on docker-compose.yml to your Wekan URL like for example:
- http://192.168.10.100 
- http://192.168.10.100/wekan
- http://example.com
- http://example.com/wekan

**Comment by lucasdiedrich** [comment]
@xet7 , thanks for the help, after installing 4.8.4 it worked just fine, i'm going to see if i make the docker installation right now.

Thanks.
