### ISSUE TITLE
Install Wekan with Mup to AWS

### ISSUE THREAD

**Issue by JeremyIglehart** [wekan/wekan#1145]
I've been trying to install Wekan to AWS using the latest version of `mup` and I've been running into problems.  Specifically, I get stuck at the bson business it seems like.

Can we figure out how to get a successful path to installation with a fresh AWS instance and document the process and add it to the Wiki?

Having a way to self host using AWS and deploying with MUP is something more people other than myself would be interested in having.

**Comment by xet7** [comment]
@JeremyIglehart 

Easiest way to install to AWS is to install Ubuntu Server 16.04 64bit image and then use Ubuntu snap to install Wekan:
https://github.com/wekan/wekan-snap/wiki/Install

What is MUP ?

**Comment by xet7** [comment]
Please reopen issue if you still have problems.
