### ISSUE TITLE
How to read the content of a outgoing webhook

### ISSUE THREAD

**Issue by datenwort** [wekan/wekan#1147]
Will there be a short wiki entry how the webhooks will work?
I receive the post call on the entered server but without any body information.

**Comment by xet7** [comment]
@nztqa 

Can you add info about Webhooks to [Features page Webhooks](https://github.com/wekan/wekan/wiki/Features#webhooks) ?

**Comment by nztqa** [comment]
@xet7 I updated the information.

@datenwort Tested with [Slack](https://slack.com/) and [Rocket.chat](https://rocket.chat/)
