### ISSUE TITLE
Add Feature: Import / Export Redmine CSV

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1150]
This pull request https://github.com/wekan/wekan/pull/397
has this Redmine CSV Import code https://github.com/wekan/wekan/pull/397/commits/443528279264e429d03e795b52c979dea204c389

It needs testing does it work, and creating pull request.
Import menu should be added like this https://github.com/wekan/wekan/pull/1117
And also be available at Sandstorm https://github.com/wekan/wekan/pull/1144

**Comment by soerenk** [comment]
I used https://github.com/wekan/wekan/wiki/virtual-appliance for testing. Import of my Trello Board is working. Members can be mapped. Labels, Lists, Cards everything was there. Minior problem is, that all activities was dated at the time of the import. That lead to an unsorted Comment section.

Is there more to test or something unclear? I will do my best to help you on this Issue.

**Comment by xet7** [comment]
@soerenk 

Your issue moved to #1157

**Comment by VictorQRS** [comment]
@xet7 @soerenk 

Since this issue was moved to #1157, shouldn't this issue be closed?

**Comment by xet7** [comment]
@VictorQRS 

No, this issue about Redmine is not closed. Wekan does not have Redmine import/export yet.

@soerenk had different issue about Trello import, that was moved #1157

**Comment by renanramos97** [comment]
Hello @xet7. This is the only open issue with "Beginner" tag associated to but it's last update dates from 1 year past today, is redmine integration not implemented yet?

**Comment by xet7** [comment]
@renanramos97 

Yes, this is not implemented yet. There is a lot of example code at CSV issue #395 , also that issue is not implemented yet. This is waiting for any Wekan contributor that has time to help adding this feature, like most other issues too. It's not possible for me to work on all 587 open issues at once. I'm only one human.

**Comment by xet7** [comment]
@renanramos97

Not all issues have tags added. In general, anyone can send pull request for anything that is not [at my Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) marked `Urgent` or `TOP PRIORITY`.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
