### ISSUE TITLE
Add Feature: Show card count and status clock at list header

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1151]
This pull request https://github.com/wekan/wekan/pull/397
has this code for Show card count and status clock at list header: https://github.com/wekan/wekan/pull/397/commits/183590d4cff2bd31bb5721c5933a065cbaea5e13

Code needs testing and adding as new pull request.

**Comment by johnleeming** [comment]
This is kind of active already - I have a board which I think was imported from Trello (or perhap wefork) where I had added a card count on one list only and that tracks the changes to the number of cards in the list but I can't see a way to add a count to other lists which didn't have the count added before the import.
![image](https://user-images.githubusercontent.com/13801070/30436650-95f66a72-9964-11e7-933e-2c7f238adbbf.png)

**Comment by AlexanderZobkov** [comment]
After doing a little investigation, yes, it appears the feature is already here. Added in commit: https://github.com/wekan/wekan/commit/606dbbbbf2e5ef4bccaadc4584d05c67d7148fc8 . However,  the menu where this feature can be enabled is not available in Sandstorm or I can't find it:
![image](https://user-images.githubusercontent.com/3214752/30930979-0707e684-a3cc-11e7-81e3-55c3319590e9.png)

Is it possible to enable the feature in Wekan running Sandstorm?

**Comment by xet7** [comment]
This feature already exists at Sandstorm.
