### ISSUE TITLE
Add Feature: Web manifest to support 'progressive web app' use

### ISSUE THREAD

**Issue by danhawkes** [wekan/wekan#1154]
This [google reference](https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/) explains the advantages.

To do so should be pretty simple: at a minimum it requires serving a few additional static files - a manifest json file, and some higher res icons. 
  
<https://w3c.github.io/manifest/>

I think this'd also be relevant to offline support: #466

**Comment by xet7** [comment]
@danhawkes 

Can you try to add pull request for those files to devel branch?

**Comment by danhawkes** [comment]
Yeah, will try and have a look this evening.
