### ISSUE TITLE
Docker-compose build fails

### ISSUE THREAD

**Issue by aaronkjones** [wekan/wekan#1159]
## Issue
**Impacted version**: 2

* Operating System: OSX 10.12.6
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker 17.06.0-ce, build 02c1d87

**Problem description**:

> gpgkeys: HTTP fetch error 7: couldn't connect: eof
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> /bin/sh: 1: gosu: Permission denied
> /bin/sh: 1: gosu: Permission denied
> ERROR: Service 'wekan' failed to build: The command '/bin/sh -c useradd --user-group --system --home-dir /home/wekan wekan &&         apt-get update -y && apt-get dist-upgrade -y && apt-get install -y --no-install-recommends ${BUILD_DEPS} &&         GOSU_ARCHITECTURE="$(dpkg --print-architecture | awk -F- '{ print $NF }')" &&     wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${GOSU_ARCHITECTURE}" &&     wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${GOSU_ARCHITECTURE}.asc" &&     export GNUPGHOME="$(mktemp -d)" &&     gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 &&     gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu &&     rm -R "$GNUPGHOME" /usr/local/bin/gosu.asc &&     chmod +x /usr/local/bin/gosu &&         wget https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     wget https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc &&         grep ${NODE_VERSION}-${ARCHITECTURE}.tar.gz SHASUMS256.txt.asc | shasum -a 256 -c - &&     export GNUPGHOME="$(mktemp -d)" &&     for key in     9554F04D7259F04124DE6B476D5A82AC7E37093B     94AE36675C464D64BAFA68DD7434390BDBE9B9C5     FD3A5288F042B6850C66B31F09FE44734EB7990E     71DCFD284A79C3B38668286BC97EC7A07EDE3FC1     DD8F2338BAE7501E3DD5AC78C273792F7D83545D     C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8     B9AE9905FFD7803F25714661B63B535A4C206CA9     ; do     gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ||     gpg --keyserver pgp.mit.edu --recv-keys "$key" ||     gpg --keyserver keyserver.pgp.com --recv-keys "$key" ;     done &&     gpg --verify SHASUMS256.txt.asc &&     rm -R "$GNUPGHOME" SHASUMS256.txt.asc &&         tar xvzf node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     rm node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     mv node-${NODE_VERSION}-${ARCHITECTURE} /opt/nodejs &&     ln -s /opt/nodejs/bin/node /usr/bin/node &&     ln -s /opt/nodejs/bin/npm /usr/bin/npm &&         npm install -g npm@${NPM_VERSION} &&     npm install -g node-gyp &&     npm install -g fibers@${FIBERS_VERSION} &&         cd /home/wekan/ &&     chown wekan:wekan --recursive /home/wekan &&     curl https://install.meteor.com -o ./install_meteor.sh &&     sed -i "s|RELEASE=.*|RELEASE=${METEOR_RELEASE}\"\"|g" ./install_meteor.sh &&     echo "Starting meteor ${METEOR_RELEASE} installation...   \n" &&     chown wekan:wekan ./install_meteor.sh &&         if [ "$USE_EDGE" = false ]; then       gosu wekan:wekan sh ./install_meteor.sh;     else       gosu wekan:wekan git clone --recursive --depth 1 -b release/METEOR@${METEOR_EDGE} git://github.com/meteor/meteor.git /home/wekan/.meteor;     fi;         mkdir -p /home/wekan/app/packages &&     chown wekan:wekan --recursive /home/wekan &&     cd /home/wekan/app/packages &&     gosu wekan:wekan git clone --depth 1 -b master git://github.com/wekan/flow-router.git kadira-flow-router &&     gosu wekan:wekan git clone --depth 1 -b master git://github.com/meteor-useraccounts/core.git meteor-useraccounts-core &&     sed -i 's/api\.versionsFrom/\/\/api.versionsFrom/' /home/wekan/app/packages/meteor-useraccounts-core/package.js &&     cd /home/wekan/.meteor &&     gosu wekan:wekan /home/wekan/.meteor/meteor -- help;         cd /home/wekan/app &&     gosu wekan:wekan /home/wekan/.meteor/meteor add standard-minifier-js &&     gosu wekan:wekan /home/wekan/.meteor/meteor npm install &&     gosu wekan:wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build &&     cp /home/wekan/app/fix-download-unicode/cfs_access-point.txt /home/wekan/app_build/bundle/programs/server/packages/cfs_access-point.js &&     chown wekan:wekan /home/wekan/app_build/bundle/programs/server/packages/cfs_access-point.js &&     gosu wekan:wekan sed -i "s|build\/Release\/bson|browser_build\/bson|g" /home/wekan/app_build/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/ext/index.js &&     cd /home/wekan/app_build/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt &&     gosu wekan:wekan rm -rf node_modules/bcrypt &&     gosu wekan:wekan npm install bcrypt &&     cd /home/wekan/app_build/bundle/programs/server/ &&     gosu wekan:wekan npm install &&     mv /home/wekan/app_build/bundle /build &&         apt-get remove --purge -y ${BUILD_DEPS} &&     apt-get autoremove -y &&     rm -R /var/lib/apt/lists/* &&     rm -R /home/wekan/.meteor &&     rm -R /home/wekan/app &&     rm -R /home/wekan/app_build &&     rm /home/wekan/install_meteor.sh' returned a non-zero code: 126

**Comment by xet7** [comment]
@aaronkjones 

On first line is the reason:

```
gpgkeys: HTTP fetch error 7: couldn't connect: eof
```

When building Docker Compose from source, build script gets GPG keys from different servers to verify that downloaded addons hashes match. Keyservers are sometimes overloaded, so you need to try again.

Building Docker Compose from source is only required during development.
If you just want to use Wekan, you can use [Wekan-MongoDB](https://github.com/wekan/wekan-mongodb) with newest release number or latest tag.

**Comment by aaronkjones** [comment]
xet7,

It passes this now, but fails on another step. I will create a new issue. Thanks.
