### ISSUE TITLE
SMTP not working (docker installation)

### ISSUE THREAD

**Issue by martster** [wekan/wekan#1165]
## Issue
**Impacted version**: 2

**Server Setup Information**:

* Operating System: Ubuntu 16.04.2
* Deployment Method: docker
* Node Version: not installed
* MongoDB Version: 2.6.10
* ROOT_URL environment variable (Is there a subfolder?): https://wekan-sub.domain.tld

**Problem description**:

I installed Wekan and everything works fine except the SMTP stuff. I set the ```MAIL_URL``` in the docker-compose.yml to the following:
```MAIL_URL=smtp://username@domain.tld:passwd@smtp.server.tld:25/```.
In the admin panel I also added the username, password, port and mail-from-field and set the SMTP-server-adress to _smtp://smtp.server.tld_

If I'm trying to send an forgot-password-email from frontend I get an internal server error. The wekan-app log says the following:

```
Exception while invoking method 'forgotPassword' Error: getaddrinfo ENOTFOUND smtp smtp:587
    at Object.Future.wait (/build/programs/server/node_modules/fibers/future.js:449:15)
    at Mail._syncSendMail (packages/meteor.js:213:24)
    at smtpSend (packages/email.js:116:13)
    at Object.Email.send (packages/email.js:174:5)
    at AccountsServer.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:614:9)
    at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:546:12)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    - - - - -
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```
In front of Wekan there is an Apache which does the Proxy Pass work. The SMTP-Server runs on another IP adress and accepts STARTTLS.

**Comment by xet7** [comment]
Have you tried troubleshooting mail ?
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by zechocobo** [comment]
Hello, I have the same problem with a Postfix server in front of Wekan.
I read troubleshooting mail without succes.

When I have TLS support enable :
`wekan_1    | Exception in callback of async function: Error: self signed certificate [email-fail]
wekan_1    |     at sendInvitationEmail (models/settings.js:119:13)
wekan_1    |     at models/settings.js:136:15
wekan_1    |     at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
wekan_1    |     at packages/mongo/collection.js:643:5
wekan_1    |     at args.(anonymous function) (packages/matb33_collection-hooks.js:391:23)
wekan_1    |     at runWithEnvironment (packages/meteor.js:1176:24)
wekan_1    |     at packages/meteor.js:1189:14
wekan_1    |     at packages/mongo/mongo_driver.js:320:7
wekan_1    |     at runWithEnvironment (packages/meteor.js:1176:24)`

without TLS:
`wekan_1    | Exception in callback of async function: Error: 140680005240640:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
wekan_1    |  [email-fail]
wekan_1    |     at sendInvitationEmail (models/settings.js:119:13)
wekan_1    |     at models/settings.js:136:15
wekan_1    |     at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
wekan_1    |     at packages/mongo/collection.js:643:5
wekan_1    |     at args.(anonymous function) (packages/matb33_collection-hooks.js:391:23)
wekan_1    |     at runWithEnvironment (packages/meteor.js:1176:24)
wekan_1    |     at packages/meteor.js:1189:14
wekan_1    |     at packages/mongo/mongo_driver.js:320:7
wekan_1    |     at runWithEnvironment (packages/meteor.js:1176:24)`

And I can't disable TLS on my postfix server.
Is there another workarround ?

**Comment by karuppiah7890** [comment]
I actually get a problem while using TLS and that too with port 587. I get the `SSL23_GET_SERVER_HELLO:unknown protocol` error

**Comment by sathieu** [comment]
I've updated https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#self-signed-certificate with better alternatives.

**Comment by xet7** [comment]
@martster  @karuppiah7890 

Do you still have problems with this?

**Comment by karuppiah7890** [comment]
@xet7 I didn't try it again later. I was just trying out Wekan and found the issue

**Comment by xet7** [comment]
Ok, then this can be closed, as email work for me.

**Comment by karuppiah7890** [comment]
👍

**Comment by linwsup** [comment]
Error trying to send email: 139731157038912:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

**Comment by linwsup** [comment]
I get a problem。
this is docker-compose.yml
MAIL_URL=smtp://user:passwd@mail.xxxx.com:578
mailserver:
  image: marvambass/versatile-postfix
  volumes:
    - /home/wekan/dkim:/etc/postfix/dkim/
    - /home/wekan/maildirs:/var/mail
  command: xxxx.com user:passwd
  environment:
    - ALIASES=postmaster:root;hostmaster:root;webmaster:root
