### ISSUE TITLE
Wekan at Sandstorm is heavily outdated!

### ISSUE THREAD

**Issue by CKoewing** [wekan/wekan#1166]
At Sandstorm the Wekan app is available in version 0.16,
but Wekan has reached version 0.32 in the meantime!

No update since more than 4 month! Please fix that!

**Comment by ocdtrekkie** [comment]
0.32 has some issues in Sandstorm that need to get resolved before it can be published for Sandstorm. @xet7 and I have actually been working on getting everything sorted to actively publish a new release for Sandstorm over the last couple of weeks.

**Comment by ocdtrekkie** [comment]
You can keep an eye on where we're at right now on #799

**Comment by CKoewing** [comment]
THX @ocdtrekkie ...waiting for updates :-)

**Comment by xet7** [comment]
Moved to #799
