### ISSUE TITLE
Add feature: Card priority

### ISSUE THREAD

**Issue by CKoewing** [wekan/wekan#1168]
There are no swimlanes in wekan and we can't change the background color of the cards, so we use the labels for prioritization. Which works, but it blocks the labels for other identifiers.

It would be usefull to have something to prioritize the cards. Icons perhabs, or a numeric priority level?

**Comment by xet7** [comment]
There are already existing feature requests:
- [Swimlanes](https://github.com/wekan/wekan/issues/955)
- [Card background color](https://github.com/wekan/wekan/issues/428)
- [Custom Fields](https://github.com/wekan/wekan/issues/807)

**Comment by danger89** [comment]
Custom fields is the most logical choice here.

That being said, it's not very elegant to use. For my custom field, dropdownbox, I need to click on the 'edit' button every time, this doesn't make sense for a dropdown box. Meaning I need to spend for each card additional times, this adds up when you have 30+ cards.
