### ISSUE TITLE
Receive the message "Your JSON data does not include the proper information in the correct format" when importing some boards from Trello

### ISSUE THREAD

**Issue by sk33z3r** [wekan/wekan#1174]
## Issue
**Impacted version**: v0.32.0

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method: Docker _(I've tried wekanteam/wekan and mquandalle/wekan)_
* Node Version: 4.8.4
* MongoDB Version: 3.2.14
* ROOT_URL environment variable (Is there a subfolder?): http://example.tld
_(I have a FQDN that is working just fine, my issue is only with importing JSON)_

**Problem description**:

Originally commented in issue #610. Moving to a new issue since the other was closed.

I receive the following error when attempting to import JSON from Trello on certain boards. I currently have 4 that I am attempting to import. 2/4 succeed, the other 2 fail with this:

![image](https://user-images.githubusercontent.com/20587571/29217977-52fc532e-7e81-11e7-9905-fdd99da33c47.png)

**Steps to reproduce**:
1. On the Trello board, go to **Show Menu > More > Print and Export > Export JSON**
2. Either save the generated file or copy
3. In Wekan, **Add Board > Import Board > from Trello**
4. Paste the JSON from Trello into the text box
5. Click **Import**
6. Link members from Trello to Wekan
7. Click **Done**
8. Observe the error

As mentioned in the linked ticket above, I cannot share the actual JSON. It has my company's sensitive data in it, besides usernames/IDs. I can help look for and draw out any odd patterns, etc. in it. I just can't share the actual JSON.

---

## My troubleshooting attempts

When I tail the docker logs for both the mongoDB and wekan containers, then do the import dance, I see no log data at all when the fail message appears, "Your JSON data does not include the proper information in the correct format." If I import a smaller board, then I can see the mongoDB logs spit up some generic info about building indexes.

I see the following when monitoring debug tools in Chrome. Replaced my actual FQDN with "example.tld"

```
Exception while simulating the effect of invoking 'importBoard' ndetails: undefinederror: "error-json-schema"errorType: "Meteor.Error"message: "[error-json-schema]"reason: undefinedstack: "Error↵    at e [as check] (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:312:5233)↵    at d.MethodInvocation.importBoard (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:311:23753)↵    at http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:83:13851↵    at r.EnvironmentVariable.withValue (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:3:7163)↵    at y.apply (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:83:13747)↵    at y.call (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:83:13146)↵    at n.finishImport (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:305:22209)↵    at nextStep (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:305:21658)↵    at n.onSubmit (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:305:24098)↵    at http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:251:6220"__proto__: Errorclone: function ()arguments: nullcaller: nulllength: 0name: ""prototype: Objectconstructor: function ()arguments: nullcaller: nulllength: 0name: ""prototype: Objectconstructor: function ()__proto__: Object__proto__: function ()[[FunctionLocation]]: 982665b….js?meteor_js_resource=true:3[[Scopes]]: Scopes[2]__proto__: Object__proto__: function ()apply: function apply()arguments: (...)bind: function bind()call: function call()caller: (...)constructor: function Function()length: 0name: ""toString: function toString()Symbol(Symbol.hasInstance): function [Symbol.hasInstance]()get arguments: function ThrowTypeError()set arguments: function ThrowTypeError()get caller: function ThrowTypeError()set caller: function ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>[[FunctionLocation]]: 982665b….js?meteor_js_resource=true:3[[Scopes]]: Scopes[2]constructor: function ()__proto__: Objectconstructor: function Error()message: ""name: "Error"toString: function toString()arguments: nullcaller: nulllength: 0name: "toString"__proto__: function ()apply: function apply()arguments: (...)bind: function bind()call: function call()caller: (...)constructor: function Function()length: 0name: ""toString: function toString()Symbol(Symbol.hasInstance): function [Symbol.hasInstance]()get arguments: function ThrowTypeError()set arguments: function ThrowTypeError()get caller: function ThrowTypeError()set caller: function ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__() Error
    at e [as check] (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:312:5233)
    at d.MethodInvocation.importBoard (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:311:23753)
    at http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:83:13851
    at r.EnvironmentVariable.withValue (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:3:7163)
    at y.apply (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:83:13747)
    at y.call (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:83:13146)
    at n.finishImport (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:305:22209)
    at nextStep (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:305:21658)
    at n.onSubmit (http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:305:24098)
    at http://example.tld/982665b65fdb43da47fffca406a48299f47467c9.js?meteor_js_resource=true:251:6220
```

There seem to be 2 possible locations where this error is possible after digging through a little of your source code. I wish I was more of a developer to be able to understand some of this and give better investigative help, but I can at least follow the trail as best I can for now and give the info.

The text, "Your JSON data does not include the proper information in the correct format", is found in the error message defined as `error-json-schema`. My initial guess is that there is some incompatible card/list/label in these boards that doesn't play well with `trelloCreator.js`. Which leads me to look...

in `models/trelloCreator.js`:
```
check(board) {
    try {
      // check(data, {
      //   membersMapping: Match.Optional(Object),
      // });
      this.checkActions(board.actions);
      this.checkBoard(board);
      this.checkLabels(board.labels);
      this.checkLists(board.lists);
      this.checkCards(board.cards);
      this.checkChecklists(board.checklists);
    } catch (e) {
      throw new Meteor.Error('error-json-schema');
    }
  }
```

and in `models/watch.js`:
```
Meteor.methods({
  watch(watchableType, id, level) {
    check(watchableType, String);
    check(id, String);
    check(level, Match.OneOf(String, null));

    const userId = Meteor.userId();

    let watchableObj = null;
    let board = null;
    if (watchableType === 'board') {
      watchableObj = Boards.findOne(id);
      if (!watchableObj) throw new Meteor.Error('error-board-doesNotExist');
      board = watchableObj;

    } else if (watchableType === 'list') {
      watchableObj = Lists.findOne(id);
      if (!watchableObj) throw new Meteor.Error('error-list-doesNotExist');
      board = watchableObj.board();

    } else if (watchableType === 'card') {
      watchableObj = Cards.findOne(id);
      if (!watchableObj) throw new Meteor.Error('error-card-doesNotExist');
      board = watchableObj.board();

    } else {
      throw new Meteor.Error('error-json-schema');
    }

    if ((board.permission === 'private') && !board.hasMember(userId))
      throw new Meteor.Error('error-board-notAMember');

    watchableObj.setWatcher(userId, level);
    return true;
  },
});
```

I did a fairly deep comparison between a working board that imports without issue and the boards that are failing. I didn't see any immediate issues in the way the JSON data was formatted or displayed, and there were no obvious differences in the scheme in general between the two boards. I used VS code to prettify and check the syntax on all 4 boards, everything seems to be OK in terms of what I'm actually pasting. I have tried pasting both prettified and minified versions of all boards with the same results each way.

https://github.com/wekan/wekan/wiki/Migrating-from-Trello#5-limitations
At this link, there is mention of comments on cards prior to December 2014 not being able to import. However, there is no data on my failing board that is older than 2016.

I had a hunch in the beginning that data may be truncated, but it seems one of my successful imports has almost double the characters that one of my failing boards have.

* Character count of a successfully imported board: 2887526
* Character count of a failed board import: 1358802

---

I and my co-worker are willing to help track this down in any way we can. We desperately would like to use Wekan as a replacement to Trello. It's the closest and simplest form of self-hosted kanban we've been able to find.

**Comment by xet7** [comment]
@sk33z3r 

What are the differences between those 2 boards that successfully import and 2 that don't ?

Have you added names to all labels, so there are no unnamed labels in the board?

Do you use some features Wekan does not yet have, like stickers ?

**Comment by xet7** [comment]
@sk33z3r

It would be useful if there's possible to try to create new Trello board, add something to it, export to Wekan, and have that trigger the problem so this could be reproduced.

**Comment by sk33z3r** [comment]
@xet7 

One failing board has all labels named, the other has a couple of unnamed. Both have ~18 lists and some cards have stickers. Are both of these known issues/limitations? Maybe I can strip out the sticker info from the JSON.

I'll take a shot at re-creating a failing board and paste the JSON here if I can keeping these two things in mind.

**Comment by sk33z3r** [comment]
- Note about one of the _successful_ boards, it has all **unnamed** labels and no stickers.
- Attempts to re-create a failing board have failed so far. I added stickers and a mix of named and unnamed labels, but still importing correctly.
- I thought permissions may be an issue as I am not an owner of either of the failing boards. However, I copied the JSON from a successful board using a downgraded/non-owner account, and the board still imported successfully. Doesn't seem to matter if the user is an owner or not when exporting the JSON in Trello.
- Could it have anything to do with a size limitation, in the amount of data coming over? Both of the failing boards do have quite a lot of attachments and images as covers compared to the boards that are importing properly. The receiving server has 55GB freespace available, and I doubt this board takes up that much. I feel like the import would begin successfully and fail later if this was the case, as well.

**Comment by xet7** [comment]
@sk33z3r 

Please test with newest Wekan does this still happen.

There has been some import export fixes for Standalone and Sandstorm versions.

[Attachment activities fixes](https://github.com/wekan/wekan/pull/1202) will be added in near future.

**Comment by sk33z3r** [comment]
The Docker image tagged "latest" reports Wekan v0.36.0.

I tried one of the boards again, but unfortunately the issue persists.

**Comment by 88fingerslukee** [comment]
This issue persists in Sandstorm/Wekan v0.37.0

**Comment by GhassenRjab** [comment]
@sk33z3r @88fingerslukee 

If you still have this issue, **are you ok with sending me the json data exported from Trello?** as it would help me debug the problem. Apparently there are some use cases we didn't take into consideration when importing from Trello.

**Your data** will be used for **debugging** reasons **only**.

**Comment by sk33z3r** [comment]
I really wish that I could. However, I am under an NDA. I know how incredibly difficult this makes it to troubleshoot.




If there's some type of filtering or search through the JSON that can be done, I'm more than willing to scrub the files myself and give stripped output. There's just way too much to strip out in the full file.




I tried my hand again this morning to reproduce the issues on a dummy board, but I guess my software team is doing something abnormal that I'm missing. I checked for special characters in all possible entry fields, stickers/other powerups, empty labels, and user permissions. Any other feature from Trello I should check out that may not play nice with Wekan?






On Sun, Sep 17, 2017 at 12:58 AM -0400, "Ghassen Rjab" <notifications@github.com> wrote:












@sk33z3r @88fingerslukee


If you still have this issue, are you ok with sending me the json data exported from Trello? as it would help me debug the problem. Apparently there are some use cases we didn't take into consideration when importing from Trello.


Your data will be used for debugging reasons only.

**Comment by sk33z3r** [comment]
Are there any debug options that I could use to draw out more explicit
errors?

**Comment by xet7** [comment]
@sk33z3r 

When I had previously problems with JSON, I used http://www.jsondiff.com (on that address is also link to it's source code) to see differences in JSON files, if some fields are missing etc, and after that somebody made that problematic field optional, as can be seen in Git history. Then Import Export started to work. There also could be other tools that can be used to compare JSON files.

**Comment by GhassenRjab** [comment]
@sk33z3r 

Or send us the structure of the JSON file only, remove recursively any value that is not an object or an array.
If this is the JSON file
`
{
  "key1": "value1",
  "key2": "value2",
  "key3": {
    "key31": [
      {
        "key311": "value311",
      }
    ]
  }
}
` 
send as just the keys, like so
`
{
  "key1": "",
  "key2": "",
  "key3": {
    "key31": [
      {
        "key311": "",
      }
    ]
  }
}
`
Don't remove nested objects and arrays because we need the full structure.

**Comment by xet7** [comment]
No example JSON file provided, can not reproduce.
