### ISSUE TITLE
 Do this have a Chinese version?

### ISSUE THREAD

**Issue by Johnhacker** [wekan/wekan#1177]
rt  

3Q

**Comment by oing9179** [comment]
@Johnhacker Reply [#1](#issue-250803657)

Check out [Translations](https://github.com/wekan/wekan/wiki/Translations).

以后别再开这种丢人现眼的 Issue.
Translated into chinese: Stop opening issues like this one, and stop being such a faggot who's lowering line of chinese people.

**Comment by xet7** [comment]
@Johnhacker 

Yes.

https://github.com/wekan/wekan/wiki/Features#translations
