### ISSUE TITLE
Remove cover not working?

### ISSUE THREAD

**Issue by anthony-ng** [wekan/wekan#118]
When you go to file attachment, and click remove cover, it seems like its not working sometimes?

**Comment by mahabatta** [comment]
hello sir   may be i  maked chlck by mistake how i resolne this??

**Comment by mquandalle** [comment]
Unfortunately I can't reproduce this bug. Could you give more details?

**Comment by mahabatta** [comment]
more details like what ??

**Comment by mquandalle** [comment]
Like how to reproduce this bug.
