### ISSUE TITLE
Make comments more distinguishable from changes/activities in cards

### ISSUE THREAD

**Issue by al3xst** [wekan/wekan#1182]
## Issue
**Impacted version**: 
0.32.0

**Server Setup Information**:
Docker Container

Comments should be displayed above of all changelogs, when expanding a card. Otherwise they get lost and it's hard to find them. Also it would be nice, if they had a slightly different background, to be even more distinguishable.

**Comment by nztqa** [comment]
Some users may not like it, but perhaps a function to display comments only with a toggle switch would be good
