### ISSUE TITLE
Feature Request: Drag'n'Drop of Checklist-Items

### ISSUE THREAD

**Issue by MaZderMind** [wekan/wekan#1191]
Sorting-Order in an Checklist is an valuable Information. It can be use to express Priority of Subtasks or to move already finished tasks to the end of the List.
Furthermore, having multiple Checklists on a card, it would be quite helpful to be able to move Checklist-Items from one List to another.

Implementing the UI via drag'n'drop als seems obvious, given that drag'n'drop is an ubiquitous pattern in wekan.

**Comment by xet7** [comment]
Moved to #876

**Comment by MaZderMind** [comment]
@xet7 sorry, i searched for "Checkbox" and missed to search for "Checklist". Thank you for linking the correct issue.
