### ISSUE TITLE
Improve notifications via mail

### ISSUE THREAD

**Issue by mxmehl** [wekan/wekan#1193]
There're three things to be improved when it comes to WeKan's notifications:

1. A user doesn't receive a mail when someone mentions her (@user) in a card which she isn't participating in, or if she's not watching the whole board. This doesn't make sense to me as there's the possibility to mention single users to raise their attention. This could be a global user setting ("Notify me every time someone mentions me in a card").

2. The mailing could be a bit more verbose in the subject, similar to how Github notification mails look like. There should at least be the title of the card in the subject. So instead of `Activity Notification` it could be `Activity Notification: this is the card's title`. 

3. Additionally, the "From:" of the email could be the person triggering the notifications. So instead of `admin@example.com` it would be `John Doe <admin@example.com`.

Thanks a lot :)

**Comment by xet7** [comment]
Moved to #794
