### ISSUE TITLE
How to change logo

### ISSUE THREAD

**Issue by safeershahul** [wekan/wekan#1196]
## Issue
**Impacted version**: All?

**Problem description**:
- *How to change logos? Like the login page, the favicon and in Wekan*

I can't seem to find any html files I can edit.

**Comment by xet7** [comment]
@safeershahul

When running Wekan in [Sandstorm](https://sandstorm.io), in menu "Admin Panel / Personalization" there is "Custom logo on sign-in dialog" where you can upload your own logo.

**Comment by safeershahul** [comment]
How do I do it when I'm installing from source?

**Comment by sk33z3r** [comment]
@safeershahul 
If you're on a *nix install, do:
`sudo find / -name wekan-logo-header.png`

Whatever folder that is in is where all the logos are stored it seems. Other than forcing the change server-side, I don't think there's a way to do it.

**Comment by pqsky** [comment]
@sk33z3r 
Hi ! How to change logo when I'm installing from docker?

**Comment by xet7** [comment]
@pqsky 

1) Clone wekan/wekan repo

2) Change logo file

3) In source code wekan directory, use [Docker Compose](https://github.com/wekan/wekan/wiki/Docker#docker-compose-examples) to build from source with this command:

```
sudo docker-compose up -d --build
```

I have not tested this yet, but it should work.

**Comment by arradoq** [comment]
How to change it when I am using windows? Do you have any recommendation?

**Comment by xet7** [comment]
I'm currently building new Wekan release v1.75 that has new feature: Hide Logo.
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v175-2018-11-20-wekan-release

It's a first step. I try to figure out Custom Logo later.

**Comment by xet7** [comment]
Plans about whitelabeling etc here:
https://blog.wekan.team/2018/11/year-2018-what-we-archieved/index.html

**Comment by xet7** [comment]
There is now at Admin Panel:
- Hide Logo
- Custom Product Name

Also in translations name `Wekan` is replaced with general descriptions at least in English and Finnish, and maybe others, if translators have translated correctly.

After these changes, text "Wekan" is only visible at Adming Panel Version, that shows Wekan version.

**Comment by namacoconut** [comment]
good morning mr.lauri,
as you see I have those fields in my snap instance, which is weird, did you release this change in the weekend? :) 

however I can't find the upload button, and if I will use a link to change that, should it be over internet?
![Screenshot (899)](https://user-images.githubusercontent.com/65490460/93704046-79d8d480-fb20-11ea-9b57-bfba4d242ee6.png)

**Comment by namacoconut** [comment]
> There is now at Admin Panel:
> 
> * Hide Logo
> * Custom Product Name
> 
> Also in translations name `Wekan` is replaced with general descriptions at least in English and Finnish, and maybe others, if translators have translated correctly.
> 
> After these changes, text "Wekan" is only visible at Adming Panel Version, that shows Wekan version.

**nice update :) thank you. 
I'll update you soon for ADFS authentication 👍**

**Comment by xet7** [comment]
I added more docs about storing logo elsewhere or in Wekan:
https://github.com/wekan/wekan/wiki/Custom-Logo
