### ISSUE TITLE
Use the gitlab account login?

### ISSUE THREAD

**Issue by leecade** [wekan/wekan#120]
Great jobs!
Is it possible to use the gitlab account login?
We all have gitlab account and don't want to register an account for libreboard.
Thanks.

---

just like: GitLab CI

**Comment by mahabatta** [comment]
I like both  and i want to register an account for libreboard.

**Comment by leecade** [comment]
:+1:

**Comment by nsrosenqvist** [comment]
Hi, is there an ETA for this feature? I would love to be able to use Libreboard to improve our Gitlab workflow.

**Comment by leecade** [comment]
#109

**Comment by leecade** [comment]
#355

**Comment by xet7** [comment]
moved to #109
