### ISSUE TITLE
A grain can't be opened.

### ISSUE THREAD

**Issue by muho-asta** [wekan/wekan#1201]
## Issue: One file is affected, I can't open it.

**Impacted version**: 0.16.0 (persists after update to 0.34.0)

**Server Setup Information**: simple virtual server 

* Operating System: Ubuntu 16.04 minimal 64 Bit
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): 
sandstorm (i set it up with the installer script a few weeks ago, there is no server like nginx installed, I think.)

**Problem description**:

If I open the grain, it just show's the error message from below. Any chance to get my boards back? 

Restarting sandstorm, the server, wekan and setting the server back to an earlier state didn't help (although I don't know for sure, that the file worked fine at this earlier point in time.

## error message:

Error: remote exception: Peer disconnected.
    at Error (native)
C++ location:(remote):??
type: disconnected

**Comment by xet7** [comment]
@muho-asta 

1) Try to save all your grains to files with arrow down button on Sandstorm. For those grains that do open, also Export them as Wekan JSON files.

2) Remove Wekan app from Sandstorm

3) Install some old Wekan .spk version from:
https://github.com/wekan/wekan/releases?after=v0.16

4) Upload your problem grain and try to download attachment

Also, in that saved Sandstorm grain is all data from that grain's MongoDB database, but I have not yet tried how to get data from those files directly.

**Comment by ocdtrekkie** [comment]
If it only happens with one grain, my guess is something in the Mongo database for that grain is corrupted. I don't know enough about Mongo to suggest how to fix it. But presumably, if you opened up the grain backup, fixed the Mongo database, then re-zipped it and uploaded the grain back to Sandstorm, it would work.

**Comment by xet7** [comment]
It is possible to repair MongoDB database this way:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

So you can restore it to Standalone Wekan like Snap or Docker.

I will later create tool to make Sandstorm grain .zip file, or another way to import to Sandstorm.

Moved  #1695
