### ISSUE TITLE
Ubuntu snap version of Wekan does not work in OpenVZ because of limited mounting privileges

### ISSUE THREAD

**Issue by m-thielen** [wekan/wekan#1203]
Your installation instructions do not work - none I tried, and I tried quite a few:

* bash scripts at https://github.com/wekan/wekan-maintainer/tree/master/virtualbox: there seems to be no installation script, just an update script, which is broken (wrong paths)
* manual installation instructions fail on various occasions, e.g. npm install
* the snap package fails to install with an "unknown mount error (-1)"

You should really update your documentation and scripts. This made me give up on Wekan.

**Comment by xet7** [comment]
@m-thielen 

Where are you trying to install Wekan?
- Operating System version
- does computer x64 processor and OS ?
- did you use sudo with snap? sudo snap install wekan
- have you installed all updated to your OS, like sudo apt-get dist-upgrade ?
- please add more details: full install log when you install from source
- did you use MongoDB 3.2.x ? Wekan is not compatible with MongoDB 3.4.x when uploading files.

Install from source instructions are at:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source

**Comment by m-thielen** [comment]
Sorry for not being very specific, but the wrong instructions/commands in the documentation and installation scripts are obvious if you try them. They are just plain wrong and probably easy to fix if you are familiar with the project.
I used a fresh Ubuntu 16.04 64bit server, had all updates installed. Tried the snap package as root, yes. It fails to mount - try it and you will see.

One problem is that you do not provide a solid starting point, e.g. in which directory to start the script (or the installation instructions) and under which user to run the script or commands.

**Comment by xet7** [comment]
I tested:
* Created new Ubuntu 16.04 VM with 1GB RAM in AWS Lightsail
* Did attach public Elastic IP
* Installed all updates

Then I added settings mentioned in these snap docs:
https://github.com/wekan/wekan-snap/wiki/Install
These settings keys:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

Like this (ip address changed)

```
sudo snap install wekan
sudo snap set wekan root-url="http://123.456.789.0"
sudo snap set wekan port=80
sudo snap disable wekan
sudo snap enable wekan
```

And Wekan did work, I did not see any errors.

Also install from source instructions do work for me.

Please add your install from source logs, etc errors. I don't see any obvious errors.

**Comment by m-thielen** [comment]
Strange. This is what I get (as root, so no sudo there):

```
$ snap install wekan
error: cannot perform the following tasks:
- Mount snap "core" (2462) ([start snap-core-2462.mount] failed with exit status 1: Job for snap-core-2462.mount failed. See "systemctl status snap-core-2462.mount" and "journalctl -xe" for details.
)

$ systemctl status snap-core-2462.mount
* snap-core-2462.mount - Mount unit for core
   Loaded: loaded (/etc/systemd/system/snap-core-2462.mount; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-09-05 14:24:50 CEST; 51s ago
    Where: /snap/core/2462
     What: /var/lib/snapd/snaps/core_2462.snap
  Process: 14843 ExecMount=/bin/mount /var/lib/snapd/snaps/core_2462.snap /snap/core/2462 -t squashfs -o nodev,ro (code=exited, status=32)
```

**Comment by xet7** [comment]
In VirtualBox VM, scripts are at /home/wekan/repos directory.

Did you install Ubuntu Server from .iso ? Is it running on some cloud like AWS/Googe/Azure/Digital Ocean or some of your hardware?

**Comment by m-thielen** [comment]
It's an openvz virtual host running in the cloud (HostEurope).

**Comment by xet7** [comment]
What kernel? snap requires new enought kernel.

**Comment by m-thielen** [comment]
4.4.0-042stab123.9

**Comment by xet7** [comment]
Kernel is new enough.

It could be that OpenVZ forbids some mounting privileges.

**Comment by m-thielen** [comment]
You are probably right...
https://github.com/anbox/anbox/issues/220

**Comment by m-thielen** [comment]
I don't like container packages anyway :-)
But unfortunately the manual installation instructions do not work for me, either. Do you want me to try again and send what I get?

**Comment by xet7** [comment]
You could install Meteor.js with install script from https://www.meteor.com

Then download precompiled tar.gz package from:
https://github.com/wekan/wekan/releases

And then start Wekan with scripts that has these environment variables
https://github.com/wekan/wekan/wiki/Install-and-Update#run-wekan-manually-if-youve-built-for-production

And in that script start wekan with command meteor .

In OpenVZ it can also be that docker version does not work.

**Comment by xet7** [comment]
Yes please add results of your manual install

**Comment by xet7** [comment]
Also Sandstorm (where Wekan is also available) does not work in OpenVZ:
https://github.com/sandstorm-io/sandstorm/issues/2799

**Comment by m-thielen** [comment]
```
# MongoDB for Ubuntu 16.04
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
sudo apt update
sudo apt install -y mongodb-org mongodb-org-server mongodb-org-shell mongodb-org-mongos mongodb-org-tools
sudo systemctl start mongod
sudo systemctl enable mongod

# Meteor
curl https://install.meteor.com/ | sh

# Wekan
su wekan
cd ~
sudo rm -rf /usr/local/lib/node_modules
sudo rm -rf ~/.npm
git clone https://github.com/wekan/wekan
cd wekan
mkdir packages
cd packages
git clone https://github.com/wekan/flow-router.git kadira-flow-router
git clone https://github.com/meteor-useraccounts/core.git meteor-useraccounts-core
sed -i 's/api\.versionsFrom/\/\/api.versionsFrom/' ~/.meteor/packages/meteor-useraccounts-core/package.js
```
The last command fails with `sed: can't read /home/wekan/.meteor/packages/meteor-useraccounts-core/package.js: No such file or directory`

Do I have to install Meteor as the non-privileged wekan user?

**Comment by xet7** [comment]
You need to install Node.js first.

I think Meteor install script asks for privileges if it needs them.

**Comment by xet7** [comment]
Required version are mentioned at:
https://github.com/wekan/wekan/blob/devel/Dockerfile

Node 4.8.4
etc

**Comment by m-thielen** [comment]
It is already installed:
```
wekan@lvps83:~/wekan/packages$ sed -i 's/api\.versionsFrom/\/\/api.versionsFrom/' ~/.meteor/packages/meteor-useraccounts-core/package.js
sed: can't read /home/wekan/.meteor/packages/meteor-useraccounts-core/package.js: No such file or directory
wekan@lvps83:~/wekan/packages$ node --version
v4.8.4
```

**Comment by xet7** [comment]
I think sed tried to replace in this file

```
~/repos/wekan/packages/meteor-useraccounts-core/package.js
```

**Comment by m-thielen** [comment]
So the path in the sed command is wrong?

**Comment by xet7** [comment]
Yes, when it gives error

**Comment by m-thielen** [comment]
`find ~ -name meteor-useraccounts-packages`finds nothing...

**Comment by xet7** [comment]
I'll try to make working install script for Ubuntu 16.04 when I have more time.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan-snap/issues/30

**Comment by kubiko** [comment]
snap install problem is very likely caused by openVZ configuration. From what I can see they seem to disbanded loop module in their kernel. Since snappy system relies heavily on squashfs it can't even mount core system snap let alone wekan snap. Whatever is their rational without loop device it's no go.
As for snap it's not container. It's more different packaging system witch includes all but core system dependencies. It's lot cleaner to install/uninstall/update. More like android or iOS application experience
