### ISSUE TITLE
Add Feature: Manage admins from admin interface

### ISSUE THREAD

**Issue by frmwrk123** [wekan/wekan#1205]
As of now the first registered user becomes admin of the whole installation. If you want to add further admins, for example you work in a team and want to give more people admin privileges, you have to manually give these users in the database the {isAdmin: true} value. It would be much more pleasant and less error-prone if you could add or remove admins from the admin interface.

The broader feature is probably a proper account management where you can safely delete users, etc.

**Comment by xet7** [comment]
Moved to #802
