### ISSUE TITLE
Use relative links internally as much as possible

### ISSUE THREAD

**Issue by adamhovorka** [wekan/wekan#1210]
## Feature Request
**Impacted version**: v0.36

**Server Setup Information**: Private business internal web application server

* Operating System: Arch Linux
* Deployment Method: Docker
* Node Version: v4.8.4
* MongoDB Version: 3.2.14
* ROOT_URL: http://10.8.59.1/wekan

**Problem description**:

We have our Wekan instance set up to be accessible over an OpenVPN connection on our employees' laptops, and it works perfectly, but we also have several desktop computers on-site which we would like to be able to access Wekan over the local network, and because the entire ROOT_URL is used to construct the links used for e.g. editing cards, when a card is clicked nothing appears to happen until the browser times out and throws up an error page saying the host couldn't be found. I believe that somehow using only the subdirectory specified on the ROOT_URL to assemble navigation links would solve this problem.

**Comment by xet7** [comment]
@adamhovorka 

You could run 2 different Wekan Docker containers that have different ROOT_URL and use same MongoDB database.

**Comment by adamhovorka** [comment]
I'm afraid I'm not very familiar with Docker or docker-compose. How would I set that up inside our docker-compose.yml? Would I just duplicate the services: wekan section? What options would I need to change?

**Comment by xet7** [comment]
@adamhovorka 

Is there different IP address or URL that is shown for VPN users and LAN users? Does that server has multiple IP addresses? Usually when I use VPN I can access same LAN IP addresses as at the office LAN.

Is there some server like Nginx or Caddy in front of Wekan Docker container?

**Comment by adamhovorka** [comment]
The server is 10.8.0.1 over the VPN and 192.168.x.x over the local network. Off-site computers visit 10.8.0.1 and on-site computers visit 192.168.x.x. The VPN is configured so that it only allows clients to connect to the server itself; it intentionally drops packets aimed elsewhere for security reasons.

The server uses Nginx as a reverse proxy for several different applications, hence /wekan in the ROOT_URL.

**Comment by xet7** [comment]
@adamhovorka 

I think you don't need multiple copies of Wekan running.

You need a nameserver, one for your LAN, and one for your VPN. Configure your computers to use those nameservers in computer or LAN/VPN DNS settings.

On nameservers, setup http://yourserver domain name (name that you made up, not real domain at internet) to point to your server where Wekan is in address http://yourserver/wekan address. LAN nameserver points to 192.168.x.x and VPN nameserver points to 10.8.0.1.

Setup Wekan ROOT_URL=http://yourserver/wekan

Setup Wekan PORT=3000   (or some other port)

Setup nginx proxy from http://yourserver/wekan to localhost port 3000 .

This way you could also have names to your other servers, no need to use IP addresses.

Tell me does this work for you.

**Comment by adamhovorka** [comment]
I went ahead and set up Nginx to forward to two different Wekan containers based on the client's IP range. Setting up nameservers is undoubtedly the cleaner solution, but unfortunately we decided that with our current setup it would be too difficult to get it set up correctly for all of the client computers.
