### ISSUE TITLE
Trying to create a PR. How do you do math in templates?

### ISSUE THREAD

**Issue by TylerL-uxai** [wekan/wekan#1216]
Trying to do something like this

  .minicard(style="background-color:hsl(354,100%,{{sort}}*2+46%)")

to get something like this (create a visual hierarchy using color lightness)

<img width="1077" alt="screen shot 2017-09-12 at 11 40 43 pm" src="https://user-images.githubusercontent.com/4743518/30361476-d345c52e-981c-11e7-84be-d78fcb746b0d.png">

**Comment by TylerL-uxai** [comment]
<img width="1074" alt="screen shot 2017-09-12 at 11 35 59 pm" src="https://user-images.githubusercontent.com/4743518/30362128-0743e542-9820-11e7-8cd4-af595f993dfa.png">

**Comment by TylerL-uxai** [comment]
<img width="1078" alt="screen shot 2017-09-14 at 10 56 47 am" src="https://user-images.githubusercontent.com/4743518/30440221-884a32f6-993b-11e7-9f2a-11746d99fcf4.png">

**Comment by xet7** [comment]
You can separately set each card color.
