### ISSUE TITLE
Thoughts on potential new logo/branding design?

### ISSUE THREAD

**Issue by rhelsing** [wekan/wekan#1219]
![wekan2](https://user-images.githubusercontent.com/392594/30395055-f4c90b86-9892-11e7-96ca-bd7dbc2a9508.png)
![wekan1](https://user-images.githubusercontent.com/392594/30395057-f5122afa-9892-11e7-85a8-2b43aa292901.png)

@xet7

**Comment by xet7** [comment]
[Wekan website](https://wekan.github.io)  shows this original logo @mquandalle bought as mentioned at #64

![wekan-logo](https://user-images.githubusercontent.com/15545/30397089-539af430-98d4-11e7-8107-2225e2f39c5e.png)

But in that same issue #64 there is also new icon by @neynah , icon is used at Sandstorm etc and has [svg in meta directory](https://github.com/wekan/wekan/tree/devel/meta/icons) and it's actually currently the official logo:

![wekan-150](https://user-images.githubusercontent.com/15545/30397173-a29bbbf0-98d4-11e7-84cd-24eb56aa9596.png)

In official icon, Wekan is shortened to We, to make icon more readable. I think new wider logo should have full name Wekan, and have design like in official logo.  I don't know yet how to improve excellent work by @neynah .

**Comment by ocdtrekkie** [comment]
Also worth noting is that the existing Wekan logo appears to be a custom typeface, which makes it uniquely distinct. The proposed replacements look like standard typefaces.

The full size logos would make it appear the pattern of three colored boxes is the "icon", but Nena's icon more properly represents lists of cards, I think.

**Comment by ocdtrekkie** [comment]
Any updated logo should probably come as a comprehensive set that replaces the full-width logo and the icons in varying sizes: https://github.com/wekan/wekan/tree/devel/meta/icons as the different sizes serve various functions in Sandstorm, and can be used in other purposes as small, medium, and large icons to represent the software.

**Comment by rhelsing** [comment]
@xet7 @ocdtrekkie this all makes sense. Issue #64 is quite the adventure! I had made these a while back because I wasn't a fan of the gradient in the logo and realized I had never posted them. Wanted to gauge the interest in some updated branding. I agree that it should be a complete package if its done.

**Comment by rhelsing** [comment]
The cursive version of the typeface can be easily modified (and possibly updated) to resemble the current typeface?

**Comment by ocdtrekkie** [comment]
@rhelsing yeah, #64 covers just about every possible question or concern, mostly because the old LibreBoard to-do was coming out of a complete redesign due to a Trello DMCA. So making sure everything including typeface are on solid legal ground is pretty key.

I think the gradient and bordering on the original logo is kinda mediocre, I'd support it being flattened out a bit. Note that an AI file for that logo does exist somewhere. (Nena has it, according to the old discussion, but I assume would not release it without Maxime's say so.)

**Comment by ocdtrekkie** [comment]
I would say between the Sandstorm icons (which are the majority of the way I see Wekan branding) and the fact that the default Wekan board is blue, I closely associate Wekan with it's blue-ish hue. I'd expect most Wekan logos to be blue-on-white or white-on-blue.

**Comment by neynah** [comment]
Awesome to see this revisited. I'm not sure what the desired direction is for Wekan branding in general but @ocdtrekkie & @xet7 make a good point that whatever the new/improved logo is there should be a comprehensive set that's consistent and covers different uses. Let me know how I can help. I'm sure I can dig up the AI file.

**Comment by ocdtrekkie** [comment]
@neynah If you are willing to shoot a copy of the source files for existing logos/icons you have to xet7, that'd be pretty great, since he's currently the maintainer of this project and probably should have access to such things at minimum.

**Comment by xet7** [comment]
@neynah 

Files can be attached to this issue in .zip archive.

**Comment by neynah** [comment]
[wekan-logos.ai.zip](https://github.com/wekan/wekan/files/1301122/wekan-logos.ai.zip)
![image](https://user-images.githubusercontent.com/855341/30403467-a6404e6c-9896-11e7-8170-af26a74f8d3c.png)

If you unclip the masks for the icons you'll be able to edit all the elements. Happy to help if anyone needs anything else.

**Comment by xet7** [comment]
I tried to edit logo, I had it looking something like this before Inkscape crashed and I lost my vector graphics edits. I'm don't often edit vector graphics so I'm not so good with it.

![wekan-newlogo](https://user-images.githubusercontent.com/15545/33389533-d7a5745a-d53b-11e7-8aa5-ce85ff6ee4a8.png)

It would be very helpful if someone would create something like this logo with proper dimensions for Wekan in SVG format and attach to this issue in .zip file.

**Comment by neynah** [comment]
Doesn't look exactly the same but maybe it's close enough. Let me know if this helps. (I could also do better to optimize the SVG file but it's not too bad.)

![wekan-1](https://user-images.githubusercontent.com/855341/33390966-5ae06b72-d4ec-11e7-8925-cd73b7421492.png)
[wekan-1.svg.zip](https://github.com/wekan/wekan/files/1514924/wekan-1.svg.zip)

**Comment by xet7** [comment]
@neynah 

Thanks, looks great!

**Comment by xet7** [comment]
@neynah 

Please include also your .ai file, because I was unable to open that .svg file in Inkscape for editing.

**Comment by xet7** [comment]
I added new logo to Wekan website, what do you all think?

https://wekan.github.io

**Comment by xet7** [comment]
@neynah 

Can you include your .ai file of new Wekan logo in .zip file please ?

**Comment by neynah** [comment]
[wekan-1.ai.zip](https://github.com/wekan/wekan/files/1620346/wekan-1.ai.zip)

**Comment by Gelmes** [comment]
The very first logo on this page is the best (My opinion) Cleaner, easier to make a clean looking icon out of. The last one is complex and has too much going on.
