### ISSUE TITLE
Feature Request: Board administration with web UI

### ISSUE THREAD

**Issue by DukeW** [wekan/wekan#1220]
It would be nice to be able as an admin to take "ownership" of boards. I have a Wekan instance running for 30 people, and some people don't archive there boards when there done. I would like to be able to take ownership of these old boards and archive them my self. Also sometimes a board creator is not present and new people need to be added to a board, right now I don't have a way of doing this.

**Comment by xet7** [comment]
@DukeW 

It's possible to change you as board admin [at MongoDB database](https://github.com/wekan/wekan/issues/1060#issuecomment-310545976), that link is mentioned at [Platforms page](https://github.com/wekan/wekan/wiki/Platforms). There is no Web UI for it yet. I have not tried can it be done with [REST API](https://github.com/wekan/wekan/wiki/Features#api).

Moved to #802

**Comment by chotaire** [comment]
As an admin, I will need to be able to list boards, also hidden boards and add myself to these boards or take ownership. This is especially important if updates break the installation, to be able to browse for possible wreckage in existing boards (as seen in v2.30 update).

So I am also requesting that these features are added to Wekan regardless of Teams/Organizations being implemented. An admin should always be able to do this. If you think this feature is too powerful, make it an optional flag? (e.g. superadmin)

**Comment by xet7** [comment]
Moved to #802
