### ISSUE TITLE
mail configuration question

### ISSUE THREAD

**Issue by liuliliGithub** [wekan/wekan#1223]
hi, i am first time use smtp, so i have one question ask you.
 i see a mail example configuration like this  :
```
export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
```
but i dont understand that in real env i need configure like this?
```
export MAIL_URL='smtp://user:pass@163.com:25/'
```
or like this?
```
export MAIL_URL='smtp://lili:lili's password@163.com:25/'
```

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by xet7** [comment]
Please reopen issue if you still have problems.

**Comment by liuliliGithub** [comment]
my MAIL_URL setting like this.
```properties
 MAIL_URL="smtps://liulili%40thunisoft.com:thunisoft@smtp.thunisoft.com:465"
```
but the error log is :
```log
Exception while invoking method 'forgotPassword' Error: connect ECONNREFUSED 172.16.20.20:465
    at Object.Future.wait (/usr/wekan-up/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at Mail._syncSendMail (packages/meteor.js:213:24)
    at smtpSend (packages/email.js:116:13)
    at Object.Email.send (packages/email.js:174:5)
```
i read you got link.but i dont know where i wrong

**Comment by liuliliGithub** [comment]
:reopen

**Comment by xet7** [comment]
@liuliliGithub 

On what [platform](https://github.com/wekan/wekan/wiki/Platforms) is this?
