### ISSUE TITLE
SSL behaviour - redirect

### ISSUE THREAD

**Issue by giezi** [wekan/wekan#1228]
## Issue
**Impacted version**: v0.38

**Server Setup Information**:

* Operating System: Ubuntu 14.04 LTS
* Deployment Method(docker  with https frontend (nginx)):
* Node Version: v4.8.4
* MongoDB Version: v2.4.9
* ROOT_URL environment variable (Is there a subfolder?): no

**Problem description**:
Since upgrade to v.038, wekan reloads the completely page if we click on a card and the following message appears in Chrome Console:

aa69abc285b66a07023a8e6ad8bc306f32379cfa.js?meteor_js_resource=true:32 Mixed Content: The page at 'https://zgrid.ch/b/wQNKCpSPudkXub46v/grid_cg_design/YmzaHDEK5hCQmtJtT' was loaded over HTTPS, but requested an insecure script 'http://XXXXX/packages/mquandalle_moment/locale/de.js?_=1505813066512'. This request has been blocked; the content must be served over HTTPS.

If we access wekan with http, the reloading behaviour is not present.

We have the following nginx reverse proxy config in place:

upstream websocket {
    server 127.0.0.1:4000;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;
        listen 443 ssl;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;

        ssl_certificate  /etc/nginx/ssl/zgrid.ch.crt;
        ssl_certificate_key /etc/nginx/ssl/zgrid.ch.key;

        client_max_body_size 5120m;
        client_body_timeout 600s;

        location / {
                proxy_read_timeout      300;
                proxy_connect_timeout   300;
                proxy_redirect          off;

                proxy_set_header    Host                $http_host;
                proxy_set_header    X-Real-IP           $remote_addr;
                proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto   $scheme;

                proxy_pass http://127.0.0.1:4000;
        }

        location ~ websocket$ {
                proxy_pass http://websocket;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }

}

Many thanks in advance for any help.

Best regards
Giezi4

**Comment by xet7** [comment]
@giezi 

In your Wekan docker-compose.yml or start-wekan.sh should be:

```
ROOT_URL=https://zgrid.ch

PORT=4000
```

Don't put 80 and 443 in same server block. Redirect to 443. Also AAAA DNS record is required for IPv6.

Do you really want IPv6 only? See:
https://codinginthetrenches.com/2013/12/14/nginx-ipv6only-setting-gotcha/

```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;
    server_name zgrid.ch;
    return 301 https://zgrid.ch$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443;
    server_name zgrid.ch;
 
    ssl_certificate  /etc/nginx/ssl/zgrid.ch.crt;
    ssl_certificate_key /etc/nginx/ssl/zgrid.ch.key;

    location / {
            proxy_read_timeout      300;
            proxy_connect_timeout   300;
            proxy_redirect          off;

            proxy_set_header    Host                $http_host;
            proxy_set_header    X-Real-IP           $remote_addr;
            proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto   $scheme;

            proxy_pass http://127.0.0.1:4000;
    }

    location ~ websocket$ {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
    }

}
```

**Comment by giezi** [comment]
Hi @xet7 

Thank you so much for your hint, wekan is now working perfectly!!

Have a great weekend!

Cheers
Reto
