### ISSUE TITLE
Add Feature: REST API: Create user despite disabling registration

### ISSUE THREAD

**Issue by soohwa** [wekan/wekan#1232]
I think registration and creation are two different things and the admin user should be able to create users with the rest api despite disabling registration.

Maybe a parameter can be added [here](https://github.com/wekan/wekan/blob/719c5404f3c1a4116115f27bd5726e9e1620b0d4/models/users.js#L581) in order to by bass [this](https://github.com/wekan/wekan/blob/719c5404f3c1a4116115f27bd5726e9e1620b0d4/models/users.js#L439) ?

**Comment by xet7** [comment]
@soohwa 

Could you try to do the change, and if it works for you, submit a pull request ?

**Comment by soohwa** [comment]
Okay I will try to do it the next few days even if I do not know anything developing meteor (x_x)

**Comment by soohwa** [comment]
I don't know if i did it with in the right way : [PR](https://github.com/wekan/wekan/pull/1241)

**Comment by xet7** [comment]
Thanks, it works !

Example of how to create new user with API:
https://github.com/wekan/wekan/wiki/REST-API#example-of-all-steps-of-create-user

**Comment by soohwa** [comment]
@xet7 Thx a lot !

**Comment by xet7** [comment]
Sorry, this still needs some work, so I need to revert this. #1249

**Comment by soohwa** [comment]
Yes sorry : https://github.com/wekan/wekan/pull/1251
I think it works (I tested a successful registration via web interface)

**Comment by soohwa** [comment]
I just forgot to modify one line by copying, this is why it worked for me ... :-D
