### ISSUE TITLE
Everytime need to start node main.js

### ISSUE THREAD

**Issue by ravi19950** [wekan/wekan#1234]
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System:ubuntu 14.04
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:v4.4.2
* MongoDB
MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):No

**Problem description**:Everytime need to start "node main.js" to use as URL
- *be as explicit has you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by xet7** [comment]
@ravi19950 

https://github.com/wekan/wekan-maintainer/tree/master/virtualbox

See there:
- /etc/rc.local startup script that runs Wekan at port 80 at startup
- run-wekan.sh that runs Wekan in loop, so it keeps running

Note that to really kill Wekan node, currently you need to use kill command.

I recommend you use Node, Mongo etc versions mentioned at:
https://github.com/wekan/wekan/blob/devel/Dockerfile

**Comment by xet7** [comment]
Please reopen issue if you still have problems.
