### ISSUE TITLE
Feature request: Option to change default to "tracking" from "muted" for all users / new users.

### ISSUE THREAD

**Issue by killua-eu** [wekan/wekan#1235]
A small feature request unless its already possilbe (then its a question how): I'd need to change the default "Watch" behavior so that its always on tracking for people invited into new board. I'd also need a way to change this globally for existing board/user relationships as well. Thanks lots, Pavel

**Comment by d3dbit** [comment]
Nice idea. I need it too.

**Comment by neonardo1** [comment]
+1

**Comment by eksell** [comment]
+1

**Comment by eksell** [comment]
+1

**Comment by xet7** [comment]
Moved to #3022
