### ISSUE TITLE
Delete the list of cards automatically refresh the problem

### ISSUE THREAD

**Issue by pqsky** [wekan/wekan#1237]
**Server Setup Information**:

Wekan version: v0.39
MongoDB Version: 3.2.14
Deployment Method: docker

**Problem description**:

Delete the list of cards, automatically refresh the list still exists, the need for the entire page refresh is normal.

It is now known that attachments in cards have the same problem.

**Comment by xadagaras** [comment]
The same happens when deleting checklists or checklist items.
