### ISSUE TITLE
Only image allowed for attachement ?

### ISSUE THREAD

**Issue by soohwa** [wekan/wekan#1239]
Isn't possible to upload any type of file ?
**Impacted version**: 0.39.0

**Comment by xet7** [comment]
@soohwa 

Works for me, I tried image, .deb file, .exe file on Wekan 0.39 built from source.

But Wekan only supports MongoDB 3.2.x. Uploading files crashes with MongoDB 3.4.x.

What file type you have problems with?

**Comment by soohwa** [comment]
It's weird, I have two installations (debian wheezy 64 bit) and it doesn't work on one.
And actually I found no matter the MIME type is, only the size matter. On one installation, only files above about 1Mo fail (installation behind nginx reverse proxy). Maybe it is the client_body_buffer_size or client_max_body_size parameter.

**Comment by soohwa** [comment]
At the javascript console I have numerous identical errors when I upload : 
```
Error: "Queue" failed [413] <html>
 <head><title>413 Request Entity Too Large</title></head>
 <body bgcolor="white">
 <center><h1>413 Request Entity Too Large</h1></center>
 <hr><center>ng... [undefined], r.makeErrorType/n@https://example.com:3000/__javascript__.js?meteor_js_resource=true:3:3461
a/<@https://example.com:3000/__javascript__.js?meteor_js_resource=true:292:3663
i/o</<@https://example.com:3000/__javascript__.js?meteor_js_resource=true:292:1026
A.once/<@https://example.com:3000/__javascript__.js?meteor_js_resource=true:1:8335
i/k.onreadystatechange@https://example.com:3000/__javascript__.js?meteor_js_resource=true:292:2322
```

**Comment by soohwa** [comment]
Issue fixed : I confirm it was that parameter : http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
