### ISSUE TITLE
Relative URL Redirect on Card Selection

### ISSUE THREAD

**Issue by AustinDoolittle** [wekan/wekan#1250]
## Relative URL Redirect on Card Selection
**Impacted version**: v0.41

**Server Setup Information**:
* Operating System: Ubuntu 16.04
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Running precompiled application as a service listening on port 81 (80 was in use)
* Node Version: v4.2.6
* MongoDB Version: v3.4.9
* ROOT_URL environment variable (Is there a subfolder?): http://<ip address>:81

**Problem description**:
When accessing the server using a hostname instead of the ip address listed in the root url, clicking to expand the card redirects the browser to the ip address listed in ROOT_URL as instead to redirecting you to the url relative to the hostname you are using. This causes the user to be logged out from that session, but does not redirect the user to the login screen until after the user clicks on any of the links in the page.

**Steps to Reproduce**
1. Edit your hosts file to include a hostname for the ip address listed as ROOT_URL
2. Access wekan by going to the hostname in your browser
3. Login, view a board
4. Click on a card
    * Expected Behavior: The card will open and the redirect url will be http://\<hostname\>/b/\<board id\>/\<board name\>/\<card id\>
    * Actual Behavior: The user session is ended and the redirect url is http://\<ROOT_URL\>/b/\<board id\>/\<board name\>/\<card id\>

**Comment by xet7** [comment]
@AustinDoolittle 

Does #1228 help you in this? Are you trying to run Wekan behind some other webserver?

**Comment by kivijoshi** [comment]
I am also having exactly same issue: followed "Manual Installation Steps"

**Comment by xet7** [comment]
You should setup ROOT_URL to your full Wekan URL, not IP address URL.
Like: http://hostname:81 or http://hostname:81/wekan

**Comment by kivijoshi** [comment]
Thanks xet7 . Solved
