### ISSUE TITLE
Can't add attachments to a card.

### ISSUE THREAD

**Issue by vgonzal** [wekan/wekan#1253]
## Issue:  Can't add attachements.

Container running in Ubuntu 17.04.

mquandalle/wekan                     <none>              a673ea652eef        21 hours ago        418MB
mongo                                latest              39f5c173b5d4        12 days ago         361MB

                   - MONGO_URL=mongodb://db
                   - ROOT_URL=http://Public_IP_of_docker_host

**Problem description**:
All works fine but when try to attache a file to a card the activity wall reports:
"username" attached null to "card"

The card show it has the attachment but isn't possible to download.

Reproduce the problem is easy. It shows up every time I try to attach something.

**Comment by xet7** [comment]
@vgonzal 

Don't use mquandalle Docker image.

Use [this Docker compose script](https://github.com/wekan/wekan-mongodb).

Also see https://github.com/wekan/wekan/issues/1254#issuecomment-332462216
