### ISSUE TITLE
Encountered errors while bringing up the project. No such image: sha256:

### ISSUE THREAD

**Issue by voicyfei** [wekan/wekan#1254]
## Issue
./docker-compose up

and i got the output:

wekan-db is up-to-date
Recreating eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_wekan-app ... 
Recreating eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3Recreating eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_wekan-app ... error
ERROR: for eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_eef23e8d3e2e_wekan-app  no such image: sha256:7b39e12782f50bc7028ac452fa94be13b5cb225f7aa93a3f7d8b632d3f64dddb: No such image: sha256:7b39e12782f50bc7028ac452fa94be13b5cb225f7aa93a3f7d8b632d3f64dddb

The wekan image worked well, but i can't register the first user. 
I noticed owner had fix the registeration problem  and update the new docker image. I deleted the old one and try to pull the new one, until I got the "no suck image" problem

How can i fix it?
thank you

**Comment by xet7** [comment]
@voicyfei 

1)  [Backup your MongoDB data](https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data)

2) [Cleanup and delete all Docker data to get Docker Compose working](https://github.com/wekan/wekan/issues/985#issuecomment-292256708) - only commands on that comment

3) `docker-compose up`

4) Restore MongoDB data, see 1)

5) If you want to run docker-compose in background, press Ctrl-C and then

```
docker-compose up -d
```
