### ISSUE TITLE
Notifications: Desktop / Bell / Browser

### ISSUE THREAD

**Issue by synergico** [wekan/wekan#1256]
Hi,
is it possible to have a notification bell, instead of always receiving notifications via email? 
Thanks

**Comment by Logicbloke** [comment]
I second this, a browser-based notification would be great!

**Comment by anthonymasset** [comment]
It would be a good feature : a bell and a desktop notification. It's typically what this kind of application should do.

**Comment by jshupptechnologies** [comment]
Yes. Having trello like bell that notifies immediately when someone mentions you would be a big plus in using this system in routine. Looking ahead to it !!

**Comment by rugk** [comment]
Maybe you can change the title of this issue to "browser notification", because that thing comes with a bell depending on your browser/system (configuration)? And it is likely better to implement browser notifications than some own custom bell.

**Comment by lvoisine** [comment]
I'm also searching for such a feature : I use Wekan in a production environment where email notifications could be overloading mailboxes, this solution would be the best

**Comment by d3dbit** [comment]
I think that it would be a great feature. In fact, I need it.

**Comment by yogi52** [comment]
Is it possible that I saw this 'browser notification'  feature in Sandstorm-wekan?

**Comment by xet7** [comment]
Maybe someone could try to add this:
https://github.com/saurabharch/push-rest

**Comment by xet7** [comment]
@yogi52 

I don't know how browser notification works on Sandstorm, is it possible for Wekan to send those. Maybe @kentonv knows?

**Comment by xet7** [comment]
Moved to #2026
