### ISSUE TITLE
Https reverse-proxy and file uploading problem in localhost environnement 

### ISSUE THREAD

**Issue by MehdyAmazigh** [wekan/wekan#1258]
Hello,
I’m using pound to have https on my localhost server, this work, I can access it from my lan.

The problem happens when I try to upload some avatars it shows me a broken image like this one :

wekan1

When I right click on it to go to the image’s URL, I have this error :

https://discourse-cdn-sjc1.com/standard2/uploads/wekan/original/1X/6b68c5c931e0379fc3168a3bcc591fa2cb6957b3.JPG

Error in method "/cfs/files/:value/:value/", Error: TypeError: Cannot read property 'avatars' of undefined
    at Object.httpGetHandler (packages/cfs_access-point.js:380:33)
    at Object.FS.HTTP.Handlers.Get (packages/cfs_access-point.js:462:27)
    at Object.accessPoint.get (packages/cfs_access-point.js:718:39)
    at packages/cfs_http-methods.js:604:33
It has something to do with the https:// as it works well on http://

Can someone explain me why ?

run-wekan.sh content :

cd /home/wekan/repos/wekan/.build/bundle
export MONGO_URL='mongodb://127.0.0.1:27017/admin'
export ROOT_URL='https://192.168.2.11'
export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
export PORT=80
node main.js
pound cfg :

User            "www-data"
Group           "www-data"
LogLevel        1
Alive           5
Control "/var/run/pound/poundctl.socket"

ListenHTTPS
        Address 0.0.0.0
        Port    443
        Cert "/etc/pound/ssl.pem"
        xHTTP           0
        Service
        BackEnd
            Address 127.0.0.1
            Port    80
        End
        End
End
Here is my config :

Wekan 0.37 (VB release https://wekan.xet7.org/release17.html)
Pound 2.6
Mongo 3.2.16
Ubutnu 14.04.5 LTS

**Comment by xet7** [comment]
@MehdyAmazigh 

Upgrade to your VB release to latest https://wekan.xet7.org

You could try something similar like at #1228 if pound has ability to proxy to other localhost port. I'm not familiar with pound.

If you are using VB release, then change Wekan to use some other port than 80.

For using hostnames like https://yourserver in local network, add server ip address and hostname to your /etc/hosts or similar hosts file on your operating system.

VirtualBox scripts are also at:
https://github.com/wekan/wekan-maintainer/tree/master/virtualbox

**Comment by LeJav** [comment]
I have exactlu the same problem with a reverse proxy + https.
I run wekan in a docker container.
Reverse proxy is nginx.
mongodb is 3.2.16 and wekan is 0.54
When I try to display the avatar, error is:
Error in method "/cfs/files/:value/:value/", Error: TypeError: Cannot read property 'avatars' of undefined
    at Object.httpGetHandler (packages/cfs_access-point.js:380:33)
    at Object.FS.HTTP.Handlers.Get (packages/cfs_access-point.js:462:27)
    at Object.accessPoint.get (packages/cfs_access-point.js:718:39)
    at packages/cfs_http-methods.js:604:33

Thanks for your help!

**Comment by xet7** [comment]
@LeJav

Do you use this recommended Nginx config ?
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

And Docker production settings?
https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by LeJav** [comment]
I have set same parameters for nginx as the ones at https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config, but still same error
For docker image, I have created it using ubuntu 16.04.1 base image and installing wekan from https://github.com/wekan/wekan/releases/download/v0.54/wekan-0.54.tar.gz.
I simply unarchive the tar.gz archive in /app.

**Comment by LeJav** [comment]
Hello again,

I have solved the problem.
I am really sorry, but it is my fault...
In my nginx config file I had a limitation on the methods used, and PUT was not allowed.
I did not see it in the log files when I investigated the problem.
It is now working as expected.
Many thanks for your support and sorry for my mistake.

**Comment by xet7** [comment]
@LeJav 

Thanks :)

@MehdyAmazigh 

If you still have this issue with newest Wekan, please reopen issue.

**Comment by fideo** [comment]
I apologize for LeJav but I am interested in knowing how you could solve the problem since I have the same problem and I can not solve it.
Thanks.
And... sorry for my English (i use google translate :P)

**Comment by LeJav** [comment]
I am sorry but I do not remember well. It is a long time and I do not use anymore...
Anyway, here is maybe the nginx configuration which made it work:

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

...

# for meteor.js     
proxy_http_version 1.1;                                                                                                                                                             
proxy_set_header Upgrade $http_upgrade; # allow websockets                                                                                                                          
proxy_set_header Connection $connection_upgrade;                                                                                                                                    

...

Hope this helps!

**Comment by fideo** [comment]
@LeJav 

I already found what was causing that error.
I had another **user** in my **nginx.conf** I changed it to **root** and my problem solved.

Thanks also.

**Comment by MehdyAmazigh** [comment]
It is almost always problems related to permissions or authorizations, on users or on HTTP methods

In case someone is asking, for Pound it's pretty easy :

ListenHTTP
   # ... some settings
   xHTTP 1 #Support GET, POST, HEAD, PUT, and DELETE
   # ... some more settings
End

Anyways, nothing related to Wekan directly, it's a configuration problem on the web server / reverse proxy, the only thing that could be done is to throw an error, but it is absolutely not necessary since it is remarkable by the obvious errors that the site returns.

**Comment by alkemyst** [comment]
Hello,
  I have the same issue with an OpenShift installation. In fact I cannot even attach documents to a card. Do you know how I debug this in OpenShift?

Thanks
Stefano

**Comment by alkemyst** [comment]
Hello,
  I am sorry for re-opening this issue: I managed to track down the problem of my installation at it was actually due to... disk space being over! In fact I could not upload any file. I moved to a larger disk and problem disappeared.
  Case closed for me.

'S
