### ISSUE TITLE
Re-design: Home page and activity feed

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#126]
Re-design discussions:
* [*current*] For the home page and the activity feed
* #94 For the board general view
* #127 For the card detailed view

---

This thread is about the home page re-design — for connected users. Personally I imagine it with an activity feed containing all events of starred boards and followed users, and in a right menu the list of all boards the user is a member of. This would be very similar to what github and gitlab do. On the mobile UI we would only display the board list, and put the event list in a menu.

Is there any other informations you would like to see on your LibreBoard home page?

I would also like to discuss the activity feed graphical design. This feed is probably going to be used in three places (1) the home page, (2) on a board, (3) and on a card. I like how gitlab draw a vertical time line linking both messages/comments and events (with an icon for each event). Maybe there is also a graphical way to display the card we are talking about, instead of saying "card “work to be done”", directly show a preview of the card on the home page.

**Comment by pwmvx1289** [comment]
The user could track/highlight certain cards or project so that detailed information will appear in a section in the home page.
I'm a 11th grade student from Hong Kong, experienced and interested in frontend development, web design and graphics design. Where else could I start with contributing?

**Comment by mquandalle** [comment]
@pwmvx1289 If you have some specific ideas about UI, feel free to share any mockup of it. Otherwise the code of the new design will be available in the coming days.

**Comment by mquandalle** [comment]
@pwmvx1289 If you have some specific ideas about UI, feel free to share any mockup of it. Otherwise the code of the new design will be available in the coming days.

**Comment by pwmvx1289** [comment]
@mquandalle My idea is something like this: https://moqups.com/pwmvx1289/Za8gVnkq
It's just a simple mockup highlighting the key sections.

**Comment by orangejuic** [comment]
@pwmvx1289 I think that's a little beside the point of the kanban board, especially if what we've started off with is the Trello design

**Comment by pwmvx1289** [comment]
@orangejuic I thought this was about the home and feed page instead of the kanban board?
