### ISSUE TITLE
Dose is it a preblem?The data of db.findOne() is different between client and server.

### ISSUE THREAD

**Issue by qishanquan** [wekan/wekan#1262]
## Why the data of Settings.findOne() is different between client and server
**Impacted version**: 0.43  docker-dev

**On Docker-dev Server's log**:
![image](https://user-images.githubusercontent.com/8034534/31012934-5640ee64-a546-11e7-8470-7ee65e872661.png)

**On Client**
![image](https://user-images.githubusercontent.com/8034534/31013014-a8f06446-a546-11e7-88a5-4fa255290547.png)

**My code**
* the file: ./models/settings.js
```
Settings.attachSchema(new SimpleSchema({
  ......

  dingtalk: {
    type: [Object],
    optional: true,
  },
  'dingtalk.host': {
    type: String,
    optional: true,
  },
  'dingtalk.corpid': {
    type: String,
    optional: true,
  },
  'dingtalk.corpsecret': {
    type: String,
    optional: true,
  },
  createdAt: {
    type: Date,
    denyUpdate: true,
  },
  modifiedAt: {
    type: Date,
  },
}));

.....

if (Meteor.isServer) {
  Meteor.startup(() => {
    const setting = Settings.findOne({});
    console.log(333, setting);
```

* the file: ./client/components/settings/settingBody.js
```
  ......
  currentSetting(){
    var ss = Settings.findOne();
    console.log(666, ss);
    return ss;
    // return Settings.findOne();
  },
  .....
```

**The Problem**

* I want use data 'setting.dingtalk'  in client, but I cannot get this data.
* Dose has it other setting on mongodb, or other's problem? I have no idea.

**Comment by nztqa** [comment]
Please try it (https://docs.meteor.com/api/pubsub.html)

Add publish
https://github.com/wekan/wekan/blob/devel/server/publications/settings.js
Add subscribe
https://github.com/wekan/wekan/blob/devel/client/components/settings/settingBody.js

**Comment by qishanquan** [comment]
@nztqa 
Solved, thank you.
