### ISSUE TITLE
reset password  keep sending English email

### ISSUE THREAD

**Issue by keekeiz** [wekan/wekan#1264]
## Issue
**Impacted version**: 0.43.0

**Server Setup Information**:

* Operating System: Windows 2008 R2
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):tar
* Node Version:v4.8.1
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):no subfolder

**Problem description**:
I'v setup wekan tool and registered a user with Chinese language. I can get invitation email in Chinese. However, when I reset my password,  I keep receiving password reset email in English. 
After making a lot investigation, I found the email language looks under control of the code in config/account.js , as follows
if (Meteor.isServer) {

  ['resetPassword-subject', 'resetPassword-text', 'verifyEmail-subject', 'verifyEmail-text', 'enrollAccount-subject', 'enrollAccount-text'].forEach((str) => {
    const [templateName, field] = str.split('-');
    Accounts.emailTemplates[templateName][field] = (user, url) => {
      return TAPi18n.__(`email-${str}`, {
        url,
        user: user.getName(),
        siteName: Accounts.emailTemplates.siteName,
      }, user.getLanguage());
    };
  });
}
when trying to print the result of user.getLanguage(), I keep getting "en".
the workaround is to change the function call to fixed string 'zh-CN', such as 
    Accounts.emailTemplates[templateName][field] = (user, url) => {
      return TAPi18n.__(`email-${str}`, {
        url,
        user: user.getName(),
        siteName: Accounts.emailTemplates.siteName,
      }, 'zh-CN');

Is there any limitation to get correct language in account.js or  not  a right  place to fix the prolbem?

**Comment by xet7** [comment]
This is already fixed.
