### ISSUE TITLE
sending email through exchange 2010 without auth in Windows

### ISSUE THREAD

**Issue by keekeiz** [wekan/wekan#1265]
## Issue
**Impacted version**: 0.43.0

**Server Setup Information**:

* Operating System: windows2008 r2
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
    Following # [Install Wekan from source on Windows](https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows), I've setup wekan and can create board and cards successfully. however, got stuck in email sending through exchange 2010. In my network situation, I've built many system which can send email without auth. 
But wekan always failed to send email , even if I followed all the ways in [Troubleshooting Mail](https://github.com/wekan/wekan/wiki/Troubleshooting-Mail) and tried any possibilities to set MAIL_URL and admin panel with port 25,465 and 587 and parameters set , such as 
?ignorTLS=true.
 
To make clear the issue,   I captued the smtp packet from wekan. because my exchange 2010 enable smtp receiving port on 25 and 587,  I set wekan with port =25 or 587 and notice wekan always send smtp packet STARTTLS followed by EHLO, at the same time wekan also give the error message as mentioned in https://github.com/wekan/wekan/issues/1120.  

In  [meteor/meteor#8637](https://github.com/meteor/meteor/issues/8637), i learn meteor send STARTTLS since 1.1.18 and also suspect exchange 2010 doesn't support STARTTLS, so the next step is to disable STARTTLS.
After going through the code, i found the workaround of the problem.  the code in file
meteor_directory\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connection\index.js 
 is for building smtp message . With comment of STARTTLS action code line 1010 to 1014 in the file , the smtp just send plain text smtp message and wekan can send email.

Moreover, one interesting thing is I found  wekan send smtp message to port 587 when no port is set in MAIL URL, such as MAIL_URL=smtp://mail.example.com. after I change to MAIL_URL=smtp://mail.example.com:25 and rerun wekan, it start send smtp to port 25.

I got the problem and workaround in windows, not sure whether it is working in other env or not.

any comments is welcome.

**Comment by xet7** [comment]
@keekeiz 

For compatibility with Exchange, you can use Davmail:
http://davmail.sourceforge.net/

Wekan SMTP => Davmail => Exchange
