### ISSUE TITLE
feature request - adjustable width of lists

### ISSUE THREAD

**Issue by johnleeming** [wekan/wekan#1266]
it would be great to be able to adjust the width of the lists, both individually and all across the board.  

It would also be good to have the option to fit all lists horizontally in the web browser window

**Comment by vrms** [comment]
also quite useful (borrowed from Odoos kanban) ... the ability to minimize or fold columns (lists in wekan terminology) which adds horizontal real estate

**Comment by neufeind** [comment]
In this context the option to create a new column maybe shouldn't take the space of an empty column itself but just be a plus-icon somewhere.
Would showing only a given number of columns be something the filter could be used for? Or a separate popout-menu to select which columns to show? Maybe together with an option "hide all empty" or so?

**Comment by xet7** [comment]
@johnleeming @vrms @neufeind 

Do you have screenshots or mockups what those suggested features should look like?  Do you have some kanban method or use case in mind?

Idea of horizontal view [has been discussed before](https://github.com/wekan/wekan/issues/781#issuecomment-306123045) but nobody has implemeted it yet.

**Comment by rgalonso** [comment]
(Copied from https://github.com/wekan/wekan/issues/1998#issuecomment-461993448, where this was originally mistakenly posted.)

I think I found the issue.  Namely, the flexboxes in the "list" CSS class are set to a hard-coded width of 270px.  Setting this instead to "auto" resolves the issue.  I believe the relevant source code is found here:

https://github.com/wekan/wekan/blob/6f0e0748e1eb6cac238edfcfcfcde1e41d613b96/client/components/lists/list.styl#L7

I've created a [pull request](https://github.com/wekan/wekan/pull/2175) that I believe will fix this.  I don't have admin rights on my local installation to test out the required change, but I did create [a Tampermonkey script (on GitHub)](https://github.com/rgalonso/tampermonkey_scripts/blob/master/wekan_auto_flex_lists.user.js) that resolves the issue, both on my local installation running version 1.55.0, and [the live demo version](https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h).

**Comment by xet7** [comment]
@rgalonso 

For this issue about adjustable width, your PR did work. I was only confused about calendar issue. Adjustable width could be added as alternative option. Comments, anyone?

**Comment by rgalonso** [comment]
@xet7 

Well, judging from your screenshot, and additional testing I've done based on your screenshot, it doesn't quite work as well as hoped.  For my use case where I don't have card titles that are excessively long, it does the trick.  But as you correctly found, for long card titles it throws the alignment off.

I'm testing some alternative strategies leveraging nth-last-child (see https://css-tricks.com/solved-with-css-logical-styling-based-on-the-number-of-given-elements/) and that's kind of working, but for some reason I keep having issues with the first column.  I'll update this issue with any info I find.

Truthfully, I'd recommend against merging my PR, unless it were done in a way where it's a non-default option.  I'm perfectly happy to keep using my Tampermonkey script to fulfill my use case until a proper solution is implemented.

**Comment by xet7** [comment]
List width was limited [in Wekan v3.25 to be smaller fixed size](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v325-2019-08-23-wekan-release), because previously it was unlimited and went way too wide. Pull requests welcome to make it configurable.

Alternatively, it's possible to pay 300 euro to me for my development time to make it configurable:
https://wekan.team/commercial-support/

**Comment by helioguardabaxo** [comment]
It's working fine on latest version:
![image](https://github.com/wekan/wekan/assets/24301085/60cae737-c9d3-4cb1-aa26-f4f8d94c0236)

**Comment by xator91** [comment]
> It's working fine on latest version: ![image](https://private-user-images.githubusercontent.com/24301085/263730676-60cae737-c9d3-4cb1-aa26-f4f8d94c0236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTk0ODQsIm5iZiI6MTcwNzI5OTE4NCwicGF0aCI6Ii8yNDMwMTA4NS8yNjM3MzA2NzYtNjBjYWU3MzctYzlkMy00Y2IxLWFhMjYtZjRmOGQ5NGMwMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA5NDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYjhhOWRmNDZhNzk0ZDk0ZTMzN2JjZWY2N2Y0ZTUwNGJkOWNlZWQ2MTE5MThiOTQ0NDZhYTgyOWRjYjNkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiFuSOxarAY81Mc7zCKirVxDnazIpd4XUnLtSesHXQE)

How did you change width size?

**Comment by xator91** [comment]
> > It's working fine on latest version: ![image](https://private-user-images.githubusercontent.com/24301085/263730676-60cae737-c9d3-4cb1-aa26-f4f8d94c0236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTk0ODQsIm5iZiI6MTcwNzI5OTE4NCwicGF0aCI6Ii8yNDMwMTA4NS8yNjM3MzA2NzYtNjBjYWU3MzctYzlkMy00Y2IxLWFhMjYtZjRmOGQ5NGMwMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA5NDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYjhhOWRmNDZhNzk0ZDk0ZTMzN2JjZWY2N2Y0ZTUwNGJkOWNlZWQ2MTE5MThiOTQ0NDZhYTgyOWRjYjNkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiFuSOxarAY81Mc7zCKirVxDnazIpd4XUnLtSesHXQE)
> 
> How did you change width size?

@xet7

**Comment by xet7** [comment]
@xator91 

What version of WeKan you have?

**Comment by xet7** [comment]
@xator91 

Version info is at:
```
sudo snap list
```
Or alternatively, after login, right to username / Admin Panel / Version

**Comment by xator91** [comment]
> @xator91
> 
> What version of WeKan you have?

6.09

**Comment by xet7** [comment]
@xator91 

This feature is at newest WeKan 7.x . You should wait for upcoming automatic upgrade, that will upgrade 6.09 to newest 7.x .
