### ISSUE TITLE
A non-intrusive way to add your own custom Theme, (and one UI tweak proposal)

### ISSUE THREAD

**Issue by synergico** [wekan/wekan#1268]
_Edit: after some tests, this hack might not really work. I'm closing this down_ 

I found a good way to add custom theme to Wekan  (yay) without breaking a lot of code, based on how Meteor' application and its build system default file load order rules. See more [here](https://guide.meteor.com/structure.html#load-order) 
_Disclaimer_: I'm no expert, so this is only my simple hack to theming :), and it worked for me. Please let me know if there are any side effects that I'm not aware of.

1. Creat an folder name `imports` at the root. (According to Meteor special folder rules, Any directory named `imports/ `is not loaded anywhere and files must be explicitly imported using `import`. )
2. You then add your e.g. `myTheme.css` file to that folder, maybe under a sub `imports/themes/ ` folder. 
3. Create a  `themeLoader.js` and put it in the `client/config/` folder with a simple line of import code:
  ` import '../../imports/themes/myTheme.css'; `
   Meteor will compile and minify all files in the `client/config `last, hence, your `myTheme.css `will override the default theme.

With this method, when you update Wekan, I don't think it will cause any major conflict. And because only a css file is loaded on the client side, it poses no real security threat (to my best knowledge). Alternatively, you can put the css file in the public/ folder.

I'm not sure if one user upload their own theme, would others have access to it in the `imports/` folder

**Comment by jeroenstoker** [comment]
Hi Synergico, does this still work? I tried, but I think I need to rebuild it after making these changes right?

(I'm a designer, with very little knowledge about Snap or Meteor)

**Comment by jeroenstoker** [comment]
Sorry for this... I am using snapcraft. I wil create an issue with the request for simply adding a custom URL in the admin.

**Comment by xet7** [comment]
@jeroenstoker 

There is already docs how to add theme as pull request:
https://github.com/wekan/wekan/wiki/Custom-CSS-themes

**Comment by jeroenstoker** [comment]
Thank you for reminding me @xet7 . I've read that issue a couple of times but I think that is not what I am looking for. I have created a new issue on:
https://github.com/wekan/wekan/issues/3086
