### ISSUE TITLE
Re-design: Card detailed view

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#127]
Re-design discussions:
* #126 For the home page and the activity feed
* #94 For the board general view
* [*current*] For the card detailed view

---

This thread is about the re-design of the card detailed view.

I don't have a lot of ideas to improve the design of Trello. We obviously need to adapt member avatars and card labels design to be consistent with the board, but that is noting significant.

A presentation that could be interesting is to open cards in a (large) sidebar on sufficiently large screen instead of using an overlay window. With this panel a user would be able to change to current detailed card with a single click, having the detailed card and the general board in the same spited screen. This would be similar two panels email clients, one for the list of emails and one for the detailed message of the currently selected email, allowing you to switch to another email in a single click. On smaller screen, we definitely want to use all the screen space for the current card, probably with an overlay window like in Trello.

Any other idea?

**Comment by ssimono** [comment]
I noticed that the comments in the card detailed view are stacked from bottom to top, which makes it difficult to read it in a chronological order.

What about ordering the comments from top to bottom ?
