### ISSUE TITLE
Question: How to add file:// hrefs

### ISSUE THREAD

**Issue by Turlin666** [wekan/wekan#1276]
I'm trying to add/create href links to file: // files on local disk, is it possible?

Thanks

**Comment by xet7** [comment]
@Turlin666 

I think this is not currently possible.

1) When I add this markdown to card description:

```
[Test](file:///home/user/Documents/index.html)
```

2) And click Test link, it has URL of of the card, not of the file.

Wekan also has some CSRF and/or XSS protection so this could be the reason also.

To make it kind of work, you would need to have some local webserver with the files, so files would have http or https url, like http://LOCAL-SERVER-IP-ADDRESS/files/test.txt

**Comment by Turlin666** [comment]
Thank you very much @xet7  for such a quick response.
