### ISSUE TITLE
[Enhancement] Improve "/api/boards" api endpoint to display private boards

### ISSUE THREAD

**Issue by TheBlusky** [wekan/wekan#1277]
As detailed in this part of the source code : 

https://github.com/wekan/wekan/blob/devel/models/boards.js#L581

```javascript
  JsonRoutes.add('GET', '/api/boards', function (req, res, next) {
    Authentication.checkUserId(req.userId);
    JsonRoutes.sendResult(res, {
      code: 200,
      data: Boards.find({ permission: 'public' }).map(function (doc) {
        return {
          _id: doc._id,
          title: doc.title,
        };
      }),
    });
});
```

The `api/boards` api endpoint only displays public boards.
It's not the intended behavior as this end point is authenticated.

It would be a good improvement to add private Boards visible to the authenticated user.

**Comment by iwkse** [comment]
Hi, I guess a fast way could be something like this:
'''
JsonRoutes.add('GET', '/api/boards', function (req, res, next, perm='public') {
    Authentication.checkUserId(req.userId);
    JsonRoutes.sendResult(res, {
      code: 200,
      data: Boards.find({ permission: perm }).map(function (doc) {
        return {
          _id: doc._id,
          title: doc.title,
        };
      }),
    });
});
'''
I would also handle the parameter perm to be only what is supposed to be (public or private) with something like
if (perm != 'public' || perm != 'private') return

**Comment by TheBlusky** [comment]
I don't think it's a good idea.
In case of a multi boards / multi user instance, you will see ALL boards.

**Comment by iwkse** [comment]
Do you mean all private boards but not only the ones related to the user?

**Comment by TheBlusky** [comment]
Here, we can see there's a function to check authorization: https://github.com/wekan/wekan/blob/devel/models/boards.js#L596 (`Authentication.checkBoardAccess`).
I guess we should filter uppon this property.

**Comment by xet7** [comment]
It's already possible to list private boards of user with API:
https://github.com/wekan/wekan/wiki/REST-API#information-about-boards-of-user
