### ISSUE TITLE
Admin announcement can be viewed without signing in

### ISSUE THREAD

**Issue by JavGuerra** [wekan/wekan#1281]
## Issue
**Impacted version**: 0.47

**Problem description**:
Admin announcement can be viewed without signing in.
The admin announcement should only be viewed by registered users once they are logged in.
The error occurs when a link to a card is used without being logged in Wekan.

![captura de pantalla de 2017-10-08 15-04-10](https://user-images.githubusercontent.com/6777224/31317128-91f18e04-ac3b-11e7-8d24-44cfdb73e1b4.png)

**Comment by nztqa** [comment]
It is site-wide announcement, not system login announcement.

It is easy to fix to members only.
```
diff --git a/client/components/main/header.jade b/client/components/main/header.jade
index ff6d075..51bccd0 100644
--- a/client/components/main/header.jade
+++ b/client/components/main/header.jade
@@ -49,13 +49,13 @@ template(name="header")
   if appIsOffline
     +offlineWarning

-
-  if hasAnnouncement
-    .announcement
-      p
-        i.fa.fa-bullhorn
-        | #{announcement}
-        i.fa.fa-times-circle.js-close-announcement
+  if currentUser.isBoardMember
+    if hasAnnouncement
+      .announcement
+        p
+          i.fa.fa-bullhorn
+          | #{announcement}
+          i.fa.fa-times-circle.js-close-announcement
```

**Comment by JavGuerra** [comment]
So, should the site-wide announcement also appear on the login screen? Or maybe the announcement only should appear, when an user is not being logged, on public boards.

I prefer that the announcement will be not displayed if you are not logged, but leave the decision at your discretion.

Than you nztqa

**Comment by nztqa** [comment]
It would be a good idea to add a radio button so that you can select an open range(public or  members only) on the announcement in admin panel.
At that time, what should we do when accessing public boats and private boards?
I would like to hear your opinion.

**Comment by JavGuerra** [comment]
Great idea (adio button), and I think it does not add much complication to the users.

About the the question "what should we do when accessing public boats and private boards?", I'm sorry, I did not understand the question very well, probably because I have not yet used the tool enough (and because my mother tongue is not English). Can you give me a step by step example to evaluate your proposal? I apologize.
