### ISSUE TITLE
Exception from sub activities id ... Error: Match error: Expected boolean, got undefined

### ISSUE THREAD

**Issue by karacsg** [wekan/wekan#1282]
## Issue
**Impacted version**: 0.47 (tried 0.37 as well, same issue)

**Server Setup Information**:

* Operating System: Centos 7.3
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): tar, httpd
* Node Version: 4.8.4
* MongoDB Version: 3.2.17
* ROOT_URL environment variable (Is there a subfolder?): no subfolder

**Problem description**:

Hi,

I have a wekan 0.10.1 and I try to migrate it's database under the latest wekan 0.47.
So I just dumped the database with mongodump and restored it on the new server with --noIndexRestore. 
I got the following exception in the log:
`Oct  9 08:37:29 wekan Wekan: Exception from sub activities id djFzCbxnu3jDgojNF Error: Match error: Expected boolean, got undefined
Oct  9 08:37:29 wekan Wekan: at exports.check (packages/check.js:57:15)
Oct  9 08:37:29 wekan Wekan: at [object Object].<anonymous> (server/publications/activities.js
:12:3)
Oct  9 08:37:29 wekan Wekan: at packages/matb33_collection-hooks.js:307:21
Oct  9 08:37:29 wekan Wekan: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Oct  9 08:37:29 wekan Wekan: at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Oct  9 08:37:29 wekan Wekan: at packages/check.js:130:16
Oct  9 08:37:29 wekan Wekan: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Oct  9 08:37:29 wekan Wekan: at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
Oct  9 08:37:29 wekan Wekan: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
Oct  9 08:37:29 wekan Wekan: at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Oct  9 08:37:29 wekan Wekan: at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
Oct  9 08:37:29 wekan Wekan: at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
Oct  9 08:37:29 wekan Wekan: at packages/ddp-server/livedata_server.js:559:43
Oct  9 08:37:29 wekan Wekan: Sanitized and reported to the client as: Match failed [400]
Oct  9 08:38:06 wekan Wekan: Exception from sub activities id eE4kNksFEHkJnoa7S Error: Match error: Expected boolean, got undefined
Oct  9 08:38:06 wekan Wekan: at exports.check (packages/check.js:57:15)
Oct  9 08:38:06 wekan Wekan: at [object Object].<anonymous> (server/publications/activities.js:12:3)
Oct  9 08:38:06 wekan Wekan: at packages/matb33_collection-hooks.js:307:21
Oct  9 08:38:06 wekan Wekan: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Oct  9 08:38:06 wekan Wekan: at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Oct  9 08:38:06 wekan Wekan: at packages/check.js:130:16
Oct  9 08:38:06 wekan Wekan: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Oct  9 08:38:06 wekan Wekan: at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
Oct  9 08:38:06 wekan Wekan: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
Oct  9 08:38:06 wekan Wekan: at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Oct  9 08:38:06 wekan Wekan: at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
Oct  9 08:38:06 wekan Wekan: at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
Oct  9 08:38:06 wekan Wekan: at packages/ddp-server/livedata_server.js:559:43
Oct  9 08:38:06 wekan Wekan: Sanitized and reported to the client as: Match failed [400]`

And Nodejs go up to 100% CPU usage, wekan slows down and then gives http error 504.

Can you please help me?

**Comment by xet7** [comment]
@karacsg

Try dropping mongodb database while restoring:

```
mongorestore --drop
```

**Comment by karacsg** [comment]
I restored with --drop.
Other thing is that the mongodb from which I was dumping is 3.4.2, can it be the problem?

**Comment by xet7** [comment]
Yes. Wekan does not support MongoDB 3.4.x, because uploading images will then crash Wekan.

Wekan only supports MongoDB 3.2.x.

**Comment by karacsg** [comment]
I know that, that's why the new server is using mongo 3.2, but it has the issue above.
My old wekan server has mongo 3.4 .

**Comment by xet7** [comment]
@karacsg 

Did you install Wekan from source to new server, could there be problem in that?
Can you try [Docker Compose version](https://github.com/wekan/wekan-mongodb) and [restore your data](https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data) there?

**Comment by xet7** [comment]
@karacsg 

Also after you have made backup of old server MongoDB, could you try new Wekan on old server with old MongoDB database and try to export data to Wekan JSON ?

**Comment by karacsg** [comment]
I used binaries from tar.gz on both servers.
I'll try the docker version (however I don't want to use docker on the server) and the new wekan with old server mongodb, and the data export.

**Comment by xet7** [comment]
Yes you can try locally with that Docker MongoDB 3.4.x if it's possible to export to JSON there.

**Comment by karacsg** [comment]
So, I tried the latest wekan (0.50) with mongodb 3.4.9 and restored the old server's data and it's working fine. Of course the attachment upload isn't working as you wrote, but other than that it's working.
No 100% CPU usage and no exceptions in the log.
So the issue is related with mongodb, especially difference between 3.4.x and 3.2.x.

**Comment by karacsg** [comment]
What exact mongodb version are you using with wekan? 3.2.?

Are there any plans for fixing the image upload issue with mongodb 3.4?

**Comment by xet7** [comment]
Wekan is only compatible with MongoDB 3.2.x, that does still receive updates to new versions.

We welcome all code contributions and bounties for fixing it.

It looks like having MongoDB 3.4 work is not at [Roadmap](https://github.com/wekan/wekan/wiki/Roadmap) or [Bountysource](https://www.bountysource.com/teams/wekan) yet. So all of those are to be done before trying to have MongoDB 3.4 work.

**Comment by xet7** [comment]
Moved to #1522
