### ISSUE TITLE
Access to web interface from wan via nat breaks side cards links.

### ISSUE THREAD

**Issue by Azbests** [wekan/wekan#1284]
## Issue
**Impacted version**: v0.47, v0.49

**Server Setup Information**:

* Operating System:
Ubuntu server 17.04
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
docker
* Node Version:
v8.6.0
* MongoDB Version:
v3.2.11
* ROOT_URL environment variable (Is there a subfolder?):
http://172.16.0.18, no subfolder wekan is installed on dedicated vm.

**Problem description**:
Wekan works fine from lan, but when I try to setup my wekan installation to be accessible from wan via nat. I can get to web interface just fine, but when trying to access various card entry side cards in boards I get timedout and I see that url changes from my wan FQDN to lan ip.

url changes from "somedomain.com/b/Qa82WkBFAdYGX78eP/welcome-board/uDLaW2we5z8XpMjkY"
to "172.16.0.18/b/Qa82WkBFAdYGX78eP/welcome-board/uDLaW2we5z8XpMjkY"

I think that I followed "Install-Wekan-Docker-in-production" article fully, but maybe there is something that I am missing in configuration?

**Comment by xet7** [comment]
Wekan only supports Node v4.8.4, MongoDB 3.2.x etc as memtioned in wekan/wekan repo Dockerfile.

Also see https://github.com/wekan/wekan/issues/1210

**Comment by Azbests** [comment]
My bad then, brain auto correct messed me. Will redeploy with v4.8.4.

Thanks for the reference to #1210. Will look into it and check how can I rework my setup.
