### ISSUE TITLE
Whitespace trimming breaks Markdown code block indentation

### ISSUE THREAD

**Issue by uusijani** [wekan/wekan#1288]
## Issue
**Impacted version**: 0.49

**Server Setup Information**:
* Operating System: Ubuntu 16.04
* Deployment Method: snap
* ROOT_URL environment variable (Is there a subfolder?): https://my-domain.com/kan (yes)

**Steps to reproduce**:
1. Create a card
2. Enter a description which consists entirely of a (markdown-styled) code block, i.e. indented with 4 spaces:

        first line
        second line

3. Save the description

**What happens:**
The description is plain, unstylized text.

**What I expect to happen:**
For the description to be rendered as a code block.

**How to work around this:**
I have to enter at least one non-whitespace character followed by at least two newlines before entering the indented code block. Urgh :(

**Comment by xet7** [comment]
@uusijani 

Description has markdown support, so if you want to use preformatted text, use 3 backtics above and below preformatted text.
https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

Related https://github.com/wekan/wekan/issues/926

**Comment by uusijani** [comment]
@xet7 Ah yes, the backticks are a cleaner workaround.

Not sure what you meant about the description supporting markdown, as markdown formatting of the description is what I was reporting on :)

In case my wording was unclear, I didn't mean I wanted to *preserve* the *indentation* going from the editor to the formatted view, but to use markdown's [indented code block](https://github.github.com/gfm/#indented-code-blocks) feature, which works just fine *unless* the indentation occurs right at the beginning of the description (or a comment), where the starting indention is trimmed off (thus breaking the code block formatting).

**Comment by xet7** [comment]
Wekan currently uses perak:markdown@1.0.5
https://github.com/wekan/wekan/blob/devel/.meteor/versions#L120

It's maybe here:
https://github.com/perak/markdown

Someone needs to check what that markdown currently supports and are there additional features to enable somehow.

**Comment by uusijani** [comment]
V0.55 didn't fix this unfortunately: my steps to reproduce still produce the unstylized text and not a code block.

tracking:        stable
installed:       0.55 (87) 125MB -
refreshed:       2017-11-19 19:51:40 +0200 EET

Perak's markdown ironically has had one issue reported about a reverse problem: someone had their [first line always treated as code block](https://github.com/perak/markdown/issues/5) (which was because they had indented the line). No bugs reported about the first line indentation being trimmed off.
