### ISSUE TITLE
Do we really need multiple checklists in a single card ?

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#129]
We plan to include “checklists” or car “sub-tasks” in the next release of LibreBoard. @hossein-khalili has been working on implementing this feature (he published his work on http://git.libreboard.com/Khalili/libreboard/commits/master).

It has implemented this feature in the same way than Trello did, more specifically
- A card can have multiple checklists
- A checklist have a title and a number of items

I don't understand why we would want any of these two features. If you want to create two separate checklists, why not put them in two different cards? And why checklists should have “titles”, it seems to me than the vast majority of users will just keep the default name ("checklist").

I encourage you to take a look at https://kanbanflow.com, I believe their “sub-tasks” feature provide the core functionality without additional unnecessary complexity.

Do I miss some use cases?

**Comment by Shekar73** [comment]
I agree having multiple checklists seemed redundant and so is the title. Most people are more concerned about identifying the items in the checklist than the title. In the checklist implementation-, 

-   When the new item needs to entered the previous item does not get emptied out. The previous item needed to be manually deleted to enter the new item
- Pressing the enter key does not post the item on the item list. It would be nice to have this functionaility where pressing the enter key will post the item similar to how cards are posted.
-  The space between the checklist title and completion bar seems to be too close. I guess if there is no checklist title this would be a non issue.

**Comment by mthart** [comment]
Here is the use case for two card sub-task lists I run into and need:

1) Sub-task list for acceptance/success criteria for the card/story to be considered "done".
2) Sub-list for dev tasks to complete the story, with points or hours estimated per task (and a roll up of total hours on card).

If you can do that, you will keep the simplicity of something like Trello, but include the planning and estimating ability of something like Pivotable Tracker or Version One.

**Comment by Shekar73** [comment]
On second thoughts I think having multiple checklists along with title would be useful. Consider the scenario where a card is assigned to two members who are incharge of its completion and they each have sub-tasks they have to complete separately or they each have sub-tasks for acceptance criteria along with tasks that are actually done, like the ones suggested above (in which case there will be 4 checklists!!).

**Comment by mthart** [comment]
Yes...there could be a list for each person, or one list but items are tagged and/or assigned to a person.

Pintask.me (down now?) had this feature.

**Comment by diego-vieira** [comment]
I like checklists with title on the same card because I can have each checklist based on subject.
Card: `Create new customer report`
Checklist: `Report Columns` - Options: `ID, Name, Email, Address`
Checklist: `Report Rows` - Options: `Format so email address is always lowercase`
Checklist: `Report Footer` - Options: `Count how many customers there are on the report`

This way, both the developer and the tester knows what to develop/test.

The card is all about the new customer report, creating multiple cards makes no sense to me TBH.
So :+1: for the multiple checklists.

**Comment by gomex** [comment]
I really need it.

**Comment by lusk** [comment]
We use multiple checklists all the time in our team. A card representing a feature would typically have a checklist for backend developer and a second one for a frontend guy. I guess there are other ways to achieve same thing, but this just works so well, that I would miss it. No big deal though.

**Comment by guarilha** [comment]
:+1: 
our team also uses multiple checklists on cards

**Comment by JayBeavers** [comment]
I also use multiple checklists on a card on Trello.  Similar to others, a Card often represents a Feature and each Checklist represents a set of tasks for the different people working on a Feature or different light workflows (e.g. polishing the feature, releasing the feature)...

**Comment by pdaoust** [comment]
I've never used it on Trello myself, so I'm a :-1:, but I see that a lot of people here like it.

**Comment by harshjv** [comment]
Yes, if there are multiple checklists, the title makes sense to me. Otherwise, for a single checklist, title seems redundant.

**Comment by expl0r3r** [comment]
:+1: for single checklist's

**Comment by gomex** [comment]
Hi. This feature is done? Is there any news about it?

**Comment by shangrila** [comment]
Bump.

**Comment by rlbisbe** [comment]
Hi, any news about this feature?

**Comment by kaziridwan** [comment]
(y) Multiple checklist makes sense, just to divide the tasks into sections... some people might even rearrange the list to decide what to set priority

**Comment by dialogik** [comment]
Yes, multiple checklists is a must have!

**Comment by zeineath** [comment]
+1:

**Comment by ottobackwards** [comment]
I use multiple checklists as well.  A 'feature' request may have several checklists with questions, concerns, high level milestones etc.  I guess you could argue that these don't need to be checklists, but could be bulleted lists ( so a combination of one checklist with some number of bulleted lists would work

**Comment by ottobackwards** [comment]
A thought would be, that instead of a checklist, you allow raw markdown support. So you could add one or more markdown areas ( and reorder them etc ).  But the thing about the checkboxes are the idea of notifications being tied to them

**Comment by MuhammetDilmac** [comment]
Hello dear,
Whats last condition for this feature.

**Comment by katrinleinweber** [comment]
Multiple checklists per card can be very useful for any kind of multi-step workflows: scientific work, recipes, etc. Even better would be the option to also insert multiple text fields in between the checklists.

**Comment by ILM126** [comment]
Would agree that this feature would be helpful and I'm sure many people would love this feature in Wekan, myself included. :+1:

**Comment by darkblinded** [comment]
Any updates on this issue?

**Comment by xet7** [comment]
Wekan already has checklists.

Closing issue.
