### ISSUE TITLE
Font issue with Polish diacritical signs [letters bigger than other in sentence]

### ISSUE THREAD

**Issue by chromas-cro** [wekan/wekan#1299]
## Issue
**Impacted version**: 0.50.0 and below

**Server Setup Information**:

* Operating System: Ubuntu Server 16.04LTS x64 
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): docker
* Node Version: v4.8.4
* MongoDB Version: 3.2.16
* ROOT_URL environment variable (Is there a subfolder?): http://(ipv4):8081

**Problem description**:
Some visual issues occurs when using letters with Polish diacritical signs (screenshot attached).
The letters seems bigger than other. Changing language settings not affect this issue in any way.
![issue_with_font](https://user-images.githubusercontent.com/8416406/31621953-53c90c2c-b29b-11e7-8f9d-ef2d6068bf54.png)

**Comment by xet7** [comment]
@chromas-cro 

What web font does show Polish correctly? At some other webpage? URL ?

**Comment by chromas-cro** [comment]
I have checked Roboto font on Google fonts and when I typed same sentence as in Wekan it was displayed well. So if this font is currently used in Wekan the problem my not be the font but maybe stylesheet or underlying os? I do not have possibility to check if same issue occurs on Windows server. Other popular font with polish diacritical signs is Lato, also found on Google fonts.

**Comment by xet7** [comment]
I am unable to duplicate this on Ubuntu 14.04.

You probably don't have some font installed.

![polish](https://user-images.githubusercontent.com/15545/31827582-daaa0fb6-b5c0-11e7-9bc7-ba60e49e9c7e.png)

**Comment by chromas-cro** [comment]
@xet7 
After thorough investigation i've found that underlying problem is roboto webfont (woff2 format) provided with docker image of Wekan (probably with all releases).

When generating webfont form truetype font a subsetting should be selected.
In default (basic) there is support for only western languages and polish characters are cut out to save font size.
![obraz](https://user-images.githubusercontent.com/8416406/31887668-7a66ac96-b7f9-11e7-8157-963b9f172f3b.png)
[screenshot from: https://www.fontsquirrel.com/tools/webfont-generator]

To generate proper webfont with multilanguage support Custom subsetting should be selected and all languages you want to suport:
![obraz](https://user-images.githubusercontent.com/8416406/31887844-241199fe-b7fa-11e7-894d-0f435e357590.png)

When I generated roboto-regular and roboto-bold selecting polish language from custom subsetting and replaced these fonts in /build/programs/web.browser/app/fonts/ directory in Wekan docker image the page was displaying properly using webfont (screen from firefox inspector, see Roboto remote):
![image](https://user-images.githubusercontent.com/8416406/31889408-06bb6e1a-b800-11e7-987c-25ad4f096dff.png)

So, why you had no problem with font? Probably you had roboto fonts installed locally as system font -in that case browser do not download webfont but use local version like ttf (see Roboto system) :
![image](https://user-images.githubusercontent.com/8416406/31889536-7d86d926-b800-11e7-867b-367b9ca18551.png)

So, if you be so kind and update webfonts in public/fonts dir [https://github.com/wekan/wekan/tree/devel/public/fonts](https://github.com/wekan/wekan/tree/devel/public/fonts) that would be great!

I hope you will read this and that my "investigation" will be helpfull for other Wekan users with similar problems :)

**Comment by xet7** [comment]
Thanks!

I use GitHub "Watch" repo feature so I do get emails from all new issues, comments etc, I do read everything.
