### ISSUE TITLE
Ability to vote on cards....

### ISSUE THREAD

**Issue by shekar73** [wekan/wekan#130]
It would be nice to have the feature to vote and display the number of votes in the cards

**Comment by Negaihoshi** [comment]
I think that is good idea,and it's useful.

**Comment by pwmvx1289** [comment]
I've been thinking of it too.
Another suggestion is a rating system.

**Comment by kayrules** [comment]
+1 vote for this feature. Trello have this feature under power ups.

**Comment by GammaNu** [comment]
+1

**Comment by skitoo** [comment]
:+1:

**Comment by megahertz77** [comment]
A must have ! Each one must be able to vote for a specific wanted feature ... so +1 or RATING BY STARS and AVERAGE as a result.

**Comment by viktor61** [comment]
Would be good. Any update on that?

**Comment by MyTheValentinus** [comment]
Update ?

**Comment by xet7** [comment]
Moved to #796
