### ISSUE TITLE
Error while export a board

### ISSUE THREAD

**Issue by thibaultgaillard** [wekan/wekan#1302]
When trying to export a board, nothing happen if there is a board user without profile.avatarUrl. Fixed by adding a default URL via a nosql request.

On Wekan 0.50.0.

Here is the stacktrace :

```
TypeError: Cannot read property 'avatarUrl' of undefined
    at models/export.js:121:11
    at Array.map (native)
    at Exporter.build (models/export.js:119:62)
    at models/export.js:32:62
    at packages/simple_json-routes.js:98:9
```

**Comment by xet7** [comment]
@GhassenRjab 

Can you look at this?

**Comment by xet7** [comment]
@thibaultgaillard 

I was not able to reproduce this. In standalone Wekan, I exported Wekan JSON, and had no avatars added, it did work. Also adding avatar to some user, when another one did not have avatar.
