### ISSUE TITLE
Mail notification work only from Member settings>edit notifications and not from board bar

### ISSUE THREAD

**Issue by chromas-cro** [wekan/wekan#1304]
## Issue
**Impacted version**: 0.50.0

**Server Setup Information**:

* Operating System: Ubuntu Server 16.04LTS x64
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): docker
* Node Version:  v4.8.4
* MongoDB Version: 3.2.16
* ROOT_URL environment variable (Is there a subfolder?): http://(ipv4):8081

**Problem description**:
No notifications when changing setting from board bar:
![image](https://user-images.githubusercontent.com/8416406/31942789-ce3b71da-b8c6-11e7-80f9-1d9f36ed64e6.png)

notifications are only sent when changed in Member settings:
![image](https://user-images.githubusercontent.com/8416406/31942832-f3d46e92-b8c6-11e7-8908-81058a562eaf.png)

Reproduce steps:
* no notification setting made in member settings>edit notifications menu,
* change notification setting on board bar to receive all notifications
* add card and wait for notification > no mail noti. came.
* change  notification setting in member settings>edit notifications to receive all notifications
* add card and wait for notification > notification received.

Expected result:
Notifications should be sent when changing settings in board bar without need to duplicating this setting in member settings menu.

**Comment by Logicbloke** [comment]
I agree, I had to enable both before getting anything. It's a little confusing to have user-based notifications. The best case where this would be useful I could think of is when you have a ton of boards and you don't remember which you are subscribed to and you don't want to receive any more notifications then you can just disable it from the master switch under the user menu.

**Comment by GuiGuiSoft** [comment]
Hello,

I have the same issue. I suggest to 

- add a third option in member notification settings to mute all board in one go.
- make the board notification settings work

Regards.
