### ISSUE TITLE
Uploading an avatar causes Wekan to crash.

### ISSUE THREAD

**Issue by bryantke** [wekan/wekan#1305]
**Impacted version**:  Latest on Github

**Problem description**:
When uploading a 100x100 6.6KB avatar or 75x75 4.16KB avatar Wekan crashes and requires a restart - and displays this to the end user:
" Wekan is loading, please wait. Refreshing the page will cause data loss. If Wekan does not load, please check that Wekan server has not stopped."
We are unable to upload avatars. Example avatars below.

![kali2](https://user-images.githubusercontent.com/9115212/31946273-00200fba-b897-11e7-8b1e-cebc62d6a105.png)
![kali](https://user-images.githubusercontent.com/9115212/31946274-01f409f4-b897-11e7-9c07-604141f38e68.png)

**Comment by xet7** [comment]
Wekan is only compatible with MongoDB 3.2.x etc versions mentioned in Wekan Git repo Dockerfile.

Using MongoDB 3.4.x causes crash when uploading file.
