### ISSUE TITLE
Mail troubleshooting in Docker

### ISSUE THREAD

**Issue by ChristopherM87** [wekan/wekan#1306]
Following on from this: [https://github.com/wekan/wekan/issues/1236](url)

Mail still does not work. And now I cannot find the wekan.log. It is a docker container.
I have /path/to/wekan/ and under there main.js, programs, README, server, star.json
Nothing in /var/log/
Where would the log file be?

**Comment by xet7** [comment]
Showing running docker containers and container IDs:

```
docker ps
```

Showing Docker logs:

```
docker logs CONTAINER-ID
```

**Comment by xet7** [comment]
docker-compose.yml file has many comments how to setup mail etc:
https://github.com/wekan/wekan-mongodb

**Comment by ChristopherM87** [comment]
Ah yes, I've done that but no error appears

**Comment by xet7** [comment]
Did you invite some user so that mail is sent? Or how it does not work?

**Comment by ChristopherM87** [comment]
As explained in my previous post, I did add the MAIL_URL and also configured the email settings in the admin panel (is that still needed if i've configured MAIL_URL?)

tried inviting but get an error saying email failed.

**Comment by xet7** [comment]
Please add your error message :)

**Comment by xet7** [comment]
What SMTP server are you using?

**Comment by ChristopherM87** [comment]
error message is "sending email failed" when inviting a user to a board

**Comment by ChristopherM87** [comment]
in docker run
--env='MAIL_URL=smtp://wekan:password@server.company.local:25' \

**Comment by xet7** [comment]
Does your email server use SSL at all ?

For Exchange DavMail can be used:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by ChristopherM87** [comment]
yes SSL/TLS and it's a dovecot and postfix server

**Comment by xet7** [comment]
Please change to have correct syntax:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml#L71-L83

SSL means that mail url starts with smtps , and port 25 is unencrypted email, you need to change it to correct SSL port.

**Comment by xet7** [comment]
Same settings also need to be in Admin Panel

**Comment by ChristopherM87** [comment]
according to this [https://www.limilabs.com/blog/ssl-vs-tls-vs-starttls-stls](url)

STARTTLS does not mean I have an SMTPS server

**Comment by ChristopherM87** [comment]
My command is actually:
--env='MAIL_URL=smtp://wekan@server.company.local:password@server.company.local:25' \

does the two @ make it fial?

**Comment by xet7** [comment]
Yes. That shoud be:
--env='MAIL_URL=smtp://wekan:password@server.company.local:25' \

**Comment by ChristopherM87** [comment]
just to clarify, if my username is my email wekan@server.company.local the comamnd should be

--env='MAIL_URL=smtp://wekan:password@server.company.local:25' \

**Comment by ChristopherM87** [comment]
The command is now:
--env='MAIL_URL=smtp://wekan:password@server.company.local:25' \

in admin panel:
SMTP host = server.company.local
SMTP port = 25
Username = wekan@server.company.local
Password = password
unchecking the "TLS support"

Still same error

**Comment by xet7** [comment]
With that kind of username, you really need to urlencode it, like with https://www.urlencoder.org/
--env='MAIL_URL=smtp://wekan%40server.company.local:password@server.company.local:25' \

**Comment by ChristopherM87** [comment]
Still the same error with command
--env='MAIL_URL=smtp://wekan%40server.company.local:password@server.company.local:25' \

Trying to find the wekan.log to see a more detailed error but cannot find it.

**Comment by xet7** [comment]
@ChristopherM87 

Are you starting Docker container with commandline? Or docker-compose.yml ? Can you add that whole text how you start Wekan, without passwords.

**Comment by ChristopherM87** [comment]
I start Wekan using a script:

```
docker run --name=${HN} -d --restart=always --net=den --ip=${IP}\
   --volume=/etc/localtime:/etc/localtime:ro \
   --env="HOSTNAME=${HN}.company.local" \
   --hostname="${HN}.company.local"\
   --dns="$DNS" \
   --env='PORT=8080' \
   --env='MONGO_URL=mongodb://wekan.company.local:27017' \
   --env="ROOT_URL=http://${HN}.den.local" \
   --env='MAIL_URL=smtp://wekan%40.server.company.local:password@server.company.local:25' \
   -v /srv/docker/wekan/dump:/dump \
   -v /srv/docker/wekan/db:/data/db \
wekan:latest

```

**Comment by xet7** [comment]
@ChristopherM87 

I did today some STARTTLS debugging, and got it working with following, you can test:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#starttls-sending-test-email-failed
