### ISSUE TITLE
Two factor authentication support

### ISSUE THREAD

**Issue by jpds** [wekan/wekan#1307]
## Issue
**Impacted version**: v0.50

**Server Setup Information**:
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker with Nginx.

**Problem description**: I'd like to see two factor authentication integrated into Wekan, this would be great for boards on public URLs on the Internet.

**Comment by xet7** [comment]
You can already add two factor auth with Google Auth by having [Nginx => ProxyBouncer Google Auth => Wekan](https://github.com/wekan/wekan/wiki/Let's-Encrypt-and-Google-Auth#b-caddy-lets-encrypt--google-auth-only-allowed-email-addresses--wekan).

On standalone Wekan this does mean 2 steps:
1) Login with Google Auth
2) Login with Wekan username and password

On Sandstorm there is only one step login.

Moved to #234
