### ISSUE TITLE
Issues editing WIP Limits

### ISSUE THREAD

**Issue by ocdtrekkie** [wekan/wekan#1310]
## Issue
**Impacted version**: 0.51

**Server Setup Information**:
Sandstorm

**Problem description**:
WIP Limits cannot be edited: When creating a WIP limit, it autopopulates the current number of cards in the list, and I am unable to change that text value. This pertains to #1278 and I am tagging @amadilsons as an FYI.

*Update:* On my work browser, I can see "up/down" arrows I couldn't see while testing Wekan 0.51 on my other device. The up/down arrows work correctly when visible, I expected to be able to change the number with my keyboard (which I believe should be an option). So this may be two issues: The number should straight-up be editable so that you don't have to spam click to get a high number, and we need to figure out when the buttons don't show for me and fix those.

**Comment by ocdtrekkie** [comment]
From what I can currently determine, the buttons do appear for me in Firefox, but do not appear for me in Edge. And note that when you click on the number, you get a flashing cursor in the box, yet cannot change said number.

**Comment by ocdtrekkie** [comment]
Note that from the screenshot in #1278 added by @xet7, whatever browser he is using does not show the buttons either.

**Comment by nztqa** [comment]
html5 `<input type="number">`  [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Browser_compatibility)

See also https://connect.microsoft.com/IE/feedbackdetail/view/2427100/inputs-with-type-number-do-not-have-spinner-controls-in-edge

**Comment by ocdtrekkie** [comment]
@nztqa That's interesting. And kind of unpleasant. :/

My impression though is that it shouldn't prevent one from editing the number directly though in the field. (I wasn't even expecting up/down buttons, I was mystified why the textbox wasn't editable.)

**Comment by ocdtrekkie** [comment]
@nztqa I noticed at the top of the MDN: "The browser may opt to provide stepper arrows", indicating that Edge is not technically wrong (although it'd be nice if they added it). It appears the onkeydown attribute is what's blocking this from being edited, so I created #1312 to remove it, as it seems to lack a constructive purpose.

**Comment by nztqa** [comment]
@ocdtrekkie I think it's OK.
