### ISSUE TITLE
Feature Request: WIP Soft Limits

### ISSUE THREAD

**Issue by darkuranium** [wekan/wekan#1311]
I think it would be nice to have the ability to make the WIP Limit on a list a "soft limit" --- that is, allow the user to go over the limit, but show some sort of a warning (e.g. different color of the column, different background, ...).

Most other Kanban boards --- at least the ones I've tried --- seem to use a soft limit by default (with no option for a hard limit), which makes them more flexible.

**Example:**
If I set the limit of a column to 3, I can at the moment not create more issues there, nor can I drag more into that list. However, sometimes, the situation may demand that I create (or move) more anyhow. For that, it would be nice to have the ability to do so *anyhow*, so that you can have e.g. "5/3" in progress (even if it's very undesirable).

**Comment by xet7** [comment]
@amadilsons

Can you look at this?

**Comment by amadilsons** [comment]
For sure, I will add a 'Soft Limit' option.
Sorry it took me so long to answer

**Comment by darkuranium** [comment]
Amazing, thank you!

And better yet, I now know *exactly* which platform I'll use as a self-hosted alternative to Trello (no points for guessing).

**Comment by amadilsons** [comment]
I've just submitted a new PR #1319 with this feature.
I've tried to test it for all the use cases I could remember but might have missed something!

Feel free to check it out and see if suits your needs :)
