### ISSUE TITLE
0.49 virtualbox image, regiester user problem.

### ISSUE THREAD

**Issue by xiaohelong** [wekan/wekan#1313]
## Issue
**Impacted version**: .0.49

**Server Setup Information**:0.49 virtualbox from official

* Operating System:
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:register success but no hints.
- *be as explicit has you can* 
- *describe the problem and its symptoms*
- *explain how to reproduce* 
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by xet7** [comment]
What hints?

After registering you can login at url /sign-in
