### ISSUE TITLE
Translation-issue for German / Limited possibility for translation-handling

### ISSUE THREAD

**Issue by neufeind** [wekan/wekan#1314]
In the activities on the right Wekan says "... hat ... zu dieses Board hinzugefügt". In German it must be "zu diesem Board". If you just say "this board" then "dieses Board" is correct. In German that depends on the usage.
In the i18n-files it seems to be based on "this-board" which, taken isolated, is correct. But together with "to-this-board" (which does not exist) it translates differently.

How could that be handled better? Having longer strings in the translation-files so that even such language nounces can be taken care of? And in the course of extending translation-possibilities (and thus unfortunately generating more strings which need translation) would the introduction of a translation-interface like Transifex maybe make sense then?

**Comment by frank-runge** [comment]
Es gibt ja bereits ein team bei transifex … https://www.transifex.com/wekan/wekan/dashboard oder habe ich etwas falsch verstanden?

Du beschreibst ein typisches Problem der deutschen Sprache, die im Gegensatz zu English (beinahe) alle beteiligten Objekte flektiert. "Longer strings" würde bedeuten, dass wir Deutschen die strings und Alternativen vorgeben müssen (die dann im Englishen immer gleich lauten)?

Vielleicht finden wir aber auch einfacherer Übertragungen, mit denen wir leben können?

---

There is already a team at transifex ... https://www.transifex.com/wekan/wekan/dashboard or did I get something wrong?

You describe a typical problem of the German language, which in contrast to English flexes (nearly) all involved objects. "Longer strings" would mean that we Germans have to give the "more strings" and alternatives which are always the same in English?

perhaps we find appropriate transfers (instead of translations) with which we are satisfied?

**Comment by neufeind** [comment]
Well, those strings don't come from a transifex then. I meant that with the current solution it's not really possible to have separate translations per usecase - it's just "what does that word mean in German" (or some other language). And usually the answer will be "it depends on the context".

**Comment by frank-runge** [comment]
Yes, I understood. I do not know transifex that good – isn't it possible to define different strings which consider the context like as in your example "this-board" + "to-this-board“? Years ago, I participated in a translation project and that was exactly what was possible there … But of course, this requires that we create a list of necessary strings for German-speakers (and so do the French and others who live in inflecting languages). The English speakers do not know what we have a problem with. Or do I understand something completely wrong?

**Comment by xet7** [comment]
Original English strings at en.i18n.json needs fixing and being more descriptive, so they can be translated better. Translation files are here:
https://github.com/wekan/wekan/tree/devel/i18n

When there is new features and additions git repo en.18n.json, I push changes to Transifex, make my Finnish etc translations, and pull all translations back to git repo. There has been cases before where I have made fixes to original English file.

**Comment by neufeind** [comment]
That's what this issue is about: Defining "longer strings" (or even just "IDs") where some might be completely identical in English but can be separately translated in other languages.
"this-board" is used in boardLabel which is used in client/components/activities/activities.jade for strings like "{{{_ 'activity-added' memberLink boardLabel}}}." That again is then in the translation-files like i18n/de.i18n.json ("activity-added": "hat %s zu %s hinzugefügt").
For the current cases it looks like we could simply change the translation to "diesem Board" (context: "to this board"). But as soon as somebody uses that same string for things like "delete this board" we can't simply reuse "this-board" again.

One possible (but larger) change might be to name "boardLabel" to "toBoardLabel", add the "zu" in German into that translation-string get rid of "zu" in places like "activity-added".
Other option might be separate strings "activity-added-board" and "activity-added-card" so that we don't have a sub-string boardLabel that gets translated and inserted separately. Hmm, maybe that would be cleanest?

**Comment by frank-runge** [comment]
NEUFEIND: "Other option might be separate strings "activity-added-board" and "activity-added-card" so that we don't have a sub-string boardLabel that gets translated and inserted separately. Hmm, maybe that would be cleanest?"

And how can we support this?

**Comment by xet7** [comment]
Would it be easier to translate if I move translations from Transifex to something like Pontoon?

Pontoon has demo site at https://pontoon.mozilla.org and docs at https://mozilla-pontoon.readthedocs.io/en/latest/index.html 

I could make website that has all Wekan screens like All Boards, Board, Admin Panel, etc.
Then click some text for example at Admin Panel, and translate in-place.

I have not tested this yet.

**Comment by frank-runge** [comment]
Hi,
I think it is better for the moment to leave it were it is.
