### ISSUE TITLE
Feature request: Attachment swipebox handling of non-images like viewing PDF etc

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1318]
## Issue
**Impacted version**: 0.52

When viewing images in swipebox, if attachment is not image, spinner is shown, and nothing happens. Maybe non-images like .pdf of .zip could be excluded from swipebox? Or could .pdf files be shown somehow?

@brooksbecton 

Do you have ideas how to fix this?

**Comment by brooksbecton** [comment]
For sure! I can look into excluding non-image file types from swipebox.

It also looks like there are a couple solutions to viewing pdfs such as [pdf.js](http://mozilla.github.io/pdf.js/) that I can also add in. 

Just for clarification, are there any requirements when adding in a new dependency? Does it have to be small or support back to a certain browser? 

Thanks :jack_o_lantern:

**Comment by xet7** [comment]
@brooksbecton 

You can add some Meteor PDF package:
https://atmospherejs.com/pascoual/pdfjs?q=pdf

For example for viewing:
https://atmospherejs.com/pascoual/pdfjs

Those files need to be included in Wekan, they can not be online outside dependencies, because Wekan is also used offline.

Some of those PDF packages can also generate PDF files, that would be handy if somebody wants to print Wekan board. There is probably feature request for that in issues already, but it's not implemented.

I don't know are there solutions for viewing other file types than images and PDF.

**Comment by whittssg** [comment]
Hmm.. Maybe http://viewerjs.org/ ?

**Comment by brooksbecton** [comment]
On my branch, non-image attachments do not get previews now, but images still preview with swipebox
https://github.com/brooksbecton/wekan/commit/b6f42f52455241ae03c0f70db116923fc4ccd60e

Next I will start looking for a previewer. 

Thanks! @whittssg I'll definitely check out this one.

**Comment by brooksbecton** [comment]
I have got a preview going for PDFs using PDFJS. I can render a PDF preview to a canvas element anywhere. 

As far as the UI, would something similar to the image preview be ok? Something like a modal that a user could flip through a PDF.

I didn't use viewerJS because I didn't see an npm package anywhere. I found a issue [207](https://github.com/kogmbh/ViewerJS/issues/207) which shows that other users also can't find a package. We would have to include it in the repo or reach out to a CDN which wouldn't support offline users.

**Comment by MyTheValentinus** [comment]
Hello,
Any update on this issue ?
Thanks

**Comment by finex** [comment]
Hi, I'm also interested in pdf preview. Is this feature planned?

**Comment by xet7** [comment]
I would recommend someone interested in this just looking at code and trying to add viewing pdf files. Related files are here:
https://github.com/wekan/wekan/tree/devel/client/components/cards

**Comment by MyTheValentinus** [comment]
Hello,
Any news on 2019-06 milestone ?
Thanks

**Comment by xet7** [comment]
@MyTheValentinus 

Oops I'll fix milestone dates, it all depends on all of Wekan community what gets progress and when. Also, it's just about 500 issues I'm trying to manage :) Showing PDF is not implemented yet.

**Comment by MyTheValentinus** [comment]
Hello @xet7
Thanks for your reply, but do you plan this feature to be added soon ?
The soft is very nice, but for full use i need pdf preview / open in new tabs when user click.
For the moment a link to open file in new tab when extension is .pdf could fix loading loop and could be a good workaround.
Thanks

**Comment by xet7** [comment]
@MyTheValentinus 

I could try does that workaround work, although no promises yet.

**Comment by MyTheValentinus** [comment]
@xet7 Major browsers they have a pdf viewer, use it ;)
I waiting your return !
Thanks

**Comment by xet7** [comment]
@MyTheValentinus 

Attachments code is here at `attachments.*`:
https://github.com/wekan/wekan/tree/master/client/components/cards

You can build wekan with `rebuild-wekan.sh` option 1 install deps, option 2 build, and use `start-wekan.sh` or `meteor --port 4000` and test with webbrowser. More developer docs at Wekan GitHub wiki. 

It would be best if you have time to help, because my own top priority is to get Wekan Snap/Docker/Sandstorm builds working #2533 , so I can again do official releases of Wekan. 

There is no bounties for this issue, so this is currently at bottom of my long todo list:
https://www.bountysource.com/issues/50971665-feature-request-attachment-swipebox-handling-of-non-images-like-viewing-pdf-etc
https://wekan.team/bounties/index.html

And any beginner Wekan contributor can add check that is file .pdf and open link in target `_blank`.

**Comment by MyTheValentinus** [comment]
Hello,
I work on this feature, i think my code is good but little quesiton about parameter "download" for {{url}} variable, when i put false or true, file are alway downloaded. 

`http://localhost:4000/cfs/files/attachments/hpnL4S7mF44cvRF5F/pdf-sample.pdf?token=eyJhdXRoVG9rZW4iOiJVTC0teUNnZzRuRm9HZUV1NFNGd3FXRUNGbjhCaUpmQ3VwVjl6VmdyeFp5In0%3D&download=true`

==

`http://localhost:4000/cfs/files/attachments/hpnL4S7mF44cvRF5F/pdf-sample.pdf?token=eyJhdXRoVG9rZW4iOiJVTC0teUNnZzRuRm9HZUV1NFNGd3FXRUNGbjhCaUpmQ3VwVjl6VmdyeFp5In0%3D&download=false`

Any ideas ?
Thanks

**Comment by MyTheValentinus** [comment]
I think is due to http header of application. 
If you check herders from response of server i have this: `content-type: application/octet-stream`
cmd: `curl -I http://localhost:4000/cfs/files/attachments/hpnL4S7mF44cvRF5F/pdf-sample.pdf\?token\=eyJhdXRoVG9rZW4iOiJVTC0teUNnZzRuRm9HZUV1NFNGd3FXRUNGbjhCaUpmQ3VwVjl6VmdyeFp5In0%3D\?download\=false
`

**Comment by MarcelB1988** [comment]
Hey there,

first of all thanks for you efforts an this amazing project! I like using Wekan! 
But I just need to clarify if this pdf problem still persists and if I can do something to change it? 
I am working a lot with pdfs and wanted to use them in the cards. But as you all know the preview still loading and nothing will be printed to screen. 
If there is a possible workaround, please assist - if you have the time to do so!

Thanks in advance for the answers!

Cheers,

Marcel

**Comment by xet7** [comment]
Hi @MarcelB1988 and others interested in this, here are some tips:

- search with `meteor js view pdf in browser`
- search PDF viewer or renderer packages from https://atmospherejs.com/?q=pdf
- some browsers like Firefox and Chrome have settings to view PDF instead of download 

Anyone that has time to do searches and tests and find some working example code would help.

**Comment by xet7** [comment]
I did try that above searhing for some hours yesterday but I did not get enough deep into rabbit hole to solve it completely yet. Help with searching and tests welcome.

**Comment by erlef10** [comment]
How is this FR going? Anyone actively working on it?

**Comment by xet7** [comment]
@erlef10 

AFAIK no. This would require someone with time to do web searches and figure out how to view PDF files in browser.

**Comment by xet7** [comment]
That PDF viewer should have copyfree licence http://copyfree.org/standard/licenses like MIT or BSD. Not GPL, Apache etc.
