### ISSUE TITLE
Feature request: linking to tickets

### ISSUE THREAD

**Issue by neufeind** [wekan/wekan#1321]
Besides regular links that could be added to a card linking to tickets would be "special".
In the easiest form this would just be "numbers" in the cards, which could be linked to an arbitrary ticket-system using a configurable URL-scheme.
Taking this further would then maybe involve supporting multiple ticket-systems (URLs), which could be handled by prefixing the number with an identifier, maybe having a default-system for all without that identifier. (1234, system2:2345, ...)
Exposing the ticketnumbers through an API would then allow custom integrations like moving a card to a different column upon status-change of a ticket or so. Defining/triggering such integration would then be up to a separate system.

**Comment by xet7** [comment]
@neufeind 

Anybody interested in this can already implement this without changes to Wekan.

In database, have table with these 2 rows:
- card url
- ticket number

Use [IFTTT with Huginn of Flogo](https://github.com/wekan/wekan/issues/1160) to make [REST API](https://github.com/wekan/wekan/wiki/REST-API).calls etc triggers to both ticketing system and Wekan, like adding ticket number to Wekan card, changing status etc.

If somebody tries to implement this, and something is not yet possible with REST API, add question about it to this issue.

**Comment by xet7** [comment]
Moved to #1160
