### ISSUE TITLE
Feature Request: Bidirectional sync Wekan <=> Trello

### ISSUE THREAD

**Issue by 8sd** [wekan/wekan#1322]
I'm using Wekan for private use. The Company I'm working at uses trello. 

I'd like to access the board at trello via the wekan front end.

It might be possible to use the trello api to do this.

**Comment by xet7** [comment]
@dudasfau

Please use Google search etc to look for various Open Source projects that use Trello API for import and export, and list those projects here. Also please check do you have access to Company Trello API.

Currently Wekan has only import from Trello, not export back to Trello and not sync with Trello.

Trello also has features that Wekan does not have, and Wekan has features that Trello does not have. So if somebody would implement sync back to Trello, it would only work for features that both have in common.

**Comment by thuanpq** [comment]
we should focus on improving wekan, dont depend on trello please

**Comment by xet7** [comment]
Starting points to any interested contributor that would like to send PR:
- https://github.com/DataFire/DataFire
- https://github.com/DataFire/Integrations
- Related: OneDB database UI, maybe add to Admin Panel? https://github.com/DataFire/OneDB

**Comment by xet7** [comment]
- Trello API https://developers.trello.com/reference
- Wekan OpenAPI https://github.com/wekan/wekan/pull/1965#issuecomment-455606651 , that will be later added to https://wekan.github.io/api/ or alternatively https://api.wekan.team , depending what would be preferred URL.
- Wekan API [login with form data](https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data), other calls with JSON
- Example sync Wekan <=> Gogs at https://github.com/wekan/wekan-gogs

**Comment by xet7** [comment]
Related to Trello API:

Anyone remember when at [Wekan v0.32 2017-07-30](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v032-2017-07-30-wekan-release) in Wekan was fixed security issue about files accessible without authentication?

That change is [coming to Trello](https://community.developer.atlassian.com/t/authenticated-access-to-s3/40647), so Trello attachments AWS S3 access will require Trello API key.

For sync, or mass import of all board from Trello to Wekan, there probably will be:
- Import boards etc with API
- Incoming Webhook to Wekan, so Trello Outgoing Webhooks for board changes can be updated to Wekan, without needing to poll for changes. Similar Outgoing Webhooks features are probably also at other Kanban software.

That probably means, I maybe will receive payment for mass import feature, after I first finish Search all boards feature. Maybe.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
