### ISSUE TITLE
Exception while invoking method 'login' TypeError: Cannot read property 'loginDisabled' of undefined

### ISSUE THREAD

**Issue by pierreozoux** [wekan/wekan#1331]
## Issue
**Impacted version**: latest

**Server Setup Information**:

* Operating System: coreos/docker
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):docker
* Node Version:docker
* MongoDB Version:lates
* ROOT_URL environment variable (Is there a subfolder?):
ROOT_URL=https://wekan.indie.host

**Problem description**:

I sent an email to somebody to join a board, and when she joins, she got an internal server error.

Here is the logs:
```
web_1  | Exception while invoking method 'login' TypeError: Cannot read property 'loginDisabled' of undefined
web_1  |     at server/authentication.js:4:13
web_1  |     at runAndHandleExceptions (packages/callback-hook.js:152:24)
web_1  |     at packages/callback-hook.js:159:12
web_1  |     at packages/accounts-base/accounts_server.js:142:13
web_1  |     at [object Object]._.extend.each (packages/callback-hook.js:128:15)
web_1  |     at AccountsServer.Ap._validateLogin (packages/accounts-base/accounts_server.js:139:27)
web_1  |     at AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js:345:8)
web_1  |     at [object Object].methods.login (packages/accounts-base/accounts_server.js:533:21)
web_1  |     at packages/check.js:130:16
web_1  |     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
web_1  |     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
web_1  |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
web_1  |     at packages/ddp-server/livedata_server.js:719:19
web_1  |     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
web_1  |     at packages/ddp-server/livedata_server.js:717:40
web_1  |     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
```

How can I help you debug that? Thanks for your help!

**Comment by gramakri** [comment]
It seems some wekan users hit this in the Cloudron app as well - https://git.cloudron.io/cloudron/wekan-app/issues/9 . Strangely, I don't see it in many other wekan instances

**Comment by gramakri** [comment]
This is easily reproduced when trying to login with an invalid username. Valid usernames (i.e already in db.users) work fine.

**Comment by ViViDboarder** [comment]
Verified as well! Didn't realize that UNs are case sensitive in Wekan which had me hitting this error.

**Comment by fcrozat** [comment]
issue is present when no user is created, when registering the first (admin) user

**Comment by nztqa** [comment]
> TypeError: Cannot read property 'loginDisabled' of undefined


NOT TESTED

https://github.com/wekan/wekan/blob/ba3c3f8289534fed7b1525821fbf0d2fd3bd5ec2/server/authentication.js#L4
```
-    return !options.user.loginDisabled;
+    const user = options.user || {};
+    return !user.loginDisabled;
```
