### ISSUE TITLE
Feature Request: hide old items

### ISSUE THREAD

**Issue by macau23** [wekan/wekan#1335]
## Issue
**Impacted version**: Latest (sandstorm)

**Server Setup Information**: Sandstorm

It would be nice for my "done" board to hide items past a certain age.

**Comment by ocdtrekkie** [comment]
Would this be like cards with checklists that have all items checked? What are 'done' cards.



Wekan already has archived cards, so I guess the feature you want here is a way to tell the cards to auto-archive after a point.

**Comment by thuanpq** [comment]
Archieved cards match this request

**Comment by macau23** [comment]
Done would mean cards in the designated column (the final column in my example, which I call the "done" column). It's a filter to hide cards in that particular column which have not been edited recently.

**Comment by ocdtrekkie** [comment]
So what you'd want is a way to specify an auto-archive timer that could be set on a column. (Since you can name any given column anything.) Also, and I don't know if Wekan does this, you'd need Wekan to know how long it's been in that specific list, as opposed to the card's overall age.

**Comment by whittssg** [comment]
If its anything like Microsoft Planners take on a Kanban then he means that the cards in the done column are completely collapsed and only show when the Accordion expand button is clicked in the list / column

**Comment by jpoles1** [comment]
@whittssg I think this would be a great solution for this functionality. 

In any case, done could possibly be used as a reserved title for columns which have the hiding/archiving functionality.

As it stands, my (rather poor) solution is just to archive the entire Done column every once and a while to get rid of my completed tasks which pile up.

**Comment by xet7** [comment]
Moved to #1499
