### ISSUE TITLE
Feature Request: Allow people to get predefined list on creating a new board

### ISSUE THREAD

**Issue by thuanpq** [wekan/wekan#1338]
this predefined lists are configured via admin panel

**Comment by whittssg** [comment]
I used to use this PR: https://github.com/wekan/wekan/pull/446 for something similar.. With that PR merged i was able to setup a board as a template, then every-time i created a new board i was able to choose the template board as a starting point (list names, checkbox lists etc)

**Comment by thuanpq** [comment]
that's nice, let me check your PR

**Comment by whittssg** [comment]
@thuanpq FYI its not my PR but it did work the last time i merged it (manually)

**Comment by xet7** [comment]
Moved to #786
