### ISSUE TITLE
Feature Request: Special list for done items

### ISSUE THREAD

**Issue by biji** [wekan/wekan#1339]
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System:
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

DOCKER

**Problem description**:
- *be as explicit has you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

Hi ,
It would be great if wekan can set special list for Done cards. This list will not highlight card's due dates when passed. This list will also show "enter date" for all cards

Thanks

**Comment by ocdtrekkie** [comment]
Out of curiosity, do you archive cards which are done? (ex. #1335 )

**Comment by biji** [comment]
Yes. That auto archive feature is cool. I may archive done cards after months

**Comment by xet7** [comment]
Some of this already exists at https://github.com/wekan/wekan-gogs , needs checking.
