### ISSUE TITLE
Feature: Clone Board

### ISSUE THREAD

**Issue by krawalli** [wekan/wekan#134]
Would it be possible to clone a existing board into a new one, so you can have a "template like board" as starting point for other boards?

**Comment by GITchristoph** [comment]
+1 ;-)

**Comment by fnkr** [comment]
+1

**Comment by mquandalle** [comment]
This feature is planned :-)

**Comment by fnkr** [comment]
@mquandalle I cannot open http://libreboard.com/boards/MeSsFJaSqeuo9M6bs/libreboard-roadmap, it stucks at the loading spinner. :(

**Comment by Shekar73** [comment]
:+1:  @mquandalle ..Also cloning a card, list across boards as well. I beleive I saw this in the roadmap, but not really sure....

**Comment by williamso** [comment]
+1

**Comment by xet7** [comment]
Pull request https://github.com/wekan/wekan/pull/446 will be merged later.

Closing issue.
