### ISSUE TITLE
It takes 5 clicks to delete a task

### ISSUE THREAD

**Issue by rruenroeng** [wekan/wekan#1341]

**Comment by xet7** [comment]
Yes, because normally you archive card so you can restore it back. Deleting is can not be undone, more clicks are by design. There was previously easily clicked button to delete a list and people deleted important list by accident, and that bug report was fixed.

**Comment by xet7** [comment]
If you want to delete cards faster, drag cards to new list, and delete that new list.

**Comment by rruenroeng** [comment]
Thanks Lauri,

My friend posted this feedback using my account when I was showing him my
personal board. All in all, I love what you've done and am excited to see
where it goes.

Best,
Ryan


On Nov 19, 2017 4:55 AM, "Lauri Ojansivu" <notifications@github.com> wrote:

If you want to delete cards faster, drag cards to new list, and delete that
new list.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wekan/wekan/issues/1341#issuecomment-345507859>, or mute
the thread
