### ISSUE TITLE
Move “Hide system messages” slider from cards to board

### ISSUE THREAD

**Issue by ArcturusB** [wekan/wekan#1345]
The slider to hide system messages from activity lists appears on every cards of a board, but it changes the visibility of system messages at the board level (ie. it affects all cards individually as well as the global activity list in the right panel). This behaviour is quite confusing because it is not what users would expect from having multiple sliders.

A solution could be to manage the visibility of system messages independently for each cards, but I don’t think this would be very useful for most users.

Therefore, having a single button to set the global visibility of these messages makes more sense. It could either be a slider next to the board activity list in the right panel, or a checkbox in the board hamburger menu. The latter option might better because it would not mislead users into thinking that the slider affects the visibility in the global activity list only.

**Comment by xet7** [comment]
That way slider would be much harder to find when it's needed.

**Comment by ArcturusB** [comment]
Sure thing, I had actually not noticed that the option was duplicated in the user settings until after I posted this issue. 

But on the other hand, having it on each and every card seems a overkill. Maybe having a single slider per board, at the top of the global activity list, can mitigate this.
