### ISSUE TITLE
Add Feature: Have all settings (SMTP etc) in environment variables or Docker Compose file, no need to setup manually at Admin Panel

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1351]
Have all settings (SMTP etc) in environment variables or Docker Compose file, no need to setup manually at Admin Panel.

**Comment by xet7** [comment]
Actually, I currently have SMTP settings in Docker Compose file, and nothing set at Admin Panel, and it seems to work. I'll probably check this later.

**Comment by Mythotical** [comment]
Just wanted to let you know that I've tested this, I left the settings alone in the docker-compose file and only edited the values in the Admin panel. It read from the docker-compose file. If I change the settings in the docker-compose file and not the values in the Admin panel it doesn't work. I had to set them both for emails to be sent successfully.
