### ISSUE TITLE
feature request: logout when closing browser

### ISSUE THREAD

**Issue by frank-runge** [wekan/wekan#1356]
When I close f.e. Safari without logout, I am still logged in when I reopen the browser.

A proper logout seems to me desirable, no?

(Firefox seems to do this).

Regards

Frank

**Comment by xet7** [comment]
This not Wekan specific setting at all, it is impossible to implement. It is browser specific setting does browser keep cookies and other browsing history when browser is closed. If cookies are not kept, or cookies are emptied, you are logged out from all websites.

To not keep cookies etc browsing history, one way is to use private browsing mode in webbrowser:
https://www.howtogeek.com/269265/how-to-enable-private-browsing-on-any-web-browser/

Other way is to configure webbrowser not to save any history at all, like cookies, browsing history, read webpages etc.  In Firefox:
Settings / Security / History / Firefox saves: No history

There are similar settings or addons for Safari, Chrome etc browsers, those instructions can be found with for example Google search.
