### ISSUE TITLE
Categories for cards

### ISSUE THREAD

**Issue by TNick** [wekan/wekan#1364]
I want to implement categories for cards. Each card would belong to exactly one category that is, by default, `(un-categorized)`.

The category would determine the aspect of the cards:

- background color;
- presence / absence of a border;
- the shape of the minicard;

(*v2*) Each category can host a template for the card that might be applied to cards at any time.

Categories would be organized in a tree, with one (possibly) inheriting properties from its patent(s). The tree of categories should be edited in right side panel by going to `Menu->Categories`. The panel needs `Add sibling`, `Add kid`, `Remove`, and items can be re-parented by drag-n-drop. Deleting a category deletes all its kids. All cards that ware in a deleted category are reassigned to `(un-categorized)`.

Changing the properties of a category (aspect of cards) can be done in same panel; each should allow inheriting from the parent / using the default for top level categories.

Changing the category of a card should be possible when the card is expanded.

I'm looking into implementing this feature for my personal use and, if needed, I could contribute it to the project. This is my first attempt at Wekan, so any ideas or suggestions about how to go about this are highly appreciated.

**Comment by xet7** [comment]
Moved to #709
