### ISSUE TITLE
Sandstorm SAML. Remove user from board.

### ISSUE THREAD

**Issue by sjoki** [wekan/wekan#1366]
Hi. 

Wekan version: 0.59.0~2017-11-23 Sandstorm version: v0.221 (2017-11-20)
I use SAML in sandstorm for authenticate users. When I create new board I can add any user to my board. But I dо not have any menu command or anything else to remove user from my board. I have only command 'Filter Cards' in the upper right corner 'Members' section.

What are the ways to delete a user?

**Comment by xet7** [comment]
Moved to #1192
