### ISSUE TITLE
Missing Binary but "linux-x64-57" exists

### ISSUE THREAD

**Issue by tenchugecko** [wekan/wekan#1367]
## Issue
**Impacted version**: 2.0.0

**Server Setup Information**:

* Operating System: Debian 9
* Deployment Method: Git
* Node Version: 8.9.1 NPM 5.5.1.
* MongoDB Version: 3.2
* ROOT_URL environment variable (Is there a subfolder?): no, where should that go?

**Problem description**:

it works on windows after npm install

when i git it up to my Debian Server, it says

 Try running this to fix the issue: /usr/bin/node /home/git/test/node_modules/synchronize/node_modules/fibers/build
Nov 29 19:18:20 worm _test[9284]: /home/git/test/node_modules/synchronize/node_modules/fibers/fibers.js:20
Nov 29 19:18:20 worm _test[9284]:         throw new Error('Missing binary. See message above.');
Nov 29 19:18:20 worm _test[9284]:         ^
Nov 29 19:18:20 worm _test[9284]: Error: Missing binary. See message above.

build doesnt work: node-gyp rebuild
gyp: binding.gyp not found (cwd: /home/git/test) while trying to load binding.gyp

i swearword had it working yesterday but dont know what i did to make it work.

**Comment by xet7** [comment]
You have too new versions of Node, npm etc. See github repo Dockerfile for correct versions. Also I have not yet figured out dependencies, because I support Ubuntu 14.04 and Debian 8 because of community request. Please use Docker version instead.

**Comment by tenchugecko** [comment]
sorry, github making me post things to wrong projects
