### ISSUE TITLE
When clicking on a card, redirect to localhost on VB image

### ISSUE THREAD

**Issue by gwir** [wekan/wekan#1368]
## Issue
**Impacted version**: 0.60

**Server Setup Information**: Just download de VBox image on a host private network (vboxnet1)

* Operating System:
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): VBOX image
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- When i click on a card the web page is redirect on a localhost page : http://localhost/b/JZctRWFyHNH2qDTkv/logiciels/fHQnyszdL8thcLjex .

It works inside the VM but don't if you access it from an other computer

Tank you

**Comment by xet7** [comment]
@gwir 

1) Setup ROOT_URL to your IP address at /home/wekan/repos/start-wekan.sh inside VM.

```
cd repos
./stop-wekan.sh
nano start-wekan.sh
```

2) Add have there your IP address, for example:

```
export ROOT_URL=http://192.168.1.100
export MAIL_URL=smtp://user:pass@mailserver.example.com:25/
export MAIL_FROM='Example Wekan Support <support@example.com>'
```

3) Save with Ctrl-o Enter and after that exit with Ctrl-x

4) Reboot VM.

5) Access Wekan at your network with IP address of VM, for example

Also check that your VirtualBox VM network settings are in bridged mode, as described in VirtualBox VM download page.

More details of settings at:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml

Hmm, maybe I need to add these to documentation to VM download page.

**Comment by xet7** [comment]
I added more details to bottom of VIrtualBox image download page.

**Comment by gwir** [comment]
Thank you!
