### ISSUE TITLE
Localization of email notification is not working

### ISSUE THREAD

**Issue by iwkse** [wekan/wekan#1374]
## Issue
**Impacted version**: 0.50 to 0.60

**Server Setup Information**:

* Operating System: Linux
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): built from sources/nginx
* Node Version: v4.8.4
* MongoDB Version:  2.4.10
* ROOT_URL environment variable (Is there a subfolder?): without subfolder

**Problem description**:
After setting the language to Italian, having also the browser language set to Italian language (shouldn't be mandatory though) the notification emails are sent in English language.

An example of the email:

Dear foo,

admin invites you to Wekan for collaborations.

Please follow the link below:
https://xxxxxx.com/sign-up

And your invitation code is: 241155

Thanks.

**Comment by xet7** [comment]
@iwkse

I don't have this bug in source install.

I'll check is there something wrong in Docker version.

What is your exact language code in your browser? Check it by clicking "Run code snippet" button at this page:
https://stackoverflow.com/questions/8199760/how-to-get-the-browser-language-using-javascript

It could be like it-it or something else.

**Comment by iwkse** [comment]
It is 'it'

**Comment by xet7** [comment]
@iwkse 

Please check Admin Panel / Version are you really running newest Wekan version 0.60.0

**Comment by xet7** [comment]
@iwkse 

I can not duplicate any problem with this. When there is Italian language selected, I get this email invitation:

Gentile user,
xet7 ti ha invitato su Wekan per collaborare.
Per favore segui il link qui sotto: http://192.168.123.123/sign-up
Il tuo codice d'invito è: 123456
Grazie.

**Comment by iwkse** [comment]
yes it's 0.60.0
With which browser are you testing?

**Comment by xet7** [comment]
Firefox.

**Comment by xet7** [comment]
With Chrome I also get invitation message in Italian.

**Comment by xet7** [comment]
@iwkse 

Try making backup, removing Wekan and MongoDB containers, starting Wekan again, and restoring data. I added more docs to:
https://github.com/wekan/wekan-mongodb#upgrading-wekan

**Comment by iwkse** [comment]
I'm not using docker, it's working fine now though
