### ISSUE TITLE
Bug?? Clicking a task doesn't work behind a reverse proxy

### ISSUE THREAD

**Issue by romu70** [wekan/wekan#1376]
## Issue
**Impacted version**: 0.60

**Server Setup Information**:

* Operating System: Linux
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker container
* Node Version:
* MongoDB Version: 3.4.10
* ROOT_URL environment variable (Is there a subfolder?): ??

**Problem description**:

I run Wekan in a Docker container, something like: http://IP:PORT, and my nas runs a reverse proxy which does the domain resolution and https part, something like https://mytasks

It works...almost. With boards, no problem, and I can create cards.

Problem occurs when I click on a card, in such case, Wekan responds on http://IP:PORT. So it doesn't work when I dialogue to my Wekan through my domain name.

**Comment by xet7** [comment]
@romu70 

You need to change Wekan ROOT_URL to https://tasks

**Comment by romu70** [comment]
Great, thanks!
