### ISSUE TITLE
Panel admin localization breaks header formatting

### ISSUE THREAD

**Issue by iwkse** [wekan/wekan#1378]
## Issue
**Impacted version**: 0.60.0

If you select from the admin a different language where "panel admin" is translated in a more verbose way, the wekan logo being at the center of the header will move to the new line and being not fully visible. You can reproduce it selecting Italian or French or other languages

**Comment by iwkse** [comment]
Setting the logo display as block-inline, fixes the issue
```
#header #header-main-bar .wekan-logo {
    display: block-inline;
```

**Comment by xet7** [comment]
@iwkse 

Can you provide pull request to Wekan devel branch?

**Comment by iwkse** [comment]
@xet7 I was just looking again at it, this solution is not really the best. I ended up customizing it more, adding the logo at the beginning and the text after that so that the text can be really big but nothing is going to happen.
Another way to workaround that would be to remove the width of the logo and this would make it floats on the right as soon as the title is too large.
The attached solution is not too nice because makes the logo dancing in the header according to the title size.
Let me know which you'd better go with

**Comment by xet7** [comment]
@iwkse

Please add 2 separate pull requests of your latest suggestions:
- more customized one
- floats on the right etc

I will test them.
