### ISSUE TITLE
Feature Request: Configurable Mail Rhythm

### ISSUE THREAD

**Issue by mirkofetter** [wekan/wekan#1382]
It would be nice if the time  mail notifications get buffered (currently fixed to 30 seconds) could be configured globally, by making the delay of `30000`  in `email.js` a variable that can be changed by the admin. 

Ideally, this would be a variable each user can set for herself to receive digest mails in more coarsed rhythms.

**Comment by xet7** [comment]
@mirkofetter 

Can you provide pull request to Wekan devel branch?

**Comment by mirkofetter** [comment]
I do not have a development enviroment setup for wekan yet. I will have a look into it next week - the required coding seems straightforward if i can add a variable `profile.notificationDelayInSec` to users.js and add it to the settings in userHeader.js/.jade for making it configurable

**Comment by xet7** [comment]
@mirkofetter 

Easiest is to use VirtualBox appliance https://wekan.xet7.org where all dependencies are already installed. There is  ~/repos/rebuild-wekan.sh script where you need to uncomment deleting ~/repos/wekan directory so your changes don't get lost.

**Comment by xet7** [comment]
@mirkofetter 

Have you looked at this?

**Comment by xet7** [comment]
Moved to #1160
