### ISSUE TITLE
attachement swipebox showing up unwanted

### ISSUE THREAD

**Issue by tjaisson** [wekan/wekan#1385]
## Issue
**Impacted version**: devel

**Server Setup Information**:

* Operating System: windows 7 x64
* Deployment Method: from sources using git - meteor installed with chocolatey
* Node Version: v8.8.1
* MongoDB Version: 3.2.12
* ROOT_URL : localhost:3000

Edit : But sandstorm demo is affected too.

**Problem description**:

In attachments section of card view the functions add-cover, remove-cover and confirm-delete cause swipebox to show up.

see
https://github.com/wekan/wekan/commit/d48043c7eef6e4314137d19149dbc7a7cbe4b615

**Comment by X-dark** [comment]
Fixed by #1386
