### ISSUE TITLE
wekan_settings (EMAIL MAIL_URL MAIL_FROM ) get reset after upgrade ?

### ISSUE THREAD

**Issue by idistech** [wekan/wekan#1393]
## Issue
**Impacted version**: 0.60(97 )

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Snap install
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?): no...

**Problem description**:
EMAIL configuration is working fine, I have configured the MAIL_URI and MAIL_FROM settings in the /var/snap/wekan/common/wekan_settings.sh file.

Snap seems to be automatically updating and managing versions, and is successfully updating as releases are made available ( Version 87,88, 97 installed and current->97 ).

The Problem is that these email settings keep disappearing, and I think its related to these automatic upgrades, the settings are not persisting. Is there a different/correct place I should be storing these values.
Ive had a search on the wiki, and forum, but apologises if ive missed this somewhere.
Many Thanks

Gary

**Comment by lichtamberg** [comment]
Where do you get this release numbers from? I installed Wekan via Snap too and I have version 60?

Also when I search for wekan, I get version 60?

```shell
snap find wekan
Name         Version  Developer  Notes  Summary
wekan-ondra  0.28     ondra      -      The open-source Trello-like kanban
wekan        0.60     xet7       -      The open-source Trello-like kanban
```

**Comment by idistech** [comment]
I think I have the same... the 'version' numbers might be no more than sequence numbers, ..

`:~# snap info wekan
name:      wekan
summary:   The open-source Trello-like kanban
publisher: xet7
description: |
  Wekan is an open-source and collaborative kanban board application.
  
  Whether you’re maintaining a personal todo list, planning your holidays with
  some friends, or working in a team on your next revolutionary idea, Kanban
  boards are an unbeatable tool to keep your things organized. They give you a
  visual overview of the current state of your project, and make you productive
  by allowing you to focus on the few items that matter the most.
  Depending on target environment, some configuration settings might need to be
  adjusted.
  For full list of configuration options call:
  $ wekan.help
snap-id: jtpboSYvTCEyHoutkkRo1SI9ioSMOUb3
commands:
  - wekan.database-backup
  - wekan.database-list-backups
  - wekan.database-restore
  - wekan.help
services:
  wekan.mongodb: simple, enabled, active
  wekan:         simple, enabled, active
tracking:        stable
installed:       0.60 (97) 125MB -
refreshed:       2017-11-29 13:00:10 +0000 UTC
channels:                              
  stable:        0.60             (97) 125MB -
  candidate:     0.60             (97) 125MB -
  beta:          0.60             (97) 125MB -
  edge:          0.60-13-ge2f768c (98) 125MB -
root@demo-07:~# ls -l /var/snap/wekan
total 16
drwxr-xr-x 4 root root 4096 Nov 11 16:32 87
drwxr-xr-x 4 root root 4096 Nov 11 16:32 88
drwxr-xr-x 4 root root 4096 Nov 11 16:32 97
drwxr-xr-x 5 root root 4096 Dec 12 09:16 common
lrwxrwxrwx 1 root root    2 Nov 29 19:02 current -> 97
`
I assumed the folder's in the /var/snap/wekan directory were versions, but , as you have identified, that was wrong...

**Comment by lichtamberg** [comment]
You are right, 97 is also showing up on snap info:

```shell
snap info wekan
name:      wekan
summary:   The open-source Trello-like kanban
publisher: xet7
description: |
  Wekan is an open-source and collaborative kanban board application.

  Whether you’re maintaining a personal todo list, planning your holidays with
  some friends, or working in a team on your next revolutionary idea, Kanban
  boards are an unbeatable tool to keep your things organized. They give you a
  visual overview of the current state of your project, and make you productive
  by allowing you to focus on the few items that matter the most.
  Depending on target environment, some configuration settings might need to be
  adjusted.
  For full list of configuration options call:
  $ wekan.help
snap-id: jtpboSYvTCEyHoutkkRo1SI9ioSMOUb3
commands:
  - wekan.database-backup
  - wekan.database-list-backups
  - wekan.database-restore
  - wekan.help
services:
  wekan.mongodb: simple, enabled, active
  wekan:         simple, enabled, active
tracking:        stable
installed:       0.60 (97) 125MB -
refreshed:       2017-11-29 14:00:10 +0100 CET
channels:
  stable:        0.60             (97) 125MB -
  candidate:     0.60             (97) 125MB -
  beta:          0.60             (97) 125MB -
  edge:          0.60-13-ge2f768c (98) 125MB -
```

For us the email settings worked fine during and after the upgrades :/

**Comment by lichtamberg** [comment]
Just for completeness, we added our settings with:

```
sudo snap set wekan mail-url="smtp://sender@example.com:pw12345@smtp.example.com:587"
sudo snap set wekan mailf-from="sender@example.com"
sudo snap set wekan root-url="https://example.com"
sudo snap set wekan port="8090" # for nginx forwarding
```

**Comment by xet7** [comment]
@kubiko 

Can you look at this?

**Comment by idistech** [comment]
Thank you xet7, 
Ive made sure the 
sudo snap set wekan mail-url="smtp://sender@example.com:pw12345@smtp.example.com:587"
sudo snap set wekan mailf-from="sender@example.com" 
is set as well,  Ill need an uplift in versions to see if it helps..

**Comment by lichtamberg** [comment]
Since 0.62 has been released some hours ago, I'm sure the snap will get updated accordingly soon.

**Comment by xet7** [comment]
Yes, I'm in progress of fixing snap build script so I can release Wekan 0.62 snap version.

**Comment by xet7** [comment]
I failed to fix build script, so I posted https://github.com/wekan/wekan-snap/issues/21 for @kubiko to help me.

**Comment by xet7** [comment]
Wekan v0.62 snap is now released, I fixed build script myself.

**Comment by lichtamberg** [comment]
I upgraded to 0.62 and all email settings still work. No problems.
