### ISSUE TITLE
Suggestion: Patreon Account

### ISSUE THREAD

**Issue by lichtamberg** [wekan/wekan#1394]
@xet7 Did you every think of creating a Patreon account?
I would support you with a small amount each month?

Wekan is really great ❤️ Thank you very much for your constant work on it!

**Comment by xet7** [comment]
@lichtamberg 

It's not possible for me to use Patreon.

Please send me private message at Vanila Chat ( my nickname there is xet7 ) to discuss other alternatives:
https://chat.vanila.io/channel/wekan

**Comment by xet7** [comment]
There is now some way to sponsor monthly: https://wekan.github.io/sponsors/

Current way is not Patreon. These are newest problems with Patreon:
- https://news.patreon.com/articles/understanding-apple-requirements-for-patreon
- https://news.ycombinator.com/item?id=41224853

Some others have also moved away from Patreon, for various reasons.
