### ISSUE TITLE
How can I run it locally?

### ISSUE THREAD

**Issue by rsouthpaw** [wekan/wekan#1395]
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System: macOS
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- *be as explicit has you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by xet7** [comment]
1) Install Docker for Mac  (Mac version includes Docker Compose)
https://docs.docker.com/docker-for-mac/install/#install-and-run-docker-for-mac

2) Edit docker-compose.yml script to have ROOT_URL=192.168.1.200:3000 and PORT=3000   (your Mac IP address and port) and start it with instructions here:
https://github.com/wekan/wekan-mongodb

3) Your local Wekan is at http://192.168.1.200:3000 for example. Register your first user, it will become admin. You can ignore error about missing email settings. Then login with your username and password.
