### ISSUE TITLE
REST-API: copy paste error in models/checklists.js ? 

### ISSUE THREAD

**Issue by Gobliins** [wekan/wekan#1396]
Hi, i think you have a copy paste error here:

`JsonRoutes.add('DELETE', '/api/boards/:boardId/cards/:cardId/checklists/:checklistId', function (req, res, next) {`
`    try {`
`      Authentication.checkUserId( req.userId);`
`      const paramCommentId = req.params.commentId;`
`      const paramCardId = req.params.cardId;`
`      Checklists.remove({ _id: paramCommentId, cardId: paramCardId });`

this looks suspicioulsy like the CardComment API. Because the checklist id is not used and the commentid is not present.

**Comment by sdorre** [comment]
const paramCommentId = req.params.commentId; 

and Checklists is a global object. 

Am I wrong ?

**Comment by Gobliins** [comment]
req is parameter of the function

**Comment by Gobliins** [comment]
Also you need to access `checklistId`..

It seems like the checklists API (POST,PUT,DELETE) is broken

**Comment by xet7** [comment]
Pull requests welcome, if someone knows fix to this.

**Comment by Gobliins** [comment]
I can fix DELETE which is pretty easy but the problems of POST on checklists is what i don't understand:

`Error: invalid json<br> &nbsp; &nbsp;at parse (/mnt/build/sthe/systems/.meteor/packages/simple_json-routes/.2.1.0.1mjtc03++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /mnt/build/sthe/systems/.meteor/packages/simple_json-routes/.2.1.0.1mjtc03++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/lib/read.js:108:18<br> &nbsp; &nbsp;at invokeCallback (/mnt/build/sthe/systems/.meteor/packages/simple_json-routes/.2.1.0.1mjtc03++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/mnt/build/sthe/systems/.meteor/packages/simple_json-routes/.2.1.0.1mjtc03++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/mnt/build/sthe/systems/.meteor/packages/simple_json-routes/.2.1.0.1mjtc03++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:308:7)<br> &nbsp; &nbsp;at emitNone (events.js:67:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:923:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:511:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:425:17)`

**Comment by Gobliins** [comment]
Also, is there an example on how to add items to the list in a request?

**Comment by andresmanelli** [comment]
This should be fixed in https://github.com/wekan/wekan/commit/4861da52a031ca6ee05755df894caef9d062be42

@Gobliins I forgot to add that endpoint in my latest commits, right now you can GET item, edit item, and DELETE item, but not create. Check `models/checklistItems.js`
