### ISSUE TITLE
Extend permissions further down to the card level

### ISSUE THREAD

**Issue by Logicbloke** [wekan/wekan#1397]
Hi,

As a project manager, I sometimes have to dispatch task to team members, but I'm mostly using one board per project rather than one board per team member. Why is it that any member added to the board with the normal permissions can edit other cards other than the ones assigned to him? To the very list bring the permissions down to the lists level.

The comment permissions look OK for this kind of thing but it's preventing the team member for ticking the checklists. 

Are kanban boards supposed to be one board per team member? 

Thanks!

**Comment by xet7** [comment]
Moved to #802
