### ISSUE TITLE
Add-Feature: Restrict registration to specific E-Mail domain

### ISSUE THREAD

**Issue by the-rene** [wekan/wekan#1399]
It would be nice, if we could have the feature in the config of wekan, to only allow self-registration with email  at a domain, e.g. exampe@exampleorganization.com but forbid example@anyelsedomain.com
I don't know how hard it is to implement this and I didn't yet finde a workaround to let wekan act with this behaviour. I'd really appreciate, if someone takes care of this.

**Comment by xet7** [comment]
@the-rene 

https://sandstorm.io platform already has this feature.

If someone wants this for Standalone Wekan, add bounty to this issue, instructions at
http://www.xet7.org/wekan

**Comment by the-rene** [comment]
Thanks alot, I didn't know about sandstorm.io and the Google Auth Option before.
I'll try to to convince my boss, that this is  necassary as a standalone feature,  to add a bounty to implement that feature or to pay you to implement it! But I can't make that decision.
 Anyways a big thanks to everyone, who worked on wekan!
