### ISSUE TITLE
How to change Docker ENV variable (change ROOT_URL)

### ISSUE THREAD

**Issue by CodeBrauer** [wekan/wekan#1403]
## Issue
**Impacted version**: 0.62

**Server Setup Information**:

* Operating System: Ubuntu 14.04
* Deployment Method: [Docker](https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production)
* Node Version: v4.8.6
* MongoDB Version: 3.2.18
* ROOT_URL environment variable (Is there a subfolder?): plesk.example.org:4000

**Problem description**:
We want to change the ROOT_URL ENV from `plesk.example.org:4000` to `board.example.org`

So I've set a proxy rule for my `board.example.org` vhost:

```sh
ProxyPassMatch   "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:4000/$1"
ProxyPass        "/" "http://127.0.0.1:4000/"
ProxyPassReverse "/" "http://127.0.0.1:4000/"
```

Now I want to change the ROOT_URL, what is the best approach?

**Comment by xet7** [comment]
@CodeBrauer 

- https://github.com/wekan/wekan/issues/1375
- https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config
- https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by CodeBrauer** [comment]
So I have to make a new container?

**Comment by xet7** [comment]
@CodeBrauer 

No. You stop Wekan container, change ROOT_URL environment variable, and start Wekan container again.

**Comment by xet7** [comment]
@CodeBrauer 

Do you have Nginx webserver in front of Wekan?

Did you start Docker with command line, on Docker Compose script?
https://github.com/wekan/wekan-mongodb

**Comment by CodeBrauer** [comment]
Yes, I used the docker compose script & I am only using Apache as proxy server, Nginx is off in our case.

I already did this:
- Exported mongoDB & saved persistent 
- Stopped & delete containers
- Recreated with new ROOT_URL with docker compose
- Imported Backup with mongorestore

**Comment by xet7** [comment]
@CodeBrauer 

You are linking to MongoDB v3.6.x documentation. Wekan only works with v3.2.x.

**Comment by CodeBrauer** [comment]
@xet7 

I've edited the link, but the command has changed since MongoDB 3.0.0 afaik

**Comment by xet7** [comment]
@CodeBrauer 

Ok, I edited wiki.

Next time you can add corrections etc directly to wiki.

**Comment by Michael2222** [comment]
> 
> 
> @CodeBrauer
> 
> No. You stop Wekan container, change ROOT_URL environment variable, and start Wekan container again.

Can you send me the 3 commands to stop container -> change ROOT_URL -> start container?

Thank you!

**Comment by xet7** [comment]
@Michael2222 

```
docker-compose stop wekan-app
```
Then change ROOT_URL in docker-compose.yml
```
docker-compose start wekan-app
```

**Comment by Michael2222** [comment]
Hello,
if I send the command with or without sudo "sudo docker-compose stop wekan-app" followed error occured:
```
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?
        Supported filenames: docker-compose.yml, docker-compose.yaml
```

**Comment by xet7** [comment]
@Michael2222 

Do you mean latest Wekan docker-compose.yml with LDAP etc?
https://github.com/wekan/wekan/wiki/LDAP

**Comment by Michael2222** [comment]
Hello,
now I have found another command to stop docker: sudo systemctl stop docker
Then I change in the file /home/michael/wekan-mongodb/docker-compose.yml to:
`- ROOT_URL=http://xy.dyndns.org`
save this file and restart docker again with: sudo systemctl start docker
But if I click to a wekan item, still this URL is used:
https://example.com/b/ySdcuhrDbjDayxFpL/privat/S7wDuTcBowcX5dXJb

What am I doing wrong?
Thank you!

**Comment by xet7** [comment]
Please try with newest docker-compose.yml at Wekan repo:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml

Add your settings to it.

**Comment by xet7** [comment]
And try it with:
```
docker-compose up -d
```

**Comment by Michael2222** [comment]
Hello,
thank you, with this commando it is working now!

**Comment by compumatter** [comment]
DOCKER SOLUTION
sudo service docker start
# this method will not require a container ID
sudo docker stop $(docker ps -q --filter ancestor=quay.io/wekan/wekan:master)
sudo vim /SM/data-drive/smw_projects/wekan-mongodb/docker-compose.yml
# Modify the ROOT_URL variable ie; 
# Comment out the existing http://localhost
# - ROOT_URL=http://localhost  #   <=== using only at same laptop/desktop where Wekan is installed
# Add the modified version by you / your company
- ROOT_URL=https://projects.mydomain.com  #   <=== using only at same laptop/desktop where Wekan is installed
(save and exit they docker-compose.yml)

OK, now let's commit those changes to the container with:
* docker-compose up -d

This will commit the changes **AND** start the container at the same time 

Done - test results in browser
