### ISSUE TITLE
Received notification after I commented

### ISSUE THREAD

**Issue by Logicbloke** [wekan/wekan#1406]
Hi,

I'm using v0.60 and I just got a notification after adding a comment on a card.

Card Creator: myself
Watching card? No
Watching List? Yes
Watching Board? Yes
Watching Notification? Enabled
Tracking Notification? Enabled

Does that sound normal or is this a bug?
Thank you.

**Comment by xet7** [comment]
Yes this is normal.

Moved to #1005
