### ISSUE TITLE
Docker image not updated

### ISSUE THREAD

**Issue by GuillaumeAmat** [wekan/wekan#1407]
## Issue
**Impacted version**: 0.63

**Server Setup Information**:

* Operating System: Fedora 27
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker image (latest)
* Node Version:
* MongoDB Version: Docker image mongo:3.2
* ROOT_URL environment variable (Is there a subfolder?): No subfolder

My installation is stuck to the 0.60 version. You recently released 0.61 to 0.63, the Docker image has been updated (as I can fetch a new :latest image), but I still got the 0.60 running on my server (based on the About section and the missing new features).

**Comment by xet7** [comment]
@GuillaumeAmat 

Remove Wekan Docker container and Docker image and reinstall it:

```
docker-compose stop

docker rm wekan-app

docker rmi wekanteam/wekan

docker-compose up -d
```

**Comment by GuillaumeAmat** [comment]
Ok I was not aware of the `wekanteam/wekan` Docker image and still using the `mquandalle/wekan` one.

Thanks
