### ISSUE TITLE
Not working on FreeBSD and no error message

### ISSUE THREAD

**Issue by snowyurik** [wekan/wekan#1409]
## Issue
**Impacted version**: 0.63

**Server Setup Information**:

* Operating System: FreeBSD 11.0-RELEASE-p1
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): tar
* Node Version: 8.8.1
* MongoDB Version: v3.2.11
* ROOT_URL environment variable (Is there a subfolder?): no subfolder

**Problem description**:
while running with 'node main.js' app does not report any problem, but browser can't establish connection and 'netstat -an | grep LISTEN' shows no changes in listening ports. So httpServer not started.

After a while I've found that there is problem during initialization inside this piece of code 

File 'programs/server/app/app.js'

```
Attachments = new FS.Collection('attachments', {                                                                       // 1
   stores: [// XXX Add a new store for cover thumbnails so we don't load big images in                                  // 2
   // the general board view                                                                                            // 5
   new FS.Store.GridFS('attachments', {                                                                                 // 6
     // If the uploaded document is not an image we need to enforce browser                                             // 7
     // download instead of execution. This is particularly important for HTML                                          // 8
     // files that the browser will just execute if we don't serve them with the                                        // 9
     // appropriate `application/octet-stream` MIME header which can lead to user                                       // 10
    // data leaks. I imagine other formats (like PDF) can also be attack vectors.                                      // 11
     // See https://github.com/wekan/wekan/issues/99                                                                    // 12
     // XXX Should we use `beforeWrite` option of CollectionFS instead of                                               // 13
     // collection-hooks?                                                                                               // 14
     // We should use `beforeWrite`.                                                                                    // 15
     beforeWrite: function (fileObj) {                                                                                  // 16
       if (!fileObj.isImage()) {                                                                                        // 17
         return {                                                                                                       // 18
           type: 'application/octet-stream'                                                                             // 19
         };                                                                                                             // 18
       }                                                                                                                // 21
                                                                                                                        //
       return {};                                                                                                       // 22
     }                                                                                                                  // 23
   })]                                                                                                                  // 6
 });   
```
Looks like it fail on `new FS.Store.GridFS(`

How to reproduce (note it's FreeBSD only problem):
1) Download latest release https://github.com/wekan/wekan/releases/download/v0.63/wekan-0.63.tar.gz
2) Untar
3) follow notes in README (npm install and env variables)
3.1) set PORT to 8080
4) node main.js
5) from different console run 'netstat -an | grep LIST'
6) no 8080 port in output

To check if it's mentioned block of code
7) open file 'programs/server/app/app.js' for editing
8) search for 'attachments.js', broken block of code will follow
9) surround block of code with console.log commands like `console.log('before'); .... code block here .. console.log('after');`
10) node main.js
You will see that console.log('before'); command had been evaluated, but console.log('after') had not been.
11) open app.js again and comment broken block out
12) node main.js
You will see, that console.log('after') had been evaluated. But Attachment variable had not been initialized and that cause error message. So the problem is somewhere inside mentioned block of code.

Good luck, hopefully Wekan will be available for FreeBSD soon )

**Comment by xet7** [comment]
@snowyurik 

This error is not specific to FreeBSD only, see https://github.com/wekan/wekan/issues/1333#issuecomment-355756823

Thanks!

**Comment by xet7** [comment]
Moved to #1333
