### ISSUE TITLE
Attachments cannot upload, the server response 500 status

### ISSUE THREAD

**Issue by BruceZCQ** [wekan/wekan#1411]
<img width="1249" alt="wx20171231-134614 2x" src="https://user-images.githubusercontent.com/2174082/34459661-137528f0-ee31-11e7-9957-ed31f6a10cd0.png">

**Comment by xet7** [comment]
@BruceZCQ 

Wekan crashes when uploading with MongoDB 3.4.x, it's a known problem. What version you use?

Wekan works only with MongoDB 3.2.x.

**Comment by BruceZCQ** [comment]
I am trying wekan on https://wekan.indie.host

**Comment by xet7** [comment]
@BruceZCQ 

I sent email to indie.host asking for more information.

**Comment by xet7** [comment]
@pierreozoux

Do you need fixes for Wekan?

**Comment by pierreozoux** [comment]
@BruceZCQ I just tried it worked, can you show me the networked tab with the response from the server.
What is the size of the attachment? (the limit is 1mb currently)

**Comment by BruceZCQ** [comment]
<img width="1291" alt="kanban1" src="https://user-images.githubusercontent.com/2174082/34676134-cd7b8f6e-f4c6-11e7-99c0-0fb49a496336.png">
maybe the file  is  too large. thanks @xet7 @pierreozoux
