### ISSUE TITLE
Wekan integration with Metabase

### ISSUE THREAD

**Issue by neurokernel73** [wekan/wekan#1415]
I just installed Wekan on Mac OS X through Meteor and create some boards with its users. Now I'm trying to integrate Wekan with Metabase to generate some statistics, how can I get the MongoDB user/password to configure the Metabase connection?

Regards.

**Comment by xet7** [comment]
@neurokernel73 

Check where mongo is running:

```
meteor mongo -U
```

See https://stackoverflow.com/questions/22020580/how-to-connect-mongodb-clients-to-local-meteor-mongodb

There is no username and password used.

Then connect to it with Metabase.

**Comment by neurokernel73** [comment]
Thanks xet7, now I can see the wekan MongoDB on Metabase, but I can't see any table on the Tables section, any idea?

**Comment by xet7** [comment]
@neurokernel73 

Are you looking at correct MongoDB database? In MongoDB tables are called collections.
