### ISSUE TITLE
Add Feature: Copy card with unchecked checklist items

### ISSUE THREAD

**Issue by fbatschi** [wekan/wekan#1416]
Feature Request: Add a new checkbox to the "Copy card" dialog which lets you decide whether you want to have the potential checklist items in the same state as they currently are, or whether they should be unchecked.

Background:
I have cards with many checklist items. Once I am done with all the items, I need to copy the card with the same content for the next month. Currently it copies the card exactly as it is right now, meaning all checked items are also checked in the new card. Would be great to have a real "fresh" card without any checked items.

**Comment by xet7** [comment]
Moved to #904
