### ISSUE TITLE
deactivating self-registration is not working

### ISSUE THREAD

**Issue by andreasernst** [wekan/wekan#1417]
## Issue
**Impacted version**: 0.63.0

**Server Setup Information**:

* Operating System: openSUSE 42.2
* Deployment Method: docker https frontend Apache httpd
* Node Version: 4.8.7
* MongoDB Version: 3.2.12
* ROOT_URL environment variable (Is there a subfolder?): no subfolder

**Problem description**:
Under Administration deactivating self-registration checked, but still shown on the login/front page

**Comment by biji** [comment]
Similiar to https://github.com/wekan/wekan/issues/1749 ?

**Comment by xet7** [comment]
This is already fixed.
