### ISSUE TITLE
Comment only Permission Can move checklist item

### ISSUE THREAD

**Issue by qicz** [wekan/wekan#1418]
## Issue
**Impacted version**: 0.63

**Server Setup Information**:

* Operating System: CentOS Linux release 7.0.1406 
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): tar+nginx
* Node Version: v6.11.4
* MongoDB Version: 3.0.5

**Problem description**:
- Comment only Permission Can move checklist item

**Comment by xet7** [comment]
Moved to #3022
