### ISSUE TITLE
External modification of MongoDB data / MongoDB data models changes

### ISSUE THREAD

**Issue by CodeBrauer** [wekan/wekan#1423]
## Question
**Impacted version**: 0.62

**Server Setup Information**:

* Operating System: Ubuntu 14.04
* Deployment Method: Docker
* Node Version: 4.8.6
* MongoDB Version: 3.2.18

**Problem description**:
So because wekan is built with meteor all MongoDB changes are pretty fast shown on the UI. We have installed restheart in first case to export all data with more structure and easier to handle for other apps. Now I thought: Is it possible to "manipulate" data (without breaking wekans structure)?

So what major changes can we expect in the MongoDB data models with upcoming releases?
  
 To be clear: I just want to modify data (updating) / not change the structure in any way

**Comment by xet7** [comment]
@CodeBrauer 

Yes, Meteor listens MongoDB changes and shows them near realtime.

Wekan plans for 2018:
https://blog.wekan.team/2017/12/2-years-of-wekan-what-we-archieved/index.html
- these do change and add to schema.

I recommend you use Wekan REST API for direct changes to Wekan:
https://github.com/wekan/wekan/wiki/REST-API
- if something in REST API does not work yet, check if there is issues for it, or add new issue

This is used in Gogs integration:
https://github.com/wekan/wekan-gogs

For having Wekan data mirrored to read-only PostgreSQL, there is also:
https://github.com/wekan/wekan-postgresql

Does this answer your question? What kind of manipulation to Wekan you mean?

**Comment by CodeBrauer** [comment]
So I need this for my webhook application... The webhook doesn't provide all data (which is good, so the data is relatively small)

```json
{
  "text": "Gabriel Wanzek hat \"Task Foo\" von \"Todo\" nach \"Doing\" verschoben\nhttp://example.org/b/2WFyTMewBj6BReRPH/demo-board/38nLaYTB57ixxqTsy",
  "cardId": "38nLaYTB57ixxqTsy",
  "listId": "eNo6uZcDB8GHzE3TY",
  "oldListId": "jTgKMkjBEge4tYRJe",
  "boardId": "2WFyTMewBj6BReRPH",
  "user": "Gabriel Wanzek",
  "card": "Task Foo",
  "description": "act-moveCard"
}
```

So basically my API calls are (to get all data I need from this webhook):

- get single board (to get name, labels, createdAt by boardID)
- get single card information (e.g. their labels, createdAt)
- get lists (title by listID / oldListID)
- get user by full username

My only update is setting `spentTime` of a single card.

**Comment by xet7** [comment]
@CodeBrauer 

Does changing 'spentTime' with Wekan REST API work for you currently? Or is there feature missing?

**Comment by CodeBrauer** [comment]
@xet7 

According to the [wiki](https://github.com/wekan/wekan/wiki/REST-API) all API calls I do are currently not available with Wekan REST API. My current approach is just using restheart.
