### ISSUE TITLE
Bug on uploading a file which name has prefix "#" such as "#A Great Pic"

### ISSUE THREAD

**Issue by thuanpq** [wekan/wekan#1425]
Bug on uploading a file which name has prefix "#" such as "#A Great Pic"

**Comment by xet7** [comment]
If file has "#" in it, I think it should be removed from filename, because otherwise webbrowsers think it's and anchor link to elsewhere in the webpage, so that's why it does not work.

@thuanpq 

Can you provide a pull request?

**Comment by xet7** [comment]
Actually "#" should be replaced with "_" because if somebody submits image "#.png" then it would not work properly when just removing "#".

**Comment by xet7** [comment]
Moved to #2759
