### ISSUE TITLE
this.userId is required when copying boards from an Rest-API call

### ISSUE THREAD

**Issue by Gobliins** [wekan/wekan#1427]
I have expanded the API to copy boards.
For copying i use your code:

`const sourceBoard = Boards.findOne(boardId);`
`  let clonedBoardId=null;`
`  if (sourceBoard) {`
`    clonedBoardId = Boards.insert({`
`      title: clonedBoardTitle,`
`      slug: sourceBoard.slug,`
`      archived: sourceBoard.archived,`
`      labels: sourceBoard.labels,`
`      permission: sourceBoard.permission,`
`      color: sourceBoard.color,`
`      description: sourceBoard.description,`
`    });`

In the `'copy.boards'` method you do a user check:
`if (!this.userId) {`
`        throw new Meteor.Error('logged-out');`
`      }`

i did not include this check. But still i get an error:
`User id is required`

I login to the API to get a token and pass the token to each API call (as you described in the API docs)
Is there a way to bypass the required `this.userId` or to set it from an API call?

I already tried `this.userId = req.userId`but it didn't work.

**Comment by xet7** [comment]
@Gobliins 

Does some of these help? https://github.com/wekan/wekan/pull/1296 https://github.com/wekan/wekan/pull/1241

**Comment by xet7** [comment]
Or this https://github.com/wekan/wekan/issues/797

**Comment by xet7** [comment]
Or this https://github.com/wekan/wekan/commit/06afa1ae35cc00efbe517b30b27c06a18910dffc

**Comment by Gobliins** [comment]
It seems like the board itself needs a member (owner). I have added it and bypassed the check when doing an API call. I will check on this issue again in some days, since i currently working on other issues.

**Comment by Gobliins** [comment]
Also the lack of this.userId seems not only to be aproblem of the boards API, it is a general problem when doing API calls.
So each time in a before/after (insert, update, remove) hook a userId is required it is sent as undefined.

**Comment by xet7** [comment]
@Gobliins 

Did you login to API before using it ?

**Comment by Gobliins** [comment]
Sure

**Comment by Gobliins** [comment]
From https://github.com/matb33/meteor-collection-hooks

You can define a defaultUserId in case you want to pass an userId to the hooks but there is no context. For instance if you are executing and API endpoint where the userId is derived from a token. Just assign the userId to CollectionHooks.defaultUserId. It will be overriden by the userId of the context if it exists.

and https://github.com/stubailo/meteor-rest/pull/118 seems to be the same problem.

Have you done anything like this? To make the API work flawless?

**Comment by xet7** [comment]
@huneau @mayjs

You did add REST API at #1037 , is there a bug ?

**Comment by mayjs** [comment]
There was an issue caused by hooks not getting the correct userId at some point. The first time we noticed it while working on the API was at #1045, which was worked around by @zarnifoulette in #1116.

His workaround was to use direct insertion into the collection, so that the hooks would not be called. The hook actions are then executed manually.
If we created functions for all hooks, we could just use these functions from the REST-endpoints without having them run the hooks.

This solution is not very elegant, but if it is implemented carefully would solve this issue. I think the defaultUserId option might cause race conditions or similar issues, if for example two REST-API calls arrive and the hooks for the first call are executed after the second call was processed.

**Comment by Gobliins** [comment]
> I think the defaultUserId option might cause race conditions or similar issues, if for example two REST-API calls arrive and the hooks for the first call are executed after the second call was processed.

Good hint

And yes the workaround is to avoid the hooks with direct.insert and call the code from the hooks in seperate functions with the userId as param from the request.

**Comment by Gobliins** [comment]
So i guess we take the workaround by calling `direct.insert` as a temporary solution and close this issue?

**Comment by mayjs** [comment]
Yes, I think this is currently the only really working solution.
