### ISSUE TITLE
Trello Import // Board not Found

### ISSUE THREAD

**Issue by generic-user-name** [wekan/wekan#1430]
## Exporting Data from grain that has Board not Found

https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

## Issue
**Impacted version**: 0.63.0

**Server Setup Information**:

* Operating System:  Ubuntu 14.04.5 LTS
* Node Version: v4.8.4
* MongoDB Version:2.6.7

**Problem description**:
- Encounterd a problem with the Import of a board from Trello
- At first it looks like its working, and everything gets imported as expected
- after I close the board and try to reopen it again I get the Message "Board not Found"

**Comment by xet7** [comment]
@generic-user-name 

How did you install Wekan? I have not seen this error before.

**Comment by generic-user-name** [comment]
Hi,

thanks for the quick reply,

WeKan is currently running under sandstorm.io

**Comment by xet7** [comment]
@generic-user-name 

Please add Wekan grain debug log, that you see with terminal/display looking button.

**Comment by generic-user-name** [comment]
...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-01-15T16:38:53.365+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
> Starting board-background-color migration.
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
> Starting use-css-class-for-boards-colors migration.
> Finishing use-css-class-for-boards-colors migration.
> Starting denormalize-star-number-per-board migration.
> Finishing denormalize-star-number-per-board migration.
> Starting add-member-isactive-field migration.
> Finishing add-member-isactive-field migration.
> Starting add-sort-checklists migration.
> Finishing add-sort-checklists migration.
> Starting enforce-public-visibility-for-sandstorm migration.
> Finishing enforce-public-visibility-for-sandstorm migration.
** SANDSTORM SUPERVISOR: Grain shutdown requested.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-01-15T16:39:53.913+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-01-15T18:05:56.122+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...

**Comment by xet7** [comment]
@generic-user-name  

Sorry, you can not import attachments directly from Trello when using Sandstorm version of Wekan. This is because Wekan is in secure sandbox at Sandstorm, and does not yet have Sandstorm-compatible way to import attachments from outside of Sandstorm.

You need to:
1) Install Standalone version of Wekan, for example Docker/Snap/VirtualBox, for example to your own computer
2) Import board from Trello
3) Export board as Wekan board. Exported JSON file includes attachments as base64 encoded files.
4) Import board as Wekan board to Sandstorm.

**Comment by lramage94** [comment]
@xet7 What happens to the imported boards?

I am new to sandstorm/wekan and I imported a couple of boards today ( and deleted the originals from Trello ). How/Can I get these back?

**Comment by xet7** [comment]
@lramage94 

In Sandstorm, you can click Wekan grain, and although it does not load, you can download it with arrow down download grain button as .zip file. When that .zip file is extracted, data is inside in MongoDB format. You could look those files what strings they have with linux command "strings filename" or with hex editor "sudo apt install hexedit", or search with google how to restore data from raw MongoDB database files. I have not tried it yet.

**Comment by gergamel** [comment]
I think I am seeing this exact issue trying to import from an older Wekan server into a wekan grain running on Sandstorm.

I have attachedThe exact steps I followed are:
- Export JSON from old wekan
- Create new board
- Add all the users that were on the old Wekan board to the new board
- Select "Import Board"->"From Wekan"
- Paste in JSON
- Map all members from the old board to their matching entry in the new board
- Click Done

At this point, it LOOKS like everything has worked. I see all the boards and cards and it all looks great. However, if I close the grain and reopen it, I get "Board not found".

I have created a simple board which recreates the issue for me. The JSON data I am importing is [here](https://pastebin.com/Rtq4vrJw). This has been parsed through a script to sanitize it because our old version of wekan is VERY old and the new version didn't like the data. I don't think there are any issues here because, as I said, everything seems to work great until you close the grain.

**Comment by xet7** [comment]
@gergamel  

Thanks for that JSON ! I'll check it.

**Comment by xet7** [comment]
@gergamel 

It seems that import on Sandstorm is broken.

I created new board in Sandstorm => Export to Wekan JSON => Import Wekan JSON => Board not found.

I created new board in Standalone Wekan => Export to Wekan JSON => Import Wekan JSON to Sandstorm => Board not found.

Your old Wekan JSON => Import to newest Standalone Wekan => invalid JSON format

Create new board in Standalone Wekan => Export to Wekan JSON => Import to Standalone Wekan => Works.

Problem is that newest Standalone Wekan has swimlanes etc features, so Wekan Export JSON format is different. I have been trying to make Sandstorm version of newest Wekan, but still have problems with even [compiling Sandstorm](https://github.com/sandstorm-io/sandstorm/issues/3036) and newest [Wekan for Sandstorm gives some C++ errors](https://github.com/wekan/wekan/issues/1333#issuecomment-359437724) after all the Meteor 1.6.0.1 upgrades, it does not start correctly.

For just using Standalone Wekan with Docker or Snap, you can upgrade to newest Standalone Wekan, and MongoDB export/import to newest Standalone Wekan should work OK. That way you could get newest Export JSON format. But I still need to get newest Wekan somehow working on Sandstorm.

**Comment by gergamel** [comment]
@xet7 

Thanks for taking a look. I'd offer to try and help, but I basically nothing about how Sandstorm works. Our sysadmin is trying it out because it looked like it would minimise his on-premise tool management workload. It remains to be seen if this is, in fact, the case :)

I've just started working with Docker for internal tools, so I'll have a crack at spinning up a Wekan image and try your suggestion. Quick google suggests I use the Docker Official [wekanteam](https://hub.docker.com/r/wekanteam/wekan/builds/) repo?

**Comment by xet7** [comment]
@gergamel 

I will fix Wekan at Sandstorm with Sandstorm developers anyway.

Docker Hub is usually broken, I use Quay more.

Use Docker or Snap, see:
https://github.com/wekan/wekan/releases

Snap has benefit that it's very easy to install to Ubuntu, and updates automatically.
But snap loses settings when new update comes, I'm waiting for fix:
https://github.com/wekan/wekan-snap/issues/29
Workaround is to have some cron script check has the version changed or does the website work, and add those settings back.

**Comment by gergamel** [comment]
@xet7 thanks for the thought.

I tried a couple, but couldn't remember what state I left my JSON cleaner script in, so I actually ended up making a new board in Sandstorm Wekan, exporting it from there and then just trying to import it straight back in. The JSON I used is here: [https://pastebin.com/ZksS4JeV](https://pastebin.com/ZksS4JeV). I confirmed it has "_id": "sandstorm" at the board level.

Again, it looks like it has worked, but after you close the grain and reopen it, you get "Board not found".

**Comment by xet7** [comment]
Ok, probably something has changed in source code so it does not work anymore, I'll check.

**Comment by DrGraypFroot** [comment]
Hey there

Don't know if this is still up-to-date, but I'm experiencing the same issue.

Also tried Wekan 1.02, same result.

Funnily enough, even exporting a board from Sandstorm Wekan and then importing it again also causes the same issue: "Board not found"

The only way is to backup a board and then restore and rename it. That works like a charm.

No way to import a Standalone-Wekan Board into Sandstorm-Wekan. 

It's no deal breaker for us, just thought I mentioned it in case someone has found a solution.

Cheers

**Comment by xet7** [comment]
@DrGraypFroot 

This is not fixed yet, that's why this issue is still open.

**Comment by dzampino** [comment]
@DrGraypFroot Backing up the board and restoring and renaming it did not work for me.

**Comment by xet7** [comment]
Help in fixing this would be very welcome. It only requires reading code and figuring it out. Wekan code is very readable.

**Comment by xet7** [comment]
[Here is related story](https://blog.wekan.team/2018/05/wekan-v1-00-released/index.html).

My own problem is my limited time.

**Comment by dzampino** [comment]
@DrGraypFroot the error showed up while restoring and remains after refreshing. Tried it a different couple of ways.

**Comment by xet7** [comment]
This Checklist data lost issue is separate from this Board not Found issue, but I'm posting it here, because I did also looking at this Board not Found issue.

## Checklist data lost when upgrading Wekan

When one user of Sandstorm Wekan upgraded to newest Wekan v1.03 or v1.02, on all Wekan grains checklists changed to be like this. Checklist content disappeared, and checklist title was duplicated to checklist items like this:

![2018-06-09_checklist_bug](https://user-images.githubusercontent.com/15545/41193883-95a55454-6c1b-11e8-8f64-30471dd2f198.png)

The problem is, that I can't duplicate this in any way.

To my knowledge, all grains in Sandstorm are separate from each other, and have separate MongoDB databases. I don't know how it's possible that checklists get messed up on all Wekan grains in Sandstorm installed to sandcats.io domain server.

I have tested on local Sandstorm install these Wekan versions. I create checklist, and upgrade to v1.03, upgrading works fine.
- 1.00
- 0.63
- 0.50
- 0.41

It's different from versions below that.
- v0.40 has login bug: it opens "Board not found" page when loading, same like in Sandstorm Wekan Import Board bug #1430, and has link to sign-in page like standalone Wekan. When I click it, and click Register, it does not allow creating password auth login, because it's currently at Sandstorm.
- v0.39: Can not connect to Wekan grain network error, log below.
- v0.34: Can not connect to Wekan grain network error, log below.

## About Board not found error

On all tested Sandstorm Wekan versions back to Sandstorm Wekan v0.34, I get "Board not found" error. This makes me think, that in what version of Wekan has Import Board worked at all? Because I remember being able to import board to Wekan.

## Sandstorm Wekan v0.39 error

```
...grations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:13:20.503+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=MCr4p4YcuAJfaMvz6
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:13:23.666+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=vPxw5dFTcBp4oe3rt
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:13:26.754+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=CjsaixDgwE2SLQ7Yn
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:13:29.968+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=zCyfDcfm9DfruFHAM
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:13:33.154+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=BzHfFA5HYXttSRd8D
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
```
## Sandstorm Wekan v0.34 error

```
...ofile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:38:27.188+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=cTtbD5hGRc5LhhKkx
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:38:30.286+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=Yb2dDjMkE74c82ZSH
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:38:33.334+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=S4Hcmett4Xn2ums6n
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:38:36.350+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=9StZWiiktZqzyQLwa
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:38:39.386+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=Qpw3KyozbjcggyzvD
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2018-06-09T15:38:43.533+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=hiLhWCWfnqJMZdSsy
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
> Starting add-sort-checklists migration.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: undefined is not a function
    at Array.find (native)
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:423:13
    at /programs/server/boot.js:464:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:462:11
** HTTP-BRIDGE: App server exited with status code: 1
*** lost connection to grain (probably because it shut down) ***
```

**Comment by xet7** [comment]
## Exporting Data from grain that has Board not Found

https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by kentonv** [comment]
@xet7 asked me to comment.

Sorry, I don't have any ideas. This seems to me like it must be some sort of migration bug in Wekan. I can't imagine how Sandstorm could have caused it.

**Comment by ocdtrekkie** [comment]
I definitely remember it working, but schema changes effectively break it every time Wekan adds a new feature.

**Comment by xet7** [comment]
I did create card with checklists, tried migrating from many versions of Wekan to newest version, and I did not have any issues. It could be some migration code bug or MongoDB bug. It seems strange, because only one migration is running at a time, I would presume, as I have seen on console.

**Comment by ocdtrekkie** [comment]
@xet7 When you are testing with older versions of the Sandstorm package, are you also testing with importing/exporting from similarly old Wekan versions?

**Comment by xet7** [comment]
@ocdtrekkie 

1) I have newest Sandstorm locally in my laptop.

2) I install Wekan old version .spk to Sandstorm.

3) I create grain and board with checklists, export it.

4) I create new grain, import previously exported (step 3) JSON file, there is board not found error.

5) I upload newest Wekan v1.03 spk and upgrade both grains.

6) Checklists still look the same, I did not get any errors, and was unable to duplicate this upgrade bug.

**Comment by xet7** [comment]
In step 6
- 1st grain where I created checklists, still has same checklists, no errors
- 2st grain, that has board not found error, still has board not found error
