### ISSUE TITLE
Add proxy auth

### ISSUE THREAD

**Issue by bputt** [wekan/wekan#1431]
Is it possible to add a proxy auth method for logging users in?

For example, nginx could proxy_pass X-AUTH-USER and wekan could use that to identify who the user is. This would essentially remove the need for people to login and no longer would have to use passwords.

Ideally, this would work similarly to Grafana's auth proxy: http://docs.grafana.org/tutorials/authproxy/

**Comment by xet7** [comment]
@bputt 

There is proxybourcer to have Google auth in front of Wekan password login, but that is still kind of 2 logins still, it's not integrated.
https://github.com/wekan/wekan/wiki/Let's-Encrypt-and-Google-Auth
