### ISSUE TITLE
When i run meteor command it stucks in Building for web.browser

### ISSUE THREAD

**Issue by fcohernandez** [wekan/wekan#1433]
## Issue

**Server Setup Information**: ubuntu server

* Operating System: Ubuntu 16.04
I am installing Wekan from source in a server, i followed all the steps but still stuck in building for web.browser
* Node Version: 4.8.6
* MongoDB Version: 3.2.18

**Problem description**:
I am installing Wekan from source in a server, i followed all the steps but still stuck in building for web.browser

When i am do the npm install step it show me this

![5](https://user-images.githubusercontent.com/32824813/35158174-0fc4373a-fd15-11e7-946e-110fb947dc1a.png)
Then i run the command with sudo but dont show me anything, so i continue with the installation y stuck in here 

![6](https://user-images.githubusercontent.com/32824813/35158264-57bc2566-fd15-11e7-8ce2-7cfb85325d62.png)

**Comment by xet7** [comment]
@fcohernandez 

Use Ubuntu snap on Ubuntu 16.04 server, it is much easier:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
@fcohernandez 

Configuring Nginx for Ubuntu snap:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by xet7** [comment]
I think it is not useful to compile Wekan on production Ubuntu servers, as node/meteor etc versions change frequently. It just takes too much time. I recommend Docker and Snap for production use.
