### ISSUE TITLE
Typo in Nginx config

### ISSUE THREAD

**Issue by danger89** [wekan/wekan#1434]
Typo in doc:
`proxy_set_header Connection $connection_upgrade;;`. 

Here located:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

Should be:

`proxy_set_header Connection $connection_upgrade;` (note the double ';'-sign at end of line)

**Comment by xet7** [comment]
@danger89 

Thanks! Fixed.

**Comment by danger89** [comment]
Np
