### ISSUE TITLE
Unable to remove Labels

### ISSUE THREAD

**Issue by nurmd** [wekan/wekan#1435]
## Cannot remove Labels from asigned card.

There is no remove button on labels. Thus we cannot remove them once we pick a label.
![screenshot_20180124_173821](https://user-images.githubusercontent.com/2098574/35331467-7e8732aa-012d-11e8-98ed-bf5dfe93cc14.png)

**Comment by xet7** [comment]
@nurmd 

Click label, and on dropdown menu click same label again to remove it. You can also rename labels, change color, etc edit label in that popup with pen icon.

![label-remove](https://user-images.githubusercontent.com/15545/35333406-4ee87a10-0117-11e8-88b7-068e70be07fa.png)
