### ISSUE TITLE
Is POST  api cards working?

### ISSUE THREAD

**Issue by fcohernandez** [wekan/wekan#1436]
When i try to insert this 

`{
 "title": "test",
 "description": "hello world",
 "authorId": "yyJWGn2FZ2AwzHsxT",
}

Using this URL http://localhost:3000/api/boards/fnnkpFjRPhdzMFkrJ/lists/ZSHvg4gEcKr7y424A/cards

boardId, listId and authorId are in the database, I check it

Throws this error 
`W20180124-17:14:18.560(-3)? (STDERR) SyntaxError: Unexpected token }
W20180124-17:14:18.560(-3)? (STDERR)     at Object.parse (native)
W20180124-17:14:18.560(-3)? (STDERR)     at parse (/home/abstrahere/.meteor/packages/simple_json-routes/.2.1.0.udtyeh++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/lib/types/json.js:88:17)
W20180124-17:14:18.561(-3)? (STDERR)     at /home/abstrahere/.meteor/packages/simple_json-routes/.2.1.0.udtyeh++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/lib/read.js:108:18
W20180124-17:14:18.561(-3)? (STDERR)     at invokeCallback (/home/abstrahere/.meteor/packages/simple_json-routes/.2.1.0.udtyeh++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
W20180124-17:14:18.562(-3)? (STDERR)     at done (/home/abstrahere/.meteor/packages/simple_json-routes/.2.1.0.udtyeh++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
W20180124-17:14:18.562(-3)? (STDERR)     at IncomingMessage.onEnd (/home/abstrahere/.meteor/packages/simple_json-routes/.2.1.0.udtyeh++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
W20180124-17:14:18.562(-3)? (STDERR)     at emitNone (events.js:67:13)
W20180124-17:14:18.563(-3)? (STDERR)     at IncomingMessage.emit (events.js:166:7)
W20180124-17:14:18.563(-3)? (STDERR)     at endReadableNT (_stream_readable.js:923:12)
W20180124-17:14:18.565(-3)? (STDERR)     at nextTickCallbackWith2Args (node.js:511:9)
W20180124-17:14:18.565(-3)? (STDERR)     at process._tickCallback (node.js:425:17)`
`
I have been trying doing the code myself but I can't yet, I'm started recently using meteor.
If someone can help me I would appreciate it.

PS: Is there some page where i can found information about JsonRouter? I look for myself but there is not too much documentation apparently. Thank you

**Comment by xet7** [comment]
@fcohernandez

You need to login at API as admin first. https://github.com/wekan/wekan/wiki/REST-API

You can also look at Gogs integration how to use API:
https://github.com/wekan/wekan-gogs

Tell me does these work. If not, I need to check it.

**Comment by fcohernandez** [comment]
@xet7 

When I use this command, (I don't know if is right)

`curl -H "Authorization: Bearer 9u8wbopNDZJJaLqNPflPmzi7fBizPOYTJ1iwxkMg7xy" \ 
-H "Content-type:application/json" \ http://localhost:3000/api/boards/fnnkpFjRPhdzMFkrJ/lists/ZSHvg4gEcKr7y424A/cards  \ 
-d '{"title": "test", "description": "hello world", "authorId": "yyJWGn2FZ2AwzHsxT"}'`

It shows me this 

`curl: (6) Could not resolve host:  -H
curl: (6) Could not resolve host: Content-type
curl: (1) Protocol " http" not supported or disabled in libcurl
curl: (6) Could not resolve host:  -d

[1/3]: "title": "test" --> <stdout>
--_curl_--"title": "test"
curl: (6) Could not resolve host: "title"

[2/3]:  "description": "hello world" --> <stdout>
--_curl_-- "description": "hello world"
curl: (6) Could not resolve host:  "description"

[3/3]:  "authorId": "yyJWGn2FZ2AwzHsxT" --> <stdout>
--_curl_-- "authorId": "yyJWGn2FZ2AwzHsxT"
curl: (6) Could not resolve host:  "authorId"`

I checked with curl --version and show me this

`curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
`

**Comment by andresmanelli** [comment]
I tried your command without the backslash, say:

```
curl -H "Authorization: Bearer 9u8wbopNDZJJaLqNPflPmzi7fBizPOYTJ1iwxkMg7xy" -H "Content-type:application/json" -X POST http://localhost:3000/api/boards/fnnkpFjRPhdzMFkrJ/lists/ZSHvg4gEcKr7y424A/cards -d '{"title": "test", "description": "hello world", "authorId": "yyJWGn2FZ2AwzHsxT"}
```

And I got:

`Error: Unauthorized [...]`

So I think it's a syntax problem. Maybe this helps.

**Comment by fcohernandez** [comment]
@andresmanelli 

Thank you so much, it worked!
