### ISSUE TITLE
Can't open card after installation

### ISSUE THREAD

**Issue by Weiping1992** [wekan/wekan#1438]
## Issue
**Impacted version**:0.63

* Operating System:Ubuntu 16.04
* Deployment Method:tar
* Node Version:4.8.6
* MongoDB Version:3.6.0
* ROOT_URL environment variable (Is there a subfolder?): testenvironment: http://192.168.199.231/

**Problem description**:
I tried install with docker and manually install. But the result is same:  can't open the card 
after creating it. 

logs below:
weiping@ubuntu:~/wekan-0.63/bundle$ node main.js 
> Starting board-background-color migration.
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
> Starting use-css-class-for-boards-colors migration.
> Finishing use-css-class-for-boards-colors migration.
> Starting denormalize-star-number-per-board migration.
> Finishing denormalize-star-number-per-board migration.
> Starting add-member-isactive-field migration.
> Finishing add-member-isactive-field migration.
> Starting add-sort-checklists migration.
> Finishing add-sort-checklists migration.
====== BEGIN MAIL #0 ======
(Mail not sent; to enable sending, set the MAIL_URL environment variable.)
Content-Type: text/plain
From: Wekan <wekan@192.168.199.231>
To: weiping@example.com
Subject: Verify your email address on 192.168.199.231
Message-ID: <d45a8bbc-1379-d0f9-eaca-ee3a36b4504a@192.168.199.231>
Content-Transfer-Encoding: quoted-printable
Date: Sun, 28 Jan 2018 05:01:58 +0000
MIME-Version: 1.0

Hello weiping,

To verify your account email, simply click the link below.

https://192.168.199.231/#/verify-email/zTyA5Sey4807CHzSxHkApEa1kSc4zkRuTYCE=
yobVH0J

Thanks.
====== END MAIL #0 ======

I don't know how to fix it. Thank you!

**Comment by xet7** [comment]
Use Wekan v0.65 and Docker Compose script, setup ROOT_URL=http://your-server-ip etc correctly. Reading all on docker-compose script is required.
https://github.com/wekan/wekan/releases

Wekan only supports MongoDB 3.2.x, not 3.6.x.

**Comment by Weiping1992** [comment]
Sorry, I have tried install with docker. 
My docker-compose.yml is below:
`version: '2'

services:
  wekandb:
    image: mongo:3.2.18
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 7780:80
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://192.168.199.231
    depends_on:
      - wekandb
volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge`

I created a board and a card both called 'test'. 
When I click the card, it tells:
This site can’t be reached
192.168.199.231 refused to connect.
But i am sure, the IP is right. and port 7780 is listening. 

weiping@ubuntu:~/wekan-mongodb$ netstat -anp|grep 7780
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::7780                :::*                    LISTEN      -

**Comment by xet7** [comment]
ROOT_URL=http://192.168.199.231:7780

And use wekan at webbrowser http://192.168.199.231:7780

**Comment by xet7** [comment]
Does it work now ?

**Comment by Weiping1992** [comment]
Still didn't work.
But connection is established.
root@ubuntu:~# netstat -anp|grep 7780
tcp        0      0 192.168.199.231:38650   192.168.199.231:7780    ESTABLISHED 2487/chromium-brows
tcp6       0      0 :::7780                 :::*                    LISTEN      81292/docker-proxy

screenshot is below:
![screenshot from 2018-01-28 21-25-37](https://user-images.githubusercontent.com/18508136/35482558-42348e4a-0472-11e8-8189-f40945c7a410.png)

**Comment by xet7** [comment]
@Weiping1992 

It's possible that this release v0.65 is broken, there are major changes.
If you have any important data in Wekan, backup MongoDB from inside of Docker:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

You can use release v0.63 while waiting for fixed version, change to docker-compose.yml file this:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml#L61

Change there:
```
image: quay.io/wekan/wekan
=>
image: wekanteam/wekan:v0.63
```

List of Docker Hub tags are at:
https://hub.docker.com/r/wekanteam/wekan/tags/

**Comment by xet7** [comment]
Actually, it seems that this was already fixed previously today in this image, so you need to add it to Dockerfile:
```
image: quay.io/wekan/wekan
```

To use it, you need to backup your data just in case (if you had any), and then do:
```
docker stop wekan-app
docker rm wekan-app
docker rmi quay.io/wekan/wekan:latest    (or wekanteam/wekan:v0.63)
docker-compose up -d
```

I will also do Wekan v0.66 release soon, in that case it will be this image:
```
image: quay.io/wekan/wekan:v0.66
```

**Comment by Weiping1992** [comment]
Thank you very much!

**Comment by xet7** [comment]
@Weiping1992 

Wekan works better in Firefox currently, see this Chrome bug:
https://github.com/wekan/wekan/issues/1404

Webbrowsers rapidly add and remove features, that causes some breakages so some fixes needs to be made sometime.
