### ISSUE TITLE
install steps is out of date on wekan wiki? how to install wekan?

### ISSUE THREAD

**Issue by evasnowind** [wekan/wekan#1440]
## Issue
wekan 0.65

* Operating System:ubuntu 16.4 LTS (virtual machine in virtualbox)
* Deployment Method :install manually

**Problem description**:
- it seems that install wiki is out of date? I was install wekan by the way described in https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps  ,however, in the latest version, 

> cd wekan-VERSION/bundle/programs/server && sudo npm install

where is wekan-VERSION/bundle/programs? I can see server directory under wekan-VERSION.
And, 

> node main.js

**I cannot find where is "main.js" in the release of wekan.**
so I cannot finish the install step. Is there anyone to tell me how to install ???

Besides, I have tried to install by ubuntu snap, howere, I encounted this error info 

>  **cannot find installed snap wekan at revision unset**

How can I install wekan :( 
thx.

**Comment by evasnowind** [comment]
when I use snap to install wekan, I also encounted snap install error like this:

> prayer@host:~$ sudo snap install wekan
[sudo] password for prayer: 
119.53 MB / 119.54 MB [====================================================================================================_] 100.00 % 356.93 KB/s 
error: cannot perform the following tasks:
- Make snap "ubuntu-core" available to the system (no state entry for key)
- Mount snap "wekan" (cannot find snap declaration for "wekan": assertion not found)

**Comment by xet7** [comment]
@evasnowind 

Newest Wekan has Docker version available:
https://github.com/wekan/wekan/issues/1438#issuecomment-361075193

Other versions are not ready yet, they will take some time.
