### ISSUE TITLE
Import Wekan Board with Swimlanes

### ISSUE THREAD

**Issue by amuesta** [wekan/wekan#1445]
## When importing an existing Board from Wekan to an other, no swimlanes will be showed
**Impacted version**: 0.67.0

**Server Setup Information**:

* Operating System: Linux
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker
* Node Version: 8.9.3
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
If export your board which has no Cards, just swimlanes and lists, you can't see something ig you use the swimlane view, just in list view you can see it.
[export.txt](https://github.com/wekan/wekan/files/1677415/export.txt)
![20170130_empty](https://user-images.githubusercontent.com/35958165/35563454-9d728cd4-05ae-11e8-8f65-71008eb2759c.JPG)
![20170130_list](https://user-images.githubusercontent.com/35958165/35563455-9d98810a-05ae-11e8-9a2e-ef7addc6c51f.JPG)

**Comment by xet7** [comment]
Yes, only part 1 of Swimlanes is in Wekan, import/export of Swimlanes is not implemented yet.

I think currently you need to add some cards in list view to see something in swimlane view.

**Comment by andresmanelli** [comment]
Hello, please see commit ec0a8449ba98aea708e484d386e5a209e2be8fff, I think this should be fixed.
