### ISSUE TITLE
Bugs after update on 0.67

### ISSUE THREAD

**Issue by podz49** [wekan/wekan#1446]
## Issue
**Impacted version**: 0.67

**Server Setup Information**:

* Operating System: Debian 8.10
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): docker
* Node Version: 6.12.3
* MongoDB Version: 3.2.14
* ROOT_URL environment variable (Is there a subfolder?):localhost:8081

**Problem description**:
Hi,
Since the last update of the docker image (from 0.66 to 0.67) all card's details in a table are inaccessibles. I can click on it but I can't modify or add a comment. 
See the screenshot below:

![image](https://user-images.githubusercontent.com/29449458/35567191-75f9f9e2-05c4-11e8-9e57-d991ba94b255.png)

And now the horizontal scrollbar is under the lowest card of the table, it's weird to navigate.
Here is a screenshot:

![image](https://user-images.githubusercontent.com/29449458/35567234-98b0e86a-05c4-11e8-9de9-9499c64f2929.png)

Thanks for your help

**Comment by xet7** [comment]
Please use quay Docker image that has Wekan v0.68 with `image: quay.io/wekan/wekan` , more details: #1444

After installing Wekan v0.68, do you still have problems?

**Comment by podz49** [comment]
I have updated to 0.68:
wahou, the swimlane view is totally WTF?! I don't understand what's happening when I drag and drop a card. See this screenshot:
![image](https://user-images.githubusercontent.com/29449458/35569722-2d85c4f8-05cd-11e8-8d0a-a0e07aa88c5a.png)
And the scroll bar is still under the lowest card...

**Comment by xet7** [comment]
Sorry, please use Docker tag `image: quay.io/wekan/wekan:v0.63` while we fix swimlanes, see #1444

Moved to #1444
