### ISSUE TITLE
Front-end broken on 0.68 (Docker)

### ISSUE THREAD

**Issue by spoonsauce** [wekan/wekan#1447]
## Issue
**Impacted version**: 0.68

**Server Setup Information**:

* Operating System: Debian 9
* Deployment Method: Docker (quay.io/wekan/wekan)
* Node Version: 8.9.3
* MongoDB Version: 3.2.18
* ROOT_URL environment variable (Is there a subfolder?): http://192.168.100.86/ (local VM)

**Problem description**:

I am experiencing some pretty severe front-end breakage on a brand new Docker deployment.

Account creation and board creation work fine, but when viewing / editing board contents:
* When opening up a board the JS console immediately shows `There is no route for the path: /b/xxxxxxxxxxxxxxxxxxx/myboard`.
* If I try to switch from list to swimlanes I get `update failed: Access denied`.  It fails and immediately changes back to list style.
* When I try to move a card, the drag-and-drop breaks and the console throws `TypeError: a is null`.
* If I switch to multi-selection, select one or more cards and try to move selection, the console throws `TypeError: Lists.findOne(...) is undefined`.

It's broken enough that I began to think it was my install, but I completely re-deployed Debian, installed Docker and tried again with the same results.

This behaviour is consistent across the latest versions of Firefox, Chrome, Safari and even Edge (!).  We tested on Fedora 27, OSX and Windows 10.

Thanks for the assistance.

**Comment by xet7** [comment]
Please use version v0.63 while we fix things, see #1444

Moved to #1444

**Comment by spoonsauce** [comment]
Understood. Thanks!
