### ISSUE TITLE
register user error

### ISSUE THREAD

**Issue by rickywu** [wekan/wekan#1448]
## Issue
**Impacted version**: xxxx
0.68.0
**Server Setup Information**:
deploy by wekan/wekan-mongodb
* Operating System: Linux
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:8.9.3
* MongoDB Version:3.2.18
* ROOT_URL environment variable (Is there a subfolder?):
http://localhost/wekan

**Problem description**:
register return internal server error but click again return user exists and console got errors:
There is no route for the path: /
f._notfoundRoute @ 1a8a5c7f9bf53daa246cebd6aa706dd6b8a0ec3d.js:247

![err](https://user-images.githubusercontent.com/442398/35627090-cf2beec6-06d2-11e8-98f3-d8e1a7449ab9.png)
![wekan](https://user-images.githubusercontent.com/442398/35627091-cf6a583c-06d2-11e8-93bc-792b870f47b6.png)

**Comment by xet7** [comment]
Intenal server error is, because email settings are not configured yet.
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Username already exists, because you already registered that user, and it's not possible to resend registration email yet, see https://github.com/wekan/wekan/issues/1320
