### ISSUE TITLE
Use absolute paths instead of full URLs on internal links

### ISSUE THREAD

**Issue by tobiasrenger-gh** [wekan/wekan#1449]
## Issue
**Impacted version**: 0.68

**Server Setup Information**:

* Operating System: Windows Server 2012 R2
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Source
* Node Version: 8.9.4
* ROOT_URL environment variable (Is there a subfolder?): http://localhost/wekan

**Problem description**:
I installed Wekan 0.68 on Windows Server 2012 R2 using the [Install Wekan from source on Windows](https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows) guide.

To integrate Wekan into an existing website the environment variables have been set to

ROOT_URL = http://localhost/wekan
PORT = 3000

and an IIS Server as reverse proxy redirects all requests from http://mydomain/wekan/?(.*) to  http://localhost:3000/wekan/{R:1}. This setup works most of the time (as long as all links in Wekan begin with /wekan) but breaks on links to cards in the swimlane/activities-sidebar that begin with http://localhost/wekan.

To run behind a reverse proxy Wekan should deliver all internal links as absolute paths (e.g. /wekan) instead of full URLs (like http://localhost/wekan).

Or did I misconfigure Wekan?

**Comment by xet7** [comment]
Wekan uses Node 8.9.3, NPM 5.1.1 and Meteor 1.6.0.1 because Meteor 1.6.1 is currently broken https://github.com/meteor/meteor/issues/9609

For config:
`ROOT_URL=http://server-ip-address:3000`

Wekan v0.68 is broken. Use previous version v0.63 or wait for new v0.69 to be released in near future, there is fixes for swimlanes.

**Comment by tobiasrenger-gh** [comment]
I now tested both new versions 0.69 and 0.71. The problem of the full URLs instead of absolute paths in links to cards in the swimlane/activities-sidebar still persists.

> For config:
> `ROOT_URL=http://server-ip-address:3000`

The change of the ROOT_URL config to http://server-ip-address:3000 will not solve this problem as Wekan must be accessible from two different domains. There is a non-secure domain for internal network access (e.g. http://intern.domain) and a secure domain for external network access (e.g. https://extern.domain). In both cases the links would still point to the wrong domain: http://server-ip-address:3000

**Comment by xet7** [comment]
@tobiasrenger-gh 

Use different wekan-app docker containers for different URLs, using same MongoDB docker container, as mentioned at docker-compose.yml:
https://github.com/wekan/wekan-mongodb

**Comment by tobiasrenger-gh** [comment]
I see that those full URLs are considered a feature, not a bug.

But I wonder what are the advantages of having full URLs instead of absolute paths. Especially as other links like the ones to the boards on the "My Boards" start page or the one to the "Export board" function in the board menu are absolute paths.

Why this mixture of link styles?

**Comment by xet7** [comment]
@tobiasrenger-gh 

Those full URLs are how Meteor js framework works. I did give you solution how to have many URLs to use same database. I don't know how to make it relative. Pull requests welcome.
