### ISSUE TITLE
Manual Installation Steps are not correct

### ISSUE THREAD

**Issue by benhartwich** [wekan/wekan#1450]
Hi,

I tried the manual installation from your wiki. When I download and extract the latest tar.gz archive from releases there is no folder /bundle/programs/server where I´ve to generate the npm depencies. Also no main.js file is present overall. 
Is the installation wiki outdated? Or am I too stupid to get what you mean?

Regards,

**Comment by xet7** [comment]
Yes wiki is outdated. If you have time, please fix wiki directly. There also other duplicated and not so well-organized pages.

Source build script rebuild-wekan-meteor-1.6.sh is here:
https://github.com/wekan/wekan-maintainer/tree/master/virtualbox

Docker version can be built from source with docker-compose.yml script at https://github.com/wekan/wekan-mongodb , setting ROOT_URL=http://your-ip:your-port and PORT=your-port , and starting building in wekan with `docker-compose up --build` in foreground mode to see debug output and stopping with Ctrl-c, or starting as service to background with `docker-compose up -d --build`

**Comment by benhartwich** [comment]
Thanks. I´ve set the following:
```
    ports:
      - 3000:80
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://127.0.0.1:3000
      - PORT=3000
      - MAIL_URL=smtp://xy:xy@mailxy:25/
      - MAIL_FROM='Orga <orga@xy>'
```
Wekan starts with 0.0.0.0:3000 and nginx cannot reach it (502 error). How can I debug wekan further or re-install / rebuild it? 
The docker log says nothing.

**Comment by xet7** [comment]
Set ROOT_URL to your https://example.com/wekan real address.

More info at docker-compose.yml file at https://github.com/wekan/wekan-mongodb
