### ISSUE TITLE
Maybe wekan should support drag a card to any position at a swimlane column

### ISSUE THREAD

**Issue by mayt2012** [wekan/wekan#1452]
Maybe wekan should support drag a card to any position at a swimlane column.  
It will be helpful for people who what show a new card at the top of a column.  
I found that these tow buttons were no effect when clicked.   

![2018-02-01_141255](https://user-images.githubusercontent.com/17042394/35663797-11ddd41e-075a-11e8-93d6-01936e19e91e.png)

**Comment by andresmanelli** [comment]
@xet7 @mayt2012 This should be fixed in v0.72
