### ISSUE TITLE
Does watching board's notifications only works by email?

### ISSUE THREAD

**Issue by AaronChoi** [wekan/wekan#1453]
Notifications on icon of chrome tab like trello is not supported yet?
Any notifications sign like red bell icon on the board card?
I set up with v0.63 wekan.tar on ubuntu 14.04 LTS, but notification is not coming up for any changes.

**Comment by anthonymasset** [comment]
I agree, I find Wekan should have html desktop notification or something else. Email notifications aren't sufficient.

**Comment by xet7** [comment]
Moved to #1256

**Comment by AaronChoi** [comment]
I just found same question as I asked. Sorry about duplication. Thanks!
