### ISSUE TITLE
attach null

### ISSUE THREAD

**Issue by gbarre** [wekan/wekan#1456]
## Issue
**Impacted version**: 0.63.0

**Server Setup Information**:

* Operating System: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-109-generic x86_64)
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): **snap**

**Problem description**:
Sometimes, on all cards of a board, we cannot attach any file. The message in activity is "_username_ attached null to _cardname_".
The very surprising thing is that it is not on all boards. It can happens on a new board or on a board in which we already hava attached files.

![capture d ecran 2018-02-01 a 15 02 05](https://user-images.githubusercontent.com/2445791/35682423-f53fd288-0760-11e8-9ee5-39332908fa8a.png)

**Comment by gbarre** [comment]
It seems this issue is due to webhook that doesn't work behind http proxy.

**Comment by xet7** [comment]
Using proxy:
https://github.com/wekan/wekan/issues/1480
