### ISSUE TITLE
Welcome board is not editable - possibly missing migration

### ISSUE THREAD

**Issue by gramakri** [wekan/wekan#1457]
## Issue
**Impacted version**: 0.69

**Server Setup Information**:
Cloudron

**Problem description**:
- It seems the welcome board is not editable (just guessing that this some migration issue with the recent swimlane changes). There is no mechanism to add cards. Note that new boards work fine. Just the pre-created welcome board has this issue.

This is the old one:
![welcome_board_old](https://user-images.githubusercontent.com/82041/35693471-29d23bb8-0733-11e8-88fd-41d4022e7092.png)

This is the new one:
![welcome_board_new](https://user-images.githubusercontent.com/82041/35693476-2f12113e-0733-11e8-93e8-942fb39e1d51.png)

You can use the [demo cloudron](https://my-demo.cloudron.me) (username and password is 'cloudron') to install wekan and test this yourself.

**Comment by andresmanelli** [comment]
Hello, commit 9df3e3d26bffb2268cdcc7fa768eda60e4f0975c fixes this I think!

**Comment by gramakri** [comment]
@andresmanelli @xet7 Thanks, I can confirm this issue is fixed.
