### ISSUE TITLE
Scrollbar appears in middle

### ISSUE THREAD

**Issue by gramakri** [wekan/wekan#1458]
## Issue
**Impacted version**: 0.69

**Server Setup Information**: Cloudron

**Problem description**:
- With the latest wekan, the horizontal scrollbar appears in the middle of the screen (instead of at the end like before).

![scrollbar](https://user-images.githubusercontent.com/82041/35693674-ba7169d2-0733-11e8-8e42-5210a431f139.png)

The scrollbar used to be all the way to the bottom before the swimlane changes.

**Comment by xet7** [comment]
@gramakri 

Yes, and when you add card, that horizontal scrollbar moves down. There is less movement needed from card to scrollbar. What is the problem or bug here? Wekan is going to have other new features too.

**Comment by gramakri** [comment]
@xet7 OK thanks, just wanted to check if the behaviour was intentional.

**Comment by X-dark** [comment]
@xet7 This behaviour is very inconvenient when you have a long list. Now the scrollbar is hidden and you need to scroll all the way down to make it appears.
Moreover you cannot drag cards between distant lists as autoscrolling when moving on the side does not work.
You cannot scroll using arrow keys either.

**Comment by xet7** [comment]
@andresmanelli 

Can you fix this?

**Comment by jkryanchou** [comment]
Yeah I found that issue too. It looks so awkward.

**Comment by sirup** [comment]
For me this is the same:
 - Scrollbar in the middle of the screen (if I use filter)
 - If I do not check a filter, there is NO HORIZONTAL SCROLLBAR at all. This is very exhausting, because I cannot move to the right or left of my lists. 

This seems like a bug to me.
