### ISSUE TITLE
Two empty columns in swimlane view

### ISSUE THREAD

**Issue by Chartman123** [wekan/wekan#1459]
## Issue
**Impacted version**: 0.65+

* Deployment Method: docker

**Problem description**:
Inside the board using the swimlane view there are two empty columns at the end. One for "Add List" and one for "Add List" and "Add Swimlane". The firtst one could be removed :)

**Comment by xet7** [comment]
@Chartman123  

What is "Impacted version 0.65+" ? Did you try 0.69 ? Wekan has changes in each release, they don't work the same.

**Comment by johnleeming** [comment]
I have this in 0.69:
![image](https://user-images.githubusercontent.com/13801070/35726045-62521684-07fb-11e8-8eaa-64ca276ac662.png)
when you first create a board it only has one empty column but then gains the extra one when you add lists

**Comment by xet7** [comment]
@andresmanelli 

Can you look at this? One empty column would be enough, I think.

**Comment by Chartman123** [comment]
@xet7 Yes it's still there in 0.69 :)

**Comment by andresmanelli** [comment]
Hello, this is already fixex at my devel branch !

**Comment by xet7** [comment]
Fix merged, will be included in next release.
