### ISSUE TITLE
Admin settings

### ISSUE THREAD

**Issue by superg2** [wekan/wekan#146]
Hi there

First : Congrats !! Your work is really impressive, I really appreciate such a work because it uses new 
technologies of the web !

I open this issue ticket because, after setup libreboard on my server, I'm really surprized there is no admin/admin account created by default. Is there a way to create such accounts who are allowed to control all boards ? (my setupe is intended to be used in a private area, but atm everybody is able to register and to create boards).

Thks a lot.
g2

**Comment by timo0** [comment]
+1

**Comment by natagoddanti** [comment]
:+1:

**Comment by anandubajith** [comment]
:+1:

**Comment by botweb** [comment]
+1

**Comment by rwatts3** [comment]
I am a Core developer with Orion , https://github.com/orionjs/orion . 
Orion is a CMS / Admin solution. I believe that an integration between the two platforms could give you exactly what you are asking for . 
@superg2

**Comment by davideuler** [comment]
+1

**Comment by Cquad** [comment]
+1

**Comment by PrestonL** [comment]
bump bump.  Would also be nice to close registration to the public for a private host.

**Comment by shtefcs** [comment]
+1

**Comment by PrestonL** [comment]
I've found that it's actually pretty easy to just sift through it with RoboMongo ( http://robomongo.org )

Can put together a basic how to if anyone thinks it would help.

As most of the site admins will be sysadmins, so maybe sifting through the database in a nice gui like that isn't a big deal?

I do like the idea of being able to restrict signups, and like the way gitlab does that by allowing you to restrict it to certain domains.

**Comment by anandubajith** [comment]
I now think that an admin interface is overkill. I could really live with an option which can prevent signups.

**Comment by mkorfmann** [comment]
Yes! Preventing sign ups would be my main feature request as well.

**Comment by nata-g** [comment]
I think we should not assume that the app would be used only by the sysadmins and in organizations. There are lot of use cases where wekan can be used for personal projects, game strategies or todo lists etc that do involve other people in some boards and in others they might not, so I think having basic admin interface with rules would be the better option to go...my 2 cents

**Comment by mkorfmann** [comment]
By preventing sign ups I mean: Invite only sign ups ;).

**Comment by leifsehn** [comment]
Admin feature would be nice and user board permissions.  +1

**Comment by storrgie** [comment]
+1

**Comment by cedvan** [comment]
:+1:

**Comment by akhockey21** [comment]
I was thinking of running a meteor admin panel on a seperate port such as https://github.com/gterrono/houston.

From my understanding you could start a new fresh meteor project in a separate directory, export the same Mongo DB settings as wekan uses. And that will give you a full administrative dashboard.

**Comment by cedvan** [comment]
why not install administration in same interface and same project ?

**Comment by adityai** [comment]
Minimum required feature: 
Admin account or an option to disable self registration.

**Comment by moutonnoireu** [comment]
:+1:

**Comment by ainouche** [comment]
+1

**Comment by Antarion** [comment]
Just installed Wekan in my organisation. No admin panel is kind of a bummer. 
I need to control acces and manage things. 
+1

**Comment by AlexanderS** [comment]
https://atmospherejs.com/sach/flow-db-admin seems like a possibility. In contrast to houston mentioned earlier it uses flow-router and does not conflict with wekan. I just tried it and it works (kind of) out of the box. But I is required to adjust the collection mappings to show some useful data.

**Comment by lifehome** [comment]
+1 for this.

**Comment by lifehome** [comment]
So it's a no for this? Or is there any kind of panel I can use for now?
It's really frustrating for us not having an admin panel for site configurations, etc.

**Comment by danger89** [comment]
Ow damn no admin user by default.. help!?

**Comment by AlexanderS** [comment]
@danger89 Currently there is no special admin user. **Internal server error** means maybe that your MAIL_URL does not work.

**Comment by danger89** [comment]
@AlexanderS you were right about the smtp settings.

**Comment by lkisme** [comment]
see PR #618

**Comment by xet7** [comment]
Moved to #790
