### ISSUE TITLE
Feature Request: Always visible editable markdown area at top bar for links to custom websites etc, only Admin can edit at Admin Panel

### ISSUE THREAD

**Issue by DejfCold** [wekan/wekan#1460]
Maybe Wekan could have a list of links managed by an admin. Links in a style of how to get fast to github/gitlab, server monitor, wiki, mail or whatever.
I'm thinking it could be right next to name/menu.
To save a bit of space on the bar, instead of text name for the link, admin could (optionally) assign an icon with tooltip or something.

**Comment by xet7** [comment]
@DejfCold 

You can already use markdown to add links to cards etc, like at https://wekan.github.io . Or do you mean something else?

**Comment by DejfCold** [comment]
I mean something else. I mean, this would be wekan wide, regardless if you are looking at board A or board B. Something that everyone would see and only admin (the one that can go to admin panel) could edit it. Can't think of a proper example for this, but this could be similar to GitHub's footer except it would be header, editable and instead of "Contact Github" there would be "GitLab", instead if "API" there would be "Protonmail", instead if "Training" there would be "Our webapp" etc . Simply put, there would be links to webapps, the team regularly use.
