### ISSUE TITLE
Unable to reorder cards

### ISSUE THREAD

**Issue by gramakri** [wekan/wekan#1461]
## Issue
**Impacted version**: 0.69

**Server Setup Information**: Cloudron

**Problem description**:
- Cards are not re-orderable anymore on the same list. Cards can be moved across lists but cannot be re-ordered on the same list.

**Comment by gramakri** [comment]
A workaround is to move the card to another list and then re-insert into the original in the desired location.

**Comment by andresmanelli** [comment]
Yes, I noticed, I'm working on this. Thanks!

**Comment by nebulade** [comment]
From what I can see in my local instance, the actual `sort` value in cards.js:move() after dropping a card, seems to be just fine, however the data model is never reflecting this and the values in the db are always -1 for me.

**Comment by ViViDboarder** [comment]
Is this issue not widespread? I feel like rearranging cards is a pretty core functionality.

I just verified this affects non-Cloudron deployments too by spinning up a fresh Docker instance.

**Comment by xet7** [comment]
@ViViDboarder 

Anyone that feels this is urgent, can send pull request to devel branch.

**Comment by ViViDboarder** [comment]
Forked and trying to follow along myself, but I've never used Meteor before...

I can see where the new index get calculated in the utils and where card.move happens. It looks like it gets calculated correctly, however I don't see where that gets posted to the server... I don't see any logs on the server for any kind of movement actions and my browser debug tools show no network changes. I'm thinking some framework is sending this through a websocket or something, but I'm not sure where else to start debugging.

**Comment by andresmanelli** [comment]
Hello, for what I can tell, after fixing some calls to `cards.move()`, the sort problem seems to be a Mongo/Meteor bug or something.

I tried fetching some docs but the sort isn't right. I think I'll try to cherry pick my swimlane commits from v0.63 or so.

**Comment by ViViDboarder** [comment]
Found issue with the move to top and move to bottom: https://github.com/wekan/wekan/blob/devel/client/components/cards/cardDetails.js#L176

Swimlane id is not passed in and it cannot find the list because it's using the sort parameter as list id.

Still debugging...

**Comment by ViViDboarder** [comment]
I think I may have found it...

It looks like the sorting of the cards is done here in [`lists.js`](https://github.com/wekan/wekan/blob/devel/models/lists.js#L85) through `Filter.mongoSelector()`. On that line it returns:

```
return Cards.find(Filter.mongoSelector(selector,
{ sort: ['sort'] }));
```

When I step in I can see that the selector function [only takes a single parameter](https://github.com/wekan/wekan/blob/devel/client/lib/filter.js#L131):

```
mongoSelector(additionalSelector) {
    const filterSelector = this._getMongoSelector();
    if (_.isUndefined(additionalSelector))
      return filterSelector;
    else
      return {$and: [filterSelector, additionalSelector]};
}
```

Doing a blame on both files shows the `mongoSelector` function hasn't changed in a few years. The list function does change with a swimlane commit here: https://github.com/wekan/wekan/commit/7b04f14e3c33db0b1c3ecff003262e7689383a15

It looks like a simple slipped paren!

I think it should be:

```
return Cards.find(Filter.mongoSelector(selector),
{ sort: ['sort'] });
```

Made the change locally and it seems fixed! I'll send a pr.

**Comment by ViViDboarder** [comment]
PR submitted.

@andresmanelli you mentioned working on the `card.move` issues. Does that include the move to top and bottom ones I flagged here? If so, then I'll leave those be so you don't have to deal with a merge conflict.

**Comment by gramakri** [comment]
@ViViDboarder I can confirm your patch fixes it for me locally as well! Wow, great debugging there.

I have tried figuring this out for 2-3 hours myself the other day and gave up on meteor :-)

**Comment by andresmanelli** [comment]
@ViViDboarder Great! I confirm #1465 fixes that problem. That also let my commit fcebb2a5373d6dea41b98b530c176cbee31bee4b fix move up/down.

@xet7 Could you add these two to wekan next dev release? Thank you!

**Comment by stahlstift** [comment]
@xet7 When you plan the next release? We need this fix.

**Comment by xet7** [comment]
@stahlstift 

Oh, I just noticed this. Ok, I'll release today.

**Comment by insertjokehere** [comment]
Just confirming that v0.72 fixes this for me. Thanks for the quick fix!

**Comment by stahlstift** [comment]
Big thx!
