### ISSUE TITLE
Error: Board id must be a string - swimlanes migration

### ISSUE THREAD

**Issue by shalev123d** [wekan/wekan#1462]
Hi Everyone,

I tried to upgrade Wekan from version 63 to 71 by following the guide of the docker compose version.
I didn't touch the Mongo container obviously because I wanted to keep my data.
When I tried to "docker-compose up", after downloading the image it threw this error and exited:

wekan-app  | > Starting add-swimlanes migration.
wekan-app  | /build/programs/server/node_modules/fibers/future.js:280
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^
wekan-app  |
wekan-app  | Error: Board id must be a string
wekan-app  |     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
wekan-app  |     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
wekan-app  |     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
wekan-app  |     at packages/matb33_collection-hooks.js:127:46
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
wekan-app  |     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
wekan-app  |     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
wekan-app  |     at Boards.find.forEach.board (server/migrations.js:162:37)
wekan-app  |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
wekan-app  |     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
wekan-app  |     at Object.Migrations.add [as migrationCallback] (server/migrations.js:156:17)
wekan-app  |     at packages/idmontie_migrations.js:238:17
wekan-app  |     at Function.time (/build/programs/server/profile.js:309:28)
wekan-app  |     at /build/programs/server/boot.js:423:13
wekan-app  |     at /build/programs/server/boot.js:464:5
wekan-app  |     at Function.run (/build/programs/server/profile.js:510:12)
wekan-app  | Presence started serverId=cBCkEZGJsffbinCXN
wekan-app  | > Starting add-swimlanes migration.
wekan-app  | /build/programs/server/node_modules/fibers/future.js:280
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^

Not sure how to proceed from here.. Any help would be greatly appreciated.
Thanks!

**Impacted version**: 0.71

**Server Setup Information**:

* Operating System: CentOS 7.3
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker compose

* Node Version: 6.12
* MongoDB Version: 3.2.18
* ROOT_URL environment variable (Is there a subfolder?): localhost

**Comment by xet7** [comment]
@shalev123d 

Did you add corrent ROOT_URL=http://your-ip-address:port to docker-compose.yml at https://github.com/wekan/wekan-mongodb ? It should not be localhost, I think. Can you post your docker-compose.yml file with changed passwords and domains like password=password and domain=example.com etc, so I can look are the settings correct?

Anyway, you could go back to Docker version 63 while we figure out what is causing the error.

Please keep frequent backups, and also before upgrades and downgrades, so you have backup outside of Docker:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

@andresmanelli 

Do you have idea why it gives error  `Error: Board id must be a string` ?

**Comment by shalev123d** [comment]
Thanks for replying!
It's not really localhost, its just the DNS name we gave the machine on our env, which worked on 63, so I believe the problem resides somewhere else. anyway, here is the file:
```

version: '2'

services:

  # 1) Create a dedicated user for Wekan, for example:
  #      sudo useradd -d /home/wekan -m -s /bin/bash wekan
  # 2) Add this user to the docker group, then logout+login or reboot:
  #      sudo usermod -aG docker wekan
  # 3) Then login as user wekan.
  # 4) Create this file /home/wekan/docker-compose.yml with your modifications.
  # 5a) Running Docker as service, on Systemd like Debian 9, Ubuntu 16.04, CentOS 7:
  #      sudo systemctl enable docker
  #      sudo systemctl start docker
  # 5b) Running Docker as service, on init.d like Debian 8, Ubuntu 14.04, CentOS 6:
  #      sudo update-rc.d docker defaults
  #      sudo service docker start
  # 6) For seeing does Wekan work, try this and check with your webbroser:
  #      docker-compose up
  # 7) Stop Wekan and start Wekan in background:
  #     docker-compose stop
  #     docker-compose up -d
  # 8) See running Docker containers:
  #     docker ps
  # 9) See stopped Docker containers:
  #     docker ps -a

  # Upgrading Wekan to new version:
  # 1) Stop Wekan:
  #      docker-compose stop
  # 2) Download new version:
  #      docker-compose pull wekan
  # 3) If you have more networks for VPN etc as described at bottom of
  #    this config, download for them too:
  #      docker-compose pull wekan2
  # 4) Start Wekan:
  #      docker-compose start

  wekandb:
    # All Wekan data is stored in MongoDB. For backup and restore, see:
    #   https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
    image: mongo:3.2.18
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    # Wekan container only has Node.js and related code,
    # there is no data stored here.
    #
    # Old Wekan that uses Node 4.8.6 and Meteor 1.4:
    image: wekanteam/wekan:latest
    # New Wekan that uses Node 6.12 and Meteor 1.6:
    # image: wekanteam/wekan:meteor-1.6
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    #---------------------------------------------------------------
    # For running Wekan in different port like 3000, use: 3000:80
    ports:
      - 80:80
    #---------------------------------------------------------------
    # Change ROOT_URL to your real Wekan URL, for example:
    #   http://example.com
    #   http://example.com/wekan
    #   http://192.168.1.100
    #---------------------------------------------------------------
    # Email settings are required in both MAIL_URL and Admin Panel,
    #   see https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
    #   For SSL in email, change smtp:// to smtps://
    #---------------------------------------------------------------
    # Not needed on Docker, but if you had installed from source,
    #   you could also have setup Wekan Node.js port at localhost
    #   with setting: PORT=3000
    #   and have Nginx proxy to port 3000, see Wekan wiki.
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://OUR_DNS_NAME_FOR_THIS_MACHINE
      - MAIL_URL=smtp://OUR_EXCHANGE_HUB_IP/
      - MAIL_FROM=Wekan <Wekan@mac.org.il>
    depends_on:
      - wekandb

#------------------------------------------------------------------
#  When using Wekan both at office LAN and remote VPN:
#    1) Have above Wekan docker container config with LAN IP address
#    2) Copy all of above Wekan config below, change name to different
#       like wekan2 or wekanvpn, and change ROOT_URL to server VPN IP
#       address.
#    3) This way both Wekan containers can use same MongoDB database
#       and see the same Wekan boards.
#    4) You could also add 3rd Wekan container for 3rd network etc.
#------------------------------------------------------------------
#  wekan2:
#    ....COPY CONFIG FROM ABOVE TO HERE...
#    environment:
#      - ROOT_URL='http://10.10.10.10'
#      ...COPY CONFIG FROM ABOVE TO HERE...

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge


```

**Comment by shalev123d** [comment]
Ok.. I think i've found the issue.
I exposed 27017 port from the container and managed to connect to the mongoDB via robomongo,
and found this board:
![image](https://user-images.githubusercontent.com/36129614/35798243-d63fc732-0a6a-11e8-82c2-4f5b041f907c.png)

don't know what is it exactly, but removing the document solved it. Thanks!

**Comment by xet7** [comment]
@shalev123d 

This Docker Hub image is broken:
```
image: wekanteam/wekan:latest
```

You should use this for latest version:
```
image: quay.io/wekan/wekan:v0.71
```

And when newer release is published, use newer release tag.
