### ISSUE TITLE
File preview from the system

### ISSUE THREAD

**Issue by davydov-vyacheslav** [wekan/wekan#1464]
## Issue
**Impacted version**: 0.61 (but I bet on latest as well)

**Server Setup Information**:

* Operating System:
* Deployment Method: docker
* MongoDB Version: 3.2

**Problem description**:
As end-user I'd like to preview files from system.

Ok, I have several kind of attachments. Everything works fine for images, but when I have attached pdf file to the list item, and click on it, preview screen is shown but no file content.

I did brief investigated the issue and found that when I click on the file, get request is sent and actual data (although, base64 encoded) is returned, but for image data the response contains actual image, not base64 encoded one. And there is one strange thing ... firefox shown that although type is octet-stream,  cause = js / img ... but the file is not image

![image](https://user-images.githubusercontent.com/9931946/35848251-1af0a6d8-0b26-11e8-8617-bd588244d418.png)

**Comment by xet7** [comment]
Moved to #1318
