### ISSUE TITLE
Feature Request: Viewing label titles on cards

### ISSUE THREAD

**Issue by Le1b1** [wekan/wekan#1466]
## Feature Request

**Feature description**:

Ability to view label titels on cards.
This is how its implemented in Trello:

![file-syrorkykvd](https://user-images.githubusercontent.com/1228025/35910703-ba39a5ba-0bf7-11e8-9778-2ed469547e31.gif) 

Most of my team members don't know the meaning of a label just by color, so this would be very helpful and increase usability.

**Comment by davydov-vyacheslav** [comment]
From my point of view, Wekan has different layout on card, that's why, IMHO, making full title for label is not a good idea because of possibility of broken layouts (especially if titles are long).
BTW, why don't you like just move mouse to the label and see what does it mean?

**Comment by xet7** [comment]
@naushil 

Info how how you can add bounty to this as Backer is at https://wekan.team/

**Comment by xet7** [comment]
@naushil

https://www.bountysource.com/issues/54741329-feature-request-viewing-label-titles-on-cards

**Comment by nickbe** [comment]
Why is it such a big deal to let us view the labels? 

For me right now, this is probably one of the biggest downsides when it comes to reviewing the board. It would be really helpful to see the labels at a glance and not only the colors. 

Also there's the question of how to adapt the label colors in the first place?

**Comment by xet7** [comment]
@nickbe 

Huh what? I already implemented viewing label titles on minicard as seen in above code https://github.com/wekan/wekan/commit/c48d5a73cab04db1a1e113e4367dc88573110438 , it's already available for Docker in docker-compose.yml at master branch of https://github.com/wekan/wekan

**Comment by nickbe** [comment]
Well I wasn't able to figure out how to display the titles. Currently I have installed wekan via snap and I have the latest 0.97 version installed.

**Comment by xet7** [comment]
Snap is not updated yet to latest. There will be automatic upgrade to snap, where it will be available as default.

**Comment by nickbe** [comment]
When will this automatic upgrade be active?

**Comment by nickbe** [comment]
Or is there a way to update wekan manually to the latest version (3.03 as of today)?

**Comment by xet7** [comment]
@nickbe 

https://github.com/wekan/wekan/issues/2533#issuecomment-517999731

**Comment by gkarachuk** [comment]
@xet7 Thanks for the great work.
My Snap just updated today.  Is there a way to toggle between the small coloured squares and the labels with text on the minicards?

**Comment by gkarachuk** [comment]
@xet7 Thanks.
