### ISSUE TITLE
[Feature Request] Feedback when Importing from Trello

### ISSUE THREAD

**Issue by supercrypt** [wekan/wekan#1467]
**Impacted version**: v0.72
**Server Setup Information**: Local VM

* Operating System: Debian
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker quay.io Image
* Node Version:  v.8.9.3
* MongoDB Version: 3.2.18

**Problem description**:
When importing from Trello and clicking the Done button multiple times it will creating several boards (As often you click the button). It would great when there were a message like "You have successful imported the board from Trello." or something else.

For test you can use this example board from Trello:
https://trello.com/b/Mxy2o2lk/demo-board-innovation-project 
Json code: https://trello.com/b/Mxy2o2lk.json

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
