### ISSUE TITLE
How to set max size of attachment file in wekan

### ISSUE THREAD

**Issue by jcdwekan** [wekan/wekan#1468]
## Issue
**Impacted version**: 0.63.0

**Server Setup Information**:

* Operating System: centos7.3
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): haproxy ,wekan docker ,mongo
* Node Version: 4.8.7
* MongoDB Version: 3.2.13
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- We test docker wekan 0.59, 0.63, 0.71 with mongo 3.2.13 . We have to set a max size attachment file to have no video or other files in  mongo collection . I test attaching at card some files of x GO size , and no problem , this big file is alaways correctly stored in mongo collection !!!
- Is-t possible to set a max size of attachment file in env variable in wekan, meteor or other component to not have a lot of  GO of data ( video , ppt etc etc ) stored in mongo ??

**Comment by xet7** [comment]
Moved to #142

**Comment by jeandat** [comment]
IMO, #1468 and #142 are not the same. Managing attachments elsewhere is not the equivalent to limit an attachment size. They both limit your database size but they don't respond the same way. My guess is that @jcdwekan wants to forbid uploading above a certain size which I'm not sure #142 will permit.
