### ISSUE TITLE
Cards copied from other boards are not visible in swimlane view

### ISSUE THREAD

**Issue by rinnaz** [wekan/wekan#1472]
## Issue
**Impacted version**: 0.73.0

**Server Setup Information**:

* Operating System: Ubuntu 16.04.3
* Deployment Method: snap
* Node Version: 8.9.3
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
If you copy a card from one board to another, at destination board it won't be visible in swimlane view, but only in list view.

**Comment by xet7** [comment]
@andresmanelli 

Can you look at this?

**Comment by andresmanelli** [comment]
I'll try to take a look this week.

**Comment by andresmanelli** [comment]
Maybe this bug is fixed with https://github.com/andresmanelli/wekan/commit/4b53b0c90a57593c0fe2d808d2298e85f488bfa9 as it is related to #1520
