### ISSUE TITLE
Feature request: Consecutive card numbering?

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1473]
When do you plan to introduce this feature?

**Comment by xet7** [comment]
@therampagerado 

Do you mean counting cards in list? Wekan already has that feature, see screenshot below.

Or do you mean other feature? Please explain, with screenshot mockup if possible.

![test counting cards](https://user-images.githubusercontent.com/15545/36022620-606a2aae-0d92-11e8-807e-d9cacd3d901d.png)

**Comment by therampagerado** [comment]
Hello xet7, thank you for your quick reply!

No I mean each new card to receive new unique number so this system can be used as internal tickets system or orders system.

Our case is:
We are shop and we need to manufacture our goods and we need software that can have kanban with different stages of one order and each order must have unique number so we can track them by that.

**Comment by therampagerado** [comment]
Also I installed snap with Ubuntu on my virtualbox for testing.

Is this secure enough for intranet use? I see it does not send out emails which is nice.

But I see couple of issues:
1. There is no settings on normal users - what they can and can not do. So now they can delete the whole kanban, do whatever they want.
2. The attachments (in our case pdfs) are not displaying in the preview. They download normally.

The first one is a stopper for us. I would like to have granulated control so not everybody can stop the company's daily work routine at any time (by mistake or on purpose).

Also I can you give me info on how to update the snap release to the latest version?

Sorry for this offtopic!

**Comment by xet7** [comment]
@therampagerado 

Hi,
this is not offtopic, Wekan is general purpose kanban tool that is in use from single users to large companies where there is thousands of users of Wekan, and also in high security places like healthcare etc. Wekan does not by itself send any data to Internet. Wekan is in use in intranets and also works without direct internet access, if you don't need to download updates, or move updates with some media like usb stick or cdrom to intranet.

Wekan does not send email if email settings are not configured correctly.

In board settings you can set from other user icons the permissions to comment only, they are not able to delete then.

Previewing PDF files is not implemented, please ask about it at https://github.com/wekan/wekan/issues/1318 could somebody implent it, or pay some developer to implement it, or add bounty to that issue - instructions at https://wekan.team

Example of implemented workflow with rest api is at https://github.com/wekan/wekan-gogs , other way to implement workflows is with Huginn or Flogo https://github.com/wekan/wekan/issues/1160

You ca update all snaps to newest version with command: sudo snap refresh
After updating you need to setup root-url again https://github.com/wekan/wekan-snap/issues/29

REST API docs are at https://github.com/wekan/wekan/wiki/REST-API

**Comment by therampagerado** [comment]
Thank you for your kind reply!

Where I can check the setting of the board? I can only change it's name when clicking on it.

What do you think regarding the numbering of the cards? Can this be implemented in any recent version?

**Comment by xet7** [comment]
@therampagerado 

First Wekan user is admin. Every user registers account, logins to wekan, and usually uploads their own face photo as avatar in top right menu profile settings. Admin creates new board and invites board users with existing username to board. Admin clicks some invited member face photo avatar and from that dropdown menu selects permissions as comment only.

About numbering of cards feature, please add screenshot mockups and more detailed description how this feature would work step by step. Are there any developers in your company that can write code to use Wekan REST API ? Or do you have budget for this feature? More details at https://wekan.team

**Comment by therampagerado** [comment]
Thank you!

I saw where those settings are located. Unfortunately 'comment only' is useless in this case because they even can't move the cards across columns.

There may be access level as:
-move, view, comment all cards
-edit own cards
-don't add, edit, delete lists, boards, column and swim-line names.

At least that. If in future more granular access rights can be implemented where every admin can create groups and rights for those groups based on functionalities of the system this will be great.

Regarding the card numbering - something like that
![image](https://user-images.githubusercontent.com/11251370/36029690-e9a3ec8c-0dac-11e8-9452-4833d882774e.png)

So every new card to get the next number.

**Comment by d3dbit** [comment]
I am also interested about: 
"*each new card to receive new unique number so this system can be used as internal tickets system or orders system. This number must be visible in collapsed view next to the name of the card too.*"

**Comment by xet7** [comment]
This feature has now been added by @syndimann at https://github.com/wekan/wekan/pull/3935 , will be in upcoming Wekan v5.43 later today.
