### ISSUE TITLE
[Feature Request] Expandable labels

### ISSUE THREAD

**Issue by naushil** [wekan/wekan#1479]
Hello. It would be great to have expandable labels so we can read the label text on the card itself. This feature is by default present in Trello.

**Comment by xet7** [comment]
Wekan is not Trello, see https://github.com/wekan/wekan/issues/92#issuecomment-364590215

Moved to #1466

**Comment by naushil** [comment]
Thanks, and my apologies for mentioning Trello.

**Comment by xet7** [comment]
@naushil 

No problem :) Wekan does import from Trello etc :)

**Comment by naushil** [comment]
I would like to contribute a Bounty for this. Where can I do that? :) @xet7

**Comment by xet7** [comment]
@naushil 

Setup bounty for #1466 as it is same issue, I will add instructions to there.
