### ISSUE TITLE
Can I meteor build wekan from OSX for windows?

### ISSUE THREAD

**Issue by NegativeDearc** [wekan/wekan#1480]
Hello,

We want use for a 4-5 man team, windows 7 platform behind proxy makes the situation a litte complex.

I tried meteor serval times following the instruction but failed due to the internet problem.

So I try to meteor build from OSX for windows x64, after the move to the windows, it throw errors like module missing something ....when I run `node main.js`.

Appreciate for every help.

**Comment by xet7** [comment]
@NegativeDearc 

If you get Docker installed, you can setup Docker to use proxy:
https://docs.docker.com/network/proxy/

Then you can start Wekan with Docker like this, change 192.168.1.200 to your IP address and 8080 to your port:
```
docker run -d --restart=always --name wekan-db mongo:3.2.18

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://192.168.1.200:8080" -p 8080:80 quay.io/wekan/wekan:v0.73
```

Another option is to download VirtualBox image and setup it to use Bridged Networking:
https://wekan.xet7.org

Then setup Ubuntu to use proxy:
https://askubuntu.com/questions/664777/systemwide-proxy-settings-in-ubuntu

Then rebuild newest Wekan from source with rebuild-wekan-meteor-1.6.sh script:
https://github.com/wekan/wekan-maintainer/tree/master/virtualbox

Does this help?

**Comment by xet7** [comment]
Building Wekan on Mac:

Install Docker for Mac, and use Docker Compose script, adding root-url etc settings there, this downloads prebuilt docker containers:
https://github.com/wekan/wekan-mongodb

You can save Docker images of wekan and mongodb containers to file with save command, and load it with load command on another computer:
https://docs.docker.com/engine/reference/commandline/save/

Then you start this docker-compose.yml file with your restores images name, like:
image: dsf83032yerh
for both wekan-app and mongodb containers:
https://github.com/wekan/wekan-mongodb

If you really want to build source (takes more time), clone https://github.com/wekan/wekan repo, copy your docker-compose.yml file there with correct root-url etc settings, and do:

```
docker-compose up -d --build
```

**Comment by NegativeDearc** [comment]
@xet7 Thank you very much my friend. I'll try more times.
