### ISSUE TITLE
Scrollbar appear not inside card when mouse click the card 

### ISSUE THREAD

**Issue by jkryanchou** [wekan/wekan#1481]
## Issue
**Impacted version**: v0.73

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): docker-compose 
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
   I have setup an wekan app from `docker-compose.yml` within in repo. 

   While When I create a new card and add more checklist into card, and I try to scroll down to see more tasks. The scrollbar seems appear outside card which is differ from old version `wekanteam/wekan:metoer:1.4` . It seems not so smoothly to do the operations. Compare to old version, the scrollbar appear inside card when my mouse move into card. You could refer difference from the red arrows.

The v0.73 version

![image](https://user-images.githubusercontent.com/1206342/36110050-514a8a2e-105c-11e8-8144-13317019e3a5.png)

And the old one wekanteam/wekan:meteor-1.46

![image](https://user-images.githubusercontent.com/1206342/36110163-a5d10898-105c-11e8-867c-efa421e33391.png)

I thought changing the scrollbar position is not a good decision. It scroll not smoothly.

**Comment by xet7** [comment]
@andresmanelli 

Can you look at this?

**Comment by jkryanchou** [comment]
@xet7 Have this issue been fixed in v0.74?

**Comment by xet7** [comment]
@jkryanchou 

No. This issue is still open. I usually close those issues that are fixed.

**Comment by jkryanchou** [comment]
@xet7 OK, Thanks all the same. Wish it to be fixed soon. : ) Wekan is so awesome, and wish it could
 be better and better. 👍

**Comment by jkryanchou** [comment]
@xet7 OK, Thanks all the same. Wish it to be fixed soon. : ) Wekan is so awesome, and wish it could
 be better and better. 👍

**Comment by xet7** [comment]
@jkryanchou 

You can support developing Wekan with Commercial Support and Bounties https://wekan.team
