### ISSUE TITLE
Feature request : [Trello Like] Sortable checklist and items list

### ISSUE THREAD

**Issue by mlorgeoux** [wekan/wekan#1483]
## Feature request
**Impacted version**: 0.34.0

**Feature request description**:
It would be great if we can dispose a sortable checklist feature (as trello).
For the moment, a checklist can be added or removed in the create order, but it is not possible to :
- change the order of the checklists in a card
- sort the items position in a checklist without remove and recreate in the right order

**Comment by xet7** [comment]
I think dragging checklists worked when @GhassenRjab added it at #876 but after @andresmanelli added swimlanes #955 there is some bug in migrations at https://github.com/wekan/wekan/blob/devel/server/migrations.js so dragging does not work anymore.

@andresmanelli @GhassenRjab 

Can you look at this?

**Comment by xet7** [comment]
@mlorgeoux  

Are you running Wekan v0.34 ? Why not latest Wekan version?

**Comment by mlorgeoux** [comment]
@xet7 : 
We still running on Wekan 0.34 because we did not take time to upgrade our inside platform
We will do it in the next few days !
Thanks
