### ISSUE TITLE
Horizontal scrolling doesn't work through dragging anymore

### ISSUE THREAD

**Issue by DissCent** [wekan/wekan#1484]
## Issue
**Impacted version**: 0.74.0

**Server Setup Information**:

* Operating System: Debian 9
* Deployment Method: docker (through quay.io/wekan/wekan)
* Node Version: 8.9.3
* MongoDB Version: 3.2.18
* ROOT_URL environment variable (Is there a subfolder?): https://wekan.sweetba.se (no subfolder)

**Problem description**:
Before the swimlanes were introduced, one could horizontally scroll within boards by simply dragging some free space around/below the cards. This was quite useful for boards with many cards. However, since the swimlanes were introduced, scrolling horizontally is only possible by scrolling down the entire page and dragging the horizontal scroll bar by hand.

This happens in both swimlane and lists view.

**Comment by onatto** [comment]
This is still an issue with 1.18.0. So annoying, please fix this.
Doesn't work with Firefox and Chromium across OSes.

**Comment by xet7** [comment]
@onatto 

Horizontal scrolling in swimlanes mode still works for me.

**Comment by onatto** [comment]
@xet7 I get the following warnings on Ubuntu 18.04, hope it helps:

Firefox 61.0.1 (64-bit) :
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

Chromium Version 66.0.3359.181 (Official Build):
d1dfc27486a69648beff442d89026c578decd83d.js?meteor_js_resource=true:207 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by lonix1** [comment]
Doesn't work for me either.
Ubuntu 18.04
Firefox latest
Chromium latest

**Comment by lonix1** [comment]
I don't know meteor, so I fixed this with a Tampermonkey script and some jQuery.

I took inspiration [from here](https://stackoverflow.com/a/22079985/9971404), and changed it so it works as expected. It drags horizontally and vertically, but won't drag if there is already a card drag underway.

You need Tampermonkey or Greasemonkey or something similar, then install the userscript below. *MAKE SURE to change `http://localhost:8080/b/*` to wherever your wekan server is.*

````js
// ==UserScript==
// @name         wekan
// @match        http://localhost:8080/b/*
// ==/UserScript==

(function() {
  "use strict";

  $.fn.attachDragger = function() {
    var attachment = false, lastPosition, position, difference;
    $(this).on("mousedown mouseup mousemove", function(e) {
      var elementToScroll = $(".board-canvas");
      if (elementToScroll.hasClass("is-dragging-active")) {
        elementToScroll.css("cursor", "default");
        attachment = false;
        return;
      }
      if (e.type == "mousedown") {
        attachment = true;
        lastPosition = [e.clientX, e.clientY];
      }
      if (e.type == "mouseup") {
        elementToScroll.css("cursor", "default");
        attachment = false;
      }
      if (e.type == "mousemove" && attachment == true) {
        elementToScroll.css("cursor", "pointer");
        position = [e.clientX, e.clientY];
        difference = [ (position[0]-lastPosition[0]), (position[1]-lastPosition[1]) ];
        elementToScroll.scrollLeft(elementToScroll.scrollLeft() - difference[0]);
        elementToScroll.scrollTop(elementToScroll.scrollTop() - difference[1]);
        lastPosition = [e.clientX, e.clientY];
      }
    });
    $(window).on("mouseup", function() { attachment = false; });
  }

  $("#content").attachDragger();

})();
````
