### ISSUE TITLE
No vertical scroll inside Lists, only browser scroll

### ISSUE THREAD

**Issue by edcaron** [wekan/wekan#1485]
## Issue
**Impacted version** 0.74.0

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method: Docker
* Node Version: 8.9.3

**Problem description**:
- Vertical scroll inside Lists now appearing anymore, only on the right of the page, the browser scroll which scrolls all the page
- Happens both on Firefox and Chrome
![gif](https://user-images.githubusercontent.com/12371872/36314869-462c6018-131d-11e8-9d82-bbd0715ae003.gif)

**Comment by andresmanelli** [comment]
Could you test commit https://github.com/andresmanelli/wekan/commit/a033c35a3411902b9bf8f62a40cd68f641e573d3 ?
