### ISSUE TITLE
Swimlane menu button overlaps Swimlane name

### ISSUE THREAD

**Issue by Gobliins** [wekan/wekan#1487]
ATM the menu button for the swimlanes is directly across the name of the swimlane.
This prevents users from renaming a swimlane.

**Comment by andresmanelli** [comment]
@xet7 @Gobliins Commit https://github.com/andresmanelli/wekan/commit/37c94622e476f50bf2387bc8b140454d66200e78 fixes this for me. Could you check?

**Comment by Gobliins** [comment]
@xet7 Yep https://github.com/andresmanelli/wekan/commit/c4fa9010f34966b633c7bf7e46ad49fc101127c9 fixed it.
