### ISSUE TITLE
Wekan is down- please help!

### ISSUE THREAD

**Issue by jenbrody** [wekan/wekan#1491]
The website does not work- it says "502 Bad Gateway" when I go to the page: https://wekan.indie.host/
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System:
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by xet7** [comment]
I have emailed admins of that website. They will fix it asap. Please try again later.
