### ISSUE TITLE
General future of Swimlanes

### ISSUE THREAD

**Issue by Gobliins** [wekan/wekan#1492]
If i may ask, what are your future plans for the swimlanes?
Will there be any improvement on it, because in it's current state, it is not usable. Even worse, it seems like you brooke your own layout.

Things which i am interested in:
-Lists as the overlapping element so only one header is at top and swimlanes are just a seperator, now we have always the list header repeated
-Lists should be scrollbar again without the header, only list bodies should be scrollable
-Also the general boardbody should be static and if cards move out of the body, a scrollbar should do the job instead of enlarging the boardbody
-Will swimlanes be movable inside lists?
-When adding a new swimlane or card by pressing the plus symbol, it should pop up where i clicked the plus symbol and not on the upper most list (or on the bottom in case its a swimlane)

Are any of these features planned in the near future?

**Comment by xet7** [comment]
@Gobliins 

All currently know swimlanes issues have been listed on Roadmap https://github.com/wekan/wekan/projects/2 . Please support work of @andresmanelli with bounties etc.
