### ISSUE TITLE
initials updates not visible to other members.

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1498]
## Issue
**Impacted version**: 0.76

**Server Setup Information**:

* Operating System: Ubuntu
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): snap
* Node Version: 8.9.3
* MongoDB Version: 
* ROOT_URL environment variable (Is there a subfolder?): no

**Problem description**:
- when I update my initials they are visible only to me and not other members of the board. If I change my name everything is visible but this issue is only with the initials.

**Comment by m1d1** [comment]
We've a bug with the initials, too. We recently switched all user profile pictures to initials. The "initial profile picture" on cards is taken from the fullname and not from the initial field. The difference is the upper/lowercase and the amount of letters. Own initials always appear correct on cards, others don't. This affects new and existing boards and is probably not related to this issue.

**Comment by NicoP-S** [comment]
@xet7 can be closed
