### ISSUE TITLE
Feature Request: Move List

### ISSUE THREAD

**Issue by zeineath** [wekan/wekan#150]
Just wondering, will the ability to copy/move a list from one board to another be applied in the future releases? 

This feature will really be helpful instead of manually copying unfinished tasks from time-based boards like "2015 1st Quarter" to "2015 2nd Quarter", etc. 

Thanks for the great project you have going here. :)

**Comment by xet7** [comment]
PR https://github.com/wekan/wekan/pull/446 will be merged later.
