### ISSUE TITLE
Announcement not visible for rest of crew

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1501]
## Issue
**Impacted version**: 0.76

**Server Setup Information**:

* Operating System: Ubuntu
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): snap
* Node Version: 8.9.3
* MongoDB Version: 
* ROOT_URL environment variable (Is there a subfolder?): no

**Problem description**:
- I as admin have set up an announcement but it's not visible for the rest of the crew added to this board.

**Comment by xet7** [comment]
This did work earlier when I merged and tested this feature, but maybe swimlanes or some other addition broke it.

**Comment by therampagerado** [comment]
Not very important but I am trying to implement wekan in our company so we can keep track of orders and this came up today.

Really not a stopper but if somebody has time it can be checked. Just wanted to share with the community.

**Comment by xet7** [comment]
@therampagerado 

Thanks a lot for reporting this, I did not know this was broken. It is very important to know if something is broken.

We have new developers and companies getting up to speed in adding fixes and new features to Wekan, it just takes some time.

**Comment by xet7** [comment]
This is already fixed in newest Wekan v1.03.
