### ISSUE TITLE
Sandstorm: List view no longer extends to the bottom of frame

### ISSUE THREAD

**Issue by ocdtrekkie** [wekan/wekan#1506]
## Issue
**Impacted version**: Tested 0.76 / 0.77

**Server Setup Information**: Sandstorm

**Problem description**:
The scrollbar should be at the bottom of the screen. It was fine as of 0.63, so something broke in changes between then and now.

![image](https://user-images.githubusercontent.com/4399499/36634604-a8dc48d6-196c-11e8-82c6-4180efff6dd3.png)

**Comment by therampagerado** [comment]
I have the same issue on snap 0.77. Yesterday it was fine. Today half of the screen is grey. Now I can scroll in the columns but it's useless because I only see 2-3 orders per column.

**Comment by andresmanelli** [comment]
This should be fixed in https://github.com/andresmanelli/wekan/commit/c62a2ee11febf7f98456c97dc3973509b4bfe119. Forcing 100% height in list view.
