### ISSUE TITLE
Email invitations to Wekan board not sent- could someone please help? Thank you!

### ISSUE THREAD

**Issue by jenbrody** [wekan/wekan#1509]
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System:
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by xet7** [comment]
Moved to #1320
