### ISSUE TITLE
Wekan Snap stops working every day, services not restarted after updates.

### ISSUE THREAD

**Issue by tmaierbnp** [wekan/wekan#1513]
## Issue
**Impacted version**: 0.77.16.ga23d933

**Server Setup Information**: Ubuntu core 16.04 kernel 4.4.0-116-generic in VM

* Operating System: Ubuntu core 16-2.31.1
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Snap 2.31.1
* Node Version: v8.9.3

**Problem description**:
Wekan is not responding in the morning.
Must restart the snap to make it work again. Behavior started with update to current version.

How can I create a log of the wekan activity?

Note: Outward behavior resembles  #1489; but since I don't know how to create a wekan log...

**Comment by Anuril** [comment]
I am also experiencing this problem. 
It stops working because of the Snap Updates being pushed. The services are not restarted after the Updates. 

This is very annoying...

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan-snap/issues/36
