### ISSUE TITLE
BUG + FIX AddCard is missing when dragging swimlanes or lists

### ISSUE THREAD

**Issue by Gobliins** [wekan/wekan#1519]
**BUG**: 
When dragging lists or swimlanes, the `addCard` field, dissapears.
   
**FIX**: 
You have to add the `boardComponent.setIsDragging(false);` in `client/components/swimlanes.js` and `client/components/lists/list.js` at the end of the drag and drop event.

**Comment by xet7** [comment]
@Gobliins 

Can you try to make pull request to devel branch?

**Comment by Gobliins** [comment]
I am not familiar with github at all. But i can try, when i am back on the project, which will be in 3-7 days.
In general it's not much, it's just two lines of code.

**Comment by xet7** [comment]
@Gobliins 

On what lines in source code? Can you attach modified file to this issue in .zip archive ?

**Comment by andresmanelli** [comment]
@xet7 I can add this later today, I know where to put those lines. I introduced this bug with my commits :D

**Comment by andresmanelli** [comment]
@xet7 See commit https://github.com/andresmanelli/wekan/commit/58e5e9b308113e5a8af5166328a68a0aafcc2558, that should fix this.
