### ISSUE TITLE
Move card is not working correct with swimlanes

### ISSUE THREAD

**Issue by stahlstift** [wekan/wekan#1520]
## Issue
**Impacted version**: 0.73

**Problem description**:

### Given
Board "A" with List "Foo" in any mode
Board "B" with List "Bar" in swimlane-mode

1. Create a new card in "Foo" on board A
2. Click on the card
3. Use the menu to "move" the card to "Bar" on board "B"
4. View board "B" in swimlane-mode

### Problem
You don't see the card in swimlane and think that the card is gone away.
Switch from swimlane to normal mode - you will now see the card
There is no way to use this card now in swimlane mode

### Solutions
* Long-Path: Add swimlane option to "move card"
* Short-Path: Move card to "default" swimlane

**Comment by andresmanelli** [comment]
Hello @xet7 @stahlstift, commit https://github.com/andresmanelli/wekan/commit/4b53b0c90a57593c0fe2d808d2298e85f488bfa9 fixes this issue, as well as card copy between boards.

I changed a little bit the UI in these popups (screenshot attached)

![seleccion_002](https://user-images.githubusercontent.com/7302217/37106948-d20c2fb6-2211-11e8-80fd-f9a7371ee5ce.png)

**Comment by andresmanelli** [comment]
Sorry I didn't notice @GhassenRjab was working on this

**Comment by GhassenRjab** [comment]
@andresmanelli practically we've done the same thing. I just kept the lists clickable.
My PR will take time as I am still developing it. If your PR is ready, submit it, there is no problem

**Comment by stahlstift** [comment]
thx @andresmanelli , @GhassenRjab and @xet7 for your work!
