### ISSUE TITLE
Can not scroll in middle of page when card is open. Scrolling possible only using right scrollbar in between of card display and sidebar.

### ISSUE THREAD

**Issue by simopaasisalo** [wekan/wekan#1521]
## Issue
**Impacted version**: 0.77
* Operating System: Linux
* Deployment Method): Docker
* Node Version: v.8.9.3

**Steps to reproduce**:
Create a list and add so many cards that you need to scroll down a fair bit
Select the bottom card

**Expected behaviour**:
The card details open next to the selected card

**Actual behaviour**:
The card opens on top the page, and you cannot scroll up to it

**Problem description**:
A couple of versions ago you changed the behaviour that the card details open in the top of the page, not in the middle of the screen. This was okay-ish, but now in 0.77 you can no longer scroll the page up or down, so if you open a card from the bottom of a long list, you cannot scroll up to actually see the contents. The only way to do it now is to use the search to reduce the length of the list first, and then open the card

**Comment by xet7** [comment]
@simopaasisalo 

Please try from GitHub releases page quay docker image latest tag, is this still an issue. Some scrolling bugs were fixed yesterday.

**Comment by simopaasisalo** [comment]
Update: You can still scroll if you put the mouse cursor on top of the card list, but it should really work for the whole page IMO.

**Comment by simopaasisalo** [comment]
I just updated from the latest image in docker half an hour ago, so this should be up to date

**Comment by xet7** [comment]
@simopaasisalo 

I did:
- make a long list
- open card, it opened at top
- scrolled to up using scrollbar that is between card display and sidebar
- changed card details

Sure it's not yet possible to scroll in middle of the page yet, only using right scrollbar, so editing card is possible, but it could be improved.

**Comment by simopaasisalo** [comment]
Hmm, now I have the latest docker build from quay and the same behavior repeats. Can only start scrolling when my mouse is on the active card. Cannot see any scrollbar between card display and sidebar.

Tested this on Edge, and scrolling from the middle of the screen does work there. I'm currently of the latest Firefox Nightly, and the guys that reported me are on the latest Firefox default build.

**Comment by simopaasisalo** [comment]
![capture](https://user-images.githubusercontent.com/17126867/36898004-3a8cd98e-1e19-11e8-939d-ca6947615397.PNG)

**Comment by xet7** [comment]
I'm using latest Ubuntu Snap version and Firefox 58.0.1 on Debian Sid 64bit. I have not tried other versions.

**Comment by therampagerado** [comment]
I have the same issue here with the latest snap release.

It would be nice to have the details open in middle of page because we  can have long lists.

Now I can only scroll if my pointer is over the active card and when it's out of the window I can't scroll up/down.

**Comment by simopaasisalo** [comment]
Just for closure: this is fixed now in 0.80
