### ISSUE TITLE
Scrollbar near top of screen when using internet explorer on Win7

### ISSUE THREAD

**Issue by lunatic4ever** [wekan/wekan#1524]
## Issue
**Impacted version**: 0.77

**Server Setup Information**: 

* Operating System: Ubuntu 16.04.04
* Deployment Method: tar
* Node Version: 8.9.4
* MongoDB Version: r3.2.19
* ROOT_URL environment variable: https://vm-wekan.jandenul.com

**Problem description**:
* Upgrade from v0.63
* works perfectly in Google Chrome
* But with Internet Explorer the horizontal scrollbar is positioned near the top of the screen.
![wekan](https://user-images.githubusercontent.com/29978082/36963638-57447676-2054-11e8-9fba-a70e64b60764.png)
* Tried with ie 11.0.9600.18920 on Win7 and 11.248 Win10

**Comment by etiehuis** [comment]
We got the same problem with Internet Explorer.
No problems with Chrome.

![ie11](https://user-images.githubusercontent.com/37071581/36974524-e056ca80-206e-11e8-8a33-8b043aa902d9.JPG)

Thanx for this great product.

Greetings,

Eric

**Comment by xet7** [comment]
@lunatic4ever @usernotuse 

Please try latest Ubuntu Snap version.

**Comment by usernotuse** [comment]
Where using the latest Ubuntu Snap version. 
![snap-version](https://user-images.githubusercontent.com/37071581/36978215-0454265c-2084-11e8-9da2-a633d05066a5.png)

**Comment by ocdtrekkie** [comment]
I was seeing very similar on Sandstorm with the latest versions, the scroll bar is no longer properly attached to the bottom of the window.

**Comment by therampagerado** [comment]
Open your css and find "350px".

If it's there you have got the recent PRs here where they tried to fix the columns scroll. Comment or remove and you will have your full height depending on the number of cards per column. The scrolling in each column will not work but it's better.

**Comment by xet7** [comment]
@usernotuse 

What does these commands show as your Wekan version?

```
$ sudo snap refresh
$ sudo snap list
Name   Version           Rev   Developer  Notes
core   16-2.31.1         4110  canonical  core
wekan  0.77-29-g9e62584  137   xet7       -
```

@ocdtrekkie @therampagerado 

Newest fixes are not yet at newest Sandstorm version yet. Please wait for next release, as only I can make releases for Sandstorm.

**Comment by lunatic4ever** [comment]
if we change the CSS style then the problem is resolved.
Apparently, the **flex:1** is not translated correctly in IE. But if you follow the W3C guidelines and change it to **flex: 1 1 auto** it behaves the same in IE and chrome.
![css wekan](https://user-images.githubusercontent.com/29978082/36984899-2ce64796-2096-11e8-8e4b-947cc7bdd49b.png)
