### ISSUE TITLE
Boards are empty after upgrade from 0.63 to 0.77

### ISSUE THREAD

**Issue by Madko** [wekan/wekan#1525]
## Issue
**Impacted version**: 0.77

**Server Setup Information**:

* Operating System: CentOS 7
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): tar
* Node Version: 8.9.3-1nodesource
* MongoDB Version: 2.6.12-6
* ROOT_URL environment variable (Is there a subfolder?): no subfolder

**Problem description**:
- we are actually using wekan 0.63
- everything is working fine
- we are testing upgrade to 0.77 on a new install
- mongodb data are dumped from the running 0.63 and restored on the 0.77 test instance
- I can log in with my user, so data seems ok from mongodb
- homepage shows all boards, but when you click on any of them, no cards are shown, no list, just the activity log.
- In firefox the only error I get is:
`There is no route for the path: /b/sd7uym2CGQAix9DRr/BOARD`
- Creating a new board seems to work. I can great swimlane, list, cards etc

Where can I find more logs ? I there a way to check or upgrade data ? Should I upgrade to previous version before directly jump to 0.77 ?

Best regards,
Edouard

**Comment by xet7** [comment]
@Madko 

Did you setup ROOT_URL correctly like described at here?
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml#L70-L86

Did you restore MongoDB with `mongorestore --drop` ? If not, all data is not restore correctly.

**Comment by Madko** [comment]
@xet7 I'm not using docker but I will check if I have a ROOT_URL somewhere. I'm also not sure about the --drop. Thanks for your help. I will keep you in touch.

**Comment by Madko** [comment]
@xet7 great this is working !
In order to correctly migrate the database schema wekan must be stopped first. Then data can be restored. At startup wekan will migrate the data.
Thanks you for your help
