### ISSUE TITLE
0.77 - issue with card details swiping under the sidebar

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1528]
## Issue
**Impacted version**: 0.77

**Server Setup Information**:

* Operating System: Linux
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): snap
* Node Version: 8.9.3
* MongoDB Version: na
* ROOT_URL environment variable (Is there a subfolder?): no

**Problem description**:
- when I try to open card in one of the columns in right of screen the card details panel swipes under the sideboard and does not move it as it was up until the latest fixes. This renders the card hamburger menu unusable.

- workaround is to firstly scroll fully right and hope the menu is visible or close the sidebar first then open the card. I imagine this is not the way it should behave
![issue-card-swipe-right](https://user-images.githubusercontent.com/11251370/37143435-dad19778-22c3-11e8-8830-84ee23c19f7b.jpg)

**Comment by xet7** [comment]
I think that when using those lists at right, cards should open to left side, not right.

**Comment by therampagerado** [comment]
For me it would be nicer to have it as now (and have focus on the details as now) and only the search results to slide r-l from the sidebar out. But if you want to change it I doubt it will take more than a day to get used to it.

One more thing which will be nice will be if we can have the card details swipe over the next columns, not like now to shift them right or left. With one click you can exit the details and you have the same layout as before. Now there's constant shifting of the columns which is not very bad because the shadow is obstructing the attention from this but.... just my 2 cents.

**Comment by xet7** [comment]
If cards open on top, I don't see what else is in the same list, as I'm going through cards in the list. It's not good that way.

**Comment by therampagerado** [comment]
Oh yes of course but I don't mean that.

I would like the details to swipe over the next column/s.

So the active column is visible, the active card is highlighted as of now and there's shadow.

But the details when slit out should not slide with them the rest of the columns. They should just overlap the next columns. One fast click as now on the shadow and they close but the rest of the UI don't move.

Now if we close the card details the columns right of them move left. Which as I said is not very bad because the shadow cover part of this move but if I look for certain card when the shadow is present and need it it will move when I close it and I have to search for it again.

Hope I described it better now!

Keep the great work on!

I noticed that you're working on features on cards? Any time-frame on those PRs?

**Comment by xet7** [comment]
@therampagerado 

What features on cards? I don't know about time-frames yet.

**Comment by xet7** [comment]
@therampagerado

It is on "Status not known".

I did try to merge it previously, but failed. Help welcome, anyone can try to clean it up and submit working pull request.

**Comment by kingflurkel** [comment]
When a card is opened, I think the scrolling of the board should be disabled.

**Comment by xet7** [comment]
@therampagerado 

Doh, I myself added Custom Fields in [blog post about plans for 2018](https://blog.wekan.team/2017/12/2-years-of-wekan-what-we-archieved/index.html). Ok, so I added it to my todo list. I'll try harder :)

**Comment by andresmanelli** [comment]
Hello, I think this is related to #1538. I think the commit mentioned there should cover this issue too.
