### ISSUE TITLE
After import of a Board drag-and-drop functionality for Lists doesn't work

### ISSUE THREAD

**Issue by filippovaleksei** [wekan/wekan#1529]
## Issue
**Impacted version**: latest docker image from wekanteam/wekan

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):docker with nginx frontend
* Node Version: 8.9.3
* MongoDB Version: 3.2.18
* ROOT_URL environment variable (Is there a subfolder?): https://xxx.xxx.xxx.xxx (it’s an IP address)

**Problem description**:
* After export-import of any Board the Lists can be dragged but when dropped return to initial position they were after import;
* When Lists of the imported Board are renamed they are automatically moved 
* These problems were discovered when we played around after first installation of Wekan and tested different functions/options. The problem was reproduced, and the situation remains the same in every new Board.  

[Wekan.docx](https://github.com/wekan/wekan/files/1793736/Wekan.docx)

**Comment by xet7** [comment]
Docker Hub wekanteam/wekan is broken, as can be seen from https://github.com/wekan/wekan/releases page, only quay latest tag really has latest Wekan. Generally I recommend Ubuntu Snap version, because it updates automatically newest version. Anyway, this bug is still at newest Snap, so it affects all platforms.

**Comment by liuhuancom** [comment]
Re-enter the panel drag and drop feature does not work

![image](https://user-images.githubusercontent.com/3874638/37239377-73dcf75c-2475-11e8-850e-441d76f4afd4.png)

TypeError: Cannot set property '_uihooks' of undefined
    at constructor.onRendered (list.js:30)
    at Blaze.TemplateInstance.onRendered (peerlibrary_blaze-components.js?hash=c2944d32784d8c8d38e21acc757b7dfaae2b26d5:839)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3398
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744)
    at fireCallbacks (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3394)
    at Blaze.View.<anonymous> (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3487)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1845
    at Object.Blaze._withCurrentView (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1844
    at Object.Tracker._runFlush (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:548)

**Comment by andresmanelli** [comment]
I think this issue was happening not because of import itself, but because of some code put in the wrong place that also broke drag & drop when leaving a board and reentering.

Commit https://github.com/andresmanelli/wekan/commit/5b0f7f8aef115b202aaff6bc25bb514426dc2009 should fix this
