### ISSUE TITLE
Docker build failed on Windows 

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [wekan/wekan#1531]
## Issue
**Impacted version**: 0.71.0

**Server Setup Information**:

* Operating System: Windows 10 Pro 64
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker
* Docker version 17.09.0-ce, build afdb6d4
* docker-compose version 1.16.1, build 6d1ac219
* Node Version: -
* MongoDB Version: -
* ROOT_URL environment variable (Is there a subfolder?): -

**Problem description**:
When trying to build the docker image on a Windows host the build failed when trying to download the correct NodeJS version for my platform:

```
λ docker-compose up -d
WARNING: The NODE_VERSION variable is not set. Defaulting to a blank string.
WARNING: The METEOR_RELEASE variable is not set. Defaulting to a blank string.
WARNING: The NPM_VERSION variable is not set. Defaulting to a blank string.
WARNING: The SRC_PATH variable is not set. Defaulting to a blank string.
WARNING: The METEOR_EDGE variable is not set. Defaulting to a blank string.
WARNING: The USE_EDGE variable is not set. Defaulting to a blank string.
Pulling wekandb (mongo:3.2.18)...

[...]

Running hooks in /etc/ca-certificates/update.d...
done.
--2018-03-09 08:56:05--  https://nodejs.org/dist/v8.9.3/node-v8.9.3-64.tar.gz
Resolving nodejs.org (nodejs.org)... 104.20.22.46, 104.20.23.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org (nodejs.org)|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-09 08:56:05 ERROR 404: Not Found.

Cloning into 'kadira-flow-router'...
Cloning into 'meteor-useraccounts-core'...
/bin/sh: 1: cd: can't cd to /home/wekan/.meteor
error: exec: "/home/wekan/.meteor/meteor": stat /home/wekan/.meteor/meteor: no such file or directory
ERROR: Service 'wekan' failed to build: The command '/bin/sh -c useradd --user-group --system --home-dir /home/wekan wekan && [...]  returned a non-zero code: 1
```

There is no https://nodejs.org/dist/v8.9.3/node-v8.9.3-64.tar.gz available for download. However, if you look at the directory https://nodejs.org/dist/v8.9.3/ there is a node-v8.9.3-64.msi or node-v8.9.3.tar.gz (without the 64) available for download.

My guess is that the build fails because the setup can not correctly identify the platform I try to build on, and therefore tries to download a non-existing file.

The corresponding line in the dockerfile is:

```
wget https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz && \
```

**Comment by xet7** [comment]
@centigrade-thomas-becker 

Where did you get that old docker compose file? It uses old version number of MongoDB.

Correct docker-compose file is here:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml

It downloads precompiled Docker container from quay, for normal use there is not need to compile it.
```
docker-compose up -d
```

If you instead want to compile it in Docker:
```
git clone https://github.com/wekan/wekan

cd wekan
```

Then edit docker-compose.yml file in wekan directory to have your correct ROOT_URL etc, and built it:
```
docker-compose up -d --build
```
