### ISSUE TITLE
need to have option to automate backup to s3 supported storage

### ISSUE THREAD

**Issue by jshupptechnologies** [wekan/wekan#1534]
Is it possible to support cloud s3 storage like AWS S3 or digitalocean spaces to configure with the default config file of wekan or via snap installation that it backups the data at predefined intervals ?
I know this is not an issue but can be treated as feature request.

But would be great if someone considers adding this to wekan / snap installation and all other supported setups.

**Comment by xet7** [comment]
@jshupptechnologies

Yes, I can add it, if someone adds bounty to this issue. More details about bounties at https://wekan.team

**Comment by jshupptechnologies** [comment]
ok i see. :+1:

**Comment by xet7** [comment]
Moved to #142
