### ISSUE TITLE
Overlay while editing is blocking scrolling

### ISSUE THREAD

**Issue by Hendrik410** [wekan/wekan#1536]
## Issue
**Impacted version**: 0.77

**Server Setup Information**:

![image](https://user-images.githubusercontent.com/11255608/37467095-a374e0c2-285f-11e8-8a0c-4999bf03fc43.png)

**Problem description**:

If you want to edit a card for which you have to scroll down to see it, the overlay prevents you from scrolling down to the editor.
If you've hovered over the editor once and move your mouse away from it, the overlay disappears and you can scroll again. It reappears again, if you hover again over the editor.

I think, the overlay should first appear, after you hovered over the editor or, even better IMHO, the window should already be scrolled to the editor after you click the card to avoid the problem in the first place

**Comment by xet7** [comment]
@Hendrik410

Most likely you have old version. When I click card, it opens. I can scroll card up and down with mouse wheel. I can then scroll list up and down and select other card, while card stays open. When I click another card, it's details are show in opened card.

I recommend:

1) Making a backup:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

2) Removing Wekan, and installing Snap version, that has automatic updates:
https://github.com/wekan/wekan-snap/wiki/Install

3) Restoring to Snap:
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore

**Comment by Hendrik410** [comment]
That did resolve the problem, thanks.

But I did install the newest update via docker-compose, can't you get the newest updates via the repositories for docker?

**Comment by xet7** [comment]
@Hendrik410 

No. As you see from releases, docker is broken and destroys your data.
https://github.com/wekan/wekan/releases

Also Snap updates automatically, docker does not.
