### ISSUE TITLE
0.78 - the archived search items don't fold out with the latest updates on card details.

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1541]
## Issue
**Impacted version**: 0.78

**Server Setup Information**:

* Operating System: Linux
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): snap
* Node Version: 8.9.3
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?): no

**Problem description**:
- with the latest release now the card details issue is solved but this probably does some conflict with archived cards and searching for them. When we search for cards still visible on the kanban and we click on them they open. But when in the search results and we click on cards that are archived they don't open as it was introduced when search function came in few versions back.
This renders the search function useless...

**Comment by xy0** [comment]
I was experiencing this too, but I just updated and it seems to be working. I do however think that archived cards should have a visual indicator on them in the search field showing that they are archived.

**Comment by therampagerado** [comment]
I now tried with card archived while ago - it only changes the url and does not fold out.

When I search for item archived today it opens properly. 

Can we search in longer periods of time and how to set that up?

**Comment by xet7** [comment]
Search original spec only did not cover searching from archived cards, list titles and other boards, because of performance issues when there is lots of boards. This is not a bug. Add a new feature request issue and bounties to get it implemented.
