### ISSUE TITLE
Upgrading Docker v0.63 to Newer Breaks Existing Boards

### ISSUE THREAD

**Issue by spoonsauce** [wekan/wekan#1542]
## Issue
**Impacted version**: 0.74, 0.75, 0.76, 0.77, 0.78
**Server Setup Information**:

* Operating System: Debian 9
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker with NGINX for SSL
* Node Version: 8.9.3
* MongoDB Version: 3.2.18
* ROOT_URL environment variable (Is there a subfolder?): http://192.168.100.86/ (local VM)

**Problem description**:

I've been trying to upgrade my 0.63 Docker deployment for several releases.  Each time, **existing** boards break, but **new** boards work fine.

My latest attempt is with 0.78.  I stop docker-compose, delete the docker app and image, change the version of Wekan in docker-compose.yml then start it back up.  The symptoms are the same each time.  Existing boards do not load any content and the button to toggle between swimlanes and lists reads "undefined".  The browser console doesn't seem to provide any useful information.

Worth noting that search and history display correctly, it's really just loading the boards.

I wonder if I'm doing something wrong during the upgrade or if I should update to an intermediary version (e.g., 0.69 or something) before moving to the latest?

Thanks!

**Comment by xet7** [comment]
Use snap, see https://github.com/wekan/wekan/issues/1536
