### ISSUE TITLE
0.78 - Can't drag list

### ISSUE THREAD

**Issue by jy333221** [wekan/wekan#1546]
## Issue
**Impacted version**: 0.78

**Server Setup Information**:

* Dockered installation

**Problem description**:
Add a new board, add two lists, and drag the list. The list can be dragged at v0.77 but can't at v0.78.

**Comment by xet7** [comment]
Try snap. Docker is broken, as you see from releases page.

**Comment by jy333221** [comment]
I tried with snap version, it still can't drag.

**Comment by xet7** [comment]
@andresmanelli 

Can you look at this?

**Comment by xet7** [comment]
In Lists view, lists can not be dragged.

When I click Lists button to switch to Swimlanes view, in Swimlanes view lists can be dragged.

**Comment by xarinatan** [comment]
With the release of 0.78.0~2018-03-17 in Sandstorm I'm also having this bug, except the lists cannot be dragged regardless of Swimlanes or Lists view. :disappointed:

**Comment by sirup** [comment]
I also have this bug with snap.
