### ISSUE TITLE
Collaborators should be able to switch to Swimline or List view independent from the current view the creator has

### ISSUE THREAD

**Issue by ahashibon** [wekan/wekan#1547]
## Issue
**Impacted version**: 0.77

**Server Setup Information**:

* Operating System: Linux/Ubuntu using official Docker images
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker (official)
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- When the owner/creator of a board adds swimlines, and chooses either swimline view, or list view, collaborators are stuck to whatever the creator currently uses. 
- if while in List mode, a collaborator clicks on swimline view, the system switches for a split of a second to swimlines then back to to List mode
- the opposite is true if the creator is on swimline, it is not possible for collaborators to switch view.

**Comment by xet7** [comment]
Docker currently is so broken, that I only respond to Snap and Sandstorm issues. See releases page for more info.

**Comment by andresmanelli** [comment]
This is because the selected view is a field in the board's model. And I think, only the creator can modify the record. The thing is, if someone changes it, the change is made visible for everyone. I am not sure how the behavior should be.
