### ISSUE TITLE
Installation problem (fiber again)

### ISSUE THREAD

**Issue by RCohenE5Group** [wekan/wekan#1552]
## Issue
cannot install

**Impacted version**: 
https://releases.wekan.team/wekan-0.78.tar.gz

**Server Setup Information**:

* Operating System: Debian 9
* Deployment Method(snap/sandstorm/mongodb bundle): ?
* Node Version: node --version => v9.9.0 , npm --version => 5.6.0

**Problem description**:
I followed the instruction on https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps : 
- install npm and mongodb ok
- cd programs/server
- npm install
> bcrypt@1.0.3 install /home/wekan/www/programs/server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
[bcrypt] Success: "/home/wekan/www/programs/server/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
npm WARN lifecycle meteor-dev-bundle@0.0.0~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@0.0.0 node npm-rebuild.js /home/wekan/www/programs/server
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
added 137 packages in 4.292s

- cd ../..
- node main.js
>module.js:545
    throw err;
    ^
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wekan/www/programs/server/boot.js:1:75)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

After googling a little, I tried to uninstall/reinstall fiber with no success (resintall does not work, infinite loop on : user "root" does not have permission to access the dev dir "/home/wekan/www/programs/server/node_modules/fibers/.node-gyp/9.9.0")

Thanks for your help.

**Comment by xet7** [comment]
[Use snap](https://github.com/wekan/wekan-snap/wiki/Install).

**Comment by RCohenE5Group** [comment]
Hello xet7
Thanks for your answer.
I've never used snap, so I followed your tutorial at https://github.com/wekan/wekan-snap/wiki/Install on a debian server

* apt-get install snapd
* snap install wekan
* snap set wekan root-url="https://wekan.5flow.com"
* snap set wekan port='443'
* systemctl restart snap.wekan.wekan
* snap set core refresh.schedule=02:00-04:00

I had an error at install wekan : 
2018-03-29T14:33:14+02:00 INFO snap "core" has bad plugs or slots: core-support-plug (unknown interface)

After all commands, mongodb is running and listening to 27017, but I don't find any wekan process. No process is listening to port 443, I don't see any http server. You wrote that caddy is optional, so there must be another way ...

Thanks for your help.

**Comment by xet7** [comment]
If you want SSL, you can use use caddy, or other webserver as decribed in Wekan GitHub wiki.

When using caddy, caddy uses ports 80 and 443, and proxies to Wekan 3001.

If you don't need https, you can set port='80'

Wekan itself only has http.

**Comment by xet7** [comment]
Hmm, what kind of server is it? I think Snap does not run on OpenVZ.

**Comment by xet7** [comment]
Maybe you need to install from source anyway.
https://github.com/wekan/wekan-maintainer/tree/master/virtualbox

There use rebuild-wekan-meteor-1.6.sh first with option 1 to install dependencies, and option 3 to compile wekan. Modify start-wekan.sh script settings as needed.

**Comment by xet7** [comment]
Those scripts can be used directly on server, without VirtualBox.

**Comment by RCohenE5Group** [comment]
Even if I set snap set wekan port='80' + restart, there is nobody listening to port 80.
I'm using a VPS on OVH french host. I don't know which vps software they use. It is on Debian 9.4
I also tried on port 8000... Wekan seems to refuse to launch, this is what I see on /var/log/syslog :

```
Mar 29 13:09:12 wekan /usr/bin/snap[25370]: cmd.go:105: DEBUG: restarting into "/snap/core/current/usr/bin/snap"
Mar 29 13:09:12 wekan wekan.wekan[25370]: MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/150/share (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: MONGODB_BIND_IP= (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: MONGODB_PORT=27019 (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: MAIL_FROM=wekan-admin@example.com (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: ROOT_URL=https://wekan.5flow.com
Mar 29 13:09:12 wekan wekan.wekan[25370]: PORT=8000
Mar 29 13:09:12 wekan wekan.wekan[25370]: DISABLE_MONGODB=false (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: CADDY_ENABLED=false (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: CADDY_BIND_PORT=3001 (default value)
Mar 29 13:09:12 wekan wekan.wekan[25370]: MONGO_URL=mongodb:///var/snap/wekan/150/shared//var/snap/wekan/150/share/wekan
Mar 29 13:09:13 wekan wekan.wekan[25370]: /snap/wekan/150/programs/server/node_modules/fibers/future.js:280
Mar 29 13:09:13 wekan wekan.wekan[25370]: #011#011#011#011#011#011throw(ex);
Mar 29 13:09:13 wekan wekan.wekan[25370]: #011#011#011#011#011#011^
Mar 29 13:09:13 wekan wekan.wekan[25370]: Error: no hostname or hostnames provided in connection string
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at module.exports (/snap/wekan/150/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:23:11)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at connect (/snap/wekan/150/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:486:16)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at Function.MongoClient.connect (/snap/wekan/150/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:250:3)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at new MongoConnection (packages/mongo/mongo_driver.js:168:11)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at new Mongo.Collection (packages/mongo/collection.js:99:40)
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at packages/idmontie_migrations.js:38:15
Mar 29 13:09:13 wekan wekan.wekan[25370]:     at packages/idmontie_migrations.js:255:4
Mar 29 13:09:13 wekan systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Mar 29 13:09:13 wekan systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Mar 29 13:09:13 wekan systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
Mar 29 13:09:13 wekan systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling restart.
Mar 29 13:09:13 wekan systemd[1]: Stopped Service for snap application wekan.wekan.
Mar 29 13:09:13 wekan systemd[1]: snap.wekan.wekan.service: Start request repeated too quickly.
Mar 29 13:09:13 wekan systemd[1]: Failed to start Service for snap application wekan.wekan.
Mar 29 13:09:13 wekan systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Mar 29 13:09:13 wekan systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.

```

**Comment by xet7** [comment]
What kernel does server have?
```
uname -a
```

**Comment by RCohenE5Group** [comment]
Linux wekan 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

**Comment by xet7** [comment]
Snap should work on that kernel.

How much RAM does server have?

```
free -m
```

**Comment by xet7** [comment]
If you still have previously installed MongoDB running, you can stop it, because snap has it's own:

```
sudo systemctl stop mongodb

sudo systemctl disable mongodb
```

**Comment by RCohenE5Group** [comment]
root@WeKan:/etc/nginx> free -m
              total        used        free      shared  buff/cache   available
Mem:           1956          93         813          20        1049        1659
Swap:             0           0           0

I had nothing on the server before wekan install

**Comment by xet7** [comment]
@RCohenE5Group 

Please ask from OVH support is there some limitations on virtualization used on that server. Maybe some kernel permissions are disabled or something. Snap does work for me at AWS EC2 and DigitalOcean, I don't know what's wrong with OVH.

**Comment by xet7** [comment]
Snap is "Ubuntu snap" software, https://snapcraft.io , for many different distros.

**Comment by xet7** [comment]
For me snap works for example on Debian 9, Ubuntu 17.10 and CentOS 7.

**Comment by xet7** [comment]
Some of the error messages you posted are similar that I got on Qubes OS that is based on XEN virtualization, so I was unable to use Snap on Qubes OS, but anyway installation from source and using mongodb from Debian 9 repos did work.

**Comment by RCohenE5Group** [comment]
ok I'll try to install from source.
thanks

**Comment by RCohenE5Group** [comment]
I tried to restart all over again with snap, uninstalling all before. The wekan process is now running !!
(I think I forgot the there was a mongo db in my first try.... sorry)
Now I got no error in syslog.
I configured nginx like in your tutorial, setting port to 8000, and I did not change /etc/nginx/nginx.conf  because it looks all right (no modification for wekan)

But the page is white !!
The browser says : error 404 for the 2 js and the css file.
There is nothing in nginx errorlog, this is accesslog : 

```
77.147.144.146 - - [29/Mar/2018:16:29:31 +0200] "GET / HTTP/1.1" 200 836 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
77.147.144.146 - - [29/Mar/2018:16:29:31 +0200] "GET /9326dcf64d8385c8f0265a3cf0796f03990ce1a7.css?meteor_css_resource=true HTTP/1.1" 404 200 "https://wekan.5flow.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
77.147.144.146 - - [29/Mar/2018:16:29:31 +0200] "GET /4095141483dff9c3eb8c54a9c071ec1867bc46a3.js?meteor_js_resource=true HTTP/1.1" 404 200 "https://wekan.5flow.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```

I don't see when html is correctly answered but not css/js.

**Comment by xet7** [comment]
@RCohenE5Group 

In your start-wekan.sh setup:
```
export ROOT_URL=https://wekan.youdomain.com

export PORT=8000
```

**Comment by xet7** [comment]
also check that you have mongodb running ase service:
```
sudo systemctl start mongodb
sudo systemctl enable mongodb
```

**Comment by RCohenE5Group** [comment]
there is no start-wekan.sh on the server, I have set the url and port through command snap like in the wiki. The "/" request returns valid html so I suppose that the port is configured all right

**Comment by RCohenE5Group** [comment]
start and enable mongodb ok, but page is still white

**Comment by xet7** [comment]
Really? Are snap services running correctly?
```
sudo snap services
```

**Comment by RCohenE5Group** [comment]
root@WeKan:/var/log/nginx> sudo snap services
Snap   Service  Startup   Current
wekan  caddy    disabled  inactive
wekan  mongodb  enabled   active
wekan  wekan    enabled   active

**Comment by xet7** [comment]
```
sudo snap set wekan root-url="https://wekan.yourdomain.com"

sudo snap set wekan port='3001'
```

And then setup Nginx to proxy to port 3001.

**Comment by RCohenE5Group** [comment]
296  snap set wekan port='3001'
  297  systemctl restart snap.wekan.wekan
change config nginx then :
  298  /etc/init.d/nginx reload

==> same 404 on css/js

**Comment by RCohenE5Group** [comment]
wekan is listenning on port 3001 :
netstat -an|grep -i listen
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:27019           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN

**Comment by xet7** [comment]
Debian 9 uses systemd, you can reload nginx with:
```
sudo systemctl reload nginx
```

**Comment by RCohenE5Group** [comment]
this command has the same effect as init.d script, I executed it but no change

**Comment by xet7** [comment]
Do you have websockets enabled on Nginx?
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by RCohenE5Group** [comment]
yes I put exactly what is in the wiki

**Comment by RCohenE5Group** [comment]
the javascript is not loaded, so it will even not try to connect the server

**Comment by RCohenE5Group** [comment]
you can have a look here : https://wekan.5flow.com/

**Comment by xet7** [comment]
There's something wrong with Nginx settings, it does not proxy .js etc files.

**Comment by RCohenE5Group** [comment]
ok my fault, there was a stupid line try_files $uri $uri/ =404; in nginx conf... sorry about this
