### ISSUE TITLE
Importing Board from WeKan (Sandstorm) to another Sandstorm server fails.

### ISSUE THREAD

**Issue by remcooverweg** [wekan/wekan#1555]
__Just a quick update, i wanted to move one board to another instance of wekan, i have done this now, with the help of the restore function. ( i did not had to use the import board function). I will see if everything works as intended__

## Issue

I'm trying to import a board from WEKAN v0.78 (Sandstorm) to another server which i have just installed.
I keep getting the following message
" Your JSON data does not include the proper information in the correct format ".

I have used a JSON validator to validate the code and it was clean, so what to do now? 
I can share my JSON, but not in public.r

**Server Setup Information**:

* Operating System: Ubuntu 16.04 (NEW server), Ubuntu 14.04 (OLD server)
* Deployment Method(snap/sandstorm/mongodb bundle): sandstorm
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):NA

**Comment by ocdtrekkie** [comment]
Import/export is currently broken, but if you're going from Sandstorm to Sandstorm, you actually don't need to use it. The grain owner can download a backup of the grain using the download icon on the top bar of Sandstorm, and you can restore the grain to the new server with the Restore grain button on the Grains tab.

**Comment by remcooverweg** [comment]
Thanks @ocdtrekkie i will close the issue since this is the solution, thanks for the response!
