### ISSUE TITLE
0.78  Wekan not loading - 502 nginx

### ISSUE THREAD

**Issue by sirup** [wekan/wekan#1556]
## Issue
Sorry to open up this issue, but I tried to solve this for weeks now. 
When people work with Wekan, it crashes. I thought I solved it but it was just that I was lucky or less people worked with it.
Now it crashes about every 20 minutes. I then have to restart the wekan service. The it works again for 20 minutes. 
Crashes means = nginx shows 502 error. 

**Server Setup Information**:
Ubuntu Server 16.04
ROOT_URL environment variable https://wekan.example.com/:

**Problem description**:
I reset the settings fully, upgraded to the latest version.
I still get the same error - which from the log file seems to me I have to reset the settings. But I did this several times already. 

`
root-url:   wekan's root url, eg http://127.0.0.1, https://example.com, https://wekan.example.com, http://example.com/wekan
                Current value set to: 'https://wekan.example.com', (default value: 'http://127.0.0.1')
`

`Mar 28 12:37:27 tux-03 wekan.wekan[24636]: Exception while invoking method '/cards/update' Error: url must be absolute and start with http:// or https://
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object._call (packages/http/httpcall_server.js:35:11)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object.call (packages/meteor.js:258:21)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object.HTTP.post (packages/http/httpcall_common.js:61:20)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Meteor.wrapAsync (server/notifications/outgoing.js:2:8)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at packages/meteor.js:258:21
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at integrations.forEach.integration (server/notifications/outgoing.js:49:24)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Array.forEach (<anonymous>)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at DDPCommon.MethodInvocation.outgoingWebhooks (server/notifications/outgoing.js:48:18)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at packages/check.js:128:16
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at resolve (packages/ddp-server/livedata_server.js:1684:36)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at new Promise (<anonymous>)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:  => awaited here:
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Promise.await (/snap/wekan/150/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Server.apply (packages/ddp-server/livedata_server.js:1635:14)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object.Activities.after.insert (models/activities.js:153:14)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at packages/matb33_collection-hooks.js:382:18
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Array.forEach (<anonymous>)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at after (packages/matb33_collection-hooks.js:381:9)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at ns.Collection.insert (packages/mongo/collection.js:491:37)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at cardState (models/cards.js:322:18)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Object.Cards.after.update (models/cards.js:414:5)
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at packages/matb33_collection-hooks.js:486:20
Mar 28 12:37:27 tux-03 wekan.wekan[24636]:     at Array.forEach (<anonymous>)
`

**Impacted version**: 
services:
  wekan.caddy:   simple, disabled, inactive
  wekan.mongodb: simple, enabled, active
  wekan:         simple, enabled, active
tracking:        stable
installed:       0.78-13-g80941e5 (150) 139MB -
refreshed:       2018-03-21 13:34:16 +0100 CET
channels:
  stable:        0.78-13-g80941e5 (150) 139MB -
  candidate:     0.78-13-g80941e5 (150) 139MB -
  beta:          0.78-13-g80941e5 (150) 139MB -
  edge:          0.78-13-g80941e5 (150) 139MB -

**Comment by rjevnikar** [comment]
@sirup  what version of Node and Meteor do you have installed?
I had a problem with the application crashing and it turned out I had the wrong Node version.
I believe right now the application uses Node 8.9.3 and Meteor 1.6.0.1

**Comment by sirup** [comment]
i just set up a new server and reinstalled everything to get a fresh start. version is now wekan (snap) 0.78.0 node v8.9.3. i don't know how to display the meteor version inside the snap container.

i just imported a db-export from the old database to migrate the data over.
unfortunately the issue still occures. so i think the problem has to be somewhere in the database.

i also figured out something additional: the problem occures only on an "older" board which where migrated over several wekan versions. on "new" boards the issue semms not to be there.

i got on this board also the problem that i can't switch to swimlane view (this failure triggers no error in the log). maybe this is somehow connected.

i also compared the board collection of a working and a not working board  `db.boards.find({"title" : "Boardname"}).pretty()` but couldn't spot any differences in the mongo-entries (besides the display mode).

does anyone have an idea on how to troubleshoot further?

**Comment by xet7** [comment]
@sirup 

I presume you did import your MongoDB database with this command?
```
mongorestore --drop --port 27019
```

**Comment by sirup** [comment]
No. 
I used the command from snap info wekan:

`snap run wekan.database-restore /path/to/backup
`

I now let 2 users delete their old boards and create them completely new. They were not very happy, but at least it seems the server is more stable now.

**Comment by xet7** [comment]
I recommend [using mongodump](https://github.com/wekan/wekan-snap/wiki/Backup-and-restore) for backups.

If you still have problems, add new issue.
