### ISSUE TITLE
create and query cards from command line?

### ISSUE THREAD

**Issue by ahillio** [wekan/wekan#1558]
Hello!  I've been admiring Wekan for a few years, dreaming of the day when I can begin to play.

One of the things I fantasize about for my post-Trello kanban boards is the ability to create cards from the command line.  Additionally it'd be awesome to be able to get card info from the commandline, optimally to be able to perform any/flexible querries.

Is anything like this currently possible?
If not currently possible how much work would be required?... would it simply need to be added to Wekan or would there be work required for Sandstorm or something else outside of Wekan itself?

**Comment by xet7** [comment]
@ahillio 

Yes, you can use for example curl or some programming language with [Wekan REST API](https://github.com/wekan/wekan/wiki/REST-API).

Also see [Wekan Gogs integration](https://github.com/wekan/wekan-gogs) as an example.

REST API works on Standalone Wekan (like Snap version) now. 

I'm currently working to enable [REST API for Sandstorm Wekan](https://github.com/wekan/wekan/issues/1279), having it working ASAP in near future.
