### ISSUE TITLE
Bug: Filter my cards hide checklist items

### ISSUE THREAD

**Issue by biji** [wekan/wekan#1561]
## Issue
**Impacted version**: v0.78

**Server Setup Information**: Docker

**Problem description**:

Pressing "Q" to filter my cards, hide checklist items, clearing filter show the checklist items again

Thanks

**Comment by xet7** [comment]
@biji 

How is this a problem? Please describe with more detail.

Filtering cards does filter by label or username.

Newest Wekan is v0.79.

**Comment by biji** [comment]
I try this on wekan sandstorm demo, opening card with check list items:

![image](https://user-images.githubusercontent.com/665559/38236960-fa82e072-374f-11e8-90e1-554304962c5f.png)

Press Q shortcut to "Filter my cards":

![image](https://user-images.githubusercontent.com/665559/38236981-09d39382-3750-11e8-8dbd-b1645cf3ac1d.png)

Result: check list items gone


Thanks

**Comment by xadagaras** [comment]
We have the same problem. As long as the board is not filtered, checklist items are shown. As soon as cards are beeing filtered, they are hidden.

Regards

**Comment by biji** [comment]
Thanks
