### ISSUE TITLE
Bug with REST-API

### ISSUE THREAD

**Issue by gbarre** [wekan/wekan#1562]
I updated from 0.73 to 0.79 and I no longer have access to the list of items in the checklists. Before I was able to get items from this url : "/api/boards/:boardId/cards/:cardId/checklists/:checklistId"

Would it be possible to put this function back in place please?

**Comment by xet7** [comment]
Yes, I'm looking at why it does not work.

**Comment by xet7** [comment]
Could be related to #1396

**Comment by xet7** [comment]
Works now with latest changes. Will be included to next Wekan release.
