### ISSUE TITLE
Feature Request: Changing the start & due dates it generates message to Outgoing Webhook

### ISSUE THREAD

**Issue by d3dbit** [wekan/wekan#1564]
Hello,
Is it possible to implement a new feature that changing the start & due dates it generates a webhook outgoing and it sends an email?
Thanks.

**Comment by d3dbit** [comment]
Hello,
Have you been able to move forward with this topic?
Thanks for your work.

**Comment by xet7** [comment]
No, nobody is paying for this using my Commercial Support https://wekan.team , and no one else has added comment to this issue that he/she is working on this.

**Comment by xet7** [comment]
I think this issue is just about adding webhook. There are other issues about IFTTT #1160, email, etc. Probably this will be implemented by pull request someone adds, or sometime this year when I happen to need this.

**Comment by xet7** [comment]
Moved to #2567
