### ISSUE TITLE
Checklist not copied when copied a card and Copy Checklist Template to Many Cards

### ISSUE THREAD

**Issue by benoitns** [wekan/wekan#1565]
## Issue
**DO NOT ADD ISSUES ABOUT DOCKER**

* [Docker destroys your data](https://github.com/wekan/wekan-mongodb/issues/9)
* Docker Hub image is broken. Quay image has problems too.
* If you would like for Docker to work, please add fix as pull request to devel branch

**Impacted version**: 
0.79.0
**Server Setup Information**:

* Operating System: Linux
* Deployment Method(snap/sandstorm/mongodb bundle): Docker
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node Version: v8.9.3
* MongoDB Version: 
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files in .zip file)*
When I copy a card (template), checklist is not copied to destination card. thank you to help me
![issue 1](https://user-images.githubusercontent.com/4178572/38297832-ef972b22-37f5-11e8-937f-9cc4cd5e6cb5.png)
![issue 2](https://user-images.githubusercontent.com/4178572/38297833-efc1c102-37f5-11e8-85d6-90edbbd9f8d5.png)

**Comment by crapnicki** [comment]
I can confirm this issue.  Copying a template card to a list isn't copying the checklists.

**Comment by phantom4242** [comment]
Version 0.77 is also affected. And "Copy Checklist Template To Many Cards" feature doesn't work too. These problems might have a common root cause.

**Comment by xet7** [comment]
Yes, there has been changes to Checklist database structure to make it easier to reorder checklists, so not all related issues are fixed yet.

**Comment by erikturk** [comment]
I will look at "Copy Checklist Template To Many Cards"

**Comment by erikturk** [comment]
Thanks for getting to this. I got busy with other stuff.
