### ISSUE TITLE
Switch List/swimlane view only working with admin privileges

### ISSUE THREAD

**Issue by Chartman123** [wekan/wekan#1567]
## Issue

**Server Setup Information**:

* Deployment Method(snap/sandstorm/mongodb bundle): Docker 0.79
* Node Version: v8.9.3

**Problem description**:
When clicking on the List/Swimlanes button as a normal user the view changes and immediately jumps back to the old view. As a admin user the view changes.

So I propose to either hide the button for normal users or to make it possible for them to switch the view.

**Comment by xet7** [comment]
Normal users should be able to switch view independently.

**Comment by Chartman123** [comment]
This is the error message that I get, when I click the button as a normal user:
`update failed: Access denied 1 192ecd8d9a2de65c21237d8cc6ac107756a0523a.js:1:6261`

**Comment by gitzimo** [comment]
Hi! I can reproduce that, though slightly different: My WEKAN account has admin priviledges, but I can only switch swimlane and list view without problems on my own boards. Tested with different OS and browsers (Win7/IE11, Win7/FF59, Win10/IE11, Win10/Chrome). Doesn't have to do with wether the board is private or public, seems to be related to whom created the board. Our deployment is wekan/latest (v79) and mongo:3.2.19 with docker-compose on docker-17.09.1. If you have any hints where I should look (logs?) maybe I can contribute some more info. Thansk in advance! Zimo

**Comment by xet7** [comment]
Yes, there is a bug, but no fix by anybody yet.

**Comment by andresmanelli** [comment]
Created #1588 for this

**Comment by Chartman123** [comment]
@andresmanelli Thanks for changing this :) Works great, except for one little thing: Now you cannot chose the viewing mode for each board separately anymore ;) Would it be possible to store this inside the user model but for every single board?
