### ISSUE TITLE
"500" Error while trying to map users to a Trello board import

### ISSUE THREAD

**Issue by quantazelle** [wekan/wekan#1569]
## When trying to import a board from Trello via the JSON post, I map either one or two users and get the same error "500" at the top in yellow. No other feedback.

**Server Setup Information**:

* Operating System: Windows 10
* Deployment Method(snap/sandstorm/mongodb bundle): Sandstorm

**Problem description**:

![image](https://user-images.githubusercontent.com/13591815/38533212-115e4494-3c2d-11e8-9459-ff1cdbc1266e.png)

**Comment by zebby76** [comment]
Upgrade to latest [v0.88](https://github.com/wekan/wekan/releases/tag/v0.88) version which contain a [fix](https://github.com/wekan/wekan/pull/1611) for Trello import.

**Comment by Samgarr** [comment]
Same issue here with latest version.
```
Wekan Version 3.56.0
Meteor Verison 1.8.2
Node Version 8.16.2
````
docker logs -f wekan-app:
```
Meteor APM: completed instrumenting the app
Exception while invoking method 'importBoard' [object Object]
Exception while invoking method 'importBoard' [object Object]
Exception while invoking method 'importBoard' [object Object]
Exception while invoking method 'importBoard' [object Object]
Exception while invoking method 'importBoard' [object Object]
Exception while invoking method 'importBoard' [object Object]
Exception while invoking method 'importBoard' [object Object]
...
```
If more logs/info needed let me know. I would like to help solve this issue out.

**Comment by xet7** [comment]
@Samgarr 

Did you create all board users to Wekan, before trying to import? It's required.

**Comment by Samgarr** [comment]
Yes, all board users created, with same username in Trello and in Wekan.

**Comment by Samgarr** [comment]
Importing boards created in Wekan back to Wekan also gives me 500 and board is not created.

**Comment by xet7** [comment]
Wekan import/export code [is here](https://github.com/wekan/wekan/tree/master/models) at:
- `wekan/models/wekanCreator.js`
- `wekan/models/import.js`
- `wekan/models/export.js`

I already did take to my todo list too much.

Questions is, can you Wekan community help, and try to make more fixes as pull requests? Or is it only me with those 573 open issues?

**Comment by Samgarr** [comment]
I'm not saying you have to fix this issue. Just trying make usable bug report. 
I already looked into wekan codebase but JS and Meteor is whole new thing for me, little bit overhelming.

**Comment by xet7** [comment]
@Samgarr 

Yes it can be overwhelming. I would maybe help if I would make some Wekan programming course with code examples, explaining how each feature is implemented, etc. But still, there would be much to learn, because Meteor Javascript framework is so different than some PHP/MySQL.

While I do encourage new contributors, I do know not many have the time available to contribute.
Anyway, Wekan is what I do fulltime, so I will fix this sometime anyway, if nobody else does fix this before that.

**Comment by t52lE4MWEcgCx** [comment]
I also try to import a Trello board. I run Wekan in Docker on a Synology. 
I created 4 users (as in Trello) - I did the user mapping, assigning all users. I hit import.
Then the Wekan container crashes. When the container is running again, I get a board that is only partially imported and I see the following message in the protocol:

TypeError: Attachments.insert is not a function
    at models/trelloCreator.js:383:46
    at setName (packages/cfs_file.js:179:17)
    at packages/cfs_file.js:151:13
    at packages/cfs_data-man.js:599:7
    at packages/cfs_data-man.js:533:7
    at runWithEnvironment (packages/meteor.js:1286:24)

I hope that helps to find the problem.

Cheers,
Ralph

**Comment by webenefits** [comment]
Just an information: I get this error again in the current version v4.90. In version 4.87 everything worked without problems. I have now temporarily just restored the old version.

In addition, I want to say briefly that we are really very enthusiastic about Wekan! We started using it about 1 month ago as an alternative to Jira. If Wekan continues to prove itself like this, we will completely switch over and then of course donate something. 

Thank you very much!
Greetings, Alexander

Translated with www.DeepL.com/Translator (free version)

**Comment by xet7** [comment]
@webenefits 

Thanks a lot for you kind words!

[Some have already changed from Jira to Wekan](https://github.com/wekan/wekan/issues/1667#issuecomment-755224854), and some have already donated.

**Comment by jrsupplee** [comment]
@webenefits 

> Just an information: I get this error again in the current version v4.90. In version 4.87 everything worked without problems. I have now temporarily just restored the old version.

Do you mean you get the 500 error or the one described by @t52lE4MWEcgCx?

**Comment by webenefits** [comment]
> @webenefits
> 
> > Just an information: I get this error again in the current version v4.90. In version 4.87 everything worked without problems. I have now temporarily just restored the old version.
> 
> Do you mean you get the 500 error or the one described by @t52lE4MWEcgCx?

I meen the 500 error. We are running Wekan on an Ubuntu VPS as Snap.

**Comment by jrsupplee** [comment]
@webenefits

> I meen the 500 error. We are running Wekan on an Ubuntu VPS as Snap.

Did you test on 4.91?

**Comment by webenefits** [comment]
> Did you test on 4.91?

Yes, just tested it. On version 4.91 the Trello import is working again! :tada: 
Thanks!

**Comment by sanderdatema** [comment]
Could there be a regression? I'm on version `5.17.0` and it happens again.

**Comment by jrsupplee** [comment]
@sanderdatema 

It means your Trello data has no labels defined.  Was it exported from Trello?  Did you edit it?

**Comment by sanderdatema** [comment]
It was imported from Trello indeed, no edits were made. And do you mean 'no labels defined' that there were only colors and no words attached to each label? If so, that was indeed the case. I'll see if I can change that.

I noticed a fixed was implemented. I use Docker and recreated the container (and redownloaded the image) to get the latest version, but the 500 error is still there.

**Comment by jrsupplee** [comment]
> It was imported from Trello indeed, no edits were made. And do you mean 'no labels defined' that there were only colors and no words attached to each label? If so, that was indeed the case. I'll see if I can change that.
> 
> I noticed a fixed was implemented. I use Docker and recreated the container (and redownloaded the image) to get the latest version, but the 500 error is still there.

I mean that the only way to get the error is if there is no `labels` property defined in the root of the Trello JSON.  Or possibly it is not defined as an array.

Should be:

```
{
   ....,
   "labels": [ ... ],
}
```

**Comment by jrsupplee** [comment]
Actually the error was `Cannot read property 'forEach' of undefined` which means `labels` is not defined in your data.

**Comment by jrsupplee** [comment]
> I noticed a fixed was implemented. I use Docker and recreated the container (and redownloaded the image) to get the latest version, but the 500 error is still there.

It included the patch above?  If so send the error.

**Comment by sanderdatema** [comment]
It seems to be fixed indeed, my bad. Somehow the patch wasn't downloaded on my end.
Thanks!

**Comment by vincesynergy** [comment]
Seems to be a problem in the latest version 7.18.  I get error 500 
![image](https://github.com/wekan/wekan/assets/16008397/bb153104-de64-4229-bfd7-215fb2c8b042)

I have recreated the users and mapped the trello users to the wekan users.

If I downgrade to version Wekan 6.09 and retry the import. It works as expected.

Wonder if there is a way to import my trello using 6.09 then upgrade wekan to 7.18 so I can use the latest wekan version with my data.
