### ISSUE TITLE
Card count label is shown in lower case

### ISSUE THREAD

**Issue by Chartman123** [wekan/wekan#1571]
## Issue

**Server Setup Information**:

* Deployment Method(snap/sandstorm/mongodb bundle): Docker 0.79

**Problem description**:
The text label next to the card count is shown in lower case. For some languages (e.g. German) this is wrong.

x karten instead of x Karten

**Comment by xet7** [comment]
Anyone can add and fix translations at Transifex:
https://www.transifex.com/wekan/wekan

**Comment by Chartman123** [comment]
The translation is in upper case...

**Comment by xet7** [comment]
Huh? I'll check at code...

**Comment by Chartman123** [comment]
It's this line here: https://github.com/wekan/wekan/blob/c72792e4ed0e1ff88a1de494e7885238dc6c9881/client/components/lists/listHeader.jade#L20
