### ISSUE TITLE
Restore a backup after updating to a newer version

### ISSUE THREAD

**Issue by schneivo77** [wekan/wekan#1573]
Hi there,

I wanted to update my wekan from version 0.63 to the newest 0.80.
Therefor I created a backup from v0.63 first and then restored it in v0.80.
Once I did that none of my cards showed up in my boards anymore.
To find out the reason I created a test-board with test-cards. This worked without any problems. Then I compared the entries in the "boards" table in mongo db and noticed that the field "view" was missing in the entries from the older version. After I copied the "view" field with its value from the test-board entry to the older entries, the cards showed up again.

So, is there any way to migrate old wekan backups to newer versions without having to edit everything manually?

I'm using the docker version.

**Comment by xet7** [comment]
Maybe something is missing from database schema migrations?
https://github.com/wekan/wekan/blob/devel/server/migrations.js

Here is current boards schema:
https://github.com/wekan/wekan/blob/devel/models/boards.js

You could also try board export to Wekan JSON at old Wekan, and import Wekan JSON at new Wekan, when using Standalone Wekan like Docker or Snap.

**Comment by schneivo77** [comment]
Ok I try that. Where do i have to put these files?

**Comment by xet7** [comment]
Restoring needs to be done with this for Docker version:
```
mongorestore --drop --port 27017
```
And for snap version where mongo is in different port:
```
mongorestore --drop --port 27019
```

**Comment by xet7** [comment]
But, Wekan container needs to be stopped first, otherwise MongoDB contents gets corrupted.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

https://github.com/wekan/wekan-snap/wiki/Backup-and-restore

**Comment by schneivo77** [comment]
OK, thanks! I'll try that and post here if it worked.

**Comment by schneivo77** [comment]
Hi again,

I updated to the latest version (v0.80) but this time, as you advised, I stopped the wekan-app container first and then restored the backup using this command:

``
mongorestore --drop --port 27017 --db wekan /data/dump/wekan/
``

And now everything seems to work fine! :)

So thank you again for your help! :) 👍
