### ISSUE TITLE
Wekan Design: Comment section on card, etc

### ISSUE THREAD

**Issue by TiibCD** [wekan/wekan#1574]
Hi guys!
I have another request! When you have some checked lists with items on a card, the comments in the activity section are hard to notice if you don't scroll down. (see screenshots below)

**Request**
* Could it be possible to have an option to hide the Attachments on cards ? 
* Or could it be possible to show the number of comments beside the "Activity" title ?

Thanks for listening and for the great work

**Server Setup Information**:

* Operating System: **Ubuntu**
* Deployment Method: **VirtualBox appliance**
* Wekan version : **v0.78**
* Node Version: **v8.9.3**

![to do - wekan - mozilla firefox](https://user-images.githubusercontent.com/24451989/38375038-847fd7de-38f5-11e8-915f-ee3f15c9105e.jpg)

![to do - wekan - mozilla firefox_2](https://user-images.githubusercontent.com/24451989/38375046-88886e2c-38f5-11e8-8dd4-2e1346ed5ca4.jpg)

**Comment by edouardpa** [comment]
Hi everyone !

I would have loved it too, if we could hide Attachements when it's empty.

Thanks for your work !

**Comment by d3dbit** [comment]
+1 to @eduardpa 's comment

It could be a nice idea to hide 'Attachements' section when it is empty

**Comment by Jay2k1** [comment]
I would actually prefer to have the comments/activity section in a second pane to the right, so that the card details canvas has two panes, the left one like it is now (minus activity) and then the activity feed to the right of that. this way, you wouldn't have to scroll down for comments (which is super slow for me btw, looks as if there's some JS "smooth scrolling" foo involved).

**Comment by FuXXz** [comment]
The layout is unfortunately a static neck break. In the 21st century, it should be more flexible, fluid, and intuitive.
It could be that easy
With a split layout, which I can adjust individually. With the bar in the middle I can slide flexibly and choose the relationship between comments and content
Wekan should be able to do that
![Anmerkung 2020-04-03 193553](https://user-images.githubusercontent.com/9010594/78389168-9325ad00-75e2-11ea-93df-3a2c9e932609.png)

**Comment by xet7** [comment]
@FuXXz

I tried a little about that. Currently it's not flexible resizeable at middle, and opens on left only for cards at left so would need to be changed to a popup. Here is current In-Progress code as a starting point for someone interested in implementing this. 

[diff.txt](https://github.com/wekan/wekan/files/4432598/diff.txt)

I really appreciate Wekan Community actively participating in Wekan development.

![wekan-wide-card](https://user-images.githubusercontent.com/15545/78461923-c39a4380-76d5-11ea-8144-b6e3fff0ca9f.png)

**Comment by FuXXz** [comment]
This looks very nice
This Change alson with this
https://github.com/wekan/wekan/issues/2986
would give a nice usability

**Comment by xet7** [comment]
Moved to here from #2939

From @victordariovera 

Hi! I think is a good idea implement some changes in UI and look and feel not only to make wekan more "modern" but a little more usable. I think that some tweaks in fonts, spacing and some controls can make Wekan more eye-catching than trello. :)

Some little ideas I have now, quick ideas:

- Improve line and paragraph spacing in activity history, text feels a bit compressed. 
- Control in "hide minicard text label" in activity history view can have better animation. It's a good idea but i feel that can be improved.
- For some reason, the dark grey vertical division lines between cards columns make me feel in old microsoft excel hahaha :D Modern UI search for open spaces, eliminate that lines can help to card gain visual prominence to cards.
- In general, controls and text can be more space to gain "visual air" and looks a little more "modern."
- Sign "+" in card controls looks redundant and add visual complexity, I think can be simplified. 

Can help a mookup?
I Could make one and post it here ;)

From @xet7 

Yes, you can add your mockup here.

**Comment by xet7** [comment]
Spacing will change a little when background image feature is ready https://github.com/wekan/wekan/issues/486#issuecomment-590308450

![wekan-background](https://user-images.githubusercontent.com/15545/75153392-f97dfc80-5713-11ea-9d10-aefa902b582d.png)

**Comment by lauinspace** [comment]
I saw older topic on that point but not sure if it lives still here. 
I use the cards to have a basic exchanges with colleagues thanks to the comments bloc.
But the view is too small not confortable, will it be to have a wider view of card or full screen view ?

**Comment by xet7** [comment]
@lauinspace 

Yes, sometime full screen view will be added, with a toggle of current view/full screen view.

Also background image will be added, someone asked about it and they have meetings to discuss can they fund it, but bureucracy takes time.

In general, upcoming is:
- Everything at Roadmap
- Many bugfixes
- Speed improvements
- Accessibility improvements
- More import/export/sync features

**Comment by lauinspace** [comment]
> @lauinspace
> 
> Yes, sometime full screen view will be added, with a toggle of current view/full screen view.
> 
> Also background image will be added, someone asked about it and they have meetings to discuss can they fund it, but bureucracy takes time.
> 
> In general, upcoming is:
> 
> * Everything at Roadmap
> * Many bugfixes
> * Speed improvements
> * Accessibility improvements
> * More import/export/sync features

Wonderful!
Thanks for your helpful answer
