### ISSUE TITLE
Reuse existing labels

### ISSUE THREAD

**Issue by drieu** [wekan/wekan#1575]
Hi all,

I used Kanban every day at my job and I'm very happy with it .
In my mind, it will be a cool feature to reuse or copy existing labels.
Indeed, at my job, I defined several card and I used always same labels (for example 0%,100%). It is a little annoying to recreate every time same labels.
Thanks for your tool.

**Comment by xet7** [comment]
@drieu 

When you create board with labels, you can export that board like a template board, and import back to Wekan, then you have 2 boards with same labels.

**Comment by lonix1** [comment]
@xet7 That is a nice trick, I didn't think of that!

But if the board already exists, is there a way to copy labels from one board to another? I'm willing to try a once-off mongo command (I'll backup my stuff first). Any tips which collections/whatever I should look in?
