### ISSUE TITLE
docker image cannot run correctly

### ISSUE THREAD

**Issue by Crandy** [wekan/wekan#1581]
i pull the image from https://hub.docker.com/r/wekanteam/wekan/
but i cannot run the image when i use the command "docker run ".
so, can you give the describe for how to run the images?
thanks

**Comment by xet7** [comment]
@Crandy 

Docker Hub is usually broken. Quay works.

Docker run examples:
https://github.com/wekan/wekan/wiki/Docker

Docker-Compose well documented example:
https://github.com/wekan/wekan-mongodb

**Comment by Crandy** [comment]
@xet7 
thank you very much, i ran it correctly, and now i am in trial
