### ISSUE TITLE
Error: roboto-condensed-bold.woff2 does not exist

### ISSUE THREAD

**Issue by apn3a** [wekan/wekan#1582]
**Server Setup Information**:
snap    2.32.3
snapd   2.32.3
series  16
ubuntu  16.04
kernel  4.4.0-87-generic
wekan snap version 0.81  rev 162

**Problem description**:
After snap refresh to version v0.81 the font looks stretched vertically, 
Upon further investigation it appears that no font is being applied due to the following error:
Failed to decode downloaded font: https://wekan.maltco.local/fonts/roboto-condensed-bold.woff2

roboto-condensed-bold.woff2 does not exist in /snap/wekan/162/programs/web.browser/app/font/ however there is roboto-condensed-bold.woff

**Comment by xet7** [comment]
I did not find woff2 font yet.
Using thinner font was request from customer.
But after that I got some pull request (accidentally to wekan) where somebody commented that the font is too thin, and they changed to other font that was used in their company.

So I need feedback, is that new font too thin? Should I go back to original font?

**Comment by apn3a** [comment]
Seems a bit too skinny, need to zoom to read well. For now I reverted to v0.80 in fact.
This is what we see:
![image](https://user-images.githubusercontent.com/4660322/38610701-eea01d50-3d81-11e8-9cd1-4091242330ab.png)

**Comment by xet7** [comment]
Ok, I'll change original font back.

**Comment by Hendrik410** [comment]
Thanks, we too liked the old font better

**Comment by kc187** [comment]
Thanks alot, maybe just make the user decide what font to use, anyway i prefer the old one alot over the newer one

**Comment by lichtamberg** [comment]
Same here, the new font was a bit too thin & too high in relation... But I would love to have something in between - I mean a bit lighter font than the old one.. What about the Roboto Light? https://fonts.google.com/specimen/Roboto

**Comment by xet7** [comment]
@lichtamberg 

Problem is that older people don't see as well as young people. So I prefer not to change to lighter font.

**Comment by lichtamberg** [comment]
Valid point. Maybe we can add a font selector in the settings in the future.. But i think this is really low prio 😄

**Comment by Hendrik410** [comment]
I also think, their is no prior to a setting and would approve the roboto light font

**Comment by therampagerado** [comment]
I think the current font is just fine. It's readable when you zoom in in order to have 5-6 columns visible on cheap screen.

No need to change what's not broken. :)
