### ISSUE TITLE
0.82 and prior: Date format mismatch

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1584]
## Issue

**Server Setup Information**:

* Operating System: Linux
* Deployment Method(snap/sandstorm/mongodb bundle): snap
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 8.9.3.
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- I have Wekan in Bulgarian and the proper format for dates is 12.04.2018 but it appears as 12/04/2018 on some users. When the card is dragged and dropped somewhere the date appears with dots but on reload all cards are reset to /. Do you experience the same issue? Can you suggest a workaround or fix for it?

**Comment by xet7** [comment]
@therampagerado 

Do all users have Bulgarian selected as Wekan language and webbrowser language? So there is no additional languages added in browser settings of those users that have that problem?

**Comment by xet7** [comment]
This depends on browser language settings and Wekan settings. To behave same, all needs to be same.
