### ISSUE TITLE
Sort board by name

### ISSUE THREAD

**Issue by fdegraeve** [wekan/wekan#1586]
# Issue

How I sort the board by name on dashboard homepage ?

**Comment by xet7** [comment]
Hmm, I think that feature is not yet in Wekan.

**Comment by fdegraeve** [comment]
Thanks for the reply. 
I hope it's on roadmap. It's hard to organize the homepage when we have lot of boards.

**Comment by xet7** [comment]
Actually, in progress feature Top Level projects will solve this.

Moved to #641
