### ISSUE TITLE
Minimize board sidebar actually just moves it over

### ISSUE THREAD

**Issue by tlmorgen** [wekan/wekan#1589]
## Issue

**Server Setup Information**:

* Operating System: Windows 10/Chrome 65.0.3325.181
* Deployment Method(snap/sandstorm/mongodb bundle): manual v0.81
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): either apache, nodejs
* Node Version: v8.11.1
* MongoDB Version: v3.4.10
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://wekan/

**Problem description**:
If you click the minimize button (right-pointing arrow anchor) of the right-hand-side info bar within a board (which contains users and audit trail), the panel will slide to the right but will in doing so create a bottom scrollbar on the page.  The panel can still be seen if one scrolls right.

**Comment by dagomar** [comment]
I've the same problem. My setup is based on docker.

I used firefox's stylus extension to fix it with:
```
.board-wrapper {
    overflow-x:hidden;
}
```

**Comment by dagomar** [comment]
Well, that was quick @xet7 !
