### ISSUE TITLE
can't import wekan from wekan

### ISSUE THREAD

**Issue by victort** [wekan/wekan#1590]
## Issue

**Server Setup Information**:

* Operating System:
Debian stretch/buster
* Deployment Method(snap/sandstorm/mongodb bundle):
docker wekan/wekan:latest
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
nginx reverse proxy
* Node Version:
whatever's in the container
* MongoDB Version:
image: mongo:3.2.14
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):
http://internal.lan:81

**Problem description**:
- can export from one docker instance  
- cannot import to another docker instance 
- *explain how to reproduce*
  - `Export Board` from the `Board Menu`
  - `Add board` in alternate instance (all versions the same)
  - `import board`, name it (or don't, same outcome)
  - paste JSON payload
  - select user to map (same user) or don't.
  - experience error

the exported board is: `140K    wekan-export-board-o8hDTCAMkbJTZbag6.json`

error: 
```
Your JSON data does not include the proper information in the correct format
Map Memebers
Your imported board has some members. Please map the members you want to import to Wekan users```

data begins: `{"_format":"wekan-board-1.0.0",`

**Comment by victort** [comment]
the good news is, i fixed my migration problem. (oops, `docker-compose.yml` was pointed at wrong directory for my db backup. fixed that, but) Still got the export/import problem, but my care-o-meter now registers a lot less now. kthx

**Comment by Hendrik410** [comment]
I have the same problem, we managed to isolate the problem:
On our server it only occurs, when the board contains a checklist somewhere.
Other than that it works like its supposed to.

@victort Do you have checklist(s) in the board you tried to export/import?

**Comment by xet7** [comment]
Please wait for next release of Wekan that has checklists fixes.

Wekan only supports MongoDB 3.2.x. There is problems with attachments with 3.4.x.

**Comment by victort** [comment]
For posterity, i do have many checklists on my board.

**Comment by dopaminereceptionist** [comment]
I just tried 0.89 and this still seems to be broken.

**Comment by xet7** [comment]
@dopaminereceptionist 

Please see #1602 if you mean that, or add a new issue.
