### ISSUE TITLE
Cards with long description/checklists, get truncated and the bottom links invisible

### ISSUE THREAD

**Issue by jbmorgado** [wekan/wekan#1593]
## Issue

**Server Setup Information**:

* Operating System: Docker

**Problem description**:
- *describe the problem and its symptoms*:  If you create too much content inside a card, namely a long checklists or many checklists the bottom functionality (namely, create new checklist, add to checklist) get's truncated and is invisible. This happens both in Firefox and in Chrome
- *explain how to reproduce*: Create a card, create checklist, populate checklist with several items (about 10)

**Comment by zombah** [comment]
Try fix from #1596 for me it helped with same as your symptoms

**Comment by xet7** [comment]
I'm unable to duplicate this.
