### ISSUE TITLE
if I add a user to a board, clicking on any card in the board returns a blank page

### ISSUE THREAD

**Issue by victort** [wekan/wekan#1595]
## Issue
if I add a user to a board, clicking on any card in the board returns a blank page
Even if I remove the user from the board (not a member, admin, not involved with the board at all), clicking any card in the board returns a blank page.

**Server Setup Information**:

* Operating System:
Debian stretch/buster
* Deployment Method(snap/sandstorm/mongodb bundle):
Docker (wekanteam/wekan:latest)
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
nginx 
* Node Version:
8.11.1
* MongoDB Version:
mongo:3.2.14
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):
ROOT_URL=http://board.mydomain.com
**Problem description**:
add a board
add some cards
add some details to the cards
new user self registers
add new user to board
nobody can open cards anymore. clicking on a card in the board returns a blank page.

**Comment by victort** [comment]
in addition, if i have another board the user has not been added to, i can open cards just fine, change/add/manipulate data in cards, close card. 
if I return to the newly shared board, card open to a blank page. even if i remove the member from the board, and only I have access again, cards i click on return a blank page

**Comment by victort** [comment]
it's somehow related to the nginx proxy.
if i hit the site directly, it works.

**Comment by xet7** [comment]
Websocket config is required in nginx:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by victort** [comment]
followed that page's advice, new config looks like:
```
# this section is needed to proxy web-socket connections
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
        listen  80;
        server_name board.mydomain.com;
        rewrite ^  https://$host$request_uri? permanent;
}

server {
        listen 443 ssl http2;
        server_name board.mydomain.com;

        ssl_certificate         /etc/ssl/board.mydomain.com/cert.pem;
        ssl_certificate_key     /etc/ssl/board.mydomain.com/key.pem;

        ssl on;
        ssl_session_cache builtin:1000 shared:SSL:10m;

        location / {
                #proxy_pass http://internal-board;
                proxy_pass http://board.mydomain:81;
                proxy_read_timeout 90;
                proxy_http_version      1.1;
                proxy_set_header        Upgrade $http_upgrade;
                proxy_set_header        Connection $connection_upgrade;
        #       proxy_set_header        X-Real-IP $remote_addr;
        #       proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header        X-Forwarded-For $remote_addr;
        #       proxy_set_header        X-Forwarded-Proto $scheme;
        }
}
```
generally the nginx proxy log doesn't scroll until I click on a card, then it appears to renegotiate(?), i briefly get the ` Wekan is loading, please wait. Refreshing the page will cause data loss. If Wekan does not load, please check that Wekan server has not stopped.` banner, and then it goes blank. 
but only on the shared board?

the logs on the proxy go something like:
```10.10.37.1 - - [19/Apr/2018:04:05:32 -0700] "GET /sockjs/361/xhix3vs9/websocket HTTP/1.1" 101 9771 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.10.37.1 - - [19/Apr/2018:04:05:32 -0700] "GET /sockjs/info?cb=b4j1r76tsw HTTP/2.0" 200 97 "https://board.mydomain.com/b/dbsvdz8GTspLGtWKx/test-board" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.10.37.1 - - [19/Apr/2018:04:05:32 -0700] "GET /b/dbsvdz8GTspLGtWKx/test-board/fMQ4cmzLqyeaGgALC HTTP/2.0" 200 1368 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.10.37.1 - - [19/Apr/2018:04:05:32 -0700] "GET /sockjs/836/_pzs73db/websocket HTTP/1.1" 101 35 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.10.37.1 - - [19/Apr/2018:04:05:33 -0700] "GET /cfs/servertime HTTP/2.0" 200 33 "https://board.mydomain.com/b/dbsvdz8GTspLGtWKx/test-board/fMQ4cmzLqyeaGgALC" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.10.37.1 - - [19/Apr/2018:04:05:33 -0700] "GET /sockjs/info?cb=vx1__b2rt6 HTTP/2.0" 200 97 "https://board.mydomain.com/b/dbsvdz8GTspLGtWKx/test-board/fMQ4cmzLqyeaGgALC" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
10.10.37.1 - - [19/Apr/2018:04:05:33 -0700] "GET /sockjs/info?cb=p2obzp39z1 HTTP/2.0" 200 97 "https://board.mydomain.com/b/dbsvdz8GTspLGtWKx/test-board/fMQ4cmzLqyeaGgALC" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
```
I can see where it's `101`ing the websocket connection, but it still comes up blank.

I get the loading banner on the board i'm not sharing, but the card eventually loads,

**Comment by xet7** [comment]
You need to proxy to localhost in nginx config, so nginx config needs to be exactly `http://127.0.0.1:3001` and `sudo snap set wekan port='3001'`

**Comment by victort** [comment]
Well, the proxy is on a different machine than the containers running Wekan. So, outside of using something like `stunnel`, I won't be able to use `localhost` in my config. =(

**Comment by victort** [comment]
Appears I'm experiencing the same thing as #1596.

**Comment by xet7** [comment]
Moved to #1596
