### ISSUE TITLE
Cannot open card of a shared board (since v0.81) when using Nginx in front of Wekan

### ISSUE THREAD

**Issue by m1d1** [wekan/wekan#1596]
## Cannot open card of a shared board

**Docker environment**:

* Host OS: Ubuntu 16.04.4 LTS 
* jwilder/nginx_proxy
* wekanteam/wekan:v0.81 (- v0.86)
* node version 8.9.3
* mongo:3.2.18 image

**Problem description**:
- This issue popped up since v0.81 and persists for v0.82, v0.83, v0.85, v0.86.
- Only cards can be opened of boards which are **not** shared.
- Opening a shared board (two users) neither of them invitee/creator can open cards (grey blank page after click).
- Rolling back to v0.80 everything works again. 

**explain how to reproduce**
-  Upgrade to v0.85 or v0.86. Create a board. Add a card. Share the board. Try to open the card.

**Comment by xet7** [comment]
Docker Hub images of wekanteam/wekan are usually broken, as is said at releases page:
https://github.com/wekan/wekan/releases/

If you use Docker, you should use Quay Docker image.

Nginx needs to have websocket etc settings configured properly:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

You need to have ROOT_URL setting configured to your real Nginx wekan URL set correctly, so that card does open.

For me, using Snap version works correctly with shared boards, I can open cards, so I am unable to reproduce this.
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
Please try the following:
1) Stop wekan-app container, and backup mongodb container:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

2) docker-compose stop your Wekan Docker version

3) Install snap:
https://github.com/wekan/wekan-snap/wiki/Install

4) Ensure that wekan.mongodb is running with `sudo snap services`. If it's not running, reinstall Wekan with `sudo snap remove wekan && sudo snap install wekan`

5) Stop Wekan container with `sudo snap stop wekan.wekan`, as described at:
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore

6) Restore data with `mongorestore --drop --port 27019`

7) Start wekan with `sudo snap start wekan.wekan`

8) Set root-url to your nginx address: `sudo snap set wekan root-url='https://example.com/wekan'`

9) Set port to your port where you have nginx proxy to: `sudo snap set wekan port='3001'` , etc settings mentioned at https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

10) Try again, does it work now.

**Comment by m1d1** [comment]
Thanks for your help.
Since I need sticking to pure docker - I've been trying the suggested "Quay Docker images" v0.80 - v0.85. 

Still the same result: v0.80 works fine, rest has the same issue, as described.

I've noticed that the `Dockerfile` changed using a newer `NODE_VERSION` and some newer modules like fiber etc.

Could you make the file [https://releases.wekan.team/node-v8.9.3-linux-x64.tar.gz](https://releases.wekan.team/node-v8.9.3-linux-x64.tar.gz) available for me to test if the newer nodejs 8.11. is causing the trouble?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/v0.83/Dockerfile#L37

**Comment by xet7** [comment]
I presume this is some database migration issue like #1576. Node version should not affect any functionality. You could look is there something missing in MongoDB database, with a tool like Robo 3T. Some previous issues were because somebody did delete some data on MongoDB directly, with some script, etc.

You can also try to export all boards as Wekan JSON files, and import them to new Wekan v0.85 Docker install.

**Comment by victort** [comment]
For my part, I can say I have not done any manual manipluation on my part of mongodb.

From the behavior of clicking-on-a-card, it appears to be a websocket renegotiation thing? Like, the proxy doesn't appear to register any traffic if I go between boards and/or add a card, but as soon as I click. Bam, 200, 200, 101, etc.. 

Maybe this is expected behavior? Maybe I'm wildly off about how it functions, this is entirely possible as I am 0 knowledgeable about node.

US$0.02++

**Comment by xet7** [comment]
I don't know could this be related to adding [browser-policy etc in v0.80](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v080-2018-04-04-wekan-release)

You could try friend docker image that currently does not have those:
https://github.com/wekan/wekan-mongodb/blob/master/friend/docker-compose.yml#L61
image: quay.io/wekan/wekan:friend

**Comment by hirowhite** [comment]
Confirmed. 85 version of VM has same issue as all other versions I have tested. 83 84 85, standalone, snap, vm. if you add a a second user to a board, then the card url for a card will only bring up a grey screen. errors:

https://pastebin.com/VSMWpzKE

**Comment by victort** [comment]
just verified, same issue with `quay.io/wekan/wekan:friend` image.

**Comment by xet7** [comment]
This does not happen when using caddy that's integrated to Wekan Snap. So it's just Nginx config issue.

**Comment by xet7** [comment]
Usually problem in Nginx config is, that there are some other settings that prevent Wekan working, for example forbidden file extensions, etc. Usually Wekan in separate wekan-website.conf file and it's own subdomain makes Nginx work. That Nginx config should be like this:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

But I have had server where was existing Drupal website, and I tried to add Wekan to work on that same domain sub-url like https://example.com/wekan , and some Drupal PHP settings did prevent it from working.

I have also used Nginx at work, and tried to configure it to not show some random links on Drupal website, not finding good documentation about that.

I have also used Certbot to renew Nginx Let's Encrypt SSL certs, and having to write various scripts to make it really work. Sometimes Certbot has messed up Nginx configs, or there has been need to build newest version directly from Certbot GitHub repo, or add additional commandline options.

I also did help recently someone to run Wekan behind Apache, it did work fine.

Caddy https://caddyserver.com renews Let's Encrypt SSL certs automatically.

I would prefer that Wekan works behind any webserver.

I really welcome all Nginx gurus to help debug this Nginx config issue.

**Comment by therampagerado** [comment]
I have the same issue with snap - the copied card link does not open when shared with another member of the board.

**Comment by uglimugli** [comment]
Same problem started after .81 release. Did check nginx settings for wekan subdomain and looks pretty much exactly as they are on the example. Some minor edits with fever accepted cyphers etc.

As said before, until i add more users to tables everything works just fine.

**Comment by m1d1** [comment]
Bug persists in v0.86.

**Comment by m1d1** [comment]
@victort post inspired me to recheck the docker configurations. `ROOT_URL` in our `docker-compose.yml` was misconfigured with http:// instead of http**s**:// . Everything works fine now at first sight. (we're using the nginx-proxy image by [jwilder]([url](https://github.com/jwilder/nginx-proxy)).

**Comment by markwooff** [comment]
Thanks @m1d1 - looks like that small change to the `docker-compose.yml` file did the trick. Appreciate the info as this was an irritating issue!

**Comment by victort** [comment]
confirmed, same change working for me too.

Even though the container isn't using `https`, setting `ROOT_URL` to `https` anyway does seem to do the trick. It's even stopped the behavior that makes it appear to renegotiate whenever a card is clicke.

**Comment by txelu** [comment]
In my case, using the snap install, it doesn't work. When I changed to use https (` sudo snap set wekan root-url=https://10.1.5.211:5000`) the cards couldn't even being opened from the board itself, so I had to revert the chance.

**Comment by txelu** [comment]
My case would be the 2: only wekan, no SSL, internal, caddy not enabled and using port 5000, and the settings in our server matches those you say:
```
sudo snap get wekan
Key        Value
mail-from  wekan-admin@usupport01.com
mail-url   smtp://10.1.5.211:25
port       5000
root-url   http://10.1.5.211:5000
```
And I can also say that this configuration was working some versions ago, until it started to fail after one upgrade (scheduled). To reproduce it just install the wekan's snap, create a board, share it with another user (if the board is private it works) and create a card on it. The link of that card shouldn't work.

**Comment by uglimugli** [comment]
that was it. now it works flawlessly. Thank you @xet7

**Comment by txelu** [comment]
Still having the same effect with v0.92 of Wekan. The strange thing is that links to dashboards work fine, but not to card. For instance:
 * http://10.1.5.211:5000/b/4hAkFK3ncv4kAd8Fg/support opens the board correctly, but
 * http://10.1.5.211:5000/b/4hAkFK3ncv4kAd8Fg/support/2smKKoZfeQQEanFGs, which is a card in that board, causes the screen to remain empty.

**Comment by medienverbinder** [comment]
Same issue here. Links to the cards (sent by the system) no longer works. Also the links from cards, I copy to the clipboard, don't work anymore.

In the browser console I get the message "There is no route for the path:".

(Wekan-Snap Version 0.94.0)

**Comment by txelu** [comment]
I can confirm that the error is still present in v0.98.

**Comment by chwid** [comment]
Still the same in v1.0

**Comment by QWERTYman2020** [comment]
virtual appliance version v1.01
edit page is unavailable.
normal board url and actions work just fine.

**Comment by lgroig** [comment]
I noticed that if I try to visit a page(card) while not logged in, and logs in when prompted, it works once. running 1.01.0

**Comment by lw-like** [comment]
In v1.02 still the same.

**Comment by lime918** [comment]
i have the same issue running 1.04 with snap, and scenario 1 from @xet7's suggestions (only wekan, no SSL, internal lan, caddy not enabled), using chrome.

**Comment by mxmehl** [comment]
Same here with the Docker quay image. I use a nginx reverse proxy with SSL in front of it but it supports the websocket headers.

**Comment by garyritchie** [comment]
I no longer see this issue with wekan 1.33; using Traefik for reverse proxy (with SSL).

If not not previously authenticated I get a "Board not found..." page. After logging in the card comes right up.

**Comment by zebby76** [comment]
@xet7 The problem does not arise when there is only one member defined on the board. Add a member to the board, and the direct links to the cards will no longer work and a blank page is displayed in the browser and that with or without NGinx in front of NodeJS. Can you re-open the issue please ?

**Comment by xet7** [comment]
@zebby76 

Have you tested this with newest Wekan ?

**Comment by zebby76** [comment]
@xet7 yes.  I tested version 1.33.  With and without NGinx in front of Wekan.  Thanks :-)

**Comment by mxmehl** [comment]
For new boards I can confirm that with v1.36 it does work. But how can we fix older boards? In my organisation we heavily rely on Wekan for some long-running projects and we cannot just switch to a new board...

**Comment by xet7** [comment]
@mxmehl 

For fixing old boards, it can help to export and import board.

I do have example database where one board did not load, and export/import did help. I will look at differences between those boards how I could fix all boards automatically for everyone.

**Comment by mxmehl** [comment]
@xet7 Many thanks in advance!

Unfortunately export/import isn't really an option. The board I'm most concerned about is huge with a lot of attachments, and the export fails (probably due to timeouts) (using the quay Docker image). If you found a way to fix existing boards I would be so happy!

**Comment by hl3fx** [comment]
we just started using, but have quickly adopted.  This issue persists on v 1.39.  Multiple users on a board = card links are grey and blank. 
![image](https://user-images.githubusercontent.com/6783603/45063304-2a6efb00-b062-11e8-8b25-d4f8d23f7c23.png)

**Comment by mxmehl** [comment]
Did you find any solution to this so far? In huge boards it's really hard to point coworkers to the correct card if we cannot use direct links...

**Comment by xet7** [comment]
@mxmehl 

Sorry, I have not had time yet to look at how to fix old boards. Direct links works on new boards on Caddy webserver for me.

**Comment by cakekol** [comment]
It seems there's a bug for WeKan behind nginx..  when we want to add details on the card, wekan put value from root-url and didn't use relative path for accessing card details. I use WeKan version 2.60 on Centos 7 using snap.  Everything is normal unless access card to add details. Please help.
