### ISSUE TITLE
Reordering lanes issues in v0.85

### ISSUE THREAD

**Issue by benjaminpech** [wekan/wekan#1599]
**Docker environment:**
- Host OS: Linux RH7
- Node Version: 8.9.3
- quay.io/wekan/wekan: latest (v0.85)
- MongoDB Version: 3.2.19

**Problem description:**
- Issue on swimlanes reordering 
- Possible to move down a lane but not to move up
- It immediately returns to its original place

**Comment by pblvsk** [comment]
Moving swimlanes works fine to me in both up and down direction.

**Comment by Chartman123** [comment]
Working fine here in latest Wekan docker release 1.01. Think we can close this issue?
