### ISSUE TITLE
Client-side page loads freeze-up browsers

### ISSUE THREAD

**Issue by pcactr** [wekan/wekan#1600]
## Issue

**Server Setup Information**:

* Operating System: RHEL 7
* Deployment Method(snap/sandstorm/mongodb bundle): pre-compiled meteor tarball
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): direct nodejs
* Node Version: 8.9.4-2.el7.x86_64
* MongoDB Version: mongodb32-2.2-9.el7.x86_64
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): not including

**Problem description**:
Wekan is taking a very long time to load on the client-side and then locks up periodically.  20+ seconds on page load with only 10 users and ~300 cards.  Full database export is only 4.1MB.  The server load never exceeds 0.20 (it's WAY overkill for Wekan, 12 cores, 24GB RAM, node and mongodb on SSDs) and is on a gigabit LAN (no remote access to Wekan).
![wekan-load](https://user-images.githubusercontent.com/11899921/39053160-2bdd2360-447c-11e8-8ff8-b50fca88abd1.png)

Firefox will continually display "this page is slow" and Chrome does periodically.  At times, the browser just freezes up for 1-10 seconds.  One way to definitely reproduce it is to change the title of a label, which basically sends it back into the "initial load" slowness (20+ seconds).

The attachment is from Chromium dev tools showing the really long page load.

**Comment by xet7** [comment]
@pcactr 

- Increase ulimit for Wekan
- use Fibers fixed node binary or tar.gz package from https://releases.wekan.team , see Wekan GitHub repo changelog and commits in Dockerfile and snapcraft.yaml and wekan/server/authentication.js for Node 100% CPU usage fixes

**Comment by pcactr** [comment]
Thanks for the quick response.

All of the CPU usage is client-side.  I've never seen the load over 0.20 on the server (which has been due to AIDE, not nodejs or mongo).  Nonetheless, I will increase the nodejs ulimit to see if it helps at all.  I am also stepping up from 0.80 to 0.85 to see if anything is repaired.

We are still on Firefox ESR -- it's a lot slower in Firefox vs. Chrome.

**Comment by pcactr** [comment]
Firefox took 100 seconds longer than Chrome on the same machine.
![firefox-devtools](https://user-images.githubusercontent.com/11899921/39095702-bc4de672-4612-11e8-943b-058e445ed3d9.png)

Firefox ESR 52.7.3

**Comment by xet7** [comment]
That slowness could be also related to amount of Javascript in current Meteor.js framework, it will be faster when I figure out how to upgrade all Wekan dependencies so that upgrading to newer version of Meteor.js is possible. There is less Javascript code and more optimizations in newer version.

Some upcoming bugfixes to Meteor could also improve performance.

**Comment by pcactr** [comment]
Thanks for the responses, xet7.

I feel like there is something wrong, and perhaps it is with Meteor and not Wekan.  Prior to submission of this issue, I saw reports of issues with Wekan with hundreds of users and 5000+ cards, but those issues are server-side, not client-side.

I can sanitize data and export if it would help.

**Comment by hmeunier95** [comment]
I have the same issue with one board (about 120 cards). In my case, it is slow with Edge, Firefox and Chrome. No problem detected on the server side.

**Comment by pcactr** [comment]
This is beginning to hinder productivity for us.  Is there a way to reduce polling intervals in meteor?  We can live with a few second delay between cards showing the most updated information if it means the page is responsive.

**Comment by xet7** [comment]
Maybe. You can Google search how to reduce polling interval in Meteor, read some Wekan code enough to understand where to add fix, and submit pull request to devel branch.

Wekan already has code to stop polling when browser tab is not active, and start polling when tab is activated again.

**Comment by pcactr** [comment]
I am not a webdev, but I am effectively claiming this issue to work on/diagnose.  If someone else wishes to take a stab at this, the help would be appreciated.

**Comment by xet7** [comment]
Yes, you are welcome to look at it, like anyone else. Required skills are just reading English (or translating with Google Translate etc), and making google searches, and following step-by-step instructions, trying does it work. Having someone with time to do that is all that is required to fix some bug or add some feature.

**Comment by d3dbit** [comment]
Hello all,
I have the same issue with one board with a lot of cards and with around 5-10 users. It is slow with Chrome and Firefox. The issue is in the client side, not in the server side.
Workaround: if I filter by my own cards, then the performance becomes OK.

**Comment by xet7** [comment]
Please test newest Wekan v1.39. There has been speedups in Wekan v1.37 and v1.38. CPU usage also seems to be lower.
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md

**Comment by xet7** [comment]
At #1672 there was some discussion about serverside resource usage. But from this issue it seems that once there is enough CPU resources at server, serverside is not the problem.

Problem seems to be Wekan boards that have a lot of cards.

Here above is mention about polling interval of meteor. Here is one comment about that:
https://github.com/meteor/meteor/issues/9796#issuecomment-411373831 :

> smeijer commented 24 days ago
> Just wanted to let know that I haven't experienced this issue anymore since I've replaced a lot of `meteor publications` with `apollo/graphql requests`.
>
> The reactivity is thereby lost, but in my case a 30sec poll is also fine. On the places that I do require reactivity, I only publish a single timestamp. This timestamp is passed through to apollo, which triggers a refetch when the timestamp is changed.
> 
> The [discussion here](https://forums.meteor.com/t/implementing-livedocument-as-an-alternative-to-livequery-discussion/40152) has also been helpful to improve performance here and there.

So I'm thinking, is `apollo/graphql` the right way to go.

**Comment by xet7** [comment]
In general, it would be good to know what is the correct part to optimize, to it have any effect.

**Comment by xet7** [comment]
It seems apollo is here https://github.com/cult-of-coders/apollo

**Comment by ja6** [comment]
I experience a slightly different browser freeze issue:
I use Wekan 1.85 installed via snap on Ubuntu 18.04. My browsers (Firefox or Chrome) freezes on load of a specific board and takes 100% CPU. It's not just slow, it doesn't load at all; I've been waiting for several minutes. The affected board is actually quite empty, as I just created it and added a few cards (<10) to it. I believe the problem started, when it tried assigning one card as a subcard of another. Now the affected board is unusable, and I can't even remove it.

**Comment by xet7** [comment]
Does anyone have this problem anymore with newest Wekan from master branch docker-compose.yml ?

**Comment by xet7** [comment]
Anyway, if this still happens, please comment or reopen issue.
