### ISSUE TITLE
Welcome board is not translated

### ISSUE THREAD

**Issue by JavGuerra** [wekan/wekan#1601]
## Issue

**Server Setup Information**:

* Operating System: Linux Mint
* Deployment Method(snap/sandstorm/mongodb bundle): snap v.0.82 and above
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://localhost:3001/wekan

**Problem description**:

In the Wekan Snap package, the 'Welcome Board' name and the 'Basics' and 'Advanced' lists names are not translated to the language of my OS (Spanish) from English.

The text of Date and Time and his format are in English too.

Can I configure something to solve it?

**Comment by xet7** [comment]
Those texts have not been made translateable yet.
