### ISSUE TITLE
When export and import Wekan board in Standalone Wekan, lists are imported to wrong order.

### ISSUE THREAD

**Issue by KingBain** [wekan/wekan#1602]
## Issue

**Server Setup Information**:

* Operating System:
I dont run the server so I dont know, but I was told its running v0.86

**Problem description**:
If I create a new board, create a bunch of lists and then export and reimport the board into the same wekan instance.  I will lose my column/list order and be no longer be able to move the lists around manually(reorder) 

![ss](https://user-images.githubusercontent.com/367922/39071250-58334704-44b4-11e8-81c6-c34abb6962ee.png)

Steps to recreate problem:

1. Create a New Board 
2. Create 3 new lists, named test1 test2 and test3  
3. Export the board
4. Import the board back into the same wekan instance
5. List order is now wrong and I cant correct it.

**Comment by zebby76** [comment]
@xet7 

I can't reproduce the problem!?! The test scenario returns the expected results without sorting problems in my environment.

**Comment by xet7** [comment]
@zebby76 

[wekan-export-import-fix-test.json.zip](https://github.com/wekan/wekan/files/1958959/wekan-export-import-fix-test.json.zip)

Before exporting, it looks like this:
![import-export-original](https://user-images.githubusercontent.com/15545/39408938-e12b73b8-4be6-11e8-9dff-a252badef87f.png)

After importing, it looks like this, and I can not drag lists:
![import-export-imported](https://user-images.githubusercontent.com/15545/39408951-ffa50552-4be6-11e8-9612-aabf45fde736.png)

This is on latest Wekan v0.89 Snap I released today:
![wekan-0 89](https://user-images.githubusercontent.com/15545/39408989-855eccd2-4be7-11e8-92f4-f2d5f2df011b.png)

**Comment by zebby76** [comment]
@xet7 

see this pull https://github.com/wekan/wekan/pull/1617 ;-)

**Comment by xet7** [comment]
@zebby76 

Thanks! That pull request makes imported board sortable.

Although when I export and import that Wekan board, lists are imported to wrong order.

**Comment by zebby76** [comment]
@xet7 

I think this is caused by import of the Wekan board.  When a list is imported the 'sort' property is applied to the list, whether it is archived or not.  I don't think the 'sort' property should be applied to archived lists.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
