### ISSUE TITLE
Content not showing in public board when not logged in at Snap and Docker

### ISSUE THREAD

**Issue by luxas0072** [wekan/wekan#1603]
## Issue

**Server Setup Information**:

* Operating System: ubuntu 16.04.4
* Deployment Method(snap/sandstorm/mongodb bundle): docker+ mongodb
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache2
* Node Version: lastest
* MongoDB Version: lastest
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://192.168.1.27:3000

**Problem description**:
-When i try to add a list on my wekan server (https://gyazo.com/c6643af84027ab07cb77c51a227427a3) it saves up but when i disconnect and go to the url again it doesn't show anything (https://gyazo.com/568d4bdd40d31317cff6bb21731b88c6) and the list is public (https://gyazo.com/1744fdac423eaf85cbff3a0757e3c424)
- i did the tutorial here : https://github.com/wekan/wekan-mongodb the only thing i changed was the port of my wekan server to 3000 because port 80 was already used by my pisignage server
-Here the configuration: https://pastebin.com/t7BHu4hz i think it's a problem of permission
Thank you

**Comment by pblvsk** [comment]
You mentioned you're using Apache2 as frontend here, could you post it's config too?

**Comment by luxas0072** [comment]
My apache 2 configuration thanks for your reply
the configuration file of /etc/apache2/sites-available/000-default: 
https://gyazo.com/4f90baa4ba61b14270ea1e1f1366749b
Should i set my apache server port to 3000 as well?

**Comment by pblvsk** [comment]
Is that the only virtual host? If so, it only serves content of whatever you have running on port 3000

```
    ports:
      - 3000:80
```

This means port 3000 on host will be redirected to port 80 in the container. If you want Apache you need to direct it to this specific port.

https://gyazo.com/568d4bdd40d31317cff6bb21731b88c6 - this image shows you're not logged in, does the content show when you do log in?

**Comment by luxas0072** [comment]
The problem with my installation is that i everything works when i'm a super admin as you can see on this picture: https://gyazo.com/c6643af84027ab07cb77c51a227427a3
BUT when i'm not authentified i don't see any pages even the public which a huge problem because i'll have an architecture with tons of raspberry with a special OS and none user interface
If there is an url with the ID and the password that redirect directly into my list or a whitelist this could solve my problem as well.
My goal is being able to edit lists as a administrator and see those lists publicly with only an url

**Comment by pblvsk** [comment]
@luxas0072 OK I see what do you mean now, when board is public and you're not logged in there's no content on the board except for Activities. Your Apache config as it seems wrong it does not affect occurrence of this isse.

I am seeing exactly the same thing and it does not seem right to me. Plus Swimlane/List switch button shows null (as on @luxas0072 screenshots.

**Comment by luxas0072** [comment]
yes exactly you got it! Now i think it's permission issues probably in the server because i've set my list in public

**Comment by luxas0072** [comment]
Oh sorry i should have been more accurate with my title

**Comment by luxas0072** [comment]
https://gyazo.com/4c81ab56384a98beaa037cc3e9bd7a9e
In case you need the configuration of my wekan server

**Comment by pblvsk** [comment]
Checked Snap version, same behavior as in Docker.

**Comment by luxas0072** [comment]
You mean all docker installation has this problem?

**Comment by pblvsk** [comment]
I mean if it's a bug it occurring everywhere. My Docker has same issue and I also checked Snap, same there.

**Comment by luxas0072** [comment]
Oh then...
There is a way to authenficate directly by putting the username/password in the url so i get directly into the list.
Or an whitelist so when i log in with an IP adresse i'm directly logged in
Or permission issues with my server?

**Comment by pblvsk** [comment]
I think it's a No for all 3 questions. Let's wait for developers to reply.

**Comment by luxas0072** [comment]
Thanks for your help anyway! You've help a lot! :)

**Comment by DrCuriosity** [comment]
I'm getting this problem also. Console is reporting the following (certain info {REDACTED}):

There is no route for the path: /b/{HASH}/{BOARD-NAME}
window.console.error @ VM158:37
dc4930405666392908d1b12a5b5134065e9311e4.js?meteor_js_resource=true:1 Exception in template helper: TypeError: Cannot read property 'profile' of null
    at n.isViewSwimlanes (http://{IP}:5000/dc4930405666392908d1b12a5b5134065e9311e4.js?meteor_js_resource=true:295:50339)
[...]
dc4930405666392908d1b12a5b5134065e9311e4.js?meteor_js_resource=true:1 Exception in template helper: TypeError: Cannot read property 'profile' of null
    at n.isViewLists (...)

The "board view" button also has the label "null".

I'm guessing that it means that some part of the swim lane interface is trying to refer to information a user profile, crashing out when it is not present for anonymous users, and taking the rest of the taskboard with it?

**Comment by ocdtrekkie** [comment]
@DrCuriosity That's more or less the beef, yes. Can you confirm your Wekan version?

**Comment by DrCuriosity** [comment]
@ocdtrekkie : Currently running Wekan 0.86.0 with Node 8.11.1, dockerised on an Ubuntu Xenial x64 host.

**Comment by xet7** [comment]
Moved to #1623
