### ISSUE TITLE
Missing Feature / Bug: Opening Cards in Swimlane View

### ISSUE THREAD

**Issue by Gobliins** [wekan/wekan#1606]
When opening a card in the Lists view the card details is popping up correctly cardDetails are focused and aligned correctly.

When opening a card in the Swimlane view, two problems occur:

1. The cardDetail section only moves the current list blocks inside a swimlane (would be cool if it moves all list sections so their vertical alignment is not broken)

2. The cardDetail section can pop out ouf the screen so scrolling is necessary.

Is there something planned on this issue?

**Comment by xet7** [comment]
@Gobliins 

Please try newest Wekan v1.00, and add animated gif and screenshot mockups about how it works currently, and what way you would like it to work, so I understand better.

**Comment by Gobliins** [comment]
Sorry i was disabled.
Current behaviour:
Swimlane View:
![cardopen1](https://user-images.githubusercontent.com/17267516/41901355-fb163b56-7930-11e8-92c3-285a7ce81022.JPG)
![cardopen2](https://user-images.githubusercontent.com/17267516/41901359-fd710f84-7930-11e8-9d26-7b6d73a070cc.JPG)
List View:
![cardopen3](https://user-images.githubusercontent.com/17267516/41901382-11bf0090-7931-11e8-8f84-d1c09a2bc863.JPG)

As you can see, in the List View the cards remain in the same list after opening a card.
In the Swimlane View, only the current Swimlane block is moved out of list context, while the upper and lower blocks are still in

![cardscroll1](https://user-images.githubusercontent.com/17267516/41902009-a7bae860-7932-11e8-8e22-cf5224b32155.JPG)

Here you can see, how the card is not scrolled vertically so it's correctly on focus.

**Comment by xet7** [comment]
Current way it works, is because of all previous bugfixes etc to functionality. Card opens to side, so that I can scroll that card down while card is open. Etc. I don't see any bug here.

**Comment by xet7** [comment]
If someone has improvements to this, please add pull request.
