### ISSUE TITLE
Copy Card, Move Card and Copy Checklist Template to Many Cards - No longer works in menu

### ISSUE THREAD

**Issue by ertanalytics** [wekan/wekan#1607]
## Issue

**Server Setup Information**:

* Operating System: Ubuntu 16.04 - Fully updated
* Deployment Method(snap/sandstorm/mongodb bundle): sandstorm
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: latest available sandstorm package update as of 4/24/2018
* MongoDB Version: latest available sandstorm package update as of 4/24/2018
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): 
https://ertanalytics.us/shared/JXWpB2JhTjG3c2gk5oDscntAzc7CWylxf7blN2P2QqQ

**Problem description**:  When opening a card and selecting the drop down three line menu, the functions copy card, move card and copy checklist template to many cards do not actually execute fully
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files in .zip file)*
![functions no longer working](https://user-images.githubusercontent.com/7130518/39183240-fb532f4e-4784-11e8-8983-2a669b11ed24.png)

**Comment by iuliaj** [comment]
I have this problem. When copying or moving a card, the destination project does not work. I export the project, remove the custom fields of the project and import it. And it works…
