### ISSUE TITLE
Card URL display a blank screen on private boards

### ISSUE THREAD

**Issue by angli13** [wekan/wekan#1609]
I'm running Wekan 0.85.0 on Heroku but I'm having an issue with the URL that are being shared by the webhook. The notifications work great on Slack but all the urls shared aren't accesible, if I click on any one it will only show me black screen and nothing else. I've checked the console and I could find this error:

URL: https://tg-wekan.herokuapp.com/b/YP6DbPXsYuiABLwpa/ecobpm-web/e265w5y4wuq33nE9P
`There is no route for the path: /b/YP6DbPXsYuiABLwpa/ecobpm-web/e265w5y4wuq33nE9P`

So it would look like a router issue, the interesting part is that the URLs work with public boards only.

* Wekan Version: 0.85
* Node Version: 8.9.3
* MongoDB Version: 3.4.14
* ROOT_URL: https://tg-wekan.herokuapp.com

<img width="1221" alt="captura de pantalla 2018-04-25 a la s 15 44 34" src="https://user-images.githubusercontent.com/3294241/39271776-9ae289e0-489f-11e8-8604-7ec5cd01fc26.png">

**Comment by zebby76** [comment]
+1

**Comment by Inkura** [comment]
I encountered the same problem on my boards.

We use the docker-compose setup and are currently running the following versions:
![image](https://user-images.githubusercontent.com/31927152/40385009-8e9fbe5c-5e05-11e8-9b26-660d06c085a9.png)


Was anyone able to resolve the issue yet?

**Comment by xet7** [comment]
Private boards? Don't you mean public boards?

**Comment by Inkura** [comment]
I currently have two boards on my instance.
Both of them are private.
## Board header
![image](https://user-images.githubusercontent.com/31927152/40385694-bc9eb8a6-5e07-11e8-9aeb-b32a058b41f2.png)

## JS errors when viewing the board
![image](https://user-images.githubusercontent.com/31927152/40385759-f1af736e-5e07-11e8-894b-5ccc0ee15409.png)

## Errors when clicking a card
![image](https://user-images.githubusercontent.com/31927152/40385795-0fc2868e-5e08-11e8-9ee9-1a5c12058e7f.png)



I hope this answers your question and helps with debugging.

**Comment by xet7** [comment]
@Inkura 

You don't have websockets enabled in your webserver. See:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config
https://github.com/wekan/wekan/wiki/Apache

**Comment by Inkura** [comment]
I just realized my mistake on the apache module.
I fixed the configuration problem, but still get the errors:

![image](https://user-images.githubusercontent.com/31927152/40386504-2f81e080-5e0a-11e8-8f80-645d0692010c.png)

![image](https://user-images.githubusercontent.com/31927152/40386518-39aec80c-5e0a-11e8-92ab-66f040cf1ec3.png)


Sorry about my configuration error :)

**Comment by xet7** [comment]
Public boards don't work currently.

**Comment by Inkura** [comment]
I did double checked the config against your link.
Did not see the error yet.

The error happened since i upgraded the docker containers recently.

Let me know if i can provide more details, as i cant find the error unfortunately :)

**Comment by bulburDE** [comment]
I am currently struggling with this error as well. After some research I found out that the error only appears after another user is invited to the board.

Steps to reproduce:

1. Create new board, list and card

**Comment by bulburDE** [comment]
I am currently struggling with this error as well. After some research I found out that the error only appears after another user is invited to the board.

Steps to reproduce:

1. Create new board, list and card
2. Click on Card -> dialog is displayed normally
![before_sharing](https://user-images.githubusercontent.com/6855903/40630330-25bdf2ec-62d2-11e8-8969-b0085305a8ab.png)
3. Invite another user to the board using the sidebar menu
4. Click on card -> an empty page is displayed
![after_sharing](https://user-images.githubusercontent.com/6855903/40630432-fc5b5254-62d2-11e8-92a0-2903736f539b.png)

Notes:
- The user doesn't need to accept the invitation
- Other boards are not affected. They are working normally until inviting a user to them.
- The bug is reproducable
- After removing the user or the invitation the bug is still present
- The error message "There is no route for the path" is also shown when it is working

Since this bug is keeping me from trying out Wekan please contact me if I can help in any way.

**Comment by bulburDE** [comment]
I installed wekan on another computer without using nginx and it worked as expected. After searching a bit more I found #1596 which seems to describe exactly my problem so I will try the solutions offered in that issue.

**Comment by angli13** [comment]
Does someone know how to make this configuration if I used the Heroku button to deploy Wekan?

**Comment by sandromario** [comment]
We're struggling with this problem too. It's very inconvenient that none of the links shared by the webhook actually work. Is there a way to switch off the links entirely in the meantime, until this has been fixed?

**Comment by alngn** [comment]
Any fix to this? im facing the same problem...

**Comment by saurabharch** [comment]
![screenshot-wekan](https://user-images.githubusercontent.com/22369562/48969676-ea4b6300-f027-11e8-97f4-f80f64866cbc.png)
this is the problem why you are getting error in when deploy wekan on heroku or working heroku

**Comment by xet7** [comment]
Have you set ROOT_URL=https://tg-wekan.herokuapp.com ?
