### ISSUE TITLE
Feature Request: hyperlink to onenote or local file

### ISSUE THREAD

**Issue by lime918** [wekan/wekan#1615]
## Issue

**Server Setup Information**:

* Operating System: ubuntu server 17.04
* Deployment Method(snap/sandstorm/mongodb bundle): snap
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: v8.11.1
* wekan versioni: 0.89.0
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
-when adding a hyperlink to a card description or in the comments using a link to a onenote page, a blank page opens instead of navigating to the onenote page:

`onenote:http://path/to/notebook/notebook.one#section_name&section-id={...}&page-id={...}&end`

will open the same card in a new window, which displays a blank pane.

**Comment by xet7** [comment]
@lime918 

Does the link itself work when pasted directly to browser URL bar ?

It seems that your link has `onenote:` in the beginning.

To create link correctly, use markdown syntax like this:
```
[Meeting notes](http://path/to/notebook/notebook.one#section_name&section-id={...}&page-id={...}&end)
```

Then it will be shown this way in Wekan description:

[Meeting notes](http://path/to/notebook/notebook.one#section_name&section-id={...}&page-id={...}&end)

**Comment by xet7** [comment]
I'm guessing that it could be some of these:

a) Wekan's [xss protection](https://www.npmjs.com/package/xss) that is at [package.json file](https://github.com/wekan/wekan/blob/devel/package.json#L32)

b) [in v0.80 added browser-policy](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v080-2018-04-04-wekan-release) that is at [Meteor package versions file](https://github.com/wekan/wekan/blob/devel/.meteor/versions#L21)

I don't yet know how I could go around those.

**Comment by lime918** [comment]
is it possible to have file: URI functionality? I'm trying to provide a markdown-formatted link to a server folder (i.e. file://subsite.company.com/data/)

**Comment by xet7** [comment]
@lime918 

I don't know yet, how well browsers would allow it.

Someone could look at current xss package options etc.

This is related to #1676 and #142 so after those maybe something could be possible.

**Comment by rgalonso** [comment]
I'm not really a JavaScript developer, but it looks like the relevant section in the XSS module is at [default.js#L158](https://github.com/leizongmin/js-xss/blob/v0.3.3/lib/default.js#L158).  (By the way, it looks the XSS module version being used by Wekan, 0.3.3, is pretty out of date!  Not sure if it's intentional, but thought I'd bring it to your attention.)

Allowing the 'file://' schema would facilitate my use case of the card description referencing a file stored on my local network under a Samba share.

Using the file URI directly in my browser (Chrome 73) works, but when I put the link in Wekan as Markdown, it doesn't.  As stated in the [original issue description](https://github.com/wekan/wekan/issues/1615#issue-318977450), clicking the link just opens the same card in a new window.

**Comment by xet7** [comment]
Depends is there any way to add that safely. There is also issue that it's risky to allow embedding remote image with markdown https://github.com/sandstorm-io/sandstorm/issues/2906 . According to npm audit command XSS version used by Wekan is not vulnerable.

**Comment by ocdtrekkie** [comment]
Not sure about what's required to enable access, but I think it should be "safe" to let Wekan link to file: or onenote: etc. Generally one's web browser is responsible for gating access to these sorts of things. For instance, file:// access is disabled by default on Firefox, but you can whitelist specific domains to be able to link to local files.

**Comment by xet7** [comment]
Ok, hopefully someone could add PR for this, or I could sometime have time to figure this out.

**Comment by xet7** [comment]
Moved to here from #2933 

From @gkarachuk 

@xet7 Is the any chance that the markdown version of the link to a local resource, e.g., "mailspring://thread?subject=connection&date=1562329389" will be corrected? It's a great feature that is only linking to the Wekan card, not the actual link.

From @xet7 

The chances are:
a) Someone spends time to figure out how to exclude those URLs from xss package that is at `wekan/package.json`.
b) Someone pays me (Wekan Team) 500 euro to figure it out https://wekan.team/commercial-support/

**Comment by rgalonso** [comment]
Thanks!
