### ISSUE TITLE
Cannot import from Wekan json

### ISSUE THREAD

**Issue by dopaminereceptionist** [wekan/wekan#1616]
## Cannot import from Wekan to Wekan

**Server Setup Information**:

* Operating System: Debian Stretch
* Deployment Method: Docker compose
* Http frontend: Docker quay image v0.89
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:

Import json, map users, and get": `Your JSON data does not include the proper information in the correct format`

Identical behavior to #1590

**Comment by xet7** [comment]
What version of Wekan did you export from?

**Comment by dopaminereceptionist** [comment]
I'm not sure. Looks like the Docker image was from 2017-08-09. Can't find a version tag anywhere and may have lost the admin account on the old one. Don't see a version tag in the json export, either. Does say format is wekan-board-1.0.0.

Thanks for replying.

**Comment by dopaminereceptionist** [comment]
Should JSON import/export work to/from future releases? For a while I was relying as the json export as the only backup and you're telling me it isn't supported.

If I need to do Mongo backups that is okay, but I think the JSON import/export should be removed if it doesn't work so it doesn't set any false expectation.

Also, I did try copying the whole mongo data folder over to another server with the new wekan. Accounts worked, but when I went to the board the right history side worked but no cards turned up so it was extremely broken.

I'm thinking I should just try to pin my use to v0.39 or something.

**Comment by xet7** [comment]
@dopaminereceptionist 

Of course JSON Import/Export will work in future releases. There has been fixes to that in today's release too. Please see #1602 for more info.

AFAIK I did not say that Import/Export is not supported. Also see changelog on GitHub repo, Wekan has very active development.

**Comment by xet7** [comment]
The breakages in JSON Import/Export functionality are because there have been new features added to Wekan, for example Swimlanes etc, and not all of Wekan's code have been modified to add support for those new database tables/fields etc.

Anyone can help support Wekan development with their pull requests and using [my Commercial Support](https://wekan.team). I really welcome more beginners starting to read Wekan code and make modifications, submit their first pull request.

**Comment by dopaminereceptionist** [comment]
I understand, thank you!

I think it would help to add a version field to the export to show which version it was coming from. That way, test cases could be made for import alteration as needed and to make sure the latest version can import from 0.4, 0.5, 0.6, etc.

Unfortunately, I don't have enough time to contribute at the moment, but maybe in the future.

**Comment by xet7** [comment]
I can't add version number to old released versions, that would require complicated re-releasing.

Yes, Wekan could have tests added, and to make it possible to upgrade from all possible previous versions of Wekan. I'll check is there issue about that, and add new one if there is not issue yet.

**Comment by xet7** [comment]
There is tests issue at #467

**Comment by sinasalek** [comment]
I have the same problem, upgrading from wekan-0.12 to the latest version.
I receive the following error: 
```Starting add-sort-checklists migration
W20180528-18:11:26.809(4.5)? (STDERR) TypeError: undefined is not a function
W20180528-18:11:26.811(4.5)? (STDERR)     at Array.find (native)
W20180528-18:11:26.812(4.5)? (STDERR)     at Checklists.find.forEach (server/migrations.js:143:21)
W20180528-18:11:26.813(4.5)? (STDERR)     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
W20180528-18:11:26.814(4.5)? (STDERR)     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
W20180528-18:11:26.815(4.5)? (STDERR)     at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
W20180528-18:11:26.816(4.5)? (STDERR)     at packages\idmontie_migrations.js:238:17
W20180528-18:11:26.817(4.5)? (STDERR)     at Function.time (wekan\.meteor\local\build\programs\server\profile.js:309:28)
W20180528-18:11:26.818(4.5)? (STDERR)     at wekan\.meteor\local\build\programs\server\boot.js:423:13
W20180528-18:11:26.819(4.5)? (STDERR)     at wekan\.meteor\local\build\programs\server\boot.js:464:5
W20180528-18:11:26.823(4.5)? (STDERR)     at Function.run (wekan\.meteor\local\build\programs\server\profile.js:510:12)
W20180528-18:11:26.825(4.5)? (STDERR)     at wekan\.meteor\local\build\programs\server\boot.js:462:11
=> Exited with code: 1
   Building the application
```

After this it just keeps repeating the same error.
I tried exporting and importing boards but that also does not work and gives sort of an invalid data format error with yellow color

**Comment by sinasalek** [comment]
I attached a sample json that i have trouble importing
[wekan-export-board-NG8THSybTFr4oM4mz.zip](https://github.com/wekan/wekan/files/2053117/wekan-export-board-NG8THSybTFr4oM4mz.zip)
