### ISSUE TITLE
Checklist item line height is too small

### ISSUE THREAD

**Issue by lichtamberg** [wekan/wekan#1619]
## Issue

After the 0.90 release, the checklist item text has a too small line height imo and looks somehow not really good - see following images (with current height of 14px and without it/unset)

![bildschirmfoto 2018-05-02 um 14 27 39](https://user-images.githubusercontent.com/10075/39523208-4b37b5d6-4e04-11e8-8bae-74bac708e28e.png)

![bildschirmfoto 2018-05-02 um 14 27 52](https://user-images.githubusercontent.com/10075/39523207-4b1956c2-4e04-11e8-8c90-15d398800a37.png)

Here is the commit: 

https://github.com/wekan/wekan/commit/1124f4120cd77622c0a6313e228e1a00690ff566#diff-2e48b5bc5ad458b178b2b34ead97e7faR97

I would like to have the original line height restored (unset is 18px, which looks fine), what are your thoughts?

@xet7 If there is consent, I can submit a PR? :D

**Server Setup Information**:

* OSX Sierra
* Installed via snap
* NGINX

**Comment by xet7** [comment]
@lichtamberg 

Please add:
* screenshot how it looks in 18px
* PR

**Comment by xet7** [comment]
Hmm, actually you already have screenshot. Looks good, please submit PR.

**Comment by lichtamberg** [comment]
18px look like the same when I unset the line height in firefox debug mode (see my second screenshot). Will post a PR in some minutes.
