### ISSUE TITLE
When filter is on I can't see checklist items.

### ISSUE THREAD

**Issue by hever** [wekan/wekan#1633]
## Issue

**Server Setup Information**:

* Operating System: Debian 9.4
* Deployment Method:snap
* Http frontend: only wekan

**Problem description**:
When filter is on (filter by label) I can't see checklist items.

**Comment by xet7** [comment]
@hever 

Please give screenshots how did you get it to not show checklist items. Because checklist items are visible to me on Wekan v0.95. I'm unable to duplicate this.

**Comment by hever** [comment]
I have Wekan v0.83. So I'll need to upgrade first. It's strange because I follow your install guide and set automatic refresh. There's some problem with refresh, I'll create new issue.

**Comment by hever** [comment]
Redo new issue, after moment it's start working. So now I have version 0.95 and problem gone. It's working as excepted. Thanks.
