### ISSUE TITLE
checklistItems broken after upgrade

### ISSUE THREAD

**Issue by franksiler** [wekan/wekan#1636]
## Issue

**Server Setup Information**:

* Operating System: CentOS
* Node Version: 8.11.1
* MongoDB Version: 0.95 (upgrade from 0.48)

**Problem description**:
- Upgraded from 0.48 to 0.95.  Discovered that checklist titles were cloned into each item description field.
- For example, had in db.checklists:

```
{
  "_id": "z329QEDfjsuQcxz7E",
  "cardId": "TBgz6gMGCcn9XNPSW",
  "title": "A list",
  "sort": 0,
  "createdAt": {
    "$date": "2018-05-09T22:20:50.537Z"
  },
  "items": [
    {
      "_id": "z329QEDfjsuQcxz7E0",
      "title": "Do some stuff",
      "isFinished": false,
      "sort": 0
    },
    {
      "_id": "z329QEDfjsuQcxz7E1",
      "title": "Do some other stuff",
      "isFinished": false,
      "sort": 1
    }
  ],
  "userId": "YndMrPQ5XhZTTKD2S"
}
```

and wound up with the following in wekan.checklistItems:

    {
      "_id": "RADPEu4nhr9PgwPHH",
      "title": "A list",
      "sort": 0,
      "isFinished": false,
      "checklistId": "z329QEDfjsuQcxz7E",
      "cardId": "TBgz6gMGCcn9XNPSW"
    }
    {
      "_id": "Guy3aaJL4WLJQjzRX",
      "title": "A list",
      "sort": 1,
      "isFinished": false,
      "checklistId": "z329QEDfjsuQcxz7E",
      "cardId": "TBgz6gMGCcn9XNPSW"
    }

and this in wekan.checklists:

    { "_id" : "z329QEDfjsuQcxz7E", "cardId" : "TBgz6gMGCcn9XNPSW", "title" : "MVP", "sort" : 0, "createdAt" : ISODate("2018-05-09T22:20:50.537Z"), "userId" : "YndMrPQ5XhZTTKD2S" }

- Each card now appears with the title "A list"- the name of the checklist, rather than the checklist item title.  I am sure there's a query that will allow me to update my current checklist items titles from my backups, but I'm new to Mongo and could use a bit of help.  Is there a script?  I dug through the source tree but don't seem to find how this transform actually happened.  Appreciate any help.

**Comment by franksiler** [comment]
Fix: load your old db.checklists into db.checklistsOld.  Use the following script in Robo3T:

db.checklistsOld.find({}, {"_id": 1, "items.title":1, "items.sort": 1 }).forEach( ( list, i, lists) => { 
  var checklistId = list._id;
  list.items.forEach( (item, j, items) => {
      var sort = item.sort,
          title = item.title;
      db.checklistItems.update({"checklistId": checklistId, "sort":sort}, {$set: {"title": title}} );
  });

});

**Comment by xet7** [comment]
@franksiler

Can you try to add that fix directly to Wekan itself as pull request?

**Comment by franksiler** [comment]
I suppose I'm not sure what you're requesting- it requires external tooling and a load of the old data in order to use the fix that I suggested.  I tried to find where in the source tree Wekan did the migration but didn't find anything of note where I could patch it.

**Comment by Badpat** [comment]
In server/migrations.js there is a bug in the 'add-checklist-items' section as the title of the new ChecklistItem is set to the title of the whole Checklist.

I think line 196 must be changed to `title: item.title`, but I can't verify at the moment.

**Comment by franksiler** [comment]
I believe @Badpat is correct and will try to take time to test my migration against that change.

**Comment by franksiler** [comment]
Tested and submitted [1641](https://github.com/wekan/wekan/pull/1641)- waiting on employer auth to sign CLA.
