### ISSUE TITLE
Filter and Search icon do not appear in the first login

### ISSUE THREAD

**Issue by d3dbit** [wekan/wekan#1638]
## Issue

**Server Setup Information**:

* Operating System: Ubuntu Linux - AWS Virtual Machine
* Deployment Method: Docker - wekan-mongodb v0.95.0
* Node Version: v8.11.1
* MongoDB Version: 3.2.19

**Problem description**:
-  The first time that I log in to the Wekan App and I try to access a Board, the Filter and the Search icon do not appear.
- After I press the Wekan icon and I try to access another time to the same Board, then the Filter and the Search icon appear.
- Example:
![image](https://user-images.githubusercontent.com/26925243/40021397-003df0ca-57c5-11e8-925f-3eac13aae02f.png)

**Comment by therampagerado** [comment]
Same here. I have to remind my people to refresh the page when they need the search option. :D

**Comment by xet7** [comment]
Do you use quay Docker image?

Do you use Firefox?

I tried it, and Search etc is always visible, when board is open. This is with existing old Wekan data, and new clean install, on Docker and Snap, both work. I'm unable to duplicate this.

**Comment by d3dbit** [comment]
Yes. I use quay Docker image.
And I use Firefox and Chrome, and I have the same issue in both browsers.
Have you tried to simulate it with an Incognito mode browser?
Thanks!

**Comment by xet7** [comment]
Please record animated gif video about what is the problem.

I tried this in Firefox and Chrome incognito mode:
1) Login to Wekan
2) Click board to open board
3) Filter, search etc is visible.

I don't understand what is the problem.

**Comment by xet7** [comment]
I'm unable to duplicate this.

**Comment by d3dbit** [comment]
Hello @xet7 ,
Sorry for the delay in reply you.
I have just upgraded to the v1.01, and it seems that now it is working well.
Thanks for your support and thanks for your good work.

**Comment by d3dbit** [comment]
Hello @xet7 ,
I have just upgraded to the v1.02 and again the issue has appeared.
Thanks.

![d3dbit_issue1638](https://user-images.githubusercontent.com/26925243/40605324-4974468e-6262-11e8-805a-d64474d50246.gif)

**Comment by d3dbit** [comment]
I have upgraded to the v1.3 and I am experimenting the same issue. Thanks.

**Comment by xet7** [comment]
@d3dbit 

Sorry, I can not duplicate your issue, I'm using Wekan v1.04 snap.

**Comment by d3dbit** [comment]
@xet7 sorry. After some tests, I think that I know how to reproduce my issue. I think that this issue only passes with the big boards. If I try to access a little board (a board with few cards) the issue does not appear. But if I try to access a big board (a board with a lot of cards and with 5-6 users) the issue appears.
Could you try to reproduce and re-open my issue?
Sorry for my insistence.
You are doing an excellent work.
Thanks.

**Comment by d3dbit** [comment]
@xet7 ,
Finally, this issue has been resolved after migrating all the cards of this issue board to a new one (as I said at issue [#1740](https://github.com/wekan/wekan/issues/1740).
Thanks.
