### ISSUE TITLE
Dockerfile "build" fails

### ISSUE THREAD

**Issue by jimt** [wekan/wekan#164]
Trying to build a Docker container from master (1b4fcc67f4ec94ed53a2f86ad6889e551f00815e) fails because of perfect-scrollbar:

```
Bower:  { [Error: Package perfect-scrollbar not found] stack: [Getter] }
Bower:  { [Error: git is not installed or not in the PATH] stack: [Getter] }
Bower:  { [Error: git is not installed or not in the PATH] stack: [Getter] }
Bower:  { [Error: git is not installed or not in the PATH] stack: [Getter] }
```

**Comment by mquandalle** [comment]
I can’t reproduce this bug, docker build is working for me.
It seems the error is causing by the fact you don’t have `git` in your PATH. I’m not sure how we should handle this case.

**Comment by JohnPostlethwait** [comment]
I see this same thing trying to build it using boot2docker via OSX.

**Comment by jimt** [comment]
Yes, the problem seems to be that `git` is not included in the base image the Docker file builds on, and is not installed by the dockerfile.

**Comment by bluepuma77** [comment]
Same issue here with Docker on Debian. 

I even added git to the Dockerfile of *libreboard*
```
FROM meteorhacks/meteord:onbuild
MAINTAINER Maxime Quandalle <maxime@quandalle.com>

RUN apt-get update && apt-get install -yq git

# Run as you wish!
# docker run -d --name libreboard-db mongo
```
but get the same error
```
Bower:  { [Error: Package autosize not found] stack: [Getter] }
Bower:  { [Error: git is not installed or not in the PATH] stack: [Getter] }
Bower:  { [Error: git is not installed or not in the PATH] stack: [Getter] }
Bower:  { [Error: git is not installed or not in the PATH] stack: [Getter] }
Errors prevented bundling:
While building the application:
packages/bower/plugin/handler.js:191:1: Cannot read property 'name' of
undefined (compiling bower.json)
at getDependencies (packages/bower/plugin/handler.js:191:1)
``` 
Not sure if this is an issue with *meteorhacks/meteord:onbuild*

**Comment by veerjainATgmail** [comment]
Hi,
Any workaround for this failure?
thanks,
Mahaveer

**Comment by mko-x** [comment]
For somewhat reason git is not included - that's correct. I was able to build it in boot2docker OSX once. But it seems like a race condition somehow on meteorhacks/meteord.

I created a working variant, find it here: 

docker -> https://registry.hub.docker.com/u/mkodockx/docker-libreboard
github -> https://github.com/mko-x/libreboard

I just added git on init and it works like a charm everywhere.
