### ISSUE TITLE
Is there a default username and password after the install?

### ISSUE THREAD

**Issue by streetlist** [wekan/wekan#1648]
i'm using the dokan wekan

how do i set up ldap for wekan? is there a documentation on the usage for the docker/wekan?

**Comment by sfahrenholz** [comment]
Hello,
is this the same as https://github.com/wekan/wekan/issues/119?

**Comment by xet7** [comment]
Yes. Standalone Wekan has example LDAP code, but it's not integrated yet. https://sandstorm.io has LDAP etc.

Moved to #119
