### ISSUE TITLE
Feature Request: Custom fields additions and fixes

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1650]
The new feature is great but I would like to make it little more user friendly.

Improvements:
1. When we specify global custom fields in the right swipe menu we have to see them for all cards in the future already available. The current way is that we have to add everyone of them to our cards manually if we need them. This takes time and is not user friendly if we need to speed things up and simplify our day-2-day activities in Wekan.
2. I would like to see the Custom Field (CF) types already visible in my cards. So in one word I would like to remove "edit" button and replace it with the placeholder - text, number, dropdown, date (date can be left as is to be in conformation with the rest of dates). This will save one click per initial field edit and will be more user friendly to the customers - they will know exactly what to expect there - number, or input text or choose from the dropdown.

Additions:
1. I would like to have checkboxes field where in the card I have already created checkbox. Let me explain the user case - I have 5 working stations. One order may have all of them involved or only 1. When I create card for this order I need to quickly specify which stations are involved in it. Now I have to create every checkbox manually and write it's values, name, etc. 

I would like to have already made checkbox with all possible combinations when I create a card. Then when I have only 3 stations involved I can delete the 2 that don't do work on this particular order and have the checkbox available for the working ones. That way the admin of the board can quickly give work to each station by just deleting the unnecessary options with 1-2 mouse clicks and when they are complete the checkbox field will light up green making the card ready to move to the next column.

I can imagine the same implementation as the new custom fields so I would like to leave it here as a suggestion.

**Comment by feuerball11** [comment]
Improvement 1.: 
I could see this as an option in the creation of customFields. It depends on the usercase. If you want to have a new custom field for 1-3 cards, or just one board, and add it to all cards on all boards, you need time to remove all the custom fields. 
So yes, as an option on the creation. 

Improvement 2: 
Sounds good

Addition 1:
Checkboxes where planned by the original autor, i just finishd what was there. I put them on my todos, but i have deleting things from recycling bin, and a few bugfixes regarding custom fields and filter bevore that. 

Final note:
Custom Fields are still an WIP Feature, also issue #807 is still open.

**Comment by xet7** [comment]
Moved to #807
