### ISSUE TITLE
Board view breaks after adding new card via REST interface

### ISSUE THREAD

**Issue by mariovor** [wekan/wekan#1651]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.0.0
* Operating System: Debian Jessie / Arch Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker / quay.io/wekan/wekan

**Problem description**:
Adding a new Card via the Rest interface leads a broken board view -> The board does not load anymore and gets stuck with the loading animation. However, I can see the new Card via the Rest interface, it is added to the database. 

I compared the Cards added via the web interface (a) and the rest interface (b):

a):
{
    "_id": "8QxavMczTrynh7xYT",
    "title": "New",
    "members": [],
    "labelIds": [],
    "customFields": [],
    "listId": "2QqaJ477zHvaZN7Am",
    "boardId": "eHKjiN5964Y8dNy7F",
    "sort": -1,
    "swimlaneId": "u4EEEdo59wTq5MmHK",
    "archived": false,
    "createdAt": "2018-05-22T18:42:03.033Z",
    "dateLastActivity": "2018-05-22T18:42:03.033Z",
    "isOvertime": false,
    "userId": "xxxx"
} 

b)

{
    "_id": "znJMnvr92GGJifHsv",
    "title": "New",
    "members": [
        "xxx"
    ],
    "listId": "2QqaJ477zHvaZN7Am",
    "boardId": "eHKjiN5964Y8dNy7F",
    "sort": 0,
    "swimlaneId": "u4EEEdo59wTq5MmHK",
    "archived": false,
    "createdAt": "2018-05-22T18:44:39.499Z",
    "dateLastActivity": "2018-05-22T18:44:39.499Z",
    "isOvertime": false,
    "swimlaneId": "u4EEEdo59wTq5MmHK",
    "userId": "xxxx"
}

We see, in b) are missing the labelIds and customFields. Without checking the Wekan code in detail, I could believe that could lead to problems.
As far as I can see in https://github.com/wekan/wekan/blob/devel/models/cards.js both elements are not added in 
`JsonRoutes.add('POST', '/api/boards/:boardId/lists/:listId/cards', function (req, res).` 
Would an expert agree with this analysis?

It requires a restore of the mongoDB in order to make Wekan work again.

Let me know if I can provide more information.

If nobody cares to much about the issue, I could try to fix it. But it could take a bit.

**Comment by ocdtrekkie** [comment]
It is probably a fairly simple fix. This sort of thing can be an easy oversight when adding new elements to boards or cards such as the just-added custom fields. (It may be good to document a list of these features that need to be checked for compatibility when adding new fields. Import/export is the usual victim.)

**Comment by mariovor** [comment]
I just tested the new version (1.0.1) and the creation of tickets via REST works now.
Thanks to all involved for the quick fix!
