### ISSUE TITLE
Imported Boards won't open

### ISSUE THREAD

**Issue by vkb** [wekan/wekan#1652]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.0.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu Server 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: (snap package)
* MongoDB Version: (snap package)
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://192.168.56.101:8080

**Problem description**:
Currently it is **not possible to open imported boards**. I considered problems with my entire setup, and therefore removed and freshly installed the wekan snap package, to get a new and clean environment.

*Steps to reproduce*
- Install a fresh setup of Wekan via snap
- Open the preexisting _Welcome Board_
- Add an additional testcard
- Export the board
- Re-Import the board
- Try to open the board

The board loading animation appears and nothing more happens. I added the export as an attachment:
[export_test.zip](https://github.com/wekan/wekan/files/2030228/export_test.zip)

Thank you for your work!

**Comment by feuerball11** [comment]
Hi, That has probalby to do something with the CustomFields Feature, I'm Currently looking into this

**Comment by vkb** [comment]
Thank you. I just noticed another detail:

URL of existing Card in preexisting _Welcome Board_:
![addressofcard](https://user-images.githubusercontent.com/458103/40414853-b09d593c-5e79-11e8-9690-c01d19a827cc.png)

URL of _Add Card_ button:
![addressofnewcard](https://user-images.githubusercontent.com/458103/40414901-d36f3b60-5e79-11e8-8011-0b9b4cd29b2c.png)

Same behavior when i create a new board. After switchting the port to 80, i can open the card. Unfortunately, it doesn't solve the loading issue of imported boards, but might represent another issue.

**Comment by feuerball11** [comment]
@vkb your sekond problem sounds more like a configuration issue... anyway, to your first problem, i opend a pullrequest that should fix this, just wait for @xet7 to include this. It should fix the issue.

**Comment by vkb** [comment]
Excellent, very much appreciated!
