### ISSUE TITLE
Can not set received and end date in cards

### ISSUE THREAD

**Issue by xadagaras** [wekan/wekan#1654]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:
* Wekan version:
1.00
* If this is about old version of Wekan, what upgrade problem you have?:
0.85
* Operating System:
Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Docker
* MongoDB Version:
3.2.20

**Problem description**:
![bildschirmfoto 2018-05-23 um 15 20 42](https://user-images.githubusercontent.com/864060/40427057-e792bdd8-5e9c-11e8-8774-88d5101a4219.png)
If you click on the date field for received or end date, you get an empty box (see screenshot). 
Expected behavior is, that a date picker will show up where you can pick the date.
This feature worked in wekan 0.85, but in the latest version it is broken. Start and due date are still working.
The following screenshot shows the dialog that should show up.
![bildschirmfoto 2018-05-23 um 15 22 39](https://user-images.githubusercontent.com/864060/40427147-2b32562a-5e9d-11e8-8ef7-df85299b4a90.png)

**Comment by rjevnikar** [comment]
This may be because in ~/client/components/cards/cardDate.js editCardReceivedDatePopup and editCardEndDatePopup extend EditCardDate while editCardStartDatePopup and editCardDueDatePopup extend DatePicker.

This change was made in version 0.96 - I'm not sure if it was intentional, or a result of resolving merge conflicts.

**Comment by viktorjamrich** [comment]
I have exactly the same problem.
Cannot set Received date nor End date - the datepicker is just missing.
Version 1.00.0

**Comment by TiibCD** [comment]
Same problem with v1.00 and virtualbox appliance
