### ISSUE TITLE
How to fire update method on client?

### ISSUE THREAD

**Issue by franksiler** [wekan/wekan#1657]
## Issue
I have a very unreliable Wekan server- and I have data that isn't being pushed from the browser to the server.  I'm not an expert on the javascript frameworks being used.  Can someone point me in the right direction as far as javascript incantations to try to update the server again?

**Server Setup Information**:

* Did you test in newest Wekan?: Yes, v1.01

**Comment by xet7** [comment]
Most likely you have some misconfigured webserver in front of Wekan.
I recommend installing Wekan Snap with Caddy for SSL to Ubuntu 18.04 server:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by franksiler** [comment]
I'm not using anything in front of wekan.  The server restarts frequently.  I would just like a way to tell the client to try updating again.

**Comment by xet7** [comment]
Did you use snap to install wekan? Do you have enough RAM for Wekan, for example 2 GB ? What Linux version you have? What kernel version?

**Comment by xet7** [comment]
No reply received.
