### ISSUE TITLE
Issue with custom fields shown on card

### ISSUE THREAD

**Issue by TiibCD** [wekan/wekan#1659]
## Issue

**Server Setup Information**:

* Wekan version: v1.00
* Operating System: Ubuntu
* Deployment Method: VirtualBox appliance

**Problem description**:

Hi all,
We found a minor issue with the new custom fields (great idea btw). When you create a field with the dropdown list type and you check the option to show it on card. What you get as a result is the id of the item and not the label.
See for yourself :

![image](https://user-images.githubusercontent.com/24451989/40542094-ed29aa62-601e-11e8-9d77-a0992eb0b246.png)
![image](https://user-images.githubusercontent.com/24451989/40542146-3101d7fa-601f-11e8-9a5e-e44ed0bc4b46.png)

**Comment by pblvsk** [comment]
I'm also experiencing this.
Deployment method: Docker, mongo 3.2.20, wekan 1.01.

**Comment by stefanwuthrich** [comment]
here also, wekan 1.02

**Comment by Fran-KTA** [comment]
Also noticed that.

Docker: mongo 3.2.20, wekan 1.02, nginx(rev-proxy SSL)

**Comment by rentox** [comment]
same here:
Wekan-Version: 1.03.0
node: v8.11.1
ubuntu: 4.13.0-36-generic

**Comment by feuerball11** [comment]
Known Problem. see #807

**Comment by TiibCD** [comment]
@feuerball11 Thanks for your work ! I was taking a look at the code to correct it myself but I'm not used to Jade so glad you did it so fast.
