### ISSUE TITLE
Moving cards from one board to another: Activity shows *undefined*

### ISSUE THREAD

**Issue by trin94** [wekan/wekan#1662]
## Server Setup Information:
* Wekan version: v1.01

## Problem description:
When moving cards between two boards the card will be referenced with *undefined*.
### Reproduce
1. Create two separate boards
2. On each board create a list
2. On the first board create a Card
3. Click on the menu and select *Move Card*
4. Select the second board, a swim lane and a list. Press done.
5. Switch to the second board.
6. Select the new card, open the menu and select *Move Card*.
7. Select the properties of the first board (does not matter which exeactly). Press done.
8. Reload the page

Activity on board 1 (the board the card was initially created):
![image](https://user-images.githubusercontent.com/12988790/40579702-e9e06188-612d-11e8-980f-502d4b2658c2.png)

Activity on board 2:
![image](https://user-images.githubusercontent.com/12988790/40579692-d0fcd7be-612d-11e8-8db4-456957abcae0.png)

### Log files
I am not server owner, sorry.

**Comment by xet7** [comment]
@trin94 

Does this still happen with newest Wekan?

**Comment by trin94** [comment]
I don't use Wekan at the moment :sweat_smile:
