### ISSUE TITLE
What is the max version of nodejs,meteor,mongodb wekan is compabile with?

### ISSUE THREAD

**Issue by sinasalek** [wekan/wekan#1664]
I read the wiki https://github.com/wekan/wekan/wiki/Install-and-Update
I'm looking for the max version not minimum requirement

**Comment by xet7** [comment]
Max versions:
- Meteor 1.6.0.1
- Node 8.11.1 or newer 8.x, currently using performance patched version from https://releases.wekan.team
- MongoDB 3.2.x

**Comment by sinasalek** [comment]
Tx, i updated the wiki
