### ISSUE TITLE
How to find exact dates of activities inside card?

### ISSUE THREAD

**Issue by zombah** [wekan/wekan#1666]
## Question

**Server Setup Information**:

* Did you test in newest Wekan?: **No**
* Wekan version: **0.93**
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: **Linux**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **docker**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Nginx**
* Node Version:
* MongoDB Version: **3.2.19**
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): **https**

**Problem description**:

Is it possible somehow to see exact dates of activities inside card? Currently card show relative dates like activity was month ago or like this.

**Comment by xet7** [comment]
Please try newest Wekan first. There is no fixes coming to old versions of Wekan.

**Comment by zombah** [comment]
I didn't thought thats an issue but just standard behaiviour. Ok i will try to update.

**Comment by therampagerado** [comment]
The update won't help you. This is the standard

**Comment by zombah** [comment]
Yep updated to v1.02 and it looks same. Maybe there is some way to change it to exact dates or it is impossible currently and needs to be implemented?

**Comment by viktorjamrich** [comment]
I'd love this thing as well. Maybe if you hovered the mouse over the relative date (like it's right now) a tooltip with an exact date would appear ;)

**Comment by zombah** [comment]
@viktorjamrich Thanks alot, i didn't noticed that tooltip
