### ISSUE TITLE
Feature Request: My Cards

### ISSUE THREAD

**Issue by viktorjamrich** [wekan/wekan#1667]
## Feature Request

**Server Setup Information**:

* Did you test in newest Wekan?: yep
* Wekan version: 1.02
* Operating System: Ubuntu 18.04 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker-compose
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache2 proxy

**Feature description**:

It would be super awesome if there was an option, like in Trello, to display all my cards so that I can clearly see what should I focus on.

Right now, we have like 10 different boards and I'm assigned to many of the cards.
If I want to see what I gotta do, I need to open EVERY SINGLE board and check out what I should do.

This would help a lot ;)

**Comment by therampagerado** [comment]
If you're tagged in the cards try "Q" and come here to thank us... :D

**Comment by viktorjamrich** [comment]
@therampagerado yep I have already discovered this feature, which is super great in a single board. But when you're in like 10 different boards, you'd still need to open every single one and then hit Q...

It would be great to have a SINGLE view with all cards I'm participating on.

**Comment by alexanderdd** [comment]
Hey, I am currently looking for task management tools and this is a deciding feature.

There **has** to be a way to see all tasks/cards assigned to you, across projects/teams (=boards). Otherwise it is not suitable for project management. I cannot expect my employees to look into all 30 boards they are a member of every day.

Even better would be if you can also see all cards assigned to user XY, and to see all overdue cards (important for managers).

The current severity is only "inconvenient". and most other users & developers seem to be interested in other features that improve work _within_ a board.

**Comment by justinr1234** [comment]
This is a high priority feature, but we don’t have enough manpower yet to implement. I expect something within the next 3 months on this.

**Comment by alexanderdd** [comment]
Thanks @justinr1234 for the quick reply. If this is high priority, why is it not in the roadmap board at https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license ? 

I noticed that the label severity:inconvenient is actually suitable since the next higher one would be severity:security, and this is not a security issue.

Yes, I understand that manpower is always difficult for open source projects that get funded just by commercial support, but 3 months sounds awesome =)

**Comment by justinr1234** [comment]
I think the roadmap is a bit outdated, @xet7

**Comment by xet7** [comment]
This issue is already at Roadmap, Commercial Support 3rd from top Main Boards:
https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/KJY6pxvvHNAgQFPoj
There is link to this issue "Top Level Projects" that mentions "My Boards" https://github.com/wekan/wekan/issues/641#issuecomment-468868580

Sure it could mentioned at Roadmap somewhat more clearly, but oh well...

That extra request is not yet at Roadmap:
"Even better would be if you can also see all cards assigned to user XY, and to see all overdue cards (important for managers)."

Because nobody had asked for that yet, or funded that yet before at:
https://wekan.team/commercial-support/

For some other issues, Roadmap could be a little outdated.

**Comment by alexanderdd** [comment]
@xet7 thank you, I checked the issues that you referred to (https://github.com/wekan/wekan/issues/2796 and https://github.com/wekan/wekan/issues/641)
This is actually not what I need & what this bug #1667 is about.

Please have a look at https://trello.com/my/cards  -- It is a list of all cards assigned to me. You can sort it by due date or by boards, you can filter it by activity within last week/month/all, you can show results from all boards or select boards that you want to see cards from.

_Minimal implementation would be: **Show a list of all cards assigned to me, sorted by due date.**_

This would make life so much easier, and it seems it is much easier to implement than the other requests (bugs linked at the top of this post).

**Comment by xet7** [comment]
@alexanderdd 

What do you mean with "much easier to implement" ? Will you make pull request to implement this?

**Comment by alexanderdd** [comment]
You are right, I don't know if it's easier, and I don't have the skills to
contribute. It sounds easier because the description of the minimal
implementation (see my last post) is much shorter than the description in
the other two issues.

Lauri Ojansivu <notifications@github.com> schrieb am Sa., 1. Feb. 2020,
22:39:

**Comment by Shekesh** [comment]
I would like to add, that even the "summary" feature of having all cards assigned to me over all boards would definitely be very helpfull, I would love to also have the option to prioritize these cards (because there could be many of them) by ordering them (which will be saved) or add a star (or something similar) to favor and prioritize some of them.

**Comment by xet7** [comment]
I added this to [here at my Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/NqtLP3vR2iE9qEYxw) because someone participated to paying for this.

**Comment by Beltrando** [comment]
> I added this to [here at my Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/NqtLP3vR2iE9qEYxw) because someone participated to paying for this.

I am a newbee here, and, I also need this feature. 
How can it  be done ?

**Comment by xet7** [comment]
It is possible to participate funding feature or fix with payment options listed at https://wekan.team/commercial-support/ . All paid features and fixes will be implemented. Current paid upcoming features are listed at Roadmap with some number amount of money, link to Roadmap is at https://wekan.github.io . Highest paid have highest priority.

**Comment by jrsupplee** [comment]
@xet7 just approved my pull request for a _My Cards_ page.  It has very basic formatting and is organized by board.  It needs be developed further, but it would be helpful to get some feedback on what this page should look like.

1. Filtering cards.  Currently all cards for which the user is an _assignee_ or a _member_ are shown.  Does this seem like the correct selection criteria?
2. Sorting of cards.  In what order should the cards be displayed?
3. Formatting.  Can anyone sketch up the best way to display the cards (keeping in mind that cards have a _board_, a _swimlane_, and a _list_ associated with them)?

I don't have a lot of time to work on this, but I would like to see it improved.

**Comment by alexanderdd** [comment]
Linking your pull request for reference. https://github.com/wekan/wekan/pull/3413 
A screenshot of your prototype would be helpful.

**Comment by xet7** [comment]
@alexanderdd @jrsupplee 

In newest Wekan, when you are member or assigned to card, there is menu option `My Cards`:

![wekan-my-cards-menu](https://user-images.githubusercontent.com/15545/103472753-ea3af700-4d99-11eb-8471-98d803b9df90.png)

It shows list of your member and assigned cards. Some possible improvements could be:
- Those Board/Swimlane/List titles could be made to render markdown and emoji by adding to `.jade` files code `+viewer`
- Layout if OK on mobile `if isMiniScreen`. When in fullscreen mode `if not isMiniScreen`, cards that are at same lists could be at same row.
- If there is undefined list etc, that text `undefined list` could be made translateable:

![my-cards-list](https://user-images.githubusercontent.com/15545/103472757-02ab1180-4d9a-11eb-9eb1-da875f1549bc.png)

![my-cards-list-undefined](https://user-images.githubusercontent.com/15545/103472779-30905600-4d9a-11eb-9b5d-7ac5966a4d07.png)

**Comment by xet7** [comment]
At first time when I was trying My Cards page, it looked like My Cards page did not not load properly, so I deleted my [Template board](https://github.com/wekan/wekan/wiki/Templates). After that, when My Cards page was working, I added new board template and card to it, with me assigned. I don't know would it be useful to add some info that card is at Template board, here I added info text to card itself manually:

![my-cards-template](https://user-images.githubusercontent.com/15545/103472981-4272f880-4d9c-11eb-82dc-84a501d64b6e.png)

**Comment by jrsupplee** [comment]
>>     * If there is undefined list etc, that text `undefined list` could be made translateable:

Agreed.

But could a card have not list assigned to it other than template cards?

**Comment by jrsupplee** [comment]
> At first time when I was trying My Cards page, it looked like My Cards page did not not load properly, so I deleted my [Template board](https://github.com/wekan/wekan/wiki/Templates). After that, when My Cards page was working, I added new board template and card to it, with me assigned. I don't know would it be useful to add some info that card is at Template board, here I added info text to card itself manually:
> 
> ![my-cards-template](https://user-images.githubusercontent.com/15545/103472981-4272f880-4d9c-11eb-82dc-84a501d64b6e.png)

Not sure why the _My Cards_ page did not work with a template board.  It does not make sense to me since the `.find()` does not have any criteria about type of board.

But your question raises another issue.  Should template cards be included in the _My Cards_ page?  If not, what `card.type` selection criteria should I use to eliminate template cards?

**Comment by xet7** [comment]
@jrsupplee 

`My Cards` page did show member and assignee cards from template board, so it works OK. Also clicking template board card works to open template board. I think it's not necessary to eliminate template cards.

**Comment by jrsupplee** [comment]
@xet7 is it possible to have a card that is not assigned to a list?  Even template cards are inside of lists.

Template cards are now displayed like this (I have reformatted the _My Cards_ page).

![image](https://user-images.githubusercontent.com/1286169/103533667-323f4400-4e96-11eb-9764-d92b0bdab148.png)

**Comment by xet7** [comment]
@jrsupplee 

Usually at Wekan first list is created, and then cards are added to list. Can you try to explain with more details and screenshot mockup about what you are trying to do?

**Comment by jrsupplee** [comment]
@xet7 
You had a card with an 'undefined list' above.  Was that a bug in displaying the list name or are there cards that have no list assigned to them?

**Comment by xet7** [comment]
@jrsupplee 

It seems that clicking card in Archived list did open board, but did not open card. This is because that list and card is archived. After I opened that board where Archived list and card is, and went back to `My Cards`, that `undefined list` text changed to real name of that Archived list. At cards/lists/swimlanes collections/tables is text about is it archived or not. It would be nice to show archived icon on those that are archived, similarly when at board when you go to Board Settings => Archive and show archived items there.

**Comment by xet7** [comment]
With some change to code, it could maybe be possible also to open archived card with direct link, like opening card that is not archived, there could be some related code somewhere.

**Comment by jrsupplee** [comment]
@xet7 
If a list is archived are the cards also marked as archived?  I am guessing they are not, otherwise the card selection criteria (`archived: false`) would not find them.

Also, the selection criteria for retrieving the swimlanes and lists on the server side has `archived: false`.  So if a card with `archived=false` is in a list with `archived=true` then the card will be returned, but not the list.

This makes perfect sense. Thanks.

Now the question: should cards in archived lists or swimlanes be shown on the _My Cards_ page?  It seems to me they should not.

**Comment by xet7** [comment]
@jrsupplee

Could there be option like slider or checkbox to optionally also show archived cards etc?

**Comment by xet7** [comment]
@jrsupplee 

Or maybe even better would be separate page my-archived-cards that only shows archived cards.

**Comment by xet7** [comment]
It would be really nice if someone that has accidently arhived card could go to my-archived-cards and restore it back. Any card where someone is member or assignee is important.

**Comment by jrsupplee** [comment]
Is there currently a way to display archived cards, lists or swimlanes?

**Comment by xet7** [comment]
@jrsupplee 

Yes. At board, click ☰ => ⚙ => Archive. There you can see and restore archived swimlanes, lists and cards. But that is only for one board.

For my-cards, you would add to your database query `'archived': false`.

For my-archived-cards, you would add to your database query `'archived': true`.

**Comment by Sebastian-PR** [comment]
Hello together,

I am happy about that new feature. 
I don't know why, but at my system I have no content at "MyCards".
I checked:
- Version -> is 4.70.0
- I have a lot of cards where I am member and which are assigned to me.
- The menu MyCards is visible
![grafik](https://user-images.githubusercontent.com/74703083/103625289-0e820980-4f3b-11eb-986d-cfa84a7eb937.png)

- I also checked the issue with the TemplateBoard -> but I did not 100% understand what I have to change. I think I have no TempateBoards created.
![grafik](https://user-images.githubusercontent.com/74703083/103625887-d7f8be80-4f3b-11eb-827a-138157a530d3.png)

I will be happy if you can give me some help to get MyCards running.

My System runs on our linux server with snap.

Thanks,
Sebastian

**Comment by xet7** [comment]
@Sebastian-PR 

At `My Cards` page, if you have a lot of cards, it may take some time for cards to load.

At `My Cards` page, at webbrowser please right click Inspect => Console, and copy all content like errors etc as a new comment to this issue. Thanks!

**Comment by xet7** [comment]
@Sebastian-PR 

Another trick is:

1. Open your biggest board(s) that has most of your cards where you are assigned or member. This will load those cards to your browserside minimongo, that is browserside database implemented in Javascript.
2. Then click `My Cards`, it should now show your cards.

**Comment by jrsupplee** [comment]
> @Sebastian-PR
> 
> Another trick is:
> 
>     1. Open your biggest board(s) that has most of your cards where you are assigned or member. This will load those cards to your browserside minimongo, that is browserside database implemented in Javascript.
> 
>     2. Then click `My Cards`, it should now show your cards.

If this works then I think the latest changes will fix the problem.  But it would be nice to see the errors from Inspect -> Console as @xet7 suggested.

**Comment by Sebastian-PR** [comment]
Thank you very much for the fast help.

Unfortunately none of the tips and tricks fix the problem. It looks like I have really no content
What I did:

1. I choose a Board with a lot of cards for me
2. I click on "my name" (right top corner) -> MyCards
3. same with different Boards

![grafik](https://user-images.githubusercontent.com/74703083/103699345-15446700-4fa3-11eb-913a-1e52167d8be2.png)

![grafik](https://user-images.githubusercontent.com/74703083/103700473-c8fa2680-4fa4-11eb-9f34-ced91d68905b.png)

**Comment by xet7** [comment]
Well, for a start I will release those changes from @jrsupplee . But if that does not help, I'll try some other way to fix this.

**Comment by jrsupplee** [comment]
@Sebastian-PR 

> ![grafik](https://user-images.githubusercontent.com/74703083/103699345-15446700-4fa3-11eb-913a-1e52167d8be2.png)

Can you send a screenshot of any errors in the _Konsole_ tab on the right?

**Comment by bronger** [comment]
This recently added feature is the reason why I finally decided for Wekan. Thank you, @jrsupplee! My use case: I need to have _private_ cards, only visible to me (e.g. personnel matters, being team lead). In Jira, you can set visibility per card. In Wekan, you need to create an extra board for this. This is sub-optimal, but the “My Cards” feature ameliorates the situation.

However, “My Cards” is one-dimensional. Having lists as columns would increase clarity and decrease scrolling.

**Comment by xet7** [comment]
@jrsupplee do you have time to try to change lists as columns? That could be added somewhere near here:
https://github.com/wekan/wekan/blob/master/client/components/main/myCards.jade#L23
https://github.com/wekan/wekan/blob/master/client/components/main/myCards.styl

If @jrsupplee does have time, anyone else can add pull request, or I can look at it.

**Comment by xet7** [comment]
Yes, all thanks to @jrsupplee . Because he needed this feature, and did see it's low priority on my Roadmap, @jrsupplee did take the time to read Wekan code and submitted pull requests for this new feature. Anyone, who has free time and has programmed in any programming language, has the required skills to implement new features.

Wekan uses Jade templates https://github.com/mquandalle/meteor-jade that are converted to HTML. .styl files are Stylus that is similar to CSS, with some additionan programming logic.

**Comment by jrsupplee** [comment]
@bronger 

> However, “My Cards” is one-dimensional. Having lists as columns would increase clarity and decrease scrolling.

I have modified it to show lists horizontally within swimlanes.

I will try to commit this code soon.

**Comment by kuchengrab** [comment]
Hello everyone,
in our coop we're introducing Wekan as a project management tool at the moment and _one_ of our users is running into the same issue that @Sebastian-PR described.
> I don't know why, but at my system I have no content at "MyCards".

The browser inspector console shows the following:
```
Exception in template helper: TypeError: Cannot read property '_id' of undefined
    at https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:112:14200
    at https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:584:391687
    at Array.forEach (<anonymous>)
    at s.forEach (https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:112:14118)
    at n.cardsFind (https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:584:391288)
    at https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:102:17259
    at https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:353:4800
    at Function.t._withTemplateInstanceFunc (https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:102:38048)
    at https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:353:4706
    at Object.p.call (https://board.example.tld/c7bc68187720057b4ac58333b710e7a259741fdd.js?meteor_js_resource=true:170:1933)
```
Hope that helps!

**Comment by jrsupplee** [comment]
@kuchengrab 

What version of wekan are you running?

**Comment by kuchengrab** [comment]
@jrsupplee sorry, should have included that information.

Wekan Version: 4.70.0
Meteor Version: 1.12
Node version: 12.20.1

Running on Cloudron / Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-129-generic x86_64)

**Comment by Sebastian-PR** [comment]
HEY,

with the new Version 4.71.0 I can see the MyCards with at trick:

1. got to "ALL Boards"
2. click User, right corner -> MyCards  -> 
3. then I still see "ALL Boards", but now I have a new Button on the left Top-Bar (By Due Date)
4. then I press By Due Date -> then no content is shown, but the Buttten "By DueDate" changed to "ByBoard"
5. press ByBoard -> then I can see all "MyCards"

At the moment the overview is not perfect, but it is a very helpful feature.

Best Regards
sebastian

**Comment by jrsupplee** [comment]
@kuchengrab 

Can you try 4.71.0 and send me any error messages in the inspection console?

**Comment by jrsupplee** [comment]
@Sebastian-PR 

> with the new Version 4.71.0 I can see the MyCards with at trick:
> 
>     1. got to "ALL Boards"
> 
>     2. click User, right corner -> MyCards  ->
> 
>     3. then I still see "ALL Boards", but now I have a new Button on the left Top-Bar (By Due Date)
> 
>     4. then I press By Due Date -> then no content is shown, but the Buttten "By DueDate" changed to "ByBoard"
> 
>     5. press ByBoard -> then I can see all "MyCards"
> 
> 
> At the moment the overview is not perfect, but it is a very helpful feature.
> 
> Best Regards
> sebastian

I need to see the error message(s) from the inspection console and/or a screenshot of what the display looks like.

**Comment by jrsupplee** [comment]
@xet7

Is it possible for a card to not have a board, swimlane, and/or list associated with it?  That is, could a card's `boardId`, `swimlaneId`, and/or `listId` ever be `null`?

**Comment by xet7** [comment]
@jrsupplee 

Maybe in theory, if:
- When creating card, if not all info is added to card, it could be a bug
- There are linked cards, template cards, etc, I have not yet checked

With [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup) it can be looked from database is something missing.

**Comment by xet7** [comment]
Also, sometime there was a bug, that some card was not visibe at Lists or Swimlane view. In that case, used had to move card to different place at Lists or Swimlane view, so after that card became visible in both view. This bug happened because when creating card info about List of Swimlane was not added. If I remember correctly, that bug has been fixed.

**Comment by Sebastian-PR** [comment]
@jrsupplee  when I press "ByDueDate" (issue 3 in my description)

I get the following Errors: (Before I have no errors, no warnings)

```
ERRORs:
Firefox can’t establish a connection to the server at ws://192.168.178.36:3001/wekan/sockjs/277/xe4_x9w3/websocket. 7a3c683aed9b31b8eea50b5f83ec6d4432d71455.js:122:23013
GEThttp://192.168.178.36:3001/apple-touch-icon.png
[HTTP/1.1 404 Not Found 0ms]

GEThttp://192.168.178.36:3001/favicon-16x16.png
[HTTP/1.1 404 Not Found 0ms]
```
When I press By Board:

```
ERRORs:
GEThttp://192.168.178.36:3001/apple-touch-icon.png
[HTTP/1.1 404 Not Found 0ms]

GEThttp://192.168.178.36:3001/favicon-16x16.png
[HTTP/1.1 404 Not Found 0ms]
```

I noticed, that I have 335 Warnings (by pressing "ByDueDate" or "ByBoard") "because the scheme does not match.
```
EXAMPLE:
Cookie “DW33c969b9e969dc85bde8a9cb25bef7e7” will be soon treated as cross-site cookie against “http://192.168.178.36:3001/wekan/sockjs/info?cb=2xno_o2f_g” because the scheme does not match. info
Cookie “coindexmenu_1299761755f0c34f5073ba” will be soon treated as cross-site cookie against “http://192.168.178.36:3001/wekan/sockjs/info?cb=2xno_o2f_g” because the scheme does not match. info
Cookie “csindexmenu_1299761755f0c34f5073ba” will be soon treated as cross-site cookie against “http://192.168.178.36:3001/wekan/sockjs/info?cb=2xno_o2f_g” because the scheme does not match. info
Cookie “DokuWiki” will be soon treated as cross-site cookie against “http://192.168.178.36:3001/wekan/sockjs/info?cb=2xno_o2f_g” because the scheme does not match. info
```

**Comment by xet7** [comment]
Huh? Does `My Boards` use cookies?

**Comment by kuchengrab** [comment]
> Can you try 4.71.0 and send me any error messages in the inspection console?

@jrsupplee can do that as soon as v4.71 is packaged for cloudron.

**Comment by jrsupplee** [comment]
@xet7

> Huh? Does `My Boards` use cookies?

No.

I think the problem with *My Cards* is a card with a `null` value for board, swimlane, or list.  I will try some things to test that.

**Comment by xet7** [comment]
@jrsupplee 

If you would like to have similar dropdown menu at `My Cards` like is `Swimlanes/Lists/Calendar`, you just at top of `Swimlanes/Lists/Calendar` popup right click Inspect, and look at that HTML/CSS values what is there. Then you search for that code:
```
cd wekan
./find.sh somevalue
```
And then you copy from `.jade/.js/.styl` code similarly to `My Cards` page dropdown. Translations of Popup title texts are at `wekan/i18n/en.i18n.json`. So when at `.jade` template is some popup, it triggers event in `.js` file for opening that popup.

**Comment by jrsupplee** [comment]
@xet7 
I had all the code.  Just was making one stupid mistake.  Figured it out and the new version has drop down menus.

**Comment by jrsupplee** [comment]
Some new updates to *My Cards* have been merged and a new release quickly made thanks to @xet7.

Anyone having problems should try 4.73 and let me know of any problems.

Also two other pages have been added: *Due Cards* and *Broken Cards*.
* *Due Cards* allows you to see incomplete cards with a *Due* date for just you or all users.
* *Broken Cards* lists cards that may have some problems.

**Comment by xet7** [comment]
@jrsupplee 

That's nice, but that `All Users` shows `My Cards` and `Due Cards` on all users private boards. Other users data should not be added to publications. That is like a security hole to see other users private cards.

While this is not fixed yet, I disabled my Wekan demo server.

Sorry, I did not look more closely before merging.

**Comment by kuchengrab** [comment]
> @kuchengrab
> 
> Can you try 4.71.0 and send me any error messages in the inspection console?

@jrsupplee 
now cloudron updated to 4.72.0 and I tried to reproduce your steps:
> 4. then I press By Due Date -> then no content is shown, but the button "By DueDate" changed to "ByBoard"
> 5. press ByBoard -> then I can see all "MyCards"

→ When I klicked the button I could not see all _MyCards_, but only one random card that was in an archived list. after deleting that list including the card from the archive, nothing was show in either _ByDueDate_ or  _ByBoard_.

 error message:

```
Exception in template helper: 
myBoards/<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:584:395741
forEach/<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:112:14200
forEach@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:112:14118
myBoards@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:584:395491
t/h._wrapCatchingExceptions/<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:17259
O/</<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:353:4800
e/t._withTemplateInstanceFunc@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:38048
O/<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:353:4706
p.call@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:170:1933
e/Template.myCards</</<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:584:378709
e/h.Each/</<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:28795
n/</<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:19108
e/t._withTemplateInstanceFunc@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:38048
n/<@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:19059
t/h._withCurrentView@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:23216
n@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:102:19007
_compute@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:74:2279
_recompute@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:74:2434
n/o._runFlush@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:74:3443
a@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:1:3087
EventListener.handleEvent*r@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:1:3133
@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:1:3398
@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:1:3408
@https://board.example.tld/f95885177e2317aa6889eb26afec962a089cdff1.js?meteor_js_resource=true:1:9502
```

**Comment by xet7** [comment]
I fixed that in newest Wekan v4.75.

> @jrsupplee
> 
> That's nice, but that `All Users` shows `My Cards` and `Due Cards` on all users private boards. Other users data should not be added to publications. That is like a security hole to see other users private cards.
> 
> While this is not fixed yet, I disabled my Wekan demo server.
> 
> Sorry, I did not look more closely before merging.

**Comment by Sebastian-PR** [comment]
with v4.75 it looks good.

MyCards now shows Cards in both Views "By Due Date" and "ByBoard".

I also checked "brocken cards" I think that was not the Problem. We have no Cards there.

Thanks for the update.

**Comment by jrsupplee** [comment]
If the `admin` user is not allowed to see all cards, who is?

**Comment by jrsupplee** [comment]
> @jrsupplee
> 
> That's nice, but that `All Users` shows `My Cards` and `Due Cards` on all users private boards. Other users data should not be added to publications. That is like a security hole to see other users private cards.
> 
> While this is not fixed yet, I disabled my Wekan demo server.
> 
> Sorry, I did not look more closely before merging.

This was because you were the `admin`.  A normal user would only be able to see his/her cards only

**Comment by xet7** [comment]
@jrsupplee 

I am admin at Wekan demo server, where Roadmap is. There are [mobile and desktop apps](https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix) for Wekan demo server. Problem was, at `All Users` I did see cards of other users private boards: When I clicked topmost card, it opened private board of other user, that had many due cards in some other language I do not understand.

From other users, I prefer to only see:
- Public boards, that are at User Settings / Public
- Due cards, that are from Public boards

Some use that Wekan demo server for teaching kanban study course, etc.

After my fixes in Wekan v4.75, at `All Users` I only see cards from other users Public boards, and my boards.

That Wekan demo server is running on bare metal server donated to Wekan development by [CNCF/Linux Foundation](https://blog.wekan.team/2019/06/wekan-on-raspi3-and-arm64-server-now-works-and-whats-next-with-cncf/). In that demo server, I have [this privacy policy](https://wekan.team/privacy/).

**Comment by johappel** [comment]
It would be nice if another small correction was included in the stylesheet:
Please set my-cards-list-wrapper "table-cell" instead of "inline-block"
```
.my-cards-list-wrapper {
    ...
    display: table-cell;
    ....
}
```

**Comment by jrsupplee** [comment]
@johappel 

> It would be nice if another small correction was included in the stylesheet:
> Please set my-cards-list-wrapper "table-cell" instead of "inline-block"
> 
> ```
> .my-cards-list-wrapper {
>     ...
>     display: table-cell;
>     ....
> }
> ```

Why do you prefer `table-cell`?

It creates problems with horizontal scrolling and breaks mobile display.

**Comment by johappel** [comment]
> Why do you prefer `table-cell`?
> 

'inlne block' drop cards to bottom:

![grafik](https://user-images.githubusercontent.com/307023/105558921-27970280-5d10-11eb-9551-4c8300d7db96.png)

table-cell displays the cards correkt

![grafik](https://user-images.githubusercontent.com/307023/105558986-4c8b7580-5d10-11eb-9d7d-77642a6df2bb.png)

**Comment by jrsupplee** [comment]
Try `inline-grid` and see if it does what you want.

**Comment by johappel** [comment]
> 
> 
> Try `inline-grid` and see if it does what you want.

Wonderful, that's what I was looking for. 
And `padding` can be dispensed with then as well
Sorry about the effort, @xet7. Can you change that?

```
.my-cards-list-wrapper {
    ...
    display: inline-grid;
     ....
    --> padding löschen
}
```

**Comment by xet7** [comment]
I added DUEbleed to Wekan CVE HoF https://wekan.github.io/hall-of-fame/

**Comment by jrsupplee** [comment]
> I added DUEbleed to Wekan CVE HoF https://wekan.github.io/hall-of-fame/

You might modify it to state that it occurred only for admins

**Comment by xet7** [comment]
@jrsupplee 

Thanks a lot ! I added clarification.

**Comment by FuXXz** [comment]
Can someone please explain to me what is wrong with "My Cards"?
I created 3 cards with 3 users. No Members, No Assignee, Requested by or Assigned by. But for all users, all cards are shown under My Cards. Xet7 said the cards are only visible if you are a member or assigned to cards?
Greetings

**Comment by xet7** [comment]
@jrsupplee Do you know? ^

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3687
