### ISSUE TITLE
Due Date always shines in red even if the End Date has already been set

### ISSUE THREAD

**Issue by viktorjamrich** [wekan/wekan#1668]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yep
* Wekan version: 1.02
* Operating System: Ubuntu 18.04 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker-compose
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache2 proxy

**Issue description**:

If I set a Due Date on a card and it becomes overdue, it shines in red.

But when I finish the task and set the End Date, thus marking it as complete,
the Due Date still shines in red and distracts me.

It would be great if, once the End Date is set, the card is considered as Completed
and thus the Due Date (when overdue) would NOT be in red.

Attaching a screenshot:
![image](https://user-images.githubusercontent.com/32012857/40622634-d4d215fe-62a2-11e8-93d1-0aeee23abc4e.png)

**Comment by therampagerado** [comment]
When I think of it - it will be nice implementation! ;)

**Comment by d3dbit** [comment]
It will be nice feature.

**Comment by therampagerado** [comment]
This 'fix' brings bug with the yellow due date tag. Please address it when you have time. It's not showing anymore, just the red due tag shows now...

**Comment by saschafoerster** [comment]
@viktorjamrich @xet7 I think this issue can be closed. I tested the behavior with the newest version and for my everything seems logical. When after the due date, an end date is set. The due date get's grey.
