### ISSUE TITLE
How to add members to LB on a SandStorm server?

### ISSUE THREAD

**Issue by ksavoie** [wekan/wekan#167]
Am I missing something obvious?
Running a SandStorm server and for the life of me I can't figure out how to add members to a LB. I can share them with a users but that doesn't add them as a member that allows them to edit. Screen shots of LB show a 'add member' button within the interface but my install does not have this button.

Thanks for any assistance?

**Comment by ocdtrekkie** [comment]
I think if you use Sandstorm's Share link to create a sharing link, and a logged in use clicks it, they will be added to LibreBoard and be able to edit. But 0.9 will have more robust Sandstorm sharing support.

**Comment by ksavoie** [comment]
I would have thought such, but unfortunately this is not the case. 
Heard an ETA on 0.9?
Thanks

**Comment by ocdtrekkie** [comment]
@mquandalle Is still working to reimplement all of the 0.8 features in 0.9. It is apparently about a 70% rewrite of the entire application.

**Comment by ksavoie** [comment]
Wow, guess that's what you run into on a new evolving project. Does that mean that all the apps will need to be updated as well to operate with .9?

**Comment by ocdtrekkie** [comment]
70% rewrite of LibreBoard, not Sandstorm.

**Comment by ksavoie** [comment]
Ahhh, got it, sry for the confusion. 
Thanks.

**Comment by devon** [comment]
Any progress on this problem? Install latest sandstorm and wekan, cannot add member to board.

**Comment by mquandalle** [comment]
As sharing was actually implemented in Wekan v0.9, this issue is now fixed.
