### ISSUE TITLE
Feature Request: Date selection popup to be translatable, and Setting the time display in the 24-hour format

### ISSUE THREAD

**Issue by perchibald** [wekan/wekan#1670]
## Feature Request

**Server Setup Information**:

* Did you test in newest Wekan?:yes
* Wekan version:1.02
* Operating System: Debian 9
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):snap

**Feature description**:

![111](https://user-images.githubusercontent.com/847633/40648283-7c84e37c-6347-11e8-91fe-0d043b055429.png)

- Translation of the calendar into other languages.
- Setting the time display in the 24-hour format.

**Comment by therampagerado** [comment]
Currently the month names can't be translated but the time display is depending on the user browser local settings. If you're US standard you will see them with PM....

**Comment by perchibald** [comment]
ОК. 
- Translation of the calendar into other languages.
~~- Setting the time display in the 24-hour format.~~

**Comment by CWempe** [comment]
It would be nice to change `first day of week` in user or global settings.
As a german it is very irritating to see `Sunday` as `first day of week`.

Should I add a separate issue for this?

**Comment by MysterAitch** [comment]
Further to this, the `MM/DD/YYYY` date format is rather distracting. 

The ability to use `DD/MM/YYYY` or preferably `DD-MMM-YYYY` (or even ISO8601 `YYYY-MM-DD`) would be much appreciated.

**Comment by perchibald** [comment]
![изображение](https://user-images.githubusercontent.com/847633/230282848-01e27509-bc6b-418c-b123-05126fba301c.png)

![изображение](https://user-images.githubusercontent.com/847633/230282976-69ea6d6b-04cd-4f56-8865-4ad73dbc3e88.png)

- Setting the time display in the 24-hour format.
