### ISSUE TITLE
Feature Request: Order by date in a list or board

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1671]
It would be nice if we can automatically order cards in board or lists by due date.

This function can be added in each list hamburger menu and it should take into account the due date and time of each card and order them accordingly. The ones that need to be done sooner should be on top of the lists.

This will save lots of manual work on busy teams with more people than those who like to keep things organized...

**Comment by xet7** [comment]
Now there is filter by due date at current board https://github.com/wekan/wekan/pull/3731

Also there is:
- Click right top you username / Due Cards, shows due cards them from all boards
- Click right top you username / Search All Boards, can be searched with `due:`
