### ISSUE TITLE
Required server resources for 2000 users?

### ISSUE THREAD

**Issue by remraz** [wekan/wekan#1672]
## Issue

How many resources (CPU, RAM, HDD, bandwith, ... ?) a couple of thousand users in a professional environment being served WeKan would use ?

**Comment by xet7** [comment]
That would require more sponsors for scalability work, see my [Commercial Support](https://wekan.team), that would be much cheaper than paying for Trello for that amount of users. There is beginnings of [Roadmap for wekan.hx with frontend without javascript](https://github.com/wekan/wekan.hx/wiki/Roadmap), that would provide best scalability with least server resources required.

Current bugs in Node.js binary executeable and Meteor.js framework cause high CPU usage.

**Comment by therampagerado** [comment]
For me with 9 core cpu @2 ghz and 8 gb ram barely can handle the load of 10 users and 50 cards in the board and 1000 more in the recycle bin...

The usual load is ~1 1 1 but the system have to be restarted daily and sometimes even more...

**Comment by xet7** [comment]
Done and in progress performance improvements are listed in this blog post:
https://blog.wekan.team/2018/01/wekan-progress-on-x64-and-arm/index.html

Node and Meteor developers have bug fixing in progress, there is links to those issues in blog post.

**Comment by xet7** [comment]
@therampagerado 

Your main problem is those cards at recycle bin. Getting those deleted would help a lot.

**Comment by xet7** [comment]
There are still a lot of ways to improve performance in current version of Wekan.

**Comment by d3dbit** [comment]
Hello @xet7 ,
_"Your main problem is those cards at recycle bin. Getting those deleted would help a lot"_
Sorry. I don't understand. I thought that if I move some cards and/or lists to "recycle bin" I will improve the performance. In fact, I am doing that. Could you explain it?
Thanks.

Note: if I try to filter by my cards, the performance improve a lot.

**Comment by therampagerado** [comment]
When you send some card in the bin it simply hides from the board but it's still sitting in the DB. So I doubt there is significant performance gain if any.

I started deleting old cards that we don't need. For now it's OK but with time if Wekan gets more filtering and search options we might need to keep the cards as order history. For now we use separate system that was in place when I went to this job.

**Comment by d3dbit** [comment]
Hello @therampagerado ,
We (My team and I) are working only in one big board and we need to have access to the old cards (we cannot delete them).
Instead of moving the old cards to the recycle bin if we try to move them to another board we will improve the performance of our Wekan environment? Or the performance will be the same as moving them to recycle bin?
Thanks.

**Comment by xet7** [comment]
@d3dbit 

It's better to move old cards to another board.

**Comment by xet7** [comment]
@d3dbit 

If you use Standalone Wekan, you can export board that has old cards to JSON file, move board to recycle bin, and delete board from recycle bin. If you sometime need old cards back, you can import JSON file.

**Comment by d3dbit** [comment]
@xet7 OK thanks. Then I will try it:

_"...It's better to move old cards to another board..."_ and _"...you can export board that has old cards to JSON file, move board to recycle bin, and delete board from recycle bin. If you sometime need old cards back, you can import JSON file..."_

**Comment by d3dbit** [comment]
@xet7 ,
Great! I tried your advice: _"...It's better to move old cards to another board..."_ and the wekan-app performance improved a lot. I recommend everyone to do it.
Thanks!

**Comment by rjevnikar** [comment]
To get around the issue of too many cards, could a board's recycle bin actually be a separate board?

**Comment by xet7** [comment]
@rjevnikar 

It's already possible to move cards to another board. Although, there is not yet feature to move list to another board, or move recycle bin content to another board.

It would also help if someone can add/fix feature to empty recycle bin #1625

**Comment by xet7** [comment]
There are 2 recycle bins that would need adding/fixing: on All Boards page Board - Recycle Bin, and on single board page card/swimlane/etc Recycle Bin.

**Comment by xet7** [comment]
Please test newest Wekan v1.39. There has been speedups in Wekan v1.37 and v1.38. CPU usage also seems to be lower.
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md

**Comment by xet7** [comment]
Moved to here from #1870

From @a5dev 

- Did you test in newest Wekan?: Yes

I have Wekan set to auto update and it’s using the latest build. When we test it with only about 12-15 users, Wekan will become unresponsive. At first we thought the workstations needed more RAM (thinking since it is a JS app all of the work was offloaded to the clients). But that did not resolve the issue.

Next we bumped up the Wekan VM to 4 processors and 24gb of RAM. Tested again but it still crashes/becomes unresponsive after using for only 10 minutes.

The latest thing we noticed was that in linux (the wekan server), the Node process is running up to 100%. Is there a way to optimize node or make a node cluster? Or is there a parameter in the Wekan config that needs to be changed?

Wondering how other organizations are able to use Wekan.

**Comment by xet7** [comment]
For latest Wekan some user reported that adding index to MongoDB did return CPU usage to normal. But that can depend on server configuration.

For fast single CPU core usage, at AWS C4 instance type has most raw CPU power, according to this:
https://forums.aws.amazon.com/thread.jspa?threadID=229648

For cheap dedicated servers, for example there is Hetzner:
https://www.hetzner.com/?country=en

At AWS, it's possible to setup for example ECS cluster:
https://github.com/wekan/wekan/wiki/AWS

And I do plan to make it possible to move files outside of MongoDB #142 

For MongoDB, there is issue about adding index to Wekan #1709 , that could probably help too.

I welcome any help with testing and debugging performance.

**Comment by xet7** [comment]
Moved to #1600
