### ISSUE TITLE
Can not set received and end date in cards

### ISSUE THREAD

**Issue by QWERTYman2020** [wekan/wekan#1674]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:
* Wekan version: v1.02
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): virtual appliance via virtualbox
* ROOT_URL environment variable : https://192.168.1.13:80

**problem description**:
edge-case bug where if you try to set the start or end date cards it says the date is invalid(even though it was formatted that way by picking from the calender)
problem went away after reboot.
reason(s) why it appeared are unclear.

**logs**:
log file is empty.

**Comment by xet7** [comment]
@QWERTYman2020 

What language you use in browser setting and in Wekan?

Try some of these
- 30/05/2018 11.00 A
- 30/05/2018 11.00 AM
- 30/05/2018 11:00
- 30/05/2018 11:00 A
- 30/05/2018 11:00 AM
- 05/30/2018 11.00 A

etc

**Comment by QWERTYman2020** [comment]
browser was on the dutch host machine.
on reboot i visited with my english chrome and the dutch host machine, issue was gone.
I can't replicate it.

**i tested:**
- 30/05/2018 11:00 [A/Nothing]
- 05/30/2018 11:00 [A/Nothing]

both did not work.
