### ISSUE TITLE
Missing Field after DB updated to Wekan 1.02

### ISSUE THREAD

**Issue by john-pallissard** [wekan/wekan#1675]
![wekan-issue](https://user-images.githubusercontent.com/37344546/40789985-59cba2a8-64b9-11e8-8e17-4bd310f75731.gif)
boardView field not moved from board to users | profile Object during database upgrade from older version

Problem upgrading from  .77.0 to 1.02

* Operating System: Ubuntu 14.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Node Version: 4.x
* MongoDB Version: 3.2.20
* ROOT_URL environment variable http://127.0.0.1 :80

Ran Mongodump from v.77
Imported data to new new Wekan v1.02 install using Mongorestore

logged in with no issue.  on board view list/swimlane link showed undefined [Image attached]

was able to manually correct by adding boardView : "board-view-lists"
to the user => profile object for all users

**Comment by xet7** [comment]
Please somebody add pull request to migrations:
https://github.com/wekan/wekan/blob/devel/server/migrations.js
