### ISSUE TITLE
Matomo tracker integration ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan#1677]
Hello,

I would like to integrate a Matomo tracker in Wekan in order to have usage stats ?
Is it possible with a docker installation ? (or should it be developed first by the project ?)

Thank you for your help.
Regards.

**Comment by xet7** [comment]
@GuiGuiSoft 

First look does Winston logger etc existing stats features work:
https://github.com/wekan/wekan/wiki/Features#stats

**Comment by GuiGuiSoft** [comment]
Hello,

Here is a first suggestion of expected behavior. **The main purpose of this feature is to [integrate Matomo](https://developer.matomo.org/guides/tracking-javascript-guide) in Wekan.**

## Admin panel

A section "Matomo" is available (below Registration, Email, Accounts and Announcement). It contains the following parameters:
 - Enable Matomo tracking [Checkbox, _if true: all settings below are enabled/displayed_]
 - Tracking site URL [string, _example: matomo.blabla.com_]
 - Site ID [integer, _example: 12_]
 - Respect "Do Not track" [Checkbox, see DoNotTrack in [Matomo API Reference](https://developer.matomo.org/api-reference/tracking-javascript)]
 - Use user ID [Checkbox, see the [UserID documentation page](https://matomo.org/docs/user-id/)]

## Detailed actions recording

In a second phase it could be interesting to enable a detailed actions recording directly in Piwik to have similar stats as mentioned above by you, @xet7 . _However I do not know enough the Wekan operation to suggest something here._

Regards.

**Comment by Akuket** [comment]
I started working on it, but the piwik.js script that comes from the server where Matomo is located can't be loaded because of the content security policy.

**Comment by xet7** [comment]
This is already in Wekan since [Wekan v1.22](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v122-2018-07-30-wekan-release), and some fixes have been added after it.

Snap:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

Docker:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml#L125-L135

Source:
https://github.com/wekan/wekan-maintainer/blob/master/virtualbox/start-wekan.sh#L19-L27
