### ISSUE TITLE
Feature Request: Backup MongoDB with cron

### ISSUE THREAD

**Issue by florianproxi** [wekan/wekan#1678]
Dear,

I have installed Wekan with Docker on Ubuntu 16.
I can create a backup by following the tutorial (https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data).

But what I would like is to be able to launch a backup via a CRON every hour so that I can recover them via SyncBackPro in ftp.

I have tested this goal the copy into / var / www / backups / backup_quotidien not working ...

exec wekan-db / bin / sh -c docker "cd /; mongodump -o / dump /; docker cp wekan-db: / dump / var / www / backups / backup_quotidien"

Thanks !

**Comment by xet7** [comment]
@florianproxi 

That is more of bash / cron question than Wekan question.

You can look at this bash example:
https://github.com/xet7/admin-scripts/blob/master/move-old-irclogs.sh

And this crontab page:
https://crontab.guru

After you have made backup script, you can add it to this wiki page directly:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

Thanks!

**Comment by DrGraypFroot** [comment]
Hi @xet7 and @florianproxi

I wrote a simple Python3-Script for Docker-Wekan that creates a mongodump, copies it to the host-system using a naming convention like: dump-wekan-timestamp.tar.gz and automatically deletes dumps older than specified amount of days.

Meant to be executed daily/nightly using cron.

I'd gladly share the script, but I'm not sure how/where to upload it (I have not much experience with github).

@xet7, maybe you can give me a hint

Cheers :-)

**Comment by xet7** [comment]
@DrGraypFroot 

You can add it directly to this wiki page:
https://github.com/wekan/wekan/wiki/Backup

Thanks!

**Comment by DrGraypFroot** [comment]
@florianproxi @xet7 

I uploaded the script on the wiki page:
https://github.com/wekan/wekan/wiki/Backup#python-backup-script-for-wekan-docker-environment

Hope it helps :-)

**Comment by d3dbit** [comment]
@DrGraypFroot 
Very good job!!! Thanks a lot for your work. 

But one thing. If I am right, this script does not stop the wekan-app docker container before it does a mongodump. I think that it is better to stop the wekan-app before doing a mongodump. What do you think?
Thanks. It is a very nice python script.

**Comment by xet7** [comment]
Yes, someone could add these to scripts:

```
docker stop wekan-app

docker start wekan-app

sudo snap stop wekan.wekan

sudo snap start wekan.wekan
```

Thanks!

**Comment by xet7** [comment]
Various backup scripts are at https://github.com/wekan/wekan/wiki/Backup . If someone has improvements, please add new issue or pull request.
