### ISSUE TITLE
Link to other cards in description

### ISSUE THREAD

**Issue by johnnyasantoss** [wekan/wekan#1680]
## Feature request
Hello! I've been using wekan (in sandstorm.io) for a few weeks and I'm loving it! Thank you for making this wonderful software.
I'm missing one thing from Trello that I think we could do it better in wekan. From a card description I cannot paste a link to others cards and say something like: 
`This card depends on [this one](*imagine the url here*)`

Would be really nice if we could simply use `#` for example and get a suggestion for card names and get a decent card's title with link to it in the rendered text :smile: 

![Example](https://user-images.githubusercontent.com/14189387/41005604-9f88de70-68f4-11e8-9e76-19b5875364b2.png)
![Rendered example](https://user-images.githubusercontent.com/14189387/41005611-a60f8794-68f4-11e8-81a8-707dd4030ebb.png)

**Comment by xet7** [comment]
Wekan will have Linked Cards and Linked Boards feature, it's in progress https://github.com/wekan/wekan/pull/1592
