### ISSUE TITLE
Custom Fields: Can not remove from Overview

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#1683]
## Issue

I search after this issue but found nothing. Sorry when i dont miss it.

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.0.2
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: current Version
* MongoDB Version: current Version

**Problem description**:
Create an Custom Field (i think the type is here not relevant, but it was text with markdown and URL). Add this custom field to a card and add a value. Select know the option "Show this field on card"
Result: The field is know show
When know deselect the option "Show this field on card" the value is still showing on the card. After deleting the custom field the information is removed.
Expected Result: The custom field is no more on the card view

**Comment by feuerball11** [comment]
Knwon Problem. See #807 (At least i think it was once written there... At least i know this problem exists)
