### ISSUE TITLE
There is no the following path 【bundle/programs/server 】

### ISSUE THREAD

**Issue by PuShaoWei** [wekan/wekan#1684]
There is no the following path

I look at the [wiki](https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps) to manually install, found no this path

```
bundle/programs/server 
```

step 1
```
wget https://github.com/wekan/wekan/archive/v1.02.tar.gz
```
step 2
```
tar zxvf v1.02.tar.gz 
```
step 3
```
cd wekanv1.02
```

```
 ls ~/wekan/
app.env       config              fix-download-unicode  models             public                  scalingo.json   snap-src
app.json      CONTRIBUTING.md     i18n                  node_modules       README.md               server
CHANGELOG.md  docker-compose.yml  LICENSE               package.json       sandstorm.js            snap
client        Dockerfile          meta                  package-lock.json  sandstorm-pkgdef.capnp  snapcraft.yaml

```

**Comment by PuShaoWei** [comment]
@lichtamberg @xet7 @brylie @mmarschall @mmarschall @ForNeVeR @

**Comment by PuShaoWei** [comment]
Then I will perform the following command

```
npm install
audited 844 packages in 2.714s
found 0 vulnerabilities
```

**Comment by lichtamberg** [comment]
I'm not sure if I can follow.. Could you please also post the error messages which you receive?

**Comment by xet7** [comment]
@PuShaoWei 

If you are only installing Wekan, easiest way is to use Snap:
https://github.com/wekan/wekan-snap/wiki/Install

If you are developing feature or bugfix for Wekan, install from source instructions are here:
https://github.com/wekan/wekan/releases
