### ISSUE TITLE
Not able to create new labels, no "select color" option

### ISSUE THREAD

**Issue by pynting** [wekan/wekan#1687]
## I am not able to create a label, due to the color selector not showing up
Version
1.03.0~2018-06-08 hosted on oasis.sandstorm.io

No color picker in chrome or firefox... no color selected = no new label!

(PS: I was not able to type in text and record  the gif at the same time unfortunately, but the color picker does not show up when I write something in the text field)

![peek 11-06-2018 11-53](https://user-images.githubusercontent.com/40074168/41225137-6e385430-6d6e-11e8-919b-2f1dbca9837a.gif)
![peek 11-06-2018 11-52](https://user-images.githubusercontent.com/40074168/41225138-6e61e5ca-6d6e-11e8-85e5-827dba4d0091.gif)

**Comment by pynting** [comment]
Just to give an update, today I was able to create labels in Firefox 61.0, but not i Chromium 67.0.3396.79 in Wekan 1.07.0~2018-06-14 for Sandstorm.

**Comment by xet7** [comment]
Works in Wekan v1.39.0~2018-08-29 at Sandstorm, using Chrome on Linux.
