### ISSUE TITLE
1.04 - after update to this version the yellow due date warning is missing.

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1693]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: currently using
* Wekan version: 1.04
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): no
* Node Version: 8.11.1
* MongoDB Version: latest
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): no

**Problem description**:
- when I came to work today the kanban has updated to the latest as usual and the yellow due date warning is missing. They stay grey as those far in time. The red warning is here.

What can have caused this issue?

**Comment by xet7** [comment]
@therampagerado 

Maybe it's this in progress work https://github.com/wekan/wekan/pull/1685 by @rjevnikar 
I presume he will do more changes later.

**Comment by therampagerado** [comment]
OK but I can't see why you have to implement a broken fix when it's WIP... Please can you revert this in 1.05 and include it again when he's ready?

**Comment by xet7** [comment]
@therampagerado 

You can add pull request to change it.

BTW, Maybe I wrote wrong, @rjevnikar has name Rebecca in GitHub name, so could be she.

**Comment by rjevnikar** [comment]
Do you have an end date set?

**Comment by xet7** [comment]
@therampagerado 

Please read #1668 about what is currently in progress to be fixed.

**Comment by therampagerado** [comment]
@rjevnikar  - no I don't use end dates because I don't need them.

Until now we used only due date which was highlighting the more urgent orders nicely (sometimes strangely but ...). Now the ones with passed dates are red (as they were before) but those due 2 or less dates are no longer yellow, they stay grey and then turn red when the time passes.

**Comment by rjevnikar** [comment]
ok, that is because of the logic
`if ((this.now.get().diff(this.date.get(), 'days') >= 2) &&
       (this.date.get().isBefore(this.data().endAt)))
      classes += 'long-overdue';
    else if ((this.now.get().diff(this.date.get(), 'minute') >= 0) &&
       (this.date.get().isBefore(this.data().endAt)))
      classes += 'due';
    else if ((this.now.get().diff(this.date.get(), 'days') >= -1) &&
       (this.date.get().isBefore(this.data().endAt)))
      classes += 'almost-due';`

where classes are only added if it is before the end date
To fix, we need to test if there is an end date.

**Comment by therampagerado** [comment]
So now I have to add both due and end date in order to have them show as before? And both dates must be the same?

For me the end date must be fixed only when the actual work is done and then the needed behavior by you must be taken into force. Until the work is done the due date is the important.

**Comment by rjevnikar** [comment]
As the code is right now, you are correct. However, I agree, it needs to be fixed.
I can work on a fix soon.
