### ISSUE TITLE
Feature Request: CLI tool to convert between Standalone Wekan MongoDB database, and Sandstorm grain .zip file. (Was: Cards and lists disappeared after update in sandstorm.io)

### ISSUE THREAD

**Issue by oec** [wekan/wekan#1695]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:
yes
* Wekan version:
1.04.0~2018-06-12
* If this is about old version of Wekan, what upgrade problem you have?:
After the latest update of the sandstorm.io version of Wekan, one of  my grains did not list any of it lists anymore.  It only shows the top-bar and the side-bar which under "Activities" seems to list some/all? of the cards.  Also, no "+ Add list" button  appears in the main panel.
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
sandstorm
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Comment by xet7** [comment]
Ok, I'll try to fix it and make new release.

**Comment by xet7** [comment]
@oec 

I am unable to duplicate this on Sandstorm Wekan 1.04 locally and at Sandstorm.io . Wekan works for me: boards do open. Please give more details.

Try to export your data. Keep backups.

Sandstorm backup / restore. Note: Sandstorm has import "Board nor found" bug that is not fixed yet. So you need to modify MongoDB database and upload grain as .zip file, if you need it back.
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

Docker backup / restore:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

Snap backup / restore:
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore

**Comment by xet7** [comment]
There is also this report about upgrade problem, that I'm also unable to reproduce:
https://github.com/wekan/wekan/issues/1430#issuecomment-395984423

To fix a bug, I would need help to reproduce it.

**Comment by oec** [comment]
@xet7, it only happened to a grain that was probably open when Wekan was updated.  Maybe that is a clue?  I did experiment, both, with backup and export of the affected grain and then restored/imported it back, for no avail.  The logs are not helping to pin the issue down.

**Comment by xet7** [comment]
@oec 

What is "for no avail" ? Please add screenshots, copy logs from grain terminal to GitHub issue, etc.

**Comment by oec** [comment]
"for no avail":  1.) the restore of the backup of the affected grain did not solve the problem., 2.) import  of the exported board did not solve the problem (due to the "Board not found" issue).

Please find here the screenshot  of the current state of the affected grain:

![wekan-1](https://user-images.githubusercontent.com/200211/41353859-bd63633c-6f1d-11e8-80f4-352a2c4218cc.png)

Please find here the full log from the affected grain, taken from the backup .zip:

[log.txt](https://github.com/wekan/wekan/files/2098278/log.txt)

**Comment by xet7** [comment]
@oec 

You can try to import JSON to Standalone Wekan like snap:
https://github.com/wekan/wekan/releases

**Comment by oec** [comment]
Yes, that did work.  I started a snap-instance of wekan, imported the json-file, merged the users and the board looks correct.

Is there a way to properly import the json-file into the wekan-grain in sandstorm?

**Comment by xet7** [comment]
Only way currently is to stop snap MongoDB database, copy mongodb raw files to same directory as in unarcived Sandstorm grain backup .zip file, and upload that .zip file to Sandstorm. I have not tried it yet. At links above about Sandstorm and Snap is more details. I have not looked what board name needs to be at sandstorm - most likely it's "sandstorm".

**Comment by xet7** [comment]
At that Sandstorm link above you also see how to see database details with Robo 3T, what are the differences etc.

**Comment by xet7** [comment]
Hmm, actually this makes me think, maybe I could develop some command line utility to convert between Standalone Wekan MongoDB database, and Sandstorm grain .zip file. That's a workaround, but anyway.

**Comment by oec** [comment]
Such a tool would be helpful, indeed.

**Comment by xet7** [comment]
Moved to here from #1697

From @xistentialist 

## Issue

**Server Setup Information**:
Ubuntu 16.04.4

* Wekan version:
1.04.0~2018-06-12

* Operating System: 
Ubuntu 16.04.4
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Sandstorm

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*
Performed upgrade for wekan 1.04.0 via sandstorm.  The contents of the board are missing, but the activity feed shows recent activity

**Comment by xet7** [comment]
It would be helpful if someone could send me some Wekan grain backup .zip file to my email x@xet7.org , so I could see where these problems happen, and make a fix.

**Comment by oec** [comment]
The latest update (v1.07.0-2018-06-14) for sandstorm seems to have fixed the problem.  All grains that failed to show with v.1.04.0 are now displayed correctly!

Maybe it had to do with commit 454aa05 and migrations are now working properly for boards with cards containing checklists...!?  Anyways, I'm glad thtat the issue has been (dis)solved.

Thanks for all your work on Wekan!

PS: the import-export tool would still come handy :)

**Comment by xet7** [comment]
It is possible to repair MongoDB database this way, I added info today to here:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
