### ISSUE TITLE
Unable to see board contents after update

### ISSUE THREAD

**Issue by xistentialist** [wekan/wekan#1697]
## Issue

**Server Setup Information**:
Ubuntu 16.04.4

* Wekan version:
1.04.0~2018-06-12

* Operating System: 
Ubuntu 16.04.4
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Sandstorm

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*
Performed upgrade for wekan 1.04.0 via sandstorm.  The contents of the board are missing, but the activity feed shows recent activity

**Comment by xet7** [comment]
Moved to #1695

**Comment by zypA13510** [comment]
@xet7 you mean #1694?
