### ISSUE TITLE
Request to be a Contributor 

### ISSUE THREAD

**Issue by rwatts3** [wekan/wekan#170]
Greetings, 

I have read through a few issues about this project. 
I would like to contribute and become apart of the team to help with building the project. 
I believe and support an open source Kanban solution and would be happy to contribute. 
Thank you , 

Ryan.

**Comment by mquandalle** [comment]
You can know contribute by discussing on [the forum](http://discuss.wekan.io) or sending a Pull Request here on GitHub :)
