### ISSUE TITLE
Board with removed custom fields not loading in 1.07

### ISSUE THREAD

**Issue by zypA13510** [wekan/wekan#1703]
## Issue

**Server Setup Information**: 

* Did you test in newest Wekan?: yes
* Wekan version: 1.07
* Operating System: CentOS 7 3.10.0-862.el7.x86_64
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): no
* Node Version: v8.11.1
* MongoDB Version: ?? (the one supplied by snap)
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://<intranet.address>/wekan

**Problem description**:
So I updated to 1.07 to mitigate issue #1694. Despite that access to other boards are restored, one board is still not loading correctly. The only particularity I can think of right now is that the board has cards with custom fields. (I will add more details later. If anyone is able to reproduce this in the meanwhile, please add more details.)

**Comment by Fran-KTA** [comment]
Same here :)

v1.05 suffers from the same (tried both), so I went back to v1.04 + manual fix.

Did some tests... and it would seem to me that a lot more exceptions show up in browser console for 1.05 and, in particular, this comes from accessing the board that doesn't show up (and the others don't throw this one AFAIK):

Exception from Tracker recompute function:
8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:1:6261
Error: cannot call methods on draggable prior to initialization; attempted to call method 'option'
8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:1:6261

I tried disabling the "show on minicard" toggle for custom fields via database, but didn't work.

Cheers!

**Comment by feuerball11** [comment]
I'm not able to reproduce anything of this by myself.
@Fran-KTA but if your working in the database already, could you may give me a json with the board data, and maybe the custom field data? Think that could help finding the problem

**Comment by Fran-KTA** [comment]
Hi there, @feuerball11! Actually, I can't share JSON exports of our board, but I found out that the board rendering goes further if accessed via the adaptive view in Chrome simulating a mobile device...

On the other hand, I set up a new docker container with its own virtual_host for not disrupting the running v1.04 one and have been trying to reproduce the issue with other board without success. 

However, in browser console while in standard view, I get this message when accesing the affected board (don't know if helps):

```
TypeError: this.find(...) is undefined[Saber más] 8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:295:271692
calculateNextPeak 				https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:295:271692
onCreated/</< 					https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:295:17967
_process_ready/</<				https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:53972
_runAfterUpdateCallbacks/< 			https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:51902
forEach 					self-hosted:261:13
A.forEach 					https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:23:852
_runAfterUpdateCallbacks 			https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:51881
_performWrites 					https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:51745
_flushBufferedWrites 				https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:51287
_livedata_data 					https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:51034
e.connection._livedata_data 			https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:243:5455
o 						https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:40226
_launchConnection/t.socket.onmessage/< 		https://testwekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:33254
forEach 					self-hosted:261:13
A.forEach 					https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:23:852
_launchConnection/t.socket.onmessage 		https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:33210
sockjs-0.3.4.js/k</o.prototype.dispatchEvent 	https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:1440
sockjs-0.3.4.js/k</O.prototype._dispatchMessage	https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:15122
sockjs-0.3.4.js/k</O.prototype._didMessage 	https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:16019
sockjs-0.3.4.js/k</O.websocket/o.ws.onmessage 	https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:77:18120
```


Cheers!

**Comment by feuerball11** [comment]
@Fran-KTA 
From what i was able to track down, this should be code used in cardDetails. 
I dont know why this is even a thing, becouse accesing a board shoudnt open up a card (or am i wrong here?) 
Maybe something is wrong in the swimline code of listsGroup or swimline. 
But even then its kinda strange, becouse it says that thsi.find() is undefined... But thats a meteor function, it never shoud be undefined...

Sounds like a realy strange bug, some race condition or something....

And becouse i'm not able to reproduce this, i cant investigate this. My only idea whould be to add an 
if (!this || !this.find) return; 
to line 10 in cardDetails.js, and hope for the best. (so that the creation process of th eboard dont stops, and it hopfully gets everything correct together)

**Comment by sfahrenholz** [comment]
We have the same problem (ubuntu with snap installation). i have exported the not working board and in the json file i the something stranges..
``{
			"_id": "vv3ivXudncfohiMWs",
			"title": "ANOMYSATION TITEL",
			"members": ["yW2H67BBPY289BYPL"],
			"labelIds": ["L3YzGC"],
			"customFields": [{
					"_id": "FJkHApngsmAb8Es6f",
					"value": "[URL_TITEL](URL_URL)"
				}, {
					"_id": "mukxeKGQ9Nmv9dvbf",
					"value": "[URL_TITEL](URL_URL)"
				}, {
					"_id": "3KY4WMbqXXYXkXMkx",
					"value": "{OTHER CUSTOM FIELD}"
				}
			],
			"listId": "BTrbrLwPN2KWmcSsC",
			"sort": 3,
			"swimlaneId": "KPpY9Q784gsX62tRk",
			"archived": false,
			"createdAt": "2018-05-29T12:36:16.344Z",
			"dateLastActivity": "2018-06-08T13:16:37.150Z",
			"isOvertime": false,
			"userId": "mCnoBNjwjEa65sTdG",
			"requestedBy": "",
			"assignedBy": ""
		}
``

one of the custom field has a duplicated entry and the json file cannot be imported to wekan...

**Comment by sfahrenholz** [comment]
@feuerball11 
i have an exported json file from a not working board.. but the imported doesnt work by me.
Maybe you find a solution

[wekan.txt](https://github.com/wekan/wekan/files/2106761/wekan.txt)

**Comment by xet7** [comment]
@sfahrenholz 

When I tried that board here:
https://jsonlint.com

There was this error about special characters in title:
```
"title": "m8ußcr2t8ußmc42t	",
```
But there could still be some other errors also.

**Comment by sfahrenholz** [comment]
@xet7 
Sorry, this is a mistake by my anonymise . i have currently no php server, so i edit in notepad++
the updated file..
[wekan.txt](https://github.com/wekan/wekan/files/2106830/wekan.txt)

**Comment by sfahrenholz** [comment]
@feuerball11
"_id": "s33cGi", "name": "Patch", "color": "Label 7"
This is my anomization mistake, color is here "black" i just wanted to scrumble the tag "name"..

to these cards i can only say: on the board they have only one label. i dont know where the NULL values come. Maybe a label was removed and another added.. Sorry that I can say so little about it.

**Comment by feuerball11** [comment]
Thats good enough. I have all infos i needes. Now i can look into the export code

Am 16. Juni 2018 14:35:33 MESZ schrieb sfahrenholz <notifications@github.com>:
>@feuerball11
>"_id": "s33cGi", "name": "Patch", "color": "Label 7"
>This is my anomization mistake, color is here "black" i just wanted to
>scrumble the tag "name"..
>
>to these cards i can only say: on the board they have only one label. i
>dont know where the NULL values come. Maybe a label was removed and
>another added.. Sorry that I can say so little about it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/wekan/wekan/issues/1703#issuecomment-397809393

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by sfahrenholz** [comment]
Thank you very much!

maybe the NULL values can be also the problem about the visibility of the board..  But do not know if this has an impact on the presentation. Maybe it's worth taking a look at the code here..

**Comment by Fran-KTA** [comment]
Hi! Sry, haven't been able to play around with our wekan 1.07 testing container (1.04 works fine with that typo corrected via sed).

I haven't been able to reproduce the behaviour in other board so far... Also, our cards do not have null labelId that I could find in our database.

On the other hand, this is an exception message appearing before the "this.find(...) is undefined" error reported earlier, FWIW:

```
Exception from Tracker recompute function:	8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:1:6261

TypeError: a is undefined	8833bc7d825b6ddb52d7912570a5f00bac83cb78.js:1:6261

customFieldsWD/<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:295:398723
customFieldsWD@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:295:398641
f.View.prototype.lookup/<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:33292
p.call@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:123:1926
template.minicard.js/Template.minicard</<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:295:114571
f.Each/</<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:28635
n/</<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:19013
e._withTemplateInstanceFunc@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:37698
n/<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:18956
f._withCurrentView@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:23097
n@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:18914
e.Computation.prototype._compute@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:2301
e.Computation@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:1263
e.autorun@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:4233
f.View.prototype.autorun@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:19093
f.Each/<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:28608
n@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:20384
e.nonreactive@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:4414
f._fireCallbacks/<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:20299
f._withCurrentView@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:23097
f._fireCallbacks@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:20267
f._createView@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:20568
f._materializeView@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:20951
e@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:15576
f._materializeDOM@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:14811
f._materializeDOM@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:14847
t@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:21171
e.nonreactive@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:4414
t@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:21138
n/</<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:19013
e._withTemplateInstanceFunc@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:37698
n/<@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:18956
f._withCurrentView@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:23097
n@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:59:18914
e.Computation.prototype._compute@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:2301
e.Computation.prototype._recompute@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:2542
e._runFlush@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:21:3718
e@https://test.wekan/8833bc7d825b6ddb52d7912570a5f00bac83cb78.js?meteor_js_resource=true:1:2469
```

At some point I'd like to try export/imnport into another database... 

Thanks for your support! Cheers!

**Comment by Fran-KTA** [comment]
Hi! Managed some minutes for a pending test.

Duplicated the database and connected the wekanapp test container to a new dbtest container. 

Since I tried to move the board to recycle bin (worked) and delete (this doesn't, though) without success, I manually deleted the board, cards, checklists, checklistitems, comments, customfields, etc. from the database.

Exported the board from real DB on v1.04 and imported the JSON on v1.07-test. The process ended with that "400" on a yellow box and the board was triplicated, but all three copies of the board are accessible.

:-/

Thanks! Cheers!

**Comment by Fran-KTA** [comment]
Sure, just noticed that while going through these little tests.

Now... I noticed something on the imported copies of the board, the customFields were stripped from the board and their references from the cards.

Went back to initial test-db state and deleted customFields. Board was still not accessible, updated all cards from that board with $unset: {customFields:""} and board showed up on v1.07.

Finally... I noticed there were 4 cards which referenced a non-existing custom field. A first version of a dropdown type custom field that was deleted and replaced at early stages of the board's life, most probably.

```
> db.cards.find({boardId:"qKWyrbASWkthj3pWo","customFields._id":"LMsLX4pQxwkMnjQPZ"},{customFields:1})
{ "_id" : "84K7gKGhkEJ2mAzqR", "customFields" : [ { "_id" : "LMsLX4pQxwkMnjQPZ", "value" : "QLrWPk" }, { "_id" : "ktY8vDRMxj2Yezo4o", "value" : "WpJQtE" } ] }
{ "_id" : "3KMfHrQQRxBttsqDt", "customFields" : [ { "_id" : "LMsLX4pQxwkMnjQPZ", "value" : "QLrWPk" }, { "_id" : "ktY8vDRMxj2Yezo4o", "value" : "WpJQtE" }, { "_id" : "vPraAAx9fEWpqzq2Y", "value" : 15 } ] }
{ "_id" : "6z9dahsMLZanbxK32", "customFields" : [ { "_id" : "LMsLX4pQxwkMnjQPZ", "value" : "QLrWPk" }, { "_id" : "ktY8vDRMxj2Yezo4o", "value" : "WpJQtE" }, { "_id" : "vPraAAx9fEWpqzq2Y", "value" : 60 } ] }
{ "_id" : "pkRnyqs3RMdz5YzWa", "customFields" : [ { "_id" : "LMsLX4pQxwkMnjQPZ", "value" : "QLrWPk" } ] }
> db.customFields.find()
{ "_id" : "vPraAAx9fEWpqzq2Y", "boardId" : "qKWyrbASWkthj3pWo", "name" : "Time Spent (minutes)", "type" : "number", "settings" : {  }, "showOnCard" : true }
{ "_id" : "ktY8vDRMxj2Yezo4o", "boardId" : "qKWyrbASWkthj3pWo", "name" : "Requestor", "type" : "dropdown", "settings" : { "dropdownItems" : [ <ELEMENTS> ] }, "showOnCard" : false }
```
So dropped those references and, happily, board shows up in v1.07.

```
db.cards.updateMany({boardId:"qKWyrbASWkthj3pWo","customFields._id":"LMsLX4pQxwkMnjQPZ"},{$unset:{customFields:{ "_id" : "LMsLX4pQxwkMnjQPZ", "value" : "QLrWPk"} } })
{ "acknowledged" : true, "matchedCount" : 4, "modifiedCount" : 4 }
```
Thanks! Cheers!

**Comment by zypA13510** [comment]
Indeed, when I run the check, I do find some cards with non-existent custom fields.

But the drop script does not work?
```
> db.cards.updateMany({boardId:"_________________","customFields._id":"_________________"},{$unset:{customFields:{ "_id" : "_________________", "value" : "______"} } })
TypeError: Property 'updateMany' of object wekan.cards is not a function
```

Anyway, I think the steps to reproduce may be (haven't got the chance to test this myself, so not 100% sure):
1. Install Wekan v1.03
2. Create a new board
3. In the new board, create some custom fields.
4. Create some cards with the custom fields created in step 3 added.
5. Delete some of the custom fields created in step 3.
6. Update to Wekan v1.04
7. Update to Wekan v1.07
8. Check if the board created in step 2 is still accessible.

**Comment by Fran-KTA** [comment]
Hi!

Sorry, @zypA13510, db.collection.updateMany() is MongoDB 3.20 onwards and your version may be older.

In that case, please, try:
```
db.cards.update( { boardId:"_________________","customFields._id":"_________________" } , { $unset:{customFields:{ "_id" : "_________________", "value" : "______"}  }  } , { "multi":true } )
```

Cheers!

**Comment by zypA13510** [comment]
According to #1725, seems like it doesn't have to upgrade from 1.03 to get the bug.
Reproduce with above step 2-5.

**Comment by LyR33x** [comment]
Same here, fresh grain created today and deleted custom fields makes the board inaccessible. So no upgrade needed.

**Comment by xet7** [comment]
Related log files at https://github.com/wekan/wekan/issues/1768#issue-340685092

**Comment by cannycartographer** [comment]
[In my case the exported json Is crashing my text editor and showing up as having one line that has over a million characters (it's an uploaded jpeg). ]

**Comment by xet7** [comment]
Please try with newest Wekan.
