### ISSUE TITLE
Feature Request: Export Board anonymise

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#1705]
In some cases (example for bugs) it is required to export the board for the deveolpers. Companys has sensitive informations in the board. So an anonymise export were nice

what should be anonymise?
- Board Settings
  - slug
  - title
- Cards
  - Title (json: title)
  - Description (json: description)
  - customFields (json: value)
- Users
  - Username (json: username)
  - profile
    - Fullname (json: fullname)
    - Initials (json: initials)
- Attachments
  - Name  (json: name  )
  - file (json: file) - This can replaced by the logo of wekan
- Check list Items and checklists
  - Title (json: title)
- Comments
  - Text (json: text)
- Llabels
  - Name(json: name)
- Activities > can be deleted

**Comment by xet7** [comment]
@sfahrenholz 

There is some PHP code to cleanup Recycle Bin of JSON exported file, it can be used as starting point to this by someone that would like to do anonymisation script:
https://github.com/wekan/wekan-cleanup/wiki/Empty-Recycle-Bin-from-exported-JSON-with-PHP

If someone does it, he/she can add it to new page to same cleanup wiki.
