### ISSUE TITLE
Cannot Importing Board, when labelIds has a NULL value

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#1706]
## Issue

**Server Setup Information**:

Testes on the Sandstorm Demo: oasis.sandstorm.io

* Did you test in newest Wekan?: yes
* Wekan version: 1.07
* Operating System: Sandstorm but i think snap-builds have the same problem

**Problem description**:
- I exported an Board from wekan, after this i try to importing this json file to the same wekan enviroment. After selecting the members/users i get following messages
"Your JSON data does not include the proper information in the correct format"

following syntax i the in the exporting json file
"labelIds": [null, "t732So"]
"labelIds": [null]

if i remove the the null in the labelIDs-List, the import is successful

[labeldIDsnull.txt](https://github.com/wekan/wekan/files/2107948/labeldIDsnull.txt)

Maybe other values have the same problem: i didnt testing it!

**Comment by sfahrenholz** [comment]
After some more tests, i think this issue is related to #1703 
I removed the NULL values from the labels, mapping the users to the demo user of sandstorm and the board is showing.

**Comment by feuerball11** [comment]
Damm. found that issue to late, i posted the same story to #1703 ^^ 
I,m looking into this later on.

**Comment by sfahrenholz** [comment]
No Problem :) @feuerball11 

here is my answer:

@feuerball11 
> "_id": "s33cGi", "name": "Patch", "color": "Label 7"
This is my anomization mistake, color is here "black" i just wanted to scrumble the tag "name"..

to these cards i can only say: on the board they have only one label. i dont know where the NULL values come. Maybe a label was removed and another added.. Sorry that I can say so little about it.

**Comment by xet7** [comment]
Moved to #1703
