### ISSUE TITLE
Feature Request: Option to show cards in modal popup like Trello

### ISSUE THREAD

**Issue by timjrobinson** [wekan/wekan#1708]
I've been using Wekan for a while and still don't like how when selecting a card it shows on the current page pushing other columns to the right.

I'd like the option of changing card display to appear as a popup modal like in Trello. 

Is this currently possible or are there any plugins or forks that have implemented this?

**Comment by xet7** [comment]
@timjrobinson 

Wekan is completely different code and graphics than Trello. Wekan does not have plugin system, everything is integrated, and enabled/disabled based on environment variables.

Changing that would require pull request that implements that change.

**Comment by xet7** [comment]
@timjrobinson 

Also, Wekan can not include any code and graphics from Trello, see info about old DMCA request:
https://github.com/wekan/wekan/wiki/FAQ#werent-you-called-libreboard-before
