### ISSUE TITLE
Tuto install 1.0X on ubuntu with nginx

### ISSUE THREAD

**Issue by florianproxi** [wekan/wekan#1716]
Hello, I am desperately looking for a tutorial to install Wekan 1.0X on Ubuntu with Nginx ... Any idea?

**Comment by xet7** [comment]
Install snap, have wekan and mongodb enabled, and caddy not enabled, and configure nginx.
https://github.com/wekan/wekan/releases

That link is Download button at wekan website https://wekan.github.io

**Comment by florianproxi** [comment]
Thanks @xet7 do you have example of nginx conf ?

**Comment by johnleeming** [comment]
I set up a very basic nginx http config then used Certbot to convert to https, worked beautifully

**Comment by florianproxi** [comment]
@johnleeming can you share it ?

**Comment by johnleeming** [comment]
this is it before certbot, hacked from another bit of software I'm running on the same server - Huginn,
`server {
  listen 0.0.0.0:80;
  listen [::]:80 ipv6only=on;
  server_name wekan.example.com; ## Replace this with your domain
  server_tokens off; ## Don't show the nginx version number, a security best practice

  ## Increase this if you want to upload large attachments
  client_max_body_size 20m;

  ## Individual nginx logs for this vhost
  access_log  /var/log/nginx/wekan_access.log;
  error_log   /var/log/nginx/wekan_error.log;

  location / {
        proxy_pass http://127.0.0.1:3003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
  }

  error_page 502 /502.html;
}
`

after Certbot does its thing it looks like this

`
## Normal HTTP host
server {
##  listen [::]:80 ipv6only=on;
  server_name wekan.example.com; ## Replace this with your domain throughout
  server_tokens off; ## Don't show the nginx version number, a security best practice

  ## Increase this if you want to upload large attachments
  client_max_body_size 20m;

  ## Individual nginx logs for this vhost
  access_log  /var/log/nginx/wekan_access.log;
  error_log   /var/log/nginx/wekan_error.log;

  location / {
        proxy_pass http://127.0.0.1:3003; ##3003 is the port for wekan
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
##        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
  }

  error_page 502 /502.html;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/wekan.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/wekan.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = wekan.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 0.0.0.0:80;
  server_name wekan.example.com;
    return 404; # managed by Certbot
`

**Comment by xet7** [comment]
Yes, link I gave on releases page included nginx example.

**Comment by florianproxi** [comment]
@johnleeming i just test your conf but nginx said : 

2018/06/19 17:35:15 [error] 28687#28687: *75 connect() failed (111: Connection refused) while connecting to upstream, client: 193.248.214.41, server: xxxx.domain.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3003/502.html", host: "xxxx.domain.com"

**Comment by johnleeming** [comment]
sorry - I'm afraid I don't know what that is due to.  For what it's worth
I'm running on an AWS microT2 with ubuntu 16.04 lts and an elastic IP
address

**Comment by florianproxi** [comment]
When i check status of snap.wekan.wekan it said :

 snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2018-06-19 17:57:55 CEST; 3s ago
  Process: 31029 ExecStart=/usr/bin/snap run wekan (code=exited, status=1/FAILURE)
 Main PID: 31029 (code=exited, status=1/FAILURE)

Jun 19 17:57:55 vps276073 systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, statu
Jun 19 17:57:55 vps276073 systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Jun 19 17:57:55 vps276073 systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
Jun 19 17:57:55 vps276073 systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling
Jun 19 17:57:55 vps276073 systemd[1]: Stopped Service for snap application wekan.wekan.
Jun 19 17:57:55 vps276073 systemd[1]: snap.wekan.wekan.service: Start request repeated too quickly.
Jun 19 17:57:55 vps276073 systemd[1]: Failed to start Service for snap application wekan.wekan.

**Comment by florianproxi** [comment]
It's working ! I removed snapd and purged it and reinstall it.

**Comment by xet7** [comment]
@florianproxi 

Please read all snap wiki pages:
https://github.com/wekan/wekan-snap/wiki

If you want to access mongodb on server, install MongoDB 3.2.x tools from www.mongodb.com for Ubuntu, and connect to database with cli:

```
mongo --port 27019
```

Some mongo commands are also explained at Docker backup wiki page:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

Info about snap is at https://snapcraft.io
