### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by TastyPlacement** [wekan/wekan#1719]
Wow, I have tried this 20 different ways and as far as I got was 502 Bad Gateway. I did see the registration page occassionally but if I try to use it, I click and then get 502 Bad Gateway. 

**Server Setup Information**:

We are on Centos 7, did mongodb and source method with node.js and nginx. 

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*
- *Explain steps how to reproduce*
- *Attach log files in .zip file)*

**Comment by xet7** [comment]
@TastyPlacement 

Try:

a) Snap
https://github.com/wekan/wekan-snap/wiki/Install

b) DockerBunker
https://github.com/chaosbunker/dockerbunker

**Comment by xet7** [comment]
But, if you are on OVH or OpenVZ servers, only building from source works:
https://github.com/wekan/wekan-maintainer/tree/master/virtualbox
