### ISSUE TITLE
Test in Openshift

### ISSUE THREAD

**Issue by Asgoret** [wekan/wekan#1721]
Hi @xet7!
I`m new in Github, so don`t be a lot of angry about wrong opening issue. I can test Wekan in Openshift Cluster. Is there some QA road-map?

**Comment by xet7** [comment]
@Asgoret 

Maybe Docker would work for OpenShift?
https://github.com/wekan/wekan-mongodb

Or some other platform?
https://github.com/wekan/wekan/releases

OpenShift is part of not tested platforms. If you get it running, please add new wiki page, and link to it:
https://github.com/wekan/wekan/wiki/Platforms#not-tested-yet

**Comment by xet7** [comment]
Moved to #182
