### ISSUE TITLE
Board with the deleted custom field does not open.

### ISSUE THREAD

**Issue by sjoki** [wekan/wekan#1725]
Hi!
I have a problem with custom field. Wekan 1.07. I do the following:
1. I create new board.
2. Add new card
3. Create custom filed
4. Add custom field to card
5. Delete custom field from board

After these actions, the board does not open.

**Comment by Fran-KTA** [comment]
Hi @sjoki, 

This would be related to issue #1703 I think...

Cheers!

**Comment by xet7** [comment]
Moved to #1703
