### ISSUE TITLE
[Question] What is the recommanded installation method ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan#1727]
Hello,

The installation wiki page recently changed. There are so many ways to install Wekan that I am quite lost so I prefer to ask : What the best way to install Wekan ? (Docker ? Snap ?...)

My main concerns :

- I use Ubuntu server 16.04 LTS
- I am looking for stability
- I am looking for security
- I don't want to install Sandstorm (only Wekan)

Regards.

**Comment by xet7** [comment]
Yes. I try to make install page more clear.
