### ISSUE TITLE
Unable to move card to different board

### ISSUE THREAD

**Issue by sorbet510** [wekan/wekan#1729]
For some reason, the drop down menu for moving cards is not populated with the other boards i have set up.  (I feel like there's some obvious error I'm making but I can't figure it out.)

The dropdown menu only lists "Current"

![screen shot 2018-06-26 at 1 43 09 pm](https://user-images.githubusercontent.com/40612742/41938198-4130adcc-7947-11e8-8bbc-87f41dd6abb4.png)

**Comment by xet7** [comment]
@sorbet510 

I do see all my boards in board menu in Snap Wekan 1.07.

```
$ sudo snap list
Name   Version  Rev   Tracking  Developer  Notes
core   16-2.33  4830  stable    canonical  core
wekan  1.07     213   stable    xet7       -
```

What Wekan version are you running?

**Comment by xet7** [comment]
This is on Ubuntu 18.04 64bit

**Comment by sorbet510** [comment]
hi @xet7 - thanks for your quick response.  I'm on 1.07 as well - using Wekan on Sandstorm. I do see my boards at the app level but they are not appearing in the drop down.  
![screen shot 2018-06-26 at 2 01 54 pm](https://user-images.githubusercontent.com/40612742/41939082-a1c37abe-7949-11e8-82da-d6acd3917104.png)

**Comment by ocdtrekkie** [comment]
@sorbet510 Each board on Sandstorm is a separate running copy of Wekan, which provides a significant additional layer of security. Unfortunately, it makes doing things like inter-board transfer fairly complicated, so it isn't possible right now.

**Comment by sorbet510** [comment]
Ahh ok, I thought that might be the case but wanted to confirm. Thank you @ocdtrekkie  @xet7

**Comment by ocdtrekkie** [comment]
It *is* technically possible to do it, I just don't want to get anyone's hopes up saying "it's coming", because it would require someone with good understanding of the internals of Sandstorm to spend a bunch of time working on Wekan code. And that's not likely anytime soon.
