### ISSUE TITLE
Private boards & organizations support

### ISSUE THREAD

**Issue by jindrichbartek** [wekan/wekan#173]
Hi, I'd like to ask - do you plan to support non-public boards? Especially only organizations visible boards?

**Comment by mquandalle** [comment]
Private boards are already implemented, they will only be accessible to boards members. Organizations doesn't exists yet, so that's the first thing to create to have “organizations visible boards”.

**Comment by aegrey** [comment]
+1 for organizations, if anyone is not actively developing this, I can fork & start.

**Comment by xet7** [comment]
Moved to #802
