### ISSUE TITLE
Board not loading in Sandstorm

### ISSUE THREAD

**Issue by sorbet510** [wekan/wekan#1733]
I'm new to Wekan/Sandstorm and added 3 boards yesterday - our main project board (which had at least 80 cards) and 2 smaller boards that I used to experiment with.

This morning, while I see all 3 boards listed as Grains, the large project board is completely blank, while the smaller boards load fine.

Is there a card limit with boards in Sandstorm?  
And is there a way I can recover the larger board?

Thanks in advance!

![screen shot 2018-06-27 at 9 33 41 am](https://user-images.githubusercontent.com/40612742/41987312-9e394b36-79ed-11e8-86c7-5bccfa480647.png)

**Comment by ocdtrekkie** [comment]
There's definitely no card limit, but I am quite curious what would be wrong here. Is there confidential information in this board you would be unable to send someone to test against? When the grain is open, there's a download button on the top bar to take a backup of the Sandstorm grain. It's likely your information is still there, but just cannot be viewed for some reason.

**Comment by xet7** [comment]
Yes you can recover data:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file
