### ISSUE TITLE
Feature Request: Translated Webhook

### ISSUE THREAD

**Issue by ghost** [wekan/wekan#1735]
Hello, i have configured outgoing webhook to send events to Mattermost. I have installed the french translate in my Wekan but the messages sent to Webhook are not translates.

Example : Florian Poisson moved "Attribution des invitations exposants pour Jackie" from "A faire" to "En cours"

How to translate them ?

Thanks !

**Comment by florianproxi** [comment]
Resolved by restart the snap service after upgrade.

**Comment by florianproxi** [comment]
Finally I reopen because it is still in English for the rest of the users while their interface is put in French. Bug?

**Comment by xet7** [comment]
I think there no translated webhooks feature yet.

**Comment by florianproxi** [comment]
It's translated only for my account....
