### ISSUE TITLE
Unable to install through Docker - "TypeError: Checklists.forEach is not a function" errors

### ISSUE THREAD

**Issue by kestrelhawk** [wekan/wekan#1736]
## Issue

**Server Setup Information**:
Windows for Docker through WSL
* Did you test in newest Wekan?:
* Wekan version:
v1.08; I've also attempted latest image `quay.io/wekan/wekan`. 
* Operating System:
Windows
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Docker
* MongoDB Version: 
3.2.20

Note: Using `wekan/wekan-mongodb` for docker-compose. 

**Problem description**:

I'm currently attempting to set up Wekan with Docker for Windows that's set up through WSL. The initial installation completes successfully; however, I'm experiencing issues with the `wekan-app` container, whereby it appears to be stuck on `node /build/main.js` and continuously restarts, as follows: 

```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                          PORTS                    NAMES
be0b6a41c867        quay.io/wekan/wekan   "node /build/main.js"    3 minutes ago       Restarting (1) 12 seconds ago                            wekan-app
fa0369aeae6c        mongo:3.2.20          "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes                    27017/tcp                wekan-db
```

When I start the container in foreground mode, I see the following errors reported repeatedly: 

```
wekan-app  | TypeError: Checklists.forEach is not a function
wekan-app  |     at Object.Migrations.add [as migrationCallback] (server/migrations.js:192:14)
wekan-app  |     at packages/idmontie_migrations.js:238:17
wekan-app  |     at Function.time (/build/programs/server/profile.js:309:28)
wekan-app  |     at /build/programs/server/boot.js:423:13
wekan-app  |     at /build/programs/server/boot.js:464:5
wekan-app  |     at Function.run (/build/programs/server/profile.js:510:12)
wekan-app  |     at /build/programs/server/boot.js:462:11
  ...
  ...
wekan-app  | > Starting add-checklist-items migration.
wekan-app  | /build/programs/server/node_modules/fibers/future.js:280
wekan-app  |                                            throw(ex);
wekan-app  |                                            ^
wekan-app  |
wekan-app  | TypeError: Checklists.forEach is not a function
wekan-app  |     at Object.Migrations.add [as migrationCallback] (server/migrations.js:192:14)
wekan-app  |     at packages/idmontie_migrations.js:238:17
wekan-app  |     at Function.time (/build/programs/server/profile.js:309:28)
wekan-app  |     at /build/programs/server/boot.js:423:13
wekan-app  |     at /build/programs/server/boot.js:464:5
wekan-app  |     at Function.run (/build/programs/server/profile.js:510:12)
wekan-app  |     at /build/programs/server/boot.js:462:11
  ...
  ...
```

The issue looks similar to issue https://github.com/wekan/wekan/issues/1576 which was recently reported and resolved. 

Thanks and please let me know if you require any further information.

**Comment by xet7** [comment]
Please try latest image v1.09

**Comment by xet7** [comment]
```
quay.io/wekan/wekan:v1.09
```
Or latest, currently only difference is changelog typo fix:
```
quay.io/wekan/wekan
```
Upgrading info for Docker:
https://github.com/wekan/wekan-mongodb#backup-before-upgrading

**Comment by kestrelhawk** [comment]
@xet7 Thanks for your reply. I've attempted v1.09 and the latest but the same error occurs. Just to note, this is a fresh install and not an upgrade.

**Comment by xet7** [comment]
@kestrelhawk 

Thanks ! I'll make new fixed Wekan v1.10 release soon.

**Comment by kestrelhawk** [comment]
@xet7 Nice one, thank you!

**Comment by xet7** [comment]
@kestrelhawk 

Please try this Docker image, is this fixed now:
```
image: quay.io/wekan/wekan:v1.10
```
