### ISSUE TITLE
Re-enabling bcrypt ?

### ISSUE THREAD

**Issue by jcabillot** [wekan/wekan#1743]
Hi,

In this commit (4b20102), you disabled bcrypt because of this issue (https://github.com/kelektiv/node.bcrypt.js/issues/604).
Now that is seem to be merged, will you revert this commit ?

Julien

**Comment by xet7** [comment]
@jcabillot 

How? What packages and to what version? I did not get it to work, so that `npm audit` would not show warning anymore.
