### ISSUE TITLE
Deleting cards, lists, boards?

### ISSUE THREAD

**Issue by ajjaic** [wekan/wekan#175]
Is it possible to delete lists and boards at the moment? There doesn't seem to be any UI provision to delete lists or boards. Although it seems possible to delete cards.

**Comment by ePirat** [comment]
In the current git master version this is not possible, as it is under heavy development due to UI redesign. I am not sure if this is a planned feature for the final version, but iirc this was possible in the 0.7 version, so it should come back.

**Comment by mquandalle** [comment]
Here is the current state of these things:

Action | in v0.8 | in `master` | in v0.9 (prevision) 
--------|-----------|---------------|------
Archive a card  | ✔ | ✔ | ✔
Restore a card  |   | ✔ | ✔
Delete a card   | ✔ | ✔ | ✔
Archive a list  | ✔ | ✔ | ✔
Restore a list  |   |   | ✔
Delete a list   |   |   | ✔
Archive a board | ✔ |   | ✔
Restore a board |   |   | ✔
Delete a board  |   |   | ✔

**Comment by mquandalle** [comment]
Here is an update on the current state of things. In the interest of ever releasing v0.9 I will probably postpone the remaining delete operations to a later release (BTW Trello doesn't have them as well).

Action | in v0.8 | in `master`
--------|-----------|---------------
Archive a card  | ✔ | ✔
Restore a card  |   | ✔
Delete a card   | ✔ | ✔
Archive a list  | ✔ | ✔
Restore a list  |   |  ✔
Delete a list   |   | 
Archive a board | ✔ | ✔
Restore a board |   |  ✔
Delete a board  |   |

**Comment by zeineath** [comment]
@mquandalle deleting a card doesn't seem to work (at least in chrome). FYI.

**Comment by mquandalle** [comment]
Closing as the possibility to archive solve the problem for most users, feel free to re-open a specific issue if you would like to have any specific non-implemented feature (like “delete a list”).

**Comment by danger89** [comment]
Yes I can delete a card, but it's pretty good hidden. And still I need to confirm it.
Why not drag & drop the card to some trash icon to remove it?

Now I need to click on the card, then the card options (another click), then More (-,- another click), finally a delete link. Ow noo.. then I need to click on "delete" again to confirm! Now its gone. Why is it so hard?

- Melroy

**Comment by genecraig** [comment]
Because like most programmers out there their ego (read "_exaggerated self-confidence in areas they have no professional experience in_") makes them think they can do UI/UX themselves rather than hire a professional. And we all suffer from it. Wekan is an ok project, but very deficient for its age and plagued with really simple problems that should have been ironed out much earlier on. Again, these would have been discovered had they also hired QA. This is the repeated downfall of many projects, perhaps in the area of 90% - refusal to hire QA and UI/UX professionals. But no one learns from anyone else' mistakes - and we ALL suffer, at least in wasting time finding out the project is garbage and will remain garbage longer than I have time to wait for.

**Comment by genecraig** [comment]
This project has been up here 2 years and we still cannot DELETE boards or lists. All programmers understand CRUD, the four most basic, elementary, and initial routines you create for your database. CREATE, RETRIEVE, UDPATE, and... you've got it... DELETE!!! It is as if they expect their product to only be used for a very short time and not very much. Why would you want to delete anything? You won't use it much anyway = their mentality. Please get with the 21st century. Add delete to the elements of the program. For heaven's sake! I have a trash bin sitting by my desk. I can throw anything I want in it and take out the trash. Give us the same with Boards and Lists.

**Comment by ocdtrekkie** [comment]
@genecraig Where do you think Wekan has the money to hire people? ...Under what do you even suspect Wekan has any money at all. Please stop trolling this project.

**Comment by genecraig** [comment]
@ocdtrekkie like any other project or startup, investments. Oh, that's right, that would require bringing a business professional onboard and programmers think they can do everything themselves. You have a startup and you don't have money, you get investments. This is the normal course of business around the world.

And don't be infantile by calling a person a troll for having an opinion.

**Comment by ocdtrekkie** [comment]
This isn't a startup. You seem to make the mistake of thinking this is a business. It is not. It's a charity for ungrateful people like you. :)
