### ISSUE TITLE
Error binding port '3001' with caddy-enabled 'true'

### ISSUE THREAD

**Issue by Asgoret** [wekan/wekan#1750]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.11.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node Version: 8.11.1
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): 127.0.0.1

**Problem description**:
If i put `caddy-enabled` in position `true` i catch this error:
```
 wekan.wekan[27969]: events.js:183
 wekan.wekan[27969]:       throw er; // Unhandled 'error' event
 wekan.wekan[27969]:       ^
 wekan.wekan[27969]: Error: listen EADDRINUSE 0.0.0.0:3001
 wekan.wekan[27969]:     at Object._errnoException (util.js:1022:11)
 wekan.wekan[27969]:     at _exceptionWithHostPort (util.js:1044:20)
 wekan.wekan[27969]:     at Server.setupListenHandle [as _listen2] (net.js:1367:14)
 wekan.wekan[27969]:     at listenInCluster (net.js:1408:12)
 wekan.wekan[27969]:     at doListen (net.js:1517:7)
 wekan.wekan[27969]:     at _combinedTickCallback (internal/process/next_tick.js:141:11)
 wekan.wekan[27969]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
 systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
 systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
 systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
 systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling restart.
 systemd[1]: Stopped Service for snap application wekan.wekan.
```
If i put `caddy-enabled` in position `false` all works fine with caddy proxy in front.

**Comment by xet7** [comment]
@Asgoret 

Did you reboot after installing Wekan? That is usually required.

Is something else using port 3001 ? You can check with:
```
sudo netstat -plant | grep :3001
```

Enabling Caddy requires Caddy to use ports 80 and 443. Do you have some other webserver running already?

Caddy usually proxies to Wekan port.

**Comment by Asgoret** [comment]
@xet7 
Before i change parametres i stop caddy and wekan.
And no. i haven`t got any web-servers on this PC.
I install Caddy via README.from systemd folder.

**Comment by xet7** [comment]
@Asgoret 

Please set ROOT_URL correctly to your server IP address or domain:
https://github.com/wekan/wekan/wiki/Settings
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
No reply received.

**Comment by Asgoret** [comment]
@xet7 Sorry for long response. At this moment ROOT_URL is 127.0.0.1

**Comment by xet7** [comment]
@Asgoret 

I already replied above how you should fix it.

**Comment by Asgoret** [comment]
@xet7 but it`s set correct on 127.0.0.1. I use Wekan and Caddy on local machine.
