### ISSUE TITLE
After migration: Can not reload cards in existing board

### ISSUE THREAD

**Issue by ghost** [wekan/wekan#1754]
## Issue

**Server Setup Information**:

* Current Wekan version: 1.18
* Previous Wekan version: 0.6
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker

**Problem description**:
Using browser refresh to reload a card from a _migrated board_ results in a blank screen. The console shows the following error:

```
Exception in defer callback: TypeError: Cannot read property 'username' of undefined
    at http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:299:232393
    at Array.map (<anonymous>)
    at f.View._render (http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:299:232336)
    at f.View.t (http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:59:21075)
    at http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:59:19015
    at Function.e._withTemplateInstanceFunc (http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:59:37698)
    at http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:59:18967
    at Object.f._withCurrentView (http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:59:23097)
    at n (http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:59:18916)
    at e.Computation._compute (http://somehost/67ccd18b44556b90039d718774cd94da19a0a513.js?meteor_js_resource=true:21:2311)
```

This problem only affects boards that existed prior to updating to 1.18. When I create a new board and a new card I can reload the card without problem.

**Steps to reproduce**
* Use Wekan 0.6
* Create a board and add a card
* Update to Wekan 1.18, migrate existing data
* Open a board, navigate to a card
* Refresh the browser page

**Comment by xet7** [comment]
Does exporting boards in Wekan 0.6 as Wekan JSON and importing to newest Wekan work?

**Comment by xet7** [comment]
If you have https in URL (for example with Nginx/Apache/Caddy), is https also in Wekan ROOT_URL ? If not, please add it, so it is real wekan URL.  See Settings:
https://github.com/wekan/wekan/wiki/Settings

**Comment by xet7** [comment]
@centigrade-thomas-becker 

What Wekan version you have? I don't see Wekan 0.6 [In ChangLog](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md)

**Comment by centigrade-kdk** [comment]
@xet7 
- We are now at V1.18 and come from v0.60
- Our ROOT_URL is correctly set (including the protocol)

I started to debug this and can tell you that this error only occurs on boards which I share with other members. I saw somewhere that there was a security issue related to fetching users. Maybe this fix is to strict.

If you reload the page while a card is open, Wekan tries to get the username by looking up the board members -> fetching the user objects -> reading the username property.
But I don't get the user object of users other than me during this page reload

I hope this helps you finding the bug

**Comment by xet7** [comment]
@centigrade-kdk 

It could be some shared board bug like #1623

Yes there was secury issue, details at https://wekan.github.io/hall-of-fame/
And that did mean that anyone logged in could have browserside access to all user details, so that would enable any user to get admin credentials, create and delete users, delete all boards etc.

I gladly welcome more contributors to help making Wekan more secure and more bug-free. Any company using Wekan should have developers in their company contributing to Wekan code, to make Wekan better.

**Comment by centigrade-kdk** [comment]
@xet7 
I got your hint and I'm willing to spend as much spare time as I have on problems we encounter in our company.

First I thought the mentioned security fix would prevent getting the username, but this is not the case after reading the infos from the Hall-Of-fame.

I could track the error down till https://github.com/wekan/wekan/blob/056843d66c361594d5d4478cfe86e2e405333b91/client/components/main/editor.js#L13

Here the call `Users.findOne(member.userId)` will give a result for my userId but not for another userId. Do you have a clue where I could look for a restriction like that?

**Comment by xet7** [comment]
@centigrade-kdk 

The security fix was in [v1.04](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v104-2018-06-12-wekan-release)  so it [publishes people code collection on serverside](https://github.com/wekan/wekan/commit/dda49d2f07f9c50d5d57acfd5c7eee6492f93b33) and there seems to be some limit change.

It could also be related to [users model](https://github.com/wekan/wekan/blob/devel/models/users.js) or some [component](https://github.com/wekan/wekan/tree/devel/client/components).

On [serverside](https://github.com/wekan/wekan/tree/056843d66c361594d5d4478cfe86e2e405333b91/server) there is authentication etc.

**Comment by centigrade-kdk** [comment]
@xet: I see and I guess I found the issue here, but I would like to discuss if my planned change would open a security issue. Do you have a preferred way to discuss those things (e.g. reach out on IRC )

**Comment by xet7** [comment]
@centigrade-kdk 

Send me email x@xet7.org , I read email often when I'm awake.

**Comment by centigrade-kdk** [comment]
Instead of: https://github.com/wekan/wekan/blob/6c7eab4456f8608ae3893d2200b759d426863cd2/server/publications/people.js#L9

I would put

```
if (user && user.isAdmin) {
    return Users.find({}, {
      limit,
      sort: {
        createdAt: -1
      },
      fields: {
        'username': 1,
        'profile.fullname': 1,
        'isAdmin': 1,
        'emails': 1,
        'createdAt': 1,
        'loginDisabled': 1,
      },
    });
  } else {
    return Users.find({}, {
      limit,
      sort: {
        createdAt: -1
      },
      fields: {
        'username': 1
      },
    });
  }
```


This change fixes our bug, but the thing is that I don't know the full consequences of this change. I tried if this would allow me to query user object by the ID without being logged in which is not the case. But not being familiar with meteor I dislike to do this change without having people with knowledge have a look. BTW. do you have a page with coding guidelines and a suggest IDE Setup to work on Wekan. Moreover, do you think on adding some automated test to Wekan?

**Comment by centigrade-kdk** [comment]
Okay I was a bit fast, it fixes the error but it prevents that the infos about the other users are fully loaded. See the following  image, which shows the avatars of the other board members:
<img width="103" alt="screen shot 2018-07-06 at 21 34 33" src="https://user-images.githubusercontent.com/31346125/42397005-7d2a15f0-8164-11e8-8f48-3adb45e20b92.png">

**Comment by kolaente** [comment]
I have the same problem, but coming from wekan `1.02`, also with a board which was shared. I also tried to export the non-working board and then create a new one of that backup but that didn't worked.

**Comment by xet7** [comment]
Could this be in any way related? #2492
