### ISSUE TITLE
Identified UX/UI problems for use on mobile device

### ISSUE THREAD

**Issue by Haocen** [wekan/wekan#1756]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.11
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: v8.11.1
* MongoDB Version: 3.2.20
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*
- *Explain steps how to reproduce*
- *Attach log files in .zip file)*
1. `header.styl`
```
margin: -10px
```
caused horizontal scroll, should be:
```
margin: -10px 0 -10px -10px
```

2. `jquery.ui.draggable` cased touch/click event blocking/not responding, no resolution other than handling touch event separately.

3. `perfect-scrollbar` cased touch/scroll event blocking/not responding, upgrade to latest version v1.4.0 should solve the problem.

I would suggest switch to React as frontend, though.

I have some nasty fixes for my own version of Wekan that barely works, but should not be considered proper fixes.

**Comment by xet7** [comment]
@Haocen 

Newest is Wekan v1.18.

What other fixes you have?

Is it possible that you submit all your fixes as pull request?

I don't have enough time to switch to React, and nobody has contributed it.

**Comment by Haocen** [comment]
Hi, I can contribute a little React if needed.

The hotfix commit can be found here:
https://github.com/Haocen/wekan/commit/43d86d7d5d3f3b34b0500f6d5d3afe7bd86b0060

Most of them are introduced by outdated package/design.

**Comment by xet7** [comment]
@Haocen 

Thanks! All improvements to Wekan are very welcome.

**Comment by Haocen** [comment]
@xet7 I believe the risk here is I may struggle to adhere to the current design philosophy of the frontend if I do the React rewrite along, it would be great if you can get somebody whose familiar with this project aboard, I can then write small components and get them reviewed through PR process.

I build a docker image with all the fixes I put in. I tested it on iOS 11.4 Safari/Chrome and Android 8.0 Chrome, should cover most use cases:
https://hub.docker.com/r/haocen/wekan/

To pull it directly:
docker pull haocen/wekan:mobile-hotfix

**Comment by xet7** [comment]
@Haocen 

Currently Wekan is using Jade/Blaze etc, so I don't know how it would look in React. Any small component pull request would help me getting the idea.

I did merge your mobile fixes a moment ago.

Next I will look at upgrading perfect-scrollbar.

Thanks!

**Comment by Haocen** [comment]
I think there is a heisenbug introduced by this hotfix, when click is triggered on the minicard by my code user maybe sent to a page with grey background, I need more time to investigate, sorry.

**Comment by xet7** [comment]
@Haocen 

No problem, thanks for your help! It's normal to have bugs in new code, usually when I merge some new feature or fix it takes some time to fix bugs it includes.

**Comment by xet7** [comment]
@Haocen 

Mobile navigation works much better with these fixes, thanks!

**Comment by xet7** [comment]
I tried newest perfect-scrollbar:
```
meteor remove mquandalle:perfect-scrollbar

meteor npm install perfect-scrollbar
```
But then when card is open, and card has many comments, scrollbar is not visible on card.
There could be some specific changes that mquandalle has made to his version.
