### ISSUE TITLE
Sign In with CAS creates an account with empty username, full name, email

### ISSUE THREAD

**Issue by sjoki** [wekan/wekan#1760]
Hi,

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.18
* Operating System: docker version
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker image
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): docker only
* Node Version: from docker image
* MongoDB Version: docker image - mongo:3.2.20

**Problem**:
I try to test sign in with CAS.
Docker run string: docker run -d --restart=always --name wekan --link "wekan-db:db" -e "METEOR_SETTINGS={\"cas\": {\"baseUrl\": \"https://auth.portal.xxx.yyy/cas/\",\"autoClose\": true},\"public\": {\"cas\": {\"loginUrl\": \"https://auth.portal.xxx.yyy/cas/login\",\"serviceParam\": \"service\",\"popupWidth\": 810,\"popupHeight\": 610}}}" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://192.168.149.199" -e "NODE_TLS_REJECT_UNAUTHORIZED=0" -p 80:80 quay.io/wekan/wekan:v1.18 
After press button "Sign In with CAS" I enter to Wekan but my user profile is empty.
But output of command "docker logs wekan": accounts-cas: user validated myname@xxx.yyy

![default](https://user-images.githubusercontent.com/26401725/42500047-b07ef640-8449-11e8-8e90-4998cdf06c8a.png)
![default](https://user-images.githubusercontent.com/26401725/42500218-19d77ff4-844a-11e8-83fe-7844fd684eab.png)

**Comment by xet7** [comment]
@ppoulard 

Can you look at this ?

**Comment by ppoulard** [comment]
Hi,

To ensure that it is an issue related to Wekan, please follow this procedure : 

- Prepare `/etc/hosts` :
`127.0.0.1       yourmachine.yourdomain.fr`

- Create Meteor app from scratch :
`
$ meteor create cas-app
$ cd cas-app
$ meteor add random accounts-ui atoy40:accounts-cas
`

- Update `package.json` :
`
"scripts": {
    "start": "ROOT_URL=\"http://yourmachine.yourdomain.fr:3000\" meteor run --settings cas.json",
`

- Create `cas.json` :

`
{
    "cas": {
        "baseUrl": <your conf here>
        <other CAS settings>
`

- In `client/main.html` :

Replace 

`
  {{> info}}
`

with

`
  {{> login}}
`

and accordingly the template with :

`
<template name="login">
  <button>Login</button>
  {{> loginButtons}}
</template>
`

- In `client/main.js` :

`
Template.login.events({
  'click button'(event, instance) {
    Meteor.loginWithCas(function() {
      console.log(arguments);
    });
  },
});
`

- Launch :
Don't start with `meteor` but with `npm` :
`
$ npm start
`

Open your browser and try CAS. If it doesn't work, try to fix it, and next apply your conf inside Wekan.

Hope this helps !

**Comment by sjoki** [comment]
npm start

> cas-app@ start /home/myname/cas-app
> ROOT_URL="http://wekan.xxx.yyy:3000" NODE_TLS_REJECT_UNAUTHORIZED=0 meteor run --settings cas.json

[[[[[ ~/cas-app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://wekan.xxx.yyy:3000
I20180709-17:26:51.596(5)? accounts-cas: user validated myname@xxx.yyy

App page after successful login: 
Login myname@xxx.yyy  Sign Out

cas.json is a copy of my docker run string:
cat ./cas.json
{"cas": {
    "baseUrl": "https://auth.portal.xxx.yyy/cas",
    "autoClose": true
},
"public": {
    "cas": {
        "loginUrl": "https://auth.portal.xxx.yyy/cas/login",
        "serviceParam": "service",
        "popupWidth": 810,
        "popupHeight": 610
    }
}
}

**Comment by ppoulard** [comment]
This new CAS feature in Wekan is just a button that triggers an existing Meteor package called atoy40:accounts-cas that perform the CAS magic. In order to integrate it in Wekan, my first step was to make it working outside Wekan in a little standalone Meteor app. If it work in Meteor, it should work in Wekan. So the question is : did you try to make that little pure Meteor app as described above ? Please answer this question and we will see whether your issue is related to the Wekan integration or not. It takes a couple of minutes to try.

**Comment by sjoki** [comment]
Yes, my previous post about that I try run this little pure Meteor app. It's work fine with my cas config which I use in docker run.
**npm start output:**
    cas-app@ start /home/myname/cas-app
    ROOT_URL="http://wekan.xxx.yyy:3000" NODE_TLS_REJECT_UNAUTHORIZED=0 meteor run --settings cas.json

[[[[[ ~/cas-app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.
=> App running at: http://wekan.xxx.yyy:3000

**cas.json which I use:**
{"cas": {
"baseUrl": "https://auth.portal.xxx.yyy/cas",
"autoClose": true
},
"public": {
"cas": {
"loginUrl": "https://auth.portal.xxx.yyy/cas/login",
"serviceParam": "service",
"popupWidth": 810,
"popupHeight": 610
}
}
}

**Browser page contain string after CAS sign-in:**
Login myname@xxx.yyy Sign Out

**App output when I try to sign-in with CAS:**
I20180709-17:26:51.596(5)? accounts-cas: user validated myname@xxx.yyy

I tried what you asked for.

**Comment by pcurie** [comment]
Hi @ppoulard 
I'm trying to fix this, but I can't find the 0.0.5 version for npm cas package.
Do you know where can I find it ?
Thanks

**Comment by xet7** [comment]
@pcurie 

https://atmospherejs.com/atoy40/accounts-cas

https://github.com/wekan/wekan/pull/1742

**Comment by ppoulard** [comment]
@pcurie 
Here are the links :
https://www.npmjs.com/package/cas
https://github.com/joshchan/node-cas
https://github.com/joshchan/node-cas/wiki/CAS-Attributes
