### ISSUE TITLE
Can't access item sub-menus, without getting a 404

### ISSUE THREAD

**Issue by OpnSrcConstruction** [wekan/wekan#1766]
Can't access item sub-menus, without getting a 404

**Server Setup Information**:
snap install wekan
(much later)>snap refresh wekan --channel edge
$ sudo snap set wekan root-url="http://localhost:5000"

* Did you test in newest Wekan?: I even tried the edge snap channel
* Wekan version:1.18(stable)/1.18-7-g90707aa(Edge)
* If this is about old version of Wekan, what upgrade problem you have?
Fresh installed on July 9
* Operating System:
Mint 19 based on Ubuntu 18.04(LTS)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
snapd
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
Caddy I think from watching the install of the snap & looking at the yaml build file
* Node Version: 
yaml says 8.11.3 node-engine, but I don't think I have anything node installed on the local machine.
* MongoDB Version:
yaml says>mongodb-linux-x86_64-ubuntu1604-3.2.20.tgz
I don't have anything mongodb installed locally.
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):
I'm just using localhost:8080 as a web address to access the Wekan instance.
**Problem description**:
Can't access item sub-menus, without getting a 404
![wekan_2018-07-11 15-11](https://user-images.githubusercontent.com/6454764/42594969-c93998c2-851e-11e8-91dc-f196b5fa7a72.gif)

Reproduction steps:
1>create board
2>create column
3>create item & click on it to try and get the sub-menus; which gives a page URL error.
- *Attach log files in .zip file)*

**Comment by xet7** [comment]
```
sudo snap set wekan port='5000'
```
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys
