### ISSUE TITLE
Card disappear when press tab while writing new one

### ISSUE THREAD

**Issue by hever** [wekan/wekan#1767]
Card disappear when press tab while writing new one.

**Comment by xet7** [comment]
@hever 

Do you have newest Wekan v1.18.0 ? When I write card and press tab, nothing happens, and I still can then continue typing.

**Comment by hever** [comment]
Now I have time to check version through terminal (command `snap list`) and yes, I have newest Wekan v1.18.0. (My previous question is still valid.)

So more describe my issue. When I press tab new card is open in left column (shift tab open card in right column). It's nice. But when I'm for long time writing long text to new card and unfortunately press tab all my text is forever disappear. Then when I press shift tab in a hope there will be my precious text, only blank card is shown. There's no popup saying "Do you really want to do this, all your text you're written will be deleted".

**Comment by xet7** [comment]
@hever 

I am  unable to duplicate your issue by pressing tab. Please add gif video how to replicate issue.

Also, I don't know why you use tab. Undo is Ctrl-z and Redo is Ctrl-Shift-z.

**Comment by hever** [comment]
![wekan tab prob](https://user-images.githubusercontent.com/98204/42759563-b3624a0c-8907-11e8-9c6a-ef38aa1e3b82.gif)

**Comment by xet7** [comment]
@hever 

What browser and OS you use?

**Comment by xet7** [comment]
@hever 

Thanks for anim gif ! Now I figured out how to duplicate this. This seems strange why it does this.

**Comment by hever** [comment]
@xet7 
Debian GNU/Linux 9 (stretch) stable / Firefox ESR 52.9.0 64bit

**Comment by listenerri** [comment]
I also encountered this problem.
wekanteam/wekan: v2.81
firefox: v68.0.1
deepin linux: v15.11
