### ISSUE TITLE
[Issue] Board doesn´t load

### ISSUE THREAD

**Issue by filipegit** [wekan/wekan#1768]
## Issue

* Did you test in newest Wekan?: Yes
* Wekan version: 1.18
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu 18.04 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* MongoDB Version: 4
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://localhost/wekan

Board doesn´t load when a card, with a custom field, was moved to it.

- *Explain steps how to reproduce*
1 - Create a card with a custom field
2 - 
![screenshot](https://user-images.githubusercontent.com/1613044/42642623-a2fc6716-85cd-11e8-8bba-e47f1afaa4aa.png)
Move the card to another board
3 - Try to open the destination board

- *Attach log files in .zip file)*

[log.txt](https://github.com/wekan/wekan/files/2189343/log.txt)

**Comment by sfahrenholz** [comment]
Hello, 
i think this is the same as #1706 and #1703.
Please export your board and show in the file for 
- "labelIds": [null,
or anythink like this.

**Comment by filipegit** [comment]
@sfahrenholz 

Here is the file.
[export.txt](https://github.com/wekan/wekan/files/2189335/export.txt)

**Comment by filipegit** [comment]
@sfahrenholz

When I import the board, it works again.

**Comment by sfahrenholz** [comment]
@filipegit the importing of the customfields are not working/implemented currently. 
thanks for the file, i can not see something, maybe @feuerball11 can have a look at this

**Comment by xet7** [comment]
Please fix your root-url to be correct http://10.1.96.116/wekan/ or http://10.1.96.116/wekan , whichever works

**Comment by filipegit** [comment]
@xet7 
 I did this 

snap set wekan root-url="http://10.1.96.116/wekan/"

But it didn´t work.

TypeError: a is undefined
e11c56d523ddc4b13681cbb929eb258077c71bc2.js:1:6261
customFieldsWD/<@http://10.1.96.116/wekan/e11c56d523ddc4b13681cbb929eb258077c71bc2.js?meteor_js_resource=true:299:432613

**Comment by filipegit** [comment]
@xet7 

I tried on CentOS 7 but the problem with custom fields still happen, and I foun
![screenshot](https://user-images.githubusercontent.com/1613044/42783890-c4c9bebc-8923-11e8-991a-418d5a9ecdbd.png)
d a new issue: I can´t delete boards from trash. Nothing happen when a click on "Delete board"

**Comment by filipegit** [comment]
I found this message

![screenshot](https://user-images.githubusercontent.com/1613044/42826915-eae92c7a-89bb-11e8-9c4b-960f4bd7a54f.png)

**Comment by digifa** [comment]
Same issue here - when you move a card with a custom field to a board without the custom field, the target board is not longer loading.

**Comment by xet7** [comment]
This moved to #1703 

Delete board moved to #833
