### ISSUE TITLE
Buttons misaligned in Safari

### ISSUE THREAD

**Issue by ePirat** [wekan/wekan#177]
Some buttons, namely the tags and (sometimes) Username circles are misaligned in Safari, as seen in the following screenshots:

![bildschirmfoto 2015-06-09 um 16 08 52](https://cloud.githubusercontent.com/assets/323210/8059775/06bf2b98-0ec2-11e5-8346-1e2c95fc6db2.png)
![bildschirmfoto 2015-06-09 um 16 09 26](https://cloud.githubusercontent.com/assets/323210/8059776/089b7c8c-0ec2-11e5-9d3a-3be160a8052b.png)

**Comment by mquandalle** [comment]
Does commit bc9fcc7 fix the problem?
