### ISSUE TITLE
Documentation: Installation

### ISSUE THREAD

**Issue by Tampa** [wekan/wekan#1770]
The Platforms page, while having a lot of information for those looking to explore, the actual manual installation process of releases is either hard to find or not well described. I have deployed a couple installations now and got down to the basics of how I have managed to get it to work properly. Feel free to create another tutorial out of this. It was tested on Debian and Ubuntu.

```
apt-get install mongodb-server make g++ gcc build-essential libssl-dev

wget https://deb.nodesource.com/setup_5.x

chmod +x setup_5.x

./setup_5.x

apt-get install nodejs

wget https://releases.wekan.team/wekan-1.18.tar.gz

tar xzvf wekan-1.18.tar.gz

cd bundle/programs/server && npm install

cd ..

cd ..

cd ..

wget https://deb.nodesource.com/setup_10.x

chmod +x setup_10.x

./setup_10.x

apt-get install -y nodejs

cd bundle/programs/server && npm install

export MONGO_URL='mongodb://127.0.0.1:27017/wekan'

export ROOT_URL='https://example.com'

export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'

export MAIL_FROM='wekan-admin@example.com'

export PORT=9090

export ROOT_URL='http://myserver:9999'

npm install fibers

cd ..

cd ..

cd ..

screen -S wekan

-> node main.js
```

The reason I use an older version along with a newer version of nodejs is because I ran into issues with just the latest version. It seems it wants the old parts in there? I have zero knowledge of nodejs so I really do not know, but this setup is working on 6 servers now so I think it's likely to work elsewhere too.

**Comment by xet7** [comment]
Your way of install does not autoupdate like snap, and does not have sandboxing like snap. Manual installs are only supported for developing new features, they are not for production in any way.

**Comment by xet7** [comment]
Running in screen does not start after server reboot.

**Comment by xet7** [comment]
Main wekan source install and build script is here:
https://github.com/wekan/wekan-maintainer/blob/master/virtualbox/rebuild-wekan.sh

If you have any improvements to it, you can add pull request.

**Comment by xet7** [comment]
Hmm, your instructions actually have some meteor bundle info that is not yet in wiki. Please edit Wekan GitHub wiki directly and add info to there.

**Comment by Tampa** [comment]
No the screen session does not restart after a reboot, but registering wekan as service will, the screen session is there to run it and check for console errors on initial setup before being moved to service. Because services are still different init.d or systemd I did not include that step.

Yes it does not auto-update, but unless bugs are encountered and grave enough to warrant upgrading the boards I deployed generally don't get upgraded for quite a while. The upgrade, if I understand nodejs documentation right, should simply be a matter of grabbing the new release and installing it over the old one. That, as maintenance goes, is not a complex task and I have a few pieces of software that require this as no docker image or other is available.

In reality I much prefer using repositories to deploy, so an apt repo to make it as easy as apt-get install would be the easiest and likely most used method of installation and maintaining wekan. I very much dislike docker and other containerization systems, because they add another layer of possible failures and systems to maintain and automated upgrades are mostly unwanted anyways, but that is a topic for another time.

I would say a good comprise would be adding a link to the documentation for "Quick and Dirty" guide on how to simply get it installed. From there moving to containers and "enabling autoupdate" would be the next logical step, rather than starting with having to learn a completely new containerization system just to see if wekan is what they are looking for. Maybe that is just me, but that is how other software documentation seems to be structured from my experience.

**Comment by xet7** [comment]
Systems that don't have automated upgrades get hacked very soon.

Wekan has Hall of Fame for those that have reported security issues:
https://wekan.github.io/hall-of-fame/

For example when Drupal security fix was released, soon most Drupal websites that did not patch, were compromised.

Sandboxing like Snap, Docker, and Sandstorm Grains prevent compromise of Wekan compromising your whole server.

Wekan has very frequent updates to fix various bugs and add new features. For example, one day I did make 7 releases of Wekan.

If you have other ways to sandbox all your software separately, like using chroot jails, or similar, and have automated your infra backup and restore to point-in-time, maybe in that case using just source installs would work. I just like to have sandboxing safety net. Those servers that don't support running snap or docker usually don't have latest kernels with latest protections.

**Comment by xet7** [comment]
I think there was deb package sometime for Wekan, somewhere in wiki or some repo listed at https://github.com/wekan

That rebuild script:
https://github.com/wekan/wekan-maintainer/blob/master/virtualbox/rebuild-wekan.sh
could have some improvements, like option for other ways to install, upgrade, etc.

There most likely is a lot to improve source, bundle etc installs. There are also some ansible scripts for installing at https://github.com/wekan . It would be very nice if those could be integrated to same script.

I do also understand the viewpoint of not doing automatic updates. Sometimes something breaks, and I fix it in next release, so Wekan works again.

**Comment by Tampa** [comment]
The boards I have deployed all run internally and are not accessible through the web and run on virtual machines, so the chances of someone using it to break in is lessened. Of course keeping software up to date is going to be better security, but even that is no guarantee and sometimes holes are even introduced through bad maintaining. As soon as a software depends on other software to operate you are at the mercy of those maintainers. Nodejs, mongodb could break any day and leak data or open holes in security. By no means a reason not to exercise caution and apply security, but I doubt wekan itself has had such huge holes outside of the vulnerabilities that widely affect other software too. Generally the update cycle for these machines is somewhere 1-4 months depending on new features and critical fixes. Major security issues have everyone scrambling to update any software, for everything else reading the changelog for critical fixes being made and scheduling a time-critical update mostly works best. Software updates are always seen as downtime even if none is incurred so it's not always easy to convince keeping automatic security updates turned on.

Like I said, please feel free to adapt and use my way of installing to improve any scripts or documentation. I don't really plan to be a great active contributor to the project, mainly because I have very little experience with code outside of php, so nodejs is like klingon to me.

Lastly, I have to express my gratitude for this project. I very much appreciate when there are alternatives to paid enterprise service software, especially since the clients I deal with are all small businesses that have not yet grown enough to afford them. It greatly helps as stepping stone and some seem to not want to switch away from it :)

**Comment by xet7** [comment]
@Tampa 

Thanks for your gratitude, all encouragement from Wekan community keeps me going !

Thanks also for your script above! I will look at it later what to add to wiki etc.

Yes, in internal networks that is a good strategy.

**Comment by rjevnikar** [comment]
@Tampa or @xet7 do you have/know the steps for installing Wekan from source on CentOS? Unfortunately, snap is not an option.

What I have so far:
```
#Install packages
sudo yum update
sudo yum install epel-release
sudo yum install telnet bind-utils yum-utils wget gcc gcc-c++ httpd bzip2  git mod_ssl

#Insall MongoDB [mongodb-org-3.2.x]
sudo yum install mongodb-org
# To improve performance of MongoDB, stop server from using transparent huge pages
https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/
# Start service
sudo chkconfig mongod on
sudo service mongod start
# Eliminate error on mongo start up
sudo vi /etc/security/limits.d/20-nproc.conf
mongod     soft    nproc     32000
# Add authentication and users to mongo
# Restart mongod service
sudo systemctl restart mongod

# Install NodeJS v8 (https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) 
curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash
sudo yum erase nodejs
sudo yum install nodejs

# Install Meteor 1.6.0.1
curl -k "https://install.meteor.com/?release=1.6.0.1" | sh

#Clone Wekan git repo

# Get packages
mkdir -p ~/wekan/packages
cd packages
git clone https://github.com/wekan/flow-router.git kadira-flow-router
git clone https://github.com/meteor-useraccounts/core.git meteor-useraccounts-core
cd ..
# make sure user has permissions
sudo chown -R user:user ../wekan/

# Create config file to hold environment vars (for running wekan as a service)
vi config.env
NODE_ENV=production
PWD=<path to /bundle>
PORT=8081
HTTP_FORWARDED_COUNT=1
MONGO_URL=<Mongo URL with Auth>
ROOT_URL=http://example.com/
MAIL_URL=smtp://example_mail.com:25/
MAIL_FROM=wekan@example.com

# In wekan directory
sudo rm -r node_modules/
npm install
sudo rm package-lock.json
npm install fibers@2.0.0
sudo rm package-lock.json
sudo rm -r .build/
meteor build .build --directory
cd ./.build/bundle/programs/server/ && npm install
export PORT=8081
export MONGO_URL=<Mongo URL with Auth>
export ROOT_URL=http://example.com/
export MAIL_URL=smtp://example_mail.com:25/
export MAIL_FROM=wekan@example.com
npm install fibers@2.0.0
cd ../../../..
# Export vars again because I've seen it done in two places
export PORT=8081
export MONGO_URL=<Mongo URL with Auth>
export ROOT_URL=http://example.com/
export MAIL_URL=smtp://example_mail.com:25/
export MAIL_FROM=wekan@example.com
```
wekan is ready to run...

I'm asking because I'm experiencing very slow performance, and am trying to determine if it my install process or something else. My log files are inconclusive.

**Comment by xet7** [comment]
Installation info is now as all separate buttons at https://wekan.github.io
