### ISSUE TITLE
UI feature suggestion: shortcuts to drop item at start or end of long lists

### ISSUE THREAD

**Issue by x11x** [wekan/wekan#1771]
I have an idea for a simple UI feature. Don't know if anyone else would find this handy or how easy to implement it would be.
When in List view, dragging cards between lists, it would be handy if 2 drop zones appeared at the top and bottom of the visible part of the target list, which automatically drops the card into the first and last position respectively.
This would help with long lists and you want to quickly add something to the top or bottom without having to scroll the whole list.
I know that with Kanban methodology you are doing it wrong if your lists are too long... But I have found that it is handy especially for personal lists where you might want to store some things longer term until you get more time -- "backburner" type lists.

**Comment by xet7** [comment]
Card have "hamburger" menu with options "Move to Top" and "Move to Bottom".
