### ISSUE TITLE
UI feature suggestion: drag handles and long press

### ISSUE THREAD

**Issue by x11x** [wekan/wekan#1772]
When using on small touch screen/mobile, it is sometimes difficult to scroll through lists as you accidentally drag cards when swiping to scroll. This could be fixed by using either drag handles, or long press to start dragging.
This is only a problem for touch, the way it is could remain the same for desktop site.
Also, long press to enter multi-selection mode is a convention for mobile apps. That would be a huge usability improvement for the mobile version. Ideal would be long press enters multi-selection mode, and then if a movement is detected, starts dragging.

**Comment by hupptechnologies** [comment]
Working on it.
