### ISSUE TITLE
Mobile/touch screen UI suggestions: swiping cards and lists, moving cards between lists, sidebar button

### ISSUE THREAD

**Issue by x11x** [wekan/wekan#1773]
Hi,
Here are a few UI suggestions to improve mobile/small touch screen usability:

1. The "<" button which opens the side bar is kind of in the way at the top right. It might be better at the bottom right, or even in the toolbar?
2. **Moving cards between lists when only one list is visible**. Not sure what the best way to implement this is. Maybe the easiest would be a context menu with a "Move to List" quick menu. Or, a nicer way would be if you could drag horizontally to change between lists -- this would be tricky to do well and make it work properly.
3. **Swipe and gestures for cards** - maybe swipe right could open a "move to list" quick menu and swipe left could send to recycle bin? Swiping cards is a common UI action for touch screens, it would be good to work out some handy shortcuts that could be performed by swiping. Maybe they would need to be customizable to different users' preferences.
4. **Dragging for lists** - when viewing on a small screen with only 1 list visible, lists are draggable, but there is nowhere to drag them (as only one list fits in the viewport). It might be better if swiping on the list name changes the view to the next list, so you can quickly swipe back and forth between your lists.

Really love this project and appreciate the work that's gone into it. Sadly I won't have the time to work on any of these suggestions any time soon, but thought I'd put them out there in case anyone thinks they would be useful or can see a way to implement them.

**Comment by arradoq** [comment]
For alternative you can just set browser to desktop view btw, and you can swipe it just like desktop. But maybe it will use more memory allocation. I think it's best to work on pixel or size adapative based on the 
device screen.

**Comment by x11x** [comment]
Thanks for your reply.
Yes it is currently usable on mobile and actually pretty good, these are just suggestions for improvement. Adaptive would be good as different functionality/gestures will be appropriate on different sized screens (as per my comments).

**Comment by xet7** [comment]
Moved to #2098
