### ISSUE TITLE
Custom fields are lost when importing a board

### ISSUE THREAD

**Issue by kolaente** [wekan/wekan#1775]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.18
* Deployment Method: docker (image: hub.docker.com/wekanteam/wekan:v1.18)
* Http frontend if any: HAproxy
* Node Version: 8.11.3
* MongoDB Version: 3.2.14

**Problem description**:

I exported imported a board after it stopped working when I did the update to 1.18. I did some modifications to the backup to resolve the issues descruíbed in #1754.
Now all custom fields are lost.

**Comment by ymeramees** [comment]
Same issue with the demo in Sandstorm.

**Comment by xet7** [comment]
Moved to #3137
