### ISSUE TITLE
Avatars won't display if the app is migrated to a different sub-path

### ISSUE THREAD

**Issue by zypA13510** [wekan/wekan#1776]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.18.0
* Operating System: CentOS 7 (3.10.0-862.el7.x86_64)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):
    * Old: http://hostname/wekan
    * New: http://new-hostname/

**Problem description**:
When migrating Wekan to a new host, the user avatar will become inaccessible, HTTP status 404. Using the ROOR_URL above, the `src` attribute of the `<img>` tag is always pointed to `/wekan/cfs/files/avatars/RandomString/filename.jpg` (removing the `/wekan` part from Chrome Dev Tools after migration will load the image correctly).

When viewing the data from mongo CLI, I discovered that the sub-path is stored into the DB:
```
> use wekan
> db.users.find()
{
    ...
    "profile" : {
        ...
        "avatarUrl" : "/wekan/cfs/files/avatars/_________________/____.jpg",
        ...
    },
    ...
}
```

Interestingly, also stored in `/cfs`, attachments work fine after migration. If the attachment is an image file, the preview loads correctly.

Maybe related to #386, #973.

**Steps to reproduce**:
1. Set up Wekan-snap using the old ROOT_URL above.
2. Perform a DB backup [wekan-snap backup and restore](https://github.com/wekan/wekan-snap/wiki/Backup-and-restore)
3. Set up Wekan-docker (or probably another Wekan-snap, not tested) with the new ROOT_URL
4. Perform a DB restore [wekan-docker export mongo data](https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data)

**Workaround**:
Not tested yet, but theoretically, one can use the mongo CLI to replace the old sub-path with RegExp. [Ref](https://stackoverflow.com/questions/33968553/mongodb-regex-replace)

**Comment by zypA13510** [comment]
Reopen?
I think we should set up the reference with an internal ID instead of a URL. And btw, attachments do not break in the same situation, so maybe just copy the solution to user avatars?

**Comment by xet7** [comment]
The bug is at CollectionFS, as can be seen at #386 .
Avatar URL currently needs to include subpath of ROOT_URL to display correctly, like `/wekan/cfs`. My javascript on the fly fix was too fragile, it did not always work. There are couple different ways to fix this.

a) Workaround way: In `wekan/server/migrations.js`, check does `process.env.ROOT_URL` contain suburl like `/wekan`. If yes, search MongoDB `users.profile.avatarUrl` for those that do not begin with `/wekan/cfs/` and change them to have that.

b) As part of #142 supporting other ways to store attachments, make all attachments to use any of those ways to store attachments with correct URLs.

**Comment by andreasgrill** [comment]
We recently experienced the same issue by changing wekan from a subpath `xy.com/wekan` to a sub-domain `wekan.xy.com`.
I used the following mongodb code to remove `/wekan` from the avatar URL:
```
db.users.find({"profile.avatarUrl": /^\/wekan\//}).forEach(function(e,i) { 
    e.profile.avatarUrl=e.profile.avatarUrl.substring(6); 
    db.users.save(e); 
});
```

**Comment by xet7** [comment]
@andreasgrill 

Can you try to make pull request that would at `wekan/server/migrations.js` [check ROOT_URL](https://github.com/wekan/wekan/blob/master/models/settings.js#L102) does it have sub-path, and run migration to correct those avatar URLs?

**Comment by xet7** [comment]
@andreasgrill 

When sub-path changes, would that require changes to other images and attachments? You could check at MongoDB database.

**Comment by xet7** [comment]
Thanks!

**Comment by andreasgrill** [comment]
@xet7 I’ll look into it this weekend.
