### ISSUE TITLE
Root user in docker {Openshift}

### ISSUE THREAD

**Issue by Asgoret** [wekan/wekan#1778]
Hi. 

I try to test Wekan in Openshift and catch security error in GUI. When i try to start docker from `docker.io` or from `quay.io` i see `Image quay.io/wekan/wekan:latest runs as the root user which might not be permitted by your cluster administrator.`.

Can we change wekan start to random user?

**Comment by xet7** [comment]
@adyachok 

Can you look at this?

**Comment by tdemaret** [comment]
#1816

**Comment by xet7** [comment]
https://github.com/wekan/wekan/pull/1816

**Comment by xet7** [comment]
@tdemaret 

Are you sure about this in docker-compose.yml ?
```
ports:
  - 8080:80
```
I think the format is:
```
<public_port>:<private_port>
```
So if you are exposing port 8080 from inside of wekan-app container, it should be:
```
8080:8080
```
if you expose it as port 8080 to outside, or:
```
80:8080
```
if you expose it to port 80. Which way is it?

**Comment by Asgoret** [comment]
@xet7 when i can re-download image?

**Comment by xet7** [comment]
@Asgoret 

Now.
```
image: quay.io/wekan/wekan
```
Image rebuilds automatically after every change. You can also see those in webbrowser at https://quay.io/wekan/wekan
