### ISSUE TITLE
Feature request: Cover/color change for boards (and possibly colors for cards)

### ISSUE THREAD

**Issue by yuppox** [wekan/wekan#1779]
I am using the latest version, deployed by snap on Ubuntu.

I notice that cards can have a cover, which is very cool. I kind of wish they could have a color, too.

However, it would be really nice if boards could have a color (or a cover). To me, a cover would be more useful for a board and a color for a card.

Thank you!

**Comment by d3dbit** [comment]
+1 Feature request

**Comment by xet7** [comment]
Boards already have color, in board hamburger menu.

Card color moved to #428

**Comment by yuppox** [comment]
Thank you @xet7

**Comment by d3dbit** [comment]
Hello, sorry I had a mistake. I thought that @yuppox wanted to say 'card colour', no 'board colour'. @xet7 sorry for my confusion.

Note: Changing card's colour could be a nice feature.
