### ISSUE TITLE
No scroll bar on cards that overflow the screen

### ISSUE THREAD

**Issue by jnso** [wekan/wekan#1780]
## No Scroll bar for long task

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.19
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap

**Problem description**:
- For long tasks that overflow the screen. I used to get a scroll-bar on the right side. Now I do not get the scroll bar. It behaves a bit different in the various browsers.
- Chrome: no scrollbar and scrolling with the mouse wheel does nothing:
![scroll-chrome](https://user-images.githubusercontent.com/3541948/42804163-2bf6f2b8-89b9-11e8-8098-35d2a4e82e2a.gif)
- Firefox: The whole page scrolls but the task is "cropped" and I can't see the bottom of it.
![scroll-ff](https://user-images.githubusercontent.com/3541948/42803664-b8776288-89b7-11e8-9414-699041261061.gif)

**Comment by jnso** [comment]
Tried on a different computer, the scroll-bar was there but when I scrolled down and release the scroll bar the task closed.

**Comment by jnso** [comment]
On chromium I tried to fiddle around in the dom-inspector.

When changing .card-details css class from using "overflow: hidden" to "overflow: scroll" it seems to be working as expected.

**Comment by therampagerado** [comment]
I have the exact same thing here - we can't scroll long cards too.
