### ISSUE TITLE
Mail-password in plain text

### ISSUE THREAD

**Issue by LyR33x** [wekan/wekan#1783]
## Issue

**Server Setup Information**: snap

* Did you test in newest Wekan?: yes
* Wekan version: 1.19.0
* Operating System: Debian stretch
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): apache http-proxy
* Node Version: 8.11.3

**Problem description**:

Reproduce: Click Adminstration -> Click Mail -> See password you entered for sending mails

The password should be blanked (showing dots, etc) and the field should be only there for entering a new password, not for reading password.

**Comment by d3dbit** [comment]
It would be great!
