### ISSUE TITLE
Installed via snap - but no access

### ISSUE THREAD

**Issue by tigger10** [wekan/wekan#1786]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.20
* Operating System: Ubuntu 18.04 server (digital ocean)
* Deployment Method: snap
* ROOT_URL environment variable http://ipaddress:8080
I don't have a domain set up yet, just using server ip address. 

**Problem description**:
I think I've successfully installed the snap as can see running a service.
Default to root url http://serveripaddress:8080 - but can't access Wekan online. 
Tried the command snap set wekan root-url="serveripaddress:8080" and opened port via ufw allow 8080. But sill no access. 

I'm still a relatively new to linux. Wasn't sure what else to do in terms of the instructions on wiki?
Not clear about whether have to tweak apache settings as indicated here: https://github.com/wekan/wekan/wiki/Apache

(By the way as a test, installed on my own linux mint pc via snap and accessed it fine via http://127.0.0.1:8080, without doing anything else).  

Any help appreciated.

**Comment by xet7** [comment]
@tigger10 

I think you mean Example 3:
https://github.com/wekan/wekan/wiki/Settings

Also see:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by tigger10** [comment]
Thanks for replying. Though I'm still stuck. 

If I follow the instructions at https://github.com/wekan/wekan-snap/wiki/Install I go up to 4. Should I now be able to access via http://serveripaddress:8080/ - because I can't. 

What else do I need to do or check?

**Comment by xet7** [comment]
snap
```bash
sudo snap set wekan root-url='http://123.456.123.456/boards'

sudo snap set port='8080'
```
apache wekan.conf:
```ApacheConf
<VirtualHost *:80>
        ServerName 123.456.123.456
        ServerAdmin webmaster@example.com

        DocumentRoot /var/www-vhosts/example.com
        <Directory />
                Options FollowSymLinks
                AllowOverride AuthConfig FileInfo Indexes Options=MultiViews
        </Directory>

        <Directory /var/www-vhosts/example.com>
                Options -Indexes +FollowSymLinks +MultiViews
                AllowOverride AuthConfig FileInfo Indexes Options=MultiViews
                Require all granted
        </Directory>

        ErrorLog /var/log/apache2/example.com-error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog /var/log/apache2/example.com-access.log combined
        ServerSignature Off
        ProxyPassMatch   "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:8080/$1"
        ProxyPass        "/" "http://127.0.0.1:8080/"
        ProxyPassReverse "/" "http://127.0.0.1:8080/"
</VirtualHost>
```

**Note:** if not already done, don't forget to enable your vhost `sudo a2ensite wekan.conf`

Reload Apache `sudo service apache2 reload`

Then browse http://123.456.123.456/boards

**Comment by tigger10** [comment]
Thanks. I'll tried this - but still no access. 
Dumb questions (please bear with me). 
As I don't have a domain name for the server, what do I use for:
`DocumentRoot /var/www-vhosts/example.com` 
I kept it as is. 

And does wekan.conf need to have file permission changed? At the moment it's:
`-rw-r--r-- 1 root root 1039 Jul 18 11:28 wekan.conf`

Thanks

**Comment by xet7** [comment]
That documentroot shoud point to your wekan/public directory.

Usually on Ubuntu file locations are at:
```
/etc/apache2/sites-available/wekan.conf
```
And there needs to be a symlink to it:
```
sudo su
cd /etc/apache2/sites-enabled
ln -s ../sites-available/wekan.conf wekan.conf
```
And then reload apache
```
sudo systemctl reload apache2
```
You also need to check that wekan and mongodb is running:
```
sudo snap services
```
If they are not running, you need to reboot your server, if you have not rebooted after installing snap:
```
sudo reboot
```
And then check again:
```
sudo snap services
```
If those are not still running, reinstall wekan:
```
sudo snap remove wekan

sudo snap install wekan
```
And set wekan root-url etc settings.

**Comment by tigger10** [comment]
Hello again

Yes, I have file the file created /etc/apache2/sites-available/wekan.conf

But I know I'm being a total noob, as I still don't understand what I should set the documentroot? Where is the wekan/public directory located? Do I have to create it?

Thanks for your patience.

**Comment by xet7** [comment]
@tigger10 

I think you don't need documentroot at all.

```ApacheConf
<VirtualHost *:80>
        ServerName 123.456.123.456
        ServerAdmin webmaster@example.com
        ErrorLog /var/log/apache2/example.com-error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog /var/log/apache2/example.com-access.log combined
        ServerSignature Off
        ProxyPassMatch   "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:8080/$1"
        ProxyPass        "/" "http://127.0.0.1:8080/"
        ProxyPassReverse "/" "http://127.0.0.1:8080/"
</VirtualHost>
```

**Comment by tigger10** [comment]
Ok. Tried that - still doesn't work. 
I followed the other steps, symlink, checked snap services etc.

**Comment by xet7** [comment]
@tigger10 

You could use my Commercial Support https://wekan.team and contact me by email.

It seems that I can't figure out exact reason without ssh access to server.

**Comment by tigger10** [comment]
Hmm...frustrating. 

Anyhow, I added a domain to my server, followed instructions, used vhost file, and I can access wekan :-)

Thanks for looking into this.
