### ISSUE TITLE
502 error after auto update in snap

### ISSUE THREAD

**Issue by florianproxi** [wekan/wekan#1787]
Hi, I own Wekan on snap under Ubuntu. Whenever it does an update (automatically at night) in the morning I have a 502. To restart it I reboot the server. Do you know what it could come from?

**Comment by xet7** [comment]
What version of Ubuntu? Do you have latest updates installed?

On my Ubuntu 18.04 and Debian 9 servers it does not require reboot.
Reboot is only required after first time after installing installind snap command.
For Ubuntu updates, I have unattended-upgrades also installed and configured, so it reboots at night if there is kernel updates.
On some server I use integrated Caddy, and on other server Nginx in front of Wekan.

What does this command output on your server?
```
sudo snap services
```
If you have these enabled:
```
sudo snap enable wekan
```
you could also make sure that systemd keeps them running:
```
sudo systemctl enable snap.wekan.wekan

sudo systemctl enable snap.wekan.mongodb
```
Another way to "fix" it would be to setup your server root cronjob to reboot at night.

**Comment by florianproxi** [comment]
Dear @xet7 and thanks for your answer !

I have Ubuntu 16.04 with nginx without caddy (i use certbot to have SSL).

The command returns this : 
`Service        Startup   Current
wekan.caddy    disabled  inactive
wekan.mongodb  enabled   active
wekan.wekan    enabled   active`

**Comment by xet7** [comment]
You could backup wekan and upgrade to Ubuntu 18.04, I I think it has newer snap.
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore

**Comment by xet7** [comment]
No reply received. For me snap works.
