### ISSUE TITLE
Feature request: auto-assigning labels to a card

### ISSUE THREAD

**Issue by tigger10** [wekan/wekan#1792]
I'm enjoying using the clean visual display of wekan.

A feature request: when creating a new card, could a label (colour) be auto-assigned. 

For example, I have a Work and Home backlog lists. Cards are then moved to a Buffer list but then it's difficult to visually sort the original cards from Work and Home. Assigning an auto-colour could help. 

Currently, I'm manually adding a colour label to Work, but this is rather laborious. Or have I missed an existing feature to do this?

**Comment by xet7** [comment]
Moved to #1160
