### ISSUE TITLE
Email Notification when user makes a change to a tile?

### ISSUE THREAD

**Issue by a5dev** [wekan/wekan#1794]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.21.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 8.11.3
* MongoDB Version: (how can I find this?)
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):   http://wekan.mydomain.com

**Problem description**:
After adding a few users and a few project/tiles, someone asked if they should be getting email notifications whenever a user made a change to a board that they flagged as 'watched'. Email appears to be set up correctly because if anyone goes to the /setting page and clicks the 'Send test email to yourself', it works. How do we enable email notifications so that whenever a user makes a change, all of the other users get an email notification?

**Comment by xet7** [comment]
Moved to #1160

**Comment by a5dev** [comment]
Just want to confirm: currently there are *no* email notifications in Wekan? (If there are, we are not getting any and so a good starting point for me would be to troubleshoot and get this working and is there a wiki page that would show how it works?). (If there are no email notifications in wekan, then at least I know my system is working as expected). Can you please confirm?
