### ISSUE TITLE
E-mails seem to use the wrong protocol

### ISSUE THREAD

**Issue by yuppox** [wekan/wekan#1797]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.21.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Node Version: 8.11.3
* MongoDB Version: 3.2.20

My root URL uses the HTTP protocol. This isn't ideal but I haven't set up the web front-end, which I assume is how you can get HTTPS. Even though I am using HTTP, links in the e-mail prefix with HTTPS (account invites, board invites).

**Comment by xet7** [comment]
Please see this for using different protocols for email:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

And this for setting Wekan ROOT_URL for http or https, according to final URL:
https://github.com/wekan/wekan/wiki/Settings
