### ISSUE TITLE
Card detail panel: Add member list misaligned

### ISSUE THREAD

**Issue by ePirat** [wekan/wekan#180]
When opening the card detail panel, and clicking on the Add member button, the list which will open has misaligned items, as on the screenshot below. (This happens in Chrome, couldn't test in Safari, as the list won't open there at all, due to #176)
![bildschirmfoto 2015-06-09 um 16 41 11](https://cloud.githubusercontent.com/assets/323210/8060608/ac4353a6-0ec6-11e5-94ea-c68311ef17e7.png)

**Comment by mquandalle** [comment]
Closing because this was fixed a while back, thanks for the report :)
