### ISSUE TITLE
Message box for deleting subtask unreachable

### ISSUE THREAD

**Issue by iwkse** [wekan/wekan#1800]
As it's visible in this recording:

![Recording](https://media.giphy.com/media/NTRTRaUD4Fn1CAe4x3/giphy.gif)

if the task has enough text, when you delete a subtask the message box will scroll down and disappear and can't be reachable by scrolling

**Comment by xet7** [comment]
@iwkse 

What version of Wekan you have?

**Comment by iwkse** [comment]
@xet7 this is tested with latest git version at commit b77be874e0385610cd8efad0526466014ddf101f

**Comment by zypA13510** [comment]
Actually, this is not only an issue for deleting subtask. Deleting a checklist from a card with long description suffers from the same issue too. The confirmation message is off the screen below while the vertical scrollbar is locked at the top.

Tested on 1.23.

## Workaround
Use the mobile version (if using Chrome on PC, open your developer console and enable "toggle device toolbar", select a mobile from the dropdown)
![image](https://user-images.githubusercontent.com/8077540/44322640-d3bdca80-a480-11e8-8c25-19302dcfff02.png)

**Comment by hupptechnologies** [comment]
Working on it.
