### ISSUE TITLE
Access problem - installing via snap, apache vhost and https

### ISSUE THREAD

**Issue by tigger10** [wekan/wekan#1801]
Server Setup Information:
    Did you test in newest Wekan?: Yes
    Wekan version: 1.20
    Operating System: Ubuntu 18.04 server (digital ocean)
    Deployment Method: snap
    ROOT_URL environment variable: /var/www/mysite.org/html

**Problem**
Accessing wekan.

Installed via snap and can see wekan services running. 
I used `snap set wekan root-url="https://mysite.org/board"`

I currently have single domain with letsencypt working, and a single vhost file at /etc/apache2/sites-available/mysite.org.conf              

```
<VirtualHost *:80>
    ServerAdmin admin@mysite.org
    ServerName mysite.org
    ServerAlias www.mysite.org

    DocumentRoot /var/www/mysite.org/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

RewriteEngine on
RewriteCond %{SERVER_NAME} =mysite.org [OR]
RewriteCond %{SERVER_NAME} =www.mysite.org
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```
I'm still newish to linux, and not sure if I need to create another vhost file for wekan, or amend the one above? When I try to access https://mysite.org/board I get a page not found. Nor am I sure about if I need caddy.

Your help is appreciated.

**Comment by xet7** [comment]
Info at #1786

**Comment by tigger10** [comment]
Yes, I looked at those instructions, but still can't access wekan. (I started afresh, with letsencrypt installed on a single domain, and with a mysite.org.conf file). 

I can publicly access directories and files located in /var/www/mysite.org/html/
Though I don't understand when I use `snap set wekan root-url="https://mysite.org/board"` how that that is served in directory in /var/www/mysite.org/html/ as a 'board' folder doesn't exist there. 

I think the issue is to do with setting up the vhost file correctly and specifically what the doc root points to. 

Just to check a couple of things:

1) I need another wekan.conf file, in addition to the original mysite.org.conf? 

2) Assuming yes, in the wekan.conf file, the DocumentRoot is: /var/www/mysite.org/html  which is the same as in mysite.conf - is this correct? 

Any further help appreciated. Thanks.

**Comment by xet7** [comment]
@tigger10 

URL `board` is not served from subdirectory, it's proxy to Wekan at localhost port.

Is there any possibility that you would try using Caddy? I'm not so familiar with Apache.
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
Also if anyone else has Wekan working Apache, please fix wiki page:
https://github.com/wekan/wekan/wiki/Apache

And write some tips to this issue too.

**Comment by tigger10** [comment]
I got wekan working (with letsencrypt too)! 
Basically, created a sub-domain (board.mysite.org), and created the wekan.conf vhost file with the subdomain info, e.g. 
ServerName board.mysite.org
DocumentRoot /var/www/board.mysite.org/html
