### ISSUE TITLE
Hiding notice: "Wekan is loading..."

### ISSUE THREAD

**Issue by tigger10** [wekan/wekan#1802]
## Issue
Server Setup Information:
Did you test in newest Wekan?: Yes
Wekan version: 1.20
Operating System: Ubuntu 18.04 server (digital ocean)
Deployment Method: snap

**Problem description**:
When I edit a card, I constantly see the Wekan is loading notice. (I changed to https, and seems to take a bit longer load?). Is there a way of suppressing this message?

Thanks

**Comment by xet7** [comment]
Please set root-url correctly

**Comment by Julianoe** [comment]
Just wanted to share that i had the same problem and did not manage to identify its source. I thought this was the normal (weird and annoying) way Wekan was built and almost switch to another tool. It was obviously only the same little problem: i had not defined root url with https but with http.

Anyway thanks for sharing your issue, it helped me resolve mine!
