### ISSUE TITLE
Card dates/date picker not localized

### ISSUE THREAD

**Issue by Chartman123** [wekan/wekan#1803]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.21
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker

**Problem description**:
![grafik](https://user-images.githubusercontent.com/16020496/43307310-1fa9e57a-917e-11e8-9a2e-3e0100a55959.png)

The card dates are always shown in the English format, this should be localilzed. Also the date picker should be localized. (e.g. German dates: dd.MM.yyyy HH:mm (24 hours))

It could be made configurable in the admin section.

**Comment by Chartman123** [comment]
In one of the last releases the date format shown on the cards switched to a localized format. Thanks for that :) 

However, the calendar itself in the date picker still isn't localized (week still starts with sunday and shows English labels).

**Comment by xet7** [comment]
Moved to #1670
