### ISSUE TITLE
Login forbidden on snap install

### ISSUE THREAD

**Issue by 9a3eedi** [wekan/wekan#1808]
None of my registered users are able to login anymore to my wekan server. Those who are already logged in can still use wekan.

I started facing this problem when I made a new account for someone and tried to login with it. It kept telling me that login is forbidden. I then realized that this problem is occurring for all accounts, after I tried to login with my own account using a different browser. 

There are similar issues about this opened in the project issue list, but I feel that they either didn't figure out a fix properly, or have different deployment methods that are unrelated to this. In my case, I'm using snap deployment on Ubuntu 16.04. The snap auto-updates to the latest version and it's my worry that this may have caused something to break.

I tried checking the logs but I'm not seeing anything interesting show up when the error occurs. Not sure where to go from here.

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.21
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://192.168.0.51/

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*
- *Explain steps how to reproduce*: no idea
- *Attach log files in .zip file)*

**Comment by xet7** [comment]
@9a3eedi 

What is your Wekan snap version?

```
sudo snap list
```

**Comment by xet7** [comment]
@9a3eedi 

Are you sure you are logging in at right url http://192.168.0.51/sign-in ?

**Comment by 9a3eedi** [comment]
It's working now. Not sure what fixed it though. This time I made sure that I was using the above URL, but I doubt that was the real reason it wasn't working. Maybe I was writing the wrong username and password this whole time?

I noticed that when I enter an incorrect username and/or password, I get the "Login forbidden" message, which I feel is misleading, as it makes it sound like the username was recognized but is forbidden from logging in, which led me to open this issue.

Anyways, the issue is fixed so I'll close it.

**Comment by harrypuru** [comment]
I'm getting forbidden login issue,
wekan@wekan:~$ sudo snap list
Name         Version    Rev   Tracking  Publisher  Notes
core         16-2.34.3  5145  stable    canonical  core
hello-world  6.3        27    stable    canonical  -

**Comment by harrypuru** [comment]
wekan@wekan:~$ snap version
snap    2.34.3
snapd   2.34.3
series  16
ubuntu  14.04
kernel  4.4.0-131-generic

**Comment by xet7** [comment]
@harrypuru 

Your `sudo snap list` shows that you don't have wekan snap installed.

**Comment by xet7** [comment]
@harrypuru 

https://github.com/wekan/wekan-snap/wiki/Install

**Comment by harrypuru** [comment]
run the command as per above kb but still getting forbidden issue
<img width="288" alt="wekan issue" src="https://user-images.githubusercontent.com/42250923/43944467-1278d34e-9c90-11e8-9ba3-14e4b6afc4a2.PNG">

**Comment by xet7** [comment]
@harrypuru 

1) At url /sign-in, click Register, at bottom of that page, Register URL is /sign-up . First registered user will be admin.

2) After registering, ignore error about email settings.

3) Login with your new account at /sign-in

**Comment by harrypuru** [comment]
Thanks. It's resolved. Can you please also confirm the wekan password of,
https://github.com/wekan/wekan-mongodb

**Comment by mabushey** [comment]
This seems to be a really common problem, my docker-compose setup is now throwing "Login forbidden" on all user login attempts. I tried changing the bcrypt password in the DB ie: `db.users.update({username: "michael"}, {$set: { "services.password": { bcrypt: '$2a$10$1x4OY5MUTemWvGbJBT8kV.x2mSAxibVGWRQV6x/MeieFfbAKg6iTC' } }})` but that still does not allow login. I'm not very impressed by the choice of Mongo as a "DB".

**Comment by xet7** [comment]
@mabushey 

That bug could have fix at https://github.com/wekan/wekan/pull/2385 that will be included in next release.

This bug is not because of MongoDB. It's just an error in code. When I originally started maintaining Wekan 2016-12, already before that original author of Wekan had created Wekan with Meteor full stack framework, that uses Node.js and MongoDB. Because of all the functionality provided by Meteor, he was able to create Wekan with well organized structure and low amount of lines of code.

There are also other database providers that implement MongoDB server protocol, like AWS providing hugely scalable backend with MongoDB 3.6-compatible DocumentDB, and also by FoundationDB that was recently open sourced by Apple. Wekan has not been tested with those yet, but having them supported is a possibility.

Most software has bugs. When I have looked changelogs of various kanban software, it's the same: bugfixes and new features.
