### ISSUE TITLE
Put in garbage a Board who i get back from the garbage

### ISSUE THREAD

**Issue by scoubidoo** [wekan/wekan#1809]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:Yes
* Wekan version:1.21
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:DOCKER
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- i put long time ago a board on the garbage but last week i want to bring back it from the list of the Boards. When i've done i want to put it on the garbage again, but the board stay on the list and i show it on the list in the garbage.

thanks

**Comment by xet7** [comment]
@scoubidoo 

Please add recorded anim gif about what is the problem. Thanks!

**Comment by xet7** [comment]
No reply received. I did not understand what is the problem.

**Comment by scoubidoo** [comment]
sorry i m in vacancy.. i make screenshoot when i go back
