### ISSUE TITLE
ova download not availible

### ISSUE THREAD

**Issue by crispybrain** [wekan/wekan#1812]
##Virtual box appliance download unavailable: 403 Forbidden

Hi guys,
I wanted to download the virtual appliance Wekan 1.20 on Ubuntu 14.04 from https://releases.wekan.team/, but get a 403 (Forbidden) error.

Are there any other mirrors available?

Thank u

**Comment by xet7** [comment]
@crispybrain 

Please try to download again. I fixed file permission issue.

Please add comment to this issue, does download work now.

**Comment by crispybrain** [comment]
@xet7
Everything works fine now. Thank u
