### ISSUE TITLE
Bad Json file format while exporting board

### ISSUE THREAD

**Issue by xiboulay** [wekan/wekan#1815]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: No
* Wekan version: 1.21
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: ubuntu 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node Version: 4.8.7
* MongoDB Version: 3.2.20

* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

When I export my board, I obtain this html file 

<!DOCTYPE

 html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/2e50e05aec328d8dde7372bf074738e0e3e65ea9.css?meteor_css_resource=true">
<title>Wekan</title><meta name="viewport" content="maximum-scale=1.0,width=device-width,initial-scale=1.0,user-scalable=0"><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="shortcut icon" href="/wekan-favicon.png"><link rel="apple-touch-icon" href="/wekan-favicon.png"><link rel="manifest" href="/wekan-manifest.json">

</head>
<body>

  <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.6.0.1%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fxxx.xxx.com%3A8000%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%22dvyihgykyzec6y1dpg%22%2C%22accountsConfigCalled%22%3Atrue%2C%22autoupdateVersion%22%3A%22502db6005a2462bc8043048ca67ea5c5aab21734%22%2C%22autoupdateVersionRefreshable%22%3A%22daf38a8e747a41514a48b2924b7d11f11f7d9f20%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"))</script>

  <script type="text/javascript" src="/b826f5930be6aa53c92761e8268474bfb6f5fedc.js?meteor_js_resource=true"></script>

</body>
</html>

Is it a problem with the version ?

Thanks

**Comment by xet7** [comment]
Wekan website had download button, on that platforms page is info how to build from source. You don't seem to have correct node.js version, or there is some other issue when you built from source. AFAIK snap and docker versions do work.

**Comment by xet7** [comment]
@xiboulay 

Did you click export with left mouse button? So it would then prompt to download .json file?

Because I think you did right click and saved Wekan webpage.

**Comment by xiboulay** [comment]
No i clicked on the menu item "export board" and not right clik on the page "save as html". I have the same problem as the one described here #1061.

**Comment by xet7** [comment]
@xiboulay 

Did you build from wekan devel branch? What commit?

**Comment by xet7** [comment]
@xiboulay 

Ok it seems that export is broken. I'll look at it.

**Comment by xet7** [comment]
@xiboulay 

Ok reason is that there is new feature that makes it possible to disable Wekan API, and sets it disabled as default: https://github.com/wekan/wekan/commit/6173a7338135c87321be909482ff356d32977de6

Disabling API seems to disable export too.

You can enable API with environment variable: `WITH_API=true`

So in your start-wekan.sh:
```
export WITH_API='true'
node main.js
```

**Comment by xiboulay** [comment]
Thank you for your help, I’ll check that and keep you updated on how it went  🙂

**Comment by xiboulay** [comment]
I confirm you that `export WITH_API='true'` solved the problem 👍.

**Comment by yrkemmi** [comment]
Same issue but how can i fix it on Windows 7 ?
