### ISSUE TITLE
Feature Request: Friendlier emails

### ISSUE THREAD

**Issue by Logicbloke** [wekan/wekan#1817]
Would be nice to have one email per card being sent instead of all of the actions being grouped on a single email.

Each email would have the card's title emboldened along with a history of the comments and actions (change of labels for instance). Pretty much a timeline of sorts.

### Task Whatever
**User 1:** Please add 1, 2 & 3
**User 2:** Done
**User 1:** Looks like there are issues with 2
**User 2:** Fixed, sorry about that.

I think this is better than 

User 1 commented on "Task Whatever":"Hi, first line goes here

More text here

More text here

More text here

And a ton more lines here."

Just an idea. Thank you for your continuing hard work on this project.

**Comment by AuspeXeu** [comment]
Right now there is no grouping at all for email, right?

**Comment by Logicbloke** [comment]
Right now all activity (within a short timespan) is sent in a single email about all tasks.

**Comment by AuspeXeu** [comment]
This timespan seems very short though. I am receiving emails within the same minute. Do you know if there is a way to change this grouping time duration?

**Comment by Logicbloke** [comment]
@AuspeXeu Yes, there's a duration in the source code that can be increased. You'll see a big number and you'll know it's that. It's been a couple of years since I last edited the code for this but you should be able to find it. Maybe try and do a search on the keywords "email" or "duration".

**Comment by AuspeXeu** [comment]
Yeah I think I found it. Its `EMAIL_NOTIFICATION_TIMEOUT` which can be set as an env var. Awesome! Thanks!
