### ISSUE TITLE
Feature request : internal/external link without opening card

### ISSUE THREAD

**Issue by cyberlacqorthez** [wekan/wekan#1818]
Hello,

I'm new here. First, sorry for my poor english.

Wekan user for months, I'd like to suggest a new feature : 
What about clicking a internal/external link without opening card ?
For example, as adding a file is possible, I'd like to add a link (either internal or external) to a card, but not in description. A new symbol like this ![link](https://upload.wikimedia.org/wikipedia/commons/archive/7/72/20180521131402%21OOjs_UI_icon_link-ltr.svg) could appear on card. By clicking this symbol without opening card, you follow the link.
If there are more than one link in the card, I could choose the default one, as I can choose the image appearing on card cover.

I hope it's clear enough. If not, please tell me.

Thanks for the great job and hope this message will help improving this real good tool called Wekan !

Best regards.

**Comment by xet7** [comment]
Hi,
Wekan already has this feature.

For example with this markdown:
```
[Wekan website](https://wekan.github.io) - [Wekan Docs](https://github.com/wekan/wekan/wiki) - [Link to card](https://boards.wekan.team/b/CrHwevz8gFi6vENRZ/test/i8hkEHtceY6riZ2ub)
```
Then you see links in your card this way, for example:

[Wekan website](https://wekan.github.io) - [Wekan Docs](https://github.com/wekan/wekan/wiki) - [Link to card](https://boards.wekan.team/b/CrHwevz8gFi6vENRZ/test/i8hkEHtceY6riZ2ub)

You can find card link here, at card hamburger menu / more / Copy Card Link to Clipboard:
![copy-card-link](https://user-images.githubusercontent.com/15545/43961195-ed128a00-9cbc-11e8-8b62-cbfe7af16cfc.png)

You can see more markdown formatting feature examples at screenshot at top of website https://wekan.github.io
