### ISSUE TITLE
No page animations with reverse proxy

### ISSUE THREAD

**Issue by hwcltjn** [wekan/wekan#1819]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: I believe so yes
* Wekan version: 1.23.0
* Operating System: Ubuntu 18
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any: Caddy and/or Nginx
* Node Version: 8.11.3

**Problem description**:

When using Wekan with NGINX _**or**_ Caddy as a reverse proxy, whenever I work in a board, the page always needs to refresh to carry out an action (open, edit, add, etc...) instead of being nicely animated. This does not happen when Wekan is run with no proxy. 

This happens in the latest versions of Chrome and Firefox.

The GIF's below better visualise the issue.

**With** a reverse proxy and HTTPS (443):
![With a reverse proxy](http://g.recordit.co/dCcaVQUzlq.gif)

**Without** a reverse proxy using only HTTP (80):
![Without a reverse proxy](http://g.recordit.co/D4Hfydmx6B.gif)

**Comment by d3dbit** [comment]
I had the same issue after trying to activate HTTPS via Nginx. 
I tried it some weeks ago and I followed the Nginx's howto that we can find in the wekan wiki. 
I thought that I had a mistake during the configuration and then I decided to disable it (now I am continuing access to wekan via HTTP).
If @hwcltjn has the same issue so I think that it is not my mistake.

**Comment by xet7** [comment]
Yes, root-url needs to be https. It works for me with Caddy, without reload.

**Comment by d3dbit** [comment]
@hwcltjn I am sorry, I can not try it now. I will let you know when I have tried it. Thanks.
