### ISSUE TITLE
Feature Request: One-click Deploy to Openshift?

### ISSUE THREAD

**Issue by brianjking** [wekan/wekan#182]
I'd love to deploy this onto OpenShift, provided by RedHat using the OneClick Installer, similar to that of Heroku's Deploy to Heroku Button.

Thanks! Please let me know how I can help...

https://blog.openshift.com/updated-openshift-deploy-buttons/

https://blog.openshift.com/cloudy-with-a-chance-of-meteorjs/

https://blog.openshift.com/day-15-meteor-building-a-web-app-from-scratch-in-meteor/

**Comment by mquandalle** [comment]
I’m not familiar with OpenShift. Now that v0.9 is released with official Heroku deploy, could you send a Pull Request implementing one-click deploy for Openshift?

**Comment by alayek** [comment]
I am interested in working on this. 

I looked into the blog posts provided above. And Googled a few references.

It seems, to deploy this app, we need to get a cartridge of `node v0.10`, then install mongo on the cloud box; finally execute a shell script to package and deploy the app. It may be doable, but I am not sure at the moment, how to incorporate all this in one-click deployment.

This is the [reference](https://github.com/sachinbhutani/meteor-openshift).

There is another way to do this - we deploy the docker image. I am not well-versed with one-click docker deployment; some pointers would be of help.

**Comment by araczkowski** [comment]
I have a wekan clone on OpenShift Online (v2) PaaS, my installation is based on this Meteor cartridge https://github.com/sachinbhutani/meteor-openshift
so I can confirm that this way is be possible and not so difficult 
the pre-configured wekan application for OpenShift should be probably in a separate repository and in the pull request to the wekan the launch button can be provided (with correct initial_git_url) in the README.md:
```
[![LAUNCH ON OpenShift](http://launch-shifter.rhcloud.com/launch/LAUNCH ON.svg)](https://openshift.redhat.com/app/console/application_type/custom?&cartridges[]=nodejs-0.10&initial_git_url=https://github.com/ryanj/launch-service.git&name=launch)
```
[![LAUNCH ON OpenShift](http://launch-shifter.rhcloud.com/launch/LAUNCH ON.svg)](https://openshift.redhat.com/app/console/application_type/custom?&cartridges[]=nodejs-0.10&initial_git_url=https://github.com/ryanj/launch-service.git&name=launch)



Docker containers are not available on the current (v2) version of OpenShift Online. They are available on OpenShift Origin (which is currently v3)  / OpenShift Dedicated PaaS

**Comment by alayek** [comment]
Ok, but if we have two repos, wouldn't it be a challenge to keep them in sync? I don't know if there are webhooks that triggers any script in other repos.

**Comment by xet7** [comment]
Moved to here from #1721 

Maybe Docker would work for OpenShift?
https://github.com/wekan/wekan-mongodb

Or some other platform?
https://github.com/wekan/wekan/releases

OpenShift is part of not tested platforms. If you get it running, please add new wiki page, and link to it:
https://github.com/wekan/wekan/wiki/Platforms#not-tested-yet

**Comment by xet7** [comment]
https://github.com/wekan/wekan/tree/devel/openshift
