### ISSUE TITLE
fail2ban integration

### ISSUE THREAD

**Issue by hwcltjn** [wekan/wekan#1821]
## Question

Are unauthorised logins to Wekan logged anywhere? I'd like these to be monitored by fail2ban.

I've poked around as much as I could in the snap installation and even logged the output of the NGINX access logs but couldn't find anything.

**Comment by xet7** [comment]
@hwcltjn 

You can look does this package included in Wekan have some options for logging:
https://atmospherejs.com/eluck/accounts-lockout

**Comment by hwcltjn** [comment]
Thanks @xet7, doesn't look like it has any native logging options unfortunately - but if Wekan comes with it included that's great! Is it working though?

I looked at the config of ```accounts-lockout``` in ```/snap/wekan/241/programs/server/packages/eluck_accounts-lockout.js``` and it's set as:

``` 
settings: {
  duration: 15,
  attempts: 5
},
```
I have just tried to login into my account about 10 times - wrongly - and it didn't lock me out.

I've got NGINX setup as a reverse proxy with:
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

**Comment by xet7** [comment]
@hwcltjn 

Maybe that is for fast repeated attempts in very short amount of time? That package has some test in github repo file. I have not tested yet how it works.
