### ISSUE TITLE
Add-Feature: Restrict registration to specific E-Mail domain

### ISSUE THREAD

**Issue by max-marschall** [wekan/wekan#1823]
Hello together,

I ask myself if anyone is still interested in this feature. It is not an issue of course (expect someone like us needs it strictly caused by companies compliance rules). I just want to renew this topic - we also use Rocket.Chat, which already has this feature (and we use it, of course :) )

That should be important for:

- self-hosted Wekan
- Access via Internet or broader network segments is available
- large corporate network with different companies (like us) to restrict access

@xet7 Is this feature inside Sandstorm a feature of sandstorm itself ?

Original Add-Feature request: #1399 

Kind regards
Max

**Comment by xet7** [comment]
@max-marschall 

It's Sandstorm feature.

Pull requests for Wekan welcome.

**Comment by JonasDralle** [comment]
We're hosting this without Sandstorm and we would greatly benefit from this feature.

![image](https://user-images.githubusercontent.com/6533815/50360243-b2203d00-055f-11e9-9b54-ca9c8f203d9d.png)

**Comment by xet7** [comment]
@JonasDralle 

In screenshot above the reason why user is not created is that if there is Admin Panel setting "Invite only" then new users can only be invited at Admin Panel by admin. To have users invite at board there is feature request #2060 

Anyway, Restrict registration to specific E-Mail domain feature is not at Wekan yet.

**Comment by JonasDralle** [comment]
to be honest for our use case registration via RegEx is more useful than invite via Mail.
but it's good that you're aware of the capabilities :)

**Comment by xet7** [comment]
@JonasDralle 

Whoa how you register with RegEx?

I presume you mean REST API.
https://github.com/wekan/wekan/wiki/REST-API

**Comment by JonasDralle** [comment]
I mean that only mail addresses matching a RegEx, e. g. `(.*)@company.com` can sign up. Similar to how NextCloud [is doing it](https://github.com/pellaeon/registration).
<sub>When you scoll down you can see "Admin can limit the email domains allowed to register"</sub>

**Comment by xet7** [comment]
Moved to #3022
