### ISSUE TITLE
Version 1.25 does not start

### ISSUE THREAD

**Issue by xadagaras** [wekan/wekan#1824]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:
* Wekan version: 1.25
* Operating System: Linux / MacOS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* MongoDB Version: 3.2.20
* ROOT_URL environment variable http://localhost:25001:

**Problem description**:
I tried to update to the latest version of Wekan, but I only get an empty response from the server. I tested with Version 1.23, there everything works. Once I update to 1.25, it stops working.

The docker-compose file used is attached as zip file.

[docker-compose.yml.zip](https://github.com/wekan/wekan/files/2276792/docker-compose.yml.zip)

Regards

**Comment by xet7** [comment]
@xadagaras 

Please change docker-compose.yml to:
```
ports:
- 25001:8080
```

**Comment by xet7** [comment]
I would recommend getting newest docker-compose.yml file from:
https://github.com/wekan/wekan-mongodb

and adding your settings to there. Newest settings will always be in that file.

**Comment by xet7** [comment]
Docker Hub image sometimes is broken. quay Docker image usually works better.

Newest Wekan is currently v1.26.

There is currently bug in Docker #1820 .

Snap does not have that bug.

**Comment by xadagaras** [comment]
Ok I've updated to the docker-compose file you mentioned, that one seems to work except for #1820 but that one seems to be still open.

Are there any announcements where someone could easily see when things like port or other configurations change? 

Or what would be the recommended way to keep the docker-compose file updated without loosing custom configurations.

**Comment by xet7** [comment]
@xadagaras 

Snap upgrades automatically, and keeps settings on automatic upgrades:
https://github.com/wekan/wekan-snap/wiki/Install
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

For Docker, I have not looked does DockerBunker have keeping settings feature yet,
you could look at it:
https://github.com/chaosbunker/dockerbunker
If there is no such feature, you could add feature request to new DockerBunker issue.

On Linux and Mac bash shell, you see differences of docker-compose.yml this way:
```
git clone https://github.com/wekan/wekan-mongodb
cd wekan-mongodb
diff docker-compose.yml /home/user/production/docker-compose.yml | less
```
If you have already cloned repo, you can check updates with:
```
cd wekan-mongodb
git pull
diff docker-compose.yml /home/user/production/docker-compose.yml | less
```

**Comment by xet7** [comment]
@xadagaras 

All Wekan changes are announced in ChangeLog:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md

That port 8080 change is here at v1.24:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v124-2018-08-09-wekan-release
