### ISSUE TITLE
[Bug],The new version 1.31(snap) can't save "Requested By","Assigned By"

### ISSUE THREAD

**Issue by flowerpig2012** [wekan/wekan#1828]
## Issue

I  installed the snap version wekan, and set auto upgrade.
yesterday, the wekan auto upgraded from v1.26 to v.1.31.
I found it impossible to save "Requested By","Assigned By" in card.

hope to fix it. thanks.

otherwise, I write a plugin for wekan, connect mongodb,statistics users card in working by everyone. when finished, I will submit the code.

**Comment by xet7** [comment]
I think this is already fixed.
