### ISSUE TITLE
After update to 1.31 one of my boards fails to open, but others do.

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1829]
This is very strange because it should or should not work - but it opens only some boards and our main daily one does not load at all...

Do you any of you experience the same issue with updated snap to 1.31?

And one more question - how to stop auto updates of snap?

**Comment by xet7** [comment]
@therampagerado 

On those boards that do open, when you on browser right click / Inspect / Console, please copy those javascript errors as comment to this issue.

Disabling auto updates is not recommended, because then you do not get bugfixes, security fixes, new features etc. Please help debug this, so I can fix this.

**Comment by xet7** [comment]
Current problem is, that some Wekan boards have a lot of cards, and there is also a lot of Wekan CSS and Javascript. I would need to find a way to make amount of data smaller, so it would load faster in browser.

**Comment by therampagerado** [comment]
Currently we have less than 100 cards in all boards, in the one that can't open we have no more than 25. With 1.26 it's loading very fast after I removed the cards to another board as Trash. The loader appears for no more than 2 seconds at the beginning which is totally ok and then the board is snappy and responsive with 15 users in it.

I can imagine that this is some update related issue but can give you additional info later today.

**Comment by xet7** [comment]
With Docker it's possible to install specific release tag version of Wekan.

Snap is designed for automatic updates.

**Comment by xet7** [comment]
@therampagerado 

Thanks for version info ! At version v1.27 there came new feature [Linked Cards and Linked Boards](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v127-2018-08-12-wekan-release) that has some search features, I'll see if it did slow things down.

**Comment by xet7** [comment]
@therampagerado 

Please test just released new Wekan v1.32, does it fix something.

**Comment by therampagerado** [comment]
This night it has updated to 1.33 and everything is working just fine. Thank you.

The only error I have now is:

49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:163 Uncaught Error: language bg does not exist
    at Function.e.setLanguage (49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:163)
    at 49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:299
    at e.Computation._compute (49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:21)
    at new e.Computation (49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:21)
    at Object.e.autorun (49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:21)
    at 49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:299
    at a (49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:1)
    at HTMLDocument.u (49d258d47418be89a4842fb9d2386a656f07c288.js?meteor_js_resource=true:1)


But this is probably because not all strings are translated?!
