### ISSUE TITLE
After update "Hide system messages" doesn´t work more

### ISSUE THREAD

**Issue by GAm7** [wekan/wekan#1830]
**After automatic update to 1.31 "Hide system messages" doesn´t work more**

**My Setting;**
OS: Debian 9.4.0 with Snap
core     16-2.34.3  5145  stable    canonical  core
mongo32  3.2.7      2     stable    niemeyer   devmode
wekan    1.31       247   stable    xet7       -

I have set with "snap set core refresh.schedule=02:00-04:00" automatic updates.

**Problem:**
Since yesterday I have noticed that system messages are always displayed in the cards. The position of the  "Hide system messages" slider has no impact more.
Also the setting under: Username (upside right) -> Change Settings has no impact more.

**Comment by Lacedaemon** [comment]
I am in the same boat, except I'm on Ubuntu 18.04.

I also cannot save anything in the 'Requested By' or 'Assigned By' fields.

**Comment by xet7** [comment]
At browser / inspect / console is:
```
Uncaught TypeError: this.data(...).setRequestedBy is not a function
```
This is related to latest changes to Wekan. I'll look how to fix this.

**Comment by xet7** [comment]
@andresmanelli is looking into this. Please wait for fixes.
