### ISSUE TITLE
"Hide system messages" switch does nothing

### ISSUE THREAD

**Issue by rinnaz** [wekan/wekan#1834]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.31
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
«Hide system messages» switch stopped working after latest updates:

![peek 2018-08-16 10-39](https://user-images.githubusercontent.com/36293513/44195125-c9c65f80-a140-11e8-8a7b-dacd0c5c8889.gif)

**Comment by andresmanelli** [comment]
Hello, I pushed a fix for this yesterday. I don't know if it was already released.

Did you test with latest version?

**Comment by xet7** [comment]
Wekan v1.32 has been released, it includes fix.

Do `sudo snap refresh` or wait it to update automatically.

Docker users need to update manually.
