### ISSUE TITLE
Board as Card / Card as Card not working

### ISSUE THREAD

**Issue by lichtamberg** [wekan/wekan#1835]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: latest
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx

Referencing #1592

**Problem description**:
When I want to add a linked card/board, it does nothing, see below:

![screencast 2018-08-16 11-07-56](https://user-images.githubusercontent.com/10075/44200415-cafa8b00-a146-11e8-8812-4bef10911b59.gif)

Here is the console output:

```
insert failed: i@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:89:2640
t@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:89:2478
c.Collection.prototype[i]@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:89:6720
@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:111:4415
n/</i[n]@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:111:1717
click .js-done@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:299:223554
u/t[n]/</<@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:217:6103
f._withCurrentView@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:59:23097
u/t[n]/<@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:217:6064
e._withTemplateInstanceFunc@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:59:37698
u/t[n]@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:217:6042
i/</</</<@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:59:27013
f._withCurrentView@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:59:23097
i/</</<@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:59:26974
a/this.delegatedHandler</<@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:59:9120
dispatch@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:19:49877
add/g.handle@https://wekan.flave.world/bdfc19fd3d3c7a13083b48491fecf984752065ea.js?meteor_js_resource=true:19:46580
bdfc19fd3d3c7a13083b48491fecf984752065ea.js:1:6261 
```

Maybe also this console output is related?

![bildschirmfoto 2018-08-16 um 11 27 14](https://user-images.githubusercontent.com/10075/44200644-6429a180-a147-11e8-96ff-bebaa86e5a22.png)

**Comment by andresmanelli** [comment]
Yes, I am looking at this issue. A failed insertion means there's a mandatory model property that is not passed to the insert method.

I didn't find what's missing for the moment..

**Comment by andresmanelli** [comment]
I was kinda opening a PR when I saw #1837 

@xet7  This was actually the cause for this feature to not work !

**Comment by BlackDuck888** [comment]
I have to extend this issue, cards of some lists are not shown in dropdown if i try to link them.

**Comment by andresmanelli** [comment]
Hello, @BlackDuck888 thanks for the feedback.

Could you describe "some" in "some lists"?

**Comment by BlackDuck888** [comment]
If i open the card drop down i got only a gray line for some lists. For most list it is working and i see the cards in drop down, but some lists only showing a gray line in dropdown.

![shoot1](https://user-images.githubusercontent.com/17740762/44397900-2ad7a400-a542-11e8-9c36-148cdf590c46.png)
![shoot2](https://user-images.githubusercontent.com/17740762/44397903-2ca16780-a542-11e8-8fd3-5d3eed4fe03f.png)

**Comment by andresmanelli** [comment]
I see the board is in list view (correct me if I'm wrong). Do the cards are in Default swimlane?

Do you have other swimlanes in board?

**Comment by BlackDuck888** [comment]
Yes it is in list view.
Yes all my cards are in Default swimlane.
I do not use swimlanes in any board right now.

**Comment by andresmanelli** [comment]
I will test in a couple of hours, but could you post  the exported board to see if there are any errors in the cards?

If you switch to swimlanes view do you still see the cards in the list?

Thanks!

**Comment by BlackDuck888** [comment]
I can't / want export this board, because of its data, but i created a new one with same problem.

I also noticed now, that for one Board a swimlane got lists, which is already removed. Same for lists at all, i get lists offered in dropdown from different boards, which are already deleted. 

But the idea with linkin cards is great!

[wekan-export-board-u8LYrx7cndqtJ2nwG.zip](https://github.com/wekan/wekan/files/2306691/wekan-export-board-u8LYrx7cndqtJ2nwG.zip)

**Comment by andresmanelli** [comment]
I opened #1849 to fix this, it works locally for me. I hope it fixes this issue !
