### ISSUE TITLE
FR: DOC: Adding users

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#1838]
Hi 

Can you please add a page about adding users when using snap? I have been searching for how to do it but no luck. Not all of us mambo jumbo node magicians some of us need clear ways to get stuff installed and running..

thanks

**Comment by xet7** [comment]
Added:
https://github.com/wekan/wekan/wiki/Adding-users

**Comment by gerroon** [comment]
@xet7 

Thanks.

"First registered user will be admin" This was the trick, also might need to add the fact that a working email setup is not required. That was the issue that got me and confused initially.

**Comment by xet7** [comment]
@gerroon 

I added emphasis that working email is not required.

Sorry about all the magic. Please ask for new docs where needed.

**Comment by gerroon** [comment]
Thanks looks good
