### ISSUE TITLE
was not found on this server.

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#1840]
Hi

I installed wekan using snap on debian testing. 

I set the port to 3001. I will reverse proxy it.

I open the page "http://127.0.0.1:3001"

I registered my name. 

I logged in

I opened Welcome Board

I created  a new card.

I click on that card

I get the error below in the browser

```
The requested URL /b/LH8Hg3fYC89dcde8C/welcome-board/hJa2FzkX8gJJqkJrR was not found on this server.
```

**Comment by xet7** [comment]
Please set root-url correctly:
https://github.com/wekan/wekan/wiki/Settings

**Comment by xet7** [comment]
It is mentioned on snap install page here:
https://github.com/wekan/wekan-snap/wiki/Install#3-install-wekan-set-url-like-subdomainexamplecomsuburl

**Comment by gerroon** [comment]
I actually did set the root url this was my second install without the root url. I tried the root url in the first install.

Just to make sure though, is the root url same as what will be after the rever proxied url (apache) ? I looked at the examples before but it is a bit not clear to me. Is the root url final url , or how I wnat it to be on the actual server or not kind of thing.

**Comment by xet7** [comment]
@gerroon 

It is the final url.

I tried to make Apache config page more clear:
https://github.com/wekan/wekan/wiki/Apache

**Comment by gerroon** [comment]
For the future reference, in case someone else has the same issue. These are the settings I use



    snap set wekan port='3001'

    snap set wekan root-url='https://MYDOMAIN/wekan'


Apache (under <VirtualHost _default_:443> ) I am running it as a subpage under the main domain  
      
      ProxyPassMatch   "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:3001/$1"                                                                                                                           
      ProxyPass        "/wekan" "http://127.0.0.1:3001/wekan"                                                                                                                                    
      ProxyPassReverse "/wekan" "http://127.0.0.1:3001/wekan"

**Comment by xet7** [comment]
@gerroon 

Thanks! I added those settings to wiki:
https://github.com/wekan/wekan/wiki/Apache
