### ISSUE TITLE
Can we swap some fields in the cards?

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1842]
Can we swap the order of the color lables and the card title so that when we have long title it will show first on the card.

Currently the lables are shown first and there's empty space above the long title.

I think that the color lables can be on the same row as the date. It should not interfere.

**Comment by xet7** [comment]
Screenshot please.

**Comment by xet7** [comment]
or mockup

**Comment by therampagerado** [comment]
![fieldswap](https://user-images.githubusercontent.com/11251370/44269152-5e61b800-a23c-11e8-9f8a-a4767a79c139.png)

**Comment by therampagerado** [comment]
Can we move if labels after

if getSpentTime
.date
+cardSpentTime

Wouldn't it show them on the same row if only one date is shown in the mini card?

**Comment by hever** [comment]
You saved absolutely minimum space and it's ugly, I'll do nothing and give it back to original place.
