### ISSUE TITLE
Time tracking

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#1843]
I've been asked to add touch times per-member/card. Since cards and boards now both have spentTime and isOvertime fields, I thought it might make sense to discuss and possibly re-think how this timing information is stored in the database.

My current thought is to split this information out into a separate collection. As it can apply to cards or boards-as-cards, I'll refer to it as a task duration.

A task duration would have:
- a unit of time (minute, hour, day, week, sprint, month, quarter, year) 
- a planned value
- an actual value
- an overtime flag
- a rate of time (total, per day, per week, per sprint, per month, per quarter, per year)
- a boardId
- a cardId
- a userId [optional]

Does this fit with the direction the project is going in and do you see any negatives to this approach?

**Comment by xet7** [comment]
Moved to #812
