### ISSUE TITLE
Feature Request: Add progress bar indicator to checklist completion (like Trello)

### ISSUE THREAD

**Issue by coursemyhorse** [wekan/wekan#1847]
Tested on instant sandstorm demo from Wekan website Version 1.20.0~2018-07-18

In Trello under a checklist you can see the progress of the completion rate of the checklist, by looking at the bar at the top which updates in real time. This feature request would be to add this to Wekan.

i.e. If items 1, 2 and 3 were checked off as complete in the below list, this shows a progress bar that is 75% complete:

1: Start
2: Do stuff
3: Do more stuff
4: Finish

![trello_checklist_progress](https://user-images.githubusercontent.com/18658093/44407900-24075c00-a557-11e8-8495-38e1f6439fa4.jpg)

**Comment by therampagerado** [comment]
Like!

**Comment by mfilser** [comment]
i find this feature also good to have :+1:
