### ISSUE TITLE
Feature Request: Add checklist functionality to be able to hide completed items (like Trello)

### ISSUE THREAD

**Issue by coursemyhorse** [wekan/wekan#1848]
Tested on instant sandstorm demo from Wekan website Version 1.20.0~2018-07-18

In Trello you can toggle between displaying and hiding completed items. The completed items are also more clearly defined with a strikethrough, but that is for a different debate.
This is helpful when dealing with long deployment plan item lists of over 100 tasks and you only want to filter on the remaining tasks, because they will not always complete in order.  Basic example below. This feature request would be to bring Wekan in line and add this functionality.

Viewing all tasks even those completed:

![trello_checklist_toggle_seeall](https://user-images.githubusercontent.com/18658093/44409020-734e8c00-a559-11e8-9aa6-d40fd7a51097.jpg)

Viewing tasks where completed are hidden:

![trello_checklist_toggle_hide_completed](https://user-images.githubusercontent.com/18658093/44409063-86f9f280-a559-11e8-9641-379f40c2ff1d.jpg)

**Comment by therampagerado** [comment]
Like

**Comment by jkornobis** [comment]
@therampagerado add a thumbs up in reaction section to voting for ;)

**Comment by therampagerado** [comment]
Does github count my posts? Am I gonna get to the next level soon? :)

**Comment by SiGmAX666** [comment]
This is a fantastic feature, I hope the devs can do it for Wekan.

**Comment by mfilser** [comment]
very useful feature :+1:

**Comment by xet7** [comment]
This is now implemented by @marc1006 at https://github.com/wekan/wekan/pull/3167 and will be in next Wekan v4.14.
