### ISSUE TITLE
"Import board from Wekan" header won't go away

### ISSUE THREAD

**Issue by ocdtrekkie** [wekan/wekan#1850]
## Issue

**Server Setup Information**:

* Wekan version: 1.33
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Sandstorm

**Problem description**:
- Go to menu and Import board
- Select Import board from Wekan
- See scary warning, decide not to overwrite board
- Hit the back arrow to the left of "Import board from Wekan" header
- It goes back to the board view... but the header is stuck.

![image](https://user-images.githubusercontent.com/4399499/44440348-4d42df00-a58d-11e8-9070-0c9ea669fb51.png)

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
