### ISSUE TITLE
Can't edit card in a board after adding an other member

### ISSUE THREAD

**Issue by konandrum** [wekan/wekan#1854]
## Issue

**Server Setup Information**:

* Wekan version: 1.35.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker swarm with reverse proxy traefik
* Node Version: the given one with the docker image
* MongoDB Version: 3.4

**Problem description**:

If I create a board with no other member, I can manage all.
If I add a new member, I can't edit a card => blank page. Here is the error in the console:

Exception in defer callback: TypeError: Cannot read property 'username' of undefined
    at https://wekan.idci-consulting.fr/e59a9994f1e722905dcdcfabc7f5c07b5c8e1cbf.js?meteor_js_resource=true:299:243519

**Comment by xet7** [comment]
Wekan only works with MongoDB 3.2. There is attachment upload crash bug on MongoDB 3.4.

**Comment by konandrum** [comment]
I change to MongoDB 3.2 and the bug still present

**Comment by Davidbrcz** [comment]
Is it the same as my non-issue  https://github.com/wekan/wekan/issues/1691 ?

**Comment by konandrum** [comment]
Ok, fixed with ROOT_URL: "https://..." instead of "http" !
Thx
