### ISSUE TITLE
Can't delete a removed board from the recycle bin

### ISSUE THREAD

**Issue by konandrum** [wekan/wekan#1855]
## Issue

**Server Setup Information**:

* Wekan version: 1.35.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker swarm
* Node Version: the given on with the docker image
* MongoDB Version: 3.2

**Problem description**:

I can't delete a removed board from the recycle bin.
Here is the error in the console: Uncaught TypeError: this.currentData is not a function

**Comment by xet7** [comment]
Moved to #1625
