### ISSUE TITLE
Feature Request: At each board, have board-specific roles

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1861]
Roles should have:
- Role name, example: client
- Role permission, example: Admin / User / Comment only / No comments
- Role color, that is round line around the avatar image

For each user on board, when role is selected from list, all role properties are applied.

Only board Admin can change roles.

**Comment by therampagerado** [comment]
Yes, this is a must.

The roles must be editable so everybody can add or remove roles and each action in the kanban should have settings in this area - from moving cards, to deleting lists, boards, etc. At the moment everybody can do virtually everything with the board, deface and ruin the work of many in the company and even stop work at all.

**Comment by xet7** [comment]
@rhelsing 

In your `Comment only` permissions PR https://github.com/wekan/wekan/pull/925 what does this mean?

models/lists.js:
```
return allowIsBoardMemberNonComment(userId, Boards.findOne(doc.boardId));
```

- What does it do?
- Did you name it correctly? Or, should is be renamed to something more descriptive?
- Do you already have permissions for `No comments` somehow? So for that users comments are not shown?

Some related PRs here:
https://github.com/wekan/wekan/pulls?q=is%3Apr+permission+is%3Aclosed

**Comment by rhelsing** [comment]
<img width="715" alt="screen shot 2018-08-31 at 8 48 43 am" src="https://user-images.githubusercontent.com/392594/44913213-b39ccf80-acfa-11e8-8c6c-26cb29fda340.png">
I believe all references to 'allowIsBoardMemberNonComment' should be changed to 'allowIsBoardMemberNonCommentOnly' to be more descriptive even though that is a bit more verbose. It could be refactored to 'allowIsBoardMemberCommentOnly' to be cleaner descriptively, but that would require more (possibly bug inducing) changes to the codebase. I believe I named it that to be as minimally intrusive as possible to the existing codebase.

**Comment by xet7** [comment]
Currently at Wekan code, problem is not to do the least intrusive change. More important is to make code clearer and have consistent naming. For example, there is still references to archives in code and database, it should be renamed to recycle bin like it's at translations already.

**Comment by xet7** [comment]
Roles for more hidden fields, and add role selection to admin panel #802

**Comment by xet7** [comment]
Moved to #3022
