### ISSUE TITLE
Feature: Table view

### ISSUE THREAD

**Issue by ehausen** [wekan/wekan#1862]
Hello,

It's wonderful to see this project doing well!

I didn't find any previous mention about creating a table view.
Could be very useful in displaying cards/tasks, but also reports.

- View task in a table-style view

Feature ideas:
- Sort columns
- Sum selected tasks (rows) field values (for example estimated tasks sum, Statuses: "Done: 5", "In Progress: 3" etc) 
- Configure visible columns
- Reorder columns
- Group tasks (rows) by a field 
- Group tasks by multiple fields (maybe multiple tags or statuses for ex. or Date range?)

Attached a screenshot from the Clickup webapp for inspiration.

![screen shot 2018-08-28 at 12 11 44](https://user-images.githubusercontent.com/6204129/44713888-bad69a00-aabc-11e8-8330-c777c7a3ea49.png)

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4479
