### ISSUE TITLE
Feature Request - ability to contact application admin

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#1868]
It would be helpful to have somewhere that allows users to contact the application administrator(s) (the ones who can access Admin Panel), or at the very least, lists the administrators. 
I think this might best be located on the sign-in/registration page.  Adding this feature would allow for users to report issues, and, if registration is disabled, request access to the application.

**Comment by rjevnikar** [comment]
@xet7  in settings you've added customHTMLafterBodyStart and customHTMLbeforeBodyEnd what are the plans for these fields? Is it HTML that will appear on all views, or just the ones when a user is logged in? I'm looking for a way of putting a link to an internal support page on at least the views you can access when not logged in, and don't want to duplicate your work.

**Comment by xet7** [comment]
@rjevnikar 

I added my current plans to #2218 but I did not get it working yet, help would be very welcome.
