### ISSUE TITLE
Wekan crashing with 12-15 users

### ISSUE THREAD

**Issue by a5dev** [wekan/wekan#1870]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes

I have Wekan set to auto update and it’s using the latest build. When we test it with only about 12-15 users, Wekan will become unresponsive. At first we thought the workstations needed more RAM (thinking since it is a JS app all of the work was offloaded to the clients). But that did not resolve the issue. 

Next we bumped up the Wekan VM to 4 processors and 24gb of RAM. Tested again but it still crashes/becomes unresponsive after using for only 10 minutes.

The latest thing we noticed was that in linux (the wekan server), the Node process is running up to 100%. Is there a way to optimize node or make a node cluster? Or is there a parameter in the Wekan config that needs to be changed? 

Wondering how other organizations are able to use Wekan.

**Comment by xet7** [comment]
Moved to #1672

**Comment by xet7** [comment]
For latest Wekan some user reported that adding index to MongoDB did return CPU usage to normal. But that can depend on server configuration.

For fast single CPU core usage, at AWS C4 instance type has most raw CPU power, according to this:
https://forums.aws.amazon.com/thread.jspa?threadID=229648

For cheap dedicated servers, for example there is Hetzner:
https://www.hetzner.com/?country=en

At AWS, it's possible to setup for example ECS cluster:
https://github.com/wekan/wekan/wiki/AWS

And I do plan to make it possible to move files outside of MongoDB #142 

For MongoDB, there is issue about adding index to Wekan #1709 , that could probably help too.

I welcome any help with testing and debugging performance.
