### ISSUE TITLE
JSON export

### ISSUE THREAD

**Issue by hingerlanton** [wekan/wekan#1873]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:  YES
* Wekan version: 1.39.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Debian 9.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): default
* Node Version: default
* MongoDB Version: default
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
exporting an board only exports "old" cards. only card created with (maybe) version 1.35 gets exported. Newer created cards are missing in the JSON. New created lists and lanes gets exported, only new created cards are missing.

i have installed a new snap 1.39 Version. Same behavior.

**Comment by ymeramees** [comment]
Same issue with 1.35.0 and 1.41.0 built from source.
