### ISSUE TITLE
Apache Proxy (Question)

### ISSUE THREAD

**Issue by BlackDuck888** [wekan/wekan#1875]
## Issue
First everything seams to work correct, i am not sure if this is an error

My Webconsole in Firefox shows 
"Firefox kann keine Verbindung zu dem Server unter wss://myserver.dyndns.org/wekan/sockjs/085/e7_wt2pr/websocket aufbauen." must be somethin like "Firefox can't establish a connection to Server ...."

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.41.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu 10.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap 
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache 
* Node Version: v8.12.0
* MongoDB Version: Snap?
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):  https://myserver.dyndns.org/wekan 

**Problem description**:
I don't know it this is the correct behaviour, but seems to me that wekan tries to connect his websockets via wss:// first an then ws:// if https is configured.

i extend my existing with

```
<Proxy *>
  Order allow,deny
  Allow from all
</Proxy>

ProxyPassMatch "^/wekan/(sockjs\/.*\/websocket)$" "ws://localhost:8080/$1"

<Location /wekan>
    SSLVerifyClient require
    SSLVerifyDepth 1

    ProxyPass http://localhost:8080/wekan
    ProxyPassReverse http://localhost:8080/wekan
</Location>
```

like the example in https://github.com/wekan/wekan/wiki/Apache

Is the the correct behaviour or did i something wrong in my apache config.

**Comment by xet7** [comment]
@BlackDuck888 

Does this help?

https://forums.meteor.com/t/websocket-connection-error-with-apache-2-4-proxy/22254/3

**Comment by BlackDuck888** [comment]
I did some tests with this, but i get still one wss:// connection error in webcole of firefox when i open the page. Maybe there is a mismatch with wss:// and ws://

**Comment by BlackDuck888** [comment]
i have an additional question for this, the wiki article example https://github.com/wekan/wekan/wiki/Apache 
look like this

```
<VirtualHost *:443>

    ServerName example.com/wekan

    SSLEngine On
    SSLCertificateFile      /etc/letsencrypt/live/example.com/cert.pem
    SSLCertificateKeyFile   /etc/letsencrypt/live/example.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem
    ServerSignature Off

    ProxyPassMatch   "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:3001/$1"                                                                                                                           
    ProxyPass        "/wekan" "http://127.0.0.1:3001/wekan"                                                                                                                                    
    ProxyPassReverse "/wekan" "http://127.0.0.1:3001/wekan"

</VirtualHost>
```
This is very similar to my setup. 
 
1. Why the ProxyPassMatch does not redirect to the suburl?
2. should it not be "wss://xxxx" for an https connection?

**Comment by xet7** [comment]
@BlackDuck888 

You can try with:
- wss only
- both ws and wss

Apache docs have this example:
https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

I don't know what are correct settings.

**Comment by BlackDuck888** [comment]
Thank you so far.

I will step in this next days with an test setup. Please let this Issue open, i will comment and close it with my results.

**Comment by BlackDuck888** [comment]
I tried many configurations and it ends up for me that it is only working if i change 

`ProxyPassMatch   "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:3001/$1" `
to
`ProxyPassMatch   "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:3001/wekan/$1" `
 
And yes, i am using a sub URL like https://myserver.dyndns.org/wekan, but the [example](https://github.com/wekan/wekan/wiki/Apache) shows that for suburls proxypassmatch does not use the suburl part, mayby a documentation fault.

Can someone crosscheck this?

**Comment by xet7** [comment]
@BlackDuck888 

Thanks! I added it to wiki:
https://github.com/wekan/wekan/wiki/Apache#b-sub-url

I don't currently have Apache installed, so it would be very welcome, if some Apache user could test.

**Comment by BlackDuck888** [comment]
The minor question is, what is the correct proxy target for websockts, if wekan is configured with a sub url?
If i look into nginx and caddy config it seams to be the sub url.
I see that you have changed the Wiki to my settings. OK i think now it is correct for every one.
