### ISSUE TITLE
Feature :Collapse Swimlane

### ISSUE THREAD

**Issue by scoubidoo** [wekan/wekan#1877]
Hi everyone,

what do you think of a option to collapse a swimlane, in my case i have 3 swimlane and one is bigger than the other and it's difficulte to navigate. This swimlane is over but i don't want to set it on the Trash.

Thanks for reading 

regards

**Comment by rc-tw** [comment]
We would really appreciate this feature too!

Collapsing/expanding a swimlane by click on the swimline title would be great. Also a "Collapse all"-Button would be very nice.

regards,
Timo

**Comment by xet7** [comment]
Moved to #2107
