### ISSUE TITLE
Wekan 1.35 : node restart when a user upload attach file at a card

### ISSUE THREAD

**Issue by jcdwekan** [wekan/wekan#1881]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: 1.35
* Wekan version: 1.35
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Centos 7.3
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker image 1.35
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): haproxy
* Node Version: 8.12.0 in image docker 1.35
* MongoDB Version: 3.2.13
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
We have installed :+1: 
- HAproxy to dispatch request to frontend AS 
- frontends AS using image docker 1.35 of wekan .
- a mongo db in replicat set config and oplog use.

When some users are using the same board and are displayed on some differents frontends,
when a user attach a file at a card , node restart on node with the same error message in log of AS :+1:

{"log":"MongoError: no chunks found for file, possibly corrupt\n","stream":"stderr","time":"2018-08-30T12:35:43.566692559Z"}
{"log":"    at Function.MongoError.create (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)\n","stream":"stderr","time":"2018-08-30T12:35:43.566711086Z"}

Never problem if a user attach a file at a card if he is alone connected at a front AS . No restart and no error message in the log of AS. 

- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*
- *Explain steps how to reproduce*

- 10 frontends AS wekan dispatching by nginx or haproxy , and mongodb at backend .
- x users connected at a board and dispatched on differents frontends.
- a user upload a big file " > 1 MO " to attach at a card
- look at logs of frontends .

- *Attach log files in .zip file)* 
trace -plantage-node.txt
[trace -plantage-node.txt](https://github.com/wekan/wekan/files/2361858/trace.-plantage-node.txt)

**Comment by xet7** [comment]
What is AS ?

**Comment by jcdwekan** [comment]
Sorry old school !!! Application server . Container docker wekan/meteor/node  1.35

**Comment by xet7** [comment]
Try newest docker or snap version.
