### ISSUE TITLE
Make Wekan more minimalistic and usable —> Possible Core/Extension Structure with EXTENSIONS MANAGER

### ISSUE THREAD

**Issue by dev-love** [wekan/wekan#1882]
I really like Wekan, but as more and more features are getting implemented, it’s loosing its simplicity.

A potential solution could be to move all features except the most basic ones to extensions. With an extension manager users could decide which extensions to use and which not. 

This would also open Wekan for further contributions from the community. For example, WordPress is so powerful because it offers an enormous amount of plugins by devs all around the world. Additionally maintaining the software should be easier because of the modular structure.

What do you think? Is anyone interested in implementing this structure?

**Comment by xet7** [comment]
No. See https://github.com/wekan/wekan/wiki/FAQ#is-there-a-plugin-system

Wekan is already open for contributions, there is nothing preventing that.

There will sometime be some UI changes to make Wekan more usable.
