### ISSUE TITLE
Date Selectors - Wrong Order

### ISSUE THREAD

**Issue by dev-love** [wekan/wekan#1883]
The date selectors of cards are currently as follows: Received, Start, Due, End

However, if you are planning a task the due date should usually be AFTER the estimated end date. This is because the due date is defined as the last date possible to end a task.

That’s why I would suggest to change the order to: Received, Start, End, Due

Btw, is the field Received absolutely nessecary? The card creation time is automatically logged in a card’s activity. That’s why I think it’s a duplicate information and the date selector can be removed to make the interface more clean and simple.

**Comment by xet7** [comment]
@dev-love 

Reveiced date is not necessarily the same date when card is created.

@rjevnikar 

Do you have idea order of Received, Start, Due, End ? I don't know how it is in projects usually.

**Comment by therampagerado** [comment]
For me this is the logical order:

- received - when a bug or task is found
- start  - when work is started
- due - when it should be done
- end - when it's done

So for me the current order is perfect and most logical. We use only due field in our company.
