### ISSUE TITLE
Cannot move card from one swimline to the other if moving in the same list

### ISSUE THREAD

**Issue by Blackclaws** [wekan/wekan#1887]
## Issue

When moving cards from one swimline to the other it is not possible to move cards to the same list in a different swimline. The card just gets moved down in the same swimlane. 

This happens with long lists which don't fit on the screen at one time. Short lists don't have this problem and moving between swimlanes is not an issue, unless the screen needs to be scrolled for the move to work. 

A possible workaround for long lists is to scroll all the way to the bottom and move then. For short lists moving also doesn't work when the screen needs to be dragged down to reach the second swimlane

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: v1.45
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Archlinux, Firefox 62 on Windows (client)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node Version: See latest docker release
* MongoDB Version: See latest docker release

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*

![wekan_bug](https://user-images.githubusercontent.com/5792929/45315517-ea61b980-b534-11e8-8263-d2ca39e07332.gif)

- *Explain steps how to reproduce*

1) Make a new board
2) Make a second swimlane
3) Add enough cards to one list to make the list scrollable
4) Try to drag cards from the top of this list or anywhere not fully scrolled down to the second lane
5) Try the same from a line next to that one when having to drag down to the bottom of the screen to hit the swimlane

- *Attach log files in .zip file)*

**Comment by xet7** [comment]
@andresmanelli 

This is partially, fixed, but I don't understand why I can't drag to swimlane below, but I need to get dropping position enable from another swimlane.

![drop-strange](https://user-images.githubusercontent.com/15545/45486833-2a0ee800-b765-11e8-929c-be200dcc78e3.gif)

**Comment by andresmanelli** [comment]
Oh ok, I'll try to look at this later today. Thanks for the feedback!

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4883
