### ISSUE TITLE
Scroll bar in long list won't scroll all the way down when populated swimlane exists below

### ISSUE THREAD

**Issue by Blackclaws** [wekan/wekan#1888]
## Issue

When using swimlanes if a list is very long and the second swimlane already has cards in it, it is now no longer possible to scroll the list all the way down anymore using the scrollbar. It still works when using mousewheel scrolling.

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: v1.45
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Archlinux, Firefox 62 on Windows (client)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node Version: See latest docker release
* MongoDB Version: See latest docker release

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*

![wekan_bug_2](https://user-images.githubusercontent.com/5792929/45316020-221d3100-b536-11e8-8b57-425ab579b578.gif)

- *Explain steps how to reproduce*

1) Create a long list that has to be scrolled
2) Add a swimlane
3) Add cards to that swimlane in the same list
4) Scroll down so the second swimlane is in view
5) Try to scroll the top list down using the scrollbar

- *Attach log files in .zip file)*

**Comment by andresmanelli** [comment]
Hello, I tried to reproduce this without success. Is there any other step you did in order to see the issue?

**Comment by Blackclaws** [comment]
I just tried it again with a chrome and firefox on linux and can reproduce the behaviour. I'll try it with another instance on a different server.
