### ISSUE TITLE
Filter feature can't work in v1.47.0

### ISSUE THREAD

**Issue by liny90626** [wekan/wekan#1897]
## Issue - Filter feature can't work in v1.47.0

**Server Setup Information**:

* Did you test in newest Wekan?: Yep
* Wekan version: v1.47.0
* Operating System: Linux x64
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: v8.12.0
* MongoDB Version:  v2.4.9
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): 
Just in local network.

**Problem description**:
I wanna filter the card which belong to me, but failed.  Everything worked fine in last version. 

- *Explain steps how to reproduce*
Enter any board, use Q or choose my user filter to active it. And then you could find this problem.

- *Attach log files in .zip file)*

![20180917090030](https://user-images.githubusercontent.com/15277710/45602873-2a0a3300-ba58-11e8-96e5-0c39373fc374.png)

As the Picture shows, when I choose a filter, I could get the card only belong to me before, but can't in current version.

Please check it. Thank you :)

**Comment by therampagerado** [comment]
Same here - none of the filters work.

**Comment by xet7** [comment]
@Angtrim 

Can you look is this related to adding IFTTT ?

**Comment by xet7** [comment]
Wekan v1.49 has now been released, it has IFTTT and OAuth2 removed. Their development continues at wekan repo edge branch, until they work.

This is how to use snap stable channel, that most Wekan users have installed:
```
sudo snap refresh wekan --stable --amend
```
This is how to use snap edge channel:
```
sudo snap refresh wekan --edge --amend
```
