### ISSUE TITLE
None of the new If this then that features works.

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1898]
What I need to do if  I want to implement some rules?

I've tried:
- adding another user when someone is added - nope
- moving cards when checklist is done - nope
- moving card to top of list if label is added - no effect other than the label is removed automatically after it's clicked.

I could find more uses but those are few of the ones that I would like to implement right away in order to speed the work with the kanban but none of them work.

Do I have to restart snap or something else? Where I can read some docs if available?

**Comment by xet7** [comment]
@Angtrim 

Can you look at this?

**Comment by Angtrim** [comment]
Hi, @xet7 @therampagerado .
I'll look into this today and see what's not working as expected.

**Comment by xet7** [comment]
I will revert to previous working version on Wekan, so that everything works again on snap stable channel.

I will keep new in-progress code on snap edge channel, until it works well.

**Comment by xet7** [comment]
Wekan v1.49 has now been released, it has IFTTT and OAuth2 removed. Their development continues at wekan repo edge branch, until they work.

This is how to use snap stable channel, that most Wekan users have installed:
```
sudo snap refresh wekan --stable --amend
```
This is how to use snap edge channel:
```
sudo snap refresh wekan --edge --amend
```

**Comment by xet7** [comment]
Related issues that got broken when adding IFTTT:
- Tasks can not be assigned #1899
- Filter feature can't work #1897

**Comment by maurice-schleussinger** [comment]
If these issues don't occur with v1.49 I would suggest setting the Latest release to v1.49.

**Comment by danielfaulknor** [comment]
Any update on this?

**Comment by xet7** [comment]
@danielfaulknor 

IFTTT already mostly works on edge:
https://github.com/wekan/wekan-snap/wiki/Snap-Developer-Docs

Moved to #1912
