### ISSUE TITLE
Tasks can not be assigned.

### ISSUE THREAD

**Issue by Montiemedia** [wekan/wekan#1899]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.47.0
* If this is about old version of Wekan, what upgrade problem you have?: No
* Operating System: RHEl 7.5
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): no Webserver
* Node Version: 8.12.0
* MongoDB Version: latest from snap

**Problem description**:
Since the last update of the weekend we have a board, where no tasks can be distributed anymore.
When someone assigns a task, the user briefly appears in it and then it is empty again.
The system messages on the right indicate that the task has been assigned. However, the field remains empty anyway.

The problem ist actual on one board.

EDIT: This happens after a rule, from the new rule framework, was set

**Comment by xet7** [comment]
Thanks ! I will revert changes and add them back later when they are stable.

**Comment by xet7** [comment]
Wekan v1.49 has now been released, it has IFTTT and OAuth2 removed. Their development continues at wekan repo edge branch, until they work.

This is how to use snap stable channel, that most Wekan users have installed:
```
sudo snap refresh wekan --stable --amend
```
This is how to use snap edge channel:
```
sudo snap refresh wekan --edge --amend
```
