### ISSUE TITLE
docker-compose fails because of https://github.com/coreos/bugs/issues/1095

### ISSUE THREAD

**Issue by maurice-schleussinger** [wekan/wekan#1900]
## Issue
Docker-compose is not working for any of the later releases because of https://github.com/coreos/bugs/issues/1095.

## Solution
This workaround: https://github.com/coreos/bugs/issues/1095#issuecomment-350574389

* Did you test in newest Wekan?: yes
* Wekan version: 1.4x
* If this is about old version of Wekan, what upgrade problem you have?: no
* Operating System: any?
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: latest in 1.4x
* MongoDB Version: 3.2.21
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
1. pull latest docker images (on certain OS?)
2. run `docker-compose up`
3. Docker stops with a number of `Directory renamed before its status could be extracted` errors for everything Meteor.

**Comment by xet7** [comment]
@maurice-schleussinger

Please test did I fix it, so I know can I add it to Wekan.

At docker-compose.yml file here:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml#L64

Change it to use this docker image:
```
image: quay.io/wekan/wekan:feature-dockerfile-bsdtar
```
