### ISSUE TITLE
Feature request : be able to export all users boards

### ISSUE THREAD

**Issue by TiibCD** [wekan/wekan#1901]
## Problem description

Hi all !
I'm currently migrating from a virtualBox appliance (v1.18) to a docker solution (latest version of wekan).

So I tried to use the export/import process into a json file, but as an admin I'm not allowed to see the others users' boards. So I can't export all the boards myself.
I think it would be useful to have a super user who can see (not write) all boards and do some maintenance on it because right now if I want to export every boards I have to ask each user to do it ! Which is not easy for them and not their job !

What do you guys think about it ?

Thanks for your help

**Comment by xet7** [comment]
@TiibCD 

All Wekan data is at MongoDB.

Backup VirtualBox MongoDB database that you see port and database name, and restore it to mongodb database name that Wekan Docker container uses. MongoDB server can be inside or outside of Docker container, or use MongoDB authentication in URL. This moves everything. See Wekan GitHub wiki for more info.

https://github.com/wekan/wekan/wiki/Backup
