### ISSUE TITLE
demo webpage not working - This page may be private. You may be able to view it by logging in.

### ISSUE THREAD

**Issue by qknight** [wekan/wekan#1902]
# issue

Your link on your README.md leads to a private or broken WeKAN board.

The link is: https://wekan.indie.host/b/t2YaGmyXgNkppcFBq/wekan-fork-roadmap

```
Board not found
This page may be private. You may be able to view it by logging in.
```

**Comment by xet7** [comment]
@qknight 

Thanks for info! I sent email to server admin asking for fixing that.

**Comment by pierreozoux** [comment]
Sorry, this demo serveur is not really used not maintained. We'll look into it Monday.
Sorry for the disturbance.

Pierre

**Comment by xet7** [comment]
Fixed.
