### ISSUE TITLE
Export/Import error "No comments is required" in v1.49.1

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#1903]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.49.1
* Operating System: Ubuntu

**Problem description**:
- We have an board since <1.46 and starting a new turn. So we exporting the old and want to import this. (around 30 card, 2 swimlanes, 8 Lists)
- We can allocate the users (all green)
- In the next step a Error 400 is showing (yellow box) and the board is not imported.

It would be nice, if there any chance to see whats happend on the import and where is the error. This is the third time, that we have this problems.
i try some analyse for the json, but its correct.. Also remove some values (activities, cards, ..) but there is no effect.. Wekan is a nice board, but more information on this way would be really nice..

**Comment by xet7** [comment]
If you use Snap, what does this command show after you see Error 400 ?
```
sudo snap logs wekan.wekan
```
If you use Docker, what does this command show after you see Error 400 ?
```
sudo docker logs wekan-app
```

**Comment by sfahrenholz** [comment]
This is the log from server

![grafik](https://user-images.githubusercontent.com/6977657/45885442-c0bb5480-bdb6-11e8-90b7-6feea087677f.png)

**Comment by xet7** [comment]
@sfahrenholz 

I think you are using Wekan edge tag, it has buggy new features like IFTTT #1898 and OAuth2. It would be better if you use some release tag or latest tag.

Anyway, that bug exists in all versions of Wekan. You can fix it manually by opening exported Wekan JSON file in text editor, and replacing:
```
"isCommentOnly":false}
```
with
```
"isCommentOnly":false,"isNoComments":false}
```
and then importing that Wekan JSON to Wekan.

This bug is because recently I added new feature member role "No Comments" #1861 . I have not fixed this yet.

**Comment by xet7** [comment]
@rjevnikar 

Do you have time to fix Wekan JSON export issue I described in comment above?

**Comment by sfahrenholz** [comment]
Thanks for the help, i can reported the board.
But there is another 400 Error after importing
![image](https://user-images.githubusercontent.com/6977657/45915898-77721000-be5d-11e8-815f-c4fcde35caf0.png)

maybe this is already important to know...

**Comment by xet7** [comment]
Thanks, I have seen also that, but forgot to mention. If all members are mapped, usually when that happens, board is imported anyway.

**Comment by crispybrain** [comment]
> @sfahrenholz
> 
> I think you are using Wekan edge tag, because you have Wekan version 1.49.1. It has buggy new features like IFTTT #1898 and OAuth2. It would be better if you use some release tag like v1.49 or latest tag.
> 
> Anyway, that bug exists in all versions of Wekan. You can fix it manually by opening exported Wekan JSON file in text editor, and replacing:
> 
> ```
> "isCommentOnly":false}
> ```
> 
> with
> 
> ```
> "isCommentOnly":false,"isNoComments":false}
> ```
> 
> and then importing that Wekan JSON to Wekan.
> 
> This bug is because recently I added new feature member role "No Comments" #1861 . I have not fixed this yet.

Worked for me! Thanks
