### ISSUE TITLE
Send email using private server with self signed certificate 

### ISSUE THREAD

**Issue by Asterix45** [wekan/wekan#1905]
## Send email using private server with self signed certificate 

**Server Setup Information**:

Using last version of Wekan installed by snap on Ubuntu server 16.04, no frontend server, working on port 8080

**Problem description**:
- Would like to understand how to make Wekan email works with company email server.
- Current configuration: 
```
sudo snap get wekan 
mail-url   smtp://user@192.168.1.1:25/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false
```
- This is working for a java app:
```
spring.mail.host=192.168.1.1
spring.mail.username=user@domain.com
spring.mail.password=
spring.mail.port=25

spring.mail.properties.mail.smtps.auth = false
spring.mail.properties.mail.smtps.starttls.enable = false
spring.mail.properties.mail.transport.protocol = smtp
spring.mail.properties.mail.debug = false
spring.mail.properties.mail.smtps.host=192.168.1.1
spring.mail.properties.mail.smtps.port=25
spring.mail.protocol=smtp
``` 
This is what happen when testing email from admin panel
![immagine](https://user-images.githubusercontent.com/1956608/45877967-c5284300-bd9f-11e8-8eea-9fdcde6d61f7.png)

**Comment by dkrtic** [comment]
The solution/workaround for using email servers (and also other services) with self signed certificates is to add setting for [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file). I have tested the `Email.send` meteor function using this method and I was able to send email using postfix server with self signed certificate.
If no one else has the time I could make a PR based on [this commit](https://github.com/wekan/wekan/commit/55252300c601ea40dc8adad1887397b31ceb0bb2). 
I just need the name for the setting.

**Comment by xet7** [comment]
@dkrtic 

That setting could be `EMAIL_NODE_EXTRA_CA_CERTS`. You can add PR.

**Comment by MamaKonda** [comment]
You can actually get this to work with the current version of Wekan just by editing the docker-compose.yml. You just have to map the authorities' root certificate (or an intermediate one) into the container and then use the [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) env variable to inform node.js about the certificate. Works like a charm for me with my self-generated certificate.

```
services:
  ...
  wekan:
  ...
    environment:
      # ==== EMAIL SETTINGS ====
      # Email settings are only at MAIL_URL and MAIL_FROM.
      # Admin Panel has test button, but it's not used for settings.
      #   see https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
      #   For SSL in email, change smtp:// to smtps://
      # NOTE: Special characters need to be url-encoded in MAIL_URL.
      #       You can encode those characters for example at: https://www.urlencoder.org
      #- MAIL_URL=smtp://user:pass@mailserver.example.com:25/
      - MAIL_URL=smtps://user:pass@mailserver.tld:465/
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/selfsigning-root-ca.crt
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw
      - ./selfsigning-root-or-im-ca.crt:/usr/local/share/ca-certificates/selfsigning-root-ca.crt:ro
```
