### ISSUE TITLE
Export data from cards

### ISSUE THREAD

**Issue by thothga** [wekan/wekan#1907]
## Issue
_This may be covered in another issue, however I'm a newb and the thread isn't clear._  

I've created some custom fields (e.g. Estimated Hours to Complete Task) and I would like to be able to extract that information from all the cards on a board.   I don't currently see a feature to extract the board data.

* Wekan version:  1.49

Thanks for all the efforts -- I'm impressed with the product thus far.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
