### ISSUE TITLE
Question: why quay.io/wekan/wekan ?

### ISSUE THREAD

**Issue by lonix1** [wekan/wekan#1914]
I always pull images from the docker hub - `docker pull wekanteam/wekan`. 

The documentation mentions "quay.io" many times, but never explains why. It also mentions that quay is preferred.

Why should I use quay instead of the docker hub?

**Comment by xet7** [comment]
Because Docker Hub images many times have been broken, while those built by quay work. Quay also builds docker containers much faster than Docker Hub.

**Comment by lonix1** [comment]
@xet7 So the benefit is for those who want the latest bits quickly. If we are on a slower adoption cycle, I assume that docker hub is ok.

Thanks for the explanation.
