### ISSUE TITLE
Exception while invoking method 'importBoard' Error: Is no comments is required

### ISSUE THREAD

**Issue by crispybrain** [wekan/wekan#1917]
Hi!

I'm trying to import a json exported from v1.20 into v1.50. The following Exception occurs:

> Sep 27 13:28:49 awm-wekan wekan.wekan[949]: Exception while invoking method 'importBoard' Error: Is no comments is required
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at packages/matb33_collection-hooks.js:127:46
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at WekanCreator.createBoardAndLabels (models/wekanCreator.js:196:35)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at WekanCreator.create (models/wekanCreator.js:670:26)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at DDPCommon.MethodInvocation.importBoard (models/import.js:27:20)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at packages/check.js:128:16
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Sep 27 13:28:49 awm-wekan wekan.wekan[949]: Sanitized and reported to the client as: Is no comments is required [400]

 GUI only shows "400" as "failure code".
Can u guys help?

Cheers 
Dan

**Comment by crispybrain** [comment]
(Re-)Importing the export into the v1.20 works fine.

**Comment by rjevnikar** [comment]
This looks to be related to #1903 - have you looked through that discussion?

**Comment by xet7** [comment]
Moved to #1903
