### ISSUE TITLE
[Enhancment Request] Export Board: JSON contains version of creation board and exported

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#1922]
## Enhancment

In the past, there where a lots of Problems with export and importing of board. I think to identify some problems the Json file contains the version where the board was created/imported and on exporting the export version

Example:
```Json
{
	"wekanCreated": "1.51.1",
	"wekanExported": "1.60",
	"_format": "wekan-board-1.0.0",
	"_id": "3AYCzBtqQcKsTWkvg",
	"archived": false,
	"color": "belize",
	"createdAt": "2018-08-23T06:52:03.224Z",
}
```

on this i hope to see the changes between the versions and can manually fix a problem

**Comment by xet7** [comment]
Well, maybe for future versions.

I can not change and re-release old versions.

**Comment by xet7** [comment]
But the actual solution to import/export errors is not adding version number.

Actual solution is to make script that:
- does `git checkout` to each Wekan version
- extracts database schema from wekan/models/* including import/export, and wekan/server/migrations.js
- makes sure every old schema is migrated to newest Wekan version
- detects file format of imported JSON, and makes sure every old import/export file format can be imported.

Related #1695

**Comment by sfahrenholz** [comment]
For me the current solution is to create on every version a new board, and exporting it. But this is very inconvenient..
I think you can understand my problem, when a new sprint is beginning and we cannot create a "fork" from an old board.. 

However the solution looks at the end, it should work

**Comment by xet7** [comment]
@sfahrenholz 

Yes it is inconvenient currently.

Sorry, I'm currently in work project that has very tight deadline, so I can not code this enchancement yet.

I really depend on all Wekan contributors to and companies using Wekan to help and submit pull requests for fixes. If it's only me coding this, progress is slow. Wekan is community effort.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
