### ISSUE TITLE
Openshift Setup from template failure

### ISSUE THREAD

**Issue by lberk** [wekan/wekan#1923]
## Issue
Openshift setup fails with error:
Wekan backed by MongoDB failed to be created.
Cannot create route "wekan". the namespace of the provided object does not match the namespace sent on the request
The following service(s) have been created in your project: wekan.
Applied Parameter Values
These parameters often include things like passwords. If you will need to reference these values later, copy them to a safe location. Parameters MONGODB_USER, MONGODB_PASSWORD, MONGODB_ADMIN_PASSWORD were generated automatically.

I'm trying to test this locally before pushing to our production instance

**Server Setup Information**:
oc cluster up
oc login -u developer
cd /path/to/wekan/openshift/
oc create -f wekan.yml

* Did you test in newest Wekan?:
latest git pull wekan.yml
* Wekan version:
% git describe
v1.51

* Operating System:
Fedora (using openshift v3.9.0 install from dnf)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
% oc version
oc v3.9.0
kubernetes v1.9.1+cbc5b49
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
as specified in wekan.yml
* MongoDB Version:
Container Image: centos/mongodb-32-centos7

* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):
tested with https://wekan.example.com/ (specified by FQDN in openshift template setup)

**Problem description**:
After setting up the template (as described above), working through the openshift template setup, the only field I enter any info into is the FQDN field (all others auto populate or get randomly generated), I tried wekan.example.com for starters.  Got the following error;

Wekan backed by MongoDB failed to be created.
Cannot create route "wekan". the namespace of the provided object does not match the namespace sent on the request
The following service(s) have been created in your project: wekan.
Applied Parameter Values
These parameters often include things like passwords. If you will need to reference these values later, copy them to a safe location. Parameters MONGODB_USER, MONGODB_PASSWORD, MONGODB_ADMIN_PASSWORD were generated automatically.

There are no logs in the wekan deployment because it was never provisioned successfully

**Comment by xet7** [comment]
@InfoSec812 

Can you look at this?

**Comment by lberk** [comment]
The issue is that the template default namespace 'openshift' isn't allowed by your normal developer.  Ideally it'd default to the currently used project/namespace, but it doesn't look like openshift supports that for templates (why?!).

For those who stumble across this issue later, change the 'Namespace' template parameter to your current 'project' for example;

oc cluster up
oc new-project wekan <---- then name the namespace 'wekan' in the template
oc create -f wekan.yml

**Comment by xet7** [comment]
@lberk 

Thanks! I added link to this solution to wiki:

https://wekan.github.io => Download Stable => OpenShift

https://github.com/wekan/wekan/wiki/OpenShift

**Comment by InfoSec812** [comment]
> The issue is that the template default namespace 'openshift' isn't allowed by your normal developer. Ideally it'd default to the currently used project/namespace, but it doesn't look like openshift supports that for templates (why?!).
> 
> For those who stumble across this issue later, change the 'Namespace' template parameter to your current 'project' for example;
> 
> oc cluster up
> oc new-project wekan <---- then name the namespace 'wekan' in the template
> oc create -f wekan.yml

OpenShift WILL default to the current namespace if you just leave the namespace field out of the template.

**Comment by lberk** [comment]
@InfoSec812 then please take a look at https://github.com/wekan/wekan/pull/1930
