### ISSUE TITLE
Feature Request: Restrict Creation of Boards

### ISSUE THREAD

**Issue by D347HxD** [wekan/wekan#1928]
I'm not sure the exact place to put this, and it's not something too urgent, so I didn't feel a bounty was needed for it.

Though, this suggestion would be simply as the title suggests.

Going further into it, basically it would be nice if from the member list in the admin menu you can restrict the users from creating boards (so they can only access and edit ones they have been added to from an admin or other users who have made boards) or even set a max limit of boards a user can make.

**Comment by jeroenstoker** [comment]
This would be nice indeed. I share my boards with clients and also make them change and add things (so I add them as users). I just want to use it for that purpose, and do not want to have them to have the ability to create new boards that I can't see.

**Comment by xet7** [comment]
Moved to #3022
