### ISSUE TITLE
[Feature Request] Disabling automatic updates over admin-panel

### ISSUE THREAD

**Issue by Nocan456** [wekan/wekan#1929]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.52.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu
* Node Version: 8.12.0

**Problem description**:
Not sure if I'm just missing something but I'd like to be able disabling automatic updates over the admin-panel.
If this is not possible I'd like to know which sites I should block on my FW to disable automatic updates.

**Comment by xet7** [comment]
@Nocan456 

It's not possible to disable Snap automatic updates.

Those that want specific Wekan version without automatic updates use Docker with specific release tag. They test newest Wekan version before upgrading.
https://github.com/wekan/wekan/wiki/Docker
