### ISSUE TITLE
Card references

### ISSUE THREAD

**Issue by tleb** [wekan/wekan#193]
I believe libreboard does not support card referencing (Trello does). Also, there is (at my knowledge) no way of knowing a card's id (in the url on Trello).

**Comment by ePirat** [comment]
The card ID appears in the URL when you click a card. You can link to the card by using that URL.

**Comment by tleb** [comment]
I know, but I don't feel like it is a good solution, or maybe if URLs where *cleaner*.

**Comment by mquandalle** [comment]
Yes the first step is to implement card ids understandable by humans (ie, incremental ids) as Trello of GitHub issue numbers do. Then we can implement a user interface in the markdown editor to support card reference.

**Comment by xet7** [comment]
Wekan already has Link to this card feature.
