### ISSUE TITLE
Feature Request: Simplify the Card Actions menu

### ISSUE THREAD

**Issue by Usernameisalreadytaken99** [wekan/wekan#1939]
Hey all,

The card actions menu could be a lot more user friendly.

Current menu
![image](https://user-images.githubusercontent.com/42954310/46588955-d5ab1e00-cb00-11e8-8adc-434aaa721c32.png)

Improved menu
![image](https://user-images.githubusercontent.com/42954310/46588992-34709780-cb01-11e8-912b-20d076eb0a32.png)

It could probably be simplified even more, but I find that this is what users are actually looking for when opening this menu.

Thanks,

**Comment by xet7** [comment]
Delete Card is in More menu, because many did accidentally delete important card. I did get many worried bug reports about it. It's more safe to move card to Recycle Bin.

**Comment by Usernameisalreadytaken99** [comment]
Good point, I guess it can be Move to Bin in red. The point is to minimize
the number of items in the menu.

**Comment by tugal** [comment]
@Usernameisalreadytaken99 
What do you mean by "to minimize the number of items in the menu" ?
-> Delete this actions ?
-> Add params to hide these actions ?

**Comment by TiibCD** [comment]
I think he means to hide these actions from the "Actions menu" as all of theses actions are available with buttons in the card. Except the "Edit custom fields" action

**Comment by xet7** [comment]
No. Current Wekan UI is in Wekan long time users muscle memory. There is huge support cost if some option suddenly disappears. If you would like to hide something, use upcoming [Custom CSS](https://github.com/wekan/wekan/issues/1690#issuecomment-437356854) or add new Role #1994
