### ISSUE TITLE
Feature request: drag and drop text into Wekan to create new cards

### ISSUE THREAD

**Issue by cannycartographer** [wekan/wekan#1941]
This would allow easy import from a wide range of sources.

Similar to this could be an option to paste text from clipboard to create new cards (which brings up similar issues / questions / possibilities to those mentioned in #1846 )

**Comment by xet7** [comment]
@cannycartographer 

How do you drag and drop text?

I would think that it's only possible to copy and paste text.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
