### ISSUE TITLE
trying to install native implementation of bcrypt

### ISSUE THREAD

**Issue by Madko** [wekan/wekan#1947]
## Issue

**Server Setup Information**: manual installation on CentOS7. Wekan 1.49

* Did you test in newest Wekan?: not yet
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 1.49
* If this is about old version of Wekan, what upgrade problem you have?: I've got this from ages
* Operating System: CentOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 8.11.2
* MongoDB Version: 2.6.12
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): IP

**Problem description**:
- *REQUIRED: We have at least one crash per day. Only 50 users. Can't find any log.
- To reproduce:
-- install from source
-- add some boards, users
-- wait

As a workaround we have a crontab to restart twice a day wekan service.

Only log file says that:
```
oct. 11 11:29:37 wekan systemd[1]: Started The Wekan Service.
oct. 11 11:29:37 wekan systemd[1]: Starting The Wekan Service...
oct. 11 11:29:39 wekan node[31105]: Presence started serverId=kd2Jmv7Mez94ESCak
oct. 11 11:29:39 wekan node[31105]: Note: you are using a pure-JavaScript implementation of bcrypt.
oct. 11 11:29:39 wekan node[31105]: While this implementation will work correctly, it is known to be
oct. 11 11:29:39 wekan node[31105]: approximately three times slower than the native implementation.
oct. 11 11:29:39 wekan node[31105]: In order to use the native implementation instead, run
oct. 11 11:29:39 wekan node[31105]: meteor npm install --save bcrypt
oct. 11 11:29:39 wekan node[31105]: in the root directory of your application.
```

When I try to install bcrypt:
```
-(jeu. oct. 11 11:37:48)--(wekan:/app/vsn/wekan/wekan-1.49/bundle/programs/server)-
[wekan] $ HTTPS_PROXY=http://proxy:8080 meteor npm install --save bcrypt

> bcrypt@3.0.1 install /app/vsn/wekan/wekan-1.49/bundle/programs/server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v46-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.1 and node@4.8.3 (node-v46 ABI, glibc) (falling back to source compile with node-gyp) 
make : on entre dans le répertoire « /app/vsn/wekan/wekan-1.49/bundle/programs/server/node_modules/bcrypt/build »
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /app/vsn/wekan/wekan-1.49/bundle/programs/server/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: on quitte le répertoire « /app/vsn/wekan/wekan-1.49/bundle/programs/server/node_modules/bcrypt/build »
wrote npm-shrinkwrap.json
meteor-dev-bundle@0.0.0 /app/vsn/wekan/wekan-1.49/bundle/programs/server
└── bcrypt@3.0.1 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
```

Seems this URL https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v46-linux-x64-glibc.tar.g is wrong, it should be v48 ? cf https://github.com/kelektiv/node.bcrypt.js/releases

Do you think it's fixed with v1.53.8 ? Do you know where I could find some logs ?

Best regards,
Edouard

**Comment by xet7** [comment]
Newest Wekan does not use native bcrypt because of security issue and no one adding working native bcrypt.

Old Wekan versions are not supported.

**Comment by Madko** [comment]
Do you know why wekan is complaining about that ?

**Comment by xet7** [comment]
@Madko 

Yes. There was security issue in binary bcrypt, so I needed to remove it some time ago.

I tried to add binary bcrypt back after it was fixed, but fix was incomplete and did not work.

If someone is interested in adding binary bcrypt back, he/she can try to get it working and add PR to edge branch.

**Comment by Madko** [comment]
So the regular crashes has nothing to do with bcrypt ?
I will try 1.53.8 and see if it still crash so often. If it does I will open a new issue.

Thanks for your help

**Comment by xet7** [comment]
@Madko 

I have not had crashes with Wekan in regular use, I don't know what you mean.

Bcrypt has nothing to do with any crashes. There is no difference is bcrypt implemented in binary or Javascript.

**Comment by Madko** [comment]
What I mean is that quite often, the nodejs process crash/die. And the only thing I saw in the logs was the line about bcrypt. Is there a way to have more verbosity, or any log ?

**Comment by xet7** [comment]
You have old version of Wekan, Node and Mongo. I would recommed trying to install using newest docker-compose.yml in edge branch. It has Node 8.12.0, Mongo 4.0.3 etc.

**Comment by xet7** [comment]
You see logs at Docker this way:
```
docker logs wekan-app
```

**Comment by Madko** [comment]
As I said I'm not using docker, it's an install from source. We can't use docker. I will check out what versions of nodejs and Mongo are specified n the docker-compose.yml. Thanks for this pointer.

**Comment by xet7** [comment]
@Madko 

Build script for edge is here:
https://github.com/wekan/wekan-maintainer/blob/master/releases/rebuild-wekan-edge.sh

I have not tested it on CentOS 7. You can add PR to add more to it, if you have time.

**Comment by GavinLilly** [comment]
> What I mean is that quite often, the nodejs process crash/die. And the only thing I saw in the logs was the line about bcrypt. Is there a way to have more verbosity, or any log ?

@Madko How many users (registered and active) and boards do you have?

We have an extremely similar sounding issue on our end. We're running Wekan on Docker swarm with 4 instances and it's regularly slow performing with the instances restarting every few hours at a minimum. 3x MongoDB replicaset behind it.

**Comment by Madko** [comment]
It seems that the problem is only from running the bundle. 1.53.8 was so unstable that we couldn't even load any board. We have very few users (< 100), and less then 1000 boards.
Now I've migrated to a docker swarm cluster, running portainer and everything is now fine.
I suspect the old apache from CentOS7 to be part of the problem, because direct acces to wekan was a bit better. With docker, we are now up-to-date, even if we lost the control of the versions.

**Comment by xet7** [comment]
@Madko 

You can specify Wekan version when using Docker.

docker-compose.yml has this line, that gets latest version:
```
image: quay.io/wekan/wekan
```
Every Wekan release has git tag. You see them at https://github.com/wekan/wekan repo `Branch: devel` dropdown, and also at commandline using command `git tag`.

You get specific release of Wekan by using tag of image:
```
image: quay.io/wekan/wekan:v1.69
```

@GavinLilly 

What version of Wekan you are running? I could make new Docker version of Wekan, that uses newer version Meteor 1.8.x, I think it is a little faster.

**Comment by GavinLilly** [comment]
> @GavinLilly
> 
> What version of Wekan you are running? I could make new Docker version of Wekan, that uses newer version Meteor 1.8.x, I think it is a little faster.

We're running v1.58 but we've been seeing this issue for a long time on our previous instance running 6 nodes on v0.78. I'm not sure if it's due to the number of people using our service or something about our configuration.

I took a look at Meteor 1.8. It looks like it could be beneficial to upgrade. Would you create a specific docker tag for 1.8 or would you just merge it into the next version?

**Comment by xet7** [comment]
@GavinLilly 

You can try these Docker tags:

1) Meteor 1.8.x with Node 8.12.0, that node could use more CPU:
```
image: quay.io/wekan/wekan:meteor-1.8
```
2) Meteor 1.8.x with Node 8.11.4, that node could use less CPU:
```
image: quay.io/wekan/wekan:meteor-1.8-node-8.11.4
```
You can see when those tags finish building at:
https://quay.io/repository/wekan/wekan?tab=builds

Meteor 1.8.x does also work with newer MongoDB, like mongo tag 4.0.3.

But I have not got Meteor 1.8.x and MongoDB 4.0.3 working with Snap version, because Node connecting to Mongo did not work on Snap. So they only work on Docker currently.

**Comment by Teutone** [comment]
I believe you have to adjust the Dockerfile for meteor-1.8 because it still builds with meteor 1.6.1 as far as I can see

https://quay.io/repository/wekan/wekan/manifest/sha256:2aa23856ee5a24c49cd9e95efa661b291a2a9b14056ac8c9e2192dec6a940bd8

**Comment by xet7** [comment]
Meteor 1.8 version is defined here:
https://github.com/wekan/wekan/blob/meteor-1.8/.meteor/release#L1
