### ISSUE TITLE
Improve notifications update broke ability to mute notifications

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1952]
https://github.com/wekan/wekan/pull/1948

I got this report at chat from one Wekan user.

@Akuket 

Can you try to fix it?

**Comment by nmd3** [comment]
I'm not the originator of the request, but just confirming that my users are getting notifications on boards marked as muted. I also no longer see system/profile-level notification options, only board level notification options. This is a 1.54 snap install.

**Comment by Akuket** [comment]
https://github.com/wekan/wekan/pull/1954
