### ISSUE TITLE
Issue : linked board won't load anymore

### ISSUE THREAD

**Issue by TiibCD** [wekan/wekan#1955]
## Issue

**Server Setup Information**:
![image](https://user-images.githubusercontent.com/24451989/47090763-cb390480-d223-11e8-8863-8b7dc2387675.png)

**Problem description**:
Hi ! One of our users try to use the linked card feature but had an issue :

Situation you have two boards A and B. You want to create links between them. If you create in the board A, a card as a link to the board B and if you create in the board B the same type of link but to the card you just created in the board A (the linked card), then the result is that the board B can't load anymore ! 

If you try to delete the board B, the board A won't load anymore aswell. We had to remove in the database the card which was the reference of the board to solve this problem

**Comment by xet7** [comment]
@andresmanelli 

Can you look at this?
