### ISSUE TITLE
Issue : copying card with custom fields cause board to stop working

### ISSUE THREAD

**Issue by Jalbladewing** [wekan/wekan#1960]
## Issue

**Server Setup Information**:

![image](https://user-images.githubusercontent.com/17258343/47282010-de5e2280-d5dd-11e8-8cbc-fb44554bb951.png)

**Problem description**:

When copying a card from board A to board B if the card has custom fields the board B stop working, it loads infinitely.

I tried creating that custom fields in the new board (board B) but the result is the same.

![image](https://user-images.githubusercontent.com/17258343/47282339-1d40a800-d5df-11e8-86c6-6722eaa7f83b.png)

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*

![image](https://user-images.githubusercontent.com/17258343/47282212-a73c4100-d5de-11e8-9f8c-82b4d47edb53.png)

![image](https://user-images.githubusercontent.com/17258343/47282247-c4710f80-d5de-11e8-9008-5177ff73f440.png)

**Comment by xet7** [comment]
Try this:
1. Export to Wekan JSON
2. Try to Import Wekan JSON
3. If it does not work, remove Custom Field(s) from JSON and Import
4. If it does not work, remove Activities from JSON and Import

**Comment by Jalbladewing** [comment]
Exporting and importing again works, but some information like the tags and the custom fields of the copied card are lost in the process.

**Comment by Akuket** [comment]
Hi,
The problem seems to be solved in the version 2.64.0 of wekan. Can you try and confirm if it's ok?
Regards

**Comment by xet7** [comment]
I tested this, this is now fixed.
