### ISSUE TITLE
Problem with export/import

### ISSUE THREAD

**Issue by adamkasprzak** [wekan/wekan#1961]
Hi!

I have successfully started Wekan 1.55 via snap on ubuntu.
Now, I tried to export my board from old and trusty Wekan v0.10.1.

I pasted the whole json file source to the field, chose one of the user and on the next screen I've got:
"Your JSON data does not include the proper information..."

Is it possible to move boards between these two releases?

**Comment by sfahrenholz** [comment]
Hey @adamkasprzak 
there are some issues with can maybe help you
#1903 
#1706
#1703

you can try to export an board in 1.55 and show the difference between both versions.
After you know the difference, you can modify the board from 0.10.1

**Comment by xet7** [comment]
Another way is to try to backup Wekan v0.10.1 MongoDB database and restore it to Snap MongoDB:
https://github.com/wekan/wekan/wiki/Backup

And then start Wekan to see does it upgrade database schema automatically.

**Comment by adamkasprzak** [comment]
Thanks!

I think that there is not that much data in my old wekan. We will start a new, fresh version. There is much new functions, which we like very much. So much was changed during this time!

**Comment by xet7** [comment]
Yes. v0.10.1 was released 2015-12-30:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v0101-2015-12-30
