### ISSUE TITLE
Rules issue 

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#1963]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 1.58
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 8.12
* MongoDB Version: latest for this release...
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- I'm trying to setup the new-old rules and again I'm running into issues.

1. I'm trying to add second member when someone is added - this works now but I have the following issue with it. When user 1 is added I need to add user 2 and vice versa... But when I add second rule "User2 adds User1" then when I manually add user2 it disappears from the card, user1 is not added. If I have only rule "User1 adds User2" it works but we have workstations where two or more people do the same thing and I need the people who adds the workstations to each job to be able to select whatever user they like and automatically the rest to join the card. Probably some issue with cycling. If so can't it be fixed by checking if this user that needs to be added is already in the card and if so don't process this rule.
2. When I open rules menu it's sometimes empty and I have to wait some time to see the rules, the same happens when I want to view each rule (what it does). I'm accessing wekan over VPN and probably this causes some delays.
3. I'm missing 'add checklist item (name) to checklist (name)' rule which will fully automate checklist creation in our case. We would like to use the following routine:

Card creation -> checklist named NAME creation
User addition to card -> checklist item NAME creation in checklist NAME

That way we can create checklists with just the needed options for each card.

**Comment by xet7** [comment]
@Angtrim 

Can you look at this?

**Comment by Angtrim** [comment]
Hi @therampagerado, thank you for the feedback.
I'll look at these issues shortly.

**Comment by therampagerado** [comment]
Thank you @Angtrim ! Your work with this feature is priceless!

**Comment by therampagerado** [comment]
@Angtrim - any idea when you will have free time to look into this? :) I'm not pushing you or something simply my female colegues are too fucking lazy to write down few rows of text and they are nagging me wih this.... Sorry once more! Your help is priceless!

**Comment by Angtrim** [comment]
Hi @therampagerado, sorry for the big delay.
The checklist items feature should be already available from release v1.99.
I'll look also at the other issue.

**Comment by therampagerado** [comment]
Yes, I saw it and it works flawlessly! Big thank you!

Just another idea that came to me when creating our rules:

Make (checklist item) in (checklist) if (user name) is added.

Once again, big thanks!

**Comment by Angtrim** [comment]
@therampagerado I'm happy that it works :)
Can you tell me if there is still the users issue?

**Comment by therampagerado** [comment]
No, everything works fine now. But I think it was some sort of 'roundabout' issue because I was trying to make the case work vice-versa. Now I left only the one way option and instructed the people what to do.

**Comment by Angtrim** [comment]
Nice.
Then @xet7 I think you can close this issue.
