### ISSUE TITLE
act-checkedItem and act-checklistCompleted are not translated in French mails

### ISSUE THREAD

**Issue by GuillaumeAmat** [wekan/wekan#1973]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.65.0
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker

---

In notification emails, `act-checkedItem` and `act-checklistCompleted` are not translated at all in French. I only can read `act-checkedItem` and `act-checklistCompleted`.

**Comment by dkessel** [comment]
Might be the same as #1969 , where these texts are not translated anymore.

**Comment by xet7** [comment]
Moved to #1969
