### ISSUE TITLE
Setting OAUTH2_ENABLED has no effect

### ISSUE THREAD

**Issue by hever** [wekan/wekan#1977]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.65.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: 8.12.0

I can't disable OAuth2 with OAUTH2_ENABLED='' or 'false'

**Comment by hever** [comment]
Another point of view:

I was testing OAuth (with rocket.chat) and then want to disable it. With oauth2-disabled I can't do it. So then I set every oauth2- settings to default and "Sign in with Oidc" was still here. Until I find a row in meteor_accounts_loginServiceConfiguration in db and delete it, the button (and the bug #1874) was still there. Maybe there is missing some unconfiguration function, that delete old config.

**Comment by xet7** [comment]
Moved to #1874

**Comment by lindhork** [comment]
This problem is still present when wekan is deployed over source. (tested on newest version)
