### ISSUE TITLE
Feature request: NTLM/Kerberos 

### ISSUE THREAD

**Issue by Michagogo** [wekan/wekan#1979]
It’s really great that you support LDAP for signing in with Windows Domain credentials, but that still requires that the user enter their username and password. It would be amazing if it were possible to add support to hook Wekan up with NTLM and/or Kerberos, thereby allowing the authentication to happen completely transparently from the user’s perspective.

**Comment by xet7** [comment]
@Michagogo 

Well, there is for example this:
https://github.com/staskorz/meteor-ntlm-example

But I have no way to test it. Someone having Windows Domain could look at it.

There is also some SAML packages here:
https://atmospherejs.com/tomwasd/flow-router-seo?q=saml

And https://sandstorm.io already has SAML, but I don't know is it possible to bypass requirement to click SAML login button.

**Comment by danpatdav** [comment]
I would be happy to test any builds that implement Kerberos auth.  I don't even think complete transparency is a requirement.  Clicking a Kerberos/SPNEGO/SAML button would get me 90% of the value.  We don't have passwords in our environment, so the choice is either Kerberos or maintaining local users/passwords (yuck).

**Comment by xet7** [comment]
@danpatdav 

One way to get Kerberos into Wekan would be that some Javascript developer in your company look at adding kerberos package:
https://www.npmjs.com/package/kerberos
and existing LDAP code in Wekan:
https://github.com/wekan/wekan-ldap

Auth0 login #1722 is coming to Wekan sometime, there is already some Meteor code in private repo that works with Auth0 and RocketChat, that needs to be cleaned up and added to Wekan. Auth0 has SAML, OAuth2 etc.

It could also help if someone would [add bounty](https://wekan.team/bounties/index.html) to this issue similarly like there is already for [adding siteminder auth](https://github.com/wekan/wekan/issues/1722).

**Comment by danpatdav** [comment]
@xet7 I think I will just switch over to this thread, as my questions are not Kerberos\NTLM related anymore.  Thanks for the advice.

#538

**Comment by xet7** [comment]
Moved to SAML issue #708
