### ISSUE TITLE
[1.66] Sandstorm: Link / Search buttons at bottom of list do not work

### ISSUE THREAD

**Issue by ocdtrekkie** [wekan/wekan#1982]
1.66 on Sandstorm

Link doesn't appear to do anything, and the highlighted link doesn't look valid. There's a console error for sure when I click the Link link. When clicking on Search a few times, I can see the search box flicker into existence briefly, but immediately disappear.

Tested on Firefox and Edge.

**Comment by xet7** [comment]
Yes, that [Linked Card/Linked Board](https://github.com/wekan/wekan/pull/1592) has not been yet fixed to work on Sandstorm. That feature shows other board's card on current board, and would probably require Wekan Sandstorm version to support multiple boards to be useful.

**Comment by ocdtrekkie** [comment]
I honestly had no idea what these buttons were supposed to do based on the label. If they require connecting multiple boards, it would probably be best to hide them on Sandstorm.

**Comment by xet7** [comment]
Yes, these features do not make much sense when using only one board.

I will hide them.

Enabling multiple boards on Sandstorm would most likely require a lot of work and break workflows Sandstorm users are used to. I think currently getting Sandstorm bugs fixes would be more useful than adding multiple boards.
