### ISSUE TITLE
Show this field on card ?

### ISSUE THREAD

**Issue by tugal** [wekan/wekan#1985]
Hi all,

I'm using custom fields on my board. When i create it in the board menu, there is boolean saying "Show this field on card".

What is the purpose of this field ? i was hoping, that it automatically adding this custom field on all newly created card, but it's not.

i check this fiels on code, it's seem to not be used ..
is it a feature to develop ?

thanks,
nelson

**Comment by xet7** [comment]
Current way Custom Fields work is at wiki:
https://github.com/wekan/wekan/wiki/Custom-Fields

Yes, someone could develop feature that new cards automatically have custom field, and add PR.
