### ISSUE TITLE
Releases should link to the changelog

### ISSUE THREAD

**Issue by C0rn3j** [wekan/wekan#1988]
For example this release 
    https://github.com/wekan/wekan/releases/tag/v1.69
could simply contain this link
    https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v169-2018-11-03-wekan-release

I don't expect anyone to retroactively apply this to all past releases, but it would be great if people didn't need to go hunt down where the changelog is when they check out new releases.

**Comment by xet7** [comment]
ChangeLog button is at Wekan website https://wekan.github.io
