### ISSUE TITLE
Feature: Map custom fields

### ISSUE THREAD

**Issue by tugal** [wekan/wekan#1993]
Hi all,

For my project, i need to display sometimes a location.
I will develop it, and PR.

i need your help to display this information, i see several use cases
1.  display a link "15 rue de provence Paris, France"(_blank) wich open a google maps page
2.  display a link "15 rue de provence Paris, France", wich display a popup with a map
3.  diplay only the value, display a map inside card detail

Which use case should we cover ?

(2)(3) need a map provider, leaflet seems to be a good candidate and free :) And maybe a way to convert an address to geocordinates.

Cheers,
Nelson

**Comment by xet7** [comment]
@tugal 

Do first the one use case that is most important for your project to get your project completed, ask from your end user that will be using your project what they would prefer. You can try leaflet or other free open source map code and provider.

**Comment by xet7** [comment]
Moved to #755 , there is $10 bounty for map/location feature, so you @tugal can have it if you want. Or alternatively, if you don't want it, you can donate it to me to support my maintaining of Wekan.
