### ISSUE TITLE
Feature: Switch Card Template

### ISSUE THREAD

**Issue by tugal** [wekan/wekan#1994]
Hi all,

For simple projects, we don't need all fields presented in card details.
We should have a board params, wich enable users, to switch card detail template.
We could have a default one, a mini view and micro without all complexity.

On technical side, we will only touch on jade template, and adding a board config (Which template to use).
```javascript
template(name="cardDetails")
    +Template.dynamic(template=getTemplate)
```
and adding new jade template..
contract between template (existing and new ones) and BlazeComponent's should not be modified to avoid complexity

What do you think about it ?

Cheers,
Nelson

**Comment by xet7** [comment]
@tugal

You can add new user role to Wekan like "No Comments" role does not show any comments, acivities etc. That issue #1861 has links to GitHub commits how that can be done. Setting that role is available to board admin in web UI by clicking board right sidebar / user avatar / permission. It's also possible to change role with REST API https://github.com/wekan/wekan/wiki/REST-API-Role

Wekan does not yet have for example view only role.

**Comment by xet7** [comment]
Also look at [ChangeLog](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md) about what other role fixes I did to get it working.

**Comment by xet7** [comment]
Moved to #1861
