### ISSUE TITLE
IFTTT Rules Feature Request: If card is moved to list [____], move card to another board [_____] list [____] at top/bottom of list [____]

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1996]
IFTTT Rules Feature Request:

IFTTT Rules Feature Request: If card is moved to list [____], move card to another board [_____] list [____] at top/bottom of list [____]

@Angtrim

If you have sometime time for this, you can look at this. I can also look at this sometime. It's just a wish, no any hurry.

**Comment by JAGL14** [comment]
I am testing wekan and this is very powerfull, but for me it is very necessary to move DONE lists or other list to other board. In Trello it's very simple, but I don't see it here.  Nowadays i have to move each card individually.

This rule would be a solution, but I don't find the action  move card to another board [_____] . I supposed that it's still open.

Thanks

**Comment by xet7** [comment]
@JAGL14 

Do you mean in general, move list to another board?

Or rule about move list to another board? If it's that, how would the whole rule text be, when you change the rule text that is written at this issue name?

**Comment by JAGL14** [comment]
Hi @xet7 . 

Yes, i mean move any list to another board. I don't find any option, only the option when i move only one card; but not drag&drop or options in list or multiple cards. I try with rule ( If card is moved to list [], **move card to another board** [_____] list [] at top/bottom of list [____]) but neither.

Are there any option? 

Thanks

**Comment by xet7** [comment]
@JAGL14 

There is not yet option to move list to another board.

If someone would like to have that feature, it's possible to use [my Commercial Support](https://wekan.team/commercial-support/) to sponsor developing that feature with some amount of money.

Alternatively, someone can code that feature and add pull request.

In general, open issues are not implemented yet. I do close those issues that are done.

**Comment by JAGL14** [comment]
Hi @xet7, and I suppose with rule is not possible yet either? I found rule to move cards but into the same board, not in another board.
Thanks

**Comment by xet7** [comment]
@JAGL14 

Yes, there is not yet rule for moving to another board.
