### ISSUE TITLE
Bug: Calendar Empty. Or: Items in calendar only shown if they have start AND end date?

### ISSUE THREAD

**Issue by KuenzelIT** [wekan/wekan#1998]
* Wekan version:
Wekan 1.70

**Problem description**:
The calendar view only shows items that have a start date AND an end date, as far as I tried it.

I assume that it should show an item if only its start date is configured (or the end date to be automatically configured to the same date). Otherwise there are quite some more clicks to get an item into the calendar view. Or am I missing something?

Thanks!

**Comment by therampagerado** [comment]
For me the calendar view is empty. No cards even that for this week we have 50... :)

Very strange. I'll test this Monday your finding.

**Comment by arradoq** [comment]
Thank you for this issue, i was started to thing this feature is just some defect, I know now

**Comment by rgalonso** [comment]
I'm also seeing this issue in version 1.55.0.  I can confirm that the item does not appear in the calendar when it only has a start date, but does appear once I add the end date.

**Comment by rgalonso** [comment]
I think I found the issue.  Namely, the flexboxes in the "list" CSS class are set to a hard-coded width of 270px.  Setting this instead to "auto" resolves the issue.  I believe the relevant source code is found here:

https://github.com/wekan/wekan/blob/6f0e0748e1eb6cac238edfcfcfcde1e41d613b96/client/components/lists/list.styl#L7

I've created a [pull request](https://github.com/wekan/wekan/pull/2175) that I believe will fix this.  I don't have admin rights on my local installation to test out the required change, but I did create [a Tampermonkey script (on GitHub)](https://github.com/rgalonso/tampermonkey_scripts/blob/master/wekan_auto_flex_lists.user.js) that resolves the issue, both on my local installation running version 1.55.0, and [the live demo version](https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h).

**Comment by xet7** [comment]
@rgalonso 

Ooops, strange effect with that change, columns don't align.

![autoscale-strange](https://user-images.githubusercontent.com/15545/52514084-94925a00-2c17-11e9-897f-e7206a712ef7.png)

**Comment by rgalonso** [comment]
Wow, I apologize.  I meant to reference that "fix" in relation to #1266.  I'll move my comment over to that thread.

**Comment by ojob** [comment]
I encounter the same issue, in fact : the card should be displayed on a period as soon as "target date" is set; using "end date" is not so relevant, since it is known only once the task is completed, i.e. belongs to the past ;-)

**Comment by xet7** [comment]
Moved to #2562
