### ISSUE TITLE
Renaming the Board name does not get reflected in the URL

### ISSUE THREAD

**Issue by shekar73** [wekan/wekan#200]
When the board is renamed, URL slug still points to the old name.

![image](https://cloud.githubusercontent.com/assets/203255/8165461/6d3449bc-1345-11e5-84c3-c96b058f3dbf.png)

**Comment by ePirat** [comment]
We need to make sure we redirect old URL's properly to the new ones.

**Comment by mquandalle** [comment]
The whole routing scheme needs some work, giant random strings aren't easy to share (and aren't necessary). I guess Trello model is more reasonable.

**Comment by mquandalle** [comment]
This meteor package could help: https://atmospherejs.com/todda00/friendly-slugs
But you are right @ePirat, we need to implement (server-side) redirections (which the above package does not).

**Comment by JeremyIglehart** [comment]
Does anyone have an easy hack on how to manually do this once?  I only have one board which has the problem.  If only I could delete the board and try again (from a backup) or something - I also wouldn't mind if I could just delete the whole board and start again with it.

Anyone have a quick patch for one board?

Thanks.

**Comment by simonsmiley** [comment]
I guess the autovalue code in the board model can just be executed after a title update to update the slug. Since the slug isn't actually used for routing (it just has to be a none-empty string) old links will still be valid.  I just stumbled across this since I found out that the slug isn't actually used, but that's another issue I guess

**Comment by xet7** [comment]
Moved from #886 

From @simonsmiley 

## Slug in board url isn't used

The slug in the board url b/:id/:slug isn't actually used anywhere. As far as I can tell it's just saved in the database and never used, so why is it there in the first place. It's mildly confusing that the slug in the url can be changed and you still get to the right board. However removing the slug from the url does result in an error...
