### ISSUE TITLE
Start script issue

### ISSUE THREAD

**Issue by warnerjon12** [wekan/wekan#2001]
## Issue

**Server Setup Information**:

* Wekan version: dev (source)

**Problem description**:

The script `rebuild-wekan.sh` is bugged. It uses `sudo npm` which is ALMOST NEVER a good idea. See https://stackoverflow.com/questions/29468404/gyp-warn-eacces-user-root-does-not-have-permission-to-access-the-dev-dir. Other similar issues may be found on google.

**Comment by warnerjon12** [comment]
I got around this issue by setting the npm prefix to `~/.local`, which is automatically used by `.profile`, but that should not be necessary.

**Comment by xet7** [comment]
Merged. Will be in next release.
