### ISSUE TITLE
docker-compose file provided in wiki seems to be using wrong port.

### ISSUE THREAD

**Issue by Jauler** [wekan/wekan#2006]
It seems like that in wiki page https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-for-testing exposed ports in lines:

```
    ports:
      - 80:80
```

Does not match what is opened and exposed from inside container. See Dockerfile in docker hub: https://hub.docker.com/r/wekanteam/wekan/~/dockerfile/

Should the port be changed to `8080`?

```
    ports:
      - 80:8080
```

**Comment by xet7** [comment]
Thanks! I fixed that outdated page.

If you notice something else outdated on wiki, you can fix it directly by editing wiki pages. Wiki is community maintained.
