### ISSUE TITLE
VBA - Received Date

### ISSUE THREAD

**Issue by arradoq** [wekan/wekan#2007]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 1.69
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Windows
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version: 
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

I am very interested in VBA using REST API, can I create new card with the received date ? If possible, could anyone give a solution on how to do it?

Thank you

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Excel-and-VBA

https://github.com/wekan/wekan/wiki/REST-API-Cards

There look at adding receivedAt value to card API call.

**Comment by xet7** [comment]
You need to login to API first before doing those card API calls:

https://github.com/wekan/wekan/wiki/REST-API
