### ISSUE TITLE
Email texts wrong: TeamMember123 added __member__ to "<Issue-Title>"

### ISSUE THREAD

**Issue by lichtamberg** [wekan/wekan#2008]
## Issue

**Server Setup Information**:

Newest wekan version installed via snap
Ubuntu 16.0.4.

**Problem description**:

Since some days, when I add a new item to a checklist, I get the notification via email, but the placeholder  ``__member__ `` is not replaced as it seems.

f.e. content: 

`Max added __member__ to Testticket`

**Comment by tesfithagos** [comment]
Is there an update for this topic?

**Comment by theonafor** [comment]
I've also notice this issue in the emails I recieved recently.

**Comment by suprovsky** [comment]
I also noticed the same thing both through email and Discord webhook,

**Comment by sfahrenholz** [comment]
think this is the same or related to #1969

**Comment by xet7** [comment]
Moved to #1969
