### ISSUE TITLE
Attachments improvements suggestions

### ISSUE THREAD

**Issue by shekar73** [wekan/wekan#201]
The UI of the attachment feature in the card details page, while functional,  looks kind of out of place, compared to the other elements. I was thinking what we needed is a  thumbnail viewer or maybe increase size of the image box in attachments. 

![image](https://cloud.githubusercontent.com/assets/203255/8166800/0871f150-134f-11e5-9339-501a6a8ed46d.png)

**Comment by nata-goddanti** [comment]
horka:swipebox

swipebox-meteor
Swipebox image viewer plugin for Meteor. 
(Swipebox is a responsive image viewer lightbox, that also works perfectly on mobile devices.) 
This package is using the original swipebox plugin.

**Comment by brooksbecton** [comment]
Hey I would like to take a crack at this!
I've already got some css resizing the images. 

I noticed if you click on a thumbnail you get a preview. Is that good enough for the original issue? Or would ya'll like to see a version of the swipebox?

**Comment by xet7** [comment]
@brooksbecton 

Yes swipebox would be very nice, please go ahead 👍 

I will add this to Roadmap,

**Comment by xet7** [comment]
Ok I updated [Roadmap](https://github.com/wekan/wekan/wiki/Roadmap)

**Comment by brooksbecton** [comment]
Add a PR in here: #1315 

Let me know if I can do anything else!
