### ISSUE TITLE
Redirect to root page

### ISSUE THREAD

**Issue by JochenHammann** [wekan/wekan#2010]
## Issue

we use Wekan 1.74.1 (Node 8.12.0) on Xubuntu 18.04, installed with snap. We have a problem with several board and card URLs.

Steps to reproduce:
- Open a board or card.
- Copy the board's or card's URL.
- Open a new browser tab.
- Paste the copied URL.
- The browser does not open the board or card. The browser opens the root page and shows the list of all boards.
- The same thing happens, if we reload a board or card via F5. The browser opens the root page.

These happens on several boards only. Some boards and cards work well - i.e. their URL opens the card and board, respectively. Unfortunately several boards do not support the direct link.

In the Network panel of the Chrome developer tools we can see, that a HTTP redirect (301) to the Location "/" is triggered, when opening a "broken" URL.

This is the HTTP request and response for a board, which URL does not work:

GET /b/ipRmnW6XgvYYTL3sC/rest-api-rpa HTTP/1.1
Host: xxxxxxxxxxxxxxx:3001
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: http://xxxxxxxxxxxxxxx:3001/
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,la;q=0.6,fr;q=0.5
Cookie: meteor_login_token=xxxxxxxxxxxxxxxxxx

HTTP/1.1 301 Moved Permanently
Location: /
Date: Tue, 20 Nov 2018 07:18:05 GMT
Connection: keep-alive
Transfer-Encoding: chunked

**Comment by xet7** [comment]
Please try newest Wekan.
