### ISSUE TITLE
Bug: Password reset emails not sent

### ISSUE THREAD

**Issue by GavinLilly** [wekan/wekan#2020]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: No
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 1.74
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: RHEL 7.5
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker Swarm
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx in Docker Swarm
* Node Version: 8.12
* MongoDB Version: 3.2.21
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://wekan.internal-url

**Problem description**:
When our users use the password reset function in Wekan, emails are not sent to the SMTP server due to a connection timeout. However other emails through Wekan such as when actions are performed on a watched board are sent like normal. The error in the log is:

```
Exception while invoking method 'forgotPassword' Error: Connection timeout
wekan_wekan-app.5.ik32ixdrubnf@internal.host.name    |     at SMTPConnection._formatError (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
wekan_wekan-app.5.ik32ixdrubnf@internal.host.name    |     at SMTPConnection._onError (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:531:20)
wekan_wekan-app.5.ik32ixdrubnf@internal.host.name    |     at Timeout._connectionTimeout.setTimeout (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:249:18)
wekan_wekan-app.5.ik32ixdrubnf@internal.host.name    |     at ontimeout (timers.js:498:11)
wekan_wekan-app.5.ik32ixdrubnf@internal.host.name    |     at tryOnTimeout (timers.js:323:5)
wekan_wekan-app.5.ik32ixdrubnf@internal.host.name    |     at Timer.listOnTimeout (timers.js:290:5)
```

The configuration in the docker-compose.yaml file is:
```
      - MAIL_URL=smtp://smtp.company-url:25
      - MAIL_FROM=noreply@company-name.com
```

In the Wekan admin panel:
![image](https://user-images.githubusercontent.com/29777802/48941486-9baca480-ef13-11e8-9a03-a66feb0661dd.png)

The settings match but for some reason password resets fail. Can you tell me when the docker variables are used and when the admin panel variables are used for sending mail and if there is some different function for sending mail for password resets?

Out current workaround is to manually pull the password reset token out of the database but this isn't very sustainable for thousands of users.

**Comment by xet7** [comment]
Because your other emails work, problem is not in your email settings.

There could be some bug in password reset code.

**Comment by GavinLilly** [comment]
After living with the issue for a few weeks I think it's actually not caused by Wekan or Meteor as some reset emails did get sent. To me it actually looks like a knock-on effect of our Node processes reaching high CPU usage, essentially meaning that the SMTP send process times out as the Node process is busy working on other tasks.

This would explain why some board notification emails have been sending correctly because those emails were sent during out-of-office hours (less usage and load on the servers).

So like many of the other issues we've had with Wekan in the past I think this comes down to our (somewhat) unique situation of having a lot of users/boards and in-turn high load. As a reminder we're running 6x instances of Wekan across 3x t3.large AWS instances.

**Comment by xet7** [comment]
@GavinLilly 

Do you still use Wekan v1.74 ?

**Comment by GavinLilly** [comment]
No we're on v2.16 now. We've moved to docker now so updating has become much easier and we're doing so normally every few weeks

**Comment by xet7** [comment]
@GavinLilly 

What SMTP server you use? Does it have any rate limits?

Wekan will use https://atmospherejs.com/msavin/sjobs package for scheduled jobs, so I'm thinking if more of Wekan functionality would be moved to scheduled jobs and not so much run in main process.

For example, if one scheduled job would check for forgot password queue and then send emails.

Would that work?

**Comment by GavinLilly** [comment]
Honestly I have no idea what SMTP we're using or if it has limits. I can try and find out. All I know is we have an Exchange environment.

Hmmm yea a job scheduler would be quite nice I think. It would certainly take some of the CPU load off when you need it

**Comment by xet7** [comment]
@GavinLilly 

Are you using DavMail ?
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by GavinLilly** [comment]
No it's a SMTP server/relay provided on our corporate network. Unfortunately I don't know the architecture.
Just to be clear, emails are working from Wekan, but only during low-usage times (evenings, weekends etc.)

**Comment by xet7** [comment]
@GavinLilly 

Newest Wekan has 10x lower resource usage, so it's much faster. Does it fix this issue? Please test.

https://github.com/wekan/wekan/commit/3c49e2d0edec19eff4f87b0fcc127f924af193fc#commitcomment-32537953

**Comment by marc1006** [comment]
@xet7 @GavinLilly 
Can this issue be closed?

**Comment by xet7** [comment]
This issue was with Wekan v1.74, and newest is Wekan v4.15. It would be nice if @GavinLilly can test does this bug still happen.

**Comment by GavinLilly** [comment]
Hello. We've been frozen on an old version for a very long time and I've not really been involved in our Wekan instance for that long too.

I will speak with our team about upgrading to a newer version but it might take some time. I'd be ok with closing this issue though as we don't seem to get any complaints from our users about emails.

**Comment by xet7** [comment]
Thanks @GavinLilly !
