### ISSUE TITLE
email confirmation mail?

### ISSUE THREAD

**Issue by almereyda** [wekan/wekan#203]
i have just registered to a custom libreboard deployment, entered my wished credentials, but didn't have to confirm my email address.
this can be a source for spam or fraud.

**Comment by nata-goddanti** [comment]
:+1:  I agree. I think sending the confirmation email  along with forgotten password email setup would remove that source of  spam or fraud.

**Comment by ePirat** [comment]
:+1: indeed I have similar problems which would be solved by that. Maybe even an optional captcha.

**Comment by HLFH** [comment]
@mquandalle It seems I got a verification email when I created my Wekan account but it would be great to be able to resend the verification email if on login, `verified` for the user is false on MongoDB.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
