### ISSUE TITLE
Migrate from 0.50 to 1.70

### ISSUE THREAD

**Issue by MrArko** [wekan/wekan#2033]
Hello all, 

OS : Linux Debian 8 x64 

Migrate from 0.50 to 1.70 problem : 

When i export board on the 0.50 , i can't see card when i import on the 1.70 but the board are here but empty.

Did you already see this ?

Thanks in advance !!

**Comment by xet7** [comment]
Import/Export of Wekan JSON is not fixed yet.

Meanwhile, try [backup/restore MongoDB database to newest Wekan version](https://github.com/wekan/wekan/wiki/Backup) to see does database migrations work correctly for your upgrade.

If database migration does not work, please reopen this issue with details about what did not work.
