### ISSUE TITLE
checklist complate rule not working

### ISSUE THREAD

**Issue by BurakTuran9** [wekan/wekan#2038]
Hello,
Thank you for wekan. Checklist complate  rule not working. Can you help me? 
![wekan rule error](https://user-images.githubusercontent.com/39942433/49218900-bcc53780-f3e2-11e8-9f98-c137a4273738.PNG)

* Wekan version:1.78.0
* If this is about old version of Wekan, what upgrade problem you have?:No
* Operating System:ubuntu 16.04
* Deployment Method: snap and source
* Node Version:8.12

**Comment by TiibCD** [comment]
Issue already discussed here [#1972](https://github.com/wekan/wekan/issues/1972)

**Comment by xet7** [comment]
Moved to #1972
