### ISSUE TITLE
Feature Request: Badges

### ISSUE THREAD

**Issue by lonix1** [wekan/wekan#2039]
It would be very useful for mini cards to show "badges" like you find in other kanban/scrum boards.

There are some things that cannot be properly represented by labels - they just add noise. In those cases we need badges, which are basically icons (we could use an icon font like fontawesome).

So the popup card should have fields for specifying a badge's data, and the mini card would show the actual badge.

For example:
- Related to #2018 - a badge for story points
- Related to #2036 - a badge for the card's type, e.g. feature, bug, tech debt, spike
- A hyperlink to corresponding issue in a bug tracker, or story in a planning tool
- Status: default (shows nothing), blocked
- Due date
- Urgency: default (shows nothing), urgent
- Risk: might miss target, possibly needs re-estimation, too slow, etc.
- Age: slow stories (compared to team velocity or lead time or whatever) are highlighted (need to set velocity or lead time per board)

If anyone has more badge ideas, please add them below so we can discuss.

**Comment by xet7** [comment]
@lonix1

Please add screenshot mockup.

**Comment by lonix1** [comment]
![](https://confluence.atlassian.com/jirasoftwarecloud/files/945539323/945539324/1/1518492124958/Issue+card+annotated.png)

An example from JIRA - doesn't need to be like this, it's just for an idea. The "badges" can be on the top right, bottom left, bottom right corners.

**Comment by lonix1** [comment]
@xet7 

![](https://confluence.atlassian.com/jirasoftwarecloud/files/945539323/945539324/1/1518492124958/Issue+card+annotated.png)

An example from JIRA - doesn't need to be like this, it's just for an idea. The "badges" can be on the top right, bottom left, bottom right corners.

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4940 . Thanks to @helioguardabaxo !
