### ISSUE TITLE
Unpatched CVEs in v1.75

### ISSUE THREAD

**Issue by danpatdav** [wekan/wekan#2046]
The latest stable build available on dockerhub (v1.75) has a number of unpatched vulnerabilities.

[wekan-175-scan-results.txt](https://github.com/wekan/wekan/files/2649947/wekan-175-scan-results.txt)

**Comment by xet7** [comment]
Does someone know how to get dockerhub build new tags automatically?

quay.io/wekan/wekan has newest Wekan.

**Comment by danpatdav** [comment]
I'll test v1.82 from quay.  Thanks.

**Comment by xet7** [comment]
I did try to setup automatic build to dockerhub, and also did add newest v1.82 tag to dockerhub so that it started building a moment ago. I'll see later did dockerhub builds work.

**Comment by xet7** [comment]
@danpatdav 

What can be updated in Dockerfile?
https://github.com/wekan/wekan/blob/devel/Dockerfile
