### ISSUE TITLE
Unpatched CVEs in v1.82

### ISSUE THREAD

**Issue by danpatdav** [wekan/wekan#2047]
There are a number of "high" vulnerabilities in the latest release.
[wekan182-scan-results.txt](https://github.com/wekan/wekan/files/2650505/wekan182-scan-results.txt)

**Comment by xet7** [comment]
There is newer meteor framework v1.8.x version here:
```
image: quay.io/wekan/wekan:meteor-1.8
```
Is there any difference in amount of vulnerabilities?

**Comment by danpatdav** [comment]
meteor-1.8 resolves 7 of 23 highs.  Good progress.
[wekan-meteor18-scan-results.txt](https://github.com/wekan/wekan/files/2653827/wekan-meteor18-scan-results.txt)

**Comment by xet7** [comment]
@danpatdav 

Meteor 1.8 version works in Docker and Source, but not yet at Snap and Sandstorm. I'll try sometime to get remaining ones working.

Yes you can submit this way:
- click fork
- fork to your own github account
- ssh clone your repo
- git checkout edge
- make your changes
- add, commit, push
- at GitHub web interface click submit pull request.

**Comment by danpatdav** [comment]
OK, so I may not be able to help with this.  I scanned the underlying buster-slim image and it is clean (other than an open CVE for which there is not yet a patch).  The packages that need to be updated are not being installed directly in the Dockerfile that I can tell.  I am guessing that meteor or another high level component is adding them.  Not sure what action can be taken in the wekan project other then adopting more up to date components as quickly as possible--which you already seem to be doing.

I'll let you decide if you want to keep this issue open or close it.

**Comment by xet7** [comment]
@danpatdav 

How did you check CVEs from docker image?

**Comment by danpatdav** [comment]
Not a substantial change on the edge build.

**Comment by xet7** [comment]
@danpatdav 

I finally got Meteor v1.8.0.1 version working. Can you test this tag is there difference in vulnerabilities? Thanks!
```
image: quay.io/wekan/wekan:meteor-1.8
```

**Comment by danpatdav** [comment]
[wekan-meteor181-scan-results.txt](https://github.com/wekan/wekan/files/2738681/wekan-meteor181-scan-results.txt)
No real change.

**Comment by xet7** [comment]
@danpatdav 

Can you test again these with your security scanner? base was changed to Ubuntu Cosmic, and there are not any CVEs listed at quay security scan.

1) `image: quay.io/wekan/wekan`

2) `image: quay.io/wekan/wekan:meteor-1.8`

![quay](https://user-images.githubusercontent.com/15545/54152838-d3017b80-4446-11e9-8681-e97e2f8f7a6c.png)

**Comment by danpatdav** [comment]
@xet7 better, but still a number of open issues.  I don't think this is related to cosmic, so much as meteor or some of the other packages Wekan is built on.
[scan-results-meteor-18-cosmic.txt](https://github.com/wekan/wekan/files/2957250/scan-results-meteor-18-cosmic.txt)

**Comment by xet7** [comment]
@danpatdav 

Can you test newest Wekan container? There has been many Meteor, Node.js etc updates.
```
image: quay.io/wekan/wekan
```

**Comment by xet7** [comment]
@danpatdav

Can you test newest Wekan container? There has been many Meteor, Node.js etc updates.

**Comment by danpatdav** [comment]
@xet7 I'm sorry, but I have move on to a different role and don't have the ability to do this anymore.

**Comment by xet7** [comment]
@danpatdav 

Ok thanks!
