### ISSUE TITLE
Using Meteor with docker-compose

### ISSUE THREAD

**Issue by InDaPond** [wekan/wekan#2048]
Following the  [installation guide](https://github.com/wekan/wekan-mongodb) all I have on my server system is a new user called wekan and the docker-compose.yml in which the wekan repo is referenced. 
Is there a way to use the faster meteor build, as it is suggested during the startup of my working wekan container?

**Comment by xet7** [comment]
Newer meteor version is at meteor-1.8 branch:
https://github.com/wekan/wekan/blob/meteor-1.8/docker-compose.yml

There change:
```
image: quay.io/wekan/wekan:meteor-1.8
```
It's also possible to use newer [MongoDB 4.x](https://hub.docker.com/_/mongo/) with newer meteor:
```
image: mongo:xenial
```

**Comment by xet7** [comment]
I added these infos above to installation guide you mentioned above.

**Comment by InDaPond** [comment]
If I am just adding the meteor-1.8 addition toward the image within the docker-compose.yml,
it does not work. 
I get

> wekan-app  | /build/programs/server/node_modules/fibers/future.js:280
wekan-app  | 						throw(ex);
wekan-app  | 						^
wekan-app  | 
wekan-app  | TypeError: Cannot read property 'constructor' of undefined
wekan-app  |     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
wekan-app  |     at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
wekan-app  |     at packages/meteorhacks_meteorx.js:175:1
wekan-app  |     at packages/meteorhacks_meteorx.js:200:4
wekan-app  |     at packages/meteorhacks_meteorx.js:208:3
wekan-app  |     at /build/programs/server/boot.js:411:36
wekan-app  |     at Array.forEach (<anonymous>)
wekan-app  |     at /build/programs/server/boot.js:220:19
wekan-app  |     at /build/programs/server/boot.js:471:5
wekan-app  |     at Function.run (/build/programs/server/profile.js:510:12)
wekan-app  |     at /build/programs/server/boot.js:470:11

Removing the line makes it work again, but not on the meteor-build, ofc.

**Comment by Teutone** [comment]
I came across this error too in our own building infrastructure. 

I was able to build our custom wekan:meteor-1.8.0.2 docker image of the [meteor-1.8 branch](https://github.com/wekan/wekan/tree/meteor-1.8) by changing: 

`.meteor/release` to `METEOR@1.8.0.2`

Then following [this workaround](https://github.com/meteorhacks/meteorx/issues/8).
Notice that you have to remove packages/ from the .gitignore if you want to use a forked repo.

**Comment by xet7** [comment]
@Teutone 

Meteor-1.8 version is not fixed or tested yet fully.
