### ISSUE TITLE
Use GitLab as a login service provider in .net core application.

### ISSUE THREAD

**Issue by Axay001** [wekan/wekan#2054]
Gitlab is providing solution to use it for login. 
https://docs.gitlab.com/ee/integration/oauth_provider.html

Is there any solution with .net core where I can get reference to use GitLab as a login provider with .net core identity?

**Comment by xet7** [comment]
Huh, what app uses .net core? I would presume you just Google search for .net core oauth, or whatever framework you are using for .net core login.

GitLab is made with Ruby.

Wekan is made with Javascript / Node.js

Wekan GitLab OAuth2 issue is at #109
