### ISSUE TITLE
Feature Request: My Cards: List of all boards/lists/cards for every card where person is assigned to card

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2055]
My Cards: List of all boards/lists/cards for every card where person is assigned to card.

Similar to Linked Cards, but My Cards view is created automatically.

**Comment by superlou** [comment]
I was looking at implementing this through the API, but is [this documentation](https://github.com/wekan/wekan/wiki/REST-API) still up to date? It doesn't look like there is a way to get cards, only add, update, and delete.

**Comment by reinos** [comment]
Hi there, what is the status of this feature.

**Comment by xet7** [comment]
@reinos 

This is not started yet.

Moved to #641

**Comment by superlou** [comment]
I'm not sure that #641 addresses this for my use case. That seems to be about creating a board at a higher level. To me, this feature would be more used to find the cards applicable to a person, then navigate to the board they are part of to work with that card. I think #2074 would be a more effective means to satisfy that use case.

**Comment by xet7** [comment]
@superlou 

Yes, both #641 and #2074 are needed, for different use cases.
