### ISSUE TITLE
New card scrollbars aren't working if client doesn't have internet connection

### ISSUE THREAD

**Issue by rinnaz** [wekan/wekan#2056]
## Issue

Add these issues to elsewhere:
- LDAP: https://github.com/wekan/wekan-ldap/issues
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: **yes**
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? **yes**
* Wekan version: **v1.87.0**
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: **Ubuntu 18.04**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **snap**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: **v8.14.0**
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:

Steps:

- Disable internet connection on client side
- Open card with many comments 
- See old scrollbar being replaced by new one

Nothing happens when trying to scroll card contents using mouse wheel.

*P.S. With internet connection enabled new scrollbar works... but is very slow*

![scrollbar0](https://user-images.githubusercontent.com/36293513/50018290-d9b35a80-ffdf-11e8-9ca0-e407552b8227.gif)

- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

**Comment by xet7** [comment]
Is Wekan server running on LAN that is not connected to Internet? It should work if there is still connection to Wekan server.

Wekan does no have any offline data caching, so disconnecting from network where Wekan server is does of course stop Wekan working.

**Comment by rinnaz** [comment]
Yep, server and clients are on LAN. Clients without internet access do have this issue, while clients with internet access — don't. 

First I didn't realize that it's about internet connection, but then reproduced it on localhost and found that toggling internet connection modifies scrollbar behavior.

**Comment by xet7** [comment]
Hmm, that's strange. I'll check does that scrollbar package load anything from Internet, it should not do that.

**Comment by xet7** [comment]
I started reading scrollbar code, and yes, it's loading from cdn:
https://github.com/MaazAli/Meteor-Malihu-Custom-Scrollbar/blob/master/jquery.mCustomScrollbar.js#L50

I will fork that package and include it locally to fix this.

Thanks a lot for finding this! By default Wekan does not load anything from Internet, and it should work this way always.
