### ISSUE TITLE
Exception from Tracker afterFlush function: ReferenceError: Ps is not defined

### ISSUE THREAD

**Issue by uusijani** [wekan/wekan#2057]
**Server Setup Information**:

* Did you test in newest Wekan?: yes (current edge is 1.88, the same as stable)
* For new Wekan install, did you configure root-url correctly? yes
* Wekan version: 1.88
* Operating System:
* Deployment Method: snap
* Http frontend: -
* ROOT_URL environment variable: http://localhost

**Problem description**:
Since (at least) a few days back, my web console (in both Firefox and Chrome) is logging this error whenever I open a card. The same error is also logged for opening a board. Additionally, in the more compact view (when the browser window is small, as in the gif I'm attaching), expanding a list causes the same error, as does closing a card.

This doesn't seem to affect any functionality AFAICT (although I did notice this while investigating why vertical scrolling within a card is suddenly very slow, but that is probably unrelated and possibly local).

The attached animation is from a fresh install with just the user account and one test card created.

***Steps to reproduce***:
1. Open web console
2. Open a card

***What happens***:
"Exception from Tracker afterFlush function", "ReferenceError: Ps is not defined". [Web console log attached](https://github.com/wekan/wekan/files/2682675/wekan-output.txt).

***If using Snap, output from  `sudo snap logs wekan.wekan`***
(Nothing during the error event)

***Peek animation***:
![peek 2018-12-15 15-48](https://user-images.githubusercontent.com/4244772/50043892-b55d8980-0084-11e9-8458-c27e212cc4df.gif)

**Comment by xet7** [comment]
It seems to be only in Firefox:
https://stackoverflow.com/questions/35300380/event-not-defined-error-only-in-firefox

I presume bug is somewhere in new scrollbar code:
https://github.com/wekan/wekan-scrollbar

**Comment by xet7** [comment]
Ok seems that complaining stopped after adding perfectscrollbar package back. I will make new release with this fix included.
