### ISSUE TITLE
Feature Request: On board, invite new user directly with email address, without using Admin Panel or registering at /sign-up

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2060]
Feature Request: On board, invite new user directly with email address, without using Admin Panel or registering at /sign-up

Add it as option to Admin Panel. That option should be disabled by default.

**Comment by saschafoerster** [comment]
@xet7 Is it possible, this only works, when self-registration is enabled? I would like to make it possible to let admins of a board let people invite them directly to the board itself via this feature, but after the update I didn't see any new option in the admin-board, nor could I invite guests via email. My board has self-sign-up turned off.
