### ISSUE TITLE
Feature Request: Hide/Filter List

### ISSUE THREAD

**Issue by HolgerGH** [wekan/wekan#2063]
Hi, we are using wekan for our weekly jour fixes. We have quite a long _Backlog list_ . Thankfully it gets a scrollbar so it doesnt grow in hight forever. But it would be nice to hide the list or cards on that list. See attached images.

### New Filter or Hide List

![filter](https://user-images.githubusercontent.com/15545/50169254-e55f9380-02f5-11e9-9e51-8731f929d108.png)

### Normal

![normal](https://user-images.githubusercontent.com/15545/50169277-f01a2880-02f5-11e9-866f-97b87f30ec70.png)

### Hidden

![hidden](https://user-images.githubusercontent.com/15545/50169299-fc05ea80-02f5-11e9-95ef-5b48de0676c6.png)

**Comment by xet7** [comment]
@HolgerGH 

I modified your feature request above to include images directly. Next time, please add images to GitHub issue directly, because 3rd party image hosting services are not reliable enough.

**Comment by rgalonso** [comment]
On a related note, hide/filter would be a nice feature at the individual card level too.  I tried adding a "Hide" custom field, but then found there was no practical way to apply a filter based on a custom field's value.  Using version 2.31.

**Comment by mattdm** [comment]
I think this is the same as #1167, yeah?

**Comment by xet7** [comment]
Moved to #1167
