### ISSUE TITLE
Windows from source install (was: Sudden Crash when starting)

### ISSUE THREAD

**Issue by arradoq** [wekan/wekan#2066]
## Issue

Add these issues to elsewhere:
- LDAP: https://github.com/wekan/wekan-ldap/issues
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

` C:\Users\<user>\wekan-devel\.meteor\local\build\programs\server\boot.js:467`
`W20181220-06:03:35.145(7)? (STDERR) }).run();`

`W20181220-06:03:35.147(7)? (STDERR)    ^`

`W20181220-06:03:35.148(7)? (STDERR)`

`W20181220-06:03:35.150(7)? (STDERR) Error: EPERM: operation not permitted, stat`
'C:\Users\`<user>\wekan-devel\.meteor\local\build\programs\server\node_modules'`

`W20181220-06:03:35.151(7)? (STDERR)     at Object.realpathSync (fs.js:1670:17)`

`W20181220-06:03:35.152(7)? (STDERR)     at toRealPath (module.js:156:13)`

`W20181220-06:03:35.157(7)? (STDERR)     at tryFile (module.js:152:22)`

`W20181220-06:03:35.158(7)? (STDERR)     at tryExtensions (module.js:164:22)`

`W20181220-06:03:35.159(7)? (STDERR)     at Function.Module._findPath (module.js:217:20)`

`W20181220-06:03:35.161(7)? (STDERR)     at Function.Module._resolveFilename (module.js:534:25)`

`W20181220-06:03:35.162(7)? (STDERR)     at Function.Module._load (module.js:466:25)`

`W20181220-06:03:35.166(7)? (STDERR)     at Module.require (module.js:579:17)`

`W20181220-06:03:35.168(7)? (STDERR)     at require (internal/module.js:11:18)`

`W20181220-06:03:35.170(7)? (STDERR)     at Object.require (C:\Users\<user>\wekan-devel\.meteor\local\build\programs\server\boot.js:283:20)`

at first, fibers cannot be found, then underscore, and then this.

**Comment by xet7** [comment]
Did you try to build Wekan from source on Windows directly? I do not know does that work. You need correctly installed fibers etc.

Or is this with Docker? Docker updates do not work, updating switches to Windows Docker containers. You need to backup (info at Wekan GitHub wiki, although I don't know what file paths Docker on Windows uses), remove Docker and containers, reinstall Docker and make sure you use Linux containers. Then use docker-compose to run Wekan again.

**Comment by arradoq** [comment]
I try to source on Windows, i've done it before, but somehow it needs to be redone, i want to know which dependency are not compatible. I use node 4.8.1 npm 2.5.1 with meteor 1.6.0.1

**Comment by nerminator** [comment]
Is there any update on this? I also have the same problem. 
at first, fibers cannot be found, then underscore, and then this wierd operation not permitted error.

**Comment by xet7** [comment]
@nerminator

Wekan has lowest RAM/CPU consumption on Windows when installing to Win10:
1) [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
2) Ubuntu for Windows from Windows Store
3) Using rebuild-wekan.sh 1 and 2, start-wekan.sh from https://github.com/wekan/wekan and MongoDB 3.2.21 from MongoDB website.

That way fibers etc works.

**Comment by nerminator** [comment]
The solution is actually running on Ubuntu rather than running on Windows.  I'll try with Oracle VirtualBox.
Thanks.

**Comment by arradoq** [comment]
if you are just interested in wekan only rather than overall ubuntu things, option 2 is more RAM friendly

**Comment by xet7** [comment]
I'm unable to fix fibers on Windows, I'm not fibers or Windows developer.

When I some years ago tried to make Windows Service, Windows file permissions did lock me out of using files.

Once I tried to install Nim programming language to Windows, and then Windows Defender deleted it.

So I failed as Windows developer, and I'm unable to make Wekan working on Windows Source install. I can not fix this. This would require some Windows developer to get it working.

**Comment by beppe9000** [comment]
I got Wekan running natively in windows server 2016 with node 10.12.0 x64. I had no problem with fibers so I think some update fixed that.

**Comment by xet7** [comment]
@beppe9000 

Please write all details how you did it, step by step.

**Comment by beppe9000** [comment]
I basically followed this: https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows#source-install-required-dependencies

I actually started with creating a test package where i installed fibers:
```
[1662]npm install npm install --global --production windows-build-tools
[1663]npm install --global --production windows-build-tools
[1665]npm install --global node-gyp
[1668]npm install fibers
```
It compiled.


 Might be of note: I use this machine for development so I already had visual studio, python and many other utilities like compilers and the rest.

**Comment by arradoq** [comment]
On my case I installed it on Windows 10 pro, after auto update, suddenly cannot use fiber again. So, i think maybe different version from OS matters here. 


Somebody please kindly update this issue if the matter on win 10 is resolved

**Comment by xet7** [comment]
`choco install meteor` etc should work now OK.
