### ISSUE TITLE
A user removed list and it's not visible in the archive. All the cards in it are gone too.

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#2068]
A user removed list and it's not visible in the archive. All the cards in it are gone too.

Why can't I view it in my archive and why all cards get deleted too (not going to the archive or moving them back to their last place)?

**Comment by xet7** [comment]
@therampagerado 

If user moves list to archive, list goes to archive.

If user really goes to submenu to delete list, it is really deleted and cards too, it does not go to arhive. That's the point is not directly in the same menu as move to arhive. In that case, you get the data from your backups.
