### ISSUE TITLE
Rule: Action: send mail does not work

### ISSUE THREAD

**Issue by RedDog99** [wekan/wekan#2077]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?:
yes

* Wekan version:
1.97

* Operating System:
Debian 9

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
snap

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
nginx

* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
If a rule with an action to send a mail is configured no mail is send.
Reset-Password links are send correctly

The connection to the mail server is done, but wekan doesn't send any mail data.

- *Explain steps how to reproduce*

Create a new board.
Add a rule:
-> on new card is added
-> send an email
-> add mail adress and so on
Create a new card

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
nothing related

**Comment by TiibCD** [comment]
Issue listing all the bugs regarding rules is already in progress here [#1972](https://github.com/wekan/wekan/issues/1972)
