### ISSUE TITLE
Sudden server issues after nightly update to 1.97

### ISSUE THREAD

**Issue by Azbests** [wekan/wekan#2078]
## Issue

**Server Setup Information**:

Running 1.97 on snap, also tried reverting to 1.96/1.95. Service was running for a long time now without any issues.

**Problem description**:

Server suddenly sopped today and started rebooting. Could this be corrupted mongodb or it points to something else?

> Dec 28 13:10:51 wekan wekan.wekan[24092]: Note: you are using a pure-JavaScript implementation of bcrypt.
> Dec 28 13:10:51 wekan wekan.wekan[24092]: While this implementation will work correctly, it is known to be
> Dec 28 13:10:51 wekan wekan.wekan[24092]: approximately three times slower than the native implementation.
> Dec 28 13:10:51 wekan wekan.wekan[24092]: In order to use the native implementation instead, run
> Dec 28 13:10:51 wekan wekan.wekan[24092]:   meteor npm install --save bcrypt
> Dec 28 13:10:51 wekan wekan.wekan[24092]: in the root directory of your application.
> Dec 28 13:10:51 wekan wekan.wekan[24092]: /snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:98
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     process.nextTick(function() { throw err; });
> Dec 28 13:10:51 wekan wekan.wekan[24092]:                                   ^
> Dec 28 13:10:51 wekan wekan.wekan[24092]: MongoError: file with id 5c2604bbc326b45ffacbf474 not opened for writing
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at Function.MongoError.create (/snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at /snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at handleCallback (/snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at /snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at handleCallback (/snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at /snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at handleCallback (/snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at setCursorNotified (/snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at /snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at queryCallback (/snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at /snap/wekan/368/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
> Dec 28 13:10:51 wekan wekan.wekan[24092]:     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
> Dec 28 13:10:51 wekan systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
> Dec 28 13:10:51 wekan systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
> Dec 28 13:10:51 wekan systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling restart.
> Dec 28 13:10:51 wekan systemd[1]: snap.wekan.wekan.service: Scheduled restart job, restart counter is at 23.

**Comment by xet7** [comment]
@Azbests  

1) Do you have ROOT_URL etc settings setup correctly?
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys
```
sudo snap get wekan
```
2) Do you have backups?
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore

**Comment by xet7** [comment]
I do have a lot of boards in my own Wekan install and it did upgrade to Wekan v1.97 just fine.

**Comment by xet7** [comment]
@Azbests 

Snap version updates automatically. That's the whole point of using snap.

Those that want to upgrade manually can use Docker.

In v1.97 I did upgrade to node 8.15.0 and MongoDB 3.2.22:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v197-2018-12-26-wekan-release

I don't know is trying to repair MongoDB useful in any way, and does it work. I tried it at #2070 where if MongoDB does not start, I did not get even raw database repair tools compiled correctly yet.

Currently Wekan is made with www.meteor.com Javascript web framework, that supports MongoDB. Wekan does not support using other databases as main database.

Unrelated to this, sometime I also tried to repair corrupted MySQL databases, and that was also not possible. There is also https://wiki.postgresql.org/wiki/Corruption page about corruption in PostgreSQL.

AFAIK currently SQLite is most resistant to database corruption https://www.sqlite.org/howtocorrupt.html

I'm thinking what to do about these corruption issues. Suggestions welcome.

**Comment by xet7** [comment]
One option would be to try to change from MongoDB to FoundationDB:
https://www.foundationdb.org/blog/announcing-document-layer/

**Comment by xet7** [comment]
I found article about recovering MongoDB data, I'll try that:
http://www.alexbevi.com/blog/2016/02/10/recovering-a-wiredtiger-collection-from-a-corrupt-mongodb-installation/

**Comment by xet7** [comment]
It is possible to repair MongoDB database this way:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

If you have problems repairing, please open issue again and add comment.
