### ISSUE TITLE
Bug: Outgoing webhook for adding/removing members from card shows "__member__" and not the member name

### ISSUE THREAD

**Issue by mpathiuk** [wekan/wekan#2085]
## Issue
When I connect wekan to rocketchat with webhooks, adding a user to the board show correctly: Mikhail added Johnny to "test board".

But when I add or remove members from a card I cannot get the username.

I've checked the logs for what is received by rocketchat and it does indeed receive "\_\_member\_\_" rather than the member name. All my members have full name and username filled in. 

Rocketchat received JSON Log sample:

 content:     { text: 'Mikhail added \_\_member\_\_ to "testing" ....-removed prod details-  description: 'act-joinMember' }

** how to reproduce**
Set up the outgoing webhook to anywhere, add a new user to the baord to see that the webhook correctly displays their name
Try adding that member to a new card and checking received webhook logs.

**Comment by sfahrenholz** [comment]
already known #1969

**Comment by xet7** [comment]
Moved to #1969
