### ISSUE TITLE
Bug: Outgoing webhook for changing label does not show label name

### ISSUE THREAD

**Issue by mpathiuk** [wekan/wekan#2086]
## Issue

When I change a label an outgoing webhook is triggered. On the incoming webhook logs of the content text I receive { text: 'Mikhail act-addedLabel ... - then standard details- ...  description: 'act-addedLabel' } 

The label name is not sent

**How to reproduce**:

Setup outgoing webhooks, add a label to your card. See the logs of the incoming webhook.

**Comment by sfahrenholz** [comment]
already known #1969

**Comment by xet7** [comment]
Moved to #1969
