### ISSUE TITLE
Cannot build and run: "Error: Cannot find module 'fibers'"

### ISSUE THREAD

**Issue by FranciscoBarros** [wekan/wekan#209]
I've cloned GitHub repo, changed to the cloned directory, and entered # meteor.
Got the stack trace :

user@host:~/sistemas/outros$ git clone https://github.com/libreboard/libreboard.git
Cloning into 'libreboard'...
remote: Counting objects: 996, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 996 (delta 6), reused 0 (delta 0), pack-reused 959
Receiving objects: 100% (996/996), 312.66 KiB | 105.00 KiB/s, done.
Resolving deltas: 100% (590/590), done.
Checking connectivity... done.
user@host:~/sistemas/outros$ cd libreboard/
user@host:~/sistemas/outros/libreboard$ ls
bower.json   Contributing.md  LICENSE    sandstorm.js
client       Dockerfile       public     sandstorm-pkgdef.capnp
collections  i18n             README.md  server
user@host:~/sistemas/outros/libreboard$ meteor
[[[[[ ~/sistemas/outros/libreboard ]]]]]      

=> Started proxy.                             
=> Started MongoDB.                           
Bower:  autosize v3.0.6 successfully installed
Bower:  perfect-scrollbar v0.6.2 successfully installed
W20150623-11:34:28.174(-3)? (STDERR)          
W20150623-11:34:28.175(-3)? (STDERR) module.js:340
W20150623-11:34:28.175(-3)? (STDERR)     throw err;
W20150623-11:34:28.176(-3)? (STDERR)           ^
W20150623-11:34:28.176(-3)? (STDERR) Error: Cannot find module 'fibers'
W20150623-11:34:28.176(-3)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150623-11:34:28.176(-3)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150623-11:34:28.176(-3)? (STDERR)     at Module.require (module.js:364:17)
W20150623-11:34:28.177(-3)? (STDERR)     at require (module.js:380:17)
W20150623-11:34:28.177(-3)? (STDERR)     at Object.<anonymous> (/home/fbarros/sistemas/outros/libreboard/.meteor/local/build/programs/server/boot.js:1:75)
W20150623-11:34:28.177(-3)? (STDERR)     at Module._compile (module.js:456:26)
W20150623-11:34:28.177(-3)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20150623-11:34:28.177(-3)? (STDERR)     at Module.load (module.js:356:32)
W20150623-11:34:28.177(-3)? (STDERR)     at Function.Module._load (module.js:312:12)
W20150623-11:34:28.178(-3)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 8                        
W20150623-11:34:38.927(-3)? (STDERR)          
W20150623-11:34:38.927(-3)? (STDERR) module.js:340
W20150623-11:34:38.928(-3)? (STDERR)     throw err;
W20150623-11:34:38.928(-3)? (STDERR)           ^
W20150623-11:34:38.930(-3)? (STDERR) Error: Cannot find module 'fibers'
W20150623-11:34:38.930(-3)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150623-11:34:38.930(-3)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150623-11:34:38.930(-3)? (STDERR)     at require (module.js:380:17)
W20150623-11:34:38.931(-3)? (STDERR)     at Module._compile (module.js:456:26)
W20150623-11:34:38.931(-3)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20150623-11:34:38.931(-3)? (STDERR)     at Module.load (module.js:356:32)
W20150623-11:34:38.931(-3)? (STDERR)     at Object.<anonymous> (/home/fbarros/sistemas/outros/libreboard/.meteor/local/build/programs/server/boot.js:1:75)
W20150623-11:34:38.932(-3)? (STDERR)     at Function.Module._load (module.js:312:12)
W20150623-11:34:38.932(-3)? (STDERR)     at Module.require (module.js:364:17)
W20150623-11:34:38.930(-3)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 8                        
W20150623-11:34:49.822(-3)? (STDERR)          
W20150623-11:34:49.822(-3)? (STDERR) module.js:340
W20150623-11:34:49.823(-3)? (STDERR)     throw err;
W20150623-11:34:49.823(-3)? (STDERR)           ^
W20150623-11:34:49.825(-3)? (STDERR) Error: Cannot find module 'fibers'
W20150623-11:34:49.825(-3)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150623-11:34:49.826(-3)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150623-11:34:49.826(-3)? (STDERR)     at Module.require (module.js:364:17)
W20150623-11:34:49.826(-3)? (STDERR)     at require (module.js:380:17)
W20150623-11:34:49.826(-3)? (STDERR)     at Object.<anonymous> (/home/fbarros/sistemas/outros/libreboard/.meteor/local/build/programs/server/boot.js:1:75)
W20150623-11:34:49.826(-3)? (STDERR)     at Module._compile (module.js:456:26)
W20150623-11:34:49.826(-3)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20150623-11:34:49.826(-3)? (STDERR)     at Module.load (module.js:356:32)
W20150623-11:34:49.827(-3)? (STDERR)     at Function.Module._load (module.js:312:12)
W20150623-11:34:49.827(-3)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 8                        
=> Your application is crashing. Waiting for file change.

**Comment by udisun** [comment]
I Had the same problem
I see now that the new version has this fixed
try to clone again

**Comment by mquandalle** [comment]
I'm also unable to reproduce this,.

**Comment by mquandalle** [comment]
Is it related to #226?
