### ISSUE TITLE
API add received date

### ISSUE THREAD

**Issue by kromonos** [wekan/wekan#2096]
When adding cards via API, it would be nice, when it's able to set the received date. Or is it already possible and I couldn't see it?

https://github.com/wekan/wekan/blob/c115046a7c86b30ab5deb8762d3ef7a5ea3f4f90/models/cards.js#L487

**Comment by xet7** [comment]
I think after creating you can update card by adding receivedAt etc

https://github.com/wekan/wekan/wiki/REST-API-Cards#update-a-card

**Comment by kromonos** [comment]
Unfortunately not yet. As on https://github.com/wekan/wekan/blob/c115046a7c86b30ab5deb8762d3ef7a5ea3f4f90/models/cards.js#L520 described, update only accepts  title, description, card id, board id, and list id, when I read the code correctly

**Comment by arradoq** [comment]
I have tested it, it is able to add date via PUT method. So first maybe you can POST your detail (title, description) then add the rest via PUT. Tested using VBA-Web to wekan 1.97

**Comment by Keelan** [comment]
Did this ever get complete?
I have a need to set fields such as the dates on POST and PUT.

**Comment by xet7** [comment]
@Keelan 

You can read API code, and if it's missing, add it with pull request. Thanks!
https://github.com/wekan/wekan/blob/master/models/cards.js#L2119

**Comment by Keelan** [comment]
If i was comfortable with the language i definitely would. PHP is where i live.

I see the `edit_card` has a bunch more fields to set. Maybe ill have a crack at modifying that code into the `new_card`, thoughts?

**Comment by xet7** [comment]
@Keelan 

Already before newbies with no Javascript experience [have added major features to Wekan](https://blog.wekan.team/2018/05/wekan-v1-00-released/). Just read that code, and add missing fields.

**Comment by xet7** [comment]
All Wekan REST API code is at `wekan/models/*`. So to add missing API, you just basically copy-paste similar code from same or different file to be the new API.

**Comment by Keelan** [comment]
@xet7 i've forked ill take a look this weekend. And hopefully push something over.
SOmewhat related, getting a list of labels for a board doesn't seem to be present in the API either

Only `PUT`
https://github.com/wekan/wekan/blob/master/models/boards.js#L1640

Ill take a look at that also.

**Comment by xet7** [comment]
@Keelan 

Thanks a lot ! Yes, a lot of API is missing, like modifying what is allowed to be visible at cards, like due date etc.

**Comment by xet7** [comment]
@Keelan 

Any progress?

**Comment by Keelan** [comment]
See my previous comment. I figured a post then retrieve the id and update
with a put was fine. Better to ensue it was created the update as required.
