### ISSUE TITLE
Feature Request: Attachment reorder and rename

### ISSUE THREAD

**Issue by mfilser** [wekan/wekan#2099]
Hello,
i have the following issue with card attachment's.
1. i want to reorder the attachment's
2. rename the filename of the attachment

Is there a way to do it?

**Comment by xet7** [comment]
1. Reorder attachments: in what way it should be possible?

**Comment by mfilser** [comment]
Hello @xet7 ,
sorry for the late answer, i did't get a notification about your comment.

I want to reorder the attachements i uploaded, maybe if possible by drag / drop.

Thank you for your amazing work on Wekan, it's very useful in business and tasks at home :)
