### ISSUE TITLE
Installation fails: Unknown package in top-level dependencies for wekan-ldap, accounts-cas, wekan-scrollbar

### ISSUE THREAD

**Issue by Jacobclaerhout** [wekan/wekan#2102]
However I try to initialize the latest dev version of Wekan (using Root installation or via Docker), I come to the following error when running meteor:

The same thing happens when I follow these guidelines: https://github.com/wekan/wekan/wiki/Install-from-source-without-root

```
=> Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: wekan:wekan-ldap
unknown package in top-level dependencies: wekan:accounts-cas
unknown package in top-level dependencies: wekan-scrollbar

ERROR: Service 'wekan-dev' failed to build: The command '/bin/sh -c chown -R wekan:wekan /home/wekan &&     chmod g+s /home/wekan &&     gosu wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build &&     chown wekan:wekan --recursive .meteor' returned a non-zero code: 1
```

The Docker-MongoDB version works perfect on Port 80, but I want to have the code in a local dev environment.

Thanks in advance for the help!

**Comment by xet7** [comment]
That is outdated page

There is at github.com/wekan/wekan script rebuild-wekan.sh that when selected 1) will install dependencies and 2) will build wekan, although it can have bugs too
and fixed paths etc. I think actually installing without root is not possible yet.

There is in progress making Wekan build with just running command `meteor`, so there will be simpler scripts.

Sorry about all the mess. I welcome all new contributors.
