### ISSUE TITLE
Attachments cannot be downloaded if they exceed a certain size

### ISSUE THREAD

**Issue by timothyparez** [wekan/wekan#2103]
## Issue

I can upload small files, for example a PNG and download them from a card.
But if the attachment is to big, nothing happens when I click download (firefox, edge, brave).

For example: if I attach this 2MB png to a card I cannot download it:

![clouds](https://user-images.githubusercontent.com/2060470/51111702-d823bf00-1837-11e9-8e9a-c6156b4aee40.png)

This also applies to all other filetypes.

(I uploaded a whole bunch of documents before I realized this, the data dir is now 300+ MB)

**Server Setup Information**:

Docker instance from `wekanteam/wekan` 
Version: 2.01.0
Node Version: 8.15
Mongo: docker instance from mongo

**Problem description**:

Upload the attached png to a board. Try to download it using Firefox, Edge, Brave

**Comment by xet7** [comment]
Works for me on Firefox and Chrome. Wekan does not have any files size limitations. Most likely you have some webserver like Nginx configure wrong in front of Wekan, and Nginx adds file size limitations.

In related note, Trello free version has attachment size limitations.

**Comment by timothyparez** [comment]
Are you saying nginx has a 1MB file size limitation by default?

**Comment by timothyparez** [comment]
Ok it seems that it does, for future reference this can be set in `/etc/nginx.conf`

```
http {
    ...
    client_max_body_size 100M;
}    
```
