### ISSUE TITLE
Card is no longer draggable after resizing screen

### ISSUE THREAD

**Issue by ajRiverav** [wekan/wekan#2105]
**Problem description**:
1) Open any board on a desktop screen.  
2) Shrink screen horizontally until a card disappears. That is, go from this:
![image](https://user-images.githubusercontent.com/22076301/51148424-86c60080-1834-11e9-909f-54236ec89b0c.png)
to this
![image](https://user-images.githubusercontent.com/22076301/51148437-90e7ff00-1834-11e9-8409-28dbb04217c7.png)
3) Notice how the card is now undraggable. This is a bug because one would expect the card to retain its draggable property. 

![image](https://user-images.githubusercontent.com/22076301/51148480-c4c32480-1834-11e9-8b1e-882ea1083986.png)

**Comment by xet7** [comment]
Use drag handle arrow-cross to drag. On mobile, other areas of card can be used to move page up and down.
https://github.com/wekan/wekan/issues/1772
https://github.com/wekan/wekan/pull/2067
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v195-2018-12-21-wekan-release

Upcoming:
Drag handles for lists in mobile:
https://github.com/wekan/wekan/issues/2098
Drag handles and long press for desktop webbrowser
https://github.com/wekan/wekan/issues/2081

**Comment by ajRiverav** [comment]
@xet7 watch video -> https://drive.google.com/file/d/1pcmngUrxApnGecZ1t0nyHW3p-nd0D5wr/view?usp=sharing

the issue is that cross-arrow handle disappears when you resize screen to its original width.

**Comment by xet7** [comment]
@ajRiverav 

You need to reload Wekan page so that cards are draggable again in original width.

Sometime when cross-arrow is implemented for full width, dragging with cross-arrow works all the time.

**Comment by ajRiverav** [comment]
got it. As long as you are aware of it , it's ok 👍
