### ISSUE TITLE
stmp invalid login: 502 Command "AUTH PLAIN

### ISSUE THREAD

**Issue by voicyfei** [wekan/wekan#2106]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:YES 
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? YES
* Wekan version: v2.01.0
* If this is about old version of Wekan, what upgrade problem you have?: new deployed
* Operating System: kubernetes
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):mongodb
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):no
* Node Version:
* MongoDB Version:v3.2.20
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): inner network 

**Problem description**:
i set up mail_url as 
smtp://a@b.com:pd@192.168.100.1:25/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false
 
when regist, i got in log
invalid login: 502 Command "AUTH PLAIN

what can i do?

**Comment by xet7** [comment]
Urlencode special characers, see top of this page:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by xet7** [comment]
You should only urlencode username and password. Not any other characters like : etc

**Comment by xet7** [comment]
What SMTP server are you trying to use?

**Comment by xet7** [comment]
Maybe it does not have non-encrypted port 25 sending at all. So it would require TLS.

**Comment by voicyfei** [comment]
No
I put the image of wekan and mongo3.2.20 to kubernetes managed by rancher

**Comment by voicyfei** [comment]
wekan:latest with the version of 2.01.0

**Comment by xet7** [comment]
Use the `authMethod` option to select a different method if your server does not support PLAIN. See the docs [here](https://nodemailer.com/smtp/)

I found this comment from:
https://github.com/nodemailer/nodemailer/issues/832#issuecomment-358258315

**Comment by xet7** [comment]
You could also google search for "smtp invalid login 502 AUTH PLAIN" for other ways to fix it. If you find something that works, please add comment to this issue.

**Comment by voicyfei** [comment]
Thank you. I'm trying.....

**Comment by voicyfei** [comment]
I tried nodemailer， not ok. crying.....
Can I switch a module of send email of wekan?

**Comment by xet7** [comment]
@voicyfei 

Does your IBM notes server have SMTP sending enabled?
https://stackoverflow.com/questions/45458885/how-to-send-mail-from-ibm-lotus-notes-using-nodemailer

**Comment by voicyfei** [comment]
I'm  sure it had enabled.  I can send mails through smtp with  Go or C# program.
I'm debuging nodemailer, try to find the issue.

**Comment by voicyfei** [comment]
holy！！！！
My email server don't need an authorization !!!!!
just remove the login name and password in the url .......
e~~

**Comment by voicyfei** [comment]
@xet7 thank you
