### ISSUE TITLE
"Edit Notifications" not showing up at Member Settings

### ISSUE THREAD

**Issue by sagilcas** [wekan/wekan#2108]
## Issue

"Edit Notifications" not showing up at Member Settings: 

![image](https://user-images.githubusercontent.com/22825706/51179654-78282980-18c6-11e9-92e1-82ca62b0a01c.png)

However, at "features" this option is showing up (https://github.com/wekan/wekan/wiki/Features)

Thanks!

**Server Setup Information**:

* Did you test in newest Wekan?:
Yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
Yes
* Wekan version: 2.01
* Operating System:
Ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
Nginx

**Comment by xet7** [comment]
That duplicate menu was removed, I updated features page:
https://github.com/wekan/wekan/wiki/Features#member-setting-when-clicking-your-username-on-top-right-corner
