### ISSUE TITLE
Feature Request: global webhook setting

### ISSUE THREAD

**Issue by andyprv** [wekan/wekan#2109]
## add global webhook setting 

All Boards are reporting to global specified WebHook Address. 

```bash

....
    -e "Global_Webhook_URL=http://127.0.0.1/wekan"
....  

```

**Comment by xet7** [comment]
Doh, now that I read your feature request again, yes, you did mention all board. Ok.

**Comment by andyprv** [comment]
Right , all Boards,  cause if an user creating a new Board, I'am as Admin  don't know this.

Well , I can check the MongoDB frequently , If there is an Board without Webhook URL ....

---
Thanx that you set it on the Wekan Milestone list .

**Comment by xet7** [comment]
Global Webhooks setting is at Admin Panel.

**Comment by smokhtari-pacdev** [comment]
This is a problem when boards are private and people don't want others (let say other admins) to see their activity as it sends out the details of private boards too. I suppose it shouldn't be doing that by default. If someone wants that on a Private board they should add it there.
Thank you!

**Comment by xet7** [comment]
@smokhtari-pacdev 

Your issue moved to https://github.com/wekan/wekan/issues/3022#issuecomment-634248516
