### ISSUE TITLE
Editors can not modify label titles / colors

### ISSUE THREAD

**Issue by kentonv** [wekan/wekan#2113]
On Sandstorm, only the owner of a board is able to edit the names and colors of labels. People with edit access are presented with the UI, but their changes are not saved. On the JS console, I see `update failed: Access denied`.

Steps to reproduce:
1. Create a new Wekan board and create a column and card.
2. Share it with another account, providing "can edit" access.
3. On the recipient account, edit the card's labels, and click the pencil icon next to the label color to edit the label itself.
4. Make a change to the label and save it.

Expected result: The label changes.
Actual result: The change is not saved, and "Access denied" is reported on the JS console.

**Comment by jrbattles** [comment]
I can confirm that I experience the same thing.

**Comment by Henry78** [comment]
Me too, but running the snap version. An with a regular card, not shared, and I'm admin. Fun fact: If I save the tag name, it's displayed for a moment as label caption an then vanished. The label name is gone. This is easily reproducible here.

**Comment by medienverbinder** [comment]
I have exactly the same problem as [Henry78](https://github.com/wekan/wekan/issues/2113#issuecomment-476353250) describes.

**Comment by xet7** [comment]
Having non-board-admin user editing labels is not yet implemented. Also non-board-admin user can not edit members.
Usually creator of the board has board-admin access to it, and has permission to set any other user as board-admin.
Possible board roles are listed in this API page:
https://github.com/wekan/wekan/wiki/REST-API-Role
And board admin can also set permission for each user in wekan board webpage.

There are these possibilities to fix this, these are not implemented yet:
- Add possibility for users to edit labels.
- Make all board members to board admins as default.
- On board, invite new user directly with email address, without using Admin Panel or registering at /sign-up #2060 .
- Add button to make all users to be board admins. Or alternatively, add wiki page with instructions how to make this change to MongoDB.

Currently at Sandstorm old board permissions stay, and newly created board creator gets Standalone Wekan Admin Panel. That is Admin permission, it's different from board-admin.

Related: Even members can assign cards to other members #282 . Yes, for some problem is too much permissions, and for some too little permissions.

Related: Teams/Organizations #802

Anyone, please add comments how this should work.

**Comment by loucurapt** [comment]
On Trello, a user with "normal" permissions on a board can add, edit and delete labels.
Maybe on Wekan, "normal" users on a board should also be able to manage labels?

You could also add an option for board admins to lock/unlock each label.
Or an option on the boards and/or admin panel to allow "normal" users to edit labels.

**Comment by rasos** [comment]
As in scrum projects we usually have a quite flat hierarchy, every user should be allowed to assign or edit labels by default. An option could be added to lock all or maybe each label.

**Comment by xet7** [comment]
Moved to #3022
