### ISSUE TITLE
https://releases.wekan.team/ down.

### ISSUE THREAD

**Issue by theonafor** [wekan/wekan#2122]
## Issue
**Problem description**:
Seems that [https://releases.wekan.team/](https://releases.wekan.team/) is down, and new versions precompiled Wekan releases can't be downloaded.

**Comment by xet7** [comment]
Sorry, Caddy webserver has errors about Let's Encrypt rate limits. I will try to do some workaround.

**Comment by xet7** [comment]
Now it works, there is workaround, by using CloudFlare. I try to get Let's Encrypt working later.
