### ISSUE TITLE
Swimlanes Chinese characters are in the wrong direction

### ISSUE THREAD

**Issue by ShuiHuo** [wekan/wekan#2133]
![default](https://user-images.githubusercontent.com/7471938/51794353-e0063a80-220b-11e9-8f86-7fd8a77ab75d.gif)

![snipaste_2019-01-27_08-09-45](https://user-images.githubusercontent.com/7471938/51794338-7dad3a00-220b-11e9-9134-6e95cb50cd1e.png)

**Comment by xet7** [comment]
@ShuiHuo 

You have old Wekan version. Please try newest Wekan v2.04 that was released today, where vertical swimlane title has been changed to horizontal.
