### ISSUE TITLE
Feature Request: Change key names of Outgoing Webhook

### ISSUE THREAD

**Issue by n0n0n0n0** [wekan/wekan#2135]
I didn't find any templates of webhooks, is it possible to customize webhook?
I have another chat (not slack or rocket) and want to make webhook for it, is it possible to customize request data?

**Comment by xet7** [comment]
@n0n0n0n0

If you don't want to include all data of webhook, you can leave some of them out, like described at:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

```
webhooks-attributes: What to send to Outgoing Webhook, or leave out.
                 Example, that includes all that are default: 
                 cardId,listId,oldListId,boardId,comment,user,card,commentId .
                 To enable the Webhooks Attributes of Wekan:
                 snap set wekan webhooks-attributes=cardId,listId,oldListId,boardId,comment,user,card,commentId
                 Disable the Webhooks Attributest of Wekan to send all default ones:
                 snap set wekan webhooks-attributes=''
```
For example, sending only comments and users to webhook:

## Snap
```
sudo snap set wekan webhooks-attributes='comment,user'
```
## docker-compose.yml
```
export WEBHOOKS_ATTRIBUTES=comment,user
```
## Source start-wekan.sh
```
export WEBHOOKS_ATTRIBUTES=comment,user
```

**Comment by n0n0n0n0** [comment]
yea that's good but anyway i cant change keys of post request?

**Comment by dapricu** [comment]
I'd be interested in this too. Any way to add, for example, start and end date to the Webhook? It woud be awesome to add things like start and end date, coulour, label, or custom fields information to the 
webhooks.

 It would become much easier to work, for example, with google calendar.

**Comment by xet7** [comment]
Moved to #2135
