### ISSUE TITLE
Wonky scroll

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2136]
Hi

I am not sure when this started but the scrolling with wheel in the cards is super slow and glitchy. It takes like 5 seconds to scroll to the bottom of a card when it is open.

I am using the Snap package on Debian, and I just updated to the latest, the issue is still there.

**Comment by xet7** [comment]
What browser and browser version?

**Comment by gerroon** [comment]
I use Firefox 64, the browser's scroll speed is fine never have any issues with other sites. This is only an issue inside a card.

**Comment by gerroon** [comment]
I just tried with chrome, same issue, you cna make it worse by zooming in on the page

**Comment by xet7** [comment]
This is fixed in Wekan v2.08 that is now in progress of being released now.

**Comment by gerroon** [comment]
Is this in the current snap release?

**Comment by gerroon** [comment]
I have 2.09 and and the vertical scroll feels even worse

**Comment by xet7** [comment]
Moved to #2179
