### ISSUE TITLE
No left or right scroll with Firefox 

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2137]
It looks like FIrefox is not able to show the bottom scroller for left or right. I can get this with Chromium but not with Firefox 64.

I cant tell what version of Wekan I am using since I set it up using Snap on Debian

**Comment by zombah** [comment]
+1 Just tried v2.06 docker and scroll  on Firefox not working, it looks like v2.02 was last working fine on Firefox version, so something in v2.03 changes breaks it

**Comment by gerroon** [comment]
Thanks for checking it

**Comment by vjrj** [comment]
see #2134

**Comment by xet7** [comment]
I made that card below swimlane fix [Firefox-only](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v206-2019-01-27-wekan-release) but seems that it made left-right scroll not work. I'll try to to make that fix up-down only.

**Comment by gerroon** [comment]
Thanks for looking into it

**Comment by mueschel** [comment]
My installation claims to be on v2.07, but there is still no horizontal scroll bar.

**Comment by xet7** [comment]
@mueschel 

What Firefox version? On my Firefox v64 when there is added so many cards or lists that they don't fit into screen, scrollbars appear.

**Comment by mueschel** [comment]
That's a FF 60.4.0esr (64-bit) on OpenSuse.  I'm missing the scroll bar in both the swimlane view and the normal list view without swimlanes.

**Comment by mueschel** [comment]
Many companies rely on ESR versions of software. This particular one will be supported and be receiving security fixes for another 10 months.

**Comment by xet7** [comment]
I presume someone from those companies will send pull request to fix that bug.

Currently I'm busy with other work.

**Comment by xet7** [comment]
@bentiss 

Do you have time to look at this? I would think this would require detecting Firefox ESR version or using some feature detection, and then setting overflow in such way it would work.

**Comment by bentiss** [comment]
@xet7 

I am actually trying to understand why the automate scrolling on the card details view is now also broken (horizontally, and slightly less vertically). I think this is all related to how I needed to add one more level in the js-swimlanes, and hopefully fixing properly the source of the problem will also solve those horizontal scrollbar disappearing

**Comment by bentiss** [comment]
OK, so the main difference between now and v2.02 is that in v2.02, scrolling appear on the BoardBody, so there is only one horizontal scrollbar at the bottom and one vertical on the left (plus per list vertical scrollbars). On the new code, there is one horizontal scrollbar per swimlane, which confuses both the automatic scroll and the rendering on FF 60.

I'll try to find a solution.
