### ISSUE TITLE
Feature Request: Custom type for URL links

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2138]
Hi

I feel like it would be nice to have another custom type field for urls, which can be rendered much smaller than the regular text to show in the cards. 

The current text field can render urls but they look like regular text, and to be honest they look uggly like that since it autowraps them.

**Comment by gerroon** [comment]
See how ugly a url looks in a text field

![screenshot_2019-01-27_14-32-43](https://user-images.githubusercontent.com/8519469/51806533-c5b37780-2272-11e9-8933-17ccb8fa6f60.png)

**Comment by xet7** [comment]
Try does it accept markdown?
```
[Docs](https://docs.python.org/3/library/pathlib.html)
```

**Comment by gerroon** [comment]
Sure, but that is not really solve the issue, it is just naming it short (docs) that it does not look ugly. If I make the `[Docs]` text part long enough it will still look ugly.I hope it makes sense

What would be nice is actually the link itself will be rendered with much smaller font and it is not wrapped ugly.

**Comment by gerroon** [comment]
Here I am tryinng to represent what I was trying to ask for as a feature. To  me this kind of url represantation might look better, naturally optional.

![photoshop_p1nq3v8zm6](https://user-images.githubusercontent.com/8519469/51811841-dd0c5800-22a6-11e9-983d-2ea546e181cc.png)

**Comment by xet7** [comment]
You could try to use some markdown or HTML to make text smaller. There are some markdown examples at https://wekan.github.io .

**Comment by xet7** [comment]
It's now possible to use markdown at Custom Fields.
