### ISSUE TITLE
wekan after low space do not start

### ISSUE THREAD

**Issue by Michael2222** [wekan/wekan#2146]
Hello,

I have installed wekan with docker. Yesterday my store from my VM are empty and wekan do not start.
So I have increase the store, but wekan start not again!
What can I do, than wekan start again (repair, log files, ...)
Thank you for any hint!
    Michael

**Comment by xet7** [comment]
Yes repair info is somewhere here:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by xet7** [comment]
For Docker here:
https://github.com/wekan/wekan-mongodb/issues/6#issuecomment-424004116

**Comment by xet7** [comment]
These links are from Wekan GitHub wiki menu / Repair

**Comment by xet7** [comment]
Also look where your database files are like /var/lib/docker/... so you have not started some new container without data

**Comment by xet7** [comment]
Also at Wekan GitHub wiki see backup page, I recommend making backups at least once per day.

**Comment by xet7** [comment]
I don't know is this wekan related, or bug in mongodb or docker. I also have no ideas about how to fix this.
