### ISSUE TITLE
Feature Request: Search users on Admin Panel

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2154]
Wekan version: 2.12

The ability to search for a particular user (by email or username) on the People section of the Admin Panel would be very helpful. It is rather tedious to scroll through hundreds of users in order to reset someone's password, or make them inactive.

**Comment by rjevnikar** [comment]
need to test but may be resolved in v2.61

**Comment by xet7** [comment]
Yes, search at Admin Panel works.
