### ISSUE TITLE
Feature Request: Add more board colors

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2156]
Hi

Is there any reason why we have only 6 colors for boards? You know these colors will repeat if the user has more than 6 boards and uses one color for each, which will end up creating unnecessary relationships between boards based on these colors. 

it would be nice if we have more colors with better variations like lesss saturation, more grays and less ambitious colors.

thanks

**Comment by gerroon** [comment]
Thanks for considering, this would be amazing. Colors are helpful with organizing ideas.

**Comment by gerroon** [comment]
Hi

See these colors from protonmail's settings. I think they are a good color  set

![screenshot_2019-02-09_23-50-45](https://user-images.githubusercontent.com/8519469/52530121-4012db80-2cf8-11e9-87c7-9a6c21bcdf36.png)

**Comment by gerroon** [comment]
I am just wondering if this thing is planned for soon or is it backlogged for quite sometime?

**Comment by xet7** [comment]
@gerroon 

This issue [does not have bounty](https://www.bountysource.com/issues/69535457-feature-request-add-more-board-colors) ([info about bounties](https://wekan.team/bounties/index.html)) so it is backlogged.

**Comment by gerroon** [comment]
I see. I am in no position to be able to pay for a bounty to get this done however I am ok with donating to the pool.

**Comment by xet7** [comment]
I did add some more colors and themes to Wekan. But really, adding so many is just overloading menu. If you would like to add some really different color or theme to Wekan, please add pull request, see details at:
https://github.com/wekan/wekan/wiki/Custom-CSS-themes
