### ISSUE TITLE
Feature Request: Preview link content

### ISSUE THREAD

**Issue by saurabharch** [wekan/wekan#2158]
There is no preview link content feature in Wekan, need to add this feature ,

example is here 

![ssr](https://user-images.githubusercontent.com/22369562/52169716-1a6b5c80-2763-11e9-8e4f-9046da845393.png)

**Comment by distantbit** [comment]
Is this feature still on the roadmap? I don't think that link preview is an accessibility related issue. Would love to see this in a near release.

**Comment by xet7** [comment]
@distantbit 

Yes, you are correct, this is not related to accessibility. I don't use GitHub milestones at all for Roadmap.

[Current Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) does not have this feature, I think.

If someone would like this, maybe:
a) someone could send pull request
b) someone could fund me to development this feature for 1000 euro https://wekan.team/commercial-support/

**Comment by xet7** [comment]
Well, it seems this is hard feature to implement correcty, as seen by some other software, so I don't know does this feature make any sense.

https://positive.security/blog/ms-teams-1-feature-4-vulns

https://news.ycombinator.com/item?id=29647457
