### ISSUE TITLE
Reordering swimlanes feature apparently does not work

### ISSUE THREAD

**Issue by helderneres** [wekan/wekan#2159]
Reordering swimlanes feature apparently does not work

**Server Setup Information**:

* Did you test in newest Wekan?: Yes.
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes, the system is in production by a long time.
* Wekan version: 2.14.
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu 18.04.
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap.
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version:
* MongoDB Version: 
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Client Setup Information**:
* Browsers: Firefox, Chrome.

**Problem description**:

In version 2.14, and some earlier, the reordering swimlanes feature (https://github.com/wekan/wekan/wiki/Swimlanes#to-reorder-swimlanes) apparently does not work.

![Screenshot](https://user-images.githubusercontent.com/4276613/52169724-ee78b880-271b-11e9-838e-f7b3c41f5de8.gif "Screenshot")

**Comment by xet7** [comment]
@bentiss 

Can you look at this?

**Comment by dabroz** [comment]
Confirmed. Wekan has autoupgraded and swimlane reordering stopped working.

**Comment by bentiss** [comment]
> @bentiss
> 
> Can you look at this?

right, still  the same bug than the scrolling one, adding components in the DOM tree messed things up.

**Comment by bentiss** [comment]
> right, still the same bug than the scrolling one, adding components in the DOM tree messed things up.

I spent almost 2 full days on this, and this is not easy (I am not a JS programmer, but still). I have a local workaround, but the reshuffling is all jumpy. I can't really revert to one `div` per swimlane because of the Firefox bug introduced in v2.04 IIRC.

So we need to adapt the `sortable` pattern to allow it to skip the slots between the headers and the list of cards in each swimlane.

**Comment by helderneres** [comment]
Great! Thanks!
