### ISSUE TITLE
search plugin/addon

### ISSUE THREAD

**Issue by Scept1c** [wekan/wekan#216]
Hi.
It's possible add feature to search Card's, List's, Comment's, ALL things in dashboard?

At the photo on libreboard github page is icon of search.

I could not find this option in source code, maybe i was not looking too deeply.

Thx for reply.

S.

**Comment by ssimono** [comment]
+1

**Comment by ssimono** [comment]
I just realized that this may be a duplicate of #33...

**Comment by enriquetuya** [comment]
Not having search made me discard the possibility of using wekan. That is definitely a needed feature for this kind of tools.

**Comment by zeigerpuppy** [comment]
I agree that this is an essential feature, it becomes very difficult to manage a board as it grows without seach

**Comment by Umi97** [comment]
+1

**Comment by laupkram** [comment]
+1

**Comment by vhadjisophocle** [comment]
+1

**Comment by aneocleous** [comment]
+1

**Comment by GSWemigo** [comment]
+1

**Comment by rhelsing** [comment]
+1

**Comment by xet7** [comment]
Don't add comment with +1, use thumbsup reaction.

**Comment by xet7** [comment]
Moved to #552
