### ISSUE TITLE
Strange bug with moving cards between columns...

### ISSUE THREAD

**Issue by therampagerado** [wekan/wekan#2161]
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 2.16.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): no
* Node Version: 8.15.0
* MongoDB Version: don't know
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): no

**Problem description**:
- sometimes we have strange "poltergeist" moving cards between columns, like in the last 30 minutes I was deleting old cards from our Archive board (not to be confused with the Archive of every boards) then deleting them from the actual Archive of that board. The system was unresponsive and unusable with ~350-400 cards in it so I had to do this.

In the meantime in our actual production board some cards were moved between columns including some cards by me. 

The same scenario appears randomly with random users, on random time intervals. The common is that it's always number of cards, not simply 1 or 2 cards accidentally dragged accross, it's always 3-4 cards.

I usually joke with my collegues that they are stupid but now there were cards moved by my account and I even was not in this board to have the opportunity to accidentally drag/drop them.

Does somebody else observe something similar?

**Comment by xet7** [comment]
@therampagerado 

Just guessing, this could be related to #2159 , so please wait until it is fixed.

**Comment by therampagerado** [comment]
@xet7 thank you for your comment!

Unfortunatelly I've been observing those issues many versions ago too. It's very little chance that it's related to this feature because it was introduced few versions ago. We use Wekan like almost an year now and those strange 'movements' were noticed I think last Summer...

**Comment by rjevnikar** [comment]
@therampagerado  is there anything in the logs? Are cards reverting back to old locations?
