### ISSUE TITLE
Unexpected token - wekan-manifest.json

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2168]
Server Setup Information:
Wekan v2.17
Deployment Method: Docker
Front-End: Nginx load balancer
MongoDB: 3.2.21
Node: v8.15
OS: CentOS 7

Problem description:
When loading all pages, the following error appears in the console:
`Manifest:  Line: 1, column: 1, Unexpected token.
wekan-manifest.json:1`

I'm not sure how important it is, but thought it was worth mentioning.

**Comment by keigel2001** [comment]
I've got the same problem under debian 9.7 with nginx 1.15.8
