### ISSUE TITLE
Slow Log-in/Log-out

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2169]
Setup Information
Wekan Version: 2.17
Deployment Method: Docker (4 containers)
Docker Image: quay.io/wekan/wekan:latest
Front-End: Nginx:Alpine (latest)
MongoDB Version: 3.2.21
Node Version: 8.15
Root URL: https://example.com
Authentication Method: password

Host System:
OS: CentOS 7
CPU: 8 CPU
RAM: 16 GB

Environment Variables:
      - ROOT_URL=https://example.com
      # - PORT=8080
      - MONGO_URL=mongodb://wekandb:27017/wekan?replicaSet=rsWekan
      - MONGO_OPLOG_URL=mongodb://<user>:<pword>@wekandb:27017/local?authSource=admin&replicaSet=rsWekan
      - MAIL_URL=smtp://example.com:25/
      - MAIL_FROM=Wekan <wekan.noreply@example.com>
      - WITH_API=true
      #- MATOMO_ADDRESS=
      #- MATOMO_SITE_ID=
      #- MATOMO_DO_NOT_TRACK=
      #- MATOMO_WITH_USERNAME=false
      - BROWSER_POLICY_ENABLED=true
      #- TRUSTED_URL=
      #- WEBHOOKS_ATTRIBUTES=
      - OAUTH2_ENABLED=false
      #- OAUTH2_CLIENT_ID=
      #- OAUTH2_SECRET=
      #- OAUTH2_SERVER_URL=
      #- OAUTH2_AUTH_ENDPOINT=
      #- OAUTH2_USERINFO_ENDPOINT=
      #- OAUTH2_TOKEN_ENDPOINT=
      - LDAP_ENABLE=false
      #- LDAP_PORT=
      #- LDAP_HOST=
      #- LDAP_BASEDN=
      #- LDAP_LOGIN_FALLBACK=false
      #- LDAP_RECONNECT=true
      #- LDAP_TIMEOUT=10000
      #- LDAP_CONNECT_TIMEOUT=10000
      #- LDAP_AUTHENTIFICATION=false
      #- LDAP_AUTHENTIFICATION_USERDN=
      #- LDAP_AUTHENTIFICATION_PASSWORD=
      #- LDAP_LOG_ENABLED=false
      #- LDAP_BACKGROUND_SYNC=false
      #- LDAP_BACKGROUND_SYNC_INTERVAL=100
      #- LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=false
      #- LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=false
      #- LDAP_ENCRYPTION=ssl
      #- LDAP_CA_CERT=
      #- LDAP_REJECT_UNAUTHORIZED=false
      #- LDAP_USER_SEARCH_FILTER=
      #- LDAP_USER_SEARCH_SCOPE=
      #- LDAP_USER_SEARCH_FIELD=
      #- LDAP_SEARCH_PAGE_SIZE=0
      #- LDAP_SEARCH_SIZE_LIMIT=0
      #- LDAP_GROUP_FILTER_ENABLE=false
      #- LDAP_GROUP_FILTER_OBJECTCLASS=
      #- LDAP_GROUP_FILTER_GROUP_ID_ATTRIBUTE=
      #- LDAP_GROUP_FILTER_GROUP_MEMBER_ATTRIBUTE=
      #- LDAP_GROUP_FILTER_GROUP_MEMBER_FORMAT=
      #- LDAP_GROUP_FILTER_GROUP_NAME=
      #- LDAP_UNIQUE_IDENTIFIER_FIELD=
      #- LDAP_UTF8_NAMES_SLUGIFY=true
      #- LDAP_USERNAME_FIELD=
      #- LDAP_MERGE_EXISTING_USERS=false
      #- LDAP_SYNC_USER_DATA=false
      #- LDAP_SYNC_USER_DATA_FIELDMAP=
      #- LDAP_SYNC_GROUP_ROLES=
      #- LDAP_DEFAULT_DOMAIN=

Problem:
Signing in and logging out of the application takes forever. No errors in the console.

**Comment by xet7** [comment]
Do you have Websockets enabled on your Nginx config?
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by rjevnikar** [comment]
Yes, I believe I do.
config file: 
[nginx.conf.txt](https://github.com/wekan/wekan/files/2832775/nginx.conf.txt)


When it eventually logs out in Firefox, the following error appears
```
Exception from Tracker recompute function:
45066f34dabe1f2c0c19ad221596efb2e5f75668.js:1:6261
TypeError: Boards.findOne(...) is undefined
45066f34dabe1f2c0c19ad221596efb2e5f75668.js:1:6261
editor.js/<@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:317:328650
t@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:59:21073
n/</<@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:59:19013
e._withTemplateInstanceFunc@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:59:37698
n/<@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:59:18956
f._withCurrentView@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:59:23097
n@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:59:18914
e.Computation.prototype._compute@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:21:2301
e.Computation.prototype._recompute@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:21:2542
e._runFlush@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:21:3718
e@https://example.com/45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:1:2469
45066f34dabe1f2c0c19ad221596efb2e5f75668.js:1:6261
```

**Comment by rjevnikar** [comment]
In Chrome, the error after logout is:
```
Uncaught Error: INVALID_STATE_ERR
    at O._didClose (45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:77)
    at 45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:77
    at n.XHRCorsObject.e.onfinish (45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:77)
    at n.XHRCorsObject.s.emit (45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:77)
    at XMLHttpRequest.s.xhr.onreadystatechange (45066f34dabe1f2c0c19ad221596efb2e5f75668.js?meteor_js_resource=true:77)
```
