### ISSUE TITLE
Can't login outside localhost ! 

### ISSUE THREAD

**Issue by Shurike** [wekan/wekan#217]
Hi there, 

I'm considering using Libreboard inside my company since our compliance rules dont allow us to store data outside our own infrastructure. 

So far I've set up Libreboard using Meteor on a personal test server, located OUTSIDE my company, and made it run on default port (3000). 

I'm encountering a strange issue however. As I said, my instance of Libreboard is running on a personal server outside my company, beyond our firewalls. 
- If I use SSH to connect to my server and then configure my browser to use SOCKS proxy, then hitting http://localhost:3000, Libreboard works pretty well. 
- If I don't use SSH to connect to my server and use http://my-ip-address:3000 (which would be a normal behavior normally), I can't create any account or even login with an existing account. 

Any ideas about what's wrong ? Why can I use it if I'm considered as localhost but not remotely ?

Thanks :+1:

**Comment by mko-x** [comment]
Hi Shurike,

first of all: It would help if you could provide some logs of your browser and your server.

So I can just do let's say 3 suggestions:

- Client firewall/proxy restrictions (maybe at your company)
- Server firewall/reverese proxy restrictions (maybe get tunneled via SSH if you are connected)
- Unset ROOT_URL environment variable

Well, I guess you don't want to use a backend which forces users to configure anything within their clients. 

If you run the board on your remote server and have it configured according to your server/client requirements - the app just runs out of the box.

Further questions would be:
- Did you change anything in the source code?
- Which environment are you running on (os, meteor, node, etc.)?
- Other way round: How do you run the server?

Finally, as you're considering to use the board for your company - that's great!
But have in mind that it is not yet a production ready system (upcoming 0.9)

Hope something helps :)

**Comment by mquandalle** [comment]
The [installation wiki page](https://github.com/wekan/wekan/wiki/Install-and-Update) now cover the points answered by @mko-x, so I’m now closing this issue. Documentation still need some work though.
