### ISSUE TITLE
Feature Request: Include Card List/Swimlane position to Outgoing Webhooks (was: Cards Monitoring via REST API)

### ISSUE THREAD

**Issue by arradoq** [wekan/wekan#2170]
## Issue

* Operating System: Ubuntu on Windows 10 no VM 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

I want to know how to track cards list position given only id of the cards via REST API? or another term is to get latest activity data?

**Comment by xet7** [comment]
Well, there is Outgoing Webhooks:
https://github.com/wekan/wekan/wiki/Outgoing-Webhook-to-Discord

But those do not currently have more specific details about card list/swimlane position, so that info would need to be added.
