### ISSUE TITLE
Wekan Deployment on Heroku fails

### ISSUE THREAD

**Issue by Fipz** [wekan/wekan#2176]
When using the **deployment button** on https://elements.heroku.com/buttons/wekan/wekan the build fails. 

ROOT_URL environment variable was set correctly. 

**Herku Build Log output:**

> -----> Node.js app detected
-----> Installing meteor
Downloading Meteor distribution
Meteor 1.8.0.2 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/app/tmp/cache/meteor/.meteor/packages/meteor-tool/1.8.0_2/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at docs.meteor.com.
-----> Target Meteor version: Meteor 1.6.0.1
-----> Checking if this meteor version supports --server-only
-----> Using node: v8.9.3
----->    and npm: 5.5.1
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
> bson-ext@2.0.1 install /tmp/build_ae305de4c00ef80ab66d3d48abf675eb/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)
make: Entering directory '/tmp/build_ae305de4c00ef80ab66d3d48abf675eb/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/src/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory '/tmp/build_ae305de4c00ef80ab66d3d48abf675eb/node_modules/bson-ext/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
added 225 packages in 13.238s
-----> Building Meteor app with ROOT_URL: https://wekandaitesting.herokuapp.com
=> Errors while initializing project:
While selecting package versions:
error: unknown package in top-level dependencies: wekan:wekan-ldap
unknown package in top-level dependencies: wekan:accounts-cas
unknown package in top-level dependencies: wekan-scrollbar
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by xet7** [comment]
Most likely those dependencies need to be included to wekan/packages directory to make it work. I'll try.

**Comment by xet7** [comment]
@Fipz 

Please try again. Now in newest Wekan v2.61 those package repos are included into main Wekan repo, so it should not complain about dependencies anymore.
