### ISSUE TITLE
Clone a Swimlane

### ISSUE THREAD

**Issue by OlivierOu** [wekan/wekan#2177]
Hello,
It is not really an issue but more a question.
I tried Wekan online and it looks exactly what I need for my team.
When my customer sends me a quality issue, I will use Wekan to assign task to my team.
Is it possible in that case to create a new swimlane as a clone of another one?
My goal is to have a sample swimlane and to copy it because in 99%, I will have the same task.

I tried to find the answer on the forum, but I could.

Thank you in advance for your answer

**Comment by xet7** [comment]
Moved to #2165
