### ISSUE TITLE
Feature Request: Import from file

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2178]
Hi,

Importing from clipboard is unbearable when the cards have images/files in them, naturally all that stuff sits in the json file and these get hugeee.

Can you please add a way to import boards from files directly, instead of clipboard thing? 

thanks

**Comment by gerroon** [comment]
Btw I cant even open these json files in Vim or Emcs, since they are huge :( I do not know I think we need a better way to import large files with embeds.

**Comment by xet7** [comment]
For viewing JSON files, you can use for example:
```
less wekan.json
```
or look at bottom 200 lines of JSON file
```
tail -200 wekan.json | less
```
For copying JSON to clipboard in Linux, it's possible to use xclip:
```
sudo apt-get install xclip
cat wekan.json | xclip -se c
```
And then paste in to webbrowser. Before pasting, do close other apps that are running, so you have enough RAM available. If it still does not work, you could run webbrowser and Wekan on server using remote desktop like VNC, to some server where is enough RAM.

Sure, these are workarounds, but these could help while I have not added uploading as files yet.

I have not checked does Wekan many any thumbnails from images that are visible at board. I don't know how much that would help using Wekan boards.

**Comment by xet7** [comment]
Also, if something needs search/replace in JSON file, you can use sed:
```
sed -i 's|something-text|use-this-text-instead|g' wekan.json
```

**Comment by gerroon** [comment]
@xet7 

Thank you for the detailed reply. 

Those work arounds are nice but I am personally not always on Linux, so it is though. Also this process crawls my laptop too :( These things can get many megabytes.

In any case I do wish to see a file import. Until then I will try your work arounds when I can.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
