### ISSUE TITLE
Feature Request: Emacs Org mode and Leo Literate Editor Import / Export, with tree view hierarachy

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2186]
Feature Request: Emacs Org mode and Leo Literate Editor Import / Export

Emacs Org mode:
http://orgmode.org/

Leo Literate Editor:
http://leoeditor.com/
Installing Leo:
http://www.xet7.org/leo

Currently there is Wekan board JSON Import/Export JSON textfile, that includes attachments. So code would need to be made to convert that JSON file to Emacs Org mode or Leo text file formats, using some programming language. If using Javascript, it could be added to Wekan menus.

**Comment by xet7** [comment]
Structure:
- [Tree Organization nested structure](https://github.com/wekan/wekan/issues/802#issuecomment-468516881) with any names and number of levels, for example: Super Admin / Company Group / Company or Department / Organization / Team / User
- For each level: Board Groups / Board / Swimlane / List / Card / Card name - Minicard text - Description text - Checklists - Attachments - Due etc Dates - Comments - etc
- Include all environment settings as tree structure for each setting type, for example: Settings / LDAP / LDAP_ENABLED etc
- At each level, it's possible import/export to current and below levels
- Leo editor Clones => Wekan Linked Cards and Linked Boards etc
- Import/Export everything in Wekan/Leo/Emacs Org mode format.
- Save all as template, for creating new Organization Structure with all settings as Template in [Tree Organization nested structure](https://github.com/wekan/wekan/issues/802#issuecomment-468516881) template menu where is currently Board Groups.

**Comment by xet7** [comment]
From @saurabharch 

[Vanila Community](https://community.vanila.io) uses [Spectrum that has GraphQL](https://github.com/vanila-io/spectrum/blob/alpha/README.md).

Why I am talking about graphql, and why it is necessary for wekan because we are dealing with data and availability.

In current status we didn’t support local data storage at client side and even we didn’t support single end point data interaction we have lot’s of rest api request now, and client request trips are over and over that is why wekan takes time to load large dataset of wekan board.

Spectrum use RethinkDB instead of mongoDB. Because RethinkDB provide direct push notifications service at subscribers. And stuff is full filled by Redis for serious data management from client side to server side.

**Comment by xet7** [comment]
@saurabharch

Because GraphQL is hierarchical, would GraphQL help with different hierarchical file formats like Emacs Org mode, Leo, Wekan JSON Import/Export, etc?

**Comment by xet7** [comment]
Moved to here from #2470

From @justinr1234

It would be good to have a todo-list style view across all cards in the system for the currently logged in user. The user should be able to get quick information about tasks without opening the board or individual cards. They should also be able to take quick actions. Please see Todoist as an example.

![todoist](https://user-images.githubusercontent.com/15545/59051517-c057e080-8895-11e9-8ad8-98203ea91bc8.gif)

**Comment by xet7** [comment]
With above, Wekan will have following viewing styles:
- Lists
- Swimlanes
- Tree
- Calendar

Mentioned #2470 `My Tasks` are actually [My Cards at Top Level Projects nested tabs view](https://github.com/wekan/wekan/issues/641#issuecomment-468868580).

Related to this, there could be feature for renaming of `Cards` to anything else, like `Tasks`, `Cars` or anything else.

**Comment by QJKX** [comment]
A possible avenue for this feature is to instead extend pandoc to support wekan & Leo.

**Comment by xet7** [comment]
@QJKX 

> A possible avenue for this feature is to instead extend pandoc to support wekan & Leo.

Maybe, if it would be some external tool. But including pandoc in WeKan itself, for example as NPM package, would most likely make WeKan GPL, because pandoc is GPL, and that is not possible, because I prefer keeping WeKan MIT.

For any import/export, I would prefer that it would not use any GPL code, and it would be included in WeKan itself, with Javascript.

**Comment by xet7** [comment]
There are also some Python code for WeKan at https://github.com/wekan/wekan/wiki/Python

**Comment by QJKX** [comment]
> including pandoc in WeKan itself, for example as NPM package, would most likely make WeKan GPL

Agreed.
A CLI wrapper would be possible and there are various modules that do that - but that approach has it's own compromises.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync

**Comment by xet7** [comment]
## Recurring checklists using Org Mode in Emacs

- https://www.naiquev.in/recurring-checklists-using-org-mode-in-emacs.html
- https://news.ycombinator.com/item?id=43014481
