### ISSUE TITLE
Center (or reduce left margin) in card view on mobile browser

### ISSUE THREAD

**Issue by MelBourbon** [wekan/wekan#2188]
## Issue / Improvement

* Wekan version: v2.22 2019-02-13

**Problem description**:
In mobile browsers (Chrome and Firefox on Android 9 and Safari on iOS 12.1.4) the card view seems to be not centered. There is a left margin but no right margin. The card is almost passing the right side of the screen. This leads to issues when closing a card (click on the cross). Card view should be centered or a margin on the right should be added. 

![screenshot_20190213-093425](https://user-images.githubusercontent.com/30600002/52699077-39dd6300-2f75-11e9-8c40-12704913eee7.jpg)

**Comment by hupptechnologies** [comment]
Working on it.
