### ISSUE TITLE
Download attachment button and upload avatar not working

### ISSUE THREAD

**Issue by PrestonL** [wekan/wekan#219]
The download attachment button does not perform any action.

**Comment by pcalex** [comment]
We met the same issue when we use download button in Attachments page. But we can download the attachment from log.

**Comment by zeineath** [comment]
after update to latest version the mentioned work-around (downloading from log) is no longer working. It only leads to a page saying: **Page Not Found - This page may be private. You may be able to view it by logging in.**

**Comment by pcalex** [comment]
After test on v0.9 rc, we met @zeineath problem as well. It shows "Page Not Found - This page may be private. You may be able to view it by logging in."

**Comment by pcalex** [comment]
The download button is working on v0.9, but I found if you try to use the link to download from log, it still shows "Page Not Found - This page may be private. You may be able to view it by logging in."
