### ISSUE TITLE
Feature Request: More customization/info on the board cards

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2192]
Hi

I feel like the board cards are wasting a lot of space and taking alot of space.They should be either smaller or the  user should be able to see more info there.

For instance

- Card`s creation date
- Card modif date
- Custom background image for the board card
- Number of total lanes and cards
- Users
- Number of done and open tasks

And more

thanks

**Comment by xet7** [comment]
At Wekan v3.98 board icons use variable height, based on how muct text etc content they have.
