### ISSUE TITLE
localhost/ host ip : port connection refused

### ISSUE THREAD

**Issue by jianlianggao** [wekan/wekan#2196]
## Issue

Add these issues to elsewhere:
- LDAP: https://github.com/wekan/wekan-ldap/issues
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

I used docker-compose.yml file to deploy WeKan on my Ubuntu 16.04.5 LTS
my docker-compose.yml is
```version: '2'
services:
  wekan:
    image: wekanteam/wekan:latest
    links:
      - wekandb
    environment:
      - MONGO_URL=mongodb://wekandb/wekan
      - ROOT_URL=https://<my ip>:8888
    ports:
      - 8888:80

  wekandb:
    image: mongo:3.2.14
    volumes:
      - /media/dockerdata/mongo_wekan/data:/data/db
```

The deployment has no error. But I can't connect to <my ip or localhost>:8888
I can only connect to the ip generated by docker

if I use wekan container released on 2018-03-14, I have no problem at all.

Any suggestions?
Many thanks.

**Comment by xet7** [comment]
Do you really have https for your IP address?
https://github.com/wekan/wekan/wiki/Settings

**Comment by jianlianggao** [comment]
Hi Lauri,
Thank you for this. The key point is not https:// directly on my Ubuntu. 
When I use wekan docker container from 2018-03-14, and keep other settings exactly the same. The wekan runs perfectly at http://<my ip>:8888  (not https, the https is implemented by a reverse proxy) While the latest WeKan docker container refuse connection at either 8888 or 80.  Reverse proxy returns 502 bad gateway when trying to visit https://<domain name>

**Comment by xet7** [comment]
You have wrong internal port. Correct one currenctly is 8080. It was changed because of fix to OpenStack config.
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L149

More normal config would be to have https://boards.example.com proxying to localhost Wekan, when Wekan would have these settings. Note that newes:
```
ports:
- 8888:8080
- ROOT_URL=https://boards.example.com
```

**Comment by jianlianggao** [comment]
Hi Lauri,

Thank you very much for your help. That sorted out my issue.
