### ISSUE TITLE
which standard compression type for mongodb is configured?

### ISSUE THREAD

**Issue by Michael2222** [wekan/wekan#2197]
Hello,

I have *.wt files from mongodb and I have read, that mongodb can compress the collection information.
It exist snappy or zlib algorithm.
What algorithm is the default, if I install wekan via docker?
Thank's!

**Comment by xet7** [comment]
I would guess it's snappy, but if MongoDB has some commandline options for algorithms used you could add them to docker-compose.yml.

**Comment by xet7** [comment]
Oops, I should first check MongoDB commandline options before closing this.

**Comment by xet7** [comment]
I think it's wiredTiger something, or whichever comes default with MongoDB.
