### ISSUE TITLE
Unable to upload avatar

### ISSUE THREAD

**Issue by PrestonL** [wekan/wekan#220]
Attempting to upload a PNG for an avatar causes a JavaScript Error:

[Error] Error: FS.Collection insert: file does not pass collection filters
	_withCurrentView (blaze.js, line 2199)
	(anonymous function) (blaze.js, line 2542)
	(anonymous function) (blaze.js, line 839)
	dispatch (jquery.js, line 4698)
	handle (jquery.js, line 4366)

Desired behavior should be to show acceptable filetypes, and an applicable error if an supported filetype.

**Comment by Akanoa** [comment]
Same issue here, I wanted upload a png picture: 

Uncaught Error: FS.Collection insert: file does not pass collection filtersr.Utility.handleError @ fea7e4c11474ab3265d3551c46af662866beab75.js:128r @ fea7e4c11474ab3265d3551c46af662866beab75.js:221o.Collection.insert @ fea7e4c11474ab3265d3551c46af662866beab75.js:221(anonymous function) @ fea7e4c11474ab3265d3551c46af662866beab75.js:351r.Utility.eachFile @ fea7e4c11474ab3265d3551c46af662866beab75.js:128change .js-upload-avatar-input @ fea7e4c11474ab3265d3551c46af662866beab75.js:351(anonymous function) @ fea7e4c11474ab3265d3551c46af662866beab75.js:195c._withCurrentView @ fea7e4c11474ab3265d3551c46af662866beab75.js:63(anonymous function) @ fea7e4c11474ab3265d3551c46af662866beab75.js:195e._withTemplateInstanceFunc @ fea7e4c11474ab3265d3551c46af662866beab75.js:64r.(anonymous function) @ fea7e4c11474ab3265d3551c46af662866beab75.js:195(anonymous function) @ fea7e4c11474ab3265d3551c46af662866beab75.js:63c._withCurrentView @ fea7e4c11474ab3265d3551c46af662866beab75.js:63(anonymous function) @ fea7e4c11474ab3265d3551c46af662866beab75.js:63(anonymous function) @ fea7e4c11474ab3265d3551c46af662866beab75.js:63ie.event.dispatch @ fea7e4c11474ab3265d3551c46af662866beab75.js:50g.handle @ fea7e4c11474ab3265d3551c46af662866beab75.js:50

**Comment by nata-goddanti** [comment]
https://github.com/libreboard/libreboard/issues/190

**Comment by Akanoa** [comment]
32 kb ok i got it thx

**Comment by singpolyma** [comment]
Yes, the UI definitely needs to say something by way of error, instead of just not working...

**Comment by mquandalle** [comment]
Closing in favour of #190.
