### ISSUE TITLE
New sandstorm grains fail to initialize, but existing boards work

### ISSUE THREAD

**Issue by xarinatan** [wekan/wekan#2200]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:
Yes, newest provided by sandstorm is 2.16.0~2019-02-03, however this issue has been around longer for me
* Wekan version: 2.16.0~2019-02-03 (but observed before)
* Operating System: Arch, Latest updates/kernel, but was also observed on Fedora 26/27/28.
* Deployment Method: Sandstorm
* Http frontend if any: sni-proxy on frontend webserver, but that should be invisible to sandstorm
* Node Version: 
* MongoDB Version:

**Problem description**:
![peek 2019-02-22 16-01](https://user-images.githubusercontent.com/1271027/53250685-3061a280-36bb-11e9-8c94-9b7f23fa213c.gif)
Peek is neat, I never knew about it, but I don't think I have to explain more than above hah.
I've attached the sandstorm grain as zip file. [Untitled Wekan board(2).zip](https://github.com/wekan/wekan/files/2894550/Untitled.Wekan.board.2.zip)
The log in the console in the gif is as follows
```
** Starting Meteor...

/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [127.0.0.1:4001] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:4001]
[..]
** HTTP-BRIDGE: App server exited with status code: 1
[repeat etc..]
```
- *Explain steps how to reproduce*
Create new wekan sandstorm grain, doesn't load, console shows mongo failed to initialize.

I've had this problem for a long time, on my older Fedora server and my newer Arch-based server. The only thing I can think of that they have in common is that they're both running in a VM on a hypervisor (KVM, also two different reinstalls, also Fedora and Arch), both of which used BTRFS on the host to store the .raw image files, and BTRFS inside the VM. I know that CoW on CoW could cause some issues, but afaik that's only performance issues and not data corruption or alike..
I also haven't tried running Wekan on Docker, I may try that soon as I have a very big (100mb+) board which takes some time to load on the same sandstorm server, that board however does work fine after loading, it's purely the new grains that are having issues. 
I've also rebooted the system since, which made no impact either.
Could anyone help?

**Comment by xet7** [comment]
Sorry, I'm not familiar with running Sandstorm on Fedora and Arch. My Sandstorm installs are usually on Ubuntu 18.04 64bit, and I have not had problems creating new Wekan boards. I recommend downloading your grains, installing Ubuntu 18.04 VM, and uploading grains.

**Comment by xarinatan** [comment]
I will try and get in touch with the Sandstorm developers to see if they can shed any light on the issue.

**Comment by xet7** [comment]
Sure, you can add Sandstorm issue, if you have not yet done so:
https://github.com/sandstorm-io/sandstorm/issues

**Comment by xet7** [comment]
Moved to https://github.com/sandstorm-io/sandstorm/issues/3125
