### ISSUE TITLE
Updated logo

### ISSUE THREAD

**Issue by MilovanovM** [wekan/wekan#2201]
## Logo doesn't look nice 

**Problem description**:
The Wekan's logo doesn't look polished. I mean, the "true-way" rounded corners can't be done by "Rounded Corners" tool in an image editing app. To make them smooth you should tune up the curve by Bezier tool.

Please see the source and the SVG version of the logo here [wekan-logo-1_2.zip](https://github.com/wekan/wekan/files/2898367/wekan-logo-1_2.zip)

You can see the difference here 
<img width="999" alt="wekan_logo_compare" src="https://user-images.githubusercontent.com/1742065/53304910-e380f600-388b-11e9-9977-5f3aa1d56922.png">

Another item to discuss it's the "grey shadow". Please consider removing it, it looks outdated. I haven't seen such shadows for a while.

The difference after removing the shadow: 
<img width="882" alt="logo_compared_no_shadow" src="https://user-images.githubusercontent.com/1742065/53304979-acf7ab00-388c-11e9-8b79-f1fb25465a5c.png">

Thanks,
M

**Comment by xet7** [comment]
@MilovanovM 

Please make new version of logo where grey shadow is removed, and add .zip file of .ai and .svg to comment of this issue by attaching files directly to issue, without using Dropbox. Thanks a lot !

**Comment by MilovanovM** [comment]
@xet7 thanks for the remarks, fixed

**Comment by xet7** [comment]
@MilovanovM 

wekan-1_2.ai is missing from .zip file, please add it.

**Comment by MilovanovM** [comment]
The source file is the same file, just hide the shadow in layers

**Comment by Chralf** [comment]
I have changed the colors to WeKan "blue" that is used in application as default. 

<img width="872" alt="bild" src="https://user-images.githubusercontent.com/126474697/223084044-08184cd2-9d52-41fc-8d44-7dde8730e5f1.png">

[wekan-1_3.ai.zip](https://github.com/wekan/wekan/files/10897032/wekan-1_3.ai.zip)

**Comment by Chralf** [comment]
This is without grey shadow (agree on outdated)

<img width="884" alt="bild" src="https://user-images.githubusercontent.com/126474697/223084443-299e9ed3-bea7-40d9-82e3-08e1f9e1279a.png">

[wekan-1_4.ai.zip](https://github.com/wekan/wekan/files/10897049/wekan-1_4.ai.zip)

**Comment by Chralf** [comment]
Here is my suggestion to simplify the logo

<img width="588" alt="bild" src="https://user-images.githubusercontent.com/126474697/223431584-e8cbace8-fe3b-40e2-bc02-38c6a12516f3.png">

[wekan-logo-ca.svg.zip](https://github.com/wekan/wekan/files/10909661/wekan-logo-ca.svg.zip)

The kanban icon is a free icon from https://icons.getbootstrap.com/ - They all are Open Source

**Comment by Chralf** [comment]
If you have the icon before text

<img width="708" alt="bild" src="https://user-images.githubusercontent.com/126474697/223432151-d9af6bab-1d75-4e9e-9ca0-3da9d10b9e95.png">

**Comment by xet7** [comment]
@Chralf

No. Logo can not be changed.

I have [this paid official trademark at Finland](https://www.tmdn.org/tmview/#/tmview/detail/FI50202100052006A) for:

1) This exact logo:

<img src="https://wekan.github.io/wekan-logo.svg" width="60%" alt="Wekan logo" />

2) Name written as `WeKan`, where both W and K are big letter.

Also, to that simplified version you have included icon that is too similar to icon trademarked by Trello. I do not have trademark of Trello logo.

**Comment by ocdtrekkie** [comment]
Not sure about Finnish trademark law, but you can probably safely use just the wordmark without the background in places you want a simplified logo, but I agree adding that little square icon would make it dangerously close to Trello's own trademark.
