### ISSUE TITLE
[Documentation] Sandstorm:  Email Configuration

### ISSUE THREAD

**Issue by sonaro** [wekan/wekan#2205]
Hello,

I'm not sure if this is a functionality issue or a documentation issue.  I have not been able to find how to configure email support for Wekan running inside Sandstorm.  Can someone provide guidance? 
 Email is working properly from Sandstorm manager.

Running Wekan version "2.16.0~2019-02-03"

Thanks!

**Comment by xet7** [comment]
Moved to #2208
