### ISSUE TITLE
Error on click on "Sign in with Oidc" Button

### ISSUE THREAD

**Issue by guillaumebdx** [wekan/wekan#2206]
## Issue

**Server Setup Information**:

* Wekan version: 2.25.0
* Deployment Method : Docker
* Node Version: 8.15.0

Hello,
I have an error when I try to connect with openId.

docker-compose.yml
```
      - OAUTH2_ENABLED=true
      - OAUTH2_CLIENT_ID=trustelem.oidc.abcdefghijkl
      - OAUTH2_SECRET=abcdefghijkl8484
      - OAUTH2_SERVER_URL=https://mycompany.trustelem.com/app/123456
      - OAUTH2_AUTH_ENDPOINT=/auth
      - OAUTH2_USERINFO_ENDPOINT=/userinfo
      - OAUTH2_TOKEN_ENDPOINT=/token
```

My identity provider give me that 

> ClientID
> trustelem.oidc.abcdefghijkl
> ClientSecret
> abcdefghijkl8484
> Issuer
> https://mycompany.trustelem.com/app/123456
> URL de Metadata, si nécessaire
> https://mycompany.trustelem.com/app/123456/.well-known/openid-configuration
> Endpoint d'autorisation
> https://mycompany.trustelem.com/app/123456/auth
> Endpoint de distribution des tokens
> https://mycompany.trustelem.com/app/123456/token
> Enpoint d'information sur l'utilisateur
> https://mycompany.trustelem.com/app/123456/userinfo

After my docker-compose up -d, when I click on the "Sign in with Oidc" button, I have the following error in my Chrome console :
```
Uncaught TypeError: a.join is not a function
    at Object.requestCredential (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:175)
    at e.isClient.e.loginWithOidc (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:177)
    at Object.click button (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:155)
    at a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:59
    at Function.e._withTemplateInstanceFunc (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:59)
    at f.View.<anonymous> (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:59)
    at a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:59
    at Object.f._withCurrentView (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:59)
    at f._DOMRange.<anonymous> (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:59)
    at HTMLButtonElement.<anonymous> (a33a650939723c9124573489e1dd465fe973fdc8.js?meteor_js_resource=true:59)
```

**Comment by guillaumebdx** [comment]
Important information :
I try with v 2.17 and openId works.
I think it's a side effect in newer versions

**Comment by t0k4rt** [comment]
Hi I still get this issue, is it normal ?
I installed Wekan through docker on version 2.75 and still having this issue.

**Comment by xet7** [comment]
@t0k4rt 

I did originally fix this at https://github.com/wekan/wekan/commit/05351c0ac100dc481f8eb6430a871f6e6d015cf0 at 27 Feb, but this bug came again after changes at #2412 and https://github.com/wekan/wekan/commit/634df8f6f26a7a7a2df6f87a705d322d88638425 and https://github.com/wekan/wekan/pull/2427 . Those changed were made by @DominikPf and me. This bug is with Wekan Docker latest tag, and not in released version of v2.75.

If you want to use release v2.75, please use Docker version tag in docker-compose.yml:
```
image: quay.io/wekan/wekan:v2.75
```

Screenshot of current bug in devel latest tag:


![bug-a-join-not-a-function](https://user-images.githubusercontent.com/15545/58346281-2a6a9180-7e63-11e9-823b-3ff8723bc64f.png)

**Comment by xet7** [comment]
@t0k4rt

To change your Wekan to v2.75, please do the following in same directory where is your docker-compose.yml:
```
docker-compose stop
docker rm wekan-app
```
Then change your docker-compose.yml to have image version tag:
```
image: quay.io/wekan/wekan:v2.75
```
Then do:
```
docker-compose start
```
or alternatively:
```
docker-compose up -d
```

**Comment by xet7** [comment]
@DominikPf

When I build newest Wekan Docker version from source, and tried OAuth2 login with Auth0, I did get login details like username etc from Auth0, but also got this error, and login did not work:

{"line":"431","file":"oauth.js","message":"Error in OAuth Server: Cannot use 'in' operator to search for '[]' in null","time":{"$date":1558721849843},"level":"warn"}
Exception while invoking method 'login' { stack: 'TypeError: Cannot use \'in\' operator to search for \'[]\' in null\n    at packages/underscore.js:894:15\n    at Array.forEach (<anonymous>)\n    at _.each._.forEach (packages/underscore.js:139:11)\n    at Function._.pick (packages/underscore.js:893:5)\n    at Object.handleOauthRequest (packages/wekan-oidc.js:48:20)\n    at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)\n    at middleware (packages/oauth.js:203:5)\n    at packages/oauth.js:176:5',

Docker version can be build from source by cloning Wekan repo, uncommenting these lines:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L132-L142
and running:
```
docker-compose up -d --build
```

**Comment by xet7** [comment]
Hmm, I need to test again, I have typos in my docker-compose.yml. Just a moment.

**Comment by xet7** [comment]
Latest Wekan code still works for me when I build from source. Maybe I just have not set all the same environment variables with Docker. Or alternatively, this is the same first admin user issue as mentioned at https://github.com/wekan/wekan/issues/2412#issuecomment-495750008 . I think I'll just include all current code to next Wekan release.

**Comment by t0k4rt** [comment]
Dear Lauri, 
Thanks for your response, I followed these instruction and created the first admin user before enabling OAUTH2.
I'm also already using v2.75 image but still getting this bug.
Any ideas ?
Thanks for your guidance !

**Comment by DominikPf** [comment]
Hi @t0k4rt v2.75 is broken for OAuth2 & OIDC.

You must build your own Wekan from Source or wait for the next release.

**Comment by t0k4rt** [comment]
Thanks ! I'll do that

**Comment by h4wkmoon** [comment]
same issue with current "master" docker image. (rocketchat provider)
