### ISSUE TITLE
Feature Request: When using OIDC login, hide password login and language selection.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2212]
Related #1874

**Comment by gil0109** [comment]
Any update on this?  It would be nice to also change Login with OIDC to just Login or SSO Login.

**Comment by xet7** [comment]
@gil0109 

If this is urgent for someone, someone can pay 300 euro to me so I will implement this:
https://wekan.team/commercial-support/

**Comment by gil0109** [comment]
Not sure if I have the budget but this is great info to know.  I will see if its a possibility on my end.  Thanks.

**Comment by xet7** [comment]
These now exists:

Snap hide password login:
```
sudo snap set wekan password-login-enabled='false'
```
Snap show password login:
```
sudo snap unset wekan password-login-enabled
```
Docker hide password login:
```
export PASSWORD_LOGIN_ENABLED=false
```
