### ISSUE TITLE
Filtering is broken since v2.29

### ISSUE THREAD

**Issue by bentiss** [wekan/wekan#2213]
## Filtering is broken since v2.29

**Server Setup Information**:
Local git tree with the wekan-dev setup

* Did you test in newest Wekan?: yep
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yep

* Wekan version: all since v2.29.

Bisected to 775476f97c1dda92e8

* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): None
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:

Since 775476f97c1dda92e8, filtering the cards is broken on my Firefox 64. On the following test board:
![screenshot from 2019-02-28 16-55-49](https://user-images.githubusercontent.com/2705518/53579823-95653e80-3b7a-11e9-9df0-4ba1fe8c4c93.png) with multiple lists, filtering by a label gives me the following: 
![screenshot from 2019-02-28 16-56-07](https://user-images.githubusercontent.com/2705518/53579879-b463d080-3b7a-11e9-8c5e-027b6e250720.png)

Note how the lists suddenly disappear.

CC-ing @andresmanelli , the author of 775476f97c1dda92e8

**Comment by xet7** [comment]
Related #2209

**Comment by bentiss** [comment]
I just realized this only happens in the Swimlane view

**Comment by andresmanelli** [comment]
@xet7 This should be fixed in https://github.com/andresmanelli/wekan/commit/49229e1723de14cdc66dc6480624bba426d35e36
