### ISSUE TITLE
Moving cards from one lane to another is no longer being logged

### ISSUE THREAD

**Issue by chotaire** [wekan/wekan#2215]
## Moving cards from one lane to another is no longer being logged

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: Any version >= 2.30 (did not test 2.27-2.29, worked in 2,26, still broken in 2.33)

* Operating System: CentOS7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): caddy with nginx reverse proxy
* Node Version: included in snap
* MongoDB Version: included in snap

**Problem description**:
- After upgrading to 2.30 or higher, moving a card from one lane to another would no longer log this in activities or via webhook. This issue exists with both already existing cards and newly created cards. Downgrading to 2.26 would fix this, but cards that were created with >=2.30 would need to be copied before they are also fixed.

**Comment by DukeW** [comment]
+1 Having the same issue. had a "Status update" webhook going to Rocket.Chat and it stopped working. Checked in RocketChat log, modifying check list still calls the hook, but moving cards no longer does.

**Comment by xet7** [comment]
Moved to #2226
