### ISSUE TITLE
Feature Request: Wider Sidebar (was: Custom HTML before Wekan iframe, and after Wekan iframe)

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2218]
For:
a) view after login
b) Optionally also for login screen, if Wekan login happens in Wekan iframe, and other menus do not show logged in state.

* customHTMLafterBodyStart: top and left menus and beginning of iframe
* customHTMLbeforeBodyEnd: `</iframe></body></html>`

Example mockup:

```
Logo     |                         | Username 
---------------------------------------------
Boards * | Wekan in iframe 
App 2    |
App 3    |
App 4    | 
---------------------------------------------
```
Beginnings of this exist at menu Admin Panel / Layout but it does save that HTML,
but making that HTML added correctly to before and after Wekan in iframe does not work yet.
If anyone can figure out why it does not work, help welcome.

**Comment by vjrj** [comment]
I was debugging this without success.

I was trying different ways to include the html settings but the jade version that wekan uses does not allow it. 

For instance to include a unescaped code like:
http://jade-lang.com/reference/code
```
p!= 'This code is' + ' <strong>not</strong> escaped!'
```
fails.

Related:
https://github.com/mquandalle/meteor-jade/issues/42
also:
https://github.com/pugjs/pug/issues/1595

Maybe this can be workaround using includes:
https://github.com/pugjs/pug/tree/0.33.0#a13

Disclaimer: Fist time playing with jade, so maybe my comment is not very accurate.

**Comment by MysterAitch** [comment]
I've just come across this issue when trying to debug why the custom HTML gets saved but never seems to get displayed.

I can see that the commit messages for 7f74e72cea111f6a776a12e6447847056af53fea and bd1df642fa2a3d5962ca1ceba8decd6516811361 indicate that it's an incomplete solution. 

Note that the issue description above refers to iframes (not found in the above commits), the commits add the setting content to the start/end of the `div#content` node, and the setting description on the admin panel refers to insertion after `<body>` and before `</body>` -- could it be that this issue describes slightly different functionality?

Assuming I've located the correct issue for this and while the feature is not yet fully implemented, perhaps a note can be added to the admin settings UI to indicate that changing it will have no effect?

**Comment by MysterAitch** [comment]
PS for those curious: My use case for wanting to insert HTML is to add some custom CSS to fix some niggles with clearly showing the edges of some elements - e.g.: 
```html
<div style="background-color: yellow; border: 4px solid red; height: 10em; width: 10em;">TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV TEST DIV</div>

<style>
.minicard {
    box-shadow: 3px 3px 2px rgba(100, 0, 0, 0.15);
}

.swimlane {
    background-color: #bbccdd;
}

.list {
    background-color: rgba(222, 222, 222, 0.8);
    margin-left: 0.2em;
}
</style>
```

![image](https://user-images.githubusercontent.com/1537214/62898687-fdd16200-bd4d-11e9-9674-24000271b84b.png)


![image](https://user-images.githubusercontent.com/1537214/62898631-dd090c80-bd4d-11e9-939c-27f48dd555eb.png)

**Comment by xet7** [comment]
Yes it's incomplete. I did not get working this feature, or Custom CSS, or Custom Javascript.

**Comment by xet7** [comment]
For Custom CSS, there is Themes feature at Wekan GitHub wiki.

**Comment by nickbe** [comment]
Who created the custom CSS feature in the first place?

**Comment by xet7** [comment]
@nickbe 

I created it originally, but because it is incomplete, I think it would be better that I would remove it.

I do add custom themes directly to Wekan code:
https://github.com/wekan/wekan/wiki/Custom-CSS-themes

**Comment by vjrj** [comment]
@xet7 I'm only use stylish to increase the width of activity column, but it's something that I cannot do for all our users (to use stylish). See:

![Captura de pantalla de 2020-01-06 10-15-52](https://user-images.githubusercontent.com/180085/71808344-de750180-306d-11ea-88c2-7850ae0a75fc.png)

The code:

```css
.board-sidebar {
	width: 548px;
	right: -548px;
}

.board-wrapper .board-canvas.is-sibling-sidebar-open {
	margin-right: 548px;
}
```
Is possible to do this small change in production? We use snap.

**Comment by xet7** [comment]
@vjrj 

Please comment on #2686 instead, full screen card would probably be even better.

**Comment by vjrj** [comment]
I only change the sidebar size to have a better general view of others users activity. The card width is ok for me.

**Comment by xet7** [comment]
@vjrj 

Ok, just a moment I try how it looks.

**Comment by vjrj** [comment]
@xet7 I added here some months ago:
https://userstyles.org/styles/177033/wekan-activities-wider

**Comment by xet7** [comment]
@vjrj 

With you change, at mobile smaller width some part at left is not visible. So I will not add it.

**Comment by vjrj** [comment]
@xet7 I'm only use this style in desktop but I can add some @media for small screen detection. Do you find useful to include it in the future?

**Comment by xet7** [comment]
@vjrj 

It is useful, if it's an improvement in some way.

**Comment by xet7** [comment]
@vjrj 

Problem is, if it's fixed size and when it's just wider, I don't know does it fit on screen properly. I would think current width and zoom to full width #2686 would be much better.

There already is isMiniScreen code for limited width.

**Comment by xet7** [comment]
@vjrj 

With current mobile width, all card elements fit on screen. They would not fit if card were wider. So I don't know is there any benefit.

**Comment by vjrj** [comment]
thanks indeed @xet7. I use this style thinking in desktop with stylish (but thinking in this just removed css/html functionality), but not thinking in include it the wekan code. So let me see the wekan code in detail and think better in some PR.

**Comment by xet7** [comment]
@vjrj 

Board sidebar stylus/css is here:
https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebar.styl#L174-L176

**Comment by nickbe** [comment]
Does changing the files mentioned in the wiki require to rebuild wekan?

**Comment by xet7** [comment]
@nickbe 

If you need any new theme, or other CSS change, add a new issue with your CSS required, so I will add new theme to Wekan.

**Comment by xet7** [comment]
@nickbe 

So it means yes, and I don't recommend rebuilding Wekan from source for normal users, that are not developers. Building Wekan takes some time.

**Comment by nickbe** [comment]
Thanks for offering this. 
Is it enough to provide a plain css sheet after testing the modified settings in the browser's developer tools?

**Comment by vjrj** [comment]
@xet7 Just with

```diff
diff --git a/client/components/sidebar/sidebar.styl b/client/components/sidebar/sidebar.styl
index 740186b..c104727 100644
--- a/client/components/sidebar/sidebar.styl
+++ b/client/components/sidebar/sidebar.styl
@@ -109,7 +109,7 @@
     color: darken(white, 40%)
 
 .board-sidebar
-  width: 248px
+  width: 548px
   right: -@width
   transition: top .1s, right .1s, width .1s
```
Works well in desktop (wider): 

![Captura de pantalla de 2020-01-06 15-22-27](https://user-images.githubusercontent.com/180085/71823875-928b8200-3098-11ea-884f-2c9118554e1a.png)

and mobile (adjusted):

![Captura de pantalla de 2020-01-06 15-22-05](https://user-images.githubusercontent.com/180085/71823876-928b8200-3098-11ea-8e3e-406cb04fd74d.png)

with 448px also is an usable width IMHO, better than just 248px.

**Comment by xet7** [comment]
@nickbe 

Yes, plain CSS changes is enough, I will add them to Wekan.

**Comment by xet7** [comment]
Plain CSS changes are easy, it's usually fast to change some CSS textfiles, I can do that for free.

It's completely different when it's about developing some new feature that requires changes to many files, that requires many hours of my Commercial Support https://wekan.team/commercial-support/

**Comment by vjrj** [comment]
Thanks @xet7 for the commit!
