### ISSUE TITLE
Feature Request: Combine hamburger menus at right

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2219]
From @justinr1234

> Hey re: menu
> On a board you have the burger menu too right below the account icon.
Then you also have a small arrow pointing left that pulls out to the activity log and the member invite panel.
> The small arrow fly out menu confuses people they expect the burger menu to be for the board settings and member invite and are very confused. Do you have issues with changing this behavior?

## Thanks for asking! 

Please add screenshot mockups how menus could be combined. After feedback to them, PRs welcome.

### 1) Sandstorm menu

Sandstorm has it's own menu, that is common for all apps running Sandstorm platform.

![sandstorm-wekan1](https://user-images.githubusercontent.com/15545/53688157-1c1b4680-3d48-11e9-9f38-2988741687e2.png)

### 2) Some days ago xet7 added top bar from Standalone Wekan Admin Panel menu

Previously this top bar was hidden at Sandstorm, but I then added it back #2208.
I did hide duplicate username, but there is still duplicate avatar. At Sandstorm there should be avatar and name hidden, and only show one hamburger menu. This can be done using isSandstorm environment variable that is used in .jade and .js files.

![sandstorm-wekan2](https://user-images.githubusercontent.com/15545/53688166-39e8ab80-3d48-11e9-8bd4-abaf349456d5.png)

### 3) Wekan board settings menu

This has some same items as some of above.

![sandstorm-wekan3](https://user-images.githubusercontent.com/15545/53688201-edea3680-3d48-11e9-8f8d-e2d93d6394e2.png)

### 4) Wekan members and activities menu

`<` arrow is used to show and hide this menu.

![sandstorm-wekan5](https://user-images.githubusercontent.com/15545/53688207-1114e600-3d49-11e9-9300-1547ce437bed.png)

**Comment by justinr1234** [comment]
@xet7 I think we should combine the Wekan Members and Activities menu together with the Wekan Board Settings Menu

**Comment by xet7** [comment]
@justinr1234 

Would this be better?
- When clicking current hamburger menu button, Members and Activities would open
- Members and Activities sidebar would have at right top corner this Settings button https://fontawesome.com/icons/cog?style=solid
- When clicking on Settings button, Wekan Boards Settings menu would open

**Comment by xet7** [comment]
@justinr1234 

What do you think about this? I only changed icons:
- hamburger to cog = Settings
- arrow to hamburger = Sidebar

![board-menu-test1](https://user-images.githubusercontent.com/15545/53692737-b35eb900-3d9d-11e9-84c0-5d07a261a6ea.png)

**Comment by justinr1234** [comment]
I still prefer a combined menu. I believe having 2 menus for the board directly next to one another is highly confusing.

**Comment by xet7** [comment]
@justinr1234 

Ok, I combined menus this way, what do you think?

## 1) Hamburger menu opens sidebar

![wekan-menu1](https://user-images.githubusercontent.com/15545/53701182-23ebf100-3e03-11e9-9e45-24dbd5a01a94.png)

## 2) Cog icon opens Board Settings

![wekan-menu2](https://user-images.githubusercontent.com/15545/53701193-37975780-3e03-11e9-8c8a-2d4ad95ff71f.png)

**Comment by justinr1234** [comment]
@xet7 I like it!

**Comment by xet7** [comment]
Wekan v2.36 is now release, it includes this feature.
