### ISSUE TITLE
[Documentation] Step by step manual installation guide

### ISSUE THREAD

**Issue by Vertux** [wekan/wekan#2221]
I am badly missing a step by step manual installation guide (at least for e.g. Debian 9) - in the internet you can only find a few outdated guides, but none official one. I am not sure if you aware that packages or automatic scripts does not work on servers, which are managed by Plesk, which is very common. An unexperienced user can mess up the whole server by installing those packages and automatic scripts, because they expect a standard installation of operating system.
At the moment the only solution to install Wekan would be to use Docker, but even if Docker is very popular at the moment not everyone likes to use Docker in an produktion environment.

**Comment by xet7** [comment]
https://github.com/wekan/wekan-snap/wiki/Install

or

https://sandstorm.io/install

**Comment by Vertux** [comment]
Thank you @xet7 but that's what I have mentioned these packages/srcipts expect a "normal" OS environment, but a server managed by Plesk handles webpages by its own mechanisms, that's why you cannot simply install a **complex** web application with apt/snap - you have to do it by hand to have full control of the installation process, especially if you running a couple of application on your server.

**Comment by xet7** [comment]
@Vertux 

You can also install from source using rebuild-wekan.sh and start-wekan.sh scripts at https://github.com/wekan/wekan . I don't know what kind of package manager Plex has, does Plex have any app store similar to what Snap and Sandstorm have.

**Comment by xet7** [comment]
Moved to #2221

**Comment by Vertux** [comment]
@xet7 [Plesk](https://en.wikipedia.org/wiki/Plesk) is a very popular commercial application for webhosting and server managemnt, which sits on top of the server operating system. It has its own configuration and control files (especially for apache and nginx) and it uses a little different directory structure. On those systems, which are managed by Plesk you can install all kinds of regular packages e.g. Debian etc., but bundled, complex web applications. If you install those packages, the chance is very high, that you run into big trouble and may end with a non-functioning server.

I know, that I can install it from source, but that does not help either, because I could not find any information about e.g. database configuration/preperation and necessary systemd/cron task etc.
I am not a programmer so I do not want to did into the code to find out all these things to make Wekan work properly.

I hope I could make my position a little clearer.

**Comment by xet7** [comment]
@Vertux 

Source install would mess up your server that has non-standard locations, so I do not recommend that.

Docker Wekan can be installed easiest this way:
- Wekan current stable version v2.35 is mentioned at https://wekan.github.io
- 4000 is port exposed to localhost, you can change to other one
- [Nginx](https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config) or [Apache](https://github.com/wekan/wekan/wiki/Apache) proxy to localhost:4000
- [ROOT_URL examples](https://github.com/wekan/wekan/wiki/Settings), below https://boards.example.com Nginx or Apache URL proxies to localhost Docker port 4000
- there are also other settings [that are documented here](https://github.com/wekan/wekan/blob/devel/docker-compose.yml), below is only minimum required
- [Adding users](https://github.com/wekan/wekan/wiki/Adding-users)
```
docker run -d --restart=always --name wekan-db mongo:3.2.21

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=https://boards.example.com" -e "WITH_API=true" -p 4000:8080 quay.io/wekan/wekan:v2.35
```

**Comment by Vertux** [comment]
Thank you @xet7. I normally try to avoid Docker, because I am not very familliar with it, but I will give it a try.

**Comment by soohwa** [comment]
@Vertux Hello, maybe [this](https://github.com/soohwa/wekan-deb) can fit for you: a debian package.
* Be aware the target is for sysv-init operating systems (like devuan).
* There are instructions to build the package, so I think you can adapt it for your system
* And then you will have a simple single debian package for wekan server (nodejs + meteor application) and obviously you have to install mongodb separately.

**Comment by Vertux** [comment]
@soohwa thank you for the link, I will take a look.

**Comment by soohwa** [comment]
@Vertux Hello, I started this: https://soohwa.github.io/wekan-doc/

**Comment by sfahrenholz** [comment]
there is already an documentation repository
https://github.com/wekan/wekanhow

see #2243 and #2222

**Comment by xet7** [comment]
@soohwa @sfahrenholz 

I added you with write access to existing documentation repository https://github.com/wekan/wekanhow .
Please add documentation from other urls like soohwa's repos and Wekan GitHub wiki directly to new style of that wekanhow repo. Thanks!
