### ISSUE TITLE
Discuss: Wekan docs at GitHub wiki vs alternatives

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2222]
Alternatives:

a) Currently Wekan docs are at GitHub wiki, that is user editable for all logged in GitHub users. Wekan docs were originally moved from GitHub repo to GitHub wiki to make it easier for Wekan community to contribute to documentation. It has worked very well, and has not required additional server maintenance and updates. Is there any real benefit in changing this, and having different login?

b) Friend will change docs to Mozilla MDN style https://developer.mozilla.org that is powered by Kuma https://developer.mozilla.org/en-US/docs/MDN/Kuma , for making collaboration and contributing to documentation easier.

Other alternatives?

**Comment by saurabharch** [comment]
Actually all wiki pages are static website on GitHub they use Jekyll that is why GitHub support markdown for Jekyll require ruby gems and ruby programming language for core features changes and development I think we are in core of JavaScript and meteor developers are hard to manage this implementation but I found another which Gatsbyjs we all know Gatsby build on the top of React framework it support many features which we required for future implementation but in another side Jekyll is hard to implement and next js is also another static web page generator but it have lack of front end plugins as per knowledge but it is very impressive like Gatsbyjs in back end features implementation but Gatsbyjs have both support from back to front and it is SEO Friendly easy for developing new components and artifacts of wekan wiki pages and it’s Graphql ready framework and also support SSR HERE IS AN EXAMPLE https://github.com/howtographql/howtographql

**Comment by xet7** [comment]
I have not used those, it would be helpful if someone that knows those would make some example from Wekan wiki docs moved to some new system. And how to make it more user friendly.

**Comment by sfahrenholz** [comment]
I hope it is ok to reference another project.
Duplicati use readthedocs.io

an example is here: https://duplicati.readthedocs.io/en/latest/
the repository is there: https://github.com/kees-z/DuplicatiDocs/

**Comment by xet7** [comment]
Making news docs and website is already in progress. Please contribute by sending PRs.
https://github.com/wekan/wekanhow

**Comment by soohwa** [comment]
@sfahrenholz Hello, I started this: https://soohwa.github.io/wekan-doc/

**Comment by xet7** [comment]
@soohwa 

Cool, keep it coming :+1:

**Comment by sfahrenholz** [comment]
@xet7 did we make an own "wekandoc" repository? So we support his better...
example an fork from @soohwa 
my wekandoc-respository is currently not on github, but i have the sources

**Comment by xet7** [comment]
@sfahrenholz 

I did work also wekandoc, and invited you to there. So now there are these:
- https://github.com/wekan/wekan-doc
- https://github.com/wekan/wekanhow

Which one gets used, depends on contributors. More contributors welcome. I do need to concentrate to coding Wekan features and fixes.

**Comment by polyzen** [comment]
> Actually all wiki pages are static website on GitHub they use Jekyll that is why GitHub support markdown for Jekyll require ruby gems and ruby programming language

I'm pretty sure they still use a closed-source fork of [Gollum](https://github.com/gollum/gollum).

**Comment by xet7** [comment]
I think markdown works similarly with GitLab/Gogs/Caddy website etc, there's not much special in what software is running at server.

**Comment by xet7** [comment]
Welcome @jean to improving Wekan docs. I added you to wekanhow and wekan-doc repos, although I think wekanhow style looks better.

**Comment by xet7** [comment]
If current GitHub wiki could be improved enough, benefit would be that any GitHub user can improve it directly. Editing docs at GitHub repos requires a lot more knowledge about commits etc.

**Comment by sfahrenholz** [comment]
@xet7 thank you, i will be starting the first documentations soon.

**Comment by jean** [comment]
@xet7 thank you for the kind welcome :grinning:
