### ISSUE TITLE
Issue: Adding Labels to cards is not possible anymore (v2.36)

### ISSUE THREAD

**Issue by gichlord** [wekan/wekan#2223]
Hello!

Since today, adding labels to cards is not possible anymore. If i click the add button, the label will not get added to the card. On existing cards, where labels are added before, it is not possible to delete them.

Here is what i found in the syslog, when clicking "ADD" a label to a card. It will show this:

Mar  4 07:17:19 wekan wekan.wekan[98049]: Exception while invoking method '/cards/update' TypeError: Cannot read property 'title' of undefined
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at cardMove (models/cards.js:1301:21)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Object.<anonymous> (models/cards.js:1461:5)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at packages/matb33_collection-hooks.js:486:20
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Array.forEach (<anonymous>)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at packages/matb33_collection-hooks.js:485:11
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Array.forEach (<anonymous>)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at after (packages/matb33_collection-hooks.js:484:9)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at packages/check.js:128:16
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar  4 07:17:19 wekan wekan.wekan[98049]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41) 

Does anyone got a solution or an idea, how i can fix this problem?

Thanks

Gichlord

[Wekan-syslog.txt](https://github.com/wekan/wekan/files/2924771/Wekan-syslog.txt)

**Comment by xet7** [comment]
Thanks for info! I will try to fix this.
