### ISSUE TITLE
Exception while invoking method '/cards/update' TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by rblomme** [wekan/wekan#2224]
**Server Setup Information**:

* Wekan version: v2.36.0
* Node version: v8.15.1
* Operating System: Ubuntu 18.04.2 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* MongoDB Version: v3.2.22

**Problem description**:
When I move a card from list A to list B, the syslog file shows

`Mar  4 11:17:51 tw06v056 wekan.wekan[12437]: Exception while invoking method '/cards/update' TypeError: Cannot read property 'title' of undefined
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at cardMove (models/cards.js:1301:21)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Object.<anonymous> (models/cards.js:1461:5)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at packages/matb33_collection-hooks.js:486:20
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Array.forEach (<anonymous>)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at packages/matb33_collection-hooks.js:485:11
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Array.forEach (<anonymous>)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at after (packages/matb33_collection-hooks.js:484:9)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at packages/check.js:128:16
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar  4 11:17:51 tw06v056 wekan.wekan[12437]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
`
- *steps how to reproduce*
create a new board "test", create a list "A" and a list "B", create a new card "test" in list A;
move the card from list A to list B

- *In webbrowser, what does show Right Click / Inspect / Console ? *
update failed: Internal server error undefined 

- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*

`2019-03-04T10:17:51Z wekan.wekan[12437]:     at Array.forEach (<anonymous>)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at after (packages/matb33_collection-hooks.js:484:9)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at packages/check.js:128:16
2019-03-04T10:17:51Z wekan.wekan[12437]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
2019-03-04T10:17:51Z wekan.wekan[12437]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
`

**Comment by xet7** [comment]
Upgrade to Wekan v2.37 with `sudo snap refresh`

**Comment by rblomme** [comment]
after upgrade, still the same problem:

`Mar  4 12:07:18 tw06v056 wekan.wekan[14829]: Exception while invoking method '/cards/update' TypeError: Cannot read property 'title' of undefined
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at cardMove (models/cards.js:1301:21)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Object.<anonymous> (models/cards.js:1461:5)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at packages/matb33_collection-hooks.js:486:20
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Array.forEach (<anonymous>)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at packages/matb33_collection-hooks.js:485:11
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Array.forEach (<anonymous>)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at after (packages/matb33_collection-hooks.js:484:9)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at packages/check.js:128:16
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar  4 12:07:18 tw06v056 wekan.wekan[14829]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
`

**Comment by xet7** [comment]
I'll try to reproduce this, is there same error on my Wekan install.

**Comment by xet7** [comment]
@andresmanelli 

Templates board disappeared from newest Wekan, that is built from edge branch.

**Comment by xet7** [comment]
Related #2209

**Comment by xet7** [comment]
There seems to be one template board at MongoDB database, and I tried to add my user to that board, but when I click Templates, Wekan goes to url `/b` and shows texts `Board not found`.

**Comment by rjevnikar** [comment]
I"m getting the same/a similar error with v2.37 using docker.
I unfortunately, can't determine what end users are doing to get this error.

When I move a card between lists, I get the following error in the console in Chrome 
`update failed: Internal server error undefined`
