### ISSUE TITLE
Bugs: 1) Webhook Not translated text in german. 2) Board activity lost notification on card move.

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2226]
**Server Setup Information**:

* Did you test in newest Wekan?: no
* Wekan version: 2.36 (tomorrow i will test the new version)
* Operating System: Ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: snap-version
* MongoDB Version: snap-version

**Problem description**:
- The Webhook text
> checked __checklistItem__ of checklist __checklist__ at card __card__ at list __list__ at swimlane __swimlane__ at board __board__

is not translated in german
> {USER} hakte {ITEMTEXT} von der Checkliste "{CHECKLIST}" der Karte "{CARDTITLE}" auf der Liste ```__list__``` bei Swimlane ```__swimlane__``` an Board "{AWESOMEBOARDNAME}" ab

List of other non translated text
* moved card __card__ from list __oldList__ at swimlane __oldSwimlane__ at board __oldBoard__ to list __list__ at swimlane __swimlane__ at board __board__ (__oldBoard__ are not replaced in this case)

List of not replaced values
* checked __checklistItem__ of checklist __checklist__ at card __card__ at list __list__ at swimlane __swimlane__ at board __board__ (list and swimlane not replaced)
* {USER} act-addedLabel

**Comment by xet7** [comment]
Moved to here from #2232

NOTE: Wekan has had some major changes to webhooks, Wekan UI etc recently, please wait, fixing bugs is in progress.

From @cyberfarer 

I added a new admin, so I imagine it is related, but I am seeing the following log:

`Mar 05 14:02:02 pydio wekan.wekan[13107]: Exception while invoking method '/cards/update' TypeError: Cannot read property 'title' of undefined
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at cardMove (models/cards.js:1301:21)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object.<anonymous> (models/cards.js:1461:5)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at packages/matb33_collection-hooks.js:486:20
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Array.forEach (<anonymous>)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at packages/matb33_collection-hooks.js:485:11
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Array.forEach (<anonymous>)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at after (packages/matb33_collection-hooks.js:484:9)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at packages/check.js:128:16
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
`

**Comment by justinr1234** [comment]
<img width="231" alt="Screen Shot 2019-03-11 at 11 56 04 AM" src="https://user-images.githubusercontent.com/7017500/54141951-ac1a5980-43f4-11e9-9e6f-76edca7b98b2.png">

@xet7 Looks like the `swimlaneId` is the issue. It is set to the same thing as the `boardId`. The id given for `swimlaneId` does exist in the `Swimlanes` collection and therefore the error on this line when it tries to find it: https://github.com/wekan/wekan/blob/devel/models/cards.js#L1301

The question is why did `swimlaneId` get set to the same as `boardId`?

**Comment by justinr1234** [comment]
@xet7 It resets it incorrectly everytime the card is moved

**Comment by xet7** [comment]
@justinr1234 

I think there is already fix for swimlaneId bug in Wekan v2.44 that is currently being built.

**Comment by andresmanelli** [comment]
> <img alt="Screen Shot 2019-03-11 at 11 56 04 AM" width="231" src="https://user-images.githubusercontent.com/7017500/54141951-ac1a5980-43f4-11e9-9e6f-76edca7b98b2.png">
> 
> @xet7 Looks like the `swimlaneId` is the issue. It is set to the same thing as the `boardId`. The id given for `swimlaneId` does exist in the `Swimlanes` collection and therefore the error on this line when it tries to find it: https://github.com/wekan/wekan/blob/devel/models/cards.js#L1301
> 
> The question is why did `swimlaneId` get set to the same as `boardId`?

c.f. https://github.com/wekan/wekan/issues/2238#issuecomment-470972136

**Comment by justinr1234** [comment]
@xet7 fixed
