### ISSUE TITLE
Request for help: Moving cards on "My Boards" page and adding colors

### ISSUE THREAD

**Issue by mikey604** [wekan/wekan#2231]
Requesting help with the following issues:
- Moving boards around on the "My Boards" page for better organization.
- Adding more than 6 colors to choose from when creating a new board.

**Comment by xet7** [comment]
> Moving boards around on the "My Boards" page for better organization.

Moved to #641

> Adding more than 6 colors to choose from when creating a new board.

Moved to #2156
