### ISSUE TITLE
Lost notifications for a card move

### ISSUE THREAD

**Issue by cyberfarer** [wekan/wekan#2232]
I added a new admin, so I imagine it is related, but I am seeing the following log:

`Mar 05 14:02:02 pydio wekan.wekan[13107]: Exception while invoking method '/cards/update' TypeError: Cannot read property 'title' of undefined
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at cardMove (models/cards.js:1301:21)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object.<anonymous> (models/cards.js:1461:5)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at packages/matb33_collection-hooks.js:486:20
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Array.forEach (<anonymous>)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at packages/matb33_collection-hooks.js:485:11
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Array.forEach (<anonymous>)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at after (packages/matb33_collection-hooks.js:484:9)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:505:5)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:355:34)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at packages/check.js:128:16
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 05 14:02:02 pydio wekan.wekan[13107]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
`

Any ideas where to begin looking? 

Thanks.

**Comment by xet7** [comment]
Moved to #2226
