### ISSUE TITLE
Bug: Unable to view PDF file attached to a card

### ISSUE THREAD

**Issue by justinr1234** [wekan/wekan#2236]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 2.37.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux Debian 9
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Source to Meteor Galaxy running Mongo Atlas
* MongoDB Version: 3.4

**Problem description**:
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.* Resource interpreted as Document but transferred with MIME type application/octet-stream

1) Attach a PDF file to a card
2) Try to view the PDF file in the browser by clicking it
3) It spins forever not displaying anything

**Comment by xet7** [comment]
Moved to #1318
