### ISSUE TITLE
Bug: Wekan v2.43 All boards page keeps changing order of boards

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2241]
In Wekan [v2.43](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v243-2019-03-08-wekan-release) I did:
- [Hide Subtask boards from All Boards](https://github.com/wekan/wekan/blob/devel/client/components/boards/boardsList.js#L23-L32) (in progress code)
- [Order All Boards by Starred, Color, Title and Description](https://github.com/wekan/wekan/blob/devel/client/components/boards/boardsList.js#L23-L32) (final code).

Problem is, All Board page keeps reordering boards all the time, making Wekan a game can correct board be clicked to open that board.

@bentiss 

Do you have ideas how this could be prevented?

I will also try to figure this out myself too.

**Comment by xet7** [comment]
This can be tested with snap beta:
```
sudo snap refresh beta --beta --amend
```
Changing back to stable Wekan version:
```
sudo snap refresh wekan --stable --amend
```

**Comment by sfahrenholz** [comment]
Good evening,

i have testing the v2.43 and see some problems
(1) the first creating i cant see the subtask
(2) to "jump" into the subtask-board is only to link one card. a entry in the menu are better
(3) i missing a description for the subtask in the wiki (how it works and more)

![ribcu-9cuy4](https://user-images.githubusercontent.com/6977657/54058822-4dd45780-41f7-11e9-8291-36c674ac56b7.gif)

**Comment by bentiss** [comment]
> Problem is, All Board page keeps reordering boards all the time, making Wekan a game can correct board be clicked to open that board.

@xet7: well, it's stable on my side. The boards are reshuffling if we do change their colors, but they reach a stable point where they do not move.

I would personally not order them by color but only keep the star and title ordering. The colors are a good way of visually remembering which card is which, but ordering the boards by color makes this point moot IMO.

@sfahrenholz : indeed, it seems like a new bug. It might be related to @xet7 change, but not entirely sure. I can have a look on Monday.

**Comment by bentiss** [comment]
@sfahrenholz Could you open a new bug with your screenshot?

I bisected the bug to 3c49e2d0ede and I am not sure how to solve this. It looks like the cards are still created, but they are not populated in the answer.

**Comment by bentiss** [comment]
@xet7 regarding the endless sorting, maybe you are hitting https://docs.meteor.com/api/collections.html#sortspecifiers:
> The last form will only work if your JavaScript implementation preserves the order of keys in objects. Most do, most of the time, but it’s up to you to be sure.

So *maybe*, using the array notation `[['stars', 'desc'], 'color', 'title', 'description']` will solve it

**Comment by xet7** [comment]
@bentiss 

I tried this at wekan/client/components/boards/boardsList.js line 23. On new Wekan board it seems to work, but on old Wekan board order of boards keeps changing. I don't know why.
```
  boards() {
    return Boards.find({
      archived: false,
      'members.userId': Meteor.userId(),
      type: 'board',
      subtasksDefaultListId: null,
    }, { sort: [['stars', 'desc'], ['color', 'asc'], ['title', 'asc'], ['description', 'asc']] });
  },
```

**Comment by bentiss** [comment]
@xet7 

I am not sure I understand the problem fully. I do realized today that the order might change if some boards have the same title and description. But I have the impression that you are seeing the boards changing and being sorted randomly?

For fixing the same title and description, and I think we could simply also order by creation date or `_id` to have a reliable sort.

**Comment by xet7** [comment]
@bentiss 

Yes, boards are changing and being sorted randomly. I'll try to add `_id`.

**Comment by sfahrenholz** [comment]
@bentiss i created an own bug report for this.
