### ISSUE TITLE
Fix your documentation!

### ISSUE THREAD

**Issue by GiganteX** [wekan/wekan#2243]
Hi!

I've been trying to run wekan in docker for like two hours now without any success,
util I figured out that wekan's default port is 8080 and not 80!

First of all, the documentation for running it in docker is hard to find. The pages on Docker Hub gives no info. Ususally on Docker Hub you're supposed to show a "docker run" example and explaining which options are available, how to connect to db, which folders you can mount in a separate volume, things like that. You have nothing like that in there.

Fine, after googling I found this in your wiki:
https://github.com/wekan/wekan/wiki/Docker

"docker run -d --restart=always --name wekan-db mongo:3.2.20
docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://192.168.1.200:8080" -p 8080:80 quay.io/wekan/wekan"

I've been trying all kinds of variations of that. I've been trying to fix the DB connection etc. But it didn't help much, could never get into the wekan UI.... as external port 8080 is mapped to internal 80 which goes nowhere!

I've been trying many other examples from all kinds of webpages I found, and I got nowhere until I did a docker ps and noticed for my wekan container: "PORTS 8080/tcp, 0.0.0.0:88->80/tcp" 

What, port 8080 ?? I've been trying to connect on port 88 which I mapped to 80... so useless!

Yeah I know, it's opensource and I have no right to be upset... but I could've spent these hours on other things so I am a bit miffed anyway. Well the good news is that it all works now when I'm using the right port. I just think you can improve on the documentation...

**Comment by xet7** [comment]
Making new docs and website is already in progress. Please contribute by sending PRs.
https://github.com/wekan/wekanhow
