### ISSUE TITLE
Change: Should not swallow e-mail errors on email actions

### ISSUE THREAD

**Issue by justinr1234** [wekan/wekan#2246]
https://github.com/wekan/wekan/blob/1b445ad789a41d97b7cf4e16af35f52ae0be694b/server/rulesHelper.js#L80

Should put this to the error log on the server for debugging purposes.

**Comment by xet7** [comment]
@justinr1234 

There is existing environment variable that can be set `DEBUG=true` so could you add some PR for this?

**Comment by xet7** [comment]
Related bug https://github.com/wekan/wekan-snap/issues/78

**Comment by justinr1234** [comment]
@xet7 I don't think this should be a `DEBUG` thing. It should be putting out an error at runtime if it can't successfully send e-mail.
