### ISSUE TITLE
Can set board's subtask board as itself

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2247]
Wekan v2.44 from Docker image

With subtask boards being hidden on All Boards, you can easily lose easy access to a board if you set the default subtask board as itself.
Off the top of my head there are two options to fix this:
A) Have a tab on All Boards to show subtask-boards
B) Don't allow a board to select itself as the subtask board

Neither option is great - but I think option B may limit how users use the board, so I might be inclined to go with option A.

**Comment by rjevnikar** [comment]
This is seems like it is the same as @2249, but maybe more specific - it probably should be incorporated into that discussion and closed

**Comment by xet7** [comment]
Subtask board should not be possible to set to itself.

@andresmanelli Can you fix this?

**Comment by xxpqxx** [comment]
@xet7 Create a Subtask in same board is very useful. In my workflow i use one board per project.

**Comment by xet7** [comment]
@rjevnikar 

> With subtask boards being hidden on All Boards, you can easily lose easy access to a board if you set the default subtask board as itself.

Can you include recorded gif animation about how this bug happends and makes something disappear? Is there still some bug?

@xxpqxx 

> Create a Subtask in same board is very useful. In my workflow i use one board per project.

Can you include recorded gif animation about your workflow? Does it work, or is there some bug?

**Comment by andresmanelli** [comment]
This should be fixed in the same way as the circular references for parent
cards.

I will take a look

Le mar. 12 mars 2019 à 23:58, Lauri Ojansivu <notifications@github.com> a
écrit :

**Comment by rjevnikar** [comment]
This is only really a bug if subtask boards are hidden, otherwise, I haven't noticed a problem.

**Comment by andresmanelli** [comment]
Why not just show boards that has the setting `parentId === _id` and hide the rest of subtasks boards?

**Comment by rjevnikar** [comment]
> Why not just show boards that has the setting `subtasksBoardId === _id` and hide the rest of subtasks boards?

I like that workaround, Additionally, I'd put the rest of the subtask boards in a tab (like templates).

**Comment by xet7** [comment]
Moved to #641
