### ISSUE TITLE
Wekan card loading animation never goes away

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2250]
When I do zoom out beyond normal %100 in a page to see a much better view of a page, I see those loading animations at the bottoms of lanes. Some stop and some never stop. It is a bit distracting :(

The issue goes away after I zoom in and scroll to the bottom of a lane. Infact the loading animation never goes away unless I zoom in enough that scrolling down is possible , then I scroll down to the lane and it reloads I guess and stops that loading thing. 

In none of the cases is, it actually needed to load anything because the page already has all the cards, so I am not sure why it is doing it.

It seems to  be doing this with the longest lanes (comparitively)

See the image

https://i.imgur.com/FsJtijy.png

**Comment by xet7** [comment]
Wekan only loads to webbrowser those cards that are visible in 100% view. When scrolling cards to not-loaded area, Wekan loads some new cards.  This makes possible loading boards that have thousands of cards. Zoom out is not implemented yet, I would think it would slow down webbrowser.

@bentiss Do you know is it possible to implement zoom out?

**Comment by xet7** [comment]
@gerroon 

What is your use case for this?

a) Do you have large monitor and would like overview of project?
b) Would like to print Wekan board?

**Comment by xet7** [comment]
c) export as PDF / CSV ?

**Comment by gerroon** [comment]
Well my use case is to see how long/tall a particular lane is compared to the others. Because it is impossible to know how far it goes down by looking at the scroll bar

**Comment by gerroon** [comment]
I am not trying to export anything, I am just trying to get a big picture. But I see your point, maybe you thought that I was trying to get a screenshot or something, which is not a bad idea in general.

**Comment by xet7** [comment]
@gerroon 

In Standalone Wekan, click on right top corner your username that shows Member settings => Change Settings => Show cards count if list contains more than => change to number 1 and click Apply. This shows count of cards. Is it enough for you for this use case?

**Comment by gerroon** [comment]
Thanks, that is a nice tip and I will try it, but that is not what  I am trying to solve here. I just do not understand why some lanes have constant "loading" animations at the bottom, even though no more cards to load.

**Comment by xet7** [comment]
@gerroon 

Maybe because you did zoom? I think zoom bugs are not fixed yet.

**Comment by gerroon** [comment]
Ok, so there are zoom bugs? I was not awarre of them I think.

**Comment by xet7** [comment]
@gerroon 

Well, according to you there is, because you created this issue. You told that zooming makes card load animation show all the time. I have not tested this yet.

**Comment by bentiss** [comment]
hmm, indeed that's an infinite scroll issue, and so I guess I am the one that will have to fix it.

What happens is when you zoom out, the column might be long enough to show all of the currently loaded cards, and the animation, which hides the scrollbar. And this is a corner case that I thought have fixed but apparently not.

**Comment by xet7** [comment]
@gerroon 

I am unable to duplicate this bug. Please add recorded animation git about how you get this showing.

**Comment by gerroon** [comment]
See the screenshot. I am on Linux atm, and i do not know any good, gif app. I also do not want to reveal personal information. I think the screenshot below should demonstrarte the issue hopefully.

![Screenshot_wekan](https://user-images.githubusercontent.com/8519469/54243704-6dce8880-4521-11e9-87ec-745cc8b5a455.png)

**Comment by nickian** [comment]
I am having this same issue. I have a large, 4k monitor. When my browser window height is around 1600, I can see 30 cards (with a single line title) and the loading animation below. There's no scrollbar/overflow because all of the cards are in view. Therefore, in order to load more cards on that list I have to resize my browser window to force a scrollbar to show up.

I'm not sure if there's a way to initiate loading more without scrolling. Perhaps you could set the number of default cards visible based on detecting the `window.innerHeight` of the page? This is kind of an annoying bug when working with large boards on high resolution monitors.

**Comment by gerroon** [comment]
@nickian

I agree, it is super distracting  :( I actually glad that this is a confirmed bug now.

**Comment by gerroon** [comment]
THis version got even worse for me :( 
- No scrolling now

- More lanes showihn infinite loop

See the image

Wekan Version	v2.56.0
Node version	v8.15.1

**Comment by xet7** [comment]
@bentiss 

It seems I need to revert your change because it did bring new bugs.

**Comment by xet7** [comment]
@gerroon 

I can not duplicate your issues, so I added zoom fixes back.

Scrollbars is visible when cards do not fit on screen, like when there is many swimlanes etc.

**Comment by gerroon** [comment]
@xet7

Can you tell me how I can revert back to an earlier version using Snap?  I was not able to test your revert since you did not release it at least snap never refreshed it

**Comment by gerroon** [comment]
Ok a new info, i think missng scroll bars etc might be related to browser cache. It seems to me that browser cache is not updated properly with the new most recent fixes. 


I can see my pages properly if I open the site in a browser that I never used for Wekan before.

**Comment by xet7** [comment]
@gerroon 

What CPU you have? And how much RAM ?

**Comment by gerroon** [comment]
Please bear in mind that I did not have any of these issues prior to fixes mentioned above.


The systemn has 8gb ram

```
lscpu
Architecture:        x86_64
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
Model name:          Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
CPU MHz:             1197.258
CPU max MHz:         3300.0000
CPU min MHz:         1200.0000

```

**Comment by xet7** [comment]
Yeah sure, sorry that Wekan uses too much Javascript, drag drop etc that not all browsers support. Maybe it would be better to remove all Javascript from frontend, including drag-drop, etc, and just use HTML+CSS+forms with POST at frontend. So that Wekan would be usable on lynx and elinks.

**Comment by xet7** [comment]
Wekan is only tested with newest Firefox, Chrome/Chromium and Edge.

**Comment by gerroon** [comment]
Yes 
But I do not understand the logic of javascript. This was anon issue just a couple weeks ago. I am jiust not getting this sudden influx of broken stuiff and high cpu use. It is not like you just implemented Javascript, it was there for a long time.

What I am saying is that all this stuff happened after the supposed fix. I am sorry that you cant reproduce it but I am able to produce this in 4 different borwsers with carying degrees. 

Also I am using Chromium latest and I have that high cpu use. My boards are not super big but I have some lanes that ahev up to 20+ cards, with not much date related, mostly simple text fields.

**Comment by xet7** [comment]
I would presume newest Firefox uses less CPU than Chromium.

You can use docker-compose.yml at https://github.com/wekan/wekan where Wekan version can be specified with version tag.

Anyway, old versions of Wekan are not supported, and those should not be used on Internet-accessible servers, because of outdated software versions.

**Comment by gerroon** [comment]
I am sorry but I feel like I am not expressing myself here well. 

None of the issues I have been trying to express here were there just a week ago or so. Now I am flooded with these, and you are telling me that newest firefox uses less cpu, i feel like our communication is broken here :( I do nto even understand the recommended response. Nothing in my usage, system, browser etc changed, I did not even add a single line of new card or board to my Wekan boards. Now suddenly I have these issues.

**Comment by xet7** [comment]
@gerroon 

I don't still know what is the actual bug. I tried Epiphany, and it did show that loading bug. But I do not see it in Chrome. Also, it's possible that there is new Chromium bug. I just don't know.

**Comment by xet7** [comment]
The new infinite scroll feature https://github.com/wekan/wekan/pull/2287 works very well in Wekan.

I do have Core 2 Duo laptop that has 8 GB RAM. It has very big Wekan board. Wekan is running in Snap that is installed to same laptop where Chrome runs. When I open that big board, it loads quite fast, because Wekan loads only those cards that are visible. Then, when I press Ctrl -  (keyboard control and minus) to show more of Wekan board, rest of the cards are loaded and then loading animation disappears when it has loaded all cards. With Ctrl + I can zoom back to normal size.

This showing only visible cards has made possible to load big bords that have thousands or cards, and have been imported from Trello to Wekan.

Sometime later when Wekan gets more optimized, there could be less CPU usage.

**Comment by xet7** [comment]
Also, on my Core 2 Duo laptops, fans are not running all the time. Fans were on only for couple minutes, and now it's quiet again.

**Comment by gerroon** [comment]
thanks, I will test it again on my laptop with Chromium, I will let it stay longer to see if the fans will tame down.

**Comment by xet7** [comment]
Moved to #2294

**Comment by gerroon** [comment]
https://github.com/wekan/wekan/pull/2302 helps with the infinite looping animation, but I still get those here and there, at least they are not always.


I think I get them if the lane height is almost same as the browser's window height.

**Comment by gerroon** [comment]
https://github.com/wekan/wekan/pull/2302 helps with the infinite looping animation, but I still get those here and there, at least they are not always.


I think I get them if the lane height is almost same as the browser's window height.

**Comment by bentiss** [comment]
> #2302 helps with the infinite looping animation, 

great!

> but I still get those here and there, at least they are not always.

sigh...

> I think I get them if the lane height is almost same as the browser's window height.

If there are too many cards to fit the window, wekan will make the swimlane the size of the window (minus the various headers), so this doesn't help spotting where this can happen unfortunately :/

> I used to get more lanes with those ones. Now it is one or two lanes having it. Zooming in an out helps to disappear them,

So, if zooming in/out helps, that means that now the callbacks are still registered (which was the initial bug in fact). And that would mean that the `requestIdleCallback` is not triggered when it should, and I am rather clueless here :(

Ideally, if you can find a simple reproducer, that would help a lot.

**Comment by gerroon** [comment]
Hi

I will try to either prepare a board or find a case that you cna repeat and post it here.

thanks

**Comment by xet7** [comment]
Please test does this workaround work #2492

**Comment by gerroon** [comment]
I still have an issue with this in even in %100 zoom in v3.13 not sure if there has been any work on since then.

**Comment by xet7** [comment]
@gerroon 

Please try newest Wekan. Do not report issues in old Wekan versions.

**Comment by gerroon** [comment]
@xet7 Okk but what do you want me to do with this isssue? Close and open a new one?  

I just tried 3.17 (docker) it is still there although much less occurence. I seem to be able to repeat it with the inital loading of a board  if the Wekan app has been also opened the first time.
