### ISSUE TITLE
Meteor source build guide problem

### ISSUE THREAD

**Issue by imidimi** [wekan/wekan#2254]
I m following this guide https://github.com/wekan/wekan/wiki/Meteor-bundle to build standalone wekan on my server. Its not working for me. When i type meteor command it gives error 'not in meteor directory'. Can you please guide me in detail as i want to customize code and build it.

**Comment by xet7** [comment]
rebuild-wekan.sh at https://github.com/wekan/wekan does 1 install dependencies 2 build to wekan/.build/bundle. That rebuild script may need modifications if you have custom directory structure or npm not installed. After building, start-wekan.sh at https://github.com/wekan/wekan does start Wekan with required environment variables and changing to correct directory. Prebuilt bundle is at .tar.gz file at https://releases.wekan.team .
