### ISSUE TITLE
[Enhancement] Duplicate Board from Wekan

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2257]
Good morning,

i have an enhancement request. We have a sprint all 4 weeks for every sprint we export and import the current board, deleting the activities, archived cards etc. In the last time, there a some issues with the process (for example #2237). 

So i ask for an enhancement to duplicated the board in wekan. 

(1) The board gets an function "Duplicate Board"
(2) you get the option to rename the board and (optional) deleting the activities/cleanup the new/duplicated board

**Comment by andresmanelli** [comment]
I am planning of adding this as part por the template feature, but I have
not added this yet.

Le mer. 13 mars 2019 à 09:01, sfahrenholz <notifications@github.com> a
écrit :
