### ISSUE TITLE
feature request: view/edit loginDisabled field in "Admin panel" 

### ISSUE THREAD

**Issue by rblomme** [wekan/wekan#2259]
**Server Setup Information**:
* Wekan version: 2.47.0
* Operating System: Ubuntu 18.04.2 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: v8.15.1
* MongoDB Version: v3.2.22

**Feature Request**:
in the "Admin panel" - "People" tab
can you add the possibility to view/edit the loginDisabled field ?

In the current version, I have to start mongo on the command line, and edit the database manually.

**Comment by rjevnikar** [comment]
This already exists - it is listed under Active, and can be edited in the popup that appears when you click Edit.

**Comment by rblomme** [comment]
Thanks.
I didn't notice that the "Active" field in the Admin panel was the same as the loginDisabled field in the database.
