### ISSUE TITLE
Can't build libreboard

### ISSUE THREAD

**Issue by schattennarr** [wekan/wekan#226]
Hi,

I'm trying to install Libreboard by using the last method. (MongoDB etc.)
Everything worked fine but now I'm failing by installing libreboard.
Using sudo npm install in /libreboard/.build/bundle/programs/server$, I get the following errors:
Terminal:
http://pastebin.com/C1wPT8GQ

npm-debug.log file
http://pastebin.com/fiMaBunm

What am I doing wrong?

**Comment by serut** [comment]
I don't think node-fibers npm module was ported to node 0.12 yet. Try using node 0.10.
#138

**Comment by mquandalle** [comment]
Does that solve the issue @schattennarr?

**Comment by solarisan** [comment]
I had similar issue, I changed to node 0.10 and it resolved the issue

**Comment by mquandalle** [comment]
@ePirat in the manual install guide you said to install the latest version of node, does that work for you? Should we update the guide to recommend node v0.10 — which is the version meteor uses and is tested on?

**Comment by ePirat** [comment]
@mquandalle Indeed, when I wrote that guide (if I recall correctly), v0.10 was the latest stable, but it's not anymore, so the correct version would be 0.10 (or higher in the future, depending which meteor needs)

**Comment by mquandalle** [comment]
From what I've seen in meteor-core development, meteor will probably stick with node v0.10 until the switch to merge of iojs and node (node 5 or whatever it is called), so that's at least 6 months.
