### ISSUE TITLE
Feature Request: Add "Restore from Archive" to archived card's hamburger menu

### ISSUE THREAD

**Issue by rgalonso** [wekan/wekan#2260]
* Did you test in newest Wekan?: yes
* Wekan version: 2.35.0

**Problem description**:
When a card is archived, the only way, currently, to restore it from the archive is by clicking "Restore" below the card, as listed under the Archive sub-menu of the board's hamburger menu.
When there are many cards in the Archive, it can be difficult to find the particular card you want to restore.  The card can be searched for, but in the resulting list of search results, there is no Restore link as there is in the Archive sub-menu.
It would make the restore functionality much easier to use if either (or both) of the following features were implemented:
  - In the hamburger menu of an archived card, add a "Restore from Archive" option.  (This would go in the place of a non-archived card's "Move Card to Archive" option.)
  - In the search results, add the Restore link.

**Relevant UI**:
  - Archive existing card 
![archive_card](https://user-images.githubusercontent.com/17463757/54379311-8c3a9e00-465f-11e9-983b-3f7ac1e78654.gif)
  - Find card in Archive and restore it
![find_and_restore](https://user-images.githubusercontent.com/17463757/54380310-81810880-4661-11e9-8a2f-0636100f1758.gif)
  - Find card via Search, but unable to restore it
![search_but_cannot_restore](https://user-images.githubusercontent.com/17463757/54380699-85615a80-4662-11e9-9662-1614955fce96.gif)

**Comment by xy0** [comment]
This confused me too at first, so good recommendation.

**Comment by Limezy** [comment]
I was also confused by the lack of restore option in the burger menu of an archived card retrieved via search.
It seems that this FR is still valuable as of today
