### ISSUE TITLE
Nowhere to add members in sandstorm implementation

### ISSUE THREAD

**Issue by GreatScott** [wekan/wekan#227]
Running sandstorm v 0.100 -

Installed Libreboard on Sandstorm no problem, but the menu sidebar is missing the button to add members. 

EDIT for more clarity: Adding members via the share private link tool (the sandstorm way) doesn't add other sandstorm users as members to the project.

**Comment by pwaller** [comment]
:+1:

**Comment by ocdtrekkie** [comment]
Generally speaking (assuming sharing works properly, which I don't believe it does in 0.8.0), when you create a sharing link, and then that user clicks on that link (while logged into Sandstorm), then they get added to the board.

**Comment by pwaller** [comment]
@ocdtrekkie this does not happen, at least when I tried it out on a sandstorm instance created a couple of days ago and a libreboard made a couple of hours ago. I can't see how to easily tell what version I'm running.

**Comment by ocdtrekkie** [comment]
The version on the Sandstorm app list is 0.8.0, and it predates Sandstorm's new sharing model. Until 0.9.0 is released, sharing LibreBoard with Sandstorm doesn't work very well.

**Comment by tiagoefreitas** [comment]
I needed Libreboard 0.9 with sharing working on sandstorm, so I created an spk from git. 

I may upload new versions periodically here if I need them:

https://6zoa0lpoq1e4mn4nlkgh.oasis.sandstorm.io

Here is the latest (commit 4ef5a21):

https://6zoa0lpoq1e4mn4nlkgh.oasis.sandstorm.io/libreboard_0.9.0_4ef5a21.spk

**Comment by ocdtrekkie** [comment]
@tiagoefreitas Have you tried using Sandstorm's share mechanic yet? (Send me an invite to a grain of yours to test?)

**Comment by ocdtrekkie** [comment]
A test grain of tiago's SPK: https://oasis.sandstorm.io/shared/uhb45z9vIVNqyVtty6YR1xB76j4fhRB5mxRq1NBA1xh

**Comment by mquandalle** [comment]
This is fixed in the upcoming v0.9 — closing so I can keep track of the remaining tasks.
