### ISSUE TITLE
Link Card to Object Storage Bucket or SMB Directory

### ISSUE THREAD

**Issue by rossmansfield** [wekan/wekan#2274]
Hello all, first time posting here, so be gentle!

In lieu of attaching files into the actual WEKAN cards, it would be fantastic if we could somehow place a thumbnail image of an object in a network location or object-storage bucket.  Even better would be if the Card could show the contents of a Bucket or file directory and allow the user to open said files from the Card.  This is very similar to how Trello can embed Google Drive.  

I've been experimenting with (SMB "Samba", OpenstackSwift, S3, etc.  This would really help with team collaboration.  A custom field could work to send users to the Bucket via an HTML link, but it doesn't allow for links to SMB type directories.   

By having integration with a Swift or S3 type object storage system, redundancy can be handled at the infrastructure level vice the container level.  

I have some experience with Openstack and Minio and could support on that end, I'm just not very strong with code development (yet).

Any thoughts on this?

**Comment by xet7** [comment]
Moved to #142
