### ISSUE TITLE
[Bug] Unable to change board card title (=Board name) at Templates page

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2275]
Similar to #2267 

At Templates page, it's possible to change card name of Card and List templates, but not card name of Board templates. Only if Board template is clicked so it goes to that Board template page, there it's possible to change Board name. But not in card name of Board at Templates page.

ping @andresmanelli

**Comment by xet7** [comment]
Oops sorry, I just forgot to merge PR, this is already fixed. Nevermind.

**Comment by andresmanelli** [comment]
Wasn't this fixed by my latest PRs?

Le jeu. 21 mars 2019 à 00:07, Lauri Ojansivu <notifications@github.com> a
écrit :

**Comment by xet7** [comment]
@andresmanelli 

Yes it's already fixed. Sorry about the noise.
