### ISSUE TITLE
Unable to see the changes in browser once we change code by running meteor command locally.

### ISSUE THREAD

**Issue by KrunalDholakiya** [wekan/wekan#2276]
## Issue
I downloaded wekan source code on my windows machine from github link to modify the application for my purpose. I used meteor command to bring the application up. Now if I change anything in the code there is no way that it will hot reload the UI and will show my changes. I need to re-run meteor command which will take too much time to build packages.

**Comment by andresmanelli** [comment]
Did you try with the `wekan-dev` repository?

Le jeu. 21 mars 2019 à 07:57, KrunalDholakiya <notifications@github.com> a
écrit :

**Comment by KrunalDholakiya** [comment]
Yes tried, but when I try to run my composed docker image it throws below error.
=> Started proxy.
Local package version is up-to-date: 3stack:presence@1.1.2
Local package version is up-to-date: accounts-base@1.4.0
Local package version is up-to-date: accounts-oauth@1.1.15
Local package version is up-to-date: accounts-password@1.5.0
Local package version is up-to-date: aldeed:collection2@2.10.0
Local package version is up-to-date: aldeed:collection2-core@1.2.0
Local package version is up-to-date: aldeed:schema-deny@1.1.0
Local package version is up-to-date: aldeed:schema-index@1.1.1
Local package version is up-to-date: aldeed:simple-schema@1.5.3
Local package version is up-to-date: alethes:pages@1.8.6
Local package version is up-to-date: allow-deny@1.1.0
Local package version is up-to-date: arillo:flow-router-helpers@0.5.2
Local package version is up-to-date: audit-argument-checks@1.0.7
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.24.7
Local package version is up-to-date: babel-runtime@1.1.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.3.1
Local package version is up-to-date: browser-policy-common@1.0.11
Local package version is up-to-date: browser-policy-framing@1.1.0
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: cfs:access-point@0.1.49
Local package version is up-to-date: cfs:base-package@0.0.30
Local package version is up-to-date: cfs:collection@0.5.5
Local package version is up-to-date: cfs:collection-filters@0.2.4
Local package version is up-to-date: cfs:data-man@0.0.6
Local package version is up-to-date: cfs:file@0.1.17
Local package version is up-to-date: cfs:gridfs@0.0.34
Local package version is up-to-date: cfs:http-methods@0.0.32
Local package version is up-to-date: cfs:http-publish@0.0.13
Local package version is up-to-date: cfs:power-queue@0.9.11
Local package version is up-to-date: cfs:reactive-list@0.0.9
Local package version is up-to-date: cfs:reactive-property@0.0.4
Local package version is up-to-date: cfs:standard-packages@0.5.9
Local package version is up-to-date: cfs:storage-adapter@0.2.3
Local package version is up-to-date: cfs:tempstore@0.1.5
Local package version is up-to-date: cfs:upload-http@0.0.20
Local package version is up-to-date: cfs:worker@0.1.4
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: chuangbo:cookie@1.1.0
Local package version is up-to-date: coffeescript@1.12.7_3
Local package version is up-to-date: coffeescript-compiler@1.12.7_3
Local package version is up-to-date: cottz:publish-relations@2.0.8
Local package version is up-to-date: dburles:collection-helpers@1.1.0
Local package version is up-to-date: ddp@1.4.0
Local package version is up-to-date: ddp-client@2.2.0
Local package version is up-to-date: ddp-common@1.3.0
Local package version is up-to-date: ddp-rate-limiter@1.0.7
Local package version is up-to-date: ddp-server@2.1.1
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: dynamic-import@0.2.1
Local package version is up-to-date: ecmascript@0.9.0
Local package version is up-to-date: ecmascript-runtime@0.5.0
Local package version is up-to-date: ecmascript-runtime-client@0.5.0
Local package version is up-to-date: ecmascript-runtime-server@0.5.0
Local package version is up-to-date: ejson@1.1.0
Local package version is up-to-date: email@1.2.3
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: fortawesome:fontawesome@4.7.0
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: horka:swipebox@1.0.2
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.3.0
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: idmontie:migrations@1.0.3
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: kadira:blaze-layout@2.3.0
Local package version is up-to-date: kadira:dochead@1.5.0
Local package version is up-to-date: kenton:accounts-sandstorm@0.7.0
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.2.0
Local package version is up-to-date: logging@1.1.19
Local package version is up-to-date: lucasantoniassi:accounts-lockout@1.0.0
Local package version is up-to-date: matb33:collection-hooks@0.8.4
Local package version is up-to-date: matteodem:easy-search@1.6.4
Local package version is up-to-date: mdg:meteor-apm-agent@3.1.2
Local package version is up-to-date: mdg:validation-error@0.5.1
Local package version is up-to-date: meteor@1.8.2
Local package version is up-to-date: meteor-base@1.2.0
Local package version is up-to-date: meteor-platform@1.2.6
Local package version is up-to-date: meteorhacks:aggregate@1.3.0
Local package version is up-to-date: meteorhacks:collection-utils@1.2.0
Local package version is up-to-date: meteorhacks:meteorx@1.4.1
Local package version is up-to-date: meteorhacks:picker@1.0.3
Local package version is up-to-date: meteorhacks:subs-manager@1.6.4
Local package version is up-to-date: meteorhacks:unblock@1.1.0
Local package version is up-to-date: meteorspark:util@0.2.0
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minifier-js@2.2.2
Local package version is up-to-date: minifiers@1.1.8-faster-rebuild.0
Local package version is up-to-date: minimongo@1.4.3
Local package version is up-to-date: mixmax:smart-disconnect@0.0.4
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.11.0
Local package version is up-to-date: modules-runtime@0.9.1
Local package version is up-to-date: momentjs:moment@2.22.2
Local package version is up-to-date: mongo@1.3.1
Local package version is up-to-date: mongo-dev-server@1.1.0
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: mongo-livedata@1.0.12
Local package version is up-to-date: mousetrap:mousetrap@1.4.6_1
Local package version is up-to-date: mquandalle:autofocus@1.0.0
Local package version is up-to-date: mquandalle:collection-mutations@0.1.0
Local package version is up-to-date: mquandalle:jade@0.4.9
Local package version is up-to-date: mquandalle:jade-compiler@0.4.5
Local package version is up-to-date: mquandalle:jquery-textcomplete@0.8.0_1
Local package version is up-to-date: mquandalle:jquery-ui-drag-drop-sort@0.2.0
Local package version is up-to-date: mquandalle:moment@1.0.1
Local package version is up-to-date: mquandalle:mousetrap-bindglobal@0.0.1
Local package version is up-to-date: mquandalle:perfect-scrollbar@0.6.5_2
Local package version is up-to-date: msavin:usercache@1.0.0
Local package version is up-to-date: npm-bcrypt@0.9.3
Local package version is up-to-date: npm-mongo@2.2.33
Local package version is up-to-date: oauth@1.2.1
Local package version is up-to-date: oauth2@1.2.0
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ongoworks:speakingurl@1.1.0
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: peerlibrary:assert@0.2.5
Local package version is up-to-date: peerlibrary:base-component@0.16.0
Local package version is up-to-date: peerlibrary:blaze-components@0.15.1
Local package version is up-to-date: peerlibrary:computed-field@0.7.0
Local package version is up-to-date: peerlibrary:reactive-field@0.3.0
Local package version is up-to-date: perak:markdown@1.0.5
Local package version is up-to-date: promise@0.10.0
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: raix:handlebar-helpers@0.2.5
Local package version is up-to-date: rajit:bootstrap3-datepicker@1.7.1
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: rate-limit@1.0.8
Local package version is up-to-date: reactive-dict@1.2.0
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: rzymek:fullcalendar@3.8.0
Local package version is up-to-date: service-configuration@1.0.11
Local package version is up-to-date: session@1.1.7
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.3.1
Local package version is up-to-date: simple:authenticate-user-by-token@1.0.1
Local package version is up-to-date: simple:json-routes@2.1.0
Local package version is up-to-date: simple:rest-accounts-password@1.1.2
Local package version is up-to-date: simple:rest-bearer-token-parser@1.0.1
Local package version is up-to-date: simple:rest-json-error-handler@1.0.1
Local package version is up-to-date: softwarerero:accounts-t9n@1.3.11
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.3
Local package version is up-to-date: srp@1.0.10
Local package version is up-to-date: standard-minifier-css@1.3.5
Local package version is up-to-date: standard-minifier-js@2.2.3
Local package version is up-to-date: staringatlights:fast-render@2.16.5
Local package version is up-to-date: staringatlights:inject-data@2.0.5
Local package version is up-to-date: stylus@2.513.13
Local package version is up-to-date: tap:i18n@1.8.2
Local package version is up-to-date: templates:tabs@2.3.0
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.3
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: useraccounts:flow-routing@1.14.2
Local package version is up-to-date: useraccounts:unstyled@1.14.2
Local package version is up-to-date: verron:autosize@3.0.8
Local package version is up-to-date: webapp@1.4.0
Local package version is up-to-date: webapp-hashing@1.0.9
Local package version is up-to-date: yasaricli:slugify@0.0.7
Local package version is up-to-date: zimme:active-route@2.3.2
=> A patch (Meteor 1.6.1.4) for your current release is available!
   Update this project now with 'meteor update --patch'.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Can't start Mongo server.
MongoDB failed global initialization

Looks like MongoDB doesn't understand your locale settings. See
https://github.com/meteor/meteor/issues/4019 for more details.

**Comment by xet7** [comment]
@KrunalDholakiya 

What you are trying to modify in Wekan? Are you trying to add some feature?

In general, Windows and Mac filesystems are slow, so I do recommend installing Linux Mint 19.1 as dual boot and building from with rebuild-wekan.sh and then meteor command.

**Comment by xet7** [comment]
And above, building without Docker.

**Comment by KrunalDholakiya** [comment]
@andresmanelli I used wekan-dev and it's working fine for me. Thanks

**Comment by KrunalDholakiya** [comment]
@xet7 I wanted to add custom feature for my personal use. But it's working fine with wekan-dev. Thanks😄
