### ISSUE TITLE
Newbie installation experience

### ISSUE THREAD

**Issue by jean** [wekan/wekan#2277]
- Stumbled my way through the confusing [wiki](https://github.com/wekan/wekan/wiki/). Finally spot: _"you could install it right away on your own server_", oh cool! Hrm, that goes to a [stub](https://github.com/wekan/wekan/wiki/Install-and-Update), and that points at a [labyrinth](https://github.com/wekan/wekan/wiki/Platforms).  
- On the labyrinthine  _Platforms_ page, it looks like Snap should be a good option. 
- Snap installs with a warning, quoted below. 
- `systemctl restart snap.wekan.wekan` completes with no output, but `ps wax | grep wekan` shows it running. 
- The wiki page doesn't mention _where_ it's running by default, but a [search](https://duckduckgo.com/?q=wekan+default+port&t=lm&ia=web) reveals it's port `8080`. 
- At that port, I find a login widget. I try to register and fail with an "internal server error".
- I go back to the install page and after skipping a lot of irrelevant steps with code blocks, find a link to [Adding users](https://github.com/wekan/wekan/wiki/Adding-users) which says that that error can be ignored.
- Oh, yay, I can actually log in!

As I find my way around, I'll try to improve the wiki pages ... I just wanted to record some first impressions. Because all newcomers share this, but it's forgotten as soon as you're up and running ...

Anyway, looks like a super interesting project, I hope we'll be able to use it. 

```
15:07 john@john:~$ sudo apt install snapd
[sudo] password for john:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  squashfs-tools
The following NEW packages will be installed:
  snapd squashfs-tools
0 upgraded, 2 newly installed, 0 to remove and 5 not upgraded.
Need to get 16.4 MB of archives.
After this operation, 95.0 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://ubuntu-mirror.totbb.net/ubuntu xenial-updates/main amd64 squashfs-tools amd64 1:4.3-3ubuntu2.16.04.3 [105 kB]
Get:2 http://ubuntu-mirror.totbb.net/ubuntu xenial-updates/main amd64 snapd amd64 2.37.4 [16.3 MB]
Fetched 16.4 MB in 6s (2,545 kB/s)
Selecting previously unselected package squashfs-tools.
(Reading database ... 742438 files and directories currently installed.)
Preparing to unpack .../squashfs-tools_1%3a4.3-3ubuntu2.16.04.3_amd64.deb ...
Unpacking squashfs-tools (1:4.3-3ubuntu2.16.04.3) ...
Selecting previously unselected package snapd.
Preparing to unpack .../snapd_2.37.4_amd64.deb ...
Unpacking snapd (2.37.4) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up squashfs-tools (1:4.3-3ubuntu2.16.04.3) ...
Setting up snapd (2.37.4) ...
md5sum: /etc/apparmor.d/usr.lib.snapd.snap-confine: No such file or directory
snapd.failure.service is a disabled or a static unit, not starting it.
snapd.snap-repair.service is a disabled or a static unit, not starting it.
```

**Comment by xet7** [comment]
Moved to #2222
