### ISSUE TITLE
Drag and drop between checklists closes the card sometimes on Firefox

### ISSUE THREAD

**Issue by OddmarDam** [wekan/wekan#2280]
## Issue
When dragging a task from one checklist to another checklist, the card closes when i release the task

**Server Setup Information**:

* Wekan version 2.51.0
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend: Nginx
* Node Version: 8.15.1

**Problem description**:
![OddmarstestNetfoUppgv](https://user-images.githubusercontent.com/4441007/54764625-0f279f80-4bf0-11e9-83c9-0aae8723ade6.gif)

**Comment by h0jeZvgoxFepBQ2C** [comment]
Can confirm.

**Comment by mfilser** [comment]
I can confirm that also.
As in gif above, it occures not always.
Did anyone notify when this happens?

**Comment by OddmarDam** [comment]
Iw'e only noticed the problem in Firefox. In Chrome it seems to work just fine.

**Comment by mfilser** [comment]
Thank you for your reply.
I use FireFox, so i can confirm it for that browser.
Chrome not testet for me yet.

**Comment by OddmarDam** [comment]
It also seems that it closes dependent on where you drop it. 
Sometimes it closes the card and sometimes not.

**Comment by xet7** [comment]
I presume it depends do you drag checklist to correct place. If you drag outside of card, I presume then card closes.

**Comment by OddmarDam** [comment]
I always drag on the list, but i notice there is a difference in the background color sometimes, when i drop on the list.

**Comment by loucurapt** [comment]
This also happens to me in Firefox when dragging and dropping checklist items, but not always.
Chrome doesn't seem to be affected.

**Comment by xet7** [comment]
Can someone test newest Wekan with Firefox/Chromium/Chrome/Edge/Chromium Edge and Mobile Chrome? Wekan currently works in those browsers. AFAIK Vivaldi/Internet Explorer and Mobile Firefox are broken, they do not load all boards or cards,

Browsers have updates all the time, it depends does new browser version break or fix something. Also, does some browser just have a bug, or is there some html/css/javascript code that would make it work on some browser.

**Comment by xet7** [comment]
Also, if some webbrowser does not work, are there errors in browser right click Inspect console?

**Comment by loucurapt** [comment]
I didn't see any error in the console (latest version of Firefox and Wekan snap).

**Comment by mfilser** [comment]
Issue is still there and no error's in the console.
The card still closes as in the description and gif above.

Tested with Wekan v3.44 and FireFox 60.0.1 (64-bit).

**Comment by stvnw** [comment]
I can confirm it is still an issue in Wekan 4.42.0 / Firefox 81.0.2. Following are some observations (none of which have been arrived at through any sort of testing more rigorous than a lot of clicking.)

It seems as though:
- The same item can be moved back and forth between the same two slots several times correctly until upon some random attempt the card will close.
- It doesn't matter whether:
	- Moving within the same or different checklists
	- The source slot is first, intermediate, or last
	- The target slot is first, intermediate, or last
	- The target list is empty or has existing items
	- The item is not actually moved; just picking up and dropping in the same slot can trigger the issue
- Every item is capable of triggering the issue eventually. Some items are affected more than others. Some appear affected 100% of the time.
- There is some positive correlation between the length of the item name and the frequency of occurrence. In my instance, an item with length >= 54 characters and no whitespace will cause the issue 100% of the time. As white space is introduced this limit in some cases goes up.

There are no relevant messages in the console throughout any of the testing.
 
These observations were made on a small (1 user / 2 boards / ~400 cards) locally hosted Wekan instance running in Docker on a 2018 MacBook Pro.

**Comment by xet7** [comment]
Just a small status update.

Someone sent me 10€ with wish to fix this. So I looked into this for some hours:
- Code works on Chromium and Safari, but not Firefox.
- Creating multiline checklist item and dragging it to another checlist reproduces this bug in Firefox every time.
- There is no errors at browser Inspect Console.
- Uncommenting some Javascript `.close()` code for closing elements did not have any effect.
- Removing [mquandalle:meteor-jquery-ui-drag-drop-sort](https://github.com/mquandalle/meteor-jquery-ui-drag-drop-sort) with `meteor remove mquandalle:meteor-jquery-ui-drag-drop-sort`, forking it to `wekan/packages/wekan-jquery-ui-drag-drop-sort`, changing package name at `package.js`, adding to meteor with `meteor add wekan-jquery-ui-drag-drop-sort` and downloading newest files of jquery-ui etc did not have any effect
- Some web searched did lead to these results:
  - https://www.google.com/search?q=firefox+jquery+ui+drag+drop+bug
  -  https://bugs.jqueryui.com/ticket/4255
  - https://bugs.jqueryui.com/ticket/2405
  - https://stackoverflow.com/questions/25830615/jquery-drag-and-drop-not-working-in-firefox-works-fine-in-chrome-and-safari (this could have some working code, not tested)

Although now my head is spinning enough so I need to take a break, and maybe try some of that possibly working code later. If someone else would also have the energy to try to try to figure out fix to this, with above additional info, it would also be nice.

**Comment by xet7** [comment]
I did add this to [Wekan Roadmap here](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/zJ8L5mPeRCG5ZaBJa)
