### ISSUE TITLE
Tips to debug a board that doesn't load?

### ISSUE THREAD

**Issue by payala** [wekan/wekan#2283]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 2.51
* If this is about old version of Wekan, what upgrade problem you have?: not about old version
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 8.15.1
* MongoDB Version: 
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
Lately I'm running quite frequently into boards that don't load, they look something like this:

https://i.imgur.com/XpnwmFi.png

When this happens, I typically log into the database and poll the "Activities" collection to see what was the last change in that board. Up to now, it normally was some kind of corrupt operation which I could undo manually.

Also, I can see an error in the browser javascript console, but I can't relate it to anything meaningful. Today, I'm getting a bunch of errors, but there is one read "uncaught typeError" which I copy below:

https://i.imgur.com/ZIRy6Eq.png

Of course, any help to debug this issue is appreciated, but what I'm really interested in knowing is a general procedure to debug these kind of errors, that would be great!

Thanks! Pedro

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*

https://i.imgur.com/C1VicNv.png

- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*

https://i.imgur.com/CLWlOXL.png

**Comment by payala** [comment]
I found out what was blocking the board from loading. Deleting the last linkedCard that I created fixes it.

The linkedCard content was this, all references are correct, but there is no linkedId:

{
    "_id" : "z6ZWhYAgN2rRQXGLG",
    "title" : "inner",
    "members" : [ 
        "DtpDEG93LfCujoSg9"
    ],
    "labelIds" : [],
    "customFields" : [],
    "listId" : "nt8grhckahdjNTg58",
    "boardId" : "7QZd8F36SfFBWaR2L",
    "sort" : 27,
    "swimlaneId" : "Bg3ETzEGfC2fZHAt6",
    "type" : "cardType-linkedCard",
    "archived" : false,
    "createdAt" : ISODate("2019-03-18T09:54:55.568Z"),
    "dateLastActivity" : ISODate("2019-03-18T09:54:55.568Z"),
    "spentTime" : 0,
    "isOvertime" : false,
    "userId" : "neyHpHif9rXEKosFJ",
    "subtaskSort" : -1,
    "parentId" : "",
    "coverId" : "",
    "description" : "",
    "requestedBy" : "",
    "assignedBy" : "",
    "linkedId" : ""
}

I remember when I created this card, something strange happened, the card suddenly dissapeared, reappeared. But I can't remember the exact sequence.

**Comment by xet7** [comment]
Well, if you make backup, and try to make that bug happen again in newest Wekan version. Some bugs like linking card to itself have been recently fixed, so I don't know can this be reproduced and how.

**Comment by xet7** [comment]
Please test does this workaround work #2492

**Comment by xet7** [comment]
Moved to #2785
