### ISSUE TITLE
如何获取所有用户的看板和用户名，邮箱

### ISSUE THREAD

**Issue by chenghongxi** [wekan/wekan#2284]
curl -H "Authorization: Bearer a6DM_gOPRwBdynfXaGBaiiEwTiAuigR_Fj_81QmNpnf" \
      http://localhost:3000/api/users/XQMZgynx9M79qTtQc/boards

使用如上接口，无法获取到看板的信息。

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data

Login Admin user:
```
curl http://localhost:3000/users/login -d "username=myusername&password=mypassword"
```
=> Bearer 12345
```
curl -H "Authorization: Bearer 12345" 
http://localhost:3000/api/users/XQMZgynx9M79qTtQc/boards
```

**Comment by chenghongxi** [comment]
我是想获取到所有卡片或者看板，每天定时发送给看板或者卡片有关联人员。 以便方便管理，在python API接口中并没有看到相关的API接口。

**Comment by xet7** [comment]
https://wekan.github.io/api/v2.55/?python#new_card

```
export EDITOR=nano
crontab -e
```
https://crontab.guru/

At every hour https://crontab.guru/#0_*_*_*_*
```
0 * * * * /home/user/add-cards.py
```
And add-cards.py:
```
which python
```
=>
```
#!/usr/bin/python

import requests
headers = {
  'Content-Type': 'multipart/form-data',
  'Accept': 'application/json',
  'Authorization': 'API_KEY'
}

r = requests.post('/api/boards/BOARD-ID-HERE/lists/LIST-ID-HERE/cards', params={

}, headers = headers)

print r.json()
```
* Nano Save: Ctrl-o Enter
* Nano Exit: Ctrl-x

**Comment by xet7** [comment]
And:
```
chmod +x /home/user/add-cards.py
```

**Comment by chenghongxi** [comment]
1.通过这个add-card.py能直接获取到用户么？
2.如何能直接获取到用户和邮箱，这样通过smtp就可以直接发送邮件了

**Comment by xet7** [comment]
https://wekan.github.io/api/v2.55/?python#get_all_users

https://wekan.github.io/api/v2.55/?python#get_user

https://wekan.github.io/api/v2.55/?python#get_boards_from_user

https://wekan.github.io/api/v2.55/?python#get_all_lists

https://wekan.github.io/api/v2.55/?python#get_all_cards

**Comment by xet7** [comment]
2) https://realpython.com/python-send-email/

**Comment by chenghongxi** [comment]
import requests
headers = {
  'Content-Type': 'application/x-www-form-urlencoded',
  'Accept': '*/*',
  'Authorization': 'API_KEY'
}
pa={'username':'admin','password':'qq'}
r_login = requests.post('http://39.105.168.17:20110/users/login', data = pa,headers = headers)
print (r_login.json())

pa_user={'user':'admin'}
r = requests.get('http://39.105.168.17:20110/api/users/{user}/boards', data = pa_user, headers = headers)
print (r.json())
输出结果：
{'id': 'gcNdbJqfp76pPJxLn', 'token': 'OUfWqbj3O-HrkWDfPEoxzQ97gdblWKD97SatICbbnDb', 'tokenExpires': '2019-07-01T14:04:01.811Z'}
{'isClientSafe': True, 'error': 'Unauthorized', 'reason': 'Unauthorized', 'message': 'Unauthorized [Unauthorized]', 'errorType': 'Meteor.Error', 'statusCode': 401}

我已经进行过使用管理账号登陆验证了，这个admin的看板信息还是没有输出出来，statuscode：401

**Comment by chenghongxi** [comment]
UserSecurity怎么使用，怎么调用？需要什么参数？

**Comment by chenghongxi** [comment]
import requests
headers = {
  'Accept': 'application/json',
  'Authorization': 'API_KEY'
}

r = requests.get('/api/users/{user}/boards', params={

}, headers = headers)

print r.json()
使用这个接口，都哪里需要什么参数？ 怎么通过这个To perform this operation, you must be authenticated by means of one of the following methods: UserSecurity验证呢？
@xet7

**Comment by xet7** [comment]
Sorry I'm busy this week. Maybe I could have time to look at it next week.

**Comment by xet7** [comment]
Boards, users etc REST API code here:
https://github.com/wekan/wekan/tree/devel/models

Maybe something there does not work yet.

**Comment by chenghongxi** [comment]
好的，谢谢您。所有需要调用api接口的都需要这个方法进行调用，UserSecurity。  这个一直不知道怎么调用他。  如果您有时间，帮我看下这个问题 谢谢

**Comment by zhangsn** [comment]
> 好的，谢谢您。所有需要调用api接口的都需要这个方法进行调用，UserSecurity。 这个一直不知道怎么调用他。 如果您有时间，帮我看下这个问题 谢谢

先通过/users/login拿到token，然后在调用具体需要验证的接口时在Header里面增加Authorization: Bearer {token}就可以了，注意Bearer是固定的，后面有一个空格

**Comment by chenghongxi** [comment]
有什么例子么？   可以看一下




------------------ 原始邮件 ------------------
发件人: "zhangsn"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 晚上10:18
收件人: "wekan/wekan"<wekan@noreply.github.com>;
抄送: "小白"<422459409@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wekan/wekan] 如何获取所有用户的看板和用户名，邮箱 (#2284)



 
好的，谢谢您。所有需要调用api接口的都需要这个方法进行调用，UserSecurity。 这个一直不知道怎么调用他。 如果您有时间，帮我看下这个问题 谢谢
  
先通过/users/login拿到token，然后在调用具体需要验证的接口时在Header里面增加Authorization: Bearer {token}就可以了，注意Bearer是固定的，后面有一个空格

**Comment by xet7** [comment]
Try to install https://github.com/wekan/wekan-gogs and look at it's code how it works.
