### ISSUE TITLE
[Bug] Incorrect variable replacement on email notifications

### ISSUE THREAD

**Issue by justinr1234** [wekan/wekan#2285]
justin added member __member__ to card "Test card" at list __list__ at swimlane __swimlane__ at board "Test board"
https://localhost:3000/b/p4kACssPpAJQxbn7T/test-board/PqEie2okKBWrKuri8

It does not properly replace the variables for `__member__`, `__list__` and `__swimlane__`

**Comment by JonasDralle** [comment]
Oh yeah we got that too.
I thought it was a setup mistake but when other experience the same it's probably a bug:

![image](https://user-images.githubusercontent.com/6533815/54904765-a4bc7b00-4edf-11e9-8830-e983d7742254.png)
(mail from 3 days ago. My mail program displays dates a bit odd)

**Comment by justinr1234** [comment]
@xet7 this commit broke it: https://github.com/wekan/wekan/commit/3bfc6ea8d7ee72d3507f64c369e1478fffeaf337#diff-3bd53577793963a790b0a2c8b10e3fabR30

You did not make the corresponding variable changes necessary here: https://github.com/wekan/wekan/blob/devel/models/cards.js#L1381

Which results in it skipping the insertion of the proper variables in the message here;

**Comment by xet7** [comment]
@justinr1234 

Can you make PR to fix it? It's too late for me to today think how to fix it, I'm too tired. I try to look at it tomorrow.

**Comment by rinnaz** [comment]
It's still an issue when
- checking/unchecking checklist items (`__list__` & `__swimlane__`)
- moving cards to Archive (`__swimlane__`)

**Comment by justinr1234** [comment]
Should be same problem. Any chance you can fix?

**Comment by rinnaz** [comment]
Ok, I'll see what I can do.

**Comment by rinnaz** [comment]
Fixed for archiving and restoring cards.
No success with:
- attachments
- card comments
- checklists
- checklist items

Need more thoughtful approach.

**Comment by rinnaz** [comment]
5283ba9 fixed checklists and card comments
