### ISSUE TITLE
Copy card with labels don't work

### ISSUE THREAD

**Issue by dieTausendsassa** [wekan/wekan#2288]
**Server Setup Information**:
* Wekan version: V2.56
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Node Version: V8.15.1
* MongoDB Version: V4.0.7

**Problem description**
- Create a card with one or more labels
- Select card menu "Copy Card"
- Confirm with "Done"

**Bug**
- New created card has all available labels

**Required**
- New created card has the same labels as the original (source) card

**Comment by andresmanelli** [comment]
I think the code is already there but for the `move` command.

**Comment by xet7** [comment]
Moved to #2970
