### ISSUE TITLE
Card move to top/bottom don't work

### ISSUE THREAD

**Issue by dieTausendsassa** [wekan/wekan#2289]
**Server Setup Information:**
- Wekan version: V2.56
- Operating System: Linux
- Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
- Node Version: V8.15.1
- MongoDB Version: V4.0.7

**Problem description**
- Select card menu "Move To Top" or "Move To Bottom"

**Bug**
- Card will not move to top or bottom in the list

**Required**
- Card should be moved to top or bottom in the list

**Comment by therampagerado** [comment]
Same here. Introduced recently...

**Comment by xet7** [comment]
@andresmanelli 

It seems that Card move to top/bottom works in Wekan v2.48 but does not work in v2.49. There are some yours and some other changes, but I could not figure out yet how to make it work. Can you look at it?

**Comment by hingerlanton** [comment]
Same here :)

**Comment by charlessteiner** [comment]
Not working in 2.74.0

**Comment by road42** [comment]
The fix was merged with release: v2.85
