### ISSUE TITLE
High CPU load in browser

### ISSUE THREAD

**Issue by insertjokehere** [wekan/wekan#2294]
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: v2.56
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker/kubernetes
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Kubernetes nginx-ingress
* Node Version: from Docker container
* MongoDB Version: `docker.io/bitnami/mongodb:3.6.6-debian-9`

**Problem description**:
When opening a wekan board, CPU usage for Chrome and Firefox (possibly others, not tested) increases substantially - with my largest board open, and no other tabs, both Firefox and Chrome will use an entire CPU core. The amount of CPU load seems to be roughly proportional to the number of cards in the board. The CPU usage does occur when the dashboard page is open

**Comment by xet7** [comment]
Well, does something not work, when your largest board is open? What is the bug?

**Comment by xet7** [comment]
Hmm, actually I kind of expected this. Now that Wekan server part works much faster, and most bugs and feature requests have been added as issues, not it's that on browser Wekan uses CPU. Well, hopefully someone figures out what to do with this.

**Comment by xet7** [comment]
I presume next bug will be that Wekan uses disk space ;)

**Comment by insertjokehere** [comment]
Sorry, to be explicit: the bug is that it didn't used to take huge amounts of CPU to load the interface. I believe this was introduced somewhere after v2.53, will downgrade to old versions to work out when it was introduced

**Comment by xet7** [comment]
Yes, if you find what change did increase CPU, it could probably be fixed.

**Comment by insertjokehere** [comment]
Testing this:
* Set Kubernetes to run container from quay.io with the appropriate version
* Wait for deployment to complete
* Open Wekan in Chrome
* Force-clear cache
* Load my "Todo" board (~75 cards in 6 columns)
* Keep tab open for 30 seconds for usage to settle
* Observe CPU usage of Chrome processes using htop

Results:
* Wekan v2.53, v2.54, v2.55: CPU is idle with Wekan open, <5% usage
* Wekan v2.56: 100% CPU load on 1 core

Looking at the changelog, I wonder if https://github.com/wekan/wekan/commit/619e5e944b0ea0fc8d5259e201359aba8434909e#diff-6249b1271059081e68694ee2e03da132R647 has something todo with this? If the `spinnerShown` check is 'stuck' as true, then the event firing is going to schedule another event to be fired immediately in a busy-loop

**Comment by xet7** [comment]
It could maybe.

@bentiss 

Can you look at this?

**Comment by gerroon** [comment]
This is a follow up from another bug. I am having the same issue.  @xet7 mentioned that cpu usage of his Chromium goes down after 2 mins or so when used with Wekan. I just tested it Chromium and let it sit thre for 5 mins, and the cpu usage never went down. The only thing that made it better was to goto the main board page. 

I am really suspecting that the new code that hanleds the scrolling is the culprit here since the OP said that the cpu use is proprotional to the number of cards, which I can attest as well.

**Comment by xet7** [comment]
I would guess that the code just does not idle enough. With some idle delay code added it could maybe work just fine.

**Comment by xet7** [comment]
That requestIdleCallback description is here:
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

I'm thinking about what kind of code would idle properly.

**Comment by insertjokehere** [comment]
Some more experimentation:

* The high-load does not seem to occur present on boards that don't have columns long enough to trigger the "load on scroll" spinner
* On boards that do trigger the high-load, if I resize the browser window smaller so the full column view is replaced by the column headers, the load goes down significantly

Both seem to indicate something to do with detecting if the spinner is on-screen

**Comment by bentiss** [comment]
couple of notes:

`requestIdleCallback` is not called more than it should. It is just a way to call the refresh function after everything has been reloaded and the DOM updated. I traced it carefully and it is called exactly once when it needs to load more cards, so it is very punctual.

I am suspecting `IntersectionObserver` to do nasty things behind our back. When the board loads and has no spinners triggered, FF shows a `Low` usage. As soon as I scroll down and get a spinner hit and triggered, then FF sticks to a `Medium` usage on my boards.

**Comment by gerroon** [comment]
HI

@bentiss 

Thanks for the fix. https://github.com/wekan/wekan/pull/2302  seems to help a lot but I still feel like the cpu usage is higher than before the initial scroll fix applied.

Using

Wekan Version	v2.57.0
Node version	v8.15.1

**Comment by bentiss** [comment]
OK, then the only thing that can make the CPU work is that we have an animation outside of the viewport which drains processing time.

I tried fixing that this morning, but I got more urgent things that came in this afternoon :/

**Comment by xet7** [comment]
Moved to here from #2309 

From @duckhawk 

**Server Setup Information**:

* Did you test in newest Wekan?:
Yes, there is fresh wekan in docker-compose.

Wekan Version	v2.55.0
Node version	v8.15.1
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	4.15.0-46-generic
OS Uptime	3 hours, 51 seconds


* Operating System:
Ubuntu 18.04.2

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Docker

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
Proxifying Nginx server

* MongoDB Version:
mongodb-core: 2.0.11

**Problem description**:
There is a 100% cpu load on fresh installation, after 10-15 minutes after start.
In proccesses, it looks like permanent work with mongo, but there is no problems in log, so I can't determine, what wekan doing at this moment.

- *Explain steps how to reproduce*
There is no some specific steps to reproduce, just wait for some time

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*

In browser I see only messages "WebSocket is closed":
9ac30447135983729d8b334aa125ec8d5f338541.js?meteor_js_resource=true:77 WebSocket connection to 'wss://x.x.x.ru/sockjs/660/2x47m7_9/websocket' failed: WebSocket is closed before the connection is established.

- *If using Docker, what does show command `sudo docker logs wekan-app` ?*

Only this:
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 144)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 147)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 150)

**Comment by xet7** [comment]
@insertjokehere @gerroon

Does `High CPU load in browser` still happen with newest WeKan v6.60 ?

**Comment by insertjokehere** [comment]
Think this is better now?

**Comment by gerroon** [comment]
I do not see  high cpu on Chromium.
