### ISSUE TITLE
Ability to Re-order labels

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2295]
**Feature Request**
The ability to adjust the order labels appear in the board and card menus would be helpful.

**Comment by rjevnikar** [comment]
I just checked with the latest docker build from quay.io and the commit that references this issue, didn't make labels re-orderable, as far as I can tell.
If I am incorrect, can someone please explain how to re-order labels? Clicking and dragging does not work.
Thank you.

**Comment by xet7** [comment]
Ok, maybe wrong issue was referenced in that commit?  @bentiss what do you think?

**Comment by bentiss** [comment]
not sure what happened here: the commit is referencing my tree here when this was a simple rebase from my side on top of devel.

The wrong commit issue is that 088ec7fd949db3 mentions this bug (#2295) when the original commit 289f1fe1340c85 mentioned #2285 -> this is just a typo when writing the changelog :)

**Comment by gkarachuk** [comment]
Label reordering would be great.

**Comment by jhgovsi** [comment]
indeed it would be great. or at least if labels were sorted (and grouped) first by colors and then by name by default...

**Comment by chrnin** [comment]
A hacky but effective way to reorder labels is to edit the board object directly in the mongodb `boards` collection and reorder the `label` property by hand. I don't know if it's a good idea to do it while wekan is running, so, properly shutdown the front service looks like a good precaution. Also, don't mess with ids :)

**Comment by xet7** [comment]
Moved to #3424
