### ISSUE TITLE
Feature Request : Send notifications of due dates

### ISSUE THREAD

**Issue by sh2515** [wekan/wekan#2297]
Can I ask if you could put into your roadmap notifications of due dates please.
For me it would have the following features:
- send notifications to email
- send notifications to phone
- be able to select that you only receive due notifications and not other activity

Possible
- could have a calendar you can subscribe to to get all this info, and each note with a date gets notifications automatically.

I have been playing with kanban self hosted web services and there doesn't appear to be any that have the ability to have notifications for coming up due dates.

**Comment by xet7** [comment]
Moved to #2567
