### ISSUE TITLE
Other members can't see cards in templates

### ISSUE THREAD

**Issue by HEMGab** [wekan/wekan#2300]
Server Setup Information:

![image](https://user-images.githubusercontent.com/49143522/55312626-41de5d00-5466-11e9-80e7-4240e903d272.png)
 
Linux Snap

Problem description:
I created templates and invited other members. Other members can see all the cards by accessing the templates through the invitation email but whenever they try to access the templates through the "templates" button no cards show up. 

show command `sudo snap logs wekan.wekan:

![snap](https://user-images.githubusercontent.com/49143522/55325192-9690d080-5484-11e9-9637-ad84ccb55e8e.png)

**Comment by andresmanelli** [comment]
Hello. No, it is not possible for the moment. But I think this is on the TODO list on #2209

**Comment by xet7** [comment]
Moved to #2209
