### ISSUE TITLE
[Bug] Card Label can not be set on created boards pre 2.57

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2307]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:

![image](https://user-images.githubusercontent.com/6977657/55508542-6a2ead00-565a-11e9-8275-78b7b395079e.png)

**Problem description**:
- I have an board, with i created in 2.56 (start vm on this version). After update to 2.57 i cannot add a label on a card at this board. There is no log (snap -logs wekan)
On new Boards, it works fine

![2019-04-03_21-52-06](https://user-images.githubusercontent.com/6977657/55508858-0b1d6800-565b-11e9-91f8-08d738fe6ace.gif)

**Comment by chotaire** [comment]
I just tried to reproduce this on a board and a card created in <2.57 and it works fine for me on 2.57.
