### ISSUE TITLE
Translation for IFTTT rules not flexible enough

### ISSUE THREAD

**Issue by Chartman123** [wekan/wekan#2308]
## Issue

**Problem description**:
The German translation for the rules configuration can't be done correctly as the order of the translated strings can't be adjusted to German grammar rules. Please make the strings more adjustable. I think it would be best to work with placeholders like in some other strings. :-)

**Comment by xet7** [comment]
@Chartman123 

Examples please? What changes should be made?

**Comment by Chartman123** [comment]
![grafik](https://user-images.githubusercontent.com/16020496/55724380-97d57680-5a0b-11e9-8c39-32874177e301.png)
![grafik](https://user-images.githubusercontent.com/16020496/55724485-ca7f6f00-5a0b-11e9-83c6-6369d99132d9.png)
![grafik](https://user-images.githubusercontent.com/16020496/55724578-0581a280-5a0c-11e9-88f5-720ee9c982e8.png)
![grafik](https://user-images.githubusercontent.com/16020496/55724669-35c94100-5a0c-11e9-9508-453732900d82.png)
These are just a few examples. The translations at the moment aren't very good German, too. But I'd like to start making them better only after we can have a more flexible word order :)

**Comment by sfahrenholz** [comment]
@Chartman123
which version is installed? 

![image](https://user-images.githubusercontent.com/6977657/55726507-3cf24e00-5a10-11e9-8c28-60da816f2833.png)

**Comment by xet7** [comment]
No reply received from @Chartman123

**Comment by Chartman123** [comment]
It's better in latest 2.60, but still not correct German grammar in all places. I'll try to correct it on transifex as much as possible

**Comment by Chartman123** [comment]
Ok, I adjusted some of the translations. But there are still some issues, where we cannot add a correct German translation.

I'd propose to switch the translation for the rules to the following scheme: Every line in one single translation with placeholders for the drop-down-lists. This way the translation can be adjusted to the grammar rules for each language :-)

**Comment by xet7** [comment]
@Chartman123 

Please add PR to jade files:
https://github.com/wekan/wekan/tree/devel/client/components/swimlanes

and English base translation, that is then translated to all languages by Wekan translators:
https://github.com/wekan/wekan/blob/devel/i18n/en.i18n.json

Thanks!

**Comment by xet7** [comment]
Doh, sorry, I mean Rules jade files:
https://github.com/wekan/wekan/tree/devel/client/components/rules

**Comment by Chartman123** [comment]
@xet7 Sorry, I'm not a programmer ;)
