### ISSUE TITLE
Permanent 100% CPU usage

### ISSUE THREAD

**Issue by duckhawk** [wekan/wekan#2309]
**Server Setup Information**:

* Did you test in newest Wekan?:
Yes, there is fresh wekan in docker-compose.

Wekan Version	v2.55.0
Node version	v8.15.1
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	4.15.0-46-generic
OS Uptime	3 hours, 51 seconds

* Operating System:
Ubuntu 18.04.2

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Docker

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
Proxifying Nginx server

* MongoDB Version:
mongodb-core: 2.0.11

**Problem description**:
There is a 100% cpu load on fresh installation, after 10-15 minutes after start.
In proccesses, it looks like permanent work with mongo, but there is no problems in log, so I can't determine, what wekan doing at this moment.

- *Explain steps how to reproduce*
There is no some specific steps to reproduce, just wait for some time

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*

In browser I see only messages "WebSocket is closed":
9ac30447135983729d8b334aa125ec8d5f338541.js?meteor_js_resource=true:77 WebSocket connection to 'wss://x.x.x.ru/sockjs/660/2x47m7_9/websocket' failed: WebSocket is closed before the connection is established.

- *If using Docker, what does show command `sudo docker logs wekan-app` ?*

Only this:
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 144)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 147)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 150)

**Comment by xet7** [comment]
Please try newest Wekan.

**Comment by xet7** [comment]
Moved to #2294
