### ISSUE TITLE
Loading never stops - accessing public board

### ISSUE THREAD

**Issue by opshh** [wekan/wekan#2311]
## Issue

Add these issues to elsewhere:
- LDAP: https://github.com/wekan/wekan-ldap/issues
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 2.57
* If this is about old version of Wekan, what upgrade problem you have?: no
* Operating System: ubuntu 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: snap
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

Since last Update to Version 2.57 it is not possible to load our ,,public" Board anymore. Loading Animation never stops. This only happens when accessing without credentials.
Under Firefox Console i see these errors

onmozfullscreenerror sollte nicht mehr verwendet werden. 4650a8bedcd0b7e7e40e08fd0535cbf3ac4ee708.js:29:10658
TypeError: Meteor.user(...) is null undefined 4650a8bedcd0b7e7e40e08fd0535cbf3ac4ee708.js:1:6331
TypeError: this.find(...) is undefined
 
When accessing as authenticated User everything works fine.

**Comment by Joe-rchrdsn** [comment]
We have exactly the same version here running V2.60.0 same server setup information as OP.
Strangely some of our public boards with minimal content continue to load.
The below is a screenshot from the chrome console, this error only appears when public boards fail to load.

![2019-04-15 11_53_19-DevTools - swpapp-wekan_b_k4YM84KXFiXCDSDeP_ict](https://user-images.githubusercontent.com/1835676/56127647-8c3b0000-5f75-11e9-8985-d1ffe659b7b7.png)

**Comment by nagaozen** [comment]
Same issue on 2.61.0. I can create new boards, but after the update none of the old boards are loading.

![20190426-wekan](https://user-images.githubusercontent.com/22817/56832399-4702b200-6842-11e9-91dc-af904f5005c1.png)

**Comment by juanluisbaptiste** [comment]
Same issue, I deleted a card on a board and after that the board hangs loading.

**Comment by felixmw** [comment]
Same here. We had to go back to docker image wekanteam/wekan:v2.56 to have the public board access working again.

**Comment by vjrj** [comment]
So if public boards works in `2.56` and not in `2.57` looking the Changelog maybe the bug was introduced by:
https://github.com/wekan/wekan/commit/289f1fe1340c85eb2af19825f4972e9057a86b7a
cc/ @justinr1234

**Comment by felixmw** [comment]
> So if public boards works in `2.56` and not in `2.57` looking the Changelog maybe the bug was introduced by:
> [289f1fe](https://github.com/wekan/wekan/commit/289f1fe1340c85eb2af19825f4972e9057a86b7a)
> cc/ @justinr1234

I am not a programmer but is something missing behind 'memberId'?

**Comment by anmol26s** [comment]
Same issue

**Comment by justinr1234** [comment]
> So if public boards works in `2.56` and not in `2.57` looking the Changelog maybe the bug was introduced by:
> [289f1fe](https://github.com/wekan/wekan/commit/289f1fe1340c85eb2af19825f4972e9057a86b7a)
> cc/ @justinr1234

Shouldn't hurt anything, this is just referencing a passed in variable and wouldn't prevent boards from loading. What would happen if there's no member performing the activity is that this field would be null, which equates to:

`memberId: undefined`

**Comment by justinr1234** [comment]
@opshh can you post any server logs that happen when you try to visit?

**Comment by vjrj** [comment]
I don't see any related server log, but many error/exceptions in js browser console, like:
```
Exception in template helper: hiddenMinicardLabelText
Exception in template helper: limitToShowCardsCount
Exception in template helper: idOrNull
Exception from Tracker recompute function: undefined 
TypeError: Meteor.user(...) is null undefined
```

**Comment by vjrj** [comment]
As Meteor.user() is null, accessing this fails:
https://github.com/wekan/wekan/blob/a33cad0d13c25cc01604802337a920e3975f6365/client/components/lists/listHeader.js#L33 
https://github.com/wekan/wekan/blob/f7e0b837d394d55d66d451c34f43fa8afd357e5b/client/components/cards/minicard.js#L30
https://github.com/wekan/wekan/blob/a97360dcfba2bf1dd1be115dd91dd1dde49ded69/client/components/lists/listBody.js#L160

**Comment by xet7** [comment]
@vjrj 

What webbrowser you use?

Wekan works in Chrome/Chromium/Edge/Chromium Edge/Firefox/Chrome Mobile.

Other webbrowsers are detected wrong, so they get wrong javascript, because of Meteor bug, so they get errors about minicard.

See #2643 and #2656

**Comment by justinr1234** [comment]
@xet7 that isn’t the issue. This is a bug with the code as it isn’t respecting when a user is logged out.

**Comment by xet7** [comment]
Oh OK.

**Comment by vjrj** [comment]
Yes, @justinr1234 is right (by the way @xet7 , I currently use Chromium and/or FirefoxESR from debian stable). Thanks for your work!

**Comment by TheMasterFX** [comment]
Same here, even on the official publich Roadmap: https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license
Tried with Chrome, Edge and IE.

**Comment by xet7** [comment]
I already have fix for this, it's not committed yet, will be in next release.
