### ISSUE TITLE
On every deployment, sending emails does not work until re-saving the password

### ISSUE THREAD

**Issue by neurolabs** [wekan/wekan#2315]
**Server Setup Information**:

* Wekan version:
2.56.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
docker on debian
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
nginx

**Problem description**:
- recorded animated gif
due to technical problems I can't attach to github issues
- *Explain steps how to reproduce*
* have working email setup ("send a test email to yourself" button works)
* upgrade the wekan version
* email does not work ("send a test email to yourself" button does not work, leads to authentication error)
* re-enter password and save
* have working email setup ("send a test email to yourself" button works)

**Comment by maltem-za** [comment]
Although this is not snap-related, [this](https://github.com/wekan/wekan/issues/2375#issuecomment-732773295) may help you to solve the problem.

**Comment by neurolabs** [comment]
I have solved this by not requiring any password to send emails from wekan. @xet7 you can close this issue on my account.
