### ISSUE TITLE
wekan not listening on port 3001

### ISSUE THREAD

**Issue by nicolasbadia** [wekan/wekan#2318]
Hi,

I followed the [guide](https://github.com/wekan/wekan-snap/wiki/Install) to install wekan on debian, but I cannot manage to have it listen on `127.0.0.1:3001`:

```
apt install snapd
snap install wekan
snap set wekan root-url="https://wekan.example.com"
snap set wekan port='3001';
systemctl restart snap.wekan.wekan;
```

This command return nothing: `netstat -tuplen | grep 3000`

And `systemctl status snap.wekan.wekan` return:

```
snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-04-05 19:15:18 CEST; 201ms ago
 Main PID: 27349 (wekan-control)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/snap.wekan.wekan.service
           ├─27349 /bin/bash /snap/wekan/493/bin/wekan-control
           ├─27425 /bin/bash /snap/wekan/493/bin/wekan-control
           └─27427 /bin/bash /snap/wekan/493/bin/wekan-control
```

Any idea of what I may have missed?
Notice that I made all the install in `root`.

**Edit:**
I also have a crazy CPU usage until I do `systemctl stop snap.wekan.wekan`:

<img width="1033" alt="Capture d’écran 2019-04-05 à 20 12 04" src="https://user-images.githubusercontent.com/477089/55648008-68422680-57df-11e9-9aa9-3fe18dce1d21.png">

**Comment by xet7** [comment]
First you set Wekan port to 3001, and the you try to grep port 3000.

**Comment by xet7** [comment]
More info about ROOT_URL and port here:
https://github.com/wekan/wekan/wiki/Settings

**Comment by nicolasbadia** [comment]
Sorry, it was a typo in my message as I also tested for 3000, which actually return:

```
tcp6       0      0 :::3000                 :::*                    LISTEN      111        17479      1212/gitea
```

When I test for port 300**1**, it return nothing. Notice that nginx report this error at each request :

```
2019/04/05 18:23:17 [error] 27676#27676: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 109.190.13.240, server: wekan.exemple.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://127.0.0.1:3001/favicon.ico", host: "wekan.exemple.com", referrer: "https://wekan.gestixi.com/"
```

I saw the Setting page, but it doesn't help. 
Other than that, it does not disturb you that wekan use 100% of my CPU ?

**Comment by xet7** [comment]
CPU issue is at https://github.com/wekan/wekan/issues/2309 , and there has been improvements to CPU usage.

Snap works for me. I don't now are all your snap services running.
```
sudo snap services
```
Also, if there something else running on Wekan port, Wekan can not use it.

**Comment by nicolasbadia** [comment]
`snap services`return this :
```
Service        Startup   Current   Notes
wekan.caddy    disabled  inactive  -
wekan.mongodb  enabled   inactive  -
wekan.wekan    enabled   inactive  -
```
Can you confirm I do not have to enable caddy if I use nginx in front of Wekan.

3001 is not used. I tried another port just to be sure, but still nothing.

It would make sense to me that this issue is related the cpu 100% usage. I will wait for a new release to be available on snap...

**Comment by xet7** [comment]
@nicolasbadia 

Your wekan is not active all. Please try:
```
sudo systemctl enable snap.wekan.mongodb
sudo systemctl enable snap.wekan.wekan
sudo systemctl start snap.wekan.mongodb
sudo systemctl start snap.wekan.wekan
sudo snap start wekan.mongodb
sudo snap start wekan.wekan
```
If still wekan and mongodb are not active, show logs:
```
sudo snap logs wekan.mongodb
sudo systemctl status snap.wekan.mongodb
sudo snap logs wekan.wekan
sudo systemctl status snap.wekan.wekan
```

**Comment by nicolasbadia** [comment]
Sorry, I keep giving you wrong informations... 
I had to stop / disabled it for the 100% cpu issue.
It doesn't work either when the services are actives :
```
Service        Startup   Current   Notes
wekan.caddy    disabled  inactive  -
wekan.mongodb  disabled  active    -
wekan.wekan    disabled  active    -
```

**Comment by xet7** [comment]
You seem to have wekan disabled. I don't know what is conflicting on your system. Usually Wekan is at port 3001 and MongoDB at 27019. Usually reboot + `sudo snap remove wekan` + `sudo snap install wekan` does make it work.

**Comment by xet7** [comment]
I hope you are not trying to run Wekan at OpenVZ or OVH, those have limited kernel permissions so snap does not work, there only way is to build from source.

**Comment by xet7** [comment]
What Debian version are you using?

Is your server running on bare metal, KVM, XEN, VirtualBox or VMWare? Or some cloud like AWS or Azure?

**Comment by xet7** [comment]
For me, Snap works on Debian 9. Debian 10 could be broken sometimes.

**Comment by nicolasbadia** [comment]
I'm running wekan on a Public Cloud OVH instance (OpenStack) on debian 9.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/OVH

I don't know can OVH in any way give permissions to run Snap or Docker.

**Comment by nicolasbadia** [comment]
Weird, snap seem to works fine. I will try from sources. Thanks for pointing this out.

**Comment by xet7** [comment]
@nicolasbadia 

If Snap works, it's better to use it, because it has automatic updates.
