### ISSUE TITLE
Memory leak in Wekan

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2319]
From @chotaire at IRC
```
Apr 5 07:00.37 kanban-app root: Successfully restarted wekan (node.js memory leak)
```
It's aroud 1 GB per day. Unsure when it was introduces but I guess since the last major node.js update. Cloud be anything tho as there are still occasional empty board activity messages and disappearing card activities since the 2.4* screwup. I might have to re-import existing boards maybe?

@bentiss 

Do you see any memory leak in Wekan?

**Comment by chotaire** [comment]
I was going to add this bug report once I have more useful data. For the moment I need to snap restart wekan once a day with about 10 idle users as it would start to consume >1GB of excess memory for no reason and seriously start lagging the VM. I cannot tell if this also happens on fresh boards that were only recently started or re-imported.

**Comment by chotaire** [comment]
![kanban-app memory usage3](https://user-images.githubusercontent.com/9246549/55665031-ac154a00-5838-11e9-9ccb-0f8d86c200ce.jpg)

Obviously this started happening on 22 March, 2018 (snap version), maybe this helps figuring out.

**Comment by therampagerado** [comment]
For me after 4 days, 12 users and ~200 cards node.js is using 1.2  GB of ram and ~60% of the CPU (9 virtual CPUs)

The board is slower, probably to the levels before the recent cache improvements...

The average load is 0,9-1,5 far away from the load when the cache fixes were introduces where I was seeing numbers like 0,3 at most (far far away from anything before hand).

**Comment by therampagerado** [comment]
Can you test the new snap wekan version that includes Node 8.16?

I again have low usage in the range of 0.30-0.15. And only 8% of memory for Node (with 15% when I was experiencing this issue, which is around 1,5 GB). 

There are 2 memory leaks fix in this 8.16 release so probably one of them at least is related?!

**Comment by chotaire** [comment]
Updated. I will have fresh colorful graphs for you guys in two days.

**Comment by chotaire** [comment]
15:18:45 <Chotaire> wekan is still leaking about 100MB of ram within 3-4 hours using v2.61.0 snap.
 15:18:54 <Chotaire> nodejs 8.16

**Comment by rog1fly** [comment]
If leak is whats going on. Sure looks like it's fine to gather information
about how much you can see 👀 so it's able to get it done.

**Comment by BobCashStory** [comment]
same here with v3.49 it take few days to hit the limit of 1Gb

**Comment by xet7** [comment]
@BobCashStory 

I really hope your Wekan is not exposed to public Internet, it most likely has old vulnerable Node.js version. I would recommend everyone to use newest Wekan.

**Comment by xet7** [comment]
This issue is old and outdated. If someone finds memory leaks in newest Wekan, please add a new issue.
