### ISSUE TITLE
UI Bug: card description not edible when description is a link

### ISSUE THREAD

**Issue by JavaZauber** [wekan/wekan#2325]
# Problem

To edit a card description one has to click on the description.
If the description is a hyperlink then by clicking the link opens instead.
Thus the description cannot be edited.

# Workaround

I solved the problem by opening the developer tools and editing the description text to something that isn't a link. I was then able to click and edit the description.

Seen in `Wekan v2.60.0`

**Comment by rinnaz** [comment]
It works if you click on the blank space next to a hyperlink
