### ISSUE TITLE
Feature Request : hide fields

### ISSUE THREAD

**Issue by tcoupin** [wekan/wekan#2327]
First: Wekan is an awesome tool! 👏 

Sometimes, all fields are not necessary and the UI seems overloaded. It would be great if I can hide some fields in board settings (like custom field)

**Comment by zitrusblau** [comment]
Hiding swimlanes would be awesome.

**Comment by xet7** [comment]
Hiding fields is more about roles #1861 

Hide swimlanes #2107

Lists width #1266
