### ISSUE TITLE
Labels don't save

### ISSUE THREAD

**Issue by bcooney** [wekan/wekan#233]
I haven't made any changes to Libreboard, just running it on an Ubuntu server (14.04) stock. Last night I added several labels, but this morning when I restarted the app the labels didn't write/save. Not sure if this is a common issue or just a problem I'm having. 

Edit: clarification: neither the labels that I applied to the cards nor the label names saved.

**Comment by mquandalle** [comment]
That seems weird to me, and I'm certainly unable to reproduce me. Labels change are implemented like any other change by using a mongo query that is persisted on the server. This is exactly the same macanism used to handle every other updates (the entire app mutable state lives in MongoDB).

What may happen is that you make the modification in your browser and you see it reflected in the UI immediately, but if you have some connectivity issue between the client and the server, and you close your browser before the client is able to publish its changes to the server then you will encounter data loses.

We should have some warning indicator in the UI in case the browser is disconnected.

**Comment by atfornes** [comment]
We are facing a similar issue. Only the member who created the wekan can edit the labels. Other users cannot.

We are using an oasis.sandstorm.io wekan.
