### ISSUE TITLE
[bug] image previews disappear when defined in template 

### ISSUE THREAD

**Issue by zitrusblau** [wekan/wekan#2331]
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: v2.60
* Operating System: Ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node Version: from snap
* MongoDB Version: from snap

**Problem description**:

_How to reproduce:_

Create swimlane template => Create list & card in swimlane template => Add image attachment to card in swimlane template (automatically adds image preview in card) => Use created swimlane template in board => Everything is fine => Wait a few minutes => Image previews in cards that came with the swimlane template disappeared.

**Comment by xet7** [comment]
You can click `Add Cover` to add image preview back.

Anyway, this is a bug and seems to happen.
