### ISSUE TITLE
Wekan markdown guide

### ISSUE THREAD

**Issue by shaygover** [wekan/wekan#2334]
Hi,

Is there a markdown guide for wekan? As I understand, there are a lot of flavors out there. Which one does Wekan use?

Thanks

**Comment by xet7** [comment]
@shaygover 

Wekan uses https://github.com/perak/markdown

Please add directly new wiki page about markdown syntax to to https://github.com/wekan/wekan/wiki and add it to wiki menu near features link. Then close this issue. Thanks!

**Comment by shaygover** [comment]
Which means that the github guide is also relevant, right?
https://guides.github.com/features/mastering-markdown/

**Comment by shaygover** [comment]
@xet7 Added https://github.com/wekan/wekan/wiki/Wekan-Markdown
1) Can you verify it's GFM?
2) Where can I use the markdown? I assume the card description is a must but maybe also card name? Anywhere else?

**Comment by xet7** [comment]
@shaygover 

1. I don't know does perak include all of GitHub markdown. Please try those GFM examples, and if there is differences, please add info to that Wekan wiki page. You can also search these Wekan GitHub issues and add list of markdown bugs to wiki.

2. Please add to Wekan wiki page where it works, please test. Maybe it works at some of these, you could test:
- card titles
- card descriptions
- checklist titles
- checklist items
- board titles
- board descriptions
- Custom Fields text fields
- maybe somewhere else

If markdown does not work somewhere, I could try adding it.

Thanks!

**Comment by shaygover** [comment]
I have some bad news:
It's appears that the parser is using v0.3.1 of marked.js (current is 0.6.2). That means it's either support gfm 0.27 or 0.28 (Current is 0.29). I can attempt to build it against a newer version but my knowledge of js and node is 0 so I'll need some way to test it.

**Comment by xet7** [comment]
@shaygover 

Thanks for info, I will try to update marked.js to newer version.

**Comment by xet7** [comment]
@shaygover 

Please try newest Wekan v2.61, it has newest markdown.

**Comment by shaygover** [comment]
So where it works is:
* Card name.
* Board name - Works on board view only. 
* Card description, list and task list.

Board name:
https://i.imgur.com/rNzvIkp.png

**Comment by xet7** [comment]
@shaygover 

It seems [Checklist on markdown does not work yet](https://github.com/wekan/wekan/issues/2419). Do you have ideas howto get it working? Or does it work with some specific syntax?

**Comment by shaygover** [comment]
I only checked basic markup like bold and italics. Other advanced syntax you think it would be good idea to check? I would like to batch check them all

**Comment by xet7** [comment]
@shaygover 

This is maybe shortest syntax check page:
https://guides.github.com/features/mastering-markdown/

Sure there is also more complete specs:
https://marked.js.org/#/README.md
https://github.github.com/gfm/
https://spec.commonmark.org/0.29/

Thanks!
