### ISSUE TITLE
Improve mobile UI: Full width of lists and space before first list

### ISSUE THREAD

**Issue by MelBourbon** [wekan/wekan#2336]
On a mobile browser the UI could be improved by enabling the list to have the full width of the screen (removing the space highlighted yellow in the screen below) and by adding some space before the first list (red circle in the screen) similar to the space between following lists (red line in the screen).

![Screenshot_20190415-220752__01__01](https://user-images.githubusercontent.com/30600002/56162308-f67e8f80-5fcb-11e9-84e9-1445830d2d27.jpg)

**Comment by xet7** [comment]
@hupptechnologies 

Can you look at this? I don't know is empty area useful in any way in mobile view, maybe there has been scrollbar, but anyway on mobile view scrolling is done by hold-dragging anyway.

**Comment by hupptechnologies** [comment]
@xet7  sure. will look into it.

**Comment by hupptechnologies** [comment]
working on it.
