### ISSUE TITLE
Cannot start wekan on mac

### ISSUE THREAD

**Issue by Idonotkonw** [wekan/wekan#2337]
Hello everyone

I am a beginner with wekan. Previously, I used trello, but I want to try wekan.

Enviroment:
Mac book air (4G+256G), Mojave

Aim:
Create local wekan service and used by myself

Jobs I have done:

1) install docker desktop from https://docs.docker.com/docker-for-mac/install/

2) create docker-compose.yml

version: '2'
services:
  db:
    container_name: wekan-db
    image: mongo
    restart: always
    command: mongod --smallfiles --oplogSize 128
    volumes:
      - ~/data/wekan:/data/db
  app:
    container_name: wekan-app
    image: wekanteam/wekan
    restart: always
    ports:
      - "80:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db
      - ROOT_URL=http://localhost
networks:
  default:
    external:
      name: nginx_default

3) enter into yml diretory via terminal and type command

docker-compose up -d

But, but, but
1) There was always errors
2) I can not use wekan via chrome

Any help will be appreciated!

**Comment by stvnw** [comment]
There is a pre-configured setup that you can clone from https://github.com/wekan/wekan-mongodb. Do you have any better results using it?

**Comment by Idonotkonw** [comment]
Hi stvnw

Thank you very much.

However, when I execute "docker-compose up -d"

There is still en error
"Pulling wekan (quay.io/wekan/wekan:master)...
ERROR: Get https://quay.io/v2/: EOF"

How to do next?

**Comment by schoeke** [comment]
Same on a Windows 10 machine.

**Comment by Idonotkonw** [comment]
Encountered new issues

Creating wekan-db ... done
Creating wekan-app ... error

ERROR: for wekan-app  Cannot start service wekan: b'driver failed programming external connectivity on endpoint wekan-app (c195a4bc3385175ac12fb3e55f46166545fe833e492554bc62bff4df3f93a016): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)'

ERROR: for wekan  Cannot start service wekan: b'driver failed programming external connectivity on endpoint wekan-app (c195a4bc3385175ac12fb3e55f46166545fe833e492554bc62bff4df3f93a016): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)'
ERROR: Encountered errors while bringing up the project.

I don't know what are these mean？ what I can do? and how?

**Comment by Idonotkonw** [comment]
I have remove all container, images and volumes and even re-install docker desktop
Problems remain like that.

**Comment by Idonotkonw** [comment]
docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
0abeaef01fca        quay.io/wekan/wekan:master   "node /build/main.js"    8 minutes ago       Created                                 wekan-app
8b65bb83f221        mongo:3.2.21                 "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        27017/tcp           wekan-db

docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
quay.io/wekan/wekan   master              af1dd2e729b5        9 days ago          701MB
mongo                 3.2.21              fb885d89ea5c        5 months ago        300MB

docker volume ls
docker volume ls
DRIVER              VOLUME NAME
local               c44543aada97bdb708fcad01e922aa7a203cf263b5bee79b6b62a9b2dfddbb1e
local               wekan-mongodb_wekan-db
local               wekan-mongodb_wekan-db-dump

why there are three volumes, the first one is what?

**Comment by xet7** [comment]
@Idonotkonw 

> starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)'

Your port 80 is in use. docker-compose.yml uses port 80 by default for Wekan:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L149

You see what containers are running at what ports with:
```
docker ps
```

You need to change to other port if you have Nginx or some other webserver at port 80.

You also need to setup root url:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L164
https://github.com/wekan/wekan/wiki/Settings

And register first user that will become admin:
https://github.com/wekan/wekan/wiki/Adding-users

**Comment by xet7** [comment]
I did a moment ago test with default unchanged docker-compose.yml at https://github.com/wekan/wekan using:
```
docker-compose up -d
```
and it did bring Wekan to http://localhost.

I do also use start.sh script at https://github.com/wekan/docker-cleanup-volumes to delete all docker data on Linux, so that any previous docker data does not prevent new Wekan install.

On Windows when using Docker for Windows, you need to make sure you are using Docker Linux containers. Sometimes when updating Docker for Windows, Docker changes to Docker Windows containers, and if switching back to Linux containers does not work, you need to remove Docker and reinstall Docker and Wekan.

If Docker does not work well enough on Mac or Windows, it's also possible to install from source at Mac and Windows Subsystem for Linux:
- https://github.com/wekan/wekan/wiki/Mac
- https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

If someone still has problems with this, please reopen or add comment to this issue.
