### ISSUE TITLE
Performance optimization: Archived data loading

### ISSUE THREAD

**Issue by nerminator** [wekan/wekan#2338]
Opening a board page with 20 non-archived cards and 150 archived cards take up to 6-7 seconds time.
But during board opening if we subscribe only the non-archived cards,lists,swimlanes, it only takes 2-3 seconds to load the whole page. (I tried it on my local standalone version)
The client can subscribe the archived data when it is needed. For example when the user clicks on search or archive buttons.

Considering the fact that the number of archived cards will continue to increase throughout the lifecycle of a project, the time needed to load the page will also increase. Unlike archived cards, the number of non-archived cards will remain in a reasonable count.

I am new to Wekan development environment, so I am not quite sure if this is a correct approach. I can submit this change if one of the experienced Wekan contributors think that this may be a good idea.

**Comment by xet7** [comment]
If you don't need archived cards, you can cleanup them:
https://github.com/wekan/wekan-cleanup

Empty Arhive feature is not done yet:
https://github.com/wekan/wekan/issues/1625

It would be also possible develop feature to move archives cards to other board, so they would not be loaded:
https://github.com/wekan/wekan/issues/1996

Wekan also has [infinite scroll so that only visible cards are loaded](https://github.com/wekan/wekan/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+infinite), so maybe also archived cards etc could have infinite scroll? @bentiss what do you think?

@nerminator Do you mean some of the above, or something else?

**Comment by therampagerado** [comment]
I would like to see a rule for moving them to another board. That way loading the working board is fast but the moving is tedius at the moment. They have to be moved one by one...

**Comment by xet7** [comment]
Related #1704 and #2155 and #2340

**Comment by nerminator** [comment]
I don't think that moving all cards is necessary. On board creation the code subscribes to all cards:
In client [boardbody.js](https://github.com/wekan/wekan/blob/devel/client/components/boards/boardBody.js) onCreate method:
```   const handle = subManager.subscribe('board', currentBoardId);
      Tracker.nonreactive(() => {
        Tracker.autorun(() => {
          this.isBoardReady.set(handle.ready());
```
This code waits all data to be loaded from server to client to set isBoardReady. This data contains all the archived and non-archived board data including cards, checklists, subtasks, attachments, comments, ... Until isBoardReady is true spinner is displayed in jade file. 

And in server side, subscribing to a board publishes all the board elements including archived ones to the server:
server [boards.js](https://github.com/wekan/wekan/blob/devel/server/publications/boards.js)


```
 Meteor.publishRelations('board', function(boardId) {
 this.cursor(Boards.find({
    _id: boardId,
    archived: false,
    // If the board is not public the user has to be a member of it to see
    // it.
    $or: [
      { permission: 'public' },
      { members: { $elemMatch: { userId: this.userId, isActive: true }}},
    ],
  // Sort required to ensure oplog usage
  }, { limit: 1, sort: { _id: 1 } }), function(boardId, board) {
    this.cursor(Lists.find({ boardId }));
    this.cursor(Swimlanes.find({ boardId }));
    this.cursor(Integrations.find({ boardId }));
    this.cursor(CustomFields.find({ boardIds: {$in: [boardId]} }, { sort: { name: 1 } }));
   // Gather queries and send in bulk
    const cardComments = this.join(CardComments);
    cardComments.selector = (_ids) => ({ cardId: _ids });
    const attachments = this.join(Attachments);
    attachments.selector = (_ids) => ({ cardId: _ids });
    const checklists = this.join(Checklists);
    checklists.selector = (_ids) => ({ cardId: _ids });
    const checklistItems = this.join(ChecklistItems);
    checklistItems.selector = (_ids) => ({ cardId: _ids });
    const parentCards = this.join(Cards);
    parentCards.selector = (_ids) => ({ parentId: _ids });
    const boards = this.join(Boards);
    const subCards = this.join(Cards);

    this.cursor(Cards.find({ boardId: {$in: [boardId,  board.subtasksDefaultBoardId]}}), function(cardId, card) {
      if (card.type === 'cardType-linkedCard') {
        const impCardId = card.linkedId;
        subCards.push(impCardId);
        cardComments.push(impCardId);
        attachments.push(impCardId);
        checklists.push(impCardId);
        checklistItems.push(impCardId);
      } else if (card.type === 'cardType-linkedBoard') {
        boards.push(card.linkedId);
      }
      cardComments.push(cardId);
      attachments.push(cardId);
      checklists.push(cardId);
      checklistItems.push(cardId);
      parentCards.push(cardId);
    });

    // Send bulk queries for all found ids
    subCards.send();
    cardComments.send();
    attachments.send();
    checklists.send();
    checklistItems.send();
    boards.send();
    parentCards.send();

```

This publish method can be modified to take a parameter for isArchive and publish only archived or non-archived data:
 ```
Meteor.publishRelations('board', function(boardId, isArchived) {
...
    this.cursor(Lists.find({ boardId: boardId, archived: isArchived }));
    this.cursor(Swimlanes.find({ boardId:boardId,  archived: isArchived  }));
...
    parentCards.selector = (_ids) => ({ parentId: _ids, archived: isArchived});
...
    subCards.selector = (_ids) => ({ archived: isArchived });
    this.cursor(Cards.find({ boardId: {$in: [boardId,  board.subtasksDefaultBoardId]},archived: isArchived}), function(cardId, card) {
....
```


And in the client board on created we can call subscribe to board with isArchived=false.
Then in the sidebarArchives.js on page creation and during search  subscribe to board will be called with isArchived=true. So if the user clicks on archive archived data will also be subscribed. But since the operation will be divided as archived and non-archived, the first board load would be much more faster.

There is also a whole board subscription in boardList.js  for hasOvertimeCards and hasSpentTimeCards. Here subscription will be done with isArchived=false. Actually it would be much more better to subscribe only these 2 fields here and not the whole board data but that is a subject of another issue.

I've done these changes on my local server and it is faster now. The functionality is also working without any loss but I've to test more.

**Comment by xet7** [comment]
@nerminator 

Please add PR of your code changes to Wekan. Thanks!

**Comment by bentiss** [comment]
> Wekan also has infinite scroll so that only visible cards are loaded, so maybe also archived cards etc could have infinite scroll? @bentiss what do you think?

This could be interesting to have, indeed, but I am not sure I'll have the time to work on this feature.

And for the record, I also think loading the archived cards when we need them (when we pop up the archive folder) would greatly help in this situation.

**Comment by nerminator** [comment]
Thanks for the feedback. I will try to send PR in 2 weeks @xet7 .
