### ISSUE TITLE
Authentication: Google/GitHub/OAuth

### ISSUE THREAD

**Issue by brodock** [wekan/wekan#234]
I've seen some issues here that could be solved by using meteor package: https://atmospherejs.com/meteor/accounts-base.

I will list the related issues that I believe could benefit from it: 

https://github.com/libreboard/libreboard/issues/120
https://github.com/libreboard/libreboard/issues/119
https://github.com/libreboard/libreboard/issues/212

Other related packages that can provide the "Enterprise grade authentication":
https://github.com/typ90/meteor-accounts-ldap (authenticate agains ldap)
https://atmospherejs.com/meteor/accounts-google (authenticate in a google apps domain organization)
https://atmospherejs.com/meteor/accounts-github (authenticate in a github organization)
https://atmospherejs.com/meteor/accounts-oauth (maybe useful for gitlab)

**Comment by rysiekpl** [comment]
THere is a meteor LDAP accounts plugin available: https://atmospherejs.com/typ/accounts-ldap

**Comment by SirCmpwn** [comment]
:+1: I would like to be able to plug wekan into arbitrary oauth providers.

**Comment by SirCmpwn** [comment]
I started looking through the code hoping to implement this, but I can't actually find any of the code that deals with the registration flow. Help?

**Comment by olberger** [comment]
Would like to see this on the Roadmap... @mquandalle any hope ?

**Comment by Prezto** [comment]
Any progress on this? I really need it badly and do not want to use Kanboard or something like that. Wekan looks much better to customers. Can i help with coding? if so, Is there already some code to start with or should i start from scratch?

I can always contribute if you need it.

**Comment by ocdtrekkie** [comment]
@Prezto While the solution is not free (but is open source), Sandstorm.io recently launched their LDAP/SAML feature as "Sandstorm for Work". Their free software, of course, already supports Google and GitHub based login. Wekan runs pretty well as a Sandstorm app.

Not a solution to the issue, but an option if you're unaware.

**Comment by Prezto** [comment]
I work in a company where everything is firewalls in segments and security is the highest priority. So hosted is not an option.

Thank you for advising. I will see what can do with the code.

Verzonden met mijn Windows Phone
________________________________
Van: Jacob Weisz<mailto:notifications@github.com>
Verzonden: ‎4/‎10/‎2016 10:09 PM
Aan: wekan/wekan<mailto:wekan@noreply.github.com>
CC: Dany Henriquez<mailto:dany.henriquez@outlook.com>
Onderwerp: Re: [wekan/wekan] plugable accounts backend (#234)

@Prezto While the solution is not free (but is open source), Sandstorm.io recently launched their LDAP/SAML feature as "Sandstorm for Work". Their free software, of course, already supports Google and GitHub based login. Wekan runs pretty well as a Sandstorm app.

Not a solution to the issue, but an option if you're unaware.

---

**Comment by ocdtrekkie** [comment]
@Prezto Sandstorm for Work is designed to be self-hosted on your internal network. They offer a hosted solution as well, but it wasn't what I was suggesting.

**Comment by Prezto** [comment]
Then i understood you wrong. My apologies. We already use KVM. I will introduce this idea.

Thank you

**Comment by pierreozoux** [comment]
Any news on that, it would be nice indeed.
@mquandalle  as @brodock is it just adding a meteor package? In this case we can do it on our side?

Thanks for your help!

**Comment by NatsumiHoshino** [comment]
It's been almost a year since this issue is opened, is there some ETA or progress on it? I'm looking into using Wekan in a non-profit I'm part of and having Google Apps login would be extremely useful. Alternatively, what would be the required work to implement it myself?

**Comment by tareko** [comment]
Also an absolute need for me. For others who can't use something without generic OAuth2, I asked (very nicely) and Frédéric Guillot (@fguillot) added it to kanboard.net

**Comment by NatsumiHoshino** [comment]
@tareko I played around with the source code on my fork and managed to add Google Apps authentication half a year ago. It wasn't that complicated (even for a beginner) but in the end I went for something else. The mess I wrote is still there if you want to take a look: https://github.com/NatsumiHoshino/gackt-wekan/commit/72bc6c15f13e1101fd9813fd8e6c4c4bcb3a9096

In a nutshell, I simply removed the meteor package `accounts-password`, added in `accounts-google` (or whatever they may be named nowadays), edited some config files and went crazy on the trial-and-error.

**Comment by tareko** [comment]
What is the other software you ended up using?

**Comment by xet7** [comment]
LDAP moved to #119

**Comment by xet7** [comment]
OAuth2 at https://github.com/wekan/wekan/pull/1578
