### ISSUE TITLE
使用snap安装wekan相关问题

### ISSUE THREAD

**Issue by chenghongxi** [wekan/wekan#2344]
您好，想咨询使用snap方式安装wekan，
     有mongodb，wekan等一些程序的安装位置么？

**Comment by chenghongxi** [comment]
@xet7

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/devel/README.md#requirements

https://github.com/wekan/wekan-snap/wiki/Install

Default: node port 3001, mongodb port 27019
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

https://github.com/wekan/wekan/wiki/Settings

/var/snap/wekan/common/Caddyfile
https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

https://github.com/wekan/wekan/wiki/Adding-users

https://github.com/wekan/wekan/wiki/Backup

**Comment by chenghongxi** [comment]
1.想知道wekan的主程序文件存在哪里，是在如下的common里么？？

2.这几个数字的文件夹都是什么作用

3.想了解下wekan的运行方式，如果有这种开发者文档，解释下运行方式，snap下wekan的程序框架更好了。以便更了解wekan
------------------ 原始邮件 ------------------
发件人: "Lauri Ojansivu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 凌晨1:39
收件人: "wekan/wekan"<wekan@noreply.github.com>;
抄送: "小白"<422459409@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wekan/wekan] 使用snap安装wekan相关问题 (#2344)




https://github.com/wekan/wekan/blob/devel/README.md#requirements
 
https://github.com/wekan/wekan-snap/wiki/Install
 
Default: node port 3001, mongodb port 27019
 https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys
 
https://github.com/wekan/wekan/wiki/Settings
 
/var/snap/wekan/common/Caddyfile
 https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config
 
https://github.com/wekan/wekan/wiki/Adding-users
 
https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
@chenghongxi 

Also see all repos at https://github.com/wekan

1. Source Linux/Mac/Windows Subsystem for Linux Ubuntu
- https://github.com/wekan/wekan/wiki/Source
- https://github.com/wekan/wekan
- `./rebuild-wekan.sh` 1 install dependencies 2 build wekan
- `./start-wekan.sh` where `cd .build/bundle` [here](https://github.com/wekan/wekan/blob/devel/start-wekan.sh#L22) and `node main.js` [here](https://github.com/wekan/wekan/blob/devel/start-wekan.sh#L308).
- Mac https://github.com/wekan/wekan/wiki/Mac

2. https://github.com/wekan/wekan/wiki/Directory-Structure

3. https://github.com/wekan/wekan/wiki/Developer-Documentation

## Snap Linux
https://snapcraft.io
https://docs.snapcraft.io/snap-documentation/3781
```
wekan/snapcraft.yaml
wekan/snap-src/
wekan/snap/
```
## Docker Linux/Mac/Windows
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows
https://github.com/wekan/wekan/wiki/Docker
```
wekan/Dockerfile
wekan/docker-compose.yml
```
## Sandstorm / Linux
- https://sandstorm.io , install https://sandstorm.io/install
- https://sandstorm.io/news/2017-02-06-sandstorm-returning-to-community-roots
- https://github.com/wekan/wekan/blob/devel/releases/release-sandstorm.sh
- https://docs.sandstorm.io/en/latest/
- https://github.com/sandstorm-io/sandstorm
- https://sandstormports.github.io
