### ISSUE TITLE
Docker: Can not finish deploy

### ISSUE THREAD

**Issue by Idonotkonw** [wekan/wekan#2363]
Hi everyone

My environment
Mac air 4G + 256G + mojave

Aim
Deploy wekan for private use

Problem

I have cloned this repo and type with Detached mode

mangodb and wekan had pulled

But at end, there is problems

"ERROR: for wekan-app  Cannot start service wekan: b'driver failed programming external connectivity on endpoint wekan-app (e49f798f42e5b0cb1b67d66b6759ffb43dd7e94a3bb1108ed9260ef6a17b0f8e): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)'

ERROR: for wekan  Cannot start service wekan: b'driver failed programming external connectivity on endpoint wekan-app (e49f798f42e5b0cb1b67d66b6759ffb43dd7e94a3bb1108ed9260ef6a17b0f8e): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)'
ERROR: Encountered errors while bringing up the project."

I don't know what are they mean? How I can do?

Any help will be appreciated

Thank you

**Comment by xet7** [comment]
@Idonotkonw 

You have already some webserver at port 80 that is in use. So you need to stop that first, or change Wekan to run at some other port than 80:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L149

Also set ROOT_URL:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L164
https://github.com/wekan/wekan/wiki/Settings

And add users:
https://github.com/wekan/wekan/wiki/Adding-users

If you still have problems, please reopen this issue.
