### ISSUE TITLE
OAuth2 rocketchat internal server error

### ISSUE THREAD

**Issue by frozenbanana** [wekan/wekan#2368]
## Issue

I followed the instruction on https://github.com/wekan/wekan/wiki/OAuth2 until step Snap - 5.3.

Then I get the error message when trying to use `Open with Oidc` button `Internal server error`. For a very short moment my avatar picture from rocket chat is being presented and options for authorization flashes by before closing.

The error message says: `Internal server error` with no further details. I have tried the to snoop for lead in the browser tools but with no success. 

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: latest
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux Ubuntu 18.04 (Droplet on Digital Ocean)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

**Comment by xet7** [comment]
```
sudo snap set wekan debug='true'
```
Then click Oidc button, and then:
```
sudo snap logs wekan.wekan
sudo systemctl status snap.wekan.wekan
```

**Comment by xet7** [comment]
Also, you need to first login to RocketChat, and then on another browser tab login to Wekan, to use RocketChat login to Wekan.

**Comment by xet7** [comment]
Hmm, just a moment I'll test does this work. There have been changes to Wekan Oidc features.

**Comment by xet7** [comment]
I fixed wiki page settings.
https://github.com/wekan/wekan/wiki/OAuth2

**Comment by frozenbanana** [comment]
Thank you for taking the time. I followed the steps and made a file called `auto.sh` and restarted both rocketchat and wekan. I logged in to rocketchat and then wekan. Same error appears. The log said:

```
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   email: 'myemail@adomain.com',
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   email_verified: false,
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   department: '',
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   birthdate: '',
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   preffered_username: 'cooluser',
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   updated_at: '2019-04-21T14:32:45.277Z',
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   picture: 'https://rednower.tk/avatar/cooluser' }
Apr 21 14:32:45 wekan-server wekan.wekan[28545]: {"line":"431","file":"oauth.js","message":"Error in OAuth Server: id is not defined","time":{
Apr 21 14:32:45 wekan-server wekan.wekan[28545]: Exception while invoking method 'login' { stack: 'ReferenceError: id is not defined\n    at O
Apr 21 14:32:45 wekan-server wekan.wekan[28545]:   source: 'method' }
``` 

Where can I define the id?

**Comment by xet7** [comment]
@frozenbanana 

https://github.com/wekan/wekan/wiki/OAuth2#4-add-wekan-settings
```
sudo snap set wekan oauth2-id-map='preffered_username'
sudo snap set wekan oauth2-username-map='preffered_username'
sudo snap set wekan oauth2-fullname-map='preffered_username'
sudo snap set wekan oauth2-email-map='email'
```

**Comment by frozenbanana** [comment]
yes, this is all included in the auto.sh file.
This is my content of auto.sh:
```
sudo snap set wekan oauth2-enabled='true'
sudo snap set wekan oauth2-client-id='<myid>'
sudo snap set wekan oauth2-secret='<mysecret>'
sudo snap set wekan oauth2-server-url='https://mydomain.com/'
sudo snap set wekan oauth2-auth-endpoint='oauth/authorize'
sudo snap set wekan oauth2-userinfo-endpoint='oauth/userinfo'
sudo snap set wekan oauth2-token-endpoint='oauth/token'
sudo snap set wekan oauth2-id-map='cooluser'
sudo snap set wekan oauth2-username-map='cooluser'
sudo snap set wekan oauth2-fullname-map='cooluser'
sudo snap set wekan oauth2-email-map='myemail@adomain.com'
```
I ran it, restarted my server, with same result.

**Comment by xet7** [comment]
@frozenbanana 

Yes, it does not work, because you changed `preffered_username` to `cooluser`. You should not change anything in those mappings.

**Comment by xet7** [comment]
@frozenbanana 

You can only change client-id, secret, and server-url. Not others.

**Comment by xet7** [comment]
Actually, my bad. I need to document better what can be changed.
