### ISSUE TITLE
User information not loading from Keycloak

### ISSUE THREAD

**Issue by boardfish** [wekan/wekan#2369]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: Latest Docker container
* If this is about old version of Wekan, what upgrade problem you have?: N/A
* Operating System: CentOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): `jwilder/nginx-proxy`
* Node Version: ??
* MongoDB Version: 3.2.21
* ROOT_URL environment variable http(s)://wekan.example.com

**Problem description**:

User is able to log in via Keycloak, but when logged in, their Full Name, Username, Initials and Email are not set or shown within Wekan. Relevant environment variables are set as follows:

```
      - OAUTH2_ID_MAP=email
      - OAUTH2_USERNAME_MAP=email
      - OAUTH2_FULLNAME_MAP=name
      - OAUTH2_EMAIL_MAP=email
```

It's of note that the schema for the `userinfo` endpoint is as follows:

```
{"sub":"<user ID from Keycloak>","email_verified":true,"name":"Simon Fish","preferred_username":"boardfish","given_name":"Simon","family_name":"Fish","email":"si@mon.fish"}
```

**Comment by xet7** [comment]
@boardfish 

What debug logs you get?
https://github.com/wekan/wekan/wiki/Keycloak

**Comment by boardfish** [comment]
Closing, stale.

**Comment by xet7** [comment]
@boardfish 

Is this now fixed?

**Comment by boardfish** [comment]
I don't believe so, but it's been a while since I've used this, so I'm closing the issue to save both sides the trouble.
