### ISSUE TITLE
When there are many boards on the header the UI gets ugly

### ISSUE THREAD

**Issue by nata-g** [wekan/wekan#237]
Adding many boards on the header makes the boards overflow in to to the UI below. Probably the additonal boards can be hidden on some kind of a dropdown

![image](https://cloud.githubusercontent.com/assets/203255/9397011/9ef4ab9a-474d-11e5-9114-2e07950b6c7a.png)

**Comment by kadishmal** [comment]
The suggestion is to group the trailing items into the last "More" menu. Would be also nice to have this list sorted based on frequency of usage or allow users to customize the order according to their wish.
