### ISSUE TITLE
Keycloak authentication failing at retrieving userinfo

### ISSUE THREAD

**Issue by primetoxinz** [wekan/wekan#2370]
## Issue
**Server Setup Information**:
![](https://img.primetoxinz.com/images/img-2019-04-21-141423.png)

**Oauth2  configuration**:
```
      - OAUTH2_USERNAME_MAP=preferred_username
      - OAUTH2_ID_MAP=preferred_username
      - OAUTH2_FULLNAME_MAP=given_name
      - OAUTH2_EMAIL_MAP=email
```

**Problem description**:
Authentication to Keycloak fails with the following error logs:
```
{"line":"431","file":"oauth.js","message":"Error in OAuth Server: Failed to get token from OIDC OAUTH2_SERVER_URL/auth/realms/master/protocol/openid-connect/token: connect ETIMEDOUT REDACTED_IP:443","time":{"$date":1555870250754},"level":"warn"}

{"line":"431","file":"oauth.js","message":"Error in OAuth Server: Failed to fetch userinfo from OIDC OAUTH2_SERVER_URL/auth/realms/master/protocol/openid-connect/userinfo: connect ETIMEDOUT REDACTED_IP:443","time":{"$date":1555871128579},"level":"warn"}
```

**Comment by xet7** [comment]
Docker logs?

https://github.com/wekan/wekan/wiki/Keycloak#debugging-if-docker-oidc-login-does-not-work

**Comment by primetoxinz** [comment]
As the logs have lots of personal information is this the largest redacted snippet that appears relevant:
https://gist.github.com/primetoxinz/cb5bb38c77f326572e881fb50122f9b8

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/2955
