### ISSUE TITLE
Mobile UI: Center cards in list view

### ISSUE THREAD

**Issue by MelBourbon** [wekan/wekan#2371]
After you made such a great job with the last improvement of the mobile UI I have another one.

On mobile browsers (Firefox as well Chrome) cards in the list view are not centric. As you can see on the screen (yellow) the left margin is bigger than the right. Either increase right margin or move card more left.

In addition the space before the first card could be increased too (red line).

![Screenshot_20190421-221458__01__01](https://user-images.githubusercontent.com/30600002/56475072-849ebe00-6483-11e9-8383-7101b5330f93.jpg)

**Comment by xet7** [comment]
@hupptechnologies 

Can you look at this?
