### ISSUE TITLE
Sandstorm: Restoring board from archive does archive some other board

### ISSUE THREAD

**Issue by cromo** [wekan/wekan#2373]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Latest available on Sandstorm.
* Wekan version: 2.61.0~2019-04-20
* Operating System: Ubuntu Server 16.04 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Sandstorm

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek* - can't right now, I'll see about doing this this evening.

Recent Wekan releases on Sandstorm allow multiple boards per grain, so I was trying to consolidate some of my boards by exporting from one and importing into the other.

I found the hamburger menu in the top right, then the settings gear in the shelf, and the import option there. After going to the import screen, I saw a notice saying that it would overwrite the current board and I cancelled the import because I wanted to keep my current board. So I went to the "All Boards" page, clicked "Add Board", then "Import" and followed the steps there. To my chagrin, this wiped out the board I just came from instead of making a new board with the imported content. Unless there's a way for me to undo my import, I just lost my main todo board 😭 

Reproduction steps:
- Export a Wekan board from another sandstorm grain
- Open the target Wekan board
- Click "All Boards" in the top left
- Click "Add Board" tile
- Click "Import" in the menu that pops up
- Click "From previous export"
- Copy the contents of the exported board's JSON file and paste it into the text box
- Click "Import"

Expected behavior:
A new board is created with the imported content

Observed behavior:
The last focused or main board (only tried once; don't know which it is) of the grain is overwritten by the import, causing data loss.

**Comment by cromo** [comment]
Upon further inspection, I found the "overwritten" board in the list of archived boards and unarchived it - it looks like it's as I left it before the import, but now the imported board is gone.

**Comment by cromo** [comment]
And then I found the imported board was archived, so I unarchived it to see if it would mess with the board it overwrote - it came back and yet another board was moved to the archive. It looks like there are some issues with importing and unarchiving boards.

**Comment by xet7** [comment]
@cromo 

Yes, that is from time when there was no multiple boards, so importing new did move current one to archive. I have not yet looked at code where this is done.

So the question is, do you have all your boards? Or did you lose some board? I recommend you download your wekan grains, and also export your boards, before doing more experiments with important data.

**Comment by cromo** [comment]
The last board it moved to the archive was a mostly blank board that I created after I thought I lost my main board that I'm okay with losing, so I have all the data I care about, even if there is still one archived/sorta-deleted board.

I'll be messing with new, unimportant grains to see about recording this behavior.

**Comment by cromo** [comment]
Welp, I just tried to recreate the issue to record it with completely fresh grains and it didn't happen this time. I wonder if it had something to do with opening the import dialog from the board first before backing out and doing it from the add board dialog?

**Comment by xet7** [comment]
Hmm, I don't know, I think it's the same import board code that is run from both menus.

**Comment by xet7** [comment]
> The last board it moved to the archive was a mostly blank board that I created after I thought I lost my main board that I'm okay with losing, so I have all the data I care about, even if there is still one archived/sorta-deleted board.
> 
> I'll be messing with new, unimportant grains to see about recording this behavior.

What is that archived/sorta-deleted board? Can you restore it?

**Comment by xet7** [comment]
Anyway, moving this to #2220

**Comment by cromo** [comment]
It was a new todo board that was completely empty other than the todo/doing/done columns. I'm afraid to restore it because restoring the other boards (whichever one was archived) caused another board to become archived, and I want to keep all the boards that are currently unarchived.

**Comment by xet7** [comment]
@cromo 

Yes, that board could be the first Wekan board that could cause some other to be archived.

You could try downloading and uploading that grain, and try it in 2nd grain.
