### ISSUE TITLE
History of Comments only shows 20 comments max

### ISSUE THREAD

**Issue by mpathiuk** [wekan/wekan#2377]
## Issue

I have a very busy card with many comments and checklist items on it for the last 5 months. Tried to check the history and I can see only comments up to 2 months ago. No comments visible after that.

**Server Setup Information**:

* Did you test in newest Wekan?:
Yes, Docker Wekan latest, updated last week
* Wekan version: Docker Wekan latest 
* Operating System: Debian on Google compute cloud
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):Nginx

**Problem description**:
When I open a card with 4 month history of comments and scroll down (both with system messages hidden and not hidden), it loads one more scroll section worth of comments and I don't get the full history of comments after that. Scrolling down after that does not show more comments. This is replicated on mac Chrome/safari and win10 chrome.

This is a screenshot of all history I can see, there is nothing showing after 2 months, and we have been working on it daily since January (4 months). Ignore the red squares, that's me redacting our company specific tasks in the comments.

<img width="592" alt="Screenshot 2019-04-24 at 11 19 38 AM" src="https://user-images.githubusercontent.com/10285937/56635361-ed07be00-6682-11e9-8fb5-7edd82327a1e.png">

- *Explain steps how to reproduce*
Make a card with 20 or more comments. When you come to the card and scroll down, one section of history is added, but continuing to scroll does not show the full history.

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
Nothing out of the ordinary

**Comment by rjevnikar** [comment]
Do you know what version this board was created in? Does it happen on all boards or just some?
This might be related to #2316

**Comment by mpathiuk** [comment]
The version was the latest version available on docker on 15th December 2018. Is there a way to see all versions as I can only check the current version after last week's upgrade.

I only have 1 board so I can't see if this has affected more than one board.

**Comment by rjevnikar** [comment]
There isn't a limit as far as I've found - I have cards that have a count of 4 comments and I can see none when I open the card.

**Comment by mpathiuk** [comment]
Did you also update recently? Perhaps it's an update issue.

I'm not mongo savvy so I don't know how I can recover those old comments, we need them soon though as this is blocking our work :(

**Comment by rjevnikar** [comment]
Yes, I've upgraded a few times, so can't pinpoint when the change happened.
The comments are still in the database (which is why the counts on the mini cards are accurate), they're just not being displayed.

From all the cards I've checked, the swimlane, board and list IDs all appear to be fine.

**Comment by mpathiuk** [comment]
I need to recover some comments. Are there any docs or instructions for how I can see them in the DB? I'm not a developer, just an avid user but I have ssh access to the server. Someone else set up our Wekan instance.
Docker and mongo.

**Comment by rjevnikar** [comment]
querying a live database isn't ideal in my mind.
You'd have to first get the cardID, then get all the comments for that ID.
Something like:
`db.cards.find({"title":"Card Title"}).pretty()
db.card_comments.find({"cardId":"value"}).pretty()`

Better yet, if we could compare the code from v1.92 to the current (v2.65) it might be easier to spot what changed. Unfortunately, right now I don't have time - hopefully by the end of the week.

**Comment by xet7** [comment]
@mpathiuk 

You can download card comments this way:

```
ssh user@yourserver.com
docker exec -it wekan-db bash
mongo
mongoexport --db wekan --collection card_comments --out card_comments.json
exit
docker cp wekan-db:/card_comments.json .
exit
scp user@yourserver.com:/home/user/card_comments.json .
```

**Comment by xet7** [comment]
More Docker related backup commands:
https://github.com/wekan/wekan/wiki/Backup

**Comment by rjevnikar** [comment]
@xet7 do you know of a fast way of comparing code between versions?

**Comment by xet7** [comment]
@rjevnikar 

Well, for example browse commits of each version at GitHub:
https://github.com/wekan/wekan/commits/devel

**Comment by mpathiuk** [comment]
I did some more checking, wekan cards are now showing only 20 comments. If I add a new comment, then the oldest comment is no longer visible. 

I made a new test card and then added 20 comments. When I added the 21st comment, the first comment was no longer visible.

<img width="491" alt="Screenshot 2019-04-25 at 10 32 29 AM" src="https://user-images.githubusercontent.com/10285937/56710811-85ff0d80-6745-11e9-933a-4c2b1b70e0b7.png">

**Comment by mpathiuk** [comment]
From https://github.com/wekan/wekan/blob/da3edb35ccf8a29bd6568b8b0445fdc1d6113b19/client/components/activities/activities.js

It looks like the loading of a page of activities is limited to 20 and then locked/unlocked if a new page is to be loaded. Is it possible the loadNextPageLocked is stuck at true?

**Comment by rjevnikar** [comment]
An additional factor I've found, is that if you are using the archiveActivities.js script (https://github.com/wekan/wekan-cleanup/blob/master/Javascript/archiveActivities.js) comments that are older than your archive date, do not appear on the card, but do appear on the mini-card count.

**Comment by lime918** [comment]
present in v3.29

**Comment by rjevnikar** [comment]
The ability to scroll and pull/see more data works in the People screen in the Admin Panel, so I did a quick comparison of peopleBody.js and activities.js, and didn't see any differences that would explain why scrolling to see more users works and scrolling to see more activities doesn't. 

Am I on the right track? Or does anyone have other ideas as to where this bug could be?

**Comment by xet7** [comment]
@rjevnikar 

In general, all scolling should use [Infinite Scroll](https://github.com/wekan/wekan/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+infinite+scroll) to show only visible ones. Infinite scroll is not yet added to every part of Wekan, so there is some code differences somewhere. You are on the right track. Thanks!

**Comment by xet7** [comment]
Moved to #2934
