### ISSUE TITLE
some changes are not persistent , Labels / Members

### ISSUE THREAD

**Issue by andyprv** [wekan/wekan#2381]
some changes are not persistent , Labels / Members

Adding Labels or Members are shown and reported , but after side reload (F5) , the changes are
gone...
But still shown in the reports on the right side.  

Wekan 2.64 Running on Docker 

after "downgrading" to V2.48 , still the same Problem.

MongoDB  size around 4Gb.

any Ideas what cause that ?

**Comment by andyprv** [comment]
# help ?

**Comment by shaygover** [comment]
Labels: Check to see if you have admin permissions on the board.

**Comment by xet7** [comment]
Yes, only board admin can currently edit those.

Moved to #2113

**Comment by andyprv** [comment]
I don't wont to change the Label , I wonna use it ..

That was working till the last upgrade , now It's not working anymore , even after "Downgrade" 
to the last running Version .

 
You can se that the activity on the right get stored / updatet , but the Lables  just disappear by them selfe.


![wekan_Lables](https://user-images.githubusercontent.com/36567942/56906127-e671b000-6aa1-11e9-9796-a44ae3a2a476.gif)

**Comment by andyprv** [comment]
Fixed !    by removing all webhooks !
