### ISSUE TITLE
Question: Backup snap, which to use?

### ISSUE THREAD

**Issue by sh2515** [wekan/wekan#2382]
Looking at the backup section of the wekan website there appears to be 2 (well 3 if you count version 1 as well) ways to backup snap.

The first one is the 'Snap backup-restore V2' [Here](https://github.com/wekan/wekan/wiki/Backup) which gives me an error of 
`line 36: /data/backups/wekan/backup-progress.log.20190425-223603: No such file or directory
wekan-backup.sh: An unexpected error occurred`

The second is the 'snap based backup' [Here](https://github.com/wekan/wekan-snap/wiki/Backup-and-restore) which appears to work okay but the website has a warning about it use.

Which is the best way to backup? (If it is the first what do I need to do to correct the error?)
Can the non-approved one be erased/archived to stop confusion please?
Can this be put into a cron job?

**Server Setup Information**:

* Did you test in newest Wekan?: 2.65
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 2.65
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: ubuntu 18.04
* Deployment Method snap:

**Comment by Fransacreblue** [comment]
The second option is the most advisable, That way you can automate your system to be doing backups

**Comment by xet7** [comment]
Yes, backup bash script that uses mongodump command is recommended.
