### ISSUE TITLE
New board with ^ pre and post is created when viewing a card sub task

### ISSUE THREAD

**Issue by shaygover** [wekan/wekan#2386]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Y
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Y
* Wekan version: 2.65
* If this is about old version of Wekan, what upgrade problem you have?: N
* Operating System: RHEL 5
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): docker
* Node Version: 8.16.0
* MongoDB Version: Whatever in the docker.
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): Can't provide in the moment.

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

Every time a card sub task is viewed a new board is created with the name ^BoardName^. Where BoardName is the original board name. See pic.
![subtask-board](https://user-images.githubusercontent.com/15545/56871130-31e47980-6a22-11e9-80b7-a7b2521c7eed.png)

**Comment by xet7** [comment]
Yes, creating subtask does create subtask board that has name with `^` and adds subtask cards to it. Original creator of subtask feature designed it this way.

There was sometime ago tested that subtask boards should be hidden, but that caused boards moving around All Boards page all the time to differet positions, so it was reverted.

How this should work?

**Comment by shaygover** [comment]
Maybe different board category?

**Comment by xet7** [comment]
Moved to #641
