### ISSUE TITLE
Feature Request: Different list names on different swimlanes

### ISSUE THREAD

**Issue by D347HxD** [wekan/wekan#2387]
## Issue

Is there a way to stop each swimming lane from having exactly the same list names?

![swimlane-list-names](https://user-images.githubusercontent.com/15545/58131437-5d284600-7c27-11e9-91fa-a3648f1bae50.png)

As you can see, they both are exactly the same and when I change or add any list, the other changes accordingly.

Is there a way I can change “Planned” in “Items” to “Need To Purchase”
and “In Progress” in “Items” to “Purchased”?

Each swimming lane for this project will need a different set of lists.

**Comment by xet7** [comment]
Moved to #2805
