### ISSUE TITLE
one of board doesn't load

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2389]
I create 5 boards with Wekan V2.65 on win10 with docker, one of it can't be load successfully. all the other 4 boards works well. 
I tried install Wekan on another computer and restore the data in the new wekan, but issue happens again.
anyone can help me? I can send you the backup data.![捕获](https://user-images.githubusercontent.com/46272743/57088106-2780f300-6d34-11e9-8612-1a0932c4ccaf.PNG)

**Comment by xet7** [comment]
@javen9881 

You can send it to my email address x@xet7.org , I will fix it.

**Comment by javen9881** [comment]
Update: @xet7 
I can duplicate the broken board and also found it works. just don't how to remove the broken board.

**Comment by xet7** [comment]
@javen9881 

https://github.com/wekan/wekan/wiki/Delete-Board

**Comment by xet7** [comment]
Hmm, actually, maybe if it does not load...

**Comment by javen9881** [comment]
You are right, it doesn't load.

**Comment by xet7** [comment]
Well, maybe if I add button to All Boards page to move board to Archive. I'll try.

**Comment by xet7** [comment]
@javen9881 

Please try this Docker image of new Wekan release, at All Boards page click broken board's Archive button:
```
image: quay.io/wekan/wekan:v2.67
```
To this line:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L118

**Comment by javen9881** [comment]
@xet7 
thanks a million for your great support :)
BTW: I found the user(comment only) also can archive the board..... is it possible give the archive function to the Board owner only?
