### ISSUE TITLE
Change email/password and leaving a board not implemented yet?

### ISSUE THREAD

**Issue by dialogik** [wekan/wekan#239]
When I try to leave a board (click on `Sidebar > Members > Myself > Leave Board`) or to change my password or email address (click on respective link under `Settings`) nothing happens. There is no change of the website, no change in my address bar (I assume this is due to some `preventDefault()` stuff) and no output (e.g. error) in my console.

So are these functions simply not implemented yet? Or is there something wrong with my setup?

**Comment by mquandalle** [comment]
These menu weren't implemented in the previous version, this is now fixed with v0.9.
