### ISSUE TITLE
[Permission request] Reviewer on zh-HK

### ISSUE THREAD

**Issue by lifehome** [wekan/wekan#2393]
Hi,

Thanks for adding the new language zh-HK, and me as the Translator. However, as the translation proceeds, I will need further permission - as a reviewer or coordinator - to review and proofread on previous strings. I am hoping that someone can elevate my permission, so that I can continue translate and proofread at the same time. (My transifex username is @lifehome)

Regards,
Ivan

**Comment by xet7** [comment]
Done.
