### ISSUE TITLE
Run wekan in meteor cause stylus error

### ISSUE THREAD

**Issue by mfshiu** [wekan/wekan#2394]
## Issue

**My environment:**
* Wekan version: 2.65
* Windows 10 x64
* Meteor version: 1.8.1 or 1.6.1
* node version: 11.14.0 / 8.7.0 / 4.8.1 (all tried)

**I use below command to run wekan:**

G:\Work\Test\wekan>meteor --settings app.json --port 8080

**but I got the error of stylus in startup**

[[[[[ ~\G\Work\Test\wekan ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While processing files with stylus (for target web.browser):

   C:\Users\mfshi\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\tools\static-assets\server\mini-files.js:43:13:
   Surprising path:
   /Users/mfshi/AppData/Local/.meteor/packages/stylus/2.513.13/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/lib/nib/size.styl
   at toDosPath
   (C:\Users\mfshi\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\tools\static-assets\server\mini-files.js:43:13)
   at Object.convertToOSPath
   (C:\Users\mfshi\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\tools\static-assets\server\mini-files.js:56:12)
   at Object.wrapper (C:\tools\fs\files.js:1594:25)
   at readFile (packages/compileStylusBatch/plugin/compile-stylus.js:123:21)
   at Array.map (<anonymous>)
   at processSourcemap
   (packages/compileStylusBatch/plugin/compile-stylus.js:143:52)
   at StylusCompiler.compileOneFile
   (packages/compileStylusBatch/plugin/compile-stylus.js:179:23)
   at async.eachLimit
   (packages/caching-compiler/multi-file-caching-compiler.js:115:45)
   at
   C:\Users\mfshi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\mfshi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\mfshi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\mfshi\AppData\Local\.meteor\packages\stylus\2.513.13\plugin.compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
   at StylusCompiler.processFilesForTarget
   (packages/caching-compiler/multi-file-caching-compiler.js:95:11)

**Comment by xet7** [comment]
On Windows, building Wekan currently works on:
- Windows Subsystem for Linux
- Docker for Windows, when using Linux containers

I'll try could I get building working using Windows-based Meteor.
