### ISSUE TITLE
Export board error  - HTTP 301

### ISSUE THREAD

**Issue by thiagofernando** [wekan/wekan#2398]
## Issue
When try to export a board, link returns http 301 and wekan redirect to initial page.

**Server Setup Information**:
i tested in two different environment
I) Windows 10 x64 -> localhost test
II) CentOS 7 -> nginx  http://xxx.com/wekan

* Did you test in newest Wekan?: yes, 2.66
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 2.66
 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
I) running meteor
2) building from source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 8.9.1
* MongoDB Version: 3.6.3
* ROOT_URL: 
I) non
II) http://mydomain.com/wekan/

**Comment by xet7** [comment]
You need to have `WITH_API=true' for export to work.

## Meteor
```
cd wekan
./rebuild-wekan.sh     # 1 and 2
WITH_API=true meteor
```
## Source
https://github.com/wekan/wekan/blob/devel/start-wekan.sh#L45

## Docker
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L223

## Snap
```
sudo snap set wekan with-api='true'
```
