### ISSUE TITLE
Allow to move a card to a different board.

### ISSUE THREAD

**Issue by kadishmal** [wekan/wekan#240]
We manage backlog issues in a separate board. Then before the next sprint we need to move some cards to that sprint's board. How to do this with Libreboard?

**Comment by zeineath** [comment]
:+1:

**Comment by davidstanke** [comment]
+1!

**Comment by pezhore** [comment]
This was previously addressed by Nelson with Libreboard - I think I still have the modified files somewhere. I'll try to see if the changes will still work with wekan.

**Comment by basvdijk** [comment]
+1 would be really cool to have this feature. It is currently the only reason I am not using Wekan.

**Comment by qsmits** [comment]
Actually came here to request this exact feature and saw this issue.

Wekan seems perfect, except for this, not having this feature would mean a lot of work copy-pasting items between backlog and sprint boards...

**Comment by synthesisGoogle** [comment]
@pezhore Do you have the changes for Livreboard in a gist or in a repo somwhere? I'd like to take a look at this.

**Comment by JSeawright** [comment]
+1 as well, this would be super great.

**Comment by mquandalle** [comment]
If anyone is interested in implementing this feature I can provide some guidance. This should be fairly easy.

**Comment by synthesisGoogle** [comment]
I'm interested.

Rob

On Tue, Oct 20, 2015 at 3:07 PM, Maxime Quandalle <notifications@github.com>
wrote:

> If anyone is interested in implementing this feature I can provide some
> guidance. This should be fairly easy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wekan/wekan/issues/240#issuecomment-149716645>.
>



-- 
Robert Anderberg | Developer Advocate | Games | synthesis@google.com

If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let me know
it
went to the wrong person.  Thanks.

**Comment by mquandalle** [comment]
@synthesisGoogle come to chat on gitter if you have some questions, https://gitter.im/wekan/wekan

**Comment by jseadragon** [comment]
I might also be interested in contributing

**Comment by NickGodspeed** [comment]
+1

**Comment by pezhore** [comment]
@synthesisGoogle Better late than never? I think this is the zip'ed repo: https://www.dropbox.com/s/x3o6iza8uxdhck1/libreboard-movecard.zip?dl=0

**Comment by kant1** [comment]
+1

**Comment by akhockey21** [comment]
Is anyone actively working on this?

**Comment by hsduk** [comment]
this would need the card to be moved to a different listid (and boardid)
Q: Could changing card boardid and listid fields to arrays be better? 
This would allow a single card to be used/shared in many lists (and boards) or just the one but i guess would be a much bigger change

**Comment by mquandalle** [comment]
@hsduk Yes I have something like that in mind, but as you say this is a bigger architectural change that need to be considered carefully (especially the edge cases). Feel free to open another thread here or on the forum about that.

**Comment by jseadragon** [comment]
I'm not working on this, is @synthesisGoogle taking it on?

**Comment by hsduk** [comment]
FYI: Simple card copy is available at: https://github.com/hsduk/wekan/tree/plugin-simple-timer

**Comment by alayek** [comment]
I am interested in working on this. I could use some help though. 

What are the edge cases?

**Comment by gwillen** [comment]
@alayek Well, I'm interested in this feature in the context of Sandstorm, where each instance of the running app has exactly one board. So for this feature to work there, it has to be possible to move cards between different copies of the app -- which may not share the same users, tags, etc.

I tried for a while to hack this in using the existing Trello import support -- copying a card to the clipboard, effectively, and pasting it into a new board. The existing Trello import can do things like letting you map the source board's users onto the destination board's users when importing a card.

Being able to do this by dragging would require HTML5 drag-and-drop, which seems like it would mean replacing _all_ the drag-drop in the app with HTML5 drag-drop, which is probably a lot of work. That's why I thought the clipboard seemed like a nice workaround.

**Comment by xet7** [comment]
Moved to #797
