### ISSUE TITLE
[Bug] Card counters at List headers are not positioned correctly

### ISSUE THREAD

**Issue by rinnaz** [wekan/wekan#2403]
## Issue
**Server Setup Information**:

* Wekan version: **2.72**
* Operating System: **Ubuntu 18.04**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **snap**

**Problem description**:
Firefox:
![image](https://user-images.githubusercontent.com/36293513/57621133-5d737200-7593-11e9-8af7-0273d913e389.png)

Chrome:
![image](https://user-images.githubusercontent.com/36293513/57621184-78de7d00-7593-11e9-9444-f04aae141b6c.png)

**Comment by xet7** [comment]
@hupptechnologies 

Can you fix this?

**Comment by hupptechnologies** [comment]
@xet7 sure will check it.
