### ISSUE TITLE
Feature request: Past image directly in a card

### ISSUE THREAD

**Issue by reinos** [wekan/wekan#2409]
Hi There,

Currently adding images is a bit cumbersome. you have to open an card and then click image and then you can paste, or select an image from you computer.

The way Trello does looks very intuitive and is much faster. In Trello you can just drop an image on an empty card or past it on an empty card and voila! 

Is there a way that this can buildin Wekan?

Thanks.
Rein

**Comment by xet7** [comment]
Moved to #1926
