### ISSUE TITLE
Bug: Duplicated Board missing comments in cards

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2411]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: v2.74
* Operating System: Ubuntu, snap

**Problem description**:
- After duplicated an Board the comment in the cards where show as icon, but the card self has no comments.

![image](https://user-images.githubusercontent.com/6977657/57832730-a1938c00-77b8-11e9-9ab7-0b185d38ac0e.png)

![image](https://user-images.githubusercontent.com/6977657/57832750-ad7f4e00-77b8-11e9-9118-f8c69d8617fd.png)

**Comment by daniel-eder** [comment]
Is this bug still present?
I just duplicated a board and while other issues such as #2329 are present, I can actually see the checklist items in the duplicated board:
![image](https://user-images.githubusercontent.com/1525711/98520303-25c1b500-2272-11eb-9d41-4a2fb09b3dce.png)

From my point of view it appears to be fixed, but it would be good if someone could verify.

**Comment by xet7** [comment]
Moved to #3336
