### ISSUE TITLE
OAuth2 Requested Scopes are wrong / cannot be configured

### ISSUE THREAD

**Issue by DominikPf** [wekan/wekan#2412]
Is there any reason for not requesting the correct Scopes for OAuth2 Tokens?

Correct scopes:
https://github.com/wekan/wekan/blob/0834f6ed1e544189c99648da3f7e1e3f4c0cef6b/packages/wekan-oidc/oidc_client.js#L24

But the settings are here static configured (so this will be used instead of the correct default of oidc-client.js):
https://github.com/wekan/wekan/blob/0834f6ed1e544189c99648da3f7e1e3f4c0cef6b/server/authentication.js#L80

The Standard response is a id_token without the "name" Claim of the User (comes with the "profile" scope) and the Mail Address (comes with the "email" scope)

The feature to configure the requested Claims was removed here (but i don't know if this worked previously):
https://github.com/wekan/wekan/commit/05351c0ac100dc481f8eb6430a871f6e6d015cf0#diff-9680c177f7ad431ea38af066796fdb1a

The current result is that "name" & "email" is undefined (because they are not in the id_token).
I don't want to configure the two Scopes statically for the Wekan Client in our Identity Solution. 

Is there any way to change that behaviour?

**Comment by xet7** [comment]
@DominikPf 

Do you mean mapping id, username etc?
https://github.com/wekan/wekan/wiki/OAuth2#4-add-wekan-settings

**Comment by DominikPf** [comment]
@xet7 
No my problem is that required Information (Name of the User & Email) is not inside my id_token, because they are not requested.

As described above only the "openid" Scope is requested, but profile & email is also needed.

Spec:
https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

**profile**
> OPTIONAL. This scope value requests access to the End-User's default profile Claims, which are: **name**, family_name, given_name, middle_name, nickname, preferred_username, profile, picture, website, gender, birthdate, zoneinfo, locale, and updated_at.

**email**

> OPTIONAL. This scope value requests access to the **email** and email_verified Claims.

Configuration is not possible because the "requestedPermissions" Property is statically set to 'openid':
https://github.com/wekan/wekan/blob/0834f6ed1e544189c99648da3f7e1e3f4c0cef6b/server/authentication.js#L80

**Comment by DominikPf** [comment]
Hi @xet7 i now get 

> Uncaught TypeError: a.join is not a function

And i think i got the Problem:
The "ServiceConfiguration" for the service oidc returns the string "[openid,profiles,email]" for "requestPermissions" instead of an Array. 
(I don't know Meteor Framework to track down the issue exactly, so i wrote a little console output for config.Scopes)

But is an Array working as Environment Variable? I thought Environment Variables are only a Key-Value pairs of strings.
A simple way to fix this would be to change the Type from Array to string, than the User is responsible for the correct Scope Request Format.
I got this so far working, here is a PR: #2427


Everything on the Authentication side seems now to be correct
In the Log all Claims are correctly mapped (Name, Email, User Id).


### **But:** 
The User is empty now and only the first one can access (probably because that there are more than one User with the same UserId '').
![2019-05-23 10_06_14-pc018107 sgr lan_3001](https://user-images.githubusercontent.com/20923469/58238345-61e41b80-7d47-11e9-8698-8c31bc8c6555.png)
![2019-05-23 10_06_37-pc018107 sgr lan_3001_people](https://user-images.githubusercontent.com/20923469/58238346-627cb200-7d47-11e9-8b19-ecaa9ef6f61c.png)


So the OAuth2 Method still doesn't work for me :/

**Comment by xet7** [comment]
@DominikPf 

After adding your changes, OAuth2 login to Wekan still works fine for me using RocketChat and Auth0 login providers using settings listed here:
https://github.com/wekan/wekan/wiki/OAuth2

What OAuth2 login provider you are trying to use with Wekan?

**Comment by DominikPf** [comment]
@xet7 I am using a Company-Internal implementation of IdentityServer4.
Wekan gets all Information from the Server and the mapping from Token to Wekan is also correct (as i can see in the log). 

I looked inside the Wekan MongoDB and extracted my Profile.
- Wekan Configured via OAuth2 & OIDC (mongodb_oauth+oidc.json)
- Wekan Configured via Password (mongodb_password.json)
[mongodb.zip](https://github.com/wekan/wekan/files/3212139/mongodb.zip)

It seems that Password & OAuth2 are to differently db schemas (could that be the Problem?)
![2019-05-23 14_41_58-mongodb_oauth+oidc json - Visual Studio Code](https://user-images.githubusercontent.com/20923469/58253776-776a3d00-7d69-11e9-98a5-61d7f04d8679.png)

My Setup:
Currently (My changes on the Scope builded with v2.75 as base) as Wekan Image
Our Company Image Layered on top of the Wekan Image (we need our internal SSL certifcates) 
[Dockerfile.txt](https://github.com/wekan/wekan/files/3212240/Dockerfile.txt)


Executed via Docker with this custom Docker-Compose Environment Settings for Wekan (All others are not touched):

```yml
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=***
      - MAIL_URL=***
      - MAIL_FROM=***
      - WITH_API=true
      - BROWSER_POLICY_ENABLED=true
      - DEBUG=true
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=Wekan
      - OAUTH2_SECRET=Wekan 
      - OAUTH2_SERVER_URL=***
      - OAUTH2_AUTH_ENDPOINT=/connect/authorize
      - OAUTH2_USERINFO_ENDPOINT=/connect/userinfo
      - OAUTH2_TOKEN_ENDPOINT=/connect/token
      - OAUTH2_ID_MAP=sub
      - OAUTH2_USERNAME_MAP=sub
      - OAUTH2_FULLNAME_MAP=name
```
Same settings are applied to the other Test Environment with the Password Login Method (works fine :))
I currently have no idea why OAuth2 works on your Test Environment but not for mine :/

Did i forgot something?

**Comment by xet7** [comment]
@DominikPf 

## Login

Well, originally I did create my user account using password login.

For automating, it's also possible to use Wekan REST API to create new password user:
1) Login to Wekan REST API using Admin username and password as form data:
https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data
2) With that Bearer token you get from step 1, create new user with API https://github.com/wekan/wekan/wiki/REST-API-User#example-of-all-steps-of-create-user
3) Set user role with REST API:
https://github.com/wekan/wekan/wiki/REST-API-Role
4) More info at API docs, how to get list of users boards, etc:
https://wekan.github.io/api/

There is also Wekan-Gogs integration example at:
https://github.com/wekan/wekan-gogs

Then at Wekan Admin Panel, it's possible to set:
- Admin Panel / Settings / Registration / Disable Self-Registration, so that nobody can register with username and password manually
- Admin Panel / Settings / Layout / Default Authentication Method: OAuth2
- Admin Panel / Settings / People / Some username: you can also change login method for each user, is it password or OAuth2, but anyway both should still work, and it's not necessary to change there.

Sure this could be made simpler, if someone has some ideas for it.

## Settings

One other thing to check is, that if you don't have slash at end of URL:
```
- OAUTH2_SERVER_URL=https://example.com
```
Then you can have slash at start of settings:
```
- OAUTH2_AUTH_ENDPOINT=/connect/authorize
```
But if you have slash at end of OAuth2 server URL:
```
- OAUTH2_SERVER_URL=https://example.com/
```
Then you should not have slash at start of settings:
```
- OAUTH2_AUTH_ENDPOINT=connect/authorize
```
## Debug
When you have tried logging, and it does not work, what Docker logs output?
```
docker logs wekan-app
```
And, on Chrome webbrowser rightclick / Inspect / Console, do you get any errors?

**Comment by DominikPf** [comment]
Hi @xet7 

Thanks for the explanation

# Settings
I fixed my slash issue but that didn't changed anything.

# Debug
**Docker:**
There isn't any error in the logs when i login, the Log-Entries from the OAuth2 Service are also looking good (this is the complete log of a freshly created container + login after startup):
[wekan ouauth2 docker log.txt](https://github.com/wekan/wekan/files/3215289/wekan.ouauth2.docker.log.txt)

**Browser:**
Directly after the Login (Landing-Page):
[wekan oauth2 browser (landing page).txt](https://github.com/wekan/wekan/files/3215304/wekan.oauth2.browser.landing.page.txt)

When i go to the people page in the Admin section:
[wekan oauth2 browser (admin people page).txt](https://github.com/wekan/wekan/files/3215306/wekan.oauth2.browser.admin.people.page.txt)

When i try to change my User Settings (Add Username, Email, Fullname):
[wekan oauth2 browser (admin people page save user settings).txt](https://github.com/wekan/wekan/files/3215308/wekan.oauth2.browser.admin.people.page.save.user.settings.txt)

# Change the Login
1. I tried create a User with the Password method => Works as always fine
2. I changed the Settings of the User from Password to OAuth2 => Works
3. I tried to Login with OAuth2 => **Also Works**

Here is the MongoDb entry of this User:
[mongodb_password_then_oauth+oidc.txt](https://github.com/wekan/wekan/files/3215327/mongodb_password_then_oauth%2Boidc.txt)

Here are both OAuth & Password fields are saved.

So the change from existing Users to OAuth2 works, but not the initial creation of the User via OAuth.

**Comment by DominikPf** [comment]
@xet7 I found this entry:
https://github.com/wekan/wekan/wiki/Keycloak

> Outstanding Bug: Create the first user (admin) with the regular process. Then the remaining users can use the Register with OIDC process.

**So if the first User is added, everything works fine :)**

I cannot find any Issue for that, should i open one?
This Issue can be closed (OAuth2 works now in my oppinion)
PS: This issue seems also to be happening with LDAP Auth.

**Comment by xet7** [comment]
@DominikPf 

It seems that changes added during this issue did break Wekan OIDC login https://github.com/wekan/wekan/issues/2206#issuecomment-495725670 . Can you add PR to fix this?

**Comment by DominikPf** [comment]
Hi @xet7 my changes are not included in v2.75, this Version is also broken for me. My PR #2427 should fix this but isn't released yet.
![2019-05-24 19_50_13-Commits · wekan_wekan](https://user-images.githubusercontent.com/20923469/58347264-aeba1600-7e5d-11e9-9f46-54dec7ce3347.png)

**Comment by xet7** [comment]
> @xet7 I found this entry:
> https://github.com/wekan/wekan/wiki/Keycloak
> 
> > Outstanding Bug: Create the first user (admin) with the regular process. Then the remaining users can use the Register with OIDC process.
> 
> **So if the first User is added, everything works fine :)**
> 
> I cannot find any Issue for that, should i open one?
> This Issue can be closed (OAuth2 works now in my oppinion)
> PS: This issue seems also to be happening with LDAP Auth.

Yes, you can add new issue about creating new user with OIDC/LDAP etc first login, when user already exists in identity provider.

**Comment by DominikPf** [comment]
This Issue should be fixed with the next Release.

I created a Issue for the "First-User"-Bug here:
#2444
