### ISSUE TITLE
[FEATURE] Rule trigger to move/copy card to another panel to create workflows

### ISSUE THREAD

**Issue by DaBlitzStein** [wekan/wekan#2415]
Wekan is difficult to use because there is no way to create good workflows. I suposse if there were a posibility to move or copy card to another panel it can be managed to simplify the structure.

Example: 

I have an event that have to be published. When the event goes to the column "Publish" then it clones the card to the RRSS panel accessible by the RRSS team.

Is this possible?

Thank you in advance,

**Comment by xet7** [comment]
Moved to #1996

**Comment by JAGL14** [comment]
I am testing wekan and this is very powerfull, but for me it is very necessary to move DONE lists to historical boards. In Trello it's very simple, but I don't see it here. This rule would be a solution? Thanks

**Comment by xet7** [comment]
@JAGL14 

This issue is closed. If you mean something else than [some existing Rules issue](https://github.com/wekan/wekan/labels/Feature%3ACards%3AIFTTT-Rules), Please add new issue with more details and screenshot mockup.

**Comment by JAGL14** [comment]
Thanks @xet7. I mean the issue moved to #1996. It is open no? I'll write in that issue.

**Comment by xet7** [comment]
@JAGL14 

Yes #1996 open, you can write to it.

<hr>

Closed issue looks like this, with red color:

![closed](https://user-images.githubusercontent.com/15545/65622065-96096a80-dfcd-11e9-87ca-9382dc70bda2.png)

<hr>

Open issue looks like this, with green color:

![open](https://user-images.githubusercontent.com/15545/65622097-a4f01d00-dfcd-11e9-869d-205717b51b94.png)

<hr>

And when I move some issue to some other issue, I write for example like this, so issue becomes closed:

Moved to #1996
