### ISSUE TITLE
[Feature request] serval small features for a better experinece.

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2417]
1. feature1: one line at bottom of card(or background) to show the card status by length, such as 30%, 90% and 100%. 
2. feature2: Convert the checklist to subtask by click, and keep the link btween them;
3. feature3: Can send any card to the list "Done" by simple click, and can make the list "Done" invisible;
4. feature4: Can show the countdown/counting of days.

**Comment by javen9881** [comment]
5. feature5: Can I drag mail/office document in as attachment? or add the link to open local folder/file in my hard disk or link to local onenote content?

**Comment by xet7** [comment]
1. one line at bottom of card(or background) to show the card status by length, such as 30%, 90% and 100%. Moved to #1847 

2. Convert the checklist to subtask by click, and keep the link be tween them. Moved to #2422 

3.
a) Can send any card to the list "Done" by simple click. Moved to #2423
b) Can make the list "Done" invisible. Moved to #2107

4. Can show the countdown/counting of days. Moved to #2424

5.
a) Can I drag mail/office document in as attachment? Moved to #1926
b) or add the link to open local folder/file in my hard disk or link to local onenote content? Moved to #1615
