### ISSUE TITLE
Labels are lost when you move a card

### ISSUE THREAD

**Issue by hmeunier95** [wekan/wekan#2421]
## Issue

We are in release 1.62 and docker.

When we move a card from one list to an other one, all labels are lost.

This behaviour occurs even in the last docker release (1.74).

Regards,

**Comment by savoiebz** [comment]
We currently have the same issue on our version installed from sources. The label are losts when card moved. Even in the same list when reordering. 

The first line in the changelog file mentions `v2.65 2019-04-24 Wekan release`.

**Comment by xet7** [comment]
Moved to #2404
