### ISSUE TITLE
On Sandstorm, adding members to a board does not work

### ISSUE THREAD

**Issue by jpretori** [wekan/wekan#2428]
## Issue

I can't seem to get colleagues the ability to see and contribute to Wekan boards on Snadstorm.

**Server Setup Information**:

* Did you test in newest Wekan?:  Yes, Sandstorm.
* Wekan version: 2.61.0~2019-04-20

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
![Peek 2019-05-24 12-02](https://user-images.githubusercontent.com/16192343/58320492-09cb1900-7e1c-11e9-8808-31d1b6439d64.gif)

- *Explain steps how to reproduce*

1. Create new Wekan grain in Sandstorm
2 . "Share Access" with several colleagues
3. Confirm they can see the first board I created the grain with
4. Try to add them as members to another board in the same grain
5. Expected them to get some kind of notification that they can now see this new board, and to be able to move cards around.  Instead, they can't even see the board.

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
```
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?
3f9b6145345d2486e5d49ca2f10cdd418dde0b54.js:103:1007
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
onmozfullscreenchange is deprecated. dde565b9b359dceb4eaad44288690fbdbbb476c2.js:29:10658
onmozfullscreenerror is deprecated. dde565b9b359dceb4eaad44288690fbdbbb476c2.js:29:10658
```

**Comment by ocdtrekkie** [comment]
This is interesting. There hasn't been nearly as much testing on additional boards in a Wekan grain, as until very recently Sandstorm only supported one board per grain.

**Comment by xet7** [comment]
Yes, this is known issue, member management is not fully implemented with multiple boards yet.

Moved to #2405

**Comment by wellgoodthen** [comment]
A fairly cumbersome workaround I've successfully used for this issue is to create new boards in Trello with the appropriate members assigned to a card, then export & import into Sandstorm Wekan.
