### ISSUE TITLE
Feature Request: REST API: Edit User password, fullname etc

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2430]
Moved to here from https://github.com/wekan/wekan/issues/1037#issuecomment-496149665

From @BobCashStory 

> @xet7 thanks i found https://wekan.github.io/api/v2.71/#edit_user but doesn't seem we can update fullname password etc, do we ?

**Comment by BobCashStory** [comment]
Thanks a lot !

**Comment by BobCashStory** [comment]
@xet7 any upddate on that ?

**Comment by xet7** [comment]
@BobCashStory 

I have not had time this yet. Anyone can read REST API code at `wekan/models/` and send pull request, if it's urgent. Newest Wekan Meteor 1.8.1 is at master branch, and developer docs at Wekan GitHub wiki.
