### ISSUE TITLE
How to lock a board and prevent changes that are not card-related?

### ISSUE THREAD

**Issue by beppe9000** [wekan/wekan#2432]

**Comment by xet7** [comment]
@beppe9000 

What card-related would still be modifiable?

**Comment by beppe9000** [comment]
It's probably a UI thing. Basically I wanted to lock the structure of a board to prevent accidental changes and hide the "add panel" panel but still allow cards to be created and moved around.

**Comment by xet7** [comment]
@beppe9000 

Lock what structure? Swimlanes? Or something else?

**Comment by beppe9000** [comment]
For example the new list space could be removed, all name changing disabled, list ordering disabled.
It's a concept similar to locking the windows taskbar to avoid unintentional changes.

**Comment by xet7** [comment]
@beppe9000 

How could list ordering be disabled, if cards could be still created or moved around?

What is use case for this?

**Comment by beppe9000** [comment]
I mean the whole list, not their content. 
![image](https://user-images.githubusercontent.com/6625123/58496655-9b1ef000-817a-11e9-9c78-3ae96b2c2cf1.png)

**Comment by printgeek** [comment]
I also see the value of this. Locking the board to the lists that are already created (prevent further lists from being created) and prevent re-ordering of the lists. This is especially important on mobile, where you can easily reorder the lists inadvertently when trying to scroll down.

**Comment by xet7** [comment]
Wekan v3.98 has mobile fixes for this.
