### ISSUE TITLE
Migration from wekan 0.78 (ubuntu 16.04) to same wekan version on Ubuntu 18.04

### ISSUE THREAD

**Issue by funk09** [wekan/wekan#2436]
## Issue

My task was to migrate wekan 0.78 to a new vm (ubuntu 18.04)
Originally someone else installed the old wekan system and it was in use for one year. So there are a lot of boards to migrate and also in the archive. 

I tried to install same version of wekan on new server. Restored there the database (first stopped the service and did a  mungodump on the old server). 

**Server Setup Information**:
new server versions wekan v.0.78, mongod  v4.0.9, node  v8.9.3 installed with npm 
(old server version wekan v0.78, mongod v3.6.9, node v9.11.2) 

* Did you test in newest Wekan?:
I installed newest version with snap and saw the export function. But the mongodb schema in wekan 2.65 was different from wekan 0.78. I couldn't migrate the data from old db to new. 

* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
I configured ROOT_URL with our url. It seems to start. 

* Wekan version:
0.78

* If this is about old version of Wekan, what upgrade problem you have?:
When I restore the database and relogin in wekan only there is one board (of 6 ) and all the cards are away. 

* Operating System:
Ubuntu 18.04 on the new server, Ubuntu 16.04 on the old. 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
Maybe on the old server there is sandstorm installed, I have no experience, and the installation looks different than mine. 

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): No, until now no configured http frondend. Planned https over apache. 
* Node Version: node  v8.9.3 (old node v9.11.2) 
* MongoDB Version: mongod  v4.0.9 (old mongod v3.6.9) 
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): I use http. 

**Problem description**:
When I restore the database and relogin in wekan only there is one board (of 6 ) and all the cards are away. When I restore the database and relogin in wekan only there is one board (of 6 ) and all the cards are away. 
I saw the migration instructions: 
https://github.com/wekan/wekan/wiki/Migrating-from-old-Wekan-manually
But I don't know how to use a *.js File and what to do with it. 
Can I somehow import my old dump in the new snap wekan database?

- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*

**Comment by xet7** [comment]
Restore:
```
sudo snap stop wekan.wekan

mongorestore --drop --port 27019

sudo snap start wekan.wekan
```
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore#stop-wekan-and-restore

**Comment by xet7** [comment]
Apache:
https://github.com/wekan/wekan/wiki/Apache

**Comment by funk09** [comment]
I restored like you proposed before. The database contains all the needed data. But it is not shown in wekan after I login the second time.  
Only one board contains the expected cards.

**Comment by xet7** [comment]
@funk09 

I need to test is there some missing migration.
