### ISSUE TITLE
Edit button doesn't work for comments on other users

### ISSUE THREAD

**Issue by netei** [wekan/wekan#244]
With a just installed libreboard instance, I see the buttons "Edit" and "Delete" on comments of other users.
![edit](https://cloud.githubusercontent.com/assets/13066384/9516204/60ec6108-4ca7-11e5-90f5-d6d963ad9024.PNG)

However, whenever I click edit and edit the post, then click edit again to confirm the edit, nothing happens. Whenever I click delete on that same post, nothing happens too.

If it is not possible to edit other comments, it would make sense not to show the buttons for those posts. However, I'd rather be able to edit other peoples posts

**Comment by mquandalle** [comment]
Thanks for the report :) I'll fix this at the user interface level. The ability to edit other members messages (is that only for board admins?) is not implement.

I will keep this issue for the UI bug, could you open another issue for the feature request (with description and motivation)?

**Comment by netei** [comment]
I think if the UI bug is solved, it is ok because it is not misleading. 

I expected to be able to edit other peoples posts because I saw the edit button. Now that it is removed, I don't expect to be able to edit other peoples posts.
