### ISSUE TITLE
card title filtering

### ISSUE THREAD

**Issue by beppe9000** [wekan/wekan#2440]
Is the card title filter regex or plain text contained in it? I wanted to add a red label to all cards that contain the word 'bug' (case insenstive) when they are added anywhere in the board.
Could you advise me on how to make that filter work? Only the exact match gets the label added...

![image](https://user-images.githubusercontent.com/6625123/58635433-2b317680-82ee-11e9-8ed9-bdc5bb77e7de.png)

**Comment by xet7** [comment]
@beppe9000 

Advanced Custom Filters were [added by Wekan newbie contributor](https://blog.wekan.team/2018/05/wekan-v1-00-released/index.html). In that blogpost is link to issue that where is more details. You can also search current open/closed issues and pull requests for related info.

Some more programming info is [at this blogpost](https://blog.wekan.team/2019/04/howto-code-part-1-learning-to-learn/index.html).

In general for this `card title filtering` feature, you can look is the related code in [sidebar or other component](https://github.com/wekan/wekan/tree/devel/client/components). Or alternatively, on webbrowser right click that filter sidebar place and click on browser Inspect, so you see related code, and use `wekan/find.sh` script to find that code. There you find how filter code works. Then you can add button to filter sidebar where you select rule to be applied to filter results.

**Comment by beppe9000** [comment]
Ah, now it's explained... thanks for the context!

**Comment by xet7** [comment]
@beppe9000 

There is [some little serverside code for authentication](https://github.com/wekan/wekan/tree/devel/server) and [database structure](https://github.com/wekan/wekan/tree/devel/models) but in newest meteor lines are blurred even more, so it depends if code checks is it running serverside, the names of directories don't matter.

Client/Serverside code etc structure probably could change in some future Wekan version, it depends when I get it figured out.

**Comment by beppe9000** [comment]
I seee. About client-server comunication, I see it's websocket but i checked with dev tools and when I moved a card no communication occurred. How can I be sure that closing a tab will not lose changes?

**Comment by xet7** [comment]
@beppe9000 

Changes are saved automatically. You can try close and open tab. I have not noticed any changes getting lost. I also don't know does your browser tools show all traffic. Meteor has also browserside mongodb implemented in javascript, and Meteor moves data between browser and server automatically. Only visible cards are loaded, using infinite scroll, so it's possible to load very big  boards that were originally imported from trello.

**Comment by beppe9000** [comment]
I returned to the tab and saw the websocket request. I think there is some sort of caching going on.

**Comment by xet7** [comment]
@beppe9000 

Yes there us buffering and latency compensation.

Also, if you go to other tab, Wekan disconnects live updates to save server resources. When tab is activated again, connections and live updates are resumed.

**Comment by beppe9000** [comment]
Is there a way to disable all that while running on localhost?

**Comment by xet7** [comment]
@beppe9000 

What is the benefit in that? Really, when browser tab is not active, your local Wekan and browser uses less CPU, so your laptop fans do not run so fast. You are not using Wekan when it's tab is not active. Changing that would require making custom version of Wekan.

**Comment by beppe9000** [comment]
Actually I lost some data the other day while i was setting up lists in a board and some test cards. I wanted to turn off the server, so I switched to the tab, went to board list and then ctrl-c'ed the server. After restart the log showed some exceptions about inexisting cards and lists. Since I couldn't reproduce it at the time I wanted to pre-emptively mitigate it by forcing the client to flush changes to server instantaneously.

I find awkward there is no user interface element to tell me that data is in sync like google document does.

**Comment by xet7** [comment]
Moved to #2537
