### ISSUE TITLE
Bug: First User (Admin) Login/Registration with OAuth2&OIDC fails

### ISSUE THREAD

**Issue by DominikPf** [wekan/wekan#2444]
This Issue was detected in #2412 and is also documented here:
https://github.com/wekan/wekan/wiki/Keycloak
or
https://github.com/wekan/wekan/issues/1874#issuecomment-460802250

If a fresh Wekan installation with OAuth2 is used, the first User cannot be generated on Registration. So Wekan cannot be used.

This Bug happens only for the first User (if you create the User via Username/Password and than change to OAuth2 everything works fine).

This Issue also seems to happen with LDAP Login (we haven't checked this again)

**Comment by ww-daniel-mora** [comment]
I am also running issues with first user creation with OAuth2. User creation appears to succeed but no profile data (user name, email etc) are populated, and cannot be be manually entered afterwards. The client just errors when encountering surprising null values like email and will not save updates.

While attempting to debug the issue I noticed that [Accounts.onCreateUser](https://github.com/wekan/wekan/blob/76f4b8316b52a81aadfc1d4759447f41d002e6f9/models/users.js#L1273) did not appear to be called during first user creation.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3994
