### ISSUE TITLE
Failed to load c++ bson

### ISSUE THREAD

**Issue by flippingtables** [wekan/wekan#245]
I follow the installation instructions that are in the Wiki on this page.
On a clean Ubuntu 12.04 server.

However when i get to the final step, and actually run `node main.js` I get this error.
Not sure why, but is it possible that there is something missing from the instructions? I tried googling this "failed to load c++ bson" issue and attempted a few things, but nothing solved it.

This is the error message:

```
[Error: /home/spoderman/libreboard/.build/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson/build/Release/bson.node: undefined symbol: _ZN2v86String3NewEPKci]
js-bson: Failed to load c++ bson extension, using pure JS version
/home/spoderman/libreboard/.build/bundle/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: /home/spoderman/libreboard/.build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: _ZN2v811HandleScopeC1Ev
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/spoderman/libreboard/.build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/spoderman/libreboard/.build/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/home/spoderman/libreboard/.build/bundle/programs/server/boot.js:162:18)
    at packages/npm-bcrypt/packages/npm-bcrypt.js:9:1
    at packages/npm-bcrypt/packages/npm-bcrypt.js:13:1
```

**Comment by yipcma** [comment]
i face the same problem on ubuntu 14.04

**Comment by ePirat** [comment]
Which node version are you using?

**Comment by flippingtables** [comment]
* Node: 0.12.7
* npm:  2.11.3
* Meteor: 1.1.0.3

**Comment by yipcma** [comment]
@flippingtables ditto your setting, but on ubuntu 14.04.3

**Comment by ePirat** [comment]
Please try to use node 0.10.x as 0.12 is too new for some dependencies to work properly.

**Comment by yipcma** [comment]
@ePirat  excellent. can use nvm install 0.10
also, the node command should run under bundles
otherwise it's good :) Thank you.

**Comment by flippingtables** [comment]
Excellent, thanks for that.
For future discoverers of this post, i did this:

Install 'n' a node version manager util.
```
$ npm install -g n
$ n 0.10.40
$ n use 0.10.40 main.js
```

**Comment by premcool** [comment]
For future references - I encountered the same issue and employed solution as below without changing node version, as mine is more recent node v4.5.0

Step 1:
./programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/ext/index.js
catch block change as below
Old: bson = require('../build/Release/bson');
New: bson = require('../browser_build/bson');

Step 2: (global install)
npm install -g node-gyp node-pre-gyp 

Step 3:
/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules# rm -rf bcrypt

Step 4:
/bundle# npm install bcrypt
