### ISSUE TITLE
[Bug] Wekan unable to Select Text from Description edit box

### ISSUE THREAD

**Issue by justinr1234** [wekan/wekan#2451]
Unable to select text from a description edit box

If you try to use your mouse to select text in any input or textarea within a Wekan card, it will cause the background to become no longer greyed-out which causes focus to shift away from the card and the card to be unselected. It behaves like you are clicking in the background when you click anywhere within an edit box in wekan.

https://youtu.be/eOmAW8Xrgww

**Comment by xet7** [comment]
This seems to be Chrome bug. It does not exist in Firefox. I will test other browsers.

**Comment by xet7** [comment]
This bug does not seem to exist in newest official Wekan Meteor 1.6 and Meteor 1.8 versions, using newest Firefox/Chrome/Chromium/Edge/Chromium Edge for Ubuntu 16.04/19.04 and Win10.

**Comment by xet7** [comment]
This seems to be Chrome bug. It does not exist in Firefox. I will test other browsers.

**Comment by xet7** [comment]
Ok now I figured out how this happens.
When I select text in description, and drag-select text to up to above of Description text box, then description box closes.

This happens on all Chromium-based browsers:
- Chrome
- Chromium
- Chromium Edge (Credge)

This does not happen on these browsers:
- Firefox Quantum
- Edge
- Wavebox

This does not happen when drag-select text down.

**Comment by xet7** [comment]
I did fix this by removing feature of card description submit on click outside. This is because when selecting text and dragging up did trigger submit of description, so description was closed and selecting text failed.
