### ISSUE TITLE
How to get horizontal swimlanes

### ISSUE THREAD

**Issue by sander1523** [wekan/wekan#2459]
Hello

Right now We have swimlanes like this:
![Capture](https://user-images.githubusercontent.com/51447192/59034894-6e4e9500-886c-11e9-9b77-da871435af32.PNG)

But we want it like this:

![capture 1](https://user-images.githubusercontent.com/51447192/59034922-7c041a80-886c-11e9-9a4f-c4f814b253d2.PNG)

How can I do this? so that the swimlane titles are horizontal.

**Comment by xet7** [comment]
@sander1523 

You have old Wekan version. Please upgrade to newest Wekan version, that has horizontal swimlanes.

https://github.com/wekan/wekan/wiki/Backup#docker-backup-and-restore

If you want to be always up-to-date, restore mongodb backup to new Wekan snap version. Snap has automatic updates.

https://github.com/wekan/wekan-snap/wiki/Install
