### ISSUE TITLE
meteor-up (MUP) for libreboard?

### ISSUE THREAD

**Issue by yipcma** [wekan/wekan#246]
Having tried sandstorm and docker without success on my digitalocean ubuntu, am wondering if there could be an MUP solution to this...thoughts?

**Comment by ocdtrekkie** [comment]
@paulproteus would almost certainly want to know about your problem getting Sandstorm working.

**Comment by paulproteus** [comment]
Hi @yipcma -- I'd love to help you get Sandstorm working, it's true! Email me at support@sandstorm.io and I'll help you make it work for free, if you are still interested.

I'll leave the rest of this discussion about MUP, to avoid noise.

**Comment by ePirat** [comment]
I don't think we can use meteor-up as it needs information such as:

```json5
// Server authentication info
  "servers": [
    {
      "host": "hostname",
      "username": "root",
      "password": "password",
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa",
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],
```

which we can't possibly know.

**Comment by yipcma** [comment]
@paulproteus Thanks for the offer. I was doing it again and this time it works with sandstorm. Of course I'd still prefer a raw-hosting solution :) Thank you.

**Comment by yipcma** [comment]
raw-hosting works, and it is pretty straight-forward. am closing this issue.
