### ISSUE TITLE
[Feature] My Tasks view

### ISSUE THREAD

**Issue by justinr1234** [wekan/wekan#2470]
It would be good to have a todo-list style view across all cards in the system for the currently logged in user. The user should be able to get quick information about tasks without opening the board or individual cards. They should also be able to take quick actions. Please see Todoist as an example.

<img src="https://i0.wp.com/doist.com/blog/wp-content/uploads/sites/3/2016/12/duplicate-task2-1.gif?resize=1356%2C1100&quality=85&strip=all&ssl=1">

**Comment by xet7** [comment]
Moved to #2186
