### ISSUE TITLE
password reminder email reset-password not exists

### ISSUE THREAD

**Issue by yipcma** [wekan/wekan#248]
hi, the linked page reset-password doesn't exist, assuming BASE_URL=example.com and port = 8080. Also, i have other things hosted at example.com, so should the link not point to example.com:8080 instead? but i don't find anything there either. am using nginx.

https://example.com/#/reset-password/fsvwA9Zp8MuocfU8z8SKf24lmG_oga1LXi4QlzfQ3PG

Thanks.

How do we customize this? Thank you.

**Comment by yipcma** [comment]
sorry, wrong setting on my end, my bad.

**Comment by yipcma** [comment]
please delete.

**Comment by mquandalle** [comment]
This is fixed [in the upcoming v0.10](https://github.com/wekan/wekan/issues/425).
