### ISSUE TITLE
Page not found when clicking on cards

### ISSUE THREAD

**Issue by naveengh** [wekan/wekan#2480]
I have exact same issue.

I have created image using Intuz on AWS to access wekan. Everything looks good so far - can create boards, cards.

But when I click on card to view details, i get following error and no page to display
Safari can't open the page https://0.0.0.0/wekan/b/Hbwfy79pdPhfwyby9/welcome-board/pkosgAPBHzbHif9mo

When you click on card it takes request to https://0.0.0.0/ which is obviously is incorrect. So I need to replace IP 0.0.0.0 with AWS public IP somewhere. I'm guessing in Security Groups of AWS or somewhere else?

So where do I insert AWS public IP?

Thanks for help.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Settings

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/OAuth2

**Comment by xet7** [comment]
You should ask Intuz support, and read their guides and faqs. I don't even know do they have latest Wekan version, because I'm not familiar with their company.

**Comment by naveengh** [comment]
Thanks Xet7, I will reach out to them and ask to help me fix. Do you know if I can directly put docker on AWS? do you have any documentation? Thanks

**Comment by xet7** [comment]
Docker:
https://github.com/chaosbunker/dockerbunker

Snap:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by naveengh** [comment]
Thank you so much Xet7, I will look into. Thanks much

**Comment by naveengh** [comment]
ok, this is fixed
