### ISSUE TITLE
[FEATURE] - json console to show the json call when we do something on the UI. 

### ISSUE THREAD

**Issue by hradec** [wekan/wekan#2482]
Would be really helpful to have a way to see what's go around when something is done in the ui, so it can be replicated in any language, like python. 

the afanasy project has something like it:  (http://cgru.info/home)
![image](https://user-images.githubusercontent.com/806743/59166393-0c956180-8ade-11e9-8d3c-70beb6023bac.png)

it's hidden most of the time, but you can show it to "grab" the json you want for certain UI actions. So one can script things very easily, without the need of documentation.

**Comment by xet7** [comment]
Wekan has API for scripting.

**Comment by xet7** [comment]
For getting info what happens at all boards, there is Global Webhooks at Admin Panel.
