### ISSUE TITLE
Wekan: not possible to assign members to a card anymore

### ISSUE THREAD

**Issue by stfnnnhfn** [wekan/wekan#2486]
Hi all, 
i am brand new to all this stuff here and happy to get wekan 0.54 running on Ubuntu 16.04 LTS.
After a while with testing and playing it is not possible to assign to cards anymore. 
Error message below
![grafik](https://user-images.githubusercontent.com/51404281/59339402-69726100-8d04-11e9-85e3-bf2b4d056b51.png)
can anyone help please

**Comment by xet7** [comment]
Wekan 0.54 is very old, please install newest Wekan.

To get assing member to a card working, please remove all Outgoing Webhooks from board. Fixing Outgoing Webhook is in progress, but it's not fixed yet.

Moved to #1402
