### ISSUE TITLE
LDAP Bug: [ERROR] InvalidCredentialsError: 80090308: LdapErr: DSID-0C090400

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2490]
From IRC:

[14:58:26] <avg> hello everyone. I am getting this erro:
[14:58:30] <avg> Error
[14:58:31] <avg> [ERROR] InvalidCredentialsError: 80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1
[14:59:19] <avg> can someone check this and tell me if I did something wrong? : https://paste.ee/p/uuUDb
[14:59:33] <avg> The credentials are correct
[15:26:09] <avg> This is the error in my syslog: https://paste.ee/p/mJdtL

**Comment by road42** [comment]
From: [Infrasightlabs](https://www.infrasightlabs.com/common-error-codes-for-active-directory-authentication)

The only thing is that `52e`points to 

> Returned when a valid username is supplied but an invalid password/credential is supplied. If this error is received, it will prevent most other errors from being displayed.

**Comment by Dayflare** [comment]
got the same error although the credentials are 100% correct and verified.
some fields are duplicated.
![grafik](https://user-images.githubusercontent.com/42730126/66137580-99b87500-e5fd-11e9-9749-de78c2be8298.png)

which one is the correct password field?

**Comment by xet7** [comment]
@Dayflare 

You see current values with `sudo snap get wekan | less`

You see setting names with `wekan.help | less`

**Comment by xet7** [comment]
Unfortunately it's possible to mistype setting name.

**Comment by Dayflare** [comment]
@xet7 thx for the fast response, the issue was the field ldap-user-authentication, you have to set this to false so it takes the defined credentials.

**Comment by xet7** [comment]
@Dayflare 

What LDAP server you use? I would think different LDAP servers have different settings.

Should default be true?

**Comment by Dayflare** [comment]
@xet7 we use Microsoft Active Directory on Windows Server 2012. The default is false, i thought this field means something else. 
wekan.help provided the necessary documentation to find it out :)

**Comment by xet7** [comment]
@Dayflare 

So does Wekan work now? Is this issue fixed?

**Comment by Dayflare** [comment]
@xet7 my issue is fixed, Wekan works wonderful.

**Comment by ZamanOof** [comment]
> got the same error although the credentials are 100% correct and verified.
> some fields are duplicated.
> ![grafik](https://user-images.githubusercontent.com/42730126/66137580-99b87500-e5fd-11e9-9749-de78c2be8298.png)
> 
> which one is the correct password field?

how to check ldap info inside wekan ? i mean how you get this list?
thanks

**Comment by xet7** [comment]
@ZamanOof 

```
sudo snap get wekan
```
https://github.com/wekan/wekan/wiki/LDAP

**Comment by xet7** [comment]
@ZamanOof
```
wekan.help | less
```

**Comment by ZamanOof** [comment]
> @ZamanOof
> 
> ```
> wekan.help | less
> ```

Hello,
I accessed the container by using 
`docker exec -it wekan-app bash`
so where to use your mentioned command 
`wekan.help | less
bash: wekan.help: command not found
bash: less: command not found
`
thanks

**Comment by ZamanOof** [comment]
the error was because of double quotes (maybe signal quotes too) was the reason behind.
@xet7 @road42 @Dayflare

**Comment by xet7** [comment]
@ZamanOof 

Can you add as comment your working config, anonymized?

**Comment by ZamanOof** [comment]
> @ZamanOof
> 
> Can you add as comment your working config, anonymized?

Hello, Actually i make change at docker-compose file.

**Comment by XL-Reaper** [comment]
I had the same issue.
Actually the defaults in the docker-compose.yml are missleading.
The quotes around 
 # The search user DN - You need quotes when you have spaces in parameters
      # 2 examples:
LDAP_AUTHENTIFICATION_USERDN="CN=wekan_adm,OU=serviceaccounts,OU=admin,OU=prod,DC=mydomain,DC=com"

are wrong - at least for me. I removed the quotes, although I had a space in the CN and it worked immediately.

**Comment by Vinc89** [comment]
> I had the same issue.
> Actually the defaults in the docker-compose.yml are missleading.
> The quotes around
> 
> `# The search user DN - You need quotes when you have spaces in parameters # 2 examples: LDAP_AUTHENTIFICATION_USERDN="CN=wekan_adm,OU=serviceaccounts,OU=admin,OU=prod,DC=mydomain,DC=com"`
> 
> are wrong - at least for me. I removed the quotes, although I had a space in the CN and it worked immediately.

Removing the quotes worked for me as well, thx!

**Comment by tromlet** [comment]
Looks like we're having a similar issue.

We had a user with an LDAP account that he wasn't fond of, so we set him up with a new one - however he'd already logged into WeKan using BOTH the new and the old LDAP accounts. When we DELETED the old LDAP account, we see like... these little "ghost" members where his old account used to be as a member of the board.

Doesn't seem to hurt anything, but we cannot seem to get that little ghost thing out of there, and I thought you might want to know that. :P 

Maybe I should file this as a bug?
