### ISSUE TITLE
Feature: Disable Public board globally

### ISSUE THREAD

**Issue by chirrut2** [wekan/wekan#2491]
**Server Setup Information**:
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 2.78
* Operating System:
ubuntu server 18; snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
apache

**Problem description**:
We dont want to share any board in public, but want to make the server public available. Is there a possibility to disable the "Public" board switch globally?

br
Daniel

**Comment by xet7** [comment]
No. If bounty target of 200 euro is reached, I will add it to Wekan.
https://www.bountysource.com/issues/75483334-feature-disable-public-board-globally

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Allow-private-boards-only
