### ISSUE TITLE
updating wekan

### ISSUE THREAD

**Issue by stfnnnhfn** [wekan/wekan#2493]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: No
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 0.54
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu 16.04.6 LTS

* Node Version: v4.2.6
* MongoDB Version: 2.6.10

**Problem description**:
Sorry for beeing an absolute newbie on this whole stuff. 
can you please shortly explain how I can update to a newer version of wekan ?
I have no snap/docker installed.
What happens to the boards already running in wekan 0.54 ?

Thanks a lot and enjoy the day
Stefan

**Comment by xet7** [comment]
Well, instructions are [here](https://github.com/wekan/wekan-snap/wiki/Install) but let's go here shortly about them.

1) Backup your current MongoDB.
```
mongodump --port 27017
```
2) Stop your current webserver(s), like Wekan node/apache/nginx etc.

3) Install Wekan
```
sudo apt-get update
sudo apt-get -y install snapd
sudo snap install wekan
```
4) Remove your current MongoDB and install MongoDB shell and tools, add repo and repo key from:
https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-ubuntu/
```
sudo apt-get install mongodb-org-shell mongodb-org-tools
```
5) Restore database
```
mongorestore --drop --port 27019
```
6) Edit /var/snap/wekan/common/Caddyfile to have your wekan domain.

7) Set your Wekan domain to snap:
```
sudo snap set root-url='https://wekan.example.com'
sudo snap set wekan caddy-enabled='true'
```
8) Login to Wekan
https://wekan.example.com/sign-in

**Comment by xet7** [comment]
If above upgrade works, you have all your boards, users, etc data, and also newest Wekan features.

**Comment by stfnnnhfn** [comment]
Thanks a lot Lauri, 
do you recommend to update to Ubuntu 18 first ?

**Comment by xet7** [comment]
Yes.

**Comment by stfnnnhfn** [comment]
Thanks again. I will keep you informed ;-)

**Comment by stfnnnhfn** [comment]
Hello Lauri, 
still trying to understand your procedure.
Let me please ask:
- sudo apt-get install mongodb-org-shell mongodb-org-tools  
are sudo apt-get install mongodb-org-server mongodb-org-mongos **not neccesary** 

- mongorestore --drop --port 27019        
 **why** using port 27019 here 

- as it seems that wekan is then running under https - do I have to set 
PORT=443 in start-script ?
and 
ROOT_URL='https://wekan.company'

Thanks in advance 
and have a nice day
Stefan

**Comment by xet7** [comment]
Your previous MongoDB server is at port 27017 usually.

MongoDB shell and tools, because you only need mongodump and mongorestore. You don't need server, because Wekan snap includes mongodb server at port 27019.

Caddy webserver config at /var/snap/wekan/common/Caddyfile does proxy Caddy 80 and 443 automatic let's encrypt to local port 3001. In Caddyfile local port number needs to be same as in Wekan `sudo snap set wekan port='3001'`. If you want to use some other webserver, you can se`sudo snap set caddy-enabled='false'` and look at some other webserver config like Apache or Nginx example at Wekan GitHub wiki.

`sudo snap set root-url='https://wekan.company'` does set correct URL for Wekan. If it's not correct, card does not open correctly.

**Comment by stfnnnhfn** [comment]
After the sudo apt-get install mongodb-org-shell mongodb-org-tools I received following message

Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket mongodb-org-shell kann nicht gefunden werden.
E: Paket mongodb-org-tools kann nicht gefunden werden.

**Comment by stfnnnhfn** [comment]
please ignore my last comment. 
I achieved to install mongodb-org-shell and tools
after filling the repofile with 
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

I was able to restore
but it fails to set the root-url with
sudo snap set root-url='https://wekan.mycompany' with errormessage
error: the required argument `<conf value> (at least 1 argument) ` was not provided

**Comment by xet7** [comment]
```
sudo snap set wekan root-url='https://wekan.mycompany'
```

**Comment by stfnnnhfn** [comment]
yes that works - great 
but I cant start wekan in my browser
with https://wekan.leguano
caddyfile looks like
http://:3001
proxy / localhost:3001 {
  websocket
  transparent
}

## SSL/TLS example. Firefox Inspect Console does not support http/2, so turning it off
## so that Firefox would not show wss websocket errors. Chrome console supports http/2.
#
wekan.leguano {
  tls {
    alpn http/1.1
  }
   proxy / localhost:3001 {
     websocket
     transparent
  }
}

**Comment by xet7** [comment]
You should only have this uncommented:
```
wekan.leguano {
tls {
alpn http/1.1
}
proxy / localhost:3001 {
websocket
transparent
}
}
```

**Comment by xet7** [comment]
to wekan.lequano, change your domain name.

**Comment by xet7** [comment]
Also make sure that Wekan is at port 3001:
```
sudo snap set wekan port='3001'
```
And enable caddy:
```
sudo snap set wekan caddy-enabled='true
```
And look at caddy logs, is making SSL certs in progress. When it's finished, it shows hosting urls like wekan.leguano at bottom.
```
sudo snap logs wekan.caddy
```
And look are all services running and enabled, caddy+wekan+mongodb
```
sudo snap services
```

**Comment by stfnnnhfn** [comment]
Lauri, 

sudo snap logs wekan.caddy
2019-06-21T09:36:37Z systemd[1]: snap.wekan.caddy.service: Service hold-off time over, scheduling restart.
2019-06-21T09:36:37Z systemd[1]: Stopped Service for snap application wekan.caddy.
2019-06-21T09:36:37Z systemd[1]: Started Service for snap application wekan.caddy.
2019-06-21T09:36:37Z wekan.caddy[7818]: DEBUG=false (default value)
2019-06-21T09:36:37Z wekan.caddy[7818]: MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/current/share (default value)
2019-06-21T09:36:37Z wekan.caddy[7818]: MONGODB_BIND_IP=127.0.0.1 (default value)
2019-06-21T09:36:37Z wekan.caddy[7818]: MONGODB_PORT=27019 (default value)
2019-06-21T09:36:37Z wekan.caddy[7818]: MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
2019-06-21T09:36:37Z wekan.caddy[7818]: MAIL_FROM=wekan-admin@example.com (default value)
2019-06-21T09:36:37Z wekan.caddy[7818]: ROOT_URL=https://wekan.leguano

looks fine to me, isn't it ?
as well as

 sudo snap services
Service        Startup  Current  Notes
wekan.caddy    enabled  active   -
wekan.mongodb  enabled  active   -
wekan.wekan    enabled  active   -
 
dont know what's wrong

**Comment by xet7** [comment]
You could try reboot server.

**Comment by stfnnnhfn** [comment]
no change after reboot

neuenhofen@UbuntuSRV01:~$ sudo snap set wekan port="3001"
neuenhofen@UbuntuSRV01:~$ sudo snap set wekan caddy-enabled="true"
neuenhofen@UbuntuSRV01:~$ sudo snap set wekan root-url="https://wekan.leguano"
neuenhofen@UbuntuSRV01:~$ sudo snap logs wekan.caddy
2019-06-21T09:54:11Z wekan.caddy[43031]: HEADER_LOGIN_LASTNAME=Header login firstname. Example for siteminder: HEADERLASTNAME (default value)
2019-06-21T09:54:11Z wekan.caddy[43031]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
2019-06-21T09:54:11Z wekan.caddy[43031]: LOGOUT_WITH_TIMER=false (default value)
2019-06-21T09:54:11Z wekan.caddy[43031]: LOGOUT_IN= (default value)
2019-06-21T09:54:11Z wekan.caddy[43031]: LOGOUT_ON_HOURS= (default value)
2019-06-21T09:54:11Z wekan.caddy[43031]: LOGOUT_ON_MINUTES= (default value)
2019-06-21T09:54:11Z wekan.caddy[43031]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-06-21T09:54:11Z wekan.caddy[43031]: caddy is enabled, adjusting ports
2019-06-21T09:54:11Z wekan.caddy[43031]: CADDY_PORT=3001
2019-06-21T09:54:11Z wekan.caddy[43031]: PORT=3001
neuenhofen@UbuntuSRV01:~$ sudo snap services
Service        Startup  Current  Notes
wekan.caddy    enabled  active   -
wekan.mongodb  enabled  active   -
wekan.wekan    enabled  active   -

**Comment by xet7** [comment]
what does these say?
```
sudo snap logs wekan.wekan
sudo snap logs wekan.mongodb
```

**Comment by stfnnnhfn** [comment]
neuenhofen@UbuntuSRV01:/var/snap/wekan/common$ sudo snap logs wekan.wekan
2019-06-21T10:13:19Z wekan.wekan[46615]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
2019-06-21T10:13:19Z wekan.wekan[46615]: LOGOUT_WITH_TIMER=false (default value)
2019-06-21T10:13:19Z wekan.wekan[46615]: LOGOUT_IN= (default value)
2019-06-21T10:13:19Z wekan.wekan[46615]: LOGOUT_ON_HOURS= (default value)
2019-06-21T10:13:19Z wekan.wekan[46615]: LOGOUT_ON_MINUTES= (default value)
2019-06-21T10:13:19Z wekan.wekan[46615]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-06-21T10:13:19Z wekan.wekan[46615]: caddy is enabled, adjusting ports
2019-06-21T10:13:19Z wekan.wekan[46615]: CADDY_PORT=3001
2019-06-21T10:13:19Z wekan.wekan[46615]: PORT=3001
2019-06-21T10:13:19Z wekan.wekan[46615]: MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan

**Comment by xet7** [comment]
And this, please change domain names, usernames and passwords befor posting:
```
sudo snap get wekan
```

**Comment by stfnnnhfn** [comment]
neuenhofen@UbuntuSRV01:/var/snap/wekan/common$ sudo snap logs wekan.mongodb
2019-06-21T10:09:32Z wekan.mongodb[22455]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
2019-06-21T10:09:32Z wekan.mongodb[22455]: LOGOUT_WITH_TIMER=false (default value)
2019-06-21T10:09:32Z wekan.mongodb[22455]: LOGOUT_IN= (default value)
2019-06-21T10:09:32Z wekan.mongodb[22455]: LOGOUT_ON_HOURS= (default value)
2019-06-21T10:09:32Z wekan.mongodb[22455]: LOGOUT_ON_MINUTES= (default value)
2019-06-21T10:09:32Z wekan.mongodb[22455]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-06-21T10:09:32Z wekan.mongodb[22455]: caddy is enabled, adjusting ports
2019-06-21T10:09:32Z wekan.mongodb[22455]: CADDY_PORT=3001
2019-06-21T10:09:32Z wekan.mongodb[22455]: PORT=3001
2019-06-21T10:09:32Z wekan.mongodb[22455]: mongodb bind options:  --unixSocketPrefix  /var/snap/wekan/current/share --bind_ip 127.0.0.1 --port 27019

**Comment by stfnnnhfn** [comment]
sorry - yes I will change those informations

**Comment by stfnnnhfn** [comment]
sudo snap get wekan
Key            Value
caddy-enabled  true
port           3001
root-url       https://wekan.companyname

**Comment by xet7** [comment]
Is Wekan visible at https://wekan.companyname/sign-up and https://wekan.companyname/sign-in ?

Do you have ports 80 and 443 open at server?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Adding-users

**Comment by stfnnnhfn** [comment]
seems there is no entry for Ports 80 and 443

sudo netstat -nlp
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:27019         0.0.0.0:*               LISTEN      24144/mongod
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1388/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1388/sshd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1129/dhclient
Aktive Sockets in der UNIX-Domäne (Nur Server)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Pfad
unix  2      [ ACC ]     STREAM     HÖRT         17284    3723/systemd        /run/user/1002/systemd/private
unix  2      [ ACC ]     SEQPAKET   HÖRT         15795    1/init              /run/udev/control
unix  2      [ ACC ]     STREAM     HÖRT         12035    1/init              /var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     HÖRT         15763    1/init              /run/systemd/private
unix  2      [ ACC ]     STREAM     HÖRT         15768    1/init              /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     HÖRT         15769    1/init              /run/systemd/fsck.progress
unix  2      [ ACC ]     STREAM     HÖRT         15774    1/init              /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     HÖRT         15776    1/init              /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     HÖRT         17522    1292/iscsid         @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     HÖRT         12030    1/init              /run/uuidd/request
unix  2      [ ACC ]     STREAM     HÖRT         12031    1/init              /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     HÖRT         12032    1/init              /run/acpid.socket
unix  2      [ ACC ]     STREAM     HÖRT         12033    1/init              /run/snapd.socket
unix  2      [ ACC ]     STREAM     HÖRT         12034    1/init              /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     HÖRT         221366   24144/mongod        /var/snap/wekan/current/share/mongodb-27019.sock

**Comment by stfnnnhfn** [comment]
Is Wekan visible at https://wekan.companyname/sign-up and https://wekan.companyname/sign-in ? 
No at no adress

**Comment by xet7** [comment]
What does these say?
```
sudo netstat -plant | grep node
sudo netstat -plant | grep caddy
sudo netstat -plant | grep nginx
sudo netstat -plant | grep apache
```

**Comment by stfnnnhfn** [comment]
nothing 
all 4 
nginx and apache are not installed - as far as i know 
But I had wekan 0.54 running on http://wekan.companyname

**Comment by xet7** [comment]
Well, maybe Caddy has problem with SSL, or something.
Let's test without caddy, with just http, for a moment:
```
sudo snap set wekan caddy-enabled='false'
sudo snap set wekan port='80'
sudo snap set wekan root-url='http://wekan.companyname'
```
Is Wekan now visible at http://wekan.companyname ?

**Comment by stfnnnhfn** [comment]
caddy is inactive now
wekan.caddy    disabled  inactive  -
wekan.mongodb  enabled   active    -
wekan.wekan    enabled   active    -

still not able to connect to http://wekan.companyname

can i use ufw to open listening on port 80 maybe ?

**Comment by xet7** [comment]
Yes. See if ufw enabled:
```
sudo ufw status
```
Then allow http and https:
```
sudo ufw allow http
sudo ufw allow https
```

**Comment by xet7** [comment]
If Wekan is running on AWS, you need to add ports 80 and 443 to EC2 Security Group, or to LightSail networking.

**Comment by xet7** [comment]
If ufw is not installed, you can install and enable it:
```
sudo apt-get install ufw
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
```
Or, disable ufw:
```
sudo ufw disable
```
At AWS, ufw is not usually needed, because only those ports are visible to outside that have been enabled in EC2 Security Group or LightSail networking.

Other clouds can have different firewall management web UIs.

**Comment by stfnnnhfn** [comment]
ufw is now enabled
sudo ufw status
Status: Aktiv

Zu                         Aktion      Von
--                         ------      ---
22/tcp                     ALLOW       Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)

but still Wekan not found on http://wekan.companyname

AWS ? you mean Amazon Web Service - No
by the way - your service is much appreciated !

**Comment by xet7** [comment]
Thanks :)

Does your domain work? Does this show your server IP address?
```
ping wekan.companyname
```

**Comment by xet7** [comment]
Hmm, I'm thinking, is there some problem migrating your data to newest Wekan.
I think you did take backup.
We could try emptying database, does Wekan get visible then.
And look at restoring data later.
```
sudo snap stop wekan.wekan
mongo --port 27019
use wekan
db.dropDatabase();
exit
sudo snap start wekan.wekan
```
Does Wekan then show at http://wekan.companyname?

**Comment by xet7** [comment]
Is this Wekan server running at OVH, Kimsufi or OpenVZ ?
Or is it running at bare metal/KVM/XEN/VirtualBox/VMware/HyperV/AWS/Azure/DigitalOcean/Upcloud/some other cloud?

**Comment by stfnnnhfn** [comment]
ping is succesful

wekan stopped
database wekan dropped
wekan.wekan started

and YEP wekan is starting with http
of course not https because caddy is inactive

**Comment by stfnnnhfn** [comment]
just running on a standalone ubuntu server just within the internal company net

**Comment by xet7** [comment]
Ok, you can then try https:
```
sudo snap set wekan port='3001'
sudo snap set wekan root-url='https://wekan.companyname'
sudo snap set wekan caddy-enabled='true'
```
Does then work https://wekan.companyname ?

**Comment by xet7** [comment]
https and caddy does not work on internal company net. only http 80 works.

**Comment by xet7** [comment]
I can look why your Wekan database does not upgrade correctly, if you can send your MongoDB database dump in .zip file to me using this URL:
https://www.dropbox.com/request/KQqepyd0Jr62GHfWETfF

You can also send me email to x@xet7.org so I can send you link to download fixed mongodb dump.

Wekan v0.54 is from 2017-11:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v054-2017-11-02-wekan-release
So there can be some migrations missing from Wekan.

**Comment by stfnnnhfn** [comment]
yes - you're right, it doesn't work with caddy enabled. So I jumped back to port 80.
I can easily live with http at the moment. Its internal and everybody will understand.
Can i restore now ?

**Comment by xet7** [comment]
Yes you can try restore

**Comment by xet7** [comment]
Does restoring database dump show any errors?

**Comment by xet7** [comment]
Hmm, actually I could try Wekan version 0.54 does it upgrade correctly to newest Wekan.

**Comment by stfnnnhfn** [comment]
restoring the dump was succesful
i can see my old data 
but i cannot see my old boards on the first screen 
yes i can open them form the marked link, but these are only those who had a star
![grafik](https://user-images.githubusercontent.com/51404281/59921319-983bb600-942d-11e9-8068-a79076e7f17b.png)

**Comment by xet7** [comment]
When you click `Alle Boards`, can you see all boards?

**Comment by stfnnnhfn** [comment]
no, thats the issue. Then I see only the Board that i've just created but not the old ones as for example Wekan Board and Privates ...

**Comment by xet7** [comment]
Maybe you created new user and did login with it?

You need to logout, and login with your old username and password.

**Comment by stfnnnhfn** [comment]
no, I haven't created any new user

**Comment by xet7** [comment]
Then you need to download MongoDB GUI:
https://nosqlbooster.com/downloads

And with it, connect via ssh to server port localhost 27019.

Then look at users collection/table what is your user ID, that is some string with users and characters.

Then look at boards collection/table, edit it's members, and add you as member to those boards.

To edit those shortcuts, you can star and unstar boards.

**Comment by xet7** [comment]
Try this, does it make boards visible by running migrations?
```
sudo snap stop wekan
sudo snap start wekan
```

**Comment by xet7** [comment]
If stop/start fixes it, you don't need to use MongoDB GUI nosqlbooster to edit database.

**Comment by stfnnnhfn** [comment]
Lauri, 
weird things happen, 
I've had a look into the data with Studio3T and now i cannot reach wekan anymore
I already stopped and started wekan
I even dropped the database and started with the restore again 
but I cant reach http://wekan.companyname anymore

**Comment by stfnnnhfn** [comment]
ping is working 
mongoshell is working
caddy is inactive

**Comment by stfnnnhfn** [comment]
im back in now with dropped database
next i try to restore again

**Comment by stfnnnhfn** [comment]
restore was succesful
wekan was starting 
not all boards visible
tried to sudo snap stop wekan
sudo snap start wekan
after that wekan does not respond anymore

**Comment by xet7** [comment]
Restore should be done this way:
```
sudo snap start wekan
sudo snap stop wekan.wekan
mongorestore --drop --port 27019
sudo snap start wekan.wekan
```

**Comment by xet7** [comment]
If you have a lot of boards and cards, it takes some time to run migrations.
You can see progress with:
```
sudo snap logs wekan.wekan
```

**Comment by xet7** [comment]
When I tried upgrading from Wekan v0.54 to newest, it did work, I did see all my boards I did make previously.

**Comment by xet7** [comment]
It should look like this, when migrations are finished:
```
$ sudo snap logs wekan.wekan
2019-06-21T12:08:15Z wekan.wekan[14415]: > Finishing add-displayAuthenticationMethod migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Starting add-defaultAuthenticationMethod migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Finishing add-defaultAuthenticationMethod migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Starting add-templates migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Finishing add-templates migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Starting fix-circular-reference_ migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Finishing fix-circular-reference_ migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Starting mutate-boardIds-in-customfields migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: > Finishing mutate-boardIds-in-customfields migration.
2019-06-21T12:08:15Z wekan.wekan[14415]: Kadira: completed instrumenting the app
```

**Comment by stfnnnhfn** [comment]
I dont understand - i started with dropped database - wekan is running after that - its empty of course
then i restored as you recommended
sudo snap start wekan
sudo snap stop wekan.wekan
mongorestore --drop --port 27019
sudo snap start wekan.wekan

logs looks like
 sudo snap logs wekan.wekan
2019-06-21T13:38:09Z wekan.wekan[9541]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-06-21T13:38:09Z wekan.wekan[9541]: MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan
2019-06-21T13:38:11Z wekan.wekan[9541]: Note: you are using a pure-JavaScript implementation of bcrypt.
2019-06-21T13:38:11Z wekan.wekan[9541]: While this implementation will work correctly, it is known to be
2019-06-21T13:38:11Z wekan.wekan[9541]: approximately three times slower than the native implementation.
2019-06-21T13:38:11Z wekan.wekan[9541]: In order to use the native implementation instead, run
2019-06-21T13:38:11Z wekan.wekan[9541]:   meteor npm install --save bcrypt
2019-06-21T13:38:11Z wekan.wekan[9541]: in the root directory of your application.
2019-06-21T13:38:12Z wekan.wekan[9541]: Presence started serverId=tK48aurgE8CkedWND
2019-06-21T13:38:13Z wekan.wekan[9541]: > Starting add-swimlanes migration.
 
but timestamp is 2 hours old

next time it brings

 sudo snap logs wekan.wekan
2019-06-21T13:39:34Z wekan.wekan[18718]: HEADER_LOGIN_ID= (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: HEADER_LOGIN_FIRSTNAME=Header login firstname. Example for siteminder: HEADERFIRSTNAME (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: HEADER_LOGIN_LASTNAME=Header login firstname. Example for siteminder: HEADERLASTNAME (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: LOGOUT_WITH_TIMER=false (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: LOGOUT_IN= (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: LOGOUT_ON_HOURS= (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: LOGOUT_ON_MINUTES= (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-06-21T13:39:34Z wekan.wekan[18718]: MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan

wekan is not running

**Comment by xet7** [comment]
Check CPU usage with command:
```
top
```
Is node and mongodb using about 100% CPU ? It could still be doing migrations.

**Comment by xet7** [comment]
How much data you have in MongoDB ? Check with:
```
mongo --port 27019
show dbs
exit
```

**Comment by stfnnnhfn** [comment]
no no cpu usage in higher percentage

and very few data 
admin  0.000GB
local  0.000GB
wekan  0.006GB

just 30 boards - most of them welcome-boards
just 50 cards

**Comment by stfnnnhfn** [comment]
I will start again with a reboot 
and dropped database

**Comment by stfnnnhfn** [comment]
i think the sudo snap start wekan.wekan doesnt come to an end

**Comment by stfnnnhfn** [comment]
after that cpu usage for node goes up

**Comment by xet7** [comment]
You could wait when that cpu usage comes down, when it's finished migrations.

**Comment by stfnnnhfn** [comment]
Lauri,
I left it running. I ll see on Monday what happens. 
Worst case I will start from the beginning without restoring old data. Is at least one important board with 7 lists and approx 50 cards, no attachments. But I hope it runs stable then without disappearing from the browser.  Hope I can count on you on Monday ;-) wish you a very nice weekend and thanks a lot so far

**Comment by xet7** [comment]
@stfnnnhfn 

Yes I'm doing Wekan maintenance also on monday. Thanks, I also wish you a very nice weekend.

**Comment by stfnnnhfn** [comment]
Good Morning Lauri, 
I've started with a empty database and with a fresh reboot. 
At the moment Wekan is working

**Comment by stfnnnhfn** [comment]
Its working fine since yesterday. 
some small things that I found out:
1. the wekan-logo doesn't appear anymore on the sign-in screen - Can I make it visible again ?
2. Cards are not moveable when wekan is in in full-screen browser or even when the window-width comes to an special width. Logos to move the cards disappear then. Is this a bug or a feature ?
Thanks for all your help
Stefan

**Comment by xet7** [comment]
1. Currently wekan-logo is hidden, because because when whitelabeling, Wekan logo would flash and disappear. Maybe sometime I will make option to add Wekan or custom logo, when I get it working well enough.

2. Wekan works differently in different modes, see See #2081 :
- Desktop mode: drag cards when dragging minicards with mouse
- Mobile mode, touchscreen finger swipe usage (or desktop with small width): for moving cards, cross icon at right side of minicard is used. Other parts of cards are used to scroll board up/down/right/left with finger swipe.
