### ISSUE TITLE
Can't select target list for subtasks

### ISSUE THREAD

**Issue by zitrusblau** [wekan/wekan#2503]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Installed Wekan Version: v2.85.0
* For new Wekan install, did you configure root-url correctly: yes
* Operating System: Ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy

No matter which target list I select, always the first one stays selected. (see GIF)

![Kapture 2019-06-19 at 10 23 40](https://user-images.githubusercontent.com/6340749/59750199-b57e5200-927e-11e9-9177-f22b0471452e.gif)

**Comment by xet7** [comment]
Please try with newest Wekan and this info:
https://github.com/wekan/wekan/wiki/Subtasks

**Comment by markusleitoldZBS** [comment]
We have exact the same behaviour, we are not able to choose the target list. The select Box always resets to the first entry. 
Informations from the Wiki Link didn't help.. we created the missing ^BoardName^ Board but the behaviour remains exactly the same.
What is more... we are wondering if the list selection shouldn't show the available lists of the chosen target board in the select box above? No matter which target board is chosen, the target list box always shows the lists of the current board for which the configuration is made, not from the chosen target board.

Our Version is:  4.24.0 and installed via docker.

**Comment by markusleitoldZBS** [comment]
Just upgraded to 4.43 without success... behaviour is identical

**Comment by bastianlemke** [comment]
I can confirm this issue still exists with v4.43.0

**Comment by xet7** [comment]
Moved to #3414
