### ISSUE TITLE
Error on load board

### ISSUE THREAD

**Issue by thiagofernando** [wekan/wekan#2511]
## Issue
Error invoking SubsManager.subscribe("board", "G7CzgGq9EfRZRYMcQ"):  Match failed

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

**Server Setup Information**:

* Did you test in newest Wekan?: yes

* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 2.9
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: CENTOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 8.9.1
* MongoDB Version: 3.6.3

**Problem description**:

After we upgrade 2.72.0 to 2.90 the boards do not open. in firefox debug console we have this output: "Error invoking SubsManager.subscribe("board", "G7CzgGq9EfRZRYMcQ"):  Match failed"

**Comment by xet7** [comment]
Does board open with this workaround? #2492

**Comment by thiagofernando** [comment]
I don't know why, i believe some commit was wrong merge, but a new clean install did work
