### ISSUE TITLE
bug: Multi-selection tool move selected cards to other list does not work

### ISSUE THREAD

**Issue by rumoru** [wekan/wekan#2513]
Hi,

If you enable Multi-selection tool and select some cards in one list and use Move selection action and pick other list, nothing happens.  This is the error when you click on that other list
![Screenshot 2019-06-26 at 11 33 52](https://user-images.githubusercontent.com/7211464/60173345-6f893700-9806-11e9-8d95-c4f265e0ad9b.png)

Wekan v.2.90 and same on Sandstorm demo

**Comment by xet7** [comment]
Hmm, it seems to work only when dragging those selected cards to other list.

That Move selection button does not seem to work.

**Comment by rumoru** [comment]
> Hmm, it seems to work only when dragging those selected cards to other list.

I did not know you can drag them when selected, d'oh! 
Well, that's useful. I guess the easiest fix is to remove that move button altogether 🤣

**Comment by xet7** [comment]
Moved to #2155
