### ISSUE TITLE
Anyone got error after upgrade to V2.92?

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2515]
I got error msg as below;
PS C:\wekan\test> docker-compose up -d
Removing wekan-app
Pulling wekan (wekanteam/wekan:v2.92)...
v2.92: Pulling from wekanteam/wekan
29c2f229a128: Already exists
5d724aeeb884: Already exists
60682405dd89: Already exists
3b9cd0202583: Already exists
30c52c64adeb: Pull complete
7983b69cfb09: Pull complete
wekan-db is up-to-date
Recreating 6dc3c01cb904_wekan-app ... error

ERROR: for 6dc3c01cb904_wekan-app  Cannot start service wekan: b'driver failed programming external connectivity on endpoint wekan-app (4800ac9e478322e2f0f56d0f96a89cfb55f8c506d96301afacdab0859c36f32d): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:82:tcp:172.19.0.3:8080: input/output error'

ERROR: for wekan  Cannot start service wekan: b'driver failed programming external connectivity on endpoint wekan-app (4800ac9e478322e2f0f56d0f96a89cfb55f8c506d96301afacdab0859c36f32d): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:82:tcp:172.19.0.3:8080: input/output error'
ERROR: Encountered errors while bringing up the project.

**Comment by xet7** [comment]
I tested that image and did not have problems. Maybe you did not remove old wekan-app container? All Wekan data is at wekan-db container.

Please try:
```
docker-compose stop
docker rm wekan-app
docker-compose up -d
```
