### ISSUE TITLE
Duplicated board keeps original board name in slug

### ISSUE THREAD

**Issue by zitrusblau** [wekan/wekan#2516]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: v2.92.0
* Operating System: Ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy

Simple problem description
================

=> Original board slug: $wekan_root_url/b/hash_original/original_board_name

=> Duplicated board slug: $wekan_root_url/b/hash_duplicate/**original_board_name**

Is there a way to edit **original_board_name** in the slug after duplication? Otherwise, sending around links to duplicated boards can be quite confusing.

**Comment by xet7** [comment]
Editing slug feature is not implemented yet #200
