### ISSUE TITLE
mail configuration - Error: Invalid login: 504 5.7.4 Unrecognized authentication type

### ISSUE THREAD

**Issue by azeemdin** [wekan/wekan#2517]
Hi,
I am using the latest docker image (wekanteam/wekan)

I have configured mail url as below

MAIL_URL=smtp://user:password@smtp.myserver.com.sa:587/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false

But when I use forgot password option, I am getting below error

`
Exception while invoking method 'forgotPassword' { stack: 'Error: Invalid login: 504 5.7.4 Unrecognized authentication type\n    at SMTPConnection._formatError (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)\n    at SMTPConnection._actionAUTHComplete (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1254:34)\n    at SMTPConnection._responseActions.push.str (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:341:26)\n    at SMTPConnection._processResponse (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)\n    at SMTPConnection._onData (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)\n    at Socket._socket.on.chunk (/build/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:462:47)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)',
  source: 'method' }`

I am unable to find any related troubleshooting step for this error in documentation. Please advise how to resolve this.

**Comment by xet7** [comment]
Well, I tried to figure it out, but did not get it working yet.

Here are some resources for someone trying to figure this out:

https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

https://docs.meteor.com/api/email.html

https://nodemailer.com/smtp/well-known/

https://nodemailer.com/smtp/

https://nodemailer.com/transports/ses/

You can find Email in wekan code this way:
```
git clone https://github.com/wekan/wekan
cd wekan
./find.sh Email
```

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses
