### ISSUE TITLE
Feature Request: Option for seeing all public boards on All Boards page

### ISSUE THREAD

**Issue by flippingtables** [wekan/wekan#252]
For someone that is hosting an instance of Wekan as an internal Kanban board, it would be nice for all users to be able to see all public boards.

The way it works now, is that if you want to see the boards of other users, you will need to either send them the public link, or to add each user to the board.
It would be nice to be able to see all public boards directly in the All Boards page when you log in.

**Comment by yipcma** [comment]
Up this feature. or else what makes public public other than access rights?

**Comment by yipcma** [comment]
Please prioritize this. It would be very difficult to use wekan in an organizational setting without such feature.

**Comment by flippingtables** [comment]
Thats what I'm thinking. Actually, it may even be better to implement some sort of GROUP functionality. 

E.g.:
Organization hosts a Wekan instance internally
Org has several internal groups.
Users are added to groups.
Boards can be declared to belong to a Group.
All users in the same group can view the group.

This would eliminate the need to manually add each individual user that should have access to the board.

**Comment by Roitoh** [comment]
Would also like to see this implemented. We are testing Wekan as an organizational program at work and it'd be nice to not have to specify users every time I make a board.

**Comment by AndyatFocallocal** [comment]
bump

**Comment by simopaasisalo** [comment]
A simple mid-level publicity options would be enough for our use case: every registered user should be able to see every public board, but the boards should not be visible to outside users like the current `Public`-setting

**Comment by koorg** [comment]
I think the way "public" boards are not seen by *any* existing user (they need to be invited to see the board), is more a bug than a feature, it doesn't "feel" public... We don't need groups at the moment, only "public" (seen/editable by any user) boards and "private" boards, as it is meant to work at the moment :)
Auto-adding is perhaps not the best way to implement it but we're looking into scripting auto-add for public boards as a dirty workaround... which is really not the way it should be...

**Comment by jacques-** [comment]
We have a "master" board and just linking to all other boards from that master board - it is super dirty.

A page with list of public boards would be so much better.

**Comment by TiibCD** [comment]
UP +1 to this feature. I agree I think the way public boards work at the moment doesn't feel "public" like we are used to.
The fact that we can share a public board via a link is great but, as a logged user to see all the public boards and my private board seems logic to me.
Any idea if someone took this feature on ?

**Comment by bboy-space** [comment]
Up ?

**Comment by bboy-space** [comment]
On the user's homepage of wekan, I suggest to he sees all public boards (with a limit and the usual "expand arrow" .. ),
And below having "my boards".

**Comment by xet7** [comment]
@rjevnikar 

There could be buttons at top bar for:
- My Boards
- Public Boards
- Subtask Boards

**Comment by xet7** [comment]
@TiibCD 

Well, maybe it could be like:
```
Boards: Starred [_] | My [X] |  Subtask Master [_] / Child [_] | Public [_]
```
There is also related [Top Level Boards issue](https://github.com/wekan/wekan/issues/641#issuecomment-357759642) for other way to categorize.

Admin Panel could also have options like:
- [_] Disable Public Boards
- [_] Disable Subtasks
- [_] Disable Custom Fields

What do you all think?

**Comment by xet7** [comment]
@GavinLilly

I presume you have a lot of boards. What kind of categorization would work best for you?

**Comment by xet7** [comment]
@DrGraypFroot 

What kind of categorization would work best for you? Having Subtask Master / Child boards on separate views would help already I think.

**Comment by GavinLilly** [comment]
> @GavinLilly
> 
> I presume you have a lot of boards. What kind of categorization would work best for you?

Currently we have 10895 boards of which 331 are public so it could present us with a bit of a monster but some configuration in the admin panel would be useful for our kind of edge case.

I like the idea of showing my boards and starred boards by default and then the user has to pick to see public boards.

**Comment by xet7** [comment]
@GavinLilly 

That many boards makes me think of pagination, maybe with selectable amount of boards per page.

**Comment by GavinLilly** [comment]
> @GavinLilly
> 
> That many boards makes me think of pagination, maybe with selectable amount of boards per page.

Yea that could work nicely. Either push the starred boards to the top or default to show starred boards only

**Comment by chotaire** [comment]
I don't think subtask boards should even be displayed on the boards page. There should be a new point "subtasks" (such as templates), and then the subtask boards should also be properly named and not all just called ^originalboardname^.

This looked so terribly wrong that I thought it was a database corruption and thereby I just deleted all subtasks of the user by getting rid of these boards.

**Comment by xet7** [comment]
Feature added at https://github.com/wekan/wekan/pull/3008.
