### ISSUE TITLE
[Bug] Call Administration in a board, the dashboard are show

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2523]
## Issue

**Server Setup Information**:

![image](https://user-images.githubusercontent.com/6977657/60461673-85a05880-9c47-11e9-896f-9f448021be81.png)
Ubuntu - snap

2.97 currently not available

**Update - 2019-07-01 21:52**
Same behavior in 2.97

**Problem description**:
- Open a board
- go to your "user settings"
- select "administration"
- the view goes to the dashboard
- repeat: go to your "user settings"
- repeat:  select "administration"
-> The Administration View is show

Expected result:
on the first click on administration the "Admin View" is show

**Comment by xet7** [comment]
Hmm, seems to be so. I don't know yet why this happens.

**Comment by sfahrenholz** [comment]
in the current snap version 3.29 it works.
