### ISSUE TITLE
Board Color Options

### ISSUE THREAD

**Issue by nickian** [wekan/wekan#2524]
I noticed that some style changes have been made. Is this a bug, something incomplete, or is this intentional? This is what green boards look like now. Surely, no one actually thinks this looks good. What purpose does this bright background serve? ...

![345435345345](https://user-images.githubusercontent.com/590678/60479456-26d8e000-9c43-11e9-92f0-085e10f2eef4.jpg)

The dark blue theme has also changed into some sort of dark mode? This does not look particularly refined either.

![242343433](https://user-images.githubusercontent.com/590678/60479622-b7172500-9c43-11e9-9471-0ac873791ee1.jpg)

Could there be a separate dark mode option from the theme color. In other words, each theme color would have a "dark" and a "light" version. And a dark mode option could be toggled in a user's settings.

**Comment by nickian** [comment]
Ah, I see this referenced at https://github.com/wekan/wekan/issues/1149

I am on Snap, so not quite on the bleeding edge of releases.

**Comment by xet7** [comment]
@nickian 

Snap updates automatically to newest version, given enough time, or you can update manually with `sudo snap refresh`.

See ChangeLog:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

Moved to #1149

**Comment by nickian** [comment]
Thanks!
