### ISSUE TITLE
Sign up with OAuth but not with email

### ISSUE THREAD

**Issue by juliensl** [wekan/wekan#2525]
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 2.97
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node Version: 8.16.0

Hi everybody.

I'm working with the OAuth authentification on wekan.
Currently, when I disable the self-registration and try to sign in with a ***new*** oauth user, I've an ***Unknown error*** and this log in the front size:
```Exception in template helper: TypeError: Cannot read property 'getTemplatesBoardId' of null
    at Object.templatesBoardId (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:323:140131)
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:231:4584
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:59:17175
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:231:4832
    at Function.e._withTemplateInstanceFunc (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:59:37698)
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:231:4739
    at p.mustacheImpl (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:123:1079)
    at Object.p.mustache (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:123:1244)
    at href (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:323:126884)
    at Object.f._withCurrentView (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:59:23097)
```

```Exception in template helper: TypeError: Cannot read property 'getTemplatesBoardSlug' of null
    at Object.templatesBoardSlug (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:323:140205)
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:231:4584
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:59:17175
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:231:4832
    at Function.e._withTemplateInstanceFunc (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:59:37698)
    at https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:231:4739
    at p.mustacheImpl (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:123:1079)
    at Object.p.mustache (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:123:1244)
    at href (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:323:126884)
    at Object.f._withCurrentView (https://plan-dev.live-for-good.org/75e14328568147cb240875c12f4704e88f163967.js?meteor_js_resource=true:59:23097)```
```

It's logical, because I disabled the self-registration.
So first, I think that we should can choose between:
* Enable all self-registrations
* Disable self-registration by email, but enable it by OAuth
* Disable all self-registrations

But after some tests, I saw that if I try to log me in a second time, it works! Even if the self-registration still disabled.

And an other fun bug, is that if you try to log you with a ***new*** oauth user, the last one will be deleted and replaced by the new one, but with the same account (same boards, etc).

So, to reproduce this, I recommend you to:
* Set a wekan with an oauth connection
* Open the admin account, disable the self-registration and go the the user panel
* Open a new browser, connect you on your website with another account and try to connect you to wekan with oauth, it fails
* Try another time, it works
* Create a new board
* Go back to your first browser and see that you have a new member in your admin user panel
* Go back to the second browser and disconnect yourself from your website and from wekan
* Try to connect you with a new account, it fails
* Try to connect you another time, it works
* You can see the board that you created before with the last account
* Go back on the first browser and see that the first member was replaced by the new one.

So, I think it's a critical bug because some members could loose their accounts and other can see privates boards.

I'm not anglophone, so If you don't understand everything I can try to explain again.

Thank you for your work.

Julien.

**Comment by xet7** [comment]
@juliensl 

Cool, nice find :+1: very interesting :) Thanks a lot ! I'll see can I fix this somehow.

**Comment by xet7** [comment]
@justir1234 

Do you have ideas based on above description, where could I start with looking into this?

**Comment by justinr1234** [comment]
@xet7 break it down into individual pieces and root cause each bug one at a time. Look at the flow of the auth and figure out what is causing the bugs. Verify that it is actually a bug. Start with reproduction and understand what the actual bug is.

**Comment by juliensl** [comment]
Hi !

I saw that you fix snap install @xet7 , congratulation !
I'll check if this bug already exist or if it's solve by the upgrade ;) 

I've just one question before. 
My first user, which was the admin, was logged by oauth. Unfortunatly, I droped my server local database, so I lost my wekan admin too ^^'

I saw how to make a new user admin, but I've a stupid question before: How can I connect myself to mongoDB ? O.O

It's a snap local install, using the port 4000 for wekan, I didn't find the answer on internet...

I hope that the problems are solved.

However, congratulation for the new release, I like it !

**Comment by xet7** [comment]
@juliensl 

Thanks!

If you have used oauth, your login username is your email address.

Use nosqlbooster to connect to MongoDB localhost port 27019
https://www.nosqlbooster.com/downloads
It can also connect to server localhost 27019 through ssh with GUI.

At wekan database users collection you can change auth from oauth2 to password by editing it.

**Comment by juliensl** [comment]
Ah good news !

We still have the *unknow error* when we try the first connection time and you can log you at the second time. But the accounts are not mixed after when you another one ! This is a pretty good thinks !

I'll try to reproduce the other connection bug #2534
Let's see !

**Comment by juliensl** [comment]
@xet7 , why did you close the issue if we still have an *unknow error* at the first connection try ?

**Comment by xet7** [comment]
Hmm? Ok I misunderstood what is fixed.

**Comment by juliensl** [comment]
> Currently, when I disable the self-registration and try to sign in with a new oauth user, I've an _**Unknown error**_

> But after some tests, I saw that if I try to log me in a second time, it works! Even if the self-registration still disabled.

This part is not fixed yet.

> And an other fun bug, is that if you try to log you with a _**new**_ oauth user, the last one will be deleted and replaced by the new one, but with the same account (same boards, etc).

This part of the bug is fixed. No more mix between users :smiley:

**Comment by xet7** [comment]
Is this related to #3259 ?

**Comment by juliensl** [comment]
Hi Lauri, 

Nop, #3259  is related to google, what I am talking is for a custom OAuth :)
