### ISSUE TITLE
Remove scrollbars where unnessessary, add where nessessary

### ISSUE THREAD

**Issue by newhinton** [wekan/wekan#2528]
* Wekan version: 2.97
Firefox 67

When a card is opened in the detailview, scrollbars are showing up, presumably because content shifts around the page. This does not look good, but can be fixed quiet easy. Also each swimlane should have it's own scrollbar, for the same reason.

I will create a pr for that some time in the future, but for now i will use this ticket to dokument my ideas:

remove overflow-y: auto; from .board-wrapper .board-canvas
(Removes scrollbar when card was opened)
add overflow-x: auto; to .swimlane (not the class but the object which contains the lists)
(Adds scrollbar to swimlane when more lists are available than screenspace)

However, since you have custom scrollbars in the details-container, it may even be better to use them for the overflow, which i would need to look into

**Comment by xet7** [comment]
@newhinton 

Ok, I'm waiting for your PR to test does it work.
