### ISSUE TITLE
Dont hide the board-overlay when detailsview is opened but not hovered on

### ISSUE THREAD

**Issue by newhinton** [wekan/wekan#2529]
When you open the detailsview, it creates a shadow-overlay which highlights the opened card. When you leave the card and hover above, eg. a different card, the shadow gets removed. In my opinion, it would be better to leave it until the user clicks somewhere. That would reduce the "flashiness" of the current shadow.

**Comment by xet7** [comment]
@newhinton 

Ok, waiting for your PR to test does it improve something.

**Comment by newhinton** [comment]
@xet7 I have set up wekan for development, however i could not find out if there is a 'live reload' or 'hot reload' available for wekan/meteor. Could you point me in the right direction, so that i can quickly see changes from codechanges?

**Comment by xet7** [comment]
@newhinton 

Reload works fastest on Linux that has SSD or NVME disk, running locally or at some fast server. Running under Windows Subsystem for Linux Ubuntu is slow.

**Comment by xet7** [comment]
@newhinton 

Also if you google search how to make RAM-based disk, and run when Wekan installed on that RAM disk, it can be faster.
