### ISSUE TITLE
Gogs issue/commit integration

### ISSUE THREAD

**Issue by yipcma** [wekan/wekan#253]
this is a wild guess but what if we can cross-reference github issue and have a 2-way interaction (so to manage issues, tag commits in kanban itself)? wonder if github has some api to do this...

**Comment by dialogik** [comment]
Yes, github has an API to manage this and there are also a couple of examples for github issues and kanban board integrations: https://www.google.com/search?q=github%20issues%20kanban%20board

**Comment by GammaNu** [comment]
and have it for gitlab could be perfect too !

**Comment by mkaito** [comment]
:+1:

**Comment by amiceli** [comment]
+1 for gogs integration

**Comment by Biromain** [comment]
:+1: for gogs

**Comment by Depado** [comment]
:+1: for gogs !

**Comment by fnkr** [comment]
:+1: for gogs

**Comment by Unknwon** [comment]
:+1: for gogs

**Comment by mquandalle** [comment]
Got it.

**Comment by denisz1** [comment]
:+1: gogs

**Comment by spacekookie** [comment]
Gitlab now has a kanban like board for issues in a gitlab project. Which is pretty cool. 

But I would much rather keep using wekan because it makes it easy to work with people outside of gitlab projects. As well as just having a nicer UI.

So I was wondering, if it was possible to do something similar:

 - A card in wekan is either just a card or linked to an issue in the gitlab tracker
 - An issue in gitlab is either just an issue or (when tagged correctly) becomes a card in wekan.

Moving a card in wekan changes the tag (labels) in gitlab.
Closing the issue in gitlab either removes card from wekan or moves it to a "done" pile.

**Comment by Caballerog** [comment]
gitea +1

**Comment by xet7** [comment]
@andresmanelli has Gogs integration is in progress, [part 1 is already merged](https://github.com/wekan/wekan/pull/1189).

**Comment by killua-eu** [comment]
Added a bounty on this issue. Please see https://www.bountysource.com/teams/wekan/issues

**Comment by xet7** [comment]
@andresmanelli some ideas for Wekan with Gogs:

https://blog.bitbucket.org/2017/09/13/say-trello-to-boards-in-bitbucket/

**Comment by andresmanelli** [comment]
@xet7 I managed to have a basic integration, I am adding some final details before uploading the repo to Github. Here's a preview.

![wekan2gogs](https://user-images.githubusercontent.com/7302217/30462877-f6d458ec-999e-11e7-985b-653ba980ec38.gif)

I am currently adding open/close and comment integration.

### My idea / What is done

- For the moment, columns default to `To Do`, `In Progress`, `Review` and `Done`
- Each column has a label relationship within a given repo, and these labels are synchronized.
- You can activate the repo in **priority** mode or **normal** mode
  - Priority: Is a board where all your priority-labeled issues are shown
  - Normal: Is a board for the repo you activate, with name `username/repoName`
- Cards are synchronized between the priority and normal boards (you can see that in the gif above)
- For the moment my integration is a CLI NodeJS app that handles hooks from wekan/gogs, no webUI for the moment.

In a couple of days I will upload the very first working code.

Any thoughts?

**Comment by kellpossible** [comment]
@andresmanelli Looks good, I've got a very similar approach which I did last year with a custom kanban board application written in python using flask. It was uni-directional in that GOGs issue tracker controlled what it looked like, but there was no ability to edit or drag and drop the issues yet in the kanban board. I used it on a project for a year, and it worked fairly well. Hopefully I get the chance to clean it up, ensure it works with current versions of GOGs/Gitea and open source it.

**Comment by xet7** [comment]
@andresmanelli 

Does the integration CLI NodeJS app do anything other than call Wekan and Gogs APIs ?

Could the same be done with Huginn #1160 that has Web UI for adding workflows with API integrations? It that issue the plan currently is to have Docker compose script similar to these, just include Huginn Docker container:
https://github.com/wekan/wekan-mongodb
https://github.com/wekan/wekan-postgresql

Same idea is in Rocket.Chat integration https://github.com/RocketChat/Rocket.Chat/issues/672#issuecomment-328469079

**Comment by xet7** [comment]
@andresmanelli 

If integration is done with Huginn, it would be easier to customize list names etc at Huginn web interface. There would be no need to touch CLI NodeJS app code that would be running in some container.

**Comment by Caballerog** [comment]
I'm waiting this PR since a long time!

I wish to test this feature :).

**Comment by andresmanelli** [comment]
@xet7 I am not really familiar with Huginn, I will take a look at it. For the moment I'll finish my work in progress, it will not be certainly fancy but maybe it helps while a better integration is developed!

**Comment by xet7** [comment]
This needs testing, pull requests for fixes etc please:
https://github.com/wekan/wekan-gogs

Thanks to @andresmanelli  !

**Comment by killua-eu** [comment]
Released bounty to @andresmanelli , thanks lots for all the work. @xet7, I'll be waiting for https://github.com/wekan/wekan-snap/issues/19 before doing more extensive testing then.
