### ISSUE TITLE
Performance Problems

### ISSUE THREAD

**Issue by nomomnom** [wekan/wekan#2531]
Hey there,
 
We're using Wekan for more than half a year in our company. Since the board is growing we're experiencing a lot of performance issues, which we can't resolve.
We already tried to use more RAM, we already tried to delete and archieve a lot of stories, we already tried to reinstall wekan on a different server and we already tried using wekan with Docker. Unfortunately nothing works and we're getting out of ideas.
Wekan is getting really slow and often crashes while working on it. Sometimes the browser said that a java execution failed. We noticed that this began happening since the board sizes are getting bigger…
 
We're using an Ubuntu VM with Ubuntu Server 18.04.2 LTS (already tested with Ubuntu Server 19.04, no improvements). 16GB of RAM and 4 CPUs. Wekan's version is v2.97.0, working with Snap.
 
Do you have any ideas? What about the Wekan customer support? Would that be an idea? Someone taking a look on our system and checking our performance?

**Comment by xet7** [comment]
Yes I provide Commercial Support https://wekan.team

Please contact me to my email address x@xet7.org
