### ISSUE TITLE
UI: Show visibly when username and email address is editable

### ISSUE THREAD

**Issue by juliensl** [wekan/wekan#2532]
Server Setup Information:

    Did you test in newest Wekan?: yes
    Wekan version: 2.97
    Operating System: Linux
    Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
    Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
    Node Version: 8.16.0

Hi everybody!

Currently, when I'm going on "edit profile", I cannot edit my username.
I think I'm not the first one to speak about this, but I the only field that I found is Issue #112, which is pretty old ^^

Maybe you choose to not enable people to change their username, but personally, it's pretty important, some people will create a new account only because they didn't "choose the right username" at the beginning :/ 

If you choose to not enable it, you should change the UX, because it looks like editable and it's very frustrating XD

Thank you for your work!

**Comment by xet7** [comment]
Well, it depends on admin of that Wekan install.

Admin Panel / Settings / Accounts
- Allow Email Change: Yes/No
- Allow Username Change: Yes/No

**Comment by xet7** [comment]
Well, it could be made to look not editable, when it's not editable.

**Comment by juliensl** [comment]
Ohhhhh my bad ! I didn't see it! 
Sorry, I open this issue for nothing x)

Ok, not exactly for nothing, I still thinking that you should change the design when it's not editable ;)

Thanks a lot Lauri.

Ps: Do I close the issue or you want to keep it opened for the design ?

**Comment by xet7** [comment]
I will keep this open for design.

**Comment by juliensl** [comment]
Hi!

I'm coming back on this topic.
When I choose to enable to change the username, I can change mine in the "edit profile field", but the other people can't do it.

I first thought that only admin can change it, like there is a permission rule missing, but not, other admins can't change it too.

In fact, that enable the username setting only for the person who allowed it in the admin panel, I unselected it with the first admin, selected it with a second admin and permissions changed, now, the second can change his username but not the first ;)
