### ISSUE TITLE
Sandstorm is not updated yet. Newest Snap and Docker v3.x are released.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2533]
Moved to here from https://github.com/wekan/wekan-dev/issues/12#issuecomment-509303500

From @JerryMWeeks 

Just tried on Windows 10 using PowerShell in admin mode, it fails at this:
+ cd /home/wekan/app
+ gosu wekan:wekan mkdir -p ./public/api
mkdir: cannot create directory './public/api': Permission denied
+ cd /home/wekan/app
+ gosu wekan:wekan /home/wekan/.meteor/meteor add standard-minifier-js
error: exec: "/home/wekan/.meteor/meteor": stat /home/wekan/.meteor/meteor: no such file or directory
ERROR: Service 'wekan' failed to build: The command '/bin/sh -c set -o xtrace &&     useradd --user-group --system --home-dir /home/wekan wekan &&         apt-get update -y && apt-get install -y --no-install-recommends ${BUILD_DEPS} &&     pip3 install -U pip setuptools wheel && … etc etc.

Reply from @xet7 

I don't know about wekan-dev, but anyway Wekan master branch builds are broken:
- Docker: I did change [docker-compose.yml to use master branch](https://github.com/wekan/wekan/commit/202cc5a797b6269ec422c6f2e532a49f09d4e30a) but trying to build master branch Dockerfile gives errors you mentioned. I did not get it working yet.
- Snap: master branch [snap build has errors](https://github.com/wekan/wekan-snap/issues/46#issuecomment-508423191)
- Sandstorm: I have not tried master branch yet with building for Sandstorm.

These changes are related to upgrading Wekan from Meteor 1.6.x to Meteor 1.8.1. Previously when meteor-1.8 branch existed, Docker build of meteor-1.8 branch did work, but Snap did not. After moving branches, building Docker does not work.

Currently:
- master branch has Meteor 1.8.1 based Wekan
- devel branch has old Meteor 1.6.x based Wekan
- I have deleted old other branches

When I get master branch working with Snap+Docker+Sandstorm, I will delete old devel branch.

Anyway, currently builds are broken. It's possible to use newest Wekan with `.tar.gz` bundle from https://releases.wekan.team or in any CPU architecture as mentioned at https://github.com/wekan/wekan/wiki/Raspberry-Pi . Also using `rebuild-wekan.sh` scripts options 1 and 2 still works for me, when I build it on Ubuntu 19.04.

All these changes are related to upgrading Wekan dependencies to newest versions, where possible.

**Comment by xet7** [comment]
On Ubuntu 19.04, when using `rebuild-wekan.sh` option 2, I'm also getting file permission errors like
```
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/wekan/.npm/_cacache'
```
Usually Wekan still works.

On Puppy Linux Bionic 64bit, when I install meteor from www.meteor.com as root, clone wekan repo and run as root, without using `rebuild-wekan.sh`:
```
meteor --port 4000 --allow-superuser
```
Then it mostly works, but because `rebuild-wekan.sh` has not been used it still have unicode filename bug:
https://github.com/wekan/wekan/blob/master/Dockerfile#L235

**Comment by JerryMWeeks** [comment]
Not sure if this needs a new issue or comes under the same issue, running command prompt in admin mode, Windows 10, Node etc already well established:
Run: rebuild-wekan.bat
Takes a while, tries to reinstall Node - which seems to work, then hits Meteor and fails:

"Building Wekan."
'meteor' is not recognized as an internal or external command,
operable program or batch file.
'meteor' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the path specified.
'meteor' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\repos\wekan\main.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3


A fair way back in the output:
Meteor has been installed!

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  https://docs.meteor.com
Full output attached:

[rebuild-wekan.bat-output.txt](https://github.com/wekan/wekan/files/3370291/rebuild-wekan.bat-output.txt)

**Comment by xet7** [comment]
@JerryMWeeks 

That .bat file is not fixed yet for Windows. I do really recommend native Linux install when building Wekan, see #2557 

@justinr1234 

I uploaded 2 broken debug snap builds to https://releases.wekan.team/debug/

## Build 19

- Is from MongoDB 4.0.10 deb
- Has mongodb error about missing libcurl.so file.

## Build 21

- Is from MongoDB 4.0.10 tgz lecacy build, that does not have curl, SSL etc.
- Build 21 keeps restarting.
- `/var/log/syslog` shows apparmor errors, because apparmor or snap prevents accessing TCP ports, maybe because of snap strict confinement
- only way to get MongoDB started is to `sudo snap stop wekan.wekan` and `sudo snap set mongodb-bind-ip=''` so that TCP is disabled and Wekan node uses MongoDB unix .sock file for communicating. Then it's possible to login to mongodb with `mongo --port 27019`
- Wekan snap shows errors about migrations. This is maybe because when upgrading to newest MongoDB 4.0.10, mongodump backup needs to be restored without indexes with `mongorestore --drop --port 27019 --noIndexRestore`:
```
2019-07-20T23:01:12Z wekan.wekan[29699]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
2019-07-20T23:01:12Z wekan.wekan[29699]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
2019-07-20T23:01:12Z wekan.wekan[29699]:     at new Collection (packages/mongo/collection.js:97:40)
2019-07-20T23:01:12Z wekan.wekan[29699]:     at packages/idmontie_migrations.js:38:15
2019-07-20T23:01:12Z wekan.wekan[29699]:     at packages/idmontie_migrations.js:255:4
2019-07-20T23:01:12Z wekan.wekan[29699]:     at packages/idmontie_migrations.js:263:3
2019-07-20T23:01:12Z wekan.wekan[29699]:     at /snap/wekan/x2/programs/server/boot.js:419:36
2019-07-20T23:01:12Z wekan.wekan[29699]:     at Array.forEach (<anonymous>)
2019-07-20T23:01:12Z systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
2019-07-20T23:01:12Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
```
- Wekan also complains about boot.js these lines:
That error line is show at this log:
```
root@wekan:/var/log# snap logs wekan.wekan
2019-07-20T23:02:57Z wekan.wekan[6543]:     at /snap/wekan/x2/programs/server/boot.js:419:36
2019-07-20T23:02:57Z wekan.wekan[6543]:     at Array.forEach (<anonymous>)
2019-07-20T23:02:57Z systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
2019-07-20T23:02:57Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
2019-07-20T23:02:57Z systemd[1]: snap.wekan.wekan.service: Service RestartSec=100ms expired, scheduling restart.
2019-07-20T23:02:57Z systemd[1]: snap.wekan.wekan.service: Scheduled restart job, restart counter is at 6.
2019-07-20T23:02:57Z systemd[1]: Stopped Service for snap application wekan.wekan.
2019-07-20T23:02:57Z systemd[1]: snap.wekan.wekan.service: Start request repeated too quickly.
2019-07-20T23:02:57Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
2019-07-20T23:02:57Z systemd[1]: Failed to start Service for snap application wekan.wekan.
```
- On above boot.js code lines are these:
```
      // Allows us to use code-coverage if the debugger is not enabled
      Profile(fileInfo.path, func).apply(global, args);
```

**Comment by xet7** [comment]
@justinr1234 

Those broken debug builds can be tested with:
```
sudo snap install --dangerous filename.snap
```

**Comment by xet7** [comment]
Wekan v3.00 Docker build at master branch now works. I will add other platforms when I get those working. Next I will add meteor bundle, it does not need any fixes, just building it.

**Comment by xet7** [comment]
Newest Wekan v3.00 for Docke at master branch has newest Meteor 1.8.1 and MongoDB 4.0.10, it requires mongodump of previous database and restore with added option --noIndexRestore, see https://github.com/wekan/wekan/wiki/Backup . That is because of major change of MongoDB from v3.2.x to v4.0.10. Also please use newest docker-compose.yml from https://github.com/wekan/wekan master branch.

Devel branch is old with Meteor 1.6.x and MongoDB 3.2.x and it is not developed anymore, and it does not have latest features.

**Comment by xet7** [comment]
Summary of upcoming Wekan Platforms upgrades:
- [Docker](https://raw.githubusercontent.com/wekan/wekan/master/docker-compose.yml): already works, required mongodump of previous and restore with addedd --noIndexRestore
- [Snap](https://github.com/wekan/wekan-snap/wiki/Install): It will be released when I get MongoDB upgrading working automatically. Currently MongoDB 4.x starts but Wekan does not start most likely because of existing old indexes. So this is not fixed yet. When I get it working, I will release automatic upgrade.
- [Sandstorm](https://github.com/wekan/wekan/wiki/Sandstorm): I have not tested building this yet, this also needs MongoDB upgrading working automatically.
- [Meteor bundle](https://releases.wekan.team): Will be released soon.
- [Raspberry Pi and other arm64 etc CPU architectures](https://github.com/wekan/wekan/wiki/Raspberry-Pi): When you see new [Wekan version bundle available](https://releases.wekan.team), you can [Upgrade Bundle](https://github.com/wekan/wekan/wiki/Raspberry-Pi#upgrade-bundle).
- [Univention](https://github.com/wekan/wekan/wiki/Platforms#production-univention-platform-many-apps-and-wekan): When I get new Wekan version working, when install newest Univention upgrades, Wekan will be automatically upgraded to newest Wekan version.

**Comment by sfahrenholz** [comment]
Hello,

is there any news for the snap implementation?

**Comment by xet7** [comment]
@sfahrenholz 

Yes, see above [what I posted 8 hours ago](https://github.com/wekan/wekan/issues/2533#issuecomment-515235545).

**Comment by xet7** [comment]
@sfahrenholz 

It did take a lot of work to get Snap to current state so that Snap build works, and MongoDB 4.x does start. So only thing remaining to fix is that Wekan error, that's probably because of indexes.

**Comment by xet7** [comment]
I don't know how to fix these errors in Snap: https://github.com/wekan/wekan/issues/2533#issuecomment-513506939

Current Snap version is old, and does seem to crash. If someone could help in debugging snap, it would be nice.

It's possible to switch to Docker version with first doing backup:
https://github.com/wekan/wekan/wiki/Backup
with command:
```
mongodump --port 27019
```
And then restoring to Docker with:
```
docker stop wekan-app
docker cp dump wekan-db:/data/
docker exec -it wekan-db bash
cd /data/
mongorestore --drop --noIndexRestore
rm -rf dump
exit
docker start wekan-app
```
There are also other Wekan platforms:
https://github.com/wekan/wekan/wiki/Platforms

**Comment by xet7** [comment]
Related old snap crash https://github.com/wekan/wekan-snap/issues/98

**Comment by xet7** [comment]
I posted about this to snapcraft forum:
https://forum.snapcraft.io/t/can-someone-help-with-getting-wekan-snap-working/12620

**Comment by xet7** [comment]
I also added ask for help to Snapcraft Wekan page:
https://snapcraft.io/wekan

**Comment by xet7** [comment]
Experimental Sandstorm package v3.14 has been published, @ocdtrekkie can test it. Univention package updating will be looked sometime at end of this month.

**Comment by raffaeleabate** [comment]
Hi! 

I do not see any bundle file for arm64 at the moment in https://releases.wekan.team/ .

The only possible installation way on arm64 seems to be via the .img file (which frankly it seems to me a bit cumbersome and insecure). Am I correct?

**Comment by xet7** [comment]
@kairosdojo 

Yes there is bundle wekan-3.15.zip . I added more info to:
https://github.com/wekan/wekan/wiki/Platforms#testing-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures

You don't need .img file.
