### ISSUE TITLE
Feature: Starting day of the week (Sunday vs Monday) 

### ISSUE THREAD

**Issue by ykorzikowski** [wekan/wekan#2535]
There is currently no way to set the starting day of the week (Sunday vs Monday) and it defaults to Sunday on date edit view. It would be great to add an option to configure this. 

See: 

![Bildschirmfoto 2019-07-09 um 20 13 10](https://user-images.githubusercontent.com/20556547/60912609-0aadf200-a286-11e9-9f4f-1f0ef82410bc.png)

**Comment by gruessung** [comment]
+1

**Comment by xet7** [comment]
Target bounty 200 euro, then I will start implementing this.

https://www.bountysource.com/issues/76694702-feature-starting-day-of-the-week-sunday-vs-monday
https://wekan.team/bounties/index.html

**Comment by saschafoerster** [comment]
We also had several issues with items accidentally put on a Sunday, because they thought it is Monday in the first line. I think this is not really a feature to be targeted by money, but rather a bug to be solved by anyone who is able. But anyway, we should support Wekan and it's development. :) So here is my +1 for this!

**Comment by ykorzikowski** [comment]
Just made some research. Maybe https://www.npmjs.com/package/js-datepicker => setting

```
  startDay: 1, // Calendar week starts on a Monday.
```

will do the trick?

**Comment by xet7** [comment]
Sure, with enough Wekan contributors I would get pull requests to all issues and Wekan would be finished :) Anyone can help and add pull requests.

**Comment by saschafoerster** [comment]
@ykorzikowski Okay, let's try the commit here? :) https://github.com/wekan/wekan/blob/devel/client/lib/datepicker.js
(I really have no clue, where to add the option. Maybe here?)

```
 onRendered() {
    const $picker = this.$('.js-datepicker').datepicker({
      todayHighlight: true,
      todayBtn: 'linked',
      language: TAPi18n.getLanguage(),
      startDay: 1,
    })
```

**Comment by xet7** [comment]
@saschafoerster 

I did try adding that `startDay: 1` but it did not make any difference.

**Comment by saschafoerster** [comment]
So I warted to give 15$ via bountysource to this feature request, my PayPal-account shows it as paid, but I am not on the list as a backer... :( https://www.bountysource.com/issues/76694702-feature-starting-day-of-the-week-sunday-vs-monday

**Comment by xet7** [comment]
@saschafoerster 

When did you add that bounty? Maybe it's not immediately visible, and takes some days.

**Comment by saschafoerster** [comment]
@xet7 Yesterday evening. I will wait a little bit, but in times of PayPal and instant payments, I am not really satisfied with their service. ;) I guess there is a bug at their side, I am in contact with their support to find out what went wrong.

**Comment by xet7** [comment]
I would really like if PayPal would be instant. Sometimes I have waited 2 weeks or one month when they "confirm payment". TransferWise is much faster, usually some days. Maybe some day I should figure out some better system.

**Comment by saschafoerster** [comment]
Feedback from Bugbounty: 

> Hi Sascha,
> I'm sorry about the issue.
> We are experiencing some site issues at the moment.
> I have refunded your payment via Paypal.
> I can notify you when the problems are resolved if you like.
> Sorry for any inconvenience
> Johan

**Comment by saschafoerster** [comment]
And the refund was there in an "iffy" :D

**Comment by vogloblinsky** [comment]
+1

**Comment by marc1006** [comment]
This issue can probably be closed since the pull request has been merged.
