### ISSUE TITLE
Broken dashboard tile links

### ISSUE THREAD

**Issue by maokomioko** [wekan/wekan#254]
https://www.dropbox.com/s/n5y3flvk4lg5e2k/Screenshot%202015-08-29%2016.34.04.png?dl=0
Link points to "Board" now instead of /b/%board-name% like it was before

**Comment by mquandalle** [comment]
I can't reproduce this:

![board links](https://cloud.githubusercontent.com/assets/1730702/9567402/0466379e-4f2a-11e5-8fe5-89996d946176.png)

Any more infos? Which {Wekan,browser} version are you using?

**Comment by maokomioko** [comment]
Yesterdays version. Checking from Safari 9, OS X 10.11dev 7 build. 
I have it as a local copy at kanbandevil.eu

**Comment by mquandalle** [comment]
I was able to see the bug in the deployed version. For some reason this version have a number a JS I have not seen at any stage of the development (things like `Error: There are multiple templates named 'boardList'. Each template needs a unique name.`). It seems that some files are included twice (but with different hashes). Is it possible that the app directorty contains additional files not present in the git history?

**Comment by maokomioko** [comment]
Only meteor/.local stays after each upgrade. I will try to update it one more time now, just to be sure.

**Comment by maokomioko** [comment]
Can confirm that it works as intended now, after I made a clean pull from the repository.
Thanks for digging it out!

**Comment by mquandalle** [comment]
You’re welcome :-)
