### ISSUE TITLE
"Import board from previous export" failing on export from previous version

### ISSUE THREAD

**Issue by arthurlogilab** [wekan/wekan#2543]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: no
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? 
* Wekan version:     2.56~ynh1
* If this is about old version of Wekan, what upgrade problem you have?: not packaged yet for yunohost
* Operating System: yunohost/debian
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): https://github.com/YunoHost-Apps/wekan_ynh/
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 8.15.1 
* MongoDB Version: 3.2.11-2+deb9u

**Problem description**:

We have a wekan 0.10.1 running with some data it in (early adopters!). We'd like to export and import a new version of wekan. 

When we "Import board from previous export" with the json exported by version 0.10.1 we get the following traceback in the logs, the board is created with some attributes (members, columns, labels, color of the board), but no cards. 

```
Exception while invoking method 'importBoard' { stack: 'TypeError: Cannot read property 'forEach' of undefined
    at WekanCreator.createSwimlanes (models/wekanCreator.js:479:20)
    at WekanCreator.create (models/wekanCreator.js:794:10)
    at DDPCommon.MethodInvocation.importBoard (models/import.js:27:20)
    at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)
    at packages/check.js:128:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/mdg_meteor-apm-agent.js:2617:38',
```

Reference to the issue in the yunohost distribution of wekan : https://github.com/YunoHost-Apps/wekan_ynh/issues/45

We can perfectly understand that importing from such an old version would not be supported, but if you have any tips on how to fix this or modify the json file so it can be imported, it would be great !

**Comment by xet7** [comment]
You need to use mongodump for backup of old Wekan, and mongorestore to new Wekan:
https://github.com/wekan/wekan/wiki/Backup

**Comment by arthurlogilab** [comment]
@xet7 thank you so much for the prompt response ! I'm going ahead to read the documentation and use that. 

Does that work for restoring into a wekan that is already populated with data ? or do I have to restore into an installation on the side, then export (new format I guess) and run my import in the existing new version ?

**Comment by xet7** [comment]
@arthurlogilab 

1. From new Wekan export all boards to Wekan JSON.
2. Backup new Wekan with mongodump.
3. Backup old Wekan with mongodump.
4. Restore old Wekan data to new Wekan with mongorestore.
5. Restore new Wekan JSON exported boards by importing them.

**Comment by arthurlogilab** [comment]
Am trying to the instructions suggested by @xet7 

First thing : the mongorestore requires `--drop` for it to work. 

Second, I have to go through user records to change the URL of the avatar (did this in python, maybe there is a way with mongo cli) : 

```python
import pymongo
from pymongo import MongoClient
client = MongoClient()
db = client.wekan
users = db.users
for doc in users.find():
   if doc['profile'].get('avatarUrl'):
     doc['profile']['avatarUrl'] = u'/wekan' + doc['profile']['avatarUrl']
     users.find_one_and_replace({u'_id': doc['_id']}, doc)
```
Tested this out in a sandbox. 

Problems to handle : 

* keep the configuration (LDAP on the new setup) 
* find a way to `export all boards to Wekan JSON` without manually going into each one through the web ui
