### ISSUE TITLE
"Delete" user buttons don't ask for confirmation

### ISSUE THREAD

**Issue by loucurapt** [wekan/wekan#2550]
The "Delete" user buttons, including the one in the top-right user profile menu, don't ask for any confirmation when clicked. They just straight up delete the user without any warning!
Not only that, the "Delete" button the the profile menu is gray, so it looks like it's disabled.

This action deletes the user and, as far as I know, can't be reverted!
These buttons should be red, and they should ask for confirmation with a big red warning text.
Maybe the confirmation dialog should require the user to input some confirmation text.

**Comment by bhueck** [comment]
Oh yes....i just click this button a few minutes ago. Annoying...
