### ISSUE TITLE
Wekan 2.99 is crashing at startup

### ISSUE THREAD

**Issue by MJO9** [wekan/wekan#2557]
I pulled Master to my local branch and then tried to just get a new clone of master to my machine and it's not starting. I tried it on window, WSL and on ubuntu.
On windows it stuck at startup giving:

> Unexpected mongo exit code 62. Restarting.

 I get code null if I try to reset meteor or delete local meteor packages cache

On WSL and ubuntu I get the same issue at startup, it's stuck at building for web.browser

Anybody having this issue?

**Comment by xet7** [comment]
Usually Wekan crashes if there is not enough free RAM.

**Comment by xet7** [comment]
It is not "stuck". It is building Wekan, it takes a lot of time. Just wait.

**Comment by xet7** [comment]
I recommend building on Ubuntu. Windows has much slower filesystem than Ubuntu. Meteor has a lot of Javascript files.

**Comment by xet7** [comment]
All these Spectre and Meltdown mitigations have made building Wekan slower. Wekan also has a lot of functionality.

**Comment by xet7** [comment]
If you like to build wekan faster, search web how to make RAM disk, and copy files to that RAM disk, and build there.
