### ISSUE TITLE
Cards no longer visible in the lists and swimlanes views

### ISSUE THREAD

**Issue by timothyparez** [wekan/wekan#2558]
**Server Setup Information**:
  
Wekan Version v2.97.0  
Node Version: v8.16.0  
Host: Linux / Docker (updated every night)  
  
**Problem description**:  
  
We have a wekan with about 16 boards.    
To one of them we added a large number of cards in a number of different swimlanes.  
It worked fine at first but then after one of the nightly updates the cards were no  
longer visible in the list/swimlane views, but they do show up in the calendar view.
  
I looked in the archive, but there is nothing there either.
  
This issue only occurs for this single board, all the other boards are working fine.  
  
![wekan](https://user-images.githubusercontent.com/2060470/61586357-896b2f00-aba4-11e9-8d25-31726ac8b771.gif)

The web console does not show anything.

The last entry in the logs show this:

```
Exception while polling query {"collectionName":"cards","selector":{"parentId":{"$in":["QYHTJkKtTmE282jh3","XpsPFTP3T2x39pTJe","2hhhQsuMoafdnC2JY","ESrN3b7kepErZ5s2N","DFQP8jfJ7AJKtxqfi","pqGk5h5nDrHTTHDZW","zwzNHL3KG7NSggTTc","3uRf4SYqpaZbd746H","35fm5FAPDaXaKE5fq","WYEa4krwxEZMQnczJ","jpMXfbpHSy5NwLMfr","Txp8jHBPfDjbsCmtq","r4RzKmnRJcYCsptAk","sC5YGK7EddoESv9XQ","zN6df4Nf5NZ3yDWrC"]}},"options":{}}: MongoError: interrupted at shutdown
    at Function.MongoError.create (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Exception while polling query {"collectionName":"checklistItems","selector":{"cardId":{"$in":["QYHTJkKtTmE282jh3","XpsPFTP3T2x39pTJe","2hhhQsuMoafdnC2JY","ESrN3b7kepErZ5s2N","DFQP8jfJ7AJKtxqfi","pqGk5h5nDrHTTHDZW","zwzNHL3KG7NSggTTc","3uRf4SYqpaZbd746H","35fm5FAPDaXaKE5fq","WYEa4krwxEZMQnczJ","jpMXfbpHSy5NwLMfr","Txp8jHBPfDjbsCmtq","r4RzKmnRJcYCsptAk","sC5YGK7EddoESv9XQ","zN6df4Nf5NZ3yDWrC"]}},"options":{}}: MongoError: interrupted at shutdown
    at Function.MongoError.create (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

But nothing is added to the log as I navigate the site.

**Comment by xet7** [comment]
@timothyparez 

If some card is only visible in list or swimlane view, try to move it to other list or some other place and back, to see does it come visible to other view.

**Comment by timothyparez** [comment]
No cards are visible in list or swimlane vies (see the gif above)  
They are only visible in the calendar view and if you export the board to json.  
  
So it seems the data is still there but just not rendered in swimlane or list view.  
This is the first time we added so many cards to a board.

**Comment by timothyparez** [comment]
So @xet7 is there anything else I can provide, because the problem persists.

**Comment by timothyparez** [comment]
Two seconds after the previous message I was able to figure out what happened.
Someone moved an entire list to the archive, and we had not realized it.
When I was looking for the items in the Archive I never even clicked on list.
So I saw the "todo" list and assumed that's where all the items were, but instead
the items were in an archived list and someone simply created a new todo list.
