### ISSUE TITLE
Feature request: Cards with due date should be shown in calendar 

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2562]
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes 
* Wekan version: v2.97.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Synology DSM 6.2.2
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: v8.16.0
* MongoDB Version: mongo:3.2.21  

**Problem description**:
- The calendar should use only the due date to show items in calendar view. It would make workflows much more useful. Actually items are only showing in calendar view, when the start date and the end date are set. This is useless, because the end date should be set, when the task is done, so you can only use the calendar watching back, what has been done. Most of the time you use calendars to see what should be done and when. How many things are due at the same time. These informations can't be read from the calendar-view. 

This topic has a rather long story in the other issues here: 
The first request was in #55, which was closed because wekan had already a due date, but not a calendar, which got a separate issue #808. 
https://github.com/wekan/wekan/issues/55#issuecomment-280938794

The calendar was implemented with this pull from @TNick: "Calendar #1728 and #1752. There, he also asked for feedback, where multiple solutions came up, which used all the dates available: "Beginn, Start, Due, End". But in the end nothing changed. Only when start and end where defined, the calendar worked. 

After the pull request successfully being integrated, a feature request and a bug report followed, which where integrated into different milestones, but actually touched the same problem: 
- Feature Request: Everything with a date should be visible in the calendar #2190  
- Milestone 36: 2019-07-31 Teams https://github.com/wekan/wekan/milestone/36
I don't think this feature request is faisible without filling the calendar with useless informations multiple times. 

- Feature: Calendar-View: https://github.com/wekan/wekan/labels/Feature%3ACalendar-view
- Bug: Calendar Empty. Or: Items in calendar only shown if they have start AND end date? #1998. The last comment there also asks for the due date to be shown: 
https://github.com/wekan/wekan/issues/1998

I hope this little history shows the importance of the due date being used for the visibility in the calendar at the core of things. I also agree if start and end date are optionally shown in calendar, but the first and standard should be the due date.

**Comment by grmpfhmbl** [comment]
> Actually items are only showing in calendar view, when the start date and the end date are set. This is useless, because the end date should be set, when the task is done, so you can only use the calendar watching back, what has been done.

I strongly disagree with that. If I have a card like "XYZ Workshop" or "System Maintenance" I need the behavior the calendar has at the moment. I know when that event will start and when it will end and it has no due date. I agree though that having cards with only a due date showing up in the calendar would be desirable.

As I see it there are basically the following options:

- A card has a start date and an end date (with time set): it should be shown exactly as it is shown at the moment.
- A card has a start date and an end date (without time set): it should be shown as "all day event". In case start date == end date it should be an "all day event" for that exact date.
- A card has a due date (with time): it should be shown as an event with the shortest possible length (I guess 30min?)
- A card has a due date (without time): it should be shown in the calendar as "all day event"

A card should have either set
- no date at all
- a start and an end date (either both with time or both without time)
- a due date (either with or without time)

Not sure if open ended cards make a lot of sense in the Kanban context.

**Comment by saschafoerster** [comment]
@grmpfhmbl As we were using Trello before, we were all happy with just a nice due-date feature. We use it more in content-planning-context, so we can see, what type of content has to be posted at a certain time. 
So maybe, as I don't care so much about "received"-, "start"- and "end"-dates, it could also be possible to think of an option, which dates do you really need. 
- Simple date: just due-date is shown (would work in calendar view as you described)
- Kanban style: as before (with your options described before as well)
For us it would also declutter the cards-view from fields, we never use in any card. Right now we have to set three dates, to make wekan functional: start and end date, so we can do some content planning, and due date to be reminded.
And even there are still some things to think of (or debug): 
Moving of cards should also work, if start and end date are on the same day. But what happens with the due date? Should it also be moved as the other dates? What if you only have due dates? I think due-dates should be relative and moved with start and end. But I am sure, not everyone is happy with that:  
https://github.com/wekan/wekan/issues/2601

And maybe we should think, which notifications are useful for the 4 different dates:
https://github.com/wekan/wekan/issues/2567

**Comment by jhgovsi** [comment]
totally agree with @saschafoerster

**Comment by saschafoerster** [comment]
I think @whowillcare did a big step forward with his pull request: https://github.com/wekan/wekan/pull/2738/

For my needs, this is fine, even though some little details like moving cards in calendar view still don't work reliably or as a would expect. But maybe it is better to put this in separate issues. if you like @xet7, you can close this.

**Comment by saschafoerster** [comment]
Solved. https://github.com/wekan/wekan/commit/6b4613d3ed6020b4072fe6540da5fdb0b2e85ac7
