### ISSUE TITLE
Any open sourcing tool can count task status of Wekan?

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2564]
I remember someone showing his screen. He used an open source software to count the information/status of wekan's task, such as the number of team members, the list of red tags, and so on.

does anyone know this kind of tool?

thanks

**Comment by xet7** [comment]
@javen9881 

Do you mean those at top of Wekan README, like Open Hub?
https://github.com/wekan/wekan

Or those at GitHub Insights?
https://github.com/wekan/wekan/pulse

**Comment by xet7** [comment]
@javen9881 

I really welcome everyone to help with Wekan GitHub issues, adding fixes as pull requests, and adding commments about duplicate issues and what can be closed. It's much better than just looking at stats :)
