### ISSUE TITLE
Feature: Create new card from checklist item

### ISSUE THREAD

**Issue by alexanderadam** [wekan/wekan#2565]
## Issue

It would be nice if it would be possible to create a new card from a checklist item.

Maybe something similar to this:
![ConvertChecklistItemToCard](https://user-images.githubusercontent.com/372620/61862749-aa968d00-aece-11e9-9e27-fff34a0fd32d.gif)

PS: someone [asked this a while ago](https://discourse.wekan.io/t/how-to-create-a-new-card-from-a-checklist-item/470) in the board

**Comment by xet7** [comment]
@alexanderadam 

Wekan already has in card hamburger menu feature `Copy Checklist Template To Many Cards`. How would this be much different?

**Comment by xet7** [comment]
Hmm, actually it seems to be different feature. So when checklist item is converted to card, is the checklist item also removed from checklist?

**Comment by alexanderadam** [comment]
Yes the item will be removed from the checklist as well. What would be the use case for having it duplicated?

**Comment by xet7** [comment]
Use case for having it duplicated is Templates.

That feature is Checklist Templates. So you create template once, then duplicate it, then use it each time you need it as a start of step-by-step process.

Other templates are described herer:
https://github.com/wekan/wekan/wiki/Templates

**Comment by xet7** [comment]
Yes, the idea in checklist templates is, that in that JSON is card titles, you can modify those titles and add new ones to it, and then checklist is copied to those titled cards.

**Comment by xet7** [comment]
Anyway, Templates if completely different feature than this `Convert to Card` feature. I did not even know that Trello feature exists before you added this issue and animgif.
