### ISSUE TITLE
Certain Wekan Board right after Login

### ISSUE THREAD

**Issue by DerPeppi** [wekan/wekan#2566]
Hi,

we set up an Raspberry Pi with Chromium in kiosk mode. We would like to see a certain board after the Login. Is there any way to do this?

Thanks for you answers in advance!

**Comment by xet7** [comment]
@DerPippi 

Do you mean:

a) Automating both login and seeing certain board ?

b) After login, automating seeing certain board ?

**Comment by DerPeppi** [comment]
Hi xet7,

we found a way to get this done just 2 Minutes ago. We figured out that you have to tag the boeard as one of you favorites and then use the direct link to the board. Works just fine now!

Anyway...thanks for your (almost) help!
