### ISSUE TITLE
Wekan "latest" Docker image won't start, but "devel" does. "MongoError: database name must be a string"

### ISSUE THREAD

**Issue by archerkg** [wekan/wekan#2568]
**Server Setup Information**:

* Did you test in newest Wekan?: 

* Wekan version: "Latest" from [https://hub.docker.com/r/mquandalle/wekan/builds](https://hub.docker.com/r/mquandalle/wekan/builds)

* Operating System: Unraid

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx

* MongoDB Version: "Latest" from [https://hub.docker.com/_/mongo?tab=tags](https://hub.docker.com/_/mongo?tab=tags)
* ROOT_URL environment variable https://wekan.nameofmysite.com:

**Problem description**:
- *REQUIRED: There's nothing to show for a gif, its an error message. Nginx shows a 502. The docker log shows:

```
/build/programs/server/node_modules/fibers/future.js:313
throw(ex);
^
MongoError: database name must be a string
at Function.create (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:43:12)
at validateDatabaseName (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/db_ops.js:720:22)
at new Db (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:181:3)
at MongoClient.db (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:268:14)
at packages/mongo/mongo_driver.js:186:25
at runWithEnvironment (packages/meteor.js:1286:24)
```

- *Explain steps how to reproduce*

Issue occurs with "latest" build of mquandalle's Wekan Docker image. Works fine when I switch to the "devel" tag on the mcquandalle dockerhub repo.

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*

Literally just a 502 bad gateway error.

- *If using Docker, what does show command `sudo docker logs wekan-app` ?*

I posted this above, where it requests for an error message.

Additionally, I'd like to mention that I haven't touched any of my Wekan/docker settings in quite some time, i.e. the configs haven't changed. I don't believe my OS has been updated in the last few days either.

Other users have had this issue: [https://forums.unraid.net/topic/50959-kru-x-wekan-and-mongodb-wekan-templates/page/2/](https://forums.unraid.net/topic/50959-kru-x-wekan-and-mongodb-wekan-templates/page/2)

I couldn't find a solution to this anywhere else. The only thing that has worked is switching the Wekan branch from "latest" to "devel" in the Docker commands

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v300-2019-07-25-wekan-release

**Comment by xet7** [comment]
https://github.com/wekan/wekan/issues/2533#issuecomment-515229756

**Comment by wuast94** [comment]
i have the same problem. fresh install of weaken and mongo:4.0.11
