### ISSUE TITLE
[Feature] 'Requested By' and 'Assigned By'

### ISSUE THREAD

**Issue by JaniDJ** [wekan/wekan#2572]
Hey there,

it would be really helpful if you could select users from some kind of dropdown menu. Sadly enough I can't delete the content of this filed if saved. You can only reduce it to one character. I'd appreciate a fix. 

Chears Jani

**Comment by saschafoerster** [comment]
And as we don‘t use it at all, it would be nice to have it optionally turned off to have less clutter.

**Comment by xet7** [comment]
This can be hidden at Board Settings / Card Settings.
