### ISSUE TITLE
High CPU usage after a few days

### ISSUE THREAD

**Issue by CreedDE** [wekan/wekan#2574]
**Server Setup Information**:
* Wekan version: 2.97
* Node version: 8.16
* Operating system: Ubuntu 16.04
* Deployment method: Snap

**Problem description**:
The CPU of the system use each day even more power. If we restart wekan, the cpu is on 
5%. Next day the cpu use 15% and its going each day even higher. On 40% the performance of 
our wekan is very slow and no one can use it. We are up to 200 users that actually using the wekan.

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
The console of my webbrowser show me that
`WebSocket connection to 'wss://xx.xx.de/sockjs/570/c_8tzkmr/websocket' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET`

- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*

![Unbenannt](https://user-images.githubusercontent.com/41332362/62127574-b02b1300-b2d2-11e9-85b6-74ff33482f15.PNG)

**Comment by xet7** [comment]
@CreedDE 

Do you have some webserver like Nginx or Apache in front of Wekan? Is websockets enabled for that webserver? See config examples at Wekan GitHub wiki.

Is server running somewhere that does not support websockets, like for example Google cloud when I last tested it there?

How much RAM is available, is there any free RAM ? What does show `free -m` ? Or is server swapping?

Does server have SSD or NVME disk?

**Comment by xet7** [comment]
From those logs it seems that something is blocking websockets. Do you have some websocket firewall lik F4 in your network?

**Comment by CreedDE** [comment]
I didnt really know that much about the server, because i didnt install it. Actually i can say that we got 8GB of RAM and only 2GB are used so we have 6GB free space.

**Comment by xet7** [comment]
@CreedDE 

Would it be possible for you to ask from the person that installed it ?

Also, can you try newest Wekan Docker version that has docker-compose.yml at master branch of https://github.com/wekan/wekan ? See https://github.com/wekan/wekan/wiki/Backup about backup/restore with --noIndexRestore.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2533
