### ISSUE TITLE
comment-editor marking issue

### ISSUE THREAD

**Issue by thomasbaumgarte** [wekan/wekan#2575]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: YES
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: v3.02.0
* Operating System: Win10
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Node Version: v8.16.0
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://wekan.webvariants.de/

**Problem description**:
Hello, I am currently experiencing a strange issue with adding a comment to any kind of ticket. If I want to mark a line within the comment editor, via mouse, it suddenly disappears when I release the left mouse-button and bring the pointer over the border of the editor. Any other marking method seams to work just fine. 
![wekan magic](https://user-images.githubusercontent.com/53519693/62208372-f2b62380-b396-11e9-95c3-2a8655f0bd9d.gif)

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/2593
