### ISSUE TITLE
Mobile problem with immediate moving of columns instraf scrolling

### ISSUE THREAD

**Issue by nickbe** [wekan/wekan#2579]
When opening wekan on a mobile browser you cannot scroll the „vertical“ board because instead the „columns“ are moved around

**Comment by StanESmith** [comment]
Agreed, was just about to come and post about this one. If the column width sizes are shrunkin down a bit to the left or right would allow a section to act as a scroll bar. This would greatly increase the usability on mobile devices since a mobile app hasn't been pushed out.

**Comment by nickbe** [comment]
I'd rather suggest completely disabling the movement of columns in mobile view. I think when working on a mobile device it's more about actual card work and not changing the layout of columns.

An even better solution would be to let us toggel editing of colums from the board settings. 
Several times now I had to reorder the columns because a user would simply reorder them by accident. So if the columns are locked by default and only the board owner would be able to edit them - that would really help.

**Comment by compumatter** [comment]
Freezing / Locking columns would be of value in both the mobile application but also in the existing desktop layout when more than one user is interacting with the board.  If I create a board, I don't want it modified by other users.  If there was a setting for this it would at least make that less likely to be rearranged without intention.

This would also put us one step closer to mobile use.   

**These two changes would allow for immediate use in mobile environment** while future app considerations are being thought out.

1. 1. Ability to lock the columns so finger touches do not drag them.
2. A 'Move To' button allowing you to move a card to another column 

Jay

**Comment by xet7** [comment]
Moved to #2081
