### ISSUE TITLE
Cant install wekan over https://packager.io/gh/wekan/wekan

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2582]
I try to install wekan about https://packager.io/gh/wekan/wekan

So i follow the specify steps, but i get follow error message on "apt install wekan"
![image](https://user-images.githubusercontent.com/6977657/62423165-0d9dd600-b6be-11e9-84dc-ca33e3f6b1fb.png)

This means, libreadline7 and libressl1.0.0 cannot installed. 

when i try apt install libreadline7 
libreadline7 > there is no install package

try with ubuntu 18.04, 18.10 and 19.04

**Comment by xet7** [comment]
@sfahrenholz 

Thanks for testing! I will look how to add those missing dependencies.

**Comment by sfahrenholz** [comment]
for 19.04 i think i found the problems

libreadline7 is not more supported, so i try it with libreadline8
libssl1.0.0 is not more supported, libssl 1.1.1b is the current version

**Comment by xet7** [comment]
I did change dependencies, let's see does it work any better:
https://github.com/wekan/wekan/blob/master/.pkgr.yml

**Comment by xet7** [comment]
It will take some time to build.

**Comment by sfahrenholz** [comment]
the installation on 18.04 are complete, thanks for this.
but wekan does not start.
is there any documentation to how start wekan with packager? (I dont used it before)

**Comment by xet7** [comment]
https://packager.io/
http://doc.packager.io/documentation/

It would be nice if you have time to look how it works, is something missing, etc, and add comment about it to this issue.

**Comment by sfahrenholz** [comment]
wekan run web

```
 info it worked if it ends with ok
1 verbose cli [ '/opt/wekan/.heroku/node/bin/node',
1 verbose cli   '/opt/wekan/.heroku/node/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.10.0
3 info using node@v6.17.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/opt/wekan/.heroku/node/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /opt/wekan/.heroku/node/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /opt/wekan/.heroku/node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /opt/wekan/.heroku/node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/opt/wekan/.heroku/node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/opt/wekan/.heroku/node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/opt/wekan/.heroku/node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /opt/wekan/.heroku/node/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
4 verbose stack     at /opt/wekan/.heroku/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:457:3)
5 verbose cwd /opt/wekan
6 verbose Linux 4.15.0-47-generic
7 verbose argv "/opt/wekan/.heroku/node/bin/node" "/opt/wekan/.heroku/node/bin/npm" "start"
8 verbose node v6.17.1
9 verbose npm  v5.10.0
10 error missing script: start
11 verbose exit [ 1, true ]
```

**Comment by xet7** [comment]
Heroku? There are some Heroku Wekan GitHub issues open, they are listed at wiki:
https://github.com/wekan/wekan/wiki/Heroku

I have not tested Heroku yet.

**Comment by xet7** [comment]
This is old Heroku config file:
https://github.com/wekan/wekan/blob/master/app.json

**Comment by xet7** [comment]
Wekan currently uses newest NPM and Node 8.16.0 and MongoDB 4.0.11. Maybe some start script is missing from somewhere?
