### ISSUE TITLE
Email Setup routines:SSL23_GET_SERVER_HELLO:unknown 

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2583]
Hi

I am trying to set up Smpt but I am getting this error below when I try to send myself a test email

```
Sending email failed
Error trying to send email: 139668140177216:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

```

My Email server uses 587 and support STARTTLS. 

I enable TLS in the settings. 

I am using Docker-Compose Wekan version `v3.03`

**Comment by xet7** [comment]
```
- MAIL_URL=.....
```
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#starttls-sending-test-email-failed

**Comment by gerroon** [comment]
Hi

Just to make sure, so I am not supposed to add this stuff in Wekan itself? It works only with env variables?

**Comment by xet7** [comment]
Yes, this is env variable setting.

**Comment by gerroon** [comment]
Thank you, sorry about the noise. I will try it then close the bug
