### ISSUE TITLE
REST API new_custom_field errors

### ISSUE THREAD

**Issue by JimCircadian** [wekan/wekan#2586]
## Issue

Attempting to create a edit a custom field against the REST API results in an error saying that boardIds should be an array (see below)

**Server Setup Information**:

* Did you test in newest Wekan?: not the latest, just from the snap
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes, other API calls work fine
* Wekan version: 2.97
* Deployment Method: snap

Referencing https://wekan.github.io/api/v3.00/#new_custom_field

**Problem description**:

Running a request from python to wekan using requests:

```    
    json_data = json.dumps({
        'name':    name,
        'type':    type,
        'showOnCard':  show,
        'automaticallyOnCard': automatic,
        'showLabelOnMiniCard': showMini,
        'authorId':    author_id,
    })
    print(json_data)
    return requests.post("{}/api/boards/{}/custom-fields".format(config.url, board_id),
                     data=json_data, auth=auth_broker).json()
```

Produces the following JSON for the request:

`{"name": "project_id", "type": "text", "showOnCard": true, "automaticallyOnCard": true, "showLabelOnMiniCard": false, "authorId": "fs3ScWXX597BLHkE3"}`

The boardId seems to be pulled from the URL parameter for boardId, so I'm unsure why this error is coming about? Manually specifying boardIds as an array in the JSON doesn't circumvent the issue. 

- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*

Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: Error: Board ids must be an array
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at getErrorObject (packages/aldeed_collection2-core.js:480:15)
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at packages/matb33_collection-hooks.js:127:46
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at Object.directOp (packages/matb33_collection-hooks.js:47:27)
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at models/customFields.js:250:36
Aug  6 15:07:21 bsl-wekan-dev wekan.wekan: at packages/simple_json-routes.js:98:9

**Very happy to diagnose further/look at submitting a pull request to fix this but prefer to check that I'm not doing some silly first!**

I've checked the history of models/customFields.js and it doesn't look like anything after 2.97 snap has altered this behaviour, so believe myself not to be raising this erroneously!

**Comment by xet7** [comment]
Please test with newest Wekan v3.13

**Comment by xet7** [comment]
Please check custom fields API code:
https://github.com/wekan/wekan/blob/master/models/customFields.js#L230

**Comment by JimCircadian** [comment]
Thanks @xet7 working on it now... ;-)

**Comment by JimCircadian** [comment]
Hello again

So I've debugged it and want to confirm that it appears to be a bug in between Wekan and the MongoDB model

![wekan-custom-field-post-error](https://user-images.githubusercontent.com/731727/62869233-59c8c600-bd0f-11e9-91ef-995e7ae10bd5.png)

Quite happy to provide a fix, but I'm not natively a Node/Meteor developer so it'll take me a little time to sort it out properly ;-)

**Comment by max0013** [comment]
Hello,

Tel me I have to open a new issue.
I try to update custom field through API REST... 
How can I do that ? 

Thanks
