### ISSUE TITLE
Unable to change any user settings (except Admin) after fresh Wekan installation

### ISSUE THREAD

**Issue by gsikalu** [wekan/wekan#2591]
## Issue
I've installed fresh copy of Wekan (with Snap). After installation mail server was properly configured. I've created first account and I was able to Edit Profile, Change Language and etc.
Authentication method is Password without LDAP connection yet.
The problem was introduced when the second user was added.
User can log in but there is no possibility to:
 - edit profile (no changes shows, eg. after filling Full Name field it reverts to blank state)

 - change language (as above, when trying to switch language it switches back to default one)
![obraz](https://user-images.githubusercontent.com/53871639/62638454-ca519a80-b93d-11e9-878f-0e34ff2a282d.png)

![obraz](https://user-images.githubusercontent.com/53871639/62638362-98403880-b93d-11e9-8cf0-e5698deed2c1.png)

Of course in Admin Panel/Settings/Accounts all fields are marked "Yes" (so all changes should be available)
![obraz](https://user-images.githubusercontent.com/53871639/62638501-e48b7880-b93d-11e9-9d41-b0a32a66975b.png)

Wekan 3.08 build with SNAP (date 20190807/17:00) Centos 7
No http frontend (checked with nginx first, but problem is the same without any)

root-url="http://wekan.not-informatyka.pl" and address is resolved to internal network class
Logs shows no issues - attached below.

[wekan.log.txt](https://github.com/wekan/wekan/files/3477938/wekan.log.txt)

**Comment by xet7** [comment]
Please try Wekan v3.11. Automatic update or manually:
```
sudo snap refresh
```

**Comment by road42** [comment]
@xet7 This one is bigger.

- My users cannot change their profile any more
- they cannot favorite boards (or unfavorite)
- switching the view from list to swimlane to calendar is not possible any more

Browser console just prints: "update failed: Access denied".
Only the full wekan admin can change the values (isAdmin)

**Comment by road42** [comment]
we use docker (image 3.11) and mongodb

**Comment by sclerc-chss** [comment]
this is the same bug than #2590

**Comment by xet7** [comment]
Moved to #2590
