### ISSUE TITLE
Theme Suggestion: Natural

### ISSUE THREAD

**Issue by compumatter** [wekan/wekan#2592]
## Issue

**Problem description**:
It was suggested that this is the place I should upload a recommended theme suggestion / screen mockup.

Name it what you'd like. I'm thinking "Natural, Forest, Earthy" etc...

I hope you'll consider it.  Thanks for your great product.

![theme-suggestion](https://user-images.githubusercontent.com/121611/62656333-ce1ef600-b918-11e9-8175-27dc7980d366.jpg)

**Comment by compumatter** [comment]
I really wanted to get this going and did not have time to wait it out.  So I devised a small hack that works very well and I wanted to pass it along.

We spent many hours finding out where their CSS styles were being pulled from and wrote some code to hack it as needed.

Our Wekan is a native install. Not in snap or docker. We are unsure where the snap / docker css file is located but this same method will apply to those environments once you find out that location.

We have found the only css file WeKan uses is in:

...bundle/programs/web.browser/eaea2befda1d3ddf4f661e46a5fd12c368801df9.css
Identifying Theme Elements
We identified which colors were being used for what theme elements using any browsers developer toolbar.

Create your own wekan_styles.css file
From the previous section we identified the following elements as requiring color changes.

We inserted these elements in a new stylesheet file called wekan_styles.css and added our new style values.

.list-header{
        background:#667968;
        color:#FFFFFF;
}
#header-quick-access{
        background:#2d392b !important;
}
.swimlane .swimlane-header-wrap{
        background:#c2c0ab;
}
#header,.board-backgrounds-list .board-color-belize.background-box, .board-color-belize#header, .board-color-belize.sk-spinner div, .board-list .board-color-belize a{
        background:#121306 !important;
}
#header{
        border-bottom:solid 5px #c5c3a0;
}

body button{
        background:#a6a780 !important;
}
a.js-open-board.board-list-item{
        background:#b3aa89 !important;
}
Run Wekan_add_styles.php file
Lastly we've created a wekan_add_styles.php file which can be run from the command line.

This is it's contents.

#!/usr/bin/php
<?PHP

# location of WeKan css file.  We will copy this file to a same named.css.original in the same filepath so it can be restored as needed
$css_file="/SM/data-drive/smw_projects/public_html/bundle/programs/web.browser/eaea2befda1d3ddf4f661e46a5fd12c368801df9.css";

if (file_exists($css_file.".original")) {
        # since .worked file exists, copying it back so we start with default blue theme
        echo "Copying .original to css file\n";
        copy($css_file.".original",$css_file);
} else {
        # copy original to a safe location before making changes
        echo "Copying css file to css.original\n";
        copy($css_file,$css_file.".original");
}

$get_css="\n\n".file_get_contents("wekan_styles.css");
file_put_contents($css_file,$get_css,FILE_APPEND);

echo "File appended successfully";
?>
You'll notice in that php code we create a safe copy of the original css file and call it ....css.original

Any time we make a theme change we copy the css.original back on top of the css file so you're always starting with the out of the box version.

The code then grabs the contents of the wekan_styles.css file and appends them to the bottom of that eaea2befda1d3ddf4f661e46a5fd12c368801df9.css file.

Clear Your Cache
You must clear your browsers cache before the new theme changes will be visible.

**Comment by xet7** [comment]
It is explained here how Wekan themes work:
https://github.com/wekan/wekan/wiki/Custom-CSS-themes

You can fork Wekan repo, commit your changes to your fork, and make pull request.
