### ISSUE TITLE
Is there anyway for me to follow wekan release updates through rss(atom)?

### ISSUE THREAD

**Issue by GammaPi** [wekan/wekan#2594]
## Issue

Is there anyway for me to follow wekan release updates through rss?

Github release page does have an atom subscription, but wekan repository doesn't show any changelog in release pages as other projects do. Also wekan blog seems to have no rss subscription options. https://blog.wekan.team/feed/ gives me a strange result.

I think you should provide a convenient way for self-hosted server owners to get latest release updates. So when there's an important feature update or a security patch, we will know and upgrade immediately.

**Comment by road42** [comment]
You can use the existing github feeds.

https://github.com/wekan/wekan/releases.atom

Some more information here: https://developer.github.com/v3/activity/feeds/

**Comment by xet7** [comment]
@GammaPi 

Current Wekan ChangeLog is here:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

I have no idea how to convert it it to feed file. If someone is interested in this and can do the conversion, feed files can be attached to this issue in .zip file. I also don't know any open source Linux based software that can generate from source file the different file target formats, like markdown/rss/atom etc.

**Comment by xet7** [comment]
As for important feature update/bugfix/security patch, really you should be running newest Wekan, if your Wekan server is at public Internet. I do make bugfixes and dependency upgrades very often. Node.js has new versions, etc. When there is some new vulnerability or fix in some dependency, usually some bad guys are watching those fixes and then start scanning for vulnerable servers soon after released fix.

The way to run Wekan at public Internet currently is by using Snap or Sandstorm, that has automatic updates, and also having [automated backups](https://github.com/wekan/wekan/wiki/Backup) to elsewhere at least once a day, preferably more often.

**Comment by GammaPi** [comment]
Okay, thanks.
But github atom feed doesn't have change log informations.
I choose to subscribe your social media account instead.
