### ISSUE TITLE
Activities aren't sorted by date anymore. Newest comments are at bottom, they should be at top.

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2596]
System activities aren't sorted by date anymore. They should be sorted with newest first on top. 

![Bildschirmfoto 2019-08-08 um 10 11 31](https://user-images.githubusercontent.com/1153741/62686492-1f84bf00-b9c5-11e9-8cec-81c12e580122.png)

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: v3.06.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Debian 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx 
* Node Version: v8.16.0
* MongoDB Version: mongo:4.0.11 
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):https://redaktion.bonn.digital

**Comment by superlou** [comment]
Also getting this with Wekan v3.11.0 on Node v8.16.0. It's especially noticeable with new comments showing up at the bottom of a card rather than the top.

**Comment by adelphi-company** [comment]
I'm having this problem with v3.15 (snap) too.

**Comment by hever** [comment]
Same problem. Maybe change of MongoDB from v3.2.x to v4.x?

**Comment by xet7** [comment]
Someone could test. Backup your database:
https://github.com/wekan/wekan/wiki/Backup

And then change MongoDB version to v3.2.22:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L96-L99

And then restore.

**Comment by xet7** [comment]
Snap still uses MongoDB 3.2.22

**Comment by hever** [comment]
I'm running snap, so it's not MongoDB 4.x problem. Problem is elsewhere.

**Comment by DerFireWal** [comment]
Can confirm this issue with
Wekan Version 3.17.0
Meteor version 1.8.1
Node version 8.16.0
MongoDB version 3.2.22

It seems to be more or less random, for example:
14 days, a month, a month, a day
13 days, 21 days, a month, a month, 2 hours, 2 days

It seems to stay in this sort order, regardless of reopening or reloading a card or board.

**Comment by hever** [comment]
There is problem in database, until some update createdAt is not Date() but number. So problem isn't in sorting but in saving.

In my case is last activity with date 2019-08-07.

![obrazek](https://user-images.githubusercontent.com/98204/63165368-80e30880-c02b-11e9-9701-73b23f77977c.png)

Maybe problem is somewhere here c60e80d25baa6a81b28f6090ca848553d20b2bb7?

**Comment by saschafoerster** [comment]
@hever How can I get a view like yours to double check in my database?

**Comment by hever** [comment]
It's a robo3t application. You need run it on machine, where wekan is. Or
do some tunnel on that machine to forward mongodb port (port 27019 i think)

Dne so 17. 8. 2019 21:56 uživatel Sascha Foerster <notifications@github.com>
napsal:

**Comment by derbolle** [comment]
This happened for us after we updated Wekan from 3.06 to 3.15. The sorting seems to be oldest --> Newest with seemingly random bits in between. Boards with big histories don't load the newest entries properly. If you need any information that can help solve this, I would be more than glad to provide

Current Setup: 

Wekan Version  3.15.0
Meteor version 1.8.1
Node-Version 8.16.0
MongoDB version 4.0.11
MongoDB storage engine wiredTiger

4.14.35-linuxkit

running on Docker EE on Windows Server 2019

**Comment by vjrj** [comment]
Some queries to show better the createdAt type issue mentioned above in our wekan (3.21.0):
```js
> db.activities.find( ).count()
8222
> db.activities.find( { createdAt: { $type : 9 } } ).count()
8178
> db.activities.find( { createdAt: { $type : 1 } } ).count()
44
>
> db.activities.find().sort({$natural:1}).limit(1);
{ "_id" : "2k59MPjEk2YQHJ9HF", "userId" : "ff4hoxPWmNfZi9SDY", "activityType" : "createCard", "boardId" : "vMcHR37DpcYiWjS37", "listId" : "hAzARbCX4ZmYF3haM", "cardId" : "WaNi7RhKaEcBXpbSu", "createdAt" : ISODate("2016-08-27T05:57:54.190Z"), "modifiedAt" : ISODate("2019-08-07T00:23:34.233Z") }
> db.activities.find().sort({$natural:-1}).limit(1);
{ "_id" : "Narhoihn5E6ty6p8x", "userId" : "ff4hoxPWmNfZi9SDY", "oldListId" : "LaS53EvbMYJmdnNHr", "activityType" : "moveCard", "listName" : "Completadas-Ago-2019", "listId" : "m8Rq52JZ5bQWr6w4Y", "boardId" : "KKj5Wp7zoHTPymPZF", "cardId" : "YSWGfRZTv9EQNMuxc", "cardTitle" : "Actualizar el IPT", "swimlaneName" : "Mejoras", "swimlaneId" : "vc5sjBxytniTKeb8v", "oldSwimlaneId" : "Cru2RQ9RsJDRwiAXM", "createdAt" : 1566208649295, "updatedAt" : 1566208649295 }
```

**Comment by hever** [comment]
So we need find where problem occurs, and repair - I think story might begin here https://github.com/wekan/wekan/blob/c60e80d25baa6a81b28f6090ca848553d20b2bb7/models/activities.js#L65.

Then run some command to repair history in MongoDB (I speak SQL language and not so good in MeteorDB).

**Comment by vjrj** [comment]
Maybe the bug was introduced here:
https://github.com/wekan/wekan/blame/master/models/activities.js#L233
cc @whowillcare

**Comment by medienverbinder** [comment]
Same issue (snap):

Wekan-Version: 3.25.0
Node-Version: 8.16.0
MongoDB-Version: 3.2.22

**Comment by vjrj** [comment]
More info about this issue that now I suppose is introduced by @justinr1234 in: 
https://github.com/wekan/wekan/commit/c60e80d25baa6a81b28f6090ca848553d20b2bb7

First of all let me show you some old comment with correct dates:
```
> db.card_comments.find().sort({$natural:1}).limit(1);
{ "_id" : "txZE63DzT5CA9RuYi", "text" : "foo", ... "createdAt" : ISODate("2018-09-18T08:42:31.383Z"), ..., "modifiedAt" : ISODate("2019-08-07T00:23:34.233Z") }
``` 
and some new:
```
> db.card_comments.find().sort({$natural:-1}).limit(1);
{ "_id" : "KGmk3YyTovaBCcnFs", "text" : "<p>foo</p>", "createdAt" : 1566902968875, "modifiedAt" : ISODate("2019-08-27T10:49:28.874Z"), "updatedAt" : 1566902968875 }
```
this new comment has `updateAt` and `modifiedAt` (strange) but `modifiedAt` has a `ISODate` and the rest just a Double. 

The same happens with activities, boards, etc

I've just created a sandbox board:
```
> db.boards.find().sort({$natural:-1}).limit(1);
{ "_id" : "3gPkxaq6RgToK9Gpj", "title" : "Sandbox", ... , "createdAt" : 1566975383734, "modifiedAt" : ISODate("2019-08-28T06:56:23.732Z"), ... "updatedAt" : 1566975383734 }
```

So I think this introduced here:
https://github.com/wekan/wekan/blob/master/server/migrations.js#L710
when set `createdAt` and `updateAt` with a `Date.now()` instead of `new Date()`.

More info:
https://stackoverflow.com/a/42915056
https://docs.mongodb.com/manual/reference/method/Date/

**Comment by ohrbeit** [comment]
I got the same problem - is there a fix in the making or a way to restructure the database, so the whole sorting is works again? :)

**Comment by xet7** [comment]
Someone could add pull request to fix this, it would be very welcome.

**Comment by hever** [comment]
This command in MongoDB fixing createAt in activities table (and then history is ok):
```
db.activities.find({ createdAt: { $type : 1 }).forEach(function(obj) { 
obj.createdAt = new Date(obj.createdAt);
db.activities.save(obj); });
```
But there is a question - do we need Date or Integer format? And modifiedAt migth be Date or Integer? And in the other tables?

**Comment by ohrbeit** [comment]
> This command in MongoDB fixing createAt in activities table (and then history is ok):
> 
> ```
> db.activities.find({ createdAt: { $type : 1 }).forEach(function(obj) { 
>   obj.createdAt = new Date(obj.createdAt);
>   db.activities.save(obj);
> });
> ```
> 
> But there is a question - do we need Date or Integer format? And modifiedAt migth be Date or Integer? And in the other tables?

It seems to not change anything - i think i can't paste multiple lines of code into the terminal of the synology docker container terminal

**Comment by xet7** [comment]
Moved to here from #2663 

From @BoxedBrain 

## Show date and time instead of unix-timestamp

## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker


**Problem description**:
If you hover "X minutes/days ago" at the card history, you see a unix-timestamp as tooltip.
It would be nice to show as formatted date respecting the timezone.

![image](https://user-images.githubusercontent.com/7748392/63935740-6747b500-ca5e-11e9-9777-7277917a3e7e.png)

**Comment by hever** [comment]
@xet7 In my opinion this needs your master touch. It seems to me that the location of the problem code in the migrations.js file is bad practice - nobody can expect it here. It's my opinion, maybe wrong. This should by elsewhere, i think.

https://github.com/wekan/wekan/blob/master/server/migrations.js#L687-718

**Comment by xet7** [comment]
@hever 

Master touch :) :) That makes me feel happy. Ok I'll look at this.

**Comment by justinr1234** [comment]
@hever the migration code isn’t the issue, it’s the facts that it’s a time stamp instead of a date. The code added in the migration is a brand new field which isn’t used by Wekan but was meant to standardize having a modified field on every table, where only some tables had it and others did not. The naming was inconsistent across fields.

The bug was that in adding the field like this, I accidentally changed the schema for an existing field to also use a time stamp instead of a date, which was a mistake.

The fix is to revert the original schema fields back to dates and add a migration to fix the dates in the DB. The tables in the existing migration are meant to be there.

**Comment by hever** [comment]
@justinr1234 What about you write is below the code i mention. Migration, in my opinion must be code which runs only one time. But this code...
```
firstBatchOfDbsToAddCreatedAndUpdated.forEach(db => {
  db.before.insert((userId, doc) => {
    doc.createdAt = Date.now();
    doc.updatedAt = doc.createdAt;
  });

db.before.update((userId, doc, fieldNames, modifier) => {
...
```
... is applying everytime and modifies what is inserting or updating - this is not one-time-code, it's every-time-code and it's might not be here, i think.

**Comment by justinr1234** [comment]
@hever this is adding a `before.insert` to those collections. It would probalby be cleaer to move it into the specific folders for those collections. The code is correct, but you're right it should move into the individual files for those collections instead of here.

**Comment by ohrbeit** [comment]
Is there already a fix implemented in the latest docker build? Or is it possible to restructure the MongoDB with a command? Unfortunately I can't get the one from @hever to work

**Comment by hever** [comment]
@ohrbeit You can repair your data with command but you have to run the code in MongoDB. In terminal may work something like this:

`mongo localhost:27019/wekan myfile.js`

On my snap version mongo command is in the path `/snap/wekan/current/bin/mongo`. In the file `myfile.js` will be command mentioned before:

```
db.activities.find({ createdAt: { $type : 1 } }).forEach(function(obj) { 
  obj.createdAt = new Date(obj.createdAt);
  db.activities.save(obj);
});
```

I personally make tunnel to my server with `ssh -L 27019:localhost:27019 root@server-ip` and then run `robo3t` GUI app where can I connect to database and run commands.

**Comment by ohrbeit** [comment]
Awesome! Thank you so much, it worked perfectly & Robo 3t is such a good tip! Now I'm just hoping for a fast fix within the next releases, but until then, your script helped a lot & saved me a lot of trouble!

**Comment by justinr1234** [comment]
One issue with the script is that it is overriding the date. To fix the date, you’ll want to find the dates where they’re integers in the database and then convert those into a date object. The way that code above is made it overrides any date to be created at the time you run the script.

**Comment by hever** [comment]
> One issue with the script is that it is overriding the date. To fix the date, you’ll want to find the dates where they’re integers in the database and then convert those into a date object. The way that code above is made it overrides any date to be created at the time you run the script.

You don't read the script well. Script do what you want.

**Comment by justinr1234** [comment]
@hevee so you’re right, this issue isn’t a good one for me! 🤪

**Comment by saschafoerster** [comment]
Robo3T doesn't work for my in the docker environment behind SSH with a key.
About the script: Could someone please describe to me a little bit, what the script is doing and how a possible fix afterwards will be influenced by this script? I want to know, if I change something, that is irreversible and if It will make a possible automated fix more difficult later? Last question: do I need to repeat the script regurlarly, if I don't change the Wekan-files themselves? Thanks!

**Comment by xet7** [comment]
You can take backup first:
```
ssh user@wekan.example.com
docker exec -it wekan-db bash
cd /data
rm -rf dump
mongodump
exit
docker cp wekan-db:/data/dump .
```

That code finds from database those that are in `unix date` format like and changes them to correct date format.

That incorrect code is in migration that runs only once, so you don't need to do it again.

That fix can be run this way:
```
ssh user@wekan.example.com
docker exec -it wekan-app bash
mongo
```
And then paste those database command to terminal.

Then exit from mongo, docker, ssh:
```
exit
exit
exit
```
Some new Wekan release would just run those same database commands to fix database aitomatically.

Sure that broken migration could be removed.

It does not matter how many times and when you run that fix. If there is no dates in `unix date` format, it does not do anything.

Above is for Docker.

Snap runs on server port 27019, so just:
```
mongo --port 27019
```
And run those database fix commands.

More info at Wekan GitHub wiki Backup page.

**Comment by ohrbeit** [comment]
@xet7 I'm not sure if it's only in migration, in my current docker installation every new comment is wrong again. I have to run the code a few times a day to fix the latest entries.

**Comment by saschafoerster** [comment]
Seems to work. Thanks! :)
