### ISSUE TITLE
can't see the comment when turn off hide system message

### ISSUE THREAD

**Issue by loginKing** [wekan/wekan#2597]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**: 

* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 3.11.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:8.16.0
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*
![image](https://user-images.githubusercontent.com/38350723/62689957-5925ec00-b9fe-11e9-9980-96b237282c41.png)

I can see comments when I turn on the hide system message, but I can't see them when I turn off the hide system message.

**Comment by rjevnikar** [comment]
When system messages are not hidden, do you see the same number of activities as you do comments if they are hidden? For example, with system messages hidden you see 4 comments, with system messages visible, you see 4 activities.

I'm wondering if this is similar to #2377 in any way....

**Comment by xet7** [comment]
This has already been fixed.
