### ISSUE TITLE
eMail setting in Wekan

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2598]
Sorry I checked information here:https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
but it still doesn't work. so I have to put here.

Wekan is runing in Docker on Win10, which in my company network with a http proxy setting.

Settings in wekan as following, it doesn't work.
![image](https://user-images.githubusercontent.com/46272743/62691508-6db7b380-ba01-11e9-94f0-c0f9f67ffa31.png)

**Comment by xet7** [comment]
Currently at my server I use AWS SES, and I have cron job to keep run these commands every morning that keeps settings active.
```
sudo snap set wekan mail-url="smtps://username:password@email-smtp.eu-west-1.amazonaws.com:587"
sudo snap set wekan mail-from="Wekan Team Boards <info@example.com>"
```
I would think that at Admin panel From should be like:
```
Wekan Team Boards <info@example.com>
```
If your company network has Exchange, you could also use DavMail SMTP to Exchange proxy.

You should also test with some other code, like little Javascript or Python code, does sending email work at all, is the error in your email server.

**Comment by javen9881** [comment]
Settings in my docker-compose.yml

```
      - MAIL_URL=smtp://wekaninfo:hereispassword@126.com:587
      - MAIL_FROM=Wekan Notifications
```
and I got result in logs
PS C:\Wekan> docker logs wekan-app
Presence started serverId=toM6yEyDr78WfxD95
Meteor APM: completed instrumenting the app

**Comment by xet7** [comment]
You should have for example single quotes because of space I think:
```
- MAIL_FROM='Wekan Notifications <support@example.com'
```
Also if you have special characters in your password, you should [urlencode those special characters](https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#special-characters).

**Comment by xet7** [comment]
To debug this, also set:
```
- DEBUG=true
```
And see Docker logs:
```
docker logs wekan-app
```

**Comment by lezioul** [comment]
Hi, is this issue solved or maybe the cron workaround is still the way to keep these settings active when using wekan within snap?

**Comment by xet7** [comment]
@lezioul 

I still use cron workaround. I have not made any fixes to this yet.

**Comment by lezioul** [comment]
> @lezioul
> 
> I still use cron workaround. I have not made any fixes to this yet.

thx.

**Comment by Logicbloke** [comment]
I have had my settings reset after my snap installation updated Wekan. I was wondering why it stopped working.

**Comment by maltem-za** [comment]
Sounds like you might have a similar problem to [what I experienced](https://github.com/wekan/wekan/issues/2375#issuecomment-732773295).

**Comment by xet7** [comment]
@javen9881 @lezioul @Logicbloke 

Please test does now `snap set wekan mail...` settings keep working with newest Wekan.

**Comment by Logicbloke** [comment]
I have it on autoupdate and have had the `set wekan mail` commands for quite some time and it's been resetting the mailserver settings every time. So, no worries about that.
