### ISSUE TITLE
Remove Archive and Duplicate Buttons from cards in board view

### ISSUE THREAD

**Issue by derbolle** [wekan/wekan#2599]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 3.06
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker, wekanteam:wekan. Mongo:xenial
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): IIS
* Node Version: 8.16.0
* MongoDB Version: 4.1.0
* ROOT_URL environment variable https://(subdomain).domain.net

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*

How it is now: 
Desktop Browser:
![grafik](https://user-images.githubusercontent.com/53299502/62697914-1d7a2a80-b9dc-11e9-9fb4-c2566e2313b7.png)

Mobile View:
![grafik](https://user-images.githubusercontent.com/53299502/62698201-db051d80-b9dc-11e9-957d-68f28b64009d.png)

How it should work: 

- Archiving and duplicating only from within the cards themselves would be an easy way to mitigate this accident prone design flaw.

- At least there should be a confirmation before anything gets done 

- Only board admins should be able to archive boards.

- *Explain steps how to reproduce*
Desktop
Mouse hover over card --> Click Archive/Duplicate
Mobile: 
Tap into lower third on card
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed 
not relevant
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
not relevant
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
not relevant
- *If logs are very long, attach them in .zip file*
not relevant

**Comment by loucurapt** [comment]
@xet7 Not everything reported in this issue has been fixed, so I don't think it should be closed.

The Archive button still appears in the "My Boards" page in all cards. **even if I'm not the administrator of the board**, and clicking the button displays **no confirmation**.
The Duplicate button also doesn't show confirmation.

**Comment by xet7** [comment]
@loucurapt 

Moved to #2644

**Comment by loucurapt** [comment]
@xet7 Thank you!
Don't forget the permissions check.

**Comment by xet7** [comment]
@loucurapt 

What permission checks? Please add new issue about those, I don't know what is missing.

**Comment by loucurapt** [comment]
@xet7 It's one of the things that @derbolle mentioned and I reiterated.
The Archive button is displayed on all boards in the main page, even if I'm not an admin of the board. 
I'm also an administrator user though (in the admin panel)... could that be it?

I can report a new issue if you like.

**Comment by xet7** [comment]
You are Admin User, so you see those buttons. Those users that are not Admin or BoardAdmin at all, have those hidden. So there is not permission issue at all, this is how it currently works. If you want those hidden, create new user that has only user permissions, not any Admin/BoardAdmin permission. Don't add new issue about this.

**Comment by loucurapt** [comment]
Ok. Thank you for the clarification! It makes sense
