### ISSUE TITLE
Bug: Horizontal scrolling in code snippets impossible

### ISSUE THREAD

**Issue by dialogik** [wekan/wekan#260]
Long lines of sourcecode create a horizontal scrollbar. But you cannot grab the scrollbar with the cursor. Instead, it selects the code.

**Comment by ePirat** [comment]
Should this be scrollable or would it be better to wrap it to newlines?

**Comment by dialogik** [comment]
I'd recommend scrolling, that's (afaik) the setting on trello, on StackOverflow and also here

    1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890

Wrapping should be done manually for posting sourcecode.
