### ISSUE TITLE
RICHER_CARD_COMMENT_EDITOR=false in docker does not turn off the editor

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2604]
When I active the option RICHER_CARD_COMMENT_EDITOR=false in the docker-compose.yml, it doesn't show any changes in Wekan itself. So the editor can't be turned off as expected. 

**Server Setup Information**:
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: v3.13.0
* Operating System: Debian 10 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx 
* Node Version: v8.16.0
* MongoDB Version: mongo:4.0.11
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):https://redaktion.bonn.digital

**Comment by saschafoerster** [comment]
CC @whowillcare https://github.com/wekan/wekan/pull/2560

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/2607
