### ISSUE TITLE
Unable to delete a custom field in a board

### ISSUE THREAD

**Issue by sclerc-chss** [wekan/wekan#2605]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 3.55
* Operating System: Debian 9.9
* Deployment Method : snap
* Node Version: 8.16

**Problem description**:
When I want to delete a custom field in a board, the field isn't deleted.
I've the same message than the #2590 in the console, maybe it's the same problem (update failed : Internal server error)

![image](https://user-images.githubusercontent.com/53857862/62783766-61912c00-babd-11e9-88d7-91a4fdaa077e.png)

- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
sudo snap logs wekan.wekan
2019-08-09T13:42:14Z wekan.wekan[32329]:     at Subscription.subscriptionProto.(anonymous function) [as removed] (packages/mdg_meteor-apm-agent.js:2857:30)
2019-08-09T13:42:14Z wekan.wekan[32329]:     at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
2019-08-09T13:42:14Z wekan.wekan[32329]:     at runWithEnvironment (packages/meteor.js:1188:24)
2019-08-09T13:42:14Z wekan.wekan[32329]:     at packages/meteor.js:1201:14
2019-08-09T13:42:14Z wekan.wekan[32329]:     at packages/mongo/observe_multiplex.js:182:30
2019-08-09T13:42:14Z wekan.wekan[32329]:     at Array.forEach (<anonymous>)
2019-08-09T13:42:14Z wekan.wekan[32329]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-08-09T13:42:14Z wekan.wekan[32329]:     at Object.task (packages/mongo/observe_multiplex.js:176:9)
2019-08-09T13:42:14Z wekan.wekan[32329]:     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:819:16)
2019-08-09T13:42:14Z wekan.wekan[32329]:     at packages/meteor.js:796:12

**Comment by sclerc-chss** [comment]
I've tried in a classic board and I've the same bug than in the board template.

**Comment by xet7** [comment]
Are you BoardAdmin of that board? Or Admin of Wekan, when you try it?

**Comment by sclerc-chss** [comment]
I've tested with and without Wekan admin rights : I've the same problem.

I've tested with an admin of the board and with a simple user of a the board : i've the same problem too.

**Comment by xet7** [comment]
Hmm, from those logs above it seems that mdg_meteor-apm-agent is complaining something. It's kadira debugger. I'll test would removing it help.

**Comment by xet7** [comment]
Hmm, I don't understand why you don't have it working.

I tested Snap:
- added new Custom Field, type text, checked all checkboxes
- on card hamburger menu, clicked custom field name, it appeared to card.
- on card hamburger menu, clicked custom field name, it disappeared from card.
- on Custom Fields, clicked custom field name's edit icon, clicked delete, it deleted custom field.

**Comment by xet7** [comment]
I tested both as admin and normal user.

**Comment by xet7** [comment]
On my laptop, this shows that I'm using Wekan v3.13:
```
$ sudo snap list
Name     Version    Rev   Tracking  Publisher   Notes
core     16-2.39.3  7270  stable    canonical✓  core
wekan    3.13       569   stable    xet7        -
```

**Comment by xet7** [comment]
I did not do any changes and I did not remove kadira etc. This is with newest snap.

**Comment by xet7** [comment]
I'm currently running Debian testing on my laptop. I think there is no difference on what distro Snap is running.

**Comment by xet7** [comment]
What webbrowser are you using?

**Comment by sclerc-chss** [comment]
I've just tested with : Vivaldi 2.6 , Chrome 76, Firefox 60.8 esr

I've always the problem.

This bug can be complex because I think that this field has appeared alone : I have another custom field with the same name and I don't remember that I create another custom field with exactly the same name ("Acteur(s)" ) ...

![image](https://user-images.githubusercontent.com/53857862/62848781-4f8dd400-bcdd-11e9-99ca-302059c4392e.png)

**Comment by sfahrenholz** [comment]
i have testing it with wekan v3.15 and an older board.
Browser is Vivaldi 2.6.1566.49 (Stable channel) (64-Bit)
Ubuntu snap

on my board i can delete the custom field.
Is this a new board? can you test it with an new board?

**Comment by sclerc-chss** [comment]
I think the bug appears when I use my board template : 

my board template has 2 custom fields : 

![image](https://user-images.githubusercontent.com/53857862/62850226-7c90b580-bce2-11e9-825c-8108e89b57ad.png)

When I create a board from my template, I retrieve only one custom field and this is this field that I can't delete : 

![image](https://user-images.githubusercontent.com/53857862/62850305-c24d7e00-bce2-11e9-9b21-dc81dcae219d.png)

The behavior is strange because I get only one custom field from the board template and this custom field isn't deletable.

Thank you for your help.

**Comment by xet7** [comment]
I tried adding Custom Field to board template and it's card, and removing those, and it works for me.

**Comment by sclerc-chss** [comment]
I've identified exactly the actions to reproduced the bug : 

- create a board template 
![image](https://user-images.githubusercontent.com/53857862/62861872-0e111f00-bd05-11e9-9e75-7d8d36cbc796.png)

- create a text custom field and create a card with it
![image](https://user-images.githubusercontent.com/53857862/62861902-2123ef00-bd05-11e9-879f-bf2a2fbee881.png)

- create a board based on template
![image](https://user-images.githubusercontent.com/53857862/62861914-2719d000-bd05-11e9-9cdc-c4d3d50beb46.png)

- delete the custom field
![image](https://user-images.githubusercontent.com/53857862/62861919-2e40de00-bd05-11e9-844c-426aec831d73.png)

- the custom field is deleted on the existing card but still present in "Custom fields" menu, with the message "update failed : Internal server error" in the web console.
![image](https://user-images.githubusercontent.com/53857862/62861948-444e9e80-bd05-11e9-90f6-e12218f5bdc7.png)

I hope it's more understandable for you.

**Comment by sclerc-chss** [comment]
Still present in 3.55.

**Comment by CodeFreezr** [comment]
Sill present in 3.84.0

**Comment by CodeFreezr** [comment]
Here another Set of Steps to Reproduce:

a) Create two Boards 1. Master, 2. Teams
b) Create CustomFields in Master
c) Add a Card in Master-Board with CustomField and add a Value
d) Copy Card from Master to Teams
e) Delete copied Card in Teams
f) You never can't delete the CustomFields in Teams-Board from the Card, even there is no card anymore.
g) CustomFields created directly in Teams-Board are deletable.

**Comment by CodeFreezr** [comment]
We have a setup of ProgramBoard, 8 Team-Boards, BacklogBoard. After creating & copying alot of cards inside a PI-Planning between all Boards, we have a really big bunch of duplicated CustomFields... 

Ok our fail. 

But now we wanna clean up, but we can't. Next PI-Planning is in two days....

**Comment by CodeFreezr** [comment]
Here are more observations: 

- can delete customfields as long I do not a copy a card to another board.
- After copying a card with customfield and value to another board, I can't delete this customfield. Neither on source-Board nor on the target-Board.

**Comment by xet7** [comment]
@CodeFreezr 

> Sill present in 3.84.0

Newest Wekan is v4.13.
