### ISSUE TITLE
Unable to remove old Board, reappears 

### ISSUE THREAD

**Issue by chirrut2** [wekan/wekan#2613]
## Issue

When deleting a specific old Board from archive, it will reappear.

#### Output of the log:

Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]: Exception while invoking method '/boards/remove' TypeError: Cannot read property 'title' of undefined
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.Activities.after.insert (models/activities.js:207:36)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at packages/matb33_collection-hooks.js:382:18
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Array.forEach (<anonymous>)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at after (packages/matb33_collection-hooks.js:381:9)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at ns.Collection.insert (packages/mongo/collection.js:520:39)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.ChecklistItems.before.remove (models/checklistItems.js:236:16)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at packages/matb33_collection-hooks.js:558:28
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Array.forEach (<anonymous>)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at packages/matb33_collection-hooks.js:557:11
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Array.forEach (<anonymous>)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at ns.Collection.remove (packages/mongo/collection.js:620:31)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at cardRemover (models/cards.js:1539:18)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.Cards.before.remove (models/cards.js:1695:5)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at packages/matb33_collection-hooks.js:558:28
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Array.forEach (<anonymous>)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at packages/matb33_collection-hooks.js:557:11
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Array.forEach (<anonymous>)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)

**Server Setup Information**:
OS: Ubuntu Server 18.04
wekan  3.17 via snap

**Comment by xet7** [comment]
If you restore that board, does that board have some linked cards or custom fields that you could remove, and then try archive and delete again?

**Comment by chirrut2** [comment]
As far as i can see, no. Maybe some other person linked it into his board. I cant verify.

**Comment by xet7** [comment]
I'm seeing this draggable error. I'll try does removing recent draggable code change help.
```
Error: cannot call methods on draggable prior to initialization; attempted to call method 'option'
    at Function.error (http://localhost/8621b8e….js?meteor_js_resource=true:19:2107)
    at HTMLAnchorElement.<anonymous> (http://localhost/8621b8e….js?meteor_js_resource=true:221:5706)
    at Function.each (http://localhost/8621b8e….js?meteor_js_resource=true:19:3172)
    at p.fn.init.each (http://localhost/8621b8e….js?meteor_js_resource=true:19:1139)
    at p.fn.init.t.fn.(anonymous function) [as draggable] (http://localhost/8621b8e….js?meteor_js_resource=true:221:5450)
    at f.View.autorun (http://localhost/8621b8e….js?meteor_js_resource=true:339:424996)
    at http://localhost/8621b8e….js?meteor_js_resource=true:63:18999
    at Function.e._withTemplateInstanceFunc (http://localhost/8621b8e….js?meteor_js_resource=true:63:37826)
    at http://localhost/8621b8e….js?meteor_js_resource=true:63:18951
    at Object.f._withCurrentView (http://localhost/8621b8e….js?meteor_js_resource=true:63:23077) undefined
```

**Comment by xet7** [comment]
Actually, here it's just complaining checklist title is missing:
```
Aug 13 13:10:35 vsvwekan01 wekan.wekan[6157]: at Object.Activities.after.insert (models/activities.js:207:36)
```
I can set it as empty string when it's missing.

**Comment by chirrut2** [comment]
Hmm, there is just one checklist in the board and it has a title?

![image](https://user-images.githubusercontent.com/50633042/62941137-9fe85d00-bdd5-11e9-8895-647a6b8bae94.png)

**Comment by xet7** [comment]
If you delete that checklist, can you delete that board?

**Comment by chirrut2** [comment]
Ok. Ivh removed all tasklists, lists and cards except one where the tasklist resides before. Ivh move this specific card to the archive:

Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]: Exception in removed observe/observeChanges callback: Error: Removed nonexistent document r4i85FhyJx2oc7ABd
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Subscription.removed (packages/ddp-server/livedata_server.js:1292:19)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Subscription.subscriptionProto.(anonymous function) [as removed] (packages/mdg_meteor-apm-agent.js:2857:30)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at runWithEnvironment (packages/meteor.js:1188:24)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at packages/meteor.js:1201:14
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at packages/mongo/observe_multiplex.js:182:30
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Array.forEach (<anonymous>)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Object.task (packages/mongo/observe_multiplex.js:176:9)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:819:16)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at packages/meteor.js:796:12
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]: Exception in removed observe/observeChanges callback: Error: Removed nonexistent document r4i85FhyJx2oc7ABd
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Subscription.removed (packages/ddp-server/livedata_server.js:1292:19)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Subscription.subscriptionProto.(anonymous function) [as removed] (packages/mdg_meteor-apm-agent.js:2857:30)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at runWithEnvironment (packages/meteor.js:1188:24)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at packages/meteor.js:1201:14
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at packages/mongo/observe_multiplex.js:182:30
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Array.forEach (<anonymous>)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Object.task (packages/mongo/observe_multiplex.js:176:9)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:819:16)
Aug 13 20:08:08 vsvwekan01 wekan.wekan[17949]:     at packages/meteor.js:796:12


I try to remove it:
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]: Exception while invoking method '/cards/remove' TypeError: Cannot read property 'title' of undefined
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Object.Activities.after.insert (models/activities.js:203:36)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at packages/matb33_collection-hooks.js:382:18
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Array.forEach (<anonymous>)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at after (packages/matb33_collection-hooks.js:381:9)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at ns.Collection.insert (packages/mongo/collection.js:491:37)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Object.ChecklistItems.before.remove (models/checklistItems.js:236:16)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at packages/matb33_collection-hooks.js:558:28
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Array.forEach (<anonymous>)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Function._.each._.forEach (packages/underscore.js:139:11)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at packages/matb33_collection-hooks.js:557:11
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Array.forEach (<anonymous>)
Aug 13 20:09:51 vsvwekan01 wekan.wekan[17949]:     at Function._.each._.forEach (packages/underscore.js:139:11)

**Comment by cimm** [comment]
I have a similar issue when removing certain archived cards. I have a card with a checklist and a card without in the archive. It happens with both.

Deleting the card works at first but the card reappears. The browser console shows `remove failed: Internal server error undefined`.

Using version 3.40.0 via snap on Ubuntu 18.04.3 LTS.

```
Exception while invoking method '/cards/remove' TypeError: Cannot read property 'title' of undefined
  at Object.Activities.after.insert (models/activities.js:214:36)
  at packages/matb33_collection-hooks.js:382:18
  at Array.forEach (<anonymous>)
  at Function._.each._.forEach (packages/underscore.js:139:11)
  at after (packages/matb33_collection-hooks.js:381:9)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:396:12)
  at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
  at ns.Collection.insert (packages/mongo/collection.js:520:39)
  at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
  at Object.ChecklistItems.before.remove (models/checklistItems.js:238:16)
  at packages/matb33_collection-hooks.js:558:28
  at Array.forEach (<anonymous>)
  at Function._.each._.forEach (packages/underscore.js:139:11)
  at packages/matb33_collection-hooks.js:557:11
  at Array.forEach (<anonymous>)
  at Function._.each._.forEach (packages/underscore.js:139:11)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)
  at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)
  at ns.Collection.remove (packages/mongo/collection.js:620:31)
  at cardRemover (models/cards.js:1541:18)
  at Object.Cards.before.remove (models/cards.js:1697:5)
  at packages/matb33_collection-hooks.js:558:28
  at Array.forEach (<anonymous>)
  at Function._.each._.forEach (packages/underscore.js:139:11)
  at packages/matb33_collection-hooks.js:557:11
  at Array.forEach (<anonymous>)
  at Function._.each._.forEach (packages/underscore.js:139:11)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)
```

**Comment by anicolaides** [comment]
Same here, with v3.44 using Docker.

**Comment by Philipoo0** [comment]
Same here some cards (not created by me) are always reappearing. I have removed all information inside (user, label, title, checklists...) but still couldn't delete them. The workaround to move to another board is working great :).

**Comment by chirrut2** [comment]
Issue still in place, v3.49, move card to another board will resolve the problem

**Comment by cimm** [comment]
I am hoping #2756 will fix this issue since it looks like the error message I am seeing. Haven't tested it yet.

**Comment by xet7** [comment]
@cimm 

You don't need to test https://github.com/wekan/wekan/pull/2756 , it is broken and causes board not to load at all. I will test each part of that pull request to see does some of it work.

**Comment by cimm** [comment]
For those with non-removable cards. I managed (with the help of @xet7, thank you) to remove my non-deletable cards via the database:

```js
$ mongo --port 27019
> use wekan
> db.cards.deleteOne({ title: 'Title of you card here' })
```

This removed the un-deletable card which in its turn allowed me to remove the un-removable board. Might not work for everyone but hey, it worked for me!

**Comment by uusijani** [comment]
I think I've (accidentally) found a reliable way to reproduce this:

1. Have a card with a checklist
2. From the card's hamburger menu, select `More` -> `Delete`, but _don't touch the ("Delete card?") confirmation prompt!_
3. With the card deletion confirmation prompt still visible, delete the checklist (choose `Delete` from the checklist title, then confirm the checklist deletion)
4. Now select `Delete` from the (still lingering) card deletion prompt

Boom! The card (and the board) is now undeletable.
