### ISSUE TITLE
Question about emails

### ISSUE THREAD

**Issue by CreedDE** [wekan/wekan#2617]
## Question

I got a question about the emails. We got many emails of cards that got a due Date and if that date comes the end, we got a email. I need only to be member of the Board and have everything on Muted and i get emails of the card that the due ending soon.

It is actually a normal behavior?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L248-L275

Same in Snap:
```
sudo snap set wekan bigevents-pattern='.....'
```
