### ISSUE TITLE
Release v0.9

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#262]
I've released the [first release candidate](https://github.com/wekan/wekan/releases/tag/v0.9.0-rc1) of Wekan v0.9:

* [Release notes](https://github.com/wekan/wekan/blob/master/History.md#next--v09)
* [Official docker image](https://hub.docker.com/r/mquandalle/wekan/)
* [Official sandstorm package](https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h)

Go download and test it! Bugs that I plan to fix before the final v0.9 release are tracked using the corresponding [GitHub milestone](https://github.com/wekan/wekan/milestones/Release%200.9).

As it introduces a new user interface, this release changes quite a bit of displayed text, and thus requires some translation work. If you are interested to contribute to it you can create or join a team on [our Transifex project](https://www.transifex.com/wekan/wekan/).

I'll also set up a discourse forum (or do you prefer something else?) for the final v0.9.

**Comment by iraycd** [comment]
:+1: Congrats. :tada: :birthday:

**Comment by mquandalle** [comment]
The [second release candidate](https://github.com/wekan/wekan/releases/tag/v0.9.0-rc2) is out and it fixes a fair amount of bugs that have been reported. A special thank you note to @nata-g who have been testing the application [quite extensively](https://github.com/wekan/wekan/issues/created_by/nata-g) :-)

I plan to publish Wekan v0.9 final release on Thursday. We are still missing a lot of translations, please join us on Transifex if you would like to help.

**Comment by nata-g** [comment]
Awesome ... :+1:  :+1:

**Comment by mquandalle** [comment]
**Released!**
