### ISSUE TITLE
Boards will not open

### ISSUE THREAD

**Issue by Chris-2019** [wekan/wekan#2623]
Hello professionals

I have been running the WEKAN board for some time for testing purposes.
Everything OK so far but since 3 days the user can still log in but no board opens (hourglass).

I can still connect to the board (the VM is on a different machine). 
It is not possible with the IE but with Firefox I can open the boards.

The SNAP installation is in a VM on Ubuntu Server (no GUI just the command prompt)

Would anyone have an idea how I can tackle the problem?

Enclosed some data of my system:
Server Setup Information:
    Did you test in newest Wekan?: Yes
    For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
    Wekan version: 3.18.0
    If this is about old version of Wekan, what upgrade problem you have?: not about old version
    Operating System: Ubuntu 19.04 Server x64 in a VM under Windows 7 64 bit
    Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
    Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): ???
    Node Version: 8.16.0
    MongoDB Version: 3.2.2 
    ROOT_URL environment variable http://(subdomain).example.com(/suburl): not set but WEKAN access via http://XXX.XXX.17.113:8080 possible
    
wekan@wekanserver:~$ sudo snap list
Name   Version  Rev    Tracking  Publisher   Notes
core   16-2.40  7396   stable    canonical✓  core
lxd    3.16     11633  stable/…  canonical✓  -
wekan  3.18     585    stable    xet7        -
wekan@wekanserver:~$ sudo snap logs wekan.wekan
2019-08-15T09:27:39Z wekan.wekan[2670]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
2019-08-15T09:27:39Z wekan.wekan[2670]: LOGOUT_WITH_TIMER=false (default value)
2019-08-15T09:27:39Z wekan.wekan[2670]: LOGOUT_IN= (default value)
2019-08-15T09:27:39Z wekan.wekan[2670]: LOGOUT_ON_HOURS= (default value)
2019-08-15T09:27:39Z wekan.wekan[2670]: LOGOUT_ON_MINUTES= (default value)
2019-08-15T09:27:39Z wekan.wekan[2670]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-08-15T09:27:39Z wekan.wekan[2670]: ATTACHMENTS_STORE_PATH= (default value)
2019-08-15T09:27:39Z wekan.wekan[2670]: MONGO_URL=mongodb://127.0.0.1:27019/wekan
2019-08-15T09:27:41Z wekan.wekan[2670]: Presence started serverId=RDJMm5F2XXXXxxxxXXXX
2019-08-15T09:27:42Z wekan.wekan[2670]: Meteor APM: completed instrumenting the app

Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco

I would be very grateful if someone could give me a tip or hint.

Chris

**Comment by xet7** [comment]
@Chris-2019 

What version of IE and Windows?

**Comment by xet7** [comment]
For those addresses, settings:
```
sudo snap set wekan root-url='http://XXX.XXX.17.113:8080'
sudo snap set wekan port='8080'
```

**Comment by Chris-2019** [comment]
Wow that is fast - Thank you!

Firefox Quantum 68.0.1 (64-Bit)
Internet Explorer 11

Sorry, but address settings did not change anything.

The crazy thing is that it does not happen to all colleagues.
Even when they use Firefox it is not working.
(I read your hint how to get admin to a board but i did not get it work like you described.)
Chris

**Comment by Chris-2019** [comment]
Microsoft Windows [Version 6.1.7601]

**Comment by xet7** [comment]
It could be that you are not running newest Windows, some updates are missing. For me on Windows 10 Home with latest updatest, browsers work, Firefox / Chrome / Chromium / Edge / Chromium Edge.

**Comment by Chris-2019** [comment]
That's right, we're just upgrading to Windows 10.
Due to some guidelines we can not update our clients ourselves.
This is distributed centrally via WSUS.

But you gave me an idea, an update of the Firefox version is a good idea.
Maybee we get new policies from the admins.
I will test that.

**Comment by Chris-2019** [comment]
Dear xet7,

problem solved. Due an security update something changed so on IE 11 and Firefox / Firefox Portable WEKAN was not running correctly.
Newest Version (68) solved that. 

Thanks for your help. 
Chris
