### ISSUE TITLE
REST API deletes too many cards

### ISSUE THREAD

**Issue by 0xC4N1** [wekan/wekan#2624]
## Issue

**Server Setup Information**:
* Did you test in newest Wekan?: Tested with docker image wekanteam/wekan:latest from 2019-08-15T05:36:01.614774048Z with a new database.
`sha256:19eb9cb63583aa4de16be65a601a789c5baa0ed9b4f17e81079cf0c7f04a2cd9`
* MongoDB Version: 4.2.0

**Problem description**:
Deleting a single card with the [delete_board_list_card](https://wekan.github.io/api/v3.00/#delete_board_list_card) API endpoint causes Wekan to delete the desired card and all remaining cards in the list. Cards in other lists are not affected. The issue persists after reloading the page.
![wekan-api-card-delete-issue](https://user-images.githubusercontent.com/7902457/63094654-49138c80-bf69-11e9-9157-e7d8232cea0a.gif)
- *Explain steps how to reproduce*
1. create cards
````bash
CARD_TITLE=woof
CARD_ID=$(curl -s --request POST $WEKAN_API/boards/$BOARD_ID/lists/$LIST_ID/cards -d "title=$CARD_TITLE&description=lipsum&authorId=$AUTHOR_ID&swimlaneId=$SWIMLANE_ID" --header "$AUTH_HDR" | jq -r '._id') && echo $CARD_ID
CARD_TITLE=mew
CARD_ID=$(curl -s --request POST $WEKAN_API/boards/$BOARD_ID/lists/$LIST_ID/cards -d "title=$CARD_TITLE&description=lipsum&authorId=$AUTHOR_ID&swimlaneId=$SWIMLANE_ID" --header "$AUTH_HDR" | jq -r '._id') && echo $CARD_ID
````
2. delete last card. Wekan deletes the desired card and shortly afterwards all remaining cards are deleted as well.
````bash
curl -s --request DELETE $WEKAN_API/boards/$BOARD_ID/lists/$LIST_ID/cards/$CARD_ID --header "$AUTH_HDR"
````
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
````
Presence started serverId=ZvrQSuBq5rzffE6nn
Meteor APM: completed instrumenting the app
````

**Comment by xet7** [comment]
Someone could look what is wrong at API code and send pull request please:
https://github.com/wekan/wekan/blob/master/models/cards.js#L2177

**Comment by 0xC4N1** [comment]
I'm not a Meteor developer and I didn't verify this guess but does it try to remove the same card twice? It calls [Cards.direct.remove](https://github.com/wekan/wekan/blob/c882ebe030ebc747a00a1b43768daf13c1645407/models/cards.js#L2197) and afterwards [Cards.remove](https://github.com/wekan/wekan/blob/c882ebe030ebc747a00a1b43768daf13c1645407/models/cards.js#L1545l) at [cardRemover](https://github.com/wekan/wekan/blob/c882ebe030ebc747a00a1b43768daf13c1645407/models/cards.js#L2205).

**Comment by 0xC4N1** [comment]
wekanteam/wekan:v2.97 is the last known working version. wekanteam/wekan:v3.00 and up is misbehaving.

**Comment by KiPiCoOl** [comment]
Hi

Same problem here.
No solution at his time in 3.x ?

Thx

**Comment by xet7** [comment]
@KiPiCoOl 

AFAIK no, nobody has helped to fix this with pull request.

**Comment by Tigralt** [comment]
Still the same problem on **wekan 3.49-1-g13a2bd6** (installed with snap).

**Comment by liske** [comment]
A had a look at it and it was triggered due a wrong remove order (Mongo DB vs. Meteor instance).
