### ISSUE TITLE
Feature Request: Text Labeling configurable for showing

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2629]
In one version the text of the labels are show on board. This has the "problem", when the labels has text, the columns get very big. The board is in this case confusing

![image](https://user-images.githubusercontent.com/6977657/63146124-28474780-bffa-11e9-9f57-4cbdf36871ca.png)

If would be good, that the Board Admin or every user self can configured, to see the texts on the label

**Comment by xet7** [comment]
Feature already exists.

https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v309-2019-08-07-wekan-release
