### ISSUE TITLE
Use username in OAuth to login

### ISSUE THREAD

**Issue by juliensl** [wekan/wekan#2631]
Hi !! It's me again 😄 

## Issue

Wekan uses username to log someone in with OAuth.

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 3.20.0
* Operating System: Ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node Version: 8.16.0
* MongoDB Version: 3.2.22
* Meteor Version : 1.8.1:

**Problem description**:
Finally, I found the reason for my 2 last login bugs.

> With password login, Wekan uses username to login.
> With OIDC or LDAP, Wekan uses email address to login.

_Originally posted by @xet7 in https://github.com/wekan/wekan/issues/2534#issuecomment-509563677_ 

In theory, maybe, but in reality, wekan uses username to login with OIDC or LDAP too.

Do this test : 

- Connect youself in kanban with OAuth
- Create some boards
- Check you username
- Log you out in wekan and in your website
- Create a new account in your website which will have the same username in wekan (for exemple, I create the wekan username using the first name and last name of the user), so, let's say that my first user was called Stephen Hawking, I'll create a new user called Stephen Hawking too.
- Connect yourself on wekan with OAuth, boom ! You're in the first account
- Check the people admin pannel, the email of the account for Stephen Hawking is replaced by the new one.

We should use only email to the login, it is unique, no mix possible ;)

**Comment by lamoquette** [comment]
You need to put OAUTH2_ID_MAP="email" in the environnement deployment and not OAUTH2_ID_MAP="sub" to synchronise correctly the classic users and the new ones created with the SSO/LDAP button
