### ISSUE TITLE
Missing button to close a card in mobile view

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2637]
When in mobile view and I try to close a card or to go back to the list, where I opened the card, I don't find an easy way to accomplish this. I would expect a close button in one of the red areas I guess, like in desktop view. 

<img width="516" alt="Bildschirmfoto 2019-08-17 um 22 02 00" src="https://user-images.githubusercontent.com/1153741/63216754-bd515a00-c13a-11e9-8825-30acc440ed5a.png">
<img width="377" alt="Bildschirmfoto 2019-08-17 um 22 02 18" src="https://user-images.githubusercontent.com/1153741/63216755-bd515a00-c13a-11e9-850b-62a66a119f6f.png">

**Server Setup Information**:
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 3.21.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Synology
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 8.16.0
* MongoDB Version: 4.0.11

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/commit/36b5965dd07e3f0fd90069353310739c394c220f
