### ISSUE TITLE
Importing from Trello: selecting user accounts seems broken

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2638]
## Issue

I go to https://[wekanurl]/import/trello and try to import JSON-exports from Trello. It works, until I should select some users. 
<img width="973" alt="Bildschirmfoto 2019-08-17 um 22 20 39" src="https://user-images.githubusercontent.com/1153741/63216959-2090bb80-c13e-11e9-95c6-917a06243b29.png">

Instead of options, which users a want to match, I get some errors in the console. 

The line: 

`  dataContext: this.currentData && this.currentData() || this`
in this seems to get an error. 
<img width="799" alt="Bildschirmfoto 2019-08-17 um 22 22 07" src="https://user-images.githubusercontent.com/1153741/63216933-be37bb00-c13d-11e9-884f-c9c27b51ef92.png">

```
      window.Popup = new class {
                    constructor()
                    {
                        this.template = Template.popup, this.current = null, this._stack = [], this._dep = new Tracker.Dependency
                    }
                    open(e)
                    {
                        const t = this,
                            r = "".concat(e, "Popup");
                        function s(e) {
                            return 0 !== $(e.target).closest(".js-pop-over").length
                        }
                        return function(e) {
                            if (t.isOpen()) {
                                const a = t._getTopStack().openerElement;
                                if (a === e.currentTarget)
                                    return void t.close();
                                $(a).removeClass("is-active")
                            }
                            let n;
                            s(e) ? n = t._getTopStack().openerElement : (t._stack = [], n = e.currentTarget), $(n).addClass("is-active"), e.preventDefault(), t._stack.push({
                                popupName: r,
                                openerElement: n,
                                hasPopupParent: s(e),
                                title: t._getTitle(r),
                                depth: t._stack.length,
                                offset: t._getOffset(n),
                                dataContext: this.currentData && this.currentData() || this
                            }), t.isOpen() ? t._dep.changed() : t.current = Blaze.renderWithData(t.template, () => (t._dep.depend(), (0, a.default)({}, t._getTopStack(), {
                                stack: t._stack
                            })), document.body)
                        }
                    }
```
<img width="831" alt="Bildschirmfoto 2019-08-17 um 22 22 25" src="https://user-images.githubusercontent.com/1153741/63216934-c4c63280-c13d-11e9-9831-c79bb5cc0375.png">

I tried with two different import-JSONs. 

** Server Setup Information: ** 

Did you test in newest Wekan?: yes
For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
Wekan version: 3.21.0
If this is about old version of Wekan, what upgrade problem you have?:
Operating System: Synology
Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
Node Version: 8.16.0
MongoDB Version: 4.0.11

**Comment by GuidoDr** [comment]
I had the same problem with a Wekan board from boards.wekan.team into our own hosted Wekan (latest version).
I was not able to select any user. Only my own user matched automatically, but I could not finish the import. No errors visible in the UI, only in the console. (but I have not saved the errors).
Only solution in my case was to remove all user information from the json (besides my own user). Then I could successfully import the board. And to later on add the users again to the imported boards. The good thing had been in my case, that the cards were not dedicated to any user yet. So removing the user information was not a problem for me but of course will not work for other boards.
So it seems not to be related to Trello only but to all board imports from Trello or Wekan boards.

**Comment by xet7** [comment]
@saschafoerster

Did you create same users to your Wekan before importing from Trello?

**Comment by saschafoerster** [comment]
I imported many boards before without creating exactly the same users. I could choose which user from Wekan should be matched with which other user from Trello. Now, no user from Wekan is shown at all, when I click on the +-sign.

**Comment by saschafoerster** [comment]
Thanks @xet7: in the newest version 3.25 I can import, but the cards have no members, or at least the matching doesn't take place: 
Before:
<img width="215" alt="Bildschirmfoto 2019-08-24 um 22 09 54" src="https://user-images.githubusercontent.com/1153741/63642187-06198d80-c6bc-11e9-9eeb-ded2bf847e91.png">
After: 
<img width="171" alt="Bildschirmfoto 2019-08-24 um 22 09 42" src="https://user-images.githubusercontent.com/1153741/63642186-06198d80-c6bc-11e9-845b-6e8aea99bf69.png">

**Comment by justinr1234** [comment]
@saschafoerster I am seeing members match correctly. Is there any issue with unicode characters in the usernames of the people who aren't matching?

**Comment by saschafoerster** [comment]
Did you execute the import? I see users, when I choose them, but after the import in the board, no users where added. I might test it another time!

**Comment by justinr1234** [comment]
@saschafoerster ya I did, and it worked

**Comment by saschafoerster** [comment]
I tried today again with the freshest version and it works. Thank you all!
