### ISSUE TITLE
MongoParseError in all Versions after 3.15

### ISSUE THREAD

**Issue by Bro3x** [wekan/wekan#2639]
3.15 ist working fine. All versions after I get a "MongoParseError: No hostname or hostnames provided in connection string"

Trace:

wekan.wekan[22156]: MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan                     wekan.wekan[22156]: /snap/wekan/587/programs/server/node_modules/fibers/future.js:280
wekan.wekan[22156]: throw(ex);
wekan.wekan[22156]: ^
wekan.wekan[22156]: MongoParseError: No hostname or hostnames provided in connection string                        
wekan.wekan[22156]: 	at parseConnectionString (/snap/wekan/587/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:514:21)
wekan.wekan[22156]:     at connect (/snap/wekan/587/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:188:3)
wekan.wekan[22156]:     at connectOp (/snap/wekan/587/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:292:3)
wekan.wekan[22156]:     at executeOperation (/snap/wekan/587/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:420:24)
wekan.wekan[22156]:     at MongoClient.connect (/snap/wekan/587/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:168:10)
wekan.wekan[22156]:     at Function.MongoClient.connect (/snap/wekan/587/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:372:22)
wekan.wekan[22156]:     at new MongoConnection (packages/mongo/mongo_driver.js:177:11)
wekan.wekan[22156]:     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
wekan.wekan[22156]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
wekan.wekan[22156]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
wekan.wekan[22156]:     at new Collection (packages/mongo/collection.js:97:40)
wekan.wekan[22156]:     at packages/idmontie_migrations.js:38:15
wekan.wekan[22156]:     at packages/idmontie_migrations.js:255:4
wekan.wekan[22156]:     at packages/idmontie_migrations.js:263:3
wekan.wekan[22156]:     at /snap/wekan/587/programs/server/boot.js:419:36
wekan.wekan[22156]:     at Array.forEach (<anonymous>)

All Version past v3.15.0
Installed via snap
Node-Version v8.16.0
Linux 4.4.0-157-generic

**Comment by xet7** [comment]
- Backup your database and snap settings `sudo snap get wekan > snap-settings.txt`
- remove and add wekan snap again
- restore with `--noIndexRestore` additional option as described at https://github.com/wekan/wekan/wiki/Backup

**Comment by Bro3x** [comment]
All done - same error.

**Comment by Bro3x** [comment]
Ok, found ist.

snap get wekan gave me a wired
mongodb-bind-unix-socket  /var/snap/wekan/current/share
I reinstalled it again and that param was deleted - all fine now.
