### ISSUE TITLE
node main.js never completes

### ISSUE THREAD

**Issue by michaelwemoto** [wekan/wekan#264]
I'm struggling to get wekan running on my centos7 minimal installation. I've followed three guides and run into different errors with each. here are the steps I'm taking.

#Fresh CentOS Linux release 7.0.1406 (Core) installation.
setenforce 0 (just for good measure)
wget http://nodejs.org/dist/v0.10.40/node-v0.10.40-linux-x64.tar.gz
tar --strip-components 1 -xzvf node-v* -C /usr/local
node --version
v0.10.40

git clone https://github.com/wekan/wekan.git
cd wekan

vi /etc/yum.repos.d/mongodb.repo
[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1

yum install mongodb-org -y
systemctl start mongod

curl https://install.meteor.com/ | sh
meteor build ../wekan-build --directory # the output from this command is
toEnd: wrong arguments-i18n-compiler` fr...  /                                     
to: wrong arguments

cd ../wekan-build/bundle/programs/server/
npm install  #output below
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
> fibers@1.0.5 install /root/wekan-build/bundle/programs/server/node_modules/fibers
> node ./build.js
`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
ansi-regex@0.2.1 node_modules/ansi-regex
ansi-styles@1.1.0 node_modules/ansi-styles
escape-string-regexp@1.0.3 node_modules/escape-string-regexp
chalk@0.5.1 node_modules/chalk
has-ansi@0.1.0 node_modules/has-ansi
strip-ansi@0.3.0 node_modules/strip-ansi
supports-color@0.2.0 node_modules/supports-color
eachline@2.3.3 node_modules/eachline
type-of@2.0.1 node_modules/type-of
amdefine@1.0.0 node_modules/amdefine
asap@2.0.3 node_modules/asap
meteor-promise@0.4.6 node_modules/meteor-promise
underscore@1.5.2 node_modules/underscore
promise@7.0.4 node_modules/promise
source-map-support@0.3.2 node_modules/source-map-support
semver@4.1.0 node_modules/semver
source-map@0.1.32 node_modules/source-map
fibers@1.0.5 node_modules/fibers

export MONGO_URL='mongodb://127.0.0.1:27017/libreboard'
export ROOT_URL='https://example.com'
export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
export PORT=8080

cd ../../

node main.js #output below
[root@libreboard bundle]# node main.js 
Meteor._wrapAsync has been renamed to Meteor.wrapAsync
> Starting board-background-color migration.
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
> Starting use-css-class-for-boards-colors migration.
> Finishing use-css-class-for-boards-colors migration.
> Starting denormalize-star-number-per-board migration.
> Finishing denormalize-star-number-per-board migration.
> Starting add-member-isactive-field migration.
> Finishing add-member-isactive-field migration.

and my server never passes this point?? any suggestions?

Thanks

Michael

**Comment by michaelwemoto** [comment]
I'm not making any progress here!

Could somebody take a look at my outputs? I'm probably missing something really obvious!

Here are all of my commands - 
http://pastebin.com/x4Savh6M

here are all out the outputs -
http://pastebin.com/HvjYM0fN

node.js is new territory for me... please help!

**Comment by ePirat** [comment]
So what exactly is the issue you are experiencing? Does it just do nothing after `Finishing add-member-isactive-field migration.`?

**Comment by michaelwemoto** [comment]
Hi ePirat, 
It sits at "Finishing add-member-isactive-field migration." on screen and never continues. I left it for over an hour yesterday and nothing progressed.

Have you seen anything in my outputs above that sets off alarms? there are a couple of things I am unsure about;

[root@centos7-virtual wekan]# meteor build ../.wekan-build --directory
toEnd: wrong arguments-i18n-compiler` fr...  -                                    
to: wrong arguments

and also

[root@centos7-virtual server]# npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

are these normal outputs?

**Comment by ePirat** [comment]
Indeed the 

```
toEnd: wrong arguments-i18n-compiler` fr... -

to: wrong arguments
```

is really weird output and looks somewhat broken. It doesn't even make any sense for me and I have no idea what it causes…

**Comment by michaelwemoto** [comment]
I'm running that command again on a fresh VM,  this time with --verbose, I'll pastebin the results shortly.

thanks

**Comment by michaelwemoto** [comment]
unfortunately --verbose and --debug only provide me with information about packaged being downloaded and no further information on the error. I'm still stuck with 

toEnd: wrong arguments-i18n-compiler` fr...  
to: wrong arguments

and a broken application...

**Comment by ePirat** [comment]
I've just checked, it seems on latest meteor version, the weird

```
toEnd: wrong arguments-i18n-compiler` fr...

to: wrong arguments
```

is normal, it happens for me as well but still the final build works fine.
Note that it is expected that output stops and the app will not exit, as it's supposed to be run by a watchdog/service like systemd. So just try to connect, if it works you just have to use your prefered service manager to run it in the background or use the simple 

```sh
node main.js &
echo $! > ./pid.txt
```

approach.

**Comment by michaelwemoto** [comment]
ePirat, you are a legend! I assumed that stopping there without any kind of confirmation was an issue, really should have nmap'd to confirm...
I've setup systemd unit files, it's surviving reboots :)

thanks for your help

Michael

**Comment by mquandalle** [comment]
I also have the following weird log

```
toEnd: wrong arguments-i18n-compiler` fr...  \

to: wrong arguments
```

since I upgraded meteor to `v1.2-rc.*`. I imagine this is due to the changes in the meteor plugin API, but I didn't found the exact issue.

Anyway, @michaelwemoto feel free to improve the install guide if some of things have confused you.

**Comment by michaelwemoto** [comment]
Hi mquandalle, firstly thank you for Wekan! I'll write a comprehensive guide for centos7 including systemd unit files, firewall configuration etc. Give me a week or so and I'll put it together at home one evening.

**Comment by ffvpor** [comment]
Hi michaelwemoto
At the first launch of Wekan (fresh install or new database for test), I think that all of this messages are "normal" because I got the same behavior but don't worry, Wekan is perfectly functioning :)
Try this :
- change export ROOT_URL='https://example.com' to export ROOT_URL='http://localhost'
- start Wekan with **node main.js**
- go to http://localhost:3000 on your favorite browser.

Note : localhost can be replace by your URL server

If you see the login page, that's means it's ok !

**Comment by ePirat** [comment]
@ffvpor The issue is already resolved :)

**Comment by michaelwemoto** [comment]
sure can! thanks all
