### ISSUE TITLE
Wekan Meteor bundle 3.20 > private boards are...not private!

### ISSUE THREAD

**Issue by HLFH** [wekan/wekan#2640]
## Issue

I was using Wekan meteor bundle 3.20 and I realized that private boards were not private!!
So I updated to 3.21 and 3.22 which were both fixing the issue.

On the 3.20 version of the Meteor bundle, non-authorized people who have the link of the private board were able to access it. So it was kind of public.

**Server Setup Information**:

* Did you test in newest Wekan?: I've tested on 3.20, 3.21, 3.22 wekan meteor bundles.

* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 3.20 not working, 3.21 & 3.22 working
* If this is about old version of Wekan, what upgrade problem you have?: no upgrade issue
* Operating System: ArchLinux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): meteor bundle
* Http frontend: Nginx
* Node Version: v8.15.1
* MongoDB Version: mongodb 4.0.12

Did you observe also that issue?

I would advise to remove release 3.20.

**Comment by xet7** [comment]
Done.
