### ISSUE TITLE
Cannot open Board by IE(Internet Explorer)

### ISSUE THREAD

**Issue by mingtao13595** [wekan/wekan#2641]
**Server Setup Information**:

* Did you test in newest Wekan?: Yes, Wekan 3.23.0
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 3.23.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:8.16.0
* MongoDB Version:3.2.22

**Problem description**:
- Chrome/FireFox/Edge work well, but IE not.
- *Explain steps how to reproduce*
- Since 3.2.20
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
2019-08-21T00:37:28Z wekan.wekan[24213]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
2019-08-21T00:37:28Z wekan.wekan[24213]: LOGOUT_WITH_TIMER=false (default value)
2019-08-21T00:37:28Z wekan.wekan[24213]: LOGOUT_IN= (default value)
2019-08-21T00:37:28Z wekan.wekan[24213]: LOGOUT_ON_HOURS= (default value)
2019-08-21T00:37:28Z wekan.wekan[24213]: LOGOUT_ON_MINUTES= (default value)
2019-08-21T00:37:28Z wekan.wekan[24213]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-08-21T00:37:28Z wekan.wekan[24213]: ATTACHMENTS_STORE_PATH= (default value)
2019-08-21T00:37:28Z wekan.wekan[24213]: MONGO_URL=mongodb://127.0.0.1:27019/wekan
2019-08-21T00:37:32Z wekan.wekan[24213]: Presence started serverId=ER2ie8Jjzx8cRpnCX
2019-08-21T00:37:34Z wekan.wekan[24213]: Meteor APM: completed instrumenting the app

**Comment by xet7** [comment]
What does not work? Screenshots, errors etc?

**Comment by xet7** [comment]
What version of Internet Explorer?

**Comment by mingtao13595** [comment]
> What version of Internet Explorer?

Thanks a lot for the reply.
It's IE 11.
Part of the bords can be opened now, 
however, it takes a long time to open a board.
![2019_08_21_13_23_48_出図管理_Grp_CMC_Kanban_Internet_Explorer](https://user-images.githubusercontent.com/9034078/63402644-14934b00-c417-11e9-909f-424de9b5e2f5.png)

**Comment by xet7** [comment]
@mingtao13595 

Does server have enough free RAM ? Check is it swapping:
```
free -m
```
If server is swapping, it gets really slow. Then you should change to server that has more RAM.

**Comment by xet7** [comment]
Also, Wekan works faster on Linux server. Windows filesystem is slow.

**Comment by xet7** [comment]
On server I usually use SSD or NVME disk, that is faster than normal spinning harddisk.

**Comment by xet7** [comment]
@whowillcare 

Your Summernote CSS fixes like showing all text at language menu etc do not seem to work on Internet Explorer 11, can you try to get them working?

**Comment by mingtao13595** [comment]
> Also, Wekan works faster on Linux server. Windows filesystem is slow.

Thank you so much for your advice for RAM management and disk.
I used Linux (CentOS7) server and install Wekan by snap.
The memory info is as follow, could you please tell me is something wrong with my server?
Some boards still can not open even waiting for a long time.
Thank you in advance.
[mingtao@iot-01 ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3789         685        1411           8        1691        2779
Swap:          1023           0        1023

**Comment by xet7** [comment]
Ok it seems server is not swapping.

Is the problem only with IE ?

Does other webbrowsers open boards correctly ?

**Comment by xet7** [comment]
I don't know can IE bugs be fixed at all, because according to Wikipedia IE webbrowser is discontinued, it only receives security fixes. IE also does not have all the CSS features, speed optimizations etc that newer webbrowsers have.

**Comment by xet7** [comment]
There is no problem on your server.

I would think only problem is that IE webbrowser does not have all new features and speed required.

**Comment by mingtao13595** [comment]
> Ok it seems server is not swapping.
> 
> Is the problem only with IE ?
> 
> Does other webbrowsers open boards correctly ?

Thanks for your reply.
Yes, except IE11, the others, like Chrome, Firefox, Edge works well.

**Comment by xet7** [comment]
I think it's not possible to fix IE11.

**Comment by mingtao13595** [comment]
> I think it's not possible to fix IE11.

Thank you so much for your prompt reply.

**Comment by xet7** [comment]
@whowillcare 

Don't add any CSS UI fixes for IE11 to Wekan, it is not useful, because IE11 is missing some features that it does not load some Wekan boards at all, when newer browsers loads those just fine. Most likely Wekan uses many so many new browser features that those do not exist at all at IE11.

**Comment by xet7** [comment]
Related #2643 , could be same bug.

**Comment by xet7** [comment]
Moved to #2643
