### ISSUE TITLE
 Is it possible to import from wekan to planner? & From Microsoft Planner to Wekan? Please!

### ISSUE THREAD

**Issue by cmesia1** [wekan/wekan#2642]
Es posible importar de Wekan hacia Microsoft Planner y viceversa? Por favor

**Comment by xet7** [comment]
I don't have Microsoft Planner.

Does Planner have some export to file (JSON, CSV, Excel etc) in some menu? Can you add that file in .zip archive to comment to this issue?

What kind of file can Planner import?

Is there API  for import/export? Link to documentation?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
