### ISSUE TITLE
Due notifications are sent to all board members instead of card members

### ISSUE THREAD

**Issue by rinnaz** [wekan/wekan#2646]
## Issue

**Server Setup Information**:

* Wekan version: **3.25**
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **snap**

**Problem description**:
How to reproduce: 
- set card due date
- check board members inbox

**Comment by xet7** [comment]
See #2617 for info.

I will keep this issue open, it seems I need to disable those by default.
