### ISSUE TITLE
Problem with new users with Wekan 3.21

### ISSUE THREAD

**Issue by hmeunier95** [wekan/wekan#2647]
Since i upgraded my Wekan to 3.21 release, when i create a new user and add him into a board, this user cannot change his profile properties or change view (swimlane, list or calendar).

User test on Windows 10 with Chrome 76.0.3809.100 (Build officiel) (32 bits).

It's a very strange behaviour. I have nothing in docker logs.

Wekan Version	3.21.0
Version de Meteor	1.8.1
Version de Node	8.16.0
Version de MongoDB	3.2.21
Moteur de stockage MongoDB	wiredTiger
MongoDB Oplog activé	
Type d'OS	Linux
OS Plate-forme	linux
OS Architecture	x64
OS Version	4.8.0-22-generic

**Comment by xet7** [comment]
Please try newest Wekan,

**Comment by hmeunier95** [comment]
Thank you! 3.25 release solved this issue.
