### ISSUE TITLE
"Custom HML before/after <body>" doesn't appear to do anything

### ISSUE THREAD

**Issue by loucurapt** [wekan/wekan#2649]
I'm using the latest snap version.

In the Admin Panel, changing the settings "Add Custom HTML after \<body\> start" and "Add Custom HTML before \</body\> end" appears to have no effect.

For example, if I put something like this:
```
<script>
console.log("TEST");
alert("TEST");
</script>
```
I would expect an alert to show and "TEST" logged to the console when refreshing the page (Ctrl+F5).
But that doesn't happen.

**Comment by xet7** [comment]
Yes, it does not work yet.

Moved to #2218
