### ISSUE TITLE
Feature Request: Notifications area

### ISSUE THREAD

**Issue by loucurapt** [wekan/wekan#2650]
This is something that Trello has.

Wekan currently sends notifications by e-mail.

I suggest that a "notifications area" be implemented.
All notifications would be delivered to this notifications area, and the user could choose if he wanted to also receive the notifications by e-mail.

The notifications area would be an overlay panel opened when the user clicked a "bell" icon on the top bar (left of the user menu), that shows all recent notifications.

That want, notifications would work even without configuring an e-mail server.

**Comment by xet7** [comment]
Moved to #2026
