### ISSUE TITLE
Feature Request: Calendar Entries should be the same color as the card (if set)

### ISSUE THREAD

**Issue by grmpfhmbl** [wekan/wekan#2651]
A card that has a color set should have the this color in the calendar view. Example: If I have the following cards

![ColoredCards](https://user-images.githubusercontent.com/5475895/63596649-fa46a200-c5bb-11e9-87e4-d732abfd9222.png)

Currently the calendar looks like this

![CurrentCalendar](https://user-images.githubusercontent.com/5475895/63596698-1b0ef780-c5bc-11e9-9189-c86f0a0d4b5d.png)

I'd like to have it look like this

![ColoredCalendar](https://user-images.githubusercontent.com/5475895/63596721-2530f600-c5bc-11e9-8606-0622235315d8.png)

I already test-implemented this locally and could provide a PR over the weekend (will sign CLA before :-) ).

**Comment by xet7** [comment]
Please add PR. Thanks a lot !

**Comment by grmpfhmbl** [comment]
This can be closed I guess.
