### ISSUE TITLE
Unclean HTML makes board inaccessible

### ISSUE THREAD

**Issue by MassiveStorage** [wekan/wekan#2655]
# Wekan Version: 3.25.0
Board is inaccessible after adding unclean html-code to the card title.

Steps to reproduce:

1. Create a empty board
2. Create a list
3. Create a card
4. Write the following thing in the card-title: `<a href="test.local.de">Test<a>`
5. Click Add

Now you should see that the card you tried to create stays empty.
If you now reload the board, it is loading infinitely.

It only appears if you add the `<a>` at the end of the link forgetting the / . If you write correct html like: `<a href="test.local.de">Test</a>` or just don't close the tag at all, everything works normal.

**Comment by xet7** [comment]
Huh? Don't add HTML to card title. Instead, add markdown:
```
[Test](http://test.local.de)
```
Most of GitHub markdown syntax works:
https://guides.github.com/features/mastering-markdown/

HTML can only be possibly used in comment wysiwyg editor.

**Comment by BoxedBrain** [comment]
@xet7 , we have the same problem here. Would it be possible to use something like strip_tags?

**Comment by xet7** [comment]
@BoxedBrain 

Yes, you can add pull request, or use my Commercial Support https://wekan.team

**Comment by Akuket** [comment]
Hello,
We also have this bug. And more generally, all unformatted content (pasted from Word for example)

**Comment by xet7** [comment]
This is already fixed.
