### ISSUE TITLE
Infinite loading on IE11

### ISSUE THREAD

**Issue by lampi87** [wekan/wekan#2656]
Hi guys,

on IE11 opening a board leads to infinite loading. Opening Dev-Tools shows the following error message:
Exception from Tracker recompute function: undefined
Error: No such template: minicardDueDate
at Anonymous function (http://url:3001/wekan/68ad622d5840c0345bb18fa03590ef9fa1228a6b.js?meteor_js_resource=true:63:32978)

Currently installed version of wekan is 3.25

On Firefox and Chrome it works fine but unfortunately we have to use IE11.

Thx in advance!

**Comment by xet7** [comment]
Hmm, actually, I don't know would this fix IE:
https://github.com/wekan/wekan/pull/2654

I will test it.

**Comment by xet7** [comment]
Related #2643 , could be same bug.

**Comment by xet7** [comment]
Moved to #2656
