### ISSUE TITLE
Wekan performances

### ISSUE THREAD

**Issue by Akuket** [wekan/wekan#2658]
**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 3.25
* If this is about an old version of Wekan, what upgrade problem you have?: From 2.60 to 3.25, performances issue
* Operating System: Ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker **with swarm** to set 4 replicas of the application (not the db).
* Node Version: 8.16.0
* MongoDB Version: 4.0.11
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?  Firefox/Chrome

**Problem description**:
- *Steps*: We updated your wekan version from 2.60 to 3.25. For the database, we used the option --noIndexRestore. 
- *Consequence*: Now we have long load times for all pages.
- *In webbrowser, what does show Right Click / Inspect /Console? Chrome shows more detailed info than Firefox.*: Sometimes there are some errors, but no more than before, and the slowness is here with or not them.
- *If using Docker, what does show command `sudo docker logs wekan-app` ?* Nothing abnormal
- When we make a docker stats, we can see some containers that exceed 100% but the most significant thing is with only one user connected to the app who tried to load his bord, the db send more than 6Go of data in her network interface and app containers received them but the sum of what they send to the client is less than 100Mo. After seeing that, I set the db profiler to see what queries performed. All data relating to the board (cards, comments,...) have been loaded 4 times. So it might be the use of the "_pull and diff_ " from Meteor instead of Oplog ? My MONGO_OPLOG_URL is not set.
- I tried to set MONGO_OPLOG_URL: create the user (in admin db with permissions to read the local db) then create the rs `rs.initiate({_id: ‘rsWekan’, members: [{_id: 0, host: ‘localhost:27017’}]});`
finally use it like this `MONGO_OPLOG_URL='mongodb://USER:PASSWORD@localhost:27017/local?authSource=admin'`. But it failed. I also tried to pass `--replSet rsWekan` to the mongod command, it failed.

If someone has an idea of what causes this issue or if I missed something when I tried to set the MONGO_OPLOG_URL ?

Regards.

**Comment by Akuket** [comment]
Yes, but @xet7 tells me that Wekan always creates missing indexes so I don't know.
Indexes can explain some of the slowness, but there is also this large amount of data.

**Comment by xet7** [comment]
I'm not sure does Wekan create missing indexes. You should check what indexes database has on new Wekan install with empty database, vs your current database.

**Comment by Akuket** [comment]
So, indexes are created and used.
```
db.boards.aggregate( [ { $indexStats: { } } ] )
{ "name" : "_id_", "key" : { "_id" : 1 }, "host" : "10717f497af6:27017", "accesses" : { "ops" : NumberLong(1609980), "since" : ISODate("2019-08-27T22:05:07.730Z") } }
{ "name" : "members.userId_1", "key" : { "members.userId" : 1 }, "host" : "10717f497af6:27017", "accesses" : { "ops" : NumberLong(259110), "since" : ISODate("2019-08-27T22:05:07.730Z") } }
{ "name" : "modifiedAt_-1", "key" : { "modifiedAt" : -1 }, "host" : "10717f497af6:27017", "accesses" : { "ops" : NumberLong(0), "since" : ISODate("2019-08-27T22:05:07.730Z") } }
{ "name" : "_id_1_members.userId_1", "key" : { "_id" : 1, "members.userId" : 1 }, "host" : "10717f497af6:27017", "accesses" : { "ops" : NumberLong(53735), "since" : ISODate("2019-08-27T22:05:07.730Z") } }
```
And there is the detail for each collection
[indexReport.txt](https://github.com/wekan/wekan/files/3551740/indexReport.txt)
If you see something weird?

**Comment by xet7** [comment]
@Akuket 

You have indexes missing.
```
wekan $ ./find.sh ensureIndex
./models/checklistItems.js:    ChecklistItems._collection._ensureIndex({ modifiedAt: -1 });
./models/checklistItems.js:    ChecklistItems._collection._ensureIndex({ checklistId: 1 });
./models/checklistItems.js:    ChecklistItems._collection._ensureIndex({ cardId: 1 });
./models/accountSettings.js:    AccountSettings._collection._ensureIndex({ modifiedAt: -1 });
./models/orgUser.js:    OrgUser._collection._ensureIndex({ orgId: -1 });
./models/orgUser.js:    OrgUser._collection._ensureIndex({ orgId: -1, userId: -1 });
./models/checklists.js:    Checklists._collection._ensureIndex({ modifiedAt: -1 });
./models/checklists.js:    Checklists._collection._ensureIndex({ cardId: 1, createdAt: 1 });
./models/rules.js:    Rules._collection._ensureIndex({ modifiedAt: -1 });
./models/triggers.js:    Triggers._collection._ensureIndex({ modifiedAt: -1 });
./models/cards.js:    Cards._collection._ensureIndex({ modifiedAt: -1 });
./models/cards.js:    Cards._collection._ensureIndex({ boardId: 1, createdAt: -1 });
./models/cards.js:    Cards._collection._ensureIndex({ parentId: 1 });
./models/unsavedEdits.js:    UnsavedEditCollection._collection._ensureIndex({ modifiedAt: -1 });
./models/unsavedEdits.js:    UnsavedEditCollection._collection._ensureIndex({ userId: 1 });
./models/org.js:    Org._collection._ensureIndex({ name: -1 });
./models/boards.js:    Boards._collection._ensureIndex({ modifiedAt: -1 });
./models/boards.js:    Boards._collection._ensureIndex(
./models/boards.js:    Boards._collection._ensureIndex({ 'members.userId': 1 });
./models/customFields.js:    CustomFields._collection._ensureIndex({ modifiedAt: -1 });
./models/customFields.js:    CustomFields._collection._ensureIndex({ boardIds: 1 });
./models/cardComments.js:    CardComments._collection._ensureIndex({ modifiedAt: -1 });
./models/cardComments.js:    CardComments._collection._ensureIndex({ cardId: 1, createdAt: -1 });
./models/users.js:    Users._collection._ensureIndex({ modifiedAt: -1 });
./models/users.js:    Users._collection._ensureIndex(
./models/lists.js:    Lists._collection._ensureIndex({ modifiedAt: -1 });
./models/lists.js:    Lists._collection._ensureIndex({ boardId: 1 });
./models/settings.js:    Settings._collection._ensureIndex({ modifiedAt: -1 });
./models/actions.js:    Actions._collection._ensureIndex({ modifiedAt: -1 });
./models/invitationCodes.js:    InvitationCodes._collection._ensureIndex({ modifiedAt: -1 });
./models/attachments.js:    Attachments.files._ensureIndex({ cardId: 1 });
./models/announcements.js:    Announcements._collection._ensureIndex({ modifiedAt: -1 });
./models/swimlanes.js:    Swimlanes._collection._ensureIndex({ modifiedAt: -1 });
./models/swimlanes.js:    Swimlanes._collection._ensureIndex({ boardId: 1 });
./models/activities.js:    Activities._collection._ensureIndex({ createdAt: -1 });
./models/activities.js:    Activities._collection._ensureIndex({ modifiedAt: -1 });
./models/activities.js:    Activities._collection._ensureIndex({ cardId: 1, createdAt: -1 });
./models/activities.js:    Activities._collection._ensureIndex({ boardId: 1, createdAt: -1 });
./models/activities.js:    Activities._collection._ensureIndex(
./models/activities.js:    Activities._collection._ensureIndex(
./models/activities.js:    Activities._collection._ensureIndex(
./models/integrations.js:    Integrations._collection._ensureIndex({ modifiedAt: -1 });
./models/integrations.js:    Integrations._collection._ensureIndex({ boardId: 1 });
```

**Comment by Akuket** [comment]
I rechecked all line by line, and except the attachment collection, we have the same indexes and more.
- There are collections where we have indexes that aren't in your report above (all cfs, cronHistory, esCounts, jobs_data, jobs_dominator_3, all meteor, presences, and unsaved-edits). 
- There also two collections with more indexes (users and invitationCodes).
- For the attachments, we haven't any indexes but there are cfs collections (cfs.attachments.filerecord by example) and I don't know if it's an equivalent.

**Comment by Akuket** [comment]
I successfully set the oplog, it's not that yet but it's really better

**Comment by xet7** [comment]
Moved to #2711
