### ISSUE TITLE
Add, delete users manually in users admin interface 

### ISSUE THREAD

**Issue by webafrancois** [wekan/wekan#2661]
## Issue
**Server Setup Information**:

* Wekan version: 3.23.0
* Operating System: Debian
* Deployment Method : docker
* Node Version:8.16.0
* MongoDB Version:3.2.21
* ROOT_URL environment variable http(s)://local_ip:
*  webbrowser version : Firefox 68.0.2 (64 bits) GNU/Linux

**Feature description**:
In the admin interface, we only can list and modify users.
It would be great to add users manually or to delete others counts.

PS : Thanks for dev wekan, it's very usefull !

**Comment by Tampa** [comment]
I was about to make the same request. Currently the only way to get new users into the system is either through external hook or invite, but the latter method requires mail to work. Ideally creating a user via the admin menu, pre-setting a password and boards to be part of should be in the People tab.

**Comment by Tampa** [comment]
I figured using Navicat I can actually connect to the mongodb and create the document needed to add a user, but that's a bit complex just to add a user.

@xet7 How much would this be to add?

**Comment by xet7** [comment]
@Tampa 

Newest Wekan already has Create new user in Admin Panel:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v380-2020-02-22-wekan-release

Sorry I forgot to update this issue.

Moved to #802

**Comment by Tampa** [comment]
Hm, I see, took me a while to find that "New" button, it being part of a table header is causing it to be hard to see, maybe add it to the left sidebar menu as well, that's where I would expect it to be.
