### ISSUE TITLE
Show date and time instead of unix-timestamp

### ISSUE THREAD

**Issue by BoxedBrain** [wekan/wekan#2663]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker

**Problem description**:
If you hover "X minutes/days ago" at the card history, you see a unix-timestamp as tooltip.
It would be nice to show as formatted date respecting the timezone.

![image](https://user-images.githubusercontent.com/7748392/63935740-6747b500-ca5e-11e9-9777-7277917a3e7e.png)

**Comment by xet7** [comment]
Moved to #2596
