### ISSUE TITLE
Oauth2 with Keycloak Broken (returns "Login forbidden")

### ISSUE THREAD

**Issue by Ryonez** [wekan/wekan#2668]
## Issue
**Server Setup Information**:

* Did you test in newest Wekan?: Running latest docker image.
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 3.34.0
* If this is about old version of Wekan, what upgrade problem you have?: NA
* Operating System: 4.19.56-Unraid
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): wekanteam/wekan + mongo dockers
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): linuxserver/letsencrypt (Nginx)
* Node Version: 8.16.1
* MongoDB Version: 4.2.0
* ROOT_URL environment variable: https://(subdomain).example.com
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*

![oauth2](https://user-images.githubusercontent.com/15545/134771374-70e49c7f-c093-40e8-9247-c47ffbeb142f.gif)

- *Explain steps how to reproduce*

1. Setup Oauth
2. Open the page
3. ???
4. Profit

- *In webbrowser, what does show Right Click / Inspect / Console ? *

There seems to be an issue with the websocket (Error during WebSocket handshake: Unexpected response code: 400) I assume it's simply because I'm not logged in. Error during WebSocket handshake: Unexpected response code: 400

- *If using Docker, what does show command `sudo docker logs wekan-app` ?*

My logs for the container aren't showing any errors at all.
The only thing in there after the app starts is an email that wasn't set. And that's because I'm not setting up an email account for it until I can login properly.

**Comment by Ryonez** [comment]
Oh, has this been fixed?

**Comment by xet7** [comment]
@Ryonez 

No. There are changes in how issues are managed:

https://github.com/wekan/wekan/blob/main/FUTURE.md

I have no idea does something reported at 2019 being still problem at 2023. Keyclock support depends on those contributors that use Keycloak and send PRs to fix it.

**Comment by xet7** [comment]
@Ryonez

I'll reopen this, because you confirmed this still is broken.

**Comment by Ryonez** [comment]
Sorry, I gave the wrong impression here.

When I made the issue was the first time I was trying Wekan out, and was unable to use my oauth system for it. Due to that, I haven't used it since.

When this closed I thought it might have been looked at and fixed, and that I could try again.

I haven't tried it recently however, and am unable to confirm the issue is still present.

**Comment by xet7** [comment]
@Ryonez 

Oh, OK.
