### ISSUE TITLE
Feature Request: Overshoot the bottom of the page

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2669]
Hi

At the moment  the pages are always tightly aligned to the bottom of the lanes which is fine but this makes it very hard to drop things at the bottoms of lanes. So I am wondering would it be a good idea to pass the last card when scrolling the page? This way one can have a decent visual area at the bottom when using scrolling. I say something like %5 of the visual area.

At the moment, when dragging enabled one can kind of pass the bottom line of the longest lane but it is very hard to control and it is really hard to target the dragged card to be the last one in the target lane. i personally seem to put the card one above always.

just an idea.

**Comment by xet7** [comment]
Click card to to open it, click card hamburger menu, click `Move to bottom`.

Is this what you mean?

**Comment by gerroon** [comment]
Well the issue is move from lane to lanes more than moving to the bottom or top inside the same lane.

**Comment by xet7** [comment]
Please provide animgif about the issue.

**Comment by xet7** [comment]
Use peek to record animgif in Linux https://github.com/phw/peek
