### ISSUE TITLE
Wekan is not running anymore

### ISSUE THREAD

**Issue by paoloprandini** [wekan/wekan#2670]
I used the snap install for more than a year, always updating 
Now it seems mongodb is unable to start, it wants to open a socket but nope:

Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten] MongoDB starting : pid=5652 port=27019 dbpath=/var/snap/wekan/common 64-bit host=www2.in.at.spe.net
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten] db version v3.2.22
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten] git version: 105acca0d443f9a47c1a5bd608fd7133840a58dd
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten] allocator: tcmalloc
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten] modules: none
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten] build environment:
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten]     distmod: ubuntu1604
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten]     distarch: x86_64
Sep  2 15:21:04 www2 mongod.27019[5652]: [initandlisten]     target_arch: x86_64
Sep  2 15:21:05 www2 mongod.27019[5652]: [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27019 }, storage: { dbPath: "/var/snap/wekan/common", journal: { enabled: true }, mmapv1: { smallFiles: true } }, systemLog: { destination: "syslog" } }
Sep  2 15:21:05 www2 mongod.27019[5652]: [initandlisten] listen(): bind() failed errno:2 No such file or directory for socket: /tmp/mongodb-27019.sock
Sep  2 15:21:05 www2 mongod.27019[5652]: [initandlisten] Failed to set up sockets during startup.
Sep  2 15:21:05 www2 mongod.27019[5652]: [initandlisten] dbexit:  rc: 48

**Comment by chotaire** [comment]
```
# pwd ; ls -al mongodb-27019.sock
/tmp/snap.wekan/tmp
srwx------. 1 root root 0 Sep  2 15:24 mongodb-27019.sock

```

**Comment by xet7** [comment]
Try this:
```
sudo snap set wekan mongodb-bind-unix-socket=''
```

**Comment by paoloprandini** [comment]
I had already tried it, but of course I tried it again just in case...
Same error...

**Comment by paoloprandini** [comment]
I would like to understand why someone else has /tmp/snap.wekan and I don't
When is it created and by whom?
Thanks

**Comment by paoloprandini** [comment]
I solved the problem with
snap set wekan mongodb-bind-ip=127.0.0.10
