### ISSUE TITLE
Feature Request: Measure Lead Time

### ISSUE THREAD

**Issue by phamorais** [wekan/wekan#2671]
How to measure Lead Teme at Wekan?

is there any plugin?

**Comment by xet7** [comment]
I did web search, it seems that some lead time spreadsheet is here:
https://www.lean.org/FuseTalk/Forum/Attachments/Lead%20Times%20Chart.xls

Can someone explain more clearly how it is calculated? Wekan has WIP limit etc, but I don't know yet how to do the calculation.

**Comment by phamorais** [comment]
@xet7 

https://en.wikipedia.org/wiki/Lead_time


It is the most used time calculation for those who use agile methodologies. It works to calculate how much time I spend on average delivering Cards, projects or activities. This can guarantee you predictability of deliveries, increasing your control and cost of activities.

**Comment by xet7** [comment]
@phamorais 

Is that related to Start and Due dates on cards? How calculation would go with some cards as an example?

**Comment by phamorais** [comment]
exactly.
Lead Time is the calculation used to measure the delivery time of a card.

However, it should not be manually dated as there may be incorrect data manipulation.

The right thing is when creating a card, the system already records the day and time. And when the card is dragged to the last column, the time taken from the day the card was started until its completion is counted.

**Comment by xet7** [comment]
@phamorais 

Would this work for one card, at hamburger menu?

Each time card changes: move/board/swimlane/list/member/assignee, then it
saves data or each board/swimlane/list.

Lead time is time between first and last time in list.

```
Lead time

Board     | Swimlane | List    | Start time       | Lead time   | Card mover | Members              | Assignee
-----------------------------------------------------------------------------|----------------------|-----------
Project 1 | Design   | Backlog | 2019-09-18 02:18 |             | Username1  |                      | 
Project 1 | Design   | Doing   | 2019-09-19 02:18 | 1d 0h 0m 0s | Username2  | Username1, Username2 | Username3
Project 1 | Design   | Done    | 2019-09-20 02:18 | 2d 0h 0m 0s | Username1  | Username1            | Username3
```

But what is the lead time of each Username in this case?

**Comment by xet7** [comment]
Is there some example how some kanban software has implemented this?

**Comment by xet7** [comment]
I'm just thinking, can this all be calculated from card history? Or is there some need to save new data?

Also, if someone moves cards to Arhive, I think after that lead time is not calculated for those cards.

**Comment by phamorais** [comment]
@xet7 

The example you applied for the burger is correct.

In the “Kanban” methodology the focus is to measure the delivery (card) and not people. The methodology states that more important than measuring the member is the customer having their product delivered. Therefore, when a customer orders a product, they are not interested in the delivery time of member 1 or member 2, but rather of card delivery. In my projects, it is more important to measure the card than to measure people.

But for some companies, it may also be important to measure each member's lead time, and that's not wrong. But it is more focused on the internal process of each company.

Perhaps one way to measure member lead time could be in this example:

- When a card is created and soon after wekan can be counted exactly the way you presented;
- Each board could have a new button called “lead time” that would have a simple table stating the name of each member.
- To measure the lead time of each user, simply add the lead time of each card in which a member participated, and divide by the amount of cards he participates. This way you will have an “average lead time” for each technician;

[This article deals well with the concept of the Kanban methodology](https://www.agilealliance.org/glossary/kanban/#q=~(infinite~false~filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'kanban))~searchTerm~'~sort~false~sortDirection~'asc~page~1))

[This article with measuring lead time on Trello](https://screenful.com/blog/tracking-lead-and-cycle-times-of-your-trello-board)


[Example of a plugin for measuring lead time in trello](https://trello.com/power-ups/5c4af277c0430d10357c87dc/kanban-analytics-by-nave)
