### ISSUE TITLE
Bug - wekan snap is stuck at 2.29

### ISSUE THREAD

**Issue by sh2515** [wekan/wekan#2676]
## Issue
Snap refresh says wekan is up to date, but in the admin panel it says it is 3.29 but the changelog says 3.34

Ubuntu 18.04 using lxc. Wekan is the only software installed on the container.

**Comment by Montiemedia** [comment]
Same Problem on RHEL 7 installation.

Only application on the Server

**Comment by xet7** [comment]
Well, that's because in commit log you see texts like "try to fix snap".
https://github.com/wekan/wekan/commits/master

Whan snap build service accepts Wekan build, then it's fixed and released.
