### ISSUE TITLE
v3.25 make multi label cut title

### ISSUE THREAD

**Issue by BobCashStory** [wekan/wekan#2677]
old behavior:
<img width="266" alt="Screenshot 2019-09-05 at 15 30 08" src="https://user-images.githubusercontent.com/47117399/64346581-aa6fce00-cff2-11e9-9539-30ca13966533.png">

new one :
![image](https://user-images.githubusercontent.com/47117399/64347279-ed7e7100-cff3-11e9-8bfc-0500cc48d76c.png)

title should not been cut like this

**Comment by xet7** [comment]
This has been fixed since [Wekan v3.88](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v388-2020-04-02-wekan-release).
