### ISSUE TITLE
Can't duplicate board

### ISSUE THREAD

**Issue by BobCashStory** [wekan/wekan#2678]
on any board on chrome on version 3.25

![dup](https://user-images.githubusercontent.com/47117399/64361764-81106b80-d00d-11e9-8ade-c42e7eec0f66.png)

**Comment by fr33kvanderwand** [comment]
same problem here

Wekan: 3.36.0
Meteor: 1.8.1
Node: 8.16.1
MongoDB: 3.2.21

tested with firefox and chorme

**Comment by xet7** [comment]
Works for me on Wekan v3.45 Snap.
