### ISSUE TITLE
Wekan doesn't start anymore after trying to upgrade

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2682]
Wekan doesn't start anymore after trying to upgrade:

```
/build/programs/server/node_modules/fibers/fibers.js:90
					return fn.apply(this, arguments);
					          ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1378:11)
    at runWebAppServer (packages/webapp/webapp_server.js:771:18)
    at webapp_server.js (packages/webapp/webapp_server.js:1175:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /build/programs/server/packages/webapp.js:1588:15
    at /build/programs/server/packages/webapp.js:1597:3
    at /build/programs/server/boot.js:419:36
    at Array.forEach (<anonymous>)
    at /build/programs/server/boot.js:228:19
    at /build/programs/server/boot.js:479:5
    at Function.run (/build/programs/server/profile.js:510:12)
    at /build/programs/server/boot.js:478:11

```

**Server Setup Information**:

* Did you test in newest Wekan?: yes, and in older Wekans as well, it stays the same error in the logs
* For new Wekan install, did you configure root-url correctly: https://github.com/wekan/wekan/wiki/Settings ? yes, it worked till today
* Wekan version: now 
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: 3.36
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: ?
* MongoDB Version: 4.0.11
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://redaktion.bonn.digital
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? ...

**Comment by xet7** [comment]
Hmm? I don't know, Snap did upgrade for me just fine.

Did you set your ROOT_URL ?
https://github.com/wekan/wekan/wiki/Settings

Are you using newest docker-compose.yml from https://github.com/wekan/wekan ?

**Comment by xet7** [comment]
With unmodified docker-compose.yml for me `docker-compose up -d` did work just fine, to run at localhost.

**Comment by saschafoerster** [comment]
I tested the unmodified docker-compose.yml and it was the same. I removed all containers, I removed all images, I tried different versions from wekan-app on quay.io and docker-hub. I am lost. :D

**Comment by saschafoerster** [comment]
Root URL was set, I didn't touch the docker-compose.yml before upgrading.

**Comment by saschafoerster** [comment]
Holy moly: I got it back up, but this is not the way it should be. 

In the docker-compose.yml I added:

```
 wekan:
...
    entrypoint: ["sh", "-c", "sleep 2073600"]
```
so I could log in to the container and start the commands manually and see what is wrong. 
Then I had some time to login into the container: 
`docker exec -i -t wekan-app bash`
I entered the command to start Wekan: 
`wekan@36e234f411e4:/$ node /build/main.js`

I got the same error message: 

```/build/programs/server/node_modules/fibers/fibers.js:90
					return fn.apply(this, arguments);
					          ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1378:11)
    at runWebAppServer (packages/webapp/webapp_server.js:771:18)
    at webapp_server.js (packages/webapp/webapp_server.js:1175:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /build/programs/server/packages/webapp.js:1588:15
    at /build/programs/server/packages/webapp.js:1597:3
    at /build/programs/server/boot.js:419:36
    at Array.forEach (<anonymous>)
    at /build/programs/server/boot.js:228:19
    at /build/programs/server/boot.js:479:5
    at Function.run (/build/programs/server/profile.js:510:12)
    at /build/programs/server/boot.js:478:11
```

So I tried to help to define this variable with this command: 

`wekan@36e234f411e4:/$ export ROOT_URL=https://redaktion.bonn.digital`

Result: now it was asking for the MONGO-URL:

```
/build/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at packages/idmontie_migrations.js:38:15
    at packages/idmontie_migrations.js:255:4
    at packages/idmontie_migrations.js:263:3
    at /build/programs/server/boot.js:419:36
    at Array.forEach (<anonymous>)
    at /build/programs/server/boot.js:228:19
    at /build/programs/server/boot.js:479:5
    at Function.run (/build/programs/server/profile.js:510:12)
    at /build/programs/server/boot.js:478:11
```
No problem, here is the MONGO-URL: 
`wekan@36e234f411e4:/$ export MONGO_URL=mongodb://wekandb:27017/wekan`

And then: it started up. 

```
wekan@36e234f411e4:/$ node /build/main.js
Presence started serverId=ajEsMi7LPr499xSJZ
> Starting fix-incorrect-dates migration.
> Finishing fix-incorrect-dates migration.
Meteor APM: completed instrumenting the app
```
So for today I keep people working, until I have some time for debugging on the desktop. If you have guesses or some hints, what I could try, I will gladly test it out!

**Comment by xet7** [comment]
Hmm, I don't usually use Docker, it's so complex.
I would recommend just installing Snap and letting it automatically upgrade:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
Or, if Docker now works you now, as you seem to have run latest Wekan version with that migration fix, you could keep it that way.

**Comment by derbolle** [comment]
The latest (docker) version (pulled yesterday) crashed repeatedly without an error message for us. 
Docker logs unfortunately didn't show any errors. The container just goes down and up again for a few seconds. The workaround was pulling v3.37 from wekanteam/wekan and not "latest"
I think that must be actually version 3.36 because there is a gap between 3.35 and 3.37. "latest" seems to be different from 3.37 on Dockerhub. Mayhaps something with the latest build on Dockerhub went wrong

![grafik](https://user-images.githubusercontent.com/53299502/64600723-ecff2500-d3bb-11e9-9f08-757adbaafe34.png)

**Comment by saschafoerster** [comment]
For me, I had the same problem with RocketChat. The solution: Synology has a bug in their docker-compose implementation. So for me the bug is closed, but I would like to let @xet7 decide, if the other bug from @derbolle should be followed here or in a new issue. 
https://community.synology.com/enu/forum/15/post/128146

**Comment by derbolle** [comment]
@saschafoerster  We are running wekan on windows server 2019 with docker LCOW. I will try using another docker version but I don't think this will solve the issue. I hope I will be able to provide further information shortly

**Comment by derbolle** [comment]
it seems to be that wekan for docker doesn't reserve enough memory for itself. It runs on a docker host with >10 GB of ram and doesnt take more than 1 GB. Is there a way to allocate more ram to the machine? Docker should normally manage this automatically but it seems that the wekanteam/wekan docker image doesn't do that. Any ideas @saschafoerster @xet7 ? This also could be responsible for many performance issues. 

![grafik](https://user-images.githubusercontent.com/53299502/64612094-43c42900-d3d3-11e9-9315-93d52b08b3aa.png)

**Comment by xet7** [comment]
@derbolle 

<img src="https://wekan.github.io/docker-ram-usage.png" width="100%" alt="Docker RAM usage" />

For better performance, you can also install without Docker:
https://github.com/wekan/wekan/wiki/Windows

@saschafoerster 

If you have problems with docker-compose on Synology, you can start Wekan without it with only Docker commands:
https://github.com/wekan/wekan/wiki/Docker

**Comment by xet7** [comment]
If Wekan inside Docker does not have enough RAM, then Wekan and MongoDB will crash and keep restarting.

**Comment by derbolle** [comment]
Hello @xet7 
we were using docker for windows server 2019 with LCOW containers. This screenshot is from Docker desktop, which we do not use. The memory limit should get set automatically by docker. The Server in question had 8 cores assigned and 12gb or Ram. Wekan only ever used 1 gb of that. In an emergency we switched to a linux server to host our docker containers. The problem is, that wekan doesn't seem to function properly since our update from 3.25 to version 3.37

![grafik](https://user-images.githubusercontent.com/53299502/64707193-f4edc080-d4b2-11e9-8eea-a0618b3dcb73.png)
 
loading boards seems longer than it should be. I don't think this is somehow related to the hardware or OS we use but I am all out of ideas. Wekan on docker (ubuntu host, 4 vcpus, 8 GB of ram, gigabit network)

![grafik](https://user-images.githubusercontent.com/53299502/64707510-6594dd00-d4b3-11e9-9835-f769b4e82744.png)

**Comment by xet7** [comment]
I'm currently building Wekan v3.38, you can try it when you see it available.

**Comment by xet7** [comment]
Please try newest Wekan.

**Comment by grop4all** [comment]
Check env wekan-app ROOT_URl

**Comment by xet7** [comment]
Docker/Source environment variable is ROOT_URL

snap is root-url='http....'
