### ISSUE TITLE
WeKan changes numbers in Card titles

### ISSUE THREAD

**Issue by ADDAH-temp** [wekan/wekan#2685]
Hello there! 

Maybe this is less an issue and more a design decision, but when giving a card the title "4. October" i.e. WeKan shows the the card title "1. October"...

I suppose WeKan handles single numbers as lists....
![October issue](https://user-images.githubusercontent.com/54981317/64419933-47d40c00-d09e-11e9-96e8-e59d82127661.PNG)

**Comment by rjevnikar** [comment]
This is a result of Wekan markdown #2334

**Comment by xet7** [comment]
Yes, you need to use formatting like Inline backtics, mentioned at:
https://guides.github.com/features/mastering-markdown/

Because formatting with markdown is so useful, like adding links, images, etc formatting, there is no plans to make any changes to this.

**Comment by xet7** [comment]
Yes, your title does show correctly when you add backticks around it:
```
`4. October`
```
