### ISSUE TITLE
Add feature: Possibility to open card in separate view

### ISSUE THREAD

**Issue by JSSSSJ** [wekan/wekan#2686]
It would be fine, if there would be an option to show a card in separate view.

For example: There is a card with traces (simply lot of text) etc. but the current view is too narrow to show it comfortably. In this case, it would be good, if there was a possibility of the separate view for single card, especially, when somebody is working only with one card for amount of time and the reading needs lot of scrolling.

I couldn't find similar issue so I made new one. If this is a duplicate then sorry for that.

**Comment by xet7** [comment]
@JSSSSJ 

Please provide screenshot about how it is too narrow.

If something is not visible in Wekan, it's a bug.

**Comment by xet7** [comment]
Hmm, actually I think I understand what you mean.

When card is open, it has limited width.

There could be maximize button at left side of card hamburger menu to maximize card width to full screen width, similarly like there is at Gmail new email compose box, where alternative are small box or full screen.

**Comment by xet7** [comment]
I think that at mobile view that button needs to be hidden.

**Comment by xet7** [comment]
I do not yet have time for this, but it is a good idea.

Pull requests welcome, if someone has time for this.

**Comment by xet7** [comment]
Well, some tips for someone trying to implement this.

At `wekan/components/cards/cardDetails.*` to `.jade` file add that button, that triggers in `.js` file Javascript code that changes CSS code at `.styl` file that has limits for width.

**Comment by JSSSSJ** [comment]
Yeah, that's exactly what I ment. Wekan has a feature, that you can have comment editing in fullscreen provided by Summernote, but there is no way to show card in fullscreen or some kind of maximized/larger view.

**Comment by xet7** [comment]
Moved to #1574
