### ISSUE TITLE
Feature Request - Creating cards through calendar view

### ISSUE THREAD

**Issue by savoiebz** [wekan/wekan#2687]
Hey!

It would be great if we could add cards from the calendar view. 

I've searched in the issues if to make sure if the feature hasn't been requested yet but can't seem to find it. Sorry if it was already asked!

Very nice project by the way. I quite enjoy it for business and personal life!

-Thank you

**Comment by airdogvan** [comment]
second that!

**Comment by xet7** [comment]
@savoiebz @airdogvan 

Please explain with more details and screenshot mockups about how this should work.

**Comment by savoiebz** [comment]
@xet7 

Sorry, it's been a while. A year, in fact. All our business migrated to Microsoft 365 and we now use MS Project.

Have a good one.

**Comment by xet7** [comment]
@savoiebz 

Hi ! Thanks for replying :smile:

About MS Project: Currently Wekan does not yet have Import/Export to MS Project, I did previously apply for grant for getting funding for that, but my application did not get accepted yet.

Businesses are different, some prefer to use Open Source software for everything and support their development, and some like to pay for high license costs of propietary software.

@airdogvan

Because you replied `second that`, do you have more details about how this should work?

**Comment by savoiebz** [comment]
Yeah in our programming department we're more into OSS. But the the rest of the business trying to adapt to the new market by selling and understanding MS365. 

Thank you for your time and nice project. Used it a lot in 2019.

Wish you the best

**Comment by xet7** [comment]
@savoiebz 

Thanks! Wish you the best too! :smile:

**Comment by sirup** [comment]
Hi!
Wanted to comment on this too. Right now I can see all the cards on the calendar, but cannot simply add one there. Let's say I want to schedule a card at a specific start+end date, I just want to click there and add the card. Start+End should be filed automatically. 
 Could look like this:
![image](https://user-images.githubusercontent.com/5006637/117636931-998d3d80-b181-11eb-80b6-85177ec8f64f.png)

Thanks!

**Comment by DimDz** [comment]
Hello, I am trying to implement this (creating cards from month view)
![2022-06-28-13-18-09](https://user-images.githubusercontent.com/70445835/176156718-c13e2b7e-c124-451e-8886-d6bb693dc83f.gif)
it doesn't create the card yet, I need to find how cards are created at swimlanes. Should be something similar I suppose, but haven't found it yet. any tip so I can continue?

**Comment by xet7** [comment]
@DimDz 

Maybe this?

https://github.com/wekan/wekan/blob/master/client/components/lists/listBody.js#L38

https://github.com/wekan/wekan/blob/master/client/components/lists/listBody.js#L96

**Comment by DimDz** [comment]
Just an update, I tried to use API requests to create cards through calendar view. It works ! but needs improvement. At the moment,  it reads only the first swimlane and first list and creates the card there.

https://user-images.githubusercontent.com/70445835/184324324-b4bd466e-6873-4eef-8ca5-b6e4d9f95ac5.mp4

**Comment by DimDz** [comment]
@xet7 
At Calendar View, on Month when you click a date it will ask you if you want to create a new card and give its name. It then creates at first swimlane and at first list the card with the due date that it got from the date you clicked. Video demonstration is on my previous https://github.com/wekan/wekan/issues/2687#issuecomment-1212903865

**Comment by xet7** [comment]
@DimDz 

Is there any `+` button where it's possible to add new card? Can you add it? Clicking invisible position is not usable.

**Comment by xet7** [comment]
@DimDz 

Or alternativelu, description text above monthly calendar, that it's possible to click some date.

**Comment by xet7** [comment]
Hmm, it seems clicking calendar opens new card popup. Thanks! I'll try to add remaining fixes myself.

**Comment by DimDz** [comment]
Can do that, will check on it on Monday and will do a PR.

**Comment by xet7** [comment]
@DimDz 

To that create card popup, also please add to right top `X` close button.

It would be easier for you to do it. That code at https://github.com/wekan/wekan/pull/4922/files looks like amazing hack, I'm not able to look at it upside down yet, I have not drinked enough coffee enough yet. And I don't even know would there be any way to do it like other popups in WeKan, because it's at top of calendar. That's so amazing that this works.

**Comment by xet7** [comment]
To use translatons at Javascript, add to top of file:
```
import { TAPi18n } from '/imports/i18n';
```
Then use translation like this, adding it to middle of that text, joining strings:
```
TAPi18n.__('add-card')
```
Translation strings are here, new can be added with PR:

https://github.com/wekan/wekan/blob/master/imports/i18n/data/en.i18n.json

**Comment by mfilser** [comment]
@DimDz 
Maybe there is also the possibility to make the popup like all other popup's with the class https://github.com/wekan/wekan/blob/master/client/lib/popup.js ?

**Comment by DimDz** [comment]
PR https://github.com/wekan/wekan/pull/4934 adds right top `X` close button and translations.
Sadly I wasn't able to make the popup like the other popups.
