### ISSUE TITLE
Added new features.

### ISSUE THREAD

**Issue by techbtz** [wekan/wekan#2689]
Hello people. I am an application user and I am having difficulty using some features. I don't know if they exist or if the community can develop. Are they:

1 - How to set the default setting of Frame View? When you create a board with the ray view and invite someone to be part of that particular board, the board view is listed.

2 - How to copy or move multiple cards at once to different frames;

3 - How to send personalized messages inviting people to join the board (usually the message is automated and the person receives the email with an automated description);

4 - How to know which structure a subtask should be part of. (subtask is usually available in the "All frames" section);

5 - How to search on a specific subject in the section "All pictures"; and

6 - How to print the cards.

Thank you in advance for your attention. Thank you very much.

**Comment by xet7** [comment]
1. Do you mean at Board view toggle switch of Lists/Swimlanes/Calendar ? There is not yet setting to hide some of them, or set default. If board is public, public non-logged in viewers see only Lists view.

2. That feature does not exist yet. AFAIK there is already feature request for it. Currently you can clone one board, import/export board, or copy/move one card.

3. First Wekan user has Admin Panel. In settings there, you can disable self-registration and then becomes visible invite to boards. It's also possible at some board for any BoardAdmin or user to invite new user with email address to board.
https://github.com/wekan/wekan/wiki/Adding-users

4. Some documentation pages:
https://github.com/wekan/wekan/wiki/Subtasks
https://github.com/wekan/wekan/wiki/Templates
https://github.com/wekan/wekan/wiki/Custom-Fields

5. That feature does not exist yet. It's only possible to search from text contents of current board.

6. That feature does not exist yet. Well, you could export board to JSON, use some code to make it printable.

As you see from [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md), new features and fixes are added very often to Wekan, by many Wekan contributors (companies and individuals) from all over the world. So probably those will be added sometime.
