### ISSUE TITLE
Board Title Rename is not working

### ISSUE THREAD

**Issue by nata-goddanti** [wekan/wekan#269]
Renaming the board title does not work.

![image](https://cloud.githubusercontent.com/assets/203255/9619989/9bd58dae-50ca-11e5-9d75-ef9a7cd1429f.png)

**Comment by mquandalle** [comment]
I believe this was fixed in 9180a8d92a0dee969bba20239c253a6ecb186b2b. I've update newui.libreboard.com in case this is what you are using for testing. Could you confirm this bug is fixed?

**Comment by nata-goddanti** [comment]
:+1:  yep it is fixed.
