### ISSUE TITLE
Some my boards is not loaded and nothing happens

### ISSUE THREAD

**Issue by hever** [wekan/wekan#2693]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 3.37
* Operating System: linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 8.16.1
* MongoDB Version: 3.2.22
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
In newest version some of my board won't load. I see only loader and nothing happens. Some boards works. I revert to 3.36 and everything works.

I have nothing where to start find where it's occur. But when I look at changelog it is mabe problem in a56988c487745b2879cebe1943e7a987016e8bef #2688. Board that is not loading have some linked cards.

**Comment by xet7** [comment]
Ooops just a moment I test...

**Comment by xet7** [comment]
When I add linked card I can not get Wekan board to load.

Anyone have idea how to duplicate this?

**Comment by xet7** [comment]
@Akuket 

Does linked cards still work for you? Do you have any problems opening any boards on newest Wekan?

**Comment by hever** [comment]
Maybe try to add cardComments / attachments / checklists / checklistItems to the card you linked. I dont know, I only looking to the code.

**Comment by Akuket** [comment]
We have just updated. We do not know yet if we will have problems. However, before this update, we already had the problem mentioned here.

**Comment by Akuket** [comment]
You can try 2 things: (make a snapshot or dump of the database before)

The first one :
- Export the board with the api.
- Go to the database, find the board by id (you can see it in the board url /b/**boardId**/boardSlug) `db.boards.find({_id: "boardId"})`
- Update the board to indicate that it is archived `db.boards.update({_id: "boardId"}, {$set: {archived: true}})`
- In wekan, go to archived boards and remove it.
- Import the board.

The second:
- Go to the database and update all linked card of that board
    - Either you delete them `db.cards.remove({$where: "this.linkedId", boardId: "boardId"})`
    - Or you change their type `db.cards.update({$where: "this.linkedId", boardId: "boardId"}, {$set: {type: "cardType-card"}}, {multi: true})`

I hope it will help you

**Comment by Hubref** [comment]
Hello, 
i have the same issue: There is one big board not loadings after the update. 
Other smaller boards with linked tasks work just fine, so I am not shure thats due to the linked tasks.

Is there something i can do to help narrowing the possible problem down?

**Comment by hever** [comment]
@Hubref My not loaded board is big so. But i think size don't matters. Maybe it's because thé board is old and it has something different in database (because some old issue do inconsitent states).

This is what @Akuket aiming to.

**Comment by Hubref** [comment]
@hever thanks for the explanation. Our IT guru is in vacation and i am just developer and not used to do the administration as well ;-).

I was able to do an work around by reverting the version with snap to 3.36 and blocking the snap update with a firewall rule. As soon as the real admin is here I'll try the solutions of @Akuket and post the results here.

**Comment by topelrapha** [comment]
we had the same problem with version 3.37 and one large board.
Rolling back to 3.36 solved the problem.

**Comment by xet7** [comment]
Hmm, I'll try reverting back change that @Akuket make, to see does it make all boards load.

**Comment by Akuket** [comment]
Ok, for those who had some big boards not loading after v3.37, can you try to see the number of cards that you have in v3.39. `Cards.find().count()` in the console after loading your board.

**Comment by hever** [comment]
@xet7 Version 3.39 works, my board is now loaded.

@Akuket Yes, now is loaded everything from database. Let's see #2688

**Comment by topelrapha** [comment]
@Akuket Cards.find().count() -> 1389

The board is loaded in version 3.39 but i can't get any card details from linked cards. "Normal" cards open without problems.

Thanks for your work
