### ISSUE TITLE
Can not add rules

### ISSUE THREAD

**Issue by chrkoe** [wekan/wekan#2694]
## Issue
I was unable to add a rule to a board (as normal user on the board). I have admin rights on wekan itself.

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 3.37.0
* Operating System: Ubuntu 18.04.3 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome

**Problem description**:
I was unable to add a rule to a board (as normal user on the board). I have admin rights on wekan itself.

I added all the information for the rule creation process and after clicking on "Finish" the rule is not added. I did not get any error message.

I asked for admin rights on the board and after that I was able to add the rule.

**Comment by xet7** [comment]
Only Admins and BoardAdmins can manage rules.
