### ISSUE TITLE
Last/Only Administrator account can be deleted

### ISSUE THREAD

**Issue by Shorty365** [wekan/wekan#2695]
I work on the Dutch translation of Wekan and during testing and invoking some of the translated strings is think I found a serious bug. I was logged in in Wekan as the only Administrator and then I tried to revoke this right from myself, using the Wekan-interface. I was expecting an error-message but there was no error-message or even a warning. Result: I locked myself out as Administrator and now my Wekan-instance runs without administrator.

This happened in Wekan 3.35

Since I have no back-up some help to make my account an Administrator again would be appreciated. I'am not that smart with mongodb.

**Comment by xet7** [comment]
I presume you are running Snap version of Wekan. You see it with:
```
sudo snap list
```

1. Download nosqlbooster GUI https://nosqlbooster.com/downloads

2. Connect with it so server localhost 27019. It's possible to connect trough SSH also.

3. At wekan database, look at users table what is your user ID.

4. Then double click boards to list them, in dropdown table mode, and when you see your table name then edit that table in JSON.

5. Change your user ID to have admin rights to board, for you to be BoardsAdmin.

6. If you instead mean Wekan Admin that has access to Admin Panel, change in users table IsAdmin=true on your user.

**Comment by xet7** [comment]
Thanks for letting me know about this! There are still ways to do something unexpected in Wekan, although many of those ways are already fixed in newest Wekan.

Amount of Wekan issues grows faster than I'm able to fix. That's why all Wekan contributors are very important, when they can help to fix issues with pull requests.
