### ISSUE TITLE
Run as normal user

### ISSUE THREAD

**Issue by MyUncleSam** [wekan/wekan#2699]
Just a short question:
I installed Wekan using Snap. It is running very good but at the moment it runs under the root user. Is it possible to change it to a normal user without any troubles? (e.g. no database access or daily updates not working)

Thank you very much for your help!

**Comment by xet7** [comment]
Wekan code at Snap is in [strict](https://github.com/wekan/wekan/blob/master/snapcraft.yaml#L13)  sandbox inside of `/var/snap/wekan/common` directory, it can not access files outside of it, and also other access is limited. For more info about security design of Snap, see https://snapcraft.io . I can not change Snap security design.
