### ISSUE TITLE
Card Title becomes 'undefined' 

### ISSUE THREAD

**Issue by ednamaeG** [wekan/wekan#2703]
Server Setup Information:::

Did you test in newest Wekan?: Yes
For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
Wekan version: 3.20
Operating System: Ubuntu 18.04
Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Source?
Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
Node Version: v12.9.1
MongoDB Version: v3.6.3

Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome

**Problem description:**
Card Title and Card Link becomes 'undefined' on the sidebar after Archiving a Card 

**Steps to Reproduce**
- Create and archive a card.
- Check the sidebar

![image](https://user-images.githubusercontent.com/49261930/64833304-13b59980-d610-11e9-9467-054c446efae6.png)

**Comment by ednamaeG** [comment]
is there any way to fix it from our end?

**Comment by PCjabber** [comment]
I'm also experiencing this issue -- archived cards appear as "undefined" and can't be restored from the Archive dialog (I only see archived Boards there).

- New install with Sandstorm
- Wekan 4.09.0~2020-05-27
- Ubuntu 18.04
- Node 12.16.3
- Mongo 2.6.7

**Comment by xet7** [comment]
This is already fixed in newest Wekan v4.12.

For Sandstorm, I'm waiting for @ocdtrekkie to test and release official Wekan v4.12 for Sandstorm that I did push to experimental yesterday.

**Comment by PCjabber** [comment]
Awesome, thanks! Installed Wekan hours ago & I'm already impressed 👍

FYI, I found a related issue #3144 while searching the Github earlier (just mentioning in case it's also fixed in v4.12 so it can be closed).
