### ISSUE TITLE
Remove label when move card

### ISSUE THREAD

**Issue by juliensl** [wekan/wekan#2705]
Hi Wekan community !

## Issue

When I label a card, and then, move this card, the label is removed.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Ok dude
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 3.40.0
* Operating System: Ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node Version: 9.16.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox updated

**Problem description**:

![wekan_label_bug](https://user-images.githubusercontent.com/43228020/64849459-b58ab580-d613-11e9-8942-9b1685c1a525.gif)

- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
Only authentification logs, wich is useless here.

Thank you for your work ;)

**Comment by derbolle** [comment]
To add to this: This only seems to happen if the label has no text on it

**Comment by Akuket** [comment]
We also have the problem

**Comment by sfahrenholz** [comment]
Same problem

![grafik](https://user-images.githubusercontent.com/6977657/66244395-7a5a3e80-e708-11e9-850c-01b2c672f21b.png)

**Comment by xet7** [comment]
Please someone test what was previous version where it did work, and in next version it got broken. It can be tested with Docker version tags, like this:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L118
```
image: quay.io/wekan/wekan:v3.45
```

**Comment by juliensl** [comment]
Hi xet7

I installed a local Docker following this tutorial : https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository

After that, I tried to launch a wekan container with this command lines : 
```
docker run -d --restart=always --name wekan-db mongo:4.0
docker run -d --restart=always --name wekan --link "wekan-db:db" -e "WITH_API=true" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://192.168.1.200:2000" -p 2000:8080 quay.io/wekan/wekan
```
( https://github.com/wekan/wekan/wiki/Docker )

After that, I went to the url : http://192.168.1.200:2000

Must I do something more ? When I'm going on http://192.168.1.200:2000, I have this error : 
"Connection failed"

I don't have other Docker things, this is my first installation, but I have a wekan snap application on the port 4000.

Do you have an idea about what happen ? 

Thank you :smiley:

**Comment by juliensl** [comment]
I succeed to launch it with docker-compose ;)

**Comment by derbolle** [comment]
I will test this with different wekan versions as soon as I have access to our wekan test docker swarm again. I will reply to you as soon as possible

**Comment by juliensl** [comment]
I've got it ! 
It works at the version 2.48
And it is broken at the version 2.49 ! :smile: 

Thank you Docker :laughing:

**Comment by xet7** [comment]
Moved to #2970
