### ISSUE TITLE
Feature request: E-Mail Notification for Card-Events

### ISSUE THREAD

**Issue by pynaconda** [wekan/wekan#2706]
## Feature request: E-Mail Notification for Card-Events

Currently we are sending E-Mail notifications when e.g. someone is added to a card by using a webhook. Would it be possible of implementing this feature directly into the application?

**Comment by reyjul** [comment]
I'm also looking towards this feature. Currently it does not seem functional, although we are receiving email notifications when setting "change watch" to "watching". Until this issue is fixed, could you tell us how did you setup this webhook as work-around? Many thanks.
