### ISSUE TITLE
Feature Request: external link with editable right

### ISSUE THREAD

**Issue by juliensl** [wekan/wekan#2707]
Hi mates, 

I think it could be a good idea to improve the right system on boards.

I mean, currently we have 2 ways to create and share a board : 
 * Create a private board and add people for : read and write
 * Create a public board, which is searchable on google and share the link, people can : read only
If you want to modify a public board, you need to be added by the owner.

I think that it could be interesting to have the possibility to : 
 * Create a semi-public board, wich is viewable with the link but not searchable on google.
The link could be configurable to allow guests to read only or modify the board.

It is like on google drive, you can share a document readable only or editable too :smiley:  

**Server Setup Information**:
* Wekan version: 3.40.0

What do you think ? :smile_cat:

**Comment by rick-gnous** [comment]
it would be a great feature!

**Comment by krallowski** [comment]
Hey :)
I just stumbled over this feature request because we are also interested in this feature and saw it was marked as completed. Can you explain to me why it's completed? :)
