### ISSUE TITLE
Add new board tile gets hidden on the Boards Screen

### ISSUE THREAD

**Issue by nata-goddanti** [wekan/wekan#271]
When there are no boards, you see "Add New Board" tile, 

![image](https://cloud.githubusercontent.com/assets/203255/9620937/48c69378-50d5-11e5-9d7d-beab6861f973.png)

But when you add a board , it gets hidden behind the new board instead of being at the end.

![image](https://cloud.githubusercontent.com/assets/203255/9620951/92ee5724-50d5-11e5-80ce-7ecead0f8433.png)

**Comment by mquandalle** [comment]
I also think this one was fixed. Could you check with the latest version on `master`?

**Comment by ePirat** [comment]
I am not able to reproduce with latest master.

**Comment by nata-goddanti** [comment]
:+1:  This is fixed
