### ISSUE TITLE
CSS Bug on swimlanes titles

### ISSUE THREAD

**Issue by sclerc-chss** [wekan/wekan#2710]
**Server Setup Information**:

* Did you test in newest Wekan?: yes 
* Wekan version: 3.42.0
* Operating System:Debian 9.9
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: 8.16.1
* MongoDB Version: 3.2.22
* What webbrowser version are you using? bug confirmed on Firefox 60.9.0esr, Chrome 76, Vivaldi 2.7, Edge 42

**Problem description**:
If I've more lists that the screen can show, when I move to the right, the color of swimlanes titles doesn't go to the end of the table.

![firefox_jHFB95kV26](https://user-images.githubusercontent.com/53857862/64947964-58426e80-d876-11e9-815e-22eedb155eac.png)

Thank you.

**Comment by TheMasterFX** [comment]
On Wekan v3.76 still the same (Chrome 79.0.3945.130, Edge 44.18362.449.0).
Not a major issue

**Comment by sclerc-chss** [comment]
Still present in 4.0.3

**Comment by xet7** [comment]
Could someone figure out the fix to CSS and add pull request?

**Comment by xet7** [comment]
This is already fixed at PR https://github.com/wekan/wekan/pull/3370 at [Wekan v4.56](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v456-2020-11-30-wekan-release)
