### ISSUE TITLE
Question/Bug advanced filters

### ISSUE THREAD

**Issue by Akuket** [wekan/wekan#2712]
**Server Setup Information**:

* Did you test in newest Wekan?: No
* Wekan version: 3.37
* Operating System: Ubuntu 18.04
* Deployment Method: Docker
* Node Version: 8.16.0
* MongoDB Version: 4.0.12
* What webbrowser version are you using?  Latest Firefox/Chrome

**Problem description**:
  We would like to use advanced filters based on custom fields but all the ways we tried failed.
  Could we have an example to make them work or if it's a bug, could someone take a look at it?

Regards

**Comment by xet7** [comment]
Looking at [filter PRs](https://github.com/wekan/wekan/pulls?q=is%3Apr+filter+is%3Aclosed), does @urakagi or @feuerball11 have time to look at this?

**Comment by xet7** [comment]
Moved to here from https://community.vanila.io/?t=155f15ae-db6a-41df-a9f9-401908348243

From timothee

Hello community. I'm newbie on Wekan. I'm trying to filter cards on personalized fields. I use the advanced filter with my field 'My custom field' and the text i'm searching for so i type : 'My custom field' == .KeyWordToSearch.. The card is not founded. !

![d8091083-5137-4f92-9f3d-86897c3318fc-wekan-filtering-trial](https://user-images.githubusercontent.com/15545/65374535-a353eb80-dc93-11e9-871d-011c26baed4f.PNG)

I have also tried another filter with a personalized field without space : 'MyCustomField' == .KeyWordToSearch.. Doesn't work.

I've tried many combinaison and i'm not able to find the right assuming that my card and a custom field named MyCustomField that contains KeyWordToSearch ! Could you help me please ?

My trials : 'MyCustomField' == .KeyWordToSearch. MyCustomField == ./KeyWordToSearch./ MyCustomField == KeyWordToSearch

**Comment by Akuket** [comment]
Same problem

**Comment by xet7** [comment]
@Akuket 

Does this still happen in newest Wekan?

**Comment by rokokoh** [comment]
Hi,
To answer to your question :
I run in the same proble but in my version 5.58.0 the search for personalized field it's not work when i click on the name of the filter but when i'm searching in advance filter it's okay.

Tell me if you need more information.
