### ISSUE TITLE
Feature request: The ability to delete users

### ISSUE THREAD

**Issue by Akuket** [wekan/wekan#2716]
This issue aims to discuss the ability to delete users and resulting constraints (functional/technical).

### Who can do it:
- Wekan's administrators.
- One user to self-deleting his account.

### What does this imply:
- Either a complete deletion of associated data that I will list later.
- Or keep the data of one or more boards by transferring the data to a member of that board.

### How to:
When an administrator or the user confirms that he wants to delete that account, he is redirected to a new page which contains all boards where he is a member. For each, he can choose two things:
 - Explicitly delete data associated for that board.
 - Choose one board member to give him all the data. Maybe like that
![image](https://user-images.githubusercontent.com/32392661/65023316-d401f100-d932-11e9-8ca2-bb16ecdb2499.png)

### When to delete one board:
If the user is the last board member or the last administrator of the board and there is no board member selected for a data transfer.

### What to delete:
If I forget something, don't hesitate to point it out. In what follows, this will correspond to MongoDB collections.

#### Always:
  -> user
  -> avatar
  -> orgUser

#### If last board member / last administrator and not data transfer:
-> board
-> [swimlane]
-> [list]
-> [card]
-> [activities]
-> [attachment]
-> [cardComment]
-> [checklist]
-> [checklistItem]
-> [customField]
-> Integration ???
-> [rules]

#### Else if no data transfer:
Only find and delete by userId

-> [card]
-> [activities] (Only for cards, attachments, cards comments, checklists, checklist items. And add one for all deleted cards).
-> [attachment]
-> [cardComment]
-> [checklist]
-> [checklistItem]

### After choosing the data transfer
Only find and update by userId

- If the deleted user was a board administrator, his rights are transferred to the selected user.
- All Cards, attachments, cards comments, checklists, checklist items, activities which belonged to the deleted user are affected to the selected user.
- For cards, if there is some requestedBy or assignedBy, they are affected to the selected user.

### Security concerns:
- The new page is only accessible to an administrator or the owner of the account.
- The url of that page might be https://domain/people/userId/delition. The userId will be used to check permissions when the user is not an administrator
- If the user is the last administrator of wekan, he can't delete his account.
- For the data transfer, only board members can be chosen to ensure confidentiality.

**Comment by xet7** [comment]
Here is some beginning of UI design.
Before deleting anything, there needs to be to select, view, edit or move
the content of all the data that is going to be deleted.

Improvements welcome.

## Admin Panel / People

```
People [______] Search    Selected: UsernameHere

Organizations | Username Fullname Admin Email Authentication Method
Teams         | (abow column names should keep their place, not move)
People >      | (not all profile data columns listed, more at profile page) 
Profile       | (when clicking user row, it becomes selected above) 
Boards        |
```

## Admin Panel / People / Profile

```
Selected: UsernameHere
                                          _______________
Organizations | Username ...              | Avatar image |
Teams         | Fullname ...              |              |
People        | Admin    ...              |______________|
Profile >     | Email    ..
Boards        | Authentication Method
              | [Save]                      [Delete User]
              |                       (confirm, and if no boards)
```

## Admin Panel / People / Boards

```
Selected: UsernameHere

Organizations | Select all - Unselect All
Teams         | [_] BoardName 1 | Admin            
People        | [_] BoardName 2 | User
Profile       | [_] BoardName 3 | NoComments
Boards  >     | [_] BoardName 4 | CommentOnly

Organizations | Selected: Change to [Admin/User/.. dropdown] [Change]
Teams         |           Move to __username__ with [Admin/User/.. dropdown] [Move]
People        |           [View one board]
Profile       | 
Boards  >     | Select all - Unselect All
              | [_] BoardName 1 | Admin            
              | [_] BoardName 2 | User
              | [_] BoardName 3 | NoComments
              | [_] BoardName 4 | CommentOnly
```

**Comment by Akuket** [comment]
Ok, so a button to make an export of one board can be added. But the rest of your answer goes beyond the scope of the deletion. Maybe another issue can be opened to see what can be done to improve the user's management?

**Comment by xet7** [comment]
@Akuket 

There is already Teams/Organizations issue #802 . I did list all those plans, because you already went out of scope. I don't know what size scope you have.

To delete something, there needs to be ability to select what data of those to delete.

When user is deleted, user is usually removed from boards and cards. Board ownership is changed to other user.

Deleting activities in problematic. Who has then done all those changes? If those are assigned to other user, that user really has not done them.

Deleting cards, checklists etc is problematic. What about remaining users that are at that board?

Wry remove rules? I don't think Wekan currently saves history data about who has made those rules. Removing rules would stop working board automations.

Current problem with deleting user was, that there was remaining "ghost avatar" user at board and cards, without any avatar image.

Please give details of your smaller scope, that still makes possible existing boards users to continue work without loss of major functionality.

**Comment by Akuket** [comment]
@xet7 

#### Case 1 The data transfert: 
There is no data that will be deleted in the board, all content will be assigned to someone else chosen by the administrator or the user if you enable self-deleting.

#### Case 2 No data transfert and there is at least one administrator of the board:
Here all cards and its dependencies (checklists,...) who belonged to that user will be deleted.

#### Case 3 No data transfert and the user is the last administrator of the board:
Delete all data of that board (lists, swimlanes, rules,...).

**Comment by Akuket** [comment]
Or, when one user wants to self-deleting his account, we only anonymize and deactivate his account.  So the ability to delete an account and if needed associated data (cards,...) is only an administrator feature.
It's the minimum personal data management we need.

**Comment by Darthagnon** [comment]
Is it possible to delete users in WeKan? I was testing but was unable to find any options to do so.

**Comment by xet7** [comment]
@Darthagnon 

For any user account that are not needed anymore, at Admin Panel you change that users password and set user as not active.

Actual deleting is not fixed yet.

For non-password 3rd party login like OIDC/OAuth2 and LDAP, Wekan has no way to write anything to those login details. For those, account are managed in those OIDC etc authentication servers, like AD, LDAP etc server management console.

**Comment by Darthagnon** [comment]
@xet7 Thank you for the info! I'll keep an eye on this topic, then :)

**Comment by robbagithub** [comment]
Would be great to see this go in shortly 👍

**Comment by MFYDev** [comment]
+1, really looking forward this feature

**Comment by darren-teo** [comment]
I recall this API, https://wekan.github.io/api/v3.55/#delete_user, used to work in previous versions.

I tried the API in the latest Wekan v5.35 but it doesn't work any more. I get HTTP status 200 OK, however the user just doesn't get deleted. Is this the expected behaviour?

**Comment by xet7** [comment]
@darren-teo 

- Delete user feature has bug, it leaves empty avatar icons to boards where deleted user used to be member of.
- Delete user works only for password login users. It is not possible to delete OAuth2/LDAP users completely, because those are managed by identity provider like OAuth2/LDAP user management consoles, not Wekan.

Having this feature depends is there any contributor willing to look at Wekan code, fix it and submit pull request. Wekan would progress much faster if there were more contributors sending pull requests.

**Comment by darren-teo** [comment]
@xet7 
I have users with password login only. I have also remove the users from all boards.

I realize the API returns the user id even when I deliberately enter a non-existent one.

I just want to clarify if this is the expected behavior from the API.

**Comment by xet7** [comment]
@darren-teo 

No problem, I will enable delete user with API and Admin Panel.

Expected behaviour for this is to:

- Wait someone to complain about that empty avatar icon bug
- Wait someone to complain about cliking delete user button by accident
