### ISSUE TITLE
Infinite loading on chromium

### ISSUE THREAD

**Issue by lampi87** [wekan/wekan#2718]
Hi guys,

on chromium 74.0.3729.157 opening a board leads to infinite loading. Opening Dev-Tools shows the following error messages:
* Exception in template helper: TypeError: Cannot read property 'hasHiddenMinicardLabelText' of null at Object.hiddenMinicardLabelText
* Exception in template helper: TypeError: Cannot read property 'getLimitToShowCardsCount' of null at n.limitToShowCardsCount
and many more

Currently installed version of wekan is 3.44

On Firefox and Chrome it's works fine.

Thx in advance!

**Comment by xet7** [comment]
That is because of Meteor bug, browser is detected wrong. Well, meanwhile you could spoof user agent. Sorry I have not had time to look at it yet.

Moved to #2643
