### ISSUE TITLE
Error 404 When Click On Card

### ISSUE THREAD

**Issue by matthoweonline1977** [wekan/wekan#2722]
I have Wekan up and running on Ubuntu / Snap. Everything seems working correctly however when I click on a card (It lets you create a cards...) But if I click on existing card after creation it throws a 404 error.

**Comment by webafrancois** [comment]
I had the same problem with a wrong url in https on a local network without SSL.
What is your root url ?
https://github.com/wekan/wekan/wiki/Settings

**Comment by matthoweonline1977** [comment]
Not certain... I have Wekan running in a VM on my Windows desktop. Windows
is Windows 10 but the VM is Ubuntu. Bridged the network adapter / can
access via my web browser on my Windows system via direct ip address...

192.168.200.232:8080

*Matthew Howe*
720-989-1773

**Comment by matthoweonline1977** [comment]
I am thinking it is an issue in that when the card is clicked it wants to
reference 127.0.0.1/jfkdlasjfkladsjkl;fjkdsjflkjdasfkljasj

I think I need to set wekan address static to my 192.168.211.133:8080

Is there a place to edit in the Wekan source to changed this? I did change
it within the browser and it worked... Brought up the card to edit the
information on it... Please let me know. This will be great. Thank you.

*Matthew Howe*
720-989-1773

**Comment by matthoweonline1977** [comment]
Also is there a way to edit the port running on from 8080 to something else?

*Matthew Howe*
720-989-1773

**Comment by webafrancois** [comment]
How did you install Wekan ? With the snap procedure ? 
Like this ? https://github.com/wekan/wekan-snap/wiki/Install
So, you should set the url_root in this install procedure.

**Comment by matthoweonline1977** [comment]
I simply installed the server and within the server setup it allows you to
choose weeken and I assume must take it from that Repository. It must
utilize snap, because I had to start the snap service before I could pull
up weekend in localhost.

From the Windows computers on the local area network I am able to access
the server IP address alcohol weaken successfully to the login. Once logged
in if you click on a card it illustrates 127.0.0.1/x/xxxxxxxxxxx and error
code 404

If I manually change this address in the address bar to the server IP
address and refresh it functions properly...

There must be some way to change this Within the system. What if I were
connecting location to location via VPN?

**Comment by matthoweonline1977** [comment]
Are you referring to the caddyfile?

**Comment by webafrancois** [comment]
Wich commands did you type to install the server ?

**Comment by xet7** [comment]
```
sudo snap set wekan root-url='http://192.168.211.133:8080'

sudo snap set wekan port='8080'
```

**Comment by matthoweonline1977** [comment]
I did not do any commands on the server... simply downloaded the latest
version of Ubuntu server. Wekan is a selectable item from the repository in
the setup. The server completes its install. And then, I ran the

Sudo snap start wekan

Command and it started successfully. I was then able to access we can from
my LAN by inputting the server's IP address and port 8080

**Comment by matthoweonline1977** [comment]
I simply clicks basically the next next next continue through the setup and
accepted all of the defaults but it was literally just from a bun to and
selecting wekan as a check box during setup

**Comment by xet7** [comment]
@matthoweonline1977 

Above I did mention snap commands that will make your card to open correctly.

**Comment by xet7** [comment]
```
sudo snap set wekan root-url='http://192.168.211.133:8080'

sudo snap set wekan port='8080'
```
