### ISSUE TITLE
Cannot read property 'getDefaultSubtasksListId' of undefined

### ISSUE THREAD

**Issue by compumatter** [wekan/wekan#2723]
## Issue
When trying to add a Sub Task to a Card it immediately spawns this error in the browser developer console.  Have tried stopping / starting Wekan.  Have also rebooted the server. The error persists.

Cannot read property 'getDefaultSubtasksListId' of undefined

Other Wekan issues can be added here.

**Server Setup Information**:
Ubuntu 18.04 Server.  

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 3.25
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): bundle/source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: v8.16.1
* MongoDB Version: 4.0.1
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
Chrome and Firefox (same issue on both)
**Problem description**: 
When trying to add a Sub Task to a Card it immediately spawns this error in the browser developer console
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
Open an existing card.  Click Add Subtask.  Fill in a task name.  As soon as you click the Save button, the error occurs.
![wekan-sub-task](https://user-images.githubusercontent.com/121611/65364504-0f1c5280-dbc7-11e9-91e8-da9ff1d09345.gif)

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:339 Uncaught TypeError: Cannot read property 'getDefaultSubtasksListId' of undefined
    at n.addSubtask (a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:339)
    at a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:233
    at Object.f._withCurrentView (a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:63)
    at a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:233
    at e._withTemplateInstanceFunc (a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:63)
    at f.View.t.<computed> (a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:233)
    at a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:63
    at Object.f._withCurrentView (a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:63)
    at f._DOMRange.<anonymous> (a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:63)
    at HTMLFormElement.delegatedHandler (a9f280c90fb09b788fe837244522852640e410b4.js?meteor_js_resource=true:63)
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

**Comment by xet7** [comment]
Please change your Subtasks settings to be correct:
https://github.com/wekan/wekan/wiki/Subtasks

**Comment by xet7** [comment]
@compumatter 

Does this still happen in newest Wekan?

**Comment by compumatter** [comment]
No - this is resolve.  Thank you!
