### ISSUE TITLE
 Deprecation Warning Buffer()

### ISSUE THREAD

**Issue by Tampa** [wekan/wekan#2725]
Deployed on nodejs 10, fibers2.0.1 Ubuntu 18.04 lts

(node:31502) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Seems like an issue with nodejs itself, is that correct?
Can try to upgrade nodejs, but under 12 it won't build and latest version of fibers is also not compatible.

Can I ignore that or should I look through code and fix those buffers; hand you a pull request for it?

**Comment by xet7** [comment]
It's a issue in Node version.

Currently Wekan uses Meteor 1.8.1 that uses Node.js 8.16.1, as can be seen from [Dockerfile](https://github.com/wekan/wekan/blob/master/Dockerfile).

Wekan will use [Node.js 12 when this pull request is ready](https://github.com/meteor/meteor/pull/10527). You don't need to send any pull requests for it.

Usually on Ubuntu Wekan is [installed from Snap](https://github.com/wekan/wekan-snap/wiki/Install), although Snap uses MongoDB 3.2.22. With Docker and Source install you can use newest MongoDB 4.x.

Source install is done with `rebuild-wekan.sh` from https://github.com/wekan/wekan with options 1 and 2.

**Comment by Tampa** [comment]
I see there are beta releases for 1.9, have you done any tests with that yet?

**Comment by xet7** [comment]
No.

**Comment by Tampa** [comment]
So I fetched the latest release, installed node 12 via their setup_12.x, then ran npm install node-gyp node-pre-gyp fibers in /bundle/programs/server after removing the /bundle/programs/server/node_modules/.bin/node-gyp file manually.

Started again using the same exports and get the same Buffer deprecated warning. Should I do more when upgrading?

**Comment by xet7** [comment]
@Tampa 

Buffer deprecated warnings have not been fixed yet. Those warnings do not affect Wekan in any way, Wekan still works.

**Comment by Tampa** [comment]
Ah okay, got the impression that would have been part of the upgrade to node12, I know it does not break anything... yet... anyways, upgrade has worked well, thanks for the effort :)
