### ISSUE TITLE
Templates Name are differents as import or in templates

### ISSUE THREAD

**Issue by webafrancois** [wekan/wekan#2727]
## Issue
**Server Setup Information**:
* Wekan version: 3.44
* Operating System: Debian 9
* Deployment Method : docker
* Node Version: 8.16.1
* MongoDB Version: 3.2.21
* Webbrowser :  Firefox 69 on Linux

**Problem description**:
The templates names shown when I add a new board from my templates are not the same that I add in templates menu.
![add-board-templates](https://user-images.githubusercontent.com/19719849/65467425-a3094b00-de61-11e9-8111-cf0f46e5abfe.gif)

From Add a board :
* projet1
* Taches-SI
perhaps the first name when we created this template

From Templates : 
*  Projets
* Taches-a-partager-SI

So I think that rename function in template don't work as well.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
