### ISSUE TITLE
Add board with "+" is empty with no templates

### ISSUE THREAD

**Issue by webafrancois** [wekan/wekan#2728]
## Issue

Server Setup Information:

    Wekan version: 3.44
    Operating System: Debian 9
    Deployment Method : docker
    Node Version: 8.16.1
    MongoDB Version: 3.2.21
    Webbrowser : Firefox 69 on Linux

Problem description:
When I Add a new board, with template link, I see my 2 templates.
But When I choose the "+" in the top bar, there is no one. I can't choose anyone.
![add-board-with-plus-emply-template](https://user-images.githubusercontent.com/19719849/65468268-efee2100-de63-11e9-8b5e-0c0b8b1f8be5.gif)

**Comment by jrsupplee** [comment]
I have the same issue on Wekan 3.46
