### ISSUE TITLE
Add board with + show differents cards as templates in a board

### ISSUE THREAD

**Issue by webafrancois** [wekan/wekan#2729]
## Issue

Server Setup Information:

    Wekan version: 3.44
    Operating System: Debian 9
    Deployment Method : docker
    Node Version: 8.16.1
    MongoDB Version: 3.2.21
    Webbrowser : Firefox 69 on Linux

Problem description:
When I use the "+" in a board, to add a new board, the pop-up show no templates, but a list of cards, which are in another board.
When I change the actual board to another, and add a new board with the "+", the list of cards are differents, but no templates anyway.
![probleme-create-board-in-boards](https://user-images.githubusercontent.com/19719849/65469001-2331af80-de66-11e9-8f79-048ab96b07de.gif)

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Templates
