### ISSUE TITLE
Custom fields export doesn't work

### ISSUE THREAD

**Issue by Akuket** [wekan/wekan#2730]
**Server Setup Information**:

* Did you test in newest Wekan?: No
* Wekan version: 3.37
* Operating System: Ubuntu 18.04
* Deployment Method: Docker
* Node Version: 8.16.0
* MongoDB Version: 4.0.12
* What webbrowser version are you using?  Latest Firefox/Chrome

**Problem description**:
- Create some custom fields and add them to cards.
- Export your board.
- Open the generated JSON. You will see your custom fields in cards like that `"customFields":[{"_id":"fNrKTCQmCyGuz6Pbo","value":"Coucou"}]`, but the custom field himself which has the id fNrKTCQmCyGuz6Pbo is not in the export. So when you will import the JSON, the IDs of the custom fields values shown in the cards will not be related to any real value. 
- Now import the board. All custom fields no longer present.

Regards

**Comment by alexander-dammeier** [comment]
This issue is still present in version 3.49.0. This is already supported in #1775 .
I have the same problem and I hope there is a solution for this in the near future. This bug exists over a year now and is the reason why we are not using custom fields in production.

**Comment by xet7** [comment]
Does anyone have time to look where error is in export or import code? And create pull request?
https://github.com/wekan/wekan/tree/master/models

I already have [really long todo list](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license).

**Comment by xet7** [comment]
According to #3137 exported JSON does include Custom Fields.
