### ISSUE TITLE
NOTIFY_DUE_DAYS_BEFORE_AND_AFTER not working as expected

### ISSUE THREAD

**Issue by JASG94** [wekan/wekan#2733]
## Issue

**Server Setup Information**:  Installation with Docker container (over Kubernetes)

* Did you test in newest Wekan?: Yes, tested on v3.44
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes, it's correctly configured
* Wekan version: v3.44
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 8.16.1
* MongoDB Version: 4.0

**Problem description**:

We are having some troubles with the env variable NOTIFY_DUE_DAYS_BEFORE_AND_AFTER. As I see in the docker-compose.yml file giving a 0 value to this variable will desactivate the "Due date" notifications, but it's not working as expected. I we set it to 0 we're still reciving notificatios about due dates.

Taking a look at the code, I think that the problem could be in the following code fragment:
![image](https://user-images.githubusercontent.com/32646573/65576180-bc012180-df71-11e9-9749-05a3a78f86d2.png)

It can be found in _cards.js_ line 1585. 

I think that this statement. 
`const notifydays =parseInt(process.env.NOTIFY_DUE_DAYS_BEFORE_AND_AFTER, 10) || 2;`

Will always set notifydays to 2 when NOTIFY_DUE_DAYS_BEFORE_AND_AFTER is equal to 0, so notificatios will not be disabled in the following if conditional.

So in order to disable notifications we can set this variable with a value grater than 15 or minor than 0, but with 0 it's not working as expected.

Thanks for you attention,
Javi.

**Comment by xet7** [comment]
Something related is merged https://github.com/wekan/wekan/pull/2738 but it's missing some changes that are mentioned at that Pull Request.

It's not released yet, I need to do #2081 first.

**Comment by xet7** [comment]
Please try Wekan v3.45 and info mentioned at https://github.com/wekan/wekan/pull/2738
