### ISSUE TITLE
Feature request : advanced search

### ISSUE THREAD

**Issue by vogloblinsky** [wekan/wekan#2737]
As a user, i want to be able to search in custom fields with the search bar.

Is that in the roadmap ?

My company need that for internal use, we can enhance Wekan and submit a PR after.

Regards

**Comment by xet7** [comment]
There is some bug #2712 in Advanced Search.

Best way to help is to submit pull request. Thanks!

**Comment by xet7** [comment]
Please test newest Wekan.
