### ISSUE TITLE
Cards don't move anymore

### ISSUE THREAD

**Issue by webafrancois** [wekan/wekan#2739]
**Server Setup Information:**

- Did you test in newest Wekan?: Yes
- Wekan version: 3.44
- Operating System: Debian 9
- Deployment Method: Docker
- Node Version: 8.16.1
- MongoDB Version: 3.2.21
- What webbrowser version are you using? Latest Firefox/Chrome

I make an upgrade from my install (from 3.40 to 3.44) and I made also a fresh install with docker-compose and the same instructions, but my cards don't move.

I can change a card to another list from the menu "move card" but I can't use the mouse to move it.
I don't understand because everything worked yesterday.
I made 3 fresh install and the problem is the same.

I try it on several web browsers.

![wekan-dont-move-card](https://user-images.githubusercontent.com/19719849/65754902-59935700-e112-11e9-8f8a-855e1766e954.gif)

**Comment by NoxInmortus** [comment]
Same issue here.

Latest docker image.

Wekan Version | 3.44.0
Meteor version | 1.8.1
Node version | 8.16.1
MongoDB version | 4.0.12

**Comment by mandalmanav** [comment]
I am also facing same issue

**Comment by xet7** [comment]
Current master has in progress drag handle changes, that's why they don't move, so it's not possible to use latest tag currently.

That's why it's currently needed to use version tag v3.44

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L118
```
image: quay.io/wekan/wekan:v3.44
```

**Comment by guillaumebriday** [comment]
Same issue here with the latest version available on the Docker Hub 🤷‍♂️

**Comment by webafrancois** [comment]
I correct my docker-compose like you write, xet7 and it's fixed ! 
Thanks a lot.

**Comment by hardmooth** [comment]
Has this bug been repaired in the master branch?

Because at the moment, my wekan installation is version-fixed at v3.44.

Sunny greetings and thank you

**Comment by xet7** [comment]
@hardmooth 

Of course, this has been fixed a very long time ago, and this is a closed issue. Only open issues are not fixed yet. Newest Wekan is v3.97.

**Comment by hardmooth** [comment]
@xet7 
Thank for your reply.

Well, I read your comment https://github.com/wekan/wekan/issues/2739#issuecomment-536106590
> That's why it's currently needed to use version tag v3.44
> https://github.com/wekan/wekan/blob/master/docker-compose.yml#L118
> image: quay.io/wekan/wekan:v3.44

and the rest of the issues the following way:
* There's currently a bug on master, but you can stay on v3.44 (as a workaround)
* by using the version tag v3.44, webafrancois didn't experience the bug anymore
* thus he closed it, although the underlying bug wasn't yet fixed

Good to know, though, that the bug was indeed fixed and one can remove the version tag.

**Comment by xet7** [comment]
If cards can not move, that kind of bug is usually noticed and fixed fast.
