### ISSUE TITLE
How due date coloring works?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2741]
https://community.vanila.io/?t=5633e6bb-f708-4f7f-b06f-155b3c434c66

@rjevnikar 

You originally added https://github.com/wekan/wekan/pull/1814 , do you know how due date coloring works?

**Comment by justinr1234** [comment]
https://github.com/rjevnikar/wekan/blob/1a64a88d3d1750c58bcf6d0b6bc584a6483d0fc7/client/components/cards/cardDate.js#L342

It is not accounting for time, only days. That is the issue.

**Comment by xet7** [comment]
@rjevnikar 

Can you make it account for time too, with pull request?

**Comment by bandresen** [comment]
I'm willing to work on this. But I think the due date and end date coloring is very confusing and should be redone.

Shouldn't the end date color always be green when it was successfully completed before the due date?

Yellow when the end date is within 24 hours (or less) of the due date and red if it's over that previous value.

**Comment by liske** [comment]
> Yellow when the end date is within 24 hours (or less) of the due date and red if it's over that previous value.

Maybe yellow is *not* needed, for short term tasks this would always be yellow. This is a binary decision: there is a due date (read: timestamp - it is not only a date) and if a task is finished until it's due date it should be OK (green), if no it should be not OK (red). Some workflows may accept small overdues (yellow) but that is not generic.

**Comment by bandresen** [comment]
I'm fine with that.

@xet7 Would you accept a PR that changes the end-date Timestamp to work the following way:
* if no due-date timestamp is set => Gray
* if end-date timestamp is younger than due-date timestamp => Green
* if end-date timestamp is older than due-date timestamp => Red

**Comment by xet7** [comment]
@bandresen 

Yes. Thanks!
