### ISSUE TITLE
Bug: drag & drop not working on Linux

### ISSUE THREAD

**Issue by marco-lancini** [wekan/wekan#2743]
## Issue

**Server Setup Information**:

* Running Wekan via `docker-compose` as per setup provided in: https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml
* Did you test in newest Wekan?: Yes, `wekan:latest`

**Problem description**:
* It is not possible to drag & drop cards between columns (tried on Chrome & Firefox on Ubuntu)
* The only way to move them is to use the menu `Move Card`

**Comment by xet7** [comment]
@marco-lancini 

I tested one second ago with that docker-compose.yml, without any changes, it works on my laptop at http://localhost/sign-in with `docker-compose up -d`.

For ROOT_URL settings, see https://github.com/wekan/wekan/wiki/Settings

And also https://github.com/wekan/wekan/wiki/Adding-users

For updating, remove old wekan-app first:
```
docker-compose stop
docker rm wekan-app
docker-compose up -d
```
Do not remove wekan-db, it has mongodb with all Wekan data.

Alternatively, as very dangerous option, delete all docker images/containers/etc data with `start.sh`
https://github.com/wekan/docker-cleanup-volumes

Note: To move card to some list that has no card, you need to first create one card there, so you can then move cards to that list. If there is extra cards, you can archive them.

**Comment by marco-lancini** [comment]
Hi @xet7, thanks for replying but I've been a Wekan user for a few years now and I know how to manage settings and create users.
This is the same setup I've run on other OSs (e.g., macOS), but on Linux I cannot drag & drop.
I've already removed container and image, but the problem persists

**Comment by xet7** [comment]
@marco-lancini 

I did test at my laptop with Chrome browser, and dragging did work. I'm running Debian testing.

**Comment by xet7** [comment]
Do you have newest docker-compose.yml from https://github.com/wekan/wekan ?

**Comment by marco-lancini** [comment]
Yes, I tried with that as well

**Comment by marco-lancini** [comment]
Update, I ended up enabling `Change Settings > Show desktop drag handles`, which no allows me to drag & drop cards.
I still cannot drag & drop when the drag handles are disabled.

**Comment by xet7** [comment]
@marco-lancini 

What Wekan version are you running? Admin Panel / Version ?

**Comment by xet7** [comment]
@marco-lancini 

Newest Wekan version v3.45 does not have option `Change Settings > Show desktop drag handles` in Docker latest version. You are running some old development version.

**Comment by xet7** [comment]
That `Change Settings > Show desktop drag handles` is In Progress feature at `feature-drag-v2` branch. It is not in latest Docker version that is base on master branch.

**Comment by xet7** [comment]
And currently at `feature-drag-v2` branch dragging also works when desktop drag handles are not enabled.

**Comment by adishmi** [comment]
Hi,
I have the same problem. Only if I enable "Change Settings > Show desktop drag handles" so drag and drop works..
I'm running on 3.49.0

**Comment by adishmi** [comment]
On Windows 10 Pro

**Comment by xet7** [comment]
@adishmi 

https://github.com/wekan/wekan/issues/2704#issuecomment-553268515
