### ISSUE TITLE
404 Site netp.doctorpcwin.ru is not served on this interface

### ISSUE THREAD

**Issue by doctorpccomputers** [wekan/wekan#2748]
When I installed ssl, I have started to get this error: 

`404 Site netp.doctorpcwin.ru is not served on this interface`

CaddyFile:

```
http://netp.doctorpcwin.ru https://net.doctorpcwin.ru {
        tls {
            load /var/snap/wekan/common/certs
            alpn http/1.1
        }
        proxy / localhost:80 {
          websocket
          transparent
        }
}
```
Please help. Thanks

**Comment by xet7** [comment]
With custom SSL cert, like https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config
```
http://netp.doctorpcwin.ru https://net.doctorpcwin.ru {
        tls {
            load /var/snap/wekan/common/certs
            alpn http/1.1
        }
        proxy / localhost:3001 {
          websocket
          transparent
        }
}
```
Wekan runs at localhost port 3001 (or some other you configure it to use). Caddy 443 proxies to localhost 3001 Wekan. Caddy http is at 80 and Caddy https is at 443.
```
sudo snap set wekan caddy-enabled='true'
sudo snap set wekan port='3001'
sudo snap set wekan root-url='http://netp.doctorpcwin.ru'
```
If you don't use CloudFlare to redirect from http to https, you can also [redirect](https://caddyserver.com/docs/redir) this way:
```
http://netp.doctorpcwin.ru {
        redir https://net.doctorpcwin.ru{uri}
}

https://net.doctorpcwin.ru {
        tls {
            load /var/snap/wekan/common/certs
            alpn http/1.1
        }
        proxy / localhost:3001 {
          websocket
          transparent
        }
}
```
Alternatively, [automatic Let's Encrypt SSL cert](https://caddyserver.com/docs/automatic-https) this way:
```
netp.doctorpcwin.ru {
        tls {
            load /var/snap/wekan/common/certs
            alpn http/1.1
        }
        proxy / localhost:3001 {
          websocket
          transparent
        }
}
```
[More Caddy examples](https://github.com/caddyserver/examples)

**Comment by doctorpccomputers** [comment]
It is not helped to me. Yes, I've done this commands:
```
sudo snap set wekan caddy-enabled='true'
sudo snap set wekan port='3001'
sudo snap set wekan root-url='https://netp.doctorpcwin.ru'
```
But when I go to https://netp.doctorpcwin.ru:3001/ I get this error now:
ERR_SSL_PROTOCOL_ERROR (Chrome).
My SSL sertificate file is /var/snap/wekan/common/certs/netp.doctorpcwin.ru.pem.

And I don't using CloudFlare. I using Comodo SSL. 
And...

My SSL key starting how `-----BEGIN RSA PRIVATE KEY-----` but in wiki it's `-----BEGIN PRIVATE KEY-----`
What variant I should use?

Sorry for my bad english :)

**Comment by xet7** [comment]
https://netp.doctorpcwin.ru/sign-in

**Comment by xet7** [comment]
https://netp.doctorpcwin.ru/sign-up

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Adding-users
