### ISSUE TITLE
Feature request: Retrieve full card information by API

### ISSUE THREAD

**Issue by coelebs** [wekan/wekan#2749]
## Issue
I want to create automations similar to Kanboard to create dynamically recurring tasks. To be able to create new tasks with due dates. With Node-Red I could build this but the webhooks don't pass along all the card details, and there is no API function to retrieve all card information (including custom fields)

I have the cardId, if I could do a GET to the API to retrieve all details, that would help a lot

**Comment by xet7** [comment]
Related #2746
