### ISSUE TITLE
can't sign in into wekan first time :login forbidden

### ISSUE THREAD

**Issue by shawnmc00** [wekan/wekan#2752]
HI, I run wekan by docker on windows 10.I just change port 80:8080 to 8880:8080 in docker-compose.yml and then use 'docker-compose up' command to run wekan.
then browse 127.0.0.1:8880 on chrome  and register an user. but when i sign in this user there is a alert:login forbidden.

![企业微信截图_20191009155858](https://user-images.githubusercontent.com/25921985/66462506-d2e55f00-eaad-11e9-80ee-5b3ee087d1ee.png)

**Comment by xet7** [comment]
If you can't use default port 80, then you need to also change ROOT_URL to `http://localhost:8880`, and login on that address, not 127.0.0.1

Or alternatively, configure it to use your computer IP address:
https://github.com/wekan/wekan/wiki/Settings

https://github.com/wekan/wekan/wiki/Adding-users

Usually starting is done with:
```
docker-compose up -d
```
When registering, you could copy-paste your username/email address/password so they get typed correctly.

If you can't login, you can stop and remove wekan containers and start again, this deletes all data:
```
docker-compose down
docker rm wekan-app wekan-db
docker-compose up -d
```
If you have configured some authentication method like OAuth2 or LDAP, then you need to login with your email address and password.
