### ISSUE TITLE
Mirror/Sync of boards

### ISSUE THREAD

**Issue by chirrut2** [wekan/wekan#2755]
Hi,
"just" a question: Is there a possibility to sync two boards/cards over the same and/or different wekan installations?

br,
Daniel

**Comment by xet7** [comment]
When you are creating new card, there you can click `Link` to create link to card that is at other board. This is on same Wekan.

You could use REST API to sync to other Wekan:

Get bearer token:
https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data

And use it to get card data card data from one Wekan and then set to other Wekan:
https://wekan.github.io/api/v3.46/#get_board_list_card

**Comment by xet7** [comment]
Related other sync to Trello #1322 and sync to Jira (maybe some issue number somewhere).

**Comment by xet7** [comment]
Moved to #1322
