### ISSUE TITLE
Issue: Moving a card between lists changes swimlane?

### ISSUE THREAD

**Issue by johnxliu** [wekan/wekan#2757]
Consider we have two lists "1" and "2" and two swimlanes "A" and "B". If I am in "Lists" view and have a card in swimlane "B" and move it from list "1" to "2", it will automatically change to swimlane "A".
Is this expected behavior? Is there a workaround so it doesn't switch swimlane? I couldn't make any rule to keep labels in the same swimlane.

I didn't setup the environment, so I'm not sure how it's configured.

**Comment by andreasgrill** [comment]
We are also experiencing a similar issue when we use the Lists view and change the list of a ticket.

**Comment by hickorysb** [comment]
I know this is really old, but I did solve this in issue #3107 in my comment.
