### ISSUE TITLE
Search results display

### ISSUE THREAD

**Issue by nata-g** [wekan/wekan#276]
The way the search results are displayed when there are many results,  seems to be broken. Maybe having a left aligned sequential one column display would do the trick...

![image](https://cloud.githubusercontent.com/assets/203255/9673097/8338dd64-5255-11e5-83e0-ef9745aedb25.png)

**Comment by mquandalle** [comment]
Fixed in 82b322777852b0f7b3f93295a0dbcc0c238bd20d
