### ISSUE TITLE
Checklist items - string problem

### ISSUE THREAD

**Issue by jhgovsi** [wekan/wekan#2760]
## Issue

**Server Setup Information**:

* Operating System: Windows
* Deployment Method: docker
* Node Version: 8.16.1
* MongoDB Version: 4.0.12
* What webbrowser version are you using? Chrome, Firefox
* Wekan Version 3.49.0

**Problem description**:
Incorrect naming appears if I create 2 checklist items within an issue and name them "1. faza" and "2. faza"

**How to recreate a problem?**
- Step 1) create new card
- Step 2) add checklist to a card
- Step 3) name a checklist 
- Step 4) add first item to a checklist, name it "1. faza"
- Step 5) add second item to a checklist, name it "2. faza"

**Result:** 
Both checklist items will be seen as "1. faza"

![image](https://user-images.githubusercontent.com/55527952/67365949-e21ae100-f572-11e9-91e3-5a4ddd4796bf.png)

**Expected result:**
Each checklist items should be seen differently ("1. faza" and "2. faza")

![image](https://user-images.githubusercontent.com/55527952/67366261-6cfbdb80-f573-11e9-96a7-5e3663476789.png)

**Comment by xet7** [comment]
There is a workaround at similar issue #2696

**Comment by xet7** [comment]
Moved to #2696
