### ISSUE TITLE
Use multi-stage builds in Docker

### ISSUE THREAD

**Issue by GavinLilly** [wekan/wekan#2762]
## Issue

**Server Setup Information**:

n/a

**Problem description**:
This is not a problem, more of a feature suggestion. Docker has the capability of doing multi-stage builds meaning you can benefit from the layer caching of using numerous `RUN` commands while also keeping a small distributable docker image. You do all the building in 1 stage then copy the final package to a small distributable stage.

https://docs.docker.com/develop/develop-images/multistage-build/

I believe this would benefit Wekan as there is a lot of steps to be done to build Wekan into a usable state and if one step fails then you need to perform all those steps again after fixing the issue. Additionally this means having to perform cleanup at the end of the build. By using multi-stage builds, that cleanup is no longer required (you don't need to cleanup something that won't ship). Using multi-stage build will result in Wekan docker building being quicker.

I'm willing to work on moving to a multi-stage build architecture but I wanted to highlight it here for the greater community

**Comment by xet7** [comment]
@GavinLilly 

Yes you are welcome to submit pull request for multistage docker build.

Someone else also tried to add multistage build about a year ago, but he did not submit pull request.

**Comment by xet7** [comment]
@GavinLilly 

Any progress on multi-stage builds?

**Comment by GavinLilly** [comment]
Sorry, I'd completely forgotten about this. I'll try and take a look this weekend

**Comment by xet7** [comment]
@GavinLilly 

Thanks! :)
