### ISSUE TITLE
On "All Boards" under some Users "Move to Archive" and "Dupicate Board" symbols will not appear

### ISSUE THREAD

**Issue by chirrut2** [wekan/wekan#2765]
## Issue

On "All Boards" under some Users "Move to Archive" and "Dupicate Board" symbols will not appear

Normal behavior:
![image](https://user-images.githubusercontent.com/50633042/67617177-c9affe00-f7e0-11e9-889e-2e841225e236.png)

Some other users (not all..):
![image](https://user-images.githubusercontent.com/50633042/67617192-f106cb00-f7e0-11e9-8a69-1923d0836796.png)

Browsers will not proivide any issues. Behavior seams to be not browser dependend. Testet under IE, Edge, Firefox, Chrome, Opera, Vivalidi

**Server Setup Information**:
Server: Ubuntu 18.04 
Version: 3.49 via snap

**Comment by xet7** [comment]
Yes, see #2599 

Problem is, it's too easy to hit those buttons by accident. So I'm thinking, could it improved somehow? For example, should each board have some popup menu?

**Comment by xet7** [comment]
Another way would be to have checkbox at each board, and then top bar options to Star/Clone/Archive all selected boards.

**Comment by BigHeadLittleArms** [comment]
Hi - By removing the buttons, the DUPLICATE BOARD function is no longer available. This is not mitigated by the suggestion on the previous ticket to copy each card, as the COPY CARD function is not working. When you select DONE the button appears to be clicked, but nothing happens. 

Sorry if this isn't the right spot for this - I'm new. Thanks!

**Comment by xet7** [comment]
@BigHeadLittleArms 

What Copy Card function does not work? What Done button? Screenshot? What Wekan version?

**Comment by BigHeadLittleArms** [comment]
Not sure what happened, but its working now. Good chance it was user error on my part, followed by rage-help-solicitation. I withdraw the comment, my apologies. Thanks
