### ISSUE TITLE
Disable text editor for comments

### ISSUE THREAD

**Issue by fmeehan** [wekan/wekan#2766]
## issue

Hi, 

Is it possible to disable the rich text editor in comments? 

For one, when pasting text, on Mac OSX 10.15, Chrome 77.0.3685.120 and Safari 13.0.2, blank lines are being introduced. 

It would be great to use markdown everywhere.

Thanks in advance,

François

**Comment by xet7** [comment]
## Snap
```
sudo snap set wekan richer-card-comment-editor='false'
```
## Docker
```
- RICHER_CARD_COMMENT_EDITOR=false 
```
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L241

**Comment by fmeehan** [comment]
Excellent!
Best regards!
*François Meehan*
fmeehan@cedvalinfo.com
514 816-5869
