### ISSUE TITLE
Extremely hard (almost impossible) to Use Wekan on Android with more than 6 columns

### ISSUE THREAD

**Issue by hacker-h** [wekan/wekan#2767]
## Issue

**Server Setup Information**:
Docker Compose with the latest compose file
latest docker image of quay.io/wekan/wekan

**Problem description**:

When using a board with more than 6 colums I want to be able to scroll, however this results in instantly dragging the column, which I do not want to. However when I clicked on the column and get redirected to the overview of many cards scrolling works absolutely fine.
As a workaround I can drag a column to the end of the display and hereby scroll with it, however this completely mixes up my columns.

**Comment by xet7** [comment]
In progress at #2081
