### ISSUE TITLE
Notification Behind Proxy Server Internet

### ISSUE THREAD

**Issue by arradoq** [wekan/wekan#2768]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: Newest
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Windows 8
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): source 
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

I've successfully deploy wekan on local network, and use it freely until I realized, the email notification thing just doesn't work. At first, I thought it was firewall problems but IT staff already non activate it. So it may be related to Proxy server, as Internet is restricted through it. Is there any way to go pass this proxy setting or any idea to make mail notification works?

**Comment by xet7** [comment]
@arradoq 

Did you setup SMTP email sending settings?
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by arradoq** [comment]
Well I use internal setting via admin panel and it works well when tested using normal internet settings, but when implemented on my office pc which only connected via proxy server it suddenly cannot send any mail

**Comment by xet7** [comment]
Email settings need to be set at both Admin Panel and docker-compose.yml .

You could try add to docker-compose.yml these settings:
```
- HTTP_PROXY=http://192....
- HTTPS_PROXY=https://192....
```
That way you could at least get Outgoing Webhook from board or Global Webhook from Admin Panel  going to some chat:
https://github.com/wekan/wekan/wiki/Outgoing-Webhook-to-Discord

Those docker settings are mentioned here:
https://docs.docker.com/network/proxy/

But I don't know does your office pc have access to any SMTP server that is at local network, or is SMTP traffic denied by some firewall.

Docker is one way to run Wekan on Windows. Another way is to run bundle from source:
https://github.com/wekan/wekan/wiki/Windows

**Comment by arradoq** [comment]
At this time I run bundle from source, so maybe i can get some insight on this case, firewall is disabled so maybe this proxy things is what actually block smtp
