### ISSUE TITLE
New List item moved from right to left

### ISSUE THREAD

**Issue by derbolle** [wekan/wekan#2772]
After our Wekan Update from Version 3.44 to 3.49 we noticed that the New-List Field moved from the right all the way to the left. 

After reverting back to Wekan 3.44 the Behaviour switched back to like it was before

**Server Setup Information**:

* Did you test in newest Wekan?: yes

* Wekan version: 3.49

* Operating System: Docker Swarm on Debian 10

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker Swarm with docker-compose file

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik reverse Proxy

* Node Version: 8.16

Mongo Version 4.0.11

* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox 69 and Chrome

**Comment by jhgovsi** [comment]
Can confirm the same!

**Comment by xet7** [comment]
@derbolle 

There is no option. I will try to revert this.
