### ISSUE TITLE
Card comments history limited to 20

### ISSUE THREAD

**Issue by shenannoel** [wekan/wekan#2775]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: yes, v3.49
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?: yes
* Wekan version: v3.49
* If this is about old version of Wekan, what upgrade problem you have?: none
* Operating System: Debian GNU/Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: v8.16.1
* MongoDB Version: v3.2.21
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? chrome v78.0.3904.70

**Problem description**:
Only 20 comments are visible on card's comment history. Once the number of comments exceed 20, oldest comments dissappear. 

In this test card i added 30 comments with numbers 1-30

![image](https://user-images.githubusercontent.com/47319128/67931897-d7062780-fbe8-11e9-908a-072e0b2749d6.png)

but here you can see the comments before number 13 has disappeared:

![image](https://user-images.githubusercontent.com/47319128/67931960-fdc45e00-fbe8-11e9-8660-249f84f34058.png)

**Comment by xet7** [comment]
Yes, I will fix it after I get some other urgent work finished.

Moved #2377
