### ISSUE TITLE
The filter screen only shows the Admin and not the other members to filter

### ISSUE THREAD

**Issue by nata-g** [wekan/wekan#278]
So in this test there are total of 3 members including Admin which is TestAccount13, but in the filter screen only the admin shows and not the other members to filter on

![image](https://cloud.githubusercontent.com/assets/203255/9673551/3839e88a-525a-11e5-8c27-71d6714def9b.png)

Also, when the filter menu item is selected from the members section in the side bar, that member is not displayed on the filter screen, although the results does get filtered.

![image](https://cloud.githubusercontent.com/assets/203255/9673586/ac9c079e-525a-11e5-84c0-9e62e6a28bf5.png)

![image](https://cloud.githubusercontent.com/assets/203255/9673606/d8e6af52-525a-11e5-9d99-c7a8adc6d77d.png)

**Comment by mquandalle** [comment]
I was not able to reproduce this one.

**Comment by nata-g** [comment]
:+1:  yep it is working ...
