### ISSUE TITLE
Generating Wekan OpenAPI docs fails with Python error

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2781]
OpenAPI was added at https://github.com/wekan/wekan/pull/1965 , but now it shows error:
```
~/repos/wekan$ ./releases/rebuild-docs.sh
Traceback (most recent call last):
  File "./openapi/generate_openapi.py", line 915, in <module>
    main()
  File "./openapi/generate_openapi.py", line 910, in main
    schemas, entry_points = parse_schemas(args.dir)
  File "./openapi/generate_openapi.py", line 700, in parse_schemas
    schema = Schemas(statement, jsdocs)
  File "./openapi/generate_openapi.py", line 588, in __init__
    self.fields = [SchemaProperty(p, self) for p in content.properties]
  File "./openapi/generate_openapi.py", line 588, in <listcomp>
    self.fields = [SchemaProperty(p, self) for p in content.properties]
  File "./openapi/generate_openapi.py", line 461, in __init__
    self.enum = [e.value.lower() for e in p.value.elements]
TypeError: 'NoneType' object is not iterable
✓ Read source file!
Failed to parse the source OpenAPI document
```
@bentiss

Can you fix it? I am unable to build new Wekan API docs to https://wekan.github.io/api/

**Comment by xet7** [comment]
This happened when I added new API for Assignee field like Jira #2452  on Ubuntu 19.10 64bit.
https://github.com/wekan/wekan/blob/master/models/cards.js#L1993
https://github.com/wekan/wekan/blob/master/models/cards.js#L2079

That Assignee feature mostly works now and is at master branch, I will add missing Assignee avatar to add Assignee popup, and missing popup title. REST API should also work but I have note tested it yet.

**Comment by xet7** [comment]
@bentiss 

Also, do you know is there a better repo for esprima-python #2545 ?

**Comment by bentiss** [comment]
> Can you fix it? I am unable to build new Wekan API docs to https://wekan.github.io/api/

Should be good now with PR #2783 

> Also, do you know is there a better repo for esprima-python #2545 ?

Yeah, sorry for not answering earlier. I saw this float past, but I was enjoying time off with my family and completely forgot about it later.
I submitted a PR (https://github.com/Kronuz/esprima-python/pull/11) to the tree, and I hope that this was not an intentional choice to inject a virus in a lib.
