### ISSUE TITLE
Wekan: Card Properties Pane Not available

### ISSUE THREAD

**Issue by lambis7** [wekan/wekan#2784]
**Server Setup Information**:

Wekan Version | 3.49.0

Meteor version | 1.8.1

Node version | 8.16.1

MongoDB version | 3.2.22

MongoDB storage engine | wiredTiger
MongoDB Oplog enabled

OS Type | Linux (Ubuntu Server 18.04)

OS Arch | x64

OS Release | 4.15.0-66-generic

OS Total Memory | 4  GB

OS Free Memory | 657  MB

OS CPU Count | 1

Installation Method: via Snap

**Problem description**:
- I have a problem while i select a Card and i want to see its properties pane. I get a Not Found URL error. I am running Apache 2.4.41
The Log information from sudo snap logs wekan.wekan is:

> 2019-10-30T15:48:11Z wekan.wekan[882]:     at Subscription.subscriptionProto.(anonymous function) [as removed] (packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:87:30)
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at runWithEnvironment (packages/meteor.js:1286:24)
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at packages/meteor.js:1299:14
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at packages/mongo/observe_multiplex.js:182:30
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at Array.forEach (<anonymous>)
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at Function._.each._.forEach (packages/underscore.js:139:11)
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at Object.task (packages/mongo/observe_multiplex.js:176:9)
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
> 2019-10-30T15:48:11Z wekan.wekan[882]:     at packages/meteor.js:894:12

**Comment by xet7** [comment]
Did you set root-url?
https://github.com/wekan/wekan/wiki/Settings

**Comment by xet7** [comment]
What does this command output?
```
sudo snap list
```

**Comment by xet7** [comment]
I presume you got it installed.

**Comment by lambis7** [comment]
@xet7 Thanks for your help i entered the root-url and everything works just fine!
