### ISSUE TITLE
Unable to create new board with no-admin users

### ISSUE THREAD

**Issue by norangebit** [wekan/wekan#2786]
## Unable to create new board with no-admin users

Add these issues to elsewhere:

**Server Setup Information**:
- Wekan Version: 3.49.0
- Meteor version: 1.8.1
- Node version: 8.16.1
- MongoDB version: 4.2.0

**Problem description**:

Throught graphic interface an user can create a new board, but throught API only admin user can do it. The response to a normal user is 403 forbidden. Is that an usual behavoiur?

**Comment by xet7** [comment]
Yes. Not all of User API is implemented yet.

Admin API has access to all of data.

**Comment by xet7** [comment]
In Wekan code at this repo, REST API code is at `wekan/models/*.js`, anyone can read that code and add permissions for users where those permissions do not exist yet, and submit pull requests for those.

Generated Wekan API documentation is here:
https://wekan.github.io/api/

And at Wekan GitHub wiki.

**Comment by norangebit** [comment]
I checked the code, and I saw that the [authentication.js](https://github.com/wekan/wekan/blob/fe42eb1d014c06dfed8114a00b29eac9b08baec6/server/authentication.js) is responsable for authentication.
In the case of the interface for creating a new board is called the function [`Authentication.checkUserId()`](https://github.com/wekan/wekan/blob/fe42eb1d014c06dfed8114a00b29eac9b08baec6/models/boards.js#L1253), whose name, in my opinion, can create confusion since it does more than it says. In fact it in addition to checking that the user exists also verifies that it is an admin. 
If I wanted to change the code and send you a pull request, I have to change the function `Authentication.checkUserId()` and make it accept an optional parameter to control the role. Or replace this function with the `Authentication.checkAdminOrCondition()` function?

**Comment by xet7** [comment]
For user, you add these checks, an test them:
1) User is logged into API
2) User is member of board. User can not list any boards that user is not member of. Admin can list all boards.
3) Similarly, user has only access to his own data, profile, etc, and can not change any other user's data.
4) But, probably user can add some other user to card, depending on user role.

Users have these roles:
https://github.com/wekan/wekan/wiki/REST-API-Role

As summary, it's good to check for role and allow according to that. Maybe that could be optional parameter or new function, depends what would make some sense.

Thanks!

**Comment by xet7** [comment]
I think somewhere was feature request for option so that user would not be able to delete any data, only archive and unarchive, there could be some related option at Admun Panel.
