### ISSUE TITLE
Broken images until pod killed

### ISSUE THREAD

**Issue by alkemyst** [wekan/wekan#2787]
## Issue
At random times the images are not displayed any more in the interface, including attachments and user icons.
If I kill the wekan pod (not the database one) then the correct behaviour recovers.

**Server Setup Information**:

| Wekan Version | 3.49.0 |
|------------------------|-----------------------------------------|
| Meteor version | 1.8.1 |
| Node version | 8.16.1 |
| MongoDB version | 3.2.21 |
| MongoDB storage engine | wiredTiger |
| MongoDB Oplog enabled |  |
| OS Type | Linux |
| OS Platform | Linux |
| OS Arch | x64 |
| OS Release | 3.10.0-1062.1.2.el7.x86_64 |
| OS Uptime | 13 days, 1 hours, 59 minutes, 8 seconds |
| OS Load Average | 3.08, 2.42, 2.28 |
| OS Total Memory | 29  GB |
| OS Free Memory | 5  GB |
| OS CPU Count | 10 |

Browser:
Firefox 70.0 (64-bit) on Ubuntu 19.04

**Problem description**:
The logs do not show anything wrong when the broken image is displayed.
For the behaviour see attached pictures:

**Before pod restart**
![Screenshot_2019-11-07 Test - the board](https://user-images.githubusercontent.com/584822/68385238-96169180-0159-11ea-8924-8c3b2782d138.png)

**After pod restart: please not that the user icon is now restored**
Usually pictures show up correctly after the restart. This one picture was not, and I was surprised, but it might be because I uploaded it while the "broken image" behaviour was happening
![Screenshot_2019-11-07 Test - the board(1)](https://user-images.githubusercontent.com/584822/68385264-a62e7100-0159-11ea-95a4-8bd72ce1531a.png)

**After deleting and re-uploading the same picture**
![Screenshot_2019-11-07 Test - the board(2)](https://user-images.githubusercontent.com/584822/68385275-b2b2c980-0159-11ea-9b7a-407e30071ca8.png)

**Comment by xet7** [comment]
Instead of MongoDB database, you can also store files to filesystem https://github.com/wekan/wekan/issues/2635#issuecomment-547177602

The actual final fix will be when attachment code is changed https://github.com/wekan/wekan/issues/2759

Moved to #2759
