### ISSUE TITLE
Worker role,  that can move and comment cards (a worker rule) without the ability to edit/create/delete cards

### ISSUE THREAD

**Issue by nickbe** [wekan/wekan#2788]
Just that. A typical worker should not have the right to edit/delete any cards, but of course he/she should make changes to the status. Which means being able to move the card between columns.

**Comment by xet7** [comment]
You are the first one that has asked for that kind of role. I don't know everybody's use cases.

Anyone can add new role to Wekan with pull request. So you can [make fork of Wekan, add changes, git commit, git push, at GitHub website click create pull request](https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm#3-fork-wekan-and-clone-your-fork).

For example in roles issue https://github.com/wekan/wekan/issues/1861 , I added "No comments" role this way https://github.com/wekan/wekan/commit/77efcf71376d3da6c19ad1a4910567263e83c0ca . So there is ready-made example already.

Role docs are [at wiki](https://github.com/wekan/wekan/wiki/REST-API-Role).

Before using Role API, you need to get Bearer token by [logging in as Admin user as form data](https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data).

**Comment by nickbe** [comment]
Well I'm not experienced with wekans' programming so forking wouldn't make much sense for me.
But the role seems to obvious that I'm astonished no one asked for it before.

If you have work team and you're the team leader, then you're also the one who creates the cards, assigns them to the team members and who is monitoring their progress.

You don't want them to move the cards - or delete them - because as a team leader it's yout reposibility to decide when a card has to be moved, archived and so on.....

Therefore you would need a worker role. And a worker would only be able to see is cards and comment then.

**Comment by xet7** [comment]
I can implement worker role if someone pays 250 euro for my coding time at:
https://wekan.team/commercial-support/

**Comment by nickbe** [comment]
**Ok, done - here's the sumary of "worker role":**

**Can**: move cards, can assign himself to card, can comment, 
**Cannot**: anything else including revoke card, change settings, create/delete/edit cards/tags and so on...

**Comment by nickbe** [comment]
Hi Lauri,
might I have a quick status update?

**Comment by xet7** [comment]
@nickbe 

Currently I have [many features on my todo list](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) so I presume this worker rule feature will be ready sometime at this month December.

**Comment by nickbe** [comment]
Ok thanks. I'll inform my team.

**Comment by xet7** [comment]
I did add worker role, and then remove it, because there was some bug when saving card. I'm currently in progress of fixing it.

If you like, you can test in-progress worker role on these docker tags, but I recommend waiting when I have fixed that card save bug.
- `quay.io/wekan/wekan:v3.59`
- `wekanteam/wekan:v3.59`

You will see on ChangeLog when I get it added back:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

**Comment by nickbe** [comment]
Happy new year Lauri 🍾 

We'll wait until the finished version is live and updatable via snap on our server,
Thanks for reporting back.
