### ISSUE TITLE
Card detail animation behavior does not work when entering a different list 

### ISSUE THREAD

**Issue by shekar73** [wekan/wekan#279]
In this test I opened card detail page and then started working on new list, but the previous card detail animation does not close unless i manually close it. I am assuming the behavior should be consistent as when you click at any other place the card detail page closes since now the focus has shifted.

![image](https://cloud.githubusercontent.com/assets/203255/9673857/a8d2aa34-525d-11e5-9a23-ca7e771530ae.png)

**Comment by mquandalle** [comment]
I'm not sure about this one. One of the idea of this panel is that you can still interact with the board mini-cards while viewing the opened cards. It works for things like drag and drop for instance, and in the future you may be able to have more interaction between the opened card and the rest of the board (eg, transform a subtask into a card by drag&drop, define some dependencies betweens cards, etc). Clicking on the board background is considered an explicit demand to close the current card.

I may re-consider this as part of a much larger navigation re-factoring in a future release.

**Comment by nata-g** [comment]
:+1:  :+1:
