### ISSUE TITLE
Printable version of a board

### ISSUE THREAD

**Issue by kalak-sudo** [wekan/wekan#2794]
Hi everyone!

I am using Wekan for my working schedule and I found that printing my board is a mess. 

Is there any way to have a printable version of the board? It would have huge implications in many uses the boards can have :)

**Comment by xet7** [comment]
Yes. You can hold `Ctrl` and use mouse scroll to zoom out so much that all cards are visible. Then you can take screenshot with `PrintScreen` key and paste it to image editor like Paint, Gimp etc.

**Comment by kalak-sudo** [comment]
Ok, thats a nice solution, but I meant a "Printable version" natively in the app :)

**Comment by xet7** [comment]
@kalak-sudo 

How that would be any different?

**Comment by kalak-sudo** [comment]
The idea is something like: 

[https://www.printfriendly.com/](https://www.printfriendly.com/)

Where it automatically removes "rubbish", such as menus or options that aren't relevant in a printed board.

**Comment by xet7** [comment]
If you export board to JSON, that JSON file has all board cards, attachments base64 encoded, etc. With some code, you could generate any kind of PDF from that.

That also raises some questions:
- How in that PDF version everything would fit on paper, or be nicely formatted to multiple pages?
- Should contents of cards be in PDF also somehow?
- What do you mean with "huge implications" ?
- Or do you mean CSV export #395 ?
- Is this so important feature that you would pay developing it using my [Commercial Support](https://wekan.team/commercial-support/) ?

**Comment by xet7** [comment]
In that printfriendly, it would mainly be that in Wekan menus and options would not be printed with normal print option of browser. Making those changes sure is easier than adding some PDF generation code.

**Comment by xet7** [comment]
Actually, I'm not yet sure about the "easier" part, I will look how time consuming it would be to make it work.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
