### ISSUE TITLE
MongoError: WiredTigerIndex::insert: key too large to index

### ISSUE THREAD

**Issue by ssendev** [wekan/wekan#2798]
## Issue

**Server Setup Information**:

* Wekan version: `wekanteam/wekan:latest`. docker hub says `:3.51` but `:latest` is a few hours newer and has a different hash (a08feb496ab2) so i am not sure
* If this is about old version of Wekan, what upgrade problem you have?: can't start
* Operating System: ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker  
* MongoDB Version: `mongo:3.2.19`

**Problem description**:
```
wekan-app  | MongoError: WiredTigerIndex::insert: key too large to index, failing  1054 { : "some long string ..." }
wekan-app  |     at Function.create (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:43:12)
wekan-app  |     at db.s.topology.insert (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/db_ops.js:329:54)
wekan-app  |     at /build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
wekan-app  |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
wekan-app  |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
wekan-app  | Presence started serverId=LvcGr2JRsz7Em2Kis
wekan-app  | Meteor APM: completed instrumenting the app
wekan-app  | /build/programs/server/node_modules/fibers/future.js:313
wekan-app  | 						throw(ex);
wekan-app  | 			
```

I read that mongo 4.2 relaxed the index size so i upgraded mongodb to 4.2 and wekan started but i am not sure if it will cause problems down the line as the docker-compose.yml in this repo has `mongo:4.0.12` but a comment says compatible with mongo 4.x

or is the issue that i shouldn't have run the newer docker with the old mongodb and the dropindex in the mongo 3 ->4 upgrade instructions fixed the issue?

**Comment by xet7** [comment]
First you need to do mongodump from old MongoDB version, and then mongorestore to new MongoDB version. If you get errors when doing mongorestore, you could try with option `--noIndexRestore`.
https://github.com/wekan/wekan/wiki/Backup
