### ISSUE TITLE
Upgrade Wekan - Source Installed - Documentation

### ISSUE THREAD

**Issue by compumatter** [wekan/wekan#2799]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:
We are running 18.04 Ubuntu and have installed the latest version of Wekan, Mongodb etc **as of about 4 months ago**. 
Versions: 
Mongodb 4.01
Node: 8.16.1
Wekan: can't figure out how to get that.
Web Server: Nginx
 
Installation Method: from source / bundle 

Everything works perfectly

I am trying to find (or create) documentation of the step by step process required to upgrade Wekan to the latest stable source version. Happy to pay for someone to itemize these steps.

**Comment by xet7** [comment]
@compumatter 

[Bundle install is here](https://github.com/wekan/wekan/wiki/Platforms#not-exposed-to-internet-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures-no-automatic-updates-no-sandboxing).

Does that work for you, or do you get some errors ?
