### ISSUE TITLE
Feature request: read only boards

### ISSUE THREAD

**Issue by tamasberesoebb** [wekan/wekan#2801]
## Issue

I've just started using Wekan, and it seems to me, that there is no real "ready only" permission for users. Why?
Comment only permission comes very close to it, but this user can still comment which is weird.

My use case:
Public Kanban board, where everyone who has access to a room, can view the board on a giant touch capable monitor. I want to only give read only access to the user which is logged in on that pc.

**Comment by xet7** [comment]
I can implement read only role if someone pays 250 euro for my coding time at:
https://wekan.team/commercial-support/

**Comment by xet7** [comment]
Moved to #2876
