### ISSUE TITLE
Adding comments as a member to a board.

### ISSUE THREAD

**Issue by nata-g** [wekan/wekan#281]
Test Description: As a member of the private Board, I should add comments to the card in the card detail page with 'normal' permission. 

Result: Could not add any comment as member to the Board.

In the example below TestAccount11 is the member of the board but there is not comment fom.  only 'admin' (testaccount13) is allowed to add comments

![image](https://cloud.githubusercontent.com/assets/203255/9674624/a5148bb0-5267-11e5-8673-59904d801bed.png)

**Comment by mquandalle** [comment]
Hum I can't reproduce this bug. It seems to me that the board permissions are in a weird state (maybe due to some bugs in a previous version?).

Could you try to open your browser JavaScript console and give me the output of the following command:

```js
JSON.stringify(Boards.findOne(Session.get('currentBoard')).members)
```

**Comment by nata-g** [comment]
@mquandalle I was trying to test this but the wekan instance at meteor.com is crashing.

**Comment by nata-g** [comment]
I tested this on the local instance and it seems to be working now. :+1:
