### ISSUE TITLE
Select all Cards -> Move option not working

### ISSUE THREAD

**Issue by ngru** [wekan/wekan#2810]
## Issue

When selecting all cards of a column, the option to move them to a different column does nothing 
(other options, like setting the label color works)

**Comment by Katzkolini** [comment]
I can't move cards or create a new one. I only can change the existing one

**Comment by podlisk** [comment]
I can confirm, we also cannot move or create new cards. Would it be wise to rollback to previous version? If so, how can we do that?

**Comment by Katzkolini** [comment]
actually the drag and drop it's not working. we can move from the menu of each card and we do the new one from the copy option

**Comment by xet7** [comment]
Try Wekan v3.55
