### ISSUE TITLE
More and better testing before deploying new features?

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2811]
We also had problems after updating the version 3.53.0 with the new feature "list order" -> #2800. Some lists couldn't be moved. We had some fun time with this non-feature at the office, because we where childishly joking around trying to move lists in their proper position, with no avail. We tried to find workarounds and lost some time with it, seeing, it is just a bug, not the users fault. (We also tried turning it off and on again.) #Irony 

On the serious side of things, I have the feeling, that new features of Wekan should be better tested in a beta-version, maybe the community should help with testing. I would be ready to have a second install for testing with our data, and then give early feedback, before buggy new features are spread around and kill our work time in the productive installation. 

Maybe I shouldn't be an early adopter, but I hope with every update, that some old bugs will go away too. On the other side I understand @xet7 and we are all happy, that @whowillcare gives us new cool features, that we awaited so long. Maybe both can tell us ways, we as a community can help to create a stable tool with all the cool new features at the same time?

**Comment by xet7** [comment]
@saschafoerster 

Wekan v3.54 released, ChangeLog:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

Please test.

Snap has automatic update, or you can update manually:
```
sudo snap refresh
```
You see at https://snapcraft.io/wekan what are current versions.

To change to edge:
```
sudo snap refresh wekan --edge --amend
```
And back to stable:
```
sudo snap refresh wekan --stable --amend
```

**Comment by saschafoerster** [comment]
For docker I was not sure how to create a test-environment and the docker-images are not on the newest version yet (takes some hours), so I tried and cloned the repository locally with git in a wekan-dev-folder and then changed the building in docker-compose.yml by replacing "image" with a link to the "build" (from sources) by a dockerfile in the same folder. So, all the testing options open, I can even test code-changes locally in my usually used docker-environment. 

```
  wekan:
    #image: quay.io/wekan/wekan
    build: .
    container_name: wekan-app
 ...
```

**Comment by xet7** [comment]
@saschafoerster 

For building, uncomment these lines:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L132-L142

And then start with:
```
docker-compose up -d --build
```
Then browse to http://localhost

To delete containers, do:
```
docker-compose down
docker rm wekan-app wekan-db
```

**Comment by xet7** [comment]
About this newest Wekan version, I think that when user is logged in, there is no need to use cookies, using database would make immediate changes in web UI. Currently logged in user has delays in settings, maybe needs to reload webbrowser, etc.

When user is not logged in, then cookies could be used.

**Comment by saschafoerster** [comment]
@xet7 Docker seems not to get a fresh package either from Quay.io, nor from Docker Hub for version v3.54.
