### ISSUE TITLE
New release duplicates cards across swimlanes

### ISSUE THREAD

**Issue by JHSheridan** [wekan/wekan#2812]
## Issue

**Server Setup Information**:
Using the newest version of wekan via snap

**Problem description**:
Any of my wekan boards with swimlanes have duplicated all issues across all swimlanes. For instance, if I had an issue called "Call Mom" in a swimlane labeled personal in a column labeled "Today", that card is now duplicated in the swimlane called "Work" below it. When I select the card in either swimlane, it opens up it's menu in BOTH swimlanes. It also works vice versa as in all my cards in the "Work" swimlane it now appears in "Personal". When I click on any cards or select them with multiselect, it selects them in both swimlanes, so it's like the cards are linked together somehow.

I'm also unable to add any new cards to any list.

I see these issues in both Firefox and Chrome in linux.

**Comment by somebuddy87** [comment]
same here!

duplicates and unable to add new cards

**Comment by DerFireWal** [comment]
Also unable to add new cards but can't reproduce the duplication issue.
Running wekan 3.54 on snapd 2.39.2-1.el7.
Using Chrome 78 on Windows. Also tested with Firefox 68.2.

**Comment by mtearle** [comment]
I'm seeing the duplicated swimlanes as well.   

mtearle@host:~$ snap list
Name   Version    Rev   Tracking  Publisher   Notes
core   16-2.42.1  8039  stable    canonical✓  core
wekan  3.54       669   stable    xet7        -

mtearle@host:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by betullam** [comment]
I can confirm the same behaviour on my System:

- Ubuntu Server 16.04.6 LTS
- Newest Wekan installed via Snap (3.54, Rev 669)
- Tested on Firefox and Chrome

**Comment by matrixes** [comment]
I can replicate this issue to the letter. It's unfortunately rendered Wekan impossible to use for our team.

**Comment by xet7** [comment]
Try Wekan v3.55

**Comment by JHSheridan** [comment]
This resolved things for me. Thanks for such a quick fix. This is an invaluable piece of software for me!
