### ISSUE TITLE
It is not possible to create comments in cards in the new release 3.54

### ISSUE THREAD

**Issue by kurgenal** [wekan/wekan#2813]
It is not possible to create comments in cards in the new release.
...
Name   Version    Rev   Tracking  Publisher   Notes
core   16-2.42.1  8039  stable    canonical✓  core
wekan  3.54       669   stable    xet7        -

**Comment by jhgovsi** [comment]
I can confirm the same for yesterday's commit no. 34bfb09 (over the dockerhub).

**Comment by Loutre-LNO** [comment]
Same behavior

**Comment by lewie** [comment]
...me too.

**Comment by matrixes** [comment]
Can't add or edit comments. The editor is collapsed to a thin line and the Comment button does nothing when clicking it.

**Comment by xet7** [comment]
Try Wekan v3.55
