### ISSUE TITLE
Unable to create cards in 3.54

### ISSUE THREAD

**Issue by virtualcharlotte** [wekan/wekan#2814]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 3.54
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 8.16.2
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?: Chrome

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
![image](https://i.boring.host/1G88bUwC.gif)

- *Explain steps how to reproduce*: Add a card
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
`insert failed: Error: Swimlane id is required
    at r (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:95:2748)
    at e.Collection.i (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:95:2586)
    at e.Collection.c.Collection.<computed> [as insert] (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:95:5412)
    at e.Collection.<anonymous> (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:117:4748)
    at e.Collection.r.<computed> [as insert] (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:117:1754)
    at n.addCard (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:341:310822)
    at https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:233:6051
    at Object.f._withCurrentView (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:63:23077)
    at https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:233:6012
    at e._withTemplateInstanceFunc (https://board/2805e74edcd06c9ed2cf57d2da74ad2c473490bc.js?meteor_js_resource=true:63:37826) undefined`

^ looks like swimlane ID gets lost somewhere along the line

**Comment by chnliyong** [comment]
The same problem，you can rollback by command `snap revert wekan` to revert the latest upgrade. This is what now I do. @virtualcharlotte

**Comment by cimm** [comment]
Thanks @chnliyong, this worked! Not sure if it's absolutely needed but I would advise to take a dump of the database before reverting (better safe than sorry).

```sh
$ snap stop wekan.wekan
$ mongodump --port 27019
$ snap revert wekan
```

**Comment by spackmat** [comment]
And also unable to move cards with same error in the JS-console. Reverting to 3.53 solves this but now my lists are in another order and I cannot sort them back. To be precise, I can sort them only a weird way: Moving a lane right has no effect (snaps back) and moving it left makes it the first one. With a little Sokoban-skills, I was able to reorder my lanes again. ;)

**Comment by chnliyong** [comment]
> I checked the snap [documentation](https://snapcraft.io/docs/getting-started#heading--revert) and the snap should not automatically update to the current broken version when you revert but it will automatically update if a newer version is released (or if you run `snap refresh` manually).

I temporarily hold the refresh action by this command: `snap set system refresh.hold='9999-12-31T17:22:54+01:00'`

**Comment by vjrj** [comment]
Hi @xet7 are you aware of this with the new release? TIA!

**Comment by nickbe** [comment]
Same here - all cards I added blindly yesterday to a column as usual are gone.
New cards cannot be added - I tried that now.

**Comment by sclerc-chss** [comment]
Same here too...

**Comment by juliensl** [comment]
> Same here - all cards I added blindly yesterday to a column as usual are gone.

Owwww I didn't check that :o 
Could you tell us if they are coming back with the revert version please ? I don't remember what I did on my kanban yesterday x)

**Comment by aldeluis** [comment]
Our Wekan instance stopped working too...

**Comment by drhugobr** [comment]
exact same issue, but if you create a NEW board, it works (some times).

Current existing boards are "frozen" in its state, also cant move cards around.

**Comment by vjrj** [comment]
It seems to me that if you are in the Swimlane view does not fails the card creation, but fails in List view.

**Comment by leejoramo-d51** [comment]
Some problem here. The suggestion to `revert` worked.

**Comment by januzi** [comment]
Obsolete header ALLOW-FROM in the X-Frame-Options is probably leading to problems with the web socket connection. Both things are marked as errors in the browser's console.

**Comment by noesmeteoro** [comment]
Same here. Thanks for the `revert` suggestion!

**Comment by TheMasterFX** [comment]
Same here. No moving or creation of card possible. BUT if I add a swimlane it works (even after removal)

**Comment by shioku** [comment]
> EDIT: After inserting one swimlane on any Board it works for all again (maybe an database issue?)

Can confirm. Added swimlane on one board and removed it and it started to work on all boards.

**Comment by xet7** [comment]
Try Wekan v3.55
