### ISSUE TITLE
Deactivate subtasks by default

### ISSUE THREAD

**Issue by dschori** [wekan/wekan#2815]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
* Wekan version: 3.49.0
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Node Version: 8.16.1
* MongoDB Version: 3.2.21
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome Version 73.0.3683.86 

**Problem description**:
Is there a possibility to deactivate subtask for all users by default for every new created Board?
![subtasks](https://user-images.githubusercontent.com/37111668/69156532-d8d65300-0ae3-11ea-8cb9-6afa0180cad1.png)

**Comment by grazius** [comment]
yes it can be a nice feature

**Comment by xet7** [comment]
Hiding subtasks was added at Wekan v3.74. It's at Board Settings / Card Settings.
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v374-2020-02-05-wekan-release
