### ISSUE TITLE
Can't toggle minicard label text

### ISSUE THREAD

**Issue by nickian** [wekan/wekan#2816]
I'm not able to click on this checkbox to toggle this option. Clicking on it does nothing. The check mark will not show up. Not working in Chrome, Firefox, or Safari. I'm running version 3.54.0.

<img width="229" alt="Screen Shot 2019-11-19 at 2 08 59 PM" src="https://user-images.githubusercontent.com/590678/69186689-42e7fb80-0ad6-11ea-8a60-b1f491b4adf5.png">

**Comment by xet7** [comment]
Try Wekan v3.55

**Comment by nickian** [comment]
Thanks, that did the trick.
