### ISSUE TITLE
Search scrolling not available

### ISSUE THREAD

**Issue by tvilayth** [wekan/wekan#2819]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: **Yes**
* Wekan version: **3.53**
* Operating System: **Debian 9**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **Sandstorm**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **FireFox 70.0.1**

Hello,
I upgraded Wekan from version 3.49 to the current version available on Sandstorm which is 3.53 a couple of days ago. 
Now when searching for a card, when you click on it from the search results field it will go to the corresponding column like normal, but now you can't scroll down the column to the card.
You have to click out of it and scroll down with no cards pulled up.
Before with the card pulled up from the search results it allowed for scrolling down the column.

**Comment by xet7** [comment]
Please make backup of your Sandstorm install and grains, and then try experimental version Wekan v3.55:
https://github.com/wekan/wekan/wiki/Sandstorm#wekan-app

@ocdtrekkie has not yet tested it yet to become official version, but all other reports from Wekan v3.55 say that it works.

**Comment by ocdtrekkie** [comment]
@tvilayth If you try 3.55, can you comment here on how it works for you?

I don't test a lot of Wekan's more advanced features when approving Sandstorm releases, so it's always ideal if someone else is also checking out new versions.

**Comment by tvilayth** [comment]
@ocdtrekkie I tried it out on the experimental version 3.55 and it's behaving like version 3.53

![scroll](https://user-images.githubusercontent.com/48764937/69353158-ed753100-0c32-11ea-9288-79f2e1a863e6.gif)

**Comment by ocdtrekkie** [comment]
@xet7 Can you reopen this issue as it appears to apply to 3.55 as well?

**Comment by xet7** [comment]
@tvilayth 

From that video it seems you don't have mouse pointer at opened card aread, mouse pointer is at right side of card area. Can you move your mouse pointer to the opened card area and try scrolling again with mouse?

**Comment by xet7** [comment]
@tvilayth 

Also please try experimental Sandstorm Wekan v3.56 that improves scrolling with mouse on card.
