### ISSUE TITLE
Even members can assign cards to other members.

### ISSUE THREAD

**Issue by shekar73** [wekan/wekan#282]
Test Description: As a member I should not be assigning other members and edit labels only 'Admin' should assign cards to members and put/edit labels to the cards. 

Result: Members with 'normal' permission are able to assign cards, labels and edit labels . The members can be assigned from the card detail page and not through drag-n-drop feature. 

In the example below TestAccount 11 is the member and TestAccount 13 is the admin

![image](https://cloud.githubusercontent.com/assets/203255/9674698/e27ac90a-5268-11e5-8672-81407c8c01ee.png)

**Comment by ePirat** [comment]
I don't think that a permission model is implemented yet? If this gets implemented there should be a way to allow all board members to assign other members to cards, as I can see that this can be useful on some boards.

**Comment by mquandalle** [comment]
Yes, the current behavior is expected in the current state of things. Allowing members to assign themselves and others to cards is also the default on Trello and something people will expect. This is one other feature request that will get solved by an admin board setting page (like #287).

**Comment by nata-g** [comment]
Maybe having  roles defined in the admin page would get some quick wins to  solve lot of those user permissions issues....

https://atmospherejs.com/alanning/roles

**Comment by nata-g** [comment]
Yeah come to think of it that is true, I can see how allowing members to assign other members can be useful in some cases due to the project needs...

**Comment by mquandalle** [comment]
Cf. #146.

**Comment by xet7** [comment]
Moved to #3022
