### ISSUE TITLE
Where is the spinner template?

### ISSUE THREAD

**Issue by urakagi** [wekan/wekan#2820]
I can see some `+spinner` codes in for example `client/components/cards/attachments.jade`, but I can't find a template named `spinner` and the `+spinner` code has no function (only `spinnerList`).

Is it gone so I need to create a new spinner template?

**Comment by xet7** [comment]
@urakagi

Maybe here, on attachments improvements:
https://github.com/wekan/wekan/pulls?q=is%3Apr+swipebox+is%3Aclosed
