### ISSUE TITLE
configure card one more, error reporting

### ISSUE THREAD

**Issue by kimi-sl** [wekan/wekan#2821]
Wekan Version：3.55.0
configure card one more，TIPS（404）.
URL:http://127.0.0.1/b/QhEjGbRqWDYhQZZRd/test/biaMn8rdmafDed8Yf

**Comment by xet7** [comment]
@kimi-sl 

I don't understand. Do you have screenshot and more detailed explanation?

**Comment by kimi-sl** [comment]
Dear all:
&nbsp; &nbsp; &nbsp; &nbsp; edit card one more

&nbsp; &nbsp; &nbsp; tips





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lauri Ojansivu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 晚上8:25
收件人:&nbsp;"wekan/wekan"<wekan@noreply.github.com&gt;;
抄送:&nbsp;"夜空の熏衣草"<165019474@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wekan/wekan] configure card one more, error reporting (#2821)




@kimi-sl
 
I don't understand. Do you have screenshot and more detailed explanation?

**Comment by xet7** [comment]
How should it work? What should it look like?

**Comment by xet7** [comment]
また、日本語でどのように機能し、どのように見えるかを説明することもできます。

**Comment by xet7** [comment]
見た目が新しい画像を作成し、この画像を添付ファイルとしてこの問題に追加できます。

**Comment by kimi-sl** [comment]
Dear all：
&nbsp; &nbsp; &nbsp; &nbsp; This is old releases,when i click the card one more ，i can edit it. But the new releases(version 3.55),i can not.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lauri Ojansivu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 中午1:39
收件人:&nbsp;"wekan/wekan"<wekan@noreply.github.com&gt;;
抄送:&nbsp;"夜空の熏衣草"<165019474@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wekan/wekan] configure card one more, error reporting (#2821)




見た目が新しい画像を作成し、この画像を添付ファイルとしてこの問題に追加できます。

**Comment by xet7** [comment]
Try newest Wekan.
