### ISSUE TITLE
LDAP Login Configuration

### ISSUE THREAD

**Issue by belmironeto** [wekan/wekan#2822]
Wekan Version: 3.55.0
Installed by: SNAP
**Issue:**
When trying to connect with LDAP User Account I Get the Message: "Must be logged in"

Here are my wekan variables:
![image](https://user-images.githubusercontent.com/57781579/69370557-ef63e200-0c7c-11ea-995b-4317b25a66e4.png)

And this is my wekan error and the log:
[ERROR] InvalidCredentialsError: 80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839

![image](https://user-images.githubusercontent.com/57781579/69370680-3356e700-0c7d-11ea-9dc5-021ea188ca8a.png)

**Comment by xet7** [comment]
Try:
```
sudo snap set wekan ldap-username-field='sAMAccountName'
sudo snap unset wekan ldap-sync-admin-status
```
Then after that, try to login with your email address and password:

**Comment by belmironeto** [comment]
Same error here...

**Comment by sclerc-chss** [comment]
At this time, I don't arrived to get a working LDAP authentication with an Active Directory server ... A test interface (and configuration ? ) in admin panel could be useful :)

**Comment by battosai30** [comment]
I agree, LDAP config is a pain in the .... 
I got mine working but it took a long time as there is a lot of parameters and each time you change one you have to reset all the Snap which is clearly not instant. When I will have everything working (ldap admin & group was still buggy severall months ago) I will try to update the doc as it's completely outdated.

**Comment by belmironeto** [comment]
> I agree, LDAP config is a pain in the ....
> I got mine working but it took a long time as there is a lot of parameters and each time you change one you have to reset all the Snap which is clearly not instant. When I will have everything working (ldap admin & group was still buggy severall months ago) I will try to update the doc as it's completely outdated.

You configured LDAP to comunicate to a Windows Server AD? Could you please put your parameters so I can compare to my?

**Comment by battosai30** [comment]
S

> > I agree, LDAP config is a pain in the ....
> > I got mine working but it took a long time as there is a lot of parameters and each time you change one you have to reset all the Snap which is clearly not instant. When I will have everything working (ldap admin & group was still buggy severall months ago) I will try to update the doc as it's completely outdated.
> 
> You configured LDAP to comunicate to a Windows Server AD? Could you please put your parameters so I can compare to my?

Sorry no, it's an OpenLDAP :s but if it could help, this is my conf : 

```
Key                                    Value
caddy-enabled                          false
default-authentication-method          ldap
ldap-authentication                    true
ldap-authentication-password           ********
ldap-authentication-userdn             cn=admin,dc=*******,dc=lan
ldap-background-sync                   true
ldap-background-sync-import-new-users  true
ldap-background-sync-interval          Every 1 minute
ldap-basedn                            dc=*****,dc=lan
ldap-email-field                       mail
ldap-enable                            true
ldap-fullname-field                    cn
ldap-group-filter-enable               false
ldap-group-filter-id-attribute         cn
ldap-group-filter-objectclass          groupOfUniqueNames
ldap-host                              192.168.100.7
ldap-log-enabled                       false
ldap-login-fallback                    true
ldap-merge-existing-users              true
ldap-port                              389
ldap-sync-admin-groups                 administrator
ldap-user-search-field                 uid
ldap-user-search-filter                (&(objectclass=inetOrgPerson))
ldap-user-search-scope                 sub
ldap-username-field                    uid
port                                   8080
root-url                               https://wekan.*****.fr
```
Group sync was buggy when I made the conf so you can ignore this parameters I guess.

**Comment by shioku** [comment]
This is the configuration (ldap-part) i use with Active Directory.

```
snap set wekan ldap-enable='true'
snap set wekan default-authentication-method='ldap'
snap set wekan ldap-port='389'
snap set wekan ldap-host='<ip>'
snap set wekan ldap-basedn='OU=Domain Users,DC=sub,DC=domain,DC=tld'
snap set wekan ldap-login-fallback='false'
snap set wekan ldap-reconnect='true'
snap set wekan ldap-timeout='10000'
snap set wekan ldap-idle-timeout='10000'
snap set wekan ldap-connect-timeout='10000'
snap set wekan ldap-authentication='true'
snap set wekan ldap-authentication-userdn='CN=LDAP-User,OU=Service Accounts,DC=sub,DC=domain,DC=tld'
snap set wekan ldap-authentication-password='<password>'
snap set wekan ldap-log-enabled='true'
snap set wekan ldap-background-sync='true'
snap set wekan ldap-background-sync-interval='60000'
snap set wekan ldap-background-sync-keep-existant-users-updated='true'
snap set wekan ldap-background-sync-import-new-users='true'
snap set wekan ldap-encryption='false'
snap set wekan ldap-user-search-field='sAMAccountName'
snap set wekan ldap-username-field='sAMAccountName'
snap set wekan ldap-fullname-field='cn'
```

**Comment by xet7** [comment]
LDAP docs moved to https://github.com/wekan/wekan/wiki/LDAP

**Comment by marcioaquilles** [comment]
I haven't been able to set up yet.

**Comment by marcioaquilles** [comment]
Did anyone get it to help me?

**Comment by xet7** [comment]
Please look at various examples to auth/login at right menu of wiki:

https://github.com/wekan/wekan/wiki

**Comment by veloprofz** [comment]
how to turn on the option so that ldap authentication appears in the admin panel?

**Comment by xet7** [comment]
@veloprofz 

https://github.com/wekan/wekan/wiki/LDAP

# Snap

sudo snap set wekan ldap-enable='true'

# Docker

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L488

**Comment by MazeOfFate** [comment]
Maybe too late for you @belmironeto but helpfull for others in the future : LDAP_USER_AUTHENTICATION have to be set to false.
