### ISSUE TITLE
Drag Handles for Checklist and Checklist Items

### ISSUE THREAD

**Issue by mfilser** [wekan/wekan#2824]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?:
Yes, i tested at latest version 3.56

* Wekan version:
3.56

* Operating System:
Linux

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
docker

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
docker reverse proxy: jwilder/nginx-proxy:alpine

* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
PC: FireFox 69.0.1 64-bit, Chromium 71.0.3578.98
Mobile: Chrome 78.0.3905.108

### Problem
As soon as i reduce at PC the Browser-Window to Mobile View i can't drag the checklist-items.
I also can't drag the checklist items when using Wekan at my Mobile.
Furthermore i have the problem at using Wekan at my Mobile that i can just scroll inside the card at the very left side. It also happends that when i want to scroll the checklist is moved up/down by mistake.

### Feature Request
The Drag Handles are very very useful at mobile view. Is it possible to implement Drag Handles also for checklist and checklist-item?

I think as long as Drag Handles are not implemented at checklist and especially checklist item, Wekan is bad to use at mobile devices.

Thank you in advance
Martin

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2081#issuecomment-531700589
