### ISSUE TITLE
Card content closed when checklist element move (Firefox only)

### ISSUE THREAD

**Issue by sclerc-chss** [wekan/wekan#2825]
**Server Setup Information**:

* Did you test in newest Wekan?: yes 
* Wekan version: 3.55.0
* Operating System:Debian 9.9
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: 8.16.2
* MongoDB Version: 3.2.22
* What webbrowser version are you using? bug confirmed on Firefox 68.2.0esr only (no problem on edge 42, Chrome 78)

**Problem description**:
When I move a checklist element with the cursor out of the text, card content is closed sometimes, only in Firefox. This was working fine before some versions.

On the left : Firefox bug
On the right: Edge which works fine
![oaQTt9g5HE](https://user-images.githubusercontent.com/53857862/69418299-b8dca480-0d1a-11ea-89d3-d1940029a1f3.gif)

Thank you.

**Comment by gerroon** [comment]
I can confirm this on FF 71 on Linux 64 build.

**Comment by xet7** [comment]
It's because FF 71 is broken, it also breaks LastPass plugin, Microsoft Teams, and a lot of other software:
https://www.reddit.com/r/voidlinux/comments/e637up/lastpass_not_working_with_firefox_71/

**Comment by Tampa** [comment]
Waterfox Classic or Current both work and retain better compatibility with plugins. Been using it for two years now, it works well and usually does not fork over Firefox bugs.

Firefox will bugfix-release after the holiday last I heard, so maybe a week or two, hopefully.
