### ISSUE TITLE
Firefox 70 Invalid X-Frame-Options:

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2826]
Hi,

I am using the Docker-compose to run this. I just pulled 3.56 and Firefox (70 on Linux) never finishes loading a page , until I do couple manual refreshes. Changing from board to board does not happen successfully as in it changes the board but it still shows the old board content, clearly a rendering issue.

Chromium seems to have no issue with this. It tuns fun in it. 

Bear in mind that this issue just started happening with the latest docker pull, I think I was using 3.54 before, so I will roill back to that one. However I thought that I would report this.

Here is the erros I see in Firefox 70 console. And I do not se any logs generated with `docker logs -f wekan-app`

```
Wekan Version	3.56.0
Meteor version	1.8.2
Node version	8.16.2
MongoDB version	4.0.11
```

https://DOMAIN/wekan/informationInvalid X-Frame-Options: “ALLOW-FROM” header from “https://DOMAIN/wekan/b/dkuMyPy9SjpbWEjCy/addon_pivotmaster” loaded into “https://DOMAIN/wekan/b/oPcepbD68umCywfsP/board”.

Firefox can’t establish a connection to the server at wss://DOMAIN/wekan/sockjs/568/cb2qs1ne/websocket. 0e3f5ad6a550ed1d08e8950011ec98a6a92a839d.js:81:17863

The connection to wss://DOMAIN/wekan/sockjs/568/cb2qs1ne/websocket was interrupted while the page was loading.

```

**Comment by xet7** [comment]
Sorry, at GitHub issues and pull requests can only be closed, not deleted.

**Comment by gerroon** [comment]
I tried deleting but the repo admin did not permit users to delete it,m I think this is soemthing an admin can do.

https://help.github.com/en/github/managing-your-work-on-github/deleting-an-issue
