### ISSUE TITLE
User board on get_user API

### ISSUE THREAD

**Issue by denis-nh** [wekan/wekan#2829]
Hi, is it possible to add on user detail API the id of the borad which he is member?

Thanks a lot!

Server wekan version 3.55.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/REST-API-Boards#information-about-boards-of-user

**Comment by denis-nh** [comment]
Thanks for the response, but the answer not responde my question. When I call /api/users/user_id, the response not contain the board's ids of the boards which the user is members. 
So if I want to know which boards a particular user is a member of, I can't know.
