### ISSUE TITLE
Is there a possibility of limiting the content sent via Webhooks?

### ISSUE THREAD

**Issue by thomasjac** [wekan/wekan#2830]
we use Wekan and we think it's great. We also use Mattermost and we have connected Wekan with Mattermost via Webhook. Now all activities in Wekan are automatically posted in Mattermost. Our question is whether there is a possibility of limiting the content sent? e.g. that selecting a card or adjusting the start time of a task should not sent. I didn't find anything about this in the documentation.

**Comment by xet7** [comment]
## 1) Webhooks Attributes

https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys#list-of-supported-keys

What to send to Outgoing Webhook, or leave out.
Example, that includes all that are default: 
```
cardId,listId,oldListId,boardId,comment,user,card,commentId .
```
To enable the Webhooks Attributes of Wekan:
```
snap set wekan webhooks-attributes=cardId,listId,oldListId,boardId,comment,user,card,commentId
```
Disable the Webhooks Attributest of Wekan to send all default ones:
```
snap set wekan webhooks-attributes=''
```
## 2) Card opened webhook
From Wekan Snap help:
```
wekan.help | less
```
This setting https://github.com/wekan/wekan/issues/2518
```
Card opened, send webhook message. Default: false 
Enable:
        $ snap set wekan card-opened-webhook-enabled='true'
Disable, default:
        $ snap set wekan card-opened-webhook-enabled='false'
```
For Docker, same settings at docker-compose.yml at https://github.com/wekan/wekan

## 3) Wekan Admin Panel

Wekan Admin Panel has Global Webhooks, but I don't know does that help.

## Question

Does this answer your question? Or do you mean something else?

**Comment by thomasjac** [comment]
perfect, thank you very much.
