### ISSUE TITLE
setting the default language for public, not logged in users

### ISSUE THREAD

**Issue by intellekta** [wekan/wekan#2831]
possibillity to set the board language for public users

via option in the admin-panel
board-default-language=DE

or via url

https://my.domain.com/b/id/name?language=DE

**Comment by xet7** [comment]
@intellekta 

At public board, currently settigs are saved to cookies. For example, when you change Lists/Swimlanes/Calendar view, and reload webbrowser, that view becomes visible.

It seems that currently on public board Language selection is not visible.

Would it be enough that I would make Language selection visible, and add using cookies to it ? Then it would be possible to change language, reload webbrowser, and have Wekan in that language.

I would think that currently language is selected according to webbrowser settings.

**Comment by intellekta** [comment]
1. when i click on list/swimlanes/calender and reload the browser the view is the same "Lists"
my version is 2.75, maybe this works fine in newer builds.

2. when it is possible to change the language with cookies, everytime the user clears the browser the setting is lost, i think its not my favorit solution.

3. my browser "chrome" is installed in german also my win10 os and also the navigator.language is: de-DE

All my public viewers are from germany and it would be nice to have an option "board language=DE"

For all other non-English speakers, such as Spain and France, this would also be helpful.

**Comment by xet7** [comment]
Wekan v2.75 [was released 2019-05-22](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v275-2019-05-22-wekan-release). Current Wekan version is [v3.56](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v356-2019-11-21-wekan-release). I do support only newest Wekan version. Old versions have security issues because of old versions of Node.js etc. Using cookies on public boards is recent feature.

**Comment by xet7** [comment]
Please [Backup](https://github.com/wekan/wekan/wiki/Backup) and restore it to newest Wekan version.

**Comment by xet7** [comment]
I can develop this feature if someone pre-pays me 300 euro at:
https://wekan.team/commercial-support/
