### ISSUE TITLE
REST API - Cannot add new card to board

### ISSUE THREAD

**Issue by hiro-toshihide** [wekan/wekan#2833]
## Issue
**Problem description**:
I am trying to add new cards to a board by the user with administrator role (IsAdmin:true). 
I get the response HTTP status 401:Unauthorized.I am using REST API to do this. 

- RestAPI
new_card
POST http://xxx.xxx.xxx.xxx:12345/api/boards/pLWAXgqeW2X9Hv3SS/lists/S9CAMjENQGwHa8kwb/cards/

- Header
  Content-Type: multipart/form-data' 
  Accept: application/json' 
  Authorization:Bearer XXXXXXXXXXXXXXXX

- Formdata
  title:test111
  authorId:8cMqBHis3P3cs4L82
  description:aaa
  swimlaneId:Jifw4igPWF3J4qeL7

- Response
  HTTP Status 401:Unauthorized
- Header
  cache-control →no-store
  connection →keep-alive
  date →Fri, 29 Nov 2019 10:10:24 GMT
  pragma →no-cache
  transfer-encoding →chunked

- Body
  none

**Server Setup Information**:
Wekan Settings
- Wekan Version：3.55.0
- Meteor version	1.8.2
- Node Version	8.16.2
- MongoDB version	3.2.13
- MongoDB storage engine	wiredTiger
- MongoDB Oplog enabled	
- OS 	Linux
- OS Platform	linux Ubuntu

**Comment by xet7** [comment]
Try Wekan v3.56

**Comment by Maxime35-bzh** [comment]
I'm same issue. I downloaded the last virtual box image :

Wekan Version : 3.42.0
Version de Meteor : 1.8.1
Version de Node : 8.16.1
Version de MongoDB : 3.2.21

GET verb work but with POST :

> {
"isClientSafe":true,
"error":"Unauthorized",
"reason":"Unauthorized",
"message":"Unauthorized [Unauthorized]",
"errorType":"Meteor.Error",
"statusCode":401
}> 
Or internal error.

Is there a particular configuration or role for the user using the API ?

**Comment by hiro-toshihide** [comment]
I could add a new card.
I was using Postman to check the IF of RestAPI. 
I changed the content-type as application/x-www-form-urlencoded and it worked.

> Maxime35-bzh
I changed each user's role to admin:yes via admin panel-> pepole.

**Comment by Maxime35-bzh** [comment]
Thx hiro-toshihide.
I try with content-type as application/json and it worked too.
On https://wekan.github.io/api/v3.55/, it's don't work with Content-Type: multipart/form-data.

**Comment by gustavengstrom** [comment]
I also had some problems here using the request library. The docs suggests using params variable to pass the body. (https://wekan.github.io/api/v4.48/?python#new_card) but this results in a 401. 

This is what worked for me:
`  
response = requests.post(
        "http://wekan:8080/api/boards/{}/lists/{}/cards".format(board_id, list_id),
        headers={
            "Accept": "application/json",
            "Authorization": "Bearer {}".format(token),
        },
        data=body_params_dict,
    )
`

**Comment by xet7** [comment]
@gustavengstrom 

Please try wekan.py example at https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API
