### ISSUE TITLE
Mail Problem

### ISSUE THREAD

**Issue by fquantin** [wekan/wekan#2835]
Hi everybody,

I have a problem when i add smtp server for receive mail after registering account
I have this error : Error trying to send email: unable to verify the first certificate

I hope you can help me

 Thank You

**Comment by GELI34** [comment]
Hello, I had the same problem. Were u able to  resolve this issue ?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by xet7** [comment]
There is about ignoreTLS at that page:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#starttls-sending-test-email-failed
