### ISSUE TITLE
"Cannot read property 'scrollHeight' of undefined"

### ISSUE THREAD

**Issue by salviof** [wekan/wekan#2838]
I'm using wekan with a docker-container, between a proxy (traefik) 
->this version :meteor-1.8  image:  24471ba279b0
On some "work frames" I get this error on Javascript and the screen stay displays warning to wait
thats ocorr only in desktop mode.

javascript error points to this line of this file:
**da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:331**

Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at n.calculateNextPeak (da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:331)
    at Object.readyCallback (da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:331)
    at da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:83
    at da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:83
    at Array.forEach (<anonymous>)
    at w._runAfterUpdateCallbacks (da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:83)
    at w._performWrites (da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:83)
    at w._flushBufferedWrites (da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:83)
    at w._livedata_data (da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:83)
    at w.n.connection._livedata_data (da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:257)

## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

**Comment by salviof** [comment]
Updating: 
In mobile, when I chose one of grid item , I receve that:

TypeError: Cannot read property 'archived' of undefined
    at e.getArchived (https://mysite.da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:331:579856)
    at https://mysite/da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:63:33251
    at Object.p.call (https://mysite/da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:129:1925)
    at https://mysite./da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:331:199535
    at f.View.<anonymous> (https://fluxo.casanovadigital.com.br/da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:63:27962)
    at https://mysite./da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:63:18999
    at Function.e._withTemplateInstanceFunc (https://fmysite./da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:63:37826)
    at https:/mysite./da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:63:18951
    at Object.f._withCurrentView (https://mysite./da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:63:23077)
    at if:condition (https://mysite./da6c4844611e341257c127da77a9224dd1db296b.js?meteor_js_resource=true:63:18900) undefined

**Comment by xet7** [comment]
Huh what? meteor-1.8 branch has not existed for a long time. Please backup and install newest Wekan:
https://github.com/wekan/wekan/wiki/Backup

**Comment by salviof** [comment]
Thanks @xet7 
now i switched from quay.io/wekan/wekan:meteor-1.8 image to quay.io/wekan/wekan, is this the correct way to update my app? Now I get other errors. like title not found, members not found, how to deal with this situation preserving my currenty data? (The docker-compose sample from april 2019 recomend use  quay.io/wekan/wekan:meteor-1.8)

**Comment by salviof** [comment]
If you already have mongodb update scripts for each version, maybe I can work on a bash to be deployed to DockerFile, automating the upgrade from docker pull, 
thanks.

**Comment by xet7** [comment]
@salviof 

After backup, correct way to upgrade Docker is to look what is latest release at ChangeLog:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

So current release is v3.56 .

After that, you look is that Docker tag available, so that it has already been built:
- https://quay.io/wekan/wekan
- https://hub.docker.com/r/wekanteam/wekan/tags

Then you use that release tag, for example:
- image: quay.io/wekan/wekan:v3.56
- image: wekanteam/wekan:v3.56

Do not non-release tags, like without a tag at all, or latest, because those have in-progress unreleased changes.

There is example of upgrading here:
https://github.com/wekan/wekan-mongodb#backup-before-upgrading

But as a shorter version, first stop Wekan, and remove wekan-app container:
``` 
docker-compose stop
docker rm wekan-app
```
Then edit docker-compose.yml so that it has newest release tag. Then:
```
docker-compose up -d
```
Then you can check did Wekan start correctly:
```
docker logs wekan-app
docker logs wekan-db
```
If you see MongoDB errors, you need to stop and remove both containers and restore data from MongoDB backup:
```
docker-compose down
docker rm wekan-app wekan-db
docker-compose up -d
docker stop wekan-app
docker cp dump wekan-db:/data/
docker exec -it wekan-db bash
cd /data
mongorestore --drop
exit
docker start wekan-app
```
Then if you still see for example MongoDB index errors, you need to restore again like above, but with:
```
mongorestore --drop --noIndexRestore
```
Anyway, I prefer to use Snap, that upgrades automatically.
