### ISSUE TITLE
Bug: Disable self registration option not working

### ISSUE THREAD

**Issue by ilgiaco** [wekan/wekan#2839]
**Server Setup Information**:

* Wekan version: 3.56
* Operating System: Ubuntu 16.04
* Deployment Method: bundle/source
* Http frontend: none
* Node Version: v8.16.2
* MongoDB Version: 2.6.10

**Problem description**:
![immagine](https://user-images.githubusercontent.com/15621136/70222731-aa46b200-174a-11ea-941b-1a13fafd1d4e.png)
As you can see Disable self registration option is checked in Admin panel
![immagine](https://user-images.githubusercontent.com/15621136/70222770-bc285500-174a-11ea-9627-b489a021ee26.png)
but in login section I still see self-registration link and if clicked I can still see the registration form, even after restarting wekan service.

Any idea?

**Comment by Nelstaar** [comment]
Same problem on CentOs7 (Installed with snap):
Wekan Version : 3.60.0
Meteor version : 1.8.3
Node version : 8.17.0
MongoDB version : 3.2.22
MongoDB storage engine : wiredTiger
MongoDB Oplog enabled
OS Type : Linux
OS Platform : linux
OS Arch : x64
OS Release : 3.10.0-1062.1.2.el7.x86_64

**Comment by xet7** [comment]
As a temporary workaround, you can have some webserver like Caddy/Nginx/Apache at front of Wekan and redirect `sign-up` url to `sign-in`.

If some other Wekan contributor has time, it would be nice. Currently I'm at this point with this patch, where sign-up url gets disabled, but Admin Panel UI does not change it. Well, it could work as environment variable, but having Admin Panel UI working for it would be better.

```
--- a/config/accounts.js
+++ b/config/accounts.js
@@ -1,5 +1,13 @@
 const passwordField = AccountsTemplates.removeField('password');
 const emailField = AccountsTemplates.removeField('email');
+let disableRegistration = true;
+
+Meteor.call('disableRegistration', (err, data) => {
+  if (!err) {
+    disableRegistration = data;
+    console.log(data);
+  }
+});
 
 AccountsTemplates.addFields([
   {
@@ -28,6 +36,7 @@ AccountsTemplates.configure({
   enablePasswordChange: true,
   sendVerificationEmail: true,
   showForgotPasswordLink: true,
+  forbidClientAccountCreation: disableRegistration,
   onLogoutHook() {
     const homePage = 'home';
     if (FlowRouter.getRouteName() === homePage) {
@@ -38,7 +47,13 @@ AccountsTemplates.configure({
   },
 });
 
-['signIn', 'signUp', 'resetPwd', 'forgotPwd', 'enrollAccount'].forEach(
+if (!disableRegistration) {
+  ['signUp'].forEach(
+    routeName => AccountsTemplates.configureRoute(routeName),
+  );
+}
+
+['signIn', 'resetPwd', 'forgotPwd', 'enrollAccount'].forEach(
   routeName => AccountsTemplates.configureRoute(routeName),
 );
 
diff --git a/models/settings.js b/models/settings.js
index 8eb02c5b..55e33251 100644
--- a/models/settings.js
+++ b/models/settings.js
@@ -301,6 +301,10 @@ if (Meteor.isServer) {
       }
     },
 
+    disableRegistration() {
+      return Settings.findOne().disableRegistration;
+    },
+
     getMatomoConf() {
       return {
         address: getEnvVar('MATOMO_ADDRESS'),
```

**Comment by xet7** [comment]
If this is really urgent for someone, it's possible for someone to pre-pay me 100 euro so I will prioritize and fix this first:
https://wekan.team/commercial-support/

**Comment by bkraul** [comment]
I wish there was some sort of crowdfunding site for bugs. 100 euro seems a bit steep for a single payer, especially for the reported issue. However, I am sure that a lot of us would crowd fund 100 (or more) in a jiffy. Maybe set up a PayPal bug squash collection campaign or something like that?

**Comment by xet7** [comment]
@bkraul

There is already PayPal payment page. https://wekan.team/commercial-support/
Dropdown starts from 10 euro, there is alternatives 10/30/50/100 etc.

I would be very happy for any amount, it would encourage me to fix bugs. It would also show that there is still interest for Wekan.

For example at #2698, many commented that they would like to participate to funding that feature. But nobody did. I did already spend on that issue much more time than the original 50 euro.

What I'm currently most happy about, is that some have added pull requests.

What would it take to organize such bug squash collection campaign?

**Comment by xet7** [comment]
It's also possible to send with PayPal or TransferWise any custom amount to email address support@wekan.team

**Comment by bkraul** [comment]
Well, actually what you have is pretty much what I am suggesting. I'll take a look at it. Like I mentioned, I am not sure I could go to my company and say, "hey man, so the registration disable has a bug, but we can pay €100.00 to get it fixed", but if enough of us pitched in €10 euro (amounting to the €100 you are requesting), that would be cool.

**Comment by bkraul** [comment]
Granted, as you know, this is probably a bad time to motivate anyone to pay sums of money when like for example in the US our economy is basically at a standstill due to the virus. But if we get through this one, we will add wekan to our list of supported contributions, as we seem to be fixing to start using it more. (we have been trying it out for several months now).

**Comment by xet7** [comment]
Well, I do know how corporate world works. I was previously working at a company as SysAdmin, they did pay thousands of euros for Jira and Trello. And when Wekan has unlimited boards, Wekan is free with MIT license, anyone from any company can contribute fixes etc, getting feedback that 100 euro is too much is kind of strange. Wekan web interface is a lot faster than Jira cloud web interface. Wekan has Swimlanes, that Trello does not have. Jira does not have public boards like Wekan, it would require license of each user. With Wekan anyone can keep data private according to GDPR. 

I do also know how it goes in big companies. Big company hires big support company, that basically just answers to tickets without fixing the actual bug, and without paying to original maintainer of software. So using Open Source kanban software is mostly about grass root effort by company employees.

Then there are those companies that would like to hire me because they are integrating Wekan to their internal systems, but they have so strict contracts that they are not allowed to hire me, or pay me in any way. Companies at various countries or working for government.

I also get feedback about Wekan website, that because of it's look, they are unable to pitch about Wekan to company management.

There are some companies that understand Open Source, and have sent source code as pull requests, or have funded some features.

**Comment by bkraul** [comment]
Well that's the thing man, we are not a big company. We are a small business. While we do well most of the time, we definitely do not qualify as a "big corporate company" by any means. I think I had mentioned before, I wish I was well-versed on meteor and other tech you use on this project. I love contributing.

**Comment by xet7** [comment]
For small business, it would help to even pitch for that 10 euro. That would help.

Currently I'm a freelancer working at home. Those payments goes directly to my everyday bills like rent etc. I don't have anyone working for me. I do all maintaining Wekan by myself, create installers for many platforms, developing features, fixing bugs, answering to issues, creating documentation. And then there is Wekan Community around the world that sends pull requests etc. It's like me and Wekan Community against all those propietary kanban software.

**Comment by bkraul** [comment]
So, I spoke to my CISO at my company, and he asked that if we went ahead and donated the €100.00, could you guarantee fixing of this issue in a reasonable time?

**Comment by xet7** [comment]
@bkraul 

Yes, this would be fixed at this month April.

**Comment by all3kcis** [comment]
@xet7  this issue won't be solved?

**Comment by xet7** [comment]
@all3kcis 

AFAIK nobody has paid to [Wekan Commercial Support](https://wekan.team/commercial-support/) anything yet for this, so I presume this is not urgent. My priorities are:

1. Security fixes
2. Commercial Support paid support/features/fixes/hosting at [Public Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)
3. Other features and fixes. In general, I will fix everything, given enough time.

Because Wekan is Open Source, anyone else also can send pull request for any new feature/fix.

**Comment by fettfoen** [comment]
Thanks, just donate 10€. Hope some people follow. Thanks for work.

**Comment by Vida444** [comment]
> Thanks, just donate 10€. Hope some people follow. Thanks for work.

I've followed up just now with a "very tiny" donation. ;)

**Comment by xet7** [comment]
I added this to [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/rXqZN2jjg6eW5rqAJ).

**Comment by fettfoen** [comment]
When using LDAP only. Is it possible to hide "Forgot your password?" ?

**Comment by relikd** [comment]
@ilgiaco Had the same "issue", though if you click on "Registrati", you will see there is an additional field "referral code" (or likewise naming). But I ended up disabling passwords altogether.

@fettfoen not sure what your setup is, but with snap you can run `snap set wekan password-login-enabled='false'`. I guess the environment variable will be `PASSWORD_LOGIN_ENABLED=false`

![wekan](https://user-images.githubusercontent.com/1321720/91668563-db071c80-eb0d-11ea-80b2-db40b6c7c5de.png)

**Comment by ASLLR** [comment]
Hi, did you plan this basic correction ?

Best Regards,

**Comment by xet7** [comment]
@ASLLR 

Yes, I try to do this at next month October.

**Comment by Meeques** [comment]
@xet7
Are you currently also looking at how to turn off the 'forgot my password' option?

**Comment by flypenguin** [comment]
bug apparently still there. @xet7 if i donate the 100, will it be fixed? and (very roughly) when? amount seems fair.

**Comment by xet7** [comment]
@flypenguin 

Depends if you really pay that.

Currently it's not possible to make any estimate for anything, because nobody has paid for some time.

**Comment by ASLLR** [comment]
Hello @xet7 if I recap, we have to pay you to repair an option available initially that you yourself broke ? 

Best Regards,

**Comment by xet7** [comment]
@ASLLR 

Hmm what? Just a moment I'll read history of this issue.

**Comment by Meeques** [comment]
@xet7 

Sorry but neither disable self registration nor disable forgot my password seems to be working.

**Comment by ASLLR** [comment]
Hi @Meeques, i'm on 6.09 version of wekan (with docker-compose) and it's work for me, for the 2 options. 

![image](https://user-images.githubusercontent.com/37147055/155948064-b957d89e-66ee-4fd6-8371-bd06935a693d.png)


Have a nice day,

**Comment by Meeques** [comment]
Oh, I'm still on version 6.08 with snap. I thought it had to work since there was a new checkbox to disable forgot my password. So thank you very much for your comment, I'll check again when we're at version 6.09.
Have a nice day, too

**Comment by Meeques** [comment]
(FYI: it works!)

**Comment by derhelge** [comment]
Hi,

we are also on 6.09 but i can't see that this issue is fixed. Although "self registration" is disabled, it is still possible to do so. @Meeques What did you do to disable it?

> Currently it's not possible to make any estimate for anything, because nobody has paid for some time.
@xet7 Actually we already paid for this issue. Please check your emails (on 2022-02-16).

**Comment by Meeques** [comment]
Hi @derhelge we just set it in the admin console:

![Wekanselfregsetting](https://user-images.githubusercontent.com/92315677/166418216-97f635bc-a5c7-4e07-b4ff-c83be0cf9932.jpg)

**Comment by xet7** [comment]
@derhelge 

Is it [some of these issues](https://github.com/wekan/wekan/issues?q=is%3Aissue+is%3Aopen+self+registration) ? Or some new issue? Please [Backup](https://github.com/wekan/wekan/wiki/Backup) and try with newest WeKan Docker version.

I did make some fixes to this, but if it does not work, it needs adding new issue.  Not commenting on closed issue.
