### ISSUE TITLE
Some Markdown Formatting not working

### ISSUE THREAD

**Issue by zeineath** [wekan/wekan#284]
I've encountered some markup formatting (markdown) to be working previously but no longer behaving correctly in the new UI :

* ordered list (using a number then a period followed by string)
* italics (single asterisk enclosing a string) and bold/italicized (triple asterisk)
* code blocks (4 spaces before the string in a newline)

I may have missed something else but these 3 are the most common.

**Comment by ePirat** [comment]
It is working as expected (the markup is generated correctly), but the styles are missing.

**Comment by mquandalle** [comment]
Yes, I just need to put the appropriate CSS [here](https://github.com/wekan/wekan/blob/6a92963e2a79e2819b7492a0389c1c48a9467ba3/client/components/main/layouts.styl#L315).
cf. #185
