### ISSUE TITLE
Adding checklist items

### ISSUE THREAD

**Issue by prunarevic** [wekan/wekan#2841]
Is it possible to add checklist items to a card? Or is there a way to copy/paste a card via REST API?

**Comment by Tampa** [comment]
Normally once the checklist is created there should be a little + Add checklist item underneath the last checklist item to add more. What exactly are you trying to do that isn't working?

**Comment by xet7** [comment]
REST API info here: https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API

**Comment by antrest** [comment]
Currently the api only support Get, Update and Delete a checklist item. We need to add a Create checklist item api endpoint for if.

**Comment by antrest** [comment]
> REST API info here: https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API

Currently the api only support Get, Update and Delete a checklist item. We need to add a Create checklist item api endpoint for if.

**Comment by xet7** [comment]
@antrest 

Wekan API docs are at https://wekan.github.io/api/

Wekan API code is at these files:
https://github.com/wekan/wekan/tree/master/models

If something is missing, please look at similar code in those files, add it, and send pull request. Thanks!
