### ISSUE TITLE
Board Export on Sandstorm not Working

### ISSUE THREAD

**Issue by warpdrivesupercruise** [wekan/wekan#2842]
## Board Export on Sandstorm is empty

Im running Wekan 3.56.0~2019-11-21 on the  hosted Oasis-Sandstorm (same Devs as Sandstorm) - wich is unfortunatly going to be shut down by December 31.
Because of this, i need to export my boards out of my wekan-grain, wich is not possible.

**Issue**
When i click through:
- "the three hizontal lines" / "Board Settings" / "Export Board"
- it opens the dialogue box for a download:
"wekan-export-board-sandstorm.json"
plain text document (0 bytes)

The file is empty.

**Operating System**
Tired it on diffrent machines:
- Linux Mint (Firefox v70.0.1)
- macOSX (Firefox v71.0)

**Additional Info**
I want to learn how to run (and defend) my own server, but not right now and not in this timeframe. Therefore i want to run Wekan offline on my Linux Mint Setup.

**Comment by ocdtrekkie** [comment]
In the short term, at least backup your Sandstorm grain (the download icon on the top bar of Sandstorm when you have the grain open). The zip file contains everything needed to restore that Wekan grain on a Sandstorm server, and also, there are instructions to extract the data for use in normal Wekan: https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by ocdtrekkie** [comment]
Additionally, you can install Sandstorm on your own machine, and use the Mass Transfer feature from Oasis to your own server. Mass Transfer will work even if the destination Sandstorm server is not publicly addressable, as long as the source (Oasis) is.

**Comment by xet7** [comment]
Try newest Wekan.

**Comment by timshannon** [comment]
FYI, I'm still getting this issue in my sandstorm instance: wekan version 5.88.0.

The export to JSON url (as well as any export URLs) appear to be missing the authToken:
```
https://ui-1234.....mydomain.com/api/boards/sandstorm/export?authToken=
```

**Comment by ocdtrekkie** [comment]
I am seeing that... but clicking on it does actually successfully export the board, it seems like.

**Comment by timshannon** [comment]
I'm still digging into it.  I have 3 different sandstorm grains running wekan instances.  Two of them exported fine, but one of them doesn't.  The only difference I can see between them is that the one that doesn't export is 1) much bigger and 2) has images.

**Comment by xet7** [comment]
There is some Sandstorm issue about too small tmp at Sandstorm, WeKan export runs out of space with bigger boards, I presume it's not fixed yet
