### ISSUE TITLE
CSS fix for untidy areas in `Card` details

### ISSUE THREAD

**Issue by geoyws** [wekan/wekan#2843]
We just have to add `box-sizing: border-box`, basically.

# Before
<img width="308" alt="Screenshot 2019-12-06 at 5 05 22 PM" src="https://user-images.githubusercontent.com/1738396/70310825-83bc7000-184b-11ea-885d-255fe8cdf614.png">
<img width="576" alt="Screenshot 2019-12-06 at 5 05 09 PM" src="https://user-images.githubusercontent.com/1738396/70310824-8323d980-184b-11ea-8430-b6fa5c22012f.png">
# After
<img width="310" alt="Screenshot 2019-12-06 at 5 02 32 PM" src="https://user-images.githubusercontent.com/1738396/70310822-8323d980-184b-11ea-8ccb-9d8e4d3728b8.png">
<img width="576" alt="Screenshot 2019-12-06 at 5 03 04 PM" src="https://user-images.githubusercontent.com/1738396/70310823-8323d980-184b-11ea-9ee6-f059ef455541.png">

**Comment by xet7** [comment]
Please give more details or better screenshot. I don't understand what you mean.

**Comment by sfahrenholz** [comment]
I think, he mean the functions "Delete...", "View it" and the card close function. in the bottom screenshot, the functions are better clickable than in the first picture.

**Comment by geoyws** [comment]
> I think, he mean the functions "Delete...", "View it" and the card close function. in the bottom screenshot, the functions are better clickable than in the first picture.

Yes precisely this. Sorry I didn't highlight that!
