### ISSUE TITLE
No filter for assignee

### ISSUE THREAD

**Issue by xadagaras** [wekan/wekan#2844]
## Issue

With Wekan version v3.50 2019-11-13 Wekan release you've added the possibility to set an assignee on a card. But you can not filter this field, only tickets with member's but not assignee.

It would be nice if you could also filter by assignee.

Best Regards,

Daniel

**Comment by rodig03** [comment]
I have the same issue in wekan 3.76 - but in the demo wekan in the cloud it works. So I suspect this is a bug not present all the time?

**Comment by PiusS** [comment]
We use Wekan 3.56.0 and 3.8.3 and have the same struggle, to be not able to filter by assignee.

We hope to be blessed with this feature, since its an essentials in our eyes. :)

**Comment by xet7** [comment]
Please only use newest Wekan version, if your Wekan is exposed to Internet. Old versions are vulnerable.

**Comment by stegro** [comment]
> but in the demo wekan in the cloud it works. So I suspect this is a bug not present all the time?
In version 3.84 the "my cards" filter does not show the cards my user is assignee of. There seems to be only a filter based on 'members'.
Can you confirm, that this is indeed implemented in some development version - or missing at the moment?

**Comment by xet7** [comment]
@stegro 

Wekan running at https://boards.wekan.team and it's public board [Roadmap](https://wekan.github.io/) is real newest Wekan Snap v3.84 running on bare metal server donated to Wekan development by [CNCF that is part Linux Foundation](https://blog.wekan.team/2019/06/wekan-on-raspi3-and-arm64-server-now-works-and-whats-next-with-cncf/index.html).

I don't know is your install Snap or some other Wekan platform.

**Comment by xet7** [comment]
There is only one Wekan version from https://github.com/wekan/wekan master branch. Differences between platforms are because of different container technology, like Snap/Docker/Sandstorm grain.

**Comment by xet7** [comment]
For example, while Snap and Docker use the same code, I have received some feedback that LDAP works better in Snap than in Docker.

For Sandstorm, based on isSandstorm environment variable, integrated Sandstorm SSO is used, board menu structure is a little different, and Wekan can not yet import attachments from Trello because inside sandboxed Sandstorm grain accessing Internet needs to be implemented with different kind of code. Also having email from Wekan grain to outside would need different kind of code so that it would work.

**Comment by rodig03** [comment]
I still have the issue - and I am using these versions on docker: could it be an issue with the DB version or is one of the following versions / settings not ok?

Wekan Version | 3.84.0
Meteor-Version | 1.10.1
Node-Version | 12.16.1
MongoDB-Version | 3.2.21
MongoDB-Speicher-Engine | wiredTiger
MongoDB-Oplog aktiviert

Thanks,
Robert

**Comment by xet7** [comment]
I don't know why some features that work on Snap do not work in Docker. Settings, code and database are mostly the same. You can try to [backup](https://github.com/wekan/wekan/wiki/Backup), then [Install Snap](https://github.com/wekan/wekan-snap/wiki/Install), restore as described in backup page, and test does it work then. For each platform like Snap/Docker/Sandstorm, it has taken countless of hours to get them even building and working well enough.

**Comment by xet7** [comment]
Filter for assignee was added at [Wekan v3.91](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v391-2020-04-08-wekan-release) with this code https://github.com/wekan/wekan/pull/2997

**Comment by speendo** [comment]
was this ever resolved for you, @rodig03 ? I think I have the same issue on Docker with the newest version of Wekan
