### ISSUE TITLE
Are this features still supported in Wekan

### ISSUE THREAD

**Issue by kkoderr** [wekan/wekan#2845]
I want to know if the following features are still supported in wekan:

* add attachment
* add checklist item
* add checklist
* comment creation
* delete attachment
* remove checked item
* remove checklist
* set custom field
* uncomplete checklist

I will also like to know how to get the label name and swimlane name from the webhook. Wekan webhook seams to not send the label and swimlane name in its payload when it is triggered.

**Comment by xet7** [comment]
@kkoderr 

Did you try them in newest Wekan?

**Comment by xet7** [comment]
Moved to #1969

**Comment by kkoderr** [comment]
> @kkoderr
> 
> Did you try them in newest Wekan?
I am using a snap locally. I can't tell if its the latest but its a recent install.
