### ISSUE TITLE
Rendered pages are blank with Firefox

### ISSUE THREAD

**Issue by mbocquet** [wekan/wekan#2847]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 3.56.0
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 8.16.2
* MongoDB Version: 3.2.21
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
Chromium and Firefox. See below for détails.

**Problem description**:
- Gif animations will be attached later, needs blurring private infos
- *Explain steps how to reproduce*
Open Chromium, Go to Wekan instance URL, the login page appears, OK
Open Firefox, Go to Wekan instance URL, nothing appears but a blank page.
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*

```
Presence started serverId=YYEodonNywJtuLSbc
Meteor APM: completed instrumenting the app
```

**Comment by xet7** [comment]
Check your Nginx config:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by mbocquet** [comment]
Hi Lauri.

Thanks for your fast response. I checked my Nginx config, commented some extra "add_header" settings which were in my config but not in the wekan example. After re-enabling almost all of these extra settings, I found THE one Firefox doesn't like but Chromium still don't care :
`add_header Content-Type text/html;`

I agree this header is useless for wekan !
Thanks again.

Cheers

Mathias.
