### ISSUE TITLE
Board is not loading after creating card with <a> in title

### ISSUE THREAD

**Issue by cocoglycerides** [wekan/wekan#2848]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 3.56.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache2
* Node Version: 8.16.2
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome 79

**Problem description**:
Card is not created and the Board does not load

- *Explain steps how to reproduce*
Create a card with `<a>` in title

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.* 
[log-Wekan.log](https://github.com/wekan/wekan/files/3950565/log-Wekan.log)
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
nothing

**Comment by xet7** [comment]
Nice find :)

You can edit MongoDB database with nosqlbooster GUI, and  edit that card to not have that content.

More info at:
- https://github.com/wekan/wekan/wiki/Backup
- https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by xet7** [comment]
At Wekan Snap version, MongoDB server is at port 27019

**Comment by juliensl** [comment]
Hi ! 

It was working at the version 3.13 and broked at the version 3.16.
There are not versions between, are there ?

**Comment by xet7** [comment]
This is fixed in newest Wekan.
