### ISSUE TITLE
Download attachments on members board not working and can delete the attachments

### ISSUE THREAD

**Issue by shekar73** [wekan/wekan#285]
Test Description: As a member of the board I should able to dowload attachment but NOT delete the attachment, (as delete option should stay with the Admin)

Result: The attachment cannot be downloaded and also as a member I can delete the attachment. 

In the example below TestAccount11 is the member to the board with TestAccount13 as admin

![image](https://cloud.githubusercontent.com/assets/203255/9676912/9ecbd7ca-5287-11e5-8976-d46c0f3356a9.png)

**Comment by xet7** [comment]
This was added at #3377 at [Wekan v4.60](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v460-2020-12-15-wekan-release)
