### ISSUE TITLE
Feature request: Don't add a blank space for empty custom fields on minicards

### ISSUE THREAD

**Issue by roobre** [wekan/wekan#2850]
**Server Setup Information**:

* Did you test in newest Wekan?: Yes, in `wekan:latest`
* Wekan version: 3.56.0
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 8.16.2
* MongoDB Version: 4.0.12
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?: Firefox 71.0b12 (64-bit)

First of all, I'd like to thank all the maintainers and contributors for this great project. I've been using Wekan as a replacement for a whiteboard with post-its for a week and it's working wonders. Thanks!

Now, I'm really liking the custom fields feature, I think it's very helpful for tailoring the view to one's needs. I particular I like to make use of a custom field called "short description" to show, well, a short description directly in the minicard. I find this useful for not polluting the title.
Thing is, say I use this for 1/4 of my cards. This is enough to tick the "Auto create field to all cards" checkbox to avoid the expensive flow of clicks that one needs to add it to a card, but this adds an ugly padding for all cards having the field blank, wasting space.

Would it be possible or reasonable to not render this space if the field is blank?

PS: Since I see you have a lot of issues open, maybe I can work on a PR for this, if you think it's a good ide. Seems simple enough for a non js expert like me to handle :)

**Comment by xet7** [comment]
Please add screenshot about how it is currently, and screenshot mockup what is should look like.

Also see:
https://github.com/wekan/wekan/wiki/Custom-Fields

**Comment by roobre** [comment]
Minicard without custom field enabled:
![DeepinScreenshot_select-area_20191212163222](https://user-images.githubusercontent.com/969721/70725662-17cf8100-1cfd-11ea-9b2e-d8db30be0a6a.png)

Minicard with custom field enabled, but blank:
![DeepinScreenshot_select-area_20191212163234](https://user-images.githubusercontent.com/969721/70725685-1ef68f00-1cfd-11ea-84c1-eafd152afcb6.png)

Minicard with custom field enabled and a sample value:
![DeepinScreenshot_select-area_20191212163246](https://user-images.githubusercontent.com/969721/70725709-274eca00-1cfd-11ea-8477-42295291339d.png)

I think the second screenshot should look like the first, essentially. If there's nothing to display, then do not reserve space for it.

Thanks!

**Comment by roobre** [comment]
Looks great, thank you very much @xet7! <3
