### ISSUE TITLE
Does this work with CosmosDB or DynamoDB?

### ISSUE THREAD

**Issue by JonathanWilbur** [wekan/wekan#2852]
Does this work with CosmosDB or DynamoDB instead of MongoDB?

**Comment by xet7** [comment]
@JonathanWilbur 

I have not tried yet. Please try.

For example, first comment out these lines:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L92-L110
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L563-L564

Then change MONGO_URL to CosmosDB or DynamoDB address:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L151

Also change ROOT_URL to be for example like https://boards.example.com
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L164

You could have Docker cluster behind AWS ELB SSL cert, or something similar. Or alternatively, install Wekan to AWS Lightsail VM.

**Comment by xet7** [comment]
Actually, I think DynamoDB is not MongoDB compatible. Probably you do mean DocumentDB:
https://aws.amazon.com/documentdb/

**Comment by xet7** [comment]
About other MongoDB compatible databases:

1) FoundationDB does not yet work, I did not have time to try to fix it:
https://forums.foundationdb.org/t/how-to-connect-to-foundationdb-with-mongodb-cli/977/2

FoundationDB was open sourced by Apple.
https://github.com/apple/foundationdb

Here is announcement about MongoDB compatibility layer:
https://www.foundationdb.org/blog/announcing-document-layer/

Although, FoundationDB has quite high hardware requirements.

2) Percona Server for MongoDB does work with Wekan, if you are interested in some of it's features:
https://www.percona.com/software/mongo-database/feature-comparison
https://www.percona.com/downloads/percona-server-mongodb-LATEST/
https://github.com/percona/percona-server-mongodb

**Comment by xet7** [comment]
These seems to be this MongoDB compatible database in development progress, I have not tested it yet:
https://github.com/256dpi/lungo

**Comment by xet7** [comment]
MongoDB Atlas #2977
