### ISSUE TITLE
Issues with Trello-Import of big Board

### ISSUE THREAD

**Issue by ADDAH-temp** [wekan/wekan#2861]
## Issues / Problems with Board after Trello-Import

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: YES
* Did you test in newest Wekan?: YES
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 3.56
* If this is about old version of Wekan, what upgrade problem you have?: -
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): -
* Node Version: 8.16.2
* MongoDB Version: 4.0.11
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome/Firefox Current releases

**Problem description**:
I have several issues after importing a Board from Trello into Wekan, which I was not able to reproduce on any other imported Board. In my theory the sitze of the Board is the main problem here -> size JSON is 15mb

I found the following issues:
-> Archive from Trello is missing and or doesn't load
-> Members aren't taggable on cards though the mapping from Trello to Wekan was done correctly. (There appears only an @ without the username in the comment)
-> Cards copied and moved to other/new Boards are taking the issues with them

**Comment by xet7** [comment]
@ADDAH-temp 

Please test with newest Wekan Snap.

**Comment by xet7** [comment]
Moved to #4877
