### ISSUE TITLE
Test Wekan Edge v3.57

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2863]
@saschafoerster @Robert-Lebedeu @hever @roobre @koelle25 @mlechner and anyone else

Please [Test Edge](https://github.com/wekan/wekan/wiki/Test-Edge) and add comments to this issue about are those [at ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v357-2019-12-22-wekan-release) fixed, and is something else fixed or broken compared to previous Wekan version.

This is so that I could know can I release Wekan v3.57 to stable Snap channel.

Thanks!

**Comment by xet7** [comment]
I have not found any issues from Wekan v3.57, it seems to be an improvement. So I will release it.

**Comment by roobre** [comment]
Thanks for the effort! Unfortunately I'm on vacation this week (and thankfully far away from my kanban :P) but I will upgrade ASAP and report any bug I happen to find.
