### ISSUE TITLE
List name not wrapping correctly

### ISSUE THREAD

**Issue by Shorty365** [wekan/wekan#2866]
In Kanban-style the list-names are very short but I use Wekan also as a more conventional planboard with longer, more descriptive, List-names. I found out that these longer list-names don't wrap nicely and sometimes overwrite the 'hamburger'-menu of the list. This is purely cosmetical but does not look nice.
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 3.57
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache2
* Node Version: 
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome and Firefox

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

**Comment by avatar1024** [comment]
I have the same issue running Wekan 4.01. Some name list wrap well if long enough, while other don't and overwrite the + and hamburger menu.
![wekan-list name wrapping](https://user-images.githubusercontent.com/18719956/81501651-6fd0da80-92d1-11ea-8c3c-9c7949e2979e.png)
