### ISSUE TITLE
Bug: Unable to find archive card/list/swamlane in kanban setting

### ISSUE THREAD

**Issue by neobradley** [wekan/wekan#2872]
**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 3.62
* If this is about old version of Wekan, what upgrade problem you have?: N/A
* Operating System: CentOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 8.17
* MongoDB Version: 3.2.21
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome

**Problem description**:
- As admin user in kanban, I would like to check and review archive items.
- In board setting, the option of checking archived items is missing, only options left in settings is
```
Change color
Export board
Outgoing Webhooks
Subtasks Settings
Move Board to Archive
```
Which in previous version should be
```
Custom Fields
Archive
Change color
---------
Export board
Outgoing Webhooks
Subtasks Settings
Move Board to Archive
```

**Comment by xet7** [comment]
Thanks a lot for info! I will try to fix it and release new fixed version today.
