### ISSUE TITLE
Penetration tests results

### ISSUE THREAD

**Issue by podlisk** [wekan/wekan#2873]
Hello,

Firstly, thank you for very much for wekan!
As our usual practice, we are performing penetration tests on all our systems. We started using wekan and decided to include the instance into penetration test loop this year. There are certain findings that I would love to share with you. What would be the best way to proceed?

**Comment by xet7** [comment]
@podlisk 

Thanks a lot ! Please send details to me email to support@wekan.team , I'm maintainer of Wekan.
