### ISSUE TITLE
Full Read-Only User

### ISSUE THREAD

**Issue by stevekiss** [wekan/wekan#2876]
I would like to know if it is possible to create a fully read-only role. User in this role should not be able to create new boards, and they should not be able to modify any of the boards they are assigned to. All they should be able to do is view the boards they have been added to. The closest I can find in the current setup is the Comments Only role, but unfortunately users assigned to this role can still create boards. Can anyone advise me if this is possible and how I could go about implementing it?

Thank you in advance for your help.

**Comment by xet7** [comment]
@stevekiss 

## a) Wekan Commercial Support pre-paid feature

I can implement read only role if someone pays 300 euro for my coding time at:
https://wekan.team/commercial-support/

## b) Code it yourself

If you would like to code that feature yourself and add a pull request, see these commits how I implemented Worker role: 
- Worker role https://github.com/wekan/wekan/commit/f6f7705f23ea18d7f1b8f8736b762eb89e00a3cf 
- Fix: Unable to find Archive Card/List/Swimlane in board settings. https://github.com/wekan/wekan/commit/8ce993921718f3e10c2daa5fabb145b939d789dd

Also see [No Commets role commits](https://github.com/wekan/wekan/issues/1861#issuecomment-417664595) how I did it.

For information about coding Wekan, please see:
-  [These steps 3-5 of building Wekan](https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm#3-fork-wekan-and-clone-your-fork)
- [Directory Structure](https://github.com/wekan/wekan/wiki/Developer-Documentation)
- [Developer Docs](https://github.com/wekan/wekan/wiki/Developer-Documentation)
- Also search this open and closed issues and pull requests, many questions have already before answered many times
- [This blog post about coding Wekan](https://blog.wekan.team/2019/04/howto-code-part-1-learning-to-learn/)
- If you have any problems implementing this, [please ask any questions at this issue immediately](https://blog.wekan.team/2018/05/wekan-v1-00-released/) to get fast progress.

With above info, you can also implement any other kind of role.

**Comment by FuXXz** [comment]
First 250€ for a worker Role #2788, then 300€ for this Read-Only.
I Think it isn't productive to implement one role after another.
Why not implement an permission System, where you can add Roles and set up permission granually?
Would that be too extensive?

**Comment by xet7** [comment]
@FuXXz 

Well, sure it would make more sense to have granular permissions.

**Comment by FuXXz** [comment]
The question is how extensive / complicated would that be.
Unfortunately I can't do much myself, I'm not a programmer, but I can donate other ambitious programmers

**Comment by xet7** [comment]
Moved to #3022
