### ISSUE TITLE
Wekan on IOS 13.3 Safari/Chrome/Firefox doesn't support the afterwards loading of cards

### ISSUE THREAD

**Issue by r4nc0r** [wekan/wekan#2878]
Server Setup Information:

Did you test in newest Wekan?: yes
Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
What webbrowser version are you using?: Safari/Chrome/Firefox on IOS

Problem description:
- If I have a large List in my Wekan Board everything works fine on my PC, but on IOS with Safari/Chrome/Firefox it doesn't load new cards if i try to scroll down! Only the loading Animation is shown! 

So I hooked up the Iphone with a Mac and connected the devTools on the mac with the Iphone and saw this Error in the Debug Console: 
![IOS Wekan](https://user-images.githubusercontent.com/15196129/72064509-4f215580-32dc-11ea-86eb-d1063435d2ae.png)

**Comment by xet7** [comment]
@r4nc0r

It seems requestIdleCallback is not supported on Safari and iOS Safari:
https://caniuse.com/#feat=requestidlecallback

And if on iOS Chrome and Firefox are only allowed to use Safari webview component, then it causes this.

Maybe there is a workaround somewhere, that would need some web searching.

**Comment by xet7** [comment]
Or is this Chromium Mac bug? Still trying to figure it out.
https://bugs.chromium.org/p/chromium/issues/detail?id=811451

**Comment by r4nc0r** [comment]
I don't think so, because on OSX(I tried it) it works perfectly fine, and the used OS in the Chromium Bug is OSX. 
I think it is because requestIdleCallback is not supported.

**Comment by derbolle** [comment]
Hello @xet7 . Can you please give me a quick status update on this issue? We have ios Users in our Org which cannot currently use Wekan because of this bug. If there is any further Information you require, I would be happy to help in any way possible to me.

**Comment by xet7** [comment]
@derbolle 

Does it load any comments at all? Can you provide photo or screenshot?

**Comment by xet7** [comment]
@derbolle 

Or does it load any cards? How it behaves?

**Comment by xet7** [comment]
@derbolle 

What exactly does not work? I went to smartphone shop, and there is iPhones with iOS 13.3.0 and iOS 13.3.1. I used Safari to login to newest Wekan Snap version and I can open cards and write comments. It did work great.

![IMG_20200206_152121](https://user-images.githubusercontent.com/15545/73942345-8abd3880-48f7-11ea-9caf-75655a5e2617.jpg)


![IMG_20200206_153302](https://user-images.githubusercontent.com/15545/73942383-9a3c8180-48f7-11ea-9bfa-44ee0fd62a77.jpg)

**Comment by xet7** [comment]
I added checklist with 100 items, that I can scroll down from left border, left side of checkboxes. Seems to work OK.

**Comment by xet7** [comment]
Hmm, trying to re-read description of this bug. I did not yet try scrolling down list, does it load all cards. I will try later.

**Comment by derbolle** [comment]
Hello @xet7 I will inquire tomorrow with one User who experiences the problems and post the Information here. I think the Problem is loading Cards when one List on a board has many cards. Loading Animation is shown, cards are not loaded.

**Comment by r4nc0r** [comment]
Our Problem is exactly the same as @derbolle described:
Use Case:
-  loading Cards when one List on a board has many cards
Problem:
- Loading Animation is shown, cards are not loaded and the before mentioned Error in Console Output is logged
