### ISSUE TITLE
Wekan should be able to have several ROOT_URL

### ISSUE THREAD

**Issue by HLFH** [wekan/wekan#2880]
Hi,

Wekan should be able to have several ROOT_URL.
So, one Wekan instance can be served by Nginx web server on several server names.

**Comment by xet7** [comment]
It's already possible by running another wekan-app Docker container with same database:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L565-L589

**Comment by HLFH** [comment]
I know it is possible by running two Wekan instances. Apps like Matomo or Nextcloud can be served on multiple domain names with only one instance. I was hoping it will be possible in the future to do it with Wekan.
