### ISSUE TITLE
Swimlanes mode,WIP limit numbers or lists cannot be set independently in different Swimlanes

### ISSUE THREAD

**Issue by almightyBeck** [wekan/wekan#2882]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues
- LDAP: https://github.com/wekan/wekan-ldap/issues
- UCS: https://github.com/wekan/univention/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:yes
* Did you test in newest Wekan?:yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:V3.69
* If this is about old version of Wekan, what upgrade problem you have?:no
* Operating System:Windows 10  En
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):Nginx
* Node Version:12.14.1
* MongoDB Version:4.0.12
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?Chrome 79.0.3945.88 x64

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
=no records
- *Explain steps how to reproduce*
=Swimlanes Schema：List Actions->Edit WIP Limit->Enable WIP Limit
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
=no error
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

**Comment by helioguardabaxo** [comment]
@almightyBeck 
Did you think of anything like this?

![expedite](https://user-images.githubusercontent.com/24301085/73969504-51d29300-48fa-11ea-826b-f3488b5039ab.png)

**Comment by helioguardabaxo** [comment]
@xet7 This issue may be merge with #2380?
Set WIP for each swimlane is very usefull for Kanban metodology.
Any predictions for these features?

**Comment by xet7** [comment]
Moved to #2380
