### ISSUE TITLE
Copying Wekan Database from One Server to Another

### ISSUE THREAD

**Issue by stevekiss** [wekan/wekan#2885]
Hello,

I have setup two server for Wekan, one for Production and one as a Sandbox. I am using the shell script with mongodump (https://github.com/wekan/wekan/wiki/Backup) to backup our Production database. I want to copy the Production database to our Sandbox but this doesn't appear to be working. The script executes without any problems; however, the actual data remains unchanged. I have ensured to stop Wekan via snap before doing the restore. Is there any way to do this?

Thank you.

Steve

**Comment by xet7** [comment]
What restore script you used?
What version of Linux is server running?

When you are in current directory, that has subdirectory dump that has content of previous mongodump, you should do:
```
sudo snap stop wekan.wekan
sudo snap start wekan.mongodb
mongorestore --drop --port 27019
```

**Comment by stevekiss** [comment]
I am using the script below, which is a modified version of the one in the link in my original post:

`#!/bin/bash

makesRestore()
{
    file=$1

    ext=$"$(basename $file)"
    parentDir=$"${file:0:${#file}-${#ext}}"
    cd "${parentDir}"

    printf "\nMakes the untar of the archive.\n"

    tar -zxvf "${file}"
    file="${file:0:${#file}-7}"

    version=$(snap list | grep wekan | awk -F ' ' '{print $3}')

    #restore=$"/snap/wekan/${version}/bin/mongorestore"
    restore=$"/opt/mongodb/mongodb-linux-x86_64-3.2.22/bin/mongorestore"

    printf "\nThe database restore is in progress.\n\n"

    ## Only if you get errors about existing indexes, use this below instead:
    ## $restore --quiet --drop --noIndexRestore -d wekan --port 27019 "${file}/dump/wekan"

    $restore --quiet --drop -d wekan --port 27019 "${file}/dump/wekan"

    rm -rf "${file}"

    printf "\nRestore done.\n"
}

makesRestore $1
~
`

The server is CentOS 7. 

In fact, all I did was:
`snap stop wekan
./wekan-restore.sh /media/nas1/backups/Wekan/20200116-020001.tar.gz
snap start wekan`

Do I need to explicitly stop wekan.mongodb?

**Comment by xet7** [comment]
Wekan Snap does not currently work on CentOS 7 https://github.com/wekan/wekan-snap/issues/103

**Comment by stevekiss** [comment]
Oh my goodness...

Is it only the backup and restore through Mongo that is affected or the whole system? 

What is the recommended distro with the quickest installation?

**Comment by stevekiss** [comment]
Hello,

I have migrated both servers to Ubuntu 18.04 but I continue to have the same issue. The scripts execute without error but the data is not updated. Any advice?

Thank you.
