### ISSUE TITLE
REST-api login working with LDAP?

### ISSUE THREAD

**Issue by alkemyst** [wekan/wekan#2887]
## Issue
I am not sure I am testing the rest-api correctly but I have a running instance, and I am trying to get the login for the first time.
I thought I could use an application key to login without using my username/password but I do not know where to find it. So I tried with username/password to get the authentication via rest-api:

```
baseAddress="https://something.me.com"
curl -X POST $baseAddress/users/login \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Accept: */*' \
  -d "username=myuser&password=xxxx"
```

Unfortunately I get the following:
```
{
  "error": "internal-server-error",
  "reason": "Internal server error"
}
```
(no other message appear in the logs).
I must say that all of my users are logged in using LDAP authorisation. Is there anything special I have to do to get that login? Or maybe I can get an application authorisation key from the browser?

Thanks in advance

**Server Setup Information**:
I am running on openshift with the following

|  |   |
|------------------------|-------------------------------------------|
| Wekan Version | 3.69.0 |
| Meteor version | 1.9 |
| Node version | 12.14.1 |
| MongoDB version | 3.2.21 |
| MongoDB storage engine | wiredTiger |
| MongoDB Oplog enabled |  |
| OS Type | Linux |
| OS Platform | linux |
| OS Arch | x64 |
| OS Release | 3.10.0-1062.9.1.el7.x86_64 |
| OS Uptime | 30 days, 20 hours, 23 minutes, 14 seconds |
| OS Load Average | 0.27 , 0.38 , 0.94 |
| OS Total Memory | 29 |
| OS Free Memory | 5 |
| OS CPU Count | 10 |

**Comment by paulz1** [comment]
Our WeKan is slightly older 3.40 but I confirm, we have the same problem.

1) Try to connect via curl using API to a LDAP user. And get
{
  "error": "not-found",
  "reason": "User with that username or email address not found."
}

2) Try to connect via curl using API to a local WeKan user, it works

**Comment by paulz1** [comment]
Are there something new about this issue?

**Comment by notohiro** [comment]
I have same issue with 4.10.0 :(

**Comment by ViViDboarder** [comment]
I'm having the same issue, but figured I'd also flag that this is also returning a result that isn't aligned with the API documentation which says `"error"` should be a number and not a string, eg "not-found".

**Comment by xet7** [comment]
Someone that has LDAP server and knows about what this issue is about, could submit pull request to fix it ?

**Comment by ViViDboarder** [comment]
I'd be interested in giving it a go, but I can't seem to find where the `/users/login` endpoint is handled. 

Searching for the url path I only find references to the YAML that generates the docs.

https://github.com/wekan/wekan/search?q=%22users%2Flogin%22

**Comment by xet7** [comment]
@ViViDboarder 

Wekan uses Meteor accounts:
https://docs.meteor.com/api/accounts.html

First registered Wekan user gets Admin access, and with it's username and password API can be used.

After typing LDAP username and code, login code is called here:
https://github.com/wekan/wekan/blob/master/client/components/main/layouts.js#L167

For creating new user, API is here:
https://github.com/wekan/wekan/blob/master/models/users.js#L1597

Login attempts are validated here, and at bottom of that file it calls various login methods:
https://github.com/wekan/wekan/blob/master/server/authentication.js#L10

So there are OIDC login etc here:
https://github.com/wekan/wekan/blob/master/server/authentication.js#L65

LDAP and other login packages are here:
https://github.com/wekan/wekan/tree/master/packages

Does that help?

**Comment by ViViDboarder** [comment]
Yes! Thank you.

**Comment by xet7** [comment]
Here is some Wekan development related info https://github.com/wekan/wekan-snap/issues/113#issuecomment-720263569

**Comment by magicbelette** [comment]
Hi,

If that can help, Rocket.Chat (aslo based on Meteor) successfully authenticates LDAP users through API with that kind of request :
`curl -H "Content-type:application/json" https://rocketchat_url/api/v1/login -H 'Accept: */*' -d '{ "ldap": true, "username": "user.name", "ldapPass": "passwd", "ldapOptions": [] }'`

I'll try to dig into Rocket.Chat code ti get more infos

**Comment by xet7** [comment]
@magicbelette 

Yes, some login code was previously ported to Wekan from RocketChat. Also, Wekan SAML login is not yet tested, someone porting some related code (or any other code) from RocketChat to Wekan would help too. Thanks for your help!

Unfortunately, while I have written some code related LDAP in Wekan, I have not installed or managed LDAP servers, so I don't understand all the LDAP options. LDAP code is mostly contributed by other Wekan contributors that are more familiar with LDAP.

**Comment by magicbelette** [comment]
A workaround could be to add the ability for an admin to create token for LDAP users through REST API ?

**Comment by xet7** [comment]
@magicbelette 

You could try. I don't have a way to test it, so those using LDAP could test it.

**Comment by magicbelette** [comment]
Yes, I can try but can't find a way to do it with Wekan API.

Looking for something like `/users/createtoken` (https://docs.rocket.chat/api/rest-api/methods/users/createtoken)

**Comment by xet7** [comment]
@magicbelette 

Wekan REST API code is at https://github.com/wekan/wekan at `wekan/models/*.js` . So you:
1. Add that creating token code to some existing or new file
2. Save that token to database, like having a new collection/table or new field in existing collection/table like others at `wekan/models/*.js`
3. If you need migrations for database, you can add them to `wekan/server/migrations.js`
4. Building Wekan and pull request info is at https://github.com/wekan/wekan/wiki/Emoji
5. LDAP related code is at `wekan/packages/`
6. For having something serverside at `wekan/models/*.js` or `wekan/server/*`, you can check for `Meteor.isServer()`
7. For searching for related code, do for example:
```
cd wekan
./find.sh Meteor.isServer
```
8. Also look at `wekan/server/authentication.js` for some login code

**Comment by magicbelette** [comment]
It seems pretty straightforward with meteor method :
https://github.com/RocketChat/Rocket.Chat/blob/119028b17f71df8797a46234cfee7cc6c8ee9217/app/lib/server/methods/createToken.js

**Comment by xet7** [comment]
Yes.

**Comment by magicbelette** [comment]
I've just realized that wekan API are only available for admin account, @xet7 can you confirm please or did I miss something ?

**Comment by xet7** [comment]
@magicbelette 

Yes, most of Wekan API is only for password login of Admin account. Some limited API is available for normal users.
