### ISSUE TITLE
Filter outgoing webhooks 

### ISSUE THREAD

**Issue by speendo** [wekan/wekan#2889]
## Issue

* Did you test in newest Wekan?:

Yes

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):

Docker via Docker-Compose

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):

Nginx

* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

Firefox

**Problem description**:

We configured our wekan instance to send outgoing webhooks to our Slack chat. However, the receiving channel gets floated by a huge amount of messages with minor importance, like:

> [username] CardSelected

How can we turn of outgoing webhooks for certain operations (like CardSelected)?

Thank you in advance!

**Comment by bbyszio** [comment]
I do the the same with an outgoing webhook to RocketChat. In RocketChat i wrote a script for the incoming webhook which filters the messages and deliver only the important message to the choosen channel.

**Comment by speendo** [comment]
Thank you for your reply!

I tried to do the same with slack, but it seems, that's not so easy there... or do you have an idea on how to do that in Slack?

**Comment by xet7** [comment]
@bbyszio 

Can you add as comment the code you used to filter webhook messages?

@speendo 

At Wekan wiki https://github.com/wekan/wekan/wiki right menu is various Webhooks links, for example how to turn off some Webhooks messages etc.

**Comment by speendo** [comment]
thank you @bbyszio . Maybe I am wrong, but I only found `snap` commands to turn off some webhook messages. However, I use the wekan docker image so I guess I don't have access to snap... or at least I don't know how...

Is there a way to do it in the docker-compose file?

**Comment by xet7** [comment]
@speendo 

AFAIK I have listed all the same settings at docker-compose.yml file at https://github.com/wekan/wekan

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L245

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L314

**Comment by speendo** [comment]
Thank you for your help, @xet7!

I just found, that I might have done an even bigger mistake: I pulled my docker-compose file from here:
https://github.com/wekan/wekan-mongodb

and just realised, this project is archived.

But I guess it will be enough to replace the `docker-compose.yml` in order to clear this mistake, right?

**Comment by xet7** [comment]
@speendo 

You should make [Backup](https://github.com/wekan/wekan/wiki/Backup) before any changes.

**Comment by sysadmfrds** [comment]
Same issue here. 
I tried with the docker-compose you [link](https://github.com/wekan/wekan/blob/master/docker-compose.yml#L245) ( I was using the same as @Speendo ).

extract of my docker-compose.yml
```
...
    environment:
      - MONGO_URL=xxxxxxxxxxxxxxxxxx
      - ROOT_URL=xxxxxxxxxxx
      - WITH_API=true
      - BIGEVENTS_PATTERN=NONE
      - RICHER_CARD_COMMENT_EDITOR=false
      - BROWSER_POLICY_ENABLED=false
      - CARD_OPENED_WEBHOOK_ENABLED=false

...
```
I use per board webhook settings (not the global one).


| Wekan Version |	3.73.0 |
|:---|:---|
| Version de Meteor | 1.9 |
| Version de Node | 	12.14.1|
|Version de MongoDB 	|4.2.3|
|Moteur de stockage MongoDB 	|wiredTiger
|MongoDB Oplog activé 	||
|Type d'OS 	|Fedora 30|
|OS Plate-forme 	|linux|
|OS Architecture 	|x64|
|OS Version 	|5.4.12-100.fc30.x86_64|

Please let me know if tou want more informations =)

**Comment by speendo** [comment]
So I finally managed to update my wekan docker image. My `docker-compose.yml` now also contains

     CARD_OPENED_WEBHOOK_ENABLED=false

However, I still get webhooks like

> [user] CardSelected

to my Slack chat.

Am I doing something wrong?

**Comment by mvanvoorden** [comment]
@speendo 

Same happens to me in the snap version. I ran `snap set wekan card-opened-webhook-enabled="false"` even though that was supposed to be default, but the setting is not respected.

This is the culprit:
`Meteor.startup(() => {
  if (process.env.CARD_OPENED_WEBHOOK_ENABLED) {
    Meteor.settings.public.CARD_OPENED_WEBHOOK_ENABLED = true;
  }
});`

An environment variable is always a string, so this statement is always true when the environment variable is set, even when the value is `false`

**Comment by speendo** [comment]
great, it works now! Thank you!
