### ISSUE TITLE
Export board function is not working

### ISSUE THREAD

**Issue by cattoshi** [wekan/wekan#2892]
Description: the board export is not working. It just redirects to the board list page. Cards are working.

Gif recording: [https://imgur.com/TmyENUp](https://imgur.com/TmyENUp)

Docker logs: nothing happens but I'm not sure how to enable more verbose debugging if available

```
hostname   | Presence started serverId=id
hostname   | Meteor APM: completed instrumenting the app
```

Nothing logs basically on interaction.

Version info https://i.imgur.com/vIvAGpc.png

**Comment by xet7** [comment]
@cattoshi 

What Wekan [Platform](https://github.com/wekan/wekan/wiki/Platforms) ?

I tried with Snap and Sandstorm Experimental, export board works.

If you build from source, `start-wekan.sh` has [this](https://github.com/wekan/wekan/blob/master/start-wekan.sh#L28) to enable API and export board:
```
export WITH_API='true'
```
If you after building from source with `.build-wekan.sh` option 1 install dependencies and option 2 build Wekan and then like to run meteor to get rebuilds when changing code file, use this at command line:
```
WITH_API=true meteor
```
Or run at specific port:
```
WITH_API=true meteor --port 4000
```
then MongoDB will be at next port, like 4001.
