### ISSUE TITLE
Feature Request: At Sandstorm, Import Trello attachments to Wekan

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2893]
Moved to here from https://github.com/sandstorm-io/sandstorm/issues/2906#issuecomment-576390678

From @ocdtrekkie 

You could look at https://github.com/zenhack/hello-sandstorm-oauth as an example of how to access an external API, so it should be possible to import direct from Trello via the Powerbox.

From @xet7 

If you mean Trello OAuth, that is not required at all. Import from Trello is implemented in a way that Trello JSON is copied to Wekan input form, and in that JSON is links to Trello attachments at https://trello-attachments.s3.amazonaws.com/....  that can be downloaded without any authentication. Sure it's a long complex URL. In Wekan only public board attachments can be seen without authentication, not private board images. In Wekan that same bug was fixed in 2017 https://github.com/wekan/wekan/issues/1105 .

There seems to be reply about it at Atlassian community:
https://community.atlassian.com/t5/Trello-questions/Attachments-in-Trello-are-public-or-private/qaq-p/990831

From @ocdtrekkie 

Ah, okay, so yeah, that should be fairly trivial to do then with the Powerbox. Basically, when you did the import, your Wekan grain would open up a Powerbox asking the user to allow Wekan to access https://trello-attachments.s3.amazonaws.com/ and if they allowed it, the import would work.

From @xet7 

It seems here is a complete list about what to allow:
https://help.trello.com/article/1072-configuring-your-firewall-for-trello

From @ocdtrekkie 

I am not sure how clean the user flow would be to request access to all of those. But I am doubtful all of them would be needed for an import.

**Comment by ocdtrekkie** [comment]
IMHO, a lot of people discussed the difficulty (or perceived difficulty) of apps being able to make network requests as one of the biggest pain points for Sandstorm. So I think all of us (cc: @zenhack here) would be really interested to see if you are able to make this work and what difficulties you have.

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2020-01-20 15:24:50)

>    IMHO, a lot of people discussed the difficulty (or perceived
>    difficulty) of apps being able to make network requests as one of the
>    biggest pain points for Sandstorm. So I think all of us (cc:
>    @zenhack here) would be really interested to see if you are able to
>    make this work and what difficulties you have.

+1. Give it a try, please don't hesitate to reach out if you get stuck.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
