### ISSUE TITLE
Wekan board export issue 

### ISSUE THREAD

**Issue by izadpoor** [wekan/wekan#2895]
## Issue
It seems there is an issue once I try to export a board that it has an attachment somehow.
 
I have tried the backend directly by postman by calling below Api but I got this error message 

Api url:
http://localhost:3000/api/boards/{boardid}/export?authToken=tttttttttttfsdfsdfsd

Response

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type number<br> &nbsp; &nbsp;at Function.from (buffer.js:305:9)<br> &nbsp; &nbsp;at getBase64Data (models/export.js:141:27)<br> &nbsp; &nbsp;at packages/meteor.js:306:21<br> &nbsp; &nbsp;at models/export.js:172:17<br> &nbsp; &nbsp;at Array.map (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at Exporter.build (models/export.js:167:8)<br> &nbsp; &nbsp;at models/export.js:43:24<br> &nbsp; &nbsp;at packages/simple_json-routes.js:98:9</pre>
</body>

</html>

**Comment by xet7** [comment]
First login to API as admin, using form data, to get Bearer token as API key:
https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data

Then try export:
https://wekan.github.io/api/v3.70/#export

**Comment by xet7** [comment]
Thanks for your fix ! https://github.com/wekan/wekan/pull/2898
