### ISSUE TITLE
Impossible to click or edit the title if markdown is used to add an image to title

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2900]
**Server Setup Information**:

Hi

If you add something like this as the name for a card title or a board title, it becomes impossible to edit, or click the card for details beause you keep opening the image instead.

I like that I can add an image to the titles but it would be nice if there is a way to actually function more close to the normal.

Add this as title to a card or a board. And try clicking on it.

`![Google](https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png)`

I am using Docker compose version.

```
Wekan Version 	3.71.0
Meteor version 	1.9
Node version 	12.14.1
MongoDB version 	4.2.2

```

**Comment by juliensl** [comment]
Hi gerroon, 

Actually, it's possible, but is not user friendly.
If you click in the same vertical area than the image, you are going on the image, but if you click just under the image area, you can edit your card : 

[https://www.casimages.com/i/200129114232621154.gif.html](https://www.casimages.com/i/200129114232621154.gif.html)

Could you confirm that you have the same behavior than me please ? :)

**Comment by juliensl** [comment]
And this is the same thing for boards : 
[https://www.casimages.com/i/200129114643888207.gif.html](https://www.casimages.com/i/200129114643888207.gif.html)

But, the more annoying thing for board, is that you cannot modify the image after that, because it's opening the image.

**Comment by xet7** [comment]
@juliensl 

In your future comments, please attach .gif files directly to issue. At external hosting services links to .git files etc could sometime break. I attached your .gif files to above. Thanks!

**Comment by juliensl** [comment]
Hi xet7, 

Sure, no problem ;)

**Comment by gerroon** [comment]
@juliensl

Thanks for confirming.  I was able to do real clicks  but it is  really hard and takes many clicks sometimes. I hope that xet7 does not remove this feature since it really makes things look nicer , especailly the board view and such. Hower like i mentioned it would be nice to have a way make it more user friendly at somepoint.

**Comment by xet7** [comment]
@gerroon 

It depends what all of Wekan community would like to have, all use cases of Wekan community.

When someone [does prepay some feature](https://wekan.team/commercial-support/), I will implement it to Wekan.

When someone [has spent a lot of time to make many changes to Wekan](https://github.com/wekan/wekan/pull/2907), I will fix and finish those changes and add them to Wekan.

I'm continuing to maintain Wekan, because all of you encourage me, and you send code to Wekan as pull requests.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/commit/2b26bbe78a1a2b8b427963a6c44c3853efdb737e
