### ISSUE TITLE
API Question: Is there a way to detect or trigger an action when card moves?

### ISSUE THREAD

**Issue by rptl** [wekan/wekan#2904]
Title is self explanatory. I am looking for a way to perform an external action (via API call) when a card is moved between lists.

Is there any way to achieve that?

**Comment by xet7** [comment]
Look at [wiki](https://github.com/wekan/wekan/wiki) right menu Webhooks, scroll down to see it.

For example, with per board webhook, or [Global Webhook](https://github.com/wekan/wekan/pull/2665), send card moved info to your [webhook receiver code or app](https://github.com/wekan/wekan/wiki/Receiving-Webhooks), and there decide in your code or app per message what to do. Also see [Limiting Webhook data](https://github.com/wekan/wekan/issues/2830).

**Comment by rptl** [comment]
Thanks sir.
