### ISSUE TITLE
Oauth connexion with docker

### ISSUE THREAD

**Issue by juliensl** [wekan/wekan#2908]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: **Yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? **No**
* Wekan version: **3.49**
* Operating System: **Ubuntu**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **docker**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **http no SSL**
* Node Version: **8.16.1**
* MongoDB Version: **4.0.12**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
[https://www.casimages.com/i/200129110636427857.gif.html](https://www.casimages.com/i/200129110636427857.gif.html)

- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.* **Nothing**

- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*

Wekan : 
```
Exception while invoking method 'login' { [object Object]
  message: 'Failed to get token from OIDC http://localhost:3000/oauth/token: connect ECONNREFUSED 127.0.0.1:3000' }
{"line":"392","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC http://localhost:3000/oauth/token: connect ECONNREFUSED 127.0.0.1:3000","time":{"$date":1580292167746},"level":"warn"}
```
My server : 
```
 [OAuth2Server] GET /oauth/authorize?loginStyle=popup&client_id=abTeKicuGKRDtFFqP&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1000%2F_oauth%2Foidc&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJUeHo3aHpGa2RmZ0lDYkUxTXBhM1pueENEREhJUjZ1REEydmlJOHhxQlRDIiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D&scope=openid%20profile%20email
[OAuth2Server] POST /oauth/authorize?loginStyle=popup&client_id=abTeKicuGKRDtFFqP&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1000%2F_oauth%2Foidc&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJUeHo3aHpGa2RmZ0lDYkUxTXBhM1pueENEREhJUjZ1REEydmlJOHhxQlRDIiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D&scope=openid%20profile%20email
[OAuth2Server] POST /oauth/authorize?loginStyle=popup&client_id=abTeKicuGKRDtFFqP&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1000%2F_oauth%2Foidc&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJUeHo3aHpGa2RmZ0lDYkUxTXBhM1pueENEREhJUjZ1REEydmlJOHhxQlRDIiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D&scope=openid%20profile%20email
[OAuth2Server] in getClient (clientId: _myClientId_ , clientSecret: null )
[OAuth2Server] in saveAuthCode (code: a7fb2fc4408dd32325fbe76f9e58705dca46b200 , clientId: _myClientId_ , expires: 2020-01-29T10:03:17.691Z , user: { id: 'd9Q7rFnmJWJtbjh6K' } )
```

Problem description : 

Hi ! 
I'm trying to configure an OAuth connection using my personal Vulcan server and a Wekan docker.
I succeed to configure it with a snap wekan in production, but I not succeed with a local wekan docker.
This is my docker-compose.yml file : 
```
version: "2"

services:
  wekandb:
    #-------------------------------------------------------------------------------------
    image: mongo:4.0.12
    #-------------------------------------------------------------------------------------
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    #-------------------------------------------------------------------------------------
    image: quay.io/wekan/wekan
    #-------------------------------------------------------------------------------------
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    #-------------------------------------------------------------------------------------
    ports:
      - 1000:8080
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      #---------------------------------------------------------------
      - ROOT_URL=http://localhost:1000 #   <=== using only at same laptop/desktop where Wekan is installed
      #---------------------------------------------------------------
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      #---------------------------------------------------------------
      - WITH_API=true
      #---------------------------------------------------------------
      - RICHER_CARD_COMMENT_EDITOR=true
      #---------------------------------------------------------------
      - CARD_OPENED_WEBHOOK_ENABLED=false
      #---------------------------------------------------------------
      - BIGEVENTS_PATTERN=NONE
      
      - BROWSER_POLICY_ENABLED=true

      - DEBUG=true
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=myClientId
      - OAUTH2_SECRET=mySecretId
      - OAUTH2_SERVER_URL=http://localhost:3000/
      - OAUTH2_AUTH_ENDPOINT=oauth/authorize
      - OAUTH2_USERINFO_ENDPOINT=oauth/userinfo
      - OAUTH2_TOKEN_ENDPOINT=oauth/token
      - OAUTH2_ID_MAP=id
      - OAUTH2_USERNAME_MAP=username
      - OAUTH2_FULLNAME_MAP=fullName
      - OAUTH2_EMAIL_MAP=email

      - LDAP_BACKGROUND_SYNC_INTERVAL=''

    depends_on:
      - wekandb

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
```

And my personal server redirects to **http://localhost:1000/_oauth/oidc**
In my server logs, my client secret is __null__, but I guess it's only a security things for logs.

Does anybody have the same problem with Wekan docker Oauth configuration ? 

Thank you :)

**Comment by xet7** [comment]
MongoDB 4.x does not support `--smallfiles` command line option, you should remove it, so that MongoDB would start correctly.
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L103

You can see MongoDB errors with `docker logs wekan-db`

**Comment by juliensl** [comment]
Hi xet7, thank you for the answer.

I removed --smallfiles but it doesn't work too.
And my mongodb logs are clean :'(

**Comment by xet7** [comment]
@juliensl 

I'm not sure how in Docker Wekan would access your localhost OAuth2 server. For Wekan, localhost is inside wekan-app container. Just guessing, maybe you would need to have your OAuth2 server use your PC IP address like 192.168.0.100:3000 and in your OAuth2 server and Wekan docker-compose.yml OAuth2 server address. Or alternatively, add your OAuth2 server as docker container to your Docker network in docker-compose.yml, where wekan-app and wekan-db already are.

**Comment by juliensl** [comment]
Good remark @xet7 

I think that doesn't have problem to deal with localhost, wekan succeed to reach my server on localhost:3000, I can see and interact with my OAuth login interface from Wekan.
Same, I think that my server is founding wekan, because I don't have any "Error_redirect_url" when I start the login protocol :thinking:

**Comment by xet7** [comment]
@juliensl 

Are your settings same on Snap and Docker? You see Snap settings with:
```
sudo snap get wekan
```
For example, on Docker settings you have these, is case of username correct?
```
      - OAUTH2_USERNAME_MAP=username
      - OAUTH2_FULLNAME_MAP=fullName
```

**Comment by xet7** [comment]
Some OAuth2 example settings are here:
- https://github.com/wekan/wekan/wiki/OAuth2
- NextCloud https://github.com/wekan/wekan/pull/2897/files
- https://github.com/wekan/wekan/wiki/Azure

**Comment by juliensl** [comment]
Hi Lauri, 

Same config : 

```
Key                       Value
debug                     true
oauth2-auth-endpoint      oauth/authorize
oauth2-client-id          __MyClientId__
oauth2-client-secret      __MyClientSecretId__
oauth2-email-map          email
oauth2-enabled            true
oauth2-fullname-map       fullName
oauth2-id-map             id
oauth2-secret             __MyClientSecretId__
oauth2-server-url         http://localhost:3000/
oauth2-token-endpoint     oauth/token
oauth2-userinfo-endpoint  oauth/userinfo
oauth2-username-map       email
port                      2000
root-url                  http://localhost:2000
with-api                  true
```
I've both _client-secret_ and _secret_, I don't know why, but I've try with this two environment variables in the docker config file and it doesn't work too.

When I'll have time, I'll try with a rocketchat instance as an Oauth server, but I'm pretty sure that this is another problem :thinking:

**Comment by xet7** [comment]
@juliensl 

I don't know how your Vulcan server works.

Previously when I tried RocketChat and Auth0, they did work.
