### ISSUE TITLE
Bug - Numbered items in checklist

### ISSUE THREAD

**Issue by Rahmanism** [wekan/wekan#2909]
## Bug

When I add items in a checklist, starting with a number and a dot, it'll be shown as 1.  

Example:  
```
1. item 1  
2. item 2  
3. item 3
```  

will be shown as:  
```
1. item 1  
1. item 2  
1. item 3
```  

When I click on any item to edit, the text is correct (e.g.: 2. item 2), but after pressing Enter or ESC button it's like before again (1. item 2)!

Wekan version: 3.73.0  
Node version: 8.17.0  
MongoDB version: 3.2.22  
OS: Ubuntu 19.10 - kernel 5.3 - x64

**Comment by xet7** [comment]
Moved to #1421
