### ISSUE TITLE
List archive don't work

### ISSUE THREAD

**Issue by simahao** [wekan/wekan#2910]
## Issue
Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?:no
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?yes
* Wekan version:3.71
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:redhat6.6
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:4.0.12
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?chrome79

**Problem description**:
- *REQUIRED: when use list archive command,list don't disappear immediately like card or board archive.

**Comment by xet7** [comment]
For me, in Wekan v3.73 when I click Archive List, it archives list immediately.
