### ISSUE TITLE
Help CAS authentication

### ISSUE THREAD

**Issue by ABertinetti** [wekan/wekan#2912]
Hello,

I installed the snap version of wekan on an ubuntu 18.04 and I have a problem with CAS authentication. I looked for how to activate it because after what I saw in the packages, it is already installed on the machine.

Do you know how I can activate and configure it?

Thank you for your help.

**Comment by xet7** [comment]
@ABertinetti 

See #1760 and #620 do they help.

There could be some settings missing from Snap version of Wekan #2166. Those could be added by anyone with pull requests to:
- [wekan/snap-src/bin/config](https://github.com/wekan/wekan/blob/master/snap-src/bin/config)
- [wekan/snap-src/wekan-help](https://github.com/wekan/wekan/blob/master/snap-src/bin/wekan-help)

If there is some settings missing from Docker, those could be added by anyone with pull requests to:
- [wekan/Dockerfile](https://github.com/wekan/wekan/blob/master/Dockerfile)
- [wekan/docker-compose.yml](https://github.com/wekan/wekan/blob/master/docker-compose.yml)
- [wekan/torodb-postgresql/docker-compose.yml](https://github.com/wekan/wekan/blob/master/torodb-postgresql/docker-compose.yml)

You could also come to [Wekan Community](https://community.vanila.io/wekan) and discuss with community member `@lyon2-university` that also would like to have CAS working, and offered some testing server to me.

Unfortunately I have not used CAS, so it would require help from Wekan community to get CAS working.

Thanks!

**Comment by xet7** [comment]
Current [Wekan CAS package code is here](https://github.com/wekan/wekan/tree/master/packages/wekan-accounts-cas) and [CAS login code is here](https://github.com/wekan/wekan/blob/master/client/components/main/layouts.js#L141).

**Comment by xet7** [comment]
[CAS was added to Wekan here](https://github.com/wekan/wekan/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+CAS).

Or alternatively, if someone would like to sponsor my time checking and testing this, and adding required support, it's possible by paying 300 euro [at my Commercial Support page](https://wekan.team/commercial-support/).

**Comment by qmercier** [comment]
Hello, 
Any update for the CAS login ? I d like to use it as well, and i could not manage to make it work... is it included in last version of wekan snap or docker ?
Thanks,
Kind regads

**Comment by xet7** [comment]
Moved to #3204
