### ISSUE TITLE
doc improvements in README.md

### ISSUE THREAD

**Issue by madhums** [wekan/wekan#2913]
I think one of the first things that anyone does when visiting a repository is checkout how to set up the application. Is there any possibility to add this to the readme? I think this will improve user experience.

First I saw the readme, couldn't find anything related to "How to setup an instance", then went to the website, also couldn't find anything, was redirected to the wiki. Then from "Getting started" I was redirected to [Install](https://github.com/wekan/wekan/wiki/Install-and-Update), which again redirects me to [Platforms](https://github.com/wekan/wekan/wiki/Platforms). The Platforms page then lists a lot of things which I haven't heard of, eventually felt giving up.

I tried to deploy to [heroku](https://github.com/wekan/wekan/search?q=heroku&type=Issues) but unfortunately that doesn't work either. 

Shouldn't setting up a new instance be as simple as clone the repo, `npm install && npm start`?

Thought I would share my experience so that we can make the docs better in setting up.

**Comment by madhums** [comment]
I still do not understand how to set this project up on my local after reading here https://github.com/wekan/wekan/wiki/Platforms

**Comment by xet7** [comment]
@madhums 

Try this: https://www.youtube.com/watch?v=rDXcuV-_cFo

That IP address is the one of your own laptop, for example 192.168.0.100, you can see it with command `ip address`.

**Comment by madhums** [comment]
Thank you for the link @xet7, but I am a mac user and I don't understand why I'd need snapd etc. 

My point being, the docs should contain dead simple instructions on setting up and running the application. Is this possible without changing shell scripts etc? 

I see in some files you are running `node /build/main.js` but not really able to figure out how to run a build.

**Comment by xet7** [comment]
@madhums 

I updated Mac docs, try bundle install: https://github.com/wekan/wekan/wiki/Mac

In general, there are many ways to install Wekan, lots of wiki pages, and also 2 other unfinished documentation efforts started by Wekan community:
- https://github.com/wekan/wekanhow
- https://github.com/wekan/wekan-doc

Contributions to Wekan documentation are very welcome! You can send pull requests to those documentation repos.
