### ISSUE TITLE
1) Bug: Moving Due Date in Calendar creates duplicate. 3) Feature Request: Wekan-wide Show on Card (was, fixed: 2) Due date is not created nor changed, when cards are moved in the calendar view.)

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#2917]
I just tested the new features in version 3.74: 
- It is really nice to turn off and on all the visible items on a card. Makes it much more adaptable for our needs and easier to use! +1
- Side-Effect: I would like to use cards only with a due date. (I make start, end, and received dates invisible): When I move this card due date in calendar view (I tried to move the due date from 17h to 10:30h), it doesn't move the due date but creates start and end dates in the card, that are not visible on the card, just in the mini view. I added some screenshots for explanation. 
![Bildschirmfoto 2020-02-05 um 11 04 46](https://user-images.githubusercontent.com/1153741/73831908-67b35b80-4807-11ea-946b-947fc6334c2e.png)
![Bildschirmfoto 2020-02-05 um 11 04 35](https://user-images.githubusercontent.com/1153741/73831910-684bf200-4807-11ea-8b6e-c8b3c1c4c3ce.png)
![Bildschirmfoto 2020-02-05 um 11 04 25](https://user-images.githubusercontent.com/1153741/73831912-68e48880-4807-11ea-9bf7-f83606fc65e9.png)
- Could it be possible to make this options not only board-wise, but Wekan-wise? (Maybe we wait for that option, if everything works :) )

**Comment by saschafoerster** [comment]
And comments don't work anymore as described in #2918 and #2919. I tested it in docker with  - RICHER_CARD_COMMENT_EDITOR=false set on false and commented out.

**Comment by xet7** [comment]
I have not made any changes to calendar yet. This feature only hides some parts of card.

**Comment by DimDz** [comment]
for (2), on my testing I changed `card.setStart(event.start.toDate());` to `card.setDue(event.start.toDate());` and fixed it. I don't use start and end dates, just due dates.

**Comment by xet7** [comment]
@DimDz 

Please send PR, like https://github.com/wekan/wekan/wiki/Emoji

**Comment by DimDz** [comment]
> 

Sadly I don't know how to send PR and cannot understand the instructions mentioned at the link you provided. The only code I changed was the above.

**Comment by xet7** [comment]
@DimDz 

To what file you made changes? Please attach that changed file in .zip package to comment of this issue. WeKan files are listed at https://github.com/wekan/wekan . Thanks !

**Comment by xet7** [comment]
It seems I found it, `wekan/client/components/boards/boardBody.js`. I'll try.

**Comment by DimDz** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/70445835/188429807-cc9cea6a-4d68-49cc-ba91-25ada7afa1f5.png)

**Comment by xet7** [comment]
Hmm, did I make wrong change?

**Comment by DimDz** [comment]
> 

No, it is like mine.

**Comment by saschafoerster** [comment]
@xet7 Cool. There more I follow this, the more I understand about programming. It's really nice that is was just this small change. Looking forward testing it! Thanks @xet7 and @DimDz

**Comment by saschafoerster** [comment]
I tested and it worked as expected for me. Another issue closed. Thanks to @DimDz and @xet7
