### ISSUE TITLE
Can't write comments anymore (v3.74)

### ISSUE THREAD

**Issue by H4usi** [wekan/wekan#2918]
Hi,
since today i can't write any comments under my cards. Everything else is working. I think snap did an update to the latest version (v3.74). 

In Chrome (v80) and Firefox (v72.02) it just reloads the website if i send a comment. Only Edge is working. I tried a fresh chrome/firefox profile and another PC but it does not fix it. 

Maybe it has something to do with the "RICHER_CARD_COMMENT_EDITOR=" change in version 3.74. How can i revert this change to test it?

Thanks
Andre

**Comment by warnt** [comment]
I have the same Error plus can't enable or disable comments in "Card Settings".
The label Description is also missing.

Thanks 
Danny

**Comment by adminschb01** [comment]
same probleme even after reactivating the richer card comment editor using:
sudo snap set wekan richer-card-comment-editor='true'
the comments are not persisted

**Comment by GAm7** [comment]
the same

**Comment by xet7** [comment]
Thanks for testing! I will fix this, it will be ready today (or tomorrow).

**Comment by e-stonia** [comment]
I see this is closed but didn't find how to fix the issue.
