### ISSUE TITLE
Commenting cards is not possible on 3.74 version

### ISSUE THREAD

**Issue by adminschb01** [wekan/wekan#2919]
after an automatic update to 3.74 version of a wekan snap installation on ubuntu 18.04, the commenting is not possible, even after reactivating the richer comment editor using:
sudo snap set wekan richer-card-comment-editor='true'

clicking on the comment button will make the page to refresh and the comment is not persisted (lost).

**Comment by saschafoerster** [comment]
See #2918.

**Comment by xet7** [comment]
Moved to #2918
