### ISSUE TITLE
Feature Request: Rule Template or copy rules

### ISSUE THREAD

**Issue by steep-nb** [wekan/wekan#2924]
In out board we have a great list of rules. Now we want to start some more boards and every board should have the same rules.
It would be great if you could copy all rules from one board to another or set a template with a bunch of rules, which you can import in every board you want.

**Comment by Kytie** [comment]
I second this request, when creating a template board and adding even just 10 rules to it, having to then recreate these 10 rules on all boards created using this template is frustrating to say the least.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3458
