### ISSUE TITLE
Feature request: Sorting

### ISSUE THREAD

**Issue by enoch85** [wekan/wekan#2927]
Thanks for a great project!

It would be nice if you could make it possible to sort the cards in a list ascending and descending, based on name and due date on the card. :)

**Comment by pesc89** [comment]
Hello,  we use Wekan as a customer file. For the customers recurring tasks (cards) occur. For us it would also be practical to be able to sort the lists of cards according to their due dates.

**Comment by Paraidomat** [comment]
See #995.

**Comment by enoch85** [comment]
OK, let's close this then, in favor of the other issue.
