### ISSUE TITLE
not able to download pdf attached files on firefox and safari

### ISSUE THREAD

**Issue by jcj74** [wekan/wekan#2928]
We have been running a wekan-mongodb docker composition, with the master quay.io/wekan/wekan image, since 1 month on a CentOS 7 virtual machine.

We created some boards, cards and have added some pdf attachments.

With Chrome or Edge, no problem to download the pdf files.

With Firefox, all pdf files are downloaded as tempfix files (tested with a lot firefox versions - 61 to 72 - on Windows 7, 10, Ubuntu 18 and CentOS 7),
With Safari, they are downloaded as tempfix.dms files (tested on 10.15 IoS

**Comment by xet7** [comment]
@jcj74 

Please update to newest Wekan. When I tested on newest Docker Wekan, downloading works on Firefox on Debian.

**Comment by xet7** [comment]
@jcj74 

When downloading attachment, you should click on small Download link, that is below PDF text. There is not yet PDF preview on Wekan.

**Comment by jcj74** [comment]
Thanks for your answer. Of course, I only ask for the download link and not a preview function.

According to what you said, I saw that the last update of the wekan-mongodb composition is from march 2019. 

Do you advice me : 
- to replace the quay.io/wekan/wekan image by the wekanteam/wekan image in the docker-compose.yml file (in order to keep my mongodb image)
- or only to run the wekanteam/wekan image in stand alone (if it includes the storage by itself) ?

Thanks again for you help.

**Comment by xet7** [comment]
@jcj74 

Keep that quay.io/wekan/wekan. Do this:
```
docker-compose stop
docker rm wekan-app
docker-compose up -d
```

**Comment by xet7** [comment]
That will update Wekan.

**Comment by jcj74** [comment]
I ran the instructions you told me, plus : 
- docker images -> docker rmi xxxx (image ID of quay.io/wekan/wekan)
So the docker-compose up did a fetch of the last version : the 3.76.0 according to the admin panel

I still have the same behavior for the old attached pdf files but if I attach new files, I am able to download them with firefox, so we can assume that the bug ix fixed.

I only have to reattach my old files.

Thanks for you help.
