### ISSUE TITLE
lists archive don't work

### ISSUE THREAD

**Issue by simahao** [wekan/wekan#2929]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?:yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:3.78
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:redhat6.6
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**There are 3 Problems**:
1. Create new board and add list, then click move list to archive in list hanburger menu,the list disappear as expected, click board setting menu and select archive,the list that deleted restore immediately, i think resotred action should be executed when i click restore link.
2. After step one, i click move list to archive again, the list don't disappear as expected.
3. I archive a board, then click All board，Archive, select one board, the restored borad don't appear in board lists, i should click All board again, the restored board appear.

**Comment by xet7** [comment]
@simahao 

When I tested 1. and 2., it seems that it's only possible to archive lists that do not have attachments. I also get this error in browser inspect console:
```
Exception in queued task TypeError: "i.initialSubviews is null"
    addedAt http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:88
    nonreactive http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:60
    addedAt http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:88
    addedAt http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:78
    addedBefore http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:96
    addedBefore http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:96
    a http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:96
    runTask http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:1
    flush http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:1
    drain http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:1
    update http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:96
    update http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:116
    e http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:108
    _performWrites http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:108
    _performWrites http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:108
    _performWrites http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:108
    _flushBufferedWrites http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:108
    _livedata_data http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:108
    _livedata_data http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:386
    onMessage http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:108
    onmessage http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:106
    forEachCallback http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:106
    onmessage http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:106
    dispatchEvent http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:106
    _dispatchMessage http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:106
    _didMessage http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:106
    onmessage http://localhost/236fea4593938f00a0f492e1e2c79f65d56cfa6a.js?meteor_js_resource=true:106
236fea4593938f00a0f492e1e2c79f65d56cfa6a.js:1:6771
```

**Comment by simahao** [comment]
I get error message in brower inspect console like below:
Exception in queued task Error: Unknown id for changed: 8Fs2EtBAHYdD8r8sw
    at Object.applyChange.changed (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:96)
    at 167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:96
    at n._SynchronousQueue.t.runTask (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:1)
    at n._SynchronousQueue.t.flush (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:1)
    at n._SynchronousQueue.t.drain (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:1)
    at w.update (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:96)
    at e.r.<computed> (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:114)
    at 167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:108
    at n.EnvironmentVariable.r.withValue (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:1)
    at M.apply (167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true:108)
