### ISSUE TITLE
Linked card cannot change date 

### ISSUE THREAD

**Issue by GammaPi** [wekan/wekan#2930]
**Server Setup Information**:
* Wekan version: 3.77
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker

**Problem description**:
![Peek 2020-02-12 13-20](https://user-images.githubusercontent.com/19838874/74305323-90ed6200-4d9a-11ea-8f0b-4490e62c68ea.gif)
Linked card cannot modify date setting, you can only edit from the original borad.

Steps to Reproduce:
- Create two boards A and B add cards c in A
- link c from board A to B
- modify date in board A success
- modify date in board B fail

**Comment by Ben0it-T** [comment]
Hello again,

In models/cards.js, there is "setStart(startAt)", "setDue(dueAt)" and "setEnd(endAt)" in "Cards.helpers" and in "Cards.mutations"

I deployed a VM (Debian 10, node 12.x, mongodb 4.x) for testing from source with meteor
./rebuild-wekan.sh => Install Wekan dependencies
./rebuild-wekan.sh => Build Wekan
./rebuild-wekan.sh => Run Meteor for dev on http://localhost:4000


I made change in models/cards.js to comment "setStart(startAt)", "setDue(dueAt)" and "setEnd(endAt)" in "Cards.mutations".

This seems to do the job

**Comment by xet7** [comment]
@Ben0it-T 

Can you send pull request with your changes?

**Comment by Ben0it-T** [comment]
I will try. I'm new on wekan and I don't understand the code yet... give a couple oj hours
what's the difference between helpers and mutations ?

Looking for the received date
-> an if condition missig in /models/cards.js
-> no receivedAt in /models/boards.js

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4002
