### ISSUE TITLE
Feature Request : Filter by Card Title

### ISSUE THREAD

**Issue by lezioul** [wekan/wekan#2931]
Hi,

do you think it would be possible to filter a board using card title.
Same as search, but result directly on board (as if you filter by assignee)

Thanks

**Comment by xet7** [comment]
@lezioul 

It's not yet possible.

I don't know does somebody really think it would be so important to have, so that someone would pay 300 euro for my time to code that feature and add it to Wekan.
https://wekan.team/commercial-support/

**Comment by lezioul** [comment]
I understand.
What about advanced filters? I understand they are based on custom fields, maybe thay could also work on standard fields such as card title?
Thanks for your time.

**Comment by xet7** [comment]
@lezioul 

Advanced Filters were added by some Wekan contributor, that is mentioned in this blogpost:
https://blog.wekan.team/2018/05/wekan-v1-00-released/

Any Wekan contributor that has some programming experience with some programming language, and some free time, could also figure it out and send pull request to implement this feature.

When you test those filters and advanced filters, if it does not work yet, it needs someone to add that feature with code changes.

**Comment by lezioul** [comment]
thx.
