### ISSUE TITLE
Richer_Text_Comment - URL Hyperlink

### ISSUE THREAD

**Issue by gkarachuk** [wekan/wekan#2933]
Thanks for the great work.  Wekan is becoming indispensable for me.

Server Setup Information:

    Wekan version: 3.78
    Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap

Problem description:
Creating link in the richer text comment field creates link but clicking on link following save opens the card not the e-mail I linked to.  I'm using the link in the comment field to link back to the e-mail that prompted creating the card, the link is correct before I save it (and remains the same when I open it to edit it) but it simply reopens the card.

Steps to Reproduce:

    Create a card
    Add a link in a richer text comment
    Save card
    Open card
    Click on the link
    Opens card in an external window

**Comment by xet7** [comment]
@gkarachuk 

You could try turning off richer text editor:
```
snap set wekan richer-card-comment-editor='false'
```
And then use markdown link like this:
```
[something here](https://wekan.github.io)
```
Would it help?

@whowillcare 

Do you have time to fix richer text editor bugs?

**Comment by xet7** [comment]
Richer text editor is quite complex and a lot of code. I don't know how many Wekan users still prefer to have it. Are there any Wekan contributors that would like to spend time fixing it. I have not added it and don't know how it works.

Or alternatively, should richer text editor be removed.

**Comment by xet7** [comment]
@urakagi

What do you think about richer text editor?

**Comment by gkarachuk** [comment]
Thanks for the responses.  I had tried the markdown approach yesterday, but being new to it, I seem to have gotten the syntax wrong.  I can now create the link using @xet7 suggestion.  

Unfortunately, that link is generating the same problem.  What is now happening in the comment after reverting to the simpler, non-rich text comments?

1. Create link to e-mail using the e-mail permalink.
2. Save comment.
3. Click on link.
4. Opens Wekan card in new window.

So, still the same problem.  If I edit the comment, I can actually see the correct link, not the card link.

Interestingly, old links continue to work correctly.

Regarding the rich text edit, for me, it's overkill.  My focus has been to simply link the tasks with the e-mail, Slack, Trello, or other trigger so that it is easy to reference the context.  I don't use any of the fancy formatting, and now that I am learning a bit or markdown, don't see the need for me.

Once again, thanks for the great work @xet7 _et al_, it's a super package.

**Comment by xet7** [comment]
@gkarachuk 

When you don't need any fancy formatting, you can just add that link directly to comment, save, and it should automatically become to a clickable link.

**Comment by gkarachuk** [comment]
@xet7 

Thanks for the suggestion.  That format seems to work with URLs, but it doesn't create a clickable link to other desktop programs.  I tested it with www. addresses and that worked, but when I used a permalink from my e-mail archive, e.g., mailspring://thread?subject=SoW%203&date=1581590593, this did not create a clickable link.

The markdown version worked nicely, and I am happy to use that, but it continues to open the card in an external window, not the e-mail.  This is a new problem as it worked previously.

**Comment by S0QR2** [comment]
I have the same issue with the markdown version in current snap version.

When creating a link to a website or custom(in our case "os://1234123") after saving the card the link will always point to that card and not to link provided. When editing the comment or description the correct link is shown.

**Comment by gkarachuk** [comment]
@xet7 Is the any chance that the markdown version of the link to a local resource, e.g., "mailspring://thread?subject=connection&date=1562329389" will be corrected?  It's a great feature that is only linking to the Wekan card, not the actual link.

**Comment by xet7** [comment]
@gkarachuk 

Your issue moved to https://github.com/wekan/wekan/issues/1615#issuecomment-594485135
