### ISSUE TITLE
Card activity shows only 20 last entries

### ISSUE THREAD

**Issue by adminschb01** [wekan/wekan#2934]
## Issue
i am using wekan 3.79 snap install on ubuntu 18
and the card activity scrolls only for last 20 entries when using Google Chrome or Opera (latest versions installed). but on firefox it loads all the entries.

**Comment by xet7** [comment]
For me it works the same on all those browsers. Card shows max 20 newest comments, but if you scroll down all of sidebar activities, after that you can usually see all comments on that card. Yes, it's a bug.

**Comment by marc1006** [comment]
> For me it works the same on all those browsers. Card shows max 20 newest comments, but if you scroll down all of sidebar activities, after that you can usually see all comments on that card. Yes, it's a bug.

Does this work for you?At least I get the error
```

Uncaught TypeError: activitiesComponent.loadNextPage is not a function
    at constructor.reachNextPeak (sidebar.js:63)
    at constructor.BlazeComponent.callFirstWith (peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:660)
    at constructor.scroll (infiniteScrolling.js:28)
    at peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:469
    at Object.Blaze._withCurrentView (view.js:533)
    at peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:468
    at Template._withTemplateInstanceFunc (template.js:490)
    at Blaze.View.eventMap.<computed> (peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:467)
    at view.js:879
    at Object.Blaze._withCurrentView (view.js:533)
```
I've created a fix for it https://github.com/wekan/wekan/pull/3168

**Comment by ertanalytics** [comment]
I wanted to add to this one that it is now also happening in Firefox.  I am not finding a browser that does not hide comments after 20 comments.

**Comment by iberlob** [comment]
Good, Do we know if this problem is solved? Thank you

**Comment by xet7** [comment]
@iberlob 

This is not solved yet. I'm currently thinking should I try to find some quick fix, or do some major changes that would also fix some other bugs too.
