### ISSUE TITLE
Clearing old (or all) activity history.

### ISSUE THREAD

**Issue by iago-lito** [wekan/wekan#2935]
I find much about deleting archived items, but I've only found [this old post](https://discourse.wekan.io/t/wekan-very-slow-how-to-delete-archive-cards-automatically-to-speed-up-performance/312) about clearing up old recorded "activity history" (associated to the cards, to the boards, *etc.*)

How can I clean activity? Is there a way not to record it at all?

This is it, thank you for support, and for wekan :)

**Comment by xet7** [comment]
@iago-lito 

Problem is, activity also includes comments. So you need to be very careful you don't delete comments.

I don't know does this have some related code, please make a backup before testing:
https://github.com/wekan/wekan-cleanup

**Comment by iago-lito** [comment]
I understand. My use case involves no other people, just me, and it also does not involve comments, so it should be safe :)

I read that `wekan-cleanup` only mentions clearing activity when it comes to clearing "orphan" objects. I understand that it means I have to delete the object (card/board/*etc.*) and remove it from archive before I can get rid of its activity history, is that correct? Or is there a way to remove activity without having to remove the object?

**Comment by xet7** [comment]
## Snap

If you have Wekan Snap version, you can first count how many activities you have:
```
/snap/wekan/current/bin/mongo --port 27019
show dbs
use wekan
db.activities.count()
```
For example, my database currently has about 15049 activities.

You can delete them all with:
```
db.activities.deleteMany({})
```
Then you can count them:
```
db.activities.count()
```
## Docker
```
docker exec -it wekan-db bash
mongo
```
And then run those count etc commands like above.

**Comment by xet7** [comment]
You can exit mongo shell with:
```
exit
```
And exit Docker container with:
```
exit
```

**Comment by xet7** [comment]
Of those command, this shows what databases mongodb server has:
```
show dbs
```
And when you use some database:
```
use wekan
```
Then you can look what collections/tables it has:
```
show collections
```
And also look what content collections have:
```
db.activities.find()
```
Or alternatively you can browse those with nosqlbooster GUI.

**Comment by iago-lito** [comment]
This worked like a charm, thank you for support :)
