### ISSUE TITLE
Board export returns HTML instead of JSON

### ISSUE THREAD

**Issue by jakubgs** [wekan/wekan#2938]
## Issue

I'm running `quay.io/wekan/wekan:v3.79` Docker image with `mongo:3.2.21` and I'm trying to export a board in order to attempt the fix suggested in #1629 for the `Removed nonexistent document` errors, but when I download the JSON file the contents look like this:
```html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/bcf27c18dfcc95a51675db5046694a0d9aaba916.css?meteor_css_resource=true">
<title></title><meta name="viewport" content="maximum-scale=1.0,width=device-width,initial-scale=1.0,user-scalable=0"><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="shortcut icon" href="/wekan-favicon.png"><link rel="apple-touch-icon" href="/wekan-favicon.png"><link rel="mask-icon" href="/wekan-logo-150.svg"><link rel="manifest" href="/wekan-manifest.json">

</head>
<body>
  <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.9%22%2C%22gitCommitHash%22%3A%2284acc65d04c7269150ef144266172302ad65033d%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%22CARD_OPENED_WEBHOOK_ENABLED%22%3Afalse%2C%22RICHER_CARD_COMMENT_EDITOR%22%3Afalse%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fboards.status.im%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22autoupdate%22%3A%7B%22versions%22%3A%7B%22web.browser%22%3A%7B%22version%22%3A%2265a1d8b6cada2cf9cff1e1bd42fbeebd30bda1ef%22%2C%22versionRefreshable%22%3A%2282e76a22e7d898158fa3d7534403b0a23385ef4a%22%2C%22versionNonRefreshable%22%3A%22b330a2928bac25fabfcd7764fae88497c02dc827%22%7D%2C%22web.browser.legacy%22%3A%7B%22version%22%3A%229b6ebe04cf37568833df490f0787ad8f2e29d0cb%22%2C%22versionRefreshable%22%3A%2282e76a22e7d898158fa3d7534403b0a23385ef4a%22%2C%22versionNonRefreshable%22%3A%228f7dfcafb9fbf5f7e9c43ce3c8637297a93e4fab%22%7D%7D%2C%22autoupdateVersion%22%3Anull%2C%22autoupdateVersionRefreshable%22%3Anull%2C%22autoupdateVersionCordova%22%3Anull%2C%22appId%22%3A%22dvyihgykyzec6y1dpg%22%7D%2C%22appId%22%3A%22dvyihgykyzec6y1dpg%22%2C%22accountsConfigCalled%22%3Atrue%2C%22isModern%22%3Atrue%7D"))</script>

  <script type="text/javascript" src="/167c14aa1a85d893f892125b39bb934e9b6f0eb0.js?meteor_js_resource=true"></script>


</body>
</html>
```
Which makes zero sense.

**Comment by jakubgs** [comment]
Oh, I see, `WITH_API=true` is required for exports to work.

If it's required, shouldn't the export button be disabled if `WITH_API=true` is not set?

**Comment by jakubgs** [comment]
And import doesn't seem to work. After mapping all the users I was shown I clicked "Done" only to be greeted by this screen:
![wekan_import_fail](https://user-images.githubusercontent.com/2212681/75063600-9018a680-54e5-11ea-85d0-f1e9bfa34cae.png)
Which has no users to map and clicking "Done" again does nothing.

**Comment by jakubgs** [comment]
Related issues:

* https://github.com/wekan/wekan/issues/2861
* https://github.com/wekan/wekan/issues/2548

**Comment by xet7** [comment]
@jakubgs 

Yes, `WITH_API` is required, as described in docker-compose.yml at https://github.com/wekan/wekan

Regardless of any errors, please check it the new board at `All Boards` page.

**Comment by jakubgs** [comment]
I did check `All Boards`, it wasn't there. It was not imported.

Also, because the import was ~80MB my browser froze for a few minutes because of pasting 80MB as text into a text field on the page. Might benefit from a file upload dialog.

At least restoring everything from backups got rid of the `Removed nonexistent document` errors from my logs. So that's nice.
