### ISSUE TITLE
Better Design?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2939]
Hi,
previously I have received feedback, that I should not make too radical changes to Wekan UI, because in some companies it gets immediate negative feedback from Wekan users. It would disturb learned workflows, where to click, etc, with resistance to change.

At Wekan website https://wekan.github.io is survey. I got this one survey response:

"Better Design Please! It looks like from 2000 :-( Bad User Adaption"

But:
- Trello was created 2011
- Wekan v0.9 original design was created by Wekan original author Maxime Quandalle to be different than Trello design, because of [DMCA complaint](https://github.com/wekan/wekan/wiki/FAQ#why-does-wekan-look-so-different-now-compared-to--v09)
- I started maintaining Wekan 2016-12
- There has been many improvements to original Wekan design from 2016-12 to today.

Can someone please give examples what would be better design for Wekan? Or how Wekan Design should be improved? Without becoming exact UI clone of some other kanban software?

And, what that "Bad User Adaption" means? How Wekan could be improved so that there good or great user adaption?

**Comment by ocdtrekkie** [comment]
Business users absolutely hate redesigns. I really don’t know why one would undertake one especially for a product as complicated as Wekan.

IMHO, if you’re getting specific usability requests or issues, address them, but general feedback of “I don’t like the design” probably isn’t super actionable. Without concrete suggestions, there’s no reason to believe your design changes would make them happy.

**Comment by xet7** [comment]
@ocdtrekkie 

It's always the same thing when adding new feature or UI change to Wekan:
- if new UI is worse, and gets any negative feedback, I revert it. For example, some UI changes previosly made cards harder to see, so I reverted it.
- if new feature if broken, I fix it, or remove it and add it back, so many times until it works correctly.
- when there is any new UI or feature change, it can in some way break some other features, and it takes time to fix all corner cases.
- current Wekan with it's API etc is integrated to countless of systems wordwide. It does not make sense to break something that already works.

I think I will do only those very specific small UI and feature changes that are at Roadmap, with minimal amount of code added to Wekan. Core features of Wekan have been working for a long time, it's currently about some new features and bug fixes, not major changes.

**Comment by fjramirez1987** [comment]
Hello, a change that for me would be important and not significant is that the types of views are visible and not grouped in a submenu.

When I want to fit the "Calendar" view I have to enter the filter menu. It would be more comfortable if calendar were out.

The submenu "rules" does not make sense to me, that is within the filters menu. I would put it out.

Thanks, it's a good job!

**Comment by xet7** [comment]
@fjramirez1987 

I don't know would all those views fit to be directly visible, and not in submenu? There will probably be more views in the future.

**Comment by victordariovera** [comment]
Hi! I think is a good idea implement some changes in UI and look and feel not only to make wekan more "modern" but a little more usable. I think that some tweaks in fonts, spacing and some controls can make Wekan more eye-catching than trello. :)

Some little ideas I have now, quick ideas:

- Improve line and paragraph spacing in activity history, text feels a bit compressed. 
- Control in "hide minicard text label" in activity history view can have better animation. It's a good idea but i feel that can be improved.
- For some reason, the dark grey vertical division lines between cards columns make me feel in old microsoft excel hahaha :D Modern UI search for open spaces, eliminate that lines can help to card gain visual prominence to cards.
- In general, controls and text can be more space to gain "visual air" and looks a little more "modern."
- Sign "+" in card controls looks redundant and add visual complexity, I think can be simplified. 

Can help a mookup?
I Could make one and post it here ;)

**Comment by xet7** [comment]
@victordariovera 

Your issue moved to #1574
