### ISSUE TITLE
Swimlane for member not visible

### ISSUE THREAD

**Issue by betacarve** [wekan/wekan#2940]
Pictures speak louder than words

![grafik](https://user-images.githubusercontent.com/57710477/75324787-fd2a9400-5877-11ea-9c90-6ff1dfbd2fde.png)

![UG](https://user-images.githubusercontent.com/57710477/75324803-03207500-5878-11ea-8c76-7265ed090d76.jpg)
![J](https://user-images.githubusercontent.com/57710477/75324808-03b90b80-5878-11ea-9ee4-5c80328355df.jpg)

**Comment by betacarve** [comment]
![UG](https://user-images.githubusercontent.com/57710477/75324402-27c81d00-5877-11ea-945b-5902bc443735.jpg)
![J](https://user-images.githubusercontent.com/57710477/75324406-2860b380-5877-11ea-9e7f-51da08c44f49.jpg)

**Comment by adminschb01** [comment]
i think that every member should set BoardView to Swimlan.

**Comment by betacarve** [comment]
I see. My fault :-(

THX 👍
