### ISSUE TITLE
profile "Comment only" is able to move cards

### ISSUE THREAD

**Issue by adminschb01** [wekan/wekan#2941]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Wekan version: 3.8
* Operating System: ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): SNAP

is it normal that when the profile "Comment Only" is applied on user, that user still be able to move cards between  lists ?

**Comment by xet7** [comment]
Moved to #2951
