### ISSUE TITLE
Too big scroll amount in card

### ISSUE THREAD

**Issue by danger89** [wekan/wekan#2949]
## Issue

**OS:** Linux Mint XFCE (Desktop)
**Browser:** Firefox (but doesn't really matter, I can easily reproduce this issue in Chromium)
**Wekan version:** 3.80.0 (Dockerized)

**Problem description**:

Open Wekan, click on a board and click on a random card. This will open the card, which can contain a description.
When I want to scroll through the card, each "scroll motion" (when my mouse scrolls up/down by 1 'click') scrolls too much the card window.

Scrolling won't go in small steps, when using the mouse wheel in a card with alot of text. See video. 

**Root cause**:

> Lorem Ipsum site scrolls about 3 lines with 1 scroll "click", Wekan is the order of 9-10 lines with 1 scroll "click".

Too big scroll amount with scroll wheel. Especially, when the card size increases. 

**Proposed solution**:

Calculate the scroll amount value based on the vertical card size. 

And maybe enable smooth scrolling again (50ms). 

**Video:**

See Youtube: https://youtu.be/Ji1TN29KUl0 

Animation:
![scrolling_issue_wekan](https://user-images.githubusercontent.com/628926/75629210-3b111a80-5be0-11ea-8cba-81afd36854c2.gif)

I hope it's not too hard. If you don't understand my issue, please let me know.

**Comment by xet7** [comment]
@danger89 

Scrolling is not too fast for me.

Scrolling was fixed here, to not be slow anymore:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v356-2019-11-21-wekan-release

Speed could be made a setting, if there is a real need.

**Comment by danger89** [comment]
> @danger89
> 
> Scrolling is not too fast for me.

Did you see the video? Here you can clearly see the difference between 1 scroll step by the mouse wheel in Wekan vs a normal site.

**Comment by danger89** [comment]
OK, so I found the docs. The change you made is only related to the animation effect.
Like:

`mouseWheel:{ scrollAmount: integer }`
And maybe:

`mouseWheel:{ deltaFactor: integer }`

[According to the docs](http://manos.malihu.gr/jquery-custom-content-scroller/)

**Comment by xet7** [comment]
What would be better mount?

@cafeoh Can you also test this?

**Comment by xet7** [comment]
All components at `wekan/client/components` are permanently at Wekan repo. I don't know is there any active upstream repo for those anywhere.

**Comment by xet7** [comment]
Oops sorry, I mean at `wekan/packages/`. Not `wekan/client/components`.

**Comment by danger89** [comment]
> What would be better amount?
> 
> @cafeoh Can you also test this?

Thanks for your reply!

I try to experiment myself, using the Firefox developer console, but I don't get the behaviour changed (without changing Wekan code, until now), in my browser I try to execute, without luck:

`$(".card-details").mCustomScrollbar({mouseWheel:{ scrollAmount: 1}})`

Any ideas to debug this for me?

**Comment by xet7** [comment]
@danger89 

Newest Wekan has mouse settings:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v384-2020-03-16-wekan-release

For example:
```
sudo snap set scrollinertia='200'

sudo snap set scrollamount='200'
```
Please test is there some better value than the current one.

**Comment by danger89** [comment]
Let me check if this solves the issue.

I'm using the docker image of Wekan. Can I run that command within that image, or should I use a different approach in my case?

**Comment by xet7** [comment]
@danger89 

Here are docker-compose.yml settings:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L245-L246

After changes, do:
```
docker-compose stop
docker-compose start
```

**Comment by danger89** [comment]
@xet7 
I can conclude the following:

1. `SCROLLINERTIA` works, and can be set to a slightly more pleasing number like 40 (`SCROLLINERTIA=40`).

2. `SCROLLAMOUNT` does **NOT** work for some reason! That suppose to set `mouseWheel:{ scrollAmount: xxx}` in amount of pixels. Changing this number to 900 or 1 doesn't make any difference in Firefox. Yes, I restarted the docker images, and reloading the pages (removing cache in FF). Nothing changed. :confused: Is there a bug in your code?

3. Moreover, I don't know if something changed regarding the description field of a card. Normally, in Firefox, when editing the description of the card the height the textarea area was much bigger (almost equal to the size of the text). Now it's just **only** ~6 lines height, see screenshot:

![desc](https://user-images.githubusercontent.com/628926/77194129-a5cabd00-6adf-11ea-892a-a04088258565.png)

Again, it used to be much bigger, maybe that was/is a _feature or a bug_? I think when editing long pieces of text, this may not be sufficient enough.

4. The change regarding SCROLLINERTIA (since that works), only applies to the card. Are there different settings of the textarea fields of eg. the description field?

**Comment by danger89** [comment]
@xet7 Could you try to introduce `DELTAFACTOR` in the YML file, that then corresponds to `mouseWheel:{ deltaFactor: integer }` setting. Maybe that is the setting is what I need to get it fixed. Since `SCROLLAMOUNT` doesn't do anything in Firefox.

> Set the number of pixels one wheel notch scrolls.

**Comment by xet7** [comment]
@tborychowski @danger89 

I did fix those settings at https://github.com/wekan/wekan/commit/7e4b791c2964f4b130abbaee62ffdff1536450c4, and added deltafactor settings. Settings are here:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L245-L247

Please test this docker image, and try to find correct settings, that I could add to Wekan:
```
image: quay.io/wekan/wekan
```
That should be changed here: https://github.com/wekan/wekan/blob/master/docker-compose.yml#L122

Related is mouse scroll issues at macOS, moved to here from #3241:
- macos catalina + firefox 80
- macos catalina + firefox 81 beta
- macos big sur + firefox 80
- macos big sur + firefox 81 beta
- windows 10 + firefox 80
- windows 10 + firefox 81 beta

**Comment by tborychowski** [comment]
I checked the image that you mentioned, but it doesn't seem to make any difference to the issue I've had...

**Comment by xet7** [comment]
@danger89 

Can you test newest Wekan, is there any changes in this issue? There are now these settings:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L247-L249

And custom scrollbar has been removed in newest Wekan.

**Comment by danger89** [comment]
> @danger89
> 
> Can you test newest Wekan, is there any changes in this issue? There are now these settings:
> https://github.com/wekan/wekan/blob/master/docker-compose.yml#L247-L249
> 
> And custom scrollbar has been removed in newest Wekan.

I tried now with all **default settings** and using the latest Wekan version (4.29.0) again. And it looks like it has been solved. I don't really know how, maybe the custom scrollbar removal fixed it?

See animation (no big jumps while scrolling, like in my [first comment](https://github.com/wekan/wekan/issues/2949#issue-573426849):

![solved](https://user-images.githubusercontent.com/628926/92984860-ce8ba800-f4ad-11ea-8596-d8c119d798f3.gif)
