### ISSUE TITLE
API login (or any other request) not working

### ISSUE THREAD

**Issue by zmaren** [wekan/wekan#2952]
Board URL is https://example.com. When I go to this URL I see board installed, I can log in/register as usual, when I log in I see boards, etc. Everything works well.

But when I try to POST https://example.com/users/login (as described on REST API docs) I'm getting this error:

![image](https://user-images.githubusercontent.com/36674206/75877467-1dc69100-5e18-11ea-8adf-d433f453f923.png)

And I'm sure I'm using correct credentials.

**Comment by xet7** [comment]
I tried with newest Wekan snap, it works for me.

## Login as admin user
https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data
```
curl https://example.com/users/login -d "email=joe@example&password=topsecret"
=> bearer token like abcdefg12345
```

## List users
https://github.com/wekan/wekan/wiki/REST-API-User#example-call-2
```
curl -H "Authorization: Bearer abcdefg12345" https://example.com/api/users
=> list of users
```
