### ISSUE TITLE
node-fibers missing binary when building sandstorm version wekan

### ISSUE THREAD

**Issue by urakagi** [wekan/wekan#2957]
After updating the wekan master branch, it seems like `node-fibers` only build binaries for node 10 and 12. When I `/wekan/.meteor-spk/bundle/programs/server/node_modules/fibers/bin$ ls`:
```
darwin-x64-64        linux-x64-64-glibc  repl           win32-x64-72
darwin-x64-72        linux-x64-64-musl   win32-ia32-64
linux-ia32-64-glibc  linux-x64-72-glibc  win32-ia32-72
linux-ia32-72-glibc  linux-x64-72-musl   win32-x64-64
```
There's only 64 and 72, but `meteor-spk` uses node 8(57) so Meteor can't run. How did you build and run the sandstorm version of wekan?

**Comment by xet7** [comment]
With Node 8.x, meteor-spk 0.5.0 and `wekan/releases/release-sandstorm.sh`
