### ISSUE TITLE
About rebuild-wekan.sh changes for CentOS 7

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2958]
@JimCircadian

About your CentOS 7 changes at https://github.com/JimCircadian/wekan/commit/c66320dda44ca28c4bf11369b97791f901586608

That script has a menu where is:
1. Install dependencies
2. Build Wekan

With your next version, please add back that menu you removed, and test that script works on Debian/Ubuntu/RHEL/CentOS 7.

**Comment by JimCircadian** [comment]
Hello @xet7 

Indeed I will do! I am currently experimenting on getting the system working again after a long time away. Once I'm sure that I've got a good commit I will add to this pull request. 

Thank you!

**Comment by xet7** [comment]
@JimCircadian 

Thanks!

**Comment by xet7** [comment]
@JimCircadian

Any progress? Can you send pull request to https://github.com/wekan/wekan/pulls ?

**Comment by JimCircadian** [comment]
Apologies, the progress stalled on this after we adopted a different system. I will review the changes required again though, and make a PR
