### ISSUE TITLE
Can't click+drag to select text in card description.

### ISSUE THREAD

**Issue by sircharleswatson** [wekan/wekan#296]
Here's is a short screencast showing what I mean:

http://www.screencast.com/t/jzxLoKf4E

**Comment by mquandalle** [comment]
Hum, are you using http://try.wekan.io? This bug was supposed to be fixed in e65c79edfadb67f3859e02ae55ad75369b7ebc17 bu I forgot to publish this fix on this test instance, now it's done.

**Comment by sircharleswatson** [comment]
Yes, I was using try.wekan. good to know it's fixed. :)

**Comment by beppe9000** [comment]
Necrobugs... I am getting this with firefox on windows both on my local instance and on try.wekan.io

**Comment by xet7** [comment]
Whoa, year 2015 called it seems.

**Comment by lindhork** [comment]
Just tested this on v4.95, the problem doesn't seem to exist anymore.
