### ISSUE TITLE
Unable to Edit and Save Users

### ISSUE THREAD

**Issue by GoblinTimes** [wekan/wekan#2960]
## Issue
When clicking on Edit to change stuff on user accounts the popup shows but then when you're done and click Save, nothing happens and it doesn't save the changes.

**Server Setup Information**:
* Did you test in newest Wekan?: **Yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings? **Yes**
* Wekan version: **3.73.0**
* Operating System:
* Deployment Method(snap/docker/sandstorm/MongoDB bundle/source): **docker**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Nginx**
* Node Version: **12.14.1**
* MongoDB Version: **Shows as unknown**
* Wekan only works on the newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Chrome 80.0.3987.149**

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek* 
**Sorry couldn't get peek to work so I did a short video and uploaded to my YouTube.**
[https://www.youtube.com/watch?v=oXhvi3sA0so](https://www.youtube.com/watch?v=oXhvi3sA0so)

- *Explain steps how to reproduce*
**1. Go to wekan**
**2. Click People**
**3. Click Edit**
**4. Change any information**
**5. Click Save**
**6. Nothing happens**

- *In webbrowser, what does show Right Click / Inspect / Console? Chrome shows more detailed info than Firefox.* **Not sure what I should report from Inspect here**
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.* **See attached file below**
- *If logs are very long, attach them in .zip file* **ATTACHED**
[log.txt](https://github.com/wekan/wekan/files/4351643/log.txt)

**Comment by xet7** [comment]
You have old Wekan version.

Please upgrade to newest Wekan v3.84 this way:
```
docker-compose stop
docker rm wekan-app
docker-compose up -d
```

**Comment by GoblinTimes** [comment]
thanks

**Comment by nebulade** [comment]
Just wanted to give more input here, we usually push wekan updates within a couple of days when upstream hits. Wekan is also by far the most active project we have in our catalogue :-) 
But this issue relies in our own LDAP code here, which was initially done back when wekan did not have support for LDAP, we are revisiting this to stay fully aligned with upstream, just have to work out how to transparently migrate the user accounts to work with upstream LDAP integration.
