### ISSUE TITLE
windwos install

### ISSUE THREAD

**Issue by cxlthxx** [wekan/wekan#2961]
Meteor under Windows, error report
 While processing files with coagmano:stylus (for target web.browser):
   fs.js:457:3: ENOENT: no such file or directory, open
   '/Users/Administrator/AppData/Local/.meteor/packages/coagmano_stylus/1.1.0/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/lib/nib/flex.styl'
   at Object.openSync (fs.js:457:3)
   at Object.readFileSync (fs.js:359:35)
   at readFile (packages/compileStylusBatch/plugin/compile-stylus.js:169:36)
   at Array.map (<anonymous>)
   at processSourcemap (packages/compileStylusBatch/plugin/compile-stylus.js:189:52)
   at StylusCompiler.compileOneFile (packages/compileStylusBatch/plugin/compile-stylus.js:311:23)
   at getResult (packages/caching-compiler/multi-file-caching-compiler.js:113:32)
   at packages/compileStylusBatch/plugin/compile-stylus.js:61:30
   at
   C:\Users\Administrator\AppData\Local\.meteor\packages\tap_i18n\1.8.2\plugin.tap-i18n-compiler.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:33:40

why???

**Comment by xet7** [comment]
Currently it's possible to use prebuilt bundle with Windows version of Node.js and MongoDB.

But building with Windows version of Meteor does not work, it gives errors. It's only possible to build on WSL, Docker, or VirtualBox Ubuntu 19.04 VM.

I added more info to wiki page.

https://github.com/wekan/wekan/wiki/Windows

**Comment by cxlthxx** [comment]
It has been solved. Thank you very much. If I want to modify the code, I need to code in Windows.

**Comment by cxlthxx** [comment]
Whether such an environment can work.What I want to say is whether we can develop a wekan in Windows environment

**Comment by xet7** [comment]
@cxlthxx 

You can develop in Windows when you build on WSL, Docker or VirtualBox. Problem is, Windows filesystem is very slow.

If you install Ubuntu 19.10 or Linux Mint as dual boot, and boot directly to Linux, Wekan builds much faster. For Wekan development, you need at least a SSD disk (or NVME if available). Wekan bundle is about 60 000 files.

**Comment by cxlthxx** [comment]
Thank you very much. Wekan supports HTTP for interface calling. If I want to call the data returned by java interface, is this feasible?

**Comment by xet7** [comment]
Yes, you can call Wekan API like any other REST API with Java. More info:

https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API

There is also Outgoing Webhooks per board at board settings, and global webhooks at Admin Panel. You can receive those similarly like any other webhook in Java.

**Comment by xet7** [comment]
Also, if you have some java generated image on java webserver, you can include it to card with html img tag, like:
```
<img src="http://192.168.0.200/report.png" />
```

**Comment by cxlthxx** [comment]
Like the controller of Java, wekan can provide external services.

**Comment by xet7** [comment]
For Global Webhooks in Admin Panel, Wekan sends all events in all boards to webhook URL, like add card. Although, sending some messages for some events is not yet implemented, more could be added later.

Data is sent in [this kind of JSON format](https://github.com/wekan/wekan/wiki/Webhook-data).

You can receive webhook data in Java like this https://github.com/Esri/webhooks-samples/tree/master/java/receiver

Then for each received data, your code can read content and based on incoming data call Wekan REST API, some Java interface, etc.

Outgoing Webhooks can also go to Slack, RocketChat, NodeRED, PowerShell etc. See right menu webhook links when scrolling down wiki page https://github.com/wekan/wekan/wiki

If you call some Java interface that returns some data, you can then write that data to Wekan card with Wekan REST API.

**Comment by xet7** [comment]
Developing Wekan in WSL or VirtualBox is possible. It is not requirement to have full Linux install.

**Comment by xet7** [comment]
Another way is to ssh to some Linux server, and in screen build wekan. That can be faster than building locally.

**Comment by xet7** [comment]
You can limit webhook data like this https://github.com/wekan/wekan/issues/2830

**Comment by cxlthxx** [comment]
It's so hard. I tried to use the CentOS environment built by docker under windows. It can be said that there were still errors when compiling the source code.

**Comment by cxlthxx** [comment]
Meteor cannot be run under root user, but some nodejs plug-ins running ordinary users cannot be obtained. Amazing.

**Comment by xet7** [comment]
Build scripts are for Ubuntu/Debian. Not CentOS.

CentOS build script is not ready yet https://github.com/wekan/wekan/issues/2958

**Comment by cxlthxx** [comment]
OK, I'll try
