### ISSUE TITLE
 my images are not seen

### ISSUE THREAD

**Issue by edgarvenom** [wekan/wekan#2962]
the images on my board were no longer displayed, no image is seen

distribution centos 7

**Comment by xet7** [comment]
Did you change ROOT_URL ?

For example, from https://example.com/wekan to https://example.com ?

If URL changes, image path is wrong on MongoDB database, so you need to change ROOT_URL or edit image paths at MongoDB database.

**Comment by xet7** [comment]
It's possible to edit database with nosqlbooster.

**Comment by edgarvenom** [comment]
the base url did not change, the images just stopped responding.

restart the service only from snap, wekan & mongodb, and they were seen again

**Comment by xet7** [comment]
Is there enough free disk space?

How much RAM server has?

**Comment by edgarvenom** [comment]
my server had enough memory and space, I just had to restart the wekan service to reset them
