### ISSUE TITLE
Unable to Edit and Save Users Still

### ISSUE THREAD

**Issue by GoblinTimes** [wekan/wekan#2963]
## Issue
When clicking on Edit to change stuff on user accounts the popup shows but then when you're done and click Save, nothing happens and it doesn't save the changes.

**Server Setup Information**:
* Did you test in newest Wekan?: **Yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings? **Yes**
* Wekan version: **3.84.0**
* Operating System:
* Deployment Method(snap/docker/sandstorm/MongoDB bundle/source): **Cloudron**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Nginx**
* Node Version: **12.14.1**
* MongoDB Version: **Shows as unknown**
* Wekan only works on the newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Chrome 80.0.3987.149**

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek* 
**Sorry couldn't get peek to work so I did a short video and uploaded to my YouTube.**
[https://www.youtube.com/watch?v=oXhvi3sA0so](https://www.youtube.com/watch?v=oXhvi3sA0so)

- *Explain steps how to reproduce*
**1. Go to wekan**
**2. Click People**
**3. Click Edit**
**4. Change any information**
**5. Click Save**
**6. Nothing happens**

- *In webbrowser, what does show Right Click / Inspect / Console? Chrome shows more detailed info than Firefox.* **Not sure what I should report from Inspect here**
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.* **See attached file below**
- *If logs are very long, attach them in .zip file* **ATTACHED**
[logs.zip](https://github.com/wekan/wekan/files/4357251/logs.zip)

**Comment by xet7** [comment]
When you add new user on Admin Panel, you really should add at least email address, username and password, and not leave them empty, so that they would be editable. I have not tested adding users without those required info. Most likely you need to remove those invalid users from database users collection/table with nosqlbooster.

Admin Panel / Settings / Accounts also have some settings about is changing username etc allowed.

**Comment by GoblinTimes** [comment]
I did that and it only added the username, admin option, verified, created at date, active, authentication method. It does not save the full name, email, or password.

**Comment by xet7** [comment]
Hmm, just a moment I'll do some tests.

**Comment by GoblinTimes** [comment]
Thanks. I'm heading off to bed now so I'll check back after work tomorrow.

**Comment by xet7** [comment]
@GoblinTimes 

When I use docker-compose.yml from https://github.com/wekan/wekan and register new user, I can add user at Admin Panel and it saves all other data but not full name. Maybe there are some different settings at Cloudron?

**Comment by xet7** [comment]
I did start it locally with:
```
docker-compose up -d
```
But it could behave differently, if you have other than password login configured, for example LDAP/OAuth2 etc.

**Comment by GoblinTimes** [comment]
The problem is I don't know how to setup containers using docker to use subdomains. If I did, then I would eliminate Cloudron and use docker-compose. I have password as authentication. I don't have an option for LDAP/OAuth2. Let me try to add it to a domain I own just using docker.

**Comment by GoblinTimes** [comment]
Ok, I did a fresh install on a new domain and everything is working as it should. So that must mean there is an issue with Cloudron causing Wekan not to work properly. I'll just stick to the stand-alone installation. Thanks for all the help.
