### ISSUE TITLE
reset password link broken

### ISSUE THREAD

**Issue by michaelwemoto** [wekan/wekan#297]
When I go to reset my password I receive the email with the reset link but there is an error.

the link appears like this
http://my.wekan.server.com/#/reset-password/4J3YM-fgY6u8KcJxT2soNfx9inpN8tZVdVFebeEdcay

the /#/ after my domain name is breaking the link

Edit:
Found the issue, it's line 1767 in accounts-base.js, I removed the #/ and all is working. 
line 1767: return Meteor.absoluteUrl('#/reset-password/' + token);

I anticipate that the verify email will have the same issue... 
line 1771: return Meteor.absoluteUrl('#/verify-email/' + token);

and also enroll-account?
line 1775: return Meteor.absoluteUrl('#/enroll-account/' + token);

I can only find where to fix this after compiling the app with meteor or from a release version, where should I be looking to fix this when I do a git clone?

**Comment by jseadragon** [comment]
+1

**Comment by mquandalle** [comment]
I’ve spend a good amount of time trying to fix this but I was unable to find the cause. The email (and all users accounts related stuff) is actually handled by the `useraccounts` set of Meteor package. @splendido do you see an issue with the following useraccounts configuration: https://github.com/wekan/wekan/blob/e92f67f1910a0a3bc40b85436a89e7d55a04a615/client/config/accounts.js

**Comment by splendido** [comment]
The file content seems fine @mquandalle...
...the problem is it's under the client folder ;-)

See [the configuration section](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api) where I say:

> **The only other requirement is to make exactly the same calls on both the server and the client.**

**Comment by splendido** [comment]
In any case, for route configuration it is now better to ensure calls to `UserAccounts.configureRoute` come after FR configuration.

See for example the standard configuration of AT options [here](https://github.com/meteor-useraccounts/boilerplates/blob/master/bootstrap-flow-router/lib/config/at_config.js) put into `lib/config/at_config.js` and the routes configuration [here](https://github.com/meteor-useraccounts/boilerplates/blob/master/bootstrap-flow-router/lib/router/routes.js#L37-L42) into  `lib/router/routes.js` after other FR stuff.

Hope this can help!

**Comment by mquandalle** [comment]
Thank you for the help, I wouldn’t have find that myself! I’m going to fix that.

(@dferber90 I know that meteor-linter does some static analysis to prevent calls on the wrong client/server environment. Could it work with third parties libraries like useraccounts?)

**Comment by dferber90** [comment]
It could in theory, but adding and maintaining the rules for many packages is a lot of work. Maybe a plugin system could be built for this. Either they could be their own ESLint plugins or they could be plugins for ESLint-plugin-Meteor, because there's some extra-work done in ESLint-plugin-Meteor to determine where code statements are going to run that could be reused across these plugins.
