### ISSUE TITLE
Browser always reload the whole page when I change one of the card color

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2971]
Does any find this issue and is it a bug?

thanks.

**Comment by xet7** [comment]
@javen9881 

Do you have newest Wekan?

What platform (Snap/Docker/Sandstorm/UCS/Source) ?

**Comment by javen9881** [comment]
both in Docker(windows version) and windows(running by start-wekan.bat)
I tried with different version like 2.6*, 3.6* and 3.85. all of them have this issue.

**Comment by xet7** [comment]
@javen9881 

What webbrowser you have?

**Comment by xet7** [comment]
@javen9881 

Please add gif video about how that happens.

**Comment by xet7** [comment]
@javen9881 

Have you set ROOT_URL correctly?
https://github.com/wekan/wekan/wiki/Settings

**Comment by javen9881** [comment]
Thanks @xet7 
I am surprised when saw these msg. thanks for your attention.
