### ISSUE TITLE
IFTTT: Move-to-top makes the card jump to the first list

### ISSUE THREAD

**Issue by adee** [wekan/wekan#2978]
Wekan Version: 3.86.0; snap

We have a rule to move a card to the top of the list if a certain label is added. Now the button to set the rules is gone. The card moves to the first list in swimlane view when a label is added. This is definitely related to the IFTTT; only the label with the rule causes this.

Where is the button? Is this functionality deprecated? How can I remove the rule to stop this?
![image](https://user-images.githubusercontent.com/680052/78005717-402acc00-733c-11ea-9228-18dc16ac072d.png)

**Comment by xet7** [comment]
@adee 

Rules are at Swimlanes/Lists/Calendar/Rules dropdown.

**Comment by adee** [comment]
> @adee
> 
> Rules are at Swimlanes/Lists/Calendar/Rules dropdown.

Thanks. But there is a legitimate bug here. The card is not supposed to change lists. Only jump to the top of the current one. This used to work.

**Comment by xet7** [comment]
In newest Wekan, Rules button is at Board Settings.

**Comment by marc1006** [comment]
@adee Seems to be the same problem as described in https://github.com/wekan/wekan/issues/3107.

I've posted a fix for it in: https://github.com/wekan/wekan/pull/3109.
