### ISSUE TITLE
Does anyone know which free mailbox with its smtp works for Wekan board?

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2981]
Does anyone know which free mailbox with its smtp works for Wekan board?
I tried the Tom.com, 126.com... none of them workes.
I tested both in Docker(WIN10) and Windows wekan with EDGE

**Comment by javen9881** [comment]
![捕获](https://user-images.githubusercontent.com/46272743/78148081-fe4a7480-7466-11ea-899f-cf09d673e359.PNG)
my settings:
SET MONGO_URL=mongodb://127.0.0.1:27017/wekan
SET ROOT_URL=http://192.168.50.138/
SET MAIL_URL=smtp://Whiteboard:131313jz@smtp.tom.com/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false
SET MAIL_FROM=Whiteboard@tom.com
SET PORT=80

**Comment by daniel-eder** [comment]
We are using MailGun, not entirely free, but effectively free for this purpose ($0.80 / 1000).
SendInBlue should work as well, and they offer 300mails/day for free.
