### ISSUE TITLE
Improvements on card details items

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#2986]
My suggestions:
- Separate items with "hr" HTML tag:
-- First line: "Received", "Start", "Due" and "End"
-- Second line: "Members", "Assignee", "Requested by" and "Assigned by"
-- Third line: Custom fields 
-- Fourth line: Labels (class card-details-item card-details-item-labels could have  
"max-width" more than 48%)

- put space between icon and title in "Description", "Checklists", "Subtasks" and "Attachments"

Looks like this:
![Screenshot_2020-04-03 Kanban -(3)](https://user-images.githubusercontent.com/24301085/78415816-a9d7fe00-75fa-11ea-9874-b44da507ceb3.png)

**Comment by FuXXz** [comment]
That would be a dream. So much potential is wasted on trifles.
Usability and layout is important!

It is currently a bunch of mixed values. Nobody can look through it.
If you use all values, it looks like so:
![1](https://user-images.githubusercontent.com/9010594/78455944-4bb22600-76a1-11ea-9164-0aaac90e8d78.png)

The Same for the Overview
![2](https://user-images.githubusercontent.com/9010594/78455990-9a5fc000-76a1-11ea-801d-be35db92651b.png)

**Comment by FuXXz** [comment]
The next point is the color of the cards.
Most colors destroy the layout, it would be better to place the card colors more discreetly on the side. not full background.
![grey](https://user-images.githubusercontent.com/9010594/78457130-51f7d080-76a8-11ea-9193-704f7e3d10c2.png)
![yellow](https://user-images.githubusercontent.com/9010594/78457132-5623ee00-76a8-11ea-8dd2-dfba1f2cf224.png)
![red](https://user-images.githubusercontent.com/9010594/78457133-56bc8480-76a8-11ea-9a30-36d930ba448d.png)

It would be better as in the following picture to avoid broken layouts
![better color](https://user-images.githubusercontent.com/9010594/78457243-1f020c80-76a9-11ea-9d3a-fc61235661ff.png)

**Comment by helioguardabaxo** [comment]
One way could be use selected color with border left in minicard and border bottom in card details.
![Screenshot_2020-04-04 Kanban -(4)](https://user-images.githubusercontent.com/24301085/78460542-148b4700-7698-11ea-834f-b9aed7184b72.png)

![Screenshot_2020-04-04 Kanban -(5)](https://user-images.githubusercontent.com/24301085/78460545-1bb25500-7698-11ea-92ac-2a1029b9939a.png)

**Comment by helioguardabaxo** [comment]
Why not modify the color palette?

How about that?
![PaletaWekan](https://user-images.githubusercontent.com/24301085/78460659-feca5180-7698-11ea-930e-040567977a75.png)

  card-details-green   #309400 #3cb500 #56d818 #77de45
  card-details-yellow  #c3a900 #fad900 #ffe437 #ffea62
  card-details-orange  #d37b00 #ff9f19 #ffb246 #ffc470
  card-details-red     #d71c1c #eb4646 #ff6e6e #ff9898
  card-details-purple  #920cd2 #a632db #b656e3 #cb83ed

  card-details-blue    #005b91 #0079bf #03a1ff 
  card-details-sky     #00879a #00c2e0 #03e0ff 
  card-details-lime    #2edd7f #51e898 #7af1b1 
  card-details-pink    #ff4db9 #ff78cb #ffa8dd

**Comment by FuXXz** [comment]
I can understand that some changes are valued differently. What person 1 thinks is good, person 2 thinks bad. Then there is trouble again. 
You should get rid of static options. Why a pallete when a small field solves all problems?
![Anmerkung 2020-04-04 231001](https://user-images.githubusercontent.com/9010594/78461488-a3fd1e00-76c9-11ea-94fd-6713e71ea1b4.png)

**Comment by helioguardabaxo** [comment]
This is a good idea! Static options + custom color are a complete solution.
This don't resolve the problem with badges contrast color, but the user can opts for multiple colors in the card.

**Comment by brianrc** [comment]
It's so cluttered. Most all these items need to be moved over to the card menu. They are not used that often. 

The card should be focused around the description and comments. All the other elements are visual ciaos. See Trello and how other Kanban boards do it. The comments could use some more breathing room too (padding).

**Comment by FuXXz** [comment]
@xet7 has already tried a little bit, Issue #1574 at https://github.com/wekan/wekan/issues/1574#issuecomment-609095074

And you need this basic informations of Dates, labels and other fields.
The suggestion from helioguardabaxo about the lines and "hr" tags is nice.

trello and others are successful with it and are accepted.
You can also decide for yourself. Wekan does everything right here
![Anmerkung 2020-04-11 133217](https://user-images.githubusercontent.com/9010594/79042546-02aa2680-7bf9-11ea-8e8c-b1a8012bd54d.png)

**Comment by helioguardabaxo** [comment]
It's a great idea!
You could also have the option to select which elements to show on the minicard, just like it works in the custom fields.

**Comment by brianrc** [comment]
@FuXXz True and that's a great feature, but it disables them completely. I'm saying all those options should be out of view unless in actual use.  

You shouldn't have to scroll down in order to see the first comment. How is that productive when 95% of the time your opening the card to read the comments?

**Comment by xet7** [comment]
Moved to #1574
