### ISSUE TITLE
Send email or notification to newly assigned assignee

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2987]
I don't know does this exist yet, someone could check.

**Comment by bbyszio** [comment]
Hi @xet7 , i've checked it with the current snap version. There ist no notification if i add antother user to a card. The user receive only a system notification if he set the tracking or watching option on the board.

**Comment by marcungeschikts** [comment]
> Hi @xet7 , i've checked it with the current snap version. There ist no notification if i add antother user to a card. The user receive only a system notification if he set the tracking or watching option on the board.

Hello, we have noticed that even when **Tracking** is set on the board , there is no notification to the newly user assigned (it works only when **watching** is set).
Is it a bug? 
Do I create a new issue?

**Comment by xet7** [comment]
@marcungeschikts 

If it's not yet mentioned at #2026 , add to that issue comment as reminder to implement it too.

**Comment by xet7** [comment]
Moved to #2026
