### ISSUE TITLE
Switching to React

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#299]
Wekan currently use Blaze as its view layer, a library written by Meteor Development Group that aims to be easy to use for developers. I've been considering replacing Blaze by React for a few months now, and except the migration cost I can see a lot of advantages in doing so:
- Have a clean component API (I currently use blaze-component, which makes things less worse than “vanilla”-blaze and will facilitate the switch to react);
- Embrace the React eco-system which is very prolific in great tools, library, and components. I'm especially interested in [react-dnd](https://github.com/gaearon/react-dnd) ([great demo](http://cdn.rawgit.com/chenglou/react-motion/master/demos/demo8/index.html)) because I already spent too much time fighting with jquery-ui, sortable, and others;
- Functional programming, I'm especially interested in composition possibility for potential plugins made by the community;
- Attract React developers by being a great example of an open-source React application;
- _In the future_: React native, for native mobile applications (see #480);
- _In the future_: GraphQL and Relay integration for data fetching, as an improvement to our current DDP subscription model.

Despite the (upcoming) official React support by MDG, Meteor build system still misses a lot of requirements to facilitate this transition (imports/exports, easy npm/browserify usage, redux-like hot reloading, etc.). I'll probably need to investigate community solutions such as [meteor-react-pack](https://github.com/jedwards1211/meteor-webpack-react) or [meteor-webpack-react-kickstart](https://github.com/thereactivestack/meteor-webpack-react-kickstart).

We will probably need to run both Blaze and React components at the same time during the transition, which seems to work well with a few helpers functions. Also our templates are currently written in Jade, but the React community tend to prefer JSX, which mean that we will probably want to rewrite our Jade templates in JSX.

**Comment by nata-g** [comment]
@mquandalle ...The reasoning seems solid and with the kind of muscle Facebook has, embracing react ecosystem is the way to go, as they seem to be controlling the current popular ideas in web/mobile development and also increases the project's exposure to other React developers (as you mentioned). However, based on my understanding,  most of the packages in the meteor universe are closely tied to Blaze and I was wondering how is the impact going to be when using React?.

**Comment by mquandalle** [comment]
@nata-g Actually we don’t use a lot of packages that are tightly coupled with Blaze, and for those who are (eg `templates:tabs`) there exists better alternatives in the React ecosystem.

@AdamBrodzinski you seem to have a lot of experience with React integration in Meteor, I don’t know if you are familiar with Wekan but I'm curious if you have some thoughts to share about migrating this kind of application to React (all the current blaze code is [here](https://github.com/wekan/wekan/tree/devel/client/components), `.jade` and `.js` files weight about 4K LOC).

**Comment by mquandalle** [comment]
Yay! Facebook just launched [React Native for Android](https://code.facebook.com/posts/1189117404435352/). As a linux user I was frustrated because I couldn't play with React Native for iOS, now it become possible. Let’s try to build a native Wekan app!

**Comment by nata-g** [comment]
:+1:  :+1:

**Comment by AdamBrodzinski** [comment]
@mquandalle Yep! I've migrated 3 apps so far. The easiest way is to start at the 'leafs' and work your way up the tree. The easiest way to render those is to use a blaze helper but you could also just use the `onRendered` callback to manually render a React node into a div.

You can pass the data that Meteor is getting into the props param of the rendered method and that will give the component the data it needs. Eventually you'll get to a point where React needs to fetch data (like components/activities) and the best way to do that is to make 2 components.. ActivitiesContainer which is only concerned about getting data and then Activities (normally) just gets props. This tends to separate concerns and makes it easier to debug.

Eventually you'll work your way back up the tree and then can attach the top nodes to a router (if wekan has one).

I would recommend this video for refactoring: https://www.youtube.com/watch?v=BF58ZJ1ZQxY

Cheers! :beers:

**Comment by bastianwegge** [comment]
Hey, we're using wekan and it's awesome! 
I'd like to take part and help out with some hours. Do you have a board or any specific planning for this?

**Comment by mquandalle** [comment]
Hi @bastianwegge, sorry I missed your message. No there is no specific planning for the migration. I feel like Meteor integration with React isn’t mature enough unless we also switch the build system (for instance with https://forums.meteor.com/t/webpack-compiler-inside-meteor-es6-modules-hot-reload-and-code-splitting/11264). I also don’t like the Meteor mixin too much and would prefer to use React stateless functional components (new in React 0.14) and have some sort of wrapper (Higher-order component) that exposes the Meteor data similarly to what Relay does.

Until this eco-system matures a bit I don’t feel super comfortable to engage this transition, but I'm confident the Meteor community will find great solutions in the following weeks. Bastian, do you have some experience with these topics?

**Comment by AdamBrodzinski** [comment]
@mquandalle you could wrap the meteor mixin into a higher order component that has a similar API to Redux but uses the mixin to sideload for ease of use. I started tinkering with something like this but moved on to using just Redux once I ran out of time:

```
let Post = function Posts(props) {
  return (
    <div>
      <div className="title">{props.title}</div>
      <div className="desc">{props.desc}</div>
    </div>
  )
}

// stateless comp.
let Posts = function Posts(props) {
  return (
    <div>
      { props.posts.map(doc => {
         return <Post ...doc />
      }) }
    </div>
  )
}
Posts = fetchMeteorData(Posts, {
  subscribeTo: 'allPosts',
  fields: {posts: {desc: 1, title: 1}}, // passed into subscribe
  mapToProps: () => {
    let docs = db.posts.find({}, {sort: {title: -1}});
    return {
      posts: docs,
    }
  }
})
```

**Comment by nata-g** [comment]
@mquandalle check this: https://forums.meteor.com/t/next-steps-on-blaze-and-the-view-layer/13561

There seems lot of discussion in regards to using React in Blaze 2 (either as templates on top or pure jsx).  My guess is MDG is going to integrate React in Blaze ASAP so that they can use Galaxy to host react based apps?  Wondering about your thoughts on this issue with reference to Wekan? Do you think we should start thinking of migrating as well ?

**Comment by nata-g** [comment]
@mquandalle  I guess on reading it more clearly, MDG is replacing blaze with React and adding template support on top of React and some migration layer for an upgrade path. This would change the whole Front end development of meteor. Interesting!!!  Thoughts????

**Comment by floatinghotpot** [comment]
@mquandalle After implemented the features of email inviting, mobile web and notification, building a native Wekan app might be the most attractive idea. Will follow up this topic, and see if I can contribute a cent or not.

**Comment by floatinghotpot** [comment]
Here I see an experimental demo, FYI:
https://github.com/hharnisc/react-native-meteor-websocket-polyfill

**Comment by mquandalle** [comment]
@floatinghotpot Your level of enthusiasm is contagious! I would be delighted if you get to contribute to a native Wekan application. I played with React Native back when Facebook released the Android support, it was a bit difficult to set up on my Linux computer but after I got it up and running the developing experience was exceptional I really feel this is the best way for us to write a native application in 2016.

To keep things organized let’s talk about React Native apps in #480 (which would probably start on a separate repository based on one of the react native starting kit), and keep this thread about the transition to React for the web client.

**Comment by mquandalle** [comment]
I also want to share that I’m super excited about @arunoda’s [Mantra](https://voice.kadira.io/sneak-peek-mantra-7161624acaa7) (early example [here](https://github.com/kadira-samples/mantra-demo)) and as we migrate to React I’ll try to stick with as much Mantra principles as possible.

**Comment by mquandalle** [comment]
Just want to add yet another important argument in favor of the soon to come migration to React, and that is the possibility to compose UI component that is very valuable for a desired plugin system. I wrote about it [on the forum](https://discuss.wekan.io/t/rfc-the-plugin-system/132).

**Comment by Asara** [comment]
Just curious if this is still in planned.  :+1:

**Comment by nchauvat** [comment]
Hi. As a user of Wekan, I would be interested in a move towards React. Do you know about https://github.com/bigardone/phoenix-trello ? Maybe some cross-pollination could bootstrap the transition?

**Comment by mquandalle** [comment]
One of the non-trivial part of the Blaze-to-React transition is the card drag and drop feature. From looking at their respective code and documentation, React Dnd has a better design and API than Jquery UI sortable. However I’ve yet to see a Wekan-like kanban written with it and there always were some quirks in the demos I’ve seen.

Does anyone know a good demo of card + column ordering using React Dnd?

**Comment by nchauvat** [comment]
http://blog.tryolabs.com/2015/04/30/building-a-kanban-app-in-react/ maybe ?

**Comment by nata-g** [comment]
@mquandalle  how about apollo stack update or is it too soon. I was recently reading  the  docs at http://docs.apollostack.com/ and going over the apollo client (for which you are the contributor) and was wondering  wekan is perfect for apollo + Mantra, now that there is little less confusion in the meteor world. My 2 cents.....

**Comment by mquandalle** [comment]
@nata-g Yes, that's actually the idea. I plan to write on the stack I plan to use for the Wekan rewrite.

**Comment by nata-g** [comment]
@mquandalle that would be awesome . Let us know the stack and high level design of Wekan rewrite. May be I can be active contributor this time....

**Comment by nata-g** [comment]
BTW @mquandalle just curious to know if have you decided which approach you plan to use for rewrite - One-on-One mapping of the existing functionality or something that is being discussed here https://discuss.wekan.io/t/abtract-lists-into-a-generalized-task-meta-data/121

**Comment by mquandalle** [comment]
The underlined data model will be the one described in the above topic. However with the default set of modules installed the UX will be similar to what we currently have.

**Comment by nata-g** [comment]
@mquandalle  Sounds good. You know I was just reading the discourse topic again after a long break. Initially I was little opposed to the idea but now I am seeing the point. I can see the benefit of the new data model and how it can be useful. Now I am looking forward to playing with the app using the new data model 😄

**Comment by nata-g** [comment]
@mquandalle  In my journey learning about react, redux, apollo, I just came across this react based rich text editor framework - https://facebook.github.io/draft-js/. I immediately thought it would be a nice feature to integrate this in Wekan, particularly for any text based input.....

**Comment by nata-g** [comment]
@mquandalle  ....As I was reading more about event sourcing and CQRS pattern, came across this resource about implementing Kanban using event sourcing. The sample app is using Java and spring framework though, but does have cool implementation architecture....

https://github.com/eventuate-examples/es-kanban-board

**Comment by mquandalle** [comment]
@nata-g This looks very cool, I will take a careful look as this application seems to implement a lot of the architecture principles I’m planning for Wekan next. Thank you for the share!

**Comment by mquandalle** [comment]
And BTW, yes draft-js is also a very good library (though a bit young, not sure if we can use it for google-docs like realtime editing by multiple users with multiple cursors). But the underlined data model makes a lot of sense and is way better than the ad-hoc transformations that we currently do for users mentions and tag assignment. So yes, I want to use draft.js in Wekan next.

**Comment by nata-g** [comment]
@mquandalle ...Awesome!!! talking about Draft-js, maybe there might be some plugins to do real time editing in Draft-js in near future that can be used, similar to https://github.com/draft-js-plugins/draft-js-plugins

Also, I was wondering, since now there is lot of community interest and contributors willing to contribute, to publish the technologies and patterns that would be used in the Wekan rewrite. I mean lot of these tech is cutting edge (like Apollo) and there is lot of paradigm changes happening with React (components, inline styles on React elements etc) and there is going to be some learning curve involved for existing and future contributors, so may be writing up about the stack that is going to be used,  and its rationale and some high level architecture patterns (Event Sourcing, using Mantrajs architecture?) that are going to be followed,  would be immensely useful. It also helps the users about the changes that are going to be coming. My 2 cents.....

**Comment by akhockey21** [comment]
@mquandalle 

I am very interested in possibly getting a group together to start tackling this feature. I am far from an expert in React, but I see React native as an opportunity too good to miss out on. I was reading the meteor guide and they give great documentation on incrementally migrating Blaze to React. Even if the Drag and Drop is the last thing we do, I would love to hear your thoughts on why we can't just start working on migrating some of the more simple Blaze templates/components to React.

Source: http://guide.meteor.com/react.html#react-in-blaze

**Comment by xet7** [comment]
It does not seem to be so good idea to switch to react anymore because of this:
https://react-etc.net/entry/apache-foundation-bans-use-of-facebook-bsd-patents-licensed-libraries-like-react-js

**Comment by xet7** [comment]
Moved to #953

**Comment by xet7** [comment]
Reopening, will see later if there is progress on this.

**Comment by jcrben** [comment]
If I added code that made it possible to write new features in React, would that be welcome?

Another benefit of React not mentjoned here is enzyme. https://github.com/airbnb/enzyme

I don't know a tom avout meteor but enzyme makes acceptance level testing fast and easy.

**Comment by xet7** [comment]
@jcrben

No. That would just add more bloat.

I would prefer pull request to to Wekan that would change used libraries to ones that have smaller amount of javascript used. Also, preferedded license to used libraries is MIT.

**Comment by jcrben** [comment]
fy, React will use fewer lines due to its declarative style. And it is MIT licensed.

**Comment by xet7** [comment]
@jcrben 

React is bloated. Something like [RE:DOM](https://redom.js.org) or [Mithril](https://mithril.js.org) would be much better.

**Comment by xet7** [comment]
Anyway, for first time contributor, first task is to get to know Meteor, and do some contributions to Wekan. Not to change Wekan to other framework.

**Comment by rwatts3** [comment]
Or Vue.js I would see as a better fit. 
Vue, Nuxt.js, and Prisma.io is a great stack.

**Comment by mtumiati** [comment]
I think that the best choice nowadays is React. Are you going to consider to switch?

**Comment by mitar** [comment]
I think Vue is better. Lol.

**Comment by xet7** [comment]
LOL yeah, I added those to wishlist.
https://github.com/wekan/demo/wiki/Roadmap

**Comment by xet7** [comment]
Wekan is huge amount of code and features. If someone really has time to help with those other frameworks, it would be nice. I'm not familiar enough with other frameworks to be able to make such a change.

**Comment by mtumiati** [comment]
In my company we use Meteor/React for many projects and it works very well. I have no experience in Vue.js, but even if the syntax seems to be similar to Blaze, it will be more or less the same amount of effort to switch. I was suggesting React also because the community is huge and I think that more people can help

**Comment by Digital768** [comment]
are you switching to react anytime soon bro???

**Comment by mfilser** [comment]
The whole GUI is based on Meteor and Blaze, why to switch to another framework like react ?

**Comment by xet7** [comment]
@Digital768 

> are you switching to react

There are no benefits in switching to React.

Here someone changed from React to HTMX. Result: -15k lines of code:

https://www.youtube.com/watch?v=wIzwyyHolRs

**Comment by xet7** [comment]
Any change to WeKan is, when someone sends PR, or I do that change, and there are benefits (speed, less code, easier to read, simpler, etc), and all (or most) features keeps working.

**Comment by xet7** [comment]
About frontend web frameworks:

- Previously, WeKan used Stylus. But that caused bugs and errors, newest version did not work, so I converted Stylus to CSS.
- I have not been able to get Jade working with Meteor 3.x yet. So if I don't get Jade working, it could happen, that Jade will be converted to Blade. Or alternatively, if some new version of Jade, with newer name Pug, would work, then change to that. But that remains to be seen, what will work with Meteor 3.x.

Anyway, with any change, requirement is that all features keep working in all supported webbrowsers.
