### ISSUE TITLE
Comment editing no longer works

### ISSUE THREAD

**Issue by uusijani** [wekan/wekan#2991]
Comments can no longer be updated, as pressing the Edit button just reverts the comment back to what it was prior to editing. Both rich and non-rich editor are affected.

**Server Setup Information**:

* Wekan version: 3.89
* Operating System: Ubuntu 16.04
* Deployment Method: snap
* Http frontend if any: Apache
* Web browser: both Chrome and Firefox affected

**Steps to reproduce**
1. Add a comment to a card.
2. Click the `edit` link to start editing the comment, make some changes.
3. Click the `Edit` button.

***What I expect to happen***
For the comment to reflect the changes made when editing.

***What happens instead***
The comment content reverts back to what it was prior to editing.

**Logs**
Nothing in browser console log, nothing related in server log.

![Peek 2020-04-07 17-06](https://user-images.githubusercontent.com/4244772/78679287-b4dca800-78f2-11ea-8ddb-f44157c26f24.gif)

**Comment by denish-kanabar** [comment]
I am facing similar situation. Once comment added to any card, not able to delete/edit card and not able to delete that card itself or for that matter list also.

If I try to delete card/list then it comes back automatically.
Is there any script or api to delete card/list ? normal api to delete is not working if you have comments in it.
Any input will be appreciated. Thanks for tool.

Regards,
Denish

**Comment by slvrpdr** [comment]
I was checking when this problem appeared.
It seems that it works properly in v3.87, but stops working in v3.88. Could it be related to the notification drawer feature?

**Comment by uusijani** [comment]
@denish-kanabar For undeleteable cards, see #2613 and a [workaround in the comments](https://github.com/wekan/wekan/issues/2613#issuecomment-549079613).

**Comment by xet7** [comment]
@jtbairdsr 

Do you have time to revert some of your notification drawer like Trello changes so editing and deleting comments would be again possible?

In general, notifications/activities features at Wekan are very complex and it's very easy to disable some Wekan features with some new code changes. This has also happened to me and other contributors many times, it's normal in complex software. When adding new feature to Wekan it usually requires some tweaks so that everything works correctly.

Thanks!

**Comment by jtbairdsr** [comment]
@xet7 

I will look into that right away.

Thanks for the heads up.

**Comment by xet7** [comment]
Thanks @jtbairdsr :)

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3005, will be in next release Wekan v3.93 today or tomorrow.
