### ISSUE TITLE
How can i Update Wekan snap

### ISSUE THREAD

**Issue by FuXXz** [wekan/wekan#2992]
Hello,

i haved read this doc https://github.com/wekan/wekan-snap/wiki/Install
and try to Update Wekan from 3.89.0 to 3.90 with sudo snap refresh.
But nothing happend, wekan is still on 3.89. What iam missing?

**Comment by xet7** [comment]
Newest Snap is that 3.89 as you can see from https://snapcraft.io/wekan

I did try to build 3.90, but it did have errors when building it, so it's not released yet.

After I get it working and built properly, you will see versio 3.90 at https://snapcraft.io/wekan
and it will automatically install, or you manually install with `sudo snap refresh`

**Comment by FuXXz** [comment]
Merci for the Infos
I didn't really understand the concept of Snap.
