### ISSUE TITLE
Filter by Assignee

### ISSUE THREAD

**Issue by darren-teo** [wekan/wekan#2995]
I guess this is more of a feature request. I'm able to filter cards by person if he/she is a member of the card, however I'm not able to filter if that person is an Assignee in the card.

Can the filtering be extended to assignee as well?

**Server Setup Information**:

* Wekan version: 3.86
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* MongoDB Version: 4.2.5

**Comment by daniel-eder** [comment]
Seems like a vital feature to me, implemented in https://github.com/wekan/wekan/pull/2997

**Comment by daniel-eder** [comment]
@xet7 this can be closed. Thanks!

**Comment by darren-teo** [comment]
Thank you. I can see the commit in 3.91 onward.
