### ISSUE TITLE
Docker build for arm64

### ISSUE THREAD

**Issue by brokencode64** [wekan/wekan#2999]
## Issue

It would be great to have a docker build for arm64 platform. Mongodb is easy enough to find, but would be nice to have a build for wekan!

**Comment by xet7** [comment]
@brokencode64 

Can you try to figure out how to do it? By searching for multiarch Docker?

Current amd64 docker-compose.yml is at https://github.com/wekan/wekan

arm64 bundle .zip file etc info is at https://github.com/wekan/wekan/wiki/Raspberry-Pi

Please add comments to this issue if you get progress, or that docker-compose.yml in .zip file attachment to this issue.

Thanks!

**Comment by brokencode64** [comment]
I've actually spent some time around this but ran into issues with meteor. Will post back if I make more progress.

**Comment by xet7** [comment]
@brokencode64 

You don't need to build it with Meteor. You just:
- unzip wekan-VERSION-arm64.zip
- set environment variables like MongoDB port etc
- `cd bundle`
- `node main.js`

**Comment by xet7** [comment]
Also it's not needed to install meteor in Dockerfile.

**Comment by brokencode64** [comment]
@xet7 I created the following PR. There is a merge conflict of course with the changes that will need to be resolved. Let me know what changes or adjustments should be made!

https://github.com/wekan/wekan/pull/3023

**Comment by xet7** [comment]
@brokencode64 

I had to rename Dockerfile.amd64 back to Dockerfile because automatic builds at Docker Hub and Quay.ioi did not find Dockerfile and then failed.

**Comment by xet7** [comment]
Moved to #3829
