### ISSUE TITLE
Drag and drop to add an attachment

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#300]

**Comment by mquandalle** [comment]
We should follow Rocket.chat implementation here.

**Comment by rchrd2** [comment]
:+1: I am a new Wekan user. It's great so far, but I initially tried to drag an image in and concluded that it didn't support images. Only until later digging in, I discovered the "attachment" feature. It would be great to have this drag and drop feature.

**Comment by floatinghotpot** [comment]
It would be great if allow attaching image from clipboard. It's a true requirement from our team.

**Comment by danieldownes** [comment]
I am having to look at a different open source alternative simply because Drag and drop attachments are not supported 👎 

Hope this helps gets things moving. I work based on images covers and simply can not browse my file system for every card I want to add.

**Comment by xet7** [comment]
@danieldownes 

Huh, really, where you got idea that thumbs down is encouragement to implement feature?
https://github.com/wekan/wekan/wiki/FAQ#etiquette

**Comment by danieldownes** [comment]
Apologies, I've read the FAQ link you gave, I don't quite understand the logic or how it could be see as offensive/trolling. I thought negative sentiment was how these FOSS projects ran, or is that just Linux? ;)

Anyway, my point is that the FAQ etiquette section seems to be a list of rules without explanation.

This was my first posting to an open source project, even though I have donated to other FOSS software projects before, looks like the FAQ was tailored directly to my post.

I have edited the post. I am a coder so will look over the code at some point. If there is any other way I can attract more awareness to this need then do let me know.

**Comment by danieldownes** [comment]
Just a little shocked that D&D images did not work which I find to be essential, but there are lots of nice other features in the project.

I see there is no way to request prioritisation of features. Again I do not understand this decision, surely a game changing killer feature that much required should be swarmed upon by contributors/developers?

**Comment by xet7** [comment]
Hehe :) Wekan is friendly positive community, not Linux kernel mailing list.

**Comment by xet7** [comment]
Actually we do have some priorities, I updated [Etiquette](https://github.com/wekan/wekan/wiki/FAQ#etiquette).

Wekan has quite small codebase of about 7000 lines only, so contributing is easier than to some other huge projects.

**Comment by xet7** [comment]
I found that here on old PR: https://github.com/wekan/wekan/pull/397
could be this upload drag-and-drop code: https://github.com/wekan/wekan/pull/397/commits/4a3525ba0d2f3f9a039cd6485cbc8dfafbf0d10f

It needs testing that does it work, and creating a new pull request.

**Comment by xet7** [comment]
[Drag and drop attachment](https://github.com/wekan/wekan/wiki/Features#cards-drag-and-drop-images-to-card-paste-images-with-ctrl-v) already exists in Wekan.

**Comment by Suleman-Elahi** [comment]
Can we drag-drop images on the card itself to upload/add as attachment like Trello and NextCloud Deck?

**Comment by xet7** [comment]
@Suleman-Elahi 

Not yet. It will be added, when possible.

Your issue moved to #2936
