### ISSUE TITLE
Login Screen Not loading in Facebook's In-App browser

### ISSUE THREAD

**Issue by brianrc** [wekan/wekan#3002]
When clicking through a Facebook messenger link to the board, the login screen fails to load. It just loads a blank light-gray screen.

It works fine on desktop browsers and in the Chrome mobile, but not the Facebook In-App Browser.

I couldn't find the version of the Facebook or Messenger App, but it's the latest I could install on Nexus 6P Android Version 9.

Waken Version 3.92.0

**Comment by marc1006** [comment]
Hi @brianrc, can you please test it with the edge version of Wekan? You can either build it yourself or install it with snap (`sudo snap install wekan --edge`) as there is no official release yet.

**Comment by xet7** [comment]
When Wekan snap is installed
https://github.com/wekan/wekan-snap/wiki/Install

Do [Backup first](https://github.com/wekan/wekan/wiki/Backup) before switching to edge. Sometimes edge is broken, use it only for testing, not production.

You can switch to edge this way:
```
sudo snap refresh wekan --edge --amend
```
And back to stable this way:
```
sudo snap refresh wekan --stable --amend
```

**Comment by xet7** [comment]
Please test newest Wekan v3.98

**Comment by brianrc** [comment]
Yes it works now! Thank you.

Yay!
