### ISSUE TITLE
[Feature-request] member permitions

### ISSUE THREAD

**Issue by ndgo** [wekan/wekan#301]
I think that wekan needs member permitions for users. For example. Some members are admins, they can do all (they can allow other user to change cards(tasks)). Admins can assign a card (task) for other user and after it user can start work with this card

**Comment by slideup-benni** [comment]
maybe a site admin role would be great too. He can see and manage all boards (even if they private).

**Comment by leifsehn** [comment]
+1

**Comment by jseadragon** [comment]
A site admin role would almost be required for any enterprise deployments

**Comment by xet7** [comment]
Moved to #802
