### ISSUE TITLE
Saving email setting in Administration breaks email

### ISSUE THREAD

**Issue by XL-Reaper** [wekan/wekan#3016]
Wekan Version	3.95.0
Meteor-Version	1.10.1
Node-Version	12.16.2
MongoDB-Version	4.2.5

I have a weird problem with the email setup:
I am using docker-compose.yml with the following mail configuration:
```
MAIL_URL=smtp://mail.server:25/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false
```

In Administration I have set the same server, Port 25, No user / password and disabled TLS.
![image](https://user-images.githubusercontent.com/17750416/79208616-902c8700-7e42-11ea-86e6-1e752aa9251c.png)

I can send a Test-Email just fine - until I press Save, after that I will only get the following error until I restart Wekan:
![image](https://user-images.githubusercontent.com/17750416/79208509-6b381400-7e42-11ea-986e-5e6d0f35ea24.png)

After the restart test-emails are fine again. If I now change NOTHING, just press save, it breaks again until a restart.

**Comment by helioguardabaxo** [comment]
@xet7 
A workaround would be call saveMailServerInfo() method inside sendSMTPTestEmail() in settingBody.js file?

```
sendSMTPTestEmail() {
    saveMailServerInfo();
    Meteor.call('sendSMTPTestEmail', (err, ret) => {
      if (!err && ret) {
        const message = `${TAPi18n.__(ret.message)}: ${ret.email}`;
        alert(message);
      } else {
        const reason = err.reason || '';
        const message = `${TAPi18n.__(err.error)}\n${reason}`;
        alert(message);
      }
    });
  },
```

**Comment by maltem-za** [comment]
Sounds like you might have a similar problem to [what I experienced](https://github.com/wekan/wekan/issues/2375#issuecomment-732773295), albeit it the other way around.

**Comment by xet7** [comment]
@XL-Reaper @helioguardabaxo @maltem-za 

Please test does now `snap set wekan mail...` settings keep working with newest Wekan.
