### ISSUE TITLE
 board does not open

### ISSUE THREAD

**Issue by edgarvenom** [wekan/wekan#3018]
I was working on an existing board, I was adding tasks and images when suddenly my board was no longer shown to me and it only kept loading

checking the logs I get the following error

[root@servidor ~]# systemctl status snap.wekan.wekan
● snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-04-14 12:11:40 CDT; 30min ago
 Main PID: 22523 (wekan-control)
   CGroup: /system.slice/snap.wekan.wekan.service
           ├─22523 /bin/bash /snap/wekan/789/bin/wekan-control
           └─23259 /snap/wekan/789/bin/node main.js

Apr 14 12:11:41 servidor.cloud wekan.wekan[22523]: LDAP_CONNECT_TIMEOUT=10000 (default value)
Apr 14 12:11:41 servidor.cloud wekan.wekan[22523]: LDAP_AUTHENTIFICATION=false (default value)
Apr 14 12:11:42 servidor.cloud wekan.wekan[22523]: LDAP_AUTHENTIFICATION_USERDN= (default value)
Apr 14 12:11:42 servidor.cloud wekan.wekan[22523]: LDAP_AUTHENTIFICATION_PASSWORD= (default value)
Apr 14 12:11:42 servidor.cloud wekan.wekan[22523]: LDAP_LOG_ENABLED=false (default value)
Apr 14 12:11:42 servidor.cloud wekan.wekan[22523]: LDAP_BACKGROUND_SYNC=false (default value)
Apr 14 12:11:42 servidor.cloud wekan.wekan[22523]: LDAP_BACKGROUND_SYNC_INTERVAL= (default value)
Apr 14 12:11:42 servidor.cloud wekan.wekan[22523]: LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=false (default value)
Apr 14 12:11:48 servidor.cloud wekan.wekan[22523]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Tue Apr 14 2020 12:11:48 GMT-0500 (Cen..."level":"info"}
Apr 14 12:12:13 servidor.cloud wekan.wekan[22523]: (node:23259) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe...ethods instead.
Hint: Some lines were ellipsized, use -l to show in full.
[root@servidor ~]#

**Comment by edgarvenom** [comment]
I get this error in the browser 

e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:108 WebSocket connection to 'wss://board.polilla.studio/sockjs/693/m74w1ux2/websocket' failed: WebSocket is closed before the connection is established.

**Comment by xet7** [comment]
What OS version that server is running?

**Comment by xet7** [comment]
Do you have some webserver at front of Wekan? Like Caddy/Nginx/Apache?

**Comment by edgarvenom** [comment]
CentOS Linux release 7.6.1810 (Core) 
 Nginx

**Comment by xet7** [comment]
For Nginx, you need websockets enabled https://github.com/wekan/wekan/issues/2635#issuecomment-610452453

And also to `/etc/nginx/nginx.conf` define maximum filesize allowed, because if it's not big enough, big attachments etc are not visible at all and can not be uploaded, for example:
```
http {
    ...
    client_max_body_size 5000M;
}    
```

**Comment by edgarvenom** [comment]
I added what was requested, but I still can't load my board, and I still get the error in the wekan status

**Comment by edgarvenom** [comment]
/var/log/nginx/error.log:92:2020/04/14 12:11:44 [error] 338#338: *124399 connect() failed (111: Connection refused) while connecting to upstream, client: 189.216.181.158, server: board, request: "GET /sockjs/info?cb=m98qx1jn4r HTTP/2.0", upstream: "http://127.0.0.1:3001/sockjs/info?cb=m98qx1jn4r", host: "board", referrer: "https://board/b/bcAtfpXb96Shxx97X/proyectouvm"

**Comment by xet7** [comment]
Is there any errors in browser inspect console?

**Comment by edgarvenom** [comment]
Uncaught TypeError: Cannot read property 'scrollTop' of undefined
    at n.scrollTop (e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:524)
    at n.setView (e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:524)
    at Object.disable (e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:524)
    at n.click .js-multiselection-reset (e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:524)
    at e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:349
    at Object.h._withCurrentView (e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:88)
    at e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:349
    at t._withTemplateInstanceFunc (e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:88)
    at h.View.t.<computed> (e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:349)
    at e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:88
e339f46b5d423e51bee973e2efcd3e41942d7caa.js?meteor_js_resource=true:1 Exception from Tracker recompute function: undefined

**Comment by xet7** [comment]
At `All Boards` page, can you try clicking `Duplicate Board` and then try does the original or duplicated board open?

**Comment by edgarvenom** [comment]
I already tried it but it doesn't let me duplicate it nor does it give me the option to export it

**Comment by xet7** [comment]
Are you BoardAdmin on that board? Next version of Wekan v3.96 will allow BoardAdmin to duplicate or archive https://github.com/wekan/wekan/pull/3013. I'm currently in progress of making that release. Please see https://snapcraft.io/wekan sometime today or tomorrow that it shows v3.96 and then manually update with `sudo snap refresh` and try can you duplicate board.

**Comment by edgarvenom** [comment]
I am an administrator of the boards, a user managed to get a json backup from the board, but it does not let me load it, it tells me that the page stopped responding


How can i charge my json?

**Comment by xet7** [comment]
You edit that JSON file with text editor like Notepad++, GEdit, Kate, etc. It's plain text file.

**Comment by edgarvenom** [comment]
my json file weighs 133mb and I can't upload it to the dashboard in the import section,
Is there a manual way to load it?
How do I manually update my snap?

**Comment by xet7** [comment]
Maybe you have deleted a linked card? #2785 

If there is something remaining from linked card, it could be edited/removed directly at MongoDB database with nosqlbooster.

**Comment by xet7** [comment]
Another possibility is, that if you can send [Backup](https://github.com/wekan/wekan/wiki/Backup) of your MongoDB database as .zip archive to me with:
https://www.dropbox.com/request/KQqepyd0Jr62GHfWETfF
and send email to me to support@wekan.team then I can try to fix that board and send fixed database back to you.

**Comment by xet7** [comment]
Manual update of snap is with:
```
sudo snap refresh
```
Creating new release is still in progress, it's not released yet.

**Comment by xet7** [comment]
Snap v3.96 is now released.

**Comment by edgarvenom** [comment]
How do I get the backup of my mongo database to send it?

**Comment by xet7** [comment]
```
ssh centos@yourserver.com
sudo yum install zip unzip
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/wekan/current/lib/x86_64-linux-gnu
export PATH="$PATH:/snap/wekan/current/bin"
mongodump --port 27019
zip -r ebackup.zip dump
exit
scp centos@yourserver.com:/home/centos/ebackup.zip .
```
Then upload with webbrowser to:
https://www.dropbox.com/request/KQqepyd0Jr62GHfWETfF
and send email to me to support@wekan.team then I can try to fix that board and send fixed database back to you.

**Comment by xet7** [comment]
Related https://github.com/wekan/univention/issues/13

**Comment by xet7** [comment]
Please try with newest Wekan.
