### ISSUE TITLE
members of a board

### ISSUE THREAD

**Issue by michaelwemoto** [wekan/wekan#302]
I created a board, invited another member, promoted them to administrator. used their account to demote me from administrator and used their account to remove me from the board.

I'm still on the board, I understand that I created it but I thought the above process would pass it to another user.

**Comment by xanghe** [comment]
Hi, 

I don't think promotion to admin is possible in Wekan yet (see #146 and #301). Looks like there's a lot of interest, though (myself included :)

**Comment by michaelwemoto** [comment]
I'm using Release 0.9, I'm pretty sure promotion to administrator is working, the other user is able to add, remove and delete items in the board that I promoted them in. am I missing something?

**Comment by xanghe** [comment]
That sounds right, I believe all users that have been added to a board are
allowed those rights. The only "admin" role I've come across is the
owner/creator of a board is the only one who can remove members from a
board. But other than that, there are no defined roles.

**Comment by michaelwemoto** [comment]
I (Michael) created a board (task-manager).

I added Daisy as a member of task-manager.

Promoted Daisy to admin in the 'change permissions' tab.

Then on Daisy's login I removed Michael from the task-manager board.

Michael can see and access task-manager but cannot add / remove / edit
anything.

This is working admin permissions in my opinion, it's just confused
about letting me in because I created the board initially.

please test these steps and tell me if you see different results.


On 16/09/15 17:40, xanghe wrote:
> That sounds right, I believe all users that have been added to a board are
> allowed those rights. The only "admin" role I've come across is the
> owner/creator of a board is the only one who can remove members from a
> board. 
(not true)
But other than that, there are no defined roles.

**Comment by xanghe** [comment]
That sounds like admin to me! But I must be on a different version because
I don't see a "change permissions" tab. I'm running v0.9 release from last
week - maybe I need to upgrade already. Can you send a screenshot?

**Comment by michaelwemoto** [comment]
Hi, here's a screenshot.

I'm running the 0.9 release, not the rc2 if that's what you got?
I'm not git cloning, downloading the .tar.gz and extracting.
CentOS7 host.

**Comment by michaelwemoto** [comment]
![wekan_permissions](https://cloud.githubusercontent.com/assets/12196996/9934181/93b1552a-5d47-11e5-95af-6f148b638898.png)

This is from release 0.9 the .tar.gz, on a CentOS7 host.

**Comment by xanghe** [comment]
Okay, great. I never saw that. I'll be back in the office tomorrow, I'll
check our local install for that. Thanks.

**Comment by xanghe** [comment]
*Sure enough*, it's there! Thanks for pointing out the obvious! I was looking a user admin panel or something.
