### ISSUE TITLE
Wekan not load at all in Firefox v.68 for Android

### ISSUE THREAD

**Issue by victordariovera** [wekan/wekan#3021]
## Issue

Wekan not load in Fitefox v.68 for android. The login form not show at all. In Chrome for Android wekan works great. In Firefox Desktop (last version) works fine too.

![Screenshot_20200416-030755_Firefox](https://user-images.githubusercontent.com/25089852/79421084-75682880-7f90-11ea-8ee5-630d63987c55.jpg)
![20200416_030901](https://user-images.githubusercontent.com/25089852/79421097-7ac57300-7f90-11ea-9ba2-db6e2a53e0c7.jpg)

**Comment by victordariovera** [comment]
Here is my version of wekan, its latest docker image :D 

<img width="794" alt="Screen Shot 2020-04-16 at 11 47 35" src="https://user-images.githubusercontent.com/25089852/79470887-51303a00-7fd8-11ea-94ca-12a70cbc8ca2.png">

**Comment by marc1006** [comment]
I have debugged it by using remote debugging, and there are some error messages:
```
ReferenceError: meteorBabelHelpers is not defined914e476290dab8425d1a7933a98e6240780147d4.js:45967
    <anonymous> 914e476290dab8425d1a7933a98e6240780147d4.js:45967
    <anonymous> 914e476290dab8425d1a7933a98e6240780147d4.js:45972
    <anonymous> 914e476290dab8425d1a7933a98e6240780147d4.js:45974
```

I'll try to fix this.

**Comment by marc1006** [comment]
@xet7  It works if I'm starting wekan by using this command line:
`WITH_API=true RICHER_CARD_COMMENT_EDITOR=false ROOT_URL=http://192.168.178.2:8080 meteor run --exclude-archs web.browser.legacy,web.cordova --port 8080`
