### ISSUE TITLE
[Feature]: export board to static site

### ISSUE THREAD

**Issue by Lewiscowles1986** [wekan/wekan#3026]
### Server Setup Information:

N/A

### Problem description:

WeKan can import from and export to JSON file format.

This is a placeholder issue to track the ability to deploy a board view, non-editable as static HTML & CSS [JS]

#### Rationale

I would like to provide read-only access to some KanBan boards on my own website, where I feel securing and maintaining wekan might be problematic

#### Goals

Create a solution (possibly as a separate repository) to use an exported wekan JSON file, and deploy  a static HTML + CSS, possibly with JS, although not desirable to keep people informed of the progress of work.

##### Actual HTML structure -> HTML

Could scrape the DOM and remove attributes

##### Data / JSON Export -> HTML

* [x] elements
  * [x] board
    * title
    * theme color
  * [x] lanes
    * title
    * is order / position needed, or can a sort allow position to be projected into HTML structure?
  * [x] cards
    * [x] title
    * [x] description
    * [x] authors
      * Should this be optional?
    * [x] labels
      * Should this be optional?
    * [x] attachments
      * Should this be optional?
    * [x] comments
      * Should this be optional?
    * is order / position needed, or can a sort allow position to be projected into HTML structure?

**Comment by xet7** [comment]
@Lewiscowles1986 

For example at Wekan Snap:
- updates are automatic
- public boards are read-only
- Snap is at strict sandbox and code at server can not access files outside of `/var/snap/wekan/common` directory

Is there some security issue in Wekan that I'm not aware yet?

Or in which way it would be problematic?

**Comment by xet7** [comment]
Anyway, all contributions for HTML export etc anything are welcome. Thanks!

**Comment by MysterAitch** [comment]
I can't comment on the motivations above, but one use case for this may be exporting to a GitHub pages webpage or similar.

**Comment by Lewiscowles1986** [comment]
It's not just GitHub pages. I deployed WeKan to Heroku in the hopes of having something public. It wasn't a good fit, so instead I'll keep it as internal only. I'd still like to share, which is why the issue.

RE: @xet7 question
> Is there some security issue in Wekan that I'm not aware yet?

Not that I'm aware of, but this has a much larger attack surface than a static HTML page 😉 

I think I'll experiment, just wanted to know if upstream would be interested if I can get it working

**Comment by xet7** [comment]
@Lewiscowles1986 

If you don't need cards opened, already when saving Wekan page and removing Javascript file it does kind of work, if paths to images are fixed, like can be seen here:
https://wekan.github.io/demo/

Of course I'm interested. I would also be interested if someone would have time to clean up and add new pull requests for CSV/Excel export etc #395.

Wekan has 593 open issues. It's physically impossible for me to work on all of them at once. To have some real progress, more contributors make it possible.

**Comment by xet7** [comment]
> RE: @xet7 question
> 
> > Is there some security issue in Wekan that I'm not aware yet?
> 
> Not that I'm aware of, but this has a much larger attack surface than a static HTML page 😉 

In theory, that static webpage could have some of Wekan features, like saving to browser local storage, exporting to various formats, and saving to some remote storage with REST API, all with that Javascript that is included to webpage. It would be interesting to see how far you can get with it.

**Comment by Lewiscowles1986** [comment]
I only want it to display. If I get that working, it'll be open enough for anyone else to tinker with further aspects.

**Comment by xet7** [comment]
Ok thanks!

**Comment by Lewiscowles1986** [comment]
This sorta works

```javascript
Array.from(document.querySelectorAll('script')).forEach(elem => elem.remove())
Array.from(document.querySelectorAll('link:not([rel="stylesheet"])')).forEach(elem => elem.remove())
document.querySelector('#header-quick-access').remove()
Array.from(document.querySelectorAll('#header-main-bar .board-header-btns')).forEach(elem => elem.remove())
Array.from(document.querySelectorAll('.list-composer')).forEach(elem => elem.remove())
Array.from(document.querySelectorAll('.list-composer,.js-card-composer')).forEach(elem => elem.remove())
```

Got to change remaining anchors to spans and remove href elements on them which I might cheat and do with string replace. Then it's ensuring relative resources are saved in some way

**Comment by Lewiscowles1986** [comment]
follow up with

```javascript
let htmlDoc = ('<!doctype html>' + window.document.querySelector('html').outerHTML)
htmlDoc = htmlDoc.replace('<a ', '<span ')
htmlDoc = htmlDoc.replace('</a>', '</span>')
let dl = document.createElement('a')
dl.href = window.URL.createObjectURL(
  new Blob([htmlDoc], {type: 'application/html'}) // file content
);
dl.onclick = event => document.body.removeChild(event.target);
dl.style.display = 'none';
dl.target = '_blank';
dl.download = "wekan-export.html"
document.body.appendChild(dl);
dl.click();
```

**Comment by Lewiscowles1986** [comment]
https://davidwalsh.name/javascript-zip looks like it could provide an answer on how to add CSS & attachments to a redistributable zip file

**Comment by Lewiscowles1986** [comment]
fetching CSS file names and contents

```javascript
Array.from(document.querySelectorAll('link[href][rel="stylesheet"]')).forEach(async elem => {
  let response = await fetch(elem.href)
  let responseBody = await response.text()
  console.log(elem.href.split('/').pop().split('?').shift())
  console.log(responseBody)
});
```

**Comment by Lewiscowles1986** [comment]
could maybe do something similar for images, which would require the .href = .href and .src = .src to change

I think relative path for both with the board slug being a sub-folder that images are placed within

**Comment by Lewiscowles1986** [comment]
I've spawned a stretch goal issue, but it is important in the case that links are within the cards "I think, I don't know"

**Comment by Lewiscowles1986** [comment]
I've got the zip thing working. It's all still very prototype right now. Are there JS events fired once the board is in a fully loaded state? Could there be?

**Comment by xet7** [comment]
@Lewiscowles1986 

Maybe you mean this?
```
~/repos/wekan$ ./find.sh onRendered
```

**Comment by Lewiscowles1986** [comment]
Thanks @xet7 I managed to do something else instead. I take it that is a lifecycle event, and I may come back to it, but I meant a global entire page event using JS events rather than a specific named callback. 

The pivot is that I'm basically putting this as a UI button underneath export to JSON. It could have issues, but as I'm still hacking right now, I think it's cool.

Very nice structure in the sidebar.js has been helpful in verifying download of single HTML file. Tinkering with zip file now. Workflow is a bit long rebuilding a several hundred MB docker image and pushing so I can test on the machine I use the wekan through is less than idea.

How do you get the `wekanteam/wekan` image down to 300MB, is it building with `--squash`? I looked in the GitHub action and Travis, but they don't seem to push.

**Comment by xet7** [comment]
@Lewiscowles1986 

Dockerfile is written by many contributors and me and built by Docker Hub, I don't know does it use `--squash`.
https://github.com/wekan/wekan/blob/master/Dockerfile

**Comment by Lewiscowles1986** [comment]
My bad. Locally it reports uncompressed size of 900MB, online we both have similar sizes. This solves my confusion around how and why. Thanks again.

**Comment by Lewiscowles1986** [comment]
@xet7 I don't know if the github.io roadmap is up-to-date and appreciate you are busy.

This may provide interim solutions:

* to people with many read-only users experiencing "slowness"
* to people wishing for read-only access to "stop cards moving"

**Comment by xet7** [comment]
@Lewiscowles1986 

Newest Wekan Roadmap link is at https://wekan.github.io, it's self-hosted on Wekan Snap version that is running on bare metal server donated to Wekan development by [CNCF](https://blog.wekan.team/2019/06/wekan-on-raspi3-and-arm64-server-now-works-and-whats-next-with-cncf/). That Roadmap is up-to-date.

Anyway, adding read-only static version for it most likely speeds up loading it. I will test this.

**Comment by Lewiscowles1986** [comment]
dockerhub codesign2/wekan:stable gets updated with cool things.

For example today and yesterday I re-factored a little to not modify the viewers document without an iframe and postmessage. I've also got a branch for some exploratory work https://github.com/Lewiscowles1986/wekan/tree/feature/microformats2-enhancement which adjusts some tagging, changes some board display issues I had for non-CSS views.

The major PITA for me is long built-times. I shortened a bit by developing on a box I have some wekan boards on.

**Comment by Lewiscowles1986** [comment]
[wekan-fonts.zip](https://github.com/wekan/wekan/files/4536603/wekan-fonts.zip) this zip file might help with fontawesome too. I may grab roboto too. But as they are free, I've decided not to bundle them in this work as they are central. I could shave quite a few KB by omitting the CSS too, but that seems more important to the look & feel.
