### ISSUE TITLE
Cloudron page at Wekan wiki

### ISSUE THREAD

**Issue by gramakri** [wekan/wekan#3035]
I was looking into creating a better install section for Cloudron at https://github.com/wekan/wekan/wiki/Platforms . However, that page is a bit of a mess. Ideally, I would like to make a big list of all providers and each provider page can provide more information. Is this something that you would like to see as well? If so, I can help in editing the page but I am not sure how I should edit a github wiki?

I also want to fix some of the broken links at https://github.com/wekan/wekan/wiki/Cloudron. Please let me know how to go about fixing them.

**Comment by xet7** [comment]
@gramakri 

Currently editing wiki by any GitHub user is disabled because of spam test pages that had comments wondering why they can edit wiki.

You can add your wiki changes as a comment to this issue.

Do these issues still affect Cloudron? #2963 #2960 

Does Cloudron still make some custom changes to Wekan? Can you contribute those as pull requests?

**Comment by gramakri** [comment]
@xet7 Makes sense, we fight a lot of spam ourselves in our wiki and git repos. I will make a comment here in a while.

I wasn't aware of the issues! I will take a look (generally, we handle all issues via our forum but I guess the user wasn't aware).

We don't make any changes to upstream Wekan. We only have the LDAP integration, which we actually want to move to the upstream implementation. We keep the wekan app updated regularly otherwise - https://git.cloudron.io/cloudron/wekan-app

**Comment by xet7** [comment]
@gramakri 

How is your LDAP implementation different from current Wekan LDAP ?

**Comment by gramakri** [comment]
@xet7 The Cloudron package used to have a custom LDAP auth backend. We never managed to contribute this upstream because we are not meteor devs :( After your comment, we looked into this again and we have now moved to using upstream LDAP backend now (https://forum.cloudron.io/topic/2404/wekan-package-updates/2). So, at this point, the Cloudron package matches the upstream wekan 1-1.

Now that this is done, I will look into the wiki change.

**Comment by xet7** [comment]
Thanks!

**Comment by xet7** [comment]
@gramakri 

I did add Cloudron directly to Download part of Wekan website https://wekan.github.io .

I presume you will add wiki page changes as a comment to this issue sometime.

**Comment by gramakri** [comment]
@xet7 Thanks! Sorry for the delay, this is still on my list. I will get it to this week.

**Comment by xet7** [comment]
@gramakri 

Do you mean this week? :smile:

**Comment by gramakri** [comment]
That only took 3 months :-)

I have put my changes in https://github.com/cloudron-io/wekan.wiki.git . There are 3 of them:

* The install link in https://github.com/cloudron-io/wekan/wiki now points directly to Platforms
* The Platform page is cleaned up - https://github.com/cloudron-io/wekan/wiki/Platforms
* I moved Univention to it's own page - https://github.com/cloudron-io/wekan/wiki/Univention

I removed a bunch of RaspPi notes because they are in https://github.com/cloudron-io/wekan/wiki/Raspberry-Pi . We should only consider removing some of those platforms because they appear dead or not updated since quite a while.

**Comment by xet7** [comment]
@gramakri 

Huh? I did mean, do you have any changes to that [Cloudron](https://github.com/wekan/wekan/wiki/Cloudron) page, and you adding those changes as comment to this issue?

**Comment by gramakri** [comment]
@xet7  I only wanted to change the demo link in Cloudron page really. That is changed as well in my repo - https://github.com/cloudron-io/wekan/wiki/Cloudron (it changed to my.demo.cloudron.io).

BTW, feel free to ignore all my other changes, I only wanted to fix the Cloudron link primarily :-) And I thought the current Platforms page could be cleaned up. Thanks!

**Comment by xet7** [comment]
Ok thanks! I changed demo link.
