### ISSUE TITLE
Accept/Decline button display problems

### ISSUE THREAD

**Issue by dieTausendsassa** [wekan/wekan#3041]
## Issue
If the board name is too long it can cause display problems on showing Accept/Decline buttons:

<img width="295" alt="PastedGraphic-4" src="https://user-images.githubusercontent.com/48297370/80089487-505e5180-855e-11ea-8a4c-251c7bce9498.png">

<img width="297" alt="grafik" src="https://user-images.githubusercontent.com/48297370/80097206-32e3b480-856b-11ea-9573-98160b6f14a6.png">

Wekan Version: 3.97.0
Meteor-Version: 1.10.2
Node-Version: 12.16.2
MongoDB-Version: 4.2.2

**Comment by xet7** [comment]
@marc1006 

Can you look at this?

**Comment by marc1006** [comment]
@xet7 What is the expected behavior? A scrollbar inside of the "board-list-item"? Increased height of all "board-list-items"?

**Comment by xet7** [comment]
@marc1006 

Maybe increased height.

**Comment by dieTausendsassa** [comment]
I think a pragmatic way is to shorten the length of the board name and invitation text. Maybe a tooltip can show the whole board name and invitation text.

**Comment by marc1006** [comment]
> I think a pragmatic way is to shorten the length of the board name and invitation text. Maybe a tooltip can show the whole board name and invitation text.

Yep, I prefer that as well. So we could either use a version from the following demo (probably the "ellipsis" version): https://codepen.io/chriscoyier/pen/gvFGI

Or we can set `overflow: auto` so we see a horizontal scrollbar.

**Comment by xet7** [comment]
@marc1006 

You can try horizontal scrollbar.

**Comment by xet7** [comment]
Also, board title could have horizontal scrollbar.

**Comment by marc1006** [comment]
Version 1:
![version_1](https://user-images.githubusercontent.com/12081346/80277988-1a9ea180-86f3-11ea-974c-ba093b75432c.png)

Version 2:
![version_2](https://user-images.githubusercontent.com/12081346/80277991-1e322880-86f3-11ea-9968-068978fe4d00.png)

**Comment by xet7** [comment]
@marc1006 

I do like Version 2. What if all board icons are only as high as there is content? For example, those with that text "ada" or "test" would be about half height or smaller?

**Comment by xet7** [comment]
@marc1006 

Also, when you click `board / board title` and and add description text, check that description text is also visible.

With board title and description, some HTML and [markdown formatting](https://guides.github.com/features/mastering-markdown/)  works.

For example, set title to this:
```
<i><font color=red>Hello</font></i>
```
And description to this:
```
<img src="https://wekan.github.io/wekan-logo.svg" width=200 height="70">
```

**Comment by marc1006** [comment]
![version_3](https://user-images.githubusercontent.com/12081346/80278423-55ee9f80-86f6-11ea-80fb-805933a8d638.png)

Better?

**Comment by xet7** [comment]
@marc1006 

This is great !! Please make pull request, so I will merge it and after that make new Wekan release.

**Comment by marc1006** [comment]
It's still broken for mobile/small devices but this could be fixed in a separate patch.

**Comment by marc1006** [comment]
I created a separate commit (https://github.com/marc1006/wekan/commit/e63e7b11318502e9f1238fcd7efff3c30590b29c) for the change, so it would be easier to revert the change if we go for version 1 after all.
