### ISSUE TITLE
BUG? | Cannot create new Comments on Cards

### ISSUE THREAD

**Issue by IamRFC1918** [wekan/wekan#3042]
Hi,

**Server Setup Information**:
Wekan Version 3.97 on Kubernetes

* Wekan version: 3.97
* MongoDB Version 4.2.5

**Problem description**:
Since we are updated from Version 3.56 to 3.97 we cannot create new Comments on Cards. Also in the Card Settings, we cannot find the point Comments.
<img width="289" alt="Screenshot 2020-04-23 at 15 47 11" src="https://user-images.githubusercontent.com/28442477/80116563-6aac2580-8586-11ea-8a7d-99788254b222.png">
<img width="507" alt="Screenshot 2020-04-23 at 15 46 56" src="https://user-images.githubusercontent.com/28442477/80116843-be1e7380-8586-11ea-88c3-92d410ce1d6a.png">

Error Log shows noting.
Is that a Bug or a feature?
Anyone have Ideas how to fix this?

Thanks,
Frank

**Comment by xet7** [comment]
That bug was fixed in Wekan v3.93. Please check you are running newest Wekan.
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v393-2020-04-10-wekan-release

With normal docker, upgrade is usually this way:
```
docker stop wekan-app
docker-rm wekan-app
docker-compose up -d
```

You see at Wekan Admin Panel version of Wekan.

**Comment by IamRFC1918** [comment]
> That bug was fixed in Wekan v3.93. Please check you are running newest Wekan.
> https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v393-2020-04-10-wekan-release
> 
> With normal docker, upgrade is usually this way:
> 
> ```
> docker stop wekan-app
> docker-rm wekan-app
> docker-compose up -d
> ```
> 
> You see at Wekan Admin Panel version of Wekan.

Hi xet7,
We're using the newest Version. Please take a look at this Screenshot:
<img width="533" alt="Screenshot 2020-04-23 at 17 34 01" src="https://user-images.githubusercontent.com/28442477/80118473-bc55af80-8588-11ea-87a5-72d7cf27a509.png">

Maybe the Bug is again there?

**Comment by xet7** [comment]
Maybe. Just a moment I test.

**Comment by xet7** [comment]
That setting UI for hiding comments was removed recently, because it did not work so well.

You can try to edit MongoDB database with nosqlbooster and at boards table/collection set allowsComments to true for all boards.

**Comment by IamRFC1918** [comment]
Thank you, this hast fixed the issue. And for new Boards, it seems Comments are enabled by default.
