### ISSUE TITLE
Feature Request: Total votes / Total of possible voters

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#3047]
Would be interesting add total votes per total possible voters on card(total members on board).

Something like this:

![Screenshot_2020-04-25 Kanban -(1)](https://user-images.githubusercontent.com/24301085/80285560-4e31f980-86fc-11ea-81e2-c1c03a27aac1.png)

**Comment by helioguardabaxo** [comment]
@NicoP-S 
What do you think?

**Comment by NicoP-S** [comment]
I added this Feature.
There is also another change which allows non Board members of public Boards to vote. If this is enabled on a public Board the Total voters are hidden.

**Comment by helioguardabaxo** [comment]
Great! :D
Vote in public board is very useful.
What do you think about to add the "finish voting" feature? Maybe could have a date/time to finish. This is necessary when we have a due date to resolve a task/card.
Nowadays we just have "delete voting and all votes". If we deleted a voting, we lose all the votes.

In this scenario, in "card actions" we could have "voting in card" item. 
In the pop-over we could have "voting question:text", "public vote:check", "due date:date/hour", "save:button" and "delete:link".

And pop-over delete confirmation with this: 
- Title: Delete voting and all votes?
- Message: All votes will be removed from the voting and you won't be able to re-open the voting. There is no undo.
- "delete:button"

**Comment by helioguardabaxo** [comment]
@NicoP-S 
I don't know if you were notified for my last message suggesting some improvements. I'm citing you here. :D

**Comment by NicoP-S** [comment]
@helioguardabaxo yes i have noticed it. I started on this too. I am struggeling with the date picker. Try to commit it later on

**Comment by NicoP-S** [comment]
@helioguardabaxo this Feature does now exist. can you close the issue?
