### ISSUE TITLE
Boards are very hard to tap in mobile

### ISSUE THREAD

**Issue by brianrc** [wekan/wekan#3049]
Boards are very hard to tap to enter with my finger in mobile.  I can only enter the board from the "All Boards" page tapping on them maybe 1 in 4 tries. It seems I can enter by taping anywhere in the box, it just doesn't register most of the time.

Wekan version: 3.98.0
Operating System: Android
Chrome Mobile

**Comment by boeserwolf** [comment]
This could be caused by this commit: https://github.com/wekan/wekan/pull/3045/commits/f1b18d79cdbfd9c9edecf4f93a89e88ee1c6faea
But I did not further investigate.

**Comment by marc1006** [comment]
@boeserwolf Yep, you're right.
