### ISSUE TITLE
Card creation broken on iOS devices - you cannot select the "Add Card" textarea to create cards on iOS devices using the mobile view

### ISSUE THREAD

**Issue by davidlinc1** [wekan/wekan#3054]
Hi all, just reinstalled the latest update via docker after some time, and I'm loving how far WeKan has come. Great work!

I just wanted to bring your attention to the fact that the software is all but perfect on iOS devices except for a heart-wrenching bug that renders the core function of WeKan unusable: you cannot create cards due to a touch issue that is present on WeKan's mobile kanban view when using iOS devices.

![IatSD4ZSZV](https://user-images.githubusercontent.com/14900082/80350494-a7e21300-8825-11ea-9ec4-dd98edf0b6ea.png)

I've reproduced this on an iPhone 8, an iPad Mini, and a Browserstack account running iPhone 11. Tested both Chrome and Safari on all.

Also tested my Android Samsung Galaxy S10, where the issue is not present.

Here's a clip of the Browserstack test where I show the click events in devtools. I confirmed the textarea is indeed the target of the click so it's not being blocked. It's simply not focusing it for some reason on iOS devices. Then, note that it briefly becomes focused as I inadvertently drag the list around - you'll see the keyboard pop up:

![ezgif-2-b976e532d6c6](https://user-images.githubusercontent.com/14900082/80351170-b846bd80-8826-11ea-9abe-f1047ba5703c.gif)

Here's my WeKan instance:

![chrome_PrLl94Jjbi](https://user-images.githubusercontent.com/14900082/80350534-b92b1f80-8825-11ea-8bdc-5728dc902a5b.png)

Hopefully this information is helpful in getting the issue fixed. I was excited about WeKan and invited some colleagues into my board to collaborate on projects during a meeting, but with most of them using iPhones they couldn't create cards and I unfortunately had to sit down about it and we moved on.

**Comment by davidlinc1** [comment]
Update: I just read both the release for https://github.com/wekan/wekan/releases/tag/v3.98 which contains certain mobile fixes (though I don't see explicit mention of this issue I'm reporting) and this other open issue: https://github.com/wekan/wekan/issues/3053 - which mentions the docker package does not contain the latest version.

This may not be an issue on 4.0 as I use the docker container for convenience. I'll leave my issue open just in case this issue wasn't known within the scope of the latest mobile fixes lately.

**Comment by marc1006** [comment]
@davidlinc1 Would be great if you could update to 4.0 as soon as the docker image is available.
I've tested the current version (4.0.0) on an iPhone simulator and it worked :)

@xet7 Could you please update the docker image?

**Comment by xet7** [comment]
@marc1006 

Docker builds have failed for both Docker Hub and quay.io/wekan/wekan. I'll try to fix it.

**Comment by xet7** [comment]
This image now is built, this gets latest tag:
```
image: quay.io/wekan/wekan
```
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L118

Docker Hub has not finished building yet.

There is no version tag for this yet, because fix was this
was added after v4.00 . Next tag will be v4.01 when next
Wekan version will be released.

**Comment by davidlinc1** [comment]
Woohoo! I should have known it was already fixed! I just verified the issue is not present on 4.00 on my iOS devices after pulling the latest.

Thank you to @xet7 and others for spending their precious time and energy on making WeKan awesome!
