### ISSUE TITLE
Bug height cards in home

### ISSUE THREAD

**Issue by andynhoo** [wekan/wekan#3057]
![22222](https://user-images.githubusercontent.com/7599346/80383475-fd480f80-8879-11ea-9659-be308adfd811.png)
![11111](https://user-images.githubusercontent.com/7599346/80383479-fde0a600-8879-11ea-8526-5067c258dd63.png)

Bug in css height auto.
Change to fixed value

**Comment by xet7** [comment]
This feature allows board icons to have variable height, depending on how much text etc that icon has. https://github.com/wekan/wekan/issues/3041#issuecomment-619362808

https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v398-2020-04-25-wekan-release
