### ISSUE TITLE
Make database name configurable

### ISSUE THREAD

**Issue by Sh4pe** [wekan/wekan#306]
In my setup, I'm using a `mongodb` instance that is shared across several services, not the single instance of `mongod` that works dedicated for *wekan* inside a docker box, as proposed in the [Dockerfile](https://github.com/wekan/wekan/blob/devel/Dockerfile#L4).

In such a shared setup, it would be nice (necessary even) to change the database name that *wekan* uses. Right now, the default DB name seems to be `admin`.

It should be (easily) possible to configure the *wekan* server to use a different database name.

**Comment by Sh4pe** [comment]
If noone is already working on this (or if this is even already possible - tell me!) I'd volunteer to do it. Might be a nice start in NodeJS for me :)

**Comment by mquandalle** [comment]
Hi David,

The database is already configurable, at least with the raw-installation. It works by setting the `MONGO_URL` environment variable to a MongoDB URI. You can see one usage example of that [in the wiki](https://github.com/wekan/wekan/wiki/Install#install-a-wekan-release):

```js
export MONGO_URL='mongodb://127.0.0.1:27017/wekan'
```

In this example the mongo server IP is `127.0.0.1` (ie localhost), the port is `27017` (default for MongoDB` and the database name is `wekan`.

Does that help?

**Comment by Sh4pe** [comment]
Yes, this solves my problem. Thank you and sorry for not reading the wiki properly :smile:

**Comment by mquandalle** [comment]
It's all fine, I need to work on the documentation :)
