### ISSUE TITLE
Added Background Image and some styles to Wekan via Stylebot

### ISSUE THREAD

**Issue by B-iggy** [wekan/wekan#3060]
**Problem description**:
It's not a problem. I just want to say hello and share something 👋
After Trello bothered me more and more with Atlassian account registrations I searched for an alternative - so here I am.
In the ~5 hours I read about Wekan, searched in Wekan, installed Wekan (first over snap, then Docker for better performance) and then imported the Trello board to Wekan smoothly, I wanted to share a little CSS code if I may.

The deal for one team member to switch from Trello to Wekan was "I need a Background Image!!". Challenge Accepted I thought 😸

Screenshot:
![image](https://user-images.githubusercontent.com/7815434/80517755-d1b24b80-8985-11ea-8f59-85184699f5ce.png)

I am using the Stylebot Chrome extension:
https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha

This is the code you can paste there then:
```
div.viewer p {
    font-weight: bold;
}

.board-wrapper .board-canvas {
    background-image: url("https://i.imgur.com/5oX8f65.jpg");
    background-size: cover;
}

.swimlane, .list {
    background: none;
}

.list-body {
    padding: 0;
}

.list {
    margin: 0 4px;
    border-left: none;
}

.list-body .minicards {
    background: #283848;
    padding: 5px 10px;
    display: inline-table;
    border-radius: 0 0 5px 5px;
}
```
I've read the wiki about [CSS Themes](https://github.com/wekan/wekan/wiki/Custom-CSS-themes) so maybe this helps someone.
If you want a different background image you can just replace the imgur link above with something from https://unsplash.com. It's where I got that image from.
Based on the image you can then change the background color in the CSS minicards block.
I couldn't add proper html wrapper for now, so I did a trick with `display: inline-table` on the minicards, to keep the scrolling + overflow mechanic.
Just make sure to not select the "Dark" or "relax" Background Color for the Board.

Anyways, so far Wekan looks great and thank you for sharing it! Maybe I can dive more into it over time and share my findings.

**Comment by xet7** [comment]
Moved to #486
