### ISSUE TITLE
Add better CI integration

### ISSUE THREAD

**Issue by marc1006** [wekan/wekan#3065]
- [ ] basic integration: generate OpenAPI docs
- [ ] lets run it for new pull requests
- [ ] integrate tests as soon as they are available (see https://github.com/wekan/wekan/issues/3055)
- [ ] generate code coverage reports

There is a `.travis.yml` file, is it currently used by Travis-CI?

**Comment by xet7** [comment]
Travis has discontinued free usage for OSS. And seems that @marc1006 is busy elsewhere, not at Wekan anymore.
