### ISSUE TITLE
Spaces between boars in v4

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#3067]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:
Debian Testing Docker

* Did you test in newest Wekan?: Yes
* Wekan version: 	4.01.0

* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any : Apache

* Node Version:12.16.3
* MongoDB Version:4.2.3
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? 

Chromium 84

Wekan works fine but with the latest upgrade I see spaces between the boards, which was not the case previously. I am not sure if this is intentional or not, so I am just reporting it. 

Please see the image for the gray areas. I use the DarkReader addon for Chrome that is why the bg is gray, however the spaces are still there even twhen the addon is disabled.

![Photoshop_kQgHRpTa63](https://user-images.githubusercontent.com/8519469/80653960-e0116d80-8a40-11ea-9aef-641040bc1dd0.jpg)

**Comment by xet7** [comment]
See https://github.com/wekan/wekan/issues/3057#issuecomment-620026717
