### ISSUE TITLE
Add warning popup before allowing F5 page reload, visual indicator like red dot when data is not yet saved to database, save Persistent Filter to localstorage

### ISSUE THREAD

**Issue by B-iggy** [wekan/wekan#3071]
## Issue

**Server Setup Information**:
* Did you test in newest Wekan?:
Yes
* Wekan version:
4.0.1

If I select a filter for me (member) and press F5 (reload the tab or reopen the tab) the filter is gone and I have to refilter again.
Is this a known bug or can I classify it as feature request?
If so, then please just add the filter you selected in the localstorage.

**Comment by xet7** [comment]
Wekan does cache a lot to minimongo at browserside, and that all gets lost if you clear and reload with F5. So there should be warning popup before reload.

**Comment by B-iggy** [comment]
A popup is nice, but does not solve the core issue.
F5 was just one example. 
Most common is to close the tab/browser and continue the work on next day with a new tab.
Expected: Wekan remembers the filter.

Trello does it as I said with easy localstorage handling.
![image](https://user-images.githubusercontent.com/7815434/80791421-df3c2100-8b91-11ea-808a-06276e1fc601.png)

Do you think this is possible @xet7 ?

**Comment by xet7** [comment]
Yes it is possible that it would be saved to localstorage, if someone adds code for that.

There also should be visual indicator like red dot when data is not yet saved to database.

**Comment by B-iggy** [comment]
I am still very new to Wekan but I like to code such stuff. 
But I have to first learn how I can make changes to Wekan and test it directly. Something like a Gulp task, you know. 
Thanks for your consideration!

**Comment by xet7** [comment]
Using steps 3-5 you get meteor running, it will rebuild when it notices file change:
https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm#3-fork-wekan-and-clone-your-fork

Directory Structure is here:
https://github.com/wekan/wekan/wiki/Directory-Structure
 
And developer docs here:
https://github.com/wekan/wekan/wiki/Developer-Documentation

Submitting filter code is here:
https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarFilters.js#L7

Wekan is made with Meteor fullstack web framework. Docs are here:
https://docs.meteor.com/

Meteor uses Optimistic UI:
https://blog.meteor.com/optimistic-ui-with-meteor-67b5a78c3fcf

Somewhere in docs or with Google search or at atmospherejs packages is something about how to implement that visual indicator. Another way would be to just in case also have data in localstorage.

Thanks!

**Comment by xet7** [comment]
When anonymous users are at public boards, where data can not be saved to database, I did add using cookies for saving state of Lists/Swimlanes/Calendar menu https://github.com/wekan/wekan/commit/351d4767d7e93c90ac798769d6071da8730d834f but because that requires reload of page with F5 to take effect, maybe it could work better with localstorage.

**Comment by xet7** [comment]
Without that visual indicator, it's possible that samething looks like it's saved to card, but it's not yet saved to database, webbrowser or tab is closed, and that data is lost. That visual indicator, warning popup, localstorage etc could help.
