### ISSUE TITLE
OAuth via Nextcloud causes problems with missing email

### ISSUE THREAD

**Issue by wackazong** [wekan/wekan#3079]
## Issue

I successfully set up nextcloud and wekan running in Docker for Windows with Wekan only allowing users authorizing via nextcloud. Problem is that users are created but do not have an email, which causes multiple problems down the way. Further problem is that I cannot add an email to the user, neither in user settings nor in admin panel due to errors. 

**Server Setup Information**:

Wekan and Nextcloud latest Docker images. OAuth Setup according to default docker-compose.yml by Wekan.

**Comment by xet7** [comment]
@wackazong 

What errors?

**Comment by wackazong** [comment]
I cannot receive emails from Wekan, for example :)

**Comment by wackazong** [comment]
I added the properties username and emails to the user json (they were missing) in the db and now its working normally

**Comment by nickian** [comment]
I'm having this same issue. What do you mean the "user json" ? Where exactly is this file that you had to add values to? I don't see a reference to this in the docker-compose.yml file.

I have the following set. Are these incorrect values?:

```yml
      # The claim name you want to map to the unique ID field:
      - OAUTH2_ID_MAP=id
      # The claim name you want to map to the username field:
      - OAUTH2_USERNAME_MAP=id
      # The claim name you want to map to the full name field:
      - OAUTH2_FULLNAME_MAP=display-name
      # Tthe claim name you want to map to the email field:
      - OAUTH2_EMAIL_MAP=email
```

**Comment by xet7** [comment]
@nickian 

Wekan needs the following:
```
      - OAUTH2_USERNAME_MAP=email
      - OAUTH2_EMAIL_MAP=email
```
https://github.com/wekan/wekan/wiki/Nextcloud
https://github.com/wekan/wekan/wiki/Google-login
