### ISSUE TITLE
Simple board template

### ISSUE THREAD

**Issue by ManuelArno** [wekan/wekan#308]
I'm always use the "TODO", "DOING" and "DONE" lists for new projects.

Would be nice if didn't have to do this every time I create a new board.

**Comment by stoufa88** [comment]
We can maybe add a select for available templates. A simple board template can hold lists for "TODO", "DOING" and "DONE". Or just add a checkbox for creating default lists.

**Comment by mquandalle** [comment]
I'm been thinking about this template feature. As a always try to keep things simple especially in the code base, I feel that being able to clone a board (as requested in #134) would basically solve this issue — calling a particular board a “template” then became nothing more than a calling convention.

Thoughts?

**Comment by mkorfmann** [comment]
Perfect solution!

**Comment by zeineath** [comment]
:+1:

**Comment by chrauscher** [comment]
That will work

**Comment by xet7** [comment]
https://github.com/wekan/wekan/pull/446 will be merged later.
