### ISSUE TITLE
Feature Request: internationalization

### ISSUE THREAD

**Issue by 71ae** [wekan/wekan#3080]
It would be great if the **calendar view** could be customized for internationalization, e.g. week start (Sunday or Monday), date format (mmm/dd, dd.mm.yy, yyyy-mm-dd), and time format (12hr/am/pm, 24hr).

**Comment by marc1006** [comment]
@71ae With the current version of Wekan it should be possible to set the week start (see https://github.com/wekan/wekan/pull/3032).
