### ISSUE TITLE
Feature Request: Add Currency Format Option for Custom Fields

### ISSUE THREAD

**Issue by signalcodec** [wekan/wekan#3082]
Would it be possible to add a format, similar to 'number' but with a currency format with currency signs ($) and comma's where appropriate.

**Comment by Amraneze** [comment]
@signalcodec can you give us more information about the feature or an illustration please ?

**Comment by signalcodec** [comment]
![Capture](https://user-images.githubusercontent.com/61852162/82160521-d4001b00-984a-11ea-85b9-0938876fc2c0.PNG)

I'm looking for an additional Custom Field "Type" for Currency... that would show numbers as $***,***.** e.g. $100,000.00.

**Comment by habenamare** [comment]
@signalcodec Is your feature request implemented?

**Comment by xet7** [comment]
AFAIK Currency format custom field is already at newest Wekan.

**Comment by habenamare** [comment]
This issue is not closed at Bountysource. @xet7 Can you check the integration? Maybe using [Bountysource Tools](https://www.bountysource.com/tools)?

**Comment by xet7** [comment]
@habenamare 

Please claim bounty at:
https://www.bountysource.com/issues/91369519-feature-request-add-currency-format-option-for-custom-fields

**Comment by xet7** [comment]
@habenamare 

It could be the button "Solve issue"

**Comment by habenamare** [comment]
> @habenamare
> 
> Please claim bounty at:
> https://www.bountysource.com/issues/91369519-feature-request-add-currency-format-option-for-custom-fields

I know but claiming is enabled only if the issue is closed at Bountysource. And since the issue at Bountysource is a mirror of this GitHub issue, with a correctly working integration

**Comment by xet7** [comment]
@habenamare 

Maybe it requires this issue is open. Now try to claim it.

**Comment by habenamare** [comment]
@xet7 
Thanks for your suggestions, but a claim can only be submitted if the issue is detected as closed at Bountysource. I am sure because I have encountered this same issue before in another repo and the fix was integrating Bountysource with the repo correctly.

For reference, checkout the [Bountysource FAQ](https://github.com/bountysource/core/wiki/Frequently-Asked-Questions).

**Comment by xet7** [comment]
@habenamare 

I did close this. Try to login to bountysource and claim it. I could not figure out how to integrate it better, it seems it's integrated already.

**Comment by xet7** [comment]
Also other Wekan contributor has already claimed other bounty, so I don't know what is missing.

**Comment by habenamare** [comment]
Thanks for trying, maybe detecting a closed GitHub issue takes some time.
