### ISSUE TITLE
WSL install

### ISSUE THREAD

**Issue by WingDust** [wekan/wekan#3085]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: NO
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 4
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Window10 WSL2
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:14.2
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**Problem description**:
- I use Window 10 and WSL2 within Archlinux 
- I want to install wekan in WSL2 but I looking up wiki , it too difficult to me try to install wekan for a beginer
- I want to have a better doc or example for reference

**Comment by xet7** [comment]
@WingDust 

Are you trying to:
a) Install Wekan for using it?
b) Develop new features for Wekan?

**Comment by xet7** [comment]
Archlinux is not a beginner distro. Wekan wiki docs are only for Ubuntu and Debian.

**Comment by WingDust** [comment]
a 

i want to build own soft ecological environment from zero ,so archlinux will be better

**Comment by xet7** [comment]
@WingDust 

Whoa, I don't know what "soft ecological environment" means, but anyway:

1) For using Wekan, you do not need WSL/WSL2 or Arch Linux at all. You only need Windows version of Node 12.x and any MongoDB 3.2.x - 4.x (preferably newest 4.x), unzip wekan .zip file, edit start-wekan.bat for ROOT_URL setting, like when at https://wekan.github.io click Windows, bundle instructions.

2) For developing Wekan with WSL or WSL2, you install Node 12.x and MongoDB 3.2.x - 4.x, although I don't know does MongoDB work on WSL2 Arch Linux. Ubuntu/Debian install info is at steps 3-5 at https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm#3-fork-wekan-and-clone-your-fork so for Arch, you try does installing Meteor etc dependencies work, with Arch package manager commands, that are similar that apt-get/dpkg on Ubuntu/Debian.

**Comment by xet7** [comment]
@WingDust

Can you give link to definition of "soft ecological environment" so I would learn what is it all about?
