### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by chicofariasneto** [wekan/wekan#3089]
I created a card, and i tried to see it.

Not Found - The requested URL was not found on this server.

I using windows, and didn't find any support about this problem for windows. 

i setup the root-url on localhost, and the port is 2000.

**Comment by xet7** [comment]
```
ROOT_URL=http://localhost:2000
PORT=2000
```

**Comment by chicofariasneto** [comment]
> ```
> ROOT_URL=http://localhost:2000
> PORT=2000
> ```

It works. Thanks!
