### ISSUE TITLE
Markdown in card descriptions and titles

### ISSUE THREAD

**Issue by GummyBear101010** [wekan/wekan#309]
Sometimes I just want to make **shit bold**. :)

**Comment by storrgie** [comment]
I may be incorrect, but I just farted around with the sandstorm demo and it looked like the description was limited supporting md (headers, lists).

Either way, I second your request for full markdown support.

**Comment by zeineath** [comment]
hmm.. this is odd... i'm able to make things bold by enclosing the string with two(2) asterisks, before and after.

**Comment by mquandalle** [comment]
Hum, unless I misses something the card description already support text emphasize using `*italic*` or `**bold**`. Not sure if we want to support that in card titles as well.

**Comment by ceymard** [comment]
Could it be possible to integrate « github's flavoured markdown » ? Notably, I'd like the possibility to add checkmarks into my description...

**Comment by tubia** [comment]
+1 to @ceymard proposal. Until we got proper check-lists :)

**Comment by Cooker-Monster** [comment]
+1 for Markdown/GFM syntax in Description field (but thx a lot for the good job already done !)

**Comment by xet7** [comment]
Moved to #926
