### ISSUE TITLE
doc for Raspberry-Pi may have typo

### ISSUE THREAD

**Issue by eMUQI** [wekan/wekan#3091]
hi, i follow [this page](https://github.com/wekan/wekan/wiki/Raspberry-Pi/21af87a781474f52b2d5a81df01fd03bca089dcd#install-wekan-to-raspi3-raspi4-or-any-arm64-server) trying to install Wekan on RasPi 4.

i saw 
```bash
sudo apt-get install npm mongodb-server mongodb-clients mongodb-tools zip unzip
```
but there is an error:
```
E: Unable to locate package mongodb-tools
```
then i search on internet and found `mongo-tools`  may is right (i am not sure), then i  use `mongo-tools`  and everything performed well throughout the rest of installation.

Is that a typo? Or did I install it by mistake?

thanks for reading my issue ！

**Comment by eMUQI** [comment]
and maybe this line has wrong hyperlink

> There are many more other possible settings here that you can optionally add

**Comment by hickorysb** [comment]
I do believe the `mongodb-tools` bit is a mistake and should be `mongo-tools`. However, that link seems to be spot on. While that could be put into a document that is much easier for a human to read that document does seem to include most, if not all, the other options you could include in that file along with examples.

**Comment by xet7** [comment]
Fixed. Thanks!
