### ISSUE TITLE
Bug: Can't Scroll on All Boards Screen in iOS

### ISSUE THREAD

**Issue by laslomcd** [wekan/wekan#3096]
![RPReplay-Final1589571887](https://user-images.githubusercontent.com/11617046/82090887-632ef680-96c4-11ea-8a75-c158872407ac.gif)

![Screen Shot 2020-05-15 at 3 57 18 PM](https://user-images.githubusercontent.com/11617046/82091111-ce78c880-96c4-11ea-9194-55e1f50e7873.png)

You can't scroll past the first few boards in iOS. This is on Chrome Mobile and Safari
I have 20 boards but am unable to get past the first 7 to see the rest.

**Comment by xet7** [comment]
Yes, I'll try to fix this.
