### ISSUE TITLE
Feature Request: Import Custom Fields from Trello

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3097]
Import Custom Fields from Trello, if they are not imported yet.

Also check other custom fields issues.

**Comment by jrsupplee** [comment]
@xet7 

I have been working on putting together a pull request for import Trello custom fields.  You can look at the changes at: https://github.com/wekan/wekan/issues/new

As part of the import code, I also created a new custom field type of `checkbox` to match the Trello checkbox custom field.

![image](https://user-images.githubusercontent.com/1286169/105015192-f4235200-5a49-11eb-83df-f5911092b63a.png)

The code is working on my tests, but this code in `forms.styl` keeps an input of type checkbox from being displayed.

```
[type="checkbox"]:not(:checked),
[type="checkbox"]:checked
  position: absolute
  left: -9999px
  visibility: hidden
```

I have commented this out to get my checkbox input to display.  Are these styles necessary for other forms?

**Comment by xet7** [comment]
@jrsupplee 

Do you mean it should work like at checklists?
https://github.com/wekan/wekan/tree/master/client/components/cards

When importing that from Trello to Wekan, you can for example:
a) search-replace it with `true/false` boolean to have it checked or unchecked, at `wekan/models/*.js` boolean field
b) Copy checklist style code to show it with animation
c) Or replace it with unicode checkmark, if it's for viewing only.
d) Replace it with some markdown code that you show with `+viewer`

**Comment by xet7** [comment]
@jrsupplee 

I think you maybe have wrong link to your code?

**Comment by jrsupplee** [comment]
> @jrsupplee
> 
> I think you maybe have wrong link to your code?

https://github.com/jrsupplee/wekan/tree/trello-import

**Comment by xet7** [comment]
@jrsupplee 

If you get it working, you can add a new pull request to Wekan, without your sample data. Thanks!

**Comment by xet7** [comment]
@jrsupplee 

Related to Import/Export, are you interested in adding more fields to first version export to Excel XLSX ? Similar like those fields already exist on CSV/TSV export? I just a moment ago added this new commit to Wekan repo:
https://github.com/wekan/wekan/commit/855151a8d18c14ec26a1ef09977b0f98f4c32759

With some code, it could maybe be possible to also import Excel: https://github.com/exceljs/exceljs

**Comment by jrsupplee** [comment]
![image](https://user-images.githubusercontent.com/1286169/105033882-62274380-5a61-11eb-9c8e-d5337e031a3a.png)

@xet7 

I'll send a pull request for this.

You don't want to have some JSON data in the repository for testing Trello import?

**Comment by jrsupplee** [comment]
> @jrsupplee
> 
> Related to Import/Export, are you interested in adding more fields to first version export to Excel XLSX ? Similar like those fields already exist on CSV/TSV export? I just a moment ago added this new commit to Wekan repo:
> [855151a](https://github.com/wekan/wekan/commit/855151a8d18c14ec26a1ef09977b0f98f4c32759)
> 
> With some code, it could maybe be possible to also import Excel: https://github.com/exceljs/exceljs

It is not functionality that I need right now.  Want to move some boards from Trello with custom fields.

**Comment by xet7** [comment]
@jrsupplee 

> You don't want to have some JSON data in the repository for testing Trello import?

No, it's not needed, and I can always get newest JSON data from Trello.

>> Related to Import/Export, are you interested in adding more fields to first version export to Excel XLSX ?
> It is not functionality that I need right now.  Want to move some boards from Trello with custom fields.

OK, I will add remaining of Excel code. Thanks!

**Comment by xet7** [comment]
@jrsupplee 

Actually, let that JSON data for testing Trello be in repo, if that does not have any private data. I'll use it for testing. Thanks!

**Comment by jrsupplee** [comment]
@xet7 
> OK, I will add remaining of Excel code. Thanks!

Sorry, I have been quite selfish in my contributions.  They have all been things I see as essential to move away from Trello to Wekan.  In the future I will see about helping with some other issues.

**Comment by xet7** [comment]
@jrsupplee 

Of course, and you should be selfish in your contributions also in the future. Everyone has it's own priorities. Thanks a lot!
