### ISSUE TITLE
strange problem : user swaped or overloaded

### ISSUE THREAD

**Issue by salleman33** [wekan/wekan#3099]
Hi, 

**Server Setup Information**:
- Wekan 4.01.0
- deploy on Openshift
- Meteor : 1.10.2
- Nodejs : 12.16.3
- Mongo : 3.6.3

**Problem description**:
I have problems with some users being swaped or overloaded. I explain : 
A few week ago, I saw in a board that an user (A) has been replaced by user (B). On the mongoDB, user A did not exist anymore and user B had the same ID of previous User A. It's like User B had overloaded user A and kept the same ID, so he has same access to boards, etc.
Today, I have an other problem : 
User C has their informations suddendly cleared : no username, no mail, no first name, etc.
On mongodb, I can find user C. But on the board member, there is not User C but an other ID members (123456). If I search this Id user on mongodb, there is nothing... 

 Do you encoutered this error ? How can I debug this ? Is there a debug mode ? 

On the wekan pod in openshift, there are sometime some error like that : 
```
Exception while invoking method 'login' RangeError: Maximum call stack size exceeded:
at Object.hasOwnProperty (<anonymous>)
    at hasOwn (packages/ejson/utils.js:9:70)
    at isArguments (packages/ejson/utils.js:17:50)
    at Object.EJSON.clone (packages/ejson/ejson.js:583:7)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
    at packages/ejson/ejson.js:600:22
```

Thanks for your help

**Comment by xet7** [comment]
@salleman33 

Can you try using newest MongoDB 4.x by using just docker tag `mongo` without any version number? I don't know is that MongoDB bug that is already fixed in newest MongoDB version.

Does your Wekan have enough RAM? If it does not have, it starts swapping, and slows down.

Also, if database gets out of disk space, it will corrupt.

You could Google search what that error message means.

**Comment by salleman33** [comment]
Hi, 
Yes, RAM and disk space are ok. I will try mongo v4.
Is there a way to enable a debug mode ?

**Comment by xet7** [comment]
@salleman33 

You could login inside of wekan-app grain and look what code is at packages/ejson/utils.js line 9 char 70, and also other lines of code.

You could enable debug, although I don't know how much it would help, because you already did see that error message from somewhere:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L327

**Comment by salleman33** [comment]
Hi, 
I have a lot of error like this. Do you know if it coult be the problem ? 

```
Exception in removedobserveChanges callback: Error: Removed nonexistent document xHfWd8b2YkCT2NpLB
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:394:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
    at Subscription.subscriptionProto.<computed> [as removed] (packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:89:30)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at runWithEnvironment (packages/meteor.js:1286:24)
    at packages/meteor.js:1299:14
    at packages/mongo/observe_multiplex.js:178:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:172:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
    at packages/meteor.js:894:12

```

**Comment by xet7** [comment]
@salleman33 

That meteor-apm-agent is Kadira integration #2152. You can setup Kadira if you like to debug it more.

@GavinLilly 

Do you have ideas about this error?

**Comment by GavinLilly** [comment]
I saw this kind of error message before I integrated Kadira.
I think the fact that meteor-apm-agent shows up in that exception stack is a misdirection because the agent hijacks errors for debug reporting.
I was never able to find the source of the `nonexistent document` error though.

I'm curious @salleman33, I see you're using Openshift. Are you load balancing across multiple pods? It could be that those multiple instances are entering a kind of race condition for dealing with requests...

**Comment by salleman33** [comment]
@GavinLilly : No, I use an unique pod for wekan app.

**Comment by salleman33** [comment]
To add some information for my initial problem: it seems that sometimes, user accounts are mysteriously deleted. 
Are there some cron tasks ? I use OIDC for authentification and I have see that some infos like "resume loginsToken" (see below) were cleaned periodically. 

```

 db.users.find({"username":"salleman"}).pretty()
{
	"_id" : "hgtrNyjpBKjBvMqy2",
	"createdAt" : ISODate("2020-04-14T11:49:44.124Z"),
	"services" : {
		"oidc" : {
			"id" : "xxxxxxxxx",
			"username" : "salleman",
			"fullname" : "xxxxxxxx",
			"accessToken" : "xxxxxxxx",
			"expiresAt" : 1591260986360,
			"email" : "xxxxxxxx"
		},
		"resume" : {
			"loginTokens" : [
				{
					"when" : ISODate("2020-03-18T22:43:06.987Z"),
					"hashedToken" : "pWtTaNYEJNcjU9U3L9GUBubJOCRH7EPHTrUvchigZs4="
				},
				{
					"when" : ISODate("2020-04-01T09:45:25.459Z"),
					"hashedToken" : "FxqwNLT2K86R44EJ64eSywSy8kcyiOZdq0pohYd/KXc="
				},
				{
					"when" : ISODate("2020-04-14T11:50:17.279Z"),
					"hashedToken" : "v0/YC2ynU6IIbksBG42UMMwPUni+cho6jYANi8/Q08o="
				},
....
```

**Comment by xet7** [comment]
@salleman33 

Yes, there are these cron tasks:
- [Notification drawer like Trello, cleanup of notifications](https://github.com/wekan/wekan/pull/2975) and [fix to that cron](https://github.com/wekan/wekan/pull/3010)
- [LDAP users sync](https://github.com/wekan/wekan/pull/2555)

@pshunter @jtbairdsr Do you have any idea about this?

**Comment by jtbairdsr** [comment]
I think that there is potential of a race condition if you have two instances running at the same time on the same database... but I don't know of any way for a user to get over written or to get replaced...

**Comment by xet7** [comment]
Is this related to #3259 ?

**Comment by salleman33** [comment]
Hi,
my issue was resolved with the 3206 pull request

**Comment by xet7** [comment]
Thanks!
