### ISSUE TITLE
Port Change

### ISSUE THREAD

**Issue by patrickave** [wekan/wekan#3100]
Hello, I am attempting to run the docker-compose stack.  I have a static macvlan I use for my hosted apps in my docker lab.  I am attempting to use wekan and have it publish to port 80 but it keeps defaulting to 8080.  I have modified the Dockerfile but it keeps reverting back to 8080.  Is there a specific value being used or forced AFTER the container comes up?  I've tried adding environment variable overrides to the docker-compose.yml but it has been unsuccessful.

**Comment by xet7** [comment]
```
docker-compose stop
```
Then check your ports:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L145-L149
```
docker-compose start
```

**Comment by patrickave** [comment]
Its due to the linux instance blocking the use of power ports.  I traced the system logs to find the access denied.  I decided to just run a simple reverse proxy using nginx.
