### ISSUE TITLE
Strange homepage presentation for tables

### ISSUE THREAD

**Issue by sclerc-chss** [wekan/wekan#3101]
**Server Setup Information**:

* Did you test in newest Wekan?: yes 
* Wekan version: 4.03.0
* Operating System:Debian 9.9
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: 12.16.3
* MongoDB Version: 3.2.22
* What webbrowser version are you using? bug confirmed on Firefox 68.8.0esr, Chrome 81, Vivaldi 3.0

**Problem description**:
We have tables with differents sizes of titles and descriptions, the presentation is very strange since 4.03 (my last version before were 3.97 and we haven't this bug).

![image](https://user-images.githubusercontent.com/53857862/82323917-093a7380-99d9-11ea-943d-6499cc7588b9.png)

Thank you.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/issues/3057
