### ISSUE TITLE
Enabling webhooks causing changes to all boards not to save

### ISSUE THREAD

**Issue by signalcodec** [wekan/wekan#3105]
When enabling webhooks, the wekan boards will only 'save' one action at a time before having to refresh.

If we add a card, we have to refresh to add a second. If we change a card, we have to refresh to change something else (you get the idea).

If we don't refresh after each change, anything past the first change is not kept.

It even goes as far as if we make a change, we can't log-out or get to the admin menu without refreshing first.

Clearing the webhooks config in the admin menu resolves the issue immediately.

**Comment by destrus3** [comment]
Same here, check if your web-api sends back response-code(eg. 200), that solves my problem.
