### ISSUE TITLE
ostrio-files errors

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3110]
In newest Wekan bundle I'm getting some errors related to https://github.com/wekan/wekan/pull/3090

s390x:
```
linux1@xvm ~]$ ./start-wekan.sh 
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Presence started serverId=2e52ASWoR7ina3Cbc
/home/linux1/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /home/linux1/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/lib/binding/node_libcurl.node: ELF file data encoding not big-endian
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Module.Mp.load (/home/linux1/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/linux1/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/dist/Easy.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.Mp._compile (/home/linux1/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Module.Mp.load (/home/linux1/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/linux1/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/dist/Curl.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.Mp._compile (/home/linux1/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Module.Mp.load (/home/linux1/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/linux1/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/dist/index.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.Mp._compile (/home/linux1/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
```
arm64:
```
$ ./start-wekan.sh 
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Presence started serverId=7FrBdnKxtWD84779r
/home/wekan/repos/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /home/wekan/repos/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/lib/binding/node_libcurl.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Module.Mp.load (/home/wekan/repos/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/wekan/repos/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/dist/Easy.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.Mp._compile (/home/wekan/repos/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Module.Mp.load (/home/wekan/repos/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/wekan/repos/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/dist/Curl.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.Mp._compile (/home/wekan/repos/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Module.Mp.load (/home/wekan/repos/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/wekan/repos/bundle/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/dist/index.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.Mp._compile (/home/wekan/repos/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
```
Also, snap builds seems to fail so I need to delete these garbage in build scripts:
```
programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/.node_modules-garbage*
```
Still testing...

**Comment by xet7** [comment]
For arm64 bundle, I did install again request-libcurl, but then I got this error:
```
Presence started serverId=n7tinswiQyri6ZwAR
node[10698]: ../src/api/hooks.cc:28:void node::AtExit(node::Environment*, void (*)(void*), void*): Assertion `(env) != nullptr' failed.
 1: 0xa07028 node::Abort() [node]
 2: 0xa07098 node::errors::SetPrepareStackTraceCallback(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 3: 0x9848dc  [node]
 4: 0x9e38e0  [node]
 5: 0x9e2cb8 node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 6: 0xbd10fc  [node]
 7: 0xbd2a8c v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 8: 0x134de0c  [node]
./start-wekan.sh: line 361: 10698 Aborted                 node main.js
```
For Wekan Snap x64, I got it finally built, but now it seems directory is missing:
```
May 24 08:12:43 localhost wekan.wekan[22028]: > Starting change-attachment-library migration.
May 24 08:12:43 localhost wekan.wekan[22028]: events.js:287
May 24 08:12:43 localhost wekan.wekan[22028]:       throw er; // Unhandled 'error' event
May 24 08:12:43 localhost wekan.wekan[22028]:       ^
May 24 08:12:43 localhost wekan.wekan[22028]: Error: ENOENT: no such file or directory, open 'assets/app/uploads/attachments2/IMG_20180223_135054.jpg'
May 24 08:12:43 localhost wekan.wekan[22028]: Emitted 'error' event on WriteStream instance at:
May 24 08:12:43 localhost wekan.wekan[22028]:     at errorOrDestroy (internal/streams/destroy.js:108:12)
May 24 08:12:43 localhost wekan.wekan[22028]:     at WriteStream.onerror (_stream_readable.js:729:7)
May 24 08:12:43 localhost wekan.wekan[22028]:     at WriteStream.emit (events.js:310:20)
May 24 08:12:43 localhost wekan.wekan[22028]:     at WriteStream.EventEmitter.emit (domain.js:482:12)
May 24 08:12:43 localhost wekan.wekan[22028]:     at internal/fs/streams.js:321:12
May 24 08:12:43 localhost wekan.wekan[22028]:     at FSReqCallback.oncomplete (fs.js:155:23) {
May 24 08:12:43 localhost wekan.wekan[22028]:   errno: -2,
May 24 08:12:43 localhost wekan.wekan[22028]:   code: 'ENOENT',
May 24 08:12:43 localhost wekan.wekan[22028]:   syscall: 'open',
May 24 08:12:43 localhost wekan.wekan[22028]:   path: 'assets/app/uploads/attachments2/IMG_20180223_135054.jpg'
May 24 08:12:43 localhost wekan.wekan[22028]: }
```

**Comment by cmF3** [comment]
Same thing is happening for me when upgrading to Wekan 4.04, Wekan 4.04 does not work after the update.

```
> node-libcurl@2.1.1 install /usr/home/wekan/4.04/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.1.1/node_libcurl-v2.1.1-node-v79-freebsd-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.1.1 and node@13.10.1 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
gmake: Entering directory '/usr/home/wekan/4.04/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/build'
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
../src/node_libcurl.cc:55:9: warning: 'AtExit' is deprecated: Use the three-argument variant of
      AtExit() or AddEnvironmentCleanupHook() [-Wdeprecated-declarations]
  node::AtExit(AtExitCallback, NULL);
        ^
/home/wekan/.cache/node-gyp/13.10.1/include/node/node.h:710:1: note: 'AtExit' has been
      explicitly marked deprecated here
NODE_DEPRECATED(
^
/home/wekan/.cache/node-gyp/13.10.1/include/node/node.h:107:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
1 warning generated.
  CXX(target) Release/obj.target/node_libcurl/src/Easy.o
../src/Easy.cc:241:30: warning: unused variable 'returnValueCallback' [-Wunused-variable]
  Nan::MaybeLocal<v8::Value> returnValueCallback = asyncResource.runInAsyncScope(
                             ^
../src/Easy.cc:1639:11: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
          arr->Set(arr->CreationContext(), arr->Length(),
          ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
  CXX(target) Release/obj.target/node_libcurl/src/Share.o
  CXX(target) Release/obj.target/node_libcurl/src/Multi.o
  CXX(target) Release/obj.target/node_libcurl/src/Curl.o
  CXX(target) Release/obj.target/node_libcurl/src/CurlHttpPost.o
  CXX(target) Release/obj.target/node_libcurl/src/CurlVersionInfo.o
../src/CurlVersionInfo.cc:19:6: warning: unused function 'SetObjPropertyToNullOrValue'
      [-Wunused-function]
void SetObjPropertyToNullOrValue<v8::Local<v8::Primitive>>(v8::Local<v8::Object> obj,
     ^
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/node_libcurl.node
  COPY Release/node_libcurl.node
  COPY /usr/home/wekan/4.04/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/lib/binding/node_libcurl.node
  TOUCH Release/obj.target/action_after_build.stamp
gmake: Leaving directory '/usr/home/wekan/4.04/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/build'

> node-libcurl@2.1.1 postinstall /usr/home/wekan/4.04/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl
> node scripts/postinstall

node-libcurl WARN Could not finish postinstall 
node-libcurl ERR! Error: Command failed: node "/usr/home/wekan/4.04/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/dist/index.js"
/usr/home/wekan/4.04/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/request-libcurl/node_modules/node-libcurl/lib/binding/node_libcurl.node: Undefined symbol "curl_version_info"
```

**Comment by xet7** [comment]
About that [change to Meteor-Files](https://github.com/wekan/wekan/pull/3090) by @urakagi 

Pros:
- It makes possible to upload and download attachments that have Chinese characters in filenames

Questions:
- Is it necessary to save all attachments to filesystem, so it needs to have attachments-store-path setup correctly? Could files still be stored to database?
- When attachments store path is changed, it does not change attachment paths in database. Does this need some detection code, are files at database/old path/new path?
- When files are stored to disk, what happens if there is many attachments with same filename? Do they overwrite each other, or are they renamed?
- Does Meteor-Files make it possible to use other storage than database/filesystem? How?

@marc1006 What do you think?

I presume we will figure out how to fix those node-libcurl errors in the near future.

**Comment by urakagi** [comment]
- The document says it's possible to use `GridFS`. If it's the recommended way I'll try to rewrite it.
- If the server and files itself don't change, there will be no problem. But if it's like you export a board and the importing server has a different storagePath, yes the attachments won't work.
- On the file system, the files are stored with the name from the _id. The filenames are only stored in the database record.
- I think leaving a deprecated library is not a bad idea.

So I think I'd better rewrite the `GridFS`?

**Comment by marc1006** [comment]
>     * The document says it's possible to use `GridFS`. If it's the recommended way I'll try to rewrite it.
> 
>     * If the server and files itself don't change, there will be no problem. But if it's like you export a board and the importing server has a different storagePath, yes the attachments won't work.
> 
>     * On the file system, the files are stored with the name from the _id. The filenames are only stored in the database record.

>     * I think leaving a deprecated library is not a bad idea.

Yep.

> 
> 
> So I think I'd better rewrite with the `GridFS`?

What was used before? GridFS? If yes, then I would also go with GridFS.

**Comment by urakagi** [comment]
@marc1006 The current code I wrote is using the file system. I don't really know if `wekan` was using GridFS or something else.

**Comment by marc1006** [comment]
@urakagi Okay, so I looked into the code and it was possible to use both (untested). See commit https://github.com/wekan/wekan/commit/c569565ec09b1d4d45d1870701995221ec785aea for details. `process.env.ATTACHMENTS_STORE_PATH` was used to differentiate.

So I would presume that we should also support both cases.

I've quickly looked into the new code... there you've created a new file with the name `old-attachments-migration.js`. When will this file be executed? And how does the migration work?

**Comment by urakagi** [comment]
@marc1006 That file is almost the original `models/attachments.js` and will be used for attachment migrating only.

The migration runs like this:
1. List the old attachments using `CollectionFS`.
2. Read attachment chunks from the old database then save as a new file.
3. Create a new file record using `Meteor-Files`, with needed attributes extracted from the old database. It uses a different collection name to the original one.
4. Assign the new file to the new record.

I do not remove the old record and chunks at this time to avoid data loss due to some unexpected migration errors.

**Comment by marc1006** [comment]
@urakagi Thanks for the explanation! What do you think about supporting both, GridFS and FileSystem?

Do you think the code is already ready for production? I really appreciate the migration to a maintained package, but I'm not sure whether the code is stable enough for a production release yet. BTW, I would suggest to use a linter for formatting the code as sometimes the indentation is off.

**Comment by urakagi** [comment]
@marc1006 I think it's the best. Flexibility is always good.

I don't think the code is already ready for production, it needs more test and in fact, I found a bug on my Sandstorm machine today. I think at least I need to run a version on my private production server for like a week without serious problems.

Also, since the import/export/client code permission part is not modified yet, it's not ready for the standalone version I think. (I think it's OK for the sandstorm version though)

**Comment by xet7** [comment]
I'll try does reverting that ostrio-files changes work, if really attachments are still at database, because currently ostrio-files does not work on arm64 and s390x.

**Comment by xet7** [comment]
Hmm, actually, there are some fixes in pull requests. Maybe we'll see first if this can be fixed.

Code should be changed so that files are not written to disk, they should stay at database. Most users only backup database, not other files.

**Comment by xet7** [comment]
I think I'll move ostrio-files changes to other branch, and revert ostrio changes in master, and try to get working version released for all platforms.

**Comment by xet7** [comment]
When I reverted ostrio-files changes, I got these working:
- Building for arm64 and s390x
- Export to CSV/TSV with Custom Fields that did work once, but may have some more problems here https://github.com/wekan/wekan/issues/395#issuecomment-633719121 , and it does not work on Sandstorm yet #3094

I could not get ostrio-files yet working on arm64/s390x. I'll think later what would be possible to do.

**Comment by xet7** [comment]
Also, that ostrio-files related code should not save attachments to disk.

**Comment by urakagi** [comment]
Okay, I'll change to GridFS then re-send a PR ti `feature-ostrio-files`.

**Comment by marc1006** [comment]
@xet7 
> Also, that ostrio-files related code should not save attachments to disk.

It was possible to store the attachments on disk and on GridFS -  see commit https://github.com/wekan/wekan/commit/c569565ec09b1d4d45d1870701995221ec785aea for details. process.env.ATTACHMENTS_STORE_PATH was used to differentiate. 

@urakagi So I would ask you to support both - if feasible.

**Comment by urakagi** [comment]
@marc1006 I guess it's a policy choice, it's also reasonable to limit only GridFS storage for a uniformed backup operation. By the way, the Sandstorm version does not have the filesystem and backup problem since it's all in a grain.

**Comment by xet7** [comment]
@urakagi 

Also in Sandstorm, it's useful to be able to save files to grain filesystem, so when downloading .zip file of grain, attachments are directly in the .zip file. So there should be some UI options to move attachments to filesystem, to database, or somewhere else what ostrio-files makes it possible. Also, there should be possibility to edit path of attachments.

Most likely ostrio-files needs more fixes and testing, because I was not able to get it working on arm64 and s390x yet.

**Comment by urakagi** [comment]
@xet7 

Okay, but it seems like a long plan. I'll just separate them by if `process.env.ATTACHMENTS_STORE_PATH` is set at this time.

**Comment by xet7** [comment]
@urakagi 

Yes, if `ATTACHMENTS_STORE_PATH = ""` (empty, not set) then it should use database.

**Comment by urakagi** [comment]
@xet7 I think simply `if (ATTACHMENTS_STORE_PATH)` will work?

**Comment by xet7** [comment]
@urakagi 

It should be similar to https://github.com/wekan/wekan/blob/master/server/scroll.js

You check for `!== ''` (empty string), and set public variable so you can read it also clientside.

**Comment by xet7** [comment]
Well, depending is that needed at clientside at all.

For serverside, there is checks at `wekan/models/*.js` like this:
```
if (Meteor.isServer) {
```
For clientside, for elsewhere:
```
if (Meteor.isClient) {
```
If it's not defined, then it runs at both. For example, permission checks etc should run at serverside.

**Comment by xet7** [comment]
For settings, usually they are tested are they empty string, because Snap/Docker/Sandstorm settings are made with environment variables often defaulting to empty string. That variable still can be null or something other and still exist, so checking only for existence is not enough, I think

**Comment by urakagi** [comment]
Hmm? But we treat empty string and null and undefined the same here right? Since in Javascript empty string has a false value, I think checking it's true-false value is enough?

**Comment by marc1006** [comment]
@urakagi It depends on whether the empty string is a valid value or not (I assume in this case it's not a valid value). But for example, a common problem with the `||` operator is that the number 0 is evaluated as false, but actually it could be a valid value.

**Comment by urakagi** [comment]
When I implement the database storage, I found it seems like storing files in the database has another risk when downloading: [See this link](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Bucket-Integration)

> Please note - by default all files will be served with 200 response code, which is fine if you planning to deal only with small files, or not planning to serve files back to users (use only upload and storage). For support of 206 partial content see this article.

It looks like bad for wekan. @xet7 do you think the backup policy worth working around this?

**Comment by xet7** [comment]
@urakagi 

Reading whole files to memory slows down Wekan, so it's better to save to filesystem.

Could there be some check that there is enough free disk space? And show warning in Wekan, preventing adding data to Wekan if disk space is low? Because MongoDB will get corrupted if disk gets full. Although that would be more of a "nice to have" but not a "must".

For safety reasons, I think original attachments should not be removed from database.

I think I'll try to make ostrio-files branch up-to-date and do some more testing with attachment paths at various platforms.

Does having different paths at different platforms affect import/export?

**Comment by urakagi** [comment]
- Sure it can be a warning, and I think it will be an extended plan.
- OK, I'll keep the old attachments there.
- I don't know how wekan's export/import works yet, but I think the import sequence can do the same thing as migrating old attachments so that the database record will have the correct path.
- Changing the attachment store path on a running server will break all the links. Well, usually, just moving the files to the new location will solve the problem IMO.

**Comment by xet7** [comment]
@urakagi 

Trello import downloads attachments and stores to database, somewhere here:
https://github.com/wekan/wekan/blob/feature-ostrio-files/models/trelloCreator.js

Wekan import converts JSON base64 encoded attachment to file and saves to database:
https://github.com/wekan/wekan/blob/feature-ostrio-files/models/wekanCreator.js#L446

So those should be saved directly to files.
