### ISSUE TITLE
errors in v4.04

### ISSUE THREAD

**Issue by GuidoDr** [wekan/wekan#3117]
I had to go back to v4.03, v4.04 does show below errors in the docker log

## Issue

wekanapp   | Presence started serverId=XcLxEdRv3ein4sPND
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=7GLA8qCuYRZ85PMKi
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=Da7jvZxDNw6TjaKqS
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=3mvzq888LAmPZLN5T
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=9LSsgvWLqM26oNFzg
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=RmbZsYx8h3kBYi7xj
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=SRyHf4DGkbHaawctf
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=Je258mrGkhoKEANGE
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13
wekanapp   | Presence started serverId=hT8E6dpfs2Dm84pRZ
wekanapp   | > Starting change-attachment-library migration.
wekanapp   | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekanapp   |       throw error;
wekanapp   |       ^
wekanapp   |
wekanapp   | TypeError: Cannot read property 'attachments' of undefined
wekanapp   |     at server/migrations.js:1054:69
wekanapp   |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
wekanapp   |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
wekanapp   |     at Object.migrationCallback (server/migrations.js:1052:24)
wekanapp   |     at packages/idmontie_migrations.js:238:17
wekanapp   |     at Function.time (/build/programs/server/profile.js:273:30)
wekanapp   |     at /build/programs/server/boot.js:415:15
wekanapp   |     at /build/programs/server/boot.js:465:7
wekanapp   |     at Function.run (/build/programs/server/profile.js:280:14)
wekanapp   |     at /build/programs/server/boot.js:463:13

**Comment by marc1006** [comment]
@urakagi Is this already fixed with the newest code?

**Comment by urakagi** [comment]
@marc1006 Yes.
For more detail, I found in this case the corrupted attachment files are also not able to download in the elder version wekan.
I am not sure if this modification causes such attachments to be lost though, but as I can check it's more like purging corrupted attachment records.

**Comment by urakagi** [comment]
FYI
https://github.com/wekan/wekan/blob/23dcd084a49de4e6568527d8f97ed25adb04dafd/server/migrations.js#L1054
When the file record does not have `copies` property this bug will happen. The new code will first use `CollectionFS.createReadStream()`, then read chunks directly from the MongoDB. A file record without `copies` property don't have information about the chunks, so if `createReadStream()` does not work it's not readable even for the current system IMO.

**Comment by GuidoDr** [comment]
just installed v4.07, the error is solved. 
Thanks everyone for solving the problem.
