### ISSUE TITLE
Docker docs are gone due to deleted wekan-mongodb repo

### ISSUE THREAD

**Issue by NicoP-S** [wekan/wekan#3124]
Hi,
it seems that the wekan-mongodb repo no longer exists.
The wiki references [Backup and Upgrade](https://github.com/wekan/wekan-mongodb#backup-before-upgrading)
https://github.com/wekan/wekan/wiki/Docker#backup-and-upgrade 

I did not find these docs in the wekan repo.

**Comment by xet7** [comment]
Oops. I added commands to wiki:
https://github.com/wekan/wekan/wiki/Docker#backup-and-upgrade
