### ISSUE TITLE
Can't open wekan with edge (using EdgeHTML engine) - spread operator not supported

### ISSUE THREAD

**Issue by neurolabs** [wekan/wekan#3125]
## Can't open wekan with edge (using EdgeHTML engine) - spread operator not supported

**Server Setup Information**:

* Did you test in newest Wekan?:

* Wekan version:
v4.06 docker image, that is the latest stable version.
* Deployment Method docker-compose
* Http frontend nginx
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
Microsoft Edge **44.18362.449.0**
Microsoft EdgeHTML 18.18363

**Problem description**:
Wekan does not work with Edge (EdgeHTML), loading the page leads to just a grey background and a JavaScript error in the console:

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
909c3cf3b8d665e287f7c90e55d5b7b1dee9df79.js (19,134059)

The code causing this is:

super({writableObjectMode:!0,...e})

Specifically, the use of the spread operator (...) on objects is not supported by Edge using the EdgeHTML engine.

- *Explain steps how to reproduce*
Open any wekan URL

**Comment by xet7** [comment]
@neurolabs 

From what I read from wikipedia, MS changed from EdgeHTML to Blink in Edge at 2019.

Anyway, are you willing to try to figure out how to fix it?

**Comment by neurolabs** [comment]
MS released the chromium/blink version in january 2020, it's quite new. But they are not rolling it out without user interaction. Especially in corporate environments, it might take months/years before we can rely on the blink engine.
In 2019, wekan used to work with Edge, so this is a regression.
TBH, I currently don't have the time to dive into an analysis.

**Comment by xet7** [comment]
Wekan used to have legacy browser support package, but it caused Wekan not working on iOS Safari, Mobile Firefox, Vivaldi, Chromium etc #2643 , so I did remove that legacy package:
https://github.com/wekan/wekan/blob/master/snapcraft.yaml#L219-L220

Well, I'll do some testing could I somehow include legacy package back without breaking support for other browsers.

**Comment by neurolabs** [comment]
@xet7 a very kind thank you for putting effort into this.

**Comment by xet7** [comment]
@neurolabs 

In what Wekan version EdgeHTML did work?

**Comment by stefanvangastel** [comment]
I have same issue with wekan:latest, downgraded to v3.97 and everything worked.

**Comment by xet7** [comment]
@neurolabs 

You should make [Backup](https://github.com/wekan/wekan/wiki/Backup) first.

Old versions of Wekan can only used offline, not directly connected to Internet, because they are vulnerable. Also, there are many bugfixes in newer versions, so it's very likely that you can hit a bug that causes board not open or something other error, so you need to take backups minimum once a day, preferably more often. I highly recommend using newest Wekan version.

**Comment by neurolabs** [comment]
Last working version is v4.01, v4.02 does show the error.

**Comment by xet7** [comment]
@marc1006 

About your comment at https://github.com/wekan/wekan/issues/2310#issuecomment-636295030

I did originally delete `web.browser.legacy`, because that way Wekan started to work on Android Firefox/Vivaldi/Opera, and also Chromium based browsers.

I did try to add legacy back, and and also try to revert back to old Meteor versions like 1.6.x, but those changed did not make Wekan working in EdgeHTML.

**Comment by xet7** [comment]
Also, removing legacy did make Wekan working on iOS Safari.

**Comment by jinthakur** [comment]
It is  not spread  operator issue  Because the  browser supports ES5 . It is Spread property feature that is part of ES9.
general spread syntax is supported.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by xet7** [comment]
I found the fix. It seems EdgeHTML does not like CSV export code. When I remove CSV export code like this, Wekan works in EdgeHTML:
```
git clone https://github.com/wekan/wekan
cd wekan
npm remove csv-stringify
```
Then change `wekan/models/exporter.js` to only have this content:
```
// exporter maybe is broken since Gridfs introduced, add fs and path
export class Exporter {
  canExport(user) {
    return false;
  }
}
```
Then build Wekan with option 2, and start Wekan:
```
./rebuild-wekan.sh
```
Then use same script to run meteor or development, or `start-wekan.sh` for production.

I will sleep and after that make new Wekan release that works with EdgeHTML.

That CSV code does not work with exporting big boards, so I will later create CSV export code without that csv-stringify package.

**Comment by jinthakur** [comment]
Great job
Can you create a bundle for windows ?



Jitender Thakur

**Comment by xet7** [comment]
@jinthakur 

At Wekan website https://wekan.github.io is Download button `Windows`, that goes to wiki page that at top a) has info, direct link:
https://github.com/wekan/wekan/wiki/Windows

**Comment by jinthakur** [comment]
Thanks for your email
You made my day. It works great. Add me to contributor list . I can test
issues.

**Comment by xet7** [comment]
@jinthakur 

Thanks! I updated contributor list https://github.com/wekan/wekan/wiki/Team

**Comment by jinthakur** [comment]
Thanks
