### ISSUE TITLE
Login forbidden for a single usser

### ISSUE THREAD

**Issue by fgrosbellet** [wekan/wekan#3126]
**Server Setup Information**:

* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: ubuntu 18.04.2 LTS
* Deployment Method: Docker compose (or so I believe : I have a docker container for the app and on e for the db)
* Http frontend if any: Apache
* MongoDB Version: v3.2.21
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome 83.0.4103.61

**Problem description**:
- I can't login anymore on my Wekan account : I receive a "Login forbidden" error. Other accounts can still login, only this one seems to be affected. I log trough email and not LDAP. Where can I start troubleshooting?

**Comment by xet7** [comment]
@fgrosbellet 

Does some user have access to Admin Panel to change your password?

**Comment by fgrosbellet** [comment]
Unfortunately, this account was the only active admin account.

If this can help : active users can't reset their password via "Forgot your password?" : this raises an internal server error.

**Comment by xet7** [comment]
```
docker exec -it wekan-db bash
mongo
```
and then change some user to admin

https://github.com/wekan/wekan/wiki/Forgot-Password

**Comment by fgrosbellet** [comment]
Thank you, I was able to solve my problem from the admin panel. This two different issues, none of them was due to Wekan itself.

I have a last question : I have deprecated users who won't login anymore. Is it ok to delete them or would you recommend not to do so in order to keep the db coherent?

**Comment by xet7** [comment]
You should set users as not active, and change their password. Not delete them.

**Comment by fgrosbellet** [comment]
Noted, thanks for your answer.
