### ISSUE TITLE
How To Use Board Templates?

### ISSUE THREAD

**Issue by compumatter** [wekan/wekan#3127]
## Issue
**Server Setup Information**:
Linux / Ubuntu 18.04

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 4.08
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu Server 18.04
* Deployment Method: bundle/source
* Http frontend: Nginx
* Node Version:  v12.16.2
* MongoDB Version: v4.0.1
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**Problem description**:
Cannot use Board Template feature
I have created a video to make obvious what I am running into: 

- https://www.youtube.com/watch?v=xoT2ZQ3rxNo

![wekan-versions](https://user-images.githubusercontent.com/121611/82950502-42835e00-9f5a-11ea-9c67-90a69f17ae27.jpg)

**Comment by xet7** [comment]
@compumatter 

There is per-user templates, but there is still some templates features missing:
https://github.com/wekan/wekan/wiki/Templates

**Comment by compumatter** [comment]
Thanks for the reply.

I have reviewed this page: https://github.com/wekan/wekan/wiki/Templates

Yes, even using as per-user and not admin, the result is the same as 
shown in the video.

Really see no way to get it done.

The "search for Template Board" I presume is looking for the Swimlane 
Title as I see no other method for naming.  However, when typing in the 
that name I receive no responses as a drop down list.

Sincerely,

Jay
	
Jay Lepore
CompuMatter
*Office*: 360 299 2428 | *Cell*: 360 202 0434
*Email*: jay@compumatter.com <mailto:jay@compumatter.com>
/If you are satisfied with your service, please consider providing us a 
social media review at https://compumatter.com/reviews
...If you are not, please let me know so I can make it better/

**Comment by xet7** [comment]
@compumatter 

Sorry, I think wiki text page is not good enough, I should try to create video about how it works. I try to explain below.

In you video, I see you have not created any board templates.

https://github.com/wekan/wekan/wiki/Templates

c) Create Board Templates
- Create List to Board Templates Swimlane
- Create card to list.
- Clicking black folder icon on that card goes to Board template page.
- Add content to Board.

So after that, at your Templates board is this:
![board-template-1](https://user-images.githubusercontent.com/15545/82962159-14d4fe00-9fc8-11ea-8517-04c0aebbfb09.png)

In the screenshot above, Board Templates swimlane has Board Template card. When you click black small icon of "folder", it goes to that Board Template board.

Then:

c) Insert Board Templates

- Go to All Boards.
- Click Add Board. (Do not write name of new board here, like in your video).
- Click Template.
- Write new Title for Template Board you are planning to add.
- Search for Template Board Name or see if Template Board Name is visible.
- Click that Template Board Name.
- Now Template Board is inserted with your new title.

**Comment by xet7** [comment]
I tried to add more clear text to Templates wiki page.

**Comment by compumatter** [comment]
Thank you for your efforts.  It gave me a few clues.  In truth, some things are still not intuitive / clear.  I did figure it out.  Templates are sooooo important that I created a video to show others what I ran into and how they are created.  It also shows a few areas where things did not work intuitively so may be improved upon. Perhaps with a little tooltip help when hovering.  

Please see this video and share if you would like: https://www.youtube.com/watch?v=K0_cP85Bvas

**Comment by xet7** [comment]
@compumatter 

Wow thanks a lot for creating that video.

**Comment by xet7** [comment]
I did add video to wiki page https://github.com/wekan/wekan/wiki/Templates

**Comment by xet7** [comment]
@compumatter 

Those avatar icons on board template card are the following, although at per user templates they are not used for these purposes at all:

1) Underlined one is that you assignee, who is assigned to card, like in Jira, as the main responsible one for implementing that card. There can be only one assignee per card.

2) Non-underlined one means you are member of the card. There can be many members of same one card.

**Comment by crewnew-git** [comment]
> * Clicking black folder icon on that card goes to Board template page.

The thing is that there's no black folder icon for me: https://i.imgur.com/IQxALaj.png

PS. If I manage to create a template with all the lists, rules, labels, WIP limits, card settings etc. then can I create a board with that template via API, too?

**Comment by iotaiota** [comment]
> The thing is that there's no black folder icon for me

Same issue. No black folder icon appears for me in the board templates cards.
