### ISSUE TITLE
Board Email Notifications

### ISSUE THREAD

**Issue by nickian** [wekan/wekan#3129]
Is there documentation somewhere that explains what email notifications are sent based on what actions, etc?

I have SMTP set up correct and test mails come through fine. However, I don't see any email notifications come through when I set a board to "watching" and make changes, or when a due date is passed, etc. Is this normal? Would I only see email notifications from other users maybe? I don't see this functionality documented anywhere.

Thanks!

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L256-L290

Similar exist for Snap:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

Also see right side menu Webhooks at
https://github.com/wekan/wekan/wiki

And [Notification drawer like Trello](https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+notification+drawer)

**Comment by nickian** [comment]
Great, thanks!
