### ISSUE TITLE
Anonymous Comment/Edit and Moderation (Extension?)

### ISSUE THREAD

**Issue by antonizoon** [wekan/wekan#313]
Is there a way to make it possible for anonymous users to comment or edit?

I would like to promote collaborative contribution using Kanban boards like a dropbox (for new leads, suggestions, etc.). Since the Kanban cards are similar to an anonymous textboard, I think it would be just the ticket to organize project development by anonymous communities (4chan, 2channel, 8ch).

Obviously, before it gets covered in spam, I would need to implement some kind of captcha and moderation tools, so I can lock cards or lists. Such a moderation suite would also work for account-based systems. 

On that topic, is there an extension framework to add extra features as necessary? I would love to build that voting feature just like Trello, and an extension feature allows people to plug it in or take unneeded features out.

**Comment by mquandalle** [comment]
I’ve been thinking a lot about building a framework for extensions/plugins developed by the community, this is definitely something I would love to do — but there are some non-trivial design decisions involved that I haven't made yet. About the “voting on card” feature I received PR #310 that seems to implement it, but I can’t merge it for now for the reason indicated in the PR.

**Comment by xet7** [comment]
There is related feature of comment-only permissions on boards, but that is only for logged in users.

Vote on cards is separate issue at #796

**Comment by xet7** [comment]
Moved to #1124
