### ISSUE TITLE
Swimlanes Title Bar Width

### ISSUE THREAD

**Issue by nickian** [wekan/wekan#3130]
I'm not sure if this is a bug or there's a reason for it, but I noticed the swimlane title bar does not extend to the width of all of your columns if you have columns beyond 100% of the browser window. This seems to happen in all themes.

Initially it looks correct:

<img width="1521" alt="screenshot1" src="https://user-images.githubusercontent.com/590678/82976120-821e6a00-9f9b-11ea-9daf-62a0d4ffbaee.png">

Then when you scroll horizontally, it breaks off:

<img width="1518" alt="screenshot2" src="https://user-images.githubusercontent.com/590678/82976140-8c406880-9f9b-11ea-91f2-9692ed7664ac.png">

**Comment by hgustafsson** [comment]
It is particularly noticeable in the modern theme where the bright background of the lists is of the same width as the swimlane title bar (i.e too short).

**Comment by xet7** [comment]
This is already fixed at PR https://github.com/wekan/wekan/pull/3370 at [Wekan v4.56](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v456-2020-11-30-wekan-release)
