### ISSUE TITLE
Wekan Browser Compatibility

### ISSUE THREAD

**Issue by zulipon** [wekan/wekan#3132]
I have searched this issue on google and github and the manual, but cant find a reference to it.
I am looking for WEKAN-BROWSER compatibility matrix.

We need to access Wekan using older browsers because the organization I'm working at is still using windows XP.

The Wekan we installed is a recent one (installed a few days ago (in May 2020) on Ubuntu 18.04 using the command:
sudo snap install wekan

It works fine when accessing it on Chrome  81.0.4044.138 (Official Build) (64-bit)
However on older browsers (the last version of firefox, chrome, opera for windows xp) it would get stuck on the login page. (It will just display a grey background without the login box).

I understand that windows XP is obsolete and newer browsers are no longer compatible with this OS. However, upgrading the OS is not an option.
Therefore, the only feasible solution (that I can think of) is to use an older version of Wekan.
This is an intranet in a zone that is not connected to the internet. So security is not an issue.

The question is: 
Where can I find the info on which version of Wekan is compatible with older browsers ? 

Thank you in advance.

**Comment by xet7** [comment]
I added something like that, someone can comment or add issue if knows more info:
https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix

**Comment by zulipon** [comment]
Thank you XET7

**Comment by xet7** [comment]
@zulipon 

You can use [MyPal browser on WinXP](https://feodor2.github.io/Mypal/), it is Firefox based, Open Source, up-to-date, and works with Wekan. I updated matrix.

**Comment by xet7** [comment]
Just a note, I updated above comment with newest links to 32bit Mypal.
