### ISSUE TITLE
Due Date Email Notifications

### ISSUE THREAD

**Issue by Keelan** [wekan/wekan#3133]
## Issue

When the due date is close an email is sent out. I would assume it would only be sent to members of the card. But it goes to everyone who is on the board regardless if they are a member of the card or not.

**Server Setup Information**:

* Did you test in newest Wekan?: **Yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? **Yes**
* Wekan version: **4.09.0**
* If this is about old version of Wekan, what upgrade problem you have?: **No but happens in old versions too**
* Operating System: ubuntu 1**6.04**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **source**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: **12.16.1**
* MongoDB Version: **4.2.6**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Chrome**

**Problem description**:

An email to me:
![image](https://user-images.githubusercontent.com/1158997/83063602-66b06f00-a02e-11ea-8e7c-c6bd3b49544c.png)

Im not a member of the card:
![image](https://user-images.githubusercontent.com/1158997/83063631-716b0400-a02e-11ea-84b5-1fbeedb515f8.png)

- *Explain steps how to reproduce* **Create a card with a due date and get a 1st reminder notification**
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.* **N/A**

**Comment by Keelan** [comment]
Its getting bad lol

![image](https://user-images.githubusercontent.com/1158997/83535130-a3151c80-a4bf-11ea-8005-8a3efdd34847.png)

Note, im not a member of any of those cards.
Im simply a board member (not even an admin a regular normal user)

**Comment by Keelan** [comment]
https://github.com/wekan/wekan/blob/d52affe65893f17bab59bb43aa9f5afbb54993d3/models/activities.js#L257

`const BIGEVENTS = process.env.BIGEVENTS_PATTERN || 'due';`

Looks like this is my issue `due` is set as a default `BIGEVENTS` which is broadcast to all members of the board who are watching.
Wouldn't this make more sense to only broadcast to admins of the board? 40+ people get notified ever time a card due date activity is triggered. I'm a member of lots of boards and just get emails constantly

**Comment by Keelan** [comment]
Looks like setting `BIGEVENTS_PATTERN` to anything it will ignore the system default

i.e. `BIGEVENTS_PATTERN = 'IGNORE'`

**Comment by marc1006** [comment]
Attempts have already been made to fix the behavior: https://github.com/wekan/wekan/commit/0083215ea3955a950d345d44a8663e5b05e8f00f. 

The question is if we shouldn't change the line https://github.com/wekan/wekan/blob/d52affe65893f17bab59bb43aa9f5afbb54993d3/models/activities.js#L257 as well. But this would change the default behaviour... so I don't know whether this is acceptable or not.

@xet7 Any opinions?

**Comment by xet7** [comment]
@marc1006 

Someone added that BIGEVENTS feature in a way that it overrides settings:
https://github.com/wekan/wekan/pull/2541

It there is some better way it could work, you (or anyone else) can add pull request.

In general, there is many features at Wekan added by about 180 contributors. I have not used some of them and don't even know do all those features work. Anyone can send fixes for anything.
