### ISSUE TITLE
Feature Request: Import Custom Fields from Wekan JSON Export

### ISSUE THREAD

**Issue by fgomezotero** [wekan/wekan#3137]
* Did you test in newest Wekan?: Yes
* Wekan version: 4.09
* Operating System: Official image from quay.io
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Deployed in Openshift Container Platform
* Node Version: 12.16.3
* MongoDB Version: 3.2
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Latest Chrome version

**Problem description**:
- When I import a board in previously exported json format that includes custom field it doesn't create them on the imported board.
-Note: The exported json does include custom fields, for me it is a problem when importing.

**Comment by jrsupplee** [comment]
@fgomezotero 

In my tests, custom field imports are working.  Is this still a problem for you?
