### ISSUE TITLE
Retrieve card information via Rest API limited to title and description?

### ISSUE THREAD

**Issue by GitGramm** [wekan/wekan#3145]
I am trying to retrieve a cards information via Rest API:
I am reading http://mywekanserver/api/boards/4jSEGaEcD5d2ougu4/lists/pfmKK8KQSG9amJDqr/cards Method used: GET
As also described in the documentation at https://github.com/wekan/wekan/wiki/REST-API-Cards the result only provides title and description. But for me it would be useful to get more info.
Is there a way to retrieve other fields like due dates or assignee via Rest API?
Thanks!

**Comment by xet7** [comment]
@GitGramm 

You can search at [API docs](https://wekan.github.io/api) and [code](https://github.com/wekan/wekan/tree/master/models). If something is missing, you can add new API calls with pull request, similarly like other code there already exists. API docs are generated automatically with OpenAPI script that I run before releasing a new version of Wekan.

**Comment by GitGramm** [comment]
Thanks for the info! I have created a pull request: https://github.com/wekan/wekan/pull/3146

**Comment by xet7** [comment]
@GitGramm 

Before `startAt`, you should also add `receivedAt`.

**Comment by GitGramm** [comment]
Done:-)

**Comment by xet7** [comment]
Merged https://github.com/wekan/wekan/pull/3146
