### ISSUE TITLE
Member can't move boards in own workspace

### ISSUE THREAD

**Issue by rptl** [wekan/wekan#3147]
Only Admins can move boards around in "My Boards" view. 

A member should be able to  move boards around in order to organize  his/her own workspace.

Steps to reproduce:

Create some boards as member X, add member Y. Logon as member Y and try to move boards around.

Tested on versions 4.01 and 4.10

Browser console displays: "update failed: Access denied"

**Comment by hever** [comment]
Yes, it's very unpleasant. I (and my coleagues also) have about 30 board and there is absolutely mess. It's assorted in every ways and there is nothing to do with this for every of us. If only there was a possibility to sort it alphabeticaly but it's isn't there.

**Comment by xet7** [comment]
I added this to [my Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/9Zg6b5oDsEk57P5TG)
