### ISSUE TITLE
Feature Request: Autologin (was: OpenID SSO)

### ISSUE THREAD

**Issue by Buliwif** [wekan/wekan#3153]
Hi,
I provide Wekan throuh a couple reverseproxy+LemonLdap.
I just configure OpenID connect both on wekan and LemonLDAP and everything works fine.

The only point is that it's not a true SSO, I have to connect to my LemonLDAP portal and when I chose Wekan, I have to click on "connect with OIDC". Is it possible to auto-connect ?

**Comment by mjler** [comment]
When gets this feature implemented?

**Comment by xet7** [comment]
@mjler 

It depends when someone has time to figure out autologin at layouts.jade and layouts.js at:
https://github.com/wekan/wekan/tree/master/client/components/main

Or when somebody pays me 300 euro to code it at https://wekan.team/commercial-support/
