### ISSUE TITLE
Wekan not sending webhook data to server in a local docker enviroment

### ISSUE THREAD

**Issue by euller88** [wekan/wekan#3155]
Hello, in my company we are transitioning from Trello and Wekan because we wanted a kanban solution in which we could host in our local network.

After discovering the REST API and webhooks we decided to integrate some of our applications with it, and I was tasked to study on how to do it.

As a base application for the experiment to receive the webhook data and to send notifications to a web client, I've copied an application I've found on  this [scotch.io article](https://scotch.io/bar-talk/build-a-realtime-chat-server-with-go-and-websockets), whose code is in this [repo](https://github.com/scotch-io/go-realtime-chat).

The only change that I've made in the application was to add a new handler that would receive the the webhook data and then broadcast to the connected clients, demonstrated in this code:
```go
...

func webhookHandler(w http.ResponseWriter, r *http.Request) {
	// just a log to register if this handler is called
	log.Println(r.Host)

	var i interface{}

	err := json.NewDecoder(r.Body).Decode(&i)
	if err != nil {
		// something went wrong while decoding the JSON 
		log.Println(err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// no need to check for errors here
	m, _ := json.Marshal(i)

	var msg = Message{
		Message: string(m),
	}

	broadcast <- msg

	w.WriteHeader(http.StatusOK)

	_, _ = w.Write([]byte(`{"ok":true}`))
}

...

func main() {
	fs := http.FileServer(http.Dir("../public"))
	http.Handle("/", fs)

	// Configure websocket route
	http.HandleFunc("/ws", handleConnections)

	http.HandleFunc("/webhook", webhookHandler)

	...
}
```

Next, I ran Wekan, Mongo, Traefik and this app in Docker, using the configuration found in this [compose file that I made](https://gist.github.com/euller88/917d55bf053cd5daf4df3f3b31b258ed) and this [Traefik configuration file](https://gist.github.com/euller88/57d8af40171626ae6ebac17f98cb06f2).

Finally, I configured Wekan to send data to two webhooks: one in [HTTPdump](httpdump.io), and the other to the Go app in webhook.docker.localhost/webhook in my local machine.

Now is where my problem happens, the fake HTTPdump endpoint does receive data from wekan whenever I do some action, but the Go app doesn't even register that it received a request, and if I try to use cURL, Postman, or any other REST client, to send JSON data to this url, not only it receives the request, but it properly sends it to the web interface through websockets.

But the worst of all is that no error messages appear in Wekan logs when it try to send webhook data to the Go app, so is not that I can give a greater insight into the problem.

**Comment by euller88** [comment]
Update on the issue: it seems that the problem lies within my local enviroment. I just tested in one of our servers and it works perfectly fine. Although I'm closing the issue, I'll keep investigating what happened, to prevent other people committing the same mistake.

**Comment by n8ores** [comment]
Try using the URL host.docker.internal if you are using it internal to docker
