### ISSUE TITLE
GitLab as oidc Identity provider for wekan

### ISSUE THREAD

**Issue by derhelge** [wekan/wekan#3156]
It's not really a bug but i don't know where to write it down... I finally figured out how to login by OpenID in wekan with GitLab as identity provider.

Those are the settings (snap installation):
```shell
sudo snap set wekan oauth2-enabled='true'
sudo snap set wekan oauth2-client-id='xxx'
sudo snap set wekan oauth2-secret='xxx'
sudo snap set wekan oauth2-server-url='https://gitlab.example.com/'
sudo snap set wekan oauth2-auth-endpoint='oauth/authorize'
sudo snap set wekan oauth2-userinfo-endpoint='oauth/userinfo'
sudo snap set wekan oauth2-token-endpoint='oauth/token'
sudo snap set wekan oauth2-id-map='sub'
sudo snap set wekan oauth2-username-map='nickname'
sudo snap set wekan oauth2-fullname-map='name'
sudo snap set wekan oauth2-email-map='email'
sudo snap set wekan oauth2-request-permissions='openid profile email'
```
And in GitLab you have to set the same scopes inside the created Application:
* openid
* profile
* email

The redirect URL is described in the wekan wiki: https://wekan.example.com/_oauth/oidc

Maybe i can save someone some time :-) Thank you for developing wekan. Its a great tool! :1st_place_medal:

**Comment by derhelge** [comment]
Its already working...

**Comment by xet7** [comment]
@derhelge 

Thanks a lot, I added it to wiki:
https://github.com/wekan/wekan/wiki/OAuth2
