### ISSUE TITLE
Error found in Wiki

### ISSUE THREAD

**Issue by Tanarri** [wekan/wekan#3157]
## Issue
In the Wiki https://github.com/wekan/wekan/wiki/Docker there is this paragraph, on which hekp is welcome
-----------------------------------------------------------------------------------------------_
Note: Currently these Docker command examples do not work, help welcome

Example for latest Wekan, port 2000 to Docker Wekan internal port 8080:
```
docker run -d --restart=always --name wekan-db mongo:4
docker run -d --restart=always --name wekan --link "wekan-db:db" -e "WITH_API=true" -e "MONGO_URL=mongodb://wekandb:27017/wekan" -e "ROOT_URL=http://192.168.1.200:2000" -p 2000:8080 quay.io/wekan/wekan
```
-----------------------------------------------------------------------------------------------_

I tested on kubuntu 20.04 with docker (bionic) the commads and following is working for me:
`docker run -d --restart=always --name wekan --link "wekan-db:db" -e "WITH_API=true" -e "MONGO_URL=mongodb://wekan-db:27017/wekan" -e "ROOT_URL=http://192.168.1.200:2000" -p 2000:8080 quay.io/wekan/wekan`

`"MONGO_URL=mongodb://wekandb:27017/wekan" --> "MONGO_URL=mongodb://wekan-db:27017/wekan"`
there was a "-" missing in "wekandb"

**Comment by xet7** [comment]
@Tanarri 

Thanks a lot ! I added that fix to wiki.
