### ISSUE TITLE
"Hide empty lists" doesn't work if the swimlane option is active

### ISSUE THREAD

**Issue by CarloRampini** [wekan/wekan#3159]
If you choose "Hide empty lists" it works only if the "Board view" is selected to "Lists".

If you choose in "Board view" the option "Swimlane" the empty lists will appear again and this seems to be not correct, if the list is empty this should be true in both options: Lists or Swimlane.

If this architectural choice is "intentional" then the option "Hide empty lists" should be unavailable when the "Board view" is in swimlane mode.

**Comment by xet7** [comment]
@urakagi 

It seems you added this ["Hide empty lists" feature at Wekan v3.21](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v321-2019-08-16-wekan-release).

Can you submit pull request to master branch for:
a) Hiding empty lists in Swimlane view, if possible (would be better)
b) Or hiding option to hide in Swimlane view

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4108
