### ISSUE TITLE
I can't run wekan on windows server

### ISSUE THREAD

**Issue by amannmaa2014** [wekan/wekan#3160]
hello guys I have windows 10 server,
I followed the instructions as written here https://github.com/wekan/wekan/wiki/Windows  , but couldn't run properly and I'n new to node+mongoDB,

when I run the file start-wekan.bat it shows this message:
{"line":"87","file":"packages\\percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Tue Jun 09 2020 09:24:57 GMT+0300,"time":{"$date":1591683897500},"level":"info"} 

I'm not sure what does it means,
+ do I need to add the application to wwwroot + IIS?

really appreciate your help.

**Comment by xet7** [comment]
@amannmaa2014 

That is normal message, that cron periodically removed already read messages from Wekan feature `Notification drawer like Trello`.

For setting ROOT_URL:
https://github.com/wekan/wekan/blob/master/start-wekan.bat#L16
See https://github.com/wekan/wekan/wiki/Settings

For example, at local network without IIS, with only Wekan running,  use server IP address:
```
ROOT_URL=http://192.168.0.100
PORT=80
```
So Wekan starts at port 80 and is visible at http://192.168.0.100

For some webserver like IIS at front of it, providing SSL, have subdomain pointing to that server IP address, and add IIS proxy (with websockets enabled) from https://boards.example.com to http://127.0.0.1:2000, for example:
```
ROOT_URL=https://boards.example.com
PORT=2000
```
Wekan GitHub wiki menu at right has also links to examples for other webservers like Caddy, Nginx and Apache.
