### ISSUE TITLE
Home Page can't be seen in Edge, no problem with Chrome at Win10.

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#3161]
Issue description:
Home Page can't be seen in Edge, no problem with Chrome at Win10.

![error](https://user-images.githubusercontent.com/46272743/84115356-8731ed80-aa60-11ea-9f55-03d13a1c7d5d.png)

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix

Moved to #3125
