### ISSUE TITLE
On Mac: clicking on card do nothing

### ISSUE THREAD

**Issue by hever** [wekan/wekan#3162]
version with symptoms: 4.12
version without symptoms: 4.11-2-g232bc74

This is maybe weird issue. My colleague using Mac and he cannot open card. He tried in Safari and in Chrome and it do the same - nothing after click on card (I see it in screen sharing). We were try reloading, another board, restarting server etc. but nothing helped. After `snap revert wekan` everything works fine.

In my linux everything works, we have same version of Chrome (newest) only difference I see on operating system (maybe I don't see something, don't know).

I'm not able to do research on his machine so I can't send anything debug info.

Maybe it has nothing to do with Mac, maybe depends on some user setting (I don't know).

**Comment by xet7** [comment]
Fixed in upcoming Wekan v4.13
