### ISSUE TITLE
card settings doesn't show up after 4.12

### ISSUE THREAD

**Issue by flexo3001** [wekan/wekan#3163]
## Issue
After the update to 4.12 i can only open card settings while in swimlane view. In the lists view the card will be selected but no dialog shows up. Is this intended behaviour? 

![Screenshot from 2020-06-09 14-10-38](https://user-images.githubusercontent.com/1415596/84146442-02dd6b80-aa5c-11ea-82a4-a00af64de35a.png)
![Screenshot from 2020-06-09 14-10-53](https://user-images.githubusercontent.com/1415596/84146444-04a72f00-aa5c-11ea-80b5-1ea3ac20a4b0.png)

**Comment by xet7** [comment]
Fixed in upcoming Wekan v4.13
