### ISSUE TITLE
No card detail in list view

### ISSUE THREAD

**Issue by StefanNeubert** [wekan/wekan#3164]
**Server Setup Information**:
* Wekan version: 4.12
* Docker :latest
* Http frontend: trafik
* MongoDB Version: 3.2.21
* Latest Chrome

**Problem description**:
- Updated to latest Wekan 4.12 no card details are shown in list view

![wekan_bug_412](https://user-images.githubusercontent.com/66677532/84148892-eba07d00-aa5f-11ea-908f-bf97db90c9b4.gif)

**Comment by StefanNeubert** [comment]
seem #3162 an #3163 are the same issue

**Comment by xet7** [comment]
Fixed in upcoming Wekan v4.13
