### ISSUE TITLE
API docs missing methods

### ISSUE THREAD

**Issue by NicoP-S** [wekan/wekan#3169]
I have looked at the api docs. The new docs are missing some methods which exist.

Example __edit_card__
https://github.com/wekan/wekan/blob/master/models/cards.js#L2339-L2382

https://wekan.github.io/api/v4.13/#wekan-rest-api-cards
![image](https://user-images.githubusercontent.com/8988747/84417384-d5d4b880-ac15-11ea-8b34-492b8c1af81c.png)

An older version of the docs has this method.
https://wekan.github.io/api/v2.55/#wekan-rest-api-cards
![image](https://user-images.githubusercontent.com/8988747/84417351-c6ee0600-ac15-11ea-81d9-a9eb99d78486.png)

**Comment by xet7** [comment]
Docs are created by [rebuild docs scripts](https://github.com/wekan/wekan/tree/master/releases) of [OpenAPI](https://github.com/wekan/wekan/pull/1965). Those scripts do not like new Javascript features like arrow functions (javascript code like `=>` ), they just silently don't create those parts of API docs where is to new code, as me and @marc1006 have noticed couple of times.

I don't know is @bentiss still around to help fix it. Or could someone search is there some newer code somewhere.

I did also [fork that code that generates docs](https://github.com/wekan/esprima-python) if that could be fixed some way.

**Comment by bentiss** [comment]
The problem was not in esprima for this one, but in my script itself. It couldn't associate the jsdoc with the operation because... there was new lines between the 2 :(

This should be fixed in #3171
