### ISSUE TITLE
Missing images after big Import from Trello

### ISSUE THREAD

**Issue by tbpoetke** [wekan/wekan#3175]
## Issue

**Server Setup Information**:

* Wekan version: 4.13
* Operating System: Ubuntu 16.04
* Deployment Method: Docker
* Http frontend: Nginx Reverse Proxy (Jwilder)
* Node Version: 12.18.0
* MongoDB Version: 4.2.7
* What webbrowser version are you using?
   Firefox
**Problem description**:
- Missing images after importing a board from Trello
- I import the Trello board with Json export / Import. After a while the board appears in Wekan, but some, not all Images are missing

** Docker-compose file**:
```hcl
version: '2'


services:

  wekandb:
    image: mongo:latest
    container_name: wekan-db
    restart: always
    command: mongod --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: wekanteam/wekan
    container_name: wekan-app
    restart: always
    expose:
      - "8080"
    networks:
      - wekan-tier
      - default
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - VIRTUAL_HOST=boards.*****
      - LETSENCRYPT_HOST=boards.******
      - LETSENCRYPT_EMAIL=admin@****
      - VIRTUAL_PORT=8080
      - ROOT_URL=https://boards.****  #   <=== using only at same laptop/desktop where Wekan is installed
      - MAIL_URL='smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}'
      - MAIL_FROM='Wekan Notifications <noreply.wekan@mydomain.com>'
      - WITH_API=true
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=****
      - OAUTH2_SECRET=****
      - OAUTH2_SERVER_URL=https://files.****
      - OAUTH2_AUTH_ENDPOINT=/index.php/apps/oauth2/authorize
      - OAUTH2_USERINFO_ENDPOINT=/ocs/v2.php/cloud/user?format=json
      - OAUTH2_TOKEN_ENDPOINT=/index.php/apps/oauth2/api/v1/token
      - OAUTH2_ID_MAP=id
      - OAUTH2_USERNAME_MAP=id
      - OAUTH2_FULLNAME_MAP=display-name
      - OAUTH2_EMAIL_MAP=email
      - BROWSER_POLICY_ENABLED=true

    depends_on:
      - wekandb

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  default:
    external:
      name: webproxy
  wekan-tier:
    driver: bridge
```
** Nginx VHost Config for Jwilder**:
```hcl

        ##
        # Basic Settings
        ##

        ## Max attachment size that can be uploaded to Wekan:
        client_max_body_size 1000M;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        types_hash_max_size 2048;
        server_tokens off;
        set_real_ip_from 0.0.0.0/32; # All addresses get a real IP.
        real_ip_header X-Forwarded-For;
        client_body_timeout 60;
        client_header_timeout 60;
        keepalive_timeout 10 10;
        send_timeout 60;
        reset_timedout_connection on;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##


        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";
        gzip_buffers 16 8k;
        gzip_comp_level 1;
        gzip_http_version 1.1;
        gzip_min_length 10;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/x-icon application/vnd.ms-fontobject font/opentype application/x-font-ttf;
        gzip_vary on;
        gzip_proxied any; # Compression for all requests.
```

**Comment by xet7** [comment]
I presume images do not import, because you have timeouts at Nginx config.

I use Caddy webserver for SSL, it works for me.

**Comment by Aschenbecher** [comment]
> I presume images do not import, because you have timeouts at Nginx config.
> 
> I use Caddy webserver for SSL, it works for me.

Do you have an idea what I can change in my NGINX config? I copied the nginx config from Wekan Wiki, so it should work normally ...

**Comment by xet7** [comment]
In theory that Nginx config should work, but I'm not so good with Nginx config.

You could try installing Wekan Snap with Caddy and try are all images etc imported from Trello. If it works, you can [Backup](https://github.com/wekan/wekan/wiki/Backup) Wekan MongoDB from Docker and restore to Snap, and then import those boards from Trello.

**Comment by Aschenbecher** [comment]
@xet7 Yeah I had the same Idea and I will give it a try

**Comment by xet7** [comment]
No reply received about did it work.

**Comment by xet7** [comment]
Anyone who uses Nginx in front of Wekan, please test does this bug exists, and add a comment to this issue.

Reopening issue.

**Comment by Aschenbecher** [comment]
sry I had to time yet to do the test with another wekan system without nginx :( Sorry alot of other tasks here. I will give feedback when its done!

**Comment by gaetan-luitot** [comment]
Hi !
I tried to import a board of mine from Trello, but it was too heavy :
POST : ![image](https://user-images.githubusercontent.com/1593579/86830392-ee5db480-c095-11ea-81c8-26e65b363896.png)
That must came from my nginx config ^^.

So I tried with a new smaller board :
![image](https://user-images.githubusercontent.com/1593579/86830627-37ae0400-c096-11ea-97cc-2e2314480285.png)

I imported it in JSON into Wekan from Trello, and it worked :
![image](https://user-images.githubusercontent.com/1593579/86830923-92476000-c096-11ea-819c-0b18f2d333f5.png)

Info that might be interesting :
- Centos 8
- Snap -> 2.45.1-1.el8
- Wekan -> 4.17
- Nginx -> 1.14.1

**Comment by xet7** [comment]
@gaetan-luitot 

In `/etc/nginx.conf`

```
http {
    ...
    client_max_body_size 1000M;
}    
```

**Comment by gaetan-luitot** [comment]
Thanks it worked :D !

But I sent this message because I didn't have any trouble with importation through nginx so maybe I could be useful for something ?

**Comment by xet7** [comment]
@gaetan-luitot 

But did you have any bigger board that did not import from Trello?

Have you tried without Nginx in front, does it work?

**Comment by xet7** [comment]
Because previously it has been possible to import huge boards from Trello when client computer and Wekan server have enough RAM. For example, when running Wekan server and browser on computer that has 28 GB RAM.

**Comment by gaetan-luitot** [comment]
I've just tried with a 1MB JSON, I don't  know if it's heavy enough, but it worked with and without Nginx in front.

**Comment by Aschenbecher** [comment]
Well, our Trello Board is really huge .... as you can see in my first post, I have the client body size settings in nginx conf already. This week I will have time to import without NGINX then I will give an update!

**Comment by xet7** [comment]
@Aschenbecher 

Thanks! If it is not possible to import it when there is enough RAM, then I will make changes to code so that importing becomes possible.

**Comment by Aschenbecher** [comment]
ok, I did some more tests:
First I skipped NGINX with portmapping to localhost and tried to reimport the Trello Board. Same Problem, some images are there, alot are missing.
Then I tried the import of the Trelloboard with another client PC, I switched from my working laptop to my private desktop with 32Gb Ram. Same Problem...
Then I created a new Server. 16 Cpu / 256Gb Ram , empty server just wekan with docker installed, ports directly mapped to internet. Import with my Desktop machine.... same problem . So for now, I know, its not the NGINX and not the memory of server/client. Maybe its docker, next try I will do without docker and do a native wekan installation

**Comment by xet7** [comment]
@Aschenbecher 

You don't need to do more tests. I will test myself and look at fixing this.

**Comment by Aschenbecher** [comment]
I will just give it another try with chromium instead of firefox

**Comment by Aschenbecher** [comment]
We really have alot of Images/attachments in our trelloboard, but it looks like Trello just save them in a S3 bucket and in the export json is just the link of the images, so wekan should just download them directly from S3

**Comment by xet7** [comment]
@Aschenbecher 

Currently Wekan does download files directly from S3 and store them to database. There is also in-progress code that could save files to filesystem, but it is not yet in Wekan because it does not work yet on arm64 an s390x. I will test why some images are not visible.

**Comment by Aschenbecher** [comment]
any news about this problem? I still have it and already tried it without NGINX :(

**Comment by xet7** [comment]
@Aschenbecher 

Thanks for reminding! I added plans to [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/RNTZ8NAm46mAeEDev) because there is upcoming funding for Trello mass import, like all boards/attachments/etc at once. Related to this, I'll look at storing files to filesystem or elsewhere, because it seems my own Wekan install (that has about 300 boards) is coming to limits of MongoDB with having a lot of attachments, and trying to restore 2.8 GB dump with mongorestore seems to timeout or take very long. I think improvements could be in Wekan release sometime this or next year.

**Comment by xet7** [comment]
Moved to #4877
