### ISSUE TITLE
changing colors makes the mobile look messy

### ISSUE THREAD

**Issue by rianseven** [wekan/wekan#3176]
hi I found a bug, where when changing the color wekan. display time to be a mess ?. is there a solution for this?

**Comment by xet7** [comment]
@rianseven 

Can you add photo or screenshot about it as attachment to comment to this issue?

**Comment by rianseven** [comment]
1. in swimlanes mode, if you add more cards, it looks truncated like the following attachment

![swimline mode](https://user-images.githubusercontent.com/45984394/84947584-a4c41e80-b114-11ea-9ad9-2a5266013913.jpg)

2. On the mobile web, for the "clearblue" background board option, the card on the board is still not as neat as other colors
![mobile](https://user-images.githubusercontent.com/45984394/84947893-35026380-b115-11ea-8556-741bb91c2721.jpg)

**Comment by xet7** [comment]
@rianseven 

1. This is another existing issue #3130 

2. What do you mean with "neat" ? Can you make screenshot mockup about what it should look like?

**Comment by rianseven** [comment]
![06225766-756E-44BE-8DDE-35D2C3E023B1](https://user-images.githubusercontent.com/45984394/85138085-66417780-b26c-11ea-8720-00ea9dd4845e.jpeg)


The red line indicates that in the mobile version, it looks like the card is not center ?. is there a solution sir
