### ISSUE TITLE
Getting away from BountySource

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3177]
## About getting away from BountySource

Hi everyone,
BountySource has [changed their ToS](https://news.ycombinator.com/item?id=23548061) that after 2 years if bounty is not claimed, BountySource grabs that bounty money. The right thing would have been to give that money to project owners, but I don't know is it possible to get them to change their ToS.

For this reason, I'm trying to get away from BountySource, by requesting that all these issues allow me getting bounty of them now, because I will implement all these features. I will update this list below when each feature has been implemented.

## Status

[Status at Wekan Roadmap, for accepted claims can start implementing](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/S22RwzJc43uv9dShH)

## Future payments to Commercial Support

For any future payments, please do not use BountySource. Instead, use [my Commercial Support](https://wekan.team/commercial-support/).

**Comment by ocdtrekkie** [comment]
Looks like in my case, my bounty on BountySource I placed was already paid out. But yeah, this is an incredible ploy for them to collect money that was donated to open source projects as profit for themselves. Everyone should look at how to get the bounty paid out to an open source developer ASAP.

**Comment by jon-watts** [comment]
@xet7 - I don't see how you have any other choice but make this move.  As a bounty contributor i'm fine with this.

**Comment by jttttttttt** [comment]
What a bad move from bountysource, you got my bounty for top level projects @xet7

**Comment by HLFH** [comment]
Terms of Service have been withdrawn. https://twitter.com/Bountysource/status/1273406549252177920

But still, wekan should migrate as proposed by @xet7.

**Comment by xet7** [comment]
@HLFH 

Yes, Wekan will still migrate away from BountySource, because BountySource is very hard to use. Bounties need to be renewed from time to time, they have their own additional fees, etc.

**Comment by xet7** [comment]
I did previously close issues that had bounty during migration. Now that all claims have been accepted, I have opened those issues again. Next, when implementing each feature, I will close each issue when that issue has been implemented. Progress can be seen from status link at first comment of this issue.

Migration will most likely be finished during this week.

**Comment by Beltrando** [comment]
So you are the only contributor who can earn money ? I mean, if I want to pay someone to make a change quickly, it's just you?

**Comment by xet7** [comment]
@Beltrando 

Yes. I am fulltime maintainer of Wekan. I reply to issues, check and merge pull requests and translations, code features and fixes, create releases for all Wekan platforms, and I have created most of the documentation.

Some history:
- Original creator of Wekan tried to [rewrite Wekan](https://github.com/wekan/wekan/wiki/faq#what-was-wekan-fork--wefork), after that I continued maintaining Wekan
- First year I did as a hobby for free. Then someone asked about bounties etc so I added bounties and my Commercial Support. Bounties are not used anymore, only Commercial Support.
- For every other contributor that has received bounty or payment, after they have coded minimal feature and got the money, they have disappeared and they did not stay around to fix bugs etc. Maybe just life happens? I don't know. It's hard to promise money to someone else if they don't stay around sending features and fixes.

**Comment by xet7** [comment]
@Beltrando 

As you see from README at https://github.com/wekan/wekan , there are 177 contributors in Wekan Global Community.

Here is those that have contributed to Wekan during latest month:
https://github.com/wekan/wekan/pulse/monthly

And here is total stats of amount of contributed code:
https://github.com/wekan/wekan/graphs/contributors

It's possible to ask some other [recent contributor](https://github.com/wekan/wekan/blob/master/CHANGELOG.md):
- Do they have time?
- Can you pay them for some feature?
- Do they know how to develop that feature or fix? Have they done only UI / CSS changes, some small features or big features?

For some other developer that has coded something similar recently that you are asking for, that other developer could be up-to-speed in implementing it.

Some other recent contributor could possibly have even more time available than me. My "quickly" has been something between some days to 8 months. I have been maintaining Wekan for about 3.5 years, [since 2016-12-16](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v0110-2016-12-16-wekan-fork-first-release).

For some older contributors, I don't know are they still around.

Many companies have in their company some developer that sends pull requests to Wekan to add some feature or fix. Also some individuals send pull requests they have developed at their free time. I don't know about other contributors what pull request is paid or not.

It's not like I can prevent someone paying to someone else.

**Comment by Beltrando** [comment]
I Understand that. And I totally agree. 
And... is it possible to have a private conversation ?

**Comment by xet7** [comment]
@Beltrando 

Yes. Send email to support@wekan.team , that is also mentioned at https://wekan.team/commercial-support/ .

For paying customers there is also private chat available. More details can be had from that email address.

**Comment by jdaviescoates** [comment]
They are not the same thing, but may I suggest @xet7 get WeKan set-up on both [Open Collective](https://opencollective.com/) and [Liberapay](https://liberapay.com/)? :)

**Comment by xet7** [comment]
@jdaviescoates 

I unpublished GitHub Sponsors, it seems too complicated.

I am not planning to add GitHub Sponsors, Open Collective, Liberapay or any other additional option. I got hurt enough with BountySource.

**Comment by jdaviescoates** [comment]
> I am not planning to add GitHub Sponsors, Open Collective, Liberapay or any other additional option. I got hurt enough with BountySource.

That is a shame. 

I can't speak for Liberapay but I know the people at Open Collective and they are all lovely.  

They would _never_ act how Bounty Source have behaved.

And so to use a couple of English sayings: by "tarring them (Open Collective) with the same brush (as Bounty Source)" it feels a bit like you are "cutting off your nose to spite your face" :confused: 

Perhaps in time you'll reconsider.

I hope so, because I think having an Open Collective for WeKan could really help you to attract recurring donations from WeKan users and help you to build up a nice sustainable livelihood to continue doing the important work you do :+1:

**Comment by xet7** [comment]
@jdaviescoates 

From what I looked at those, both Liberapay and Open Collective add their own additional fees etc 3rd party complications.

Current payment methods at [Commercial Support](https://wekan.team/commercial-support/) do work well. Most use PDF invoice or PayPal.

I do add every paid feature to [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license).

All Wekan code is Open Source.

About that Open Collective, does that mean submitting my data to USA ? Those strange IRS forms?

How does Open Collective work?

**Comment by ocdtrekkie** [comment]
OpenCollective acts as the legal/financial entity for your project, so you don't have to do tax forms and such. People donate to your OpenCollective organization and then you can submit invoices for work done against it.

**Comment by xet7** [comment]
@jdaviescoates 

Well, I'm still a little scared and not sure how that OpenCollective works, but I added it anyway, although I don't know did I setup it correctly:

https://opencollective.com/wekan

I added that link to bottom of funding page https://wekan.team/commercial-support/

If someone really dares to use that way to fund Wekan, that someone should also help with related questions.

**Comment by xet7** [comment]
I archived that OpenCollective page. I am not interested in USA based payment systems.

**Comment by jdaviescoates** [comment]
> I archived that OpenCollective page. 

Who hadn't actually created a "collective" that could collect donation anyway.

> I am not interested in USA based payment systems.

But you already use Paypal.  Open Collective, also uses Paypal, but also Stripe and Transferwise too.

What Open Collective is basically doing is making it easy for people to become the fiscal hosts for projects/ groups who don't have a legal entity/ bank account.  It's a great service.

The primary Open Collective legal structure is US based (but so is PayPal, which you already use), but there are fiscal hosts all over the place and you can choose which one you'd like to use.

Here is the list of hosts:
https://opencollective.com/hosts

**Comment by xet7** [comment]
@jdaviescoates 

I will worse about even discussing about that kind of additional complexity.

**Comment by xet7** [comment]
> > I am not planning to add GitHub Sponsors, Open Collective, Liberapay or any other additional option. I got hurt enough with BountySource.
> 
> That is a shame.

It's just trying to shame someone like me, that is badly hurt, to think again all the feelings I got from BountySource, and waste time in "shopping around". There is so many host options that it's the same trust problem as in amount of TLS certificate providers.

I already have some payment methods that currently work.

**Comment by xet7** [comment]
It seems some others have problems with BountySource:

https://github.com/bountysource/core/issues/1586

https://news.ycombinator.com/item?id=37384014

**Comment by ocdtrekkie** [comment]
Wow that looks really bad.

**Comment by abebeos** [comment]
> I feel
> badly hurt
> I'm still a little scared

@xet7 , I feel that you're overdoing it in expressing your feelings. This is IT - things happen naturally.

Bountysource could be identified as a weak system easily (messy processes, amateurish presence/content). So, if  you go hurt, that's on you.

Open-Collective looks fine.

And talking about feelings:

This page scares me: https://wekan.team/commercial-support/

(@xet7 - all good, do as you please)

**Comment by jdaviescoates** [comment]
> > Open-Collective looks fine.
> 
> No, they have had problems with payments to others.

Have they? Can you point me to any evidence of that? I'd guess that any problems are likely related to payment providers rather than Open Collective themselves. Or perhaps from shoddy fiscal hosts who are slow to process stuff (which is out of their control).

I've been using Open Collective for years, both as a hosted collective and as a host myself and I'm not aware of any issue with them. They have a great team (I know some of them) and are doing great work. They are even cooking up plans to "Exit to the community" to become owned by the hosts and collectives that depend on the platform, see https://opencollective.com/e2c

**Comment by abebeos** [comment]
> There have been customers, where I have coded for them for many months, and then they did not pay me, when it was about postpaid work. That can cause some feelings. That is why I accept prepaid work only.

Well, I feel you.

I lost now $900 to bountysource, and some open-source work did not go that well:

- https://github.com/deepnest-io/Deepnest/issues/130

So, in the end, everything is fine, as long as you (and your paying users) are fine with it.

@jdaviescoates 

know when to stop. It is time.

**Comment by xet7** [comment]
@jdaviescoates 

> Have they? Can you point me to any evidence of that?

I did not find that webpage where was some evidence.

Now that I looked at Open-Collective details, it seems to add more fees, delays, bureaucracy, time to understand how it works. Are there any benefits at all?

**Comment by abebeos** [comment]
> Are there any benefits at all?

I was curious, for myself, but I just aborted the evaluation process, due to this:

>We have created the [Open Source Collective](https://opencollective.com/opensource), a non-profit umbrella organization, to serve the open source community. To join, you need to meet our [verification criteria](https://www.oscollective.org/#criteria).

> Fees: 10% of funds raised.

> Our fees cover operating costs like accounting, payments, tax reporting, invoices, legal liability, use of the Open Collective Platform, and providing support. We also run a range of initiatives to support a sustainable and healthy open source ecosystem. Join us!

So, you're right:

- additional cost
- additional overhead
- additional buerocracy

**Comment by TouchstoneTheDev** [comment]
Are there any bounties active

**Comment by xet7** [comment]
@TouchstoneTheDev 

BountySource is not used anymore.

Paid development info is at https://wekan.team/commercial-support/

Roadmap link is at https://wekan.github.io

**Comment by xet7** [comment]
News about BountySource, that is not used with WeKan anymore:

https://boehs.org/node/bountysource

https://news.ycombinator.com/item?id=40253514
