### ISSUE TITLE
Wekan (Snap) was very slow after I sync LDAP users (15K users)

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#3178]
I am using Snap

Login and logout is slow.
Open board is very slow.

Is that any way to revert this?
I didn't use group filter. In really, I don't need all this users in my database.
I think that was my fault.

Thanks!

**Comment by xet7** [comment]
@helioguardabaxo 

First make [Backup](https://github.com/wekan/wekan/wiki/Backup)

I have not tested this, but you could try:
- Add group filter where is only some users
- Add that ldap group to your ldap
- Use nosqlbooster to connect server via SSH to server localhost port 27019
- Delete extra users from users table
- Turn off ldap sync

**Comment by helioguardabaxo** [comment]
@xet7 

Should I edit this fields?
ldap-group-filter-enable: 
ldap-group-filter-objectclass:  
ldap-group-filter-id-attribute: 
ldap-group-filter-member-attribute: 
ldap-group-filter-group-name:

In others applications, I use 'cn=nti' to filter a group that I need. This is used in ldap-group-filter-objectclass?

**Comment by xet7** [comment]
@helioguardabaxo 

You can try these examples:
https://github.com/wekan/wekan/wiki/LDAP#active-directory-ldap-part

**Comment by kevin1017** [comment]
This link cannot be found.

**Comment by kevin1017** [comment]
This link cannot be found.
https://raw.githubusercontent.com/wekan/wekan/edge/docker-compose.yml

**Comment by helioguardabaxo** [comment]
My workaround:
- Copy user table from backup previous LDAP synchronization
- Replace user table from most recent backup
- Restore backup

Thanks for you help, @xet7!
