### ISSUE TITLE
written comments aren't visible in mobile view

### ISSUE THREAD

**Issue by mfilser** [wekan/wekan#3182]
**Server Setup Information**:

* Did you test in newest Wekan?:
* Wekan version: 4.15
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome mobile

**Problem description**:

I upgraded from version 4.03 to version 4.15, now the written comment's aren't visible anymore in the card at mobile view, at desktop view, it's still there.

**Comment by xet7** [comment]
I'm in progress of fixing this.

**Comment by xet7** [comment]
I'm currently checking in which version this did get broken. It was not because of latest changes in newest version.

**Comment by xet7** [comment]
It seems it wors in Wekan v4.13 but is broken in v4.14

**Comment by marc1006** [comment]
I found the issue. Will create a PR.

**Comment by xet7** [comment]
@marc1006 

Comments are visible when I reverted your [Fix infinite scrolling for activities](https://github.com/wekan/wekan/pull/3168) but it would be very nice if these both could be fixed at the same time:
- Infinite scrolling on activities
- Showing comments on card on mobile view

I will wait for your PR.

**Comment by marc1006** [comment]
@xet7 Here it is https://github.com/wekan/wekan/pull/3183 :)

**Comment by xet7** [comment]
@mfilser 

Try Wekan v4.17

**Comment by mfilser** [comment]
It works very well with version 4.17, thank's a lot @xet7 and @marc1006  :slightly_smiling_face:
