### ISSUE TITLE
how to build & run wekan repo on ubuntu os 20.04.

### ISSUE THREAD

**Issue by Mrian07** [wekan/wekan#3188]
hi is that running wekan repo on ubuntu 20.04? I have installed ubuntu linux Os 20.04 and want to build wekan on my computer, is there any instructions and documentation that explains install wekan source code on ubuntu 20.04. i have clone repo wekan from github. after that run rebuild-wekan.sh and choose 1 after that I choose 3 for run projects. but that doesn't work

**Comment by xet7** [comment]
Steps 3-5
https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm#3-fork-wekan-and-clone-your-fork

**Comment by rianseven** [comment]
hi @xet7 , is there a document document how to upload the build repo results on the aws ec2 server. I have repaired the mobile UI version, and I want to upload the results of my build on the AWS EC2 server?

**Comment by xet7** [comment]
@Mrian07 

```
cd wekan/.build

scp -i ec2serverkey.pem -rp bundle ubuntu@SERVER-IP-ADDRESS:/home/ubuntu/

ssh -i ec2serverkey.pem ubuntu@SERVER-IP-ADDRESS-HERE

sudo apt install npm mongodb-server mongo-tools screen

sudo systemctl enable mongodb
# or: mongod

sudo systemctl start mongodb
# or: mongod

npm -g install n

n 12.18.1

npm -g install npm

git clone https://github.com/wekan/wekan

mkdir wekan/.build

mv bundle wekan/.build/

cd wekan

screen

# press space couple of times to get to command prompt

nano start-wekan.sh

# Change:
# ROOT_URL=http://YOUR-SERVER-IP-ADDRESS:2000
# PORT=2000
# Then: Ctrl-o Enter Ctrl-x Enter

start-wekan.sh
```
Then at AWS Security Groups open port 2000 and browse to that URL above.

Alternatively, you can configure some other webserver in front of Wekan to provide SSL etc.

**Comment by xet7** [comment]
There is info about setting Wekan as service at:
https://github.com/wekan/wekan/wiki/Raspberry-Pi
