### ISSUE TITLE
'Welcome to Nginx' screen after setting up config

### ISSUE THREAD

**Issue by wellgoodthen** [wekan/wekan#3190]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 4.17.0
* Operating System: Ubuntu 18.04 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 12.18.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome 83.0.4103.106

**Problem description**:
This is not a problem with Wekan and is undoubtedly something people familiar with nginx already know; just passing some feedback on the [the Nginx config wiki](https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config) that would have helped me. Apologies if this is not the appropriate channel for sending Wiki feedback. (Note: I installed nginx using the instructions on the [AWS wiki](https://github.com/wekan/wekan/wiki/AWS))

I followed the [the Nginx wiki](https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config) and reached a point where everything was installed correctly and 'sudo nginx -t' was passing (with warnings), but when I went to the root-url I was still getting the generic welcome screen from nginx saying 'Welcome to nginx! If you see this page, the nginx web server is successfully installed and working. Further configuration is required'

I got stuck here for a very long time, fiddling with my config files, until I found [this answer](https://stackoverflow.com/questions/11426087/nginx-error-conflicting-server-name-ignored). In my install, 'default' files had been automatically created in /etc/nginx/conf.d/ and in /etc/nginx/sites-available/

Once I deleted those files, nginx was working instantly. Propose a new step could be added to the wiki, before the 'sudo nginx -t' step, instructing users to check whether they have those 'default' files and delete them if they do.

**Comment by xet7** [comment]
Thanks! I added it to https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config
