### ISSUE TITLE
Wrong formatting of Markdown in card title

### ISSUE THREAD

**Issue by RayMacLewis** [wekan/wekan#3191]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 4.17.0

**Problem description**:
When adding a new card which has for example the title "11. test" it will automatically transformed into "1. test" in the overview. If you enter the card and click on the title it will show "11. test" again. I guess this is an error in the Markdown formatting which interprets this as an enumeration.

**Comment by xet7** [comment]
Moved to #1421
