### ISSUE TITLE
Wekan Installation

### ISSUE THREAD

**Issue by ameddeb** [wekan/wekan#3193]
Hello, I encountered some  problems with the installation of Wekan, is someone there to guide me please?

**Comment by xet7** [comment]
@ameddeb 

a) Commercial Support is at email support@wekan.team https://wekan.team/commercial-support/ , that has possibility for remote desktop guided install etc more complex installations, and is per hour paid service with private communication. Commercial Support response time is prioritized as fastest.

b) Open Source free support is by adding public comments to this issue, describing what is the error etc, and not adding any identity information like server addresses, passwords etc. Anyone can answer those questions, and there is no quaranteed response time.

**Comment by ameddeb** [comment]
Ok Thank you very much


​Ahlem 
MEDDEB 
​|
​ Software Developer
R&D
Office:
Email:
+216 71 160 600
ameddeb@vermeg.com
Follow WHO hygiene and safety instructions for COVID-19 prevention: Take care and keep safe!
​VERMEG BCP team is at your disposal, for any information don’t hesitate to contact : InfoSec@vermeg.com
​This message, including any attachments, may contain confidential and privileged information for the sole use of the intended recipient(s). Review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient, or authorized to receive information for the recipient, please contact the sender by reply email, and delete all copies of this message. Thank you.
​
________________________________
