### ISSUE TITLE
Problem deploying to Heroku

### ISSUE THREAD

**Issue by JHSheridan** [wekan/wekan#320]
When the app is building on Heroku, I get the following error message in the Heroku dashboard:

```
-----> Fetching custom git buildpack... done

-----> Node.js app detected

-----> Installing node

-----> Installing meteor

Downloading Meteor distribution

Meteor 1.2.0.1 has been installed in your home directory (~/.meteor).

Now you need to do one of the following:

  (1) Add "$HOME/.meteor" to your path, or

  (2) Run this command as root:

        cp "/tmp/buildpack_75d843d2ec26f4e12cdec3c2dad36245/meteor-9YtG/.meteor/packages/meteor-tool/1.1.8/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor

Then to get started, take a look at 'meteor --help' or see the docs at

docs.meteor.com.

-----> Bundling bundle

-----> Building Meteor with ROOT_URL: https://<App Name>.herokuapp.com

$ROOT_URL, if specified, must be an URL.

 !     Push rejected, failed to compile Node.js app

```

Any ideas?

**Comment by mquandalle** [comment]
You need to manually update the `ROOT_URL` variable to give it the URL your are will be served from (for instance `https://<App Name>.herokuapp.com`)

**Comment by vandretti** [comment]
I still have the same error even after I updated the ROOR_URL variable. It seems this error does not occur prior to Meteor version 1.2.0.1

**Comment by mquandalle** [comment]
I've just re-tested Heroku deploy and it works for me. @vandretti are you sure that (1) you given a name to your application and (2) set `ROOT_URL` to `https://<App Name>.herokuapp.com`?

**Comment by vandretti** [comment]
Thanks for checking.  I made sure that the both (1) and (2) are set up as Config Vars in my heroku app dashboard (i.e. under settings menu). Using git push -f heroku master, the Heroku build log produced addition errors as shown below:

remote: Meteor 1.2.0.2 has been installed in your home directory (~/.meteor).
remote: 
remote: Now you need to do one of the following:
remote: 
remote:   (1) Add "$HOME/.meteor" to your path, or
remote:   (2) Run this command as root:
remote:         cp "/tmp/buildpack_fba7755de52a8223dab919f93df6f922/meteor-JXII/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
remote: 
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: -----> Bundling bundle
remote: -----> Building Meteor with ROOT_URL: http://backtestchart.herokuapp.com
remote: => Errors executing Cordova commands:
remote: 
remote:    While building Cordova app for platform Android:
remote:    Error:
remote:    /tmp/build_fba7755de52a8223dab919f93df6f922/.meteor/local/cordova-build/platforms/android/cordova/build:
remote:    Command failed with exit code 2 Error output:
remote:    [Error: Failed to find 'ANDROID_HOME' environment variable. Try setting
remote:    setting it manually.
remote:    Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to
remote:    include path to valid SDK directory.]
remote:    at ChildProcess.whenDone
remote:    (/tmp/buildpack_fba7755de52a8223dab919f93df6f922/meteor-JXII/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
remote:    at ChildProcess.emit (events.js:98:17)
remote:    at maybeClose (child_process.js:766:16)
remote:    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to backtestchart.
remote: 
To https://git.heroku.com/backtestchart.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/backtestchart.git'

**Comment by mquandalle** [comment]
So it is actually a different issue than the OP’s one. The `cordova` part is weird, we don’t have any support for it and I don’t see why it tries to search for things like `ANDROID_HOME`...
Have you tried on the `master` branch?

**Comment by vandretti** [comment]
Yes. I only use the master branch.

Coincidentally, I also have a failure trying to use "mup deploy"  for install this app to Amazon EC2. The mup logs show a lot of conflicts as it's still using Meteor@1.1.5 in the build process. According to them, meteor 1.2 requires an upgrade to  node version "0.10.40". 

I noticed that the Heroku logs above said  "failed to compile Node.js app". How do I check for which version of Node.js is used by Heroku?

**Comment by mquandalle** [comment]
Theoretically it uses [the last version of the node v0.10.x branch](https://github.com/AdmitHub/meteor-buildpack-horse/blob/fb37ee8c099dbd8113c8dba2fe0a72707ca2c4f8/bin/compile#L54) ie Node v0.10.40 which is exactly the version we require for Wekan.

**Comment by mquandalle** [comment]
Is this resolved?

**Comment by anissen** [comment]
> Is this resolved?

I encountered the same issue as @JHSheridan. Correcting the `ROOT_URL` field after trying to deploy still resulted in the same error.

However, starting over and setting the `ROOT_URL` field before attempting to deploy succeeded without any errors.

**Comment by sidneysm** [comment]
try to remove android platform in .meteor/platforms
