### ISSUE TITLE
./start-wekan.sh not working ubuntu 20.04

### ISSUE THREAD

**Issue by Mrian07** [wekan/wekan#3200]
when I run the application ./wekan-start.sh it becomes like the following screenshot?
whereas when run using the meteor app runs fine

is there a solution?
![Screenshot from 2020-06-30 22-48-40](https://user-images.githubusercontent.com/45984394/86147891-2314bd80-bb24-11ea-9a6d-98ec1a9ba3f3.png)

**Comment by xet7** [comment]
@Mrian07 

Did you have this at your start-wekan.sh ?
```
ROOT_URL=http://localhost:2000
PORT=2000
```
Do you have mongodb running at port that is defined in start-wekan.html ?

**Comment by Mrian07** [comment]
not a problem ./start-wekan.sh

apparently there was a problem when I was ./rebuild-wekan.sh

in the .build / bundle / web browser folder does not include the compressed css file.

so the conclusion of my problem when build wekan, build folder can not include css files. Is JS only available?

is there a xet7 solution?
I have made many changes in time

**Comment by Mrian07** [comment]
[app.unopipe.com](url)

(currently I enter css files manually in the build / bundle folder), by associating merged_style in the bundle ?. even though my problem seems to have been seen / done.
but I still have interference in spead time, because my css file is entered manually

**Comment by Mrian07** [comment]
https://app.unopipe.com/

**Comment by xet7** [comment]
@Mrian07 

There is prebuilt bundle with name wekan-VERSION-NUMBER.zip at https://releases.wekan.team

There are separate bundles for x64, arm64 and s390x. Installing and using them is described at:
https://github.com/wekan/wekan/wiki/Raspberry-Pi

For production use, I mainly use [Snap](https://github.com/wekan/wekan-snap/wiki/Install), that has automatic updates.

For more info how Wekan works, and Wekan developement, see https://github.com/wekan/wekan/issues/3203#issuecomment-656599602

**Comment by xet7** [comment]
@Mrian07 

I edited your comments to removed those public links to your private server. Please do not add private info to these public issues.
