### ISSUE TITLE
[Feature Request] Allow admin users the ability to delete others comments on cards

### ISSUE THREAD

**Issue by r0bbie** [wekan/wekan#3201]
As an admin user there currently doesn't seem to be any way to delete other users comments on cards, even if the admin has full access to edit / delete the card itself. This seems an odd inconsistency and can certainly envision a lot of situations where an admin not having this ability could be problematic. Would be great to see this feature implemented.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3340
