### ISSUE TITLE
Node CPU Usage High 100%+

### ISSUE THREAD

**Issue by Keelan** [wekan/wekan#3202]
## Issue

Im having very high CPU issues. Basically so bad it makes wekan unresponsive until i restart it and im simply copying a card or deleting a card.

Server Specs:

- Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
- 32GB RAM
- 6TB HDD

**Server Setup Information**:

* Did you test in newest Wekan?: **Yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings?:  **Yes**
* Wekan version: **4.17**
* Operating System: Ubuntu **16.04**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **Source**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Apache2**
* Node Version: **12.18.1**
* MongoDB Version: **4.28**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Chrome**

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
![image](https://i.imgur.com/rL1CyrE.gif)
- *Explain steps how to reproduce* **Copy a card or delete a card with lots of checklists**
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.:* **Nope**

**Comment by xet7** [comment]
@Keelan 

How many users you have using Wekan at the same time?

**Comment by xet7** [comment]
@Keelan 

How many cards you have at board?

**Comment by Keelan** [comment]
I have say 30 users but only 1 or 2 use it at the same time.

It only seems to happen when I have lots of checklists in the card I want
to copy/delete. Spikes to 150% cpu , when you try to reload the webpage it
hangs. I end up restarting wekan service

I'm assuming its just processing the card and checklists but seems very
resource intense for a copy/paste.

**Comment by xet7** [comment]
@Keelan 

Please try Wekan v4.17

**Comment by xet7** [comment]
@Keelan 

Also, please upgrade to newest Ubuntu.

**Comment by Keelan** [comment]
> @Keelan
> 
> Please try Wekan v4.17

I'm on 4.17 (i put 4.16 by accident)



> @Keelan
> 
> Also, please upgrade to newest Ubuntu.

Id rather not if i can help it, this is a stable in production server. That can't honestly be the solution?
The only time i get this node issue is with checklists. Seems very wekan specific not OS specific.

**Comment by xet7** [comment]
@Keelan 

When you have lot's of checklist on the card, you should not reload webpage, because copy/delete is still in progress. Is there some reason you can not wait for that copy/delete to finish?

**Comment by xet7** [comment]
Upgrading to newest Ubuntu is not required.

**Comment by xet7** [comment]
How many checklists you have on card?

**Comment by Keelan** [comment]
@xet7 
How would the end user know the copy is finished?
From a user perspective, they copy the card. See the card is there and 0/44 checklist items complete (suggesting the copy is complete) and move on to copying another card. Ultimately they copy a few cards in a row and wekan will hang (though ive noticed wekan hang even on one card). Then the user will lose the majority of the cards because the system had hung copying.
https://i.imgur.com/xj0sW6K.gif
https://i.imgur.com/R7eu2sh.gif
https://i.imgur.com/GWACrzs.png

Is the solution to copy a card and wait 5 minutes before coping another?
Why does refreshing/navigating away not continue the copy in the background?
If the user navigates away in the middle of a copy they lose data?

**Comment by xet7** [comment]
@Keelan 

Currently the solution is to copy card and wait before copying another. Refreshing page can lose data. I am looking into how to fix this, fix will be in some future Wekan update.

**Comment by helioguardabaxo** [comment]
@Keelan 
Is the problem the number of swimlanes in the board?
I have a board with several swimlanes(20) and it always takes a long time to load.
Could you test the same cards on a board with only one swimlane?

**Comment by Keelan** [comment]
I've tried it on a brand new install, new board with no rules, default 1
swimlane and 1 list.

**Comment by xet7** [comment]
Moved to #3203
