### ISSUE TITLE
Exporting to CSV leads to UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by virEmtUgpilUryai** [wekan/wekan#3209]
**Server Setup Information**:

* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?

Yes.

* Wekan version:

- v4.17

* Operating System:

- Debian 10 Buster (amd64)

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):

- Installed via quay.io/wekan/wekan:v4.17

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):

- nginx

* Node Version:

- 

* MongoDB Version:

- mongo v4.2.8

* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

- Tested both Firefox v75 and Vivaldi 3.1.1929.45

**Problem description**:

- Go to menu, trigger export to CSV file. Wait for 50 seconds, error 504 (timeout appears). Further digging see belog (log).

Log:

`(node:1) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received undefined

at write_ (_http_outgoing.js:653:11)

at ServerResponse.write (_http_outgoing.js:621:15)

at models/export.js:93:11

at doCall (packages/meteorhacks_picker.js:128:14)

at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)

at processNextRoute (packages/meteorhacks_picker.js:90:14)

at processNextMiddleware (packages/meteorhacks_picker.js:78:7)

at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)

at packages/meteorhacks_picker.js:162:10

at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by virEmtUgpilUryai** [comment]
Upgraded to 4.18, same problem.

Exporting to JSON works in both releases, though.

**Comment by xet7** [comment]
Moved to #3173
