### ISSUE TITLE
Running Wekan in a subdir

### ISSUE THREAD

**Issue by maikeldus** [wekan/wekan#321]
Hi,

I tried to run 
```
docker run -d -e "MONGO_URL=mongodb://172.17.42.1:27017/wekan" -e "ROOT_URL=http://somedomain.com/wekan/" -p 6030:80 mquandalle/wekan
```

And put this in my Nginx:
```
location /wekan/ {
        proxy_pass http://127.0.0.1:6030;
    }
```

But it seems it does not work. I get "page not found" and when i want to login i get redirected to `somedomain.com/sign-in` (which will work because of HTML5 url changing, but it needs to be `somedomain.com/wekan/sign-in`).

It seems someone other people stated this problem before and there was a fix as stated before in:
https://github.com/kadirahq/flow-router/pull/329 but it does not seem to work (since I just pulled it from docker).

Can anyone help me? Am i missing some enviroument variables?

**Comment by mquandalle** [comment]
hi @maikeldus, thank you for the bug report. This issue is fixed on `devel`. I don’t know when I will release Wekan v0.10 but if you don’t want to wait you can follow https://github.com/wekan/wekan/issues/133#issuecomment-146691959.

**Comment by maikeldus** [comment]
Thx!
