### ISSUE TITLE
Bug! Clone cards in home not working.

### ISSUE THREAD

**Issue by andynhoo** [wekan/wekan#3216]
## Issue
The clone of the cards in the home is not working. There is an error in the console.

**Server Setup Information**:
Wekan Version 4.20.0

Version 
**Problem description**:
The clone of the cards in the home is not working. There is an error in the console.
![Sem título](https://user-images.githubusercontent.com/7599346/88087366-29182000-cb5f-11ea-8353-0f3e1b19f079.png)

**Comment by Fox2726** [comment]
Wekan Version 4.21.0

Clone board had the same error message.

Exception while simulating the effect of invoking 'cloneBoard' TypeError: a.build is not a function
Exception in delivering result of invoking 'cloneBoard': TypeError: this.setError is not a function

**Comment by xet7** [comment]
This was fixed here https://github.com/wekan/wekan/commit/1624fc82f7c319e84a78f29445c7867f7da15c32 , will be in next release later today.
