### ISSUE TITLE
board export API always returns zero bytes

### ISSUE THREAD

**Issue by papimla** [wekan/wekan#3219]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: **yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?  **yes**
* Wekan version:  **4.20**
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: **Debian GNU/Linux buster**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **snap**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **nginx reverse proxy**
* Node Version: 
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **curl**

**Problem description**:
- *Explain steps how to reproduce* 
```
$ curl https://wekan.mlalerte.ovh/users/login -d "username=loic&password=XXXXXXXXXX"
{"id":"Mx3syo6wNqYDEWemR","token":"XXXXXXXXXXXXXXXX","tokenExpires":"2020-10-20T09:22:11.184Z"}
$ curl --silent -H "Content-type:application/json" -H "Authorization: Bearer XXXXXXXX" -X GET https://wekan.mlalerte.ovh/api/boards
[{"_id":"bP8vf3SJtE95w2cQF","title":"XXXXXXXX"}]
$ curl --verbose -H "Content-type:application/json" -H "Authorization: Bearer XXXXXXX" -X GET https://wekan.mlalerte.ovh/api/boards/bP8vf3SJtE95w2cQF/export
[... redacted ...]
> GET /api/boards/bP8vf3SJtE95w2cQF/export HTTP/1.1
> Host: wekan.mlalerte.ovh
> User-Agent: curl/7.64.0
> Accept: */*
> Content-type:application/json
> Authorization: Bearer XXXXXXXXXXXXXXXXX
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 22 Jul 2020 09:26:15 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-store
< Pragma: no-cache
< 
* Connection #0 to host wekan.mlalerte.ovh left intact
```

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/3173#issuecomment-662003592
