### ISSUE TITLE
Add pluralization to translatable strings

### ISSUE THREAD

**Issue by apienk** [wekan/wekan#3220]
## Issue

**Server Setup Information**:

* Wekan version: 4.21.0
* Operating System: Linux amd64
* Deployment Method: snap
* Http frontend: node
* Node Version: 12.18.2
* MongoDB Version: 3.2.22
* Web browser: Chrome 84.0.4147.89

**Problem description**:

None of the translatable strings in Wekan code are currently pluralized. i18n pluralization is necessary for using proper forms following numbers in most languages, e.g. 1 "Card" but 2 "Cards". In Polish, which I work on, there are 3 different forms (e.g., 1 karta, 2 karty, 5 kart). Please enable pluralization for each string which follows a number.

**Comment by xet7** [comment]
Please add pull request with plurals for this file:
https://github.com/wekan/wekan/blob/master/i18n/en.i18n.json
