### ISSUE TITLE
Exporting from version 4.20.0 on Sandstorm to anything (json, html...) does not work (neither cloning boards)

### ISSUE THREAD

**Issue by juankaamez** [wekan/wekan#3221]
## Issue

After upgrading to Wekan 4.20.0 on sandstorm (everything working properly), we cannot export to any format (json, html, csv..) The file after exporting are 0 bytes long, but no error is thrown.
We cannot copy any board either.

We have read that this is an issue and that it will be fixed. Do you know if we can do anything to have the server in proper conditions again? 
Is there a fix coming? If so, should we wait for an automatic update, as we have them activated and they do usually work?

**Comment by xet7** [comment]
@juankaamez 

Yes, coding a fix is in progress. Please wait for automatic update that will probably come sometime this or next week.

Moved to https://github.com/wekan/wekan/issues/3173#issuecomment-663447915
