### ISSUE TITLE
Bundle with Windows Node+MongoDB v4.22 - Custom port breaks card url after it has been added.

### ISSUE THREAD

**Issue by unknown797** [wekan/wekan#3222]
- Wekan version 4.22
- Windows 10 Pro Build 1903
- Bundle with Windows Node+MongoDB
- Apache/2.4.43 (Win64) on Port 80
- Node Version: v12.18.2
- MongoDB Version: MongoDB 4.2.8 Community
- Browser: Firefox 78.0.2 (64-bit)

**Problem description**:

1. Edit start-wekan.bat file to change default port from 80 to port 81 to avoid conflict with Apache web server on port 80.

SET ROOT_URL=http://localhost
SET PORT=**81**
SET MONGO_URL=mongodb://127.0.0.1:27017/wekan 

2. Save file and run start-wekan.bat.
3. Able to use Wekan as per normal, however after adding card, I am unable to edit the card as the href link no longer includes the port details when the url is generated.

Expected URL from href link:

localhost:81/xyzetc...

Result URL from href link

localhost/xyzetc...

![image](https://user-images.githubusercontent.com/68732442/88377470-5c72dd00-cdf3-11ea-9293-e5914702f0da.png)

I've found a temporary fix by changing the start-wekan.bat file by adding the port to the ROOT_URL as well.

SET ROOT_URL=http://localhost:81
SET PORT=81
SET MONGO_URL=mongodb://127.0.0.1:27017/wekan

**Comment by xet7** [comment]
@unknown797 

Your temporary fix is the correct final fix.

**Comment by xet7** [comment]
Also, if you like to access same Wekan in local network from other computers and mobile devices, you need to change localhost to your computer IP address, like this:
```
ROOT_URL=http://192.168.0.200:81
```
More info:
https://github.com/wekan/wekan/wiki/Settings
