### ISSUE TITLE
Could you update 4.22 to Sandboard versions

### ISSUE THREAD

**Issue by juankaamez** [wekan/wekan#3223]
## Issue

Sandboard not updated to 4.22, therefore vital updates (export and card cloning) still not working. Could you please update the sandboard version? Thanks a zillion!

And please accept our most sincere congratulations for the fixes in 4.22 ;-)
Thanks a lot! You rock! Great job!

**Comment by xet7** [comment]
AFAIK export does not work yet on Sandstorm Wekan v4.22. 

If you have full backups of whole Sandstorm and also separate Wekan grain backups in downloaded .zip files, you can try Wekan experimental:
https://github.com/wekan/wekan/wiki/Sandstorm#wekan-app

But I would really recommend waiting that @ocdtrekkie has time to test it, is there any critical bugs, and release official version.

Anyway, newest is always on experimental, and after testing released to official.

**Comment by xet7** [comment]
Anyway, I try to get all export options fixed in near future.

**Comment by ocdtrekkie** [comment]
Generally Sandstorm versions will wait until a release where everything is working well. So we're holding on the export issue. But the experimental market is indeed a good choice if you need a fix faster than we approve it.
