### ISSUE TITLE
My IP was changed by my internet provider. Now I cannot open the cards created under a different URL.

### ISSUE THREAD

**Issue by Paula-T-F** [wekan/wekan#3225]
## Cannot open cards after an IP change by my internet provider

Thanks for your wonderful work with Wekan. I love it.
My hubbie set an Oracle Virtual Machine in my Windows PC to run Wekan under Windows 10, as a self-hosted site which I use to track a project with different stages and tasks, and which I share it with an associate in a different country. So far I could set up the site, the users, create lists and cards for all the jobs. 
I was happy.

I used to connect to the wekan site by navigating to the URL in my browser, after initiating the virtual machine.
So far everything was going well.

**Problem description**:

This week my internet provider changed the IP and now I can open the board and see all the cards in their lists. But when I try to open any card for edition, I get an error. The card URL I get on the browser with the failed connection starts with the old URL and obviously leads nowhere. I have tried to replace the first part of the URL by the new one and leave the rest. If I do this, I can effectively open the card and see it. But as soon as I close it and want to reopen it, I get the same issue. The card is redirected (prefixed) to the old URL.

**Server Setup Information**:

For instance (not real IP numbers):

My previous URL was 
186.19.217.213:9000
so that the ID for a card, any card as an example, was:
186.19.217.213:9000/b/PzkbLEqKG3DZH7mDx/MyBoard/KWNXs8X8specMs84Z

Now the new IP has changed to
181.47.124.230
and when I open the site 
inputing the URL
187.47.124.230/9000
I get a successful connection to:
187.47.124.230/9000/b/PzkbLEqKG3DZH7mDx/MyBoard/

And see my board all right.
But when I click a card to edit it,
instead of opening the card in 181.47.124.230:9000/b/PzkbLEqKG3DZH7mDx/MyBoard/KWNXs8X8specMs84Z
the URL which comes up (with an error and the card is not opened) is 
186.19.217.213:9000/b/PzkbLEqKG3DZH7mDx/MyBoard/KWNXs8X8specMs84Z

and, of course, I cannot see the card.
If I replace the first part of this URL with 181.47.124.230:9000, I can open the card. But upon closing it, the new IP is not saved, and every time I try to use the card again, the old URL is triggered.

Even if I could find a way to manually change and save every URL address for each card, there are a lot of them, and this would not be practical at all.

Can you help me find a solution here? I am not a programmer, although I have used systems and computers for more than 30 years, and I apologize if my issue sounds stupid to you. 
Wekan is amazing as a self-based app and I really want to make it work.

Thank you very much!

**Comment by xet7** [comment]
In Linux terminal, try type:
```
sudo snap set wekan root-url='http://181.47.124.230:9000'
```
For more info, see http://github.com/wekan/wekan/wiki/Settings

**Comment by Paula-T-F** [comment]
This worked very well. I am most grateful for your prompt and great help.
Small but sincere donation coming now!
