### ISSUE TITLE
Windows Bundle: Batch file fails to run

### ISSUE THREAD

**Issue by p2635** [wekan/wekan#3229]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Y
* Did you test in newest Wekan?: I think so
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? I followed https://github.com/wekan/wekan/wiki/Windows
* Wekan version: 4.2.2
* Operating System: Windows 10
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): N/A
* Node Version: 12.18.3
* MongoDB Version: When I run choco list, I get mongodb 4.2.8 and mongodb.install 4.2.8
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox

**Problem description**:
- *Explain steps how to reproduce*

1. Follow steps in https://github.com/wekan/wekan/wiki/Windows
2. Put a shortcut for the batch file in the windows startup file
3. Restart PC
4. The batch file doesn't successfully to run completely (see log below)
5. Browser tab still shows yesterday's screen with this message, I'm scared to refresh.

![image](https://user-images.githubusercontent.com/4522927/89627393-b1eac780-d892-11ea-95fe-734349c5fc97.png)

**Log**

I then tried to run it manually to see the log.

```
PS C:\wekan-4.22\bundle> .\start-wekan.bat
C:\wekan-4.22\bundle\programs\server\node_modules\fibers\future.js:313
                                                throw(ex);
                                                ^

MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (C:\wekan-4.22\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\core\topologies\server.js:438:11)
    at Pool.emit (events.js:315:20)
    at C:\wekan-4.22\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\core\connection\pool.js:561:14
    at C:\wekan-4.22\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\core\connection\pool.js:994:11
    at C:\wekan-4.22\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\core\connection\connect.js:31:7
    at callback (C:\wekan-4.22\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\core\connection\connect.js:264:5)
    at Socket.<anonymous> (C:\wekan-4.22\bundle\programs\server\npm\node_modules\meteor\npm-mongo\node_modules\mongodb\lib\core\connection\connect.js:294:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  [Symbol(mongoErrorContextSymbol)]: {}
}
````

My guess is mongodb is not running? But I don't know how to use choco to check whether it's running and just running mongodb does nothing in the terminal (unrecognised). If I am right then does the batch file need to be updated to run mongodb before it does anything else?

**Comment by xet7** [comment]
Do you have any data in mongodb? For me those steps do work. When I reinstalled mongodb this way, mongodb still works:
```
choco uninstall -y mongodb
choco install -y mongodb
```

**Comment by xet7** [comment]
BTW, I do run start-wekan.bat as Administrator in cmd.exe. Not PowerShell.

**Comment by p2635** [comment]
I get the same results on cmd.exe
![image](https://user-images.githubusercontent.com/4522927/89765541-6fbdc200-daee-11ea-9b17-bfd2ddc5e75f.png)

I'm hesitate to reinstall mongodb in case I lose my data. Yet I don't know how to backup mongodb or start it up (if it is indeed not running).

**Comment by xet7** [comment]
@p2635 

I added more info how to use MongoDB on Windows:
https://github.com/wekan/wekan/wiki/Windows

**Comment by p2635** [comment]
Just as you posted that, I worked out how to do it mysyelf! thanks @xet7 

I saw that my MongoDB service was 'Stopped' so I had to start it again. I'm sure net start mongodb does the same thing.
