### ISSUE TITLE
When Url contains column `:`, the display is weird

### ISSUE THREAD

**Issue by netei** [wekan/wekan#323]
Try putting this in the description of a card, it doesn't show the URL : `http://test.com/?b=abc:dd:ff`

It works correctly on github for example here: 

http://test.com/?b=abc:dd:ff

**Comment by AlexanderS** [comment]
The problem is, that `:dd:` is interpreted as smiley.

**Comment by netei** [comment]
Yes, the URL parsing should probably take place **before** the smiley parsing

**Comment by mquandalle** [comment]
Actually the URL parsing already takes place before the emojies one, but it then get overwritten by it — the code is [here](https://github.com/wekan/wekan/blob/57fa7af24c8d59629e1b82f6d4f2173d77710128/client/components/main/editor.jade#L11-L13).

This probably need a larger refactoring about how we handled enhanced inputs.

**Comment by hidepark** [comment]
:+1:

**Comment by blaskovic** [comment]
Hi,

is it possible to globally disable smileys in wekan?

**Comment by nztqa** [comment]
Package comparison
 - [seriousm:emoji-continued](https://atmospherejs.com/seriousm/emoji-continued) (Currently in use")
 - [emojione:emojione](https://atmospherejs.com/emojione/emojione)

## TEST app
- Add packages
```
$ meteor create emoji-test
$ cd emoji-test 
$ meteor add seriousm:emoji-continued emojione:emojione
$ npm install emojione-assets --save
```
### Edit files
- client/main.js
```
$ vi  client/main.js

#Add
emojione.sprites = true;
```
- client/main.html 
```
$ vi client/main.html 

#Add
<h2>seriousm:emoji-continued</h2>
<ul>
  <li>{{> emoji ":smile:"}}</li>
  <li>{{> emoji "16:08:03"}}</li>
  <li>{{> emoji "http://test.com/?b=abc:dd:ff:alien:gg"}}</li>
</ul>
<h2>emojione:emojione</h2>
<ul>
  <li>{{> emojione ":smile:"}}</li>
  <li>{{> emojione "16:08:03"}}</li>
  <li>{{> emojione "http://test.com/?b=abc:dd:ff:alien:gg"}}</li>
</ul>
```
### Result
![image](https://user-images.githubusercontent.com/22808079/27775878-08ab14cc-5fe1-11e7-98fb-f68b571e1879.png)
