### ISSUE TITLE
Azure authentication - The reply URL specified in the request does not match...

### ISSUE THREAD

**Issue by fone** [wekan/wekan#3230]
I used the info here to help configure authentication via azure- https://github.com/wekan/wekan/wiki/Azure
Though when trying to sign in through Oidc, I get the error below:

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'my-azure-app-id-here'

For anyone familiar with Azure app registration, could you please let me know what settings I should configure? I feel like I might be using the wrong Redirct URI, though I'm uncertain what it's expecting.

thank you...

**Comment by xet7** [comment]
https://community.microfocus.com/t5/Identity-Manager-Tips/Creating-the-application-Client-ID-and-Client-Secret-from/ta-p/1776619

**Comment by fone** [comment]
I got the azure application configured, that's how I've managed to get the
error thus far. I think it's expecting a redirect URI that I just don't
know. Like... Https://wekan.site.com/sign-in (or something like this...).

**Comment by xet7** [comment]
Oh, it seems that info was missing from Azure wiki page, I added it.

The redirect URL is your Wekan root-url+_oauth/oidc like this: https://boards.example.com/_oauth/oidc

**Comment by fone** [comment]
apparently I had multiple issues, this redirect URL was key but I also had an old root-url in place.. prior to me setting up https and  changing the port. somehow nginx kept everything working still. after updating the root-url and using the proper redirect on the azure app I'm all set. thank you.
