### ISSUE TITLE
The owner of a board was deleted using the REST API, and now the boards created by him can't be duplicated, renamed or archived.

### ISSUE THREAD

**Issue by hradec** [wekan/wekan#3232]
## The owner of a board was deleted using the REST API, and now the boards created by him can't be duplicated, renamed or archived. 

trying to duplicate the board, gives this in chrome js console: 
![image](https://user-images.githubusercontent.com/806743/89955626-4aad7a00-dbe8-11ea-9e82-5b62ec047034.png)

and this in wekan log: 
![image](https://user-images.githubusercontent.com/806743/89955647-59942c80-dbe8-11ea-95c7-05f4ec885923.png)

**Server Setup Information**:

Using docker-compose to start a mongodb database docker container and a wekan doker container, running the official latest wekan image, as showed below:
![image](https://user-images.githubusercontent.com/806743/89955798-abd54d80-dbe8-11ea-9903-18807179ec67.png)
I've tried with version 4.22 and latest, same issue!

**Problem description**:
-We have Board 1 that was created by user B. 
-User B was deleted using the REST API. 
-Board 1 still shows user B as admin=true when retrieving its data using the REST API (`curl -H "Authorization: Bearer $token"      -H "Content-type:application/json"      -X GET     http://localhost:8080/wekan/api/boards/<board 1 id>`), and all other users as admin=false.
-Using the global admin user A  (the first user added to wekan), I tried to use the REST API (`curl -H "Authorization: Bearer $token"      -H "Content-type:application/json"      -X POST    http://localhost:8080/wekan/api/boards<board 1 id>/members/<user A id>   -d '{"isAdmin": "true", "isNoComments":"false", "isCommentOnly": "false", "isWorker": "false"}'`) attempting to "promote" user A to admin=true. The command execute without error (and no message at all is retrieved), but user A still is admin=false after execution. 

**Question**:
is there any workaround to promote a user to admin in Board 1 so we can rename, archive or duplicate it? 
Even editing the mongodb database directly would suffice for now, just so we can fix just this one board that we need to be able to rename in production. ( a snippet command of how to edit in the mongodb database directly would be appreciated, since I have no idea on how to do it! )

**Conclusion**
We won't delete users using the REST API in the future! I promise!

**Comment by xet7** [comment]
If you use Wekan Snap version, you can use nosqlbooster GUI to connect via ssh to server localhost port 27019.
