### ISSUE TITLE
Error while installing mongodb using chocolatey : MonitoringTools feature not found

### ISSUE THREAD

**Issue by npalmero** [wekan/wekan#3233]
Extract from MSI-install log :
---------------------------------------------------------
MSI (s) (24:D0) [09:12:12:202]: Note: 1: 2711 2: MonitoringTools 
Action start 09:12:12: CostFinalize.
DEBUG: Error 2711:  The specified Feature name ('MonitoringTools') not found in Feature Table.
MSI (s) (24:D0) [09:12:12:202]: Product: MongoDB 4.4.0 2008R2Plus SSL (64 bit) -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: MonitoringTools, , 

The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: MonitoringTools, , 
Action ended 09:12:12: CostFinalize. Return value 3.
Action ended 09:12:12: INSTALL. Return value 3.
---------------------------------------------------------

Full log file 
[mongodb.install_msi_install.log](https://github.com/wekan/wekan/files/5067963/mongodb.install_msi_install.log)

**Comment by xet7** [comment]
I have not used MonitoringTools. For that error, you should contact Chocolatey or MongoDB developers.

When I have installed MongoDB with Chocolatey like described at https://github.com/wekan/wekan/wiki/Windows , Wekan has worked for me.
