### ISSUE TITLE
Sending user email server domain

### ISSUE THREAD

**Issue by easywekan** [wekan/wekan#3236]
## Issue

Just started using this and it is probably just a settings issue I am unaware of but when emails inviting users to join a board are sent it shows the internal ip address of the server - how can this be updated?

It is running on a local ubuntu machine installed via snap and is behind my office firewall and so I am port forwarding to the machine for remote access.

Sorry if this is the wrong place to post this - however I'd also like to find out about the best backing up?

Is there a forum somewhere for wekan as it is fantastic?

**Comment by xet7** [comment]
@easywekan 

Email:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Backup:
https://github.com/wekan/wekan/wiki/Backup

Forum:
When it's not about feature requests and bugs, for just casual chatting at Wekan Community Chat PWA:
https://community.vanila.io/wekan

**Comment by xet7** [comment]
At that community forum there is public chatting with anyone at community, and "Messages" area for private messages about casual chatting.

There is also Commercial Support https://wekan.team/commercial-support/ for priority features/fixes/support/hosting.
