### ISSUE TITLE
Update of Wekan on Sandstorm still needed

### ISSUE THREAD

**Issue by juankaamez** [wekan/wekan#3237]
## Issue
 
Wekan version of Sandstorm is still not updated to the newest version. That is making it impossible to export or make backups of the cards or boards since July.

Sandstorm update to 4.22 is more than needed. 
Thanks!

**Comment by xet7** [comment]
AFAIK in Sandstorm Wekan v4.22 export is not fixed yet. Fixing is still currently in progress.

While Wekan v4.22 is already available at Sandstorm experimental (tip: link to info page somewhere at Wekan homepage), I do recommend waiting for official version where all export options are fixed.

Moved to #3173

**Comment by xet7** [comment]
Oh, about question, why it takes time to fix that export. Suprisingly, life happened, and I lost some time time helping friends. Luckily now I'm back to coding.

**Comment by juankaamez** [comment]
You are doing an amazing job! So totally understandable. Thanks for the great effort and quality!
