### ISSUE TITLE
Feature request: Checklist drag handles for mobile devices

### ISSUE THREAD

**Issue by schweigel** [wekan/wekan#3240]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 4.23.0
* Operating System: debain 10
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 12.18.3
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Vivaldi (newest from PlayStore)

**Problem description**:
It would be nice to have these drag and drop crosses for boards, lists and cards for check lists too. So sorting check list and check list items on mobile devices will be possible.

current:
![image](https://user-images.githubusercontent.com/52450003/90975906-b2dd5380-e538-11ea-9083-0c40a500bedc.png)

possible new:
![image](https://user-images.githubusercontent.com/52450003/90975933-ef10b400-e538-11ea-9733-6475535b5dfb.png)

**Comment by mfilser** [comment]
@schweigel 
Please have a look at the latest Wekan Version 4.57 and give a feedback if it works now as expected :)

**Comment by schweigel** [comment]
It works perfect. Thank you. 👍

**Comment by mfilser** [comment]
Great. Thank's a lot for your feedback @schweigel :slightly_smiling_face:
