### ISSUE TITLE
Drop custom scrollbar

### ISSUE THREAD

**Issue by tborychowski** [wekan/wekan#3241]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: [latest](https://hub.docker.com/layers/wekanteam/wekan/latest/images/sha256-16b859b86cfa0960c5e02328f7b586227e9ba3615034ce7d6c925b14d97106ce?context=explore)
* Operating System: Macos
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none
* Node Version: docker
* MongoDB Version: docker
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
Firefox

**Problem description**:
When a column has more cards than can fit in a screen, so that the scrollbar appears - scrolling on a mac in Firefox adds a weird fading delay and it scrolls more than needed. If I scroll even more - the cards will go all the way up and disappear eventually. (It seems to work fine in chrome).
I'm guessing this is because of a custom scrollbar implementation?

![Screen Recording 2020-08-26 at 08 22 28](https://user-images.githubusercontent.com/392513/91273663-819d9700-e775-11ea-9fd2-11de0661c4b2.gif)

**Comment by xet7** [comment]
What version of Firefox you use?

**Comment by xet7** [comment]
What version of macOS you have?

**Comment by xet7** [comment]
I can not figure out how to duplicate this on macOS Catalina using Firefox 80. More information required.

**Comment by tborychowski** [comment]
Hi @xet7 , thanks for your response.
I've tested this and was able to reproduce on the following platforms/browsers:
- macos catalina + firefox 80
- macos catalina + firefox 81 beta
- macos big sur + firefox 80
- macos big sur + firefox 81 beta
- windows 10 + firefox 80
- windows 10 + firefox 81 beta

Which would suggest that this is not a problem with a particular os/browser version but rather the setup.
Have you been testing this with a regular mouse? 
(I'm using apple's magic mouse or trackpad)
This looks like a problem with how firefox handles the inertia-scrolling and basically the "spin-down" from where the scrolling stopped and the inertia-scrolling starts is when it happens (as in the gif).

**Comment by xet7** [comment]
There are settings for scrollInertia: https://github.com/wekan/wekan/issues/2949#issuecomment-600021905

I just don't have enough info what could be the correct values.

**Comment by tborychowski** [comment]
I've tried to set different values from 0 to 1000 in different configurations (including "auto") but none of them had any effect on this issue.
The issue you've linked was about scrolling inside card details, whereas mine is about scrolling cards inside a column, are these handled the same? e.g. should these 2 values affect both scrollings?

Why is there a need for a custom scrollbar? 
Asking out of curiosity, as in my 20yrs of experience in web dev, there has been such a need only once and it was a long time ago 😄 . Nowadays browsers handle scrolling quite well and I just don't feel the need to reinvent the wheel 😉

**Comment by xet7** [comment]
@tborychowski 

Really? Do you feel like trying to get Wekan working without mouse scroll code, submitting a pull request?

**Comment by xet7** [comment]
Wekan already existed and had mouse scroll code before I started maintaining Wekan at 2016-12. There has been fixes to mouse scroll code when new Chrome update broke it, some Wekan contributor fixed it. My experience is that if I remove that code, scrollbars disappear, and Wekan becomes unuseable.

**Comment by xet7** [comment]
Moved to #2949

**Comment by tborychowski** [comment]
@xet7, thanks. I'd love to contribute, but I'm not familiar with the stack (meteor is it?), so it will take me a while to get familiar with the code (unless it's as simple as removing [this package](https://github.com/wekan/wekan/tree/master/packages/wekan-scrollbar) 😄 ).
But regarding scrollbars - the only reason why you had issues with them is because wekan is using a custom jquery plugin!
If this is removed, and scrollbars are handled by the browser natively, with scroll areas properly defined in css, it will just work.

Is there any docs for devs & contributors?
(how to set it up locally, etc.?)

**Comment by xet7** [comment]
@tborychowski 

For Mac:
https://github.com/wekan/wekan/wiki/Mac#build-bundle-from-source-and-develop-wekan

Usually I develop Wekan on Ubuntu 20.04 64bit (or Debian) with wekan repo cloned to at /home/wekan/repos/wekan,
I have not tested recently how well it works on a Mac.
That rebuild-wekan.sh script install node.js, npm, meteor and some packages.

https://github.com/wekan/wekan/wiki/Directory-Structure

https://github.com/wekan/wekan/wiki/Developer-Documentation

Wekan has Meteor packages from atmospherejs.com and npm packages from npmjs.com

Wekan has these scrollbars:
```
wekan-scrollbar
mquandalle:perfect-scrollbar
```

https://atmospherejs.com/mquandalle/perfect-scrollbar
https://github.com/mquandalle/meteor-perfect-scrollbar

And that wekan-scrollbar is at repo wekan/packages/wekan-scrollbar

https://github.com/wekan/wekan/blob/master/.meteor/packages#L85-L86
https://github.com/wekan/wekan/blob/master/.meteor/versions#L127
https://github.com/wekan/wekan/blob/master/.meteor/versions#L197

So in Wekan repo directory you type:
```
meteor remove wekan-scrollbar
meteor remove mquandalle:perfect-scrollbar
```
That will remove those from wekan/.meteor/packages and wekan/.meteor/versions

Then, in wekan repo directory you can write this to search for scrollbar code in non-generated directories:
```
./find.sh scrollbar
```
Npm packages form npmjs.com are at package.json and package-lock.json. Those can be changed with:
```
meteor npm install somepackage
meteor npm remove somepackage
```

Thanks!

**Comment by xet7** [comment]
With that `./find.sh scrollbar` there is for example these in clientside code. Those .styl files are stylus css template code https://stylus-lang.com , that is then converted to css. It's looks like CSS, and has some additional template features.
```
./client/components/lists/list.styl:  .ps-scrollbar-y-rail
./client/components/lists/listBody.jade:  .list-body.js-perfect-scrollbar
./client/components/lists/listBody.jade:  .list-body.js-perfect-scrollbar.search-card-results
./client/components/lists/listBody.js:    this.container = this.$(this.spinner).parents('.js-perfect-scrollbar')[0];
./client/components/main/popup.js:  // scrollbars. This happen for instance when the newly opened popup has some
./client/components/main/popup.styl:      &::-webkit-scrollbar-button
./client/components/mixins/perfectScrollbar.js:      const domElement = component.find('.js-perfect-scrollbar');
./client/components/cards/cardDetails.js:          scrollbarPosition: 'outside',
./client/components/cards/cardDetails.jade:  section.card-details.js-card-details.js-perfect-scrollbar: .card-details-canvas
./client/components/cards/cardDetails.styl:  .ps-scrollbar-y-rail
./client/components/boards/boardBody.jade:    .board-canvas.js-swimlanes.js-perfect-scrollbar(
./client/components/sidebar/sidebar.jade:      .sidebar-content.js-board-sidebar-content.js-perfect-scrollbar
./client/components/sidebar/sidebarSearches.jade:  .list-body.js-perfect-scrollbar
./client/lib/exportHTML.js:      document.querySelectorAll('.js-perfect-scrollbar > div:nth-of-type(n+2)'),
./client/lib/exportHTML.js:    Array.from(document.querySelectorAll('.js-perfect-scrollbar')).forEach(
./client/lib/exportHTML.js:        elem.classList.remove('js-perfect-scrollbar');
```

**Comment by tborychowski** [comment]
Thanks so much for that! I'll have a look as soon as I can :-)

**Comment by tborychowski** [comment]
So I followed the linked mac development setup and managed to set it up* and - funny thing - the issue is not there!
Scrollbars work as they should!
I don't know what's going on there.
This would not be caused by extensions (as I've also tested on a clean install of Firefox) and nothing with my docker setup, as this issue also happens in [other boards](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)...
I will keep investigating.

* one issue was this error:
```
Unable to resolve some modules:

  "@babel/runtime/helpers/objectSpread2" in /Users/i313281/Projects/wekan/client/lib/multiSelection.js (web.browser)
  "xss" in /Users/i313281/Projects/wekan/client/components/activities/activities.js (web.browser)
  "jszip" in /Users/i313281/Projects/wekan/client/lib/exportHTML.js (web.browser)
  "papaparse" in /Users/i313281/Projects/wekan/client/components/import/import.js (web.browser)
  "fibers/future" in /Users/i313281/Projects/wekan/models/users.js (web.browser)
  "fs" in /Users/i313281/Projects/wekan/sandstorm.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime xss jszip papaparse fibers meteor-node-stubs
```
but I run this command and it worked.

**Comment by tborychowski** [comment]
Anyways, I've created a PR which removes the custom scrollbar. I've tested it locally (as best I could) and it seems to work.

**Comment by xet7** [comment]
@tborychowski 

You did directly run meteor, so it just says those dependencies are not installed. In wekan repo directory you can run that command:
```
meteor npm install --save @babel/runtime xss jszip papaparse fibers meteor-node-stubs
```
So it will install those and error will go away. Those packages are:
- babel/runtime: compatibility with different browsers
- xss: xss protection on input fields
- jszip: used when exporting Wekan board to html files that are packed to .zip files
- papaparse: for csv import/export (currently I'm fixing csv export)
- fibers: for realtime changes
- meteor-node-stubs: dependenicies related to meteor

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3246

**Comment by tborychowski** [comment]
thank you!
just pulled image from `quay.io/wekan/wekan` and can confirm that it works as expected now.

**Comment by bkraul** [comment]
This change appears to introduce a styling issue.

This is the previous with custom scrollbar. Notice the close button is fully visible:

![image](https://user-images.githubusercontent.com/14616851/92684529-48c7fb00-f2fb-11ea-8e46-d2c47e12424e.png)

This is version 4.27 without custom scrollbar:

![image](https://user-images.githubusercontent.com/14616851/92684555-57aead80-f2fb-11ea-8c77-a432cecc4bbb.png)

As you can see, the close button is now partially blocked.

This was tested on Edge Chromium, Firefox and Chrome (latest versions), on Windows 10 Professional Version 2004.

**Comment by tborychowski** [comment]
Thanks, I'll have a look.

**Comment by tborychowski** [comment]
Hi @bkraul,
I've added ad PR that should fix the issue on Windows.

FYI, @xet7
