### ISSUE TITLE
Bad formating exporting to JSON

### ISSUE THREAD

**Issue by gusarg81** [wekan/wekan#3242]
Hi,

For testing purposes to see data structure of JSON exported file and analyze how I can import boards into Taiga, I saw that in some point the exported data has a Bad formatting.

I've checked this by using a JSON Formatter:

![wekan-json](https://user-images.githubusercontent.com/15545/91320270-00babb80-e7c6-11ea-9551-1083e5659163.png)

Currently using Wekan v4.23 (snap method).

**Comment by xet7** [comment]
I moved your screenshot from imgur to GitHub attachment. In future, please attach images directly to issues. Thanks!

**Comment by gusarg81** [comment]
> I moved your screenshot from imgur to GitHub attachment. In future, please attach images directly to issues. Thanks!

Yeah, sorry. I've forgot this.

**Comment by helioguardabaxo** [comment]
It's working fine on latest version:
![image](https://github.com/wekan/wekan/assets/24301085/c9a4877e-2a22-483e-a60b-ccb736c62a63)
