### ISSUE TITLE
Restarting Wekan Docker containers with mongo:4.4, use mongo:4.2 instead

### ISSUE THREAD

**Issue by GuidoDr** [wekan/wekan#3247]
## Issue
**Server Setup Information**:
Ubuntu 18.04.5 LTS
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
Wekan version: 4.24.0
Meteor version: 1.11
Node version: 12.18.3
MongoDB version: 4.2.9  (the problem is with the latest version 4.4.0)
MongoDB storage Engine: wiredTiger
MongoDB Oplog enabled

**Problem description**:

images in the docker-compose.yml are configured as:
image: wekanteam/wekan:latest
image: mongo:latest

but since Mongo introduced version 4.4 this ends up in an endless restarting loop of the containers. I had to change the mongo image inside the docker-compose.yml to "image: mongo:4.2" (which latest version is currently 4.2.9) in order to get wekan working again. It seems to be a problem with the WiredTiger engine

below the log of wekandb when it tries to start with the latest version (4.4.0):

docker-compose logs wekandb
Attaching to wekandb
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.759+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.798+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.798+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.798+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"4683cb5fdfcd"}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.798+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.0","gitVersion":"563487e100c4215e2dce98d0af2a6a5a2d67c5cf","openSSLVersion":"OpenSSL 1.1.1  11 Sep 2018","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu1804","distarch":"x86_64","target_arch":"x86_64"}}}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.798+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"18.04"}}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.798+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"},"replication":{"oplogSizeMB":128}}}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.817+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.818+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
wekandb    | {"t":{"$date":"2020-08-30T08:14:18.818+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=15546M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:19.330+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
wekandb    | {"t":{"$date":"2020-08-30T08:14:19.330+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"95: Operation not supported"}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:19.330+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":1100}}
wekandb    | {"t":{"$date":"2020-08-30T08:14:19.330+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}

And then it starts again and again ...

wekandb    | {"t":{"$date":"2020-08-30T08:14:23.679+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
wekandb    | {"t":{"$date":"2020-08-30T08:14:23.682+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
wekandb    | {"t":{"$date":"2020-08-30T08:14:23.682+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
wekandb    | {"t":{"$date":"2020-08-30T08:14:23.682+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"4683cb5fdfcd"}}
...

**Comment by gpalyu** [comment]
Just wanted to note that I am running mongo 4.4 but wekan 4.23 and everything is working correctly.

**Comment by xet7** [comment]
@gpalyu 

Thanks a lot for info!

@GuidoDr 

Do you have enough RAM at your server? Or is server swapping? See with:
```
free -h
```
Do you have enough free disk space?

Can you:
- [Backup](https://github.com/wekan/wekan/wiki/Backup)
- [Delete all Docker data](https://github.com/wekan/docker-cleanup-volumes) with start.sh
- Reinstall Wekan
- Restore Wekan data?

**Comment by GuidoDr** [comment]
sorry for the late answer, I am quite busy these days.

> Do you have enough RAM at your server? Or is server swapping? See with:

yes and it is not swapping 

              total        used        free      shared  buff/cache   available
Mem:            31G         12G        1.0G        749M         18G         18G
Swap:          7.6G         11M        7.6G

top - 21:30:31 up 21 days,  8:24,  1 user,  load average: 1.19, 1.15, 1.10
Tasks: 871 total,   1 running, 789 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.3 us,  0.7 sy,  0.0 ni, 96.9 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 32888060 total,  1010676 free, 12640572 used, 19236812 buff/cache
KiB Swap:  7999480 total,  7987292 free,    12188 used. 19272472 avail Mem

Your other steps I will try to do somewhere this week. 
I will first have to inform the users that Wekan will be offline for some time.

**Comment by brian-j** [comment]
I'm successfully running this configuration in a Synology NAS Docker environment:

Mongo 4.4.1  (from mongo:latest)
WeKan 4.50.0 (from wekanteam/wekan:latest)

**Comment by xet7** [comment]
@brian-j 

I updated newest Wekan and MongoDB to docker-compose.yml at https://github.com/wekan/wekan . Sorry Docker Hub buils are broken, only Quay works, it's updated to docker-compose.yml now.

**Comment by GuidoDr** [comment]
just for the records, the problem had been, that for whatever reason even though the database had been on 4.2.9 the featureCompatibilityVersion had still been 4.0 instead of 4.2 in the data.
After I did set it to 4.2 I could successfully upgrade to the 4.4 version
______________
from https://docs.mongodb.com/master/release-notes/4.4-upgrade-standalone/

Feature Compatibility Version

The 4.2 instance must have featureCompatibilityVersion set to "4.2". To check featureCompatibilityVersion:

db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )

The operation should return a result that includes "featureCompatibilityVersion" : { "version" : "4.2" }.

To set or update featureCompatibilityVersion, run the following command:

db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )
