### ISSUE TITLE
Height of page does not adjust when using zoom on Safari

### ISSUE THREAD

**Issue by PrestonL** [wekan/wekan#325]
Height of page stays static when using Zoom on Safari to make elements on page smaller / larger.  Width adjusts just fine.  Page height will adjust when changing window size, but will have a large empty space at the bottom when zoomed out, and overflow when zoomed in.

**Comment by PrestonL** [comment]
<img width="1298" alt="screen shot 2015-09-24 at 11 51 52 am" src="https://cloud.githubusercontent.com/assets/4715059/10079991/bc453626-62b2-11e5-8421-3055dd7cc94d.png">
Screenshot of issue in action

**Comment by mquandalle** [comment]
What version of Safari is that? (I don't have Mac to test that, I will need to ask someone)

**Comment by PrestonL** [comment]
Safari Version 8.0.8 (10600.8.9)

I am currently working to see if it does it on Safari for Windows as well.

**Comment by PrestonL** [comment]
Just realized that Safari for Windows doesn't exist anymore and am unable to replicate in Edge / Chrome / Firefox.
