### ISSUE TITLE
Feature Request: Select a local image to be used as the board background

### ISSUE THREAD

**Issue by vikuto** [wekan/wekan#3255]
## Feature Request: Change board background to local image

I've noticed the lack of customization of board backgrounds since it can't be chosen any image as the background, only background colors. So I decided to create this issue for this feature request with the hope to solve this problem.

An image sample of what should be like (just an example): https://imgbox.com/N8PFUqHC

**Comment by vikuto** [comment]
Local machine => user machine directories

**Comment by xet7** [comment]
Moved to #486
