### ISSUE TITLE
How do I import a customized CSS Theme into the Wekan local files?

### ISSUE THREAD

**Issue by vikuto** [wekan/wekan#3258]
How do I customize my local wekan instance by importing a customized CSS Theme? I didn't found instructions of how-to in the wiki.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Custom-CSS-themes

There at beginning of page is this:

All Wekan themes are directly integrated to Wekan. You can add pull request to master branch to add custom theme, you can see from [from this commit](https://github.com/wekan/wekan/commit/34b2168d0dda253dedabbee47031873efa4ae446) required new color/theme name and changes to these files 3 files listed below. In that commit is also changes to other files, you don't need to change those files.
  - `wekan/client/components/boards/boardColors.styl`
  - `wekan/models/boards.js`
  - `wekan/server/migrations.js`

**Comment by Jofemago** [comment]
Hii

I can change the main color that I see when I log in to my Wekan server with the snap installation, this method you propose is for the colors of the board as I understand, but I want to change the blue in the main view, can I do it somehow? I have been looking and I have not been able to, I have no problem with using another installation method other than snap but it is imperative to be able to change these colors, thanks.

**Comment by xet7** [comment]
@Jofemago 

By sending pull request to https://github.com/wekan/wekan/pulls , with code that implements that feature. Existing change color code is in this same repo https://github.com/wekan/wekan and docs at https://github.com/wekan/wekan/wiki . For previous questions about how to change code etc, please seach current open and closed issues. Thanks!
