### ISSUE TITLE
MongoNetworkError: failed to connect to server [wekandb:27017] on first connect

### ISSUE THREAD

**Issue by WeiSong84** [wekan/wekan#3263]
## Issue
Install Step:
1. docker.compose.version  1.26.2
2. install step:
  a. git clone https://github.com/wekan/wekan
  b. cd wekan
  c. docker-compose up -d
3. then I found mongo db  OK
4. but wekan app logs as below:
MongoNetworkError: failed to connect to server [wekandb:27017] on first connect [Error: connect EHOSTUNREACH 172.18.0.2:27017

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {

  name: 'MongoNetworkError'

**Comment by WeiSong84** [comment]
I used snap install method ,ok;
But I used docker install method,error is still.

**Comment by xet7** [comment]
@WeiSong84 

Do you have something else running on these ports already? So Docker can not start Wekan and MongoDB ?
- port 80 https://github.com/wekan/wekan/blob/master/docker-compose.yml#L151
- port 27017 https://github.com/wekan/wekan/blob/master/docker-compose.yml#L153

**Comment by xet7** [comment]
If those are not free, you should change them to other ports. For example Wekan Node.js:
```
- 5000:8080
```

**Comment by brandonsturgeon** [comment]
I have actual mongodb running on this same machine supporting other services, so I can't use the default 27017.

When I try changing these ports in the docker compose file, I still get this error
```
MongoNetworkError: failed to connect to server [wekandb:<myport>] on first connect [Error: connect EHOSTUNREACH 172.18.0.2:27017
```

and when I start only `wekan-db`, then run `docker ps` I see this:
```
a13466fd735b        mongo:4.2                  "docker-entrypoint.s…"   4 minutes ago       Up Less than a second   27017/tcp, <myport>/tcp            wekan-db
```

so it's still doing _something_ with 27017? Why?

I changed all of the config variables in the `docker-compose.yml` but still experience this issue. Please advise!

**Comment by xet7** [comment]
@brandonsturgeon 

Did you remove MongoDB container? https://github.com/wekan/wekan/blob/master/docker-compose.yml#L92-L112

And set MONGO_URL to some server IP address? https://github.com/wekan/wekan/blob/master/docker-compose.yml#L153

For Wekan inside Docker, localhost for wekan-app container is inside that container. Accessing to your actual server localhost is kind of accessing to outside. It could depend on firewall rules or exposed ports, but please do not expose MongoDB directly to Internet available for anyone.

It could be easier to run Wekan source bundle version with just newest Node.js 12.x LTS with start-wekan.sh, systemd or similar:
https://github.com/wekan/wekan/wiki/Raspberry-Pi (same page is about bundle for any x64/arm64/s390x server)

That way container networking would not complicate that setup.

**Comment by WeiSong84** [comment]
I found the reason,I used CentOS 7 and docker ,it is all OK.
But used CentOS 8 and docker, this error occurred again.
So I don't know why.

**Comment by xet7** [comment]
@WeiSong84 

For my own servers, I use Wekan Snap on newest Ubuntu, that has always worked for me. I don't use CentOS or Docker.
