### ISSUE TITLE
Historical cards display

### ISSUE THREAD

**Issue by iberlob** [wekan/wekan#3266]
a query

we have a long history in time and we do not see all the notes on the cards
We can't see notes from for example two months ago
Is any filter applied? Is it possible to view the entire list of notes?

Thank you

**Comment by xet7** [comment]
Those are at database, you can see them with nosqlbooster GUI, for example by connecting in nosqlbooster GUI to via SSH to server localhost port 27019 where Wekan Snap MongoDB database it.

I try to fix bug #2934 soon so those would be visible directly on card.
