### ISSUE TITLE
cfs:gridfs deprecated

### ISSUE THREAD

**Issue by blaggacao** [wekan/wekan#3272]
## Issue

https://atmospherejs.com/cfs/gridfs

this blocks #3262 since because of an old mongodb version used as transitive dependency, it's impossible to connect to a remote mongo service (using some supported auth mecanism)

Despite #3270 

What can we do?

In fact it looks like none of the `cfs`'s packages is maintained any longer: https://atmospherejs.com/cfs

Affecting:

- https://github.com/wekan/wekan/blob/5870d38e8e63159ede8c18d1766a4f9f6ba8987c/.meteor/packages#L20
- https://github.com/wekan/wekan/blob/5870d38e8e63159ede8c18d1766a4f9f6ba8987c/.meteor/packages#L79
- https://github.com/wekan/wekan/blob/5870d38e8e63159ede8c18d1766a4f9f6ba8987c/.meteor/packages#L97

**Comment by xet7** [comment]
@blaggacao 

Do you mean connecting to some specific remove MongoDB version?

**Comment by xet7** [comment]
Do you mean this? #2977

**Comment by blaggacao** [comment]
Maybe drop all those unmaintained packages and implement:

- https://github.com/VeliovGroup/Meteor-Files
- https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration -> https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Bucket-Integration

@xet7 With a little guidance, I might give it a try?

> Do you mean connecting to some specific remote MongoDB version?

Yes  it's mongo 4.2.6 &mdash; I'm using the mongodb operator which _only_ supports SCRAM - which is _only_ SCARM-SHA256 in case of 4.2.6.

**Comment by blaggacao** [comment]
> Do you mean this? #2977

> Wekan never connect to mongodb saying member of replicaset can't be found

I had this error, but it seemed it was a mis-configuration in the URI, the persistant error (which might also be behind that reported issue) is that the auth methods don't match.

**Comment by xet7** [comment]
Is Meteor-Files same or different than ostrio-files? https://github.com/wekan/wekan/pull/3268#issuecomment-691030970

**Comment by blaggacao** [comment]
> Is Meteor-Files same or different than ostrio-files? #3268 (comment)

[It is the same!](https://github.com/VeliovGroup/Meteor-Files#installation) Thanks for the link &mdash; I didn't associate with your comment.

**Comment by xet7** [comment]
That ostrio-files changes are not merged yet, because those did not build yet on arm64 and s390x. But maybe that could be made working some way too.

**Comment by xet7** [comment]
@urakagi and @blaggacao could look together how to get those ostrio-files changes as pull request to newest Wekan

**Comment by blaggacao** [comment]
So you did do some work on https://github.com/wekan/wekan/tree/feature-ostrio-files &mdash; then you stopped because it didn't build &mdash; now it needs rebasing + fixing those build? +- right?

**Comment by blaggacao** [comment]
`feature-ostrio-files` seems not to have any extra commits compared to master. Did I miss something?

**Comment by blaggacao** [comment]
Ok, I'll hgive it a try to refactor the use of legacy packages towards `ostrio:files` & and gridfs-stream` towards https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Bucket-Integration

**Comment by xet7** [comment]
@blaggacao 

Those by urakagi 

https://github.com/wekan/wekan/commits/feature-ostrio-files?after=23dcd084a49de4e6568527d8f97ed25adb04dafd+34&branch=feature-ostrio-files

https://github.com/wekan/wekan/commits/feature-ostrio-files?after=23dcd084a49de4e6568527d8f97ed25adb04dafd+69&branch=feature-ostrio-files

https://github.com/wekan/wekan/commits/feature-ostrio-files?after=23dcd084a49de4e6568527d8f97ed25adb04dafd+104&branch=feature-ostrio-files

**Comment by xet7** [comment]
And some could be at https://github.com/wekan/wekan/pull/3217

**Comment by xet7** [comment]
Idea being, that migrating files from database to files or elsewhere, without overwriting duplicate files names, could somehow be made possible.

**Comment by blaggacao** [comment]
Ok As far as I can judge and see some work is also in master:

https://github.com/wekan/wekan/commit/0a1bfd37b3b1b2f4108a734c0449c1bd5a1b691f

Inline with https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Bucket-Integration

Some work not directly related with this change is pending in #3212 

Currently there are no commits in `feature-ostrio-files` which are not also currently in `master`. BUt master does not import `ostrio:files` &mdash; so this is where the delta lays.

**Comment by xet7** [comment]
Wow, that wiki page starts with `1. Create a GridFSBucket factory`. Seems that some Java people coded that...

**Comment by blaggacao** [comment]
So this is from where it should start: https://github.com/wekan/wekan/pull/3273/files

**Comment by blaggacao** [comment]
@xet7 might I disregard all ocurrences in `fix-download-unicode/cfs_access-point.txt`? &mdash; see: https://github.com/wekan/wekan/pull/3273#issue-486236976

**Comment by xet7** [comment]
@blaggacao 

You can delete that directory `fix-download-unicode` and all related code. It was old fix #784 and it does not work anymore with newest Meteor.

**Comment by blaggacao** [comment]
@xet7 It looks like `FS.File` is just a conventional file handle. Should they become collections?

```
models/trelloCreator.js:          const file = new FS.File();
models/wekanCreator.js:          const file = new FS.File();
client/lib/utils.js:    const file = new FS.File(fileObj)
client/components/cards/attachments.js:      const file = new FS.File(results.file);
```

**Comment by blaggacao** [comment]
Are ES6 Imports ok?

**Comment by xet7** [comment]
About ES6, I think so ? https://github.com/wekan/wekan/blob/master/.eslintrc.json#L9

**Comment by xet7** [comment]
Currently attachments are stored in database, and most have automated database backups

**Comment by blaggacao** [comment]
> Currently attachments are stored in database, and most have automated database backups

So all file handels should become `MongoInternals.NpmModule.GridFSBucket`. Sounds easy to do :+1:

**Comment by xet7** [comment]
But in your code do not use Javascript arrow functions, because Python-based API documentation generation code does not like those arrow functions code.

**Comment by xet7** [comment]
Well, if there is Javascript arrow function, then Python code does not show any error, and just leaves out generating some part of documentation at https://wekan.github.io/api/

**Comment by blaggacao** [comment]
> Well, if there is Javascript arrow function, then Python code does not show any error,

Even better those factory and generator functions do not need to be exposed, I'll stow them away in a helper file in `client/*.js :+1: &mdash; less work, safer result

**Comment by xet7** [comment]
For serverside code, you could add check `isServer`. For clientside, isClient. Otherwise, code runs at both serverside and clientside.
https://github.com/wekan/wekan/blob/master/server/statistics.js#L3

Checking for logged in user with `Meteor.user()` and user being Admin `Meteor.user().isAdmin)
https://github.com/wekan/wekan/blob/master/server/statistics.js#L6

**Comment by xet7** [comment]
Other roles like `isWorker` etc listed here https://github.com/wekan/wekan/wiki/REST-API-Role

**Comment by blaggacao** [comment]
> Will initiate download, if links are called with ?download="true" queryparam

Is this a problem? Can we refactor? It seems very clean + global solution.

**Comment by xet7** [comment]
@blaggacao 

Hmm? Well, for example JSON etc exported links need to downloaded. You can try does it work.

**Comment by xet7** [comment]
Also there are download links for attachments at cards. Directly clicking some attached bitmap image starts slideshow.

**Comment by xet7** [comment]
But I have not yet figured out how to view PDF files in slideshow #1318

**Comment by blaggacao** [comment]
Since I commented out console logs, there is an eslint warning in https://github.com/wekan/wekan/pull/3273/commits/4158b29a897415200a5425e12df29e58f9c550b9

```console
/home/blaggacao/ghq/github.com/wekan/wekan/models/lib/fsHooks/createAfterUpdate.js
28:22  warning  'err' is defined but never used  no-unused-vars

/home/blaggacao/ghq/github.com/wekan/wekan/models/lib/fsHooks/createOnAfterRemove.js
11:32  warning  'err' is defined but never used                           no-unused-vars
```

Should those `err` buble up somewhere/how? or is it ok to ignore?

**Comment by xet7** [comment]
Warnings do not prevent building Wekan. Only errors prevent building.

**Comment by blaggacao** [comment]
[Docs](https://docs.meteor.com/api/collections.html#Mongo-Collection-allow) suggest:
```
  remove(userId, doc) {
    // Can only remove your own documents.
    return doc.owner === userId;  # sic doc.owner!
  },

```

But for example avatars:
```
Avatars.files.before.insert((userId, doc) => {
  doc.userId = userId;
});
```

***Is `doc.owner` not available?***

**Comment by xet7** [comment]
Hmm, I don't know is owner available to normal users.

About allow/deny:
https://github.com/wekan/wekan/commit/ba24c4e40c728d030504ed21ccf79247d0449e1b

**Comment by xet7** [comment]
I would think, that you'll just try what does and does not work.

**Comment by xet7** [comment]
BTW, for example when I added feature [Assignee field like Jira](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v350-2019-11-13-wekan-release), there this way I did [prevent more than one assignee](https://github.com/wekan/wekan/commit/1728298659521ee8e6fc94fedad3160030b9a2c3).

**Comment by blaggacao** [comment]
Can local fs storage support be dropped? What is it good for? Would some follow up export from gridfs solve the use case?

**Comment by xet7** [comment]
I think currently local fs storage does not work well enough. There is settings for it, but it depends does link to file really point to database or filesystem, is everything visible:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L239

**Comment by blaggacao** [comment]
There is however `storagePath?: string | ((fileObj: FileObj<MetadataType>) => string);` in https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/typescript-definitions.md  and https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration exemplifies as:

```
  const UserFiles = new FilesCollection({
    debug: false, // Change to `true` for debugging
    storagePath: 'assets/app/uploads/uploadedFiles',
...
```

I'll drop it in the meantime, but maybe once `ostorio:files` is working, it should be relatively easy to add back.

**Comment by xet7** [comment]
If files are moved outside of database, then it's about how well linking to those files really works? Do those files have one-time view keys, are they at intranet, require Google login, or something else? Because private board attachments are not currently visible to non-logged in users, and it should still be that way.

**Comment by blaggacao** [comment]
> If files are moved outside of database, then it's about how well linking to those files really works? Do those files have one-time view keys, are they at intranet, require Google login, or something else? Because private board attachments are not currently visible to non-logged in users, and it should still be that way.

For such use cases https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration seems like the right answer.

**Comment by xet7** [comment]
Yes. Currently it's first that with ostrio-files using attachments at database does still work, and then see does using ostrio-files solve your using remote database issue.

**Comment by blaggacao** [comment]
Why is file type not preserved on attachments?

```
    if (!fileObj.isImage()) {
      return {
        type: 'application/octet-stream',
      };
    }
```

Wouldn't it make more sense to preserve metadata?

**Comment by xet7** [comment]
Yes.

**Comment by xet7** [comment]
Currently problem is, that PDF files open also in slideshow, but then show nothing, because there is no PDF viewer setup.

Slideshow only shows JPG/JPEG/PNG/GIF bitmap image files, other file types should be excluded from slideshow, when those filetypes do not work.

**Comment by blaggacao** [comment]
> Slideshow only shows JPG/JPEG/PNG/GIF bitmap image files, other file types should be excluded from slideshow, when those filetypes do not have a viewer that would work.

Sounds like a fix is appropriate over there at the slideshow implementation. We should take note to open a follow-up issue on this aspect of the refactoring.

**Comment by xet7** [comment]
That AWS S3 integration seems to have some image processing Lambda possibilities for creating thumbnails:
https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration#further-image-jpeg-png-processing-with-aws-lambda

Currently Wekan has some image resize code:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L248-L253

But currently that is optional, so all boards do load big images from big boards to browser and that slows down Wekan, because Wekan does not have thumbnails in general use.

**Comment by blaggacao** [comment]
**Problem:**

> These checks are run only when a client tries to write to the database directly, for example by calling update from inside an event handler. Server code is trusted and isn’t subject to allow and deny restrictions. That includes methods that are called with Meteor.call — they are expected to do their own access checking rather than relying on allow and deny.

 It looks like the new implementation of allow / deny is without effects on on server side _callers_, was this the case before, too?

**Comment by blaggacao** [comment]
`_ensureIndex` &rarr; [is deprecated](https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/)

<details>
<summary>Occurrances</summary>

```
models/triggers.js:    Triggers._collection._ensureIndex({ modifiedAt: -1 });
models/rules.js:    Rules._collection._ensureIndex({ modifiedAt: -1 });
models/invitationCodes.js:    InvitationCodes._collection._ensureIndex({ modifiedAt: -1 });
models/cardComments.js:    CardComments._collection._ensureIndex({ modifiedAt: -1 });
models/cardComments.js:    CardComments._collection._ensureIndex({ cardId: 1, createdAt: -1 });
models/attachments.js:    Attachments.files._ensureIndex({ cardId: 1 });
models/customFields.js:    CustomFields._collection._ensureIndex({ modifiedAt: -1 });
models/customFields.js:    CustomFields._collection._ensureIndex({ boardIds: 1 });
models/actions.js:    Actions._collection._ensureIndex({ modifiedAt: -1 });
models/swimlanes.js:    Swimlanes._collection._ensureIndex({ modifiedAt: -1 });
models/swimlanes.js:    Swimlanes._collection._ensureIndex({ boardId: 1 });
models/accountSettings.js:    AccountSettings._collection._ensureIndex({ modifiedAt: -1 });
models/checklistItems.js:    ChecklistItems._collection._ensureIndex({ modifiedAt: -1 });
models/checklistItems.js:    ChecklistItems._collection._ensureIndex({ checklistId: 1 });
models/checklistItems.js:    ChecklistItems._collection._ensureIndex({ cardId: 1 });
models/lists.js:    Lists._collection._ensureIndex({ modifiedAt: -1 });
models/lists.js:    Lists._collection._ensureIndex({ boardId: 1 });
models/orgUser.js:    OrgUser._collection._ensureIndex({ orgId: -1 });
models/orgUser.js:    OrgUser._collection._ensureIndex({ orgId: -1, userId: -1 });
models/cards.js:    Cards._collection._ensureIndex({ modifiedAt: -1 });
models/cards.js:    Cards._collection._ensureIndex({ boardId: 1, createdAt: -1 });
models/cards.js:    Cards._collection._ensureIndex({ parentId: 1 });
models/users.js:      Lists._collection._ensureIndex(value);
models/users.js:    Users._collection._ensureIndex({ modifiedAt: -1 });
models/users.js:    Users._collection._ensureIndex(
models/integrations.js:    Integrations._collection._ensureIndex({ modifiedAt: -1 });
models/integrations.js:    Integrations._collection._ensureIndex({ boardId: 1 });
models/org.js:    Org._collection._ensureIndex({ name: -1 });
models/announcements.js:    Announcements._collection._ensureIndex({ modifiedAt: -1 });
models/settings.js:    Settings._collection._ensureIndex({ modifiedAt: -1 });
models/boards.js:    Boards._collection._ensureIndex({ modifiedAt: -1 });
models/boards.js:    Boards._collection._ensureIndex(
models/boards.js:    Boards._collection._ensureIndex({ 'members.userId': 1 });
models/activities.js:    Activities._collection._ensureIndex({ createdAt: -1 });
models/activities.js:    Activities._collection._ensureIndex({ modifiedAt: -1 });
models/activities.js:    Activities._collection._ensureIndex({ cardId: 1, createdAt: -1 });
models/activities.js:    Activities._collection._ensureIndex({ boardId: 1, createdAt: -1 });
models/activities.js:    Activities._collection._ensureIndex(
models/activities.js:    Activities._collection._ensureIndex(
models/activities.js:    Activities._collection._ensureIndex(
models/checklists.js:    Checklists._collection._ensureIndex({ modifiedAt: -1 });
models/checklists.js:    Checklists._collection._ensureIndex({ cardId: 1, createdAt: 1 });
models/unsavedEdits.js:    UnsavedEditCollection._collection._ensureIndex({ modifiedAt: -1 });
models/unsavedEdits.js:    UnsavedEditCollection._collection._ensureIndex({ userId: 1 });

```

</summary>
</details>

**Comment by blaggacao** [comment]
@xet7 After kind of figuring out how this is supposed to work (took quite some time), I didn't find where to which object the `url()` method was attached in the previous code:

https://github.com/wekan/wekan/pull/3273/commits/e4c28c39b989d29e18b73246e61f777c5191d28e#diff-e37acd9674ee4d6c1221038429907195R107-R108

What was `file.url()` before?

**Comment by xet7** [comment]
@blaggacao 

Avatars are uploaded to database at Wekan user settings:

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/models/avatars.js#L2

**Comment by xet7** [comment]
UserAvatar form here https://github.com/wekan/wekan/tree/master/client/components/users

**Comment by xet7** [comment]
In future, avatar can also be link to avatar image elsewhere, like at LDAP, Google Auth, Gravatar etc with image URL that is get in response to login to some auth system. In general, avatar URL points to database or elsewhere.

**Comment by blaggacao** [comment]
The PR is +- reviewable, now. I'm going to bed, now. Hope to catch up tomorrow with your comments. Thanks for this guidance. Felt like peer programming! Super nice!

**Comment by xet7** [comment]
@blaggacao 

Thanks :+1: I just woke up :coffee:

**Comment by xet7** [comment]
Well that deepcode sometime suggested Javascript arrow functions so it is not always right.

**Comment by razum2um** [comment]
just 2cents reg. "image processing Lambda possibilities for creating thumbnails": maybe approach with smart "resize-on-pull" proxy is the way to go, what do you think?

i.e. just adding settings-url like here: https://docs.mattermost.com/administration/image-proxy.html

**Comment by xet7** [comment]
@razum2um 

Wekan already has some code to make thumbnails. Wekan is used at private LANs that are not connected to Internet, so it's not possible to use Lambda there. Also, I think there is no need for separate proxy.
