### ISSUE TITLE
Wekan OAUTH2 keycloak  problem

### ISSUE THREAD

**Issue by skyox** [wekan/wekan#3277]
## Issue

I configure the SSO  according to the manual [ wiki Keycloak](https://github.com/wekan/wekan/wiki/Keycloak) , but I have some problems.

**Server Setup Information**:

* Docker image Form:  https://hub.docker.com/r/wekanteam/wekan/
* Wekan version:  4.32.0 ( wekanteam/wekan:v4.32)
* Node Version:  12.18.3
*  Oauth & keycloak config:
```
OAUTH2_ENABLED=true
OAUTH2_LOGIN_STYLE=redirect
OAUTH2_CLIENT_ID=wekan_client
OAUTH2_SECRET=a0b6aeff-cd9b-4d39-9e0f-428252ab682f
OAUTH2_SERVER_URL=http://keycloak.mycom:8080/auth
OAUTH2_AUTH_ENDPOINT=/realms/appstore/protocol/openid-connect/auth
OAUTH2_USERINFO_ENDPOINT=/realms/appstore/protocol/openid-connect/userinfo
OAUTH2_TOKEN_ENDPOINT=/realms/appstore/protocol/openid-connect/token
OAUTH2_FULLNAME_MAP=given_name
OAUTH2_REQUEST_PERMISSIONS=openid profile email
OAUTH2_USERNAME_MAP=preferred_username
OAUTH2_ID_MAP=preferred_username
```

**Problem description**:

When  Click Sign In with Oidc,  will open a new windows with URL（keyclock return `An internal server error has occurred`）
```
http://keycloak.mycom:8080/auth/realms/appstore/protocol/openid-connect/auth?loginStyle=popup&client_id=gitea&response_type=code&redirect_uri=http%3A%2F%2F%20http%3A%2F%2Fwekan-test.appstoredev%2F_oauth%2Foidc&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJRR1JUNm1oMHJseGFtREQ1bXluOEdYV1NQbFh3VEhiOW9GYm5rSGNoRU9NIiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D&scope=openid%20profile%20email
```
I find there are two point is incorrect in the URL 
- `loginStyle=popup` 
    Is this should be `redirect` ?
- `redirect_uri=http%3A%2F%2F%20http%3A%2F%2Fwekan-test.appstoredev` is     `redirect_uri= http:// http://wekan-test.appstoredev`   
   This shouldn't be an extra `http:// `

Can any one help me,Thanks ?

**Comment by phaseshift3r** [comment]
If you enable Debug logs and look at them when connecting what does they say? Regarding the claims

I tested with wekan after following 

https://docs.rocket.chat/guides/administrator-guides/authentication/open-id-connect/keycloak

And got it to work. That double http in uri i didnt get that,

**Comment by skyox** [comment]
@phaseshift3r 
Thanks for reply, I reconfigured keycloak and wekan,login   it works now。

```
- OAUTH2_ENABLED=true
- OAUTH2_LOGIN_STYLE=redirect
- OAUTH2_CLIENT_ID=wekan_client
- OAUTH2_SECRET=a0b6aeff-cd9b-4d39-9e0f-428252ab682f
- OAUTH2_SERVER_URL=http://keycloak.mycom:8080/auth
- OAUTH2_AUTH_ENDPOINT=/realms/appstore/protocol/openid-connect/auth
- OAUTH2_USERINFO_ENDPOINT=/realms/appstore/protocol/openid-connect/userinfo
- OAUTH2_TOKEN_ENDPOINT=/realms/appstore/protocol/openid-connect/token
- OAUTH2_FULLNAME_MAP=name
- OAUTH2_REQUEST_PERMISSIONS=openid profile email
- OAUTH2_USERNAME_MAP=preferred_username
- OAUTH2_ID_MAP=preferred_username
- OAUTH2_EMAIL_MAP=email
```
But `OAUTH2_LOGIN_STYLE=redirect` does not seem to work

Finally, thank you very much for taking your time

**Comment by phaseshift3r** [comment]
@skyox nice you got it working, i was possitivly surpriced of keyclock my self.

**Comment by Blaumilch** [comment]
> @phaseshift3r Thanks for reply, I reconfigured keycloak and wekan,login it works now。
> 
> ```
> - OAUTH2_ENABLED=true
> - OAUTH2_LOGIN_STYLE=redirect
> - OAUTH2_CLIENT_ID=wekan_client
> - OAUTH2_SECRET=a0b6aeff-cd9b-4d39-9e0f-428252ab682f
> - OAUTH2_SERVER_URL=http://keycloak.mycom:8080/auth
> - OAUTH2_AUTH_ENDPOINT=/realms/appstore/protocol/openid-connect/auth
> - OAUTH2_USERINFO_ENDPOINT=/realms/appstore/protocol/openid-connect/userinfo
> - OAUTH2_TOKEN_ENDPOINT=/realms/appstore/protocol/openid-connect/token
> - OAUTH2_FULLNAME_MAP=name
> - OAUTH2_REQUEST_PERMISSIONS=openid profile email
> - OAUTH2_USERNAME_MAP=preferred_username
> - OAUTH2_ID_MAP=preferred_username
> - OAUTH2_EMAIL_MAP=email
> ```
> 
> But `OAUTH2_LOGIN_STYLE=redirect` does not seem to work
> 
> Finally, thank you very much for taking your time

Hello, could you tell me how you configured keycloak? I seem to have problems with setting the redirect_uri correctly. Help would be greatly appreciated.

**Comment by Blaumilch** [comment]
> @phaseshift3r Thanks for reply, I reconfigured keycloak and wekan,login it works now。
> 
> - OAUTH2_ENABLED=true
> - OAUTH2_LOGIN_STYLE=redirect
> - OAUTH2_CLIENT_ID=wekan_client
> - OAUTH2_SECRET=a0b6aeff-cd9b-4d39-9e0f-428252ab682f
> - OAUTH2_SERVER_URL=http://keycloak.mycom:8080/auth
> - OAUTH2_AUTH_ENDPOINT=/realms/appstore/protocol/openid-connect/auth
> - OAUTH2_USERINFO_ENDPOINT=/realms/appstore/protocol/openid-connect/userinfo
> - OAUTH2_TOKEN_ENDPOINT=/realms/appstore/protocol/openid-connect/token
> - OAUTH2_FULLNAME_MAP=name
> - OAUTH2_REQUEST_PERMISSIONS=openid profile email
> - OAUTH2_USERNAME_MAP=preferred_username
> - OAUTH2_ID_MAP=preferred_username
> - OAUTH2_EMAIL_MAP=email
> But OAUTH2_LOGIN_STYLE=redirect does not seem to work
> 
> Finally, thank you very much for taking your time

Hello @phaseshift3r , could you tell me how you configured keycloak? I seem to have problems with setting the redirect_uri correctly. Help would be greatly appreciated.
