### ISSUE TITLE
[Feature-request] Background color for lists

### ISSUE THREAD

**Issue by ssimono** [wekan/wekan#328]
I would like to change the background color of my columns. this way I could have some kind of categories for the lists.

For example I could have a yellow list which is my backlog and then 3 blue lists which are the planned sprints ahead, even with different depths of blue :smile: 

The cool things with color is that it is a soft setting and allow several approches for grouping or highlighting lists

**Comment by jonathan-chin** [comment]
+1 I would love this as well!

**Comment by DeGroote99** [comment]
I have requested this feature, instead of the entire section being colored, just the list name in a colored box. much cleaner look
