### ISSUE TITLE
Watch boards by default

### ISSUE THREAD

**Issue by AuspeXeu** [wekan/wekan#3282]
Is there a setting where I can configure that boards are watched by default instead of being muted?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L258-L274

For Snap:
```
sudo snap set wekan bigevents-pattern=due
```
Removing that setting, so it's back to default none:
```
sudo snap unset wekan bigevents-pattern
```

**Comment by saschafoerster** [comment]
I think it is not really the same: 
BIGEVENTS =  broadcast to all members of the board who are watching. AND especially can't be turned off or controlled by users board by board. 

@AuspeXeu Maybe you can look in the code to see, where the option sits and then chose another default for wekan? I would also think that "watching" should be default everywhere. Maybe some others can also tell, what they think should be default and why?

**Comment by xet7** [comment]
When that BIGEVENTS enabled was default in Wekan, there were new issues creating about Wekan sending too much email.

I don't think I would change defaults. If someone would like to enable watching for everyone, that would be separate setting to click at Admin Panel, I think.

I don't know is email notifications the correct way to notify.

@jtbairdsr How does `Notification drawer like Trello` feature https://github.com/wekan/wekan/pull/2975 work? For example, if someone is tagged with `@username`, it maybe should add notification to that user? That [clicking `@username` code](https://github.com/wekan/wekan/blob/master/client/components/main/editor.js#L304-L309) is currently changed to underline, because clicking it did open Wekan in new tab. Should that open user details popup or something else? Are due notifications added to notification drawer, does it work?

**Comment by xet7** [comment]
Problem with email is, if someone would get about 200 email notifications, it's just too much.

**Comment by xet7** [comment]
Sometime there was feature request about combining multiple notifications into one email. I did not yet find where that feature request is.

**Comment by AuspeXeu** [comment]
I think there are two things to consider here.

1. It would be great if this could be set in the admin panel
2. It would be super valuable if instead of having individual email notifications, one could set a time period, e.g. 2h, during which notifications get buffered and then only a summary is sent out

What do you guys think?

**Comment by saschafoerster** [comment]
@AuspeXeu I agree with both! :) 👍

**Comment by jtbairdsr** [comment]
@xet7

The notification board is pretty simple… when an activity is created, if that activity will notify the user (i.e. send them an email) it creates a record in the notifications array on the user record that captures the id of that activity record… we also capture a timestamp when the notification is read and then we periodically remove all notifications that have been read from the array… that is about all there is to it.  It is unaware of due notifications and it displays notifications the same way that activity is displayed in the activity logs (for cards and boards).  There isn’t anymore to it than that.

**Comment by AuspeXeu** [comment]
@jtbairdsr this is to implement the bulk email notifications?

**Comment by AuspeXeu** [comment]
Is there a way to only have the wekan board notifications and not receive emails?

**Comment by xet7** [comment]
@AuspeXeu 

If you remove email configuration, you don't get any emails.

Currently there is many kinds of notifications in Wekan.
For example:
- Muted/Watching/Tracking for per-user email notifications
- Bigevents etc various settings:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L253-L291
- Notification drawer like Trello
https://github.com/wekan/wekan/issues/2471

But there is not yet:
- Push Notification, and notifications area with settings
https://github.com/wekan/wekan/issues/2026
- Scheduled Rules https://github.com/wekan/wekan/issues/2476
- Combine Rules https://github.com/wekan/wekan/issues/2953
- Email Templates https://github.com/wekan/wekan/issues/2022
- Email grouping https://github.com/wekan/wekan/issues/1817
- Notifications only work when watching whole board - you can't watch
only specific lists or cards https://github.com/wekan/wekan/issues/1005

**Comment by ryanMushy** [comment]
We found in the source code a very easy way to force all users to "track" a board. This setting should be made configurable using the start-wekan file

![Screenshot_20210331-073214](https://user-images.githubusercontent.com/77740971/113161496-4a9fd000-91f3-11eb-93a8-2cd6115079b4.png)

**Comment by benjaminhrivera** [comment]
@xet7 unfortunately changing muted to tracking does not work, it causes notifications to not work when tracking, but will work when watching. Would you know why this is?

**Comment by xet7** [comment]
Sometime in future Notifications Settings will be implemented.

Moved to #2026
