### ISSUE TITLE
Impersonate one user. #3280 is not logged or auditable

### ISSUE THREAD

**Issue by meerkampdvv** [wekan/wekan#3284]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version:  4.40.0
* If this is about old version of Wekan, what upgrade problem you have?: no
* Operating System: Centos 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): treafik
* Node Version: 12.18.4 
* MongoDB Version: 4.2.2
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome 85.0.4183.83

**Problem description**:
Since versions v4.39 which added Impersonate one user. #3280 it is Possible to impersonate any Users without any trace of it. This creates quite some Privacy, Security and Audit concerns. 
Please add a a possibility of Notification for the User and/or a log entry for this feature.

**Comment by xet7** [comment]
@meerkampdvv 

That feature would cost 1000 euro. Payment at https://wekan.team/commercial-support/
