### ISSUE TITLE
How to status color cart carry over in right?

### ISSUE THREAD

**Issue by 1adena** [wekan/wekan#3285]
![4ff31-clip-7kb](https://user-images.githubusercontent.com/15545/93865741-63bd4680-fccf-11ea-84a5-5288bd48f30b.png)

**Comment by xet7** [comment]
There is no feature in Wekan to move them to right.

Click right hamburger menu / Hide minicard label text to show or hide texts:

![Screenshot_20200922-123317](https://user-images.githubusercontent.com/15545/93867000-193cc980-fcd1-11ea-9825-b64202bb9926.jpg)
