### ISSUE TITLE
Sort list of names under filter/member and filter/assigned

### ISSUE THREAD

**Issue by ntongeren31** [wekan/wekan#3286]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: no
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox

**Problem description**:
The lists of names in the filter pane are sorted by the date someone was added to a board. Please sort the member and assigned lists in the filter pane alphabetically.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5107 . Thanks to @helioguardabaxo !
