### ISSUE TITLE
Custom Date-field shows in long format

### ISSUE THREAD

**Issue by Shorty365** [wekan/wekan#3287]
In Wekan I use a Custom field with a date in it. Works fine but on my board the date shows in long format like 'Thu Oct 01 2020 08:00:00 GMT+0200 (Midden-Europese zomertijd)'and this is not consistent with the other date-fields in Kanban, which show the date in short format like '01-10-2020'

On the card itself the date in the custom-field shows in the correct format.

Tested in;
Wekan: 4.40.0 (snap-version)
Meteor: 1.11.1
Node: 12.18.4
MongoDB: 3.3.33
OS: Ubuntu 18.04, fully up to date
![Knipsel-Wekan](https://user-images.githubusercontent.com/34029827/94432995-ee9eb500-0197-11eb-8722-af9f0f0b0410.PNG)

**Comment by Lucifer-Clegg** [comment]
I have the same issue:

Wekan Version 	4.47.0
Meteor-Version 	2.0-beta.4
Node-Version 	12.19.0
MongoDB-Version 	4.4.1
MongoDB-Speicher-Engine 	wiredTiger
MongoDB-Oplog aktiviert 	
Typ des Betriebssystems 	Linux
Plattform 	linux
Betriebssystem-Architektur 	x64
Version des Betriebssystem 	4.4.59+
![wek](https://user-images.githubusercontent.com/57875690/98208994-82edfb80-1f3e-11eb-8c70-386da1ff6225.jpg)

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3446

**Comment by Lucifer-Clegg** [comment]
fine, will this be available in the next update?

**Comment by xet7** [comment]
@Lucifer-Clegg 

Yes, in next Wekan release sometime today or tomorrow.

**Comment by Lucifer-Clegg** [comment]
oh, fine, good work, boys and girls ;-)
