### ISSUE TITLE
@mention user list select user by pressing Enter key

### ISSUE THREAD

**Issue by mweiss237** [wekan/wekan#3289]
## Issue

**Server Setup Information**:
* Did you test in newest Wekan?: yes
* Wekan version: 4.40
* Operating System: Microsoft Windows 10 Pro Version 10.0.19041 Build 19041
* Node Version: v12.18.2
* MongoDB Version: v4.2.8
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome Version 85.0.4183.121 (but also on Firefox)

**Problem description**:
![Video_2020-09-30_142955_Clip](https://user-images.githubusercontent.com/26773967/94685863-508f2400-032a-11eb-9776-5e4c2747609d.gif)
The first time the user list disappears I tried to select the user by hitting the **Enter key**. 
Then I selected the user by clicking on it with my mouse.  

- *Explain steps how to reproduce*:
Open any board with multiple users, open a card, go to comments and start mentioning any user by typing "@" and select one from the list with your keyboard by pressing the arrow buttons and try to select the entry by pressing the Enter key. 

- *Expected behaviour*:
The expected behavior would be, that you can select the user by pressing the enter key, so you don't have to use the mouse.

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
Nothing.

**Comment by xet7** [comment]
Related code:
https://github.com/wekan/wekan/blob/master/client/components/main/editor.js#L304-L309

**Comment by xet7** [comment]
Try newest Wekan.
