### ISSUE TITLE
LDAP MS ActiveDirectory with wekan_start.bat on WindowsServer

### ISSUE THREAD

**Issue by holehner** [wekan/wekan#3292]
I have a microsoft server 2012 with wekan_start.cmd with ldap configuration for ms active directory. the user and the ldap paths are correct. However, I keep getting the error: InvalidCredentialsError: 80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1
my config looks like this:
set  ldap-enable='true'
set  default-authentication-method='ldap'
set  ldap-port='389'
set  ldap-host='192.168.199.5'
set  ldap-basedn='CN=Users,DC=test,DC=local'
set  ldap-login-fallback='false'
set  ldap-reconnect='true'
set  ldap-timeout='10000'
set  ldap-idle-timeout='10000'
set  ldap-connect-timeout='10000'
set  ldap-authentication='true'
set  ldap-authentication-userdn='CN=wekan,CN=Users,DC=test,DC=local'
set  ldap-authentication-password='meintest28r'
set  ldap-log-enabled='true'
set  ldap-background-sync='true'
set  ldap-background-sync-interval='60000'
set  ldap-background-sync-keep-existant-users-updated='true'
set  ldap-background-sync-import-new-users='true'
set  ldap-encryption='false'
set  ldap-user-search-field='sAMAccountName'
set  ldap-username-field='sAMAccountName'
set  ldap-fullname-field='cn'
set  internal_log_level=debug

i have no idea, please help me. thank you

**Comment by xet7** [comment]
>  ldap-background-sync-interval='60000'

Syntax is `every 1 hour` or similar. 
https://github.com/wekan/wekan/wiki/LDAP

**Comment by holehner** [comment]
Thanks for the quick help. the one with the interval was a test. i have just corrected it, but the same error picture. I have already found the wiki page, but I still get no further. can it be that there are problems with windows-> windows and ldap?

**Comment by holehner** [comment]
Even if I intentionally configure incorrect user data for authentication, the same error message appears

**Comment by xet7** [comment]
@holehner 

I don't know. There are many ways to configure login at https://github.com/wekan/wekan/wiki at right menu.

**Comment by holehner** [comment]
ok, is there a way to extend the login so that I can get more ldap debug information?

**Comment by xet7** [comment]
```
sudo snap set wekan debug='true'

sudo snap logs wekan.wekan
```
And also look at syslog:
```
sudo tail -f /var/log/syslog
```

**Comment by holehner** [comment]
![grafik](https://user-images.githubusercontent.com/8546380/94997313-8f331180-05aa-11eb-86a9-1b2b6915eece.png)
ok, i already have the debug active and get the display on the cli. I'm not surprised, however, that I always get the same error message. I meant whether there might be more ldap info. Many Thanks

**Comment by xet7** [comment]
You can also search these issues for previous LDAP answers.

UCS also uses LDAP with Wekan Docker version, some replies could be related:
https://github.com/wekan/univention/issues

**Comment by holehner** [comment]
ok, i check your answer. one more question, if the debug shows: "[INFO] LDAP is connected" should a correct connection be available?

**Comment by xet7** [comment]
@holehner 

Maybe. I don't use LDAP on my servers. I did some changes related to LDAP, but LDAP code is originally from other Wekan contributors. Some other LDAP users have written that LDAP login works in some configurations.

**Comment by holehner** [comment]
thank you very much, then i will keep trying my luck. a lovely evening

**Comment by holehner** [comment]
[wekan_ldap_win2012.txt](https://github.com/wekan/wekan/files/5323166/wekan_ldap_win2012.txt)

Ldap works! I have an MS Windows 2012 server with wekan_start.cmd and the accompanying configuration. I am using MS Active Directory. The main problem was that a filter had to be set. It doesn't work without a filter! A few reboots to be on the safe side and it works!

**Comment by veloprofz** [comment]
how to turn on the option so that ldap authentication appears in the admin panel?

**Comment by xet7** [comment]
@veloprofz 

https://github.com/wekan/wekan/wiki/LDAP

# Snap

sudo snap set wekan ldap-enable='true'

# Docker

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L488
