### ISSUE TITLE
snap.wekan.wekan.service: Scheduled restart job, restart counter is at 10365.

### ISSUE THREAD

**Issue by relikd** [wekan/wekan#3293]
## Issue

Just noticed that my wekan server is down and don't seem to recover.
Can it be that a software update triggered the bad behavior as I didn't change anything in the configuration.

Sorry for the short detail description I am still trying to get it working again.

```
/snap/wekan/1028/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoNetworkError: failed to connect to server [127.0.0.1:27019] on first connect [Error: co>
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/snap/wekan/1028/programs/server/npm/node_modules/meteor/npm-mongo/>
    at Pool.emit (events.js:315:20)
    at /snap/wekan/1028/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongo>
    at /snap/wekan/1028/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongo>
    at /snap/wekan/1028/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongo>
    at callback (/snap/wekan/1028/programs/server/npm/node_modules/meteor/npm-mongo/node_mod>
    at Socket.<anonymous> (/snap/wekan/1028/programs/server/npm/node_modules/meteor/npm-mong>
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by xet7** [comment]
Is MongoDB running?
Try this:
```
sudo snap stop wekan

sudo snap start wekan
```

**Comment by relikd** [comment]
Already did. Does not work. Here is additional context from the logs:
```
mongod.27019[1367907]: [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27019 }, storage: { dbPath: "/var/snap/wekan/common", journal: { enabled: true } }, systemLog: { destination: "syslog", quiet: true } }
mongod.27019[1367907]: [initandlisten] listen(): bind() failed errno:2 No such file or directory for socket: /tmp/mongodb-27019.sock
mongod.27019[1367907]: [initandlisten] Failed to set up sockets during startup.
mongod.27019[1367907]: [initandlisten] dbexit:  rc: 48
wekan.mongodb[1367909]: Error parsing command line: unrecognised option '--bind_ip'
wekan.mongodb[1367909]: try 'mongo --help' for more information
```

**Comment by xet7** [comment]
What settings you have? Please anonymize URLs, usernames, passwords etc.
```
sudo snap get wekan
```

**Comment by relikd** [comment]
```
Key                       Value
oauth2-auth-endpoint      /index.php/apps/oauth2/authorize
oauth2-client-id          REDACTED
oauth2-email-map          email
oauth2-enabled            true
oauth2-fullname-map       display-name
oauth2-id-map             id
oauth2-login-style        redirect
oauth2-secret             REDACTED
oauth2-server-url         https://REDACTED/
oauth2-token-endpoint     /index.php/apps/oauth2/api/v1/token
oauth2-userinfo-endpoint  /ocs/v2.php/cloud/user?format=json
oauth2-username-map       id
password-login-enabled    false
port                      5040
root-url                  https://REDACTED
```
(using nextcloud for oauth)

**Comment by xet7** [comment]
Try this:
```
sudo snap set wekan mongodb-bind-unix-socket='/var/snap/wekan/current/share'

sudo snap unset mongodb-bind-ip

sudo snap enable wekan.mongodb

sudo snap start wekan.mongodb
```

**Comment by xet7** [comment]
Also in your URLs, for example you have this:
```
oauth2-server-url         https://REDACTED/
oauth2-token-endpoint     /index.php/apps/oauth2/api/v1/token
```
If you have `/` at right end of URL, it should not also be at left beginning of token endpoint, because you then get double `//`, when you don't use full URLs with `http...`.

**Comment by relikd** [comment]
*Phew*, I fixed it. Though I don't know what caused the issue. I deleted old snaps and forced a complete system reboot. That did the trick. Thanks for your support!
Secondary wish: Maybe there is a way to prevent the constant service restart after a couple hundred retries? It spammed my sys-logs with about 256MB per hour for I don't know how many hours.

Thanks for pointing out the issue with the slash. That is indeed the case. And the login worked so far but only on the second try. Maybe that was the reason for that.
Again, many many thanks.

**Comment by xet7** [comment]
Sometimes systemd gets confused with restarting services, so in that case usually reboot works.

I don't know do I have any access to restart behaviour, I would presume it is the default that is used in Snap packages.

About logging to syslog, I have not yet fould how to reduce amount of logs generated.

**Comment by relikd** [comment]
Just did a quick search, it seems snap [has support][1] for the systemd restart behavior, e.g., `restart-delay` though `10m` is max. Which would help already. It could also be made `oneshot` in which case it wouldn't restart at all. But that needs to be evaluated what side effects this will have on other issues that result in a crash.

About syslog, luckily I had set a maximum of 4GB, so it didn't hurt that much. But I think it is by default either unlimited or very high at least.

[1]: https://snapcraft.io/docs/services-and-daemons

**Comment by xet7** [comment]
@relikd 

What should that `restart-delay` be?

**Comment by relikd** [comment]
It depends on whether there are cases where a restart can actually solve a problem. For example, if a crash is produced by a temporary inaccessible ressource, I would like the service to restart immediatelly (as it is the case now). If a restart can't fix the problem (as in my case) I would want the delay to be longer. Maybe something between 1 and 5 minutes is reasonable?

It would help if we had data on the how and when wekan crashes. If the first type of crash never occurs then this can be set to 'oneshot'. That way the service will stop altogether and properly display the error reason. Which in turn, would make the debugging much easier and tell you exactly when the service crashed for the first time.

But as long as we can't be sure that there are situations where a restart indeed helps, this may backfire and users start complaining why their service isn't running anymore. I am not sure whats the good course of action here. You could also set it to 30 minutes and see if someone complains in the next months.

**Comment by xet7** [comment]
I don't know of any cases about why it should be changed. So I will keep it the same.

**Comment by xet7** [comment]
Although, setting it to 10 seconds would probably help with too fast restarts problem of systemd.
