### ISSUE TITLE
Request: Calendar items should be color-coded

### ISSUE THREAD

**Issue by ocdtrekkie** [wekan/wekan#3296]
## Issue

When you add a due date to a card, it is visible in calendar view... but in calendar view, it is always blue. It is not themed, and most unfortunately, it is not color-coded. A user I am trying to introduce to Wekan would very much like the color of a label assigned to the card to be the color it appears in calendar view (especially monthly view).

**Comment by helioguardabaxo** [comment]
It's working fine on latest version:
![image](https://github.com/wekan/wekan/assets/24301085/244017df-caa1-411c-bc3c-c4d0794c0d84)
