### ISSUE TITLE
oauth2 fails with self-signed server certificate

### ISSUE THREAD

**Issue by om22** [wekan/wekan#3299]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: yes, v4.41.0
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: v4.41.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: RHEL 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 12.18.4
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome 86.0.4240.75

**Problem description**:

- No GIF, but screenshot should be enough:

![2020-10-12 09_18_54-Window](https://user-images.githubusercontent.com/5031488/95717055-af2e9900-0c6c-11eb-8c90-7f141ca8a4e9.png)
On login with OIDC the redirect window opens, then it just shows Internal server error

- Log with debug enabled:

2020-10-12T06:58:01Z wekan.wekan[84894]: Exception while invoking method 'login' Error: Failed to get token from OIDC https://xxxxxx/auth/realms/xxxxxx/protocol/openid-connect/token: self signed certificate in certificate chain

- oauth2 settings:

oauth2-enabled: true
oauth2-login-style: redirect
oauth2-client-id: *************
oauth2-secret: *************
oauth2-server-url: *************
oauth2-auth-endpoint: auth/realms/xxxxxx/protocol/openid-connect/auth
oauth2-userinfo-endpoint: auth/realms/xxxxxx/protocol/openid-connect/userinfo
oauth2-token-endpoint: auth/realms/xxxxxx/protocol/openid-connect/token
oauth2-id-map: preferred_username (also tested email)
oauth2-username-map: preferred_username (also tested email)
oauth2-fullname-map: name
oauth2-email-map: email
oauth2-request-permissions: openid profile email

Our PKI root CA certificate is installed on the server and should be accepted as valid, but somehow Wekan doesn't accept it. Is there a way to tell it to do so or can we import our root certificate?
We are using Keycloak. Any help is appreciated

**Comment by faust64** [comment]
Hi,

FYI, NodeJS ships with its own trust store. Trusting some CAs on your system has no effect on NodeJS apps.

I'm ending up here hitting with the very same issue.
The OIDC code calls for node HTTP methods (eg: https://github.com/wekan/wekan/blob/a33cad0d13c25cc01604802337a920e3975f6365/packages/wekan-oidc/oidc_server.js#L61 ) without allowing to set some optional CA path, as it was done in the LDAP auth code.

A PR would be necessary ...

**Comment by xet7** [comment]
@faust64 

Please send PR :slightly_smiling_face:
