### ISSUE TITLE
More than one assignee?

### ISSUE THREAD

**Issue by ivan-paleo** [wekan/wekan#3302]
I cannot assign more than one person per card; is that normal or is it a bug? 

If it's not a bug, there might be a good reason for that, but I think it would make sense to allow more than 1 assignee per card. In any case, the "+" seems to suggest it is possible.

**Comment by xet7** [comment]
@ivan-paleo 

Original feature request really required that only one assignee can be selected #2452 

Assignee is the main person responsible for getting that task done. Others can be members.

I implemeted feature `Assignee field like Jira` at [Wekan v3.50](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v350-2019-11-13-wekan-release).

In that implementation, there is [this change: Prevent more than one assignee](https://github.com/wekan/wekan/commit/1728298659521ee8e6fc94fedad3160030b9a2c3). If that change is reverted, there can be any amount of assignees.

Related to that, I implemented [Worker role](https://github.com/wekan/wekan/issues/2788) at [Wekan v3.62](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v362-2020-01-05-wekan-release). The person who has worker role can only assign itself to issue, but can not unassign itself.

So it depends, does some other kanban software really have possibility to more than one assignee? And does someone need that feature?

**Comment by ivan-paleo** [comment]
> Assignee is the main person responsible for getting that task done. Others can be members.
> And does someone need that feature?

Thank you @xet7 for the detailed answer.
To me it then becomes a matter of terminology: "Assignee" is explicitly saying that the person will do the job, while "Member" is someone watching if you see what I mean. That's why, to me, it should be possible to have more than 1 person truly working on a task. 

But since it's a matter of terminology, I just need to let people know about what each role implies :)
