### ISSUE TITLE
users accounts lockout 

### ISSUE THREAD

**Issue by still-L** [wekan/wekan#3306]
accounts-lockout" : { "failedAttempts" : 1, "lastFailedAttempt" : 1603184469280, "firstFailedAttempt" : 1603184469276 } } MongoDB  How to remove lock。

**Comment by xet7** [comment]
You could try using nosqlbooster . Please search with that word `nosqlbooster` for other open and closed issues where are more instructions.

**Comment by still-L** [comment]
> You could try using nosqlbooster . Please search with that word `nosqlbooster` for other open and closed issues where are more instructions.
thank.
this is docker run mongo   no proxy port can not use nosqlbooster . is shell link mongo

**Comment by xet7** [comment]
Well, maybe I'll try to write some examples:
```
docker exec -it wekan-db bash

mongo

use wekan

show collections
```
That does show table names. For example, if there is:
```
AccountsLockout.Connections
```
Then you can look what is has with:
```
db.AccountsLockout.Connections.find()
```
And then delete those all:
```
db.AccountsLockout.Connections.deleteMany({})
```
Then exit:
```
exit

exit
```

**Comment by still-L** [comment]
> Well, maybe I'll try to write some examples:
> 
> ```
> docker exec -it wekan-db bash
> 
> mongo
> 
> use wekan
> 
> show collections
> ```
> 
> That does show table names. For example, if there is:
> 
> ```
> AccountsLockout.Connections
> ```
> 
> Then you can look what is has with:
> 
> ```
> db.AccountsLockout.Connections.find()
> ```
> 
> And then delete those all:
> 
> ```
> db.AccountsLockout.Connections.deleteMany({})
> ```
> 
> Then exit:
> 
> ```
> exit
> 
> exit
> ```

**Comment by still-L** [comment]
> > Well, maybe I'll try to write some examples:
> > ```
> > docker exec -it wekan-db bash
> > 
> > mongo
> > 
> > use wekan
> > 
> > show collections
> > ```
> > 
> > 
> > That does show table names. For example, if there is:
> > ```
> > AccountsLockout.Connections
> > ```
> > 
> > 
> > Then you can look what is has with:
> > ```
> > db.AccountsLockout.Connections.find()
> > ```
> > 
> > 
> > And then delete those all:
> > ```
> > db.AccountsLockout.Connections.deleteMany({})
> > ```
> > 
> > 
> > Then exit:
> > ```
> > exit
> > 
> > exit
> > ```
AccountsLockout.Connections tables IP host lock remove，this is  lock  users tables  user id information have accounts-lockout。

**Comment by still-L** [comment]
![image](https://user-images.githubusercontent.com/24404908/96668260-5d34f400-138d-11eb-8b16-b1b01611a17e.png)

**Comment by xet7** [comment]
@still-L 

Deleting accounts-lockout of all users:
```
db.users.update( { }, { $unset: { "services.accounts-lockout": "" } }, { multi: true } )
```

Deleting accounts-lockout of one user:
```
db.users.update( { "username": "turtle" }, { $unset: { "services.accounts-lockout": "" } }
```
