### ISSUE TITLE
"Connect with oidc" Button

### ISSUE THREAD

**Issue by Dranaxel** [wekan/wekan#3309]
Other Wekan issues can be added here.

EC2 on amazon with Wekan 4.43.0

Hello I'm using Wekan with oauth2 authentication from Azure AD, an only this. So i only have a button with "Connect with Oidc" (more or less, i'm using french version)

I would like to know if there is a way to modify the caption of the button, ie "Connect using Azure AD" or anything else.

Thanks

**Comment by xet7** [comment]
@Dranaxel 

Currently there is not yet feature in Wekan to change that button text. OIDC means same as OAuth2.

There are these features:

1) Click right top your username / Admin Panel / Settings / Layout, there you can change:
- [Custom Logo](https://github.com/wekan/wekan/wiki/Custom-Logo)
- Text Below Custom Logo, etc. So you can add text that has info, for example: `Please click OIDC button to Connect using Azure AD`.
- Click `Display Authentication Method: No` to hide displaying authentication method selection like OAuth2/OIDC/Password
- You can select default authentication method

2) At server shell with `wekan.help | password` is info about this command, that hides password login, so it's possible to login only with OIDC button:
```
sudo snap set wekan password-login-enabled='false'
```

If this is still not enough, and you would like ability to change button text, you can fund 500 euro for developing that feature with payment options at https://wekan.team/commercial-support/ . Getting custom button text requires developing custom template for login screen, where is more flexibility for button texts and other changes.
