### ISSUE TITLE
worker can't move a card in mobile view

### ISSUE THREAD

**Issue by jtbairdsr** [wekan/wekan#3314]
## Issue

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly?: yes
* Wekan version: v4.43
* Operating System: ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none
* Node Version: v14.5.0
* MongoDB Version: v4.0.4
* What web browser version are you using?: Chrome Version 86.0.4240.111 (Official Build) (x86_64)

**Problem description**:
the menu option to move a card is hidden for workers.  That is just fine in desktop mode because we can still drag and drop cards between columns.  In mobile mode, the worker is not able to move the card to a new column.  I have inspected the code and I can see that we are deliberately hiding that menu option for workers so I believe that this is intentional.  The question I have is why we don't want workers to move cards... my understanding is that is exactly what workers are supposed to do.  It occurs to me that we may not want workers to move cards to another board.

I have a PR ready that exposes that menu option to a worker and hides the move board functionality from the submenu; but I want to make sure I understand the complexities before I go any farther down that road.

@xet7 would you be willing to review and accept a PR with that change or am I missing something.

**Comment by xet7** [comment]
@jtbairdsr 

Yes, you can send PR to fix these.

**Comment by jtbairdsr** [comment]
@xet7 I just sent the PR across.  let me know what needs to happen to move it through.  Thanks again for your support.
