### ISSUE TITLE
Access denied [403] on download attachment

### ISSUE THREAD

**Issue by gustavooliveir** [wekan/wekan#3317]
Firstly, thanks for developing this amazing app, it is being of great use for our team.

When someone creates a card and attach some files to it and send the card to another board, it happens that only THOSE THAT WERE IN THE ORIGINAL BOARD at the time of attachment of those files can access the files attached on that card. When someone who doesn't have access to the board in which it was created try to download an attached file, it says 'Access denied [403]'.

We've tryied to change admin permissions and everything but it seems that nothing changes this behavior. In the end, if i open my board, create a card, attach some PDFs to it and send it to someone else who doesn't have access to my board, this second person cannot access those PDFs.

I am not sure if it is a feature or a bug. If it is something like a privacy feature, maybe there is an option i'm not aware of to make the files avaiable to all those who receive the card.

I am using the latest version of wekan

**Comment by xet7** [comment]
Yes, that is by design https://github.com/wekan/wekan/issues/1322#issuecomment-709755215

If you change that board from Private to Public, anyone in Internet can see board and attachments and download them.

**Comment by xet7** [comment]
@gustavooliveir 

Oops, maybe I did not read your question carefully enough?

With `attach some PDFs to it and send it to someone`, do you mean:

- [ ] Copy card to another board?
- [ ] Move card to another board?
- [ ] Link card to another board?

If that happens, I think that it could be a bug.

**Comment by gustavooliveir** [comment]
I meant "Move card to another board".

Whenever I move a card to another board, no one from the new board can access the PDF files, except for those that had access to the board where the card files where attached. Therefore, it seems there is no point in attaching files to a card if you intend to send this card to some other board for other team to work with.

**Comment by xet7** [comment]
Hmm, probably move card does not set all the permissions correctly. It's a bug.
