### ISSUE TITLE
Gitlab Oauth not working

### ISSUE THREAD

**Issue by Aguay-val** [wekan/wekan#3321]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 4.44.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): traefik
* Node Version: 14.15.0
* MongoDB Version: 3.2.21
* Gitlab CE : 13.3.6
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Google Chrome

**Problem description**:
I can't use my private gitlab server to oauth on  wekan. Both as "register" or "login".
All is looking "great" but i have "internal server error" when my gitlab server call back wekan.

Here logs in docker compose : 
```
wekan-app  | {"line":"405","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC https://gitlab/oauth/token: failed [401] {\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}","time":{"$date":1604055710445},"level":"warn"}
wekan-app  | Exception while invoking method 'login' Error: Failed to get token from OIDC https://gitlab/oauth/token: failed [401] {"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

**Comment by xet7** [comment]
Did you set redirect URL to your Wekan root-url+_oauth/oidc like this: https://boards.example.com/_oauth/oidc ?

**Comment by Aguay-val** [comment]
Yes absolutely. Here my docker-compose file : 
```
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://wekan.fqdn.fr
      - MAIL_URL=smtp://smtp:25/?ignoreTLS=true
      - MAIL_FROM='Wekan <email>'
      - WITH_API=true
      - DEBUG=true
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=CLIENT_ID
      - OAUTH2_SECRET=SECRET_ID
      - OAUTH2_SERVER_URL=https://mygitserver/
      - OAUTH2_AUTH_ENDPOINT=oauth/authorize
      - OAUTH2_USERINFO_ENDPOINT=oauth/userinfo
      - OAUTH2_TOKEN_ENDPOINT=oauth/token
      - OAUTH2_ID_MAP=sub
      - OAUTH2_USERNAME_MAP=nickname
      - OAUTH2_FULLNAME_MAP=name
      - OAUTH2_EMAIL_MAP=email
      - OAUTH2_REQUEST_PERMISSIONS=openid profile email
```
And here gitlab configuration:
![image](https://user-images.githubusercontent.com/2204373/97708981-e6e56f80-1ab9-11eb-8457-132ffce240ca.png)

**Comment by xet7** [comment]
Try these:
```
      - OAUTH2_USERNAME_MAP=email
      - OAUTH2_EMAIL_MAP=email
```
If after that is still does not work, change this too:
```
- OAUTH2_LOGIN_STYLE=popup
```
If after that is still does not work,  change this too:
```
- OAUTH2_REQUEST_PERMISSIONS=openid
```

**Comment by Aguay-val** [comment]
Still not working I don't know what i'm doing bad. Do i have to register or should i be able to login from "oidc" button ?

**Comment by xet7** [comment]
First you need to be logged in to GitLab, and then in another tab click OIDC button.

**Comment by xet7** [comment]
Does it show any errors at:
- Near OIDC button
- `docker logs wekan-app`
- browser right click Inspect Console ?

**Comment by xet7** [comment]
At Wekan right click top right username / Admin Panel / Settings / Layout is `Show Authentication Method`. When that is selected to be visible, at login screen is dropdown OAuth2 or Password login.

At Admin Panel / Settings / People you can select for each person OAuth2 or password login.

After OAuth2 works, Authentication Method can be hidden, and in docker-compose.yml can be set `PASSWORD_LOGIN_ENABLED=false` to hide password login.

**Comment by Aguay-val** [comment]
Ok finally it's working. 
I tried to "upgrade" are wekan installation. I finally docker-compose stop/rm + delete all data.
I docker-compose up and it's seems to work. I don't know what happend. You probably help me with the request permission.

Thanks a lot !
