### ISSUE TITLE
Uploading attachments suddenly stopped working in Wekan v4.44, it is fixed already in Wekan v4.45

### ISSUE THREAD

**Issue by evservice** [wekan/wekan#3322]
Today wekan suddenly won't accept uplaods anymore. The browser shows a 503 error when trying to add an attachment to a card.

The wekan log shows:

Oct 30 14:14:19 linux.yakkz.nl wekan.wekan[19415]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Fri Oct 30 2020 14:14:18 GMT+0100 (Central European Standard Time)","time":{"$date":1604063659122},"level":"info"}
Oct 30 14:14:35 linux.yakkz.nl wekan.wekan[19415]: (node:20980) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Oct 30 14:14:35 linux.yakkz.nl wekan.wekan[19415]: (Use `node --trace-deprecation ...` to show where the warning was created)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]: SA GridFS - ERROR! undefined
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]: packages/cfs_collection.js:186
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:         self.emit('error', new Error('Error storing uploaded file to TempStore: ' + error.message), fileObj);          // 153
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:                                                                                           ^
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]: TypeError: Cannot read property 'message' of undefined
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at EventEmitter.<anonymous> (packages/cfs_collection.js:186:91)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at EventEmitter.emit (events.js:327:22)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at EventEmitter.emit (domain.js:486:12)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at GridWriteStream.<anonymous> (packages/cfs:tempstore/tempStore.js:348:10)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at GridWriteStream.emit (events.js:327:22)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at GridWriteStream.EventEmitter.emit (domain.js:486:12)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at GridWriteStream.FlushWritable.emit (/snap/wekan/1045/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/node_modules/flushwritable/lib/FlushWritable.js:37:31)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at GridWriteStream._error (/snap/wekan/1045/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:246:7)
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at /snap/wekan/1045/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:265:8
Oct 30 14:14:46 linux.yakkz.nl wekan.wekan[19415]:     at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Server Setup Information**:

* Did you test in newest Wekan?: YES
* Operating System: Debian
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache, but tried direct (without frontend) as well
* Node Version: ?
* MongoDB Version: Snap version
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome/Opera

**Comment by xet7** [comment]
Please upgrade to Wekan v4.45 . It will update automatically, or you can manually update with:
```
sudo snap refresh
```
I will leave this issue open for a while so that others notice this too.

**Comment by evservice** [comment]
Upgrading did indeed fix the issue.

**Comment by ramzauchenna** [comment]
Hi @xet7. Please how did you fix this. i have a similar issue in my personal project after upgrading to meteor 2.7.3 regardless of the node version

**Comment by xet7** [comment]
@ramzauchenna 

This fix at v4.45 is from 2020, it is in no way related to current WeKan v6.39 now at 2022.

Meteor 2.7.3 only works with Node.js 14.x and MongoDB 5.x. Compatible versions are listed at https://wekan.github.io Download section.

Attachments changes was mostly @imajus and @mfilser at https://github.com/wekan/wekan/pull/4336 etc, not me.

WeKan has changed from CollectionFS to Meteor-Files/ostrio:files. For that, there is attachments migrations at wekan/server/migrations.js , where name has text `ostrio` included. Migrations move attachments to different collections/tables at same database, by temporarily saving files to filesystem, and writing attachments back to database. For that, there is required to be environment variable WRITABLE_PATH in start-wekan.sh/bat, docker-compose.yml, snap etc.

But there is still bugs in migrations from older versions, I'm In Progress of trying to fix it.
