### ISSUE TITLE
Click on the duplicate logo action doesn't do anything since recent version change

### ISSUE THREAD

**Issue by e-gaulue** [wekan/wekan#3326]
On the Snap version.

Same on Firefox or Safari.

![Capture d’écran 2020-11-02 à 14 57 15](https://user-images.githubusercontent.com/4291874/97876263-e0eec900-1d1b-11eb-982f-7e481124003f.png)

Regards,

**Comment by xet7** [comment]
@e-gaulue 

Thanks! I'll try to fix it.

**Comment by e-gaulue** [comment]
Hi,

I think it has gone again.

Regards, EG

**Comment by jrsupplee** [comment]
I think it was part of the regex issue.  Should be fixed.

**Comment by xet7** [comment]
@e-gaulue 

Is this fixed now in newest Wekan?
