### ISSUE TITLE
Error syntax highlighting in description and comments

### ISSUE THREAD

**Issue by dialogik** [wekan/wekan#333]
Two issues:
## Unintended encoding of character `<`
1. When sourcecode with an `<` is entered in description or comments, that is encoded to its HTML ASCII equivalent `&lt;` whereas `>` remains unchanged. E.g.
   
   ```
   <IfModule mod_headers.c>
     Header always set X-Frame-Options SAMEORIGIN
   </IfModule>
   ```
   
   becomes
   
   ```
   &lt;IfModule mod_headers.c>
     Header always set X-Frame-Options SAMEORIGIN
   &lt;/IfModule>
   ```
## Trimming suppresses syntax highlighting

When you try to start the description or a comment with four-whitespace-indentated sourcecode, trimming (at least I assume that this is due to trimming) the content removes the leading whitespaces which removes syntax highlighting.

**Comment by xet7** [comment]
Try newest Wekan.

Closing issue.
