### ISSUE TITLE
[Question] Docker Container Version Number?

### ISSUE THREAD

**Issue by NoDraven** [wekan/wekan#3331]
Hello,
  everthing is working fine.  Probably i  have looked at the wrong places because i could not locate the "current version number" of the podman/docker container in use. I'd like to add this info to the name of backup files, as it is described in the backupscript file for the snap version.
Would someone be so nice and direct me to a "file/location" from where i can extract the actual version e.g.: 4.48 ?  I didn't find a solution in here ( issues) either.

Thanks in advance.

**Comment by NoDraven** [comment]
Anyone knows were one can extract the version  of the running container?

**Comment by xet7** [comment]
@NoDraven 

From container:
```
docker exec -it wekan-app bash
more /build/programs/web.browser/app/api/wekan.yml
```
Or webbrowser: Click right top username / Admin Panel / Version

**Comment by NoDraven** [comment]
Thank you.
