### ISSUE TITLE
Kubernetes Helm chart doesn't work - mongoDB version deprecated.

### ISSUE THREAD

**Issue by missteek** [wekan/wekan#3332]
Hello team,

Can you please update this Helm chart and provide some documentation.

* mongodb version is deprecated 
* does not work with mongoDB bitnami chart

**Comment by xet7** [comment]
@missteek 

Please send pull request to fix it, or find previous Wekan Helm chart contributor from changelog, link at https://wekan.github.io

I have not used Kubernetes.

**Comment by jiangytcn** [comment]
@missteek can you elaborate the release/version for bitnami chart ?

**Comment by missteek** [comment]
Hello Jiang,

Thanks for the email.

Couldn't get wekan to run on k8s due to the deprecated mongodb 3.11.x
helm charts (https://kubernetes-charts.storage.googleapis.com/) in
requirements.yaml

Helm now advise using bitnami helm charts for mongodb, versions
supported are from 4.x onwards and any version 4 chart from Bitnami
should work.

Best regards







Jiang Yitao wrote:

**Comment by jiangytcn** [comment]
thanks @missteek, working on it
