### ISSUE TITLE
Bug: Duplicated Board missing custom fields, comments, checklist items, parent tasks and member assignment

### ISSUE THREAD

**Issue by daniel-eder** [wekan/wekan#3336]
## Issue

**Server Setup Information**:
* Did you test in newest Wekan?: yes
* Wekan version: 4.49.0
* Operating System: Ubuntu
* Deployment Method: snap
* Http frontend if any: nginx
* Node Version: 12.19.0
* MongoDB Version: 3.2.22
* What webbrowser version are you using? Chromium Version 79.0.3945.117

**Problem description**:
When cloning a board all custom fields are lost. That means no custom fields exist in the custom fields configuration of the board, and, as one would expect in that case, the cards no longer have custom fields either.

Source Board custom fields:
![image](https://user-images.githubusercontent.com/1525711/98521301-87ceea00-2273-11eb-9e30-fc4deb037ba5.png)

Cloned board custom fields:
![image](https://user-images.githubusercontent.com/1525711/98521336-90bfbb80-2273-11eb-8472-553766f8e1b4.png)

*Explain steps how to reproduce*:
- Go to board overview
- Click "Duplicate board"
- Compare source to the cloned board: Custom fields are missing

**Further Info** 
A quick look at wekanCreator.js (which after a cursory look seems to be responsible) shows that custom fields are not handled in there yet.

**Comment by xet7** [comment]
@daniel-eder 

Can you send pull request to fix it? [Here is info how to build Wekan and create PR](https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin).

**Comment by daniel-eder** [comment]
> @daniel-eder
> 
> Can you send pull request to fix it? [Here is info how to build Wekan and create PR](https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin).

@xet7 I've got it on my todo list, as we're trying to duplicate our board by year's end. Couldn't make time for it yet, but will definitely PR when I find time to create a fix.

**Comment by avatar1024** [comment]
I have just noticed that comments and checklist items are also lost when duplicating a board (check list name/headings are conserved). I wonder if the two issues are related? Happy to open a new issue if preferable.

**Comment by lezioul** [comment]
Hi,

why is this issue closes? I'm using latest version and it is still happening (number of comments are listed but no comments in detailed view).
Maybe i can provide logs if you want.
It is always reproductible : make a card, add comments, duplicate the whole board : comments and attachments are missing.

**Comment by xet7** [comment]
@lezioul 

At Admin Panel / Version, do you have Wekan v4.60 ?

**Comment by xet7** [comment]
This was closed because @daniel-eder already fixed this.

**Comment by xet7** [comment]
Just a moment I'll test.

**Comment by daniel-eder** [comment]
> Just a moment I'll test.

I couldn't repro it on my end - give me a ping if it repros, if possible with an export of the affected board, and I'll revisit the issue

**Comment by xet7** [comment]
@lezioul 

When I duplicate board, comments and attachments are duplicated too. Please check are you running newest Wekan.

What Wekan platform are you running on? Snap, Docker, Source, Sandstorm, Univention?

**Comment by daniel-eder** [comment]
@lezioul 
This may depend on board size or on some "arcane" situation like having a deleted comment or a deleted card on the board, the checklist items had a similar issue where the import/clone would error out when it hit a deleted checklist or card.

If you are on the latest version, does this reproduce on a clean new board?

**Comment by lezioul** [comment]
I'm using snap version 4.60.0
I cannot provide an export of the board but here are 2 screens : 

Original board : 
![image](https://user-images.githubusercontent.com/4048547/102353347-33710580-3fa9-11eb-8f98-a10f6cb94c38.png)

Duplicate Board : 
![image](https://user-images.githubusercontent.com/4048547/102353379-3d930400-3fa9-11eb-892f-ffe7158afedf.png)

Attachement is missing, as well as comments and checklist.
I have some deleted cards, so maybe i should start from scratch and create a new board and move current unfinished tasks to this?

**Comment by daniel-eder** [comment]
@lezioul Can you create a new board in your instance, and test if it happens in that board as well?
If it does not, it would help if you could e.g. delete a card and try again, then a comment and try again and so on, to see when the issue first starts. 

If we find out how to reproduce it and/or you can get me a board export that shows the error I can fix that for you and you need not move to a new board :)

**Comment by lezioul** [comment]
Ok.
Where are located the logs?

**Comment by lezioul** [comment]
Just tested what you said and same behaviour occurs.
How can i send you an export without sensible data in it (e.g. names)?

**Comment by daniel-eder** [comment]
Maybe @xet7 has an idea regarding the logs, I've only done a few small contributions, by no means an expert
What you can do @lezioul is open the exported .json file in a text editor and do a quick search and replace to remove anything sensitive. If this is on a fresh board it should be a relatively small export with very few data.

**Comment by daniel-eder** [comment]
@lezioul The issue seems to be the attachment. `.class` had some issues with mime types that I will fix. 
Can you create a new test board (important, do not reuse the existing), and create just 2 cards with comments (and nothing else) and see if the comments work on duplicate or export/import?

Just to rule out any additional issues. Thanks!

**Comment by lezioul** [comment]
Hi!
To be honest i upload the first file available in the filechoose :D (i think nobody will attach a compile java Class on a card)
I've just tested what you suggest, and it worked on duplicate.
Also work on export and reimport.

**Comment by daniel-eder** [comment]
Still, it's a good use case! The same would probably apply to e.g. pdfs or most other files that are not text-based, archives or images. 
Based on your report it sounds like the issue really was just the attachment - the fix is already done and just needs to be accepted by xet7, so with any luck it will be live tomorrow or the day after.

**Comment by lezioul** [comment]
Maybe it also fixes my other open issue then.

**Comment by daniel-eder** [comment]
Remaining issue with attachments fixed in #3395
