### ISSUE TITLE
Screenshots in comments

### ISSUE THREAD

**Issue by Podolyan98** [wekan/wekan#3337]
I tried to take a screenshot(print screen) and upload it to a comment(ctrl + v), but it doesn't work. It can be fixed? 
I used different permissions for the user, but nothing has changed. 

My task looks like this:
![image](https://user-images.githubusercontent.com/68119338/98551398-f0cf5580-22a5-11eb-84de-efc590d09aab.png)

**Comment by xet7** [comment]
On some operating systems, it could be possible to add image with Ctrl-V to attachments to Attachments / Ctrl-V part of card.

If you like to view that attachment also in comment, you can use that image url with image tag like this with optional width and height: `<img src='https...' width="100" height="100">` , but it's not currently possible to paste or attach image to comment.
