### ISSUE TITLE
issue of attachment

### ISSUE THREAD

**Issue by HonestQiao** [wekan/wekan#334]
1. In a new card, if we want to upload a attachment, it need two click.
2. In attachment list, The length and breadth of the thumbnail is wrong.
3. In activity, the image is too small.
4. If a attachment is a image, we can't click and view it online.

**Comment by xet7** [comment]
1. Yes, that's how it works currently.
2. Themes #781 will make all layout customizable at some point.
3. See 2. above
4. Viewing attachement seems to work now.
