### ISSUE TITLE
Speed improvements In Progress

### ISSUE THREAD

**Issue by bbyszio** [wekan/wekan#3345]
## Issue
On boards with many members (60 an more) the loading of the mention preview is very slow or does not work.
When i type @ i have to wait a few minutes for seeing the preview of membernames. Often the never will appear.
The creating of new cards (The execution of rules on the card) is very slow too.

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 4.50.0
* Operating System: Ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): apache
* Node Version: 12.19.0
* MongoDB Version: 3.2.22
* MongoDB-Speicher-Engine: wiredTiger
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? : Google Chrome 86.0.4240.193

It is installed on a virtuell server with 8 cpus and 16 GB memory. The free memory is 13 GB. The average system load shows 0.12, 0.10, 0.16

I think it is a database issue

**Comment by xet7** [comment]
Do you have websockets configured for Apache?
https://github.com/wekan/wekan/wiki/Apache

Does your server have SSD or NVME disk?

For my own use, I run Wekan demo server at bare metal server that has:
- [Caddy webserver](https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config) that is included in Snap, with CloudFlare SSL certs
- NVME disk that has is mounted as /var
- total 1562 users
- [Wekan Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)

**Comment by xet7** [comment]
For example Hetzner has bare metal servers https://www.hetzner.com/?country=en

**Comment by bbyszio** [comment]
Sorry for my late answer. Due to Corona, I didn't get to it earlier.
The Problem still exists. 

I would say that websockets are configured. 
The host-server have SAS HDDs. I could move the virtual server to a host with ssd hard disks.
Do you think it would be better to use caddy as a web server? Is it easy to switch from apache to caddy?

**Comment by xet7** [comment]
I do use Wekan Snap on my server, because it has automatic updates, and Caddy.
https://github.com/wekan/wekan-snap/wiki/Install

Difference between HDD and SSD is, that on HDD creating new Wekan board takes 5 minutes, and on SSD it takes 2 seconds.

**Comment by bbyszio** [comment]
I do use wekan Snap too. But with apache instead of caddy. I will try to move wekan to the server with SSD and then we will see what happens.:-) Thank you.

**Comment by xet7** [comment]
@bbyszio 

Did you test with SSD ?

Do you have any Global Webhooks at Admin Panel / Settings / Global Webhooks? Sending all Wekan boards actions to some webhook does slow down Wekan.

**Comment by bbyszio** [comment]
@xet7 Yes, I tested it with the SSD. It's gotten a little better. Mentioning users in the comments with @ still does not work in the large boards. And if about 15 users are on the board at the same time, it gets very slow.
The users log in via LDAP, I don't know if that's important.
I don't have global webhooks.

I also noticed yesterday that I can no longer export the largest board (in json). When importing, the error occurs that it is not a correct JSON.

In January I will try to move the system to a bare metal dedicated server.

**Comment by xet7** [comment]
@bbyszio 

Thanks for info. I'll think of some improvements.

**Comment by bbyszio** [comment]
@xet7 I forgot to say that there are a lot of rules (around 30) on the board for notifications, adding checklists and labels. The rules also automatically add members to the cards in certain situations. There are also 12 custom fields on all cards

**Comment by bbyszio** [comment]
@xet7 
I have now moved Wekan to a BareMetal server. Unfortunately, that hasn't changed the performance problems.
The CPU load (is slightly increased, increases in the course of the day), the memory load and the network traffic appear normal in the monitoring.
Could it be that every tab opened with Wekan creates a load on the system? Even if it is in the background and not working in the tab at all? I observe an increase in the CPU load, the more users have Wekan open in one or more tabs.

We now have 120 users and 3 boards with about 15 IFFT rules (each of these boards) and some custom fields. There are more boards in the system, but with less users and no IFFT rules. These other boards are slow too. Wekan need about 30 - 40 seconds to load. Sometimes opening a card needs the same time or longer. With opening the Settings it's the same.

**Comment by xet7** [comment]
@bbyszio 

Yes all tabs are active, see https://github.com/wekan/wekan/issues/718#issuecomment-561377824

I'll think how to fix.

**Comment by bbyszio** [comment]
Thank you! If getting commercial support can speed this up, please let me know how much it would cost and how much it could speed up.:-)

**Comment by xet7** [comment]
@bbyszio 

With enough funding, I could get to global scale, very fast speeds. If anyone can help providing funding for that, please email support@wekan.team

Currently I can not code at all, because I don't have funding to speed up solving some logistics problems. Manually solving those would take me some weeks or months.

**Comment by xet7** [comment]
Update: I figured out how to solve logistics problem manually, so I'm back to coding. Currently I'm going through GitHub issues and adding tags like bug, etc, and closing fixed issues.

I have not yet received email to support@wekan.team about funding to speed up.

**Comment by r4nc0r** [comment]
Hi,
how mich so you think it would host to Speed this up? We are also interested in this fix!

**Comment by xet7** [comment]
Amount depends on how much speedup is necessary.
- Small speedup: About 1000 euro. With this, I could look at Wekan not storing files at MongoDB database.
- Global scale: About 20 000 euro. But that is only possible with different kind of Wekan, that would need several different prototypes made by me to first test alternatives, and then use that for future Wekan development.

**Comment by bbyszio** [comment]
What do you mean with "Not storing files at MongoDb Database"? Do you mean attachments? This wouldn't help us, because we don't use attachments. Or do you mean the type how MongoDB stores its data? If it helps us, we can talk about the small speedup.

**Comment by xet7** [comment]
@bbyszio 

Yes, small speedup is about adding enough speedups to Wekan, so that Wekan works fast enough.

**Comment by xet7** [comment]
It is mainly about looking what parts of code are slow in Wekan, and fixing those parts.

**Comment by bbyszio** [comment]
@xet7 
Ok, that sounds good. I will discuss this in our Team. I'll send than an email to support@wekan.team with our request in the next two days.

**Comment by xet7** [comment]
@bbyszio 

Please try Wekan v5.02, is there any difference. Thanks!

**Comment by bbyszio** [comment]
I did the update last night and watched the system today. I have the impression that things have gotten a little better. But that could also be due to the fact that fewer people worked today. I'll keep watching that tomorrow.
It seems like the CPU load has decreased a bit.

**Comment by xet7** [comment]
@bbyszio 

I think there is no difference yet, because I had to revert that change I did previously, because some Wekan features did not work with that change. In future releases, I will make other changes to see do they improve speed, and does Wekan still work.

**Comment by xet7** [comment]
I will try some of these optimizations (only a start, not a complete list):

- [ ]  https://github.com/Urigo/awesome-meteor#performance
- [ ]  [Bundle Visualizer](https://forums.meteor.com/t/suggestions-for-making-my-app-load-faster/51919/3)
- [ ]  [montiapm](https://forums.meteor.com/t/tools-to-benchmark-and-profile-meteor-app/54111)

If someone finds Wekan is missing some index from MongoDB database, or other bottleneck, help and pull requests also welcome. Anyway, I will try as many optimizations as required to have enough speedups in Wekan.

**Comment by xet7** [comment]
@bbyszio

Please upgrade to Wekan v5.04 and check do you see any improvement in speed.

**Comment by bbyszio** [comment]
@xet7 
We have been watching this for 2 days now and I would say the system is a little faster and more fluid.
But it still takes a long time until a board is fully loaded and during this time it is of course not possible to work with the board. Since the users do not notice this because the cards are already displayed, they think they have not clicked correctly and click many more times, which later leads to confusion.

It also takes a long time until, for example, checklists are added to a card by rule. Sometimes up to 40 seconds for 3 checklists with 5 options each. During this time, it is not possible to work with the entire board, which again leads to confusion and wild clicking.

The same problem exists with multiselect actions.

I also noticed that if I only open a tab with a Wekan board (125 cards, 10 lists, 60 users), Chrome immediately consumes 400 MB more memory. If I switch to a smaller board, the memory consumption is reduced by half. If I switch back and forth between the two boards 3-4 times, Chrome uses about 2 GB of memory after the 3 or 4 times. Although I still only have one tab with one board.

We will continue to monitor this and I will contact you when I have new information. If there are more updates, please let me know.

**Comment by xet7** [comment]
@bbyszio 

Thanks a lot for detailed testing!

Yes there will be more updates, I will let you know when they can be tested.

**Comment by jrsupplee** [comment]
@xet7

> I also noticed that if I only open a tab with a Wekan board (125 cards, 10 lists, 60 users), Chrome immediately consumes 400 MB more memory. If I switch to a smaller board, the memory consumption is reduced by half. If I switch back and forth between the two boards 3-4 times, Chrome uses about 2 GB of memory after the 3 or 4 times. Although I still only have one tab with one board.

I am wondering if part of this can be solved by calling `stop()` somehow on the subscription from the board.  Or is that done automatically?

**Comment by jrsupplee** [comment]
At times I have noticed that there is too much data being sent between the server and the client.  There are fields being sent that are not necessary for display in some contexts.  This might be slowing things down, but it does not sound like the problem described here.  Might be worthwhile to review the `fields` option for some queries.

**Comment by jrsupplee** [comment]
@bbyszio 

Trying to understand why the board is so slow.  I have a big board that is not slow like yours, but I don't have 60 users.  Do you have a lot of comments or activity on the cards of the large board?

**Comment by xet7** [comment]
@jrsupplee 

For using subscriptions more like they should, subscriptions should only have `_id` that changes, and then use meteor method to get remaining data.

Slowness with bigger boards is, because Wekan loads most cards etc data to browserside minimongo, that is small mongodb implementation made with Javascript.

It could be possible to use Wekan without subscriptions and minimongo. For example, create minimal Meteor project:
 ```
 meteor create --minimal wekan
 ```
That would be without minimongo. For updating data, meteor methods would call to serverside functions. Although, that way could be work to get data saved and changes visible, when not using minimongo and subscriptions.

Also, with that [Bundle Visualizer](https://forums.meteor.com/t/suggestions-for-making-my-app-load-faster/51919/3) it can be seen that currently most dependencies are included to browserside Javascript bundle. For example, ExcelJS is a lot of Javascript. It could maybe be moved from `wekan/models/*import*` to `wekan/server/` so that it would only be used serverside, and use lazy loading to load it later.

Some of that slowness could be, that there is a lot of Rules. If all those rules run at every simultaneous users browserside, that could slow down Wekan. Alternative would be to move them to run serverside at `wekan/server/` if possible.

**Comment by xet7** [comment]
@jrsupplee 

Also one option is to change current substrictions to ligter version:
https://github.com/adtribute/pub-sub-lite

**Comment by xet7** [comment]
Oh, it seems I forgot to write details about that recent speed improvement:
https://github.com/wekan/wekan/commit/9db3c931161adfbeb6fc52d3e4cf621fb9a4955f

I'll try to remember what I did:

1) [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup) to view database, like Snap on 27019 or from `meteor --port 4000` then mongo at next port 4001

2) Enable [profiling level 2](https://docs.mongodb.com/manual/reference/method/db.setProfilingLevel/#db.setProfilingLevel) with:
```
db.setProfilingLevel(2)
```
(This is similar like in MySQL enabling slow_log)

3) Click Tools / Server Monitoring Tools / Database Profiler

4) I think there was `keysExamined` returning about 80000 rows for wekan database `presences` collection table, that had all Wekan logins since many years ago. So [in that code change](https://github.com/wekan/wekan/commit/9db3c931161adfbeb6fc52d3e4cf621fb9a4955f), that when Wekan is started or restarted (like when there is new updates), it deletes all older logins than 2 weeks.

5) Also in that improvement, I added index to `presences` collection `serverId` column that is most frequestly accessed.

6) This caused that query to Wekan database `presences.serverId` be so fast, that it was not visible at all at stats anymore.

But this kind of optimization is not good for all use cases, because for example activities etc data can not be deleted, it would lose activity history and comments on cards.

There are also other stats options at nosqlbooster menus.

Another way to optimize code is looking with browser performance logging tools, where time is spent, some example video here:
https://www.youtube.com/watch?v=oewDaISQpw0

Also there are Meteor developer tools extension for browser:
https://chrome.google.com/webstore/detail/meteor-devtools/ippapidnnboiophakmmhkdlchoccbgje

**Comment by xet7** [comment]
If possible, it would probably be fastest to optimize current Meteor based Wekan where needed. That would be keep all current features and fixes working, and keeping upcoming features and fixes in closer future.

Sure I do like exploring new and old tech, is there some better way to code Wekan, but usually someone reminds me that I should continue to maintain current Wekan that already has most things working.

Changing to some other tech would probably mean splitting Wekan to pieces and trying to fit pieces again together in some way, and fixing related corner cases again.

**Comment by bbyszio** [comment]
> At times I have noticed that there is too much data being sent between the server and the client. There are fields being sent that are not necessary for display in some contexts. This might be slowing things down, but it does not sound like the problem described here. Might be worthwhile to review the `fields` option for some queries.

To me that sounds like our problem. I noticed that Chrome uses 2 GB and more of RAM when Wekan hangs. For example, it looks to me as if the complete list of board members is loaded with every card. When I want to add a member to a card, this list can be quickly viewed and scrolled. Even if the rest of the system is very slow.

**Comment by bbyszio** [comment]
> @bbyszio
> 
> Trying to understand why the board is so slow. I have a big board that is not slow like yours, but I don't have 60 users. Do you have a lot of comments or activity on the cards of the large board?

We have a lot of activities, like moving cards to other lists, checking checkboxes or filling custom fields on some boards. But the system hangs also on small boards without custom fields and rules and only 4 or 5 users. 

Especially when I have such a small board open in one browser tab and a large board in another browser tab.

**Comment by bbyszio** [comment]
> @jrsupplee
> 
> For using subscriptions more like they should, subscriptions should only have `_id` that changes, and then use meteor method to get remaining data.
> 
> Slowness with bigger boards is, because Wekan loads most cards etc data to browserside minimongo, that is small mongodb implementation made with Javascript.
> 
> It could be possible to use Wekan without subscriptions and minimongo. For example, create minimal Meteor project:
> 
> ```
> meteor create --minimal wekan
> ```
> 
> That would be without minimongo. For updating data, meteor methods would call to serverside functions. Although, that way could be work to get data saved and changes visible, when not using minimongo and subscriptions.
> 
> Also, with that [Bundle Visualizer](https://forums.meteor.com/t/suggestions-for-making-my-app-load-faster/51919/3) it can be seen that currently most dependencies are included to browserside Javascript bundle. For example, ExcelJS is a lot of Javascript. It could maybe be moved from `wekan/models/*import*` to `wekan/server/` so that it would only be used serverside, and use lazy loading to load it later.
> 
> Some of that slowness could be, that there is a lot of Rules. If all those rules run at every simultaneous users browserside, that could slow down Wekan. Alternative would be to move them to run serverside at `wekan/server/` if possible.

@xet7 
I think it could really help, if more actions run serverside instead of clientside. 
Because, i can influence the configuration of the server, but not or only badly that of the clients.

**Comment by r4nc0r** [comment]
@bbyszio try enabling "hide system messages" in a card. This improved client side performance extremely for us in large boards. But every user has to set this for himself.

**Comment by xet7** [comment]
@bbyszio 

> I think it could really help, if more actions run serverside instead of clientside.
> Because, i can influence the configuration of the server, but not or only badly that of the clients.

Thanks for info! I'll continue coding my serverside prototype, to see how it would work.

**Comment by bbyszio** [comment]
> @bbyszio try enabling "hide system messages" in a card. This improved client side performance extremely for us in large boards. But every user has to set this for himself.

@r4nc0r 
Thanks, we'll try that. 
But that brings me to another issue. It would be good if some settings could be set centrally for all users by the admin. 

E.g. I would like to set that all users follow a board by default so that they receive notifications about changes to their cards. 
Or whether the system messages are hidden or shown by default.

But the performance is more important and for these points I will open a new issue when the opportunity arises. :-)

**Comment by bbyszio** [comment]
@xet7 

I've tried @ r4nc0r's tip "enabling" hide system messages "in a card" and the first impression is that it works much better.

If I now have 4 tabs with large boards, the memory consumption of Chrome is just under 1 GB instead of 1 GB with one board or 2 GB with 2 boards as before. 
You can also work more fluently at the moment. 

Is there a quick way I can make the "hide system messages" setting the default for everyone? If you want to see it, you can change it in a card.

I'll watch how it works from Monday, when there are more users on the system again.

**Comment by r4nc0r** [comment]
Good to hear, i think this setting helps because else if you open a card the complete history is loaded from the backend. If there was any server side paging and only last 10 history entries are shown it would be better? 

We would also love to set settings like these from the admin page :)

**Comment by xet7** [comment]
@bbyszio @r4nc0r 

Ok I will make to Admin Panel a button that will switch off system messages for everyone. If someone needs to enable it later, that someone can enable it.

**Comment by xet7** [comment]
Related:
https://blog.meteor.com/first-load-optimization-with-meteor-7cd896fa217d

**Comment by jrsupplee** [comment]
> @jrsupplee
> 
> Also one option is to change current subscriptions to lighter version:
> https://github.com/adtribute/pub-sub-lite

I do not use `subManager` in my code because it was causing weirdness.

**Comment by jrsupplee** [comment]
> For using subscriptions more like they should, subscriptions should only have `_id` that changes, and then use meteor method to get remaining data.

I disagree strongly with this.  Meteor is designed to send data to the client using subscriptions.

To pass data via method calls means that they will be passed as JSON  *not* as query sets.  This means the client gets only data.  So when you pass cards to the client they are not in `Card` objects.  So no accessing methods like `.board()` or `.list()`.  A lot of display code depends on having the database objects.

I explored this when I was writing the global search and coded it.  However, I quickly saw how unworkable it was as a solution.  So instead I added the `SessionData` table to pass the `cardId`s of the results from the query (the data being passed via subscription).

**Comment by xet7** [comment]
@jrsupplee 

Ok thanks!

**Comment by chrisi51** [comment]
@xet7  i can tell you now that it is still raising cpu comsumption over time as described in https://github.com/wekan/univention/issues/16 

![image](https://user-images.githubusercontent.com/2156760/112467262-206b8f80-8d67-11eb-9b81-29f403aabdae.png)

on 02-24 we've just rebootet our instance with installed version 4.95
at 03-11 we've updated to 5.05

so it may be better but its still raising the comsumption.

**Comment by xet7** [comment]
@chrisi51 

Thanks for info ! I will think how to fix.

**Comment by xet7** [comment]
@bbyszio @r4nc0r

In newest Wekan v5.08 try:
```
Admin Panel/Settings/Accounts: Hide system messages of all users. 
```

**Comment by bbyszio** [comment]
@xet7 I will do the update this night and then i'll try the new setting. Thanks. 

By the way. I've been watching the CPU usage on our server for the past few days and it looks the same for us as it did for @chrisi51. The utilization increases continuously.

**Comment by urmel1960** [comment]
Hi there 

After update to 5.08 - when I try this:

> 
> 
> @bbyszio @r4nc0r
> 
> In newest Wekan v5.08 try:
> 
> ```
> Admin Panel/Settings/Accounts: Hide system messages of all users. 
> ```

I do see

![grafik](https://user-images.githubusercontent.com/144102/112642630-cab8e500-8e43-11eb-8394-5abf6a22077b.png)

You can not see if it is set or not and click on the button gives only and always:
![grafik](https://user-images.githubusercontent.com/144102/112642990-27b49b00-8e44-11eb-91f5-48c3b8cf40d9.png)

Maybe I missed something ?

**Comment by xet7** [comment]
@urmel1960 

Yes, that hat does hide system messages of all users, that button was requested here https://github.com/wekan/wekan/issues/3345#issuecomment-803431998. Anyone, that needs to view system messages, can open any card and click `Show system messages` switch at bottom of card to show/hide. This does lower down CPU usage.

**Comment by xet7** [comment]
@urmel1960 

You see from this code change https://github.com/wekan/wekan/commit/a249ffc8054189d8e3db9b4c8f082cc7ce7dcb52 how I made it.

**Comment by urmel1960** [comment]
ok thanks - I see now how this should work.
Is there any way to revert this to default settings?

**Comment by xet7** [comment]
@urmel1960 

I have not added a way to make system settings visible for all users, I don't think it would make any sense, it would just slow down Wekan a lot.

Any user can toggle it for their own user if that user would like to see system messages https://github.com/wekan/wekan/issues/3345#issuecomment-808270078. It's not something hardcoded like other settings in that setting page.

**Comment by xet7** [comment]
It seems that after major speedup of `Hide all system messages` this has moved to related feature request #3681.
