### ISSUE TITLE
Markdown in card description broken?

### ISSUE THREAD

**Issue by avatar1024** [wekan/wekan#3347]
I have noticed that I cannot use markdown any more card description. I am not entirely sure since which version it is happening as Wekan updates automatically (I'm on Cloudron). 
I wonder if this is to do with the rich text editor that is now enable on card description.

**Comment by xet7** [comment]
Yes, see #3343

In some future Wekan version there will be either:
a) better rich text editor that works with markdown, and has emoji selector
b) both rich text editor and markdown editor selectable, so that markdown like emojis work

I'll leave this issue open while this is not fixed yet.

**Comment by avatar1024** [comment]
@xet7 Thank you for the reply. And sorry for missing the issue already reported (I only searched opened ones).

**Comment by xet7** [comment]
Moved to #3399
