### ISSUE TITLE
Weird Bug when selecting same 'add member' twice

### ISSUE THREAD

**Issue by nata-g** [wekan/wekan#335]
This happens when you are an admin and by mistake if you select your own name to add members, then you lose your admin privaleges. For example in the screenshot below, 'testaccount13' is the admin

![image](https://cloud.githubusercontent.com/assets/203255/10184622/ca376a0c-66f3-11e5-8a05-25b9df1414f0.png)

but when I add 'testaccount13' again by mistake then then I lose the admin priveleges and lose my ability to add any members and the board becomes unusable as there is no way to restore the 'admin' rights. 

![image](https://cloud.githubusercontent.com/assets/203255/10184670/5afc285c-66f4-11e5-8a82-3ca52c90bb61.png)

**Comment by mquandalle** [comment]
I can’t reproduce this in v0.10-rc4 (you can try at https://wekan.io/sign-in). I plan to refactor the whole allow and deny and mutation thing soon so this sort of bug would be less likely to happen.
