### ISSUE TITLE
does this do this basic thing? overflowed notes, cards under cards, responsive design

### ISSUE THREAD

**Issue by makethingsbetter** [wekan/wekan#3352]
is this able to add notes/cards where they would go under current notes ?

under current notes so all notes fit on the screen?

responsive design basically

new notes would overflow under current ones

does it do that

trello does that

**Comment by xet7** [comment]
@makethingsbetter 

Please record animgif about what you mean, and attach it to comment to this issue.

**Comment by makethingsbetter** [comment]
here https://chrome.google.com/webstore/detail/list-layouts-for-trello/aldklnbenbdgfgfbflalmlddkkndgnlc

**Comment by xet7** [comment]
@makethingsbetter 

Wekan already has Swimlanes integrated. In Wekan, it's possible to reorganize swimlanes with drag-drop, and set Swimlane/List/Card color.

You are linking to Chrome extension. So it's not even integrated to Trello at all.

**Comment by makethingsbetter** [comment]
if we download this thing, would it just work? 

https://github.com/wekan/wekan/releases

windows 10
