### ISSUE TITLE
Are you open to UX suggestions?

### ISSUE THREAD

**Issue by AgatheMametz** [wekan/wekan#3355]
Hi,
Not an bug/issue, but I just want to know if someone would be open to the idea of upgrading the UX of the card detail panel, which is currently a bit hard to use.

As a product designer I can come with a **Figma hand-off** but **won't be able to integrate it in the code.**

I saw the story with the Trello DMCA complaint, so I would make sure to make something different enough, between Trello, Airtable, Notion, Zenkit...

This is the first time I propose that to an open source project. I am curious of the reactions 👍

**Comment by xet7** [comment]
@AgatheMametz 

Next version of card details will be fullscreen like this, when I get it working well enough:
https://github.com/wekan/wekan/issues/1574#issuecomment-609095074

There is attached patch in that comment, but currently that new card details layout does not work well enough on all screen sizes, so it still needs some work.

You can add comment to this issue with attachment image of figma screenshot of possible improvements to that fullscreen example above.

There are many places in Wekan that would benefit from better UX suggestions, you are welcome to add new issues with screenshots about changes to anything. In some places Trello UX is worse than Wekan, is some places better. Some pages in Trello are very repetitive and have too much whitespace. In Wekan it's better that Add Board button is at top left, so it's not needed to scroll always to bottom of cards. Both Trello and Wekan UX changes all the time, with pull requests, new features, etc.

**Comment by xet7** [comment]
You can send new suggestions in new issues and pull requests.
