### ISSUE TITLE
Wekan shows duplicate card details

### ISSUE THREAD

**Issue by yaronbsmtx** [wekan/wekan#3356]
While browsing the roadmap board [here](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) and when displaying the details of a card, I noticed that these details appear in 2 duplicates:
![WekanIssue](https://user-images.githubusercontent.com/19538802/99390441-4e385780-28e1-11eb-89d4-e68cde1d59bc.png)
I am using Chrome 86 on Windows 10.

**Comment by xet7** [comment]
@yaronbsmtx 

This seems to be fixed in newest Wekan.
