### ISSUE TITLE
access to card  give an error

### ISSUE THREAD

**Issue by Havivw** [wekan/wekan#3358]
https://ip/b/iTuCbQAfqLsTWhzTf/sssss/d9EFby6upWCpD6MrZ

This site can’t be reached ip refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by mauroat** [comment]
I have the same problem. Please post the solution

**Comment by xet7** [comment]
@mauroat 

When root-url is set correctly, card does open correctly.

IP address can not have SSL certificate.

https://github.com/wekan/wekan/wiki/Settings

For example, local Wekan:
```
sudo snap set wekan root-url='http://localhost'
sudo snap set wekan port='80'
```

For local network, with IP address:
For example, local Wekan with computer IP address, for example:
```
# show ip address
ip address
# add settings
sudo snap set wekan root-url='http://192.168.0.200'
sudo snap set wekan port='80'
```
For HTTPS with Caddy:
https://github.com/wekan/wekan-snap/wiki/Install

Seeing logs:
```
sudo snap set wekan debug='true'
sudo snap logs wekan
```

Docker:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L158
```
docker-compose up -d
# seeing logs
docker logs wekan-app
docker logs wekan-db
```
