### ISSUE TITLE
Issue to integrate Wekan with WSO2 using Auth2-OIDC

### ISSUE THREAD

**Issue by Ketchup31** [wekan/wekan#3362]
![image](https://user-images.githubusercontent.com/15796167/99872142-f733ca80-2bdf-11eb-9d83-2d8dcdf60123.png)

Hello,

I try since few days to connect Wekan to WSO2 by using Auth2-OIDC without success.

I get always the following errors forl Wekan logs:

> XXX: getUserInfo response:  { sub: 'admin' }
XXX: userinfo: { sub: 'admin' }
XXX: serviceData: {
  id: undefined,
  username: undefined,
  fullname: undefined,
  accessToken: '<myAccessToken>',
  expiresAt: 1605951436256,
  email: undefined,
  refreshToken: '<myRefreshToken>'
}
XXX: profile: { name: undefined, email: undefined }
Exception while invoking method 'login' Error: Service data for service oidc must include id
    at AccountsServer.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1202:13)
    at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:55:21)
    at packages/accounts-base/accounts_server.js:475:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1309:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:473:22)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:533:31)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
>

In WSO2 logs everything seems normal.

And in Wekan login form:

![image](https://user-images.githubusercontent.com/15796167/99872297-23038000-2be1-11eb-83a6-1b6c5121c7bf.png)

Does anybody has any suggestion and/or guidelines in order to have a successful integration?

Thank you for your support.

**Comment by xet7** [comment]
@Ketchup31 

Settings should be similar like in this page:
https://github.com/wekan/wekan/wiki/Google-login

Important settings are, that these both are email:
```
snap set wekan oauth2-email-map='email'
snap set wekan oauth2-username-map='email'
```
With OIDC/OAuth2 Wekan can connect to many different kinds of OIDC/OAuth2 servers.

**Comment by xet7** [comment]
In your logs above is:
```
username: undefined,
email: undefined,
```
From your OAuth2 identity provider Wekan should get email address etc, but those are undefined. Is email address in some other field than email?

**Comment by Ketchup31** [comment]
Hello,
Thank you for your help. Much appreciated. In fact now, it is OK to login to Wekan via OAuth2, with my Admin account all is fine and in serviceData all fields are well filled with the right values and Wekan has the right data in the user profile. But with other account, serviceData values are not filled and considered as undefined, and data in Wekan user profile are empty.

Do you have any idea?

Is it mandatory to set these values (email):
```
snap set wekan oauth2-email-map='email'
snap set wekan oauth2-username-map='email'
``` 

Thank you.
```
XXX: getUserInfo response:  {
  sub: 'cd427c6e-f2f3-4d91-a872-569b61896c7c',
  id: 'cd427c6e-f2f3-4d91-a872-569b61896c7c',
  email: '<myEmailAddress>'
}
XXX: userinfo: {
  sub: 'cd427c6e-f2f3-4d91-a872-569b61896c7c',
  id: 'cd427c6e-f2f3-4d91-a872-569b61896c7c',
  email: '<myEmailAddress>'
}
XXX: serviceData: {
  id: 'cd427c6e-f2f3-4d91-a872-569b61896c7c',
  username: undefined,
  fullname: undefined,
  accessToken: '<accessToken>',
  expiresAt: 1605986980912,
  email: '<myEmailAddress>',
  refreshToken: 'c792395d-3add-377c-bf97-6020766916ff'
```

**Comment by xet7** [comment]
@Ketchup31

You could try this:
```
snap set wekan oauth2-email-map='userinfo.email'
snap set wekan oauth2-username-map='userinfo.email'
```
Some identity providers require workarounds, like in Oracle OIM sometimes email is empty, so it's copied from username field:
https://github.com/wekan/wekan/blob/master/packages/wekan-oidc/oidc_server.js#L48

In Auth0 case, some mapping is made at Auth0 service settings, to get correct values:
https://github.com/wekan/wekan/wiki/OAuth2#auth0

Point is to find on what fields email address is found.

Wekan OIDC/OAuth2 uses email address and password for login.

**Comment by xet7** [comment]
@Ketchup31 

Please upgrade to newest Wekan, and add comment to this issue, about do you have any problems anymore.

**Comment by Ketchup31** [comment]
@xet7 

Hi, Thank you and sorry for my long silence. I will give a try on next week-end and will be back to you asap.

**Comment by xet7** [comment]
@Ketchup31 

Thanks!

**Comment by Ketchup31** [comment]
Hello xet7,

OK after a long period of silence, I try again to connect to wsO2is v5.11.0. I can connect to WEKAN with only one user which is the admin of WEKAN. For him, WEKAN do not get any value from my IDP like username, email, etc...
Then when I try to connect with another one, I get the error below.

Any support would be welcome.

Thank you.


![image](https://user-images.githubusercontent.com/15796167/111065896-7d8c5900-84bc-11eb-8824-fa2313951686.png)


```
XXX: getToken response:  {
  access_token: 'c73541d5-efda-3929-8bb8-0e3f9d61c369',
  scope: 'email openid profile',
  id_token: 'eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoidjk2VGo2dGdVdzRka0s3WnFINFowZyIsImF1ZCI6WyJMMzZDNzNYWHU5cUsyb3NqY2ZfbURmT2NyZlVhIiwiIl0sImNfaGFzaCI6InlicE5wbDZvcDhqcDAybjU1SHlOeUEiLCJzdWIiOiJ0YXRhIiwibmJmIjoxNjE1NzE5MDE3LCJhenAiOiJMMzZDNzNYWHU5cUsyb3NqY2ZfbURmT2NyZlVhIiwiYW1yIjpbIkJhc2ljQXV0aGVudGljYXRvciJdLCJpc3MiOiJodHRwczpcL1wvaWRlbnRpdHkuZ2xhYi50YXNmLmZyXC9vYXV0aDJcL3Rva2VuIiwiZXhwIjoxNjE1NzIyNjE3LCJpYXQiOjE2MTU3MTkwMTd9.UzfNVYEbY-jqEka1j8XDX4HVViizcxrYDTY19hUPECjz_c2q4hADRgzi-s3dcUc4VFe98oO3i6UemBYSC6KV_hH7ac5xUuWN5CrU2kaDYIMLcFISbhn3bBRE4TqGPUFRFKuFRQ3eRGusrUhkiYPIhayLXVE05ryXZRqgj1Bg-uqgdNRIShUhE-uW-gAv08tL6qIjUmyUA4__jqnIzxPeANQV2rkB1KHXGhHlyCLUUMgmp3nWUmmlcbj1IdeUzQ2GX_WhnofQqWYLSmujRuD1S1QJXucEb3LQ4d9lasIl_onv_1WsIdv8kFDztVGQ66y4P_yQhBbiYMsUWU56DvFpbA',
  token_type: 'Bearer',
  expires_in: 697
}
XXX: register token: {
  access_token: 'c73541d5-efda-3929-8bb8-0e3f9d61c369',
  scope: 'email openid profile',
  id_token: 'eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoidjk2VGo2dGdVdzRka0s3WnFINFowZyIsImF1ZCI6WyJMMzZDNzNYWHU5cUsyb3NqY2ZfbURmT2NyZlVhIiwiIl0sImNfaGFzaCI6InlicE5wbDZvcDhqcDAybjU1SHlOeUEiLCJzdWIiOiJ0YXRhIiwibmJmIjoxNjE1NzE5MDE3LCJhenAiOiJMMzZDNzNYWHU5cUsyb3NqY2ZfbURmT2NyZlVhIiwiYW1yIjpbIkJhc2ljQXV0aGVudGljYXRvciJdLCJpc3MiOiJodHRwczpcL1wvaWRlbnRpdHkuZ2xhYi50YXNmLmZyXC9vYXV0aDJcL3Rva2VuIiwiZXhwIjoxNjE1NzIyNjE3LCJpYXQiOjE2MTU3MTkwMTd9.UzfNVYEbY-jqEka1j8XDX4HVViizcxrYDTY19hUPECjz_c2q4hADRgzi-s3dcUc4VFe98oO3i6UemBYSC6KV_hH7ac5xUuWN5CrU2kaDYIMLcFISbhn3bBRE4TqGPUFRFKuFRQ3eRGusrUhkiYPIhayLXVE05ryXZRqgj1Bg-uqgdNRIShUhE-uW-gAv08tL6qIjUmyUA4__jqnIzxPeANQV2rkB1KHXGhHlyCLUUMgmp3nWUmmlcbj1IdeUzQ2GX_WhnofQqWYLSmujRuD1S1QJXucEb3LQ4d9lasIl_onv_1WsIdv8kFDztVGQ66y4P_yQhBbiYMsUWU56DvFpbA',
  token_type: 'Bearer',
  expires_in: 697
}
XXX: getUserInfo response:  {
  name: 'tata',
  sub: 'tata',
  given_name: 'TataFirstName',
  family_name: 'TATALastName',
  email: 'myemail@mail.com'
}
XXX: userinfo: {
  name: 'tata',
  sub: 'tata',
  given_name: 'TataFirstName',
  family_name: 'TATALastName',
  email: 'myemail@mail.com'
}
XXX: serviceData: {
  id: 'tata',
  username: 'TATALastName',
  fullname: undefined,
  accessToken: 'c73541d5-efda-3929-8bb8-0e3f9d61c369',
  expiresAt: 1615719714184,
  email: 'myemail@mail.com'
}
XXX: profile: { name: undefined, email: 'myemail@mail.com' }
Exception while invoking method 'login' TypeError: Cannot read property 'split' of undefined
    at AccountsServer._onCreateUserHook (models/users.js:1045:10)
    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1124:23)
    at AccountsServer.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1300:22)
    at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:55:21)
    at packages/accounts-base/accounts_server.js:499:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1341:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:497:22)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:557:31)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by xet7** [comment]
@Ketchup31

In that `serviceData` you have `fullname: undefined`. Then at that error is:
```
Exception while invoking method 'login' TypeError: Cannot read property 'split' of undefined
    at AccountsServer._onCreateUserHook (models/users.js:1045:10)
```
So in that code https://github.com/wekan/wekan/blob/master/models/users.js#L1044-L1049
it tries to split `undefined` from where is space(s) in fullname with regex `s+`, and, well, that fullname is not even defined, so there is no space at all.

In theory, this could be fixed with checking for undefined:
```
const initials = '';

if (user.services.oidc.fullname !==  undefined) {
      initials = user.services.oidc.fullname
        .split(/\s+/)
        .reduce((memo, word) => {
          return memo + word[0];
        }, '')
        .toUpperCase();
};
```
Or if that fullname is defined, and does not have space, maybe take 2 first characters?

Or if fullname is not defined, take 1st character of given_name and 1st character of family_name to create initials? 

Alternatively, if you somewhere has fullname that has space, you could map something else to it:
https://github.com/wekan/wekan/wiki/OAuth2#4-add-wekan-settings
```
sudo snap set wekan oauth2-fullname-map='given_name'
```
Although checking for space would fail, if there is no space.

Anyway, if you figure out what would be good enough way to fix it, please send pull request to fix it, similarly like described at https://github.com/wekan/wekan/wiki/Emoji

**Comment by xet7** [comment]
Hmm, I think I'll add some code for this to Wekan.

**Comment by xet7** [comment]
Hmm, it seems I got lost, I need to drink more coffee and think about this sometime later.

**Comment by Ketchup31** [comment]
Ah ah ah ... :-) Thank you so much for your support. I will give a try this afternoon and let you know the result.

Enjoy your coffee !!!

**Comment by Ketchup31** [comment]
Hi @xet7 are you awake ?  ;-)

Thank to your feedback It seems to work now.  I setup the configuration in order to disallow the user to change their personal data like email, name etc... As they can do it via the IDP. I see that email update in IDP is not taken into account in WEKAN while I see in log files that the new email adress is well returned by my IDP to WEKAN. 

For me , and maybe I amw wrong,  I think that if we have an IDP to manage users personal data, this IDP should be the source of true for connected applications. 

May be I did something wrong, do you have any idea?

Thank you.

**Comment by xet7** [comment]
@Ketchup31 

Thanks, I woke up couple minutes ago, I did take a small nap.

1) IDP should be source of truth. There are some LDAP sync code at `wekan/packages` but I have not looked is there something similar for OIDC code at `wekan/packages`. If you see some data updated from IDP to Wekan, maybe it partially works, and more data could be added to be updated also? I think there is no code in Wekan that would update data from Wekan to IDP.

2) About private task not visible, maybe you mean #1122 that will receive funding in near future and I will implement it

**Comment by Ketchup31** [comment]
@xet7 
1) Yes may be to try to link WEKAN with LDAP could do the job. I will test it.
2) Glad to hear that.  More or less what we have in #1122 for me it was really simple with a single tag like "Private" and then all cards with this tag would be only seen by the owner.

I close the ticket as topics above are another story. 

Thank you again for your support !!!

**Comment by xet7** [comment]
@Ketchup31 

https://github.com/wekan/wekan/wiki/LDAP

**Comment by Ketchup31** [comment]
@xet7 

Thank you. I will have a look and do tests. I will keep you touch.
