### ISSUE TITLE
Search sidebar returns only 10 search results

### ISSUE THREAD

**Issue by kvacha13** [wekan/wekan#3364]
The Wekan 4.55 is installed on Ubuntu 20.04 deployed using snap.

1) I have one board with a default Swimlane, 4 lists and more than 150 cards. When I search for SearchKeyWord from "card/list titles, descriptions and custom fields", the search sidebar every time returns only 10 search results while actually there should be  more than 50. Is it limited to return just 10 results (tried several different search keywords and all of them returned only 10 results).

2) Is it possible in Wekan to filter cards by name containing some SearchKeyWord? 

Thank you.

**Comment by xet7** [comment]
@kvacha13 

Does new feature `Search All Boards` work for you?

**Comment by kvacha13** [comment]
Hi Lauri,

 

I am on wekan-snap, and there is no Search All Board Feature (or am I wrong?). 

 



 

But if I use a search tool, it lists only 10 results.

 



 

 

BR,

George

**Comment by xet7** [comment]
@kvacha13 

Please look at click right top your username => Search All Boards.

**Comment by kvacha13** [comment]
Cool…hidden Search feature…it works perfectly 😊

 

Thank you. Appreciate your help.

 

George
