### ISSUE TITLE
Helm chart 1.0.1 deletes mongodb contents

### ISSUE THREAD

**Issue by gesslein** [wekan/wekan#3375]
**Server Setup Information**:
Helm chart 1.0.0 upgraded to 1.0.1

**Problem description**:
When upgrading the helm chart you will loose your database (mongodb-replicaset) and start with a empty one (mongodb statefulset), due to changed mongodb chart dependency. I was able to use mongodump and mongorestore to manually move my data, but this upgrade needs to be documented and should probably be a MAJOR version change.

**Comment by xet7** [comment]
@gesslein  @jiangytcn 

How files at https://github.com/wekan/wekan/tree/master/helm/wekan could be improved? Can someone send pull request?

Recently there was this PR https://github.com/wekan/wekan/pull/3369 by @jiangytcn , but unfortunately I have not used helm charts at all, I don't know what to change.

**Comment by gesslein** [comment]
I'm going to prepare a PR that will keep using the "old" mongodb-replicaset as the default backend, and only use bitnami/mongodb if variables are set. Might take a few days to find the spare time, so anybody willing to start on this is more than welcome.

The upgrade instuctions could be to set variables for both databases, and some manual commands to export/import and then disable mongodb-replicaset which will change the MONGO_URL and remove the deployment.

A 2.x might remove mongodb-replicaset completely in the future.

**Comment by jiangytcn** [comment]
thanks @gesslein  that make sense. and for production deployment,  prefer to separate the deployment of  the mongo and wekan and give us much flexibility. thoughts ?

**Comment by xet7** [comment]
@gesslein @jiangytcn

Does this still happen?
