### ISSUE TITLE
#2250 Card loading animation issue is back

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#3379]
Hi

This issue is back in 4.56.0 I believe that this issue was actualy fixed in previous versions ( I skipped couple minor versions) so not sure when it was reintroduced again. Basically the issue happens when there are alot of cards in the column thta wont fit in the visible space. In this case (one in the video) I hhave over 50 cards in the column.

The original issue is located here https://github.com/wekan/wekan/issues/2250

Please see the video in the attached zip file to see what it looks like. As you see it goes away if the user slightly moves the scroll bar, until then the animation never stops.

[HiUUvUCfgg.zip](https://github.com/wekan/wekan/files/5627327/HiUUvUCfgg.zip)

I am using 

server: docker- compose  (image: quay.io/wekan/wekan  4.56.0  ) on Debian Testing, 

client: Chromium  84.0.4147 on Debian Testing

**Comment by Mystikal57** [comment]
hi,
Same problem for us with last update :-(
