### ISSUE TITLE
Helm Chart: Provide a way to include secrets into configuration

### ISSUE THREAD

**Issue by ThoreKr** [wekan/wekan#3381]
**Server Setup Information**: Helm Chart 1.0.1

**Problem description**:
We have a GitOps based workflow and try manage secrets via git as well (encrypted). 
With the wekan helm chart we are facing the issue to provide the list of environment variables for the "regular" configuration as well as the secret configuration (e.g., oidc secret.

With a dict merge strategy of two configmaps (the regular config and the secret) this ends up replacing the entire secret.

Can this somehow be resolved by either the possibility to provide the name of a secret to be used or providing a second list (e.g. secretEnv) which is handled with a similar templating logic but can be provided in a different way?

@jiangytcn what do you think about the second approach? I'd be happy to open a PR adding this possibility.

**Comment by xet7** [comment]
@ThoreKr 

Please add PR for any fixes. Thanks!

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/3382
