### ISSUE TITLE
Incorrect Path

### ISSUE THREAD

**Issue by pinghe** [wekan/wekan#3384]
4.56

```
GET https://mydomain/site.webmanifest 404
site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
A bad HTTP response code (404) was received when fetching the script.
test:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://mydomain/') with script ('https://mydomain/pwa-service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
```
It seems to refer to to paths in the domain root, whereas my root-url has the path https://mydomain/wekan/. 

I have Nginx providing SSL.

config wekan:
```
- ROOT_URL=https://mydomain/wekan/
```

**Comment by xet7** [comment]
@pinghe 

I do usually install Wekan to subdomain like https://boards.example.com, not sub-url. Some sub-url related issues have not been fixed yet. If you really need Wekan at sub-url, you can copy files from `wekan/public/*` to your website https://mydomain root directory, and adjust their content if needed.

**Comment by xet7** [comment]
I mean files here: https://github.com/wekan/wekan/tree/master/public

**Comment by pinghe** [comment]
thanks
