### ISSUE TITLE
csv exports fails  with custom fields.

### ISSUE THREAD

**Issue by joerntillmans** [wekan/wekan#3386]
##csv export fails when boards have custom fields

Hallo there,  we love this wekan and your awesome work! Since we work with csv export once and again, we have been following the csv export issues the last months and we were extremly happy that this feature was working again.  But there seems to be another issue with custom fields (another nice feature we appreciate!):

It seems like csv export fails when boards have custom fields in them.

When duplicating the board, custom fields get lost in the duplicate. But the board can then be exported correctly. I tried both Edge/chrome/firefox with same result. (json does work as far as I can see)
 I tried a testboard with a single card with customfields of the given param types (currency/text/number/dropdown) and the same error occurs.

Do I miss something importend and can you help us somehow?

Error is simply:
Wekan-Export-Server-Fehler

**Server Setup Information**:
I am afraid i don't now by now.

**Comment by xet7** [comment]
@joerntillmans 

Well, some funding for fixes could help? https://wekan.team/commercial-support/

Related https://github.com/wekan/wekan/issues/3173#issuecomment-713832834 #3336

**Comment by joerntillmans** [comment]
Sorry for letting you wait. Funding seems possible. We need same more time to check exacly what we would need. 

Am 08.12.2020 um 20:35 schrieb Lauri Ojansivu <notifications@github.com>:

﻿

@joerntillmans

Well, some funding for fixes could help? https://wekan.team/commercial-support/

Related #3173 (comment) #3336

**Comment by xet7** [comment]
@joerntillmans 

Yes, please take your time. When you have checked what you need, you can send details to support@wekan.team 

Please note that these emails from GitHub issues are public, visible at https://github.com/wekan/wekan/issues/3386 . Emails to support@wekan.team are private.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
