### ISSUE TITLE
wekan fails to build on fresh ubuntu 20.04.1 LTS (using rebuild-wekan script) - not in meteor project...

### ISSUE THREAD

**Issue by CoolDreamZ** [wekan/wekan#3391]
## Issue
**Server Setup Information**

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: **Yes**
* Did you test in newest Wekan?: **Yes v4.58**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? **DId not get that far!**
* Wekan version: **v4.58**
* If this is about old version of Wekan, what upgrade problem you have?: **N/A**
* Operating System: **Ubuntu 20.04.1 LTS**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **source**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none, did not get that far
* Node Version: **v12.20.0**
* MongoDB Version: **v3.6.9**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Firefox 83.0**

**Problem description**

Steps to reproduce (logged in as root):
* setup fresh ubuntu installation and create wekan user with sudo privilege
* apt install mongodb-server
* curl -LO https://github.com/wekan/wekan/archive/v4.58.tar.gz
* tar -xf v4.58.tar.gz
* cd wekan-4.58
* rsync -a * /home/wekan/
* cd /home/wekan
* chown -R wekan:wekan .
* su wekan
* ./rebuild-wekan.sh
* Choose Option 1 (install dependencies) - completed OK
* ./rebuild-wekan.sh
* Choose Option 2 (build) - **FAILS with "build: You're not in a Meteor project directory."**
* ./rebuild-wekan.sh
* Choose Option 4 (run on current ip:4000) - **FAILS (does not parse IP address correctly - minor BUG)**
* ./rebuild-wekan.sh
* Choose Option 5 (run on custom address/port) - **FAILS with "run: You're not in a Meteor project directory."**

See screenshots below:

<img width="807" alt="Screenshot 2020-12-10 at 13 20 27" src="https://user-images.githubusercontent.com/70951446/101778178-6d469580-3aeb-11eb-997b-7baf37c0f1da.png">

<img width="663" alt="Screenshot 2020-12-10 at 13 22 02" src="https://user-images.githubusercontent.com/70951446/101778303-9830e980-3aeb-11eb-8d53-84791ea30605.png">

**Comment by CoolDreamZ** [comment]
Checking back o the session I see it also failed to build, I did not notice that the first time as the build phase appeared to complete ok. Here is the relevant section:

<img width="657" alt="Screenshot 2020-12-10 at 13 40 20" src="https://user-images.githubusercontent.com/70951446/101779668-79cbed80-3aed-11eb-898d-edcb541463b0.png">

**Comment by xet7** [comment]
Would this help? https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

I build Wekan various versions on Debian 10 x64, Ubuntu 20.10 x64, Ubuntu 20.04 arm64, RHEL 8 s390x etc. For me building works.

**Comment by CoolDreamZ** [comment]
Thanks, using a git clone (rather than the tarball) means I now seem to be able to build OK. However the application will not run. I have tried all 3 options provided by rebuild-wekan.sh without success. Here is the whole session with the steps taken  annotated with '********* STEP X .....'

[wekan session.txt](https://github.com/wekan/wekan/files/5683086/wekan.session.txt)

**Comment by CoolDreamZ** [comment]
Ah, digging deeper I find this was caused by an oom on the hypervisor (I am running wekan in an LXC). Increasing the RAM available to the container from 1Gb to 2Gb fixed the issue and it now runs OK.

This issue can be closed.
