### ISSUE TITLE
Bug: When adding items to a checklist, using 1., 2., etc it will display as 1., 1., etc.

### ISSUE THREAD

**Issue by Mythotical** [wekan/wekan#3398]
### Server Setup Information

* Did you test in newest Wekan?: **Yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? **Yes**
* Wekan version: **4.60.0**
* Operating System: **CentOS 7**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **Docker and Docker-Compose**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Apache**
* Node Version: **12.20.0**
* MongoDB Version: **4.2.10**
* Wekan only works on the newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Chrome 87.0.4280.88**

### Problem description
- When adding items to a checklist, for me it is a Bug report card where individuals would use the Steps to Reproduce checklist to give steps by adding 1. Example, 2. Then this example, 3. Finally this example but instead it becomes 1. Example, 1. Then this example, 1. Finally this example.

### Steps to Reproduce
1. Create a card normally or a card template.
2. Add a checklist labeled whatever you want.
3. Type in 1. This is an example.
![checklist-step-becomes-1](https://user-images.githubusercontent.com/7572268/102719064-60772e00-42b1-11eb-901b-c466a7367ec9.png)

4. Click Save or press Enter to go to the next item.
5. Type in 2. Then this example.
![checklist-step-2](https://user-images.githubusercontent.com/7572268/102719070-6967ff80-42b1-11eb-96e0-21afa0c21140.png)

6. Click Save or press Enter to go to the next item.
7. Type in 3. Finally this example.
![checklist-step-3](https://user-images.githubusercontent.com/7572268/102719073-6e2cb380-42b1-11eb-9fd9-cf98f4de363a.png)

8. Click Save or press Enter.
9. All items will display with 1. instead of the numbers given.
![checklist-step-3-becomes-1](https://user-images.githubusercontent.com/7572268/102719078-72f16780-42b1-11eb-9896-8aefc2deee18.png)

### What it should look like
![what-it-should-look-like](https://user-images.githubusercontent.com/7572268/102719163-088cf700-42b2-11eb-92cb-a3dce3996526.png)

### Inspect->Console
- *In webbrowser, what does show Right Click / Inspect / Console? Chrome shows more detailed info than Firefox.*
There is no errors, warnings, or anything that would suggest a possible issue.

### Logs
- *If using Docker, what does show command `sudo docker logs wekan-app`? Please anonymize logs.*
[docker-logs.zip](https://github.com/wekan/wekan/files/5721220/docker-logs.zip)

**Comment by xet7** [comment]
This is because wekan supports markdown and [Emoji](https://github.com/wekan/wekan/wiki/Emoji] at input fields like checklist items. Markdown support thinks it's first element of ordered list.

Workaroud is to escape dot, by adding backslash before dot:
```
3\.
```
For markdown, Wekan uses markdown-it. This issue there is https://github.com/markdown-it/markdown-it/issues/377 so to fix this, it would require patching markdown-it and maintaining forked version. Is that really necessary?

**Comment by helioguardabaxo** [comment]
It's working fine on latest version:
![image](https://github.com/wekan/wekan/assets/24301085/a442b8bf-9b0b-4ea1-9791-37155969337a)
