### ISSUE TITLE
Fix Summernote editor

### ISSUE THREAD

**Issue by Mythotical** [wekan/wekan#3399]
I have just started using Reddit as a regular user but when creating posts I noticed they use Fancy Pants editor which I feel would be great to use in the card Description area to save on having to remember or even lookup markdown to properly display my description as I want.

I don't know how easy this would be or if it would require recoding the whole card but I'm willing to look into doing the work then submitting it to be merged if @xet7 doesn't have time but I'm looking to see how many others would enjoy using the Fancy Pants editor.

Anyway, here are some screenshots of it being used on Reddit.

**Regular Markdown Editor**
![normal-markdown-editor](https://user-images.githubusercontent.com/7572268/102722444-c15d3100-42c6-11eb-9dff-0381aaabc45c.png)

**Fancy Pants Editor**
![fancy-pants-editor](https://user-images.githubusercontent.com/7572268/102722453-cae69900-42c6-11eb-8eb7-653e3b39238e.png)

I think this could save some time for users adding cards especially if they are reporting a bug.

**Comment by xet7** [comment]
What is URL for fancy pants editor source code?

**Comment by xet7** [comment]
Currently Wekan has [Summernote](https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+summernote) [editor](https://summernote.org/) in card description and comments. In Wekan Snap, you can enable it with:
```
sudo snap set wekan richer-card-comment-editor='true'
```
But, Summernote is very buggy, and it produces HTML. Not markdown.

Some have asked for WYSIWYG editor that has clickable emoji selector. I did try some from https://atmospherejs.com and https://npmjs.com , but I did not get any of them yet working with Wekan yet. It would be very welcome to replace Summernote with other editor that saves as markdown and has clickable emoji selector.

[Here at Stackoverflow](https://stackoverflow.com/questions/54227850/which-markdown-editor-does-reddit-use) someone asked about editor Reddit uses, is there similar Open Source one, and somebody suggested [react-rte](https://github.com/sstur/react-rte) but it seems it does not have emoji selector.

**Comment by xet7** [comment]
Also, in that replacement markdown editor with emoji selector, it would help that source code would be MIT/BSD/ISD or similar Open Source license. I can not add those emoji selectors that do no have any license, because those are propietary, I can not redistribute them. It would also be nice that it does not have GPL-like license, because then I can only use it in [Wekan GPL Gantt](https://github.com/wekan/wekan-gantt-gpl) version, not normal MIT-licensed Wekan version. The only reason there is [separate Wekan Gantt GPL Snap and Docker version](https://github.com/wekan/wekan/issues/2870#issuecomment-721364824) is because that Gantt chart component has GPL license.

**Comment by xet7** [comment]
GPL is very nice license, but unfortunately in some workplaces using GPL licensed code is forbidden by company management.

**Comment by Mythotical** [comment]
Well as it seems fancy pants editor is owned by Reddit there is no source I found for it but I'll do some digging around then post suggestions back here.

**Comment by Mythotical** [comment]
@xet7 
Here are some I found on GitHub.
[Toast UI Editor](https://github.com/nhn/tui.editor) - This is a WYSIWYG editor but utilizes markdown. ``MIT LICENSE``
[Markdown Plus](https://github.com/tylingsoft/markdown-plus) - Same as above but nearly all written in JS. ``MIT LICENSE``
[Rich Markdown Editor](https://github.com/outline/rich-markdown-editor) - Not sure as there are no screenshots. ``BSD LICENSE``
[Markdown-It Editor](https://github.com/k55k32/markdown-it-editor) - No idea about the license on this one.
[Markdown WYSIWYG Editor](https://github.com/Alyw234237/md-wysiwyg-editor) - No license listed for this one, but I'm not even sure it will work with Wekan.
[Simditor](https://github.com/mycolorway/simditor) - This one comes with an emoji extension you can include with it. 

That is all I found worth mentioning. Merry Christmas and Happy New Year.

**Comment by Mythotical** [comment]
@xet7 
Have you had a chance to look over the suggested editors above? If so, is there one you like that I can possibly help out by implementing it to save you some time?

**Comment by xet7** [comment]
@Mythotical 

Maybe these:

- [Toast UI editor](https://github.com/nhn/tui.editor) with Plain Javascript. Inserting images should be disabled, having them in attachments is better, I think. For plugins, you can add those that you get working.
- https://emoji-button.js.org with unicode emoji and Plain Javascript.

Most of current code is here:
- https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+richer
- https://github.com/wekan/wekan/blob/master/client/components/main/editor.jade
- https://github.com/wekan/wekan/blob/master/client/components/main/editor.js
- https://github.com/wekan/wekan/tree/master/packages/markdown
- https://github.com/wekan/wekan/blob/master/.meteor/packages#L91
- https://github.com/wekan/wekan/blob/master/.meteor/packages#L94
- https://github.com/wekan/wekan/blob/master/.meteor/versions#L59
- https://github.com/wekan/wekan/blob/master/.meteor/versions#L241

Thanks!

**Comment by Mythotical** [comment]
@xet7 
Thanks for that info. I'll look into it once I get done setting up Wekan on a local development environment on my computer.

**Comment by xet7** [comment]
@Mythotical 

Here is how to fork Wekan, build it, make changes, and make pull request:
- https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin
- https://github.com/wekan/wekan/wiki/Directory-Structure
- https://github.com/wekan/wekan/wiki/Developer-Documentation

**Comment by Mythotical** [comment]
@xet7 
Awesome thanks for that information as well. Will help me a lot.

**Comment by Mythotical** [comment]
I'm officially on top of implementing this new editor. Will do a PR when ready for review.

**Comment by xet7** [comment]
@Mythotical 

Thanks!

**Comment by basketball00011** [comment]
Love this change. Thanks everyone!

**Comment by ryanMushy** [comment]
Removing images from the description field will BREAK all cards which have an image in the description field. The desired outcome is to allow wekan to update without breaking my existing boards/cards. However, after this update, all of my cards are now filled with 5,000 lines of text for every image which used to be attached. This makes editing the text field impossible. But yay emojis right?

This "fix" was clearly not tested.

**Comment by ryanMushy** [comment]
@Mythotical is no longer working on this issue according to his dev activity 

![image](https://user-images.githubusercontent.com/77740971/113196667-9f097680-9218-11eb-8f8f-fbf3adf1092d.png)

**Comment by ryanMushy** [comment]
@xet7 
Since I can not sign up for Pull Request permission: https://github.com/wekan/wekan/issues/3710

Here is yet another fix for summernote inside of wekan

![image](https://user-images.githubusercontent.com/77740971/114478904-2f9a6c00-9bb4-11eb-9730-573cb14a8ad1.png)

the same line was added to both .onDestroyed()  methods.

**Comment by xet7** [comment]
@ryanMushy 

I deleted clahub requirement, please try again to add pull request, if you did not add pull request yet.

**Comment by ryanMushy** [comment]
@xet7 are there any outstanding bugs that relate to summernote?

The last feature i want to add is to keep text/image formatting when summernote editor is not visible. But I fear this change may upset some users...

**Comment by xet7** [comment]
@ryanMushy 

You can check are these related in any way, and what is possible for you to fix:

1) When adding markdown to Summernote, it is not rendered correctly, if it not added to beginning on text.

2) Summernote should save as markdown, not HTML

3) Too long links could cause issues https://github.com/wekan/wekan/issues/1389 

4) Checkbox behaviour https://github.com/wekan/wekan/issues/2419

5) Markdown attachments not yet editable https://github.com/wekan/wekan/issues/595

6) Whitespace trimming breaks Markdown code block indentation https://github.com/wekan/wekan/issues/1288

7) Custom URL schemes do not work yet, there is link button, should there be custom URL scheme button(s) too? https://github.com/wekan/wekan/issues/3218

8) Checklist item numbering behaviour https://github.com/wekan/wekan/issues/3398

9) Summernote does not have emoji picker yet https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v516-2021-04-01-wekan-release

**Comment by xet7** [comment]
> The last feature i want to add is to keep text/image formatting when summernote editor is not visible. But I fear this change may upset some users...

Currently there is setting https://github.com/wekan/wekan/blob/master/docker-compose.yml#L238 
```
- RICHER_CARD_COMMENT_EDITOR=false
```
In general:
- Those that use summernote, would be upset if summernote is not enabled
- Those that do not use summernote, would be upset if summernote would be enabled, and adding plain markdown would not work.

The way to have both available at the same time, would be for example, that there could be tabs (like in Wekan board archive card/list/swimlane tabs) for markdown and summernote modes, and each user could select which one to use.

**Comment by xet7** [comment]
Tabs here https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarArchives.jade#L3-L4
