### ISSUE TITLE
Mobile miniscreen: Drag handle not visible in long checklist item text.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3402]
Hi,
there is bug:
- Mobile miniscreen: Drag handle not visible in long checklist item text.

I'll try to fix this in near future.

**Comment by mfilser** [comment]
@xet7 
Thank you very much for the fix, i didn't recognized it until i saw this issue.

I had a look at the latest version 4.67 how it look's like now.
Is the ```padding-top: 6px``` necessary for fixing it or is only ```padding-right: 20px``` necessary.?
The arrows now looks like they are a bit between the checklist items.
![grafik](https://user-images.githubusercontent.com/13166201/103212319-bc256500-490a-11eb-8473-416fb2564263.png)

I added a green line to see it better.

**Comment by xet7** [comment]
@mfilser 

It depends how easy it is to drag items on miniscreen on Android Chrome and Android Firefox. You can test and send improvements as pull requests.

Another problem currently is, that it's hard to click Swimlane hamburger menu on mobile, it should be more to right from current place.

**Comment by xet7** [comment]
Also, currently Admin Panel is not fully visible in miniscreen.

**Comment by mfilser** [comment]
> Another problem currently is, that it's hard to click Swimlane hamburger menu on mobile, it should be more to right from current place.

I must first have a look / test it. Maybe you have a screenshot?

> Also, currently Admin Panel is not fully visible in miniscreen.

Yes, that's right. I add it to my todo list.

Also the notification icon overlaps with the hamburger icon if you have notifications (at mobile view). That's what i also want to fix...

**Comment by xet7** [comment]
@mfilser 

> > Another problem currently is, that it's hard to click Swimlane hamburger menu on mobile, it should be more to right from current place.
> 
> I must first have a look / test it. Maybe you have a screenshot?

I don't have screenshot yet, but anyway, when I run Wekan in development mode at local network with:
```
cd wekan

# build once
./rebuild-wekan.sh

WITH_API=true ROOT_URL=http://192.168.0.100:4000 meteor --port 4000
```
And then browse to http://192.168.0.100:4000 on mobile phone Chrome or Firefox, trying to click ☰ (Swimlane hamburger menu that has change swimlane color etc) with finger is very difficult, because + and ☰ are too close to each other:
```
_____________________________________________
+  ☰               Swimlane name
_____________________________________________
Card 1...
```

Also, it would need testing is it possible to click every menu on small mobile phone screen, or are also other menus hard to click.
