### ISSUE TITLE
Feature Request: Usergroups/Multiple Roles

### ISSUE THREAD

**Issue by Mythotical** [wekan/wekan#3404]
With how things work today, being able to only assign Admin role to a user or they are just a normal user is something that isn't big. What I suggest is a usergroup system or allowing us to add more roles where we can have User, Viewer, Mod, Admin, etc. This way if I don't want to assign the admin role to users just so they can access my private board(s) I can set up a new role with permissions to allow viewing and posting on private board(s).

This process could have its own page in the Admin Panel. Don't list Admin role, leave that how it is but anyone who signs up is a User or whatever the default role is we set up. Then add a new field to the users edit form that is a dropdown to change their role from User to something else we created.

I know this is probably going to be a big request since things would have to be changed in the code to use if statements based on permissions so I don't expect it anytime soon. I may try to add this in myself, if I succeed then I'll do a pull request to submit the changes.

**Comment by xet7** [comment]
Moved to #3022
