### ISSUE TITLE
Is it possible to use 2 node mode?

### ISSUE THREAD

**Issue by dvolozhinok** [wekan/wekan#3406]
Hello, dear Wekan developers!

Sorry, don't know where to ask a question about this system. Please don't be angry at me if I write not to the appropriate place.
Please tell me, how to run Wekan as HA cluster with more than one node so I can switch to another Wekan node when the first server will be unavailable? Is it possible by software?

**Comment by xet7** [comment]
Yes. Wekan is made with Meteor web framework. You can register to [Meteor Impact 2020 event](https://impact.meteor.com) and watch [this talk](https://impact.meteor.com/meetings/virtual/He7TTgNYzny87Giaj), they run Meteor in global scale (their own Meteor app, not Wekan). They have some additional monitoring added to [Meteor hosting](https://www.meteor.com/hosting).

For MongoDB database, it's possible to alternatively use [MongoDB hosting](https://www.mongodb.com/cloud/atlas).

Some more info at [Scaling wiki page](https://github.com/wekan/wekan/wiki/Scaling).

For my own use, I prefer to run Wekan on bare metal server with single Wekan Snap version and NVME disk, at https://packet.com or https://hetzner.de/en/ , it has been fast enough, I have not tried to do HA setup.

**Comment by xet7** [comment]
Hmm, I think you did ask only for 2 node setup.

For example, if you use docker-compose.yml from https://github.com/wekan/wekan , or Source bundle for any x64/arm64/s390/ppc64le server from https://github.com/wekan/wekan/Raspberry-Pi , you can have:
- Wekan running on 2 frontend servers and one backend MongoDB server (or MongoDB cluster)
- Have Wekan MONGO_URL pointing to your same database server, on both 2 frontend servers

Does that answer your question?

**Comment by dvolozhinok** [comment]
>     * Have Wekan MONGO_URL pointing to your same database server, on both 2 frontend servers
Hello, is it possible to run 2 MongoDB servers and 2 frontend servers?

**Comment by xet7** [comment]
@dvolozhinok 

https://docs.mongodb.com/manual/replication/
