### ISSUE TITLE
Moving Cards to empty Swimlanes

### ISSUE THREAD

**Issue by solunix** [wekan/wekan#3415]
## Moving Cards to empty Swimlanes not working via Drag and Drop

**Server Setup Information**:

* Wekan version: 4.56

**Problem description**:
- The Drop-Box appears only first time in another empty lane, dragging over a third one no more else. Working only, when at least one Box is already in the Column or Row
![moving-cards-bug](https://user-images.githubusercontent.com/5192607/103537626-066f8e80-4e95-11eb-8728-da011e08f7ed.gif)

**Comment by xet7** [comment]
@solunix 

Please upgrade to newest Wekan and try again.

**Comment by pmeidl66** [comment]
I'm running v4.95 (latest), and the problem persists. it looks like only the last (bottom) swimlane is affected (other empty swimlanes work as expected).

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4883

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4883
