### ISSUE TITLE
Color picker of lists is empty

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3418]
I use the following configuration:

Wekan 4.70.0 (in container)
Meteor 1.12
Node 12.20.1

WIth this, in Chromium and FIrefox (both running under Ubuntu), the colour picker for changing the colour of lists is just a white (i.e. empty) pop-up. Hovering with the mouse over it, I can see changes in the mouse cursor, and I can even select a colour, but I do so blindly.

**Comment by xet7** [comment]
@bronger

What theme you are using at ☰  => ⚙ => Change Color ?

**Comment by xet7** [comment]
@bronger 

Please add screenshot.

**Comment by xet7** [comment]
@bronger 

What container are you using? Docker, LXC, or something else?

**Comment by xet7** [comment]
@bronger 

Did you use Docker container from https://quay.io/wekan/wekan , or did you build container yourself?

**Comment by bronger** [comment]
> @bronger
> 
> Please add screenshot.

![image](https://user-images.githubusercontent.com/2184938/103696013-eb3c7600-4f9d-11eb-8908-353eee389f8c.png)

I use the image `wekanteam/wekan` on hub.docker.com. It runs on Kubernetes, but not K8s 1.20, so I suspect it still uses the Docker engine.

**Comment by xet7** [comment]
@bronger 

It seems only Docker version is broken. At Snap and Sandstorm it shows all colors.

Problem is, also Univention uses Docker version of Wekan. And choosing color from all white is very, very hard.

I did not see any errors at browser inspect console.

At Docker container, I did see these errors:
```
$ docker logs wekan-app
WARNING: failed loading: 
Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at packages/wekan-oidc.js:30:14
    at packages/wekan-oidc.js:277:4
    at packages/wekan-oidc.js:285:3
    at /build/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /build/programs/server/boot.js:226:21
    at /build/programs/server/boot.js:464:7
    at Function.run (/build/programs/server/profile.js:280:14)
    at /build/programs/server/boot.js:463:13 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
```
There are various ways to fix this. I'll think.

**Comment by bronger** [comment]
Yes, I also see this error message.

**Comment by xet7** [comment]
That code in wekan-oidc.js is this:
```
./packages/wekan-oidc/oidc_server.js:   httpCa = fs.readFileSync(process.env.OAUTH2_CA_CERT);
```
So it seems it is trying to read file, but because that environment variable is wrong or empty, it does fail. I'll try to add better check for environment variable setting length, so that it is required to be longer than 0.

**Comment by xet7** [comment]
Hmm, it seems that I fixed that error message in Docker, but it did not fix this Color picker yet. I'll think and try something else.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/commit/4649553c5e84c8f81b3b9b1c371e1e79f397a57a
