### ISSUE TITLE
Teams don't save when creating a new Team

### ISSUE THREAD

**Issue by Mythotical** [wekan/wekan#3420]
## Issue

When creating a new team through the Admin Panel it does not save. It acts like it saved the team but when you go to Team page there is no new team.

**Server Setup Information**:

* Did you test in newest Wekan?: **Yes**
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? **Yes**
* Wekan version: **4.70**
* Operating System: **CentOS 7 64-bit**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **Docker**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Apache**
* Node Version: **12.20.1**
* MongoDB Version: **4.2.10**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? **Google Chrome Version 87.0.4280.141**

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek* 
![Teams](https://user-images.githubusercontent.com/7572268/103995044-80399d80-515d-11eb-9387-4ec5a52790d4.gif)

**How it should look I guess:**
![Teams](https://user-images.githubusercontent.com/7572268/103997017-31d9ce00-5160-11eb-82ab-e96a061eb207.png)

- *Explain steps how to reproduce:* Go to Admin Panel > Click on Teams > Click New > Fill out all fields > Click Save > Brief second you see "You are not authorized to view this page." 
![https-roadmap-goblin-technologies-com-people](https://user-images.githubusercontent.com/7572268/103995507-33a29200-515e-11eb-9d9c-723c2d8c7a1e.png)

- *In webbrowser, what does show Right Click / Inspect / Console ?* **Nothing related to the new Team being saved.**
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file* **Unable to obtain logs. Receive the error message below.**

> [wekan]# docker logs wekan-app
> WARNING: failed loading:
> Error: ENOENT: no such file or directory, open
>     at Object.openSync (fs.js:462:3)
>     at Object.readFileSync (fs.js:364:35)
>     at packages/wekan-oidc.js:30:14
>     at packages/wekan-oidc.js:277:4
>     at packages/wekan-oidc.js:285:3
>     at /build/programs/server/boot.js:401:38
>     at Array.forEach (<anonymous>)
>     at /build/programs/server/boot.js:226:21
>     at /build/programs/server/boot.js:464:7
>     at Function.run (/build/programs/server/profile.js:280:14)
>     at /build/programs/server/boot.js:463:13 {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT'
> }
> Presence started serverId=2KgaSScrFFDyyTbni
> {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Fri Jan 08 2021 08:28:07 GMT+0000 (Coordinated Universal Time)","time":{"$date":1610094487425},"level":"info"}
> (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by xet7** [comment]
Yes, code to save Team etc is not written yet. That feature is still In Progress, it's not ready yet.

That Docker error about not existing file is already fixes, and will be in next Wekan release.

Moved to #802

**Comment by Mythotical** [comment]
@xet7 
Ah ok that makes sense. LOL
