### ISSUE TITLE
Export menu and member settings at Sandstorm Wekan

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3423]
Moved to here from #3377

From @PizzaProgram 

> Export, when board is open:
> 
>     * Click: ☰ => gear => Board Settings => Export.

Sadly, there is no EXPORT possibility. 
(Fresh v4.7 install, first time use. Created 100 cards, do not want to loose...)
![kép](https://user-images.githubusercontent.com/26026089/104103340-d57ec780-52a1-11eb-9e41-d939226eda4b.png)

Also, it is not possible to Add second user to a board.
1.
![kép](https://user-images.githubusercontent.com/26026089/104103436-66ee3980-52a2-11eb-8040-5184f4a02033.png)
2.
Selecting Sandstorm member, Clicking connect...
![kép](https://user-images.githubusercontent.com/26026089/104103483-a3ba3080-52a2-11eb-8806-769d1c48e280.png)

Nothing happens.

PS: 
- We are both Admins
- none of us can see Export menu
- on none of the Boards

**Comment by xet7** [comment]
For next Wekan release, I'll try to make Export menu visible on Wekan Sandstorm version.

**Comment by PizzaProgram** [comment]
Maybe this error has something to do with the problem too?
`TypeError: Meteor.user() is null`

**Comment by xet7** [comment]
@PizzaProgram 

It could, because user permissions are different at Sandstorm, than on other Wekan versions.

**Comment by xet7** [comment]
@PizzaProgram 

You can:
a) Wait for @ocdtrekkie to check and release newest Wekan v4.72 as official update
b) If you have backups of your /opt/sandstorm and downloaded all your grains as .zip files, you can install newest Wekan v4.72 immediately [from experimental](https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h?experimental=true)

Newest Wekan has export menu visible at Wekan Sandstorm version.

**Comment by xet7** [comment]
@PizzaProgram 

If you are in a hurry with board member permissions, you can:
1. Export your Sandstorm Wekan boards to JSON
2. Install [Wekan Snap version](https://github.com/wekan/wekan-snap/wiki/Install)
3. Add all your users to Wekan Snap
4. At All Boards page click Add Board => Import => From previous export, to import your boards.

Member settings at Sandstorm Wekan version have not been fixed yet.

**Comment by PizzaProgram** [comment]
Thank you for the quick infos. :)
We have tried to install Snap version, but had problems. Formatted VPS server > started over with Sandstorm.

I think We'll wait until everything gets fixed and released with the new version.
Sadly we have not enough Linux experience and I'm afraid we'll loose our work so far.

**Comment by PizzaProgram** [comment]
Until then, maybe a sentence here:
https://github.com/wekan/wekan#requirements
` "warning: Member permissions at Sandstorm Wekan version have not been fixed yet."`
would help other beginner not to go through this like we did the whole day long ;-)

**Comment by xet7** [comment]
@PizzaProgram 

Adding that warning does not help, because you had problems with Snap version, and Sandstorm version is still easier.

What would help Sandstorm Wekan version, would be some funding at https://wekan.team/commercial-support/ , or more contributors helping fixing Sandstorm related bugs.

**Comment by PizzaProgram** [comment]
< OFF >
Yes, I've donated already 10min ago. Wanted anyway. 
Sadly, 10Eur is a ridiculously small amount for you, but high to me. 
(Your hour rate=120Eur is 8 times higher then mine=14Eur, so I can not afford more. Sorry.)

Started to learn JS just 3 weeks ago. (Working with Pascal 30 years long.) So finding / fixing bugs in JS is very hard yet.

Thank you for your time!
As soon as Export is fixed >> We'll backup our work and try to install Snap version again.

**Comment by xet7** [comment]
Hmm, it seems for this issue, somebody sent me €10 and thanks. That makes me happu :slightly_smiling_face: I think I'll look at fixing more of Sandstorm related bugs.

**Comment by xet7** [comment]
@PizzaProgram 

I don't know is trying to use Snap version really worth that extra trouble. It would be better to keep using Sandstorm Wekan version and add more comments to issues about Sandstorm related bugs.

**Comment by xet7** [comment]
@PizzaProgram 

Yes, 10Eur is small for me, at Finland rent etc costs are high. But amount of motivation and happiness for me is much higher than amount of money. When someone sends me money, without me asking for it first, or needing to deal with bureaucracy for many months, it's like breath of fresh air.

Another thing that motivates me, is someone adding new issues, comments, or pull requests, spending their time caring about Wekan, translating, adding docs, etc contributing in some way.

**Comment by PizzaProgram** [comment]
I agree.
But I do not understand, how is it possible that nobody else has any problem with this?
I've thought thousands of people using Wekan daily and adding hundreds of new Members to Boards.

**History / reproduce of problem:**
1. This is a VPS server we have rented a week ago and installed a virgin fresh Ubuntu. Nothing else.
1. The Sandstorm installation did everything automatically. It has created subdomains under ....sandstorm.io fine.
1. Seemed everything OK at first.
1. It also worked with the 1th board fine. Both of our icons appeared at "Members".
![kép](https://user-images.githubusercontent.com/26026089/104108500-7632ae80-52c5-11eb-9594-dff200893879.png)

Just I had no editing right,
- So I added a 2th Board, where I was admin. _(Thought I can add the "super-admin" back to it later. )_
- And that's were the problems started.
- A long yellow message started to pop up on top for a half-half second. Could not even read.

- After I've got admin rights too > I was able to go into Sandstorm menu > Admin panel > ... and read it fully:
`WARNING: This server seems to be unable to create a WebSocket. Sandstorm may appear to run fine, but many apps will fail to run properly. Learn more. Usually this is caused by a reverse proxy like nginx or Apache that needs to be reconfigured. If you think you are seeing this message in error, please reload this page or file an issue.`

**Comment by PizzaProgram** [comment]
>  translating, adding docs, etc

What a coincidence ... I've just translated and fixed ca 200 today of hu_HU :laughing: 
I like to add back something to communities, if I'm using the fruits of their work. (If I can.)

> But amount of motivation and happiness for me is much higher than amount of money.

We think very similar!
Thank you for your time.

**Comment by xet7** [comment]
@PizzaProgram 

Of course also others using Wekan Sandstorm version have [Sandstorm-related bugs](https://github.com/wekan/wekan/labels/Targets%3ASandstorm). Sandstorm related info is [also at wiki](https://github.com/wekan/wekan/wiki/Sandstorm). Sandstorm has [most advanced security features in the world](https://docs.sandstorm.io/en/latest/using/security-practices/). Because those security features, having some feature also working at Sandstorm requires additional Sandstorm security compatible coding.

Standalone Wekan version (Snap, Source, Docker, Univention Docker) does not have those Members related bugs. And also not as many security features.

Anyway, huge bonus points to you for also translating Wekan. That does also motivate me for looking at Sandstorm related issues more.

**Comment by PizzaProgram** [comment]
>  Of course also others using Wekan Sandstorm version have Sandstorm-related bugs.

OK, now I see: the user / admin bug is there since 2 years #2405  
Reading that issue clearified: the same thing happened to us too.
1. if a normal user created a new board,
2. and gets promoted after that, so they can add more users,
3. Wekan does not get notified by the permission change.

I'll ask my college to restart Standtorm completely, so we can check, if permissions are red correctly during startup / load.

**Comment by PizzaProgram** [comment]
I've upgraded from 4.70 >> to 4.75, but there is still no **Export** menu visible.
![kép](https://user-images.githubusercontent.com/26026089/105892247-e35a7980-6011-11eb-95bc-923f1375e5ba.png)

**Comment by PizzaProgram** [comment]
But!
 it **is visible** on those Board I've created under the Grain I've created. (Where I'm the "super-admin".)

So the problem is still member-access based, as I've stated at the beginning.

**Comment by PizzaProgram** [comment]
Is there ANY temporary / dirty way to get our data out of this, so I could import back in a Docker-based Wekan?

- export is not working on a board which was not created by the Grain-owner (superadmin).
- can not copy lists / boards
- can not even copy cards, so at least I could move 150 one by one
- the superadmin can not see those boards I've archived
- can not add other user
- can not "give away"  / push my rights to superadmin

So there is no way to export / move our board.

# Is it maybe possible to manipulate / edit something somehow at the database level or any Wekan files, so we get access?

We are not looking for a "3-year development global solution", just a quick-fix so we can leave this sandstorm-nightmare forever.

Please help !

PS: I've translated and fixed +100 sentences of Wekan to Hungarian this week again. ca 150 left only.

**Comment by xet7** [comment]
Yes https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by xet7** [comment]
Although, I don't recomment Docker. I recommend Snap. YMMV.

**Comment by xet7** [comment]
Snap: https://github.com/wekan/wekan-snap/wiki/Install

**Comment by xet7** [comment]
Also see https://github.com/wekan/wekan/wiki/Backup

**Comment by chrisi51** [comment]
Dunno if im correct here but dont wanted to open a new issue for same problem ... im using docker version 4.93.0 and with none of my users i see the export button - even with main user which is system admin as i am the only user of the system. 
I tried to create new users which are not system admins and created boards with them so that they are board admin. Also no export button :(

On creating new boards there is the option to import json from an export. thats the only reason, i started searching for "how to export a board then" and just found some tickets and in another wekan instance (ucs / docker) there is everything working. So is there anything wrong in the docker package or do i have to set any configuration or something like?

**Comment by PizzaProgram** [comment]
Dear xet7, :-)

Rather than waiting of a full-fix of this function,
please **DELETE "visibility-filter" of the Export function from code** , so EACH user can see this menu.
No member-setting needed. Export should be available to every user.
Simple, quick solution.

... or at least point me to the right .js file, where this "export" menu is coded.

_IMHO it's better to have a working button, than a limited hidden one._

Thank you in forward!

**Comment by PizzaProgram** [comment]
A wild guess:
What if you would comment this line:
https://github.com/wekan/wekan/blob/926f39c96bab1497cdfaf085bcdad0e674c45a2c/client/components/sidebar/sidebar.jade#L293

Also `user` is usually NULL inside docker or sandstorm.
So this line:
https://github.com/wekan/wekan/blob/926f39c96bab1497cdfaf085bcdad0e674c45a2c/models/exporter.js#L422
should be like:
`if (user) { return board && board.isVisibleBy(user); } else {return board;}`

**Comment by PizzaProgram** [comment]
Also `user` is usually NULL inside docker or sandstorm.
So this line:
https://github.com/wekan/wekan/blob/926f39c96bab1497cdfaf085bcdad0e674c45a2c/models/exporter.js#L422
should be like:
`if (user) { return board && board.isVisibleBy(user); } else {return board;}`

**Comment by PizzaProgram** [comment]
At current latest 5.53.0~2021-08-27 version EXPORT menu is still not available.

![kép](https://user-images.githubusercontent.com/26026089/131230917-29f9410e-554c-4a22-a8d3-da5d0bb26280.png)

**Comment by PizzaProgram** [comment]
I see the `exporter.js` was modified, but I still don't see any `user == null` handling happens at Sandstorm !!
https://github.com/wekan/wekan/blob/38666cbda2e732b60a466b255c91059039d18651/models/exporter.js#L418

Something like:
`if (user ==! undefined) { return board && board.isVisibleBy(user); } else {return board;}`

As I have already suggested 4 month ago :-(

**Comment by xet7** [comment]
@PizzaProgram 

Yes, I'm still waiting for your pull request. ;)

**Comment by PizzaProgram** [comment]
@xet7 Sorry for misunderstanding, but:
- I'm NOT a JS programmer ! Just started to learn a little about it 1 year ago.
- I do not know the WHOLE Wekan codebase as good as you guys. So I'm unsure if it may affect anything else. 
- So I'm not 100% sure if my code is right that way... should it be `!= null` ?
- Maybe you guys want to do it other way, without security risk ? _(First getting the real user from StandStorm API?)_
- Also I can not debug the code. Especially under SandStorm.

**Summarized:**
 PLEASE copy that 1 line, if you find it good enough and debug + test it ! _(Or upload a new version and I will test it.)_
Thanks :-)

**Comment by xet7** [comment]
@PizzaProgram 

User permissions between Sandstorm and Wekan is kind of a hack, it's not properly implemented yet.

Yes, this and other bugs will be fixed sometime.

**Comment by PizzaProgram** [comment]
Please tell me this will be fixed this year. :frowning_face: 
We would really like to move away from current install, but we 
# still **can not export anything** from Sandstorm based setup.
11 month has past.

- I've donated,
- Translated strings, as you have asked
- Tested in every possible way
- Suggested a solution https://github.com/wekan/wekan/issues/3423#issuecomment-907690093
- What else can I do that you guys finally fix this BUG?

If you can not Fix the problem, than simply:
# Turn OFF permissions under Sandstorm!

... or at least give a possibility to do so in the setup menu.

**Comment by xet7** [comment]
Hmm? Ok, this will be fixed this year.

**Comment by xet7** [comment]
@PizzaProgram 

What version of WeKan you have at Sandstorm? Please install wekan-5.80.spk from https://releases.wekan.team/sandstorm/ and check do you have hamburger menu => cog icon Board Settings => Export to JSON ?

**Comment by xet7** [comment]
@PizzaProgram 

When I tried Sandstorm WeKan v5.80 on board where I do not have admin rights, there I did have export board to JSON feature available to menu, and it did work. But it seems that when I do not have admin rights at Sandstorm WeKan, not all avatar icons are visible, so it's kind of crippled and not useful enough.

I will search WeKan ChangeLog for my previous code change where I did add admin rights to Sandstorm WeKan, to see does it fix showing all avatar icons, and joining boards. If it fixes those, I will probably make new release of WeKan with those admin rights fixes.

@ocdtrekkie What do you think?

**Comment by xet7** [comment]
@ocdtrekkie  

Those avatar icons not visible problems were in old Sandstorm board that has name `Sandstorm Ports In Progress`

**Comment by ocdtrekkie** [comment]
@xet7 If you were looking at my old Sandstorm Ports In Progress Wekan board on Alpha, it is probably because I copied the grain from another server for testing, so none of those avatar icons were available to the new server.

**Comment by xet7** [comment]
@ocdtrekkie 

How are some relying on it? Does any permissions work properly at Sandstorm? And how to implement it properly?

**Comment by ocdtrekkie** [comment]
As far as I know, permissions work fine for almost all pretty basic functionality. The admin panel stuff appears to be an issue for very old boards (such as the Ports in Progress one). I can share with you a modern example board at different permission levels so you can test if you would like.

**Comment by xet7** [comment]
@ocdtrekkie 

> As far as I know, permissions work fine for almost all pretty basic functionality. The admin panel stuff appears to be an issue for very old boards (such as the Ports in Progress one). I can share with you a modern example board at different permission levels so you can test if you would like.

Yes please share example. I would like to know how to do properly those where in this file is word `Hack`:
https://github.com/wekan/wekan/blob/master/sandstorm.js

**Comment by xet7** [comment]
@ocdtrekkie 

Thanks for sharing that example grain. In that grain, export does work, but there still is bug that my avatar is not visible at board activities. I'll think can that be fixed.

**Comment by ocdtrekkie** [comment]
It appears to display correctly after the initial activity. Look at this screenshot:

![image](https://user-images.githubusercontent.com/4399499/143924495-26c03bda-f7b4-42fe-8cdc-af1ba3351bd8.png)

You can see the avatar is added for both of us, but when each of us is added to the board, that activity does not show our avatars.

**Comment by xet7** [comment]
@PizzaProgram

Every user has WeKan Admin and WeKan Admin Panel at wekan-5.81.spk from https://releases.wekan.team/sandstorm/ . You can try is it useful to you. But in next WeKan v5.82 that "At Sandstor Every WeKan user is WeKan Admin" change will be reverted to original where permissions are in use.

**Comment by ocdtrekkie** [comment]
Yeah, if @PizzaProgram wants to get the grain out of Sandstorm anyways, 5.81 might present a good solution to manually upload to the Sandstorm server in question. But it will grant any and all users with access to the grain the ability to see and edit everything, and it's probably not trivially reversible, so installer beware.

**Comment by xet7** [comment]
@PizzaProgram 

If you have big attachments at your Sandstorm WeKan board, then you could try to download those and delete them so that it's possible to export to JSON, or alternatively try again when this is fixed https://github.com/sandstorm-io/sandstorm/issues/3592

**Comment by PizzaProgram** [comment]
Thank you all of you.
How do I install that .spk ?

**Comment by PizzaProgram** [comment]
At SandStorm App market there is only 5.78 available.

**Comment by xet7** [comment]
@PizzaProgram 

1. Login to your Sandstorm
2. Click Apps
3. Click Upload app to server
4. Upload wekan-5.81.spk from https://releases.wekan.team/sandstorm/
5. Click Upgrade grains

**Comment by PizzaProgram** [comment]
Thanks!! I'll try now.

**Comment by xet7** [comment]
@PizzaProgram 

That wekan-5.81 will not be accepted to Sandstorm App Market, because it gives everyone WeKan Admin permission. Only 5.82 or newer will be accepted to Sandstorm App Market, where not everyone has WeKan Admin permission.

**Comment by PizzaProgram** [comment]
> That wekan-5.81 will not be accepted to Sandstorm App Market
Understand. Did the upgrade.
Waiting for the Admin guy to report back...

**Comment by PizzaProgram** [comment]
At those boards I've created (I'm the Admin) ALL went well !
- version is the new one,
- Export menu appeared

But I still can not export that board I'm only a User and it's "just" shared with me.
(I have Admin rights too, but it does not count.)

I still waiting for the Admin guy ... hi left his PC 16 min. ago.

**Comment by PizzaProgram** [comment]
I guess he has to do the upgrade process too.
I've realized:
 - it is **not enough** that I upgrade Wekan "from my side".
 - He still sees the old version from his side ! (Even after logoff on logon again)

**Comment by xet7** [comment]
@PizzaProgram 

Oops, I helped you to "crack Sandstorm WeKan permissions", signed with my cryptographic Sandstorm package signing key, that only I have. I just moved that wekan-5.81.spk to not be visible at WeKan download server. I feel stupid.

**Comment by xet7** [comment]
@PizzaProgram 

If you would like to migrate from Sandstorm WeKan to Standalone Wekan, you can use these instructions:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by ocdtrekkie** [comment]
You didn't do anything harmful @xet7, a user can only upgrade grains they own. Which means @PizzaProgram can "crack" his own grains with that package, but the owner of the other grains needs to upgrade those packages.

**Comment by PizzaProgram** [comment]
> crack
I do not really understand what you are saying. But I hope it won't have any consequvences.
I'm an ethic guy, my Company is and my reputation is my everything.

**Comment by ocdtrekkie** [comment]
Don't worry, @PizzaProgram, all is good. 👍

**Comment by ocdtrekkie** [comment]
You can only update the grains you created/own. The only way releasing 5.81 would be particularly harmful is if we approved it in the app market, because then Wekan grains for unsuspecting users everywhere might auto-update. Which is why we don't auto-approve things.

**Comment by PizzaProgram** [comment]
I understand that releasing a non-secure version publicly is not recommended.
What I do not understand:
 - why someone, who has access to a shared board can NOT export the board?
 - why would that be riskier than taking a simple screenshot or print the page into PDF ?

**Comment by xet7** [comment]
@PizzaProgram 

In official WeKan from Sandstorm App Market, it is possible to export board, by non-admin user, and also by view-only user. It's just that your Sandstorm admin person has not updated to newest official WeKan from Sandstorm App Market.

**Comment by xet7** [comment]
@PizzaProgram 

Very likely you are running some very old buggy version of Sandstorm WeKan.

**Comment by ocdtrekkie** [comment]
@PizzaProgram Not letting users with read access export is a bug with the grain you are trying to export, not an intended behavior in this case, I think.

However, there *can* often be significant risks with enabling export for all users. (Sandstorm itself, you'll notice, does not allow you to download a grain backup for grains you do not own.) The reason why is because an export or backup might contain more information than a user is normally able to see in the UI. For instance, a grain backup has things like log data or transaction log content or other deleted content that people believe are purged from the grain. Export features generally have to be built carefully to only allow a user to download the information they can already access in the app.

**Comment by PizzaProgram** [comment]
I've just got the message:

# Export succeeded !
