### ISSUE TITLE
Wekan server Crash When Upload Avatar

### ISSUE THREAD

**Issue by jcaillet64** [wekan/wekan#3429]
Hello,

My Server Configuration :
- Windows server 2012 R2
- Wekan : 4.71.0
- Meteor : 1.12
- NodeJs : 14.15.4
- MongoDB : 4.2.11 

My trouble is the wekan server crash when i uploading an avatar. 

How i doing for resolve that ? downgrade mongodb ? upgrade wekan ?

Thanks for your help.

Jcaillet

**Comment by xet7** [comment]
@jcaillet64 

Try with Node.js 12.20.1 and start-wekan.bat , like mentioned at https://github.com/wekan/wekan/wiki/Offline

In use Node.js version can be seen from [Dockerfile](https://github.com/wekan/wekan/blob/master/Dockerfile#L15).

For some users, MongoDB 4.2.x works fine. For some other users, MongoDB 4.4.x does not work, and for others does work.

**Comment by jcaillet64** [comment]
Thanks @xet7,
Work well with Nodejs 12.x
