### ISSUE TITLE
Better "quick-creation" of cards.

### ISSUE THREAD

**Issue by FuzzyWuzzie** [wekan/wekan#343]
Almost universally across Kanban software, I find the biggest hold up for myself is actually creating the cards in the first place. Typing the title of the card is usually easy, but assigning the card to people or giving it specific labels often involves several clicks down the rabbit hole. When you add this up over even tens of cards, it becomes quite a time-sink.

I used to use [Remember The Milk](https://www.rememberthemilk.com/) and in their app, you can use special characters when typing to attach metadata to a list item (for example, <kbd>^</kbd> brings up a menu on when the item is due). I found this extremely useful, and for lack of a better term—*slick*.

I just came across wekan, and so far I really like it (thanks devs!). That said, I want this feature in it, so I've created an initial implementation in #342. Is this a feature people are in to? If so, how can it be improved? Please let me know and I'll be happy to add whatever I can to this awesome project!

**Comment by mquandalle** [comment]
Hi Kenton,

Sorry I didn’t answer before. I fully support having some keyboard shortcuts to fill the card meta-data. Your implementation in #342 seems to be on the perfect track. I’ll review the code later today. Thanks :-)

**Comment by mquandalle** [comment]
I’m closing this assuming #342 solved the issue.
