### ISSUE TITLE
Currency decimal separator

### ISSUE THREAD

**Issue by schweigel** [wekan/wekan#3436]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 4.77.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: debain
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 12.20.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Vivaldi (Chrome based)

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

I have added a custom currency field.
If I try to fill a number with comma as seperator it shows nothing and NaN ist stored.
![input1](https://user-images.githubusercontent.com/52450003/104809103-271bda80-57eb-11eb-920c-272c6aa0b424.PNG)
![result1](https://user-images.githubusercontent.com/52450003/104809106-2aaf6180-57eb-11eb-8203-6f6f03f61365.PNG)
![result2](https://user-images.githubusercontent.com/52450003/104809110-2edb7f00-57eb-11eb-8d89-a00b1d6c3206.PNG)
If I fill a number with point as seperator it works and is shown with a comma as seperator.
![input2](https://user-images.githubusercontent.com/52450003/104809125-40248b80-57eb-11eb-8d4e-f25a38b3c0fe.PNG)
![result3](https://user-images.githubusercontent.com/52450003/104809128-41ee4f00-57eb-11eb-8b1e-9d05b24164fd.PNG)
In german it should be booth a comma as seperator. In english it shoud be booth a point.
I would like it if comma and point as seperator works for input.

**Comment by lindhork** [comment]
Hey @schweigel I think your objection is a good one and have taken a look at the problem.
I'll create a pull request, maybe it will be adopted.
