### ISSUE TITLE
Combine of "Search All Boards" and "My Cards"

### ISSUE THREAD

**Issue by mfilser** [wekan/wekan#3439]
Hello,
first thank you a lot for the new useful features "Search All Boards", "My Cards", "Broken Cards" and "Due Cards"

I think "My Cards" can be replaced by a specific search at "Search All Boards" ?

So I just want to mention an idea i have. Maybe it will be useful to combine this 2 features togehter:
- "Move" the layout of "My Cards" to "Search All Boards"
- At "Search All Boards" put a link/button to have the same as "My Cards".
- Maybe "Due Cards" can be included as well into the "Search All Boards" as well ?
- Is it also possible to move "Broken Cards" to "Search All Boards" ?

This would also reduce the menu options at "Member Settings", maybe like this:
![grafik](https://user-images.githubusercontent.com/13166201/104909628-6c294380-5988-11eb-91ac-9292dd722707.png)

![grafik](https://user-images.githubusercontent.com/13166201/104910351-7bf55780-5989-11eb-9bba-0b1a7e18fcde.png)

**Comment by xet7** [comment]
Please no. Current menus work well on mobile and this is just extra click.
