### ISSUE TITLE
CustomFields are duplicated when moving a card from a board to another board

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#3445]
## Issue
**Problem description**:
CustomFields are duplicated when moving a card from a board to another board
Steps to reproduce:
1- create 2 boards
2- create the same customfield in both boards
3- create a card in board1 and set a value for the customfield
4- move the card from board1 to board2
5- the card is properly moved, but the customfield is defined 2 times in board2

See video of the issue:
https://user-images.githubusercontent.com/74183327/105058395-73c71600-5a76-11eb-9c57-cfc9101067e5.mp4

**Comment by bronger** [comment]
I observed that too, but a design decision is needed for how it should be. This is not trivial.

Suggestion:

- If the destination board has no custom field the a matching name, create the field (current behaviour).
- If the destination board has a custom field with a matching name *and* type, use it and just copy the field value.
- If the destination board has a custom field with a matching name but different type, create a new custom field with the source board name appended as a suffix.

But there are other possibilities.

**Comment by marcungeschikts** [comment]
Hallo Torsten,

thank you for your quick answer.

Concerning the design decision to take , I just want to mention that this is the behaviour for label:
-  If a label is defined on 2 boards, the label of the card moved from a board1 to aboard2 will be kept in board2 (see the [same video](https://user-images.githubusercontent.com/74183327/105058395-73c71600-5a76-11eb-9c57-cfc9101067e5.mp4) in attachment).

**Comment by marcungeschikts** [comment]
Concerning the workaround, we use the second one, but it is heavy in the long run when we have a lot of cards.

**Comment by jrsupplee** [comment]
The reason for this behavior is that custom fields are defined per board.  That is, the custom field definitions from one board are not shared with another (except in the case of copying a card from one board to another, I think).  So copying a card to another board shares the board definitions from the previous board creating apparently duplicate fields.

If I am right then the copy function should probably look for equivalent fields on the new board (same name and type) and use those instead of sharing the from board's definition.

**Comment by bronger** [comment]
> If I am right then the copy function should probably look for equivalent fields on the new board (same name and type) and use those instead of sharing the from board's definition.

Yes, this is desired behaviour (at least by @marcungeschikts and me).

I think this is suitable for the general design of Wekan, which seems to rely on name matching in many cases, instead of true object identity.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3449 . Will be in upcoming Wekan v4.83 sometime today or tomorrow.

**Comment by marcungeschikts** [comment]
Thanks to everyone, Great job and impressive responsiveness.
