### ISSUE TITLE
Can't create Organizations or Teams : why ? 

### ISSUE THREAD

**Issue by ledufakademy** [wekan/wekan#3454]
Hello,

i have just setup wekan with ldap  support (no group support working : bug notified).
And no i cannot create : 

- organizations,
- teams.
- 
Note : i can create Board.

What should i have missed ?

thank you.
(i have see no user manual so ... posting  here)

**Comment by xet7** [comment]
@ledufakademy 

That Teams/Organizations code is still In Progress. It's not ready yet. Code to save Teams etc is not written yet. It will added later.

Moved to #802

**Comment by ledufakademy** [comment]
ok thank you for your answer xet7
