### ISSUE TITLE
Link dialog closes card when clicking in dialog

### ISSUE THREAD

**Issue by mweiss237** [wekan/wekan#3455]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: No
* Wekan version: 4.75.0
* Operating System: Windows 10 
* Node Version: 12.18.2
* MongoDB Version: 4.2.8
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Google Chrome

**Problem description**:
![Video_2021-01-22_085653 (1)](https://user-images.githubusercontent.com/26773967/105464144-5cb04000-5c91-11eb-825f-7d3cfab6498d.gif)

- *Explain steps how to reproduce*
  - open a card and go to description or comments. Edit this field and press STRG + K to open link dialog. Click in field "text to display" and enter your Text. As you can see the card in the background will be closed as you click the dialog.

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
  - No error/warning in explorers console

**Comment by xet7** [comment]
@mweiss237 

That Summernote WYSIWYG editor is buggy. In Progress is changing it to other WYSIWYG editor, but it's not ready yet.

Moved to #3399

**Comment by ryanMushy** [comment]
IMO this comes down to how to wekan deals with mouse clicks in the UI.

You can get the same terrible implementation inside the Admin People Board when trying to drag-select a text field while editing a users information. If your mouse leaves the window and performs a mouse up cmd, you will lose focus on the settings and lose all changes.

**Comment by ryanMushy** [comment]
@xet7 Bug solution
![image](https://user-images.githubusercontent.com/77740971/113218464-6a0b1d00-9234-11eb-8a2c-d16da9782efa.png)
