### ISSUE TITLE
Add custom fields to all cards

### ISSUE THREAD

**Issue by jrsupplee** [wekan/wekan#3460]
On custom fields there is an option: *Auto create field to all cards*.  Currently this option add the field to all *new* cards but not to existing cards.  Is this the correct functionality?  If so, I suggest we rename the property to *Auto create field on new cards* and add another option to create the field on all existing cards.

**Comment by xet7** [comment]
@jrsupplee 

Yes, you can add pull request if you figure it out. If I remember correctly, somebody else also asked about this sometime.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3466
