### ISSUE TITLE
Highlighting of number of cards in list is too sensitive

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3467]
Taken from discussion https://github.com/wekan/wekan/discussions/3463.

I think that the number of cards in a list – if a WiP limit is active – should only be marked red if the limit is *exceeded*. Otherwise, if you take care of filling your lists as it should be in the Kanban method, you perpetually have red numbers on top of them, although everything is okay.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3468
