### ISSUE TITLE
wekan-ldap vs. packages/wekan-ldap

### ISSUE THREAD

**Issue by robert-scheck** [wekan/wekan#3480]
I filed two issues and two PRs against wekan-ldap but noticed now that `packages/wekan-ldap/` seems to ship a (modified?) copy of the code (where I would have expected a Git submodule instead).

 - [Security: SSL/TLS certificate validation for LDAP disabled by default](https://github.com/wekan/wekan-ldap/issues/89)
 - [Reject by default LDAP connections not authorized via CA trust store](https://github.com/wekan/wekan-ldap/pull/90)
 - [Unable to pass trusted root CA certificate via LDAP_CA_CERT](https://github.com/wekan/wekan-ldap/issues/91)
 - [Handle '\n' line breaks in PEM-encoded SSL/TLS certificates](https://github.com/wekan/wekan-ldap/pull/92)

Do I need to file the issues and PRs here, too? Or will they be merged? What's the proper way?

**Comment by xet7** [comment]
@robert-scheck 

All submodules code were added directly to `packages/`, because cloning submodules had errors on Windows. So please add PRs to `packages/wekan-ldap/`.
