### ISSUE TITLE
Global search: “list not found” error if no search results in this list

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3481]
With Wekan 4.86, the global search

    @bronger list:"A" list:"B"

results in the error message “List 'B' not found.” if “bronger” has no cards currently in list “B”, although there are cards of “bronger” in list “A”, and both “list” operators should be OR’ed.

Besides,

    @bronger list:"B"

results in the same error message, which is confusing, since the list is there, it just does not contain search results.

**Comment by jrsupplee** [comment]
Is there an actual list named "B"?  The search first verifies the predicates exist and then performs the search.  If any of the predicates do not match, an error is returned.

**Comment by bronger** [comment]
The list “B” exists in many boards, and it is not empty. It just contains no `@bronger` cards.

**Comment by jrsupplee** [comment]
How about a search containing only `list:B` ?

**Comment by bronger** [comment]
This finds cards in list “B” (all of them, I assume, but I didn’t check that).

**Comment by bronger** [comment]
It does not seem to occur always. I can only reproduce it when I entered global search via a search link.

Log into https://op.its.kfa-juelich.de/ as test/12345. Then, open https://op.its.kfa-juelich.de/global-search?q=list%3AB and you see the error, although e.g. https://op.its.kfa-juelich.de/b/fiCQxabGhrqEsNNWL/test-1 contains a list “B”.

**Comment by bronger** [comment]
I didn’t notice that a URL with a query string is necessary because once you opened global search via such a link, also filling the search query field and starting fresh searches exhibits the error.

**Comment by jrsupplee** [comment]
Yea, there's lots of weirdness.

I have seen this a little before.  I think it has something to do with subscription manager that is being used (`SubsManager`).

**Comment by jrsupplee** [comment]
You can try changing the subscription from using `subManager.subscribe()` to `Meteor.subscribe()` at https://github.com/wekan/wekan/blob/4bd3329d07e4db378bd5728b0934cb7e0f54e612/client/components/main/globalSearch.js#L328

See if that fixes it.

**Comment by bronger** [comment]
This does not change the behaviour.

**Comment by jrsupplee** [comment]
I am going to commit a major update to search probably today and I do not see these problems.  Rather than trying to debug this wait and test it on the update.

**Comment by jrsupplee** [comment]
@bronger 

The latest update has been included in the master repository.  If you have a chance to test it let me know if there are problems.  Also, if you have a large dataset to test the search on I would like to know how it performs.  I only have about 300 cards in mine.

**Comment by jrsupplee** [comment]
Do searches work for you at all?  In the current repository they are broken.

**Comment by bronger** [comment]
No, they don’t work. They only use the local CPU to 100%. Tested with Wekan v4.90.

**Comment by jrsupplee** [comment]
The snap build was failing and changes were made that caused this.

My fork has code that works: https://github.com/jrsupplee/wekan/tree/new-search

**Comment by jrsupplee** [comment]
4.91 has been released and is working properly for me.

**Comment by bronger** [comment]
Indeed, I cannot reproduce this problem anymore with v4.91. Thank you!
