### ISSUE TITLE
Unable to pass trusted root CA certificate via LDAP_CA_CERT

### ISSUE THREAD

**Issue by robert-scheck** [wekan/wekan#3484]
As mentioned in the [wiki](https://github.com/wekan/wekan/wiki/LDAP) and in [some code](https://github.com/wekan/wekan/blob/master/start-wekan.sh#L264), the trusted root CA certificate should be passed via `LDAP_CA_CERT` as a single-line string. This however does not work and the issue has been likely hidden by #3482 so far. PEM format is [well-specified](https://tools.ietf.org/html/rfc1421) and things only started to work for me, once I was able to pass line breaks in.

**Comment by xet7** [comment]
Please send pull request.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3485

**Comment by robert-scheck** [comment]
Wow, thank you for the quick review and merge!
