### ISSUE TITLE
How to manually reset password in db

### ISSUE THREAD

**Issue by rahulserver** [wekan/wekan#3486]
## Issue
I am running wekan in intranet lan where no outside internet is accessible and we do not have a mail server to send emails. 
So how do I manually reset the password in db if its lost?

**Comment by xet7** [comment]
@rahulserver You edit database with nosqlbooster, mongodb cli or similar. If you have registration disabled, edit that to be enabled in settings collection/table. Then create new user at /sign-up , edit that user be admin, and in admin panel change other users password. Wekan database is usually at port 27019 or 27017, database name wekan. Also see:
- https://github.com/wekan/wekan/wiki/Backup
- https://github.com/wekan/wekan/wiki/Forgot-Password

**Comment by xet7** [comment]
Also, you can edit database users collection/table and copy one user password hash to some other user password hash.

**Comment by xet7** [comment]
If you have LDAP enabled, you can change that user login from ldap to password, so you can login with password, when changing users collection/table.
