### ISSUE TITLE
Quay builds are not getting updates.

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#3488]
Hi

I switch to the Quay builds because of that Docker hub issues. I am still on Quay builds because the current release docker-compose.yml is still pointing to the Quay however it does not look like I am able to get the latest versions.

I am still on 4.81.0 and the current release is 4.87

```
docker pull quay.io/wekan/wekan
Using default tag: latest
latest: Pulling from wekan/wekan
Digest: sha256:fa611de07f0dae9a24f4493bcc4e02c94010a83d72c68fd561fa227ecaf2bd8a
Status: Image is up to date for quay.io/wekan/wekan:latest
quay.io/wekan/wekan:latest


```

thanks

**Comment by xet7** [comment]
Thanks a lot for info! It seems Quay builds had some failures so Quay disabled build triggers. I did delete build triggers and create them again, so now newest Wekan v4.87 containers for tag and latest are building, they should be available soon.
