### ISSUE TITLE
Docker images not up-to-date

### ISSUE THREAD

**Issue by AuspeXeu** [wekan/wekan#3490]
https://quay.io/repository/wekan/wekan?tab=tags does not seem to carry the latest versions?

**Comment by xet7** [comment]
@AuspeXeu 

Latest tag is newest Wekan version. v4.87 is still building. Yes, it seems Quay builds very slowly.

**Comment by AuspeXeu** [comment]
Are these the same images like on hub.docker.com ?

**Comment by xet7** [comment]
@AuspeXeu 

Yes, same docker images at Quay and Docker Hub. Builds at Docker Hub work just fine:
https://hub.docker.com/r/wekanteam/wekan/tags?page=1&ordering=last_updated

**Comment by AuspeXeu** [comment]
Testing this right now. Thanks!

**Comment by AuspeXeu** [comment]
This worked fine. Thanks again!
