### ISSUE TITLE
Data recovery from not bootable system

### ISSUE THREAD

**Issue by FuXXz** [wekan/wekan#3494]
Hello,

Data recovery not bootable system
I had Wekan installed on Ubuntu 18 via Snap. But my VPS server doesn't start anymore, I don't know what going up and the provider cant help me. The provider offers only a VPS Container Export.
Can the wekan data be accessed via a rescue system / exportet Container in order to import it to another VPS?
Maybe this doesn't fit in here, but I have no other help and hope you can help me.
Greetings

**Comment by xet7** [comment]
@FuXXz 

1. To new server, install Wekan Snap. For example:
```
sudo snap install wekan
```
or
```
sudo snap install wekan-gantt-gpl
```
2. At new server, stop Wekan Snap. For example:
```
sudo snap stop wekan
```
or
```
sudo snap stop wekan-gantt-gpl
```
3. Copy from old server directory `/var/snap/wekan/common` to replace new server directory `/var/snap/wekan/common` and set permissions. For example:
```
sudo chown root:root /var/snap/wekan/common
```
4. Start Wekan. For example:
```
sudo snap start wekan
```
or
```
sudo snap start wekan-gantt-gpl
```
5. Set Wekan Snap settings. For example:
```
sudo snap set wekan root-url='http://localhost'
sudo snap set wekan port='80'
```
or
```
sudo snap set wekan-gantt-gpl root-url='http://localhost'
sudo snap set wekan-gantt-gpl port='80'
```

**Comment by FuXXz** [comment]
Ok, thank you very much!
Does the version of the old Wekan installation have to match the new one?
Probably there are problems if I have different versions?

And if so, how can I find out the version on the broken server and install a special version on the new server?

**Comment by xet7** [comment]
@FuXXz 

Wekan automatically upgrades any old database structure to newest. It does not matter what is your version.
