### ISSUE TITLE
LDAP login Failure with 4.87.0

### ISSUE THREAD

**Issue by robbagithub** [wekan/wekan#3495]
Add these issues to elsewhere:

Snap: https://github.com/wekan/wekan-snap/issues
LDAP: https://github.com/wekan/wekan-ldap/issues
UCS: https://github.com/wekan/univention/issues
Other Wekan issues can be added here.

Server Setup Information:

Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
Did you test in newest Wekan?: Yes
For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
Wekan version: 4.87.0
If this is about old version of Wekan, what upgrade problem you have?:
Operating System: Linux
Deployment Method(snap/docker/sandstorm/mongodb bundle/source):snap
Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):Nginx
Node Version: 12.20.1
MongoDB Version: 3.2.22
Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?Chrome 87.0.4280.141
Problem description:

*REQUIRED: Unable to login via LDAP
2021-01-27T02:03:34Z wekan.wekan[63755]: [Symbol(kCapture)]: false
2021-01-27T02:03:34Z wekan.wekan[63755]: },
2021-01-27T02:03:34Z wekan.wekan[63755]: tlsOptions: { rejectUnauthorized: true }
2021-01-27T02:03:34Z wekan.wekan[63755]: }
2021-01-27T02:03:44Z wekan.wekan[63755]: [ERROR] connection time out 10000
2021-01-27T02:03:44Z wekan.wekan[63755]: [ERROR] Error: Timeout

Explain steps how to reproduce - Login page appears, attempt login and fails.

--

Logs from Admin

I think the option change wasn't applied It still has this
: tlsOptions: { rejectUnauthorized: true } 
We set that to false

**Comment by robbagithub** [comment]
I've recreated as the issue was closed but problem not solved

**Comment by xet7** [comment]
@robbagithub 

Please do not duplicate issues.

Moved to #3493

**Comment by robbagithub** [comment]
Please don’t close open ones!
