### ISSUE TITLE
page reload when opening "my cards" and "due cards"

### ISSUE THREAD

**Issue by tsia** [wekan/wekan#3507]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 4.91.0
* If this is about old version of Wekan, what upgrade problem you have?: -
* Operating System: CentOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node Version: 12.20.1
* MongoDB Version: 3.4.24
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Edge 88

**Problem description**:
- Open private Window or clear all Browser data
- Log in to wekan
- Click on Username
- Click on "My Cards" or "Due Cards"
- previous page reloads instead of opening "my cards" or "due cards"
- after that it works fine. It's only broken on first load with empty cache/cookies/localStorage whatever.

**Comment by jrsupplee** [comment]
@xet7 

The patch I submitted fixes the problem that @tsia described.

However the issue is that when a sort is set the page is reloaded so the page sees the sort.  There must be some way to propagate changes from a popup to the main template without reloading the page.

**Comment by xet7** [comment]
@jrsupplee 

Do you mean like this?
- https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarFilters.js#L107-L110
- https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarFilters.js#L146-L150

Fixed at https://github.com/wekan/wekan/pull/3509

**Comment by jrsupplee** [comment]
I think something like the first one might work.  Thanks
