### ISSUE TITLE
Display trouble with avatars in notifications

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3515]
I experience the following display problems with notifications:

![image](https://user-images.githubusercontent.com/2184938/106468437-34e58700-649e-11eb-816f-255416d636a6.png)

As you can see, the avatar is overlapping with other text, and differs in width.  I think this is a regression but I have not investigated this so far. I’m happy to do that unless the root cause is obvious to you.

I use Wekan v4.91.

**Comment by mfilser** [comment]
@xet7 
I can have a look at this if you like.

**Comment by xet7** [comment]
@mfilser 

It would be great if you could fix that, please send PR. Your previous PR at https://github.com/wekan/wekan/pull/3491 did also break displaying red colored line below Assignee avatar icons at card, that line is now at center below Assignee avatar icons.

**Comment by xet7** [comment]
Thanks!

**Comment by ischeriad** [comment]
The red line on the cards (.assigneehr) is still not properly displayed in Firefox (seems to be covered up by the avatar).
My CSS is very rusty, but ``margin-top: 32px`` on the class seemed to work without breaking the display in Safari, Chrome or Edge. But I'm not sure about other implications that might have.

**Comment by mfilser** [comment]
Thank you for your hint. Can you post here a screenshot?

**Comment by ischeriad** [comment]
**Firefox**, before the change (actually, I just turned it off as you can see). The line is hidden:

<img width="962" alt="Firefox_before" src="https://user-images.githubusercontent.com/1580928/106753335-d817d700-662b-11eb-8233-c0e9d59255c3.png">

**Firefox**, adding ``margin-top: 32px``

<img width="980" alt="Firefox_after" src="https://user-images.githubusercontent.com/1580928/106753377-e1a13f00-662b-11eb-99aa-773063791f54.png">

**Chrome**, same change, appearance is the same here as without. Increasing ``margin-top`` further would move the line down:

<img width="973" alt="Chrome_after" src="https://user-images.githubusercontent.com/1580928/106753391-e534c600-662b-11eb-961e-a2d19ebc9ccc.png">

**Comment by mfilser** [comment]
Thank you for this useful screenshot, i will have a look at it :)

**Comment by mfilser** [comment]
I think it depends on which avatar you uploaded.
I have no avatar uploaded and it's displayed as expected:
![grafik](https://user-images.githubusercontent.com/13166201/106781756-af063f00-6649-11eb-8c93-a1367792b9b5.png)

Which size does your original uploaded avatar have ?

**Comment by ischeriad** [comment]
But it looks like you are in Chrome, which works fine here as well. (As do Safari on macOS and Edge on Windows 10)

Firefox is the problem (tested in 85 on macOS and Windows).

My Chrome screenshot is only to show that my proposed fix doesn't break in other browsers.
Sorry if this was not clear.

**Comment by mfilser** [comment]
@ischeriad 
I see, thank you for clarifiying, i didn't get it exactly, but now i understand it.
I will have a look it it. The strange is that at Firefox the <hr> line is displayed before the <a> tag and at Chrome it's displayed as defined in html.
Maybe there is another solution too. Doing all the layout with margin / padding and pixel numbers, and the same for mobile view, is for me not the best practise, but i am also not an css designer, i am a lot more the programmer ;)

**Comment by mfilser** [comment]
I have a good solution which should work on all browsers very well.
I will rebase my commit when #3524 is resolved because i always want to test at latest version before submitting a pull request.

**Comment by xet7** [comment]
@mfilser 

https://github.com/wekan/wekan/issues/3524 is now resolved.

**Comment by mfilser** [comment]
Thank you very much, i will do it tomorrow, i am nearly sleeping

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3532

**Comment by ischeriad** [comment]
@mfilser Looks like the distinction between card members and assignees got lost in the process. Everyone now has the red line (which displays beautifully in Firfox now 😉)
![Screenshot 2021-02-11 102720](https://user-images.githubusercontent.com/1580928/107620181-9b179a00-6c54-11eb-9fd5-f79ddee8d41e.png)

**Comment by mfilser** [comment]
@ischeriad 
Thanks for the hint, i can have a look at it.
