### ISSUE TITLE
Sandstorm: If two users have the same display name, the second doesn't get logged in

### ISSUE THREAD

**Issue by dwrensha** [wekan/wekan#352]
To reproduce: Start the Sandstorm demo and create a new Wekan grain. Create a sharing link with edit permissions and copy it. Now start a new Sandstorm demo in a new private window and redeem the sharing link. The new demo user does not get logged in to the Wekan grain and cannot edit the board.

**Comment by mquandalle** [comment]
Related: https://github.com/sandstorm-io/sandstorm/issues/1027
