### ISSUE TITLE
Missing line wrapping in notifications

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3527]
In Wekan v4.92, the nowarp in https://github.com/wekan/wekan/blob/282505cde2265b71f9da5c174f623d94e78e2686/client/components/main/header.styl#L120 switches off line wrapping in the notifications:

![image](https://user-images.githubusercontent.com/2184938/106762066-c0dde700-6635-11eb-9961-bee2cd7ab9d5.png)

If I remove this line, the notifications fit into the notification popup again, but the avatars have wrong proportions:

![image](https://user-images.githubusercontent.com/2184938/106762153-da7f2e80-6635-11eb-9436-fb475a59b591.png)

**Comment by xet7** [comment]
@mfilser 

Can you look at this?

**Comment by mfilser** [comment]
@xet7 
Yes, i will have a look at this
