### ISSUE TITLE
Restricted Registration / Signups

### ISSUE THREAD

**Issue by PrestonL** [wekan/wekan#353]
If a full admin interface is too much development time, would it be possible to at least have signups restricted by having a default admin user that is created who can add / remove / reset passwords for users, then that admin superuser that would be able to open registration to all if that's what is preferred?

Approaching it from a superuser vector would also negate the need for an extensive administration interface.  The superuser could even "become" another user to see things from the other user's perspective.

Right now I have wekan sitting behind an HTTP password gateway to mitigate access.  Getting rid of that would probably do a lot to help the ones I have using the software.

Thanks in advance, everything has come so far!

**Comment by yjfdl123** [comment]
have u solve this question?
I also want to change the user register program

**Comment by synxmax** [comment]
add `forbidClientAccountCreation: true,` after `showForgotPasswordLink: true,` in /config/accounts.js

**Comment by xet7** [comment]
This is already implemented in Admin Panel settings to set Wekan invite-only.
