### ISSUE TITLE
Feature : Add Prometheus metrics

### ISSUE THREAD

**Issue by pichouk** [wekan/wekan#3535]
Hi,

I'm currently hosting a Wekan instance for several organisations, and I wonder if we can add a [Prometheus](https://prometheus.io/) endpoint to get some metrics from Wekan, for example : 
- number of users
- number of connected users
- number of boards (public or private)

Prometheus is really the leading monitoring solution, and a lot of online softwares have integrated Prometheus exporter (or plugins that does the job).
I guess it should not be too complicated as it consists of exposing a simple plain text file under `/metrics`, as described in [Prometheus documentation](https://prometheus.io/docs/instrumenting/exposition_formats/). This page is generated regularly based on database query.

I'm not a Javascript developer (nor a developer actually), but I may try to implement an opt-in Prometheus exporter feature if it sounds interesting for other people. Or at least help to describe/design the feature.

**Comment by mfilser** [comment]
I think the best to integrate third party apps is using the Wekan API.

**Comment by xet7** [comment]
Yes. For those counts, you would add REST API code to `wekan/models/*.js` so that logged in admin user is aithorized to get that info. Then you would [call that api](https://github.com/wekan/wekan/blob/master/api.py) in cron script that would write that textfile.

**Comment by xet7** [comment]
Related https://github.com/wekan/wekan-scheduler

**Comment by xet7** [comment]
Related #1308

**Comment by pichouk** [comment]
Yes, maybe I can directly use the API. But I would like some advices because it would be nice to have an API endpoint to get all private boards.

Right now, `/api/boards` return only public boards, and to get private boards I have to loop on `/api/users/{user}/boards` for each user (which is really inefficient for a large instance). IMHO it seems logical that `/api/boards` returns all boards, with an attribute that indicate if a board is private or not.
But it would be a breaking change, so I don't think it will be merged if I submit a PR. Should we had another endpoint ? `/api/privateboard` ? Or add a GET parameter to `/api/boards` to choose public or private boards ?

**Comment by xet7** [comment]
@pichouk 

You should add new API endpoint that does `.count` query/queries. Not loop through everything with cursor.

**Comment by pichouk** [comment]
:thinking: I'm not sure to understand. You mean I should create a `/api/boards_count` endpoint that return the number of public/private boards ?

**Comment by xet7** [comment]
@pichouk 

Yes. Somewhere here:
https://github.com/wekan/wekan/blob/master/models/boards.js#L1710

With this kind of MongoDB database counting query:
```
const privateBoardsCount = Boards.find({ 'permission': 'private' }).count()
const publicBoardsCount = Boards.find({ 'permission': 'public' }).count()
```

**Comment by pichouk** [comment]
Ok I see, thanks I'll take a look and submit a PR !

**Comment by xet7** [comment]
@pichouk

You can build Wekan, test code changes, and send pull request like similar like here:
https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

But with only your code changes, no need to add any plugin.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3556

**Comment by Emile840** [comment]
Hi,

@pichouk, did you find a way to implement that prometheus exporter ?
@xet7, do you mind (or do you thing is a good idea) if i implement a new end point in WeKan "/metrics" that will be exposed without authentication and return severals metrics on promotheus text format ?

**Comment by xet7** [comment]
@Emile840 

Wow, without authentication? Those that mass scan Internet would get a lot of details. I prefer no.

**Comment by xet7** [comment]
WeKan already has Matomo Web Analytics integration, is that not enough?
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys#matomo-web-analytics-integration

**Comment by xet7** [comment]
@Emile840 

Yes allowed IP address list for metrics is OK.

**Comment by pichouk** [comment]
Just FYI I made a little python script to act as a Prometheus exporter, which use the Wekan API. it is hosted [here](https://gitlab.utc.fr/picasoft/projets/services/wekan/-/tree/master/prometheus-exporter) but IIRC this is a private Gitlab instance. If you need it I may provide you a gist.

**Comment by xet7** [comment]
@pichouk 

Please provide gist. Thanks!

**Comment by pichouk** [comment]
You can find a copy of the code here https://gist.github.com/pichouk/2040c30127bec7a561d31d646c4571a7

I'm not sure it will be very helpful because this is just a simple Python script running (in Docker) on the same server than the Wekan instance. This is not great software :joy: 
Also, please note that I'm not on the entity that run this script anymore, so I am not really able to debug it.

**Comment by xet7** [comment]
@pichouk 

It's very helpful. There are many Python scripts for WeKan already, this is great addition. Thanks!

**Comment by xet7** [comment]
@pichouk 

I added wiki page about what Python code there is for WeKan:
https://github.com/wekan/wekan/wiki/Python

**Comment by Emile840** [comment]
@xet7 
regarding allowed IP address list for metrics, would you mind if a list of trusted ip adress is setted by using an environment variable instead of changing admin panel and corresponded back-end ?

**Comment by xet7** [comment]
@Emile840 

Environment variable usually is less code to add, it's OK.
