### ISSUE TITLE
Snap: Get verified on snapcraft.io

### ISSUE THREAD

**Issue by Justinzobel** [wekan/wekan#3537]
If this is official as stated https://snapcraft.io/wekan please move to a Wekan named account and get it verified by snapcraft.

**Comment by xet7** [comment]
@Justinzobel 

How to become verified? Is that feature available yet? Link please?

And how to move to Wekan named account?

From previous discussions I did read from https://snapcraft.io forums, becoming verified is not yet available.

**Comment by xet7** [comment]
@Justinzobel 

Wekan installing official Wekan Snap, it does already show a message like:
"Installed wekan 4.93 from developer Lauri Ojansivu (xet7)"

What is difference in being "verified" ? How is verification done?
