### ISSUE TITLE
Issue - Deleting a linked card blocked the parent board to load

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#3540]
## Issue
* Wekan version: last version
* Deployment Method :snap
* Webbrowser version :Chrome Version 88.0.4324.146 (Build officiel) (64 bits)

**Problem description**:
- Quite similar to https://github.com/wekan/wekan/issues/3367 except that it is the card which is linked that we deleted
Steps to reproduce:
In board A, create a card.
In board B, create a link to that card.
In board B, delete that linked card
Board A fails to load. 

N.B.: 
1- Board A and B contains some customs fields
2- I did not manage to reproduce in another board.
3- The board which fails to load, already encountered this issue and was repaired after #3367 was fixed

**Comment by xet7** [comment]
@marcungeschikts 

Can you send your Wekan database to me like described here https://github.com/wekan/wekan/issues/3367#issuecomment-762253087 ? It would help me fix that bug.

**Comment by olivierlambert** [comment]
Email sent!

**Comment by mfilser** [comment]
@xet7
Sorry for that issue, again.
What error did you got exactly? At linked cards the custom fields are missing, i have a look to get this working too.
I think the try-catch should be always safe.

https://github.com/wekan/wekan/commit/d57eb6a2fc73c7b25c957ad42b5f7a06f680e1a1#diff-2e4af921ac17ac7d0ef51c82aad90b0887bae9cf0dba9f04d0d7b90077d5e661R750-R756

Can we re-enable custom fields sorting with this try-catch code?

**Comment by xet7** [comment]
@mfilser 

With those changes, there are these errors:

![undefined](https://user-images.githubusercontent.com/15545/107275143-06494c80-6a5a-11eb-9246-33e48b480a95.png)

**Comment by xet7** [comment]
@mfilser 

Of course you can send any PR.

**Comment by mfilser** [comment]
Thank you a lot for this, i sent a PR, i hope that this fixes the issue and is still sorting where at normal cards.

**Comment by marcungeschikts** [comment]
Issue fixed...Impressive reactivity...once again.

Thanks for your amazing job.
