### ISSUE TITLE
Email notification when card becomes due

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3543]
I’d like to receive an email when a card is due.  We use Wekan v4.87 in a Docker container, which gets – amongst others – the following two environment variables:

    NOTIFY_DUE_DAYS_BEFORE_AND_AFTER=1,0
    NOTIFY_DUE_AT_HOUR_OF_DAY=6

Email notifications work in principle, but I still do not get due notifications at 6am local time (or any other time) when a card becomes due. I would have expected to get two mails per card: one on the day the card has its deadline, and one the day before.

Do I need to set anything else in order to receive those notifications?

**Comment by bronger** [comment]
https://github.com/wekan/wekan/discussions/3498#discussioncomment-333119 and https://github.com/wekan/wekan/discussions/3498#discussioncomment-333123 seem relevant.

**Comment by K1LLUM1N471** [comment]
Hello, 
we've got the same problem here. Email is working fine, except due notifications.

Wekan (Snap) Version: 4.96.0

`notify-due-at-hour-of-day='7'`
`notify-due-days-before-and-after='1,0'`

Is there already a solution or workaround available?

Kind regards, 
K1llum1na471

**Comment by s-rades** [comment]
Is there already a solution or workaround available?

**Comment by lucaslgithub** [comment]
Hello all. We're still experiencing a lack of email notifications, running Snap - Test email from settings works great and I don't see any errors triggered in logs, as if the cron job had not executed. Running 6.09.0, meteor 2.2, node 12.22.10.

**Comment by dereckhall** [comment]
same issue here. i receive email notifications for setting due dates, adding comments, moving items to different lanes... but i do not receive email notifications for start, due, end dates. i also do not see any errors within logs.

type of install: docker-compose
host: centos 7.9.2009
docker version: 18.06.1-ce
wekan image: quay.io/wekan/wekan:v6.30
mongo image: mongo:5

i have the following related environment variables set within docker-compose for the wekan-app and i have verified they're visible within the wekan-app container.
NOTIFY_DUE_DAYS_BEFORE_AND_AFTER=2,0
NOTIFY_DUE_AT_HOUR_OF_DAY=12
-
i've also tried enabling/disabling the below variable to no avail.
BIGEVENTS_PATTERN=received|start|due|end

**Comment by xet7** [comment]
@lucaslgithub 

Maybe someone could have time to read the code, about how it works, and provide PR like at https://github.com/wekan/wekan/wiki/Emoji ? Most of those that originally added code related to notificatons, schedules, cron, rules etc have not contributed anything for a long time, and I have not yet looked at how this all works.

https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+bigevents

https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+NOTIFY_DUE_DAYS_BEFORE_AND_AFTER

Also there is some cron related code for scheduled something:

https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+cron

https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+drawer

https://github.com/wekan/wekan/issues/3378

And there are some wishes like scheduled rules, but nobody has yet spent time to figure it out:

https://github.com/wekan/wekan/issues/2476

https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+rules

https://github.com/wekan/wekan/issues/1160

There is also this feature request:

https://github.com/wekan/wekan/issues/2026

Any help would be very welcome.

My challenge is, that am I able to get enough new contributors to WeKan, so that WeKan could get faster progress. Does anyone dare to look at WeKan code?

**Comment by lucaslgithub** [comment]
@xet7 - you're very kind. Thank you for the detailed response. I managed to "patch" my need momentarily by creating a stand alone python script which connects to mongo locally and iterates through due cards, and uses AWS SES to send an email. 

Here's a raw working version in case it helps anyone experiencing a lack of email notifiications. I will run this via a cronjob daily once a day.

`
import pymongo, emails, os
from datetime import datetime, timedelta
from html import escape

DAYS_NOTIFY = 3

SES_SECRET = os.getenv('SES_SECRET')
SES_KEY = os.getenv('SES_KEY')
if SES_SECRET == None:
    print("Please set SES_SECRET to an AWS SES secret key")
    exit(-1)
if SES_KEY == None:
    print("Please set SES_KEY to an AWS SES access key")
    exit(-1)

def send_notification(card, pending_days):
    notify_emails = {}

    board_title = myboards.find({"_id":card["boardId"]})[0]["title"]

    owner = myusers.find({"_id":card["userId"]})[0]
    notify_emails[owner["username"]] = owner["emails"][0]["address"]

    for person in card["assignees"]:
        found = myusers.find({"_id":person})[0]
        notify_emails[found["username"]] = found["emails"][0]["address"]

    if pending_days < 0:
        subject = "Overdue task ("+str(pending_days*-1)+" days late)"
    elif pending_days == 0:
        subject = "Task will be overdue today"
    else:
        subject = "Task will soon be overdue ("+str(pending_days)+" days)"

    subject += ": " + escape(card["title"])[:30]

    message = "<table><tr><td>Status</td><td>"+subject+"</td></tr>"
    message += "<tr><td>Due on</td><td>"+card["dueAt"].strftime("%Y-%m-%d")+"</td></tr>"
    message += "<tr><td>Board</td><td>"+board_title+"</td></tr>"
    message += "</table>"

    notify_emails = list(notify_emails.values())
    message = emails.html(html=message, subject=subject, mail_from="wekan@your-domain.com",)

    # Send the email
    r = message.send(to=notify_emails, smtp={ "host": "email-smtp.us-east-1.amazonaws.com", "port": 587, "timeout": 5, "user": SES_KEY, "password": SES_SECRET, "tls": True, },)

myclient = pymongo.MongoClient("mongodb://localhost:27019/")
mydb = myclient["wekan"]
myusers = mydb["users"]
mycards = mydb["cards"]
myboards = mydb["boards"]
today = datetime.today()
today = today.replace(hour=0, minute=0, second=0, microsecond=0)
gt_date = today - timedelta(days=5)

for card in mycards.find({"dueAt":{"$gt":gt_date}}):
    pending_days = (card["dueAt"] - today).days
    if pending_days <= DAYS_NOTIFY:
        send_notification(card, pending_days)
`

**Comment by xet7** [comment]
@lucaslgithub 

I added link to your code to https://github.com/wekan/wekan/wiki/Python

**Comment by xet7** [comment]
Moved to #2026
