### ISSUE TITLE
Worker cannot select himself in Assignee field

### ISSUE THREAD

**Issue by serberman** [wekan/wekan#3546]
When a Worker changes Assignee field, they see and select their account from the dropdown, but the card is still assigned to the Admin

**Comment by mbcon** [comment]
Hi,
any news on this one? I am using Gitea 1.16.x on Docker and the issue can be reproduced.

Thx in advance,
mbcon

**Comment by mbcon** [comment]
Hi,
any news on this one? I am using Wekan 5.97.0 on Docker and the issue can be reproduced.

Thx in advance,
mbcon
