### ISSUE TITLE
When I was in build wekan, this happened. How can I solve this problem?

### ISSUE THREAD

**Issue by xuguotong** [wekan/wekan#3550]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /app/2-testkanban/kanban/.build/bundle/programs/server/package.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/app/2-testkanban/kanban/.build/bundle/programs/server/package.json'
npm ERR!  [Error: EACCES: permission denied, open '/app/2-testkanban/kanban/.build/bundle/programs/server/package.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/app/2-testkanban/kanban/.build/bundle/programs/server/package.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/rebuild-wekan.sh#L82-L97
