### ISSUE TITLE
Can not add Organizations (Javascript Error)

### ISSUE THREAD

**Issue by Treyfane** [wekan/wekan#3555]
## Issue
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
* Did you test in newest Wekan?: Yes, v4.95
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version: 4.95, also tried 4.90
* Operating System: Debian
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node Version: 10.15.1
* MongoDB Version: 4.4 as per docker install 
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox 85.0, Safari 14.0.3

**Problem description**:
Upon trying to add a new Organization as Administrator, a javascript error is produced onclick "Save":

Uncaught ReferenceError: email is not defined
    submit https://URL(redacted)/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:651
    e/t.prototype.events/r[i]</</< https://URL(redacted)/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:159
    _withTemplateInstanceFunc https://URL(redacted)/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:159
    e/t.prototype.events/r[i]</< https://URL(redacted)/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:159
    i https://plan.furcom.org/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:159
    _withCurrentView https://URL(redacted)/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:159
    i https://plan.furcom.org/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:159
    delegatedHandler https://URL(redacted)/7a550c0c4069ccca61663e3dd37fadf4e5e3682b.js?meteor_js_resource=true:159

**Comment by xet7** [comment]
Oops. Maybe I should sometime write that code that actually saves that organization.

Moved to #802
