### ISSUE TITLE
Need a version number somewhere on the front page

### ISSUE THREAD

**Issue by green-coder** [wekan/wekan#356]
Currently (from what I saw in the live demo), the version of the installed WeKan is not displayed.

That would be nice to have it written somewhere, maybe in a corner on the front page.

**Comment by mquandalle** [comment]
Interestingly our friend at Rocket.chat (also an open-source Meteor application) encounter the same issue at https://github.com/RocketChat/Rocket.Chat/issues/1111

**Comment by jseadragon** [comment]
+1, was looking for this earlier on my install
