### ISSUE TITLE
Coloured cards on "Modern" theme are completely white with no next visible.

### ISSUE THREAD

**Issue by danielwilson654** [wekan/wekan#3565]
I really like the modern theme,I want to use it everywhere! however, colored cards go white when the theme is activated for some reason. Please see attached gif.

## Issue

**Server Setup Information**: **Docker**
* Did you test in newest Wekan?: **Yes**
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? : **Firefox**

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek* 
![recording](https://user-images.githubusercontent.com/17303371/107717799-94f2ed80-6d28-11eb-8638-86b0784b4613.gif)

- *Explain steps how to reproduce* Set board theam to "modern", set card colour.

**Comment by danielwilson654** [comment]
Not sure why the gif uploaded twice.. can't remove it.

**Comment by danielwilson654** [comment]
@xet7 @helioguardabaxo Thanks guys for the fix and merge :D

**Comment by 1ubuntuuser** [comment]
NICE! fix confirmed. @xet7 @helioguardabaxo 
![recording(3)](https://user-images.githubusercontent.com/17303371/108001301-22dc1a80-7040-11eb-997c-9123b332fcd3.gif)

**Comment by helioguardabaxo** [comment]
Thanks for your feedback! :smiley:
