### ISSUE TITLE
WebHooks - act-setCustomField returns `undefined` in the text field 

### ISSUE THREAD

**Issue by n8ores** [wekan/wekan#3574]
## Issue

I am able to receive WebHooks just fine, however, when I modify a cards custom field (SatNo), I get the following information:

```
{ text:
   'My Admin edited custom field SatNo: undefined at card "test card" at list __list__ at swimlane __swimlane__ at board "Test Board"\nhttp://<my_url>/b/pjnHFYqAgRr9vP4Ri/test-board/8QpsjcouAHvF86w55',
  cardId: '8QpsjcouAHvF86w55',
  boardId: 'pjnHFYqAgRr9vP4Ri',
  user: 'My Admin',
  card: 'test card',
  description: 'act-setCustomField' }
```

Obviously receiving undefined is not the intended result.

Using **Two-Way Webhooks** gives more information, but still not the value of the changed field.

```
{ description: 'act-setCustomField',
  activityId: 'kT2MQo7YQovpSMPBf',
  user: 'My Admin',
  userEmails: [ { address: 'info@myemail.com', verified: false } ],
  userId: 'ugRhpvFFtSmRwK7L5',
  board: 'Test Board',
  url:
   'http://<my_url>/b/pjnHFYqAgRr9vP4Ri/test-board/8QpsjcouAHvF86w55',
  boardId: 'pjnHFYqAgRr9vP4Ri',
  card: 'test card',
  cardId: '8QpsjcouAHvF86w55',
  customField: 'SatNo',
  watchers: [] }
```

What is worse, is the WebHook for act-setCustomField **does not** return the **listId** for the card! So I cannot even look up the card's details manually using the REST API.

**Server Setup Information**:

* Did you test in newest Wekan?: YES
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? YES
* Wekan version: 
Wekan Version | 4.96.0
-- | --
2.0
12.20.2
4.4.3
wiredTiger 
Linux
linux
x64
4.19.128-microsoft-standard
3 hours, 14 minutes, 58 seconds
0.01, 0.03, 0.00
37 GB
33 GB
12

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker-compose
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: 10.23.3
* MongoDB Version: 4.4.3
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome

**Comment by xet7** [comment]
@n8ores 

Please check that those `act-setCustomField` and other fields are at [activities](https://github.com/wekan/wekan/tree/master/client/components/activities) and [translation source language English file](https://github.com/wekan/wekan/blob/master/i18n/en.i18n.json). Also, you can search code with for example:
```
cd wekan

./find.sh act-setCustomField

./find.sh activities
```
If there is something missing, please add it and provide [pull request like this](https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin) (please ignore emoji and plugin related stuff at that page, actual info is creating pull request).

**Comment by dudeofawesome** [comment]
Looks like this is a known issue: https://github.com/wekan/wekan/blob/49df8f4b4312a389ff8201b521ac891c414448dc/models/customFields.js#L200-L214

**Comment by xet7** [comment]
Hmm, lets check:
```
$ git blame customFields.js | grep bug
5283ba9eb (Lauri Ojansivu     2019-06-27 04:06:21 +0300 200) // This has some bug, it does not show edited customField value at Outgoing Webhook,
```
Doh, I wrote that comment myself :smile:

**Comment by dudeofawesome** [comment]
I've been trying to fix this myself, but I'm struggling to figure out how exactly the new doc gets inserted in to the activities collection. As far as I can tell, that code I linked above is dead?

**Comment by n8ores** [comment]
What do you mean by dead?

**Comment by dudeofawesome** [comment]
Dead as in it never gets run. I'm not familiar with Meteor though, so I could be missing something.
Regardless, I think I just found a solution to getting the listId and swimlaneId values passed to webhooks. Should have a PR incoming shortly.

**Comment by n8ores** [comment]
OK I was able to debug and find the issue.

I will do a pull request.

**Comment by n8ores** [comment]
OK I was able to fix this bug, and while I was at it, I added the customField and customFieldValue to the webhook data as well. There was no good reason to not be passing this back to the user.

**Comment by n8ores** [comment]
> Dead as in it never gets run. I'm not familiar with Meteor though, so I could be missing something.
> Regardless, I think I just found a solution to getting the listId and swimlaneId values passed to webhooks. Should have a PR incoming shortly.

While I was debugging this I confirmed your theory that this code in fact is never called. In-fact I am nearly certain we can remove a lot of redundant code out of the models/customFields.js and clean it up considerably. I will get onto that when I get some free time.

**Comment by dudeofawesome** [comment]
Sorry I didn't get to sending you those patches, but it sounds like you've got it figured out!

Do you know if that's made it in to a release of the docker image?

**Comment by xet7** [comment]
@dudeofawesome 

No, [those pull requests](https://github.com/wekan/wekan/pulls) have not been merged yet. You will see from [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md) when those have been merged in near future, and then check is that Docker release tag built at [Docker Hub](https://hub.docker.com/r/wekanteam/wekan/tags?page=1&ordering=last_updated) or [Quay](https://quay.io/wekan/wekan).

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3584
