### ISSUE TITLE
OpenApi wekan.yml refers to external files

### ISSUE THREAD

**Issue by boekhoffj2801** [wekan/wekan#3578]
## Issue
Hello, our Wekan board is running.
I'm new to OpenApi and would like to generate a C# wrapper to access our wekan board. I found a swagger description file wekan.yml in the api subfolder. But If I try to use this file e.g. within NSwagStudio I get an System.InvalidOperationException: Could not resolve the path '#/definitions/UsersProfileNotifications'.

Within the wekan.yml there are several lines $ref: "#/definitions/xxxxxxx" which appear to be references to external files which can't be found...
Where can I find the missing definition files? Or is it possible to get one OpenApi file which includes all necessary definitions? Or may be there is an existing c# api that I could use?

(Wekan REST API  version: v4.96)

**Comment by xet7** [comment]
@boekhoffj2801 

- [OpenAPI was added here](https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+OpenAPI)
- [This script installs doc build dependencies](https://github.com/wekan/wekan/blob/master/releases/rebuild-docs-install-deps.sh)
- [This script builds OpenAPI docs](https://github.com/wekan/wekan/blob/master/releases/rebuild-docs.sh)
- [Gerated docs are here](https://wekan.github.io/api/)
- [Also see trojan warning about that generation code](https://github.com/wekan/wekan/issues/2545)

If you have improvements or any other new way to build OpenAPI docs with any programming language, please send pull request.

**Comment by boekhoffj2801** [comment]
Thank you. In the meantime I found out that #/definitions/UserProfileNotifications should point to a place in the document itself. All other references can be found. Only UserProfileNotifications is missing in our description file. Because I don't need notifications I added a dummy entry manually. So I was able to use NSwag to create a c# wrapper.
