### ISSUE TITLE
Local file permissions while uploading attachment may make it inaccessible

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3583]
Observed with:

Wekan Version	4.96.0
Meteor-Version	2.0
Node-Version	12.20.1
MongoDB-Version	4.4.3
MongoDB-Speicher-Engine	wiredTiger

When uploading a file as an attachment for a card, and this local file has restrictive file permissions like the effect of `chmod 204 myfile.pdf`, the attachment can not be downloaded anymore. Even Wekan itself seems to be unable to access the file since no large “PDF” or “DOCX” is printed to the attachment thumbnail.

The expected behaviour is that local file permissions should not be stored in the Wekan server and should not matter when interacting with the attachment.

**Comment by xet7** [comment]
Wow, nice find! Thanks a lot!

Could be related to #2635

**Comment by xet7** [comment]
Related #2759 #3110 #3628

**Comment by xet7** [comment]
@bronger 

Please upgrade to [Wekan v5.27](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v527-2021-04-29-wekan-release) where I fixed uploading and downloading Non-ASCII attachment filename, and test does upload/download of Non-ASCII attachment work. Also please test does local file permissions still affect ability to upload/download of files. Thanks!

**Comment by xet7** [comment]
Hmm, just a moment I also test this myself.

**Comment by xet7** [comment]
It seems this bug still exists. Attachment URL ends with `http://localhost:4000/.../oeps/null`

**Comment by xet7** [comment]
When in Firefox I try to File/Open that PDF file directly, I get this error, translated to English:
```
The file is not readable.

The file may have been deleted or moved, or you may not have access to it.
```
So it seems, I don't have enough permissions to add that file, so it adds null file, that does not exist.

**Comment by xet7** [comment]
So it seems file permissions are:
```
--w----r-- 
```
It shows I don't even have rights to read that file.

Also, when double clicking PDF file at file manager, it says:
```
Unable to open document “file:///.....pdf”.
Error opening file /home/.....pdf: Permission denied
```
So I can not open that PDF file at all.

Maybe there could be a way to detect null file somehow?

**Comment by bronger** [comment]
I am still suprised that the browser passes the information about local permissions to the JavaScript code in the first place. :-/
