### ISSUE TITLE
Impossible to export board to excel - exceeding 31 chars

### ISSUE THREAD

**Issue by mickappa** [wekan/wekan#3589]
Wekan Snap installed, latest:

Wekan Version: 4.96.0
Meteor: 2.0
Node: 12.20.2
MongoDB: 3.2.22 (wiredTiger)
Linux x64 - 4.19.0-14-amd64

Problem description:
When on any board, going to Export board -> Export to Excel-> nothing happens, no excel is proposed to save.

Wekan Snap Logs:

Feb 19 13:27:55 wekan wekan.wekan[29662]: Worksheet name "Worksheet_name" exceeds 31 chars. This will be truncated
Feb 19 13:27:55 wekan wekan.wekan[29662]: (node:30887) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'properties' of undefined
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at ExporterExcel.build (models/exportExcel.js:228:8)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at models/exportExcel.js:43:21
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at doCall (packages/meteorhacks_picker.js:128:14)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at processNextRoute (packages/meteorhacks_picker.js:90:14)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at processNextRoute (packages/meteorhacks_picker.js:92:9)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at packages/meteorhacks_picker.js:162:10
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at /snap/wekan/1350/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Feb 19 13:27:55 wekan wekan.wekan[29662]: (node:30887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 46)

**Comment by xet7** [comment]
Can you change your board name be 31 characters or less, and then try export to Excel again?

If that does not help, please send example export to JSON files of those boards that can not be exported from Wekan to Excel from free https://protonmail.com email to my paid Protonmail Wekan Support email address support@wekan.team (email is automatically encrypted between Protonmail accounts) so I can fix that bug.

**Comment by mickappa** [comment]
Hello Lauri,

renaming the board works as expected and excel file gets exported correctly.
Is there any way to make it work for board names exceeding 31 chars?
Or at least throw out an error instead of silence?

**Comment by mfilser** [comment]
I think exceeding of 31 chars is not possible because it's a Excel limitation:
![grafik](https://user-images.githubusercontent.com/13166201/108728467-eb7ed980-7529-11eb-8e2d-9a2f0e100b98.png)

Maybe cutting at 31 chars would be better, but i think xet7 has also some idea's :)

**Comment by xet7** [comment]
In think that with code, I will do this:

a) If cell content is 31 chars or less, just add it.
b) If cell is over 31 chars, and has spaces (that is so nice!), then I just split string by space and add as many cells as needed, with as many parts of string that fits to each cell.
c) If cell does not have any spaces (that is not so nice!), then I just cut string to pieces of 31 characters, and add as many cells that are needed to view all characters.

Also while coding this, I'll add formatting so that each cell is so wide that it will show all 31 characters without requiring to make some rows and columns wider. And test that it does work at least with Excel and LibreOffice Calc.
