### ISSUE TITLE
Feature Request: Search All Boards / Checklists

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3590]
Hi,
it seems Search All Boards does not search Checklists text.

Related question [at Discussions](https://github.com/wekan/wekan/discussions/3588):

From @ClaudiaK21

> Is it possible to search only for cards which have **Checklists** in the global board search?
>
> How can I do this?

Maybe if @jrsupplee sometime has time to implement this. If not, I could maybe look at this sometime.

**Comment by jrsupplee** [comment]
This can be done, but it will make the search more expensive.

Two more collections will have to be searched: `Checklists` and `ChecklistItems`.

**Comment by jrsupplee** [comment]
The other issue is checking for existence of a checklist on a card.  This would probably best be implemented with a new operator.

Maybe a `has:` operator.

```
has:checklist
has:attachments
has:description
```

**Comment by xet7** [comment]
Yes, everything is expensive:
- Time is expensive. Once spent, it's not coming back.
- Wekan is expensive. Each new feature and fix makes Wekan more valuable, and adds more code to maintain. Maintaining takes time.

**Comment by jrsupplee** [comment]
Hmm.  Trying to figure out if you understood me.  What I meant was that with a nosql (non-relational) database you often end up querying the database several times for what would be a single query in a relational database.  I think the global search does a minimum of 4 database queries for each search.  Searching checklists will add two more queries.  So the new minimum will be six.  On my small data set it is imperceptible, but I am worried that with large datasets it will become cumbersome.  Especially given the way the queries are put together.

I will send a parch for searching *checklists*.  The code is very easy.

**Comment by xet7** [comment]
Steps are, according to [Kent Beck](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast), there is also some [background images about this](https://quotefancy.com/quote/1663435/Kent-Beck-Make-it-work-make-it-right-make-it-fast):

1. Make It Work
2. Make It Right
3. Make It Fast

So at first, it's enough it kind of works, for small datasets.

If some Wekan users have large datasets, they should participate in sending pull requests for optimizations, or participate to funding optimizations.

**Comment by xet7** [comment]
Also, features should first exist. Before that, there is nothing to optimize yet. For contributors usually optimization does not matter at first, because someone (like me or some other contributor) will later optimize it on parts of code where is the bottleneck.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3597 , I presume. Will be at next release.
