### ISSUE TITLE
Token to download attachments by Rest API

### ISSUE THREAD

**Issue by vagnernascimento** [wekan/wekan#3596]
## Issue

I am able to get the board attachment list using the route /api/boards/:board-id/attachments 
The expected results was something like this:
```
[ {
        "attachmentId": "hq25Hq8hu2op9nDLz",
        "attachmentName": "CAT.pdf",
        "attachmentType": "application/pdf",
        "url": "https://myserver/cfs/files/attachments/boardidhere/CAT.pdf",
        "urlDownload": "https://myserver/cfs/files/attachments/boardidhere/CAT.pdf?download=true&token=",
        "cardId": "59hCKaNPNm6HJCTjQ",
        "listId": "pnfytDuayauvYRzoF",
        "swimlaneId": "NRjPxdBkBDmiimpcZ"
    } ]
```
However I don´t know how to get the **token** (the last attribute on **urlDownload**) to download the file. I had tryed use the same token of header Authorizaton but not work. 

Can anyone help me, please?

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?:
Yes

* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
Yes

* Wekan version:

4.96.0

* Operating System:

Linux

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
 
Docker

* Node Version:

12.20.2

* MongoDB Version:

4.2.12

**Comment by vagnernascimento** [comment]
Hi @xet7,
Could you help me about this question?
Thanks,

**Comment by xet7** [comment]
Moved to #1482
