### ISSUE TITLE
German translation of due:n in the Global Search is not correct

### ISSUE THREAD

**Issue by ClaudiaK21** [wekan/wekan#3601]
## German translation of due:n in the Global Search

**Problem description**:
The Global Search Page information translation for
due:n - cards which are due  n  days from now

Current German is:
Fällig:n - Karten, die seit  n  Tagen überfällig sind

Correct translation and what result is displayed would be:
Fällig:n - Karten, die **bis in**  n  Tagen **fällig** sind

Thanks in Advance. I hope I posted this in the right section.

I wonder, because also the cards which are "overdue" up to now + the days until  n   are given in the results, so maybe the English description and all others might can get an optimization too.

**Comment by xet7** [comment]
@ClaudiaK21 

Translations are done at https://transifex.com/wekan/wekan . Can you join there and try to fix it yourself?

**Comment by ClaudiaK21** [comment]
Ok, yes I can, but how can I find this string? 
I'm logged into transifex now, but cannot find this part. Its in the global search description.

**Comment by ClaudiaK21** [comment]
Done

**Comment by xet7** [comment]
Thanks!
