### ISSUE TITLE
Mongodb doesn't start

### ISSUE THREAD

**Issue by gurretp** [wekan/wekan#3603]
Hi, 

it seems that the 4.98 release broke mongodb in the snap package. Wekan and its database don't start anymore: 

Feb 25 08:38:09 XXX wekan.mongodb[2819839]: mongodb bind options:  --bind_ip 127.0.0.1 --port 27019
Feb 25 08:38:09 XXX wekan.mongodb[2819839]: Sending mongodb logs to /dev/null
Feb 25 08:38:09 XXX wekan.mongodb[2819839]: Error parsing command line: unrecognised option '--bind_ip'
Feb 25 08:38:09 XXX wekan.mongodb[2819839]: try 'mongo --help' for more information

Upgrading to 4.99 this morning didn't fix the problem

Thank you

**Comment by xet7** [comment]
Hmm?
```
$ snap install wekan
2021-02-25T08:53:37Z INFO Waiting for automatic snapd restart...
wekan 4.99 from Lauri Ojansivu (xet7) installed
$ snap logs wekan.mongodb
2021-02-25T08:53:49Z wekan.mongodb[1708]: mongodb bind options:  --bind_ip 127.0.0.1 --port 27019
2021-02-25T08:53:49Z wekan.mongodb[1708]: Sending mongodb logs to /dev/null
```
Try starting mongodb?
```
sudo snap start wekan.mongodb
```
Or update your system. It works for me on Ubuntu 20.10. What Linux version you have?

**Comment by dragonnn** [comment]
I just hit the same issue, @gurretp how did solve this?

**Comment by gurretp** [comment]
Rebooting the server fixed the issue. I am running centos 8.3.  Restarting the different snap module didn’t solve anything.

**Comment by dragonnn** [comment]
Strange... I am not lucky with restarting my server and wouldn't prefer finding a cause of this.

**Comment by dragonnn** [comment]
So I found a workaround to avoid restarting my server.
I created a snapshot using snap save.
Then I complete removed snap from my system, delete all its data and made sure all mounts of it are umount/services stooped.
Installed snap back, did a clean install of wekan, this already fixed starting mongodb.
Then I restored the snapshot and everything worked.
What a hassle... but at least it is working.
