### ISSUE TITLE
Issue - CustomFields are not working anymore on any boards - Can't Update or delete it.

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#3613]
## Issue
Wekan version: last version
Deployment Method :snap
Webbrowser version :Chrome Version 88.0.4324.146 (Build officiel) (64 bits)

**Problem description**:
1- When I try to modify the value of a custom field in a card, the change is not saved
2- When I try to elete a customfields for the Board, it is not deleted

⚠️  It happens for all our cards in all our boards and for all custom fields.

See video : https://user-images.githubusercontent.com/74183327/109302616-d3fd6480-7839-11eb-82fc-3a175f60bd63.mp4

**Comment by xet7** [comment]
Please upgrade to Wekan v5.01 where this is already is fixed.

I will keep this issue open until all releases of Wekan v5.01 has finished building and have been released.

**Comment by marcungeschikts** [comment]
Great..Kiitos

**Comment by xet7** [comment]
That typos was fixed here https://github.com/wekan/wekan/pull/3610

**Comment by marcungeschikts** [comment]
I confirm it is fixed....thanks a lot
