### ISSUE TITLE
"Internal Server error" when registering 1st user and email sending is not configured yet

### ISSUE THREAD

**Issue by maltsev-gorskij** [wekan/wekan#3616]
**Server Setup Information**:

* Did you test in newest Wekan?: Yes. Latest images from https://hub.docker.com/r/wekanteam/wekan
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 5.01.0
* If this is about old version of Wekan, what upgrade problem you have?: no
* Operating System: Ubuntu 20.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker Compose
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): direct access to wekan-app container
* MongoDB Version: 4.4
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? 87.0.4280.67 (x86_64)

**Problem description**:
- Exception in wekan-app container during first creation of administration user. At account creation window error appears "Internal server error"

*Explain steps how to reproduce*

- git clone https://github.com/wekan/wekan.git
- change in docker-compost.yml root url to one that match server dns address
- docker-compose up -d
- access wekan gui with url
- click on "registration" button and full in all fields
- click "registration"
- above text field appears error "Internal Server Error"
- in docker logs exception appears
- 
```
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Sat Feb 27 2021 09:32:19 GMT+0000 (Coordinated Universal Time)","time":{"$date":1614418339511},"level":"info"}
Exception while invoking method 'ATCreateUserServer' Error: connect ECONNREFUSED 127.0.0.1:587
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

**Comment by maltsev-gorskij** [comment]
Despite this error user creates successfully and be able to login. But this is not normal that user need to ignore this error and go back to login window to proceed in Wekan.

**Comment by TBG-FR** [comment]
Encountered the same issue today, still there. Do you know what is supposed to be on `127.0.0.1:587` ?

**Comment by xet7** [comment]
@TBG-FR 

Email settings:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

If email settings are not defined, it gives error, but user account is created anyway. For using Wekan, it is not required to define working email settings, user accounts can be created anyway.

**Comment by kaipee** [comment]
> For using Wekan, it is not required to define working email settings

The email field should be marked as (Optional) on the Registration web form
