### ISSUE TITLE
Dockerized Wekan E-Mail sending failures

### ISSUE THREAD

**Issue by mbalmer** [wekan/wekan#3621]
## Issue

After restarting the dockerized wekan I can send a few emails to myself as a test, but then email sending stop I keep getting an obscure error message:

Senden der E-Mail fehlgeschlagen
Fehler beim Senden der E-Mail: 139907884001088:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

**Comment by schoeke** [comment]
I get the same error in a non-dockerized server.

**Comment by schoeke** [comment]
Okay, for me it was solved by changing `smtps://...` to `smtp://...`.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#if-you-get-sslv3-protocol-error
