### ISSUE TITLE
Bug: Link at board title can not be edited

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3622]
Moved to here from https://community.vanila.io/wekan/bugs/cannot-rename-board-when-the-current-name-is-url~130adc6b-6a6c-49f2-8594-b8bb3281de2e

From jonesrussell42 and aiac:

eg. Board title: `www.example.com`

Normally clicking on the title/name of a Board activates an "edit in place" behaviour allowing you to rename the Board.

When the title/name of a Board is a URL like `www.example.com` it becomes an active link with no "edit in place" behaviour.

From aiac:

Stumbled upon this issue right now in Wekan 4.96.0. Workaround: use browser inspector on board page and remove <a> tag around board title - then you can click on title and change it.

@xet7 This issue also breaks ability to add "board link" card - instead of redirection to the board, it redirects to URL typed into title

**Comment by bbyszio** [comment]
Until it is fixed, you can use also another workaround. If you position the mouse pointer just below the URL, the edit window will open after clicking.
