### ISSUE TITLE
Email Benachrichtigungen funktionieren plötzlich nicht mehr

### ISSUE THREAD

**Issue by Wekan2020** [wekan/wekan#3625]
Guten Tag

Seit gestern bekommen unsere Wekan user keine Email Benachrichtigungen mehr, wenn sich auf der Karte was ändert und das obwohl die Karte auf beobachten eingestellt ist.

Wäre sehr froh wenn jemand helfen könnte.

Beste Grüsse

**Comment by jrsupplee** [comment]
There was a change made yesterday to email setup.  The program no longer reads the values in the database.

Mail must be configured using the `MAIL_URL` and `MAIL_FROM` environment variables.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
