### ISSUE TITLE
Feature Request: Checklist Item due dates/reminders

### ISSUE THREAD

**Issue by 88fingerslukee** [wekan/wekan#3627]
I apologize if this is in the wrong place or has already been asked but I couldn't find anything so I'm asking here. I'm hoping to request a feature.  

I'd love to see due dates and reminders for individual checklist items. Trello has this functionality in their paid version (see image below)

![image](https://user-images.githubusercontent.com/2788639/109855682-6ff9e800-7c0d-11eb-967a-c745af138548.png)

Thanks for all your hard work on such a great product!!

**Comment by xet7** [comment]
@88fingerslukee 

Please add more screenshots or screenshots mockups about how it works. I don't have paid Trello account.

**Comment by 88fingerslukee** [comment]
https://help.trello.com/article/942-how-to-use-advanced-checklists-to-set-due-dates-and-add-members-to-checklist-items 

I don't have a paid membership either anymore. Does this link help?

**Comment by xet7** [comment]
@88fingerslukee 

Yes. Thanks!

**Comment by AdriDevelopsThings** [comment]
Will the feature be built in? When yes, when and whats the priority from the developers to this feature here?
What can I do to speed the development up?

**Comment by xet7** [comment]
@AdriDevelopsThings 

Anyone that has written any code can read Wekan source code https://github.com/wekan/wekan , develop any feature or fix, and send pull request. These Wekan issues, wiki etc has many answers already for development related questions. [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md) has info about who has sent pull requests. All contributors that send pull requests do speed up development.

As maintainer of Wekan, I already have huge workload, and a long todo list at [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license).

**Comment by xet7** [comment]
When compared to Trello and Jira, those are not Open Source, and it's not possible to add feature or fix any bug in Trello and Jira. Wekan already is translated to 56+ languages, much more than Trello and Jira.

**Comment by xet7** [comment]
Moved to #4755
