### ISSUE TITLE
Move all user that already have a login with local password to LDAP authentication

### ISSUE THREAD

**Issue by mdemori** [wekan/wekan#3638]
## Issue

Email settings:
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Add these issues to elsewhere:
- SECURITY ISSUES: https://github.com/wekan/wekan/blob/master/SECURITY.md
- UCS: https://github.com/wekan/univention/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**Problem description**:

After an initial test with some people, we have moved all login to LDAP authentication. Now seem that all user that has been used as tester for the inizial trial, are unable to login with the domain credentials.
These user are initially have password as "Authentication method", now if i change manually the autentication to LDAP seem that the login is not possible anymore.
How can I set the ldap login without deleting the users?

thank you

**Comment by xet7** [comment]
@mdemori 

You can look at wekan database users collection/table with [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup) to see what is difference between working password and LDAP user, and do required changes.

**Comment by xet7** [comment]
At Admin Panel you can choose default authentication method etc.
