### ISSUE TITLE
Card links don't include port

### ISSUE THREAD

**Issue by mneilly** [wekan/wekan#3639]
## Issue

When modifying docker-compose.yml to change the port for the wekan service from "80:8080" to "3001:8080" most of the links work and point to localhost:3001 but the card links point to localhost not localhost:3001. This results in a 404 error when clicking on the cards.

**Server Setup Information**:

The  docker image:
wekanteam/wekan    latest    d07c0f30fe3f   5 hours ago     748MB

**Problem description**:

$ git clone https://github.com/wekan/wekan.git
$ cd wekan
$ sed -i 's/80:8080/3001:8080/g' docker-compose.yml 
$ docker-compose up
connect to localhost:3001
Register
Login
Add board
Add list
Add card
Click on card

https://user-images.githubusercontent.com/5897087/110189856-8bafea80-7dd5-11eb-8050-f022ef3bd4ba.mp4

**Comment by xet7** [comment]
```
ROOT_URL=http://localhost:3001
```

**Comment by mneilly** [comment]
Ah, that works. Thanks.
