### ISSUE TITLE
Display board name in page title

### ISSUE THREAD

**Issue by xavierpriour** [wekan/wekan#364]
Trello uses '[board name] | Trello' as page title, this is very helpful when you have multiple boards open in  different tabs.

Would be great if Trello had this. I'm open to doing the PR, but I'll need some guidance as I already tried a few things that failed miserably :(

**Comment by mquandalle** [comment]
That’s a good idea! Yes, having a variable in the HTML `<head>` is not that easy on Meteor (but I’m pretty sure there are good packages to do set the page reactively). I’ll take a look.

**Comment by mquandalle** [comment]
https://github.com/tomwasd/flow-router-seo/ looks reasonable.

**Comment by mquandalle** [comment]
Hum, or maybe https://github.com/kadirahq/meteor-dochead
