### ISSUE TITLE
Importing Large Boards

### ISSUE THREAD

**Issue by nickian** [wekan/wekan#3649]
Why must we copy and paste JSON vs having a file upload? This is inconvenient, plus whenever I try to import a large board with images, etc, from a JSON export, the browser just freezes and the import doesn't happen. Is there another way to import a large board via the command line or something of the sort?

**Comment by xet7** [comment]
@nickian 

Mass import [has already been funded](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/RNTZ8NAm46mAeEDev) but not implemented yet. With it, Wekan will use Trello API to import directly all boards etc from Trello via Trello API, using Trello API key, without any copy-paste. Mass Import will be implemented sometime in near future, after I have first made more speed improvements.
