### ISSUE TITLE
Email notification, showing 127.0.0.1 instead of domain

### ISSUE THREAD

**Issue by ChrisFredriksson** [wekan/wekan#3654]
## Issue

**Server Setup Information**:

Wekan version 5.05.0
Meteor-version 2.1
Nodversion 12.21.0
MongoDB-version 3.2.22
MongoDB-lagringsmotor wiredTiger
OS Typ Linux
OS Arch x64
OS utgåva Debian 4.19.0-14-amd64

**Problem description**:
Email I get (notification email) when someone or myself updates the board gives the following link;
http://127.0.0.1/b/PZbwuCTSo4bALNDno......

Is it possible to configure this somehow, somewhere to https://wekan.domain.tld/b/PZbwuCTSo4bALNDno...... instead?

**Comment by xet7** [comment]
root-url https://github.com/wekan/wekan-snap/wiki/Install#3-install-wekan-set-url-like-subdomainexamplecomsuburl
