### ISSUE TITLE
My cards empty when logged out

### ISSUE THREAD

**Issue by iwkse** [wekan/wekan#3655]
## Issue

When a user isn't logged in, the my-cards page should redirect to login, right now it shows an empty content

**Comment by jrsupplee** [comment]
I have noticed this as well and have also seen the same behavior on other pages.

**Comment by jrsupplee** [comment]
@xet7 

I could add:
````
  triggersEnter: [AccountsTemplates.ensureSignedIn],
````

to the `Flowrouter.route()` entry in `router.js` so only logged in users can access it.  This is probably fine for *My Cards*, but what about *Due Cards* and *Global Search*?

**Comment by xet7** [comment]
@jrsupplee 

Yes you can add to all those.

**Comment by xet7** [comment]
@jrsupplee 

Actually, there's one more somewhere. Usually, if user is not logged in, Wekan ROOT_URL address shows something else than login page. It should usually redirect to /sign-in if user is not logged in.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3677
