### ISSUE TITLE
BUG: login is sometimes not working

### ISSUE THREAD

**Issue by chrisi51** [wekan/wekan#3658]
Users come from time to time to me and tell me that their login is not working. they tried multiple times to login and its just not working. mostly i send them the main page url again (without the "/sign-in") and than its mostly working. 

Seems like there is something not working from time to time and if you are on the sign-in url and its not working than you can try as often as you want but your login will not work. Only getting back to the main page in a new tab or stripping manually the part from the url leads to a working login.

i have no clue what this can cause but maybe you have an idea?

we are using ldap from univention ucs but i guess this is a more general problem?! The problem occured first time as we started using wekan ... so its really old ... at least one year i guess .. and so it can't be an issue of recent changes.

i can't give you more information as personally me don't have this problem but my users from time to time.

**Comment by xet7** [comment]
@chrisi51 

Try deleting brute force prevention logs:
https://github.com/wekan/wekan/issues/3306#issuecomment-713329885

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Accounts-Lockout

**Comment by chrisi51** [comment]
as we use ucs im not sure if i can use this :(

**Comment by xet7** [comment]
@chrisi51 

Of course you can. You just ssh your ucs VM like this, with same username password you used when installin UCS and administering UCS apps, su to root:
```
ssh Administrator@192.168.0.100
su
```
And then use those Docker commands https://github.com/wekan/wekan/issues/3306#issuecomment-712743002
