### ISSUE TITLE
Some user cant "move card" to another board

### ISSUE THREAD

**Issue by SperlingFP** [wekan/wekan#3659]
## Issue

On boards i created i can move cards to other boards - in the menu of the card  by chosing "move card" and then select "board", "swimlane" and "list".

It seems that other users i added to the board cant move cards because they dont see this option in the menu of the card. All they can do is copy and then chose board, swimlane and list - and then delete the card.

I cant find any way to change this, even if i "switch" the user to be "admin".

Am i blind?

**Comment by xet7** [comment]
@SperlingFP 

Ask those users, that when that happends, at browser right click / Inspect / Console, and copy all text from console to comment to this issue.

No, you are not blind. You were able to add new issue.

**Comment by SperlingFP** [comment]
they dont know wht to do and cant help .... i tryed with a new account, console in Chrome tell me

[Violation] 'message' handler took 502ms
[Violation] Forced reflow while executing JavaScript took 41ms
e12e1b5d42f612a0018e5d6cb9f080f65389d6e9.js?meteor_js_resource=true:179 [Violation] 'message' handler took 408ms

![image](https://user-images.githubusercontent.com/25441596/111984778-1dc12e00-8b0c-11eb-9cfd-9a73166f4e44.png)

**Comment by SperlingFP** [comment]
This user is admin

**Comment by SperlingFP** [comment]
On Board the user created it worked - "move card" is in context menue

**Comment by SperlingFP** [comment]
Next: These Users cant add decription to labels.

I am just a noob in Wekan, but this looks like a problem in the rights of users who did not create the Board

**Comment by bbyszio** [comment]
I've just tested it in my instance (newest Snap-Version 5.07) and i can't see this problem. We have now 110 user in the system and the most of them are working in boards which they have'nt create by them selve. We don't have this problem.

Are you using the Snap-Version too?
