### ISSUE TITLE
Unable to upload attachments (images/pdf) to Wekan card

### ISSUE THREAD

**Issue by ChrisFredriksson** [wekan/wekan#3664]
**Server Setup Information:**

Wekan version 5.05.0
Meteor-version 2.1
Nodversion 12.21.0
MongoDB-version 3.2.22
MongoDB-lagringsmotor wiredTiger
OS Typ Linux
OS Arch x64
OS utgåva Debian 4.19.0-14-amd64

**Problem description:**
I'm unable to upload image (primarily) but also any other file type to a card in Wekan. It seems that the placeholder information is created properly, as seen in the below image. Wekan knows the name of the file and if I click on the file square, inside the card, the black/dark popup comes up with the rotating waiting thingie in the middle but never loads the file.

Also as seen in the image below, no preview is shown for the image, ok its an pdf I show in the image, but it is the same with images. Also setting the image as cover image does not do anything and the "download" link for the image does not work either.

So I guess that the file is not found on the server, meaning it isn't uploaded correctly?

Is there yet another setting I've missed or is this simply a bug?

![upload](https://user-images.githubusercontent.com/33225247/111958260-4d147280-8aed-11eb-8c58-ec1e73293141.png)

**Comment by solunix** [comment]
I can confirm that. Same behavior at our site, but still can not say when it happens. Some PDF are showed and could be open, next can not. Our PDF are very small, because they are Vector-Drawings. I thought it is a problem with the reverse Proxy first, but I can not found any related log entry in apache.

**Comment by urmel1960** [comment]
I made a quick check here.
PDF can be uploaded and retrieved - as long as you download and open them in the desktp app. Pictures (jpg,svg,png) are fine as far as I could test quickly. They get rendered properly in the browser. Video mp4 do not render properly - see behaviour pdf and docx. 
Opening pdf with double click in the browser end up in the behaviour described by ChrisFredriksson.
Double clicking docx in the card failed too - browser tried to render the file - same  behaviour as with pdf.

**Comment by xet7** [comment]
Moved to #2635 and #1318
