### ISSUE TITLE
502 Bad Gateway when i try download attachment with cyrillic name

### ISSUE THREAD

**Issue by dvdent** [wekan/wekan#3679]
![Screenshot_10](https://user-images.githubusercontent.com/6939479/112946796-605bb980-914f-11eb-921f-348c01bd1a6a.png)

**Comment by dvdent** [comment]
<domain>/cfs/files/attachments/<id>/**наименование**.pdf?token=<tokenid>&download=true

**Comment by dvdent** [comment]
snap revert to 5.13 doesn't help, 
previously, these attachments were downloaded

**Comment by xet7** [comment]
@dvdent 

Thanks for info! I will keep this and related issues open until I have fixed this.

**Comment by xet7** [comment]
Moved to #2759
