### ISSUE TITLE
Cannot add users to second board

### ISSUE THREAD

**Issue by stoltenhoff** [wekan/wekan#3684]
Setup: 
I am using Wekan 4.75.0~2021-01-11 via Sandstorm and i have problems with a grain/installation, that contains two boards. 

Problem: 
I cannot add users to the second board. Everyone from my team is registred to the grain and also to the first board. But they do not see the second board and i am not able to add them as users too. (I tried to copy cards with users from the first to the second board. The copying went fine, their assigned users »moved« also, but that changed nothing to the problem.)

My steps to add users:
- I open the right drawer and click on the + icon to add users 
- Clicking on a user and set permissions to »member - can edit« (only option here)
- Clicking »connect« and pop up window is closing again 
- No changes to the users/avatars – i can see my avatar only

**Comment by xet7** [comment]
Oops, I really should spend some quality time to fix Sandstorm Wekan bugs.

Moved to #2405
