### ISSUE TITLE
SMTP NOT WORKING

### ISSUE THREAD

**Issue by cur1ou5soul** [wekan/wekan#3685]
## Issue

Hey guys I just cant get WEKAN to send any E-Mail the following I have tried:

1. G Mail Relay
smtp://smtp-relay.gmail.com:587?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false
-> Error EHLO HELO 421 (I allowed the ip of my server in gmail

2. G Mail Relay
smtps://smtp-relay.gmail.com:587
-> SSL3 ERROR

3. AMAZON SES 
smtps://XX:XX@email-smtp.eu-west-1.amazonaws.com:587
ERROR SENDING EMAIL EGAIN ADR INFO

Email settings:
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Other Wekan issues can be added here.

**Server Setup Information**:

Docker-Compose with wekanteam:wekan:latest and Mongodb 
Traefik is my proxy for wekan. 

Regards and thank you alot!

**Comment by xet7** [comment]
@cur1ou5soul 

SSL3 error:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#if-you-get-sslv3-protocol-error

**Comment by cur1ou5soul** [comment]
![image](https://user-images.githubusercontent.com/57013347/113133969-90bf5880-9220-11eb-9874-816a84140601.png)

Sorry I tried this already

**Comment by xet7** [comment]
@cur1ou5soul 

It seems that at my server settings, sending with SES also failed with error `getaddrinfo ENOTFOUND`.

So then I logged into AWS console, and checked settings. It seems that my DKIM settings had typo. I fixed that typo, clicked retry verification, and now I am waiting for results.

In CloudFlare DNS settings, I have Wekan subdomain with setting `DNS Only`.

This is what I currently use on Wekan Snap:
```
sudo snap set wekan mail-url='smtp://AKIAusername:password@email-smtp.eu-west-1.amazonaws.com:587?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false'
```

I will add more info later.

**Comment by cur1ou5soul** [comment]
Well I also could use smtp releay from Google but this didn't work either. :-(

**Comment by xet7** [comment]
Current progress:

Wekan uses Meteor email package:
https://docs.meteor.com/api/email.html

That uses nodemailer:
https://nodemailer.com/transports/ses/

Related tests here:
https://github.com/nodemailer/nodemailer/tree/master/test
https://github.com/nodemailer/nodemailer/tree/master/test/ses-transport
https://github.com/nodemailer/nodemailer/tree/master/test/dkim

If someone finds out what kind of nodemailer code successfully sends email with AWS SES, Google, or any other way, I can add it to Wekan.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses
