### ISSUE TITLE
 Elements are duplicated on the view "My card"

### ISSUE THREAD

**Issue by xavier-GitHub76** [wekan/wekan#3698]
Hello,

I'am a french new user of Wekan (sorry for my english, if i do mistakes)

On the view "My card", i have an issue.
The last elements are duplicated
![Duplicated](https://user-images.githubusercontent.com/82046143/113739886-86a9c800-9700-11eb-8fef-6897dd373cf6.png)

Thanks for the work done on this application.

**Comment by jrsupplee** [comment]
@xavier-GitHub76 

In which swim lane of the board *PRO* are the cards located?

**Comment by xavier-GitHub76** [comment]
The cards are located in differents swim lane of the board PRO.
The issue is only on "My cards", the main view is correct.

Le mer. 7 avr. 2021 à 00:29, John Supplee ***@***.***> a
écrit :

**Comment by jrsupplee** [comment]
> The cards are located in differents swim lane of the board PRO. The issue is only on "My cards", the main view is correct.

I have not seen this problem so I need to understand the exact structure of the cards in the board.  In which swimlane(s) do the duplicated cards appear on the board?

**Comment by xavier-GitHub76** [comment]
You could see an example with the following screenshots :

Sheets created :
#1
[image: SHEET 1.png]

#2
[image: SHEET 2.png]

#3 (with swim lanes)
[image: SHEET 3.png]

"Card 16" is in swim lane 2.
"Card 19" is in swim lane 3.

All cards are assigned to me.

The "My cards" view :
[image: MyCards.png]

"Card 16" is displayed in swim lane 3 instead of "Card 19"


Le dim. 11 avr. 2021 à 02:23, John Supplee ***@***.***> a
écrit :

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3708
