### ISSUE TITLE
Rules: "Remove value from date filed due" not working

### ISSUE THREAD

**Issue by mks-85** [wekan/wekan#3703]
Hi there,

OS: ubuntu 20.04
Wekan 5.17.0 installed by snap

Rule "Remove value from date filed due" not working with following rules setup.

Any Idea if I did a mistake when i created the rules or is this a bug in wekan?

![wekan1](https://user-images.githubusercontent.com/74009667/114200886-ebaa2b80-9955-11eb-96a0-50d82baf531b.jpg)

**Comment by jrsupplee** [comment]
I am seeing the same thing

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3706
