### ISSUE TITLE
Wekan v5.17 persistent datas

### ISSUE THREAD

**Issue by fredbcode** [wekan/wekan#3709]
Hello 

I'm testing wekan v5.17 with docker and mongo (latest image), I added ldap authentication and all works well 
Unfortunately some datas seems persistent 

For example, if I delete all my archived datas and press f5 my dashboards are undead !

![image](https://user-images.githubusercontent.com/5287473/114422705-cec06300-9bb6-11eb-9348-a6e10f5b0977.png)

But it can also be a dashboard removed from panel that appears again suddenly   

If I connect/disconnect same issue
It's unclear to me, if I missed something in configuration or not ? 

Maybe this is related if I add a dashboard, I must refresh otherwise I still looking the animated logo 

![image](https://user-images.githubusercontent.com/5287473/114423979-fd8b0900-9bb7-11eb-870c-d201089b3f3f.png)

Tested with FF 86, wekan v5.17, traefik 1.7.30, mongodb 4.4.5

**Comment by xet7** [comment]
If you delete those boards, but do not wait for them to be actually deleted (it takes some time) and immediately reload webpage, Yes, those are still not deleted. This is Optimistic UI https://blog.meteor.com/optimistic-ui-with-meteor-67b5a78c3fcf

**Comment by xet7** [comment]
@fredbcode 

Yes, please add separate issue.

Also, for both issues, add any debugging info, like at browser right click / Inspect / Console, copy all content to plain text editor, anonymize your Wekan domain, and copy-paste to issue comment.

**Comment by fredbcode** [comment]
Ok, I will made more tests before

**Comment by fredbcode** [comment]
I guess both are related 

Today the dashboards still archived, I tested with chromium and same issue (Ubuntu 18.04)

With debugger on, I'm seeing something weird there is no request at all in "network" 
If I delete or click on add a board there is nothing as I'm disconnected, I guess this is expected and related to wss

![image](https://user-images.githubusercontent.com/5287473/114515732-f78b3b80-9c3c-11eb-8bd3-efc229d8930b.png)

But if I press f5 (when the animated logo move without end) this new dahsboard appears in FF and also Chromium   

How I can investigate more ?

**Comment by fredbcode** [comment]
Request Header

GET wss://wekan.xx/sockjs/055/l_5mm26x/websocket HTTP/1.1
Host: wekan.xx
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Upgrade: websocket
Origin: https://wekan.xx
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: meteor_login_token=i71PVNuVIHffyj2_RRpW81NdBRnHlDTZGnURQsAHH0P
Sec-WebSocket-Key: qij5uLV9FH2yQFWOJMrpng==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits



Response Header

HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Sec-Websocket-Accept: mVe4muFQ1vvyBz0Ukh8BokDlBB4=
Sec-Websocket-Extensions: permessage-deflate
Upgrade: websocket

Console (after 3/4 minutes):
﻿
(index):1 Autofocus processing was blocked because a document already has a focused element.
10d0fcc……_js_resource=true:1 Exception from Tracker afterFlush function:
10d0fcc……_js_resource=true:1 TypeError: Cannot read property 'open' of undefined
    at n.openNewListForm (10d0fcc……s_resource=true:651)
    at n.onRendered (10d0fcc……s_resource=true:651)
    at h.TemplateInstance.onRendered (10d0fcc……s_resource=true:420)
    at 10d0fcc……s_resource=true:159
    at Function.t._withTemplateInstanceFunc (10d0fcc……s_resource=true:159)
    at i (10d0fcc……s_resource=true:159)
    at h.View.<anonymous> (10d0fcc……s_resource=true:159)
    at 10d0fcc……s_resource=true:159
    at Object.h._withCurrentView (10d0fcc……s_resource=true:159)
    at 10d0fcc……s_resource=true:159

**Comment by fredbcode** [comment]
Same without traefik, port 8080 directly exposed

**Comment by xet7** [comment]
@fredbcode 

Please [Backup](https://github.com/wekan/wekan/wiki/Backup) and install [Wekan Snap with Caddy](https://github.com/wekan/wekan-snap/wiki/Install) and [Restore](https://github.com/wekan/wekan/wiki/Backup) and try again.

**Comment by xet7** [comment]
@xavier-GitHub76 

At your Wekan board, after trying to delete file, please right click / Inspect / Console, and copy all those logs to comment to this issue. Thanks!

**Comment by xavier-GitHub76** [comment]
Here are the logs

[wekan.xcl060918.synology.me-1620419873485.log](https://github.com/wekan/wekan/files/6444181/wekan.xcl060918.synology.me-1620419873485.log)

**Comment by xet7** [comment]
@xadagaras 

Are you BoardAdmin at that board? Only BoardAdmin can delete attachments. Normal user etc can not. Permissions can be seen when hovering mouse over right sidebar avatar, and BoardAdmin can change permission by clicking avatar and changing permission.

**Comment by xavier-GitHub76** [comment]
Yes, I'm already admin.

**Comment by xavier-GitHub76** [comment]
Hello,
how can i force delete a file ?

**Comment by xet7** [comment]
@xavier-GitHub76 

Please make [Backup](https://github.com/wekan/wekan/wiki/Backup) first.

You could for example:
1) Create new Swimlane
2) Move cards, that have attachments to delete, to that new Swimlane
3) Move Swimlane to another board, like new board
4) Delete that new board

**Comment by xavier-GitHub76** [comment]
Thank you for your reply. Unfortunately, deletion does not work for me


Le mar. 6 juil. 2021 à 22:34, Lauri Ojansivu ***@***.***> a
écrit :

**Comment by xavier-GitHub76** [comment]
Thank you for your reply. Unfortunately, deletion does not work for me.

**Comment by xet7** [comment]
@xavier-GitHub76 

Another way is to delete attachment directly from database with DBGate or nosqlbooster. If running in docker, it requires opening port to mongodb 27017, or backup/restore of mongodump/mongorestore to another computer where same MongoDB version is running and port is open.

https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui

**Comment by xet7** [comment]
Alternatively, sometime those file related bugs will be fixes, in some future Wekan version.

**Comment by xavier-GitHub76** [comment]
Hello,
thanks for your answer.
I spent a few hours analyzing the problem (first use for me of MongoDB and discovering the structure of the Wekan database).

I discovered the cause of the problem: cfs.attachments.filerecord table contains fields not updated when moving cards.
If 
- the user has moved a card containing an attachment
- the board, from which the attachment was originally dropped, is deleted
then the deletion fails.

To reproduce the bug:
1. Create a board
2. Create a list
3. Create a card
4. Add an attachment
5. Move the card to another board
6. Delete the board created in step 1
7. Try to delete the card created in step 3 or the attachment created in step 4 ==> FAILED 

To correct the problem, it is necessary during a card move to update boardId of cfs.attachments.filerecord with the value of the board targeted by the move.

I manually corrected the values ​​of the few lines affected.
Deletions then work :)

You could see the detailed analysis as an attachment
[Analyse.ods](https://github.com/wekan/wekan/files/6797092/Analyse.ods)

**Comment by xavier-GitHub76** [comment]
Attachments are not the only way of reproduce the bug :
Comments are also concerned.

To reproduce the bug:

Create a board
Create a list
Create a card
Add a comment
Move the card to another board
Delete the board created in step 1
Try to delete the card created in step 3 ==> FAILED

You could see the issue in video

https://user-images.githubusercontent.com/82046143/125256635-eb2a8380-e2fc-11eb-9a23-4b5de4b8f713.mp4
