### ISSUE TITLE
ClanHub signup failure

### ISSUE THREAD

**Issue by ryanMushy** [wekan/wekan#3710]
## Issue
The website to signup to submit Pull Requests does not load in chrome or firefox.
To get started, [please sign the Contributor License Agreement](https://www.clahub.com/agreements/wekan/wekan).

**Comment by xet7** [comment]
https://github.com/clahub/clahub/issues/174

**Comment by xet7** [comment]
@ryanMushy 

Unfortunately, clahub is someone other's service, I can not fix it. I don't know did they save existing CLA. Then you just don't sign CLA, and in this case that code will just be MIT licensed code like other code in Wekan.

**Comment by xet7** [comment]
I deleted clahub from pull request requirements.
