### ISSUE TITLE
How to select more than 1 card and copy to another board?

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#3711]
I remember wekan allow you select more cards and copy to another board together. but I can't find it now.

does anybody know it?

thanks and have a nice day!

**Comment by xet7** [comment]
@javen9881 

Click Swimlane hamburger menu => Move Swimlane. It will move Swimlane to other board.

(Another one is Multi-Select, but it only moves cards to some list on current board, not to another board.)
