### ISSUE TITLE
Triggers/Rules

### ISSUE THREAD

**Issue by MTLNX** [wekan/wekan#3717]
## Issue

I wonder if is possible to add Rules/Triggers by duedate?

I would like to send an email every time a due date is overdue.

In addition, I would like to send e-mails to remind that the conclusion date is close, for example, two days before the conclusion.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L269-L282

For Snap:
```
sudo snap set wekan notify-due-days-before-and-after='2,0'
```
Later there will be added [Notifications Settings](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/r9wbs35A62u8xF2Rj)
