### ISSUE TITLE
Suddenly Person-Icons are on each card - cannot remove it

### ISSUE THREAD

**Issue by sirup** [wekan/wekan#3719]
**Server Setup Information**:
Wekan Version 5.20.0
Deployment Method: snap

**Problem description**:
Since today (Wekan must have updated automatically) on each card there is a small icon of a person. I have nowhere someone assigned. It must be the creator of the board I guess.
This is super annoying as now my cards have doubled in height. Having an overview of the cards is now very difficult.
I can additionally assign a person - This has the circle with a red undline. The wrong circle has a green underline. 
It is just everywhere suddenly and I cannot remove it.

![image](https://user-images.githubusercontent.com/5006637/114767360-d115ef00-9d67-11eb-9684-6a773b433b62.png)

**Comment by xet7** [comment]
@sirup 

It is creator of card https://github.com/wekan/wekan/pull/3705

To hide it, click Board Settings / Card Settings / [X] Creator
