### ISSUE TITLE
Feature Request: Label ordering in cards and label list

### ISSUE THREAD

**Issue by intellekta** [wekan/wekan#3726]
in the current version the labels orderd in the card as they created in the label list
the first added label in the card is left and last added label is right.

1.
it was fine when users can change the order on cards

a Card has
Label-A | Label-B | Label-C
user move C left before A.
result:
Label-C | Label-A | Label-B 

2.
and in the label list 
--------------
Label-A
Label-B
Label-C

user move C up before A. 
result:
--------------
Label-C
Label-A
Label-B

so users can move often used labels to top, 

3.
Also labels added to a card should stay at the position.
1. added Label-C at position 1 
2. added Label-B at position 2 
3. added Label-A at position 3 
result should be:
Label-C | Label-B | Label-A

this brings a very flexible and nice looking view to labels on cards, 

a sample, when we have three types of labels like rooms, groups, actions
and we want that rooms are left, groups are middle and actions are right

we create this labellist
--------------
room1
group1
action1

then we create a new card with label
room1, group1, action1
it looks nice 
room1, group1, action1

later we add a group2 to the labellist
--------------
room1
group1
action1
group2

and create a new card with label
room1, group2, action1

in the current version the group is right but should be in the middle.
room1, action1, group2

**Comment by mfilser** [comment]
See also #3424
