### ISSUE TITLE
After upload, attachements are renamed during download

### ISSUE THREAD

**Issue by xavier-GitHub76** [wekan/wekan#3727]
Hello,
I use Wekan 5.20.
When I upload files, wekan display the good name but when I want download attachements, they are renamed during download.

Exemple :
 - Upload file "a:a.txt"
 - The downloading file will be renamed  "a a.txt"

The characters concerned by this issue are : 
" --> a"a.txt --> a
* --> a*a.txt --> a a.txt
: --> a:a.txt --> a a.txt
< --> a<a.txt --> a a.txt
> --> a>a.txt --> a a.txt
| --> a|a.txt --> a a.txt

Best regards

**Comment by xet7** [comment]
Moved to #2759
