### ISSUE TITLE
After upload, attachements with special characters can be unattainabled (Access denied [403])

### ISSUE THREAD

**Issue by xavier-GitHub76** [wekan/wekan#3728]
Hello,
I use Wekan 5.20.
I upload files with special characters and it's not possible to download attachements : 
Access denied [403]

Example :
    Upload file "a#a.txt"
    Download file will display the message "Access denied [403]"

The characters concerned by this issue are :
'# --> a#a.txt --> Access denied [403]
? --> a?a.txt --> Access denied [403]

Best regards

**Comment by gpalyu** [comment]
I also have this issue, but until now was unable to figure out what caused it! I have a file attachment with a # on a card that I am unable to download. I could not figure out why it did not work, but other cards did.

This is the issue. My file has a #. I did a test of the same exact file without the #, and I was able to download it from the same card.

This issue has been going on for 2+ months for me. Thank you for shedding light!

**Comment by xet7** [comment]
Moved to #2759
