### ISSUE TITLE
After upload, attachements with special characters can be unattainabled (400 Bad Request)

### ISSUE THREAD

**Issue by xavier-GitHub76** [wekan/wekan#3729]
Hello,
I use Wekan 5.20.
I upload files with special characters and it's not possible to download attachements :
400 Bad Request

Example :
Upload file "a%a.txt"
Download file will display the message "400 Bad Request"

The only character % is  concerned by this issue
% --> a%a.txt --> 400 Bad Request

Best regards

**Comment by xet7** [comment]
Moved to #2759
