### ISSUE TITLE
After upload, attachements with special characters can be unattainabled (Page not found) 

### ISSUE THREAD

**Issue by xavier-GitHub76** [wekan/wekan#3730]
Hello,
I use Wekan 5.20.
I upload files with special characters and it's not possible to download attachements :
Page not found

Example :
Upload file "a\a.txt"
Download file will display the message "Page not found"

Best regards

**Comment by mfilser** [comment]
I never saw someone put's this special characters in a filename.

**Comment by xavier-GitHub76** [comment]
Hello,
seeing a loss of file, I wanted to test the cases to understand the cause of the problem.
Use "\" is unlikely but a file can be named with this character by a user and this file is accepted for import by Wekan.
Then the user can no longer access his file. It is therefore lost.
Wekan should not accept the file during import or ideally be able to restore the file during download.

**Comment by xet7** [comment]
File is still in Wekan database and can be saved with [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup).

Downloading file with special characters has bug, and many add duplicates of this issue as a new issue. I will try sometime to combine those issues and fix this bug. I do know many are impatient.

**Comment by xavier-GitHub76** [comment]
Thanks for your response and for the job done on wekan.
Your tool became a must of my daily life.

**Comment by xet7** [comment]
Moved to #2759
