### ISSUE TITLE
Filtering via Assignee or Member with OR

### ISSUE THREAD

**Issue by kbknapp** [wekan/wekan#3732]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly?: Yes
* Wekan version: 5.22.0
* Operating System: Ubuntu 20.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 12.22.1
* MongoDB Version: 4.4.5
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?: Firefox 87

**Problem description**:

Possible dupe of #2044, please close if so. My office uses Wekan internally, but we wish to be able to filter via OR when it comes to assignees and members. Google has turned up nothing, and the advanced filters don't seem to match on those fields with all the incantations I've tried. Is there a currently supported way to do this, or a future feature request?

I.e. we'd like to be able to filter all cards assigned to one of two people, or all cards that are either assigned to person X, or where person X is a member.

**Comment by jrsupplee** [comment]
Per the instructions: "Similar operators are *OR*ed together."

so:
```
assignee:user1 assignee:user2
```

Would return all cards where either `user1` *or* `user2` is the assignee.

**Comment by kbknapp** [comment]
Thank you much!
