### ISSUE TITLE
After attaching a file with a national name (Russian as an example), it is not possible to download it

### ISSUE THREAD

**Issue by neutrolino** [wekan/wekan#3746]
Wekan version 5.22
After attaching a file with a national name (Russian as an example), it is not possible to download it.
For download the link looks like:
_https://wekan.example.org/cfs/files/attachments/bCoT8ytdntzJKhyYj/%D0%98%D1%82%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%A2%D0%B5%D1%85%D0%BD%D0%BE%D0%BF%D0%BE%D0%BB%D0%B8%D1%81%20(1).xlsx?token=DELETED&download=true_
File name in Russian: Итоговое Технополис (1).xlsx
![изображение](https://user-images.githubusercontent.com/68535525/115684692-41bc9d00-a360-11eb-8bb6-6c48cc2455d8.png)

Error: We cannot find this site.

**Comment by xet7** [comment]
Moved to #2759
