### ISSUE TITLE
Time-Format / Date-Format in french Translation wrong in 5.22.0

### ISSUE THREAD

**Issue by pnrm** [wekan/wekan#3750]
Hi there,

OS: ubuntu server 20.04.2 LTS
Wekan 5.22.0 installed by snap

In version 5.22.0 the time format in all (french example) translation is 12 hours with am and pm instand of 24h format and date format is MM/DD/JJJJ instead of DD/MM/JJJJ.
![image](https://user-images.githubusercontent.com/18323883/115704166-53577200-a36b-11eb-9085-94414e90c35e.png)

**Comment by areanod** [comment]
OS: Debian Server 10 (Buster)
WEKAN 5.25.0 via snap

I have the exact same issue no matter which language: The timeformat is stuck on 12hrs.
I've read in some older posts to change the language setting to English UK but to no avail.

**Comment by xet7** [comment]
@areanod 

Sometime there will be added ability to change custom time format.
