### ISSUE TITLE
Feature Request: Planning Poker

### ISSUE THREAD

**Issue by Shorty365** [wekan/wekan#3751]
Remote working is here to stay and Wekan provides an excellent tool for remote workers. A few teams in our organisation have asked for a Planning Poker functionality and we believe this could be a good functional extension in Wekan. A remote Planning Poker session is, of course, possible with other tools like specialized websites and Skype or MS Teams like functionality but would it not be nice to incorporate things withing Wekan?

Planning Poker works like a kind of Voting-systematic with a closed set of answers. The current Voting-functionality in Wekan works with only 2 possible answers 'For' and 'Against' and I believe it should be fairly easy to extend the possible answers with the usual deck of poker-cards. Using the current Voting-functionality also, optionally, shows and store what every member voted so this could be a good starting point to start a discussion with that specific member. 

The Wikipedia-page shows a few decks of cards and further explanation. I would suggest using the  sequence: 0, ½, 1, 2, 3, 5, 8, 13, 20, 40, 100, and optionally a ? (unsure), an infinity symbol (this task cannot be completed).
https://en.wikipedia.org/wiki/Planning_poker

Thanks for attention and looking forward to your reaction.

**Comment by xet7** [comment]
@NicoP-S You did voting feature at https://github.com/wekan/wekan/pull/2994 . Are you interested in adding Planning Poker feature?

**Comment by Shorty365** [comment]
My request could be made more generic: Extend the current voting functionality with more, user defined, possible answers. This functionality could als be used for other more complex votes where a simple "For' or 'Against' is not suitable.

**Comment by NicoP-S** [comment]
@xet7 sorry i am busy at the moment and can't do it. 
Maybe someone who need's this feature can implement it.

**Comment by helioguardabaxo** [comment]
Hi, @Shorty365 !
I am trying to implements planning poker copying code from Voting (Thanks to @NicoP-S ).
I created this options below and I wonder to know what question use to guide members to vote in a poker card?
![image](https://user-images.githubusercontent.com/24301085/116786224-da939c80-aa73-11eb-8fd2-cdc28711e514.png)

Other question: the vote count is private until planning poker ends?

**Comment by Shorty365** [comment]
Hi helioguardabaxo,
The question would be something like "What is your estimate in time for your amount of work on this user story?" Hiding the cards until everyeone voted would be very nice because in this way the votes are unbiased. In Planning Poker there are several rounds of poker until an settlement has been reached on or around a certain number. The objective is to let everyone participate in the planning and let them say why a user story is, relative, simple to achieve or very hard to achieve. The goal is to discover if there are any surprises that nobody, but one, had thought of.  Studies show that by playing planning poker better achievable plans come up.

**Comment by helioguardabaxo** [comment]
@Shorty365 
Thanks for explain me
Now, the votes are private until the voting expires.
When a voting expires is show results. The winner poker card is highlighted.
I created a function to order poker cards counts and select winner(s). Then, if two cards are tied, the poker card with the highest value will be selected.

![image](https://user-images.githubusercontent.com/24301085/116911146-d787e000-ac1c-11eb-982b-bd9a3845cd52.png)
are the results clear?

On minicard, do you think that have to show the poker winner? (I used "check" as a badge to indicates that have a planning poker in this card)
![image](https://user-images.githubusercontent.com/24301085/116911578-6b59ac00-ac1d-11eb-8253-8c1d8bae6c07.png)

**Comment by Shorty365** [comment]
Hi helioguardabaxo,
I think you are missing the point of planning poker, no offense.  The point of PP is reaching consensus in the team on the amount of work is needed to finish an user story. It's not about winning, it's about getting the best and most information from every teammember so an archivale planning can be made. Saving the PP result of the last round is a good idea. I suggest that you watch some clips on PP for a better understanding of the purpose and the proces. Again no offense and I appreciate your efforts very much.

**Comment by helioguardabaxo** [comment]
No problem! The important is do this the right way.
I understood there are some rounds until team consensus.
The workflow may be:
- Create a Planning Poker (set question, check/or not "allow all logged users",  check/or not "show who voted whom", set/or not end date) 
- At current round ends date is show count votes for each poker card  
- For a second round: 
 - delete current Planning Poker and Create a new, or
 -  edit current Planning Poker ends date and the teammates change/or not their votes

It's ok?

 If do not need show a card "winner" in the first rounds, what do you think to put a button to enable/disable "show result" to show result when team achieve a consensus.
![image](https://user-images.githubusercontent.com/24301085/117171223-12b31c00-ada1-11eb-8bc8-87d449e44bf5.png)

But, what criteria to define a "selected" poker card? 
If have a consensus should have a unique poker card?

**Comment by Shorty365** [comment]
I think your workflow is quite accurate;

- Create a Planning Poker; 
-- set question: **OK**, 
-- check/or not "allow all logged users": _It's intended to be an interactive proces, so not really needed but it doesn't hurt either._ 
-- check/or not "show who voted whom": _Maybe a button named something like 'Show votes' after somebody castes his/her own vote? The voting in PP is not secret, it has te be unbiased and after voting the outcome is the starting point for discussions, so you have to know who voted what._
-- set/or not end date: _Since it's intended as an interactive proces this end date is not really needed but it doesn't hurt either._ 

- At current round ends date is show count votes for each poker card: _Yes, with a drill down to the voters name, to let them speak out/motivate their decision._
- For a second round:
- delete current Planning Poker and Create a new, or: _No_
- edit current Planning Poker ends date and the teammates change/or not their votes: _The question has to be the same, and teammembers have to rethink their votes, so clearing the previous results and setting a new end-date should do the trick. There is no need to keep the previous results._

If do not need show a card "winner" in the first rounds, what do you think to put a button to enable/disable "show result" to show result when team achieve a consensus: _Why not just keep the last result of the PP-round and add a text/button 'Consensus reached'? This answers also answers your your last question_

The criteria aka the value of each card is defined within the team. The value of '8' doesn't mean 8 hours but more work than '5' and less work than '13'. The team gives meaning to each value. The use of the Fibonnaci sequence is common practice. The meaning of the values can be quite different between the teams.

**Comment by marcungeschikts** [comment]
Hi @Shorty365 & @helioguardabaxo ,
Personally, my need seems simple:
1. Simply enabling Planning Poker in the card menu to add the section Planning Poker in the card with the Fibonnaci choices (all logged users will be allow, it will always show who vote what, no need of question, neither end date).
2. During the planning poker session, the team members will vote, we will discuss and some will change their vote until we all agree...and that's it.

Why do you need end date and to manage round?
___
The other solution proposed at the beginning by @Shorty365 (https://github.com/wekan/wekan/issues/3751#issuecomment-826620657) was also interesting(possibility to define many answers), but it would mean to have the ability to choose some templates for Planning poker, and it is probably not the same cost.

**Comment by Shorty365** [comment]
Hi marcungeschikts,

Thanks for your reply!

Your approach is really simple and I understand that when a PP-session is interactive and supported by a conference call of any kind that the simple solution is good enough. We however also want to give the opportunity or choice to play a non-interactive PP-session.  I have no idea how often a non-interactive PP-session will be played but it could be nice to have the opportunity to make a choice, setting an end date helps to keep momentum and urge the teammembers to vote.

Managing rounds is not important. I mean that multiple rounds of PP can be played to reach consensus. Keeping track of the several round is not at all important, hence my previous comment. 

My first suggestion is still valid and enables a broader range of usability but helioguardabaxo volunteered to implement PP so we went that route. I still prefer the broader scope but my initial question was about PP and I now believe that the broader option requires more development.

**Comment by Lucky-IT** [comment]
It seems, this will be a great feature when it could be implemented in the application.
However, something similar is also available from Atlassian's Marketplace for Jira; https://marketplace.atlassian.com/apps/1212495/planning-poker?hosting=cloud&tab=overview

**Comment by helioguardabaxo** [comment]
Hi @Shorty365 @Lucky-IT @marcungeschikts 
I send a PR to implements Planning Poker.
Thanks for yours ideas and help.
If have some thing wrong, open a issue and cite me in it.
