### ISSUE TITLE
Feature Request: Move a group of selected cards(multi-selection) to another board.

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#3752]
It is not possible to move a group of card to another board. You have to do it card by card and open each card.

The multi-selection allow only to move a group of cards using to another list inside the board or to the archive.
![movetoboardmultiselect](https://user-images.githubusercontent.com/74183327/115738922-ca9dfd80-a38d-11eb-8d96-7eb012ea4240.png)

**UX improvement:**
Be able to move the selected cards to an other board.

**Comment by xet7** [comment]
Yes, that feature does not yet exist.

At Swimlane hamburger menu, there is feature of move swimlane to another board.

**Comment by marcungeschikts** [comment]
Thank you for your quick answer. 
This request is slightly different, when you do not need to move the full swimlane.
I have just found that this request is a duplication of this one [#2155](https://github.com/wekan/wekan/issues/2155). 
You can close it then.

**Comment by xet7** [comment]
Moved to #2155
