### ISSUE TITLE
Swinlane in Export

### ISSUE THREAD

**Issue by Keelan** [wekan/wekan#3754]
## Feature Request

Is it possible to add the swimlane to the Export (CSV/Excel)?
Could we also hide/show stuff based on card/board settings?

**Comment by Keelan** [comment]
https://github.com/wekan/wekan/issues/395

**Comment by ryanMushy** [comment]
I will try to submit a pull request for this today as one of our developers has implemented the first request. 

We also have interest in hiding rows from the excel output but have decided this feature is low priority. 

Other things we would like is:
using board filters with all exports
using some delimiter between words on the same cell (newline or comma)

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3764
