### ISSUE TITLE
Feature Request: Automatically enable drag handles at mobile tablet landscape touch screen mode

### ISSUE THREAD

**Issue by mks-85** [wekan/wekan#3755]
Hi there,

OS: Ubuntu 20.04
Wekan 5.23.0 snap installation

Using wekan on my Galaxy S2 9.7 Tablet in landscape mode it is not possible to open a card.

In portrait mode I can open cards.

Doesn't matter if I use Chrome, Edge or PWA.

If I use my Oneplus 5T in landscape mode and I switch to desktop view in Chrome I can open cards but only if I tap to the card more times fast.

Would be great if wekan is usable on mobile devices.

**Comment by xet7** [comment]
@mks-85 

Do you have desktop drag handles enabled? It is designed for touch screen usage.

Click right top your username / Change Settings / Show Desktop Drag Handles.

At mobile, this code should detect device width and enable mobile web UI. Maybe it does not automatically enable desktop drag handles yet?
https://github.com/wekan/wekan/blob/master/client/lib/utils.js#L204

Unfortunately I don't have new enough tablet where I could debug this. Can some Wekan contributors try Wekan in tablet and try debugging this, possibly sending pull request to fix?

**Comment by mks-85** [comment]
> @mks-85 
> 
> Do you have desktop drag handles enabled? It is designed for touch screen usage.
> 
> Click right top your username / Change Settings / Show Desktop Drag Handles.
> 
> At mobile, this code should detect device width and enable mobile web UI. Maybe it does not automatically enable desktop drag handles yet?
> https://github.com/wekan/wekan/blob/master/client/lib/utils.js#L204
> 
> Unfortunately I don't have new enough tablet where I could debug this. Can some Wekan contributors try Wekan in tablet and try debugging this, possibly sending pull request to fix?

@xet7

Thx for your feedback!

I activated desktop drag handles and now I've got no problems to open the cards, work's fine now.

Desktop drag handles was not enabled, looks like it was not detected automatically.

I'm not a developer so I can't help you with debugging.

Btw: I'm using wekan since 8 weeks and I love it!!! 
Helps me to organise my stressful days. 
Great tool, great team!

**Comment by xet7** [comment]
[Enabling All Touch Screen Support](https://github.com/wekan/wekan/wiki/Touch-Screen-support)

**Comment by repmovs** [comment]
[this pull request](https://github.com/wekan/wekan/pull/4633) should have repaired the issue
