### ISSUE TITLE
How to move wekan to other computer by docker?

### ISSUE THREAD

**Issue by GanZhiXiong** [wekan/wekan#3758]
I have read the official documents[Move Docker containers to other computer](https://github.com/wekan/wekan/wiki/Move-Docker-containers-to-other-computer), but the documents are not detailed enough, and I failed in the end.

Here's how I do it:
1. Connect to server A
1. `docker export wekan-app > wekan-app.tar`
2. `docker export wekan-db > wekan-db.tar` 
3. Connect to server B
4. `docker import - wekanteam/wekan < wekan-app.tar`
5. `docker import - mongo < wekan-db.tar`
6. `git clone https://github.com/wekan/wekan`
7. `vim docker-compose.yml`
8. Modify wekan image to wekanteam/wekan and wekandb image to mongo
9. `docker-compose up -d` Error is as follows：

```bash
$ docker-compose up -d
wekan-db is up-to-date
Creating wekan-app ... error

ERROR: for wekan-app  Cannot create container for service wekan: No command specified

ERROR: for wekan  Cannot create container for service wekan: No command specified
ERROR: Encountered errors while bringing up the project.
```

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
If you really would like to use docker containers in that way directly, you should change Docker container wekan-app and wekan-db IDs to docker-compose.yml , and not download them from Docker Hub or Quay.

**Comment by GanZhiXiong** [comment]
image use id also not.
1. 
![image](https://user-images.githubusercontent.com/27394631/116022058-054cb200-a67c-11eb-977c-687bb1f04476.png)
2. 
![image](https://user-images.githubusercontent.com/27394631/116022110-23b2ad80-a67c-11eb-81eb-3d3728ee2af3.png)
3. 
![image](https://user-images.githubusercontent.com/27394631/116022251-68d6df80-a67c-11eb-8605-b07c32c03440.png)

**Comment by xet7** [comment]
Oh no, you wrote `docker-compose down`, that removed wekan-app and wekan-db containers. You should have writter `docker-compose stop`.

**Comment by GanZhiXiong** [comment]
Thank you very much for your answer！😀
But I still don't understand！

I hope the authorities will write a detailed tutorial on migrating Docker deployed Wekan to another server.😂😂


https://github.com/wekan/wekan/wiki/Backup  It looks complicated

https://github.com/wekan/wekan/wiki/Move-Docker-containers-to-other-computer It's not detailed enough

**Comment by xet7** [comment]
@GanZhiXiong 

I tried to add simpler info:
https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
I did find only a way to move all Docker containers at once:
https://github.com/wekan/wekan/wiki/Move-Docker-containers-to-other-computer

**Comment by GanZhiXiong** [comment]
@xet7   

In this way, The move to another server was successful.

But how to modify the port of wekan-app on the new server because there is no docker-compose. yml file.

With the `docker  inspect wekan-app`command, I query to the working_dir location
![image](https://user-images.githubusercontent.com/27394631/116182902-9b054180-a74f-11eb-858c-47061ec28351.png)

But there is no wekan directory under /root/

**Comment by GanZhiXiong** [comment]
j

> @xet7
> 
> In this way, The move to another server was successful.
> 
> But how to modify the port of wekan-app on the new server because there is no docker-compose. yml file.
> 
> With the `docker inspect wekan-app`command, I query to the working_dir location
> ![image](https://user-images.githubusercontent.com/27394631/116182902-9b054180-a74f-11eb-858c-47061ec28351.png)
> 
> But there is no wekan directory under /root/

I solved this problem by copying the docker-compose.yml file from the old server to the new server's /root/wakan directory.  😂

Thanks.
