### ISSUE TITLE
Language "Schwiitzerdütsch" uses wrong local settings

### ISSUE THREAD

**Issue by urmel1960** [wekan/wekan#3763]
## Issue

When choosing Swiss German as language - which is currently named "Schwiitzerdütsch" date and time are not formated properly. 

Schwiizerdütsch should be renamed and locale settings should be as stated here https://www.localeplanet.com/icu/de-CH/index.html

**Comment by xet7** [comment]
@urmel1960

Renamed to what? What is the language name, written in that language?

**Comment by xet7** [comment]
Sometime will be added feature to change to any date and time format. That feature has not been funded yet, but someone asked how much would it cost to develop it, I have not estimated it yet.

**Comment by urmel1960** [comment]
> @urmel1960
> 
> Renamed to what? What is the language name, written in that language?

Deutsch (Schweiz, de_CH)

**Comment by urmel1960** [comment]
Usually in other Programms it is for all kind oif varieties of German

Deutsch (Deutschland)
Deutsch (Schweiz)

sometimes you find also:

Schweiz (Deutsch)
Schweiz (Französisch)
Schweiz (Italienisch)

**Comment by xet7** [comment]
In Wekan, language in same country, like:
- Deutsch (Deutschland), de or de_DE
- Finnish (Finland), fi or fi_FI

These are at https://transifex.com/wekan/wekan without that country, like:
- Deutsch
- Finnish

When language and country is not same, there is suffix of country.

At Transifex, only one of those, like de or de_DE is translated, which one is started to translate at first, not both. Requests to add duplicate language are denied and removed.

Language names are written like those using that language to write that language name would do.

**Comment by urmel1960** [comment]
Ok - I understand the problem.
It is so that one speaks German in Switzerland basically. The German spoken and written in Switzerland has regional (Swiss) differences to the German spoken and written in Germany.  For example, in German (Switzerland) there is no "ß" but one writes "ss". There are further differences in the terminology.
Furthermore, there is "Schwizerdütsch" (Swiss German) which is the term for a German dialect that is widely spoken in Switzerland - this "Schwizerdütsch" still exists in a variety of regional variants.  However, this is generally not a linguistic variant that would be used in software. 

Switzerland has 4 official languages (German, French, Italian and Romansh). 
Therefore, localizations for Switzerland usually have at least 3 versions for the language - German, French and Italian. The reason why e.g. Switzerland - French is not equal to French, are the different characteristics of the number formats, thousand separators, decimal point etc.. You have the same with German (Germany) and German (Switzerland).

**Comment by urmel1960** [comment]
@xet7 

I still have the problem that when I use now Deutsch (Schweiz) - (thanks) - the date and time fomat is not as expected. It seems to fall back somehow to en locale settings with am/pm time etc. 

I see that the browser is loading 
```
13:16:41.723 XHRGET https://wekan.domain.tld/packages/mquandalle_moment/locale/de-ch.js?_=1619695001250
[HTTP/2 200 OK 33ms]
```
I checked on the server - the file de-ch.js does not exist on the harddisk within the snap in the respective directory. Strange - but it gets a 200 ok repsonse code although the file is definitely missing. 

I checked mquandalle:moment repo to see if the file is there - it was missing and I sent a pull request with that file to the repo. mquandalle set his repo now to archive status and sent me a note that since 5 years he does not maintain that repo any longer. 
As far as I could see mquandalle:moment is still a dependency in wekan. Does it makes sense to replace this dependency with moment:moment which seems to be active and somehow maintained ?

Regards

**Comment by xet7** [comment]
@urmel1960 

Thanks for info! I need to fork that repo and add it directly to `wekan/packages/`. mquandalle created Wekan and maintained it until I continued maintaining Wekan at 2016-12, he is not involved in Wekan development currently.

**Comment by urmel1960** [comment]
@xet7 

I think I saw that moment.js/moment is now built in as a dependency - or am I wrong?
But I can still see that the wrong locale from mquandalle_moment is used. 
Is there anything I can do to help ?

**Comment by xet7** [comment]
@urmel1960 

Bug is here:
https://github.com/wekan/wekan/blob/master/client/components/cards/cardDetails.js#L1032

After that line, insert:
```
console.log(newDate);
```
And see that value in browser right click / inspect / console.

That date value should be set to some correct format, so that it would be valid also for other languages:
https://momentjs.com/docs/#/i18n/

I have not figured it out yet.

**Comment by xet7** [comment]
Related to fixes also to those `js-end-date` links, here is my current diff:

```
diff --git a/client/components/cards/cardDetails.jade b/client/components/cards/cardDetails.jade
index 8edf34da..479b621f 100644
--- a/client/components/cards/cardDetails.jade
+++ b/client/components/cards/cardDetails.jade
@@ -107,7 +107,7 @@ template(name="cardDetails")
           else
             if canModifyCard
               unless currentUser.isWorker
-                a.card-label.add-label.js-end-date
+                a.card-label.add-label.js-card-end-date
                   i.fa.fa-plus
 
       hr
@@ -792,7 +792,7 @@ template(name="cardStartVotingPopup")
           span {{_ 'vote-public'}}
       .check-div.flex
         i.fa.fa-hourglass-end
-        a.js-end-date
+        a.js-vote-end-date
           span
             | {{_ 'card-end'}}
             unless getVoteEnd
@@ -838,7 +838,7 @@ template(name="cardStartPlanningPokerPopup")
           span {{_ 'allowNonBoardMembers'}}
       .check-div.flex
         i.fa.fa-hourglass-end
-        a.js-end-date
+        a.js-poker-end-date
           span
             | {{_ 'card-end'}}
             unless getPokerEnd
diff --git a/client/components/cards/cardDetails.js b/client/components/cards/cardDetails.js
index a973df07..32c72e76 100644
--- a/client/components/cards/cardDetails.js
+++ b/client/components/cards/cardDetails.js
@@ -378,7 +378,7 @@ BlazeComponent.extendComponent({
         'click .js-received-date': Popup.open('editCardReceivedDate'),
         'click .js-start-date': Popup.open('editCardStartDate'),
         'click .js-due-date': Popup.open('editCardDueDate'),
-        'click .js-end-date': Popup.open('editCardEndDate'),
+        'click .js-card-end-date': Popup.open('editCardEndDate'),
         'click .js-show-positive-votes': Popup.open('positiveVoteMembers'),
         'click .js-show-negative-votes': Popup.open('negativeVoteMembers'),
         'mouseenter .js-card-details'() {
@@ -565,7 +565,7 @@ Template.cardDetailsActionsPopup.events({
   'click .js-received-date': Popup.open('editCardReceivedDate'),
   'click .js-start-date': Popup.open('editCardStartDate'),
   'click .js-due-date': Popup.open('editCardDueDate'),
-  'click .js-end-date': Popup.open('editCardEndDate'),
+  'click .js-card-end-date': Popup.open('editCardEndDate'),
   'click .js-spent-time': Popup.open('editCardSpentTime'),
   'click .js-move-card': Popup.open('moveCard'),
   'click .js-copy-card': Popup.open('copyCard'),
@@ -973,7 +973,7 @@ BlazeComponent.extendComponent({
   events() {
     return [
       {
-        'click .js-end-date': Popup.open('editVoteEndDate'),
+        'click .js-vote-end-date': Popup.open('editVoteEndDate'),
         'submit .edit-vote-question'(evt) {
           evt.preventDefault();
           const voteQuestion = evt.target.vote.value;
@@ -1069,7 +1069,7 @@ BlazeComponent.extendComponent({
   events() {
     return [
       {
-        'click .js-end-date': Popup.open('editPokerEndDate'),
+        'click .js-poker-end-date': Popup.open('editPokerEndDate'),
         'submit .edit-poker-question'(evt) {
           evt.preventDefault();
           const pokerQuestion = true;
@@ -1120,6 +1120,7 @@ BlazeComponent.extendComponent({
 
           const dateString = `${evt.target.date.value} ${time}`;
           const newDate = moment(dateString, 'L LT', true);
+          console.log(newDate);
           if (newDate.isValid()) {
             // if active poker -  store it
             if (this.currentData().getPokerQuestion()) {
```

**Comment by xet7** [comment]
@urmel1960 

Oops sorry, I added some comments here to different issue, I moved those comments to #3837

**Comment by xet7** [comment]
@urmel1960 

I mean, I have not tried to fix this yet.

**Comment by xet7** [comment]
Well, I did kind of write better language detection in my joke toy prototype where even login does not work yet:
https://github.com/KanRule/php/blob/master/public/index.php#L27

But I have not tried to fix it in Meteor Wekan yet.

**Comment by urmel1960** [comment]
wekan is still using mquandalle:moment in its packages which is no longer maintained by mquandalle for a longer time. There is e.g. no de-CH-languange-settings-file. May be that other languages are effected in the same way - I don not know exactly.  

I would prepare a PR if I would know where the right place is to change the code. I already searched up and down - seems that I am to stupid to find the right place and approach to change this. 

Any advice and help is highly appreciated
