### ISSUE TITLE
Bring back Almost-Due for Start Date

### ISSUE THREAD

**Issue by darren-teo** [wekan/wekan#3766]
**Server Setup Information**:

* Did you test in newest Wekan?: **No**
* Wekan version: **5.23**
* Deployment Method: **docker**
* MongoDB Version: **4.2.13**

**Problem description**:
With regards to the changes implemented here, https://github.com/wekan/wekan/pull/3749, we have grown accustomed to the Start Date being Almost-Due (Yellow) when current time is after Start Date. The previous behaviour actually gives us a very good visual representation of cards that are in progress.

Can we bring back this behaviour or perhaps a env variable to enable it?

**Comment by listenerri** [comment]
@xet7 

The code: https://github.com/wekan/wekan/blob/823f11d5dd7435c8c317eff72ddd7892c4508321/client/components/cards/cardDate.js#L190
It is obviously wrong for the start date.
Is it just a matter of getting used to the wrong approach and continuing to let the mistake remain?
I hope you can reconsider this problem.

**Comment by darren-teo** [comment]
@listenerri 

I can understand the logic you are proposing. From a visual perspective, it is difficult to differentiate the cards that are being worked on or have past. I will gladly consider other alternatives, like different colour or font, bold or italics etc...

**Comment by listenerri** [comment]
> @listenerri
> 
> I can understand the logic you are proposing. From a visual perspective, it is difficult to differentiate the cards that are being worked on or have past. I will gladly consider other alternatives, like different colour or font, bold or italics etc...

Why don't you use `Due` to achieve your needs?
![image](https://user-images.githubusercontent.com/7995379/116667606-f8f38c80-a9ce-11eb-8334-e77326f5b71b.png)

And the wrong logic of `Start` cannot identify the attributes that are being processed and have been deferred.
Because as long as more than one minute, the color of `Start` will become yellow, can your cards are completed within a minute?

**Comment by listenerri** [comment]
https://github.com/wekan/wekan/wiki/Due-Date

**Comment by listenerri** [comment]
1. I create a card for someone else and set up the `Due` time, then assign the card to someone
2. When someone find the new card, he check the card details, and when he think the content of the card makes sense, he set the `Received` for the card.
3. When he finished the other tasks and started working on this new card, he set the `Start` for this card.
4. When the card is about to expire, `Due`  becomes yellow.
5. When the card expires, `Due`  becomes red.
6. When he finishes the card, he will set the `End`.

This is how I use wekan, is this the correct way to use it? @xet7 
Does this process meet your needs? @darren-teo 

If this process is correct, then this code should be deleted. https://github.com/wekan/wekan/blob/823f11d5dd7435c8c317eff72ddd7892c4508321/client/components/cards/cardDate.js#L190

**Comment by darren-teo** [comment]
I have a particular case where a batch of tasks are scheduled 1 to 2 weeks ahead. Once the batch is completed, we archive the tasks or move the batch to another list.

Visually, this is how we can differentiate. 
![image](https://user-images.githubusercontent.com/32067070/116676029-14639500-a9d9-11eb-9f53-0002f671446b.png)

I don't see how `Start` being differentiated will affect the "right" process, especially since this behaviour has been there for the longest time.

**Comment by listenerri** [comment]
> I have a particular case where a batch of tasks are scheduled 1 to 2 weeks ahead. Once the batch is completed, we archive the tasks or move the batch to another list.
> 
> Visually, this is how we can differentiate.
> ![image](https://user-images.githubusercontent.com/32067070/116676029-14639500-a9d9-11eb-9f53-0002f671446b.png)
> 
> I don't see how `Start` being differentiated will affect the "right" process, especially since this behaviour has been there for the longest time.

Aha, I got you.
You think the `Start` should be a part of the schedule, But I think the `Start` is set when it actually starts processing the task.

I think your method is different from the one designed in the [wiki](https://github.com/wekan/wekan/wiki/Due-Date).
Although this behavior has existed for a long time, I think it is still necessary to fix it.

**Comment by listenerri** [comment]
@darren-teo 
I have an immature suggestion:
1. If `Start` is at some point in the future, then it is gray
2. If `Start` is current or in the past, we set it into green

Because yellow has a warning meaning(almost-due), I cannot understand that A is yellow when it is normal.

**Comment by darren-teo** [comment]
Thanks @listenerri!

This make sense! I'm totally good with this great suggestion, not immature at all.

> @darren-teo
> I have an immature suggestion:
> 
> 1. If `Start` is at some point in the future, then it is gray
> 2. If `Start` is current or in the past, we set it into green
> 
> Because yellow has a warning meaning(almost-due), I cannot understand `Start` is yellow when it is normal.

**Comment by xet7** [comment]
@listenerri 

Can you send pull request with this fix?

> @darren-teo
> I have an immature suggestion:
> 
>     1. If `Start` is at some point in the future, then it is gray
> 
>     2. If `Start` is current or in the past, we set it into green
> 
> 
> Because yellow has a warning meaning(almost-due), I cannot understand `Start` is yellow when it is normal.

**Comment by listenerri** [comment]
> @listenerri
> 
> Can you send pull request with this fix?
> 
> > @darren-teo
> > I have an immature suggestion:
> > ```
> > 1. If `Start` is at some point in the future, then it is gray
> > 
> > 2. If `Start` is current or in the past, we set it into green
> > ```
> > 
> > 
> > Because yellow has a warning meaning(almost-due), I cannot understand `Start` is yellow when it is normal.

I will try : )

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3793
