### ISSUE TITLE
Feature Request: Add Custom Fields values (and name) in Excel export

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#3769]
## Custom Fields values in Excel sheet after Excel export
On Excel export feature, add custom fields in the Excel columns with he value(s) of each custom fields in different columns, and ideally the name of the custom field in the column name(not mandatory, it could be an ID).

**Comment by ryanMushy** [comment]
for future developers, check out this commit which does the same but for swimlanes
https://github.com/wekan/wekan/pull/3764

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
