### ISSUE TITLE
REST API Docs: Top part missing from generated PHP code-sample

### ISSUE THREAD

**Issue by gnanet** [wekan/wekan#3770]
### Ruby
```ruby
require 'rest-client'
require 'json'

headers = {
  'Content-Type' => 'application/x-www-form-urlencoded',
  'Accept' => '*/*'
}

result = RestClient.post '/users/login',
  params: {
  }, headers: headers

p JSON.parse(result)
```

### PHP
```php
 'application/x-www-form-urlencoded',
    'Accept' => '*/*',
);

$client = new \GuzzleHttp\Client();

// Define array of request body.
$request_body = array();

try {
    $response = $client->request('POST','/users/login', array(
        'headers' => $headers,
        'json' => $request_body,
       )
    );
    print_r($response->getBody()->getContents());
 }
 catch (\GuzzleHttp\Exception\BadResponseException $e) {
    // handle exception or api errors.
    print_r($e->getMessage());
 }

 // ...
```

#### Add the missing part:
```php
$headers = array(
    'Content-Type' => 
```

#### becomes:
```php

$headers = array(
    'Content-Type' => 'application/x-www-form-urlencoded',
    'Accept' => '*/*',
);

$client = new \GuzzleHttp\Client();

// Define array of request body.
$request_body = array();

try {
    $response = $client->request('POST','/users/login', array(
        'headers' => $headers,
        'json' => $request_body,
       )
    );
    print_r($response->getBody()->getContents());
 }
 catch (\GuzzleHttp\Exception\BadResponseException $e) {
    // handle exception or api errors.
    print_r($e->getMessage());
 }

 // ...
```

**Comment by gnanet** [comment]
@xet7 oh, my fault, i could have opened this issue at https://github.com/wekan/wekan.github.io
Is there some automated solution, that generates the API Docs?

**Comment by xet7** [comment]
@gnanet 

I did move this issue from wekan.github.io to wekan.

Yes there is automated solution https://github.com/wekan/wekan/blob/master/releases/rebuild-docs.sh

Related #3757

**Comment by gnanet** [comment]
I just tested the v5.27 wekan.yml with **api2html**, and the problem that strips the initial part, seems to reside in `widdershins/templates/openapi3/code_php.dot`, or at least how their template engine is handling the initial
```
<?php
```

If i change the first line of the template to this
```
// php
```

A nice looking but at least not-cropped PHP code is generated.


Also i found this PR in **widdershins** where the user faced the same problem caused by the opening tag of php.

https://github.com/Mermade/widdershins/pull/414

**Comment by gnanet** [comment]
Was not satisfied with removing the php-opening-tag, and found out, that changing `<?php` to `&lt;?php` in **code_php.dot** allows to keep the opening tag,without cropping the start of the code-example.
