### ISSUE TITLE
v5.27 Filename with # can not be downloaded

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3776]
Moved to here from #2759 

From @gpalyu 

I have updated to most recent version, 5.27.0, and I am still having the same issue.

I went to an old card created 4 months ago with a file with # in it, and got error (403) still.

Then I created a new file with a # in it and uploaded and tried to download and got same error (403).

**Comment by xavier-GitHub76** [comment]
Hello,
I have updated to most recent version, 5.27.0, and I am still having the same issue.

A new file with a `#` in it or  a new file with a `?` in it, and got error (403) still.

A new file with a `\` in it, and got error "Page not found".

A new file with a `%` in it, and got error "400 Bad Request"

A new file with a `"` in it or  a new file with a `*` in it, or  a new file with a `:` in it, or  a new file with a `<` in it, or  a new file with a `>` in it, or  a new file with a `|` in it, and file is renamed.

Good luck for fix

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5083 . Thanks to @VidVidex !
