### ISSUE TITLE
Feature Request: Outlook 2016 and Docuware integration to Wekan

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3781]
Moved to here from https://community.vanila.io/?t=c8d45a31-3786-4429-acc2-ca7623272055

From @fakhrul

Can anyone tell me how to integrate outlook 2016 to Wekan?

From @xet7 

- How should it work?
- What kind of integration?
- Does anybody have idea about what does this mean?

**Comment by fakhrulparvez** [comment]
@xet7  If you check Asana then you will have an idea about this outlook2016 integration. 

also please try to bring Docuware in the integration list. 

@xet7  I ahve sent you an email already. Would you please reply that?

Thanks

**Comment by fakhrulparvez** [comment]
@xet7  Hi Ojansivu 

I have sent you an email. Can you please reply.  I have mentioned all required features there that we need. Please have a look and reply.. 

Kind Regards
Fakhrul
