### ISSUE TITLE
How to add mind map function

### ISSUE THREAD

**Issue by xuguotong** [wekan/wekan#3794]
I want to add mind map function to the wekan project. At present, I choose the open source Baidu mind map. The address of Baidu mind map is: https://github.com/NaoTu/DesktopNaotu .At present, my practice is to put the mind map project into the public folder, and then visit it in the project. In the wekan project, Kanban and mind map are quickly rendered, but the problem of OOM appears. What's the right way to add mind map function to wekan project? I'm looking forward to your reply. If you have any questions, please let me know. I may reply a little slower, please forgive me.

**Comment by xet7** [comment]
That mind map is GPLv2. I'm trying to keep Wekan with MIT license.

So instead, I'll add markdown-it-mermaid, I hope it helps:
https://github.com/wekan/wekan/wiki/Mermaid-Diagram

Mermaid also has Gantt, so if it's somehow possible to migrate https://github.com/wekan-gantt-gpl to use Mermaid instead, Wekan GPLv2 version could be migrated to Wekan MIT version, and Wekan GPLv2 version deprecated.

Please someone comment is Mermaid useful, or should I try something else.

**Comment by xuguotong** [comment]
thank you，l will try that way.
