### ISSUE TITLE
Which version of Mongo database should the new version of wekan project use?

### ISSUE THREAD

**Issue by xuguotong** [wekan/wekan#3800]
Which version of Mongo database should the new version of wekan project use? The current project is using version 4.0. Is there any problem with this version cooperating with the new version of wekan project?

**Comment by xet7** [comment]
@xuguotong 

There is no problems I think.

If you change MongoDB version, make [Backup](https://github.com/wekan/wekan/wiki/Backup) first.

Wekan works with MongoDB versions 3.2.x - 4.x . Newest MongoDB has newest bugfixes.

Wekan works with official MongoDB and Percona MongoDB:
https://www.percona.com/software/mongodb/feature-comparison

**Comment by xuguotong** [comment]
thank you very much.
