### ISSUE TITLE
Oauth with WP Oauth Server

### ISSUE THREAD

**Issue by servantofchaos** [wekan/wekan#3808]
## Oauth challenge

I am running WP Oauth Server with Wordpress. 
I have setup the client and server successfully and can have multiple Wordpress sites authenticate without issue.

I can manually receive the correct userinfo when using https://my-domain/oauth/me/?access_token=khjjfrokyijmmhtgwiv99s8qiyt1aorntcupai5a

But the log files generate an error. I have tried changing scope variables ('openid' etc) without success.

```
XXX: register token: {
   access_token: 'khjjfrokyijmmhtgwiv99s8qiyt1aorntcupai5a',
   expires_in: 3600,
   token_type: 'Bearer',
   scope: 'basic',
   refresh_token: 'tufmrtcjd3dvpc4etugakrsh24yp6lr4nezkpfly'
 }

 {"line":"405","file":"oauth_server.js","message":"Error in OAuth Server: Failed to fetch userinfo from OIDC https://my-domain.com/oauth/me: failed [400] {\"error\":\"invalid_request\",\"error_description\":\"Invalid token\",\"error_uri\":\"https:\\/\\/tools.ietf.org\\/html\\/draft-ietf-oauth-v2-31#section-7.2\"}","time":{"$date":1620806018118},"level":"warn"}

Exception while invoking method 'login' Error: Failed to fetch userinfo from OIDC https://my-domain.com/oauth/me: failed [400] {"error":"invalid_request","error_description":"Invalid token","error_uri":"https:\/\/tools.ietf.org\/html\/draft-ietf-oauth-v2-31#section-7.2"}
     at getUserInfo (packages/wekan-oidc.js:240:20)
     at Object.handleOauthRequest (packages/wekan-oidc.js:59:16)
     at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)
     at middleware (packages/oauth/oauth_server.js:170:5)
     at /snap/wekan/1492/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```
It seems that the access token isn't being appended correctly but I am unsure how to test this. Any suggestion would be appreciated.

**Server Setup Information**:
Wekan Version	5.28.0
Meteor version	2.2
Node version	12.22.1
MongoDB version	3.2.22
MongoDB storage engine	wiredTiger
MongoDB Oplog enabled	
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	5.4.0-1047-aws

**Comment by xet7** [comment]
@servantofchaos 

Wekan works for example with RocketChat OAuth2 identity provider, and many others. Do these settings help?
https://github.com/wekan/wekan/wiki/OAuth2#rocketchat-providing-oauth2-login-to-wekan

Or does it need some mapping like Auth0 ?
https://github.com/wekan/wekan/wiki/OAuth2#auth0

Also in OAuth2, there should be these settings, like mentioned at https://github.com/wekan/wekan/wiki/Google-login 
```
snap set wekan oauth2-email-map='email'
snap set wekan oauth2-username-map='email'
```

**Comment by servantofchaos** [comment]
@xet7 - thanks. I might try and see if I can get it working with Auth0. It could be that the settings don't map easily.
