### ISSUE TITLE
E-Mail Settings "...must be 'smtp' or 'smtps'..."

### ISSUE THREAD

**Issue by MasterCowlenz** [wekan/wekan#3809]
Hello,

I read and try all infos from Email settings:
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

no solution :(

I use a Docker USC installation with the newest Wekan version 5.27.0

Then I sent a Mail, at first try shows this message:

"Sending email failed
Fehler beim Senden der E-Mail: Email protocol in $MAIL_URL ('smtps://username@gmail.com:password!@smtp.gmail.com:465') must be 'smtp' or 'smtps'"

And the second try that display "the mail sent", but it doesn't....

The command `sudo docker logs wekan-app` shows:

"
====== BEGIN MAIL #0 ======
(Mail not sent; to enable sending, set the MAIL_URL environment variable.)
Content-Type: text/plain
From: "'Wekan Notifications '" <noreply@gmail.de>
To: max.mustermann@gmx.de
Subject: SMTP Test-E-Mail
Message-ID: <16d60afb-7653-25f5-5104-39719d62a334@gmail.de>
Content-Transfer-Encoding: 7bit
Date: Thu, 13 May 2021 21:36:57 +0000
MIME-Version: 1.0

Sie haben erfolgreich eine E-Mail versandt
====== END MAIL #0 ======
"

Please help me... any idea?

Thanks!

**Comment by xet7** [comment]
Sending email with Google does not work, if you have not allowed in your google account settings using less safe email apps. I have not tried does sending with Google work.

I have only tested that sending with AWS SES works.
