### ISSUE TITLE
Login Forbidden Admin Panel Access Help

### ISSUE THREAD

**Issue by DemonRem** [wekan/wekan#3810]
hey guys 

i installed the wekan latest version
but once i using user name and password wekan
its not connection "Login forbidden" this is the error

so i try to create a new account but i cant access the admin panel i also never used mongodb on linux
what i  can do to get the admin panel ("admin access")?

**Comment by xet7** [comment]
Did you install Snap, Docker, or some other version of Wekan?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Forgot-Password
