### ISSUE TITLE
href link to the minicard do not present when board  is exported as "html"

### ISSUE THREAD

**Issue by Dariozz** [wekan/wekan#3812]
Hello everyone, 
maybe someone could help me ! 

I constated that when you export a board as html, the index.html provide the main  layout, but does not allow access to minicard, when i inspect html code, it's seems every href link disappeared. I noticed that the data content is present in the json data. Is it normal ? or maybe need i have to do some action ? 

Thanks a lot for your help !

Best regard 

Dariozz

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
