### ISSUE TITLE
Please recommend a performance testing tool.

### ISSUE THREAD

**Issue by xuguotong** [wekan/wekan#3819]
At present, more and more people are using the wekan project in the company, so I want to test the performance of the system before going online. Two or three testing tools are used to test the performance of nodejs, but they are not satisfactory. So please recommend a tool to test the performance of wekan project. Thank you very much!

**Comment by xet7** [comment]
Performance is different in each Wekan release, depending on bugfixes, added features, optimizations, etc, so there is no general answer to this. Future optimizations will speed up Wekan.
