### ISSUE TITLE
[Bug] Notifications broken when editing dates

### ISSUE THREAD

**Issue by benjaminhrivera** [wekan/wekan#3825]
**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 5.24.0
* Operating System: Windows
* Deployment Method: mongodb
* Node Version: 12.22.1

**Problem description**:

When adding / changing dates to cards, users who are assigned as members to that card, are notified however the notification is broken

Has / is anyone else experienceing this?

![image](https://user-images.githubusercontent.com/57966706/119888042-e6ec0780-bf02-11eb-98a1-c2dac03014a7.png)

**Comment by benjaminhrivera** [comment]
Wondering if this is something on my end, does this happen for you @xet7 ? I pulled a fresh copy of wekan and it still seems to be persistent.

**Comment by xet7** [comment]
Moved to #2026
