### ISSUE TITLE
PHP/MySQL Installation

### ISSUE THREAD

**Issue by dbierspb** [wekan/wekan#383]
Is there a walkthrough or anything for a PHP+MySQL LAMP stack installation or only docker/sandstorm?  I would like to deploy some of it on my server but I don't bother with docker.

**Comment by ocdtrekkie** [comment]
Wekan is built on Meteor. It doesn't use PHP or MySQL.

**Comment by Kleintan** [comment]
Is there a way im running in ubuntu and it is getting slower in loading a board that usual
