### ISSUE TITLE
[Login page] The default wekan logo appears briefly before displaying the custom logo

### ISSUE THREAD

**Issue by Emile840** [wekan/wekan#3830]
## Issue
![wekanLogo](https://user-images.githubusercontent.com/83423044/120175029-0edeb200-c206-11eb-8af7-cad50ab48663.gif)

Each time you arrive on the login page, there is a call to the database to retrieve the “setting” object which contains the configuration data (including the link to custom logo), the problem is that there is a delay of a few seconds between the first display of the page and the call to the database. For those few seconds wekan default logo is displayed (see gif image above). I'm working on this issue

**Comment by xet7** [comment]
Moved to #3832
