### ISSUE TITLE
quay.io/wekan/wekan:latest not updated, it is still version 5.27

### ISSUE THREAD

**Issue by GuidoDr** [wekan/wekan#3834]
## Issue
**Problem description**:
- quay.io/wekan/wekan:latest is still version 5.27, looks like it did not get the recent updates
- hub.docker.com is on version 5.29

But since the default setup in docker-compose .yml for the image is "image: quay.io/wekan/wekan" I did not get the latest version. I just switched it to "image: wekanteam/wekan:latest" so that I now also got version 5.29

**Comment by xet7** [comment]
I started builds for 5.30. They should finish sometime today.
