### ISSUE TITLE
Setting End Date in Planning Poker is impossible

### ISSUE THREAD

**Issue by Shorty365** [wekan/wekan#3838]
## Issue

Today I entered the Dutch translations for Planning Poker and since I'm the requester I also did a quick test. Everything looks fine except for the setting of an end date to a vote. In the calendar-widget I can select a date but as soon as I try to save it, Wekan throws an error ' Invalid date. This probably has to do with localization because I'm using the Dutch localization.

@helioguardabaxo 

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:

* Wekan version: 5.30.0
* Operating System: Ubuntu 20.4, fully up to date
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node Version: 12.22.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox 89

**Comment by xet7** [comment]
Moved to #3837
