### ISSUE TITLE
Sortable issue

### ISSUE THREAD

**Issue by nod103** [wekan/wekan#3839]
I'm running into an issue where I cannot drop a card into an empty swim lane. I saw in another post this was fixed but I'm seeing the same issue. I'm using Wekan in Chrome. I checked the console and I'm not getting any error messages. 

![Animation2](https://user-images.githubusercontent.com/61754382/120865212-97898500-c55b-11eb-90dd-d5bf27ffa793.gif)

**Comment by xet7** [comment]
You are doing it too fast. Drag card to top of another swimlane's list and wait 2 seconds to insert slot top open.

**Comment by nod103** [comment]
Here's what happens as I go slower. 

![Animation3](https://user-images.githubusercontent.com/61754382/120891292-c3495100-c5d5-11eb-803e-eff135341863.gif)

**Comment by xet7** [comment]
You should first drag it to top of leftmost list, and after 2 seconds when insert slot opens, on that same swimlane you can also drag it to some list at right.

**Comment by xet7** [comment]
Or alternatively, add even one card to that swimlane list, so then dragging is easier.
