### ISSUE TITLE
Wekan UI fails to finish import of closed Trello boards

### ISSUE THREAD

**Issue by berezovskyi** [wekan/wekan#3840]
## Issue

**Server Setup Information**:

* Newest version of Wekan via Docker (as of 2021-06-06)
* Latest version of Brave (as of 2021-06-06)

![image](https://user-images.githubusercontent.com/64734/120935971-9b590b00-c705-11eb-80a9-1ede94e69449.png)

**Problem description**:

1. Paste an exported JSON from a **closed** Trello board into the Trello import dialog.
2. Either map users or proceed without mapping (I tried both).
3. You will see another user mapping dialog, without any more users to map. Pressing the button does nothing (no HTTP requests are sent). ~The import does not finish.~ Actually, the import is done correctly but because the board is closed, it does not show up in the main UI unless you go to the "Boards in Archive" to check.

![Screenshot_2021-06-06_at_20_19_18](https://user-images.githubusercontent.com/64734/120935821-e58dbc80-c704-11eb-860a-7bfbfccb4aa1.png)
![Screenshot 2021-06-06 at 20 19 36](https://user-images.githubusercontent.com/64734/120935823-e9214380-c704-11eb-8e27-9557dc5b522f.png)
![Screenshot 2021-06-06 at 20 19 26](https://user-images.githubusercontent.com/64734/120935827-ec1c3400-c704-11eb-98fd-f69423485367.png)

Now edit the JSON to replace `"closed":true,"dateClosed":"2021-06-05T16:44:24.537Z"` with `"closed":false` and try to import again:

![Screenshot_2021-06-06_at_20_23_22](https://user-images.githubusercontent.com/64734/120935895-33a2c000-c705-11eb-8988-8c72f64751a2.png)
![Screenshot 2021-06-06 at 20 23 27](https://user-images.githubusercontent.com/64734/120935901-37364700-c705-11eb-9f3b-5146fd1e2f87.png)
![Screenshot 2021-06-06 at 20 23 42](https://user-images.githubusercontent.com/64734/120935902-39000a80-c705-11eb-91c9-f0dc4d661a8a.png)

Logs: none were output while I was doing these operations. Some of the recent log messages:

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 40)
(node:1) UnhandledPromiseRejectionWarning: Error: failed [503]
    at Object.exports.makeErrorByStatus (packages/http.js:177:10)
    at Request._callback (packages/http.js:141:24)
    at Request.self.callback (/build/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/build/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/build/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 43)
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Presence started serverId=xyz
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Sun Jun 06 2021 18:10:53 GMT+0000 (Coordinated Universal Time)","time":{"$date":1623003054052},"level":"info"}
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

(Sun Jun 06 2021 18:10:53 GMT+0000) is 13 minutes prior to the import, for the record.

Finally, let me thank you for your effort in developing Wekan!

**Comment by berezovskyi** [comment]
The backup was done using https://github.com/mattab/trello-backup with a tweak: [lines 90-92](https://github.com/mattab/trello-backup/blob/master/trello-backup.php#L90-L92) were commented out in order to export closed boards as well.

**Comment by berezovskyi** [comment]
As I am importing more boards, I found that simply setting `"closed":true` and leaving the `dateClosed` intact also allows the import to proceed.

**Comment by berezovskyi** [comment]
The lack of errors in the logs was bothering me and then I accidentally imported a board that I did not mean to. I then discovered that my previous import attempts were all successful but UI did not handle the imported of the closed boards properly:

![image](https://user-images.githubusercontent.com/64734/120936890-9fd3f280-c70a-11eb-98e7-f46bd16f54be.png)

**Comment by xet7** [comment]
@berezovskyi 

Wekan does ignore some errors, to be able to import even something.

That closed board could be here:
https://github.com/wekan/wekan/blob/master/models/trelloCreator.js#L95

There are also checks for closed cards etc, that could mean that card is archived.

Here is how you can test your code changes and submit pull request (ignore plugin related info):
https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin
