### ISSUE TITLE
Remove the mention "+ Add a card" already available at the head of the column

### ISSUE THREAD

**Issue by JFa-Orkis** [wekan/wekan#3848]
Remove the mention "+ Add a card" visible from everywhere and which clutters the reading of the table, the "+" being already available at the head of the column

**Comment by mfilser** [comment]
"+ Add a card" is different to the one in the header. If you use + in the header the cards are added at the top, "+ Add a card" add cards at the bottom of the column. A description to + is a good (imho) idea.
