### ISSUE TITLE
Sort number  “0” not accepted

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#3859]
With v5.34, I cannot save “0” as the sort number in the detail view of a card.  Because I use this feature only recently – because I read that those numbers are now printed on the minicards – I don’t know whether this is intended behaviour. Still, it seems odd, given that some of my cards do have the value “0”.

**Comment by xet7** [comment]
@mfilser

Do you know how that sort number feature works?

**Comment by mfilser** [comment]
@xet7
@bronger
I will have a look at it. Give me some days, i am currently busy at home.
