### ISSUE TITLE
Avatars won’t display if the app is deployed under a sub-path

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#386]
Deploying Wekan under a sub-path of a domain name was recently implemented in devel (see #133) and will be shipped in the next version of Wekan.

I strongly suspect this “avatar not displaying” bug comes from Collection-fs not taking into account the `ROOT_URL` environment variable correctly to support prefixed URLs. I will probably open a PR to support it (which should be fairly similar to the support introduced in Flow-Router in https://github.com/kadirahq/flow-router/pull/329)

**Comment by mquandalle** [comment]
I was slightly wrong on the problem description, I reported the bug to CollectionFs with a corrected explanations at https://github.com/CollectionFS/Meteor-CollectionFS/issues/884.

**Comment by xet7** [comment]
Moved to #973
