### ISSUE TITLE
Add feature: draw relation between cards

### ISSUE THREAD

**Issue by rasos** [wekan/wekan#3860]
We are having a special use case that after brainstorming and sorting cards into rows, users should be able to draw relations between cards and add a label what kind of relation that is. Admittedly, that is not for scrum, but for citizens' participation making social relations visible for tasks.

Drawing the relation could be free form or some kind of snap in. 

![3508-2480-max](https://user-images.githubusercontent.com/485723/121788344-d6a77e00-cbcc-11eb-8314-54c2cf741980.png)

Related to #709

**Comment by xet7** [comment]
@rasos 

Is this:

a) Red strings #3392 

b) Gantt dependencies https://github.com/wekan/wekan/issues/2870#issuecomment-857115753 https://github.com/wekan/wekan/issues/2870#issuecomment-721364824

c) Mermaid markdown graphs https://github.com/wekan/wekan/wiki/Mermaid-Diagram

d) Something else?

**Comment by rasos** [comment]
We need something similar to red strings. Closing this issue in favor of #3392.
