### ISSUE TITLE
checklists only readable via API by Admin accounts

### ISSUE THREAD

**Issue by JayVii** [wekan/wekan#3862]
When using the `/api/boards/:boardId/cards/:cardId/checklists` call with a non-Admin account, it always returns NULL, even if there clearly are checklists in the given card. The issue does not happen when the authenticated user has Admin privileges on the server.

There are no further logs as far as I can tell, it just returns an empty response.

**Server Setup Information**:

Wekan 5.29 via docker from official image on a Ubuntu 20.04 host with apache2 as proxy.

**Comment by xet7** [comment]
@JayVii 

If user can login to API, maybe user could access those boards data user is member of.

Checklists REST API is here:
https://github.com/wekan/wekan/tree/master/models

Authentication code is here:
https://github.com/wekan/wekan/blob/master/server/authentication.js

Here is how to make pull request:
https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

**Comment by JayVii** [comment]
During my tests, the user was authenticated. All other API calls worked perfectly fine.

I could retrieve information about the **user's own boards** (or those they had access to) from `/api/boards/`, about all lists of a board from `/api/boards/:boardId/lists` as well as cards from `/api/boards/:boardId/cards` and specific card information via `/api/boards/:boardId/cards/:cardId`, just not the checklists (unless the autheticated user had admin privileges).

I'll look into the REST API code, but my experience with JS code is very limited, so this might take a while. Thanks anyways :)

**Comment by xet7** [comment]
@JayVii 

Thanks a lot for more details! For those that work, like all lists, it seems it checks this way:
https://github.com/wekan/wekan/blob/master/models/lists.js#L471
```
Authentication.checkBoardAccess(req.userId, paramBoardId);
```

Checklists do not work:
- https://github.com/wekan/wekan/blob/master/models/checklists.js#L207
- https://github.com/wekan/wekan/blob/master/models/checklistItems.js#L268
```
Authentication.checkUserId(req.userId);
```
So it seems you coud change that checking code to be:
```
Authentication.checkBoardAccess(req.userId, paramBoardId);
```

**Comment by xet7** [comment]
Hmm, maybe I'll try to make that change myself. Just a moment.

**Comment by JayVii** [comment]
Wow, thanks a lot for this swift fix! Greatly appreciated :+1:
