### ISSUE TITLE
Global Search gives access to ALL card titles

### ISSUE THREAD

**Issue by adelphi-company** [wekan/wekan#3864]
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 5.3.5
* Operating System: Debian 10
* Deployment Method: snap
* Http frontend if any: apache
* Node Version: snap
* MongoDB Version: snap
* What webbrowser version are you using? Chrome 91, FF 89

**Problem description**:

If using global seach for "status:archiviert", ALL archived cards are shown including title and editor even if user has no access to it.

- *Explain steps how to reproduce*

1. Login as user that doesn't have access to any board
2. open https://wekan/global-search
3. Enter search phrase "status:archiviert" (german language)
-> You will get a list of ALL archived boards altough the user never has access to them.

See more information in https://github.com/wekan/wekan/discussions/3680#discussioncomment-606260

**Comment by xet7** [comment]
@jrsupplee 

Can you look at this?

**Comment by jrsupplee** [comment]
> @jrsupplee
> 
> Can you look at this?

Yes, but I am traveling right now.  I have an idea about the problem, just need to look at the code.

**Comment by xet7** [comment]
I can not reproduce this in newest Wekan. Searching for `status:archived` returns only cards for current user.

**Comment by adelphi-company** [comment]
> I can not reproduce this in newest Wekan. Searching for `status:archived` returns only cards for current user.

Good for you, but at our installation of v5.37 is still occurs.

I can offer you an account at our wekan so you can se it yourselves. Just PM me.

Maybe the bug has some dependencies:
- We are using snap
- We are using LDAP users. 
- Our wekan is running for >2 years, starting with v2.37. Maybe one of the (database) upgrades was creating this failure and with a fresh install it doesnt occur?

We can offer any data you need to fix this, just tell us what's necessary....

**Comment by jrsupplee** [comment]
@adelphi-company is this still happening?

**Comment by adelphi-company** [comment]
Yes, still happening on 5.83

**Comment by adelphi-company** [comment]
Problem still exists in v5.88. Maybe related to https://github.com/wekan/wekan/issues/4255 ?

**Comment by jrsupplee** [comment]
@adelphi-company could you please perform the following search and then post the *selector*:

    status:archived debug:selector

**Comment by jrsupplee** [comment]
Also, see this page I have started writing describing searching in Wekan.  Comments are welcome @xet7 

https://jrsupplee.notion.site/Searching-in-Wekan-a1fe0076764a4bed8729d6c6607b98ca

**Comment by adelphi-company** [comment]
{
  "type": "cardType-card",
  "$and": [
    {
      "$or": [
        {
          "boardId": {
            "$in": [
              "C8q8szbwtm9aNb9dS",
              "aKoxhjPM3PmG3JbNh",
              "DE6HRrTmbhy8z4PFo",
              "cFJM4XMQugShARXgQ",
              "aSfFHkoChBubqje47",
              "5PcW7YFQTjmv4JWjj",
              "qv4Hh5bCnszmbCPaf",
              "fxxrJPda8B46pYJ9y",
              "ErHfnqK6mdFdJKCoK",
              "j3MXEFScFDAEXYtDG",
              "4NFRLGnRhPganGfeS",
              "MycuNdJHnRvpB7Ten",
              "biCcH7jcDM7r6LLxM",
              "ADK5XZ58NWkgbTHuq",
              "wFSG3GHHSZABKbYbC",
              "MaXZBN5eMMKYTNohJ",
              "4mSWoJZnAQs2785Ba",
              "R8Q7EJozjebZEjRBe",
              "yForoFF2cBKRFq3rw",
              "THRk4NqWvr69Q8RvT",
              "fFK4ZdXS5DzAzLhCw",
              "atXz9gznsyuvAsgsx",
              "XmWurtsXohee6mvtY",
              "utXFzyQzacL28nxxi",
              "Ga5f4TvPkHqcXZZxG",
              "PErqSnRNrS7DqynDQ",
              "k52j8bSoYHxeCNmyR",
              "aHfC2qDumyow5Xjs5"
            ]
          }
        },
        {
          "swimlaneId": {
            "$in": []
          }
        },
        {
          "listId": {
            "$in": []
          }
        },
        {
          "archived": true
        }
      ]
    }
  ],
  "boardId": {
    "$in": [
      "C8q8szbwtm9aNb9dS",
      "aKoxhjPM3PmG3JbNh",
      "DE6HRrTmbhy8z4PFo",
      "cFJM4XMQugShARXgQ",
      "aSfFHkoChBubqje47",
      "5PcW7YFQTjmv4JWjj",
      "qv4Hh5bCnszmbCPaf",
      "fxxrJPda8B46pYJ9y",
      "ErHfnqK6mdFdJKCoK",
      "j3MXEFScFDAEXYtDG",
      "4NFRLGnRhPganGfeS",
      "MycuNdJHnRvpB7Ten",
      "biCcH7jcDM7r6LLxM",
      "ADK5XZ58NWkgbTHuq",
      "wFSG3GHHSZABKbYbC",
      "MaXZBN5eMMKYTNohJ",
      "4mSWoJZnAQs2785Ba",
      "R8Q7EJozjebZEjRBe",
      "yForoFF2cBKRFq3rw",
      "THRk4NqWvr69Q8RvT",
      "87FRpDWBpwFLsQSaj",
      "fFK4ZdXS5DzAzLhCw",
      "atXz9gznsyuvAsgsx",
      "XmWurtsXohee6mvtY",
      "utXFzyQzacL28nxxi",
      "Ga5f4TvPkHqcXZZxG",
      "TBcaKnZhPWfaPzFen",
      "K8yTTGXzPqmMH7ana",
      "PErqSnRNrS7DqynDQ",
      "k52j8bSoYHxeCNmyR",
      "aHfC2qDumyow5Xjs5"
    ]
  }
}

**Comment by xet7** [comment]
@jrsupplee 

> Also, see this page I have started writing describing searching in Wekan. Comments are welcome @xet7
>
> https://jrsupplee.notion.site/Searching-in-Wekan-a1fe0076764a4bed8729d6c6607b98ca

For those Global Search docs, can you add also add these?
- MongoDB queries you are now using for Global Search
- SQL queries you would use instead for serverside Global Search with SQLite and PostgreSQL

**Comment by jrsupplee** [comment]
@adelphi-company the user has permission to access all of these boards:

    "boardId": {
        "$in": [
            "C8q8szbwtm9aNb9dS",
            "aKoxhjPM3PmG3JbNh",
            "DE6HRrTmbhy8z4PFo",
            "cFJM4XMQugShARXgQ",
            "aSfFHkoChBubqje47",
            "5PcW7YFQTjmv4JWjj",
            "qv4Hh5bCnszmbCPaf",
            "fxxrJPda8B46pYJ9y",
            "ErHfnqK6mdFdJKCoK",
            "j3MXEFScFDAEXYtDG",
            "4NFRLGnRhPganGfeS",
            "MycuNdJHnRvpB7Ten",
            "biCcH7jcDM7r6LLxM",
            "ADK5XZ58NWkgbTHuq",
            "wFSG3GHHSZABKbYbC",
            "MaXZBN5eMMKYTNohJ",
            "4mSWoJZnAQs2785Ba",
            "R8Q7EJozjebZEjRBe",
            "yForoFF2cBKRFq3rw",
            "THRk4NqWvr69Q8RvT",
            "87FRpDWBpwFLsQSaj",
            "fFK4ZdXS5DzAzLhCw",
            "atXz9gznsyuvAsgsx",
            "XmWurtsXohee6mvtY",
            "utXFzyQzacL28nxxi",
            "Ga5f4TvPkHqcXZZxG",
            "TBcaKnZhPWfaPzFen",
            "K8yTTGXzPqmMH7ana",
            "PErqSnRNrS7DqynDQ",
            "k52j8bSoYHxeCNmyR",
            "aHfC2qDumyow5Xjs5"
        ]
    }

Login as a user with admin privileges.  Go to the "Admin Panel" -> "Reports" -> "Boards Report"

Since you have said the user is not a member of any board, team, or organization, then all of these boards must be public.  Find the above board ids in the Boards Report.

**Comment by adelphi-company** [comment]
You are totally right! Someone set all those boards to public. Thank you for clearing this finally!

**Comment by jrsupplee** [comment]
I am glad that we have finally got to the bottom of the issue
