### ISSUE TITLE
Bug: Mentioning other users in comments in maximized cards does not work

### ISSUE THREAD

**Issue by bbyszio** [wekan/wekan#3866]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: yes 
* Did you test in newest Wekan?: yes
* Wekan version: 5.35.0
* Operating System: Ubuntu 18.04.5 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node Version: 12.22.1
* MongoDB Version: 3.2.22
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?: Chrome

**Problem description**:
If I maximize a card and then want to @mention a user in a comment, the list of suggestions does not appear. 
If I write the appropriate username after the @ by hand, the mention works.
In minimized cards, the mention works as expected.

Nothing happens in the log files.

**Comment by xet7** [comment]
I presume this is fixed at https://github.com/wekan/wekan/pull/3939 .

If not, please reopen issue (or add new issue).
