### ISSUE TITLE
Can not export to Excel, CSV or TSV at Wekan (Snap)

### ISSUE THREAD

**Issue by galletl** [wekan/wekan#3869]
Hello.

Excel, CSV or TSV exports have never working on our platform.
I have seen several exchange on this point on various issues marked "closed".

When I export a board in Excel, CSV or TSV, I have a HTML document.
[export-board-excel-oHnhpfAsGJheRozdz.xlsx.txt](https://github.com/wekan/wekan/files/6685770/export-board-excel-oHnhpfAsGJheRozdz.xlsx.txt)
HTML and JSON exports work.
It is like the closed issue #3094 on Sandstorm.

Our installation : Wekan Snap on Debian 10. No automatic update, updates are made manually regularly after tests on dedicated platform.
```
~# snap version
snap    2.50.1
snapd   2.50.1
series  16
debian  10
kernel  4.19.0-11-amd64
```

This issue was reported at least on 4.48, 5.01, 5.29 versions.
We have Apache HTTP Server on front of Wekan, but the problem appears also when I access directly to Wekan without Apache HTTP Server.

I have no error in the debug log of wekan (`snap set wekan debug='true'`), just this warning :
```
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run
  meteor npm install --save bcrypt
in the root directory of your application.
```

**Comment by galletl** [comment]
Export problem appears on simple board (one list, one card).

**Comment by xet7** [comment]
@galletl 

After you have tried to export, please right click => Inspect => Console, and copy all texts to new comment of this issue. Thanks!

**Comment by galletl** [comment]
Log with the 3 browser I have on my PC, test in HTTP without Apache HTTP Server (direct access).
[Firefox.txt](https://github.com/wekan/wekan/files/6692502/Firefox.txt)
[Vivaldi.log](https://github.com/wekan/wekan/files/6692503/Vivaldi.log)
[Edge-Chromium.log](https://github.com/wekan/wekan/files/6692504/Edge-Chromium.log)

Note: the 404 error in some browser appears before I click on export feature.

Before the download, Edge-chromium indicates that the file has a size of 0 bytes.

**Comment by StefanNeubert** [comment]
Same here with Version 5.35.0 running on docker behind traefik subdomain and oidc with keycloak.
The api export links result in a http 404.

**Comment by StefanNeubert** [comment]
Seems to be an extra slash in the api endpoint.
![wekan_export_bug](https://user-images.githubusercontent.com/66677532/122929588-6b4b7200-d36b-11eb-98ff-cb2795878464.gif)

**Comment by StefanNeubert** [comment]
ROOT_URL env var has no trailing slash in this setup

**Comment by galletl** [comment]
> 
> 
> Seems to be an extra slash in the api endpoint.
In my environnement, there is no problem with JSON export.
Adding a "/" like your exemple doesn't resolve the problem for CSV/TSV/Excel export. With or without double slash, I have a page not found.
