### ISSUE TITLE
Discussion on moving cards between boards/card existing on multiple boards

### ISSUE THREAD

**Issue by xanghe** [wekan/wekan#388]
Following up on #240 and per encouragement from @mquandalle, here is a thread to discuss the issue of cards moving between boards. It looks like there are two scenarios here:
- Move card from one board to another (easily implemented, low impact)
- Allow a card to exist on multiple boards at once (more difficult, potential use-cases and impact needs to be vetted)

I use Wekan in the public sector with a small team. I often receive assignments which I then delegate to staff members. These assignments are normally isolated tasks rather than pieces of a larger project. In my scenario, I see much value in the ability for a card to exist simultaneously on my private board AND on a staff member's private board. Moving a card could be useful in other scenarios, too, but my vote would be for the "multiple board" model.

What do you think?

**Comment by akhockey21** [comment]
I really like that idea, although i don't know if the development is worth the time for me right now. I think "copy card to another board" and "move card to another board" is very needed right now. 

Im actually thinking of working on it around the end of the month.

**Comment by xanghe** [comment]
Yes, you're right that the immediate need is to move/copy cards to another
board. I wish I was well-versed enough to help in the development of this
feature.

Are there any other thoughts on the usefulness of the "multiple board"
model?

**Comment by hsduk** [comment]
Hi
FYI: I have pushed a card clone feature to https://github.com/hsduk/wekan/tree/plugin-simple-timer

**Comment by xanghe** [comment]
Wow, will have to update to try it. 

Does the sample card on https://github.com/wekan/wekan/pull/389 show that it is associated with three boards at once, or are those "child boards?" And same questions with the Lists: does the card reside in multiple lists simultaneously?

**Comment by hsduk** [comment]
Hi,
When you click the clone icon, upto 25 boards are shown, in order of last updated.
When you select a board, the lists for that board are displayed. Selecting a list will copy the current card to the bottom of that list.

**Comment by xanghe** [comment]
Ok, I see. Thanks.

**Comment by nidico** [comment]
> Are there any other thoughts on the usefulness of the "multiple board" model?

Maybe - my use case is the following:

- Each project (we have around 15 "projects" in our team, everybody shall have access to all of them) has one board
- Each person has a board which displays all cards (of any board) in which they are a member.

However I feel like such a personal dashboard might be better implemented as a separate feature, and not in a "personal board", as the semantics of the personal board columns wouldn't be clear, also the column state of the "real board" of the respective card would need to be displayed somehow.

**Comment by xet7** [comment]
Moved to #797

**Comment by sirup** [comment]
I want to comment on 
**Allow a card to exist on multiple boards at once (more difficult, potential use-cases and impact needs to be vetted)**

I think this is a very important feature. Use case: People/small teams/projects have their own board. They mark the most important/big tasks (cards). All important cards from the different boards are then shown in a "meta board". So big teams or project teams can talk about the most important stuff in all projects!

Is this planned in any way?
