### ISSUE TITLE
Upcoming upgrades: Meteor 2.2 to 2.3, Node.js 12.x to 14.x, MongoDB 3.2.x-4.x to 5.x, attachments, email sending

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3881]
# Summary: Upcoming upgrades

For [Snap users](https://github.com/wekan/wekan-snap/wiki/Install), all updates and upgrades happen automatically after they have been released.

1. Meteor 2.2 to 2.3, there is [this In Progress Wekan PR that does not work yet](https://github.com/wekan/wekan/pull/3903) and discussion in this issue
2. Node.js 12.x to 14.x, also included in PR at 1 above
3. MongoDB 3.2.x-4.x to 5.x: a) [this In Progress Meteor PR](https://github.com/meteor/meteor/pull/11556) because [MongoDB 5.0 release notes/removed commands](https://docs.mongodb.com/manual/release-notes/5.0/#removed-commands) mentioned syntax change for creating database indexes, command has changed from `ensureIndex` to `createIndex`. b) Also in Wekan, change all of `ensureIndex` to `createIndex`.
4. Wekan attachment handling: [from CollectionFS to Meteor-Files](https://github.com/wekan/wekan/pull/3273#issuecomment-868438191). Meteor-Files works on x64, and needs testing does it work at arm64/s390x/ppc64le. Meteor-Files has attachment progress indicator #4038 
5. Bugfixes to Wekan attachment handling #3709 #2635 #3774 #3776 etc
6. Email fixes #3702 and [In Progress Meteor Discussion](https://github.com/meteor/meteor/discussions/11547) and and [In Progress Meteor PR](https://github.com/meteor/meteor/pull/11554)
7. Fix Registration still visible after Disable "Self Registration" in Admin Panel #3971
8. According to Meteor Impact talk 2021-10-21 [Meteor Accounts 2.0 and Beyond](https://impact.meteor.com/meetings/virtual/Pyem5vNjDGWRP9jHd), there are some plans and discussion about Meteor Accounts to have core integrated login packages for Passwordless, [2FA](https://github.com/wekan/wekan/issues/3058), [Apple](https://github.com/wekan/wekan/issues/2458), WebAuth, maybe also OAuth2. No mention of [Oracle OIM](https://github.com/wekan/wekan/wiki/Oracle-OIM). No plans for [Auth0 that currently Wekan already supports](https://github.com/wekan/wekan/wiki/OAuth2#auth0), but they are open to discussions about it, so [xet7 added comment to discussion about accounts improvements here](https://github.com/meteor/meteor/discussions/11653#discussioncomment-1521490). 

<hr>

## Upgrade to Meteor 2.3

Hi,
there is new version Meteor 2.3:
https://docs.meteor.com/changelog.html

About previous upgrades:
- [Howto upgrade Node.js version](https://github.com/wekan/wekan/commit/2201372744639ade3ba74b6ff9115988f011b9ac)

About CollectionFS, GridFS etc for MongoDB and files saved to database:
- CollectionFS is forked to `wekan/packages/wekan-cfs-*` to fix [fix downloading non-ASCII filename crashed](https://github.com/wekan/wekan/commit/c2da47773552a61d45b010a095f73d2e441f687c)
- Packages are added to `wekan/.meteor/packages` with `meteor add wekan-cfs-something`
- Newer Meteor may have a way to use MongoDB and GridFS without CollectionFS
- There is [PR for changing from CollectionFS to Meteor-Files](https://github.com/wekan/wekan/pull/3273#issuecomment-836687510) but it had some problems like:
  - requiring some writable temprorary directory that can be different on various Wekan platforms for migrating files for reasons I don't know
  - unanswered questions about is some file publicly accessible or requiring authentication

I tried moving those `wekan/packages/wekan-cfs-*` away to outside of wekan directory, and removing them from `wekan/.meteor/packages` and `wekan/.meteor/versions`. This way I also removed as many other dependencies until Meteor upgrade to 2.3 was possible.

About this migrations step:

> Old API for packages definitions has been removed. The old underscore method names (e.g. api.add_files()) will no longer, please use the camel case method names (e.g. api.addFiles()).

For this, I changed at `wekan/packages/somepackage/package.json` those `api.add_files` to `api.addFiles`.

After that, I have been adding some dependencies back based on error messages about what is missing, and commenting out some code that does not yet have working dependency added, like related to GridFS

My current In Progress of trying to upgrade is here:
https://github.com/wekan/wekan/tree/upgrade-meteor-2.3

@jankapunkt Can you look at this?

**Comment by jankapunkt** [comment]
Is something currently crashing since the upgrade to 2.3?

**Comment by xet7** [comment]
@jankapunkt 

Wekan does not work yet [at In Progress branch](https://github.com/wekan/wekan/tree/upgrade-meteor-2.3), because all dependencies have not beed added yet. For example, I attachments with GridFS does not work yet, so I commented that part of code out so I could progress to see next error. Login like OAuth2/LDAP/Sandstorm does not work yet, because it would require changes to allowed dependencies, like allowing `http@2.0.0`.   They are not compatible, so I'm thinking, can those dependencies be updates, or do I need to fork every dependency that is not yet forked to `wekan/packages/`.

**Comment by jankapunkt** [comment]
@xet7 so I checked and Meteor 2.3 removed lots of deprecated code and includes Blaze 2.5, which in turn also removes deprecazted code. I think we should fokus on removing this old code in wekan, too instead of just trying to get it running.

I will investigate and comment here with a list of potential removals and their potential replacements. First thing I spottet is `tap:i18n`, which has not been updated since 2016. A potential replacement is `ostrio:i18n` but it's not a drop-in replace, there needs to be updates in many places. Let me see what I can do.

**Comment by jankapunkt** [comment]
@xet7 can you add me as contributor, so I can directly add commits to the `upgrade-meteor-2.3` branch?

**Comment by xet7** [comment]
@jankapunkt 

Added.

**Comment by xet7** [comment]
There is now new branch [`upgrade-meteor-2.3-try2`](https://github.com/wekan/wekan/tree/upgrade-meteor-2.3-try2) where current status is:
- Uses Node.js v14.x
- It's possible to login and add list, use some menus

TODO:
- Ability to add card. Current error is: `formComponent is undefined` at list.js

Help welcome.

**Comment by xet7** [comment]
Also, currently building Snap versions of Wekan is broken, so I need to figure out how to fix those, before I can continue developing features.

**Comment by StorytellerCZ** [comment]
Took a quick look on some of the packages in the branch and I have to agree with @jankapunkt, some of them have had for a while a maintained replacement. For now just forking them locally will work, but eventually code upgrade will be necessary.

**Comment by xet7** [comment]
@StorytellerCZ 

For which dependencies there is maintained replacement available? What is replacement package name?

**Comment by xet7** [comment]
Currently I have error:
```
Uncaught TypeError: formComponent is undefined
```

With this kind of code. Any idea what package I have missing?

```
const formComponent = this.childComponents('addCardForm')[0];
    let sortIndex;
    if (position === 'top') {
      sortIndex = Utils.calculateIndex(null, firstCardDom).base;
    } else if (position === 'bottom') {
      sortIndex = Utils.calculateIndex(lastCardDom, null).base;
    }

    const members = formComponent.members.get();
```

**Comment by xet7** [comment]
it's in some list.js file at `wekan/client/components/lists/*`

**Comment by xet7** [comment]
Related discussion at https://forums.meteor.com/t/help-test-2-3-1-rc/56196/25

**Comment by xet7** [comment]
Snap error is at https://forum.snapcraft.io/t/automated-reviews-and-snapcraft-2-38/4982/24

**Comment by StorytellerCZ** [comment]
@xet7 For starters anything meteorhacks/kadira related, for example:
`meteorhacks:picker` => `communitypackages:picker` https://atmospherejs.com/communitypackages/picker

I've made the Picker update as it stopped working for me in new releases.

**Comment by xet7** [comment]
I added also new forum post about Snap error to https://forum.snapcraft.io/t/building-wekan-snap-failed/25400 , and also commented in request to rebuild Snap package about that I would like to have info how to fix it.

**Comment by xet7** [comment]
@StorytellerCZ 

With `communitypackages:picker` I get this error:

```
=> Modified -- restarting.                    
I20210712-23:25:17.926(3)? Presence started serverId=6audM8CTe9DqF9hGz
W20210712-23:25:19.277(3)? (STDERR) /home/wekan/.meteor/packages/meteor-tool/.2.3.0.10lra21.5op4++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210712-23:25:19.278(3)? (STDERR) 						throw(ex);
W20210712-23:25:19.278(3)? (STDERR) 						^
W20210712-23:25:19.279(3)? (STDERR) 
W20210712-23:25:19.279(3)? (STDERR) ReferenceError: Picker is not defined
W20210712-23:25:19.280(3)? (STDERR)     at module (models/export.js:145:3)
W20210712-23:25:19.280(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210712-23:25:19.281(3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210712-23:25:19.281(3)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20210712-23:25:19.281(3)? (STDERR)     at /home/wekan/repos/wekan/.meteor/local/build/programs/server/app/app.js:27827:1
W20210712-23:25:19.282(3)? (STDERR)     at /home/wekan/repos/wekan/.meteor/local/build/programs/server/boot.js:401:38
W20210712-23:25:19.282(3)? (STDERR)     at Array.forEach (<anonymous>)
W20210712-23:25:19.282(3)? (STDERR)     at /home/wekan/repos/wekan/.meteor/local/build/programs/server/boot.js:226:21
W20210712-23:25:19.283(3)? (STDERR)     at /home/wekan/repos/wekan/.meteor/local/build/programs/server/boot.js:464:7
W20210712-23:25:19.283(3)? (STDERR)     at Function.run (/home/wekan/repos/wekan/.meteor/local/build/programs/server/profile.js:280:14)
W20210712-23:25:19.284(3)? (STDERR)     at /home/wekan/repos/wekan/.meteor/local/build/programs/server/boot.js:463:13
```

**Comment by StorytellerCZ** [comment]
I'll look into it, probably an import issue. I'll get a PR ready.

**Comment by jankapunkt** [comment]
@StorytellerCZ can you please check If you can append it to my ongoing PR?

**Comment by StorytellerCZ** [comment]
> @StorytellerCZ can you please check If you can append it to my ongoing PR?

Will do

**Comment by xet7** [comment]
Now Wekan Snap builds are fixed, and I released newest Wekan Snap version!

**Comment by xet7** [comment]
Wekan Snap fix info is here https://forum.snapcraft.io/t/building-wekan-snap-failed/25400/18

**Comment by xet7** [comment]
@StorytellerCZ 

Any ideas how to get router and translations working in this branch?
https://github.com/wekan/wekan/tree/upgrade-meteor-2.3

**Comment by xet7** [comment]
I figured out fi translation, and I'm looking at other changes too.

**Comment by xet7** [comment]
Well, it seems it did kind of work once, and not anymore after that.

**Comment by xet7** [comment]
Moved to here from Slack

Filipe Névola  10 hours ago
Hi, I don’t see specific errors or breaking changes that you are getting in the latest comments of this issue.
Are you having specific issues with Meteor core?

jkuester  3 hours ago
I once updated to 2.3 and it worked (you can see in the commit history of the PR), it seems to have now some issue with meteortesting:mocha  I am currently close to the next milestones at work so I have not so much time right now. @xet7 did you change anything on the testing side of things?

xet7  5 minutes ago
I have merged changes from master to that meteor 2.3 branch. For me, router (login sign-up etc) has not worked at all, and translations did work once but not after that.
I don't know do all various ways to login work because most are removed from wekan/packages/
And it seems AccountsTemplate etc are commented out
Anyway you can look at it later when you have time

There has been new features etc in master branch that uses Meteor 3.2 and Node 12.22.6
for that I have made new releases

**Comment by xet7** [comment]
Also currently there are some errors related to Team/Organizations changes. I'll try later and add those messages etc.

**Comment by xet7** [comment]
I'm currently enjoying reading:

https://blog.kronis.dev/articles/never-update-anything

There in article I found definition about who I am:

"If things don't work out that way, then eventually we'll just have bunches of clueless code monkeys that execute npm commands that they don't understand to use frameworks and mechanisms which they have no hope of understanding to create as much value as quickly possible in the short period before all of that goes to hell and there's the eventual breakdown of nothing working and noone having any idea of why. I'm exaggerating slightly, but sooner or later software projects out there will exceed the cognitive capabilities of any single person - the only question is whether that will happen in 50 or 500 years."

And also there is recommendation to use Lazarus/FreePascal, that can be installed locally, and used offline. I have not yet figured out how to do any other web framework dev offline, npm etc always requires online downloads etc.

https://news.ycombinator.com/item?id=29106159 , that I commented about [here](https://news.ycombinator.com/item?id=29127944)

**Comment by xet7** [comment]
@mfilser 

About trying to upgrade Meteor, like mentioned at https://github.com/wekan/wekan/issues/4061#issuecomment-1014955119

Below instructions, while most likely you know some of these, are just reminder for myself, so that I can later read these and know all related details.

Building WeKan in detailed at https://github.com/wekan/wekan/wiki/Emoji

In https://github.com/wekan/wekan repo, there is branch upgrade-meteor-2.3 . It's possible to send pull requests to that branch.

As seen from https://docs.meteor.com/changelog.html , current Meteor version is v2.5.3

That Meteor version uses Node.js v14.

For changing Node.js version, currently I use volta at https://github.com/wekan/wekan/blob/master/rebuild-wekan.sh#L34

So installing newest Node.js v14 would be:
```
volta install node@14
```
Or alternatively specific version:
```
volta install node@14.18.3
```
Volta also installs compatible npm version.

Or downloading from https://nodejs.org/dist/latest-v14.x/

When upgrading Meteor, it first needs some cleanup
```
cd wekan
meteor reset
```
Then upgrade meteor:
```
meteor upgrade --release 2.5.2
```
Then rebuild WeKan
```
./rebuild-wekan.sh
```
Choose option 2 to rebuild.

Then run it with option 3 etc.

If there are missing dependencies, meteor will show what commands to run to install those.

Then merge latest changes from master:
```
git merge master
```
This could bring some merge conflicts, that you see with git status.

When you open file with nano, showing current line position with option -c
```
nano -c file.js
```
With Ctrl-w you search form these kinds of lines:
```
====
```
or
```
<<<<
```
And there make changes to combine differences between branches, remove those `====` and `<<<<` lines, commit and push those changes.

When starting WeKan, at browser inspect console there will show some errors. Those are from various dependencies.

How to do translations has changed in those upgrade commits. When previously Wekan translations were at `wekan/i18n/*.i18n.json`, now instead they have been moved to `wekan/public/i18n/`. With other code files at `wekan/i18n/*`, those now at WeKan runtime get only current translation from public directory, so those are not anymore included in browserside combined Javascript. But that translation code may need more changes to make translations working.

**Comment by imajus** [comment]
> Currently I have error:
> 
> ```
> Uncaught TypeError: formComponent is undefined
> ```
> 
> With this kind of code. Any idea what package I have missing?
> 
> ```
> const formComponent = this.childComponents('addCardForm')[0];
>     let sortIndex;
>     if (position === 'top') {
>       sortIndex = Utils.calculateIndex(null, firstCardDom).base;
>     } else if (position === 'bottom') {
>       sortIndex = Utils.calculateIndex(lastCardDom, null).base;
>     }
> 
>     const members = formComponent.members.get();
> ```

I've faced the same issue when trying to upgrade Wekan to Meteor 2.6 by myself. In order to isolate the issue I've created a fresh Meteor application. 
In order to reproduce the issue locally do the following:
```
git clone https://github.com/imajus/meteor-blaze-components-child-components-issue-demo.git
cd meteor-blaze-components-child-components-issue-demo
meteor npm install
meteor npm start
```
Then, open http://localhost:3000 in the browser and note the output:
```
Child components:
- template2
- template3
```

**Comment by imajus** [comment]
My research on the issue has resulted in the following findings:
1. It MAY BE that the breaking change was introduced in `peerlibrary@blaze-components@0.16.0` update. Note the excerpt from the HISTORY.md file:
    > Block helpers components are correctly positioned inside the component tree. Fixes [#50](https://github.com/peerlibrary/meteor-blaze-components/issues/50) and [#51](https://github.com/peerlibrary/meteor-blaze-components/issues/51).
2. There is a [discussion](https://github.com/peerlibrary/meteor-blaze-components/issues/50) available where we could find out the reason for this update. 
3. Apparently this is a "bugfix" on which current Wekan UI source code relies as on a feature, and since it was fixes the Wekan UI breaks down.

**Comment by imajus** [comment]
I've updated my example repository to reflect the actual templates hierarchy in question.
It's based on the templates hierarchy from Wekan:

```html
<template name="listBody">
  {{#inlinedForm}}
    {{>addCardForm}}
  {{/inlinedForm}}
</template>
```

And I also extended the output, so now with the old `peerlibrary:blaze-components` version I'm getting this:

```
[template3] Parent component: template1
[template2] Child components: N/A
[template4] Parent component: template1
[template1] Child components: template2 template3 template4
```

And this is the output for the latest version of `peerlibrary:blaze-components`:

```
[template3] Parent component: template2
[template2] Child components: template3
[template4] Parent component: template1
[template1] Child components: template2 template4
```

Simply put it means that when `template3` is rendered inside the template `template2` using `Template.contentBlock` it used to consider outer template as a parent for `template3` but after the `peerlibrary:blaze-components` bugfix it now considers `template2` as a parent for `template3`. This is also affects what `childComponents` returns in the same way.

**Comment by imajus** [comment]
And here's [the fix](https://github.com/majus/wekan/commit/d10ac4247c4981cfc25ad7cf41433920f6367d13#diff-10ccc45947d48c87297ca71b98bb91d6a0444404a7ec95fa375149f4d6713fd4) for the issue.

**Comment by xet7** [comment]
This issue is mostly about upgrades we have already done.
