### ISSUE TITLE
Building OpenAPI docs is broken in Wekan v3.56

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3884]
Hi,
building OpenAPI docs is broken in upcoming Wekan v3.56. Maybe it's related to added tests?
https://github.com/wekan/wekan/blob/master/CHANGELOG.md
```
$ ./releases/rebuild-docs.sh 5.36
Traceback (most recent call last):
  File "./openapi/generate_openapi.py", line 1073, in <module>
    main()
  File "./openapi/generate_openapi.py", line 1068, in main
    schemas, entry_points = parse_schemas(args.dir)
  File "./openapi/generate_openapi.py", line 824, in parse_schemas
    program = context.program
AttributeError: 'NoneType' object has no attribute 'program'
✓ Read source file!
✗ Error during conversion via Widdershin:
Cannot read property 'swagger' of undefined
```

@bentiss can you look at this?

**Comment by xet7** [comment]
For Wekan v5.36, I only changed version number manually, because generating API docs does not work currently.

**Comment by bentiss** [comment]
Well, it was a bad logic from my side. Anyway, #3889 should fix it (until next time :-P )

**Comment by xet7** [comment]
@bentiss 

Thanks a lot ! :slightly_smiling_face:
