### ISSUE TITLE
Feature Requests: Attachment file preview

### ISSUE THREAD

**Issue by listenerri** [wekan/wekan#3888]
wekan version: 5.30.0, running in docker container.

I found that when I clicked directly on the text attachment uploaded to the card, it would keep loading.

After analysis, I found that the wekan was requesting and opening the text file as a picture, and when clicking on the picture attachment, everything worked fine.

So I guess the preview feature for text attachments is not supported, it would be great if this feature could be implemented.

**Comment by Meeques** [comment]
WeKan 6.09.0 running with ubuntu snap.
I have the same request :)
