### ISSUE TITLE
Performance degradation because of archived swimlanes

### ISSUE THREAD

**Issue by andreasgrill** [wekan/wekan#3893]
My colleagues and I've noticed that the performance of a Wekan board degrades over time, even if [wekan-cleanup](https://github.com/wekan/wekan-cleanup) is used. For instance, creating or moving cards is getting very slow.

Today I finally found the reason for this!
On our board we create and archive swimlanes pretty regularly. Usually the swimlanes contain cards when they get archived.
Now Wekan only sets the `archived` field of the swimlane to true but leaves the cards untouched. 
After I manually set the `archived` field of the cards with archived swimlanes to true, the performance of the board improved dramatically. My guess is that the non-archived cards are fetched even though they are not displayed because of their archived swimlane.

I'd like to create a PR to fix this, however, I wanted to check first what would be the preferable solution here. 
The quick fix would be to archive the cards too if their swimlane (or list) gets archived, but this would lead to a new issue where a restored swimlane would always be empty without any card.

A slightly better solution would be to add an additional field to the the cards that indicates whether they were archived because of their swimlane (or list). With that information they could be automatically unarchived along with their swimlane.
I'd also add a db migration that would set the fields accordingly.

Of course this could also be solved through wekan-cleanup, but I guess a solution directly within Wekan would be the cleaner way.

Right now we are using Wekan: 5.27.0 with docker-compose.

**Comment by xet7** [comment]
@andreasgrill 

1) Restore swimlane from archive

2) Click swimlane hamburger menu

3) Click move swimlane, to move swimlane to another board.

**Comment by xet7** [comment]
If you don't have Move Swimlane feature, please upgrade to newest Wekan.

**Comment by andreasgrill** [comment]
@xet7 
We have fixed this issue for the moment on our board by setting all non-archived cards with archived swimlanes to `archived: true` directly in mongo db. 

I just wanted to know your opinion before creating a PR.

**Comment by xet7** [comment]
@andreasgrill 

Please send PR. Thanks!

**Comment by mfilser** [comment]
@andreasgrill
If i can make a suggest: I personally would extend the current database query to get only cards of active swimlanes. Adding an extra field to cards increases the program logic, and moving cards to archive if the swimlane is archived could lead to other issues and maybe break backwards compatibility. 
If you extend the database query maybe it's helps too to add a new index at the database for a faster query.

But as i told, it's just a suggestion and how i would solve it if i would code this 😉

**Comment by xet7** [comment]
I don't know yet does having cards of archived swimlane also be actual archived cards break something, before getting that PR and trying it.

Having only visible cards loaded possible with current Meteor publications/subscriptions would require, that someone would add code to:
1) Start subscription when visible
2) Stop subscription when not visible

And also with upcoming Collapsible Swimlanes, hide and collapse swimlane and stop subscription of that swimlane.

Because current Wekan loads all cards of one board to browserside. For very big boards, that's just too much. Also, exporting very big boards does not work for similar reasons.

**Comment by andreasgrill** [comment]
Thanks for your feedback!
I'll look into it.
