### ISSUE TITLE
Question: How to find out my MongoDB user/pass & how to auto login

### ISSUE THREAD

**Issue by crewnew-git** [wekan/wekan#3898]
We have the lastest Wekan snap. 

1. We're integrating Wekan with our time tracker so that for example from this URL wekanserver.com/b/rBSNhWw3yTT6TZPtw/test-project/uopmZXZjwPrXNCsGs we would automatically track time for the project `test-project` and would like to also get the task name from the card name that is probably doable if we search MongoDB `uopmZXZjwPrXNCsGs`
2. Another question is that id the user is logged into our app then we would like the user to be automatically also logged in to Wekan. Via token? Not sure how to achieve that.

**Comment by xet7** [comment]
@crewnew 

1. At Wekan Snap, MongoDB listens only localhost 27019 https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui . It does not have username/password, and it's not accessible directly from Internet.

2. Autologin currently exists on in Sandstorm Wekan version https://github.com/wekan/wekan/blob/master/sandstorm.js#L370 .  For others, it has not been fully implemented yet #2019 , pull requests welcome. Some related code is:
- https://github.com/wekan/wekan/blob/master/server/header-login.js
- How to set headers https://github.com/wekan/wekan/blob/master/server/cors.js#L5

**Comment by xet7** [comment]
1. Password can be changed at `Admin Panel / People / People / Edit` or using REST API:

- https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API
- https://github.com/wekan/wekan/wiki/Adding-users
- https://wekan.github.io/api/v5.37/#new_user

**Comment by xet7** [comment]
When using Wekan REST API, not all database fields are editable with `edit_user` REST API. Missing fields can be added to this REST API code https://github.com/wekan/wekan/blob/master/models/users.js#L1808 using similar editing REST API code that is used elsewhere at `wekan/models/*.js` to edit field values. It's welcome for anyone to add missing code and send pull request. Here is how to build Wekan and send pull request https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin . Thanks!

**Comment by xet7** [comment]
Moved to #4311
