### ISSUE TITLE
"archive all" button doesn't work

### ISSUE THREAD

**Issue by jadeqwang** [wekan/wekan#390]
When I try to archive all cards in a list, I can't.

![image](https://cloud.githubusercontent.com/assets/1584904/11014229/b1be1ea0-84e2-11e5-8774-df2ef948a095.png)

**Comment by skitoo** [comment]
I have the same problem.

**Comment by mquandalle** [comment]
Thank you for the bug report. I’m considering removing that option in favor of the more-flexible multisection workflow: you can click “Select all cards in this list” on the list menu and then on the sidebar “Archive selection”. That’s one more click but I feel that archiving all cards of a list isn’t a very common task so doing it in two clicks is reasonable, and I also want to encourage the usage of MultiSelection for this kind of operation.

What do you think?
