### ISSUE TITLE
Unable merge user oauth2 + LDAP

### ISSUE THREAD

**Issue by jas01** [wekan/wekan#3904]
## Issue

After configuring oauth2 authentication (against Keycloak) and LDAP connection, I can connect with both but end up to be two differents accounts. The LDAP accounts are working since one year, just configure the oauth2. 

The

  `LDAP_MERGE_EXISTING_USERS=true`

but the accounts was'nt merge.

I don't know if it's a bug or a feature. I notice the email from LDAP are with upper/lower case, but the email send by keycloak are only lowercase. Don't know if that's why wekan are unable to merge

I really like to known if I can modify/merge user by hand (currently I don't have a lot of users.

## Configuration

Docker :
   Version : wekan 5.37
   mongodb : latest

**Comment by xet7** [comment]
@jas01 

Maybe by editing database, changing user IDs ?
https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui

There is also take ownership API call, but I have not used it:
https://github.com/wekan/wekan/blob/master/models/users.js#L1815

**Comment by jas01** [comment]
I eventually fix the problem. 

With a gui client of mongodb Il modify the old account authentication method and add the uid (don't know why ldap did'nt do that)

Thanks
