### ISSUE TITLE
When ROOT_URL is set, the Kanban cannot be exported normally

### ISSUE THREAD

**Issue by liyongxin** [wekan/wekan#3906]
## Issue

**Server Setup Information**:
docker-compose  with wekanteam/wekan:v5.38 image

* Did you test in newest Wekan?:yes
* Wekan version: wekanteam/wekan:v5.38
* Operating System: CentOS7
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
Chrome 92.0.4515.101

**Problem description**:
when i set ROOT_URL=http://<my-ip>:3000/wekan, the Kanban cannot be exported normally.
But when i set ROOT_URL=http://<my-ip>:3000, the Kanban can exported normally

Is any other settings to resolve this question? thanks

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Settings
