### ISSUE TITLE
Ldap do not want work

### ISSUE THREAD

**Issue by devagleo** [wekan/wekan#3908]
## Issue

**Server Setup Information**:
Wekan Version 5.35.0
Meteor version 2.2
Node version  12.21.0
MongoDB version 5.0.0-rc2
MongoDB storage engine: wiredTiger
OS Type: Windows_NT
OS Platform: win32
OS Arch: x64
OS Release: 10.0.17763

**Problem description**:
I spent 2 weeks implementing LDAP in wekan. I am getting the same error as the other 52e date. I'm sure my credentials (userdn and password) are exactly correct. I tried to create different credentials, use a different container for userdn. I even brought up a new clean Active Directory but I get the same error.
![Error](https://user-images.githubusercontent.com/41387583/126342946-29dd659e-2926-422e-b22f-e88904bc92a6.png)

What else have I tried:
Use MongoDB version 4.4.7, 5.0.0, 4.2.15;
Use as a server: Windows Server 2019, Windows Server 2012 R2;
Use Active Directory 2012 R2;
Create users inside Wekan and set LDAP authorization;
Use the option for authorization: login or login@domain.srv;
I read all the issues about LDAP here.

Local password authorization works great. Through LDAP, no.
I really liked the wekan project and I want to implement it in the organization, but without ldap authorization I will not advance further, please help.
[start-wekan-Impersonal.txt](https://github.com/wekan/wekan/files/6849142/start-wekan-Impersonal.txt)

**Comment by xet7** [comment]
@devagleo

Please do not use MongoDB 5.x, it has made incompatible changes to Wekan MongoDB syntax. Use only MongoDB 4.2.x or 4.4.x.

For 52e error, please look at previous 52e errors https://github.com/wekan/wekan/issues?q=is%3Aissue+52e+is%3Aclosed

**Comment by devagleo** [comment]
I've looked at previous questions on error 52e, nothing helps. Maybe the error is related to this?
![Error](https://user-images.githubusercontent.com/41387583/126469112-f5ccf2f4-dc10-4b69-9126-445ae7f7bcac.png)

**Comment by xet7** [comment]
@devagleo 

No, those bcrypt and DeprecationWarniong are not related to this.

Please try LDAP AD Simple Auth in [Wekan v5.39](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v539-2021-07-24-wekan-release) or newer:
https://github.com/wekan/wekan/wiki/LDAP-AD-Simple-Auth

**Comment by devagleo** [comment]
Thank you very much! It really helped, the authorization went through and the search requests started. Just before the full launch, I fixed a couple of errors.
This has already been discussed earlier, but let me remind you who got here in the first.
Be sure to specify general or any other filter for your search
SET LDAP_USER_SEARCH_FILTER = (objectClass = user)
I met a new paramtr, I have not met him before:
SET LDAP_EMAIL_FIELD = mail

After fixing LDAP it worked.
