### ISSUE TITLE
Creating a new user does not save initials and full name

### ISSUE THREAD

**Issue by AuspeXeu** [wekan/wekan#3911]
## Issue
Creating a new user does not persist the user's initials and full name

**Server Setup Information**:
v5.38

**Problem description**:
1. Go to admin panel
2. click 'new' in the people > people panel
3. Fill in the information and hit save
4. The new entry in the table is missing the initials and the full name of the user you just created

**Comment by devagleo** [comment]
v5.41 same problem

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3946
