### ISSUE TITLE
Delete of Planning Poker doesn't work

### ISSUE THREAD

**Issue by hatl** [wekan/wekan#3915]
## Issue

**Server Setup Information**:

* Wekan version: v5.38
* Operating System: docker image wekanteam/wekan:v5.38
* MongoDB Version:
* Browser: latest Chrome (92)

**Problem description**:
* Add Planning Poker to a card
* Try to delete it -> delete button doesn't seem to do anything

**Comment by xet7** [comment]
@helioguardabaxo 

Can you look at this?

**Comment by xet7** [comment]
Nevermind, I already figured this out.
