### ISSUE TITLE
total number of cards above each list

### ISSUE THREAD

**Issue by Jan02** [wekan/wekan#392]
total number of cards above each list should be shown

**Comment by xanghe** [comment]
:+1:

**Comment by hsduk** [comment]
Hi, I think is only useful when there are many cards. Having this for say less than 8 cards is unnecessary?

**Comment by AndrewGearhart** [comment]
Would be great as a board setting (show list member count after)
0: never
1: always
Any other positive number... After that number is reached.

**Comment by choclin** [comment]
I would love to have such a functionality and as @AndrewGearhart suggest, it should be a board setting.
If it is not too complicated it would also be great to have a setting that shows the number of cards if not all cards are within the browsers viewport.

**Comment by xet7** [comment]
Wekan already has this.
