### ISSUE TITLE
Change standard Tracking setting to "follow" instead of "silence"

### ISSUE THREAD

**Issue by docknack** [wekan/wekan#3921]
Thank you for the great wekan tool. As company we suggest to work with it, but we miss some little features.
We use the snap Version of wekan (automatic updates)  on a Ubuntu Server and it would be nice to add a settings for the standard tracking option. So I wish, it were possible to set the tracking to "follow" as standard instead of "silence".

**Comment by xet7** [comment]
Moved to #2026
