### ISSUE TITLE
JSON exports can no longer be imported since version 5.32.

### ISSUE THREAD

**Issue by homer1993** [wekan/wekan#3922]
## Issue

JSON exports can no longer be imported since version 5.32. The import fails with the error code 500.

**Server Setup Information**:

Version information: 
Wekan 5.32 and above. 
Mongo Version 4.4 
Docker Version: 20.10.7
Operating System: Ubuntu 21.04

**Problem description**:

- JSON exports can no longer be imported since version 5.32. The import fails with the error code 500 and the message "Map members: Your imported board has some members. Please map the members you want to import to your users. Note: Unmapped members will be assigned to the current user."
- If you confirm this message with "done", the import will not be continued. The user mapping does not take place.
- The behavior occurs regardless of whether a user is selected via the "map members" editor or not.
- For my test, I installed a Docker environment with the respective Wekan version tag. In the test procedure, I create a board with always the same content. Then I export it via JSON. Then I import it via JSON.
- For the test I have all versions from 5.15 to 5.36. taken into account. Up to and including version 5.30 the import works without an error message. The behavior only occurs from version 5.32.

Error Message: 
![Import-Error](https://user-images.githubusercontent.com/51082485/127022657-9b8fad4d-ad59-4dfc-bc09-75cdc5964dd9.png)

Docker-Compose:
[docker-compose-wekan532.txt](https://github.com/wekan/wekan/files/6879732/docker-compose-wekan532.txt)

Wekan-App-532 Container Log: 

Exception while invoking method 'importBoard' TypeError: Cannot read property 'forEach' of undefined
    at WekanCreator.createBoardAndLabels (models/wekanCreator.js:274:26)
    at WekanCreator.create (models/wekanCreator.js:955:26)
    at MethodInvocation.importBoard (models/import.js:35:20)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43

**Comment by xet7** [comment]
Oops sorry, this is already fixed #3918 but not yet released, I'll try to make release soon. When it's released, I'll close this issue. Thanks!

**Comment by homer1993** [comment]
Thank you for
1) a great open source project,
2) stable software releases which I have been using productively for years and
3) the persistence for support over this long life cycle.
I am very grateful to always have this Kanban board by my side.

Very cool that there is already a fix for this. I will use 5.30 until the fix is ready.

**Comment by xet7** [comment]
Wekan v5.41 released with this fix. Docker Hub image with tag v5.41 is already ready.

**Comment by xet7** [comment]
I also started Quay Docker image builds a moment ago.
