### ISSUE TITLE
Consolidate helm charts

### ISSUE THREAD

**Issue by varac** [wekan/wekan#3923]
The current helm chart situation for wekan is confusing. There are 3 different helm charts:

* [gabisonfire/wekan](https://artifacthub.io/packages/helm/gabisonfire/wekan) as an independent helm chart published at artifacthub (see also https://github.com/wekan/wekan/issues/3226#issue-671767929)
* The [wekan/charts fork of above chart](https://github.com/wekan/charts), which seems like an exact copy of the gabisonfire/wekan  chart
* The [helm chart in the git wekan/wekan repo](https://github.com/wekan/wekan/tree/master/helm/wekan) (all last updated 2021/02)

It would be nice to improve this situation, because as long as the [Helm chart install options in the Wiki are missing](https://github.com/wekan/wekan/issues/3226), it's unclear to me which chart to use best. Thanks !

**Comment by xet7** [comment]
@varac 

- Only [helm chart in the git wekan/wekan repo](https://github.com/wekan/wekan/tree/master/helm/wekan) is official.
- I added link to Wiki download section.
- Official Download links are at https://wekan.github.io Download section. There was already previously text `Kubernetes` so I changed it to `Helm Chart for Kubernes` to make it more clear.

Newest environment variables are at [docker-compose.yml](https://github.com/wekan/wekan/blob/master/docker-compose.yml). Please send pull request to add them to [helm chart in the git wekan/wekan repo](https://github.com/wekan/wekan/tree/master/helm/wekan). Thanks!

**Comment by xet7** [comment]
@varac 

I archived [wekan/charts repo](https://github.com/wekan/charts) and changed it's link to wiki page.

**Comment by xet7** [comment]
@varac 

Wiki page is here https://github.com/wekan/wekan/wiki/Helm

**Comment by xet7** [comment]
Also, nobody has answered does this bug still happen #3375

**Comment by varac** [comment]
@xet7 Thx for your quick responses!

> Only helm chart in the git wekan/wekan repo is official.

Would you mind publishing the official helm chart on https://artifacthub.io ? It would increase the visibility of wekan there, and simplify the installation when there's a proper helm repository for wekan.

> Newest environment variables are at docker-compose.yml. Please send pull request to add them to helm chart in the git wekan/wekan repo.

I'll take a look and will do a PR if needed !

**Comment by xet7** [comment]
@varac 

Yes, PR is required. For keeping Wekan working with helm chart, it's required that those using helm chart contribute to keeping it up-to-date. I don't know anything about helm charts or kubernetes, I have not used kubernetes.

**Comment by varac** [comment]
> Yes, PR is required. For keeping Wekan working with helm chart, it's required that those using helm chart contribute to keeping it up-to-date. I don't know anything about helm charts or kubernetes, I have not used kubernetes.

Sure, I understand. I'm happy to contribute to the helm chart, but the chart hosting needs to be done by project maintainers.
Here's an example [how to host a chart using github pages](https://helm.sh/docs/topics/chart_repository/#github-pages-example) , and how to [automate releases using the chart releaser action](https://helm.sh/docs/howto/chart_releaser_action/). Disclaimer: I have not used github action myself.

**Comment by xet7** [comment]
@varac 

Yes, after your PR is done, I will setup chart hosting, github actions etc. I have maintained Wekan [since 2016-12](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v0110-2016-12-16-wekan-fork-first-release).

**Comment by varac** [comment]
Awesome !

**Comment by varac** [comment]
Official chart is now here: https://artifacthub.io/packages/helm/wekan/wekan
