### ISSUE TITLE
Error binding with background sync LDAP with AD and OpenLDAP

### ISSUE THREAD

**Issue by devagleo** [wekan/wekan#3926]
**Server Setup Information:**
Wekan Version 5.41.0
Meteor version 2.2
Node version 12.22.3
MongoDB version 4.2.14
MongoDB storage engine: wiredTiger
OS Type: Windows_NT
OS Platform: win32
OS Arch: x64
OS Release: 10.0.17763

**Problem description:**
Error when background syncing.
![Background Sync Error](https://user-images.githubusercontent.com/41387583/127366284-8e5b87ca-b008-409c-8eaf-ec9c5a4a69cd.png)

**Configuration about background sync:**

> LDAP_BACKGROUND_SYNC=true
> LDAP_BACKGROUND_SYNC_INTERVAL=every 1 minute
> LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=true
> LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=false
> LDAP_SYNC_USER_DATA_FIELDMAP={"samAccountName":"name","displayName":"Full name", "mail":"email"}
> LDAP_UNIQUE_IDENTIFIER_FIELD=sAMAccountName

**P.S.**
As it should be, I studied all similar issues, therefore, in the direction, but I did not find a solution or a similar question.
I can assume that the problem may be related to the new parameter that I am using LDAP_AD_SIMPLE_AUTH = true. Because the authorizations themselves when entering wekan work fine and binding success, only the background sync does not work.

**Comment by xet7** [comment]
@devagleo 

> LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=false

Maybe this should be `true` ?

https://github.com/wekan/wekan/wiki/LDAP#ldap-filter-settings

**Comment by devagleo** [comment]
I dont need 8k peoples in wekan. IMPORT_NEW_USERS=false, but update KEEP_EXISTANT_USERS_UPDATED=true. Sync get first people YurcheIS in Wekan, going to AD and get error.

**Comment by xet7** [comment]
Moved to here from https://github.com/KanRule/ldap/issues/93

From @olivierlambert 

## Syncing wekan groups with OpenLDAP?

Hi there,

I'm not sure if this feature exists or not. If it does, how to configure it? (I currently have a successful user LDAP sync: however, when we create a new board for a "functional team", that would be lovely to avoid adding users one by one, but instead assign a group that will be the same than the LDAP one)

From @xet7 

Newest Wekan LDAP code is here:
https://github.com/wekan/wekan/tree/master/packages/wekan-ldap

Some wiki settings here:
https://github.com/wekan/wekan/wiki/LDAP

LDAP sync works for some, as can been seen from some previous closed issues, but I don't have any LDAP server so it depends about LDAP using contributors who can figure it out and add pull request if needed.
