### ISSUE TITLE
Default language for all new users

### ISSUE THREAD

**Issue by devagleo** [wekan/wekan#3927]
Can I set the default language for all users when they sign in and when working with boards?
I read in previous issues that the language is stored in cookies, but maybe it can be set globally when starting the server in the configuration?

**Comment by xet7** [comment]
@devagleo 

There is not that feature yet. [Languages are listed here](https://github.com/wekan/wekan/tree/master/i18n). Maybe you could use shell script? For example, for Snap, changing to language `de`, those 2 places in database query:

`lang.sh`
```
#!/bin/bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/wekan/current/lib/x86_64-linux-gnu
export PATH="$PATH:/snap/wekan/current/bin"
mongo --port 27019 < lang.js
```

`lang.js`
```
use wekan
db.users.update({"profile.language":{$ne:"de"}},{$set:{"profile.language":"de"}},{multi:true})
```
Also set script as executeable:
```
chmod +x lang.sh
```

**Comment by xet7** [comment]
For Windows, it's like this:

`lang.bat`
```
mongo --port 27017 < lang.js
```
`lang.js`
```
use wekan
db.users.update({"profile.language":{$ne:"de"}},{$set:{"profile.language":"de"}},{multi:true})
```

**Comment by devagleo** [comment]
> For Windows, it's like this:
> 
> `lang.bat`
> 
> ```
> mongo --port 27017 < lang.js
> ```
> 
> `lang.js`
> 
> ```
> use wekan
> db.users.update({"profile.language":{$ne:"de"}},{$set:{"profile.language":"de"}},{multi:true})
> ```

I used it, the welcome page really seems to have changed to the desired language, but for new users the language after authorization remained English. 
My understanding is that db.users.update updates the language to all existing users, but not new ones. Is there some solution possible?

**Comment by xet7** [comment]
@devagleo 

Well, maybe `createUser` at https://github.com/wekan/wekan/blob/master/models/users.js should read some new language setting like `LANG` similar [like this](https://github.com/wekan/wekan/blob/master/server/header-login.js#L2), for example `process.env.LANG` and set it to public variable, and save it to profile when creating user, and from that public variable read it somewhere nere here:
```
./client/components/main/layouts.js:      } else if (lang.name === 'en-IT') {
./client/components/users/userHeader.js:      } else if (lang.name === 'en-IT') {
```

Then, at Admin Panel could be something similar to [Hide System Messages](https://github.com/wekan/wekan/commit/a249ffc8054189d8e3db9b4c8f082cc7ce7dcb52) to set language for all users.

So, maybe someone could figure it out and send pull request, with info provided above. (Or maybe me, if nobody volunteers).

@helioguardabaxo What do you think?

**Comment by xet7** [comment]
And [add that setting to all platforms like this](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v539-2021-07-24-wekan-release).

**Comment by devagleo** [comment]
I would like to continue the conversation.

> ./client/components/main/layouts.js:      } else if (lang.name === 'en-IT') {
> ./client/components/users/userHeader.js:      } else if (lang.name === 'en-IT') {

For new users, the language is perfectly chosen.

But for people who are not registered and open public boards by link, they still get the wrong language.
For them, I would like to change the view of the board view from Swimlanes to Lists
