### ISSUE TITLE
Link attachments in md

### ISSUE THREAD

**Issue by hsduk** [wekan/wekan#393]
Q: If I upload an attachment to a card, is it possible to reference that attachment, e.g image or video in-line, in the card description md? I.E. Do attachments have a secure href I can link to? I.E. Only the app can serve the attachment to a logged in user. Haven't tried, but know would be useful.
I guess the logical next is to specify if an attachment is private or public so card attachments can be served elsewhere when linked.

**Comment by mquandalle** [comment]
You can click right on the attachment and “Copy link”.

**Comment by chm-tm** [comment]
Note that it suffices to refer to the path of the link. You can omit host name and query.
