### ISSUE TITLE
PostgreSQL integration wiki not working

### ISSUE THREAD

**Issue by crewnew** [wekan/wekan#3930]
https://github.com/wekan/wekan-postgresql gives 404

**Comment by xet7** [comment]
@crewnew 

Where is that old link?

At https://wekan.github.io Download Server section is button `ToroDB PostgreSQL` that goes to this new address:
https://github.com/wekan/wekan/tree/master/torodb-postgresql

**Comment by crewnew** [comment]
Googled "wekan integrations" and first result was: https://github.com/wekan/wekan/wiki/Integrations

**Comment by xet7** [comment]
I updated link. Thanks!

**Comment by C0rn3j** [comment]
https://github.com/wekan/wekan/wiki/PostgreSQL

Also completely broken here

**Comment by xet7** [comment]
@C0rn3j 

I updated those pages.

ToroDB is not developed anymore. Try FerretDB instead, if you have time, I have not yet figure out all the required settings.

https://github.com/wekan/wekan/wiki/PostgreSQL

**Comment by C0rn3j** [comment]
Still waiting for https://github.com/wekan/wekan/issues/4780 which this is apparently actually a blocker for, but if you decide to go for Mongo for snap in the end, I might look into it later.

I already run postgre, and getting rid of mongo would be nice, but unfortunately I don't have that much spare time at the moment.

**Comment by xet7** [comment]
@C0rn3j 

I'm in progress of changing to SQL databases. Not keeping MongoDB.
