### ISSUE TITLE
Wekan image with MongoDB

### ISSUE THREAD

**Issue by thytetgc** [wekan/wekan#3931]
Are there any docker images with MongoDB already integrated?

I cannot install separately....

**Comment by xet7** [comment]
@thytetgc 

Do you mean, that you cannot use docker-compose.yml at https://github.com/wekan/wekan , and would need to use only Docker commands like this?
https://github.com/wekan/wekan/wiki/Docker#example-for-latest-wekan-port-2000-to-docker-wekan-internal-port-8080

When there is separate wekan-app and wekan-db containers, upgrading is removing old wekan-app container and adding new one, keeping mongodb container the same.

Or do you really need them to be in same container?

Or would you like to have Wekan without Docker? Like at https://github.com/wekan/wekan/wiki/Raspberry-Pi ?

Or have offline install? https://github.com/wekan/wekan/wiki/Offline

**Comment by xet7** [comment]
If you have anything to add, please reopen issue. Thanks!
