### ISSUE TITLE
Docker only at Quay for Wekan >=v5.42. Docker Hub not building.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3932]
Hi,

## Docker images at Quay works

at docker-compose.yml at https://github.com/wekan/wekan , currently images are building only at Quay, like for example with:
```
image: quay.io/wekan/wekan:5.42
```

## Docker images at Docker Hub does not work

I previously applied to [Docker Hub Open Source program](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/), but have not yet received reply about progress.

A moment ago I sent this email to Docker Hub:

Hi,
I'm today releasing Wekan v5.42 to Docker image wekanteam/wekan,
it has critical security update to Node.js 12.22.4.
I do not see any builds happening on Docker Hub web interface.
What is the status of my application to Docker Open Source Program?

**Comment by AuspeXeu** [comment]
Still missing v5.43

**Comment by xet7** [comment]
@AuspeXeu 

Thanks for info! I started builds for v5.43 .

**Comment by xet7** [comment]
at Quay

**Comment by xet7** [comment]
@AuspeXeu 

That depends when Docker Hub has time to respond to my email, I presume they get a lot of email, so it could take some time.

I think Wekan does fill all the criteria of being fully FOSS, and [Docker Hub has Open Source program](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/) for keeping FOSS Docker images available for free.

Docker Hub web UI looks like they have made some change, so it's not possible to start builds at all. Builds seems to be available only for paid plans.

**Comment by xet7** [comment]
@AuspeXeu

This Docker image is now available:
```
image: quay.io/wekan/wekan:v5.43
```

**Comment by marek94901** [comment]
Hello, i have such a beginner question if we have versions 5.41 and 5.42 bug fixes so how can i solve the upgrade? We use docker on Synology devices.

**Comment by xet7** [comment]
@marek94901 

Maybe this, using quay image? https://github.com/wekan/wekan/issues/3874#issuecomment-867526249

Also see https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
I figured it out. I tried downloading Docker image from Quay.io and uploading it to Docker Hub. So now newest Wekan is also at Docker Hub.
