### ISSUE TITLE
Wiki Backup page improvements

### ISSUE THREAD

**Issue by C0rn3j** [wekan/wekan#3941]
https://github.com/wekan/wekan/wiki/Backup

Two small things - one is using formatting for the code blocks for colored syntax - ie using \`\`\`bash instead of just \`\`\`
```bash
sudo snap stop wekan.wekan
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/wekan/current/lib/x86_64-linux-gnu
export PATH="$PATH:/snap/wekan/current/bin"
mongodump --port 27019
sudo snap get wekan > snap-settings.sh
```

Another one is that snap paths aren't the same on all systems, for example, on Arch the path is `/var/lib/snapd/snap` and not just `/snap`, so it took me a bit to recognize that I need to edit the above code block.

**Comment by xet7** [comment]
@C0rn3j 

Thanks! I added syntax formatting.

Please add comment that has working code example of all those path changes for that script above that has 5 lines of text. I have not used Arch, so I can not test myself.

**Comment by C0rn3j** [comment]
https://gitlab.com/C0rn3j/configs/blob/8c13ac94c447e79248e8f102c7e59aee33199dca/ansible/playbooks/roles/server_wekan/files/backup.sh#L10

Only other change(which is not Arch specific) aside from the path, is letting the LD_library variable be unset `${LD_LIBRARY_PATH-}`, (the - at the end) as it is not set in the systemd unit env, which is how I run my backup script, and it was erroring out as I've enabled exit on unset variables.

**Comment by xet7** [comment]
Info added https://github.com/wekan/wekan/wiki/Backup#backup-wekan-snap-to-directory-dump
