### ISSUE TITLE
Can't download PDF file 

### ISSUE THREAD

**Issue by namacoconut** [wekan/wekan#3943]
Dear @xet7 , Good day,

I am using wekan V-- 5.25.0 using snap image

and when I upload a pdf file I can't download it, is shows : 403 access denied error

any recommendation please!
--

**Comment by xet7** [comment]
@namacoconut 

I tested with newest Wekan Snap, uploading and downloading PDF works with Wekan and Caddy.

Please upgrade to newest Wekan Snap, for example this way manually:
```
sudo snap refresh
```

If you use Nginx in front of Wekan:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

Then please set enough big attachment file size: https://github.com/wekan/wekan/issues/2103#issuecomment-455014303

**Comment by Nissulya** [comment]
Is there any limit per board? We only have the same problem on a board with many attachment. 
They can be uploaded and it worked on this board for some time, but now board members and board admins get 403 trying to download even small attachments.

client_max_body_size is set in nginx to 50M
It's wekan 6.09.0, snap on Ubuntu 22.04.1 LTS

**Comment by xet7** [comment]
@Nissulya 

I don't use Nginx, I use only Caddy.

Also, I use only newest WeKan 8.x https://wekan.fi/upgrade/
