### ISSUE TITLE
Trello don´t import attachments 

### ISSUE THREAD

**Issue by gusben2020** [wekan/wekan#3950]
## Issue
Hi.
Wekan imports boards from trello, (using JSON way) but without attachments.
jul/21/2021 was working and importing attachments (with version 5.05)
today do not import attachments in 5.05 or in 5.49 version.

may be any with AWS hosting attachments of trello, but I can´t find any log to detect.

im runing wekan server on windows 10

Any with the same trouble?.
Thanks

**Comment by gusben2020** [comment]
in Public board there is no problem.
It seems like trello secured links to attachments.
Wekan can´t download attachments from private boards.
Could I give some credentials to wekan to do this?

**Comment by xet7** [comment]
@gusben2020 

Depends when someone figures out how to download Trello attachment. I tried, but did not get it working yet. Help is very welcome. If someone figures out how to download attachment from Trello private board with authenticated access with curl, node.js or any other programming language and adds that code (with sensitive keys removed) as comment to this issue, it would help someone to [fix this import code](https://github.com/wekan/wekan/blob/master/models/trelloCreator.js#L423) and add [input fields](https://github.com/wekan/wekan/tree/master/client/components/import) for API keys to Wekan import from Trello. Maybe someone could even figure out how to create pull request with those changes.

Trello API keys are at https://trello.com/app-key

There is this announcement: https://community.developer.atlassian.com/t/update-authenticated-access-to-s3/43681

How to authorize to Trello API:
https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/

Here is Trello attachment REST API docs:
https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-cards-id-attachments-idattachment-get

At Atlassion Trello developer community is some posts about Authenticated access to S3:
https://community.developer.atlassian.com/c/trello/42

**Comment by helioguardabaxo** [comment]
Hi, @xet7 !
Maybe this code would be useful to export attachments from Trello:
https://github.com/Ben0it-T/trello-board-exporter

**Comment by xet7** [comment]
@helioguardabaxo 

That code at https://github.com/Ben0it-T/trello-board-exporter does not seem to have MIT license or similar.

To get attachments from Trello:

1. WeKan Import from Trello page should have field for Trello API key
2. Trello API key should be in download request headers like this https://github.com/wekan/wekan/blob/master/trello/api.py#L141
3. In Javascript here https://github.com/wekan/wekan/blob/master/models/trelloCreator.js#L452

Most other stuff is already imported from Trello to WeKan.

**Comment by Ben0it-T** [comment]
Hi @xet7 and Happy New Year
I added a license at https://github.com/Ben0it-T/trello-board-exporter

I've also been doing this https://github.com/Ben0it-T/trello-attachments-export for the past few days, initially for testing. The idea was to test if we could easily add to 'JSON export' a cards.attachments.file containing attachment

**Comment by xet7** [comment]
Moved to #4877
