### ISSUE TITLE
Support for export to JSON

### ISSUE THREAD

**Issue by singpolyma** [wekan/wekan#396]
to import into another instance with the import from json function

**Comment by xavierpriour** [comment]
I'm on it!
I'll just code the exporting of a whole board (no card or list), if you don't mind.

**Comment by singpolyma** [comment]
works for me. Thanks!

**Comment by xavierpriour** [comment]
Hey @mquandalle, a JSON export to me is pretty much the first step of an API, so I'd like to implement this as a route to /api/b/:id that would return the proper json. The UI will just be a link to that URL.

I would do the routing using https://atmospherejs.com/simple/json-routes, and code the json myself.

Is that fine by you?

**Comment by mquandalle** [comment]
Didn’t know `simple:json-routes`, but from a quick look at it and given that is developed by MDG core members that seems like a pretty good choice. I also agree that redirect to the JSON document itself is a good idea for an export.

**Comment by xavierpriour** [comment]
After some thougths, I think we need a proper Wekan JSON format for export & import. Using Trello format limits us to only data that Trello has and forces us to do some unnatural mappings.

So I'm going to code that - a clean export, and then an import for that.

**Comment by singpolyma** [comment]
Are the mappings really that unnatural? The apps are almost exactly the same...

**Comment by mquandalle** [comment]
This was also my impressions on the matter, I agree with Xavier about the need for our own format. This will become even more required once we implement the plugin ecosystem that will probably differ significantly from what Trello currently have (and Trello format hasn’t be designed to be re-used by third party software anyway). 

Xavier feel free to share some of the design considerations about the export format once you had the time to figure them out.

**Comment by xavierpriour** [comment]
In addition to Maxime's remark, we already have lots of small things that differ:

- colors and permissions are not the same (both field name and acceptable values)
- comments in Trello are stored as a type of activity, Wekan store them as specific objects
- Wekan has the notion of an owner/creator for a board or list, Trello does not
- the Trello export has no field to store the board slug (short name)
- the names for all activities are different
- etc.

None of the above is currently blocking, but it requires verbose code to transcode everything.

**Comment by mquandalle** [comment]
Though the downside of having our own format is that people won’t be able to import a Wekan board into Trello... But I guess if it is a highly requested feature someone will write a JSON from Wekan to JSON of Trello transpiler at some point.

**Comment by xavierpriour** [comment]
I don't think you can import a Trello board into Trello actually.

**Comment by mquandalle** [comment]
Oh woah I forgot that, maybe with the Entreprise edition? (or maybe if you contact the support by e-mail?). Anyway you are right, so Wekan to Trello import are even less a concern than I initially thought.

**Comment by xavierpriour** [comment]
For the export format, I'm going with the internal Wekan format for the moment (minus the repeated field boardId, and sensitive userId like password or mail). Should be "good enough" for a first pass.

**Comment by mquandalle** [comment]
I wonder if we should denormalize the data as Trello does (with the re-normalization task at import time) or if could generate something more like clasical database exports where we can refer to previous document using their identifier. For that we could even use a format like Netflix [JsonGraph](http://netflix.github.io/falcor/documentation/jsongraph.html) (or similar) which would potentially provide some integration with some third party tools and libraries.

**Comment by xavierpriour** [comment]
I believe normalized data is the way to go. Concise, consistent, easy to code and understand.

I'm sceptical of JsonGraph, it seems to be pretty verbose and reminds me a little of the xml formalism. Why all the $ref, $type, etc?

**Comment by mquandalle** [comment]
I searched for JsonGraph alternatives but wasn’t able to find any popular project (but people complaining that the JSON spec should have references... it’s right :-)).

JsonGraph is indeed a little bit verbose (I guess using a `{$ref: 'refId'}` would be enough for references) but that’s not really a problem. I think that having a clear document like the one I linked above to explain the reference format is an advantage for potential third parties implementors. In a further future we may also use GraphQL here for now I would say that it would be over-engineering.

**Comment by xavierpriour** [comment]
Or maybe http://jsonapi.org/ ?

**Comment by mquandalle** [comment]
JsonAPI seems explicitly designed in the context of a request-response architecture. It looks for designing an actual API but isn’t that a bit overkill for a simple reference convention in our exports? (The project looks good by the way, seeing Steve Klabnik as an author is reassuring, and they seems to be a fair number of implementations).

**Comment by xavierpriour** [comment]
Damn, I've hit a wall regarding authentication/authorization:

- with simple:json-routes, I have a beautiful url, and return json easily BUT I'm outside the usual Meteor context, so no access to userId. To protect access, I would have to use API token authentication, which means asking for user password again, and using additional packages to turn this into a valid token.
- without simple:json-routes, I actually could not find any doc on how to have FlowRouter return json instead of a web page.

Any idea?

**Comment by mquandalle** [comment]
(on my phone in a bar right now, so sorry for the somehow short response) Maybe option 2, but replacing FlowRouter by Picker? Not sure if the Auth will be automatic but I'm pretty sure there is a reasonable way to make it work.

**Comment by xavierpriour** [comment]
None of the API-optimized/serve-side routers provide smooth authentication from a logged-in client - which is logical: they expect a first call to authenticate and get a token, then supplying that token to each API call.

So I've backtracked and implemented it as a UI-driven file download using [filesaver](https://atmospherejs.com/pfafman/filesaver), and everything works great. The export code itself is isolated, so the API can call it too once we have start implementing it.

**Comment by mquandalle** [comment]
Yes it is logical since generally speaking HTTP is only used as an client-agnostic distribution protocol in Meteor, and the actual authenticated communications between the server and the client happen on DDP. However, I know that @arunoda’s FastRender was able to serve authenticated HTTP using a classical HTTP cookie (`meteor_login_token`). I’m pretty sure that we could re-use that token to authenticated a specific HTTP route.

If I understand correctly Filesaver works iff the client has all the required data (all activities, comments, etc.)? If yes, I guess it’s still worth to investigate server-side generation for the export.

**Comment by xavierpriour** [comment]
Board export is called from the board view, which means client already has all the data. Why force a server generation?

**Comment by mquandalle** [comment]
I think we don’t send the activity feed in the general board view publication as of today.

At some point we will also have better efficiency (à la Facebook/Relay) about the amount of data we send to the client — for instance there is no point in sending all the cards comments just to being able to compute the number of comments on a card client side; we already feeling the lag because of that on large boards like the Meteor Roadmap.

**Comment by xavierpriour** [comment]
Server-side done!
For the records, here's the blog post that explained it: https://blog.kayla.com.au/server-side-route-authentication-in-meteor/
