### ISSUE TITLE
Export JSON Files

### ISSUE THREAD

**Issue by gusben2020** [wekan/wekan#3966]
**Error importing large board from JSON code**
Hi,

I´m newbie about this.

I have been doing some test with backup over Json files.

A) Import from JSON FILES 
I think that would be a good Idea import a board from a json files.
I tried from clipboard, the only method available, with a large booard, 120 Mb, Chrome and Edge run out of memory, just firefox works, but with errors, and the board shows up and few seconds later goes away.
  
B) Duplicating a Board
I have been thinking that, 
1)  duplicating a board
2) export to JSON the second copy, to do it over clean copy. Avoiding errors and runing a clean-up.py previosly

But I detect when I duplicate a board of 120Mb 
the export (JSON Files) of the second board dont have atachment and ,20kb
the export (JSON Files) of the first board ,240 Mb. it can´t be restored trought clipboard

seems like all attachment stay with the first board, just in the  exportation proces. The attachemnt are in each copy of the board at presentation.

Thank you very much

**Comment by xet7** [comment]
Moved to #3966

**Comment by nstoeckigt** [comment]
This is still a very annoying Issue, so what is meant by 'Moved to #3966' - THIS is #3966!

What are the plans to fix this?

**Comment by xet7** [comment]
@nstoeckigt 

Sorry, I tried to write: Moved to #4615 , where is listed similar issues.
