### ISSUE TITLE
[Bug] Card number equal to #0 when creating a sub-task from a card

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#3970]
## Issue
**Problem description**:
When creating a sub-task from a card, the card number of all the subtasks cards will have card number #0

**N.B.**: 
- it happens even if the sub-task is created in another board
- it happens even if the card number setting is activated after the sub task is created

**How to reproduce**:   ![See video in attachment](https://user-images.githubusercontent.com/74183327/130997331-6aba1fe9-0f30-4fae-835e-5a4a87fdd21a.mp4)

**Comment by marcungeschikts** [comment]
Hi, 
The bug is fixed, but as I still have some cards with #0 as card number, I have one board where I can't open card anymore with card number #0 and all the parent cards linked. It is stuck and after few seconds I have the following message.
![Page ne répondant pas](https://user-images.githubusercontent.com/74183327/134210343-580afafe-7db0-4179-b278-8e20d3e677e5.png).
For the other card, I have no issue to open its.
I have the issue in one board...but I did not reproduce on another board(smaller) with #0 card.

N.B.: I tried to copy the swimlane with  the #0 cards to another board, but unfortunately, it duplicated some of the cards in the original board and in the targeted board, and I was not able either to open the card in the swimlane copied :( @

**Comment by xet7** [comment]
@marcungeschikts

Also, is there errors with:
```
sudo snap logs wekan.wekan
```
or alternatively:
```
docker logs wekan-app
```

**Comment by marcungeschikts** [comment]
> Is there errors at browser right click / Inspect / Console? Please copy them to comment to this issue.

![console](https://user-images.githubusercontent.com/74183327/134218318-3cfeeb38-a5d2-4057-b538-0949c928ede8.png)

**Comment by marcungeschikts** [comment]
> Click the link after `n.lastLabel` and take screenshot and paste to comment.
![nlabel](https://user-images.githubusercontent.com/74183327/134227717-3f6cac32-286e-4052-b16e-46ea20365351.png)

**Comment by olivierlambert** [comment]
FYI, `sudo snap logs wekan.wekan` doesn't return anything relevant (only LDAP sync tasks, no warning or errors)

**Comment by xet7** [comment]
I think it's somewhere here:
https://github.com/wekan/wekan/blob/master/client/components/activities/activities.js#L114-L119

Can someone try to figure it out why there is error detecting name undefined?

Info how to build Wekan is at: https://github.com/wekan/wekan/wiki/Emoji

**Comment by xet7** [comment]
And what is at database there? It can be looked like this:
https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui

**Comment by xet7** [comment]
Well, I think if it goes to this part:
```
    } else {
      return lastLabel.name;
    }
```
but name is still undefined, so I think I'll add additional check before that return.

**Comment by marcungeschikts** [comment]
Unfortunately even on  wekan  5.60       1711   latest/stable  xet7   
We still have the same issue:
![error#0](https://user-images.githubusercontent.com/74183327/134539133-3e00154c-bd38-4837-8acf-d24ad5c91a2f.png)
