### ISSUE TITLE
Feature Request - Foldable swimlanes

### ISSUE THREAD

**Issue by ygaeon** [wekan/wekan#3973]
As a user I'd like to be able to fold my board's swimlanes so that I can easier focus on the swimlane I'm currently working with, as I have many cards in each swimlane.

Perhaps a `toggle` button on the `swimlane-header` could add/remove `style="visibility:hidden;height:0;"` to the following `<div>`?
```html
<div id="swimlane-xxxx">...</div>
```
It gives the desired effect when I test it in developer tools.

**Comment by xet7** [comment]
Moved to #2804
