### ISSUE TITLE
feature request: LDAP/Active Directory authentication

### ISSUE THREAD

**Issue by paulotfilho** [wekan/wekan#398]
It would be awesome to use LDAP/Active Directory to authenticate in Wekan. I don't know how difficult it is to do that, but I know there is a meteor-account-ldap package for logging in and creating users with LDAP credentials.

**Comment by snolahc** [comment]
Hey, there already is a feature request for LDAP : #199 
+1 for this, i won't be able to install it for my teams without it

**Comment by juggernate** [comment]
:+1:

**Comment by paulotfilho** [comment]
Hi @snolahc, I think you mean issue #119. Sorry for opening a duplicate issue.

**Comment by mquandalle** [comment]
Let’s move to #119.
