### ISSUE TITLE
SandStorm Upgrade from 5.27 Error: Package hash did not match.

### ISSUE THREAD

**Issue by PizzaProgram** [wekan/wekan#3980]
SandStorm Version: 0.286 (latest 2021-08)
1. No "Upgrade" butting appears.

2. If clicking APPS > Wekan > Install button, 
 following error happens:  (copied from Standstorm SysLog)

```
Downloading app: https://app-index.sandstorm.io/packages/e199df9a4913c201e046eb1643625d42
Failed to install app: Error: Package hash did not match.
    at AppInstaller.<anonymous> (imports/server/installer.js:344:17)
    at Request.<anonymous> (imports/server/installer.js:237:23)
    at Request.emit (events.js:326:22)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
sandstorm/gateway.c++:1072: error: exception = kj/compat/tls.c++:66: failed: OpenSSL error; message = error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
stack: 51bff4 5223e2 522a15 565fc1 5234c0 51e020 5f7310
sandstorm/gateway.c++:1072: error: exception = kj/compat/tls.c++:66: failed: OpenSSL error; message = error:100003f2:SSL routines:OPENSSL_internal:SSLV3_ALERT_UNEXPECTED_MESSAGE
stack: 51bff4 5223e2 522a15 565fc1 5234c0 51e020 717f80
sandstorm/gateway.c++:1072: error: exception = kj/compat/tls.c++:66: failed: OpenSSL error; message = error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL
...
```

In the last 2 month Sandstorm upgraded Let's Encrypt SSL + dependencies. Maybe that's why?
`OPENSSL_internal:WRONG_VERSION_NUMBER` , `SSLV3_ALERT_UNEXPECTED_MESSAGE`, `UNSUPPORTED_PROTOCOL` ... are very suspicious for me.

**Comment by PizzaProgram** [comment]
PS: translated and fixed 150+ strings today to Hungarian at Transiflex.

**Comment by xet7** [comment]
@PizzaProgram 

I did also get some error, then I clicked "Try again", and it did install Wekan update, and open new Wekan version

I don't know what those TLS errors are about. Maybe it's more of Sandstorm issue, at https://github.com/sandstorm-io/sandstorm/issues ? @zenhack @ocdtrekkie @kentonv any ideas?

Thanks a lot for your translations!

**Comment by xet7** [comment]
@PizzaProgram 

I do always download newest translations before releasing new Wekan version. Thanks!

**Comment by ocdtrekkie** [comment]
Yeah the OpenSSL errors likely just refer to attempts for old clients with old TLS versions trying and failing to connect to Sandstorm. No big deal.

**Comment by PizzaProgram** [comment]
Thank you all! Try again WORKED.  Version 5.53.0~2021-08-27 .

PS: Sadly still no EXPORT menu available :-(
![kép](https://user-images.githubusercontent.com/26026089/131230356-24f3a977-af8a-47ab-875d-00794018b4c6.png)
