### ISSUE TITLE
Minor visual issue: align lists when some have a WIP limit and others don't

### ISSUE THREAD

**Issue by mattdm** [wekan/wekan#3985]
## Issue
**Problem description**:

I think this is clear from one screenshot: see how list 2 is pushed down because it has a Work In Progress Limit? It'd be nice if they were all pushed down evenly.

![image](https://user-images.githubusercontent.com/123367/131764255-cb2bf247-175c-4ed8-b38a-8127763b6ba7.png)

I'm currently working around this by giving WIP limits of 1000 to other columns. This feels icky to me, though. It'd be nice for them to just align. 

An alternate workaround might be to have the option of showing a card-count on a list without showing a limit. That could be activated for lists without WIP, bringing them all into alignment.

**Comment by VidVidex** [comment]
I think this has already been fixed at some point (I'm running wekan 6.98).

![image](https://github.com/wekan/wekan/assets/18378617/d3044a5e-5fff-486a-8184-71cbb2199abb)
