### ISSUE TITLE
Disappear marked checklist items

### ISSUE THREAD

**Issue by devagleo** [wekan/wekan#3988]
## Issue

**Server Setup Information**:
* Wekan version: Tested on 5.54.0
* If this is about old version of Wekan, what upgrade problem you have?: Additional tested on 5.39.0
* Operating System: Windows Server 2019
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Windows LAN Offline
* Node Version: 12.22.3
* MongoDB Version: 4.2.14
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?
Test Google Chrome, Edge.

**Problem description**:
When I check the items in the checklist, they disappear, but other users see as usual that these items are crossed out.
It bug works only for my account. I have tested on different machines and other users have tested on my machine.
I don’t know how it happened and I couldn’t find any settings to fix it. I would not like to create a new account.
Create new checklist
![1](https://user-images.githubusercontent.com/41387583/131815696-fef0bd17-03a5-4bc1-8d3e-1a392b4d7264.jpg)
Checklist not checked - all works.
![2](https://user-images.githubusercontent.com/41387583/131815709-e1de4ba2-67a5-45b0-82b8-e6a1fb74cbfd.jpg)
I check first item. It dissapear. Other users see as usual that these items are crossed out
![3](https://user-images.githubusercontent.com/41387583/131815713-7c1c50f1-b366-4479-a57d-c0bdb9812877.jpg)

In all boards of my account.

**Comment by helioguardabaxo** [comment]
Hi, @devagleo!

Did you enable "hide checked items"?
In my card all items are showing when switch(top right) is disable:
![image](https://user-images.githubusercontent.com/24301085/131841366-f3d2156f-a73c-4c4a-a8a5-fedf29eab18e.png)

When I enable this switch marked items disappear:
![image](https://user-images.githubusercontent.com/24301085/131841517-a541ae09-6ab4-4938-aade-7debd34e9afd.png)
