### ISSUE TITLE
My Cards & Due Cards

### ISSUE THREAD

**Issue by FuXXz** [wekan/wekan#3990]
Hello, everyone,

I have questions about "My Cards" and Due Cards "
Is it intended that only cards of which I am a member will appear there?

I would like to see all my due cards that I have created. But I always have to manually add myself as a member.
It would be logical that the creator can also automatically see "My Cards" and "Due Cards "

However, if I am not a member, this view is empty.

Is that a mistake or something intentional?
Thank you and best regards

**Comment by xet7** [comment]
For showing creator of cards on current board, click hamburger menu / cog icon at right side of members ar right sidebar / Board Settings / Card Settings / Creator.

My Cards shows all cards at all boards where you are member or assignee at that card.

Due Cards shows all cards at all boards where you are member or assignee and card has due date.

Sometime in future there will be new feature that shows at current board only those cards where you are member or assignee, and not any other cards.
