### ISSUE TITLE
Feature Request: Add support for swarm secrets

### ISSUE THREAD

**Issue by ww-daniel-mora** [wekan/wekan#3995]
Swarm secrets are loaded as files in /run/secrets/<secret-name>
Enable users to set *_FILE environment variables for variables which should be treated as secret.
For example the user would be able to set:
`OAUTH2_SECRET=something-very-secure`
or
`OAUTH2_SECRET_FILE=/run/secrets/oauth2-secret`
to set the value for the `OAUTH2_SECRET`.

**Comment by xet7** [comment]
@ww-daniel-mora 

Do you mean like searching [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md) about adding that setting `to all Wekan platforms` ? Or add some more related code? Can you add pull request?

**Comment by xet7** [comment]
@ww-daniel-mora 

Thanks!
