### ISSUE TITLE
mysterious refreshing

### ISSUE THREAD

**Issue by jadeqwang** [wekan/wekan#400]
While editing a card on my own board, WeKan suddenly told me in rapid succession (less than 1 sec for each of these):
- that I didn't have access to the board
- that it was loading
- my card is back open, but lost the recent changes.

I'm not sure how to repro this (the grain has not been open very long, and I recently revoked someone's access?), but I can comment again if it happens again.

**Comment by jadeqwang** [comment]
Ok, I captured video of this refreshing behavior (with console open for extra helpfulness). https://youtu.be/4_-gs7Hxm_E

After the refreshing went on for some time, it seemed to eventually recover. And then it did an auto refresh again:

![image](https://cloud.githubusercontent.com/assets/1584904/11491285/59dc26a8-9795-11e5-811a-873771f57e1b.png)

**Comment by mquandalle** [comment]
Hum, I suspect something is wrong on the server side, could you share the Sandstorm grain logs (if any)?

**Comment by xet7** [comment]
Please try with newest version. If this happens again, reopen this issue.
