### ISSUE TITLE
Continuous GET requests issued from any WeKan screen 

### ISSUE THREAD

**Issue by skye0402** [wekan/wekan#4003]
## Issue

I recognized in Chrome Debugger that several get requests are issued per second to the server, no matter which screen I am in. 
![Screenshot 2021-09-13 153904](https://user-images.githubusercontent.com/36907475/133036341-69e8b048-c8fb-4e8f-b00e-4aa79bc8fd7c.png)

They all look like this:
`https://<wekanurl>/cfs/files/avatars/SsN6iHGa824juLK35 `
where the last part is random. So in a few minutes I have several thousand requests which are answered with 404 by the server. What could be the reason?

**Server Setup Information**:

Wekan Version	5.41.0
Meteor version	2.2
Node version	12.22.3
MongoDB version	4.4.6
MongoDB storage engine	wiredTiger
MongoDB Oplog enabled	
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	5.4.0-5-cloud-amd64
OS Uptime	134 days, 46 minutes, 2 seconds
OS Load Average	4.07, 1.57, 1.02
OS Total Memory	31 GB
OS Free Memory	6 GB
OS CPU Count	8

**Problem description**:

As described above. Login screen is the same situation (no login needed to have this problem).
It is the docker image version of WeKan.

**Comment by xet7** [comment]
@skye0402 

Wekan is trying to load your avatar, did you remove it, or is it not added?

Login to Wekan => Click right top your username => Change Avatar?

(Unrelated to Wekan, but maybe also backup all, install newest available Linux kernel for Arch with newest fixes, and reboot server?)

**Comment by xet7** [comment]
Newest Node.js is 12.22.6, so if your server is exposed to Internet, maybe also update it.

**Comment by skye0402** [comment]
@xet7 I impersonated myself to another user, then I tried to change the avatar of that user which failed (there is already an open issue for this). Then I logged out, logged in as the other user, set the avatar successfully. Finally I logged back in with my user and deleted my avatar.
The get requests still were issued. I then reloaded the page with Ctrl+F5 to bypass the cache. That stopped it. So I suppose it can be reproduced by impersonating a user, set that user's avatar (it never had one before) which fails, then get back to the "real" login and see if the GETs come up. At least we have a workaround now.

**Comment by xet7** [comment]
@skye0402 

I think Node.js 12.22.6 is already at newest Docker image at quay:
```
image: quay.io/wekan/wekan:v5.58
```

Still no response from Docker Hub, that does not work: https://github.com/wekan/wekan/issues/3932

**Comment by xet7** [comment]
There is also `latest` tag at Quay https://quay.io/repository/wekan/wekan that has latest changes and newest freatures from master branch. Currently master branch does work, but I recommend running release tags, because sometimes master branch is broken.

**Comment by xet7** [comment]
According to Dockerfile, that Node.js 12.22.6 should be there: https://github.com/wekan/wekan/blob/master/Dockerfile#L15

I do update Node version for all platforms with this bash script:
https://github.com/wekan/wekan/blob/master/releases/node-update.sh

**Comment by skye0402** [comment]
@xet7 Thank you, I was able to run it with 5.58 from quay.io. The avatar bug with the GETs is still there but it can be stopped if you delete the broken upload (impersonated user), get back to Initials and "hard reload" (Ctrl+F5) the page. I you want I can close the issue as it's a minor bug and likely fixed with #3327
