### ISSUE TITLE
Feature Request: Limit uploaded file size and type

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4005]
"We are looking to limit the size of files uploaded in cards. We tried settings in nginx reverse proxy but it seems Wekan handle file splitting and then bypass the limitation. Is there any settings in Wekan to limit file size ?"

**Comment by xet7** [comment]
I added this [to Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/rRaXzAcPEYAdDYv9F)

**Comment by xet7** [comment]
Before this, I think that attachments related upgrades and fixes needs to be done first https://github.com/wekan/wekan/issues/3881

**Comment by xet7** [comment]
I will soon add this feature and settings.

In Progress code is at https://gist.github.com/xet7/dd88fa2d23f752d52fc9eeb6a1806722

**Comment by saschafoerster** [comment]
We also had users uploading video raw material with a size of 1,2 Gb. 😇 very useful when this is implemented.

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4618
