### ISSUE TITLE
Pasting text into an edit box adds extra line-breaks...

### ISSUE THREAD

**Issue by ygaeon** [wekan/wekan#4008]
## Issue

**Server Setup Information**:
```
* Wekan Version		5.26.0
* Meteor version	2.2
* Node version		14.16.1
* MongoDB version	4.4.5
* MongoDB storage engine wiredTiger
* MongoDB Oplog		enabled
* OS Type		Linux
* OS Platform		linux
* OS Arch		x64
* OS Release		4.9.0-16-amd64
* Firefox		91.0.2 (64-bit)
```

**Problem description**:

Editing comments and descriptions add extra `<p><br></p>` when copy/pasting text into the edit box.
It is text copied from `gedit`.

**Expected behaviour:**
No added extra  `<p><br></p>` when copy/pasting text into the edit box.

Attached peek:
![Peek 2021-09-13 20-48](https://user-images.githubusercontent.com/7010726/133140237-92013bac-69f9-4a6b-b667-461c8257d08b.gif)

**Comment by xet7** [comment]
You have Wekan v5.26

This was fixed 2 months ago in [Wekan v5.38](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v538-2021-07-18-wekan-release)

Please upgrade to newest Wekan that is currently v5.58
