### ISSUE TITLE
Docker Hub abandoned ?

### ISSUE THREAD

**Issue by Tuphal** [wekan/wekan#4010]
## Issue

The Docker Hub image is now 2 month old. Still at v5.41
https://hub.docker.com/r/wekanteam/wekan

From quay.io I can not pull the image in the Synology Docker GUI :/

**Comment by xet7** [comment]
Yes https://github.com/wekan/wekan/issues/3932

Also see https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
I figured it out. I tried downloading Docker image from Quay.io and uploading it to Docker Hub. So now newest Wekan is also at Docker Hub.
