### ISSUE TITLE
Can't delete attachment

### ISSUE THREAD

**Issue by luistiktok** [wekan/wekan#4012]
## Issue

Note: With Docker, please don't use latest tag. Only use release tags.
See https://github.com/wekan/wekan/issues/3874

If you can not login for any reason:
- https://github.com/wekan/wekan/wiki/Forgot-Password

Email settings:
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Add these issues to elsewhere:
- SECURITY ISSUES: https://github.com/wekan/wekan/blob/master/SECURITY.md
- UCS: https://github.com/wekan/univention/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? Yes
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?: No
* Operating System: Ubuntu 20.04 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx proxy
* Node Version:
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**Problem description**:
For some reason i cant no longer delete attachements.

![Untitled Project](https://user-images.githubusercontent.com/90870363/133683612-0b77e566-0061-4041-91e2-40e3ab88bd06.gif)

**Comment by xet7** [comment]
@luistiktok 

On that board, are you BoardAdmin or Normal user? Only BoardAdmin can delete attachments.

See https://github.com/wekan/wekan/issues/3377 and other change in [Wekan v4.60](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v460-2020-12-15-wekan-release)

**Comment by luistiktok** [comment]
Board Admin

**Comment by luistiktok** [comment]
Im using Wekan version 5.58

**Comment by xet7** [comment]
@luistiktok 

It could be something in your Nginx settings:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by luistiktok** [comment]
I did follow the instructions. I tried attaching another file and i was able to delete it. But that particular file i just cant.

**Comment by xet7** [comment]
@luistiktok 

Maybe copy text etc to other card, and then archive card, and delete card from archive.

**Comment by luistiktok** [comment]
I tried. But when trying to delete from archive i get: remove failed: Internal server error

**Comment by xet7** [comment]
@luistiktok 

At server, can you try does this show error:
```
sudo snap logs wekan.wekan
```
If you have Wekan Gantt GPL version, then instead this:
```
sudo snap logs wekan-gantt-gpl.wekan
```

**Comment by luistiktok** [comment]
Im using docker version.,

**Comment by xet7** [comment]
Oops. Docker:
```
docker logs wekan-app
```
Or:
```
sudo docker logs wekan-app
```

**Comment by luistiktok** [comment]
I created the error.log on the repo im sharing with you. Thank you
