### ISSUE TITLE
An example docker-compose.yml is not the right place for 700 lines of documentation and PR comments

### ISSUE THREAD

**Issue by timdonovanuk** [wekan/wekan#4014]
I guess the intent was trying to make the docker-compose.yml easier to use, but it's a sprawling mess and it is close to impossible to actually tell what is going on. 

That's all, thanks :)

**Comment by xet7** [comment]
@timdonovanuk 

Yeah, right! Sorry about all the documentation. It would be better for everyone to just read all of Wekan source code ;)

**Comment by xet7** [comment]
Also sorry about too many features. Yes, it's a mess ;)

**Comment by timdonovanuk** [comment]
You have clearly put a lot of time and effort into your creation, so surely you'd like as many people as possible to try it, no? I am just suggesting lowering the barrier to entry and making it more digestible.

**Comment by xet7** [comment]
@timdonovanuk 

How?

**Comment by timdonovanuk** [comment]
Here are the docker-compose files for similar kanban FOSS projects:

- https://github.com/SrGMC/kanbana#docker-compose
- https://docs.kanboard.org/en/latest/admin_guide/docker.html#docker-compose
- https://vikunja.io/docs/docker-walkthrough/#create-all-necessary-files
- https://raw.githubusercontent.com/plankanban/planka/master/docker-compose.yml
- https://github.com/mattermost/focalboard/blob/main/website/site/content/download/personal-edition/docker.md

Some are 1 line, most are under 20 lines (even the ones that ship with postgres included). I could spin up any of these in under 60 seconds to try the software. I even know they're not doing anything nefarious or harmful to my system, because I can quickly assess 20 lines quickly (vs 700!).

A wekan docker-compose with the bare minimum for what you feel is a great example of the software would be cool (I think all the LDAP option lines would be a great candidate for removal from a better example docker-compose!)

Cheers.

**Comment by mfilser** [comment]
Having a docker-compose file with all options included and also documented is, for me, well done.
No need to go through extern documentation, everything in 1 file  👏

**Comment by mfilser** [comment]
Where is the difference of reading 700 lines of extern documentation to read 700 lines of docker-compose file.?

**Comment by xet7** [comment]
@timdonovanuk 

Many use LDAP with Wekan. Some of those other kanban software don't even have LDAP.

**Comment by timdonovanuk** [comment]
I'm glad the "documentation" works for _you_, both maintainers of the project 👏 👏 👏 Seems like you cannot or are unwilling to assess this objectively, as it's not about LDAP.

It's about having a config file and not 500 options in the bootstrap of the project, it's about making the docker-compose safe, accessible and maintainable, it's about putting PR comments where they belong, it's about using .env files (the proper way to write a compose file), it's about having sensible defaults, it's about moving ramblings about mongodb CPU usage into a blog post, it's about people easily being able to try out your (probably great, I'll never know) software, it's about first impressions, it's about elegance and quality and care.

I've shown you 5 examples, but take any other popular FOSS project and you'll hit upon how to actually publish a compose file. Yours is objectively bad, by any standards except your own. The wekan homepage is just as cluttered and inaccessible for people too, by the way. You're both happy with that and that's fine, it's your project, not mine. I will just thank you for your contribution to FOSS and move onto something else. So, thanks 👍

**Comment by xet7** [comment]
@timdonovanuk 

To try Wekan with that docker-compose.yml, you just run `docker-compose up -d` and it works at localhost, without any changes. Easy enough?

**Comment by timdonovanuk** [comment]
I'm not going to blindly trust 700 lines of code on my system, even if containerized and nobody else should either :) Thanks.

**Comment by johncadengo** [comment]
@timdonovanuk I'm curious, what did you end up using if not Wekan?

**Comment by razum2um** [comment]
I'm not a maintainer, but I'm glad wekan has such a docker-compose.yml file, @xet7 thanks for that. To be honest, it could skip links to PRs (they could be in commit info), but overall I think now it's good and even aligned with a lot of others:
- new devops stuff: helm charts when example `values.yml` is as rich as possible having most stuff `enabled: false`
- old school packages like postfix (notable example of a complicated config) - if not install into default, deb packages still keep a huge ~700 lines config in `/usr/share/postfix/main.cf.dist`

**Comment by xet7** [comment]
@razum2um 

Links to PRs are very important, because usually someone is complaining if something does not work, and it needs to be fixed.

Everything in that docker-compose.yml is necessary. There is login for OAuth2/OIDC, LDAP, etc. URL to app. Connection to database. It is what is required for app to work. I have asked in some issue, can some feature be removed, answer was no, they use most features.

WeKan is Enterprise software, with FOSS MIT license. Like Jira Datacenter, pricing here:
https://www.atlassian.com/licensing/data-center#data-center-approved-apps

There is no propietary code in WeKan. Everything is Open Source. WeKan .zip file has about 60k files of Javascript etc.

Sure if having this much features is too much, better to use pen and sticky notes paper, and organize those notes.
