### ISSUE TITLE
How to resize the wekan memory？

### ISSUE THREAD

**Issue by styxlcx** [wekan/wekan#4016]
We have a PC with 8GB of RAM, win10 as the operating system, and the latest version of wekan installed on it. Now there are about 100 users. I found that this system reports memory overflow every once in a while. May I ask where wekan can be modified Memory configuration? How to modify, thank you experts!

Note: With Docker, please don't use latest tag. Only use release tags.
See https://github.com/wekan/wekan/issues/3874

If you can not login for any reason:
- https://github.com/wekan/wekan/wiki/Forgot-Password

Email settings:
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

Add these issues to elsewhere:
- SECURITY ISSUES: https://github.com/wekan/wekan/blob/master/SECURITY.md
- UCS: https://github.com/wekan/univention/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using?

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

**Comment by xet7** [comment]
For using Source install of Wekan https://github.com/wekan/wekan/wiki/Offline with Windows versions of Node.js 12.22.6 and MongoDB 4.x, try start-wekan.bat from https://github.com with some kind of option like this https://github.com/wekan/wekan/issues/3585#issuecomment-782431177 

I have not tested it, I usually run Wekan on Linux with SSD or NVME disk, there Wekan is faster.

**Comment by xet7** [comment]
Also see https://github.com/wekan/wekan/wiki/Backup
