### ISSUE TITLE
About UI changes

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4027]
Hi,
It seems Trello changed their web UI again. Now there is also left sidebar, and top dropdown menus. Left sidebar can not be completely hidden, there is still bar visible. I feel a little confused and scared with that new Trello UI. Feeling that I do not know anymore how to use Trello. There being similar options in many different Trello menus. Well, I only have couple test boards at Trello, but anyway.

I presume also Wekan users would be confused similarly, if I would change Wekan UI. Now I know how it feels, having experienced it with Trello UI changes. I have some experimental Wekan UI changes in one branch, but they do not work well enough yet.

This gives me something new to think. Thinking about what kind of UI and menu structure would make most sense.

**Comment by xet7** [comment]
I'm thinking about WeKan to have following menu structure, similar like Firefox/LibreOffice Writer/Gimp:


```
[Logo] | File | Edit | View | Bookmarks | Settings | Help | [Notifications bell icon] | [Avatar icon]

-----------------------------------------------------------------------------------------------------

File
----

New > Board
      Template

Import Board > From Trello
               From previous export
               From CSV/TSV

Export Board > To JSON
               To Excel
               To CSV
               To TSV
               To HTML

Logout

-----------------------------------------------------------------------------------------------------

Edit
----
Search One Board
Search All Boards
Filter
Multi-Selection
Move Board to Archive

-----------------------------------------------------------------------------------------------------

View
----
All Boards
Swimlanes
Lists
Calendar
Gantt
My Cards
Due Cards
Public
Templates
Boards Archive
Cards/Lists/Swimlanes Archive
Admin Panel

-----------------------------------------------------------------------------------------------------

Bookmarks
---------
Project 1
Project 2
Global Status

-----------------------------------------------------------------------------------------------------

Settings
--------
Edit Profile
Change Avatar
Change Password
Change Language
Show desktop drag handles
Show cards count
Set day of the week start
Rules
Custom Fields
Change color or theme
Outgoing Webhooks
Card Settings
Subtasks Settings

-----------------------------------------------------------------------------------------------------

Help
----
About [Product name]

-----------------------------------------------------------------------------------------------------
```

For `All Boards` page, I'm thinking about board grouping,
similar like iOS/Android grouping of app icons.

What do you all think?

**Comment by helioguardabaxo** [comment]
Hi @xet7 !

It's a great idea!
Here are some suggestions: 

[Logo] | File | Edit | View | Bookmarks | Settings | **Admin panel** | Help | [Notifications bell icon] | [Avatar icon]

-----------------------------------------------------------------------------------------------------


User/Profile
----------------
Edit Profile
Change Avatar
Change Password
Change Language
-----------------------------------------------------------------------------------------------------

Settings
-----------
Show desktop drag handles
Show cards count
Set day of the week start
Rules
Custom Fields
Change color or theme
Outgoing Webhooks
Card Settings
Subtasks Settings
-----------------------------------------------------------------------------------------------------

**Comment by xet7** [comment]
@helioguardabaxo 

Thanks! I modified menu structure above a little.

**Comment by helioguardabaxo** [comment]
If we split View menu?
View: just board view options
Workspace: all things relative to the boards that I work

Workspace
----
Admin Panel
All Boards
My Cards
Due Cards
Public Boards
Templates
Archive (Boards/Cards/Lists/Swimlanes Archive)

-----------------------------------------------------------------------------------------------------

View
-------
Swimlanes
Lists
Calendar
Gantt

-----------------------------------------------------------------------------------------------------

**Comment by xet7** [comment]
@helioguardabaxo 

Thanks! I grouped View menu.

Separate Workspace menu would take too much space away from `[Board name]`. I try to fit most details on one top menu.

**Comment by helioguardabaxo** [comment]
@xet7 
Ok!
The main idea is merge quick access bar and header just in one header?

**Comment by xet7** [comment]
@helioguardabaxo 

Yes:
- One header that takes less space
- Group options with similar options

**Comment by xet7** [comment]
I have been looking at many different software menus, combining ideas from menu structures, and thinking about less is more.

This is also how to make adding more features possible, without going too far clicking subsubsubsubmenu options.

**Comment by xet7** [comment]
This is also still work in progress, I'm still trying to improve it more. Ideas welcome.

**Comment by helioguardabaxo** [comment]
I agree that less is more.
Would My Boards remain the Home page?

**Comment by xet7** [comment]
@helioguardabaxo 

Yes, but it will be configurable, I added to plans that:
```
Bookmarks / Edit Homepage to be any Bookmark
```
I'm still thinking, maybe setting can be in Bookmarks menu. Or should it be in Settings menu.

Bookmarks are also related to Board key #2449 , so any Board key could be bookmark.

**Comment by xet7** [comment]
These simplifying changes are also related to:
- Feedback that configuring Wekan is too complex #4014
- I bought from local shop [Linux Magazine](https://www.linux-magazine.com/Issues/2021/251/Visual-Aid/(language)/eng-US) that has article about Wekan, also in that article is mention that there are so many configuration options that it's too much to cover in article in magazine. Also in that article is link to some GitHub issues I did not remember looking at in a long time.

So I also have done simplifying Wekan website https://wekan.github.io :
- Grouped install options for Docker/Snap/Sandstorm/etc so that it would be easier to figure out
- Moved links to be at more obvious locations
- Removed some duplicated info

I am also thinking about how to improve docs, or maybe adding some of those docs directly to Wekan menus.

**Comment by helioguardabaxo** [comment]
Do you thinking about in a knowledge base/helper built in?

At my company I created some tutorials to users. 
Eg.: https://nti.ufabc.edu.br/guias-praticos/kanban/kanban-2-quadros-listas-raias-e-cartoes

But I would like to have this tutorials inside Wekan.
Would be easier to users.

**Comment by xet7** [comment]
@helioguardabaxo 

Yes:
- Each menu option at right side could have `?` button that would open tutorial for that menu option
- Tutorials could be translated at https://transifex.com/wekan/wekan , similar like all other texts. If possible, drag-drop animations of tutorials could be done with code (not recorder animgif), so that it would show correctly translated for each language
- Same translated tutorials would be also available at some Wekan docs website
- All Wekan docs from https://github.com/wekan/wekan/wiki, REST API docs at https://wekan.github.io/api/ and from various issues at https://github.com/wekan/wekan/issues would be moved to tutorials inside Wekan, and translated
- Transifex translations would also be used to translate Wekan website https://wekan.github.io to all those languages
- Fix [RTL issues](https://github.com/wekan/wekan/issues?q=is%3Aissue+is%3Aopen+RTL)
- Fix [misaligment issue](https://github.com/wekan/wekan/issues/4023)
- Add feature to [change font and font size](https://github.com/wekan/wekan/issues/3086#issuecomment-629682047)

Also, pull requests welcome for any of these changes.

**Comment by xet7** [comment]
If installing Wekan is simplified enough, it could maybe be enough that all docs are inside Wekan in tutorials.

**Comment by xet7** [comment]
Currently there are very many settings that are done with environment variables for Snap/Docker/Source. Those could maybe be also added to web UI in logical places, if that does not make some use case too complex.

**Comment by xet7** [comment]
I also would like to keep all existing settings working, and automatic upgrades still working, without any changes to current settings.

**Comment by xet7** [comment]
Many Wekan features are complex with multiple steps to get them working. If anyone has ideas how they could be made simpler, show all related settings at same page, etc, all ideas welcome.

**Comment by xet7** [comment]
And can some feature be changed to have less steps?

**Comment by xet7** [comment]
BTW, there seems to be some Hacktoberfest, about it is info at https://forums.meteor.com/t/hactoberfest-2021/56755 . I have not yet figured out could those be somehow related to WeKan.

**Comment by helioguardabaxo** [comment]
About simplifying some things:
1 - "Delete card" could be put together "Copy card" and "Move card"
2 -  Reorganizes Sidebar and Board settings, using tabs in a side bar:

General
----
Organizations
Teams
Members
Labels
-----------------------------------------------------------------------------------------------------

Board Settings
----
Rules
Custom Fields
Archive
Change Color
Export board
Outgoing Webhooks
Card settings
Subtasks settings
Move board to archive
-----------------------------------------------------------------------------------------------------

Activities
-----------

**Comment by xet7** [comment]
@helioguardabaxo 

1. No. "Delete card" is in separate menu, because it's too easy to delete by accident. Currently only BoardAdmin can delete. Soon I will also add confirmation question to "Archive card".

2. Yes. Tabs at Sidebar are great.

**Comment by xet7** [comment]
Hmm. I'm just thinking, what is the point in having Sidebar? Members etc can be also added directly at card, etc:
- Sidebar size is very limited. It is better to edit those settings at full width view.
- Organizations/Teams/Members/Labels/Hide minicard label text should be at Settings. Usually there are too many members etc that they do not fit at sidebar. At full width view, viewing members would be easier, and load all members only at members view etc. At card, members etc can be added with Search.
- Board activities should be full width view. Maybe some grouping/pagination/search or something like that. Activities should be loaded with inifinite scroll only when Activities view is visible.
- Rules etc should also be full width view

**Comment by xet7** [comment]
Well, then with `Less is More` is another question if `Worse is Better`. If with all these changes it makes existing docs, workflows etc different or broken, and some people do not like change. When adding each feature and option, related corner cases and bugs have already been fixed. Currently UI and backend are very tightly coupled, so changing UI has potential to introduce bugs back.

**Comment by xet7** [comment]
When I think of some stories about people that do not like change, related to non-Wekan changes:

1. Years ago, I changed Linux distro for someone. They were very used to old distro, and did not like it.
2. For someone, I changed phone, because old one is broken. That person now would not like to change to other phone, because it did take time to learn all that current phone UI.
3. Some have many years used Linux Mint UI, that has stayed mostly the same. They would not like to change.
4. Some got very angry when newer version of Windows had different UI, or required different hardware. They preferred old familiar one.

Current positive stories about Wekan:

1. Some are thanking that updates to Wekan have continued for many years.
2. Some are thanking how well received current Wekan is by their users, and have ordered some specific feature or fix.
3. Some have replied that they would not like to fund Wekan rewrite.
4. Some seem to have urgent need to have ordered paid feature/fix very soon.

I think I would need more feedback before making changes to something in Wekan that already works.

**Comment by xet7** [comment]
Also, moving some current top bar buttons to dropdown menu would add additional clicks.

But I don't know. I would need more feedback.

**Comment by xet7** [comment]
For example, when I did read from Gambas mailing list that someone is porting software from VB6 to Gambas because customers don't want Windows on factory floor anymore, when porting, they are making about same looking UI with Gambas that already existed in VB6 app, and only changing some basic syntax etc where there are differences.

So I would think, that if I sometime would have time to change some non-visible frontend/backend code in Wekan, I would probably need to keep visible UI code kind of same.

But now I feel stupid, here just arguing with myself.

**Comment by helioguardabaxo** [comment]
Human being is resistant for changes but pandemic showed that its able to adapt speedily.
Particularity, I like Linux Mint with Cinnamon but I want to change to Pop OS because its modern design and keyboard usage on operation, similar to i3.

It's very important to do a soliloquy! It's not stupid and been part of conscious evolution.

**Comment by helioguardabaxo** [comment]
What do you think to do a short and specific survey to UI/UX? 
The last survey(june 2020) has few points/answers about UI.

**Comment by xet7** [comment]
@helioguardabaxo 

Thanks! That last survey (june 2020) is still valid for many points. It seems many would like to have WeKan UI/UX simpler, and custom everything. It's kind of what I already started doing with prototypes, I just should continue developing those prototypes, and maybe just replace everything at once, to have maximum effect ;)

**Comment by Meeques** [comment]
Hi, just a disclaimer: I didnt read every comment in this section throughoutly but I wanted to add my opinion on displaying settings in full width. I think this is very unnessesary and would just add confusion because you have to scan your whole monitor to get the info/setting/option you need. I think a Pop Up window would be best for clear and quick changes in settings. Or at least something that doesn't hit you all over

**Comment by xet7** [comment]
@Meeques 

Thanks a lot ! So I think I will keep current UI.
