### ISSUE TITLE
[Bug] Moving cards manually (drag and drop) from a swimlane to another is frequently difficult

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#4032]
## Issue
Moving cards manually (drag and drop) from a swimlane to another is frequently difficult
See video :
https://user-images.githubusercontent.com/74183327/136057325-750ddf99-d68a-41c8-8247-e4795064db15.mp4

N.B.:
- It does appear all the time, but unfortunately very often (many times a day)
- Almost all our boards (>10) have the issue.
- It "seems" it appears on cards with many elements displayed (date, assignee,custom fields...)
- It "seems" it appears on boards with lot of cards and history
- When I reproduced for the video, the performance of wekan was correct, and I was the only one connected to the board
- On other boards it appears also when moving from a list to another list in the same swimlane

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4883
