### ISSUE TITLE
[Bug] Sum fields is not displayed at the top of the list

### ISSUE THREAD

**Issue by marcungeschikts** [wekan/wekan#4034]
## Issue
To reproduce:
- create a custom filed with type number
- select " show sum of fields at top of list" in the definition of the field
- Add value for this customfield in some cards
=> The label of the field is displayed in top of the list, but not the sum
See screenshot:
![image](https://user-images.githubusercontent.com/74183327/136061204-ffac29e3-c563-4991-bd14-d706e5bb2d00.png)

**Comment by xet7** [comment]
That feature is still in progress, I will add that counted number in near future to some new Wekan release. That feature is not ready yet.

Moved to #3796

**Comment by marcungeschikts** [comment]
👌🏻
