### ISSUE TITLE
Attachment upload progress indicator

### ISSUE THREAD

**Issue by luis-pato** [wekan/wekan#4038]
Very often when we add an attachment to a card it doesn't quite work.

For instance when i add an image as an attachement it seems that it is uploading the image, but nothing happens:
![image](https://user-images.githubusercontent.com/42058106/136334913-060e683d-f723-44a1-b4cf-1e36059de418.png)
(2nd image is "empty", when we click on it it open the lightbox but shows only the spinner and no image)

I think it would be great to have some kind of notification or visual signal that the upload has started, is in progress and has finished (either with success or error)

**Comment by xet7** [comment]
I think this already exists on newest WeKan.
