### ISSUE TITLE
Since version v5.61 normal wekan users are not able to perform actions via REST API anymore

### ISSUE THREAD

**Issue by bastianwenske** [wekan/wekan#4039]
## Issue
Before version v5.61 "normal" wekan users which had the permission (user, admin etc.) to a specific board were able to use the REST API. Within commit e3a0dea85fa1f8e2f580f419b30cf5f36775d731 this feature was removed so from v5.61 "normal" users with sufficient privilegies are not able anymore to perform actions via REST API to granted boards.

**Server Setup Information**:
Did you test in newest Wekan?: yes (latest version v5.63)
Wekan version: Problem occurs since version v5.61
Plattform: RedHat Openshift 4 with official wekan docker image. 

**Problem description**:
General:
* The permissions of the user do not has changed.
* The used Bearer token is valid.

Before Version v5.61:
`GET https://$URL$/api/boards/ZsE9TMREJnZmkfTWm`
```{
  "_id": "ZsE9TMREJnZmkfTWm",
  "archived": false,
  "color": "modern",
  "createdAt": "2021-10-06T09:14:59.333Z",
  "labels": [
    {
      "_id": "72jGMY",
      "color": "green",
      "name": "Change"
    },
....
```

Since Version v5.61:
`GET https://$URL$/api/boards/ZsE9TMREJnZmkfTWm`
```
{
  "isClientSafe": true,
  "error": "Forbidden",
  "reason": "Forbidden",
  "message": "Forbidden [Forbidden]",
  "errorType": "Meteor.Error",
  "statusCode": 403
}
```

**Comment by xet7** [comment]
@Meridiana 

I'm also trying to figure out how to add ical feeds directly to Wekan, so that it would not need some Python/PHP/Java ical server.

**Comment by ThomasSchoeller** [comment]
@xet7 this is a major issue for us. what can we do to get "non admin api access" back?
How much does it take to fund development on this issue?

**Comment by xet7** [comment]
@ThomasSchoeller 

500 euro. https://wekan.team/commercial-support/

**Comment by xet7** [comment]
This has been funded and added to [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-r-open-source-kanban-board-with-mit-license/FFzJDL3Bd3kccj8GE). I'm looking at how to fix this.

**Comment by Meeques** [comment]
@xet7 was there any payment until now?

**Comment by xet7** [comment]
@Meeques 

This feature has been paid and will come to WeKan.

**Comment by Meeques** [comment]
@xet7 
Are you currently also looking at how to turn off the 'forgot my password' option?
