### ISSUE TITLE
Attachment support

### ISSUE THREAD

**Issue by ovidiub13** [wekan/wekan#404]
A functionality of Trello that I use a lot is adding attachments. Can you please add this in your RoadMap?
http://try.wekan.io/b/MeSsFJaSqeuo9M6bs/wekan-roadmap

**Comment by xavierpriour** [comment]
Attachments are already implemented in Wekan at the card level.

**Comment by ovidiub13** [comment]
Just saw that. Although deleting them doesn't work.

**Comment by batjko** [comment]
Not to bud in on a closed ticket, but is it correct that there is no attachment button on the card (i.e. I always have to go the card's menu and select "Edit attachments"?
