### ISSUE TITLE
enhancement: board overall look.

### ISSUE THREAD

**Issue by luistiktok** [wekan/wekan#4041]
Be able to add picture background and the overall look of those kanban boards
[https://plankanban.github.io/planka/#/boards/207391868235809799](https://plankanban.github.io/planka/#/boards/207391868235809799)

Thank you

**Comment by xet7** [comment]
@luistiktok 

> the overall look of those kanban boards

Can you please add more details about what do you mean specifically? It looks like for me mostly, that Planka is missing many features Wekan already has.

Background image is another issue #486

**Comment by avatar1024** [comment]
@xet7 Wekan is definitely more feature rich than Planka

However I would like to add to this original post and be more specific as to what I think is good about Planka's **design** and which I miss on Wekan.

1. a cleaner, less cluttered, card details layout: In Wekan, all field are listed in a single column and are there whether or not they are filled (I know you can remove fields entirely in the card settings but it might still be useful to have certain field available even if not used in every card). In Planka, only three field are visible in the main pane (description, task, comments) but then you can add more field from afield list in the right hand side of the pane. This keeps the cards less cluttered an only show info which are being used.
![Wekan_card_layout](https://user-images.githubusercontent.com/18719956/161537959-306bedcb-e497-49b8-8d0c-2457685a8725.png)
![Planka_card_layout](https://user-images.githubusercontent.com/18719956/161537976-ed1a739b-8923-49ac-a6e8-243a2e96b1a1.png)

2. In Planka you can see progress on task from inside the card details but also from the main board view which is pretty nice!
![Planka task progression details](https://user-images.githubusercontent.com/18719956/161538022-d0190262-f75a-4952-8c56-c9b1a0c1d883.png)
![Planka task progression main board view](https://user-images.githubusercontent.com/18719956/161538039-95081911-029a-4b00-97c4-b025326a8575.png)

More minor points from then on:
3. Animation i
![planka card animation](https://user-images.githubusercontent.com/18719956/161539134-6649e62b-75ec-43f9-9ba5-895dae98dabc.gif)
n moving cards is smoother and nicer in Planka with more of a gliding effect (it is even better in real than in the gif)


4. The overall look of the board feels more modern with lists being separated / spaced and contrasted from the background image (I know you are working on the background image already).

Hope this is useful

**Comment by avatar1024** [comment]
@mfilser Oh yes, you are right, I hadn't spotted that. However it does not appear on the main board view as it does in Planka which I find very helpful.

**Comment by xet7** [comment]
There are existing features about showing/hiding something at card or minicard. Someone can look at existing code and add more to show/hide.

**Comment by avatar1024** [comment]
@xet7 thanks for the reply. Any suggestion regarding point 1? It is often that we ended up with cards that have a many empty fields which clutter the view. The solution in Planka would prevent that. Currently in wekan we can only show/hide fields (using Board Settings > Card Settings) that applies to every cards on a board. But if I want to add attachments to some cards I need the attachment field, yet most cards (those without an attachment) will unnecessary show an empty attachment field.

It feels like the fields we can select in Board Settings > Card Settings should be the fields which are available to select (but not always displayed) within a card (what is in the right hand side of the card view in Planka). Could even add a setting a choose which field are by default visible (in Planka these are Description, Tasks, Comments). I believe this will greatly improve visibility in Wekan.

![Planka_card_design](https://user-images.githubusercontent.com/18719956/161720708-2bb3165a-2eb0-413d-9098-104424a4588d.png)

**Comment by mfilser** [comment]
@avatar1024 
It's a idea, but i guess as soon as it's developed in Wekan here are 10 more issues that's it's very time consuming to fill out all fields.
Every Tool has it's own life, i am not sure if we should develop Planka 2. The next one requests to develop Trello 2, and the next one Padlet 2.
Don't understand me wrong, i appreciate idea's and they are useful, but at some point, Wekan can't subtitute every Kanban Tool in the world. That's only my opinion, i am open for other contributions and of course of the excellent work of @xet7 and he's decision.

**Comment by avatar1024** [comment]
@mfilser Thanks for your input and I fully agree with you, we shouldn't try to develop a clone of another app. Wekan is its own (very good) thing. However I also believe it makes sense to get inspired from what is being (well) down elsewhere and see if it can improve our own software. The suggestion here are not about changing Wekan functionalities or workflow, but are about changing (in my view improving) the design layout without impacting workflow.

> It's a idea, but i guess as soon as it's developed in Wekan here are 10 more issues that's it's very time consuming to fill out all fields.

Here I'm not sure I follow what you mean, how is that more time consuming? We already have to click to add say a Due Date, the difference here is that you'd click on on the right hand side button. As a result the Due Date field by default would not take any space in on the left hand side (where the info about the card are) until a due date is actually added. Maybe I am missing something though?

Also as I mentioned here:
> Could even add a setting a choose which field are by default visible (in Planka these are Description, Tasks, Comments).

we could also add in Card Settings a way let you choose which field is visible by default on every card. In Card Settings we could have something like:
List of field and then two columns with tick boxes "Available on card" and "Displayed on Card"

But I'm also opened to being told wrong here and hear what others have to say. Also this comes from feedback from people in my organisation using Wekan, it did not bother me particularly as I'm not put off by clutter that much and I'm a bit dated so used to old interfaces. But when people pointed that out to me it felt like they had a good point, and by looking at other implementations, especially Planka, the presentation of card info did feel a lot clearer (even to me :)).

**Comment by xet7** [comment]
@avatar1024 

Having only those card details fields visible, where is some content, is possible to implement by having some if statement about existing content somewhere here:
https://github.com/wekan/wekan/blob/master/client/components/cards/cardDetails.jade#L82

Card details Javascript code is here:
https://github.com/wekan/wekan/blob/master/client/components/cards/cardDetails.js

Testing changes and sending PR can be made like this:
https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

Pull requests welcome. Thanks!

**Comment by avatar1024** [comment]
@xet7 Thanks a lot for pointing to the relevant places for this. I sadly don't have much developer skills currently but I could try in the future and anyone else who might be interested might have a look to.

**Comment by xet7** [comment]
It seems Planka changed license from MIT https://github.com/KanRule/planka to AGPL-3.0 https://github.com/plankanban/planka

WeKan stays MIT. I discontinued WeKan GPL version and will add MIT licensed Gantt https://github.com/wekan/wekan/issues/2870#issuecomment-1516992963
