### ISSUE TITLE
Mail Setup not working in Docker

### ISSUE THREAD

**Issue by danst0** [wekan/wekan#4046]
## Issue
I cannot get mail setup in my Wekan Docker container.
I am using tag v5.62

This is my mail_url
MAIL_URL=smtps://admin%40domain.me:password_w_only_small_caps_and_dash@mail.server.de:587/

This is the error message:

(node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:587,
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16),
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What am I doing wrong?

Daniel

**Comment by xet7** [comment]
Please upgrade to Wekan v5.64
