### ISSUE TITLE
Restore a database which was taken from wekan installed from source , to a version of wekan installed with snap

### ISSUE THREAD

**Issue by petkodimitrov1986** [wekan/wekan#4106]
Hello, 
We have an old version 5.17 of wekan, which was installed manually from source.  I have installed wekan with snap and I want to  restore the database which I have backed up earlier from the installed from source version using mongodump.  I have completed the install of snap wekan and tried to restore with mongorestore , which should have taken the backup from /bin/dump. 

```
petko@Ubuntu:~$ mongo
MongoDB shell version v3.6.8
connecting to: mongodb://127.0.0.1:27017
WARNING: No implicit session: Logical Sessions are only supported on server versions 3.6 and greater.
Implicit session: dummy session
MongoDB server version: 3.2.22
WARNING: shell and server versions do not match
Server has startup warnings: 
2021-10-29T19:33:25.826+0300 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2021-10-29T19:33:25.826+0300 I CONTROL  [initandlisten] 
>show dbs
local  0.000GB
wekan  0.001GB
> use wekan
switched to db wekan
petko@Ubuntu:~$ mongorestore --drop --port 27017 --db wekan
2021-10-29T19:39:53.464+0300	the --db and --collection args should only be used when restoring from a BSON file. Other uses are deprecated and will not exist in the future; use --nsInclude instead
2021-10-29T19:39:53.464+0300	using default 'dump' directory
2021-10-29T19:39:53.464+0300	see mongorestore --help for usage information
2021-10-29T19:39:53.464+0300	Failed: mongorestore target 'dump' invalid: stat dump: no such file or directory
```

Please help me restore a database which was taken from wekan installed from source , to a version of wekan installed with snap. Thank you.

**Comment by xet7** [comment]
You have not made backup yet with `mongodump`, so subdirectory `dump` does not exists. I recommend you make backup first, and copy `dump` directory content to somewhere safe, before trying any kind of restore.

You are trying to restore from non-existing `dump` directory to overwrite your MongoDB database that has not been backed up yet.

**Comment by petkodimitrov1986** [comment]
In production , I have baked up the db uisng mongodump , here is the content of /bin/dump:

```
/bin/dump# cd wekan
root@kreider:/bin/dump/wekan# ls
accountSettings.bson                       cards.metadata.json                          checklists.bson                 meteor_accounts_loginServiceConfiguration.bson           sessiondata.metadata.json
accountSettings.metadata.json              cfs.attachments.filerecord.bson              checklists.metadata.json        meteor_accounts_loginServiceConfiguration.metadata.json  settings.bson
AccountsLockout.Connections.bson           cfs.attachments.filerecord.metadata.json     cronHistory.bson                meteor-migrations.bson                                   settings.metadata.json
AccountsLockout.Connections.metadata.json  cfs_gridfs.attachments.chunks.bson           cronHistory.metadata.json       meteor-migrations.metadata.json                          swimlanes.bson
actions.bson                               cfs_gridfs.attachments.chunks.metadata.json  customFields.bson               meteor_oauth_pendingCredentials.bson                     swimlanes.metadata.json
actions.metadata.json                      cfs_gridfs.attachments.files.bson            customFields.metadata.json      meteor_oauth_pendingCredentials.metadata.json            team.bson
activities.bson                            cfs_gridfs.attachments.files.metadata.json   dump                            org.bson                                                 team.metadata.json
activities.metadata.json                   cfs_gridfs._tempstore.chunks.bson            esCounts.bson                   org.metadata.json                                        triggers.bson
announcements.bson                         cfs_gridfs._tempstore.chunks.metadata.json   esCounts.metadata.json          orgUser.bson                                             triggers.metadata.json
announcements.metadata.json                cfs_gridfs._tempstore.files.bson             integrations.bson               orgUser.metadata.json                                    unsaved-edits.bson
boards.bson                                cfs_gridfs._tempstore.files.metadata.json    integrations.metadata.json      presences.bson                                           unsaved-edits.metadata.json
boards.metadata.json                       cfs._tempstore.chunks.bson                   invitation_codes.bson           presences.metadata.json                                  users.bson
card_comments.bson                         cfs._tempstore.chunks.metadata.json          invitation_codes.metadata.json  rules.bson                                               users.metadata.json
card_comments.metadata.json                checklistItems.bson                          lists.bson                      rules.metadata.json
cards.bson                                 checklistItems.metadata.json                 lists.metadata.json             sessiondata.bson
```
I have created the folder /bin/dump in my test side  where I have installed wekan with snap , copied the content from the prod /bin/dump with the backup , so in my test side I have /bin/dump/wekan with the same content as the prod folder.
Then I did this on my test side:
` petko@Ubuntu-NEW:/$ mongorestore --maintainInsertionOrder -h 127.0.0.1 --port 27019 -d wekan /bin/dump/wekan`
and now I have all the boards and all the permissions same as the production side, all the activities within the boards are there , but the content of the boards is empty. Which file contains the cards for the individual boards please ?

**Comment by petkodimitrov1986** [comment]
Thank you very much for your help! Really appreciate your time. Everything looks ok ,I have all the boards , all the cards , permissions , comments , activities. Now the only thing left is to uninstall the legacy version in prod, installed from source, then do a fresh install on the same server with snap and import the database using the command `mongorestore --maintainInsertionOrder -h 127.0.0.1 --port 27019 -d wekan /bin/dump/wekan` . Do you have by any chance a procedure for clean uninstall please ? And again , thank you.

**Comment by xet7** [comment]
@petkodimitrov1986 

## 1) Old Wekan source directory

1. Backup those settings from `start-wekan.sh` for root-url etc
2. Delete old wekan source directory: `rm -rf wekan`

## 2) Biggest directories

To see biggest directories, you can install ncdu:
```
sudo apt -y install ncdu

sudo su

cd /

ncdu
```
When ncdu has calculated subdirectory sizes, move with arrow keys and enter to subdirectories, to see which one are biggest.

## 3) Disable old MongoDB

You could stop and disable old mongodb, it is service mongodb or mongod, so it is not running anymore, and does not take any RAM and CPU time anymore:
```
sudo systemctl stop mongodb

sudo systemctl stop mongod

sudo systemctl disable mongodb

sudo systemctl disable mongod
```
## 3) Remove old MongoDB

It is package mongodb-org, or mongodb-server mongodb-clients mongodb-tools:
```
sudo apt --purge remove mongodb-org mongodb-server mongodb-clients mongo-tools

sudo apt clean

sudo apt -y autoclean

sudo apt -y autoremove
```

Delete all old MongoDB database raw data:
```
sudo rm -rf /var/lib/mongodb
```

## Nodejs: removing not recommended

If at your server nodejs is not in use for anything else, and you really need more disk space, maybe it can be removed, but there is potential to mess up something and get famous semver errors. There is some docs page about directories to be removed etc, but I did not find it yet. 

## Using Snap commands for mongodump, mongorestore etc

For backups etc, you can use mongodump etc commands that are included in snap:
https://github.com/wekan/wekan/wiki/Backup#backup-wekan-snap-to-directory-dump

Snap includes all of Wekan: nodejs, mongodb server, mongodump, mongorestore etc, usually there is no need to have those separately installed. Automatic Snap updates updates all included software.

## About file locations in Wekan snap

Depending on Wekan snap used, raw mongodb database files are in some of these directories. It's better to use mongodump to backup, and not backup raw database files. Wekan code is sandboxed in snap, code back not write outside of these directories.
```
/var/snap/wekan/common

/var/snap/wekan-gantt-gpl/common
```
Wekan Javascript etc code is write protected in these directories:
```
/snap/wekan

/snap/wekan-gantt-gpl
```
## Seeing current Snap settings
```
sudo snap get wekan > snap-get-wekan-settings.txt
```
Then settings can be seen in textfile.

**Comment by petkodimitrov1986** [comment]
Thank you very much. Is there a documentation how to configure certificates after a fresh wekan installation with snap please ?

**Comment by xet7** [comment]
@petkodimitrov1986 

Yes, at Snap installation page and at wiki.

**Comment by petkodimitrov1986** [comment]
hello, I have installed wekan with snap in production successfully with the documentation in github, but I cant access the web ui. Please let me know what I am doing wrong ?
When I open a browser and I try to open server ip and port 3001 , I get connection refused

```
sudo ss -tunelp | grep 3001
tcp     LISTEN   0        128              0.0.0.0:3001           0.0.0.0:*      users:(("node",pid=7669,fd=24)) ino:41699 sk:5 <->


systemctl status  snap.wekan.wekan
● snap.wekan.wekan.service - Service for snap application wekan.wekan
   Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-11-03 09:02:53 EET; 20s ago
 Main PID: 6879 (wekan-control)
    Tasks: 12 (limit: 2252)
   Memory: 143.8M
   CGroup: /system.slice/snap.wekan.wekan.service
           ├─6879 /bin/bash /snap/wekan/1798/bin/wekan-control
           └─7669 /snap/wekan/1798/bin/node main.js

nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:27019         0.0.0.0:*               LISTEN      2449/mongod

```

**Comment by petkodimitrov1986** [comment]
Hello ,
I managed to install wekan with snap. Wekan was using the old (default) DB even after I restored using `mongorestore --maintainInsertionOrder -h 127.0.0.1 --port 27019 -d wekan /bin/dump/wekan`

Then I connected using the mongo command, and found my restored DB, wekan:

```
> show dbs
local  0.000GB
wekan  0.004GB
```

Then I attempted to set the right DB used using the command: 

snap set wekan mongo-url='mongodb://127.0.0.1:27019/wekan'

Then I restarted the mongo service, and it failed. 

```
mongo --port 27019
MongoDB shell version: 3.2.22
connecting to: 127.0.0.1:27019/test
2021-11-03T12:53:48.014+0200 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27019, in(checking socket for error after poll), reason: errno:111 Connection refused
2021-11-03T12:53:48.014+0200 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27019, connection attempt failed :
connect@src/mongo/shell/mongo.js:231:14
@(connect):1:6

exception: connect failed
```

Please let me know what should I do next to resolve this? Thank you.
