### ISSUE TITLE
Copy large Wekan board fails, retries, fails, retries, etc.

### ISSUE THREAD

**Issue by ChrisMagnuson** [wekan/wekan#4111]
On the My Boards screen I accidentally clicked the copy icon on a board that has a ton of cards, checklists, archived, cards etc.

I have increased the memory available to the wekan cointainer and to the mongodb container that it connects to in the hopes that I could give it enough resources to complete but the process keeps failing and retrying.

I now show 9 other copies of the board and every time I restart the container or wait for a while the process will fail and then try again creating yet another copy that it never finishes creating.

Is there a collection in the mongodb that stores these pending operations, like this copy board operation, that I could manually edit to delete the record so that I can restart things and at least not have it try to make a copy again?

**Comment by ChrisMagnuson** [comment]
I have tracked the path that executes this code through the following:

https://github.com/wekan/wekan/blob/df26bc9013489a7cf3a6605df207b64a794ceaee/client/components/boards/boardsList.jade#L77
https://github.com/wekan/wekan/blob/d39e8bc03a7dbb6bde60250dd485c63275c895d6/client/components/boards/boardsList.js#L223
https://github.com/wekan/wekan/blob/508c7b7a904f6402307a0669afb5eb38d12e6328/models/boards.js#L561

Based on some other googling the Meteor.call [here](https://github.com/wekan/wekan/blob/d39e8bc03a7dbb6bde60250dd485c63275c895d6/client/components/boards/boardsList.js#L224) is being handled by Meteor's code and the retry logic if the method doesn't complete may be client side.

I have closed the browser that I had open and rebooted the computer where I clicked this button and will wait to see if this stops the board from continuing to be duplicated, I am currently up to 20 copies of the board.

**Comment by xet7** [comment]
Try clear browser cache

**Comment by ChrisMagnuson** [comment]
By using `chrome://settings/siteData` to clear the browser cache for our wekan site I was then able to access the site again without the duplicate operation retrying.

After that I was able to archive each of the partially created duplicate boards and then access the archive and permanently delete the boards.
