### ISSUE TITLE
Problems Integration with API 5.72.0

### ISSUE THREAD

**Issue by darwinbar** [wekan/wekan#4114]
Dear, good morning.

We are finishing an integration of a tool with the API of your Wekan, the same adjustment to version 5.72.0.
Before to link with a board it was enough to authenticate as a user as "local administrator of the board", now that stopped working and only allows us to link with a board being "super administrator" and it is also associated with the board that we want to link.

Is there something that has changed or any parameter that we can touch to link to a board with a "local administrator" user on a board?

Thanks
Greetings
Darwin.

**Comment by xet7** [comment]
Moved to #4039
