### ISSUE TITLE
Mongo Oplog Settings in Docker Compose

### ISSUE THREAD

**Issue by johncadengo** [wekan/wekan#4120]
From the docker compose file [here](https://github.com/wekan/wekan/blob/master/docker-compose.yml):

```
# ==== OPTIONAL: MONGO OPLOG SETTINGS =====
      # https://github.com/wekan/wekan-mongodb/issues/2#issuecomment-378343587
      # We've fixed our CPU usage problem today with an environment
      # change around Wekan. I wasn't aware during implementation
      # that if you're using more than 1 instance of Wekan
      # (or any MeteorJS based tool) you're supposed to set
      # MONGO_OPLOG_URL as an environment variable.
      # Without setting it, Meteor will perform a poll-and-diff
      # update of it's dataset. With it, Meteor will update from
      # the OPLOG. See here
      #   https://blog.meteor.com/tuning-meteor-mongo-livedata-for-scalability-13fe9deb8908
      # After setting
      # MONGO_OPLOG_URL=mongodb://<username>:<password>@<mongoDbURL>/local?authSource=admin&replicaSet=rsWekan
      # the CPU usage for all Wekan instances dropped to an average
      # of less than 10% with only occasional spikes to high usage
      # (I guess when someone is doing a lot of work)
      # - MONGO_OPLOG_URL=mongodb://<username>:<password>@<mongoDbURL>/local?authSource=admin&replicaSet=rsWekan
```

Where do we find these variables: `username`, `password`, and `mongoDbURL`? I don't see them anywhere in the docker compose file or any documentation about how to obtain them.

**Comment by xet7** [comment]
@johncadengo 

Wekan database does not have username and password, so URL could be `mongodb://127.0.0.1:27017/wekan` or `mongodb://127.0.0.1:27019/wekan`. Sure you could read MongoDB docs how to add username and password to MongoDB.

You could look related oplog info from RocketChat docs, because RocketChat usually sets up oplog to it's MongoDB by default.

**Comment by xet7** [comment]
Maybe related https://github.com/RocketChat/Rocket.Chat/issues/14353
