### ISSUE TITLE
[Question] Is there a way to apply themes to the main Wekan site?

### ISSUE THREAD

**Issue by alxpettit** [wekan/wekan#4121]
I actually quite like the 'ModernDark' theme, but every time I go to my main Wekan page, this theme is reverted. Is there a way around this?

**Comment by xet7** [comment]
@alxpettit 

Theme changing feature is currently per-board feature. Nobody has yet added theme changing feature to `All Boards` or other pages as pull request.

**Comment by alxpettit** [comment]
The themes are just CSS being applied per user settings -- would applying the same CSS to the main page work?

**Comment by huma2000** [comment]
Just an idea but maybe the easiest way to add something like that will be adding the ability to add custom CSS to the page, I know that can break things easily but will allow for theming without having to add them to the source code

**Comment by xet7** [comment]
@huma2000 

Adding easy way to break WeKan is not the solution.

Correct solution to this issue would be to add ability to apply themes globally.

**Comment by xet7** [comment]
Moved to #486
