### ISSUE TITLE
Global search: new Card Detail Pop-Up not loading correctly and layout issues

### ISSUE THREAD

**Issue by ClaudiaK21** [wekan/wekan#4129]
Wekan version: current
Operating System: Debian 10
Deployment Method: snap
Http frontend if any: apache
Node Version: snap
MongoDB Version: snap
What webbrowser version are you using? FF 94

1 When I click on a card now in the global search result list the popup looks like this:

![grafik](https://user-images.githubusercontent.com/79307821/140962596-f6141cc9-c2fe-4931-94c3-318789b48a60.png)

And the popup is 
2. not right size it is too narrow
3. and is not moving with the card its position is fixed, you must make sure to position the card you wish to see at top of the list.
   If you click a card far below, you might even cannot see the pop up content at all

**Comment by mfilser** [comment]
@ClaudiaK21 
I am working on this already, i realized it a few days ago on my boards :grin:

**Comment by mfilser** [comment]
@ClaudiaK21 
Thank you for the info :slightly_smiling_face:

**Comment by ClaudiaK21** [comment]
@mfilser 
Thanks for correcting, but the width of the poop-up card is still too small.
It should has at least the same width as the result list items.

**Comment by mfilser** [comment]
@ClaudiaK21
I just made the fix that all card details are loaded. **Resizing the popup is a completly new feature/issue.** I have it already on my todo list, some day i have i look at it.

**Comment by ClaudiaK21** [comment]
> I wonder, may there is a misunderstanding - I don't wanna resize it, but the **default** width, which you might have set somewhere, is too small, so the card details are very long, squzeezed, not easy to read. I look forward, but I hope "one day" is still in the near future ;-)
![grafik](https://user-images.githubusercontent.com/79307821/143039484-c70366ee-8a60-4c8e-9e28-74d0f34d0a92.png)

**Comment by mfilser** [comment]
I understood it already. In the code there's a general function for popup's, and there's a fixed width. I just used that general function to not "invent the wheel" again.
