### ISSUE TITLE
How to "Mark all as read" for notifications

### ISSUE THREAD

**Issue by johncadengo** [wekan/wekan#4133]
I have over 5,000 notifications that are unread. When I click the bell at the top right of the screen, it has trouble loading and the webpage becomes unresponsive. As a result, when I try to click "Mark all as read" the command doesn't register. Is there a way to accomplish this via REST API or command line?

**Comment by xet7** [comment]
@johncadengo 

Maybe look at database? https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui

**Comment by xet7** [comment]
Moved to #2026
