### ISSUE TITLE
ERROR: for wekan-db  Cannot start service wekandb: OCI runtime create failed: container_linux.go:380

### ISSUE THREAD

**Issue by qiutian00** [wekan/wekan#4136]
Run `docker-compose up -d --build` command, show this error:

![image](https://user-images.githubusercontent.com/24382500/141305446-cb92f74e-32fd-4ed3-b36b-767f62ef6198.png)
![image](https://user-images.githubusercontent.com/24382500/141305783-bf622d8a-dff1-417a-b66f-d4e94e88fdff.png)

Is there some issues with docker or wekan ?

**Comment by xet7** [comment]
@qiutian00 

a) Use prebuilt docker image:

```
docker-compose up -d
```

b) Or build docker image:

Clone repo:
```
git clone https://github.com/wekan/wekan

cd wekan
```
Uncomment these lines: https://github.com/wekan/wekan/blob/master/docker-compose.yml#L136-L138
```
    build:
      context: .
      dockerfile: Dockerfile
```
Then build:
```
docker-compose up -d --build
```

**Comment by xet7** [comment]
Alternative:
```
git clone https://github.com/wekan/wekan

cd wekan

docker build .

docker tag 12345 wekan-app
```
Where 12345 is ID of that docker image you built. Then use that tag or ID in your docker-compose.yml .

**Comment by qiutian00** [comment]
@xet7 Thanks.

**Comment by qiutian00** [comment]
> @qiutian00
> 
> a) Use prebuilt docker image:
> 
> ```
> docker-compose up -d
> ```
> 
> b) Or build docker image:
> 
> Clone repo:
> 
> ```
> git clone https://github.com/wekan/wekan
> 
> cd wekan
> ```
> 
> Uncomment these lines: https://github.com/wekan/wekan/blob/master/docker-compose.yml#L136-L138
> 
> ```
>     build:
>       context: .
>       dockerfile: Dockerfile
> ```
> 
> Then build:
> 
> ```
> docker-compose up -d --build
> ```

But alert this problem, I had try many times.

gosu wekan:wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build
/home/wekan/.meteor/packages/meteor-tool/.2.2.0.s4egaw.utiam++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:553:9)
    at Object.execFile (child_process.js:237:17)
    at /tools/isobuild/meteor-npm.js:901:32
    at new Promise (<anonymous>)
    at /tools/isobuild/meteor-npm.js:900:12

**Comment by xet7** [comment]
@qiutian00 

ENOMEM could mean that your computer does not have enough free RAM available.

Using prebuilt image and building image like this https://github.com/wekan/wekan/issues/4136#issuecomment-966336860 works for me on Linux Mint Mate 64bit.

**Comment by qiutian00** [comment]
@xet7 , Thank you for your reply ,  I try it on my other mac computer.
