### ISSUE TITLE
"Must be logged in" when attempting to reset password

### ISSUE THREAD

**Issue by ptvirgo** [wekan/wekan#414]
Cool demo site.  Forgot my password, requested a new one via the e-mail link.  The e-mail arrived, when I browsed to the included link I was redirected to the sign in page with the error "Must be logged in."

Bit of a catch-22.

**Comment by mquandalle** [comment]
Should be fixed by e551d06 which will be released [in the upcoming v0.10](https://github.com/wekan/wekan/issues/425).
