### ISSUE TITLE
Snap backup script doesn't work, mongodump missing required files

### ISSUE THREAD

**Issue by tromlet** [wekan/wekan#4141]
## Issue

The WeKan backup script [from this page](https://github.com/wekan/wekan/wiki/Backup) for snaps doesn't work on CentOS 7 - I get the following error (bearing in mind I had to change :

`/var/lib/snapd/snap/wekan/1724/bin/mongodump: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

### Server Setup Information:

| Server Setup Query | Server Setup Response |
|---|---|
| **Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:** | Yes |
| **Did you test in newest Wekan?:** | Yes |
| **For new Wekan install, did you configure root-url correctly so Wekan cards open correctly `https://github.com/wekan/wekan/wiki/Settings` ?** | n/a - not new WeKan install |
| **Operating System:** | CentOS 7 |
| **Deployment Method(Snap/Docker/Sandstorm/bundle/source):** | Snap |
| **Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):** | Caddy |
| **Node.js Version:** | Whichever came with the snap |
| **MongoDB Version:** | Whichever came with the snap |
| **Wekan works on newest desktop and mobile webbrowsers that support Javascript. What webbrowser version are you using?** | Firefox 93 |

### Problem description:

I can't really add an animated gif, but I run this script:

```bash
!/bin/bash

makeDump()
{
    # Backups will be created below this directory.
    backupdir="/root/wekan-backup"

    # Delete old backups
    rm -rf $backupdir/*

    # Gets the version of the snap.
    version=$(snap list | grep wekan | awk -F ' ' '{print $3}')

    # Gets current time to variable "now"
    now=$(date +'%Y-%m-%d_%H.%M.%S')

    # Creates new backup directory like BACKUPDIR/BACKUPVERSIO-TIMENOW
    mkdir -p $backupdir/$version-$now

    # Targets the dump file.
    dump=$"/var/lib/snapd/snap/wekan/$version/bin/mongodump"

    # Changes to backup directory
    cd $backupdir/$version-$now

    # Backup Caddy settings
    snap get wekan > snap-settings.txt

    # Show text that database backup is in progress
    printf "\nThe database backup is in progress.\n\n"

    # Backup to current directory, creates subdirectory called "dump"
    # with database dump files
    $dump --port 27019

    # Change diretory (=cd) to parent directory
    cd ..

    # Show text "Makes the tar.gz archive file"
    printf "\nMakes the tar.gz archive file.\n"

    # Creates tar.gz archive file. This works similarly like creating .zip file.
    tar -zcvf wekan.tar.gz $version-$now

    # Delete temporary files that have already been
    # compressed to above tar.gz file
    rm -rf $version-$now

    # Shows text "Backup done."
    printf "\nBackup done.\n"

    # Show where backup archive file is.
    echo "Backup is archived to .tar.gz file at $backupdir/wekan.tar.gz"
}

# Checks is the user is sudo/root
if [ "$UID" -ne "0" ]
then
    echo "This program must be launched with sudo/root."
    exit 1
fi

# Starts
makeDump
```

...and I get this output:

```text
The database backup is in progress.

/var/lib/snapd/snap/wekan/1798/bin/mongodump: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Makes the tar.gz archive file.
1798-2021-11-11_17.36.37/
1798-2021-11-11_17.36.37/snap-settings.txt

Backup done.
Backup is archived to .tar.gz file at /mnt/backup/wekan/wekan.tar.gz
```

I'm specifically concerned about the line `/var/lib/snapd/snap/wekan/1798/bin/mongodump: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`, as it means I have no way of backing up WeKan and restoring it (short of the entire server image).

I've tried it with a fully up-to-date system.

Although, incidentally, I DID have an earlier error that I fixed - my script up there fixes the "Targets the dump file" line to be compatible with CentOS / RHEL / Rocky Linux systems. :3

**Comment by xet7** [comment]
You should link to LD_LIBRARY_PATH etc:
https://github.com/wekan/wekan/wiki/Backup#backup-wekan-snap-to-directory-dump

**Comment by tromlet** [comment]
Yer a hero, Harry. Er, uh, I mean @xet7.

I got it working, just added those exports to the beginning of my scripts and now I have a quick and dirty backup of all of our data in our two WeKan instances!
