### ISSUE TITLE
Big performance problem with "watching" functionality enabled

### ISSUE THREAD

**Issue by galletl** [wekan/wekan#4145]
Hello.

We have big performance problem with some users.
For thoses users, the browser (Firefox, Chrome, etc.) lags 10-30 seconds before they can use Wekan and Wekan can lags also after first board loading.
On Firefox, the message "This page is slowing down Firefox…" appears systematically.
The problem appears only for some users on a same board (~200 cards). On their PC, CPU is massively use and memory consumption is ~1Gb for the browser tab with Wekan. Server resource was not very used. So, the problem is rather on the client side. 

After (long) investigation, I have found the origin : users with performance problem have activated "watching" on the board with lagging problem.

If they disable "watching" functionality, Wekan is reactive.

Wekan is deployed with Snap on Debian Linux 10 behind an Apache HTTP Server.
Wekan is configured to send mails on a local postfix who relay to a Exchange Server.
I have detected no problem to the sending mail process.

PS: this issue look like https://github.com/wekan/wekan/issues/3938 but I don't know if it is the same origin.

**Comment by xet7** [comment]
So the solution is to remove watching feature? ;)

**Comment by xet7** [comment]
Or remove all Javascript etc extra stuff from browserside, only have HTML/CSS that is compatible with all browsers. That would be so fast, right? ;)

**Comment by xet7** [comment]
No drag drop anymore etc ;)

**Comment by galletl** [comment]
Perhaps !
I told users in my administration to stop using it.

**Comment by galletl** [comment]
Seriously, Wekan work great in general. But, with this functionality enabled, Wekan becomes unusable with some board.
Perhaps, there is a problem in my Wekan configuration ?

**Comment by xet7** [comment]
@galletl 

I don't know, but I could guess, that if there are many changes at board, bottleneck could be sending so many emails. I have not yet coded upcoming feature where many notifications are combined to one notification.

**Comment by xet7** [comment]
Anyway, currently WeKan contributors are fixing to current Meteor WeKan so fast with pull requests coming all the time, so I may run out of reasons to complain before I finish any of my silly rewrite prototypes.

**Comment by xet7** [comment]
@marcungeschikts 

That's because Meteor WeKan currently has memory leaks. Maybe setup cron job to restart wekan nightly?

I'm coding RAM and CPU usage related fixes currently. I presume they will be released this year when I get then working.

**Comment by xet7** [comment]
@galletl @marcungeschikts

Does performance problem still exist in newest WeKan v6.60 ? There has been fixes to memory leaks.

**Comment by galletl** [comment]
Hello.
@xet7 
I plan an upgrade and I answer you.

**Comment by galletl** [comment]
Hello.

@xet7
I can't test last version because I can't upgrade my WeKan installation.

If I run `snap download wekan`, the result is the revision 1998 (I have revision 1999).

I think I have the same problem described in https://github.com/wekan/wekan-snap/issues/161.

**Comment by tangjiahao2001** [comment]
@xet7 I deployed the latest version with docker in CentOS 7, `image: quay.io/wekan/wekan:v6.70`

### USE `docker stats`
![image](https://user-images.githubusercontent.com/72953189/212821584-6f4d8471-2db1-40d9-869c-7a34f48e880b.png)

![image](https://user-images.githubusercontent.com/72953189/212823062-8c72940f-be63-4c90-9dae-157911994eb0.png)

Not open email, Not open "watching", Just one person use it. There are two Kanban boards, one containing less than 50 cards and one containing less than 30

For personal use, I just use the basic functions, but for me, I feel that wekan's memory usage is relatively high. I used docker to deploy a rich text Note software that used less than 150MB of memory, but wekan used over 300MB for a long time.

Best wishs!

**Comment by xet7** [comment]
@tangjiahao2001 

> For personal use, I just use the basic functions, but for me, I feel that wekan's memory usage is relatively high. I used docker to deploy a rich text Note software that used less than 150MB of memory, but wekan used over 300MB for a long time.

Previously problem was:
- too high RAM usage, like requiring 4 GB RAM, and growing RAM usage (memory leaks)
- 100% CPU usage, or growing CPU usage

Sure there are ways to get RAM usage lower than 300 MB, but it's not the most critical issue currently.
