### ISSUE TITLE
Copy link to card button don't work

### ISSUE THREAD

**Issue by bbyszio** [wekan/wekan#4155]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Operating System: Ubuntu 18.04.6 LTS
* Deployment Method(Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node.js Version: 12.22.7
* MongoDB Version: 3.2.22
* Wekan works on newest desktop and mobile webbrowsers that support Javascript. What webbrowser version are you using? yes

**Problem description**:
- *REQUIRED: When i click on the "Link to card" icon, nothing happens. 
- ![image](https://user-images.githubusercontent.com/34517676/142183036-b5ff8d29-5fd6-4155-a5c5-0252c46882d9.png)
- When i go over the Menu->More->"Copy card link to clipboard" it copies only the relativ link without the domain. 
![image](https://user-images.githubusercontent.com/34517676/142183393-ea17bae5-b3ae-49ae-bb73-4c2d23330d57.png)

- This error is an old error wich was fixed in the last year i think. No we have it again.;) In the logfile nothing is logged.;)

**Comment by mfilser** [comment]
I will have a look at this.
