### ISSUE TITLE
Can't select labels on board view

### ISSUE THREAD

**Issue by chaudebault** [wekan/wekan#4156]
Hi,
on wekan v5.78.0 installed with snap, we can't select labels on dekstop view.
Example: on this card with a yellow label, I can't disable the yellow or enable another label:
![image](https://user-images.githubusercontent.com/29449458/142196630-e60011d9-34af-44cd-b8f4-bd55245da338.png)

Selecting labels work in the card view.
Thanks for your help

**Comment by mfilser** [comment]
I have a look at this, give me some time..

**Comment by mfilser** [comment]
I got the problem fixed. I will run my CI and test it on desktop and mobile. PR is coming soon.
