### ISSUE TITLE
Yes/no Radio boxes are too close to each other

### ISSUE THREAD

**Issue by Tanarri** [wekan/wekan#4159]
Hi,

In the admin panel --> account, the radio boxes are too close to each other, so it doesn't look nice in my opinion.

Image:
![grafik](https://user-images.githubusercontent.com/6181166/142508388-a5b0348d-a0fe-4bd8-a402-ab9adb7b7136.png)

By adding the following lines, the distance between the radio boxes is increased, which looks better. Unfortunately I don't know in which file the CSS information is, otherwise I could make a pull request.
```
input[type="radio"] {
    -webkit-appearance: radio;
    min-height: inherit;
    margin: 4px; /* NEW */
}
```
After:
![grafik](https://user-images.githubusercontent.com/6181166/142508535-5c5a353e-e939-4130-a2ff-7f444d76e6bb.png)

Greetings
TanarRi

**Comment by mfilser** [comment]
Thank you for your css suggestion :clap:
I will have a look at this.
