### ISSUE TITLE
Feature request: Time base rules

### ISSUE THREAD

**Issue by huma2000** [wekan/wekan#4164]
Hi,

Just started to work with wekan and I am planning to implement it to help with the workflow of our veterinary hospital.
With the actual rules I can automatize the creation of list on the animals but some things happen regularly to them, so It will be great if a trigger based on a timer or based on a fix hour can be implemented, lets say something like:
- After 2 hours of card being created send and allert/ reset a check list/etc

This can be very useful on other scenarios too, like in time sensitive task where you can automatize the reminder for example.

Cheers

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2476#issuecomment-974627426
