### ISSUE TITLE
Manual Install Instructions anywhere? Not interested in sandstorm, snap, docker, flatpak, appimage, etc.

### ISSUE THREAD

**Issue by xekon** [wekan/wekan#4167]
Has anyone put together some manual install instructions? similar to this: https://docs.taiga.io/setup-production.html#setup-prod-from-source-code

debian package / ppa would be OK! but prefer installing dependencies/requirements via apt and then compiling/installing wekan manually.

We are currently using Kanboard and while it has served us fairly well there are some issues with it that have slowed down our productivity. I am currently reading about and testing possible replacements for kanboard.

Really appreciate it if somebody could point me to the manual install documentation, thank you.

**Comment by xet7** [comment]
https://wekan.github.io Download section

**Comment by xet7** [comment]
without container/vm

**Comment by xekon** [comment]
Thanks for the reply, there does not appear to be a debian based installer, however maybe I can work off the raspberry pi instructions and modify them for the debian equivalent for amd64

the ones I see under "Without container/VM" are:

RaspberryPi : looks up to date, but its for pi (I can probably modify these to work on an amd64 based debian system)
FreeBSD: 2 years old, but probably still works, prefer debian though.

Ones I would not / could not use:
Offline Windows
Mac
smartOS
Qnap NAS
Uberspace
Server for Android

Will try and use the raspberrypi instructions and modify them for an amd64 debian based system.

But if you do happen to know of any install instructions for an amd64 debian based system I would be very interested in them. I run Ubuntu 20.04.3

**Comment by xet7** [comment]
@xekon 

That pi page https://github.com/wekan/wekan/wiki/Raspberry-Pi is for any Linux/BSD/etc on many CPU platforms. Not only pi. I tried to add more clarifying text to beginning of that page.

**Comment by xekon** [comment]
Excellent! thank you for clarifying that, very excited to get this up and running and try it out, will get it setup tonight!

**Comment by xet7** [comment]
> We are currently using Kanboard and while it has served us fairly well there are some issues with it that have slowed down our productivity. I am currently reading about and testing possible replacements for kanboard.

Can you give more details about what has slowed down your productivity with Kanboard? Both Kanboard and WeKan have a lot of features.

**Comment by xekon** [comment]
Well its a long list, despite all these issues we have used kanboard for nearly 2 years! and it has helped us to stay organized, but I have a little free time so I am evaluating other products.

with kanboard we use bigboard plugin so we can get an overview of what we are working on.

When you make an edit to a project or task it reloads the entire page and jumps it back to the top, you have to wait for the page to fully reload then scroll back down to the section you were working on.

Also anytime I make a new project, I have to set permissions for other users to be able to edit the project/tasks. This eats up time as well. An editable set of default permissions for newly created tasks would have saved a lot of time, we are a small team.

To edit the color of a task card I have to click edit task, left click the color drop down, left click on the color i want, then click save.... a right click menu at the bigboard that allows me to simply pick the color from a flyout menu would have saved a good amount of time.

It would also be nice if you could define some sort of automatic rules for card colors. for example on creation of new cards by a particular user it gets a particular color. Maybe if the task sits in work in progress for more than 2 weeks it uses a similar color 2 shades darker, things like this can save a lot of time.

Kanboard does not allow inline images in the description/post you can only add them as attachments at the bottom. This is unfortunate because sometimes having the pictures directly in the post can add valuable context.

With the Kanboard bigboard, you have to add newly created projects, with a selection picker, I would prefer that all projects are added to the bigboard by default (we are a small team)

a faster overall page load speed of the bigboard would also be nice. currently we have about 40 projects with 3-10 cards per project, fully loaded page speed is about 2 seconds. This is not over the internet, its on our local network on a xeon e5 server with plenty of resources. I think the page load speed would matter a little less to me if the entire page didn't have to rerender when we make a change to a single task.

You also cannot assign a task to more than one user, very unfortunate, but not the end of the world I guess.

The overall look of kanboard is also not the greatest, the best theme I have found so far is Moon which is not bad, but still seems a little clunky compare to the UI on highly polished software.

**Comment by xet7** [comment]
@xekon 

> with kanboard we use bigboard plugin so we can get an overview of what we are working on.

In WeKan, dashboard kind of systems can be made with linked cards: https://github.com/wekan/wekan/discussions/4169

> When you make an edit to a project or task it reloads the entire page and jumps it back to the top, you have to wait for the page to fully reload then scroll back down to the section you were working on.

Hmm, you could try does this work better in WeKan.

> Also anytime I make a new project, I have to set permissions for other users to be able to edit the project/tasks. This eats up time as well. An editable set of default permissions for newly created tasks would have saved a lot of time, we are a small team.

In WeKan Admin Panel, you can add people to your teams or organizations, and at board add team or organization.

> To edit the color of a task card I have to click edit task, left click the color drop down, left click on the color i want, then click save.... a right click menu at the bigboard that allows me to simply pick the color from a flyout menu would have saved a good amount of time.

In WeKan, it's possible to change color of swimlane/list/card, and select board color/theme.

> It would also be nice if you could define some sort of automatic rules for card colors. for example on creation of new cards by a particular user it gets a particular color. Maybe if the task sits in work in progress for more than 2 weeks it uses a similar color 2 shades darker, It could go back to 2 shades brighter when there is an update to the task, things like this can save a lot of time.

In WeKan, you can look at some rules at right sidebar cog icon / Board Settings.

> Kanboard does not allow inline images in the description/post you can only add them as attachments at the bottom. This is unfortunate because sometimes having the pictures directly in the post can add valuable context.

In WeKan, you can select which card attachment image is cover image at minicard.

> With the Kanboard bigboard, you have to add newly created projects, with a selection picker, I would prefer that all projects are added to the bigboard by default (we are a small team)

Hmm, maybe there should be some more automated way to create dashboard? How that bigboard works, can you show anonymized screenshot?

> a faster overall page load speed of the bigboard would also be nice. currently we have about 40 projects with 3-10 cards per project, fully loaded page speed is about 2 seconds. This is not over the internet, its on our local network on a xeon e5 server with plenty of resources. I think the page load speed would matter a little less to me if the entire page didn't have to rerender when we make a change to a single task.

Sorry, current version of WeKan loads all cards of current board to browserside, so I don't know is WeKan yet any faster. I'm currently researching how to fix this, and show only visible cards.

> You also cannot assign a task to more than one user, very unfortunate, but not the end of the world I guess.

In WeKan, it's possible to assign task to many users. There is also board user roles for BoardAdmin/CommentOnly/NoComments/Worker, where Worker can only assing tasks to itself, not unassign tasks.

**Comment by xekon** [comment]
@xet7 is there an online demo of wekan anywhere? I tried this but it 503 https://apps.sandstorm.io/

I would like to try implementing the dashboard like system to make sure it does what I need similarly to the bigboard from kanboard:

In WeKan, dashboard kind of systems can be made with linked cards: https://github.com/wekan/wekan/discussions/4169

**Comment by xet7** [comment]
@xekon 

Yes, there is online demo, only thing missing there is access to Admin Panel:
- Register: https://boards.wekan.team/sign-up
- Login: https://boards.wekan.team/sign-in

That demo also has mobile apps at Play Store, Windows desktop Microsoft Store and Ubuntu Touch OpenStore:
https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix

If you have your own WeKan server, this way you can add mobile etc app icon:
https://github.com/wekan/wekan/wiki/PWA

I also provide paid hosting: https://wekan.team/commercial-support/

**Comment by xekon** [comment]
well... I tried the demo made a few boards, I like that you can star them and they show up as clickable links along the top.

I wonder if the admin interface has options to make newly created boards stared by default, then users would need to unstar them if they are not using them (better for our small team)

I also wonder if the star favorites along the top get highlighted or something when a particular board has activity in the last x amount of time.

We always use 4 lists:  Waiting, Ready, Work in Progress, Complete.... I could not figure out how to make a template that always gets applied with these 4 lists on creation of a new board, from the look of the product there probably is a way but I could not figure it out intuitively.... maybe its in the admin panel you spoke of.

I was reading the documentation here: https://wekan.github.io/wekan-doc/user/Board-Administration.html
there is a link for Templates Topic that I tried to click but it took me to a 404 not found: https://wekan.github.io/wekan-doc/user/Templates.md

Is there a way to define a default set of lists for newly created boards?

**Comment by xet7** [comment]
@xekon 

> well... I tried the demo made a few boards, I like that you can star them and they show up as clickable links along the top.
> 
> I wonder if the admin interface has options to make newly created boards stared by default, then users would need to unstar them if they are not using them (better for our small team)

Currently those are per-user stars, stars are not shared.

> I also wonder if the star favorites along the top get highlighted or something when a particular board has activity in the last x amount of time.

Card aging #3984 and board aging is not implemented yet.

> We always use 4 lists: Waiting, Ready, Work in Progress, Complete.... I could not figure out how to make a template that always gets applied with these 4 lists on creation of a new board, from the look of the product there probably is a way but I could not figure it out intuitively.... maybe its in the admin panel you spoke of.
>
> I was reading the documentation here: https://wekan.github.io/wekan-doc/user/Board-Administration.html there is a link for Templates Topic that I tried to click but it took me to a 404 not found: https://wekan.github.io/wekan-doc/user/Templates.md
> 
> Is there a way to define a default set of lists for newly created boards?

At `All Boards` page, when hovering mouse pointer at top of board icon, there is at bottom right corner `Clone Board` button that clones board.

If you used Google Login in that demo, Templates is not created, it's a bug #2339

Related feature Shared Templates is In Progress, not ready yet #3313

Templates docs are at https://github.com/wekan/wekan/wiki/Templates

> the features guides link here also did not work: https://wekan.github.io/wekan-doc/user/
> 
> ... actually it seems most of the links in the docs are not working...
> 
> the forum appears to be working, so i will check there.

Huh, what forum? wekan-doc could have old links.

**Comment by xet7** [comment]
Also, editing Organizations/Teams/People is only at Admin Panel. It's not at demo.

That demo is actually full WeKan, but I just can not give Admin Panel access there, because there is not yet feature to have per-user Admin Panel.

**Comment by xekon** [comment]
Stars not being shared is not a problem, in fact that's a great way to have it, but I am curious if all newly created boards could be stared for any existing users. this would make it more obvious that. HEY THERE'S A NEW BOARD! (an option like star new boards)

Card Aging and board aging would be super slick! it would really help team organization, then you know which ones are active and which ones are not.

So am I understanding correctly, to set some default lists you would create a board with some lists but without tasks, and then just duplicate that board when you want to make a new board? That would work, but i would prefer being able to just click "Add Board" and have it be created with my default set of lists.

I used password instead of google login, so i guess i lucked out there.

here is the forum I was talking about: https://community.vanila.io/wekan

Another thing I noticed is that lists have a fixed width, I would prefer auto width which is how kanboard currently acts, maybe a toggle setting to switch between fixed width and auto width, but I seen you discussed it here: https://github.com/wekan/wekan/issues/1266

I really appreciate you taking the time to answer my questions, i am sure your fairly busy and this thread has run on for quite a while.

Overall I am really impressed with Wekan, I actually already eliminated most products I reviewed, Wekan is currently on a short list of about 3 remaining products. (I reviewed at a glance about 30 of these kanboard type solutions)

Last night I ruled out several of the remaining ones, they have too many features to their detriment, more features are great except when they are on by default and cannot be disabled, then it becomes a cluttered mess...

**Comment by xekon** [comment]
One more thing, In addition to starred boards, maybe you could have a "pinned boards" feature. This would make it so that if somebody pins a board, it would show up at the start of the starred boards list for ALL users. (similar to forums)

**Comment by xet7** [comment]
@xekon 

> Stars not being shared is not a problem, in fact that's a great way to have it, but I am curious if all newly created boards could be stared for any existing users. this would make it more obvious that. HEY THERE'S A NEW BOARD! (an option like star new boards)

When adding new Organization/Team/Member to board, that user need to click `Accept` to join that board. So that feature kind of already exists.

> Card Aging and board aging would be super slick! it would really help team organization, then you know which ones are active and which ones are not.

Well, someday WeKan maybe will have that.

> So am I understanding correctly, to set some default lists you would create a board with some lists but without tasks, and then just duplicate that board when you want to make a new board? That would work, but i would prefer being able to just click "Add Board" and have it be created with my default set of lists.

That `Add Board / From Template` should do just that, it could already work, or work after adding Shared Templates #3313

> I used password instead of google login, so i guess i lucked out there.
> 
> here is the forum I was talking about: https://community.vanila.io/wekan

I do still reply at that forum, but that forum does not have good search etc, so mostly from that forum we have moved to GitHub Discussions. Although, I don't know is that Discussions good at all, because some ask about features and fixes there, when they belong to issues, so it's kind of confusing to have Discussions enabled.

> Another thing I noticed is that lists have a fixed width, I would prefer auto width which is how kanboard currently acts, maybe a toggle setting to switch between fixed width and auto width, but I seen you discussed it here: #1266

Yes, sometime there will be a way to change width/height #1266, and collapse swimlanes etc #2804

> I really appreciate you taking the time to answer my questions, i am sure your fairly busy and this thread has run on for quite a while.

I like when somebody is interested enough about WeKan to ask some questions! Feel free to ask anything.

> Overall I am really impressed with Wekan, I actually already eliminated most products I reviewed, Wekan is currently on a short list of about 3 remaining products. (I reviewed at a glance about 30 of these kanboard type solutions)
> 
> Last night I ruled out several of the remaining ones, they have too many features to their detriment, more features are great except when they are on by default and cannot be disabled, then it becomes a cluttered mess...

What are these 3 remaining products? :slightly_smiling_face:

**Comment by xekon** [comment]
Wekan - nice and minimalistic, and thanks to your answers I already know for the most part which features are in place and which ones we will have to wait for.

Planka - was able to use their demo, is very minimalistic, but seemed to work good. (have not yet researched which of the features are missing that we will need)

leantime - this one overall looked fairly good, but there was only a few pictures and I could not find a demo to try it anywhere, so its hard to say if it would do what we need it to.

kanboard - and then of coarse we could just stick with kanboard, or try to fix the issues that we have with it.

I also noticed that gitea has a projects like kanboard which you can assign open issues to a project, I will probably use this for my personal software projects, but not for my other business which is more of a small team of network administrators. having to create an issue and then follow that up by assigning it to a project, is less intuitive then opening a project and adding a task directly to it.

**Comment by xet7** [comment]
@xekon 

Gitea is a fork of Gogs. There is some kind of integration here, I don't know is it useful, or does it work well enough: https://github.com/wekan/wekan-gogs

**Comment by xet7** [comment]
@xekon 

I do sometimes look at various kanban software, to try to figure out could it be possible to figure out import/export.

Usually those non-WeKan kanban software has so different codebase, features, bugs/fixes etc, I have not yet figured out what works or does not work. Sometimes I have trouble installing or compiling them.

**Comment by xet7** [comment]
A little similar like Gitea, there is https://fossil-scm.org , there is some kind of kanban in progress but I have not tried it yet http://chiselapp.com/user/charlie/repository/fossil-kanban/index

**Comment by xekon** [comment]
I got this installed, but the only thing I ended up using from the raspberry pi page was the environment file and service file, the rest I just modified from the dockerfile, but without using docker.

**Comment by xekon** [comment]
made a write up: https://github.com/wekan/wekan/issues/4202

**Comment by Jieiku** [comment]
Not having BigBoard was a non starter for me with using Wekan... Here is a screenshot of the current incarnation of bigboard on my test environment so I dont have to censor anything:

![2021-12-08_05-55](https://user-images.githubusercontent.com/106644/145221165-574b46bd-ff74-4380-bba5-4c91c12eed85.png)

**Comment by NLBlackEagle** [comment]
Bringing this to light has been a godsend! Perhaps this could be included into the wiki platform page too? Building from source simply gives one much more options to work with.

Coincidentally I have also found my way here after running into productivity issues using kanboard.

**Comment by xet7** [comment]
I'll try to make installing etc simpler.

**Comment by Jieiku** [comment]
Feel free to do whatever you want with the info here https://github.com/wekan/wekan/issues/4202

**Comment by xet7** [comment]
Building from source is broken. Please do not waste your time. Only some Docker images work.

**Comment by Jieiku** [comment]
It must have recently broke then, back when I wrote up that post it worked fully. I still have the proxmox container for it.

**Comment by xet7** [comment]
Currently when building from source, CSS is missing #4545

Yes, it's recent problem.

**Comment by NLBlackEagle** [comment]
Good to hear it was not me, I've done several attempts installing Wekan from source but failed pretty badly. Only the snapd and a old pre-packaged bundle as per these instructions: https://www.howtoforge.com/tutorial/ubuntu-wekan-installation/ managed to work for me.

I've also reverted back to using kanboard for the time being as it's easier to get a overview of the tasks that I still have to complete, especially given there are a lot of tasks I need to add. Here's the two different roadmaps for comparison:

Kanboard: https://roadmap.dregora.com/?controller=BoardViewController&action=readonly&token=faa613072bf23a92431a5afa615629caea1082bea725c7ba232bfec868fd

Wekan: https://wekan.dregora.com/b/vNdh4DJbwnh8vX6np/dregora

Wekan functions better on pretty much all fronts except for customization options given that one can directly change kanboard CSS to fit their needs.

**Comment by xet7** [comment]
Newest WeKan should show CSS correctly.

**Comment by xet7** [comment]
@NLBlackEagle

> Wekan functions better on pretty much all fronts except for customization options given that one can directly change kanboard CSS to fit their needs.

Custom CSS and Javascript is very dangerous: https://github.com/wekan/wekan/issues/3086#issuecomment-627615017

Correct solution is to add setting like here #4558 

WeKan target group is those that call WeKan "Monkey Proof Software", so that WeKan is easy to figure out, user friendly, polished enough. Jira is not "Monkey Proof Software".

If someone is asking for "Custom CSS", that means they are programmers, and should be sending PRs to WeKan with fixes to UI, new settings, etc, so that WeKan works safely without "Custom CSS", for normal non-programmer people.
