### ISSUE TITLE
Linking cards.

### ISSUE THREAD

**Issue by phaseshift3r** [wekan/wekan#4171]
When Linking cards the parent card list is empty at first attempt.

opencard -> breadcrumb -> more -> board source gets filled with boards.

second dropdown "parent card" is empty. 

close the breadcrumb. redo the above. now the dropdown with "parent card" isnt empty and youre able to link the card to a parent .

Wekan: Version 5.78.0

raw install on ubuntu with mongodb 4.2.17 oplog and replicaset configured and working

**Comment by xet7** [comment]
@phaseshift3r 

How did you configure oplog and replicaset?

**Comment by phaseshift3r** [comment]
Hi @xet7 
Environment variable in my systemd wekan.service file
MONGO_OPLOG_URL= pointing to replicaset and authdb for it

i took a peek at how rocketchat did it. 
https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/mongo-replicas

the reason is i run multiple node instances behind nginx against a  mongodb cluster with a replicaset configured.
offcourse i dont know the implimentation in wekan, but it uses meteor and seems to work like expected. perhaps i was hasty in my thoughts?

changes are updated snappy between different clients.

**Comment by phaseshift3r** [comment]
Updated to 5.80.  No issues. 

Found out my node links wasnt updated so it used node 12.22.6 instead of node 12.22.7 so that was the issue iam sure. 
Resolved. 

Sorry.
