### ISSUE TITLE
Default Top Left Corner Logo Image display few seconds before  a display of custom Top Left Corner Logo Image

### ISSUE THREAD

**Issue by Emile840** [wekan/wekan#4173]
Default Top Left Corner Logo Image display few seconds before  a display of custom Top Left Corner Logo Image (see gif image below)
![custom top left corner logo image url](https://user-images.githubusercontent.com/83423044/143463848-8fd17202-7afe-4339-ba7d-a6382ac8a50e.gif)

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4174
