### ISSUE TITLE
LDAP logging broken?

### ISSUE THREAD

**Issue by AxisNL** [wekan/wekan#4175]
## Issue

I can't get any output from the ldap module.

Yesterday I did a fresh install of an Ubuntu 20.04 machine, running pre-built wekan-5.78.zip with nodejs v12.22.7. This machine is running on an airgapped network, and security policies make sure we don't want to use Docker and other container technologies. I have quite some *nix experience, but no nodejs experience, so it takes me a while as a DevSecOps veteran to wrap my head around all the different deployment strategies wekan is supporting ;) 

I couldn't find any logging for wekan, but I found out that if I set the environment variable DEBUG to '*' and I start node, I get a lot of logging, each http request, etc on stdout. In my case systemd writes that output to the journal, fine.

But I want to get ldap up and running, and I want the log output for that. I can't figure out HOW to get any logging. I see nothing in the output for authentication/ldap. What am I missing?

I can't get ldap to work, but first I would like to see exactly what's happening under the hood, and then I'm pretty sure I can fix it from there on..

Excerpt from my environment file:

```
DEBUG=*
DEFAULT_AUTHENTICATION_METHOD=ldap
LDAP_Authentication_Password=****
LDAP_Authentication=true
LDAP_Authentication_UserDN=****
LDAP_BaseDN=****
LDAP_Enable=true
LDAP_Encryption="ssl"
LDAP_Fullname_Field="displayName"
LDAP_Group_Filter_Enable=false
LDAP_Host=******
LDAP_Idle_Timeout=10000
LDAP_Internal_Log_Level=debug
LDAP_Log_Enabled=true
LDAP_Login_Fallback=true
LDAP_Merge_Existing_Users=true
LDAP_Port=636
LDAP_Reconnect=true
LDAP_Timeout=10000
LDAP_USER_AUTHENTICATION=true
LDAP_USER_SEARCH_SCOPE="sub"
LDAP_Username_Field="cn"
LDAP_User_Search_Field="sAMAccountName"
LDAP_User_Search_Filter=
LDAP_User_Search_Scope=
MAIL_FROM=*****
MAIL_URL=*****
MONGO_URL=*****
PORT=2000
ROOT_URL=https://****
UTF8_Names_Slugify=true
```

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Operating System: Ubuntu 20.04.03 LTS
* Deployment Method(Snap/Docker/Sandstorm/bundle/source): bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node.js Version: v12.22.7
* MongoDB Version: 4.4.10
* Wekan works on newest desktop and mobile webbrowsers that support Javascript. What webbrowser version are you using? n/a

**Problem description**:
Not enough logging output

**Comment by xet7** [comment]
Please remove double quotes from settings. Thanks!

**Comment by AxisNL** [comment]
> Please remove double quotes from settings. Thanks!

Great, thanks, removed all the quoted variables. Still no logging on authentication or ldap. Any ideas? When logging in using any LDAP account (or a non-existing acount for that matter), I get the gui error "Login forbidden", but no output from the server whatsoever.

**Comment by xet7** [comment]
```
DEBUG=true
```

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/LDAP

**Comment by AxisNL** [comment]
When I use `DEBUG=true` I get no more debug output whatsoever. When I do `DEBUG=*` I at least get some info like requests. And thanks for the LDAP page, I studied several different LDAP configuration pages, including that one. I don't see any specific info on LDAP debugging, except for a few flags I already set?

**Comment by xet7** [comment]
@AxisNL 

Well, I'm just guessing, because I know nothing about LDAP, and I don't have any LDAP server running. WeKan LDAP code is here: https://github.com/wekan/wekan/tree/master/packages/wekan-ldap

**Comment by AxisNL** [comment]
Well, if I can't get ANY debug output, I guess something else is broken. Even without ldap, shouldn't failed/succesful logins be shown in the debug logs? If yes, perhaps I should backtrack versions until logging does work?

**Comment by xet7** [comment]
@AxisNL 

Maybe. LDAP has been added to WeKan by those that know something about LDAP.

**Comment by AxisNL** [comment]
If we forget about LDAP, but just focus on Wekan. Should DEBUG=true show failed/succesful logins or anything related to authentication? In the server output? If so, I should focus on fixing that first.

**Comment by xet7** [comment]
AFAIK `DEBUG=true` does show OAuth2 logins. I don't know is similar logging added to LDAP yet. OAuth2/OIDC directories are at https://github.com/wekan/wekan/tree/master/packages .

**Comment by AxisNL** [comment]
> AFAIK `DEBUG=true` does show OAuth2 logins. I don't know is similar logging added to LDAP yet. OAuth2/OIDC directories are at https://github.com/wekan/wekan/tree/master/packages .

Sorry, I think i did not ask my question clear enough. I was asking if the internal authentication (password auth) logs anything  to the debug output? (So this is not related to external authentication such as ldap, oidc).

**Comment by xet7** [comment]
@AxisNL 

Depends is there checking for `DEBUG=true` here:
https://github.com/wekan/wekan/blob/master/server/authentication.js

**Comment by AxisNL** [comment]
> @AxisNL
> 
> Depends is there checking for `DEBUG=true` here: https://github.com/wekan/wekan/blob/master/server/authentication.js

I don't quite understand what you are saying, but I see process.env.DEBUG is used in line 131, but I have no idea if that makes authentication write debug info to stdout. I have DEBUG=true in my environment variables, but still stdout isn't showing anything when local users log in. I guess I'm going to have to get an internet-connected machine and try the docker stuff, because it looks like the whole debug stuff is broken in the bundle or something.

**Comment by faburem** [comment]
Hi @AxisNL,
I just stumbled upon the same problem when we moved our Wekan instance to LDAP authentication. The root cause is that Wekan does not respect the environment variable `DEFAULT_AUTHENTICATION_METHOD=ldap` - instead you have to set it through the Admin panel > Layout settings:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/11456790/154688518-ebd295f6-99f5-43b4-8dd0-c2c251f6023c.png">
If you set this to LDAP and save then the logging and authentication through LDAP works as expected. Not exactly straightforward but it works :)

Best,
Fabian

**Comment by AxisNL** [comment]
Hey Fabian, I'm pretty sure I have that setting set as well. But never mind, I deleted this server and set up a new one using the docker image. I don't like docker in my puppet-managed and enterprise air-gapped networks, but at least everything works out of the box there ;)
