### ISSUE TITLE
Feature request: option to show or hide members and assignee(s) on minicard

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4177]
Hello,

On Card Settings, when "Creator" is uncheck, "Creator" does'nt appear on minicard (in minicard.jade : if showCreator).
However, on Card Settings, when "Assignee" and/or "Members" are uncheck, infos always appears on the minicard.

I think it would be great if "Assignee" and/or "Members" could be displayed or hidden like "Creator".
If you are ok, I could have a look at this

Thanks

**Comment by xet7** [comment]
@Ben0it-T 

Yes you can look at this and send PR. Thanks!

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4179
