### ISSUE TITLE
Can not delete checklist on mobile

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4196]
Hi,
at iPhone 12 mini I created PWA icon for Safari for WeKan, and opened WeKan card. When I create checklist to card, and click Delete to delete Checklist, confirmation popup is at bottom of the screen so that I see some of it's text at top but button to confirm is not visible, I can not click it. Help?

**Comment by Emile840** [comment]
Hi @xet7
I noticed the same bug on the web browser "wekan version 5.29 and 5.78" (i think it's related to a focus element issue).
![image](https://user-images.githubusercontent.com/83423044/143555177-b8fb99e7-6318-4d35-8691-857b1574dec0.png)

**Comment by mfilser** [comment]
@xet7
I can have a look at this if you like

**Comment by xet7** [comment]
@mfilser 

Thanks! You can send PR.

**Comment by helioguardabaxo** [comment]
@mfilser 
Wouldn't it be better to use a popover just like in attachments?
![image](https://user-images.githubusercontent.com/24301085/143583152-b793c307-b49a-4ef1-9586-f8a906f8f313.png)

**Comment by mfilser** [comment]
@helioguardabaxo
Yes, that's the way i want to change it 🙂

**Comment by helioguardabaxo** [comment]
@mfilser 
Great!
Thanks

**Comment by mfilser** [comment]
@helioguardabaxo 
The commit is done and PR is ready, i just wait for the other open PR if the new change is "better".
