### ISSUE TITLE
Feature Request: Export card

### ISSUE THREAD

**Issue by mmarques28** [wekan/wekan#4197]
Hi,

When I try to export a simple card form my board there are no option available.
When I check the console of my browser (Chrome or Edge) I get the following error. 

```
Exception in template helper: Error: Template 'exportCard' cannot be found.
    at meteor_js_resource=true:407:5074
    at Object.o.nonreactive (meteor_js_resource=true:197:4139)
    at I (meteor_js_resource=true:407:4990)
    at meteor_js_resource=true:407:10502
    at Object.o.nonreactive (meteor_js_resource=true:197:4139)
    at n.t.renderComponent (meteor_js_resource=true:407:10432)
    at meteor_js_resource=true:407:9679
    at c._withTemplateInstanceFunc (meteor_js_resource=true:221:38718)
    at meteor_js_resource=true:407:9641
    at Object.o.nonreactive (meteor_js_resource=true:197:4139)
```

I am using snap wekan, which means I have all the latest versions.

Wekan 5.80.0
Meteor 2.2
Node 12.22.7
MongoDB 3.2.22

**Comment by xet7** [comment]
Sorry I did not yet finish Export card to PDF feature etc. It does not work yet.

**Comment by meyerrob** [comment]
Is there already an estimation when this interesting feature will be available?

**Comment by xet7** [comment]
@meyerrob 

There is no estimate yet. Maybe sometime this year, after I have done WeKan speed improvements.

**Comment by meyerrob** [comment]
Is there maybe the possibilty to get a higher priority for this feature if there is some kind of sponsoring?

**Comment by xet7** [comment]
@meyerrob 

When I look at that [export card feature at Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-r-open-source-kanban-board-with-mit-license/2WEQrd6DQgnksyZZ4), it seems that it has enough funding, and that I have set deadline of implementing that feature as today. Well, I did not even remember that I did set deadline, thanks for reminding!

I'll check what it would take to implement that feature.

**Comment by meyerrob** [comment]
Thank you, I am happy to hear that :-)

**Comment by pauloacosta** [comment]
Is this feature already available?

**Comment by xet7** [comment]
@pauloacosta 

No, someone that promised more funding did not pay. This feature has only 200 euro funding. Minimum is 500 euro.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
