### ISSUE TITLE
wekan-5.80-arm64 not starting (fiber problems)

### ISSUE THREAD

**Issue by kvacha13** [wekan/wekan#4199]
## I have been running the wekan-5.63-arm64 (downloaded https://releases.wekan.team/raspi3/wekan-5.63-arm64.zip) successfully. Recently I decided to update it to the newer wekan-5.80-arm64 (downloaded https://releases.wekan.team/raspi3/wekan-5.80-arm64.zip) and followed the update instruction provided at https://github.com/wekan/wekan/wiki/Raspberry-Pi. 
Unfortunately, the new version of wekan (5.80) fails to start. Tried to install the required dependencies (version of Node and Mongodb), newer and older versions. Tried to rebuild using the rebuild-wekan.sh file, npm install in "programs/server" but without any success. 
Finally, tried to run "node main.js" and got the following error "/opt/wekan/programs/server/node_modules/fibers/bin/linux-arm64-72-glibc/fibers.node" is missing.  I checked the folder and instead of  "linux-arm64-72-glibc" there is only "linux-arm64-83-glibc"..Any recommendations on how to fix the problem? 

**Server Setup Information**:

* Linux;  20.04.1-Ubuntu aarch64 GNU/Linux
* Node v12.16.1
* Mongodb version v5.0.3
* Apache2
* Web Browser Chrome

**Comment by xet7** [comment]
Fibers error could be because I did build on newer Ubuntu. Not 20.04. So you need to rebuild fibers. And maybe remove old folder.

**Comment by kvacha13** [comment]
Thank you Lauri for your prompt reply.

You say that I should not use Mongodb 5.x, but Wekan version 5.63 works OK with Mongodb 5.0.3. So, should i still downgrade it for Wekan 5.80??
I tried to rebuild fibers per your suggestion ("node build.js") without success (it asked for the missing nopt module and I installed it by npm install node-gyp). I should mention that I had tried it earlier too by running "npm install node-gyp node-pre-gyp fibers" in the programs/server folder.
The main problem seems node implementation, as even if the wekan service starts, the netstat -npl|grep node returns nothing. I would really appreciate your help. I need my wekan to be updated from 5.63 to 5.80 (and to get future updates too :-) . Thanks,.

**Comment by xet7** [comment]
@kvacha13 

WeKan is not yet tested with MongoDB 5.x, that has different syntax for creating database indexes. Database indexes could speed up WeKan, but I don't know how noticeable it is. There could also be other compatibility issues, because I have not tested MongoDB 5.x at all yet.

Can you try to use https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-a.sh script and and use it to build that arm64 bundle version? And check do you have all dependencies mentioned in that script? Maybe you are missing some dependencies or something. Also install newest npm and node:
```
sudo npm -g install npm

sudo npm -g install n

sudo n 12.22.7
```

**Comment by xet7** [comment]
@kvacha13

Oops sorry. It seems I have wrong Node.js 14.x version on my arm64 build server, I have now changed it back to Node.js 12.x. I hope WeKan v5.81 or newer bundle appearing in near future to https://releases.wekan.team/raspi3/ will be more successful for you. Thanks, great catch!

**Comment by xet7** [comment]
@kvacha13

In that newer bundle it should not be required for you to build fibers yourself. Anyway, you can test does it work without building fibers. Thanks a lot!

**Comment by kvacha13** [comment]
Thank you for the notice. I was going to upgrade ubuntu from 20.04 to 21.1 to let it try.... Wanted to ask also whether I should have used https://releases.wekan.team/raspi3/maintainer-make-bundle.sh or the one you suggested https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-a.sh. 
Anyway, I'll wait for the v5.81 and let you know how it will go through. Thank you.

**Comment by xet7** [comment]
@kvacha13 

You don't need to try bundle build scripts. Try only that WeKan v5.81 that is now uploaded to https://releases.wekan.team/raspi3/

It's not needed to upgrade Ubuntu, because my current arm64 build server is also using Ubuntu 20.04.

**Comment by kvacha13** [comment]
Well noted. Will try tomorrow and let you know the results.  Thank you.

**Comment by kvacha13** [comment]
Could not wait until tomorrow. Downloaded 5.81 and successfully updated from 5.63 to 5.81. Everything working as it should. Great work. Thank you so much. Waiting for new updates and for new features with the new updates :-).
