### ISSUE TITLE
2021-12-01 WeKan maintenance paused

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4207]
Hi,
it seems one of my paying customers paused all of my ability to code by sending one week time limit and threatening by legal action if feature is not ready by then.

For any WeKan contributors, you can still send pull requests, I will merge them if this situation is fixed sometime and I have had enough time to recover.

**Comment by mfilser** [comment]
@xet7 
I hope everything goes well, good luck.

**Comment by xet7** [comment]
@mfilser 

Thanks! I'll try to rest and recover, waiting for reply from that customer, would it be possible to cancel that time limit and threat.

**Comment by xet7** [comment]
I'll see if some day I will be able to code again. Currently I feel like slowing down from lightspeed of major architecture huge level feature devepment to walking speed one feature development, that could take some days.

**Comment by xet7** [comment]
After discussing this with some others, it seems total 2 different persons are trying to encourage to me to do 2 different things, with some non-usual way of encouraging. Of those, only one thing is currently important to do, and that is my WeKan related work. So I expect to recover soon and get back to making progress with current WeKan.

In theory, it could be possible that I would get that clients feature ready in one week or soon enough, if I don't receive more non-usual way of encouraging.
