### ISSUE TITLE
How can I setup the cron for email reminder job for snap installation?

### ISSUE THREAD

**Issue by mdemori** [wekan/wekan#4209]
Hi,

I've installed wekan Snap version and configured everything for e-mail delivery with smtp, sending the test message through the UI work as expected, I receive the test email.

Now I don't understand how can I set-up a cron job that check if there are some reminder to send.. there is something that the Snap version do by itself? Sorry but I can't find any documentation on this topic and I don't know snap very well :(

**Comment by xet7** [comment]
Moved to #2026
