### ISSUE TITLE
WeKan ® v5.83: Unable to delete checklist item.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4213]
Unable to delete checklist item.

**Comment by mfilser** [comment]
@xet7
I will have a look at it

**Comment by mfilser** [comment]
@xet7 
I can't reproduce it, for me, i can delete checklist-items at Wekan 5.83.
Do you get an error at the console?

**Comment by xet7** [comment]
Hmm, it happened once, but after that I was able to delete checklist items. I don't know. Nevermind.

**Comment by mfilser** [comment]
Thank you for the feedback. 

Probably it was a Heisenbug 😁

**Comment by xet7** [comment]
@mfilser 

Yes, there Heisenbugs like this #4214 will disappear sometime after enough changes.
