### ISSUE TITLE
Rare bug: Board icons random dance

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4214]
Rarely happens at `All Boards` page, that board icons change places randomly all the time, so it makes kind of hard to click board icon.

This bug will most likely disappear sometime when I have changed from using PubSub to use Methods or API.

**Comment by mohammadZahedian** [comment]
any improvement?
 its very annoying...

**Comment by Ben0it-T** [comment]
Is this bug like this ?
_(on each "page refesh" board icons change place)_
![wekan-board-icons-dance](https://user-images.githubusercontent.com/37017213/157118175-6bc59eb4-9426-4077-9dd8-1bb9e864f211.gif)

**Comment by xet7** [comment]
@Ben0it-T 

Yes, but this does not need page refresh. When this bug happens, about every second board icon places changes again.

**Comment by xet7** [comment]
At discussions https://github.com/wekan/wekan/discussions/4794 from @lealanana is about this same issue. Flickering, or boards icons changing to have different places, is the same issue. Fixing this would mean, that boards keep same place all the time.

https://user-images.githubusercontent.com/15545/210187742-a036a147-3985-4902-8424-f4a84483ad61.mp4

**Comment by mfilser** [comment]
> Is this bug like this ? _(on each "page refesh" board icons change place)_ ![wekan-board-icons-dance](https://user-images.githubusercontent.com/37017213/157118175-6bc59eb4-9426-4077-9dd8-1bb9e864f211.gif) [ ![wekan-board-icons-dance](https://user-images.githubusercontent.com/37017213/157118175-6bc59eb4-9426-4077-9dd8-1bb9e864f211.gif) ](https://user-images.githubusercontent.com/37017213/157118175-6bc59eb4-9426-4077-9dd8-1bb9e864f211.gif) [ ](https://user-images.githubusercontent.com/37017213/157118175-6bc59eb4-9426-4077-9dd8-1bb9e864f211.gif)

I think the boards all have the same sort number, so they load in different order each time the page loads again.

**Comment by xet7** [comment]
It does not need page refresh. When this happens, board icons change places every second. So it is impossible to click correct icon, because positions change all the time.

**Comment by xet7** [comment]
Similarly, when I try to so some MongoDB queries, each time MongoDB returns different results.

**Comment by xet7** [comment]
You can see this happening in video of this above comment https://github.com/wekan/wekan/issues/4214#issuecomment-1368567848

**Comment by mfilser** [comment]
It depends on your query and database data.
if both are good, the result is stable.
Also, it's not related to MongoDB, to every other database too.

**Comment by xet7** [comment]
So is there some bug in All Boards page MongoDB query? What kind of bug? Can you fix it?

**Comment by mfilser** [comment]
For analysing this issue i have to reproduce it, or have the boards collection data.

**Comment by xet7** [comment]
I don't currently know how to reproduce this bug.

**Comment by xet7** [comment]
This bug has happened to me sometime, but it does not happen every time.

**Comment by mfilser** [comment]
It never happended to me, and i use Wekan each day.

**Comment by xet7** [comment]
@mfilser 

I don't know are you using official newest WeKan version or your custom modified version with custom fixes and versions of MongoDB.

**Comment by xet7** [comment]
According to [this discussion](https://github.com/wekan/wekan/discussions/4794#discussioncomment-4568067) this did happen on Cloudron with WeKan v6.64

**Comment by xet7** [comment]
@nebulade

Has this happened to someone at Cloudron ? What version of WeKan and MongoDB are you using?

**Comment by xet7** [comment]
Also, I really would like to get WeKan working on Sandstorm again. There is MongoDB 3.0 at Sandstorm, and newest Meteor does not support it. So I'm making some kind of custom version of WeKan that would have possibility to use MongoDB 3.0 or migrate from it to SQLite.

**Comment by mfilser** [comment]
> @mfilser
> 
> I don't know are you using official newest WeKan version or your custom modified version with custom fixes and versions of MongoDB.

I use official MongoDB 6

**Comment by mfilser** [comment]
Only MongoDB 3 on Sandstorm? In my eyes, Sandstorm should upgrade, not Wekan downgrade.

**Comment by xet7** [comment]
Does @zenhack and @ocdtrekkie think it would be possible for Sandstorm to upgrade MongoDB ?

**Comment by xet7** [comment]
@mfilser 

What version of Meteor you use?

**Comment by mfilser** [comment]
The same than latest Wekan commit. 2.10.0

**Comment by nebulade** [comment]
> @nebulade
> 
> Has this happened to someone at Cloudron ? What version of WeKan and MongoDB are you using?

I am not aware of any such issue from Cloudron users. Personally I also use it every day and haven't seen it.
There is mongodb 4.4.10 and meteor 2.10.0 with nodejs 14.21.3

**Comment by zenhack** [comment]
To be clear: the version of mongo used by the wekan package in Sandstorm is entirely independent of the version used by Sandstorm itself. The only hurdle to updating is that you'd need to fully script the upgrade.

**Comment by xet7** [comment]
@zenhack 

Is that MongoDB 3.0 in meteor-spk, WeKan.spk, or elsewhere? In what code file it is included?

**Comment by xet7** [comment]
@zenhack 

1) Is that upgrade done when starting WeKan grain?

2) How to make sure migration is not interrupted? Maybe just save one textfile to grain after successfull upgrade, and skip upgrading next time. If upgrade failed, next time starting grain delete temporary upgrade files and try upgrading again?

3) Or could there be scheduled nightly cron job that upgrades all WeKan grains MongoDB to newest?

**Comment by ocdtrekkie** [comment]
@xet7 meteor-spk is where that particular MongoDB version is, and how it gets pulled into your Wekan SPK.

Either you'd want to add the upgrade functionality into an update to meteor-spk or build a custom vagrant-spk build script that uses newer Mongo and Meteor, and pulled in the data from old grains successfully.

But basically on grain startup, you'd want to identify if you your database was the old version, export/import it into the new version, and then start Wekan. And obviously the grain shouldn't delete the old database data until after the upgrade is successful (if it needs to be deleted at all).

**Comment by xet7** [comment]
Just adding more details:
- If there is at All Boards page feature Cards Count, those counts appear on card, and cards changes to be higher, and then random change of position of board icons starts happen, position of board icons change by itself every second
- If there is at All Boards page feature members of board feature, that makes card higher, and then random change of position of board icons starts happen, position of board icons change by itself every second

So I have disabled and hidden these features related code.
