### ISSUE TITLE
Feature Request: Keep done checklist items visible

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4215]
Checklist items marked as done disappear, respectively appear in activity. It would be fantastic if checked items would still be visible in the checklist but crossed out. So that you can keep track of the whole checklist and not just the items that are still open.

**Comment by helioguardabaxo** [comment]
Hi @Meeques 
You can use a toggle button on right upside to hide checked items.
shown checked items:
![Screenshot 2021-12-06 at 09-32-02 Quadro teste 2 - Kanban UFABC](https://user-images.githubusercontent.com/24301085/144846938-f6249c75-26dd-43f1-b624-b31ec0ca13cd.png)

hidden checked items:
![Screenshot 2021-12-06 at 09-32-21 Quadro teste 2 - Kanban UFABC](https://user-images.githubusercontent.com/24301085/144847000-9dc1fcb4-6faf-4fd1-b466-ee66c56329e4.png)

**Comment by Meeques** [comment]
oooh I thought this would hide the entire checklist. Thanks a lot!

**Comment by xet7** [comment]
@Meeques 

When you move mouse to top of some toggle (or something else), you should see explainig tooltip:

![tooltip](https://user-images.githubusercontent.com/15545/144854069-55edc728-9c1b-44b3-88b2-1fb78097e5e3.png)

**Comment by Meeques** [comment]
Great, I will include this in my manual. Thanks again!

**Comment by xet7** [comment]
@Meeques 

Is your manual online? Or can you send it to support@wekan.team so I can modify it to be WeKan manual at wiki?

**Comment by Meeques** [comment]
It's on our uni website but with restricted access. I will send it to you via mail.

**Comment by xet7** [comment]
@Meeques 

Yes. Thanks!

**Comment by Meeques** [comment]
It's online but with restricted access so I just sent it to you via mail.

**Comment by xet7** [comment]
@Meeques 

Thanks a lot! This helps me to think what kind of manual there should be for WeKan. I'll improve that manual and will sometime make it available in many languages.

**Comment by edkedk99** [comment]
@Meeques , thank you for asking this question. I was struggling with this issue too.
