### ISSUE TITLE
Rare Bug: Clicking to view Swimlane archive adds temporarily many empty Lists to board

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4216]
Hi,
there is Rare Bug: Clicking to view Lists or Swimlanes Archive adds temporarily many empty Lists to board. Then also removing lists does not work.

When webpage it is reloaded, that fixes that strange condition.

This Heisenbug will most likely disappear after some backend changes.

**Comment by Ben0it-T** [comment]
@xet7 
I think I got something. It's between `/client/components/sidebar/sidebarArchives.js` and `client/components/swimlanes/swimlanes.js`

`/client/components/sidebar/sidebarArchives.js` introduce `archivedRequested`
https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/client/components/sidebar/sidebarArchives.js#L1

https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/client/components/sidebar/sidebarArchives.js#L12-L22

In `client/components/swimlanes/swimlanes.js`, `archivedRequested` is reussed to show archived list if filter archive is active or archive is selected
https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/client/components/swimlanes/swimlanes.js#L150-L155

https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/client/components/swimlanes/swimlanes.js#L282-L287


`archivedRequested` as probably been introduced in the past to allow archived lists to be displayed when clicking on "Archive" (Lists or Swimlanes view)

Need to dig a little but changing 
`if (!(Filter.archive.isSelected() || archivedRequested)) `
to 
`if (!(Filter.archive.isSelected())) `
should do the job => archived lists won't be displayed when clicking on "Archive" (Lists or Swimlanes view)

**Comment by xet7** [comment]
@Ben0it-T 

Yippee you are genius bug fixer!

**Comment by Ben0it-T** [comment]
@xet7
I've made a quick test

In `client/components/swimlanes/swimlanes.js`
changing `if (!(Filter.archive.isSelected() || archivedRequested))` to `if (!Filter.archive.isSelected())`
do the job

After this change
`./find.sh archivedRequested` only returns `/client/components/sidebar/sidebarArchives.js` : L1 and L16
I think we could remove those 2 lines 

Do you want I send PR ?

**Comment by xet7** [comment]
@Ben0it-T 

Yes. Thanks!
