### ISSUE TITLE
undefinded added member to board

### ISSUE THREAD

**Issue by Emile840** [wekan/wekan#4222]
Sometimes, an admin user get notification email says that "undefined" added member "user name" to a private board "board name".
The problem is that no one from that private board's members has invited that user.
the bug was first noticed last September on weekan version 5.29. 
Is there anyone who has an idea about this issue ?

**Comment by Emile840** [comment]
@xet7,
I'm working on this issue, but there is something that I just can't figure out how it works. 
Beside the function "inviteUserToBard" in users.js file "https://github.com/wekan/wekan/blob/master/models/users.js", Is there anywhere else that a new user can be invited automatically to participate on the private board which can cause this bug ?

**Comment by xet7** [comment]
@Emile840 

Maybe try to search code:
```
cd wekan

./find.sh invite
```

**Comment by Emile840** [comment]
Yeah, i've already done that and on my comprehension, all codes that add a member to a board and that notify with "undefined added a member to a board" message, might come from the "inviteUserToBoard" function which is only called on a user's action.

**Comment by Ben0it-T** [comment]
@Emile840 
> Is there anywhere else that a new user can be invited automatically to participate on the private board which can cause this bug ?

A new user can be invited to participate on the private board at Admin Panel.
Doing that way reproduce notification email saying that "undefined added member _username_ to board".

Step to reproduce:

Step 1: At Admin Panel, invite new user and check a board 
<img width="669" alt="step-01" src="https://user-images.githubusercontent.com/37017213/146195638-2c1cbc41-aee9-443d-b8ac-0980d685ef30.png">

New user will be notified
<img width="469" alt="new-user-notification" src="https://user-images.githubusercontent.com/37017213/146195085-e9ce0fec-c78b-452e-a921-5ca1f6d144b7.png">

Bord activities, at this step
<img width="365" alt="board-activities-01" src="https://user-images.githubusercontent.com/37017213/146195358-a99fb33a-2015-492d-8035-102bd7f45426.png">

Step 2: New user creates account
<img width="266" alt="new-user-creates-account" src="https://user-images.githubusercontent.com/37017213/146196050-12e725f2-dbb2-4ad3-8ed2-368b3e228539.png">

<img width="491" alt="new-user-creates-account-2" src="https://user-images.githubusercontent.com/37017213/146196187-525c945a-c084-4d95-80bf-f3be1547c79a.png">


Board activities 
<img width="378" alt="board-activities-02" src="https://user-images.githubusercontent.com/37017213/146196459-3c823af1-95a2-4f14-8d27-063a1273fcc1.png">

If boardAdmin is "watching" that board
<img width="600" alt="notification-email-02" src="https://user-images.githubusercontent.com/37017213/146197511-989baf45-4d43-49ca-8d18-04764d8fbac7.png">


Hope this can help

**Comment by Emile840** [comment]
@xet7, @Ben0it-T 
Thanks for your comments, it's helped.
I finaly found the issue.

When a new user is invited to participate on a board (as shown above by @Ben0it-T for example)
- An invitation code is created (if not already exists) in database (collection : invitation_codes)
- When the user sign-up with password authentication mode, he'll give an invitation code that he received on his email, the user is saved in database and its corresponding invitation code is deleted from "invitation_codes" collection (in this case, all work well, the user will see all boards that has been invited to.
- But if the user sign-up with OIDC authentication mode, he'll not give an invitation code and at row number 1868 of user.js file (https://github.com/wekan/wekan/blob/master/models/users.js), if there're datas in "invitation_codes" collection, this piece of code will return an invitation object which belong to an other user because findOne with undefined code as value will return an object. So, the user will be created but with boards to which he was not invited to.
- I'm going to make a pull request with this correction : if is OIDC authentication mode then finding an invitation_code object is done by using "email field" instead of "code field"

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4245
