### ISSUE TITLE
Bug: Long Subtasks cannot be deleted [with video]

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4225]
Hi, I discovered a bug while trying to delete a long subtask. I used Firefox. If you need the exact version of wekan I can ask my colleague. 
I think the problem is that the whole subtask text is copied into the message that pops up asking you wether you are sure that you want to delete the subtask. In the Video I refreshed the page at a point where everything was frozen. Then I tried deleting the subtask in the minimized card display and it didn't work either. 
Kind regards!

**Comment by Meeques** [comment]
I will delete the video now because of data sensibility. If you need it I can temporarily upload it again or sent it to you.

**Comment by sleroq** [comment]
It's ugly, but I can delete the subtask on [public instance](https://boards.wekan.team/)
![2022-03-18_16-21](https://user-images.githubusercontent.com/52239427/159010452-65117974-fe0d-4515-b24d-33c71f5427a6.png)

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4446
