### ISSUE TITLE
Can't download attachments that have # in filename

### ISSUE THREAD

**Issue by CaptainPackers** [wekan/wekan#4227]
I am running a docker version of Wekan on a headless Unbuntu virtual machine, and it is working flawlessly for the most part. The only thing I can't get to work is the downloading of attachments. When I try I get a 403 error on my client machine.

I also have a snap instance installed on my client, and I have no trouble downloading attachments from this local wekan instance.

I don't think this is a bug. I'm just looking for community support.

Any suggestions would be appreciated.

Thanks

**Comment by xet7** [comment]
@CaptainPackers 

Do you have Nginx in front of Docker Wekan?
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config
Attachment file size: https://github.com/wekan/wekan/issues/2103#issuecomment-455014303

Or maybe just backup docker, and restore it to snap?
https://github.com/wekan/wekan/wiki/Backup

**Comment by CaptainPackers** [comment]
Hi Lauri,
Thanks for the quick reply.
It looks like switching to the snap version is going to work for me.
But I don't get how to export the docker database and import it to the new snap instance.
Any pointers there?

Regards,
Donald Lund

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by xet7** [comment]
@CaptainPackers 

https://github.com/wekan/wekan/wiki/Backup#backup-docker

https://github.com/wekan/wekan/wiki/Backup#restore-wekan-snap

**Comment by CaptainPackers** [comment]
I did a docker dump and zipped up the dump directory.

Then I'm trying
wekan.database-restore FULL_PATTH_TO_DUMP_ZIP_FILE/dump.zip

All the files in the zip were chmod to 0777 before the zip
The zip file has 777 permissions, as does the directory that contains it
It looks like the zip file is being parsed, but the last line of output is
Failed: open /home/myhome/dump/dump.zip: permission denied

Any thoughts?

Regards,
Donald Lund

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by xet7** [comment]
@CaptainPackers 

Unzip that .zip file, use mongorestore.

**Comment by xet7** [comment]
In directory where you are running mongorestore command, there is dump subdirectory that has raw database .wt files etc

**Comment by CaptainPackers** [comment]
no reachable server

do I have to run the command from the mongo snap directory?

**Comment by xet7** [comment]
@CaptainPackers 

Did you install WeKan MIT-licensed Snap?
https://github.com/wekan/wekan-snap/wiki/Install

Or alternatively WeKan Gantt Snap that has GPL licensed Gantt chart component?
https://github.com/wekan/wekan/issues/2870#issuecomment-721364824

**Comment by xet7** [comment]
Snap has MongoDB at port 27019:
https://github.com/wekan/wekan/wiki/Backup#restore-wekan-snap

**Comment by xet7** [comment]
Is WeKan running? If you installed snapd, did you reboot after installing snapd?

```
sudo snap enable wekan

sudo snap start wekan

sudo snap services
```

**Comment by xet7** [comment]
There should be running wekan.wekan and wekan.mongodb

**Comment by xet7** [comment]
@CaptainPackers 

Do you have some webserver at front of WeKan? Like Nginx? Check your settings:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by CaptainPackers** [comment]
This is the only text displayed on the page when I try to download the larger file:

Access denied [403]

----
And, as mentioned above, smaller files download OK.

**Comment by CaptainPackers** [comment]
I see there is an option to store attachements on server filesystem instead of mongodb in the compose file. I wonder if that would make a difference.

**Comment by xet7** [comment]
I'm currently coding solution for all attachments etc related issues. So I prefer to concentrate to that, and not debugging this.

**Comment by CaptainPackers** [comment]
OK, just an fyi, I looked at the embedded nginx.conf file inside the container and the client_max_body_size is set to 10G, so that should not be the issue.

Will your updates be easily integrated into my current docker instance of wekan?

Thanks for supporting Wekan. It is a wonderful tool, really helps my workflow and productivity.

**Comment by xet7** [comment]
I would presume updating will be easy enough.

**Comment by CaptainPackers** [comment]
I see you just released a never version of Wekan. Thanks for all your hard work in maintaining this wonderful app.

I just installed the new docker image of wekan, but I still get the "Access Denied [403]" page displayed (the only content on the page) when I try to download the same, large, Excel file that I just attached to a card. The file size is 2861 KB.

Since you have access to the code and are familiar with it, can you tell me what conditions cause this message to be displayed?

Thanks in advance.

**Comment by CaptainPackers** [comment]
I think I may have resolved this. The file name had the '#' symbol in it. When I removed the symbol from the file name, the file downloaded OK.

If you can just confirm that special characters in the file name will produce the "Access Denied [403]" error I think we can mark this resolved and close it.

Thanks again for Wekan

**Comment by xet7** [comment]
@CaptainPackers 

Yes special characters is a known problem in filenames.

Please do not close this issue, this is not solved yet, this still happens.

This will be fixed sometime in future because I'll fix this and other attachments related issues at once.

Related #4144 #3774

**Comment by ekrgb** [comment]
Hi,

I do have the same issue. Appreciate it when it is fixed in the future.
