### ISSUE TITLE
Comments from other users not visible after JSON import

### ISSUE THREAD

**Issue by akitzing** [wekan/wekan#4228]
• Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
• Did you test in newest Wekan?: Yes
• For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings? Existing install
• Wekan version: 5.63 
• Operating System: Linux
• Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
• Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik (reverse proxy only)
• MongoDB Version: 4.4.9
• Browser: Chrome 96
Problem: Comments from other users not visible after JSON import
Steps to reproduce:

In version 5.63 I made a json board export. When I import the dataset into a new wekan instance (also 5.63 and also 5.83), When assigning accounts, there are accounts that no longer exist. I have assigned these to me. In the board these comments (from the other user)) are not displayed. In the new instance there are only LDAP accounts.

**Comment by xet7** [comment]
@akitzing 

Are those comments in exported JSON file? Or do you have mongodump backup of that 5.63 whole database, are comments there?

**Comment by akitzing** [comment]
Yes

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
