### ISSUE TITLE
 Feature request: At Admin Panel, sort Organizations, Teams and People

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4231]
At Admin Panel, actually, Organizations, Teams are sort by createdAt -1.
_For People (users), I can't correctly identify how they are sorted_
It would by nice if :
- Organizations were sort by orgDisplayName
- Teams were sort by teamDisplayName
- People (users) were sort by username

For Organizations and Teams, indexes exist
https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/models/org.js#L220
https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/models/team.js#L217

Can we  change these indexes to "1" (ASC) ?
And then make some changes in client/components/settings/peopleBody.js  ?

If you are ok, I could have a look at this

**Comment by xet7** [comment]
@Ben0it-T 

Yes it's OK.
