### ISSUE TITLE
Issue: Admin user (boardAdmin) can't edit or delete others comments on cards

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4237]
* Did you test in newest Wekan?: Yes, WeKan 5.83
* Operating System: Debian 10
* Deployment Method: Snap
* Http frontend: Apache

Admin user (boardAdmin) can’t edit or delete comment owned by another user.
When the user is boardAdmin, he has a button to edit or delete a comment owned  by others:
https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/client/components/activities/activities.jade#L149-L153

However, this does not work...
Digging a bit I noticed that update or delete comments (CardComments) seems to be allowed only by the "owner"
https://github.com/wekan/wekan/blob/9b22e6da7a8f703abb567c6879bdda653a7f86b0/models/cardComments.js#L73-L84

**Comment by Ben0it-T** [comment]
Something like that, could probaby do the job
```
CardComments.allow({
  insert(userId, doc) {
    return allowIsBoardMember(userId, Boards.findOne(doc.boardId));
  },
  update(userId, doc) {
    return userId === doc.userId || allowIsBoardAdmin(userId, Boards.findOne(doc.boardId));
  },
  remove(userId, doc) {
    return userId === doc.userId || allowIsBoardAdmin(userId, Boards.findOne(doc.boardId));
  },
  fetch: ['userId', 'boardId'],
});
```

**Comment by xet7** [comment]
@Ben0it-T 

Related:
- [WeKan v5.29](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v529-2021-05-29-wekan-release) that has  https://github.com/wekan/wekan/commit/3908cd5413b775d1ee549f0a95304cf9998d3855
- [WeKan v4.39](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v439-2020-09-17-wekan-release) that has https://github.com/wekan/wekan/pull/3280

PRs welcome. Thanks!

**Comment by Ben0it-T** [comment]
@xet7
I did not completely understand...
"Impersonate one user" allows a Wekan administrator "to connect as" (then he can edit/delete/export...)

Should a boardAdmin be able to edit or delete a comment owned by other users ? or only Wekan admin ?

**Comment by xet7** [comment]
@Ben0it-T 

Permisson definitions:
- Impersonate one use is serious last-resort action of WeKan Admin, using it will be logged to datatabase
- WeKan Admin has access to Admin Panel has full access to any WeKan data via API
- BoardAdmin is the user that has created board. Can be any user that creates new board. Does not require being WeKan Admin.

This is about permissions of BoardAdmin and Normal User like at #3377 and #3642 , so let's ask them:

Hi @compumatter @Samunosuke @pgh2357 @csjjpm @rokokoh !

How these permissions in WeKan should work by default in your use cases?

**Comment by Ben0it-T** [comment]
The feature exists, it seems to have been introduced here #3201 (#3340).
I think we can fix it.

**Comment by Samunosuke** [comment]
A "board admin" can delete the whole board, then the "board admin" should also be able to delete cards or comments. The important thing for me is that a normal member (alias "worker") of the board can not delete the board or comments of other members.
In my use case...
A "board admin" should be able to:
- delete/rename the board
- move / delete / rename... swimlanes
- delete any comment / not just comments which he/she created
- change whatever is possible within the board

A board member "worker" should be able to:
- move cards
- comment cards 
- edit cards
- create cards
- delete the cards which he/she created
- add labels...

A board member should be **forbidden** to:
- delete cards which are created by other members / admins
- delete comments which were created by other members
- delete/move/add swimlanes 
- make any change to the structure of the board

**Comment by Ben0it-T** [comment]
@Samunosuke 
Thanks a lot for your answer.
It is extremely clear

@xet7, @Samunosuke 
If we extrapolate,
currently only a Wekan Admin can add a team (or an organization) to collaborate on a board. 
Can we allow a boardAdmin to do the same?
This could save him time by directly adding a team/org to collaborate rather than adding users one by one.

**Comment by xet7** [comment]
@Ben0it-T 

Well, it depends. In theory it should work like this, but I did not test this yet:

- If BoardAdmin is part of Team/Org, BoardAdmin should be able to add those Teams/Orgs to board.
- If BoardAdmin is not part of some Team/Org, BoardAdmin should not be able to add that Team/Org to board.
- At All Boards page should be visible only those Teams/Orgs some user is member of.
- WeKan Admin can add People to Team/Org.

But if someone has some different use case, please add more details to comment to this issue.
