### ISSUE TITLE
it's possible using CalDav for calendar?

### ISSUE THREAD

**Issue by manuelsongokuh** [wekan/wekan#424]
i write title..

**Comment by mquandalle** [comment]
Well, writing a title is not enough. You should explain what you mean exactly, why you want this feature, and how you plan to use it.

**Comment by manuelsongokuh** [comment]
hello,sorry me, for to use wekan needs add calendar share (protocol icalendar maybe use caldav..?)
when i add "to do list" and with calendar share or build-in new calendar and future will be export or share public or private..

I want not calendar of Google, I want calendar original from wekan, will could be export calendar share ok?

sorry for my english..

then what do you think about calendar for wekan? it's be COOL?
:-)

**Comment by manuelsongokuh** [comment]
see example of kanboard there is calendar cute.. see demo of kanboard
http://kanboard.net/demo

**Comment by manuelsongokuh** [comment]
i check trello don't have it...

**Comment by manuelsongokuh** [comment]
sorry me maybe i-m confusing for calender..

then

-1
i wish wekan can create feature calendar original for wekan. this is for my office job will use it.
because more application for calendar is not work correct.

2-
add feature for invite friend, also permission (only read, write, public, private, private with invites,etc)

this calendar is very necessary and helpful for my office jobs for wekan.

i was wrong to thinking about caldav:
i wante to say for CALDAV server in wekan, to share all clients of wekan registers.
so now i'm understand that is big time for create code caldav a lot.. i think this is can cancel feature for caldav, becasue wekan will creare new calendar own and original, for this is sufficient but calendar will be complete (permissions, design UI cute, export file ICS for other app calendar..etc) it is ok?

did you see other example? :
 http://restya.com/board/demo.html
http://kanboard.net/demo

first for all:
i wont to share with google calendar ok?
wekan calendar original.
if who want to use with google then wekan will export ICS or share direct google calendar read only..

**Comment by computerinfo21** [comment]
I would also find a calendar very helpful. There are libraries that might allow the functionality without completely writing a caldav implementation from scratch.
i.e. https://github.com/mikedeboer/jsDAV

**Comment by manuelsongokuh** [comment]
good idea for jsDAV but i hope team wekan will be add feature calendar..thank you

**Comment by simdol** [comment]
@mquandalle  I would very much like the feature of the CalDav support. For instance, I have external CalDav server where I have all of the events in one place. If I were to be able to add a say, 'to-do list' with specific due date, I would like it to be able to be synced into my calendar (add a new event into that due date in the calendar).  By doing this, the productivity could be exponentially improved and usablity as well (considering it can be synced across any CalDAV compatible devices.)

If you could please consider creating an app for this feature, I would be thrilled.

Thank you.

**Comment by lenucksi** [comment]
Another CalDAV use case could be the following:
 - I have an existing CalDAV resource containing ToDo items.
 - I would like to have them displayed and usable in Wekan.
    - Dates or priorities added to them in Wekan should be added to them in the CalDAV resource as well, allowing them to be displayed / scheduled in a normal calendar as well.
    - Dates or priorities added in a normal calendar should be mapped to Wekan as well. This would likely require some sort of user configurable mapping for each CalDAV source.
 - This would allow me to manage CalDAV sources (which are really common) in a Kanban board / visual way as well as allow me to profit from classic calendar features.

**Comment by xet7** [comment]
Moved to #808
