### ISSUE TITLE
Docker-Compose Does Not Pull New Image

### ISSUE THREAD

**Issue by CaptainPackers** [wekan/wekan#4241]
Hi,
I've followed the posted upgrade procedure using docker-compose at

https://github.com/wekan/wekan/wiki/Repair-Docker#6-trying-to-upgrade-wekan

but the wekan docker image does not update. When I start wekan again and check the version, it's still shows the old version.

What else can I do to upgrade wekan?

Thanks

**Comment by CaptainPackers** [comment]
Now I'm getting the following error messages:

ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 92, column 3
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 125, column 5

here's line 92:
  wekandb:

and line 125:
    container_name: wekan-app

**Comment by CaptainPackers** [comment]
The quay image did not work for me. When I updated and uncommented the wekanteam/wekan:v5.84 line the update worked.

How can I donate to this project?

Thanks

**Comment by xet7** [comment]
@CaptainPackers 

Donate/Support page is at https://wekan.team/commercial-support/

**Comment by xet7** [comment]
In general, I'm working to make updating easier.
