### ISSUE TITLE
Release v0.10

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#425]
Hi,

I've released the [first release candidate](https://github.com/wekan/wekan/releases/tag/v0.10.0-rc1) of Wekan v0.10. The release link contains the Sandstorm `spk`, the Nodejs `tar.gz` application. The official Docker image is also available on the [DockerHub](https://hub.docker.com/r/mquandalle/wekan/).

You can [read the release notes here](https://github.com/wekan/wekan/blob/master/Changelog.md#v010). This release includes some contributions from @AlexanderS, @dferber90, @fisle, @floatinghotpot, @FuzzyWuzzie, @mnutt, @ndarilek, @SirCmpwn, and @xavierpriour, thank you all very much.

Issues remaining before the final v0.10 are tracked using the corresponding [GitHub milestone](https://github.com/wekan/wekan/milestones/Release%200.10).

We need your help to test the application, report bugs, and [translate the new features to your local languages](https://www.transifex.com/wekan/)!

If you don’t want to install Wekan on your own server, I’ll deploy an instance on https://wekan.io sometime in the coming days.

**Comment by FuzzyWuzzie** [comment]
Woo!

**Comment by mfaure** [comment]
Cool !

Here is the correct link for the [Release Notes](https://github.com/wekan/wekan/blob/master/Changelog.md#v010) (file is Changelog.md instead of History.md)

**Comment by mquandalle** [comment]
Thanks @mfaure, fixed.

**Comment by floatinghotpot** [comment]
@mquandalle some defects are found, one of them is introduced by myself. here is the bugfix patch. https://github.com/wekan/wekan/pull/426

And, the newly translated zh-CN is still not pulled from Transifex. Any review process required?

**Comment by anselal** [comment]
I think that the email notification feature is the important update in this release. I sure will give it a try.
Great work to all of you !!!

**Comment by mquandalle** [comment]
I thought I pulled zh-CN translations, but I may have done something wrong. No, there isn’t any review process required for now. Anyway don’t worry @floatinghotpot there is still work to be done for v0.10 (including merging your PR!) so I’ll release more release candidates in the coming days (I’ll pull translations from Transifex before every RC).

**Comment by mquandalle** [comment]
You can now test the next RC using the deployed instance at https://wekan.io/sign-in (it may be a little slow as the server is located in France, I will configure a CDN).

**Comment by mquandalle** [comment]
[Released v0.10-rc2](https://github.com/wekan/wekan/releases/tag/v0.10-rc2)

**Comment by mquandalle** [comment]
Released [v0.10-rc4](https://github.com/wekan/wekan/releases/tag/v0.10.0-rc4) which includes some bug fixes, an adapted UI for mobile, and the possibility to export a board to JSON. It’s deployed at https://wekan.io/sign-in

**Comment by mquandalle** [comment]
[Released](https://github.com/wekan/wekan/releases/tag/v0.10.0)

**Comment by nata-g** [comment]
:+1:  :+1:
