### ISSUE TITLE
WeKan v5.88:Templates are Missing, Error: Site not Found "/templates" is missing in the URL

### ISSUE THREAD

**Issue by Dac3r** [wekan/wekan#4253]
When accessing the templates site it is showing "site not found"

he opens this url: https://domain/b/YZCaNGkXorLLxsLjE

when i put in this url manual https://domain/b/YZCaNGkXorLLxsLjE/templates it is working.

By clicking on "templates" the "/templates" is missing in the url.

updated from 5.87 to 5.88
when i downgrade from 5.88 to 5.87 everything is working fine

**Comment by xet7** [comment]
Thanks! I will fix this in near future.
