### ISSUE TITLE
Bug: Card Color is not displayed with dark theme

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4254]
Hi, we have the newest version of wekan installed with an own instance at our university. 

When I select a color for a card it should be visible on the board as a rose/red/blue/whatever minicard. As you can see in my screenshot, this doesn't work with the dark theme. 
![BugColorCard](https://user-images.githubusercontent.com/92315677/147062258-50a90ebf-71bd-4fb4-afe9-e5f08c4afba2.jpg)

Of course, when I open the card, the selected color shows in the title.

Kind regards and thanks for all the work you're putting in!

**Comment by Go-rom** [comment]
Hello,

i think you are mistaken about the theme.

Your screenshot shows Moderndark theme and not dark theme.
Plus, i can reproduce this bug with the Moderndark theme, not the dark one.

**Comment by xet7** [comment]
Can someone test it and make pull request to some change in this file?
https://github.com/wekan/wekan/blob/master/client/components/boards/boardColors.styl#L747

How to make pull request:
https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

**Comment by xet7** [comment]
Or alternatively, add comment to this issue, mentioning what line to change in that boardColors.styl?

**Comment by Go-rom** [comment]
Issue happens with the following themes : relax, natural, modern and modernblack

**Comment by xet7** [comment]
@Go-rom 

Yes, I tried some change so it's better on dark themes. I'll try some more changes.

**Comment by xet7** [comment]
@Go-rom 

That comment counter is bold red on purse for that using client.

**Comment by xet7** [comment]
The explanation for relax theme is, that red color makes WeKan users more relaxed, and that red bold emphasis shows more clearly that there is a comment in that card.

**Comment by Go-rom** [comment]
Got it, thanks for the explanation 👍

**Comment by xet7** [comment]
I'm currently making changes to many themes, so that card and list colors would be visible.

**Comment by Go-rom** [comment]
All right, while you're polishing some themes, would you please make darker the text displayed inside the comments ?

Only the dark theme is affected by this issue, see https://github.com/wekan/wekan/issues/4293

Thank you very much

**Comment by Meeques** [comment]
Thank you so much!

**Comment by jghaanstra** [comment]
@xet7 The commit that was pushed to solve this bugs has some undesired side effects, at least in my opinion. Cards that do not have a set color are white. This is not what you expect from a dark theme. Is there a way to set the default color of cards to a darker shade (the original #444444 for instance) while keeping the ability to overwrite it with a card specific color.

Als the headers of the even columns are now unreadable on version 5.95.0. See:

![image](https://user-images.githubusercontent.com/4710062/149972256-1ca2c805-8daa-4c96-8c6e-7839982bff93.png)

**Comment by xet7** [comment]
@jghaanstra 

Can you figure out from https://github.com/wekan/wekan/commit/218ddf03bc109b954d1fe741d1aa533467b51a4d what did I do wrong?

**Comment by jghaanstra** [comment]
> @jghaanstra
> 
> Can you figure out from [218ddf0](https://github.com/wekan/wekan/commit/218ddf03bc109b954d1fe741d1aa533467b51a4d) what did I do wrong?

I already did but I dont know how to solve it without breaking the custom color card again.

For the mini card you comment out lines 922 and 923 which sets the background color and font color on the minicard. Adding it back would prevent minicard-<<colorname>> to set the card color. So the solution that is choosen for adding custom card colors does not allow for theme card colors.

And for the header you commented out line 871, probably when trying to fix the custom column color but only commeting out line 873 which you also did would have solve that already. So removing the slashes on line 871 should at least fix the column color on darkmodern theme.

**Comment by xet7** [comment]
@jghaanstra 

Hmm, I did not quite understand that yet, I think I need to drink some more coffee. Can you send pull request? It would help a lot.

**Comment by xet7** [comment]
@mfilser 

Hey do you undestand this stuff?

**Comment by mfilser** [comment]
@xet7
I didnt get the right path now, but also just read and didn't test it.
I could give it a try the next days...

**Comment by jghaanstra** [comment]
PR https://github.com/wekan/wekan/pull/4308 fixes the moderdark theme basis color for minicards but breaks the custom minicard color functionality of the minicard again.

**Comment by mfilser** [comment]
It's depends so much on user which colors are used. It's a never ending loop of changing theme colors. I think i can change theme's 365 days a year 🤣

**Comment by xet7** [comment]
> PR #4308 fixes the moderdark theme basis color for minicards but breaks the custom minicard color functionality of the minicard again.

Huh what?

**Comment by jghaanstra** [comment]
> > PR #4308 fixes the moderdark theme basis color for minicards but breaks the custom minicard color functionality of the minicard again.
> 
> Huh what?

A quick fix is changing [this code](https://github.com/wekan/wekan/blob/033a5d8186eb0c05137c1a3bce6feb411ca73a70/client/components/cards/minicard.styl#L237) to:

```
minicard-color(background, color...)
  background-color: background !important
  if color
    color: color !important //overwrite text for better visibility
  &:hover:not(.minicard-composer),
  .is-selected &,
  .draggable-hover-card &
    background: darken(background, 3%)
  .draggable-hover-card &
    background: darken(background, 7%)
```
The added `!important` statements overwrite the color set by the theme.

A proper fix would be to implement the suggestions made here: https://github.com/wekan/wekan/issues/3086 (for which I actually donated for back in november 2020 :-) ). They way theming now works is very inflexible and does not allow much user customization.

**Comment by C0rn3j** [comment]
I am not sure if this is intended behavior or a new bug - is the moderdark theme not supposed to show card color?

It's the only theme that doesn't.

**Comment by jghaanstra** [comment]
Works for me on version 6.68.0. It was fixed some time ago, what version of Wekan are you using?

**Comment by C0rn3j** [comment]
6.09.0... apparently the snap autoupdates broke a long while ago
