### ISSUE TITLE
Wekan v5.88: Duplicate Board strange issue

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4260]
WeKan 5.88
Operating System: Debian 10
Deployment Method: Snap
Http frontend: Apache

Duplicate a board creates a new board but doesn't show/open it. Need to refresh page to show the new board.
Downgrading from 5.88 to 5.87 and Duplicate Board is working fine

**Comment by Ben0it-T** [comment]
This is related to recent changes in the selector in `server/publications/boards.js`
https://github.com/wekan/wekan/blob/a37856c937c403f71aad6535fa08aea411f611db/server/publications/boards.js#L36

When a board is cloned or created from a template, the new `_id` is outside the selector.
By making the following changes, it seems to work again (_I'm not very familiar with Publish and Subscribe_).
In `wekan/models/boards.js`, `copy()` (L569), add `return _id` to send it back to the client 
```js
Boards.helpers({
  copy() {
    ...
   return _id;
  },
```

In `client/components/boards/boardBody.js`, `'click .js-clone-board'(evt)` (L230)
Subscribe to the new board
Adding `subManager.subscribe('board', res, false);`
```js
'click .js-clone-board'(evt) {
  Meteor.call(
    'copyBoard',
    this.currentData()._id,
    {
      sort: Boards.find({ archived: false }).count(),
      type: 'board',
      title: Boards.findOne(this.currentData()._id).title,
    },
    (err, res) => {
      if (err) {
        this.setError(err.error);
      } else {
        Session.set('fromBoard', null);
        subManager.subscribe('board', res, false);
        Utils.goBoardId(res);
      }
    },
  );
  evt.preventDefault();
},
```

in `client/components/lists/listBody.js`, `'click .js-minicard'(evt)` L(668)
Subscribe to the new board
Adding `subManager.subscribe('board', _id, false);`
```js
...
Meteor.call(
  'copyBoard',
  element.linkedId,
  {
    sort: Boards.find({ archived: false }).count(),
    type: 'board',
    title: element.title,
  },
  (err, data) => {
    _id = data;
    subManager.subscribe('board', _id, false);
  },
);
...
```

@xet7 
When you'll have time, could you take a look 
(_I'm not very familiar with Publish and Subscribe_).

**Comment by xet7** [comment]
@Ben0it-T 

Thanks! I'll look.

**Comment by xet7** [comment]
@Ben0it-T 

> When you'll have time, could you take a look
> (I'm not very familiar with Publish and Subscribe).

It looks like you are familiar enough, you added to correct places stopping subscriptions so that there will not be errors. :slightly_smiling_face:
