### ISSUE TITLE
Feature Request: Import all comment reaction emojis from Trello, and have any emoji in WeKan comment reaction

### ISSUE THREAD

**Issue by evolverine** [wekan/wekan#4261]
Add the possibility to react to comments with (multiple) emojis, like Trello currently does.

Reasoning: as trivial as it may sound, one of the biggest blocks for us to transition our Trello boards to Wekan is the presence of this feature, of replying with emojis to comments. We use it extensively, and have specific meanings for many emojis (comment read, agreed with, actioned, deal with later, and so on), and would really like the current emoji comments to follow us through any transition to another system.

(I looked in the issue tracker for this feature, sorry if it exists and has a different name.)

**Comment by xet7** [comment]
@evolverine 

You can already react to comments with multiple emojis in newest WeKan:

![multiple-comment-emoji](https://user-images.githubusercontent.com/15545/147394100-bcd80ce9-d1c9-49d5-b866-ff775cda3ff1.png)

Do you mean emojis would need to be imported from Trello?

Or please provide more details about what you actually would like to have?

**Comment by xet7** [comment]
Currently WeKan has these emojis in popup. Maybe it would also need option to add any other emoji too with emoji text code.

![more-emoji](https://user-images.githubusercontent.com/15545/147394290-9547cce3-1e7f-43f0-b9f6-fbea51a02919.png)

**Comment by evolverine** [comment]
Thank you for the response, I'm very glad that there's already an implementation of this! Indeed, it would be great if all emojis were present to be used (and imported from Trello). Is there an open issue for that? If not, we can transform this one to represent that feature request.

**Comment by xet7** [comment]
This is related to [Mass Import/Export/Sync at Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-r-open-source-kanban-board-with-mit-license/HJAiF3uRSJHGeeRdE)
