### ISSUE TITLE
Wekan v5.88/v5.89: Creating board from Template. Template list not opening 

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4263]
When create a new board from template, clicking  "Template" doen't open the board template list
<img width="308" alt="create-board-from-template" src="https://user-images.githubusercontent.com/37017213/147412445-532786f6-a864-43a0-8bfa-aa89b4d3cb7a.png">

This is related to recent changes in the selector in server/publications/boards.js
https://github.com/wekan/wekan/blob/dbe0b4922fd6dc6962bd644eca4859a040eda6ee/client/components/lists/listBody.js#L577-L579
The template board is out of the selector

This seems to do the job
```js
    if (this.isTemplateSearch) {
      //board = Boards.findOne((Meteor.user().profile || {}).templatesBoardId);
      board._id = (Meteor.user().profile || {}).templatesBoardId;
    } else {
```
Just `board._id` is needed
https://github.com/wekan/wekan/blob/dbe0b4922fd6dc6962bd644eca4859a040eda6ee/client/components/lists/listBody.js#L597-L599

Is it also possible to temporarily put back  the selector  in `boardsList.js` in order to prevent the display of "Templates" miniboard 
https://github.com/wekan/wekan/blob/dbe0b4922fd6dc6962bd644eca4859a040eda6ee/client/components/boards/boardsList.js#L135-L144

Put back to 
```js
  boards() {
    let query = {
      // { type: 'board' },
      // { type: { $in: ['board','template-container'] } },
      $and: [
        { archived: false },
        { type: 'board' },
        { $or:[] }
      ]
    };
```

**Comment by xet7** [comment]
@Ben0it-T 

What I'm actually try to do is take to use use all template-container boards where user is member of template-container board:
https://github.com/wekan/wekan/issues/3313#issuecomment-1001187003

template-container boards are visible on purpose.

**Comment by Ben0it-T** [comment]
@xet7
Ok. Thanks for the feedback. Noted

**Comment by Ben0it-T** [comment]
@xet7 
A huge thank you for your great availability and your flawless reactivity.
