### ISSUE TITLE
API question: how to get the full attachment URL?

### ISSUE THREAD

**Issue by ZRunner** [wekan/wekan#4272]
## Issue

Using the wekan API I found how to get an attachment URL based on its ID, for example when I want to display a cover image.
But the url seems to be incomplete, as I get a 403 response when trying to access it.

According to the client website, the URL needs a "token" parameter to be displayed. But this token is not the wekan API token, and I could not find anywhere in the code where it was defined. Neither in the API documentation. Not even in the website local storage/cookies.

Could you tell me where to find this token to correctly display an image, assuming that it is possible? Thanks!

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: No (version 5.83.0)
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly? yup
* Operating System: Hosted on a Synology NAS
* Deployment Method(Snap/Docker/Sandstorm/bundle/source): Docker
* Node.js Version: 12.22.7
* MongoDB Version: 4.4.9-rc0
* Wekan works on newest desktop and mobile webbrowsers that support Javascript. What webbrowser version are you using? Firefox 95.0.2

**Comment by xet7** [comment]
@ZRunner 

Using API with attachments is not implemented yet. Also token probably will be moved from URL to headers.

Moved to #1482
