### ISSUE TITLE
Unable to disable "Show sum of fields at top of list"

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan#4274]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Operating System: linux
* Deployment Method(Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node.js Version: 12.22.8
* MongoDB Version: 4.2.17
* Wekan works on newest desktop and mobile webbrowsers that support Javascript. What webbrowser version are you using? Firefox 95.0.2

**Problem description**:
1. Create a custom field (type number)
2. Uncheck "Show sum of fields at top of list"
3. Save
4. Edit the custom field

The box is enabled whereas it should be disabled

![image](https://user-images.githubusercontent.com/8069239/148037122-669556b1-7004-47f8-846b-cf7c5a36bb14.png)

**Comment by hatl** [comment]
In the latest version `v6.09`, the field is shown on top of the list, but the sum is missing.
Maybe the same root cause?

**Comment by xet7** [comment]
In Progress. Not ready yet.

Moved to #3796
