### ISSUE TITLE
Template "Board not Found"

### ISSUE THREAD

**Issue by marcuskki** [wekan/wekan#4275]
Somewhere between 21DEC and now (v5.90) on some of our wekan user-accounts the template board is missing. By clicking on the template URL, its still opening the correct URL like before (f.e. https://todo.kki-intranet.de/b/RxhGQveqGHvieSuYD/templates) but then only a "board not found" site appears.

When creating a new card, also no templates are selectable anymore

**Comment by marcuskki** [comment]
Updated to 5.91, template page is still not working

**Comment by marcuskki** [comment]
Is there at least a way to recover it for 1 user and/or extract the information to import it to another user? we urgently need the information from one template board

**Comment by xet7** [comment]
@marcuskki 

You can use nosqlbooster or other mobgodb gui https://github.com/wekan/wekan/wiki/Backup to add that user id to that board members id list

**Comment by marcuskki** [comment]
thats beyond fromwhat i can do, is this bug gonna be fixed with any future update so the templates are accessible again?

> @marcuskki
> 
> You can use nosqlbooster or other mongodb gui https://github.com/wekan/wekan/wiki/Backup to add that user id to that board members id list

**Comment by xet7** [comment]
@marcuskki 

Depends if someone orders some hours of Commercial Support at https://wekan.team/commercial-support/ and sends database backup and details of what user or board or template needs to be recovered, so that I can see that bug myself and fix it and recover that board.

**Comment by modem7** [comment]
Getting this bug myself. 

Are there any log files we can send?

**Comment by xet7** [comment]
If someone has some logfiles, those can be sent to support@wekan.team

**Comment by xet7** [comment]
Anyway, most likely this will be fixed in future WeKan update.

**Comment by ktecv2000** [comment]
Hi, any update for this issue?

**Comment by xet7** [comment]
@ktecv2000 

Templates are not fixed yet. I have kind of promised at this month, to try to code some other features, and try to make possible to upgrade Snap Stable to newest WeKan.

Fixing templates is on Roadmap, yes.
