### ISSUE TITLE
Normal board users cannot create new lists or labels -- by design?

### ISSUE THREAD

**Issue by RyanHecht** [wekan/wekan#4276]
My team is used to Trello, where regular board members are able to add new lists and labels. It seems like as of [this commit](https://github.com/wekan/wekan/commit/4a205fcfcb40438faead3bf8973b10b8e42974f0#diff-c5114b02de667f7c0e971e93819f9224fb960227cb1bac0acef72ba78dcc2260), list creation is restricted to board admins, and as of [this commit](https://github.com/wekan/wekan/commit/0e43a5561b5c9cd7bb627cb1b44274f2ff72b1f6#diff-c0a17b234c360d5b475e7cd6a3e3c1e6ef9b920fc932ab9a0a5f0be2d4460f5e), label creation is restricted to board admins. What was the logic behind deviating from Trello's behavior here? Is there any chance you would reconsider this design? 

Trying to determine whether it's worth forking to remove the `isBoardAdmin` check to be more in-line with what my users expect :)

**Comment by xet7** [comment]
@RyanHecht 

That logic of normal user is from WeKan users #3377 

Changing it depends is there funding for #3022 

It is also possible to send pull requests to WeKan for additional options https://github.com/wekan/wekan/pulls

Forking would be a lot of extra work, I recommend contributing directly to WeKan:
https://blog.wekan.team/2018/02/benefits-of-contributing-your-features-to-upstream-wekan/

**Comment by xet7** [comment]
In the future, more Trello features will be implemented in, so that it will be possible to import most data from Trello to WeKan with mass import.

**Comment by RyanHecht** [comment]
I could give a go at implementing a global environment-variable-backed config option such as `EXPANDED_MEMBER_PERMISSIONS` that would seek to more closely mimic Trello's normal board member permissions -- could you point me in the right direction for how to get started on implementing a new config option?
