### ISSUE TITLE
Possible Bug: Send message to Person that is @-mentioned

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4277]
Hi there! I am using the newest version of WeKan with our own instance at our univerity (it is continually and automatically updated) and the current version of Firefox.
As I observed with a colleague, the @-mention function will not inform the mentioned person in any way that they got mentioned in a card. I don't quite understand what's the benefit of the feature if the user is not nudged in any way. 
Thank you!

**Comment by Ben0it-T** [comment]
@Meeques 
Could you try with the latest Wekan (5.91)
User mentions now return "@username (full name)" -> if `username` contains any word character `[a-zA-Z0-9_]` a dot `.` or a hypen `-`, it should fire a notification
(#4273 and #4057)

**Comment by Meeques** [comment]
@Ben0it-T 
I tried with the newest Version of WeKan and the newest Version of Firefox. If I @-mention board_members oder card_members, the notification works just fine. If I want to mention a person with username, there is no notification either on the board or sent out via mail.

**Comment by Ben0it-T** [comment]
@Meeques 
I did a quick test (_Wekan 5.91 / debian 10 / snap / apache_)
If username contains word characters ( `a-z` `A-Z` `0-9` `_`) `.` or `-`, it works

<img width="573" alt="user-mention" src="https://user-images.githubusercontent.com/37017213/149464804-5049882d-eacd-4038-9fad-bbe4ee4e0229.png">

<img width="421" alt="user-mention-notification" src="https://user-images.githubusercontent.com/37017213/149464844-09ca642a-c824-463d-8f4c-d360c526f023.png">

<img width="690" alt="user-mention-mail" src="https://user-images.githubusercontent.com/37017213/149464869-def1bb19-472d-4665-9594-448a28abc38b.png">

Could you  give me an example of username ? or a screenshot ?

**Comment by Meeques** [comment]
@Ben0it-T Thank you for your time!
It works now with a colleague. He's receiving an email. 
![#4277moodlenet_2](https://user-images.githubusercontent.com/92315677/149495187-619f900b-9c55-486f-85f1-dfed8425b3eb.jpg)

If I mention myself, I don't get any notification.
![#4277MoodleNet](https://user-images.githubusercontent.com/92315677/149495279-978153cd-7b85-4871-8567-83d1d528fdfd.jpg)

If I mention a colleague with a space in her username, it doesn't work either.
![#4277moodlenet_3](https://user-images.githubusercontent.com/92315677/149495390-5b076c87-79b1-4f7e-9778-faefd03b8aad.jpg)

I imagine that changing the username would help. But they can't change it themselves.

**Comment by Ben0it-T** [comment]
@Meeques 
Great !

> If I mention myself, I don't get any notification. 
This is normal !
https://github.com/wekan/wekan/blob/2ac5f0b2d71cd057b9f2672ca16723648fa14b5a/models/activities.js#L211-L214

> If I mention a colleague with a space in her username, it doesn't work either.
I know, personally, I won't be able to do much about it ...
Probably a regex ninja will be able to...
