### ISSUE TITLE
Card color

### ISSUE THREAD

**Issue by ceymard** [wekan/wekan#428]
Just a little suggestion ;

It would be nice to be able to have different background colors for cards.

The idea would be that in the real world, we sometimes use post-its of different colors to symbolize different things (priority, type, etc.). It would be then nice to have this feature on top of having labels for a more visual feedback of what a card represents.

Thoughts ?

**Comment by xavierpriour** [comment]
In Trello, I use a Chrome extension that uses the label color as background color - and mixes them when you add multiple labels.

What do you think about it?

**Comment by ceymard** [comment]
This could be a nice idea, but wouldn't it be better if it was built-in instead of having to use an extension ?

How hard would it be to convert this extension to Wekan ? Is it something like userstyle ?

**Comment by xavierpriour** [comment]
Oops, sorry I was unclear.

I meant building it into Meteor, but using the label color as background color, instead of adding another parameter.

Don't know if we should make it the only behavior, or make it a parameter (and in that case, should it be board or wekan setting? And what should be the default?)

**Comment by ceymard** [comment]
I'm not sure. I like the idea, however I have a little problem with it conceptually ;

A card 

* can only have *one* background color.
* can also have *several* label

Therefore, we are trying to convert *several* to *one*, potentially losing visual "information" in the process.

I think the character of having a *unique* color for the card (as opposed to *multiple* labels) hints to the fact that in the end, they're not the same thing and can't have the same purpose -- or have one derived from the other.

In the way I was thinking of using them, for instance, I was going to leave most of them blank (with labels) and have a few colored (like deadlines ? or something else ?).

Anyway, this is just food for thought, I don't have a very definite opinion on the subject.

**Comment by jonathan-chin** [comment]
+1 card background and / or list background will make organization much easier

**Comment by sirup** [comment]
+1 - This would be a really nice feature.
I would love to be able to look at the board and know to which category the cards (tasks) belong.
Like mentioned before it would be equal to different colored post its in real life. 

It would be the class .minicard which would be needed to be changed.
I Guess here: \wekan-devel\client\components\cards\minicard.styl

**Comment by AlexanderZobkov** [comment]
+1 This would be a really nice feature.
@xet7 Why this issue has been closed?

**Comment by xet7** [comment]
@AlexanderZobkov 

This issue is open, as you see at top of this webpage in green. Above closed issue 1168 mentions this issue.

**Comment by AlexanderZobkov** [comment]
Ah, yes, Thanks, My mistake.

**Comment by d3dbit** [comment]
+1  This would be a great feature.

**Comment by xet7** [comment]
Card color, todo:

![colored-cards](https://user-images.githubusercontent.com/15545/41798133-3017b866-7675-11e8-832a-25759bf02225.png)

**Comment by Bertrandcoic** [comment]
Hi,
Being able to define the color of the card is indeed very interesting, added to the lables (for instance, the color of the card could represent project streams such as engineering, process, IT) in addition to the labels that could define criticity and urgency; or the opposite, the card color representing the criticity while the labels are linked to the steams

I'm sorry but with your comment on june 22nd, I didn't understand if it was possible yet. I tried but could'nt succeed so far. 
Could you please detail, in the case it is possible, how to proceed ?
Regards

**Comment by xet7** [comment]
@Bertrandcoic 

This issue is still open, so this feature is not in Wekan yet. Also, in previous comment I said "todo" and there is mockup. It is not in Wekan yet.

**Comment by Bertrandcoic** [comment]
thx a lot, wait for it then :-)

**Comment by DrXadium** [comment]
I support this request as well, right now having all the cards be white  makes itr very hard to quickly distinguish priorities, even with labels. 

To give you an idea of how colors and lablels might work together, this is what a colored card looks like in the kanban rpgram I am currently using to supplement Wekan (Portable Kanban, sadly no longer updated)

![image](https://user-images.githubusercontent.com/39009823/50767796-335c1d00-124c-11e9-824b-25480386bd21.png)

**Comment by timdonovanuk** [comment]
If you ended up like me here trying to find out how to change card colours it's "documented" via a PR title: https://github.com/wekan/wekan/commit/3368ebf067779d1f306a2447e2357e34213f0126
