### ISSUE TITLE
Feature Request: Allow lists to have no name

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4284]
As a user and teacher, I want to display content without having to create a list to save time when I just need a single card per list. The card title will then kind of replace the list title.

**Comment by Ben0it-T** [comment]
@Meeques 
Could you test with `&nbsp;` as list title ?

<img width="621" alt="lists-with-no-name" src="https://user-images.githubusercontent.com/37017213/149166937-b1f73861-b493-4b1b-8291-99f5ac0bb20d.png">

**Comment by Meeques** [comment]
That works! Thank you so much!
