### ISSUE TITLE
Estonian language support

### ISSUE THREAD

**Issue by andrewlytvyn** [wekan/wekan#4287]
How to add Estonian language to program?

**Comment by xet7** [comment]
@andrewlytvyn 

Thanks! I accepted these at https://transifex.com/wekan/wekan

- Estonian (Estonia) et_EE
- Russian (Ukraine) ru_UA
- Ukrainian (Ukraine) uk_UA

What are those language names in those languages? What should be visible in WeKan change language menu?

**Comment by xet7** [comment]
@andrewlytvyn 

For some of those languages, I copied from existing translations:
- Russian => Russian (Ukraine)
- Ukrainian => Ukrainian (Ukraine)

You can add changes where those are different. Thanks!

**Comment by xet7** [comment]
> @andrewlytvyn
> 
> What are those language names in those languages? What should be visible in WeKan change language menu?

Nevermind, I already figured out language at https://github.com/wekan/wekan/commit/ac85e00e0a99574499786ddf97823dcf2802a47f and https://github.com/wekan/wekan/commit/30131ffc20173d222cb02b283f38a8c0d6a28ccc by using Google Translate.
