### ISSUE TITLE
Bug: Official board.wekan.team is unavailable, error 524 - timeout / server IP address could not be found.

### ISSUE THREAD

**Issue by vdst** [wekan/wekan#4290]
## Issue

The official board.wekan.team website is currently down.
It has been unreachable for a day or two at the time of writing this issue.
This includes access to personal account, boards and their content.
It also includes the "Roadmap (read-only board at WeKan ® Demo)" link from the official website.

**Server Setup Information**:

No information can be provided about the setup, as it was hosted by the official Wekan website.

**Problem description**:

"board.wekan.team" is/was a platform hosted by the Wekan team, where users could register an account and use the Wekan tool as if it was installed on the user's machine/server. I have been using this service for years without hiccups until January 11, 2022. From that day onward, my boards, account and whole site is unreachable.

Firefox returns a timeout error (524), stating that the web browser and Cloudflare near me are working, but the host (board.wekan.team) is not.
![Wekan - Firefox](https://user-images.githubusercontent.com/29022567/149401105-27492614-473f-43a7-95b1-7bd4b92abe45.PNG)

Opera states that "board.wekan.team’s server IP address could not be found." "ERR_NAME_NOT_RESOLVED".

Chrome returns the exact same error name as Opera.
![Wekan - Chrome](https://user-images.githubusercontent.com/29022567/149401109-d889aca3-4c0d-45ad-8d5d-a5ca0ae01666.PNG)

Several online tools to report downtimes all confirm that this issue isn't local to my setup/network.

Since no notification regarding a maintenance, shut down of service or any other planned downtime was sent, I assume this is an issue.
The roadmap (https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) link from the official wekan.team website is, of course, also affected by this issue.

My most sincere apologies if this isn't the right place to report this problem, I will gladly follow any given link to post this report in the correct place. Best regards.

**Comment by xet7** [comment]
@vdst 

Thanks for info ! Just a moment I wil fix it.
