### ISSUE TITLE
Problem with Heroku

### ISSUE THREAD

**Issue by nonamich** [wekan/wekan#4302]
Hi there,

Is wekan still supported in heroku elements?
I'm asking because when I automatically deploin wekan in heroku I get the error "The addon "mongolab" does not exist. Please ensure that the addon is spelled correctly."

you can check here: https://elements.heroku.com/buttons/wekan/wekan

Thanks for your time!

**Comment by xet7** [comment]
@nonamich 

I have never used Heroku. Old Heroku support is from other WeKan contributors that most likely are not currently contributing to WeKan at all. If you know something about Heroku, please send pull requests. I think it's this file https://github.com/wekan/wekan/blob/master/app.json ?

Some news:
- https://blog.mlab.com/2016/02/mongolab-is-now-mlab/
- https://blog.mlab.com/2018/10/mlab-is-becoming-a-part-of-mongodb-inc/

I have no idea what MongoDB Heroku currently uses. Very likely it is not mongolab anymore.

Related to WeKan hosting:
- Meteor Cloud provides tiny Meteor hosting for free https://www.meteor.com/cloud
- I do also provide WeKan hosting https://wekan.team/commercial-support/
- You can self-host WeKan, and there are also many SaaS options, see download section of https://wekan.github.io
