### ISSUE TITLE
faster way to do actions that uses frequently

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#4303]
in trello you can access them by right click : move/copy.
or some of them by shortcuts : label - due date.
also some of them can be solved by more Rules.
<img width="323" alt="a" src="https://user-images.githubusercontent.com/25129673/150302215-355f103d-b2e2-4570-bf14-c0848036395a.png">

**Comment by xet7** [comment]
@mohammadZahedian 

Hmm, I checked at Trello, it seems hijack webbrowser right click to show custom menu. Similar feature in WeKan would really make right click inspect debugging harder. Please no hijacking right click. Please think of any other alternative that does not hijack right click.

**Comment by xet7** [comment]
I'm thinking, how would right click work on mobile phone touch screen?

**Comment by mfilser** [comment]
Maybe left click with left hand, right click with right hand 🤣

... Just kidding 😁

Hm, good question, maybe long pressing e. g. 3 seconds without moving the finger. But, it could be tricky, maybe...

**Comment by xet7** [comment]
@mfilser 

AFAIK long pressing is native desktop or native mobile app feature. Not webbrowser feature.

**Comment by mohammadZahedian** [comment]
> I'm thinking, how would right click work on mobile phone touch screen?

Trello doesn't have this option in mobile phone. It can be disable at mobile phone.

Or three dot at corner of the card.

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian
> 
> Hmm, I checked at Trello, it seems hijack webbrowser right click to show custom menu. Similar feature in WeKan would really make right click inspect debugging harder. Please no hijacking right click. Please think of any other alternative that does not hijack right click.

How about three dot at corner of cards?

**Comment by mfilser** [comment]
> How about three dot at corner of cards?
This area is already used for drag handles

**Comment by mohammadZahedian** [comment]
> > How about three dot at corner of cards?
> 
> This area is already used for drag handles

Its empty in web browser.
In mobile phone we can use left corner.

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian
> 
> Hmm, I checked at Trello, it seems hijack webbrowser right click to show custom menu. Similar feature in WeKan would really make right click inspect debugging harder. Please no hijacking right click. Please think of any other alternative that does not hijack right click.

@xet7 

trello use an icon in top right corner when you hover a card.
![1](https://user-images.githubusercontent.com/25129673/150669177-edb2bb06-b758-4095-94ed-ce6566884a0b.png)

**Comment by mohammadZahedian** [comment]
@xet7 any idea?

**Comment by xet7** [comment]
@mohammadZahedian 

I think, that ☰ menu that is on opened card, could also be on minicard.

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian
> 
> I think, that ☰ menu that is on opened card, could also be on minicard.

with all of its options?
i think move, copy, duedate and label are enough.

**Comment by HT-Marley** [comment]
yeah that would be great, I also think that this icon ☰ could be directly on the card but only for a smal number of quick actions.
I also think that the hijacking the right mouse button is not a good solution.
It would be great if one of the quick actions could also be "link" (create linked card on another board or list)

**Comment by mohammadZahedian** [comment]
@xet7 anything that we can do?

**Comment by mohammadZahedian** [comment]
@xet7 🙄

**Comment by mohammadZahedian** [comment]
@xet7 😭😭😭

**Comment by xet7** [comment]
@mohammadZahedian 

Cards code is here:
https://github.com/wekan/wekan/tree/master/client/components/cards

Please make those changes and submit pull request, like this:
https://github.com/wekan/wekan/wiki/Emoji#about-other-markdown-it-plugins

Thanks!

**Comment by xet7** [comment]
At that wiki page, please ignore plugin related stuff.

**Comment by mohammadZahedian** [comment]
@xet7 Unfortunately i am not able to help in programming stuff...
Isn't this a feature request?

**Comment by mohammadZahedian** [comment]
@xet7
im am not programmer
how can we publish this issue to someone solve it?

**Comment by mohammadZahedian** [comment]
@mfilser

**Comment by mohammadZahedian** [comment]
@xet7 @mfilser How long should I wait for this feature to be added?

**Comment by mohammadZahedian** [comment]
@xet7 @mfilser  is there any chance to someone add this feature?

**Comment by xet7** [comment]
@mohammadZahedian @HT-Marley 

I added this feature. Please try newest WeKan (for example Docker), does this work?

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian @HT-Marley
> 
> I added this feature. Please try newest WeKan (for example Docker), does this work?

would you pleas answer #4710

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian @HT-Marley
> 
> I added this feature. Please try newest WeKan (for example Docker), does this work?


😍 it is so great... i am user wekan much faster now. thanks.

**Comment by mohammadZahedian** [comment]
![photo144127282853457960](https://user-images.githubusercontent.com/25129673/211259193-03ebca63-e11a-4c3b-9040-15074af50360.jpg)
there is no Close or Back icon in mobile
also Archive is a widely using button that us not here

**Comment by mohammadZahedian** [comment]
![image](https://user-images.githubusercontent.com/25129673/211260265-1ef821eb-b634-4f9f-9fd0-a2df149a6b1b.png)
☰ menu need a padding

**Comment by mohammadZahedian** [comment]
area of ☰ is tiny and a little hard to click on it ( like close icon in ads 😂 )
![image](https://user-images.githubusercontent.com/25129673/211261189-d3f761c0-4962-487e-aeff-2f1f942d70fc.png)
![image](https://user-images.githubusercontent.com/25129673/211261194-e68493ea-3037-42d7-81a8-1447376ce659.png)
like above pics it can have hover area to make it a little bigger

**Comment by xet7** [comment]
@mohammadZahedian 

You have wrong settings. Info about correct settings at https://github.com/wekan/wekan/issues/4803#issuecomment-1375399334

**Comment by mohammadZahedian** [comment]
> area of ☰ is tiny and a little hard to click on it ( like close icon in ads 😂 ) ![image](https://user-images.githubusercontent.com/25129673/211261189-d3f761c0-4962-487e-aeff-2f1f942d70fc.png) ![image](https://user-images.githubusercontent.com/25129673/211261450-cecba7c0-9211-4e35-a34d-3fa30a6df328.png)
> 
> like above pics it can have hover area to make it a little bigger

@xet7

**Comment by mohammadZahedian** [comment]
@xet7 
Archive card is missing
This is one of the most used buttons

**Comment by xet7** [comment]
@mohammadZahedian 

I added menu buttons bigger and "Move card to archive" to WeKan v6.77 .

**Comment by mohammadZahedian** [comment]
![image](https://user-images.githubusercontent.com/25129673/228842757-9a16801d-7776-4b2e-9d50-f4f816c3540d.png)

in rtl languages ☰ needs  a little padding 

@xet7
