### ISSUE TITLE
There was a problem when I added the description

### ISSUE THREAD

**Issue by lixiangxian** [wekan/wekan#4304]
I passed docker-compose Deploy wekan，
and there was a problem when I added the description
![8cccc7ada254bfebb3ac7a0c1e4af26](https://user-images.githubusercontent.com/51731099/150303837-ea5a064e-c9ab-4249-8ccd-2b1b1d59feb8.jpg)

**Comment by mfilser** [comment]
@lixiangxian 
Is there a way to reproduce it? If yes, can you send a record with "peek" (https://github.com/phw/peek) ?

**Comment by lixiangxian** [comment]
docker version 20.10.8
docker-compose version v2.2.3
https://user-images.githubusercontent.com/51731099/150307667-1653d5af-73b7-4874-8f48-94ebee2ba845.mp4

![7abe7b895da1a7be581b43f47adf920](https://user-images.githubusercontent.com/51731099/150307668-1f7c1709-3060-4b22-9c31-3ab892194463.jpg)

**Comment by mfilser** [comment]
Thank you.
I will have a look at this

**Comment by lixiangxian** [comment]
thanks

**Comment by lixiangxian** [comment]
@mfilser
I found the cause of the problem，Because Google browser version is too low，I'm sorry to trouble you

**Comment by mfilser** [comment]
@lixiangxian 
I see, thank you for your feedback and solution.
My first though was it's because of the Rich-Text editor
