### ISSUE TITLE
Port in email notification

### ISSUE THREAD

**Issue by AlexandrovRR** [wekan/wekan#4305]
Hello everyone. The arrival of the message by mail. He's looking out for the next view
http://10.102.24.122/b/ao8qBEEQvxBtyYBGd/it-otdel/2JmW23NaP9KZmDhda

Although it should look like this
http://10.102.24.122:3001/b/ao8qBEEQvxBtyYBGd/it-otdel/2JmW23NaP9KZmDhda

How to change the letter template, I can not figure it out

**Comment by xet7** [comment]
@AlexandrovRR 

Snap:
```
sudo snap set wekan root-url='http://10.102.24.122:3001'
```

Or similar ROOT_URL setting in other WeKan versions

**Comment by AlexandrovRR** [comment]
> 
but at the same time we open the link http://10.102.24.122:3001

**Comment by AlexandrovRR** [comment]
> 

o, thank you very mutch
