### ISSUE TITLE
Can we add a copy checklist option to the new Checlist Actions menu?

### ISSUE THREAD

**Issue by ChrisMagnuson** [wekan/wekan#4306]
@mfilser Thank you for adding the new Checklist Actions menu with the ability to Delete and Move a checklist.

Is there any way you could also add a Copy Checklist option?

This would make a big difference to our workflow as today we currently copy a card that has 20ish checklists and then delete the ones we don't need which can at times be most of them and if we could instead create a new card and copy only the checklists we needed over to that new card or even copy them as we need them, maybe later on when the scope of what is being accomplished on the card changes, that would be a much better workflow.

**Comment by mfilser** [comment]
@ChrisMagnuson
Thank you for the feedback about the created checklist action menu, good to see it's useful :slight_smile:

That was the idea to create a checklist menu to have more options, one of them could be indeed to copy a checklist. 
I could have a look at this, but this week i don't have time for it.

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4331

**Comment by ChrisMagnuson** [comment]
@mfilser Thank you so much for implementing this feature! We will use it all the time in our office. 😀🎉

**Comment by mfilser** [comment]
@ChrisMagnuson 
Your welcome. Thank you very much, i am happy to hear it :slightly_smiling_face: :man_dancing:
