### ISSUE TITLE
Fast render not working (publishComposite bug)

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#431]
It seems that our `FastRender` configuration doesn’t publish the board publication on the initial page load. I tried to debug this on the surface by writing various `console.log` at various places in the code but wasn’t able to find anything abnormal.

You can see an example of the unexpected latency here: https://wekan.io/b/MeSsFJaSqeuo9M6bs/wekan-roadmap (a look at the HTTP response confirm that indeed the cards data aren’t sent).

@arunoda do you see anything wrong with these two calls:

* [FastRender.route](https://github.com/wekan/wekan/blob/f9a60616df625ea71386442de512fbfb43602d09/server/publications/fast-render.js#L5-L7)
* [Meteor.publish](https://github.com/wekan/wekan/blob/f9a60616df625ea71386442de512fbfb43602d09/server/publications/boards.js#L58-L151)

**Comment by arunoda** [comment]
Check this. Use the `FastRender.debugger` to findout which documents sent to the client. 
See:

![screen shot 2015-12-09 at 10 45 16 am](https://cloud.githubusercontent.com/assets/50838/11677287/2001b7da-9e62-11e5-9dd9-b7a757f0744f.png)

It seems like FR subscriptions works, but something with the publication. I don't understand publish-composite pattern. May be you need to dig more into it.

**Comment by mquandalle** [comment]
Ok thank you for the hint. Do you know any convenient way to log the DDP messages, like `added` or `ready`, on the server side, to verify if these are generated correctly?

**Comment by arunoda** [comment]
There is a way you can do it by simply calling a method on the server. I don't remember it now. Something like `Meteor._printDDPLogs()`

**Comment by mquandalle** [comment]
Hi @reywood, did you already used FastRender on a PublishComposite publication? Any idea why it wouldn’t work?

**Comment by arunoda** [comment]
One idea. If FastRender gets this.ready() message from the publication, it
won't listen for data after that.
I assume, publish-composite sends this.ready() even before sending actual
data in this particular scenario.
Check DDP logs.

**Comment by mquandalle** [comment]
I didn’t figured out the exact method name yet :-) BTW, the publishComposite function is pretty simple: https://github.com/englue/meteor-publish-composite/blob/5bf1e1e741a6dbf544be148e6288a99971df75aa/lib/publish_composite.js#L1-L22

**Comment by mquandalle** [comment]
Hum, and there is a `Meteor.publishComposite.enableDebugLogging()`, let’s try that.
