### ISSUE TITLE
popups are out of screen ( need to scroll )

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#4312]
when you have to set date and label many cards in a day its very annoying that you have to scroll in every action ( specially duedate 😭)
![1](https://user-images.githubusercontent.com/25129673/150613667-baedb9f1-cf45-47f2-9fd8-0f5da0345f82.gif)

![2](https://user-images.githubusercontent.com/25129673/150613685-671b5534-84bc-4b7f-8564-68919d4e4c3b.gif)

----------------------------------------

It would be great if the popups appeared in the middle of the screen ( like trello ):

![3](https://user-images.githubusercontent.com/25129673/150613720-b7b348dc-d4cf-48f4-babd-e4399eb840de.gif)

![4](https://user-images.githubusercontent.com/25129673/150613840-c40afd37-1be2-4b5a-9671-3f9b8d6cc6d9.gif)

**Comment by xet7** [comment]
@mohammadZahedian 

When you click label directly at minicard, you can change label there.

You could create [Custom Field](https://github.com/wekan/wekan/wiki/Custom-Fields) like Date, and show that on minicard, and then change them directly at minicard. There is not yet feature for displaying DueDate on minicard.

Anyway, those popup positions could be changed sometime, by some WeKan contributor or me. Thanks!

**Comment by xet7** [comment]
Hmm, would some Multi-Selection feature like this help?
- Set DueDate for all Multi-Selected
- Set Label for all Multi-Selected

And maybe possibility to also click List to select all cards in that List ? Or select all in Swimlane?

**Comment by mohammadZahedian** [comment]
i think a tiny change in css would fix it, like:
`.pop-over{
    position:fixed;
    top:20%;
    left:50%;
    }`

**Comment by mfilser** [comment]
@mohammadZahedian
@xet7 
Popup's are used at many places in Wekan, i think this change could break many other popup's, especially the card detail popup

**Comment by mohammadZahedian** [comment]
it would be grate if there was something like "custom css" to test more ways.
and custom css can prevent many user to submit an issue or request.
@xet7 @mfilser

**Comment by xet7** [comment]
@mohammadZahedian 

You can already have Custom CSS for WeKan with browser plugin. It does not help if some CSS fix is only on someone's local browser. Those fixes need to be made available for every WeKan user with pull requests etc.

Sometime there will be Custom CSS and Custom Everything in WeKan, maybe this or next year, but it's not yet.
