### ISSUE TITLE
Issue: comments not loading on cardType-linkedBoard

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4314]
### Server Setup Information
* Did you test in newest Wekan?: Yes - Wekan 5.95
* Did you configure root-url correctly so Wekan cards open correctly ? Yes
* Operating System: Debian 10
* Deployment Method: Snap
* Http frontend: Apache
* Node.js Version: 12.22.9
* MongoDB Version: 3.2.22

### Problem description
On linkedBoard card (_cardType-linkedBoard_) comments are not displayed. They are not loaded

<img width="796" alt="linkedBoard - 01" src="https://user-images.githubusercontent.com/37017213/150645166-712ff166-bb19-481c-9cfc-42a50f80800e.png">

<img width="1172" alt="linkedBoard - 02" src="https://user-images.githubusercontent.com/37017213/150645172-cad6be19-ed9f-4436-8ad2-d6aeccbe3c1c.png">

<img width="355" alt="linkedBoard - 03" src="https://user-images.githubusercontent.com/37017213/150645189-a5f312ca-484f-4dee-8906-52549416fa40.png">

Need to open firts the target board (h_ere "Test Board 2"_) to force card comments loading.

<img width="1161" alt="linkedBoard - 04" src="https://user-images.githubusercontent.com/37017213/150645296-86e5f22d-5e55-4b9b-b73e-fa81d64b0295.png">

<img width="287" alt="linkedBoard - 05" src="https://user-images.githubusercontent.com/37017213/150645333-451d1420-a4a9-4c83-a537-0413afbc2b25.png">

**Comment by Ben0it-T** [comment]
@xet7 
Digging for several days 
Think I got something here 
https://github.com/wekan/wekan/blob/ba24e4a775d1127eabf9867bef646d949529bbc2/server/publications/boards.js#L229-L279

`cardType-linkedBoard `won't load cardComments

To force cardComments loading I've test this:
```js
const cardCommentsLinkedBoards = this.join(CardComments);
cardCommentsLinkedBoards.selector = _ids => ({ boardId: _ids });
```

```js
if (card.type === 'cardType-linkedCard') {
  const impCardId = card.linkedId;
  subCards.push(impCardId); // GitHub issue #2688 and #2693
  cardComments.push(impCardId);
  attachments.push(impCardId);
  checklists.push(impCardId);
  checklistItems.push(impCardId);
} else if (card.type === 'cardType-linkedBoard') {
  boards.push(card.linkedId);
  cardCommentsLinkedBoards.push(card.linkedId); // boardId
}
```

```js
cardCommentsLinkedBoards.send();
```

Could you have a look a this ?
If ok I'll send PR
Thanks

**Comment by Ben0it-T** [comment]
<img width="1207" alt="linkedBoard - 06" src="https://user-images.githubusercontent.com/37017213/150646222-74229350-5f80-495c-9f21-a081715e2ef7.png">

**Comment by xet7** [comment]
@Ben0it-T 

Please send PR. Thanks!
