### ISSUE TITLE
Custom fields showed up in 5.90 that no one created

### ISSUE THREAD

**Issue by skye0402** [wekan/wekan#4320]
### Server Setup Information

* Did you test in newest Wekan?: Yes, 5.97
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Linux 
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker/ Kubernetes
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Just the deployed docker image.
* Node.js Version: 12.22.9
* MongoDB Version: 4.4.10
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Chrome/ latest

### Problem description
I copied a board with custom fields on version 5.90 and the copy looked good. At some point in time (don't know how) 9 unnamed custom fields showed up and existing fields got duplicated (just empty, values were not copied). I deleted the duplicate fields but im still with these icons. As you see in the screenshot. How can I delete them?

![image](https://user-images.githubusercontent.com/36907475/150677092-0466d6bc-7530-450a-b63b-dc78e931cde3.png)

#### Reproduction Steps
Don't know how to reproduce.

#### Logs
n/a

**Comment by xet7** [comment]
@skye0402 

Can you hide them by clicking them at card hamburger menu?

Or are they visible at Board Settings / Custom Fields, delete from there?

Or should you edit database with DBGate?
https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui

**Comment by skye0402** [comment]
Thank you kindly for the reply. I can't hide them as they are not visible in the custom field menu.
I'll try your DB recommendation.

**Comment by mfilser** [comment]
Before you make database changes i suggest to make a backup. There is a good documentation in the Wiki here in this project.

**Comment by skye0402** [comment]
Here's how it looks on the MongoDB
![image](https://user-images.githubusercontent.com/36907475/150706815-5e193953-50dd-457b-8d9a-7baceaf74369.png)

I'm not very knowledgeable with MongoDB - how can I set a statement to delete all custom fields on cards where value = null and _id does not exist? 😥

**Comment by skye0402** [comment]
I was able to remove it by this statement (running it 9 times). I'm sure this can be more elegant but I'm a MongoDB Noob. 😅
```
db.getCollection("cards").update({ boardId: "iSHzdvxF3FxYwJ24f" }, {
    $set: {
        "customFields.2": ObjectId("61ee09ef35ee264a684f8b1a")
    }
}, { multi: true });
db.getCollection("cards").update({}, {
    $pull: {
        "customFields": {
            "$in": [
                ObjectId("61ee09ef35ee264a684f8b1a")
            ]
        }
    }
}, { multi: true }); 
```
