### ISSUE TITLE
List not movable when lists require scrolling

### ISSUE THREAD

**Issue by gbmd** [wekan/wekan#4322]
## Issue
Lists (Especially on the right) are not movable when there are too many lists to fit the screen.
They become movable again when the left end of the board is visible again. (Extreme Zoom-out)
This could be related to Issue: https://github.com/wekan/wekan/issues/4219

### Server Setup Information
![image](https://user-images.githubusercontent.com/54003582/150948423-83f14e5a-9eff-4066-a199-7d147de083bf.png)
* Operating System:
* Deployment Method Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using: Chrome 97.0.4692.99

### Problem description
note: M is last Board
![Peek Wekan](https://user-images.githubusercontent.com/54003582/150949751-778da53f-df65-403b-af8a-fe189dc3ccdb.gif)
#### Reproduction Steps
Can be reproduced by creating a Board with 13 Lists (A-M), scrolling to M and trying to switch M and L

#### Logs
no console messages

**Comment by mfilser** [comment]
I will have a look at this
