### ISSUE TITLE
[Feature Request] [UI/UX]: Make card corners round 

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4326]
For a more modern and appealing look, it would be nice if the corners of cards would be round. Like those on Padlet.com
![RundeEckenWeKan](https://user-images.githubusercontent.com/92315677/151768639-43e47144-9bba-4039-85e5-89dccd17ef64.jpg)

**Comment by Meeques** [comment]
Like the theme 'clearblue'

**Comment by xet7** [comment]
@Meeques 

Thanks! I did not remember that some theme already has rounded corners. I'll check how clearblue does it.

**Comment by jghaanstra** [comment]
I just updated and noticed this has been added to all themes including moderndark. I designed this theme to not have rounded corners on the minicard. Am I allowed to revert this for the moderndark theme with a PR?

**Comment by xet7** [comment]
@jghaanstra 

Yes of course. Everyone is allowed to send any PR.

**Comment by Meeques** [comment]
I really like the new look, thank you @xet7 !
