### ISSUE TITLE
Bug: Received Date is not displayed on Minicard

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4327]
Hi, I'm using the newest version of WeKan with the newest version of firefox. 

As you can see on the screenshot, the received date should be displayed in the minicard. But it is not. I set the date for start, due and end. Then saved, then added the received date. It wasn't displayed so I deleted the start date in case there are only so many dates that can be displayed on the minicard. Seems this is not the case.

![BugWekanEmpfangenDatum](https://user-images.githubusercontent.com/92315677/151943020-f107fc2d-74ab-4d84-9e1c-b5b1d5d52b8d.jpg)

**Comment by xet7** [comment]
@Meeques 

Those settigs are currently for showing on card. I need to add settings for showing on minicard.

**Comment by Meeques** [comment]
@xet7 got it, thanks for the clarification!
