### ISSUE TITLE
[Feature Request]: Show description on minicard

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4328]
I find it somewhat circumstantial to only see if there is a description on a minicard, but not it's content. For that I have to check inside the card. For short descriptions this will make usability better because you don't have to make all those extra clicks. For longer descriptions, I could imagine an unfold option. 

I added a small mockup:
![description](https://user-images.githubusercontent.com/92315677/152006923-49da878f-ec64-4ae9-ad1c-0ce9d2884e80.jpg)

**Comment by Meeques** [comment]
This feature is not really intuitive, although I appreciate that it's there. Most users won't notice that they can hover over the icon to read the description. It would be more user friendly if one could set the description to be displayed on the minicard.

**Comment by Meeques** [comment]
@xet7 Could you tell me how much funding would be needed for this to work?

**Comment by helioguardabaxo** [comment]
Hi, @Meeques and @xet7 
Does this feature has any funding?

**Comment by xet7** [comment]
@helioguardabaxo 

Yes, funding bureaucracy is In Progress. Just a moment, I'll add info to some issues about funding.

**Comment by helioguardabaxo** [comment]
Ok.

I am trying to implements here. There is any problem?

**Comment by xet7** [comment]
@helioguardabaxo 

No. I would prefer to have as many pull requests, contributions etc as possible, it would speed up developing WeKan a lot. There are 741 open issues, it has grown, some time ago it was about 500.

**Comment by xet7** [comment]
If someone other implements some upcoming paid feature, then with that funding I can implement some other feature/fix etc. I have implemented many features and fixes without funding. First year of maintaining WeKan I did without any funding, and after that there have been some partial funding sometimes.

**Comment by xet7** [comment]
But I have not heard any feedback about that bureacracy process, that will it get accepted, go forward etc at all. So I think I dont add these to Roadmap yet.

Bureaucracy processes usually take about 6-12 months in big organizations.

**Comment by helioguardabaxo** [comment]
Great!
Thanks for your feedback's.

**Comment by helioguardabaxo** [comment]
When enable, description text is showed on minicard and description badge/icon is not showed:
![Screenshot 2022-04-05 at 14-34-07 My best board -](https://user-images.githubusercontent.com/24301085/161819764-d0a74494-beb8-4d2c-8d09-a522ba5bbc19.png)

When disable, just description badge/icon is showed:
![Screenshot 2022-04-05 at 14-34-40 My best board -](https://user-images.githubusercontent.com/24301085/161819991-2961a98c-1cc9-431c-9054-b4cabc306a49.png)

**Comment by xet7** [comment]
@helioguardabaxo 

Please send PR. Thanks!

**Comment by xet7** [comment]
@helioguardabaxo 

Very many have developed additional features to WeKan. Problem is, if they have not sent that feature to WeKan, then that feature has possibility to disappear, like at https://github.com/wekan/wekan/issues/3948#issuecomment-1063488560

https://blog.wekan.team/2018/02/benefits-of-contributing-your-features-to-upstream-wekan/

There are also many Python-based features that need separate install, nobody have added those directly to Javascript WeKan:
https://github.com/wekan/wekan/wiki/Python

It's not about does some feature have funding or not. It is about is someone interested in having that feature at Javascript WeKan at all.

**Comment by helioguardabaxo** [comment]
@xet7 
Today Python is more familiar to me that JavaScript. So, I am creating a script to plot CFD (Cumulative Flow Diagram) for a Wekan board. But I would like to implement it on Wekan.

**Comment by xet7** [comment]
@helioguardabaxo 

Can you send that WeKan Python Cumulative Flow Diagram script repo URL in new issue comment? I could then add it to Python page.

**Comment by xet7** [comment]
I have sometimes thinked about making Python version of WeKan, because there are so many Python-only features.

**Comment by xet7** [comment]
Feature added at https://github.com/wekan/wekan/pull/4454

**Comment by Meeques** [comment]
Thank you so much @helioguardabaxo !

**Comment by aov-arnold** [comment]
@helioguardabaxo @xet7 
We have some very long description texts which fill the whole screen now. Would it be possible to only show the first x characters by default and implement the unfold option which was mentioned by @Meeques in the beginning?

**Comment by xet7** [comment]
@aov-arnold 

Hmm. Would @helioguardabaxo or someone else like to do it?

I currently have other features development In Progress.

**Comment by aov-arnold** [comment]
Yes that looks good!
