### ISSUE TITLE
Incorrect message in card details after adding a member

### ISSUE THREAD

**Issue by xavierpriour** [wekan/wekan#433]
On wekan roadmap, card "Be able to clone a board, a list, or a card".
User "floatinghotpot" added itself to the card.

Card details display: "floatinghotpot added this card to floatinghotpot." = incorrect
Board sidebar displays: "floatinghotpot added floatinghotpot to Be able to clone a board, a list, or a card" = correct

![wekan-bug-cardmemberadd](https://cloud.githubusercontent.com/assets/2295912/11679894/c43587fe-9e54-11e5-98d8-92becd9a33e3.png)

**Comment by mquandalle** [comment]
I’m curious why you consider the second activity description as correct but not the first one. Anyway I think a better description would be:

1. *(at the card level)* ${user} joined this card
2. *(at the board level)* ${user} joined ${cardName}

**Comment by xavierpriour** [comment]
It's just that I believe the description should be: "**userA** added **userB** to **cardName**" in all cases.
And current card description actually says that "userA added **card** to userB".

You're right, we could also shorten it to "**userA** joined **card**" when user adds himself.

**Comment by mquandalle** [comment]
Got it!
