### ISSUE TITLE
Issue: can't add attachment to a card

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4338]
### Server Setup Information
* Did you test in newest Wekan?: Yes, WeKan 6.02
* Operating System: Debian 10
* Deployment Method: Snap
* attachments-store-path = /var/snap/wekan/common/attachments
* Http frontend: Apache
* Node.js Version: 14.19.0
* MongoDB Version: 3.2.22

<img width="635" alt="wekan-snap" src="https://user-images.githubusercontent.com/37017213/152696273-8177de17-d897-4a2b-af10-4edb7e7ee368.png">

### Problem description
Since Wekan 6.02, can't add attachment to a card. 
Was working in Wekan 6.00

<img width="279" alt="addAttachment" src="https://user-images.githubusercontent.com/37017213/152696370-d2d9378a-6a53-4360-9e68-15a5414c1ade.png">

**Comment by xet7** [comment]
@Ben0it-T 

Please copy all from right click / Inspect / Console to comment of this issue, with domain anonymized to be like example.com . Thanks!

**Comment by xet7** [comment]
For me, it seems viewing existing images does work, but uploading does not.

It could be because in WeKan 6.01 I updated Node.js from 12 to 14, it made WeKan work also at Sandstorm. Anyway, there is no going back to Node.js 12, because it will be EOL soon.

So it mainly depends does @imajus and @mfilser get uploading etc working with https://github.com/wekan/wekan/pull/4336

**Comment by Ben0it-T** [comment]
@xet7 
Viewing existing files/images works.
Only adding new attachment fails

<img width="1000" alt="addAttachment-console" src="https://user-images.githubusercontent.com/37017213/152698393-f426241b-b457-450e-baaf-373cd0c62b06.png">

Nothing in /var/log/messages
Nothing in snap logs wekan

**Comment by xet7** [comment]
For fixing this, I changed Node.js back to 12.22.10 https://github.com/wekan/wekan/commit/cc5486797648b8098e50fa4f68cc4b588f41ab60 . I'm in progress of releasing WeKan 6.03 , hopefully it's fixed there.

But, that Node 12.22.10 does not work on Sandstorm, so sometime later it needs to be figured out how to upgrade to Node.js 14.x while still having upload working.
