### ISSUE TITLE
[Bug]: Copy card to list doesn't work

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4343]
Hi! I just noted that copying a card to another list does not work. The card gets copied, but stays in the same list as original card.
Used the newest Version of WeKan and Firefox.
![Wekanbug_copytolist](https://user-images.githubusercontent.com/92315677/152764561-31a379aa-7be0-4117-b8a0-883566cbb1cf.jpg)
Thank you.

**Comment by Meeques** [comment]
Firefox Version 91.5.1esr
WeKan gets updated via snap, so is always the newest version (I cannot view the current version)

**Comment by xet7** [comment]
I think it is a bug in this new advanced feature https://github.com/wekan/wekan/pull/4333 . I'll try to revert that, probably that feature will be fixed later.

**Comment by mfilser** [comment]
@xet7 
I will have a look at this
