### ISSUE TITLE
[BUG] Move card not working and deleting card

### ISSUE THREAD

**Issue by Driksi** [wekan/wekan#4344]
## Expected Behavior
 In the Weken application when selecting a card and the the option to move card, after indicating the board to witch the card should be moved and selecting Done the card should be properly placed in the chosen board while storing the logs of the action performed.

## Current Behavior
Currently when performing this action the card gets deleted however the logs still state that the card was in fact moved

## Steps to Reproduce
![Wekan_bug1](https://user-images.githubusercontent.com/89528434/152781349-7f289ae6-7344-44c0-a069-206486c4e724.PNG)

![2r](https://user-images.githubusercontent.com/89528434/152781388-bfd8a993-7416-4ee8-ad8e-deef2d99b46c.PNG)

![4](https://user-images.githubusercontent.com/89528434/152781408-04e054ef-1c9c-41ee-ad6f-1afc36fa3469.PNG)

![5](https://user-images.githubusercontent.com/89528434/152781436-82c87bca-fa96-4da1-bed4-1cf0b6f96f4f.PNG)

## Context (Environment)
Mozilla Firefox 96.0.3 (64-bit)

**Comment by nsg** [comment]
We where affected by this as well, 20 or so cards disappeared when we moved them between two boards. We use the snap and noticed the problem running change 52, 53 later that evening fixed the problem.

```
# snap changes wekan
ID   Status  Spawn                   Ready                   Summary
52   Done    yesterday at 11:29 CET  yesterday at 11:29 CET  Auto-refresh snap "wekan"
53   Done    yesterday at 19:44 CET  yesterday at 19:44 CET  Auto-refresh snap "wekan"

# ls -l /var/lib/snapd/snaps/wekan_*
-rw------- 1 root root 167890944 Feb  7 11:29 /var/lib/snapd/snaps/wekan_1973.snap
-rw------- 1 root root 167890944 Feb  7 19:44 /var/lib/snapd/snaps/wekan_1981.snap
```

I looked around in the database and noticed that the move operation had not updated `boardId`, `swimlaneId`. I think it only updated the `listID` field, the other where still referring to the old board.

After figuring out the `_id` of my affected cards I did a `db.cards.update({_id: "<card id>"}, {$set: {boardId: "<board id>", swimlaneId: "<swimlane id>", listId: "<list id>"}})` to update the fields to something consistent.

We have increased the rate of database backups "just in case" :) ... even if I was able to restore the state without reverting to backups in this case. I hope this can be useful for someone else.

**Comment by mfilser** [comment]
@nsg 
Which Wekan Version are you running?

**Comment by nsg** [comment]
@mfilser

```
installed:          6.05            (1981) 167MB -
```

I have no idea what version rev 1973 was, I can probably dig inside the snap-file if relevant.

**Comment by nsg** [comment]
Realized that the last version was still on disk:

```
/snap/wekan/1973/meta/snap.yaml:version: '6.03'
/snap/wekan/1981/meta/snap.yaml:version: '6.05'
```

**Comment by Driksi** [comment]
I'm sorry that you were affect worse than me by this issue @nsg but given that the issue has been resolved on following updates I will be closing this Issue.
