### ISSUE TITLE
Global search: Preview of cards in maximised view does not work

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#4346]
Using the “maximised” view for card details:

![image](https://user-images.githubusercontent.com/2184938/153184759-c617d89c-09bb-42dd-a544-141c12ea7c51.png)

and using the global search:

![image](https://user-images.githubusercontent.com/2184938/153184862-8ae7afe2-aa01-4e52-aaa6-cf4fe268be4d.png)

makes any card preview in the search results almost unusable:

![image](https://user-images.githubusercontent.com/2184938/153185052-d8c9bf51-b203-4b7c-95dd-9a30ca3acc86.png)

As you can see, the card details are extremely small. My current workaround is to click on the “chain” icon to open the card in another tab.

**Comment by bronger** [comment]
Have a look at https://github.com/wekan/wekan/blob/master/client/components/cards/cardDetails.styl#L266.  This `height` directive causes the collapse of the popup.

**Comment by bronger** [comment]
If I understand you correctly, it may be that changes in Wekan after we forked our theme may be missing in our theme, causing this problem?

**Comment by mfilser** [comment]
It depends on your custom theme what you defined there

**Comment by bronger** [comment]
FWIW, I can see this bug also with the default theme.

**Comment by mfilser** [comment]
@bronger 
Sure. It's look like this with the theme "Belize"

![grafik](https://user-images.githubusercontent.com/13166201/153628248-43d957f4-5baf-4272-8183-fd32b4d98e75.png)

**Comment by bronger** [comment]
This more looks like the normal card view. Are you sure you have maximised the card details? (See the very first screenshot in the issue description.)

**Comment by mfilser** [comment]
@bronger
Hm, not sure right now. I will check again as soon as i am at my Linux workstation again

**Comment by mfilser** [comment]
I think i got the problem now. Hang on, i will send a PR.

**Comment by mfilser** [comment]
@bronger 
I think the pull request #4352 should solve this issue. Thank you for your patience :slightly_smiling_face:
