### ISSUE TITLE
Custom Fields (sum) can't be unset and does not sum (6.05)

### ISSUE THREAD

**Issue by KoshNaranek** [wekan/wekan#4347]
new install of wekan 6.05 snap on Ubutu
If you add a custom filed eg "time planned" (number) and set it to "Show sum of field on top of row" you can't remove it anymore - and there is no sum. If you untick the setting and click SAVE, nothing happens. If you re-open the settings, it's ticked again.
<img width="1274" alt="Bildschirmfoto 2022-02-09 um 21 16 11" src="https://user-images.githubusercontent.com/34599995/153283214-ddf89a8e-9eba-40d3-807d-62a5a61ef47f.png">

 
upgraded an other instance from 5.30 to 6.05 today - now all custom fields in existing boards are below each other instead of next to each other (card, not minicard).
before: 
field#1  field#2  field#3
after: 
field#1
field#2
field#3 (toggle/settings)

**Comment by KoshNaranek** [comment]
oh.. by the way: in "moderndark" you can't read the sum-field
<img width="564" alt="Bildschirmfoto 2022-02-09 um 21 36 53" src="https://user-images.githubusercontent.com/34599995/153285739-a9d0e0bf-6bbd-44b4-8423-66041a262b39.png">

**Comment by KoshNaranek** [comment]
![Greenshot 2022-02-10 09 08 19](https://user-images.githubusercontent.com/34599995/153364419-751d9356-9849-4653-8c71-4f70b1fef75c.png)
Custom field "wrong display" after update...

**Comment by chrisi51** [comment]
just wanted to report the same :)

![image](https://user-images.githubusercontent.com/2156760/153836527-51e1efa2-04e7-4569-9011-d66d96404912.png)

The sum is not working for a long while. at least 5.80 probably even longer. As we did not used it, i don't wanted to report a bug, which probably is none :)

I'm on UCS 5.99.0

@mfilser could this be a small issue, you could fix between your bigger improvements? :)
really appreciate your contributing

**Comment by xet7** [comment]
Implementing sum of fields feature is still In Progress, it's not finished yet.

Moved to #3796

**Comment by mfilser** [comment]
@chrisi51
Thank you a lot for your kind words 🙂

I think @xet7 has it already on his roadmap
