### ISSUE TITLE
Wow MongoDB Atlas not for WeKan next week???

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4351]
I just received this email:

> Meteor 2.6 Release
>
> If you are using MongoDB Atlas, M0/M2/M5 clusters will automatically be upgraded to MongoDB 5.0 next week. You need to upgrade your Meteor app before this happens or your app will stop working.
>
> The Meteor 2.6 release has several important updates, one of which being the MongoDB upgrades, which you can read more about in our [blog post](https://blog.meteor.com/meteor-2-6-and-mongo-348fb2287716) regarding the changes.
>
> It’s important to read the [Migration Guide](https://guide.meteor.com/2.6-migration.html) step by step before upgrading.
>
> Our team has outlined all of the updates in our changelog, but we've also highlighted some of the modifications below. 
>
> Highlights:
> • MongoDB Node.js driver Upgrade from 3.6.10 to 4.3.1
> • MongoDB Server 5.x Support
> • Embedded Mongo now uses MongoDB 5.0.5
> • Dark theme-specific splash screens on iOS and Android
>
> For full details on the release, click on the link below to access our Meteor changelog.

So, if you are using MongoDB Atlas with WeKan, next week WeKan will not work, because WeKan is not yet upgraded to newest Meteor. WeKan is not yet compatible with newest Meteor and MongoDB 5.x.

**Comment by Shirobachi** [comment]
That's pretty old issue, but that sucks a bit. I wish we could use MongoDB Atlas..

**Comment by xet7** [comment]
@Shirobachi 

You should be able to. Current newest WeKan is compatible with MongoDB 5.x, as can be seen in list of versions at Download section of https://wekan.github.io

Sorry about old info.

**Comment by Shirobachi** [comment]
No worries, that's actually kinda my fault.
Actually, I tried to use MongoDB atlas, but does not work. Do you mind have a look for compose file? Or maybe is a better place where I could ask for help?
