### ISSUE TITLE
Feature Request: Add checkbox for minicards to mark them done

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4356]
For faster cardmanagement, it would be nice if you could add a checkbox on minicards. So you don't have to open the card, click on burgermenu and then go down to 'archive card' just to get it from the board. 

So clicking the checkbox would send the card to archive.

![Done_Button](https://user-images.githubusercontent.com/92315677/153855327-9fe052fb-1ea6-45ac-94df-8b0d8e32afe8.jpg)

**Comment by KoshNaranek** [comment]
Custom Field + Rule?... just saying ;-) "Done/Closed" should be column, no?

**Comment by Meeques** [comment]
@xet7 
This has nothing to do with the checklist. Every card would get a checkbox so you can 'delete' cards with just one click. The user would click inside the circle on the minicard and then the card goes to the archive. Please let me know how much funding would be needed for this. 
Kind regards

**Comment by shrippen** [comment]
Sorry to reopen this - you are correct that WeKan already has this feature. But could the GUI be changed to trigger this behaviour like Meeques mentioned via a checkbox directly on the card without having to click Multi-Selection first?

This would reduce the amount of clicking from 3 to 1.

Would this require funding?
