### ISSUE TITLE
Feature Request: Ability to read board without WeKan account

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4366]
I am requesting a feature that lets you share a temporary link to users without a WeKan account. So that these non-wekan-users can read (but not edit) a board. The authorisation to read would end after a certain period of time that must be set by board creator.
Again, let me know the amount of funding that would be needed for this.

Thank you!

**Comment by xet7** [comment]
@Meeques 

Do you mean existing feature of setting Private board to Public?

**Comment by Meeques** [comment]
@xet7 
for our instance private is private but public is only public internal to the university. So if you have no university account, you cannot access public boards.

**Comment by xet7** [comment]
@Meeques 

Would exporting board to HTML work?

Are those non-wekan-users in university network? Or would there need to be a way to sync read-only wekan board to some external webserver?

**Comment by xet7** [comment]
There is existing WeKan feature of export board to HTML, but I don't know is it enough.

**Comment by xet7** [comment]
That export board to HTML will later get some fixes, so that in that static exported board website, after fixing, cards can be opened.

**Comment by Meeques** [comment]
@xet7 

We have to discuss this internally. I will get back to you. Thanks!

**Comment by Meeques** [comment]
We came to the conclusion that it would be best for us to create another instance of WeKan for external partners. So no need for any additional feature. Thanks!
