### ISSUE TITLE
Document name changed after download - google chrome

### ISSUE THREAD

**Issue by phamorais** [wekan/wekan#4367]
Guys!

After update to version 6.05, when we download files, it has its title changed as shown in the print below
![image](https://user-images.githubusercontent.com/35368369/154534832-fab0af92-2e1c-4c0b-9e82-02c9db39a496.png)

after download

![image](https://user-images.githubusercontent.com/35368369/154534876-30e089de-d099-4241-95fc-ddbccca05935.png)

Obs: in Firefox its Ok.

**Comment by xet7** [comment]
Well, maybe in filenames spaces could be replaced with _ . But only after https://github.com/wekan/wekan/pull/4336 is merged.

**Comment by phamorais** [comment]
@xet7 thx!

Its already merged. Its possible fix this bug now?

**Comment by phamorais** [comment]
@xet7 ?
