### ISSUE TITLE
Wekan broken on mongo restore

### ISSUE THREAD

**Issue by yash-hive** [wekan/wekan#4369]
## Issue

We have to transfer wekan from one server to another for some reason. So we created a backup at first server as recommeneded and restored it on 2nd server. We are able to get all the data back, but this breaks the wekan for some reason. We are unable to upload attachments, delete comments and unable to perform some other utilites.
### Server Setup Information

* Did you test in newest Wekan?: Yes, we tested on 5.25, 6.00 and on latest
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Ubuntu 20.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Server A - Docker, Server B - tried both docker and bundle/source.
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx 
* Node.js Version: v12.22.6
* MongoDB Version: v4.4.12
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? latest chrome and firefox

#### Reproduction Steps
Wekan breaks attachment upload, comments deletion, cards movement and other important utilies when database is restored from a backup.
It works fine if we create a completely new database without chaging other things, but as soon we restore the backup, wekan breaks.
![wekan_issue](https://user-images.githubusercontent.com/95089881/154754725-385d6599-9192-46a5-933f-b00cee168144.gif)

Now if we just use a new database from scratch, everything works fine, the attachments are uploaded in fractions of seconds. But as soon as we restore, it breaks. :disappointed:

**Comment by yash-hive** [comment]
@xet7 Thanks for quick response.

I tried repairing mongoDb Database as you suggested, but it didn't work, still stuck on same issue.

Also looking into the logs of repairing mongoDb, it couldn't find any corrupt data, so it didn't repair anything.

Anything else which might be causing this behaviour.

**Comment by xet7** [comment]
@yash-hive 

Is there something slowing down, like:
- Global Webhooks enabled?
- Per board webhook? If some webhook does not get immediate 200 response, it slows down system
- Many IFTTT Rules?
- Many users using board at the same time?
- Big attachments at same board?
