### ISSUE TITLE
Support Mobile Browser

### ISSUE THREAD

**Issue by floatinghotpot** [wekan/wekan#437]
If WeKan works in mobile device (at least mobile browser as the first step), it will be much more convenient. Maybe we can consider raise the priority to support mobile device. I'd like to open a tracker to discuss how to implement this feature.

Here are the screen size of mobile browser:
iphone, width 320px
iphone6 plus, width 414px
and more:
http://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions

My thought is when detecting mobile device, adjust all the topmost UI to fit the full screen. The related UIs are:
1. pop up (current width is fixed 300px).
2. carde details (current width is fixed 470px).
3. user login form (current width is fixed 325px).
4. sidebar (current width is fixed 248px).
5. lists (current width is fixed 270px).

I will try prototyping the above ideas, and any comments are welcome.

**Comment by nata-g** [comment]
@floatinghotpot Question: Does this sizing dimensions apply only to Iphone devices or android phones as well?

**Comment by floatinghotpot** [comment]
I suppose the approach should apply to all small screen, even a PC browser window narrower than a fixed width, say, 420px.

**Comment by floatinghotpot** [comment]
It's quite smooth for the prototyping, and I even think it's good enough as a new feature. 

@mquandalle Please help to review. PR is created, #442. 

Some screenshots, FYI:

Board List & Board View:
![img_3162](https://cloud.githubusercontent.com/assets/2339512/11846408/763a409e-a453-11e5-8999-d716dc1fc6ff.jpg)  ---  ![img_3163](https://cloud.githubusercontent.com/assets/2339512/11846419/88838580-a453-11e5-9c5e-7b60a5f6e234.jpg)

Card View, Sidebar:
![img_3164](https://cloud.githubusercontent.com/assets/2339512/11846491/db2c5e42-a453-11e5-838d-84b19b7cad7d.jpg) ---  ![img_3167](https://cloud.githubusercontent.com/assets/2339512/11846517/ef07084a-a453-11e5-9052-03ad0b8c18c8.jpg)

Pop-over, & Form:
![img_3165](https://cloud.githubusercontent.com/assets/2339512/11846536/079dbc5a-a454-11e5-84e1-2e3586581d6a.jpg) --- ![img_3166](https://cloud.githubusercontent.com/assets/2339512/11846546/0e6b8ab2-a454-11e5-98a8-f36ead93828d.jpg)

**Comment by mquandalle** [comment]
Woah, I didn’t expect that to go that fast! It looks great from the screenshots. I’m super excited to review and merge that :)
