### ISSUE TITLE
Import Done Button do not redirect

### ISSUE THREAD

**Issue by cristese** [wekan/wekan#4374]
## Issue
After a importing a board via JSON, the botton done ist shown.
by clicking on done button, nothing happends.

### Server Setup Information
Wekan-snap
WeKan Version: 6.05.0
Meteor-Version: 2.2
Node-Version: 12.22.10
Mongo-DB-Version: 3.2.22
MongoDB-storage-engine: wiredTiger
OS: Linux x64
OS Version: 4.15.0-143-generic

### Problem description
After a importing a board via JSON, the botton done ist shown.
by clicking on done button, apparently nothing happends. But if you go to the boards overwiev, the imported board ist shown many times. reproducing this problem showed, that the click of done create the imported board. because nothing happens by clicking the done button, user clicking much more times on the done button. per click on done, one importet board is created. so 6 times clicking on done = 6 boards

#### Reproduction Steps

Export Board to JSON. 
Create new Board -> Import
Import from Export (JSON Code).
Button Import.
Button Done (Problem).

**Comment by Ben0it-T** [comment]
@xet7 
I think I got something
https://github.com/wekan/wekan/blob/0712309266b78847524e237d9e4bf46d4db87f6a/client/components/import/import.js#L80-L94

We need to subscribe to the new created board
```js
const subManager = new SubsManager();
subManager.subscribe('board', res, false);
```

However, `Utils.goBoardId(res);` doesn't work... strange.
If I replace by `FlowRouter.go('home');`, it seems to do the job.

![wekan-import](https://user-images.githubusercontent.com/37017213/156935801-f46df053-0e0f-4f64-97af-5741c5cc027c.gif)

Need to dig a little more

**Comment by xet7** [comment]
@Ben0it-T 

Cool !! If you get it working, please send PR. Thanks!

**Comment by Ben0it-T** [comment]
@xet7 
Interesting !
If I wait for the ready status of subscription, it seems to work like a charm.
```js
subManager.subscribe('board', res, false);
Session.set('fromBoard', null);
Tracker.autorun(function() {
if(subManager.ready()) {
  // all the subscriptions are ready to use.
  const board = Boards.findOne(res);
  if (board) {
    console.log("OK ! => " + board._id);
  }
  Utils.goBoardId(res);
}
});
```

<img width="1245" alt="wekan-import" src="https://user-images.githubusercontent.com/37017213/157112484-a81441bd-cc67-45ab-a543-2b6dd1739e2d.png">


I keep digging but I think we have something !

**Comment by Ben0it-T** [comment]
![wekan-import-02](https://user-images.githubusercontent.com/37017213/157114138-18b45803-4b89-4533-8bd6-8d8085fa4698.gif)

**Comment by xet7** [comment]
@Ben0it-T 

If you can find out how to have subscriptions to only visible swimlanes, lists etc, that would speed up working with big boards a lot. Like starting subscription when list is visible, and stopping when it's not visible.

**Comment by Ben0it-T** [comment]
@xet7 
Do you have a json test file (a big board test export)?

**Comment by Ben0it-T** [comment]
@xet7 
`Tracker.autorun` (like in https://github.com/wekan/wekan/issues/4374#issuecomment-1061103637) or using a callback like   
```js
const subManager = new SubsManager();
subManager.subscribe('board', res, false, function() {
  Utils.goBoardId(res);
});
```
have perverse side effects !

However, using 
```js
let title = getSlug(this.importedData.get().title) || 'imported-board';
FlowRouter.go('board', {
  id: res,
  slug: title,
})
```
do the job (_no need to subscribe_).

![wekan-import-board](https://user-images.githubusercontent.com/37017213/158068530-a2ce62a4-32bb-4c90-b0f3-333dfe3e5f3e.gif)

**Comment by Ben0it-T** [comment]
@xet7 
I think we can do the same for "Duplicate Board" and "Create board from template"
