### ISSUE TITLE
Changing list color in Firefox does not save

### ISSUE THREAD

**Issue by s3rvant** [wekan/wekan#4376]
## Issue
After clicking Save within Set Color on a List the list color changes, then page refreshes without saving the change.

This occurs on Firefox 96 (PopOS 21.10) however the change saves properly in Chromium 98.

## Server Setup Information
Wekan 6.05 via Snap on Ubuntu Server 20.04 behind Nginx with Lets Encrypt TLS.

## Logs
These are on page load; no further log entries appear between clicking Save button and page refresh:

**Chromium**
WebSocket connection to 'wss://wekan.example.com/sockjs/964/string/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

**Firefox**
GET wss://wekan.example.com/sockjs/291/string/websocket [[HTTP/1.1 400 Bad Request 225ms]]()
Firefox can’t establish a connection to the server at wss://wekan.example.com/sockjs/291/string/websocket.

**Snap**
No log entries are generated from this - checked with both Chromium and Firefox

**Comment by xet7** [comment]
Try newest wekan.

Also see wiki for configuring enabling websockets.
