### ISSUE TITLE
Logged as someone else on boards.wekan.team / login forbidden.

### ISSUE THREAD

**Issue by vdst** [wekan/wekan#4378]
## Issue

I was logged as someone else on https://boards.wekan.team. My own account doesn't seem to exist anymore.

### Server Setup Information

No information can be provided about the setup, as it was hosted by the official Wekan website.

### Problem description

Today, I noticed that my account wasn't actually mine. The name of the account wasn't mine, nor was the profile picture. I could access my personal boards without any issue, but I was logged as someone else. In an attempt to fix it, I logged out.
When trying to log back in, the website returned "login forbidden".

Creating an account with my old account's name worked. Since no two accounts can have the same username, it leads me to believe that my original account doesn't exist anymore, or was replaced by someone else account. Loosing access to all of my boards and work.

The authentication method used was : Password. (not with Google / OAuth2).
The issue happened today, a few hours ago.

I did not take note of who I was logged in as.

![wekan](https://user-images.githubusercontent.com/29022567/155355561-4c1d55f1-eb6c-417b-9f7f-ecc754d9e6f9.PNG)

**Comment by xet7** [comment]
@vdst 

Please send your username and email address to support@wekan.team so I'll try to figure it out.

**Comment by xet7** [comment]
@vdst 

It seems that there are 2 similar email addresses.

If you are logging in with username/password, please check that in login dropdown you select password, and that you are not logged into Gmail. For example, login with username/password in new incognito window.

**Comment by xet7** [comment]
@vdst 

Of your latest login, there is only 6 minutes difference between your hotmail and gmail logins. So I presume both are your accounts, and you just accidentally logged into wrong one.

**Comment by xet7** [comment]
Anyway, if you still have problems, please email support@wekan.team , like described at privacy policy:
https://wekan.team/privacy/

**Comment by xet7** [comment]
@vdst 

Yes, sending email is preferred, from account you have at boards.wekan.team , to see that it's real email address. Email addresses should not be added to these public GitHub issues.
