### ISSUE TITLE
Feature Request: Show Logo on Tab

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4381]
If one has too many tabs open, one cannot distinguish between what's WeKan and what's not. As long as I can see the name of the board in the tab it's ok but I know that many people work with a crowded tab bar where only the logos are displayed. I propose the 'W' of the word mark 'WeKan'.
Thank you!

**Comment by helioguardabaxo** [comment]
Change favicon would be a alternative.

I created a prototype with "We" because is currently mark
![wekan-logo](https://user-images.githubusercontent.com/24301085/161616439-67fd8c62-cf36-41c0-8f17-40201153ff93.png)

What do you think?

**Comment by Meeques** [comment]
Thank you! I think the new one is definetly preferable.
