### ISSUE TITLE
No possibilty to register first user at initial login with v6.07  (snap install)

### ISSUE THREAD

**Issue by urmel1960** [wekan/wekan#4383]
## Issue
I installed latest wekan v6.07 with snap on a new ubuntu 20.04 LTS VM. When you access initially wekan via browser there is no chance to register the first user in the login dialog. 

I then checked a fresh v6.05 release install via snap - it is working properly and I can register my uswer at initial login.

### Server Setup Information

* Did you test in newest Wekan?:
tested with v.6.07 via snap - this is the release where the issue occurs
tested with v6.05  via snap - this release has no problem with the described issue

* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
yes - no problem to access browser interface

* Operating System:
Ubuntu 20.04.3 LTS x64  VM 

* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
snap 

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
none

* Node.js Version:
see snap

* MongoDB Version:
see snap

* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
FF 97.01 (64bit)
Chrome Version 98.0.4758.102 (Offizieller Build) (64-Bit)

### Problem description

 see above
#### Reproduction Steps

clean install wekan v6.07 via snap on Ubuntu 20.04
access wekan with browser

**Comment by xet7** [comment]
Just a moment, I'm figuring out how to fix this...

**Comment by xet7** [comment]
As seen with some [MongoDB GUI](https://github.com/wekan/wekan/wiki/Backup), at `settings` table is values `disableRegistration` and `disableForgotPassword`, those can be edited to be true or false. There is somewhere some incorrect default value or something, I'm trying to find how to fix it so that it would work and not show any errors.

**Comment by urmel1960** [comment]
seems that this came with one of the releases after 6.05. standard configuration was enabled with 6.05

Maybe it is in here config/accounts.js ?

```
let disableRegistration = true; 
let disableForgotPassword = true;
```

**Comment by xet7** [comment]
@urmel1960 

But changing those is not enough. When first user has registered to WeKan and becomes Admin, it should be possible to use Admin Panel to set those true or false, but it does not work yet with those changes. I'm currently trying to use Meteor method in `config/accounts.js` to get correct values, because I did not get PubSub working there. I'm currently on my about 5th try to find some way to fix it. If I don't figure it out, well, I'll just rewrite WeKan.

**Comment by xet7** [comment]
I presume it's just just some Javascript [Wat](https://www.destroyallsoftware.com/talks/wat) like some mentioned here:
https://heyjavascript.com/javascript-string-to-boolean/

**Comment by xet7** [comment]
Well, I need to sleep now, and at morning I'm in meetings for many hours. I'll try to continue fixing this tomorrow evening.

If would be very helpful if some other WeKan contributor had time to figure this out and send PR, it would speedup releasing a fix. I just don't know is this important enough for any other contributor.

**Comment by Ben0it-T** [comment]
@xet7 
Probably something to dig
Meteor calls seem to be asynchronous calls
https://github.com/wekan/wekan/blob/4bcddcc98a91fcf628733997e1d4ae1e0576c779/config/accounts.js#L6
https://github.com/wekan/wekan/blob/4bcddcc98a91fcf628733997e1d4ae1e0576c779/config/accounts.js#L13

**Comment by Ben0it-T** [comment]
@xet7 
For the "string to boolean",
In `models/settings.js`
```js
    getDisableRegistration() {
      const setting = Settings.findOne({});
      if (!setting.disableRegistration) {
        return false;
      } else {
        return (`${setting.disableRegistration}` === 'true');
      }
    },

   getDisableForgotPassword() {
      const setting = Settings.findOne({});
      if (!setting.disableForgotPassword) {
        return false;
      } else {
        return (`${setting.disableForgotPassword}` === 'true');
      }
    },
```

And in `config/accounts.js`
```js
Meteor.call('getDisableRegistration', (err, data) => {
  if (!err) {
    disableRegistration = (data === 'true');
  }
});

Meteor.call('getDisableForgotPassword', (err, data) => {
  if (!err) {
    disableForgotPassword = (data === 'true');
  }
});
```


For the 2 calls,
I tried without success:
- with Future (fibers/future),
- promise (await new Promise)

I have no other idea at the moment.

**Comment by urmel1960** [comment]
As far as I could test so far with a new snap installation of v6.08, registering the first user at initial login works now again .
Thanks a lot for your extra weekend effort !
