### ISSUE TITLE
Disable forget password does not work on v6.08

### ISSUE THREAD

**Issue by urmel1960** [wekan/wekan#4384]
## Issue

As far as I could test with a new snap install of v6.08 and as well on an updated existing install of  wekan (update to v6.08) the functiionality to disable forget password does not work.

You still get the password forget dialog and an email is sent with a link leading to the password reset page. 

### Server Setup Information
* Did you test in newest Wekan?:
*yes v6.08
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
yes
* Operating System:
Ubuntu 20.04 LTS 
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
*snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
n/a
* Node.js Version:
see snap
* MongoDB Version:
see snap
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
FF latets availabale version
Chrome latest available version

**Comment by xet7** [comment]
@urmel1960

Does it work in WeKan v6.09 ?

**Comment by Ben0it-T** [comment]
It works in WeKan v6.09.
Thanks !

**Comment by urmel1960** [comment]
@xet7 

Sorry for the late response ... it was late this night  - and therefore late this morning ...

Thanks for fixing this - I tested it with an existing installaton and with a brand new one - all good so far.

**Comment by Ben0it-T** [comment]
@xet7 
if `isDisableForgotPassword`, at-pwd-link is hide => `$('.at-pwd-link').hide();`
if `isDisableRegistration`, at-signup-link is hide => `$('.at-signup-link').hide();`
But they are always present on the page, they are just hidden

I wonder if it wouldn't be better to:
- $('.at-pwd-link').remove();
- $('.at-signup-link').remove();

No ?

**Comment by xet7** [comment]
@Ben0it-T 

Maybe, I have not yet tested does that work.

The proper way would be to only show required HTML on browserside like [in my PHP prototype](https://github.com/wekan/php/blob/main/public/index.php#L318-L334), and not that browserside Javascript show hide JQuery stuff. It's just that Meteor makes hard stuff easy, and easy stuff hard.
