### ISSUE TITLE
Feature Request: Automatic saving of card entries

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4386]
If I write something in the description of a card, or add a checklist, add a subtask, etc. I have to save at every field. Many people forget to save or accidentally click somewhere so the card closes. In these cases nothing gets saved and the entries get lost.
Is there a way you could install an automatic saving of card entries?
If you can, please tell me the amount of funding that would be needed for this.
Thank you!

**Comment by xet7** [comment]
500 euro.

**Comment by Meeques** [comment]
After I did some thinking, this would be an over all product improvement that, in my humble opinion, you should put on the roadmap without funding.

**Comment by xet7** [comment]
Moved to #4823
