### ISSUE TITLE
Feature Request: Select triggering activities for outgoing webhooks

### ISSUE THREAD

**Issue by webenefits** [wekan/wekan#4388]
## Description
We have been using Wekan for a year now and are very happy with it so far. We want to stay with Wekan as project management and are therefore willing to donate for a few of our wishes now. :blush: 

This feature request is concerning **webhooks**. We currently have the problem that the generated comments in our Mattermost (via webhook) are just too many and so our channels are a bit spammed. In detail, we have for each project a Wekan board and a matching Mattermost channel in which we communicate in the team. Now both should act in symbiosis with each other, so that comments in Wekan or a new card in the respective board sends a matching post in Mattermost, but without flooding the channel too much with messages.

Our request would be an option similar to "webhooks-attributes" ([Supported settings keys »](https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys)), where you can easily set for which activities in Wekan the webhook is triggered. Specifically, we just want notifications about:
- Newly created cards
- Moved cards
- New comments

Example configuration code:
```
snap set wekan webhooks-activities='cardcreated,cardmoved,commentcreated'
```

How complex would such a customization be?

### Server Setup Information
* Wekan Version: 6.09.0
* Operating System: Ubuntu 18.04.6 LTS
* Deployment Method: Snap
* Node.js Version: 12.22.10
* MongoDB Version: 3.2.22
* Webbrowser: Firefox and Chrome

**Comment by webenefits** [comment]
Feel free to let me know if you want me to create the idea/feature request rather as "Discussions → Ideas" instead of an issue here.

**Comment by xet7** [comment]
Hmm, maybe 500 or 1000 euro? Depends how many needs to be customized, some or all.

https://wekan.team/commercial-support/

**Comment by webenefits** [comment]
Hi @xet7,
well you'll have to tell me how much to adjust, no? :grin: Or are there still unclear requirements or do you still have questions?

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2026#issuecomment-1058436251

**Comment by webenefits** [comment]
Hmm ok, since the request for "Feature Request: Push Notification, and notifications area with settings #2026" is already open for a very long time and it is also not clear when this will be implemented, we can unfortunately not donate anything for this. In addition, in my opinion, this is also a different topic, even if there are connections or intersections. Sorry :confused:

**Comment by xet7** [comment]
@webenefits 

I can keep this issue open, if that is more clear for you.

In general, after something has been paid, development can be started. But without payment, development does not start. It depends do you need this feature. I hope that is clear enough. Please ask more questions, if you need more clarity.

**Comment by webenefits** [comment]
Hello @xet7 
I would like to take up this topic again. :grin: 

To communicate it clearly again:
We would need a configuration feature to minimize outgoing notifications by webhooks, so that notifications are **only** generated when
1. a new card has been created
2. a card has been moved
3. a card has a new comment

Would it be possible to implement this feature for 500,- €?

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/5106 . Thanks to @ipyramiddev !
