### ISSUE TITLE
New user can't create an account if he gets an board invitation beforehand

### ISSUE THREAD

**Issue by h8h** [wekan/wekan#440]
Bonjour 

I pulled the latest commit: `677e9937e0c1872bfe4ec5ce87bf2a8ca99febe1` and run `meteor build .build --directory` with user privs. After that I have to install some npm libs `semver` `source-map-support` and `underscore` with root rights. Finally I successfully upgraded wekan and wanted to test the email invitation for the boards. I invited an non-existing user. The user receives the link and after entering the webpace the user gets:
`Board not found
This page may be private. You may be able to view it by logging in.`

If the user then wants to create an user account its not possible with that address any more. There are two usecases:

Usecase 1:
Invitation send to wekanuser@domain.tld
User tries to sign up with
Username: User1 
Email: wekanuser@domain.tld
Password: xxxx
Throws exception (Javascript - Console)

```
Exception in delivering result of invoking 'ATCreateUserServer': L.prototype.atPwdFormEvents["submit #at-pwd-form"]/<@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:162:28745
e.bindEnvironment/<@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:5:6832
._maybeInvokeCallback@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:78:8275
.receiveResult@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:78:8583
._livedata_result@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:78:19786
u/o@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:78:6561
._launchConnection/t.socket.onmessage/<@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:78:567
A.forEach@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:3:863
._launchConnection/t.socket.onmessage@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:78:523
v</r.prototype.dispatchEvent@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:77:1119
v</C.prototype._dispatchMessage@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:77:14711
v</C.prototype._didMessage@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:77:15601
v</C.websocket/o.ws.onmessage@domain.tld/board/ab2c582d3f25de44cf0d469fea4d31a7778f47bb.js?meteor_js_resource=true:77:17702
```

Usecase 2:
Invitation send to wekanuser@domain.tld
User tries to sign up with
Username: wekanuser 
Email: wekanuser@domain.tld
Password: xxxx
Result:
`Username already exists.`

The user can reset the password to receive his first password :)

**Comment by Pacific01** [comment]
I had the same error and i was able to solve it. It would be nice if a guest could choose his password somehow in the case he was invited.

For now i removed the user in mongo database and registered it by normal mode (without invite him to a board)

`
mongo
use wekan
db.users.find({address:<email address of your user>})
db.users.remove({ _id:"<user id you want to remove>"})
`

I hope that works for people who have the same problem.

bye.

**Comment by xet7** [comment]
Invitations do work already.
