### ISSUE TITLE
Boards.uniqueTitle not working as expected

### ISSUE THREAD

**Issue by Ben0it-T** [wekan/wekan#4400]
### Server Setup Information
* Did you test in newest Wekan?: yes - Wekan 6.09 (snap) / Wekan 6.11 (local)
* Did you configure root-url correctly so Wekan cards open correctly? yes
* Operating System: Debian 10
* Deployment Method: snap

### Problem description
At "All boards" (_My Boards)_, when "copy" board ("_Duplicate Board_"), "copyTitle" returns "uniqueTitle" only if board.title contains "`[d+]`".

![wekan-duplicate-01](https://user-images.githubusercontent.com/37017213/156915564-54c121a6-3735-4665-8b32-cea5dccd4ef4.gif)

![wekan-duplicate-02](https://user-images.githubusercontent.com/37017213/156915567-1a270943-a81a-41a1-8a57-925a1b4db1f2.gif)

#### Reproduction Steps
1. Create a board, ie. "Test board"
2. At "All boards" (My Boards), clicks on "Duplicate Board"

#### Logs
no error in browser console / snap

### Discussion
I think this was introduced by https://github.com/wekan/wekan/pull/3526
https://github.com/wekan/wekan/blob/d52e0bcb6e62ed11c726d2fd0474320fedcfbc6a/models/boards.js#L1473-L1477

If I change/revert to
```js
return `${m.groups.title} [${num + 1}]`;
```
It seems to work as expected

![wekan-duplicate-03](https://user-images.githubusercontent.com/37017213/156916155-e0afe688-23f6-4b4e-8da5-57d235796185.gif)
 
@jrsupplee @xet7 
Is it ok for you if I send PR

**Comment by xet7** [comment]
@Ben0it-T 

Yes.
