### ISSUE TITLE
Paste in discription of a Card is not possible

### ISSUE THREAD

**Issue by Thorgrimson** [wekan/wekan#4406]
I try to paste some text via strg-c strg-v and right-click menu in the discription of card. but it wont work. pasting in checklists is possible.
Dont know if this is a bug or not implemented?

greatings  and thanks for the software ;)

**Comment by Thorgrimson** [comment]
in comments pasting is only possible via right-click menu

**Comment by Meeques** [comment]
For me, this works. Which browser are you using?
