### ISSUE TITLE
enhancement idea for the "new user invitation for private board" workflow  

### ISSUE THREAD

**Issue by araczkowski** [wekan/wekan#441]
HI,
right now when the new user is invited to the private board the workflow is:
1. go to the the link provided in the email, to see the message that
   'This page may be private. You may be able to view it by logging in.'
2. click the the "logging in" link
   to go to the Sign in page
3. click the "Register" link
   to finally Create an Account

in my opinion this is little confusing - first time I thought that something is broken.

During the invitation sent we know that the user is new, so in my opinion we should give him a better flow - special url to confirm a new account (provide a password).

What do you think? 
If it will be OK I think that I can provide this via pull request.

**Comment by alerma** [comment]
I love the idea!

**Comment by alayek** [comment]
hi @mquandalle and @floatinghotpot, I have decided to take this on. I am planning to raise a PR to resolve this.

I would like to present my approach briefly for review.

The invite email provides the new user an URL of the form `/b/:board_id/:board_name_slug/`. I am planning to create a new route to render a different template; something like `/b/join/:board_id/:board_name_slug/`.

As of now, my plan is to create a new route in `config/router.js`; and render the template for joining the service (registration).

But I have a question - should this new incoming / onboarding user be able to join the board like any other member? The inviter specified an email ID; so the template cannot allow for the new joinee to edit the email ID, and let them sign up with a different email ID.

For instance, say I sent a request to let `abc@abc.com` to join my board. And then, when **abc** opens the joining page, he should join with the email ID `abc@abc.com`, not something else.

This would also help the system keep track of whether or not invited person joined.

Another way to achieve this (email verification on invite based joining) would be to use some special URL (I am not sure what the name is, but it's kind of like URLs sent in emails which confirms the email ID) in the invite.

The server would be able to keep track of who is joining, and notify the inviter that the invitee has joined. 

If the invitee uses different email from the one used by inviter, to sign up for the application, we would just send another confirmation email to his choice of email ID.

**Comment by araczkowski** [comment]
I just want to add, that when I described this issue, my case was that I've received only the "InviteToBoard" email - I didn't receive the "enrollAccount" email.
That is why I was so confused...
When I checked this again (for new account) I recived first the "enrollAccount" then the "InviteToBoard" message. So now this is not so strange as it was for the first time. 

Of course there is still a big chance that new user will first click on the link from the "InviteToBoard" message (the most recent message).
To improve this case maybe we can:
1. add a userId to the "InviteToBoard" url
2. when the user will go to this url, we can check if the account (via the userId from url) was already enrolled
3. if yes we can redirect to the board url (or to the login page if the board is private), if no we can redirect to the  "enrollAccount" for this particular user (userId) 

But this are details, now when I received the "enrollAccount" I don't mind if you close this issue - it is up to you.

**Comment by mquandalle** [comment]
@alayek is actually working on improving this flow, I don’t have all the details but it’s probably better to keep this issue open for now.

**Comment by alayek** [comment]
When a user adds another user by Email ID, the new user gets added to the board with `userID` as the email ID, before the `@` symbol. Their email ID gets created as the email ID provided by the user.

@araczkowski, currently we are planning for it to be like this - 
- An invited person receives the email.
- The link in the email takes her to `changePassword` or `resetPassword` route, as the user only needs to pick a password.
- Once the password is set, the user is taken directly to the board she was invited to.

@mquandalle, should it be `changePwd` or `resetPwd`?

**Comment by xet7** [comment]
Moved to #3022
