### ISSUE TITLE
Feature Request: Ability to have folders on board overview

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4414]
Hello, I got a request from a somewhat poweruser if it would be possible to put boards on the overview page into a folder. Because the "all boards" page gets loaded quickly for some people (like me). This is how Taskcards does it: (Ordner = folders)

![BeispielWeKanBoards](https://user-images.githubusercontent.com/92315677/158349096-7205db56-838a-4f6e-88ae-d454bfe12f38.png)

Boards that are not sorted into a folder are displayed under 'Pinnwände' (Boards).

**Comment by Meeques** [comment]
Ordner = folder

**Comment by xet7** [comment]
Moved to #4791
