### ISSUE TITLE
Import: subtasks are not taken over

### ISSUE THREAD

**Issue by cristese** [wekan/wekan#4420]
## Issue
After a importing a board via JSON, subtasks are lost. 

### Server Setup Information
Wekan-snap
WeKan Version: 6.05.0
Meteor-Version: 2.2
Node-Version: 12.22.10
Mongo-DB-Version: 3.2.22
MongoDB-storage-engine: wiredTiger
OS: Linux x64
OS Version: 4.15.0-143-generic

### Problem description
After a importing a board via JSON, subtasks are lost.  In exportet JSON file is subtasksDefaultBoardId set.
But after importing the board, subtasksDefaultBoardId of the board is empty in mongoDB. 

#### Reproduction Steps
Export Board to JSON.
Create new Board -> Import
Import from Export (JSON Code).
Button Import.
Subtasks are lost

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
