### ISSUE TITLE
Wekan board can not be displayed 

### ISSUE THREAD

**Issue by gavinWithGu** [wekan/wekan#4425]
Hi, I build the wekan by rebuild source with rebuild-wekan.sh and login the system successfully  

At first I can see the content and everything seems ok , but today when I login and check the board I created couple of day ago, there is a loading picture show on the page and nothing displayed

<img width="949" alt="微信图片_20220321203807" src="https://user-images.githubusercontent.com/9295466/159262454-844bb49e-1a9b-46d9-97d1-3a4061fdc93b.png">

I have checked the chrome console and all ajax response code is 200 or 301 .   
So what I can do to fix this problem? 

Thanks

**Comment by xet7** [comment]
@gavinWithGu 

Maybe there is some problem with your manually built WeKan.

You can [backup](https://github.com/wekan/wekan/wiki/Backup) and restore to Snap (or Docker) WeKan, try does it work there.

**Comment by gavinWithGu** [comment]
Thanks for the reply
If I use snap or docker way. When I change source code , can I apply it in snap or docker?

**Comment by gavinWithGu** [comment]
> @gavinWithGu
> 
> Maybe there is some problem with your manually built WeKan.
> 
> You can [backup](https://github.com/wekan/wekan/wiki/Backup) and restore to Snap (or Docker) WeKan, try does it work there.

Thanks for the reply
If I use snap or docker way. When I change source code , can I apply it in snap or docker?

**Comment by xet7** [comment]
@gavinWithGu 

You can apply with Docker:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L136-L138

**Comment by xet7** [comment]
@gavinWithGu 

Does board open now?

**Comment by gavinWithGu** [comment]
Yeah , Probleam sloved now , Thank you very much
