### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by huornlmj** [wekan/wekan#4427]
Stale or idle cards changing colour would be very useful.

**Comment by xet7** [comment]
@huornlmj 

Do you mean this? #3984

Currently cards have created and last modified dates. Maybe calculate if card is older than some amount of days? Or having those times and colors configurable, like Board Settings / Card aging ? Or how should it work?

**Comment by huornlmj** [comment]
Yes @xet7 that's exactly it.  I didn't want to reference Tr33l0 directly.  Closing this issue and following #3984 instead.
