### ISSUE TITLE
[Wekan Docker 6.11] delete a subtasks

### ISSUE THREAD

**Issue by ASLLR** [wekan/wekan#4429]
Hi everyone, 

I use wekan 6.11 in docker-compose environment but this issue is present from anterior versions. 
It's very difficult to delete a subtasks from cards. When i click on delete the window to confirm deletion is very big and is only accessible if we unzoom all the page.
#### Reproduction Steps
1. Create a Board
2. Create a Card
3. Create a subtasks
4. Try to delete the subtasks
![delete](https://user-images.githubusercontent.com/37147055/159493846-9725edf7-3cb2-4011-97e8-6992b2ef03c5.png)

Thank you in advance,
Best Regards

**Comment by avatar1024** [comment]
In 6.18, the delete confirmation dialogue has changed and you shouldn't have this issue any more.

**Comment by ASLLR** [comment]
Hello, thank you for your answer. I tried and you're right, this issue is solved in 6.18.

Have a nice day
