### ISSUE TITLE
"My Cards" + "Due Cards" not showing. 

### ISSUE THREAD

**Issue by lealanana** [wekan/wekan#4430]
Hi Everyone

## Issue
"My Cards" + "Due Cards" not showing with all the users accounts including admin account.

I have installed wekan via cloudron. Everything was running smoothly until the update from v4.18.2 to v4.18.3 (2 weeks ago), both "my cards and the "due cards" sections stop showing anything. Since then, there has been a few updates (current version v4.19.0. 

I have tried rebooting the server and restarting the app from cloudron. (the situation still continues)

### Server Setup Information
Proxmox 6.4-13
VM with 8GB ram, 4 core , 50G drive

Would like to know what i can do to get the information showing again.

Thank you so much for help
Best regards.

**Comment by xet7** [comment]
@nebulade @mfilser 

Do you know about this?

**Comment by nebulade** [comment]
Ah actually I didn't know of those views, but I can confirm this is not working as expecting in our instance on Cloudron either. The error in the webinspector is:
```
Exception in template helper: isNotOAuth2AuthenticationMethod@https://roadmap.cloudron.io/3e799963e44d5c2513be2ef9c75ef600186507d5.js
```
I am investigating what is happening here.

**Comment by mfilser** [comment]
@xet7
in the error message of @nebulade is something about OAuth. Was there a change too in the last weeks?

Due and My Cards are working in my docker installation, i dont have / used Cloudron.

**Comment by mfilser** [comment]
@lealanana
Current Wekan Version is 6.12, not 4.18.3. 4.18 was a very long long time ago (2020-07-10)
Can you give here more hints?

**Comment by lealanana** [comment]
> @lealanana Current Wekan Version is 6.12, not 4.18.3. 4.18 was a very long long time ago (2020-07-10) Can you give here more hints?

so sorry for the confusion , actually 4.18 is the update number that cloudron is showing me. The actual wekan version is Wekan 6.11.

**Comment by mfilser** [comment]
@lealanana
Thank you for clarifying.

I wonder why Cloudron have their own Wekan version number. Maybe they are changing Wekan too...

**Comment by nebulade** [comment]
On Cloudron there is an app package version and an upstreamVersion. For Wekan we currently have Wekan 6.11 packaged.
Version 6.12 is pending an upstream release, which includes https://github.com/wekan/wekan/pull/4408

**Comment by mfilser** [comment]
I tested the latest commit 0fb00bb1
Due cards and My cards are running very smoothly.

**Comment by nebulade** [comment]
Could this be related to Cloudron using the LDAP login provider?

**Comment by xet7** [comment]
In near future I'll try to figure out how to fix Snap, so that I could release newest WeKan for all platforms.

**Comment by lealanana** [comment]
Thank you once again for all the help. I will wait for updates. Really appreciate and great job with wekan and cloudron. Love both a lot.

**Comment by WassimDhib** [comment]
Hi

I have the same probel ("my cards" not showing)

I see this error in my server logs 


```
Exception from sub myCards id yoSsjtqm3fLdqQYHX Error: Publish function returned an array of non-Cursors
    at Subscription._publishHandlerResult (packages/ddp-server/livedata_server.js:1101:20)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1063:10)
    at Subscription.MeteorX.Subscription._runHandler (packages/lamhieu_unblock.js:68:22)
    at Session.MeteorX.Session._startSubscription (packages/lamhieu_unblock.js:56:7)
    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
    at Session.MeteorX.Session.protocol_handlers.sub (packages/lamhieu_unblock.js:27:15)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by nebulade** [comment]
We have updated the Cloudron app package now to the latest version and as far as I can tell the issue is fixed. The My cards at least are loading now. Thanks everyone!

**Comment by mfilser** [comment]
@nebulade
Great, thank you for the feedback

**Comment by lealanana** [comment]
@nebulade
Thank you so much! All working perfect.
