### ISSUE TITLE
Upgrading from 5.90 to 6.11(6.12) Wekan (arm64): The version in Admin panel still shows 5.90.

### ISSUE THREAD

**Issue by kvacha13** [wekan/wekan#4437]
### Server Setup Information
Server Setup Information:

Linux; 20.04.1-Ubuntu aarch64 GNU/Linux
Node v12.16.1
Mongodb version v5.0.3
Apache2
Web Browser Chrome

### Problem description
Upgrading from 5.90 to 6.11(6.12) Wekan ([arm64](https://releases.wekan.team/raspi3/)). Following the upgrade instruction (https://github.com/wekan/wekan/wiki/Raspberry-Pi).  Everything goes well and works but the version in the Admin panel still shows v5.90.
#### Reproduction Steps
Upgrade from 5.90 to 6.11(or 6.12) Wekan ([arm64) from https://releases.wekan.team/raspi3/wekan-6.11-arm64.zip

**Comment by xet7** [comment]
@kvacha13 

At https://wekan.github.io is listed compatible versions of Node.js, MongoDB etc. I don't even know does WeKan work with MongoDB 5.0.3, I have not tested it. Node.js version is 14.x.

For running WeKan, you should have all environment variables from newest start-wekan.sh at https://github.com/wekan/wekan , like `WRITABLE_PATH` etc.

If Admin Panel still shows 5.90, you are still running old version, I don't know did you download newest bundle from arm64 https://releases.wekan.team/raspi3/  , replace that bundle directory at your server, and check that start-wekan.sh or your service has those newest environment variables, and starts correctly `node main.js` in that bundle directory?

For aarch64, MongoDB 4.x is available for example as Snap package, or alternatively from www.mongodb.com website.

**Comment by kvacha13** [comment]
I've been using Wekan on that environment from Wekan v5.30. and upgraded gradually till the 5.90 version following the same
upgrade instruction (downloading a new bundle from arm64 and replacing the old one, while removing the old one) and I
never had a problem like that. There were some problems (like the issue: https://github.com/wekan/wekan/issues/ 4199) that
were solved with your help. So. now this seems really strange, why upgraded version still shows the old version. And my bad, i
am useing a mongodb v4.4.J.2. not v5.0.3.
Admin panel view (upgraded to v6.11) :
WeKan ® Version	5.90.0
Meteor version	2.2
Node version	12.16.1
MongoDB version	4.4.10
MongoDB storage engine	wiredTiger
MongoDB Oplog enabled	
OS Type	Linux
OS Platform	linux
OS Arch	arm64
OS Release	5.8.0-63-generic

**Comment by kvacha13** [comment]
Please close the ticket...it was a false alarm. My bad. Had two Wekan folders in different locations on the server and was changing the one on the wrong location.

**Comment by kvacha13** [comment]
Still problems with the upgrade. Version 5.90 works but version 6.11/6.12 not. All services (Apache, mongodb, wekan) start without any errors/warnings but the Wekan page is broken (This site can’t be reached). Run Mongodb v4.4.10 on node 14.9.0 (listed as the required version) and also on node 14.9.1.  Please, can you help me identify the problem?

Ubuntu 20.04.1- aarch64 GNU/Linux
Node v14.9.0
Mongodb version v4.4.10

**Comment by kvacha13** [comment]
Hi Lauri,

Can you help me with the issue? Just, to recall the all actions i've done: All main services (wekan, mongodb, apache) are active and status shows no problems. It seems that despite wekan is active it does not brings node port 3001 up (port is not listed under lsof -i -P -n | grep LISTEN). Tried rebuild-wekan.sh (which actually is deprecated as it install node v8) also start-wekan.sh, no success, There should be problem with node like i had one in the past and you helped me to fix it (ticket #4199). Please can you foncirm that Wekan6.12 is working on aarch64? Appreciate your help.

**Comment by kvacha13** [comment]
Finally have identified the problem. Despite that the downloaded Wekan (and Wekan v5.90) folder has 'rwxr-xr-x', it fails to run until changing permissions to 'rwxrwxrwx' (at least the permissions need to be changed for the folder '/opt/wekan/programs/server/assets/app,  which is strange.  So, the node (14.19.0) is ok and the wekan version 6.11 is working on aarch64.
