### ISSUE TITLE
Snap migration error

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4439]
@mfilser 

wekan-gantt-gpl snap is v6.09 is installed this way:
```
sudo snap install wekan-gantt-gpl
```
When I try to switch it to edge v6.13 with:
```
sudo snap refresh wekan-gantt-gpl --edge --amend
```
Then at boards, images disappear. Removing some recent ostrio migrations, stopping and starting to run again, has no effect.

When I restore v6.09, images appear back:
```
sudo snap refresh wekan-gantt-gpl --stable --amend
```
I get this error:
```
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]: Exception in callback of async function: TypeError: Cannot read property 'startsWith' of undefined
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at server/migrations.js:1259:42
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at server/migrations.js:1253:26
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at packages/ostrio:files/server.js:1500:25
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at packages/mongo/collection.js:733:7
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at args.<computed> (packages/matb33_collection-hooks.js:431:23)
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at runWithEnvironment (packages/meteor.js:1286:24)
2022-04-01T23:37:43+03:00 wekan-gantt-gpl_wekanteam.wekan[27488]:     at packages/meteor.js:1299:14
```

**Comment by mfilser** [comment]
@xet7

https://github.com/wekan/wekan/blob/5fc5500845a04a47a7f3eb783d95699228797568/server/migrations.js#L1259

avatarUrl seems to be undefined. Can you check this?

**Comment by mfilser** [comment]
or old_url is undefined...

**Comment by xet7** [comment]
Hi,
I think it's not good idea to prevent WeKan from starting, so that PR
should be cancelled. Better way would be to fix it so that everything works
anyway without WRITABLE_PATH. I also try to figure it out, what change
causes images to not show at all.

- Lauri

la 2.4.2022 klo 1.17 Martin Filser ***@***.***> kirjoitti:

**Comment by xet7** [comment]
At docker-compose I get this error:
```
wekan-app  | create storagePath because it doesn't exist: /data/uploads/attachments
wekan-app  | /build/programs/server/node_modules/fibers/future.js:280
wekan-app  | 						throw(ex);
wekan-app  | 						^
wekan-app  | 
wekan-app  | Error: EACCES: permission denied, mkdir '/data/uploads/attachments'
wekan-app  |     at Object.mkdirSync (fs.js:1013:3)
wekan-app  |     at models/attachments.js:90:10
wekan-app  |     at Function.time (/build/programs/server/profile.js:273:30)
wekan-app  |     at /build/programs/server/boot.js:415:15
wekan-app  |     at /build/programs/server/boot.js:465:7
wekan-app  |     at Function.run (/build/programs/server/profile.js:280:14)
wekan-app  |     at /build/programs/server/boot.js:463:13 {
wekan-app  |   errno: -13,
wekan-app  |   syscall: 'mkdir',
wekan-app  |   code: 'EACCES',
wekan-app  |   path: '/data/uploads/attachments'
wekan-app  | }
```

**Comment by mfilser** [comment]
I made the PR not because of this issue.

I am currently working on a new feature, self called "Attachment Multi Storage", and if i see it right Meteor Files will always first write to hard disk, and after this you can move the file to GridFS or any other place like S3 Bucket, Google Drive and so on. So Wekan needs a directory to write to.
Currently some other settings are needed to run Wekan, now one setting more is required, which also makes other features possible.

**Comment by mfilser** [comment]
Wekan must have the rights to write files and create subdirectories.

**Comment by xet7** [comment]
@mfilser 

Thanks! I merged your PR. I'll continue trying to figure this out.

**Comment by mfilser** [comment]
@xet7
Great, thank you.

**Comment by xet7** [comment]
For docker-compose.yml and also torodb, I figured out how to allow WRITABLE_PATH to write to /data. But I have not yet tried does migrating from WeKan 6.09 to 6.14 still keep images visible. Images are visible in 6.09.

rebuild-wekan.sh / start-wekan.sh / start-wekan.bat has some changes to that there is WRITABLE_PATH. But start-wekan.bat etc https://github.com/wekan/wekan/wiki/Offline is not yet tested.

Changes to Snap did not yet make images visible in 6.14. I'll try later to figure it out.

**Comment by xet7** [comment]
# Someone asked:

Question : when migrating from wekan v5.17 to v6.11, is there a specific action/migration to do for the attachments ?

a user reported he lost his attachments and also information about assigned cards

# From xet7:

You should have WRITABLE_PATH set, for example in docker-compose.yml at https://github.com/wekan/wekan

Attachments can also be saved by using nosqlbooster GUI https://github.com/wekan/wekan/wiki/Backup

Updating is like at Backup page, mongodump and mongorestore

WeKan has automatic migrations that usually upgrade any old database structure to newest structure

If WRITABLE_PATH is not added yet, it is possible to add it later, and use nosqlbooster to delete row of already run meteor-files migration from database, so it will run next time WeKan is started

Having info about assigned cards lost is maybe some new bug. I will test migrations does that happen.

I will also test about disappearing attachments, currently that still happens on Snap version of WeKan, but Docker and Sandstorm WeKan works I think

For any found migration etc bugs that are found, we usually add fixes to newest WeKan so that those are fixed when upgrading to newest WeKan

**Comment by xet7** [comment]
I tried this with newest Edge WeKan Snap, using GUI tools nosqlbooster and dbgate at https://github.com/wekan/wekan .

At nosqlbooster, it's possible to right click WeKan database and click `In-progress Operations on This Database`.

At dbgate, I opened wekan database, and from meteor-migrations collection, removed all collectionFS migration entries.

Then I stopped WeKan Snap, and started it again.

Migrations wrote all attachments files to common directory. At WeKan Snap, it's /var/snap/wekan/common/files . At WeKan Gantt GPL Snap, it's /var/snap/wekan-gantt-gpl/common/files. At demo server, it dumped all 1.2 GB total size of 5117 files to that directory. I don't know is it necessary to save all to disk and keep all there? Would it be better to only save one file during migration?

After waiting a little, images become visible for my logged in user. But images are not visible at public board, so maybe that needs some fix.

@mfilser What do you think?

I'll continue trying to figure this out.

**Comment by mfilser** [comment]
@xet7
This is, i think, the related code:
https://github.com/wekan/wekan/blob/a825b2fe81c84bfd0df1231620ab571a1ad858fc/models/attachments.js#L62-L68

I don't see a problem here, but also, i didn't test it yet. 
I was busy nearly all the day with 'Multi File Storage" feature.

**Comment by xet7** [comment]
@mfilser 

Thanks!

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/4780
