### ISSUE TITLE
[UI/UX] Maximized card header

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#4445]
Hi!
Maximized card header appears better with width 100%, IMHO. To improve UI, I added border to split left and right sides.

![image](https://user-images.githubusercontent.com/24301085/161431977-060e5352-00db-40e2-a3b9-7d4966a1f16a.png)

What do you think, guys?

**Comment by xet7** [comment]
@helioguardabaxo 

Please send PR. Thanks!

**Comment by helioguardabaxo** [comment]
Thanks, @xet7 !
I sent PR #4446 for this change.
