### ISSUE TITLE
I can not deploy it on Heroku

### ISSUE THREAD

**Issue by alerma** [wekan/wekan#445]
I received this error when deploying:

Building Meteor with ROOT_URL: https://<App Name>.herokuapp.com

$ROOT_URL, if specified, must be an URL.

 !     Push rejected, failed to compile Node.js app

Any idea? Thanks.

**Comment by mquandalle** [comment]
See #320

**Comment by mquandalle** [comment]
Does that help?

**Comment by alerma** [comment]
Yes! That help me! Thanks. Awesome work!
