### ISSUE TITLE
wrong attachement link  

### ISSUE THREAD

**Issue by WassimDhib** [wekan/wekan#4453]
Hi

We are using wekan in a large deployment (more than 20 000 users and 27 000 boards created)

Multiple instance of wekan are  running behin a reverse proxy, and all the instances are using the same mong database.

Some of the wekan instances have a basic url : `wekan.mycompany.com`  , we have no problem of attachement link here

We have also some wekan instances that have an url of this type : `wekan.mycompany2/myapp/`  , for those ones, when we add an attachement in a card, the link is malformed and the cover is not showed

`<div class="minicard-cover" style="background-image: url('/cdn/storage/attachments/some_id/original/some_id.bmp?dummyReloadAfterSessionEstablished=some_other_id');"></div>`

The image attachement is not found in server since the link doesn't contain the `/myapp/` folder part.

When we click on the card, the attachment is displayed correctly => 
`<img class="attachment-thumbnail-img" src="https://wekan.mycompany2.com/myapp/cdn/storage/attachments/some_id/original/some_id.bmp">`

I was thinking of creating a nginx proxy mapping rule to rewrite the url dynamically

translate `/cdn/storage/attachments/`  to  `/myapp/cdn/storage/attachments/ `  if the url matches 
```
  map $http_x_forwarded_host $conditional_filter1 {
        ~^wekan.mycompany2.com/$ '/myapp/cdn/storage/attachments/' ;
        default '/cdn/storage/attachments/' ;
    }
```

but it won't work since the attachement link in` attachment-thumbnail-img` si different from the link in  `minicard-cover`

**Comment by mfilser** [comment]
What Version are you running?

**Comment by WassimDhib** [comment]
v6.14

**Comment by mfilser** [comment]
How did the migration to Meteor-Files worked for you?
How fast was it?

**Comment by WassimDhib** [comment]
> How did the migration to Meteor-Files worked for you? How fast was it?

we are not using meteorfiles, but w'd like to try it
how can I do this migration?

**Comment by mfilser** [comment]
Wekan uses Meteor-Files since v6.10, so you "already have it".
