### ISSUE TITLE
HTML tags shown in card preview texts

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#4460]
### Server Setup Information

* Did you test in newest Wekan?: 6.15
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?: Yes.
* Operating System: Yes.
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 	14.19.1
* MongoDB Version: 4.4.12
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?: Unrelated to Browsers …

### Problem description
After finally migrating successfully to 6.14 and 6.15, I notice that card text previews show HTML tags:
![Bildschirmfoto 2022-04-06 um 15 13 10](https://user-images.githubusercontent.com/39904614/161984192-6fe0eba5-902f-47a8-86b1-1a7472f7ff6a.png) ![Bildschirmfoto 2022-04-06 um 15 13 42](https://user-images.githubusercontent.com/39904614/161984199-79c61d55-b571-4cdc-a8cc-10398f9716d9.png)
Apparently some card descriptions contain HTML, which wasn't visible before. Switching to code view in Rich Text Editor and removing tags does not make them go away in card preview, also deletion of tags is not persistent.

#### Reproduction Steps
I see this only on cards existing prior to switching from 6.09 to newer versions. New or newer cards do not show this behaviour.

**Comment by Ben0it-T** [comment]
@BabyFnord 
it was mentioned at #4456 and resolved by #4457

**Comment by BabyFnord** [comment]
Thank you very much @Ben0it-T and @xet7 and please forgive my ignorance (I searched but missed #4456 ).

**Comment by xet7** [comment]
@BabyFnord 

No problem. There are 700+ open issues, it's very easy to miss some result. Many bug reports is better than no report at all. If we don't know about some bug, it's not possible to fix it.
