### ISSUE TITLE
Multi File / Attachment Storage

### ISSUE THREAD

**Issue by mfilser** [wekan/wekan#4463]
After moving von CFS to Meteor-Files it's now possible to implement a "multi file storage" at Wekan.
In the first step GridFS and Filesystem are implemented, later any other Storage System like Amazon S3 Bucket, Google Drive and so on are easy to implement.

**I am working on this**, see this preview:

![wekan-multi_file_storage](https://user-images.githubusercontent.com/13166201/162073707-71c1305d-e765-44e3-8269-6ed6a5f97849.gif)

There are some debug informations in this gif, they are removed in the final version.

**Comment by Ben0it-T** [comment]
Thank you for this work
it will be great

**Comment by BabyFnord** [comment]
Cool 👍🏻

**Comment by mfilser** [comment]
In Admin panel there is a new page:
![grafik](https://user-images.githubusercontent.com/13166201/164312128-82e8e58d-bbdd-4a71-87dc-c03083973d97.png)

**Comment by mfilser** [comment]
Attachment renaming is coming soon, initial idea of #2099
