### ISSUE TITLE
'Bug': Card Description on dark theme is too dark

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4465]
I know I already read this in some other ticket but I sadly can't find it.
In dark theme, the description of cards is too dark and therefore not readable.

<img width="479" alt="darkdescriptionisdark" src="https://user-images.githubusercontent.com/92315677/162158300-cbd722b7-c4ff-48c9-a961-efce6e794c64.png">

A lighter textcolor for more contrast would be great! I really like this theme.

**Comment by TheExo** [comment]
i deployed a css style fix so it looks like that now.

![](https://i.imgur.com/JqcQ6Ws.png)

**Comment by Meeques** [comment]
Thank you! @TheExo
