### ISSUE TITLE
Bug: cannot add new attachments to cards

### ISSUE THREAD

**Issue by AuspeXeu** [wekan/wekan#4467]
I am on version 6.17 - somehow this also broke our custom logo.
![image](https://user-images.githubusercontent.com/2115696/162259465-9730e170-aca3-454f-9c3b-1368ba9903e1.png)

**Comment by xet7** [comment]
@AuspeXeu 

What platform? Docker/Snap/Sandstorm/Bundle/UCS ?

**Comment by AuspeXeu** [comment]
Docker

**Comment by xet7** [comment]
Moved to #4468
