### ISSUE TITLE
Board View: Table

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#4469]
Hi, @xet7 
I am trying to create a table view in a board using tabular meteor package (https://atmospherejs.com/aldeed/tabular)

In example documentation, it say:
"Define your table in common code (code that runs in both NodeJS and browser)"
I created a .js file in root directory (outside server and client folders) and it run.
![Screenshot 2022-04-06 at 07-31-24 Screenshot](https://user-images.githubusercontent.com/24301085/162279738-43174cbd-e989-4f6d-a41b-e5e5b2a7abf8.png)

Where I should create put this code in Wekan's repository?

Thanks!

**Comment by xet7** [comment]
@helioguardabaxo 

# Table view

With table view, maybe you mean similar like Admin Panel / People ?
https://github.com/wekan/wekan/tree/master/client/components/settings

If you are creating another view like Swimlanes/Calendar etc, you can find related code with:
```
cd wekan
./find.sh view-swimlanes | grep -v i18n | grep -v api | less
```
Some views like My Cards are here:
https://github.com/wekan/wekan/tree/master/client/components/main

# All Boards

Future of `All Boards` page is to be similar like iOS/Android, where icons can be grouped:
https://github.com/wekan/wekan/issues/4178#issuecomment-980229676

For that, there is already drag-drop of arranging of boards icons. Missing is detecting when board icon is above another board icon and dropped, so then mini-board-icon would be added to board icon, to shot nested structure.

![Univention_Management_Console](https://user-images.githubusercontent.com/15545/143617375-647a64cd-842a-42ad-a0fc-b8a4937bb37d.png)

**Comment by helioguardabaxo** [comment]
I would like to create another view like Swimlanes/Calendar and a Big Table to MyCards (with filters, search and ordination).

**Comment by helioguardabaxo** [comment]
About future of All Boards: 
#3796 is in progress?

**Comment by xet7** [comment]
Yes, #3796 is In Progress, not ready yet.

**Comment by xet7** [comment]
> I would like to create another view like Swimlanes/Calendar and a Big Table to MyCards (with filters, search and ordination).

Yes, you can create view-table similar to view-swimlanes and add those files here:
https://github.com/wekan/wekan/tree/master/client/components/main

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4479
