### ISSUE TITLE
"fibers.node` is missing" error

### ISSUE THREAD

**Issue by Mysterius** [wekan/wekan#447]
Hello,

Running Ubuntu 15.10 & Node 0.10.40, I have this error spamming into the log : 

_Error: `/root/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-4.5/fibers.node` is missing. Try reinstalling `node-fibers`?_

I used the auto-install script to install Wekan.
Any idea ? I tried node build inside the fibers directory but it keeps saying

_linux-x64-v8-3.14` exists; testing
Binary is fine; exiting_

**Comment by mquandalle** [comment]
Which auto-install script did you use (there isn’t any “official” script yet)?

Just from reading the error, the following should work

```
$ cd /root/bundle/programs/server/
$ npm install
[and restart the application]
```

**Comment by Mysterius** [comment]
Unfortunately, it didn't work. I am not familiar with node.js but it appears it's trying to use a nonexistent recent binary (linux v8-4.5) but when I try to update it says v8-3.14 is the latest. Hm...

**Comment by mquandalle** [comment]
What version of `node` and `npm` do you have installed `node --version` and `npm --version`?

**Comment by Mysterius** [comment]
node is 0.10.40.
npm 1.4.28

Oh, and I forgot earlier, i used this script : https://github.com/anselal/wekan/blob/master/autoinstall_wekan.sh

**Comment by mquandalle** [comment]
Any idea @anselal?

**Comment by anselal** [comment]
Try to uninstall fibers.node first.

```sh
$ npm uninstall fibers
$ npm install fibers
[restart the system]

```

**Comment by Mysterius** [comment]
Building in /root/bundle/programs/server (as expected for Wekan) returns what I said in my original message :
*linux-x64-v8-3.14` exists; testing
Binary is fine; exiting*

Building in /root, just for testing, is different however. In the /root/node_modules/fibers/bin I have more binaries (still the 8-3.14 one that is useless, but also a newer 8-4.6. However, the system seems to be expecting 8-4.5 which doesn't appear anywhere. 

I'm sorry if what I say is stupid. I never touched node.js before installing Wekan :x.

**Comment by anselal** [comment]
No question is stupid. I will try to reproduce your problem by running the script in Ubuntu 15.10 but it will take a week or so since I am on vacation. You can always try my "ready to go" vm appliance.

**Comment by Mysterius** [comment]
Thank you for your answer anselal. Please keep me informed if you find something.
I won't be able to do much for a week since i'm with family for Christmas but i'll still answer here if need be.

In the meantime, Wekan is working. It's only a problem because it's spamming my logfile. I have temporarily disabled logging.

**Comment by bevinhex** [comment]
Got the same problem here, printing
```
programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
/fibers.node` is missing. Try reinstalling `node-fibers`?
```
while I do have ```programs/server/node_modules/fibers/bin/linux-x64-v8-4.5``` folder
got it while trying to deploy meteor app, any idea?

**Comment by tampham47** [comment]
I got the same issue :((

**Comment by leo-combes** [comment]
+1

**Comment by vavrecan** [comment]
I was able to install to install using node 0.10.41 
i installed fibers in programs/server manually - npm install fibers
and then went to the  node_modules/fibers and did node build.js 

missing fibers.node was build without any problem ^^

**Comment by xet7** [comment]
Use newest version, install instructions at repo readme and wiki.

**Comment by sinasalek** [comment]
I'm on Windows 10 and have the same problem.
node: v0.10.48 i also tried it with node 0.10.40
npm: 2.15.1
wekan: [0.11.1-rc1 ](https://github.com/wekan/wekan/releases/download/v0.11.1-rc1/wekan-0.11.1-rc1.tar.gz)

What am i doing wrong? does it need any dependency? how can i find out why it fails? I attached npm log file?
[npm-debug.zip](https://github.com/wekan/wekan/files/811445/npm-debug.zip)

**Comment by xet7** [comment]
@sinasalek 

1) Don't comment on closed issues. If you don't find existing open issue, create new issue.

2) Nobody has had success with compiling from source on Windows. If you get it working, please add your instructions to existing wiki page:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

3) If you want to use Wekan on Windows, you could ty it with Docker.

**Comment by xet7** [comment]
@sinasalek 

@entrptaher today added new Windows instructions, you can try does it work for you:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

**Comment by sinasalek** [comment]
Thanks @xet7 , the new guide is much better, i'm following it now to see if it works. I also created a new issue to share the result #883

**Comment by abdulquadir202** [comment]
i am getting the same problem .

**Comment by xet7** [comment]
@abdulquadir202 

This issue is closed, please continue discussion at #883

**Comment by gringolalia** [comment]
I downgraded node with `nvm use 12` and then ran `npm run serve` and it was good ....

**Comment by prakash-synamedia** [comment]
Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit [dacc2fee0f](https://github.com/v8/v8/commit/dacc2fee0f815823782a7e432c79c2a7767a4765) is a breaking change and workarounds are non-trivial.

https://www.npmjs.com/package/fibers

**Comment by xet7** [comment]
@prakash-synamedia 

Yes. Options that I'm looking at currently are:

a) Upcoming Meteor 3.0 will be without fibers and targeting Node.js 18, try to upgrade to it if possible:
- https://github.com/meteor/meteor/pulls?q=is%3Apr+is%3Aopen+fibers
- https://github.com/meteor/meteor/discussions?discussions_q=fibers

b) Migrate to Upcoming WeKan Multiverse https://github.com/wekan/wekan/issues/4578
