### ISSUE TITLE
Raspi4 upgrade 6.18 error for fiber and start_wekan.sh

### ISSUE THREAD

**Issue by ncs19960831** [wekan/wekan#4470]
I used the [website's](https://releases.wekan.team/raspi3/) wekan-latest-arm64.zip to update. while the following error occurred:

> 
> ubuntu@ubuntu:~/Software/wekan$ ./start-wekan.sh
> ## There is an issue with `node-fibers` ##
> `XX/wekan/bundle/programs/server/node_modules/fibers/bin/linux-arm64-72-glibc/fibers.node` is missing.
> 
> Try running this to fix the issue: /usr/local/bin/node XX/wekan/bundle/programs/server/node_modules/fibers/build
> Error: Cannot find module 'XX/wekan/bundle/programs/server/node_modules/fibers/bin/linux-arm64-72-glibc/fibers'
> Require stack:
> - XX/Software/wekan/bundle/programs/server/node_modules/fibers/fibers.js
> - XX/Software/wekan/bundle/programs/server/boot.js
> - XX/wekan/bundle/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
>     at Module.require (internal/modules/cjs/loader.js:1042:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.<anonymous> (XX/wekan/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
>     at Module._compile (internal/modules/cjs/loader.js:1156:30)
>     at Module.Mp._compile (XX/wekan/bundle/programs/server/runtime.js:50:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Module.Mp.load (XX/wekan/bundle/programs/server/runtime.js:15:31)
> /home/ubuntu/Software/wekan/bundle/programs/server/node_modules/fibers/fibers.js:23
>                 throw new Error('Missing binary. See message above.');
>                 ^
> 
> Error: Missing binary. See message above.
>     at Object.<anonymous> (XX/wekan/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
>     at Module._compile (internal/modules/cjs/loader.js:1156:30)
>     at Module.Mp._compile (XX/wekan/bundle/programs/server/runtime.js:50:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Module.Mp.load (XX/wekan/bundle/programs/server/runtime.js:15:31)
>     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
>     at Module.require (internal/modules/cjs/loader.js:1042:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.<anonymous> (XX/wekan/bundle/programs/server/boot.js:2:15)
> ubuntu@ubuntu:~/XX/wekan$ cd XX/wekan/bundle/programs/server/node_modules/fibers/bin/
> ubuntu@ubuntu:~/XX/wekan/bundle/programs/server/node_modules/fibers/bin$ ls
> darwin-x64-64  linux-arm64-83-glibc  linux-x64-64-musl   linux-x64-72-musl  win32-ia32-64  win32-x64-64
> darwin-x64-72  linux-ia32-64-glibc   linux-x64-64-glibc   linux-x64-72-glibc  repl               win32-ia32-72  win32-x64-72
> 

Then I try to install

> ~/wekan/bundle/programs/server$ npm install fibers
> 
> > fibers@4.0.3 install wekan/bundle/programs/server/node_modules/fibers
> > node build.js || nodejs build.js
> 
> make: Entering directory 'wekan/bundle/programs/server/node_modules/fibers/build'
>   CXX(target) Release/obj.target/fibers/src/fibers.o
> ../src/fibers.cc: In function ‘void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&))’:
> ../src/fibers.cc:355:87: warning: cast between incompatible function types from ‘uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’} to ‘v8::AccessorNameGetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’} [-Wcast-function-type]
>   355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
>       |                                                                                       ^~~~~~
> ../src/fibers.cc:355:123: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} to ‘v8::AccessorNameSetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} [-Wcast-function-type]
>   355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
>       |                                                                                                                           ^~~~~~
> In file included from ../src/coroutine.h:1,
>                  from ../src/fibers.cc:1:
> ../src/fibers.cc: At global scope:
> ~/.cache/node-gyp/12.16.2/include/node/node.h:608:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
>   608 |       (node::addon_register_func) (regfunc),                          \
>       |                                           ^
> ~/.cache/node-gyp/12.16.2/include/node/node.h:642:3: note: in expansion of macro ‘NODE_MODULE_X’
>   642 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
>       |   ^~~~~~~~~~~~~
> ../src/fibers.cc:930:1: note: in expansion of macro ‘NODE_MODULE’
>   930 | NODE_MODULE(fibers, init)
>       | ^~~~~~~~~~~
>   CXX(target) Release/obj.target/fibers/src/coroutine.o
>   CC(target) Release/obj.target/fibers/src/libcoro/coro.o
>   SOLINK_MODULE(target) Release/obj.target/fibers.node
>   COPY Release/fibers.node
> make: Leaving directory '~/Software/wekan/bundle/programs/server/node_modules/fibers/build'
> Installed in `~/Software/wekan/bundle/programs/server/node_modules/fibers/bin/linux-arm64-72-glibc/fibers.node`
> + fibers@4.0.3
> updated 1 package and audited 148 packages in 33.079s

No more errors, but missing WRITABLE_PATH symbol.

> Note: you are using a pure-JavaScript implementation of bcrypt.
> While this implementation will work correctly, it is known to be
> approximately three times slower than the native implementation.
> In order to use the native implementation instead, run
> 
>   meteor npm install --save bcrypt
> 
> in the root directory of your application. You may also need to
> install build tools to compile bcrypt. For more information see:
> https://github.com/nodejs/node-gyp#installation
> Presence started serverId=AktzkJaQh93MkDDgg
> 
> 
> 
> WRITABLE_PATH environment variable missing and/or unset, please configure !
> 
> 
> Stopping Wekan
> Wekan isn't runnable. Please resolve the error's above and restart Wekan !

I looked at the [start-wekan.sh](https://releases.wekan.team/raspi3/start-wekan.sh), and there is no such configuration, but it exists in the git repository. [start-wekan.sh](https://github.com/wekan/wekan/blob/14aeef8d96c309a7aed74c3407367b48f098b68b/start-wekan.sh).

I used this and it worked successfully.
Is there a problem with file generation inside the [site](https://releases.wekan.team/raspi3/)? I don't know why there is a problem.

**Comment by xet7** [comment]
@ncs19960831 

Are you using Node.js 14.19.1 and MongoDB 3.2.x-4.x like mentioned at Download section of https://wekan.github.io ?

Fibers can be built this way:
https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-a.sh#L19-L22

**Comment by ncs19960831** [comment]
@xet7 I was running 6.11 before, so I don't think there should be dependency issues.

**Comment by ncs19960831** [comment]
@xet7 I found it, my node version 12.16 is too low, thank you for your help
