### ISSUE TITLE
[UI/UX Bug] moderndark/exodark card description previews: Insufficient text contrast to background.

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#4472]
### Server Setup Information

* Did you test in newest Wekan?: 6.18
* Did you configure root-url correctly so Wekan cards open correctly?: Yes.
* Operating System: Linux 3.10.0-1160.24.1.el7.x86_64
* Deployment Method: bundle
* Http frontend if any: Nginx
* Node.js Version: 14.19.1
* MongoDB Version: 4.4.13
* What webbrowser version are you using?: ungoogled-chromium 100.0.4896.75, Safari 14.1.2

### Problem description
Card description previews lack sufficient text contrast to background on `moderndark` and `exodark` themes:
![Bildschirmfoto 2022-04-09 um 12 44 55](https://user-images.githubusercontent.com/39904614/162569010-09a0d08d-20a0-4187-ac35-f46a799a17b5.png) ![Bildschirmfoto 2022-04-09 um 12 45 23](https://user-images.githubusercontent.com/39904614/162569011-058e2639-bc0e-4841-94ec-332054a557d2.png)

I've read elsewhere that this presumably had been fixed, but can't see this implemented in 6.18. Tho I really like both themes, it's not a deal breaker, just FYI.

**Comment by gerald41** [comment]
For the exodark theme, the same problem with checklist
<img width="575" alt="Capture d’écran 2022-04-15 à 01 44 07" src="https://user-images.githubusercontent.com/11268587/163494233-0dcd0036-18b7-4efd-88bc-869df9c3b90b.png">

**Comment by BabyFnord** [comment]
Maybe @TheExo can have a look at this artefact? Thank you 🙂

**Comment by TheExo** [comment]
will do it for the exodark theme, i have some more adjustments to make to the theme.

**Comment by TheExo** [comment]
actually i think i can fix that for the other theme aswell :)

**Comment by TheExo** [comment]
@gerald41 could you tell me which browser and OS you are using?

**Comment by TheExo** [comment]
i submitted a fix which should take care of everything in here, also the comments/activity bubbles within the card details. for future stuff just tag me, i dont look through all the issues in here :)

**Comment by gerald41** [comment]
Thanks @TheExo , certainly too late but my os is osx big sur, browsers safari and chrome have the same result,
 on mobile the same with ios , on safari and chrome

good job with your theme

**Comment by TheExo** [comment]
i tested it on various browsers, even some like opera and brave. sometimes ppl have odd browsers hence im asking.

im pleased that u like the theme :)

**Comment by BabyFnord** [comment]
Hello @xet7 and @TheExo, there still is this issue:
When one highlights a text with a background colour (here, yellow … like a real text marker), the text colour itself will be white (according to the ExoDark theme). This is fine as long as you're in edit mode but, thereafter, white text on yellow background isn't readable. 
![Exodark and yellow highlight](https://user-images.githubusercontent.com/39904614/208148461-ae8ec33b-1915-4c48-aa19-44c19987c59c.gif)

It seems some kind of text colour switching needs to be implemented, providing good contrast according to any background colour _and_ theme. Do you think this can be fixed?

**Comment by xet7** [comment]
@BabyFnord 

> It seems some kind of text colour switching needs to be implemented, providing good contrast according to any background colour and theme.

I don't know is there some general way. It depends what color each theme uses.

> Do you think this can be fixed?

I presume yes, because I also figured out how to fix previous color stuff. Maybe I'll look at it sometime, or if @TheExo has time.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/commit/ab944e51c728412d455d88b5714e84393eccb210 . Thanks to xet7 !

**Comment by xet7** [comment]
Related fix, this also to moderndark theme https://github.com/wekan/wekan/commit/05c6e101ff32efb42365ac2ffbd802497d5199ac
