### ISSUE TITLE
Board Settings / All Boards Settings for showing count of list and memberlist has some bug

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4478]
@helioguardabaxo

After checking show memberlist, and closing popup, it is still unchecked, while memberlist still visible. Do you have idea how to fix it?

Are these settings per-board settings? Not per-user?

**Comment by xet7** [comment]
These settings https://github.com/wekan/wekan/pull/4477

**Comment by helioguardabaxo** [comment]
@xet7 
I used allow "Received" field in CardSettings as example to create this feature....

Maybe the bug is here:
https://github.com/helioguardabaxo/wekan/blob/ab077e7eb9612707a0fd6bab60e966ced36e3d43/server/migrations.js#L92

Do you try in a existing board or a new?

**Comment by xet7** [comment]
@helioguardabaxo 

On nyew board.

I don't know why it would be necessary to have migrations for new fields. Adding to wekan/models/boards.js should be enough. When someone has thousands of boards, updating everyone takes a lot of time, and makes me feel like just doing a rewrite.

**Comment by helioguardabaxo** [comment]
Sorry, I don't thought this before.

The problem is just in check, I guess. Because the members avatar is showing on My Boards.
Right?

**Comment by xet7** [comment]
@helioguardabaxo 

Please build WeKan with newest changes from git repo https://github.com/wekan/wekan . When you check or uncheck those options, do they keep being checked or unchecked when looking at those option menus again? And do those settings match settings at All Boards page visibility of memberlists etc?

**Comment by helioguardabaxo** [comment]
@xet7 
I found the bug:
"allowsBoardMemberList" instead of "allowsBoardMember"

In:
https://github.com/helioguardabaxo/wekan/blob/ab077e7eb9612707a0fd6bab60e966ced36e3d43/client/components/sidebar/sidebar.jade#L151

and

https://github.com/helioguardabaxo/wekan/blob/ab077e7eb9612707a0fd6bab60e966ced36e3d43/client/components/sidebar/sidebar.jade#L152

Could you try?
In my environment works fine. I remove migrations too.

**Comment by helioguardabaxo** [comment]
I will build the newest version here

**Comment by xet7** [comment]
@helioguardabaxo 

Thanks! I'm building with those changes.

**Comment by helioguardabaxo** [comment]
@xet7 
Thanks for your help!

**Comment by xet7** [comment]
@helioguardabaxo 

Thanks for your feature and bugfix!
