### ISSUE TITLE
GLPI and WEKAN

### ISSUE THREAD

**Issue by Mateussj15** [wekan/wekan#4481]
**What's the best way to integrate GLPI with Wekan?

Is there any documentation that simplifies these steps?**

**Comment by xet7** [comment]
Moved to here from #4313

From @AlexandrovRR

Is it possible to integrate glpi into wekan?

From @xet7 

Depends if someone sends integration as pull request.

**Comment by xet7** [comment]
@Mateussj15 

Yes, there is docs.

Here is how to build WeKan and submit pull request: https://github.com/wekan/wekan/wiki/Emoji

Use Node.js etc versions mentioned at https://wekan.github.io Download section.

Here is WeKan source code: https://github.com/wekan/wekan

**Comment by Mateussj15** [comment]
Thanks!!

**Comment by xet7** [comment]
@Mateussj15 

You can also search ChangeLog for any existing WeKan features, it has links to code where those features have been implemented. You can use similar code to add similar integration.

https://github.com/wekan/wekan/blob/master/CHANGELOG.md

**Comment by xet7** [comment]
@Mateussj15 

Also look at wiki, is there similar integrations already at right menu:
https://github.com/wekan/wekan/wiki
