### ISSUE TITLE
Sending emails using Exchange

### ISSUE THREAD

**Issue by abujbr** [wekan/wekan#4483]
Hello everyone,

I have some problems regarding sending emails using exchange, I have gone through all the troubleshooting methods without any luck till I found some info that states that exchange is currently not supported!

My current issue I have now is the "self signed certificate error"

Is there any solution for this? or can I just modify the source code of sending emails functionality and test? and if so, how can I do it in Snap?
I am currently using Wekan Snap.

Thank you very much

**Comment by xet7** [comment]
@abujbr 

What version of Exchange?

Does Exchange have STMP receiving enabled?

Did you try DavMail ?
- http://davmail.sourceforge.net
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#email-servers-smtp-or-exchange

Did you try self-signed options?
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#self-signed-certificate

Did you try SSLv3 options?
- https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses

**Comment by abujbr** [comment]
Thank you very much

the problem has been solved.

I just used this url without user or pass
snap set wekan mail-url='smtp://mail.example.com:25/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false'

every thing is okay now

Thank you
