### ISSUE TITLE
Maximum avatar size is wrong

### ISSUE THREAD

**Issue by Destiphy** [wekan/wekan#4489]
There is a mismatch between the shown maximum avatar size to the user and the implemented maximum file size.

UI:
https://github.com/wekan/wekan/blob/65434876ebba5fb3d319b928bec54b079dcf6934/i18n/en-GB.i18n.json#L135

Code:
https://github.com/wekan/wekan/blob/65434876ebba5fb3d319b928bec54b079dcf6934/models/avatars.js#L26

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4648
