### ISSUE TITLE
jQuery Drag and Drop on touch devices

### ISSUE THREAD

**Issue by araczkowski** [wekan/wekan#449]
jQuery Drag and Drop doesn't work for touch screens

for me this solves the problem
https://github.com/furf/jquery-ui-touch-punch

maybe this code can be added to the project (/client/config) or maybe better to the package https://github.com/mquandalle/meteor-jquery-ui-drag-drop-sort

after this, the app can more useful on touch screens

![touch](https://cloud.githubusercontent.com/assets/1263968/11930004/0f3b2a80-a7e0-11e5-980b-da138fd85492.png)

**Comment by mquandalle** [comment]
That’s a good idea, I will do that.
