### ISSUE TITLE
Images attached to card does not show correctly

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan#4507]
### Server Setup Information
* Did you test in newest Wekan? Yes
* Did you configure root-url correctly so Wekan cards open correctly? Yes
* Operating System: Ubuntu 18.04.6 LTS
* Deployment Method: Docker
* Http frontend: Apache
* Node.js Version: 14.19.2
* MongoDB Version: 4.2.19
* What webbrowser version are you using? Firefox 100.0 (64 bits)

### Problem description
The problem appeared after an update from 5.95.0 to 6.22.0
Images attached to card does not show correctly.

#### Reproduction Steps
1. Add an image as a card attachment
2. Refresh the board (or logout/login)
3. Display the board/card

#### Logs
Error in browser console :  
![wekan-attachment-error](https://user-images.githubusercontent.com/8069239/167871718-d138a741-8470-4d1e-ac84-bd05dad6c144.png)

**Comment by mfilser** [comment]
Upcoming Meteor 2.7.1 (#4485) has many improvements, and based on this version also new attachment features). i suggest to wait for this upcoming versions and then try again.

**Comment by GuiGuiSoft** [comment]
Hello,

I updated Wekan to 2.66 but the problem remain :/

![image](https://user-images.githubusercontent.com/8069239/170242941-887df229-0daa-4024-8606-fa4bad0196c7.png)

**Comment by GuiGuiSoft** [comment]
Hello,

I updated to 2.68 and the problem remain.
Is it possible to reopen the issue or should I create a new one ?

Regards.

**Comment by ilovefreesw** [comment]
I think it works correctly...just have to configure mini card settings.

![image](https://github.com/wekan/wekan/assets/77317006/44c6c749-1e59-4bc3-8bf8-7911f5023be8)
