### ISSUE TITLE
Helm-chart repo duplicate

### ISSUE THREAD

**Issue by luclu** [wekan/wekan#4509]
I noticed that the Helm-chart of wekan is available at two different repos at different states:
- https://github.com/wekan/wekan/tree/master/helm/wekan
- https://github.com/wekan/charts/tree/main/wekan

As the main-repo one is currently active I suspect it was merged but the deprecated one not marked as such.
Thus I recommend to:
- enable the archive state of the old one and
- replicate any PRs to the new one (if legally possible) or notify the PRs authors to do so themselves.

Thank you!

**Comment by xet7** [comment]
@luclu 

PRs and instructions welcome about how to do that. I have not used helm.

**Comment by xet7** [comment]
Moved https://github.com/wekan/wekan/blob/master/helm.md
