### ISSUE TITLE
Disconnected indicator

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#451]
When the client is disconnected from the server we need to indicate it in the UI and include a counter to the next try and a button to retry immediately. Currently users lose data because of the absence of this indicator. This is what connected client like Gmail do:

![gmail](https://cloud.githubusercontent.com/assets/1730702/11935076/18f3039c-a806-11e5-8754-7a4f7244bd67.png)

Another possible longer term solution would be to support a full offline mode where unsynced changes are kept on the browser local storage.

**Comment by araczkowski** [comment]
in my opinion the full offline mode will be great :+1: , especially on mobile devices

for the data this can be usefull https://github.com/GroundMeteor/db
and for the app maybe this https://atmospherejs.com/meteor/appcache

of course not everything will be possible (register new user for example) 
but still it will be a super feature

**Comment by mquandalle** [comment]
Yes I would also like to support offline mode, in which case it is still relevant to have a indicator in the UI saying “You are in offline mode”.

I played with GroudDB and I’m confident this is a good solution for us. However appcache [is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache), and the replacing technology is the service worker. I would love to see someone developing an offline package for Meteor using service worker (and I’m not the only one) and if no one is doing it, I may try.

Let’s open a separate thread about offline support and keep this one about the indicator.

**Comment by mquandalle** [comment]
Created #466 for offline mode discussions
