### ISSUE TITLE
Test new WeKan with Meteor 2.7.2

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4512]
@mfilser @helioguardabaxo @imajus @TheExo

## Newest Meteor 2.7.2

- WeKan master branch now uses newest Meteor 2.7.2
- I added remaining packages for login
- Other branches have been deleted. There is copy of code before merging at https://wekan.github.io/wekan-before-merge_2022-05-16.7z
- Newest Meteor uses MongoDB 5.x

## Stylus to CSS

- [Converted Stylus to CSS. Removed Stylus. This change removed many error messages](https://github.com/wekan/wekan/commit/072778b9aaefd7fcaa7519b1ce1cafc1704d646d). Thanks to xet7.
- It was hard to get newest Stylus working with newest Meteor, so I got Stylus converted to CSS.
- Now there are some CSS to fix, like:
  -  bullet option ball visible at some menus and Admin Panel
  - Some Font Awesome icons not displaying at Swimlane Change Color menu
- PRs welcome

## About login

- Please test does everything work, like login, etc

**Comment by xet7** [comment]
Hmm, I think I try make new release, so that it will be possible to test this.

**Comment by mfilser** [comment]
@xet7
I tested Meteor 2.7.1 for many weeks without any issues (for me). Also i had no issues with stylus...

About convert stylus to CSS:
Is there a command you used for converting from Stylus to CSS ?

**Comment by xet7** [comment]
@mfilser 

https://github.com/wekan/wekan/blob/master/releases/stylus-to-css.sh

**Comment by xet7** [comment]
@mfilser 

It is possible that converting to CSS did not convert something, not all Stylus extensions were in use etc. Anyway, it seems to mostly work.

**Comment by xet7** [comment]
docker-compose.yml seems to work.

I have some problems at Sandstorm WeKan https://github.com/sandstorm-io/sandstorm/issues/3618

**Comment by xet7** [comment]
With docker-compose.yml from https://github.com/wekan/wekan it's possible to do:
```
docker-compose up -d
```
That docker-compose.yml has MongoDB 5 etc.

**Comment by helioguardabaxo** [comment]
@xet7 @mfilser 

Hi, guys!
All menus with popover are not working and menu items have a extra padding/margin left.


![Peek 17-05-2022 08-52](https://user-images.githubusercontent.com/24301085/168804835-8a83861f-e81f-4814-ad65-1c8f0dfb851a.gif)

**Comment by helioguardabaxo** [comment]
Wow....stranger things here.
![Peek 17-05-2022 09-03](https://user-images.githubusercontent.com/24301085/168806816-e419b83e-90f9-4303-9dd1-3e630d625d6e.gif)

I didn't nothing and now is working.

**Comment by xet7** [comment]
@helioguardabaxo 

I presume it takes some time for all Javascript to load and run.

**Comment by mfilser** [comment]
@xet7 

I had a look at changing `stylus` to `css`.
For my personal feeling i am not happy with it for several reasons.

**the css files are much compressed and many things repeated again**

before:
https://github.com/wekan/wekan/blob/01a1a2cdce5c131b54c972abc31c61566f88e5aa/client/components/boards/boardColors.styl#L81-L82

after:
https://github.com/wekan/wekan/blob/f4fe33fb05858f729ba4387035e5518d0fbfddb9/client/components/boards/boardColors.css#L1-L72

**helpful comments are removed**

before:
https://github.com/wekan/wekan/blob/01a1a2cdce5c131b54c972abc31c61566f88e5aa/client/components/boards/boardColors.styl#L357-L360

after:
https://github.com/wekan/wekan/blob/f4fe33fb05858f729ba4387035e5518d0fbfddb9/client/components/boards/boardColors.css#L1023-L1025

**it's harder to maintain this css code now**

before:
https://github.com/wekan/wekan/blob/01a1a2cdce5c131b54c972abc31c61566f88e5aa/client/components/boards/boardColors.styl#L1-L1232

after:
https://github.com/wekan/wekan/blob/f4fe33fb05858f729ba4387035e5518d0fbfddb9/client/components/boards/boardColors.css#L1-L2176

Because of the big change it's possible to "get many new style issues".
Also i think further Wekan development is getting harder too.

So if i can make a suggestion i think it's better to make the necessary migrations to the latest stylus version instead of "changing the whole weel".

**Comment by xet7** [comment]
Changing this wheel fixed a lot of bugs. I will fix UI issues.

**Comment by mfilser** [comment]
I see. I think i was missing that issues.
Do you have some example issues? Maybe that issues are now "closeable"..

**Comment by xet7** [comment]
Changing to Stylus also fixed this kind of errors when building WeKan https://github.com/Meteor-Community-Packages/meteor-stylus/issues/9

**Comment by xet7** [comment]
Mainly:
- Maximun call stack size exceeded, at browserside
- Serverside those stylus build errors, about 30 lines of error messages

**Comment by xet7** [comment]
I did previously increase stack size for WeKan, trying if those help with exceeded error messages. But that could also increase RAM requirements.

With Meteor 2.2 version, something in WeKan code caused memory leaks, so RAM and CPU usage was growing both at browserside and serverside. I'm trying to remove extra code, and with that make WeKan run faster, and use less RAM and CPU.

**Comment by xet7** [comment]
Currently there are many themes, where only difference is 1 or 2 colors. That causes duplication of CSS. Sometime those will be combined, and added settings to change to any color.

**Comment by TheExo** [comment]
ill try do look through all the css and touch up on the left out stuff if i find anything critical the next days

**Comment by mfilser** [comment]
Thank you for the links and explaining.
I thought until now that Stylus is compiled to CSS at compiling or compiled at Server during startup and especially not compiled browser side.

**Comment by xet7** [comment]
With newest WeKan, I don't know why changing Swimlane color reloads page. Wekan partially works like SPA (Single Page Application, automatically updating in place), partially like MPA (Multi Page Application application, always loading whole page), and also too much is loaded to browserside at once.

I'm trying to make changes so that for non-JS browsers, WeKan would work like MPA with HTML/CSS only and be visible and accessible (currently WeKan displays nothing on non-JS browsers), and where browser supports Javascript it would run that additional SPA features code like current Meteor WeKan realtime UI.

**Comment by xet7** [comment]
Problem with minimongo and optimistic UI is that there is not yet indicator when change is saved to database  https://github.com/wekan/wekan/issues/3071#issuecomment-622300835 

For example, to customer happened, that he made a lot of changes for 30 minutes, closed webbrowsers, and those changes were lost.

So sometime I'll try add that indicator, and remove minimongo, optimistic UI etc from browserside. With that much less code, it will make webpages to load faster. Some related code is at https://github.com/wekan/we . Anyway, plan is to only change required parts of current WeKan code to make that happen. WeKan has a lot of code that already works well.

**Comment by mfilser** [comment]
Maybe this save issue doesn't exists with Meteor 2.7.2 anymore.
For me i hadn't this issue yet..

**Comment by xet7** [comment]
@mfilser 

Meteor 2.7.2 is much faster than Meteor 2.2, I don't know does that issue happen anymore.

@TheExo 

Currently this is extra change I added, it only makes that ul li same color as background, but anyway that is extra border taking too much space. Similar li elements are also at Admin Panel, but I have not changed them.
- https://github.com/wekan/wekan/blob/master/client/components/boards/boardsList.css#L6
- https://github.com/wekan/wekan/blob/master/client/components/boards/boardsList.jade#L32

**Comment by mfilser** [comment]
@xet7 
About the CSS changes and adding extra padding / margin at many element. It seems stylus did some settings too.
This is what i have in Browser Inspector with stylus and not with CSS:
![grafik](https://user-images.githubusercontent.com/13166201/168915310-55596b4e-9b3e-4392-91ff-21f34b02b702.png)

So there is extra margin / padding at the top of the list and the first minicard.

before:
![grafik](https://user-images.githubusercontent.com/13166201/168915514-f694a0eb-ad8d-42e3-97fe-95d51aa03578.png)


after:
![grafik](https://user-images.githubusercontent.com/13166201/168915448-c9d6f069-aaa8-42f5-96dc-a925bcbc9cf8.png)

**Comment by mfilser** [comment]
Maybe it's related to this:
https://github.com/stylus/nib/blob/master/lib/nib/reset.styl

Did you remove the `import nib` before running `npm stylus` ?

**Comment by xet7** [comment]
@mfilser 

Yes, because newest stylus npm package does not support that `import nib` code, that extension is not in use, it did give some syntax error:
https://github.com/wekan/wekan/blob/master/releases/stylus-to-css.sh#L6

**Comment by xet7** [comment]
@mfilser 

When I installed newest WeKan to my demo server, there was some time also this bug #4214, but after some time it stopped, maybe it's because WeKan had also attachment migrations or some other migration stuff In Progress.

**Comment by xet7** [comment]
@mfilser 

Thanks! I fixed those extra li bullets etc UI issues by adding that code at https://github.com/wekan/wekan/issues/4512#issuecomment-1129347536 to `wekan/client/components/main/layouts.css`.

**Comment by mfilser** [comment]
@xet7 
Great. And thank you too :slightly_smiling_face:

**Comment by xet7** [comment]
I added wiki page for more clear summary: https://github.com/wekan/wekan/wiki/Converting-Meteor-Stylus-to-CSS

**Comment by DimDz** [comment]
Using v6.26, I cannot change language on my other PCs it's just untranslated as seen on the screenshot. I use Docker or source using Ubuntu 22.04

![image](https://user-images.githubusercontent.com/70445835/169760793-8c71a326-aecc-49c5-8b2e-7bcd2f144ea7.png)

**Comment by xet7** [comment]
@DimDz See https://github.com/wekan/wekan/issues/4518#issuecomment-1133763518

**Comment by DimDz** [comment]
@xet7 already seen, and done as described on both PCs. On host PC, works as intended. On alt PCs, it doesn't. Tried using chrome and edge, same results.

**Comment by xet7** [comment]
@DimDz 

What language are you trying to use?

**Comment by xet7** [comment]
@DimDz 

Did you set ROOT_URL correctly?

https://github.com/wekan/wekan/wiki/Settings

For example, see ip address with command on WSL2:
```
ip address
```
And then in start-wekan.sh, set your WSL2 ip address here:
```
export ROOT_URL=http://192.168.0.200
export PORT=80
```
And then at remote PC, browse to http://192.168.0.200

**Comment by xet7** [comment]
Also, WSL2 has some problems with network access, because of resolv.conf . To fix it, edit it:
```
sudo nano /etc/resolv.conf
```
And there change it to some working nameserver, like cloudflare:
```
nameserver 1.1.1.1
```
Or Google:
```
nameserver 8.8.8.8
```
Then Ctrl-o Enter Ctrl-x.
Then network should work, like apt, etc.

**Comment by xet7** [comment]
Also at that resolv.conf is info how to keep network settings:
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
```

**Comment by DimDz** [comment]
> @DimDz
> 
> What language are you trying to use?

English, tried other languages too with no result.


> @DimDz
> 
> Did you set ROOT_URL correctly?
> 
> https://github.com/wekan/wekan/wiki/Settings
> 
> For example, see ip address with command on WSL2:
> 
> ```
> ip address
> ```
> 
> And then in start-wekan.sh, set your WSL2 ip address here:
> 
> ```
> export ROOT_URL=http://192.168.0.200
> export PORT=80
> ```
> 
> And then at remote PC, browse to http://192.168.0.200

Already done, with ports on firewall too.



> Also, WSL2 has some problems with network access, because of resolv.conf . To fix it, edit it:
> 
> ```
> sudo nano /etc/resolv.conf
> ```
> 
> And there change it to some working nameserver, like cloudflare:
> 
> ```
> nameserver 1.1.1.1
> ```
> 
> Or Google:
> 
> ```
> nameserver 8.8.8.8
> ```
> 
> Then Ctrl-o Enter Ctrl-x. Then network should work, like apt, etc.



> Also at that resolv.conf is info how to keep network settings:
> 
> ```
> # This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
> # [network]
> # generateResolvConf = false
> ```

Did that too, no result.

It was working just fine at wekan v6.22 though, no changes on my configuration. But after updating to v6.23-v.6.26 it doesn't change to any language. It's like it's not reading the i18n files.

**Comment by xet7** [comment]
@DimDz 

Maybe it's some other problem with WSL2 ?

Can you try Docker version docker-compose.yml from https://github.com/wekan/wekan ? It's Linux container type.

**Comment by DimDz** [comment]
> @DimDz
> 
> Maybe it's some other problem with WSL2 ?
> 
> Can you try Docker version docker-compose.yml from https://github.com/wekan/wekan ? It's Linux container type.

Docker-compose did the work. Thanks a lot for your kind help.

**Comment by C0rn3j** [comment]
@xet7 Isn't this done?

https://github.com/wekan/wekan/releases/tag/v6.56

Seems that latest release already uses 2.8
