### ISSUE TITLE
Trying CAS Auth

### ISSUE THREAD

**Issue by jgribonvald** [wekan/wekan#4515]
### Server Setup Information

* Did you test in newest Wekan?: **yes v6.22 and builded docker image from latest source**
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? **yes**
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): **docker-compose**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **Apache**
* Node.js Version:
* MongoDB Version: **5**
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? **latest Firefox and Chrome on Ubuntu 20**

### Problem description

All work well if I'm using password avvount but when I set the CAS auth we don't get any redirect to CAS. I've tested with  `PASSWORD_LOGIN_ENABLED=false` and to `true` but no redirect is launched, I'm staying on https://my.domain.tld/wekan/sign-in

getting this page only:
![Sélection_297](https://user-images.githubusercontent.com/1597283/169013994-7555fdc8-67a7-41d6-9979-62ce34d968d5.png)

#### Reproduction Steps
1/ set these params into docker-compose.yml:
```
      - PASSWORD_LOGIN_ENABLED=false
      #-------------------------------------------------------------------
      - CAS_ENABLED=true
      - CAS_BASE_URL=https://my.domain.tld/cas
      - CAS_LOGIN_URL=https://my.domain.tld/login
      - CAS_VALIDATE_URL=https://my.domain.tld/cas/serviceValidate
```
2/ run `docker-compose up --build`
3/ go on `https://my.domain.tld/wekan`

#### Logs

I don't have any request to my CAS server URL

**Comment by xet7** [comment]
@jgribonvald 

I'm still waiting for funding for CAS at https://github.com/wekan/wekan/issues/3204#issuecomment-1038961524

I have never setup or used any CAS server.

Anyway, if you would like to figure it out and submit PR to https://github.com/wekan/wekan/pulls , some info:

- [Building WeKan from source and submitting PR](https://github.com/wekan/wekan/wiki/Emoji)
- https://github.com/wekan/wekan/tree/master/packages/wekan-accounts-cas
- https://github.com/wekan/wekan/wiki/CAS
- [CAS related added PRs](https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+CAS)
- RocketChat repo may have some newer CAS code https://github.com/RocketChat/Rocket.Chat

**Comment by xet7** [comment]
Moved to #3204
