### ISSUE TITLE
change langage not work

### ISSUE THREAD

**Issue by s-honda** [wekan/wekan#4518]
at docker image v6.24 & v6.23 change langage not work.
when external PC(windows10) access to wekan server.

docker image v6.22 work good.

best regards

**Comment by xet7** [comment]
@s-honda 

With what webbrowser?

**Comment by s-honda** [comment]
I checked in Google Chrome 101.0.4951.47 
and Microsoft Edge v101.0.1210.47

**Comment by s-honda** [comment]
My wekan server is running docker on centos7.

Language change is working fine on firefox on centos ( wekan running docker ).

However, when I access wekan from an external windows pc, 
the language change does not work and I cannot change from English.

**Comment by xet7** [comment]
Please test WeKan v6.26

**Comment by s-honda** [comment]
v6.26 was the same as v6.24.

**Comment by s-honda** [comment]
I installed firefox (v100.0.2) on my windows PC and tried it out.
wekan v6.26 worked the same as Microsoft Edge.

**Comment by s-honda** [comment]
I think it's probably due to a different version of Meteor, but what about it?

wekan v6.22 & meteor v2.2 work fine
Wekan v6.23 ～ & meteor v2.7.2 seems to have a problem

<img width="431" alt="wekan_v6 22" src="https://user-images.githubusercontent.com/17880909/169638959-4832be27-74b7-43a8-9404-3f5c3d88ee34.PNG">
<img width="402" alt="wekan_v6 23" src="https://user-images.githubusercontent.com/17880909/169638964-415f707c-9b0d-4500-a611-bc5aa0e5d94d.PNG">

**Comment by xet7** [comment]
@s-honda 

What language you are using?

**Comment by xet7** [comment]
@s-honda 

It could be that some language is not detected correctly. For me, Finnish language is detected.

**Comment by xet7** [comment]
@s-honda 

For me, detecting Finnish works for me in Windows 11 Build 22598.ni_releases.220408-1503:
- Chrome 101.0.4951.67
- Edge 101.0.1210.53
- Firefox 100.0.2

These work:
- When I login, language is detected correctly as Finnish
- I can change language at top right menu

I'll try to find are other languages detected.

**Comment by xet7** [comment]
@s-honda 

Ok, from your screenshot it looks like you are using Japanese (ja). I'll try how it works in WeKan.

**Comment by xet7** [comment]
@s-honda 

To show WeKan in Japanese, there needs to be only Japanese selected at Firefox Preferences / Choose your preferred language for displaying pages. Delete all other languages from there, there needs to be only Japanese, like this:

<img width="714" alt="wekan-language" src="https://user-images.githubusercontent.com/15545/169667806-88585bbf-4a8d-49ed-a4ad-473cd2a5203b.png">

After that, WeKan is in Japanese:

<img width="583" alt="admin-panel" src="https://user-images.githubusercontent.com/15545/169667820-51ef8368-89ae-4aee-8e93-13a3722f8a98.png">

Not everything is transated to Japanese yet. You can help by translating to Japanese at https://transifex.com/wekan/wekan . Thanks !

Does this help?

**Comment by s-honda** [comment]
Thank you for your support.
There seems to be something wrong with my PC.
I will report when the cause is known.
Thanks !

**Comment by s-honda** [comment]
I have identified the cause.
I forgot to set the ROOT_URL.
I set ROOT_URL and it worked fine with v6.26.
In v6.22, it worked normally without setting ROOT_URL, so I didn't notice it.
Thank you for your support.

**Comment by gitaarik** [comment]
For documentation sake: I had the `ROOT_URL` set to `localhost` but I should've used the IP-address (or domain name eventually), because  I was accessing the web UI with the IP-address, and it got a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error on `localhost`.
