### ISSUE TITLE
Apache configuration not working -- workaround

### ISSUE THREAD

**Issue by hermannkm** [wekan/wekan#4520]
## Issue

Wekan: latest (6.09), Apache/2.4.29 (Ubuntu 18.04)

Using the apache configuration shown [here](https://github.com/wekan/wekan/wiki/Apache) ("Main URL") I got a 403. Adding this block after Proxy Statements

```
      <Proxy *>
            Options FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Proxy>
```

solved this.

**Comment by xet7** [comment]
@hermannkm 

Thanks! I added those to wiki page.
