### ISSUE TITLE
No preview and no cover in browser

### ISSUE THREAD

**Issue by belf88** [wekan/wekan#4524]
I created a board with 50 lists and about 400 cards. If I attach a pdf file or an image file I cannot view it directly in the web browser and I have to download it to my computer. the same thing happens with the preview of the image files on the cover. Are you aware of this error? When I open a card I see the 3 blue dots of loading under the attached item.

This did not happen before when there were fewer cards and lists.

**Comment by xet7** [comment]
@belf88 

What WeKan version? Please [Backup](https://github.com/wekan/wekan/wiki/Backup) and try with WeKan v6.26 docker-compose.yml from https://github.com/wekan/wekan

**Comment by xet7** [comment]
WeKan has bitmap image viewer, for .png , .jpg etc.

WeKan does not have PDF viewer.

**Comment by belf88** [comment]
> 
> WeKan does not have PDF viewer.

few days ago I was seeing PDF files in the browser

I use WeKan ® Version | 6.09.0

**Comment by xet7** [comment]
@belf88 

Most likely you are using newest Snap version. Snap builds are currently broken https://github.com/wekan/wekan/issues/4423#issuecomment-1112181784 , I'm trying to figure out how to fix them.

Newest WeKan v6.26 has huge amount of upgrades, including newest Meteor etc.

**Comment by xet7** [comment]
Hmm, interesting. Some new Snap build did finish successfully. I'll try can I fix it so it works.

**Comment by xet7** [comment]
I'm not sure did Snap/Canonical fix something there, or did I fix something with some change, so that build did work.

**Comment by VidVidex** [comment]
@xet7 I think this can also be closed as pdf previewing is now supported
