### ISSUE TITLE
Keycloak/CA Certificate "unable to verify the first certificate"

### ISSUE THREAD

**Issue by MarcBollmann** [wekan/wekan#4525]
Hello currently im trying to setup WeKan with Keycloack and Docker in an intranet environment this means I have to use my own CA certificate. In my `docker-compose` I set up keycloak/oauth like this. 

```
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=wekan
      - OAUTH2_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - OAUTH2_SERVER_URL=https://auth.mtg/auth
      - OAUTH2_AUTH_ENDPOINT=/realms/MTG/protocol/openid-connect/auth
      - OAUTH2_USERINFO_ENDPOINT=/realms/MTG/protocol/openid-connect/userinfo
      - OAUTH2_TOKEN_ENDPOINT=/realms/MTG/protocol/openid-connect/token
      - OAUTH2_FULLNAME_MAP=name
      - OAUTH2_REQUEST_PERMISSIONS=openid profile email
      - OAUTH2_USERNAME_MAP=email
      - OAUTH2_ID_MAP=preferred_username
      - OAUTH2_EMAIL_MAP=email
      - OAUTH2_CA_CERT=-----BEGIN CERTIFICATE-----XXXXXXXXXX-----END CERTIFICATE-----
```

But when I'm trying to login via keycloak im getting the following error code:

```
{"line":"406","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC https://auth.mtg/auth/realms/MTG/protocol/openid-connect/token: request to https://auth.mtg/auth/realms/MTG/protocol/openid-connect/token failed, reason: unable to verify the first certificate","time":{"$date":1653390617024},"level":"warn"}
```

It seems that the `OAUTH2_CA_CERT` parameter doesn't seem to have any effect in this use case and my CA certificate isn't being utilized. 

I also tried to modify the dockerfile to install the custom ca, but it seems WeKan isn't using the CA certificate.

```
FROM wekanteam/wekan:v6.26
WORKDIR /
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates
ADD CA.crt /usr/local/share/ca-certificates/CA.crt
RUN update-ca-certificates
```

I hope someone can help me out with this issue and/or faced similar problems.
Greetings Marc

**Comment by MarcBollmann** [comment]
Okay I solved it myself I had to modify the dockerfile in 2 steps:
1. Install the ca-cert into the Ubuntu docker-image
2. Tell node.js to use ca-certs with the launch option 'node --use-openssl-ca'

The final result:
```
FROM wekanteam/wekan:v6.26
WORKDIR /
USER root
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates
ADD CA.crt /usr/local/share/ca-certificates/CA.crt
RUN update-ca-certificates
CMD ["bash", "-c", "ulimit -s 65500; exec node --use-openssl-ca --stack-size=65500 /build/main.js"]
```

**Comment by Neferites** [comment]
Hello,
it's also possible to import your own CA in a volume, and add an env var with the CA's path : 
NODE_EXTRA_CA_CERTS = "My ca path"
Regards

**Comment by adelphi-company** [comment]
@Neferites  Could you please share how to add a volume ? I tried to change the docker-compose.yml File but for some reason my volume is not  mounted ... The following are the relevant parts of my configuration 
`
  wekan:
    #-------------------------------------------------------------------------------------
    # ==== MONGODB AND METEOR VERSION ====
    # a) Quay automatic builds do work work, https://quay.io/wekan/wekan
    image: quay.io/wekan/wekan:v6.41
    volumes:
      - /srv/docker-src/docker-ca:/mnt
     ...
    environment:
      - NODE_EXTRA_CA_CERTS=/mnt/CA.crt
`
I just get the warnign  CA.rt not found and indeed it si missing inside the container but i have no clue why.
