### ISSUE TITLE
Localization text not being set properly, can't change language

### ISSUE THREAD

**Issue by Sdub76** [wekan/wekan#4526]
## Issue
Localization seems to be broken in my installation.  Rather than localized text, it shows generic placeholder text:
<img width="229" alt="image" src="https://user-images.githubusercontent.com/11237911/170029729-10d1a8c2-de62-4b7a-971e-f57420471f6f.png">

If I try to switch languages, nothing happens.  Clicking on another item in the list has no effect.  The language won't change.  

<img width="244" alt="image" src="https://user-images.githubusercontent.com/11237911/170033284-c62fbcd5-2ea2-4564-886e-72b6c7feaf00.png">

### Server Setup Information
Tested on multiple browsers (FF, Edge) across multiple computers

<img width="430" alt="image" src="https://user-images.githubusercontent.com/11237911/170032557-acf49866-20fc-4949-9a1e-547e6ecbfa44.png">

**Comment by xet7** [comment]
Try Docker https://github.com/wekan/wekan/issues/4512#issuecomment-1134531906

**Comment by Sdub76** [comment]
The issue was the ROOT_URL.  I had forgotten that I recently changed the site name.

I'm using Unraid which doesn't use docker compose, so that wasn't an option.  I noticed that the default Unraid docker template lacks many of the env vars in the docker_compose.yaml file so I went ahead and added them to my docker template for good measure.
