### ISSUE TITLE
After upgrading to 6.23 authenticating against the Wekan api fails

### ISSUE THREAD

**Issue by ChrisMagnuson** [wekan/wekan#4528]
We are running Wekan hosted on Cloudron and after upgrading to 6.23 and all subsequent updates through to 6.26 which we are running currently we have no longer been able to authenticate against the Wekan api using credentials that use Authentication method password or Authentication method LDAP.

We access the api via N8N work flows as well as directly via Powershell calls to the api and both are failing since upgrading to 6.23.

**Comment by xet7** [comment]
@ChrisMagnuson 

Thanks! I'll try does WeKan API work.

**Comment by xet7** [comment]
WeKan API does not work.

It seems there is this old fork of `simple:json-routes` that was originally created to not conflict with `ostrio:files`, that was recently added to WeKan to provide better attachments migration support. I'll try to find is there somewhere a more up-to-date fork, and does there need to be some code changes, is syntax different in newer API related json-routes code.

https://github.com/apiko-dev/meteor-json-routes

**Comment by ThomasSchoeller** [comment]
maybe related to #4039

**Comment by xet7** [comment]
@ThomasSchoeller 

API did work as Admin before Meteor and Meteor-Files upgrades. After upgrades, API does not work as Admin.

That User API etc can be fixed after it's found how to make Admin API working.

Currently all API does not work.

**Comment by DimDz** [comment]
Any news about API?

**Comment by xet7** [comment]
@DimDz 

API does not work yet. Anyway, I'll try to figure it out and fix it.

**Comment by xet7** [comment]
That meteor-json-routes `jss:json-routes` did  not work, I tried it couple of days ago.

Yesterday I got tip from some Meteor developer to try this https://github.com/leaonline/http-factory , can I get REST API working with it. I'll try.

**Comment by xet7** [comment]
Well, that http-factory looks like it uses custom header, and there is no mention about would it work with Meteor logins.

I presume that I'll instead try to modify kadira-flow-router, would that make API working.

**Comment by ertanalytics** [comment]
My Add card is still working and I believe the only one I have trouble with today is the export one I wrote up::

`#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vi:ts=4:et
import imp

Login = '[OMITTED]'
import pycurl

try:
    # python 3
    from urllib.parse import urlencode
except ImportError:
    # python 2
    from urllib import urlencode

import certifi
import json
from io import BytesIO
import sys

arguments = len(sys.argv) - 1
print("# of arguments passed: " + str(arguments))
if arguments == 0:
    print("=== Wekan API Python CLI: Shows IDs for addcard ===")
    print("Argument Count passed -1 = " + arguments)
    print("AUTHORID is USERID that writes card.")
    print("Syntax:")
    print("  python3 wekan.py users              # All users")
    print("  python3 wekan.py boards USERID      # Boards of USERID")
    print("  python3 wekan.py board BOARDID      # Info of BOARDID")
    print("  python3 wekan.py swimlanes BOARDID  # Swimlanes of BOARDID")
    print("  python3 wekan.py lists BOARDID      # Lists of BOARDID")
    print("  python3 wekan.py addcard AUTHORID BOARDID SWIMLANEID LISTID CARDTITLE CARDDESCRIPTION")
    exit

# ------- SETTINGS START -------------

username = '[OMITTED]'
password = Login.botPass
wekanurl = 'https://'[OMITTED]'.'[OMITTED]'.com/'

# SYNTAX
# python3 wekan.py addcard AUTHORID BOARDID SWIMLANEID LISTID CARDTITLE CARDDESCRIPTION

# EXAMPLE 1:
# Write to original test board
# python3 wekan.py addcard ZM4XxTMFfJZfRmo2d ks9JgJZX3Nw7rdunt NBDpWDW6xYTyoojF4 hXgbH6WD3nCFnSQPk "Test z" "Desc z"

# EXAMPLE 2:
# Write to Welcome board
# python3 wekan.py addcard ZM4XxTMFfJZfRmo2d X4g32tZd88PKkK7Wh iR3n6vWmBMo5Po6Gm G2diahhy2Di775dAe "Welcome test" "Desc test"

# ------- SETTINGS END -------------

# ------- API URL GERENARTION START -----------

loginurl = 'users/login'
wekanloginurl = wekanurl + loginurl
apiboards = 'api/boards/'
apiusers = 'api/users/'
s = '/'
l = 'lists'
sw = 'swimlane'
sws = 'swimlanes'
lbl = 'labels'
cs = 'cards'
bs = 'boards'
users = wekanurl + apiusers

# ------- API URL GERENARTION END -----------

# ------- LOGIN TOKEN START -----------

buffer = BytesIO()
c = pycurl.Curl()
c.setopt(c.URL, wekanloginurl)
c.setopt(c.WRITEDATA, buffer)
c.setopt(c.CAINFO, certifi.where())
post_data = {"username": username, "password": password}
# Form data must be provided already urlencoded.
postfields = urlencode(post_data)
# Sets request method to POST,
# Content-Type header to application/x-www-form-urlencoded
# and data to send in request body.
c.setopt(c.POSTFIELDS, postfields)

c.perform()
c.close()

body = buffer.getvalue()
# Body is a byte string.
# We have to know the encoding in order to print it to a text file
# such as standard output.
data = body.decode('iso-8859-1')
# print(data)
d = json.loads(data)
# print(list(d.keys()))
# print(d['token'])
apikey = d['token']

# ------- LOGIN TOKEN END -----------

if arguments == 7:

    if sys.argv[1] == 'addcard':
        # ------- WRITE TO CARD START -----------
        authorid = sys.argv[2]
        boardid = sys.argv[3]
        swimlaneid = sys.argv[4]
        listid = sys.argv[5]
        cardtitle = sys.argv[6]
        carddescription = sys.argv[7]
        # memberids = sys.argv[8]

        # authorid = ''
        # boardid = sys.argv[3]
        # swimlaneid = sys.argv[4]
        # listid = sys.argv[5]
        # cardtitle = sys.argv[6]
        # carddescription = sys.argv[7]
        cardtolist = wekanurl + apiboards + boardid + s + l + s + listid + s + cs
        # Write to card
        c = pycurl.Curl()
        c.setopt(c.URL, cardtolist)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        post_data = {"authorId": authorid, "title": cardtitle, "description": carddescription, "swimlaneId": swimlaneid}
        # Form data must be provided already urlencoded.
        postfields = urlencode(post_data)
        # Sets request method to POST,
        # Content-Type header to application/x-www-form-urlencoded
        # and data to send in request body.
        c.setopt(c.POSTFIELDS, postfields)
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print(data)

    # ------- WRITE TO CARD END -----------
if arguments == 8:

    if sys.argv[1] == 'addcard':
        # ------- WRITE TO CARD START -----------
        authorid = sys.argv[2]
        boardid = sys.argv[3]
        swimlaneid = sys.argv[4]
        listid = sys.argv[5]
        cardtitle = sys.argv[6]
        carddescription = sys.argv[7]
        memberids = sys.argv[8]
        print("Member IDs passed in argument 8: " + str(memberids))

        #memberids = 'K4ciboHrbgiFBvvWL,S3tGjofrtCeiKsp8c'
        memberlist = []
        for m in memberids.split(","):
            memberlist.append(m)
        memberlist = list(set(memberlist))


        # authorid = ''
        # boardid = sys.argv[3]
        # swimlaneid = sys.argv[4]
        # listid = sys.argv[5]
        # cardtitle = sys.argv[6]
        # carddescription = sys.argv[7]
        cardtolist = wekanurl + apiboards + boardid + s + l + s + listid + s + cs
        # Write to card
        c = pycurl.Curl()
        c.setopt(c.URL, cardtolist)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        post_data = {"authorId": authorid, "title": cardtitle, "description": carddescription, "swimlaneId": swimlaneid, "members": memberids}
        # Form data must be provided already urlencoded.
        postfields = urlencode(post_data)
        for member in memberlist:
            postfields = postfields + '&members=' + member
        print(postfields)
        # Sets request method to POST,
        # Content-Type header to application/x-www-form-urlencoded
        # and data to send in request body.
        c.setopt(c.POSTFIELDS, postfields)
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print(data)

    # ------- WRITE TO CARD END -----------
#print("Test Argument: " + sys.argv[6])
if arguments == 22:
    if sys.argv[1] == 'editcard_full':
        # ------- WRITE TO CARD START -----------

        cardid = sys.argv[2]
        boardid = sys.argv[3]
        swimlaneid = sys.argv[4]
        listid = sys.argv[5]

        cardtitle = sys.argv[6]  # the new title of the card
        listId = sys.argv[7]  # the new list ID of the card (move operation)
        authorId = sys.argv[8]  # change the owner of the card
        description = sys.argv[9]  # the new description of the card
        color = sys.argv[10]  # the new color of the card
        labelIds = sys.argv[11]  # the new list of label IDs attached to the card
        requestedBy = sys.argv[12]  # the new requestedBy field of the card
        assignedBy = sys.argv[13]  # the new assignedBy field of the card
        receivedAt = sys.argv[14]  # the new receivedAt field of the card
        startAt = sys.argv[15]  # the new startAt field of the card
        dueAt = sys.argv[16]  # the new dueAt field of the card
        endAt = sys.argv[17]  # the new endAt field of the card
        spentTime = sys.argv[18]  # the new spentTime field of the card
        isOverTime = sys.argv[19]  # 'true/false' # the new isOverTime field of the card
        customFields = sys.argv[20]  # the new customFields value of the card
        members = sys.argv[21]  # the new list of member IDs attached to the card
        swimlaneId = sys.argv[22]  # the new swimlane ID of the card

        cardtolist = wekanurl + apiboards + boardid + s + l + s + listid + s + cs + cardid
        # Write to card
        c = pycurl.Curl()
        c.setopt(c.URL, cardtolist)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.VERBOSE, True)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.CUSTOMREQUEST, "PUT")
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        put_data = {"title": cardtitle,
                    "listId": listId,
                    "authorId": authorId,
                    "description": description,
                    "color": color,
                    "labelIds": labelIds,
                    "requestedBy": requestedBy,
                    "assignedBy": assignedBy,
                    "receivedAt": receivedAt,
                    "startAt": startAt,
                    "dueAt": dueAt,
                    "endAt": endAt,
                    "spentTime": spentTime,
                    "isOverTime": isOverTime,
                    "customFields": customFields,
                    "members": members,
                    "swimlaneId": swimlaneid}
        # Form data must be provided already urlencoded.
        putfields = urlencode(put_data)
        # Sets request method to POST,
        # Content-Type header to application/x-www-form-urlencoded
        # and data to send in request body.
        c.setopt(c.POSTFIELDS, putfields)
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print(data)
        print(c)

        # body = c.getinfo(pycurl.HTTP_CODE)
        # data = body.decode('iso-8859-1')

        # print(data)

    # ------- WRITE TO CARD END -----------

if arguments == 8:
    if sys.argv[1] == 'editcard':
        print("On Edit Card")
        # ------- WRITE TO CARD START -----------
        cardid = sys.argv[2]

        print("On Card ID: " + cardid)


        boardid = sys.argv[3]
        swimlaneid = sys.argv[4]
        listid = sys.argv[5]

        print("On List ID: " + listid)

        cardtitle = sys.argv[6]  # the new title of the card
        description = sys.argv[7]  # the new description of the card
        requestedBy = sys.argv[8]  # the new customFields value of the card

        cardtolist = wekanurl + apiboards + boardid + s + l + s + listid + s + cs + cardid
        # Write to card
        c = pycurl.Curl()
        c.setopt(c.URL, cardtolist)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.CUSTOMREQUEST, "PUT")
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        put_data = {"board": boardid,
                    "list": listid,
                    "card": cardid,
                    "body": '',
                    "swimlaneId": swimlaneid,
                    "title": cardtitle,
                    "description": description,
                    "requestedBy": requestedBy}
        # Form data must be provided already urlencoded.
        putfields = urlencode(put_data)
        # Sets request method to POST,
        # Content-Type header to application/x-www-form-urlencoded
        # and data to send in request body.
        c.setopt(c.POSTFIELDS, putfields)
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print(data)

    # ------- WRITE TO CARD END -----------

if arguments == 2:

    # ------- BOARDS LIST START -----------
    userid = sys.argv[2]
    boards = wekanurl + apiusers + userid + s + bs
    if sys.argv[1] == 'boards':
        c = pycurl.Curl()
        c.setopt(c.URL, boards)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print("=== BOARDS ===\n")
        data2 = data.replace('}', "}\n")
        print(data2)
        print("\n")
        data = ""
    # ------- BOARDS LIST END -----------

    if sys.argv[1] == 'board':
        # ------- BOARD INFO START -----------
        boardid = sys.argv[2]
        board = wekanurl + apiboards + boardid
        c = pycurl.Curl()
        c.setopt(c.URL, board)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print("=== BOARD ===\n")
        data2 = data.replace('}', "}\n")
        print(data2)
        print("\n")
        data = ""

        # ------- BOARD INFO END -----------

    if sys.argv[1] == 'swimlanes':
        boardid = sys.argv[2]
        swimlanes = wekanurl + apiboards + boardid + s + sws
        # ------- SWIMLANES OF BOARD START -----------
        c = pycurl.Curl()
        c.setopt(c.URL, swimlanes)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print("=== SWIMLANES ===\n")
        data2 = data.replace('}', "}\n")
        print(data2)
        print("\n")
        data = ""
        # ------- SWIMLANES OF BOARD END -----------

    if sys.argv[1] == 'labels':
        boardid = sys.argv[2]
        labels = wekanurl + apiboards + boardid + s + lbl
        # ------- LABELS OF BOARD START -----------
        c = pycurl.Curl()
        c.setopt(c.URL, labels)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print("=== LABELS ===\n")
        data2 = data.replace('}', "}\n")
        print(data2)
        print("\n")
        data = ""
        # ------- LABELS OF BOARD END -----------

    if sys.argv[1] == 'lists':
        # ------- LISTS OF BOARD START -----------
        boardid = sys.argv[2]
        lists = wekanurl + apiboards + boardid + s + l
        c = pycurl.Curl()
        c.setopt(c.URL, lists)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print("=== LISTS ===\n")
        data2 = data.replace('}', "}\n")
        print(data2)
        print("\n")
        data = ""
        # ------- LISTS OF BOARD END -----------

if arguments == 1:

    if sys.argv[1] == 'users':
        # ------- LIST OF USERS START -----------
        c = pycurl.Curl()
        c.setopt(c.URL, users)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.CAINFO, certifi.where())
        c.setopt(c.HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer {}'.format(apikey)])
        c.perform()
        c.close()
        body = buffer.getvalue()
        data = body.decode('iso-8859-1')
        print("=== USERS ===\n")
        data2 = data.replace('}', "}\n")
        print(data2)
        print("\n")
        data = ""
        # ------- LIST OF USERS END -----------

"""
authorId: string
members: string
assignees: string
title: string
description: string
swimlaneId: string
"""

`

**Comment by valen14** [comment]
Hi ! n8n no conecta con la api a partir de la version 6.23 de wekan

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/commit/aa2c3774a233025a163e9d9c210ad2f1807c0acb
