### ISSUE TITLE
macOS Mojave Safari 14.12 and iPad Safari: No longer able to create new labels / cannot see label color palette after upgrade

### ISSUE THREAD

**Issue by huguesderiau** [wekan/wekan#4529]
Wekan Docker Mac

WeKan Version	6.26.0
Meteor version	2.7.2
Node version	14.19.3
MongoDB version	5.0.8

After upgrading to 6.26, when clicking on Create Label
- the color palette is no longer displayed
- if entering a name and click "Create", the new label is not created

![Screen Shot 2022-05-24 at 10 40 46 AM](https://user-images.githubusercontent.com/72530102/170098947-d33f6fed-f7da-41c6-a502-476f3e39dbac.jpg)
d

**Comment by xet7** [comment]
@huguesderiau 

Do you also have PORT=80  ?

**Comment by xet7** [comment]
I mean like this:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L145

**Comment by huguesderiau** [comment]
Yes I have 80:8080

**Comment by xet7** [comment]
@huguesderiau 

What webbrowser are you using?

**Comment by huguesderiau** [comment]
Safari 14.12

**Comment by xet7** [comment]
@huguesderiau 

Is creating labels visible in Chrome or Firefox ?

**Comment by huguesderiau** [comment]
I can in FF, it behaves fine

**Comment by xet7** [comment]
@huguesderiau 

What macOS version are you using? Is it Intel or M1 Mac?

**Comment by xet7** [comment]
I presume you have old Safari version.

**Comment by huguesderiau** [comment]
Intel 
Yes I'm running OSX 10.14.6

**Comment by huguesderiau** [comment]
I just tried Chrome, it's working fine there too

**Comment by xet7** [comment]
Newest is Safari 15.5 on macOS Monterey, there label color palette is visible. Saferi version could depend on macOS version used.

But usually macOS Mojave users still have important expensive software that is only compatible with macOS Mojave, like some software that has 32bit parts. In that case it's not recommended to upgrade.

Easiest is to use Firefox or Chrome.

I currently use WaterFox https://www.waterfox.net on some computers, because it's more privacy friendly.

**Comment by huguesderiau** [comment]
Yep, That's what I'm still on Mojave, for my Adobe apps ...
So I'm assuming this new issue won't be fixed?

**Comment by xet7** [comment]
Well, maybe, or maybe not. I'm trying to add support for even more browser versions.

**Comment by huguesderiau** [comment]
OK, thank you for all your efforts, love the app!

**Comment by huguesderiau** [comment]
This issue is no longer present after I upgraded to Wekan 6.2

![Screen Shot 2022-06-22 at 10 21 44 AM](https://user-images.githubusercontent.com/72530102/175099270-822d4b77-19aa-40f8-9dc1-6d541ca752e4.jpg)
8
