### ISSUE TITLE
Cannot drag and drop in Linux (usually)

### ISSUE THREAD

**Issue by ragesoss** [wekan/wekan#453]
I'm running the latest release via Sandstorm, and I can hardly ever drag and drop cards to reorder them or switch columns. It seems to occasional become functional (and then, all the dragging and dropping works), but most of the time, it does not work. This is the case for me on Iceweasel and Chromium on Debian, as well as Firefox on Ubuntu.

**Comment by iwazaru** [comment]
I'm having the same issue on Mac OS X, tried with Chrome, Firefox and Safari.

**Comment by mquandalle** [comment]
It sounds like a critical problem but I haven’t reproduced it yet. @iwazaru are you using Sandstorm as well?

To help figuring out what is happening could you also share the browser version and take took in the browser console to see if there are some errors there?

**Comment by ragesoss** [comment]
For me, this has been present since before 0.10. I get no obvious errors in the console.

Happening for me in Iceweasel 38 as well as Chromium 46.

**Comment by nhducit** [comment]
I got this problem with, Fedora 23, google chrome 47

**Comment by mquandalle** [comment]
@nhducit The above log is actually related to a *à priori* benign edge case in Sandstorm, see https://github.com/sandstorm-io/sandstorm/issues/1318.

**Comment by nhducit** [comment]
@mquandalle thank you, I'll waiting for new version of sandstorm :)

**Comment by iwazaru** [comment]
The bug seems to be fixed for reordering cards, but I still can't drag-and-drop tags on cards (Mac Os X, Chrome, Sandstorm, Wekan 0.10.1).

**Comment by nhducit** [comment]
I have same problem as @iwazaru, wekan via sandstorm, fedora 23
