### ISSUE TITLE
Text next to checklist items

### ISSUE THREAD

**Issue by DimDz** [wekan/wekan#4544]
Hello all,
this is something I am trying to make.
![Screenshot_1](https://user-images.githubusercontent.com/70445835/171617357-2fb13b86-ec41-41c6-86bb-83113dfc99ae.png)
what i am trying to do is to have a text input where I can put a date/text/etc for every checklist item.
My issue is that I cannot find where checklist values are stored so I can save the values I put inside the boxes.
Any help is appreciated.

**Comment by xet7** [comment]
Checklists are stored at MongoDB database, wekan/models, like here https://github.com/wekan/wekan/tree/master/models

Although, they could be also at activities. Current database structure could be kind of funny. It will be improved in SQLite version. There should be in future tables for current newest data, and different tables for historical changes. That will help doing sum, etc stats, like at #3796
