### ISSUE TITLE
Binary release on releases.wekan.team lacks the CSS

### ISSUE THREAD

**Issue by znerol** [wekan/wekan#4545]
## Issue

The [zip file](https://releases.wekan.team/wekan-latest-x64.zip) currently available from the releases.wekan.team server seems to lack the aggregated CSS file.

```
$ zipinfo wekan-latest-x64.zip | grep 'programs/web.browser/*.css'
```

When building wekan using `meteor build --directory /tmp/wekan` I find the following:

```
$ ls /tmp/wekan/bundle/programs/web.browser/*.css
/tmp/wekan/bundle/programs/web.browser/486842d9c14f4308b7c42bf9e7463eb50fb157df.css
```

### Server Setup Information

N/A

#### Reproduction Steps

Download zip file from releases.wekan.team and examine its contents.

#### Logs

N/A

**Comment by mrcancer91** [comment]
Same here! 
Btw, when I try to build from source, the test run on localhost:4000 shows a blank page with nothing inside from v6.24 to v6.27. Meanwhile, v6.23 runs as expected. 

Server Information: 
- MacOS (Intel): Monterey v12.4 
- Node: v14.19.3
- Meteor: 2.7.2
- Mongo: 5.0.6

**Comment by BabyFnord** [comment]
I can reproduce this problem on a bundle install v6.27 (https://releases.wekan.team/6.27.zip). WeKan renders a plain text website with huge graphics inbetween … very reminiscent of Netscape Navigator times 😄.

**Comment by xet7** [comment]
Strange thing is, that when I build WeKan on Debian, there is no errors at browser inspect console, and board is visible.

But when I build WeKan on macOS Monterey, there are errors at browser inspect console, and board is not visible at all, because of those errors.

I did remove lightbox component that caused errors at browser inspect console, when building on Debian.

Anyway, I'll figure out some way to make board visible, with or without Javascript at frontend.

**Comment by BabyFnord** [comment]
@xet7 Bespoke issue is the same on my 6.27 bundle install. As far as I’m concerned this doesn‘t seem to be related with macOS on the client side.

**Comment by xet7** [comment]
Anyway, I already have idea about how to fix it. I'll move .css files to `wekan/public/css/html5/defaulttheme/` and then include those files at `wekan/client/components/main/layouts.jade`.

Similarly, I'm thinking about moving some .js files to `wekan/public/js/`

Then I'll remove those minifiers.

I'll try.

**Comment by xet7** [comment]
I think originally this happened, because I converted Stylus .styl files to .css, and removed Stylus, to fix many bugs. That Stylus code and minifiers did originally convert Stylus to CSS and minify them to one .css file, but after removing Stylus, that combining did not happen for .css files.

**Comment by xet7** [comment]
Well, my idea did not work, maybe those CSS files were in wrong order, layout was not same as before changes. Anyway, I'll try something else.
