### ISSUE TITLE
Feature Request: Change List Width. And easier install on CentOS 8

### ISSUE THREAD

**Issue by NLBlackEagle** [wekan/wekan#4558]
## Suggestion
A way to adjust the wekan board css so I can widen the list width.

### Server Setup Information
CentOs 8 and practically all methods of installing among which build from source and using a pre-packaged bundle setup both failed.

### Problem description
I have been attempting to install a version of wekan which would allow me to adjust or append CSS files but have not found a solution as of yet. A separate issue would be that my dedicated server is not able to build from source given it has crashed as I attempted to do this (Most likely due to a lack of performance) I realize that setting up a workspace vm on my own computer would solve this issue but this goes against my reason to use wekan which is to improve my productivity.

**Comment by NLBlackEagle** [comment]
Thanks! Is there a way I could customize the CSS without using a browser extension? I'm using WeKan as a roadmap with a public front and I can't exactly ask every visitor to install a browser extension or am I misunderstanding how it works?

**Comment by NLBlackEagle** [comment]
I have update to the latest branch [v6.30] and see that you have added a settings controlling .list {} width
list._id.width(), 

But I take it these settings have not found their way onto a button yet or am I missing something?

**Comment by xet7** [comment]
Currenly there is only changing any width, not saving yet. Yes, button is missing.

And someone would like to get fixed width back https://github.com/wekan/wekan/issues/4597

**Comment by mark-i-m** [comment]
@xet7 As I understand #4597, they only want to freeze the layout on their board, not freeze it for everyone using Wekan.

If I can figure it out, would you welcome a PR that adds back the changes in https://github.com/wekan/wekan/commit/01d0dd3b1dd0a3c9764e7c9d31eab739db2d3ad8, but makes it configurable by the admin only?

**Comment by xet7** [comment]
@mark-i-m 

This and #4904 should be per-user per-list and per-user per-swimlane profile setting. Simplest way would be to allow input integer number starting from from for example 100, and only allow input integer number (not text), so that list would not become invisible, and setting it in pixels.

There could be:
- List width setting at List ☰ menu, saved to users.js profile: boardId, listId, listWidth
- Swimlane height setting at Swimlane ☰ menu, saved to users.js profile: boardId, swimlaneId, swimlaneHeight

There is still about 780 issues open, all help is very welcome!

**Comment by xet7** [comment]
Making something more fancy, like adjusting width and heigh with drag-drop or slider would maybe be more complex to implement, that just input integer number.

**Comment by xet7** [comment]
So it is about:
- Building WeKan like at https://github.com/wekan/wekan/wiki/Emoji
- Adding new profile fields to wekan/models/users.js
- Adding new menu options to wekan/client/components/swimlanes/swimlane.jade (UI) and related Javascript code to swimlane.js (or similar files)
- similar to lists component
- Adding those new user profile values to be visible browseside at wekan/server/publications/users.js or similar

**Comment by xet7** [comment]
For any related code, can be found by searching:
```
cd wekan

./find.sh something
```

**Comment by xet7** [comment]
Change List Width added at https://github.com/wekan/wekan/pull/4964 . Thanks to @mark-i-m !
