### ISSUE TITLE
Update and backup

### ISSUE THREAD

**Issue by belf88** [wekan/wekan#4563]
hi, i need to update "ekan to the latest version. I have a lot of problems with slow loading.

I would like to keep all cards and boards created. is it possible to make a backup?

I created about 900 cards in 8 different boards.

Will updating to the latest version fix Wekan loading speed issues?

In admin panel I see this information:

WeKan ® Versione	
Versione Meteor	
Versione di Node	
Versione MongoDB	
Storage engine di MongoDB	
MongoDB Oplog abilitato	
Tipo SO	
Piattaforma SO	
Architettura SO	
Versione di rilascio SO	
Tempo di attività del SO	
Carico medio SO	NaN, NaN, NaN
Memoria totale SO	NaN undefined
Memoria libera SO	NaN undefined
Numero CPU SO	
Node heap: total heap size	NaN undefined
Node heap: total heap size executable	NaN undefined
Node heap: total physical size	NaN undefined
Node heap: total available size	NaN undefined
Node heap: used heap size	NaN undefined
Node heap: heap size limit	NaN undefined
Node heap: malloced memory	NaN undefined
Node heap: peak malloced memory	NaN undefined
Node heap: does zap garbage	
Node heap: number of native contexts	
Node heap: number of detached contexts	
Node memory usage: resident set size	NaN undefined
Node memory usage: total size of the allocated heap	NaN undefined
Utilizzo memoria del nodo: memoria effettivamente usata	NaN undefined
Uttilizzo memoria del nodo: esterna	NaN undefined

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Backup

Newest WeKan does not yet have all loading speed issues fixed. Fixing speed issues is In Progress, and will appear in some later WeKan version.

**Comment by xet7** [comment]
Related #4061
