### ISSUE TITLE
Feature Request: Android tablet, Enable drag handles automatically (was: At All Boards page, can not click existing board icon to open board)

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4569]
- Samsung Galaxy Tab A8 4G, 3 GB RAM
- Chrome
- Android 11

At All Boards page, can not click existing board icon to open board. This is when using desktop mode of WeKan on Android tablet. Desktop mode is visible when display is bigger that smartphone display.

**Comment by xet7** [comment]
Solution was to enable drag handles. But, if possible, for Android etc those should be enabled automatically.

**Comment by repmovs** [comment]
should be repaired after I've changed some calls of isMiniScreen to isTouchScreen

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4633
