### ISSUE TITLE
Need help for install wekanv6.28 from scratch 

### ISSUE THREAD

**Issue by sdenu9564** [wekan/wekan#4584]
I tried to install wekan v6.28. But lots of errors i faced installing it. Please guide me for install it. Thank you

**Comment by sdenu9564** [comment]
Hello, I have used wekan for the last 3 months and I wanted to update the wekan to v6.28. But I got errors whenever I want to run it.
I Update the meteor and rebuild wekan.sh. After successfully rebuild no main.js file is created.
Whenever i do start-wekan.sh it says 
./start-wekan.sh: line 5: cd: .build/bundle: No such file or directory
internal/modules/cjs/loader.js:905
  throw err;
  ^
Error: Cannot find module '/home/sdenu9564/wekan/wekan-6.28/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
I am using ubuntu 20.04 in wsl.
Please help me. Thank you in advance.

**Comment by xet7** [comment]
1. Backup https://github.com/wekan/wekan/wiki/Backup
2. Use docker-compose.yml from https://github.com/wekan/wekan
3. Restore https://github.com/wekan/wekan/wiki/Backup
