### ISSUE TITLE
Upgrading docker container to 6.29 fails

### ISSUE THREAD

**Issue by dragondagda** [wekan/wekan#4585]
## Issue
I tried upgrading my wekan docker container to 6.29 but sadly the container fails.

### Server Setup Information
* Operating System: Ubuntu 20.04.4 LTS
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker (20.10.3)
* MongoDB Version: 4.4.14

### Problem description
When upgrading docker image from 6.28 to 6.29 the wekan container crashes with the following log error. 

#### Logs
```
wekan-app  | node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
wekan-app  |  1: 0xa3ac10 node::Abort() [node]
wekan-app  |  2: 0xa3ac8e  [node]
wekan-app  |  3: 0xaab44e  [node]
wekan-app  |  4: 0xaab516 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node]
wekan-app  |  5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node]
wekan-app  |  6: 0xa03831 node::Start(int, char**) [node]
wekan-app  |  7: 0x7f55fe5c2d90  [/lib/x86_64-linux-gnu/libc.so.6]
wekan-app  |  8: 0x7f55fe5c2e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
wekan-app  |  9: 0x98c58c  [node]
```

**Comment by Pax90** [comment]
Identical error in our instance.

**Comment by kovacs-andras** [comment]
Same issue here. :(

**Comment by xet7** [comment]
WeKan is only compatible with MongoDB 5, versions are listed at https://wekan.github.io Download section.

1. Please [Backup](https://github.com/wekan/wekan/wiki/Backup) your previous install with mongodump, using your current version of MongoDB.

2. Delete all docker containers and data with:
```
git clone https://github.com/wekan/docker-cleanup-volumes
cd docker-cleanup-volumes
```
3. Add ROOT_URL etc settings to newest docker-compose.yml from https://github.com/wekan/wekan

4. `docker-compose up -d`

**Comment by xet7** [comment]
@m-brangeon 

What at what hosting provider or datacenter your server is? Maybe they have restricted kernel settings.

**Comment by m-brangeon** [comment]
> @m-brangeon
> 
> At what hosting provider or datacenter your server is? Maybe they have restricted kernel settings.

On my own centos7 server. I pasted the workaround in the other issue the one I created first, maybe you could have a closer look at it ? 
(I would do it myself, but I dont now nodejs at all). It  did the trick so start the app:
```
    security_opt:
      - seccomp:unconfined
```

**Comment by xet7** [comment]
Oh, centos 7 ? Hmm, I'll test with it.

**Comment by m-brangeon** [comment]
It something with docker and the libc6 and node. Maybe introduce by this new ubuntu switch for container image.
Not sure it's safe to keep that security option off forever. I just found it as a temporary fix, 
Anyway thanks for what you do !

**Comment by xet7** [comment]
Hmm, I don't know is this related to selinux? https://github.com/wekan/wekan/issues/2792#issuecomment-630222315

**Comment by m-brangeon** [comment]
> 

nope I dont have selinux. It's something with the libc6 inside the container

**Comment by BabyFnord** [comment]
> […] WeKan is only compatible with MongoDB 5 […]

@xet7 Thank you, I wasn't aware of that. Uberspace allows for easy switching over from 4.4.13 to 5.x … would I risk breaking something by simply doing so?

**Comment by xet7** [comment]
@BabyFnord 

Take [Backup](https://github.com/wekan/wekan/wiki/Backup) with mongodump first, then try that easy switching.

**Comment by xet7** [comment]
@BabyFnord 

Node.js version is 14.20.0 , versions listed at https://wekan.github.io Download section.

Did you set WRITEABLE_PATH to somewhere so that attachments can be added or migrated?
https://github.com/wekan/wekan/blob/master/start-wekan.sh#L13

**Comment by BabyFnord** [comment]
WRITEABLE_PATH is set. Attachments worked with WeKan v6.28. Is Node.js v14.19.3 a problem in regard to this?

**Comment by xet7** [comment]
@BabyFnord 

It seems same error is at all WeKan versions, like Bundle/Source/Docker etc. That `replace` function/method does not exist or work anymore. I don't know yet is it because of new version of:
- `ostrio:files`
- mongodb
- something else?

https://github.com/wekan/wekan/blob/v6.29/models/attachments.js#L26

@mfilser What do you think ?

**Comment by xet7** [comment]
It looks like attachments can not be uploaded in this newest WeKan 6.29

**Comment by xet7** [comment]
I'm currently building new WeKan release 6.30, it has fix for uploading attachments.

**Comment by xet7** [comment]
@BabyFnord 

Please try WeKan 6.30 . Thanks!

**Comment by BabyFnord** [comment]
Confirmed working, @xet7 🥳 Thank you so much!
