### ISSUE TITLE
Wekan 6.30 Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

### ISSUE THREAD

**Issue by joyinfo** [wekan/wekan#4590]
twbs:bootstrap@3.3.6 is not compatible with jQuery 1.7.4 and gives an error below:

Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

<img width="1284" alt="Screen Shot 2022-07-14 at 14 49 53" src="https://user-images.githubusercontent.com/20535391/178919498-0e8a0092-62ae-46fe-be07-c85de01dec94.png">

**Comment by joyinfo** [comment]
I fixed it by changing 
`"jQuery": "^1.7.4",`
to
`"jquery": "^2.2.4",`

**Comment by xet7** [comment]
Try WeKan v6.31
