### ISSUE TITLE
Login Page Error, Lists can't move anymore Uncaught TypeError: l._id.width is not a function

### ISSUE THREAD

**Issue by johnnytolengo** [wekan/wekan#4592]
Using Docker version latest v6.30, when I move a list I got this JS errors. I had to move back to wekan:v6.28 to make it work again.

Uncaught TypeError: l._id.width is not a function

![image](https://user-images.githubusercontent.com/5218298/178921422-cf6ce0ce-a36d-4fd5-8011-631c62cb58a0.png)

After login page loads I got this error:
![image](https://user-images.githubusercontent.com/5218298/178921723-0c8edab1-2521-422b-874d-2c9c378d6c50.png)

**Comment by gda140** [comment]
I have the same issue, impossible to move list, wekan 6.30

**Comment by xet7** [comment]
Hmm? I'll check.
