### ISSUE TITLE
Wekan Snap services running but unable to access via Browser 

### ISSUE THREAD

**Issue by narrapavanreddy** [wekan/wekan#4594]
Hi,

from yesterday, unable to access wekan all the services are running but unable to access 
@xet7 please help to fix the issue
Thanks

**Comment by xet7** [comment]
@narrapavanreddy 

Do you mean your self-installed WeKan server?

What WeKan version are you running?

What WeKan platform, like Snap/Docker/Bundle/Source/UCS ?

Or do you mean my WeKan services, like https://boards.wekan.team/sign-in, Android Play Store Wekan app, MS Windows Store app, Ubuntu Touch OpenStore app?

**Comment by narrapavanreddy** [comment]
@xet7 thanks for the reply

We are you self hosted snap platform all the services are showing active and running when in trying to find the port 80 it is not showing in active ports and unable to browse in any web browser

Thanks

**Comment by xet7** [comment]
@narrapavanreddy 

What does this command show?

sudo snap list

**Comment by narrapavanreddy** [comment]
@xet7 please find the attachments
![Uploading Image Pasted at 2022-7-14 17-13--1276675800.png…]()

**Comment by narrapavanreddy** [comment]
![Image Pasted at 2022-7-14 17-13--1155590802](https://user-images.githubusercontent.com/14920325/179033612-ca437537-a765-4b39-8c11-19fd86df058c.png)

**Comment by xet7** [comment]
@narrapavanreddy 

Those do not show what channel you are using, like stable/candidate/beta/edge , see  
https://github.com/wekan/wekan/issues/4505#issuecomment-1158380746

Please attach screenshots directly to github commend, so images will be visible. Do not use any 3rd party image hosting service.

**Comment by narrapavanreddy** [comment]
@xet7 here is the sudo snap list

![image](https://user-images.githubusercontent.com/14920325/179141224-f42325f6-a453-45f8-9788-f39e604514af.png)

**Comment by narrapavanreddy** [comment]
@xet7 please help us to fix the issue

**Comment by xet7** [comment]
@narrapavanreddy 

What does these command show?
```
sudo snap logs wekan.wekan

sudo snap logs wekan.mongodb
```
And what does this show? Please anonymize domain names, passwords etc:
```
sudo snap get wekan
```

**Comment by narrapavanreddy** [comment]
@xet7  here is the logs screenshot 
![IMG_20220715_205625](https://user-images.githubusercontent.com/14920325/179255894-8d701b98-7359-4867-be76-de3b1af1010b.jpg)
![IMG_20220715_205721](https://user-images.githubusercontent.com/14920325/179255923-ffa9f9e2-722b-49d6-ae6a-6c946dbb353c.jpg)
![IMG_20220715_205757](https://user-images.githubusercontent.com/14920325/179255950-2f17eef2-6204-4c7a-b410-025043f1a8d2.jpg)

**Comment by narrapavanreddy** [comment]
@xet7 all of the sudden the server went down unable to access it from last two days

**Comment by xet7** [comment]
@narrapavanreddy 

Try:
```
sudo snap stop wekan

sudo snap start wekan
```

**Comment by narrapavanreddy** [comment]
@xet7 no luck tried all methods restarting the server also not working

**Comment by xet7** [comment]
@narrapavanreddy 

Does making backup and upgrading to newer WeKan candidate version work?

https://github.com/wekan/wekan/issues/4505#issuecomment-1158380746

**Comment by narrapavanreddy** [comment]
@xet7 we have a backup , what i observed Is I'm unable to find the active web port which is 80

**Comment by xet7** [comment]
@narrapavanreddy 

Check server still has same IP address of 192.168.1.3:
```
ip address
```
Then try:
```
sudo snap set wekan caddy-enabled='false'

sudo snap set wekan port='80'

sudo snap set wekan root-url='http://192.168.1.3'

sudo snap start wekan
```

**Comment by narrapavanreddy** [comment]
![Uploading IMG_20220715_212222.jpg…]()

**Comment by xet7** [comment]
@narrapavanreddy 

Check what is running at port 80:
```
sudo apt install net-tools

sudo netstat -plant | grep :80

sudo netstat -plant | grep mongo

sudo netstat -plant | grep node
```

**Comment by narrapavanreddy** [comment]
![IMG_20220715_212222](https://user-images.githubusercontent.com/14920325/179260808-1cd9d819-fecb-4df7-9d13-b7de8fb8153e.jpg)

**Comment by narrapavanreddy** [comment]
@xet7 

sudo netstat -plant | grep :80 showing nothing

**Comment by xet7** [comment]
@narrapavanreddy 

Try that upgrade https://github.com/wekan/wekan/issues/4505#issuecomment-1158380746

**Comment by narrapavanreddy** [comment]
@xet7  thanks let me try to upgrade, is there any minimum storage requirements, now only 100GB free space left in the server

**Comment by narrapavanreddy** [comment]
@xet7 at present my snap storage size is 400 GB

**Comment by xet7** [comment]
@narrapavanreddy 

How big is your WeKan database with this command?
```
sudo du -sh /var/snap/wekan/common
```

**Comment by xet7** [comment]
You would need enough disk space, because if MongoDB is running and server gets out of disk space, MongoDB gets corrupted.

**Comment by xet7** [comment]
Hmm, actually this makes me worried about upgrading Snap MongoDB version automatically, because if some WeKan users don't have enough free disk space, they may lose data.

**Comment by xet7** [comment]
I think I would need to find a way to run WeKan with current old version of MongoDB, without upgrading.

**Comment by narrapavanreddy** [comment]
@xet7 how to fix the issues without upgrading

**Comment by narrapavanreddy** [comment]
@xet7 my db size is 412GB

**Comment by xet7** [comment]
@narrapavanreddy 

What size is your backup, that you made with mongodump ?

**Comment by narrapavanreddy** [comment]
@xet7  the back-up size is 442GB

**Comment by xet7** [comment]
@narrapavanreddy 

You can try this. It reinstalls wekan, while still keeping all same database files etc.

```
sudo su

snap stop wekan

mv /var/snap/wekan/common /

snap remove wekan

snap install wekan

snap set wekan caddy-enabled='false'

snap set wekan port='80'

snap set wekan root-url='http://192.168.1.3'

snap stop wekan

rm -rf /var/snap/wekan/common

mv /common /var/snap/wekan/

snap start wekan
```

**Comment by narrapavanreddy** [comment]
@xet7 If i do above procedure my old db will be safe.right

**Comment by narrapavanreddy** [comment]
@xet7 thanks for your support let me try

**Comment by narrapavanreddy** [comment]
@xet7 for reinstall is 100GB storage is enough??

**Comment by narrapavanreddy** [comment]
@xet7 can I copy the back-up folder into other systems is that works?

**Comment by xet7** [comment]
@narrapavanreddy 

It would be much better for you to install WeKan to different server that has a lot more free disk space, and restore backup there.

**Comment by narrapavanreddy** [comment]
@xet7 tried the above procedure in backup server the fresh installation is working fine and after restoring the old common folder the same issue is repeating, im unable to find the process of port 80 in the process monitor.
![Screenshot from 2022-07-16 09-11-11](https://user-images.githubusercontent.com/14920325/179337823-1027f875-6fad-4b16-b0be-704ace463f87.png)

**Comment by xet7** [comment]
Usually backup is restored with mongorestore. Not by copying back common folder.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Backup

**Comment by narrapavanreddy** [comment]
> Usually backup is restored with mongorestore. Not by copying back common folder.

@xet7 the backup was restored with mongoretore only and i have tried in my liv server also not working

**Comment by narrapavanreddy** [comment]
@xet7 after restoring the old db I'm unable to find the port 80 process

**Comment by xet7** [comment]
@narrapavanreddy 

You could change Snap to Docker with docker-compose.yml from https://github.com/wekan/wekan

**Comment by xet7** [comment]
And restore database to Docker like at https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
But I just get a feeling that you should have paid Commercial Support from https://wekan.team/commercial-support/ because you seem to need so much help.

**Comment by narrapavanreddy** [comment]
@xet7 at present I would  to go with 100EUR plan @xet7  please let me know how will you connect and what is the approx hours for 100 EUR's

Thanks

**Comment by xet7** [comment]
@narrapavanreddy 

Please email support@wekan.team

**Comment by xet7** [comment]
Today I did upgrade this Snap to newest WeKan candidate, and delete incomplete upload like this https://github.com/wekan/wekan/issues/1298#issuecomment-1189422125 , so then WeKan started.

There are still some other issues what does not work yet in newest WeKan, but main point is that WeKan is now accessible via browser, and it's using newest WeKan candidate.
