### ISSUE TITLE
Wekan 6.30 - API login creates error 500

### ISSUE THREAD

**Issue by skye0402** [wekan/wekan#4595]
### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Docker image from quay.io
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Istio
* Node.js Version: 14.20.0
* MongoDB Version: 4.4.12
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Chrome

#### Reproduction Steps
I used a perfectly working login script to Wekan and from version 6.18 (where it worked) to version 6.30 it stopped working. Server error 500 - Internal server error.
`{
    "error": "internal-server-error",
    "reason": "Internal server error"
}`
Login to web frontend works fine with same credentials.
Call url: 'https://\<wekanserver\>/users/login'

#### Logs

No specific logs in the console of the running docker image.

**Comment by skye0402** [comment]
Update: Upgraded MongoDB to 5.0.9 (fresh installation) and played in a backup from 6.18 with the same results. Reverting now to 6.18

**Comment by shivadasv** [comment]
It seems that if there any open resume tokens (Mongo collection - users, under services-resume), those would not work with the new bcrypt. So I deleted the existing tokens for the user and the error went away for me. Hope this helps.

**Comment by skye0402** [comment]
It's likely #4528 - Your suggestion didn't help. I even created a new user with Admin rights to no avail. That's bad, I need to stay with my current WeKan version then.

**Comment by Limezy** [comment]
OK... Now I understand why the n8n wekan node doesn't work !

**Comment by shivadasv** [comment]
> Reference
Interesting !! Only difference is I also have LDAP users too along with Password Users.

**Comment by shivadasv** [comment]
> It's likely #4528 - Your suggestion didn't help. I even created a new user with Admin rights to no avail. That's bad, I need to stay with my current WeKan version then.

Interesting !! Only difference is I also have LDAP users too along with Password Users.

**Comment by Limezy** [comment]
Same here, I had to downgrade !

**Comment by xet7** [comment]
Note to myself: Maybe this could have some related API code?

https://docs.meteor.com/api/http.html

**Comment by raul-mg** [comment]
> 

Seems it happens too with a clean mongo installation, soo I bet to old tokens are not the cause for this error, also I catch this error on signup new user: 
`Exception while invoking method 'ATCreateUserServer' Error: connect ECONNREFUSED 127.0.0.1:587
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
`

**Comment by DimDz** [comment]
Using Postman I seem to send API requests successfully with no errors. Sending API requests inside wekan code also works.

**Comment by xet7** [comment]
@DimDz 

What WeKan version?

**Comment by DimDz** [comment]
Latest

**Comment by Limezy** [comment]
After an upgrade to 6.44, the API still doesn't work for me 😢

**Comment by DimDz** [comment]
> 
tested again on a new cloned repo, v6.44 using Postman.
![Screenshot_1](https://user-images.githubusercontent.com/70445835/189113984-e541ac76-36f7-4091-a43b-36de64f2cd63.png)

**Comment by Limezy** [comment]
By replacing the line
`apikey = d['token']`
With 
`apikey = "_hmvJpLXvngCGCrM-0fKIzgK6aZUHht5s0tISEHA8vp"`
__hmvJpLXvngCGCrM-0fKIzgK6aZUHht5s0tISEHA8vp_ being a value I've found in developper tools under local storage, it works... So the problem seem to be related with the first step to retrieve that token

**Comment by DimDz** [comment]
line 165: `body = requests.post(wekanloginurl, data=data)`
to `body = requests.post(wekanloginurl, json=data)`
seems to gets token

**Comment by Limezy** [comment]
@DimDz I confirm that changing that line (137 in my case) works
So, how could the API be repaired... ? (I need to connect my wekan instance with n8n and would like to upgrade!)

**Comment by xet7** [comment]
@Limezy 

I think, that it means, that WeKan API has been working in newest WeKan for a long time. There is no bug in WeKan server.

Bug is in that client api.py code, how to call that API correctly, in that one line.

**Comment by Limezy** [comment]
I see... Has there been any API login change from  v5.93 and v6.44 ?
The n8n wekan node is perfectly working with an instance running v5.93, but failing with all 6.xx I could try
If yes, I'll file a node update issue in n8n repo
Thanks !

**Comment by xet7** [comment]
@Limezy 

Newest WeKan works with versions listed at https://wekan.github.io Download section.

Anyway, before upgrade, please make [Backup](https://github.com/wekan/wekan/wiki/Backup).

**Comment by DimDz** [comment]
Latest working API with n8n was with v6.22, before meteor update to 2.7.3

**Comment by Limezy** [comment]
> Latest working API with n8n was with v6.22, before meteor update to 2.7.3 if that helps.

So... Do you agree that the issue seems to be on Wekan side, rather than on n8n node side ?

**Comment by Limezy** [comment]
I can't find any difference between
https://wekan.github.io/api/v6.18/#wekan-rest-api-login
and
https://wekan.github.io/api/v6.44/#wekan-rest-api-login

**Comment by DimDz** [comment]
I created an issue on n8n github, [4086](https://github.com/n8n-io/n8n/issues/4086)

**Comment by Joffcom** [comment]
Morning,

I have been looking into the reported n8n issue and when I send the data from Postman to 6.44 using the documented content type of `application/x-www-form-urlencoded` I am getting an internal server error message back.

It looks like this is no longer the correct content type and instead it should be `application/json`, I will get our node fixed later today.

**Comment by Limezy** [comment]
@Joffcom, thank you so much for spotting this out !

**Comment by Joffcom** [comment]
Update for anyone following along, I have put in a PR to fix this on our side (n8n) 👍🏻

**Comment by DimDz** [comment]
On that PR @Joffcom mentioned, I tested it using latest clean wekan and also my working dev wekan, everything works as intented

**Comment by skye0402** [comment]
Confirm this works! Super!
