### ISSUE TITLE
Feature to freeze layout

### ISSUE THREAD

**Issue by Tuphal** [wekan/wekan#4597]
Is there a possibility to lock the layout?

The swimlanes and lists are fixed and should not be moved anymore by accident. 
Also there is currently no need to add more lists or swimlanes or to rename the existing ones.

With such a "Freeze layout" option we get a sleek design.

![grafik](https://user-images.githubusercontent.com/42291781/179462635-6e60fa00-457d-45e7-9b00-1d9066f23979.png)

![grafik](https://user-images.githubusercontent.com/42291781/179462805-1f4b3c38-e0b6-40b1-b7a1-1246c168ef53.png)

**Comment by xet7** [comment]
In newest WeKan layout is freezed.
