### ISSUE TITLE
Regression: Cannot rearrange lists

### ISSUE THREAD

**Issue by 0x326** [wekan/wekan#4612]
### Server Setup Information

* Did you test in newest Wekan?: Yes (v6.30)
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Ubuntu 20.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker 
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Caddy
* Node.js Version: v14.20.0
* MongoDB Version: 4.4
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Desktop Chrome and iOS Safari

#### Reproduction Steps

Go to any board and try to drag-and-drop a list to a new position. The list moves while being dragged, but it jumps to its original position upon release (followed by a run-time exception in the client -- `TypeError: l._id.width is not a function`).

#### Logs

Client-side logs:
![image](https://user-images.githubusercontent.com/20781397/181973918-e94f4bf9-3dad-4de3-bd95-133653d318aa.png)

Server logs:
```
➜  ~ docker logs -f home-server_wekan_1
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Sat Jul 30 2022 13:55:16 GMT-0400 (Eastern Daylight Time)","time":{"$date":1659203716935},"level":"info"}
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

```

**Comment by xet7** [comment]
Try WeKan v6.31
