### ISSUE TITLE
In Lists view, Card Details pop-up does not appear in 6.31 release

### ISSUE THREAD

**Issue by Sdub76** [wekan/wekan#4616]
## Issue
Card details pop-up does not appear in 6.31 release

### Server Setup Information
* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly: Yes
* Operating System: Unraid
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik
* Node.js Version: 14.20.0
* MongoDB Version: 5.0.9
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Microsoft Edge

### Problem description
After upgrading to 6.31, clicking on a card does not bring up the details pane.  The card is selected, but nothing happens.  Repeated on multiple computers, including incognito mode.  Reverting to 6.30 resolved the issued.

#### Reproduction Steps
Click on any card on an existing board after upgrading to 6.31

#### Logs
I can upgrade to 6.31 again and capture logs if necessary, but I'm away from the server right now.  Just wanted to get this up in case others are seeing the same issue.

**Comment by xet7** [comment]
@Sdub76

For me, using Docker WeKan v6.31, card details does open on Win11 using newest browsers like MS Chromium Edge, Chrome and Firefox.

Did you setup ROOT_URL etc?

## Port 2000

ROOT_URL=http://192.168.0.100:2000

PORT=2000

## Port 80

ROOT_URL=http://192.168.0.100

PORT=80

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Settings

**Comment by Sdub76** [comment]
Yes this setting was correct. And why would it stop working on 6.31?

**Comment by xet7** [comment]
What Windows version?

What Edge version?

**Comment by xet7** [comment]
Any browser version can have some new bug, that causes that something in WeKan does not work. It has happened many times before. Usually solution is to update to newest browser version.

**Comment by xet7** [comment]
Does card details open in Chrome or Firefox?

**Comment by xet7** [comment]
Some browser bugs can be fixed with some code changes, if someone figures out how to fix it.

For example:

- Chrome bug #1404 
- Firefox bug #2280

**Comment by xet7** [comment]
I really hope Chrome does not remove alert(), that would break huge amount of webpages.

https://www.theregister.com/2021/08/05/google_chrome_iframe/

**Comment by niels** [comment]
We are seeing the same issue both with the latest Firefox and Chromium versions.

We can work around the issue by switching the "Board View" mode from "Lists" to "Swimlanes":

![2022-08-02_11-01](https://user-images.githubusercontent.com/16709/182336253-0e83d094-593a-41b3-aa8a-8aa8f1123304.png)

I did some initial troubleshooting and noticed that the swimlane and list views call `currentCardIsInThisList` (wich determine whether or not to show `cardDetails`) differently ([swimlane](https://github.com/wekan/wekan/blob/aeb29a4f95cd8378aa2d79c34f8987199303d113/client/components/swimlanes/swimlanes.jade#L19-L20) vs [list](https://github.com/wekan/wekan/blob/aeb29a4f95cd8378aa2d79c34f8987199303d113/client/components/swimlanes/swimlanes.jade#L40-L41)) but couldn't find any related changes introduced in v6.31.

**Comment by mfilser** [comment]
Maybe it's related to this?
https://github.com/wekan/wekan/pull/4610

Just an idea, i didn't test it yet.

**Comment by medjedovicm** [comment]
We have the same issue and I am also confirming that changing to "swimlanes" is a working workaround.

**Comment by xet7** [comment]
Hmm, it seems that it needs adding code to check, is it in Swimlane view or List view. I'll try.
