### ISSUE TITLE
Dockerfile: Consider breaking up variables with `ENV` and `ARG`

### ISSUE THREAD

**Issue by 0x326** [wekan/wekan#4617]
## Issue

In order to make the Wekan Docker image more self-documenting, would it be possible to mark the environment variables used during run-time with `ENV` Dockerfile statements and switch build-time environments variables (such as `BUILD_DEPS`) to `ARG` Dockerfile statement?  Thanks!

**Comment by xet7** [comment]
@0x326 

Huh? I don't know what you mean. If you think it would not break anything, you can submit pull request.

There are many comments at https://github.com/wekan/wekan/blob/master/docker-compose.yml
