### ISSUE TITLE
Drafted input data within a card's Description box does not cache at all, clicking off the card erases all your work.

### ISSUE THREAD

**Issue by ManZosh** [wekan/wekan#4619]
## Issue
When adding a card description, the input data does not cache to the card when clicking off the card (either intentionally to check another card's content or accidentally, maybe by Window focusing back onto the site from a prior application) and as a result all typed text and formatting is permanently lost.

### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Ubuntu Server v20.04.4 (server) Windows 10 (client)
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 12.22.10
* MongoDB Version: 3.2.22
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox 88

### Problem description
Add description text, click off the card you're working on without saving, and then click back into the card, only to find that by doing this all of the description you were working on is now gone. I've used plenty of other software where unfinished/drafted input data is cached when you revisit it at a later time within the application. I'm surprised WeKan doesn't yet support this!
![WeKan_CardCaching](https://user-images.githubusercontent.com/28317348/182894996-db6be249-91da-4db5-b14e-2dde7eac0177.gif)

We use WeKan in production for running a whole IT department and assigning projects. Many times now I've spent sometimes 30 - 60 minutes researching an issue/technology/protocol/application, carefully articulating my words, dialing in the proper formatting, just to accidentally click off the card and LOSE all of that work. It's incredibly frustrating, especially considering the desired draft caching functionality exists and is established on other apps out there. Sure, maybe the user should save more often... But with how easy it is to click-off the card, maybe some caching feature like this should be incorporated.
#### Reproduction Steps

**Comment by helioguardabaxo** [comment]
Hi, @ManZosh 
Do you using 6.31 version?
This version have a new feature to alert when you close card that has unsaved changes on description.
https://github.com/wekan/wekan/pull/4598

**Comment by ManZosh** [comment]
Ohh nice, is that version live on Snap?
![snap_wekan](https://user-images.githubusercontent.com/28317348/183490206-5d12878a-e226-4659-8171-90f55da66121.png)
?

**Comment by xet7** [comment]
@ManZosh 

Not at Snap Stable.

It's at Snap Candidate https://github.com/wekan/wekan/issues/4505#issuecomment-1158380746

There's still stuff to figure out before Candidate can be promoted to Stable https://github.com/wekan/wekan/issues/4423#issuecomment-1203192017

**Comment by ManZosh** [comment]
Hi, I just typed up over an hour's worth of summarizing documentation on a big project card, had an end-user come to my desk for a question, and ended up accidentally clicking off the card and lost all the thoughts I extrapolated on, text formatting and everything...

I see Snap still only supports WeKan Stable v6.09 from back in March. Just curious roughly when the next stable release will be rolled out to Snap packman users?
