### ISSUE TITLE
Restrict actions only to members associated with the card.

### ISSUE THREAD

**Issue by lrmirabelli** [wekan/wekan#4620]
## Issue
Hello!

I'm a new user of the WeKan solution and I'm really enjoying using it.

I would like to know **how can I restrict the movement of cards by its members**, so that only users assigned to the card (apart from the admin) can move or edit it?

Is there any way to create a rule or configuration option to implement this?

Thank you for your attention.

Luis.

### Server Setup Information

* Did you test in newest Wekan?:
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

**Comment by xet7** [comment]
@lrmirabelli

At right sidebar, click user avatar and change to some other role:
https://github.com/wekan/wekan/wiki/REST-API-Role

Assigned users to worker:
https://github.com/wekan/wekan/issues/2788

Others to for example Comment Only

Normal users can not move card to other board, or delete attachments:
https://github.com/wekan/wekan/issues/3377
