### ISSUE TITLE
[Bug] Avatar Image broken for v6.10 and onwards [Docker Engine] [Linux]

### ISSUE THREAD

**Issue by Neko-Box-Coder** [wekan/wekan#4629]
### Server Setup Information
* Did you test in newest Wekan?: 
  * Yes, and for versions v6.10+. This doesn't affect v6.09.
* Operating System: 
  * 5.18.14-arch1-1
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): 
  * Docker Engine (Docker, Containerd and Docker-compose)
* Node.js Version: 
  * Using docker, 14.19.0 for v6.10.
* MongoDB Version: 
  * Not relevant. Tested from v4.4 to 5.
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? 
  * Firefox and Chrome.

### Problem description
Custom avatar image is shown as broken after uploading, doesn't matter what types of image.
As far as I tested, this only affects new installations and not instances that are updated from older versions.

![image](https://user-images.githubusercontent.com/93885501/183469772-7d05b110-6f5a-40a6-8d55-46e09f5a2e36.png)

This could be a Linux only or Arch only issue, in theory it shouldn't but I can't tell.

#### Reproduction Steps
Create a new directory, make sure volumes/bind mounts are not using any existing ones.
Do `sudo docker-compose down -d`
Create account and upload any image as avatar. 

#### Logs
Didn't output any related logs as far as I can tell.

**Comment by derbolle** [comment]
I have one user who told me about this or a similar Problem with broken Avatars as well. He worked around it by using a very small(well below 80kb) jpg file. I have not investigated further but I hope this information is helpful

**Comment by Neko-Box-Coder** [comment]
Yeah, thanks. I have tried with images below 80 kb and it didn't work. For now, I am sticking with v6.09 since I want to have working avatar.

I am not sure if it is just me but it isn't even working on the [demo board](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-r-open-source-kanban-board-with-mit-license) if you click into one of the cards.

**Comment by xet7** [comment]
Try WeKan v6.26

**Comment by xet7** [comment]
Hmm, it seems that avatar URL has changed somewhere in the code. Trying to figure it out.

Related https://github.com/veliovgroup/Meteor-Files/issues/847

**Comment by mfilser** [comment]
@xet7 
I will have a look at it (namingFunction)

**Comment by xet7** [comment]
@mfilser 

Currently in newest wekan Meteor-Files is newest version, but images etc are not visible at board at all, attachment URLs are wrong somewhere, or they would need full URL in every attachment.

**Comment by mfilser** [comment]
@xet7
I will have a look at the latest commit and do the changes so uploading works again

**Comment by xet7** [comment]
I would like to keep using newest Meteor-Files and it's latest fixes, and still have working:
- uploading attachments
- having attachments/images etc visible at cards
- have avatars visible at cards

**Comment by xet7** [comment]
@mfilser 

Meteor-Files has new breaking changes to that namingFunction:

https://github.com/veliovgroup/Meteor-Files/releases
