### ISSUE TITLE
All Boards: The list of "lists" on each card with the summary counts is not sorted

### ISSUE THREAD

**Issue by ViViDboarder** [wekan/wekan#4634]
### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: MacOS
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Cloudron
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Cloudron (Nginx I think)
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox

### Problem description

On the All Boards view, the mini view showing a summary of lists and items in each list is not sorted. The order appears to be fairly arbitrary (maybe based on creation date?)

For example, I see:

![image](https://user-images.githubusercontent.com/137025/184427314-a3c5d3c9-fa78-4482-b87d-514d6cf56e6a.png)

When in the board my lists are ordered `Topics, Draft, Published`:

![image](https://user-images.githubusercontent.com/137025/184427422-caeedca8-679e-4d99-be2a-cf7d326d4f36.png)

I imagine this is not so much a bug as an improvement.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4635
