### ISSUE TITLE
[Bug] Placeholder Text instead of translation if no board is starred.

### ISSUE THREAD

**Issue by meerkampdvv** [wekan/wekan#4636]
### Server Setup Information

* Did you test in newest Wekan?: 6.37.0
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Centos 
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): kubernetes Helm Chart
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node.js Version: 14.20.0 
* MongoDB Version:4.4.11
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? chromium 99.0.4844.84

### Problem description

if the User has no board starred the text "quick-access-description" appears but not the translation.

![image](https://user-images.githubusercontent.com/42608682/184813618-36be26ae-d37c-4986-93de-8044fc4080b7.png)

#### Reproduction Steps

do not star any board.

#### Logs

shouldn't be needed.

**Comment by zz707** [comment]
I use docker. The initial image was version 6.43 and labels was is ok. After pull new version the labels broke.

![image](https://user-images.githubusercontent.com/48176834/188484907-c422c289-3a60-44d5-ac4d-e1d7c4c3330b.png)
![image](https://user-images.githubusercontent.com/48176834/188484986-1b042475-c52d-4b67-857e-1761f6114813.png)

**Comment by xet7** [comment]
@zz707

Did you empty browser history and cache?

What webbrowser you use?

Does it work with different webbrowser?

**Comment by xet7** [comment]
What is webbrowsers version?

**Comment by zz707** [comment]
@xet7 I tried even incognito mode with the same result.
Chrome Version 105.0.5195.102 (Official Build) (64-bit)
Firefox 104.0.2
OS: Ubuntu 22.04

**Comment by xet7** [comment]
@zz707 

Is you wekan ROOT-URL:

a) subdomain like wekan.example.com

b) sub-url like example.com/wekan (there usually have problems)

c) with some port number like http://192.168.1.200:4000 ?

**Comment by xet7** [comment]
See https://github.com/wekan/wekan/wiki/Settings

**Comment by zz707** [comment]
Everything was working before the update.

**Comment by xet7** [comment]
@zz707 

Newest is WeKan ® v6.44, using Meteor 2.7.3, Node.js 14.20.0, MongoDB 5.x. It seems you are using MongoDB 4.x that is not compatible with newest WeKan. To upgrade, it needs mongodump/mongorestore like described at [Backup page](https://github.com/wekan/wekan/wiki/Backup.

**Comment by xet7** [comment]
Also, if upgrading does not work, you should go back to WeKan version that did work for you. There are still bugs that are not fixed yet in upgrade process.

**Comment by zz707** [comment]
I use docker-compose from this
https://github.com/wekan/wekan/issues/4566#issuecomment-1231940369
with mongo 5.0 from start.

**Comment by xet7** [comment]
@zz707 

To show some language in WeKan, like German, it needs to be set in Chromium settings as only language like here I have set Finnish:

![wekan-language](https://user-images.githubusercontent.com/15545/188499307-b8210945-d879-4936-b24e-5cd8b6d5a257.png)

**Comment by zz707** [comment]
This error occurrence even with english language, the same time i can not choose any other languages.

**Comment by xet7** [comment]
@zz707 

Is your Chromium settings locked down by some policy? Does changing Chromium settings and reloading WeKan webpage work?

**Comment by zz707** [comment]
@xet7 I'm sorry, this is my mistake. ROOT_URL was set to local network address. I was misled that before the update everything worked.
I apologize again for your time spent.
Everything works as it should.
