### ISSUE TITLE
node main.js Meteor._wrapAsync has been renamed to Meteor.wrapAsync

### ISSUE THREAD

**Issue by aswin5** [wekan/wekan#464]
I have been trying to localhost wekan. I have installed all the dependencies but when I reach the last step 
node main.js
I get this in my terminal :
Meteor._wrapAsync has been renamed to Meteor.wrapAsync

Its been for hours like this. No promt on the terminal cannot determine whether its still installing in background or a something else.

**Comment by mquandalle** [comment]
What installation recipe did you follow?

**Comment by aswin5** [comment]
I have been able to resolve it on my own. it was a installation problem. thank you.
