### ISSUE TITLE
Bad UX when entering a user email for invitation 

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#465]
As reported by @alayek on the [gitter chat](https://gitter.im/wekan/wekan) the current user experience when entering an email address to invite a new user is currently confusing. For one every time you press a character you have a giant spinner that appear and disappear during less than a second and then “No result” is displayed. If there is no result for `abc` it should be obvious that there isn't any result either for `abcdef` and so one optimization would be to not send this query to the server and wait for a response and just remember that there is no member that match this name.

We should also make more clear that it is possible to enter an email address to this field. Also if you click on the “Invite by email” without entering anything you get a confusing error “This user does not exist”. I imagine we could have a Regex checking for an email address and adapt the UI accordingly.

So there is room for improvement here, feel free to propose some ideas or what other applications do for inspiration.

**Comment by alayek** [comment]
+1

**Comment by xet7** [comment]
There is already checking for if user already exists.
