### ISSUE TITLE
Copy card popup menu allows you to create a card with a boardID of the current board but swimlaneId and listId from another board's swimlanes and lists

### ISSUE THREAD

**Issue by ChrisMagnuson** [wekan/wekan#4655]
I have been seeing an issue where when using copy card the Boards selection switches to current after copying a card while leaving the selection for Swimlanes and Lists as whatever those options were from the previously selected board.

If I change the Board drop down option the Swimlanes and Lists options update as expected but if I leave it set to current with a Swimlane and List selected that aren't on the board it creates a card that has the board id of the current board but a swimlane and listid from whatever the previously selected options were from the last time a card was copied to a different board.

I have tried things like running the following in Mongodb to reset the users's profile options:
```
db.users.updateOne({username:"usernamegoeshere"},{$set: {
    "profile.moveAndCopyDialog":{},
    "profile.moveChecklistDialog":{},
    "profile.copyChecklistDialog":{}
}})
```

but even after confirming the values are blank and then set correctly the issue still happens.

As an example when I run:

```
db.users.find({username:"cmagnuson"},{
    username:1,
    "profile.moveAndCopyDialog":1,
    "profile.moveChecklistDialog":1,
    "profile.copyChecklistDialog":1
}).pretty()
```

All the values make sense, the the board ID of the board your on is the key and the values for boardId, swimlaneId, and listId are all the values of the last place you copied or moved a card to from the boardId that is the key but when I click copy card, the board is set to current but the swimlane and listid's selected match what is in the moveAndCopyDialog object.

If there are other troubleshooting steps you would like me to take let me know, still looking through the code to see if I can identify what is happening.

**Comment by ChrisMagnuson** [comment]
I found that I could also see these values by looking at `Meteor.user().profile.moveAndCopyDialog` in the javascript console of the wekan page and then can inspect the elements which have the Ids so I can show more clearly what is happening:

![image](https://user-images.githubusercontent.com/2277702/186177638-56ee6b1f-c4ba-4b51-9521-ff5315fbbb7f.png)

Now if we look at the address bar I am on boardId `kBoHB8SAarxEYwDaq`:

![image](https://user-images.githubusercontent.com/2277702/186178034-9bbf3dae-8103-45d7-ade4-9d68fe067199.png)

Based on the values in `moveAndCopyDialog` when I am on the `kBoHB8SAarxEYwDaq` board the copy card dialog should have the `SMHx25NCvQqY7yH7c` boardId selected but we can see that the Id of the option selected is `kBoHB8SAarxEYwDaq`:

![image](https://user-images.githubusercontent.com/2277702/186179367-87bb442e-8279-4756-b0ac-f78ff3141455.png)

![image](https://user-images.githubusercontent.com/2277702/186179528-ae38a70c-a2f4-4b8c-91b8-5d0ade3ada25.png)

Looking at the values of swimlanes that can be selected we see the swimlanes for boardId `SMHx25NCvQqY7yH7c` with the swim lane selected that does match what we would expect from the swimlaneId value in `moveAndCopyDialog`:

![image](https://user-images.githubusercontent.com/2277702/186178880-c0f652a7-f4cd-428c-b647-5171e6b8a06c.png)

It seems like most of this is working just somehow the boardId is getting changed as the pop is being rendered as the Id is correct in `moveAndCopyDialog` but by the time the rendering process is done the board that is selected is not the one that should be based on `moveAndCopyDialog`.

**Comment by ChrisMagnuson** [comment]
@mfilser I hesitate to tag you so no worries if you don't have time to respond but I believe the issue I am seeing might be coming from a part of the code base you know well, any input would be appreciated, thank you!

**Comment by ChrisMagnuson** [comment]
I believe the pop up is being rendered using the [`dialogWithBoardSwimlaneList`](https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/lib/dialogWithBoardSwimlaneList.js#L1) blaze component and the [`onCreated()`](https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/lib/dialogWithBoardSwimlaneList.js#L27) method seems to call [`Utils.getCurrentBoardId()`](https://github.com/wekan/wekan/blob/8eb4ffea899cf12192a4fb4eee991546d83380fe/client/lib/utils.js#L5) to get the `boardId` used.

[`cardDetails`](https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/components/cards/cardDetails.js#L845) extends this component and then overides `getDialogOptions()` using the values from the profile.

The [`setOption()`](https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/lib/dialogWithBoardSwimlaneList.js#L38) function of the `dialogWithBoardSwimlaneList` blaze component seems to have the logic in it that decides which `boardId` to use as the selected option which may be where the problem is occurring.

**Comment by ChrisMagnuson** [comment]
The `cardDetails` jade template also has some logic in it in the [`copyAndMoveCard`](https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/components/cards/cardDetails.jade#L734) template for determining which board is the selected board that may be relevant.

**Comment by mfilser** [comment]
@ChrisMagnuson
Yes, you are right, that code is from me.
It's intention is to store the dialog values and restore them later again.

I will have a look at it.

**Comment by mfilser** [comment]
@ChrisMagnuson 
I tested it right now, copy card and move card.
After i confirmed the copy or move card dialog the field values are stored and if i copy/move a card again, the last field values are restored.
Furthermore, the field values are stored for each board (per board and not global).
If you still have issues with it, can you record it e.g. with [peek](https://github.com/phw/peek) ?

**Comment by mfilser** [comment]
If the copy/move dialog openes and there are invalid swimlane id and/or list id, the first swimlane id / list id is selected from database:
https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/lib/dialogWithBoardSwimlaneList.js#L55

**Comment by mfilser** [comment]
Also i don't set a boardId as card id, i only use copyCard from server. But maybe i am missing something... 

https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/components/cards/cardDetails.js#L860

**Comment by ChrisMagnuson** [comment]
![Animation](https://user-images.githubusercontent.com/2277702/186259370-8c50f058-8918-419b-9589-014b659f6dc8.gif)
Here is a recording of the issue occuring.

Something I didn't note properly before is that the Boards value being set to `current` regardless of the values of `moveAndCopyDialog` only occurs on some boards and not all.

There is another board for instance that the values properly update to whatever the last values that were used were and but on some boards the Boards: value on the pop up is always current with the swimlanes and lists being the values from the board that was in `moveAndCopyDialog` but isn't displayed in Boards:

**Comment by ChrisMagnuson** [comment]
@mfilser I believe that code is probably being excecuted and completing correctly as at the time it executes the `this.selectedBoardId.get()` must be giving back the correct boardId of the last board where a card from the current board was copied but sometime after it runs something else flips it to Boards: to current but does so in a way that doesn't trigger the event here:
https://github.com/wekan/wekan/blob/a9334b3bf4fab210f4dbb9b8b7c7c447d1cf013d/client/lib/dialogWithBoardSwimlaneList.js#L177

**Comment by mfilser** [comment]
Hm, hard to say what's going wrong. Also it just works on many boards for you, but not all (if i understood right).

I must get this error on my side to test and fix it.

**Comment by mfilser** [comment]
I think i have something found. I keep you posted

**Comment by mfilser** [comment]
@ChrisMagnuson 
Please have a look if it's fixed now.

**Comment by ChrisMagnuson** [comment]
@mfilser I tried to find a way to manually update my wekan instance with your jade template change but I am unfamiliar with how that build system works as simply changing the one file and restarting wekan didn't seem to pick up the change.

We use wekan hosted on Cloudron and now that it is merged in we will get the updated version in a day or so and then I can confirm this resolved it.

**Comment by ChrisMagnuson** [comment]
@mfilser That did the trick, now the board doesn't flip to current as it had in the past, thank you!

**Comment by mfilser** [comment]
@ChrisMagnuson
Great, thank you for the feedback

**Comment by ChrisMagnuson** [comment]
@mfilser I just bumped into another spot in the code that I believe needs to be updated in the same way to fix the same issue of the current board being incorrectly selected:

https://github.com/wekan/wekan/blob/c1d449d3bdc787e80d22a34cbafd27f8744fb37a/client/components/cards/checklists.jade#L142

I searched for everywhere in the code base that `if $eq _id currentBoard._id` showed up and found one other spot that may need to be updated but I am not familiar with using the board actions functionality to know for sure:

https://github.com/wekan/wekan/blob/c1d449d3bdc787e80d22a34cbafd27f8744fb37a/client/components/rules/actions/boardActions.jade#L28

**Comment by mfilser** [comment]
@ChrisMagnuson
Thanks, i will have a look at this

**Comment by mfilser** [comment]
@ChrisMagnuson 
I checked it, if i remove this code (as you mentioned)
https://github.com/wekan/wekan/blob/c1d449d3bdc787e80d22a34cbafd27f8744fb37a/client/components/cards/checklists.jade#L142

the board dialog option will not contain "current" and the "board name" instead. So i think there is no change needed.
And as i had a look at it, i saw another issue, the dialog is sometimes empty. I will send a PR soon about it.
