### ISSUE TITLE
分享链接以及仅查看模式

### ISSUE THREAD

**Issue by Avey777** [wekan/wekan#4658]
我们想使用wekan 公布我们的 roadmap  ，但是我们想让我们的客户仅查看和评论我们的Ideas

参考：https://roadmap.meilisearch.com/tabs/5-ideas

**Comment by xet7** [comment]
### 单击右侧边栏，用户头像，更改权限，仅评论。

#### 1) 

![perm3](https://user-images.githubusercontent.com/15545/186737881-c86209d6-24cb-416b-a8f3-caa05a67c6b1.png)

#### 2)

![perm4](https://user-images.githubusercontent.com/15545/186738012-78669b30-12d8-46a4-91e6-5f1b99af2fc7.png)

<hr>

### Click right sidebar, user avatar, change permission, comment only.

#### 1)

![perm1](https://user-images.githubusercontent.com/15545/186738154-ca03adbc-38a1-4096-960a-d5d67ab44fb5.png)

#### 2)

![perm2](https://user-images.githubusercontent.com/15545/186738225-e575c33a-bb4c-4f48-9c61-5b7b03c956be.png)
