### ISSUE TITLE
Unable to create/use template

### ISSUE THREAD

**Issue by brunushky** [wekan/wekan#4661]
Hi, I found this problem in the last time I use wekan, I did it in the past in old version I guest but I can't do it in the last version, I even try with the demo version and get the same result. 

* So first, I follow the instructions, but the first thing is I don't see the template icon anymore so I guess this new option "template container" is what I need.

![image](https://user-images.githubusercontent.com/2323149/186961453-cfaaca5a-3c3e-4f6a-a9f3-191b9e289c01.png)

* I add a list and a card to a board template , but I didn't found the "black folder" icon in the card, so that is my last step trying to create a template board

![image](https://user-images.githubusercontent.com/2323149/186962096-1ee72772-f7d1-492d-ba16-610257404baf.png)

* Finally I try to create a new board from template, but there are nothing in the list. 

![image](https://user-images.githubusercontent.com/2323149/186962649-5226eae4-ec39-4669-94b4-fa9c3fd1578a.png)

Maybe I'm missing something.

Thanks.

**Comment by xet7** [comment]
Shared Templates is not fixed yet #3313 

Yes there is funding for fixes, but currently there is work overload.

**Comment by xet7** [comment]
See https://github.com/wekan/wekan/wiki/Templates
