### ISSUE TITLE
Image build from Dockerfile fails

### ISSUE THREAD

**Issue by willman42** [wekan/wekan#4666]
## Issue
`docker build` fails when using the `Dockerfile` provided in v6.41 (not using v6.42 because the only difference is a [PR](https://github.com/wekan/wekan/pull/4663) I made that is actually going to be reversed, so no net difference between v6.41 and v6.42 Dockerfile files).

### Server Setup Information
* Operating System: Debian 11.4 amd64
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): caddy
* Node.js Version: n/a
* MongoDB Version: n/a

#### Logs
```
+ gosu wekan:wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build
=> Errors while initializing project:

While downloading cfs:reactive-list@0.0.9...:
error: ETIMEDOUT
```
...and a bunch of such timeouts on various other packages trying to be downloaded. Then ultimately the last error message is:

```
The command '/bin/sh -c set -o xtrace &&     useradd --user-group --system --home-dir /home/wekan wekan &&         apt-get update -y && apt-get install -y --no-install-recommends ${BUILD_DEPS} &&         cp $(which tar) $(which tar)~ &&     ln -sf $(which bsdtar) $(which tar) &&         wget https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     wget https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc &&         grep ${NODE_VERSION}-${ARCHITECTURE}.tar.gz SHASUMS256.txt.asc | shasum -a 256 -c - &&     rm -f SHASUMS256.txt.asc &&         tar xvzf node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     rm node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     mv node-${NODE_VERSION}-${ARCHITECTURE} /opt/nodejs &&     ln -s /opt/nodejs/bin/node /usr/bin/node &&     ln -s /opt/nodejs/bin/npm /usr/bin/npm &&     mkdir -p /opt/nodejs/lib/node_modules/fibers/.node-gyp /root/.node-gyp/${NODE_VERSION} /home/wekan/.config &&     chown wekan --recursive /home/wekan/.config &&             npm install -g npm@${NPM_VERSION} &&         cd /home/wekan/ &&     chown wekan --recursive /home/wekan &&     echo "Starting meteor ${METEOR_RELEASE} installation...   \n" &&     gosu wekan:wekan curl https://install.meteor.com/ | /bin/sh &&     mv /root/.meteor /home/wekan/ &&     chown wekan --recursive /home/wekan/.meteor &&         sed -i 's/api\.versionsFrom/\/\/api.versionsFrom/' /home/wekan/app/packages/meteor-useraccounts-core/package.js &&     cd /home/wekan/.meteor &&     gosu wekan:wekan /home/wekan/.meteor/meteor -- help;         cd /home/wekan/app &&     mkdir -p /home/wekan/.npm &&     chown wekan --recursive /home/wekan/.npm /home/wekan/.config /home/wekan/.meteor &&     chmod u+w *.json &&     gosu wekan:wekan npm install &&     gosu wekan:wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build &&     cd /home/wekan/app_build/bundle/programs/server/ &&     chmod u+w *.json &&     gosu wekan:wekan npm install &&     cd node_modules/fibers &&     node build.js &&     cd ../.. &&     rm -rf /home/wekan/app_build/bundle/programs/web.browser.legacy &&     mv /home/wekan/app_build/bundle /build &&         mv $(which tar)~ $(which tar) &&         apt-get remove --purge -y ${BUILD_DEPS} &&     apt-get autoremove -y &&     npm uninstall -g api2html &&    rm -R /tmp/* &&     rm -R /var/lib/apt/lists/* &&     rm -R /home/wekan/.meteor &&     rm -R /home/wekan/app &&     rm -R /home/wekan/app_build &&     mkdir /data &&     chown wekan --recursive /data' returned a non-zero code: 1
```

Checked my firewall and proxy logs, nothing seems to be blocking any outbound traffic fetching these packages.

**Comment by xet7** [comment]
Usually when building with Docker:

1. Add ROOT_URL etc settings to docker-compose.yml
2. Uncomment these lines https://github.com/wekan/wekan/blob/master/docker-compose.yml#L143-L145
3. In wekan repo directory, run command:

```
docker-compose up -d --build
```

**Comment by willman42** [comment]
If I understand correctly, running `docker-compose up -d --build` on a docker-compose.yml file with the `build:` argument in a service is simply a wrapper/convenience script for running `docker build .` in the directory containing the Dockerfile. So essentially they are the exact same thing, correct?

**Comment by willman42** [comment]
Either way, when running your instructions I get the following output:
```
[+] Building 0.3s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                              0.2s
 => => transferring dockerfile: 2B                                                                0.0s
 => [internal] load .dockerignore                                                                 0.2s
 => => transferring context: 2B                                                                   0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount851397526/Dockerfile: no such file or directory
```

Here's `daemon.log` output too. There are no currently running instances of wekan on my system, so I'm not sure what it means by "Error while dialing only one connection allowed":

```
Sep  1 06:58:30 docker systemd[135636]: run-docker-runtime\x2drunc-moby-4246ae7c37b3100fa24c18a983c09c6b9ee1e1f0c0b3707ba99c009640e65e1c-runc.kugPIr.mount: Succeeded.
Sep  1 06:58:30 docker systemd[1]: run-docker-runtime\x2drunc-moby-4246ae7c37b3100fa24c18a983c09c6b9ee1e1f0c0b3707ba99c009640e65e1c-runc.kugPIr.mount: Succeeded.
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.583107754-04:00" level=info msg="parsed scheme: \"\"" module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.584373587-04:00" level=info msg="scheme \"\" not registered, fallback to default scheme" module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.584423559-04:00" level=info msg="ccResolverWrapper: sending update to cc: {[{localhost  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.584442449-04:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.600548957-04:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {localhost  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing only one connection allowed\". Reconnecting..." module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.617178491-04:00" level=info msg="parsed scheme: \"\"" module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.617243297-04:00" level=info msg="scheme \"\" not registered, fallback to default scheme" module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.617277733-04:00" level=info msg="ccResolverWrapper: sending update to cc: {[{localhost  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Sep  1 06:58:32 docker dockerd[517]: time="2022-09-01T06:58:32.617304182-04:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Sep  1 06:58:33 docker systemd[1]: var-lib-docker-tmp-buildkit\x2dmount851397526.mount: Succeeded.
Sep  1 06:58:33 docker systemd[135636]: var-lib-docker-tmp-buildkit\x2dmount851397526.mount: Succeeded.
Sep  1 06:58:33 docker systemd[135636]: var-lib-docker-tmp-buildkit\x2dmount4185332661.mount: Succeeded.
Sep  1 06:58:33 docker systemd[1]: var-lib-docker-tmp-buildkit\x2dmount4185332661.mount: Succeeded.
Sep  1 06:58:33 docker dockerd[517]: time="2022-09-01T06:58:33.040560515-04:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {localhost  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing only one connection allowed\". Reconnecting..." module=grpc
```

**Comment by xet7** [comment]
No.

a) "docker-compose up -d --build" starts full wekan with mongodb, building from source only wekan-app container. Option "-d" starts it to background.

b) "docker build ." only builds Dockerfile, and shows container id as last step. After that, I use scripts wekan/releases/docker-push-wekan.sh and wekan/releases/docker-push-gantt.sh to push images to Docker Hub and quay.io .

When only using wekan, that --build option and those uncommentings are not used, prebuilt wekan-app image is downloaded from quay.io or Docker Hub, depending what image is used at docker-compose.yml

**Comment by xet7** [comment]
I usually build docker images on amd64 server that has Debian or Ubuntu. Building images works, and correctly shows container id when finished.

**Comment by xet7** [comment]
Currently building without Docker like at https://github.com/wekan/wekan/wiki/Emoji does build incorrectly on Mac M1, trying to run it fails.

Also building on WSL2 can have problems.

When developing, best is to use Mint/Ubuntu/Debian amd64 on SSD or NVME disk, and at least 16 GB RAM. 8 GB is too little, webbrowsers use so much RAM.

**Comment by willman42** [comment]
Ok thanks for the clarification.

So if I understand correctly, if I try to build from the Dockerfile in the repo, it runs those 2 scripts you mentioned? I don't want to publish my image to dockerhub or do anything with Gantt of course. 

How can I build the image just on my local system and not publish to Dockerhub or do anything in those 2 scripts? I just want to verify changes made to Dockerfile don't break image creation. Before submitting more PR's 👍

**Comment by xet7** [comment]
@willman42 

When testing, you could use:

a) `docker-compose up -d --build` https://github.com/wekan/wekan/issues/4666#issuecomment-1234207733

b) Building without docker https://github.com/wekan/wekan/wiki/Emoji , this works faster than building Docker.

Only I can publish official images to Docker Hub etc, because I have official passwords, 2FA, etc. Sure others could setup their own to their accounts, but others are not official.

**Comment by xet7** [comment]
When developing, I sometimes delete all docker containers, volumes etc data to free up disk space, with this:
```
git clone https://github.com/wekan/docker-cleanup-volumes

cd docker-cleanup-volumes

./start.sh
```
I install Docker from here https://docs.docker.com/engine/install/ubuntu/

And docker-compose from here https://docs.docker.com/compose/install/compose-plugin/#installing-compose-on-linux-systems

**Comment by willman42** [comment]
> `docker-compose up -d --build` [#4666 (comment)](https://github.com/wekan/wekan/issues/4666#issuecomment-1234207733)

Yes this is what I used.

> Only I can publish official images to Docker Hub etc, because I have official passwords, 2FA, etc. Sure others could setup their own to their accounts, but others are not official.

Yes I understand- I **_don't_** want to publish to Dockerhub.

Do I need to clear out al containers and volumes on the host I use to build an image? Or is that just your preference?

@xet7 How can I test changes made to a Dockerfile? I assume I should be able to use the Dockerfile in my local copy of the Wekan repo to build an image from it as a test, correct? Or am I misunderstanding something fundamental about building images from Dockerfiles?

**Comment by xet7** [comment]
@willman42 

> @xet7 How can I test changes made to a Dockerfile?

With webbrowser, register at http://localhost/sign-up and login at http://localhost/sign-in

**Comment by xet7** [comment]
No, you don't need to clear out all containers and volumes, if you have anything important data there without [Backup](https://github.com/wekan/wekan/wiki/Backup). It's just that because I release new version of WeKan very often, I just free some disk space sometimes.

**Comment by willman42** [comment]
> 

Don't I need to actually build a new image with the modified Dockerfile first?

**Comment by xet7** [comment]
@willman42 

That `docker-compose up -d --build` uses all your current modifications in wekan directory. So  if you have cloned WeKan repo:

```
git clone https://github.com/wekan/wekan

cd wekan
```
And then modified Dockerfile or other files, then all changes are built with:
```
docker-compose up -d --build
```

**Comment by willman42** [comment]
Ok right- that's what I'm saying isn't working. It's failing with the error output in the original post.

**Comment by xet7** [comment]
@willman42 

For WeKan users, it's easiest to use prebuilt container, and not build from source.

**Comment by xet7** [comment]
Similarly like here https://github.com/wekan/wekan/issues/4665

**Comment by willman42** [comment]
I know it's easiest to use prebuilt containers. I'm just asking how am I supposed to test a proposed change to the Dockerfile before merging the commit to `master`? Like to prevent what happened with #4663 having to be reversed. I could figure out how to test my proposed changes before submitting the PR, and I'd like to be able to do so for the next time.

But when I run the `docker build` or `docker compose up --build` commands as above, I get the error in my original post.

**Comment by xet7** [comment]
@willman42 

Building works for me locally at home Mint/Ubuntu/Debian based computer, and at server Debian. Problem could be restrictions in your local network, slow disk (if it's not SSD or NVME), slow network connection, etc.

**Comment by xet7** [comment]
Or alternatively, if you don't have enough RAM, like minimum 16 GB RAM, or you have too many other apps running.

**Comment by xet7** [comment]
It's just that building WeKan does create directory `wekan/.meteor/bundle` that has about 60 000 mostly small files of HTML/CSS/JS. Building is not for slow computers.

**Comment by willman42** [comment]
Ok fair enough. Can you tell me what the build process is trying to do in this specific step: `+ gosu wekan:wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build`

And can you shed some light on this error output for me so I can better troubleshoot potential connection problems?

```
=> Errors while initializing project:

While downloading cfs:reactive-list@0.0.9...:
error: ETIMEDOUT
```

**Comment by xet7** [comment]
Yes, it timed out when trying to download it. There could be some F5 firewall or MS Defender or some other that causes trouble.

**Comment by willman42** [comment]
Do you know where it tries to download from?

**Comment by xet7** [comment]
Well, maybe here https://atmospherejs.com/cfs/reactive-list , or elsewhere at https://atmospherejs.com or https://npmjs.com

**Comment by xet7** [comment]
Prebuilt .zip files of bundle are at https://github.com/wekan/wekan/releases and directories of https://releases.wekan.team like described at https://github.com/wekan/wekan/wiki/Raspberry-Pi , so in theory, you could edit any HTML/CSS/JS file in that directory, and then just run it with start-wekan.sh

**Comment by xet7** [comment]
If some changes need to be added to wekan, you could find those from wekan repo with script that ignores generated directories, and make PR, for example here about code related to webhooks:

```
git clone https://github.com/wekan/wekan

cd wekan

./find.sh webhooks
```

**Comment by xet7** [comment]
Dockerfile expects you have in Ubuntu/Debian username wekan, you see hardcoded paths in that Dockerfile. Also, in Dockerfile files are installed, directory permissions changed, etc, so that the correct directory works:

```
/home/wekan
```
And that repo is cloned to `/home/wekan/repos/wekan`
```
mkdir repos
cd repos
git clone https://github.com/wekan/wekan
cd wekan
docker build .
```
or alternatively:
```
docker-compose up -d --build
```
 Also, meteor needs to be installed here, that `rebuild-wekan.sh` script installs it:
```
/home/wekan/.meteor
```
I have not yet figured out how to make possible building Dockerfile/docker-compose.yml if paths are different.
