### ISSUE TITLE
Container cannot be stopped gracefully

### ISSUE THREAD

**Issue by bronger** [wekan/wekan#4668]
The process 1 in the Wekan container (node) does not respond to a TERM signal, therefore, the container needs to be stopped forcefully and after a grace period.  Instead, a SIGTERM sent to the node process should terminate it gracefully.

A workaround is to add

    STOPSIGNAL SIGKILL
to the Dockerfile. But the preferred way is to make node to react to TERM (or INT).

**Comment by xet7** [comment]
@bronger 

To what line number of Dockerfile it should be added?
https://github.com/wekan/wekan/blob/master/Dockerfile

What text exactly should that line of text have?

**Comment by xet7** [comment]
@bronger 

Can you send PR ?

**Comment by bronger** [comment]
It works for me now. I hope it’s okay if I close it.
