### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#467]
Apart from the mostly stylistic Eslint static analysis, Wekan currently doesn’t have any test. This is a big problem that we need to fix. Unfortunately the Meteor ecosystem has historically been sort of lacking in this field, which means that writing tests for a Meteor application involves making some architecture decisions that haven’t been figure out as a documented standard by either the Meteor community or MDG.

I would distinguish mainly two categories of tests:
- **Non Meteor specific tests.** After all we are just building a web application that runs on NodeJS on the server and a browser on the client, so we can re-use most of the existing testing infrastructure in the broader NodeJS ecosystem. One limitation that we currently have is the difficulty to `import` a single JavaScript object to run unit tests on it due to the lack of ES6 modules support in Meteor, but that problem will be solved with Meteor 1.3. So we soon won’t have any limitations on standard tests anymore.
- **Meteor specific tests.** As we build rich-client application we want to test some scenarios with mutliple client creating actions and a server in the middle. For instance we want to test that if I remove access to a board to a user, then this user can't access any of the board data anymore. It seems that [Gagarin](https://github.com/anticoders/gagarin) is a good fit for these tests.

The first tests will come pretty soon. Basically I plan to migrate Wekan to Meteor 1.3 as soon as there is a working beta (`beta-2` raises some exceptions on application start, but these are reported and should be fixed in the next beta), then we will have to re-organize to some extends the internal structure of the application to make it more modular and to use ES6 `import` and `export`, first tests will come concurrently with this transition to canonical Meteor 1.3.

**Comment by jseadragon** [comment]
Once this is out, I'd be open to helping write some tests. It'd be a good way to learn how Wekan is built, too.

@mquandalle Do you think there would be any form of an integration test that would interface with the raw <div> elements (like cucumber or selenium)? Or could we get enough user-story coverage using the JS unit tests and 'mocking' out the other modules? If it's a silly question, no worries. I'm not familiar with the NodeJS testing ecosystem.

**Comment by romant** [comment]
Check out [chimp](https://github.com/xolvio/chimp); has been invaluable for Meteor testing

**Comment by miherlosev** [comment]
Wekan is a end-user application.
So, e2e tests is more preferred.
I can write them using [Testcafe](https://github.com/devexpress/testcafe) and setup CI on `Travis` or `appveyor`.

**Comment by ocdtrekkie** [comment]
@miherlosev Some of the Wekan community is currently working off of https://github.com/wefork/wekan and I don't think any CI testing is set up currently for that repo. But I think it would probably be quite welcome.

**Comment by miherlosev** [comment]
Ok. 
I will create pull request with CI integration and write first e2e tests.

**Comment by miherlosev** [comment]
> Wekan is a end-user application.
> So, e2e tests is more preferred.
> I can write them using Testcafe and setup CI on Travis or appveyor.

@xet7 
What do you think?

**Comment by xet7** [comment]
@miherlosev 

There is .travis.yml file and build passing badge already at:
https://github.com/wefork/wekan

If it's missing something, send a pull request or add issue to wefork what I should add there.
