### ISSUE TITLE
Members, Orgs and Teams on sidebar

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#4671]
Hi, guys!

When I have a team or a org, a lot of info is showed on sidebar.
![image](https://user-images.githubusercontent.com/24301085/188283387-7aa33bf6-4f01-495b-b58c-9cb02168a9c0.png)

What do you think about this idea:
![image](https://user-images.githubusercontent.com/24301085/188283427-59b6c81e-9fda-499d-b87c-9a1ed8ea0e65.png)

![image](https://user-images.githubusercontent.com/24301085/188283494-ab243c4b-5daa-46f9-a906-aceec47fac41.png)

I use tabs to Members (people, orgs and teams) and change "board settings" link.

**Comment by xet7** [comment]
@helioguardabaxo 

Yes, it would be better. 

But in text "Board Settings" please do not add "..."

You can send PR.

**Comment by helioguardabaxo** [comment]
Nice!
Thanks!

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4672
