### ISSUE TITLE
Cannot update wekan v6.11 to v6.44 on arm64

### ISSUE THREAD

**Issue by kvacha13** [wekan/wekan#4676]
### Server Setup Information

* Did you test in newest Wekan?:
Yes, downloaded from https://releases.wekan.team/raspi3/
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
The server was already running Wekan v6.11
* Operating System:
Linux my-arm64-server 5.11.0-1022-oracle #23~20.04.1-Ubuntu SMP Fri Nov 12 15:45:47 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
bundel
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
Apache/2.4.41 (Ubuntu)
* Node.js Version:
v14.19.3
* MongoDB Version:
db version v5.0.3
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
Chrome

### Problem description
after update service wekan  does not start
#### Reproduction Steps
1. download file wekan-6.44-arm64.zip from https://releases.wekan.team/raspi3/wekan-6.44-arm64.zip
2. unzip the file
3. stop services wekan and apache2
4. change the name of the existing wekan folder (in my case /opt/wekan changed to /opt/wekan611) to back up the existing version.
5. mv the unzipped folder bundle to /opt/wekan
6. service wekan start (fails to start with no important errors)

####Log
 There is an issue with `node-fibers` ##
Sep 08 20:25:42 my-arm64-server node[259960]: `/opt/wekan/programs/server/node_modules/fibers/bin/linux-arm64-83-glibc/fib>Sep 08 20:25:42 my-arm64-server node[259960]: Try running this to fix the issue: /usr/local/bin/node /opt/wekan/programs/s>Sep 08 20:25:42 my-arm64-server node[259960]: Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (req>Sep 08 20:25:42 my-arm64-server node[259960]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:>Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.load (internal/modules/cjs/loader.js:950:32)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.Mp.load (/opt/wekan/programs/server/runtime.js:46:33)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.require (internal/modules/cjs/loader.js:974:19)
Sep 08 20:25:42 my-arm64-server node[259960]:     at require (internal/modules/cjs/helpers.js:101:18)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Object.<anonymous> (/opt/wekan/programs/server/node_modules/fibers/fi>Sep 08 20:25:42 my-arm64-server node[259960]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.Mp._compile (/opt/wekan/programs/server/runtime.js:99:23)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)Sep 08 20:25:42 my-arm64-server node[259960]: /opt/wekan/programs/server/node_modules/fibers/fibers.js:23
Sep 08 20:25:42 my-arm64-server node[259960]:                 throw new Error('Missing binary. See message above.');
Sep 08 20:25:42 my-arm64-server node[259960]:                 ^
Sep 08 20:25:42 my-arm64-server node[259960]: Error: Missing binary. See message above.
Sep 08 20:25:42 my-arm64-server node[259960]:     at Object.<anonymous> (/opt/wekan/programs/server/node_modules/fibers/fi>Sep 08 20:25:42 my-arm64-server node[259960]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.Mp._compile (/opt/wekan/programs/server/runtime.js:99:23)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.load (internal/modules/cjs/loader.js:950:32)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.Mp.load (/opt/wekan/programs/server/runtime.js:46:33)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Module.require (internal/modules/cjs/loader.js:974:19)
Sep 08 20:25:42 my-arm64-server node[259960]:     at require (internal/modules/cjs/helpers.js:101:18)
Sep 08 20:25:42 my-arm64-server node[259960]:     at Object.<anonymous> (/opt/wekan/programs/server/boot.js:2:15)
Sep 08 20:25:42 my-arm64-server systemd[1]: wekan.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 20:25:42 my-arm64-server systemd[1]: wekan.service: Failed with result 'exit-code'.
Sep 08 20:25:43 my-arm64-server systemd[1]: wekan.service: Scheduled restart job, restart counter is at 5.
Sep 08 20:25:43 my-arm64-server systemd[1]: Stopped The Wekan Service.
Sep 08 20:25:43 my-arm64-server systemd[1]: wekan.service: Start request repeated too quickly.
Sep 08 20:25:43 my-arm64-server systemd[1]: wekan.service: Failed with result 'exit-code'.
Sep 08 20:25:43 my-arm64-server systemd[1]: Failed to start The Wekan Service.

**Comment by xet7** [comment]
Hmm, I don't know. For me, wekan starts OK on arm64 server, using versions mentioned at https://wekan.github.io Download section.

**Comment by xet7** [comment]
I presume you should install build-essential or some similar, and reinstall fibers and bcrypt.

- https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-a.sh#L22
- https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-a.sh#L24

**Comment by kvacha13** [comment]
I had a similar issue earlier (issue #4199). And that time, you fixed a fiber problem in the installation file. Can you please check it also?

**Comment by xet7** [comment]
@kvacha13 

I have Node.js 14.20.0 and Ubuntu 22.04.1 LTS on arm64 server. Can you upgrade Ubuntu?

**Comment by kvacha13** [comment]
Unfortunately, I would refrain from updating at the moment as it is running multiple programs and I rather avoid any complications due to the update. Could it be the issue of  Node.js 14.20? I'm running 14.19? Should i try 14.20?

**Comment by xet7** [comment]
@kvacha13 

Yes, and try [reinstalling fibers and bcrypt](https://github.com/wekan/wekan/issues/4676#issuecomment-1241115642).

**Comment by kvacha13** [comment]
Can you please instruct me on how safely reinstall fibers and bcrypt? in case something goes wrong I would like to restore the existing version (v6.11) by just restoring the old weaken folder.

**Comment by xet7** [comment]
@kvacha13 

In directory, where is your newest bundle subdirectory of newest wekan, run those lines of commands I linked above.

**Comment by xet7** [comment]
And before them:
```
sudo apt -y install build-essential
```

**Comment by kvacha13** [comment]
@xet7  Thank you for the help. It fixed the problem. Just, I've noticed that the version mark for the Wekan 6.44 in the admin panel is incorrect, showing v6.11 (instead of v6.44). Can you check it and correct it?

**Comment by xet7** [comment]
@kvacha13 

My newest WeKan shows 6.44. You have old WeKan version.

**Comment by kvacha13** [comment]
Can you please give me the exact link, to download the newest because i've downloaded it from this webpage https://releases.wekan.team/raspi3/  and to be more precise, this file: https://releases.wekan.team/raspi3/wekan-latest-arm64.zip

**Comment by xet7** [comment]
<img width="979" alt="wekan-arm" src="https://user-images.githubusercontent.com/15545/189353191-9ddbdaff-146a-4013-813b-efe3151f0729.png">

**Comment by xet7** [comment]
Yes that is the same correct link. In above screenshot, I'm running from that bundle.

**Comment by xet7** [comment]
I run MongoDB 5.x from juju-db snap:

https://github.com/wekan/wekan/wiki/Raspberry-Pi#installing-mongodb-snap-for-amd64arm64ppc64els390x

**Comment by kvacha13** [comment]
Yep, very strange. this is my admin panel:
![image](https://user-images.githubusercontent.com/8162633/189360392-68911d4e-8cdf-4375-a9a8-c33b0f2a41c6.png)
![adminPAnel](https://user-images.githubusercontent.com/8162633/189360455-ca0b1a83-b1b4-46cd-8e53-c105bddd3713.png)

**Comment by xet7** [comment]
Try this:

```
sudo apt -y install g++ build-essential npm

sudo npm -g install n

sudo n 14.20.0

cd bundle/programs/server

npm remove fibers bcrypt

npm install fibers bcrypt

cd ../../..

./start-wekan.sh
```
That start-wekan.sh is at https://github.com/wekan/wekan , and it should be edited for correct path at beginning:
```
cd bundle
```
And at bottom:
```
cd ..
```
Also, if you installed juju-db snap, also install mongodb shell and tools from mongodb.com community server pages, if you use MongoDB CLI.

I just tried this on Raspberry Pi 4 that has 4 GB RAM, Raspberry Pi OS 64bit, and juju-db.

**Comment by xet7** [comment]
With Linux distros, problem is, that each distro uses different versions of dependencies, so fibers and bcrypt needs to be reinstalled for each distro.

This could maybe change later, if Meteor figures out how to remove fibers, or if something else gets changed in WeKan server, so that fibers would not be needed anymore.

**Comment by xet7** [comment]
Other alternative would be, that I would make only one WeKan bundle, that would include directory of fibers and bcrypt for all different distros, and when starting wekan with `node main.js`, in beginning of that code would be code that moves fibers and bcrypt to correct directories, if filesystem is not read-only. But, on Docker/Snap/Sandstorm filesystem is read-only.

**Comment by kvacha13** [comment]
@xet7 Thank you for still working with me on this problem. I tried what you suggested before and now also, but while installing bcrypt I'm getting the following error lo:
root@my-arm64-server:/opt/wekan/programs/server# npm install fibers bcrypt
npm ERR! code 127
npm ERR! path /opt/wekan/programs/server/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c -- node build.js || nodejs build.js
npm ERR! internal/modules/cjs/loader.js:905
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '../'
npm ERR! Require stack:
npm ERR! - /opt/wekan/programs/server/node_modules/.bin/node-gyp
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:101:18)
npm ERR!     at Object.<anonymous> (/opt/wekan/programs/server/node_modules/.bin/node-gyp:8:13)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [ '/opt/wekan/programs/server/node_modules/.bin/node-gyp' ]
npm ERR! }
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! sh: 1: nodejs: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-10T04_30_21_208Z-debug-0.log
root@my-arm64-server:/opt/wekan/programs/server# service wekan start
root@my-arm64-server:/opt/wekan/programs/server# service wekan status
● wekan.service - The Wekan Service
     Loaded: loaded (/etc/systemd/system/wekan.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-09-10 06:31:37 CEST; 1s ago
    Process: 570618 ExecStart=/usr/local/bin/node main.js (code=exited, status=1/FAILURE)
   Main PID: 570618 (code=exited, status=1/FAILURE)

Sep 10 06:31:37 my-arm64-server systemd[1]: wekan.service: Scheduled restart job, restart counter is at 5.
Sep 10 06:31:37 my-arm64-server systemd[1]: Stopped The Wekan Service.
Sep 10 06:31:37 my-arm64-server systemd[1]: wekan.service: Start request repeated too quickly.
Sep 10 06:31:37 my-arm64-server systemd[1]: wekan.service: Failed with result 'exit-code'.
Sep 10 06:31:37 my-arm64-server systemd[1]: Failed to start The Wekan Service.

**Comment by kvacha13** [comment]
Just found out that "maintainer-make-bundle-a.sh"  from https://github.com/wekan/wekan/blob/master/releases/maintainer-make-bundle-a.sh#L22, instructs to go to the folder bundle/programs/server/node_modules/fibers and rebuild node build.js. But there is no fibers folder in the bundle from the newest arm64.
The instruction also says to go to bundle/programs/server/npm/node_modules/meteor/accounts-password && npm remove bcrypt && npm install bcrypt, but there is no accounts-password folder in this path.
then in which folders should these commands be run (I mean node build.js and npm remove/install bcrypt)?

**Comment by kvacha13** [comment]
Updated:
npm from v6 to v8.19.1
Node  from v14.19 to v14.20

following:
sudo npm -g uninstall node-pre-gyp
sudo npm -g install @mapbox/node-pre-gyp
cd bundle/programs/server && chmod u+w *.json && cd node_modules/fibers && node build.js)

Result:
Wekan started without error
but node  not listening port 3001 ( ss -tunlp).

**Comment by kvacha13** [comment]
I also think that problem is with fibers and bcrypt but could not manage to fix the problem. Should I first remove fibers and reinstall it? and should I reinstall it globally (npm -g install fibers), or according to wekan instruction: cd bundle/programs/server && chmod u+w *.json && cd node_modules/fibers && node build.js) The same question regarding bcrypt. PEr the wekan instruction : cd bundle/programs/server/npm/node_modules/meteor/accounts-password && npm remove bcrypt && npm install bcrypt.  But there is no accounts-password folder on this path. Should I execute it in bundle/programs/server/npm/node_modules/meteor folder? Any suggestions?

**Comment by xet7** [comment]
@kvacha13 

Try:
```
sudo npm -g install @mapbox/node-pre-gyp

cd bundle/programs/server

npm install

npm remove fibers bcrypt

npm install fibers bcrypt
````
Also, in start-wekan.sh or systemd service scripts needs to be defined ROOT_URL and PORT.

**Comment by kvacha13** [comment]
after npm install in folder bundle/programs/server:

root@ubuntu:/opt/wekan/programs/server# npm install
npm WARN old lockfile
npm WARN old lockfile The npm-shrinkwrap.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

> install
> node npm-rebuild.js

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'rebuild', '--update-binary' ]
}
npm ERR! code 1
npm ERR! path /opt/wekan/programs/server
npm ERR! command failed
npm ERR! command sh -c -- node npm-rebuild.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-10T15_53_57_880Z-debug-0.log

**Comment by xet7** [comment]
Hmm. I'll try to built it myself.

**Comment by kvacha13** [comment]
Thank you a lot. Appreciate your patience. 
after  npm install fibers bcrypt I got:

root@ubuntu:/opt/wekan/programs/server# npm install fibers bcrypt
npm ERR! code 1
npm ERR! path /opt/wekan/programs/server/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c -- node build.js || nodejs build.js
npm ERR! internal/modules/cjs/loader.js:905
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '../'
npm ERR! Require stack:
npm ERR! - /opt/wekan/programs/server/node_modules/.bin/node-gyp
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:101:18)
npm ERR!     at Object.<anonymous> (/opt/wekan/programs/server/node_modules/.bin/node-gyp:8:13)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [ '/opt/wekan/programs/server/node_modules/.bin/node-gyp' ]
npm ERR! }
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! internal/modules/cjs/loader.js:905
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '../'
npm ERR! Require stack:
npm ERR! - /opt/wekan/programs/server/node_modules/.bin/node-gyp
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:101:18)
npm ERR!     at Object.<anonymous> (/opt/wekan/programs/server/node_modules/.bin/node-gyp:8:13)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [ '/opt/wekan/programs/server/node_modules/.bin/node-gyp' ]
npm ERR! }
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`

npm ERR! A complete log of this run can be found in:

**Comment by kvacha13** [comment]
I've tried to reinstall fibers and bcrypt again on fresh Wekan v6.44 and everything went ok until the final step npm,  install fibers bcrypt gave me fewer errors, mainly regarding some permission issue. Maybe you know the reason:
                                                                                                                           
root@ubuntu:/opt/wekan/programs/server# npm install fibers bcrypt                                                          
                                                                                                                           
> fibers@5.0.3 install /opt/wekan/programs/server/node_modules/fibers                                                      
> node build.js || nodejs build.js                                                                                         
                                                                                                                           
gyp ERR! clean error                                                                                                       
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'                                                             
gyp ERR! System Linux 5.8.0-63-generic                                                                                     
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-
-release"                                                                                                                  
gyp ERR! cwd /opt/wekan/programs/server/node_modules/fibers                                                                
gyp ERR! node -v v14.20.0                                                                                                  
gyp ERR! node-gyp -v v5.1.0                                                                                                
gyp ERR! not ok                                                                                                            
node-gyp exited with code: 1                                                                                               
Please make sure you are using a supported platform and node version. If you                                               
would like to compile fibers on this machine please make sure you have setup your                                          
build environment--                                                                                                        
Windows + OS X instructions here: https://github.com/nodejs/node-gyp                                                       
Ubuntu users please run: `sudo apt-get install g++ build-essential`                                                        
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`                                    
Alpine users please run: `sudo apk add python make g++`                                                                    
gyp ERR! clean error                                                                                                       
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'                                                             
gyp ERR! System Linux 5.8.0-63-generic                                                                                     
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-
-release"                                                                                                                  
gyp ERR! cwd /opt/wekan/programs/server/node_modules/fibers                                                                
gyp ERR! node -v v14.20.0                                                                                                  
gyp ERR! node-gyp -v v5.1.0                                                                                                
gyp ERR! not ok                                                                                                            
node-gyp exited with code: 1                                                                                               
Please make sure you are using a supported platform and node version. If you                                               
would like to compile fibers on this machine please make sure you have setup your                                          
build environment--                                                                                                        
Windows + OS X instructions here: https://github.com/nodejs/node-gyp                                                       
Ubuntu users please run: `sudo apt-get install g++ build-essential`                                                        
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`                                    
Alpine users please run: `sudo apk add python make g++`                                                                    
npm ERR! code ELIFECYCLE                                                                                                   
npm ERR! errno 1                                                                                                           
npm ERR! fibers@5.0.3 install: `node build.js || nodejs build.js`                                                          
npm ERR! Exit status 1                                                                                                     
npm ERR!                                                                                                                   
npm ERR! Failed at the fibers@5.0.3 install script.                                                                        
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                         
                                                                                                                           
npm ERR! A complete log of this run can be found in:

**Comment by kvacha13** [comment]
I manage to avoid permission issue by adding --unsafe-perm to last command - npm install fibers bcrypt --unsafe-perm.
it still gave some errors but now wekan starts. And it still shows v6.11 instead of 6.44 in the Admin panel. Strange, Can you tell me what npm version you run on arm64 (in my case it is 6.14.17)?

**Comment by xet7** [comment]
@kvacha13 

Try this: https://releases.wekan.team/raspi3/wekan-latest-ubu20.04-arm64.zip

**Comment by kvacha13** [comment]
Thank you for compiling new version. I've jsut installed it on previous (v6.11) state/checkpoint environment and end it did not work (allservices running but node on port 3001 not up) . Do i need to run:

udo npm -g install @mapbox/node-pre-gyp

cd bundle/programs/server

npm install

npm remove fibers bcrypt

npm install fibers bcrypt

Is it compiled with the consideration of my linux environment:
UBuntu 20.01 arm64
npm v8.19.1
node v14.20.0
mongodb "version": "5.0.3",
Apache 2.4

**Comment by mfilser** [comment]
@kvacha13
Just an idea: Maybe you have a option like using Docker? These images are already compiled with all dependencies without any effect to other applications on your Server...

**Comment by kvacha13** [comment]
Thank you for the suggestion. But does the docker support arm64? and does wekan is on docker for arm64?

**Comment by mfilser** [comment]
Docker in general yes.
I don't know if there is a compiled image for arm64 available.

**Comment by xet7** [comment]
There is no Docker and Snap versions yet for arm64. There is some issue about Docker arm64 at #4607

**Comment by manfromdownunder** [comment]
> Docker in general yes. I don't know if there is a compiled image for arm64 available.

I compiled one a couple of days ago docker pull manfromdownunder/wekan-arm

**Comment by xet7** [comment]
Moved to #4607
