### ISSUE TITLE
Meteor WeKan translations: English works only on English, not English USA

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4679]
When in browser settings is English selected, Wekan web UI is in English.

If it's English (USA), English translations are not in use, it shows untranslated placeholder strings.

**Comment by JaredBoone** [comment]
I reproduced this issue.

**Comment by JaredBoone** [comment]
@xet7 In what release was this bug introduced?

**Comment by xet7** [comment]
@JaredBoone 

I don't know.
