### ISSUE TITLE
Wekan docker-compose upgrade from 6.28 -> 6.29 failed

### ISSUE THREAD

**Issue by BFalz** [wekan/wekan#4682]
### Server Setup Information
* Did you test in newest Wekan?: can't
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Ubuntu 20.04.2 LTS (Focal Fossa)
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker/Docker-Compose
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node.js Version: -
* MongoDB Version: 5
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Chrome + Firefox

### Problem description
I tried updating Wekan v6.28 to v.6.29 (or to latest). i switched from 
```
 wekan:
    #-------------------------------------------------------------------------------------
    # ==== MONGODB AND METEOR VERSION ====
    # a) Quay automatic builds do work work, https://quay.io/wekan/wekan
    image: quay.io/wekan/wekan:v6.28
```
to
```
 wekan:
    #-------------------------------------------------------------------------------------
    # ==== MONGODB AND METEOR VERSION ====
    # a) Quay automatic builds do work work, https://quay.io/wekan/wekan
    image: quay.io/wekan/wekan:v6.29
```
and restarted the docker containers and on v6.29 startup i get this error:
```
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xa3ac10 node::Abort() [node]
 2: 0xa3ac8e  [node]
 3: 0xaab44e  [node]
 4: 0xaab516 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node]
 5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node]
 6: 0xa03831 node::Start(int, char**) [node]
 7: 0x7fa7c12ffd90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fa7c12ffe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x98c58c  [node]
```

Docker ps:
```
root@wizardly-rhodes:/home/lorop/wekan# docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS                           PORTS                                                                      NAMES
394ca4d72a65   nginx                       "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes                     0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx
f651a70b6392   quay.io/wekan/wekan:v6.29   "bash -c 'ulimit -s …"   2 minutes ago   Restarting (139) 9 seconds ago                                                                              wekan-app
e76a6d64bd7f   mongo:5                     "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes                     27017/tcp                                                                  wekan-db
```

**Comment by bwulff** [comment]
I experience exactly the same. Did only set the base URL, otherwise docker-compose file is untouched.

**Comment by xet7** [comment]
@bwulff 

Did you use newest docker-compose.yml from https://github.com/wekan/wekan , with `docker-compose up -d`? it works for me.

For any previous version, do backup with mongodump, and restore to newest https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
Also you need maybe at least 2 or 4 GB RAM total in server where WeKan is running (although I usually have more at servers). If there is too little RAM, it crashes.

**Comment by xet7** [comment]
Currently I'm developing on Ubuntu 22.10 . And also Docker base image is 22.10 in newest WeKan Docker container.

**Comment by bwulff** [comment]
@xet7 so I tried on another machine. Just cloned repo, changed base URL in docker-compose file and did `docker-compose up -d`. That worked fine.
However doing the same on the other machine leads to ´wekan-app´ restarting with the following error:
```
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xa3ac10 node::Abort() [node]
 2: 0xa3ac8e  [node]
 3: 0xaab44e  [node]
 4: 0xaab516 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node]
 5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node]
 6: 0xa03831 node::Start(int, char**) [node]
 7: 0x7f2473674510  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f24736745c9 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x98c58c  [node]
```
The OS and the Docker daemon sure are of older versions on the machine where it fails. I'll post details once I gathered them.

**Comment by xet7** [comment]
@bwulff 

https://github.com/nodejs/node/issues/43064
