### ISSUE TITLE
General board view feature

### ISSUE THREAD

**Issue by Zenithar** [wekan/wekan#469]
Add a feature to merge virtually (readonly) a set of board in one to have a overview of all column (same 'wishes', 'wishes for next release', 'wip').

Its makes things easy when trying to plan multiple project roadmaps.

**Comment by jseadragon** [comment]
Any chance [this proposal](https://discuss.wekan.io/t/abtract-lists-into-a-generalized-task-meta-data/121) is remotely similar to what you're suggesting?

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/pull/1592
