### ISSUE TITLE
wekan-app exited with code 139 after last update

### ISSUE THREAD

**Issue by airdogvan** [wekan/wekan#4690]
Did the update with docker-compose pull wekan
as I usually do and now wekan won't start.

Please find log below: (sorry for formating)

wekan-db                |  
wekan-db                | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that! 
wekan-db                |   see https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2 
wekan-db                |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814 
wekan-db                |  
wekan-db                | 2022-09-15T18:08:43.809+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none' 
wekan-db                | 2022-09-15T18:08:43.817+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=4bad81c2f5e7 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] db version v4.2.16 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] git version: 8a5c1f52a77bc92320c90ecbe5424e841874296e 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] allocator: tcmalloc 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] modules: none 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] build environment: 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten]     distarch: x86_64 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten]     target_arch: x86_64 
wekan-db                | 2022-09-15T18:08:43.817+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" }, replication: { oplogSizeMB: 128 } } 
wekan-db                | 2022-09-15T18:08:43.818+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'. 
wekan-db                | 2022-09-15T18:08:43.818+0000 I  STORAGE  [initandlisten]  
wekan-db                | 2022-09-15T18:08:43.818+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine 
wekan-db                | 2022-09-15T18:08:43.818+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem 
wekan-db                | 2022-09-15T18:08:43.818+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3469M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_ma
x=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0
),verbose=[recovery_progress,checkpoint_progress],

wekan-app               | node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_th
read, this))' failed. 
wekan-app               |  1: 0xa3ac10 node::Abort() [node] 
wekan-app               |  2: 0xa3ac8e  [node] 
wekan-app               |  3: 0xaab44e  [node] 
wekan-app               |  4: 0xaab516 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node] 
wekan-app               |  5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node] 
wekan-app               |  6: 0xa03831 node::Start(int, char**) [node] 
wekan-app               |  7: 0x7fe867de3d90  [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  8: 0x7fe867de3e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  9: 0x98c58c  [node] 
wekan-db                | 2022-09-15T18:08:44.938+0000 I  STORAGE  [initandlisten] WiredTiger message [1663265324:938346][1:0x7fce1db8fb00], txn-recover: Recovering log 40 through 41 
wekan-db                | 2022-09-15T18:08:45.114+0000 I  STORAGE  [initandlisten] WiredTiger message [1663265325:114029][1:0x7fce1db8fb00], txn-recover: Recovering log 41 through 41 
wekan-db                | 2022-09-15T18:08:45.202+0000 I  STORAGE  [initandlisten] WiredTiger message [1663265325:202341][1:0x7fce1db8fb00], txn-recover: Main recovery loop: starting at 40/6784 to 41/256 
wekan-db                | 2022-09-15T18:08:45.308+0000 I  STORAGE  [initandlisten] WiredTiger message [1663265325:308179][1:0x7fce1db8fb00], txn-recover: Recovering log 40 through 41 
wekan-db                | 2022-09-15T18:08:45.386+0000 I  STORAGE  [initandlisten] WiredTiger message [1663265325:386291][1:0x7fce1db8fb00], txn-recover: Recovering log 41 through 41 
wekan-db                | 2022-09-15T18:08:45.445+0000 I  STORAGE  [initandlisten] WiredTiger message [1663265325:445814][1:0x7fce1db8fb00], txn-recover: Set global recovery timestamp: (0, 0) 
wekan-db                | 2022-09-15T18:08:45.480+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0) 
wekan-db                | 2022-09-15T18:08:45.502+0000 I  STORAGE  [initandlisten] No table logging settings modifications are required for existing WiredTiger tables. Logging enabled? 1 
wekan-db                | 2022-09-15T18:08:45.510+0000 I  STORAGE  [initandlisten] Timestamp monitor starting 
wekan-db                | 2022-09-15T18:08:45.513+0000 I  CONTROL  [initandlisten]  
wekan-db                | 2022-09-15T18:08:45.513+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database. 
wekan-db                | 2022-09-15T18:08:45.513+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted. 
wekan-db                | 2022-09-15T18:08:45.513+0000 I  CONTROL  [initandlisten]  
wekan-db                | 2022-09-15T18:08:45.513+0000 I  CONTROL  [initandlisten]  
wekan-db                | 2022-09-15T18:08:45.513+0000 I  CONTROL  [initandlisten] ** WARNING: soft rlimits too low. rlimits set to 31495 processes, 1048576 files. Number of processes should be at least 524288 : 
0.5 times number of files. 
wekan-db                | 2022-09-15T18:08:45.558+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment. 
wekan-db                | 2022-09-15T18:08:45.577+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data' 
wekan-db                | 2022-09-15T18:08:45.586+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock 
wekan-db                | 2022-09-15T18:08:45.587+0000 I  NETWORK  [listener] Listening on 0.0.0.0 
wekan-db                | 2022-09-15T18:08:45.588+0000 I  NETWORK  [listener] waiting for connections on port 27017
wekan-app               |  2: 0xa3ac8e  [node] 
wekan-app               |  3: 0xaab44e  [node] 
wekan-app               |  4: 0xaab516 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node] 
wekan-app               |  5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node] 
wekan-app               |  6: 0xa03831 node::Start(int, char**) [node] 
wekan-app               |  7: 0x7f215e30cd90  [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  8: 0x7f215e30ce40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  9: 0x98c58c  [node] 
wekan-app exited with code 139

wekan-app               | node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_th
read, this))' failed. 
wekan-app               |  1: 0xa3ac10 node::Abort() [node] 
wekan-app               |  2: 0xa3ac8e  [node] 
wekan-app               |  3: 0xaab44e  [node] 
wekan-app               |  4: 0xaab516 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node] 
wekan-app               |  5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node] 
wekan-app               |  6: 0xa03831 node::Start(int, char**) [node] 
wekan-app               |  7: 0x7f3a5b58dd90  [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  8: 0x7f3a5b58de40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  9: 0x98c58c  [node] 
wekan-app exited with code 139

wekan-app               |  1: 0xa3ac10 node::Abort() [node] 
wekan-app               |  2: 0xa3ac8e  [node] 
wekan-app               |  3: 0xaab44e  [node] 
wekan-app               |  4: 0xaab516 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node] 
wekan-app               |  5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node] 
wekan-app               |  6: 0xa03831 node::Start(int, char**) [node] 
wekan-app               |  7: 0x7f5f1d9fed90  [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  8: 0x7f5f1d9fee40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  9: 0x98c58c  [node] 
wekan-app exited with code 139

wekan-app               |  5: 0xa0330d node::InitializeOncePerProcess(int, char**) [node] 
wekan-app               |  6: 0xa03831 node::Start(int, char**) [node] 
wekan-app               |  7: 0x7f2ea8b0fd90  [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  8: 0x7f2ea8b0fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6] 
wekan-app               |  9: 0x98c58c  [node] 
wekan-app exited with code 139

Any help greatly appreciated.

**Comment by xet7** [comment]
Sorry, current MongoDB 5.x requires AVX instructions #4321 

Porting to other databases is In Progress https://github.com/wekan/wekan/issues/4578#issuecomment-1248485306 

Moved to #4321

**Comment by airdogvan** [comment]
Not sure that this answers my problem.
What you see in the logs regarding Mongo is only a warning and Mongo does start correctly.
And also during that last year I've never upgraded Mongo (neither did I this time) but ONLY wekan.

And as said after the latest WEKAN upgrade I get this error.
The warning has been there since almost the beginning (more that 1 year ago) and everything was running fine.
For reference I'm running  Mongo 4.2.

**Comment by xet7** [comment]
@airdogvan 

Some old version of Meteor WeKan does not require MongoDB 5.x and AVX instructions hardware support. Newest Meteor WeKan does require.

**Comment by airdogvan** [comment]
So is it possible for me to run the previous version of wekan?  Could I for instance pull the previous version?
Thanks for the help

**Comment by xet7** [comment]
@airdogvan 

Yes, look at docker image tag versions and mongodb versions from GitHub top left button master / tags. docker-compose.yml is at https://github.com/wekan/wekan .

**Comment by airdogvan** [comment]
thanks, tried going back to image v6.31 and still the same error.  Guess something really did get messed up in the db... and I have to start from scatch   :(
Thanks again
