### ISSUE TITLE
Links not showing the port (3001), so they don't work?

### ISSUE THREAD

**Issue by ejlkemper** [wekan/wekan#4695]
Hi all,

Wekan is performing well and we are happy with it. But only one thing confuses me.
I got the email part working, but the links that are send with it, don't have the port 3001 attached to the URL?
When I add the port manually in the URL link in the browser, it shows the page.
 
Any hints where I when wrong?

**Comment by xet7** [comment]
@ejlkemper 

Do you have port number in ROOT_URL ?

https://github.com/wekan/wekan/wiki/Settings

**Comment by ejlkemper** [comment]
No, is that the culprit?

**Comment by xet7** [comment]
Yes

**Comment by ejlkemper** [comment]
Ok, I will test that and get back to you!
Thanks!

**Comment by ejlkemper** [comment]
Hello xet7,

It works, so thank you for the help on this!
