### ISSUE TITLE
Missing Contribution Information for the Wiki

### ISSUE THREAD

**Issue by BlobbyBob** [wekan/wekan#4696]
Yesterday I've found an invalid link on a wiki page, but I couldn't find any information on how to fix issues on wiki pages.  
After quite some search I've found [this issue comment](https://github.com/wekan/wekan/issues/922#issuecomment-287604373), but the information seems outdated and the wiki is not editable for me.

As the `CONTRIBUTING.md` refers to the wiki main page which then refers to the [Contribution Guidelines](https://github.com/wekan/wekan/wiki/Developer-Documentation) it would probably the best to add a short info over there.

**Comment by xet7** [comment]
Thanks! Added.
