### ISSUE TITLE
Wiki: Broken link to Meteor repair tools

### ISSUE THREAD

**Issue by BlobbyBob** [wekan/wekan#4697]
The link to the meteor repair tools has changed slightly. You find a patch here: [fixed-meteor-repair-link-patch.txt](https://github.com/wekan/wekan/files/9597779/fixed-meteor-repair-link-patch.txt)

*Note*: I think for small fixes like this a patch file and a `git apply` are much simpler to generate/use than a zip file and its easier to see the changes. But if you prefer zip files, here you go: [fixed-link-meteor-repair-tools.zip](https://github.com/wekan/wekan/files/9597799/fixed-link-meteor-repair-tools.zip) :slightly_smiling_face:

**Comment by xet7** [comment]
@BlobbyBob 

Thanks! I added those changes to  https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file#2-if-you-dont-have-meteor-1601-installed-download-it-to-your-home-directory-and-unarchive-it
