### ISSUE TITLE
languange italian is done 25%?

### ISSUE THREAD

**Issue by manuelsongokuh** [wekan/wekan#470]
/i18n/it.i18n.json

i see language italian make done till 25%...?

i can call my firend to help translate 100%?

**Comment by mquandalle** [comment]
Translations happen on Transifex, Italian translators can join the team here: https://www.transifex.com/wekan/wekan/

**Comment by manuelsongokuh** [comment]
ok thank you i will call my friend ok?

**Comment by mquandalle** [comment]
Well, do what you want :)

**Comment by manuelsongokuh** [comment]
i did send my friend and wait to reply to my email ok?

thank you

**Comment by manuelsongokuh** [comment]
hi @mquandalle 
languange italian is finish 100%! finally, that is for my office job using wekan for italian full!! thank you

i will waiting for calendar for wekan ok? thank you!

**Comment by manuelsongokuh** [comment]
hi
i check file : 
https://github.com/wekan/wekan/blob/devel/i18n/it.i18n.json
is not updated.. maybe will later..?
