### ISSUE TITLE
Persistent Volumes

### ISSUE THREAD

**Issue by CaptainPackers** [wekan/wekan#4702]
Is there a way to modify the docker-compose.yml file to use persistent volumes?
I tried, for example, to modify 
```
volumes:
  - wekan-db:/data/db`
```
to 
```volumes:
  - ./wekan-db:/data/db
```
and then comment out the local driver volume at the end of the file, however, the application then becomes unreachable via my web browser and ``$ docker ps`` shows that it is in a continuous state of restarting, so I suspect something is going on in the container where the application isn't able to find or access the /data/db volume so it never completes the start up process.

Thanks

**Comment by xet7** [comment]
I would think that it is already persistent volume. It just has name wekan-db. I could be wrong, I'm not docker expert.

**Comment by gu1ll0me** [comment]
xet7 is right. Both syntax creates persistent volume. `wekan-db:/data/db` create a volume managed by Docker in `/var/lib/docker/volumes` (`docker volume ls` will show the volume) and `./wekan-db:/data/db` is a bind mount, non-managed by Docker (`docker volume ls` will not show the volume) and it will create/use a folder named `wekan-db` in the same directory that your docker-compose file.

To debug why your container is restarting continually, use `docker logs [your container name]` to show the log messages.

**Comment by xet7** [comment]
If some volume paths are changed to be incorrect, WeKan will not work. I would recommend changing back to original volume settings.
