### ISSUE TITLE
Wekan 6.50 Crash : The "path" argument must be of type string

### ISSUE THREAD

**Issue by knacky34** [wekan/wekan#4704]
I've upgraded to Wekan 6.50 from 6.09 and I can't start the service.

## Server Setup Information
* Wekan Version: 6.50
* root-url configured correctly
* Operating System: arch-linux
* Deployment Method: bundle
* Node.js Version: 14.20.0
* MongoDB Version: 5.0.6

### Environment variables
```
MONGO_URL='mongodb://user:password@address:port/databasName'
ROOT_URL='http://address'
PORT=httpPort
#MAIL_URL='smtp://user:password@mailhost:port/'  <- I don't have mail server running, it didn't create any issues in older releases
```

## Problem description
Service crashes when started.

### Logs
```
/opt/wekan/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at module (models/attachments.js:40:22)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/opt/wekan/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (server/publications/attachments.js:1:24)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /opt/wekan/bundle/programs/server/app/app.js:168756:1
    at /opt/wekan/bundle/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /opt/wekan/bundle/programs/server/boot.js:226:21
    at /opt/wekan/bundle/programs/server/boot.js:464:7
    at Function.run (/opt/wekan/bundle/programs/server/profile.js:280:14)
    at /opt/wekan/bundle/programs/server/boot.js:463:13 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by xet7** [comment]
Try without quotes on those ROOT_URL etc

**Comment by knacky34** [comment]
Thanks @xet7 but It didn't solve the issue

**Comment by xet7** [comment]
Can you try docker-compose.yml from https://github.com/wekan/wekan or Snap Candidate?

**Comment by knacky34** [comment]
I tried using docker-compose and I can't get it works : the docker container starts, no errors but when checking on browser I've blank page.
When the service is not started I get 502 error from the nginx server.

**Comment by xet7** [comment]
@knacky34 

## Nginx attachment file size

https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config#attachment-file-size

## Websockets

https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config#nginx-webserver-configs

## ROOT_URL

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L172
```
ROOT_URL=https://wekan.example.com
```

## PORT

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L152
```
- 3001:8080
```

**Comment by knacky34** [comment]
I fix my configuration for the Docker version according to your comment but it still doesn't work (blank page).
I also tried to run the standalone version with a fresh mongo database but I got the same error.

**Comment by knacky34** [comment]
I tried version 6.23 and 6.28 of Wekan, same error.
I would try an earlier version, before node v14 and Meteor v2.7 but I could not find the binaries for Wekan 6.21 and 6.22

**Comment by knacky34** [comment]
I finally fixed the issue using the start script provided in the repo. I think some mandatory variables were not exported.
Wekan 6.53 is running.

**Comment by xet7** [comment]
Great !

**Comment by GastroGeek** [comment]
For posterity - as I had this exact issue and wanted to know what specifically was missing (since I use my own script in the root folder):

```bash
export MONGO_URL=
export ROOT_URL=
export MAIL_URL=
export MAIL_FROM=
export PORT=

# just adding this next line, verbatim fixed it
export WRITABLE_PATH=..
```

🥳

**Comment by knacky34** [comment]
Good job @GastroGeek !
Could you add `WRITABLE_PATH=..` to `bundle/README` @xet7 ?

**Comment by xet7** [comment]
@knacky34 

There is already info about most important environment settings like WRITABLE_PATH and permission for node binding to port 80 at https://github.com/wekan/wekan/wiki/Raspberry-Pi
