### ISSUE TITLE
Unable to download attachments after migrating Wekan to Ubuntu 22.04 Server 

### ISSUE THREAD

**Issue by CaptainPackers** [wekan/wekan#4705]
I had issues with my Ubuntu 20.04 Server not booting up after trying the release upgrade to 22.04, so I created a new 22.04 Sever (VirtualBox VM) and migrated Wekan to the new server. Everything seem to be working fine except that I am unable to download attachments. I can upload them, but I can't download them. I get this:

This site can’t be reached 192.168.xx.xx refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

The URL is 

http://192.168.xx.xx/cdn/storage/attachments/Q4sbZY67uZv3pxKrS/original/Q4sbZY67uZv3pxKrS.xlsx?download=true

Wekan version is

WeKan ® info | 6.49.0
-- | --
Meteor_version | 2.7.3
Node_version | 14.20.0
MongoDB_version | 6.0.1

Any ideas on what I can/should do to correct this? I really did enjoy this feature when it was working on my 20.04 Server.

Thanks

**Comment by CaptainPackers** [comment]
I think this may be related to the fact that I selected the option to set up docker during the server installation and docker was set up as a snap. Now /var/lib/docker is buried in /var/snap/docker/common as directory var-lib-docker with 710 permission and owned by root:root. I'm starting to think trying to migrate to 22.04 was a mistake. Nothing seems to work anymore. Maybe I migrated too soon.

**Comment by CaptainPackers** [comment]
Has the delete card option been removed from the latest version of Wekan? I used to be able to delete a single card, but can no longer find that option. Is it the new server? Is it the new version of Wekan? In v.5.84.0 which I was running on 20.04 I had the option to delete a card.

Also, in 6.49.0 on 22.04, the option to scroll right when I open a card to edit it does not function properly. I have to increase the size of my browser window to be able to edit the card.

**Comment by xet7** [comment]
@CaptainPackers 

If you like to try newest WeKan, easiest is with Snap Candidate:
```
sudo snap install wekan --channel=latest/candidate
```
https://github.com/wekan/wekan-snap/wiki/Install

Delete card is available for BoardAdmins #3377 

When opening card, there is at card popup top right button that can maximize card. Does that help? Or do you mean this bug #4572 ?

Well, if you install Docker with Snap etc that goes way too complex. Docker is quite compex tech.

I do use Ubuntu 22.04 based distros when developing WeKan.
