### ISSUE TITLE
adding attachments error:no such file or directory, mkdir in windows wekan bundle

### ISSUE THREAD

**Issue by gforcelong** [wekan/wekan#4707]
### Server Setup Information

* Did you test in newest Wekan?:yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?:yes
* Operating System:windows10
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:14.20
* MongoDB Version:5.0.12
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Microsoft Edge 105

#### Reproduction Steps
when adding attachements to card, cmd log show error :

Exception in callback of async function: Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (fs.js:1014:3)
    at packages/ostrio:files/write-stream.js:47:16
    at packages/ostrio:files/write-stream.js:10:50
    at runWithEnvironment (packages\meteor.js:1320:24) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT

and the attachments didn't seem to upload to card:
![image](https://user-images.githubusercontent.com/20057180/192915686-9689a959-0a90-44ae-9801-0cba481373dc.png)

## start-wekan.bat settings:
SET ROOT_URL=http://10.10.53.36
SET PORT=80
SET MONGO_URL=mongodb://10.10.53.36:27017/wekan
SET WRITABLE_PATH=..

#### Logs

Exception in callback of async function: Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (fs.js:1014:3)
    at packages/ostrio:files/write-stream.js:47:16
    at packages/ostrio:files/write-stream.js:10:50
    at runWithEnvironment (packages\meteor.js:1320:24) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT

**Comment by xet7** [comment]
@mfilser @helioguardabaxo 

Do you know why Node.js 14.20.1 can not create directories attachments and avatars to WRITABLE_PATH on Windows? Is there some new change somewhere?

**Comment by xet7** [comment]
I also try to fix this.

**Comment by xet7** [comment]
That bundle does work on Linux with that setting `WRITABLE_PATH=..`, but not anymore on Windows with this new Node.js version 14.20.1

**Comment by mfilser** [comment]
@xet7
I don't have any idea of this "Windows" bug. I also don't use Windows,so i can't look at it.

**Comment by xet7** [comment]
@gforcelong 

Please try newest WeKan, does it work better? https://github.com/wekan/wekan/releases

**Comment by gforcelong** [comment]
> 

tried ,but with no luck,

**Comment by gforcelong** [comment]
> @xet7
> 
> tried ,but with no luck,
> 
> > @gforcelong
> > Please try newest WeKan, does it work better? https://github.com/wekan/wekan/releases

 i tried wekan 6.54,but it had the same error message,did i missing something? like settings or thirdparty pacakges?

**Comment by xet7** [comment]
@gforcelong 

While this bundle bug still exists (I presume), it's possible to use working docker-compose.yml from https://github.com/wekan/wekan on Windows.

**Comment by xet7** [comment]
Is this same issue like here? Maybe try something similar?

- https://github.com/veliovgroup/Meteor-Files/issues/857
- https://github.com/veliovgroup/Meteor-Files/commit/4f58852a9fa63e068479acd6cea758c021e86a62

**Comment by xet7** [comment]
Hmm? It seems it's exactly the same error message, with solution to upgrade to `ostrio:files@2.3.2`, and WeKan is already upgraded to that version. I'll try does this error happen anymore.
