### ISSUE TITLE
No Gantt chart in public view

### ISSUE THREAD

**Issue by GammaPi** [wekan/wekan#4709]
## Issue
When opening gantt chart view in board page. I see errors in browser debug panel.

### Server Setup Information
* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?: Yes
* Operating System: Ubuntu 20.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?: Firefox

### Problem description
See logs.

#### Reproduction Steps
Create a public board
Open that link and switch to gantt chart.

#### Logs

![image](https://user-images.githubusercontent.com/19838874/193329222-8e3c2c38-ccbe-491f-bb63-9af9dbe9d34c.png)

**Comment by xet7** [comment]
Yes, Gantt feature is broken on WeKan Gantt GPL version. I presume that I (or someone else) will make MIT licensed Gantt feature to WeKan MIT license version sometime in the future.

Related #2870

**Comment by GammaPi** [comment]
Got it. Is this on the roadmap already?

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2870#issuecomment-1267020057
