### ISSUE TITLE
Add a card button not working

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#471]
Just set it up and there seems to be a bug with the add a card button. we've confirmed our accounts, but when clicking the button nothing at all happens.

console returns this error:

9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:405 Uncaught TypeError: Cannot read property 'members' of undefinedBlazeComponent.extendComponent.addCard @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:405(anonymous function) @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:252(anonymous function) @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:252d._withCurrentView @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:54(anonymous function) @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:252e._withTemplateInstanceFunc @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:55G @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:252r.(anonymous function) @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:252(anonymous function) @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:54d._withCurrentView @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:54(anonymous function) @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:54(anonymous function) @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:54ie.event.dispatch @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:25g.handle @ 9128326d32128ecbb977e0b0194593c21e19d9c1.js?meteor_js_resource=true:25

**Comment by AndyatFocallocal** [comment]
i put it in a photo as well if the lack of formatting makes it difficult to read: http://imgur.com/vknjXUF

**Comment by mquandalle** [comment]
What installation process did you follow? I suspect you are not running on the latest stable release.

**Comment by AndyatFocallocal** [comment]
the guy who set it up has logged off for the night. he struggled to set it up untll i mentioned that you had 1 click set ups on Sandstorm and Heroku, so i suspect he used one of those - although i wont be able to find out until tomorrow.

**Comment by AndyatFocallocal** [comment]
(and thanks for your quick reply)

**Comment by AndyatFocallocal** [comment]
not to worry, we set it up from the development code sorry
