### ISSUE TITLE
[Bug] Wekan 6.53 : Text are not displayed correctly

### ISSUE THREAD

**Issue by knacky34** [wekan/wekan#4727]
I've upgraded to Wekan 6.53 from 6.09 and the texts are weirdly displayed, It seems these are placeholders.

## Server Setup Information
* Wekan Version: 6.53
* root-url configured correctly
* Operating System: arch-linux
* Deployment Method: bundle
* Node.js Version: 14.19.3
* MongoDB Version: 5.0.6

### Environment variables
```
MONGO_URL='mongodb://***'
WRITABLE_PATH=..
ROOT_URL='http://***'
MAIL_URL='smtp://user:pass@mailserver.example.com:25/'        # Don't have mail server configured
MAIL_FROM='Wekan Boards <info@example.com>'
PORT=80
WITH_API='true'
RICHER_CARD_COMMENT_EDITOR=false
CARD_OPENED_WEBHOOK_ENABLED=false
BIGEVENTS_PATTERN=NONE
BROWSER_POLICY_ENABLED=true
TRUSTED_URL=''
WEBHOOKS_ATTRIBUTES=''
LDAP_BACKGROUND_SYNC_INTERVAL=''
NODE_OPTIONS="--max_old_space_size=4096"
```

## Problem description
Wekan is working normally except texts aren't displayed correctly.

![Wrong texts displayed](https://i.imgur.com/f5extgg.png)

### Logs
No logs.

**Comment by xet7** [comment]
@knacky34 

In Environment variables, when there is no space, do not add quotes, remove quotes:
```
ROOT_URL=http://wekan.example.com
```
Only use quotes when there is space:
```
MAIL_FROM='Wekan Boards <info@example.com>'
```
In browser settings, only have one webpage language https://github.com/wekan/wekan/issues/4518#issuecomment-1133763518
