### ISSUE TITLE
Adding a Swimlane to a board without swimlanes

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4733]
Maybe I am just not finding it, but I am not able to create a swimlane, if there is not at least one swimlane on the board. 
So when I wanted to add a swimlane to a board without swimlanes, I couldn't find an option to do so.
Thanks!

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5635 . Thanks to @NadavTasher !
