### ISSUE TITLE
Desktop Drag Handle setting moved to top-left corner

### ISSUE THREAD

**Issue by hatl** [wekan/wekan#4734]
### Server Setup Information
Wekan v6.54.0

### Problem description

"Show Desktop drag handles" is gone from settings menu:

![image](https://user-images.githubusercontent.com/70505/198299023-9bc15caf-3e3e-4bfd-83f9-bf409961026a.png)

Now permanently visible in top-left corner:

![image](https://user-images.githubusercontent.com/70505/198299361-bd12a3af-b880-4ddc-a840-dc30e0786631.png)

Was this an intentional change or should it be part of the settings menu?

**Comment by xet7** [comment]
@hatl 

Intentional in [WeKan v6.54](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v654-2022-10-24-wekan--release). It fixes this problem at #4715 

> I've got a notebook with a touch screen and have 2 external screens connected.
> Which makes it impossible to disable the drag handles if only one of your screens is touch-enabled.

It is fixed this way in this way in [WeKan v6.54](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v654-2022-10-24-wekan--release):

> Drag handle toggle at top left. Each touch/non-touch screen can use different setting, because it's saved to browser localstorage, not database. For example, when using Firefox Multi-Account Containers AddOn, different browsers etc, when logged in as same user. [Part 1](https://github.com/wekan/wekan/commit/e214bc55dcfd685c96311da7c2226cfb96208fca), [Part 2](https://github.com/wekan/wekan/commit/7e5e29cacb90e6eb01f34baad2b6dec9adb0ad4a). Thanks to hatl and xet7.
