### ISSUE TITLE
BUG: Creating a "Link card" gives a Javascript error

### ISSUE THREAD

**Issue by hpvb** [wekan/wekan#4742]
## Issue
Pressing the "Link card" button does not work.

### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Fedora 36
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 14.20.1
* MongoDB Version: 5.0.13
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox and Chromium

### Problem description

![image](https://user-images.githubusercontent.com/2591099/199102260-4f4b29b0-971f-4de9-acef-2b0f7a531164.png)

#### Reproduction Steps

Press the "Link card" button on any card

#### Logs
No errors appear in either Javascript console or the docker console.

**Comment by xet7** [comment]
That error means, that board `^Backlog^` does not have any swimlanes.

Related #4733

**Comment by hpvb** [comment]
The 'queue' and 'card' pulldowns also don't get populated with meaningful data it seems though? Maybe I'm misunderstanding how this is SUPPOSED to work though :)

**Comment by xet7** [comment]
Yes, that error `key 'default (en)' returned an object instead` is same that is shown when someone deletes last swimlane of board. Solution would be to add button that adds new swimlane to that board. I tried to add that button, but did not get it working yet.

Sure it would be possible to directly insert Swimlane to database, but it's not so user friendly.

**Comment by xet7** [comment]
Hmm, just thinking. If some board does not have swimlane, maybe if it would be added automatically?

**Comment by xet7** [comment]
It seems, that when adding subtask, it adds new swimlane to `^Subtask Board^`, but without any swimlane name. I'll look could I add some swimlane names by default.

**Comment by hpvb** [comment]
In the situation I'm in there is one swimlane, the 'default' one. Again, maybe I'm misunderstanding what this is SUPPOSED to do. I was expecting to be able to link to cards on other boards. But that appears to not be possible?

**Comment by xet7** [comment]
@hpvb 

Linked cards is used to show content of card at other boards. For example, you can have Dashboard board, where are Linked cards from all other boards, to show status of everything at Dashboard.

Usually Linked cards are created at Boards. I did just test, that creating Linked card on Subtask board does also work.

At Subtask board, if some Swimlane does not have name (so it shows that funny error message), it's possible to rename Swimlane to have some better name. That would make also easier to select correct Swimlane in that popup. I would think showing that error message is just cosmetic, I would presume it would not prevent something from working.

**Comment by xet7** [comment]
@hpvb 

Linked cards was originally added here https://github.com/wekan/wekan/pull/1592

Related bug was fixed here https://github.com/wekan/wekan/pull/3547

Subtasks was originally added here https://github.com/wekan/wekan/pull/1723

Subtasks Docs https://github.com/wekan/wekan/wiki/Subtasks
