### ISSUE TITLE
Docker-compose can not change or select Language 

### ISSUE THREAD

**Issue by xiaoyuesansui** [wekan/wekan#4747]
hey developer 
good day

meet across exactly same problems with #4526 ,and also tried swith to root_URL to localhost or ip address 

also tried #4518 and leave Chinese as only Lanuage in chrome ,but wekan is still showed in English

my wekan is 

WeKan ® info	6.54.0
Meteor_version	2.8.0
Node_version	14.20.1
MongoDB_version	5.0.13
MongoDB_storage_engine	wiredTiger
MongoDB_Oplog_enabled	
OS_Type	Linux
OS_Platform	linux
OS_Arch	x64
OS_Release	5.10.0-19-amd64
OS_Uptime	13 days, 21 hours, 22 minutes, 8 seconds
OS_Loadavg	3.81, 3.41, 3.16
OS_Totalmem	8.34 GB
OS_Freemem	135.24 MB
OS_Cpus	3
Node_heap_total_heap_size	117.66 MB
Node_heap_total_heap_size_executable	835.58 kB
Node_heap_total_physical_size	116.69 MB
Node_heap_total_available_size	4.23 GB
Node_heap_used_heap_size	113.48 MB
Node_heap_heap_size_limit	4.35 GB
Node_heap_malloced_memory	149.17 kB
Node_heap_peak_malloced_memory	4.08 MB
Node_heap_does_zap_garbage	0
Node_heap_number_of_native_contexts	2
Node_heap_number_of_detached_contexts	0
Node_memory_usage_rss	182.81 MB
Node_memory_usage_heap_total	117.66 MB
Node_memory_usage_heap_used	113.49 MB
Node_memory_usage_external	69.14 MB

**Comment by leonyannnick** [comment]
hi, 
i have an revers proxy in front of wekan, and changed the root-url to the domain, to which wekan is forwarded to. 
Since that, everything is working fine. 

a little workaround: 
v6.22 was the last Version, where the problem with **wrong root_url ending up in issues** wasnt there. I've tried **all** versions, believe me :D

**Comment by xet7** [comment]
Have you tried ROOT_URL examples at https://github.com/wekan/wekan/wiki/Settings ?
