### ISSUE TITLE
Error: Cannot find module '/imports/i18n/data/es.i18n.json'

### ISSUE THREAD

**Issue by enekux** [wekan/wekan#4749]
Hi we have detected an issue with the Language display after upgrading Wekan from version v6.22 onwards. The site does not show properly the strings. Also if we deploy the latest version of Wekan we see the same behaviour, and the error is the next:

![image](https://user-images.githubusercontent.com/3785138/201081430-8e69976c-2770-4942-b68c-bcf09042719d.png)

Looks like something is broken with Language display from v6.22 onwards, could it be related to this change maybe in the v6.23 release?

![image](https://user-images.githubusercontent.com/3785138/201082255-60ad623d-b83d-4583-9413-63701ef76592.png)

Thank you

**Comment by xet7** [comment]
see https://github.com/wekan/wekan/discussions/4753#discussioncomment-4198577
