### ISSUE TITLE
Bug: Swimlane title in subtask board is not set properly.

### ISSUE THREAD

**Issue by titho85** [wekan/wekan#4763]
## Issue
When a subtask board is created, the swimlane title says "key 'default (en)' returned an object instead of string.". The same happens when switching to other languages (e.g. German) >  "key 'default (de)' returned an object instead of string.".

### Server Setup Information
* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Rocky Linux 8
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker Swarm
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): 3 (only Wekan, no SSL, different port)
* Node.js Version: 14.21.1
* MongoDB Version: 5.0.14
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Google Chrome

### Problem description
When a subtask board is created, the swimlane title says "key 'default (en)' returned an object instead of string.". The same happens when switching to other languages (e.g. German) >  "key 'default (de)' returned an object instead of string.".
#### Reproduction Steps
1. Add Board
2. Add List
3. Add Card
4. Click on card
5. Click on + under "Subtasks" create a subtask (text + ENTER)
6. Click on hamburger menu and then "View it" > nothing happens (see Issue #4762)
7. Reload page
8. Click on "View it" under "Subtasks"
9. Subtask board is opened with swimlane title "key 'default (en)' returned an object instead of string."

#### Logs
No logs or errors visible.

**Comment by titho85** [comment]
Thanks for mentioning. We have that issue at least since 6.11 but never bothered to open up an issue. So I didn't catch that in the meantime there was a related issue.
And by the way a solution for us would also be to just deactivate subtask feature for all new boards in administration if there was such an option.

**Comment by xet7** [comment]
@titho85 

There is setting at `Board Settings` / `Card Settings` / `[_] Subtasks`.

There is not yet global setting at `Admin Panel`.

**Comment by titho85** [comment]
Thanks, I was aware of that option. But unfortunately with thousands of users and boards created daily there is no chance for "educating" every user/board creator.
