### ISSUE TITLE
Ubuntu 20.04.5 docker 20.10.12 - can not update to wekan v6.60

### ISSUE THREAD

**Issue by intellekta** [wekan/wekan#4765]
## Issue 
can not update to wekan v6.60

### Server Setup Information
Ubuntu 20.04.5 
docker 20.10.12

### Problem description
**Administration - Version (wekan stays on 6.09)**
WeKan ® Version | 6.09.0
Meteor 2.2
Node 12.22.10
Mongo 3.2.21 wiredTiger
#### Reproduction Steps
- machine:/docker/wekan-wdc$ `sudo docker-compose stop`
  *Stopping wekan-app-wdc ... done*
  *Stopping wekan-db-wdc  ... done*
- machine:/docker/wekan-wdc$ sudo `docker-compose rm -f`
  *Going to remove wekan-app-wdc, wekan-db-wdc*
  *Removing wekan-app-wdc ... done*
  *Removing wekan-db-wdc  ... done*
- machine:/docker/wekan-wdc$ `sudo docker-compose pull wekanteam/wekan:v6.60`
  *v6.60: Pulling from wekanteam/wekan*
  *Digest: sha256:4d5cc0d1f1b0ff187411a4ba0c6f18efb49f9f915cf08e23214c5ba567c2df96*
  *Status: Image is up to date for wekanteam/wekan:v6.60*
  *docker.io/wekanteam/wekan:v6.60*
- machine:/docker/wekan-wdc$ `sudo docker-compose -f docker-compose.yml up -d`
  *Creating wekan-db-wdc ... done*
  *Creating wekan-app-wdc ... done*

**Comment by xet7** [comment]
@intellekta

Did you first create backup? https://github.com/wekan/wekan/wiki/Backup

For newest version, did you use newest docker-compose.yml from https://github.com/wekan/wekan that has required WRITABLE_PATH etc, and then restored like mentioned at https://github.com/wekan/wekan/wiki/Backup ?

**Comment by intellekta** [comment]
@xet7 
1. now i did a backup as described.
2. take the newest docker-compose.yml and change it to our settigs
3. docker-compose -f docker-compose.yml up -d
4. ... it installs a mongo:5  
5. then i did a restore as described
6. docker exec wekan-db-wdc rm -rf /data/dump
Result: Error response from daemon: Container 75f2e703e054 is restarting, wait until the container is running

**Comment by intellekta** [comment]
@xet7 
1) Server has 8GB RAM
~~~
        KB total      occupied   free       shared   intermediate  available
Memory:    6.052.928  2.038.400    187.288  29.932   3.827.240     3.704.692
Outsource: 1.459.804      9.788  1.450.016
~~~

2) i have 3 wekan boards and 1 nginx container

3) docker start wekan-db wekan-app 
starts the container but on the web site i got **502 Bad Gateway**
the other two wekan boards are runnig fine

PS: in my other wekan-db the mongo ist v3.x maybe the newer 5.x is not komatible ?

**Comment by xet7** [comment]
@intellekta

Newest WeKan is only compatible with MongoDB 5.x

**Comment by intellekta** [comment]
@xet7 
oh, i mean "is mongo 5 kompatible with the old mongo 3 database?"

**Comment by intellekta** [comment]
i go back to 
- image: wekanteam/wekan:v6.09
- image: mongo:3.2.21

and restore the last dump, that works.
don´t know, how iKan go to the Newest WeKan
