### ISSUE TITLE
Admin user overview broken 

### ISSUE THREAD

**Issue by tograss** [wekan/wekan#4766]
### Server Setup Information
* Did you test in newest Wekan?: Yes 6.60
* Operating System: Debian Bullseye
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node.js Version:
* MongoDB Version: 5
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Chrome

### Problem description
The user list in the admin area is broken. When first accessing the page it shows 106 users (which is an impossible number). After a reload the user number drops to 26. Which is still wrong.

#### Reproduction Steps
I'm not sure. I suspect it has something to do with the recently added ldap-sync . The majority of our users are ldap users. I expect quite a few where removed and might still left some traces in the database.

#### Logs
js console:
``
a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583 WebSocket connection to 'wss://xxx/sockjs/683/_wh_4a79/websocket' failed: 
k.websocket @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
k._try_next_protocol @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
k._didClose @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
o._ir.onfinish @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
i.emit @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
i.onfinish @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
i.emit @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
s.xhr.onreadystatechange @ a95e051377a14e1255025567e60dcbc4c30b02e6.js?meteor_js_resource=true:583
``
Docker logs
<code>
Exception in onConnection callback: TypeError: Cannot read property 'userId' of null
    at server/publications/users.js:123:44
    at Array.forEach (<anonymous>)
    at server/publications/users.js:118:46
    at runWithEnvironment (packages/meteor.js:1347:24)
    at packages/meteor.js:1360:14
    at packages/ddp-server/livedata_server.js:1614:9
    at Hook.forEach (packages/callback-hook/hook.js:110:15)
    at Hook.each (packages/callback-hook/hook.js:122:17)
    at Server._handleConnect (packages/ddp-server/livedata_server.js:1612:27)
    at packages/ddp-server/livedata_server.js:1496:18
</code>
Thanks in advance for any help.

**Comment by dvschuetz** [comment]
similar: https://github.com/wekan/wekan/issues/4897
