### ISSUE TITLE
Bug: Imported  from wekan.csv can't create cards

### ISSUE THREAD

**Issue by jiangfangfangxm** [wekan/wekan#4769]
### Server Setup Information

* Did you test in newest Wekan?:
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
My enviorment:
 I use the sandstorm demo app : [Sandstorm app demo](https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h),

### Problem description

I try to create a board by using the function import from CSV. 
I used the CSV file from https://github.com/wekan/wekan/wiki/CSV [CSV](https://raw.githubusercontent.com/brymut/github-gifs/master/wekan%3Awekan%3Aissues%3A395/board-import.csv)
the board was created successed, but the cards havn't been created. 
#### Reproduction Steps
1. create a board
<img width="1769" alt="clipboard" src="https://user-images.githubusercontent.com/45526589/206894407-9cea5e39-6296-4e80-ab0d-bd964cff88a7.png">
2. import from CSV
<img width="370" alt="clipboard" src="https://user-images.githubusercontent.com/45526589/206894331-2365aa04-46b4-44a2-a7c6-ad5a841cf3d0.png">

3. pasted from the sample  CSV file  from  [CSV](https://raw.githubusercontent.com/brymut/github-gifs/master/wekan%3Awekan%3Aissues%3A395/board-import.csv)

<img width="1770" alt="clipboard" src="https://user-images.githubusercontent.com/45526589/206894312-04383502-d0a7-48e2-8f68-0418fb87ef5f.png">

<img width="869" alt="clipboard" src="https://user-images.githubusercontent.com/45526589/206894282-6066a535-85fa-4e06-b501-91aaff1c8843.png">
5. the board created without the cards
<img width="1770" alt="clipboard" src="https://user-images.githubusercontent.com/45526589/206894355-d9ebcc68-7f3a-4871-9a19-19084779e482.png">

I also test it in my stand alone verson. it is the same. 
I found:
1. I can't import the exported wekan.csv  from wekan directorly . I　found that the exported file use the name "list" ,but the imported file use the name "stage"  for "column".
2. by reading the program [csvCreator.js](https://github.com/wekan/wekan/blob/master/models/csvCreator.js), I guess the import from CSV only create the default swimlane, maybe I am wrong.

**Comment by xet7** [comment]
@commonist 

Is that Javascript import code too difficult to understand for some contibutor to fix? Would it help if it was instead using Basic programming language?

**Comment by xet7** [comment]
@commonist 

What kind of CSV format that file is? What fields? What separator? Any anonymized example?

**Comment by commonist** [comment]
> @commonist
> 
> Is that Javascript import code too difficult to understand for some contributor to fix? Would it help if it was instead using Basic programming language?

Funny question... ^^ I guess, Javascript is okay. Nevertheless contributing might depend on more factors like setting up the dev environment, testing etc.

**Comment by commonist** [comment]
> @commonist
> 
> What kind of CSV format that file is? What fields? What separator? Any anonymized example?

As pointed out in the bug report even the example CSV file does not work. I think the simple use case should work first. (I figured that out after a long run of testing with my own data until a starting using very simple test cases end ended up using the sample file, which failed. Then I stopped testing.)

**Comment by helioguardabaxo** [comment]
Hi, @commonist @jiangfangfangxm  @xet7 !

I tested CSV cite above. If you try to import lines with "empty" values on date fields this bug occurs.
I select just header, card 1, card 2 and card 7 lines and works fine.

**Comment by helioguardabaxo** [comment]
For example, when 'start date' value is empty, the code set it value like Null
https://github.com/wekan/wekan/blob/cfbb06ed1f94f92e618bfcbd49b8b0f06c53d88f/models/csvCreator.js#L299C19-L299C19

**Comment by helioguardabaxo** [comment]
If you create a new card without 'start date' via app (not via csv import) this field is not create in database.

**Comment by xet7** [comment]
@helioguardabaxo 

Can you send PR to fix it?

**Comment by commonist** [comment]
> Hi, @commonist @jiangfangfangxm @xet7 !
> 
> I tested CSV cite above. If you try to import lines with "empty" values on date fields this bug occurs. I select just header, card 1, card 2 and card 7 lines and works fine.

Thanks for your support, I really appreciate it! 

I tested line 1 and card 1 and it didn't work. The board was created with one column but no card. Then I tested with line 1, card 1 and card 2. Same, except, two columns were created. 

I can provide the wekan version later.

**Comment by helioguardabaxo** [comment]
@commonist
I tried to fix this bug.
When this fix is release, give me a feedback.

**Comment by commonist** [comment]
Greate, @helioguardabaxo! 

To be clear: I tried to follow your workaround:

> "I select just header, card 1, card 2 and card 7 lines and works fine." 

But for me it did not work. Thus, I'm not sure if fixing the date fields will solve the problem. I'm running version 6.09.

**Comment by xet7** [comment]
@commonist 

You do not have that fix yet, that is why it does not work for you yet. That fix will be in newest WeKan I will release soon.

Your old 6.09 will upgrade automatically to newest WeKan, when we have figured out how to keep attachments visible: https://github.com/wekan/wekan/issues/4780#issuecomment-1626401785

**Comment by xet7** [comment]
@commonist 

When I tested fix from @helioguardabaxo before making release, after importing that test CSV file it looks like this:

![WekanCSV](https://github.com/wekan/wekan/assets/15545/55d69c97-94d1-46f4-849a-f2b3ad4fb89f)

**Comment by commonist** [comment]
> @commonist
> 
> You do not have that fix yet, that is why it does not work for you yet. That fix will be in newest WeKan I will release soon.
> 
> Your old 6.09 will upgrade automatically to newest WeKan, when we have figured out how to keep attachments visible: [#4780 (comment)](https://github.com/wekan/wekan/issues/4780#issuecomment-1626401785)

Maybe I understood it wrong. For me the fix and the workaround are two different things. I know the fix needs to be released. The workaround, though, seems to be to define the date fields manually. @helioguardabaxo said that testing with cards 1, 2, and 7 works fine **without** the fix. 

Nevertheless, I'm looking forward to the new release! Thank you so far :-)

**Comment by helioguardabaxo** [comment]
@commonist 
I made a mistake.
I tested after change a call to function below:
Cards.direct.insert(cardToCreate);
