### ISSUE TITLE
API call to /users/login returns "error": "internal-server-error"

### ISSUE THREAD

**Issue by WassimDhib** [wekan/wekan#4771]
Hi

I just installed the wekan v6.60 ( docker compose method)

The API /users/login does not work (it was perfectly working in previous v6.20)

```

curl -X POST http://localhost:80/users/login -d "username=admin&password=123456"   -H 'Content-Type: application/x-www-form-urlencoded'    -H 'Accept: */*'

{
  "error": "internal-server-error",
  "reason": "Internal server error"
* STATE: PERFORM => DONE handle 0x203d0738; line 1980 (connection #0)
* multi_done
* Connection #0 to host localhost left intact
* Expire cleared
}   
```

**Comment by WassimDhib** [comment]
The problem first appeared in [v6.23](https://github.com/wekan/wekan/releases/tag/v6.23)  version

**Comment by xet7** [comment]
There was some API code changes https://github.com/wekan/wekan/issues/4528

Those have been updated to Python3 example api.py at https://github.com/wekan/wekan

**Comment by xet7** [comment]
It should work in newest WeKan
