### ISSUE TITLE
[Bug (Feature?)] Enforce whole digits when numbering

### ISSUE THREAD

**Issue by norrig** [wekan/wekan#4784]
## Issue/Feature?
Not sure if intended or not

### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: AlmaLinux
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Default snap settings
* Node.js Version: Default snap settings
* MongoDB Version: Default snap settings
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Chrome

### Problem description
Is there any way we can force whole digits when numbering? I'm not sure how it happens, but when working with large boards, they often end up with ID's/numbers that aren't useful, see image:
![image](https://user-images.githubusercontent.com/5526261/209136611-f8d2c997-6405-4e24-a9aa-3ba52f902550.png)

Is it a bug or intended behavior? If intended, can we possibly get a setting that forces whole numbers only. 
If it's a bug, let me know if you need logs/additional info.

I use the numbering to refer to cards, and saying "Check card 7" makes a lot more sense than "Check card 7.375".
I'd ideally like the cards to get a whole, incrementing number on creation and retain that number forever.

Thanks in advance

edit:
Negative numbers can also occur for some reason:
![image](https://user-images.githubusercontent.com/5526261/209140200-e7eee86e-729d-43b1-9228-d1a30fbff873.png)

#### Reproduction Steps

Unsure how it happens, but usually involves a lot of cards and a lot of drag n' dropping the cards around.

#### Logs
Let me know if needed

**Comment by xet7** [comment]
Please change settings:

`Board Settings` / `Card Settings`
```
[_] Card sorting by number
[X] Card number
```
