### ISSUE TITLE
[Feature request] Allow non board-admins with edit rights to create labels

### ISSUE THREAD

**Issue by norrig** [wekan/wekan#4785]
### Server Setup Information
Snap package, fully updated.

### Problem description
Right now, if another person has been added to a board, they cannot create labels. However, they can edit the cards and even delete them and do pretty much everything else. Can we change it so any permitted user (edit-rights) can also create labels?  
 
 Semi-Related: https://github.com/wekan/wekan/issues/1229  

#### Reproduction Steps
- Create a board, add a person with edit rights.
- Invited user can add/delete/edit cards, but can't create labels.

#### Logs
N/A

**Comment by xet7** [comment]
@norrig

Links to code related to those limitations is at https://github.com/wekan/wekan/issues/4276#issue-1093672249

It's possible to remove limitations by sending PR like this https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

Limitations were requested at #3377 

@compumatter @Samunosuke @pgh2357 @PizzaProgram @RyanHecht 

What do you think?

**Comment by xet7** [comment]
@norrig

Are you using Snap Stable or Candidate? Check with command:
```
sudo snap list
```
Info about Candidate at #4780

**Comment by norrig** [comment]
> @norrig
> 
> Are you using Snap Stable or Candidate? Check with command:
> 
> ```
> sudo snap list
> ```
> 
> Info about Candidate at #4780

Currently using **stable**. I'm unable to test candidate release at the moment (Christmas vacation, no access to the backend servers from here)

Overall I consider this more of a bug/unintended behavior, considering the invited users can do pretty much everything but create labels, which seems nonsensical. Ideally the permission to create labels should be included in the permission to edit labels.
