### ISSUE TITLE
 Bug: Adding Users to Groups via OIDC seems to be broken 

### ISSUE THREAD

**Issue by Viehlieb** [wekan/wekan#4786]
### Automatic adding Users to Groups via OIDC seems to be broken in wekan > 6.0
_Reason_: knownUser.js:219 >> onLogin >>  `Meteor.call('groupRoutineOnLogin', loginInfo.user.services.oidc, loginInfo.user._id);` -> Hook does not work.

_Suggestion_: Build logic in oidc-server.js instead of Meteor.call and check for environment variable (propagateOidcData)

Or any better place to add the group routine?
Regards

**Comment by Viehlieb** [comment]
Checkout changes in

https://github.com/wekan/wekan/pull/4788

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4788
