### ISSUE TITLE
card opened display location outside of the screen

### ISSUE THREAD

**Issue by gforcelong** [wekan/wekan#4789]
### Server Setup Information

* Did you test in newest Wekan?:Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System:win10
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:14.20
* MongoDB Version:5.04
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? edge /chrome

### Problem description
when open a card on the side ,the detail content displaying outside of the screen; when test in wekan 6.09 the horizontal scrollbar would  automaticaly  scroll to show the detailed card contents
![image](https://user-images.githubusercontent.com/20057180/209607539-e16bba3d-6fbd-49ab-9b18-7a0753439a23.png)

**Comment by xet7** [comment]
Moved to #4572
