### ISSUE TITLE
404 when serving .js subdirectory 

### ISSUE THREAD

**Issue by tubia** [wekan/wekan#479]
Hi,
I'm trying to run wekan in a subpath. I have set a reverse proxy rule in Apache2 and edited wekan export accordingly:

```
export MONGO_URL='mongodb://127.0.0.1:27017/wekan'
export ROOT_URL='http://example.com/wekan'
export PORT=6000
```

Then when I run it, checking the requests from the browser I see a successfully GET for:
`http://example.com/wekan/f0426bcbeb2093dda4b534ff1a77049c6f346db8.css?meteor_css_resource=true` 
but a 404 for:
`http://example.com/wekan/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true`
If I remove `?meteor_js_resource=true` editing the request from the dev tools in Firefox, I have a 200 response, however it doesn't work. The files are those located here:  `bundle/programs/web.browser`.
Wekan works when started from a path like `wekan.example.com` (of course using a different apache configuration).

Hints on possible solutions?

**Comment by mquandalle** [comment]
You set the port to `6000` but I don’t read it on the URL examples you provide. Is that on purpose? Shouldn’t the `ROOT_URL` be `http://example.com:6000/wekan`? Otherwise if you want to use port 80 you don’t have to set the `PORT` env variable.

**Comment by tubia** [comment]
Hi @mquandalle,
yes, it should be handled by apache.
To explain better I attach my apache conf below:
```apache
ProxyPreserveHost On
ProxyRequests off

SSLProxyEngine on

ProxyPass /wekan http://127.0.0.1:6000/wekan
ProxyPassReverse /wekan http://127.0.0.1:6000/wekan
<Location /wekan>
        SetEnv proxy-initial-not-pooled no
</Location>
```

**Comment by quimnuss** [comment]
Did you ever find the solution for this @tubia ?

**Comment by c25** [comment]
I'd also like to know, I'm having exactly the same issue, and it's been over two years since the OP!

**Comment by xet7** [comment]
@c25

What is the problem? Example Apache config is here:
https://github.com/wekan/wekan/wiki/Apache

And sub urls work with Nginx and Caddy already. This is very old issue.

Generally you proxy from https://example.com/wekan to localhost port like 3000, and setup Wekan ROOT_URL to htts://example.com/wekan and PORT=3000 .

I have not cleaned up all old issues yet.

**Comment by c25** [comment]
@xet7

It's exactly as the OP says, I've got exactly the configuration you decribe using the official docker compose install, with apache on the host.

It could be that apache is too old ... it is on CentOS7 (don't ask :( )
I'll try upgrading apache and see if that resolves the issue.

**Comment by xet7** [comment]
@c25 

I'll check this on CentOS 7, I did not know this is still a problem.

**Comment by c25** [comment]
To confirm, I have the latest apache offered by centos.

I can look at using another source to get the latest, if you think it might be relevant?

**Comment by xet7** [comment]
@c25 

I did not have time to look at Apache yet.

I added CentOS 7 example with Snap and Caddy webserver automatic Let's Encrypt example to:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by aravindhsampath** [comment]
I'm hitting the same issue on CentOS 7... after following your link above as well.
installed snapd as per the wiki,
ran wekan on port 3000
configured nginx to proxy https://aravindh.net/wekan to 127.0.0.1:3000
when I hit the url, it leads to a blank page,
JS console in the browser and the server logs show 404s..

    212.237.134.167 - - [01/Aug/2018:21:09:12 +0000] "GET /wekan/1f4185c81411ca5123e2ae80c0e1051e2f3c3efb.js?meteor_js_resource=true HTTP/2.0" 404 3101 "https://aravindh.net/wekan" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"

Two odd things here.
1. What is that 3101? Did wekan ignore my request to start on port 3000 and try to load assets from 3101?

2. I'm using http/2 by default on nginx. Hope that is not the reason for this mess..

**Comment by xet7** [comment]
@aravindhsampath 

```
sudo snap set wekan root-url='https://aravindh.net/wekan'

sudo snap set wekan port='3000'
```

Also allow websockets in Nginx:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Comment by aravindhsampath** [comment]
Thanks for the response.
I checked the nginx config once again. It is as per wiki except for this `proxy_set_header Connection $connection_upgrade;`line. which throws the error below.
`nginx: [emerg] unknown "connection_upgrade" variable`

I ran without it, I get to 404. 

The websocket line `proxy_set_header Upgrade $http_upgrade; # allow websockets` is in the config. I assume nginx is running with websockets.

**Comment by xet7** [comment]
@aravindhsampath 

You have this missing from Nginx config:
```
# this section is needed to proxy web-socket connections
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
```

**Comment by xet7** [comment]
More info at point 6
https://www.nginx.com/blog/websocket-nginx/

**Comment by aravindhsampath** [comment]
Thanks for the tip. I added the map section now. Now the error about connection_upgrade disappeared and nginx reloaded without errors.

My configuration looks nearly identical to the one in the wiki, but still no luck with getting wekan to work. Same 404 :-( 

Here is my entire nginx site config. 

    map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
    }
    server {
        server_name  aravindh.net www.aravindh.net;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        #charset koi8-r;
        access_log  /var/log/nginx/host.access.log  main;

        root   /var/www/html;
        location / {
                #root   /var/www/html;
                index  index.html index.htm;
        }
	location /wekan {
                proxy_pass http://127.0.0.1:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade; # allow websockets
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
        }
	location ~*  \.(jpg|jpeg|png|gif|ico|css|js|woff2)$ {
                expires 15d;
        }
	location ~*  \.(pdf)$ {
        expires 30d;
        }
	# Dont expose .git directories
        location ~ /\.git {
                deny all;
        }

	# or, all . directories/files in general (including .htaccess, etc)

        location ~ /\. {
                deny all;
        }

	error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
	error_page   500 502 503 504  /50x.html;
        location = /50x.html {
                root   /var/www/html;
        }

	#----- https settings added by certbot -----#
        listen 443 ssl http2 default_server; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/aravindh.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aravindh.net/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        #----- end -----#

        #------GZIP Start------#
        #GZIP Compression
        gzip  on;
        gzip_comp_level 6;
        gzip_vary on;
        gzip_min_length 256;
        gzip_buffers 4 32k;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/css text/x-component application/x-javascript application/javascript text/javascript text/x-js text/richtext image/svg+xml text/plain text/xsd text/xsl text/xml image/x-ico$
        gzip_disable "MSIE [1-6]\.";
        #------GZIP End------#
    }


    server {
        #----- Redirect http to https -----#
        listen 80; # Default listen port
        server_name    aravindh.net www.aravindh.net;
        return 301 https://$server_name$request_uri;
    }

Do you suspect that the 404s are from websocket connections? If so, I'll study more about nginx and websockets..

**Comment by xet7** [comment]
You have so many other denying rules that they are most likely the reason.

I tried to help somebody to combine Nginx config of Drupal website and Wekan sub-url and failed. I mostly use Caddy.

**Comment by xet7** [comment]
Usually I setup Wekan in separate Nginx config file in subdomain, that works better than sub-url.

**Comment by aravindhsampath** [comment]
Yeah. I'm losing patience with this setting. I'll try tomorrow setting wekan up as a separate subdomain, and hopefully it works then. Appreciate your help looking into it!

**Comment by xet7** [comment]
I presume subdomain did work for you.
