### ISSUE TITLE
Enhacement Request: set chunkSize for gridFS

### ISSUE THREAD

**Issue by jltallon** [wekan/wekan#4796]
(untested, as of yet -- more like a suggestion)
Files stored in gridFS --- even if it is temporarily, before being moved elsewhere --- can originate a tremendous amount of chunk-related overhead for big files (e.g. images).

BSON's maximum "blob" size is 16MB, which is obviously excessive. Based on previous experience in other environments, a chunkSize of 2MB seems optimal for the expected usecases.

It might make sense to only change the chunkSize for "attachments" and not for the rest (e.g. 'avatars')

Prototype change follows (please excuse the syntax):

--------------------------------
```
diff --git a/models/lib/grid/createBucket.js b/models/lib/grid/createBucket.js
index d5da5a170..310f470e7 100644
--- a/models/lib/grid/createBucket.js
+++ b/models/lib/grid/createBucket.js
@@ -1,7 +1,9 @@
 import { MongoInternals } from 'meteor/mongo';
 
+const chunkSize = 2048 * 1024;
+
 export const createBucket = bucketName => {
-  const options = bucketName ? { bucketName } : void 0;
+  const options = bucketName ? { bucketName, chunkSize } : void 0;
   return new MongoInternals.NpmModule.GridFSBucket(
     MongoInternals.defaultRemoteCollectionDriver().mongo.db,
     options,
```
----------------------------------------

Thank you in advance

**Comment by mfilser** [comment]
What about existing GridFS? Will this destroy existing GridFS Buckets?
Leaving the chunk size at default size is, as i think, ok.

**Comment by xet7** [comment]
I think it's safer to keep current chunk size.
