### ISSUE TITLE
Docker-Compose.YML + Wekan Visual Issues (Follow-up from #4797

### ISSUE THREAD

**Issue by Mr-Boomo** [wekan/wekan#4799]
## Issue
So I had some visual errors with my Wekan page (text appearing in lowercase and with "-" instead of spaces) along with some actual missing settings in the Admin Panel.
Someone replied with some help regarding what I had in my "docker-compose.yml" file since I use Docker.
I changed the contents accordingly yet my site remains the same.
Is it because the site didn't read the new .yml? I removed the containers various times, resetting new images and building the new containers with them but they remain the same, and anything inside the site that would help me make sure is missing.

Or is it just that the settings are wrong?
In Root_URL i used an actual domain url that does link me to the Wekan page just as the old url address (following the original structure) did.
In Mail_URL I used a gmail account that is open and available, stating the name of it and password in the file so Wekan can have access, the port too.

### Server Setup Information

* Did you test in newest Wekan?:
Yes, it's based off of the newest available image of Wekan
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
Yes, I've followed the example linked by a past commenter
* Operating System:
Linux x65
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
None, just Wekan itself.
* Node.js Version:
14.21.2
* MongoDB Version:
6.0.3
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
Just regular old Google Chrome.

**Comment by xet7** [comment]
@Mr-Boomo 

NOTE:
- Docker/Source/Bundle like this, no quotes, big letters, underscore: `ROOT_URL=http://192.168.0.100`
- Snap like this, single quotes, small letters: `root-url='http://192.168.0.100'`

**Comment by xet7** [comment]
Moved to #4803
