### ISSUE TITLE
Picture cannot be show

### ISSUE THREAD

**Issue by tangjiahao2001** [wekan/wekan#4803]
Hi, Thanks for the software, but I found an error when I used it.
### Use the latest version, use docker-compose.yml .Image uploaded successfully, but cannot display
![image](https://user-images.githubusercontent.com/72953189/211029008-658e30ca-7abc-48e7-9e0e-9b3d80c1c62b.png)

**Comment by xet7** [comment]
In docker-compose.yml, maybe you did not set ROOT_URL ? like:
- ROOT_URL=http://192.168.0.100  (your computer IP address)
- ROOT_URL=http://localhost   (if only your computer locally)
- ROOT_URL=https://wekan.example.com (if you use SSL/TLS at from like Caddy/Nginx/Apache, see wiki)

**Comment by xet7** [comment]
Hmm, I think there are some bugs somewhere:

1. Attachments are only visible after reload of webpage, or move attachment to filesystem (visible) or then back to MongoDB (also then visible). Related #4797 #4802
2. When migrating and moving attachments, createdAt/modifiedAt/updatedAt are lost #4798

**Comment by tangjiahao2001** [comment]
yes, thanks for your reply, @xet7 
### The official demo can't display pictures either, look:
![image](https://user-images.githubusercontent.com/72953189/211125016-62685367-4fe5-450e-a74b-1136818cbaea.png)
![image](https://user-images.githubusercontent.com/72953189/211125148-606e152f-b27e-47ea-9ea5-ed56cb903090.png)


hmm, I also had a bug switching languages, 
### I couldn't switch languages with the latest version of wekan.
![image](https://user-images.githubusercontent.com/72953189/211125320-4cde4c0e-2ad8-4afc-9e89-4a7fb8576f82.png)

**Comment by xet7** [comment]
@tangjiahao2001

Demo board was upgraded too early, some links to images are not correct yet, it needs some fixes.

In newest Docker WeKan setting language and changing language works very well, when ROOT_URL is correct. You still have wrong setting because you have untranslated strings visible like `all-boards`, `sort-cards`. I just have problems how to explain it properly, I don't know could someone else explain it better.

## ROOT_URL

![root-url](https://user-images.githubusercontent.com/15545/211127079-031c2dd9-6f4c-4212-8e0e-07d5f82e9b60.png)

## Working translations in newest WeKan

![lang](https://user-images.githubusercontent.com/15545/211127092-8ba86b8f-b902-48f1-a6a4-967bc4541fe5.png)

## Browser settings need to have only one language

For example,  show WeKan in Japanese, there needs to be only Japanese selected at Firefox Preferences / Choose your preferred language for displaying pages. Delete all other languages from there, there needs to be only Japanese, like this:

<img width="714" alt="wekan-language" src="https://user-images.githubusercontent.com/15545/169667806-88585bbf-4a8d-49ed-a4ad-473cd2a5203b.png">

After that, WeKan is in Japanese:

<img width="583" alt="admin-panel" src="https://user-images.githubusercontent.com/15545/169667820-51ef8368-89ae-4aee-8e93-13a3722f8a98.png">

**Comment by tangjiahao2001** [comment]
Thank you very much for your answer. @xet7  Your answer was excellent. Now all my questions are solved

### language and pictures
![image](https://user-images.githubusercontent.com/72953189/211128206-588df1d1-a61b-405d-8fe2-b1ff3d392f69.png)

best regards! thanks

**Comment by mohammadZahedian** [comment]
> @tangjiahao2001
> 
> Demo board was upgraded too early, some links to images are not correct yet, it needs some fixes.
> 
> In newest Docker WeKan setting language and changing language works very well, when ROOT_URL is correct. You still have wrong setting because you have untranslated strings visible like `all-boards`, `sort-cards`. I just have problems how to explain it properly, I don't know could someone else explain it better.
> 
> ## ROOT_URL
> ![root-url](https://user-images.githubusercontent.com/15545/211127079-031c2dd9-6f4c-4212-8e0e-07d5f82e9b60.png)
> 
> ## Working translations in newest WeKan
> ![lang](https://user-images.githubusercontent.com/15545/211127092-8ba86b8f-b902-48f1-a6a4-967bc4541fe5.png)
> 
> ## Browser settings need to have only one language
> For example, show WeKan in Japanese, there needs to be only Japanese selected at Firefox Preferences / Choose your preferred language for displaying pages. Delete all other languages from there, there needs to be only Japanese, like this:
> 
> <img alt="wekan-language" width="714" src="https://user-images.githubusercontent.com/15545/169667806-88585bbf-4a8d-49ed-a4ad-473cd2a5203b.png">
> 
> After that, WeKan is in Japanese:
> 
> <img alt="admin-panel" width="583" src="https://user-images.githubusercontent.com/15545/169667820-51ef8368-89ae-4aee-8e93-13a3722f8a98.png">

i am using snap, and have same language problem
didn't understand what should i do now

**Comment by tangjiahao2001** [comment]
@mohammadZahedian 
### Maybe you could take a look at this
https://github.com/wekan/wekan/wiki/Settings
![image](https://user-images.githubusercontent.com/72953189/211186026-19ee8789-bd59-4776-be7f-54eaf46e0143.png)

**Comment by xet7** [comment]
Yes, that is setting for WeKan server computer IP address, at local network.

**Comment by xet7** [comment]
@mohammadZahedian 

According to your screenshots at https://github.com/wekan/wekan/issues/4303#issuecomment-1375211178 you have not setup root-url correctly, because you still have menu names like `-title` etc. Having wrong settings also can cause attachments not visible.

If you use WeKan at local network, you can check your WeKan server IP address at network settings, or with command:
```
ip address
```
For example, if you have IP address `192.168.0.100`, then use settings:
```
sudo snap set wekan root-url='http://192.168.0.100'
sudo snap set wekan port='80'
```
But change your IP address to above.

If your WeKan server is at public Internet, and you have nameserver subdomain like `wekan.example.com` pointing to your server like `A 100.100.100.100` where you change that to your server public IP address, then you can setup Caddy 2 to provide SSL/TLS https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

So then settings would be:
```
sudo snap set wekan root-url='https://wekan.example.com'
sudo snap set wekan port='3001'
```
In this above case, Caddy would redirect from HTTP 80 to HTTPS 443, and then proxy to localhost 3001 WeKan Node.js server.

**Comment by mohammadZahedian** [comment]
i have just restored database every thing is ok except pictures and attachments...
root url is ok too...
what shoud i do now?

**Comment by mohammadZahedian** [comment]
![image](https://user-images.githubusercontent.com/25129673/212825713-5052c0b9-aa6d-462e-a466-6e111c5695c8.png)

**Comment by mohammadZahedian** [comment]
also cant import with json most of the time, espacialy when the board has attachment

**Comment by xet7** [comment]
@mohammadZahedian 

It depends can you send your mongodump backup in .zip file from free https://proton.me email account to support@wekan.team (Protonmail encrypts internal email), so that I could look what bug there is.

**Comment by bonnebulle** [comment]
Hello
Am using last version (w/ Docker)
I have the same issue ( when no port specified )
Docker env:
```ROOT_URL=http://192.168.125.14```
error message : 
```GET
http://192.168.125.14/cdn/storage/avatars/6QB3ZGv2njJWevp5r/original/6QB3ZGv2njJWevp5r.png?auth=false&brokenIsFine=true
[HTTP/1.1 403 Forbidden 1ms]````

If I specify port it's OK
```ROOT_URL=http://192.168.125.14:3080```
( maybe can help others )

**Comment by mohammadZahedian** [comment]
still have translate problem
![image](https://github.com/wekan/wekan/assets/25129673/db6cdce9-2f86-4da4-b38b-cf3e4b9162a3)

but after refresh it is fine

**Comment by xet7** [comment]
Related https://github.com/wekan/wekan/issues/4780#issuecomment-1643699532

**Comment by Dexus** [comment]
Hello, we have also the problem with the `401 Forbidden` on attachments and pictures.

The `ROOT_URL` is correct. We use a HA PROXY within a openshift as frontend/LB. Since the update from 6.xx to 7.0.9 we see this error.

Any idear how we can fix it?

**Comment by sopheck** [comment]
> Hello Am using last version (w/ Docker) I have the same issue ( when no port specified ) Docker env: `ROOT_URL=http://192.168.125.14`
> 
> console error message :
> 
> ```
> GET
> http://192.168.125.14/cdn/storage/avatars/6QB3ZGv2njJWevp5r/original/6QB3ZGv2njJWevp5r.png?auth=false&brokenIsFine=true 
> [HTTP/1.1 403 Forbidden 1ms]
> ```
> 
> If I specify port it's OK `ROOT_URL=http://192.168.125.14:3080` ( maybe can help others )

This was exactly the source of my error: I changed the port from 80 to 9000 in the compose file - but not for `ROOT_URL=http://localhost` (which is port 80 by default). As soon as I restarted the containers with `ROOT_URL=http://localhost:9000`, everything worked as expected. Perhaps an adjustment in the documentation would be helpful here, such as

https://github.com/wekan/wekan/blob/main/docker-compose.yml
```
# ==== ROOT_URL SETTING ====
      # Change ROOT_URL to your real Wekan URL, for example:
      # If you have Caddy/Nginx/Apache providing SSL
      #  - https://example.com
      #  - https://boards.example.com
      # This can be problematic with avatars https://github.com/wekan/wekan/issues/1776
      #  - https://example.com/wekan
      # If without https, can be only wekan node, no need for Caddy/Nginx/Apache if you don't need them
      #  - http://example.com
      #  - http://boards.example.com
      #  - http://192.168.1.100    <=== using at local LAN
      - ROOT_URL=http://localhost:<YOUR PORT HERE> #   <=== using only at same laptop/desktop where Wekan is installed e.g. http://localhost or http://localhost:9000 (depending on the port setting)
 ```

Thank you @bonnebulle  for pointing this out.

**Comment by xet7** [comment]
@sopheck 

Localhost can only be used at computer where WeKan server is running. It's not useful.

Point in setting ROOT_URL=http://WEKAN-SERVER-IP-ADDRESS and PORT=80 is that then everyone at local network can use WeKan at desktop and mobile devices at http://WEKAN-SERVER-IP-ADDRESS and make icon for mobile https://github.com/wekan/wekan/wiki/PWA

If WeKan server is accessible at Internet, it's useful to setup Caddy 2 SSL/TLS and ROOT_URL=https://wekan.example.com and for example PORT=3000 when Caddy 2 proxies HTTPS 443 to 3000

https://github.com/wekan/wekan/wiki/Settings

https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

https://github.com/wekan/wekan-snap/wiki/Many-Snaps-on-LXC

Also, if card cover image is not visible, it's useful to enable showing it, at right sidebar / Board Settings / Card Settings / Show Cover Image.

After adding new image, if it's not visible, it maybe is useful to reload webpage.

Sure, there also could be some bugs.

**Comment by sopheck** [comment]
@xet7 

Thanks a lot for the detailed explanation – that makes perfect sense!
You're absolutely right regarding accessibility from other devices. In my case, I was just running WeKan as a personal tool on my local machine, so localhost with a custom port worked well for me.

Maybe a small note in the docker-compose.yml comments could help clarify this distinction for others in a similar single-user local setup. I totally understand that most setups aim for multi-user or network-wide access.

Anyway, I really appreciate the great work and your quick feedback. Thanks again for the helpful links!

**Comment by xet7** [comment]
@sopheck 

For single user local use, it would be simplest to have one execteable desktop app, that would automatically create one database file wekan.db SQLite database to same directory, but I don't have that yet. Currently it takes too much time to explain all the command line options etc complexity to everyone.

**Comment by sopheck** [comment]
@xet7 

That would actually be great! A lightweight standalone version with SQLite would definitely lower the entry barrier for personal use.
I can imagine that many people (like me) would appreciate a no-setup-needed version for quick local boards.

That said, I totally understand that building and maintaining something like this would take a lot of time and effort.
For my part, I'm doing fine with the Docker setup now that I got it working – thanks again for your help and for all the work.
