### ISSUE TITLE
PPA Install Support

### ISSUE THREAD

**Issue by zeljkoantich** [wekan/wekan#4806]
## Feature Fequest: PPA Install Support
Are you planning to support PPA installations? 

I prefer not to use Snap. Distro that I use, Linux Mint, disallows Snap ( I support that decision ).

**Comment by xet7** [comment]
No. PPA is Ubuntu/Debian-only packaging format. WeKan already supports other ways to install that work on more than only Ubuntu/Debian. I'm more interested to sometime find out how to make AppImage or Flatpak, they work on many distros.

It is possible to use Snap on Mint. Using Snap saves a lot of time, when new version is released nearly every day. Snap also provides secure sandboxing.
- https://snapcraft.io/docs/installing-snap-on-linux-mint

It's also possible to install without any containers, like without Snap/Docker etc:
- https://github.com/wekan/wekan/wiki/Raspberry-Pi

Please do not feed Snap FUD trolls. Thanks!
