### ISSUE TITLE
REST API "Internal server error"

### ISSUE THREAD

**Issue by corbing** [wekan/wekan#4807]
I have a brand-new install of Wekan and am trying to [use the API to get the token](https://github.com/wekan/wekan/wiki/REST-API).

I have created a new user with a username = API and made that user an admin.

I am calling it with:

curl https://kanban.domain.com/users/login \\
     -d "username=API&password=ThePassword"

But, it is returning:
{
    "error": "internal-server-error",
    "reason": "Internal server error"
}

WeKan  Version	6.70.0
Meteor version	2.9.1
Node version	14.21.2
MongoDB version	4.4.10

**Comment by xet7** [comment]
@corbing

Sorry, login as Form Data does not work after latest fixes.

Please instead use login as JSON:
https://github.com/wekan/wekan/wiki/REST-API#example-call---as-json

Or api.py example at https://github.com/wekan/wekan

**Comment by xet7** [comment]
I updated wiki about what login works.

**Comment by corbing** [comment]
Are you sure that JSON example is correct?  I can't get that to work either.

**Comment by xet7** [comment]
@corbing 

Yes, I did test:
```
wekan@z:~/repos$ cat ap.sh
curl -H "Content-type:application/json" \
      http://192.168.0.20:4000/users/login \
      -d '{ "username": "testtest", "password": "testtest" }'

wekan@z:~/repos$ ./ap.sh
{
  "id": "SMvCZ3ji94QxZWrWc",
  "token": "oiD79O...",
  "tokenExpires": "2023-04-15T22:22:55.555Z"
}
```

**Comment by xet7** [comment]
For you, it should some something like this:
```
curl -H "Content-type:application/json" \
      https://kanban.domain.com/users/login \
      -d '{ "username": "API", "password": "ThePassword" }'
```

**Comment by xet7** [comment]
But I'm not sure why you use MongoDB 4.x . Currently WeKan is compatible only with MongoDB 5.x and newer, newest versions listed at https://wekan.github.io Download section, there is MongoDB 6.0.3.

**Comment by xet7** [comment]
Changing MongoDB version required mongodump and mongorestore.

**Comment by xet7** [comment]
Ok seems problem was, username and password is case sensitive. So now it works. I added to wiki info about case sensitive.
