### ISSUE TITLE
Checklist model not creating collection and not saving to database

### ISSUE THREAD

**Issue by leon-developer** [wekan/wekan#481]
I am trying to add checklist functionality to CardDetails . I added some templating to CardDetails.jade

          .card-details-item.card-details-item-checklists
            h3.card-details-item-title {{_ 'checklists'}}
            a(class="{{#if currentUser.isBoardMember}}js-add-checklists{{else}}is-disabled{{/if}}" title="{{_ 'card-labels-title'}}")
            if currentUser.isBoardMember
              a.card-label.add-label.js-add-checklists(title="{{_ 'card-labels-title'}}")
                i.fa.fa-plus

I added an event to CardDetails Blaze Component to make a PopUp

      'click .js-add-checklists': Popup.open('cardChecklists'),

Here is my client/components/cards/checklists.js

<pre><code>
Template.cardChecklistsPopup.events({
  submit(evt, tpl) {
    evt.preventDefault();
    const text = tpl.$('.js-checklist-name').val().trim();
    if (text) {
      const ax = CardChecklists.insert({
        text,
        cardId: this._id,
      });
    }
    Popup.close();
  },
});
</code></pre>
This is my client/components/cards/checklists.jade

<pre><code>
template(name="cardChecklistsPopup")
  form
    label
      | {{_ 'title'}}
      input.js-checklist-name(type="text" autofocus)
    input.primary.wide(type="submit" value="{{_ 'create'}}")
</code></pre>

I copied models/cardComments.js and created cardChecklists.js

<pre><code>
CardChecklists = new Mongo.Collection('card_checklists');

CardChecklists.attachSchema(new SimpleSchema({
  cardId: {
    type: String,
  },
  text: {
    type: String,
  },
  createdAt: {
    type: Date,
    denyUpdate: false,
  },
  userId: {
    type: String,
  },
}));

CardChecklists.allow({
  insert(userId, doc) {
    return allowIsBoardMember(userId, Boards.findOne(doc.boardId));
  },
  update(userId, doc) {
    return userId === doc.userId;
  },
  remove(userId, doc) {
    return userId === doc.userId;
  },
  fetch: ['cardId'],
});

CardChecklists.helpers({
  user() {
    return Users.findOne(this.userId);
  },
});

CardChecklists.hookOptions.after.update = { fetchPrevious: false };

CardChecklists.before.insert((userId, doc) => {
  doc.createdAt = new Date();
  doc.userId = userId;
});
</code></pre>

In the UI, on card details, I can see a Plus button similar to Members, which is what I wanted. When I click on the plus button I can see a PopUp and Create button. When I click on the create button, this code runs and in the ax variable I see an id. 

      const ax = CardChecklists.insert({
        text,
        cardId: this._id,
      });

But when I log into MongoDb, card_checklists collection is not created and subsequently the checklist is not saved. What am I doing wrong ?

**Comment by hsduk** [comment]
try change the collection name to `CardChecklists = new Mongo.Collection('cardchecklists');` ?
http://stackoverflow.com/questions/5916080/what-are-naming-conventions-for-mongodb

**Comment by leon-developer** [comment]
Fixed it myself. There was no boardId in my model schema and also not passing it on submit. So
<code>
CardChecklists.allow({
  insert(userId, doc) {
    return allowIsBoardMember(userId, Boards.findOne(doc.boardId));
  },
</code>
This was returning false. Hoping to contribute my checklist code once it is complete.

**Comment by hsduk** [comment]
Try the session var currentboard instead of the findone?
On 16 Jan 2016 13:09, leon-developer <notifications@github.com> wrote:Fixed it myself. There was no boardId in my model schema and also not passing it on submit. So

CardChecklists.allow({
  insert(userId, doc) {
    return allowIsBoardMember(userId, Boards.findOne(doc.boardId));
  },

This was returning false. Hoping to contribute my checklist code once it is complete.
