### ISSUE TITLE
Alerts to users when you add them as "assignee"

### ISSUE THREAD

**Issue by HEMGDevelopment** [wekan/wekan#4814]
## Issue
I don't know if this is an issue or not, maybe it can be categorized as an opinion.

But we have noticed that the tracking alerts to people are based upon if your a "member" or "creator" of a card.
You don't get any any alerts if you on a board have chosen "Tracking" (there is Watching, tracking, Muted) when you get a task assigned to you as "assignee" on a card. So we have to first set the assignee as a member and then to assignee so that they get alerts. In my opinion if I had to choose one person on a card that get alerts it should be the assignee who is supposed to react to the card.
It is not a big issue but it is easy to forget to first add member and then assignee when you assign a card to someone.

Maybe who get alerts could be a general setting on your wekan installation?

### Server Setup Information

* Did you test in newest Wekan?: Yes, newest version available as snap. 
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

### Problem description
See above.
#### Reproduction Steps
1. Go to a board and assign a card to someone has choosen "tracking" under "Tracking"-alternatives.
You will notice that his person don't ge a e-mail notification.
2. Go to a bord and create a card, set a person as member that is "tracking" then assign a card to him/her.

**Comment by xet7** [comment]
Moved to #2026
