### ISSUE TITLE
Copying a specific board missing most of its information

### ISSUE THREAD

**Issue by kjgcoop** [wekan/wekan#4816]
When I try to copy a specific board, it only adds the first list and even then, no cards in it. I tested another board and had no problem, so there's something funny about this board. I came across a older post somewhere indicating that Wekan then had problems duplicating boards with attachments. I don't see any attachments on any of the cards. It has a total of five columns and about 85 cards. 

## Server Setup Information
* Tested in Wekan 6.09.0, which is the latest in Ubuntu 22.04's snap repository. 
* I'm not having trouble opening cards, so I'm not inclined to believe root-url is an issue. 
* Node version: 12.22.10
* MongoDB version: 3.2.22
* I'm on Firefox 102.6. I've also tried it on an older version of Chrome.

## Problem description
The resulting board:
![image](https://user-images.githubusercontent.com/51257881/215257794-c87ad19f-2193-43d2-ac25-2e5b9886d087.png)

## Reproduction Steps
I saw it when I clicked the duplicate icon in the bottom corner of the board square in the all boards view. I also tried exporting it as JSON and re-imported it to the same effect.

### Error in Firefox Developer Console
Exception in delivering result of invoking 'copyBoard': TypeError: this.setError is not a function
    e/events/click .js-clone-board/< http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:632
    bindEnvironment [IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:1
    _maybeInvokeCallback http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    dataVisible http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    _process_updated http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    _runAfterUpdateCallbacks http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    _runAfterUpdateCallbacks http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    _performWrites http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    _flushBufferedWrites http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    _livedata_data http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    _livedata_data http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:584
    onMessage http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    onmessage http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    forEachCallback http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    onmessage http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    dispatchEvent http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    _dispatchMessage http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    _didMessage http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    onmessage http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    websocket http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    _try_next_protocol http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    _didClose http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    onfinish http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    emit http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    onfinish http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    emit http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    onreadystatechange http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    EventHandlerNonNull* http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    XHRLocalObject http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    setTimeout handler*t/n.delay http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    XHRLocalObject http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    <anonymous> http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    J http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    setTimeout handler*t/n.delay http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    J http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    q http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    k http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    _launchConnection http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    u http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:243
    M http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    connect http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    e http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    g http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:5
    n http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:5
    o http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:7
    e http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    g http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:5
    n http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:5
    e http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:5
    <anonymous> http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
    <anonymous> http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true:245
[cb67c9e27fa36a4dd9085640bd07631368ca11ce.js:1:6771](http://[IP address:port]/cb67c9e27fa36a4dd9085640bd07631368ca11ce.js?meteor_js_resource=true)

### Snap:
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at packages/ddp-server/livedata_server.js:719:19
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at packages/ddp-server/livedata_server.js:717:46
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at packages/ddp-server/livedata_server.js:715:46
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at new Promise (<anonymous>)
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2023-01-28T00:45:57-08:00 wekan.wekan[2165]:     at packages/ddp-server/livedata_server.js:559:43

## Thank you!
Any help would be much appreciated.

**Comment by xet7** [comment]
Please wait for automatic Snap upgrade, developing it is in progress.

Moved to #4780
