### ISSUE TITLE
On mobile (Android) unable to login, or navigate the site

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#482]
Not been able to login - or navigate using my my mobile phone

![screenshot](http://i.imgur.com/6oZbwcU.png)

**Comment by mquandalle** [comment]
We miss a “sign-in” link on this page.

**Comment by AndyatFocallocal** [comment]
also the navigation menus weren't accessible

**Comment by xet7** [comment]
Login works for me on Android browser.
