### ISSUE TITLE
Ability to move Boards for organisation purposes

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#483]
potentially re-size them as well, although that might be controversial

**Comment by mquandalle** [comment]
I guess you are speaking about moving boards in the home page grid? Could you explain more about what you are trying to achieve?

**Comment by AndyatFocallocal** [comment]
i'd like to be able to organise the boards so we could group our 4 different areas together, probably in rows

[projects]   [activities]   [general tasks]   [teams]
[    p1    ]   [    a1     ]    [      g1           ]   [   t1    ]
[    p2    ]   ..etc

**Comment by jonathan-chin** [comment]
+1 I would love this functionality!

**Comment by xet7** [comment]
Moved to #641
