### ISSUE TITLE
SVG image failed to rendering

### ISSUE THREAD

**Issue by o0sh4d0w0o** [wekan/wekan#4830]
### Server Setup Information

* Did you test in newest Wekan? Yes.
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Linux
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap (but tested with docker too)
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: Latest
* MongoDB Version: 5
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Chrome / Firefox

### Problem description
When uploading a SVG image, the image appear as missing. Sometimes, the image will appear but when refreshing with (Ctrl + F5) the image will don't work anymore.

Here is result while trying to access to the image directly after refreshing (in demo board) :
![image](https://user-images.githubusercontent.com/25451887/217499083-930900f2-c9f8-4f02-aaa6-4434be417717.png)
![image](https://user-images.githubusercontent.com/25451887/217499112-9ea9bf77-ffeb-491e-8666-12700f5b7176.png)

Here is result while trying to access to the image mounted in local environement (via docker) :
![image](https://user-images.githubusercontent.com/25451887/217500449-a259ec6c-742e-4599-a187-4a27dd54e0cd.png)
![image](https://user-images.githubusercontent.com/25451887/217500551-bef86a16-8375-434f-a92f-19aac8784654.png)

It look like mime type are missing or in case there is a content-type it has the wrong value for attachment resources (same to any uploaded content)

#### Reproduction Steps

- Upload a SVG image by any available way (avatar, card, ...)
- If image is showing correctly first time refresh page
- Do a refresh with CTRL + F5 or by clearing cache to be sure
- In this case image should appear as missing

**Comment by xet7** [comment]
What version of WeKan are your running?

Check with:
 ```
sudo snap list
```
