### ISSUE TITLE
Error login API with LDAP

### ISSUE THREAD

**Issue by jbraud44** [wekan/wekan#4836]
### Server Setup Information
* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly ? yes
* Deployment Method: Docker
* Http frontend if any: Apache

### Problem description
When i try to login the API (explain in https://github.com/wekan/wekan/wiki/REST-API#login) with a LDAP user i have this error : 
{
    "error": "internal-server-error",
    "reason": "Internal server error"
}

I don't have any issue with an internal user.

**Comment by xet7** [comment]
@jbraud44 

WeKan currently has API for internal normal users and internal Admin users.

If someone would like to figure out API for LDAP/OAuth2 etc users and [send Pull Request](https://github.com/wekan/wekan/wiki/Emoji), related files are:

- REST API code at https://github.com/wekan/wekan/tree/master/models
- LDAP code at https://github.com/wekan/wekan/tree/master/packages
- Authentication code at https://github.com/wekan/wekan/blob/master/server/authentication.js
- Login page at `layouts.*` at https://github.com/wekan/wekan/tree/master/client/components/main

Thanks!

**Comment by xet7** [comment]
Moved to #3707
