### ISSUE TITLE
Docker Container with NGINX Reverseproxy --> Wrong Views of WEKAN

### ISSUE THREAD

**Issue by CrashOverride-lab** [wekan/wekan#4838]
### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version:
* MongoDB Version: newest 5
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox

### Problem description

Hi Guys,

i build a new WEKAN Setup but Wekan looks on some Points odd:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/85289600/219774301-07d2861e-ddee-4855-92f3-bb2124213aa0.png">

I found here Information that this is a Problem with the ROOT_URL, and i can confirm that. But i didn´t found any helping Information how i can fix this Problem with an NGINX Reverseproxy (WEKAN is deployed as a SUB-URL --> and this is mendatory)

#### Reproduction Steps

Deploy current WEKAN Docker-Container  with the following ROOT_URL Parameter:
ROOT_URL=https://Main-Website.com/wekan

Configuration on the Reverseproxy:

```
  location /wekan {
    proxy_pass             http://10.0.0.2:9000;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP

  }
```
But i tried differnent Reverseproxy Configurations the last hours :-D.

Has someone a Tipp, how i can fix that?

Thanks in advance ;-)

**Comment by xet7** [comment]
@CrashOverride-lab 

> (WEKAN is deployed as a SUB-URL --> and this is mendatory)

For such mandatory non-standard configuration, it is mandatory to pay 4000 euro to fund fixing all related bugs at https://wekan.team/commercial-support/

Standard WeKan configuration to use subdomain like https://kanban.example.com

**Comment by xet7** [comment]
@CrashOverride-lab 

Meteor WeKan does not support sub-URL properly, it's because of ROOT_URL etc requirements built into Meteor web framework. Meteor WeKan works better with sub-Domains.

Other upcoming WeKan versions like Multiverse will work OK with sub-URLs.
