### ISSUE TITLE
Edit boards once posted to top level page

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#484]
right now it appears that the only possibility is to delete them, which would then require writing all the cards they house as well

**Comment by mquandalle** [comment]
What do you mean by “edit boards”? It’s already possible to change to board title (by clicking on it on the board view).

**Comment by AndyatFocallocal** [comment]
sorry, i missed this. although it would be nice to be able to edit the description on the top level boards list, its not too important. i see you deleted my suggestion for resizing boards, i agree that was a daft idea.
