### ISSUE TITLE
Cannot create team or organization

### ISSUE THREAD

**Issue by xiepu1212** [wekan/wekan#4843]
### Server Setup Information
I use docker privatization deployment Wekan 

Wekan 版本	5.22.0
Meteor版本	2.2
Node.js版本	12.22.1
MongoDB版本	5.0.5
MongoDB存储引擎	wiredTiger
MongoDB Oplog已启用	

### Problem description

Cannot create team or organization

![image](https://user-images.githubusercontent.com/34331649/220839523-0449a093-eae7-41a3-b57c-5ff655377df3.png)
![image](https://user-images.githubusercontent.com/34331649/220839810-08055435-52d1-43a2-a2f9-130afd5b2400.png)

**Comment by xet7** [comment]
You have old WeKan version.

Can you install newest WeKan?

For example with:

a) Using docker-compose.yml from https://github.com/wekan/wekan

b) https://github.com/wekan/wekan/wiki/Offline

**Comment by xiepu1212** [comment]
@xet7  I pull the docker image the last version，the image ID is d26c44fa7732 , created almost 2 years ago

**Comment by xiepu1212** [comment]
> @xiepu1212
> 
> You have old WeKan version.
> 
> Can you install newest WeKan?
> 
> For example with:
> 
> a) Using docker-compose.yml from https://github.com/wekan/wekan
> 
> b) https://github.com/wekan/wekan/wiki/Offline

I used the newest version，but the container startup failed , there is some error

![image](https://user-images.githubusercontent.com/34331649/221130147-e9c13db6-bfb1-4153-89c1-a69798456c52.png)

**Comment by xet7** [comment]
@xiepu1212 

Please use newest docker-compose.yml that has WRITABLE_PATH:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L156
