### ISSUE TITLE
Bug: Tiles are moving on landing page

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4848]
* Operating System: Windows 10, Chrome Version 110.0.5481.178 
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version: 14.21.3
* MongoDB Version: 6.0.4

#### Reproduction Steps
Go to landing page, see tiles. Maybe press F5.

Emptying my cache didn't do anything.

[wekanbug_kacheltanzen.zip](https://github.com/wekan/wekan/files/10860912/wekanbug_kacheltanzen.zip)

**Comment by Meeques** [comment]
It's because of the avatar pic I guess. Loading again and again

**Comment by xet7** [comment]
Moved to #4214
