### ISSUE TITLE
Wekan language switch does not work

### ISSUE THREAD

**Issue by julred** [wekan/wekan#4854]
## Issue
The wekan language switch does not work. I prefered german language on login - but I can only see the label for each item on the website:
![14-03-_2023_08-14-39](https://user-images.githubusercontent.com/6383396/224924023-dc881614-e239-4d7e-a7df-18fb5cc73cfa.png)

It's also not possible to change the language when I'm logged in.

Wekan: 6.73.0
Meteor: 2.10.0
Node: 14.21.2
MongoDB_version: 6.0.4

**Comment by spidernete** [comment]
Change to SET PORT=80 in start-wekan.bat file
Had same problem and this fixed the issue instantly.

**Comment by julred** [comment]
Unfortunately I dont have any chance to change the port setting on my maschine due to firewall restrictions.
I need to go with port 2000 - any recommendations?

**Comment by spidernete** [comment]
Yes, just add the port to the root url:
SET ROOT_URL=http://192.168.1.25**:2000**
Change "192.168.1.25" to your server ip adress
