### ISSUE TITLE
Unable to upload avatar

### ISSUE THREAD

**Issue by andrewshadura** [wekan/wekan#4856]
## Issue

When I try to upload a new avatar (about 80KB), an error appears, `The avatar is too large (520KB max)`. I see no network requests in the browser’s devtools, no errors in the console.

### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Debian bookworm
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node.js Version: ??
* MongoDB Version: 4.4
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox

#### Logs
Nothing in the Docker logs or in the browser’s console.

**Comment by mfilser** [comment]
I have already a commit regarding to this in my pipeline.
