### ISSUE TITLE
Feature Request: Board Background Image and All Boards Background Image

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#486]
probably not very important as a dev can easily do so themselves, but it would help attract non-techy uses with improved visual experience

**Comment by jseadragon** [comment]
maybe we could provide a handful of nice looking backgrounds to go with it, too (assuming they're in the public domain, of course)

**Comment by mquandalle** [comment]
Where would you put the background? At the board level? On the home page?

**Comment by AndyatFocallocal** [comment]
i'd suggest for all of it.here's a mock up i made for our developers (btw, the background looks amazing and i believe is not licensed)

![challenges](https://cloud.githubusercontent.com/assets/16229696/12244201/57e04dea-b89a-11e5-8caa-482e17a7eaca.jpg)

![challenges menu](https://cloud.githubusercontent.com/assets/16229696/12244210/5dc8d808-b89a-11e5-8dbf-24da35b5d03b.jpg)

**Comment by Umi97** [comment]
@mquandalle  Hi, 
I am working to achieve the feature (add a background image to the board). But I have a problem. I add an attribute in [board.js](https://github.com/wekan/wekan/blob/90428e7ba1c0e4185f92dc26b793aff1a9e04bc6/models/boards.js#L3) named 'image', and it look like below: `  image: {
    type: String,
    allowedValues: [
      'img001',
      'img002',
    ],
  },` When I add this attribute, I find I cannot add a new board......
Did I miss something?

**Comment by whodafly** [comment]
@anhenghuang Are you still working on this one?

**Comment by anhenghuang** [comment]
@whodafly Frankly speaking I achieved this feature last year. But I lost the code and details so I cannot help you... Things I still remember is that wekan (or meteor) is highly modularized. It will not be too difficult for you to work it !!!!

**Comment by ChrisMag18** [comment]
Is there anyone who could help me to do this?

**Comment by vasyugan** [comment]
Hi, I just discovered wekan, and I am trying to get my organisation to move to it from Trello. I guess to increase its acceptance, it should resemble Trello as much as possible, and that includes board backgounds, which are also the image identifying a particular board in the overview. So I just wanted to bump this issue up...

**Comment by ultibo** [comment]
agreed it would improve user acceptance if we could have nice backgrounds.
as you all probably know trello uses unsplash.com as a source of freely usable images. 
would love to have the feature.
Otherwise very interested in where in the code to look to properly add this background image

**Comment by derbolle** [comment]
I would be very glad about this feature if it would become available. If you @xet7 could name a price to implement customizable board background images (custom per board per user would be really handy, too) I would go forward this to my superiors. 

This is a feature that would give wekan more acceptance in my organisation

**Comment by xet7** [comment]
@derbolle 

300 euro. https://wekan.team/commercial-support/

**Comment by xet7** [comment]
Nobody has paid for this feature yet, but...

I received new Wekan theme from @nickbe . When I did originally promise to @nickbe to add theme to Wekan for free, but I did not know that it would include a background image.

I added some of those CSS changes from @nickbe to Wekan, it currently looks like this:

![wekan-background](https://user-images.githubusercontent.com/15545/75153392-f97dfc80-5713-11ea-9d10-aefa902b582d.png)

I did start to add `Board Setting / Change Background Image`, where is Board Image URL input box, but it does not work fully yet, it needs some fixes.

Then there is questions, would someone like to have:
- Import also background image from Trello
- Export Wekan board with background image to JSON, and import back
- Should there be ability to add multiple background images to board, and select which one to use. For example, when importing Trello board, are there multiple background images in the Trello JSON.
- Ability to add and remove background images of board
- Should there be ability for all members of organization to see all background images of all boards
- When there is no background image, use all original CSS.
- When there is background image, use new CSS from @nickbe , that allows showing image at background, letting some parts of the board to be transparent.
- Changes to CSS also do change card look a little.

It seems that finishing this Board Background Image feature would require a lot more work, so I did stop developing it, to concentrate to Teams/Organizations and Nested Tabs https://github.com/wekan/wekan/issues/802#issuecomment-590299118 that are already paid.

I don't know is somebody so interested in this feature that someone would like to pay for this for example 500 euro at https://wekan.team/commercial-support/ . I will think about this later when I have some more free time.

**Comment by nickbe** [comment]
It looks like your time is as limited as my own :)

So honestly, I think that it would be enough to be able to use the theme I've sent you without any image at all, but instead with an option to freely define the background color (not even with a color picker but rather with a plain old simple hex value field per board).

Having said this, I feel like importing/exporting images is far too much hassle. Also if there would be an option to use an image at all, then an image URL field per board would definetely be enough. 
(Either we can use our own webservers to host the images we like or we can use one of the many free image services out there)

All other options like having some sort of image pool, importing images from trello, exporting with images, different role settings might be nice in the future, but this is certainly something for a donation round.

**Comment by xet7** [comment]
@nickbe 

Your theme did not work as additional theme in that one CSS file, so I did copy some parts of your CSS to affect all Wekan themes, without adding any new single theme. I don't know, is your theme background color much different from Wekan midnight theme? Do you need those colors?

Maybe I just got lost when thinking all those complex import/export etc options, and that made me stop. If just menu option for background URL is enough, there is only a little missing from it to make it working fully.

I don't know in which way my time is limited. I do decide about my own time usage. I do Wekan features and fixes fulltime and rest when needed. Mainly it's just that do I see a clear way to implement something minimal first, or is it some never-ending rabbit hole.

**Comment by xet7** [comment]
Well, I think that I'll just try to fix so that changing background works, and let changes affect all themes. Then see what feedback I get.

**Comment by nickbe** [comment]
Hey :)
Well being able to freely change the background will probably satisfy most users. And the changes you've made are already pretty close to what I've suggested. 

If you also find a simple solution for the background image, then I'm pretty sure many users will be more than happy about this. 

We're always using background images or colors because on multiple screens and tabs it really helps to keep my orientation - AND it's more fun to look at this way, which I always encourage because the more we like something, the more we use it.

**Comment by nickbe** [comment]
Oh and... thanks again for putting some time into this at all. 
These things are not strictly needed but much appreciated 😃

**Comment by nickbe** [comment]
Anything new regarding this?

**Comment by xet7** [comment]
@nickbe 

I did not get background image setting working yet. I will add it later, when I get it working.

**Comment by nickbe** [comment]
Ok, thanks!

**Comment by vikuto** [comment]
is this feature paid/still in development or what? quite confusing since at some point it says it is paid then it is free.

**Comment by xet7** [comment]
@vikuto 

This is still [waiting for funding](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/BBGFFF27d3mKF2TCe)

Paid In Progress features have some amount of money number [at Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)

My current priorities are:
1. Security fixes
2. Paid features
3. Others

**Comment by vasyugan** [comment]
> @vikuto
> 
> This is still [waiting for funding](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/BBGFFF27d3mKF2TCe)

From the link, I don't understand what amount of funding is required and how it can be provided.

**Comment by xet7** [comment]
@vasyugan 

Oops, sorry.

For this feature, 500 euro. That funding can be from one person, or multiple persons can participate to combined amount of 500 euro.

Funding payment options are at https://wekan.team/commercial-support/

**Comment by xet7** [comment]
Moved to here from #3777

From @DemonRem 

Add Feature

Add background and a big cover icon image
![Screenshot_20210501_003905_com trello](https://user-images.githubusercontent.com/29927382/116757206-5101b180-aa16-11eb-9e21-91b2d2ea1da1.jpg)

**Comment by Meeques** [comment]
@xet7 we're thinking about funding a few issues. Has there been any funding regarding this issue?

**Comment by xet7** [comment]
Backgroud image feature has been paid and is In Progress of about 20%. Because some other urgent In Progress paid features have had good progress and are near finishing, it will make possible continuing developing this feature after them.

**Comment by Meeques** [comment]
Hi Lauri, are there any updates since April?

**Comment by xet7** [comment]
@Meeques 

I added board background image feature:
https://github.com/wekan/wekan/commit/49ef80ab6c2dc038941558f68eface5e82a87593

It will be in next release of WeKan.

**Comment by xet7** [comment]
@Meeques @derbolle @ultibo @mfilser @helioguardabaxo @vikuto @vasyugan @nickbe 

I added per-board background image, editable by Admin and BoardAdmin. But should there be per-user override?

I am currently adding All Boards Change Color and Change Background Image, editable by Admin. But should there be per-user override?

About Cover Image, does someone know is this about changing Cover Image to where?

**Comment by xet7** [comment]
Also, should that All Boards Color and Background Image also affect other pages, like My Cards, etc?

Or should there be possibility select Global Color and Background Image, that affects all boards and all pages?

I think, what is enough, or what is too much?

**Comment by helioguardabaxo** [comment]
Hi, @xet7 !

Follow below my preferences:

Each Board:
Per-board color and background image, editable BoardAdmin.

All Boards | My Cards | Due Cards | Global Search | etc. :
Global Per-user color and background image, editable by User

**Comment by helioguardabaxo** [comment]
About cover image:
I use it for show some attached image on minicard
![image](https://github.com/wekan/wekan/assets/24301085/9f3cd9b7-7008-4cb3-92d7-8113b645ba32)

**Comment by xet7** [comment]
@helioguardabaxo

> Each Board: Per-board color and background image, editable BoardAdmin.

Ok. This is already done.

> All Boards | My Cards | Due Cards | Global Search | etc. : Global Per-user color and background image, editable by User

Thanks! First I started to add those settings to All Boards page, but now I understand, those settings should be at User Settings!

**Comment by xet7** [comment]
@helioguardabaxo

> All Boards | My Cards | Due Cards | Global Search | etc. : Global Per-user color and background image, editable by User

Hmm, I think that maybe at those menus:
- User Settings / Change Color
- User Settings / Background Image

Could maybe also be this setting:
```
[_] Boards
```
That would also override board specific colors and background images. For example, if someone would like to have dark mode everywhere.

Although, if it would override differences in boards, maybe then keep some small part of original color at All Boards page board icons.

But maybe I am thinking it some too difficult way. Anyway, I will think about this sometime later.

**Comment by helioguardabaxo** [comment]
@xet7 
Override board specific colors and background images for user that prefers Dark mode is a good idea.

User settings menu on Home maybe join too: Edit profile, change settings, change avatar, change password, change lang.

**Comment by Meeques** [comment]
Hi @xet7, thanks for adding background images. Every user should be able to set a backgroundimage for their Board. Boards with more than one user will be set by the admin. So like you already implemented. In my opinion, it doesn't have to affect "my cards", only the boards itselves.

**Comment by xet7** [comment]
@Meeques 

The creator of board is BoardAdmin. So it already works like you described.

**Comment by Meeques** [comment]
I just looked at the option. You can enter a picture URL, which most of our users won't be able to do without asking how it works / researching how it works. Best would be an upload button right there.

**Comment by xet7** [comment]
@Meeques

> Best would be an upload button right there.

That would be complex to implement.

Instead, I will add option `Set Background Image` to `Card Attachment ☰ Menu`.

https://github.com/wekan/wekan/wiki/Cover#card-attachment--menu-set-cover-image

**Comment by Meeques** [comment]
Alright, then it is what it is. I like the option you will add, thanks!

**Comment by mohammadZahedian** [comment]
@xet7 it would be nice if background image also appear on "board card" in "boards list items" ( all board page )

![image](https://github.com/wekan/wekan/assets/25129673/6f184fbf-1b93-45e8-a548-110afa4e70de)
![image](https://github.com/wekan/wekan/assets/25129673/772cc4d4-76a3-4681-936d-83bc37102513)

**Comment by mohammadZahedian** [comment]
> @xet7 it would be nice if background image also appear on "board card" in "boards list items" ( all board page )
> 
> ![image](https://user-images.githubusercontent.com/25129673/244341439-6f184fbf-1b93-45e8-a548-110afa4e70de.png) ![image](https://user-images.githubusercontent.com/25129673/244341449-772cc4d4-76a3-4681-936d-83bc37102513.png)

is it hard to do?
