### ISSUE TITLE
Problem with the information of the cards located at the edges of a board

### ISSUE THREAD

**Issue by SmartPhoneLover** [wekan/wekan#4861]
### Issue
When you have not too many columns, or you have a big monitor (wekan has more left-right space), no problem.
But, if you have as many columns to be able to reach the **right side** of the window, when you try to open the information of a card in that specific column, you will notice that the card's information is now cut and cannot be shown correctly.

### Reproduce
Create as many columns as needed to reach the right side of your browser's window and add a card. Then, try to open the information of that card.

### Desired Behavior
The window that shows the information of a card should be resized and/or displaced dynamically.

### Server Setup
* Did you test in newest Wekan?: Yes (v6.78.0)
* Did you configure root-url correctly so Wekan cards open correctly?: Yes
* Operating System: unRAID OS (OS for NAS)
* Deployment Method: Docker
* Http frontend if any: No
* Node.js Version: v14.21.3
* MongoDB Version: v4.4.10
* What webbrowser version are you using? latest (Firefox)

### More Information
Here I include some screenshots where I show it:

![Desktop 17-03-2023 19-12-22](https://user-images.githubusercontent.com/42898749/225993040-f72eec68-4f74-4d65-8860-5ed9b0c7b8a9.jpg)
![Desktop 17-03-2023 19-12-23](https://user-images.githubusercontent.com/42898749/225993042-2382e41d-ffbe-4eaa-9f35-bd11b9074f1d.jpg)

**Comment by mohammadZahedian** [comment]
i have same problem

**Comment by mohammadZahedian** [comment]
it also happend when you open label list of a card that is in end of a list
you shoud scroll down

it can be solve in this way:

it should see the location of the card: if it is in right half of page it should be opened in left side
or if in half bottom of page, open in top of the card

**Comment by mohammadZahedian** [comment]
@xet7

**Comment by xet7** [comment]
Fixed in newest WeKan.

**Comment by mohammadZahedian** [comment]
it is fine that open full width ?

![image](https://user-images.githubusercontent.com/25129673/230705553-a3402e83-0956-42e3-a7a6-6bf1fcd0dbb1.png)

**Comment by xet7** [comment]
@mohammadZahedian 

Yes. I got it working full width.

I did not get it working yet in any other way yet, in those cases card was sometimes not visible.
