### ISSUE TITLE
Feature Request: Get error message when upload files are too big

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4863]
Hello, 
When a file is uploaded that is over maximum size, the user will see that it is uploaded and then it disappears without a message. This confuses users.
Thank you!

**Comment by ClaudiaK21** [comment]
What is the current maximum size? OR max. width and height too?
I tried to upload an avatar which has only 199 kb.

I couldn't but there is no info given in our current wekan instance. 

For translation I need to know more details, thanks in advance :)

**Comment by xet7** [comment]
@ClaudiaK21 

By default, there are not any limits. Limits are only visible at card attachments and avatar upload if they are set. There is not any number of max size etc added to translated strings directly, numbers come from that setting that can optionally be added.
- https://github.com/wekan/wekan/blob/master/docker-compose.yml#L277-L287
- https://github.com/wekan/wekan/blob/master/snap-src/bin/wekan-help#L133-L167
