### ISSUE TITLE
scrolling is too hard or impossible in mobile 

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#4866]
in mobile:
1) it is impossible for me to scroll in boards page:

![board](https://user-images.githubusercontent.com/25129673/227223602-1e0a32eb-39d9-4e13-af1a-431f71665024.gif)

2) its hard to scroll in swimlanes:

![swim](https://user-images.githubusercontent.com/25129673/227223687-96bd5154-efac-492d-8781-35cb369f74cc.gif)

3) it is  very hard to scroll between cards in a list:

![list](https://user-images.githubusercontent.com/25129673/227225037-8b041e76-7b04-4aa7-82ff-d189223a14af.gif)

**Comment by mfilser** [comment]
Which Wekan Version?

**Comment by mohammadZahedian** [comment]
> Which Wekan Version?

snap 6.79.0

**Comment by xet7** [comment]
@mohammadZahedian 

I added docs:

https://github.com/wekan/wekan/wiki/Drag-Drop
