### ISSUE TITLE
Wekan installation

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#4874]
Hello,

I want to install Wekan but i found many methods to do that.
What's the difference between them and how to know the suitable option for me.

thanks

**Comment by xet7** [comment]
@MeriemBH 

## Linux amd64: Snap

If you have Linux that has Snap, like those distos mentioned here, easiest is to install Snap, and it has automatic updates:
https://snapcraft.io/docs/installing-snapd

Installing is like this, when your computer or server has IP address like 192.168.0.200:
```
sudo snap install wekan --channel=latest/candidate
sudo snap set wekan root-url='http://192.168.0.200'
sudo snap set wekan port='80'
```
Some related info is here:
- https://github.com/wekan/wekan/wiki/OpenSuse

Then you register first user that will be admin at http://192.168.0.200/sign-up and login at http://192.168.0.200/sign-in

## Windows

If you are using only Windows, you can try install like this: https://github.com/wekan/wekan/wiki/Offline

## Windows and Mac: Docker

Or alternatively, install Docker Desktop, and use docker-compose.yml from https://github.com/wekan/wekan , edit it to have that ROOT_URL=http://192.168.0.200 , and then `docker-compose up -d`

## Different CPU

If you have computer that has different CPU, not x86_64, some info here https://github.com/wekan/wekan/wiki/Raspberry-Pi

**Comment by xet7** [comment]
If you are setting public server, you can Snap like above, and Caddy2 at front of it:
https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config
