### ISSUE TITLE
OIDC: invalid scope parameter with Keycloak 21

### ISSUE THREAD

**Issue by frezik** [wekan/wekan#4878]
Running Wekan via snap, version 6.09, and Keycloak 21.0.1. Trying to login via OIDC, the window pops up and disappears immediately.

Keycloak logs show: `KC-SERVICES0093: Invalid parameter value for: scope`

Was able to fetch the URL out of the nginx logs, which shows the scope parameter of `scope=%27openid%20profile%20email%27`.  The %27 is a single quote char. If I remove those and try to open it in a browser, I get a different error in the keycloak log (`Parameter 'client_id' not present or present multiple times in the HTTP request parameters`). Which might just be due to opening it in a browser directly. The original error is present if I open the URL with the quote chars in the browser, so that client_id issue does seem to be a step past the scope issue.

**Comment by xet7** [comment]
@frezik 

#Keycloak

https://github.com/wekan/wekan/wiki/Keycloak

# Docker

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L467

# Snap

https://github.com/wekan/wekan/blob/master/snap-src/bin/config#L315

https://github.com/wekan/wekan/blob/master/snap-src/bin/wekan-help#L357

# Bundle / Source

https://github.com/wekan/wekan/blob/master/start-wekan.sh#L253

https://github.com/wekan/wekan/blob/master/start-wekan.bat#L204

https://github.com/wekan/wekan/wiki/Raspberry-Pi

https://github.com/wekan/wekan/wiki/Offline

https://github.com/wekan/wekan/wiki/Emoji
