### ISSUE TITLE
click-and-drag to label no longer works

### ISSUE THREAD

**Issue by jadeqwang** [wekan/wekan#488]
I used to be able to click and drag a label from the sidebar onto a Wekan card, and the card would get the label. Now, that no longer works. In order to label a card, I have to open the card and use [+] under Labels.

Other details: using Wekan on Sandstorm (latest version); Chrome on Mac.

**Comment by nata-g** [comment]
Yep...I have the same issue

**Comment by nata-g** [comment]
For whatever reason it seem to be working now on my local instance!!!

**Comment by SgtPooki** [comment]
Can we add a 'sandstorm' label for the fact that this is only occurring on the sandstorm instance?

**Comment by ahkimkoo** [comment]
chrome v 48， same problem

**Comment by nztqa** [comment]
TEST: Sandstorm app demo
It seems to happen after clearing the filter.
There is no log on the console.

Related #879

**Comment by lindhork** [comment]
Just tested this on v4.95, the problem doesn't seem to exist anymore.
