### ISSUE TITLE
Improving card open position in WeKan v6.82 and newer

### ISSUE THREAD

**Issue by SmartPhoneLover** [wekan/wekan#4882]
## Issue
With the latest release (fixing my [latest report](https://github.com/wekan/wekan/issues/4861), thanks!), if you have more than a single Swimlane in a board, when you click a card, the window containing its information is not opened in the current position, and depending on if the window has more or less information on it (bigger or smaller size), you can (or cannot) scroll with mouse.

### Reproduce
Create a board, and add at least, 2 Swimlanes.
Then, create as many cards in a column as needed to fill the entire column. The same for both Swimlanes.
Now, try to open the information of a card from the first swimlane (top). Then, open the information of a card located in the second swimlane. You will notice that you won't have any problem with the cards located inside the first swimlane, but you will have to scroll up (if possible) for the cards contained on swimlanes below it.

### Desired Behavior
The window showing the information of cards from swimlanes located below the first one, should be popped-up/shown in the current position, not at the begining of the page.

### Server Setup
- Did you test in newest Wekan?: Yes (v6.82.0)
- Did you configure root-url correctly so Wekan cards open correctly?: Yes
- Operating System: unRAID OS (OS for NAS)
- Deployment Method: Docker
- Http frontend if any: No
- Node.js Version: v14.21.3
- MongoDB Version: v4.4.10
- What webbrowser version are you using? latest (Firefox)

### More Information
![9238473983294492-1](https://user-images.githubusercontent.com/42898749/230624598-5a2b860f-b818-40a7-b924-9ecb385cca94.JPG)
![9238473983294492-2](https://user-images.githubusercontent.com/42898749/230624609-730d4693-5903-4d61-b651-e1794417b995.JPG)
![9238473983294492-3](https://user-images.githubusercontent.com/42898749/230624616-e417a217-de32-4fcf-9c51-f09da289f042.JPG)

**Comment by BabyFnord** [comment]
Similar issue here:
Upgrading my bundle installation from v6.81 to 6.82, and using browsers ungoogled-chromium 111.0.5563.146 (Official Build, macos) (x86_64), Safari 14.1.2. The card window is completely off the screen, no chance to edit anything. This only happens to empty cards, when Swimlanes exist.

![Card window does not open](https://user-images.githubusercontent.com/39904614/230668661-74e6c360-bcac-409c-b304-400d50842b4d.gif)

Reverting now to v6.81, this bug renders WeKan v6.82 unusable 🙁.

**Comment by xet7** [comment]
@BabyFnord 

What macOS version are you using? That is not the newest Safari.

**Comment by xet7** [comment]
Current Safari version is 16.4

**Comment by xet7** [comment]
Some web search did show about Safari:

Safari 14.1.2. Released September 13, 2021. WebKit. Available for: macOS Catalina and macOS Mojave

**Comment by BabyFnord** [comment]
@xet7 I'm on macos 10.14.6 and aware it's the trailing edge of technology, hence, I use ungoogled-chromium 111.0.5563.146 for WeKan, which afaik is the current release.

**Comment by xet7** [comment]
@BabyFnord 

It depends can I duplicate your bug some way. I have tried:
- Newest Safari on M1
- Newest Firefox, Chrome, MS Chromium Edge on Ubuntu 22.10

But I did not have any of those problems yet. I will try other browsers soon too.

**Comment by xet7** [comment]
On Linux, using Ungoogled Chromium from Flatpak, cards opens always on top of all swimlanes:

![ungoogled](https://user-images.githubusercontent.com/15545/230677263-35df7a8e-ba91-4ec3-9be3-11036818a958.png)

**Comment by BabyFnord** [comment]
Thank you for looking into this @xet7 ! 

I did not test it with LibreWolf 111.0.1-1 (which I only use for skipping paywalls), as I have already reverted to v6.81 to finish some work. I stopped using Firefox for their unsolicited telemetry, favouring ungoogled chromium now for its own render engine. A newer version of Safari won't run on this OS. Do you suggest that the latest ungoogled chromium still renders issues related to browsing WeKan on an obsolete OS version?

**Comment by xet7** [comment]
Currently it looks like it does not depend on browser version. I'll try to fix, is this just about CSS z-index bug.

**Comment by BabyFnord** [comment]
Kiitos @xet7 !

**Comment by BabyFnord** [comment]
Confirmed working here w/ all above mentioned browsers. Thank you so much, @xet7 ⚡️☺️
