### ISSUE TITLE
Description in minicard: bullet points overlay each other 

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4888]
If there is a list in the description of a card, the last bullet point is overlayed with the second last one, creating this view:
![Beschreibungstextminikarte](https://user-images.githubusercontent.com/92315677/231975552-3fd245a9-df22-409b-b3cd-3bea0fe4a07c.jpg)

**Comment by xet7** [comment]
@Meeques 

What version of WeKan you have?

I think this was fixed at [WeKan v6.46](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v646-2022-09-15-wekan--release): Added limit description on minicard to three lines. Thanks to @helioguardabaxo .
