### ISSUE TITLE
Request - Delete Card in the first menu visible - without opening the card?

### ISSUE THREAD

**Issue by ClaudiaK21** [wekan/wekan#4889]
I wonder why the Delete card option is only available in three steps
1. open the card
2. click the three dot menü
3. click more

Why can't we have the delete option in the menu three dot view in the first menu, without having to open the card?
Or at least the "more" option here too.
I have to delete more than 10 cards now and this 3 steps (4 to delete) takes too much time.

We don't need to archive all sorts of cards and then delete (this will easily be forgettable :)
![grafik](https://user-images.githubusercontent.com/79307821/231993696-e8a31e19-360a-411f-878e-d7647a3f3b22.png)

**Comment by xet7** [comment]
Because #1341
