### ISSUE TITLE
how can i install meteor releated packages manually?

### ISSUE THREAD

**Issue by cenjoy** [wekan/wekan#489]
when i run wekan(https://github.com/wekan/wekan) by meteor,but i download some related packages failed. error messages are as follow:

test@cenjoy:~/project/wekan$ meteor 
Sorry, this project uses Meteor 1.2.2-faster-rebuilds.0, which is not installed and could not be downloaded. Please check to make sure that you are online. Downloading meteor-tool@1.1.11-faster... [ ] 0% 0.0s***

so,how can i install meteor releated packages manually?

**Comment by hsduk** [comment]
hi, try `meteor update` first then `meteor`

**Comment by mquandalle** [comment]
@cenjoy Did you figure out. From your log output, the issue doesn’t seem related to Wekan. Maybe it was just a connectivity issue?

**Comment by cenjoy** [comment]
@mquandalle @hsduk thanks. it is indeed a connectivity issue. I've solved the problem by copying  meteor releated packages from a diffirent server
