### ISSUE TITLE
move card causes lag

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#4893]
moving card to another board causes about 4 sec lag
sometimes it takes 10 sec
@xet7

**Comment by xet7** [comment]
Yes, that's possible, when card has a lot of checklists, attachments, etc.

Some newer versions of WeKan will have speed improvements.

**Comment by mohammadZahedian** [comment]
for me it happens with simple cards

**Comment by xet7** [comment]
@mohammadZahedian 

How much there is free RAM ? Or is it using swap, slowing down? Try with this:
```
free -h
```

**Comment by xet7** [comment]
@mohammadZahedian

> moving card to another board causes about 4 sec lag
> sometimes it takes 10 sec

Is this on laptop or smartphone? What model?

What operating system and version?

What webbrowser and version?

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/4578#issuecomment-1511879386

**Comment by mohammadZahedian** [comment]
> Newest WeKan has many fixes. Any new WeKan version can bring speed improvements etc.

![image](https://user-images.githubusercontent.com/25129673/233989005-2101195d-c7b4-478f-9f11-e9f68c65e705.png)
