### ISSUE TITLE
email configuration

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#4894]
Hello,

i installed wekan on ubunto via snap.
Unfortunately, i found that there is no mail server within.
What should i do?
i did some research but i couldn't figure the easiest way with details.

thanks

**Comment by xet7** [comment]
WeKan works for example with sending email with AWS SES, by configuring mail-url and mail-from:

https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

https://github.com/wekan/wekan/blob/master/snap-src/bin/wekan-help#L63
