### ISSUE TITLE
[Bug] Normal board-user can archive boards from overview page

### ISSUE THREAD

**Issue by colletda** [wekan/wekan#4896]
Wekan 6.81.0, Meteor 2.11.0, Node 14.21.3, MongoDB 5.0.14

Is this a bug? Normal board-user can archive a board from the overview page. Not only for himself, the board is moved (for all users) to the archive. Only the board-admins can restore the board from the archive.

In the boards-settings, this function is for normal board-user not possible. Only board-admin can archive a board from board settings.

Daniel

**Comment by xet7** [comment]
I tried WeKan 6.85. Normal user can not archive board, button to archive board is not visible. Only BoardAdmin and Admin can archive bord.

I don't know what do you mean with overview page. Maybe All Boards page (or Public Boards page) ? On those, normal user can not archive board.

If you have more details, please reopen issue.
