### ISSUE TITLE
Rules - Put card with label XX on top of its list doesn't work - moves it on top of first list instead 

### ISSUE THREAD

**Issue by C6lDubois** [wekan/wekan#4898]
Hello, 

My colleague and I tried  tired to make a rule to put cards with a certain label on top of their list when the label is added. 

It doesn't work properly : when we ad the label, it moves the card on top of the first list on the left. 

Here is an example - I want to put card with a nex "Critical" label on top of its list
![image](https://user-images.githubusercontent.com/129739111/233298510-278c5dcd-24de-4338-a835-874f3509df14.png)
Here is the rule I created

![image](https://user-images.githubusercontent.com/129739111/233298822-89e0f8f7-8913-4d48-8ac5-bf8b69cfd930.png)

I tried with "'Card 4" then "Card 3" and here is the result 

![image](https://user-images.githubusercontent.com/129739111/233298978-77c3c804-7eb1-4c1a-af70-e03e36acbe57.png)

We are on v6.84.0, I'm aware it's not the latest version - but I checked and I didnt find this bug report on github, or a correction to this issue in v6.85 change log 

Thank you for your help

**Comment by kgts23** [comment]
Same bug under v7.09.0 (dockerized) but for us, the card disappears completely on the board. The direct link won't show the card. Its gone, forever....

**Comment by xet7** [comment]
@C6lDubois @kgts23 

Hmm, does it not get correct list id here?

https://github.com/wekan/wekan/blob/master/server/rulesHelper.js#L70-L84

I'll try to add some logging and check.

**Comment by xet7** [comment]
@C6lDubois @kgts23 

I added some logging:

```
repos/wekan % git diff
diff --git a/server/rulesHelper.js b/server/rulesHelper.js
index a2a10fba7..71baeac79 100644
--- a/server/rulesHelper.js
+++ b/server/rulesHelper.js
@@ -1,4 +1,5 @@
 import { ReactiveCache } from '/imports/reactiveCache';
+import { Log } from 'meteor/logging';
 
 RulesHelper = {
   executeRules(activity) {
@@ -68,19 +69,23 @@ RulesHelper = {
       let listId;
       if (action.listName === '*') {
         list = card.list();
+        Log.info('List1: ', list);
         if (boardId !== action.boardId) {
           list = ReactiveCache.getList({ title: list.title, boardId: action.boardId });
+          Log.info('List2: ', list);
         }
       } else {
         list = ReactiveCache.getList({
           title: action.listName,
           boardId: action.boardId,
         });
+        Log.info('List3: ', list);
       }
       if (list === undefined) {
         listId = '';
       } else {
         listId = list._id;
+        Log.info('ListId4: ', listId);
       }
 
       let swimlane;
```
When I added label critical to card, there was these logs:
```
I20230915-16:59:36.925(3) (rulesHelper.js:82) List3: 
I20230915-16:59:36.926(3) (rulesHelper.js:88) ListId4:
```
So there was no list ID at all?

@mfilser 

How to get list ID ?

**Comment by xet7** [comment]
The above way to add logging did not work, so I added webhook to http://127.0.0.1:7000 with https://github.com/wekan/webhook . With it, I can see this webhook content. I'll test some more.

**Comment by xet7** [comment]
Adding label seems to trigger `act-addedLabel` webhook:
```
[Fri Sep 15 17:39:39 2023] 127.0.0.1:54937 [200]: POST /
[Fri Sep 15 17:39:39 2023] 127.0.0.1:54937 Closing
[Fri Sep 15 17:39:39 2023] 127.0.0.1:54938 Accepted
Webhook received: Array
(
    [text] => testtest Added label __label__ to card "Card 3" at list "List 3" at swimlane "Swimlane 1" at board "Board 1"
http://localhost:4000/b/SegjCMcBkQy9NmfnC/board-1/fNBSkS6Pu3kwXStd7
    [cardId] => fNBSkS6Pu3kwXStd7
    [listId] => WLxCq8ZJuBFyBkmHZ
    [boardId] => SegjCMcBkQy9NmfnC
    [user] => testtest
    [card] => Card 3
    [swimlaneId] => p6QuEH7CuAGfMj6gC
    [description] => act-addedLabel
)
```

**Comment by xet7** [comment]
Hmm, that webhook does not have label name?
