### ISSUE TITLE
new members only able to register at home page

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#490]
i sent a direct link to a board to someone. they were able to see it, but not register or interact with it 

(firefox ios)

**Comment by hsduk** [comment]
did you try using the `/sign-up` page available at yourwekaninstall.com/sign-up and then add that user to the board?
Probably better to have a clearer signup link or popup displayed when an unknown user accesses a board link for the first time.

**Comment by AndyatFocallocal** [comment]
yeah, people could link to the site from all over - and we'd never know as they cant login or register. should be pretty simple to stick a box in the menu with a link to the sign up page, right?

**Comment by xet7** [comment]
Moved to #3022
