### ISSUE TITLE
Blank space

### ISSUE THREAD

**Issue by jas01** [wekan/wekan#4901]
## Issue

* Did you test in newest Wekan?: Yes
* Operating System: Server : Debian, Client : Arch linux
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* wekan: 6.85 (but alsol old version)
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?: Firefox/Chromium

### Problem description
I've got since long time some blank space between board and I try every (well lots of ) possibles moves, those blank are still here. 
If try to find if they're any weird characters inside the «last» board (before blank) and don't find any.
If I report only now (the problem are present since 1 year), it's because now sometime when I open wekan thoses boards jump place to place and it's become very annoying.
Note : Only me have this problem.
![Screenshot 2023-04-22 at 11-09-03 https __wekan obspm fr](https://user-images.githubusercontent.com/11524096/233775147-5908d668-15d5-430c-b641-837424014826.png)

**Comment by xet7** [comment]
Blank space is maybe because board icon height depends on how much it has text. I'll think about it.

Jumping boards is this different issue, that I'm thinking how to fix https://github.com/wekan/wekan/issues/4214
