### ISSUE TITLE
Feature Request: Set height of Swimlane

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#4904]
WeKan Version 6.85.0

If I have more than one swimlane, I want to set the height of swimlanes, so I don't have to worry about my list getting too long and having to scroll, even if there are only a few but high cards. 
Let's say I have 6 pretty high cards in list 1 on swimlane 1. With only one swimlane, I don't have to scroll in the list to see all minicards. I add one swimlane and now the 6 cards from swimlane 1 are not displayed all at once but I have to scroll to see them all. If I could set swimlane 2 to be so far under swimlane 1 that all my minicards are displayed at once, that would be great.

Thanks for reviewing!

**Comment by Meeques** [comment]
Hi @xet7, I just wanted to let you know some additional info. Not every user on every board wishes that the swimlane adapts to the list length, so an optional feature would be the best option. People can decide (boardspecific) if they want a scroll bar for their long lists or if the next swimlane should start whereever the longest list ends (no scollbar). 

I'm also adding a screenshot of the 'problem':

![2023-07-18_111324](https://github.com/wekan/wekan/assets/92315677/eb2eb718-5b0e-45b4-b34a-342a08bbf7c2)

**Comment by xet7** [comment]
@Meeques 

Do you mean per-board per-user setting (saved to per-user profile), height of all swimlanes?

I think scrollbar appears, when there is more cards in list than fits to screen.

**Comment by xet7** [comment]
@Meeques 

Another way could be, User Setting, height of all swimlanes at all boards.

**Comment by Meeques** [comment]
@xet7 thanks for the fast reply. Ideally, the setting would be per board, not per user. Boardadmins can then set height of swimlanes to either default (scrollbar) or adapt to list length (no scollbar). With the option where there is no scrollbar, you would scroll the entire Board to get to the end of the list, so no need for one, if that makes sense.

**Comment by xet7** [comment]
Oops I implemented most of this feature https://github.com/wekan/wekan/commit/b56018db05f9881abc9e85ef88949c11d3907cbd . 

@helioguardabaxo Do you understand what is missing from that code, can you add the remaining? It's popup at Swimlanes hamburger menu option is similar how WIP limit setting popup is done. It also sets some CSS similar like in Background Image feature.

**Comment by xet7** [comment]
@Meeques 

It depends on feature, some are easy and fast to implement, some take many tries and thinking how to get it working. Suprisingly here I got most done on first try.

**Comment by helioguardabaxo** [comment]
@xet7 
I will try to implements this week.

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/pull/4964 and https://github.com/wekan/wekan/pull/5059 . Thanks to @mark-i-m !

It is at newest WeKan already.

**Comment by Meeques** [comment]
Thank you! 
Is there a height cap? everything above 2000 doesn't do anything

**Comment by mark-i-m** [comment]
Perhaps it is this line:

https://github.com/mark-i-m/wekan/blob/4b04af9a9cecbc3b4fb3e3968c51d7499db38aa5/client/components/swimlanes/swimlanes.css#L50

**Comment by Meeques** [comment]
the cap is throwing the same behaviour as before. Swimlane height grows with tasks, but there is a max. The request was to overcome the max so you can avoid having a scroll bar

**Comment by xet7** [comment]
@Meeques 

I presume you still have WeKan v7.09. This fix is in upcoming Wekan release v7.10, it is not released yet. When I tested this fix, it did remove the limit.

**Comment by Meeques** [comment]
Oh, I didn't know that. Thank you!
