### ISSUE TITLE
Change order of starred boards?

### ISSUE THREAD

**Issue by noppelmax** [wekan/wekan#4907]
Hey everybody,

first of all thanks for your timeless effort!

I just started to use starred boards, which are then shown in the navbar. However, i couldn't figure out how to change the order of them. It does not seem to be the order in which i fav them, nor the lexicographical order. It would be fine for be to order them lexicographically. I could just add "00_", "01_" ... to them. Is there any way of enabling that?

Kind regards,
Max

**Comment by alexanderbazo** [comment]
Hi,
Correct me if I am wrong, but I think that the order of the starred boards is the same as the order on the dashboard ("All boards"). When you reorder them per Drag & Drop, the position in the navbar should change to.

![wekan-reorder-navbar](https://user-images.githubusercontent.com/946672/235088306-a480c2b3-d5f6-4873-8baa-b439f66cfb25.gif)

**Comment by noppelmax** [comment]
Oh! Yes that works! Thanks a lot!
