### ISSUE TITLE
mail not working

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#4908]
Hello,

i installed wekan-gantt-gpl with snap.
i tried the following snap command for mail configuration for both gmail and yahoo:

sudo snap set wekan-gantt-gpl mail-url='smtp://user:pass@smtp.mail.yahoo.com:465'
sudo snap set wekan-gantt-gpl mail-url='smtp://user:pass@smtp.gmail.com:25'

But i alwyas get the same error:  **sending email failed ,error trying to send email greeting never received.**

I even tried the same command by adding secureconnection=false:

sudo snap set wekan-gantt-gpl mail-url='smtp://user:pass@smtp.mail.yahoo.com:465'?tls={ciphers:"sslv3}&secureconnection=false'

thanks,

**Comment by xet7** [comment]
@MeriemBH 

I added Gmail example from some other issue to https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#gmail

I do not have working Yahoo example yet.
