### ISSUE TITLE
move lists between boards

### ISSUE THREAD

**Issue by divramod** [wekan/wekan#491]
Hey, is it possible to move lists from one board to another?

It would also be nice to make it possible to link lists in different boards.

if not, can i help to implement it?

**Comment by pgrm** [comment]
This would be great, I just want to mention, how could such a feature work in the sandstorm version of the application? - Maybe it would be time to allow for multiple boards to be able to create boards which belong together? (We have backlog, spring and archive boards in trello to have a better focus).

**Comment by ocdtrekkie** [comment]
@pgrm: Once Sandstorm has the Powerbox fully implemented, you could essentially share a list from one Wekan grain to another Wekan grain, which would copy it.

**Comment by pgrm** [comment]
@ocdtrekkie oh awesome, looking forward to that than :smile:

**Comment by M4urice** [comment]
Any news on this?

**Comment by hradec** [comment]
I'm also looking forward for this one!

**Comment by xet7** [comment]
@hradec 

I'm not sure about that PowerBox style moving, but in general:

If someone would like to implement this like import/export list, that someone can look at `wekan/models/*.js` for import/export code, and similar export menu options at `wekan/client/components/sidebar/sidebar.*`. For searching Wekan code:
```
cd wekan
./find.sh import
./find.sh export
```
Wekan already has code how to:
- Import from Trello
- Import/Export from Wekan as JSON
- Import/Export CSV/TSV (could be improved, though)
- Copy/Move Card to same or another board
- Duplicate Board

So with that existing code, it would be possible to add features like:
- Copy/Move List to same or another board
- Copy/Move Swimlane to same or another board
- Duplicate List
- Duplicate Swimlane
- Import/Export List as JSON
- Import/Export Swimlane as JSON

That Import/Export List/Swimlane would work in Sandstorm also, without any PowerBox usage.

Wekan API code is at `wekan/models/*.js`. With current API, it's possible to read and write cards etc https://wekan.github.io/api/ , but AFAIK those List/Swimlane features mentioned above have not been implemented yet.

It would be nice if some Wekan contributor would have time to implement these. Those Clone Board etc features have also been added by some contributors.

Sure it's also possible to fund me at https://wekan.team/commercial-support/ so I would implement these, it's just that having many contributors in Wekan would make much faster progress, that just me coding everything. For these List/Swimlane Copy/Move features there already is existing similar code, so it would only require some contributor to have some free time.

**Comment by xet7** [comment]
Moved to #3531
