### ISSUE TITLE
invitation via mail

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#4915]
Hello,

the invitation via mail is not working.
Am i missing some configuration?

thanks,
Meriem

**Comment by xet7** [comment]
For sending email, did you configure AWS SES, Gmail or ProtonMail Bridge?

https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by xet7** [comment]
I think it's better that you add new users, passwords etc at Admin Panel / People / People.

At Admin Panel, you could also disable self-registration.
