### ISSUE TITLE
board not found

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#4916]
Hello,
i installed wekan gantt.
Sometimes, when i click on the task, the following message appears:board not found.
I have to refresh the web page as a workaround.
Is there any solution for that?

thanks

**Comment by xet7** [comment]
What version of WeKan you are running?

**Comment by MeriemBH** [comment]
wekan-gantt-gpl 6.09.0

**Comment by xet7** [comment]
Newest WeKan is v6.86. That v6.09 could very likely have some bugs newest WeKan does not have.

I recommend you wait for automatic upgrade, developing that is In Progress, status of progress is reported at this issue https://github.com/wekan/wekan/issues/4780#issuecomment-1512246404
