### ISSUE TITLE
short name for actions

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#4919]
@xet7 
i am using this menu for two month but still it takes me some times  to find the option i want:

![image](https://github.com/wekan/wekan/assets/25129673/5dafcbaf-58e6-4915-b236-233cce38666e)

i think because the option names are two long
for example i am looking for label but the first word is edit...

and also they should be ordered by frequently used option.

look the trello options name:
![image](https://github.com/wekan/wekan/assets/25129673/90abe54f-4711-4e8a-b61c-113519b95643)

i suggest this names and order:

Move
Copy
Archive
Lable
Due date
Color
Link

**Comment by xet7** [comment]
I don't understand how this would be any improvement. I think WeKan menu looks much more clear than Trello menu.

**Comment by xet7** [comment]
But someone could try to explain better.

**Comment by mfilser** [comment]
I also don't see any improvements. Wekan is Wekan and not Trello 2 for free

**Comment by xet7** [comment]
Trello has worse design than WeKan. I don't know how to hide those too many extra menus in Trello, when I rarely login to Trello. I'm just used to WeKan design, everything is where it is designed to be.

For any kind of WeKan updates, there could be internal changes, anyway UI will stay like it currently is, only minor improvements.

**Comment by mohammadZahedian** [comment]
> I don't understand how this would be any improvement. I think WeKan menu looks much more clear than Trello menu.

what i am saying is that: when i am looking for Label option it takes me  3 sec to find it
i think that's because keywords are not distinct some way

i have three suggestion:

1- put keywords at first,  for example "Label editing"
2- make keyword bold, like " edit **label** "  or give them different color
3- make option just one word and more detail appears when we hover on it as tooltip
