### ISSUE TITLE
Board of boards 

### ISSUE THREAD

**Issue by whittssg** [wekan/wekan#492]
Is it possible to have a board of boards?  I would like to use it to track projects and thought that if I could have a board that contains lists like not started started testing and complete and withing each list I could have a card that linked to a project (another board).

**Comment by vrms** [comment]
in other words that would be something like a parent/child attribute any board could have.
So if a board is a child, then you will point it to it's parent. inside of the parent board each 'child' just appears as a card which can be shifted through the board as usual, right?

I agree, that would be a super slick feature to have. Video editing software often has such a feature and they call it 'nesting'. I think it would be important to super easy get in and out of such a child board/card and easily jump back to the parent board

**Comment by whittssg** [comment]
@vrms Exactly :)

**Comment by ScarabMonkey** [comment]
This is exactly what I have been thinking about! I would go one step further and make any card able to be promoted into a board. This would be a killer feature that is better than trello and could even be a better system than checklists.

**Comment by jonathan-chin** [comment]
+1

I would love this functionality and / or a list of lists

**Comment by andresmanelli** [comment]
Hello, I started an implementation for this feature. It's still a work in progress, but here are some screenshots:

![seleccion_006](https://user-images.githubusercontent.com/7302217/37677255-4fee0b6a-2c59-11e8-963c-e6afd217c673.png)
Here, next to the `Add` button, you can select `Import` (from dropdowns) or `Search` (an entire board).

![seleccion_004](https://user-images.githubusercontent.com/7302217/37677045-88ab920c-2c58-11e8-92f0-7a7a846623ce.png)
In the `Import` popup, you cad `Import` the selected board (next to the board name), or the selected card (at the bottom of the popup).

![seleccion_005](https://user-images.githubusercontent.com/7302217/37677073-a902243a-2c58-11e8-9c2b-f58a79b0a63e.png)
In the `Search` popup, you can `click` in the card to import and `search` with the text input (hitting enter).

I am working in displaying the imported card details, and in providing a 'link' button to the imported board _in the details view of the card that represents the board_.

What I find handful about the detailed view of a board, is that you could add checklists to that board (like partial implementations needed by root project).

Any comments are welcome!

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/pull/1592
