### ISSUE TITLE
the latest version deploy in k8s cannot change language 

### ISSUE THREAD

**Issue by lihongbo138** [wekan/wekan#4920]
### Server Setup Information

* Did you test in newest Wekan?:
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

**Comment by lihongbo138** [comment]
image:
  repository: wekanteam/wekan
  tag: v6.87

this images deploy in k8s cannot change to other language

**Comment by xet7** [comment]
@lihongbo138 

- How did you install k8s and WeKan? What commands and steps you used?
- What versions of OS and software you use?
- What webserver is at front of WeKan?

**Comment by lihongbo138** [comment]
I install k8s by helm chart  wekan-1.4.4.tgz. and language cannot change.

I trid today by version v6.15 ,and it works succesful.

**Comment by xet7** [comment]
@Nightreaver

Does this happen to you too with newest WeKan ?

**Comment by lihongbo138** [comment]
I install k8s on baremetal with kubekey which  based  kubeadm. the k8s version is v1.22.10. and install ceph  with rook-operator.

**Comment by xet7** [comment]
To have translations working, it needs correct settings https://github.com/wekan/wekan/issues/4874#issuecomment-1499677728
