### ISSUE TITLE
Backup Wekan Gantt GPL

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#4924]
Hello,

Once i follow the steps described in this link  [https://github.com/wekan/wekan/wiki/Backup], will the backup run daily automatically?

thanks,

**Comment by xet7** [comment]
@MeriemBH 

https://github.com/wekan/wekan/wiki/Backup#scheduled-backups-to-local-or-remote-server

**Comment by MeriemBH** [comment]
Hello, 
the steps described in the link you sent differ from the link i wrote in the first comment.
Is this another suggestion?

**Comment by MeriemBH** [comment]
@ [xet7](https://github.com/xet7) what do you think about the comment above?
thanks

**Comment by xet7** [comment]
@MeriemBH 

It depends do you have Docker or Snap version of WeKan, and is there file in those directories, would it be good to backup those additional directories too.
