### ISSUE TITLE
Wekan API - updating custom fields on a card

### ISSUE THREAD

**Issue by RazvanTinca** [wekan/wekan#4927]
I'm using the latest version of Wekan in a docker container, everything works fine but I've tried to use the api, and so far it is great.
I'm trying to automated a few workflows and I've come to a blocking point where I'm trying to call the endpoint for updating a custom field. I've tried it first in n8n with a custom HTTP Request but it doesn't return anything, next I've tried with a HTTP Client (Insomnia) to manually call the endpoint and it seems that I get an 405 Method not allowed. I've tried to play with the content that I'm sending, to change the content type but it doesn't work.

![image](https://github.com/wekan/wekan/assets/17953262/d37b1af5-8228-4873-9ab9-9abad68cc3ff)

Any ideas on what I can do ?

**Comment by xet7** [comment]
@RazvanTinca 

Hmm, I just checked docs, adding checklist item is in wrong source code file, it should be in checklistItems.js, not in checklists.js .

It is here:
- https://wekan.github.io/api/v6.89/#new_checklist_item
- https://github.com/wekan/wekan/blob/master/models/checklists.js#L387

It should be near here:

- https://github.com/wekan/wekan/blob/master/models/checklistItems.js#L286

It seems I have not yet added example about adding checklist item:

- https://github.com/wekan/wekan/blob/master/api.py#L35

**Comment by xet7** [comment]
Sorry, you did mention Custom Fields, not Checklist Items. Sorry, I'll think again.

**Comment by DimDz** [comment]
Using Postman I can change or put a value on Custom Fields
![Screenshot_1](https://github.com/wekan/wekan/assets/70445835/cd677572-ba25-408f-a146-896da9151d31)
![Screenshot_2](https://github.com/wekan/wekan/assets/70445835/0cda2b19-5879-4a79-bb16-686f9c529557)

**Comment by DimDz** [comment]
I am using latest, check that you pasted correctly the bearer token on Authorization and then on your headers Content-Type and Accept with values of application/json. Then the body has to be in json format like the screens I posted earlier.

**Comment by RazvanTinca** [comment]
> I am using latest, check that you pasted correctly the bearer token on Authorization and then on your headers Content-Type and Accept with values of application/json. Then the body has to be in json format like the screens I posted earlier.

This is the request (with the token generated seconds before the request) (the token was trimmed for security reasons : ) )
![image](https://github.com/wekan/wekan/assets/17953262/16e54191-dda5-4bd7-ab92-a86e78ec5a3a)

![image](https://github.com/wekan/wekan/assets/17953262/a195e37e-220a-4223-a37c-7e1cc0d7c76d)
 In the logs says something about board access, but I'm the owner of the board...

**Comment by DimDz** [comment]
Try to login

POST {{URL}}/users/login

with body like this
{
    "username": "{{username}}",
    "password": "{{password}}"
}

**Comment by RazvanTinca** [comment]
> Try to login
> 
> POST {{URL}}/users/login
> 
> with body like this { "username": "{{username}}", "password": "{{password}}" } do you get a response?

Yes, the login is the only endpoint that works. the others don't anymore, since this morning when I restarted the app, I'll try to reinstall the instance, hopefully there won't be any major data losses and try again to see if it works.

**Comment by DimDz** [comment]
> > Try to login
> > POST {{URL}}/users/login
> > with body like this { "username": "{{username}}", "password": "{{password}}" } do you get a response?
> 
> Yes, the login is the only endpoint that works. the others don't anymore, since this morning when I restarted the app, I'll try to reinstall the instance, hopefully there won't be any major data losses and try again to see if it works.
> 
> (Edit) I've tried to reinstall the instance. it seems that the problem still persists, It must be something that I'm doing wrong, could you please export the "get boards" request from postman to a file/text and send it to me, maybe I'm missing something.

https://pastebin.com/7v1CkmXD , this is my Postman Collection. It has login, get boards, edit customfieldvalue.

**Comment by xet7** [comment]
@RazvanTinca 

Did you try api.py from https://github.com/wekan/wekan ?

**Comment by RazvanTinca** [comment]
> @RazvanTinca
> 
> Did you try api.py from https://github.com/wekan/wekan ?

No, I haven't tried it, I just check what it does, but I don't find anything for editing the custom field, I only can find the get info and adding a new custom field to the board.

I already have the custom field added to the board, I just need to add a value to it on a specific card.

**Comment by xet7** [comment]
@RazvanTinca 

Does any of these help?

- https://wekan.github.io/api/v6.89/#edit_custom_field
- https://github.com/wekan/wekan/blob/master/models/customFields.js#L393

**Comment by RazvanTinca** [comment]
> @RazvanTinca
> 
> Does any of these help?
> 
> * https://wekan.github.io/api/v6.89/#edit_custom_field
 This will edit a custom field, I need to edit the value of the custom field on a card, not the custom field it's self.

> * https://github.com/wekan/wekan/blob/master/models/customFields.js#L393
 This is also referred to the same thing, 
This one is the one that will give me the error: https://github.com/wekan/wekan/blob/master/models/cards.js#L3961

**Comment by xet7** [comment]
If that customFields.js does not have API for editing value, it should be added.

**Comment by xet7** [comment]
Similarly like there is API at that and other files at `wekan/models/*.js`

Here is how to make PR https://github.com/wekan/wekan/wiki/Emoji

**Comment by xet7** [comment]
@RazvanTinca 

Oh, that's so confusing. I will move it to customFields.js , so that API Docs will be more logical.

**Comment by RazvanTinca** [comment]
I've tried with the api.py, still doesn't work for me. Could you let me know if you had to enable something on a docker instance in order to work? Or did you have to allow anything, permission related for the user?

**Comment by xet7** [comment]
@RazvanTinca 

Did you add your WeKan URL, admin username and password to api.py ?

**Comment by RazvanTinca** [comment]
> @RazvanTinca
> 
> Did you add your WeKan URL, admin username and password to api.py ?

Yes, of course, I get the same 405 Error, which is "Method not found", The other function from api.py works just fine. only this one is the problem.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/master/api.py#LL68C1-L68C1

**Comment by xet7** [comment]
@RazvanTinca 

Are you using newest api.py ?

git clone https://github.com/wekan/wekan

cd wekan

python3 api.py

**Comment by RazvanTinca** [comment]
Yes, the one that was updated 2 days ago.

**Comment by xet7** [comment]
Hmm, I'll test.

**Comment by RazvanTinca** [comment]
If you want, I can give you access in private to my wekan instance and a test card

**Comment by xet7** [comment]
I tested with newest Docker version, and it works for me, when admin user is member of board, and there is Custom Field at card. 

```
python3 api.py editcustomfield BOARDID LISTID CARDID CUSTOMFIELDID NEWCUSTOMFIELDVALUE

python3 api.py editcustomfield afXZayrYEcdZr9CNY KZ9eHokGSp8uuBsys AqbJrGhKJhoNKgCQR 5rBxJCNEH3MJSdydj Testing
```

**Comment by xet7** [comment]
I did install newest Docker version this way:

```
git clone https://github.com/wekan/wekan

cd wekan

docker-compose up -d
```

Then I created first user that became admin, created board/list/card/customfield, then used api.py

**Comment by xet7** [comment]
Do you have some webserver at front of WeKan? What kind of config it has, is there any URL limitations?

**Comment by RazvanTinca** [comment]
Could you give me your email, I'll send you a link for the wekan among with an account, docker-compose.yml, and the apache2 configuration that I'm using

**Comment by xet7** [comment]
support@wekan.team

**Comment by RazvanTinca** [comment]
Did you receive my email?

**Comment by xet7** [comment]
Yes.

**Comment by xet7** [comment]
It looks like editing custom field works as Admin User, but not as Normal User. I will look why this happens.

**Comment by xet7** [comment]
When I tested locally, it looks like editing Custom Fields as Normal User works, also in Docker.

It looks like your Apache config does not have websockets etc configured:

https://github.com/wekan/wekan/wiki/Apache#a-main-url

**Comment by RazvanTinca** [comment]
I don't think the apache is the problem, as I've tried the endpoint directly to the ip:port and still get the same error. Did you manage to change the field through the API with the admin user? or directly from the interface?

**Comment by xet7** [comment]
@RazvanTinca 

I did manage to use API as both:
- Normal User
- Admin User

When using locally to my computer installed newest WeKan, built from source version, and newest Docker version.

I did not get it working on your WeKan using API. I do not know do you have newest WeKan.

**Comment by RazvanTinca** [comment]
You were right, I just went to the wekanteam/wekan on docker hub and found out that I was using another image, even though it was the latest version, I was using "quay.io/wekan/wekan:latest" which wasn't the right image. I updated it and now it works as expected, Thank you so much for your patience and help.

**Comment by xet7** [comment]
@RazvanTinca 

Thanks! I updated info about Docker image versions:

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L113-L126
