### ISSUE TITLE
import many users

### ISSUE THREAD

**Issue by hikoseuro** [wekan/wekan#493]
Hello! I have been introducing wekan at work and ran into a problem. I have a huge list of users to add to the system. Manual will be very slow, and the addition of directly in the database is a bad decision. Any idea how to do it?

**Comment by yjfdl123** [comment]
have u solve this problem?

**Comment by xet7** [comment]
Use REST API:
https://github.com/wekan/wekan/wiki/REST-API#example-of-all-steps-of-create-user
