### ISSUE TITLE
Feature Request: Windows one file setup.exe install wizard

### ISSUE THREAD

**Issue by TomaszSzt** [wekan/wekan#4932]
## Background

I am aiming at replacing Microsoft Planner with some more powerful and less expensive alternative. The wekan looks very promising so I decided to give it a try. Unfortunately my first attempt to use it is a bit confusing. 

### Installation related issues

I did follow: https://github.com/wekan/wekan/wiki/Offline

to perform the installation.  I did get wekan-6.90-amd64-windows.zip and after some struggling with logic loop at: "Check required compatible version of Node.js from https://wekan.github.io/" which linked back to the initial page I was finally able to figure out that node.js 14.21.3 is required and that other, more current versions won't work.

Ok, the program started. 

First what I could see was, that registering new user failed with cryptic "internal server error" in the web browser:
![image](https://github.com/wekan/wekan/assets/87855864/f69400e1-2c92-4d60-9964-770e41edf26d)

 the console however correctly pointed me to missing mail server configuration:
<pre>
Exception while invoking method 'ATCreateUserServer' Error: You have not provided a mail URL. You can provide it by using the environment variable MAIL_URL or your settings. You can read more about it here: https://docs.meteor.com/api/email.html.
    at packages/email/email.js:310:11
    at C:\wekan-server\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (C:\wekan-server\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:56:12)
    at Object.Email.send (packages/email/email.js:250:18)
    at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:734:9)
    at MethodInvocation.ATCreateUserServer (packages/useraccounts:core/lib/server_methods.js:119:16)
    at packages/check/match.js:118:15
    at packages\meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1389:31)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
    at packages\meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1389:31)
    at packages/ddp-server/livedata_server.js:791:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
</pre>
 I don't want mails, so I tried to not specify the email (not having any mail server at hand), but the form refused registration. Notice, this requirement was not specified in the installation guide.

Gladly user account was created before server reported the problem. Or I hope it was? Was it? I was able log in, so I think it was.

Next thing which surprised me was the console message:
"(...)[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. (...)"

Just for Your information. I have no problem with it.

#### Localization
What I noticed first is a total lack of translations. To anything. 

Like on below image:
![image](https://github.com/wekan/wekan/assets/87855864/4c0d003f-d5a5-4974-8c08-c27794dd1062)

I tried to change language, but nothing happen. The menu with language did open, but was totally irresponsible.

### Attachments uploading 
I did create a card, was able to upload some files. I was able to confirm that some folders were created in a location I specified in 

SET WRITABLE_PATH=....

in start-wekan.bat

but an attempt to click "download" produced absolutely no response except:
"Firefox can’t establish a connection to the server at localhost." blank page.

I was able to confirm that download link, which in this case was:
http://localhost/cdn/storage/attachments/646e29bbd4ea0fb92634731b/original/646e29bbd4ea0fb92634731b.bsh?download=true

was missing the server port specification. Due to technical reasons I did change the port from default 80 to free 8081 using:

SET PORT=8081

in start-wekan.bat

# Solution

To my great surprise the culprit was in the missleading information contained in start-wekan.bat:

I have found there the:

SET ROOT_URL=http://localhost
SET PORT=80

Notice, the ROOT_URL is __NOT__ specifying the port. The port IS however specified below directly. So I, following the notion did:

SET ROOT_URL=http://localhost
SET PORT=8081

After noticing the incorrect download link I pondered a bit, scratched by baldy head and tried to do:

SET ROOT_URL=http://localhost:8081
SET PORT=8081

And now everything works. Translations are present, language can be changed, files can be downloaded an uploaded. 

Obviously because the incomplete _http://localhost_ was used in queries sent to a server, which browser interpreted, according to standard as, _http://localhost:80_, while the server was observing the 8081 port.

# My kind requests:

1. Please update the installation guide at https://github.com/wekan/wekan/wiki/Offline
with correct link to the place where one can find a required versions of database and nodejs. 

I was able to figure out the version of node.js from within the "wekan-6.90-amd64-windows.zip/bundle/.node_version.txt" but the required version of database is still a mystery to me.

2. Please update the start-wekan.bat to contain __full url__ with port in SET ROOT_URL to avoid future confusions at users part.

**Comment by xet7** [comment]
@TomaszSzt

> Please update the installation guide at https://github.com/wekan/wekan/wiki/Offline
> with correct link to the place where one can find a required versions of database and nodejs.

Sorry. Some WeKan contributor that contributed new WeKan section renamed WeKan website https://wekan.github.io Download section to Install, so it is `Install WeKan ® Server`. I fixed it to step `a) 2` and `a) 3` of https://github.com/wekan/wekan/wiki/Offline

Currently at WeKan website Install section is this: Install WeKan ® Server v6.90, Meteor 2.12.0, Node.js 14.21.3, MongoDB 6.0.6

Those are required compatible versions of Node.js and MongoDB.

> Notice, the ROOT_URL is NOT specifying the port.

It is not required to specify port, when using port 80. Also, using localhost is only when there is one user. At step `a) 8` is example. So you should look what is your Windows computer IPv4 address, and have in `start-wekan.bat` this:
```
SET ROOT_URL=http://YOUR-IP-ADDRESS-HERE

SET PORT=80
```
For example:
```
SET ROOT_URL=http://192.168.0.100

SET PORT=80
```
To above, replace 192.168.0.100 with your Windows computer IP address.

When using IP address of WeKan Server at Windows, other computers at local network can login to wekan at http://YOUR-IP-ADDRESS/sign-in .

Sure it is possible to use different port, if you already have some other webserver at port 80.

More examples about ROOT_URL is at https://github.com/wekan/wekan/wiki/Settings

If sending email is not setup, error can be ignored, first registered user will be created anywa. First registered user will be admin. Next registered users will be normal users. It is possible to disable self-registration at Admin Panel, and add more users at Admin Panel / People / People. https://github.com/wekan/wekan/wiki/Adding-users

Here is list of various roles like admin, normal etc https://github.com/wekan/wekan/wiki/REST-API-Role

Yes, writing clear enough docs and install info is hard. There has been about 400 issues about ROOT_URL where something related has been tried to explain correctly. ROOT_URL and PORT settings are required to set correctly to WeKan to work properly, they are settings of Meteor web framework https://www.meteor.com , WeKan is made with Meteor.

**Comment by TomaszSzt** [comment]
Thanks. 

>(...)Yes, writing clear enough docs and install info is hard.(...)

Sure, I know it from experience. Yet the first contact with documentation makes a huge impact on IT personnel. Seeing nice, working step-by-step guide, seeing one complete bundle (sure, not optimal and not with all bells and whistles) with no deps and etc. makes us to think: "This will be piece of cake to maintain, I can recommend it to my boss". Seeing even one dependency You need to figure out Yourself, seeing not working manual, seeing that only user guide is a forum is a clear message: "If I will get into it I will be deep in ** with maintenance work".

I had such an unpleasant experience personally with GitLab (a real "cookbook" how to install it an maintain) and a very pleasant 30-minut walk with setting up two instances of GitBlit on the same machine. Guess which one I have chosen to maintain?

Of course, possibly, if I would get the "doker" and "VM" path it would be made much easier. Maybe it is time for me to learn new things and stop being worried about performance and resources?

Thanks again for quick response.

**Comment by xet7** [comment]
@TomaszSzt 

> Seeing nice, working step-by-step guide, seeing one complete bundle (sure, not optimal and not with all bells and whistles) with no deps and etc. makes us to think: "This will be piece of cake to maintain, I can recommend it to my boss"

Ok, I think this is about Windows one file setup.exe install wizard. I'll think about it.
