### ISSUE TITLE
create and restore backups

### ISSUE THREAD

**Issue by divramod** [wekan/wekan#494]
is this possible until now or a new feature request?

**Comment by mzemb** [comment]
I may be wrong (wekan newbie here), but does the export board fill your need ?

**Comment by gonter** [comment]
An export is certainly useful but not a complete backup/restore solution.  Since wekan lives (almost) entirely within a MongoDB, this is the level where the backup must take place, IMHO.

**Comment by mzemb** [comment]
Sounds logical.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
