### ISSUE TITLE
How Badges work?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4944]
@helioguardabaxo

You added feauture Badges show minicard https://github.com/wekan/wekan/pull/4940

To this issue, please add comment with English screenshot attachments about how this feature works, what to do step by step to add Badges etc, what settings there and where. This way I would not need to figure out from source code how it works.

If this feature is related to some feature in Trello, if there are Trello Badges, please add screenshot attachments about what this looks like in Trello.

I need those, because I am explaining to translators, what is a Badge, and how to use it, so that they can translate it correctly. Similarly like I added explanation what is a Cover https://github.com/wekan/wekan/wiki/Cover .

Thanks a lot !

**Comment by xet7** [comment]
@helioguardabaxo

For that Cover https://github.com/wekan/wekan/wiki/Cover , I did draw arrows this way:

1. I did take screenshot of WeKan feature
2. In Gimp, I did crop screenshot
3. In LibreOffice Writer top menu: View / Toolbars / Drawing
4. At bottom drawing tools, I did select arrow type and arrow color, and draw arrow.
5. I did take screenshots of what is visible at LibreOffice.
6. I did use Gimp to crop images.

You can similarly add arrow to your screenshots.

**Comment by mfilser** [comment]
Another, maybe easier tool, is Flameshot to screenshot, cut and add arrows.
https://flameshot.org/

**Comment by helioguardabaxo** [comment]
@xet7 and @mfilser !

I create this feature to show/hide some badges that are showed in bottom of minicard.
See below how it works:
![Peek 01-06-2023 15-44](https://github.com/wekan/wekan/assets/24301085/137f6b35-f027-49b6-9b0a-a06931207203)

**Comment by xet7** [comment]
@helioguardabaxo 

Please add separate step by step screenshot images with arrows as attachment to this issue. I get lost when looking at that video where it is not possible to pause.

**Comment by xet7** [comment]
@helioguardabaxo

And with plain text or markdown description like here https://github.com/wekan/wekan/wiki/Cover

**Comment by helioguardabaxo** [comment]
#Minicard Show/Hide Cover Image
- Click on ☰ to open sidebar
- Click on "Board Settings" menu
- Click on "Minicard Settings" menu
- Check "Cover Attachment on minicard" to show or uncheck to hide

![Screenshot 2023-06-01 at 17-05-25 Quadro de teste 1 -](https://github.com/wekan/wekan/assets/24301085/bbe769e4-c419-4c32-8f09-c6c61dfc66bb)

![Screenshot 2023-06-01 at 17-05-46 Quadro de teste 1 -](https://github.com/wekan/wekan/assets/24301085/0165c803-18d0-45ba-a73e-a958d95daede)

![Screenshot 2023-06-01 at 17-05-46 Quadro de teste 1 -](https://github.com/wekan/wekan/assets/24301085/0482a34c-ca97-4e27-8192-17f90634fd5a)

![Screenshot 2023-06-01 at 17-04-55 Quadro de teste 1 -](https://github.com/wekan/wekan/assets/24301085/f23feda9-e446-4de7-b8ac-0d00cda46902)


#Minicard Show/Hide badges
- Click on ☰ to open sidebar
- Click on "Board Settings" menu
- Click on "Minicard Settings" menu
- Check "Badge Attachment on minicard" to show or uncheck to hide
- Check "Card Sorting By Number" to show or uncheck to hide
