### ISSUE TITLE
How to install Wekan in my Localhost

### ISSUE THREAD

**Issue by isdzulqor** [wekan/wekan#495]
Hello guys, I am newbie in node js and meteor js.. 
I have a problem when understanding this wekan structure folder. I see that it's not like the Meteor structure folder. My question is what kind of structure folder of this app? And how could I install it in my localhost and re-structuring to be meteor structure folder??
thank you before.. I am sorry I still lay in this case..

**Comment by mquandalle** [comment]
This kind of question are better suited for the [forum](https://discuss.wekan.io).

Meteor doesn’t really enforces a folder structure. The installation is documented in the [wiki](https://github.com/wekan/wekan/wiki/Install-and-Update).

**Comment by xet7** [comment]
Installation instructions at wiki:
https://github.com/wekan/wekan/wiki
