### ISSUE TITLE
Android: Can't click on a board or a task in lightweight privacy browsers taken from F-Droid store

### ISSUE THREAD

**Issue by dob777** [wekan/wekan#4966]
### Server Setup Information

* Did you test in newest Wekan?: my wekan source version is 6.89
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes it's alright
* Operating System: Debian 11 bullseye arm64 @ Orange Pi
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): source builded and running on node.js
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx requests redirection to node.js
* Node.js Version: v14.21.3
* MongoDB Version: "version": "5.0.6"
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?: tried a lot of different and this question is why I am writing this issue

### Problem description

Wekan frontend is not working good in lightweight-privacy-browsers (non-firefox/non-chromium based) available in F-Droid store. I tried default LineageOS browser, Privacy Browser, Lightning and some others so I can't open a board using mentioned browsers. See the screenshot:
<img src="https://github.com/wekan/wekan/assets/121567421/aed4cd5c-b145-49d2-b92f-b31af71768dd" width="300" />
Clicking on a board has no effect as well as clicking on a task the same has no effect but other buttons work well.

I tried firefox based browsers and chrome and it's all okay. The issue persists only at lightweight-privacy-browsers.

#### Reproduction Steps
Install of the following browsers and try to open a board from your phone: 
Privacy Browser: https://f-droid.org/en/packages/com.stoutner.privacybrowser.standard/
Lightning: https://f-droid.org/packages/acr.browser.lightning/

#### Logs

I can't find console in those browsers they have quite limited functionality.

**Comment by xet7** [comment]
@dob777

> Wekan frontend is not working good in lightweight-privacy-browsers (non-firefox/non-chromium based) available in F-Droid store.

Both Privacy Browser and Lightning uses Android Webview, that is based on Chromium. I presume LineageOS browser also uses Chromium.

- https://developer.chrome.com/docs/multidevice/webview/
- https://github.com/anthonycr/Lightning-Browser/issues/845
- https://f-droid.org/packages/acr.browser.lightning/
- https://f-droid.org/en/packages/com.stoutner.privacybrowser.standard/
- https://gitweb.stoutner.com/?p=PrivacyBrowserAndroid.git;a=summary

**Comment by dob777** [comment]
Thank you for your answer.

I installed Wekan v6.97 and that fixed my issue. Now I can click boards and tasks in every possible browser.

Speaking about correct ROOT_URL I'd like to say that it is still alright. I have localization labels working well on all browsers I tried (like 6 browsers) but labels are not appearing correctly only in Lightning browser (where my previous screenshot comes from).

**Comment by xet7** [comment]
@dob777 

Have you installed all updates from Play Store? Webview updates are installed from Play Store.

At Lightning General Settings, do you have these enabled?
```
[X] Enable Javascript
[X] Enable color mode
```

I do have WeKan translations visible correctly at Lightning, using Android 11.

It could be that translations do not appear immediately, running Javascript takes some time on slower Android devices. After some time translations should appear.

**Comment by dob777** [comment]
<img src="https://github.com/wekan/wekan/assets/121567421/d474e873-7bc1-4a94-9058-297385728cf2" width="300" />

I have JavaScript enabled. My LOS is based on Android 12.
I noticed that labels appear correctly after I click on a board then go back and forth and it's all okay.
