### ISSUE TITLE
Language preference is not persisted

### ISSUE THREAD

**Issue by simon816** [wekan/wekan#4967]
### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Ubuntu 22.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node.js Version: 14.20.0
* MongoDB Version: 6.0.1
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox

### Problem description

When I select a language under the "Change Language" dropdown, the UI correctly changes language, but the preference does not persist when refreshing the page, defaulting back to the browser's language. My expectation is that it is persisted across refreshes.

#### Reproduction Steps

* User menu
  * Change Language
    * Select a language that's not the browser language
* Refresh
* Observe language is back to browser language

Cause: By setting a breakpoint, I found that `Meteor.user()` is `undefined` within the `Meteor.startup()` callback: https://github.com/wekan/wekan/blob/8f43b74bbca78fa03162985fc7b2192782549c1f/client/lib/i18n.js#L8

See also: https://stackoverflow.com/questions/36695551/meteor-check-if-the-user-is-logged-on-startup

**Comment by xet7** [comment]
@simon816 

It looks like changing language is trying to save it:

https://github.com/wekan/wekan/blob/master/client/components/users/userHeader.js#L279

Can you try adding that LoggingIn and try to fix it and send PR?

Info how to build WeKan is at https://github.com/wekan/wekan/wiki/Emoji

**Comment by xet7** [comment]
When debugging, you could see variables at browser inspect console by adding to some client .js file:

```
console.log(variablename);
```

**Comment by simon816** [comment]
Thanks for the tips. I've submitted a PR. 

Can I suggest you update step 6 on the wiki page to include `export WRITABLE_PATH=..`? I needed that in order for it to launch

**Comment by xet7** [comment]
@simon816 

Thanks! I updated wiki page.
