### ISSUE TITLE
onHover background in filter cards view is off-center

### ISSUE THREAD

**Issue by glumb** [wekan/wekan#497]
The background is not vertical centered.
<img width="234" alt="bildschirmfoto 2016-01-20 um 17 14 34" src="https://cloud.githubusercontent.com/assets/3062564/12454854/8a9f6bde-bf99-11e5-9672-09610ee7d2c0.png">
removing `margin-bottom: 5px;` from `.card-label` fixes that. But I don't know if this class is used elsewhere.
<img width="227" alt="bildschirmfoto 2016-01-20 um 17 18 15" src="https://cloud.githubusercontent.com/assets/3062564/12454927/d30d52dc-bf99-11e5-90ec-d7faf8d92661.png">

**Comment by VidVidex** [comment]
This doesn't seem to be in issue anymore (running 7.0.5)

![image](https://github.com/wekan/wekan/assets/18378617/3fce4298-f10f-4d39-9e17-63eb1a75cde0)
