### ISSUE TITLE
Wrong URL when accessing cards

### ISSUE THREAD

**Issue by k4r7u** [wekan/wekan#498]
Hi,
I am running Wekan in a subpath with the following export statements:
```
export ROOT_URL='https://myurl.com/wekan'
export PORT=3001
```

Apache2 is working as the proxy:
```
ProxyPass /wekan http://127.0.0.1:3001/wekan
ProxyPassReverse /wekan http://127.0.0.1:3001/wekan
```

I can access Wekan via https://mydomain.com/wekan and add boards, lists and cards without any problem. Clicking on a card however produces a wrong URL with the subpath 2 times in it and shows a "Page not found" error in Wekan.

https://myurl.com/wekan/wekan/b/49pMcJL8kvm9CLZsK/test/6JYtSNi26ugkT6XNe

Removing one "wekan" from the URL and changing it manually to:
https://myurl.com/wekan/b/49pMcJL8kvm9CLZsK/test/6JYtSNi26ugkT6XNe
opens the correct page.

**Comment by Vivi-IX** [comment]
I can confirm the problem. Happened after I updated to the last version on master branch.
No problems before the update.

**Comment by mquandalle** [comment]
This will be fixed by https://github.com/kadirahq/flow-router/pull/510

**Comment by kurtteichman** [comment]
I'm having a new issue now under the same conditions.

Wekan card links are have an extra '/' so the routing is going to a 404

example:
https://myurl.com/wekan//b/49pMcJL8kvm9CLZsK/test/6JYtSNi26ugkT6XNe

there is no route to handle the //b

**Comment by AlexanderS** [comment]
@kurtteichman This is #624
