### ISSUE TITLE
Bug CSS: max-width in minicard-custom-field-item

### ISSUE THREAD

**Issue by koluka** [wekan/wekan#4988]
Hi!
When adding an custom field to the card, it is incorrectly displayed on the card in desktop mode. 
![CustomFieldWidth](https://github.com/wekan/wekan/assets/47507278/c8f41bc8-b62d-4caf-830e-2d6721cc949e)
![CustomFieldWidth2](https://github.com/wekan/wekan/assets/47507278/782557c0-ecc9-42d5-8f3f-f582dda95f59)

It seems to me there should be 100% and not 100px.
![CustomFieldWidth3](https://github.com/wekan/wekan/assets/47507278/6f2f05a2-19b5-4ebd-9082-a62d73e1fccb)

If this is not an error, pls tell me how I can fix this parameter in my version (ubuntu 22.04, snap) 
Thanks!

**Comment by koluka** [comment]
![CustomFieldWidth4](https://github.com/wekan/wekan/assets/47507278/8ff577d0-4a16-4ac4-abee-b1b72e6ab32e)

**Comment by xet7** [comment]
@koluka 

I fixed this. I try to release new Snap Stable sometime this week, before midnight Sunday Finland time, if possible.

**Comment by koluka** [comment]
Thanks! I'm not in a hurry... =)

**Comment by xet7** [comment]
@koluka 

> Thanks! I'm not in a hurry... =)

Thanks!

But one of my customers is in a hurry for getting new Snap Stable version, so I try to make it happen, if possible. Releasing new Snap Stable requires making some more fixes so that upgrades would work properly.
