### ISSUE TITLE
requests to join board

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#499]
users who arent logged in can see boards they are given a link to. it'd be a cool feature if they could send a request to join the board

**Comment by SimonSarazin** [comment]
We started to use wekan for the nuitdebout mouvement (tableau.nuitdebout.fr & https://wiki.nuitdebout.fr/index.php?title=Tableaux) and it's a really must have feature.  Maybe also to be able to open totally the board to anyone to edit (really usefull when we just start a board).

**Comment by xet7** [comment]
Moved to #/802
