### ISSUE TITLE
maximum call stack size exceeded - on sign-in page - website stop working 

### ISSUE THREAD

**Issue by Dexus** [wekan/wekan#4994]
### Server Setup Information

* Did you test in newest Wekan?: v6.98
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: openshift cloud
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): n/a
* Node.js Version: same as in dockerfile
* MongoDB Version: 4.4.1-3 - external managed
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Current microsoft edge

### Problem description

Once i open the website, it now prints me an error "maximum call stack size exceeded" in the dev console.

#### Reproduction Steps

First I have to say, it was working last week...
Today, it was printing errors.

Open webpage like always, webpage get refresh and removed the login field, only the single side sign-on is available.

Oauth2 was working before bun now it opens short a popup and closes again but nothing else happens, the websocket showing receiving data from the oauth2, but website does nothing... no redirect no additional errors nothing.

#### Logs

```js

i18next: languageChanged en
i18next: initialized {
  debug: 'true',
  initImmediate: true,
  ns: [ 'translation' ],
  defaultNS: 'translation',
  fallbackLng: [ 'en' ],
  fallbackNS: false,
  supportedLngs: [
    'ar-DZ',  'ar-EG', 'ar',    'ary',   'az-AZ',   'az-LA',
    'az',     'bg',    'br',    'ca',    'ca-ES',   'cnm',
    'cs',     'cs-CZ', 'cy-GB', 'cy',    'da',      'de-AT',
    'de-CH',  'de',    'el-GR', 'el',    'en-BR',   'en-DE',
    'en-GB',  'en-IT', 'en-MY', 'en-YS', 'en',      'eo',
    'ast-ES', 'es-AR', 'es-CL', 'es-CO', 'es-LA',   'es-MX',
    'es-PE',  'es-PY', 'es',    'et-EE', 'eu',      'fa-IR',
    'fa',     'fi',    'fr-BE', 'fr-CA', 'fr-CH',   'fr',
    'fy-NL',  'fy',    'gl-ES', 'gl',    'gu-IN',   'he-IL',
    'he',     'hi-IN', 'hi',    'hr',    'hu',      'hy',
    'id',     'ig',    'it',    'ja',    'ja-Hira', 'ja-JP',
    'ka',     'km',    'ko-KR', 'ko',    'lt',      'lv',
    'mk',     'mn',    'ms',    'ms-MY', 'nb',      'nl-NL',
    'nl',     'oc',    'pa',    'pl-PL', 'pl',      'pt-BR',
    'pt',     'pt-PT', 'ro',    'ro-RO', 'ru-UA',   'ru',
    'sk',     'sl',    'sr',    'sv',    'sw',      'ta',
    'th',     'tlh',   'tr',    'ua-UA',
    ... 32 more items
  ],
  nonExplicitSupportedLngs: false,
  load: 'all',
  preload: false,
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  partialBundledLanguages: false,
  saveMissing: false,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: [ 'sprintf' ],
  postProcessPassResolved: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: false,
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation: {
    escapeValue: false,
    format: [Function: bound format],
    prefix: '__',
    suffix: '__',
    formatSeparator: ',',
    unescapePrefix: '-',
    nestingPrefix: '$t(',
    nestingSuffix: ')',
    nestingOptionsSeparator: ',',
    maxReplaces: 1000,
    skipOnVariables: true
  },
  cleanCode: true,
  defaultNs: 'translation',
  resources: {},
  ignoreJSONStructure: true,
  lng: 'en'
}
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Thu Jul 06 2023 13:58:50 GMT+0000 (Coordinated Universal Time)","time":{"$date":1688651931256},"level":"info"}
```

**Comment by xet7** [comment]
Reloading WeKan webpage in browser usually makes possible continue.

Alternatively, reboot WeKan server.

**Comment by Dexus** [comment]
Hi @xet7 I have already tried both options. But it looks like it will not help here.

As soon as the refresh "maximum call stack size exceeded" prints 3 times(grouped each by 3 repeats). 
After restart it prints one time "maximum call stack size exceeded" another refresh it showing same as before 3 times, 3 repeats each.
