### ISSUE TITLE
When you drag a card on to a list.. it doesn't work.

### ISSUE THREAD

**Issue by TylerL-uxai** [wekan/wekan#500]
Drop a card on the title of a list instead of in the box below it. It doesn't work.

**Comment by nata-g** [comment]
AFAIK it is not designed that way. It is designed to drop in to the list. Besides why do you want to drop it in the title. Title is like the header to the list

**Comment by TylerL-uxai** [comment]
nata-g I specialize in human error. Trust me, the first mistake I made was dragging and dropping it on to the title. It makes sense that way to some people based on actual evidence of my user test.

**Comment by mquandalle** [comment]
Yes, adding that interaction would makes sense.

**Comment by xet7** [comment]
Moved to #766
