### ISSUE TITLE
Background image is not set via card 

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#5003]
Server Setup Information
* Did you test in newest Wekan? Version 6.99.5
* Deployment Method: Snap
* Node.js Version: 14.21.3
* MongoDB Version: 6.0.7
* What webbrowser version are you using: Chrome Version 114.0.5735.199 (newest)

### Problem description
![WeKan_Hintergrundbild_gehtnicht](https://github.com/wekan/wekan/assets/92315677/29d5efc5-3d1f-49f2-a8b1-d801eedba235)
Using the setting option on the card with the background image as attachment -> background doesn't change.
#### Reproduction Steps
Load an image to a card as an attachement. Go to options of attachment. Choose as background image. 

Logs show nothing happens when I click use as background image

**Comment by xet7** [comment]
@VidVidex 

Is this related to something being hidden or not, or z-index ? Do you know how to add PR to make background image and card cover visible?

**Comment by VidVidex** [comment]
It seems like I renamed a class so the url was undefined. Fixed in PR #5004
