### ISSUE TITLE
(enhancement idea) Provide a way to print from Wekan

### ISSUE THREAD

**Issue by boinst** [wekan/wekan#501]
I use Wekan in Sandstorm. I note that there is no real way to print a Wekan board or list, or to export to another format that I might be able to print from.

**Comment by GarenKreiz** [comment]
Printing support would be great, possibly with an option to define the level of information to be printed : card title with labels and member icons (as on screen), idem with description, idem with description and comments. 

A implementation could be based on the json export to generate a well-tagged html that could be associated with differents CSS files to hide/display different types of info or to impact the layout (e.g. lists in columns or rows).

I'm no Javascript/Meteor programmer yet, so I'm not currently able to help, sorry.

**Comment by xet7** [comment]
Moved to #1173
