### ISSUE TITLE
Excessive Client Side RAM usage + Tab Freeze

### ISSUE THREAD

**Issue by jqlifice** [wekan/wekan#5010]
### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Server Ubuntu 22.04.2; Client Windows 10
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none
* Node.js Version: idk, command cant be found (node --version)
* MongoDB Version: idk, command cant be found (mongod --version)
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox 115

### Problem description

Can't add a Video due to sensitive information in the board.
I have a card that is child/subtask of another card, which again is child/subtask of another card. Opening any of these cards causes the browser tab to use up all available RAM and freezes the browser tab. One card contains a docx file as attachment, all others just contain text.
#### Reproduction Steps
I created the cards and later linked them by selecting them as subtasks, now I cant open any of them and the above freeze happens when I tried to open them.

#### Logs

No Log events are thrown in the console. It just eats up RAM, then eventually freezes.

The Log only shows LDAP-Sync related events on the server
When requesting the page/card there are no additional events thrown.

**Comment by jqlifice** [comment]
I am not certain, but I might have accidentially made 2 of the cards recursive subtasks of each other, at least it looks like it. That might be the reason

**Comment by xet7** [comment]
What WeKan version? You see it this way:

```
sudo snap list
```

**Comment by jqlifice** [comment]
@xet7 6.09, snap refresh did not install a newer version, thats why I put "newest? yes"
