### ISSUE TITLE
No text editor anymore after upgrade 6.98 → 6.99.8

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#5012]
## Issue
No text editor anymore after upgrade 6.98 → 6.99.8

### Server Setup Information

* Did you test in newest Wekan?:	6.99.8
* Operating System: Linux 3.10.0-1160.88.1.el7.x86_64
* Deployment Method: bundle
* Http frontend: Nginx
* Node.js Version: 14.x
* MongoDB Version: 5.0.18
* What webbrowser version are you using? macOS Chromium 114.0.5735.198 (Official Build, ungoogled-chromium) (x86_64). Same happens in (EOL) macOs Safari Version 14.1.2 (14611.3.10.1.7). System is macOS 10.14.6.

### Problem description
Card comment and description fields have no editor anymore, rendering it impossible to set text attributes. Unrelated to a specific theme, as far as I could test it.
![WeKan editor](https://github.com/wekan/wekan/assets/39904614/0181512d-ab8c-4053-b6d7-f2553dc538f9)

**Comment by xet7** [comment]
@BabyFnord 

Having editor back depends, is there any better editor that is not vulnerable.

**Comment by xet7** [comment]
@BabyFnord 

One alternative is, that I will add code, that converts that existing editor HTML to markdown, so that it will be visible again.

**Comment by BabyFnord** [comment]
Having Markdown available would do for the moment (while there isn“t a full editor available), at least for the most basic text formatting.

**Comment by xet7** [comment]
@BabyFnord 

It depends what editor I get working well enough. I have tried some, they did not work yet.
