### ISSUE TITLE
Metrics are broken with lastConnectionDate missing

### ISSUE THREAD

**Issue by magicbelette** [wekan/wekan#5013]
### Server Setup Information
Wekan 6.97

### Problem description
Since the following function has been removed "lastConnectionDate" isn't updated at users' login:
https://github.com/wekan/wekan/blob/61223503e35e93edbc701f36305713d5c997cc10/server/publications/users.js#L118

As metrics use this field, metrics are partially broken.

Cheers

**Comment by xet7** [comment]
@Emile840 

Can you fix this Metrics feature you added?
