### ISSUE TITLE
Can't delete images from cards

### ISSUE THREAD

**Issue by vitorcruzfaculdade** [wekan/wekan#5016]
Hello everyone, hope you guys doing fine;

Since last update I can't remove images (image.png) Attached to cards. It shows only options to add new images, and put it in mini card cover.

Also, I always run docker-compose with RICHTER_CARD_COMMENT_EDITOR=true, but it's not showing rich format options anymore in any new or old card.

Aside this, everything else is working just fine.

My versions are:
Wekan: 6.99.9
Meteor 2.12
Node 14.21.3
MongoDB 6.0.6

Using docker (deployed from docker-compose.yml)

Docker version 24.0.4, build 3713ee1
O.S. Ubuntu Server 20.04.6 LTS (latest patches)

Browsers: Google Chrome 115.0.5790.99 / Mozilla Firefox 115.0.2

![image](https://github.com/wekan/wekan/assets/91508411/1ba0ebcc-da07-4e55-8b59-9933d8284d25)

**Comment by xet7** [comment]
Related #5012

**Comment by xet7** [comment]
@VidVidex 

Can you check can attached images be deleted in newest WeKan? If they can not be deleted, can you fix it?

**Comment by xet7** [comment]
@vitorcruzfaculdade 

> Hi @xet7 , sorry to bother, but what about the option to remove attached image ? Is this affected by the issue with richeditor as well?

No, richeditor is different issue #5012 . Richeditor edits text and images inside Card Description and Card Comments. Not attachments at attachments part of card.

**Comment by mfilser** [comment]
This change came at commit: 7ef3bba9f7d3d9474bf7074f8ebb3ad7315d1dd5 by @VidVidex in PR #4993
I think this wasn't the intention.

I will send a PR to get back the old behavior
