### ISSUE TITLE
No Assignee avatar on minicards with v7.00

### ISSUE THREAD

**Issue by kovacs-andras** [wekan/wekan#5017]
## Issue
Avatar of the Assignee is not visible on the minicards with v7.00.
Avatar of the Members is still visible and works as expected.

I downgraded back to v6.99.9 and both works again where I can turn on-off the avatars of the Assignees with:
Boards Settings / Card Settings / √ Assignee

### Server Setup Information
* Did you test in newest Wekan?: v7.00
* Deployment Method: Docker
* Http frontend: traefik
* What webbrowser version are you using: Firefox 102.13.0

#### Logs
No error has been logged.

If this change was intentional, just ignore my issue. Thank you!

**Comment by mfilser** [comment]
I will have a look at this

**Comment by xet7** [comment]
I got message from @mfilser that he has fixed this, and will send PR in near future.
