### ISSUE TITLE
Feature Request : Archive a card directly from the burger menu of the card

### ISSUE THREAD

**Issue by garciadavy** [wekan/wekan#5024]
Add a button to archive a card directly from the burger menu of the card :

![image](https://github.com/wekan/wekan/assets/82655441/ff5956c2-c2f6-4433-8e4c-892b2d90b3a5)

**Comment by DimDz** [comment]
With the admin role you can already archive it from the burger menu.

**Comment by xet7** [comment]
@garciadavy 

What version of WeKan you have? In WeKan v7.01, it looks like that also normal user can archive card:

https://github.com/wekan/wekan/blob/master/client/components/cards/minicard.jade#L191-L201
