### ISSUE TITLE
oidc: dangling "OR" text in login screen when only oidc is enabled

### ISSUE THREAD

**Issue by gramakri** [wekan/wekan#5028]
## Issue
There is a dangling "OR" when only OIDC login method is enabled in Wekan.

### Server Setup Information
* Wekan on Cloudron

### Problem description

Best described with a screenshot. There is an *OR* and also "Must be logged in". It's not clear what this means.

![image](https://github.com/wekan/wekan/assets/82041/6221d4f3-e701-4a6c-8b47-8dca7a8cbc38)

**Comment by xet7** [comment]
Related https://github.com/wekan/wekan/issues/5029#issuecomment-1652449147
