### ISSUE TITLE
Feature Request: Resizable comments area

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#5033]
## Issue
The comments area in v7.01.0 is so small. Writing longer comments becomes tedious, as you need to scroll often to see what has already been said.

### Server Setup Information
Did you test in newest Wekan?: 7.01.0
Operating System: Linux 3.10.0-1160.88.1.el7.x86_64
Deployment Method: bundle
Http frontend: Nginx
Node.js Version: 14.x
MongoDB Version: 5.0.18
What webbrowser version are you using? macOS Chromium 115.0.5790.98 (Official Build, ungoogled-chromium) (x86_64). Same as in (EOL) macOS Safari Version 14.1.2 (14611.3.10.1.7). System is macOS 10.14.6.

### Problem description
The comments area in v7.01.0 needs to be resizable, to ease writing longer comments:
![comments](https://github.com/wekan/wekan/assets/39904614/6e8c5290-2093-409f-ada0-daf1d764cb01)

The previous summernote based editor field could be made to fit needs, at least resizing would be handy. 
Thank you for considering this.

**Comment by VidVidex** [comment]
I cannot replicate this in 7.03. Both firefox and Chrome seem fine.

![image](https://github.com/wekan/wekan/assets/18378617/5b77d8b5-8409-4288-a912-e403ccbb0a17)

**Comment by BabyFnord** [comment]
Please note, this is being reported of v7.01.0, not 7.03. IF this behaviour changed over the course to 7.03, it seems to be left out of the announcements.

**Comment by VidVidex** [comment]
@xet7 can we close this if doesn't seem to be an issue in the latest versions?

**Comment by xet7** [comment]
@VidVidex 

Actually this issue is just about WYSIWYG editor, or some way to view that content.

Moved to #5012

**Comment by BabyFnord** [comment]
@xet7  @VidVidex I'm sorry to report that in v7.05, the comment field remains fixed at two lines. It does not extend automagically as it should, according to your screenshot 🤷🏻‍♂️.

**Comment by xet7** [comment]
@BabyFnord 

Yes, because WYSIWYG editor is not yet added back #5012 . After that is added, there are not those two lines, there will be WYSIWYG editor.

If you like to switch to markdown editor, change WYSIWYG editor to false:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L272

Or with Snap:
```
sudo snap set wekan richer-card-comment-editor='false'
```

**Comment by BabyFnord** [comment]
> Yes, because WYSIWYG editor is not yet added back #5012 . After that is added, there are not those two lines, there will be WYSIWYG editor.
> 
> If you like to switch to markdown editor, change WYSIWYG editor to false

🙏 for Markdown, that's fine for the time being. Just for the record, mine is a bundle install, but it's the same setting in the startup script 🙂.
