### ISSUE TITLE
v7.01.0 fresh install in listview first column small

### ISSUE THREAD

**Issue by intellekta** [wekan/wekan#5034]
in a fresh install and new board in Listview the first column is more smaller than all following columns.
tested with chrome and vivaldi.
![image](https://github.com/wekan/wekan/assets/14091136/85fc9ae8-4076-491a-b1ba-aca7f6571b1a)

**Comment by xet7** [comment]
@intellekta 

Did you install with Docker, Snap Candidate or Bundle?

**Comment by intellekta** [comment]
I install it on yunohost 11.2.3 (stable)
Version Wekan 7.01~ynh1

**Comment by xet7** [comment]
@intellekta 

Please take screenshot of what happend if you click that grey + button below text First at your image.

It looks like yonohost related files are at https://github.com/YunoHost-Apps/wekan_ynh

**Comment by intellekta** [comment]
![image](https://github.com/wekan/wekan/assets/14091136/f7577fa4-a333-460e-b172-e407336d7a8c)
after click on +
![image](https://github.com/wekan/wekan/assets/14091136/40e934aa-0b6a-4b92-8f14-e848d45a628a)
in swimlanes view its allways okay
![image](https://github.com/wekan/wekan/assets/14091136/e7aaffd7-5d46-41e6-a6c0-6e1b57513a80)

**Comment by xet7** [comment]
Oh, it's in Lists view, not Swimlanes view! Ok!
