### ISSUE TITLE
Wrong return data in API

### ISSUE THREAD

**Issue by Pandetthe** [wekan/wekan#5038]
Hi! I found that return data in API request GET /api/boards/{board}/cards_count is wrong. Instead of getting only board_cards_count, I got whole array of card objects containing:
_id, title, boardId, listId, description, userId, swimlaneId, sort, cardNumber, customFields, members, assignees, archieved, parentId, coverId, createdAt, modifiedAt, dateLastActivity, requestedBy, assignedBy, labelIds, spentTime, isOvetTime, etc.

**Comment by xet7** [comment]
@Pandetthe 

Thanks! API code is at wekan/models/

Please send PR to fix it like this https://github.com/wekan/wekan/wiki/Emoji

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5040 . Thanks to @Pandetthe !
