### ISSUE TITLE
Invalid api documentation

### ISSUE THREAD

**Issue by Pandetthe** [wekan/wekan#5039]
Description of parameter "assignees" for POST /api/boards/{board}/lists/{list}/cards says that "the array of maximum one ID of assignee of the new card". I think "maximum one ID" is invalid because it is possible to create card with multiple assignees.

**Comment by xet7** [comment]
@Pandetthe 

Thanks! API docs code is at wekan/models/

Please send PR to fix it like this https://github.com/wekan/wekan/wiki/Emoji
