### ISSUE TITLE
Preview of attachments is broken in Safari 

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#5042]
## Issue
The preview of attachments is broken in MacOS safari. When clicking on an attachment to make it bigger, only the size of the card is used and not the full browser screen. Also the image is cut off, so I can't see the full image in preview. 
When using Google Chrome, it works as expected.. 

### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System: Debian 11
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 14.21.3
* MongoDB Version: 6.08
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Safari (16.6)

### Problem description
Preview of screenshot is not shown in full browser width and cut off in the middle: 
<img width="660" alt="Bildschirmfoto 2023-08-01 um 13 32 32" src="https://github.com/wekan/wekan/assets/1153741/b59a132f-68f5-44f8-a452-3b1bb3884ab1">

#### Reproduction Steps
Open image in preview in Wekan with Safari, MacOS.

**Comment by xet7** [comment]
@saschafoerster 

What version of WeKan are you running? You see it at Admin Panel / Version.

**Comment by xet7** [comment]
@saschafoerster 

Hmm, it looks like this happens on newest WeKan and Safari. I'll look at it.

**Comment by saschafoerster** [comment]
@xet7 Thank you very much. We are using the newest version 7.01.0

**Comment by xet7** [comment]
@VidVidex

Do you know how to fix this? Can you send PR ?

**Comment by VidVidex** [comment]
I suspect the problem is some css that behaves differently in safari. Sadly I do not have a mac to try and test what exactly is broken.

If someone has a mac and some time, the problematic css is probably here: https://github.com/wekan/wekan/blob/master/client/components/cards/attachments.css

**Comment by xet7** [comment]
@VidVidex 

Thanks! I have a Mac, but I did not yet find how to fix it.

Also if someone else has Mac, help is very welcome.
