### ISSUE TITLE
The authentication method on the login page has disappeared

### ISSUE THREAD

**Issue by yuyuan0507** [wekan/wekan#5051]
### Server Setup Information

* Did you test in newest Wekan?: Yes, 7.03.0
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?: Yes
* Operating System: Ubuntu
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.8
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? MS Edge & Google Chrome

### Problem description

There are two issues:
1.The authentication method on the login page has disappeared.
2.Currently, it is not possible to log in using LDAP accounts.
Regarding the first issue, please refer to the video explanation below: 

![LDAPdisappear](https://github.com/wekan/wekan/assets/18033527/b94a7784-434b-407c-9462-b4b3f4e27eb5)

**Comment by xet7** [comment]
@nebulade 

Can you look at this and send PR to fix it?

**Comment by ManZosh** [comment]
We're having the same issue in our company instance. We've been on the candidate release channel and only started having the same issue as described above with this latest version. We'll go to log in and the loading circle just goes forever and you can't ever login via LDAP anymore.
