### ISSUE TITLE
Bug: Fixed swimlane height

### ISSUE THREAD

**Issue by nebulade** [wekan/wekan#5057]
## Issue
With 26d2efdedb the swimlanes have a default height of 270px. The settings do not allow setting a nullish value to make it expand the full height, which was the behavior before. The only workaround right now seems to be to set this to a very high number. Am I missing something obvious to make it by default use the whole available height?

**Comment by xet7** [comment]
@nebulade 

Default should be full available height.

@mark-i-m 

Can you fix it and send PR ?
