### ISSUE TITLE
Feature Request: Customize some strings in some translations

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5065]
Moved to here from https://github.com/wekan/wekan/pull/5036

Example how someone could develop this for Admin Panel:

## 1. Create new table to database for translations

- https://github.com/wekan/wekan/tree/master/models
- for example, table/collection `wekan/models/translation.js`
- There add fields like this:
```
    language': {
      /**
       * The uniq ID of the member
       */
      type: String,
    },
    'text': {
      /**
       * The uniq ID of the member
       */
      type: String,
    },
    'translationText': {
      /**
       * The uniq ID of the member
       */
      type: String,
    },
```
Then add editing those values code, similar like in other files at `wekan/models`.

## 2. Add Admin Panel left menu option

For example below webhook settings:

https://github.com/wekan/wekan/blob/master/client/components/settings/settingBody.jade#L37-L40

For example this translation setting menu:

```
            li
              a.js-setting-menu(data-id="translation-setting")
                i.fa.fa-globe
                | {{_ 'translation'}}
```

## 3. Add editable translation table

Add file `wekan/client/components/settings/translationBody.jade`

There add Form for editing transations similar like editable people table here:

- https://github.com/wekan/wekan/blob/master/client/components/settings/peopleBody.jade#L216-L294

For example:
```
template(name="translation")
  table
    tbody
      tr
        th {{_ 'language'}}
        th {{_ 'text'}}
        th {{_ 'translationText'}}
        th
          +newTranslationRow
      each translation in translationList
        +translationRow(translationId=translation._id)
```

Add CSS file `wekan/client/components/settings/translationBody.css` similar like this:

- https://github.com/wekan/wekan/blob/master/client/components/settings/peopleBody.css

Add Javascript file for editing translations like this:

- https://github.com/wekan/wekan/blob/master/client/components/settings/peopleBody.js

## 4. Publish translations

Add file `wekan/server/publications/translation.js`
```
Meteor.publish('translation', function() {
  const ret = Translation.find();
  return ret;
});
```

## 5. Read published translations and use them

Subscribe to translation texts similar like this:

https://github.com/wekan/wekan/blob/master/client/components/boards/boardBody.js#L39

Subscribe at your translations change code file, and if that language is selected and in use, change that text to translationText:

https://github.com/wekan/wekan/pull/5036/files#diff-280798bf3228358cf15345e23bad3394c03fcbc47eebff8ecca3652a15df8f90

**Comment by xet7** [comment]
### Example ASCII mockup of Admin Panel left menu, add Translation menu to bottom
```
Admin Panel
Settings

Registration
Email
Accounts
Board visibility
Announcement
Layout
Global Webhooks
Translation
```
### Example Translation page

- Language from https://github.com/wekan/wekan/blob/master/imports/i18n/languages.js
- Translation files at https://github.com/wekan/wekan/tree/master/imports/i18n/data
- English string name https://github.com/wekan/wekan/blob/master/imports/i18n/data/en.i18n.json#L3C3-L3C50

Language | Text | Translation text | [New]
------------ | ------------- | ------------- | -------------
en | act-activity-notify | Custom Activity Notification | [Edit]
en | add-card | Add Custom Card | [Edit]
fi | act-activity-notify | Mukautettu aktiviteetti ilmoitus | [Edit]
fi | add-card | Lisää mukautettu kortti | [Edit]

**Comment by ipyramiddev** [comment]
@xet7 Ok, these above orders are to create custom strings. So, I should also modify imports/i18n/tap.js using these strings, right?

**Comment by xet7** [comment]
@ipyramiddev 

Yes.

**Comment by ipyramiddev** [comment]
@xet7 If you say yes, in tap.js I should connect to Database, and it means, tap.js has dependency on database. And I think, this is not good as i18n/js files should be simple and have dependencies as less as possible.

**Comment by ipyramiddev** [comment]
Besides, in your suggested translation page, to add new item, the user (administrator) should know each original certain word like 'add-card' and 'act-activity-notify'. We can know them because they can see i18n/data/language json files as developers, but how an administrator(user) can know those correct words on service? May be should I also add dropdown list for it?

**Comment by xet7** [comment]
@ipyramiddev 

WeKan also has Public Board feature, that shows realtime updates to boards, without logging in.

There is no version of WeKan that works without database.

WeKan wiki has pages with links how feature works https://github.com/wekan/wekan/wiki/Customize-Translations

**Comment by xet7** [comment]
From https://github.com/wekan/wekan/pull/5036#issuecomment-1658983421

From @xet7

Adding checking non-existing 128 custom translation files is a major slowdown.

**Comment by xet7** [comment]
@ipyramiddev 

Above I have described user friendly way to implement it without slowdown.

**Comment by xet7** [comment]
@ipyramiddev 

From your requirements at https://github.com/wekan/wekan/pull/5036#issuecomment-1659005911

> 3. the nicest variant would be if you could store them via text fields in the backend admin area of wekan."

**Comment by xet7** [comment]
@ipyramiddev 

Those queries are to browserside MiniMongo Javascript database where those values already are, because they have been published to browserside. There is no visit to serverside at all. Also Meteor reads any changes to MongoDB database from MongoDB change stream and immediately pushes changes to browserside where they can be used without any noticeable delays. Those are realtime features of Meteor full stack web framework www.meteor.com .

From https://github.com/wekan/wekan/issues/5065#issue-1839807114

## 4. Publish translations

Add file `wekan/server/publications/translation.js`
```
Meteor.publish('translation', function() {
  const ret = Translation.find();
  return ret;
});
```

**Comment by xet7** [comment]
@ipyramiddev 

If this were not about Meteor, but were done in tiny WeKan PHP prototype that does not have enough features yet, there also would be no problem, because first it would read translation file, then do one query to custom translation content, and then use those strings in PHP array everywhere, that is also very fast:

https://github.com/wekan/php/blob/main/page/translations.php#L10

**Comment by wolflion0812** [comment]
> Besides, in your suggested translation page, to add new item, the user (administrator) should know each original certain word like 'add-card' and 'act-activity-notify'. We can know them because they can see i18n/data/language json files as developers, but how an administrator(user) can know those correct words on service? May be should I also add dropdown list for it?

Ok, then how about this?

**Comment by xet7** [comment]
@wolflion0812

No drop-down list. It would be too many for that many strings. Just write it as text.

Also, often all of those change https://github.com/wekan/wekan/blob/master/imports/i18n/data/en.i18n.json
- New translations
- New text, what to translate for new feature
- New translation

**Comment by ipyramiddev** [comment]
Hi, @wolflion0812 
Thank you for your interesting on my opinion. :)

**Comment by ipyramiddev** [comment]
@xet7 I have one thing to be clear. For example, if an admin wants to change the string of webhook of creating board, how should he add translation in your suggesting translation page.

**Comment by xet7** [comment]
@ipyramiddev 

 I updated above examples https://github.com/wekan/wekan/issues/5065#issuecomment-1668259510

Buttons of New and Edit, copy code from wekan/client/components/settings/ where is Admin Panel / People / People, similar like adding or editing Organizations/Teams/People, copy code from those and edit to similar code.

**Comment by xet7** [comment]
@ipyramiddev 

At Admin Panel / People is already working examples how to add new, edit, etc, same code and forms just copy to editing Translations.

**Comment by webenefits** [comment]
Hello together,

we are the clients of the original feature request. 

In this case we want to be able to customize the text of the webhook. The whole thing must be implemented so that you @xet7 then merge it into your codebase. Our requirement is not necessarily to customize all translations, but mainly the text that is sent through the webhook. Of course it would be nice to be able to customize the text in the admin area, so we don't have to search in the source files, which could be difficult with a snap installation for example. Here the original request: https://github.com/wekan/wekan/pull/5036#issuecomment-1659005911

@xet7 which way would you recommend for this without the feature being too complex to implement?

@ipyramiddev please estimate then the effort for this.

And @xet7 for your information: Our intension is to hire ipyramiddev for further developments, which will hopefully be taken over by you into the core. For example https://github.com/wekan/wekan/issues/4388 or https://github.com/wekan/wekan/issues/3948

Many greetings

**Comment by xet7** [comment]
@webenefits 

Above in this issue comments I have described the recommended way to implement this, so that this can be merged.

**Comment by xet7** [comment]
@webenefits @ipyramiddev 

Point in developing WeKan features is to ask any questions immediately, so that I can answer them. That makes for fast progress. There are no stupid questions. There is only my stupid answers.

https://blog.wekan.team/2018/05/wekan-v1-00-released/

All development help is very welcome. It is a lot of work for me to maintain WeKan, upgrade WeKan dependencies, develop features and fixes where many are In Progress, develop WeKan security fixes (sometimes some WeKan contributors and security researchers help), etc. It would be nice that with help of WeKan contributors more of open issues could be implemented, fixed and closed.

**Comment by ipyramiddev** [comment]
@xet7 As you know, webhook api descriptions include micros. For example, 
"act-addedLabel": "Added label __label__ to card __card__ at list __list__ at swimlane __swimlane__ at board __board__"
So when an admin user edit or create custom strings, they might miss some macros, and I think, this is very dangerous.
What about you?

**Comment by xet7** [comment]
@ipyramiddev 

There could be use case, that webhook should not include board name for some reason, for example to not show private data.

In that case, there would not be text `at board __board__`

I do not think it is dangerous. You see at Admin Panel what translations have been modified.

**Comment by xet7** [comment]
@ipyramiddev 

If there needs to be audit logs about who did change webhooks, and saving that audit logs to database, that can be done same way I added audit logs to Admin Panel Impersonate User https://github.com/wekan/wekan/commit/3908cd5413b775d1ee549f0a95304cf9998d3855 . That audit data is at database, but there is not yet web UI at Admin Panel for that audit data.

**Comment by xet7** [comment]
@ipyramiddev 

But if there is requirement that Admin should not be able to mess up translation strings, you could check that source string and new string have same amount of same named macros, by making check with Javascript, and showing error message when it does not match.

**Comment by xet7** [comment]
@ipyramiddev 

Not being able to mess up something is one of design principles of WeKan, that we should try to implement as much as possible:

https://github.com/wekan/wekan/wiki/Monkey-Proof-Software

**Comment by ipyramiddev** [comment]
@xet7 Ok, thank you for your explain.

**Comment by xet7** [comment]
@webenefits 

If this feature for 1000 euro is prepaid at https://wekan.team/commercial-support/ , after payment is received, this feature is added to WeKan in 2 weeks.

I can not estimate for anyone else.

**Comment by ipyramiddev** [comment]
> 

@xet7 Now I am working for this issue as you recommended, and I have a question. I should add some strings such as 'translation', 'text', 'language' into i18n\data, so should I these strings to all files in i18n\data? Or is there any convenient way to add a new string?

**Comment by xet7** [comment]
@ipyramiddev 

If string is not yet in this file, add to bottom of this file, that is original source strings of translations:

https://github.com/wekan/wekan/blob/master/imports/i18n/data/en.i18n.json

In that file are also popup-title source strings.

Others are translated here:
https://explore.transifex.com/wekan/wekan/

If some language is not translated to 100% yet, anyone can join and translate, and request new languages.

I download new translations from transifex and add them to WeKan often and before making new releases. That is seen at commit logs as "Updated translations." and at changelog when new language has been added.

**Comment by ipyramiddev** [comment]
@xet7 I added new source codes for this function again as you recommended.  - pull request #5085 
Please check it and merge it.

**Comment by xet7** [comment]
@ipyramiddev 

Please create new PR where you make these changes to your code, so that it works correctly with reactiveCache:

https://github.com/wekan/wekan/issues/5000#issuecomment-1640950446

**Comment by ipyramiddev** [comment]
@xet7 
I worked with latest source code, so those changes are already on my source code.

**Comment by ipyramiddev** [comment]
Ok. I will check and do it.

**Comment by ipyramiddev** [comment]
I've created new PR, please check it.

**Comment by xet7** [comment]
This feature will be in WeKan v7.08

Docs at https://github.com/wekan/wekan/wiki/Customize-Translations
