### ISSUE TITLE
Webpack and tree shaking?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5067]
- https://forums.meteor.com/t/meteor-webpack-integration-tree-shaking-secured-code-and-more/60290
- https://github.com/freak2geek/simpletasks-webpack

@mfilser @helioguardabaxo @VidVidex @nebulade @mark-i-m @Pandetthe @DimDz 

Do you understand what this is? Would it work with WeKan? Can you try?

**Comment by mark-i-m** [comment]
I don't know enough about either meteor or webpack to know what this is or why it is useful. As a general rule, though, I would be wary of adding a dependency on a tool developed and maintained by a single hobbyist; when it breaks or the hobbyist gets busy, you will be left up a creek without a paddle...
