### ISSUE TITLE
cleaner memberlist popups

### ISSUE THREAD

**Issue by chrisi51** [wekan/wekan#5068]
i would like to optimize this view:
![image](https://github.com/wekan/wekan/assets/2156760/ae07ab57-819d-4d73-baa4-511f73da1eba)
to this one:
![image](https://github.com/wekan/wekan/assets/2156760/87c63b89-824a-448f-b64c-bf7395076256)

**Comment by chrisi51** [comment]
another problem is that the memberlist for adding ppl to board is ordered by username as it seems but all other memberlists on a card itself seem to be unordered

![image](https://github.com/wekan/wekan/assets/2156760/76dc0157-0f97-43d3-830f-ff3a4883125e)
at least its not ordered by username or fullname

and i can't find any point where to add a sort for this. i thought about the global members array to get sorted, so that every copy or filtered list of that may be sorted aswell.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5066
