### ISSUE TITLE
move card rule on checklist complete doesn't work

### ISSUE THREAD

**Issue by matdemb** [wekan/wekan#5069]
### Server Setup Information
* Did you test in newest Wekan?: Yes (7.0.4)
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: debian 11.7
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version:
* MongoDB Version: 6.0.8
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Edge 115, Firefox 116

### Problem description
The rules that move a card when a checklist is completed doesn't works anymore. It worked on 6.98 but not after un upgrade to 7.01 or 7.04
#### Reproduction Steps
Create a rule "when the checklist XXX is completed by * Move cards to top of the board current in list YYYY in swimlane *", create a card with a checklist XXX and complete it to see if the card is moved.

#### Logs

Nothing in Chrome Console

Only logs about authentication in "sudo docker logs wekan-app"

**Comment by DimDz** [comment]
Any news regarding this issue? I might have time to look it at next Friday.

**Comment by xet7** [comment]
@DimDz 

Thanks! I think nobody has looked at this yet. I'm In Progress of trying to make upgrades to all WeKan platforms.

**Comment by xet7** [comment]
All help is very welcome !

**Comment by xet7** [comment]
I do remember time, when we had about 500 issues open. It would be nice sometime to get back there.

**Comment by DimDz** [comment]
removing the reactiveCache code on the models/checklistItems.js and models/checklists.js seems to fix the issue with the move card rule.

**Comment by xet7** [comment]
@mfilser 

What do you think about this, at above comment?

**Comment by mfilser** [comment]
@xet7
I can have a look at this.

**Comment by DimDz** [comment]
I put all the code of v6.98 in checklists.js and checklistitems.js.

**Comment by mfilser** [comment]
@DimDz 
There are several checklists.js files, which folder?

**Comment by DimDz** [comment]
@mfilser 
on the models folder as I mentioned on my previous comment.
