### ISSUE TITLE
Install Wekan on Synology

### ISSUE THREAD

**Issue by Kyryus** [wekan/wekan#507]
Hello,

When I try to install Wekan on Synology by manual installation, I receive a message : "Invalid file format".

Can you explain me how to install it on Synology ?

I have DSM 5.2 and DS414.

Thank you in advance for your help,

**Comment by manuelsongokuh** [comment]
Wekan on DSM with DOCKER.. but bad information: docker works 64bit only..

**Comment by carlokok** [comment]
+1

**Comment by xet7** [comment]
What processor Synology has?

**Comment by saschafoerster** [comment]
You can install Wekan easily on Synology, if your Synology supports docker: 
https://www.synology.com/de-de/dsm/packages/Docker
Your model doesn't support Docker, so I guess, you can't install Wekan without good knowledge of servers and the Synology operating system. 

For the others looking for help with docker on Synology: 

create a docker-compose.yml in a subfolder like /volume1/docker/wekan based on this example: 

https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml

and then: `sudo docker-compose up -d` in that folder.

**Comment by Kyryus** [comment]
Hello Sascha,

I changed my DS414 to a DS1515+ and I installed it using docker. So it is working.

Thank you for all your responses :)
