### ISSUE TITLE
alphabetic ordered member lists

### ISSUE THREAD

**Issue by chrisi51** [wekan/wekan#5070]
another problem is that the memberlist for adding ppl to board is ordered by username as it seems but all other memberlists on a card itself seem to be unordered

![image](https://github.com/wekan/wekan/assets/2156760/76dc0157-0f97-43d3-830f-ff3a4883125e)
at least its not ordered by username or fullname

and i can't find any point where to add a sort for this. i thought about the global members array to get sorted, so that every copy or filtered list of that may be sorted aswell.

**Comment by xet7** [comment]
@chrisi51 

Maybe this? I think it does not yet have sort.

https://github.com/wekan/wekan/blob/master/models/users.js#L567

**Comment by chrisi51** [comment]
is this the global users object which could get sorted in that line? 

https://github.com/wekan/wekan/blob/a60acac51ac833f2a7618f36c6df230a9856d30e/models/users.js#L11C3-L11C3

**Comment by xet7** [comment]
@chrisi51 

Hmm, I don't know? Just try something.
