### ISSUE TITLE
wekan SNAP MongoDB Error

### ISSUE THREAD

**Issue by 10erNetzwerk** [wekan/wekan#5073]
Hi, I've encountered a problem with my WEKAN instance. We've been using the Snap version for months without any issues. However, since yesterday, we've had this problem. I found the same issue on Github, but there it was related to Docker, not Snap.

https://github.com/wekan/wekan/issues/3528

` sudo systemctl status snap.wekan.wekan.service
● snap.wekan.wekan.service - Service for snap application wekan.wekan
     Loaded: loaded (/etc/systemd/system/snap.wekan.wekan.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-08-08 13:40:29 UTC; 13s ago
   Main PID: 12508 (wekan-control)
      Tasks: 12 (limit: 19088)
     Memory: 187.6M
     CGroup: /system.slice/snap.wekan.wekan.service
             ├─12508 /bin/bash /snap/wekan/1999/bin/wekan-control
             └─13504 /snap/wekan/1999/bin/node --stack-size=65500 main.js

Aug 08 13:40:33 wekan-server wekan.wekan[12508]: MONGO_URL=mongodb://127.0.0.1:27019/wekan
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: Note: you are using a pure-JavaScript implementation of bcrypt.
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: While this implementation will work correctly, it is known to be
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: approximately three times slower than the native implementation.
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: In order to use the native implementation instead, run
Aug 08 13:40:39 wekan-server wekan.wekan[13504]:   meteor npm install --save bcrypt
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: in the root directory of your application. You may also need to
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: install build tools to compile bcrypt. For more information see:
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: https://github.com/nodejs/node-gyp#installation
Aug 08 13:40:39 wekan-server wekan.wekan[13504]: Presence started serverId=XwaQyM3TfFD8kbstQ
Aug 08 13:40:43 wekan-server wekan.wekan[13504]: /snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb/lib/utils.js:98
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     process.nextTick(function() { throw err; });
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:                                   ^
Aug 08 13:40:43 wekan-server wekan.wekan[13504]: Error [MongoError]: no chunks found for file, possibly corrupt
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at Function.MongoError.create (/snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb-core/lib/error.js:31:11)
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:825:29
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:1201:5
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at handleCallback (/snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb/lib/utils.js:96:12)
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb/lib/collection.js:1401:5
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at handleCallback (/snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb/lib/utils.js:96:12)
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb/lib/cursor.js:675:5
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at handleCallback (/snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb-core/lib/cursor.js:172:5)
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at setCursorNotified (/snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb-core/lib/cursor.js:517:3)
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb-core/lib/cursor.js:590:16
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at queryCallback (/snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb-core/lib/cursor.js:233:18)
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at /snap/wekan/1999/programs/server/npm/node_modules/meteor/wekan-cfs-gridfs/node_modules/mongodb-core/lib/connection/pool.js:436:18
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
Aug 08 13:40:43 wekan-server wekan.wekan[13504]:   driver: true
Aug 08 13:40:43 wekan-server wekan.wekan[13504]: }
Aug 08 13:40:43 wekan-server systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 13:40:43 wekan-server systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
`

**Comment by xet7** [comment]
I added repair info to wiki https://github.com/wekan/wekan/wiki/Repair-MongoDB

**Comment by 10erNetzwerk** [comment]
@xet7 

Thank you for your fast response.

The error is gone, but now I get "ERR_CONNECTION_REFUSED" when accessing the website.
The command "ss -tunelp | grep 80" returns no output.
Which logs do you need to fix the system?

**Comment by xet7** [comment]
@10erNetzwerk 

1. Try reboot. Does it work then?
2. See what is running:
```
sudo snap services
```
3. See what version of WeKan it is:
```
sudo snap list
```
4. See WeKan settings. Have you set root-url and port ?
```
sudo snap get wekan
```

**Comment by xet7** [comment]
@10erNetzwerk 

If wekan or mongodb is not running, this can also be tried:
```
sudo snap start wekan.mongodb

sudo snap start wekan.wekan
```

**Comment by 10erNetzwerk** [comment]
Hello @xet7,

Thank you for the response. I've restarted the server multiple times.

Here are the results of the commands:

root@wekan-server:~# sudo snap services
Service        Startup   Current   Notes
wekan.caddy    disabled  inactive  -
wekan.mongodb  enabled   active    -
wekan.wekan    enabled   active    -



root@wekan-server:~# sudo snap list
Name   Version    Rev    Tracking       Publisher   Notes
core   16-2.59.5  15511  latest/stable  canonical✓  core
wekan  6.09       1999   latest/stable  xet7        -


root@wekan-server:~# sudo snap get wekan
Key       Value
port      80
root-url  http://10.XX.XX.XX

(its the correct local server ip)

**Comment by xet7** [comment]
@10erNetzwerk 

```
sudo snap logs wekan.wekan

sudo snap logs wekan.mongodb
```

**Comment by 10erNetzwerk** [comment]
@xet7 

root@wekan-server:~# sudo snap logs wekan.wekan
2023-08-10T10:52:42Z wekan.wekan[222614]: NODE_OPTIONS=--max_old_space_size=4096 (default value)
2023-08-10T10:52:42Z wekan.wekan[222614]: MONGO_URL=mongodb://127.0.0.1:27019/wekan
2023-08-10T10:52:48Z wekan.wekan[223548]: Note: you are using a pure-JavaScript implementation of bcrypt.
2023-08-10T10:52:48Z wekan.wekan[223548]: While this implementation will work correctly, it is known to be
2023-08-10T10:52:48Z wekan.wekan[223548]: approximately three times slower than the native implementation.
2023-08-10T10:52:48Z wekan.wekan[223548]: In order to use the native implementation instead, run
2023-08-10T10:52:48Z wekan.wekan[223548]:   meteor npm install --save bcrypt
2023-08-10T10:52:48Z wekan.wekan[223548]: in the root directory of your application. You may also need to
2023-08-10T10:52:48Z wekan.wekan[223548]: install build tools to compile bcrypt. For more information see:
2023-08-10T10:52:48Z wekan.wekan[223548]: https://github.com/nodejs/node-gyp#installation



root@wekan-server:~# sudo snap logs wekan.mongodb
2023-08-10T10:05:49Z wekan.mongodb[27477]: SAML_IDENTIFIER_FORMAT= (default value)
2023-08-10T10:05:49Z wekan.mongodb[27477]: SAML_LOCAL_PROFILE_MATCH_ATTRIBUTE= (default value)
2023-08-10T10:05:49Z wekan.mongodb[27477]: SAML_ATTRIBUTES= (default value)
2023-08-10T10:05:49Z wekan.mongodb[27477]: ORACLE_OIM_ENABLED=false (default value)
2023-08-10T10:05:50Z wekan.mongodb[27477]: RESULTS_PER_PAGE= (default value)
2023-08-10T10:05:50Z wekan.mongodb[27477]: WAIT_SPINNER=Bounce (default value)
2023-08-10T10:05:50Z wekan.mongodb[30436]: error: error running snapctl: get which option?
2023-08-10T10:05:50Z wekan.mongodb[27477]: NODE_OPTIONS=--max_old_space_size=4096 (default value)
2023-08-10T10:05:50Z wekan.mongodb[27477]: mongodb bind options:  --bind_ip 127.0.0.1 --port 27019
2023-08-10T10:05:50Z wekan.mongodb[27477]: Sending mongodb logs to /dev/null

**Comment by xet7** [comment]
@10erNetzwerk 


Change saving MongoDB logs to file:
```
sudo snap set wekan mongo-log-destination='snapcommon'
```
Look that there comes some logs:
```
sudo tail -f /var/snap/wekan/common/mongodb.log
```
Add mongodb.log to .zip archive and attach to comment of this issue.

MongoDB log destinations are listed here:

https://github.com/wekan/wekan/blob/master/snap-src/bin/mongodb-control#L93-L107

**Comment by xet7** [comment]
Before adding logs to .zip file, edit logfile to remove any private data.

**Comment by 10erNetzwerk** [comment]
@xet7 

[mongodb.zip](https://github.com/wekan/wekan/files/12312044/mongodb.zip)

**Comment by xet7** [comment]
@10erNetzwerk 

Try does this help?
```
sudo snap refresh --devmode wekan

sudo snap start wekan
```

**Comment by 10erNetzwerk** [comment]
That didn't help. The commands executed without errors, but the website still displays the "ERR_CONNECTION_REFUSED" error.

root@XXX:~# sudo snap refresh --devmode wekan
snap "wekan" has no updates available
root@XXX:~# sudo snap start wekan
Started.

**Comment by xet7** [comment]
@10erNetzwerk 

> That didn't help. The commands executed without errors, but the website still displays the "ERR_CONNECTION_REFUSED" error.

Maybe you have something else running at port 80 ?

```
sudo systemctl stop nginx

sudo systemctl disable nginx

sudo systemctl stop apache2

sudo systemctl disable apache2

sudo snap start wekan
```

**Comment by xet7** [comment]
@10erNetzwerk 

Look at what is running at port 80:

```
sudo apt-get -y install net-tools

sudo netstat -plant | grep :80
```
