### ISSUE TITLE
Wekan Windows bundle does not start

### ISSUE THREAD

**Issue by Bu11etmagnet** [wekan/wekan#5076]
### Server Setup Information

* Did you test in newest Wekan?: almost - https://releases.wekan.team/windows/wekan-7.05-amd64-windows.zip
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Windows 10
* Deployment Method bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.8
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? N/A

### Problem description
c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle>start-wekan.bat
c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Cannot find module "/node_modules/meteor/accounts-password/node_modules/bcrypt/bcrypt.js". Try installing the npm package or make sure it is not a devDependency.
    at Module.useNode (packages\modules-runtime.js:741:11)
    at module (c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\packages\accounts-password.js:1245:8)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at Module.moduleLink [as link] (c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\npm\node_modules\meteor\modules\node_modules\@meteorjs\reify\lib\runtime\index.js:52:22)
    at module (packages/accounts-password/password_server.js:1:37)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at require (packages\modules-runtime.js:258:21)
    at c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\packages\accounts-password.js:1256:1
    at c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\packages\accounts-password.js:1261:3
    at c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\boot.js:385:38
    at Array.forEach (<anonymous>)
    at c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\boot.js:210:21
    at c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\boot.js:439:7
    at Function.run (c:\Users\Bu11etmagnet\wekan\wekan-7.05-amd64-windows\bundle\programs\server\profile.js:256:14)

#### Reproduction Steps
Install MongoDB
Unzip wekan-7.05-amd64-windows.zip
Copy node-v14.21.4-win-x64.exe into bundle as node.exe
Copy start-wekan.bat into bundle
Edit start-wekan.bat

```
REM # MongoDB database URL required
SET MONGO_URL=mongodb://127.0.0.1:27017/wekan

REM # If port is 80, must change ROOT_URL to: http://YOUR-WEKAN-SERVER-IPv4-ADDRESS , like http://192.168.0.100
REM # If port is not 80, must change ROOT_URL to: http://YOUR-WEKAN-SERVER-IPv4-ADDRESS:YOUR-PORT-NUMBER , like http://192.168.0.100:2000
REM # If ROOT_URL is not correct, these do not work: translations, uploading attachments.
SET ROOT_URL=http://localhost

REM # Must change to YOUR-PORT-NUMBER:
SET PORT=80
```

Run start-wekan.bat

The same procedure worked in 2021 with wekan 5.61

**Comment by xet7** [comment]
I built new Node.js 14.21.4 from source for Windows, because that existing looked like old version Meteor included to bundle, looking at version with this command:
```
node -v
```
I also built WeKan 7.05 bundle again, including bcrypt correctly this time, making sure it starts correctly.

Your start-wekan.bat should have WeKan server IP address and WRITABLE_PATH like here at wiki page. Not localhost.

https://github.com/wekan/wekan/wiki/Offline

**Comment by MeriemBH** [comment]
Hello,

i have the same issue. Did you solve it?

thanks

**Comment by xet7** [comment]
It looks like Windows version does not currently work, it shows that error. I'll try to look at it.

**Comment by MeriemBH** [comment]
@xet7 FYI this issue appeared even for windows2022.
i will wait for your update
thanks

**Comment by MeriemBH** [comment]
Hello Lauri,
Do you have any idea when this issue will be resolved?
thanks

**Comment by xet7** [comment]
@MeriemBH 

I don't know yet.

At Windows, it is possible to use Docker, with docker-compose.yml from https://github.com/wekan/wekan

**Comment by MeriemBH** [comment]
unfortunately, i thought it would be possible to install wekan offline. i don't have access to the net in the server side.

**Comment by MeriemBH** [comment]
unfortunately, i thought it would be possible to install wekan offline. i don't have access to the net in the server side.

**Comment by xet7** [comment]
@MeriemBH 

From https://wekan.github.io

> Newest WeKan at amd64 platforms: Linux bundle, Snap Candidate, Docker, Kubernetes. Fixing other platforms In Progress. 

It is possible to install offline. For example:

1. Install Linux Mint/Ubuntu/Debian amd64 to VM, like VirtualBox/VMware/Qemuetc
2. Install WeKan Snap Candidate, Docker or Bundle to   VM
3. Copy VM to offline
4. Setup bridged networking, like at https://github.com/wekan/wekan/wiki/virtual-appliance#how-to-use

But that previous way, installing directly at Windows, is currently broken. I don't know will it be fixed for example next year, it depends when updates become available.
