### ISSUE TITLE
When I have an active webhook/integration, the board does not save card positions

### ISSUE THREAD

**Issue by soucannabisdev** [wekan/wekan#5077]
When creating a new webhook/integration, the system only sends the first request, then stops sending data through the webhook and stops saving the position of the cards.

When reloading the page and moving a card, it sends the first request and stops sending the webhook data again and the cards return to the position they were before being moved.

Has anyone had this problem or have a solution for it?

**Comment by xet7** [comment]
@soucannabisdev 

Best is in your webhook receiver reply 200 OK immediately and then continue other stuff in your webhook receiver.

https://github.com/wekan/webhook/blob/main/public/index.php#L48C1-L48C1
