### ISSUE TITLE
Board Titles with '#' Break the Favorites Bar

### ISSUE THREAD

**Issue by Kubo-Security** [wekan/wekan#5079]
### Server Setup Information

* Did you test in newest Wekan?: **yes**
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? **yes**
* Operating System: **Ubuntu 22.04.3 LTS**
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): **docker**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): **no**
* Node.js Version: **dont know, just used https://raw.githubusercontent.com/wekan/wekan/master/docker-compose.yml**
* MongoDB Version: **dont know, just used https://raw.githubusercontent.com/wekan/wekan/master/docker-compose.yml**
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? **Firefox 116.0.2**

### Problem description

The favorites bar breaks when a table title contains Markdown, especially headings with `#`

![image](https://github.com/wekan/wekan/assets/64486743/2486f25e-c877-464e-9a7e-5f8f88ab6f93)

![image](https://github.com/wekan/wekan/assets/64486743/e10b4f51-6dc7-402f-ab80-fba8639c985d)

#### Reproduction Steps
Create board with title `# Test 1`, mark as favorite

**Comment by xet7** [comment]
Yes, board title can have markdown. But this is not a problem. You can change board title back to not have `#` that is H1 formatting. You have not made something that is not possible to fix yourself.
