### ISSUE TITLE
Need to rebuild bcrypt when installing from source on OS X 10.11.2

### ISSUE THREAD

**Issue by pol** [wekan/wekan#508]
The instructions are more or less correct, I did the following to get a local install working on MacOS.  Things that the instructions had wrong or that I had to do extra are bold:
1. brew install mogodb
2. **brew install node 0.12.7**
   - it has to be backported, meteor doesn't work with new node
3. install meteor: `curl https://install.meteor.com/ | sh`
   - check the script source if you want, it was safe when I looked.
4. `cd /path/to/install`
5. `git clone https://github.com/wekan/wekan.git && cd wekan`
6. `meteor build .build --directory`
7. `cd .build/bundle/programs/server/`
8. **remove bcrypt**: `rm -rf npm/bcrypt && npm install bcrypt`
   - you get a "Error: Module did not self-register." for npm/bcrypt if you try run with the default.
9. `npm install`
10. **Install mailcatcher for local smtp (if you don't otherwise want/have smtp)**
    - `gem install mailcatcher`
    - `mailcatcher`
    - mailcatcher runs as a daemon and you just kill it from its UI
11. Make a little script called `run-wekan.sh` with the following in it (**node main.js path is wrong in the instructions**):
    
    ```
    #!/bin/sh
    
    export MONGO_URL='mongodb://127.0.0.1:27017/wekan'
    export ROOT_URL='http://localhost:6283'
    export MAIL_URL='smtp://localhost:1025'
    export PORT=6283
    
    cd /path/to/install/wekan/
    node .build/bundle/main.js 
    ```
12. `chmod +x run-wekan.sh` and then run it.
13. Open up your browser to http://localhost:6283. You can change that port if you want, but the others are the default for those apps (mongo, mailcatcher).

**Comment by xet7** [comment]
It would be easier to use latest Docker image on Mac.
