### ISSUE TITLE
Problem to visualize ticket or creat them in the calendar (board-view-cal)

### ISSUE THREAD

**Issue by pamini65** [wekan/wekan#5082]
On WEKAN V7.06 we are not able to visualize the tickets in the calendar(board-view-cal). It's also impossible to create and manage ticket via the calendar menu. Are we missing a plugin or is this a missing feature.

**Comment by xet7** [comment]
@pamini65 

I created wiki page about create card at calendar, and what is missing.

https://github.com/wekan/wekan/wiki/Calendar

WeKan does not have plugin system. All features that exist are included.

Anyone can look at WeKan code and send feature or fix as PR https://github.com/wekan/wekan/wiki/Emoji

Or alternatively fund feature or fix https://wekan.team/commercial-support/
