### ISSUE TITLE
Calendar view broken after updating to v7.XX

### ISSUE THREAD

**Issue by ricardogfp** [wekan/wekan#5086]
When creating new cards on the calendar view on version v7.00 and up, the card is created on the list view but it doesn't show on the calendar view. Similarly if a card with due date is created on the list view it is not shown on the calendar view.
Rolling back to v6.99 solved the issue

**Comment by saschafoerster** [comment]
Our calendar is empty as well (Wekan 7.08, docker)

**Comment by mfilser** [comment]
@xet7 
I will have a look at this

**Comment by DimDz** [comment]
After creating a card, I have to hit refresh button in order for the card to appear on the calendar. Is it intended?

**Comment by mfilser** [comment]
I don't think so. I haven't used the calender view yet.
I hope to find some time the next days to look at this again.

**Comment by mfilser** [comment]
I looked at this and tested with Wekan v6.97 and it wasn't there working too. New cards created by calender view aren't visible right after creation with v6.97, there's a reload necessary too.

So it's not a problem of Wekan v7.xx.

**Comment by mfilser** [comment]
@xet7 
If you can confirm this I think you can close this issue because it's not related to v7.xx. It's a new feature request to have cards visible right after creation by calender view.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5105 . Thanks to DimDz !

**Comment by saschafoerster** [comment]
@xet7 Would be lovely to push a new version with it. :) Thank you!
