### ISSUE TITLE
Safari attachment preview of images can't be scrolled up

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#5089]
## Issue
When opening an image to see the full view from attachment view, then the full image is now shown, but I can't scroll up to the bottom of the image. I would either like to scroll, or have a preview that shows the full image in the browser window. 

### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Debian 11
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node.js Version:  14.21.4
* MongoDB Version: 6.09
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Safari 16.6

### Problem description
<img width="852" alt="Bildschirmfoto 2023-08-18 um 12 34 58" src="https://github.com/wekan/wekan/assets/1153741/fe21acbf-c04a-4154-abf2-a335c68c394b">
When the image is larger than the screen, then I should be able to scroll the image, but it doesn't move. 

#### Reproduction Steps
- Upload image
- Show full image

#### Logs
None

**Comment by xet7** [comment]
@VidVidex 

Can you look at this?
