### ISSUE TITLE
Make a SMTP page in the administration to test Parameters 

### ISSUE THREAD

**Issue by scoubidoo** [wekan/wekan#509]
hello, thanks to developping Wekan it's smooth and beautiful board.

but i have some issues to configure  the smtp and test if this parameter it's OK.

Can you add for a futur release a panel where we can add the smtp parameters and we can test by sending a mail if the parameters are ok.

thx for all.

**Comment by jamesacampbell** [comment]
Would really like this. I can't get smtp.google.com to work yet.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
