### ISSUE TITLE
Welcome board not working

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#51]
When a new user is created, we want to create a sample board. This feature is broken due to the `userId` parameter of the `after.insert` hook being `null` ; and we consequently create a `BoardMembers` document with a null `userId`.

**Comment by mquandalle** [comment]
[Here](https://github.com/yasaricli/metrello/commit/df1642494c0ac427bdb133fc8b71298701f8fd1b#diff-13b3b47c8335836d2a2e0da24cc7256eL73) is a hacky fix.

**Comment by mquandalle** [comment]
Fixed in 5d43a5f61d777542eddcfdbca1765048268981fa

**Comment by pauricthelodger** [comment]
I just set up an account and I'm afraid that there was no welcome board. Had this commit been released yet?

**Comment by mquandalle** [comment]
Yes, but a commit (8d2f687464660b35103b14856a8e33db2273b55d) broke this feature again.

Anyway I plan to refactor this welcome board with the following goals in mind:

1. Have a board that explains the project
2. Have it available in the user language
3. Displayed in the home page (if the user is not connected)
4. Copied into the user board list when a user create a new account

**Comment by pauricthelodger** [comment]
Good plan! May I also suggest adding an about link in the header member menu? Even a link to this repo as it was rather empty for myself as a new user. Not that I minded, I just searched here. Would you prefer I open a separate issue for that, if you think it's something to think about?

**Comment by mquandalle** [comment]
The home definitely need a lot of work (which in a way is not too bad, because it slow down adoption while we're implementing new features like crazy!). Yes, you can open a new issue about it :-)
