### ISSUE TITLE
Card details view largely broken on IE

### ISSUE THREAD

**Issue by kentonv** [wekan/wekan#510]
On Internet Explorer 11 (as tested on Windows 7), the card details view (opened by clicking a card) has some pretty big bugs:
- Comments are not displayed. (You can add new comments, but you can't see them once added.)
- Clicking on "edit" under "description" closes the panel.

These were reported by a user. There may be other problems; I haven't tested everything.

**Comment by NickG-WC** [comment]
I've found IE support issues in a few places.  

Attached is a screenshot of the issue kentonv has reported.
![card-comments](https://cloud.githubusercontent.com/assets/9416485/13014432/b110e486-d1ab-11e5-9936-a0d305f11c71.png)

Also, clicking the filter icon takes the user back to the board selection screen in IE.

I've also had users report that they've come back to the browser to find they are at a screen saying board not found - again I've attached a screenshot.
![board-not-found](https://cloud.githubusercontent.com/assets/9416485/13014433/b1202b80-d1ab-11e5-8656-6beec2cd0610.png)

Nick

**Comment by darkree** [comment]
Am having no joy with IE and Wekan.  Same issue as kentonv and NickG-WC.
Using IE 11 (Edge) - Getting the following errors

**DOM7011:** The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337

**HTML1501:** Unexpected end of file.
Exception from Tracker recompute function:
Error: cannot call methods on sortable prior to initialization; attempted to call method 'option'
   at error (http://156.129.202.83/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:21:13048)
   at Anonymous function (http://156.129.202.83/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:230:5616)
   at each (http://156.129.202.83/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:21:14213)
   at ie.prototype.each (http://156.129.202.83/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:21:12059)
   at t.fn[e] (http://156.129.202.83/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:230:5563)
   at Anonymous function (http://156.129.202.83/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:379:2530)
   at Anonymous function (http://156.129.202.83/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18456)
   at e._withTemplateInstanceFunc (http://156.129.202.83/8e718784e5e106f4d9f24ce295
![err](https://cloud.githubusercontent.com/assets/17908282/13863742/a9e18f46-ec61-11e5-8007-6276d4fce1d8.jpg)

**Comment by jumbojett** [comment]
Bump

**Comment by ocdtrekkie** [comment]
My experience with the latest https://github.com/wefork/wekan version on Sandstorm using Microsoft Edge is that the comments do not display on a card until I hover over the "Write a comment" box, and then they seem to pop in and load. I do not know why.

@xet7 Should issues like this be reopened against wefork, or is it safe to assume people still monitor and look at issues here?

**Comment by xet7** [comment]
@ocdtrekkie 

IE 11 issue can be continued at existing Wefork issue:
https://github.com/wefork/wekan/issues/60

I don't know does Microsoft Edge behave the same way, so is it the same issue.

Generally all still existing issues need to be reopened against wefork and all relevant info added there, if there is no existing wefork issue yet, because there it's possible to rename/combine/close issues.

**Comment by ocdtrekkie** [comment]
wefork#60 seems to be fairly different to what Kenton and I have seen. Edge often shares some weird rendering quirks with it's elder cousin, and I'm fairly confident @kentonv and I have the same issue.

**Comment by xet7** [comment]
@ocdtrekkie 

Ok, create separate wefork issue for Edge.

**Comment by dwrensha** [comment]
We've determined that the comments-loading issue on Edge was due to a bug in Sandstorm causing @ocdtrekkie to see a stale version of the Wekan SPK. The problem is not present on the latest version of the Wekan SPK.
