### ISSUE TITLE
GitHub rate limiting git clone wekan repo to 200 KiB/sec

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5101]
Hi,
I have cable Internet, that can download sometimes 5 MB/sec or 10MB/sec.
But when I do this:
```
git clone https://github.com/wekan/wekan
```
GitHub is rate limiting git clone to 200 KiB/sec.

If I change to 5G WLAN shared from smartphone, there git clone downloads faster.

Does this happen to anyone else?

Or is it just that WeKan is too popular, when it's used at most countries of the world, GitHub barely can handle the load?

Maybe some repo mirror on some other server could improve this.

Related to this, downloading issues with git-bug or gitea is slow also, because of GitHub rate limiting.

Maybe downloading from some Gitea or Fossil SCM repo would be faster. Fossil also syncs issues.

What do you all think?

**Comment by DimDz** [comment]
I do git clone pretty often, downloading from 7.90 MiB/sec at least and haven't seen 200 KiB/sec yet. I am downloading from a Windows 11 environment and Ubuntu environment, both seem okay and haven't had any problems.

**Comment by xet7** [comment]
Ok, maybe it is just a temporary issue.
