### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by Fedox-die-Ente** [wekan/wekan#5108]
Where is the save location from wekan if i installed it via snapd? I want to change the webhook thing

**Comment by xet7** [comment]
@Fedox-die-Ente 

> Where is the save location from wekan if i installed it via snapd?

If you mean uploaded attachments, they are in MongoDB database, using GridFS. You can save those attachments with NoSQLBooster https://github.com/wekan/wekan/wiki/Backup#using-nosqlbooster-closed-source-mongodb-gui-with-wekan-snap-to-edit-mongodb-database

> I want to change the webhook thing

Look at right menu Webhooks at https://github.com/wekan/wekan/wiki
