### ISSUE TITLE
Calendar View still broken on V7 or do i use it wrong?

### ISSUE THREAD

**Issue by incoggnito** [wekan/wekan#5111]
### Server Setup Information
* Did you test in newest Wekan?: yes, on 7.08.0
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Linux 5.15.108-1-pve
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Ngnix
* Node.js Version: 14.21.4
* MongoDB Version: 5.0.20
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Brave

### Problem description
The calendar view is empty now cards are shown. But i can create cards from there.

#### Reproduction Steps
None

#### Logs
No specific errors

**Comment by xet7** [comment]
@incoggnito 

At card, did you set both start and end time?

**Comment by incoggnito** [comment]
Yes, I've set all combinations.

**Comment by xet7** [comment]
@incoggnito 

Are dates visible at calendar when using Firefox, Chromium, Chrome, MS Chromium Edge or Safari?

**Comment by xet7** [comment]
I think newest fixes to calendar are not released yet. I'll think when to make new release. Maybe I need to make some more testing and more fixes before new release.

**Comment by incoggnito** [comment]
Yes, i've set it. On another server it seems to work a with some bugs on  reloading the page or on the week view.

**Comment by xet7** [comment]
@helioguardabaxo 

There are bugs in Due Date, at not yet released changes, at master branch: #5114
