### ISSUE TITLE
Files for discord webhook

### ISSUE THREAD

**Issue by Fedox-die-Ente** [wekan/wekan#5115]
Hey, i installed wekan over snap, where is the file with the messages from the discord webhook? I want to replace them in a other language but i dont find them..

**Comment by xet7** [comment]
@Fedox-die-Ente 

Depends, did you install Candidate, with your wekan server IP address.

```
sudo snap install wekan --channel=latest/candidate

sudo snap set wekan root-url='http://192.168.0.100'

sudo snap set wekan port='80'
```

https://github.com/wekan/wekan/wiki/Customize-Translations

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Outgoing-Webhook-to-Discord
