### ISSUE TITLE
Comment function is not showing at 100% zoom, but on 50% zoom

### ISSUE THREAD

**Issue by Dexus** [wekan/wekan#5118]
### Server Setup Information

* Did you test in newest Wekan?: 7.0.9
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker/openshift
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

### Problem description

When opening an item, it cannot be displayed fully.
This is the case for minimized view of item as well as for maximized view of item.
In both cases the comment section of the item will not be displayed when browser zoom is set to 100%.
Current workaround is to reduce zoom (sometimes to 50%) to be able to enter and submit comments - but the the resolution i.e. on a 14" notebook is so small that you cannot not see what you are typing.

Issues appears with Microsoft Edge and Google Chrome browser.

**Comment by Dexus** [comment]
Sure 7.0.9 sorry, I'll edit it.

**Comment by xet7** [comment]
@Dexus 

What screen resolution you have?

Does it help if you maximize card?

**Comment by xet7** [comment]
@mfilser 

It looks like, that with current master head, when card is open, card or page does not scroll down with mouse scroll anymore. Only with card maximized it is possible to view card comments. What do you think?

**Comment by mfilser** [comment]
@xet7 
I think this issue could be related to #5012

I can scroll the card up/down with the mouse scroll.
