### ISSUE TITLE
LDAP [ERROR] TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Danny-Graf** [wekan/wekan#5121]
Hello,
after a successful connection to our LDAP I get the following error after binding the UserDN:

`[ERROR] TypeError: Cannot read property '0' of undefined`

```
[INFO] LDAP connected
[INFO] Binding UserDN "cn=xxx,ou=xxx,ou=xxx,ou=xxx,ou=xxx,ou=xxx,ou=xxx,dc=xxx,dc=xxx"
[ERROR] TypeError: Cannot read property '0' of undefined
[INFO] Idle
[INFO] Disconecting
[INFO] Closed
```

@xet7 do you have any hints for this? I use a Windows Server 2022 with MS Active Directory. The UserDN above is verified and should work.

Thank you and best regards

**Comment by xet7** [comment]
@Danny-Graf 

Add environment variable like:
```
export DEBUG=true
```
And try again, is there better error message. Alternatively, add some more debug logging to wekan/packages/wekan-ldap/server/ldap.js , what property is 0.

**Comment by Danny-Graf** [comment]
@xet7 

After I enabled and configured AD Simple Auth, the error disappeared.
