### ISSUE TITLE
/etc/timezone error

### ISSUE THREAD

**Issue by dabiao2008** [wekan/wekan#5123]
### Server Setup Information
CentOS 8.2.2004 x86_64(Py3.7.9)

### Problem description  
[root@iZ8vb7i28oglm67pf1amepZ wekan]# docker-compose up -d
 
**Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/timezone" to rootfs at "/etc/timezone": mount /etc/timezone:/etc/timezone (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type**

### Reason: 
/ect/timezone in CentOS 8.2 is a folder, not a file
### Solution: 
Rename the timezone folder to timezone2 and create an empty file named timezone

**Comment by xet7** [comment]
@dabiao2008

a) What kind of setting would work for timezone at CentOS 8 ? WeKan container is based on Ubuntu Docker image.

b) You can send PR to add comments about CentOS 8 specific behavious near timezone settings of docker-compose.yml at https://github.com/wekan/wekan

c) Would WeKan time work correctly if timezone is not mounted at all from host to guest?

d) Is there other solution that would work correctly at all distros?
