### ISSUE TITLE
Bug: Font-Awesome not visible at opened card dates

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5127]
@helioguardabaxo 

After adding newest Font Awesome,  those fa.sign-out etc are not visible at opened card dates at Ubuntu Firefox, like before text "Last Monday" etc, these should be same icon like above it, but it looks like some not working unicode character.

![date-bug](https://github.com/wekan/wekan/assets/15545/d96a562b-e864-4c53-a003-3e98d1c113f9)

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5128 . Thanks to @helioguardabaxo !

**Comment by mfilser** [comment]
@helioguardabaxo 
Thank you for updating the font-awesome package.

At the minicard there is the comment sign missing (fa-comment-o).
Can you check if it's in the updated package?

Thank you very much in advance

**Comment by mfilser** [comment]
`fa-clock-o` seems also to be missing

**Comment by mfilser** [comment]
`fa-calendar-o` too

Maybe all `-o` icons?

**Comment by helioguardabaxo** [comment]
Hi, @mfilser !
Thanks for report this bug.

**Comment by mfilser** [comment]
@helioguardabaxo
Thank you for looking at this.
I saw you changed to another icon. The `-o` Icons only had a small line of the icon, without `-o`, the icon is completly filled. Can you add the `-o` Icons and not change the icon?

Before:
![grafik](https://github.com/wekan/wekan/assets/13166201/e29d1ca8-3382-41f7-bfed-6568aa6ca77c)

After:
![grafik](https://github.com/wekan/wekan/assets/13166201/ccef31e5-2a36-40d2-899e-7f4bd983ff61)


Also the number in front of the comment icon is completly different now.

**Comment by mfilser** [comment]
@helioguardabaxo 
I think i got it. If it's ok i can send PR.

**Comment by helioguardabaxo** [comment]
@mfilser 
I checked on FontAwesome site about regular/solid icons:
https://fontawesome.com/search?q=paperclip&o=r

Some icons now are paid.

**Comment by helioguardabaxo** [comment]
Or not?

**Comment by helioguardabaxo** [comment]
> @helioguardabaxo I think i got it. If it's ok i can send PR.

Sure!
