### ISSUE TITLE
Card view gets cut off

### ISSUE THREAD

**Issue by Jaffex** [wekan/wekan#5130]
## Issue
Card views get cut off when the board takes up most of the screen.

### Server Setup Information
* Did you test in newest Wekan?: yes, Version 7.09
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Fedora 38
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker-compose
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none
* Node.js Version: via docker container of version 7.09
* MongoDB Version: 6
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox 117, Reproducible in Chromium 116.0.5845.96

### Problem description

When opening a card, if the card is at a position where the card content would not fit on the screen anymore, it is opened, but cut off and there is no way to scroll to it's contents.

Examples:
![grafik](https://github.com/wekan/wekan/assets/31133207/7c318b7d-8dfe-4ec5-8f32-d4c2cbff769d)
![grafik](https://github.com/wekan/wekan/assets/31133207/80646d16-64e7-4aae-a65b-0bf8a9250a0d)

In a small enough window, the card content does not get shown at all:
![Peek 2023-09-13 09-43](https://github.com/wekan/wekan/assets/31133207/465ab6f5-cd23-496f-b1bd-6fa39c8d6bc6)

#### Reproduction Steps

Create a board and artificially fill the used up space with swimlanes and lists or just go to a big board that has enough cards to fill the available space, then open a card at the right screen edge.

**Comment by dokime7** [comment]
Hi,
Same here.
Thanks

**Comment by xet7** [comment]
@VidVidex @mfilser 

Hmm. I think this was fixed previously, but now it is broken again. Any idea why?

**Comment by mfilser** [comment]
For me it's broken too.
I wanted to change to open the card always in the middle of the screen, but if i remember right you didn't want it @xet7

**Comment by xet7** [comment]
@mfilser 

If I remember correctly, this happened:

1. Originally card opened near card.
2. There was bug that bottom card opened so that it was not visible at screen
3. I fixed card to be at left of screen, because I did not get working fix to open card near card
4. @VidVidex fixed that card opened near card, and scrolled to visible area of card

From my point of view, card can open near card, if we figure out how to fix it.

Also, there is no scrollbars at card and board, when card is open.

**Comment by xet7** [comment]
Card could also open at middle. Point is, it would be nice card would open to be visible at screen.

**Comment by mfilser** [comment]
@xet7 
I can't actually test it because current master build is broken while building NodeJS

**Comment by mfilser** [comment]
@xet7 
Thank you, i will test if building now works and then have a look at this issue.
If everything works, i send PR.

**Comment by faburem** [comment]
any update on this? I'm happy to provide any input since this is actually quite annoying if you work with Wekan on a daily basis in some bigger projects with lots of cards.

**Comment by BabyFnord** [comment]
+1 here
With just five lists, that is already a real bugger on my laptop (1440 px horizontal res), not to mention tablet device … 💁🏻‍♂️
Thank you fixing this!

**Comment by bbyszio** [comment]
We need this fix too. We could'nt make any updates if this do not work.

**Comment by mfilser** [comment]
PR comes soon, i am currently testing it

**Comment by johnnytolengo** [comment]
I have the same issue on 7.09.0.
