### ISSUE TITLE
cant use card tempalte

### ISSUE THREAD

**Issue by celevra** [wekan/wekan#5131]
### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: ubuntu 22.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node.js Version: 
* MongoDB Version: 5
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? chrome

### Problem description
if i click on the plus in a list and then try to click tempalte the search windows is there for milliseconds and vanishes
so it is not possible to create a card based on a template.
There is no error in the browser console or somewhere else, i'm not sure how to debug this
i'm on the latest docker release, freshly installed

#### Logs

no errors in console, nginx error.log or docker log

**Comment by faburem** [comment]
I can confirm this issue. It seems like there is some subscription missing because it works fine if you open the template before doing the search for the card template.

**Comment by xet7** [comment]
@faburem 

Something from here?

https://github.com/wekan/wekan/tree/main/server/publications

**Comment by faburem** [comment]
I have created a hacky PR to make this work. It's definitely not ideal but it does not break anything else and makes the feature at least useable. Happy to get some feedback how to improve the code!

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5161 . Thanks to @faburem !

**Comment by faburem** [comment]
is this going to make it into the next Wekan release? I am asking because I don't see it mentioned in the [changelog](https://github.com/wekan/wekan/blob/main/CHANGELOG.md) for the upcoming release...

**Comment by xet7** [comment]
@faburem 

It seems I did forget to add it to ChangeLog, so I have added it now. Thanks!

It is possible to test current git head with this automatic Docker build, it already includes all changes:

https://github.com/wekan/wekan/blob/main/docker-compose.yml#L126

Before making new release, I'm making some more fixes, and waiting for some fix PR.
