### ISSUE TITLE
become slow after a week 

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#5140]
after using wekan about a week it becomes slow 
i have to restart snap wekan, then it is fast and amazing again
now i am thinking about a cron job to restart wekan once a day😂😎

ubuntu / 6GB ram / 6cpu core / 100G ssd
 
![image](https://github.com/wekan/wekan/assets/25129673/b5f206a9-cfdf-4433-95c2-6413615ec1c9)

**Comment by mohammadZahedian** [comment]
and sometime it wont load until restart wekan
@xet7

**Comment by xet7** [comment]
@mohammadZahedian 

Yes, that happens on my WeKan server too. I'm thinking how to fix this.

**Comment by xet7** [comment]
@mohammadZahedian 

I do not know does it make any sense of trying to fix this yet.

Because with WeKan v7.00 ReactiveCache changes, it did speed up WeKan, and make that "becoming slow" to be more rare, only happening once a week. Some years ago, I had similar problem with Golang based server, it did become unresponsive after one week. It would be easier to debug, if memory leaks, or memory usage growing, would happen more frequently, like after one day, so that it would be possible to see changes in profiler. But one week it much harder to debug.

Also, soon there will be upgrade to Meteor 3.0. That will add many additional fixes and speedups. It could be, that this "becoming slow" bug will just disappear sometime during upgrades. This kind of bug could be anywhere, like in Node.js itself, Meteor code, or WeKan code.

It would also be an option to make WeKan restart automatically daily, with some internal cron. I have not tried to implement it yet.

**Comment by xet7** [comment]
That bug could also be dependencies WeKan has. WeKan dependencies are updated very often. So if someone fixes some bug in some dependency, upgrades also bring that fix to WeKan.

Upgrading to Meteor 3.0 also upgrades to Node.js 18, that has many fixes that came after current Node.js 14. After that, Meteor will upgrade to Node.js 20 etc newest Node.js and other dependencies, being the leading realtime web framework.

**Comment by mohammadZahedian** [comment]
@xet7 
what should i log when it stuck in loading?

**Comment by xet7** [comment]
@mohammadZahedian 

You should have nightly cron that runs these commands in bash script

```
sudo snap stop wekan
sudo snap start wekan
```

**Comment by mohammadZahedian** [comment]
> @xet7 what should i log when it stuck in loading?

i mean,  how should i undrestand  why i stucked?
i there any log file?
which logs should i check?

**Comment by xet7** [comment]
@mohammadZahedian 

Logs usually are at /var/log/syslog

**Comment by mohammadZahedian** [comment]
are this log important?


`audit: type=1400 audit(1696844590.997:6133553): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/1048466/net/snmp" pid=1048466 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

`audit: type=1400 audit(1696844662.000:6134054): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/memory" pid=1048466 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

`audit: type=1400 audit(1696804573.000:5853574): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/cpu" pid=956950 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

my log is full of this lines

**Comment by mohammadZahedian** [comment]
my log is full of this logs:

```
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>
 apparmor="DENIED" operation="open" profile="snap.wekan.mong>

```

**Comment by mohammadZahedian** [comment]
my log is full of this logs:


```
kernel: [  675.696761] audit: type=1400 audit(1696848503.001:4156): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/5499/net/netstat" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  675.698218] audit: type=1400 audit(1696848503.001:4157): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/vmstat" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  675.698381] audit: type=1400 audit(1696848503.001:4158): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/cpu" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  675.698387] audit: type=1400 audit(1696848503.001:4159): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/memory" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  675.698390] audit: type=1400 audit(1696848503.001:4160): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/io" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
wekan.wekan[5070]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Mon GMT+0330 (Iran Standard Time)","time":{"$date":1696848503049},"level":"info"}
kernel: [  676.695923] audit: type=1400 audit(1696848503.997:4161): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/5499/net/netstat" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  676.696737] audit: type=1400 audit(1696848504.001:4162): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/vmstat" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  676.696746] audit: type=1400 audit(1696848504.001:4163): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/cpu" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  676.696751] audit: type=1400 audit(1696848504.001:4164): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/memory" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  676.696756] audit: type=1400 audit(1696848504.001:4165): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/proc/pressure/io" pid=5499 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
kernel: [  681.696571] kauditd_printk_skb: 20 callbacks suppressed

```


is this ok?

**Comment by xet7** [comment]
@mohammadZahedian 

> wekan.wekan[5070]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Mon GMT+0330 (Iran Standard Time)","time":{"$date":1696848503049},"level":"info"}

That is WeKan cron, deleting older notification messages, or syncing LDAP users.

> kernel: [  676.695923] audit: type=1400 audit(1696848503.997:4161): apparmor="DENIED"

That is MongoDB https://github.com/wekan/wekan/issues/4855

Those are normal messages. Not errors.

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian
> 
> Logs usually are at /var/log/syslog

i am checking this log every day, but found nothing important...
and stuck in loading happens every time...

**Comment by xet7** [comment]
@mohammadZahedian 

Please test did I disable apparmor denied messages in newest WeKan Snap Candidate correctly.

https://github.com/wekan/wekan/issues/4855#issuecomment-1820049235

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian
> 
> Please test did I disable apparmor denied messages in newest WeKan Snap Candidate correctly.
> 
> [#4855 (comment)](https://github.com/wekan/wekan/issues/4855#issuecomment-1820049235)

@xet7 
no, I still receive error

**Comment by xet7** [comment]
@mohammadZahedian 

Ok. I try to fix this.

**Comment by xet7** [comment]
Try this https://github.com/wekan/wekan/wiki/Cron
