### ISSUE TITLE
Upgrade to Meteor 3.0 alpha 18

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5142]
@StorytellerCZ  

Related to Meteor Alpha 15 https://github.com/meteor/meteor/pull/12359 ,
when I was writing WeKan Deep Dive you asked for, and there is also screenshot about how to update dependencies by adding Meteor version number:

- https://github.com/wekan/wekan/wiki/Deep-Dive-Into-WeKan 

I did now try upgrading to Meteor 3.0 alpha 15. Interestingly this time there was no error about increasing memory size. 

Instead, there was this list of dependencies to upgrade.

I have not yet tried to fix all warnings that are visible with these CLI options:
```
WARN_WHEN_USING_OLD_API=true NODE_OPTIONS="--trace-warnings"
```
That is one option at my dev build script:
https://github.com/wekan/wekan/blob/master/rebuild-wekan.sh#L134

I'm thinking about:
- how to upgrade these dependencies
- if there are some Async Await changes needed, how to do them?

Sure, upgrading to Meteor 3.0 could be a lot of changes, but also changing to any other tech could also be a lot of changes, like when I tried some small prototypes here:

- https://github.com/wekan/wekan/wiki/WeKan-Multiverse-Roadmap

Maybe @filipenevola also has thoughts about this.

## Upgrading to Meteor 3.0 alpha 15

Tried at M1 Air, using macOS Sonoma beta 14.0, using Node.js 14.21.3: 

https://gist.github.com/xet7/0028ce353f372f5c23a1fc26e4510b4e

**Comment by StorytellerCZ** [comment]
The first step is to fix the any issues that come out of `WARN_WHEN_USING_OLD_API=true`. The problem with this is that it will highlight some internal Meteor APIs and packages. If you have a list of packages that are causing problems list them and tag me and I will try to fix as many as possible.

**Comment by xet7** [comment]
@StorytellerCZ 

Cool ! Thanks !

**Comment by xet7** [comment]
Node.js 14.21.3 and 14.21.4 does Segmentation fault at s390x Ubuntu 23.04. I need up upgrade to Node.js 18.x  or newer.
```
linux1@wekanubu2304:~$ sudo -E n 14.21.4
     copying : node/14.21.4
   installed : v14.21.4 (with npm 6.14.17)
linux1@wekanubu2304:~$ node -v
v14.21.4
linux1@wekanubu2304:~$ ./start-wekan.sh 
./start-wekan.sh: line 555:  1785 Segmentation fault      (core dumped) bash -c "ulimit -s 65500; exec node main.js"
```

**Comment by xet7** [comment]
@StorytellerCZ

I'm currently migrating to Meteor 3.0 at this branch:

https://github.com/wekan/wekan/tree/feature-meteor3

I used this migration guide:

https://forums.meteor.com/t/announcing-how-to-migrate-your-application-to-async-methods-and-be-ready-to-3-0-guide/60698

1. Migrated server code:
```
git clone https://github.com/minhna/meteor-async-migration.git

cd meteor-async-migration
```
2. Then I did these kinds of commands, to upgrade code at server, models, config, with those steps mentioned at meteor-async-migration repo:
```
DEBUG="transform:print*" jscodeshift -t transform.ts /home/user/repos/wekan/server --parser=tsx
```
3. For packages/sandstorm, I removed extra await where was some error it is not inside async

4. Because directly upgrading had some errors about memory:

```
meteor update --release 3.0-alpha.15
```
5. I instead went other way around, by creating empty Meteor project, and copying changes from .meteor/release, .meteor/packages, .meteor/versions

```
meteor create --release 3.0-alpha.15 met

cd met

meteor npm install

meteor
```
6. For most forked packages at wekan/packages/ , I removed requirement for specific versions of packages, like api.versionsFrom , and any version numbers from other packages ( https://github.com/wekan/wekan/wiki/Deep-Dive-Into-WeKan ).

Forking Atmospherejs.com package is in general like this:
```
cd packages

git clone https://github.com/some/packagename.git

cd packagename

rm -rf .git

nano package.js
```
And there changing package name like `somecoder:somepackage` to name like `wekan-autofocus`, and then adding it:
```
cd ..

meteor add wekan-autofocus
```
For npm packages, I publish forked packages to to npmjs.com https://www.npmjs.com/search?q=%40wekanteam

8. But for this case, I hade to add version number:
```
api.use('oauth@~3.0.0-alpha300.15', ['client', 'server']);
```
9. For any forked packages at wekan/packages, I added them when they did not cause some errors immediately after adding them, like this:
```
meteor add wekan-autofocus
```
10. For npm packages, I added some same that were previously at package.json:
```
npm install markdown-it
```
11. jquery version I forced to upgrade similar like previously:
```
meteor add jquery@3.0.0!
```
12. Because there was some errors at `meteor add percolate:synced-cron`, I instead added `meteor add ostrio:cron-jobs` that did not show errors. But I have not yet made changes to https://github.com/wekan/wekan/blob/feature-meteor3/packages/wekan-ldap/server/sync.js so that it would sync LDAP users with that `ostrio:cron-jobs`, that code is still commented out, so that I was able to add wekan-ldap package.
13. Adding wekan-accounts-oidc package does not work yet, it can not register oidc for some reason.
14. I had to add some additional imports to some files, because running meteor command did show, like importing more from reactive cache https://github.com/wekan/wekan/blob/feature-meteor3/imports/reactiveCache.js#L2-L5
15. simpl-schema npm package does not work yet, it seems Meteor 3.0 async changes have not been merged yet https://github.com/Meteor-Community-Packages/meteor-collection2/pull/443

```
=> Modified -- restarting.
I20231016-16:39:13.414(-4)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
W20231016-16:39:14.686(-4)? (STDERR) packages/core-runtime.js:205
W20231016-16:39:14.686(-4)? (STDERR)             throw error;
W20231016-16:39:14.686(-4)? (STDERR)             ^
W20231016-16:39:14.686(-4)? (STDERR) 
W20231016-16:39:14.686(-4)? (STDERR) Error: Invalid definition for modifiedAt field: "denyUpdate" is not a supported property
W20231016-16:39:14.686(-4)? (STDERR)     at /home/user/repos/wekan/node_modules/simpl-schema/dist/SimpleSchema.js:1182:13
W20231016-16:39:14.686(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20231016-16:39:14.686(-4)? (STDERR)     at checkAndScrubDefinition (/home/user/repos/wekan/node_modules/simpl-schema/dist/SimpleSchema.js:1180:27)
W20231016-16:39:14.686(-4)? (STDERR)     at /home/user/repos/wekan/node_modules/simpl-schema/dist/SimpleSchema.js:627:9
W20231016-16:39:14.686(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20231016-16:39:14.686(-4)? (STDERR)     at SimpleSchema.extend (/home/user/repos/wekan/node_modules/simpl-schema/dist/SimpleSchema.js:608:18)
W20231016-16:39:14.687(-4)? (STDERR)     at new SimpleSchema (/home/user/repos/wekan/node_modules/simpl-schema/dist/SimpleSchema.js:116:10)
W20231016-16:39:14.687(-4)? (STDERR)     at module.wrapAsync.self (models/translation.js:8:3)
W20231016-16:39:14.687(-4)? (STDERR)     at Module.wrapAsync (/home/user/.meteor/packages/modules/.0.19.1-alpha300.15.12wtcr3.p77gi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20231016-16:39:14.687(-4)? (STDERR)     at module (/home/user/repos/wekan/.meteor/local/build/programs/server/app/app.js:17509:9)
W20231016-16:39:14.687(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20231016-16:39:14.687(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20231016-16:39:14.687(-4)? (STDERR)     at Module.mod.require (/home/user/.meteor/packages/modules/.0.19.1-alpha300.15.12wtcr3.p77gi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20231016-16:39:14.687(-4)? (STDERR)     at Module.moduleLink [as link] (/home/user/.meteor/packages/modules/.0.19.1-alpha300.15.12wtcr3.p77gi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:104:22)
W20231016-16:39:14.687(-4)? (STDERR)     at module.wrapAsync.self (imports/i18n/tap.js:1:304)
W20231016-16:39:14.687(-4)? (STDERR)     at Module.wrapAsync (/home/user/.meteor/packages/modules/.0.19.1-alpha300.15.12wtcr3.p77gi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20231016-16:39:14.687(-4)? (STDERR)     at module (/home/user/repos/wekan/.meteor/local/build/programs/server/app/app.js:28898:9)
W20231016-16:39:14.688(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20231016-16:39:14.688(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20231016-16:39:14.688(-4)? (STDERR)     at Module.mod.require (/home/user/.meteor/packages/modules/.0.19.1-alpha300.15.12wtcr3.p77gi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20231016-16:39:14.688(-4)? (STDERR)     at Module.moduleLink [as link] (/home/user/.meteor/packages/modules/.0.19.1-alpha300.15.12wtcr3.p77gi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:104:22)
W20231016-16:39:14.688(-4)? (STDERR)     at module.wrapAsync.self (imports/i18n/index.js:1:57)
W20231016-16:39:14.688(-4)? (STDERR) 
W20231016-16:39:14.688(-4)? (STDERR) Node.js v18.16.0
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by xet7** [comment]
I added comment about current progress here:

https://forums.meteor.com/t/announcing-how-to-migrate-your-application-to-async-methods-and-be-ready-to-3-0-guide/60698/5?u=xet7

**Comment by xet7** [comment]
@StorytellerCZ 

What Meteor package has helpers?

```
W20231020-21:50:54.838(3)? (STDERR) TypeError: Users.helpers is not a function
W20231020-21:50:54.838(3)? (STDERR)     at module.wrapAsync.self (models/users.js:708:7)
W20231020-21:50:54.839(3)? (STDERR)     at Module.wrapAsync (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20231020-21:50:54.839(3)? (STDERR)     at module (/home/wekan/repos/wekan/.meteor/local/build/programs/server/app/app.js:18827:9)
W20231020-21:50:54.839(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20231020-21:50:54.839(3)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20231020-21:50:54.840(3)? (STDERR)     at Module.mod.require (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20231020-21:50:54.840(3)? (STDERR)     at Module.moduleLink [as link] (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:104:22)
W20231020-21:50:54.841(3)? (STDERR)     at module.wrapAsync.self (models/server/metrics.js:1:82)
W20231020-21:50:54.841(3)? (STDERR)     at Module.wrapAsync (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20231020-21:50:54.842(3)? (STDERR)     at module (/home/wekan/repos/wekan/.meteor/local/build/programs/server/app/app.js:2694:9)
W20231020-21:50:54.842(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20231020-21:50:54.842(3)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20231020-21:50:54.842(3)? (STDERR)     at Module.mod.require (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20231020-21:50:54.843(3)? (STDERR)     at Object.require (packages/modules-runtime.js:257:21)
W20231020-21:50:54.843(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:183:26)
W20231020-21:50:54.843(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-21:50:54.844(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-21:50:54.844(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-21:50:54.844(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-21:50:54.844(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-21:50:54.845(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-21:50:54.845(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-21:50:54.845(3)? (STDERR) 
W20231020-21:50:54.846(3)? (STDERR) Node.js v18.16.0
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by xet7** [comment]
@StorytellerCZ 

Nevermind, I added `dburles:collection-helpers`

Continuing to upgrade dependencies to Meteor 3.0.

**Comment by mfilser** [comment]
@xet7
I am not mentioned, but think I can help too:
https://github.com/dburles/meteor-collection-helpers

**Comment by xet7** [comment]
@mfilser 

Currently I'm getting these errors, running at:
- wekan repo branch remotes/origin/feature-meteor3
- Using Node.js 18.x
- merged linux arm meteor/meteor branch remotes/origin/feature-linux-arm for branch origin/release-3.0 to ~/.meteor
- Meteor 3.0 alpha 15 as Asahi Fedora arm64 at M1 Air with this linux  https://github.com/meteor/meteor/pull/12160 where I did ./scripts/generate-dev-bundle.sh , running from meteor checkout
- LD_LIBRARY_PATH with these files for arm64 https://wekan.github.io/LD_LIBRARY-linux-arm64.zip
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wekan/lib
```
Although you don't need that arm64 stuff when running on amd64.

Currently I'm getting these errors:
```
I20231020-22:43:07.536(3)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
W20231020-22:43:08.292(3)? (STDERR) packages/core-runtime.js:205
W20231020-22:43:08.292(3)? (STDERR)             throw error;
W20231020-22:43:08.292(3)? (STDERR)             ^
W20231020-22:43:08.292(3)? (STDERR) 
W20231020-22:43:08.292(3)? (STDERR) TypeError: Cannot read properties of undefined (reading 'update')
W20231020-22:43:08.292(3)? (STDERR)     at module.wrapAsync.self (models/users.js:1923:15)
W20231020-22:43:08.292(3)? (STDERR)     at Module.wrapAsync (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20231020-22:43:08.292(3)? (STDERR)     at module (/home/wekan/repos/wekan/.meteor/local/build/programs/server/app/app.js:18843:9)
W20231020-22:43:08.292(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20231020-22:43:08.292(3)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20231020-22:43:08.292(3)? (STDERR)     at Module.mod.require (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20231020-22:43:08.292(3)? (STDERR)     at Module.moduleLink [as link] (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:104:22)
W20231020-22:43:08.292(3)? (STDERR)     at module.wrapAsync.self (models/server/metrics.js:1:82)
W20231020-22:43:08.292(3)? (STDERR)     at Module.wrapAsync (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20231020-22:43:08.292(3)? (STDERR)     at module (/home/wekan/repos/wekan/.meteor/local/build/programs/server/app/app.js:2710:9)
W20231020-22:43:08.292(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20231020-22:43:08.292(3)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20231020-22:43:08.292(3)? (STDERR)     at Module.mod.require (/home/wekan/repos/wekan/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20231020-22:43:08.293(3)? (STDERR)     at Object.require (packages/modules-runtime.js:257:21)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:183:26)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-22:43:08.293(3)? (STDERR)     at evaluateNextModule (packages/core-runtime.js:218:7)
W20231020-22:43:08.293(3)? (STDERR) 
W20231020-22:43:08.293(3)? (STDERR) Node.js v18.16.0
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by xet7** [comment]
All those changes are at this branch https://github.com/wekan/wekan/commits/feature-meteor3

**Comment by xet7** [comment]
To get those dependencies running, I have forked more packages to:
https://github.com/wekan/wekan/tree/feature-meteor3/packages

Mainly because they require some specific version of dependencies. When I sometime get WeKan actually running, I maybe try to move those dependencies to Meteor community packages of PRs to upstream packages.

**Comment by xet7** [comment]
WeKan and some my other posts at Meteor forums was mentioned at todays live podcast:

https://www.youtube.com/watch?v=Otf_jslXFBU

**Comment by xet7** [comment]
I pushed my current Meteor 3.0 alpha 15 fork with Linux arm64 changes to here, as main branch, so that I can use it later:

https://github.com/wekan/meteor

**Comment by mfilser** [comment]
@xet7
Unfortunately at can't help to upgrade to Meteor 3.0

**Comment by xet7** [comment]
I added issue to https://github.com/Meteor-Community-Packages/meteor-collection-hooks/issues/304 about this core dump I'm getting when running Meteor at M1 Air Asahi Fedora arm64 with Meteor linux-arm branch merged:
```
} Track: METEOR;
        Version: 3.0-alpha.15
node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
Aborted (created core dump file)
```
I'm trying to add this package, because probably it includes code to make this error fixed:
https://github.com/wekan/wekan/issues/5142#issuecomment-1773317180

**Comment by xet7** [comment]
I pause upgrading to Meteor 3.0, because I don't know yet how to fix that newest error above. Previous errors I did fix.

Instead, I'm going back to main branch, and preparing for release of newest WeKan with Meteor 2.x, Node.js 14.x and MongoDB 6.x, adding additional fixes, trying to upgrade all platforms.

**Comment by xet7** [comment]
I upgraded to Meteor 3.0 alpha 16 at that upgrade branch. Now, when building, I get this error:

```
node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
./rebuild-wekan.sh: line 22:  8656 Aborted                 meteor build .build --directory --platforms=web.browser
./rebuild-wekan.sh: line 103: cd: .build/bundle/programs/server: No such file or directory
./rebuild-wekan.sh: line 105: cd: .build/bundle/programs/server/npm/node_modules/meteor/accounts-password: No such file or directory
./rebuild-wekan.sh: line 107: cd: .build/bundle: No such file or directory
```

**Comment by xet7** [comment]
@Grubba27

Do you know what the above coroutine.cc error means?

**Comment by Grubba27** [comment]
We do https://github.com/meteor/meteor/blob/008c52df58bc0d2e3f0f1716d968a62482c135b4/scripts/build-dev-bundle-common.sh#L8

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/5226
