### ISSUE TITLE
Users can't change their password since V7.02 (docker)

### ISSUE THREAD

**Issue by kschimpanski** [wekan/wekan#5144]
### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Ubuntu Server / Docker
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): None
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.10
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Edge, Brave

### Problem description
Since Version 7.02 users cannot change their password anymore. When clicking on "Change Password" there is no form to enter the new password:
![image](https://github.com/wekan/wekan/assets/117566832/e3b0161b-3e03-4601-b7ca-be6717e3cad0)

#### Reproduction Steps

Can be reproduced by deploying a clean (docker-)installation (https://github.com/wekan/wekan/blob/main/docker-compose.yml):
V7.01 is the last version in which users are able to change the password.

Best regards

**Comment by mfilser** [comment]
I had a look at this. The bug came with PR #5032

@nebulade 
Was this by your intention?

**Comment by nebulade** [comment]
No, this was not my intention. I can reproduce it here. Seems like a side-effect of my previous change, will see how to fix it. Sorry for that.

**Comment by mfilser** [comment]
No problem, thank you for your feedback
