### ISSUE TITLE
Mirror all of WeKan from GitHub to elsewhere

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5145]
Problem:
- GitHub has many rate limits, like importing issues to Gitea is slow. Fossil SCM clone/sync is faster and includes issues.
- GitHub issues and GitHub wiki can not be viewed in iframe, like at [Friend Desktop](https://github.com/wekan/wekan/wiki/Friend) / WeKan app menu option Docs, because GitHub has browser policy framing disallow.
- At some countries, using GitHub is denied

Solution: I will create mirrors all of WeKan GitHub to some of these:

- [x] Gitea: Import, without releases, did work. But importing issues, wiki etc did work only, when I did not make it a mirror. I don't know how to import changes that came after that import to Gitea.
- [x] Git-Bug https://github.com/MichaelMure/git-bug , importing issues did work, and can also later add only newest changes, no need to re-download all.
- [ ] Fossil SCM
- [ ] GitLab: Trying to import shows errors listing names GitHub repos
- [ ] Make mirrors public

**Comment by C0rn3j** [comment]
I believe this project would be eligible for GitLab Ultimate, should you decide you need the features - https://about.gitlab.com/blog/2022/02/04/ultimate-perks-for-open-source-projects/

**Comment by xet7** [comment]
@C0rn3j 

I think I already have GitLab for FOSS. https://gitlab.com/help shows version to be:

GitLab Enterprise Edition 16.5.0-pre [f13dfe5059d](https://gitlab.com/gitlab-org/gitlab/-/commits/f13dfe5059d)

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
