### ISSUE TITLE
v7.10 missing profile pictures

### ISSUE THREAD

**Issue by kovacs-andras** [wekan/wekan#5147]
* Deployment Method: Docker
* What webbrowser version are you using: Google Chrome 117.0.5938.132, FireFox 102.15.1esr

### Problem description
Dear Team,

With the latest, v7.10 relase some of the custom .jpg and .png profile pictures can't load.
I see one user's profile picture which can load and located at `/cdn/storage/avatars/...`
But all the others can't which are trying to load from `/cfs/files/avatars/...`
Reverting to v7.09 fixed the issue.

#### Logs
I don't see any relevant logs neither on the server or in the browser.

![Screenshot from 2023-09-29 11-09-06](https://github.com/wekan/wekan/assets/51884166/037b679b-7d79-4c07-aa26-8c65c413520e)

**Comment by xet7** [comment]
@kovacs-andras 

Thanks for testing! There is one month since previous WeKan release, so very likely there is some stuff to fix.

**Comment by xet7** [comment]
I try to fix this, and release new version of WeKan, before updating other platforms.

**Comment by kovacs-andras** [comment]
Thanks for the quick response!
This project is great!

**Comment by xet7** [comment]
@kovacs-andras 

Please test WeKan v7.15 , did I fix this correctly?

**Comment by xet7** [comment]
Hmm, I mean v7.16, or newer available.

**Comment by kovacs-andras** [comment]
On v7.17 the pictures from /cfs are not loading for me, but deleting/re-uploading the profile pictures fixed it (now they are loading from /cdn). And the page load even with many cards became super fast so huge thanks for everything!!!

**Comment by mfilser** [comment]
@kovacs-andras
Thank you very much for your kind words, your the first one who appreciate my hard work on coding the speedup improvements, mostly of them came in 7.00 (#5000) 🥳
