### ISSUE TITLE
Cards are not in the board but found in board search!!!!!

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#5154]
i was working via api ( get_swimlane_cards )
i founded many cards that are not in the board
first i thought they are archived card, but they werent

also they can be found in by search in board ( not in global search! )
in search result when you click on it nothing happends

**Comment by mohammadZahedian** [comment]
they are my old card, but they are not my board or archive now

**Comment by mohammadZahedian** [comment]
i imported this board from trello two years ago

they could be archived card that were archived in trello
or corrupted card in import

how can i find and remove theme?

**Comment by mohammadZahedian** [comment]
@xet7 i exported board json, they can be found there too:
![Screenshot 2023-10-05 191145](https://github.com/wekan/wekan/assets/25129673/f5008ef1-62e9-4a56-bcda-cd2cc2609416)

**Comment by DimDz** [comment]
> i imported this board from trello two years ago
> 
> they could be archived card that were archived in trello or corrupted card in import
> 
> how can i find and remove them?

To remove them you can use the delete_card operation from the API. You will need the boardId, the listId and cardId and then POST a request to /api/boards/:boardId/lists/:listId/cards/:cardId

**Comment by xet7** [comment]
@mohammadZahedian 

> i founded many cards that are not in the board

Are you using some Filter? That only shows cards selected in filters, not all cards.

Or, are those cards at SwimlaneId or ListId that does not exist ? Change cards to have existing SwimlaneId or ListId.

**Comment by xet7** [comment]
Change cards to have existing SwimlaneId or ListId makes them visible at board.

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian
> 
> > i founded many cards that are not in the board
> 
> Are you using some Filter? That only shows cards selected in filters, not all cards.
> 
> Or, are those cards at SwimlaneId or ListId that does not exist ? Change cards to have existing SwimlaneId or ListId.

No filter
no the list id and swimlane id doesnt exist

how should i change id?

and why this have happend? there is about 500 hidden card that makes board slow

**Comment by xet7** [comment]
@mohammadZahedian 

Copy your swimlanes to new board.

Then new board does not have those old cards, and new board will work faster.

**Comment by mohammadZahedian** [comment]
> Copy your swimlanes to new board.

done, but labels are missing

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
