### ISSUE TITLE
v7.10/v7.11 break LDAP login

### ISSUE THREAD

**Issue by BlobbyBob** [wekan/wekan#5156]
LDAP login works for us in v7.09, but breaks in v7.10 and v7.11

## Server Setup Information
* Operating System: Debian
* Deployment Method: Docker
* Http frontend: Traefik
* Node.js Version: (bundled in Docker image)
* MongoDB Version: 4.4

## Reproduction Steps
Log in with username and password for a valid LDAP user.

### v7.11 (not working):
```
wekan-app  | [INFO] Init LDAP login "REDACTED"
wekan-app  | {"line":"93","file":"ldap.js","message":"Init setup","time":{"$date":1696583075397},"level":"info"}
wekan-app  | [ERROR] ReferenceError: Bunyan is not defined
```
### v7.09 (working):
```
wekan-app  | [INFO] Init LDAP login "REDACTED"
wekan-app  | [WARN] Lookup for unset variable: INTERNAL_LOG_LEVEL 
wekan-app  | [WARN] Lookup for unset variable: LDAP_USER_ATTRIBUTES 
wekan-app  | [INFO] Init setup 
wekan-app  | [INFO] Connecting "ldaps://REDACTED"
wekan-app  | [DEBUG] connectionOptions{
wekan-app  |   url: 'ldaps://REDACTED',
wekan-app  |   timeout: 10000,
wekan-app  |   connectTimeout: 10000,
wekan-app  |   idleTimeout: 10000,
wekan-app  |   reconnect: true,
wekan-app  |   log: Logger {
wekan-app  |     _events: [Object: null prototype] {},
wekan-app  |     _eventsCount: 0,
wekan-app  |     _maxListeners: undefined,
wekan-app  |     _level: 30,
wekan-app  |     streams: [ [Object] ],
wekan-app  |     serializers: null,
wekan-app  |     src: false,
wekan-app  |     fields: {
wekan-app  |       name: 'ldapjs',
wekan-app  |       component: 'client',
wekan-app  |       hostname: 'a5ee1cf7a851',
wekan-app  |       pid: 1
wekan-app  |     },
wekan-app  |     [Symbol(kCapture)]: false
wekan-app  |   },
wekan-app  |   tlsOptions: { rejectUnauthorized: true }
wekan-app  | } 
wekan-app  | [INFO] LDAP connected 
wekan-app  | [INFO] Binding UserDN "REDACTED"
wekan-app  | [INFO] Searching user "REDACTED"
wekan-app  | [DEBUG] searchOptions {
wekan-app  |   "filter": "REDACTED",
wekan-app  |   "scope": "sub",
wekan-app  |   "sizeLimit": 0
wekan-app  | }
wekan-app  | [DEBUG] BaseDN "REDACTED"
wekan-app  | [INFO] Search result count 1
wekan-app  | [INFO] Authenticating "REDACTED"
wekan-app  | [INFO] Authenticated "REDACTED"
wekan-app  | [DEBUG] Identifying user with: REDACTED 
wekan-app  | [INFO] Querying user 
wekan-app  | [DEBUG] userQuery {
wekan-app  |   "services.ldap.id": "REDACTED"
wekan-app  | }
wekan-app  | [INFO] Logging user 
wekan-app  | [INFO] Syncing user data 
wekan-app  | [DEBUG] user {
wekan-app  |   "_id": "REDACTED"
wekan-app  | }
wekan-app  | [DEBUG] fullname= "REDACTED"
wekan-app  | [INFO] Syncing user fullname: "REDACTED"
wekan-app  | [DEBUG] email= "REDACTED"
wekan-app  | [INFO] Syncing user email: "REDACTED"
wekan-app  | [INFO] Idle 
wekan-app  | [INFO] Disconecting 
wekan-app  | [INFO] Closed
```

**Comment by faburem** [comment]
I think the reason is that the bunyan logger is still referenced here, but the dependency has been removed in the latest wekan versions: https://github.com/wekan/wekan/blob/a76067abfad3120a88f909d70a6314507265a5ff/packages/wekan-ldap/server/ldap.js#L106

**Comment by xet7** [comment]
@faburem 

At WeKan v7.10 bugfixes https://github.com/wekan/wekan/blob/a76067abfad3120a88f909d70a6314507265a5ff/CHANGELOG.md#v710-2023-09-29-wekan--release

"Replaced ldap logger https://www.npmjs.com/package/bunyan with https://docs.meteor.com/packages/logging.html, because bunyan did show dtrace errors when building WeKan. [Part 1](https://github.com/wekan/wekan/commit/e83945c1a6c08fe58f660bcd7b7f8494f629e913), [Part 2](https://github.com/wekan/wekan/commit/427eb8ebd16b847eb278cd319adb75adc5206e99). Thanks to xet7."

Can you send PR to change to use that meteor logging package?

**Comment by faburem** [comment]
Done, PR is ready for review here:
https://github.com/wekan/wekan/pull/5159

**Comment by xet7** [comment]
Fixed at #5159 . Thanks to @faburem !

**Comment by xet7** [comment]
@faburem @BlobbyBob

Please test does this automatic build Docker image work now, with this fix:

https://github.com/wekan/wekan/blob/main/docker-compose.yml#L126

**Comment by faburem** [comment]
Yes I can confirm the LDAP login is working as expected with this Docker image 🕺
