### ISSUE TITLE
Bug: calendar view does not display events 

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#5162]
If I set a start date on a task, the task is not displayed at any of the views from calendar. I set a due date on another task. This event will be displayed, but only on monthly overview. Additionally, If I click on week, I get an empty page (see attachement). 
![WeKan_calendarView](https://github.com/wekan/wekan/assets/92315677/175ea19a-1ac2-4526-b4c1-43019672b71d)
![wekan_stand_121023](https://github.com/wekan/wekan/assets/92315677/d058f829-4a74-4531-b5ba-7889362d423c)

**Comment by xet7** [comment]
@Meeques 

Please upgrade to newest WeKan, and try is this bug now fixed. Thanks!

**Comment by Meeques** [comment]
seems like it works. Thanks!
