### ISSUE TITLE
snap failed

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#5170]
Hello,

 i can not reboot my ubunto machine with snap-gantt.
I got the following error: snap failed

thanks,

**Comment by xet7** [comment]
@MeriemBH 

What commands you used to install it ?

**Comment by MeriemBH** [comment]
sudo snap install wekan-gantt-gpl

**Comment by MeriemBH** [comment]
let's sum up:
i created two virtual machines:
-ubunto snap wekan gantt
-windows wekan offline

i did a clone for the first one to avoid issues.
Now, i lost the first machine when doing the backup: i am getting a kernel panic issue.
When trying to boot the cloned machine, i got the snap failed error

**Comment by xet7** [comment]
@MeriemBH 

That is old version.

Try this:

```
sudo snap stop wekan-gantt-gpl

sudo rm -rf /var/snap/wekan-gantt-gpl/common/*

sudo snap remove wekan-gantt-gpl

sudo snap install wekan --channel=latest/candidate

sudo snap set wekan root-url=http://IP-ADDRESS-HERE

sudo snap set wekan-port='80'
```
There change IP address to what you see with command `ip address` to be your wekan server ip address

You can check is wekan.wekan and wekan.mongodb running with command:
```
sudo snap services
```
And check logs with:
```
sudo snap logs wekan
```

**Comment by MeriemBH** [comment]
i can not even reboot the system.
[
![error](https://github.com/wekan/wekan/assets/36626790/63109776-4634-4911-a03d-c0bd5fa1ef4e)
](url)

**Comment by xet7** [comment]
@MeriemBH

Are you are running Ubuntu in VirtualBox in Windows?

Did you not get WeKan working directly in Windows with these updated info?

https://github.com/wekan/wekan/wiki/Offline

**Comment by xet7** [comment]
@MeriemBH 

It takes many GB of disk space to install Ubuntu.

It would be better that you would delete that Ubuntu, and install only WeKan this way:

https://github.com/wekan/wekan/wiki/Offline

**Comment by MeriemBH** [comment]
Lauri, do you suggest to install wekan on windows?
is it stable? i  thought that the ubunto version is better!!
another issue, we don't have windows22. our current system is windows8

**Comment by MeriemBH** [comment]
@xet7 
Our current system is windows 10.
I am afraid that wekan installation wil not work because the version in the documenation is for windows22.
If you can garantee that it will work for windows 10 and it is a stable version than i can do it.
thanks for your advice

**Comment by xet7** [comment]
@MeriemBH 

Yes, WeKan does work at windows 10 using this info:

https://github.com/wekan/wekan/wiki/Offline

**Comment by MeriemBH** [comment]
this link is for wekan.
Is there any documentation for wekan-gantt?

**Comment by xet7** [comment]
@MeriemBH 

Newest WeKan does not have that old mimimal Gantt feature:

https://github.com/wekan/wekan/issues/2870#issuecomment-1516992963

 New better Gantt feature will probably be added back to WeKan at next month.

**Comment by xet7** [comment]
Old minimal Gantt feature docs are at:

https://github.com/wekan/wekan/wiki/Gantt

**Comment by MeriemBH** [comment]
regarding the disk space issue, is there a way to create a notification to avoid it?

**Comment by xet7** [comment]
@MeriemBH 

First make sure there is enough disk space, deleting biggest files that you don't need, by finding biggest files with this app:

https://windirstat.net

For example, if you have some big `ubuntu.vdi` VirtualBox image, or `ubuntu.iso` install image, those do take a lot of disk space.

Installing to Windows directly takes less disk space, than installing Ubuntu.

If you install to ubuntu, you need to make hard disk image `ubuntu.vdi` growable size big enough.

For notification, how to check disk space in windows, and send notification, you could search Google or ask Bing AI or ChatGPT about that.
