### ISSUE TITLE
Broken card preview, when cards are minimized  

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#5175]
## Issue

When a card is opened in minimized mode, the comments can't be scrolled and the card can't be moved in a way to show all the details. Workaround: full screen card details works, but we then need to explain to all clients, that they need to switch to full-screen card view. 

### Server Setup Information

* Did you test in newest Wekan?: yes, WeKan ® Version | 7.10.0
* Operating System: Debian
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.11
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Safari and Chrome, MacOS

### Problem description
<img width="541" alt="Bildschirmfoto 2023-10-30 um 12 01 32" src="https://github.com/wekan/wekan/assets/1153741/55d000c3-8f2d-4d21-afa7-8657556d393f">

![Issue](https://github.com/wekan/wekan/assets/1153741/61dd7502-362c-4a81-81ec-460bf7734965)

#### Reproduction Steps

- Create some lists so that a card is close to the right border of the browser. 
- Open the card in minimize mode: can't scroll the full details. 
- Open another card from the left side and switch to full screen mode
- Then everything can be seen. 
- Switch back to minimize mode: can't scroll again.

**Comment by xet7** [comment]
Please wait, I will release fixed WeKan version this week.
