### ISSUE TITLE
Security issue: Hyperlink injection

### ISSUE THREAD

**Issue by mc-marcy** [wekan/wekan#5176]
## Issue
Hyperlink injection possible during self registration

### Server Setup Information
Wekan Version 7.09.0
Debian 12

### Problem description
When a user is putting an url in the username field during the self registration the confirmation link will forward you to this url

#### Reproduction Steps
go to self registration
put a domain in the username field
click the link in the received approval mail

**Comment by xet7** [comment]
@mc-marcy 

Thanks! I will fix this soon.

I hope that next time you will follow responsible disclosure, sending info by email, if possible with PGP:

https://github.com/wekan/wekan/blob/main/SECURITY.md

**Comment by mc-marcy** [comment]
oh i'm really sorry for that. we got it today via our bugbounty program and you can imagine, panic :)
but of course will follow it next time.
sorry
