### ISSUE TITLE
It's impossible to edit comments since the disappearance of the rich text editor.

### ISSUE THREAD

**Issue by Maskoot** [wekan/wekan#5178]
It's impossible to edit comments since the disappearance of the rich text editor.

## Issue

Following the removal of rich text editing for comments on a card, modifying these comments has become impossible. The text is buried within HTML tags.

Is there any tool being considered to replace the previous one ?

### Server Setup Information

Install : Snap
Version : 7.09

**Comment by xet7** [comment]
I will release WeKan v7.10 today. It has `M` Convert to markdown button at edit area of Card Description and Card Comment.

**Comment by xet7** [comment]
Correction: WeKan v7.11.
