### ISSUE TITLE
Installing Wekan via Snap

### ISSUE THREAD

**Issue by Danny-Graf** [wekan/wekan#5180]
Hello,

after I try to install Wekan via snap, I receive the following error:

error: cannot install "wekan": Post https://api.snapcraft.io/v2/snaps/refresh: x509: certificate
       signed by unknown authority

Could you please help me with the issue?

Best regards
Danny

**Comment by xet7** [comment]
@Danny-Graf 

Did you install Candidate?

```
sudo snap install wekan --channel=latest/candidate

sudo snap set wekan root-url='http://IP-ADDRESS-HERE'

sudo snap set wekan port='80'
```

**Comment by Danny-Graf** [comment]
@xet7 

The error still exists

sudo snap install wekan --channel=latest/candidate
error: cannot install "wekan": Post https://api.snapcraft.io/v2/snaps/refresh: x509: certificate
       signed by unknown authority

Best regards
Danny

**Comment by xet7** [comment]
@Danny-Graf 

What distro version are you using?
