### ISSUE TITLE
Notification spam via e-mail for removed labels. 

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#5185]
I have some boards, where I want to be notified about all changes, as there are customers working with us in this board. 
This morning someone removed the Twitter-label. This created about 130 e-mails, some of them containing 5-10 references like this one: 

[Boardname] Content Name Removed label __label__ from card "Content" at list "Publish" at swimlane Plan at board "Customer" https://link

We already got banned our IP from spamming to much once. Now I have the choice between turning off notifications for our customers and myself or accepting this. 

I know, notifications are really hard to get right. In this case, I think one e-mail would be really enough. Like "Notification X was removed from board Y". 

Thank you for Wekan and all the work that's already in there, hoping to further improve it.

**Comment by xet7** [comment]
Moved to #5171
