### ISSUE TITLE
List does not update when trying to load more cards

### ISSUE THREAD

**Issue by crmocz** [wekan/wekan#5186]
## Issue
* Issue DID NOT occur with v7.05 and mongo 6.0.8
* Issue occurs now after I upgraded to v7.12 and mongo 6.0.11
* **20 Cards per List load when the page loads, if I scroll down to the bottom of a List, I see the loading blue dots indefinitely.**
* If I press the Alt key on the Linux+Firefox machine, the next 20 items immediately appear as expected, but I haven't noticed a workaround yet on the Mac+Chrome machine.

### Server Setup Information
* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System:
** It is the same on 2 different machines.  One is Linux Mint (Vera 21.1) running Firefox (118.0.1), and the other is a Macbook (Ventura 13.6.1) running Chrome (119.0.6045.105).
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
** Docker (docker compose)
** image: ghcr.io/wekan/wekan:v7.12
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): N/A
* Node.js Version: 18.17.1
* MongoDB Version: 6.0.11
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
** It is the same on 2 different machines.  One is Linux Mint (Vera 21.1) running Firefox (118.0.1), and the other is a Macbook (Ventura 13.6.1) running Chrome (119.0.6045.105).

### Problem description
* See Issue section above

#### Reproduction Steps
* Load any board that has one or more Lists containing more than 20 Cards
* Scroll down to the bottom of the List to cause it to try to load more Cards

#### Logs
* No new events appear in Console or Network tabs when I scroll down to duplicate this issue

**Comment by xet7** [comment]
WeKan only works with Node.js 14.x, like 14.21.4 . Not with Node.js 18.x .

**Comment by crmocz** [comment]
Since I am running the Docker version with docker compose, my locally installed Node version should be irrelevant.  Node 14.x should be in the image, right?

**Comment by crmocz** [comment]
For additional context, this is how I performed my upgrade on both the Linux+Firefox and Mac+Chrome machines.  It was working on both before, and broken on both after.

1. Run scripts/wekan-backup.zsh to backup my data, just in case
2. Update scripts/wekan/wekan-docker-compose.yml with new image versions for mongo and wekan
3. Stop wekan in Docker Desktop
4. docker rm wekan-app
5. docker compose -f wekan-docker-compose.yml up -d

**Comment by xet7** [comment]
@crmocz 

Yes, newest docker-compose.yml from https://github.com/wekan/wekan uses correct versions anyway.

I'll try does this bug happen.

**Comment by xet7** [comment]
@crmocz 

Does it help, if at Swimlane ☰  menu, you set Swimlane Height to for example 500, 1000 or 2000 ? 

Because, I guess automatic height with setting `-1`could behave in strange ways, when there is more that one screenfull of cards.

@mfilser 

What do you think?

**Comment by DimDz** [comment]
I encountered this issue, when manually setting the Swimlane Height it is fixed. But for default Swimlane Height set as -1, the problem occurs. As stated, if a list has more than 20 cards, the swimlane is not automatically adjusted to the maximum of cards but instead it has an infinite loading icon on that list. Also, I want to add that manually setting the Swimlane Height, it's set only for that user and not for the others.

**Comment by xet7** [comment]
@DimDz 

>  Also, I want to add that manually setting the Swimlane Height, it's set only for that user and not for the others.

Yes, because other users may need to view more or less cards at once, for editing, presentation etc purposes.

**Comment by crmocz** [comment]
> Does it help, if at Swimlane ☰ menu, you set Swimlane Height to for example 500, 1000 or 2000 ?

Yes, manually setting Swimlane Height works well.

**Comment by mfilser** [comment]
I don't know this bug. I never set swimlane to a manual height. Also i am not sure if it's good to have this setting per user or for all users. It's more flexible for users of course, but maybe there are needs to have a global setting per board and to disallow to set it per user.

**Comment by xet7** [comment]
@mfilser 

In Firefox, when there is auto height and more cards that fits on one screen, there is spinner that does not load more cards and scrollbar does not come visible. Currently only workaround is to set fixed swimlane height.

I have not yet tested at other browsers.

**Comment by derbolle** [comment]
the behaviour (not loading additional elements when reaching the bottom of the lane) seems to be the same in chromium browsers. Manual swimlane height is an okay-ish workaround but maybe sane defaults or an admin toggle for default swimlane height would be nice.

also the scroll behaviour has changed if you compare it to earlier wekan versions. if a column had more elements than the swimlane could show in its height, the column had a scrollbar where you could scroll only in the specified column until it reached its end. now with infinite height you always scroll the whole page

**Comment by aiac** [comment]
We got the same issue after updating to 7.27.0.

Tested in newest Chrome, Firefox, Safari and Opera, so its not chromium based browsers issue.

Setting manual height worked, cards started to load, but this has to be done per every swim-lane / user.

**Comment by C0rn3j** [comment]
Docker 7.44 wekan and Chromium.

This happens when the Swimlane has a Board with Cards that span more than the current Swimlane height.

If it has LESS height, it gives it a scrollbar, and then it works fine.

The card refresh can be triggered by manually resizing the browser window.  
The moment the scrollbar is there, it loads the rest of the cards fine without having to constantly resize the window.

**Comment by Gomoryong** [comment]
Hello,
We have the same problem as you, is there a way to define the swimlane height for everyone, everywhere ? 
Thanks

**Comment by xet7** [comment]
@Gomoryong

I'm not sure, is [this new code](https://github.com/wekan/wekan/pull/5417) for this issue, but anyway, I'll try to make new realese, so that somebody can test.

**Comment by DimDz** [comment]
> @Gomoryong
> 
> I'm not sure, is [this new code](https://github.com/wekan/wekan/pull/5417) for this issue, but anyway, I'll try to make new realese, so that somebody can test.

it fixes it
