### ISSUE TITLE
Edit button for Card Description not clickable anymore

### ISSUE THREAD

**Issue by derbolle** [wekan/wekan#5187]
### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System:  Docker
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik (docker)
* Node.js Version: 14.21.4
* MongoDB Version: 5.0.13
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox

### Problem description

"Edit" in Description is not clickable anymore. You have to use a poorly visible button far to the right. Was possible until at least v7.09

![image](https://github.com/wekan/wekan/assets/53299502/67d04ae5-9b76-4205-826c-6137f23a1cab)

#### Reproduction Steps
Open Card. Try to click "Edit" in Description

**Comment by xet7** [comment]
@derbolle 

Oh, it seems I forgot to remove that Edit text, when I moved edit to the right pen icon, when coding In Progress feature of show checklist at minicard. I'll try to fix it.

**Comment by mfilser** [comment]
I also found this issue today. I found it very useful to click on the description and edit it right away. Now, i have to go to the edit button in the upper right corner to edit the text, very annoying, especially for long descriptions.

However, i found how to have the option to click on the description and the edit icon to edit the description, so i am glad to have my own deploying infrastructure / wekan instance.
By the way, there were already some other changes i didn't like and change it right away for my personal need :slightly_smiling_face:

**Comment by xet7** [comment]
@mfilser 

> By the way, there were already some other changes i didn't like and change it right away for my personal need 🙂

Would those changes be useful to others too?
You can send your changes to WeKan as PRs.

**Comment by mfilser** [comment]
@xet7 
I send every useful feature to other users as PR.
There aren't much i have for my own. One is now the description editing above, and one other thing are the rounded cards i don't like. There are some other ones i can't say at the moment, but they are only things i changed back after a  commit i didn't like for my personal feeling.

**Comment by xet7** [comment]
@mfilser 

> I send every useful feature to other users as PR.

Thanks!

Yes, those other changes are what other WeKan users have requested and are mostly happy with using, they will stay like they currently are in WeKan.

**Comment by xet7** [comment]
Currently edit button icon is at right, in next WeKan release, because at left it would disturb reading description text, that starts at left. Edit button icon is similar like what is already at top toolbar, with tooltip that has text `Edit`. Clicking some non-edit text does not necessarily start edit mode everywhere in WeKan, or I have not checked.

Any menus will change as needed, to be at most logical place, when I add more features to Wekan. Or alternatively, if someone suggest some better UI layout.
