### ISSUE TITLE
Suggestion: fixed list which creates a new duplicate card when dragged

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#519]
for some boards where tasks are fixed and will need to completed often, like an induction for example

if the 1st list was fixed, and dragging a card across would create a duplicate of the card from the 1st (fixed column)

using this system there could be a 'to do' list for multiple users to complete the same process, then a 'Doing' and 'Done' list for users to record their progress

this is prob a long way off but it would be a cool feature, also a 1 up on Trello

**Comment by xet7** [comment]
@AndyatFocallocal 

Would this be something different than just copying card to other list?

**Comment by frmwrk123** [comment]
For me it doesn't matter how it is done but not being able to copy cards is really bad. In my usage there are some activities that repeat itself so I have created cards with checklists for them. Now I want to be able to duplicate/copy/drag and duplicate/whatever them to use them multiple times and prevent annoying repeating steps.

**Comment by xet7** [comment]
Copying checklist template to multiple cards already exists https://github.com/wekan/wekan/pull/1470
