### ISSUE TITLE
Add more LABELs to docker image

### ISSUE THREAD

**Issue by mueller-ma** [wekan/wekan#5191]
## Issue

A few more labels could be added to the Docker image. These labels are already detected during build, but not included:

Detected at least `org.opencontainers.image.source`: https://github.com/wekan/wekan/actions/runs/6807735300/job/18511066356#step:4:47

But not included in the final image: 

```bash
$ docker inspect quay.io/wekan/wekan | grep -A 4 Label
            "Labels": {
                "maintainer": "wekan",
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "23.10"
            },
```

**Comment by mueller-ma** [comment]
I think you got me wrong: `org.opencontainers.image.ref.name` and `org.opencontainers.image.version` are already included in the image. Some more `org.opencontainers.image.*` labels are automatically created during build (https://github.com/wekan/wekan/actions/runs/6807735300/job/18511066356#step:4:47), but not included in the final image.

**Comment by xet7** [comment]
@mueller-ma 

Please send PR, if you know how to fix it.

Dockerfile is at https://github.com/wekan/wekan

Charts are at https:U//github.com/wekan/charts

**Comment by xet7** [comment]
@mueller-ma 

I would think, that defining those Docker Labels more correctly, they would appear also in final image. But I could be wrong.
