### ISSUE TITLE
v7.14 startup fail: Warning: no saslprep library specified.

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#5192]
## Issue
After upgrading v7.12 → v7.14, starting WeKan fails by "Warning: no saslprep library specified."
### Server Setup Information
Did you test in newest Wekan?: 7.14
Operating System: Linux 3.10.0-1160.99.1.el7.x86_64
Deployment Method: bundle
Http frontend: Nginx
Node.js Version: 14.21.4 (version provided for WeKan)
MongoDB Version: 5.0.21

### Problem description
After upgrading from v7.12 to v7.14, starting WeKan fails by throwing this error:
```
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
(node:4673) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:7070
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at doListen (net.js:1516:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 7070
}
```

Have to revert back to v7.12 for now …

**Comment by xet7** [comment]
@BabyFnord 

> Error: listen EADDRINUSE: address already in use 0.0.0.0:7070

You already have something running at 7070.

You can not run both old and new WeKan at same port.
You should stop old WeKan first.

**Comment by BabyFnord** [comment]
@xet7 WeKan is the only thing using that port, and by `tmux ls` I can confirm that it's not running. When I list all ports in use, 7070 isn't listed. What else could I check? I couldn't find any difference between the startup script of v7.12 and v7.14 … 🤷

**Comment by xet7** [comment]
@BabyFnord 

Check is node.js running:

```
sudo apt-get -y install net-tools

sudo netstat -plant | grep :7070

sudo netstat -plant | grep node
```

**Comment by BabyFnord** [comment]
$ netstat -plant | grep :7070
tcp        0      0 0.0.0.0:7070            0.0.0.0:*               LISTEN      29457/node
tcp        0      0 100.65.68.2:7070        100.65.68.1:51664       VERBUNDEN   29457/node

$ netstat -plant | grep node
tcp        0      0 0.0.0.0:7070            0.0.0.0:*               LISTEN      29457/node
tcp        0      0 127.0.0.1:51146         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:38860         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57906         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57676         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57620         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:51148         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:51234         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57932         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57908         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57618         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57678         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:58004         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:51236         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57674         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:38858         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57934         127.0.0.1:27017         VERBUNDEN   29457/node
tcp        0      0 100.65.68.2:7070        100.65.68.1:51664       VERBUNDEN   29457/node
tcp        0      0 127.0.0.1:57930         127.0.0.1:27017         VERBUNDEN   29457/node

Would I need to stop `node`?

**Comment by xet7** [comment]
@BabyFnord 

Yes.

If you have some service, with systemd, at /etc/systemd/system like mentioned at https://github.com/wekan/wekan/wiki/Raspberry-Pi , then maybe could be something like:

```
sudo systemctl stop wekan
```
For snap:
```
sudo snap stop wekan
```
But if it is started manually, check what is it's process numer:
```
ps aux | grep node
```
And then kill it:
```
kill -9 NODE-PROCESS-NUMBER-HERE
``

**Comment by BabyFnord** [comment]
Oh, I see this, too:
```
$ uberspace web backend list
my.URL/ http:7070 => OK, listening: PID 29457, /home/name/opt/node14.21.4/bin/node main.js
/ apache (default)
```

Never had this issue before when upgrading to another version. Is there something new happening with v7.14?

**Comment by xet7** [comment]
@BabyFnord 

Depends how running node.js works at Uberspace. How to stop and start backend. Maybe they have some documentation website? Or ask from Uberspace support?

**Comment by BabyFnord** [comment]
Thanks a lot @xet7, I managed to start v7.14 after `kill -9 NODE-PROCESS-NUMBER-HERE`. While there is documentation as to starting/stopping web backends, I wonder why this wasn't necessary with v7.12 and earlier. 

Could it be, that the recent addition to my [update_wekan](https://github.com/BabyFnord/update_wekan) script
```
if tmux has-session -t wekan 2>/dev/null; then
    tmux kill-session -t wekan
    echo "Terminated WeKan session."
fi
```
has caused an ungraceful termination of a prior WeKan session?

**Comment by xet7** [comment]
@BabyFnord 

It depends, is WeKan running as web backend service, or is it running in tmux.

**Comment by BabyFnord** [comment]
The web backend service is to direct a subdomain to the port dedicated for WeKan. The startup-script runs in tmux.

**Comment by xet7** [comment]
@BabyFnord 

> Btw., the tmux session still prints `(node:29953) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized` … is this to be ignored?

If there are any MongoDB passwords in use in connecting serverside Wekan to serverside MongoDB, those are used only in environment variables at serverside, it is not accessible to users. So you can ignore that message.
