### ISSUE TITLE
"The avatar is too large" message is broken in German

### ISSUE THREAD

**Issue by mueller-ma** [wekan/wekan#5193]
### Server Setup Information

* Did you test in newest Wekan?: v7.14
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System: Docker
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox

### Problem description

When I upload a too large avatar for my account, the error message doesn't show the actual maximum size, but the placeholder `__Größe__` (German for size). When setting the language to English, the error message displays the correct maximum size.

![grafik](https://github.com/wekan/wekan/assets/22525368/4df33ad7-b15d-4b42-999c-e1625ac6f050)

#### Reproduction Steps

- Change language to German
- Upload a too large avatar

**Comment by xet7** [comment]
@mueller-ma 

This is because __size__ should not be translated. Please fix it at https://transifex.com/wekan/wekan . Thanks!

**Comment by mueller-ma** [comment]
Done
