### ISSUE TITLE
Error: wekan offline

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#5201]
Hello,

i have a machine with windows server 2016.

i want to install wekan offline .
while running start-wekan.bat, i got the following error:
Error: Cannot find module './lib/_stream_passthrough.js'

node:14.21.4

thanks

**Comment by xet7** [comment]
@MeriemBH 

Please try with newest WeKan v7.17. I updated links to newest version at Offline page:

https://github.com/wekan/wekan/wiki/Offline

**Comment by MeriemBH** [comment]
@xet7  can you please tell me the which file did you change to download it.

**Comment by xet7** [comment]
@MeriemBH 

https://github.com/wekan/wekan/releases/download/v7.17/wekan-7.17-amd64-windows.zip

**Comment by MeriemBH** [comment]
it's the zip

**Comment by xet7** [comment]
@MeriemBH 

Yes. Like written at Offline wiki page, point is to:
- Unzip zip file, so you get bundle directory, to that directory add node.exe and start-wekan.bat
- Install MongoDB
- Edit start-wekan.bat , so it starts Node.js at bundle directory, with `node main.js`
- Run start-wekan.bat

**Comment by MeriemBH** [comment]
i think the issue is coming from the following error: erreur 0*80010135 too long access for windows
while unziping the folder.

**Comment by MeriemBH** [comment]
i have the same error:Error: Cannot find module "/node_modules/meteor/accounts-password/node_modules/bcrypt/bcrypt.js".

it may be related with windows16?
