### ISSUE TITLE
wekan-v7.17 missing at https://releases.wekan.team

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#5203]
## Issue
wekan-v7.17 missing at https://releases.wekan.team

### Problem description
https://releases.wekan.team/wekan-7.17.zip does not exist (v7.16 does) although v7.17 has been released. Just sayin' … 😊

#### Reproduction Steps
See https://releases.wekan.team/ … thank you @xet7!

**Comment by xet7** [comment]
@BabyFnord 

Thanks! I added that file.

**Comment by BabyFnord** [comment]
Here we go again ;) 
## Problem description
https://releases.wekan.team/wekan-7.29.zip does not exist (v7.28 does) although v7.29 has been released. 

Thanks for filling v7.29!
