### ISSUE TITLE
Wekan on RaspberryPi (Raspbian Jessie) ?

### ISSUE THREAD

**Issue by pihug12** [wekan/wekan#521]
Hello,

I can't get Wekan to install on my RaspberryPi running Raspbian Jessie.
_Fibers_ seems to be the problem.

**Debug log:** [npm-debug.log](https://github.com/wekan/wekan/files/129568/npm-debug.log.txt)

> pi@raspberrypi:~/bundle/programs/server $ sudo npm install
> 
> > fibers@1.0.5 install /home/pi/bundle/programs/server/node_modules/fibers
> > node ./build.js
> 
> (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.6.0"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/bundle/programs/server/node_modules/fibers/.node-gyp"
> make: Entering directory '/home/pi/bundle/programs/server/node_modules/fibers/build'
>   CXX(target) Release/obj.target/fibers/src/fibers.o
> ../src/fibers.cc: In function ‘v8::Handlev8::Signature uni::NewSignature(v8::Isolate_, v8::Handlev8::FunctionTemplate, int, v8::Handlev8::FunctionTemplate_)’:
> ../src/fibers.cc:132:54: error: no matching function for call to ‘v8::Signature::New(v8::Isolate_&, v8::Handlev8::FunctionTemplate&, int&, v8::Handlev8::FunctionTemplate_&)’
>    return Signature::New(isolate, receiver, argc, argv);
>                                                       ^
> ../src/fibers.cc:132:54: note: candidate is:
> In file included from /home/pi/bundle/programs/server/node_modules/fibers/.node-gyp/5.6.0/include/node/node.h:42:0,
>                  from ../src/coroutine.h:1,
>                  from ../src/fibers.cc:1:
> /home/pi/bundle/programs/server/node_modules/fibers/.node-gyp/5.6.0/include/node/v8.h:4674:27: note: static v8::Localv8::Signature v8::Signature::New(v8::Isolate_, v8::Localv8::FunctionTemplate)
>    static Local<Signature> New(
>                            ^
> /home/pi/bundle/programs/server/node_modules/fibers/.node-gyp/5.6.0/include/node/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
> ../src/fibers.cc: In function ‘void uni::SetResourceConstraints(v8::Isolate_, v8::ResourceConstraints_)’:
> ../src/fibers.cc:140:3: error: ‘SetResourceConstraints’ is not a member of ‘v8’
>    v8::SetResourceConstraints(isolate, constraints);
>    ^
> ../src/fibers.cc:140:3: note: suggested alternative:
> ../src/fibers.cc:139:7: note:   ‘uni::SetResourceConstraints’
>   void SetResourceConstraints(Isolate_ isolate, ResourceConstraints\* constraints) {
>        ^
> ../src/fibers.cc: In function ‘v8::Handlev8::Signature uni::NewSignature(v8::Isolate_, v8::Handlev8::FunctionTemplate, int, v8::Handlev8::FunctionTemplate_)’:
> ../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
>   }
>   ^
> fibers.target.mk:95: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
> make: **\* [Release/obj.target/fibers/src/fibers.o] Error 1
> make: Leaving directory '/home/pi/bundle/programs/server/node_modules/fibers/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:100:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Linux 4.1.13+
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
> gyp ERR! cwd /home/pi/bundle/programs/server/node_modules/fibers
> gyp ERR! node -v v5.6.0
> gyp ERR! node-gyp -v v3.2.1
> gyp ERR! not ok
> Build failed
> npm WARN meteor-dev-bundle@0.0.0 No description
> npm WARN meteor-dev-bundle@0.0.0 No repository field.
> npm WARN meteor-dev-bundle@0.0.0 No license field.
> npm ERR! Linux 4.1.13+
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> npm ERR! code ELIFECYCLE
> 
> npm ERR! fibers@1.0.5 install: `node ./build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the fibers package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./build.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs fibers
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls fibers
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/pi/bundle/programs/server/npm-debug.log
> pi@raspberrypi:~/bundle/programs/server $

**Comment by loics2** [comment]
Same problem here. I tried to add a swap file (it's sometimes the problem with the nodegyp on small RAM computer), but it didn't change anything.

**Comment by j8r** [comment]
You can try to use https://github.com/4commerce-technologies-AG/meteor, `npm install` succeed but if you launch Wekan, you will end with this gridfs error
```
/home/wekan/meteor/dev_bundle/bin/node /home/wekan/bundle/main.js
[Error: /home/wekan/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson/build/Release/bson.node: wrong ELF class: ELFCLASS64]
js-bson: Failed to load c++ bson extension, using pure JS version

/home/wekan/bundle/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: /home/wekan/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: wrong ELF class: ELFCLASS64
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/wekan/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/wekan/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/home/wekan/bundle/programs/server/boot.js:162:18)
    at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:9:1)
    at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:13:1)
    at /home/wekan/bundle/programs/server/packages/npm-bcrypt.js:33:4
```

**Comment by pihug12** [comment]
I solved my issue weeks ago but I forgot to write down what I exactly did. :disappointed: 

I think these steps are enough:
```
pi@raspberrypi:~ $ cd bundle/programs/server/npm/npm-bcrypt/
pi@raspberrypi:~/bundle/programs/server/npm/npm-bcrypt $ npm uninstall bcrypt
unbuild bcrypt@0.7.8
pi@raspberrypi:~/bundle/programs/server/npm/npm-bcrypt $ npm install bcrypt
[...]
bcrypt@0.8.5 node_modules/bcrypt
├── bindings@1.2.1
└── nan@2.0.5
pi@raspberrypi:~/bundle/programs/server/npm/npm-bcrypt $

pi@raspberrypi:~ $ cd bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb
pi@raspberrypi:~/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb $ npm uninstall bson
unbuild bson@0.2.21
pi@raspberrypi:~/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb $ npm install bson
[...]
bson@0.2.22 node_modules/bson
└── nan@1.8.4
pi@raspberrypi:~/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb $
```

**Comment by j8r** [comment]
Thank you! Now I will be able to complete my installation script in my project https://github.com/j8r/DPlatform :)

**Comment by xet7** [comment]
Moved to #1053
