### ISSUE TITLE
Unable to compile an ARM64 version of Wekan using the Dockerfile.arm64v8 file

### ISSUE THREAD

**Issue by Plus-xu** [wekan/wekan#5210]
* Operating System: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1045-oracle aarch64)
* Docker Engine Version: 24.0.6 linux/arm64
* Wekan version: f512047ac6439e53f92359f45ab907c629d225a9

### Problem description

Unable to compile an ARM64 version of Wekan using the Dockerfile.arm64v8 file
#### Logs

Attaching to wekan-app, wekan-db
wekan-app  | ## There is an issue with `node-fibers` ##
wekan-app  | `/home/wekan/bundle/programs/server/node_modules/fibers/bin/linux-arm64-83-glibc/fibers.node` is missing.
wekan-app  | 
wekan-app  | Try running this to fix the issue: /opt/nodejs/bin/node /home/wekan/bundle/programs/server/node_modules/fibers/build
wekan-app  | Error: libnode.so.108: cannot open shared object file: No such file or directory
wekan-app  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1175:18)
wekan-app  |     at Module.load (internal/modules/cjs/loader.js:981:32)
wekan-app  |     at Module.Mp.load (/home/wekan/bundle/programs/server/runtime.js:37:33)
wekan-app  |     at Function.Module._load (internal/modules/cjs/loader.js:821:12)
wekan-app  |     at Module.require (internal/modules/cjs/loader.js:1005:19)
wekan-app  |     at require (internal/modules/cjs/helpers.js:107:18)
wekan-app  |     at Object.<anonymous> (/home/wekan/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
wekan-app  |     at Module._compile (internal/modules/cjs/loader.js:1116:14)
wekan-app  |     at Module.Mp._compile (/home/wekan/bundle/programs/server/runtime.js:77:23)
wekan-app  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1145:10)
wekan-app  | /home/wekan/bundle/programs/server/node_modules/fibers/fibers.js:23
wekan-app  | 		throw new Error('Missing binary. See message above.');
wekan-app  | 		^
wekan-app  | 
wekan-app  | Error: Missing binary. See message above.
wekan-app  |     at Object.<anonymous> (/home/wekan/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
wekan-app  |     at Module._compile (internal/modules/cjs/loader.js:1116:14)
wekan-app  |     at Module.Mp._compile (/home/wekan/bundle/programs/server/runtime.js:77:23)
wekan-app  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1145:10)
wekan-app  |     at Module.load (internal/modules/cjs/loader.js:981:32)
wekan-app  |     at Module.Mp.load (/home/wekan/bundle/programs/server/runtime.js:37:33)
wekan-app  |     at Function.Module._load (internal/modules/cjs/loader.js:821:12)
wekan-app  |     at Module.require (internal/modules/cjs/loader.js:1005:19)
wekan-app  |     at require (internal/modules/cjs/helpers.js:107:18)
wekan-app  |     at Object.<anonymous> (/home/wekan/bundle/programs/server/boot.js:2:15)
wekan-app exited with code 0

**Comment by xet7** [comment]
Currently, WeKan for Linux arm64 and Linux s390x does not work, because Node.js 14.x segfaults. It will be fixed when upgrading to newer Node.js version 20, for example at this or next year.

**Comment by xet7** [comment]
arm64 depends on some future upgrade, where newer Node.js or something else does not segfault

**Comment by Plus-xu** [comment]
> arm64 depends on some future upgrade, where newer Node.js or something else does not segfaultarm64 取决于未来的某些升级，较新的 Node.js 或其他内容不会出现段错误

Thanks
