### ISSUE TITLE
Error 500 Importing From Trello in Wekan Ver 7.18

### ISSUE THREAD

**Issue by vincesynergy** [wekan/wekan#5212]
Importing from Trello using JSON seems to be a problem in the latest version 7.18. I get error 500
image
![image](https://github.com/wekan/wekan/assets/16008397/d737501a-d5db-4b2e-b69d-377a1fa0d081)

I have recreated the users and mapped the trello users to the wekan users.
If I downgrade to version Wekan 6.09 and retry the import. It works as expected.
Wonder if there is a way to import my trello using 6.09 then upgrade wekan to 7.18 so I can use the latest wekan version with my data.

**Comment by xet7** [comment]
I try to fix Import/Export/Attachment related issues this year.

**Comment by xet7** [comment]
Moved to #4877
