### ISSUE TITLE
 installation from sources doesn't work: fibers@1.0.5 error

### ISSUE THREAD

**Issue by eboily** [wekan/wekan#522]
I follow the wiki for installation from sources and I get the following error:

````
$ git clone https://github.com/wekan/wekan.git && cd wekan
Cloning into 'wekan'...
remote: Counting objects: 3627, done.
remote: Total 3627 (delta 0), reused 0 (delta 0), pack-reused 3627
Receiving objects: 100% (3627/3627), 1.22 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (2370/2370), done.
Checking connectivity... done.
$ meteor build .build --directory
                                              
WARNING: The output directory is under your source tree.
                                              
$ cd .build/bundle/programs/server/ && sudo npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
/
> fibers@1.0.5 install /Users/eboily/Downloads/wekan/.build/bundle/programs/server/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:132:44: error: too many arguments to function call, expected at most 2, have 4
                return Signature::New(isolate, receiver, argc, argue)
                       ~~~~~~~~~~~~~~                    ^~~~~~~~~~
/Users/eboily/.node-gyp/4.2.4/include/node/v8.h:4675:3: note: 'New' declared here
  static Local<Signature> New(
  ^
../src/fibers.cc:140:3: error: no member named 'SetResourceConstraints' in namespace 'v8'; did you mean simply 'SetResourceConstraints'?
                v8::SetResourceConstraints(isolate, constraints);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                SetResourceConstraints
../src/fibers.cc:139:7: note: 'SetResourceConstraints' declared here
        void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
             ^
2 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/eboily/Downloads/wekan/.build/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibres package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibres
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eboily/Downloads/wekan/.build/bundle/programs/server/npm-debug.log
$
```

I am attaching the `npm-debug.log` file as a txt file:
[npm-debug.txt](https://github.com/wekan/wekan/files/131174/npm-debug.txt)

The error seems to be with fibers 1.0.5 but I can't find where to set the wekan dependency to this package to a newer version. Any idea?

Thanks!

 - Edouard

**Comment by guillaumesoul** [comment]
I'm facing the same issue too

**Comment by willow-noe** [comment]
Same too on Wheezy :'(

**Comment by jossemarGT** [comment]
Have you tried installing build-essentials and python before?

**Comment by willow-noe** [comment]
I found a solution with previous node packages. I do not know which update do the trick, i have changed the port too, it is ok now :) Thx a lot.

**Comment by RobertasMurza** [comment]
Had the same problem. Only read headers on instructions page, so had to spend whole day figuring it out :)

Just below "Install Node.js" on wiki page, there's some text, which says "currently Version 0.10.40 is required". If you install Node with `sudo apt-get install nodejs` (like I did), you'll get newer version of Node (I got 5.x.x). To install 0.10, read a bit [here](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories/), instructions are near the bottom of the page.

After getting the correct Node version, everything installs successfully.

**Comment by CodeBrauer** [comment]
Same here. You need an old version of node to run it.

I just used [`nvm`](https://github.com/creationix/nvm) to switch to v0.10.40

**Comment by pvencill** [comment]
so, that's a bug... isn't v0.10.x deprecated for security?

**Comment by CodeBrauer** [comment]
@pvencill no, currently not. https://github.com/nodejs/LTS

**Comment by mquandalle** [comment]
Wekan is dependent on node v0.10.40 due to Meteor limitations, let’s use #634 to track the removal of that limitation.

**Comment by ASES573** [comment]
Error not solved till now
C:\Users\Documents\Dev_Projects\crimson.networkexplorer.ui\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\
nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK ve
rsion 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking t
he solution and selecting "Retarget solution". [C:\Users\Documents\Dev_Projects\crimson.networkexplorer.ui\node_modules\fibers\build\fibe
rs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild" "--release"
gyp ERR! cwd C:\Users\Documents\Dev_Projects\crimson.networkexplorer.ui\node_modules\fibers
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","
arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\pm2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","
arch":"x64"})
npm WARN browserify-shim@2.0.10 requires a peer of browserify@>= 2.3.0 < 4 but none was installed.
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fibers@1.0.10" "--sav
e"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.10 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.10 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Documents\Dev_Projects\crimson.networkexplorer.ui\npm-debug.log

C:\Users\Documents\Dev_Projects\crimson.networkexplorer.ui>npm install fibers@1.0.11 --save
npm ERR! fetch failed https://registry.npmjs.org/fibers/-/fibers-1.0.11.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/fibers/-/fibers-1.0.11.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by CodeBrauer** [comment]
@ASES573 - you still need node v4 - node 6 is not supported.

**Comment by ASES573** [comment]
Thanks @CodeBrauer  
Anyway I found a fix for this
I am using npm version `3.10.10`
Node version `6.11.2`
Fibers version `~1.0.10`
If you receive any errors in installing npm packages especially fibers, do the following
Run a command prompt as Administrator and run the following command
`npm install --global --production windows-build-tools`
`npm install --global node-gyp`

NOTE: Visual Studio C++ should be installed, which actually contains the compiler for building the "fibers" module
To install VS C++ if you haven't installed, 
Goto 
-> Control Panel
-> Programs and Features
-> Visual Studio 2015
Right-click and select Change
->Select the Visual Studio C++ and Install

Now u can use the appropriate version of fibers in your project

**Comment by CodeBrauer** [comment]
No problem, @ASES573 

But you should check this PR and this comment out, https://github.com/meteor/meteor/pull/6923#issuecomment-301197439

Maybe using node6 isn't stable yet.

**Comment by xet7** [comment]
You get 100% CPU usage errors with Wekan on Node v6.

Wekan only supports Node v4.8.4 etc versions mentioned in wekan/wekan repo Dockerfile.

**Comment by willWinQuan** [comment]
window7
node:v9.5.0
npm:5.6.0

C:\Users\Administrator>meteor
C:\Users\Administrator\node_modules\_fibers@0.6.9@fibers\fibers.js:13
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node
-fibers`?');
        ^

Error: `C:\Users\Administrator\node_modules\_fibers@0.6.9@fibers\bin\win32-x64-v
8-6.1\fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (C:\Users\Administrator\node_modules\_fibers@0.6.9@fib
ers\fibers.js:13:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at makeCompatible (C:\Users\Administrator\AppData\Local\.meteor\packages\met
eor-tool\1.6.1\mt-os.windows.x86_64\tools\tool-env\install-promise.js:6:56)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages
\meteor-tool\1.6.1\mt-os.windows.x86_64\tools\tool-env\install-promise.js:9:1)

C:\Users\Administrator>node -v
v9.5.0

C:\Users\Administrator>npm -v
5.6.0

C:\Users\Administrator>choco --version
0.10.8

C:\Users\Administrator>choco install meteor
Chocolatey v0.10.8
Installing the following packages:
meteor
By installing you accept licenses for the packages.
meteor v0.0.2 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - meteor - meteor v0.0.2 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

what?

**Comment by CodeBrauer** [comment]
@willWinQuan As stated above, for best expierence node version 4.x.x

https://nodejs.org/dist/latest-v4.x/

In your case you can download this version: https://nodejs.org/dist/latest-v4.x/node-v4.8.7-x64.msi

**Comment by xet7** [comment]
As you can see from https://github.com/wekan/wekan/blob/devel/Dockerfile Wekan currently uses Meteor 1.6.0.1 and it's related versions of Node.js 8.9.3 and NPM 5.5.1. Currently Meteor bugs are preventing upgrading Meteor to v1.6.1 meteor/meteor#9609 but when those are solved, I can upgrade.
Newer version of Node, NPM etc does not work yet.

**Comment by aryeharmon** [comment]
same error on node v8.11.1

**Comment by xet7** [comment]
@aryeharmon 

This is old issue. Currently build with fibers 2.0.0 works for me.

Build from source instructions at:
https://github.com/wekan/wekan/releases

**Comment by xavisavvy** [comment]
@xet7 what version of node are you running that it is working on? With so many variables hard to tell the issue / see solutions without more details. I get this error on 4.9.1, 8.1.3, and 10.13.0
