### ISSUE TITLE
Images Upload issue

### ISSUE THREAD

**Issue by SassaBoy** [wekan/wekan#5221]
Hi guys,
I have a site that uses node js for the backend and mongodb as a database. The site stores images that must be displayed on the site, however, when in localhost(Website running from my machine), I can freely upload images and they will display, but when I deployed the site, it's not showing the images on the site.
The issue is that the images pulled from mongodb do not show up when the site is deployed. Also, sometimes when I upload the images in production mode, they do show up maybe for 10 minutes, and then they disappear. I don't know what the issue is.
What's even more confusing is when I upload an image when the website is in localhost, I go to the deployed url, it's not showing up, but it shows up in localhost/production mode. What is the issue here if they are all using the same database, in production mode and development? Or is there a timeframe set somewhere to allow the images to show up for a short period of time and then disappear?

**Comment by xet7** [comment]
@SassaBoy 

Do you mean ROOT_URL ?

https://github.com/wekan/wekan/wiki/Settings

**Comment by xet7** [comment]
@SassaBoy 

Anyway, there is In Progress of fixing all attachment related issues.

Moved to https://github.com/wekan/wekan/wiki/Sync

**Comment by SassaBoy** [comment]
ROOT_URL=http://localhost/ (if only your computer locally)
When I upload images like that: They do show up.
They just don't show up when I deployed my site to Render. I thought it was CORS but that's not the issue

**Comment by xet7** [comment]
@SassaBoy 

Instead of localhost, ROOT_URL should have your computer IP address, like ROOT_URL=http://192.168.0.200
