### ISSUE TITLE
Sandstorm Marketplace Version Significantly Outdated

### ISSUE THREAD

**Issue by AndrewKahr** [wekan/wekan#5223]
### Server Setup Information

* Did you test in newest Wekan?: N/A
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?: N/A
* Operating System: Ubuntu 22.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Sandstorm
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: v14.17.5
* MongoDB Version: v2.6.7
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?: Chrome 119.0.6045.160

### Problem description

I am setting up wekan on Sandstorm but the version on the marketplace is only v6.15.0 (from April 2022). Looking at this repo there have been a lot of updates since that version but I can't seem to find a good way to update. Is sandstorm still a supported platform for Wekan? I see a lot of documentation saying it is the preferred platform so I am a bit confused why it is so out of date on the Sandstorm Marketplace. Are we supposed to build our own spk instead? If so are there good docs for doing this? I saw some developer docs for building spk's but I am unsure if that is valid for a production system and there were warnings about the docs being out of date. Apologies if this has been asked before, I searched through the issues but couldn't find anything recent/relevant but perhaps my search terms weren't accurate enough. Appreciate any guidance I can get on this!

#### Reproduction Steps
1. Install a fresh copy of sandstorm
2. View installed version of Wekan being 6.15.0. No new spk is available in Github releases either.

**Comment by ocdtrekkie** [comment]
Hi, unfortunately the packaging tool Wekan uses for Sandstorm (meteor-spk) is pretty out of date, and Wekan moved to using newer versions of Meteor than it supports. The Sandstorm project is working on raising money to tackle some major upgrades (likely eventually this problem as well), but unfortunately we aren't there yet.

Note that unless you need newer features or fixes in Wekan, the version on Sandstorm should be perfectly adequate. Sandstorm apps are largely immune to security vulnerabilities, so they are safe to use even if significantly out of date.

**Comment by AndrewKahr** [comment]
Ah I see, really appreciate the detailed explanation on this! Is there a nice way to see the major differences between the sandstorm version and the current latest version or are they effectively equal feature wise?

**Comment by xet7** [comment]
@AndrewKahr 

As seen at:
- Install Server section: https://wekan.github.io
- At top of https://github.com/wekan/wekan/blob/main/CHANGELOG.md

> Newest WeKan at amd64 platforms: Linux bundle, Snap Candidate, Docker, Kubernetes. Fixing other platforms In Progress.

That "other platforms" also means fixing Sandstorm WeKan is In Progress.

It is possible to help by funding development at https://wekan.team/commercial-support/

**Comment by xet7** [comment]
@ocdtrekkie 

What is niscu? Is it some older version of MongoDB, where migration was made to newer MongoDB ? Does it migrate by copying data from old MongoDB port to new MongoDB port?

https://github.com/sandstorm-io/meteor-spk/blob/master/start.js#L140-L141

When running newest WeKan 7.21 at Sandstorm, there is error that MongoDB driver does not support older MongoDB used at Sandstorm. So migration would be needed:

a) To MongoDB 6.x

b) To FerretDB proxy to SQLite. Currently FerretDB is maybe missing support for OpLog, I will look what is status there. For attachments, those would be exported to files with mongofiles like https://github.com/wekan/minio-metadata converts from MongoDB to SQLite and files.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/5226
