### ISSUE TITLE
feature request: As user I want to store and follow URL, maybe with a new custom field type "URL"

### ISSUE THREAD

**Issue by KTK-Bue** [wekan/wekan#5224]
### what we have

We evaluate wekan as a collaborative tool to track tasks.  (surprise)

There can be 
* another board with correstponding task of another team
* another board with more detailed tasks (like child or 
* the wiki-page for documentation
* a web-portal (like github ;-)) to use
* a ticketsystem
 And so on.

We want to hold specific URL in cards an follow easily the link.   

### what we do

We use the custom field type "text" to put in the URL to the other website and use the checkbox "show on mini-card".

### Problem
Unfortunaly lots of URL are very long for different reasons.  
So the cards and special the minicards are very overloaded.

### what we wish

We like to have a custom field to hold URL.  
The field should show only the name on the minicard as HREF. 
As target it uses the saved URL.  
On the card maybe it should show the same.

### Example in screenshot
"Zum Board" means "go to board"

![image](https://github.com/wekan/wekan/assets/152152910/bf170309-4260-40e7-9c38-152b353235b5)

**Comment by xet7** [comment]
@KTK-Bue 

Use Custom Fields type text and Markdown like this, that shows only text Roadmap:

```
[Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-r-open-source-kanban-board-with-mit-license)
```

Or, what kind of shorter URLs you mean? Board Key like Jira? #2449

**Comment by xet7** [comment]
@KTK-Bue 

Currently markdown link opens new browser tab. Is that OK ? Or should there be a way to open link at current browser tab?

**Comment by KTK-Bue** [comment]
> Use Custom Fields type text and Markdown like this, that shows only text Roadmap:

Yes, this will work! I was not aware of using Markdown in this field. Thank you @xet7 

This way it is even better than using one custom field for each type of reference.  
To open the link in a new tab or not I don't mind. Anyway, in my opinion the new tab is better because one looks at some information and switch back to the board.

![image](https://github.com/wekan/wekan/assets/152152910/08defc0b-cd9d-4cc4-bc9c-1348ac2da639)
