### ISSUE TITLE
Azure AD B2C

### ISSUE THREAD

**Issue by snowsky** [wekan/wekan#5242]
It is a quick question about the endpoint of user info. The settings of Azure SSO work for Azure AD but not for Azure AD B2C. Azure AD B2C uses custom policy to support the endpoint of user info. Did someone also use B2C for SSO? Can the user info endpoint be optional? I tried other services that don't use user info endpoint. Thanks!

**Comment by xet7** [comment]
@snowsky 

Do you mean some custom endpoint like at Auth0 ?

https://github.com/wekan/wekan/wiki/OAuth2#auth0

Or ADFS ?

https://github.com/wekan/wekan/wiki/ADFS

Or something even more custom, where OIDC/OAuth2 was modifies to support ORACLE OIM ? Look at related commits at this wiki page:

https://github.com/wekan/wekan/wiki/Oracle-OIM

**Comment by xet7** [comment]
@snowsky 

Code is here at directories wekan-accounts-oidc and wekan-oidc:

https://github.com/wekan/wekan/tree/main/packages

Here is how to build wekan and submit pull request:

https://github.com/wekan/wekan/wiki/Emoji

**Comment by snowsky** [comment]
@xet7 thanks for the prompt response 👍 I think I found something may help for the case. Will keep you posted.

**Comment by snowsky** [comment]
From https://github.com/wekan/wekan/blob/5a9a5df448cd8a65cbeb746e733e0c1218bbc912/packages/wekan-oidc/oidc_server.js#L32, if `OAUTH2_ADFS_ENABLED` is set to `true`, the user info endpoint of B2C is not required.

The issue now is the user info returned from Azure B2C has `emails` (array) instead of `email` (string):
```
XXX: userinfo: {
...
  name: 'a a',
  given_name: 'a',
  family_name: 'a',
  emails: [ '<EMAIL_1>' ],
  ...
}
```

Probably is it possible to work with both `emails` and `email`?

Thanks!

**Comment by xet7** [comment]
@snowsky 

Please try WeKan v7.24 , settings are at https://github.com/wekan/wekan/wiki/B2C

**Comment by snowsky** [comment]
Thanks @xet7. It works 👍 by setting `OAUTH2_USERNAME_MAP` to `sub`, but didn't work if set to `email`.

**Comment by xet7** [comment]
@snowsky 

Do you use any other OAUTH2 settings, than those listed at https://github.com/wekan/wekan/wiki/B2C ? Please list all those remaining settings, anonymized, so that I can add them to that wiki page. Thanks!

**Comment by snowsky** [comment]
Here you go 👍 
```
  - name: OAUTH2_B2C_ENABLED
    value: true
  - name: OAUTH2_ENABLED
    value: true
  - name: OAUTH2_REQUEST_PERMISSIONS
    value: "openid email profile"
  - name: OAUTH2_CLIENT_ID
    value: xxxxxxxxx
  - name: OAUTH2_SECRET
    value: xxxxxxxxx
  - name: OAUTH2_SERVER_URL
    value: "https://B2C_TENANT_NAME.b2clogin.com/B2C_TENANT_NAME.onmicrosoft.com/B2C_POLICY_NAME"
  - name: OAUTH2_AUTH_ENDPOINT
    value: /oauth2/v2.0/authorize
  - name: OAUTH2_TOKEN_ENDPOINT
    value: /oauth2/v2.0/token
  - name: OAUTH2_USERNAME_MAP
    value: sub
  - name: OAUTH2_EMAIL_MAP 
    value: email
  - name: OAUTH2_FULLNAME_MAP 
    value: name
  - name: OAUTH2_ID_MAP
    value: sub
```

**Comment by xet7** [comment]
@snowsky 

Thanks! I added those settings to wiki:

https://github.com/wekan/wekan/wiki/B2C
