### ISSUE TITLE
Ability to delete / hide labels

### ISSUE THREAD

**Issue by jseadragon** [wekan/wekan#525]
Please forgive me if this has already been filed as an issue already.

1) Once a custom label is added to the sidebar, there seems to be no way to get rid of it (or hide it) if I'm no longer using it. This is extra visual clutter on the screen, and it would be a nice usability improvement to be able to remove (or hide) unused ones.
-  If a color was selected for the custom label that is already in use, this also means there are two labels with the same color, and one of them is no longer in use.

2) Another minor gripe is that I can't 'rearrange' the ordering of the labels, so it's hard to make the labels consistent across multiple boards.

Does that make sense? I'm curious if other people run into similar issues.

**Comment by xet7** [comment]
It's possible to delete labels already.
