### ISSUE TITLE
Wekan 7.27 - Metrics error:  TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by Tewis** [wekan/wekan#5258]
Wekan version: 7.27.0
Firefox 115.2.1 ESR
nginx configurated in docker-compose.yml + config file found in github

link: https://wekant.xxxxx.fr/metrics
result:     TypeError: Cannot read property 'title' of undefined

debug console:

GET
https://wekant.xxx.fr/metrics
[HTTP/1.1 500 Internal Server Error 16ms]

	
GET
	https://wekant.xxx.fr/metrics
État
500
Internal Server Error
VersionHTTP/1.1
Transfert 201 o (taille 52 o)
Priorité de la requête Highest

HTTP/1.1 500 Internal Server Error
Server: nginx/1.25.3
Date: Fri, 05 Jan 2024 14:16:23 GMT
Transfer-Encoding: chunked
Connection: keep-alive

GET /metrics HTTP/1.1
Host: wekant.xxx.fr
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: _ga=GA1.2.2007403256.1638459745; x_mtok=MCXhKGq3N9qEgSxwC
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1

Have you got an idea for this problem ?

Thank you !

**Comment by xet7** [comment]
The error is that variable title is not defined somewhere. You did not include complete error message of browser right click / Inspect / Console, where it would show at what line of what file does not have that variable defined. I have not tried does that metrics work at all.

There are also matomo metrics, I don't remember how it worked, I maybe tried some years ago.

**Comment by Tewis** [comment]
Hi,

After reboot of the server and my pc, all it's ok.
