### ISSUE TITLE
the board I left before still exist in database

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#5260]
i was working with API
in get Boards I found a board that I had left before
and i also can not access  to the board using API, retunes forbidden ( because the board still exist but i am not one of its members )

this could become a security issue... the user is not a member of board but access boars some information

**Comment by xet7** [comment]
@mohammadZahedian 

If you have Admin Panel access, then you Admin, and you also have access with API to all boards.

With API, or Admin Panel / People / People / Edit / Impresonate User, of some user that has BoardAdmin access to board, you can add yourself back to the board you are currently not member of. Or alternatively, by editing databas, adding your user ID from Users table/collection to board members IDs.

It is not a security issue, that Admin has access to everything.

So the question is, can some normal user, that is not Admin, see some data at webbrowser or API, that normal user should not see?

**Comment by mohammadZahedian** [comment]
no the user i was working with was not admin... but i could see the boards i was member of them some day...
it ( the board ) is not in my panel in site, but  i can see it in API

**Comment by xet7** [comment]
@mohammadZahedian 

Does your WeKan user see Admin Panel?

Sure, if you think that Admin should not have any access to any other users, I could remove Admin Panel, encrypt all users data, and disable API.

**Comment by xet7** [comment]
@mohammadZahedian 

WeKan has User API, and Admin API.

Admin, that can see Admin Panel, can see all boards with Admin API. At All Boards page, Admin sees those boards Admin is member of. With API, Admin can list all boards, also those,that Admin is not member of. This is because Admin than change membership of boards, and create new users, with Admin API.

User, with User API, can only see those boards User is member of.

**Comment by xet7** [comment]
@mohammadZahedian 

Being member of board, and leaving board, still keeps the board at database.

If board is Archived, and deleted from Archive, then board does not exist anymore at database.

**Comment by xet7** [comment]
@mohammadZahedian 

> the user is not a member of board but access boars some information

What information that user can access?

**Comment by xet7** [comment]
@mohammadZahedian 

Please email me at support@wekan.team 

Any security issues should be reported by email.

https://github.com/wekan/wekan/blob/main/SECURITY.md

**Comment by mohammadZahedian** [comment]
> Does your WeKan user see Admin Panel?
no he doesn't

> Sure, if you think that Admin should not have any access to any other users, I could remove Admin Panel, encrypt all users data, and disable API.
no it is oK


> User, with User API, can only see those boards User is member of.
it is what exactly i am saying, User can see the board that is **not** member of, have left before




> > the user is not a member of board but access boars some information
>
> What information that user can access?

now as i found it can see the board name and id, other request respond FORBIDDEN , but seeing the board name and id doesn't make sense when user is not member of that board

**Comment by mohammadZahedian** [comment]
i am trying to make an simple android app for wekan, and this is the problem that it shows the board that user have left before

**Comment by xet7** [comment]
@mohammadZahedian 

What version of WeKan are you running?

What API did you use?

With newest WeKan, I created new normal user. It does not show list of non-member boards. There is other API for showing list for Public Boards.

**Comment by xet7** [comment]
@mohammadZahedian 

At Admin Panel you can disable all Public Boards, if you do not want any board to be public.

**Comment by xet7** [comment]
@mohammadZahedian 

Did you try api.py at https://github.com/wekan/wekan ?

**Comment by xet7** [comment]
@mohammadZahedian 

It looks like listing public boards if forbidden for normal users API.

I presume you have old WeKan.

**Comment by mohammadZahedian** [comment]
> @mohammadZahedian
> 
> It looks like listing public boards if forbidden for normal users API.

no it is private 
> I presume you have old WeKan.

![image](https://github.com/wekan/wekan/assets/25129673/7c4ad422-81bb-4f71-b0cd-a96266dc5638)

**Comment by mohammadZahedian** [comment]
look

this user have left from this board 

![تصویر صفحه 2024-01-10 112124](https://github.com/wekan/wekan/assets/25129673/7ede1789-582f-4b4b-a1a3-ed232912a9ac)


but with his user pass it can see the "test" board in API:

![تصویر صفحه 2024-01-10 112412](https://github.com/wekan/wekan/assets/25129673/8d9dab21-8518-474b-998d-64cb54da6bfe)

**Comment by mohammadZahedian** [comment]
@xet7 
it looks be simple bug.
but i dont know where to search for its codes...
after leaving board somewhere it should be deleted form database... it seems it doesnt

**Comment by xet7** [comment]
@mohammadZahedian 

Did you install newest WeKan? I think I already fixed this WeKan v7.72. Please test.

**Comment by mimZD** [comment]
@xet7 
no this bugs still exist...
