### ISSUE TITLE
wekan-gantt-gpl is outdated on quay.io

### ISSUE THREAD

**Issue by ppom0** [wekan/wekan#5266]
Hi, we're happy users of wekan-gantt-gpl at the Picasoft non-profit since 2021 ([first commit!](https://gitlab.utc.fr/picasoft/projets/dockerfiles/-/commit/3fbef92542a9b90fe045a10619f7f74a5d76ed08) 😄).

However it seems like the Gantt version hasn't seen new tags since a few months.

- https://quay.io/repository/wekan/wekan?tab=tags
  The main wekan image's latest tag is v7.27
- https://quay.io/repository/wekan/wekan-gantt-gpl?tab=tags
  While Gantt-GPL image's latest tag is v7.10

Is it a temporary error, or is the second image unsupported?

**Comment by xet7** [comment]
@ppom0 

wekan-gantt-gpl is deprecated, because new MIT-licensed Gantt is coming to MIT-licensed wekan.

Moved to #2870

**Comment by ppom0** [comment]
Okay, thanks a lot!
