### ISSUE TITLE
MongoDB dead after upgrading from stable to beta/rc/edge

### ISSUE THREAD

**Issue by mbrinkmann** [wekan/wekan#5267]
## Issue
Dear Forum,
we are running a Wekan Snap installation on Debian 12 using stable channel. We use nginx to handle SSL, therefore caddy is not needed.

services:
  wekan.caddy:   simple, disabled, inactive
  wekan.mongodb: simple, enabled, active
  wekan:         simple, enabled, active
snap-id:      jtpboSYvTCEyHoutkkRo1SI9ioSMOUb3
tracking:     latest/stable
refresh-date: 2023-11-09
channels:
  latest/stable:    6.09 2022-12-24 (1999) 167MB -
  latest/candidate: 7.27 2024-01-02 (2782) 236MB -
  latest/beta:      6.77 2023-02-27 (2384) 187MB -
  latest/edge:      7.27 2024-01-08 (2784) 236MB -
installed:          6.09            (1999) 167MB -

whenever we upgrade to either candidate or edge, mongo is dead some seconds after the service restart. This also happens after testing upgrade from stable to beta.
i wonder, if we are missing any step.

### Server Setup Information

* Did you test in newest Wekan?:       I would love to
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? YES
* Operating System: Debian 12 up-to-date apt status
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):  snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version: from snap
* MongoDB Version: from snap
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

#### Reproduction Steps

snap refresh wekan --channel=latest/edge
![Uploading Wekan-Mongo.png…]()

This also happens, if we upgrade the correctly running stable to candidate or beta.

#### Logs
root@ne-wekan:~# journalctl -r -u snap.wekan.mongodb
Jan 17 10:25:33 ne-wekan systemd[1]: Failed to start snap.wekan.mongodb.service - Service for snap application wekan.mongodb.
Jan 17 10:25:33 ne-wekan systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'.
Jan 17 10:25:33 ne-wekan systemd[1]: snap.wekan.mongodb.service: Start request repeated too quickly.
Jan 17 10:25:33 ne-wekan systemd[1]: snap.wekan.mongodb.service: Consumed 1.380s CPU time.
Jan 17 10:25:33 ne-wekan systemd[1]: Stopped snap.wekan.mongodb.service - Service for snap application wekan.mongodb.
Jan 17 10:25:33 ne-wekan systemd[1]: snap.wekan.mongodb.service: Scheduled restart job, restart counter is at 10.
Jan 17 10:25:33 ne-wekan systemd[1]: snap.wekan.mongodb.service: Consumed 1.380s CPU time.
Jan 17 10:25:33 ne-wekan systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'.
Jan 17 10:25:33 ne-wekan systemd[1]: snap.wekan.mongodb.service: Main process exited, code=exited, status=127/n/a
Jan 17 10:25:33 ne-wekan wekan.mongodb[34027]: /snap/wekan/2784/bin/mongodb-control: line 120: mongo: command not found
Jan 17 10:25:33 ne-wekan wekan.mongodb[34026]: /snap/wekan/2784/bin/mongodb-control: line 118: mongo: command not found
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: Sending mongodb logs to /dev/null
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: mongodb bind options:  --bind_ip 127.0.0.1 --port 27019
Jan 17 10:25:32 ne-wekan wekan.mongodb[34018]: /snap/wekan/2784/bin/mongodb-control: line 85: mongo: command not found
Jan 17 10:25:32 ne-wekan wekan.mongodb[34017]: /snap/wekan/2784/bin/mongodb-control: line 82: mongo: command not found
Jan 17 10:25:32 ne-wekan wekan.mongodb[34016]: /snap/wekan/2784/bin/mongodb-control: line 81: mongo: command not found
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: NODE_OPTIONS= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: WAIT_SPINNER=Bounce (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: RESULTS_PER_PAGE= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: ORACLE_OIM_ENABLED=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_ATTRIBUTES= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_LOCAL_PROFILE_MATCH_ATTRIBUTE= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_IDENTIFIER_FORMAT= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_PUBLIC_CERTFILE= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_PRIVATE_KEYFILE= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_IDPSLO_REDIRECTURL= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_CERT= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_ISSUER= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_ENTRYPOINT= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_PROVIDER= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: SAML_ENABLED=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: CAS_VALIDATE_URL= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: CAS_LOGIN_URL= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: CAS_BASE_URL= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: CAS_ENABLED=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: PASSWORD_LOGIN_ENABLED=true (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: DEFAULT_AUTHENTICATION_METHOD=ldap
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LOGOUT_ON_MINUTES= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LOGOUT_ON_HOURS= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LOGOUT_IN= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LOGOUT_WITH_TIMER=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: HEADER_LOGIN_EMAIL=Header login email. Example for siteminder: HEADEREMAILADDRESS (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: HEADER_LOGIN_LASTNAME=Header login firstname. Example for siteminder: HEADERLASTNAME (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: HEADER_LOGIN_FIRSTNAME=Header login firstname. Example for siteminder: HEADERFIRSTNAME (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: HEADER_LOGIN_ID= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_SYNC_ADMIN_GROUPS= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_SYNC_ADMIN_STATUS= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_EMAIL_FIELD= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_EMAIL_MATCH_VERIFIED=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_EMAIL_MATCH_REQUIRE=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_EMAIL_MATCH_ENABLE=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_DEFAULT_DOMAIN= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_SYNC_GROUP_ROLES= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_SYNC_USER_DATA_FIELDMAP= (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_SYNC_USER_DATA=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_MERGE_EXISTING_USERS=false (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_FULLNAME_FIELD=CN
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_USERNAME_FIELD=sAMAccountName
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_UTF8_NAMES_SLUGIFY=true (default value)
Jan 17 10:25:32 ne-wekan wekan.mongodb[33263]: LDAP_UNIQUE_IDENTIFIER_FIELD= (default value)

**Comment by xet7** [comment]
@mbrinkmann 

Yes, you should switch back to stable channel, to get WeKan working again.

There will be automatic update to stable channel, when I have fixed upgrading MongoDB. That update will have newest WeKan.

**Comment by mbrinkmann** [comment]
Thank you :-) thanks to Vmware snapshots, the way back to working stable is easy ;-)

We found something more, looking in this thread: https://github.com/wekan/wekan/issues/5073

i tried to follow the repair command using the commands you told, adjusted to our environment.
I looks like there is an incompatibility issue with openssl1.1 and 3.0 which i also faced on another place in two of our debian 12 servers:

services:
  wekan.caddy:   simple, disabled, inactive
  wekan.mongodb: simple, enabled, inactive
  wekan:         simple, enabled, inactive
snap-id:      jtpboSYvTCEyHoutkkRo1SI9ioSMOUb3
tracking:     latest/candidate
refresh-date: today at 11:01 CET
channels:
  latest/stable:    6.09 2022-12-24 (1999) 167MB -
  latest/candidate: 7.27 2024-01-02 (2782) 236MB -
  latest/beta:      6.77 2023-02-27 (2384) 187MB -
  latest/edge:      7.27 2024-01-08 (2784) 236MB -
installed:          7.27            (2782) 236MB -
root@ne-wekan:~# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/wekan/2782/lib/x86_64-linux-gnu
root@ne-wekan:~# export PATH="/snap/wekan/2782/bin:$PATH"
root@ne-wekan:~# mongod --dbpath "/var/snap/wekan/common" --repair >> /root/repairlog.txt
mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory


Maybe this is the reason, the upgrade of mongo is not working?

**Comment by xet7** [comment]
@mbrinkmann 

> mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
> Maybe this is the reason, the upgrade of mongo is not working?

If you are repairing database, you should first stop WeKan:
```
sudo snap stop wekan
```
If using WeKan 6.09 Snap Stable, and included version of mongod, I presume path to libcrypto.so.1.1 should be first at path:
```
export LD_LIBRARY_PATH=/snap/wekan/2782/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
```
And then use that mongod that is included at /snap/wekan/bin 

If using WeKan 7.x Snap Candidate, it has newest MongoDB 6.x dependencies.

But, upgrading is actually more about doing mongodump with old MongoDB 3.x, and mongorestore with MongoDB 6.x, and then also changing database structure so that attachments are visible, that migration code is what I'm working to fix. 

There will be automatic upgrade from WeKan 6.09 Snap Stable to newest WeKan 7.x, staying at Stable channel. Also other channels will be using that newest WeKan 7.x, but the point is, Stable users should keep using Stable.

**Comment by mbrinkmann** [comment]
Understood.

Thanks a lot for your explanation and work! :)

Kind regards
Marc

**Comment by lorodoes** [comment]
https://github.com/wekan/wekan/pull/5349

Should be fixed with this pull
