### ISSUE TITLE
connect OnlyOffice and Wekan?

### ISSUE THREAD

**Issue by mbrinkmann** [wekan/wekan#5268]
## Issue
connect OnlyOffice and Wekan?

### Server Setup Information
* Did you test in newest Wekan?: newest stable version in snap, yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Debian 12
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: from snap
* MongoDB Version: from snap
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? mainly Firefox and Edge, both up-to-date in stable channel

### Question
Is it possible to connect OnlyOffice and Wekan, so that Office or PDF Files can directly be opened in the browser?

**Comment by xet7** [comment]
There will be automatic update to Snap Stable from WeKan 6.09 to 7.x.

WeKan 7.x can preview card attachment PDF at browser.
