### ISSUE TITLE
wekan-v7.29 missing at https://releases.wekan.team

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#5274]
### Problem description
https://releases.wekan.team/wekan-7.29.zip does not exist (v7.28 does) although v7.29 has been released. 

Thanks for filling v7.29!

**Comment by xet7** [comment]
Thanks! Fixed.

**Comment by BabyFnord** [comment]
@xet7 Same for 7.38 … thanks for fixing!

**Comment by xet7** [comment]
@BabyFnord 

Fixed.

**Comment by BabyFnord** [comment]
@xet7 Same for 7.47 … thanks for fixing!

**Comment by xet7** [comment]
Sorry, it does not work.

Please fix your scripts to use files at GitHub releases:

https://github.com/wekan/wekan/releases

There is also RSS feed of releases:

https://github.com/wekan/wekan/releases.atom

**Comment by BabyFnord** [comment]
I modified my script accordingly:
```
base_url="https://github.com/wekan/wekan/releases/download"
version=$(curl --silent https://api.github.com/repos/wekan/wekan/releases | grep -oP '"tag_name":\s*"v\K[^"]+' | sort -h | tail -n1)
wget "$base_url"/v"$version"/wekan-"${version}".zip
```
which renders `https://github.com/wekan/wekan/releases/download/v7.48/wekan-7.48.zip` as in the past, a URL in the scheme of `https://releases.wekan.team/wekan-7.48.zip` lead to the required `bundle` version of a latest release.

@xet7, your links do not point to the required `bundle` version, in fact, I can't find any bundle version on Github.

**Comment by BabyFnord** [comment]
@xet7 [https://releases.wekan.team/](https://releases.wekan.team/) was the only place to download bundle versions, they are not released on Github. Could you please change that?

**Comment by xet7** [comment]
@BabyFnord 

What bundle version is missing?

7.29 is here: https://github.com/wekan/wekan/releases/download/v7.29/wekan-7.29-amd64.zip

Release of that version is here: https://github.com/wekan/wekan/releases/tag/v7.29

**Comment by BabyFnord** [comment]
> What bundle version is missing?

The bundle version previously available at https://releases.wekan.team/ and referenced here: https://github.com/wekan/wekan/wiki/Platforms#not-exposed-to-internet-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures-no-automatic-updates-no-sandboxing

This is needed for Linux 3.10.0-1160.99.1.el7.x86_64 … Thank you!

**Comment by xet7** [comment]
@BabyFnord 

What WeKan version number?

**Comment by xet7** [comment]
@BabyFnord 

There are many different versions mentioned at that webpage.

**Comment by BabyFnord** [comment]
Oopsie, there was a misunderstanding from my side: 
I assumed any bundle version from https://releases.wekan.team/ to be technically different from the `*-amd64.zip` Github releases. All I need is the most recent version. That's fixed for now … 

Thanks again @xet7!

**Comment by xet7** [comment]
@BabyFnord 

Yes, those bundles are same at https://github.com/wekan/wekan/releases . Thanks!
