### ISSUE TITLE
Docker-Image 7.30  from wekanteam/wekan has user assignment bug

### ISSUE THREAD

**Issue by kschimpanski** [wekan/wekan#5285]
## Issue
Today we recognized that users cannot be assigned to cards anymore. If you try to add a user to a card, only your own user is shown to be assigned multiple times, however you cant click the entries (see screenshot). Also if you have a look at the board members it will only show your own user - again multiple times.
Last friday (Febrary 2nd) this bug definitely didn't occur. Since the last wekan update was on January 28th I guess the docker image has been recreated since Friday but now contains this bug..?

I used a backup and changed the image version to 7.29 which resolved the problem.

Is it safe to go back to version 7.29 or can you provide a bug fix for the current docker-image?

### Server Setup Information

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Ubuntu 22.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.13
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox, Edge, ...

### Problem description
![image](https://github.com/wekan/wekan/assets/117566832/f529d1cd-f2a2-40e4-98d1-3243540e6fd5)
#### Reproduction Steps
Create a fresh docker(-compose) instance using the latest image from wekanteam: wekanteam/wekan:latest
Create a user, create a card and assign the user to the card. The current user is shown multiple times, but can't be assigned.

#### Logs
Logs don't show any errors.

Best regards

**Comment by kschimpanski** [comment]
I just recognized if you set the image version to 7.30: wekanteam/wekan:v7.30 it's fine. If you set it to wekanteam/wekan:latest its not working again. However wekan shows to be version 7.30.0 in both cases.

**Comment by rjl9** [comment]
Same experience with 7.31. My team has been upgraded to this version and board use has been crippled due this bug. Any way to fix it?
