### ISSUE TITLE
Api.py Label

### ISSUE THREAD

**Issue by xator91** [wekan/wekan#5286]
There is a way to add label with api.py?

**Comment by xet7** [comment]
@xator91 

WeKan API docs are at https://wekan.github.io/api/

api.py is here https://github.com/wekan/wekan/blob/main/api.py

API code is here https://github.com/wekan/wekan/tree/main/models

You can add way to add label to api.py

Here is info how to make pull request:

https://github.com/wekan/wekan/wiki/Emoji

**Comment by xator91** [comment]
Tried, but doesnt work:

if arguments == 3:

    if sys.argv[1] == 'cardsbyswimlane':
        # ------- RETRIEVE CARDS BY SWIMLANE ID START -----------
        boardid = sys.argv[2]
        swimlaneid = sys.argv[3]
        cardsbyswimlane = wekanurl + apiboards + boardid + s + sws + s + swimlaneid + s + cs
        headers = {'Accept': 'application/json', 'Authorization': 'Bearer {}'.format(apikey)}
        print("=== CARDS BY SWIMLANE ID ===\n")
        body = requests.get(cardsbyswimlane, headers=headers)
        data = body.json()

        for card in data:
            label_ids = card.get('labelIds', [])
            print(f"Card ID: {card['_id']}")
            print(f"Title: {card['title']}")
            print(f"Description: {card['description']}")
            print(f"List ID: {card['listId']}")
            
            if label_ids:
                print(f"Label IDs: {label_ids}")
            else:
                print("No Label IDs")

            print("-----")
            
Im trying to retrieve id of labels:

Card ID: mkMHyYQAMQMydxo8j
Title: w
Description:
List ID: 7ffkpzgLSD7nRgad4
No Label IDs

**Comment by xet7** [comment]
@xator91 

Add some lines to print what happens at each step. Check that there is API code at models.

**Comment by xator91** [comment]
> @xator91
> 
> Add some lines to print what happens at each step. Check that there is API code at models.

=== CARDS BY SWIMLANE ID ===

URL: http://localhost:3001/api/boards/4wdoc4JnJqMDMfz5r/swimlanes/JTwakM9LyXQRbMHmn/cards
Status Code: 200
Data: [{"_id":"j7qANvZEbu5QbzByP","title":"130 / 60/2200 2,2 KW","description":"test","listId":"7ffkpzgLSD7nRgad4","assignees":[]}
,{"_id":"u6cCy3DNarTN9pw7v","title":"130 / 60/2200 2,2 KW","description":"test","listId":"7ffkpzgLSD7nRgad4","assignees":[]}
,{"_id":"mkMHyYQAMQMydxo8j","title":"w","description":"","listId":"7ffkpzgLSD7nRgad4","assignees":[]}

**Comment by xator91** [comment]
Maybe i have to add a way to add "card id" to retrieve everything from a card?

**Comment by xet7** [comment]
@xator91 

Maybe, if there is no API for that yet.

**Comment by xet7** [comment]
@xator91 

There is API for getting info from card:

https://wekan.github.io/api/v7.30/#get_card

So you could add to api.py a way to call that API.
