### ISSUE TITLE
Allow to import Trello JSON data from the uploaded files

### ISSUE THREAD

**Issue by ForNeVeR** [wekan/wekan#529]
I am not even the biggest GTD addict, but my data exported from Trello weighs more than 2.5 MB. Chrome is extremely unhappy to paste such amount of data to a single text field on an import page (FF was just ordinarily unhappy though). Wekan server itself is okay and haven't very much problem importing this data.

I think that the better solution would be to allow users to upload their data as `.json` file, not with the text input field.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
