### ISSUE TITLE
Labels and Duplicate api.py integrations

### ISSUE THREAD

**Issue by xator91** [wekan/wekan#5298]
I want to integrate a new function with api.py, who is the function to duplicate a board? 

Also there is a way to have "labels" global instead of label attached to boards? I mean having labels that are automatically added for every new boards?

@xet7

**Comment by xet7** [comment]
@xator91 

For duplicate board, you can find related code by searching wekan code directory:
```
cd wekan

./find.sh duplicate
```
For example, if that function is at `models` directory, you can look at other models code how to add new REST API.

For labels, you can also find related code with:
```
./find.sh label
```
But I'm not sure what you mean with global, it depends where it is useful to have labels. For example, should there be labels added at Admin Panel / People / Teams, so everyone at that team should have that label at all boards, where team is member of that board.
