### ISSUE TITLE
Question about checklist in card

### ISSUE THREAD

**Issue by odseg** [wekan/wekan#5310]
WeKan ®  6.09.0

Good day , not find anwer on my question.
May be present way to bulk add points in checklist in card?

**Comment by xet7** [comment]
@odseg 

It is possible to add checklist with API. Docs at https://wekan.github.io/api/ , and `api.py` at https://github.com/wekan/wekan . 

If there is not yet example command at `api.py` , maybe @xator91 can help to add it.

**Comment by odseg** [comment]
thnks a lot

**Comment by xator91** [comment]
> thnks a lot

Commited. Have a nice day
