### ISSUE TITLE
People list (administrator shown many, many times)

### ISSUE THREAD

**Issue by johnnytolengo** [wekan/wekan#5317]
## Issue
Env: Docker v7.31, mongodb v7.0

After upgrade from v7.27 to v7.31 suddenly the user is shown multiple times:

![image](https://github.com/wekan/wekan/assets/5218298/1869fc2d-4ed0-4ff5-b312-8e86daa4e8b5)

![image](https://github.com/wekan/wekan/assets/5218298/7d854ef7-2801-4f7d-afff-874eae547bf5)

**Comment by e-gaulue** [comment]
Maybe it's another bug, but in fact I observe the same even in v7.37.

In my case, what I see is:
- user was associated with a board (I see 26 members in my board in no SQL Booster)
- user is removed (I see 19 documents in my users collection in no SQL Booster)
- then user icon in the board is replace by one of the administrator: I've got 7 of them at the end of the list

When you want to remove them from the board you get the same as #5330.

According to me all of those troubles are linked.
