### ISSUE TITLE
API get_all_cards doesn't return SwimlaneId

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#5319]
@xet7 @xator91 
in API when you get_all_cards the result json is ordered by created date not real order on list

**Comment by xator91** [comment]
> @xet7 @xator91 in API when you get_all_cards the result json is ordered by created date not real order on list

get_all_cards Swimlane or List? Rest-API or api.py?

**Comment by mohammadZahedian** [comment]
> get_all_cards Swimlane or List? Rest-API or api.py?

@xator91
both of them, now i am using swimlane

**Comment by xator91** [comment]
> > get_all_cards Swimlane or List? Rest-API or api.py?
> 
> 
> 
> @xator91
> 
> both of them, now i am using swimlane , Rest-API

Ok I'll check it on Monday

**Comment by mohammadZahedian** [comment]
@xator91 
any improvement ?

**Comment by mohammadZahedian** [comment]
@xet7 why it is closed ?

**Comment by mohammadZahedian** [comment]
@xet7 
thanks, fixed
but in get_swimlane_cards it has same problem
