### ISSUE TITLE
Problem with Heroku

### ISSUE THREAD

**Issue by Cosbgn** [wekan/wekan#532]
Hi, I'm having an error when trying the automatic heroku deploy.. Any ideas why?
Thanks!

`There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.`

**Comment by alvinvarghese** [comment]
Same problem here, Please help

**Comment by denisinla** [comment]
+1

**Comment by alvinvarghese** [comment]
It seems like no one is gonna respond. It is been a long time :-1:

**Comment by xet7** [comment]
Moved to #693
