### ISSUE TITLE
K8s - LDAP Authentification

### ISSUE THREAD

**Issue by Gomoryong** [wekan/wekan#5327]
Hello,
Is there a way to configure Ldap authentification in a Wekan helm deployment on K8s ?
I found the documentation for docker-compose but i don't find any documentation for K8s
Thank you

Regards

**Comment by xet7** [comment]
@Gomoryong 

LDAP is using environment variables at all platforms:

https://github.com/wekan/charts/blob/main/wekan/values.yaml#L28

https://github.com/wekan/wekan/wiki/LDAP

https://artifacthub.io/packages/helm/wekan/wekan

For properly syncing LDAP users, there is separete Python script. Using internal way to sync users with synced-cron is incomplete.

https://github.com/wekan/wekan/blob/main/ldap-sync/ldap-sync.py

**Comment by Gomoryong** [comment]
Hello @xet7 
Thank a lot, i will take a look at the links :)
