### ISSUE TITLE
Will wecan add a new function that tips the deadline time around card?

### ISSUE THREAD

**Issue by yjfdl123** [wekan/wekan#533]
We're now using the wecan in our group.  And it really boost our communication.

But in practice, we want a new function.

We can add a card in a list. And the cards are marked  with different colors represent different tasks.
### If the card can be marked with deadline time.

When the time is passing, then the color can be changed automatically.

Will you add such function??

**Comment by Umi97** [comment]
+1

**Comment by avatar1024** [comment]
There is a post on this function See [#55](https://github.com/wekan/wekan/issues/55).
