### ISSUE TITLE
Filtering is slow

### ISSUE THREAD

**Issue by HMGG** [wekan/wekan#5342]
### Server Setup Information

* Did you test in newest Wekan?: Tested in 7.37
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Not related
* Operating System: Linux
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): no
* Node.js Version: 14.21.4
* MongoDB Version: 5.0.8
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox 123

### Problem description

When filtering the page is unresponsive for ~20 seconds. The board has about 400 cards, 10 swimlanes and lists, and 50 labels.
Here's a link for a profiler recording, the filtering starts at 8 seconds and the page is responsive again at 28 seconds.
https://share.firefox.dev/3VfGKSm

#### Reproduction Steps

Click on a label to filter.

#### Logs

No relevant logs in browser, backend is not related

**Comment by xet7** [comment]
@HHGG 

Did you test in newest WeKan ?

**Comment by HMGG** [comment]
Tested in 7.42, UI was still unresponsive for 13 seconds
https://share.firefox.dev/3JD2xwx

**Comment by xet7** [comment]
@HMGG 

Does some Chromium based browsed load page faster?

**Comment by HMGG** [comment]
Yes, I tested in Brave, it took 5 seconds.

**Comment by HMGG** [comment]
For a colleague who uses chrome, it froze for 20 seconds, he also got a "page is unresponsive" message.
This issue is probably not related to browser engines.

**Comment by xet7** [comment]
@HMGG 

Issue is related to browser engines.

At Amiga 500, with 1 MB of RAM, it is possible to play fast-paced game.

Godot has 3D game example that works when there is good graphics card. But when game is saved as HTML/WASM, Chrome can not load it. Smaller games work fine.

When importing big board JSON file that also has attachments BASE64 encoded to WeKan, it only works on computer that has 32 GB RAM.

Browsers can not handle 10 MB of Javascript with a lot of cards. Browsers usually have 20 millions of lines of code, and a lot of optimizations.

Browser is the problem, it is not fast enough.

In progress is figuring out how to filter serverside, and load only visible data, with minimal Javascript, then it will load fast.

**Comment by xet7** [comment]
Try this https://github.com/wekan/wekan/wiki/Cron
