### ISSUE TITLE
E-mail lang

### ISSUE THREAD

**Issue by gabrin** [wekan/wekan#535]
If change on profile language, emails sending on english.

**Comment by HLFH** [comment]
@mquandalle Hi. It would be great to have the invitation email in French or in another language if we have switched the Wekan board from English to French (or another language).

**Comment by xet7** [comment]
@whodafly 

Can you check does this still happen? I did not get my SMTP server settings configured correctly yet.

Invitation emails are translated in Transifex, but I don't know are they in use currently.

Email sending code is at repo at wekan/models/users.js .

I did add more other text to be translatable today at https://github.com/wekan/wekan/commit/c9c6682299ce342f942ffe33d7bba2e4a640c1c4

**Comment by xet7** [comment]
Invitations use language that is used by admin that makes invitations in Admin Panel. This seems to be fixed already.
