### ISSUE TITLE
Strikethrough text in Board Settings / Members / Teams or Organizations

### ISSUE THREAD

**Issue by DarthJahus** [wekan/wekan#5352]
### Server Setup Information

* Did you test in newest Wekan? Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Ubuntu 23.04 Server
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache2
* Node.js Version: /
* MongoDB Version: 6
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Latest MS Edge

### Problem description

![image](https://github.com/wekan/wekan/assets/7353366/62002f4c-98b1-4d98-87b3-64e93f288067)

As you can see on the screenshot, organization or team name is shown as ~~strikethrough~~. This only happens when the team/org is active, and does not happen if it's inactive.

When a team is inactive, the name is already strikethrough, so I guess the strikethrough tag are nullifying each other.

In the following screenshot, R-pur is __not__ active, but MinuteNews is active:

![image](https://github.com/wekan/wekan/assets/7353366/1c0d738d-49dc-461f-812c-945fa643c8d1)

**Comment by xet7** [comment]
@DarthJahus 

Maybe send PR like this https://github.com/wekan/wekan/wiki/Emoji ?

To files here:

https://github.com/wekan/wekan/tree/main/client/components/sidebar

I'll get some sleep.
