### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by CodeCrafts68** [wekan/wekan#5357]
### Server Setup Information

* Did you test in newest Wekan?:yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System:windows
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:14
* MongoDB Version:7
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?chrome

#### Reproduction Steps
Download the source code to start Wekan locally and install Meteor. Run meteor npm install, run meteor, but report an error

**Comment by zhengyawen1126** [comment]
![Uploading meteorError.png…]()

**Comment by zhengyawen1126** [comment]
W20240318-16:42:52.456(8)? (STDERR) C:\Users\zheng\AppData\Local\.meteor\packages\meteor-tool\2.15.0\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20240318-16:42:52.479(8)? (STDERR)                                             throw(ex);
W20240318-16:42:52.480(8)? (STDERR)                                             ^
W20240318-16:42:52.481(8)? (STDERR) 
W20240318-16:42:52.482(8)? (STDERR) TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
W20240318-16:42:52.483(8)? (STDERR)     at new NodeError (internal/errors.js:322:7)
W20240318-16:42:52.484(8)? (STDERR)     at validateString (internal/validators.js:124:11)
W20240318-16:42:52.485(8)? (STDERR)     at Object.join (path.js:424:7)
W20240318-16:42:52.486(8)? (STDERR)     at module (models/attachments.js:41:22)
W20240318-16:42:52.487(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20240318-16:42:52.488(8)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20240318-16:42:52.489(8)? (STDERR)     at Module.moduleLink [as link] (C:\Users\zheng\AppData\Local\.meteor\packages\modules\0.20.0\npm\node_modules\@meteorjs\reify\lib\runtime\index.js:52:22)
W20240318-16:42:52.490(8)? (STDERR)     at module (server/publications/attachments.js:1:24)
W20240318-16:42:52.491(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20240318-16:42:52.492(8)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20240318-16:42:52.492(8)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20240318-16:42:52.493(8)? (STDERR)     at D:\projects\wekan-main1\.meteor\local\build\programs\server\app\app.js:195009:1
W20240318-16:42:52.493(8)? (STDERR)     at D:\projects\wekan-main1\.meteor\local\build\programs\server\boot.js:385:38
W20240318-16:42:52.494(8)? (STDERR)     at Array.forEach (<anonymous>)
W20240318-16:42:52.494(8)? (STDERR)     at D:\projects\wekan-main1\.meteor\local\build\programs\server\boot.js:210:21
W20240318-16:42:52.495(8)? (STDERR)     at D:\projects\wekan-main1\.meteor\local\build\programs\server\boot.js:439:7
W20240318-16:42:52.495(8)? (STDERR)     at Function.run (D:\projects\wekan-main1\.meteor\local\build\programs\server\profile.js:256:14)
W20240318-16:42:52.496(8)? (STDERR)     at D:\projects\wekan-main1\.meteor\local\build\programs\server\boot.js:438:13 {
W20240318-16:42:52.496(8)? (STDERR)   code: 'ERR_INVALID_ARG_TYPE'
W20240318-16:42:52.496(8)? (STDERR) }
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
