### ISSUE TITLE
not obvious now to scroll "my boards" in mobile safari

### ISSUE THREAD

**Issue by risacher** [wekan/wekan#5374]
## Issue
When accessing Wekan via mobile Safari, if there are too many boards to fit on the screen, it seems impossible to scroll the list of boards to access the boards at the bottom of the screen.

### Server Setup Information
* Did you test in newest Wekan?: 	7.23.0 (yes)
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? 
* Operating System: Ubuntu 20.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): (custom reverse proxy)
* Node.js Version: 	14.21.4
* MongoDB Version:  4.2.24
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? mobile safari (

### Problem description

https://youtu.be/L-v5YuBO5lk
	
#### Reproduction Steps

1. Make enough boards that they don't fit on the screen of an iPhone.
2. Access wekan through safari on iPhone.
3. Try to get to a board off the bottom of the screen.
4. Be frustrated.

**Comment by risacher** [comment]
Whoops!  I just discovered that two-finger drag does what I wanted.   I will rename this issue from `"my boards" not scrollable in mobile safari` to `not obvious how to scroll "my boards" in mobile safari`.  Feel free to close this as WONTFIX if you think its a non-issue.

**Comment by xet7** [comment]
@risacher 

Have you enabled drag handles?

https://github.com/wekan/wekan/wiki/Drag-Drop
