### ISSUE TITLE
Why is the "Contributing code" link pointing to "Emoji"?

### ISSUE THREAD

**Issue by tvogel** [wekan/wekan#5376]
I am still looking for a way to set up a local Wekan dev environment, tried the "Building WeKan and sending PR."  link and was quite puzzled to find myself on a page about Emojis:

https://github.com/wekan/wekan/blob/3f28c0dd227fee70d3a1aae0513cb736178a634b/CONTRIBUTING.md?plain=1#L36

**Comment by xet7** [comment]
@tvogel 

That page has info how to correctly build WeKan and make pull request.
