### ISSUE TITLE
Run Wekan Locally

### ISSUE THREAD

**Issue by ghadafs** [wekan/wekan#5389]
Hi, I would like to customize some stuff in UI and I'm unable to run the code locally on visual studio,
Can you please assist?

**Comment by xet7** [comment]
@ghadafs 

For users, It is already possible to add custom logo and product name at Admin Panel / Layout. Also it's possible to set card attachment image as background image or card cover image. At board settings, it's possible to change color theme. At hamburger menus, it's possible to change color of swimlane, list, card and labels.

For programmers, info is at https://github.com/wekan/wekan/wiki/Emoji
