### ISSUE TITLE
Wekan should tell when connection is lost

### ISSUE THREAD

**Issue by ForNeVeR** [wekan/wekan#539]
Consider a following scenario:
1. I open Wekan in browser.
2. Wekan host is down.
3. I use Wekan: create new cards etc. _There's no indication_, but it cannot save anything to server.
4. After the server is restarted, all my changes are lost.

Wekan definitely should show a big red scary notification about lost connection, and maybe even block the data editing.

**Comment by xet7** [comment]
Moved to #466
