### ISSUE TITLE
Wekan - Node process

### ISSUE THREAD

**Issue by Pablo9h** [wekan/wekan#5391]
Traducción al inglés con datos separados por puntos:
Hello. We have a virtual machine (VM) created on our ProxMox server with a Debian 12 operating system and Wekan installed on it. The problem is that for the past week we have been having problems with a process called "node" which, as time goes on, consumes exponentially more and more CPU, to the point that Wekan crashes and needs to be restarted. We have executed the command "cpulimit -b -e node -l 50" which limits CPU usage to 50% (since the node process sucks up all the CPU) but it still slows down and crashes. Here are more technical specifications about our Wekan and we hope for a solution:

Wekan Specifications:

Version: 6.09.0
Meteor Version: 2.2
Node Version: 12.22.10
MongoDB Version: 3.2.22
MongoDB Storage Engine: WiredTiger
MongoDB Oplog Enabled: Yes
System Type: Linux
System Platform: linux
System Architecture: x64
System Release: 6.1.0-18-amd64
System Uptime: 3 hours, 15 minutes, 3 seconds
System Load Average: 0.42, 0.71, 0.83
Total System Memory: 16 GB
Free System Memory: 13 GB
Number of System CPUs: 12
Node Heap Usage:

Total Heap Size: 691 MB
Executable Heap Size: 4 MB
Total Physical Size: 691 MB
Total Available Size: 4 GB
Used Heap Size: 477 MB
Heap Size Limit: 4 GB
Malloced Memory: 152 KB
Peak Malloced Memory: 6 MB
Does Zap Garbage: 0
Number of Native Contexts: 2
Number of Detached Contexts: 0
Node Memory Usage:

Resident Set Size: 834 MB
Total Size of the Allocated Heap: 691 MB
Actual Memory Used: 477 MB
External: 71 MB
We hope for a solution to this issue.

**Comment by dzuperman** [comment]
I add information to the case
The installation method has been via “snap” from the url: https://github.com/wekan/wekan-snap/wiki/Install
Server Setup Information
Did you test in newest Wekan?: No (only 6.09.0)
Did you configure root-url correctly so Wekan cards open correctly (see[ https://github.com/wekan/wekan/wiki/Settings](https://github.com/wekan/wekan/wiki/Settings))? Yes
Operating System: Linux Debian-Server 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux on Proxmox
Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
Node.js Version: 12.22.10
MongoDB Version: 3.2.22
What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox 125.0.2 and latest, GChrome latest

Thansk in advance for any support!

**Comment by xet7** [comment]
Solution is to wait for automatic upgrade to newer WeKan, where will be improvements.

**Comment by bitacorabyte** [comment]
Dear Mr. Lauri Ojansivu.
Thank you very much for your answer and dedication.
Is there an estimate time of the moment when the update will be release?
Thank you so much

**Comment by dzuperman** [comment]
Dear Mr. Lauri Ojansivu.
Thank you very much for your answer and dedication.
Is there an estimate time of the moment when the update will be release?
Thank you so much

**Comment by xet7** [comment]
@dzuperman 

There is no estimated time. It is ready and released as automatic update, when it is ready.

It's just that upgrading all platforms is In Progress.
