### ISSUE TITLE
Can't set a Due Date that has a leading zero in time, errors with `invalid time`

### ISSUE THREAD

**Issue by C0rn3j** [wekan/wekan#5395]
### Server Setup Information
7.44 Wekan in Docker using Chromium, behind nginx reverse proxy

### Problem description

Trying to change due date on some of my old cards throws `invalid time` error.

These were made ages ago on an old snap wekan version.  
New cards seem to work fine.

![image](https://github.com/wekan/wekan/assets/1641362/96824458-0574-45b6-9ef0-b0b943739768)

**Comment by juppees** [comment]
You may try to omit the leading zero - this works at least for me. With a leading zero, the same error arrises.

**Comment by C0rn3j** [comment]
> You may try to omit the leading zero - this works at least for me. With a leading zero, the same error arrises.

Thanks for that workaround and nailing it down!

`09:00` errors but `9:00` works just fine.

**Comment by C0rn3j** [comment]
https://github.com/wekan/wekan/blob/f3113593739df90f2b4c8cd68e24a62f389eacd0/client/lib/datepicker.js#L6-L11

https://github.com/wekan/wekan/blob/f3113593739df90f2b4c8cd68e24a62f389eacd0/client/lib/datepicker.js#L102-L120

Well it's here, but I am not 100% sure how to fix it.

**Comment by C0rn3j** [comment]
This makes 9:00 be invalid, which is perhaps not ideal, but at least it corresponds to the HH:mm hint.

Side note, is there a way to add the variable that's problematic to the error output?

`Invalid time: "9:00", expected HH:mm format` would make the issue even more obvious.  
I honestly did not understand at first that it was the TIME that was the problem, despite it saying so and even highlighting the form. I though the date could also be wrong somehow.
