### ISSUE TITLE
Cannot scroll down "my Boards" in Android Chrome PMI

### ISSUE THREAD

**Issue by caeschfloh** [wekan/wekan#5397]
### Problem description
It is almost impossible on my mobile device to scroll up and down. Sometimes it works with 1 finger on the left, sometimes on the right. But most of the time, it drags a Board square instead, which is rather annoying. The scrolling feature is far too thin (or the board squares too large). With two fingers, it doesn't work at all. 
#### Reproduction Steps
Start the PMI app on Android Chrome and try to scroll down to the 12th Board (I can see 8 full and 2 half in two columns)

**Comment by xet7** [comment]
Enable drag handles:

https://github.com/wekan/wekan/wiki/Drag-Drop
