### ISSUE TITLE
unable to scroll down on main page

### ISSUE THREAD

**Issue by AndyatFocallocal** [wekan/wekan#541]
We have more cards than will fit on the main screen and there is no scrollbar showing to navigate to the lower ones

link: http://boards.focallocal.org/

**Comment by heerden** [comment]
This is still an issue, in FF 59, Chrome 54 and IE 11. When you have a lot of boards that "over-flow" from the browser screen, a vertical scroll bar does not appear until the browser width is reduced to at-least 800 px. In this state it makes it impossible to access your boards, until the browser window size is reduced.

**Comment by xet7** [comment]
Link does not work, and I'm unable to reproduce this. If this still happens, reopen issue and add step by step instructions how to reproduce this.

**Comment by CKoewing** [comment]
Hi @xet7 I have the same problem.

If there are to many cards in a list, the scroll bar of the list is not shown (sporadically).

Example: https://oasis.sandstorm.io/shared/Yc4FxY8gAPH-FBZpGezk3txuTIWstX6qJVlev9X4RG7

My Browser: Firefox 54.0.1 and now  55.0.2

**Comment by xet7** [comment]
@CKoewing 

Sandstorm has old version is old. I will test later is this already fixed on unreleased working newest version of Wekan for Sandstorm at #799

**Comment by xet7** [comment]
This is fixed on newest Wekan that is available at Sandstorm App Market.
