### ISSUE TITLE
"Edit Description" button is wildly out of place

### ISSUE THREAD

**Issue by C0rn3j** [wekan/wekan#5413]
7.45 Docker WeKan

After updating from the snap version to the latest docker version, I noticed the description edit button is on the other side of the screen now, unlike every other button, seems like something broke rather than this being an intentional change?

It's unwieldy to use now:

![image](https://github.com/wekan/wekan/assets/1641362/547c8ddc-8a67-471f-a79b-9d63b50d4808)

**Comment by xet7** [comment]
@C0rn3j 

Hmm, actually, that's a good point. Someone could send PR to change position.
