### ISSUE TITLE
How to run on localhost?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [wekan/wekan#542]
Hello,
Can I test wekan using something like node index.js or npm start ? I have just downloaded the code and I don't know yet how to use docker

**Comment by N07070** [comment]
Seconded ; not everybody may want or can use docker.

**Comment by ePirat** [comment]
There is a guide in the [Wiki](https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps) that describes how to do that.

**Comment by jcguarinpenaranda** [comment]
thank you

Juan Camilo Guarín Peñaranda
Estudiante de Ingeniería Multimedia y Emprendedor en tecnología
Universidad Autónoma de Occidente
Otherwise Studios: http://otherwise-studios.com
<http://mailstat.us/tr/t/pleg6bmaikkbgvuq/h/http://otherwise-studios.com/>

2016-03-14 4:31 GMT-05:00 ePirat <notifications@github.com>:
