### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by elgenmfg** [wekan/wekan#543]
I was just wondering if the notification feature will be added, and if you'd have an ETA. Thank you!

**Comment by suicidepills** [comment]
+1

**Comment by PapePathe** [comment]
+1

**Comment by PapePathe** [comment]
i am a volunteer to add this feature. Because we need it.

**Comment by AlexanderS** [comment]
There is already a notification feature in the development version. Only the release is missing.

**Comment by ebxm** [comment]
Hello, 

Is it possible to have in-app notification telling you :

- "You have been added to this card"
- "Your card has been deplaced by XXX"
- etc.

The email is great but not enough. We need a visual notification on the app.

Regards

**Comment by xet7** [comment]
Moved to #794
