### ISSUE TITLE
Mentions in comments are broken after updating to Wekan 7.47.0

### ISSUE THREAD

**Issue by saschafoerster** [wekan/wekan#5431]
## Issue

Trying to mention with @ someone in comments did work with the previous versions and is broken now. 
It is broken in multiple boards and not and issue of a deleted user, that is still present in a board. 

### Server Setup Information

Please anonymize info, and do not any of your Wekan board URLs, passwords,
API tokens etc to this public issue.

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System: Debian
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker 
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.15
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Safari

**Comment by ajimix** [comment]
@saschafoerster have you checked #5330 ? That issue is still open and happening; maybe it is the same for you. Make sure your boards have no removed users as that breaks the mentions

**Comment by saschafoerster** [comment]
@ajimix Seems to be fixed by one of the last updates without me changing anything in the DB.
