### ISSUE TITLE
7.46 doesn't start in Docker

### ISSUE THREAD

**Issue by mueller-ma** [wekan/wekan#5432]
## Issue

Updating from v7.45 to v7.46 or v7.47 doesn't work as the container doesn't become healthy. Docker says `task: non-zero exit (137): dockerexec: unhealthy container`. Sadly there isn't more information about why the container doesn't become healthy.

### Server Setup Information

* Did you test in newest Wekan?:  No, as there's an issue with the update
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes, it does work on 7.45.
* Operating System: Docker on Debian
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik
* Node.js Version: from Docker image
* MongoDB Version: from Docker image

#### Logs

````
[INFO] Enabling LDAP Background Sync
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"LDAP_Sync\" next run @0","time":{"$date":1717496563196},"level":"info"}
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Tue Jun 04 2024 10:22:43 GMT+0000 (Coordinated Universal
Time)","time":{"$date":1717496563199},"level":"info"}
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"LDAP_Sync\" next run @0","time":{"$date":1717496563199},"level":"info"}
{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Tue Jun 04 2024 10:22:43 GMT+0000 (Coordinated Universal
Time)","time":{"$date":1717496563200},"level":"info"}
````

**Comment by mfilser** [comment]
I can have a look at this

**Comment by mfilser** [comment]
I tested the original Docker Image Version 7.46 without any issue and Wekan running well:
![grafik](https://github.com/wekan/wekan/assets/13166201/75c666c7-6c3f-4792-80c9-8472aacd8eac)

The sames is for 7.47, no issues and Wekan is running well, too:
![grafik](https://github.com/wekan/wekan/assets/13166201/1ba084a0-c3f8-4ab7-8656-f09ea99968a2)

Futhermore I am running Traefik too on a Debian Docker host.

**Comment by xet7** [comment]
Is this in any way related to Kubernetes and and fix I just merged? Changes to Chart came after newest WeKan release.

https://github.com/wekan/charts/issues/31

**Comment by mueller-ma** [comment]
This is unrelated to Kubernetes as I'm using Docker Swarm.

**Comment by mueller-ma** [comment]
We had a custom healthcheck in the container that executed `node` and the path to `node` changed.
