### ISSUE TITLE
Internal server errod due new user registration - email don`t come

### ISSUE THREAD

**Issue by pokrakos** [wekan/wekan#545]
Hello.
I installed just wekan. And I have a problem. When adding new user shows me the message: Internal server error. The user is added, but does not come email. Mail is configured in the file /etc/init.d/wekan:
export MAIL_URL = 'smtp: // wekanuser: wekanpass @ ip_address: 25 /'
Mail server is not the viewer attempts to log on to the e-mail. Mail to Postfix, SMTP port 25 + TLSand mail authorization. What i`m doing wrong?

**Comment by HLFH** [comment]
This is my wekan.service. I'm using systemd.

```
[Unit]
Description=open-source Kanban
After=network.target

[Service]
User=wekan
Group=wekan
WorkingDirectory=/srv/http/wekan/
Environment=NODE_ENV=production
Environment=MONGO_URL=mongodb://127.0.0.1:27017/wekan
Environment=ROOT_URL=https://example.com
Environment=MAIL_URL=smtp://username@example.com:mypassword@myhost:587/
Environment=PORT=8084
ExecStart=/usr/bin/node /srv/http/wekan/main.js

[Install]
WantedBy=multi-user.target
```

**Comment by xet7** [comment]
Somebody at chat said recently that emails work OK.
