### ISSUE TITLE
Wekan can't connect to database after update

### ISSUE THREAD

**Issue by EscolarProgramming** [wekan/wekan#5450]
### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Debian 11
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node.js Version: v14.21.4
* MongoDB Version: v6.0.15
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox, Chrome

### Problem description

Since a version from 2022 is still being delivered via Snap, I switched to the candidate branch (6.09 -> 7.50). However, after the update I always get a "503 Service Unavailable" message. When I look at the logs, I see that it cannot connect to the database: https://hastebin.com/share/torulugeyu.yaml

#### Reproduction Steps

Install Wekan with release branch (v 6.09), switch to candidate branch, update Wekan zu 7.50

#### Logs

See above

**Comment by xet7** [comment]
@EscolarProgramming 

No, it's not possible to migrate by changing channel.

Change back to Stable branch:
```
sudo snap refresh wekan --channel=latest/stable --amend
```
And wait for official automatic update, that will upgrade correctly.
