### ISSUE TITLE
Redis does not work on a wekan installed in a docker

### ISSUE THREAD

**Issue by HEMGDevelopment** [wekan/wekan#5451]
## Issue

Redis does not work on a wekan installed in a docker

* Did you test in newest Wekan?: Yes, version: 7.48.0
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: AlmaLinux VERSION 8.5 (Arctic Sphynx)
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version: 14.21.4
* MongoDB Version: 4.0.28
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
Chrome

### Problem description

Redis does not work on a wekan installed in a docker.
I have tested Redis, it stores keys/values when I do them manually.
I have tested wekan config. ( docker inspect wekan_wekan_1 | grep CACHE_URL ), it's correct.

#### Reproduction Steps
Try to install and use Redis on a docker-installed wekan.

#### Logs

The browser logs aren't relevant for checking Redis cache on wekan I think.

Docker: sudo docker logs wekan-app

{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Mon Jun 24 2024 12:22:11 GMT+0000 (Coordinated Universal Time)","time":{"$date":1719231731478},"level":"info"}

**Comment by HEMGDevelopment** [comment]
Sorry forgot: "Http frontend if any": nginx

**Comment by xet7** [comment]
@HEMGDevelopment 

If you mean using Redis OpLog, I have not tried to use it.
