### ISSUE TITLE
Bug - Cards opening off-screen, not centered correctly. [UPDATE] ModernDark Theme, Have submitted pull req

### ISSUE THREAD

**Issue by walster001** [wekan/wekan#5454]
### Server Setup Information

* Did you test in newest Wekan?: Yes, Wekan Snap Candidate 7.50
* Operating System: Ubuntu 22.04.4 LTS
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.15
* What webbrowser version are you using: Chrome 123.0.6312.58 64 bit. 

### Problem description

When creating a board with lists beyond the width of the browser screen, and then trying to open cards on those boards, the cards open at the centre of the original screen. This particular board has 12 lists, and when opening card 'test' it opens it in the center of the board, rather than the center of the screen. 

#### Reproduction Steps

Create a board in latest wekan snap candidate 7.50 and add at minimum enough lists to get a horizontal scrollbar. You will notice the more lists you add the further off screen to the left the card opens. 

Grateful for any insight you might have @xet7 
![Bug-Cardsnotopeningcenteredlongboards](https://github.com/wekan/wekan/assets/11192349/744c02b8-1e64-4530-98a3-9f9aa37111c6)

**Comment by xet7** [comment]
@walster001 

Try changing from Lists mode to Swimlanes mode, in Lists/Swimlanes/Calendar dropdown.

Try updating to newest Chrome.

Try some other web browser.

https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix

Check do you have ROOT_URL configured correctly https://github.com/wekan/wekan/wiki/Settings

For me, this does not happen in Chrome/Firefox/Brave.

**Comment by xet7** [comment]
@walster001 

At open card right top corner, try minimize/maximize.

**Comment by walster001** [comment]
> @walster001
> 
> Try changing from Lists mode to Swimlanes mode, in Lists/Swimlanes/Calendar dropdown.
> 
> Try updating to newest Chrome.
> 
> Try some other web browser.
> 
> https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix
> 
> Check do you have ROOT_URL configured correctly https://github.com/wekan/wekan/wiki/Settings
> 
> For me, this does not happen in Chrome/Firefox/Brave.

You're right, I created a new board and tried it and it now works. Will try recreating the board that has the error as it may have been a glitch for boards created on an earlier version?

**Comment by walster001** [comment]
Ah, I've figured it out. It's only when the board has the "Modern Dark" theme selected
@xet7

**Comment by walster001** [comment]
> Ah, I've figured it out. It's only when the board has the "Modern Dark" theme selected @xet7
> 
> So I believe it may be a theme specific issue
> 
> Update: Have found the relevant CSS, will create a pull req

See Pull Req
#5455

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5455 . Thanks to @walster001 !
