### ISSUE TITLE
Wekan system comments not showing date and time

### ISSUE THREAD

**Issue by DashamoolmDamu** [wekan/wekan#5459]
System comments in the activity section of the card are not showing the date and time,but normal comments do show the date and time of the comments.Am i missing something,please help me out

**Comment by DashamoolmDamu** [comment]
@devilmengcry This makes it hard to track when the card was created.

**Comment by RowhamD** [comment]
Found that this is
still working in 7.45
first broken in 7.46

Maybe its related with: 66d739b ?

**Comment by mfilser** [comment]
I can have a look at this.
