### ISSUE TITLE
Card owned by several boards

### ISSUE THREAD

**Issue by fmonthel** [wekan/wekan#546]
Hi,

I'm working in environment where we're managing several team and guys with several functional managers (so in several teams)
It should be useful to have cards that could be owned on several dashboard (not duplicate) to give visibility on several teams of Kanban activity for1 guy
Thanks

**Comment by killua-eu** [comment]
Added a bounty on this issue. Please see https://www.bountysource.com/teams/wekan/issues ...

**Comment by xet7** [comment]
@fmonthel @killua-eu 

Do you mean Linked Cards feature Wekan already has?

**Comment by xet7** [comment]
I presume this is about existing Linked Cards feature.
