### ISSUE TITLE
Wekan database backup now failing due to obsolete MongoDB

### ISSUE THREAD

**Issue by cautiouscoyote** [wekan/wekan#5467]
## Issue

Running Wekan on Ubuntu 22.04 using the latest available snap version 6.09 - which is now so ancient that it starts to hurt.

**[PLEASE UPGRADE](https://github.com/wekan/wekan/wiki/Backup)** to the newest
WeKan ® before reporting an issue, if possible.
-> **no can do as simple user.**

Please search existing Open and Closed issues, most questions have already been answered.
-> **Can't find any on this particular matter.**
I do understand however, the long-lasting [issue](https://github.com/wekan/wekan/issues/5226) of upgrading Wekan Snap due to the integration of MongoDB 3.x, which is apparently difficult to upgrade to 6.0 in a robust way.

### Server Setup Information

* Did you test in newest Wekan?: latest available on Snap, Wekan version 6.09, see above.
* Operating System: Ubuntu 22.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: it doesn't show
* MongoDB Version: it doesn't show
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?: Chromium (seems to do better than Firefox on some aspects)

### Problem description

Periodic **database backup dumps fail since regular package updates** recently (early July).
It worked fine up to that point. Something in those updates has broken stuff.

#### Reproduction Steps

Having installed "mongodb-org-tools" from the official MongoDB 6.0 repository, since lower are not officially supported on Ubuntu 22.04:
`$ echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org.list`
`$ apt install mongodb-org-tools`

`$ mongodump --version`
> mongodump version: 100.9.5
> git version: 90481484c1783826fe26ca18bbdcd30e933f3b88
> Go version: go1.21.11
>    os: linux
>    arch: amd64
>    compiler: gc

Command used:
`$ mongodump --port 27019 -o /backup/wekan-mongodbbackup-`date +"%u"``

Result:
> Failed: can't create session: failed to connect to mongodb://localhost:27019/: server at localhost:27019 reports wire version 4, but this version of the Go driver requires at least 6 (MongoDB 3.6)

Now what? This is a deal breaker. No backups is unacceptable. Suppose I'm not the only user suffering this issue?

**Comment by xet7** [comment]
@cautiouscoyote 

Use mongodump command from Snap 6.09:

https://github.com/wekan/wekan/wiki/Backup#backup-wekan-snap-to-directory-dump

I'm currently working to make automatic upgrades working and released.
