### ISSUE TITLE
no option to create a checklist item

### ISSUE THREAD

**Issue by forReason** [wekan/wekan#5472]
## Issue
I am looking at the documentation: https://wekan.github.io/api/v2.55/#wekan-rest-api-checklistitems

there is documentation to:
- get checklist item
- update checklist item
- delete checklist item

### Server Setup Information

- NaN - Documentation issue

### Problem description

- How can I add a checklist item?
![image](https://github.com/user-attachments/assets/267ee489-1f1e-406a-ac2e-6d58d775e708)

#### Reproduction Steps
1. open the wekan documentation in the browser:
https://wekan.github.io/api/v2.55/#wekan-rest-api-checklistitems
2. try to find out how to create a checklist item

#### Logs
- nan

**Comment by xet7** [comment]
@forReason 

Where did you find that link to old docs old WeKan v2.55 ? Newest WeKan is v7.51.

Link to newest docs is at https://wekan.github.io/api/

**Comment by forReason** [comment]
huh, that is literally the first link on google

**Comment by xet7** [comment]
@forReason 

Web search engines and AI have wrong results, those are getting worse all the time, when some purposefully add misinformation to web.

**Comment by xet7** [comment]
I think, I'll make .zip archive of old API docs, and only have newest docs. Maybe that will help with search engines.

**Comment by xet7** [comment]
Ok, now old docs are at .zip file. https://github.com/wekan/wekan.github.io/tree/main/api
