### ISSUE TITLE
Lost Data and Slow Loading

### ISSUE THREAD

**Issue by Ruyeex** [wekan/wekan#5508]
I'm currently using both mobile (Android) and PC (Windows), and today I got noticed that my only board was removed out of nowhere and even on mobile can't access it, and it's slow to load as well as my PC.
It's stuck on loading screen, and it doesn't work anymore on me.
I checked where to access the archived ones, and it didn't appear, and I have the newest update, but it stutters.
The only way to recover my data is to relog in
Any help?

**Comment by xet7** [comment]
@Ruyeex 

Do you mean WeKan app https://wekan.team/app/ ? After noticing your issue, some seconds ago, I rebooted WeKan server. Does that help?

Or do have self-hosted WeKan https://wekan.github.io/install/ ? What version of WeKan are you using?

**Comment by xet7** [comment]
@Ruyeex 

If it is https://wekan.team/app/ , from same email address you use for WeKan, please send email to support@wekan.team , so that I can verify it's you, and find and restore your boards.

**Comment by Ruyeex** [comment]
I managed to recover the board but the way to replicate the issue is odd bcs I can't find a way to replicate it.

> @Ruyeex
> 
> Do you mean WeKan app https://wekan.team/app/ ? After noticing your issue, some seconds ago, I rebooted WeKan server. Does that help?
> 
> Or do have self-hosted WeKan https://wekan.github.io/install/ ? What version of WeKan are you using?

Yes
I managed to recover the board but the way to replicate the issue is odd bcs I can't find a way to replicate it.
It's some common issue that sometimes happen to random users?

**Comment by xet7** [comment]
@Ruyeex 

> It's some common issue that sometimes happen to random users?

Yes, there is bug, that in some rare cases, boards could dissappear. I have fixed those cases manually at database, by fixing member IDs of board.

Meteor 2 based WeKan needs start-stop about once a week, because there are memory leaks #5140 . This is because server based Javascript (like Node.js) apps usually grow in RAM and CPU usage when time goes on. I have some non-serverside-Javascript based WeKan prototypes where that does not happen, but those do not yet have enough features to replace Meteor 2 based WeKan.

**Comment by xet7** [comment]
@Ruyeex 

For making WeKan faster, it's useful to empty browser cache, and use some fast Chromium based browser. List of browsers is at https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix

**Comment by xet7** [comment]
@Ruyeex 

Currently there is in progress figuring out, how to solve these and related issued #5475

**Comment by Ruyeex** [comment]
Can you try Mull a FOSS Firefox Browser on Mobile?

**Comment by xet7** [comment]
@Ruyeex 

Because it's Firefox based, it should work OK.

Where did you find that browser? Is it at F-Droid, Play Store, Aurora Store, iOS App Store, or somewhere else?

**Comment by xet7** [comment]
@Ruyeex 

If smartphone has 4 GB RAM or less RAM, browser could crash. 6 GB RAM or more works better at smartphone.

For iOS Safari etc, it's possible to make PWA icon https://github.com/wekan/wekan/wiki/PWA

**Comment by Ruyeex** [comment]
> @Ruyeex
> 
> Because it's Firefox based, it should work OK.
> 
> Where did you find that browser? Is it at F-Droid, Play Store, Aurora Store, iOS App Store, or somewhere else?

F-Droid

**Comment by xet7** [comment]
@Ruyeex 

Ok, I'll try that browser.

Some future version of Wekan will support more webbrowsers, load faster, and not have memory leaks. Developing that is in progress.

**Comment by xet7** [comment]
https://wekan.team/app slowness was fixed with this https://github.com/wekan/wekan/wiki/Cron

Mull browser had some security issues, so F-Droid removed it.
