### ISSUE TITLE
Install path (doc) to build custom docker images

### ISSUE THREAD

**Issue by jeanfrancoisgratton** [wekan/wekan#5509]
### Problem description

Proper install path for someone who wants to build custom docker images (alpinelinux prefered, but not absolute). Custom will include, for instance, an hashicorp vault client, and custom-built GO tools, own CA cert and other certs, etc; all is needed are the basic blocks to build my own image, I'll take care of further customizations. Path is required for AMD64, and if possible (not an hard-requirement) for aarch64.

#### Reproduction Steps

n/a

#### Logs

n/a

#### Remarks, comments:

Current doc seems to be a bit outdated (no criticism of mine: I know how hard it can be to keep up), pointing at non-existant filenames, etc.

**Comment by xet7** [comment]
@jeanfrancoisgratton 

I added updated docs to:
- https://github.com/wekan/wekan/wiki/Docker
- https://github.com/wekan/wekan/blob/main/docs/Platforms/FOSS/Docker/Docker.md
