### ISSUE TITLE
Exception while invoking method 'login' RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by LicaiMaker** [wekan/wekan#5529]
### Server Setup Information

Please anonymize info, and do not any of your Wekan board URLs, passwords,
API tokens etc to this public issue.

* Did you test in newest Wekan?: yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: mac os: 14.6.1  
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): source
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): yes
* Node.js Version: v14.19.1
* MongoDB Version: v7.0.12
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? chrome

### Problem description

when i use my oauth2 provider, after click "sign in with oidc" , i got everythings done(including get token and userInfo), but the errors occured, here is the server log:
```
Exception while invoking method 'login' RangeError: Maximum call stack size exceeded
I20240918-17:13:08.819(8)?     at EJSON.clone (packages/ejson/ejson.js:557:15)
I20240918-17:13:08.819(8)?     at Array.map (<anonymous>)
I20240918-17:13:08.819(8)?     at Object.EJSON.clone (packages/ejson/ejson.js:586:14)
I20240918-17:13:08.819(8)?     at packages/ejson/ejson.js:606:22
I20240918-17:13:08.819(8)?     at Array.forEach (<anonymous>)
I20240918-17:13:08.819(8)?     at Object.EJSON.clone (packages/ejson/ejson.js:605:13)
I20240918-17:13:08.819(8)?     at packages/ejson/ejson.js:606:22
I20240918-17:13:08.819(8)?     at Array.forEach (<anonymous>)
I20240918-17:13:08.819(8)?     at Object.EJSON.clone (packages/ejson/ejson.js:605:13)
I20240918-17:13:08.819(8)?     at packages/ejson/ejson.js:606:22
I20240918-17:13:08.819(8)?     at Array.forEach (<anonymous>)
I20240918-17:13:08.819(8)?     at Object.EJSON.clone (packages/ejson/ejson.js:605:13)
I20240918-17:13:08.819(8)?     at packages/ejson/ejson.js:606:22
I20240918-17:13:08.819(8)?     at Array.forEach (<anonymous>)
I20240918-17:13:08.820(8)?     at Object.EJSON.clone (packages/ejson/ejson.js:605:13)
I20240918-17:13:08.820(8)?     at packages/ejson/ejson.js:606:22
I20240918-17:13:08.820(8)?     at Array.forEach (<anonymous>)
I20240918-17:13:08.820(8)?     at Object.EJSON.clone (packages/ejson/ejson.js:605:13)
I20240918-17:13:08.820(8)?     at packages/ejson/ejson.js:606:22
I20240918-17:13:08.820(8)?     at Array.forEach (<anonymous>)
I20240918-17:13:08.820(8)?     at Object.EJSON.clone (packages/ejson/ejson.js:605:13)
I20240918-17:13:08.820(8)?     at packages/ejson/ejson.js:606:22
I20240918-17:13:08.820(8)?  => awaited here:
I20240918-17:13:08.820(8)?     at Function.Promise.await (/Users/caili/.meteor/packages/promise/.0.12.2.undgfo.m3w8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20240918-17:13:08.820(8)?     at packages/accounts-base/accounts_server.js:653:7
I20240918-17:13:08.820(8)?     at /Users/caili/.meteor/packages/promise/.0.12.2.undgfo.m3w8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20240918-17:13:08.820(8)?  => awaited here:
I20240918-17:13:08.820(8)?     at Function.Promise.await (/Users/caili/.meteor/packages/promise/.0.12.2.undgfo.m3w8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20240918-17:13:08.820(8)?     at packages/meteor.js:367:22
I20240918-17:13:08.820(8)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
I20240918-17:13:08.820(8)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
I20240918-17:13:08.820(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
I20240918-17:13:08.820(8)?     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
I20240918-17:13:08.820(8)?     at packages/meteor.js:365:18
I20240918-17:13:08.820(8)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
I20240918-17:13:08.820(8)?     at packages/ddp-server/livedata_server.js:827:46
I20240918-17:13:08.820(8)?     at new Promise (<anonymous>)
I20240918-17:13:08.820(8)?     at Session.method (packages/ddp-server/livedata_server.js:775:23)
I20240918-17:13:08.820(8)?     at packages/ddp-server/livedata_server.js:639:43
```

<img width="504" alt="image" src="https://github.com/user-attachments/assets/545030ee-ba26-440b-9fbf-38ce5acaf59e">

**Comment by xet7** [comment]
@LicaiMaker

"Maximum call stack size exceeded" is a bug in current Meteor 2 based WeKan. It could be because of:

a) Too much Javascript at browserside
b) Javascript memory leak

Some upcoming WeKan version will not have this bug anymore, when it will use less Javascript at browserside.

**Comment by LicaiMaker** [comment]
> > @LicaiMaker
> > "Maximum call stack size exceeded" is a bug in current Meteor 2 based WeKan. It could be because of:
> > a) Too much Javascript at browserside b) Javascript memory leak
> > Some upcoming WeKan version will not have this bug anymore, when it will use less Javascript at browserside.

thanks for replying, after this issue, i suddenly find that my oauth2 provider doesn't provide email field, when i make it a constant(such as : 'xxxx@163.com'), it works! 
```
// packages/wekan-oidc/oidc_server.js
serviceData.email = userinfo[process.env.OAUTH2_EMAIL_MAP] + '@163.com'
```
May be it also works for you ! thanks again!

**Comment by LicaiMaker** [comment]
> @LicaiMaker
> 
> "Maximum call stack size exceeded" is a bug in current Meteor 2 based WeKan. It could be because of:
> 
> a) Too much Javascript at browserside b) Javascript memory leak
> 
> Some upcoming WeKan version will not have this bug anymore, when it will use less Javascript at browserside.

thanks for replying, after this issue, i suddenly find that my oauth2 provider doesn't provide email field, when i make it a constant(such as : '[xxxx@163.com](mailto:xxxx@163.com)'), it works!
```
    // packages/wekan-oidc/oidc_server.js
    serviceData.email = userinfo[process.env.OAUTH2_EMAIL_MAP] + '@163.com'
```
May be it also works for you ! thanks again!
