### ISSUE TITLE
slow on opening and closing card

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#5533]
wekan 7.60
@xet7 

when click on card, it takes a while to open it, and also this causes lists to become unload again.
closing card is also slow...

![20240930_103008](https://github.com/user-attachments/assets/852c4d60-dd2d-4b59-a98d-4be479865ee1)

**Comment by mohammadZahedian** [comment]
at opening it seems card opens twice somehow....

**Comment by joshlupo** [comment]
if a card at the bottom of a long list is clicked, the 7.60 update causes the list to scroll back to top
prior versions did not have this behavior

**Comment by sumiflow** [comment]
if a card at the bottom of a long list is clicked, this also causes the list to scroll back to the top
this behavior did not occur prior to 7.60

**Comment by xet7** [comment]
Hmm. I also notice slowness when using WeKan Roadmap. I'll look at what change caused this.

**Comment by mohammadZahedian** [comment]
> Hmm. I also notice slowness when using WeKan Roadmap. I'll look at what change caused this.

@xet7 

it is very annoying, how can i revert snap version? and how can i stop auto refresh?

**Comment by xet7** [comment]
@mohammadZahedian 

At server, type:
```
sudo snap refresh
```
That will revert back to WeKan Snap Candidate version that is faster opening card.

**Comment by xet7** [comment]
Or alternatively, wait for automatic update.

I select what WeKan version is used at each Snap Channel.
