### ISSUE TITLE
Write log to /var/log/wekan.log instead of /run/Wekan.log by default

### ISSUE THREAD

**Issue by haperu** [wekan/wekan#554]
just for standardisation purposes

Thanks for consideration

**Comment by xet7** [comment]
@haperu

Does Wekan really write log to /run/Wekan.log still ? I did think that Wekan log location on Wekan source install is defined like this:
https://github.com/wekan/wekan-maintainer/blob/master/virtualbox/start-wekan.sh

And docker logs can be viewed with:
```
docker ps
docker logs CONTAINER-ID-HERE
```

**Comment by haperu** [comment]
Hello xet7

Very sorry, I abandonned the inhouse wekan trial. months ago,
TBH, I completely forgot about this report. So, if considered resolved, thanks anyway. :)

**Comment by xet7** [comment]
@haperu 

No problem :)  Wekan has gained more more features like move cards to other board etc meanwhile, there has been lot's of progress since months ago.

**Comment by tromlet** [comment]
Out of curiousity... where DOES WeKan put logs? :S

**Comment by xet7** [comment]
@tromlet 

https://github.com/wekan/wekan/wiki/Logs
