### ISSUE TITLE
Create a "custom" popup from card description

### ISSUE THREAD

**Issue by xator91** [wekan/wekan#5543]
If i would like to insert custom javascript to create a button inside card description and open a popup how can i do it? @xet7

**Comment by xet7** [comment]
@xator91 

Please create github repo to your github account, where you add small demo, how at webpage open:

1. Click top open card that has description
2. Click button to open your popup

There have buttons to open and close those popups.

Use this for those popup layers:

https://unpoly.com/up.layer

I will then add that to future version of WeKan.

**Comment by xet7** [comment]
After that, add link to your GitHub repo to comment of this issue.

**Comment by xator91** [comment]
> @xator91
> 
> Please create new GitHub repo to your GitHub account, where you add small demo, how at webpage open:
> 
> 1. Click top open card that has description
> 2. Click button to open your popup
> 
> There have buttons to open and close those popups.
> 
> Use this for those popup layers:
> 
> https://unpoly.com/up.layer
> 
> I will then add that to future version of WeKan.

Would not be easy to add <script> working on HTML and markdown? I don´t have idea how to work with popup layers

**Comment by xet7** [comment]
@xator91 

For what purpose is that custom popup?

**Comment by xator91** [comment]
> @xator91
> 
> For what purpose is that custom popup?

I have an HTML button inside the description and inside a subtask title. I would like to open a popup onclick, that show a popup with Text or more two button inside clickable. I need it for a custom project, that im trying to do.

**Comment by xator91** [comment]
Would be ok to know, where to insert javascript code, that can work with HTML added inside wekan.

Example:

    <script>
        function showPopup() {
            const popup = document.getElementById('popup');
            popup.style.display = 'block';
        }

        function hidePopup() {
            const popup = document.getElementById('popup');
            popup.style.display = 'none';
        }
    </script>
    <button onclick="showPopup()">Click Me!</button>

    <div id="popup" style="display: none;">
        <p>This is a popup message!</p>
        <button onclick="hidePopup()">
            <a href="https://example.com/link1" style="text-decoration: none; color: inherit;">Button 1</a>
        </button>
        <button onclick="hidePopup()">
            <a href="https://example.com/link2" style="text-decoration: none; color: inherit;">Button 2</a>
        </button>
    </div>

**Comment by xet7** [comment]
@xator91 

For Javascript, add to OnRendered:

https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.js#L131

For HTML, using Jade syntax, add button to cardDescription template, and popup content to some other template at same file:

https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.jade

**Comment by xet7** [comment]
@xator91 

This is Jade template that is used:

https://github.com/mquandalle/meteor-jade

**Comment by xator91** [comment]
> @xator91
> 
> For Javascript, add to OnRendered:
> 
> https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.js#L131
> 
> For HTML, using Jade syntax, add button to cardDescription template, and popup content to some other template at same file:
> 
> https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.jade

So, this is the way if i want the HTML on description HTML and javascript added to insert the popup function to call, right? It should work in this way. Because HTML should be dinamically on description i don´t want a jade template

**Comment by xator91** [comment]
@xet7 Or there are no way to have the popup button and popup itself direct inside the editor? Because i add dinamically content inside the DB. That´s why i need it.

**Comment by xet7** [comment]
@xator91 

Do you mean adding field above card description? In that case, when you add content to database, it is immediately shown at opened card.

**Comment by xet7** [comment]
@xator91 

Editor is here:

https://github.com/wekan/wekan/tree/main/client/components/main

**Comment by xator91** [comment]
> @xator91
> 
> Do you mean adding field above card description? In that case, when you add content to database, it is immediately shown at opened card.

Yes i mean.

This should be on description card:

<button onclick="showPopup()">Click Me!</button>

<div id="popup" style="display: none;">
    <p>This is a popup message!</p>
    <button onclick="hidePopup()">
        <a href="https://example.com/link1" style="text-decoration: none; color: inherit;">Button 1</a>
    </button>
    <button onclick="hidePopup()">
        <a href="https://example.com/link2" style="text-decoration: none; color: inherit;">Button 2</a>
    </button>
</div>


and this javascript on rendered:

<script>
    function showPopup() {
        const popup = document.getElementById('popup');
        popup.style.display = 'block';
    }

    function hidePopup() {
        const popup = document.getElementById('popup');
        popup.style.display = 'none';
    }
</script>

Tried it, but the button do nothing. Doesn´t open the popup.

**Comment by xet7** [comment]
@xator91 

Or do you mean Custom Fields feature?

https://github.com/wekan/wekan/wiki/Custom-Fields

**Comment by xet7** [comment]
@xator91 

With board top buttons Search and Filter, and Filter right SideBar Advanced Filter, it's possible to search and filter Custom Fields.

Custom Fields can be edited at database, and it does realtime updates to boards.

**Comment by xator91** [comment]
> @xator91
> 
> Or do you mean Custom Fields feature?
> 
> https://github.com/wekan/wekan/wiki/Custom-Fields

No i mean, i want to add manually inside card description .

![image](https://github.com/user-attachments/assets/a00f91ec-e3f9-4179-8e18-d3af1f6db74b)

Here i would like to add this html button:

```html
<button onclick="showPopup()">Click Me!</button>

<div id="popup" style="display: none;">
    <p>This is a popup message!</p>
    <button onclick="hidePopup()">
        <a href="https://example.com/link1" style="text-decoration: none; color: inherit;">Button 1</a>
    </button>
    <button onclick="hidePopup()">
        <a href="https://example.com/link2" style="text-decoration: none; color: inherit;">Button 2</a>
    </button>
</div>
``` 

![image](https://github.com/user-attachments/assets/232b0ea6-5a9c-4a73-97eb-f810e5d722a6)


And i want that this Click Me will open a popup on click.

**Comment by xet7** [comment]
@xator91 

Does it need any popup?

You could edit description content directly at database.

**Comment by xator91** [comment]
> @xator91
> 
> Does it need any popup?
> 
> You could edit description content directly at database.

Yes. I need a popup on click, because i want to "ask something" to the user clicking on it. With other 2 button to select inside this popup.

**Comment by xet7** [comment]
@xator91 

Or alternatively, use WeKan API to edit description.

**Comment by xator91** [comment]
> @xator91
> 
> Or alternatively, use WeKan API to edit description.

I dont need to edit description. I need a popup because the people using it clicking on button should select one of two option after click.

**Comment by xet7** [comment]
@xator91 

You could, for example:

1.Add that button to cardDetails.jade

2. Button runs javascript in cardDetails.js where you use JQuery hide/show additional buttons at opened card

3. Answer buttons would run some Javascript function at cardDetails.js

**Comment by xet7** [comment]
@xator91 

Hmm, I think this could be a feature like this:

1. Custom Field Question

2. Dropdown list of answers

3. Each answer can start some action

4. Select where that Question is, is it at Description, or somewhere else

There could be some use cases for this kind of feature.

Or just add to existing Custom Field feature these additional options.

**Comment by xator91** [comment]
> @xator91
> 
> Hmm, I think this could be a feature like this:
> 
> 1. Custom Field Question
> 2. Dropdown list of answers
> 3. Each answer can start some action
> 4. Select where that Question is, is it at Description, or somewhere else
> 
> There could be some use cases for this kind of feature.
> 
> Or just add to existing Custom Field feature these additional options.

I think we are going more complicate that what is. There is not a way to add a simple "onclick" action, adding an external js or jquery popup ?

**Comment by xator91** [comment]
There are no way that i can add an external js file ?

**Comment by xet7** [comment]
@xator91 

Correct. There are no way to add an external js file.

Normal way is to add new feature by sending a pull request.

**Comment by mfilser** [comment]
> There are no way that i can add an external js file ?

Sorry for jumping in.
I am just thinking about security here, otherwise a user could add a javascript like e. g. "hack.js"

**Comment by xet7** [comment]
@mfilser 

Yes, that's correct.

WeKan prevents XSS security issues, running Javascript of any input field, like any popup alert, with Dompurify.

https://github.com/wekan/wekan/blob/main/SECURITY.md#xss

https://wekan.github.io/hall-of-fame/

**Comment by xator91** [comment]
> @xator91
> 
> Correct. There are no way to add an external js file.
> 
> Normal way in WeKan is to add a new feature by sending a pull request.

I can´t even add direct to my source files just for my custom wekan? Because, we running wekan in a local system with firewall, running only in local.

**Comment by xator91** [comment]
> > There are no way that i can add an external js file ?
> 
> Sorry for jumping in. I am just thinking about security here, otherwise a user could add a javascript like e. g. "hack.js"

Thanks, i though this too. But i need to add it just for a custom project running completely in local with some firewall, so nobody could not inject

**Comment by xet7** [comment]
@xator91 

WeKan build scripts like rebuild-wekan.sh download all dependencies from Internet, and creates prebuilt bundle directory, that has about 60 000 files of HTML/CSS/Javascript/images etc.

For offline, it's only needed to have that prebuilt .zip file, Node.js and MongoDB. If you need to modify some files, modify them directly inside that bundle directory. That offline version has all dependencies and files included, it does not require downloading anything from Internet.

https://github.com/wekan/wekan/wiki/Offline

**Comment by xator91** [comment]
> @xator91
> 
> WeKan build scripts like `rebuild-wekan.sh` download all dependencies from Internet, and creates prebuilt bundle directory, that has about 60 000 files of HTML/CSS/Javascript/images etc.
> 
> For offline, it's only needed to have that prebuilt .zip file, Node.js and MongoDB. If you need to modify some files, modify them directly inside that bundle directory. That offline version has all dependencies and files included, it does not require downloading anything from Internet.
> 
> https://github.com/wekan/wekan/wiki/Offline

Ok, i was always using rebuild-wekan.sh. So i can´t simply edit .build/bundle to add or edit js right?

I see that wekan have already popup.js and a file called modal.js there is no way to add a button in HTML inside the description that would use integrated popup/modal that wekan have already?

**Comment by xet7** [comment]
@xator91 

1. Integrated popup is using `popup.Open` https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.js#L288
2. It opens template https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.jade#L627

**Comment by xator91** [comment]
> @xator91
> 
> 1. Integrated popup is using `popup.Open` https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.js#L288
> 2. It opens template https://github.com/wekan/wekan/blob/main/client/components/cards/cardDetails.jade#L627

So the only "simple way" is to create a popup template.

But cause i need that the content of template should be "dinamically" and not a "static template" there are no way that could read that content from HTML description?

I would like to add a new popup.Open and a new template, but the content inside this template, should be "read" from what inside a subtask is or inside a description

**Comment by xet7** [comment]
@xator91 

For example, there is convert to markdown button, that reads Card Description, and converts it to Markdown:

- https://github.com/wekan/wekan/commit/069e2c69b2e00e402628a3123164af257533ddc6#diff-93c856b49f4a87aa14bb33c9d62ca0d3b77d9bd5cbde2610accc4bbf8cd67ab3R57
- https://github.com/wekan/wekan/commit/3cc10c77f99db344d0af3d6d862eb05c909fbf2c

**Comment by xator91** [comment]
> @xator91
> 
> For example, there is convert to markdown button, that reads Card Description, and converts it to Markdown:
> 
> * [069e2c6](https://github.com/wekan/wekan/commit/069e2c69b2e00e402628a3123164af257533ddc6)
> * [3cc10c7](https://github.com/wekan/wekan/commit/3cc10c77f99db344d0af3d6d862eb05c909fbf2c)

Thanks, but i think this would bring me nothing

**Comment by xator91** [comment]
> > @xator91
> > For example, there is convert to markdown button, that reads Card Description, and converts it to Markdown:
> > 
> > * [069e2c6](https://github.com/wekan/wekan/commit/069e2c69b2e00e402628a3123164af257533ddc6)
> > * [3cc10c7](https://github.com/wekan/wekan/commit/3cc10c77f99db344d0af3d6d862eb05c909fbf2c)
> 
> Thanks, but i think this would bring me nothing

No way for my custom release to disable Dompurify?

**Comment by xet7** [comment]
@xator91 

To disable dompurify, comment out this line https://github.com/wekan/wekan/blob/main/packages/markdown/src/template-integration.js#L1, like this:


```
// import DOMPurify from 'dompurify';
```
And from same file, remove this kind of code:
```
DOMPurify.sanitize(
```
Also same for this file https://github.com/wekan/wekan/blob/main/client/components/main/editor.js

This adds back this security vulnerability https://wekan.github.io/hall-of-fame/fieldbleed/

**Comment by xator91** [comment]
> @xator91
> 
> To disable dompurify, comment out this line https://github.com/wekan/wekan/blob/main/packages/markdown/src/template-integration.js#L1, like this:
> 
> ```
> // import DOMPurify from 'dompurify';
> ```
> 
> And from same file, remove this kind of code:
> 
> ```
> DOMPurify.sanitize(
> ```
> 
> Also same for this file https://github.com/wekan/wekan/blob/main/client/components/main/editor.js
> 
> This adds back this security vulnerability https://wekan.github.io/hall-of-fame/fieldbleed/

Tried to disable it in both files but <script> stil not running inside the editor. How is that possible? ahah.

```html
<button id="openPopup">Open Popup</button>

<div id="popup" style="display:none;">
    <p>Popup!</p>
    <button id="closePopup">Close Popup</button>
</div>

<script>
document.getElementById("openPopup").addEventListener("click", function() {
    document.getElementById("popup").style.display = "block";
});

document.getElementById("closePopup").addEventListener("click", function() {
    document.getElementById("popup").style.display = "none";
});
</script>
``` 

![image](https://github.com/user-attachments/assets/e99c2649-43c4-4249-9027-453767a50ace)

Only button appear

**Comment by xet7** [comment]
@xator91 

Maybe remove dompurify package?
```
npm remove dompurify
```
