### ISSUE TITLE
After clicking attachments download button, it takes many seconds before downloading starts

### ISSUE THREAD

**Issue by Ruyeex** [wekan/wekan#5544]
Not sure if it's a bug but it's something I would like to have it.
But it doesn't work when I want to download files suc b as obs. from my PC.
And I can't send file from Android bcs it's limited to PC.

**Comment by xet7** [comment]
@Ruyeex 

What Android version?

What app or webbrowser? Is it from Play Store, F-Droid, or somewhere else?

**Comment by xet7** [comment]
@Ruyeex 

What version of WeKan? Is it your own WeKan server, or is it https://wekan.team/app/ ?

**Comment by Ruyeex** [comment]
> @Ruyeex 
> 
> What version of WeKan? Is it your own WeKan server, or is it https://wekan.team/app/ ?

28.0.0.0
It's the recent version I have?

**Comment by xet7** [comment]
@Ruyeex 

Have installed newest Chrome from Play Store, and set it as your default browser, like described at https://wekan.team/app/ ? If you do that, does file transfer work?

**Comment by Ruyeex** [comment]
> @Ruyeex 
> 
> Have installed newest Chrome from Play Store, and set it as your default browser, like described at https://wekan.team/app/ ? If you do that, does file transfer work?

I don't have Chrome but I use Mull on Mobile and Librewolf on PC.

**Comment by xet7** [comment]
@Ruyeex 

If app does not work, then try any mobile webbrowser with URL https://boards.wekan.team/sign-in

Just a moment, I'll try what webbrowsers work at Android.

**Comment by Ruyeex** [comment]
> @Ruyeex 
> 
> If app does not work, then try any mobile webbrowser with URL https://boards.wekan.team/sign-in
> 
> Just a moment, I'll try what webbrowsers work at Android.

Mull works but the app doesn't?

**Comment by xet7** [comment]
I will update to this wiki page, what webbrowsers work.

https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix

**Comment by xet7** [comment]
@Ruyeex

> Mull works but the app doesn't?

If app requires Chrome, and you don't have Chrome installed and set as default, app does not work.

When you prefer Mull, just use Mull.

**Comment by xet7** [comment]
Having Chrome installed and default makes possible WeKan app to be fullscreen.

**Comment by Ruyeex** [comment]
Is it possible to fix it?

**Comment by xet7** [comment]
@Ruyeex 

Fix what?

**Comment by Ruyeex** [comment]
The download button of the file on the app?

**Comment by xet7** [comment]
@Ruyeex 

I tested. Downloading file works in WeKan app, Mull, and other browsers. Problem is, that when clicking download button, it can take many seconds before file starts downloading. Restarting server did help speed up a little.

Anyway, I try to make download buttor work faster, so that after clicking download button, it would sooner start to download.

**Comment by xet7** [comment]
Fixed, with cron that does every hour:
```
snap stop wekan.wekan

snap start wekan.wekan
```
That's needed currently, because current Meteor 2 WeKan has some memory leaks.
