### ISSUE TITLE
Opening cards moves board up to the initial vertical position

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#5548]
## Issue
Opening cards moves board up to the initial vertical position

### Server Setup Information
* Did you test in newest Wekan?: 7.60.0
* Did you configure root-url correctly so Wekan cards open correctly? Yes.
* Operating System: Linux 3.10.0-1160.119.1.el7.tuxcare.els2.x86_64
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node.js Version: 14.21.4
* MongoDB Version: 5.0.29
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
Safari 18.0.1 (19619.1.26.111.11, 19619)
Chromium Version 129.0.6668.100 (Official Build, ungoogled-chromium) (arm64)

### Problem description
When I open any card (on any board) which you would scroll to, the board position would reset to its initial vertical (or home) position. See screen capture …
![WeKan Move2](https://github.com/user-attachments/assets/a6f54055-e174-413e-bb71-a5d74de385dd)

Thanks for looking into it.

**Comment by r4nc0r** [comment]
We have this problem too, wekan is unusable for us in this state, can you please fix this?

**Comment by Zwergenpunk** [comment]
Please fix it. This is really boggling my mind.

**Comment by xet7** [comment]
@BabyFnord 

Please try WeKan v5.57 bundle. Does it work there?

**Comment by xet7** [comment]
Currenly Snap Candidate has been reverted to v5.57 . It should be automatically installed, or just type `sudo snap refresh` .

For Docker, it's possible change to use image:
```
image: ghcr.io/wekan/wekan:v5.57
```
at here:

https://github.com/wekan/wekan/blob/main/docker-compose.yml#L122

And then do:
```
docker compose stop

docker rm wekan-app

docker compose up -d
```
This does not do any changes to wekan-db mongodb container, all data stays there.

**Comment by xet7** [comment]
After WeKan release v5.57 there were many changes, that I will check, do they need additional changes, like changing version of dependency, etc.

Snap Candidate was reverted to v5.57 because of this #5533

**Comment by BabyFnord** [comment]
@xet7 I'm sorry, WeKan is at v7.60, I can't revert that far to 5.57 😕.

**Comment by xet7** [comment]
@BabyFnord 

Oh sorry. I mean v7.57.

**Comment by BabyFnord** [comment]
@xet7 v7.57 does not move the board 💁🏻‍♂️.

**Comment by xet7** [comment]
@BabyFnord 

Ok, so WeKan v7.57 is working version of WeKan.

**Comment by joshlupo** [comment]
@xet7 just FYI, 7.59 also does not have the vertical position issue. It breaks going from 7.59  to 7.60

**Comment by sumiflow** [comment]
@xet7 just FYI, 7.59 does not have the vertical position issue. It broke going from 7.59 to 7.60
