### ISSUE TITLE
I think that Wekan is sorely missing a textual search feature.

### ISSUE THREAD

**Issue by vavalt** [wekan/wekan#555]
I can't say how ecstatic I was to find out about Wekan, but the one thing I've missed from it has been textual search, something like gmail's. Frankly I was a bit shocked to find it missing. There's already tag filtration, which I think could be integrated into a gmial like search syntax:

```
title:(title substring) #nameoftag1 #nameoftag2 search query words to look for in card description and comments' text.
```

Are there any objections to implementing this?

**Comment by ebxm** [comment]
Isn'it similar to #552 ?

**Comment by xet7** [comment]
Moved to #552
