### ISSUE TITLE
Can't use WeKan properly on my iPhone. 

### ISSUE THREAD

**Issue by cnah66** [wekan/wekan#5551]
I installed the latest version of WeKan using Docker, but I can't use WeKan properly on my iPhone. Whenever I try to scroll through the page, I end up dragging a card to the wrong place. I wonder if I'm using it incorrectly?

**Comment by xet7** [comment]
Try WeKan v7.61

**Comment by xet7** [comment]
Update like this, but for v7.61:

https://github.com/wekan/wekan/issues/5548#issuecomment-2426386480
