### ISSUE TITLE
Card delete and templates don't work since upgrading to 7.61.0

### ISSUE THREAD

**Issue by CaptainPackers** [wekan/wekan#5559]
Since upgrading my WeKan snap to v. 7.61.0, I cannot delete cards anymore. The option seems to be gone. 

Also, templates are not working right. Wekan seems to be creating links from new cards to the card template instead of copying the body of the template card into the new card. When I click on the card after creating it with a template, WeKan opens the template card on the template board.

**Comment by xet7** [comment]
@CaptainPackers

> Since upgrading my WeKan snap to v. 7.61.0, I cannot delete cards anymore. The option seems to be gone.

BoardAdmin can delete card, by opening card, and at hamburger menu / More / Delete. Normal user can not delete card, that would cause data loss. Usually card is archived, or restored from archive.

> Also, templates are not working right

Does this help? https://github.com/wekan/wekan/wiki/Templates

**Comment by CaptainPackers** [comment]
I can't download attachments either. I get this:
This site can’t be reached
127.0.0.1 refused to connect.
I'm not using 127.0.0.1 as my ip addess for Wekan.

**Comment by CaptainPackers** [comment]
OK, found the delete option

**Comment by CaptainPackers** [comment]
I've already looked at https://github.com/wekan/wekan/wiki/Templates. Followed the guidelines. Behavior is still to open card template, not copy it into new card.

**Comment by CaptainPackers** [comment]
I think I'm going to roll back to previous version as I'm having to many issues with this one. I can't deal with all this in my production environment.

**Comment by xet7** [comment]
For attachments, root-url needs to have correct IP address:

https://github.com/wekan/wekan/wiki/Settings

Not localhost, or 127.0.0.1

If attachments are from migrating from from 6.09 to 7.x, it needs additional changes to get attachments visible.  https://github.com/wekan/wekan/discussions/5557#discussioncomment-11135860

For Snap Stable 6.09, it's better to wait when there will be working automatic upgrade to newest 7.x , I'm developing fixes related to that upgrade.

**Comment by CaptainPackers** [comment]
Thanks. I will wait for the automatic upgrade.
