### ISSUE TITLE
HTML code entered in card description or comments is not escaped

### ISSUE THREAD

**Issue by ProCycleDev** [wekan/wekan#556]
Any html code that is entered in a card's description or comments is not escaped and instead is parsed by the browser. The card title escapes html code properly.
This allows external resources to be embeded in the page instead of attached, including iframes. This also makes using wekan to track development of html code very difficult as everything entered has to be manually escaped.

If this is intentional then please provide an option to turn code escaping on and off.

**Comment by xet7** [comment]
Moved to #801
