### ISSUE TITLE
card actions menu stays open after moving a card

### ISSUE THREAD

**Issue by CaptainPackers** [wekan/wekan#5561]
I don't think this is an intended action, so I'm reporting it as a bug.

After I move a card, the card actions menu remains open. 
![Capture](https://github.com/user-attachments/assets/e2960944-2ed3-4db9-8ac4-017f30b4eb17)

This is for a snap version of Wekan.
Here is the pertinent version/system information:
![image](https://github.com/user-attachments/assets/4f0dafa7-3c8f-4c6e-bb7d-4ea24e0ae530)

**Comment by mfilser** [comment]
It's not a bug, it's a feature (intended)
