### ISSUE TITLE
The label is not creating on the card

### ISSUE THREAD

**Issue by nikalasmd** [wekan/wekan#5564]
The label is not creating on the card
@xet7 any idea
![label](https://github.com/user-attachments/assets/469bb911-8b95-430e-b070-8c49c741ea8e)
![image](https://github.com/user-attachments/assets/36ff82a8-ce0a-44b6-816f-28a7b8608e9c)

**Comment by nikalasmd** [comment]
@xet7 what do you think about this?

**Comment by xet7** [comment]
@nikalasmd 

Please upgrade to newest WeKan.

Have you set root-url ? https://github.com/wekan/wekan/wiki/Settings

For example, to your WeKan server IP address:
```
sudo snap set wekan root-url='http://192.168.0.50'

sudo snap set wekan port='80'
```
Or, if you have Caddy/Nginx/Apache to provide SSL/TLS, proxying to for example port 5000:
```
sudo snap set wekan root-url='https://wekan.example.com'

sudo snap set wekan port='5000'
```

**Comment by xet7** [comment]
@nikalasmd 

Are you using WeKan only at internal network?

Or is it installed to server where is ports 80 and 443 open to Internet?

**Comment by nikalasmd** [comment]
@xet7 
at the moment i use only internal(via ip or dns name and port 80 or 443)

**Comment by xet7** [comment]
@nikalasmd 

Ok. Check what is WeKan server IP address is:
```
ip address | grep 192
```
Then, if it's for example 192.168.0.50, change below your correct IP address:
```
sudo snap set wekan caddy-enabled='false'

sudo systemctl stop snap.wekan.caddy

sudo systemctl disable snap.wekan.caddy

sudo snap set wekan root-url='http://192.168.0.50'

sudo snap set wekan port='80'
```
Then login to WeKan at http://192.168.0.50/sign-in

And try to add label. For added labels, you can click label, to add it to card, so it becomes a little bigger size.

**Comment by xet7** [comment]
Also, change to candidate channel:
```
sudo snap refresh wekan --channel=latest/candidate --amend
```

**Comment by nikalasmd** [comment]
The problem is not solved

root@debian:/var/snap/wekan# sudo snap get wekan caddy-enabled
false

root@debian:/var/snap/wekan# sudo systemctl status snap.wekan.caddy
○ snap.wekan.caddy.service - Service for snap application wekan.caddy
     Loaded: loaded (/etc/systemd/system/snap.wekan.caddy.service; disabled; preset: enabled)
     Active: inactive (dead)

Nov 20 15:27:35 debian wekan.caddy[585717]: Activating privacy features... done.
Nov 20 15:27:35 debian wekan.caddy[585717]: Serving HTTPS on port 443
Nov 20 15:27:35 debian wekan.caddy[585717]: https://wekan.local
Nov 20 15:27:35 debian wekan.caddy[585717]: Serving HTTP on port 80
Nov 20 15:27:35 debian wekan.caddy[585717]: http://192.168.0.95
Nov 20 15:27:35 debian wekan.caddy[585717]: http://wekan.local
Nov 20 16:05:00 debian systemd[1]: Stopping snap.wekan.caddy.service - Service for snap application wekan.caddy...
Nov 20 16:05:00 debian systemd[1]: snap.wekan.caddy.service: Deactivated successfully.
Nov 20 16:05:00 debian systemd[1]: Stopped snap.wekan.caddy.service - Service for snap application wekan.caddy.
Nov 20 16:05:00 debian systemd[1]: snap.wekan.caddy.service: Consumed 2.246s CPU time.

root@debian:/var/snap/wekan# sudo snap get wekan root-url
http://192.168.0.95

root@debian:/var/snap/wekan# sudo snap get wekan port
80

**Comment by nikalasmd** [comment]
root@debian:/var/snap/wekan# sudo systemctl enable snap.wekan.caddy
Created symlink /etc/systemd/system/multi-user.target.wants/snap.wekan.caddy.service → /etc/systemd/system/snap.wekan.caddy.service.

root@debian:/var/snap/wekan# sudo systemctl start snap.wekan.caddy

root@debian:/var/snap/wekan# sudo systemctl status snap.wekan.caddy
○ snap.wekan.caddy.service - Service for snap application wekan.caddy
     Loaded: loaded (/etc/systemd/system/snap.wekan.caddy.service; disabled; preset: enabled)
     Active: inactive (dead)

Nov 20 16:15:41 debian wekan.caddy[594111]: SAML_LOCAL_PROFILE_MATCH_ATTRIBUTE= (default value)
Nov 20 16:15:41 debian wekan.caddy[594111]: SAML_ATTRIBUTES= (default value)
Nov 20 16:15:41 debian wekan.caddy[594111]: ORACLE_OIM_ENABLED=false (default value)
Nov 20 16:15:41 debian wekan.caddy[594111]: RESULTS_PER_PAGE= (default value)
Nov 20 16:15:41 debian wekan.caddy[594111]: WAIT_SPINNER=Bounce (default value)
Nov 20 16:15:41 debian wekan.caddy[594111]: NODE_OPTIONS= (default value)
Nov 20 16:15:41 debian wekan.caddy[594111]: caddy is disabled. Stop service
Nov 20 16:15:41 debian systemd[1]: Stopping snap.wekan.caddy.service - Service for snap application wekan.caddy...
Nov 20 16:15:41 debian systemd[1]: snap.wekan.caddy.service: Deactivated successfully.
Nov 20 16:15:41 debian systemd[1]: Stopped snap.wekan.caddy.service - Service for snap application wekan.caddy.

**Comment by xet7** [comment]
@nikalasmd 

You do not need Caddy at local network. WeKan Snap has old Caddy. I tried to write you above the commands to disable caddy.

**Comment by xet7** [comment]
@nikalasmd 

Also look what is running at those ports:
```
sudo apt-get -y install net-tools

sudo netstat -plant | grep :80
```
Also see what is at logs:
```
sudo snap logs wekan
```

**Comment by xet7** [comment]
If you have other webservers, disable them, and then start WeKan:

```
sudo systemctl stop apache2

sudo systemctl disable apache2

sudo systemctl stop nginx

sudo systemctl disable nginx
```

**Comment by nikalasmd** [comment]
root@debian:/var/snap/wekan# sudo snap start wekan
Started.

root@debian:/var/snap/wekan# sudo snap enable wekan
error: cannot enable "wekan": snap "wekan" already enabled

root@debian:/var/snap/wekan# sudo netstat -plant | grep :80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      592217/node
tcp        0      0 192.168.0.95:80         192.168.0.4:57244       ESTABLISHED 592217/node
tcp        0      0 192.168.0.95:48946      151.101.2.132:80        TIME_WAIT   -
tcp        0      0 192.168.0.95:80         192.168.0.36:20203      ESTABLISHED 592217/node
tcp        0      0 192.168.0.95:80         192.168.0.36:21165      ESTABLISHED 592217/node

root@debian:/var/snap/wekan# sudo snap logs wekan
2024-11-20T16:23:00-05:00 wekan.wekan[592217]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Finished \"LDAP_Sync\".","time":{"$date":1732137780380},"level":"info"}
2024-11-20T16:23:10-05:00 wekan.wekan[592217]: {"line":"146","file":"ldap.js","message":"Idle","time":{"$date":1732137790372},"level":"info"}
2024-11-20T16:23:10-05:00 wekan.wekan[592217]: {"line":"595","file":"ldap.js","message":"Disconecting","time":{"$date":1732137790373},"level":"info"}
2024-11-20T16:23:10-05:00 wekan.wekan[592217]: {"line":"151","file":"ldap.js","message":"Closed","time":{"$date":1732137790374},"level":"info"}

**Comment by xet7** [comment]
@nikalasmd 

Those are normal messages.

When you login with webbrowser at http://192.168.0.95/sign-in , does creating new label work?

**Comment by nikalasmd** [comment]
@xet7 
root@debian:/var/snap/wekan# sudo snap list
Name    Version             Rev    Tracking          Publisher   Notes
core    16-2.61.4-20240607  17200  latest/stable     canonical✓  core
core20  20240911            2434   latest/stable     canonical✓  base
wekan   7.65                3010   latest/candidate  xet7        -

**Comment by xet7** [comment]
@nikalasmd 

Try to create new board. Can you add card and label at new board?

Maybe you are not BoardAdmin at that current board.

**Comment by nikalasmd** [comment]
@xet7 
![image](https://github.com/user-attachments/assets/7c0ba633-cda9-43ab-beff-9a12e7bc6674)

**Comment by xet7** [comment]
Click that red label once, it will be visible at card.

**Comment by nikalasmd** [comment]
@xet7 
If I am not the board administrator, I cannot add a new label?
Can I give permissions?

**Comment by xet7** [comment]
@nikalasmd 

If you have access to Admin Panel, you can go to People / People, and there impersonate some existing BoardAdmin, and as that BoardAdmin click at right sidebar avatar your permissions to BoardAdmin.

**Comment by xet7** [comment]
@nikalasmd 

Alternatively, ask existing BoardAdmin to give you BoardAdmin rights, by clicking your right sidebar avatar.

**Comment by nikalasmd** [comment]
@xet7 
Why only  admin permissions can add label ?
Why can't normal permissions do this? because this dashboard is used every day.

**Comment by xet7** [comment]
@nikalasmd 

Hmm? I'll check how permissions work, and try to fix those.

**Comment by mfilser** [comment]
I think there are use cases where only admin's should be able to add new labels ...

**Comment by xet7** [comment]
@mfilser 

Yes, because changing labels can easily cause some damage.

**Comment by xet7** [comment]
Anyway, I got confused when I tried to make possible normal user adding and editing labels. There was some code I added previously to make it possible, but it seems it does not work.

I think I'll try to write some WeKan prototype with simpler code.
