### ISSUE TITLE
Clicking outside of Add Card box causes loss of entered text

### ISSUE THREAD

**Issue by ProCycleDev** [wekan/wekan#558]
When adding a new card if you click outside of the containing form element the box closes and you lose your information. This is especially bad because if you miss the save button by 1 pixel on the bottom it will trigger a close.

I tested the behavior for adding card comments and while the window does close, it saves what you entered so you can come back to it if you mistakenly clicked away.

When adding cards it would help if it retains the entered information in the event you click away, or disabling the auto-close functionality when adding cards.

**Comment by xet7** [comment]
Moved to #466
