### ISSUE TITLE
Bug: Sidebar activities transparent background

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5585]
@NadavTasher 

Sidebar activities has transparent background. This happens at:

- Safari
- Firefox
- I'll test other browsers soon.

<img width="824" alt="wekan-sidebar" src="https://github.com/user-attachments/assets/d82ba662-733b-4142-b90f-f9c2466afe99">

**Comment by NadavTasher** [comment]
Oh no, I can fix this!
I'll take a look at it ASAP.

**Comment by xet7** [comment]
@NadavTasher 

Please wait, I'm making new release, reverting some changes. After that, you can send PRs for other things, that are not related to current reverted changes.

**Comment by NadavTasher** [comment]
@xet7 
What do you mean?

**Comment by xet7** [comment]
@NadavTasher 

That you would not send again those changes related to scrollbar, sidebar and list width.

You can send PRs related to anything else.

**Comment by xet7** [comment]
@NadavTasher 

Correction: You can send those changes again, but please keep scrollbars visible, and try to fix #5585 . Thanks!

**Comment by NadavTasher** [comment]
Will do 😀

**Comment by NadavTasher** [comment]
@xet7 
This can be safely closed :)
