### ISSUE TITLE
Serious issue causing data loss

### ISSUE THREAD

**Issue by vavalt** [wekan/wekan#559]
I made changes and then my internet stopped working, and so I refreshed my browser. The internet was still not working and didn't reset until about 15 minutes later. When I reloaded by Wekan board my changes were gone. I shouldn't have been able to refresh without a prompt while there were unsynced changes. If Gmail failed to transmit changes back to the server, it won't let you refresh or close your tab.

Wekan should be no different. I would even propose a local-storage sync-queue so that if the page is refreshed there can be a seamless resumption of change syncing.

I propose this as a serious data fidelity issue. Changes are represented as stored on the boards, when they actually aren't. It's very misleading and dangerous.

**Comment by ForNeVeR** [comment]
That's linked with #539 and maybe #466.

**Comment by makufiru** [comment]
Seems like it could be a modification of the 'Unsaved Edits' lib to also store a copy in localStorage.

**Comment by xet7** [comment]
Moved to #466
