### ISSUE TITLE
list width too long for long titles

### ISSUE THREAD

**Issue by joshlupo** [wekan/wekan#5593]
### Server Setup

* Did you test in newest Wekan?: **yes**
* Hosted via pikapods.com
* What webbrowser version are you using?: **Brave**

### Problem description
- Lists with long titles are too wide after PR #5581 in my opinion
- It's not a nice experience to read a paragraph of text in one line across a wide monitor.  It doesn't look much like a "card" then.  The version of Wekan before this PR handled this nicer in my opinion.  Lists had a fixed width that was much smaller, which made them easier to read, look more like cards, and have a more consistent viewing experience across different boards that each have a different number of lists.
![image](https://github.com/user-attachments/assets/ee7da88e-272a-48c5-b906-0444f4bb8fdc)

### Reproduction Steps
- Create any board with a single list and card that has a long title.

### Recommendations
- My choice would be to revert the change. If others don't agree then I suggest adding a new option to set the **Max** Width, in addition to the Min Width option.
![image](https://github.com/user-attachments/assets/afa391c2-21c6-40e8-b843-dfb54ba01e87)

**Comment by xet7** [comment]
@NadavTasher 

Please send PR, where default is previous list width, and optional is fill up space evenly. Thanks!

**Comment by NadavTasher** [comment]
I will get to that today / tomorrow.

**Comment by NadavTasher** [comment]
@joshlupo 
This happens only when you have just one list.
If you have more then one list it handles them great.

@xet7 WDYT?

**Comment by xet7** [comment]
@NadavTasher 

Every list should have that original small width by default. Anything else is optional.

**Comment by NadavTasher** [comment]
Okay. I will work on that ASAP.

**Comment by NadavTasher** [comment]
I will open a PR soon.

**Comment by computrav** [comment]
+1 on this request, however, some thoughts (all IMO of course!):
( @NadavTasher if you are working on this )

1. Both a MIN width and MAX width should be able to be defined for list widths. For MAX, it could be definable in both pixels or a special value of "auto max width" (but a better name) -- meaning it would act like it does now where the list width = total width divided by the number of lists. I still think a default of a fixed pixel width is more likely to be desired by users, however. Bare minimum though, having both MIN and MAX in pixels would be MVP.
2. Each value should have sensible defaults - e.g., 270px for default MIN width, but also a default MAX width, perhaps something around 400px.
3. These settings should be able to be defined both at the application level (via Admin panel), but also per-board (like min-width is now).

I don't think that relying on there being 1, 2, 3, or X lists on the board is a good user experience qualifier for whether it looks good or bad by default, but instead it should look great regardless of the number of lists. By allowing the MAX to be in pixels or "auto max width", it covers all possible user preferences for how lists appear.

**Comment by NadavTasher** [comment]
Agree with most points.

I think making it configurable through the Admin panel is a waste of time :)

I am still working on it - have just been a little busy with work.
Hopefully will get it done till Friday.

**Comment by computrav** [comment]
As a phase 1, agree. Perhaps at least allowing a config setting then + via ENV vars if using Docker. I'm happy to test as-needed, just LMK.

**Comment by NadavTasher** [comment]
Have opened a PR addressing this issue:
https://github.com/wekan/wekan/pull/5607

**Comment by NadavTasher** [comment]
I think this issue can be closed.
