### ISSUE TITLE
exodark comments invisible

### ISSUE THREAD

**Issue by joshlupo** [wekan/wekan#5594]
### Server Setup

* Did you test in newest Wekan?: **yes**
* Hosted via pikapods.com
* What webbrowser version are you using?: **Brave**

### Problem description
- Comments in the exodark theme are effectiviely invisible because they are white text on a white background.
- A month or so ago this wasn't an issue, so a recent change must have broken it but I'm not sure which one.
![image](https://github.com/user-attachments/assets/b72fb5bb-a95e-436e-b086-765099b10a81)
![image](https://github.com/user-attachments/assets/2e6c30b7-567e-4249-bb8c-0f67ea4714e1)

### Reproduction Steps
- Set any board's theme to exodark and add a comment.

**Comment by xet7** [comment]
@TheExo @walster001

Do you have time to send PR to fix this ? You are most familiar with this theme.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5595 . Thanks to @walster001 !
