### ISSUE TITLE
Wekan OAUTH2 keycloak problem

### ISSUE THREAD

**Issue by Blaumilch** [wekan/wekan#5599]
### Issue

I configured keycloak and wekan the way it is described but the login with OAUTH2 doesn't work for me

Server Setup Information:

- Wekan version: 7.63 ( wekanteam/wekan:v7.63)
- Oauth & keycloak config:

>OAUTH2_ENABLED=true 
>OAUTH2_LOGIN_STYLE=redirect
>OAUTH2_CLIENT_ID=wekan
>OAUTH2_SECRET=xxx-xxx-xxx-xxx-xxx
>OAUTH2_SERVER_URL=http://keycloak.xxx.com/auth
>OAUTH2_AUTH_ENDPOINT=/realms/xxx/protocol/openid-connect/auth
>OAUTH2_USERINFO_ENDPOINT=/realms/xxx/protocol/openid-connect/userinfo
>OAUTH2_TOKEN_ENDPOINT=/realms/xxx/protocol/openid-connect/token
>OAUTH2_FULLNAME_MAP=name
>OAUTH2_REQUEST_PERMISSIONS=openid profile email
>OAUTH2_USERNAME_MAP=email
>OAUTH2_ID_MAP=email

Problem description:

> WRN Error in OAuth Server: Failed to fetch userinfo from OIDC http://keycloak.xxx.com/auth/realms/xxx/protocol/openid-connect/userinfo: failed [401] | line=406 file=oauth_server.js

I didn't import the entire [realm-export.zip](https://wekan.github.io/keycloak/realm-export.zip) from https://github.com/wekan/wekan/wiki/Keycloak but the keycloak setup is:

>client protocol: openid-connect
>Access type: confidential
>Root URL: https://wekan.xxx.com
>Valid redirect URL: https://wekan.xxx.com/_oauth/oidc
>base URL: https://wekan.xxx.com
>admin URL: https://wekan.xxx.com
>Web-Origin: https://wekan.xxx.com/* ; *

**Comment by xet7** [comment]
@malteprang 

What do you think? You sent some Keycloak changes recentyly at https://github.com/wekan/wekan/pull/5597

Should something be fixed at environment variables, wiki etc? https://github.com/wekan/wekan/wiki/Keycloak

**Comment by malteprang** [comment]
@Blaumilch 
please try the Web-Origin in the keyloak client config without trailing slash. 
E.g. https://wekan.xxx.com
Have you already turned on user events in the keycloak realm settings?
There should be a specific error message when a client is not allowed to login.
@xet7 
The wiki looks fine. I didn't try snaps but the required environment variables look fine.

**Comment by Blaumilch** [comment]
@xet7
@malteprang  
I also have this error  https://github.com/wekan/wekan/issues/3299 with my certificate so I had to use http in OAUTH2 Server URL, I don't know if these issues are connected

**Comment by Blaumilch** [comment]
@xet7
@malteprang
After further testing it is connected to https://github.com/wekan/wekan/issues/3299 . I can't set oauth2 userinfo endpoint in wekan to https because wekan has a problem with the self signed certificate but keycloak will only allow to send data to userinfo endpoint with https. Is there a workaround to this?

**Comment by xet7** [comment]
@Blaumilch 

Maybe try to get valid signed sertificate for your IP address for your userinfo endpoint with Caddy server? 
- https://caddyserver.com
- https://caddyserver.com/docs/automatic-https#local-https
- https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

**Comment by Blaumilch** [comment]
The certificate was valid, I managed to fix the error by following https://github.com/wekan/wekan/issues/1905 .
