### ISSUE TITLE
two translation for persian language 

### ISSUE THREAD

**Issue by mohammadZahedian** [wekan/wekan#5601]
![image](https://github.com/user-attachments/assets/a2ad0bf0-955a-4214-9b86-b0d3d7f31f2f)

this two translation are the same ( must be same )
must be merged.

**Comment by xet7** [comment]
I don't know what it is for each language. There are languages, with language names, and similar languages for different countries. One language can be different at different countries. For example, there is English USA, English UK, etc. It depends on translators, what they translate.
