### ISSUE TITLE
Autosave changes

### ISSUE THREAD

**Issue by zeigerpuppy** [wekan/wekan#561]
Autosaving changes makes sense in this sort of application,
It reduces clicks significantly,

For instance, clicking on the heading of a card and changing the text should autosave if the user clicks somewhere else.

The same should apply for comments and descriptions.

I am constantly finding myself entering items twice due to forgetting to press save!

**Comment by makufiru** [comment]
I think this could cause a lot of accidents in regards to changing data that someone didn't mean to.

This is why they introduced the unsaved edits feature in the first place.  If you're forgetting to save, try "ctrl+Enter" to submit that field, thus saving it.
