### ISSUE TITLE
Horizontal dragscroll broken after list-width/scroll updates. 

### ISSUE THREAD

**Issue by walster001** [wekan/wekan#5613]
Tested in newest WeKan version 7.72

Hey team! So, the horizontal dragscroll appears to be broken when you have super long lists going to the right, you are unable to dragscroll horizontally only vertically. 

Thinking this may have to do with recent changes in regards to list limiting in swimlanes. 

@NadavTasher wondering whether you may have a idea of the code that could be causing the issue?
Also, awesome to see all your commits! Love the list auto-width/min-max feature you've implemented.

Grateful for any thoughts. I'll keep also digging into it to see what I can find myself but many hands make light work 😄

**Comment by NadavTasher** [comment]
Oh no...
I'll check this later today.

**Comment by walster001** [comment]
Hey mate! Appreciate your quick response. 
I am also using google chrome, and you are right dragscroll works as expected on the swimlanes feature. 

However when you have list view enabled for boards it breaks the ability to scroll left/right :) not sure what might be causing it still yet but grateful for any thoughts you may have

**Comment by NadavTasher** [comment]
Ok, will check later :)

**Comment by NadavTasher** [comment]
@walster001 

From what I have observed, this is **NOT** a bug caused by recent features. (You can observe the same behaviour in `v7.68`)

Regardless, I have opened a PR (https://github.com/wekan/wekan/pull/5618) that fixes this issue **and** another issue I found during testing 😄
