### ISSUE TITLE
 I would like to install the cpanel?

### ISSUE THREAD

**Issue by davicolet** [wekan/wekan#562]
Hello , I have a hosting and only have access to cpanel . I wonder if would like to install for it. Since ja grateful

Await response .

**Comment by ocdtrekkie** [comment]
Generally, if you only have access to cPanel (meaning you use shared or managed hosting), you aren't able to run Wekan. Wekan uses a platform called Meteor that isn't installed by default on most hosting platforms.

You could always ask your host if they support Meteor or would install Meteor for you, but more than likely, you'll need to get a VPS or dedicated server to run Wekan.

**Comment by davicolet** [comment]
Hm . ok was thinking of changing my server for a vps , one more reason now . haha

Thanks for the info

**Comment by beppe9000** [comment]
cPanel has recently introduced the possibility of hosting node.js apps

**Comment by tomkpt** [comment]
YES, you are right ... "cPanel has recently introduced the possibility of hosting node.js apps with version 80."

Please guide us all .. How to Install WEKAN on CPANEL WHM 

PLEASE PLEASE ... THANKs

**Comment by beppe9000** [comment]
From what I've seen cpanel expects apps to be fully compliant of phusion passenger [guidelines](https://github.com/phusion/passenger/wiki/Phusion-Passenger:-Node.js-tutorial#prepare-your-app).

**Comment by tomkpt** [comment]
Thank you Bepee9000. Im not that much technical person.

In nutshell, can you please tell, is it possible to run WEKAN on CPANEL VPS or Dedicated Server (having ROOT Access)

Thanks again :)

**Comment by beppe9000** [comment]
Me too am very ignorant on passenger. imho the more practical way is to bypass cpanel probably. so you should follow the install steps for [regular linux](https://github.com/wekan/wekan/wiki/Source) and use only cpanel to edit the proxy setting for the virtual host associated with the wekan domain.

**Comment by xet7** [comment]
@davicolet 

Please use Snap that has automatic updates. There is very often security updates to Node.js etc.
https://github.com/wekan/wekan-snap/wiki/Install

Snap works on bare metal, KVM/XEN/HyperV/VirtualBox/VMware.

**Comment by beppe9000** [comment]
is snapd suitable for hosting "production" apps ? i.e. on a centos webserver with cpanel installed?
