### ISSUE TITLE
Style Cleandark: Font color of comments not readable 

### ISSUE THREAD

**Issue by Germardies** [wekan/wekan#5625]
Good morning everyone,

I have found an error in the board color /style Exodark.
When I select Exodark I cannot read the comments in the map.
The background of the written comment is white. But unfortunately the font color is also white.
You have to select the text with the mouse to be able to read the text.

**Comment by xet7** [comment]
@walster001 

Do you have time to look at this? I think this happens at Cleandark theme.

I tried to add this to `wekan/client/components/boards/boardColors.css` but it does not work:

```
.board-color-cleandark .card-details .board-canvas .card-details-canvas .card-details-left .comment .comment-desc .comment-text {
  color:#000;
}
```
