### ISSUE TITLE
"esc" doesn't work

### ISSUE THREAD

**Issue by mimZD** [wekan/wekan#5631]
@xet7 
when your are adding a card "esc" doesn't work to cancel adding card

**Comment by xet7** [comment]
@mimZD 

I don't know, has it ever worked?

When shortcuts are enabled, Esc closes popup windows only, I think.

Esc currently does not cancel adding card.

**Comment by xet7** [comment]
@mimZD 

It looks like Esc cancels adding a card at Trello. But not in WeKan yet.

**Comment by xet7** [comment]
@mimZD 

Also, it looks like Esc closes right sidebar at Wekan, but not in Trello.

**Comment by NadavTasher** [comment]
Esc works perfectly.
There is no need to change anything.

**Comment by xet7** [comment]
@NadavTasher 

No, Esc does not work perfectly.

When keyboard shortcuts are enabled, after adding new card, Esc should cancel adding new card, like it does cancel at Trello. It does not work in WeKan.

**Comment by NadavTasher** [comment]
I will check this as soon as I can.
