### ISSUE TITLE
API call to create new label dies with empty reply from server

### ISSUE THREAD

**Issue by kjgcoop** [wekan/wekan#5632]
First off, thanks for making a great piece of software! 

### Server Setup Information

* Did you test in newest Wekan?: It's the latest docker image: 7.74.0
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Ubuntu
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): I'm not sure how the docker image does this. 
* Node.js Version: I'm not sure
* MongoDB Version: it's using the image mongo:6
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox but I'm not having a problem in the browser.

### Problem description
When I use PHP (using Guzzle) to run a PUT request to /api/boards/{board}/labels, it takes a long time but eventually I get an error, "cURL error 52: Empty reply from server" This also happens when I run a request from Postman or cURL from the command line.

#### Reproduction Steps
I'll offer the code. First:
`        $result = json_decode($this->call('boards/'.$this->projectId.'/labels', 'PUT', $body));`

The salient part of $this->call():
```
                $client = new Client(['headers' => $headers]);

                $response = $client->$verb(self::WEKAN_BASE.$path, [
                    GuzzleHttp\RequestOptions::JSON => $body
                ]);
```

I can be reasonably certain I'm getting the API key, etc, right because I'm not having problems with other API calls. 

#### Logs
When I run `docker compose up` but don't detach it, it outputs logs. It doesn't issue any remarks when I run this request (whether by PHP, cURL or Postman). 

When I run `sudo docker logs wekan-app`, it just has one line which doesn't seem topical:
`{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Sun Dec 29 2024 00:00:10 GMT-0800 (Pacific Standard Time)","time":{"$date":1735459211930},"level":"info"}`

Any help would be much appreciated! Thank you!

**Comment by kjgcoop** [comment]
I see this, but the solution is in Python: https://github.com/wekan/wekan/issues/2793

I looked at the Python code and - realizing I'm not fluent in python - at a glance it looks like it's doing the same thing as my PHP code.

**Comment by xet7** [comment]
@kjgcoop 

It works for me.

Steps:

1. Add new label to board
2. Look with DBGate MongoDB GUI, what are BOARDID LISTID CARDID LABELID
3. Run api.py that does login to API with username and password, and gets Bearer Token https://github.com/wekan/wekan/blob/main/api.py#L79-L83
4. Add label with that bearer token https://github.com/wekan/wekan/blob/main/api.py#L303-L319

```
./api.py addlabel BOARDID LISTID CARDID LABELID

./api.py addlabel QstPcSxLhRXmdyPyX 4t7zwLqwefS6Bg6bn 9q5XKdXatMAxDs2tx Mnqn8y
```

**Comment by xet7** [comment]
@kjgcoop 

You can also use PHP to run that Python api.py code, like this: 

https://github.com/wekan/webhook/blob/main/public/index.php#L46

**Comment by kjgcoop** [comment]
Awesome, thanks!

**Comment by kjgcoop** [comment]
I was trying to add the label to the board, as opposed to the card. Still, that's working for me from the python script, so thank you.

I'm going to leave a little more detail for the folks who come after me in the interest of sparing them a little Googling:
1. Download https://github.com/wekan/wekan/blob/main/api.py. It doesn't have to be run from the Wekan server, you can run it from any computer that can communicate with your Wekan server. 
2. Fill in the values on line 79 through 83. 
3. I got the board ID by checking the URL of my board in the browser. The URL is in the format [host]/b/[board ID]/[fancy name]
4. If you're trying to add a label to a card, see @xet7's instructions above.
5. If you're trying to add a label to a board, you'll need to specify the color name. Your choices are on line 48 of api.py, https://github.com/wekan/wekan/blob/main/api.py#L47C1-L48C34
6. Run the following in the same directory where you saved api.py: `python3 api.py createlabel [board ID] yellow 'CLI label'` You may be able to run it with just the command`python` as opposed to `python3` like I did.

Hope this helps somebody.
