### ISSUE TITLE
Allow additional label colors

### ISSUE THREAD

**Issue by brylie** [wekan/wekan#565]
Board label colors seem to be [hard coded to only a few](https://github.com/wekan/wekan/blob/devel/models/boards.js#L42). There may be cases where users want/need more color options. Consider how to allow more, possibly custom, label colors.
# Resources
- D3.js [default color palettes](http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d)

**Comment by brylie** [comment]
As an aside, one challenge that arises with label text is finding contrasting color. There could be a function that compares label color luminance with white and grey and then selects a font color to maximize contrast.

**Comment by klischka** [comment]
I support this - as a user I really want and need more color options for labels.

**Comment by xet7** [comment]
Moved to #457
