### ISSUE TITLE
Internal server error  during user registration

### ISSUE THREAD

**Issue by Issam2204** [wekan/wekan#568]
During user registration I get an internal server error:
![screenshot from 2016-04-07 20 03 55](https://cloud.githubusercontent.com/assets/8282518/14361643/22e4e776-fcfc-11e5-98d1-b8792385c27c.png)

emails are not delivered to destination.

This is my setting:
`export MAIL_URL='smtp://wekan@example.com:HUHuhsus656fdffd@mail.example.com:587/'`

I installed WeKan on Ubuntu 14.04 64 bit using the automated script.

**Comment by HLFH** [comment]
Duplicate of https://github.com/wekan/wekan/issues/545

**Comment by AlexanderS** [comment]
You may have to encode the `@` in the login name of your mail server as `%40`.

**Comment by mpartipilo** [comment]
This has been updated recently. I suggest you try again.

**Comment by Gelmes** [comment]
Try refreshing and logging in. worked for me.

If someone could post a relative link to setting up the SMTP that would be helpful. I do not know what to look for myself. Google results are usually what I would use to set it up on my phone so I might not be looking for the right location.

https://www.lifewire.com/what-are-the-gmail-smtp-settings-1170854

**Comment by krisfris** [comment]
Is it possible to disable email altogether?

**Comment by xet7** [comment]
@krisfris 

Yes, depending on what login method you use. More info at wiki.
