### ISSUE TITLE
Broken Sandstorm board?

### ISSUE THREAD

**Issue by elimisteve** [wekan/wekan#570]
When I try to visit my Wekan board on Sandstorm, I get an HTTP 500 with this:

```
Error: Error: remote exception: remote exception: remote exception: ::read(fd, buffer, maxBytes): Connection reset by peer
C++ location:(javascript):??
type: disconnected
```

I am running the latest versions of both Sandstorm (since it's Oasis) and Wekan (no new updates available).  I've created a _new_ board, and it works fine, so the issue is just with this older, existing board, from about a week ago IIRC.

Debug log:

```
...*** couldn't connect to grain (Error: remote exception: remote exception: remote exception: ::read(fd, buffer, maxBytes): Connection reset by peer) ***
```

**Comment by ocdtrekkie** [comment]
I'm going to tag @paulproteus here because he might be able to help!

**Comment by paulproteus** [comment]
Hey @elimisteve - did this problem ever get fixed? If not, I should dig into it.

**Comment by elimisteve** [comment]
Interestingly, yes it looks like this works fine now. Thanks!

**Comment by paulproteus** [comment]
Oasis was having periodic issues that affected a small fraction of users which we recently fixed all instances of, so it's probably that. Sorry about that, and glad that our cleanup worked.
