### ISSUE TITLE
labels can't be dropped into opened cards

### ISSUE THREAD

**Issue by alvaropinot** [wekan/wekan#571]
At first, great work!

Despite that the opened card get highlighted and the rest get dimmed, labels can only be dropped into the card miniature.

![captura de pantalla 2016-04-14 a las 11 54 36](https://cloud.githubusercontent.com/assets/6654199/14524335/219de93a-0238-11e6-9522-72e37060fcd4.png)

**Comment by xet7** [comment]
@ocdtrekkie 

Does this bug still exists?

**Comment by ocdtrekkie** [comment]
I don't think this is or would be Sandstorm specific. I wouldn't really know about this issue, if it's an issue.

**Comment by xet7** [comment]
@alvaropinot 

On card there is labels + button where you can add and edit labels. Backgroud is dimmed because you should operate on opened card.
