### ISSUE TITLE
Reporting Security Issue

### ISSUE THREAD

**Issue by Gormogon** [wekan/wekan#573]
I have found a fairly serious security vulnerability in Wekan and want to properly disclose it to the developers.  What is the appropriate process to disclose this to you guys. I'd rather not plaster Github with vulnerability information before a patch can be released.

**Comment by nata-g** [comment]
Maybe you can share it in the gitter channel, shown in the Readme.  @mquandalle is the main person to contact for these things

**Comment by mquandalle** [comment]
Please send me an email at mquandalle@wekan.io.

**Comment by Gormogon** [comment]
@mquandalle An email has been sent.

**Comment by nidico** [comment]
Is this fixed in #579 or something else?

**Comment by Gormogon** [comment]
@nidico An email was sent on Apr 17 to @mquandalle outlining my findings.  I received an email the same day stating that a fix would be worked on and released as soon as possible; however, it does not appear that any patch has been released yet.
