### ISSUE TITLE
Export option links to "localhost" instead ipaddress:port

### ISSUE THREAD

**Issue by hellc2** [wekan/wekan#575]
I'm testing wekan.io and we have installed docker container.
I just see that in "Board menu > Export board" is a link to localhost/api/... instead the host:port/api/...

;)

**Comment by AlexanderS** [comment]
You have to change that line https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L28 to point to your correct host:port combination.

**Comment by xiaohelong** [comment]
in virtualbox images 0.49 version,I modified /home/wekan/repos/run-wekan.sh ROOT_URL to my ip,then restart ,it's ok then.

**Comment by xet7** [comment]
@Nocan456 

[Use snap](https://github.com/wekan/wekan-snap/wiki/Install)

[Docker destroys your data, it does not work](https://github.com/wekan/wekan-mongodb/issues/9)

**Comment by Nocan456** [comment]
@xet7 
I used the VMWare image for 0.77 - fresh install

**Comment by Nocan456** [comment]
or - to put it differently - whats the fastest way to get back to the supportet version if I build up everything with the VM Image?

**Comment by xet7** [comment]
@Nocan456 

Copy changes you made in your fork to VM repos/wekan directory. cd wekan , meteor - you can see live changes. or recompile all binary extensions too with rebuild-weka-meteor-1.6.sh option 3. Make new fork and submit pull request too devel branch if you want it included to all wekan platforms. See wekan github wiki developer documentation for more info about making linting fixes, etc.
