### ISSUE TITLE
MongoDB empty after upgrading docker-compose?

### ISSUE THREAD

**Issue by infertux** [wekan/wekan#588]
I'm not sure what happened but all my data is gone somehow. I started Wekan as usual running `docker-compose up` and noticed some unusual lines in the output:

```
wekandb_1  | 2016-04-23T12:59:37.721+0000 I INDEX    [initandlisten] allocating new ns file /data/db/local.ns, filling with zeroes...
wekandb_1  | 2016-04-23T12:59:37.852+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
wekandb_1  | 2016-04-23T12:59:37.852+0000 I STORAGE  [FileAllocator] creating directory /data/db/_tmp
wekandb_1  | 2016-04-23T12:59:37.859+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.004 secs
[...]
wekandb_1  | 2016-04-23T12:59:38.524+0000 I INDEX    [conn5] allocating new ns file /data/db/wekan.ns, filling with zeroes...
wekandb_1  | 2016-04-23T12:59:38.598+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/wekan.0, filling with zeroes...
wekandb_1  | 2016-04-23T12:59:38.601+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/wekan.0, size: 64MB,  took 0.002 secs
wekandb_1  | 2016-04-23T12:59:38.605+0000 I INDEX    [conn5] build index on: wekan.users properties: { v: 1, unique: true, key: { username: 1 }, name: "username_1", ns: "wekan.users", safe: true, sparse: 1 }
```

I tried to run `mongodump` and indeed all collections are empty. The only change I can think of is upgrading _docker-compose_ from 1.6.2 to 1.7.0 but I can't find anything related in their [changelog](https://github.com/docker/compose/blob/master/CHANGELOG.md#170-2016-04-13). Any ideas what might have gone wrong and how to recover my data? Thanks a lot!

**Comment by infertux** [comment]
So it looks like Docker mounted a new volume for some reason, I have no idea why. But I was able to recover my data from `/var/lib/docker/volumes` in the end.

**Comment by simopaasisalo** [comment]
@infertux How did you recover your data from a volume? I managed to delete my data when trying to update Wekan to it's newest version

**Comment by infertux** [comment]
@simopaasisalo I think I did something like that IIRC:

1. `mv /var/lib/docker/volumes/$NEW_VOLUME_ID /tmp/`
2. `mv /var/lib/docker/volumes/$OLD_VOLUME_ID /var/lib/docker/volumes/$NEW_VOLUME_ID`
3. `docker-compose up`
4. Enjoy :)

If you can't identify what is `$OLD_VOLUME_ID` or the directory is gone, that won't work though :/

**Comment by simopaasisalo** [comment]
@infertux Thanks a lot! I'll see tomorrow if it works. There are ~five volumes in the directory, and I have no idea which is which, but I guess I can try each of them out and see.

**Comment by infertux** [comment]
@simopaasisalo I found the right volume with `tree /var/lib/docker/volumes/` and saw some `.bson` files (MongoDB file format). Hope that helps.

**Comment by simopaasisalo** [comment]
@infertux It worked! 

The new install had created a new 'data' directory to my wekan install directory. By your directions I did `mv data /tmp/`
a little digging to find the volume (turned out to be the first in .../docker/volumes)
`mv /var/lib/docker/volumes/$OLD_VOLUME_ID/_data data`

Thanks again a thousand times!
