### ISSUE TITLE
Wekan not starting on reboot, using Docker production install instructions

### ISSUE THREAD

**Issue by brylie** [wekan/wekan#590]
I have followed the [Wekan Docker production installation guide](https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production), including adding the following to my Wekan Docker compose file:

``` json
  wekan:
    image: mquandalle/wekan
    restart: always
```

I then run Wekan as the `wekan` user, via Docker compose, and things work. However, when restarting the server, Wekan must manually be started again. What should I do to ensure that Wekan starts when the OS boots?
# Environment

Ubuntu 14.04

**Comment by xet7** [comment]
sudo update-rc.d docker defaults
