### ISSUE TITLE
Add Feature: Option to make board-sidebar default closed

### ISSUE THREAD

**Issue by anhenghuang** [wekan/wekan#594]
Our team want to make the board-sidebar default closed.
Although there is some code to control board-sidebar as below:

```
template(name="sidebar")
  .board-sidebar.sidebar(class="{{#if isOpen}}is-open{{/if}}")

```

And I have tried to assign a boolean(true or false) value to the func 'isOpen', but this effort did not work, the sidebar is always here as long as we open a board.

**Comment by 2Belette** [comment]
+1 for this :)

**Comment by xet7** [comment]
Sidebar is now by default closed.
