### ISSUE TITLE
[Request] Simple Admin Panel

### ISSUE THREAD

**Issue by alergant** [wekan/wekan#598]
Add a simple admin panel.
Use a password that you can set during setup or in .json file.
This admin can
1º Add Users (Although forbidClientAccountCreation: true)
2º Delete Users
3º Change passwords

Its a simple admin buy necessary mode.

I havent got time and im not js programer (im python and .NET programer Xd) but i think that it is simple to implement

**Comment by stefuNz** [comment]
+1

**Comment by brylie** [comment]
The Admin panel could also allow SMTP configuration.

**Comment by lkisme** [comment]
I made a PR on this, check out #618

**Comment by danger89** [comment]
Must have feature!!

**Comment by NoodleBB** [comment]
+1 Must have.

**Comment by ArcturusB** [comment]
@NoodleBB: this has already been included in [v.0.1.11-rc2][1].

[1]: https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v0111-rc2-2017-03-05-wekan-prerelease

**Comment by NoodleBB** [comment]
@ArcturusB: I can't find it in v0.16

**Comment by HLFH** [comment]
@NoodleBB is right. And that's why we are keeping this issue open.

**Comment by xet7** [comment]
Moved to #802
