### ISSUE TITLE
[Mail] Can't send any email or troubleshoot where's the problem coming from

### ISSUE THREAD

**Issue by tperas** [wekan/wekan#599]
Hi, 

It make 3 days that i'm trying to make Wekan work correctly but nothing work.
I've used the Appliance deployment to easily use the solution on my infrastructure. 

The server is correctly configure for name resolution.
The server can connect my smtp server (telnet test)

After a lot of different configuration test i can't make the email system work to send email for inscription, password reset, etc... 
Plus, i don't see any way to personalize the sender.

I've try the solution from @kayrules (https://github.com/wekan/wekan/issues/228), but it doesn't work for me. 

Is there any way to troubleshoot this issue ? Because i can't find any log on the server. 

Thanks for your help.

**Comment by Umi97** [comment]
smtp-config.js of #228 really works well for me. Make sure you have tried 'AUTH LOGIN' while you test your smtp server. Not only helo or ehlo, successful connect is not enough.

**Comment by tperas** [comment]
Apparently, there is no authentication needed because the AUTH LOGIN  command isn't recognized. I've test to manually create and send email using telnet and it work.

**Comment by Umi97** [comment]
Wekan is a smtp client and you need some authorization to use the smtp server. No auth login, no authorization. If your smtp server failed to support this command, you can enable 'smtpd_sasl_auth_enable'. You can follow this [guide](https://help.ubuntu.com/community/Postfix) if you are using ubuntu. It works for me. Good luck.

**Comment by tperas** [comment]
@Umi97 tnahk you for your help. 
It's allowed on my internal network to send email without authentication so just by limiting the line MAIL_URL to 'smtp://@mydomainsmtp:25/' it work. 

Now I'm searching for hos to modify sender, and where I can found any log information about this mail part.

**Comment by tperas** [comment]
Ok, by adding "MAIL_FROM" line in /etc/init.d/wekan configuration file, you can define the sender for automated email.

**Comment by Umi97** [comment]
You are right. It is reasonable, just 'smtp://@mydomainsmtp:25/', because you are using internal network. I tried this but failed...Maybe I need your help now...
You can also set the sender with: 
> Meteor.startup(function () {
  Accounts.emailTemplates.from = 'YourName <user@example.com>';
});

**Comment by tperas** [comment]
Yes that's the same result, because by defining MAIL_FROM in wekan configuration file, this configuration will be used after to define the Accounts.emailTemplates.from under /root/bundle/programs/server/app/config/account.js

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
