### ISSUE TITLE
Wrong .eslintrc in last zip release

### ISSUE THREAD

**Issue by mbeaudru** [wekan/wekan#607]
Hi,

There is two times Filter: true at line 115 in .eslintrc preventing eslint to initialise in the last release zip.

I can't seem to find out how to pull request this so I'm doing it here, sorry if I'm in the wrong place.

**Comment by mquandalle** [comment]
Hello @mbeaudru, if you want to create a pull request you should `git pull https://github.com/wekan/wekan.git`, and not download the ZIP source of the last release.

**Comment by mbeaudru** [comment]
I couldn't find the bug in the repo, that's why I refered to the ZIP in the first place.

I suppose I was tired that day, counting that I found it instantly today... Wasn't looking for the right branch.

Thanks though, I'm doing it right away !
