### ISSUE TITLE
BUG: Few URL with incorrect host when using Apache ProxyPass

### ISSUE THREAD

**Issue by ArcturusB** [wekan/wekan#609]
When installing docker package behind Apache with ProxyPass (following the [production installation instructions][wiki:production] in the wiki), some (few) URL are not displayed in the page with the correct host. Eg. `http://localhost:8181` is displayed instead of `https://vhost.example.com`. 

So far, I’ve spotted:
- “Card Actions” > “More” > “Link to this card”
- “Board Menu” > “Export Board”.

[wiki:production]: https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by AlexanderS** [comment]
You should change the ROOT_URL in the docker file.

**Comment by ArcturusB** [comment]
Using `wekan.environment.ROOT_URL=https://vhost.example.com` in `docker-compose.yml` does solve the issue.
