### ISSUE TITLE
[Request] Delete a List

### ISSUE THREAD

**Issue by JeremyIglehart** [wekan/wekan#611]
Is it possible to delete a list for good?  I can rename a list and therefore repurpose it.  But I'd like to be able to entirely delete a list.

**Comment by AlexanderS** [comment]
It is currently only possible to archive a list. It will be hidden and you can restore the list from the archived elements view.

**Comment by JeremyIglehart** [comment]
I'm glad that you've confirmed this functionality.

I'd like to request that deleting a list be added as a feature.

**Comment by danger89** [comment]
It would be very nice when a trash icon appears using drag & drop feature in order to remove/archive an item, list or card.. Who agrees?

**Comment by BaobabCoder** [comment]
Does not use drag & drop but allows to delete a list.
I agree it would be nice with drag & drop.

**Comment by hhxjzyr** [comment]
It is very good, but now, I delete a list accidentally, How can i  restore it?

**Comment by xet7** [comment]
It's now possible to delete list. Also Delete option is on menu "More" and there's some additional warning text, so it's not so easy to delete accidentally.
