### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by zeigerpuppy** [wekan/wekan#612]
This has only happened a couple of times, but sometimes on sandstorm, Wekan gives an nginx error 504 (the main sandstorm interface is functional).  Restarting the app doesn't help but closing the grain and reopening it restores function.
Happy to try and trace what's happening next time I see it if anyone has any diagnostics I can run?

the sandstorm log shows:

```
Error: Requested session that no longer exists, and timed out waiting for client to restore it. This can happen if you have opened an app's content in a new window and then closed it in the UI. If you see this error *inside* the Sandstorm UI, please report a bug and describe the circumstances of the error. [504]
    at server/proxy.js:580:24
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (packages/meteor.js:1154:24)
```

**Comment by xet7** [comment]
Please try with newest version. If it still happens, reopen issue.

**Comment by zeigerpuppy** [comment]
thanks, haven't had any issue with it lately, I'll reopen if it occurs again.

**Comment by YumeJapan123** [comment]
We are using wekan versio 5.98.0. But it works very slowly and I got 504 error.
After taking a while, we can log in but "Uncaught RangeError: Maximum call stack size exceeded " is still occuring. Even though I have admin permission, when I try to check the admin panel, it says that I have no authorizaion.(After taking a while, I could open it)
--


<br class="Apple-interchange-newline">
</body>
</html>


![image](https://user-images.githubusercontent.com/112185369/187368472-8658e7d1-fe61-4b50-9d86-7a13d6eee705.png)
![image](https://user-images.githubusercontent.com/112185369/187368862-4e7c05e5-61f9-4764-8dc0-7acaa8b5342f.png)
![image](https://user-images.githubusercontent.com/112185369/187369148-e3380031-7f09-4691-b7a3-ff93ce12b384.png)

**Comment by xet7** [comment]
@YumeJapan123 

Newest WeKan is v6.41. I have no way to test or build older versions.

**Comment by YumeJapan123** [comment]
@xet7 
Thank you very muych for your quick answer.
I am not sure if this problem is related to the version. It was fine until yesterday.

Yesterday, I tried to export file (json and excel ) to deal with  the issue #1289 https://github.com/wekan/wekan/issues/1289
But system error occured and could not download it. (Before, I could download them without any problem)
I am not sure if this caused the 504 error problem but after then, we are facing on this issue. Would be there any way to check logs or something? The app is on docker.

**Comment by xet7** [comment]
@YumeJapan123 

You could restore your WeKan backup you did take before deleting users.

**Comment by xet7** [comment]
And disable those users at Admin Panel

**Comment by YumeJapan123** [comment]
@xet7 

I am sorry I am not used to this app and am not sure what you meant but
do you mean this procedures? After executing this, would all the data on board will remain??

 Restoring database
#      # 1) Stop wekan
#             docker stop wekan-app
#      # 2) Go inside database container
#             docker exec -it wekan-db bash
#      # 3) and data directory
#             cd /data
#      # 4) Remove previous dump
#             rm -rf dump
#      # 5) Exit db container
#             exit
#      # 6) Copy dump to inside docker container
#             docker cp dump wekan-db:/data/
#      # 7) Go inside database container
#             docker exec -it wekan-db bash
#      # 8) and data directory
#             cd /data
#      # 9) Restore
#             mongorestore --drop
#      # 10) Exit db container
#             exit
#      # 11) Start wekan
#             docker start wekan-app

**Comment by xet7** [comment]
@YumeJapan123 

No, it would not remain. So you should not restore.

**Comment by YumeJapan123** [comment]
@xet7 

Ok, I don't have backup before deleting those users. So the way does not make sense in this case. And actually, I deleted users from Admin panel before causing #1289 problem.

1) I deleted useres from Admin
2) The issue #1289 occured
3)  Search (mention) function does not occur

**Comment by xet7** [comment]
@YumeJapan123 

It would be good idea to make backup now, just in case, so that you would not delete something accidentally in future.

You can see your current data in database with [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup#using-nosqlbooster-closed-source-mongodb-gui-with-wekan-snap-to-edit-mongodb-database)

**Comment by xet7** [comment]
Newest WeKan does not yet have enough fixes, so I don't recommend upgrading WeKan. Sometime later I will make new WeKan version that fixes ghost users etc automatically.

**Comment by Sarah-ifx** [comment]
Hi @xet7 
We updated our Wekan to V.7.09, and since then some of the users have been getting "504 Gateway Time-out". 
As I see this is a known error in the earlier versions. Is this error still exist? What can we do as a workaround? 
TY.
