### ISSUE TITLE
Bad Board - Comments no longer display

### ISSUE THREAD

**Issue by JeremyIglehart** [wekan/wekan#613]
I'm sorry that I'm reporting something without having any technical lead as to why this is happening - I can't figure it out at all.

Basically, I have a fresh install of Wekan, and I have a board which just stopped displaying comments.

You can create new lists, add cards (to them, and old ones) but it no longer displays new or old comments or any activities on the cards themselves.  The activities get recorded normal on the activity log on the right hand side - but the cards stop functioning properly.

To add to it, the animations also start to malfunction.  Somehow this one board is just weird - it's only happening to one of my 8 boards I have.  I renamed it to "Bad Board" and archived it and made a new board with duplicate information (all manually).

I just thought I'd share my experience here so that we could start to track this bug down and fix it.

**Comment by franckFleet** [comment]
Same problem when I update my wekan version from 0.10.0 to 0.11.0-rc2

comments appears on some cards, never on others, after tenth of seconds on other cases.

**Comment by AlexanderS** [comment]
@franckFleet That sounds more like #656.

**Comment by franckFleet** [comment]
yes it is.
we have to hover the comments entry box in order for the comments to show up, but when they were displayed, closing and reopen the card doesn't need to hover the comment entry box for seeing comments (ever loaded ?)

**Comment by xet7** [comment]
#656 has already been fixed.
