### ISSUE TITLE
Add a card button on top of a list if it grows 

### ISSUE THREAD

**Issue by martingabelmann** [wekan/wekan#617]
After a list has grown one has to scroll all the way down to click on "Add a card". It would be nice if the button appears on top of the list if the scrollbar appears.
  
another possibility would be to add a card right in place when clicking between two existing cards.

**Comment by RomFouq** [comment]
Or even simpler: just move the 'Add a card' button to the top instead of the bottom.

**Comment by laupkram** [comment]
+1

**Comment by mquandalle** [comment]
There is already a “Add a card” action in the list menu.

**Comment by martingabelmann** [comment]
True.   
Thanks!
