### ISSUE TITLE
How to remove a user ?

### ISSUE THREAD

**Issue by vrninfo** [wekan/wekan#621]
How do I remove a user ?

_Wekan is installed on Ubuntu 14.04 amd64_

If I do the following  : 

> mongo
> 
> use wekan
> 
> db.users.find().pretty()

I get a list of all registered users, but how do I delete one of them ?

**Comment by Merlin90** [comment]
I would be interested too. An admin account with a user administration would be useful.

**Comment by danger89** [comment]
Almost there... If you are using Docker, try to first find the MongoDB container ID (using `docker ps`), the with name "wekan_wekandb_x" and remember the container ID. Then:
`docker exec -i -t <container_id> /bin/bash`
What vrninfo said connect to the DB, via:
`mongo wekan`
List the users:
`db.users.find().toArray()`
Finally, delete the user record! Hopefully this won't brake anything else :P
`db.test_users.remove( {"username": "admin"})`

Good luck!

**Comment by Merlin90** [comment]
Thank you very much . I use the virtual appliance and have users that I didn't got deleted. The easiest way would actually a simple admin interface.

**Comment by vrninfo** [comment]
@danger89 
> Hopefully this won't brake anything else

This is exactly what I was afraid of and why I ask how to delete a user in the first place... :/

**Comment by danger89** [comment]
Ahha just try it :p

**Comment by mhoffmann75** [comment]
Mhh, it seems to me that deleting users breaks cards, where this already deleted user was assigned to. They simply cannot be opened anymore and the whole gui hangs.

**Comment by danger89** [comment]
That is where I was afraid for. Meaning you first need to remove all the cards/boards that belongs to this user, before removing the user. 

Final solution: Please, someone should implement this feature in the code behind a button.

**Comment by msbt** [comment]
Did you find a solution after removing a user? I Figured I would try it myself and of course, some cards do not work anymore ;) Would be quite a bit of work to recover the missing cards...

Best regards

**Comment by xet7** [comment]
@msbt 

Hmm, no backups before messing with database?

Moved to #802

**Comment by msbt** [comment]
I did have backups, I was just poking around a little ;)

Sorry for reopening, here's one solution:
After removing the user, you also have to change the userID of existing cards and boards to an active one, i.e. check
`db.cards.find().toArray()`
for the id of the deleted user and then replace them with
`db.cards.update( {"userId": "deleted_user_id"}, { $set: { "userId": "existing_user_id" } } );`

and also remove the deleted user from the members of the board, i.e. check
`db.boards.find().toArray()`
and look for the "members" : array

Best regards, M

**Comment by xet7** [comment]
@msbt 

You could contribute to cleanup scripts that also access MongoDB directly:
https://github.com/wekan/wekan-cleanup

**Comment by msbt** [comment]
It looks like this is already implemented in the cleanup script you mentioned here 
`# Will update boards to remove deleted users `
and here
`# Will update cards to remove deleted users`

I reckon this can be closed after all!
