### ISSUE TITLE
How do I set WIP limits?

### ISSUE THREAD

**Issue by denisz1** [wekan/wekan#623]
New Wekan user here.

Kanban without WIP limits is kinda pointless.

So I'm assuming there is a WIP limit option, and I just don't know how to find/use it?

**Comment by AlexanderS** [comment]
Currently there is no such feature.

**Comment by denisz1** [comment]
What a pity! Wekan is good otherwise.

But WIP limits are a necessity for kanban. **This should go into the todo list.**

**Comment by xet7** [comment]
Moved to #783
