### ISSUE TITLE
Request! Hide Activities

### ISSUE THREAD

**Issue by elzeron** [wekan/wekan#626]
I really don't know where to post this, I'm new in GitHub yet

I'd propose a button to hide all activities in a card, just because comments are pushed down, which are more important than activities. Maybe the button could be disabled by default or remember the selection within the session.

Taking al look at the code maybe filtering by "activityType" == "addComment"

**Comment by xet7** [comment]
This already exists in Wekan:
Change Settings/Hide system messages

**Comment by MaStrOD** [comment]
hej folks,
is there anny way to do this in sansdstorm to? i don't find anny other settings then color and language.

**Comment by xet7** [comment]
@MaStrOD 

I think feature is not enabled on Sandstorm yet. You could try to install latest available .spk file to Sandstorm from Wekan releases page. It will later disable new install from source and docker version Admin Panel on Sandstorm and enable features that make sense there. Sandstorm platform is very important for me, please be patient :)
