### ISSUE TITLE
New release, v0.10.1 is from Dec/2015

### ISSUE THREAD

**Issue by smarek** [wekan/wekan#631]
Hi,

is there any roadmap available for next release? Current stable is from Dec/2015 as of git tag v0.10.1

Changes since last release: [https://github.com/wekan/wekan/compare/master...devel](https://github.com/wekan/wekan/compare/master...devel)

Thank you

**Comment by xet7** [comment]
See link to latest v0.21 tag etc at Wekan GitHub releases page.
