### ISSUE TITLE
Can't deploy on Heroku

### ISSUE THREAD

**Issue by raum-IO** [wekan/wekan#638]
Basic/predefined deployment get's an compiler-error:

> -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
> -----> Node.js app detected
> -----> Installing node
> -----> Installing meteor
> Downloading Meteor distribution
>   4.8%#############                                                             18.3%##################                                                        25.6%81.4%#####           88.5%###########################      95.5%
> Meteor 1.3.4.1 has been installed in your home directory (~/.meteor).
> Now you need to do one of the following:
>   (1) Add "$HOME/.meteor" to your path, or
>   (2) Run this command as root:
>         cp "/tmp/buildpack20160704-158-8jv8tz/meteor-o05c/.meteor/packages/meteor-tool/1.3.4_1/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
> Then to get started, take a look at 'meteor --help' or see the docs at
> docs.meteor.com.
> $ROOT_URL, if specified, must be an URL.
> -----> Upgrading meteor to METEOR@1.2.1
> $ROOT_URL, if specified, must be an URL.
>  !     Push rejected, failed to compile Node.js app

**Comment by jvenator** [comment]
+1 on this from today. Same message.

**Comment by mquandalle** [comment]
Did you set the `ROOT_URL` variable to your domain name? We unfortunately can’t avoid this extra configuration step due to a Heroku limitation (see also https://github.com/RocketChat/Rocket.Chat/issues/2287).
