### ISSUE TITLE
Codeblocks should not be scanned for emoji

### ISSUE THREAD

**Issue by Ryman** [wekan/wekan#643]
It breaks the ability to copy code later from a comment, e.g. with rust code:

``` rust
use std::mem::transmute;

// becomes
use std: [:mem:] :transmute;
```

**Comment by mquandalle** [comment]
Yes, see also #323.

**Comment by DrCuriosity** [comment]
I've just experienced this problem with putting timestamps on a card. A "`16:08:03`" tries to extract the middle ":08:" as an emoji, even when escaped.
