### ISSUE TITLE
Installation on CentOS 6 or RHEL 6

### ISSUE THREAD

**Issue by eabquina** [wekan/wekan#644]
Has anyone tried installing this in a CentOS or RHEL server? 
I was able to install things bit-by-bit,.. "and tried what can be left running using the autoinstall_wekan.sh" script

running "service wekan start" says "info: Forever processing file: main.js"
And it stays like that forever. 

Tried to load the link, and it is not working...

**Comment by howardroark2018** [comment]
:( that's the exact same problem I am facing! Any help would be appreciated! 

Thanks!

**Comment by NoodleBB** [comment]
Wekan v0.18 runs on CentOS. Take a look at [Install Wekan on Uberspace](https://github.com/wekan/wekan/wiki/Install-Wekan-on-Uberspace)

**Comment by xet7** [comment]
@eabquina @howardroark2018 

If you can use Docker, you could try something similar like on SUSE docs:
https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-on-SUSE-Linux-Enterprise-Server-12-SP1
