### ISSUE TITLE
Release 0.11

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#648]
Hi all,

I’ve released the [first release candidate](https://github.com/wekan/wekan/releases/tag/v0.11.0-rc1) of Wekan 0.11. The release notes are available [here](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v011).

As always we need your help to test the app, translate the UI, report bugs, or really provide any feedback you feel could improve this release. There will be multiple release candidates in the coming days, and the final release 0.11 is expected for the next week.

Thanks for your help!

**Comment by mquandalle** [comment]
#650 is pretty critical as it prevent using Wekan from a blank database. I would recommend waiting for RC2 fix before doing your tests.

**Comment by mquandalle** [comment]
Released [RC2](https://github.com/wekan/wekan/releases/tag/v0.11.0-rc2) with a few fixes.

**Comment by martingabelmann** [comment]
Still seems to be broken, at least within docker. I get a blank page after startup. console output is:

```
23:19:38.312 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 5d2af15834c54f4c95944521a629e99ae9279f03.js:131:2869
23:19:38.622 Error: Cannot find module 'xss'
 5d2af15834c54f4c95944521a629e99ae9279f03.js:7:580
23:19:38.683 There is no route for the path: / d2af15834c54f4c95944521a629e99ae9279f03.js:184:5954
23:19:38.685 TypeError: n is null 5d2af15834c54f4c95944521a629e99ae9279f03.js:227:3287
23:19:39.722 ReferenceError: Boards is not defined 5d2af15834c54f4c95944521a629e99ae9279f03.js:305:15272
```

docker-compose.yml:
```
wekan:
  image: mquandalle/wekan
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://localhost:80
  ports:
    - 80:80

wekandb:
  image: mongo
  ports:
    - 27017:27017
```

**Comment by mquandalle** [comment]
Oh yes sorry, I encountered a weird bug while trying to publish RC{1,2} on DockerHub and didn’t get back on it. I will try again now.

**Comment by mquandalle** [comment]
(Though I’m not sure were these error messages comes from...)

**Comment by martingabelmann** [comment]
no problem, the 0.10-tag still works... Do you want to push it with a specific 0.11rcx tag and let the latest tag point to 0.10? Otherwise it somehow forces people to be a beta tester (of an actually broken state of the app).

**Comment by mquandalle** [comment]
So far I’ve always moved the `latest` tag to the latest release, including release candidates. IIRC a similar pattern is followed by other open-source apps like Discourse, and maybe even recommended in the Docker documentation. It would makes sense to have an additional `stable` tag for people that want to stay on the stable release—however there isn’t any sort of automated updating or even notification when the tag you are following isn’t up to date anymore, so the large majority of `latest` users won’t notice the release candidate.

**Comment by martingabelmann** [comment]
actually there is an automated updating by using linked repositories on the hub: using this the image gets rebuild if the upstream image gets pushed...

**Comment by simopaasisalo** [comment]
Is there any ETA for the final release?

**Comment by xet7** [comment]
There has already been new Wefork release, and now Wefork is being merged back to Wekan. Docker Hub already has latest Wekan.
