### ISSUE TITLE
have a stable tag on dockerhub

### ISSUE THREAD

**Issue by martingabelmann** [wekan/wekan#653]
As discussed in #648 it might be useful to have a tag/branch that always points to the latest stable release.

Imho this is a essential feature for people and organizations that want to use wekan in production.

**Comment by Abioy** [comment]
run the latest image from dockerhub and got a msg 'meteor requires node v0.10.41 or later'.

**Comment by mquandalle** [comment]
@Abioy this is now fixed, see #650.
