### ISSUE TITLE
docker-composer error: Meteor requires Node v0.10.41 or later.

### ISSUE THREAD

**Issue by vjrj** [wekan/wekan#655]
I'm trying to install wekan locally via docker-composer but I get this error:
`wekan_1  | Meteor requires Node v0.10.41 or later.`

Checking the meteor versions of the images I get:
```
➜  ~ docker run -it --entrypoint=/bin/bash mquandalle/wekan:latest    
root@b03749bd3f41:/# node -v
v0.10.40
➜  ~ docker run -it --entrypoint=/bin/bash meteorhacks/meteord:onbuild
root@e0d5043c649c:/# node -v
v0.10.41
```
If helps, in some of my meteor (1.3) projects I use `meteord:base` instead of `onbuild`:
```
➜  ~ docker run -it --entrypoint=/bin/bash meteorhacks/meteord:base   
root@c66a62030bd2:/# node -v
v0.10.43
```

Any suggestion?

**Comment by martingabelmann** [comment]
quickfix:  
the tag ``0.10.0`` still works. However, it was pushed 7 months ago while the upstream image was pushed 4 months ago (im running it for ~3 days now without problems).

**Comment by afhoffman** [comment]
I have very little experience with any of this software but I do have a hacky solution for getting the newest version to run:

1. Start the database:

    `docker run -d --restart=always --name wekan-db mongo`
2. Run wekan and drop into a shell:

    `docker run -it --entrypoint=/bin/bash --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost" -p 8080:80 mquandalle/wekan`

3. Update node to 0.10.43

    `curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash -`

    `apt-get install nodejs`

4. Exit the terminal and start the app

    `exit`

    `docker exec -d wekan /bin/bash /opt/meteord/run_app.sh`

I'm not gonna pretend that it's clean or convenient, but it runs. I tried just changing the "image" line in the docker-compose.yml to `build: .` to build wekan on top of the newer version of meteord but I just get a blank screen when I try to log in.

**Comment by mquandalle** [comment]
I had a hard time with implicit docker dependency and unexpectedly pushed a broken image as part of my deploy script. I’m closing this issue as the image is now fixed on DockerHub.

**Comment by vjrj** [comment]
Thanks indeed. Now it works as expected.
