### ISSUE TITLE
Can't see card comments with Chrome

### ISSUE THREAD

**Issue by tscrip** [wekan/wekan#656]
On Chrome version 51, I have to hover over the comments entry box in order for the comments to show up. I have tried in FireFox and this does not seem to be an issue.

**Comment by xet7** [comment]
@tscrip 

What version Wekan?

- Docker Wekan latest ? See #659 .
- Docker Wekan 0.10 ? I use this, seems not affected on Chrome 52.
- Git repo, what branch ?
- Sandstorm version ?

**Comment by tscrip** [comment]
I am running 11 rc2. This is running on a virtual CentOS server.
I am not using sandstorm. I am manually running the main.js or whatever it is with node. 
I also noticed in version 10 this was not an issue.

**Comment by AlexanderS** [comment]
This seems to be caused by bda1df5ada4cc086e4e05748f8019afbb24e0117 and is a result of #646.

**Comment by mkoitka** [comment]
Just commenting to add, that since 0.11 this bug is present for me in all major browsers (Windows 10, FF, Chrome, IE, Edge)

**Comment by xet7** [comment]
I think this is already fixed in latest Wekan, for example Docker image. Closing issue.
