### ISSUE TITLE
Login forbidden

### ISSUE THREAD

**Issue by wreels** [wekan/wekan#661]
Can someone help me.  I'm a novice at openSUSE but by the grace of God, after three weeks I finally got the login page to load for wekan.  Now when I try to log in with wekan as the ID and wekan as the password, I get Login forbidden.  Can someone please help me to let me know what would cause this behavior?

**Comment by xet7** [comment]
@wreels 

First you need to register your user.

Other possibilities:

## Google Cloud not supported

If you are trying to run Wekan at Google Cloud, we have not yet found a way to enable websocket support at Google Cloud yet, and this slows down Wekan a lot and makes some functionality broken. Wekan uses websockets.

## Running on Docker

For Wekan Docker image, see #659 

More info about Docker usage here:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

And using Docker on openSUSE:
https://docs.docker.com/engine/installation/linux/SUSE/

## Manual install

Latest version in Git could be broken.

## Debugging on Chrome

Start Chrome, click top right 3 dots menu, More Tools, Developer tools, Console. Reload page. Is there any errors? Copy paste to your reply.

## Debugging on Firefox

Start Firefox, right click webpage, click Inspect Element, Console. Reload page. Is there any errors? Copy paste to your reply.

**Comment by wreels** [comment]
When I do register, it says "Internal server error" so I'm not doing something correctly - I just have no idea what it is.  Any specific troubleshooting help would be greatly appreciated. 

God bless...

**Comment by xet7** [comment]
@wreels 

Remove your current install, and install Wekan Docker version 0.10.0 using links above.

**Comment by xet7** [comment]
@wreels 

But before that, could you try on Chrome or Firefox what Javascript errors you get using info above?

**Comment by wreels** [comment]
@xet7 

I don't have Docker installed.  It took me a couple weeks to get the page to load - kind of scared that if I remove it I'll never get it running again.  I've tried in Chrome with the same result but I didn't get a Java error.  Is there something I need to do in Chrome to see the errors?  Sorry,  like I said, I'm a novice with Linux.

**Comment by xet7** [comment]
@wreels 

Start Chrome, click top right 3 dots menu, More Tools, Developer tools, Console. Reload page. Is there any errors?

**Comment by xet7** [comment]
@wreels 

What openSUSE version you have? You can see it this way:

https://en.opensuse.org/SDB:Find_openSUSE_version

**Comment by wreels** [comment]
@xet7 

No javascript errors in Chrome in the console in the bottom.  I only get "Internal server error" just above the username field on the login screen.

I issued the uname -a command and this is what came back.
 Linux <servername> 3.12.59-60.45-default #1 SMP Sat Jun 25 06:19:03 UTC 2016 (396c69d) x86_64 x86_64 x86_64 GNU/Linux

**Comment by xet7** [comment]
@wreels 

This command shows operating system release version:

```bash
cat /etc/os-release
```

What text comes with that command?

**Comment by wreels** [comment]
@xet7 

NAME="SLES"
VERSION="12-SP1"
VERSION_ID="12.1"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp1"

**Comment by xet7** [comment]
What is your current port where wekan is?
For example, when URL is http://ip-adress:8080 then 8080 is the port.

**Comment by xet7** [comment]
Did you install mongodb ?

**Comment by wreels** [comment]
you won't be able to get to it since it's behind a firewall.  Also, yes mongodb is installed.  - infact, it wasn't until I was able to successfully run mongod, that the page was able to load.  I wasn't able to load the page before /data/db was created manually so that mongod would run.

**Comment by xet7** [comment]
What is your current wekan version at Git repository?

In wekan git directory, type:

```
git log
```

Latest topmost change in Git repo is this:

```
commit 301210c87bd50c8491844182e515c0ffd97c18f6
Author: Maxime Quandalle <mquandalle@wekan.io>
Date:   Thu Jul 21 12:52:32 2016 +0200

    Fix eslint testing
    
    Partially reverting c8705a0
```

But we may need to use previous version from git history, that works better.

**Comment by xet7** [comment]
I'm still thinking what of these options is better for you:

1) Try to fix your current install of Wekan, that did take a long time for you to install. This may take longer time to debug.

2) Install Docker version. Install, upgrade, downgrade is very fast. It can be installed to run at the same time on your server, in different port, and also removed fast if needed. I'm using Docker version and it works great.

What do you think?

**Comment by wreels** [comment]
@xet7 
issued git log
fatal: Not a git repository (or any of the parent directories): .git

Also, how do I install Docker on this server?  Is it compatible with the OS I'm running?

**Comment by xet7** [comment]
Yes it's compatible.

Here's how to install Docker and Wekan fast:

```
# Enable repository where Docker is
sudo SUSEConnect -p sle-module-containers/12/x86_64 -r ''

# Install Docker
sudo zypper in docker

# Start Docker
sudo systemctl start docker

# Enable Docker to start at boot
sudo systemctl enable docker

# For user you use your server with, enable docker commands
sudo /usr/sbin/usermod -a -G docker <username>
# For example:
sudo /usr/sbin/usermod -a -G docker michael
# So this is the user that has home directory /home/michael
```

Then to get networking enabled there's 2 options:
a) in YaST browse to Network Devices -> Network Settings -> Routing menu (f) and check the Enable IPv4 Forwarding box.
b) If networking is handled by the Network Manager, instead of YaST you need to edit the /etc/sysconfig/SuSEfirewall2 file to ensure the FW_ROUTE flag is set to yes like so:

```
FW_ROUTE="yes"
```

Then install MongoDB and Wekan, they also restart automatically on computer boot and error exit conditions:

```
# Install and run MongoDB
docker run -d --restart=always --name wekan-db mongo

# Install and run Wekan. Change the port 8080 to another free port that is not currently used.
# The another portnumber 80 is internal to docker, you don't need to change that.
docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost" -p 8080:80 mquandalle/wekan:0.10.0
```

And now you can access Wekan at your http://ip-address:port

For backup and restore see this page:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

**Comment by wreels** [comment]
SUSEConnect error: Net::HTTPServerException: 407 "Proxy Authentication Required" after the SUSConnect command.  lol  sigh...

**Comment by xet7** [comment]
Ok, your network uses proxy login, so you can add those settings:
https://www.novell.com/support/kb/doc.php?id=7006845

**Comment by xet7** [comment]
Also if repo is already configured, you could try if installing docker already works:
```
sudo zypper in docker
```

**Comment by xet7** [comment]
But then if your network does not have any outside network access, but your some computer has Internet access, I could write install instructions for offline install.

**Comment by xet7** [comment]
Docker works on Windows, Mac, Linux etc most computers, and transferring Wekan as files is possible.

**Comment by wreels** [comment]
HTTP_PROXY="http://192.168.0.1"  I assume the IP address needs to be replaced with my servers IP?  Also, if I could get wekan running on a windows server 2012 server I would be ecstatic!

**Comment by xet7** [comment]
Yes it's possible to get it running on Windows Server 2012. Does it have internet access?

**Comment by wreels** [comment]
yes it does

**Comment by xet7** [comment]
Ok, from this webpage:
https://www.docker.com/products/docker-toolbox

Click the Windows flag Download button to download and then install it.

It could have some GUI, or docker commands be typed on DOS, I'll search how to get access to it.

**Comment by wreels** [comment]
OK I'll get started on my side.  thanks

**Comment by xet7** [comment]
Typing somewhere command "docker" should show it's working.
With these docker commands you get mongo and wekan, change port 8080 to other if needed:

```
docker run -d --restart=always --name wekan-db mongo

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost" -p 8080:80 mquandalle/wekan:0.10.0
```

**Comment by wreels** [comment]
that's for the Linux server correct?

**Comment by xet7** [comment]
No, Windows server.

**Comment by wreels** [comment]
ah... interesting I tried it on my Linux server and got this.  Does this mean that docker is already installed?  I did docker run --help and it listed all the docker commands.  hm..


docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.


Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

  -a, --attach=[]                 Attach to STDIN, STDOUT or STDERR
  --add-host=[]                   Add a custom host-to-IP mapping (host:ip)
  --blkio-weight                  Block IO (relative weight), between 10 and 100                                                                                                                     0
  --blkio-weight-device=[]        Block IO weight (relative device weight)
  --cpu-shares                    CPU shares (relative weight)
  --cap-add=[]                    Add Linux capabilities
  --cap-drop=[]                   Drop Linux capabilities
  --cgroup-parent                 Optional parent cgroup for the container
  --cidfile                       Write the container ID to the file
  --cpu-period                    Limit CPU CFS (Completely Fair Scheduler) peri                                                                                                                     od
  --cpu-quota                     Limit CPU CFS (Completely Fair Scheduler) quot                                                                                                                     a
  --cpuset-cpus                   CPUs in which to allow execution (0-3, 0,1)
  --cpuset-mems                   MEMs in which to allow execution (0-3, 0,1)
  -d, --detach                    Run container in background and print containe                                                                                                                     r ID
  --detach-keys                   Override the key sequence for detaching a cont                                                                                                                     ainer
  --device=[]                     Add a host device to the container
  --device-read-bps=[]            Limit read rate (bytes per second) from a devi                                                                                                                     ce
  --device-read-iops=[]           Limit read rate (IO per second) from a device
  --device-write-bps=[]           Limit write rate (bytes per second) to a devic                                                                                                                     e
  --device-write-iops=[]          Limit write rate (IO per second) to a device
  --disable-content-trust=true    Skip image verification
  --dns=[]                        Set custom DNS servers
  --dns-opt=[]                    Set DNS options
  --dns-search=[]                 Set custom DNS search domains
  -e, --env=[]                    Set environment variables
  --entrypoint                    Overwrite the default ENTRYPOINT of the image
  --env-file=[]                   Read in a file of environment variables
  --expose=[]                     Expose a port or a range of ports
  --group-add=[]                  Add additional groups to join
  -h, --hostname                  Container host name
  --help                          Print usage
  -i, --interactive               Keep STDIN open even if not attached
  --ip                            Container IPv4 address (e.g. 172.30.100.104)
  --ip6                           Container IPv6 address (e.g. 2001:db8::33)
  --ipc                           IPC namespace to use
  --isolation                     Container isolation level
  --kernel-memory                 Kernel memory limit
  -l, --label=[]                  Set meta data on a container
  --label-file=[]                 Read in a line delimited file of labels
  --link=[]                       Add link to another container
  --log-driver                    Logging driver for container
  --log-opt=[]                    Log driver options
  -m, --memory                    Memory limit
  --mac-address                   Container MAC address (e.g. 92:d0:c6:0a:29:33)
  --memory-reservation            Memory soft limit
  --memory-swap                   Swap limit equal to memory plus swap: '-1' to                                                                                                                      enable unlimited swap
  --memory-swappiness=-1          Tune container memory swappiness (0 to 100)
  --name                          Assign a name to the container
  --net=default                   Connect a container to a network
  --net-alias=[]                  Add network-scoped alias for the container
  --oom-kill-disable              Disable OOM Killer
  --oom-score-adj                 Tune host's OOM preferences (-1000 to 1000)
  -P, --publish-all               Publish all exposed ports to random ports
  -p, --publish=[]                Publish a container's port(s) to the host
  --pid                           PID namespace to use
  --privileged                    Give extended privileges to this container
  --read-only                     Mount the container's root filesystem as read                                                                                                                      only
  --restart=no                    Restart policy to apply when a container exits
  --rm                            Automatically remove the container when it exi                                                                                                                     ts
  --security-opt=[]               Security Options
  --shm-size                      Size of /dev/shm, default value is 64MB
  --sig-proxy=true                Proxy received signals to the process
  --stop-signal=SIGTERM           Signal to stop a container, SIGTERM by default
  -t, --tty                       Allocate a pseudo-TTY
  --tmpfs=[]                      Mount a tmpfs directory
  -u, --user                      Username or UID (format: <name|uid>[:<group|gi                                                                                                                     d>])
  --ulimit=[]                     Ulimit options
  --uts                           UTS namespace to use
  -v, --volume=[]                 Bind mount a volume
  --volume-driver                 Optional volume driver for the container
  --volumes-from=[]               Mount volumes from the specified container(s)
  -w, --workdir                   Working directory inside the container

**Comment by wreels** [comment]
I git bash installed on my windows server, do I use that for this command?

docker run -d --restart=always --name wekan-db mongo

**Comment by xet7** [comment]
Probably docker is already installed on your Linux server.
Try there this:

```
# Start Docker
sudo systemctl start docker

# Enable Docker to start at boot
sudo systemctl enable docker

# For user you use your server with, enable docker commands
sudo /usr/sbin/usermod -a -G docker <username>
# For example:
sudo /usr/sbin/usermod -a -G docker michael
# So this is the user that has home directory /home/michael
```

**Comment by xet7** [comment]
After that you could try on Linux server installing and running Wekan, changing port 8080:
```
docker run -d --restart=always --name wekan-db mongo

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost" -p 8080:80 mquandalle/wekan:0.10.0
```

**Comment by wreels** [comment]
I log in as virtual and then go to root from there.  So should I do the /usr/usermod command with virtual?

**Comment by xet7** [comment]
You can also try those commands on your Windows server

**Comment by xet7** [comment]
docker commands

**Comment by xet7** [comment]
You don't need to go to root if you add docker rights to virtual:
```
sudo /usr/sbin/usermod -a -G docker virtual
```

**Comment by xet7** [comment]
Ok this page seems to show how on Windows to get to type docker commands:
https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by wreels** [comment]
virtual don't have the rights.  I need to use root.  "virtual is not in the sudoers file.  This incident will be reported." lol sigh, one roadblock after another.

**Comment by xet7** [comment]
Ok sorry, you need to go to root and type this, because virtual does not have rights to add rights to itself:

```
/usr/sbin/usermod -a -G docker virtual
```

**Comment by xet7** [comment]
After that you can exit root and use docker as user virtual

**Comment by wreels** [comment]
big fail on Linux...  on to Windows... sigh

:~ # docker run -d --restart=always --name wekan-db mongo
Unable to find image 'mongo:latest' locally
Pulling repository docker.io/library/mongo
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mongo/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.

**Comment by AlexanderS** [comment]
@wreels Did you set `MAIL_URL`? If you register a user, wekan will send you a mal. If you do not have `MAIL_URL` configured, there will be an "Internal Server Error".

I think there is no reason to use docker, if you have a running standalone version.

**Comment by xet7** [comment]
@AlexanderS 

What should MAIL_URL be in internal network? When I installed Docker version it did not ask for mail url, if I remember correctly.

**Comment by wreels** [comment]
I was a little confused about that setup.  It has export MAIL_URL='smtp://user:pass@mailserver.example.com:25/' but I'm not sure what that equates to for outlook exchange server.

**Comment by wreels** [comment]
not practical to have my user and password there for environment variable, plus my password must be changed - so I didn't think that's what it was asking for.  I hope not.

**Comment by xet7** [comment]
try:
MAIL_URL='smtp://user:pass@mailserver.example.com:587/'

**Comment by AlexanderS** [comment]
If there is no relaying mail server, that is willing to deliver mail without authentication for your host, then you have to supply your user and password. But typical there is some mail server that delivers mail from a server network without authentication (or if you only need mail delivery to your internal users, you can simply submit the mails without authentication at the responsible mail server).

**Comment by wreels** [comment]
@AlexanderS 
I've only ever be able to used
 CDO.Message for something like this but not sure anything like that can be used with this.

	Set oMessage = CreateObject("CDO.Message")
	oMessage.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/sendusing") = 2 
	oMessage.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserver") = strSMTPRelay
	oMessage.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserverport") = 25 
	oMessage.Configuration.Fields.Update

**Comment by AlexanderS** [comment]
The value of `strSMTPRelay` should maybe work. But I do not know your setup.

**Comment by wreels** [comment]
Tried with my credentials and mail server and didn't get an email on the register. I will try with http://schemas.microsoft.com/cdo/configuration/smtpserver.

**Comment by wreels** [comment]
that didn't work but I went back to my credentials and it worked!  I don't know why but I setup test ID with my credentials and a different email address as I was using before and it allowed me to log in.  I wonder if all my other attempts failed because the MAIL_URL wasn't setup properly and I kept using the same email address for each ID?  Now... How do I setup an admin account?  How do I remove all the other failed accounts that I've already setup?  if I tried to reenter it, it said it already existed - so they accounts were created, I just couldn't log in with them for some reason.

**Comment by xet7** [comment]
Nice! 

Just drop database, it will be created again on browser refresh:

```
mongo
use admin
db.runCommand( { dropDatabase: 1 } )
exit
```

**Comment by wreels** [comment]
oh and before I forget, how do I get the wekan service to start when the server is rebooted?

**Comment by wreels** [comment]
did the database drop but doesn't seem to have cleared the bad users out.  plus I was still able to get in with the user that worked for me.  what am I missing?

**Comment by xet7** [comment]
Ok there's still data left. Create textfile dropall.js with this contents:

```
var dbs = db.getMongo().getDBNames()
for(var i in dbs){
    db = db.getMongo().getDB( dbs[i] );
    print( "dropping db " + db.getName() );
    db.dropDatabase();
}
```

And then run:

```
mongo dropall.js
```

And then reload webpage.

**Comment by wreels** [comment]
two questions.  Do I just vi dropall.js and paste that code into it and save it?  Also, I noticed after doing a show databases that there are two.  Is that why the drop didn't work for the wekan database?  it cleared local and left the wekan database alone?

> show databases
local  0.000GB
wekan  0.001GB

**Comment by xet7** [comment]
Yes, textfile with vi and save.

You should all databases with that command: mongo dropall.js

**Comment by wreels** [comment]
@AlexanderS 

Wanted to give a big thanks to you too!  Your tip on the URL took me over the hurdle!  Much appreciated!

**Comment by wreels** [comment]
yeah, with the way things have gone these three weeks.  couldn't have been that easy.  lol mommy make it stop.
~ # mongo  dropall.js
MongoDB shell version: 3.2.8
connecting to: test
2016-08-01T22:30:55.771-0400 E QUERY    [thread1] SyntaxError: expected expression, got '=' @dropall.js:1:1

failed to load: dropall.js

**Comment by xet7** [comment]
For getting wekan running at boot, check node command path:
```
which node
```

As root, create this textfile /etc/systemd/system/wekan@.service , it assumes your wekan files are under user virtual, also change full path to your node and wekan main.js:

```
; see `man systemd.unit` for configuration details
; the man section also explains *specifiers* `%x`

[Unit]
Description=Wekan %I
Documentation=https://wekan.io
After=network-online.target
Wants=network-online.target
Wants=systemd-networkd-wait-online.service

[Service]
; run user and group for wekan
User=virtual
Group=virtual
ExecStart=/usr/local/bin/node /path/to/main.js
Restart=on-failure
RestartSec=10
; create a private temp folder that is not shared with other processes
PrivateTmp=true
; limit the number of file descriptors, see `man systemd.exec` for more limit settings
LimitNOFILE=8192

[Install]
WantedBy=multi-user.target
```

Then change file permissions of that file and enable service for user virtual:
```
chmod 644 /etc/systemd/system/wekan@.service
systemctl start wekan@virtual
systemctl enable wekan@virtual
```

**Comment by xet7** [comment]
Maybe first line is missing ; at end

```
var dbs = db.getMongo().getDBNames();
```

**Comment by wreels** [comment]
recreated the file and it appears to have worked.  checking now

**Comment by xet7** [comment]
You may need to do as root
```
service mongo restart
```

or:

```
service mongod restart
```

I was already beginning to suggest trying this instead if it did not work:
```
mongo
var mongo = db.getMongo(); mongo.getDBNames().forEach(function (dbname) { var db = mongo.getDB(dbname); db.dropDatabase(); });
exit
```

**Comment by xet7** [comment]
Or maybe mongo is running under systemd, run as root:

```
systemctl restart mongo
```

**Comment by xet7** [comment]
Sorry, I forgot to add Wekan environment variables to service, change and add those all to the Environment line below separated by spaces:

```
; see `man systemd.unit` for configuration details
; the man section also explains *specifiers* `%x`

[Unit]
Description=Wekan %I
Documentation=https://wekan.io
After=network-online.target
Wants=network-online.target
Wants=systemd-networkd-wait-online.service

[Service]
; run user and group for wekan
User=virtual
Group=virtual
ExecStart=/usr/local/bin/node /path/to/main.js
Restart=on-failure
RestartSec=10
; create a private temp folder that is not shared with other processes
PrivateTmp=true
; limit the number of file descriptors, see `man systemd.exec` for more limit settings
LimitNOFILE=8192
Environment=NODE_ENV=production PORT=1337

[Install]
WantedBy=multi-user.target
```

I will also update previous post.

**Comment by wreels** [comment]
don't know what happened but now after doing the dropall.js I'm back to Internal server error.  ugh and I've confirmed that the MAIL_URL has my credentials..  make it stop!

**Comment by xet7** [comment]
Ok sorry, something is messed up, as root you need to uninstall, cleanup and reinstall mongo:

```
service mongod stop
zypper remove $(rpm -qa | grep mongodb-org)
rm -r /var/log/mongodb
rm -r /var/lib/mongo
zypper -n install mongodb-org
service mongod start
chkconfig mongod on
```

**Comment by wreels** [comment]
for some reason I got export the Internal server error but when I tried to log in with the user ID and password it allowed me in.  No idea what's the deal with this.  It's late bud - I think I'm going to bed.  Tomorrow is another day.  That thing with the wekan service looks a bit confusing to me.  I'll try to follow it tomorrow.  I want to thank you once a gain for your patience and kindness for helping me with this.  You are one of kind ones in the world.  :) thanks again and good night...

**Comment by xet7** [comment]
Thank you also for your patience in trying, and good night, let's continue later :)

**Comment by xet7** [comment]
@wreels 

I tested on same version of SUSE you have on AWS cloud, it seems that firewall settings are missing from your install. Check you have done all steps in documentation I just wrote:

https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-on-SUSE-Linux-Enterprise-Server-12-SP1

**Comment by xet7** [comment]
@wreels 

It's also possible to use Wekan in VirtualBox image on your Windows Server:

https://github.com/wekan/wekan/wiki/virtual-appliance

I created yesterday new VirtualBox image, it's option 2) on that webpage.

**Comment by xet7** [comment]
Now there is new version of Wekan Docker image with new feature, and it also works on Docker on SLES12SP1. If there are any other problems, add a new issue.

Closing issue.

**Comment by enrichilversum** [comment]
Hi all, writing from the future here (2019). 

Short comment plus answer and solution:

I just got this error too, login forbidden, on Ubuntu 18.04 / snap after registering a user. This is a local setup and I am logging in from another machine.

**The solution** is just to restart mongodb : 

`sudo snap restart snap.wekan.mongodb`

It worked without restarting wekan proper, but it won't harm either.
After that you can just sign in with the user you just created, despite the previous error.
If you try to register again you will get a "user already exist" error. 

So, that's it.

I also stopped Apache as it was getting in the way when I tried calling the page using port tcp/80 and it was also interfering when using port tcp/3001 causing the infamouse "404 error" when clicking on the cards.

;)



Just for the records, that's my snap: 

snap    2.37.4+18.04.1
snapd   2.37.4+18.04.1
series  16
ubuntu  18.04
kernel  4.15.0-46-generic
