### ISSUE TITLE
Question about forking

### ISSUE THREAD

**Issue by rooney** [wekan/wekan#662]
Hello,

First, I want to thank you for the great work. Kudos!

I'm trying to repurpose Wekan to be a research management app. I need different terms for the objects (e.g. Trials, Forms), customize the actions on them, and also customize the UI of the "details" views (e.g. add some input boxes and checkboxes).

What is the best way to achieve that? My concern is if I fork the project, there will be lots of conflicts later when there's changes upstream. Or if I shouldn't worry about that? Is the project structure stable enough that such conflict will be rare if I do rebase not merge?

Any suggestion?

Thanks in advance.

**Comment by xet7** [comment]
Yes, Wekan is moving fast. I recommend working with existing feature requests like adding API, programmability etc and contributing them directly to Wekan, because then you don't get benefits of other new features also.
