### ISSUE TITLE
Title changes after a couple of seconds

### ISSUE THREAD

**Issue by hendricius** [wekan/wekan#663]
Great work on wekan - it's amazing. I wanted to change the title of the application to something different. However after a few seconds the title is automatically updated, despite me having something different set in the `layouts.jade`

Could this value come from the database? I also did not find the `Wekan` title in any of the translations.

Thanks!

**Comment by AlexanderS** [comment]
You may need to change it at a few other locations. You should look into `config/router.js` and `client/lib/popup.js`. (And maybe `client/components/main/header.jade` for the header logo and the alt text.)

**Comment by hendricius** [comment]
I feel stupid. I searched for `"Wekan"` not `'Wekan'`. Thanks!
