### ISSUE TITLE
User removed from Board continue receiving email updates of that Board

### ISSUE THREAD

**Issue by bonniec11** [wekan/wekan#667]
Hi,
I have deployed Wekan's v0.11.0-rc2 release on Bluemix and have been testing it for a while.
I have an issue with email notifications.
A user was removed from a Board but is still being notified (by email) of the updates on that board.
He can't change his subscription configuration on the cards or activities in the board because he is not a member of the board anymore.
Probably Wekan should implement a unsubscription flow in cascade when a user is removed from a board.

**Comment by AlexanderS** [comment]
I can confirm that this is currently not handled. It could be added to the `Boards.after.update` hook when creating the activity for removing a member.
