### ISSUE TITLE
[Sandstorm] "Link to this card" option only displays partial URL

### ISSUE THREAD

**Issue by neynah** [wekan/wekan#671]
![image](https://cloud.githubusercontent.com/assets/855341/17820156/31e40028-6600-11e6-9002-a0716048ad6f.png)

**Comment by mrshu** [comment]
I can confirm that I also ran into this on sandstorm.

Maybe the fix is similar to what @mquandalle replied in #679

**Comment by xet7** [comment]
With today's merged https://github.com/wekan/wekan/pull/1087 link to this card is visible again, and link can be drag-selected with mouse fully and copied to clipboard.

This fix is not yet in release version of standalone Wekan and also not on Sandstorm.

**Comment by xet7** [comment]
This is already fixed in Wekan, and will be in next version for Sandstorm.
