### ISSUE TITLE
Renaming an imported Trello board duplicates it

### ISSUE THREAD

**Issue by NatsumiHoshino** [wekan/wekan#672]
I am not sure if the issue also applies to regular board, it could be the case. At the very least renaming the Welcome Board didn't cause any issues.

Repro steps:
- Import a board from Trello using the wizard
- Rename the imported board

The board then appears on the board list twice: once with the previous name, once with the new name.

**Comment by nztqa** [comment]
I can't reproduce it on Wekan 0.26
