### ISSUE TITLE
Cannot find module 'xss'

### ISSUE THREAD

**Issue by vusalalishov** [wekan/wekan#673]
Hello.

I deployed wekan, but when I try to access wekan via browser, I get error on client side:
`Uncaught Error: Cannot find module 'xss'`

CentOS 7
node v0.10.41
Meteor 1.3.5.1

Please help me to solve this problem.

**Comment by AlexanderS** [comment]
Did you deply it from source or do you used the docker image? Maybe you need to execute:

```
meteor npm install --save xss
```

**Comment by vusalalishov** [comment]
I deploy from source. I tried to install xss, but it's not solved problem.

Eventually, I installed node 0.10.41 and reinstalled meteor.
