### ISSUE TITLE
Case-sensitive email handling

### ISSUE THREAD

**Issue by Zetten** [wekan/wekan#675]
There is some inconsistency in the handling of email addresses between the various login/registration/password reset forms.

One of the accounts in our Wekan instance was registered with the email string `John.Smith@example.com`. This is fine - John gets his activation email and he can log in, and everything works nicely.

But if John forgets his password, the reset password form apparently tries to a) lowercase the email address before b) looking up the user with a case sensitive query. This results in 'User not found' errors for both `john.smith@example.com` and `John.Smith@example.com`.

Trying to register a new account resulted in 'User already exists' errors for both case variations, so that form is apparently not case sensitive. I'm not sure about the login form, but I assume that was also working fine with a lowercase email login, i.e. not case sensitive.

It was possible to work around this by attaching to the mongodb instance and manually updating the user record to set the email address to lowercase.

**Comment by nztqa** [comment]
@xet7 
Target package: https://atmospherejs.com/useraccounts/core
It has been fixed.https://github.com/meteor-useraccounts/core/commit/2e8986813b51f321f908d2f6211f6f81f76cd627
but,last master branch is not the same publish on atmosphere.
