### ISSUE TITLE
Cannot install wekan

### ISSUE THREAD

**Issue by raz99** [wekan/wekan#677]
Hi,

  I am trying to install wekan on Ubuntu 16 using https://github.com/anselal/wekan and I get following error

1733 error Linux 4.4.0-34-generic
1734 error argv "node" "/root/.nvm/v0.10.40/bin/npm" "install"
1735 error node v0.10.40
1736 error npm  v3.10.6
1737 error code ELIFECYCLE
1738 error fibers@1.0.13 install: `node build.js || nodejs build.js`
1738 error Exit status 1
1739 error Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
1739 error Make sure you have the latest version of node.js and npm installed.
1739 error If you do, this is most likely a problem with the fibers package,
1739 error not with npm itself.
1739 error Tell the author that this fails on your system:
1739 error     node build.js || nodejs build.js
1739 error You can get information on how to open an issue for this project with:
1739 error     npm bugs fibers
1739 error Or if that isn't available, you can get their info via:
1739 error     npm owner ls fibers
1739 error There is likely additional logging output above.
1740 verbose exit [ 1, true ]

  Anyone knows how to fix this?

Best Regards,
Razvan

**Comment by xet7** [comment]
@raz99

Possible answers:

1) You need to install newer npm:
sudo npm -g install npm

2) That install script is for init.d systems like Ubuntu 14.04, while Ubuntu 16.04 uses systemd so it would require changes. It would be easier for you to install Wekan using Docker instructions at Wekan wiki.

**Comment by AlexanderS** [comment]
@raz99 It looks like you are using node-4.4. That's currently not supported. See #634.

**Comment by xet7** [comment]
Today's release v0.19 works on Node v4.x.
