### ISSUE TITLE
Reverse Proxy with multiple locations

### ISSUE THREAD

**Issue by fr4g3r** [wekan/wekan#678]
Hey Guys,

i cant seem to get reverse proxy with nginx in combination with wekan and jenkins to run properly.

Im trying to set a custom location 

$ cat /etc/nginx/sites-enabled/wekan -->

```
        location /wekan {

            client_max_body_size 10M;

            proxy_set_header Host $http_host;

            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_read_timeout 120;

            proxy_connect_timeout 10;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_pass http://localhost:1234/;

         }
```

but it doesnt work. I think it somehow corresponds to the usage of absolute url paths(?).

**Comment by xet7** [comment]
My nginx-fu is a little rusty. I have used Wekan with Caddy where proxy setup is easy:
https://github.com/wekan/wekan/wiki/Let's-Encrypt-and-Google-Auth

Are you sure you need all those timeouts? Wekan uses websockets that could be long running, Nginx may have some configuration needed.

If you use basic auth somewhere, there could be some clashes if both Caddy and Jenkins have basic auth enabled:
https://forum.caddyserver.com/t/basicauth-not-working-in-conjunction-with-proxy/273

**Comment by fr4g3r** [comment]
Did you try using wekan with caddy but with another path? If i use wekan on "/" it works perfectly fine.
If i try another Path the uri is wrong (double slashes). You are right, i should remove them.
https://discuss.wekan.io/t/how-to-run-docker-container-on-a-subfolder-behind-nginx-proxy/43

there seems to be a commit, but it doesnt seem to be fixed for me properly.

**Comment by jaimeagudo** [comment]
Thanks a lot for sharing this great work, first of all 😄 👏 

I am facing the same "double slash" problem here and I have read all the relevant issues from https://discuss.wekan.io/t/how-to-run-docker-container-on-a-subfolder-behind-nginx-proxy/43 
and tried different non trailing slash configs I can think of

```nginx
upstream wekan_upstream {
    server 127.0.0.1:8888;
    keepalive 64;
}


server {
        listen 443 ssl;
        listen [::]:443 ssl;
      

        location /wekan {
            proxy_pass http://wekan_upstream/wekan;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_max_temp_file_size 0;
            proxy_redirect off;
            proxy_read_timeout 240s;
        }

}
```

```bash
export ROOT_URL='https://mysite/wekan'
meteor -p 8888
```

Any updates on this @mquandalle  ? Kind Regards

**Comment by nammn** [comment]
@jaimeagudo this project seems to have died, because the main contributor/repository-owner has left the project. 

There is a actively developed fork. Did you try: https://github.com/wefork/wekan?
Other people seem to be more successful with caddy instead of nginx.

**Comment by xet7** [comment]
@jaimeagudo 

The double slash issue is the same for Apache, Nginx and Caddy and the reason is buggy FlowRouter. @Serubin is working on testing bugfix https://github.com/kadirahq/flow-router/pull/691 for it, but it's not integrated to Wefork yet. Integrating requires to fork FlowRourer using multiple packages and host them under Wefork GitHub organization.

Double slash issue at Wefork is:
https://github.com/wefork/wekan/issues/49

After your 0.10.1 version there has been many other bugfixes and new features in Wefork.

**Comment by ckuhn203** [comment]
[Flow Router seems to be dead][1], but if we can somehow switch the URL generation from absolute to relative, we could solve the issue. My problem is that I can't seem to find anything in the client code that's creating the //b/ urls. 

[1]:https://github.com/kadirahq/flow-router/issues/677

**Comment by Serubin** [comment]
@ckuhn203 This is the relevant issue comment that shows the issue in detail: [wefork#49](https://github.com/wefork/wekan/issues/49#issuecomment-274506388)

Any further discussion with the //b/ issues should be kept to wekan#785 for consistency.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/785
