### ISSUE TITLE
Cannot install wekan 

### ISSUE THREAD

**Issue by taichen** [wekan/wekan#680]
wekan master
E:\ceshiwekan\wekan-master>meteor

=> Started proxy.
=> Meteor 1.4.1.1 is available. Update this project with 'meteor update'.
=> Errors prevented startup:

   While processing files with stylus (for target web.browser):

   C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.5_1\mt-
os.windows.x86_32\tools\static-assets\server\mini-files.js:34:13:
   Surprising path:
   /Users/Administrator/AppData/Local/.meteor/packages/stylus/2.512.5/plugin.com
pileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/l
ib/nib/size.styl
   at toDosPath
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.5_1\mt
-os.windows.x86_32\tools\static-assets\server\mini-files.js:34:13)
   at Object.convertToOSPath
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.5_1\mt
-os.windows.x86_32\tools\static-assets\server\mini-files.js:47:12)
   at Object.wrapper (C:\tools\fs\files.js:1341:25)
   at readFile
   (packages/compileStylusBatch/plugin/compile-stylus.js:119:21)
   at Array.map (native)
   at processSourcemap
   (packages/compileStylusBatch/plugin/compile-stylus.js:139:52)
   at StylusCompiler.compileOneFile
   (packages/compileStylusBatch/plugin/compile-stylus.js:169:23)
   at packages/caching-compiler/multi-file-caching-compiler.js:115:45
   at packages/caching-compiler/multi-file-caching-compiler.js:97:11
   at
   C:\Users\Administrator\AppData\Local.meteor\packages\stylus\2.512.5\plugin.c
ompileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async
\lib\async.js:182:20
   at replenish
   (C:\Users\Administrator\AppData\Local.meteor\packages\stylus\2.512.5\plugin.
compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\asyn
c\lib\async.js:317:21)
   at
   C:\Users\Administrator\AppData\Local.meteor\packages\stylus\2.512.5\plugin.c
ompileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\async
\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\Administrator\AppData\Local.meteor\packages\stylus\2.512.5\plugin.
compileStylusBatch.os\npm\node_modules\meteor\caching-compiler\node_modules\asyn
c\lib\async.js:221:35)
   at StylusCompiler.processFilesForTarget
   (packages/caching-compiler/multi-file-caching-compiler.js:95:11)

**Comment by AlexanderS** [comment]
This is an upstream problem: https://github.com/meteor/meteor/issues/5372

**Comment by mquandalle** [comment]
Good catch @AlexanderS!

**Comment by xet7** [comment]
Should work now ok on today's release v0.19.
