### ISSUE TITLE
Error: language zh does not exist

### ISSUE THREAD

**Issue by taichen** [wekan/wekan#681]
Error: language zh does not exist
There is no route for the path: /
TypeError: language is null

**Comment by qftgtr** [comment]
I encountered the same problem and this is fixed by [https://github.com/wekan/wekan/pull/682](https://github.com/wekan/wekan/pull/682)

**Comment by dwrensha** [comment]
Fixed by https://github.com/wefork/wekan/pull/4, which has now been pulled into this repo.
