### ISSUE TITLE
Hide system messages in the card

### ISSUE THREAD

**Issue by dinya** [wekan/wekan#683]
Is it possible to add the option to hide system messages (show only user messages)?

![wekan-hide](https://cloud.githubusercontent.com/assets/2182222/18262977/cd7a67ca-741f-11e6-8811-92d8e0c5e7aa.png)

**Comment by mario-orlicky** [comment]
Hi, do you want the option directly in a card or as the user property?

**Comment by dinya** [comment]
@mario-orlicky, Both or if this is hard work for user only

**Comment by xet7** [comment]
This had been already been done and merged to Wefork, and merged back to Wekan:
https://github.com/wefork/wekan/pull/19
