### ISSUE TITLE
White Screen of Death

### ISSUE THREAD

**Issue by pacolotero** [wekan/wekan#685]
Hi,

Upgrading my wekan site from v0.10.1 to v0.11.0-rc2 I get these errors in the browser (white screen):

```
There is no route for the path: /
Uncaught TypeError: Cannot read property 'toLowerCase' of null
```

**Node version** - v0.10.41

**Comment by TheFonix** [comment]
Yep I'm getting this too

**Comment by xet7** [comment]
Use newest Wekan Docker image:
https://github.com/wekan/wekan
