### ISSUE TITLE
Global activity log

### ISSUE THREAD

**Issue by stefnats** [wekan/wekan#686]
Hi,

i'd really like a global activity log for all boards that i'm subscribed to.
Right now i have around 8 boards and i need to click each and every one of those to look up the recent changes, a "global" or "overall" activity log on the right side would be a real time saver!
What do you say, does this make sense or is it already hidden somewhere?

**Comment by xet7** [comment]
@stefnats

Can you check does any of stats features mentioned here have this?

https://github.com/wekan/wekan/wiki/Features#stats
