### ISSUE TITLE
How to integrate with letsencrypt + nginx reverse proxy

### ISSUE THREAD

**Issue by mareeba** [wekan/wekan#691]
Just wondering if there is a guide on how to get this working (ideally using docker compose) with letsencrypt and nginx in a similar fashion to:

[https://help.nextcloud.com/t/nextcloud-nginx-reverse-proxy-letsencrypt-in-docker-containers/1687](url)

See:
[https://hub.docker.com/_/nginx/](url)
[https://hub.docker.com/r/jwilder/docker-gen/](url)
[https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/](url)
[https://hub.docker.com/r/wonderfall/nextcloud/](url)
[https://hub.docker.com/_/mariadb/](url)

Any help would be most appreciated!

**Comment by mareeba** [comment]
bump?

**Comment by mareeba** [comment]
Okay, if it's easier, how about some guidance on how to get this running with --->
https://hub.docker.com/r/steveltn/https-portal/

**Comment by AlexanderS** [comment]
There is currently no guide specifically targeting your desired setup. You can find some setups with docker in the wiki (f.e. https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production).

You can try to create a docker-compose for the letsencrypt stuff by yourself... Should be similar to the nextcloud stuff.

**Comment by jaimeagudo** [comment]
I have a working setup but without docker, running with `meteor -p` on ubuntu 16.04 if interested. This may help too https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx @mareeba

**Comment by xet7** [comment]
I added that related tutorial to wiki, and also another link to Let's Encrypt implementations:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config
