### ISSUE TITLE
0.11.0-rc2 : Link to this card blank

### ISSUE THREAD

**Issue by franckFleet** [wekan/wekan#692]
updating from 0.10.0 to 0.11.0-rc2 makes "link to card" shortcut field blank

**Comment by xet7** [comment]
@franckFleet

This is fixed in Wefork:
https://github.com/wefork/wekan

**Comment by xet7** [comment]
@franckFleet 

Wefork is merged back to Wekan. Use newest Docker version:
https://github.com/wekan/wekan
