### ISSUE TITLE
heroku deployment guide

### ISSUE THREAD

**Issue by srikrishnacj** [wekan/wekan#693]
is it is possible to deploy in heroku with out Logentries addon. with this addon heroku is asking for credit card details. I just want to use only free dyno in heroku.

**Comment by NatsumiHoshino** [comment]
You could simply edit out the logentries entry in app.json, in the "addons" array. As far as I know it shouldn't cause any issues. I am not using logentries either and am using a single free dyno in Heroku myself.

**Comment by xet7** [comment]
Someone should test at Heroku, and do deployment guide.

**Comment by adulenzy** [comment]
I have tested it and doesn't work. @xet7 did you solve this, please? I will be working on this in the coming days. Anyone interested to collaborate are most welcome.

**Comment by xet7** [comment]
@adulenzy 

I have never used Heroku. All help very welcome. Thanks!

**Comment by xet7** [comment]
It seems using Heroku is not so good idea:

https://news.ycombinator.com/item?id=28249216

If someone still would like to add Heroku support, please add PR.
