### ISSUE TITLE
Index into  card_comments

### ISSUE THREAD

**Issue by fmonthel** [wekan/wekan#702]
We have more than 400 users and 10000 cards in one instance
Mongodb database was 1600% load (16 CPU)
After putting this index, load go down to 40% :)

 db['card_comments'].createIndex({"cardId" : 1,"createdAt" : -1})

**Comment by fmonthel** [comment]
PR created : https://github.com/wekan/wekan/pull/736

**Comment by xet7** [comment]
This has been already merged.
