### ISSUE TITLE
Wekan crashes on startup

### ISSUE THREAD

**Issue by PrestonL** [wekan/wekan#705]
When trying to start wekan, this problem crawls up:

.meteor/packages/coffeescript/.1.1.4.elew99++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^

If you delete the .meteor directory, and reinstall meteor, it will eventually crash in the same manner.  Meteor will try to update itself at random and then the same crash will happen, and eventually wekan won't start at all.  Running on Debian Jessie

**Comment by xet7** [comment]
@PrestonL 

Can you try with these install instructions?
https://github.com/wefork/wekan/wiki/Install-from-source

**Comment by xet7** [comment]
Use newest Docker or Sandstorm version:
https://github.com/wekan/wekan

Closing issue.
