### ISSUE TITLE
Add Feature: Children/Related cards

### ISSUE THREAD

**Issue by hmrodrigues** [wekan/wekan#709]
It would be awesome to have some kind of relation between cards, like a link two or more cards

**Comment by xet7** [comment]
@hmrodrigues 

How it should work? What would it be used for?

**Comment by hmrodrigues** [comment]
@xet7 
You can have basic relations, kinda like related issues.
In my case for dependencies.

**Comment by xet7** [comment]
@hmrodrigues 

Does changing one affect the other one someway? Could you provide step by step instructions how this should work and how it would be useful?

**Comment by hmrodrigues** [comment]
@xet7 Not really. The process is just like labels. In Card1 you select Card2 as a related card.
This would be useful to relate card that aren't on the same label ,for example, you have a task that splits into four microtasks. Two of them with the label _FrontOffice_, one with _BackOffice_ and the another with _Core_. With the relations, you can have all those four microtasks connected.

**Comment by xet7** [comment]
Maybe something like this in kanbanflow?

![subtasks_at_kanbanflow](https://cloud.githubusercontent.com/assets/15545/22906208/37db96e8-f24c-11e6-8aa5-c890106bb59d.jpg)

**Comment by hmrodrigues** [comment]
@xet7 Yes kinda like that

**Comment by xet7** [comment]
Moved to here from #1092

From @yarons

I'm not sure I fully understood how to define a relation between two cards, lets pretend my card is about putting an entire footwear, I have another card for putting socks on and then I have a card for putting shoes on.
Can I define the relation between them to be that I can't go on with the footwear card until I finish the socks and shoes cards?

Thanks!

**Comment by anrras** [comment]
I understand is like more the powerup "helloepics" from trello [ https://helloepics.com/](Link)

**Comment by yarons** [comment]
@xet7, although you can wear shows without socks, the relation to socks in that case is a blocker, a task that unless completed the wearing shoes action may not be executed (completely or partially).

**Comment by xet7** [comment]
Moved to here from #1364

From @TNick

I want to implement categories for cards. Each card would belong to exactly one category that is, by default, `(un-categorized)`.

The category would determine the aspect of the cards:

- background color;
- presence / absence of a border;
- the shape of the minicard;

(*v2*) Each category can host a template for the card that might be applied to cards at any time.

Categories would be organized in a tree, with one (possibly) inheriting properties from its patent(s). The tree of categories should be edited in right side panel by going to `Menu->Categories`. The panel needs `Add sibling`, `Add kid`, `Remove`, and items can be re-parented by drag-n-drop. Deleting a category deletes all its kids. All cards that ware in a deleted category are reassigned to `(un-categorized)`.

Changing the properties of a category (aspect of cards) can be done in same panel; each should allow inheriting from the parent / using the default for top level categories.

Changing the category of a card should be possible when the card is expanded.

I'm looking into implementing this feature for my personal use and, if needed, I could contribute it to the project. This is my first attempt at Wekan, so any ideas or suggestions about how to go about this are highly appreciated.

**Comment by xet7** [comment]
@TNick  

Yes your features are welcome to Wekan. Please look at [Developer Documentation](https://github.com/wekan/wekan/wiki/Developer-Documentation) and add any questions and info or your progress to this issue. Thanks!

**Comment by xet7** [comment]
Related #211

**Comment by TiibCD** [comment]
Hi all,

Indeed it would be great to have dependencies between cards. 
For example Card A cannot move until all related cards aren't "done". Or just a feature to see a relation between cards parent/child would also be great

**Comment by d3dbit** [comment]
Great feature.

+1 to @TiibCD ' comment: 
"_For example Card A cannot move until all related cards aren't "done". Or just a feature to see a relation between cards parent/child would also be great like the "Helloepics" plugin_"

**Comment by xet7** [comment]
Children cards implemented by @TNick at https://github.com/wekan/wekan/pull/1723

**Comment by beingshashi** [comment]
@xet7 : Can it be possible to auto import to child card - whenever a new checklist is added to the parent card?

**Comment by xet7** [comment]
@beingshashi 

Please add new Feature Request issue with screenshot mockup and description how it should work.
