### ISSUE TITLE
nexe

### ISSUE THREAD

**Issue by vavrecan** [wekan/wekan#710]
hey, I think deployment is huge issue - because the app is depended on thousand of the libraries and does not work with ubuntu's node version out of box. 
I was thinking, do you think it would be possible to create single binary out of the wekan? Like using nexe? 
Would save a lot of pain and would be definitely huge improvement everybody would enjoy :+1:

**Comment by xet7** [comment]
@vavrecan 

It looks like nexe does not support building native extensions from source. Is there workaround for this?

**Comment by vavrecan** [comment]
There are workaround mentioned on the project site - excluding then from the build and including the compiled libraries in node_modules directoey. Hovewer, best would be avoiding such extensions (not sure if it is easy to replace them)

**Comment by xet7** [comment]
@vavrecan 

It there example how to use nexe? I have not used it yet.

**Comment by vavrecan** [comment]
should be easy as https://github.com/nexe/nexe#cli-usage (well because of native extensions it might be more painful)

**Comment by calebboyd** [comment]
There is limited support for native addons in nexe v2. Open an issue if you have questions! :)

**Comment by beppe9000** [comment]
I'd love to see official nexe'd releases for windows.

**Comment by xet7** [comment]
@beppe9000 

You can run Wekan on `Windows Subsystem for Linux` on Windows 10 by building from source. Docker could also work.
https://github.com/wekan/wekan/wiki/Windows

Sorry I only have Windows on very slow VirtualBox VM, it's not usable for development.

Someone with fast Windows computer could try does nexe work.

**Comment by beppe9000** [comment]
@xet7 too bad my windows version does not support that...

can I issue the nexe command in the docker container?

**Comment by xet7** [comment]
@beppe9000 

I don't know does nexe work on Docker. I did not get Wekan working yet directly on Win10.

Docker for Windows supports Linux containers like Wekan.

There is also VirtualBox version of Wekan at https://releases.wekan.team

**Comment by beppe9000** [comment]
I was able to get a docker container running wekan correctly on my windows machine, but `docker attach wekan-app` hangs...

**Comment by xet7** [comment]
For going inside container, try:
```
docker exec -it wekan-app bash
```
or for mongo
```
docker exec -it wekan-db bash
```
For settings etc, use docker-compose.yml at https://github.com/wekan/wekan

More info here:
https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
I have added some beginnings of Wekan build and run scripts to:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

**Comment by beppe9000** [comment]
What are the default credentials for root in the `wekan-app` container?

**Comment by xet7** [comment]
@beppe9000 

I don't know, Dockerfile does not set any root password, it uses gosu to install most things as user wekan, and runs container as user wekan. So I don't know is there any way to use root if you don't modify and build Dockerfile yourself.
https://github.com/wekan/wekan/blob/devel/Dockerfile#L271

But I don't know how it would be useful to run nexe in Linux Docker container. That only would make linux executeable. I would think you should try to install Wekan using Windows versions of node etc, to generate Windows executeable with nexe.

**Comment by beppe9000** [comment]
> But I don't know how it would be useful to run nexe in Linux Docker container. That only would make linux executeable. I would think you should try to install Wekan using Windows versions of node etc, to generate Windows executeable with nexe.

Nexe can do cross-platform builds from linux: [nexe/nexe#290 (comment)](https://github.com/nexe/nexe/issues/290#issuecomment-333013267), so I can make a test build for my linux shared hosting where i am not root, while I figure how nexe works and eventually how to include native windows dependencies.

**Comment by xet7** [comment]
@beppe9000 

Oh, I did not know that. I'll try that, I do have Linux build environment already.

**Comment by xet7** [comment]
Wekan Linux Docker containers seem to work fine on Docker on Windows 10.

![win10-wekan](https://user-images.githubusercontent.com/15545/48806635-9ab52080-ed23-11e8-9cd0-f8c1712e5df6.png)

**Comment by xet7** [comment]
@beppe9000

If you or some other Windows developer does not get this working, this will never work.

I can not fix this, I'm not fibers or Windows developer, see https://github.com/wekan/wekan/issues/2066#issuecomment-468680450

**Comment by beppe9000** [comment]
just adding some new information...

Nexe support seems to depend on the bundle package produced by `meteor build`. 
I tried to make a bundle and it spits a tarball with symlinks in it (7zip gives an access denied when extracting them on windows, the target seem inexistent). Ignoring the symlinks errors I tried to run the resulting package but received the infamous 'fibers not found' error...

**Comment by xet7** [comment]
At this article https://news.ycombinator.com/item?id=31068919 is mentioned:

From ISV_Damocles:

I've personally used `nexe` before and ended up swapping it out for Vercel's `pkg`[1]. `pkg` worked better with building ARM binaries and with less gotchas with multiplatform builds, in my experience.
[1]: https://github.com/vercel/pkg

I have not yet tried does it work with current WeKan, or with newer upgraded WeKan https://github.com/wekan/wekan/pull/4482

Anyone is welcome to try. Thanks!

**Comment by xet7** [comment]
Nexe does not work.

Combining everything to one executeable prototypes moved to https://github.com/wekan/wekan-node20
