### ISSUE TITLE
Error compiling to install

### ISSUE THREAD

**Issue by robisson** [wekan/wekan#714]
I tried in various ways to compile and install Wekan but always returns me the same error. I am following the step by step wiki. I've tried to node 5 and node 6 and using the Meteor 1.3.5.1 and no success.

Always shows the error below:

````sh
/root/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
````

Anyone else had this error ?

**Comment by AlexanderS** [comment]
Wekan currently does not work with node 5 or 6. Meteor 1.3 requires node v0.10.40. Please see #634.

**Comment by robisson** [comment]
That was it. Thankyou  @AlexanderS  .
