### ISSUE TITLE
Would you consider accepting money to develop a user admin?

### ISSUE THREAD

**Issue by kramer65** [wekan/wekan#720]
With our company we are currently looking at Wekan and restyaboard. From those two we absolutely prefer Wekan, but there is one thing missing for us: user administration.

We would like to be able to restrict user registration to a certain list of email addresses or maximum number of accounts per TLD or simply be able to invite people by email address. Furthermore we would like to be able to block users.

I see there is an open pull request which implements such an invitation mode: https://github.com/wekan/wekan/pull/618 . Unfortunately nothing seems to happen there.

I would like to ask whether you are open to accepting a fee to motivate the addition of such functionality to Wekan. If so, do you have a price in mind so that we can discuss this in our company?

We really enjoy Wekan and with this we would like to show our appreciation, help make Wekan suitable for our company and in the meantime also help the project forward. 

Kind regards

**Comment by soohwa** [comment]
> there is one thing missing for us: user administration.

+1 : I think the exact same thing ! And maybe many people is waiting for that too ^^

**Comment by mconsoir** [comment]
+1 That would be awesome!!!

**Comment by neeboo** [comment]
+1 no explanation needed :P

**Comment by xet7** [comment]
https://github.com/wefork/wekan/issues/13

**Comment by nordsmetal** [comment]
@xet7 it is good to have an admin panel, but unfortunately it is available to all user, only the link is not displayed to them, just for the first user. Also that "admin" user is available when it is a new installation. Not works if wekan is just updated(not the first user, or the first user registered after update become that "admin")

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/FAQ#will-my-feature-request-be-implemented
