### ISSUE TITLE
Interaction issues on windows surface

### ISSUE THREAD

**Issue by chongchai** [wekan/wekan#737]
Hello. l open it in the browser of surface and find a problem.
- drag and drop function for the card can't work when I use touch mode
It's working when I use mouse to drag. I also test it on my phone and it's OK.
So, I'm confused. 
Is anything I can do to make it work on my surface with touch mode? Anyone has a good clue on how to fix this?
 
my env:
wekan version is 0.10.0
win 10 Edge

**Comment by chongchai** [comment]
I checked the "card" in the html. It's in "<a></a>". And when I touch the card, a url box will pop up which I think cause the failure for dragging. Can anyone help to solve?

**Comment by xet7** [comment]
Please try newest Docker or Sandstorm version, more info at README.md at:
https://github.com/wekan/wekan
