### ISSUE TITLE
Docker installation; when clicking cards page always reloads

### ISSUE THREAD

**Issue by doughnet** [wekan/wekan#741]
I have a running/functioning Wekan.

Database: MariaDB latest
HTTP Proxy: caddyserver (works fine with all my other docker images that I proxy)
Wekan Version:  latest from Docker

The issue I am coming across is that every time I click on a card it does a page refresh flashes for a split second "The application is currently offline, refresh the page will cause data loss."  See image below:
![capture 399](https://cloud.githubusercontent.com/assets/9806529/20686685/82b5ecb0-b56e-11e6-910a-03b30ea4dfd3.png)

But the page will reload and the card will be selected as it should; see image below:

![capture 400](https://cloud.githubusercontent.com/assets/9806529/20686684/82b21270-b56e-11e6-8cde-ad08f92745a4.png)

I have a HTTP Proxy being used as transparent and with a websocket but it still causes this issue.  Any help would be appreciated.

**Comment by centigrade-thomas-becker** [comment]
Is your root url properly configured? I had a similiar problem where the root url was http but the page was served over https.

If the configured root url and the actual url from where the page is served are not exactly the same, then a click on the card will always trigger a page reload.

**Comment by thomasnaudin** [comment]
Agreed, I had exactly the same problem, @centigrade-thomas-becker solution solved it.
