### ISSUE TITLE
Altering user Email address?

### ISSUE THREAD

**Issue by lightweight** [wekan/wekan#742]
I have set up two Wekan instances using Docker... in both cases, I'm unable to find a way to alter my user's email address in the settings. Am I missing something?

**Comment by xet7** [comment]
@lightweight 

On standalone Wekan there is no admin settings yet, it's coming later:
https://github.com/wefork/wekan/issues/13
https://github.com/wefork/wekan/issues/52

Sandstorm version has admin settings.

**Comment by xet7** [comment]
Moved to #848
