### ISSUE TITLE
Emojis are bad sized

### ISSUE THREAD

**Issue by tchncs** [wekan/wekan#743]
Hi folks, i just experienced that emojis aren't adjusted to the font size:
![2016-11-30-011928_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/20734661/458e22ca-b69b-11e6-9936-8ef39af7d545.png)

latest release

**Comment by xet7** [comment]
When more markdown support was added with Wekan v0.55 , we don't have anymore conversion of text to emojis. Adding emojis is only possible with adding unicode characters and images in markdown. So this bug does not exists anymore.
