### ISSUE TITLE
when surport  node.jS ? cannot find example

### ISSUE THREAD

**Issue by liulover5** [wekan/wekan#749]
when surport  node.jS ? cannot find example

**Comment by xet7** [comment]
@liulover5 

Wekan uses Node.js version 0.10.x. Install instructions are at:
https://github.com/wefork/wekan/wiki/Install-from-source

There is feature request for newer Node.js version 4.x at:
https://github.com/wefork/wekan/issues/23
but nobody has started working on it yet.

**Comment by xet7** [comment]
Easiest way to run newest wekan is to run Docker container. This and more info at README.md at https://github.com/wekan/wekan .
