### ISSUE TITLE
Attached .MOV file non-responsive

### ISSUE THREAD

**Issue by ertanalytics** [wekan/wekan#750]
![image](https://cloud.githubusercontent.com/assets/7130518/21544353/ce0c6ada-cd93-11e6-9032-6abffb02ff06.png)

Chrome browser, sandstorm setup

**Comment by xet7** [comment]
On Wekan newest Sandstorm this seems to work for me, at least with small .MOV files.

When you upload .MOV file, you need to wait it to be fully uploaded, then above filename IMG_0003.MOV comes big text MOV. After that, you can right click Download link to save MOV file. And also delete MOV file.
