### ISSUE TITLE
Get overview of all current boards

### ISSUE THREAD

**Issue by sg6** [wekan/wekan#753]
Hello,

I haven't found anything like that in the current issues. Is there a possibility to create an overview of all boards? Something like this on Kanboard

![image](https://cloud.githubusercontent.com/assets/10222288/21605500/f33caf62-d1a9-11e6-8a55-98ad2c9a6c88.png)

Another really great feature would be: user can select some boards, and then see one giant "board" with all  columns and cards. This only makes sense, if multiple projects have the same column-structure and the columns are grouped (it should search for the name, case-insensitive). I have several projects with the same structure, and right now I have to click in each of them.

Thanks and have a nice day!

**Comment by xet7** [comment]
You can use REST API:
https://github.com/wekan/wekan/issues/1037

For layouts, see https://github.com/wekan/wekan/issues/781
