### ISSUE TITLE
Modify config in Wekan Docker container

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [wekan/wekan#754]
I want to change a few config values in my Docker container. I tried [a few things](https://github.com/wekan/wekan/issues/569#issuecomment-270376069) that did not work, until somebody mentioned that I had to rebuild the meteor app.

So now I am trying to retrace the steps that went into creating the [official Wekan Docker image](https://hub.docker.com/r/mquandalle/wekan/), and trying to find the correct build stept that I need to run again.

Using `docker history` I got the following output (reformatted):

```
IMAGE      CREATED         CREATED BY
sha256:17  5 months ago    /bin/sh -c #(nop) MAINTAINER Maxime Quandalle <mquandalle@wekan.io>                                           0 B
<missing>  5 months ago    /bin/sh -c bash $METEORD_DIR/on_build.sh                                                                      78.92 MB
<missing>  5 months ago    /bin/sh -c #(nop) COPY dir:6bf2ba39dcbf7e3aa13683f1642e9867b8bc20ec7ae72e89cf01a59881e58dea in /app           600.9 MB
<missing>  9 months ago    /bin/sh -c #(nop) ONBUILD RUN bash $METEORD_DIR/on_build.sh                                                   0 B
<missing>  9 months ago    /bin/sh -c #(nop) ONBUILD COPY ./ /app                                                                        0 B
<missing>  9 months ago    /bin/sh -c #(nop) MAINTAIN ER MeteorHacks Pvt Ltd.                                                             0 B
<missing>  11 months ago   /bin/sh -c #(nop) ENTRYPOINT &{["/bin/sh" "-c" "bash $METEORD_DIR/run_app.sh"]}                               0 B
<missing>  11 months ago   /bin/sh -c #(nop) EXPOSE 80/tcp                                                                               0 B
<missing>  11 months ago   /bin/sh -c bash $METEORD_DIR/init.sh                                                                          245.8 MB
<missing>  11 months ago   /bin/sh -c #(nop) COPY dir:f82128f87d4694453bb7aceb3279cc1e4e633f27a32c2d164368699a6f9a0ee8 in /opt/meteord   3.264 kB
<missing>  11 months ago   /bin/sh -c #(nop) ENV METEORD_DIR=/opt/meteord                                                                0 B
<missing>  11 months ago   /bin/sh -c #(nop) MAINTAINER MeteorHacks Pvt Ltd.                                                             0 B
<missing>  11 months ago   /bin/sh -c #(nop) CMD ["/bin/bash"]                                                                           0 B
<missing>  11 months ago   /bin/sh -c #(nop) ADD file:41fbf9f100beb805491bb568f69661f98b7403baf969f0b8f1a516ba80415135 in /              84.89 MB
```

I tried to run `init.sh`, `on_build.sh` and `run_app.sh`, but none had the desired result.  Also, I had to manually set the executable bit for these files first which seemed weird.

What exactly do I need to change the config value for `forbidClientAccountCreation` inside the Docker container?

**Comment by martingabelmann** [comment]
Have a look at the [meteord](https://github.com/meteorhacks/meteord) project, especially at the base and the onbuild tree which form the baseimage of the official wekan image. The executable bit isnt set because the scripts are usually called via `bash scriptname` but that should not be of interest since the build/run of the app is called by the entrypoint script of the meteor baseimage (with `ONBUILD RUN` statements).   
If I understood all this right one simply have to clone/fork the wekan project, do your changes under ./config/account.js and build the dockerimage from the provided dockerfile with `docker build -t wekan .`.

**Comment by xet7** [comment]
@centigrade-thomas-becker 

Are you trying to do something that is not yet possible by modifying environment variables in Docker Compose file?

https://github.com/wekan/wekan-mongodb

**Comment by centigrade-thomas-becker** [comment]
I think I opened this issue during the "wefork" period when I was trying to disable account creation. 

Since Wekan has this feature now this issue is moot.
