### ISSUE TITLE
wekan is stop to develop..?

### ISSUE THREAD

**Issue by manuelsongokuh** [wekan/wekan#759]
hi
i see nothing news for wekan, what is happen?

**Comment by ocdtrekkie** [comment]
Check out http://github.com/wefork/wekan

The original maintainer has gone silent, but the community is definitely alive and still interested in working on the project.

**Comment by manuelsongokuh** [comment]
oh THANK YOU! but site of wekan will can redirect to wefork/wekan?

**Comment by dcworldwide** [comment]
Glad to see the community is still working on it. What's the motivation @ocdtrekkie are you using it as a a template for an app, or is it purely to learn meteor?

**Comment by manuelsongokuh** [comment]
i want to ask you @ocdtrekkie 
my friend danilo did translate all in italian version, he used from other site: Transifex
 i want to know that wefork/wekan is update from transifex?

thank you for community is work on!!!

**Comment by ocdtrekkie** [comment]
@manuelsongokuh As the original maintainer is absent, we can't make any sort of redirects, unfortunately.

@dcworldwide I use the Sandstorm.io version of Wekan, and I try and help out here with information and such, though I'm not really a developer.

@manuelsongokuh I believe @xet7 just pulled in the latest from Transifex yesterday: https://github.com/wefork/wekan/commit/bdd88f486e28c02fa21a8c582a27e7d543e9c040

**Comment by manuelsongokuh** [comment]
ok thank you i will close here ok thank you
