### ISSUE TITLE
Cann't run wekan application

### ISSUE THREAD

**Issue by miherlosev** [wekan/wekan#762]
See [video](https://www.screencast.com/t/n7Y7K5AOgD) with reproduce.

**Comment by xet7** [comment]
@miherlosev 

You use too new Node.js version.

This is how newest Wekan is installed in Linux, it works now:
https://github.com/wefork/wekan/wiki/Install-from-source

And this is my progress when I tried to install Wekan in Windows, but did not get it working yet:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

If you can get it working in Windows, please update Windows install instructions wiki page.

Other way is to install to install Ubuntu on Windows version of VirtualBox.
There is old VirtualBox appliances at:
https://github.com/wekan/wekan/wiki/virtual-appliance
but they don't have newest changes.

**Comment by miherlosev** [comment]
Ok.
I also tried to install Wekan on Window and it didn't work.
Lately, I tried to install this on Linux

**Comment by xet7** [comment]
@miherlosev 

I fixed install from source instructions:
https://github.com/wefork/wekan/wiki/Install-from-source

I also created new VirtualBox appliance:
https://github.com/wekan/wekan/wiki/virtual-appliance

**Comment by xet7** [comment]
@miherlosev

@entrptaher today added new Windows instructions, you can try does it work for you:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows
