### ISSUE TITLE
Question: Adding new fields to models/cards.js

### ISSUE THREAD

**Issue by jLouzado** [wekan/wekan#764]
Hello everyone,

I'm trying to add a deadline feature to Wekan and I've added a date-picker and UI elements to the card, I've added all the callbacks in `CardDetails.js`, I've added an appropriate function in the `Cards.mutations` segment and yet I can't seem to get the actual field updated in the `db.cards` record.

I don't know what else to do, I've been trying to figure this out for a couple of days now. Any help would be greatly appreciated.

Regards,
-Joel

**Comment by ocdtrekkie** [comment]
As a useful note, the due date feature has already been added to Wekan in the community fork: https://github.com/wefork/wekan/pull/26

**Comment by jLouzado** [comment]
Thanks so much @ocdtrekkie will just shift to base my work off the wefork repo. So glad I reached out only a couple of days into working on this. >_<

**Comment by ocdtrekkie** [comment]
Yeah, sorry about that. The original maintainer has gone pretty silent, and nobody can updated or redirect people from the original repo. So I just try and point people along when I see them!
