### ISSUE TITLE
Add feature: Reordering of labels in the label panel

### ISSUE THREAD

**Issue by vanoudh** [wekan/wekan#767]
on the label panel, the labels appear sorted by creation date

it would be very nice to be able to reorder them manually, like we can reorder cards in a column

or more simply, have them ordered by color then name

the same order should be applied in the "filter cards" menu

**Comment by xet7** [comment]
In what version of Wekan?

1) original old Wekan

2) newest up-to-date Wefork https://github.com/wefork/wekan/wiki/FAQ
on
a) Standalone Wefork
b) Wefork on Sandstorm ?

**Comment by vanoudheusden** [comment]
old wekan (wekan:0.11.0-rc2)

**Comment by fmonthel** [comment]
Yes could be very helpful !
We're using label as project / category and sometime helpful to inject new project not at the end...

**Comment by SteamWind** [comment]
Hello, is it planned or updated?

**Comment by xet7** [comment]
@SteamWind  

AFAIK no, there is no bounties for this issue:
https://www.bountysource.com/issues/41078561-add-feature-reordering-of-labels-in-the-label-panel

Info about bounties:
https://wekan.team

All planned and in progress features are at [Roadmap](https://github.com/wekan/wekan/projects/2)

**Comment by xet7** [comment]
Addition: Those at roadmap that have "In Progress" are currently in progress, nobody has started or planned others yet.

**Comment by jhgovsi** [comment]
at least if labels were sorted (and grouped) first by colors and then by name by default...would be excellent!

**Comment by xet7** [comment]
Moved to #2295
