### ISSUE TITLE
Support of WebHooks?

### ISSUE THREAD

**Issue by shilch** [wekan/wekan#770]
First: Thank you for this nice project!

I would like Wekan to send messages to a Telegram group whenever an action happens (e.g. moving a card).
I thought of creating a WebHook that receives these changes and sends them to the group. But it seems that Wekan does not support WebHooks.

Is this a planned feature or is it already included and I can't find it?
If it is not available: Are there any alternatives to WebHooks?

Thank you in advance!

**Comment by shilch** [comment]
I did rewrite some code and added hooks by myself.

**Comment by garyritchie** [comment]
Is this something you can share in a PR or gist?

**Comment by xet7** [comment]
Outgoing Webhooks is now added to Wekan https://github.com/wekan/wekan/pull/1119

It's already available on Docker wekanteam latest and source installs.

**Comment by KrunalDholakiya** [comment]
@xet7 Is there any webhook for user login or user registration? If not can you please guide me to create it?

**Comment by xet7** [comment]
@KrunalDholakiya 

Login happens here:
https://github.com/wekan/wekan/blob/devel/server/authentication.js

Outgoing Webhooks are here:
https://github.com/wekan/wekan/blob/devel/server/notifications/outgoing.js

Activities are here:
https://github.com/wekan/wekan/blob/devel/models/activities.js

**Comment by KrunalDholakiya** [comment]
Thanks @xet7  😄

**Comment by KrunalDholakiya** [comment]
Hi @xet7 , I'm using ldap authentication in wekan, now I have separate python script which calls /users/login api to get token from wekan. But unfortunately I'm getting response as "Matched Failed" as response.

**Comment by KrunalDholakiya** [comment]
Hi @xet7 , I'm blocked because of the above issue, could you please help me on this?

**Comment by xet7** [comment]
@KrunalDholakiya 

You need to first login to REST API to get Bearer token:
https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data
```
curl http://localhost:3000/users/login -d "username=myusername&password=mypassword"
```
And then use the Bearer token in your next REST API call.

**Comment by xet7** [comment]
@KrunalDholakiya 

The username and password above is of Wekan Admin user that has Password login selected in Admin Panel.

**Comment by xet7** [comment]
Actually this issue is getting off topic to cover multiple topics. Please add separate new issues for those that are not answered yet and where there is no existing open issue yet about the exact topic, to:
- Wekan issues to https://github.com/wekan/wekan/issues
- Wekan LDAP issues to https://github.com/wekan/wekan-ldap/issues
