### ISSUE TITLE
Images distorted

### ISSUE THREAD

**Issue by carlito** [wekan/wekan#772]
Pretty basic: when I upload a square or portrait image and set it as a cover its not displayed in its original dimensions in the board.

(latest version)

**Comment by xet7** [comment]
@carlito 

Please include screenshot, and description how it should work.

**Comment by carlito** [comment]
![wekan-covers](https://cloud.githubusercontent.com/assets/111418/22558911/b8e5ccda-e96f-11e6-8b9b-5daa1bb26116.png)

That problem appears only for portrait and square images. Maybe this is even intentional because very high and narrow pictures will look weird in full height in a card – but I think this should be up to the user and the cover image should be in the original aspect ratio.

Thank you!

**Comment by nztqa** [comment]
Fixed: #548 
Please check with the latest version.
