### ISSUE TITLE
Add feature: Themes. Upload, switch and manage in settings.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#781]
Originally from @vanila.web.studio at Wefork Rocket.Chat.

Theme settings:
- upload, download themes, including CSS files, images etc
- on each board, it's possible to change what theme name to use
- changing theme name changes it everywhere. This way you can have different versions of same theme, like summer1, summer2, summer3 etc.

Example themes: 
- desktop, responsive
- mobile, responsive
- custom application for managing websites
- custom application for different kanban workflows

Themes should be based on Wekan theme, as we have no rights to use Trello theme.

Example theme screenshot from @vanila.web.studio :

![trello-by-franciscoamk](https://cloud.githubusercontent.com/assets/15545/22627534/72b16e6c-ebcd-11e6-998b-df3f9350261b.png)

**Comment by tugal** [comment]
I need this too 👍 
How can we achieve this ? plugins ? cause many template are involved...

**Comment by xet7** [comment]
@tugal 

There's no plugin system in Wekan.

Here are the steps how somebody wanting this feature would implement this:

1) User interface is defined by images and CSS. Currently it works so that some of those are generated with Wekan build process, that takes templates and and combines and minimizes final CSS. Building themes needs to be separated to different build script, that has option of theme name, so it saves theme to different named theme directory.

2) Theme is then archived to .zip file.

3) On Wekan Settings / Theme, there is list of themes, and those can be uploaded, renamed and downloaded.

4) When new theme is uploaded, it is unarchived on server, and all files are added to MongoDB.

5) In Theme Settings you can change what theme is used. That change then changes URLs on Wekan, so CSS points to for example themes/websitemanager/css/layout.css etc.

**Comment by tugal** [comment]
Hi,

So this feature only cover css & images, not templates ?

**Comment by xet7** [comment]
@tugal 

Please give more detailed description of what templates you mean, english is not my native language.

**Comment by xet7** [comment]
@tugal 

Do you mean https://github.com/wefork/wekan/issues/39 ? That's separate issue that is about board data, that could be added and copied to new board. This issue is about visual look: images, CSS, layout. Not board content.

**Comment by xet7** [comment]
@tugal 

I think board data also includes what theme that board uses. I'll update this issue description.

**Comment by jelenajjo** [comment]
I started working on theme and here is the first update on what I got so far, just by changing CSS.

![Theme update](http://image.prntscr.com/image/e26405aabd5847998296ef98470ab209.png)

**Comment by xet7** [comment]
Using .zip files would be too compicated, it would result in constant zip/unzip when making changes.

**Implementation plan v2**

1) User interface is defined by images and CSS. Currently it works so that some of those are generated with Wekan build process, that takes templates and and combines and minimizes final CSS. Building themes needs to be separated to different build script, that has option of theme name, so it saves theme to different named theme directory.

2) Like there is separate Archived cards, there would be list of Theme cards. Could same board have different views for Normal cards/Archived cards/Theme cards/other card types?

3) Card would have new option to checkmark it as:
[X] Theme card

4) Add images, css, etc theme files as attachments to Theme card.

_I don't know is this good idea:
Theme card does not need to be on the same board, it can be on separate board that Admin user also has access. But then, if only Admin has access to separate board that has Theme card, and users of board don't have access to board where Theme card is, how would we make it possible that users also have permission to see new theme on board?_

5) In board settings, select:
5.1) 1st dropdown list of Board names that admin has access.
5.2) 2nd dropdown list of of Theme cards in that board. This list should show only those cards that are checkmarked as Theme card.

6) When new Theme card is selected for that one board, URLs would be changed to use CSS and images from selected Theme card.

**Pro**

- If Wekan is running on Docker container, it can be replaced with new version of Wekan, as nothing is saved to Wekan container. All data including Themes are in MongoDB database.
- In Sandstorm, Wekan files are cryptographically signed and read-only. All changeable data is in MongoDB database, including Themes.
- We would not need to implement attachment upload logic for theme files

**Con**

- On Sandstorm, Theme card needs to be on same board as boards are in separate grains.
- Should Theme cards be completely separate, like Archived cards are in different place and not usually visible?
- If Theme does make Wekan unuseable, how do we make sure that it's possible to change back to working theme?

**Conclusion**

Please add your comment could this design work, or have I not considered some use cases etc in this properly. It's also possible that this is still more complicated, and it would be better to just have Theme menu with upload/download of theme files as one multi-file upload/download, and maybe .zip file option if that's needed by somebody.

**Comment by xet7** [comment]
This is related to https://github.com/wekan/wekan/issues/776

**Comment by elioqoshi** [comment]
That looks pretty good! I'd put the title of the board on the same place where it is currently in Wekan (same also in Trello). I'd give the list columns also a bit more opacity, to differentiate them a bit more.

I'm not the best to help with technicalities here, but I'd be happy to help with the UI

**Comment by xet7** [comment]
Please note, that any CSS and images from Trello will not accepted to Wekan.
There was already a lot of work done to create Wekan's own theme during previous time of DMCA takedown notice:
https://github.com/wekan/wekan/issues/92

**Comment by neooleg** [comment]
> I don't know is this good idea:
Theme card does not need to be on the same board, it can be on separate board that Admin user also has access. But then, if only Admin has access to separate board that has Theme card, and users of board don't have access to board where Theme card is, how would we make it possible that users also have permission to see new theme on board?

Not sure that I understood the idea. Is it means that I can apply different theme (sub-theme) per different board?

**Comment by xet7** [comment]
@neooleg 

Yes. Complete themes.

Admin Panel:
- List theme.
- Upload theme files, specity theme name (and version number).
- Download theme
- Edit theme name and version number, renaming it. Themes must have different names.
- Delete themes.
- Possibly: List all board names and themes, modify what theme is used.

Board settings:
- Select theme name and version number from dropdown list.

This Themes, API, programmability etc makes working like Jira possible:
- Multiple boards with different themes
- Showing cards vertically or horizontally
- Clicking something goes to another board that has another theme

API, programmability etc makes also possible https://github.com/johannesjo/super-productivity/issues/7

**Comment by neooleg** [comment]
@xet7,

thanks for sharing, looks good. Versioning is really important, nice to see it 👍 

However, what confuses me is (possibly) mixing very different features:

- Plugin API *which is **extra logic** and view*
- Themes *which is view (for existing UI)*.

Am I missing something?

**Comment by xet7** [comment]
@neooleg

There is separate open issues about API etc, I did not have time to link to those issue numbers. This issue is only about themes.

**Comment by xet7** [comment]
I'm [rethinking about Themes feature](https://github.com/sandstorm-io/sandstorm/issues/1713#issuecomment-306121342), mostly by having only minimal changes that other features need integrated in Wekan.

For Jira use case there would be only those different layouts where horizontal / vertical can be changed, and all this while still showing Wekan logo and having Wekan look and feel.

For full theme changes, users would need to use them on browser plugins so they would not make Wekan broken so easily.

**Comment by whittssg** [comment]
@jelenajjo Did you every finish you theme that you posted a while back? It was looking good, Thanks

**Comment by xet7** [comment]
I did chat with one company about implementation of General Themes feature, it they choose to try to implement this. Currently many companies have hacked Wekan web interface to:

a) have some kind of company theme, that is acceptable use

b) to have Trello theme, that if you use images and CSS from Trello, [is a DMCA violation and also why new Wekan theme was developed years ago](https://github.com/wekan/wekan/wiki/FAQ#why-does-wekan-look-so-different-now-compared-to--v09). Having Trello theme in Wekan repo, or hosted elsewhere by Wekan Team, is not legal.

For the a) case, requirements for implementing full themes feature:
- Upload/Download themes to Wekan as .zip archives to board, stored at MongoDB
- Select what theme board uses
- In Admin Panel see what boards have what themes uploaded, and way to globally reset to original Wekan theme, or reset theme of one board, so boards that have broken theme could be accessed again
- Documentation to Wekan GitHub wiki, how to update custom themes, when there is new feature added to Wekan, that changes original Wekan theme.

If some themes implementation has different way of implementing this, it could be good starting point also.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/FAQ#policy-about-wekan-ui-changes

**Comment by amitkparekh5** [comment]
> I started working on theme and here is the first update on what I got so far, just by changing CSS.
> 
> ![Theme update](https://camo.githubusercontent.com/ffba3d5710475e8b3052c24f148f898670921d8a/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f65323634303561616264353834373939383239366566393834373061623230392e706e67)

How can I get this theme?

**Comment by xet7** [comment]
@amitkparekh5 

I don't have code to that theme.

Wekan now has some themes:
https://github.com/wekan/wekan/wiki/Custom-CSS-themes
