### ISSUE TITLE
Add feature: WIP limits

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#783]
Moved to here from https://github.com/wefork/wekan/issues/86

Originally asked by @denisz1 

Doing Kanban without WIP limits isn't easy. Please add WIP limits, it's really essential.

"WIP limits" are central part of LEAN process - a team doing LEAN (or Kanban etc.) needs them. Otherwise kanban board is just a pretty thing without real management power.

Very good info is [many explanation videos on YouTube](http://www.youtube.com/results?search_query=kanban+OR+lean+wip+limits).
[This one is very good](http://youtu.be/hLuSAuVIpI8?t=1692), I linked to the exact time 28:12 in the video.
[Short one](https://www.youtube.com/watch?v=W92wG-HW8gg)

There are plenty of explanations. Just search "kanban wip limits", and maybe:
[JIRA has it](https://www.atlassian.com/agile/wip-limits)
[More](http://www.personalkanban.com/pk/primers/the-basics-of-limiting-wip-why-limit-wip-series-post-1/#sthash.Bbe2MjeY.SkPfwsXC.dpbs)
[More](https://kanbanize.com/blog/kanban-101-applying-wip-limits/)

**Comment by grokky1** [comment]
Agree we also use WIP limits, but since wekan doesn't have it, we duplicate some of the board on our physical whiteboard, and write the WIP limits manually. Sucks I know, but important.

**Comment by amadilsons** [comment]
@xet7 any idea of what the layout should look like for this feature?
Maybe ' WIP Limit {{ limit }} ' beneath the list title, with the option to edit the limit in the List Actions pop-up??

**Comment by amadilsons** [comment]
@xet7 any idea of how the layout for this feature should look like?
Maybe "WIP Limit {{ limit }}" beneath the list title and the option to edit it in List Activities popup? What do you think about that?

**Comment by grokky1** [comment]
@amadilsons I think it should be similar to how it's used elsewhere.

I think that maybe "WIP Limit (3)" is too "wordy". It should simply have the number next to the name, for example:

`Backlog (*) | Ready (6) | In-progress (3) | Testing (3) | Complete (*)`

Or something like that. The `"(*)"` is optional / unnecessary.

**Comment by amadilsons** [comment]
I'm not sure the user should be allowed to add more than the limit. Wouldn't that defeat the purpose of the WIP limit?
But I also agree it should be an option!
For now, I'll go for a simpler version of this feature, not allowing the user to add more tasks than the limit. 
After that, we consider solving that issue!

**Comment by grokky1** [comment]
@amadilsons I agree - in our team we never add more tasks than the limit!!! Like you said it defeats the purpose!

**Comment by synergico** [comment]
@grokky1 should it be something like ` In-progress (0/3)` for the limit? It would be rather confusing if only (3) there, people might think it is just the count number.

**Comment by grokky1** [comment]
@synergico I've seen it both ways. In my current team we use `(3)`. But in the past I've also seen `(1/3)`.

It depends on the maximum number:
- in a large team its better to have `(11/16)` because it's easier than counting the tasks in that column.
- but in a small team, the maximum is implied because you can see the max just by looking at the board. And that extra `/x` is unnecessary "noise".

Ideally it should be a config option. But that means more work.

I think you should decide what is easiest for you! :smile:
