### ISSUE TITLE
Download file(unicode filename) action cause server process crashed with exception.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#784]
Moved to here from https://github.com/wefork/wekan/issues/87

@yatusiter can you submit this as pull request to devel branch, so it shows you as author of fix in git history, and I can add you as contributor to changelog?

Originally by @yatusiter

When click download from card with unicode(Chinese) filename (upload is OK), the server process crash with following exception : 

> ./wekan/bundle/programs/server/node_modules/fibers/future.js:280
> throw(ex);
> ^
> TypeError: The header content contains invalid characters
> at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
> at ServerResponse.res.setHeader (/home/sjyb/install/wekan/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
> at packages/cfs_http-methods/http.methods.server.api.js:599:1
> at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
> at packages/cfs_http-methods/http.methods.server.api.js:595:1
> 

----
After googled around, it's seems the HTTP header "Content-Disposition" cannot accept unicode encoding characters, and should be binary or URI encoded.

[https://en.wikipedia.org/wiki/List_of_HTTP_header_fields](url)
[https://my.oschina.net/jsan/blog/180333](url)

Fix with this solution:
#bundle/programs/server/packages/cfs_access-point.js add after line 444, FS.HTTP.Handlers.Get function：
```
const originalHandler = FS.HTTP.Handlers.Get;
FS.HTTP.Handlers.Get = function (ref) {
//console.log(ref.filename);
  try {
     var userAgent = (this.requestHeaders['user-agent']||'').toLowerCase();

        if(userAgent.indexOf('msie') >= 0 || userAgent.indexOf('chrome') >= 0) {
            ref.filename =  encodeURIComponent(ref.filename);
        } else if(userAgent.indexOf('firefox') >= 0) {
            ref.filename = new Buffer(ref.filename).toString('binary');
        } else {
            /* safari*/
            ref.filename = new Buffer(ref.filename).toString('binary');
        }   
   } catch (ex){
        ref.filename = 'tempfix';
   } 
   return originalHandler.call(this, ref);
};

```

**Comment by xet7** [comment]
Possible to be related to https://github.com/wekan/wekan/issues/698

**Comment by yatusiter** [comment]
@xet7 glade to see wekan main repo continue working, I will submit a pull request soon:)

**Comment by xet7** [comment]
@yatusiter 

It seems that your pull request has been accepted to Meteor-CollectionFS.

Does something need to be changed in Wekan code to use it?

**Comment by yatusiter** [comment]
@xet7 nothing need to be modified in wekan. it's the problem of meteor cfs. Wekan attachment model just use the cfs store. All GET requests will chang the filename encoding after the modification of cfs.

**Comment by xet7** [comment]
@yatusiter 

Wekan uses old version of Meteor. When I rebuilt Wekan, fix was not there. Can you test?

**Comment by yatusiter** [comment]
@xet7 sorry that I am not familiar with meteor development .In my original post, temporary fix was intended to fix after built.
------
#bundle/programs/server/packages/cfs_access-point.js add after line 444, FS.HTTP.Handlers.Get function

----

Right now if the fix is not in the meteor framework package, I think it need some encoding transformation in attachment model for download handler. Do you have any idea where to perform the trans?

**Comment by xet7** [comment]
@yatusiter 

I will look at this later and make necessary changes. Thanks!

**Comment by nztqa** [comment]
Add support for IE11
IE11 keeps "Trident" in it's UA string, but drops MSIE.
```
if(userAgent.indexOf('msie') >= 0 || userAgent.indexOf('trident') >= 0 || userAgent.indexOf('chrome') >= 0)
```

**Comment by xet7** [comment]
@nztqa 

Your issue is moved to #1031

This issue is already closed.
