### ISSUE TITLE
Add feature: Board Templates

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#786]
Moved here from https://github.com/wefork/wekan/issues/39

**From @whittssg**

Once a board is setup allow the option to set the board as a template. Then when creating a new board add an option to create the board from a list of templates. Thanks

Includes board data:

- Lists
- Cards
- Comments
- Checklists
- Attachments
- Settings like what theme name is selected
- Members

Does not include:

- Themes https://github.com/wekan/wekan/issues/781

**Comment by killua-eu** [comment]
Added a bounty on this issue. Please see https://www.bountysource.com/teams/wekan/issues ...
Let me know if I can provide details to further implementation of this.

**Comment by xet7** [comment]
Moved to here from #1338

@whittssg 

Can you clean up that https://github.com/wekan/wekan/pull/446 and add as new pull request Wekan devel branch?

**Comment by whittssg** [comment]
@xet7  My new laptop arrives next week so hopefully it will have a bit more oomph to let me run some linux  VMs and get this done (i struggle to get anywhere with wekan dev and windows)

**Comment by rickywu** [comment]
Any update? Waiting for this feature

**Comment by andresmanelli** [comment]
I think this will be covered in #2165

**Comment by xet7** [comment]
Moved to #2165
