### ISSUE TITLE
Disable Admin page PR 618 in Sandstorm

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#790]
_From @davydov-vyacheslav on November 17, 2016 8:47_

Hi All,
taking in account the fact that you're moving all the stuff from wekan's pull requests here (I do appreciate that!) I think that it would be nice to have some kind of admin page (maybe even per each board). 
Let me explain ... I believe that the most of pull requests weren't merged by @mquandalle because of he would like to them as pluggin ... and I agree with him about this decision. Not all pull-request features are useful for all wekan/wefork users and there should be mechanism to disable one or several features. It would be less messy on the screen for users which want some kind of base functionality and I hope it would be faster a bit for them as they are not trigger odd database requests 

_Copied from original issue: wefork/wekan#13_

**Comment by xet7** [comment]
@davydov-vyacheslav 

I added this to wefork roadmap.

There is existing pull request on for admin page on original wekan/wekan project, I don't remember where. It would be helpful for somebody to find it and add link here.

I have not yet looked at status of plugin system. Anyway with or without it, there will settings option to enable or disable features in settings. Some platforms like Sandstorm turn those features off that Sandstorm platform already provides.

@mquendalle tried to do complete rewrite, and after that he has not had energy to review and accept pull requests for some months, that's why wefork exists. We are happy to merge back if he sometime comes more active.

**Comment by xet7** [comment]
_From @soohwa on November 17, 2016 16:1_

I don't remember if it was that pull request https://github.com/wekan/wekan/pull/618

**Comment by xet7** [comment]
@soohwa 

Thanks, that's the one I was looking for! There was probably something else also mentioned on original Wekan Gitter chat but I did not have time to scroll back chat history. If someone could find that that then it would be very helpful.

@kramer65

Did you get my email? Please see:
https://github.com/wefork/wekan/wiki/FAQ
https://github.com/wefork/wekan

**Comment by xet7** [comment]
_From @soohwa on November 17, 2016 17:6_

I found https://github.com/wekan/wekan/issues/353 and https://discuss.wekan.io/t/restrict-registration/71/3
And with the filter : https://github.com/wekan/wekan/issues?q=is%3Aissue+is%3Aopen+label%3AFeature%3AUser-accounts
And on the original chat at Mar 20 18:42 (Mahan @laupkram)

```
AccountsTemplates.configure({                                          // 11
  forbidClientAccountCreation: true,
  defaultLayout: 'userFormsLayout',                                    // 12
  defaultContentRegion: 'content',                                     // 13
  confirmPassword: false,                                              // 14
  enablePasswordChange: true,                                          // 15
  sendVerificationEmail: true,                                         // 16
  showForgotPasswordLink: true,                                        // 17
  onLogoutHook: function () {                                          // 18
    var homePage = 'home';                                             // 19
    if (FlowRouter.getRouteName() === homePage) {                      // 20
      FlowRouter.reload();                                             // 21
    } else {                                                           //
      FlowRouter.go(homePage);                                         // 23
    }                                                                  //
  }                                                                    //
});                                                                    //
                                                                       //
['signIn', /*'signUp',*/ 'resetPwd', 'forgotPwd', 'enrollAccount'].forEach(function (routeName) {
  return AccountsTemplates.configureRoute(routeName);                  //
});
```

**Comment by xet7** [comment]
@soohwa 

Thanks! I'll assign this to myself and start working on this.

**Comment by xet7** [comment]
There's

- translation updates mixed with pull request
- comments for variable naming that need to be checked and fixed

etc so this will take some time.

**Comment by xet7** [comment]
_From @soohwa on November 22, 2016 5:19_

No pb, anyway it's a good news that is underway ^^

**Comment by lkisme** [comment]
@xet7 It seems a lot happened here in Wekan project lately, a lot of PR got merged, I'm glad to see the project is moving forward. For the PR #618 , the original idea is to introduce "invitation only" capability to the system, then I thought a admin panel would be nice for this kinda feature, but @mquandalle had a plan(plugin?) for these kind of features, I closed the PR #618 because there were a lot conflict there, I'm planing open a new PR for the feature for review.

**Comment by xet7** [comment]
@lkisme

Admin panel and option to disable self-registrations are highly requested features, thanks!

Plugin system will not be implemented because of issues described in #781

I'm maintainer of Wekan currently. @mquandalle has not responded to requests mentioned in Wekan roadmap board for a long time.

**Comment by xet7** [comment]
@ocdtrekkie

I would really need a way to build Sandstorm .spk file to test how to disable something at Sandstorm:
https://github.com/wekan/wekan/issues/823

**Comment by ocdtrekkie** [comment]
I think @dwrensha pretty much detailed everything in #823 but it may just be best for him to PR that being disabled when he packages the new version. It sounds like a lot of this will be simpler after Wekan moves to a newer Meteor version.

**Comment by xet7** [comment]
Moved to #823

**Comment by dwrensha** [comment]
When I build the Sandstorm package, I don't see any admin UI that looks like it needs to be hidden. Is there anywhere in particular that I should be looking?

**Comment by xet7** [comment]
@dwrensha 

Admin Panel does need enabling in MongoDB, so I presume this does not currently affect Sandstorm:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v0111-rc2-2017-03-05-wekan-prerelease

With some future import/export feature it could probably be enabled, but not otherwise.
