### ISSUE TITLE
Q: upgrade of WeKan data?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#795]
_From @romu70 on December 14, 2016 16:34_

Hello,
Simple question: is there any feature on the roadmap to support a smooth upgrade from an existing WeKan instance? I think in particular of the data, some export/import capability.

_Copied from original issue: wefork/wekan#45_

**Comment by xet7** [comment]
@romu70 

All Wekan data is at MongoDB:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

Tell me if something does not work after changing to Wefork newest version:
https://github.com/wefork/wekan/wiki/Install-from-source

Then I could look if some migration scripts is needed.

Please try on separate non-production system copy first.

**Comment by xet7** [comment]
_From @romu70 on December 14, 2016 16:46_

To be honest, I don't run Wekan for the moment, and I'm looking at the best way to run it on my Synology nas. I thought I could run the SPK provided by the old project, but it targets an old version of the DSM, so it's dead. But the "install from source" is great, I can try to build a Docker image to run it. Thanks.

**Comment by xet7** [comment]
@romu70 

Problem with Synology nas ARM is that AFAIK Meteor is available only for x86_64 (and probably x86) so in those instructions if you don't have appropriate Node.js version you would use nvm instead of n to compile nodejs, and also with Meteor it could need a lot of recompiling. You could try to do Google search if somebody has managed to get Meteor working on ARM.

**Comment by xet7** [comment]
@romu70 

Also Sandstorm currently is x86_64 only, it's not available for ARM.

**Comment by xet7** [comment]
_From @romu70 on December 14, 2016 16:57_

That's why I bought a x86_64 Syno. It's just a PC with some nice nas features around.

**Comment by xet7** [comment]
@romu70 

Nice :) Ok try to install it and tell me how it goes.

Yesterday on original Wekan Gitter chat @weaktyper also was in progress to create new Dockerfile, it relates to https://github.com/wefork/wekan/issues/33 and I presume it will be contributed to Wefork replacing original Dockerfile if one pull request is accepted to some Docker base image of Meteor.

**Comment by xet7** [comment]
_From @ocdtrekkie on December 14, 2016 17:15_

If you have an existing Sandstorm grain backup for Wekan, it will work when restored to another Sandstorm server with Wekan installed. Sandstorm recognizes both as the same app.

But I'm a bit confused about your mention of the Wekan SPK (which is a Sandstorm app package) targeting "the DSM", because AFAIK, Wekan SPKs "just work" with Sandstorm, and generally don't work with anything else.

I recall the Sandstorm team wanting to support the Synology, but at the time, I think there was an issue with kernel features. (Though Sandstorm works on more kernels now, and they mentioned it should work better with the Synology now.) I think the best thing to do would be to tag some Sandstorm people here. @kentonv @paulproteus

**Comment by xet7** [comment]
@dwrensha has made Sandstorm-specific updates to Wefork, although I have not looked does Sandstorm use only Wefork now. Sandstorm may have additional requirements of kernel etc. For Sandstorm version multiboard features etc are not in use as environment variable option, as there's just one board object at a time that is set as public, and because Sandstorm handles authentication, sandboxing in grains etc.

Those install from source instructions are for standalone Wekan, without Sandstorm. Standalone version requires just Node.js, MongoDB and Meteor.

**Comment by xet7** [comment]
_From @ocdtrekkie on December 14, 2016 17:45_

@xet7 The newest version of Wekan on the Sandstorm App Market is based on Wefork. Sandstorm has an entry that tells it the app key David used for Wefork is a suitable replacement for the Wekan key held by Maxime, so people can easily upgrade from Wekan to Wefork.

If @romu70 wants to use Sandstorm on his device, and it isn't working, he can file an issue at github.com/sandstorm-io/sandstorm which may be a better place for that chat. But I am unsure exactly what we're trying to do.

@romu70 Do you have any current Wekan data you need to migrate? Is it from standalone Wekan or a Wekan grain backup from Sandstorm? And then are you looking to use standalone Wekan, or Wekan on Sandstorm on your Synology?

**Comment by xet7** [comment]
@romu70 

What kernel version does that Synology run? Are you able to upgrade kernel? I'm just thinking because Docker and Sandstorm both probably use same recent enough kernel features for sandboxing.

**Comment by xet7** [comment]
_From @ocdtrekkie on December 14, 2016 18:9_

Sandstorm's current kernel requirement, FWIW, is 3.10, and it no longer requires userns: https://sandstorm.io/news/2016-11-10-rhel-centos-arch-support

Meteor, on the other hand, pretty much runs on anything x86_64.

**Comment by xet7** [comment]
@weaktyper

Node serves that app. Meteor is the framework of Javascript etc code.

**Comment by xet7** [comment]
_From @kentonv on December 15, 2016 3:59_

Possible point of confusion: Synology packages are also called "SPK"s. These have nothing to do with Sandstorm. :/

**Comment by xet7** [comment]
_From @ocdtrekkie on December 15, 2016 4:39_

@kentonv Wow. That explains so much.

**Comment by xet7** [comment]
_From @romu70 on December 15, 2016 8:32_

Point to @kentonv. The confusion is all mine, sorry if I introduced some doubts in there. Yes, I thought the official Wekan SPK was a package for Synology, I didn't know Sandstorm uses the same extension.

Finally this is good, I just have to focus on the Docker image.

**Comment by xet7** [comment]
@romu70 

You can follow https://github.com/wefork/wekan/issues/33 about progress of self-created and official Docker image.

**Comment by xet7** [comment]
_From @romu70 on December 15, 2016 8:58_

I'm on it, thanks.

**Comment by xet7** [comment]
Upgrades to newest version of Wekan work, and this issue has gone somewhat offtopic. If you have any problems, please add new issue.

Closing issue.

**Comment by romu70** [comment]
Thanks a lot @xet7, I'll look at wefork#33. Sorry, I was totally disconnect for a while.
