### ISSUE TITLE
Add feature: Vote on cards, number of votes, average as result

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#796]
_From @xet7 on December 14, 2016 19:24_

Original issue: https://github.com/wekan/wekan/issues/130

_Copied from original issue: wefork/wekan#46_

**Comment by killua-eu** [comment]
Added a bounty on this issue. Please see https://www.bountysource.com/teams/wekan/issues ...
I'd prefer if both +/- wotes are allowed. Having alternative + while not clotting the user interface would be absolutely awesome.

**Comment by killua-eu** [comment]
Having +/-/whatever votes on comments would be nice too.

**Comment by xet7** [comment]
I don't know how to reach someone that has youtube video of vote feature:

https://youtu.be/8jQPqcNgKA0

**Comment by onthisearth** [comment]
@xet7 I contacted the Youtuber. Let's see, if he'll contact me :)

**Comment by d3dbit** [comment]
Hello all,
I think that the idea to vote and display the number of votes in the cards would be a nice feature.
Thanks for your effort.

**Comment by lynchmaniac** [comment]
Hi,
is anyone have some news about this feature ?
The feature on the video looks great.

**Comment by pablanopete** [comment]
@xet7 did you ever get in contact with the youtuber? maybe this would be worth a Gitcoin bounty; but I don't know how to define that scope in terms of how much time it could take.

**Comment by NicoP-S** [comment]
@xet7 I think this can be closed.
