### ISSUE TITLE
First wefork release

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#798]
_From @HLFH on December 16, 2016 10:49_

Hi,

Now that the Wekan community is relying on Wefork, can you make releases?
With Wefork, we have great features like https://github.com/wefork/wekan/pull/26.

So, it would be interesting to get a v0.11.0 release based on your master Wefork code.
It would be easier for a lot of people to deploy Wefork in production if you do that.

cc @xet7 @pierreozoux 

Thanks,
HLFH

_Copied from original issue: wefork/wekan#50_

**Comment by xet7** [comment]
What is required for release?

I could commit current devel to master branch. What else needs to be done?

**Comment by xet7** [comment]
_From @HLFH on December 16, 2016 11:0_

What is required for release? You could see that here: https://github.com/wekan/wekan/releases/download/v0.11.0-rc2/wekan-0.11.0-rc2.tar.gz

For now, there is no new release there: https://github.com/wefork/wekan/releases

From my side, I'm not sure how the previous developer M. Q. was releasing it but it shouldn't be difficult.

**Comment by xet7** [comment]
@HLFH 

Ok I'll try to make a release.

**Comment by xet7** [comment]
Done.

**Comment by xet7** [comment]
_From @HLFH on December 16, 2016 12:27_

Thanks!

**Comment by xet7** [comment]
_From @HLFH on December 16, 2016 12:30_

@xet7 EDIT:  but shouldn't we get also a tarball? like here: https://github.com/wekan/wekan/releases/download/v0.11.0-rc2/wekan-0.11.0-rc2.tar.gz

M.Q. was also releasing a .tar.gz tarball with less files than the full source code. https://github.com/wekan/wekan/releases/

**Comment by xet7** [comment]
@HLFH 

Yes there is already tarball at:
https://github.com/wefork/wekan/releases
https://github.com/wefork/wekan/releases/tag/v0.11.0

Direct link:
https://github.com/wefork/wekan/archive/v0.11.0.tar.gz

**Comment by xet7** [comment]
@HLFH 

Huh what kind tarball Meteor bundle is that? I'll try to figure out later how to create it.

**Comment by xet7** [comment]
_From @HLFH on December 16, 2016 12:40_

It seems that for now you provide the source code tarball but not the Wekan/Wefork release tarball.

Ok. Thanks. I'll search also from my side.

**Comment by xet7** [comment]
@HLFH 

Please do search, that would help a lot. I need to continue my actual non-related work project.

**Comment by xet7** [comment]
_From @AlexanderS on January 2, 2017 16:53_

@HLFH It's the meteor bundle. Created with `meteor bundle <output.tar.gz>`.

**Comment by xet7** [comment]
_From @HLFH on January 2, 2017 23:7_

@AlexanderS Thank you. Nevetheless, "WARNING: 'bundle' has been deprecated. Use 'build' instead".
So, I'm doing that:

```bash
su - wekan -s /bin/bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
nvm install 0.10.48
nvm use 0.10.48
wget https://github.com/wefork/wekan/archive/v0.11.0.zip
unzip v0.11.0.zip
cd wekan-0.11.0/
npm install
sudo -u wekan meteor build --server-only ../wekan-0.11.0
cd ../wekan-0.11.0/
curl --upload-file ./wekan-0.11.0.tar.gz https://transfer.sh/wekan-0.11.0.tar.gz
```
> Using the --directory option on `meteor build` will produce a bundle directory instead of the tarball. So, I don't use this option there.

@xet7 Could you add me as a `Wefork` collaborator, so I will be able to [submit/edit releases here](https://github.com/wefork/wekan/releases) when necessary?
https://transfer.sh/5obRm/wekan-0.11.0.tar.gz
OR: [wekan-0.11.0.tar.gz](https://github.com/wefork/wekan/files/681473/wekan-0.11.0.tar.gz)

**Comment by xet7** [comment]
_From @soohwa on January 3, 2017 0:47_

@HLFH thx :-) I updated https://github.com/soohwa/sps/blob/master/example/docs/1/wekan.md with your tarball https://github.com/wefork/wekan/files/681473/wekan-0.11.0.tar.gz

**Comment by xet7** [comment]
Wefork has been merged to Wekan.
Today released new Wekan v1.11.1-rc1 prerelease version includes precompiled version.

**Comment by ocdtrekkie** [comment]
@dwrensha Is it possible for you to package the release candidate for Sandstorm testing?

**Comment by dwrensha** [comment]
@ocdtrekkie I've uploaded a Wekan v0.11.1-rc1 SPK here:
https://oasis.sandstorm.io/shared/IA34GCqZGgqT4G5NHG-2d2WSIEPdNgVzvPy62r5Lx2e

**Comment by xet7** [comment]
@dwrensha 

I added that SPK to Wekan v0.11.1-rc1 release:
https://github.com/wekan/wekan/releases

**Comment by ocdtrekkie** [comment]
I've installed the rc1 spk on Alpha and upgraded a copy of my Ports in Progress Wekan grain. Everything _looks_ alright so far. I created a checklist with it, and that seems to work sanely as well. Keyboard shortcuts shortcut appears and operates correctly. Not sure if much else needs to be tested for Sandstorm.
