### ISSUE TITLE
HTML code entered in card description or comments is not escaped

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#801]
_From @HLFH on December 19, 2016 15:41_

Hi,

Wekan related issue: https://github.com/wekan/wekan/issues/556

> Any html code that is entered in a card's description or comments is not escaped and instead is parsed by the browser. The card title escapes html code properly.
This allows external resources to be embeded in the page instead of attached, including iframes. This also makes using wekan to track development of html code very difficult as everything entered has to be manually escaped.
If this is intentional then please provide an option to turn code escaping on and off.

Please support HTML code within some markdown.

_Copied from original issue: wefork/wekan#53_

**Comment by xet7** [comment]
_From @HLFH on December 19, 2016 15:44_

Hum. I'm testing it right now again and it seems it works within some markdown.
Can you confirm it from your side ? So then we will close https://github.com/wekan/wekan/issues/556 and https://github.com/wefork/wekan/issues/53

Thanks!

**Comment by xet7** [comment]
@ProCycleDev @HLFH

I upgraded xss dependency to newer version. Can you test Docker image, is this still a problem?

**Comment by HLFH** [comment]
@xet7 Thanks. I'll update my Wekan. I will try tonight.

**Comment by ProCycleDev** [comment]
Our Wekan is a manual install so we do not use docker. However if input is being sanitized properly then this bug is fixed. Sanitized HTML code should appear without being parsed by the browser.

**Comment by HLFH** [comment]
@xet7 I tested https://github.com/wekan/wekan/releases/download/v0.11.1-rc1/wekan-0.11.1-rc1.tar.gz and it seems I no longer have this issue. You can close it. Thanks!!
