### ISSUE TITLE
Add feature: Calendar View

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#809]
_From @xet7 on January 10, 2017 17:8_

Wish originally from @TutloTutlo

It's this Trello feature:
http://help.trello.com/article/811-viewing-cards-in-a-calendar-view
http://blog.trello.com/enable-trello-calendar-mode

There's also possibility use Trello with Google Calendar:
http://help.trello.com/article/829-using-trello-with-google-calendar

In Sandstorm Wekan could work with some Sandstorm calendar app instead.

_Copied from original issue: wefork/wekan#62_

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#808

**Comment by NoodleBB** [comment]
+1
