### ISSUE TITLE
Add feature: Removing members from board

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#816]
_From @abliss on January 19, 2017 15:6_

Over time, a board's memebrs area can get crowded with old members who have moved on to other teams. I can't find any way to remove them.

_Copied from original issue: wefork/wekan#80_

**Comment by nztqa** [comment]
Implemented.

![image](https://user-images.githubusercontent.com/22808079/27724982-483f7bd4-5daf-11e7-9577-15cd09204092.png)
