### ISSUE TITLE
Current manual install instructions for running produce error

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#818]
_From @kdamianakis on January 25, 2017 9:50_

manual installation Instructions on
[https://github.com/wefork/wekan/wiki/Install-from-source]
produce the following error at the last step - new to meteor/node so any advice:

meteor-dev-bundle@0.0.0 /root/repos/wekan/.build/bundle/programs/server
├── amdefine@1.0.0 
├── ansi-regex@0.2.1 
├── ansi-styles@1.1.0 
├── asap@2.0.4 
├── chalk@0.5.1 
├── eachline@2.3.3 
├── escape-string-regexp@1.0.5 
├── has-ansi@0.1.0 
├── meteor-promise@0.7.2 
├── promise@7.1.1 
├── semver@4.1.0 
├── source-map@0.1.32 
├── source-map-support@0.3.2 
├── strip-ansi@0.3.0 
├── supports-color@0.2.0 
├── type-of@2.0.1 
└── underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/repos/wekan/.build/bundle/programs/server/npm-debug.log

_Copied from original issue: wefork/wekan#88_

**Comment by xet7** [comment]
@kdamianakis 

It's very likely that because of rapidly changing node.js packages those install from source instructions need fixing again. If you are in a hurry and just trying Wefork, use VirtualBox appliance at https://wekan.xet7.org

**Comment by xet7** [comment]
_From @kdamianakis on January 25, 2017 10:48_

Thank you for this - not in a hurry but would be useful to see if others have also a similar problem. I believe Wekan to be a very useful open source self hosted app.

**Comment by xet7** [comment]
@kdamianakis 

Yes it has happened before to others that they had problems installing from source, although I for me install went fine when I created VirtualBox appliance. I have fixed those instructions multiple times before. There are also other bugfixes in progress.

**Comment by 2Belette** [comment]
Hi I am trying to install it as well from source and same error today...
```
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.9.8-gnu-1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/belette/softwares/wekan/.build/bundle/programs/server/npm-debug.log
```

**Comment by xet7** [comment]
@2Belette 

You have too new version of node. Please try these instructions:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source
