### ISSUE TITLE
Add to wiki: Creating Sandstorm .spk from Wekan source

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#823]
Add to wiki, how to create wekan.spk from source, so it can be installed to Sandstorm instance and tested there.

I have not looked are there instructions somewhere already, so if there is, this can be closed with link to existing documentation.

_From @ocdtrekkie_

This should be relatively trivial to document. You pretty much just run `spk pack` in the source folder. (Though it might be `meteor-spk pack` actually, which would need to be installed, as well as Sandstorm itself.)

The important part is that a third party trying to build it will not have the required key to publish an app with the Wekan app ID. They would need to change it, which is a process documented here: https://docs.sandstorm.io/en/latest/developing/publishing-apps/#double-check-your-app-id

And they could not upgrade grains from official Wekan to a Wekan version they built themselves.

_From @dwrensha_

@ocdtrekkie Unfortunately it's not quite so simple.

Due to https://github.com/sandstorm-io/meteor-spk/issues/25, a locally-modified version of meteor-spk v0.2.1 needs to be used (updated schemas need to be dropped in at `meteor-spk.deps/node_modules/sandstorm/`).

Due to the issue described [here](https://github.com/sandstorm-io/meteor-accounts-sandstorm/pull/31), I've been maintaining an [upstream patch](https://github.com/dwrensha/wekan/commit/f2fe28aed74b265b66a86a031a9c8b7bf6bcc41e) in Wekan that I apply before releasing.

**Comment by xet7** [comment]
Moved to here from #790

From @ocdtrekkie 

> I think @dwrensha pretty much detailed everything in #823 but it may just be best for him to PR that being disabled when he packages the new version. It sounds like a lot of this will be simpler after Wekan moves to a newer Meteor version.

Ok thanks! I'll try building .spk using these instructions.

**Comment by ocdtrekkie** [comment]
This issue can probably be closed now.

**Comment by xet7** [comment]
https://github.com/wekan/wekan-maintainer/wiki/Building-Wekan-for-Sandstorm
