### ISSUE TITLE
Add Feature: List View of All Tasks

### ISSUE THREAD

**Issue by phillc73** [wekan/wekan#826]
I think it would be useful to have an ordered list view of all tasks, across all boards.

Currently, there is so single page (that I am aware of) which shows all tasks across all boards, which can be ordered by due date.

A simple use case is to login each morning and view a list of tasks due that day, across all boards.

Related to #808. Although this List View request does not specifically require calendar integration, in effect they'd achieve something very similar.

**Comment by xet7** [comment]
You can use REST API:
https://github.com/wekan/wekan/issues/1037

For layouts, see https://github.com/wekan/wekan/issues/781
