### ISSUE TITLE
Add Feature: In checklists, display and focus a new item input when validating one

### ISSUE THREAD

**Issue by GuillaumeAmat** [wekan/wekan#828]
Having checklists in cards is awesome but it lacks of a fluid input flow. Currently you have to manually click the *add item* link to display a new item input.

It would be better to display and focus a new input right after validating an item.

**Comment by GuillaumeAmat** [comment]
I was about to create a new issue for drag'n drop of checklists items and I found that issue: #597 

It contains both issues... Should I close mine? Or split the #597 in several issues?

cc @xet7 @jLouzado

**Comment by jLouzado** [comment]
wow, #597 has veered off into discussions about community governance xD

Maybe split the remaining bugs into separate issues and link them all in a comment? Then @xet7 can just close #597 and development can continue on the cleaner issues.

**Comment by xet7** [comment]
@GuillaumeAmat @jLouzado 

I will cleanup issues myself. Just let it be as it is now.

**Comment by GuillaumeAmat** [comment]
@xet7 Great thanks!
