### ISSUE TITLE
Creating Checklist does not work

### ISSUE THREAD

**Issue by port22** [wekan/wekan#829]
I'm running wekan via docker:

```
docker run -d --restart=always --name wekan-db -v $PWD/mongo:/data/db:Z mongo:3.2.11
docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://wekan.local" -p 80:80 mquandalle/wekan:latest
```

When I try to create a checklist in any board-card, it just happens literally nothing. I don't get any error message with "docker logs" on the wekan or wekan-db container.

Any ideas for debugging ?

**Comment by GuillaumeAmat** [comment]
I'm not a Wekan contributor, as I don't know the code yet, but perhaps it's a javascript bug?
Can you open your devtools console before trying to create a checklist and see if an error pops up?

**Comment by port22** [comment]
chrome console log: ` insert failed: Access denied`
http://wekan.local/ca55c557cb8213872b310ef2faf661bdefe7df7c.js?meteor_js_resource=true:3

`!function(){var t=Package.underscore._,e,n,r;(function(){e=this}).call(this),function(){n=__meteor_runtime_config__.meteorEnv,r={isProduction:"production"===n.NODE_ENV,isDevelopment:"production"!==n.NODE_ENV,isClient:!0,isServer:!1,isCordova:!1},"object"==typeof __meteor_runtime_config__&&__meteor_runtime_config__.PUBLIC_SETTINGS&&(r.settings={"public":__meteor_runtime_config__.PUBLIC_SETTINGS})}.call(this),function(){function e(t){return t?r._debug("Exception in callback of async function",t.stack?t.stack:t):void 0}if(r.isServer)var n=Npm.require("fibers/future");"object"==typeof __meteor_runtime_config__&&__meteor_runtime_config__.meteorRelease&&(r.release=__meteor_runtime_config__.meteorRelease),t.extend(r,{_get:function(t){for(var e=1;e<arguments.length;e++){if(!(arguments[e]in t))return void 0;t=t[arguments[e]]}return t},_ensure:function(t){for(var e=1;e<arguments.length;e++){var n=arguments[e];n in t||(t[n]={}),t=t[n]}return t},_delete:function(t){for(var e=[t],n=!0,r=1;r<arguments.length-1;r++){var o=arguments[r];if(!(o in t)){n=!1;break}if(t=t[o],"object"!=typeof t)break;e.push(t)}for(var r=e.length-1;r>=0;r--){var o=arguments[r+1];if(n)n=!1;else for(var i in e[r][o])return;delete e[r][o]}},wrapAsync:function(o,i){return function(){for(var a=i||this,s=t.toArray(arguments),u,c=s.length-1;c>=0;--c){var l=s[c],f=typeof l;if("undefined"!==f){"function"===f&&(u=l);break}}if(!u){if(r.isClient)u=e;else{var p=new n;u=p.resolver()}++c}s[c]=r.bindEnvironment(u);var _=o.apply(a,s);return p?p.wait():_}},_inherits:function(e,n){for(var r in n)t.has(n,r)&&(e[r]=n[r]);var o=function(){this.constructor=e};return o.prototype=n.prototype,e.prototype=new o,e.__super__=n.prototype,e}});var o=!1;r._wrapAsync=function(t,e){return o||(r._debug("Meteor._wrapAsync has been renamed to Meteor.wrapAsync"),o=!0),r.wrapAsync.apply(r,arguments)}}.call(this),function(){"use strict";function t(){if(o.setImmediate){var t=function(t){o.setImmediate(t)};return t.implementation="setImmediate",t}return null}function e(){function t(t,e){return"string"==typeof t&&t.substring(0,e.length)===e}function e(e){if(e.source===o&&t(e.data,s)){var n=e.data.substring(s.length);try{a[n]&&a[n]()}finally{delete a[n]}}}if(!o.postMessage||o.importScripts)return null;var n=!0,r=o.onmessage;if(o.onmessage=function(){n=!1},o.postMessage("","*"),o.onmessage=r,!n)return null;var i=0,a={},s="Meteor._setImmediate."+Math.random()+".";o.addEventListener?o.addEventListener("message",e,!1):o.attachEvent("onmessage",e);var u=function(t){++i,a[i]=t,o.postMessage(s+i,"*")};return u.implementation="postMessage",u}function n(){var t=function(t){o.setTimeout(t,0)};return t.implementation="setTimeout",t}var o=this;r._setImmediate=t()||e()||n()}.call(this),function(){var e=function(t){if(Package.ddp){var e=Package.ddp.DDP._CurrentInvocation;if(e.get()&&e.get().isSimulation)throw new Error("Can't set timers inside simulations");return function(){e.withValue(null,t)}}return t},n=function(t,n){return r.bindEnvironment(e(n),t)};t.extend(r,{setTimeout:function(t,e){return setTimeout(n("setTimeout callback",t),e)},setInterval:function(t,e){return setInterval(n("setInterval callback",t),e)},clearInterval:function(t){return clearInterval(t)},clearTimeout:function(t){return clearTimeout(t)},defer:function(t){r._setImmediate(n("defer callback",t))}})}.call(this),function(){r.makeErrorType=function(t,e){var n=function(){Error.captureStackTrace?Error.captureStackTrace(this,n):this.stack=(new Error).stack,e.apply(this,arguments),this.errorType=t};return r._inherits(n,Error),n},r.Error=r.makeErrorType("Meteor.Error",function(t,e,n){var r=this;r.error=t,r.reason=e,r.details=n,r.reason?r.message=r.reason+" ["+r.error+"]":r.message="["+r.error+"]"}),r.Error.prototype.clone=function(){var t=this;return new r.Error(t.error,t.reason,t.details)}}.call(this),function(){r._noYieldsAllowed=function(t){return t()},r._SynchronousQueue=function(){var t=this;t._tasks=[],t._running=!1,t._runTimeout=null},t.extend(r._SynchronousQueue.prototype,{runTask:function(e){var n=this;if(!n.safeToRunTask())throw new Error("Could not synchronously run a task from a running task");n._tasks.push(e);var o=n._tasks;n._tasks=[],n._running=!0,n._runTimeout&&(clearTimeout(n._runTimeout),n._runTimeout=null);try{for(;!t.isEmpty(o);){var i=o.shift();try{i()}catch(a){if(t.isEmpty(o))throw a;r._debug("Exception in queued task: "+(a.stack||a))}}}finally{n._running=!1}},queueTask:function(e){var n=this;n._tasks.push(e),n._runTimeout||(n._runTimeout=setTimeout(t.bind(n.flush,n),0))},flush:function(){var t=this;t.runTask(function(){})},drain:function(){var e=this;if(e.safeToRunTask())for(;!t.isEmpty(e._tasks);)e.flush()},safeToRunTask:function(){var t=this;return!t._running}})}.call(this),function(){var t=[],e=!1,n=!1,o=0,i=function(){o++},a=function(){o--,s()},s=function(){if(!(n||!e||o>0)){for(n=!0;t.length;)t.shift()();r.isCordova&&WebAppLocalServer.startupDidComplete()}},u=function(){e||(e=!0,s())};r.isCordova&&(i(),document.addEventListener("deviceready",a,!1)),"complete"===document.readyState||"loaded"===document.readyState?window.setTimeout(u):document.addEventListener?(document.addEventListener("DOMContentLoaded",u,!1),window.addEventListener("load",u,!1)):(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&u()}),window.attachEvent("load",u)),r.startup=function(e){var o=!document.addEventListener&&document.documentElement.doScroll;if(o&&window===top){try{o("left")}catch(i){return void setTimeout(function(){r.startup(e)},50)}e()}else n?e():t.push(e)}}.call(this),function(){var t=0;r._debug=function(){if(t)return void t--;if("undefined"!=typeof console&&"undefined"!=typeof console.log)if(0==arguments.length)console.log("");else if("function"==typeof console.log.apply){for(var e=!0,n=0;n<arguments.length;n++)"string"!=typeof arguments[n]&&(e=!1);e?console.log.apply(console,[Array.prototype.join.call(arguments," ")]):console.log.apply(console,arguments)}else if("function"==typeof Function.prototype.bind){var r=Function.prototype.bind.call(console.log,console);r.apply(console,arguments)}else Function.prototype.call.call(console.log,console,Array.prototype.slice.call(arguments))},r._suppress_log=function(e){t+=e},r._suppressed_log_expected=function(){return 0!==t}}.call(this),function(){r._escapeRegExp=function(t){return String(t).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}}.call(this),function(){var t;t=r.isClient?n.TEST_METADATA:process.env.TEST_METADATA;var e=JSON.parse(t||"{}"),o=e.driverPackage;r.isTest=!!e.isTest,r.isAppTest=!!e.isAppTest,r.isPackageTest=!!o&&!r.isTest&&!r.isAppTest,"string"==typeof o&&r.startup(function(){var t=Package[o];if(!t)throw new Error("Can't find test driver package: "+o);if(r.isClient){if("function"!=typeof t.runTests)throw new Error("Test driver package "+o+" missing `runTests` export");t.runTests()}else"function"==typeof t.start&&t.start()})}.call(this),function(){var e=0,n=[];r.EnvironmentVariable=function(){this.slot=e++},t.extend(r.EnvironmentVariable.prototype,{get:function(){return n[this.slot]},getOrNullIfOutsideFiber:function(){return this.get()},withValue:function(t,e){var r=n[this.slot];try{n[this.slot]=t;var o=e()}finally{n[this.slot]=r}return o}}),r.bindEnvironment=function(e,o,i){var a=t.clone(n);if(!o||"string"==typeof o){var s=o||"callback of async function";o=function(t){r._debug("Exception in "+s+":",t&&t.stack||t)}}return function(){var r=n;try{n=a;var s=e.apply(i,t.toArray(arguments))}catch(u){o(u)}finally{n=r}return s}},r._nodeCodeMustBeInFiber=function(){}}.call(this),function(){r.absoluteUrl=function(e,n){n||"object"!=typeof e||(n=e,e=void 0),n=t.extend({},r.absoluteUrl.defaultOptions,n||{});var o=n.rootUrl;if(!o)throw new Error("Must pass options.rootUrl or set ROOT_URL in the server environment");return/^http[s]?:\/\//i.test(o)||(o="http://"+o),/\/$/.test(o)||(o+="/"),e&&(o+=e),n.secure&&/^http:/.test(o)&&!/http:\/\/localhost[:\/]/.test(o)&&!/http:\/\/127\.0\.0\.1[:\/]/.test(o)&&(o=o.replace(/^http:/,"https:")),n.replaceLocalhost&&(o=o.replace(/^http:\/\/localhost([:\/].*)/,"http://127.0.0.1$1")),o},r.absoluteUrl.defaultOptions={},"object"==typeof __meteor_runtime_config__&&__meteor_runtime_config__.ROOT_URL&&(r.absoluteUrl.defaultOptions.rootUrl=__meteor_runtime_config__.ROOT_URL),r._relativeToSiteRootUrl=function(t){return"object"==typeof __meteor_runtime_config__&&"/"===t.substr(0,1)&&(t=(__meteor_runtime_config__.ROOT_URL_PATH_PREFIX||"")+t),t}}.call(this),"undefined"==typeof Package&&(Package={}),function(t,e){for(var n in e)n in t||(t[n]=e[n])}(Package.meteor={},{Meteor:r,global:e,meteorEnv:n})}();`

**Comment by GuillaumeAmat** [comment]
Ok so it's really a javascript bug ^^
Or maybe an auth one? Are you sure you're logged in? What happens if you reload the page?

Also, if you want to paste a big trace like yours, it's better to put triple ``` around it (not just one).

**Comment by port22** [comment]
what the ... that's embarassing ... I am consistently working on that board for the last of hours and no complaints. But you're right, I'm suddenly not logged in anymore. 
I'm going to hide my head in the sand. thanks and sorry ^^
