### ISSUE TITLE
Is the latest release/commit docker build working?

### ISSUE THREAD

**Issue by weaktyper** [wekan/wekan#832]
Is the latest docker image working for someone?
I'm doing an upgrade and having issues.

**Comment by xet7** [comment]
@weaktyper 

If you originally installed using commands alone like this:

```
docker run -d --restart=always --name wekan-db mongo:3.2.11

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost:8080" -p 8080:80 mquandalle/wekan:latest
```

If you have newer mongo version, you need backup your MongoDB data:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
and use similar commands as below to replace you mongo container with version 3.2.11, and then restore data.

Then you can upgrade just only the Wekan container this way:

Show docker containers:
```
docker ps
```

Stop mquandalle/wekan container:
```
docker stop CONTAINER-ID-HERE
```

Remove mquandalle/wekan container:
```
docker rm CONTAINER-ID-HERE
```

Remove mquandalle/wekan image:
```
docker rmi mquandalle/wekan:latest
```

Run latest version:
```
docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost:8080" -p 8080:80 mquandalle/wekan:latest
```

@jLouzado Can you update this documentation to wiki?

@weaktyper Can you update docker compose documentation to wiki if something needs to be changed for this?

**Comment by weaktyper** [comment]
@xet7 
Ok, actually, there is nothing wrong with the build. I have a separate production `docker-compose.yml` of my own and I had the wrong port specified on it. 
Closing this issues so. Thanks.

**Comment by weaktyper** [comment]
I can also confirm that the export process works. That said, I was forced to add the db name to the `mongorestore` command.

```
mongorestore --drop
```
returned an error like this	`don't know what to do with file`

```
mongorestore --drop --db=wekandb
```
did work.

**Comment by jLouzado** [comment]
@xet7 done, please [check](https://github.com/wekan/wekan/wiki/Install-and-Update#updating-docker).

@weaktyper Is the change in step 9a) what you wanted changed? [link](https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Dat)

**Comment by xet7** [comment]
Thanks @jLouzado ! I made some updates to that wiki page.
