### ISSUE TITLE
Add Feature: Delete Wekan board

### ISSUE THREAD

**Issue by HLFH** [wekan/wekan#833]
Hi,

We should be able to delete Wekan board.
Archive feature is not enough.

Thanks,

**Comment by HLFH** [comment]
Offtopic: can you add the milestone v0.12 @xet7 to Wekan and link https://github.com/wekan/wekan/issues/785 and https://github.com/wekan/wekan/issues/784? Thanks!

**Comment by fmonthel** [comment]
Hi,

I developed below script to clean database (so here will delete board archived fore more than 1 month) : https://github.com/fmonthel/wekan-cleanup

**Comment by xet7** [comment]
@fmonthel 

Does your script delete archived card attachments?

**Comment by fmonthel** [comment]
Arf not, but I will add (as checklist)

**Comment by xet7** [comment]
@fmonthel 

Thanks! I added link to your cleanup script to readme and changelog.

**Comment by fmonthel** [comment]
wekan-cleanup fix to delete (at least into cfs.attachments.filerecord) upload data. Not sure how to proceed with other cfs.* collection , I need to look deeper
wekan-cleanup fix as well to delete checklists

Script is deleting as well board(s) with no cards into and created more than x days ago

**Comment by xet7** [comment]
Issues related to Wekan cleanup Python script can be continued at:
https://github.com/wekan/wekan-cleanup

This issue is about deleting board in Wekan.

**Comment by genecraig** [comment]
2 years and we cannot delete boards? ABSURD!

**Comment by ocdtrekkie** [comment]
@genecraig This is an open source project. Nobody makes any money to work on it. The fact that you have the ability to create Wekan boards for free is something you should be appreciative of. If you'd like to contribute, do so. If you'd like to offer up money on here for someone to write a feature you want, someone might be interested in taking you up on that even.

But coming in to comment on the "absurdity" that a feature you want isn't in a program that you didn't pay for or contribute to in any way is, in fact, absurd. :)

**Comment by genecraig** [comment]
@ocdtrekkie definition of trolling is to follow someone around online commenting on their comments. This is what you have just done from one thread to another. STOP!

And this is NOT a charity. You are using the public for free QA. We are doing part of your work for your projects and your compensation is allowing us to use the product in its half-baked state. If you don't want criticism then why did you put your projects on GitHub? It is NOT charity. You are so ungrateful for the work the public does on YOUR intellectual property without any payment.

**Comment by ocdtrekkie** [comment]
I actually get notifications of all Wekan issues and comments in my email, and sometimes I respond. I am not following your juvenile rear anywhere, though I find it at least mildly entertaining to read to kind of nonsense you're typing.

*This is not a business. Nobody's talking about who's what intellectual property. This is a free, open source thing for your use if you want it. If you don't want it, don't use it. The people who bother to support or work on this project are people who use it, and benefit from improvements to it, and that's the only reason they're here.*

**Comment by xet7** [comment]
If somebody wants this feature, add more to this bounty:
https://www.bountysource.com/issues/41924320-add-feature-delete-wekan-board
Instructions:
http://www.xet7.org/wekan

**Comment by feuerball11** [comment]
I'm looking into this the days.

**Comment by feuerball11** [comment]
Timelines moved, and i have no time to do this. Sry. I want to concentrate on Custom Fields and Advanced Filters

**Comment by xet7** [comment]
@rjevnikar 

I don't know why delete board from recycle bin does not work anymore.

**Comment by d3dbit** [comment]
Hello all,
I cannot delete boards from recycle bin. The delete boards button appears but it does not do anything.

The same issue as: #1731 Cannot delete board from recycle bin

**Comment by d3dbit** [comment]
v1.11 and v1.18 --> I cannot delete boards from recycle bin

**Comment by loginKing** [comment]
same issue
![image](https://user-images.githubusercontent.com/38350723/42548122-26b1ebca-84f8-11e8-8396-51f729971273.png)

**Comment by Skrylar** [comment]
@d3dbit Doesn't work in v1.10 either. Is there a version where this feature has ever worked? I'd be willing to do the git-bisect.

**Comment by rjevnikar** [comment]
I have board deletion working, but there is no confirming popup before hand.
@xet7 I can push it as a PR, but I don't think it is the best idea. What are your thoughts?

**Comment by xet7** [comment]
@rjevnikar 

You can add PR. I will look how to add confirming popup, or alternatively warning text that there is no confirming popup.

**Comment by duwei54** [comment]
I had the same problem,version 1.20

**Comment by rjevnikar** [comment]
added #1866 as a quick fix

**Comment by xet7** [comment]
I fixed Delete Board at 534b20fedac9162d2d316bd74eff743d636f2b3d and it has working confirmation popup at Wekan v1.38 https://github.com/wekan/wekan/blob/devel/CHANGELOG.md . Please wait for newest Wekan version to build and be available.
