### ISSUE TITLE
Enhancement: International Date Formatting

### ISSUE THREAD

**Issue by phillc73** [wekan/wekan#838]
The Due and Start Date on card is currently in mm/dd/yyyy format. This is not always internationally appropriate.

Either allow dates to be formatted in different styles, e.g. dd/mm/yyyy or set the date display by default to the internationally recognised [ISO date format](https://www.w3.org/QA/Tips/iso-date), yyyy-mm-dd

![wekanscreen](https://cloud.githubusercontent.com/assets/815126/22930417/606a0bde-f2c0-11e6-9b27-2a11f1a9c549.png)

**Comment by sonntagd** [comment]
I am using the current release candidate v0.11.1-rc1 and I see it like 15.2.2017 as it is typical in Germany.

Are you sure, this does not depend on the client? Or maybe a language setting?

**Comment by phillc73** [comment]
@sonntagd Interesting. The screenshot above was taken from the Wekan version currently running on Sandstorm.io and the language is set to English (I don't think there's an option for UK/US/Australian English variants.

I've also just installed Wekan on cloudron.io, where yesterday they updated to v0.11.1-rc1, again with English langauge and the date is still in mm/dd/yyyy format. If I change the language setting within Wekan to Deutsch, I do see dates in dd.m.yyyy format as you do.

Therefore, I do think defaulting to the ISO data format of yyyy-mm-dd would be a good idea.

**Comment by ArcturusB** [comment]
Hi all, 

I also get the mm/dd/yyyy format running v0.11.1-rc1 in Docker. Of course it changes when I switch to a different language, but not everyone using the the app in English are comfortable with the US date format.

It would be nice to use the ISO yyyy-mm-dd format when formatting dates in English. 

Maybe an en-US format could be added to the language list for users who want to use the mm/dd/yyyy format.

**Comment by johnleeming** [comment]
I have the same issue

**Comment by NoodleBB** [comment]
@sonntagd 
I always see the american formatting, regardless which client i use.

**Comment by NoodleBB** [comment]
+1 👍

**Comment by lumatijev** [comment]
We are testing release v0.23 and datetime format is not changing even if I switch to another language.

It would be great if admin could setup custom datetime format that will be used by, lets say, `momentjs`. For example Croatian layout would be "DD.MM.YYYY. HH:mm" and we would still be able to use English translations.

**Comment by johnleeming** [comment]
I think this can be sorted by creating a new language EN_GB.  I have requested it in transifex.  If the project owners can approve it then I can do the necessary "translation" quickly

**Comment by xet7** [comment]
@johnleeming 

I have merged EN_GB, you can test it for example at Docker:
https://github.com/wekan/wekan/wiki/Platforms#docker

Does it work for you now?

**Comment by xet7** [comment]
This seems to work for me, so en-GB is DD/MM/YYYY and en-US is MM/DD/YYYY.

Date format is language and country specific. Request new language in transifex if some is missing.

**Comment by johnleeming** [comment]
Works for me too.  Page Refresh necessary to change dates formats after you chaneg languages

**Comment by saschafoerster** [comment]
We just had a problem, where I created a board and my profile was german, while my colleagues language was set on English: when she tried to add a date it didn't work. When she switched to german, everything worked fine.

**Comment by xet7** [comment]
@saschafoerster 

I tried, and these did work for me in different English time formats. 

English
Date: 10/23/2017
Time: 2:00 PM

English (UK)
Date: 23/10/2017
Time: 14:00

Did you get any error messages? Or how it did not work?

**Comment by saschafoerster** [comment]
I tried to recreate but I can't: it was a new account from my colleague, which she started in english. The board and my profile where german. She tried to add dates and got error messages (I remember: date format not correct). As soon she switched language once to german, everything worked fine.

**Comment by BjoernLudwigPTB** [comment]
@xet7 

Thanks for the great work here and with the project in general. We love the application and start to use it extensively in different local and international contexts. The [ISO date format](https://www.w3.org/QA/Tips/iso-date) YYYY-MM-DD would be most appropriate in many cases for us. I am not sure what would be the best way to express the need for that. Please give me some advice on how to request that.

**Comment by xet7** [comment]
@BjoernLudwigPTB 

This issue is continued at #1176

**Comment by mdykierek** [comment]
Hit that when coming back to Wekan after some while :(
