### ISSUE TITLE
Enhancement: Allow Only Unique List Names

### ISSUE THREAD

**Issue by phillc73** [wekan/wekan#839]
Wekan currently allows List names to be exactly the same as each other, within the same board.

I'd like to propose that Wekan only allows unique list names within a board. See attached screen grab of "Still More Stuff"

![wekanscreen](https://cloud.githubusercontent.com/assets/815126/22930479/bfca6bdc-f2c0-11e6-9f53-b2a49414cf38.png)

**Comment by xet7** [comment]
@phillc73 

No. I sometimes move same named lists from different boards to same boards, to combine those lists.

**Comment by phillc73** [comment]
I think that's a different use case and Wekan should ask if you wish to merge/combine the lists. If answered in the negative, then the lists are differentiated by number. e.g. To Do and To Do 2

**Comment by xet7** [comment]
Oh, yes that's true.

Reopening issue.

**Comment by xet7** [comment]
Moved to #3022
