### ISSUE TITLE
[How To] Migrate from old setup to new on Fedora 22

### ISSUE THREAD

**Issue by kirantpatil** [wekan/wekan#841]
Hi,

I am using old setup on Fedora 22 which is the before Wefork merge.

I would like to know how to upgrade it to work seamlessly with current working setup.

Setup details:
-----------------

$ meteor --version
Meteor 1.3.5.1                                

$ mongod --version
db version v2.6.11
2017-02-15T12:58:38.667+0530 git version: nogitversion
2017-02-15T12:58:38.667+0530 OpenSSL version: OpenSSL 1.0.1k-fips 8 Jan 2015

$ node --version
v0.10.42

Thanks.

**Comment by xet7** [comment]
@kirantpatil 

You can download newest precompiled binary release .tar.gz file:
https://github.com/wekan/wekan/releases

Then in that unarchived directory run command:
```
meteor
```
Or any other way that you used to start Wekan previously.

Does this work for you?

**Comment by xet7** [comment]
Create new issue if you have any problems.
