### ISSUE TITLE
`new item to checklist` form should be in focus after creating a checklist item

### ISSUE THREAD

**Issue by jLouzado** [wekan/wekan#842]
Right now if you have to create two checklist items, you have to click on `Add an item to checklist` again after creating the first item.

This is not a very big deal but it breaks continuity: You have to take your fingers off the keyboard to activate the `add item` form.

Compare this to the behavior of the `Add a card` form - there you can keep typing and hitting `Return` to create a new item, and you press `Esc` to exit focus.

**Comment by GuillaumeAmat** [comment]
It's a duplicate of #828 ;)

**Comment by jLouzado** [comment]
Oops, thank you @GuillaumeAmat 

Closed since it's a duplicate. :)
