### ISSUE TITLE
[ENH] Change email address 

### ISSUE THREAD

**Issue by fmonthel** [wekan/wekan#848]
Hi

It's seem that we can't change email address on your account, should be as very basic feature
Nevertheless we need to verify it at the end
Thanks

**Comment by NoodleBB** [comment]
This was exactly the first question i got from the people i invited.

**Comment by NoodleBB** [comment]
Temporary Workaround:
```
db.users.update( { username: "the_username" },
  { $set: 
    { 
    "emails.0.address": "new@mail.com", 
    "services.email.verificationTokens.0.address": "new@mail.com" 
    } 
  } 
)
```
