### ISSUE TITLE
Remove mail notification for "self" changes

### ISSUE THREAD

**Issue by elvince** [wekan/wekan#849]
Hi,

The email notification is really great. 
Is there a way to not have notification of our changes? I mean, as a user I don't need to receive a notification that **I** made change on a "card".

I didn't find the option in the menu so it might be a feature request. 

Thanks for the tool!

**Comment by xet7** [comment]
What notifications? I did not test is such feauture in Wekan yet. How does it work for you?
Please continue discussion at  https://github.com/wekan/wekan/issues/794

This is duplicate issue, so I'm now closing this issue.
