### ISSUE TITLE
Ubuntu Core for Docker

### ISSUE THREAD

**Issue by iAdanos** [wekan/wekan#851]
What do you think about using [https://www.ubuntu.com/core](Ubuntu Core) as a base for Docker Container?

Maybe it could make container smaller and faster.

**Comment by rubberduck203** [comment]
I would consider Alpine as an alternative. Ubuntu Core doesn't seem to have an official image (yet?). If you're really looking to minimize the container's disk footprint, Alpine weighs in at 5MB. 

https://www.google.com/amp/s/www.brianchristner.io/docker-image-base-os-size-comparison/amp/

**Comment by xet7** [comment]
@rubberduck203 

Alpine is not stable enough for Meteor or Docker.

**Comment by Barthalion** [comment]
@xet7 I'd like to hear what issues you had with Alpine. Although I'm not involved directly in the project anymore, I'm more than happy to get back to it if it could result in using Alpine for Docker image.

**Comment by stephenmoloney** [comment]
@rubberduck203 , @Barthalion  see `wekan-launchpad`. The issue I had was getting the size of the meteor bundle down.

**Comment by xet7** [comment]
I think it's enought that there already is [Ubuntu snap](https://github.com/wekan/wekan/wiki/Platforms#ubuntu-snap)
