### ISSUE TITLE
Wekan and logstash

### ISSUE THREAD

**Issue by fmonthel** [wekan/wekan#855]
Hi,

Here wrapper to get cards into logstash filter in order to build some Kibana report and graphes
https://github.com/fmonthel/wekan-logstash

Goal is to export data into Json format that we can be used as input for log stash and ElastisSearch / Kibana
Import in logstash should be done daily basic (as we have field daily event)

**Comment by xet7** [comment]
Thanks!

Please add your description of that repo in your comment above to your repo's description.

I will add link to your repo to readme and changelog.

**Comment by xet7** [comment]
@fmonthel 

Before I add link etc, can you rename your repo to wekan-logstash, as it has a typo?

**Comment by fmonthel** [comment]
@xe7 : done :)

**Comment by xet7** [comment]
@fmonthel

Your WekanStats looks nice also, do you have plans to add features that are requested in it's issues?
https://github.com/fmonthel/WekanStats

**Comment by xet7** [comment]
@fmonthel 

I did mean that on wekan-logstash repo, add description to above view of files, there is still text "No description, website, or topics provided."

**Comment by xet7** [comment]
@fmonthel 

Do you want to keep those Wekan related repos under your own account, or can they be moved under Wekan GitHub Organization, and give you access there?

**Comment by xet7** [comment]
@fmonthel 

That way I and other Wekan GitHub organization members could update those repos directly.

**Comment by xet7** [comment]
@fmonthel 

I have now added info about logstash code etc to readme and changelog.

**Comment by fmonthel** [comment]
@xet7 : yes sure no pb to move them to Wekan org. I will check how to do that but not today

**Comment by fmonthel** [comment]
@xet7 : to transfer to wekan orgs, It's seem that I need to have the relevant right to create repo into orga

**Comment by xet7** [comment]
@fmonthel 

I moved those repos to Wekan GitHub Organization myself, and invited you to there with write access.
Issues related to those can be handled in those repos issues. Thanks!

Closing issue.

**Comment by fmonthel** [comment]
Ok perfect
Thanks
