### ISSUE TITLE
Add feature: Admin setting, turn on filter: Users see only their own cards on board

### ISSUE THREAD

**Issue by poweroffsntndr** [wekan/wekan#863]
Hello, I was checking the code and I will like to know if there is a way to display:

- If I am the admin of the board
     - show all users cards
- If I am a normal user on any board
     - show only the cards in which I am member

Example:

Admin view (OK);
![image](https://cloud.githubusercontent.com/assets/25924159/23159176/1250be18-f822-11e6-85ac-d43300710256.png)

Admin is able to show all cards of the board

Wanted User view by default:
![image](https://cloud.githubusercontent.com/assets/25924159/23159231/4c218118-f822-11e6-9eeb-472355a9d669.png)

This is the same as filter on my own user but i dont want that normal users can change this.

Thanks for your time,

Alberto.

**Comment by xet7** [comment]
Addition from chat:

> poweroffsntndr:
> I think the key is in sidebarFilters.js
```
return [{
'click .js-toggle-label-filter'(evt) {
evt.preventDefault();
Filter.labelIds.toggle(this.currentData()._id);
Filter.resetExceptions();
},
```

**Comment by xet7** [comment]
Moved to #3022
