### ISSUE TITLE
Add feature: Third user permissions level with comment only privileges 

### ISSUE THREAD

**Issue by rhelsing** [wekan/wekan#870]
I would like to add another user level with commenting only privileges but I don't know all the relevant places to modify. Any pointers for starters? Even if you don't want to add this into the main repo, I would like to create a fork and use it within my organization. Thanks!

**Comment by xet7** [comment]
It would be very useful for Wekan, no need to fork.

Look at https://github.com/wekan/wekan/pull/618 , it's not integrated yet because of merge conflicts.

**Comment by rhelsing** [comment]
@xet7 would you mind giving me (or directing me to someone who can give me) a quick high level run down of what I would need to modify to develop barebones version of this feature?

**Comment by xet7** [comment]
@rhelsing 

- Admin Panel is already integrated, look at changelog at git repo how to enable it. There is no actual user remove and permissions management yet.
- Check Admin Panel commit with Git history viewer, there is inviting users to boards.
- Add more options to Admin Panel for user management: listing users, removing users, adding permissions
- in MongoDB users collection, or if there is permissions collection, add column for permissions of user in same way there's creating other collections in MongoDB database, if those do not exist yet
- look at git history commits how read-only non-editable public view of board is made. From that you get idea how to disable editing.
- also for anything else, see comments with gitk on git history
- Wekan GitHub wiki has some info about compiling from source, etc
- if you get it working, submit pull request to devel branch
- ask here for questions if you get stuck

**Comment by rhelsing** [comment]
@xet7 Thanks so much, I will get started this weekend!

**Comment by rhelsing** [comment]
@xet7 I have my dev environment setup and was able to enable the admin panel without a problem. I believe my intention was to go in a slightly different direction then what you mention, although those features would be useful as well. There may be some overlap, or I may just be misunderstanding you. 

Here is what I envision:
A user currently has the ability to add other registered users to his/her board.
When those users are added, the board owner is currently able to click the users icon and change their permissions.
Currently, the only two options are 'Admin' and 'Normal'
**I would like to add a third option: 'Limited' or 'Comment Only'** that when set on a user that has been added to the board restricts them from doing anything except opening a card and commenting on it

I think this would be a minimally obtrusive feature add and would require less overhead than the implementation you originally suggested. If you agree, what would be the next logical steps for me to take? The vanila chat seems to have a redirection issue btw..

**Comment by xet7** [comment]
@rhelsing 

Yes, your plan sounds good :) 

Just search code for "Change Permissions" and there Admin and Normal, look how those are implemented, and add Comment only.

**Comment by rhelsing** [comment]
@xet7 I have done a very quick/rough implementation and it works tested manually.. I am sure there are better ways to do it, I am new to this codebase and meteor but thought the best way to learn was to get my hands dirty. If you would like to take a look at my current progress, you can see it here: https://github.com/rhelsing/wekan/pull/1/files

Before refactoring and making the implementation cleaner, I would like to hear some of your feedback if you have time.

**Comment by xet7** [comment]
@rhelsing 

Please submit that pull request to wekan devel branch, it's easier for me to test.

**Comment by xet7** [comment]
Comment only feature is already in Wekan.

**Comment by mzenzikhadija** [comment]
it only limit user to edit task what about subtasks??
