### ISSUE TITLE
Add Feature: Use Markdown in Checklists

### ISSUE THREAD

**Issue by cyphar** [wekan/wekan#877]
In trello, checklist entires render in markdown. In WeKan, only the description and comments are rendered in markdown. This is just a graphical nicety but it also means that things like links don't actually render as links when you put them in a checklist entry.

**Comment by GuillaumeAmat** [comment]
By *checkpoint* you meant *checklist* right? ;)

**Comment by lkisme** [comment]
That's reasonable, but I think a checklist item should be a small enough subtask that can be described with one simple sentence, to remind you there's something that need to be done, from this perspective, you wouldn't need  the markdown rendering in the checklist entry to show fancy effect like bold text or nice link.

**Comment by cyphar** [comment]
Sure, but not being able to use backticks in checklists makes it annoying. Also, it means that URLs aren't actually rendered as links -- which is an issue. Not to mention that Trello has this.

**Comment by xet7** [comment]
For Trello compatibility, it would be good to be able to import markdown from Trello and use it in Wekan.

**Comment by xet7** [comment]
Moved to #926
