### ISSUE TITLE
Add Feature: share cards between multiple dashboards or Agregate several dashboards in one

### ISSUE THREAD

**Issue by wouwou4444** [wekan/wekan#878]
Hi All,

1) I don't know if the feature exists but I need to manage several teams that work on the same topic.
I'd like to share on card from on dashboard to another dashboard I manage without the need to copy the content of the card. 
This way all the dashboards have the same level of visibility on the task in collaborative mode.

this card may be modified from either the origin board or from all boars when the card is shared (option maybe)

2) the counterpart of the first part is to be able to dispaly tasks from different boards in one global board as a manager of different teams working independently

regards,
Valery

**Comment by phillc73** [comment]
#808 #826 #864 all deal with aggregating tasks in some form or another.

**Comment by ChangePlaces** [comment]
this is done in phabricator with tags. e.g. putting a tag of one project into a task makes it show up in that project as well as the project it was created inside of

**Comment by xet7** [comment]
You can use REST API:
https://github.com/wekan/wekan/issues/1037
