### ISSUE TITLE
Using Docker for Wekan development

### ISSUE THREAD

**Issue by eemeli** [wekan/wekan#880]
This is a follow-on from discussion under #874.

I'd like to work on Wekan while running the node+meteor+wekan stack in a Docker environment, rather than running it directly on my host. At the moment, the Docker configs included in [this repo](../blob/devel/Dockerfile), in [wekan-launchpad](/wekan/wekan-launchpad), and in the [wiki](../wiki/Install-Wekan-Docker-for-testing) as well as elsewhere all focus on using Docker for production use. This means that they are optimised to minimise the resulting image size, rather than the reload time of the system during development, which can be rather long esp. due to re-fetching the meteor package dependencies on every build.

To support this use case, the Docker environment would need to be set up such that changes to the source code don't require a rebuild of the images, and with the source code editable on the host while still able to have changes to it trigger an update of `meteor run` in the container.

Is this something other people would also be interested in? It would help in resolving the rather specific version requirements, as well as otherwise setting up the environment in a controlled fashion to make it as easy as possible to start hacking on Wekan. Also, should this environment be included in Wekan core, or hosted in a separate repo?

**Comment by xet7** [comment]
@eemeli 

Thanks, this is very welcome!

I created this repo and invited you with direct commit access, please add your files etc there:
https://github.com/wekan/wekan-dev

**Comment by eemeli** [comment]
@xet7 An initial version has now been added to [the repo](/wekan/wekan-dev).

**Comment by xet7** [comment]
@eemeli 

Thanks! I added it to changelog, readme and wiki:
https://github.com/wekan/wekan/wiki/Developer-Documentation

**Comment by stephenmoloney** [comment]
`wekan-launchpad` could facilitate this too.

**Comment by eemeli** [comment]
@stephenmoloney The problem with using `wekan-launchpad` for this is that its `build` and `final` images need to be re-built for any code changes, the meteor package cache is wiped between re-builds, and there's no automatic tracking of changes to trigger a refresh. In total, that means a total turnaround time of multiple minutes for every code change, rather than the 10 seconds or so I'm seeing with `wekan-dev` atm.

On the other hand, I may also have misunderstood something with your setup. Is there a way to get its refresh time to be of that order as well?

**Comment by stephenmoloney** [comment]
@eemeli 
There was no way to avoid this because Alpine is a different distro and a rebuild of certain npm packages seemed to be necessary to make the build work. At least that's what I think. That might change in future. So wekan-dev might be faster alright for development purposes. 

Wekan-launchpad might be useful for alpine images all the same.

**Comment by stephenmoloney** [comment]
sorry for the delay in replying this issue just got away from me.
