### ISSUE TITLE
Running wekan as an standalone program on Windows

### ISSUE THREAD

**Issue by sinasalek** [wekan/wekan#883]
As you may know, there isn't any decent client program for kanaban, wekan is a very good candidate. On Linux docker can be used since it does not have much of a overhead and can be installed with few lines of commands. However on windows unfortunately it's quite difficult if not impossible. I opened up this issue the share my work and let anyone interested to join. So i'm trying to run wekan as an standalone windows program with no dependencies (all dependencies included). eventually it can be packaged as an windows installer msi file.

Here is the steps i've taken:
---
1. Created a wekan folder
2. Downloaded the latest version and extracted in bundle folder inside the wekan folder: wekan\bundle
3. Installed nodejs 0.10.48 from [here]( https://nodejs.org/en/download/releases/), copied the installed files to wekan\nodejs
4. Downloaded the [MongoDB portable](https://github.com/lightchpa/MongoDBPortable/releases) and extract it as wekan\MongoDBPortable
5. Created the following windows batch file:
```
SET MONGO_URL=mongodb://127.0.0.1:27017/wekan
SET ROOT_URL=http://127.0.0.1:8081/
SET MAIL_URL=smtp://user:pass@mailserver.example.com:25/
SET MAIL_FROM=wekan-admin@example.com
SET PORT=8081
MongoDBPortable\MongoDBPortable.exe
cd bundle
..\nodejs\node.exe main.js
pause
```
6. Wekan did not run even though i downloaded the binary release.
```
cd bundle\programs\server
..\..\..\nodejs\npm install
```
Error ([npm-debug.zip](https://github.com/wekan/wekan/files/813992/npm-debug.zip)) :
```
Missing win32-x64-v8-3.14\fibers.node
```
So right now i'm following the [new guide](https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows) suggested by @xet7 to overcome the problem.

**Comment by xet7** [comment]
@entrpharer

How did you get fibers compiled?

**Comment by sinasalek** [comment]
Referencing some related issues:
1. [error in node js when trying to install a module in windows](http://stackoverflow.com/questions/31772382/error-in-node-js-when-trying-to-install-a-module-in-windows)
2. [Cant install fibers on windows 10](https://github.com/laverdet/node-fibers/issues/250)
3. [Troubles with NPM and node-gyp in Windows](https://github.com/nodejs/node-gyp/issues/849)
4. [stack: Troubles with NPM and node-gyp in Windows](http://stackoverflow.com/questions/34335043/troubles-with-npm-and-node-gyp-in-windows)
5. [Version 1.0.6 requires a rebuild during npm install](https://github.com/laverdet/node-fibers/issues/236)

**Comment by sinasalek** [comment]
wekan-0.11.1-rc1.tar.gz contains fibres binaries, but when i run wekan i receive the following error, the strange thing is among those binaries there binaries for both Windows x32 and x64 so why is it looking for it on a wrong path? even when i compiled wekan from source, the generated fibres binaries did not contain such a folder!
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: %1 is not a valid Win32 application.
wekan\bundle\programs\server\node_modules\fibers\bin\win32-x64-v8-3.14\fibers.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Sina\Downloads\wekan\bundle\programs\server\node_modules\fibers\fibers.js:20:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I tried copy those binaries to the folder it's looking for but now i receive the following error: 

What do you think? is this problem related to wekan or fibres, meteor? my google search so far was not much of a help.
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: %1 is not a valid Win32 application.
wekan\bundle\programs\server\node_modules\fibers\bin\win32-x64-v8-3.14\fibers.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Sina\Downloads\wekan\bundle\programs\server\node_modules\fibers\fibers.js:20:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by xet7** [comment]
@sinasalek 

wekan-0.11.1-rc1.tar.gz has been compiled on Linux, I think it does not directly work on Windows.

I'll try to compile Windows version and see if those could be combined, or have Windows
version in .zip file.

**Comment by sinasalek** [comment]
I couldn't build x64 binaries for fibres (probably because of dependency issues) but manged to build x32 binaries. i copied them over to fibers/bin and finally got passed the error.
No i'm getting the following error, i search for the windows binary on my recent build from source and copied it over again and the problem fixed. It seems that it's working fine now i'm playing with it to see if there is still any problem.

```
wekan\bundle\programs\server\node_modules\fibers\future.js:280
                                                throw(ex);
                                                      ^
Error: %1 is not a valid Win32 application.
wekan\bundle\programs\server\npm\node_modules\meteor\npm-bcrypt\node_modules\bcrypt\build\Release\bcrypt_lib.node
    at Module.load (module.js:356:32)
    at Module.Mp.load (wekan\bundle\programs\server\npm\node_modules\meteor\babel-compiler\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (wekan\bundle\programs\server\npm\node_modules\meteor\npm-bcrypt\node_modules\bcrypt\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (wekan\bundle\programs\server\npm\node_modules\meteor\npm-bcrypt\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (wekan\bundle\programs\server\npm\node_modules\meteor\babel-compiler\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (wekan\bundle\programs\server\boot.js:190:18)
    at Package (packages/npm-bcrypt/wrapper.js:1:1)
```

**Comment by sinasalek** [comment]
An official Windows build is highly appreciated, wekan is really good for using as client kanban board and it's very fast.
Here is a hackish way to run it then, i don't like it but it works :
```
FOR %%A IN (.) DO (
SET CURDIR=%%~dpnA
)
cd %CURDIR%
SET MONGO_URL=mongodb://127.0.0.1:27017/wekan
SET ROOT_URL=http://127.0.0.1:8081/
SET MAIL_URL=smtp://user:pass@mailserver.example.com:25/
SET MAIL_FROM=wekan-admin@example.com
SET PORT=8081
start "" MongoDBPortable\MongoDBPortable.exe
PING 1.1.1.1 -n 1 -w 1000 >NUL
start "" nodejs\node.exe bundle\main.js
PING 1.1.1.1 -n 1 -w 3000 >NUL
ChromiumPortable\ChromiumPortable http://127.0.0.1:8081
```

**Comment by entrptaher** [comment]
After testing for several hours, I've come up with final solutions, I've been using node version 6.9, 6.10 and 7.6. In my case there were node-gyp related issues, so I suggested a visual c++ build, I don't see anything related to visual c++ in your issue details.

Also, It's advisable to use an ongoing issue instead of creating a new issue, it keeps all the problems and solutions on same page. 

I've updated the details of this wiki, please try again and reply how it went after following all of them,
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

**Comment by sinasalek** [comment]
@entrptaher The new guide worked just fine, i tried it on a fresh Windows 10 Pro and could compile wekan from source and run it on Windows, then i copied the windows binaries for fibres and bcrypt over to the linux binary release to make it run cleanly. However we can't expect every user to spend several hours for just running the application. The problem is there is no windows binary build so everytime we have a new release i have to do the whole process again if the used fibres and bcrypt version changes.

So the next step as @xet7 mentioned is to add Windows to the build process and have a separate zip file for Windows.

**Comment by sinasalek** [comment]
[The are also more robust solutions making meteor desktop app](https://forums.meteor.com/t/a-meteor-desktop-application/291/47). [arboleya:electrify](https://atmospherejs.com/arboleya/electrify?__hstc=256467284.3edb733801a32e11f40d7efb68f9710a.1487243528182.1488472767063.1488552819921.5&__hssc=256467284.1.1488552819921&__hsfp=124040765) looks like a good option

**Comment by hellectronic** [comment]
Anyone experience with electrifying? This would be awesome!

**Comment by chrisafl** [comment]
@sinasalek Have you checked out [https://dmitryivanov.net/](https://dmitryivanov.net/)?

It contains "Portable Kanban" and might be able to fulfill your needs.

**Comment by sinasalek** [comment]
@chrisafl Yes i did, i tried many different kanaban boards util i decided to use Wekan, that's the reason i said if wekan supports desktop, it can be extremely useful for many people.
Portable Kanban has good set of features but unlike wekan it is not user friendly and difficult to use specially for heavy users such as myself. It does not import from trello, and it is not open source (i could find any) nor cross platform, also it supports only one board!.

I don't have any problem using Wekan on my desktop after i managed to set it up, the experience is great. I run it with single click and it's fast. But it is a very ugly and unmaintainable way of doing it and i will have problem with updates.

**Comment by chrisafl** [comment]
@sinasalek I agree with all of your points. Additionally, I would love to see an easy to install desktop version of Wekan as well. Thank you for the work you did to get it working and for sharing it with everyone. Hopefully it can end up in a nice MSI package for newbies like me one day.

**Comment by emahuni** [comment]
any news on this?

**Comment by xet7** [comment]
@emahuni 

At #1088 somebody already got Wekan running on Windows by installing from source as related git submodule bug got fixed recently, more details about Windows support at https://github.com/wekan/wekan/wiki/Platforms#source-on-windows

So this mainly requires somebody testing is it possible to create standalone Windows package and add related info to wiki. Then I could make releases also as standalone program on Windows.

**Comment by xet7** [comment]
Moved to here from #447

@abdulquadir202 

AFAIK newest Docker for Windows and Mac include Docker Compose, and they should be also able to run Linux containers with this docker-compose.yml:
https://github.com/wekan/wekan-mongodb

There has been a lot of Wekan upgrades like Meteor 1.6.0.1 etc that can be seen from Dockerfile:
https://github.com/wekan/wekan/blob/devel/Dockerfile

Anyone having newest Docker for Windows, please test these with Linux and Windows versions of dependencies, and add results about your tests to this issue. Thanks!

**Comment by xet7** [comment]
@sinasalek 

Yes, you can convert this bash file to bat file, and run with only node:
https://github.com/wekan/wekan-maintainer/blob/master/virtualbox/start-wekan.sh

**Comment by xet7** [comment]
Moved to #710
