### ISSUE TITLE
Capital letters in Username / Email. User unable to log in / reset password.

### ISSUE THREAD

**Issue by rvalle** [wekan/wekan#887]
Hi!

I somehow run into a path in which users could neither log on / request a new password.

I believe I invited new users to a board, and users accepted via email creating a new account.

I believe users were able to interact with the system as they kept their session open for some weeks.

Later when the session, for whatever reason, expired they could not log on the system / request new password.

Looking in the database I found the user with first letter in username and email capitalized, like User, Email@domain.com.

there seems to be an usability problem here. The log in form will convert email to lowercase, but the invitation form will accept a capitalized email. Probably any of the browsers autocapitalized the fields as they were edited.

**Comment by xet7** [comment]
Moved to #825
