### ISSUE TITLE
HipChat / Slack notifications

### ISSUE THREAD

**Issue by arjitc** [wekan/wekan#889]
Would be really useful to have these, to push a notification into HipChat or Slack when a task/issue is moved from column to column, assigned to someone, commented on etc

**Comment by dimidd** [comment]
Hi @arjitc ,

This already exists, at least for slack. In Slack, go to Manage -> Custom Integrations -> Incoming webhooks, and create in slack an incoming hook. Then, in wekan go to menu->Outgoing webhooks and paste the url.

**Comment by xet7** [comment]
This already exists.
https://github.com/wekan/wekan/wiki/Features#webhooks
