### ISSUE TITLE
prevent non numeric input in time input field for start/due dates

### ISSUE THREAD

**Issue by Sohalt** [wekan/wekan#893]
It is currently possible to enter non numeric characters in the time input field when setting start/due dates. The user only gets informed of their error after they have clicked the save button.
It would be better to immediately catch bad input as the user types, effectively preventing invalid input from being entered in the first place.

**Comment by xet7** [comment]
@Sohalt 

Would this cause problems in some languages that probably don't use Arabic numerals?

**Comment by Sohalt** [comment]
The labels already provide hints as to what to enter (the light gray text in the background) so I think it's predetermined what constitutes a valid date format. Doesn't it make sense to enforce that while typing?

**Comment by xet7** [comment]
@Sohalt 

How to make enforcing work on all languages, including Chinese, Japanese etc?

**Comment by xet7** [comment]
For example:

![enforce-date](https://user-images.githubusercontent.com/15545/28669726-01756620-72de-11e7-9747-e1216908533d.png)

And also order or date, month and year changes by language settings.
Is there some pre-made node package for this?

**Comment by xet7** [comment]
Moved to #2011
