### ISSUE TITLE
Can't send emails without credentials

### ISSUE THREAD

**Issue by mgiacomoli** [wekan/wekan#895]
Hi, I have a local smtp server and I'd like to send emails without using credentials. With version 0.12 configuring email parameters in admin panel forces me to enter username and password.
Also setting in mongodb empty username and password fields in settings collection gave me errors. I had to manually patch the code too.
I ask you to add an option in admin panel that let you not specify user credentials

Best regards
MG

**Comment by xet7** [comment]
@mgiacomoli 

What patch code did you use?

**Comment by xet7** [comment]
@lkisme 

Do you know how to fix this?

**Comment by mgiacomoli** [comment]
@xet7 I patched the code by myself in `programs/server/packages/email.js` 
The (ugly) patch I quickly wrote to workaround the problem just skips using credentials if `mailUrl.auth == ":"` in function makePool.

**Comment by simopaasisalo** [comment]
+1

**Comment by xet7** [comment]
Fixed in today's Wekan release v0.13.
