### ISSUE TITLE
Admin Panel Access?

### ISSUE THREAD

**Issue by arjitc** [wekan/wekan#897]
I'm currently running the latest docker image (published ~2 days ago) but am not able to find the "admin" panel in the dropdown 

![image](https://cloud.githubusercontent.com/assets/363587/23658830/f221d1e2-0369-11e7-81de-525cc09be896.png)

Is there anything else I have to do to enable the admin panel?

**Comment by xet7** [comment]
Yes. Read changelog on github repo for instructions, and github wiki docker mongodb backup page how to make change to mongodb inside docker.

**Comment by jazn** [comment]
Shortcut to changelog: https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v0111-rc2-2017-03-05-wekan-prerelease
