### ISSUE TITLE
Unable to install release v0.12 on ubuntu 16.04

### ISSUE THREAD

**Issue by souch** [wekan/wekan#899]
Hi,

By following this doc  : https://github.com/wekan/wekan/wiki/Install-and-Update#install-a-wekan-release
I am not able to install wekan.

On ubuntu 16.04 LTS 64 bits :

installed npm from: 
`sudo apt install npm`

installed node helper: 
`sudo npm install -g n`

installed nodejs v6.6.0: 
`sudo n 6.6.0`

got latest wekan release v0.12 archive using 
`wget https://github.com/wekan/wekan/releases/download/v0.12/wekan-0.12.tar.gz`
extracted it to newly created dir wekan-0.12

run: 
`cd wekan-0.12/bundle/programs/server`
`sudo npm install`

exported the 5 required env vars NAME MONGO_URL ROOT_URL MAIL_URL PORT

run: 
`cd wekan-0.12/bundle`
`node main.js`

got crash :
```
/home/me/wekan-0.12/bundle/programs/server/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
        ^

Error: `/home/me/wekan-0.12/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-5.1/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/home/me/wekan-0.12/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/me/wekan-0.12/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:556:32)
```

**Comment by soohwa** [comment]
You should retry with node 0.10.48 and because of fibers rebuild it from source : https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source

**Comment by souch** [comment]
Thanks, for your answer. We didn't try it still because we switched to another task. And we prefer work on one problem at a time. We'll try to your solution ASAP.

**Comment by souch** [comment]
I reinstalled from source following the doc and it works.
The only modifications on the instruction was to add `sudo` for every npm command:

```
    sudo npm install n
    ## if the previous fails (and asks you to run as sudo) just rm /home/<username>/node_modules and retry
    sudo n 0.10.48
    sudo npm install npm@latest
    sudo npm install node-gyp
    sudo npm install fibers

    # install wekan npm dependancies
    sudo npm install

    sudo meteor build .build --directory
    cd .build/bundle/programs/server
    sudo npm install
```

**Comment by xet7** [comment]
@souch 

sudo is not needed for every command. I added those back that are needed. I'm not the only one contributing to wiki, some would like that installing would work without sudo, but it's not possible yet.

**Comment by souch** [comment]
Ok, thanks for the feedback.
