### ISSUE TITLE
Import Trello json, comments are wrong member

### ISSUE THREAD

**Issue by squidrpi** [wekan/wekan#903]
When importing from trello json the comments are all set to the member importing the cards not the member who created the comment on trello. Member allocation for the cards works fine.

**Comment by xet7** [comment]
@whodafly

Can you try to fix this?

**Comment by whodafly** [comment]
I actually tried to fix this with my checklist import change, but it didn't seem to work. I'll try to look into this.

**Comment by quants-ch** [comment]
Had the same situation here when trying to import json from Trello.
This feature would be really great to work properly.
Thanks!

**Comment by xet7** [comment]
@GhassenRjab 

Do you have time to look at this?
