### ISSUE TITLE
Add Feature: Checklist templates. Import and Export checklists.

### ISSUE THREAD

**Issue by waldren** [wekan/wekan#904]
Checklists are a very powerful tool to ensure everything is addressed. There are classes of tasks that have the same checklist items (i.e. to get sign off, check in new code, etc.). It would be helpful to be able to create a checklist template that be reused for new tasks (card). Right now one must create a new checklist each time and hope they remember all the items that should be on the checklist.

Thanks for considering.

**Comment by luckyboy** [comment]
Looking forward to this feature.

**Comment by slyk** [comment]
I think the easy way to help people that need this feature fast - would be parsing multiline checklist item as separate items. Then we just save multiline text in "notepad on desktop" and paste where it needed. System recognize new line chars and instead of removing them, creates checklist item for every line.

**Comment by xet7** [comment]
Moved to here from #1416

From @fbatschi 

Feature Request: Add a new checkbox to the "Copy card"  dialog which lets you decide whether you want to have the potential  checklist items in the same state as they currently are, or whether they  should be unchecked. Background: I have cards with many checklist items. Once I am done with all the  items, I need to copy the card with the same content for the next month.  Currently it copies the card exactly as it is right now, meaning all  checked items are also checked in the new card. Would be great to have a  real "fresh" card without any checked items.

**Comment by xet7** [comment]
This Checklist Template feature https://github.com/wekan/wekan/pull/1470  is included in today's Wekan release v0.75 . You can create checklist and copy it to many cards to same or another board in Standalone Wekan. You generally export and import board that has checklists, there is no export/import for only checklist yet.

**Comment by xet7** [comment]
Reopening, because there is not yet import/export of checklists.

**Comment by Kisakila** [comment]
> 
> 
> Reopening, because there is not yet import/export of checklists.

Hello Guys,
any update about this feature ? 
thanks for your work.

**Comment by xet7** [comment]
@Kisakila 

I can code this feature, if someone pays 300 euro for time I use to develop this:
https://wekan.team/commercial-support/

**Comment by jdaviescoates** [comment]
If I could import csv or txt checklists that would almost solve #1846 for me too.

**Comment by eMUQI** [comment]
can wekan import Templates ?

**Comment by xet7** [comment]
@eMUQI 

Not yet.

**Comment by jdaviescoates** [comment]
I was hoping that this issue being closed indicated that either checklist templates or bulk import/ expert of checklists were now doable, but it doesn't appear that is the case. So why closed? Thanks!

**Comment by xet7** [comment]
@jdaviescoates 

See https://github.com/wekan/wekan/issues/3177

**Comment by lonelyadmin** [comment]
Just to be clear, there is currently no way to reuse common checklists?

**Comment by xet7** [comment]
@lonelyadmin 

There are these ways to reuse checklists:

You can add checklist to some board, and:
a) duplicate board at All Boards page, by clicking duplicate button you see when mouse pointer is over board icon
b) in Swimlane menu `☰` => `Copy Swimlane` you can copy swimlane to other board.
c) in card menu `☰` => `Copy Card` you can copy card to other board

Then, at card menu `☰` => `Copy Checklist Template to Many Cards` you can create many copies of that checklist, with different card titles.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
