### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by shaygover** [wekan/wekan#906]
Hi,

Let's say I've just updated the translation on transfix, what do I need to do to update my installation?

Thanks,

Shay

**Comment by ocdtrekkie** [comment]
The next release of Wekan should include all of the translation updates pulled from Transifex.

**Comment by xet7** [comment]
@shaygover 

Addition: I do pull translations from Transifex often, and they are immediately available to install using automated Docker builds, and any platform that installs directly from source.

**Comment by shaygover** [comment]
Thanks
