### ISSUE TITLE
ROOT_URL and PORT

### ISSUE THREAD

**Issue by anselal** [wekan/wekan#907]
I tested wekan v0.12 and v0.13 and noticed that I must specify the port number in the ROOT_URL variable. When I don't do that then I cannon open my cards because the link does not include the port number (PORT variable)
The link for creating a new board, list and card concats the ROOT_URL with the PORT variable. But the link for editing a card does not. Please fix this and update the wiki section so that the ROOT_URL is clean without the port.

**Comment by anselal** [comment]
When I leave the ROOT_URL to 127.0.0.1 then I still cannot edit a card because the link is in the form of 127.0.0.1 but the links for creating boards, cards and lists are in the form of http://MY_IP:PORT/....
If I remember correctly this was not an issue in versions v0.10.1 and earlier.

**Comment by NoodleBB** [comment]
I've updated last weekend. I can confirm that bug. This bug doesn't existed in v0.10.1. And it just drove me crazy. 

@anselal: Thanks for the hint.

**Comment by anselal** [comment]
Glad I could help.

**Comment by xet7** [comment]
@lkisme 

Can you check this?

**Comment by lkisme** [comment]
I didn't see this bug with running Wekan with source code, what's you guys' environment?

**Comment by NoodleBB** [comment]
My system:

- OS: centos-release-6-8.el6.centos.12.3.x86_64
- Kernel: Linux 2.6.32-642.6.2.el6.x86_64
- wekan: v0.16
- node: v0.10.43
- mongo: 2.6.12

**Comment by xet7** [comment]
In some issue was comment that ROOT_URL is not in use anymore, only setting in Admin Panel works. I have not tested it.

**Comment by NoodleBB** [comment]
I had to set the ENV var.

**Comment by lkisme** [comment]
ROOT_URL is for the address of the whole web app, but you can only set SMTP related info(MAIL_URL & MAIL_FROM) in admin panel as far as I know, the functionality of admin panel would have no side effect on "ROOT_URL" setting.

**Comment by NoodleBB** [comment]
This bug also appears also when you click on "Export board" in the "Board menu".

**Comment by nztqa** [comment]
Need an absolute URL in e-mail notification system. https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v0110-rc2-2016-07-21

See also 
 - #679 
 - https://docs.meteor.com/api/core.html#Meteor-absoluteUrl

**Comment by xet7** [comment]
@nztqa 

Does this need some fix? Or can this be closed?

**Comment by nztqa** [comment]
@xet7 No fix. Please close this issue.

**Comment by xiaohelong** [comment]
特别注意：在系统中需要设定ROOT变量为设定的ip或者域名，否则页面中很多地方会全是localhost
在/home/wekan/repos/run-wekan.sh中将ROOT_URL和端口改成本机IP和需要的端口即可解决页面很多链接是localhost基地址的问题。改完后，重启计算机。
while true; do
        cd /home/wekan/repos/wekan/.build/bundle
        export MONGO_URL='mongodb://127.0.0.1:27017/admin'
        # Production: https://example.com/wekan
        # Local: http://localhost:3000
        export ipaddress=$(ifdata -pa eth0) #autoset ipaddress 这是自动获取系统IP地址的命令，默认是注释掉的。
        export ROOT_URL='http://10.0.2.15' # set ip here 
        export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
        # This is local port where Wekan Node.js runs, same as below on Caddyfile settings.
        export PORT=80
        node main.js
done

**Comment by xiaohelong** [comment]
Wekan Meteor 1.4 and Node.js v4.x version on Ubuntu 14.04 64bit desktop, Gnome fallback, in VirtualBox
When using VirtualBox bridged mode, you can browse from other computer to http://ipadress to use Wekan. Node runs on port 80 and is started from /etc/rc.local on boot. See also README.txt at Ubuntu desktop, scripts at ~/repos directory, and /home/wekan/.bash_history how it was installed, including typos :)

To login to the virtual machine with ssh port 22:

username: wekan

password: wekan

vdi文件为virtualbox的
voa为通用的，可以用vmware导入的文件。（vmware要比virtualbox好用稳定)
特别注意：在系统中需要设定ROOT变量为设定的ip或者域名，否则页面中很多地方会全是localhost
在/home/wekan/repos/run-wekan.sh中将ROOT_URL和端口改成本机IP和需要的端口即可解决页面很多链接是localhost基地址的问题。改完后，重启计算机。
while true; do
        cd /home/wekan/repos/wekan/.build/bundle
        export MONGO_URL='mongodb://127.0.0.1:27017/admin'
        # Production: https://example.com/wekan
        # Local: http://localhost:3000
        export ipaddress=$(ifdata -pa eth0) #get ip from command,这是自动获取系统IP地址的命令，默认是注释掉的。
        export ROOT_URL='http://10.0.2.15' #set your iphere
        export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
        # This is local port where Wekan Node.js runs, same as below on Caddyfile settings.
        export PORT=80
        node main.js
done
~
