### ISSUE TITLE
Compatibility Mode Internet Explorer 11

### ISSUE THREAD

**Issue by immertroll** [wekan/wekan#909]
We use the Compatibility Mode IE8 in the Internet Explorer 11. With activated mode the wekan board doesn't load. It's not possible to set some websites to a "whitelist".

The only possibility is to force the IE11 mode with an meta-tag. Please add this tag in wekan.
<meta http-equiv="X-UA-Compatible" content="IE=11" />

source: https://msdn.microsoft.com/library/cc817574.aspx

**Comment by REJack** [comment]
I personally would not set it on `IE11`, i would set it on `edge`.

**Comment by immertroll** [comment]
That would also be a great improvement. Thanks

**Comment by xet7** [comment]
Added at https://github.com/wekan/wekan/commit/862ce27eb935c3f1a0a0af18e484c0f18dcbef5b
Will be included in release v0.14.

Closing issue.

**Comment by immertroll** [comment]
Does the latest docker image include this change?
btw: Can I find out which version the Docker Image is based on?

**Comment by xet7** [comment]
@immertroll 

Yes, docker latest tag includes this change. And source install. See changelog for changes.

There is not tag numbers yet on Docker Hub, I'll try to contact @mquandalle to get access there so I can add tags.

Latests tag includes all latest changes from GitHub repo. It's rebuild after every new commit.

**Comment by gil0109** [comment]
@xet7 I am not sure this applies to the Login page.  If not, I need this on the login page for the OIDC login to work correctly.

Currently the code is here: client/components/main/layouts.jade

Specifically this: <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>

Thanks

**Comment by xet7** [comment]
@gil0109 

When I look at /sign-in webpage source, there is this:
```
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```
AFAIK this if for all Wekan webpages.

Is there something that does not work?
