### ISSUE TITLE
ATCreateUserServer -> invitationcode

### ISSUE THREAD

**Issue by iAdanos** [wekan/wekan#910]
Just updated to the lastest version and enabled Admin Panel. 

I was testing that registration is really closed, and i've got:

1. If registration is closed in Admin Panel and user try to register without invitation code, i get the following error in wekan container log:
`13.03.2017 20:48:04Exception while invoking method 'ATCreateUserServer' TypeError: Cannot read property 'invitationcode' of undefined`  
`13.03.2017 20:48:04    at AccountsServer._onCreateUserHook (models/users.js:404:19)  `
`13.03.2017 20:48:04    at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1239:21)  `
`13.03.2017 20:48:04    at _createUser (packages/accounts-password/password_server.js:998:25)  `
`13.03.2017 20:48:04    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1067:10)  `
`13.03.2017 20:48:04    at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/lib/server_methods.js:103:1)  `
`13.03.2017 20:48:04    at packages/check/match.js:107:1  `
`13.03.2017 20:48:04    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)  `
`13.03.2017 20:48:04    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)  `
`13.03.2017 20:48:04    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)  `
`13.03.2017 20:48:04    at packages/ddp-server/livedata_server.js:711:19  `
`13.03.2017 20:48:04    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)  `
`13.03.2017 20:48:04    at packages/ddp-server/livedata_server.js:709:40  `
`13.03.2017 20:48:04    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)  `
`13.03.2017 20:48:04    at packages/ddp-server/livedata_server.js:707:46  `
`13.03.2017 20:48:04    at tryCallTwo (/build/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5)  `
`13.03.2017 20:48:04    at doResolve (/build/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13)`  
![image](https://cloud.githubusercontent.com/assets/4068779/23868003/e2ab309a-082e-11e7-8976-07d219e072f0.png)

2. If user try to register with non-existing invitation code, i have nothing in log, and:
![image](https://cloud.githubusercontent.com/assets/4068779/23868087/2699f502-082f-11e7-9b36-dd70ca98aae2.png)

Note: "Неизвестная ошибка" translates as "Unknown error"

**Comment by xet7** [comment]
@lkisme 

Can you try to fix this?

**Comment by NoodleBB** [comment]
I get exact this error on a fresh installation of v0.16. When i try to register the first user. :confused:

**Comment by NoodleBB** [comment]
I have exactly the same problem.

**Comment by lkisme** [comment]
About the error msg when invitation code doesn't exist, I'm still working on it.
Wekan uses ["meteor-useraccounts"](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#errors-text) package to implement the user signin/signup functionality, and it's really "not development-friendly" to customize, haven't find an safe and elegant way to customize the error msg.

**Comment by lkisme** [comment]
This should be fixed in the latest update.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/943
