### ISSUE TITLE
Failed to send invite

### ISSUE THREAD

**Issue by iAdanos** [wekan/wekan#911]
When sending an invite from Admin Panel, i get:
`13.03.2017 21:00:05Exception in callback of async function: Error: Mail from command failed - 501 5.1.7 Bad address mailbox syntax. [email-fail]`
`13.03.2017 21:00:05    at sendInvitationEmail (models/settings.js:107:13)`
`13.03.2017 21:00:05    at models/settings.js:124:15`
`13.03.2017 21:00:05    at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core/lib/collection2.js:467:1)`
`13.03.2017 21:00:05    at packages/mongo/collection.js:651:5`
`13.03.2017 21:00:05    at args.(anonymous function) (packages/matb33_collection-hooks/insert.js:44:1)`
`13.03.2017 21:00:05    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)`
`13.03.2017 21:00:05    at packages/meteor/dynamics_nodejs.js:123:1`
`13.03.2017 21:00:05    at packages/mongo/mongo_driver.js:322:7`
`13.03.2017 21:00:05    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)`

**Comment by xet7** [comment]
@lkisme 

Do you have idea how to fix this?

**Comment by boolsee** [comment]
In my case, successfully sent an invitation mail but failed to sign-up with the invited e-mail.
Set up the SMTP setting in "**Admin Panel > Settings > Email**"  before sending an e-mail. If you failed sending an e-mail already, you should delete the invitation record from your MongoDB like this before retry it.

(I'm using the latest docker image.)

$ mongo
use wekan
use admin
db.invitation_codes.find({})
db.invitation_codes.remove({})

**Comment by lkisme** [comment]
For the error of @iAdanos , it seems the mailbox setting is wrong, maybe you should check if you set the SMTP correctly.

@boolsee Yes, consider this is a known bug, I believe I did mention consider this somewhere, the invitation code should be removed if email sending failed.

**Comment by iAdanos** [comment]
@lkisme, I'm using the same config as before update. It was working.
I tryed to change SMTP options, save config and enter correct options again. The result is the same. Maybe I'm doing something wrong.

**Comment by lkisme** [comment]
@iAdanos , are u using version later than 0.1.3?
If so, please be aware of this:
1. Your input of SMTP setting in admin panel will compose a string to replace the old `MAIL_URL=smtp://user:pass@mailserver.example.com:25/` env.
1. If the fields of username and passworld is left blank, the string will be `MAIL_URL=smtp://mailserver.example.com:25/`
1. Or, 501 error might cause by the syntax of "TO" value(destination address) is wrong.

Hope this will help you on the troubleshooting

**Comment by Zokormazo** [comment]
This should be fixed by https://github.com/wekan/wekan/pull/968
