### ISSUE TITLE
Installed wekan on mac but what is default username and password

### ISSUE THREAD

**Issue by mendipankaj** [wekan/wekan#913]
hi, Just installed wekan on mac so I have no idea what is the default username and password and when tried to register then gets Internal server error. Tried to export MAIL_URL but it is not set yet. COuld you help

**Comment by xet7** [comment]
@mendipankaj 

What platform? Docker, install from source, or other?

**Comment by mendipankaj** [comment]
Kiitos Lauri. Actually i am beginner so i just used meteor and it did everything for me.

Do you need any other information.

**Comment by xet7** [comment]
@mendipankaj 

Enabling Admin Panel that has SMTP settings:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md

Docker Compose:
https://github.com/wekan/wekan-mongodb

Source:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source

**Comment by vClouds** [comment]
Please clarify, what does it meant by "Admin Panel" exactly?
Is it "Users Management" as we know it?
I installed v0.13 but i found that, anyone can access and signup.
Login admin/admin seems like regular member.

**Comment by xet7** [comment]
@vClouds 

There is only these:

1) When Wekan is first installed, first wekan user(s) need to register themselves. Registering works even when email settings are not correct yet.

2) Enable Admin Panel for username you have already created in MongoDB database.

3) In Admin Panel has options:
a) To disable user registration, and invite users by email.
b) SMTP settings for sending email.

I could try to add screenshots and description of features sometime.

**Comment by vClouds** [comment]
@xet7 
Many thanks for the above clarifications!
Well, means wekan is flexible to be left to the public for registration or to be switched to users management mode which imposes invitations mode.
That's great.

Now, I can understand what's meant by that feature introduced since v0.11.1-rc2.

Can you please hint on commands of mongo cli to enable Admin mode?
Sorry, I just recently started moving to wekan and leaving restya.

**Comment by xet7** [comment]
@vClouds 

https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v0111-rc2-2017-03-05-wekan-prerelease

https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

**Comment by voicyfei** [comment]
Hi, when i register the first user, it shows "From admin is required", have i missed any thing?
i installed wekan on my mac, with docker prodution https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by e-stoniauk** [comment]
> @vClouds
> 2. Enable Admin Panel for username you have already created in MongoDB database.

Can anybody tell how to enable for example for user "user33" Admin Panel from MongoDB?
