### ISSUE TITLE
NPM issue while installing wekan

### ISSUE THREAD

**Issue by petrk94** [wekan/wekan#918]
Hello,
I tried to install wekan, but get this error message below:
![wekan](https://cloud.githubusercontent.com/assets/19719052/24047638/9c9bd23a-0b26-11e7-870d-935cd3c5640b.PNG)

What can I do to solve this issue?
Thanks

**Comment by REJack** [comment]
Try to use nodejs v0.10.40+ not the latest version

**Comment by petrk94** [comment]
The problem is, that I have other Apps which need a more current version.

**Comment by REJack** [comment]
Then you should use something like `n` or `nodenv`.

**Comment by xet7** [comment]
@petrk94 

Installing from source:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source

Alternatives:

1) Use Docker install

2) Help with, or wait for newer version port: https://github.com/datamaker/wekan

Would this work for you?

**Comment by petrk94** [comment]
@xet7 thanks for your help.
But I have only a VPS server from Uberspace, so some restrictions, docker is gone and sudo I dont have full access. I have chose a alternative MeisterTask!

Thanks anyway
