### ISSUE TITLE
Feature Request: Private setting for Labels

### ISSUE THREAD

**Issue by Marabon** [wekan/wekan#920]
I think it'd be great if we could have the option to mark a label as private in a public board.
The way I'm thinking it'd work is a simple checkbox in the label settings for Private Label.
If the label is flagged as private the cards and activity with the label on it is hidden for public guests/users not a member of the board.

This would allow you to have a public view of a development board, while keeping internal cards/issues private. Instead of having to maintain a private board, and another board with the "public" progress.

I tried to search to see if there was a request for such a feature but didn't find any.

Thoughts on this?

**Comment by xet7** [comment]
For somebody implementing this, there is already related features for:

- private / public boards
- filters
- labels
- hiding system messages.

Look at git history with GUI like gitk to see how those are implemented. It's just mainly looking at the code and figure out how to combine them.

Submit pull request to devel branch. Thanks! :)

**Comment by xet7** [comment]
Moved to #3022
