### ISSUE TITLE
[Out-dated info] /wekan/wiki/Install-and-Update#install-manually-releases

### ISSUE THREAD

**Issue by theriverman** [wekan/wekan#922]
Hi,

Found a little inconsistency here: [Install and Update/Manual Installation Steps](https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps)

> Make sure Node.js is installed (currently Version 0.10.40 is required). If you don't have this version, you can use the node packages.

I followed every step of guide. My output is the following:

> root@ip-***:/var/lib/wekan/bundle# node main.js
> Meteor requires Node v0.10.41 or later.
> root@ip-***:/var/lib/wekan/bundle# node -v
> v0.10.40
> root@ip-***:/var/lib/wekan/bundle#

Cheers

**Comment by xet7** [comment]
Fixed.

Wiki is freely editable by any GitHub user, and documentation contributions are very welcome, so in future you or anybody else can fix those directly to wiki. No need to create new issue.

Closing issue.
