### ISSUE TITLE
Bug: First user registration produces exception [0.16], [0.13], [0.12],

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#923]
The first user registration on a plain fresh manual install of versions later than 0.10.1. (0.12, 0.13, 0.16) produces an Exception:

```
Exception while invoking method 'ATCreateUserServer' Error: getaddrinfo ENOTFOUND
    at Object.Future.wait (/home/wekantst/wekan/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at smtpSend (packages/email/email.js:89:1)
    at Object.Email.send (packages/email/email.js:192:1)
    at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:797:9)
    at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/lib/server_methods.js:119:1)
    at packages/check/match.js:107:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at tryCallTwo (/home/wekantst/wekan/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/wekantst/wekan/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13)
    - - - - -
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:126:16)
```

The parameters / env-values were:
```
MONGO_URL=mongodb://wekantst_mongoadmin:username@127.0.0.1:21421/wekan?authSource=admin
PORT=61258 
ROOT_URL=http://wekantst.lupus.uberspace.de:61258/ 
MAIL_URL=smtp://username:password@lupus.uberspace.de:587/ 
MAIL_FROM=username@lupus.uberspace.de
```

**Comment by xet7** [comment]
@NoodleBB

Please don't include your username and password in GitHub issues, and please change them. I removed them from your post above.

Is this same as #910 ? That has ATCreateUserServer error too.

**Comment by NoodleBB** [comment]
I'm aware of that. This was just from a testing account.

**Comment by xet7** [comment]
Ok, we'll keep it separate.

**Comment by xet7** [comment]
@NoodleBB 

Ok I'm able to duplicate this issue.

1) I think this is because there's some problem in sending registration email to first one that registers account to Wekan.

2) Although it gives this error, new user account is created anyway, and it's possible to login as that new just created user. It's possible to register also with invalid email address, it's not mandatory to have working SMTP server.

3) Another related issue could be that usually registering and logging in works in some languages like English etc, but no all, because of missing translations of login screen. I have not checked what is current status of different languages.

**Comment by NoodleBB** [comment]
I had the same assumptions, the log points in that direction. My language settings was "_english_".

**Comment by REJack** [comment]
@NoodleBB Did you tested the mailserver domain from your shell login? (with a ping or telnet test)

I don't know, but it could be that your mailserver domain cant be resolved trough your server, try the ip address instead of the domain.

**Comment by NoodleBB** [comment]
Yes. The mailserver is up and fine.

**Comment by REJack** [comment]
I had a similar issue, i've fixed it with setup smtp over the admin panel. Did you tried this?

**Comment by NoodleBB** [comment]
This problem occurs before a user exits. So you can't disable it in the admin panel.

**Comment by REJack** [comment]
Sure you can disable it in the admin panel, after the error you can straight login ^^ wekan doesn't send a verification mail, like xet7 wrote it ^^ You only need to set the user as admin over the mongo cmd.

But try to encode your account and password, that was my issue and i got a similar error message.

**Comment by NoodleBB** [comment]
I don't get the point of your post.

**Comment by REJack** [comment]
The Settings work trough the Admin Panel? If yes, encode your account and password it's often the problem inside a `smtp`-url.

**Comment by NoodleBB** [comment]
Yes, the settings work in the admin panel. You can send invitations etc.

**Comment by REJack** [comment]
It's sounds like your password or username use some special characters that interrupt the url.  

My problem was a `@` in the username that caused an error on my instance.

**Comment by NoodleBB** [comment]
Nope. Just [a-zA-z0-9].

**Comment by REJack** [comment]
Try to wrap your env-values into `'` or `"`

like this:  
```bash
MAIL_URL='smtp://username:password@alpha.uberspace.de:587/'
```

**Comment by NoodleBB** [comment]
The quote were striped.

**Comment by xet7** [comment]
@NoodleBB 

Try this:

1) Register user account, if you have not registered yet. Ignore any errors it shows.

2) Reload Wekan webpage and login.

3) Enable admin interface by adding your username as admin to MongoDB:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v0111-rc2-2017-03-05-wekan-prerelease
Some of this MongoDB command examples can be useful:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

4) Reload Wekan webpage, you should see Admin Panel in menu.

5) Setup your SMTP etc settings in Admin Panel and save.

**Comment by NoodleBB** [comment]
@xet7 
I know. I've tested that, this way.

**Comment by xet7** [comment]
@NoodleBB 

Are you installing precompiled build from Wekan releases page?

Have you enabled websockets? Wekan needs them.

I'll try installing to uberspace.de later and try to provide instructions to wiki.

**Comment by NoodleBB** [comment]
I can publish my install notes tomorrow.

**Comment by xet7** [comment]
@NoodleBB 

Thanks! Please add your install notes to Wekan GitHub wiki. I will try your install notes and update wiki when I get Wekan to work at uberspace.de.

**Comment by NoodleBB** [comment]
@xet7 
It's in the Wiki now. https://github.com/wekan/wekan/wiki/Install-Wekan-on-Uberspace

**Comment by boolsee** [comment]
![wekan-unknown-error](https://cloud.githubusercontent.com/assets/7019147/24177214/4c931e76-0ee4-11e7-8192-e9eb617da614.PNG)

In my case, I could not sign-up with the invited e-mail. There's no any wekan-app logs, but javascript error like an image instead. 

In my settings:

`> db.settings.find({})
{ "_id" : "YssRKTcc9AccnRMgA", "disableRegistration" : true,`
