### ISSUE TITLE
Add Feature: Set admin on first run

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#924]
When you freshly install Wekan from the bare metal, there's no default user and no admin account. So i would suggest to create a first user / admin account on the first run, by setting a env variable to something like `FIRST_USER =potus44:y3sw3c4n:bo@whitehouse.gov`.

**Comment by Marabon** [comment]
Instead of creating a user upon first run you could also put in a check on the registration, and if the registration is for the first user, make that user the admin account. That would mean no extra/new environment variables.

**Comment by NoodleBB** [comment]
But when the register dialog hangs, it would be very useful to have a first user.

**Comment by Marabon** [comment]
Isn't that a different issue all together if the register dialog hangs? If that issue is solved, then there's no issue in having the first created user be the first admin user.

**Comment by soohwa** [comment]
Maybe on the first run having a first dialog with the choice : public or private use :

- public use : okay, go on without restriction
- private use : okay, restrict registration and define an administrator

**Comment by soohwa** [comment]
Maybe add a third choice : 

- ldap account

**Comment by lkisme** [comment]
The idea of @soohwa's is interesting, but with the "first user is admin& admin panel" feature, you can achieve the same goal

**Comment by soohwa** [comment]
@lkisme @Marabon You're right, it's much more clear and simple :-)
