### ISSUE TITLE
Add Feature: Markdown in cards, card titles, checklists, board titles.

### ISSUE THREAD

**Issue by llagerlof** [wekan/wekan#926]
Can Wekan be configured to accept line breaks in cards?

**Comment by nztqa** [comment]
Card titles?

**Comment by xet7** [comment]
This would be nice, so in card titles and list titles there could be editable markdown similarly like at card description field.

**Comment by xet7** [comment]
Also board title and title's description could allow markdown.

I'm just thinking that does this work, so if those contain only markdown link, is it still possible to both:
1) click link
2) edit titles

**Comment by HLFH** [comment]
I'm sure Wekan now desserves a new release with this great added feature.

**Comment by xet7** [comment]
@HLFH 

Yes, there's also other great features and bugfixes, I'm just adding most of them before making a release.
