### ISSUE TITLE
Notifications by E-mail not working

### ISSUE THREAD

**Issue by itsmedani** [wekan/wekan#929]
Hi all, 

I installed Wekan for docker and everything is working like a charm except e-mail notifications. 

Wekan is able to send e-mail for invitation, so I guess my smtp configuration is working. However, when I modify a card, nobody receive an E-mail. 

In the user panel, I enabled the tracking in the "Edit Notification" and in the "Cards Option" I enabled "Watch".

Did I miss something? How can I check my Wekan current version?

Thanks you guys

**Comment by xet7** [comment]
Moved to #794
