### ISSUE TITLE
Keyboard shortcuts popup aggressively appears

### ISSUE THREAD

**Issue by ocdtrekkie** [wekan/wekan#931]
I'm testing 0.16 on Sandstorm using MS Edge. (https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h?experimental=true)

Clicking on the delete link for a checklist causes the keyboard shortcuts popup to also appear. Clicking on a member on the side bar, moving the mouse off of their picture, and then back and clicking on them again... also makes the keyboard shortcuts popup also appear. It is very strange.

**Comment by ocdtrekkie** [comment]
Does not happen on Firefox.

**Comment by xet7** [comment]
Does not happen to me on:

* Linux Chrome 57.0.2987.110 (64-bit)

* Edge 38.14393.0.0

**Comment by ocdtrekkie** [comment]
Correction on reproduction steps:

- Open the keyboard shortcut list.
- Click off of the keyboard shortcut list to get rid of it.
- Delete a checklist.

**Comment by ocdtrekkie** [comment]
Does NOT happen if you close the keyboard shortcut list with the X. Does happen if you close the keyboard shortcut list by clicking elsewhere on the screen.

**Comment by xet7** [comment]
Ok, with new steps now I can reproduce on Edge, but not on Linux Chrome.

**Comment by xet7** [comment]
Does not happen on Windows Chrome.

On Edge, I can not change Wekan language to Finnish. It stays English. I have Finnish Windows and Edge browser menus are also in Finnish.

On Windows Chrome, Wekan language can be changed to Finnish.

**Comment by ocdtrekkie** [comment]
Still does not happen on Windows Firefox with new reproduction steps. So pretty confident now this is an Edge-specific quirk.
