### ISSUE TITLE
Bug: Unable to add an existing user to a board [v0.16]

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#933]
## Setup
There are different users on the host. Each user has it's own boards. 
Alice (Admin user) want to invite Bob (non-Admin-user) to one of her boards. 

## Problem
There's no way to add an **existing** user as a member to someoneelses board. In the Admin Menu, you can invite **only new users** for **registration**. When you try it with an existing user, it fails.

## Error
When you try to invite an existing user via Admin Menu Registration to a board, you'll get an Error in the log: `Error: Email must be unique [invitation-generated-fail]`.

## Conclusion
It seems you can't invite somebody, that is registered on the same host. 😕

**Comment by Marabon** [comment]
@NoodleBB You're able to add a registered member to a board by going into the board itself and clicking the + sign in the upper right corner and then simply typing their username.

Screenshot: [https://goo.gl/X5oWKA](url)

I think invitation by the admin panel is for inviting new members into a closed system only. Once they're in you can use the above method to add them to specific boards.

**Comment by NoodleBB** [comment]
You're right. Thanks you.
I would await that function in the **board** menu. Not in the right-side-slide-popup-log.
