### ISSUE TITLE
Uses Ubuntu 16.04 VM. You need websockets enabled on your VM.

### ISSUE THREAD

**Issue by congdv** [wekan/wekan#934]
I currently use Ubuntu 16.04 on Vmware, but I really don't know how to enable websockets on my Vmware.

**Comment by xet7** [comment]
@congdv 

I don't know. Websockets work in VirtualBox.

**Comment by congdv** [comment]
Thank you for answer.

**Comment by ravip** [comment]
Hi, Could you pls mention answer here.

I am also having same issue. My nodeJS server with socket connection works fine on AWS, local VM however its not working on Azure VM. Its getting opened and closed immediately on Azure VM.
Do I need to do anything to make websocket working on Azure VM?

**Comment by Farham0** [comment]
Have same here with kind of media server running in Azure, I got an error like following

kurento-client.js:27362 WebSocket connection to 'wss://******.australiaeast.cloudapp.azure.com:8888/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
ws @ kurento-client.js:27362
WebsocketStream @ kurento-client.js:27252
WebsocketStream @ kurento-client.js:27235
(anonymous) @ kurento-client.js:25476
attempt @ kurento-client.js:25380
emitTwo @ kurento-client.js:4927
emit @ kurento-client.js:4998
Backoff.onBackoff_ @ kurento-client.js:2236
