### ISSUE TITLE
Uploading attachment knocks Wekan offline

### ISSUE THREAD

**Issue by outdoorWI** [wekan/wekan#936]
When we upload an attachment to a card, Wekan is knocked offline.  Sometimes Wekan will resume working after a few seconds, or minutes.  And sometimes I must restart the server.

Also, once an attachment is uploaded to a card, no one is able to download the attachment.

I'm using the latest Docker Image on Ubuntu 16.04.2 with an Apache2 reverse proxy.

**Comment by xet7** [comment]
@outdoorWI 

Does attachment filename contain special characters?

What MongoDB version are you running?

**Comment by outdoorWI** [comment]
The MongoDB version 3.4.2 - it is installed automatically when you pull the docker image from the hub.

**Comment by xet7** [comment]
@outdoorWI 

Wekan crashes with MongoDB 3.4.x, it's know issue.

Use MongoDB 3.2.x, like in this Docker Compose file:
https://github.com/wekan/wekan-mongodb

This will probably be fixed by @datamaker when Meteror 1.4 port is complete:
https://github.com/datamaker/wekan

**Comment by gsachin1809** [comment]
due to company policy, if we want to work on 3.4x of mongoDB, what is solution for that for the same issue
