### ISSUE TITLE
Bug: Invitation mails from (sender) is not set.

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#937]
The "from" field is set in the Admin panel. But the invitationmails have no sender name.

**Comment by lkisme** [comment]
So, the "from" value in your setting is a name, instead of an email addr?
if so, make sure your smtp host allows you to do this.

**Comment by lkisme** [comment]
Are you using wekan version greater that 0.13?

Usually the from would be like `Thomas Anderson<thomas@anderson.com>`.

Just FYI, the value of the "from" field will be set into the MAIL_FROM env as before.

**Comment by NoodleBB** [comment]
> Are you using wekan version greater that 0.13?

Yes. It's 0.16.

> Usually the from would be like Thomas Anderson<thomas@anderson.com>.

Yes. In my case it would be Wekan Admin<admin@wekan.myhost.de>

> Just FYI, the value of the "from" field will be set into the MAIL_FROM env as before.

The name was set in the admin panel in the field "From".
