### ISSUE TITLE
Add Feature: Bulk creation of checklist entries

### ISSUE THREAD

**Issue by sonntagd** [wekan/wekan#938]
The checklists feature is great! I often have many things to do when working on a card. I have them all in separate lines of the clipboard like

```
task 1
task 2
task 3
```

I'd like to have a chance to paste them anywhere to create separate checklist entries out of them. Those lists often have 10 or much more items and it is very cumbersome to:
+ copy one task
+ click plus
+ paste
+ hit enter
for every entry.

**Comment by nelsonlyra** [comment]
Hi

What is the workflow associated ? have somewhere a checklist admin, and add a button "Import Checklist" in the card ?

What is the best UX/UI for this feature..
I have the same use case, but i'm not sure if i need a bulk creation of checklist or create cards from a model (which contains checklist)

**Comment by tugal** [comment]
Hi
What is the workflow associated? have somewhere a checklist admin, and add a button "Import Checklist" in the card ?
What is the best UX/UI for this feature..
I have the same use case, but i'm not sure if i need a bulk creation of checklist or create cards from a model (which contains checklist)

**Comment by sonntagd** [comment]
I think, an Import Checklist feature would be good if I could paste my plain tasks as described above and they were taken line-by-line as single tasks. Maybe we could make this a configurable behaviour of the "add task" input field.

**Comment by xet7** [comment]
Moved to #904
