### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by Neibaf94** [wekan/wekan#941]
Hi,
I'm using the socgen version of wekan "https://wekan.fr.world.socgen".
When I try to upload a file I receive the message "Null has been attached to the card".
Do you have any idea to fix the problem.
Thanks in advance for your help.
Regards.

**Comment by iAdanos** [comment]
I think, it's the same as #773.

If I'm right, file upload is working only with MongoDB 3.2.11

**Comment by xet7** [comment]
@Neibaf94 

https://github.com/wekan/wekan/issues/936#issuecomment-289113367
