### ISSUE TITLE
registration bug

### ISSUE THREAD

**Issue by schneivo77** [wekan/wekan#944]
Hi,

I found a bug.

On Wekan start page, when registering a new user, the user is registered but the error-message "Internal server error" shows up.

I use wekan with the docker image and just downloaded the "latest" one

**Comment by REJack** [comment]
That's happend if your SMTP is not correct configured.

**Comment by xet7** [comment]
@schneivo77 

Fixes for internal server error etc email bugs are merged, so source install works.

Docker builds are currently being actively fixed, and we are adding tags to Docker Hub in near future.

**Comment by schneivo77** [comment]
ok thanks!
