### ISSUE TITLE
The mail From: field should specify that it is an email address, not just a name

### ISSUE THREAD

**Issue by vampirefrog** [wekan/wekan#948]
In the admin page, as well as the [run-wekan.sh example](https://github.com/wekan/wekan/wiki/Install-and-Update#run-wekan-manually-if-youve-built-for-production) in the install guide, it is not specified what format the MAIL_FROM field needs to be in. Some mail servers generate an error when this From: field is not a correct email that they can find in their accounts list. The format is either: email@example.com, or Firstname Lastname <email@example.com>. Please add a help text or an extra field (one for name, one for email) to clarify this format. It has taken me 3 days of debugging and trials to figure this one out. Thanks

**Comment by xet7** [comment]
@vampirefrog 

Does Admin Panel not work for you for setting email options? See Wekan GitHub project readme.
