### ISSUE TITLE
Inviting new members in to the board

### ISSUE THREAD

**Issue by nata-g** [wekan/wekan#95]
Right now there is no way for new members to be invited using email validation. I think at this point this important entry point in to the app is missing. I was thinking may be this feature enhancement can be used to differentiate from Trello like having a two factor authentication using SMS(may be twilio api)  and Email for security. Also the UI can be separated in to two buttons "Search Member" and "Add Member" with each taking its own path, which is very different from what Trello is doing. My suggestion is if this accounts  management and validation  flow can be given a high priority now, (as the project is gaining lot of visibility and it is one of those low hanging fruits that can be easiy achieved),  then there would  be enough meat in to the argument that we are extending our own ideas and also when users evaluate libreboard, this would be the starting point of their entry in to the app and they would be seeing a different workflow from Trello from a first impression pov, which enhance the argument that we have our own ideas....

**Comment by mquandalle** [comment]
Invite by email was implemented in #422 and will be released [in the upcoming v0.10](https://github.com/wekan/wekan/issues/425).
