### ISSUE TITLE
Add Feature: Swimlanes (rows)

### ISSUE THREAD

**Issue by brylie** [wekan/wekan#955]
# Context
A common practice in Agile/Lean development is to group tasks by User Story. To facilitate the grouping, some Kanban tools support both **rows** and **columns**. The columns are commonly used to track task status/progress while rows provide a secondary grouping, such as:
- user story
- software component
- team

# Feature request
Allow Wekan boards to support multiple rows.

# Example media
![swimlanes on StackOverflow discussion](https://i.stack.imgur.com/XYnYV.jpg)

![kanban flow swimlanes](https://kanbanflow.com/img/screenshots/Swimlanes.png?b2a9d)

[Additional examples](https://www.google.fi/search?q=kanban+swimlane&tbm=isch)

**Comment by 76house** [comment]
Swimlanes are definitely neeed when you want to plan for more teams, projects or clients.

**Comment by brylie** [comment]
I am interested to know why this proposal has been downvoted. What are some of the down-sides to allowing boards to have swimlanes?

**Comment by xet7** [comment]
@76house @brylie 

Please ignore all trolls, spammers, downvotes etc in our issues, and discussion about those. All feature requests are considered good and can be implemented by those that wish to do so.
https://github.com/wekan/wekan/wiki/FAQ

**Comment by siepkes** [comment]
There are some interesting reads on the web as to why horizontal rows (swimlanes) can make sense:

* https://www.targetprocess.com/blog/2013/10/kanban-as-multiban/
* https://www.breeze.pm/blog/102-better-task-management-with-swimlanes

**Comment by xet7** [comment]
Someone could look how [swimlanes is implemented at Kanboard](https://kanboard.net/documentation/swimlanes) to get some ideas or use same libraries. Both Wekan and Kanboard use MIT license.

**Comment by jadbox** [comment]
Any update on this?

**Comment by xet7** [comment]
@jadbox 

There is [no bounties for this feature](https://www.bountysource.com/issues/43611228-add-feature-swimlanes-rows). More info [about bounties here](https://wekan.team).

At [old roadmap](https://github.com/wekan/wekan/wiki/Roadmap) and [new roadmap lists planned and in progress](https://github.com/wekan/wekan/projects/2) it seems that nobody is working on this feature.

This does not seem to be so important to have in near future.

**Comment by andresmanelli** [comment]
Hello, I have a basic draft of swimlanes for Wekan. Could someone try it out?

[Repo](https://github.com/andresmanelli/wekan)

What is implemented:
- Default swimlane when board is created
- Add swimlane
- Move cards between swimlanes

What is missing:
- Remove swimlane
- Rename swimlane
- Migrate to swimlane-enabled Wekan? Move cards to default swimlane?
- ...

**Note**: All lists are shared across swimlanes. They belong to the board. So if a new list is created, it appears automatically on all swimlanes.

### Screenshot
![seleccion_001](https://user-images.githubusercontent.com/7302217/35167278-a131bf44-fd33-11e7-9592-850eefa53fb5.png)

**Comment by xet7** [comment]
I did try that code. Suggestions:
- [Fix lint errors](https://github.com/wekan/wekan/wiki/Developer-Documentation#preventing-travis-ci-lint-errors-before-submitting-pull-requests). Warnings are OK, they don't need to be fixed.
- Layout change on board menu: horizontal/vertical/swimlane (vertical later), saved to board settings like board color, so it changes layout for all board members. If there are better official names for those, like horizontal=kanban and vertical=something else, then suggestions welcome.

That offtopic vertical layout is mentioned at separate [themes issue](https://github.com/wekan/wekan/issues/781#issuecomment-306123045) and looks similar like this Jira screenshot middle column. Vertical layout can be looked at later.

![jira-vertical](https://user-images.githubusercontent.com/15545/35172086-eba2b854-fd6e-11e7-884d-940b018c1948.png)

Comments, anybody?

**Comment by xet7** [comment]
Reminder to myself:
- Check my notes about other swimlanes functionality wishes I did get previously, add to here

**Comment by xet7** [comment]
Optional, maybe later additions. These partially are related to filtering.

Ability to hide:
- row
- column
- cards that have some label
- some users
- show only my own cards

These would need some logical UI design.

**Comment by xet7** [comment]
Today's release v0.65 includes Swimlanes part 1, please test Docker image at Quay.io:
https://github.com/wekan/wekan/releases

**Comment by scoubidoo** [comment]
thx for this feature, i don't know  how to delete a Swimlanes when i create 2 instead of 1 ?

**Comment by andresmanelli** [comment]
Hello @scoubidoo, I didn't get much free time to continue this development but it is in my TODO list.

What is missing: 
- Changing the name is not possible yet
- Sort capability
- Delete capability
- ...

For the moment there basic functionality, I hope I have more time this week to continue.

**Comment by scoubidoo** [comment]
@andresmanelli  ok no pb, i give you my feedback about this new feature 
Thx for giving your time to make a better Wekan :)

**Comment by naveengh** [comment]
Thanks.... I was also waiting for this.

An ability to add and hide swim lanes is great if you can add.

**Comment by andresmanelli** [comment]
Hello again,

@naveengh I just pushed a couple of commits that adds name edition and archive capability. Tests are welcome!

@xe7 Could you or someone check if including commiit https://github.com/andresmanelli/wekan/commit/42bc905c16d1c01cbf24f773d2d5224ccdbeba78 everything works fine? It works for me, but some people had issues, maybe because of cherry picking.

Anyway, I'll try to add the sort capabiliity in a couple of days.

**Comment by rzoss** [comment]
Hi Everybody
Wekan has a high potential to replace our painful Excel Kanban board. I'm looking forward to see the swimline feature in a stable release soon. But something we are using today in the Excel and paper board is missing in all known kanban web boards. I just explain how we use the boards:

Each Project (or several similar Projects) have their own board. They plan development tasks with a lengt of 1-4 weeks. Each development task creates a swimline on the board with subtaks (should be around one day of work). The subtasks are then moved from "backlog" to "in progress" to "in review" and finally "done". 

What we need now is the possibility to add some Attibutes to the Swimline. At least the following attributes are needed:

- Task or Incident number (would be good to create a link)
- Title of the Task or Incident
- Responsible user(s)
- Planned Effort (orignial estimation)
- Planned Effort (actual estimation)
- Start date
- End date

The best would be to add the possibility to define custom optional attributes for the swimlines. This would fullfill everyones requirements thougt configuration.

**Comment by xet7** [comment]
BTW, @andresmanelli is doing excellent work with adding swimlanes, adding features, fixing bugs etc. I really recommend all users of swimlanes feature to add to bounty at https://www.bountysource.com/issues/43611228-add-feature-swimlanes-rows because there is none yet, and feature request list just keeps growing. More info about bounties at https://wekan.team .

@rzoss 

Wekan does not have any separate development and stable releases. There is only newest release, which currently is v0.70. We rely on Wekan users to add GitHub issues about bugs and feature requests.

I don't know what you mean by attributes to Swimline. Wekan cards already have:
- Markdown for card text, formatting, links, etc
- Responsible members can be added to cards
- Spent time/Overtime
- Start Date
- Due Date
- Gogs integration, similar workflows could be used https://github.com/wekan/wekan-gogs

Wekan will sometime also have
- Custom Fields, it's not finished or merged yet #807
- LDAP #119 , it's not finished or merged yet
- Calendar, so Start/Due dates can be seen on calendar, and dragged around #808 

So I don't know are you asking something that does not exist yet. Please add more details, screenshot mockups etc about what you would like to have.

**Comment by naveengh** [comment]
@andresmanelli 

Thank you. I’m looking forward to test that feature once I get Wekan installed. Thanks for working on it and I will get back with testing results.

@xet7 , I hope you have this feature on latest build. Thank you

**Comment by xet7** [comment]
@naveengh 

Yes, swimlanes is included in latest Wekan release.

**Comment by rzoss** [comment]
BTW you all do a great job here. There is so much flow in this project. I'm still impressed ...

Back to my idea to have attributes for the swimline. I assume somethin similar to this:

![image](https://user-images.githubusercontent.com/11527399/35818097-6f2c0134-0a9f-11e8-8765-e61f90bc2f15.png)

The first line is the so called identifier for the swimline. This means in our case a development task in a life cycle management tool. I have now decided to install wekan in the latest version in our environment and will use it as shown in the print screen above. 

@andresmanelli 
Another feature for swimline which would be great is the possibility to move them up and down to rearrange the priorities.

**Comment by xet7** [comment]
@andresmanelli 

Thanks for update! I added it to Roadmap https://github.com/wekan/wekan/projects/2

Please do what is most important to you, there are other contributors that can look at those issues. Do not take any pressure about Wekan contributions, afaik you did not have any bounties yet, so we are just grateful what you did already. There is no requirement to spend additional time.

**Comment by andresmanelli** [comment]
Hello @xet7 @naveengh , commit https://github.com/andresmanelli/wekan/commit/37c94622e476f50bf2387bc8b140454d66200e78 adds reordering capability to swimlanes.

@xet7 could you include this one and the one mentioned in #1487 ?

**Comment by andresmanelli** [comment]
@xet7 commit https://github.com/andresmanelli/wekan/commit/8d2839f0c3429a21b33bf8333cb2f20a275bc596 fix lists reorder in lists view. I don't remember any more where this was discussed.

**Comment by andresmanelli** [comment]
Hello, I just added two commits:

- https://github.com/andresmanelli/wekan/commit/2f0309bc6bd6ba4b742591c0f2b9e280c32e1305 fixes (for me at least) #1458  and #1484
- https://github.com/andresmanelli/wekan/commit/ac7d44f8a8d809cd94ed5ef3640473f34c72403b fixes #1481 partially. The swimlane should be scrolled to the top in order to see properly the card details. But at least limits the details height to the board-canvas height so overall height doesn't get too big.

@xet7 could you try those?

**Comment by andresmanelli** [comment]
Actually, I think the first commit up there also fixes #1497 (alignment). Maybe #1497 should consider only what the OP said: 

> I'd like to see the list titles only appear once at the top of the list and more distinct vertical lines dividing lists.

**Comment by andresmanelli** [comment]
Maybe #1521 is related to these commits?

**Comment by johnleeming** [comment]
These fixes are a great improvement but don't fully fix the alignment problems I put in #1497.  I think that the swimlanes header needs to be set to a fixed width in wekan/client/components/swimlanes/swimlanes.styl, e.g. line 42 change "min-width: 30px;" to "width: 40px".  40 is a minimum, 50 or 60 might be better.  

Ideal would be to make it editable via the swim lane header menu but that's beyond me.

to make the dividers more visible I've also done the following, but that's a personal taste issue I think. 
 client/components/lists/list.styl
12 -  border-left: 1px solid darken(white, 20%)
13 -  border-bottom: 1px solid #CCC
12  +  border-left: 1px solid darken(white, 40%)
13 +  border-bottom: 1px solid #AAA

client/components/swimlanes/swimlanes.styl
32 -    border-bottom: 1px solid #CCC
32 +    border-bottom: 1px solid #AAA

**Comment by andresmanelli** [comment]
@johnleeming I tried your changes to *.styl files. I personally think 30% is a good compromise as 40% seems a little too dark. Can you try this? :

```diff
diff --git a/client/components/lists/list.styl b/client/components/lists/list.styl
index fa32ff6..746e59b 100644
--- a/client/components/lists/list.styl
+++ b/client/components/lists/list.styl
@@ -9,8 +9,8 @@
   // Even if this background color is the same as the body we can't leave it
   // transparent, because that won't work during a list drag.
   background: darken(white, 13%)
-  border-left: 1px solid darken(white, 20%)
-  border-bottom: 1px solid #CCC
+  border-left: 1px solid darken(white, 30%)
+  border-bottom: 1px solid darken(white, 30%)
   padding: 0
   float: left
 
diff --git a/client/components/swimlanes/swimlanes.styl b/client/components/swimlanes/swimlanes.styl
index 29054d3..78f2441 100644
--- a/client/components/swimlanes/swimlanes.styl
+++ b/client/components/swimlanes/swimlanes.styl
@@ -29,7 +29,7 @@
     flex-direction: row;
     flex: 0 0 50px;
     padding-bottom: 30px;
-    border-bottom: 1px solid #CCC
+    border-bottom: 1px solid darken(white, 30%)
 
     .swimlane-header
       writing-mode: vertical-rl;
```

And about the header width, I didn't understand why to increase the width? Do you see the headers unaligned?

**Comment by johnleeming** [comment]
I'm happy with the 30%.
The problem I had was that the swimlane headers were adapting their width to the length of the titles and this was throwing out the alignment of all the lists.  see this exaggerated example:
![previousvariableheader](https://user-images.githubusercontent.com/13801070/37245561-f50cdd80-2491-11e8-924a-4507677bcb61.PNG)
my hack is to fix the width of the swimlane header - I think including "min width =" over-rides the flex properties 0 0 - teh exact width could be different.  I tried to make it an editable variable in the swimlanes action menu but that's beyond me.  My fix does lead to  the possibility of ugly word wrapping:
![myfixedheader](https://user-images.githubusercontent.com/13801070/37245600-8179b310-2492-11e8-941c-7f0f12367427.PNG)

**Comment by andresmanelli** [comment]
@johnleeming Isn't this related to #1526?

**Comment by johnleeming** [comment]
could be - I'm using Vivaldi browser which is based on the Chromium engine

**Comment by xet7** [comment]
Swimlanes is already in Wekan.

**Comment by ivan-paleo** [comment]
I'm new to Wekan so please excuse me if this is basic or if this has been discussed somewhere else.

In all screenshots I have seen so far, swimlane titles are always shown as row headers. In my case, they are located on top of all the lists (see screenshot).
![screenshot](https://user-images.githubusercontent.com/12525997/96092541-501a8f80-0ecb-11eb-9651-eaf39ae399d4.PNG)

I am not admin on the server so maybe this is a setting I cannot change myself, but if it is, I cannot find how to change it.

Additionally, I haven't found an extensive documentation about Wekan, and in particular, info about swimlanes is difficult to find. Are you considering adding this?

**Comment by xet7** [comment]
@ivan-paleo 

Swimlanes was changed from vertical to horizontal at #1688 . I can not be changed to vertical.

There already is Swimlanes documentation at wiki https://github.com/wekan/wekan/wiki right menu Features topic, direct link:
https://github.com/wekan/wekan/wiki/Swimlanes

**Comment by xet7** [comment]
@ivan-paleo 

Also see:
- https://en.wikipedia.org/wiki/Swim_lane
- https://en.wikipedia.org/wiki/Kanban_(development)

**Comment by xet7** [comment]
@ivan-paleo 

There will be later Collapse Swimlane feature (maybe also Collapse List) #2107

**Comment by ivan-paleo** [comment]
@xet7 Thanks a lot for the links! I indeed overlooked it under "Features", my bad...

The collapse feature would indeed be a very good compromise (or the best of both worlds!)

**Comment by xet7** [comment]
@ivan-paleo 

Yes, that Collapse feature [has already been paid and is at Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/j9MtNahuvqs5ZQeEA) so it will be in Wekan sometime this year I think.
