### ISSUE TITLE
Register user link for fresh instance

### ISSUE THREAD

**Issue by brylie** [wekan/wekan#956]
When starting a fresh instance of Wekan, and navigating to the base route, the only thing visible is *Create Board* button. However, the user cannot create a board until they have registered.

For anonymous users, consider showing a link to 'register' or 'sign-in' on the base route/template.

**Comment by xet7** [comment]
@brylie 

Would this prevent viewing public boards?

**Comment by brylie** [comment]
Probably not. I.e. there is already a topbar with sign in link. I will prepare a screenshot shortly.

**Comment by brylie** [comment]
My apologies, I cannot duplicate on `devel` branch.
