### ISSUE TITLE
Link the repository with the Docker Hub

### ISSUE THREAD

**Issue by ncarlier** [wekan/wekan#96]
As the project has a Dockerfile, it would be great to link this repository with the [Docker Hub](http://hub.docker.com) . Users will be able to pull and run the container from anywhere.

**Comment by Telemakhos** [comment]
It would be nice to have a phusion-passenger docker container... It's one of the few hosts that support sticky sessions (required for meteor to scale)...

https://github.com/phusion/passenger-docker

**Comment by mquandalle** [comment]
Done.
