### ISSUE TITLE
Add Feature: Show version

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#963]
You can't see which version are you running. It would be helpful to have a place (may be in the admin panel) where you can see the version and other informations. With all that stuff that could be useful for debugging. 

Wekan: v0.17
Node: v0.10.43
Mongo: 2.6.12
OS: CentOS 6.8
etc.

This is one of the first features i implement, when i write software. A pane, button or switch that collects and shows all (hopefully relevant) informations. :relaxed:

**Comment by schneivo77** [comment]
Would be really nice if this would be implemented.
