### ISSUE TITLE
Bug: Release contains wrong javascript version 

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#969]
The [latest release version](https://github.com/wekan/wekan/releases/download/v0.17/wekan-0.17.tar.gz) contains wrong javascript version. This lead to the double slashes bug.

Reproduceable steps:
The [Manual Installation](https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps).

Wekan: 0.17 release version.

**Comment by xet7** [comment]
Moved to #962
