### ISSUE TITLE
Add Feature: Date format localization and selection

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#971]
The dates aren't localized. When switching the language (for example to french, german or spain), the date formats doesn't change. It would be great if the dates change with the selection of the language or if you could select it individually in a popup.

The both most common **[intl. date formats](https://en.wikipedia.org/wiki/Date_format_by_country)** are: Little-endian (dd.mm.yyyy) and Big-endian (yyyy-mm-dd) (ISO format). With slash or dot separators.

Maybe this could be useful: **[Moments.js](https://momentjs.com/)** (MIT Lizence)
`meteor add momentjs:moment`

**Comment by xet7** [comment]
Moved to #838
