### ISSUE TITLE
Bug: Subpath is missing in admin panel

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#974]
v.0.18: When opening the Admin panel, the subpath-part (...etc.com/**wekan**) of the URL gets lost. It seems the admin panel does not use the ROOT_URL. This leads to a  404 _"The requested URL /setting was not found on this server."_ .

When typing the missing subpath-component (...etc.com/wekan/setting) manually in the URL it works.

**Comment by NoodleBB** [comment]
This bug is the same: #962

**Comment by xet7** [comment]
@NoodleBB 

Is this same or different bug?

**Comment by NoodleBB** [comment]
I belive i could be the same bug.

**Comment by xet7** [comment]
Moved to #962
