### ISSUE TITLE
"Link to this card" doesn't exist.

### ISSUE THREAD

**Issue by kaitoan2000** [wekan/wekan#975]
Hi team,
It seem doesn't exist with wekan v.0.18.
I test with v.0.10.1, it's working correctly, but not now.
http://prntscr.com/es6c7p
Regards,
AN

**Comment by NoodleBB** [comment]
+1

**Comment by anlx-sw** [comment]
+1 confirmed using v.0.18

**Comment by xet7** [comment]
@BaobabCoder 

Do you have time to check does link to this card or list work, and possibly fix so link works?
