### ISSUE TITLE
Cannot clone wekan on Windows

### ISSUE THREAD

**Issue by bbenoist** [wekan/wekan#977]
```text
> git clone https://github.com/wekan/wekan.git
Cloning into 'wekan'...
remote: Counting objects: 5825, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 5825 (delta 8), reused 0 (delta 0), pack-reused 5798R
Receiving objects: 100% (5825/5825), 2.88 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (3890/3890), done.
error: cannot create submodule directory packages/kadira:flow-router
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by Kerenok** [comment]
Same thing here : the Windows version of git seems to have problems with the colon character in a file name.

Cloning works fine using the Cygwin git but it changes the colon character to something else.

**Comment by xet7** [comment]
@bbenoist 

I don't know is that submodule really needed, as I already needed to remove it at #962
We'll see if it could be removed.

We are currently in progress of fixing #928 and doing upgrade #788

After that, Windows build instructions at https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows may need also updating.

**Comment by Serubin** [comment]
Windows cannot handle the colon character in paths. I'm sure meteor has a way to get around this, perhaps we need to look at way to change the path name for the submodule based on if the system is windows or unix?

**Comment by neooleg** [comment]
Unfortunately, Cygwin didn't help me as @Kerenok mentioned.

I've deleted submodule on nix machine pushed and then it

**Comment by neooleg** [comment]
@xet7 

I can make a PR for removing problematic submodule.

Will you merge the PR?

**Comment by xet7** [comment]
@neooleg 

Does Wekan work without it? I have not tested that yet.

**Comment by Serubin** [comment]
@neooleg. It will work but the double slash problem will be back for you.

**Comment by neooleg** [comment]
@xet7, yes it works in general. In particular, I didn't test carefully _each_ feature, but most features work as expected.

**Comment by xet7** [comment]
I will not merge anything that reintroduces double slash bug.

**Comment by Serubin** [comment]
@neooleg Removing the submodule will introduce the double slash bug.

**Comment by neooleg** [comment]
Got it. However, I didn't catch it since submodule was removed on both Windows 7 x64 and Mac OS X.

**Comment by neooleg** [comment]
OK, let me to test Wekan carefully including #962.

Anyway, current issue blocks using (developing) Wekan on Windows, so it's major enough in terms for contribution.

**Comment by xet7** [comment]
Now git clone works on Windows :)  You can check [Linux from source](https://github.com/wekan/wekan/wiki/Install-and-Update#install-and-build-wekan) instructions to see what other repos are needed.
