### ISSUE TITLE
wekan official binaries release (0.17 and 0.18) won't run on Ubuntu 14.04

### ISSUE THREAD

**Issue by Nebelwolf** [wekan/wekan#978]
Hi,

I tried to run the version from the binary release: https://github.com/wekan/wekan/releases/tag/v0.18

after npm install I get the error:
```
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
/home/builder/wekan/wekan/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/builder/wekan/wekan/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/home/builder/wekan/wekan/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/home/builder/wekan/wekan/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/builder/wekan/wekan/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/home/builder/wekan/wekan/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```
When I run the release on a Ubuntu 16.04 it starts with no errors and I can access the Webinterface.
Is a newer libstdc++ version now mandatory or do we have to build it from source?

**Ubuntu 14.04**
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Ubuntu 16.04**:
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by Nebelwolf** [comment]
The nodejs version is 0.10.48

**Comment by xet7** [comment]
@Nebelwolf 

I have been doing all my development on Ubuntu 16.04 based systems for a long time.

On Ubuntu 14.04 it currently requires build from source.

**Comment by Nebelwolf** [comment]
Sorry for commenting on a closed one but then you should update the docs. That Ubuntu 16.04 is a requirement.

**Comment by xet7** [comment]
@Nebelwolf 

Do you mean compiling from source on 14.04 does not work? Or do we need releases for Ubuntu 14.04 ?

**Comment by xet7** [comment]
@Nebelwolf 

I will sometime test Wekan on Ubuntu 14.04 and add support for it.

We are currently in process of upgrading to Meteor 1.4 and Node v4.

**Comment by Nebelwolf** [comment]
I mean that running the binary release from ["Installing with Official Binaries"](https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-releases) does not state that it's minimum requirement is Ubuntu 16.04. Had running it on 14.04 before and 14.04 is supported until April 2019.

---
I'm trying now to build it from source on 14.04 but getting some errors. If I cant sort out that the problem lies on my end I open another issue for it.

**Comment by xet7** [comment]
@Nebelwolf 

Please keep your errors in this issue. I will also keep this open until I have fixed this.

**Comment by Nebelwolf** [comment]
@xet7 

Building it from source on Ubuntu 14.04 works. Also I can start and use that binary on 16.04.

I updated the Wiki to give a note about the Official Binaries problem on 14.04.

**Comment by xet7** [comment]
@Nebelwolf 

Thanks!

**Comment by NoodleBB** [comment]
> We are currently in process of upgrading to Meteor 1.4 and Node v4.

When looking on the LTS schedule i have a question: The node 4 lts maintenance ends in little less than 12 months. Why not upgrading to node 6 lts?

**Comment by xet7** [comment]
@NoodleBB 

Node v6 upgrade is not OK yet afaik, see #788

**Comment by NoodleBB** [comment]
Ah. I understand. Meteor is the problem.

**Comment by xet7** [comment]
Today's Wekan release v0.19 has been built on Ubuntu 14.04 and should work ok.
