### ISSUE TITLE
having issue in fetching lists of different board

### ISSUE THREAD

**Issue by faisalahmed** [wekan/wekan#979]
Hi,

i am having issue in following code 

`     var boardId = Session.get('selectedBoard') ? Session.get('selectedBoard') : Session.get('currentBoard')
      var selectedBoardLists = Boards.findOne({ '_id' : boardId}).lists();
      var list = selectedBoardLists.fetch();`

where board id would be any other board which user selects or currentBoard ... usually it doesn't return any results on some of boardId which exists in mongoDB ... its only working for currentBoard

but when i open up all the boards at least once and than again run above code in my helper function of "moveCardPopup" template fetch lists correctly from mongoDB

i am testing above code with AdminUser who has access to all the boards and also done testing by changing permission between public and private but it didn't worked

**Comment by xet7** [comment]
@faisalahmed 

Is this for some feature you are developing now?

**Comment by faisalahmed** [comment]
@xet7 

yes, i am currently making feature of move and copy cards between different boards

**Comment by xet7** [comment]
@faisalahmed 

Have you looked at existing pull request, that currently does not build properly?
https://github.com/wekan/wekan/pull/446

**Comment by xet7** [comment]
@faisalahmed 

That pull request may have some stuff that is not needed.

**Comment by xet7** [comment]
Moved to #797

**Comment by faisalahmed** [comment]
i have read all the code related to the pull request you have shared https://github.com/wekan/wekan/pull/446

my issue is different ... as i am facing issue in fetching data from DB when i send different BoardId which is not opened yet

**Comment by xet7** [comment]
@faisalahmed 

Does cardClone code from #797 have something that helps you? It's originally linked to this:
https://github.com/hsduk/wekan/tree/plugin-simple-timer/client/components/plugins

and probably same code is also at devel branch:
https://github.com/hsduk/wekan/tree/devel/client/components/plugins

**Comment by xet7** [comment]
@faisalahmed 

Can you share your current in-progress code of move and copy cards as pull request or GitHub gist?

**Comment by xet7** [comment]
Move and copy cards feature has already been added to Wekan.
