### ISSUE TITLE
Organizing and displaying data by properly nesting and filtering by tags

### ISSUE THREAD

**Issue by JamborJan** [wekan/wekan#98]
There is a discussion about differentiation and USPs ongoing here: https://github.com/libreboard/libreboard/issues/92. So here is an idea I have not yet seen good implemented.

My idea of a perfect information and gtd world would be more or less like this:
- I have a huge pile of information pieces (cards which can contain text, links, attachments). Only for reference: my Evernote has currently 1822 notes
- I would like to have a time view: what to do when. I like the Kanban board approach here but thats not all.
- I also would have a topic e.g. project or product where I can group the tasks
- I also would like to add persons e.g. which things are assigned with my boss, my employees etc.

This sounds super complicated but it is in fact not if the tagging is done smart and also visualized smart. Actually thats where most apps fail.

My suggestion looks like my following mockup shows. I’m not a designer but thats what I would love to see added in LibreBoard

![mockup_jja_4_libreboard](https://cloud.githubusercontent.com/assets/7508960/5842536/ec5f4dc0-a1a5-11e4-9d6e-79df2bcedc73.png)

**Comment by mquandalle** [comment]
Hello, have you already tried the filtered view?

**Comment by JamborJan** [comment]
I'm running the sandstorm app. Is it possible that this view is not yet available there?

**Comment by mquandalle** [comment]
Oh yes, this was implemented recently (last week) and I haven't already published a new release. You can test this feature on http://libreboard.com or wait until early next week for the sandstorm release :-)

**Comment by JamborJan** [comment]
Cool cool, is the attachment feature also available then in the sandstorm app?

Thx.

**Comment by mquandalle** [comment]
Yes, the attachment feature will land in v0.8 early next week.

**Comment by JamborJan** [comment]
I have thought a bit more about it and I think the following would be pretty cool. Again I'm not a designer so I did a quick mockup which should only show the function not a final UI design.
- Of course there should be the sidebar where the tags could be the listed
- The tags could be nested in multiple levels (2 levels only shown in examples below)
- Multi selecting tags would filter the current view of cards accordingly
- There should be e.g. tabs to create new views
- A view is basically an amount of lanes where every lane can be assigned to one tag and only cards with that tag are shown
- Moving one card from one lane to another would remove the tag where it was before and add the tag where it is dropped
- All views can always be additionally filtered by selecting on or more tags in the side bar

Issue: as this is very dynamically a manual ordering of cards in the lanes is not possible as far as I see. So there could be a sorting only by creation date, last update desc or asc.

Examples
![01_all](https://cloud.githubusercontent.com/assets/7508960/5890828/3fadf518-a470-11e4-94e1-7d88a395cb77.png)
Here you see the tag list on the left side, nothing is selected. On top you see 3 views which can be renamed. The lanes have each one tag, in the example the time tags.

![02_timing projects](https://cloud.githubusercontent.com/assets/7508960/5890830/3fae78d0-a470-11e4-8467-d29ff3445e73.png)
Here you see that one project tag is clicked in the left sidebar. The view is filtered and shows only cards with that project tag. 

![03_who today](https://cloud.githubusercontent.com/assets/7508960/5890829/3fae3e24-a470-11e4-9769-9bfc772742ef.png)
This example shows a view where name tags are building the lanes. Additionally the today tag on the sidebar is clicked so I see all tasks from all persons today. When I move one card from one lane to another the name tag  where it has been taken will be removed and the tag where it has been dropped will be added.

![04_projects today me](https://cloud.githubusercontent.com/assets/7508960/5890827/3fad791c-a470-11e4-9b87-add7c17ae80b.png)
This example shows a view where project tags build the lanes. Furthermore there are two tags selected in the left sidebar. The view is filtered accordingly.

I think this would be an awesome productivity feature and would make it easy to stay on top of a huge pile of tasks / cards. It would be also very flexible. You are working in development, no matter make a view with the upcoming sprints and move easy tasks from one to another. You are planning to build a new house? Make a view with the different companies involved. And so.

Furthermore all other commercial products no matter what they are named can go f***k themselves.

**Comment by hsduk** [comment]
:+1: 

I think this would be very powerful for two scopes:
- system (across all boards and cards) - but only for certain enabled users
- user (across all boards and cards user has access)

Tags can be auto generated:

Board Names
List Names
Card Names
User Names
Board Owners
Board Members
Card Members
Comment Members
Labels
Has Attachments
Has Attachment Types
Has no Attachments

This would cover many of the usecases and issues requesting a search feature too using a freetext search and tag generator - e.g. click 'Add Custom Tag' -> enter freetext to search -> all wekan objects containing text are tagged and added to the list of available tags, with a share this custom tag option too.

**Comment by xet7** [comment]
Wekan currently has:
- Swimlanes

And upcoming is:
- Children/Nested tasks https://github.com/wekan/wekan/pull/1723
- Linked Boards and Linked Cards https://github.com/wekan/wekan/pull/1592
