### ISSUE TITLE
Exception while invoking method 'ATCreateUserServer' Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by banchuanyu** [wekan/wekan#987]
I use docker deploy wekan, and set MAIL_URL in docker-compose.xml env, and when I register, I got this error, but I could login by the username that I just registed

> wekan-app  | Exception while invoking method 'ATCreateUserServer' Error: getaddrinfo ENOTFOUND
> wekan-app  |     at Object.Future.wait (/build/programs/server/node_modules/fibers/future.js:449:15)
> wekan-app  |     at smtpSend (packages/email/email.js:89:1)
> wekan-app  |     at Object.Email.send (packages/email/email.js:192:1)
> wekan-app  |     at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:797:9)
> wekan-app  |     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/lib/server_methods.js:119:1)
> wekan-app  |     at packages/check/match.js:107:1
> wekan-app  |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> wekan-app  |     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
> wekan-app  |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
> wekan-app  |     at packages/ddp-server/livedata_server.js:711:19
> wekan-app  |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> wekan-app  |     at packages/ddp-server/livedata_server.js:709:40
> wekan-app  |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> wekan-app  |     at packages/ddp-server/livedata_server.js:707:46
> wekan-app  |     at tryCallTwo (/build/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5)
> wekan-app  |     at doResolve (/build/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13)
> wekan-app  |     - - - - -
> wekan-app  |     at errnoException (dns.js:37:11)
> wekan-app  |     at Object.onanswer [as oncomplete] (dns.js:126:16)

**Comment by stephenmoloney** [comment]
Please state versions being used -- this looks like an old build?

**Comment by banchuanyu** [comment]
@stephenmoloney version v0.18，latest version in dockerhub 
https://hub.docker.com/r/mquandalle/wekan/

**Comment by banchuanyu** [comment]
@stephenmoloney I just saw your changelog v0.11.1，and use the admin panel solved the problem.
I'm sorry to have wasted your time.
