### ISSUE TITLE
Wekan docker image segfaults with newer kernels

### ISSUE THREAD

**Issue by thypon** [wekan/wekan#988]
```
$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.8
 Git commit:   v17.04.0-ce
 Built:        Thu Apr  6 16:27:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   v17.04.0-ce
 Built:        Thu Apr  6 16:27:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ uname -a
Linux pompel.me 4.10.8_2 #1 SMP PREEMPT Mon Apr 3 15:23:46 UTC 2017 x86_64 GNU/Linux
```
The problem seems to be related to https://github.com/CentOS/sig-cloud-instance-images/issues/62 the new `vsyscall=none` policy

**Comment by stephenmoloney** [comment]
I don't know how to fix this issue.

same issue on the `alpine image` at wekan-launchpad?

**Comment by thypon** [comment]
The problem is with the `debian:wheezy` glibc: switching to alpine or a more recent debian should do the trick.

**Comment by stephenmoloney** [comment]
@thypon If you get a chance, does [this](https://github.com/wekan/wekan/pull/992) fix this issue?

**Comment by thypon** [comment]
It fixes the problem. Thank you :) :+1:
