### ISSUE TITLE
Minor bug: Invitation URL in case of self-registration disabled.

### ISSUE THREAD

**Issue by khba** [wekan/wekan#993]
Hello, 

In case of self-registration disabled, the user receives an invitation mail with an invitation code + a link to the sign-up page http://127.0.0.1/sign-up. But when he clicks on the link, he arrives on the sign-up page without a field where to write his invitation code: there are only the fields for Username, Email and Password.  For the "Invitation Code" field to appear, he has to click on "sign-in" which redirects him to the sign-in page http://127.0.0.1/sign-in, then to click again on "register" which redirects him back in sign-up page http://127.0.0.1/sign-up and only then the  "Invitation Code" field become available.

The simpler solution would be to modify the URL given in the invitation email to point directly to http://127.0.0.1/sign-in instead of http://127.0.0.1/sign-up :  where is the code to change that ?? 

The right solution would be to change the sign-up page so that if self-registration is disabled, the user arrives directly on the sign-up page with an "Invitation Code" field available.

For info I'm using the docker image wekanteam/wekan:meteor-1.4

Thanks,

**Comment by Braintelligence** [comment]
Same problem! Thanks for writing it up!

**Comment by xet7** [comment]
@khba 

Are you using Wekan only locally? Otherwise ROOT_URL needs to be setup to Wekan full url like https://example.com or https://example.com/wekan .

**Comment by Braintelligence** [comment]
I've set ROOT_URL to https://my.domain.com

**Comment by khba** [comment]
@xet7 my ROOT_URL has been set correctly  the IP 127.0.0.1 is just an example, team is able to access and create boards remotely etc, everything works fine except that little annoying detail at registration. 

Where in the code can I change/customize the content of the mail sent by wekan during invitation ?

**Comment by alexgleason** [comment]
This is kind of a bad bug. I just invited like 10 people to a board and all of them were confused and couldn't get on.

**Comment by xet7** [comment]
@khba 

Invitation email text is in source code, I think it's not localized yet. You can recursively search for it for example in linux:

```
cd wekan

find . | xargs grep 'some text in invitiation here' -sl
```

**Comment by khba** [comment]
@xet7 I am using the wekan docker image, is the source code available there?

**Comment by xet7** [comment]
It would be easier to clone Wekan github repo, make change there, and submit pull request.

**Comment by alexgleason** [comment]
Thanks for the fix!

**Comment by LyR33x** [comment]
Same here! Snap needs to be updated i think. Its not fixed in snap so far.
