### ISSUE TITLE
Sort cards in List by Dates/Labels/CustomFields

### ISSUE THREAD

**Issue by ghost** [wekan/wekan#995]
Hello, 

We have a need linked to the filter idea (#935) which is sorting.

ex :
- Sorting by tags (we use priority colors : P1 is red, P2 is orange, P3 is yellow and would like a sort by priority) ;
- Sorting by dates (beginning, deadline, etc.) ;

It could be an option of a column or a global option like filter.

Thanks

**Comment by duelle** [comment]
This would be an interesting feature. Most interesting for us would be the sorting of columns by due date.

**Comment by xet7** [comment]
Related #808 that is now in progress.

This issue has lower priority.

**Comment by frakman1** [comment]
@xet7 [This](https://github.com/wekan/wekan/issues/808) feature appears to be about making a Calendar View. However, it doesn't let you sort the tasks by due date as intended by this issue (I think that was the intent anyway). What I mean is that it would be nice to allow the user to sort the cards in the list view by `Due Date` the same way that Trello does. See screenshot below:

![image](https://user-images.githubusercontent.com/5826484/48951016-11604280-ef0b-11e8-8ed3-63d3372c245a.png)


![image](https://user-images.githubusercontent.com/5826484/48951066-31900180-ef0b-11e8-971e-678abef64585.png)

**Comment by Lievenvdh** [comment]
Hello, I have a question and hope that it is posted in the correct blog. I am new in WeKan, and not a programmer.. I have created in WeKan a custom field "ReleaseDate" referring to the release date of a software tool. Within the cards, I'm also using the standard "due date' field.  I want to create a filter with as result a of all cards with release date 02-07-2020 (7 february 2020) and a due date later then 24-01-2020 (24 January). I could not find a solution here, but on the datameer blogs, I could find the follwing information (https://support.datameer.com/hc/en-us/community/posts/115019362323-Advanced-Filtering-Greater-Than-Date). Following this,:

1) To have all cards with custom field "ReleaseDate' equal to 02-07-2020, I first have to click 'Releasedate' in the filterlist and then in advanced filter write: #DateColumn == ASDATE("02-07-2020";"MM-dd-yyyy"). As I am not a programmer, I also tried #ReleaseDate == ASDATE("02-07-2020";"MM-dd-yyyy"). Both of them not working. If I follow the explanation in WeKan about advanced filter, I should enter 'ReleaseDate' == "02-07-2020", but also this doesn't work.
2) To have all cards with due date 02-07-2020 (7 february), I tried an equal filter, again without result.

Could anyone help or direct me to the correct page? Thanks!

**Comment by xet7** [comment]
@Lievenvdh 

When in Wekan you click Filter, there is instructions at bottom of that right filter sidebar.

But I think currently Filter is broken #2712 

Someone could look where the bug is.

**Comment by xet7** [comment]
That datameer is different product that Wekan, Wekan has different syntax in Filter.

**Comment by Lievenvdh** [comment]
okay, thanks for your reply. I have read the explanation on the bottom and was trying to do as wirtten, so in my case: for the custom field 'ReleaseDate', the filter would be:
        'ReleaseDate' == '02-07-2020'
However, without result. I hope the problem with advance filter will be solved soon!
Thanks for the remark about datameer and its different syntax.

**Comment by AH-SWG** [comment]
Am I right to assume that sorting isn't going to happen anytime soon? It's quite a big feature to be missing and this doesn't seem to have moved anywhere since it was requested six years ago.

**Comment by xet7** [comment]
WeKan already has Sort list feature.

**Comment by C6lDubois** [comment]
Hello,  could you please explain me were I can find this sort list feature ? 
 
My team and I tried to use Rules to "kind of" sort cards by label but it doesn't work how we expected.  I just  opened an issue here https://github.com/wekan/wekan/issues/4898

Are Rules the only way to sort a list ?

Thank you
